extern __imp_?ClearLogFile@@YAKPEAX@Z:PANYARGS
?ClearLogFile@@YAKPEAX@Z TEXTEQU <__imp_?ClearLogFile@@YAKPEAX@Z>
extern __imp_?FindAccelerometerDevice@@YAEPEAPEAX@Z:PANYARGS
?FindAccelerometerDevice@@YAEPEAPEAX@Z TEXTEQU <__imp_?FindAccelerometerDevice@@YAEPEAPEAX@Z>
extern __imp_?GetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z:PANYARGS
?GetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z TEXTEQU <__imp_?GetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z>
extern __imp_?GetRealTimeXYZ@@YAKPEAXPEAGPEAU_OVERLAPPED@@@Z:PANYARGS
?GetRealTimeXYZ@@YAKPEAXPEAGPEAU_OVERLAPPED@@@Z TEXTEQU <__imp_?GetRealTimeXYZ@@YAKPEAXPEAGPEAU_OVERLAPPED@@@Z>
extern __imp_?IsSoftwareEnabled@@YAKPEAXPEAE@Z:PANYARGS
?IsSoftwareEnabled@@YAKPEAXPEAE@Z TEXTEQU <__imp_?IsSoftwareEnabled@@YAKPEAXPEAE@Z>
extern __imp_?NotifyAccelerometerAboutPower@@YAKPEAXK@Z:PANYARGS
?NotifyAccelerometerAboutPower@@YAKPEAXK@Z TEXTEQU <__imp_?NotifyAccelerometerAboutPower@@YAKPEAXK@Z>
extern __imp_?RegisterForAccelerometerDisabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PANYARGS
?RegisterForAccelerometerDisabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z TEXTEQU <__imp_?RegisterForAccelerometerDisabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z>
extern __imp_?RegisterForAccelerometerDiskCountChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PANYARGS
?RegisterForAccelerometerDiskCountChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z TEXTEQU <__imp_?RegisterForAccelerometerDiskCountChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z>
extern __imp_?RegisterForAccelerometerEnabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PANYARGS
?RegisterForAccelerometerEnabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z TEXTEQU <__imp_?RegisterForAccelerometerEnabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z>
extern __imp_?RegisterForAccelerometerParameterChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PANYARGS
?RegisterForAccelerometerParameterChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z TEXTEQU <__imp_?RegisterForAccelerometerParameterChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z>
extern __imp_?RegisterForAccelerometerShockEndEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PANYARGS
?RegisterForAccelerometerShockEndEvent@@YAPEAXPEAUHWND__@@PEAX@Z TEXTEQU <__imp_?RegisterForAccelerometerShockEndEvent@@YAPEAXPEAUHWND__@@PEAX@Z>
extern __imp_?RegisterForAccelerometerShockSignaledEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PANYARGS
?RegisterForAccelerometerShockSignaledEvent@@YAPEAXPEAUHWND__@@PEAX@Z TEXTEQU <__imp_?RegisterForAccelerometerShockSignaledEvent@@YAPEAXPEAUHWND__@@PEAX@Z>
extern __imp_?SetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z:PANYARGS
?SetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z TEXTEQU <__imp_?SetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z>
