extern __imp_??0CDecryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PANYARGS
??0CDecryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z TEXTEQU <__imp_??0CDecryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>
extern __imp_??0CEncryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PANYARGS
??0CEncryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z TEXTEQU <__imp_??0CEncryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>
extern __imp_??1CDecryptedData@@QEAA@XZ:PANYARGS
??1CDecryptedData@@QEAA@XZ TEXTEQU <__imp_??1CDecryptedData@@QEAA@XZ>
extern __imp_??1CEncryptedData@@QEAA@XZ:PANYARGS
??1CEncryptedData@@QEAA@XZ TEXTEQU <__imp_??1CEncryptedData@@QEAA@XZ>
extern __imp_?Decrypt@CEncryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PANYARGS
?Decrypt@CEncryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z TEXTEQU <__imp_?Decrypt@CEncryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>
extern __imp_?Encrypt@CDecryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PANYARGS
?Encrypt@CDecryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z TEXTEQU <__imp_?Encrypt@CDecryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>
extern __imp_ACCAPENCDecryptFile:PANYARGS
ACCAPENCDecryptFile TEXTEQU <__imp_ACCAPENCDecryptFile>
extern __imp_ACCAPENCEncryptFile:PANYARGS
ACCAPENCEncryptFile TEXTEQU <__imp_ACCAPENCEncryptFile>
extern __imp_PKCS5_PBES2_SHA256_AES256CBC_Decrypt:PANYARGS
PKCS5_PBES2_SHA256_AES256CBC_Decrypt TEXTEQU <__imp_PKCS5_PBES2_SHA256_AES256CBC_Decrypt>
extern __imp_PKCS5_PBES2_SHA256_AES256CBC_Encrypt:PANYARGS
PKCS5_PBES2_SHA256_AES256CBC_Encrypt TEXTEQU <__imp_PKCS5_PBES2_SHA256_AES256CBC_Encrypt>
extern __imp_PKCS5_PBKDF2_HMAC_SHA256:PANYARGS
PKCS5_PBKDF2_HMAC_SHA256 TEXTEQU <__imp_PKCS5_PBKDF2_HMAC_SHA256>
extern __imp_acGetEKUFromCertificate:PANYARGS
acGetEKUFromCertificate TEXTEQU <__imp_acGetEKUFromCertificate>
extern __imp_acGetMaximumEncryptedSize:PANYARGS
acGetMaximumEncryptedSize TEXTEQU <__imp_acGetMaximumEncryptedSize>
extern __imp_acIsCertOKForPKILogon:PANYARGS
acIsCertOKForPKILogon TEXTEQU <__imp_acIsCertOKForPKILogon>
extern __imp_acProfileAddRuntimeParameter:PANYARGS
acProfileAddRuntimeParameter TEXTEQU <__imp_acProfileAddRuntimeParameter>
extern __imp_acProfileCheckSignature:PANYARGS
acProfileCheckSignature TEXTEQU <__imp_acProfileCheckSignature>
extern __imp_acProfileClose:PANYARGS
acProfileClose TEXTEQU <__imp_acProfileClose>
extern __imp_acProfileExportFromHandle:PANYARGS
acProfileExportFromHandle TEXTEQU <__imp_acProfileExportFromHandle>
extern __imp_acProfileFreeString:PANYARGS
acProfileFreeString TEXTEQU <__imp_acProfileFreeString>
extern __imp_acProfileGetAttribute:PANYARGS
acProfileGetAttribute TEXTEQU <__imp_acProfileGetAttribute>
extern __imp_acProfileGetAttributeValue:PANYARGS
acProfileGetAttributeValue TEXTEQU <__imp_acProfileGetAttributeValue>
extern __imp_acProfileIsSectionExists:PANYARGS
acProfileIsSectionExists TEXTEQU <__imp_acProfileIsSectionExists>
extern __imp_acProfileLoadFile:PANYARGS
acProfileLoadFile TEXTEQU <__imp_acProfileLoadFile>
extern __imp_acProfileOpen:PANYARGS
acProfileOpen TEXTEQU <__imp_acProfileOpen>
