extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_??0ACDelegateSubscriber@@QEAA@AEBV0@@Z:PANYARGS
??0ACDelegateSubscriber@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ACDelegateSubscriber@@QEAA@AEBV0@@Z>
extern __imp_??0ACDelegateSubscriber@@QEAA@XZ:PANYARGS
??0ACDelegateSubscriber@@QEAA@XZ TEXTEQU <__imp_??0ACDelegateSubscriber@@QEAA@XZ>
extern __imp_??1ACDelegateSubscriber@@UEAA@XZ:PANYARGS
??1ACDelegateSubscriber@@UEAA@XZ TEXTEQU <__imp_??1ACDelegateSubscriber@@UEAA@XZ>
extern __imp_??4ACDelegateSubscriber@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ACDelegateSubscriber@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ACDelegateSubscriber@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_7ACDelegateSubscriber@@6B@:PANYARGS
??_7ACDelegateSubscriber@@6B@ TEXTEQU <__imp_??_7ACDelegateSubscriber@@6B@>
extern __imp_?GetEvent@ACDelegateSubscriber@@QEAAHXZ:PANYARGS
?GetEvent@ACDelegateSubscriber@@QEAAHXZ TEXTEQU <__imp_?GetEvent@ACDelegateSubscriber@@QEAAHXZ>
extern __imp_?GetEventHandle@ACDelegateSubscriber@@QEAAPEAXXZ:PANYARGS
?GetEventHandle@ACDelegateSubscriber@@QEAAPEAXXZ TEXTEQU <__imp_?GetEventHandle@ACDelegateSubscriber@@QEAAPEAXXZ>
extern __imp_?GetEventTable@ACDelegateSubscriber@@QEAAPEAPEAXXZ:PANYARGS
?GetEventTable@ACDelegateSubscriber@@QEAAPEAPEAXXZ TEXTEQU <__imp_?GetEventTable@ACDelegateSubscriber@@QEAAPEAPEAXXZ>
extern __imp_?Subscribe@ACDelegateSubscriber@@IEAAHH@Z:PANYARGS
?Subscribe@ACDelegateSubscriber@@IEAAHH@Z TEXTEQU <__imp_?Subscribe@ACDelegateSubscriber@@IEAAHH@Z>
extern __imp_?UnSubscribe@ACDelegateSubscriber@@IEAAHXZ:PANYARGS
?UnSubscribe@ACDelegateSubscriber@@IEAAHXZ TEXTEQU <__imp_?UnSubscribe@ACDelegateSubscriber@@IEAAHXZ>
