extern __imp_EditAuditInfo:PANYARGS
EditAuditInfo TEXTEQU <__imp_EditAuditInfo>
extern __imp_EditOwnerInfo:PANYARGS
EditOwnerInfo TEXTEQU <__imp_EditOwnerInfo>
extern __imp_EditPermissionInfo:PANYARGS
EditPermissionInfo TEXTEQU <__imp_EditPermissionInfo>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_FMExtensionProcW:PANYARGS
FMExtensionProcW TEXTEQU <__imp_FMExtensionProcW>
extern __imp_SedDiscretionaryAclEditor:PANYARGS
SedDiscretionaryAclEditor TEXTEQU <__imp_SedDiscretionaryAclEditor>
extern __imp_SedSystemAclEditor:PANYARGS
SedSystemAclEditor TEXTEQU <__imp_SedSystemAclEditor>
extern __imp_SedTakeOwnership:PANYARGS
SedTakeOwnership TEXTEQU <__imp_SedTakeOwnership>
