extern __imp_aclogClose:PANYARGS
aclogClose TEXTEQU <__imp_aclogClose>
extern __imp_aclogLog:PANYARGS
aclogLog TEXTEQU <__imp_aclogLog>
extern __imp_aclogLogBin:PANYARGS
aclogLogBin TEXTEQU <__imp_aclogLogBin>
extern __imp_aclogSetDate:PANYARGS
aclogSetDate TEXTEQU <__imp_aclogSetDate>
extern __imp_aclogSetFile:PANYARGS
aclogSetFile TEXTEQU <__imp_aclogSetFile>
extern __imp_aclogSetModuleName:PANYARGS
aclogSetModuleName TEXTEQU <__imp_aclogSetModuleName>
extern __imp_aclogSetOutput:PANYARGS
aclogSetOutput TEXTEQU <__imp_aclogSetOutput>
extern __imp_aclogTrace:PANYARGS
aclogTrace TEXTEQU <__imp_aclogTrace>
extern __imp_aclogTraceBin:PANYARGS
aclogTraceBin TEXTEQU <__imp_aclogTraceBin>
