extern __imp_CreateSecurityPage:PANYARGS
CreateSecurityPage TEXTEQU <__imp_CreateSecurityPage>
extern __imp_EditSecurity:PANYARGS
EditSecurity TEXTEQU <__imp_EditSecurity>
extern __imp_aclui_ordinal3:PANYARGS
aclui_ordinal3 TEXTEQU <__imp_aclui_ordinal3>
extern __imp_aclui_ordinal4:PANYARGS
aclui_ordinal4 TEXTEQU <__imp_aclui_ordinal4>
extern __imp_aclui_ordinal5:PANYARGS
aclui_ordinal5 TEXTEQU <__imp_aclui_ordinal5>
extern __imp_aclui_ordinal6:PANYARGS
aclui_ordinal6 TEXTEQU <__imp_aclui_ordinal6>
extern __imp_aclui_ordinal7:PANYARGS
aclui_ordinal7 TEXTEQU <__imp_aclui_ordinal7>
extern __imp_aclui_ordinal8:PANYARGS
aclui_ordinal8 TEXTEQU <__imp_aclui_ordinal8>
extern __imp_aclui_ordinal9:PANYARGS
aclui_ordinal9 TEXTEQU <__imp_aclui_ordinal9>
extern __imp_aclui_ordinal10:PANYARGS
aclui_ordinal10 TEXTEQU <__imp_aclui_ordinal10>
extern __imp_aclui_ordinal11:PANYARGS
aclui_ordinal11 TEXTEQU <__imp_aclui_ordinal11>
extern __imp_aclui_ordinal12:PANYARGS
aclui_ordinal12 TEXTEQU <__imp_aclui_ordinal12>
extern __imp_aclui_ordinal13:PANYARGS
aclui_ordinal13 TEXTEQU <__imp_aclui_ordinal13>
extern __imp_aclui_ordinal14:PANYARGS
aclui_ordinal14 TEXTEQU <__imp_aclui_ordinal14>
extern __imp_aclui_ordinal15:PANYARGS
aclui_ordinal15 TEXTEQU <__imp_aclui_ordinal15>
extern __imp_IID_ISecurityInformation:PANYARGS
IID_ISecurityInformation TEXTEQU <__imp_IID_ISecurityInformation>
