extern __imp_??0Card@@QEAA@AEBV0@@Z:PANYARGS
??0Card@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0Card@@QEAA@AEBV0@@Z>
extern __imp_??0Card@@QEAA@PEAVSmartCardConnection@@@Z:PANYARGS
??0Card@@QEAA@PEAVSmartCardConnection@@@Z TEXTEQU <__imp_??0Card@@QEAA@PEAVSmartCardConnection@@@Z>
extern __imp_??0Card@@QEAA@XZ:PANYARGS
??0Card@@QEAA@XZ TEXTEQU <__imp_??0Card@@QEAA@XZ>
extern __imp_??0CardAccessor@@QEAA@AEBV0@@Z:PANYARGS
??0CardAccessor@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CardAccessor@@QEAA@AEBV0@@Z>
extern __imp_??0CardAccessor@@QEAA@XZ:PANYARGS
??0CardAccessor@@QEAA@XZ TEXTEQU <__imp_??0CardAccessor@@QEAA@XZ>
extern __imp_??0CardCriteria@@QEAA@AEBV0@@Z:PANYARGS
??0CardCriteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CardCriteria@@QEAA@AEBV0@@Z>
extern __imp_??0CardCriteria@@QEAA@XZ:PANYARGS
??0CardCriteria@@QEAA@XZ TEXTEQU <__imp_??0CardCriteria@@QEAA@XZ>
extern __imp_??0Criteria@@QEAA@AEBV0@@Z:PANYARGS
??0Criteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0Criteria@@QEAA@AEBV0@@Z>
extern __imp_??0Criteria@@QEAA@XZ:PANYARGS
??0Criteria@@QEAA@XZ TEXTEQU <__imp_??0Criteria@@QEAA@XZ>
extern __imp_??0ObjectAccessor@@QEAA@AEBV0@@Z:PANYARGS
??0ObjectAccessor@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ObjectAccessor@@QEAA@AEBV0@@Z>
extern __imp_??0ObjectAccessor@@QEAA@XZ:PANYARGS
??0ObjectAccessor@@QEAA@XZ TEXTEQU <__imp_??0ObjectAccessor@@QEAA@XZ>
extern __imp_??0PIN@@QEAA@AEBV0@@Z:PANYARGS
??0PIN@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0PIN@@QEAA@AEBV0@@Z>
extern __imp_??0PIN@@QEAA@PEAVSmartCardConnection@@@Z:PANYARGS
??0PIN@@QEAA@PEAVSmartCardConnection@@@Z TEXTEQU <__imp_??0PIN@@QEAA@PEAVSmartCardConnection@@@Z>
extern __imp_??0PIN@@QEAA@XZ:PANYARGS
??0PIN@@QEAA@XZ TEXTEQU <__imp_??0PIN@@QEAA@XZ>
extern __imp_??0PINAccessor@@QEAA@AEBV0@@Z:PANYARGS
??0PINAccessor@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0PINAccessor@@QEAA@AEBV0@@Z>
extern __imp_??0PINAccessor@@QEAA@XZ:PANYARGS
??0PINAccessor@@QEAA@XZ TEXTEQU <__imp_??0PINAccessor@@QEAA@XZ>
extern __imp_??0PINCriteria@@QEAA@AEBV0@@Z:PANYARGS
??0PINCriteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0PINCriteria@@QEAA@AEBV0@@Z>
extern __imp_??0PINCriteria@@QEAA@XZ:PANYARGS
??0PINCriteria@@QEAA@XZ TEXTEQU <__imp_??0PINCriteria@@QEAA@XZ>
extern __imp_??0PINLogicalCriteria@@QEAA@AEBV0@@Z:PANYARGS
??0PINLogicalCriteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0PINLogicalCriteria@@QEAA@AEBV0@@Z>
extern __imp_??0PINLogicalCriteria@@QEAA@W4PINLogicalCriteriaType@@PEAEI@Z:PANYARGS
??0PINLogicalCriteria@@QEAA@W4PINLogicalCriteriaType@@PEAEI@Z TEXTEQU <__imp_??0PINLogicalCriteria@@QEAA@W4PINLogicalCriteriaType@@PEAEI@Z>
extern __imp_??0Reader@@QEAA@AEBV0@@Z:PANYARGS
??0Reader@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0Reader@@QEAA@AEBV0@@Z>
extern __imp_??0Reader@@QEAA@PEAD@Z:PANYARGS
??0Reader@@QEAA@PEAD@Z TEXTEQU <__imp_??0Reader@@QEAA@PEAD@Z>
extern __imp_??0ReaderManager@@QEAA@AEBV0@@Z:PANYARGS
??0ReaderManager@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ReaderManager@@QEAA@AEBV0@@Z>
extern __imp_??0ReaderManager@@QEAA@XZ:PANYARGS
??0ReaderManager@@QEAA@XZ TEXTEQU <__imp_??0ReaderManager@@QEAA@XZ>
extern __imp_??0SDKCardServiceFactory@@QEAA@AEBV0@@Z:PANYARGS
??0SDKCardServiceFactory@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0SDKCardServiceFactory@@QEAA@AEBV0@@Z>
extern __imp_??0SDKCardServiceFactory@@QEAA@XZ:PANYARGS
??0SDKCardServiceFactory@@QEAA@XZ TEXTEQU <__imp_??0SDKCardServiceFactory@@QEAA@XZ>
extern __imp_??0SKI@@QEAA@AEBV0@@Z:PANYARGS
??0SKI@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0SKI@@QEAA@AEBV0@@Z>
extern __imp_??0SKI@@QEAA@PEAVSmartCardConnection@@@Z:PANYARGS
??0SKI@@QEAA@PEAVSmartCardConnection@@@Z TEXTEQU <__imp_??0SKI@@QEAA@PEAVSmartCardConnection@@@Z>
extern __imp_??0SKI@@QEAA@XZ:PANYARGS
??0SKI@@QEAA@XZ TEXTEQU <__imp_??0SKI@@QEAA@XZ>
extern __imp_??0SKIAccessor@@QEAA@AEBV0@@Z:PANYARGS
??0SKIAccessor@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0SKIAccessor@@QEAA@AEBV0@@Z>
extern __imp_??0SKIAccessor@@QEAA@XZ:PANYARGS
??0SKIAccessor@@QEAA@XZ TEXTEQU <__imp_??0SKIAccessor@@QEAA@XZ>
extern __imp_??0SKICriteria@@QEAA@AEBV0@@Z:PANYARGS
??0SKICriteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0SKICriteria@@QEAA@AEBV0@@Z>
extern __imp_??0SKICriteria@@QEAA@XZ:PANYARGS
??0SKICriteria@@QEAA@XZ TEXTEQU <__imp_??0SKICriteria@@QEAA@XZ>
extern __imp_??0SKILogicalCriteria@@QEAA@AEBV0@@Z:PANYARGS
??0SKILogicalCriteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0SKILogicalCriteria@@QEAA@AEBV0@@Z>
extern __imp_??0SKILogicalCriteria@@QEAA@W4SKILogicalCriteriaType@@PEAEI@Z:PANYARGS
??0SKILogicalCriteria@@QEAA@W4SKILogicalCriteriaType@@PEAEI@Z TEXTEQU <__imp_??0SKILogicalCriteria@@QEAA@W4SKILogicalCriteriaType@@PEAEI@Z>
extern __imp_??0SmartCardConnection@@QEAA@AEBV0@@Z:PANYARGS
??0SmartCardConnection@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0SmartCardConnection@@QEAA@AEBV0@@Z>
extern __imp_??0SmartCardConnection@@QEAA@XZ:PANYARGS
??0SmartCardConnection@@QEAA@XZ TEXTEQU <__imp_??0SmartCardConnection@@QEAA@XZ>
extern __imp_??0SmartCardConnectionManager@@QEAA@AEBV0@@Z:PANYARGS
??0SmartCardConnectionManager@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0SmartCardConnectionManager@@QEAA@AEBV0@@Z>
extern __imp_??0SmartCardConnectionManager@@QEAA@XZ:PANYARGS
??0SmartCardConnectionManager@@QEAA@XZ TEXTEQU <__imp_??0SmartCardConnectionManager@@QEAA@XZ>
extern __imp_??0Static@@QEAA@AEBV0@@Z:PANYARGS
??0Static@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0Static@@QEAA@AEBV0@@Z>
extern __imp_??0Static@@QEAA@PEAVSmartCardConnection@@@Z:PANYARGS
??0Static@@QEAA@PEAVSmartCardConnection@@@Z TEXTEQU <__imp_??0Static@@QEAA@PEAVSmartCardConnection@@@Z>
extern __imp_??0Static@@QEAA@XZ:PANYARGS
??0Static@@QEAA@XZ TEXTEQU <__imp_??0Static@@QEAA@XZ>
extern __imp_??0StaticAccessor@@QEAA@AEBV0@@Z:PANYARGS
??0StaticAccessor@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0StaticAccessor@@QEAA@AEBV0@@Z>
extern __imp_??0StaticAccessor@@QEAA@XZ:PANYARGS
??0StaticAccessor@@QEAA@XZ TEXTEQU <__imp_??0StaticAccessor@@QEAA@XZ>
extern __imp_??0StaticCriteria@@QEAA@AEBV0@@Z:PANYARGS
??0StaticCriteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0StaticCriteria@@QEAA@AEBV0@@Z>
extern __imp_??0StaticCriteria@@QEAA@XZ:PANYARGS
??0StaticCriteria@@QEAA@XZ TEXTEQU <__imp_??0StaticCriteria@@QEAA@XZ>
extern __imp_??0StaticLogicalCriteria@@QEAA@AEBV0@@Z:PANYARGS
??0StaticLogicalCriteria@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0StaticLogicalCriteria@@QEAA@AEBV0@@Z>
extern __imp_??0StaticLogicalCriteria@@QEAA@W4StaticLogicalCriteriaType@@PEAEI@Z:PANYARGS
??0StaticLogicalCriteria@@QEAA@W4StaticLogicalCriteriaType@@PEAEI@Z TEXTEQU <__imp_??0StaticLogicalCriteria@@QEAA@W4StaticLogicalCriteriaType@@PEAEI@Z>
extern __imp_??1Card@@UEAA@XZ:PANYARGS
??1Card@@UEAA@XZ TEXTEQU <__imp_??1Card@@UEAA@XZ>
extern __imp_??1CardAccessor@@UEAA@XZ:PANYARGS
??1CardAccessor@@UEAA@XZ TEXTEQU <__imp_??1CardAccessor@@UEAA@XZ>
extern __imp_??1CardCriteria@@UEAA@XZ:PANYARGS
??1CardCriteria@@UEAA@XZ TEXTEQU <__imp_??1CardCriteria@@UEAA@XZ>
extern __imp_??1Criteria@@UEAA@XZ:PANYARGS
??1Criteria@@UEAA@XZ TEXTEQU <__imp_??1Criteria@@UEAA@XZ>
extern __imp_??1ObjectAccessor@@UEAA@XZ:PANYARGS
??1ObjectAccessor@@UEAA@XZ TEXTEQU <__imp_??1ObjectAccessor@@UEAA@XZ>
extern __imp_??1PIN@@UEAA@XZ:PANYARGS
??1PIN@@UEAA@XZ TEXTEQU <__imp_??1PIN@@UEAA@XZ>
extern __imp_??1PINAccessor@@UEAA@XZ:PANYARGS
??1PINAccessor@@UEAA@XZ TEXTEQU <__imp_??1PINAccessor@@UEAA@XZ>
extern __imp_??1PINCriteria@@UEAA@XZ:PANYARGS
??1PINCriteria@@UEAA@XZ TEXTEQU <__imp_??1PINCriteria@@UEAA@XZ>
extern __imp_??1PINLogicalCriteria@@UEAA@XZ:PANYARGS
??1PINLogicalCriteria@@UEAA@XZ TEXTEQU <__imp_??1PINLogicalCriteria@@UEAA@XZ>
extern __imp_??1Reader@@UEAA@XZ:PANYARGS
??1Reader@@UEAA@XZ TEXTEQU <__imp_??1Reader@@UEAA@XZ>
extern __imp_??1ReaderManager@@UEAA@XZ:PANYARGS
??1ReaderManager@@UEAA@XZ TEXTEQU <__imp_??1ReaderManager@@UEAA@XZ>
extern __imp_??1SDKCardServiceFactory@@UEAA@XZ:PANYARGS
??1SDKCardServiceFactory@@UEAA@XZ TEXTEQU <__imp_??1SDKCardServiceFactory@@UEAA@XZ>
extern __imp_??1SKI@@UEAA@XZ:PANYARGS
??1SKI@@UEAA@XZ TEXTEQU <__imp_??1SKI@@UEAA@XZ>
extern __imp_??1SKIAccessor@@UEAA@XZ:PANYARGS
??1SKIAccessor@@UEAA@XZ TEXTEQU <__imp_??1SKIAccessor@@UEAA@XZ>
extern __imp_??1SKICriteria@@UEAA@XZ:PANYARGS
??1SKICriteria@@UEAA@XZ TEXTEQU <__imp_??1SKICriteria@@UEAA@XZ>
extern __imp_??1SKILogicalCriteria@@UEAA@XZ:PANYARGS
??1SKILogicalCriteria@@UEAA@XZ TEXTEQU <__imp_??1SKILogicalCriteria@@UEAA@XZ>
extern __imp_??1SmartCardConnection@@UEAA@XZ:PANYARGS
??1SmartCardConnection@@UEAA@XZ TEXTEQU <__imp_??1SmartCardConnection@@UEAA@XZ>
extern __imp_??1SmartCardConnectionManager@@UEAA@XZ:PANYARGS
??1SmartCardConnectionManager@@UEAA@XZ TEXTEQU <__imp_??1SmartCardConnectionManager@@UEAA@XZ>
extern __imp_??1Static@@UEAA@XZ:PANYARGS
??1Static@@UEAA@XZ TEXTEQU <__imp_??1Static@@UEAA@XZ>
extern __imp_??1StaticAccessor@@UEAA@XZ:PANYARGS
??1StaticAccessor@@UEAA@XZ TEXTEQU <__imp_??1StaticAccessor@@UEAA@XZ>
extern __imp_??1StaticCriteria@@UEAA@XZ:PANYARGS
??1StaticCriteria@@UEAA@XZ TEXTEQU <__imp_??1StaticCriteria@@UEAA@XZ>
extern __imp_??1StaticLogicalCriteria@@UEAA@XZ:PANYARGS
??1StaticLogicalCriteria@@UEAA@XZ TEXTEQU <__imp_??1StaticLogicalCriteria@@UEAA@XZ>
extern __imp_??4Card@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4Card@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4Card@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CardAccessor@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CardAccessor@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CardAccessor@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CardCriteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CardCriteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CardCriteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4Criteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4Criteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4Criteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4ObjectAccessor@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ObjectAccessor@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ObjectAccessor@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4PIN@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4PIN@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4PIN@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4PINAccessor@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4PINAccessor@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4PINAccessor@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4PINCriteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4PINCriteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4PINCriteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4PINLogicalCriteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4PINLogicalCriteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4PINLogicalCriteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4Reader@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4Reader@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4Reader@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4ReaderManager@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ReaderManager@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ReaderManager@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SDKCardServiceFactory@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4SDKCardServiceFactory@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4SDKCardServiceFactory@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SKI@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4SKI@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4SKI@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SKIAccessor@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4SKIAccessor@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4SKIAccessor@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SKICriteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4SKICriteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4SKICriteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SKILogicalCriteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4SKILogicalCriteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4SKILogicalCriteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SmartCardConnection@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4SmartCardConnection@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4SmartCardConnection@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SmartCardConnectionManager@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4SmartCardConnectionManager@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4SmartCardConnectionManager@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4Static@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4Static@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4Static@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4StaticAccessor@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4StaticAccessor@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4StaticAccessor@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4StaticCriteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4StaticCriteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4StaticCriteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4StaticLogicalCriteria@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4StaticLogicalCriteria@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4StaticLogicalCriteria@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_7Card@@6B@:PANYARGS
??_7Card@@6B@ TEXTEQU <__imp_??_7Card@@6B@>
extern __imp_??_7CardAccessor@@6B@:PANYARGS
??_7CardAccessor@@6B@ TEXTEQU <__imp_??_7CardAccessor@@6B@>
extern __imp_??_7CardCriteria@@6B@:PANYARGS
??_7CardCriteria@@6B@ TEXTEQU <__imp_??_7CardCriteria@@6B@>
extern __imp_??_7Criteria@@6B@:PANYARGS
??_7Criteria@@6B@ TEXTEQU <__imp_??_7Criteria@@6B@>
extern __imp_??_7ObjectAccessor@@6B@:PANYARGS
??_7ObjectAccessor@@6B@ TEXTEQU <__imp_??_7ObjectAccessor@@6B@>
extern __imp_??_7PIN@@6B@:PANYARGS
??_7PIN@@6B@ TEXTEQU <__imp_??_7PIN@@6B@>
extern __imp_??_7PINAccessor@@6B@:PANYARGS
??_7PINAccessor@@6B@ TEXTEQU <__imp_??_7PINAccessor@@6B@>
extern __imp_??_7PINCriteria@@6B@:PANYARGS
??_7PINCriteria@@6B@ TEXTEQU <__imp_??_7PINCriteria@@6B@>
extern __imp_??_7PINLogicalCriteria@@6B@:PANYARGS
??_7PINLogicalCriteria@@6B@ TEXTEQU <__imp_??_7PINLogicalCriteria@@6B@>
extern __imp_??_7Reader@@6B@:PANYARGS
??_7Reader@@6B@ TEXTEQU <__imp_??_7Reader@@6B@>
extern __imp_??_7ReaderManager@@6B@:PANYARGS
??_7ReaderManager@@6B@ TEXTEQU <__imp_??_7ReaderManager@@6B@>
extern __imp_??_7SDKCardServiceFactory@@6B@:PANYARGS
??_7SDKCardServiceFactory@@6B@ TEXTEQU <__imp_??_7SDKCardServiceFactory@@6B@>
extern __imp_??_7SKI@@6B@:PANYARGS
??_7SKI@@6B@ TEXTEQU <__imp_??_7SKI@@6B@>
extern __imp_??_7SKIAccessor@@6B@:PANYARGS
??_7SKIAccessor@@6B@ TEXTEQU <__imp_??_7SKIAccessor@@6B@>
extern __imp_??_7SKICriteria@@6B@:PANYARGS
??_7SKICriteria@@6B@ TEXTEQU <__imp_??_7SKICriteria@@6B@>
extern __imp_??_7SKILogicalCriteria@@6B@:PANYARGS
??_7SKILogicalCriteria@@6B@ TEXTEQU <__imp_??_7SKILogicalCriteria@@6B@>
extern __imp_??_7SmartCardConnection@@6B@:PANYARGS
??_7SmartCardConnection@@6B@ TEXTEQU <__imp_??_7SmartCardConnection@@6B@>
extern __imp_??_7SmartCardConnectionManager@@6B@:PANYARGS
??_7SmartCardConnectionManager@@6B@ TEXTEQU <__imp_??_7SmartCardConnectionManager@@6B@>
extern __imp_??_7Static@@6B@:PANYARGS
??_7Static@@6B@ TEXTEQU <__imp_??_7Static@@6B@>
extern __imp_??_7StaticAccessor@@6B@:PANYARGS
??_7StaticAccessor@@6B@ TEXTEQU <__imp_??_7StaticAccessor@@6B@>
extern __imp_??_7StaticCriteria@@6B@:PANYARGS
??_7StaticCriteria@@6B@ TEXTEQU <__imp_??_7StaticCriteria@@6B@>
extern __imp_??_7StaticLogicalCriteria@@6B@:PANYARGS
??_7StaticLogicalCriteria@@6B@ TEXTEQU <__imp_??_7StaticLogicalCriteria@@6B@>
extern __imp_?CreateCardCriteria@@YAPEAVCardCriteria@@XZ:PANYARGS
?CreateCardCriteria@@YAPEAVCardCriteria@@XZ TEXTEQU <__imp_?CreateCardCriteria@@YAPEAVCardCriteria@@XZ>
extern __imp_?CreatePINLogicalCriteria@@YAPEAVPINLogicalCriteria@@W4PINLogicalCriteriaType@@PEAEI@Z:PANYARGS
?CreatePINLogicalCriteria@@YAPEAVPINLogicalCriteria@@W4PINLogicalCriteriaType@@PEAEI@Z TEXTEQU <__imp_?CreatePINLogicalCriteria@@YAPEAVPINLogicalCriteria@@W4PINLogicalCriteriaType@@PEAEI@Z>
extern __imp_?CreateSDKCardServiceFactory@@YAPEAVSDKCardServiceFactory@@XZ:PANYARGS
?CreateSDKCardServiceFactory@@YAPEAVSDKCardServiceFactory@@XZ TEXTEQU <__imp_?CreateSDKCardServiceFactory@@YAPEAVSDKCardServiceFactory@@XZ>
extern __imp_?CreateSKILogicalCriteria@@YAPEAVSKILogicalCriteria@@W4SKILogicalCriteriaType@@PEAEI@Z:PANYARGS
?CreateSKILogicalCriteria@@YAPEAVSKILogicalCriteria@@W4SKILogicalCriteriaType@@PEAEI@Z TEXTEQU <__imp_?CreateSKILogicalCriteria@@YAPEAVSKILogicalCriteria@@W4SKILogicalCriteriaType@@PEAEI@Z>
extern __imp_?CreateStaticLogicalCriteria@@YAPEAVStaticLogicalCriteria@@W4StaticLogicalCriteriaType@@PEAEI@Z:PANYARGS
?CreateStaticLogicalCriteria@@YAPEAVStaticLogicalCriteria@@W4StaticLogicalCriteriaType@@PEAEI@Z TEXTEQU <__imp_?CreateStaticLogicalCriteria@@YAPEAVStaticLogicalCriteria@@W4StaticLogicalCriteriaType@@PEAEI@Z>
extern __imp_?GetCriteriaType@PINLogicalCriteria@@QEAA?AW4PINLogicalCriteriaType@@XZ:PANYARGS
?GetCriteriaType@PINLogicalCriteria@@QEAA?AW4PINLogicalCriteriaType@@XZ TEXTEQU <__imp_?GetCriteriaType@PINLogicalCriteria@@QEAA?AW4PINLogicalCriteriaType@@XZ>
extern __imp_?GetCriteriaType@SKILogicalCriteria@@QEAA?AW4SKILogicalCriteriaType@@XZ:PANYARGS
?GetCriteriaType@SKILogicalCriteria@@QEAA?AW4SKILogicalCriteriaType@@XZ TEXTEQU <__imp_?GetCriteriaType@SKILogicalCriteria@@QEAA?AW4SKILogicalCriteriaType@@XZ>
extern __imp_?GetCriteriaType@StaticLogicalCriteria@@QEAA?AW4StaticLogicalCriteriaType@@XZ:PANYARGS
?GetCriteriaType@StaticLogicalCriteria@@QEAA?AW4StaticLogicalCriteriaType@@XZ TEXTEQU <__imp_?GetCriteriaType@StaticLogicalCriteria@@QEAA?AW4StaticLogicalCriteriaType@@XZ>
extern __imp_?GetCriteriaValue@PINLogicalCriteria@@QEAAPEAEXZ:PANYARGS
?GetCriteriaValue@PINLogicalCriteria@@QEAAPEAEXZ TEXTEQU <__imp_?GetCriteriaValue@PINLogicalCriteria@@QEAAPEAEXZ>
extern __imp_?GetCriteriaValue@SKILogicalCriteria@@QEAAPEAEXZ:PANYARGS
?GetCriteriaValue@SKILogicalCriteria@@QEAAPEAEXZ TEXTEQU <__imp_?GetCriteriaValue@SKILogicalCriteria@@QEAAPEAEXZ>
extern __imp_?GetCriteriaValue@StaticLogicalCriteria@@QEAAPEAEXZ:PANYARGS
?GetCriteriaValue@StaticLogicalCriteria@@QEAAPEAEXZ TEXTEQU <__imp_?GetCriteriaValue@StaticLogicalCriteria@@QEAAPEAEXZ>
extern __imp_?GetCriteriaValueLen@PINLogicalCriteria@@QEAAIXZ:PANYARGS
?GetCriteriaValueLen@PINLogicalCriteria@@QEAAIXZ TEXTEQU <__imp_?GetCriteriaValueLen@PINLogicalCriteria@@QEAAIXZ>
extern __imp_?GetCriteriaValueLen@SKILogicalCriteria@@QEAAIXZ:PANYARGS
?GetCriteriaValueLen@SKILogicalCriteria@@QEAAIXZ TEXTEQU <__imp_?GetCriteriaValueLen@SKILogicalCriteria@@QEAAIXZ>
extern __imp_?GetCriteriaValueLen@StaticLogicalCriteria@@QEAAIXZ:PANYARGS
?GetCriteriaValueLen@StaticLogicalCriteria@@QEAAIXZ TEXTEQU <__imp_?GetCriteriaValueLen@StaticLogicalCriteria@@QEAAIXZ>
extern __imp_?GetName@CardCriteria@@UEAAPEADXZ:PANYARGS
?GetName@CardCriteria@@UEAAPEADXZ TEXTEQU <__imp_?GetName@CardCriteria@@UEAAPEADXZ>
extern __imp_?GetName@PINLogicalCriteria@@UEAAPEADXZ:PANYARGS
?GetName@PINLogicalCriteria@@UEAAPEADXZ TEXTEQU <__imp_?GetName@PINLogicalCriteria@@UEAAPEADXZ>
extern __imp_?GetName@SKILogicalCriteria@@UEAAPEADXZ:PANYARGS
?GetName@SKILogicalCriteria@@UEAAPEADXZ TEXTEQU <__imp_?GetName@SKILogicalCriteria@@UEAAPEADXZ>
extern __imp_?GetName@StaticLogicalCriteria@@UEAAPEADXZ:PANYARGS
?GetName@StaticLogicalCriteria@@UEAAPEADXZ TEXTEQU <__imp_?GetName@StaticLogicalCriteria@@UEAAPEADXZ>
extern __imp_?GetReaderName@Reader@@UEAAPEADXZ:PANYARGS
?GetReaderName@Reader@@UEAAPEADXZ TEXTEQU <__imp_?GetReaderName@Reader@@UEAAPEADXZ>
extern __imp_CreateCardCriteria:PANYARGS
CreateCardCriteria TEXTEQU <__imp_CreateCardCriteria>
extern __imp_CreatePINLogicalCriteria:PANYARGS
CreatePINLogicalCriteria TEXTEQU <__imp_CreatePINLogicalCriteria>
extern __imp_CreateSDKCardServiceFactory:PANYARGS
CreateSDKCardServiceFactory TEXTEQU <__imp_CreateSDKCardServiceFactory>
extern __imp_CreateSKILogicalCriteria:PANYARGS
CreateSKILogicalCriteria TEXTEQU <__imp_CreateSKILogicalCriteria>
extern __imp_CreateStaticLogicalCriteria:PANYARGS
CreateStaticLogicalCriteria TEXTEQU <__imp_CreateStaticLogicalCriteria>
