extern __imp_acPipintCall:PANYARGS
acPipintCall TEXTEQU <__imp_acPipintCall>
extern __imp_acPipintCallEx:PANYARGS
acPipintCallEx TEXTEQU <__imp_acPipintCallEx>
extern __imp_acPipintEnd:PANYARGS
acPipintEnd TEXTEQU <__imp_acPipintEnd>
extern __imp_acPipintInitCall:PANYARGS
acPipintInitCall TEXTEQU <__imp_acPipintInitCall>
extern __imp_acPipintStart:PANYARGS
acPipintStart TEXTEQU <__imp_acPipintStart>
