extern __imp_pivConnect:PANYARGS
pivConnect TEXTEQU <__imp_pivConnect>
extern __imp_pivCrypt:PANYARGS
pivCrypt TEXTEQU <__imp_pivCrypt>
extern __imp_pivDisconnect:PANYARGS
pivDisconnect TEXTEQU <__imp_pivDisconnect>
extern __imp_pivGenerateKeyPair:PANYARGS
pivGenerateKeyPair TEXTEQU <__imp_pivGenerateKeyPair>
extern __imp_pivGetData:PANYARGS
pivGetData TEXTEQU <__imp_pivGetData>
extern __imp_pivLogIntoCardApplication:PANYARGS
pivLogIntoCardApplication TEXTEQU <__imp_pivLogIntoCardApplication>
extern __imp_pivLogoutOfCardApplication:PANYARGS
pivLogoutOfCardApplication TEXTEQU <__imp_pivLogoutOfCardApplication>
extern __imp_pivPutData:PANYARGS
pivPutData TEXTEQU <__imp_pivPutData>
extern __imp_pivSelectCardApplication:PANYARGS
pivSelectCardApplication TEXTEQU <__imp_pivSelectCardApplication>
