extern __imp_C_CancelFunction:PANYARGS
C_CancelFunction TEXTEQU <__imp_C_CancelFunction>
extern __imp_C_CetCUID:PANYARGS
C_CetCUID TEXTEQU <__imp_C_CetCUID>
extern __imp_C_CloseAllSessions:PANYARGS
C_CloseAllSessions TEXTEQU <__imp_C_CloseAllSessions>
extern __imp_C_CloseSession:PANYARGS
C_CloseSession TEXTEQU <__imp_C_CloseSession>
extern __imp_C_CopyObject:PANYARGS
C_CopyObject TEXTEQU <__imp_C_CopyObject>
extern __imp_C_CreateObject:PANYARGS
C_CreateObject TEXTEQU <__imp_C_CreateObject>
extern __imp_C_Decrypt:PANYARGS
C_Decrypt TEXTEQU <__imp_C_Decrypt>
extern __imp_C_DecryptDigestUpdate:PANYARGS
C_DecryptDigestUpdate TEXTEQU <__imp_C_DecryptDigestUpdate>
extern __imp_C_DecryptFinal:PANYARGS
C_DecryptFinal TEXTEQU <__imp_C_DecryptFinal>
extern __imp_C_DecryptInit:PANYARGS
C_DecryptInit TEXTEQU <__imp_C_DecryptInit>
extern __imp_C_DecryptUpdate:PANYARGS
C_DecryptUpdate TEXTEQU <__imp_C_DecryptUpdate>
extern __imp_C_DecryptVerifyUpdate:PANYARGS
C_DecryptVerifyUpdate TEXTEQU <__imp_C_DecryptVerifyUpdate>
extern __imp_C_DeriveKey:PANYARGS
C_DeriveKey TEXTEQU <__imp_C_DeriveKey>
extern __imp_C_DestroyObject:PANYARGS
C_DestroyObject TEXTEQU <__imp_C_DestroyObject>
extern __imp_C_Digest:PANYARGS
C_Digest TEXTEQU <__imp_C_Digest>
extern __imp_C_DigestEncryptUpdate:PANYARGS
C_DigestEncryptUpdate TEXTEQU <__imp_C_DigestEncryptUpdate>
extern __imp_C_DigestFinal:PANYARGS
C_DigestFinal TEXTEQU <__imp_C_DigestFinal>
extern __imp_C_DigestInit:PANYARGS
C_DigestInit TEXTEQU <__imp_C_DigestInit>
extern __imp_C_DigestKey:PANYARGS
C_DigestKey TEXTEQU <__imp_C_DigestKey>
extern __imp_C_DigestUpdate:PANYARGS
C_DigestUpdate TEXTEQU <__imp_C_DigestUpdate>
extern __imp_C_Encrypt:PANYARGS
C_Encrypt TEXTEQU <__imp_C_Encrypt>
extern __imp_C_EncryptFinal:PANYARGS
C_EncryptFinal TEXTEQU <__imp_C_EncryptFinal>
extern __imp_C_EncryptInit:PANYARGS
C_EncryptInit TEXTEQU <__imp_C_EncryptInit>
extern __imp_C_EncryptUpdate:PANYARGS
C_EncryptUpdate TEXTEQU <__imp_C_EncryptUpdate>
extern __imp_C_Finalize:PANYARGS
C_Finalize TEXTEQU <__imp_C_Finalize>
extern __imp_C_FindObjects:PANYARGS
C_FindObjects TEXTEQU <__imp_C_FindObjects>
extern __imp_C_FindObjectsFinal:PANYARGS
C_FindObjectsFinal TEXTEQU <__imp_C_FindObjectsFinal>
extern __imp_C_FindObjectsInit:PANYARGS
C_FindObjectsInit TEXTEQU <__imp_C_FindObjectsInit>
extern __imp_C_GenerateKey:PANYARGS
C_GenerateKey TEXTEQU <__imp_C_GenerateKey>
extern __imp_C_GenerateKeyPair:PANYARGS
C_GenerateKeyPair TEXTEQU <__imp_C_GenerateKeyPair>
extern __imp_C_GenerateRandom:PANYARGS
C_GenerateRandom TEXTEQU <__imp_C_GenerateRandom>
extern __imp_C_GetAttributeValue:PANYARGS
C_GetAttributeValue TEXTEQU <__imp_C_GetAttributeValue>
extern __imp_C_GetFunctionList:PANYARGS
C_GetFunctionList TEXTEQU <__imp_C_GetFunctionList>
extern __imp_C_GetFunctionStatus:PANYARGS
C_GetFunctionStatus TEXTEQU <__imp_C_GetFunctionStatus>
extern __imp_C_GetInfo:PANYARGS
C_GetInfo TEXTEQU <__imp_C_GetInfo>
extern __imp_C_GetMechanismInfo:PANYARGS
C_GetMechanismInfo TEXTEQU <__imp_C_GetMechanismInfo>
extern __imp_C_GetMechanismList:PANYARGS
C_GetMechanismList TEXTEQU <__imp_C_GetMechanismList>
extern __imp_C_GetObjectSize:PANYARGS
C_GetObjectSize TEXTEQU <__imp_C_GetObjectSize>
extern __imp_C_GetOperationState:PANYARGS
C_GetOperationState TEXTEQU <__imp_C_GetOperationState>
extern __imp_C_GetSessionInfo:PANYARGS
C_GetSessionInfo TEXTEQU <__imp_C_GetSessionInfo>
extern __imp_C_GetSlotInfo:PANYARGS
C_GetSlotInfo TEXTEQU <__imp_C_GetSlotInfo>
extern __imp_C_GetSlotList:PANYARGS
C_GetSlotList TEXTEQU <__imp_C_GetSlotList>
extern __imp_C_GetTokenInfo:PANYARGS
C_GetTokenInfo TEXTEQU <__imp_C_GetTokenInfo>
extern __imp_C_InitPIN:PANYARGS
C_InitPIN TEXTEQU <__imp_C_InitPIN>
extern __imp_C_InitToken:PANYARGS
C_InitToken TEXTEQU <__imp_C_InitToken>
extern __imp_C_Initialize:PANYARGS
C_Initialize TEXTEQU <__imp_C_Initialize>
extern __imp_C_Login:PANYARGS
C_Login TEXTEQU <__imp_C_Login>
extern __imp_C_Logout:PANYARGS
C_Logout TEXTEQU <__imp_C_Logout>
extern __imp_C_OpenSession:PANYARGS
C_OpenSession TEXTEQU <__imp_C_OpenSession>
extern __imp_C_ResetToken:PANYARGS
C_ResetToken TEXTEQU <__imp_C_ResetToken>
extern __imp_C_SeedRandom:PANYARGS
C_SeedRandom TEXTEQU <__imp_C_SeedRandom>
extern __imp_C_SetAttributeValue:PANYARGS
C_SetAttributeValue TEXTEQU <__imp_C_SetAttributeValue>
extern __imp_C_SetOperationState:PANYARGS
C_SetOperationState TEXTEQU <__imp_C_SetOperationState>
extern __imp_C_SetPIN:PANYARGS
C_SetPIN TEXTEQU <__imp_C_SetPIN>
extern __imp_C_Sign:PANYARGS
C_Sign TEXTEQU <__imp_C_Sign>
extern __imp_C_SignEncryptUpdate:PANYARGS
C_SignEncryptUpdate TEXTEQU <__imp_C_SignEncryptUpdate>
extern __imp_C_SignFinal:PANYARGS
C_SignFinal TEXTEQU <__imp_C_SignFinal>
extern __imp_C_SignInit:PANYARGS
C_SignInit TEXTEQU <__imp_C_SignInit>
extern __imp_C_SignRecover:PANYARGS
C_SignRecover TEXTEQU <__imp_C_SignRecover>
extern __imp_C_SignRecoverInit:PANYARGS
C_SignRecoverInit TEXTEQU <__imp_C_SignRecoverInit>
extern __imp_C_SignUpdate:PANYARGS
C_SignUpdate TEXTEQU <__imp_C_SignUpdate>
extern __imp_C_UnlockPIN:PANYARGS
C_UnlockPIN TEXTEQU <__imp_C_UnlockPIN>
extern __imp_C_UnwrapKey:PANYARGS
C_UnwrapKey TEXTEQU <__imp_C_UnwrapKey>
extern __imp_C_Verify:PANYARGS
C_Verify TEXTEQU <__imp_C_Verify>
extern __imp_C_VerifyFinal:PANYARGS
C_VerifyFinal TEXTEQU <__imp_C_VerifyFinal>
extern __imp_C_VerifyInit:PANYARGS
C_VerifyInit TEXTEQU <__imp_C_VerifyInit>
extern __imp_C_VerifyRecover:PANYARGS
C_VerifyRecover TEXTEQU <__imp_C_VerifyRecover>
extern __imp_C_VerifyRecoverInit:PANYARGS
C_VerifyRecoverInit TEXTEQU <__imp_C_VerifyRecoverInit>
extern __imp_C_VerifyUpdate:PANYARGS
C_VerifyUpdate TEXTEQU <__imp_C_VerifyUpdate>
extern __imp_C_WaitForSlotEvent:PANYARGS
C_WaitForSlotEvent TEXTEQU <__imp_C_WaitForSlotEvent>
extern __imp_C_WrapKey:PANYARGS
C_WrapKey TEXTEQU <__imp_C_WrapKey>
