extern __imp_ADsGetObject:PANYARGS
ADsGetObject TEXTEQU <__imp_ADsGetObject>
extern __imp_ADsBuildEnumerator:PANYARGS
ADsBuildEnumerator TEXTEQU <__imp_ADsBuildEnumerator>
extern __imp_ADsFreeEnumerator:PANYARGS
ADsFreeEnumerator TEXTEQU <__imp_ADsFreeEnumerator>
extern __imp_ADsEnumerateNext:PANYARGS
ADsEnumerateNext TEXTEQU <__imp_ADsEnumerateNext>
extern __imp_ADsBuildVarArrayStr:PANYARGS
ADsBuildVarArrayStr TEXTEQU <__imp_ADsBuildVarArrayStr>
extern __imp_ADsBuildVarArrayInt:PANYARGS
ADsBuildVarArrayInt TEXTEQU <__imp_ADsBuildVarArrayInt>
extern __imp_ADsOpenObject:PANYARGS
ADsOpenObject TEXTEQU <__imp_ADsOpenObject>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_ADsSetLastError:PANYARGS
ADsSetLastError TEXTEQU <__imp_ADsSetLastError>
extern __imp_ADsGetLastError:PANYARGS
ADsGetLastError TEXTEQU <__imp_ADsGetLastError>
extern __imp_AllocADsMem:PANYARGS
AllocADsMem TEXTEQU <__imp_AllocADsMem>
extern __imp_FreeADsMem:PANYARGS
FreeADsMem TEXTEQU <__imp_FreeADsMem>
extern __imp_ReallocADsMem:PANYARGS
ReallocADsMem TEXTEQU <__imp_ReallocADsMem>
extern __imp_AllocADsStr:PANYARGS
AllocADsStr TEXTEQU <__imp_AllocADsStr>
extern __imp_FreeADsStr:PANYARGS
FreeADsStr TEXTEQU <__imp_FreeADsStr>
extern __imp_ReallocADsStr:PANYARGS
ReallocADsStr TEXTEQU <__imp_ReallocADsStr>
extern __imp_ADsEncodeBinaryData:PANYARGS
ADsEncodeBinaryData TEXTEQU <__imp_ADsEncodeBinaryData>
extern __imp_PropVariantToAdsType:PANYARGS
PropVariantToAdsType TEXTEQU <__imp_PropVariantToAdsType>
extern __imp_AdsTypeToPropVariant:PANYARGS
AdsTypeToPropVariant TEXTEQU <__imp_AdsTypeToPropVariant>
extern __imp_AdsFreeAdsValues:PANYARGS
AdsFreeAdsValues TEXTEQU <__imp_AdsFreeAdsValues>
extern __imp_ADsDecodeBinaryData:PANYARGS
ADsDecodeBinaryData TEXTEQU <__imp_ADsDecodeBinaryData>
extern __imp_AdsTypeToPropVariant2:PANYARGS
AdsTypeToPropVariant2 TEXTEQU <__imp_AdsTypeToPropVariant2>
extern __imp_PropVariantToAdsType2:PANYARGS
PropVariantToAdsType2 TEXTEQU <__imp_PropVariantToAdsType2>
extern __imp_ConvertSecDescriptorToVariant:PANYARGS
ConvertSecDescriptorToVariant TEXTEQU <__imp_ConvertSecDescriptorToVariant>
extern __imp_ConvertSecurityDescriptorToSecDes:PANYARGS
ConvertSecurityDescriptorToSecDes TEXTEQU <__imp_ConvertSecurityDescriptorToSecDes>
extern __imp_BinarySDToSecurityDescriptor:PANYARGS
BinarySDToSecurityDescriptor TEXTEQU <__imp_BinarySDToSecurityDescriptor>
extern __imp_SecurityDescriptorToBinarySD:PANYARGS
SecurityDescriptorToBinarySD TEXTEQU <__imp_SecurityDescriptorToBinarySD>
extern __imp_ConvertTrusteeToSid:PANYARGS
ConvertTrusteeToSid TEXTEQU <__imp_ConvertTrusteeToSid>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
