extern __imp_DetectTSE:PANYARGS
DetectTSE TEXTEQU <__imp_DetectTSE>
extern __imp_IsTerminalServicesEnabled:PANYARGS
IsTerminalServicesEnabled TEXTEQU <__imp_IsTerminalServicesEnabled>
extern __imp_MSICleanMergedFolders:PANYARGS
MSICleanMergedFolders TEXTEQU <__imp_MSICleanMergedFolders>
extern __imp_MSIDeleteResourceFiles:PANYARGS
MSIDeleteResourceFiles TEXTEQU <__imp_MSIDeleteResourceFiles>
extern __imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV12@1@Z:PANYARGS
?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV12@1@Z TEXTEQU <__imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV12@1@Z>
extern __imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAV12@1@Z:PANYARGS
?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAV12@1@Z TEXTEQU <__imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAV12@1@Z>
extern __imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z:PANYARGS
?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z TEXTEQU <__imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z>
extern __imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0@Z:PANYARGS
?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0@Z TEXTEQU <__imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0@Z>
extern __imp_aiRegReadBinaryValue:PANYARGS
aiRegReadBinaryValue TEXTEQU <__imp_aiRegReadBinaryValue>
extern __imp_aiRegReadDWORDValue:PANYARGS
aiRegReadDWORDValue TEXTEQU <__imp_aiRegReadDWORDValue>
extern __imp_aiRegReadMultiStringValue:PANYARGS
aiRegReadMultiStringValue TEXTEQU <__imp_aiRegReadMultiStringValue>
extern __imp_aiRegReadStringValue:PANYARGS
aiRegReadStringValue TEXTEQU <__imp_aiRegReadStringValue>
extern __imp_aiRegReadValue:PANYARGS
aiRegReadValue TEXTEQU <__imp_aiRegReadValue>
extern __imp_aiRegWriteBinaryValue:PANYARGS
aiRegWriteBinaryValue TEXTEQU <__imp_aiRegWriteBinaryValue>
extern __imp_aiRegWriteDWORDValue:PANYARGS
aiRegWriteDWORDValue TEXTEQU <__imp_aiRegWriteDWORDValue>
extern __imp_aiRegWriteMultiStringValue:PANYARGS
aiRegWriteMultiStringValue TEXTEQU <__imp_aiRegWriteMultiStringValue>
extern __imp_aiRegWriteStringValue:PANYARGS
aiRegWriteStringValue TEXTEQU <__imp_aiRegWriteStringValue>
extern __imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PANYARGS
?aiSysGetFixedDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z TEXTEQU <__imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>
extern __imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z:PANYARGS
?aiSysGetFixedDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z TEXTEQU <__imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z>
extern __imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PANYARGS
?aiSysGetSystemDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z TEXTEQU <__imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>
extern __imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z:PANYARGS
?aiSysGetSystemDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z TEXTEQU <__imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z>
extern __imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAPEAX@Z:PANYARGS
?aiSysGetUserSID@@YAKAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAPEAX@Z TEXTEQU <__imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAPEAX@Z>
extern __imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAPEAX@Z:PANYARGS
?aiSysGetUserSID@@YAKAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAPEAX@Z TEXTEQU <__imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAPEAX@Z>
extern __imp_aiNetConvertUserIdToNETBIOSA:PANYARGS
aiNetConvertUserIdToNETBIOS  TEXTEQU <__imp_aiNetConvertUserIdToNETBIOSA>
extern __imp_aiNetConvertUserIdToNETBIOSW:PANYARGS
aiNetConvertUserIdToNETBIOSW TEXTEQU <__imp_aiNetConvertUserIdToNETBIOSW>
extern __imp_aiNetGetCurrentUserAndDomainA:PANYARGS
aiNetGetCurrentUserAndDomain  TEXTEQU <__imp_aiNetGetCurrentUserAndDomainA>
extern __imp_aiNetGetCurrentUserAndDomainW:PANYARGS
aiNetGetCurrentUserAndDomainW TEXTEQU <__imp_aiNetGetCurrentUserAndDomainW>
extern __imp_aiNetGetNETBIOSDomainNameFromUPNA:PANYARGS
aiNetGetNETBIOSDomainNameFromUPN  TEXTEQU <__imp_aiNetGetNETBIOSDomainNameFromUPNA>
extern __imp_aiNetGetNETBIOSDomainNameFromUPNW:PANYARGS
aiNetGetNETBIOSDomainNameFromUPNW TEXTEQU <__imp_aiNetGetNETBIOSDomainNameFromUPNW>
extern __imp_aiNetGetUserNameDomainFromUPNA:PANYARGS
aiNetGetUserNameDomainFromUPN  TEXTEQU <__imp_aiNetGetUserNameDomainFromUPNA>
extern __imp_aiNetGetUserNameDomainFromUPNW:PANYARGS
aiNetGetUserNameDomainFromUPNW TEXTEQU <__imp_aiNetGetUserNameDomainFromUPNW>
extern __imp_aiSysConvertSIDA:PANYARGS
aiSysConvertSID  TEXTEQU <__imp_aiSysConvertSIDA>
extern __imp_aiSysConvertSIDW:PANYARGS
aiSysConvertSIDW TEXTEQU <__imp_aiSysConvertSIDW>
extern __imp_aiSysGetFixedDriveA:PANYARGS
aiSysGetFixedDrive  TEXTEQU <__imp_aiSysGetFixedDriveA>
extern __imp_aiSysGetFixedDriveW:PANYARGS
aiSysGetFixedDriveW TEXTEQU <__imp_aiSysGetFixedDriveW>
extern __imp_aiSysGetSystemDriveA:PANYARGS
aiSysGetSystemDrive  TEXTEQU <__imp_aiSysGetSystemDriveA>
extern __imp_aiSysGetSystemDriveW:PANYARGS
aiSysGetSystemDriveW TEXTEQU <__imp_aiSysGetSystemDriveW>
extern __imp_aiSysGetUserSIDA:PANYARGS
aiSysGetUserSID  TEXTEQU <__imp_aiSysGetUserSIDA>
extern __imp_aiSysGetUserSIDW:PANYARGS
aiSysGetUserSIDW TEXTEQU <__imp_aiSysGetUserSIDW>
extern __imp_aiSysObtainSIDA:PANYARGS
aiSysObtainSID  TEXTEQU <__imp_aiSysObtainSIDA>
extern __imp_aiSysObtainSIDW:PANYARGS
aiSysObtainSIDW TEXTEQU <__imp_aiSysObtainSIDW>
