extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_IsAdmDirty:PANYARGS
IsAdmDirty TEXTEQU <__imp_IsAdmDirty>
extern __imp_ResetAdmDirtyFlag:PANYARGS
ResetAdmDirtyFlag TEXTEQU <__imp_ResetAdmDirtyFlag>
extern __imp_AdmClose:PANYARGS
AdmClose TEXTEQU <__imp_AdmClose>
extern __imp_AdmFinishedA:PANYARGS
AdmFinished  TEXTEQU <__imp_AdmFinishedA>
extern __imp_AdmFinishedW:PANYARGS
AdmFinishedW TEXTEQU <__imp_AdmFinishedW>
extern __imp_AdmInitA:PANYARGS
AdmInit  TEXTEQU <__imp_AdmInitA>
extern __imp_AdmInitW:PANYARGS
AdmInitW TEXTEQU <__imp_AdmInitW>
extern __imp_AdmResetA:PANYARGS
AdmReset  TEXTEQU <__imp_AdmResetA>
extern __imp_AdmResetW:PANYARGS
AdmResetW TEXTEQU <__imp_AdmResetW>
extern __imp_AdmSaveData:PANYARGS
AdmSaveData TEXTEQU <__imp_AdmSaveData>
extern __imp_CheckDuplicateKeysA:PANYARGS
CheckDuplicateKeys  TEXTEQU <__imp_CheckDuplicateKeysA>
extern __imp_CheckDuplicateKeysW:PANYARGS
CheckDuplicateKeysW TEXTEQU <__imp_CheckDuplicateKeysW>
extern __imp_CreateAdmUiA:PANYARGS
CreateAdmUi  TEXTEQU <__imp_CreateAdmUiA>
extern __imp_CreateAdmUiW:PANYARGS
CreateAdmUiW TEXTEQU <__imp_CreateAdmUiW>
extern __imp_GetAdmCategoriesA:PANYARGS
GetAdmCategories  TEXTEQU <__imp_GetAdmCategoriesA>
extern __imp_GetAdmCategoriesW:PANYARGS
GetAdmCategoriesW TEXTEQU <__imp_GetAdmCategoriesW>
extern __imp_GetFontInfoA:PANYARGS
GetFontInfo  TEXTEQU <__imp_GetFontInfoA>
extern __imp_GetFontInfoW:PANYARGS
GetFontInfoW TEXTEQU <__imp_GetFontInfoW>
