extern __imp_??0CLexer@@QEAA@XZ:PANYARGS
??0CLexer@@QEAA@XZ TEXTEQU <__imp_??0CLexer@@QEAA@XZ>
extern __imp_??1CLexer@@QEAA@XZ:PANYARGS
??1CLexer@@QEAA@XZ TEXTEQU <__imp_??1CLexer@@QEAA@XZ>
extern __imp_ADsAbandonSearch:PANYARGS
ADsAbandonSearch TEXTEQU <__imp_ADsAbandonSearch>
extern __imp_ADsCloseSearchHandle:PANYARGS
ADsCloseSearchHandle TEXTEQU <__imp_ADsCloseSearchHandle>
extern __imp_ADsCreateAttributeDefinition:PANYARGS
ADsCreateAttributeDefinition TEXTEQU <__imp_ADsCreateAttributeDefinition>
extern __imp_ADsCreateClassDefinition:PANYARGS
ADsCreateClassDefinition TEXTEQU <__imp_ADsCreateClassDefinition>
extern __imp_ADsCreateDSObject:PANYARGS
ADsCreateDSObject TEXTEQU <__imp_ADsCreateDSObject>
extern __imp_ADsCreateDSObjectExt:PANYARGS
ADsCreateDSObjectExt TEXTEQU <__imp_ADsCreateDSObjectExt>
extern __imp_ADsDeleteAttributeDefinition:PANYARGS
ADsDeleteAttributeDefinition TEXTEQU <__imp_ADsDeleteAttributeDefinition>
extern __imp_ADsDeleteClassDefinition:PANYARGS
ADsDeleteClassDefinition TEXTEQU <__imp_ADsDeleteClassDefinition>
extern __imp_ADsDeleteDSObject:PANYARGS
ADsDeleteDSObject TEXTEQU <__imp_ADsDeleteDSObject>
extern __imp_ADsEnumAttributes:PANYARGS
ADsEnumAttributes TEXTEQU <__imp_ADsEnumAttributes>
extern __imp_ADsEnumClasses:PANYARGS
ADsEnumClasses TEXTEQU <__imp_ADsEnumClasses>
extern __imp_ADsExecuteSearch:PANYARGS
ADsExecuteSearch TEXTEQU <__imp_ADsExecuteSearch>
extern __imp_ADsFreeColumn:PANYARGS
ADsFreeColumn TEXTEQU <__imp_ADsFreeColumn>
extern __imp_ADsGetColumn:PANYARGS
ADsGetColumn TEXTEQU <__imp_ADsGetColumn>
extern __imp_ADsGetFirstRow:PANYARGS
ADsGetFirstRow TEXTEQU <__imp_ADsGetFirstRow>
extern __imp_ADsGetNextColumnName:PANYARGS
ADsGetNextColumnName TEXTEQU <__imp_ADsGetNextColumnName>
extern __imp_ADsGetNextRow:PANYARGS
ADsGetNextRow TEXTEQU <__imp_ADsGetNextRow>
extern __imp_ADsGetObjectAttributes:PANYARGS
ADsGetObjectAttributes TEXTEQU <__imp_ADsGetObjectAttributes>
extern __imp_ADsGetPreviousRow:PANYARGS
ADsGetPreviousRow TEXTEQU <__imp_ADsGetPreviousRow>
extern __imp_ADsHelperGetCurrentRowMessage:PANYARGS
ADsHelperGetCurrentRowMessage TEXTEQU <__imp_ADsHelperGetCurrentRowMessage>
extern __imp_ADsObject:PANYARGS
ADsObject TEXTEQU <__imp_ADsObject>
extern __imp_ADsSetObjectAttributes:PANYARGS
ADsSetObjectAttributes TEXTEQU <__imp_ADsSetObjectAttributes>
extern __imp_ADsSetSearchPreference:PANYARGS
ADsSetSearchPreference TEXTEQU <__imp_ADsSetSearchPreference>
extern __imp_ADsWriteAttributeDefinition:PANYARGS
ADsWriteAttributeDefinition TEXTEQU <__imp_ADsWriteAttributeDefinition>
extern __imp_ADsWriteClassDefinition:PANYARGS
ADsWriteClassDefinition TEXTEQU <__imp_ADsWriteClassDefinition>
extern __imp_AdsTypeToLdapTypeCopyConstruct:PANYARGS
AdsTypeToLdapTypeCopyConstruct TEXTEQU <__imp_AdsTypeToLdapTypeCopyConstruct>
extern __imp_AdsTypeToLdapTypeCopyDNWithBinary:PANYARGS
AdsTypeToLdapTypeCopyDNWithBinary TEXTEQU <__imp_AdsTypeToLdapTypeCopyDNWithBinary>
extern __imp_AdsTypeToLdapTypeCopyDNWithString:PANYARGS
AdsTypeToLdapTypeCopyDNWithString TEXTEQU <__imp_AdsTypeToLdapTypeCopyDNWithString>
extern __imp_AdsTypeToLdapTypeCopyGeneralizedTime:PANYARGS
AdsTypeToLdapTypeCopyGeneralizedTime TEXTEQU <__imp_AdsTypeToLdapTypeCopyGeneralizedTime>
extern __imp_AdsTypeToLdapTypeCopyTime:PANYARGS
AdsTypeToLdapTypeCopyTime TEXTEQU <__imp_AdsTypeToLdapTypeCopyTime>
extern __imp_BerBvFree:PANYARGS
BerBvFree TEXTEQU <__imp_BerBvFree>
extern __imp_BerEncodingQuotaControl:PANYARGS
BerEncodingQuotaControl TEXTEQU <__imp_BerEncodingQuotaControl>
extern __imp_BuildADsParentPath:PANYARGS
BuildADsParentPath TEXTEQU <__imp_BuildADsParentPath>
extern __imp_BuildADsParentPathFromObjectInfo2:PANYARGS
BuildADsParentPathFromObjectInfo2 TEXTEQU <__imp_BuildADsParentPathFromObjectInfo2>
extern __imp_BuildADsParentPathFromObjectInfo:PANYARGS
BuildADsParentPathFromObjectInfo TEXTEQU <__imp_BuildADsParentPathFromObjectInfo>
extern __imp_BuildADsPathFromLDAPPath2:PANYARGS
BuildADsPathFromLDAPPath2 TEXTEQU <__imp_BuildADsPathFromLDAPPath2>
extern __imp_BuildADsPathFromLDAPPath:PANYARGS
BuildADsPathFromLDAPPath TEXTEQU <__imp_BuildADsPathFromLDAPPath>
extern __imp_BuildADsPathFromParent:PANYARGS
BuildADsPathFromParent TEXTEQU <__imp_BuildADsPathFromParent>
extern __imp_BuildLDAPPathFromADsPath2:PANYARGS
BuildLDAPPathFromADsPath2 TEXTEQU <__imp_BuildLDAPPathFromADsPath2>
extern __imp_BuildLDAPPathFromADsPath:PANYARGS
BuildLDAPPathFromADsPath TEXTEQU <__imp_BuildLDAPPathFromADsPath>
extern __imp_ChangeSeparator:PANYARGS
ChangeSeparator TEXTEQU <__imp_ChangeSeparator>
extern __imp_Component:PANYARGS
Component TEXTEQU <__imp_Component>
extern __imp_ConvertSidToString:PANYARGS
ConvertSidToString TEXTEQU <__imp_ConvertSidToString>
extern __imp_ConvertSidToU2Trustee:PANYARGS
ConvertSidToU2Trustee TEXTEQU <__imp_ConvertSidToU2Trustee>
extern __imp_ConvertU2TrusteeToSid:PANYARGS
ConvertU2TrusteeToSid TEXTEQU <__imp_ConvertU2TrusteeToSid>
extern __imp_FindEntryInSearchTable:PANYARGS
FindEntryInSearchTable TEXTEQU <__imp_FindEntryInSearchTable>
extern __imp_FindSearchTableIndex:PANYARGS
FindSearchTableIndex TEXTEQU <__imp_FindSearchTableIndex>
extern __imp_FreeObjectInfo:PANYARGS
FreeObjectInfo TEXTEQU <__imp_FreeObjectInfo>
extern __imp_GetDefaultServer:PANYARGS
GetDefaultServer TEXTEQU <__imp_GetDefaultServer>
extern __imp_GetDisplayName:PANYARGS
GetDisplayName TEXTEQU <__imp_GetDisplayName>
extern __imp_GetDomainDNSNameForDomain:PANYARGS
GetDomainDNSNameForDomain TEXTEQU <__imp_GetDomainDNSNameForDomain>
extern __imp_GetLDAPTypeName:PANYARGS
GetLDAPTypeName TEXTEQU <__imp_GetLDAPTypeName>
extern __imp_?GetNextToken@CLexer@@QEAAJPEAGPEAK@Z:PANYARGS
?GetNextToken@CLexer@@QEAAJPEAGPEAK@Z TEXTEQU <__imp_?GetNextToken@CLexer@@QEAAJPEAGPEAK@Z>
extern __imp_GetSyntaxOfAttribute:PANYARGS
GetSyntaxOfAttribute TEXTEQU <__imp_GetSyntaxOfAttribute>
extern __imp_InitObjectInfo:PANYARGS
InitObjectInfo TEXTEQU <__imp_InitObjectInfo>
extern __imp_?InitializePath@CLexer@@QEAAJPEAG@Z:PANYARGS
?InitializePath@CLexer@@QEAAJPEAG@Z TEXTEQU <__imp_?InitializePath@CLexer@@QEAAJPEAG@Z>
extern __imp_IsGCNamespace:PANYARGS
IsGCNamespace TEXTEQU <__imp_IsGCNamespace>
extern __imp_LdapAddExtS:PANYARGS
LdapAddExtS TEXTEQU <__imp_LdapAddExtS>
extern __imp_LdapAddS:PANYARGS
LdapAddS TEXTEQU <__imp_LdapAddS>
extern __imp_LdapAttributeFree:PANYARGS
LdapAttributeFree TEXTEQU <__imp_LdapAttributeFree>
extern __imp_LdapCacheAddRef:PANYARGS
LdapCacheAddRef TEXTEQU <__imp_LdapCacheAddRef>
extern __imp_LdapCloseObject:PANYARGS
LdapCloseObject TEXTEQU <__imp_LdapCloseObject>
extern __imp_LdapCompareExt:PANYARGS
LdapCompareExt TEXTEQU <__imp_LdapCompareExt>
extern __imp_LdapControlFree:PANYARGS
LdapControlFree TEXTEQU <__imp_LdapControlFree>
extern __imp_LdapControlsFree:PANYARGS
LdapControlsFree TEXTEQU <__imp_LdapControlsFree>
extern __imp_LdapCountEntries:PANYARGS
LdapCountEntries TEXTEQU <__imp_LdapCountEntries>
extern __imp_LdapCrackUserDNtoNTLMUser2:PANYARGS
LdapCrackUserDNtoNTLMUser2 TEXTEQU <__imp_LdapCrackUserDNtoNTLMUser2>
extern __imp_LdapCrackUserDNtoNTLMUser:PANYARGS
LdapCrackUserDNtoNTLMUser TEXTEQU <__imp_LdapCrackUserDNtoNTLMUser>
extern __imp_LdapCreatePageControl:PANYARGS
LdapCreatePageControl TEXTEQU <__imp_LdapCreatePageControl>
extern __imp_LdapDeleteExtS:PANYARGS
LdapDeleteExtS TEXTEQU <__imp_LdapDeleteExtS>
extern __imp_LdapDeleteS:PANYARGS
LdapDeleteS TEXTEQU <__imp_LdapDeleteS>
extern __imp_LdapFirstAttribute:PANYARGS
LdapFirstAttribute TEXTEQU <__imp_LdapFirstAttribute>
extern __imp_LdapFirstEntry:PANYARGS
LdapFirstEntry TEXTEQU <__imp_LdapFirstEntry>
extern __imp_LdapGetDn:PANYARGS
LdapGetDn TEXTEQU <__imp_LdapGetDn>
extern __imp_LdapGetNextPageS:PANYARGS
LdapGetNextPageS TEXTEQU <__imp_LdapGetNextPageS>
extern __imp_LdapGetSchemaObjectCount:PANYARGS
LdapGetSchemaObjectCount TEXTEQU <__imp_LdapGetSchemaObjectCount>
extern __imp_LdapGetSubSchemaSubEntryPath:PANYARGS
LdapGetSubSchemaSubEntryPath TEXTEQU <__imp_LdapGetSubSchemaSubEntryPath>
extern __imp_LdapGetSyntaxIdOfAttribute:PANYARGS
LdapGetSyntaxIdOfAttribute TEXTEQU <__imp_LdapGetSyntaxIdOfAttribute>
extern __imp_LdapGetSyntaxOfAttributeOnServer:PANYARGS
LdapGetSyntaxOfAttributeOnServer TEXTEQU <__imp_LdapGetSyntaxOfAttributeOnServer>
extern __imp_LdapGetValues:PANYARGS
LdapGetValues TEXTEQU <__imp_LdapGetValues>
extern __imp_LdapGetValuesLen:PANYARGS
LdapGetValuesLen TEXTEQU <__imp_LdapGetValuesLen>
extern __imp_LdapInitializeSearchPreferences:PANYARGS
LdapInitializeSearchPreferences TEXTEQU <__imp_LdapInitializeSearchPreferences>
extern __imp_LdapIsClassNameValidOnServer:PANYARGS
LdapIsClassNameValidOnServer TEXTEQU <__imp_LdapIsClassNameValidOnServer>
extern __imp_LdapMakeSchemaCacheObsolete:PANYARGS
LdapMakeSchemaCacheObsolete TEXTEQU <__imp_LdapMakeSchemaCacheObsolete>
extern __imp_LdapMemFree:PANYARGS
LdapMemFree TEXTEQU <__imp_LdapMemFree>
extern __imp_LdapModDnS:PANYARGS
LdapModDnS TEXTEQU <__imp_LdapModDnS>
extern __imp_LdapModifyExtS:PANYARGS
LdapModifyExtS TEXTEQU <__imp_LdapModifyExtS>
extern __imp_LdapModifyS:PANYARGS
LdapModifyS TEXTEQU <__imp_LdapModifyS>
extern __imp_LdapMsgFree:PANYARGS
LdapMsgFree TEXTEQU <__imp_LdapMsgFree>
extern __imp_LdapNextAttribute:PANYARGS
LdapNextAttribute TEXTEQU <__imp_LdapNextAttribute>
extern __imp_LdapNextEntry:PANYARGS
LdapNextEntry TEXTEQU <__imp_LdapNextEntry>
extern __imp_LdapOpenObject2:PANYARGS
LdapOpenObject2 TEXTEQU <__imp_LdapOpenObject2>
extern __imp_LdapOpenObject:PANYARGS
LdapOpenObject TEXTEQU <__imp_LdapOpenObject>
extern __imp_LdapParsePageControl:PANYARGS
LdapParsePageControl TEXTEQU <__imp_LdapParsePageControl>
extern __imp_LdapParseResult:PANYARGS
LdapParseResult TEXTEQU <__imp_LdapParseResult>
extern __imp_LdapReadAttribute2:PANYARGS
LdapReadAttribute2 TEXTEQU <__imp_LdapReadAttribute2>
extern __imp_LdapReadAttribute:PANYARGS
LdapReadAttribute TEXTEQU <__imp_LdapReadAttribute>
extern __imp_LdapReadAttributeFast:PANYARGS
LdapReadAttributeFast TEXTEQU <__imp_LdapReadAttributeFast>
extern __imp_LdapRenameExtS:PANYARGS
LdapRenameExtS TEXTEQU <__imp_LdapRenameExtS>
extern __imp_LdapResult:PANYARGS
LdapResult TEXTEQU <__imp_LdapResult>
extern __imp_LdapSearch:PANYARGS
LdapSearch TEXTEQU <__imp_LdapSearch>
extern __imp_LdapSearchAbandonPage:PANYARGS
LdapSearchAbandonPage TEXTEQU <__imp_LdapSearchAbandonPage>
extern __imp_LdapSearchExtS:PANYARGS
LdapSearchExtS TEXTEQU <__imp_LdapSearchExtS>
extern __imp_LdapSearchInitPage:PANYARGS
LdapSearchInitPage TEXTEQU <__imp_LdapSearchInitPage>
extern __imp_LdapSearchS:PANYARGS
LdapSearchS TEXTEQU <__imp_LdapSearchS>
extern __imp_LdapSearchST:PANYARGS
LdapSearchST TEXTEQU <__imp_LdapSearchST>
extern __imp_LdapTypeBinaryToString:PANYARGS
LdapTypeBinaryToString TEXTEQU <__imp_LdapTypeBinaryToString>
extern __imp_LdapTypeCopyConstruct:PANYARGS
LdapTypeCopyConstruct TEXTEQU <__imp_LdapTypeCopyConstruct>
extern __imp_LdapTypeFreeLdapModList:PANYARGS
LdapTypeFreeLdapModList TEXTEQU <__imp_LdapTypeFreeLdapModList>
extern __imp_LdapTypeFreeLdapModObject:PANYARGS
LdapTypeFreeLdapModObject TEXTEQU <__imp_LdapTypeFreeLdapModObject>
extern __imp_LdapTypeFreeLdapObjects:PANYARGS
LdapTypeFreeLdapObjects TEXTEQU <__imp_LdapTypeFreeLdapObjects>
extern __imp_LdapTypeToAdsTypeDNWithBinary:PANYARGS
LdapTypeToAdsTypeDNWithBinary TEXTEQU <__imp_LdapTypeToAdsTypeDNWithBinary>
extern __imp_LdapTypeToAdsTypeDNWithString:PANYARGS
LdapTypeToAdsTypeDNWithString TEXTEQU <__imp_LdapTypeToAdsTypeDNWithString>
extern __imp_LdapTypeToAdsTypeGeneralizedTime:PANYARGS
LdapTypeToAdsTypeGeneralizedTime TEXTEQU <__imp_LdapTypeToAdsTypeGeneralizedTime>
extern __imp_LdapTypeToAdsTypeUTCTime:PANYARGS
LdapTypeToAdsTypeUTCTime TEXTEQU <__imp_LdapTypeToAdsTypeUTCTime>
extern __imp_LdapValueFree:PANYARGS
LdapValueFree TEXTEQU <__imp_LdapValueFree>
extern __imp_LdapValueFreeLen:PANYARGS
LdapValueFreeLen TEXTEQU <__imp_LdapValueFreeLen>
extern __imp_LdapcKeepHandleAround:PANYARGS
LdapcKeepHandleAround TEXTEQU <__imp_LdapcKeepHandleAround>
extern __imp_LdapcSetStickyServer:PANYARGS
LdapcSetStickyServer TEXTEQU <__imp_LdapcSetStickyServer>
extern __imp_PathName:PANYARGS
PathName TEXTEQU <__imp_PathName>
extern __imp_ReadPagingSupportedAttr:PANYARGS
ReadPagingSupportedAttr TEXTEQU <__imp_ReadPagingSupportedAttr>
extern __imp_ReadSecurityDescriptorControlType:PANYARGS
ReadSecurityDescriptorControlType TEXTEQU <__imp_ReadSecurityDescriptorControlType>
extern __imp_ReadServerSupportsIsADControl:PANYARGS
ReadServerSupportsIsADControl TEXTEQU <__imp_ReadServerSupportsIsADControl>
extern __imp_SchemaAddRef:PANYARGS
SchemaAddRef TEXTEQU <__imp_SchemaAddRef>
extern __imp_SchemaClose:PANYARGS
SchemaClose TEXTEQU <__imp_SchemaClose>
extern __imp_SchemaGetClassInfo:PANYARGS
SchemaGetClassInfo TEXTEQU <__imp_SchemaGetClassInfo>
extern __imp_SchemaGetClassInfoByIndex:PANYARGS
SchemaGetClassInfoByIndex TEXTEQU <__imp_SchemaGetClassInfoByIndex>
extern __imp_SchemaGetObjectCount:PANYARGS
SchemaGetObjectCount TEXTEQU <__imp_SchemaGetObjectCount>
extern __imp_SchemaGetPropertyInfo:PANYARGS
SchemaGetPropertyInfo TEXTEQU <__imp_SchemaGetPropertyInfo>
extern __imp_SchemaGetPropertyInfoByIndex:PANYARGS
SchemaGetPropertyInfoByIndex TEXTEQU <__imp_SchemaGetPropertyInfoByIndex>
extern __imp_SchemaGetStringsFromStringTable:PANYARGS
SchemaGetStringsFromStringTable TEXTEQU <__imp_SchemaGetStringsFromStringTable>
extern __imp_SchemaGetSyntaxOfAttribute:PANYARGS
SchemaGetSyntaxOfAttribute TEXTEQU <__imp_SchemaGetSyntaxOfAttribute>
extern __imp_SchemaIsClassAContainer:PANYARGS
SchemaIsClassAContainer TEXTEQU <__imp_SchemaIsClassAContainer>
extern __imp_SchemaOpen:PANYARGS
SchemaOpen TEXTEQU <__imp_SchemaOpen>
extern __imp_?SetAtDisabler@CLexer@@QEAAXH@Z:PANYARGS
?SetAtDisabler@CLexer@@QEAAXH@Z TEXTEQU <__imp_?SetAtDisabler@CLexer@@QEAAXH@Z>
extern __imp_?SetExclaimnationDisabler@CLexer@@QEAAXH@Z:PANYARGS
?SetExclaimnationDisabler@CLexer@@QEAAXH@Z TEXTEQU <__imp_?SetExclaimnationDisabler@CLexer@@QEAAXH@Z>
extern __imp_?SetFSlashDisabler@CLexer@@QEAAXH@Z:PANYARGS
?SetFSlashDisabler@CLexer@@QEAAXH@Z TEXTEQU <__imp_?SetFSlashDisabler@CLexer@@QEAAXH@Z>
extern __imp_SortAndRemoveDuplicateOIDs:PANYARGS
SortAndRemoveDuplicateOIDs TEXTEQU <__imp_SortAndRemoveDuplicateOIDs>
extern __imp_UnMarshallLDAPToLDAPSynID:PANYARGS
UnMarshallLDAPToLDAPSynID TEXTEQU <__imp_UnMarshallLDAPToLDAPSynID>
extern __imp_intcmp:PANYARGS
intcmp TEXTEQU <__imp_intcmp>
extern __imp_ADSIAbandonSearch:PANYARGS
ADSIAbandonSearch TEXTEQU <__imp_ADSIAbandonSearch>
extern __imp_ADSICloseDSObject:PANYARGS
ADSICloseDSObject TEXTEQU <__imp_ADSICloseDSObject>
extern __imp_ADSICloseSearchHandle:PANYARGS
ADSICloseSearchHandle TEXTEQU <__imp_ADSICloseSearchHandle>
extern __imp_ADSICreateDSObject:PANYARGS
ADSICreateDSObject TEXTEQU <__imp_ADSICreateDSObject>
extern __imp_ADSIDeleteDSObject:PANYARGS
ADSIDeleteDSObject TEXTEQU <__imp_ADSIDeleteDSObject>
extern __imp_ADSIExecuteSearch:PANYARGS
ADSIExecuteSearch TEXTEQU <__imp_ADSIExecuteSearch>
extern __imp_ADSIFreeColumn:PANYARGS
ADSIFreeColumn TEXTEQU <__imp_ADSIFreeColumn>
extern __imp_ADSIGetColumn:PANYARGS
ADSIGetColumn TEXTEQU <__imp_ADSIGetColumn>
extern __imp_ADSIGetFirstRow:PANYARGS
ADSIGetFirstRow TEXTEQU <__imp_ADSIGetFirstRow>
extern __imp_ADSIGetNextColumnName:PANYARGS
ADSIGetNextColumnName TEXTEQU <__imp_ADSIGetNextColumnName>
extern __imp_ADSIGetNextRow:PANYARGS
ADSIGetNextRow TEXTEQU <__imp_ADSIGetNextRow>
extern __imp_ADSIGetObjectAttributes:PANYARGS
ADSIGetObjectAttributes TEXTEQU <__imp_ADSIGetObjectAttributes>
extern __imp_ADSIGetPreviousRow:PANYARGS
ADSIGetPreviousRow TEXTEQU <__imp_ADSIGetPreviousRow>
extern __imp_ADSIModifyRdn:PANYARGS
ADSIModifyRdn TEXTEQU <__imp_ADSIModifyRdn>
extern __imp_ADSIOpenDSObject:PANYARGS
ADSIOpenDSObject TEXTEQU <__imp_ADSIOpenDSObject>
extern __imp_ADSISetObjectAttributes:PANYARGS
ADSISetObjectAttributes TEXTEQU <__imp_ADSISetObjectAttributes>
extern __imp_ADSISetSearchPreference:PANYARGS
ADSISetSearchPreference TEXTEQU <__imp_ADSISetSearchPreference>
extern __imp_ADsDecodeBinaryData:PANYARGS
ADsDecodeBinaryData TEXTEQU <__imp_ADsDecodeBinaryData>
extern __imp_ADsEncodeBinaryData:PANYARGS
ADsEncodeBinaryData TEXTEQU <__imp_ADsEncodeBinaryData>
extern __imp_ADsGetLastError:PANYARGS
ADsGetLastError TEXTEQU <__imp_ADsGetLastError>
extern __imp_ADsSetLastError:PANYARGS
ADsSetLastError TEXTEQU <__imp_ADsSetLastError>
extern __imp_AdsTypeFreeAdsObjects:PANYARGS
AdsTypeFreeAdsObjects TEXTEQU <__imp_AdsTypeFreeAdsObjects>
extern __imp_AllocADsMem:PANYARGS
AllocADsMem TEXTEQU <__imp_AllocADsMem>
extern __imp_AllocADsStr:PANYARGS
AllocADsStr TEXTEQU <__imp_AllocADsStr>
extern __imp_FreeADsMem:PANYARGS
FreeADsMem TEXTEQU <__imp_FreeADsMem>
extern __imp_FreeADsStr:PANYARGS
FreeADsStr TEXTEQU <__imp_FreeADsStr>
extern __imp_LdapTypeToAdsTypeCopyConstruct:PANYARGS
LdapTypeToAdsTypeCopyConstruct TEXTEQU <__imp_LdapTypeToAdsTypeCopyConstruct>
extern __imp_MapADSTypeToLDAPType:PANYARGS
MapADSTypeToLDAPType TEXTEQU <__imp_MapADSTypeToLDAPType>
extern __imp_MapLDAPTypeToADSType:PANYARGS
MapLDAPTypeToADSType TEXTEQU <__imp_MapLDAPTypeToADSType>
extern __imp_ReallocADsMem:PANYARGS
ReallocADsMem TEXTEQU <__imp_ReallocADsMem>
extern __imp_ReallocADsStr:PANYARGS
ReallocADsStr TEXTEQU <__imp_ReallocADsStr>
