extern __imp_AddDelBackupEntry:PANYARGS
AddDelBackupEntry TEXTEQU <__imp_AddDelBackupEntry>
extern __imp_AdvInstallFile:PANYARGS
AdvInstallFile TEXTEQU <__imp_AdvInstallFile>
extern __imp_CloseINFEngine:PANYARGS
CloseINFEngine TEXTEQU <__imp_CloseINFEngine>
extern __imp_DelNode:PANYARGS
DelNode TEXTEQU <__imp_DelNode>
extern __imp_DelNodeRunDLL32:PANYARGS
DelNodeRunDLL32 TEXTEQU <__imp_DelNodeRunDLL32>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DoInfInstall:PANYARGS
DoInfInstall TEXTEQU <__imp_DoInfInstall>
extern __imp_ExecuteCab:PANYARGS
ExecuteCab TEXTEQU <__imp_ExecuteCab>
extern __imp_ExtractFiles:PANYARGS
ExtractFiles TEXTEQU <__imp_ExtractFiles>
extern __imp_FileSaveMarkNotExist:PANYARGS
FileSaveMarkNotExist TEXTEQU <__imp_FileSaveMarkNotExist>
extern __imp_FileSaveRestore:PANYARGS
FileSaveRestore TEXTEQU <__imp_FileSaveRestore>
extern __imp_FileSaveRestoreOnINF:PANYARGS
FileSaveRestoreOnINF TEXTEQU <__imp_FileSaveRestoreOnINF>
extern __imp_GetVersionFromFile:PANYARGS
GetVersionFromFile TEXTEQU <__imp_GetVersionFromFile>
extern __imp_GetVersionFromFileEx:PANYARGS
GetVersionFromFileEx TEXTEQU <__imp_GetVersionFromFileEx>
extern __imp_IsNTAdmin:PANYARGS
IsNTAdmin TEXTEQU <__imp_IsNTAdmin>
extern __imp_LaunchINFSection:PANYARGS
LaunchINFSection TEXTEQU <__imp_LaunchINFSection>
extern __imp_LaunchINFSectionEx:PANYARGS
LaunchINFSectionEx TEXTEQU <__imp_LaunchINFSectionEx>
extern __imp_NeedReboot:PANYARGS
NeedReboot TEXTEQU <__imp_NeedReboot>
extern __imp_NeedRebootInit:PANYARGS
NeedRebootInit TEXTEQU <__imp_NeedRebootInit>
extern __imp_OpenINFEngine:PANYARGS
OpenINFEngine TEXTEQU <__imp_OpenINFEngine>
extern __imp_RebootCheckOnInstall:PANYARGS
RebootCheckOnInstall TEXTEQU <__imp_RebootCheckOnInstall>
extern __imp_RegInstall:PANYARGS
RegInstall TEXTEQU <__imp_RegInstall>
extern __imp_RegRestoreAll:PANYARGS
RegRestoreAll TEXTEQU <__imp_RegRestoreAll>
extern __imp_RegSaveRestore:PANYARGS
RegSaveRestore TEXTEQU <__imp_RegSaveRestore>
extern __imp_RegSaveRestoreOnINF:PANYARGS
RegSaveRestoreOnINF TEXTEQU <__imp_RegSaveRestoreOnINF>
extern __imp_RegisterOCX:PANYARGS
RegisterOCX TEXTEQU <__imp_RegisterOCX>
extern __imp_RunSetupCommand:PANYARGS
RunSetupCommand TEXTEQU <__imp_RunSetupCommand>
extern __imp_SetPerUserSecValues:PANYARGS
SetPerUserSecValues TEXTEQU <__imp_SetPerUserSecValues>
extern __imp_TranslateInfString:PANYARGS
TranslateInfString TEXTEQU <__imp_TranslateInfString>
extern __imp_TranslateInfStringEx:PANYARGS
TranslateInfStringEx TEXTEQU <__imp_TranslateInfStringEx>
extern __imp_UserInstStubWrapper:PANYARGS
UserInstStubWrapper TEXTEQU <__imp_UserInstStubWrapper>
extern __imp_UserUnInstStubWrapper:PANYARGS
UserUnInstStubWrapper TEXTEQU <__imp_UserUnInstStubWrapper>
