extern __imp_??0CPattern@@QEAA@PEAD_N@Z:PANYARGS
??0CPattern@@QEAA@PEAD_N@Z TEXTEQU <__imp_??0CPattern@@QEAA@PEAD_N@Z>
extern __imp_??0bytestring@@QEAA@AEBV0@@Z:PANYARGS
??0bytestring@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0bytestring@@QEAA@AEBV0@@Z>
extern __imp_??0bytestring@@QEAA@H@Z:PANYARGS
??0bytestring@@QEAA@H@Z TEXTEQU <__imp_??0bytestring@@QEAA@H@Z>
extern __imp_??0bytestring@@QEAA@PEBEH@Z:PANYARGS
??0bytestring@@QEAA@PEBEH@Z TEXTEQU <__imp_??0bytestring@@QEAA@PEBEH@Z>
extern __imp_??0bytestring@@QEAA@XZ:PANYARGS
??0bytestring@@QEAA@XZ TEXTEQU <__imp_??0bytestring@@QEAA@XZ>
extern __imp_??1CPattern@@QEAA@XZ:PANYARGS
??1CPattern@@QEAA@XZ TEXTEQU <__imp_??1CPattern@@QEAA@XZ>
extern __imp_??1bytestring@@QEAA@XZ:PANYARGS
??1bytestring@@QEAA@XZ TEXTEQU <__imp_??1bytestring@@QEAA@XZ>
extern __imp_??4CPattern@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CPattern@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CPattern@@QEAAAEAV0@AEBV0@@Z>
extern __imp_?IsMatched@CPattern@@QEAA_NPEBD@Z:PANYARGS
?IsMatched@CPattern@@QEAA_NPEBD@Z TEXTEQU <__imp_?IsMatched@CPattern@@QEAA_NPEBD@Z>
extern __imp_?clear@bytestring@@QEAAXXZ:PANYARGS
?clear@bytestring@@QEAAXXZ TEXTEQU <__imp_?clear@bytestring@@QEAAXXZ>
extern __imp_?data@bytestring@@QEAAPEAEXZ:PANYARGS
?data@bytestring@@QEAAPEAEXZ TEXTEQU <__imp_?data@bytestring@@QEAAPEAEXZ>
extern __imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PANYARGS
?fromasc@bytestring@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z TEXTEQU <__imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>
extern __imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z:PANYARGS
?fromasc@bytestring@@QEAA_NAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z TEXTEQU <__imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z>
extern __imp_?fromasc@bytestring@@QEAA_NPEBDH@Z:PANYARGS
?fromasc@bytestring@@QEAA_NPEBDH@Z TEXTEQU <__imp_?fromasc@bytestring@@QEAA_NPEBDH@Z>
extern __imp_?random@bytestring@@QEAAXH@Z:PANYARGS
?random@bytestring@@QEAAXH@Z TEXTEQU <__imp_?random@bytestring@@QEAAXH@Z>
extern __imp_?size@bytestring@@QEAAHXZ:PANYARGS
?size@bytestring@@QEAAHXZ TEXTEQU <__imp_?size@bytestring@@QEAAHXZ>
extern __imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PANYARGS
?toasc@bytestring@@QEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z TEXTEQU <__imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>
extern __imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z:PANYARGS
?toasc@bytestring@@QEAA_NAEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z TEXTEQU <__imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z>
extern __imp_acPatternIsMatched:PANYARGS
acPatternIsMatched TEXTEQU <__imp_acPatternIsMatched>
