extern __imp_??0ACCertificateExpiryNotificationInfo@@QEAA@AEBV0@@Z:PANYARGS
??0ACCertificateExpiryNotificationInfo@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ACCertificateExpiryNotificationInfo@@QEAA@AEBV0@@Z>
extern __imp_??0ACCertificateExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z:PANYARGS
??0ACCertificateExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z TEXTEQU <__imp_??0ACCertificateExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z>
extern __imp_??0ACExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAX@Z:PANYARGS
??0ACExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAX@Z TEXTEQU <__imp_??0ACExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAX@Z>
extern __imp_??0ACPoliciesDlg@@QEAA@PEAUPwdRuleArgs@@HPEAUtagRECT@@PEAVCWnd@@HHH@Z:PANYARGS
??0ACPoliciesDlg@@QEAA@PEAUPwdRuleArgs@@HPEAUtagRECT@@PEAVCWnd@@HHH@Z TEXTEQU <__imp_??0ACPoliciesDlg@@QEAA@PEAUPwdRuleArgs@@HPEAUtagRECT@@PEAVCWnd@@HHH@Z>
extern __imp_??0CBaseDialog@@QEAA@IHPEAUtagRECT@@PEAVCWnd@@@Z:PANYARGS
??0CBaseDialog@@QEAA@IHPEAUtagRECT@@PEAVCWnd@@@Z TEXTEQU <__imp_??0CBaseDialog@@QEAA@IHPEAUtagRECT@@PEAVCWnd@@@Z>
extern __imp_??0CCMLockedDlg@@QEAA@PEAVCWnd@@PEBD@Z:PANYARGS
??0CCMLockedDlg@@QEAA@PEAVCWnd@@PEBD@Z TEXTEQU <__imp_??0CCMLockedDlg@@QEAA@PEAVCWnd@@PEBD@Z>
extern __imp_??0CCapsLockSensitiveEdit@@QEAA@XZ:PANYARGS
??0CCapsLockSensitiveEdit@@QEAA@XZ TEXTEQU <__imp_??0CCapsLockSensitiveEdit@@QEAA@XZ>
extern __imp_??0CChangePINDialog@@QEAA@HH_NPEAUtagRECT@@PEAUPwdRuleArgs@@PEAVCButton@@PEAVCWnd@@HHH@Z:PANYARGS
??0CChangePINDialog@@QEAA@HH_NPEAUtagRECT@@PEAUPwdRuleArgs@@PEAVCButton@@PEAVCWnd@@HHH@Z TEXTEQU <__imp_??0CChangePINDialog@@QEAA@HH_NPEAUtagRECT@@PEAUPwdRuleArgs@@PEAVCButton@@PEAVCWnd@@HHH@Z>
extern __imp_??0CDisplayUCChild@@QEAA@HPEAUtagRECT@@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAVCWnd@@@Z:PANYARGS
??0CDisplayUCChild@@QEAA@HPEAUtagRECT@@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAVCWnd@@@Z TEXTEQU <__imp_??0CDisplayUCChild@@QEAA@HPEAUtagRECT@@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAVCWnd@@@Z>
extern __imp_??0CDisplayUnlockCodeDlg@@QEAA@PEAVCWnd@@PEBD1H@Z:PANYARGS
??0CDisplayUnlockCodeDlg@@QEAA@PEAVCWnd@@PEBD1H@Z TEXTEQU <__imp_??0CDisplayUnlockCodeDlg@@QEAA@PEAVCWnd@@PEBD1H@Z>
extern __imp_??0CInitializePinDlg@@QEAA@PEAVCWnd@@PEAUPINPolicies@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@HHHHHH@ZP6AH2@ZP6AH2AEAV34@@ZPEBD@Z:PANYARGS
??0CInitializePinDlg@@QEAA@PEAVCWnd@@PEAUPINPolicies@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@HHHHHH@ZP6AH2@ZP6AH2AEAV34@@ZPEBD@Z TEXTEQU <__imp_??0CInitializePinDlg@@QEAA@PEAVCWnd@@PEAUPINPolicies@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@HHHHHH@ZP6AH2@ZP6AH2AEAV34@@ZPEBD@Z>
extern __imp_??0CPopupAlert@@QEAA@XZ:PANYARGS
??0CPopupAlert@@QEAA@XZ TEXTEQU <__imp_??0CPopupAlert@@QEAA@XZ>
extern __imp_??0CResetCardDialog@@QEAA@HPEAUtagRECT@@PEAVCButton@@PEAVCWnd@@@Z:PANYARGS
??0CResetCardDialog@@QEAA@HPEAUtagRECT@@PEAVCButton@@PEAVCWnd@@@Z TEXTEQU <__imp_??0CResetCardDialog@@QEAA@HPEAUtagRECT@@PEAVCButton@@PEAVCWnd@@@Z>
extern __imp_??0CResetCardDialogMain@@QEAA@HPEAVCWnd@@HHHPEBD@Z:PANYARGS
??0CResetCardDialogMain@@QEAA@HPEAVCWnd@@HHHPEBD@Z TEXTEQU <__imp_??0CResetCardDialogMain@@QEAA@HPEAVCWnd@@HHHPEBD@Z>
extern __imp_??0CUnlockCardDlg@@QEAA@PEAVCWnd@@PEAUPwdRuleArgs@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@3@ZP6AH2AEAV34@@ZPEBD@Z:PANYARGS
??0CUnlockCardDlg@@QEAA@PEAVCWnd@@PEAUPwdRuleArgs@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@3@ZP6AH2AEAV34@@ZPEBD@Z TEXTEQU <__imp_??0CUnlockCardDlg@@QEAA@PEAVCWnd@@PEAUPwdRuleArgs@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@3@ZP6AH2AEAV34@@ZPEBD@Z>
extern __imp_??0CUnlockFailedDlg@@QEAA@PEAVCWnd@@PEBDH@Z:PANYARGS
??0CUnlockFailedDlg@@QEAA@PEAVCWnd@@PEBDH@Z TEXTEQU <__imp_??0CUnlockFailedDlg@@QEAA@PEAVCWnd@@PEBDH@Z>
extern __imp_??0CUnlockInitToolDlg@@QEAA@PEAVCWnd@@PEBDH@Z:PANYARGS
??0CUnlockInitToolDlg@@QEAA@PEAVCWnd@@PEBDH@Z TEXTEQU <__imp_??0CUnlockInitToolDlg@@QEAA@PEAVCWnd@@PEBDH@Z>
extern __imp_??0CUnlockSuccessDlg@@QEAA@PEAVCWnd@@@Z:PANYARGS
??0CUnlockSuccessDlg@@QEAA@PEAVCWnd@@@Z TEXTEQU <__imp_??0CUnlockSuccessDlg@@QEAA@PEAVCWnd@@@Z>
extern __imp_??1ACCertificateExpiryNotificationInfo@@QEAA@XZ:PANYARGS
??1ACCertificateExpiryNotificationInfo@@QEAA@XZ TEXTEQU <__imp_??1ACCertificateExpiryNotificationInfo@@QEAA@XZ>
extern __imp_??1ACExpiryNotificationInfo@@QEAA@XZ:PANYARGS
??1ACExpiryNotificationInfo@@QEAA@XZ TEXTEQU <__imp_??1ACExpiryNotificationInfo@@QEAA@XZ>
extern __imp_??1ACPoliciesDlg@@UEAA@XZ:PANYARGS
??1ACPoliciesDlg@@UEAA@XZ TEXTEQU <__imp_??1ACPoliciesDlg@@UEAA@XZ>
extern __imp_??1CBaseDialog@@UEAA@XZ:PANYARGS
??1CBaseDialog@@UEAA@XZ TEXTEQU <__imp_??1CBaseDialog@@UEAA@XZ>
extern __imp_??1CCMLockedDlg@@UEAA@XZ:PANYARGS
??1CCMLockedDlg@@UEAA@XZ TEXTEQU <__imp_??1CCMLockedDlg@@UEAA@XZ>
extern __imp_??1CCapsLockSensitiveEdit@@UEAA@XZ:PANYARGS
??1CCapsLockSensitiveEdit@@UEAA@XZ TEXTEQU <__imp_??1CCapsLockSensitiveEdit@@UEAA@XZ>
extern __imp_??1CChangePINDialog@@UEAA@XZ:PANYARGS
??1CChangePINDialog@@UEAA@XZ TEXTEQU <__imp_??1CChangePINDialog@@UEAA@XZ>
extern __imp_??1CDisplayUCChild@@UEAA@XZ:PANYARGS
??1CDisplayUCChild@@UEAA@XZ TEXTEQU <__imp_??1CDisplayUCChild@@UEAA@XZ>
extern __imp_??1CDisplayUnlockCodeDlg@@UEAA@XZ:PANYARGS
??1CDisplayUnlockCodeDlg@@UEAA@XZ TEXTEQU <__imp_??1CDisplayUnlockCodeDlg@@UEAA@XZ>
extern __imp_??1CInitializePinDlg@@UEAA@XZ:PANYARGS
??1CInitializePinDlg@@UEAA@XZ TEXTEQU <__imp_??1CInitializePinDlg@@UEAA@XZ>
extern __imp_??1CPopupAlert@@UEAA@XZ:PANYARGS
??1CPopupAlert@@UEAA@XZ TEXTEQU <__imp_??1CPopupAlert@@UEAA@XZ>
extern __imp_??1CResetCardDialog@@UEAA@XZ:PANYARGS
??1CResetCardDialog@@UEAA@XZ TEXTEQU <__imp_??1CResetCardDialog@@UEAA@XZ>
extern __imp_??1CResetCardDialogMain@@UEAA@XZ:PANYARGS
??1CResetCardDialogMain@@UEAA@XZ TEXTEQU <__imp_??1CResetCardDialogMain@@UEAA@XZ>
extern __imp_??1CUnlockCardDlg@@UEAA@XZ:PANYARGS
??1CUnlockCardDlg@@UEAA@XZ TEXTEQU <__imp_??1CUnlockCardDlg@@UEAA@XZ>
extern __imp_??1CUnlockFailedDlg@@UEAA@XZ:PANYARGS
??1CUnlockFailedDlg@@UEAA@XZ TEXTEQU <__imp_??1CUnlockFailedDlg@@UEAA@XZ>
extern __imp_??1CUnlockInitToolDlg@@UEAA@XZ:PANYARGS
??1CUnlockInitToolDlg@@UEAA@XZ TEXTEQU <__imp_??1CUnlockInitToolDlg@@UEAA@XZ>
extern __imp_??1CUnlockSuccessDlg@@UEAA@XZ:PANYARGS
??1CUnlockSuccessDlg@@UEAA@XZ TEXTEQU <__imp_??1CUnlockSuccessDlg@@UEAA@XZ>
extern __imp_??4ACCertificateExpiryNotificationInfo@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ACCertificateExpiryNotificationInfo@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ACCertificateExpiryNotificationInfo@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_7ACPoliciesDlg@@6B@:PANYARGS
??_7ACPoliciesDlg@@6B@ TEXTEQU <__imp_??_7ACPoliciesDlg@@6B@>
extern __imp_??_7CBaseDialog@@6B@:PANYARGS
??_7CBaseDialog@@6B@ TEXTEQU <__imp_??_7CBaseDialog@@6B@>
extern __imp_??_7CCMLockedDlg@@6B@:PANYARGS
??_7CCMLockedDlg@@6B@ TEXTEQU <__imp_??_7CCMLockedDlg@@6B@>
extern __imp_??_7CCapsLockSensitiveEdit@@6B@:PANYARGS
??_7CCapsLockSensitiveEdit@@6B@ TEXTEQU <__imp_??_7CCapsLockSensitiveEdit@@6B@>
extern __imp_??_7CChangePINDialog@@6B@:PANYARGS
??_7CChangePINDialog@@6B@ TEXTEQU <__imp_??_7CChangePINDialog@@6B@>
extern __imp_??_7CDisplayUCChild@@6B@:PANYARGS
??_7CDisplayUCChild@@6B@ TEXTEQU <__imp_??_7CDisplayUCChild@@6B@>
extern __imp_??_7CDisplayUnlockCodeDlg@@6B@:PANYARGS
??_7CDisplayUnlockCodeDlg@@6B@ TEXTEQU <__imp_??_7CDisplayUnlockCodeDlg@@6B@>
extern __imp_??_7CInitializePinDlg@@6B@:PANYARGS
??_7CInitializePinDlg@@6B@ TEXTEQU <__imp_??_7CInitializePinDlg@@6B@>
extern __imp_??_7CPopupAlert@@6B@:PANYARGS
??_7CPopupAlert@@6B@ TEXTEQU <__imp_??_7CPopupAlert@@6B@>
extern __imp_??_7CResetCardDialog@@6B@:PANYARGS
??_7CResetCardDialog@@6B@ TEXTEQU <__imp_??_7CResetCardDialog@@6B@>
extern __imp_??_7CResetCardDialogMain@@6B@:PANYARGS
??_7CResetCardDialogMain@@6B@ TEXTEQU <__imp_??_7CResetCardDialogMain@@6B@>
extern __imp_??_7CUnlockCardDlg@@6B@:PANYARGS
??_7CUnlockCardDlg@@6B@ TEXTEQU <__imp_??_7CUnlockCardDlg@@6B@>
extern __imp_??_7CUnlockFailedDlg@@6B@:PANYARGS
??_7CUnlockFailedDlg@@6B@ TEXTEQU <__imp_??_7CUnlockFailedDlg@@6B@>
extern __imp_??_7CUnlockInitToolDlg@@6B@:PANYARGS
??_7CUnlockInitToolDlg@@6B@ TEXTEQU <__imp_??_7CUnlockInitToolDlg@@6B@>
extern __imp_??_7CUnlockSuccessDlg@@6B@:PANYARGS
??_7CUnlockSuccessDlg@@6B@ TEXTEQU <__imp_??_7CUnlockSuccessDlg@@6B@>
extern __imp_??_FCDisplayUCChild@@QEAAXXZ:PANYARGS
??_FCDisplayUCChild@@QEAAXXZ TEXTEQU <__imp_??_FCDisplayUCChild@@QEAAXXZ>
extern __imp_??_FCResetCardDialog@@QEAAXXZ:PANYARGS
??_FCResetCardDialog@@QEAAXXZ TEXTEQU <__imp_??_FCResetCardDialog@@QEAAXXZ>
extern __imp_??_FCUnlockSuccessDlg@@QEAAXXZ:PANYARGS
??_FCUnlockSuccessDlg@@QEAAXXZ TEXTEQU <__imp_??_FCUnlockSuccessDlg@@QEAAXXZ>
extern __imp_?AddCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z:PANYARGS
?AddCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z TEXTEQU <__imp_?AddCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z>
extern __imp_?AdjustWindow@CCMLockedDlg@@IEAAXXZ:PANYARGS
?AdjustWindow@CCMLockedDlg@@IEAAXXZ TEXTEQU <__imp_?AdjustWindow@CCMLockedDlg@@IEAAXXZ>
extern __imp_?CheckCapsLockMessage@CCapsLockSensitiveEdit@@IEAAXXZ:PANYARGS
?CheckCapsLockMessage@CCapsLockSensitiveEdit@@IEAAXXZ TEXTEQU <__imp_?CheckCapsLockMessage@CCapsLockSensitiveEdit@@IEAAXXZ>
extern __imp_?CheckWindow@CResetCardDialog@@QEAAX_N@Z:PANYARGS
?CheckWindow@CResetCardDialog@@QEAAX_N@Z TEXTEQU <__imp_?CheckWindow@CResetCardDialog@@QEAAX_N@Z>
extern __imp_?Create@CPopupAlert@@QEAAHPEAUHWND__@@@Z:PANYARGS
?Create@CPopupAlert@@QEAAHPEAUHWND__@@@Z TEXTEQU <__imp_?Create@CPopupAlert@@QEAAHPEAUHWND__@@@Z>
extern __imp_?DisablePIN@CResetCardDialog@@QEAAXXZ:PANYARGS
?DisablePIN@CResetCardDialog@@QEAAXXZ TEXTEQU <__imp_?DisablePIN@CResetCardDialog@@QEAAXXZ>
extern __imp_DisplayCardExpiryNotification:PANYARGS
DisplayCardExpiryNotification TEXTEQU <__imp_DisplayCardExpiryNotification>
extern __imp_DisplayLastPINTry:PANYARGS
DisplayLastPINTry TEXTEQU <__imp_DisplayLastPINTry>
extern __imp_DisplayUnlockCode:PANYARGS
DisplayUnlockCode TEXTEQU <__imp_DisplayUnlockCode>
extern __imp_?DoDataExchange@ACPoliciesDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@ACPoliciesDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@ACPoliciesDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CBaseDialog@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CBaseDialog@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CBaseDialog@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CCMLockedDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CCMLockedDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CCMLockedDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CChangePINDialog@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CChangePINDialog@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CChangePINDialog@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CDisplayUCChild@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CDisplayUCChild@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CDisplayUCChild@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CDisplayUnlockCodeDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CDisplayUnlockCodeDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CDisplayUnlockCodeDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CInitializePinDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CInitializePinDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CInitializePinDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CResetCardDialog@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CResetCardDialog@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CResetCardDialog@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CResetCardDialogMain@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CResetCardDialogMain@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CResetCardDialogMain@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CUnlockCardDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CUnlockCardDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CUnlockCardDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CUnlockFailedDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CUnlockFailedDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CUnlockFailedDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CUnlockInitToolDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CUnlockInitToolDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CUnlockInitToolDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoDataExchange@CUnlockSuccessDlg@@MEAAXPEAVCDataExchange@@@Z:PANYARGS
?DoDataExchange@CUnlockSuccessDlg@@MEAAXPEAVCDataExchange@@@Z TEXTEQU <__imp_?DoDataExchange@CUnlockSuccessDlg@@MEAAXPEAVCDataExchange@@@Z>
extern __imp_?DoModal@CCMLockedDlg@@UEAA_JXZ:PANYARGS
?DoModal@CCMLockedDlg@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CCMLockedDlg@@UEAA_JXZ>
extern __imp_?DoModal@CDisplayUnlockCodeDlg@@UEAA_JXZ:PANYARGS
?DoModal@CDisplayUnlockCodeDlg@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CDisplayUnlockCodeDlg@@UEAA_JXZ>
extern __imp_?DoModal@CInitializePinDlg@@UEAA_JXZ:PANYARGS
?DoModal@CInitializePinDlg@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CInitializePinDlg@@UEAA_JXZ>
extern __imp_?DoModal@CResetCardDialogMain@@UEAA_JXZ:PANYARGS
?DoModal@CResetCardDialogMain@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CResetCardDialogMain@@UEAA_JXZ>
extern __imp_?DoModal@CUnlockCardDlg@@UEAA_JXZ:PANYARGS
?DoModal@CUnlockCardDlg@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CUnlockCardDlg@@UEAA_JXZ>
extern __imp_?DoModal@CUnlockFailedDlg@@UEAA_JXZ:PANYARGS
?DoModal@CUnlockFailedDlg@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CUnlockFailedDlg@@UEAA_JXZ>
extern __imp_?DoModal@CUnlockInitToolDlg@@UEAA_JXZ:PANYARGS
?DoModal@CUnlockInitToolDlg@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CUnlockInitToolDlg@@UEAA_JXZ>
extern __imp_?DoModal@CUnlockSuccessDlg@@UEAA_JXZ:PANYARGS
?DoModal@CUnlockSuccessDlg@@UEAA_JXZ TEXTEQU <__imp_?DoModal@CUnlockSuccessDlg@@UEAA_JXZ>
extern __imp_?EraseAllPinBuffers@CChangePINDialog@@QEAAXXZ:PANYARGS
?EraseAllPinBuffers@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?EraseAllPinBuffers@CChangePINDialog@@QEAAXXZ>
extern __imp_FreeGetPinBuffer:PANYARGS
FreeGetPinBuffer TEXTEQU <__imp_FreeGetPinBuffer>
extern __imp_?GenerateRegion@CPopupAlert@@IEAAPEAUHRGN__@@PEAUHBITMAP__@@EEE@Z:PANYARGS
?GenerateRegion@CPopupAlert@@IEAAPEAUHRGN__@@PEAUHBITMAP__@@EEE@Z TEXTEQU <__imp_?GenerateRegion@CPopupAlert@@IEAAPEAUHRGN__@@PEAUHBITMAP__@@EEE@Z>
extern __imp_?Get24BitPixels@CPopupAlert@@IEAAPEAEPEAUHBITMAP__@@PEAG1@Z:PANYARGS
?Get24BitPixels@CPopupAlert@@IEAAPEAEPEAUHBITMAP__@@PEAG1@Z TEXTEQU <__imp_?Get24BitPixels@CPopupAlert@@IEAAPEAEPEAUHBITMAP__@@PEAG1@Z>
extern __imp_?GetCancelEvent@ACExpiryNotificationInfo@@QEAAPEAXXZ:PANYARGS
?GetCancelEvent@ACExpiryNotificationInfo@@QEAAPEAXXZ TEXTEQU <__imp_?GetCancelEvent@ACExpiryNotificationInfo@@QEAAPEAXXZ>
extern __imp_?GetCertificateExpiryDate@ACCertificateExpiryNotificationInfo@@QEAAAEAVCTime@ATL@@XZ:PANYARGS
?GetCertificateExpiryDate@ACCertificateExpiryNotificationInfo@@QEAAAEAVCTime@ATL@@XZ TEXTEQU <__imp_?GetCertificateExpiryDate@ACCertificateExpiryNotificationInfo@@QEAAAEAVCTime@ATL@@XZ>
extern __imp_?GetCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAPEAVACCertificateExpiryNotificationInfo@@H@Z:PANYARGS
?GetCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAPEAVACCertificateExpiryNotificationInfo@@H@Z TEXTEQU <__imp_?GetCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAPEAVACCertificateExpiryNotificationInfo@@H@Z>
extern __imp_GetChangePINInfoFromUser:PANYARGS
GetChangePINInfoFromUser TEXTEQU <__imp_GetChangePINInfoFromUser>
extern __imp_GetErrorString:PANYARGS
GetErrorString TEXTEQU <__imp_GetErrorString>
extern __imp_?GetFriendlyName@ACCertificateExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PANYARGS
?GetFriendlyName@ACCertificateExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ TEXTEQU <__imp_?GetFriendlyName@ACCertificateExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>
extern __imp_?GetMessageMap@ACPoliciesDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@ACPoliciesDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@ACPoliciesDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CBaseDialog@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CBaseDialog@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CBaseDialog@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CCMLockedDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CCMLockedDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CCMLockedDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CCapsLockSensitiveEdit@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CCapsLockSensitiveEdit@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CCapsLockSensitiveEdit@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CChangePINDialog@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CChangePINDialog@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CChangePINDialog@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CDisplayUCChild@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CDisplayUCChild@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CDisplayUCChild@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CDisplayUnlockCodeDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CDisplayUnlockCodeDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CDisplayUnlockCodeDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CInitializePinDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CInitializePinDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CInitializePinDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CPopupAlert@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CPopupAlert@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CPopupAlert@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CResetCardDialog@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CResetCardDialog@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CResetCardDialog@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CResetCardDialogMain@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CResetCardDialogMain@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CResetCardDialogMain@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CUnlockCardDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CUnlockCardDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CUnlockCardDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CUnlockFailedDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CUnlockFailedDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CUnlockFailedDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CUnlockInitToolDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CUnlockInitToolDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CUnlockInitToolDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetMessageMap@CUnlockSuccessDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetMessageMap@CUnlockSuccessDlg@@MEBAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetMessageMap@CUnlockSuccessDlg@@MEBAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetNbCertExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAHXZ:PANYARGS
?GetNbCertExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAHXZ TEXTEQU <__imp_?GetNbCertExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAHXZ>
extern __imp_?GetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAHXZ:PANYARGS
?GetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAHXZ TEXTEQU <__imp_?GetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAHXZ>
extern __imp_GetPINFromUser:PANYARGS
GetPINFromUser TEXTEQU <__imp_GetPINFromUser>
extern __imp_?GetPin@CResetCardDialog@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PANYARGS
?GetPin@CResetCardDialog@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ TEXTEQU <__imp_?GetPin@CResetCardDialog@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>
extern __imp_?GetPin@CResetCardDialogMain@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PANYARGS
?GetPin@CResetCardDialogMain@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ TEXTEQU <__imp_?GetPin@CResetCardDialogMain@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>
extern __imp_?GetReaderName@ACExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PANYARGS
?GetReaderName@ACExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ TEXTEQU <__imp_?GetReaderName@ACExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>
extern __imp_?GetRegistryParameters@CPopupAlert@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAKH@Z:PANYARGS
?GetRegistryParameters@CPopupAlert@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAKH@Z TEXTEQU <__imp_?GetRegistryParameters@CPopupAlert@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAKH@Z>
extern __imp_?GetRuntimeClass@ACPoliciesDlg@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@ACPoliciesDlg@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@ACPoliciesDlg@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CBaseDialog@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CBaseDialog@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CBaseDialog@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CCMLockedDlg@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CCMLockedDlg@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CCMLockedDlg@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CCapsLockSensitiveEdit@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CCapsLockSensitiveEdit@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CCapsLockSensitiveEdit@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CChangePINDialog@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CChangePINDialog@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CChangePINDialog@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CDisplayUCChild@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CDisplayUCChild@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CDisplayUCChild@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CDisplayUnlockCodeDlg@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CDisplayUnlockCodeDlg@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CDisplayUnlockCodeDlg@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CPopupAlert@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CPopupAlert@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CPopupAlert@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CResetCardDialog@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CResetCardDialog@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CResetCardDialog@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CResetCardDialogMain@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CResetCardDialogMain@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CResetCardDialogMain@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetRuntimeClass@CUnlockInitToolDlg@@UEBAPEAUCRuntimeClass@@XZ:PANYARGS
?GetRuntimeClass@CUnlockInitToolDlg@@UEBAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetRuntimeClass@CUnlockInitToolDlg@@UEBAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@ACPoliciesDlg@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@ACPoliciesDlg@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@ACPoliciesDlg@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CBaseDialog@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CBaseDialog@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CBaseDialog@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CCMLockedDlg@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CCMLockedDlg@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CCMLockedDlg@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CCapsLockSensitiveEdit@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CCapsLockSensitiveEdit@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CCapsLockSensitiveEdit@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CChangePINDialog@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CChangePINDialog@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CChangePINDialog@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CDisplayUCChild@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CDisplayUCChild@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CDisplayUCChild@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CDisplayUnlockCodeDlg@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CDisplayUnlockCodeDlg@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CDisplayUnlockCodeDlg@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CPopupAlert@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CPopupAlert@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CPopupAlert@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CResetCardDialog@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CResetCardDialog@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CResetCardDialog@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CResetCardDialogMain@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CResetCardDialogMain@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CResetCardDialogMain@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisClass@CUnlockInitToolDlg@@SAPEAUCRuntimeClass@@XZ:PANYARGS
?GetThisClass@CUnlockInitToolDlg@@SAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?GetThisClass@CUnlockInitToolDlg@@SAPEAUCRuntimeClass@@XZ>
extern __imp_?GetThisMessageMap@ACPoliciesDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@ACPoliciesDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@ACPoliciesDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CBaseDialog@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CBaseDialog@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CBaseDialog@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CCMLockedDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CCMLockedDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CCMLockedDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CCapsLockSensitiveEdit@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CCapsLockSensitiveEdit@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CCapsLockSensitiveEdit@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CChangePINDialog@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CChangePINDialog@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CChangePINDialog@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CDisplayUCChild@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CDisplayUCChild@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CDisplayUCChild@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CDisplayUnlockCodeDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CDisplayUnlockCodeDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CDisplayUnlockCodeDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CInitializePinDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CInitializePinDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CInitializePinDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CPopupAlert@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CPopupAlert@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CPopupAlert@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CResetCardDialog@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CResetCardDialog@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CResetCardDialog@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CResetCardDialogMain@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CResetCardDialogMain@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CResetCardDialogMain@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CUnlockCardDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CUnlockCardDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CUnlockCardDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CUnlockFailedDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CUnlockFailedDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CUnlockFailedDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CUnlockInitToolDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CUnlockInitToolDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CUnlockInitToolDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?GetThisMessageMap@CUnlockSuccessDlg@@KAPEBUAFX_MSGMAP@@XZ:PANYARGS
?GetThisMessageMap@CUnlockSuccessDlg@@KAPEBUAFX_MSGMAP@@XZ TEXTEQU <__imp_?GetThisMessageMap@CUnlockSuccessDlg@@KAPEBUAFX_MSGMAP@@XZ>
extern __imp_?Hide@CPopupAlert@@QEAAXXZ:PANYARGS
?Hide@CPopupAlert@@QEAAXXZ TEXTEQU <__imp_?Hide@CPopupAlert@@QEAAXXZ>
extern __imp_?HidePinFromMemory@CBaseDialog@@IEAAXAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PANYARGS
?HidePinFromMemory@CBaseDialog@@IEAAXAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z TEXTEQU <__imp_?HidePinFromMemory@CBaseDialog@@IEAAXAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>
extern __imp_InitGUIDll:PANYARGS
InitGUIDll TEXTEQU <__imp_InitGUIDll>
extern __imp_?InitWindow@CPopupAlert@@QEAA_NPEAUHWND__@@HK@Z:PANYARGS
?InitWindow@CPopupAlert@@QEAA_NPEAUHWND__@@HK@Z TEXTEQU <__imp_?InitWindow@CPopupAlert@@QEAA_NPEAUHWND__@@HK@Z>
extern __imp_?IsAlphaPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PANYARGS
?IsAlphaPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z TEXTEQU <__imp_?IsAlphaPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>
extern __imp_?IsNeverDisplayChecked@CDisplayUCChild@@QEAAHXZ:PANYARGS
?IsNeverDisplayChecked@CDisplayUCChild@@QEAAHXZ TEXTEQU <__imp_?IsNeverDisplayChecked@CDisplayUCChild@@QEAAHXZ>
extern __imp_?IsPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PANYARGS
?IsPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z TEXTEQU <__imp_?IsPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>
extern __imp_?IsPointOnArea@CPopupAlert@@AEAA_NPEAVCPoint@@PEAVCRect@@@Z:PANYARGS
?IsPointOnArea@CPopupAlert@@AEAA_NPEAVCPoint@@PEAVCRect@@@Z TEXTEQU <__imp_?IsPointOnArea@CPopupAlert@@AEAA_NPEAVCPoint@@PEAVCRect@@@Z>
extern __imp_?LocCreate@ACPoliciesDlg@@QEAAHPEAVCWnd@@@Z:PANYARGS
?LocCreate@ACPoliciesDlg@@QEAAHPEAVCWnd@@@Z TEXTEQU <__imp_?LocCreate@ACPoliciesDlg@@QEAAHPEAVCWnd@@@Z>
extern __imp_?LocCreate@CChangePINDialog@@QEAAHPEAVCWnd@@@Z:PANYARGS
?LocCreate@CChangePINDialog@@QEAAHPEAVCWnd@@@Z TEXTEQU <__imp_?LocCreate@CChangePINDialog@@QEAAHPEAVCWnd@@@Z>
extern __imp_?LocCreate@CDisplayUCChild@@QEAAHPEAVCWnd@@@Z:PANYARGS
?LocCreate@CDisplayUCChild@@QEAAHPEAVCWnd@@@Z TEXTEQU <__imp_?LocCreate@CDisplayUCChild@@QEAAHPEAVCWnd@@@Z>
extern __imp_?LocCreate@CResetCardDialog@@QEAAHPEAVCWnd@@@Z:PANYARGS
?LocCreate@CResetCardDialog@@QEAAHPEAVCWnd@@@Z TEXTEQU <__imp_?LocCreate@CResetCardDialog@@QEAAHPEAVCWnd@@@Z>
extern __imp_?MoveDlgItem@CResetCardDialogMain@@AEAAXHHH@Z:PANYARGS
?MoveDlgItem@CResetCardDialogMain@@AEAAXHHH@Z TEXTEQU <__imp_?MoveDlgItem@CResetCardDialogMain@@AEAAXHHH@Z>
extern __imp_?MoveUpWindow@CInitializePinDlg@@IEAAXIH@Z:PANYARGS
?MoveUpWindow@CInitializePinDlg@@IEAAXIH@Z TEXTEQU <__imp_?MoveUpWindow@CInitializePinDlg@@IEAAXIH@Z>
extern __imp_?MoveUpWindow@CUnlockCardDlg@@IEAAXIH@Z:PANYARGS
?MoveUpWindow@CUnlockCardDlg@@IEAAXIH@Z TEXTEQU <__imp_?MoveUpWindow@CUnlockCardDlg@@IEAAXIH@Z>
extern __imp_?MustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAHAEAVCTime@ATL@@@Z:PANYARGS
?MustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAHAEAVCTime@ATL@@@Z TEXTEQU <__imp_?MustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAHAEAVCTime@ATL@@@Z>
extern __imp_?OnBnClickedStaticNp@CUnlockCardDlg@@QEAAXXZ:PANYARGS
?OnBnClickedStaticNp@CUnlockCardDlg@@QEAAXXZ TEXTEQU <__imp_?OnBnClickedStaticNp@CUnlockCardDlg@@QEAAXXZ>
extern __imp_?OnCancel@CUnlockCardDlg@@MEAAXXZ:PANYARGS
?OnCancel@CUnlockCardDlg@@MEAAXXZ TEXTEQU <__imp_?OnCancel@CUnlockCardDlg@@MEAAXXZ>
extern __imp_?OnCardEvent@CPopupAlert@@QEAA_J_K_J@Z:PANYARGS
?OnCardEvent@CPopupAlert@@QEAA_J_K_J@Z TEXTEQU <__imp_?OnCardEvent@CPopupAlert@@QEAA_J_K_J@Z>
extern __imp_?OnCardEvent@CResetCardDialogMain@@IEAA_J_K_J@Z:PANYARGS
?OnCardEvent@CResetCardDialogMain@@IEAA_J_K_J@Z TEXTEQU <__imp_?OnCardEvent@CResetCardDialogMain@@IEAA_J_K_J@Z>
extern __imp_?OnCardEvent@CUnlockCardDlg@@IEAA_J_K_J@Z:PANYARGS
?OnCardEvent@CUnlockCardDlg@@IEAA_J_K_J@Z TEXTEQU <__imp_?OnCardEvent@CUnlockCardDlg@@IEAA_J_K_J@Z>
extern __imp_?OnChangeEdit@CUnlockCardDlg@@IEAAXXZ:PANYARGS
?OnChangeEdit@CUnlockCardDlg@@IEAAXXZ TEXTEQU <__imp_?OnChangeEdit@CUnlockCardDlg@@IEAAXXZ>
extern __imp_?OnChangeEditNewPin@CInitializePinDlg@@IEAAXXZ:PANYARGS
?OnChangeEditNewPin@CInitializePinDlg@@IEAAXXZ TEXTEQU <__imp_?OnChangeEditNewPin@CInitializePinDlg@@IEAAXXZ>
extern __imp_?OnCheckOkButton@CResetCardDialog@@IEAAXXZ:PANYARGS
?OnCheckOkButton@CResetCardDialog@@IEAAXXZ TEXTEQU <__imp_?OnCheckOkButton@CResetCardDialog@@IEAAXXZ>
extern __imp_?OnContextualHelp@CCMLockedDlg@@MEAAXXZ:PANYARGS
?OnContextualHelp@CCMLockedDlg@@MEAAXXZ TEXTEQU <__imp_?OnContextualHelp@CCMLockedDlg@@MEAAXXZ>
extern __imp_?OnContextualHelp@CUnlockCardDlg@@MEAAXXZ:PANYARGS
?OnContextualHelp@CUnlockCardDlg@@MEAAXXZ TEXTEQU <__imp_?OnContextualHelp@CUnlockCardDlg@@MEAAXXZ>
extern __imp_?OnCreate@CPopupAlert@@QEAAHPEAUtagCREATESTRUCTA@@@Z:PANYARGS
?OnCreate@CPopupAlert@@QEAAHPEAUtagCREATESTRUCTA@@@Z TEXTEQU <__imp_?OnCreate@CPopupAlert@@QEAAHPEAUtagCREATESTRUCTA@@@Z>
extern __imp_?OnCtlColor@CBaseDialog@@QEAAPEAUHBRUSH__@@PEAVCDC@@PEAVCWnd@@I@Z:PANYARGS
?OnCtlColor@CBaseDialog@@QEAAPEAUHBRUSH__@@PEAVCDC@@PEAVCWnd@@I@Z TEXTEQU <__imp_?OnCtlColor@CBaseDialog@@QEAAPEAUHBRUSH__@@PEAVCDC@@PEAVCWnd@@I@Z>
extern __imp_?OnDestroy@CChangePINDialog@@QEAAXXZ:PANYARGS
?OnDestroy@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?OnDestroy@CChangePINDialog@@QEAAXXZ>
extern __imp_?OnDestroy@CDisplayUnlockCodeDlg@@IEAAXXZ:PANYARGS
?OnDestroy@CDisplayUnlockCodeDlg@@IEAAXXZ TEXTEQU <__imp_?OnDestroy@CDisplayUnlockCodeDlg@@IEAAXXZ>
extern __imp_?OnDestroy@CPopupAlert@@QEAAXXZ:PANYARGS
?OnDestroy@CPopupAlert@@QEAAXXZ TEXTEQU <__imp_?OnDestroy@CPopupAlert@@QEAAXXZ>
extern __imp_?OnDestroy@CResetCardDialogMain@@IEAAXXZ:PANYARGS
?OnDestroy@CResetCardDialogMain@@IEAAXXZ TEXTEQU <__imp_?OnDestroy@CResetCardDialogMain@@IEAAXXZ>
extern __imp_?OnDestroy@CUnlockCardDlg@@IEAAXXZ:PANYARGS
?OnDestroy@CUnlockCardDlg@@IEAAXXZ TEXTEQU <__imp_?OnDestroy@CUnlockCardDlg@@IEAAXXZ>
extern __imp_?OnDisplayPINPolicies@CInitializePinDlg@@IEAA_J_K_J@Z:PANYARGS
?OnDisplayPINPolicies@CInitializePinDlg@@IEAA_J_K_J@Z TEXTEQU <__imp_?OnDisplayPINPolicies@CInitializePinDlg@@IEAA_J_K_J@Z>
extern __imp_?OnDisplayPINPolicies@CUnlockCardDlg@@IEAA_J_K_J@Z:PANYARGS
?OnDisplayPINPolicies@CUnlockCardDlg@@IEAA_J_K_J@Z TEXTEQU <__imp_?OnDisplayPINPolicies@CUnlockCardDlg@@IEAA_J_K_J@Z>
extern __imp_?OnEnChangeEditPin@CChangePINDialog@@QEAAXXZ:PANYARGS
?OnEnChangeEditPin@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?OnEnChangeEditPin@CChangePINDialog@@QEAAXXZ>
extern __imp_?OnEnChangeEditPinConfirm@CChangePINDialog@@QEAAXXZ:PANYARGS
?OnEnChangeEditPinConfirm@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?OnEnChangeEditPinConfirm@CChangePINDialog@@QEAAXXZ>
extern __imp_?OnEnChangeEditPinNew@CChangePINDialog@@QEAAXXZ:PANYARGS
?OnEnChangeEditPinNew@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?OnEnChangeEditPinNew@CChangePINDialog@@QEAAXXZ>
extern __imp_?OnEnSetfocusEditPin@CChangePINDialog@@QEAAXXZ:PANYARGS
?OnEnSetfocusEditPin@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?OnEnSetfocusEditPin@CChangePINDialog@@QEAAXXZ>
extern __imp_?OnEnSetfocusEditPinConfirm@CChangePINDialog@@QEAAXXZ:PANYARGS
?OnEnSetfocusEditPinConfirm@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?OnEnSetfocusEditPinConfirm@CChangePINDialog@@QEAAXXZ>
extern __imp_?OnEnSetfocusEditPinNew@CChangePINDialog@@QEAAXXZ:PANYARGS
?OnEnSetfocusEditPinNew@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?OnEnSetfocusEditPinNew@CChangePINDialog@@QEAAXXZ>
extern __imp_?OnEraseBkgnd@CPopupAlert@@QEAAHPEAVCDC@@@Z:PANYARGS
?OnEraseBkgnd@CPopupAlert@@QEAAHPEAVCDC@@@Z TEXTEQU <__imp_?OnEraseBkgnd@CPopupAlert@@QEAAHPEAVCDC@@@Z>
extern __imp_?OnInitDialog@ACPoliciesDlg@@MEAAHXZ:PANYARGS
?OnInitDialog@ACPoliciesDlg@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@ACPoliciesDlg@@MEAAHXZ>
extern __imp_?OnInitDialog@CBaseDialog@@MEAAHXZ:PANYARGS
?OnInitDialog@CBaseDialog@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CBaseDialog@@MEAAHXZ>
extern __imp_?OnInitDialog@CCMLockedDlg@@UEAAHXZ:PANYARGS
?OnInitDialog@CCMLockedDlg@@UEAAHXZ TEXTEQU <__imp_?OnInitDialog@CCMLockedDlg@@UEAAHXZ>
extern __imp_?OnInitDialog@CChangePINDialog@@MEAAHXZ:PANYARGS
?OnInitDialog@CChangePINDialog@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CChangePINDialog@@MEAAHXZ>
extern __imp_?OnInitDialog@CDisplayUnlockCodeDlg@@MEAAHXZ:PANYARGS
?OnInitDialog@CDisplayUnlockCodeDlg@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CDisplayUnlockCodeDlg@@MEAAHXZ>
extern __imp_?OnInitDialog@CInitializePinDlg@@MEAAHXZ:PANYARGS
?OnInitDialog@CInitializePinDlg@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CInitializePinDlg@@MEAAHXZ>
extern __imp_?OnInitDialog@CResetCardDialog@@MEAAHXZ:PANYARGS
?OnInitDialog@CResetCardDialog@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CResetCardDialog@@MEAAHXZ>
extern __imp_?OnInitDialog@CResetCardDialogMain@@MEAAHXZ:PANYARGS
?OnInitDialog@CResetCardDialogMain@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CResetCardDialogMain@@MEAAHXZ>
extern __imp_?OnInitDialog@CUnlockCardDlg@@MEAAHXZ:PANYARGS
?OnInitDialog@CUnlockCardDlg@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CUnlockCardDlg@@MEAAHXZ>
extern __imp_?OnInitDialog@CUnlockFailedDlg@@MEAAHXZ:PANYARGS
?OnInitDialog@CUnlockFailedDlg@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CUnlockFailedDlg@@MEAAHXZ>
extern __imp_?OnInitDialog@CUnlockInitToolDlg@@UEAAHXZ:PANYARGS
?OnInitDialog@CUnlockInitToolDlg@@UEAAHXZ TEXTEQU <__imp_?OnInitDialog@CUnlockInitToolDlg@@UEAAHXZ>
extern __imp_?OnInitDialog@CUnlockSuccessDlg@@MEAAHXZ:PANYARGS
?OnInitDialog@CUnlockSuccessDlg@@MEAAHXZ TEXTEQU <__imp_?OnInitDialog@CUnlockSuccessDlg@@MEAAHXZ>
extern __imp_?OnKeyUp@CCapsLockSensitiveEdit@@QEAAXIII@Z:PANYARGS
?OnKeyUp@CCapsLockSensitiveEdit@@QEAAXIII@Z TEXTEQU <__imp_?OnKeyUp@CCapsLockSensitiveEdit@@QEAAXIII@Z>
extern __imp_?OnKillFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z:PANYARGS
?OnKillFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z TEXTEQU <__imp_?OnKillFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z>
extern __imp_?OnMove@CChangePINDialog@@QEAAXHH@Z:PANYARGS
?OnMove@CChangePINDialog@@QEAAXHH@Z TEXTEQU <__imp_?OnMove@CChangePINDialog@@QEAAXHH@Z>
extern __imp_?OnMove@CInitializePinDlg@@QEAAXHH@Z:PANYARGS
?OnMove@CInitializePinDlg@@QEAAXHH@Z TEXTEQU <__imp_?OnMove@CInitializePinDlg@@QEAAXHH@Z>
extern __imp_?OnMove@CResetCardDialog@@QEAAXHH@Z:PANYARGS
?OnMove@CResetCardDialog@@QEAAXHH@Z TEXTEQU <__imp_?OnMove@CResetCardDialog@@QEAAXHH@Z>
extern __imp_?OnMove@CResetCardDialogMain@@QEAAXHH@Z:PANYARGS
?OnMove@CResetCardDialogMain@@QEAAXHH@Z TEXTEQU <__imp_?OnMove@CResetCardDialogMain@@QEAAXHH@Z>
extern __imp_?OnMove@CUnlockCardDlg@@QEAAXHH@Z:PANYARGS
?OnMove@CUnlockCardDlg@@QEAAXHH@Z TEXTEQU <__imp_?OnMove@CUnlockCardDlg@@QEAAXHH@Z>
extern __imp_?OnNcHitTest@CPopupAlert@@QEAA_JVCPoint@@@Z:PANYARGS
?OnNcHitTest@CPopupAlert@@QEAA_JVCPoint@@@Z TEXTEQU <__imp_?OnNcHitTest@CPopupAlert@@QEAA_JVCPoint@@@Z>
extern __imp_?OnNotify@CCapsLockSensitiveEdit@@MEAAH_K_JPEA_J@Z:PANYARGS
?OnNotify@CCapsLockSensitiveEdit@@MEAAH_K_JPEA_J@Z TEXTEQU <__imp_?OnNotify@CCapsLockSensitiveEdit@@MEAAH_K_JPEA_J@Z>
extern __imp_?OnOK@CDisplayUnlockCodeDlg@@MEAAXXZ:PANYARGS
?OnOK@CDisplayUnlockCodeDlg@@MEAAXXZ TEXTEQU <__imp_?OnOK@CDisplayUnlockCodeDlg@@MEAAXXZ>
extern __imp_?OnOK@CInitializePinDlg@@MEAAXXZ:PANYARGS
?OnOK@CInitializePinDlg@@MEAAXXZ TEXTEQU <__imp_?OnOK@CInitializePinDlg@@MEAAXXZ>
extern __imp_?OnOK@CUnlockCardDlg@@MEAAXXZ:PANYARGS
?OnOK@CUnlockCardDlg@@MEAAXXZ TEXTEQU <__imp_?OnOK@CUnlockCardDlg@@MEAAXXZ>
extern __imp_?OnOtpOk@CPopupAlert@@QEAA_J_K_J@Z:PANYARGS
?OnOtpOk@CPopupAlert@@QEAA_J_K_J@Z TEXTEQU <__imp_?OnOtpOk@CPopupAlert@@QEAA_J_K_J@Z>
extern __imp_?OnPopupAlertClicked@CPopupAlert@@QEAA_J_K_J@Z:PANYARGS
?OnPopupAlertClicked@CPopupAlert@@QEAA_J_K_J@Z TEXTEQU <__imp_?OnPopupAlertClicked@CPopupAlert@@QEAA_J_K_J@Z>
extern __imp_?OnPopupAlertHelpClicked@CPopupAlert@@QEAA_J_K_J@Z:PANYARGS
?OnPopupAlertHelpClicked@CPopupAlert@@QEAA_J_K_J@Z TEXTEQU <__imp_?OnPopupAlertHelpClicked@CPopupAlert@@QEAA_J_K_J@Z>
extern __imp_?OnRadioClicked@CResetCardDialog@@IEAAXXZ:PANYARGS
?OnRadioClicked@CResetCardDialog@@IEAAXXZ TEXTEQU <__imp_?OnRadioClicked@CResetCardDialog@@IEAAXXZ>
extern __imp_?OnSetFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z:PANYARGS
?OnSetFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z TEXTEQU <__imp_?OnSetFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z>
extern __imp_?OnSysColorChange@CBaseDialog@@QEAAXXZ:PANYARGS
?OnSysColorChange@CBaseDialog@@QEAAXXZ TEXTEQU <__imp_?OnSysColorChange@CBaseDialog@@QEAAXXZ>
extern __imp_?OnTimer@CPopupAlert@@QEAAX_K@Z:PANYARGS
?OnTimer@CPopupAlert@@QEAAX_K@Z TEXTEQU <__imp_?OnTimer@CPopupAlert@@QEAAX_K@Z>
extern __imp_?PrepareBackgroundBitmap@CPopupAlert@@AEAAHI_N0@Z:PANYARGS
?PrepareBackgroundBitmap@CPopupAlert@@AEAAHI_N0@Z TEXTEQU <__imp_?PrepareBackgroundBitmap@CPopupAlert@@AEAAHI_N0@Z>
extern __imp_?PutPoliciesInBox@ACPoliciesDlg@@AEAAXXZ:PANYARGS
?PutPoliciesInBox@ACPoliciesDlg@@AEAAXXZ TEXTEQU <__imp_?PutPoliciesInBox@ACPoliciesDlg@@AEAAXXZ>
extern __imp_?ResetToolTip@CCapsLockSensitiveEdit@@QEAAXXZ:PANYARGS
?ResetToolTip@CCapsLockSensitiveEdit@@QEAAXXZ TEXTEQU <__imp_?ResetToolTip@CCapsLockSensitiveEdit@@QEAAXXZ>
extern __imp_?ResetToolTip@CChangePINDialog@@QEAAXXZ:PANYARGS
?ResetToolTip@CChangePINDialog@@QEAAXXZ TEXTEQU <__imp_?ResetToolTip@CChangePINDialog@@QEAAXXZ>
extern __imp_?ResetToolTip@CInitializePinDlg@@QEAAXXZ:PANYARGS
?ResetToolTip@CInitializePinDlg@@QEAAXXZ TEXTEQU <__imp_?ResetToolTip@CInitializePinDlg@@QEAAXXZ>
extern __imp_?ResetToolTip@CResetCardDialog@@QEAAXXZ:PANYARGS
?ResetToolTip@CResetCardDialog@@QEAAXXZ TEXTEQU <__imp_?ResetToolTip@CResetCardDialog@@QEAAXXZ>
extern __imp_?ResizeDlg@CBaseDialog@@QEAAXHHH@Z:PANYARGS
?ResizeDlg@CBaseDialog@@QEAAXHHH@Z TEXTEQU <__imp_?ResizeDlg@CBaseDialog@@QEAAXHHH@Z>
extern __imp_?ResizeDlg@CResetCardDialogMain@@AEAAXHH@Z:PANYARGS
?ResizeDlg@CResetCardDialogMain@@AEAAXHH@Z TEXTEQU <__imp_?ResizeDlg@CResetCardDialogMain@@AEAAXHH@Z>
extern __imp_?SetAlphaPIN@ACPoliciesDlg@@AEAAX_N0@Z:PANYARGS
?SetAlphaPIN@ACPoliciesDlg@@AEAAX_N0@Z TEXTEQU <__imp_?SetAlphaPIN@ACPoliciesDlg@@AEAAX_N0@Z>
extern __imp_?SetAnimStatusToWaiting@CPopupAlert@@AEAAXXZ:PANYARGS
?SetAnimStatusToWaiting@CPopupAlert@@AEAAXXZ TEXTEQU <__imp_?SetAnimStatusToWaiting@CPopupAlert@@AEAAXXZ>
extern __imp_?SetChallenge@CResetCardDialog@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PANYARGS
?SetChallenge@CResetCardDialog@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z TEXTEQU <__imp_?SetChallenge@CResetCardDialog@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>
extern __imp_?SetConfirmPIN@ACPoliciesDlg@@AEAAX_N@Z:PANYARGS
?SetConfirmPIN@ACPoliciesDlg@@AEAAX_N@Z TEXTEQU <__imp_?SetConfirmPIN@ACPoliciesDlg@@AEAAX_N@Z>
extern __imp_?SetMaxPINLen@ACPoliciesDlg@@AEAAXH_N0@Z:PANYARGS
?SetMaxPINLen@ACPoliciesDlg@@AEAAXH_N0@Z TEXTEQU <__imp_?SetMaxPINLen@ACPoliciesDlg@@AEAAXH_N0@Z>
extern __imp_?SetMessage@CPopupAlert@@QEAAXPEBD@Z:PANYARGS
?SetMessage@CPopupAlert@@QEAAXPEBD@Z TEXTEQU <__imp_?SetMessage@CPopupAlert@@QEAAXPEBD@Z>
extern __imp_?SetMinPINLen@ACPoliciesDlg@@AEAAXH_N0@Z:PANYARGS
?SetMinPINLen@ACPoliciesDlg@@AEAAXH_N0@Z TEXTEQU <__imp_?SetMinPINLen@ACPoliciesDlg@@AEAAXH_N0@Z>
extern __imp_?SetMode@CCapsLockSensitiveEdit@@QEAAX_N@Z:PANYARGS
?SetMode@CCapsLockSensitiveEdit@@QEAAX_N@Z TEXTEQU <__imp_?SetMode@CCapsLockSensitiveEdit@@QEAAX_N@Z>
extern __imp_?SetMustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAXH_J@Z:PANYARGS
?SetMustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAXH_J@Z TEXTEQU <__imp_?SetMustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAXH_J@Z>
extern __imp_?SetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAXH@Z:PANYARGS
?SetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAXH@Z TEXTEQU <__imp_?SetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAXH@Z>
extern __imp_SetPinPromptString:PANYARGS
SetPinPromptString TEXTEQU <__imp_SetPinPromptString>
extern __imp_?SetPolicyIcon@ACPoliciesDlg@@AEAAXPEAVCWnd@@PEAUHICON__@@@Z:PANYARGS
?SetPolicyIcon@ACPoliciesDlg@@AEAAXPEAVCWnd@@PEAUHICON__@@@Z TEXTEQU <__imp_?SetPolicyIcon@ACPoliciesDlg@@AEAAXPEAVCWnd@@PEAUHICON__@@@Z>
extern __imp_?SetPreventSamePIN@ACPoliciesDlg@@AEAAX_N0@Z:PANYARGS
?SetPreventSamePIN@ACPoliciesDlg@@AEAAX_N0@Z TEXTEQU <__imp_?SetPreventSamePIN@ACPoliciesDlg@@AEAAX_N0@Z>
extern __imp_?SetReader@CPopupAlert@@QEAAXPEBD@Z:PANYARGS
?SetReader@CPopupAlert@@QEAAXPEBD@Z TEXTEQU <__imp_?SetReader@CPopupAlert@@QEAAXPEBD@Z>
extern __imp_?SetSkin@CPopupAlert@@QEAAHI_N0FFF@Z:PANYARGS
?SetSkin@CPopupAlert@@QEAAHI_N0FFF@Z TEXTEQU <__imp_?SetSkin@CPopupAlert@@QEAAHI_N0FFF@Z>
extern __imp_?SetSkin@CPopupAlert@@QEAAHPEBDFFF@Z:PANYARGS
?SetSkin@CPopupAlert@@QEAAHPEBDFFF@Z TEXTEQU <__imp_?SetSkin@CPopupAlert@@QEAAHPEBDFFF@Z>
extern __imp_?SetTextColor@CPopupAlert@@QEAAXKK@Z:PANYARGS
?SetTextColor@CPopupAlert@@QEAAXKK@Z TEXTEQU <__imp_?SetTextColor@CPopupAlert@@QEAAXKK@Z>
extern __imp_?SetTextFont@CPopupAlert@@QEAAXPEBDHHH@Z:PANYARGS
?SetTextFont@CPopupAlert@@QEAAXPEBDHHH@Z TEXTEQU <__imp_?SetTextFont@CPopupAlert@@QEAAXPEBDHHH@Z>
extern __imp_?SetTextRect@CPopupAlert@@QEAAXUtagRECT@@@Z:PANYARGS
?SetTextRect@CPopupAlert@@QEAAXUtagRECT@@@Z TEXTEQU <__imp_?SetTextRect@CPopupAlert@@QEAAXUtagRECT@@@Z>
extern __imp_?SetThreadRoutine@CPopupAlert@@QEAAXP6AKPEAX@Z@Z:PANYARGS
?SetThreadRoutine@CPopupAlert@@QEAAXP6AKPEAX@Z@Z TEXTEQU <__imp_?SetThreadRoutine@CPopupAlert@@QEAAXP6AKPEAX@Z@Z>
extern __imp_?SetWeakPIN@ACPoliciesDlg@@AEAAX_N0@Z:PANYARGS
?SetWeakPIN@ACPoliciesDlg@@AEAAX_N0@Z TEXTEQU <__imp_?SetWeakPIN@ACPoliciesDlg@@AEAAX_N0@Z>
extern __imp_?Show@CPopupAlert@@QEAAXXZ:PANYARGS
?Show@CPopupAlert@@QEAAXXZ TEXTEQU <__imp_?Show@CPopupAlert@@QEAAXXZ>
extern __imp_ShowAbout:PANYARGS
ShowAbout TEXTEQU <__imp_ShowAbout>
extern __imp_?StopDetectingRemoveEvent@CResetCardDialogMain@@IEAAXXZ:PANYARGS
?StopDetectingRemoveEvent@CResetCardDialogMain@@IEAAXXZ TEXTEQU <__imp_?StopDetectingRemoveEvent@CResetCardDialogMain@@IEAAXXZ>
extern __imp_?VerifyAndUpdateAllPolicies@CChangePINDialog@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PANYARGS
?VerifyAndUpdateAllPolicies@CChangePINDialog@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z TEXTEQU <__imp_?VerifyAndUpdateAllPolicies@CChangePINDialog@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>
extern __imp_?VerifyAndUpdatePolicies@ACPoliciesDlg@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@000@Z:PANYARGS
?VerifyAndUpdatePolicies@ACPoliciesDlg@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@000@Z TEXTEQU <__imp_?VerifyAndUpdatePolicies@ACPoliciesDlg@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@000@Z>
extern __imp_?_GetBaseClass@ACPoliciesDlg@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@ACPoliciesDlg@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@ACPoliciesDlg@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CBaseDialog@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CBaseDialog@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CBaseDialog@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CCMLockedDlg@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CCMLockedDlg@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CCMLockedDlg@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CCapsLockSensitiveEdit@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CCapsLockSensitiveEdit@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CCapsLockSensitiveEdit@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CChangePINDialog@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CChangePINDialog@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CChangePINDialog@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CDisplayUCChild@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CDisplayUCChild@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CDisplayUCChild@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CDisplayUnlockCodeDlg@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CDisplayUnlockCodeDlg@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CDisplayUnlockCodeDlg@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CPopupAlert@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CPopupAlert@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CPopupAlert@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CResetCardDialog@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CResetCardDialog@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CResetCardDialog@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CResetCardDialogMain@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CResetCardDialogMain@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CResetCardDialogMain@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?_GetBaseClass@CUnlockInitToolDlg@@KAPEAUCRuntimeClass@@XZ:PANYARGS
?_GetBaseClass@CUnlockInitToolDlg@@KAPEAUCRuntimeClass@@XZ TEXTEQU <__imp_?_GetBaseClass@CUnlockInitToolDlg@@KAPEAUCRuntimeClass@@XZ>
extern __imp_?classACPoliciesDlg@ACPoliciesDlg@@2UCRuntimeClass@@B:PANYARGS
?classACPoliciesDlg@ACPoliciesDlg@@2UCRuntimeClass@@B TEXTEQU <__imp_?classACPoliciesDlg@ACPoliciesDlg@@2UCRuntimeClass@@B>
extern __imp_?classCBaseDialog@CBaseDialog@@2UCRuntimeClass@@B:PANYARGS
?classCBaseDialog@CBaseDialog@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCBaseDialog@CBaseDialog@@2UCRuntimeClass@@B>
extern __imp_?classCCMLockedDlg@CCMLockedDlg@@2UCRuntimeClass@@B:PANYARGS
?classCCMLockedDlg@CCMLockedDlg@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCCMLockedDlg@CCMLockedDlg@@2UCRuntimeClass@@B>
extern __imp_?classCCapsLockSensitiveEdit@CCapsLockSensitiveEdit@@2UCRuntimeClass@@B:PANYARGS
?classCCapsLockSensitiveEdit@CCapsLockSensitiveEdit@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCCapsLockSensitiveEdit@CCapsLockSensitiveEdit@@2UCRuntimeClass@@B>
extern __imp_?classCChangePINDialog@CChangePINDialog@@2UCRuntimeClass@@B:PANYARGS
?classCChangePINDialog@CChangePINDialog@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCChangePINDialog@CChangePINDialog@@2UCRuntimeClass@@B>
extern __imp_?classCDisplayUCChild@CDisplayUCChild@@2UCRuntimeClass@@B:PANYARGS
?classCDisplayUCChild@CDisplayUCChild@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCDisplayUCChild@CDisplayUCChild@@2UCRuntimeClass@@B>
extern __imp_?classCDisplayUnlockCodeDlg@CDisplayUnlockCodeDlg@@2UCRuntimeClass@@B:PANYARGS
?classCDisplayUnlockCodeDlg@CDisplayUnlockCodeDlg@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCDisplayUnlockCodeDlg@CDisplayUnlockCodeDlg@@2UCRuntimeClass@@B>
extern __imp_?classCPopupAlert@CPopupAlert@@2UCRuntimeClass@@B:PANYARGS
?classCPopupAlert@CPopupAlert@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCPopupAlert@CPopupAlert@@2UCRuntimeClass@@B>
extern __imp_?classCResetCardDialog@CResetCardDialog@@2UCRuntimeClass@@B:PANYARGS
?classCResetCardDialog@CResetCardDialog@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCResetCardDialog@CResetCardDialog@@2UCRuntimeClass@@B>
extern __imp_?classCResetCardDialogMain@CResetCardDialogMain@@2UCRuntimeClass@@B:PANYARGS
?classCResetCardDialogMain@CResetCardDialogMain@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCResetCardDialogMain@CResetCardDialogMain@@2UCRuntimeClass@@B>
extern __imp_?classCUnlockInitToolDlg@CUnlockInitToolDlg@@2UCRuntimeClass@@B:PANYARGS
?classCUnlockInitToolDlg@CUnlockInitToolDlg@@2UCRuntimeClass@@B TEXTEQU <__imp_?classCUnlockInitToolDlg@CUnlockInitToolDlg@@2UCRuntimeClass@@B>
