extern __imp_UPSCancelWait:PANYARGS
UPSCancelWait TEXTEQU <__imp_UPSCancelWait>
extern __imp_UPSGetState:PANYARGS
UPSGetState TEXTEQU <__imp_UPSGetState>
extern __imp_UPSInit:PANYARGS
UPSInit TEXTEQU <__imp_UPSInit>
extern __imp_UPSStop:PANYARGS
UPSStop TEXTEQU <__imp_UPSStop>
extern __imp_UPSTurnOff:PANYARGS
UPSTurnOff TEXTEQU <__imp_UPSTurnOff>
extern __imp_UPSWaitForStateChange:PANYARGS
UPSWaitForStateChange TEXTEQU <__imp_UPSWaitForStateChange>
