extern __imp_CsSetOptions:PANYARGS
CsSetOptions TEXTEQU <__imp_CsSetOptions>
extern __imp_CsCreateClassStore:PANYARGS
CsCreateClassStore TEXTEQU <__imp_CsCreateClassStore>
extern __imp_CsEnumApps:PANYARGS
CsEnumApps TEXTEQU <__imp_CsEnumApps>
extern __imp_CsGetAppCategories:PANYARGS
CsGetAppCategories TEXTEQU <__imp_CsGetAppCategories>
extern __imp_CsGetClassAccess:PANYARGS
CsGetClassAccess TEXTEQU <__imp_CsGetClassAccess>
extern __imp_CsGetClassStore:PANYARGS
CsGetClassStore TEXTEQU <__imp_CsGetClassStore>
extern __imp_CsGetClassStorePath:PANYARGS
CsGetClassStorePath TEXTEQU <__imp_CsGetClassStorePath>
extern __imp_CsRegisterAppCategory:PANYARGS
CsRegisterAppCategory TEXTEQU <__imp_CsRegisterAppCategory>
extern __imp_CsServerGetClassStore:PANYARGS
CsServerGetClassStore TEXTEQU <__imp_CsServerGetClassStore>
extern __imp_CsUnregisterAppCategory:PANYARGS
CsUnregisterAppCategory TEXTEQU <__imp_CsUnregisterAppCategory>
extern __imp_GenerateGroupPolicy:PANYARGS
GenerateGroupPolicy TEXTEQU <__imp_GenerateGroupPolicy>
extern __imp_IID_IClassAdmin:PANYARGS
IID_IClassAdmin TEXTEQU <__imp_IID_IClassAdmin>
extern __imp_ProcessGroupPolicyObjectsEx:PANYARGS
ProcessGroupPolicyObjectsEx TEXTEQU <__imp_ProcessGroupPolicyObjectsEx>
extern __imp_ReleaseAppCategoryInfoList:PANYARGS
ReleaseAppCategoryInfoList TEXTEQU <__imp_ReleaseAppCategoryInfoList>
extern __imp_ReleasePackageDetail:PANYARGS
ReleasePackageDetail TEXTEQU <__imp_ReleasePackageDetail>
extern __imp_ReleasePackageInfo:PANYARGS
ReleasePackageInfo TEXTEQU <__imp_ReleasePackageInfo>
extern __imp_ServiceMain:PANYARGS
ServiceMain TEXTEQU <__imp_ServiceMain>
