extern __imp_ASPHAddCardInRegistry:PANYARGS
ASPHAddCardInRegistry TEXTEQU <__imp_ASPHAddCardInRegistry>
extern __imp_ASPHAuthCheckCode:PANYARGS
ASPHAuthCheckCode TEXTEQU <__imp_ASPHAuthCheckCode>
extern __imp_ASPHAuthenticate:PANYARGS
ASPHAuthenticate TEXTEQU <__imp_ASPHAuthenticate>
extern __imp_ASPHAuthenticateEx:PANYARGS
ASPHAuthenticateEx TEXTEQU <__imp_ASPHAuthenticateEx>
extern __imp_ASPHBeginTransaction:PANYARGS
ASPHBeginTransaction TEXTEQU <__imp_ASPHBeginTransaction>
extern __imp_ASPHCacheEnd:PANYARGS
ASPHCacheEnd TEXTEQU <__imp_ASPHCacheEnd>
extern __imp_ASPHCancelMonitor:PANYARGS
ASPHCancelMonitor TEXTEQU <__imp_ASPHCancelMonitor>
extern __imp_ASPHCardLogout:PANYARGS
ASPHCardLogout TEXTEQU <__imp_ASPHCardLogout>
extern __imp_ASPHChangeUnlockCode:PANYARGS
ASPHChangeUnlockCode TEXTEQU <__imp_ASPHChangeUnlockCode>
extern __imp_ASPHCheckCard:PANYARGS
ASPHCheckCard TEXTEQU <__imp_ASPHCheckCard>
extern __imp_ASPHCheckDataPresence:PANYARGS
ASPHCheckDataPresence TEXTEQU <__imp_ASPHCheckDataPresence>
extern __imp_ASPHCleanPIVRegistry:PANYARGS
ASPHCleanPIVRegistry TEXTEQU <__imp_ASPHCleanPIVRegistry>
extern __imp_ASPHClearCache:PANYARGS
ASPHClearCache TEXTEQU <__imp_ASPHClearCache>
extern __imp_ASPHClearCard:PANYARGS
ASPHClearCard TEXTEQU <__imp_ASPHClearCard>
extern __imp_ASPHComputeCryptogram:PANYARGS
ASPHComputeCryptogram TEXTEQU <__imp_ASPHComputeCryptogram>
extern __imp_ASPHConnect:PANYARGS
ASPHConnect TEXTEQU <__imp_ASPHConnect>
extern __imp_ASPHConnectEx:PANYARGS
ASPHConnectEx TEXTEQU <__imp_ASPHConnectEx>
extern __imp_ASPHCredentialAttrRead:PANYARGS
ASPHCredentialAttrRead TEXTEQU <__imp_ASPHCredentialAttrRead>
extern __imp_ASPHCredentialAttrUpdate:PANYARGS
ASPHCredentialAttrUpdate TEXTEQU <__imp_ASPHCredentialAttrUpdate>
extern __imp_ASPHDataCreate:PANYARGS
ASPHDataCreate TEXTEQU <__imp_ASPHDataCreate>
extern __imp_ASPHDataDelete:PANYARGS
ASPHDataDelete TEXTEQU <__imp_ASPHDataDelete>
extern __imp_ASPHDeleteCredential:PANYARGS
ASPHDeleteCredential TEXTEQU <__imp_ASPHDeleteCredential>
extern __imp_ASPHDisconnect:PANYARGS
ASPHDisconnect TEXTEQU <__imp_ASPHDisconnect>
extern __imp_ASPHDisconnectOnExit:PANYARGS
ASPHDisconnectOnExit TEXTEQU <__imp_ASPHDisconnectOnExit>
extern __imp_ASPHEndMonitor:PANYARGS
ASPHEndMonitor TEXTEQU <__imp_ASPHEndMonitor>
extern __imp_ASPHEndTransaction:PANYARGS
ASPHEndTransaction TEXTEQU <__imp_ASPHEndTransaction>
extern __imp_ASPHExternalAuth:PANYARGS
ASPHExternalAuth TEXTEQU <__imp_ASPHExternalAuth>
extern __imp_ASPHGeneralAuthenticate:PANYARGS
ASPHGeneralAuthenticate TEXTEQU <__imp_ASPHGeneralAuthenticate>
extern __imp_ASPHGenerateKey:PANYARGS
ASPHGenerateKey TEXTEQU <__imp_ASPHGenerateKey>
extern __imp_ASPHGetATR:PANYARGS
ASPHGetATR TEXTEQU <__imp_ASPHGetATR>
extern __imp_ASPHGetAspcomHandle:PANYARGS
ASPHGetAspcomHandle TEXTEQU <__imp_ASPHGetAspcomHandle>
extern __imp_ASPHGetAuthCode:PANYARGS
ASPHGetAuthCode TEXTEQU <__imp_ASPHGetAuthCode>
extern __imp_ASPHGetCCCContainer:PANYARGS
ASPHGetCCCContainer TEXTEQU <__imp_ASPHGetCCCContainer>
extern __imp_ASPHGetCardInfo:PANYARGS
ASPHGetCardInfo TEXTEQU <__imp_ASPHGetCardInfo>
extern __imp_ASPHGetCardManagerState:PANYARGS
ASPHGetCardManagerState TEXTEQU <__imp_ASPHGetCardManagerState>
extern __imp_ASPHGetCardManufacturerAndModel:PANYARGS
ASPHGetCardManufacturerAndModel TEXTEQU <__imp_ASPHGetCardManufacturerAndModel>
extern __imp_ASPHGetCardProfileUID:PANYARGS
ASPHGetCardProfileUID TEXTEQU <__imp_ASPHGetCardProfileUID>
extern __imp_ASPHGetCardProperties:PANYARGS
ASPHGetCardProperties TEXTEQU <__imp_ASPHGetCardProperties>
extern __imp_ASPHGetCardStatus:PANYARGS
ASPHGetCardStatus TEXTEQU <__imp_ASPHGetCardStatus>
extern __imp_ASPHGetCardStructure:PANYARGS
ASPHGetCardStructure TEXTEQU <__imp_ASPHGetCardStructure>
extern __imp_ASPHGetCardUIDData:PANYARGS
ASPHGetCardUIDData TEXTEQU <__imp_ASPHGetCardUIDData>
extern __imp_ASPHGetChallenge:PANYARGS
ASPHGetChallenge TEXTEQU <__imp_ASPHGetChallenge>
extern __imp_ASPHGetClock:PANYARGS
ASPHGetClock TEXTEQU <__imp_ASPHGetClock>
extern __imp_ASPHGetContainerCertificate:PANYARGS
ASPHGetContainerCertificate TEXTEQU <__imp_ASPHGetContainerCertificate>
extern __imp_ASPHGetContainerList:PANYARGS
ASPHGetContainerList TEXTEQU <__imp_ASPHGetContainerList>
extern __imp_ASPHGetContainerProperties:PANYARGS
ASPHGetContainerProperties TEXTEQU <__imp_ASPHGetContainerProperties>
extern __imp_ASPHGetContainerPropertiesEx:PANYARGS
ASPHGetContainerPropertiesEx TEXTEQU <__imp_ASPHGetContainerPropertiesEx>
extern __imp_ASPHGetContainerPropertiesEx2:PANYARGS
ASPHGetContainerPropertiesEx2 TEXTEQU <__imp_ASPHGetContainerPropertiesEx2>
extern __imp_ASPHGetCredentialProperties:PANYARGS
ASPHGetCredentialProperties TEXTEQU <__imp_ASPHGetCredentialProperties>
extern __imp_ASPHGetCurrentContainer:PANYARGS
ASPHGetCurrentContainer TEXTEQU <__imp_ASPHGetCurrentContainer>
extern __imp_ASPHGetDataModel:PANYARGS
ASPHGetDataModel TEXTEQU <__imp_ASPHGetDataModel>
extern __imp_ASPHGetDataModelId:PANYARGS
ASPHGetDataModelId TEXTEQU <__imp_ASPHGetDataModelId>
extern __imp_ASPHGetDefaultCertCredential:PANYARGS
ASPHGetDefaultCertCredential TEXTEQU <__imp_ASPHGetDefaultCertCredential>
extern __imp_ASPHGetDemographicAppletList:PANYARGS
ASPHGetDemographicAppletList TEXTEQU <__imp_ASPHGetDemographicAppletList>
extern __imp_ASPHGetDisableDefaultCertificate:PANYARGS
ASPHGetDisableDefaultCertificate TEXTEQU <__imp_ASPHGetDisableDefaultCertificate>
extern __imp_ASPHGetFileContent:PANYARGS
ASPHGetFileContent TEXTEQU <__imp_ASPHGetFileContent>
extern __imp_ASPHGetFileList:PANYARGS
ASPHGetFileList TEXTEQU <__imp_ASPHGetFileList>
extern __imp_ASPHGetFileProperties:PANYARGS
ASPHGetFileProperties TEXTEQU <__imp_ASPHGetFileProperties>
extern __imp_ASPHGetKeyConfiguration:PANYARGS
ASPHGetKeyConfiguration TEXTEQU <__imp_ASPHGetKeyConfiguration>
extern __imp_ASPHGetKeyGenerationConf:PANYARGS
ASPHGetKeyGenerationConf TEXTEQU <__imp_ASPHGetKeyGenerationConf>
extern __imp_ASPHGetMonitorReadersCount:PANYARGS
ASPHGetMonitorReadersCount TEXTEQU <__imp_ASPHGetMonitorReadersCount>
extern __imp_ASPHGetPINPolicies:PANYARGS
ASPHGetPINPolicies TEXTEQU <__imp_ASPHGetPINPolicies>
extern __imp_ASPHGetPinContainerProperties:PANYARGS
ASPHGetPinContainerProperties TEXTEQU <__imp_ASPHGetPinContainerProperties>
extern __imp_ASPHGetReaderByHandle:PANYARGS
ASPHGetReaderByHandle TEXTEQU <__imp_ASPHGetReaderByHandle>
extern __imp_ASPHGetReaderProperties:PANYARGS
ASPHGetReaderProperties TEXTEQU <__imp_ASPHGetReaderProperties>
extern __imp_ASPHGetReadersCount:PANYARGS
ASPHGetReadersCount TEXTEQU <__imp_ASPHGetReadersCount>
extern __imp_ASPHGetReadersList:PANYARGS
ASPHGetReadersList TEXTEQU <__imp_ASPHGetReadersList>
extern __imp_ASPHGetStaticBuffer:PANYARGS
ASPHGetStaticBuffer TEXTEQU <__imp_ASPHGetStaticBuffer>
extern __imp_ASPHGetTagFromAID:PANYARGS
ASPHGetTagFromAID TEXTEQU <__imp_ASPHGetTagFromAID>
extern __imp_ASPHGetUniqueIdentifier:PANYARGS
ASPHGetUniqueIdentifier TEXTEQU <__imp_ASPHGetUniqueIdentifier>
extern __imp_ASPHGetVersion:PANYARGS
ASPHGetVersion TEXTEQU <__imp_ASPHGetVersion>
extern __imp_ASPHInitCredential:PANYARGS
ASPHInitCredential TEXTEQU <__imp_ASPHInitCredential>
extern __imp_ASPHInitMonitor:PANYARGS
ASPHInitMonitor TEXTEQU <__imp_ASPHInitMonitor>
extern __imp_ASPHIsCACCard:PANYARGS
ASPHIsCACCard TEXTEQU <__imp_ASPHIsCACCard>
extern __imp_ASPHIsCardContentModified:PANYARGS
ASPHIsCardContentModified TEXTEQU <__imp_ASPHIsCardContentModified>
extern __imp_ASPHIsClearCardAllowed:PANYARGS
ASPHIsClearCardAllowed TEXTEQU <__imp_ASPHIsClearCardAllowed>
extern __imp_ASPHIsPIVCard:PANYARGS
ASPHIsPIVCard TEXTEQU <__imp_ASPHIsPIVCard>
extern __imp_ASPHIsPIVExtCard:PANYARGS
ASPHIsPIVExtCard TEXTEQU <__imp_ASPHIsPIVExtCard>
extern __imp_ASPHIsStandaloneCard:PANYARGS
ASPHIsStandaloneCard TEXTEQU <__imp_ASPHIsStandaloneCard>
extern __imp_ASPHIsUnlockCardAllowed:PANYARGS
ASPHIsUnlockCardAllowed TEXTEQU <__imp_ASPHIsUnlockCardAllowed>
extern __imp_ASPHListCredentials:PANYARGS
ASPHListCredentials TEXTEQU <__imp_ASPHListCredentials>
extern __imp_ASPHLocalAuthenticate:PANYARGS
ASPHLocalAuthenticate TEXTEQU <__imp_ASPHLocalAuthenticate>
extern __imp_ASPHLocalLogout:PANYARGS
ASPHLocalLogout TEXTEQU <__imp_ASPHLocalLogout>
extern __imp_ASPHLogin:PANYARGS
ASPHLogin TEXTEQU <__imp_ASPHLogin>
extern __imp_ASPHLogout:PANYARGS
ASPHLogout TEXTEQU <__imp_ASPHLogout>
extern __imp_ASPHLogoutByContext:PANYARGS
ASPHLogoutByContext TEXTEQU <__imp_ASPHLogoutByContext>
extern __imp_ASPHMonitor:PANYARGS
ASPHMonitor TEXTEQU <__imp_ASPHMonitor>
extern __imp_ASPHMonitorReaders:PANYARGS
ASPHMonitorReaders TEXTEQU <__imp_ASPHMonitorReaders>
extern __imp_ASPHNotifyEvent:PANYARGS
ASPHNotifyEvent TEXTEQU <__imp_ASPHNotifyEvent>
extern __imp_ASPHPIVGenerateKey:PANYARGS
ASPHPIVGenerateKey TEXTEQU <__imp_ASPHPIVGenerateKey>
extern __imp_ASPHPassThru:PANYARGS
ASPHPassThru TEXTEQU <__imp_ASPHPassThru>
extern __imp_ASPHPinInit:PANYARGS
ASPHPinInit TEXTEQU <__imp_ASPHPinInit>
extern __imp_ASPHPinSet:PANYARGS
ASPHPinSet TEXTEQU <__imp_ASPHPinSet>
extern __imp_ASPHPinUnlock:PANYARGS
ASPHPinUnlock TEXTEQU <__imp_ASPHPinUnlock>
extern __imp_ASPHPinVerifiedCheck:PANYARGS
ASPHPinVerifiedCheck TEXTEQU <__imp_ASPHPinVerifiedCheck>
extern __imp_ASPHPinVerifiedCheckByContext:PANYARGS
ASPHPinVerifiedCheckByContext TEXTEQU <__imp_ASPHPinVerifiedCheckByContext>
extern __imp_ASPHPivGetData:PANYARGS
ASPHPivGetData TEXTEQU <__imp_ASPHPivGetData>
extern __imp_ASPHPivPutData:PANYARGS
ASPHPivPutData TEXTEQU <__imp_ASPHPivPutData>
extern __imp_ASPHRSAPrivateDecrypt:PANYARGS
ASPHRSAPrivateDecrypt TEXTEQU <__imp_ASPHRSAPrivateDecrypt>
extern __imp_ASPHRSAPrivateSign:PANYARGS
ASPHRSAPrivateSign TEXTEQU <__imp_ASPHRSAPrivateSign>
extern __imp_ASPHRSARawPrivateSign:PANYARGS
ASPHRSARawPrivateSign TEXTEQU <__imp_ASPHRSARawPrivateSign>
extern __imp_ASPHReadTagList:PANYARGS
ASPHReadTagList TEXTEQU <__imp_ASPHReadTagList>
extern __imp_ASPHReadValue:PANYARGS
ASPHReadValue TEXTEQU <__imp_ASPHReadValue>
extern __imp_ASPHRefreshCardEdge:PANYARGS
ASPHRefreshCardEdge TEXTEQU <__imp_ASPHRefreshCardEdge>
extern __imp_ASPHSelectCardApplication:PANYARGS
ASPHSelectCardApplication TEXTEQU <__imp_ASPHSelectCardApplication>
extern __imp_ASPHSelectContainer:PANYARGS
ASPHSelectContainer TEXTEQU <__imp_ASPHSelectContainer>
extern __imp_ASPHSelectContainerByService:PANYARGS
ASPHSelectContainerByService TEXTEQU <__imp_ASPHSelectContainerByService>
extern __imp_ASPHSelectContainerEx:PANYARGS
ASPHSelectContainerEx TEXTEQU <__imp_ASPHSelectContainerEx>
extern __imp_ASPHSetDisableDefaultCertificate:PANYARGS
ASPHSetDisableDefaultCertificate TEXTEQU <__imp_ASPHSetDisableDefaultCertificate>
extern __imp_ASPHSetPinPromptString:PANYARGS
ASPHSetPinPromptString TEXTEQU <__imp_ASPHSetPinPromptString>
extern __imp_ASPHSetSilentMode:PANYARGS
ASPHSetSilentMode TEXTEQU <__imp_ASPHSetSilentMode>
extern __imp_ASPHSetStaticBuffer:PANYARGS
ASPHSetStaticBuffer TEXTEQU <__imp_ASPHSetStaticBuffer>
extern __imp_ASPHSetUIPrompt:PANYARGS
ASPHSetUIPrompt TEXTEQU <__imp_ASPHSetUIPrompt>
extern __imp_ASPHShowAuthentication:PANYARGS
ASPHShowAuthentication TEXTEQU <__imp_ASPHShowAuthentication>
extern __imp_ASPHStaticUnlock:PANYARGS
ASPHStaticUnlock TEXTEQU <__imp_ASPHStaticUnlock>
extern __imp_ASPHUnlockGetChallenge:PANYARGS
ASPHUnlockGetChallenge TEXTEQU <__imp_ASPHUnlockGetChallenge>
extern __imp_ASPHUpdateValue:PANYARGS
ASPHUpdateValue TEXTEQU <__imp_ASPHUpdateValue>
extern __imp_ASPHWaitCardStatus:PANYARGS
ASPHWaitCardStatus TEXTEQU <__imp_ASPHWaitCardStatus>
extern __imp_ASPHakdGetCounter:PANYARGS
ASPHakdGetCounter TEXTEQU <__imp_ASPHakdGetCounter>
extern __imp_ASPHakdGetDeviceStatus:PANYARGS
ASPHakdGetDeviceStatus TEXTEQU <__imp_ASPHakdGetDeviceStatus>
extern __imp_ASPHakdGetLeftPINTries:PANYARGS
ASPHakdGetLeftPINTries TEXTEQU <__imp_ASPHakdGetLeftPINTries>
extern __imp_ASPHakdIsSIMPresent:PANYARGS
ASPHakdIsSIMPresent TEXTEQU <__imp_ASPHakdIsSIMPresent>
