extern __imp_AtiDisConnectEvent:PANYARGS
AtiDisConnectEvent TEXTEQU <__imp_AtiDisConnectEvent>
extern __imp_AtiLockEvent:PANYARGS
AtiLockEvent TEXTEQU <__imp_AtiLockEvent>
extern __imp_AtiLogoffEvent:PANYARGS
AtiLogoffEvent TEXTEQU <__imp_AtiLogoffEvent>
extern __imp_AtiLogonEvent:PANYARGS
AtiLogonEvent TEXTEQU <__imp_AtiLogonEvent>
extern __imp_AtiLowLevelKeyboardProc:PANYARGS
AtiLowLevelKeyboardProc TEXTEQU <__imp_AtiLowLevelKeyboardProc>
extern __imp_AtiReConnectEvent:PANYARGS
AtiReConnectEvent TEXTEQU <__imp_AtiReConnectEvent>
extern __imp_AtiReleaseKeyboardHook:PANYARGS
AtiReleaseKeyboardHook TEXTEQU <__imp_AtiReleaseKeyboardHook>
extern __imp_AtiSetKeyboardHook:PANYARGS
AtiSetKeyboardHook TEXTEQU <__imp_AtiSetKeyboardHook>
extern __imp_AtiShutdownEvent:PANYARGS
AtiShutdownEvent TEXTEQU <__imp_AtiShutdownEvent>
extern __imp_AtiStartScreenSaverEvent:PANYARGS
AtiStartScreenSaverEvent TEXTEQU <__imp_AtiStartScreenSaverEvent>
extern __imp_AtiStartShellEvent:PANYARGS
AtiStartShellEvent TEXTEQU <__imp_AtiStartShellEvent>
extern __imp_AtiStartupEvent:PANYARGS
AtiStartupEvent TEXTEQU <__imp_AtiStartupEvent>
extern __imp_AtiStopScreenSaverEvent:PANYARGS
AtiStopScreenSaverEvent TEXTEQU <__imp_AtiStopScreenSaverEvent>
extern __imp_AtiUnLockEvent:PANYARGS
AtiUnLockEvent TEXTEQU <__imp_AtiUnLockEvent>
extern __imp_ChangeDesktopSetting:PANYARGS
ChangeDesktopSetting TEXTEQU <__imp_ChangeDesktopSetting>
