extern __imp_GsDrvEnableDriver:PANYARGS
GsDrvEnableDriver TEXTEQU <__imp_GsDrvEnableDriver>
extern __imp_VPEAccessCallback:PANYARGS
VPEAccessCallback TEXTEQU <__imp_VPEAccessCallback>
extern __imp_bD3dHslSetDriverCallsEx:PANYARGS
bD3dHslSetDriverCallsEx TEXTEQU <__imp_bD3dHslSetDriverCallsEx>
extern __imp_bDD4DISPDescribeSurface:PANYARGS
bDD4DISPDescribeSurface TEXTEQU <__imp_bDD4DISPDescribeSurface>
extern __imp_bDD4DISPDescribeSurface_WA:PANYARGS
bDD4DISPDescribeSurface_W  TEXTEQU <__imp_bDD4DISPDescribeSurface_WA>
extern __imp_bDD4DISPEnableDD:PANYARGS
bDD4DISPEnableDD TEXTEQU <__imp_bDD4DISPEnableDD>
extern __imp_bDD4DISPInitDD:PANYARGS
bDD4DISPInitDD TEXTEQU <__imp_bDD4DISPInitDD>
extern __imp_bDdHslQueryCIInfo:PANYARGS
bDdHslQueryCIInfo TEXTEQU <__imp_bDdHslQueryCIInfo>
extern __imp_bDdHslQueryRegistryValue:PANYARGS
bDdHslQueryRegistryValue TEXTEQU <__imp_bDdHslQueryRegistryValue>
extern __imp_bDdHslSharedMemFree:PANYARGS
bDdHslSharedMemFree TEXTEQU <__imp_bDdHslSharedMemFree>
extern __imp_bDdHslVideoMemoryFree:PANYARGS
bDdHslVideoMemoryFree TEXTEQU <__imp_bDdHslVideoMemoryFree>
extern __imp_bGDI3DQueryDesktopCompositionSupport:PANYARGS
bGDI3DQueryDesktopCompositionSupport TEXTEQU <__imp_bGDI3DQueryDesktopCompositionSupport>
extern __imp_bGDI3DQueryInfo:PANYARGS
bGDI3DQueryInfo TEXTEQU <__imp_bGDI3DQueryInfo>
extern __imp_dDdHslEscape:PANYARGS
dDdHslEscape TEXTEQU <__imp_dDdHslEscape>
extern __imp_pDD4DISPDeriveSurface:PANYARGS
pDD4DISPDeriveSurface TEXTEQU <__imp_pDD4DISPDeriveSurface>
extern __imp_pDdHslQueryDeviceObject:PANYARGS
pDdHslQueryDeviceObject TEXTEQU <__imp_pDdHslQueryDeviceObject>
extern __imp_pDdHslSharedMemCalloc:PANYARGS
pDdHslSharedMemCalloc TEXTEQU <__imp_pDdHslSharedMemCalloc>
extern __imp_vD3dHslSetDriverCalls:PANYARGS
vD3dHslSetDriverCalls TEXTEQU <__imp_vD3dHslSetDriverCalls>
extern __imp_vDD4DISPDisableDD:PANYARGS
vDD4DISPDisableDD TEXTEQU <__imp_vDD4DISPDisableDD>
extern __imp_vDD4DISPExitDD:PANYARGS
vDD4DISPExitDD TEXTEQU <__imp_vDD4DISPExitDD>
extern __imp_vDD4DISPFlush3D:PANYARGS
vDD4DISPFlush3D TEXTEQU <__imp_vDD4DISPFlush3D>
extern __imp_vDD4DISPHandlePanCallback:PANYARGS
vDD4DISPHandlePanCallback TEXTEQU <__imp_vDD4DISPHandlePanCallback>
extern __imp_vDD4DISPResetDxObj:PANYARGS
vDD4DISPResetDxObj TEXTEQU <__imp_vDD4DISPResetDxObj>
extern __imp_vDD4DISPSetDDCallBacks:PANYARGS
vDD4DISPSetDDCallBacks TEXTEQU <__imp_vDD4DISPSetDDCallBacks>
extern __imp_vDD4DISPSurfaceNotify:PANYARGS
vDD4DISPSurfaceNotify TEXTEQU <__imp_vDD4DISPSurfaceNotify>
extern __imp_vDD4DispGDIPrimaryAccess:PANYARGS
vDD4DispGDIPrimaryAccess TEXTEQU <__imp_vDD4DispGDIPrimaryAccess>
extern __imp_vDVDHSLUpdatePDEV:PANYARGS
vDVDHSLUpdatePDEV TEXTEQU <__imp_vDVDHSLUpdatePDEV>
extern __imp_vDdHslVideoMemoryAlloc:PANYARGS
vDdHslVideoMemoryAlloc TEXTEQU <__imp_vDdHslVideoMemoryAlloc>
extern __imp_vGDI3DAATextOut:PANYARGS
vGDI3DAATextOut TEXTEQU <__imp_vGDI3DAATextOut>
extern __imp_vGDI3DAATextOut_WA:PANYARGS
vGDI3DAATextOut_W  TEXTEQU <__imp_vGDI3DAATextOut_WA>
extern __imp_vGDI3DAlphaBlt:PANYARGS
vGDI3DAlphaBlt TEXTEQU <__imp_vGDI3DAlphaBlt>
extern __imp_vGDI3DAlphaBlt_WA:PANYARGS
vGDI3DAlphaBlt_W  TEXTEQU <__imp_vGDI3DAlphaBlt_WA>
extern __imp_vGDI3DDesktopComposition_WA:PANYARGS
vGDI3DDesktopComposition_W  TEXTEQU <__imp_vGDI3DDesktopComposition_WA>
extern __imp_vGDI3DGradientFill:PANYARGS
vGDI3DGradientFill TEXTEQU <__imp_vGDI3DGradientFill>
extern __imp_vGDI3DGradientFill_WA:PANYARGS
vGDI3DGradientFill_W  TEXTEQU <__imp_vGDI3DGradientFill_WA>
extern __imp_vGDI3DSolidFill:PANYARGS
vGDI3DSolidFill TEXTEQU <__imp_vGDI3DSolidFill>
extern __imp_vGDI3DSolidFill_WA:PANYARGS
vGDI3DSolidFill_W  TEXTEQU <__imp_vGDI3DSolidFill_WA>
extern __imp_vGDI3DStretchBlt:PANYARGS
vGDI3DStretchBlt TEXTEQU <__imp_vGDI3DStretchBlt>
extern __imp_vGDI3DStretchBlt_WA:PANYARGS
vGDI3DStretchBlt_W  TEXTEQU <__imp_vGDI3DStretchBlt_WA>
