extern __imp_calclAssembleObject:PANYARGS
calclAssembleObject TEXTEQU <__imp_calclAssembleObject>
extern __imp_calclCompile:PANYARGS
calclCompile TEXTEQU <__imp_calclCompile>
extern __imp_calclDisassembleImage:PANYARGS
calclDisassembleImage TEXTEQU <__imp_calclDisassembleImage>
extern __imp_calclDisassembleObject:PANYARGS
calclDisassembleObject TEXTEQU <__imp_calclDisassembleObject>
extern __imp_calclExtGetProc:PANYARGS
calclExtGetProc TEXTEQU <__imp_calclExtGetProc>
extern __imp_calclExtSupported:PANYARGS
calclExtSupported TEXTEQU <__imp_calclExtSupported>
extern __imp_calclFreeImage:PANYARGS
calclFreeImage TEXTEQU <__imp_calclFreeImage>
extern __imp_calclFreeObject:PANYARGS
calclFreeObject TEXTEQU <__imp_calclFreeObject>
extern __imp_calclGetErrorString:PANYARGS
calclGetErrorString TEXTEQU <__imp_calclGetErrorString>
extern __imp_calclGetVersion:PANYARGS
calclGetVersion TEXTEQU <__imp_calclGetVersion>
extern __imp_calclImageGetSize:PANYARGS
calclImageGetSize TEXTEQU <__imp_calclImageGetSize>
extern __imp_calclImageWrite:PANYARGS
calclImageWrite TEXTEQU <__imp_calclImageWrite>
extern __imp_calclLink:PANYARGS
calclLink TEXTEQU <__imp_calclLink>
