extern __imp_calCtxCreate:PANYARGS
calCtxCreate TEXTEQU <__imp_calCtxCreate>
extern __imp_calCtxDestroy:PANYARGS
calCtxDestroy TEXTEQU <__imp_calCtxDestroy>
extern __imp_calCtxFlush:PANYARGS
calCtxFlush TEXTEQU <__imp_calCtxFlush>
extern __imp_calCtxGetMem:PANYARGS
calCtxGetMem TEXTEQU <__imp_calCtxGetMem>
extern __imp_calCtxIsEventDone:PANYARGS
calCtxIsEventDone TEXTEQU <__imp_calCtxIsEventDone>
extern __imp_calCtxReleaseMem:PANYARGS
calCtxReleaseMem TEXTEQU <__imp_calCtxReleaseMem>
extern __imp_calCtxRunProgram:PANYARGS
calCtxRunProgram TEXTEQU <__imp_calCtxRunProgram>
extern __imp_calCtxRunProgramGrid:PANYARGS
calCtxRunProgramGrid TEXTEQU <__imp_calCtxRunProgramGrid>
extern __imp_calCtxRunProgramGridArray:PANYARGS
calCtxRunProgramGridArray TEXTEQU <__imp_calCtxRunProgramGridArray>
extern __imp_calCtxSetMem:PANYARGS
calCtxSetMem TEXTEQU <__imp_calCtxSetMem>
extern __imp_calDeviceClose:PANYARGS
calDeviceClose TEXTEQU <__imp_calDeviceClose>
extern __imp_calDeviceGetAttribs:PANYARGS
calDeviceGetAttribs TEXTEQU <__imp_calDeviceGetAttribs>
extern __imp_calDeviceGetCount:PANYARGS
calDeviceGetCount TEXTEQU <__imp_calDeviceGetCount>
extern __imp_calDeviceGetInfo:PANYARGS
calDeviceGetInfo TEXTEQU <__imp_calDeviceGetInfo>
extern __imp_calDeviceGetStatus:PANYARGS
calDeviceGetStatus TEXTEQU <__imp_calDeviceGetStatus>
extern __imp_calDeviceOpen:PANYARGS
calDeviceOpen TEXTEQU <__imp_calDeviceOpen>
extern __imp_calExtGetProc:PANYARGS
calExtGetProc TEXTEQU <__imp_calExtGetProc>
extern __imp_calExtGetVersion:PANYARGS
calExtGetVersion TEXTEQU <__imp_calExtGetVersion>
extern __imp_calExtSupported:PANYARGS
calExtSupported TEXTEQU <__imp_calExtSupported>
extern __imp_calGetErrorString:PANYARGS
calGetErrorString TEXTEQU <__imp_calGetErrorString>
extern __imp_calGetVersion:PANYARGS
calGetVersion TEXTEQU <__imp_calGetVersion>
extern __imp_calImageFree:PANYARGS
calImageFree TEXTEQU <__imp_calImageFree>
extern __imp_calImageRead:PANYARGS
calImageRead TEXTEQU <__imp_calImageRead>
extern __imp_calInit:PANYARGS
calInit TEXTEQU <__imp_calInit>
extern __imp_calMemCopy:PANYARGS
calMemCopy TEXTEQU <__imp_calMemCopy>
extern __imp_calModuleGetEntry:PANYARGS
calModuleGetEntry TEXTEQU <__imp_calModuleGetEntry>
extern __imp_calModuleGetFuncInfo:PANYARGS
calModuleGetFuncInfo TEXTEQU <__imp_calModuleGetFuncInfo>
extern __imp_calModuleGetName:PANYARGS
calModuleGetName TEXTEQU <__imp_calModuleGetName>
extern __imp_calModuleLoad:PANYARGS
calModuleLoad TEXTEQU <__imp_calModuleLoad>
extern __imp_calModuleUnload:PANYARGS
calModuleUnload TEXTEQU <__imp_calModuleUnload>
extern __imp_calResAllocLocal1D:PANYARGS
calResAllocLocal1D TEXTEQU <__imp_calResAllocLocal1D>
extern __imp_calResAllocLocal2D:PANYARGS
calResAllocLocal2D TEXTEQU <__imp_calResAllocLocal2D>
extern __imp_calResAllocRemote1D:PANYARGS
calResAllocRemote1D TEXTEQU <__imp_calResAllocRemote1D>
extern __imp_calResAllocRemote2D:PANYARGS
calResAllocRemote2D TEXTEQU <__imp_calResAllocRemote2D>
extern __imp_calResFree:PANYARGS
calResFree TEXTEQU <__imp_calResFree>
extern __imp_calResMap:PANYARGS
calResMap TEXTEQU <__imp_calResMap>
extern __imp_calResUnmap:PANYARGS
calResUnmap TEXTEQU <__imp_calResUnmap>
extern __imp_calShutdown:PANYARGS
calShutdown TEXTEQU <__imp_calShutdown>
