extern __imp_VCAMInitEntryPoints:PANYARGS
VCAMInitEntryPoints TEXTEQU <__imp_VCAMInitEntryPoints>
extern __imp_bDestroyVCAM:PANYARGS
bDestroyVCAM TEXTEQU <__imp_bDestroyVCAM>
extern __imp_bDisableVCAMByHDevice:PANYARGS
bDisableVCAMByHDevice TEXTEQU <__imp_bDisableVCAMByHDevice>
extern __imp_bVCAMInitialize:PANYARGS
bVCAMInitialize TEXTEQU <__imp_bVCAMInitialize>
extern __imp_bVCAMSetDriverCallsEx:PANYARGS
bVCAMSetDriverCallsEx TEXTEQU <__imp_bVCAMSetDriverCallsEx>
extern __imp_ulVCAMEscape:PANYARGS
ulVCAMEscape TEXTEQU <__imp_ulVCAMEscape>
extern __imp_ulVCAMGetHeaderVersion:PANYARGS
ulVCAMGetHeaderVersion TEXTEQU <__imp_ulVCAMGetHeaderVersion>
extern __imp_vNotifyVCAMCALLink:PANYARGS
vNotifyVCAMCALLink TEXTEQU <__imp_vNotifyVCAMCALLink>
extern __imp_vNotifyVCAMCALLink_WA:PANYARGS
vNotifyVCAMCALLink_W  TEXTEQU <__imp_vNotifyVCAMCALLink_WA>
extern __imp_GsDrvEnableDriver:PANYARGS
GsDrvEnableDriver TEXTEQU <__imp_GsDrvEnableDriver>
