extern __imp_bDestroyR0ORCA:PANYARGS
bDestroyR0ORC  TEXTEQU <__imp_bDestroyR0ORCA>
extern __imp_bDisableR0ORCA:PANYARGS
bDisableR0ORC  TEXTEQU <__imp_bDisableR0ORCA>
extern __imp_bOriginNotifyR0ORCA:PANYARGS
bOriginNotifyR0ORC  TEXTEQU <__imp_bOriginNotifyR0ORCA>
extern __imp_bR0ORCACreateWndObj:PANYARGS
bR0ORCACreateWndObj TEXTEQU <__imp_bR0ORCACreateWndObj>
extern __imp_bR0ORCAInitialize:PANYARGS
bR0ORCAInitialize TEXTEQU <__imp_bR0ORCAInitialize>
extern __imp_bR0ORCASetDriverCallsEx:PANYARGS
bR0ORCASetDriverCallsEx TEXTEQU <__imp_bR0ORCASetDriverCallsEx>
extern __imp_ulR0ORCAEscape:PANYARGS
ulR0ORCAEscape TEXTEQU <__imp_ulR0ORCAEscape>
