extern __imp_DrvCopyContext:PANYARGS
DrvCopyContext TEXTEQU <__imp_DrvCopyContext>
extern __imp_DrvCreateContext:PANYARGS
DrvCreateContext TEXTEQU <__imp_DrvCreateContext>
extern __imp_DrvCreateLayerContext:PANYARGS
DrvCreateLayerContext TEXTEQU <__imp_DrvCreateLayerContext>
extern __imp_DrvDeleteContext:PANYARGS
DrvDeleteContext TEXTEQU <__imp_DrvDeleteContext>
extern __imp_DrvDescribeLayerPlane:PANYARGS
DrvDescribeLayerPlane TEXTEQU <__imp_DrvDescribeLayerPlane>
extern __imp_DrvDescribePixelFormat:PANYARGS
DrvDescribePixelFormat TEXTEQU <__imp_DrvDescribePixelFormat>
extern __imp_DrvGetLayerPaletteEntries:PANYARGS
DrvGetLayerPaletteEntries TEXTEQU <__imp_DrvGetLayerPaletteEntries>
extern __imp_DrvGetProcAddress:PANYARGS
DrvGetProcAddress TEXTEQU <__imp_DrvGetProcAddress>
extern __imp_DrvRealizeLayerPalette:PANYARGS
DrvRealizeLayerPalette TEXTEQU <__imp_DrvRealizeLayerPalette>
extern __imp_DrvReleaseContext:PANYARGS
DrvReleaseContext TEXTEQU <__imp_DrvReleaseContext>
extern __imp_DrvSetContext:PANYARGS
DrvSetContext TEXTEQU <__imp_DrvSetContext>
extern __imp_DrvSetLayerPaletteEntries:PANYARGS
DrvSetLayerPaletteEntries TEXTEQU <__imp_DrvSetLayerPaletteEntries>
extern __imp_DrvSetPixelFormat:PANYARGS
DrvSetPixelFormat TEXTEQU <__imp_DrvSetPixelFormat>
extern __imp_DrvShareLists:PANYARGS
DrvShareLists TEXTEQU <__imp_DrvShareLists>
extern __imp_DrvSwapBuffers:PANYARGS
DrvSwapBuffers TEXTEQU <__imp_DrvSwapBuffers>
extern __imp_DrvSwapLayerBuffers:PANYARGS
DrvSwapLayerBuffers TEXTEQU <__imp_DrvSwapLayerBuffers>
extern __imp_DrvValidateVersion:PANYARGS
DrvValidateVersion TEXTEQU <__imp_DrvValidateVersion>
extern __imp_atiPPHSN:PANYARGS
atiPPHSN TEXTEQU <__imp_atiPPHSN>
extern __imp_atiPS:PANYARGS
atiPS TEXTEQU <__imp_atiPS>
extern __imp_atiQD:PANYARGS
atiQD TEXTEQU <__imp_atiQD>
extern __imp_atiQDS:PANYARGS
atiQDS TEXTEQU <__imp_atiQDS>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
