extern __imp_ATMAddFont:PANYARGS
ATMAddFont TEXTEQU <__imp_ATMAddFont>
extern __imp_ATMAddFontA:PANYARGS
ATMAddFont  TEXTEQU <__imp_ATMAddFontA>
extern __imp_ATMAddFontEx:PANYARGS
ATMAddFontEx TEXTEQU <__imp_ATMAddFontEx>
extern __imp_ATMAddFontExA:PANYARGS
ATMAddFontEx  TEXTEQU <__imp_ATMAddFontExA>
extern __imp_ATMAddFontExW:PANYARGS
ATMAddFontExW TEXTEQU <__imp_ATMAddFontExW>
extern __imp_ATMAddFontW:PANYARGS
ATMAddFontW TEXTEQU <__imp_ATMAddFontW>
extern __imp_ATMBBoxBaseXYShowText:PANYARGS
ATMBBoxBaseXYShowText TEXTEQU <__imp_ATMBBoxBaseXYShowText>
extern __imp_ATMBBoxBaseXYShowTextA:PANYARGS
ATMBBoxBaseXYShowText  TEXTEQU <__imp_ATMBBoxBaseXYShowTextA>
extern __imp_ATMBBoxBaseXYShowTextW:PANYARGS
ATMBBoxBaseXYShowTextW TEXTEQU <__imp_ATMBBoxBaseXYShowTextW>
extern __imp_ATMBeginFontChange:PANYARGS
ATMBeginFontChange TEXTEQU <__imp_ATMBeginFontChange>
extern __imp_ATMClient:PANYARGS
ATMClient TEXTEQU <__imp_ATMClient>
extern __imp_ATMEndFontChange:PANYARGS
ATMEndFontChange TEXTEQU <__imp_ATMEndFontChange>
extern __imp_ATMEnumFonts:PANYARGS
ATMEnumFonts TEXTEQU <__imp_ATMEnumFonts>
extern __imp_ATMEnumFontsA:PANYARGS
ATMEnumFonts  TEXTEQU <__imp_ATMEnumFontsA>
extern __imp_ATMEnumFontsW:PANYARGS
ATMEnumFontsW TEXTEQU <__imp_ATMEnumFontsW>
extern __imp_ATMEnumMMFonts:PANYARGS
ATMEnumMMFonts TEXTEQU <__imp_ATMEnumMMFonts>
extern __imp_ATMEnumMMFontsA:PANYARGS
ATMEnumMMFonts  TEXTEQU <__imp_ATMEnumMMFontsA>
extern __imp_ATMEnumMMFontsW:PANYARGS
ATMEnumMMFontsW TEXTEQU <__imp_ATMEnumMMFontsW>
extern __imp_ATMFinish:PANYARGS
ATMFinish TEXTEQU <__imp_ATMFinish>
extern __imp_ATMFontAvailable:PANYARGS
ATMFontAvailable TEXTEQU <__imp_ATMFontAvailable>
extern __imp_ATMFontAvailableA:PANYARGS
ATMFontAvailable  TEXTEQU <__imp_ATMFontAvailableA>
extern __imp_ATMFontAvailableW:PANYARGS
ATMFontAvailableW TEXTEQU <__imp_ATMFontAvailableW>
extern __imp_ATMFontSelected:PANYARGS
ATMFontSelected TEXTEQU <__imp_ATMFontSelected>
extern __imp_ATMFontStatus:PANYARGS
ATMFontStatus TEXTEQU <__imp_ATMFontStatus>
extern __imp_ATMFontStatusA:PANYARGS
ATMFontStatus  TEXTEQU <__imp_ATMFontStatusA>
extern __imp_ATMFontStatusW:PANYARGS
ATMFontStatusW TEXTEQU <__imp_ATMFontStatusW>
extern __imp_ATMForceFontChange:PANYARGS
ATMForceFontChange TEXTEQU <__imp_ATMForceFontChange>
extern __imp_ATMGetBuildStr:PANYARGS
ATMGetBuildStr TEXTEQU <__imp_ATMGetBuildStr>
extern __imp_ATMGetBuildStrA:PANYARGS
ATMGetBuildStr  TEXTEQU <__imp_ATMGetBuildStrA>
extern __imp_ATMGetBuildStrW:PANYARGS
ATMGetBuildStrW TEXTEQU <__imp_ATMGetBuildStrW>
extern __imp_ATMGetFontBBox:PANYARGS
ATMGetFontBBox TEXTEQU <__imp_ATMGetFontBBox>
extern __imp_ATMGetFontInfo:PANYARGS
ATMGetFontInfo TEXTEQU <__imp_ATMGetFontInfo>
extern __imp_ATMGetFontInfoA:PANYARGS
ATMGetFontInfo  TEXTEQU <__imp_ATMGetFontInfoA>
extern __imp_ATMGetFontInfoW:PANYARGS
ATMGetFontInfoW TEXTEQU <__imp_ATMGetFontInfoW>
extern __imp_ATMGetFontPaths:PANYARGS
ATMGetFontPaths TEXTEQU <__imp_ATMGetFontPaths>
extern __imp_ATMGetFontPathsA:PANYARGS
ATMGetFontPaths  TEXTEQU <__imp_ATMGetFontPathsA>
extern __imp_ATMGetFontPathsW:PANYARGS
ATMGetFontPathsW TEXTEQU <__imp_ATMGetFontPathsW>
extern __imp_ATMGetGlyphList:PANYARGS
ATMGetGlyphList TEXTEQU <__imp_ATMGetGlyphList>
extern __imp_ATMGetGlyphListA:PANYARGS
ATMGetGlyphList  TEXTEQU <__imp_ATMGetGlyphListA>
extern __imp_ATMGetGlyphListW:PANYARGS
ATMGetGlyphListW TEXTEQU <__imp_ATMGetGlyphListW>
extern __imp_ATMGetMenuName:PANYARGS
ATMGetMenuName TEXTEQU <__imp_ATMGetMenuName>
extern __imp_ATMGetMenuNameA:PANYARGS
ATMGetMenuName  TEXTEQU <__imp_ATMGetMenuNameA>
extern __imp_ATMGetMenuNameW:PANYARGS
ATMGetMenuNameW TEXTEQU <__imp_ATMGetMenuNameW>
extern __imp_ATMGetNtmFields:PANYARGS
ATMGetNtmFields TEXTEQU <__imp_ATMGetNtmFields>
extern __imp_ATMGetNtmFieldsA:PANYARGS
ATMGetNtmFields  TEXTEQU <__imp_ATMGetNtmFieldsA>
extern __imp_ATMGetNtmFieldsW:PANYARGS
ATMGetNtmFieldsW TEXTEQU <__imp_ATMGetNtmFieldsW>
extern __imp_ATMGetOutline:PANYARGS
ATMGetOutline TEXTEQU <__imp_ATMGetOutline>
extern __imp_ATMGetOutlineA:PANYARGS
ATMGetOutline  TEXTEQU <__imp_ATMGetOutlineA>
extern __imp_ATMGetOutlineW:PANYARGS
ATMGetOutlineW TEXTEQU <__imp_ATMGetOutlineW>
extern __imp_ATMGetPostScriptName:PANYARGS
ATMGetPostScriptName TEXTEQU <__imp_ATMGetPostScriptName>
extern __imp_ATMGetPostScriptNameA:PANYARGS
ATMGetPostScriptName  TEXTEQU <__imp_ATMGetPostScriptNameA>
extern __imp_ATMGetPostScriptNameW:PANYARGS
ATMGetPostScriptNameW TEXTEQU <__imp_ATMGetPostScriptNameW>
extern __imp_ATMGetVersion:PANYARGS
ATMGetVersion TEXTEQU <__imp_ATMGetVersion>
extern __imp_ATMGetVersionEx:PANYARGS
ATMGetVersionEx TEXTEQU <__imp_ATMGetVersionEx>
extern __imp_ATMGetVersionExA:PANYARGS
ATMGetVersionEx  TEXTEQU <__imp_ATMGetVersionExA>
extern __imp_ATMGetVersionExW:PANYARGS
ATMGetVersionExW TEXTEQU <__imp_ATMGetVersionExW>
extern __imp_ATMInstallSubstFontA:PANYARGS
ATMInstallSubstFont  TEXTEQU <__imp_ATMInstallSubstFontA>
extern __imp_ATMInstallSubstFontW:PANYARGS
ATMInstallSubstFontW TEXTEQU <__imp_ATMInstallSubstFontW>
extern __imp_ATMMakePFM:PANYARGS
ATMMakePFM TEXTEQU <__imp_ATMMakePFM>
extern __imp_ATMMakePFMA:PANYARGS
ATMMakePFM  TEXTEQU <__imp_ATMMakePFMA>
extern __imp_ATMMakePFMW:PANYARGS
ATMMakePFMW TEXTEQU <__imp_ATMMakePFMW>
extern __imp_ATMMakePSS:PANYARGS
ATMMakePSS TEXTEQU <__imp_ATMMakePSS>
extern __imp_ATMMakePSSA:PANYARGS
ATMMakePSS  TEXTEQU <__imp_ATMMakePSSA>
extern __imp_ATMMakePSSW:PANYARGS
ATMMakePSSW TEXTEQU <__imp_ATMMakePSSW>
extern __imp_ATMProperlyLoaded:PANYARGS
ATMProperlyLoaded TEXTEQU <__imp_ATMProperlyLoaded>
extern __imp_ATMRemoveFont:PANYARGS
ATMRemoveFont TEXTEQU <__imp_ATMRemoveFont>
extern __imp_ATMRemoveFontA:PANYARGS
ATMRemoveFont  TEXTEQU <__imp_ATMRemoveFontA>
extern __imp_ATMRemoveFontW:PANYARGS
ATMRemoveFontW TEXTEQU <__imp_ATMRemoveFontW>
extern __imp_ATMRemoveSubstFontA:PANYARGS
ATMRemoveSubstFont  TEXTEQU <__imp_ATMRemoveSubstFontA>
extern __imp_ATMRemoveSubstFontW:PANYARGS
ATMRemoveSubstFontW TEXTEQU <__imp_ATMRemoveSubstFontW>
extern __imp_ATMSelectEncoding:PANYARGS
ATMSelectEncoding TEXTEQU <__imp_ATMSelectEncoding>
extern __imp_ATMSelectObject:PANYARGS
ATMSelectObject TEXTEQU <__imp_ATMSelectObject>
extern __imp_ATMSetFlags:PANYARGS
ATMSetFlags TEXTEQU <__imp_ATMSetFlags>
extern __imp_ATMXYShowText:PANYARGS
ATMXYShowText TEXTEQU <__imp_ATMXYShowText>
extern __imp_ATMXYShowTextA:PANYARGS
ATMXYShowText  TEXTEQU <__imp_ATMXYShowTextA>
extern __imp_ATMXYShowTextW:PANYARGS
ATMXYShowTextW TEXTEQU <__imp_ATMXYShowTextW>
