extern __imp_AddEmailToAutoComplete:PANYARGS
AddEmailToAutoComplete TEXTEQU <__imp_AddEmailToAutoComplete>
extern __imp_AutoDiscoverAndOpenEmail:PANYARGS
AutoDiscoverAndOpenEmail TEXTEQU <__imp_AutoDiscoverAndOpenEmail>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
