extern __imp_AppCleanup:PANYARGS
AppCleanup TEXTEQU <__imp_AppCleanup>
extern __imp_capCreateCaptureWindowA:PANYARGS
capCreateCaptureWindow  TEXTEQU <__imp_capCreateCaptureWindowA>
extern __imp_capCreateCaptureWindowW:PANYARGS
capCreateCaptureWindowW TEXTEQU <__imp_capCreateCaptureWindowW>
extern __imp_capGetDriverDescriptionA:PANYARGS
capGetDriverDescription  TEXTEQU <__imp_capGetDriverDescriptionA>
extern __imp_capGetDriverDescriptionW:PANYARGS
capGetDriverDescriptionW TEXTEQU <__imp_capGetDriverDescriptionW>
extern __imp_videoThunk32:PANYARGS
videoThunk32 TEXTEQU <__imp_videoThunk32>
