extern __imp_AVIBuildFilter:PANYARGS
AVIBuildFilter TEXTEQU <__imp_AVIBuildFilter>
extern __imp_AVIBuildFilterA:PANYARGS
AVIBuildFilter  TEXTEQU <__imp_AVIBuildFilterA>
extern __imp_AVIBuildFilterW:PANYARGS
AVIBuildFilterW TEXTEQU <__imp_AVIBuildFilterW>
extern __imp_AVIClearClipboard:PANYARGS
AVIClearClipboard TEXTEQU <__imp_AVIClearClipboard>
extern __imp_AVIFileAddRef:PANYARGS
AVIFileAddRef TEXTEQU <__imp_AVIFileAddRef>
extern __imp_AVIFileCreateStream:PANYARGS
AVIFileCreateStream TEXTEQU <__imp_AVIFileCreateStream>
extern __imp_AVIFileCreateStreamA:PANYARGS
AVIFileCreateStream  TEXTEQU <__imp_AVIFileCreateStreamA>
extern __imp_AVIFileCreateStreamW:PANYARGS
AVIFileCreateStreamW TEXTEQU <__imp_AVIFileCreateStreamW>
extern __imp_AVIFileEndRecord:PANYARGS
AVIFileEndRecord TEXTEQU <__imp_AVIFileEndRecord>
extern __imp_AVIFileExit:PANYARGS
AVIFileExit TEXTEQU <__imp_AVIFileExit>
extern __imp_AVIFileGetStream:PANYARGS
AVIFileGetStream TEXTEQU <__imp_AVIFileGetStream>
extern __imp_AVIFileInfo:PANYARGS
AVIFileInfo TEXTEQU <__imp_AVIFileInfo>
extern __imp_AVIFileInfoA:PANYARGS
AVIFileInfo  TEXTEQU <__imp_AVIFileInfoA>
extern __imp_AVIFileInfoW:PANYARGS
AVIFileInfoW TEXTEQU <__imp_AVIFileInfoW>
extern __imp_AVIFileInit:PANYARGS
AVIFileInit TEXTEQU <__imp_AVIFileInit>
extern __imp_AVIFileOpen:PANYARGS
AVIFileOpen TEXTEQU <__imp_AVIFileOpen>
extern __imp_AVIFileOpenA:PANYARGS
AVIFileOpen  TEXTEQU <__imp_AVIFileOpenA>
extern __imp_AVIFileOpenW:PANYARGS
AVIFileOpenW TEXTEQU <__imp_AVIFileOpenW>
extern __imp_AVIFileReadData:PANYARGS
AVIFileReadData TEXTEQU <__imp_AVIFileReadData>
extern __imp_AVIFileRelease:PANYARGS
AVIFileRelease TEXTEQU <__imp_AVIFileRelease>
extern __imp_AVIFileWriteData:PANYARGS
AVIFileWriteData TEXTEQU <__imp_AVIFileWriteData>
extern __imp_AVIGetFromClipboard:PANYARGS
AVIGetFromClipboard TEXTEQU <__imp_AVIGetFromClipboard>
extern __imp_AVIMakeCompressedStream:PANYARGS
AVIMakeCompressedStream TEXTEQU <__imp_AVIMakeCompressedStream>
extern __imp_AVIMakeFileFromStreams:PANYARGS
AVIMakeFileFromStreams TEXTEQU <__imp_AVIMakeFileFromStreams>
extern __imp_AVIMakeStreamFromClipboard:PANYARGS
AVIMakeStreamFromClipboard TEXTEQU <__imp_AVIMakeStreamFromClipboard>
extern __imp_AVIPutFileOnClipboard:PANYARGS
AVIPutFileOnClipboard TEXTEQU <__imp_AVIPutFileOnClipboard>
extern __imp_AVISave:PANYARGS
AVISave TEXTEQU <__imp_AVISave>
extern __imp_AVISaveA:PANYARGS
AVISave  TEXTEQU <__imp_AVISaveA>
extern __imp_AVISaveOptions:PANYARGS
AVISaveOptions TEXTEQU <__imp_AVISaveOptions>
extern __imp_AVISaveOptionsFree:PANYARGS
AVISaveOptionsFree TEXTEQU <__imp_AVISaveOptionsFree>
extern __imp_AVISaveV:PANYARGS
AVISaveV TEXTEQU <__imp_AVISaveV>
extern __imp_AVISaveVA:PANYARGS
AVISaveV  TEXTEQU <__imp_AVISaveVA>
extern __imp_AVISaveVW:PANYARGS
AVISaveVW TEXTEQU <__imp_AVISaveVW>
extern __imp_AVISaveW:PANYARGS
AVISaveW TEXTEQU <__imp_AVISaveW>
extern __imp_AVIStreamAddRef:PANYARGS
AVIStreamAddRef TEXTEQU <__imp_AVIStreamAddRef>
extern __imp_AVIStreamBeginStreaming:PANYARGS
AVIStreamBeginStreaming TEXTEQU <__imp_AVIStreamBeginStreaming>
extern __imp_AVIStreamCreate:PANYARGS
AVIStreamCreate TEXTEQU <__imp_AVIStreamCreate>
extern __imp_AVIStreamEndStreaming:PANYARGS
AVIStreamEndStreaming TEXTEQU <__imp_AVIStreamEndStreaming>
extern __imp_AVIStreamFindSample:PANYARGS
AVIStreamFindSample TEXTEQU <__imp_AVIStreamFindSample>
extern __imp_AVIStreamGetFrame:PANYARGS
AVIStreamGetFrame TEXTEQU <__imp_AVIStreamGetFrame>
extern __imp_AVIStreamGetFrameClose:PANYARGS
AVIStreamGetFrameClose TEXTEQU <__imp_AVIStreamGetFrameClose>
extern __imp_AVIStreamGetFrameOpen:PANYARGS
AVIStreamGetFrameOpen TEXTEQU <__imp_AVIStreamGetFrameOpen>
extern __imp_AVIStreamInfo:PANYARGS
AVIStreamInfo TEXTEQU <__imp_AVIStreamInfo>
extern __imp_AVIStreamInfoA:PANYARGS
AVIStreamInfo  TEXTEQU <__imp_AVIStreamInfoA>
extern __imp_AVIStreamInfoW:PANYARGS
AVIStreamInfoW TEXTEQU <__imp_AVIStreamInfoW>
extern __imp_AVIStreamLength:PANYARGS
AVIStreamLength TEXTEQU <__imp_AVIStreamLength>
extern __imp_AVIStreamOpenFromFile:PANYARGS
AVIStreamOpenFromFile TEXTEQU <__imp_AVIStreamOpenFromFile>
extern __imp_AVIStreamOpenFromFileA:PANYARGS
AVIStreamOpenFromFile  TEXTEQU <__imp_AVIStreamOpenFromFileA>
extern __imp_AVIStreamOpenFromFileW:PANYARGS
AVIStreamOpenFromFileW TEXTEQU <__imp_AVIStreamOpenFromFileW>
extern __imp_AVIStreamRead:PANYARGS
AVIStreamRead TEXTEQU <__imp_AVIStreamRead>
extern __imp_AVIStreamReadData:PANYARGS
AVIStreamReadData TEXTEQU <__imp_AVIStreamReadData>
extern __imp_AVIStreamReadFormat:PANYARGS
AVIStreamReadFormat TEXTEQU <__imp_AVIStreamReadFormat>
extern __imp_AVIStreamRelease:PANYARGS
AVIStreamRelease TEXTEQU <__imp_AVIStreamRelease>
extern __imp_AVIStreamSampleToTime:PANYARGS
AVIStreamSampleToTime TEXTEQU <__imp_AVIStreamSampleToTime>
extern __imp_AVIStreamSetFormat:PANYARGS
AVIStreamSetFormat TEXTEQU <__imp_AVIStreamSetFormat>
extern __imp_AVIStreamStart:PANYARGS
AVIStreamStart TEXTEQU <__imp_AVIStreamStart>
extern __imp_AVIStreamTimeToSample:PANYARGS
AVIStreamTimeToSample TEXTEQU <__imp_AVIStreamTimeToSample>
extern __imp_AVIStreamWrite:PANYARGS
AVIStreamWrite TEXTEQU <__imp_AVIStreamWrite>
extern __imp_AVIStreamWriteData:PANYARGS
AVIStreamWriteData TEXTEQU <__imp_AVIStreamWriteData>
extern __imp_CreateEditableStream:PANYARGS
CreateEditableStream TEXTEQU <__imp_CreateEditableStream>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_EditStreamClone:PANYARGS
EditStreamClone TEXTEQU <__imp_EditStreamClone>
extern __imp_EditStreamCopy:PANYARGS
EditStreamCopy TEXTEQU <__imp_EditStreamCopy>
extern __imp_EditStreamCut:PANYARGS
EditStreamCut TEXTEQU <__imp_EditStreamCut>
extern __imp_EditStreamPaste:PANYARGS
EditStreamPaste TEXTEQU <__imp_EditStreamPaste>
extern __imp_EditStreamSetInfo:PANYARGS
EditStreamSetInfo TEXTEQU <__imp_EditStreamSetInfo>
extern __imp_EditStreamSetInfoA:PANYARGS
EditStreamSetInfo  TEXTEQU <__imp_EditStreamSetInfoA>
extern __imp_EditStreamSetInfoW:PANYARGS
EditStreamSetInfoW TEXTEQU <__imp_EditStreamSetInfoW>
extern __imp_EditStreamSetName:PANYARGS
EditStreamSetName TEXTEQU <__imp_EditStreamSetName>
extern __imp_EditStreamSetNameA:PANYARGS
EditStreamSetName  TEXTEQU <__imp_EditStreamSetNameA>
extern __imp_EditStreamSetNameW:PANYARGS
EditStreamSetNameW TEXTEQU <__imp_EditStreamSetNameW>
extern __imp_IID_IAVIEditStream:PANYARGS
IID_IAVIEditStream TEXTEQU <__imp_IID_IAVIEditStream>
extern __imp_IID_IAVIFile:PANYARGS
IID_IAVIFile TEXTEQU <__imp_IID_IAVIFile>
extern __imp_IID_IAVIStream:PANYARGS
IID_IAVIStream TEXTEQU <__imp_IID_IAVIStream>
extern __imp_IID_IGetFrame:PANYARGS
IID_IGetFrame TEXTEQU <__imp_IID_IGetFrame>
