extern __imp_AzAddPropertyItem:PANYARGS
AzAddPropertyItem TEXTEQU <__imp_AzAddPropertyItem>
extern __imp_AzApplicationClose:PANYARGS
AzApplicationClose TEXTEQU <__imp_AzApplicationClose>
extern __imp_AzApplicationCreate:PANYARGS
AzApplicationCreate TEXTEQU <__imp_AzApplicationCreate>
extern __imp_AzApplicationDelete:PANYARGS
AzApplicationDelete TEXTEQU <__imp_AzApplicationDelete>
extern __imp_AzApplicationEnum:PANYARGS
AzApplicationEnum TEXTEQU <__imp_AzApplicationEnum>
extern __imp_AzApplicationOpen:PANYARGS
AzApplicationOpen TEXTEQU <__imp_AzApplicationOpen>
extern __imp_AzAuthorizationStoreDelete:PANYARGS
AzAuthorizationStoreDelete TEXTEQU <__imp_AzAuthorizationStoreDelete>
extern __imp_AzCloseHandle:PANYARGS
AzCloseHandle TEXTEQU <__imp_AzCloseHandle>
extern __imp_AzContextAccessCheck:PANYARGS
AzContextAccessCheck TEXTEQU <__imp_AzContextAccessCheck>
extern __imp_AzContextGetAssignedScopesPage:PANYARGS
AzContextGetAssignedScopesPage TEXTEQU <__imp_AzContextGetAssignedScopesPage>
extern __imp_AzContextGetRoles:PANYARGS
AzContextGetRoles TEXTEQU <__imp_AzContextGetRoles>
extern __imp_AzFreeMemory:PANYARGS
AzFreeMemory TEXTEQU <__imp_AzFreeMemory>
extern __imp_AzGetProperty:PANYARGS
AzGetProperty TEXTEQU <__imp_AzGetProperty>
extern __imp_AzGroupCreate:PANYARGS
AzGroupCreate TEXTEQU <__imp_AzGroupCreate>
extern __imp_AzGroupDelete:PANYARGS
AzGroupDelete TEXTEQU <__imp_AzGroupDelete>
extern __imp_AzGroupEnum:PANYARGS
AzGroupEnum TEXTEQU <__imp_AzGroupEnum>
extern __imp_AzGroupOpen:PANYARGS
AzGroupOpen TEXTEQU <__imp_AzGroupOpen>
extern __imp_AzInitialize:PANYARGS
AzInitialize TEXTEQU <__imp_AzInitialize>
extern __imp_AzInitializeContextFromName:PANYARGS
AzInitializeContextFromName TEXTEQU <__imp_AzInitializeContextFromName>
extern __imp_AzInitializeContextFromToken:PANYARGS
AzInitializeContextFromToken TEXTEQU <__imp_AzInitializeContextFromToken>
extern __imp_AzOperationCreate:PANYARGS
AzOperationCreate TEXTEQU <__imp_AzOperationCreate>
extern __imp_AzOperationDelete:PANYARGS
AzOperationDelete TEXTEQU <__imp_AzOperationDelete>
extern __imp_AzOperationEnum:PANYARGS
AzOperationEnum TEXTEQU <__imp_AzOperationEnum>
extern __imp_AzOperationOpen:PANYARGS
AzOperationOpen TEXTEQU <__imp_AzOperationOpen>
extern __imp_AzRemovePropertyItem:PANYARGS
AzRemovePropertyItem TEXTEQU <__imp_AzRemovePropertyItem>
extern __imp_AzRoleCreate:PANYARGS
AzRoleCreate TEXTEQU <__imp_AzRoleCreate>
extern __imp_AzRoleDelete:PANYARGS
AzRoleDelete TEXTEQU <__imp_AzRoleDelete>
extern __imp_AzRoleEnum:PANYARGS
AzRoleEnum TEXTEQU <__imp_AzRoleEnum>
extern __imp_AzRoleOpen:PANYARGS
AzRoleOpen TEXTEQU <__imp_AzRoleOpen>
extern __imp_AzScopeCreate:PANYARGS
AzScopeCreate TEXTEQU <__imp_AzScopeCreate>
extern __imp_AzScopeDelete:PANYARGS
AzScopeDelete TEXTEQU <__imp_AzScopeDelete>
extern __imp_AzScopeEnum:PANYARGS
AzScopeEnum TEXTEQU <__imp_AzScopeEnum>
extern __imp_AzScopeOpen:PANYARGS
AzScopeOpen TEXTEQU <__imp_AzScopeOpen>
extern __imp_AzSetProperty:PANYARGS
AzSetProperty TEXTEQU <__imp_AzSetProperty>
extern __imp_AzSubmit:PANYARGS
AzSubmit TEXTEQU <__imp_AzSubmit>
extern __imp_AzTaskCreate:PANYARGS
AzTaskCreate TEXTEQU <__imp_AzTaskCreate>
extern __imp_AzTaskDelete:PANYARGS
AzTaskDelete TEXTEQU <__imp_AzTaskDelete>
extern __imp_AzTaskEnum:PANYARGS
AzTaskEnum TEXTEQU <__imp_AzTaskEnum>
extern __imp_AzTaskOpen:PANYARGS
AzTaskOpen TEXTEQU <__imp_AzTaskOpen>
extern __imp_AzUpdateCache:PANYARGS
AzUpdateCache TEXTEQU <__imp_AzUpdateCache>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
