extern __imp_BatMeterCapabilities:PANYARGS
BatMeterCapabilities TEXTEQU <__imp_BatMeterCapabilities>
extern __imp_CreateBatMeter:PANYARGS
CreateBatMeter TEXTEQU <__imp_CreateBatMeter>
extern __imp_DestroyBatMeter:PANYARGS
DestroyBatMeter TEXTEQU <__imp_DestroyBatMeter>
extern __imp_PowerCapabilities:PANYARGS
PowerCapabilities TEXTEQU <__imp_PowerCapabilities>
extern __imp_UpdateBatMeter:PANYARGS
UpdateBatMeter TEXTEQU <__imp_UpdateBatMeter>
