extern __imp_VidBitBlt:PANYARGS
VidBitBlt TEXTEQU <__imp_VidBitBlt>
extern __imp_VidBufferToScreenBlt:PANYARGS
VidBufferToScreenBlt TEXTEQU <__imp_VidBufferToScreenBlt>
extern __imp_VidCleanUp:PANYARGS
VidCleanUp TEXTEQU <__imp_VidCleanUp>
extern __imp_VidDisplayString:PANYARGS
VidDisplayString TEXTEQU <__imp_VidDisplayString>
extern __imp_VidDisplayStringXY:PANYARGS
VidDisplayStringXY TEXTEQU <__imp_VidDisplayStringXY>
extern __imp_VidInitialize:PANYARGS
VidInitialize TEXTEQU <__imp_VidInitialize>
extern __imp_VidResetDisplay:PANYARGS
VidResetDisplay TEXTEQU <__imp_VidResetDisplay>
extern __imp_VidScreenToBufferBlt:PANYARGS
VidScreenToBufferBlt TEXTEQU <__imp_VidScreenToBufferBlt>
extern __imp_VidSetScrollRegion:PANYARGS
VidSetScrollRegion TEXTEQU <__imp_VidSetScrollRegion>
extern __imp_VidSetTextColor:PANYARGS
VidSetTextColor TEXTEQU <__imp_VidSetTextColor>
extern __imp_VidSolidColorFill:PANYARGS
VidSolidColorFill TEXTEQU <__imp_VidSolidColorFill>
