extern __imp_browseui_ordinal101:PANYARGS
browseui_ordinal101 TEXTEQU <__imp_browseui_ordinal101>
extern __imp_browseui_ordinal102:PANYARGS
browseui_ordinal102 TEXTEQU <__imp_browseui_ordinal102>
extern __imp_browseui_ordinal103:PANYARGS
browseui_ordinal103 TEXTEQU <__imp_browseui_ordinal103>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_browseui_ordinal105:PANYARGS
browseui_ordinal105 TEXTEQU <__imp_browseui_ordinal105>
extern __imp_browseui_ordinal106:PANYARGS
browseui_ordinal106 TEXTEQU <__imp_browseui_ordinal106>
extern __imp_browseui_ordinal107:PANYARGS
browseui_ordinal107 TEXTEQU <__imp_browseui_ordinal107>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllGetVersion:PANYARGS
DllGetVersion TEXTEQU <__imp_DllGetVersion>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_browseui_ordinal113:PANYARGS
browseui_ordinal113 TEXTEQU <__imp_browseui_ordinal113>
extern __imp_browseui_ordinal114:PANYARGS
browseui_ordinal114 TEXTEQU <__imp_browseui_ordinal114>
extern __imp_browseui_ordinal115:PANYARGS
browseui_ordinal115 TEXTEQU <__imp_browseui_ordinal115>
extern __imp_browseui_ordinal116:PANYARGS
browseui_ordinal116 TEXTEQU <__imp_browseui_ordinal116>
extern __imp_browseui_ordinal117:PANYARGS
browseui_ordinal117 TEXTEQU <__imp_browseui_ordinal117>
extern __imp_browseui_ordinal118:PANYARGS
browseui_ordinal118 TEXTEQU <__imp_browseui_ordinal118>
extern __imp_browseui_ordinal119:PANYARGS
browseui_ordinal119 TEXTEQU <__imp_browseui_ordinal119>
extern __imp_browseui_ordinal120:PANYARGS
browseui_ordinal120 TEXTEQU <__imp_browseui_ordinal120>
extern __imp_browseui_ordinal121:PANYARGS
browseui_ordinal121 TEXTEQU <__imp_browseui_ordinal121>
extern __imp_browseui_ordinal122:PANYARGS
browseui_ordinal122 TEXTEQU <__imp_browseui_ordinal122>
extern __imp_browseui_ordinal123:PANYARGS
browseui_ordinal123 TEXTEQU <__imp_browseui_ordinal123>
extern __imp_browseui_ordinal124:PANYARGS
browseui_ordinal124 TEXTEQU <__imp_browseui_ordinal124>
extern __imp_browseui_ordinal125:PANYARGS
browseui_ordinal125 TEXTEQU <__imp_browseui_ordinal125>
extern __imp_browseui_ordinal126:PANYARGS
browseui_ordinal126 TEXTEQU <__imp_browseui_ordinal126>
extern __imp_browseui_ordinal127:PANYARGS
browseui_ordinal127 TEXTEQU <__imp_browseui_ordinal127>
extern __imp_browseui_ordinal128:PANYARGS
browseui_ordinal128 TEXTEQU <__imp_browseui_ordinal128>
extern __imp_browseui_ordinal129:PANYARGS
browseui_ordinal129 TEXTEQU <__imp_browseui_ordinal129>
extern __imp_browseui_ordinal130:PANYARGS
browseui_ordinal130 TEXTEQU <__imp_browseui_ordinal130>
extern __imp_browseui_ordinal131:PANYARGS
browseui_ordinal131 TEXTEQU <__imp_browseui_ordinal131>
extern __imp_browseui_ordinal132:PANYARGS
browseui_ordinal132 TEXTEQU <__imp_browseui_ordinal132>
extern __imp_browseui_ordinal133:PANYARGS
browseui_ordinal133 TEXTEQU <__imp_browseui_ordinal133>
extern __imp_browseui_ordinal134:PANYARGS
browseui_ordinal134 TEXTEQU <__imp_browseui_ordinal134>
extern __imp_browseui_ordinal135:PANYARGS
browseui_ordinal135 TEXTEQU <__imp_browseui_ordinal135>
extern __imp_browseui_ordinal136:PANYARGS
browseui_ordinal136 TEXTEQU <__imp_browseui_ordinal136>
extern __imp_browseui_ordinal137:PANYARGS
browseui_ordinal137 TEXTEQU <__imp_browseui_ordinal137>
extern __imp_browseui_ordinal138:PANYARGS
browseui_ordinal138 TEXTEQU <__imp_browseui_ordinal138>
