extern __imp_GetDllVersion:PANYARGS
GetDllVersion TEXTEQU <__imp_GetDllVersion>
extern __imp_DllGetVersion:PANYARGS
DllGetVersion TEXTEQU <__imp_DllGetVersion>
extern __imp_Extract:PANYARGS
Extract TEXTEQU <__imp_Extract>
extern __imp_DeleteExtractedFiles:PANYARGS
DeleteExtractedFiles TEXTEQU <__imp_DeleteExtractedFiles>
extern __imp_cabinet_ordinal5:PANYARGS
cabinet_ordinal5 TEXTEQU <__imp_cabinet_ordinal5>
extern __imp_cabinet_ordinal6:PANYARGS
cabinet_ordinal6 TEXTEQU <__imp_cabinet_ordinal6>
extern __imp_cabinet_ordinal7:PANYARGS
cabinet_ordinal7 TEXTEQU <__imp_cabinet_ordinal7>
extern __imp_cabinet_ordinal8:PANYARGS
cabinet_ordinal8 TEXTEQU <__imp_cabinet_ordinal8>
extern __imp_cabinet_ordinal9:PANYARGS
cabinet_ordinal9 TEXTEQU <__imp_cabinet_ordinal9>
extern __imp_FCICreate:PANYARGS
FCICreate TEXTEQU <__imp_FCICreate>
extern __imp_FCIAddFile:PANYARGS
FCIAddFile TEXTEQU <__imp_FCIAddFile>
extern __imp_FCIFlushFolder:PANYARGS
FCIFlushFolder TEXTEQU <__imp_FCIFlushFolder>
extern __imp_FCIFlushCabinet:PANYARGS
FCIFlushCabinet TEXTEQU <__imp_FCIFlushCabinet>
extern __imp_FCIDestroy:PANYARGS
FCIDestroy TEXTEQU <__imp_FCIDestroy>
extern __imp_cabinet_ordinal15:PANYARGS
cabinet_ordinal15 TEXTEQU <__imp_cabinet_ordinal15>
extern __imp_cabinet_ordinal16:PANYARGS
cabinet_ordinal16 TEXTEQU <__imp_cabinet_ordinal16>
extern __imp_cabinet_ordinal17:PANYARGS
cabinet_ordinal17 TEXTEQU <__imp_cabinet_ordinal17>
extern __imp_cabinet_ordinal18:PANYARGS
cabinet_ordinal18 TEXTEQU <__imp_cabinet_ordinal18>
extern __imp_cabinet_ordinal19:PANYARGS
cabinet_ordinal19 TEXTEQU <__imp_cabinet_ordinal19>
extern __imp_FDICreate:PANYARGS
FDICreate TEXTEQU <__imp_FDICreate>
extern __imp_FDIIsCabinet:PANYARGS
FDIIsCabinet TEXTEQU <__imp_FDIIsCabinet>
extern __imp_FDICopy:PANYARGS
FDICopy TEXTEQU <__imp_FDICopy>
extern __imp_FDIDestroy:PANYARGS
FDIDestroy TEXTEQU <__imp_FDIDestroy>
extern __imp_FDITruncateCabinet:PANYARGS
FDITruncateCabinet TEXTEQU <__imp_FDITruncateCabinet>
