extern __imp_?CancelWriteICR@@YAJPEAPEAUIComponentRecords@@@Z:PANYARGS
?CancelWriteICR@@YAJPEAPEAUIComponentRecords@@@Z TEXTEQU <__imp_?CancelWriteICR@@YAJPEAPEAUIComponentRecords@@@Z>
extern __imp_CreateComponentLibraryTS:PANYARGS
CreateComponentLibraryTS TEXTEQU <__imp_CreateComponentLibraryTS>
extern __imp_GetCatalogCRMClerk:PANYARGS
GetCatalogCRMClerk TEXTEQU <__imp_GetCatalogCRMClerk>
extern __imp_?GetReadICR@@YAJHPEAPEAUIComponentRecords@@@Z:PANYARGS
?GetReadICR@@YAJHPEAPEAUIComponentRecords@@@Z TEXTEQU <__imp_?GetReadICR@@YAJHPEAPEAUIComponentRecords@@@Z>
extern __imp_?GetWriteICR@@YAJPEAPEAUIComponentRecords@@@Z:PANYARGS
?GetWriteICR@@YAJPEAPEAUIComponentRecords@@@Z TEXTEQU <__imp_?GetWriteICR@@YAJPEAPEAUIComponentRecords@@@Z>
extern __imp_OpenComponentLibraryTS:PANYARGS
OpenComponentLibraryTS TEXTEQU <__imp_OpenComponentLibraryTS>
extern __imp_?ReleaseReadICR@@YAXPEAPEAUIComponentRecords@@@Z:PANYARGS
?ReleaseReadICR@@YAXPEAPEAUIComponentRecords@@@Z TEXTEQU <__imp_?ReleaseReadICR@@YAXPEAPEAUIComponentRecords@@@Z>
extern __imp_?SaveWriteICR@@YAJPEAPEAUIComponentRecords@@@Z:PANYARGS
?SaveWriteICR@@YAJPEAPEAUIComponentRecords@@@Z TEXTEQU <__imp_?SaveWriteICR@@YAJPEAPEAUIComponentRecords@@@Z>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
