extern __imp_??0CComPlusComponent@@QEAA@AEBV0@@Z:PANYARGS
??0CComPlusComponent@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CComPlusComponent@@QEAA@AEBV0@@Z>
extern __imp_??0CComPlusInterface@@QEAA@AEBV0@@Z:PANYARGS
??0CComPlusInterface@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CComPlusInterface@@QEAA@AEBV0@@Z>
extern __imp_??0CComPlusMethod@@QEAA@AEBV0@@Z:PANYARGS
??0CComPlusMethod@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CComPlusMethod@@QEAA@AEBV0@@Z>
extern __imp_??0CComPlusObject@@QEAA@AEBV0@@Z:PANYARGS
??0CComPlusObject@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CComPlusObject@@QEAA@AEBV0@@Z>
extern __imp_??1CComPlusComponent@@UEAA@XZ:PANYARGS
??1CComPlusComponent@@UEAA@XZ TEXTEQU <__imp_??1CComPlusComponent@@UEAA@XZ>
extern __imp_??1CComPlusInterface@@UEAA@XZ:PANYARGS
??1CComPlusInterface@@UEAA@XZ TEXTEQU <__imp_??1CComPlusInterface@@UEAA@XZ>
extern __imp_??4CComPlusComponent@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CComPlusComponent@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CComPlusComponent@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CComPlusInterface@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CComPlusInterface@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CComPlusInterface@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CComPlusMethod@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CComPlusMethod@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CComPlusMethod@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CComPlusObject@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CComPlusObject@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CComPlusObject@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CComPlusTypelib@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CComPlusTypelib@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CComPlusTypelib@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_7CComPlusComponent@@6B@:PANYARGS
??_7CComPlusComponent@@6B@ TEXTEQU <__imp_??_7CComPlusComponent@@6B@>
extern __imp_??_7CComPlusInterface@@6B@:PANYARGS
??_7CComPlusInterface@@6B@ TEXTEQU <__imp_??_7CComPlusInterface@@6B@>
extern __imp_??_7CComPlusMethod@@6B@:PANYARGS
??_7CComPlusMethod@@6B@ TEXTEQU <__imp_??_7CComPlusMethod@@6B@>
extern __imp_??_7CComPlusObject@@6B@:PANYARGS
??_7CComPlusObject@@6B@ TEXTEQU <__imp_??_7CComPlusObject@@6B@>
extern __imp_?GetITypeLib@CComPlusTypelib@@QEAAPEAUITypeLib@@XZ:PANYARGS
?GetITypeLib@CComPlusTypelib@@QEAAPEAUITypeLib@@XZ TEXTEQU <__imp_?GetITypeLib@CComPlusTypelib@@QEAAPEAUITypeLib@@XZ>
extern __imp_RegDBBackup:PANYARGS
RegDBBackup TEXTEQU <__imp_RegDBBackup>
extern __imp_RegDBRestore:PANYARGS
RegDBRestore TEXTEQU <__imp_RegDBRestore>
extern __imp_StartMTSTOCOM:PANYARGS
StartMTSTOCOM TEXTEQU <__imp_StartMTSTOCOM>
extern __imp_WinlogonHandlePendingInfOperations:PANYARGS
WinlogonHandlePendingInfOperations TEXTEQU <__imp_WinlogonHandlePendingInfOperations>
extern __imp_CGMIsAdministrator:PANYARGS
CGMIsAdministrator TEXTEQU <__imp_CGMIsAdministrator>
extern __imp_COMPlusUninstallActionW:PANYARGS
COMPlusUninstallActionW TEXTEQU <__imp_COMPlusUninstallActionW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_FindAssemblyModulesW:PANYARGS
FindAssemblyModulesW TEXTEQU <__imp_FindAssemblyModulesW>
extern __imp_ManagedRequestW:PANYARGS
ManagedRequestW TEXTEQU <__imp_ManagedRequestW>
extern __imp_QueryUserDllW:PANYARGS
QueryUserDllW TEXTEQU <__imp_QueryUserDllW>
extern __imp_RunMTSToCom:PANYARGS
RunMTSToCom TEXTEQU <__imp_RunMTSToCom>
extern __imp_SysprepComplus:PANYARGS
SysprepComplus TEXTEQU <__imp_SysprepComplus>
extern __imp_SysprepComplus2:PANYARGS
SysprepComplus2 TEXTEQU <__imp_SysprepComplus2>
