extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_OpenChannel:PANYARGS
OpenChannel TEXTEQU <__imp_OpenChannel>
extern __imp_ParseDesktopComponent:PANYARGS
ParseDesktopComponent TEXTEQU <__imp_ParseDesktopComponent>
extern __imp_Subscribe:PANYARGS
Subscribe TEXTEQU <__imp_Subscribe>
extern __imp_SubscribeToCDF:PANYARGS
SubscribeToCDF TEXTEQU <__imp_SubscribeToCDF>
