extern __imp_CancelCDMOperation:PANYARGS
CancelCDMOperation TEXTEQU <__imp_CancelCDMOperation>
extern __imp_CloseCDMContext:PANYARGS
CloseCDMContext TEXTEQU <__imp_CloseCDMContext>
extern __imp_DetFilesDownloaded:PANYARGS
DetFilesDownloaded TEXTEQU <__imp_DetFilesDownloaded>
extern __imp_DownloadIsInternetAvailable:PANYARGS
DownloadIsInternetAvailable TEXTEQU <__imp_DownloadIsInternetAvailable>
extern __imp_DownloadUpdatedFiles:PANYARGS
DownloadUpdatedFiles TEXTEQU <__imp_DownloadUpdatedFiles>
extern __imp_FindMatchingDriver:PANYARGS
FindMatchingDriver TEXTEQU <__imp_FindMatchingDriver>
extern __imp_LogDriverNotFound:PANYARGS
LogDriverNotFound TEXTEQU <__imp_LogDriverNotFound>
extern __imp_OpenCDMContext:PANYARGS
OpenCDMContext TEXTEQU <__imp_OpenCDMContext>
extern __imp_OpenCDMContextEx:PANYARGS
OpenCDMContextEx TEXTEQU <__imp_OpenCDMContextEx>
extern __imp_QueryDetectionFiles:PANYARGS
QueryDetectionFiles TEXTEQU <__imp_QueryDetectionFiles>
