extern __imp_certcli_ordinal201:PANYARGS
certcli_ordinal201 TEXTEQU <__imp_certcli_ordinal201>
extern __imp_certcli_ordinal202:PANYARGS
certcli_ordinal202 TEXTEQU <__imp_certcli_ordinal202>
extern __imp_certcli_ordinal203:PANYARGS
certcli_ordinal203 TEXTEQU <__imp_certcli_ordinal203>
extern __imp_certcli_ordinal204:PANYARGS
certcli_ordinal204 TEXTEQU <__imp_certcli_ordinal204>
extern __imp_certcli_ordinal205:PANYARGS
certcli_ordinal205 TEXTEQU <__imp_certcli_ordinal205>
extern __imp_certcli_ordinal206:PANYARGS
certcli_ordinal206 TEXTEQU <__imp_certcli_ordinal206>
extern __imp_certcli_ordinal207:PANYARGS
certcli_ordinal207 TEXTEQU <__imp_certcli_ordinal207>
extern __imp_certcli_ordinal208:PANYARGS
certcli_ordinal208 TEXTEQU <__imp_certcli_ordinal208>
extern __imp_certcli_ordinal209:PANYARGS
certcli_ordinal209 TEXTEQU <__imp_certcli_ordinal209>
extern __imp_certcli_ordinal210:PANYARGS
certcli_ordinal210 TEXTEQU <__imp_certcli_ordinal210>
extern __imp_certcli_ordinal211:PANYARGS
certcli_ordinal211 TEXTEQU <__imp_certcli_ordinal211>
extern __imp_certcli_ordinal212:PANYARGS
certcli_ordinal212 TEXTEQU <__imp_certcli_ordinal212>
extern __imp_certcli_ordinal213:PANYARGS
certcli_ordinal213 TEXTEQU <__imp_certcli_ordinal213>
extern __imp_certcli_ordinal214:PANYARGS
certcli_ordinal214 TEXTEQU <__imp_certcli_ordinal214>
extern __imp_certcli_ordinal215:PANYARGS
certcli_ordinal215 TEXTEQU <__imp_certcli_ordinal215>
extern __imp_certcli_ordinal216:PANYARGS
certcli_ordinal216 TEXTEQU <__imp_certcli_ordinal216>
extern __imp_certcli_ordinal217:PANYARGS
certcli_ordinal217 TEXTEQU <__imp_certcli_ordinal217>
extern __imp_certcli_ordinal218:PANYARGS
certcli_ordinal218 TEXTEQU <__imp_certcli_ordinal218>
extern __imp_certcli_ordinal219:PANYARGS
certcli_ordinal219 TEXTEQU <__imp_certcli_ordinal219>
extern __imp_certcli_ordinal220:PANYARGS
certcli_ordinal220 TEXTEQU <__imp_certcli_ordinal220>
extern __imp_certcli_ordinal221:PANYARGS
certcli_ordinal221 TEXTEQU <__imp_certcli_ordinal221>
extern __imp_certcli_ordinal222:PANYARGS
certcli_ordinal222 TEXTEQU <__imp_certcli_ordinal222>
extern __imp_certcli_ordinal223:PANYARGS
certcli_ordinal223 TEXTEQU <__imp_certcli_ordinal223>
extern __imp_certcli_ordinal224:PANYARGS
certcli_ordinal224 TEXTEQU <__imp_certcli_ordinal224>
extern __imp_certcli_ordinal225:PANYARGS
certcli_ordinal225 TEXTEQU <__imp_certcli_ordinal225>
extern __imp_certcli_ordinal226:PANYARGS
certcli_ordinal226 TEXTEQU <__imp_certcli_ordinal226>
extern __imp_certcli_ordinal227:PANYARGS
certcli_ordinal227 TEXTEQU <__imp_certcli_ordinal227>
extern __imp_certcli_ordinal228:PANYARGS
certcli_ordinal228 TEXTEQU <__imp_certcli_ordinal228>
extern __imp_certcli_ordinal229:PANYARGS
certcli_ordinal229 TEXTEQU <__imp_certcli_ordinal229>
extern __imp_certcli_ordinal230:PANYARGS
certcli_ordinal230 TEXTEQU <__imp_certcli_ordinal230>
extern __imp_certcli_ordinal231:PANYARGS
certcli_ordinal231 TEXTEQU <__imp_certcli_ordinal231>
extern __imp_certcli_ordinal232:PANYARGS
certcli_ordinal232 TEXTEQU <__imp_certcli_ordinal232>
extern __imp_certcli_ordinal233:PANYARGS
certcli_ordinal233 TEXTEQU <__imp_certcli_ordinal233>
extern __imp_certcli_ordinal234:PANYARGS
certcli_ordinal234 TEXTEQU <__imp_certcli_ordinal234>
extern __imp_certcli_ordinal235:PANYARGS
certcli_ordinal235 TEXTEQU <__imp_certcli_ordinal235>
extern __imp_certcli_ordinal236:PANYARGS
certcli_ordinal236 TEXTEQU <__imp_certcli_ordinal236>
extern __imp_certcli_ordinal237:PANYARGS
certcli_ordinal237 TEXTEQU <__imp_certcli_ordinal237>
extern __imp_certcli_ordinal238:PANYARGS
certcli_ordinal238 TEXTEQU <__imp_certcli_ordinal238>
extern __imp_certcli_ordinal239:PANYARGS
certcli_ordinal239 TEXTEQU <__imp_certcli_ordinal239>
extern __imp_certcli_ordinal240:PANYARGS
certcli_ordinal240 TEXTEQU <__imp_certcli_ordinal240>
extern __imp_certcli_ordinal241:PANYARGS
certcli_ordinal241 TEXTEQU <__imp_certcli_ordinal241>
extern __imp_certcli_ordinal242:PANYARGS
certcli_ordinal242 TEXTEQU <__imp_certcli_ordinal242>
extern __imp_certcli_ordinal243:PANYARGS
certcli_ordinal243 TEXTEQU <__imp_certcli_ordinal243>
extern __imp_certcli_ordinal244:PANYARGS
certcli_ordinal244 TEXTEQU <__imp_certcli_ordinal244>
extern __imp_certcli_ordinal245:PANYARGS
certcli_ordinal245 TEXTEQU <__imp_certcli_ordinal245>
extern __imp_certcli_ordinal246:PANYARGS
certcli_ordinal246 TEXTEQU <__imp_certcli_ordinal246>
extern __imp_certcli_ordinal247:PANYARGS
certcli_ordinal247 TEXTEQU <__imp_certcli_ordinal247>
extern __imp_certcli_ordinal248:PANYARGS
certcli_ordinal248 TEXTEQU <__imp_certcli_ordinal248>
extern __imp_certcli_ordinal249:PANYARGS
certcli_ordinal249 TEXTEQU <__imp_certcli_ordinal249>
extern __imp_certcli_ordinal250:PANYARGS
certcli_ordinal250 TEXTEQU <__imp_certcli_ordinal250>
extern __imp_certcli_ordinal251:PANYARGS
certcli_ordinal251 TEXTEQU <__imp_certcli_ordinal251>
extern __imp_certcli_ordinal252:PANYARGS
certcli_ordinal252 TEXTEQU <__imp_certcli_ordinal252>
extern __imp_certcli_ordinal253:PANYARGS
certcli_ordinal253 TEXTEQU <__imp_certcli_ordinal253>
extern __imp_certcli_ordinal254:PANYARGS
certcli_ordinal254 TEXTEQU <__imp_certcli_ordinal254>
extern __imp_certcli_ordinal255:PANYARGS
certcli_ordinal255 TEXTEQU <__imp_certcli_ordinal255>
extern __imp_certcli_ordinal256:PANYARGS
certcli_ordinal256 TEXTEQU <__imp_certcli_ordinal256>
extern __imp_certcli_ordinal257:PANYARGS
certcli_ordinal257 TEXTEQU <__imp_certcli_ordinal257>
extern __imp_certcli_ordinal258:PANYARGS
certcli_ordinal258 TEXTEQU <__imp_certcli_ordinal258>
extern __imp_certcli_ordinal259:PANYARGS
certcli_ordinal259 TEXTEQU <__imp_certcli_ordinal259>
extern __imp_certcli_ordinal260:PANYARGS
certcli_ordinal260 TEXTEQU <__imp_certcli_ordinal260>
extern __imp_certcli_ordinal261:PANYARGS
certcli_ordinal261 TEXTEQU <__imp_certcli_ordinal261>
extern __imp_certcli_ordinal262:PANYARGS
certcli_ordinal262 TEXTEQU <__imp_certcli_ordinal262>
extern __imp_certcli_ordinal263:PANYARGS
certcli_ordinal263 TEXTEQU <__imp_certcli_ordinal263>
extern __imp_certcli_ordinal264:PANYARGS
certcli_ordinal264 TEXTEQU <__imp_certcli_ordinal264>
extern __imp_certcli_ordinal265:PANYARGS
certcli_ordinal265 TEXTEQU <__imp_certcli_ordinal265>
extern __imp_certcli_ordinal266:PANYARGS
certcli_ordinal266 TEXTEQU <__imp_certcli_ordinal266>
extern __imp_certcli_ordinal267:PANYARGS
certcli_ordinal267 TEXTEQU <__imp_certcli_ordinal267>
extern __imp_CAAccessCheck:PANYARGS
CAAccessCheck TEXTEQU <__imp_CAAccessCheck>
extern __imp_CAAccessCheckEx:PANYARGS
CAAccessCheckEx TEXTEQU <__imp_CAAccessCheckEx>
extern __imp_CAAddCACertificateType:PANYARGS
CAAddCACertificateType TEXTEQU <__imp_CAAddCACertificateType>
extern __imp_CACertTypeAccessCheck:PANYARGS
CACertTypeAccessCheck TEXTEQU <__imp_CACertTypeAccessCheck>
extern __imp_CACertTypeAccessCheckEx:PANYARGS
CACertTypeAccessCheckEx TEXTEQU <__imp_CACertTypeAccessCheckEx>
extern __imp_CACertTypeGetSecurity:PANYARGS
CACertTypeGetSecurity TEXTEQU <__imp_CACertTypeGetSecurity>
extern __imp_CACertTypeQuery:PANYARGS
CACertTypeQuery TEXTEQU <__imp_CACertTypeQuery>
extern __imp_CACertTypeRegisterQuery:PANYARGS
CACertTypeRegisterQuery TEXTEQU <__imp_CACertTypeRegisterQuery>
extern __imp_CACertTypeSetSecurity:PANYARGS
CACertTypeSetSecurity TEXTEQU <__imp_CACertTypeSetSecurity>
extern __imp_CACertTypeUnregisterQuery:PANYARGS
CACertTypeUnregisterQuery TEXTEQU <__imp_CACertTypeUnregisterQuery>
extern __imp_CACloneCertType:PANYARGS
CACloneCertType TEXTEQU <__imp_CACloneCertType>
extern __imp_CACloseCA:PANYARGS
CACloseC  TEXTEQU <__imp_CACloseCA>
extern __imp_CACloseCertType:PANYARGS
CACloseCertType TEXTEQU <__imp_CACloseCertType>
extern __imp_CACountCAs:PANYARGS
CACountCAs TEXTEQU <__imp_CACountCAs>
extern __imp_CACountCertTypes:PANYARGS
CACountCertTypes TEXTEQU <__imp_CACountCertTypes>
extern __imp_CACreateAutoEnrollmentObjectEx:PANYARGS
CACreateAutoEnrollmentObjectEx TEXTEQU <__imp_CACreateAutoEnrollmentObjectEx>
extern __imp_CACreateCertType:PANYARGS
CACreateCertType TEXTEQU <__imp_CACreateCertType>
extern __imp_CACreateLocalAutoEnrollmentObject:PANYARGS
CACreateLocalAutoEnrollmentObject TEXTEQU <__imp_CACreateLocalAutoEnrollmentObject>
extern __imp_CACreateNewCA:PANYARGS
CACreateNewC  TEXTEQU <__imp_CACreateNewCA>
extern __imp_CADeleteCA:PANYARGS
CADeleteC  TEXTEQU <__imp_CADeleteCA>
extern __imp_CADeleteCertType:PANYARGS
CADeleteCertType TEXTEQU <__imp_CADeleteCertType>
extern __imp_CADeleteLocalAutoEnrollmentObject:PANYARGS
CADeleteLocalAutoEnrollmentObject TEXTEQU <__imp_CADeleteLocalAutoEnrollmentObject>
extern __imp_CAEnumCertTypes:PANYARGS
CAEnumCertTypes TEXTEQU <__imp_CAEnumCertTypes>
extern __imp_CAEnumCertTypesEx:PANYARGS
CAEnumCertTypesEx TEXTEQU <__imp_CAEnumCertTypesEx>
extern __imp_CAEnumCertTypesForCA:PANYARGS
CAEnumCertTypesForC  TEXTEQU <__imp_CAEnumCertTypesForCA>
extern __imp_CAEnumCertTypesForCAEx:PANYARGS
CAEnumCertTypesForCAEx TEXTEQU <__imp_CAEnumCertTypesForCAEx>
extern __imp_CAEnumFirstCA:PANYARGS
CAEnumFirstC  TEXTEQU <__imp_CAEnumFirstCA>
extern __imp_CAEnumNextCA:PANYARGS
CAEnumNextC  TEXTEQU <__imp_CAEnumNextCA>
extern __imp_CAEnumNextCertType:PANYARGS
CAEnumNextCertType TEXTEQU <__imp_CAEnumNextCertType>
extern __imp_CAFindByCertType:PANYARGS
CAFindByCertType TEXTEQU <__imp_CAFindByCertType>
extern __imp_CAFindByIssuerDN:PANYARGS
CAFindByIssuerDN TEXTEQU <__imp_CAFindByIssuerDN>
extern __imp_CAFindByName:PANYARGS
CAFindByName TEXTEQU <__imp_CAFindByName>
extern __imp_CAFindCertTypeByName:PANYARGS
CAFindCertTypeByName TEXTEQU <__imp_CAFindCertTypeByName>
extern __imp_CAFreeCAProperty:PANYARGS
CAFreeCAProperty TEXTEQU <__imp_CAFreeCAProperty>
extern __imp_CAFreeCertTypeExtensions:PANYARGS
CAFreeCertTypeExtensions TEXTEQU <__imp_CAFreeCertTypeExtensions>
extern __imp_CAFreeCertTypeProperty:PANYARGS
CAFreeCertTypeProperty TEXTEQU <__imp_CAFreeCertTypeProperty>
extern __imp_CAGetCACertificate:PANYARGS
CAGetCACertificate TEXTEQU <__imp_CAGetCACertificate>
extern __imp_CAGetCAExpiration:PANYARGS
CAGetCAExpiration TEXTEQU <__imp_CAGetCAExpiration>
extern __imp_CAGetCAFlags:PANYARGS
CAGetCAFlags TEXTEQU <__imp_CAGetCAFlags>
extern __imp_CAGetCAProperty:PANYARGS
CAGetCAProperty TEXTEQU <__imp_CAGetCAProperty>
extern __imp_CAGetCASecurity:PANYARGS
CAGetCASecurity TEXTEQU <__imp_CAGetCASecurity>
extern __imp_CAGetCertTypeExpiration:PANYARGS
CAGetCertTypeExpiration TEXTEQU <__imp_CAGetCertTypeExpiration>
extern __imp_CAGetCertTypeExtensions:PANYARGS
CAGetCertTypeExtensions TEXTEQU <__imp_CAGetCertTypeExtensions>
extern __imp_CAGetCertTypeExtensionsEx:PANYARGS
CAGetCertTypeExtensionsEx TEXTEQU <__imp_CAGetCertTypeExtensionsEx>
extern __imp_CAGetCertTypeFlags:PANYARGS
CAGetCertTypeFlags TEXTEQU <__imp_CAGetCertTypeFlags>
extern __imp_CAGetCertTypeFlagsEx:PANYARGS
CAGetCertTypeFlagsEx TEXTEQU <__imp_CAGetCertTypeFlagsEx>
extern __imp_CAGetCertTypeKeySpec:PANYARGS
CAGetCertTypeKeySpec TEXTEQU <__imp_CAGetCertTypeKeySpec>
extern __imp_CAGetCertTypeProperty:PANYARGS
CAGetCertTypeProperty TEXTEQU <__imp_CAGetCertTypeProperty>
extern __imp_CAGetCertTypePropertyEx:PANYARGS
CAGetCertTypePropertyEx TEXTEQU <__imp_CAGetCertTypePropertyEx>
extern __imp_CAGetDN:PANYARGS
CAGetDN TEXTEQU <__imp_CAGetDN>
extern __imp_CAInstallDefaultCertType:PANYARGS
CAInstallDefaultCertType TEXTEQU <__imp_CAInstallDefaultCertType>
extern __imp_CAIsCertTypeCurrent:PANYARGS
CAIsCertTypeCurrent TEXTEQU <__imp_CAIsCertTypeCurrent>
extern __imp_CAOIDAdd:PANYARGS
CAOIDAdd TEXTEQU <__imp_CAOIDAdd>
extern __imp_CAOIDCreateNew:PANYARGS
CAOIDCreateNew TEXTEQU <__imp_CAOIDCreateNew>
extern __imp_CAOIDDelete:PANYARGS
CAOIDDelete TEXTEQU <__imp_CAOIDDelete>
extern __imp_CAOIDFreeLdapURL:PANYARGS
CAOIDFreeLdapURL TEXTEQU <__imp_CAOIDFreeLdapURL>
extern __imp_CAOIDFreeProperty:PANYARGS
CAOIDFreeProperty TEXTEQU <__imp_CAOIDFreeProperty>
extern __imp_CAOIDGetLdapURL:PANYARGS
CAOIDGetLdapURL TEXTEQU <__imp_CAOIDGetLdapURL>
extern __imp_CAOIDGetProperty:PANYARGS
CAOIDGetProperty TEXTEQU <__imp_CAOIDGetProperty>
extern __imp_CAOIDSetProperty:PANYARGS
CAOIDSetProperty TEXTEQU <__imp_CAOIDSetProperty>
extern __imp_CARemoveCACertificateType:PANYARGS
CARemoveCACertificateType TEXTEQU <__imp_CARemoveCACertificateType>
extern __imp_CASetCACertificate:PANYARGS
CASetCACertificate TEXTEQU <__imp_CASetCACertificate>
extern __imp_CASetCAExpiration:PANYARGS
CASetCAExpiration TEXTEQU <__imp_CASetCAExpiration>
extern __imp_CASetCAFlags:PANYARGS
CASetCAFlags TEXTEQU <__imp_CASetCAFlags>
extern __imp_CASetCAProperty:PANYARGS
CASetCAProperty TEXTEQU <__imp_CASetCAProperty>
extern __imp_CASetCASecurity:PANYARGS
CASetCASecurity TEXTEQU <__imp_CASetCASecurity>
extern __imp_CASetCertTypeExpiration:PANYARGS
CASetCertTypeExpiration TEXTEQU <__imp_CASetCertTypeExpiration>
extern __imp_CASetCertTypeExtension:PANYARGS
CASetCertTypeExtension TEXTEQU <__imp_CASetCertTypeExtension>
extern __imp_CASetCertTypeFlags:PANYARGS
CASetCertTypeFlags TEXTEQU <__imp_CASetCertTypeFlags>
extern __imp_CASetCertTypeFlagsEx:PANYARGS
CASetCertTypeFlagsEx TEXTEQU <__imp_CASetCertTypeFlagsEx>
extern __imp_CASetCertTypeKeySpec:PANYARGS
CASetCertTypeKeySpec TEXTEQU <__imp_CASetCertTypeKeySpec>
extern __imp_CASetCertTypeProperty:PANYARGS
CASetCertTypeProperty TEXTEQU <__imp_CASetCertTypeProperty>
extern __imp_CASetCertTypePropertyEx:PANYARGS
CASetCertTypePropertyEx TEXTEQU <__imp_CASetCertTypePropertyEx>
extern __imp_CAUpdateCA:PANYARGS
CAUpdateC  TEXTEQU <__imp_CAUpdateCA>
extern __imp_CAUpdateCertType:PANYARGS
CAUpdateCertType TEXTEQU <__imp_CAUpdateCertType>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetProxyDllInfo:PANYARGS
GetProxyDllInfo TEXTEQU <__imp_GetProxyDllInfo>
