extern __imp_CLSID_CfgComp:PANYARGS
CLSID_CfgComp TEXTEQU <__imp_CLSID_CfgComp>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_IID_ICfgComp:PANYARGS
IID_ICfgComp TEXTEQU <__imp_IID_ICfgComp>
extern __imp_IID_ISettingsComp:PANYARGS
IID_ISettingsComp TEXTEQU <__imp_IID_ISettingsComp>
extern __imp_IID_ISettingsComp2:PANYARGS
IID_ISettingsComp2 TEXTEQU <__imp_IID_ISettingsComp2>
