extern __imp_ClbAddData:PANYARGS
ClbAddData TEXTEQU <__imp_ClbAddData>
extern __imp_ClbSetColumnWidths:PANYARGS
ClbSetColumnWidths TEXTEQU <__imp_ClbSetColumnWidths>
extern __imp_ClbStyleW:PANYARGS
ClbStyleW TEXTEQU <__imp_ClbStyleW>
extern __imp_ClbWndProc:PANYARGS
ClbWndProc TEXTEQU <__imp_ClbWndProc>
extern __imp_CustomControlInfoW:PANYARGS
CustomControlInfoW TEXTEQU <__imp_CustomControlInfoW>
