extern __imp_ActivatorUpdateForIsRouterChanges:PANYARGS
ActivatorUpdateForIsRouterChanges TEXTEQU <__imp_ActivatorUpdateForIsRouterChanges>
extern __imp_?ClearList@@YAXPEAVCStructArray@@@Z:PANYARGS
?ClearList@@YAXPEAVCStructArray@@@Z TEXTEQU <__imp_?ClearList@@YAXPEAVCStructArray@@@Z>
extern __imp_CoRegCleanup:PANYARGS
CoRegCleanup TEXTEQU <__imp_CoRegCleanup>
extern __imp_?CreateComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z:PANYARGS
?CreateComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z TEXTEQU <__imp_?CreateComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z>
extern __imp_?DataConvert@@YAJGGKPEAKPEAX1KK0EEK@Z:PANYARGS
?DataConvert@@YAJGGKPEAKPEAX1KK0EEK@Z TEXTEQU <__imp_?DataConvert@@YAJGGKPEAKPEAX1KK0EEK@Z>
extern __imp_DeleteAllActivatorsForClsid:PANYARGS
DeleteAllActivatorsForClsid TEXTEQU <__imp_DeleteAllActivatorsForClsid>
extern __imp_?DestroyStgDatabase@@YAXPEAVStgDatabase@@@Z:PANYARGS
?DestroyStgDatabase@@YAXPEAVStgDatabase@@@Z TEXTEQU <__imp_?DestroyStgDatabase@@YAXPEAVStgDatabase@@@Z>
extern __imp_DowngradeAPL:PANYARGS
DowngradeAPL TEXTEQU <__imp_DowngradeAPL>
extern __imp_?GetDataConversion@@YAJPEAPEAUIDataConvert@@@Z:PANYARGS
?GetDataConversion@@YAJPEAPEAUIDataConvert@@@Z TEXTEQU <__imp_?GetDataConversion@@YAJPEAPEAUIDataConvert@@@Z>
extern __imp_?GetDataConvertObject@@YAPEAVCGetDataConversion@@XZ:PANYARGS
?GetDataConvertObject@@YAPEAVCGetDataConversion@@XZ TEXTEQU <__imp_?GetDataConvertObject@@YAPEAVCGetDataConversion@@XZ>
extern __imp_GetGlobalBabyJITEnabled:PANYARGS
GetGlobalBabyJITEnabled TEXTEQU <__imp_GetGlobalBabyJITEnabled>
extern __imp_?GetPropValue@@YAJGPEAJPEAXHPEAHAEAUtagDBPROP@@@Z:PANYARGS
?GetPropValue@@YAJGPEAJPEAXHPEAHAEAUtagDBPROP@@@Z TEXTEQU <__imp_?GetPropValue@@YAJGPEAJPEAXHPEAHAEAUtagDBPROP@@@Z>
extern __imp_?GetStgDatabase@@YAJPEAPEAVStgDatabase@@@Z:PANYARGS
?GetStgDatabase@@YAJPEAPEAVStgDatabase@@@Z TEXTEQU <__imp_?GetStgDatabase@@YAJPEAPEAVStgDatabase@@@Z>
extern __imp_?InitErrors@@YAXPEAK@Z:PANYARGS
?InitErrors@@YAXPEAK@Z TEXTEQU <__imp_?InitErrors@@YAXPEAK@Z>
extern __imp_?OpenComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z:PANYARGS
?OpenComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z TEXTEQU <__imp_?OpenComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z>
extern __imp_?PostError@@YAJJZZ:PANYARGS
?PostError@@YAJJZZ TEXTEQU <__imp_?PostError@@YAJJZZ>
extern __imp_?ShutDownDataConversion@@YAXXZ:PANYARGS
?ShutDownDataConversion@@YAXXZ TEXTEQU <__imp_?ShutDownDataConversion@@YAXXZ>
extern __imp_UpdateFromAppChange:PANYARGS
UpdateFromAppChange TEXTEQU <__imp_UpdateFromAppChange>
extern __imp_UpdateFromComponentChange:PANYARGS
UpdateFromComponentChange TEXTEQU <__imp_UpdateFromComponentChange>
extern __imp_CLSIDFromStringByBitness:PANYARGS
CLSIDFromStringByBitness TEXTEQU <__imp_CLSIDFromStringByBitness>
extern __imp_CheckMemoryGates:PANYARGS
CheckMemoryGates TEXTEQU <__imp_CheckMemoryGates>
extern __imp_ComPlusEnablePartitions:PANYARGS
ComPlusEnablePartitions TEXTEQU <__imp_ComPlusEnablePartitions>
extern __imp_ComPlusEnableRemoteAccess:PANYARGS
ComPlusEnableRemoteAccess TEXTEQU <__imp_ComPlusEnableRemoteAccess>
extern __imp_ComPlusMigrate:PANYARGS
ComPlusMigrate TEXTEQU <__imp_ComPlusMigrate>
extern __imp_ComPlusPartitionsEnabled:PANYARGS
ComPlusPartitionsEnabled TEXTEQU <__imp_ComPlusPartitionsEnabled>
extern __imp_ComPlusRemoteAccessEnabled:PANYARGS
ComPlusRemoteAccessEnabled TEXTEQU <__imp_ComPlusRemoteAccessEnabled>
extern __imp_CreateComponentLibraryEx:PANYARGS
CreateComponentLibraryEx TEXTEQU <__imp_CreateComponentLibraryEx>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetCatalogObject:PANYARGS
GetCatalogObject TEXTEQU <__imp_GetCatalogObject>
extern __imp_GetCatalogObject2:PANYARGS
GetCatalogObject2 TEXTEQU <__imp_GetCatalogObject2>
extern __imp_GetComputerObject:PANYARGS
GetComputerObject TEXTEQU <__imp_GetComputerObject>
extern __imp_GetSimpleTableDispenser:PANYARGS
GetSimpleTableDispenser TEXTEQU <__imp_GetSimpleTableDispenser>
extern __imp_InprocServer32FromString:PANYARGS
InprocServer32FromString TEXTEQU <__imp_InprocServer32FromString>
extern __imp_OpenComponentLibraryEx:PANYARGS
OpenComponentLibraryEx TEXTEQU <__imp_OpenComponentLibraryEx>
extern __imp_OpenComponentLibraryOnMemEx:PANYARGS
OpenComponentLibraryOnMemEx TEXTEQU <__imp_OpenComponentLibraryOnMemEx>
extern __imp_OpenComponentLibraryOnStreamEx:PANYARGS
OpenComponentLibraryOnStreamEx TEXTEQU <__imp_OpenComponentLibraryOnStreamEx>
extern __imp_ServerGetApplicationType:PANYARGS
ServerGetApplicationType TEXTEQU <__imp_ServerGetApplicationType>
extern __imp_SetSetupOpen:PANYARGS
SetSetupOpen TEXTEQU <__imp_SetSetupOpen>
extern __imp_SetSetupSave:PANYARGS
SetSetupSave TEXTEQU <__imp_SetSetupSave>
extern __imp_SetupOpen:PANYARGS
SetupOpen TEXTEQU <__imp_SetupOpen>
extern __imp_SetupSave:PANYARGS
SetupSave TEXTEQU <__imp_SetupSave>
