extern __imp_AutoDialFunc:PANYARGS
AutoDialFunc TEXTEQU <__imp_AutoDialFunc>
extern __imp_CmCustomDialDlg:PANYARGS
CmCustomDialDlg TEXTEQU <__imp_CmCustomDialDlg>
extern __imp_CmCustomHangUp:PANYARGS
CmCustomHangUp TEXTEQU <__imp_CmCustomHangUp>
extern __imp_CmReConnect:PANYARGS
CmReConnect TEXTEQU <__imp_CmReConnect>
extern __imp_GetCustomProperty:PANYARGS
GetCustomProperty TEXTEQU <__imp_GetCustomProperty>
extern __imp_InetDialHandler:PANYARGS
InetDialHandler TEXTEQU <__imp_InetDialHandler>
extern __imp_RasCustomDeleteEntryNotify:PANYARGS
RasCustomDeleteEntryNotify TEXTEQU <__imp_RasCustomDeleteEntryNotify>
extern __imp_RasCustomDial:PANYARGS
RasCustomDial TEXTEQU <__imp_RasCustomDial>
extern __imp_RasCustomDialDlg:PANYARGS
RasCustomDialDlg TEXTEQU <__imp_RasCustomDialDlg>
extern __imp_RasCustomEntryDlg:PANYARGS
RasCustomEntryDlg TEXTEQU <__imp_RasCustomEntryDlg>
extern __imp_RasCustomHangUp:PANYARGS
RasCustomHangUp TEXTEQU <__imp_RasCustomHangUp>
