extern __imp_??0CIniA@@QEAA@PEAUHINSTANCE__@@PEBD111@Z:PANYARGS
??0CIniA@@QEAA@PEAUHINSTANCE__@@PEBD111@Z TEXTEQU <__imp_??0CIniA@@QEAA@PEAUHINSTANCE__@@PEBD111@Z>
extern __imp_??0CIniW@@QEAA@PEAUHINSTANCE__@@PEBG111@Z:PANYARGS
??0CIniW@@QEAA@PEAUHINSTANCE__@@PEBG111@Z TEXTEQU <__imp_??0CIniW@@QEAA@PEAUHINSTANCE__@@PEBG111@Z>
extern __imp_??0CRandom@@QEAA@I@Z:PANYARGS
??0CRandom@@QEAA@I@Z TEXTEQU <__imp_??0CRandom@@QEAA@I@Z>
extern __imp_??0CRandom@@QEAA@XZ:PANYARGS
??0CRandom@@QEAA@XZ TEXTEQU <__imp_??0CRandom@@QEAA@XZ>
extern __imp_??0CmLogFile@@QEAA@XZ:PANYARGS
??0CmLogFile@@QEAA@XZ TEXTEQU <__imp_??0CmLogFile@@QEAA@XZ>
extern __imp_??1CIniA@@QEAA@XZ:PANYARGS
??1CIniA@@QEAA@XZ TEXTEQU <__imp_??1CIniA@@QEAA@XZ>
extern __imp_??1CIniW@@QEAA@XZ:PANYARGS
??1CIniW@@QEAA@XZ TEXTEQU <__imp_??1CIniW@@QEAA@XZ>
extern __imp_??1CmLogFile@@QEAA@XZ:PANYARGS
??1CmLogFile@@QEAA@XZ TEXTEQU <__imp_??1CmLogFile@@QEAA@XZ>
extern __imp_??4CIniA@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CIniA@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CIniA@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CIniW@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CIniW@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CIniW@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CRandom@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CRandom@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CRandom@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CmLogFile@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CmLogFile@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CmLogFile@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_FCIniA@@QEAAXXZ:PANYARGS
??_FCIniA@@QEAAXXZ TEXTEQU <__imp_??_FCIniA@@QEAAXXZ>
extern __imp_??_FCIniW@@QEAAXXZ:PANYARGS
??_FCIniW@@QEAAXXZ TEXTEQU <__imp_??_FCIniW@@QEAAXXZ>
extern __imp_?Banner@CmLogFile@@QEAAXXZ:PANYARGS
?Banner@CmLogFile@@QEAAXXZ TEXTEQU <__imp_?Banner@CmLogFile@@QEAAXXZ>
extern __imp_?CIniA_DeleteEntryFromReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1@Z:PANYARGS
?CIniA_DeleteEntryFromReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1@Z TEXTEQU <__imp_?CIniA_DeleteEntryFromReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1@Z>
extern __imp_?CIniA_GetEntryFromReg@CIniA@@IEBAPEAEPEAUHKEY__@@PEBD1KK@Z:PANYARGS
?CIniA_GetEntryFromReg@CIniA@@IEBAPEAEPEAUHKEY__@@PEBD1KK@Z TEXTEQU <__imp_?CIniA_GetEntryFromReg@CIniA@@IEBAPEAEPEAUHKEY__@@PEBD1KK@Z>
extern __imp_?CIniA_WriteEntryToReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1PEBEKK@Z:PANYARGS
?CIniA_WriteEntryToReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1PEBEKK@Z TEXTEQU <__imp_?CIniA_WriteEntryToReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1PEBEKK@Z>
extern __imp_?CIniW_DeleteEntryFromReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1@Z:PANYARGS
?CIniW_DeleteEntryFromReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1@Z TEXTEQU <__imp_?CIniW_DeleteEntryFromReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1@Z>
extern __imp_?CIniW_GetEntryFromReg@CIniW@@IEBAPEAEPEAUHKEY__@@PEBG1KK@Z:PANYARGS
?CIniW_GetEntryFromReg@CIniW@@IEBAPEAEPEAUHKEY__@@PEBG1KK@Z TEXTEQU <__imp_?CIniW_GetEntryFromReg@CIniW@@IEBAPEAEPEAUHKEY__@@PEBG1KK@Z>
extern __imp_?CIniW_WriteEntryToReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1PEBEKK@Z:PANYARGS
?CIniW_WriteEntryToReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1PEBEKK@Z TEXTEQU <__imp_?CIniW_WriteEntryToReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1PEBEKK@Z>
extern __imp_?CIni_SetFile@CIniA@@KAXPEAPEADPEBD@Z:PANYARGS
?CIni_SetFile@CIniA@@KAXPEAPEADPEBD@Z TEXTEQU <__imp_?CIni_SetFile@CIniA@@KAXPEAPEADPEBD@Z>
extern __imp_?CIni_SetFile@CIniW@@KAXPEAPEAGPEBG@Z:PANYARGS
?CIni_SetFile@CIniW@@KAXPEAPEAGPEBG@Z TEXTEQU <__imp_?CIni_SetFile@CIniW@@KAXPEAPEAGPEBG@Z>
extern __imp_?Clear@CIniA@@QEAAXXZ:PANYARGS
?Clear@CIniA@@QEAAXXZ TEXTEQU <__imp_?Clear@CIniA@@QEAAXXZ>
extern __imp_?Clear@CIniW@@QEAAXXZ:PANYARGS
?Clear@CIniW@@QEAAXXZ TEXTEQU <__imp_?Clear@CIniW@@QEAAXXZ>
extern __imp_?Clear@CmLogFile@@QEAAXH@Z:PANYARGS
?Clear@CmLogFile@@QEAAXH@Z TEXTEQU <__imp_?Clear@CmLogFile@@QEAAXH@Z>
extern __imp_?CloseFile@CmLogFile@@AEAAJXZ:PANYARGS
?CloseFile@CmLogFile@@AEAAJXZ TEXTEQU <__imp_?CloseFile@CmLogFile@@AEAAJXZ>
extern __imp_CmAtolA:PANYARGS
CmAtol  TEXTEQU <__imp_CmAtolA>
extern __imp_CmAtolW:PANYARGS
CmAtolW TEXTEQU <__imp_CmAtolW>
extern __imp_CmBuildFullPathFromRelativeA:PANYARGS
CmBuildFullPathFromRelative  TEXTEQU <__imp_CmBuildFullPathFromRelativeA>
extern __imp_CmBuildFullPathFromRelativeW:PANYARGS
CmBuildFullPathFromRelativeW TEXTEQU <__imp_CmBuildFullPathFromRelativeW>
extern __imp_CmCompareStringA:PANYARGS
CmCompareString  TEXTEQU <__imp_CmCompareStringA>
extern __imp_CmCompareStringW:PANYARGS
CmCompareStringW TEXTEQU <__imp_CmCompareStringW>
extern __imp_CmConvertRelativePathA:PANYARGS
CmConvertRelativePath  TEXTEQU <__imp_CmConvertRelativePathA>
extern __imp_CmConvertRelativePathW:PANYARGS
CmConvertRelativePathW TEXTEQU <__imp_CmConvertRelativePathW>
extern __imp_CmEndOfStrA:PANYARGS
CmEndOfStr  TEXTEQU <__imp_CmEndOfStrA>
extern __imp_CmEndOfStrW:PANYARGS
CmEndOfStrW TEXTEQU <__imp_CmEndOfStrW>
extern __imp_CmFmtMsgA:PANYARGS
CmFmtMsg  TEXTEQU <__imp_CmFmtMsgA>
extern __imp_CmFmtMsgW:PANYARGS
CmFmtMsgW TEXTEQU <__imp_CmFmtMsgW>
extern __imp_CmFree:PANYARGS
CmFree TEXTEQU <__imp_CmFree>
extern __imp_CmIsDigitA:PANYARGS
CmIsDigit  TEXTEQU <__imp_CmIsDigitA>
extern __imp_CmIsDigitW:PANYARGS
CmIsDigitW TEXTEQU <__imp_CmIsDigitW>
extern __imp_CmIsSpaceA:PANYARGS
CmIsSpace  TEXTEQU <__imp_CmIsSpaceA>
extern __imp_CmIsSpaceW:PANYARGS
CmIsSpaceW TEXTEQU <__imp_CmIsSpaceW>
extern __imp_CmLoadIconA:PANYARGS
CmLoadIcon  TEXTEQU <__imp_CmLoadIconA>
extern __imp_CmLoadIconW:PANYARGS
CmLoadIconW TEXTEQU <__imp_CmLoadIconW>
extern __imp_CmLoadImage:PANYARGS
CmLoadImage TEXTEQU <__imp_CmLoadImage>
extern __imp_CmLoadImageA:PANYARGS
CmLoadImage  TEXTEQU <__imp_CmLoadImageA>
extern __imp_CmLoadImageW:PANYARGS
CmLoadImageW TEXTEQU <__imp_CmLoadImageW>
extern __imp_CmLoadSmallIconA:PANYARGS
CmLoadSmallIcon  TEXTEQU <__imp_CmLoadSmallIconA>
extern __imp_CmLoadSmallIconW:PANYARGS
CmLoadSmallIconW TEXTEQU <__imp_CmLoadSmallIconW>
extern __imp_CmLoadStringA:PANYARGS
CmLoadString  TEXTEQU <__imp_CmLoadStringA>
extern __imp_CmLoadStringW:PANYARGS
CmLoadStringW TEXTEQU <__imp_CmLoadStringW>
extern __imp_CmMalloc:PANYARGS
CmMalloc TEXTEQU <__imp_CmMalloc>
extern __imp_CmParsePathA:PANYARGS
CmParsePath  TEXTEQU <__imp_CmParsePathA>
extern __imp_CmParsePathW:PANYARGS
CmParsePathW TEXTEQU <__imp_CmParsePathW>
extern __imp_CmRealloc:PANYARGS
CmRealloc TEXTEQU <__imp_CmRealloc>
extern __imp_CmStrCatAllocA:PANYARGS
CmStrCatAlloc  TEXTEQU <__imp_CmStrCatAllocA>
extern __imp_CmStrCatAllocW:PANYARGS
CmStrCatAllocW TEXTEQU <__imp_CmStrCatAllocW>
extern __imp_CmStrCpyAllocA:PANYARGS
CmStrCpyAlloc  TEXTEQU <__imp_CmStrCpyAllocA>
extern __imp_CmStrCpyAllocW:PANYARGS
CmStrCpyAllocW TEXTEQU <__imp_CmStrCpyAllocW>
extern __imp_CmStrStrA:PANYARGS
CmStrStr  TEXTEQU <__imp_CmStrStrA>
extern __imp_CmStrStrW:PANYARGS
CmStrStrW TEXTEQU <__imp_CmStrStrW>
extern __imp_CmStrTrimA:PANYARGS
CmStrTrim  TEXTEQU <__imp_CmStrTrimA>
extern __imp_CmStrTrimW:PANYARGS
CmStrTrimW TEXTEQU <__imp_CmStrTrimW>
extern __imp_CmStrchrA:PANYARGS
CmStrchr  TEXTEQU <__imp_CmStrchrA>
extern __imp_CmStrchrW:PANYARGS
CmStrchrW TEXTEQU <__imp_CmStrchrW>
extern __imp_CmStripFileNameA:PANYARGS
CmStripFileName  TEXTEQU <__imp_CmStripFileNameA>
extern __imp_CmStripFileNameW:PANYARGS
CmStripFileNameW TEXTEQU <__imp_CmStripFileNameW>
extern __imp_CmStripPathAndExtA:PANYARGS
CmStripPathAndExt  TEXTEQU <__imp_CmStripPathAndExtA>
extern __imp_CmStripPathAndExtW:PANYARGS
CmStripPathAndExtW TEXTEQU <__imp_CmStripPathAndExtW>
extern __imp_CmStrrchrA:PANYARGS
CmStrrchr  TEXTEQU <__imp_CmStrrchrA>
extern __imp_CmStrrchrW:PANYARGS
CmStrrchrW TEXTEQU <__imp_CmStrrchrW>
extern __imp_CmStrtokA:PANYARGS
CmStrtok  TEXTEQU <__imp_CmStrtokA>
extern __imp_CmStrtokW:PANYARGS
CmStrtokW TEXTEQU <__imp_CmStrtokW>
extern __imp_CmWinHelp:PANYARGS
CmWinHelp TEXTEQU <__imp_CmWinHelp>
extern __imp_?DeInit@CmLogFile@@QEAAJXZ:PANYARGS
?DeInit@CmLogFile@@QEAAJXZ TEXTEQU <__imp_?DeInit@CmLogFile@@QEAAJXZ>
extern __imp_?FormatWrite@CmLogFile@@AEAAXW4_CMLOG_ITEM@@PEAG@Z:PANYARGS
?FormatWrite@CmLogFile@@AEAAXW4_CMLOG_ITEM@@PEAG@Z TEXTEQU <__imp_?FormatWrite@CmLogFile@@AEAAXW4_CMLOG_ITEM@@PEAG@Z>
extern __imp_?GPPB@CIniA@@QEBAHPEBD0H@Z:PANYARGS
?GPPB@CIniA@@QEBAHPEBD0H@Z TEXTEQU <__imp_?GPPB@CIniA@@QEBAHPEBD0H@Z>
extern __imp_?GPPB@CIniW@@QEBAHPEBG0H@Z:PANYARGS
?GPPB@CIniW@@QEBAHPEBG0H@Z TEXTEQU <__imp_?GPPB@CIniW@@QEBAHPEBG0H@Z>
extern __imp_?GPPI@CIniA@@QEBAKPEBD0K@Z:PANYARGS
?GPPI@CIniA@@QEBAKPEBD0K@Z TEXTEQU <__imp_?GPPI@CIniA@@QEBAKPEBD0K@Z>
extern __imp_?GPPI@CIniW@@QEBAKPEBG0K@Z:PANYARGS
?GPPI@CIniW@@QEBAKPEBG0K@Z TEXTEQU <__imp_?GPPI@CIniW@@QEBAKPEBG0K@Z>
extern __imp_?GPPS@CIniA@@QEBAPEADPEBD00@Z:PANYARGS
?GPPS@CIniA@@QEBAPEADPEBD00@Z TEXTEQU <__imp_?GPPS@CIniA@@QEBAPEADPEBD00@Z>
extern __imp_?GPPS@CIniW@@QEBAPEAGPEBG00@Z:PANYARGS
?GPPS@CIniW@@QEBAPEAGPEBG00@Z TEXTEQU <__imp_?GPPS@CIniW@@QEBAPEAGPEBG00@Z>
extern __imp_?Generate@CRandom@@QEAAHXZ:PANYARGS
?Generate@CRandom@@QEAAHXZ TEXTEQU <__imp_?Generate@CRandom@@QEAAHXZ>
extern __imp_?GetFile@CIniA@@QEBAPEBDXZ:PANYARGS
?GetFile@CIniA@@QEBAPEBDXZ TEXTEQU <__imp_?GetFile@CIniA@@QEBAPEBDXZ>
extern __imp_?GetFile@CIniW@@QEBAPEBGXZ:PANYARGS
?GetFile@CIniW@@QEBAPEBGXZ TEXTEQU <__imp_?GetFile@CIniW@@QEBAPEBGXZ>
extern __imp_?GetHInst@CIniA@@QEBAPEAUHINSTANCE__@@XZ:PANYARGS
?GetHInst@CIniA@@QEBAPEAUHINSTANCE__@@XZ TEXTEQU <__imp_?GetHInst@CIniA@@QEBAPEAUHINSTANCE__@@XZ>
extern __imp_?GetHInst@CIniW@@QEBAPEAUHINSTANCE__@@XZ:PANYARGS
?GetHInst@CIniW@@QEBAPEAUHINSTANCE__@@XZ TEXTEQU <__imp_?GetHInst@CIniW@@QEBAPEAUHINSTANCE__@@XZ>
extern __imp_?GetLogFilePath@CmLogFile@@QEAAPEBGXZ:PANYARGS
?GetLogFilePath@CmLogFile@@QEAAPEBGXZ TEXTEQU <__imp_?GetLogFilePath@CmLogFile@@QEAAPEBGXZ>
extern __imp_GetOSBuildNumber:PANYARGS
GetOSBuildNumber TEXTEQU <__imp_GetOSBuildNumber>
extern __imp_GetOSMajorVersion:PANYARGS
GetOSMajorVersion TEXTEQU <__imp_GetOSMajorVersion>
extern __imp_GetOSVersion:PANYARGS
GetOSVersion TEXTEQU <__imp_GetOSVersion>
extern __imp_?GetPrimaryFile@CIniA@@QEBAPEBDXZ:PANYARGS
?GetPrimaryFile@CIniA@@QEBAPEBDXZ TEXTEQU <__imp_?GetPrimaryFile@CIniA@@QEBAPEBDXZ>
extern __imp_?GetPrimaryFile@CIniW@@QEBAPEBGXZ:PANYARGS
?GetPrimaryFile@CIniW@@QEBAPEBGXZ TEXTEQU <__imp_?GetPrimaryFile@CIniW@@QEBAPEBGXZ>
extern __imp_?GetPrimaryRegPath@CIniA@@QEBAPEBDXZ:PANYARGS
?GetPrimaryRegPath@CIniA@@QEBAPEBDXZ TEXTEQU <__imp_?GetPrimaryRegPath@CIniA@@QEBAPEBDXZ>
extern __imp_?GetPrimaryRegPath@CIniW@@QEBAPEBGXZ:PANYARGS
?GetPrimaryRegPath@CIniW@@QEBAPEBGXZ TEXTEQU <__imp_?GetPrimaryRegPath@CIniW@@QEBAPEBGXZ>
extern __imp_?GetRegPath@CIniA@@QEBAPEBDXZ:PANYARGS
?GetRegPath@CIniA@@QEBAPEBDXZ TEXTEQU <__imp_?GetRegPath@CIniA@@QEBAPEBDXZ>
extern __imp_?GetRegPath@CIniW@@QEBAPEBGXZ:PANYARGS
?GetRegPath@CIniW@@QEBAPEBGXZ TEXTEQU <__imp_?GetRegPath@CIniW@@QEBAPEBGXZ>
extern __imp_?GetSection@CIniA@@QEBAPEBDXZ:PANYARGS
?GetSection@CIniA@@QEBAPEBDXZ TEXTEQU <__imp_?GetSection@CIniA@@QEBAPEBDXZ>
extern __imp_?GetSection@CIniW@@QEBAPEBGXZ:PANYARGS
?GetSection@CIniW@@QEBAPEBGXZ TEXTEQU <__imp_?GetSection@CIniW@@QEBAPEBGXZ>
extern __imp_?Init@CRandom@@QEAAXK@Z:PANYARGS
?Init@CRandom@@QEAAXK@Z TEXTEQU <__imp_?Init@CRandom@@QEAAXK@Z>
extern __imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBD@Z:PANYARGS
?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBD@Z TEXTEQU <__imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBD@Z>
extern __imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBG@Z:PANYARGS
?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBG@Z TEXTEQU <__imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBG@Z>
extern __imp_?IsEnabled@CmLogFile@@QEAAHXZ:PANYARGS
?IsEnabled@CmLogFile@@QEAAHXZ TEXTEQU <__imp_?IsEnabled@CmLogFile@@QEAAHXZ>
extern __imp_IsFarEastNonOSR2Win95:PANYARGS
IsFarEastNonOSR2Win95 TEXTEQU <__imp_IsFarEastNonOSR2Win95>
extern __imp_IsLogonAsSystem:PANYARGS
IsLogonAsSystem TEXTEQU <__imp_IsLogonAsSystem>
extern __imp_?LoadEntry@CIniA@@IEBAPEADPEBD@Z:PANYARGS
?LoadEntry@CIniA@@IEBAPEADPEBD@Z TEXTEQU <__imp_?LoadEntry@CIniA@@IEBAPEADPEBD@Z>
extern __imp_?LoadEntry@CIniW@@IEBAPEAGPEBG@Z:PANYARGS
?LoadEntry@CIniW@@IEBAPEAGPEBG@Z TEXTEQU <__imp_?LoadEntry@CIniW@@IEBAPEAGPEBG@Z>
extern __imp_?LoadSection@CIniA@@QEBAPEADPEBD@Z:PANYARGS
?LoadSection@CIniA@@QEBAPEADPEBD@Z TEXTEQU <__imp_?LoadSection@CIniA@@QEBAPEADPEBD@Z>
extern __imp_?LoadSection@CIniW@@QEBAPEAGPEBG@Z:PANYARGS
?LoadSection@CIniW@@QEBAPEAGPEBG@Z TEXTEQU <__imp_?LoadSection@CIniW@@QEBAPEAGPEBG@Z>
extern __imp_?Log@CmLogFile@@QEAAXW4_CMLOG_ITEM@@ZZ:PANYARGS
?Log@CmLogFile@@QEAAXW4_CMLOG_ITEM@@ZZ TEXTEQU <__imp_?Log@CmLogFile@@QEAAXW4_CMLOG_ITEM@@ZZ>
extern __imp_MakeBold:PANYARGS
MakeBold TEXTEQU <__imp_MakeBold>
extern __imp_?OpenFile@CmLogFile@@AEAAJXZ:PANYARGS
?OpenFile@CmLogFile@@AEAAJXZ TEXTEQU <__imp_?OpenFile@CmLogFile@@AEAAJXZ>
extern __imp_ReleaseBold:PANYARGS
ReleaseBold TEXTEQU <__imp_ReleaseBold>
extern __imp_?SetEntry@CIniA@@QEAAXPEBD@Z:PANYARGS
?SetEntry@CIniA@@QEAAXPEBD@Z TEXTEQU <__imp_?SetEntry@CIniA@@QEAAXPEBD@Z>
extern __imp_?SetEntry@CIniW@@QEAAXPEBG@Z:PANYARGS
?SetEntry@CIniW@@QEAAXPEBG@Z TEXTEQU <__imp_?SetEntry@CIniW@@QEAAXPEBG@Z>
extern __imp_?SetEntryFromIdx@CIniA@@QEAAXK@Z:PANYARGS
?SetEntryFromIdx@CIniA@@QEAAXK@Z TEXTEQU <__imp_?SetEntryFromIdx@CIniA@@QEAAXK@Z>
extern __imp_?SetEntryFromIdx@CIniW@@QEAAXK@Z:PANYARGS
?SetEntryFromIdx@CIniW@@QEAAXK@Z TEXTEQU <__imp_?SetEntryFromIdx@CIniW@@QEAAXK@Z>
extern __imp_?SetFile@CIniA@@QEAAXPEBD@Z:PANYARGS
?SetFile@CIniA@@QEAAXPEBD@Z TEXTEQU <__imp_?SetFile@CIniA@@QEAAXPEBD@Z>
extern __imp_?SetFile@CIniW@@QEAAXPEBG@Z:PANYARGS
?SetFile@CIniW@@QEAAXPEBG@Z TEXTEQU <__imp_?SetFile@CIniW@@QEAAXPEBG@Z>
extern __imp_?SetHInst@CIniA@@QEAAXPEAUHINSTANCE__@@@Z:PANYARGS
?SetHInst@CIniA@@QEAAXPEAUHINSTANCE__@@@Z TEXTEQU <__imp_?SetHInst@CIniA@@QEAAXPEAUHINSTANCE__@@@Z>
extern __imp_?SetHInst@CIniW@@QEAAXPEAUHINSTANCE__@@@Z:PANYARGS
?SetHInst@CIniW@@QEAAXPEAUHINSTANCE__@@@Z TEXTEQU <__imp_?SetHInst@CIniW@@QEAAXPEAUHINSTANCE__@@@Z>
extern __imp_?SetICSDataPath@CIniA@@QEAAXPEBD@Z:PANYARGS
?SetICSDataPath@CIniA@@QEAAXPEBD@Z TEXTEQU <__imp_?SetICSDataPath@CIniA@@QEAAXPEBD@Z>
extern __imp_?SetICSDataPath@CIniW@@QEAAXPEBG@Z:PANYARGS
?SetICSDataPath@CIniW@@QEAAXPEBG@Z TEXTEQU <__imp_?SetICSDataPath@CIniW@@QEAAXPEBG@Z>
extern __imp_?SetParams@CmLogFile@@QEAAJHKPEBD@Z:PANYARGS
?SetParams@CmLogFile@@QEAAJHKPEBD@Z TEXTEQU <__imp_?SetParams@CmLogFile@@QEAAJHKPEBD@Z>
extern __imp_?SetParams@CmLogFile@@QEAAJHKPEBG@Z:PANYARGS
?SetParams@CmLogFile@@QEAAJHKPEBG@Z TEXTEQU <__imp_?SetParams@CmLogFile@@QEAAJHKPEBG@Z>
extern __imp_?SetPrimaryFile@CIniA@@QEAAXPEBD@Z:PANYARGS
?SetPrimaryFile@CIniA@@QEAAXPEBD@Z TEXTEQU <__imp_?SetPrimaryFile@CIniA@@QEAAXPEBD@Z>
extern __imp_?SetPrimaryFile@CIniW@@QEAAXPEBG@Z:PANYARGS
?SetPrimaryFile@CIniW@@QEAAXPEBG@Z TEXTEQU <__imp_?SetPrimaryFile@CIniW@@QEAAXPEBG@Z>
extern __imp_?SetPrimaryRegPath@CIniA@@QEAAXPEBD@Z:PANYARGS
?SetPrimaryRegPath@CIniA@@QEAAXPEBD@Z TEXTEQU <__imp_?SetPrimaryRegPath@CIniA@@QEAAXPEBD@Z>
extern __imp_?SetPrimaryRegPath@CIniW@@QEAAXPEBG@Z:PANYARGS
?SetPrimaryRegPath@CIniW@@QEAAXPEBG@Z TEXTEQU <__imp_?SetPrimaryRegPath@CIniW@@QEAAXPEBG@Z>
extern __imp_?SetReadICSData@CIniA@@QEAAXH@Z:PANYARGS
?SetReadICSData@CIniA@@QEAAXH@Z TEXTEQU <__imp_?SetReadICSData@CIniA@@QEAAXH@Z>
extern __imp_?SetReadICSData@CIniW@@QEAAXH@Z:PANYARGS
?SetReadICSData@CIniW@@QEAAXH@Z TEXTEQU <__imp_?SetReadICSData@CIniW@@QEAAXH@Z>
extern __imp_?SetRegPath@CIniA@@QEAAXPEBD@Z:PANYARGS
?SetRegPath@CIniA@@QEAAXPEBD@Z TEXTEQU <__imp_?SetRegPath@CIniA@@QEAAXPEBD@Z>
extern __imp_?SetRegPath@CIniW@@QEAAXPEBG@Z:PANYARGS
?SetRegPath@CIniW@@QEAAXPEBG@Z TEXTEQU <__imp_?SetRegPath@CIniW@@QEAAXPEBG@Z>
extern __imp_?SetSection@CIniA@@QEAAXPEBD@Z:PANYARGS
?SetSection@CIniA@@QEAAXPEBD@Z TEXTEQU <__imp_?SetSection@CIniA@@QEAAXPEBD@Z>
extern __imp_?SetSection@CIniW@@QEAAXPEBG@Z:PANYARGS
?SetSection@CIniW@@QEAAXPEBG@Z TEXTEQU <__imp_?SetSection@CIniW@@QEAAXPEBG@Z>
extern __imp_?SetWriteICSData@CIniA@@QEAAXH@Z:PANYARGS
?SetWriteICSData@CIniA@@QEAAXH@Z TEXTEQU <__imp_?SetWriteICSData@CIniA@@QEAAXH@Z>
extern __imp_?SetWriteICSData@CIniW@@QEAAXH@Z:PANYARGS
?SetWriteICSData@CIniW@@QEAAXH@Z TEXTEQU <__imp_?SetWriteICSData@CIniW@@QEAAXH@Z>
extern __imp_?Start@CmLogFile@@QEAAJH@Z:PANYARGS
?Start@CmLogFile@@QEAAJH@Z TEXTEQU <__imp_?Start@CmLogFile@@QEAAJH@Z>
extern __imp_?Stop@CmLogFile@@QEAAJXZ:PANYARGS
?Stop@CmLogFile@@QEAAJXZ TEXTEQU <__imp_?Stop@CmLogFile@@QEAAJXZ>
extern __imp_SzToWz:PANYARGS
SzToWz TEXTEQU <__imp_SzToWz>
extern __imp_SzToWzWithAlloc:PANYARGS
SzToWzWithAlloc TEXTEQU <__imp_SzToWzWithAlloc>
extern __imp_UpdateFont:PANYARGS
UpdateFont TEXTEQU <__imp_UpdateFont>
extern __imp_?WPPB@CIniA@@QEAAXPEBD0H@Z:PANYARGS
?WPPB@CIniA@@QEAAXPEBD0H@Z TEXTEQU <__imp_?WPPB@CIniA@@QEAAXPEBD0H@Z>
extern __imp_?WPPB@CIniW@@QEAAXPEBG0H@Z:PANYARGS
?WPPB@CIniW@@QEAAXPEBG0H@Z TEXTEQU <__imp_?WPPB@CIniW@@QEAAXPEBG0H@Z>
extern __imp_?WPPI@CIniA@@QEAAXPEBD0K@Z:PANYARGS
?WPPI@CIniA@@QEAAXPEBD0K@Z TEXTEQU <__imp_?WPPI@CIniA@@QEAAXPEBD0K@Z>
extern __imp_?WPPI@CIniW@@QEAAXPEBG0K@Z:PANYARGS
?WPPI@CIniW@@QEAAXPEBG0K@Z TEXTEQU <__imp_?WPPI@CIniW@@QEAAXPEBG0K@Z>
extern __imp_?WPPS@CIniA@@QEAAXPEBD00@Z:PANYARGS
?WPPS@CIniA@@QEAAXPEBD00@Z TEXTEQU <__imp_?WPPS@CIniA@@QEAAXPEBD00@Z>
extern __imp_?WPPS@CIniW@@QEAAXPEBG00@Z:PANYARGS
?WPPS@CIniW@@QEAAXPEBG00@Z TEXTEQU <__imp_?WPPS@CIniW@@QEAAXPEBG00@Z>
extern __imp_?Write@CmLogFile@@AEAAJPEAG@Z:PANYARGS
?Write@CmLogFile@@AEAAJPEAG@Z TEXTEQU <__imp_?Write@CmLogFile@@AEAAJPEAG@Z>
extern __imp_WzToSz:PANYARGS
WzToSz TEXTEQU <__imp_WzToSz>
extern __imp_WzToSzWithAlloc:PANYARGS
WzToSzWithAlloc TEXTEQU <__imp_WzToSzWithAlloc>
