extern __imp_comdlg32_ordinal100:PANYARGS
comdlg32_ordinal100 TEXTEQU <__imp_comdlg32_ordinal100>
extern __imp_ChooseColorA:PANYARGS
ChooseColor  TEXTEQU <__imp_ChooseColorA>
extern __imp_ChooseColorW:PANYARGS
ChooseColorW TEXTEQU <__imp_ChooseColorW>
extern __imp_ChooseFontA:PANYARGS
ChooseFont  TEXTEQU <__imp_ChooseFontA>
extern __imp_ChooseFontW:PANYARGS
ChooseFontW TEXTEQU <__imp_ChooseFontW>
extern __imp_CommDlgExtendedError:PANYARGS
CommDlgExtendedError TEXTEQU <__imp_CommDlgExtendedError>
extern __imp_FindTextA:PANYARGS
FindText  TEXTEQU <__imp_FindTextA>
extern __imp_FindTextW:PANYARGS
FindTextW TEXTEQU <__imp_FindTextW>
extern __imp_GetFileTitleA:PANYARGS
GetFileTitle  TEXTEQU <__imp_GetFileTitleA>
extern __imp_GetFileTitleW:PANYARGS
GetFileTitleW TEXTEQU <__imp_GetFileTitleW>
extern __imp_GetOpenFileNameA:PANYARGS
GetOpenFileName  TEXTEQU <__imp_GetOpenFileNameA>
extern __imp_GetOpenFileNameW:PANYARGS
GetOpenFileNameW TEXTEQU <__imp_GetOpenFileNameW>
extern __imp_GetSaveFileNameA:PANYARGS
GetSaveFileName  TEXTEQU <__imp_GetSaveFileNameA>
extern __imp_GetSaveFileNameW:PANYARGS
GetSaveFileNameW TEXTEQU <__imp_GetSaveFileNameW>
extern __imp_LoadAlterBitmap:PANYARGS
LoadAlterBitmap TEXTEQU <__imp_LoadAlterBitmap>
extern __imp_PageSetupDlgA:PANYARGS
PageSetupDlg  TEXTEQU <__imp_PageSetupDlgA>
extern __imp_PageSetupDlgW:PANYARGS
PageSetupDlgW TEXTEQU <__imp_PageSetupDlgW>
extern __imp_PrintDlgA:PANYARGS
PrintDlg  TEXTEQU <__imp_PrintDlgA>
extern __imp_PrintDlgExA:PANYARGS
PrintDlgEx  TEXTEQU <__imp_PrintDlgExA>
extern __imp_PrintDlgExW:PANYARGS
PrintDlgExW TEXTEQU <__imp_PrintDlgExW>
extern __imp_PrintDlgW:PANYARGS
PrintDlgW TEXTEQU <__imp_PrintDlgW>
extern __imp_ReplaceTextA:PANYARGS
ReplaceText  TEXTEQU <__imp_ReplaceTextA>
extern __imp_ReplaceTextW:PANYARGS
ReplaceTextW TEXTEQU <__imp_ReplaceTextW>
extern __imp_Ssync_ANSI_UNICODE_Struct_For_WOW:PANYARGS
Ssync_ANSI_UNICODE_Struct_For_WOW TEXTEQU <__imp_Ssync_ANSI_UNICODE_Struct_For_WOW>
extern __imp_WantArrows:PANYARGS
WantArrows TEXTEQU <__imp_WantArrows>
extern __imp_dwLBSubclass:PANYARGS
dwLBSubclass TEXTEQU <__imp_dwLBSubclass>
extern __imp_dwOKSubclass:PANYARGS
dwOKSubclass TEXTEQU <__imp_dwOKSubclass>
