extern __imp_CommonPropertySheetUIA:PANYARGS
CommonPropertySheetUI  TEXTEQU <__imp_CommonPropertySheetUIA>
extern __imp_CommonPropertySheetUIW:PANYARGS
CommonPropertySheetUIW TEXTEQU <__imp_CommonPropertySheetUIW>
extern __imp_GetCPSUIUserData:PANYARGS
GetCPSUIUserData TEXTEQU <__imp_GetCPSUIUserData>
extern __imp_SetCPSUIUserData:PANYARGS
SetCPSUIUserData TEXTEQU <__imp_SetCPSUIUserData>
