extern __imp_CosGetCallContext:PANYARGS
CosGetCallContext TEXTEQU <__imp_CosGetCallContext>
extern __imp_comsvcs_ordinal6:PANYARGS
comsvcs_ordinal6 TEXTEQU <__imp_comsvcs_ordinal6>
extern __imp_comsvcs_ordinal7:PANYARGS
comsvcs_ordinal7 TEXTEQU <__imp_comsvcs_ordinal7>
extern __imp_GetMTAThreadPoolMetrics:PANYARGS
GetMTAThreadPoolMetrics TEXTEQU <__imp_GetMTAThreadPoolMetrics>
extern __imp_CoCreateActivity:PANYARGS
CoCreateActivity TEXTEQU <__imp_CoCreateActivity>
extern __imp_CoEnterServiceDomain:PANYARGS
CoEnterServiceDomain TEXTEQU <__imp_CoEnterServiceDomain>
extern __imp_CoLeaveServiceDomain:PANYARGS
CoLeaveServiceDomain TEXTEQU <__imp_CoLeaveServiceDomain>
extern __imp_CoLoadServices:PANYARGS
CoLoadServices TEXTEQU <__imp_CoLoadServices>
extern __imp_ComSvcsExceptionFilter:PANYARGS
ComSvcsExceptionFilter TEXTEQU <__imp_ComSvcsExceptionFilter>
extern __imp_ComSvcsLogError:PANYARGS
ComSvcsLogError TEXTEQU <__imp_ComSvcsLogError>
extern __imp_DispManGetContext:PANYARGS
DispManGetContext TEXTEQU <__imp_DispManGetContext>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetManagedExtensions:PANYARGS
GetManagedExtensions TEXTEQU <__imp_GetManagedExtensions>
extern __imp_GetObjectContext:PANYARGS
GetObjectContext TEXTEQU <__imp_GetObjectContext>
extern __imp_GetTrkSvrObject:PANYARGS
GetTrkSvrObject TEXTEQU <__imp_GetTrkSvrObject>
extern __imp_MTSCreateActivity:PANYARGS
MTSCreateActivity TEXTEQU <__imp_MTSCreateActivity>
extern __imp_MiniDumpW:PANYARGS
MiniDumpW TEXTEQU <__imp_MiniDumpW>
extern __imp_RecycleSurrogate:PANYARGS
RecycleSurrogate TEXTEQU <__imp_RecycleSurrogate>
extern __imp_RegisterComEvents:PANYARGS
RegisterComEvents TEXTEQU <__imp_RegisterComEvents>
extern __imp_SafeRef:PANYARGS
SafeRef TEXTEQU <__imp_SafeRef>
