extern __imp_CORLockDownProvider:PANYARGS
CORLockDownProvider TEXTEQU <__imp_CORLockDownProvider>
extern __imp_CORPolicyEE:PANYARGS
CORPolicyEE TEXTEQU <__imp_CORPolicyEE>
extern __imp_CORPolicyProvider:PANYARGS
CORPolicyProvider TEXTEQU <__imp_CORPolicyProvider>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetPublisher:PANYARGS
GetPublisher TEXTEQU <__imp_GetPublisher>
extern __imp_GetUnsignedPermissions:PANYARGS
GetUnsignedPermissions TEXTEQU <__imp_GetUnsignedPermissions>
