extern __imp_CryptExtAddCER:PANYARGS
CryptExtAddCER TEXTEQU <__imp_CryptExtAddCER>
extern __imp_CryptExtAddCERW:PANYARGS
CryptExtAddCERW TEXTEQU <__imp_CryptExtAddCERW>
extern __imp_CryptExtAddCRL:PANYARGS
CryptExtAddCRL TEXTEQU <__imp_CryptExtAddCRL>
extern __imp_CryptExtAddCRLW:PANYARGS
CryptExtAddCRLW TEXTEQU <__imp_CryptExtAddCRLW>
extern __imp_CryptExtAddCTL:PANYARGS
CryptExtAddCTL TEXTEQU <__imp_CryptExtAddCTL>
extern __imp_CryptExtAddCTLW:PANYARGS
CryptExtAddCTLW TEXTEQU <__imp_CryptExtAddCTLW>
extern __imp_CryptExtAddP7R:PANYARGS
CryptExtAddP7R TEXTEQU <__imp_CryptExtAddP7R>
extern __imp_CryptExtAddP7RW:PANYARGS
CryptExtAddP7RW TEXTEQU <__imp_CryptExtAddP7RW>
extern __imp_CryptExtAddPFX:PANYARGS
CryptExtAddPFX TEXTEQU <__imp_CryptExtAddPFX>
extern __imp_CryptExtAddPFXW:PANYARGS
CryptExtAddPFXW TEXTEQU <__imp_CryptExtAddPFXW>
extern __imp_CryptExtAddSPC:PANYARGS
CryptExtAddSPC TEXTEQU <__imp_CryptExtAddSPC>
extern __imp_CryptExtAddSPCW:PANYARGS
CryptExtAddSPCW TEXTEQU <__imp_CryptExtAddSPCW>
extern __imp_CryptExtOpenCAT:PANYARGS
CryptExtOpenCAT TEXTEQU <__imp_CryptExtOpenCAT>
extern __imp_CryptExtOpenCATW:PANYARGS
CryptExtOpenCATW TEXTEQU <__imp_CryptExtOpenCATW>
extern __imp_CryptExtOpenCER:PANYARGS
CryptExtOpenCER TEXTEQU <__imp_CryptExtOpenCER>
extern __imp_CryptExtOpenCERW:PANYARGS
CryptExtOpenCERW TEXTEQU <__imp_CryptExtOpenCERW>
extern __imp_CryptExtOpenCRL:PANYARGS
CryptExtOpenCRL TEXTEQU <__imp_CryptExtOpenCRL>
extern __imp_CryptExtOpenCRLW:PANYARGS
CryptExtOpenCRLW TEXTEQU <__imp_CryptExtOpenCRLW>
extern __imp_CryptExtOpenCTL:PANYARGS
CryptExtOpenCTL TEXTEQU <__imp_CryptExtOpenCTL>
extern __imp_CryptExtOpenCTLW:PANYARGS
CryptExtOpenCTLW TEXTEQU <__imp_CryptExtOpenCTLW>
extern __imp_CryptExtOpenP10:PANYARGS
CryptExtOpenP10 TEXTEQU <__imp_CryptExtOpenP10>
extern __imp_CryptExtOpenP10W:PANYARGS
CryptExtOpenP10W TEXTEQU <__imp_CryptExtOpenP10W>
extern __imp_CryptExtOpenP7R:PANYARGS
CryptExtOpenP7R TEXTEQU <__imp_CryptExtOpenP7R>
extern __imp_CryptExtOpenP7RW:PANYARGS
CryptExtOpenP7RW TEXTEQU <__imp_CryptExtOpenP7RW>
extern __imp_CryptExtOpenPKCS7:PANYARGS
CryptExtOpenPKCS7 TEXTEQU <__imp_CryptExtOpenPKCS7>
extern __imp_CryptExtOpenPKCS7W:PANYARGS
CryptExtOpenPKCS7W TEXTEQU <__imp_CryptExtOpenPKCS7W>
extern __imp_CryptExtOpenSTR:PANYARGS
CryptExtOpenSTR TEXTEQU <__imp_CryptExtOpenSTR>
extern __imp_CryptExtOpenSTRW:PANYARGS
CryptExtOpenSTRW TEXTEQU <__imp_CryptExtOpenSTRW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
