extern __imp_CDBuildIntegrityVect:PANYARGS
CDBuildIntegrityVect TEXTEQU <__imp_CDBuildIntegrityVect>
extern __imp_CDBuildVect:PANYARGS
CDBuildVect TEXTEQU <__imp_CDBuildVect>
extern __imp_CDFindCommonCSystem:PANYARGS
CDFindCommonCSystem TEXTEQU <__imp_CDFindCommonCSystem>
extern __imp_CDFindCommonCSystemWithKey:PANYARGS
CDFindCommonCSystemWithKey TEXTEQU <__imp_CDFindCommonCSystemWithKey>
extern __imp_CDGenerateRandomBits:PANYARGS
CDGenerateRandomBits TEXTEQU <__imp_CDGenerateRandomBits>
extern __imp_CDLocateCSystem:PANYARGS
CDLocateCSystem TEXTEQU <__imp_CDLocateCSystem>
extern __imp_CDLocateCheckSum:PANYARGS
CDLocateCheckSum TEXTEQU <__imp_CDLocateCheckSum>
extern __imp_CDLocateRng:PANYARGS
CDLocateRng TEXTEQU <__imp_CDLocateRng>
extern __imp_CDRegisterCSystem:PANYARGS
CDRegisterCSystem TEXTEQU <__imp_CDRegisterCSystem>
extern __imp_CDRegisterCheckSum:PANYARGS
CDRegisterCheckSum TEXTEQU <__imp_CDRegisterCheckSum>
extern __imp_CDRegisterRng:PANYARGS
CDRegisterRng TEXTEQU <__imp_CDRegisterRng>
extern __imp_MD5Final:PANYARGS
MD5Final TEXTEQU <__imp_MD5Final>
extern __imp_MD5Init:PANYARGS
MD5Init TEXTEQU <__imp_MD5Init>
extern __imp_MD5Update:PANYARGS
MD5Update TEXTEQU <__imp_MD5Update>
