extern __imp_MprServiceProc:PANYARGS
MprServiceProc TEXTEQU <__imp_MprServiceProc>
extern __imp_ReInt_WndProc:PANYARGS
ReInt_WndProc TEXTEQU <__imp_ReInt_WndProc>
extern __imp_LogonHappened:PANYARGS
LogonHappened TEXTEQU <__imp_LogonHappened>
extern __imp_LogoffHappened:PANYARGS
LogoffHappened TEXTEQU <__imp_LogoffHappened>
extern __imp_Update:PANYARGS
Update TEXTEQU <__imp_Update>
extern __imp_RefreshConnections:PANYARGS
RefreshConnections TEXTEQU <__imp_RefreshConnections>
extern __imp_BreakConnections:PANYARGS
BreakConnections TEXTEQU <__imp_BreakConnections>
extern __imp_CheckCSC:PANYARGS
CheckCSC TEXTEQU <__imp_CheckCSC>
extern __imp_CSCIsCSCEnabled:PANYARGS
CSCIsCSCEnabled TEXTEQU <__imp_CSCIsCSCEnabled>
extern __imp_CSCFindClose:PANYARGS
CSCFindClose TEXTEQU <__imp_CSCFindClose>
extern __imp_CSCSetMaxSpace:PANYARGS
CSCSetMaxSpace TEXTEQU <__imp_CSCSetMaxSpace>
extern __imp_CSCFreeSpace:PANYARGS
CSCFreeSpace TEXTEQU <__imp_CSCFreeSpace>
extern __imp_CheckCSCEx:PANYARGS
CheckCSCEx TEXTEQU <__imp_CheckCSCEx>
extern __imp_CSCDoEnableDisable:PANYARGS
CSCDoEnableDisable TEXTEQU <__imp_CSCDoEnableDisable>
extern __imp_cscdll_ordinal15:PANYARGS
cscdll_ordinal15 TEXTEQU <__imp_cscdll_ordinal15>
extern __imp_cscdll_ordinal16:PANYARGS
cscdll_ordinal16 TEXTEQU <__imp_cscdll_ordinal16>
extern __imp_cscdll_ordinal17:PANYARGS
cscdll_ordinal17 TEXTEQU <__imp_cscdll_ordinal17>
extern __imp_cscdll_ordinal18:PANYARGS
cscdll_ordinal18 TEXTEQU <__imp_cscdll_ordinal18>
extern __imp_cscdll_ordinal19:PANYARGS
cscdll_ordinal19 TEXTEQU <__imp_cscdll_ordinal19>
extern __imp_CSCPinFileA:PANYARGS
CSCPinFile  TEXTEQU <__imp_CSCPinFileA>
extern __imp_CSCUnpinFileA:PANYARGS
CSCUnpinFile  TEXTEQU <__imp_CSCUnpinFileA>
extern __imp_CSCQueryFileStatusA:PANYARGS
CSCQueryFileStatus  TEXTEQU <__imp_CSCQueryFileStatusA>
extern __imp_CSCFindFirstFileA:PANYARGS
CSCFindFirstFile  TEXTEQU <__imp_CSCFindFirstFileA>
extern __imp_CSCFindNextFileA:PANYARGS
CSCFindNextFile  TEXTEQU <__imp_CSCFindNextFileA>
extern __imp_CSCDeleteA:PANYARGS
CSCDelete  TEXTEQU <__imp_CSCDeleteA>
extern __imp_CSCFillSparseFilesA:PANYARGS
CSCFillSparseFiles  TEXTEQU <__imp_CSCFillSparseFilesA>
extern __imp_CSCMergeShareA:PANYARGS
CSCMergeShare  TEXTEQU <__imp_CSCMergeShareA>
extern __imp_CSCCopyReplicaA:PANYARGS
CSCCopyReplica  TEXTEQU <__imp_CSCCopyReplicaA>
extern __imp_CSCEnumForStatsA:PANYARGS
CSCEnumForStats  TEXTEQU <__imp_CSCEnumForStatsA>
extern __imp_CSCIsServerOfflineA:PANYARGS
CSCIsServerOffline  TEXTEQU <__imp_CSCIsServerOfflineA>
extern __imp_CSCGetSpaceUsageA:PANYARGS
CSCGetSpaceUsage  TEXTEQU <__imp_CSCGetSpaceUsageA>
extern __imp_CSCTransitionServerOnlineA:PANYARGS
CSCTransitionServerOnline  TEXTEQU <__imp_CSCTransitionServerOnlineA>
extern __imp_CSCCheckShareOnlineA:PANYARGS
CSCCheckShareOnline  TEXTEQU <__imp_CSCCheckShareOnlineA>
extern __imp_CSCDoLocalRenameA:PANYARGS
CSCDoLocalRename  TEXTEQU <__imp_CSCDoLocalRenameA>
extern __imp_CSCEnumForStatsExA:PANYARGS
CSCEnumForStatsEx  TEXTEQU <__imp_CSCEnumForStatsExA>
extern __imp_CSCFindFirstFileForSidA:PANYARGS
CSCFindFirstFileForSid  TEXTEQU <__imp_CSCFindFirstFileForSidA>
extern __imp_CSCQueryFileStatusExA:PANYARGS
CSCQueryFileStatusEx  TEXTEQU <__imp_CSCQueryFileStatusExA>
extern __imp_CSCQueryShareStatusA:PANYARGS
CSCQueryShareStatus  TEXTEQU <__imp_CSCQueryShareStatusA>
extern __imp_CSCPurgeUnpinnedFiles:PANYARGS
CSCPurgeUnpinnedFiles TEXTEQU <__imp_CSCPurgeUnpinnedFiles>
extern __imp_CSCPinFileW:PANYARGS
CSCPinFileW TEXTEQU <__imp_CSCPinFileW>
extern __imp_CSCUnpinFileW:PANYARGS
CSCUnpinFileW TEXTEQU <__imp_CSCUnpinFileW>
extern __imp_CSCQueryFileStatusW:PANYARGS
CSCQueryFileStatusW TEXTEQU <__imp_CSCQueryFileStatusW>
extern __imp_CSCFindFirstFileW:PANYARGS
CSCFindFirstFileW TEXTEQU <__imp_CSCFindFirstFileW>
extern __imp_CSCFindNextFileW:PANYARGS
CSCFindNextFileW TEXTEQU <__imp_CSCFindNextFileW>
extern __imp_CSCDeleteW:PANYARGS
CSCDeleteW TEXTEQU <__imp_CSCDeleteW>
extern __imp_CSCFillSparseFilesW:PANYARGS
CSCFillSparseFilesW TEXTEQU <__imp_CSCFillSparseFilesW>
extern __imp_CSCMergeShareW:PANYARGS
CSCMergeShareW TEXTEQU <__imp_CSCMergeShareW>
extern __imp_CSCCopyReplicaW:PANYARGS
CSCCopyReplicaW TEXTEQU <__imp_CSCCopyReplicaW>
extern __imp_CSCEnumForStatsW:PANYARGS
CSCEnumForStatsW TEXTEQU <__imp_CSCEnumForStatsW>
extern __imp_CSCIsServerOfflineW:PANYARGS
CSCIsServerOfflineW TEXTEQU <__imp_CSCIsServerOfflineW>
extern __imp_CSCGetSpaceUsageW:PANYARGS
CSCGetSpaceUsageW TEXTEQU <__imp_CSCGetSpaceUsageW>
extern __imp_CSCTransitionServerOnlineW:PANYARGS
CSCTransitionServerOnlineW TEXTEQU <__imp_CSCTransitionServerOnlineW>
extern __imp_CSCCheckShareOnlineW:PANYARGS
CSCCheckShareOnlineW TEXTEQU <__imp_CSCCheckShareOnlineW>
extern __imp_CSCDoLocalRenameW:PANYARGS
CSCDoLocalRenameW TEXTEQU <__imp_CSCDoLocalRenameW>
extern __imp_CSCEnumForStatsExW:PANYARGS
CSCEnumForStatsExW TEXTEQU <__imp_CSCEnumForStatsExW>
extern __imp_CSCDoLocalRenameExW:PANYARGS
CSCDoLocalRenameExW TEXTEQU <__imp_CSCDoLocalRenameExW>
extern __imp_CSCCheckShareOnlineExW:PANYARGS
CSCCheckShareOnlineExW TEXTEQU <__imp_CSCCheckShareOnlineExW>
extern __imp_CSCBeginSynchronizationW:PANYARGS
CSCBeginSynchronizationW TEXTEQU <__imp_CSCBeginSynchronizationW>
extern __imp_CSCEndSynchronizationW:PANYARGS
CSCEndSynchronizationW TEXTEQU <__imp_CSCEndSynchronizationW>
extern __imp_CSCFindFirstFileForSidW:PANYARGS
CSCFindFirstFileForSidW TEXTEQU <__imp_CSCFindFirstFileForSidW>
extern __imp_cscdll_ordinal61:PANYARGS
cscdll_ordinal61 TEXTEQU <__imp_cscdll_ordinal61>
extern __imp_CSCEncryptDecryptDatabase:PANYARGS
CSCEncryptDecryptDatabase TEXTEQU <__imp_CSCEncryptDecryptDatabase>
extern __imp_CSCQueryDatabaseStatus:PANYARGS
CSCQueryDatabaseStatus TEXTEQU <__imp_CSCQueryDatabaseStatus>
extern __imp_CSCQueryFileStatusExW:PANYARGS
CSCQueryFileStatusExW TEXTEQU <__imp_CSCQueryFileStatusExW>
extern __imp_CSCQueryShareStatusW:PANYARGS
CSCQueryShareStatusW TEXTEQU <__imp_CSCQueryShareStatusW>
extern __imp_CSCShareIdToShareName:PANYARGS
CSCShareIdToShareName TEXTEQU <__imp_CSCShareIdToShareName>
extern __imp_cscdll_ordinal67:PANYARGS
cscdll_ordinal67 TEXTEQU <__imp_cscdll_ordinal67>
extern __imp_cscdll_ordinal68:PANYARGS
cscdll_ordinal68 TEXTEQU <__imp_cscdll_ordinal68>
extern __imp_cscdll_ordinal69:PANYARGS
cscdll_ordinal69 TEXTEQU <__imp_cscdll_ordinal69>
extern __imp_cscdll_ordinal70:PANYARGS
cscdll_ordinal70 TEXTEQU <__imp_cscdll_ordinal70>
extern __imp_cscdll_ordinal71:PANYARGS
cscdll_ordinal71 TEXTEQU <__imp_cscdll_ordinal71>
extern __imp_cscdll_ordinal72:PANYARGS
cscdll_ordinal72 TEXTEQU <__imp_cscdll_ordinal72>
extern __imp_cscdll_ordinal73:PANYARGS
cscdll_ordinal73 TEXTEQU <__imp_cscdll_ordinal73>
extern __imp_cscdll_ordinal74:PANYARGS
cscdll_ordinal74 TEXTEQU <__imp_cscdll_ordinal74>
extern __imp_cscdll_ordinal75:PANYARGS
cscdll_ordinal75 TEXTEQU <__imp_cscdll_ordinal75>
extern __imp_cscdll_ordinal76:PANYARGS
cscdll_ordinal76 TEXTEQU <__imp_cscdll_ordinal76>
extern __imp_cscdll_ordinal77:PANYARGS
cscdll_ordinal77 TEXTEQU <__imp_cscdll_ordinal77>
extern __imp_cscdll_ordinal78:PANYARGS
cscdll_ordinal78 TEXTEQU <__imp_cscdll_ordinal78>
extern __imp_cscdll_ordinal79:PANYARGS
cscdll_ordinal79 TEXTEQU <__imp_cscdll_ordinal79>
extern __imp_cscdll_ordinal80:PANYARGS
cscdll_ordinal80 TEXTEQU <__imp_cscdll_ordinal80>
extern __imp_cscdll_ordinal81:PANYARGS
cscdll_ordinal81 TEXTEQU <__imp_cscdll_ordinal81>
extern __imp_cscdll_ordinal82:PANYARGS
cscdll_ordinal82 TEXTEQU <__imp_cscdll_ordinal82>
extern __imp_cscdll_ordinal83:PANYARGS
cscdll_ordinal83 TEXTEQU <__imp_cscdll_ordinal83>
extern __imp_cscdll_ordinal84:PANYARGS
cscdll_ordinal84 TEXTEQU <__imp_cscdll_ordinal84>
extern __imp_cscdll_ordinal85:PANYARGS
cscdll_ordinal85 TEXTEQU <__imp_cscdll_ordinal85>
extern __imp_cscdll_ordinal86:PANYARGS
cscdll_ordinal86 TEXTEQU <__imp_cscdll_ordinal86>
extern __imp_cscdll_ordinal87:PANYARGS
cscdll_ordinal87 TEXTEQU <__imp_cscdll_ordinal87>
extern __imp_cscdll_ordinal88:PANYARGS
cscdll_ordinal88 TEXTEQU <__imp_cscdll_ordinal88>
extern __imp_cscdll_ordinal89:PANYARGS
cscdll_ordinal89 TEXTEQU <__imp_cscdll_ordinal89>
extern __imp_cscdll_ordinal90:PANYARGS
cscdll_ordinal90 TEXTEQU <__imp_cscdll_ordinal90>
extern __imp_cscdll_ordinal91:PANYARGS
cscdll_ordinal91 TEXTEQU <__imp_cscdll_ordinal91>
extern __imp_cscdll_ordinal92:PANYARGS
cscdll_ordinal92 TEXTEQU <__imp_cscdll_ordinal92>
extern __imp_cscdll_ordinal93:PANYARGS
cscdll_ordinal93 TEXTEQU <__imp_cscdll_ordinal93>
extern __imp_cscdll_ordinal94:PANYARGS
cscdll_ordinal94 TEXTEQU <__imp_cscdll_ordinal94>
extern __imp_cscdll_ordinal95:PANYARGS
cscdll_ordinal95 TEXTEQU <__imp_cscdll_ordinal95>
extern __imp_cscdll_ordinal96:PANYARGS
cscdll_ordinal96 TEXTEQU <__imp_cscdll_ordinal96>
extern __imp_cscdll_ordinal97:PANYARGS
cscdll_ordinal97 TEXTEQU <__imp_cscdll_ordinal97>
extern __imp_cscdll_ordinal98:PANYARGS
cscdll_ordinal98 TEXTEQU <__imp_cscdll_ordinal98>
extern __imp_cscdll_ordinal99:PANYARGS
cscdll_ordinal99 TEXTEQU <__imp_cscdll_ordinal99>
extern __imp_cscdll_ordinal100:PANYARGS
cscdll_ordinal100 TEXTEQU <__imp_cscdll_ordinal100>
extern __imp_cscdll_ordinal101:PANYARGS
cscdll_ordinal101 TEXTEQU <__imp_cscdll_ordinal101>
extern __imp_cscdll_ordinal102:PANYARGS
cscdll_ordinal102 TEXTEQU <__imp_cscdll_ordinal102>
extern __imp_cscdll_ordinal103:PANYARGS
cscdll_ordinal103 TEXTEQU <__imp_cscdll_ordinal103>
extern __imp_cscdll_ordinal104:PANYARGS
cscdll_ordinal104 TEXTEQU <__imp_cscdll_ordinal104>
extern __imp_cscdll_ordinal105:PANYARGS
cscdll_ordinal105 TEXTEQU <__imp_cscdll_ordinal105>
extern __imp_cscdll_ordinal106:PANYARGS
cscdll_ordinal106 TEXTEQU <__imp_cscdll_ordinal106>
extern __imp_cscdll_ordinal107:PANYARGS
cscdll_ordinal107 TEXTEQU <__imp_cscdll_ordinal107>
extern __imp_cscdll_ordinal108:PANYARGS
cscdll_ordinal108 TEXTEQU <__imp_cscdll_ordinal108>
extern __imp_cscdll_ordinal109:PANYARGS
cscdll_ordinal109 TEXTEQU <__imp_cscdll_ordinal109>
extern __imp_cscdll_ordinal110:PANYARGS
cscdll_ordinal110 TEXTEQU <__imp_cscdll_ordinal110>
extern __imp_cscdll_ordinal111:PANYARGS
cscdll_ordinal111 TEXTEQU <__imp_cscdll_ordinal111>
extern __imp_cscdll_ordinal112:PANYARGS
cscdll_ordinal112 TEXTEQU <__imp_cscdll_ordinal112>
extern __imp_cscdll_ordinal113:PANYARGS
cscdll_ordinal113 TEXTEQU <__imp_cscdll_ordinal113>
extern __imp_cscdll_ordinal114:PANYARGS
cscdll_ordinal114 TEXTEQU <__imp_cscdll_ordinal114>
extern __imp_cscdll_ordinal115:PANYARGS
cscdll_ordinal115 TEXTEQU <__imp_cscdll_ordinal115>
extern __imp_cscdll_ordinal116:PANYARGS
cscdll_ordinal116 TEXTEQU <__imp_cscdll_ordinal116>
extern __imp_cscdll_ordinal117:PANYARGS
cscdll_ordinal117 TEXTEQU <__imp_cscdll_ordinal117>
extern __imp_cscdll_ordinal118:PANYARGS
cscdll_ordinal118 TEXTEQU <__imp_cscdll_ordinal118>
extern __imp_cscdll_ordinal119:PANYARGS
cscdll_ordinal119 TEXTEQU <__imp_cscdll_ordinal119>
extern __imp_cscdll_ordinal120:PANYARGS
cscdll_ordinal120 TEXTEQU <__imp_cscdll_ordinal120>
extern __imp_cscdll_ordinal121:PANYARGS
cscdll_ordinal121 TEXTEQU <__imp_cscdll_ordinal121>
extern __imp_cscdll_ordinal122:PANYARGS
cscdll_ordinal122 TEXTEQU <__imp_cscdll_ordinal122>
extern __imp_cscdll_ordinal123:PANYARGS
cscdll_ordinal123 TEXTEQU <__imp_cscdll_ordinal123>
extern __imp_cscdll_ordinal124:PANYARGS
cscdll_ordinal124 TEXTEQU <__imp_cscdll_ordinal124>
extern __imp_cscdll_ordinal125:PANYARGS
cscdll_ordinal125 TEXTEQU <__imp_cscdll_ordinal125>
extern __imp_cscdll_ordinal126:PANYARGS
cscdll_ordinal126 TEXTEQU <__imp_cscdll_ordinal126>
extern __imp_cscdll_ordinal127:PANYARGS
cscdll_ordinal127 TEXTEQU <__imp_cscdll_ordinal127>
extern __imp_cscdll_ordinal128:PANYARGS
cscdll_ordinal128 TEXTEQU <__imp_cscdll_ordinal128>
extern __imp_cscdll_ordinal129:PANYARGS
cscdll_ordinal129 TEXTEQU <__imp_cscdll_ordinal129>
extern __imp_cscdll_ordinal130:PANYARGS
cscdll_ordinal130 TEXTEQU <__imp_cscdll_ordinal130>
extern __imp_cscdll_ordinal131:PANYARGS
cscdll_ordinal131 TEXTEQU <__imp_cscdll_ordinal131>
extern __imp_cscdll_ordinal132:PANYARGS
cscdll_ordinal132 TEXTEQU <__imp_cscdll_ordinal132>
extern __imp_cscdll_ordinal133:PANYARGS
cscdll_ordinal133 TEXTEQU <__imp_cscdll_ordinal133>
extern __imp_cscdll_ordinal134:PANYARGS
cscdll_ordinal134 TEXTEQU <__imp_cscdll_ordinal134>
extern __imp_cscdll_ordinal135:PANYARGS
cscdll_ordinal135 TEXTEQU <__imp_cscdll_ordinal135>
extern __imp_cscdll_ordinal136:PANYARGS
cscdll_ordinal136 TEXTEQU <__imp_cscdll_ordinal136>
extern __imp_cscdll_ordinal137:PANYARGS
cscdll_ordinal137 TEXTEQU <__imp_cscdll_ordinal137>
extern __imp_cscdll_ordinal138:PANYARGS
cscdll_ordinal138 TEXTEQU <__imp_cscdll_ordinal138>
extern __imp_cscdll_ordinal139:PANYARGS
cscdll_ordinal139 TEXTEQU <__imp_cscdll_ordinal139>
extern __imp_cscdll_ordinal140:PANYARGS
cscdll_ordinal140 TEXTEQU <__imp_cscdll_ordinal140>
extern __imp_cscdll_ordinal141:PANYARGS
cscdll_ordinal141 TEXTEQU <__imp_cscdll_ordinal141>
extern __imp_cscdll_ordinal142:PANYARGS
cscdll_ordinal142 TEXTEQU <__imp_cscdll_ordinal142>
extern __imp_cscdll_ordinal143:PANYARGS
cscdll_ordinal143 TEXTEQU <__imp_cscdll_ordinal143>
extern __imp_cscdll_ordinal144:PANYARGS
cscdll_ordinal144 TEXTEQU <__imp_cscdll_ordinal144>
extern __imp_cscdll_ordinal145:PANYARGS
cscdll_ordinal145 TEXTEQU <__imp_cscdll_ordinal145>
extern __imp_cscdll_ordinal146:PANYARGS
cscdll_ordinal146 TEXTEQU <__imp_cscdll_ordinal146>
extern __imp_cscdll_ordinal147:PANYARGS
cscdll_ordinal147 TEXTEQU <__imp_cscdll_ordinal147>
extern __imp_cscdll_ordinal148:PANYARGS
cscdll_ordinal148 TEXTEQU <__imp_cscdll_ordinal148>
extern __imp_cscdll_ordinal149:PANYARGS
cscdll_ordinal149 TEXTEQU <__imp_cscdll_ordinal149>
extern __imp_cscdll_ordinal150:PANYARGS
cscdll_ordinal150 TEXTEQU <__imp_cscdll_ordinal150>
extern __imp_cscdll_ordinal151:PANYARGS
cscdll_ordinal151 TEXTEQU <__imp_cscdll_ordinal151>
extern __imp_cscdll_ordinal152:PANYARGS
cscdll_ordinal152 TEXTEQU <__imp_cscdll_ordinal152>
extern __imp_cscdll_ordinal153:PANYARGS
cscdll_ordinal153 TEXTEQU <__imp_cscdll_ordinal153>
extern __imp_cscdll_ordinal154:PANYARGS
cscdll_ordinal154 TEXTEQU <__imp_cscdll_ordinal154>
extern __imp_cscdll_ordinal155:PANYARGS
cscdll_ordinal155 TEXTEQU <__imp_cscdll_ordinal155>
extern __imp_cscdll_ordinal156:PANYARGS
cscdll_ordinal156 TEXTEQU <__imp_cscdll_ordinal156>
extern __imp_cscdll_ordinal157:PANYARGS
cscdll_ordinal157 TEXTEQU <__imp_cscdll_ordinal157>
extern __imp_cscdll_ordinal158:PANYARGS
cscdll_ordinal158 TEXTEQU <__imp_cscdll_ordinal158>
extern __imp_cscdll_ordinal159:PANYARGS
cscdll_ordinal159 TEXTEQU <__imp_cscdll_ordinal159>
extern __imp_cscdll_ordinal160:PANYARGS
cscdll_ordinal160 TEXTEQU <__imp_cscdll_ordinal160>
extern __imp_cscdll_ordinal161:PANYARGS
cscdll_ordinal161 TEXTEQU <__imp_cscdll_ordinal161>
extern __imp_cscdll_ordinal162:PANYARGS
cscdll_ordinal162 TEXTEQU <__imp_cscdll_ordinal162>
extern __imp_cscdll_ordinal163:PANYARGS
cscdll_ordinal163 TEXTEQU <__imp_cscdll_ordinal163>
extern __imp_cscdll_ordinal164:PANYARGS
cscdll_ordinal164 TEXTEQU <__imp_cscdll_ordinal164>
extern __imp_cscdll_ordinal165:PANYARGS
cscdll_ordinal165 TEXTEQU <__imp_cscdll_ordinal165>
extern __imp_cscdll_ordinal166:PANYARGS
cscdll_ordinal166 TEXTEQU <__imp_cscdll_ordinal166>
extern __imp_cscdll_ordinal167:PANYARGS
cscdll_ordinal167 TEXTEQU <__imp_cscdll_ordinal167>
extern __imp_cscdll_ordinal168:PANYARGS
cscdll_ordinal168 TEXTEQU <__imp_cscdll_ordinal168>
extern __imp_cscdll_ordinal169:PANYARGS
cscdll_ordinal169 TEXTEQU <__imp_cscdll_ordinal169>
extern __imp_cscdll_ordinal170:PANYARGS
cscdll_ordinal170 TEXTEQU <__imp_cscdll_ordinal170>
extern __imp_cscdll_ordinal171:PANYARGS
cscdll_ordinal171 TEXTEQU <__imp_cscdll_ordinal171>
extern __imp_cscdll_ordinal172:PANYARGS
cscdll_ordinal172 TEXTEQU <__imp_cscdll_ordinal172>
extern __imp_cscdll_ordinal173:PANYARGS
cscdll_ordinal173 TEXTEQU <__imp_cscdll_ordinal173>
extern __imp_cscdll_ordinal174:PANYARGS
cscdll_ordinal174 TEXTEQU <__imp_cscdll_ordinal174>
extern __imp_cscdll_ordinal175:PANYARGS
cscdll_ordinal175 TEXTEQU <__imp_cscdll_ordinal175>
extern __imp_cscdll_ordinal176:PANYARGS
cscdll_ordinal176 TEXTEQU <__imp_cscdll_ordinal176>
extern __imp_cscdll_ordinal177:PANYARGS
cscdll_ordinal177 TEXTEQU <__imp_cscdll_ordinal177>
extern __imp_cscdll_ordinal178:PANYARGS
cscdll_ordinal178 TEXTEQU <__imp_cscdll_ordinal178>
extern __imp_cscdll_ordinal179:PANYARGS
cscdll_ordinal179 TEXTEQU <__imp_cscdll_ordinal179>
extern __imp_cscdll_ordinal180:PANYARGS
cscdll_ordinal180 TEXTEQU <__imp_cscdll_ordinal180>
extern __imp_cscdll_ordinal181:PANYARGS
cscdll_ordinal181 TEXTEQU <__imp_cscdll_ordinal181>
extern __imp_cscdll_ordinal182:PANYARGS
cscdll_ordinal182 TEXTEQU <__imp_cscdll_ordinal182>
extern __imp_cscdll_ordinal183:PANYARGS
cscdll_ordinal183 TEXTEQU <__imp_cscdll_ordinal183>
extern __imp_cscdll_ordinal184:PANYARGS
cscdll_ordinal184 TEXTEQU <__imp_cscdll_ordinal184>
extern __imp_cscdll_ordinal185:PANYARGS
cscdll_ordinal185 TEXTEQU <__imp_cscdll_ordinal185>
extern __imp_cscdll_ordinal186:PANYARGS
cscdll_ordinal186 TEXTEQU <__imp_cscdll_ordinal186>
extern __imp_cscdll_ordinal187:PANYARGS
cscdll_ordinal187 TEXTEQU <__imp_cscdll_ordinal187>
extern __imp_cscdll_ordinal188:PANYARGS
cscdll_ordinal188 TEXTEQU <__imp_cscdll_ordinal188>
extern __imp_cscdll_ordinal189:PANYARGS
cscdll_ordinal189 TEXTEQU <__imp_cscdll_ordinal189>
extern __imp_cscdll_ordinal190:PANYARGS
cscdll_ordinal190 TEXTEQU <__imp_cscdll_ordinal190>
extern __imp_cscdll_ordinal191:PANYARGS
cscdll_ordinal191 TEXTEQU <__imp_cscdll_ordinal191>
extern __imp_cscdll_ordinal192:PANYARGS
cscdll_ordinal192 TEXTEQU <__imp_cscdll_ordinal192>
extern __imp_cscdll_ordinal193:PANYARGS
cscdll_ordinal193 TEXTEQU <__imp_cscdll_ordinal193>
extern __imp_cscdll_ordinal194:PANYARGS
cscdll_ordinal194 TEXTEQU <__imp_cscdll_ordinal194>
extern __imp_cscdll_ordinal195:PANYARGS
cscdll_ordinal195 TEXTEQU <__imp_cscdll_ordinal195>
extern __imp_cscdll_ordinal196:PANYARGS
cscdll_ordinal196 TEXTEQU <__imp_cscdll_ordinal196>
extern __imp_cscdll_ordinal197:PANYARGS
cscdll_ordinal197 TEXTEQU <__imp_cscdll_ordinal197>
extern __imp_cscdll_ordinal198:PANYARGS
cscdll_ordinal198 TEXTEQU <__imp_cscdll_ordinal198>
extern __imp_cscdll_ordinal199:PANYARGS
cscdll_ordinal199 TEXTEQU <__imp_cscdll_ordinal199>
extern __imp_WinlogonLogonEvent:PANYARGS
WinlogonLogonEvent TEXTEQU <__imp_WinlogonLogonEvent>
extern __imp_WinlogonLogoffEvent:PANYARGS
WinlogonLogoffEvent TEXTEQU <__imp_WinlogonLogoffEvent>
extern __imp_WinlogonScreenSaverEvent:PANYARGS
WinlogonScreenSaverEvent TEXTEQU <__imp_WinlogonScreenSaverEvent>
extern __imp_WinlogonShutdownEvent:PANYARGS
WinlogonShutdownEvent TEXTEQU <__imp_WinlogonShutdownEvent>
extern __imp_WinlogonLockEvent:PANYARGS
WinlogonLockEvent TEXTEQU <__imp_WinlogonLockEvent>
extern __imp_WinlogonUnlockEvent:PANYARGS
WinlogonUnlockEvent TEXTEQU <__imp_WinlogonUnlockEvent>
extern __imp_WinlogonStartShellEvent:PANYARGS
WinlogonStartShellEvent TEXTEQU <__imp_WinlogonStartShellEvent>
extern __imp_WinlogonStartupEvent:PANYARGS
WinlogonStartupEvent TEXTEQU <__imp_WinlogonStartupEvent>
