extern __imp_CSCUIOptionsPropertySheet:PANYARGS
CSCUIOptionsPropertySheet TEXTEQU <__imp_CSCUIOptionsPropertySheet>
extern __imp_ProcessGroupPolicy:PANYARGS
ProcessGroupPolicy TEXTEQU <__imp_ProcessGroupPolicy>
extern __imp_CSCOptions_RunDLL:PANYARGS
CSCOptions_RunDLL TEXTEQU <__imp_CSCOptions_RunDLL>
extern __imp_CSCOptions_RunDLLA:PANYARGS
CSCOptions_RunDLL  TEXTEQU <__imp_CSCOptions_RunDLLA>
extern __imp_CSCOptions_RunDLLW:PANYARGS
CSCOptions_RunDLLW TEXTEQU <__imp_CSCOptions_RunDLLW>
extern __imp_CSCUIInitialize:PANYARGS
CSCUIInitialize TEXTEQU <__imp_CSCUIInitialize>
extern __imp_CSCUIMsgProcess:PANYARGS
CSCUIMsgProcess TEXTEQU <__imp_CSCUIMsgProcess>
extern __imp_CSCUIRemoveFolderFromCache:PANYARGS
CSCUIRemoveFolderFromCache TEXTEQU <__imp_CSCUIRemoveFolderFromCache>
extern __imp_CSCUISetState:PANYARGS
CSCUISetState TEXTEQU <__imp_CSCUISetState>
extern __imp_CscPolicyProcessing_RunDLLW:PANYARGS
CscPolicyProcessing_RunDLLW TEXTEQU <__imp_CscPolicyProcessing_RunDLLW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
