extern __imp_CheckFullscreen:PANYARGS
CheckFullscreen TEXTEQU <__imp_CheckFullscreen>
extern __imp_Direct3DShaderValidatorCreate9:PANYARGS
Direct3DShaderValidatorCreate9 TEXTEQU <__imp_Direct3DShaderValidatorCreate9>
extern __imp_PSGPError:PANYARGS
PSGPError TEXTEQU <__imp_PSGPError>
extern __imp_PSGPSampleTexture:PANYARGS
PSGPSampleTexture TEXTEQU <__imp_PSGPSampleTexture>
extern __imp_D3DPERF_BeginEvent:PANYARGS
D3DPERF_BeginEvent TEXTEQU <__imp_D3DPERF_BeginEvent>
extern __imp_D3DPERF_EndEvent:PANYARGS
D3DPERF_EndEvent TEXTEQU <__imp_D3DPERF_EndEvent>
extern __imp_D3DPERF_GetStatus:PANYARGS
D3DPERF_GetStatus TEXTEQU <__imp_D3DPERF_GetStatus>
extern __imp_D3DPERF_QueryRepeatFrame:PANYARGS
D3DPERF_QueryRepeatFrame TEXTEQU <__imp_D3DPERF_QueryRepeatFrame>
extern __imp_D3DPERF_SetMarker:PANYARGS
D3DPERF_SetMarker TEXTEQU <__imp_D3DPERF_SetMarker>
extern __imp_D3DPERF_SetOptions:PANYARGS
D3DPERF_SetOptions TEXTEQU <__imp_D3DPERF_SetOptions>
extern __imp_D3DPERF_SetRegion:PANYARGS
D3DPERF_SetRegion TEXTEQU <__imp_D3DPERF_SetRegion>
extern __imp_DebugSetLevel:PANYARGS
DebugSetLevel TEXTEQU <__imp_DebugSetLevel>
extern __imp_DebugSetMute:PANYARGS
DebugSetMute TEXTEQU <__imp_DebugSetMute>
extern __imp_Direct3DCreate9:PANYARGS
Direct3DCreate9 TEXTEQU <__imp_Direct3DCreate9>
