extern __imp_?COMToCRBvr@@YAPEAVCRBvr@@PEAUIUnknown@@@Z:PANYARGS
?COMToCRBvr@@YAPEAVCRBvr@@PEAUIUnknown@@@Z TEXTEQU <__imp_?COMToCRBvr@@YAPEAVCRBvr@@PEAUIUnknown@@@Z>
extern __imp_?CRAbs@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRAbs@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRAbs@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRAcos@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRAcos@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRAcos@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRAcquireGCLock@@YA_NXZ:PANYARGS
?CRAcquireGCLock@@YA_NXZ TEXTEQU <__imp_?CRAcquireGCLock@@YA_NXZ>
extern __imp_?CRAdd@@YAPEAVCRNumber@@PEAV1@0@Z:PANYARGS
?CRAdd@@YAPEAVCRNumber@@PEAV1@0@Z TEXTEQU <__imp_?CRAdd@@YAPEAVCRNumber@@PEAV1@0@Z>
extern __imp_?CRAdd@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z:PANYARGS
?CRAdd@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRAdd@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z>
extern __imp_?CRAdd@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z:PANYARGS
?CRAdd@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRAdd@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z>
extern __imp_?CRAdd@@YAPEAVCRVector2@@PEAV1@0@Z:PANYARGS
?CRAdd@@YAPEAVCRVector2@@PEAV1@0@Z TEXTEQU <__imp_?CRAdd@@YAPEAVCRVector2@@PEAV1@0@Z>
extern __imp_?CRAdd@@YAPEAVCRVector3@@PEAV1@0@Z:PANYARGS
?CRAdd@@YAPEAVCRVector3@@PEAV1@0@Z TEXTEQU <__imp_?CRAdd@@YAPEAVCRVector3@@PEAV1@0@Z>
extern __imp_?CRAddBvrToRun@@YA_NPEAVCRView@@PEAVCRBvr@@_NPEAJ@Z:PANYARGS
?CRAddBvrToRun@@YA_NPEAVCRView@@PEAVCRBvr@@_NPEAJ@Z TEXTEQU <__imp_?CRAddBvrToRun@@YA_NPEAVCRView@@PEAVCRBvr@@_NPEAJ@Z>
extern __imp_?CRAddElement@@YAJPEAVCRArray@@PEAVCRBvr@@K@Z:PANYARGS
?CRAddElement@@YAJPEAVCRArray@@PEAVCRBvr@@K@Z TEXTEQU <__imp_?CRAddElement@@YAJPEAVCRArray@@PEAVCRBvr@@K@Z>
extern __imp_?CRAddPickData@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@_N@Z:PANYARGS
?CRAddPickData@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@_N@Z TEXTEQU <__imp_?CRAddPickData@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@_N@Z>
extern __imp_?CRAddPickData@@YAPEAVCRImage@@PEAV1@PEAUIUnknown@@_N@Z:PANYARGS
?CRAddPickData@@YAPEAVCRImage@@PEAV1@PEAUIUnknown@@_N@Z TEXTEQU <__imp_?CRAddPickData@@YAPEAVCRImage@@PEAV1@PEAUIUnknown@@_N@Z>
extern __imp_?CRAddRefGC@@YA_NPEAX@Z:PANYARGS
?CRAddRefGC@@YA_NPEAX@Z TEXTEQU <__imp_?CRAddRefGC@@YA_NPEAX@Z>
extern __imp_?CRAddSite@@YA_NPEAVCRSite@@@Z:PANYARGS
?CRAddSite@@YA_NPEAVCRSite@@@Z TEXTEQU <__imp_?CRAddSite@@YA_NPEAVCRSite@@@Z>
extern __imp_?CRAlways@@YAPEAVCREvent@@XZ:PANYARGS
?CRAlways@@YAPEAVCREvent@@XZ TEXTEQU <__imp_?CRAlways@@YAPEAVCREvent@@XZ>
extern __imp_?CRAmbientColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CRAmbientColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CRAmbientColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CRAmbientLight@@YAPEAVCRGeometry@@XZ:PANYARGS
?CRAmbientLight@@YAPEAVCRGeometry@@XZ TEXTEQU <__imp_?CRAmbientLight@@YAPEAVCRGeometry@@XZ>
extern __imp_?CRAnd@@YAPEAVCRBoolean@@PEAV1@0@Z:PANYARGS
?CRAnd@@YAPEAVCRBoolean@@PEAV1@0@Z TEXTEQU <__imp_?CRAnd@@YAPEAVCRBoolean@@PEAV1@0@Z>
extern __imp_?CRAndEvent@@YAPEAVCREvent@@PEAV1@0@Z:PANYARGS
?CRAndEvent@@YAPEAVCREvent@@PEAV1@0@Z TEXTEQU <__imp_?CRAndEvent@@YAPEAVCREvent@@PEAV1@0@Z>
extern __imp_?CRAntiAliasing@@YAPEAVCRFontStyle@@PEAV1@N@Z:PANYARGS
?CRAntiAliasing@@YAPEAVCRFontStyle@@PEAV1@N@Z TEXTEQU <__imp_?CRAntiAliasing@@YAPEAVCRFontStyle@@PEAV1@N@Z>
extern __imp_?CRAntiAliasing@@YAPEAVCRLineStyle@@PEAV1@N@Z:PANYARGS
?CRAntiAliasing@@YAPEAVCRLineStyle@@PEAV1@N@Z TEXTEQU <__imp_?CRAntiAliasing@@YAPEAVCRLineStyle@@PEAV1@N@Z>
extern __imp_?CRAppTriggeredEvent@@YAPEAVCREvent@@XZ:PANYARGS
?CRAppTriggeredEvent@@YAPEAVCREvent@@XZ TEXTEQU <__imp_?CRAppTriggeredEvent@@YAPEAVCREvent@@XZ>
extern __imp_?CRApplyDXTransform@@YAPEAVCRDXTransformResult@@PEAUIUnknown@@JPEAPEAVCRBvr@@PEAV3@@Z:PANYARGS
?CRApplyDXTransform@@YAPEAVCRDXTransformResult@@PEAUIUnknown@@JPEAPEAVCRBvr@@PEAV3@@Z TEXTEQU <__imp_?CRApplyDXTransform@@YAPEAVCRDXTransformResult@@PEAUIUnknown@@JPEAPEAVCRBvr@@PEAV3@@Z>
extern __imp_?CRAqua@@YAPEAVCRColor@@XZ:PANYARGS
?CRAqua@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRAqua@@YAPEAVCRColor@@XZ>
extern __imp_?CRArc@@YAPEAVCRPath2@@NNNN@Z:PANYARGS
?CRArc@@YAPEAVCRPath2@@NNNN@Z TEXTEQU <__imp_?CRArc@@YAPEAVCRPath2@@NNNN@Z>
extern __imp_?CRArcRadians@@YAPEAVCRPath2@@NNNN@Z:PANYARGS
?CRArcRadians@@YAPEAVCRPath2@@NNNN@Z TEXTEQU <__imp_?CRArcRadians@@YAPEAVCRPath2@@NNNN@Z>
extern __imp_?CRArcRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z:PANYARGS
?CRArcRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z TEXTEQU <__imp_?CRArcRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z>
extern __imp_?CRAsin@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRAsin@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRAsin@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRAtan2@@YAPEAVCRNumber@@PEAV1@0@Z:PANYARGS
?CRAtan2@@YAPEAVCRNumber@@PEAV1@0@Z TEXTEQU <__imp_?CRAtan2@@YAPEAVCRNumber@@PEAV1@0@Z>
extern __imp_?CRAtan@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRAtan@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRAtan@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRAttachData@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z:PANYARGS
?CRAttachData@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z TEXTEQU <__imp_?CRAttachData@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z>
extern __imp_?CRBSpline@@YAPEAVCRBvr@@HJQEAPEAVCRNumber@@JQEAPEAV1@J0PEAV2@W4CR_BVR_TYPEID@@@Z:PANYARGS
?CRBSpline@@YAPEAVCRBvr@@HJQEAPEAVCRNumber@@JQEAPEAV1@J0PEAV2@W4CR_BVR_TYPEID@@@Z TEXTEQU <__imp_?CRBSpline@@YAPEAVCRBvr@@HJQEAPEAVCRNumber@@JQEAPEAV1@J0PEAV2@W4CR_BVR_TYPEID@@@Z>
extern __imp_?CRBillboard@@YAPEAVCRGeometry@@PEAV1@PEAVCRVector3@@@Z:PANYARGS
?CRBillboard@@YAPEAVCRGeometry@@PEAV1@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRBillboard@@YAPEAVCRGeometry@@PEAV1@PEAVCRVector3@@@Z>
extern __imp_?CRBlack@@YAPEAVCRColor@@XZ:PANYARGS
?CRBlack@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRBlack@@YAPEAVCRColor@@XZ>
extern __imp_?CRBlendTextureDiffuse@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z:PANYARGS
?CRBlendTextureDiffuse@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z TEXTEQU <__imp_?CRBlendTextureDiffuse@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z>
extern __imp_?CRBlue@@YAPEAVCRColor@@XZ:PANYARGS
?CRBlue@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRBlue@@YAPEAVCRColor@@XZ>
extern __imp_?CRBold@@YAPEAVCRFontStyle@@PEAV1@@Z:PANYARGS
?CRBold@@YAPEAVCRFontStyle@@PEAV1@@Z TEXTEQU <__imp_?CRBold@@YAPEAVCRFontStyle@@PEAV1@@Z>
extern __imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRImage@@@Z:PANYARGS
?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRImage@@@Z TEXTEQU <__imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRImage@@@Z>
extern __imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRPath2@@PEAVCRLineStyle@@@Z:PANYARGS
?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRPath2@@PEAVCRLineStyle@@@Z TEXTEQU <__imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRPath2@@PEAVCRLineStyle@@@Z>
extern __imp_?CRBoundingBox@@YAPEAVCRBbox3@@PEAVCRGeometry@@@Z:PANYARGS
?CRBoundingBox@@YAPEAVCRBbox3@@PEAVCRGeometry@@@Z TEXTEQU <__imp_?CRBoundingBox@@YAPEAVCRBbox3@@PEAVCRGeometry@@@Z>
extern __imp_?CRBvrApplyPreference@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z:PANYARGS
?CRBvrApplyPreference@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z TEXTEQU <__imp_?CRBvrApplyPreference@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z>
extern __imp_?CRBvrToCOM@@YA_NPEAVCRBvr@@AEBU_GUID@@PEAPEAX@Z:PANYARGS
?CRBvrToCOM@@YA_NPEAVCRBvr@@AEBU_GUID@@PEAPEAX@Z TEXTEQU <__imp_?CRBvrToCOM@@YA_NPEAVCRBvr@@AEBU_GUID@@PEAPEAX@Z>
extern __imp_?CRCeiling@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRCeiling@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRCeiling@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRClearLastError@@YAXXZ:PANYARGS
?CRClearLastError@@YAXXZ TEXTEQU <__imp_?CRClearLastError@@YAXXZ>
extern __imp_?CRClearMatte@@YAPEAVCRMatte@@XZ:PANYARGS
?CRClearMatte@@YAPEAVCRMatte@@XZ TEXTEQU <__imp_?CRClearMatte@@YAPEAVCRMatte@@XZ>
extern __imp_?CRClip@@YAPEAVCRImage@@PEAV1@PEAVCRMatte@@@Z:PANYARGS
?CRClip@@YAPEAVCRImage@@PEAV1@PEAVCRMatte@@@Z TEXTEQU <__imp_?CRClip@@YAPEAVCRImage@@PEAV1@PEAVCRMatte@@@Z>
extern __imp_?CRClipPolygonImage@@YAPEAVCRImage@@PEAV1@PEAVCRArray@@@Z:PANYARGS
?CRClipPolygonImage@@YAPEAVCRImage@@PEAV1@PEAVCRArray@@@Z TEXTEQU <__imp_?CRClipPolygonImage@@YAPEAVCRImage@@PEAV1@PEAVCRArray@@@Z>
extern __imp_?CRClose@@YAPEAVCRPath2@@PEAV1@@Z:PANYARGS
?CRClose@@YAPEAVCRPath2@@PEAV1@@Z TEXTEQU <__imp_?CRClose@@YAPEAVCRPath2@@PEAV1@@Z>
extern __imp_?CRColorHsl@@YAPEAVCRColor@@NNN@Z:PANYARGS
?CRColorHsl@@YAPEAVCRColor@@NNN@Z TEXTEQU <__imp_?CRColorHsl@@YAPEAVCRColor@@NNN@Z>
extern __imp_?CRColorHsl@@YAPEAVCRColor@@PEAVCRNumber@@00@Z:PANYARGS
?CRColorHsl@@YAPEAVCRColor@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRColorHsl@@YAPEAVCRColor@@PEAVCRNumber@@00@Z>
extern __imp_?CRColorKey@@YAPEAVCRImage@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CRColorKey@@YAPEAVCRImage@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CRColorKey@@YAPEAVCRImage@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CRColorRgb255@@YAPEAVCRColor@@FFF@Z:PANYARGS
?CRColorRgb255@@YAPEAVCRColor@@FFF@Z TEXTEQU <__imp_?CRColorRgb255@@YAPEAVCRColor@@FFF@Z>
extern __imp_?CRColorRgb@@YAPEAVCRColor@@NNN@Z:PANYARGS
?CRColorRgb@@YAPEAVCRColor@@NNN@Z TEXTEQU <__imp_?CRColorRgb@@YAPEAVCRColor@@NNN@Z>
extern __imp_?CRColorRgb@@YAPEAVCRColor@@PEAVCRNumber@@00@Z:PANYARGS
?CRColorRgb@@YAPEAVCRColor@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRColorRgb@@YAPEAVCRColor@@PEAVCRNumber@@00@Z>
extern __imp_?CRCompose2@@YAPEAVCRTransform2@@PEAV1@0@Z:PANYARGS
?CRCompose2@@YAPEAVCRTransform2@@PEAV1@0@Z TEXTEQU <__imp_?CRCompose2@@YAPEAVCRTransform2@@PEAV1@0@Z>
extern __imp_?CRCompose2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z:PANYARGS
?CRCompose2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRCompose2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z>
extern __imp_?CRCompose3@@YAPEAVCRTransform3@@PEAV1@0@Z:PANYARGS
?CRCompose3@@YAPEAVCRTransform3@@PEAV1@0@Z TEXTEQU <__imp_?CRCompose3@@YAPEAVCRTransform3@@PEAV1@0@Z>
extern __imp_?CRCompose3@@YAPEAVCRTransform3@@PEAVCRArray@@@Z:PANYARGS
?CRCompose3@@YAPEAVCRTransform3@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRCompose3@@YAPEAVCRTransform3@@PEAVCRArray@@@Z>
extern __imp_?CRConcat@@YAPEAVCRPath2@@PEAV1@0@Z:PANYARGS
?CRConcat@@YAPEAVCRPath2@@PEAV1@0@Z TEXTEQU <__imp_?CRConcat@@YAPEAVCRPath2@@PEAV1@0@Z>
extern __imp_?CRConcat@@YAPEAVCRPath2@@PEAVCRArray@@@Z:PANYARGS
?CRConcat@@YAPEAVCRPath2@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRConcat@@YAPEAVCRPath2@@PEAVCRArray@@@Z>
extern __imp_?CRConcatString@@YAPEAVCRString@@PEAV1@0@Z:PANYARGS
?CRConcatString@@YAPEAVCRString@@PEAV1@0@Z TEXTEQU <__imp_?CRConcatString@@YAPEAVCRString@@PEAV1@0@Z>
extern __imp_?CRCond@@YAPEAVCRBvr@@PEAVCRBoolean@@PEAV1@1@Z:PANYARGS
?CRCond@@YAPEAVCRBvr@@PEAVCRBoolean@@PEAV1@1@Z TEXTEQU <__imp_?CRCond@@YAPEAVCRBvr@@PEAVCRBoolean@@PEAV1@1@Z>
extern __imp_?CRConnect@@YA_NPEAUHINSTANCE__@@@Z:PANYARGS
?CRConnect@@YA_NPEAUHINSTANCE__@@@Z TEXTEQU <__imp_?CRConnect@@YA_NPEAUHINSTANCE__@@@Z>
extern __imp_?CRCos@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRCos@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRCos@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRCreateArray@@YAPEAVCRArray@@JQEANW4CR_BVR_TYPEID@@@Z:PANYARGS
?CRCreateArray@@YAPEAVCRArray@@JQEANW4CR_BVR_TYPEID@@@Z TEXTEQU <__imp_?CRCreateArray@@YAPEAVCRArray@@JQEANW4CR_BVR_TYPEID@@@Z>
extern __imp_?CRCreateArray@@YAPEAVCRArray@@JQEAPEAVCRBvr@@K@Z:PANYARGS
?CRCreateArray@@YAPEAVCRArray@@JQEAPEAVCRBvr@@K@Z TEXTEQU <__imp_?CRCreateArray@@YAPEAVCRArray@@JQEAPEAVCRBvr@@K@Z>
extern __imp_?CRCreateBoolean@@YAPEAVCRBoolean@@_N@Z:PANYARGS
?CRCreateBoolean@@YAPEAVCRBoolean@@_N@Z TEXTEQU <__imp_?CRCreateBoolean@@YAPEAVCRBoolean@@_N@Z>
extern __imp_?CRCreateNumber@@YAPEAVCRNumber@@N@Z:PANYARGS
?CRCreateNumber@@YAPEAVCRNumber@@N@Z TEXTEQU <__imp_?CRCreateNumber@@YAPEAVCRNumber@@N@Z>
extern __imp_?CRCreatePoint2@@YAPEAVCRPoint2@@NN@Z:PANYARGS
?CRCreatePoint2@@YAPEAVCRPoint2@@NN@Z TEXTEQU <__imp_?CRCreatePoint2@@YAPEAVCRPoint2@@NN@Z>
extern __imp_?CRCreatePoint2@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z:PANYARGS
?CRCreatePoint2@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRCreatePoint2@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z>
extern __imp_?CRCreatePoint3@@YAPEAVCRPoint3@@NNN@Z:PANYARGS
?CRCreatePoint3@@YAPEAVCRPoint3@@NNN@Z TEXTEQU <__imp_?CRCreatePoint3@@YAPEAVCRPoint3@@NNN@Z>
extern __imp_?CRCreatePoint3@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z:PANYARGS
?CRCreatePoint3@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRCreatePoint3@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z>
extern __imp_?CRCreateString@@YAPEAVCRString@@PEAG@Z:PANYARGS
?CRCreateString@@YAPEAVCRString@@PEAG@Z TEXTEQU <__imp_?CRCreateString@@YAPEAVCRString@@PEAG@Z>
extern __imp_?CRCreateTuple@@YAPEAVCRTuple@@JQEAPEAVCRBvr@@@Z:PANYARGS
?CRCreateTuple@@YAPEAVCRTuple@@JQEAPEAVCRBvr@@@Z TEXTEQU <__imp_?CRCreateTuple@@YAPEAVCRTuple@@JQEAPEAVCRBvr@@@Z>
extern __imp_?CRCreateUserData@@YAPEAVCRUserData@@PEAUIUnknown@@@Z:PANYARGS
?CRCreateUserData@@YAPEAVCRUserData@@PEAUIUnknown@@@Z TEXTEQU <__imp_?CRCreateUserData@@YAPEAVCRUserData@@PEAUIUnknown@@@Z>
extern __imp_?CRCreateVector2@@YAPEAVCRVector2@@NN@Z:PANYARGS
?CRCreateVector2@@YAPEAVCRVector2@@NN@Z TEXTEQU <__imp_?CRCreateVector2@@YAPEAVCRVector2@@NN@Z>
extern __imp_?CRCreateVector2@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z:PANYARGS
?CRCreateVector2@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRCreateVector2@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z>
extern __imp_?CRCreateVector3@@YAPEAVCRVector3@@NNN@Z:PANYARGS
?CRCreateVector3@@YAPEAVCRVector3@@NNN@Z TEXTEQU <__imp_?CRCreateVector3@@YAPEAVCRVector3@@NNN@Z>
extern __imp_?CRCreateVector3@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z:PANYARGS
?CRCreateVector3@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRCreateVector3@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z>
extern __imp_?CRCreateView@@YAPEAVCRView@@XZ:PANYARGS
?CRCreateView@@YAPEAVCRView@@XZ TEXTEQU <__imp_?CRCreateView@@YAPEAVCRView@@XZ>
extern __imp_?CRCrop@@YAPEAVCRImage@@PEAV1@PEAVCRPoint2@@1@Z:PANYARGS
?CRCrop@@YAPEAVCRImage@@PEAV1@PEAVCRPoint2@@1@Z TEXTEQU <__imp_?CRCrop@@YAPEAVCRImage@@PEAV1@PEAVCRPoint2@@1@Z>
extern __imp_?CRCross@@YAPEAVCRVector3@@PEAV1@0@Z:PANYARGS
?CRCross@@YAPEAVCRVector3@@PEAV1@0@Z TEXTEQU <__imp_?CRCross@@YAPEAVCRVector3@@PEAV1@0@Z>
extern __imp_?CRCubicBSplinePath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z:PANYARGS
?CRCubicBSplinePath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z TEXTEQU <__imp_?CRCubicBSplinePath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z>
extern __imp_?CRCyan@@YAPEAVCRColor@@XZ:PANYARGS
?CRCyan@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRCyan@@YAPEAVCRColor@@XZ>
extern __imp_?CRD3DRMTexture@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@@Z:PANYARGS
?CRD3DRMTexture@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@@Z TEXTEQU <__imp_?CRD3DRMTexture@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@@Z>
extern __imp_?CRDash@@YAPEAVCRLineStyle@@PEAV1@PEAVCRDashStyle@@@Z:PANYARGS
?CRDash@@YAPEAVCRLineStyle@@PEAV1@PEAVCRDashStyle@@@Z TEXTEQU <__imp_?CRDash@@YAPEAVCRLineStyle@@PEAV1@PEAVCRDashStyle@@@Z>
extern __imp_?CRDashEx@@YAPEAVCRLineStyle@@PEAV1@K@Z:PANYARGS
?CRDashEx@@YAPEAVCRLineStyle@@PEAV1@K@Z TEXTEQU <__imp_?CRDashEx@@YAPEAVCRLineStyle@@PEAV1@K@Z>
extern __imp_?CRDashStyleDashed@@YAPEAVCRDashStyle@@XZ:PANYARGS
?CRDashStyleDashed@@YAPEAVCRDashStyle@@XZ TEXTEQU <__imp_?CRDashStyleDashed@@YAPEAVCRDashStyle@@XZ>
extern __imp_?CRDashStyleSolid@@YAPEAVCRDashStyle@@XZ:PANYARGS
?CRDashStyleSolid@@YAPEAVCRDashStyle@@XZ TEXTEQU <__imp_?CRDashStyleSolid@@YAPEAVCRDashStyle@@XZ>
extern __imp_?CRDefaultFont@@YAPEAVCRFontStyle@@XZ:PANYARGS
?CRDefaultFont@@YAPEAVCRFontStyle@@XZ TEXTEQU <__imp_?CRDefaultFont@@YAPEAVCRFontStyle@@XZ>
extern __imp_?CRDefaultLineStyle@@YAPEAVCRLineStyle@@XZ:PANYARGS
?CRDefaultLineStyle@@YAPEAVCRLineStyle@@XZ TEXTEQU <__imp_?CRDefaultLineStyle@@YAPEAVCRLineStyle@@XZ>
extern __imp_?CRDefaultMicrophone@@YAPEAVCRMicrophone@@XZ:PANYARGS
?CRDefaultMicrophone@@YAPEAVCRMicrophone@@XZ TEXTEQU <__imp_?CRDefaultMicrophone@@YAPEAVCRMicrophone@@XZ>
extern __imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@N@Z:PANYARGS
?CRDepth@@YAPEAVCRCamera@@PEAV1@N@Z TEXTEQU <__imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@N@Z>
extern __imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRDepth@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@N@Z:PANYARGS
?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@N@Z TEXTEQU <__imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@N@Z>
extern __imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRDerivative@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRDerivative@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRDerivative@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRDerivative@@YAPEAVCRVector2@@PEAV1@@Z:PANYARGS
?CRDerivative@@YAPEAVCRVector2@@PEAV1@@Z TEXTEQU <__imp_?CRDerivative@@YAPEAVCRVector2@@PEAV1@@Z>
extern __imp_?CRDerivative@@YAPEAVCRVector2@@PEAVCRPoint2@@@Z:PANYARGS
?CRDerivative@@YAPEAVCRVector2@@PEAVCRPoint2@@@Z TEXTEQU <__imp_?CRDerivative@@YAPEAVCRVector2@@PEAVCRPoint2@@@Z>
extern __imp_?CRDerivative@@YAPEAVCRVector3@@PEAV1@@Z:PANYARGS
?CRDerivative@@YAPEAVCRVector3@@PEAV1@@Z TEXTEQU <__imp_?CRDerivative@@YAPEAVCRVector3@@PEAV1@@Z>
extern __imp_?CRDerivative@@YAPEAVCRVector3@@PEAVCRPoint3@@@Z:PANYARGS
?CRDerivative@@YAPEAVCRVector3@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRDerivative@@YAPEAVCRVector3@@PEAVCRPoint3@@@Z>
extern __imp_?CRDestroyView@@YAXPEAVCRView@@@Z:PANYARGS
?CRDestroyView@@YAXPEAVCRView@@@Z TEXTEQU <__imp_?CRDestroyView@@YAXPEAVCRView@@@Z>
extern __imp_?CRDetail@@YAPEAVCRLineStyle@@PEAV1@@Z:PANYARGS
?CRDetail@@YAPEAVCRLineStyle@@PEAV1@@Z TEXTEQU <__imp_?CRDetail@@YAPEAVCRLineStyle@@PEAV1@@Z>
extern __imp_?CRDetectableEmptyImage@@YAPEAVCRImage@@XZ:PANYARGS
?CRDetectableEmptyImage@@YAPEAVCRImage@@XZ TEXTEQU <__imp_?CRDetectableEmptyImage@@YAPEAVCRImage@@XZ>
extern __imp_?CRDifferenceMatte@@YAPEAVCRMatte@@PEAV1@0@Z:PANYARGS
?CRDifferenceMatte@@YAPEAVCRMatte@@PEAV1@0@Z TEXTEQU <__imp_?CRDifferenceMatte@@YAPEAVCRMatte@@PEAV1@0@Z>
extern __imp_?CRDiffuseColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CRDiffuseColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CRDiffuseColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CRDirectionalLight@@YAPEAVCRGeometry@@XZ:PANYARGS
?CRDirectionalLight@@YAPEAVCRGeometry@@XZ TEXTEQU <__imp_?CRDirectionalLight@@YAPEAVCRGeometry@@XZ>
extern __imp_?CRDisconnect@@YA_NPEAUHINSTANCE__@@@Z:PANYARGS
?CRDisconnect@@YA_NPEAUHINSTANCE__@@@Z TEXTEQU <__imp_?CRDisconnect@@YA_NPEAUHINSTANCE__@@@Z>
extern __imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z:PANYARGS
?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z TEXTEQU <__imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z>
extern __imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z:PANYARGS
?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z TEXTEQU <__imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z>
extern __imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z:PANYARGS
?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z TEXTEQU <__imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z>
extern __imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z:PANYARGS
?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z TEXTEQU <__imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z>
extern __imp_?CRDiv@@YAPEAVCRNumber@@PEAV1@0@Z:PANYARGS
?CRDiv@@YAPEAVCRNumber@@PEAV1@0@Z TEXTEQU <__imp_?CRDiv@@YAPEAVCRNumber@@PEAV1@0@Z>
extern __imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@N@Z:PANYARGS
?CRDiv@@YAPEAVCRVector2@@PEAV1@N@Z TEXTEQU <__imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@N@Z>
extern __imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRDiv@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@N@Z:PANYARGS
?CRDiv@@YAPEAVCRVector3@@PEAV1@N@Z TEXTEQU <__imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@N@Z>
extern __imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRDiv@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRDoGC@@YA_NXZ:PANYARGS
?CRDoGC@@YA_NXZ TEXTEQU <__imp_?CRDoGC@@YA_NXZ>
extern __imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector2@@0@Z:PANYARGS
?CRDot@@YAPEAVCRNumber@@PEAVCRVector2@@0@Z TEXTEQU <__imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector2@@0@Z>
extern __imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector3@@0@Z:PANYARGS
?CRDot@@YAPEAVCRNumber@@PEAVCRVector3@@0@Z TEXTEQU <__imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector3@@0@Z>
extern __imp_?CRDraw@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@@Z:PANYARGS
?CRDraw@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@@Z TEXTEQU <__imp_?CRDraw@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@@Z>
extern __imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@N@Z:PANYARGS
?CRDuration@@YAPEAVCRBvr@@PEAV1@N@Z TEXTEQU <__imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@N@Z>
extern __imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRDuration@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CREQ@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PANYARGS
?CREQ@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CREQ@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>
extern __imp_?CREmissiveColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CREmissiveColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CREmissiveColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CREmptyColor@@YAPEAVCRColor@@XZ:PANYARGS
?CREmptyColor@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CREmptyColor@@YAPEAVCRColor@@XZ>
extern __imp_?CREmptyGeometry@@YAPEAVCRGeometry@@XZ:PANYARGS
?CREmptyGeometry@@YAPEAVCRGeometry@@XZ TEXTEQU <__imp_?CREmptyGeometry@@YAPEAVCRGeometry@@XZ>
extern __imp_?CREmptyImage@@YAPEAVCRImage@@XZ:PANYARGS
?CREmptyImage@@YAPEAVCRImage@@XZ TEXTEQU <__imp_?CREmptyImage@@YAPEAVCRImage@@XZ>
extern __imp_?CREmptyLineStyle@@YAPEAVCRLineStyle@@XZ:PANYARGS
?CREmptyLineStyle@@YAPEAVCRLineStyle@@XZ TEXTEQU <__imp_?CREmptyLineStyle@@YAPEAVCRLineStyle@@XZ>
extern __imp_?CREmptyMontage@@YAPEAVCRMontage@@XZ:PANYARGS
?CREmptyMontage@@YAPEAVCRMontage@@XZ TEXTEQU <__imp_?CREmptyMontage@@YAPEAVCRMontage@@XZ>
extern __imp_?CREnd@@YAPEAVCRLineStyle@@PEAV1@PEAVCREndStyle@@@Z:PANYARGS
?CREnd@@YAPEAVCRLineStyle@@PEAV1@PEAVCREndStyle@@@Z TEXTEQU <__imp_?CREnd@@YAPEAVCRLineStyle@@PEAV1@PEAVCREndStyle@@@Z>
extern __imp_?CREndEvent@@YAPEAVCRBvr@@PEAV1@@Z:PANYARGS
?CREndEvent@@YAPEAVCRBvr@@PEAV1@@Z TEXTEQU <__imp_?CREndEvent@@YAPEAVCRBvr@@PEAV1@@Z>
extern __imp_?CREndEx@@YAPEAVCRLineStyle@@PEAV1@K@Z:PANYARGS
?CREndEx@@YAPEAVCRLineStyle@@PEAV1@K@Z TEXTEQU <__imp_?CREndEx@@YAPEAVCRLineStyle@@PEAV1@K@Z>
extern __imp_?CREndStyleFlat@@YAPEAVCREndStyle@@XZ:PANYARGS
?CREndStyleFlat@@YAPEAVCREndStyle@@XZ TEXTEQU <__imp_?CREndStyleFlat@@YAPEAVCREndStyle@@XZ>
extern __imp_?CREndStyleRound@@YAPEAVCREndStyle@@XZ:PANYARGS
?CREndStyleRound@@YAPEAVCREndStyle@@XZ TEXTEQU <__imp_?CREndStyleRound@@YAPEAVCREndStyle@@XZ>
extern __imp_?CREndStyleSquare@@YAPEAVCREndStyle@@XZ:PANYARGS
?CREndStyleSquare@@YAPEAVCREndStyle@@XZ TEXTEQU <__imp_?CREndStyleSquare@@YAPEAVCREndStyle@@XZ>
extern __imp_?CRExp@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRExp@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRExp@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRExtendedAttrib@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z:PANYARGS
?CRExtendedAttrib@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z TEXTEQU <__imp_?CRExtendedAttrib@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z>
extern __imp_?CRExtract@@YANPEAVCRNumber@@@Z:PANYARGS
?CRExtract@@YANPEAVCRNumber@@@Z TEXTEQU <__imp_?CRExtract@@YANPEAVCRNumber@@@Z>
extern __imp_?CRExtract@@YAPEAGPEAVCRString@@@Z:PANYARGS
?CRExtract@@YAPEAGPEAVCRString@@@Z TEXTEQU <__imp_?CRExtract@@YAPEAGPEAVCRString@@@Z>
extern __imp_?CRExtract@@YA_NPEAVCRBoolean@@@Z:PANYARGS
?CRExtract@@YA_NPEAVCRBoolean@@@Z TEXTEQU <__imp_?CRExtract@@YA_NPEAVCRBoolean@@@Z>
extern __imp_?CRFalse@@YAPEAVCRBoolean@@XZ:PANYARGS
?CRFalse@@YAPEAVCRBoolean@@XZ TEXTEQU <__imp_?CRFalse@@YAPEAVCRBoolean@@XZ>
extern __imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAG@Z:PANYARGS
?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAG@Z TEXTEQU <__imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAG@Z>
extern __imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAVCRString@@@Z:PANYARGS
?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAVCRString@@@Z TEXTEQU <__imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAVCRString@@@Z>
extern __imp_?CRFill@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@PEAV1@@Z:PANYARGS
?CRFill@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@PEAV1@@Z TEXTEQU <__imp_?CRFill@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@PEAV1@@Z>
extern __imp_?CRFillMatte@@YAPEAVCRMatte@@PEAVCRPath2@@@Z:PANYARGS
?CRFillMatte@@YAPEAVCRMatte@@PEAVCRPath2@@@Z TEXTEQU <__imp_?CRFillMatte@@YAPEAVCRMatte@@PEAVCRPath2@@@Z>
extern __imp_?CRFirst@@YAPEAVCRBvr@@PEAVCRPair@@@Z:PANYARGS
?CRFirst@@YAPEAVCRBvr@@PEAVCRPair@@@Z TEXTEQU <__imp_?CRFirst@@YAPEAVCRBvr@@PEAVCRPair@@@Z>
extern __imp_?CRFloor@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRFloor@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRFloor@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z:PANYARGS
?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z TEXTEQU <__imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z>
extern __imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PANYARGS
?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>
extern __imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z:PANYARGS
?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z TEXTEQU <__imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z>
extern __imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PANYARGS
?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>
extern __imp_?CRFollowPathAngleEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PANYARGS
?CRFollowPathAngleEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRFollowPathAngleEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>
extern __imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z:PANYARGS
?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z TEXTEQU <__imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z>
extern __imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PANYARGS
?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>
extern __imp_?CRFollowPathAngleUprightEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PANYARGS
?CRFollowPathAngleUprightEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRFollowPathAngleUprightEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>
extern __imp_?CRFollowPathEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PANYARGS
?CRFollowPathEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRFollowPathEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>
extern __imp_?CRFont@@YAPEAVCRFontStyle@@PEAGNPEAVCRColor@@@Z:PANYARGS
?CRFont@@YAPEAVCRFontStyle@@PEAGNPEAVCRColor@@@Z TEXTEQU <__imp_?CRFont@@YAPEAVCRFontStyle@@PEAGNPEAVCRColor@@@Z>
extern __imp_?CRFont@@YAPEAVCRFontStyle@@PEAVCRString@@PEAVCRNumber@@PEAVCRColor@@@Z:PANYARGS
?CRFont@@YAPEAVCRFontStyle@@PEAVCRString@@PEAVCRNumber@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRFont@@YAPEAVCRFontStyle@@PEAVCRString@@PEAVCRNumber@@PEAVCRColor@@@Z>
extern __imp_?CRFuchsia@@YAPEAVCRColor@@XZ:PANYARGS
?CRFuchsia@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRFuchsia@@YAPEAVCRColor@@XZ>
extern __imp_?CRGT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PANYARGS
?CRGT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRGT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>
extern __imp_?CRGTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PANYARGS
?CRGTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRGTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>
extern __imp_?CRGain@@YAPEAVCRSound@@PEAV1@N@Z:PANYARGS
?CRGain@@YAPEAVCRSound@@PEAV1@N@Z TEXTEQU <__imp_?CRGain@@YAPEAVCRSound@@PEAV1@N@Z>
extern __imp_?CRGain@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRGain@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRGain@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRGetArrayTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z:PANYARGS
?CRGetArrayTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z TEXTEQU <__imp_?CRGetArrayTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z>
extern __imp_?CRGetBlue@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PANYARGS
?CRGetBlue@@YAPEAVCRNumber@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRGetBlue@@YAPEAVCRNumber@@PEAVCRColor@@@Z>
extern __imp_?CRGetCompletionEvent@@YAPEAVCREvent@@PEAVCRImportationResult@@@Z:PANYARGS
?CRGetCompletionEvent@@YAPEAVCREvent@@PEAVCRImportationResult@@@Z TEXTEQU <__imp_?CRGetCompletionEvent@@YAPEAVCREvent@@PEAVCRImportationResult@@@Z>
extern __imp_?CRGetCompositeDirectlyToTarget@@YA_NPEAVCRView@@@Z:PANYARGS
?CRGetCompositeDirectlyToTarget@@YA_NPEAVCRView@@@Z TEXTEQU <__imp_?CRGetCompositeDirectlyToTarget@@YA_NPEAVCRView@@@Z>
extern __imp_?CRGetConstDuration@@YANPEAVCREvent@@@Z:PANYARGS
?CRGetConstDuration@@YANPEAVCREvent@@@Z TEXTEQU <__imp_?CRGetConstDuration@@YANPEAVCREvent@@@Z>
extern __imp_?CRGetDC@@YAPEAUHDC__@@PEAVCRView@@@Z:PANYARGS
?CRGetDC@@YAPEAUHDC__@@PEAVCRView@@@Z TEXTEQU <__imp_?CRGetDC@@YAPEAUHDC__@@PEAVCRView@@@Z>
extern __imp_?CRGetDDD3DRM@@YA_NPEAVCRView@@PEAPEAUIUnknown@@1@Z:PANYARGS
?CRGetDDD3DRM@@YA_NPEAVCRView@@PEAPEAUIUnknown@@1@Z TEXTEQU <__imp_?CRGetDDD3DRM@@YA_NPEAVCRView@@PEAPEAUIUnknown@@1@Z>
extern __imp_?CRGetData@@YAPEAUIUnknown@@PEAVCRUserData@@@Z:PANYARGS
?CRGetData@@YAPEAUIUnknown@@PEAVCRUserData@@@Z TEXTEQU <__imp_?CRGetData@@YAPEAUIUnknown@@PEAVCRUserData@@@Z>
extern __imp_?CRGetDirectDrawSurface@@YAPEAUIUnknown@@PEAVCRView@@@Z:PANYARGS
?CRGetDirectDrawSurface@@YAPEAUIUnknown@@PEAVCRView@@@Z TEXTEQU <__imp_?CRGetDirectDrawSurface@@YAPEAUIUnknown@@PEAVCRView@@@Z>
extern __imp_?CRGetDuration@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z:PANYARGS
?CRGetDuration@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z TEXTEQU <__imp_?CRGetDuration@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z>
extern __imp_?CRGetElement@@YAPEAVCRBvr@@PEAVCRArray@@J@Z:PANYARGS
?CRGetElement@@YAPEAVCRBvr@@PEAVCRArray@@J@Z TEXTEQU <__imp_?CRGetElement@@YAPEAVCRBvr@@PEAVCRArray@@J@Z>
extern __imp_?CRGetEvent@@YAPEAVCREvent@@PEAVCRPickableResult@@@Z:PANYARGS
?CRGetEvent@@YAPEAVCREvent@@PEAVCRPickableResult@@@Z TEXTEQU <__imp_?CRGetEvent@@YAPEAVCREvent@@PEAVCRPickableResult@@@Z>
extern __imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRImportationResult@@@Z:PANYARGS
?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRImportationResult@@@Z TEXTEQU <__imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRImportationResult@@@Z>
extern __imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRPickableResult@@@Z:PANYARGS
?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRPickableResult@@@Z TEXTEQU <__imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRPickableResult@@@Z>
extern __imp_?CRGetGreen@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PANYARGS
?CRGetGreen@@YAPEAVCRNumber@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRGetGreen@@YAPEAVCRNumber@@PEAVCRColor@@@Z>
extern __imp_?CRGetHue@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PANYARGS
?CRGetHue@@YAPEAVCRNumber@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRGetHue@@YAPEAVCRNumber@@PEAVCRColor@@@Z>
extern __imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRImportationResult@@@Z:PANYARGS
?CRGetImage@@YAPEAVCRImage@@PEAVCRImportationResult@@@Z TEXTEQU <__imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRImportationResult@@@Z>
extern __imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRPickableResult@@@Z:PANYARGS
?CRGetImage@@YAPEAVCRImage@@PEAVCRPickableResult@@@Z TEXTEQU <__imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRPickableResult@@@Z>
extern __imp_?CRGetImportPriority@@YAMPEAVCRBvr@@@Z:PANYARGS
?CRGetImportPriority@@YAMPEAVCRBvr@@@Z TEXTEQU <__imp_?CRGetImportPriority@@YAMPEAVCRBvr@@@Z>
extern __imp_?CRGetInvalidatedRects@@YAJPEAVCRView@@KJPEAUtagRECT@@@Z:PANYARGS
?CRGetInvalidatedRects@@YAJPEAVCRView@@KJPEAUtagRECT@@@Z TEXTEQU <__imp_?CRGetInvalidatedRects@@YAJPEAVCRView@@KJPEAUtagRECT@@@Z>
extern __imp_?CRGetLastError@@YAJXZ:PANYARGS
?CRGetLastError@@YAJXZ TEXTEQU <__imp_?CRGetLastError@@YAJXZ>
extern __imp_?CRGetLastErrorString@@YAPEBGXZ:PANYARGS
?CRGetLastErrorString@@YAPEBGXZ TEXTEQU <__imp_?CRGetLastErrorString@@YAPEBGXZ>
extern __imp_?CRGetLightness@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PANYARGS
?CRGetLightness@@YAPEAVCRNumber@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRGetLightness@@YAPEAVCRNumber@@PEAVCRColor@@@Z>
extern __imp_?CRGetModifiableBvr@@YAPEAVCRBvr@@PEAV1@@Z:PANYARGS
?CRGetModifiableBvr@@YAPEAVCRBvr@@PEAV1@@Z TEXTEQU <__imp_?CRGetModifiableBvr@@YAPEAVCRBvr@@PEAV1@@Z>
extern __imp_?CRGetOutputBvr@@YAPEAVCRBvr@@PEAVCRDXTransformResult@@@Z:PANYARGS
?CRGetOutputBvr@@YAPEAVCRBvr@@PEAVCRDXTransformResult@@@Z TEXTEQU <__imp_?CRGetOutputBvr@@YAPEAVCRBvr@@PEAVCRDXTransformResult@@@Z>
extern __imp_?CRGetPreference@@YA_NPEAVCRView@@PEAGPEAUtagVARIANT@@@Z:PANYARGS
?CRGetPreference@@YA_NPEAVCRView@@PEAGPEAUtagVARIANT@@@Z TEXTEQU <__imp_?CRGetPreference@@YA_NPEAVCRView@@PEAGPEAUtagVARIANT@@@Z>
extern __imp_?CRGetProgress@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z:PANYARGS
?CRGetProgress@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z TEXTEQU <__imp_?CRGetProgress@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z>
extern __imp_?CRGetRMDevice@@YA_NPEAVCRView@@PEAPEAUIUnknown@@PEAK@Z:PANYARGS
?CRGetRMDevice@@YA_NPEAVCRView@@PEAPEAUIUnknown@@PEAK@Z TEXTEQU <__imp_?CRGetRMDevice@@YA_NPEAVCRView@@PEAPEAUIUnknown@@PEAK@Z>
extern __imp_?CRGetRed@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PANYARGS
?CRGetRed@@YAPEAVCRNumber@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRGetRed@@YAPEAVCRNumber@@PEAVCRColor@@@Z>
extern __imp_?CRGetSaturation@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PANYARGS
?CRGetSaturation@@YAPEAVCRNumber@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRGetSaturation@@YAPEAVCRNumber@@PEAVCRColor@@@Z>
extern __imp_?CRGetServiceProvider@@YAPEAUIServiceProvider@@PEAVCRView@@@Z:PANYARGS
?CRGetServiceProvider@@YAPEAUIServiceProvider@@PEAVCRView@@@Z TEXTEQU <__imp_?CRGetServiceProvider@@YAPEAUIServiceProvider@@PEAVCRView@@@Z>
extern __imp_?CRGetSimulationTime@@YANPEAVCRView@@@Z:PANYARGS
?CRGetSimulationTime@@YANPEAVCRView@@@Z TEXTEQU <__imp_?CRGetSimulationTime@@YANPEAVCRView@@@Z>
extern __imp_?CRGetSite@@YAPEAVCRViewSite@@PEAVCRView@@@Z:PANYARGS
?CRGetSite@@YAPEAVCRViewSite@@PEAVCRView@@@Z TEXTEQU <__imp_?CRGetSite@@YAPEAVCRViewSite@@PEAVCRView@@@Z>
extern __imp_?CRGetSize@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z:PANYARGS
?CRGetSize@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z TEXTEQU <__imp_?CRGetSize@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z>
extern __imp_?CRGetSound@@YAPEAVCRSound@@PEAVCRImportationResult@@@Z:PANYARGS
?CRGetSound@@YAPEAVCRSound@@PEAVCRImportationResult@@@Z TEXTEQU <__imp_?CRGetSound@@YAPEAVCRSound@@PEAVCRImportationResult@@@Z>
extern __imp_?CRGetTransform@@YAPEAUIUnknown@@PEAVCRDXTransformResult@@@Z:PANYARGS
?CRGetTransform@@YAPEAUIUnknown@@PEAVCRDXTransformResult@@@Z TEXTEQU <__imp_?CRGetTransform@@YAPEAUIUnknown@@PEAVCRDXTransformResult@@@Z>
extern __imp_?CRGetTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z:PANYARGS
?CRGetTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z TEXTEQU <__imp_?CRGetTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z>
extern __imp_?CRGetWindow@@YAPEAUHWND__@@PEAVCRView@@@Z:PANYARGS
?CRGetWindow@@YAPEAUHWND__@@PEAVCRView@@@Z TEXTEQU <__imp_?CRGetWindow@@YAPEAUHWND__@@PEAVCRView@@@Z>
extern __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PANYARGS
?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z TEXTEQU <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>
extern __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PANYARGS
?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>
extern __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PANYARGS
?CRGetX@@YAPEAVCRNumber@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>
extern __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRGetX@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PANYARGS
?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z TEXTEQU <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>
extern __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PANYARGS
?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>
extern __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PANYARGS
?CRGetY@@YAPEAVCRNumber@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>
extern __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRGetY@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PANYARGS
?CRGetZ@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>
extern __imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRGetZ@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRGlobalTime@@YAPEAVCRNumber@@XZ:PANYARGS
?CRGlobalTime@@YAPEAVCRNumber@@XZ TEXTEQU <__imp_?CRGlobalTime@@YAPEAVCRNumber@@XZ>
extern __imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0N@Z:PANYARGS
?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0N@Z TEXTEQU <__imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0N@Z>
extern __imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z:PANYARGS
?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z TEXTEQU <__imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z>
extern __imp_?CRGradientPolygon@@YAPEAVCRImage@@PEAVCRArray@@0@Z:PANYARGS
?CRGradientPolygon@@YAPEAVCRImage@@PEAVCRArray@@0@Z TEXTEQU <__imp_?CRGradientPolygon@@YAPEAVCRImage@@PEAVCRArray@@0@Z>
extern __imp_?CRGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@000@Z:PANYARGS
?CRGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@000@Z TEXTEQU <__imp_?CRGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@000@Z>
extern __imp_?CRGray@@YAPEAVCRColor@@XZ:PANYARGS
?CRGray@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRGray@@YAPEAVCRColor@@XZ>
extern __imp_?CRGreen@@YAPEAVCRColor@@XZ:PANYARGS
?CRGreen@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRGreen@@YAPEAVCRColor@@XZ>
extern __imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PANYARGS
?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z TEXTEQU <__imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z>
extern __imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PANYARGS
?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>
extern __imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PANYARGS
?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z TEXTEQU <__imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z>
extern __imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PANYARGS
?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>
extern __imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PANYARGS
?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z TEXTEQU <__imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z>
extern __imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PANYARGS
?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>
extern __imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PANYARGS
?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z TEXTEQU <__imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z>
extern __imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PANYARGS
?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>
extern __imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PANYARGS
?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@N@Z TEXTEQU <__imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@N@Z>
extern __imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PANYARGS
?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>
extern __imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PANYARGS
?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@N@Z TEXTEQU <__imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@N@Z>
extern __imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PANYARGS
?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>
extern __imp_?CRHook@@YAPEAVCRBvr@@PEAV1@PEAVCRBvrHook@@@Z:PANYARGS
?CRHook@@YAPEAVCRBvr@@PEAV1@PEAVCRBvrHook@@@Z TEXTEQU <__imp_?CRHook@@YAPEAVCRBvr@@PEAV1@PEAVCRBvrHook@@@Z>
extern __imp_?CRIdentityTransform2@@YAPEAVCRTransform2@@XZ:PANYARGS
?CRIdentityTransform2@@YAPEAVCRTransform2@@XZ TEXTEQU <__imp_?CRIdentityTransform2@@YAPEAVCRTransform2@@XZ>
extern __imp_?CRIdentityTransform3@@YAPEAVCRTransform3@@XZ:PANYARGS
?CRIdentityTransform3@@YAPEAVCRTransform3@@XZ TEXTEQU <__imp_?CRIdentityTransform3@@YAPEAVCRTransform3@@XZ>
extern __imp_?CRImageMontage@@YAPEAVCRMontage@@PEAVCRImage@@N@Z:PANYARGS
?CRImageMontage@@YAPEAVCRMontage@@PEAVCRImage@@N@Z TEXTEQU <__imp_?CRImageMontage@@YAPEAVCRMontage@@PEAVCRImage@@N@Z>
extern __imp_?CRImageMontageAnim@@YAPEAVCRMontage@@PEAVCRImage@@PEAVCRNumber@@@Z:PANYARGS
?CRImageMontageAnim@@YAPEAVCRMontage@@PEAVCRImage@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRImageMontageAnim@@YAPEAVCRMontage@@PEAVCRImage@@PEAVCRNumber@@@Z>
extern __imp_?CRImageQuality@@YAPEAVCRImage@@PEAV1@K@Z:PANYARGS
?CRImageQuality@@YAPEAVCRImage@@PEAV1@K@Z TEXTEQU <__imp_?CRImageQuality@@YAPEAVCRImage@@PEAV1@K@Z>
extern __imp_?CRImportCancel@@YA_NPEAVCRBvr@@@Z:PANYARGS
?CRImportCancel@@YA_NPEAVCRBvr@@@Z TEXTEQU <__imp_?CRImportCancel@@YA_NPEAVCRBvr@@@Z>
extern __imp_?CRImportDirect3DRMVisual@@YAPEAVCRGeometry@@PEAUIUnknown@@@Z:PANYARGS
?CRImportDirect3DRMVisual@@YAPEAVCRGeometry@@PEAUIUnknown@@@Z TEXTEQU <__imp_?CRImportDirect3DRMVisual@@YAPEAVCRGeometry@@PEAUIUnknown@@@Z>
extern __imp_?CRImportDirect3DRMVisualWrapped@@YAPEAVCRGeometry@@PEAUIUnknown@@JNNNNNNNNNNNNNK@Z:PANYARGS
?CRImportDirect3DRMVisualWrapped@@YAPEAVCRGeometry@@PEAUIUnknown@@JNNNNNNNNNNNNNK@Z TEXTEQU <__imp_?CRImportDirect3DRMVisualWrapped@@YAPEAVCRGeometry@@PEAUIUnknown@@JNNNNNNNNNNNNNK@Z>
extern __imp_?CRImportDirectDrawSurface@@YAPEAVCRImage@@PEAUIUnknown@@PEAVCREvent@@@Z:PANYARGS
?CRImportDirectDrawSurface@@YAPEAVCRImage@@PEAUIUnknown@@PEAVCREvent@@@Z TEXTEQU <__imp_?CRImportDirectDrawSurface@@YAPEAVCRImage@@PEAUIUnknown@@PEAVCREvent@@@Z>
extern __imp_?CRImportGeometry@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6@Z:PANYARGS
?CRImportGeometry@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6@Z TEXTEQU <__imp_?CRImportGeometry@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6@Z>
extern __imp_?CRImportGeometryWrapped@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6JNNNNNNNNNNNNNK@Z:PANYARGS
?CRImportGeometryWrapped@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6JNNNNNNNNNNNNNK@Z TEXTEQU <__imp_?CRImportGeometryWrapped@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6JNNNNNNNNNNNNNK@Z>
extern __imp_?CRImportImage@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NEEEPEAVCRImage@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@7@Z:PANYARGS
?CRImportImage@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NEEEPEAVCRImage@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@7@Z TEXTEQU <__imp_?CRImportImage@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NEEEPEAVCRImage@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@7@Z>
extern __imp_?CRImportMedia@@YAPEAVCRImportationResult@@PEAGPEAXW4CR_MEDIA_SOURCE@@QEAPEAXKPEAVCRImportSite@@@Z:PANYARGS
?CRImportMedia@@YAPEAVCRImportationResult@@PEAGPEAXW4CR_MEDIA_SOURCE@@QEAPEAXKPEAVCRImportSite@@@Z TEXTEQU <__imp_?CRImportMedia@@YAPEAVCRImportationResult@@PEAGPEAXW4CR_MEDIA_SOURCE@@QEAPEAXKPEAVCRImportSite@@@Z>
extern __imp_?CRImportMovie@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRImage@@PEAVCRSound@@PEAPEAV3@PEAPEAV4@PEAPEAVCRNumber@@PEAPEAVCREvent@@88@Z:PANYARGS
?CRImportMovie@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRImage@@PEAVCRSound@@PEAPEAV3@PEAPEAV4@PEAPEAVCRNumber@@PEAPEAVCREvent@@88@Z TEXTEQU <__imp_?CRImportMovie@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRImage@@PEAVCRSound@@PEAPEAV3@PEAPEAV4@PEAPEAVCRNumber@@PEAPEAVCREvent@@88@Z>
extern __imp_?CRImportSound@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRSound@@PEAPEAV3@PEAPEAVCRNumber@@PEAPEAVCREvent@@66@Z:PANYARGS
?CRImportSound@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRSound@@PEAPEAV3@PEAPEAVCRNumber@@PEAPEAVCREvent@@66@Z TEXTEQU <__imp_?CRImportSound@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRSound@@PEAPEAV3@PEAPEAVCRNumber@@PEAPEAVCREvent@@66@Z>
extern __imp_?CRImportStatus@@YAJPEAVCRBvr@@@Z:PANYARGS
?CRImportStatus@@YAJPEAVCRBvr@@@Z TEXTEQU <__imp_?CRImportStatus@@YAJPEAVCRBvr@@@Z>
extern __imp_?CRImportance@@YAPEAVCRBvr@@PEAV1@N@Z:PANYARGS
?CRImportance@@YAPEAVCRBvr@@PEAV1@N@Z TEXTEQU <__imp_?CRImportance@@YAPEAVCRBvr@@PEAV1@N@Z>
extern __imp_?CRInit@@YA_NPEAVCRBvr@@0@Z:PANYARGS
?CRInit@@YA_NPEAVCRBvr@@0@Z TEXTEQU <__imp_?CRInit@@YA_NPEAVCRBvr@@0@Z>
extern __imp_?CRIntegral@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRIntegral@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRIntegral@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRIntegral@@YAPEAVCRVector2@@PEAV1@@Z:PANYARGS
?CRIntegral@@YAPEAVCRVector2@@PEAV1@@Z TEXTEQU <__imp_?CRIntegral@@YAPEAVCRVector2@@PEAV1@@Z>
extern __imp_?CRIntegral@@YAPEAVCRVector3@@PEAV1@@Z:PANYARGS
?CRIntegral@@YAPEAVCRVector3@@PEAV1@@Z TEXTEQU <__imp_?CRIntegral@@YAPEAVCRVector3@@PEAV1@@Z>
extern __imp_?CRInterpolate@@YAPEAVCRNumber@@NNN@Z:PANYARGS
?CRInterpolate@@YAPEAVCRNumber@@NNN@Z TEXTEQU <__imp_?CRInterpolate@@YAPEAVCRNumber@@NNN@Z>
extern __imp_?CRInterpolate@@YAPEAVCRNumber@@PEAV1@00@Z:PANYARGS
?CRInterpolate@@YAPEAVCRNumber@@PEAV1@00@Z TEXTEQU <__imp_?CRInterpolate@@YAPEAVCRNumber@@PEAV1@00@Z>
extern __imp_?CRIntersectMatte@@YAPEAVCRMatte@@PEAV1@0@Z:PANYARGS
?CRIntersectMatte@@YAPEAVCRMatte@@PEAV1@0@Z TEXTEQU <__imp_?CRIntersectMatte@@YAPEAVCRMatte@@PEAV1@0@Z>
extern __imp_?CRInverse@@YAPEAVCRTransform2@@PEAV1@@Z:PANYARGS
?CRInverse@@YAPEAVCRTransform2@@PEAV1@@Z TEXTEQU <__imp_?CRInverse@@YAPEAVCRTransform2@@PEAV1@@Z>
extern __imp_?CRInverse@@YAPEAVCRTransform3@@PEAV1@@Z:PANYARGS
?CRInverse@@YAPEAVCRTransform3@@PEAV1@@Z TEXTEQU <__imp_?CRInverse@@YAPEAVCRTransform3@@PEAV1@@Z>
extern __imp_?CRIsConnected@@YA_NPEAUHINSTANCE__@@@Z:PANYARGS
?CRIsConnected@@YA_NPEAUHINSTANCE__@@@Z TEXTEQU <__imp_?CRIsConnected@@YA_NPEAUHINSTANCE__@@@Z>
extern __imp_?CRIsConstantBvr@@YA_NPEAVCRBvr@@@Z:PANYARGS
?CRIsConstantBvr@@YA_NPEAVCRBvr@@@Z TEXTEQU <__imp_?CRIsConstantBvr@@YA_NPEAVCRBvr@@@Z>
extern __imp_?CRIsImport@@YA_NPEAVCRBvr@@@Z:PANYARGS
?CRIsImport@@YA_NPEAVCRBvr@@@Z TEXTEQU <__imp_?CRIsImport@@YA_NPEAVCRBvr@@@Z>
extern __imp_?CRIsModifiableBvr@@YA_NPEAVCRBvr@@@Z:PANYARGS
?CRIsModifiableBvr@@YA_NPEAVCRBvr@@@Z TEXTEQU <__imp_?CRIsModifiableBvr@@YA_NPEAVCRBvr@@@Z>
extern __imp_?CRIsReady@@YA_NPEAVCRBvr@@_N@Z:PANYARGS
?CRIsReady@@YA_NPEAVCRBvr@@_N@Z TEXTEQU <__imp_?CRIsReady@@YA_NPEAVCRBvr@@_N@Z>
extern __imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform2@@@Z:PANYARGS
?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform2@@@Z TEXTEQU <__imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform2@@@Z>
extern __imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform3@@@Z:PANYARGS
?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform3@@@Z>
extern __imp_?CRItalic@@YAPEAVCRFontStyle@@PEAV1@@Z:PANYARGS
?CRItalic@@YAPEAVCRFontStyle@@PEAV1@@Z TEXTEQU <__imp_?CRItalic@@YAPEAVCRFontStyle@@PEAV1@@Z>
extern __imp_?CRJoin@@YAPEAVCRLineStyle@@PEAV1@PEAVCRJoinStyle@@@Z:PANYARGS
?CRJoin@@YAPEAVCRLineStyle@@PEAV1@PEAVCRJoinStyle@@@Z TEXTEQU <__imp_?CRJoin@@YAPEAVCRLineStyle@@PEAV1@PEAVCRJoinStyle@@@Z>
extern __imp_?CRJoinEx@@YAPEAVCRLineStyle@@PEAV1@K@Z:PANYARGS
?CRJoinEx@@YAPEAVCRLineStyle@@PEAV1@K@Z TEXTEQU <__imp_?CRJoinEx@@YAPEAVCRLineStyle@@PEAV1@K@Z>
extern __imp_?CRJoinStyleBevel@@YAPEAVCRJoinStyle@@XZ:PANYARGS
?CRJoinStyleBevel@@YAPEAVCRJoinStyle@@XZ TEXTEQU <__imp_?CRJoinStyleBevel@@YAPEAVCRJoinStyle@@XZ>
extern __imp_?CRJoinStyleMiter@@YAPEAVCRJoinStyle@@XZ:PANYARGS
?CRJoinStyleMiter@@YAPEAVCRJoinStyle@@XZ TEXTEQU <__imp_?CRJoinStyleMiter@@YAPEAVCRJoinStyle@@XZ>
extern __imp_?CRJoinStyleRound@@YAPEAVCRJoinStyle@@XZ:PANYARGS
?CRJoinStyleRound@@YAPEAVCRJoinStyle@@XZ TEXTEQU <__imp_?CRJoinStyleRound@@YAPEAVCRJoinStyle@@XZ>
extern __imp_?CRKeyDown@@YAPEAVCREvent@@J@Z:PANYARGS
?CRKeyDown@@YAPEAVCREvent@@J@Z TEXTEQU <__imp_?CRKeyDown@@YAPEAVCREvent@@J@Z>
extern __imp_?CRKeyState@@YAPEAVCRBoolean@@PEAVCRNumber@@@Z:PANYARGS
?CRKeyState@@YAPEAVCRBoolean@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRKeyState@@YAPEAVCRBoolean@@PEAVCRNumber@@@Z>
extern __imp_?CRKeyUp@@YAPEAVCREvent@@J@Z:PANYARGS
?CRKeyUp@@YAPEAVCREvent@@J@Z TEXTEQU <__imp_?CRKeyUp@@YAPEAVCREvent@@J@Z>
extern __imp_?CRLT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PANYARGS
?CRLT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRLT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>
extern __imp_?CRLTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PANYARGS
?CRLTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRLTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>
extern __imp_?CRLeftButtonDown@@YAPEAVCREvent@@XZ:PANYARGS
?CRLeftButtonDown@@YAPEAVCREvent@@XZ TEXTEQU <__imp_?CRLeftButtonDown@@YAPEAVCREvent@@XZ>
extern __imp_?CRLeftButtonState@@YAPEAVCRBoolean@@XZ:PANYARGS
?CRLeftButtonState@@YAPEAVCRBoolean@@XZ TEXTEQU <__imp_?CRLeftButtonState@@YAPEAVCRBoolean@@XZ>
extern __imp_?CRLeftButtonUp@@YAPEAVCREvent@@XZ:PANYARGS
?CRLeftButtonUp@@YAPEAVCREvent@@XZ TEXTEQU <__imp_?CRLeftButtonUp@@YAPEAVCREvent@@XZ>
extern __imp_?CRLength@@YAJPEAVCRTuple@@@Z:PANYARGS
?CRLength@@YAJPEAVCRTuple@@@Z TEXTEQU <__imp_?CRLength@@YAJPEAVCRTuple@@@Z>
extern __imp_?CRLength@@YAPEAVCRNumber@@PEAVCRArray@@@Z:PANYARGS
?CRLength@@YAPEAVCRNumber@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRLength@@YAPEAVCRNumber@@PEAVCRArray@@@Z>
extern __imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PANYARGS
?CRLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>
extern __imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PANYARGS
?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>
extern __imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@NNN@Z:PANYARGS
?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@NNN@Z TEXTEQU <__imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@NNN@Z>
extern __imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@11@Z:PANYARGS
?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@11@Z TEXTEQU <__imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@11@Z>
extern __imp_?CRLightColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CRLightColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CRLightColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@N@Z:PANYARGS
?CRLightRange@@YAPEAVCRGeometry@@PEAV1@N@Z TEXTEQU <__imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@N@Z>
extern __imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRLightRange@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRLighting@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z:PANYARGS
?CRLighting@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z TEXTEQU <__imp_?CRLighting@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z>
extern __imp_?CRLime@@YAPEAVCRColor@@XZ:PANYARGS
?CRLime@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRLime@@YAPEAVCRColor@@XZ>
extern __imp_?CRLine@@YAPEAVCRPath2@@PEAVCRPoint2@@0@Z:PANYARGS
?CRLine@@YAPEAVCRPath2@@PEAVCRPoint2@@0@Z TEXTEQU <__imp_?CRLine@@YAPEAVCRPath2@@PEAVCRPoint2@@0@Z>
extern __imp_?CRLineColor@@YAPEAVCRLineStyle@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CRLineColor@@YAPEAVCRLineStyle@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CRLineColor@@YAPEAVCRLineStyle@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CRLinearGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z:PANYARGS
?CRLinearGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z TEXTEQU <__imp_?CRLinearGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z>
extern __imp_?CRLn@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRLn@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRLn@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRLocalTime@@YAPEAVCRNumber@@XZ:PANYARGS
?CRLocalTime@@YAPEAVCRNumber@@XZ TEXTEQU <__imp_?CRLocalTime@@YAPEAVCRNumber@@XZ>
extern __imp_?CRLog10@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRLog10@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRLog10@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRLookAtFrom@@YAPEAVCRTransform3@@PEAVCRPoint3@@0PEAVCRVector3@@@Z:PANYARGS
?CRLookAtFrom@@YAPEAVCRTransform3@@PEAVCRPoint3@@0PEAVCRVector3@@@Z TEXTEQU <__imp_?CRLookAtFrom@@YAPEAVCRTransform3@@PEAVCRPoint3@@0PEAVCRVector3@@@Z>
extern __imp_?CRLoop@@YAPEAVCRSound@@PEAV1@@Z:PANYARGS
?CRLoop@@YAPEAVCRSound@@PEAV1@@Z TEXTEQU <__imp_?CRLoop@@YAPEAVCRSound@@PEAV1@@Z>
extern __imp_?CRMagenta@@YAPEAVCRColor@@XZ:PANYARGS
?CRMagenta@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRMagenta@@YAPEAVCRColor@@XZ>
extern __imp_?CRMapToUnitSquare@@YAPEAVCRImage@@PEAV1@@Z:PANYARGS
?CRMapToUnitSquare@@YAPEAVCRImage@@PEAV1@@Z TEXTEQU <__imp_?CRMapToUnitSquare@@YAPEAVCRImage@@PEAV1@@Z>
extern __imp_?CRMaroon@@YAPEAVCRColor@@XZ:PANYARGS
?CRMaroon@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRMaroon@@YAPEAVCRColor@@XZ>
extern __imp_?CRMax@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z:PANYARGS
?CRMax@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z TEXTEQU <__imp_?CRMax@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z>
extern __imp_?CRMax@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z:PANYARGS
?CRMax@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z TEXTEQU <__imp_?CRMax@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z>
extern __imp_?CRMin@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z:PANYARGS
?CRMin@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z TEXTEQU <__imp_?CRMin@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z>
extern __imp_?CRMin@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z:PANYARGS
?CRMin@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z TEXTEQU <__imp_?CRMin@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z>
extern __imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@N@Z:PANYARGS
?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@N@Z TEXTEQU <__imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@N@Z>
extern __imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRMix@@YAPEAVCRSound@@PEAV1@0@Z:PANYARGS
?CRMix@@YAPEAVCRSound@@PEAV1@0@Z TEXTEQU <__imp_?CRMix@@YAPEAVCRSound@@PEAV1@0@Z>
extern __imp_?CRMix@@YAPEAVCRSound@@PEAVCRArray@@@Z:PANYARGS
?CRMix@@YAPEAVCRSound@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRMix@@YAPEAVCRSound@@PEAVCRArray@@@Z>
extern __imp_?CRMod@@YAPEAVCRNumber@@PEAV1@0@Z:PANYARGS
?CRMod@@YAPEAVCRNumber@@PEAV1@0@Z TEXTEQU <__imp_?CRMod@@YAPEAVCRNumber@@PEAV1@0@Z>
extern __imp_?CRModelClip@@YAPEAVCRGeometry@@PEAV1@PEAVCRPoint3@@PEAVCRVector3@@@Z:PANYARGS
?CRModelClip@@YAPEAVCRGeometry@@PEAV1@PEAVCRPoint3@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRModelClip@@YAPEAVCRGeometry@@PEAV1@PEAVCRPoint3@@PEAVCRVector3@@@Z>
extern __imp_?CRModifiableBvr@@YAPEAVCRBvr@@PEAV1@K@Z:PANYARGS
?CRModifiableBvr@@YAPEAVCRBvr@@PEAV1@K@Z TEXTEQU <__imp_?CRModifiableBvr@@YAPEAVCRBvr@@PEAV1@K@Z>
extern __imp_?CRModifiableNumber@@YAPEAVCRNumber@@N@Z:PANYARGS
?CRModifiableNumber@@YAPEAVCRNumber@@N@Z TEXTEQU <__imp_?CRModifiableNumber@@YAPEAVCRNumber@@N@Z>
extern __imp_?CRModifiableString@@YAPEAVCRString@@PEAG@Z:PANYARGS
?CRModifiableString@@YAPEAVCRString@@PEAG@Z TEXTEQU <__imp_?CRModifiableString@@YAPEAVCRString@@PEAG@Z>
extern __imp_?CRMousePosition@@YAPEAVCRPoint2@@XZ:PANYARGS
?CRMousePosition@@YAPEAVCRPoint2@@XZ TEXTEQU <__imp_?CRMousePosition@@YAPEAVCRPoint2@@XZ>
extern __imp_?CRMul@@YAPEAVCRNumber@@PEAV1@0@Z:PANYARGS
?CRMul@@YAPEAVCRNumber@@PEAV1@0@Z TEXTEQU <__imp_?CRMul@@YAPEAVCRNumber@@PEAV1@0@Z>
extern __imp_?CRMul@@YAPEAVCRVector2@@PEAV1@N@Z:PANYARGS
?CRMul@@YAPEAVCRVector2@@PEAV1@N@Z TEXTEQU <__imp_?CRMul@@YAPEAVCRVector2@@PEAV1@N@Z>
extern __imp_?CRMul@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRMul@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRMul@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRMul@@YAPEAVCRVector3@@PEAV1@N@Z:PANYARGS
?CRMul@@YAPEAVCRVector3@@PEAV1@N@Z TEXTEQU <__imp_?CRMul@@YAPEAVCRVector3@@PEAV1@N@Z>
extern __imp_?CRMul@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRMul@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRMul@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRNE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PANYARGS
?CRNE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRNE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>
extern __imp_?CRNavy@@YAPEAVCRColor@@XZ:PANYARGS
?CRNavy@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRNavy@@YAPEAVCRColor@@XZ>
extern __imp_?CRNeg@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRNeg@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRNeg@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRNeg@@YAPEAVCRVector2@@PEAV1@@Z:PANYARGS
?CRNeg@@YAPEAVCRVector2@@PEAV1@@Z TEXTEQU <__imp_?CRNeg@@YAPEAVCRVector2@@PEAV1@@Z>
extern __imp_?CRNeg@@YAPEAVCRVector3@@PEAV1@@Z:PANYARGS
?CRNeg@@YAPEAVCRVector3@@PEAV1@@Z TEXTEQU <__imp_?CRNeg@@YAPEAVCRVector3@@PEAV1@@Z>
extern __imp_?CRNever@@YAPEAVCREvent@@XZ:PANYARGS
?CRNever@@YAPEAVCREvent@@XZ TEXTEQU <__imp_?CRNever@@YAPEAVCREvent@@XZ>
extern __imp_?CRNormalize@@YAPEAVCRVector2@@PEAV1@@Z:PANYARGS
?CRNormalize@@YAPEAVCRVector2@@PEAV1@@Z TEXTEQU <__imp_?CRNormalize@@YAPEAVCRVector2@@PEAV1@@Z>
extern __imp_?CRNormalize@@YAPEAVCRVector3@@PEAV1@@Z:PANYARGS
?CRNormalize@@YAPEAVCRVector3@@PEAV1@@Z TEXTEQU <__imp_?CRNormalize@@YAPEAVCRVector3@@PEAV1@@Z>
extern __imp_?CRNot@@YAPEAVCRBoolean@@PEAV1@@Z:PANYARGS
?CRNot@@YAPEAVCRBoolean@@PEAV1@@Z TEXTEQU <__imp_?CRNot@@YAPEAVCRBoolean@@PEAV1@@Z>
extern __imp_?CRNotEvent@@YAPEAVCREvent@@PEAV1@@Z:PANYARGS
?CRNotEvent@@YAPEAVCREvent@@PEAV1@@Z TEXTEQU <__imp_?CRNotEvent@@YAPEAVCREvent@@PEAV1@@Z>
extern __imp_?CRNotify@@YAPEAVCREvent@@PEAV1@PEAVCRUntilNotifier@@@Z:PANYARGS
?CRNotify@@YAPEAVCREvent@@PEAV1@PEAVCRUntilNotifier@@@Z TEXTEQU <__imp_?CRNotify@@YAPEAVCREvent@@PEAV1@PEAVCRUntilNotifier@@@Z>
extern __imp_?CRNth@@YAPEAVCRBvr@@PEAVCRArray@@PEAVCRNumber@@@Z:PANYARGS
?CRNth@@YAPEAVCRBvr@@PEAVCRArray@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRNth@@YAPEAVCRBvr@@PEAVCRArray@@PEAVCRNumber@@@Z>
extern __imp_?CRNth@@YAPEAVCRBvr@@PEAVCRTuple@@J@Z:PANYARGS
?CRNth@@YAPEAVCRBvr@@PEAVCRTuple@@J@Z TEXTEQU <__imp_?CRNth@@YAPEAVCRBvr@@PEAVCRTuple@@J@Z>
extern __imp_?CROlive@@YAPEAVCRColor@@XZ:PANYARGS
?CROlive@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CROlive@@YAPEAVCRColor@@XZ>
extern __imp_?CROnFocus@@YA_NPEAVCRView@@_N@Z:PANYARGS
?CROnFocus@@YA_NPEAVCRView@@_N@Z TEXTEQU <__imp_?CROnFocus@@YA_NPEAVCRView@@_N@Z>
extern __imp_?CROnKey@@YA_NPEAVCRView@@NJ_NE@Z:PANYARGS
?CROnKey@@YA_NPEAVCRView@@NJ_NE@Z TEXTEQU <__imp_?CROnKey@@YA_NPEAVCRView@@NJ_NE@Z>
extern __imp_?CROnMouseButton@@YA_NPEAVCRView@@NJJE_NE@Z:PANYARGS
?CROnMouseButton@@YA_NPEAVCRView@@NJJE_NE@Z TEXTEQU <__imp_?CROnMouseButton@@YA_NPEAVCRView@@NJJE_NE@Z>
extern __imp_?CROnMouseLeave@@YA_NPEAVCRView@@N@Z:PANYARGS
?CROnMouseLeave@@YA_NPEAVCRView@@N@Z TEXTEQU <__imp_?CROnMouseLeave@@YA_NPEAVCRView@@N@Z>
extern __imp_?CROnMouseMove@@YA_NPEAVCRView@@NJJE@Z:PANYARGS
?CROnMouseMove@@YA_NPEAVCRView@@NJJE@Z TEXTEQU <__imp_?CROnMouseMove@@YA_NPEAVCRView@@NJJE@Z>
extern __imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@N@Z:PANYARGS
?CROpacity@@YAPEAVCRGeometry@@PEAV1@N@Z TEXTEQU <__imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@N@Z>
extern __imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CROpacity@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CROpacity@@YAPEAVCRImage@@PEAV1@N@Z:PANYARGS
?CROpacity@@YAPEAVCRImage@@PEAV1@N@Z TEXTEQU <__imp_?CROpacity@@YAPEAVCRImage@@PEAV1@N@Z>
extern __imp_?CROpacity@@YAPEAVCRImage@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CROpacity@@YAPEAVCRImage@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CROpacity@@YAPEAVCRImage@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CROpaqueMatte@@YAPEAVCRMatte@@XZ:PANYARGS
?CROpaqueMatte@@YAPEAVCRMatte@@XZ TEXTEQU <__imp_?CROpaqueMatte@@YAPEAVCRMatte@@XZ>
extern __imp_?CROr@@YAPEAVCRBoolean@@PEAV1@0@Z:PANYARGS
?CROr@@YAPEAVCRBoolean@@PEAV1@0@Z TEXTEQU <__imp_?CROr@@YAPEAVCRBoolean@@PEAV1@0@Z>
extern __imp_?CROrEvent@@YAPEAVCREvent@@PEAV1@0@Z:PANYARGS
?CROrEvent@@YAPEAVCREvent@@PEAV1@0@Z TEXTEQU <__imp_?CROrEvent@@YAPEAVCREvent@@PEAV1@0@Z>
extern __imp_?CROrigin2@@YAPEAVCRPoint2@@XZ:PANYARGS
?CROrigin2@@YAPEAVCRPoint2@@XZ TEXTEQU <__imp_?CROrigin2@@YAPEAVCRPoint2@@XZ>
extern __imp_?CROrigin3@@YAPEAVCRPoint3@@XZ:PANYARGS
?CROrigin3@@YAPEAVCRPoint3@@XZ TEXTEQU <__imp_?CROrigin3@@YAPEAVCRPoint3@@XZ>
extern __imp_?CROval@@YAPEAVCRPath2@@NN@Z:PANYARGS
?CROval@@YAPEAVCRPath2@@NN@Z TEXTEQU <__imp_?CROval@@YAPEAVCRPath2@@NN@Z>
extern __imp_?CROval@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z:PANYARGS
?CROval@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CROval@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z>
extern __imp_?CROverlay@@YAPEAVCRImage@@PEAV1@0@Z:PANYARGS
?CROverlay@@YAPEAVCRImage@@PEAV1@0@Z TEXTEQU <__imp_?CROverlay@@YAPEAVCRImage@@PEAV1@0@Z>
extern __imp_?CROverlay@@YAPEAVCRImage@@PEAVCRArray@@@Z:PANYARGS
?CROverlay@@YAPEAVCRImage@@PEAVCRArray@@@Z TEXTEQU <__imp_?CROverlay@@YAPEAVCRImage@@PEAVCRArray@@@Z>
extern __imp_?CRPan@@YAPEAVCRSound@@PEAV1@N@Z:PANYARGS
?CRPan@@YAPEAVCRSound@@PEAV1@N@Z TEXTEQU <__imp_?CRPan@@YAPEAVCRSound@@PEAV1@N@Z>
extern __imp_?CRPan@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRPan@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRPan@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRParallelCamera@@YAPEAVCRCamera@@N@Z:PANYARGS
?CRParallelCamera@@YAPEAVCRCamera@@N@Z TEXTEQU <__imp_?CRParallelCamera@@YAPEAVCRCamera@@N@Z>
extern __imp_?CRParallelCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@@Z:PANYARGS
?CRParallelCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRParallelCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@@Z>
extern __imp_?CRParallelTransform2@@YAPEAVCRTransform2@@PEAVCRTransform3@@@Z:PANYARGS
?CRParallelTransform2@@YAPEAVCRTransform2@@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRParallelTransform2@@YAPEAVCRTransform2@@PEAVCRTransform3@@@Z>
extern __imp_?CRPauseModel@@YA_NPEAVCRView@@@Z:PANYARGS
?CRPauseModel@@YA_NPEAVCRView@@@Z TEXTEQU <__imp_?CRPauseModel@@YA_NPEAVCRView@@@Z>
extern __imp_?CRPerspectiveCamera@@YAPEAVCRCamera@@NN@Z:PANYARGS
?CRPerspectiveCamera@@YAPEAVCRCamera@@NN@Z TEXTEQU <__imp_?CRPerspectiveCamera@@YAPEAVCRCamera@@NN@Z>
extern __imp_?CRPerspectiveCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@0@Z:PANYARGS
?CRPerspectiveCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRPerspectiveCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@0@Z>
extern __imp_?CRPhase@@YAPEAVCRSound@@PEAV1@N@Z:PANYARGS
?CRPhase@@YAPEAVCRSound@@PEAV1@N@Z TEXTEQU <__imp_?CRPhase@@YAPEAVCRSound@@PEAV1@N@Z>
extern __imp_?CRPhase@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRPhase@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRPhase@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z:PANYARGS
?CRPickable@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z TEXTEQU <__imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z>
extern __imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z:PANYARGS
?CRPickable@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z TEXTEQU <__imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z>
extern __imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z:PANYARGS
?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z TEXTEQU <__imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z>
extern __imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z:PANYARGS
?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z TEXTEQU <__imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z>
extern __imp_?CRPie@@YAPEAVCRPath2@@NNNN@Z:PANYARGS
?CRPie@@YAPEAVCRPath2@@NNNN@Z TEXTEQU <__imp_?CRPie@@YAPEAVCRPath2@@NNNN@Z>
extern __imp_?CRPieRadians@@YAPEAVCRPath2@@NNNN@Z:PANYARGS
?CRPieRadians@@YAPEAVCRPath2@@NNNN@Z TEXTEQU <__imp_?CRPieRadians@@YAPEAVCRPath2@@NNNN@Z>
extern __imp_?CRPieRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z:PANYARGS
?CRPieRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z TEXTEQU <__imp_?CRPieRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z>
extern __imp_?CRPixel@@YAPEAVCRNumber@@XZ:PANYARGS
?CRPixel@@YAPEAVCRNumber@@XZ TEXTEQU <__imp_?CRPixel@@YAPEAVCRNumber@@XZ>
extern __imp_?CRPoint2Polar@@YAPEAVCRPoint2@@NN@Z:PANYARGS
?CRPoint2Polar@@YAPEAVCRPoint2@@NN@Z TEXTEQU <__imp_?CRPoint2Polar@@YAPEAVCRPoint2@@NN@Z>
extern __imp_?CRPoint2Polar@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z:PANYARGS
?CRPoint2Polar@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRPoint2Polar@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z>
extern __imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@NNN@Z:PANYARGS
?CRPoint3Spherical@@YAPEAVCRPoint3@@NNN@Z TEXTEQU <__imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@NNN@Z>
extern __imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z:PANYARGS
?CRPoint3Spherical@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z>
extern __imp_?CRPointLight@@YAPEAVCRGeometry@@XZ:PANYARGS
?CRPointLight@@YAPEAVCRGeometry@@XZ TEXTEQU <__imp_?CRPointLight@@YAPEAVCRGeometry@@XZ>
extern __imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PANYARGS
?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z TEXTEQU <__imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>
extern __imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PANYARGS
?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>
extern __imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PANYARGS
?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z TEXTEQU <__imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>
extern __imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PANYARGS
?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>
extern __imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEANI0I@Z:PANYARGS
?CRPolydrawPath@@YAPEAVCRPath2@@PEANI0I@Z TEXTEQU <__imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEANI0I@Z>
extern __imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z:PANYARGS
?CRPolydrawPath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z TEXTEQU <__imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z>
extern __imp_?CRPolyline@@YAPEAVCRPath2@@PEAVCRArray@@@Z:PANYARGS
?CRPolyline@@YAPEAVCRPath2@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRPolyline@@YAPEAVCRPath2@@PEAVCRArray@@@Z>
extern __imp_?CRPow@@YAPEAVCRNumber@@PEAV1@0@Z:PANYARGS
?CRPow@@YAPEAVCRNumber@@PEAV1@0@Z TEXTEQU <__imp_?CRPow@@YAPEAVCRNumber@@PEAV1@0@Z>
extern __imp_?CRPredicate@@YAPEAVCREvent@@PEAVCRBoolean@@@Z:PANYARGS
?CRPredicate@@YAPEAVCREvent@@PEAVCRBoolean@@@Z TEXTEQU <__imp_?CRPredicate@@YAPEAVCREvent@@PEAVCRBoolean@@@Z>
extern __imp_?CRProject@@YAPEAVCRPoint2@@PEAVCRPoint3@@PEAVCRCamera@@@Z:PANYARGS
?CRProject@@YAPEAVCRPoint2@@PEAVCRPoint3@@PEAVCRCamera@@@Z TEXTEQU <__imp_?CRProject@@YAPEAVCRPoint2@@PEAVCRPoint3@@PEAVCRCamera@@@Z>
extern __imp_?CRPropagate@@YA_NPEAVCRView@@@Z:PANYARGS
?CRPropagate@@YA_NPEAVCRView@@@Z TEXTEQU <__imp_?CRPropagate@@YA_NPEAVCRView@@@Z>
extern __imp_?CRPurple@@YAPEAVCRColor@@XZ:PANYARGS
?CRPurple@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRPurple@@YAPEAVCRColor@@XZ>
extern __imp_?CRPutPreference@@YA_NPEAVCRView@@PEAGUtagVARIANT@@@Z:PANYARGS
?CRPutPreference@@YA_NPEAVCRView@@PEAGUtagVARIANT@@@Z TEXTEQU <__imp_?CRPutPreference@@YA_NPEAVCRView@@PEAGUtagVARIANT@@@Z>
extern __imp_?CRQueryHitPoint@@YAKPEAVCRView@@KPEBUtagRECT@@UtagPOINT@@J@Z:PANYARGS
?CRQueryHitPoint@@YAKPEAVCRView@@KPEBUtagRECT@@UtagPOINT@@J@Z TEXTEQU <__imp_?CRQueryHitPoint@@YAKPEAVCRView@@KPEBUtagRECT@@UtagPOINT@@J@Z>
extern __imp_?CRQueryHitPointEx@@YAJPEAVCRView@@JPEA_KPEANPEBUtagRECT@@UtagPOINT@@@Z:PANYARGS
?CRQueryHitPointEx@@YAJPEAVCRView@@JPEA_KPEANPEBUtagRECT@@UtagPOINT@@@Z TEXTEQU <__imp_?CRQueryHitPointEx@@YAJPEAVCRView@@JPEA_KPEANPEBUtagRECT@@UtagPOINT@@@Z>
extern __imp_?CRRadialGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z:PANYARGS
?CRRadialGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z TEXTEQU <__imp_?CRRadialGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z>
extern __imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@N@Z:PANYARGS
?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@N@Z TEXTEQU <__imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@N@Z>
extern __imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@PEAVCRNumber@@@Z:PANYARGS
?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@PEAVCRNumber@@@Z>
extern __imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0NN@Z:PANYARGS
?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0NN@Z TEXTEQU <__imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0NN@Z>
extern __imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@1@Z:PANYARGS
?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@1@Z TEXTEQU <__imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@1@Z>
extern __imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0N@Z:PANYARGS
?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0N@Z TEXTEQU <__imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0N@Z>
extern __imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z:PANYARGS
?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z TEXTEQU <__imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z>
extern __imp_?CRRate@@YAPEAVCRSound@@PEAV1@N@Z:PANYARGS
?CRRate@@YAPEAVCRSound@@PEAV1@N@Z TEXTEQU <__imp_?CRRate@@YAPEAVCRSound@@PEAV1@N@Z>
extern __imp_?CRRate@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRRate@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRRate@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRRay@@YAPEAVCRPath2@@PEAVCRPoint2@@@Z:PANYARGS
?CRRay@@YAPEAVCRPath2@@PEAVCRPoint2@@@Z TEXTEQU <__imp_?CRRay@@YAPEAVCRPath2@@PEAVCRPoint2@@@Z>
extern __imp_?CRRect@@YAPEAVCRPath2@@NN@Z:PANYARGS
?CRRect@@YAPEAVCRPath2@@NN@Z TEXTEQU <__imp_?CRRect@@YAPEAVCRPath2@@NN@Z>
extern __imp_?CRRect@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z:PANYARGS
?CRRect@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRRect@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z>
extern __imp_?CRRed@@YAPEAVCRColor@@XZ:PANYARGS
?CRRed@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRRed@@YAPEAVCRColor@@XZ>
extern __imp_?CRReleaseGC@@YA_NPEAX@Z:PANYARGS
?CRReleaseGC@@YA_NPEAX@Z TEXTEQU <__imp_?CRReleaseGC@@YA_NPEAX@Z>
extern __imp_?CRReleaseGCLock@@YA_NXZ:PANYARGS
?CRReleaseGCLock@@YA_NXZ TEXTEQU <__imp_?CRReleaseGCLock@@YA_NXZ>
extern __imp_?CRRemoveElement@@YA_NPEAVCRArray@@J@Z:PANYARGS
?CRRemoveElement@@YA_NPEAVCRArray@@J@Z TEXTEQU <__imp_?CRRemoveElement@@YA_NPEAVCRArray@@J@Z>
extern __imp_?CRRemoveRunningBvr@@YA_NPEAVCRView@@J@Z:PANYARGS
?CRRemoveRunningBvr@@YA_NPEAVCRView@@J@Z TEXTEQU <__imp_?CRRemoveRunningBvr@@YA_NPEAVCRView@@J@Z>
extern __imp_?CRRemoveSite@@YA_NPEAVCRSite@@@Z:PANYARGS
?CRRemoveSite@@YA_NPEAVCRSite@@@Z TEXTEQU <__imp_?CRRemoveSite@@YA_NPEAVCRSite@@@Z>
extern __imp_?CRRender@@YAPEAVCRImage@@PEAVCRGeometry@@PEAVCRCamera@@@Z:PANYARGS
?CRRender@@YAPEAVCRImage@@PEAVCRGeometry@@PEAVCRCamera@@@Z TEXTEQU <__imp_?CRRender@@YAPEAVCRImage@@PEAVCRGeometry@@PEAVCRCamera@@@Z>
extern __imp_?CRRender@@YAPEAVCRImage@@PEAVCRMontage@@@Z:PANYARGS
?CRRender@@YAPEAVCRImage@@PEAVCRMontage@@@Z TEXTEQU <__imp_?CRRender@@YAPEAVCRImage@@PEAVCRMontage@@@Z>
extern __imp_?CRRender@@YA_NPEAVCRView@@@Z:PANYARGS
?CRRender@@YA_NPEAVCRView@@@Z TEXTEQU <__imp_?CRRender@@YA_NPEAVCRView@@@Z>
extern __imp_?CRRenderResolution@@YAPEAVCRImage@@PEAV1@JJ@Z:PANYARGS
?CRRenderResolution@@YAPEAVCRImage@@PEAV1@JJ@Z TEXTEQU <__imp_?CRRenderResolution@@YAPEAVCRImage@@PEAV1@JJ@Z>
extern __imp_?CRRenderSound@@YAPEAVCRSound@@PEAVCRGeometry@@PEAVCRMicrophone@@@Z:PANYARGS
?CRRenderSound@@YAPEAVCRSound@@PEAVCRGeometry@@PEAVCRMicrophone@@@Z TEXTEQU <__imp_?CRRenderSound@@YAPEAVCRSound@@PEAVCRGeometry@@PEAVCRMicrophone@@@Z>
extern __imp_?CRRepaint@@YA_NPEAVCRView@@JJJJ@Z:PANYARGS
?CRRepaint@@YA_NPEAVCRView@@JJJJ@Z TEXTEQU <__imp_?CRRepaint@@YA_NPEAVCRView@@JJJJ@Z>
extern __imp_?CRRepeat@@YAPEAVCRBvr@@PEAV1@J@Z:PANYARGS
?CRRepeat@@YAPEAVCRBvr@@PEAV1@J@Z TEXTEQU <__imp_?CRRepeat@@YAPEAVCRBvr@@PEAV1@J@Z>
extern __imp_?CRRepeatForever@@YAPEAVCRBvr@@PEAV1@@Z:PANYARGS
?CRRepeatForever@@YAPEAVCRBvr@@PEAV1@@Z TEXTEQU <__imp_?CRRepeatForever@@YAPEAVCRBvr@@PEAV1@@Z>
extern __imp_?CRResumeModel@@YA_NPEAVCRView@@@Z:PANYARGS
?CRResumeModel@@YA_NPEAVCRView@@@Z TEXTEQU <__imp_?CRResumeModel@@YA_NPEAVCRView@@@Z>
extern __imp_?CRRightButtonDown@@YAPEAVCREvent@@XZ:PANYARGS
?CRRightButtonDown@@YAPEAVCREvent@@XZ TEXTEQU <__imp_?CRRightButtonDown@@YAPEAVCREvent@@XZ>
extern __imp_?CRRightButtonState@@YAPEAVCRBoolean@@XZ:PANYARGS
?CRRightButtonState@@YAPEAVCRBoolean@@XZ TEXTEQU <__imp_?CRRightButtonState@@YAPEAVCRBoolean@@XZ>
extern __imp_?CRRightButtonUp@@YAPEAVCREvent@@XZ:PANYARGS
?CRRightButtonUp@@YAPEAVCREvent@@XZ TEXTEQU <__imp_?CRRightButtonUp@@YAPEAVCREvent@@XZ>
extern __imp_?CRRotate2@@YAPEAVCRTransform2@@N@Z:PANYARGS
?CRRotate2@@YAPEAVCRTransform2@@N@Z TEXTEQU <__imp_?CRRotate2@@YAPEAVCRTransform2@@N@Z>
extern __imp_?CRRotate2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PANYARGS
?CRRotate2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRRotate2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>
extern __imp_?CRRotate2Degrees@@YAPEAVCRTransform2@@N@Z:PANYARGS
?CRRotate2Degrees@@YAPEAVCRTransform2@@N@Z TEXTEQU <__imp_?CRRotate2Degrees@@YAPEAVCRTransform2@@N@Z>
extern __imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@N@Z:PANYARGS
?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@N@Z TEXTEQU <__imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@N@Z>
extern __imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@PEAVCRNumber@@@Z:PANYARGS
?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@PEAVCRNumber@@@Z>
extern __imp_?CRRound@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRRound@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRRound@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRRoundRect@@YAPEAVCRPath2@@NNNN@Z:PANYARGS
?CRRoundRect@@YAPEAVCRPath2@@NNNN@Z TEXTEQU <__imp_?CRRoundRect@@YAPEAVCRPath2@@NNNN@Z>
extern __imp_?CRRoundRect@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z:PANYARGS
?CRRoundRect@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z TEXTEQU <__imp_?CRRoundRect@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z>
extern __imp_?CRRunOnce@@YAPEAVCRBvr@@PEAV1@@Z:PANYARGS
?CRRunOnce@@YAPEAVCRBvr@@PEAV1@@Z TEXTEQU <__imp_?CRRunOnce@@YAPEAVCRBvr@@PEAV1@@Z>
extern __imp_?CRSampleAtLocalTime@@YAPEAVCRBvr@@PEAV1@N@Z:PANYARGS
?CRSampleAtLocalTime@@YAPEAVCRBvr@@PEAV1@N@Z TEXTEQU <__imp_?CRSampleAtLocalTime@@YAPEAVCRBvr@@PEAV1@N@Z>
extern __imp_?CRScale2@@YAPEAVCRTransform2@@NN@Z:PANYARGS
?CRScale2@@YAPEAVCRTransform2@@NN@Z TEXTEQU <__imp_?CRScale2@@YAPEAVCRTransform2@@NN@Z>
extern __imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z:PANYARGS
?CRScale2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z>
extern __imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z:PANYARGS
?CRScale2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z>
extern __imp_?CRScale2Uniform@@YAPEAVCRTransform2@@N@Z:PANYARGS
?CRScale2Uniform@@YAPEAVCRTransform2@@N@Z TEXTEQU <__imp_?CRScale2Uniform@@YAPEAVCRTransform2@@N@Z>
extern __imp_?CRScale2Uniform@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PANYARGS
?CRScale2Uniform@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRScale2Uniform@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>
extern __imp_?CRScale3@@YAPEAVCRTransform3@@NNN@Z:PANYARGS
?CRScale3@@YAPEAVCRTransform3@@NNN@Z TEXTEQU <__imp_?CRScale3@@YAPEAVCRTransform3@@NNN@Z>
extern __imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z:PANYARGS
?CRScale3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z>
extern __imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z:PANYARGS
?CRScale3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z>
extern __imp_?CRScale3Uniform@@YAPEAVCRTransform3@@N@Z:PANYARGS
?CRScale3Uniform@@YAPEAVCRTransform3@@N@Z TEXTEQU <__imp_?CRScale3Uniform@@YAPEAVCRTransform3@@N@Z>
extern __imp_?CRScale3Uniform@@YAPEAVCRTransform3@@PEAVCRNumber@@@Z:PANYARGS
?CRScale3Uniform@@YAPEAVCRTransform3@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRScale3Uniform@@YAPEAVCRTransform3@@PEAVCRNumber@@@Z>
extern __imp_?CRSecond@@YAPEAVCRBvr@@PEAVCRPair@@@Z:PANYARGS
?CRSecond@@YAPEAVCRBvr@@PEAVCRPair@@@Z TEXTEQU <__imp_?CRSecond@@YAPEAVCRBvr@@PEAVCRPair@@@Z>
extern __imp_?CRSeededRandom@@YAPEAVCRNumber@@N@Z:PANYARGS
?CRSeededRandom@@YAPEAVCRNumber@@N@Z TEXTEQU <__imp_?CRSeededRandom@@YAPEAVCRNumber@@N@Z>
extern __imp_?CRSequence@@YAPEAVCRBvr@@PEAV1@0@Z:PANYARGS
?CRSequence@@YAPEAVCRBvr@@PEAV1@0@Z TEXTEQU <__imp_?CRSequence@@YAPEAVCRBvr@@PEAV1@0@Z>
extern __imp_?CRSequenceArray@@YAPEAVCRBvr@@JQEAPEAV1@@Z:PANYARGS
?CRSequenceArray@@YAPEAVCRBvr@@JQEAPEAV1@@Z TEXTEQU <__imp_?CRSequenceArray@@YAPEAVCRBvr@@JQEAPEAV1@@Z>
extern __imp_?CRSetBvrAsProperty@@YA_NPEAVCRDXTransformResult@@PEBGPEAVCRBvr@@@Z:PANYARGS
?CRSetBvrAsProperty@@YA_NPEAVCRDXTransformResult@@PEBGPEAVCRBvr@@@Z TEXTEQU <__imp_?CRSetBvrAsProperty@@YA_NPEAVCRDXTransformResult@@PEBGPEAVCRBvr@@@Z>
extern __imp_?CRSetClipRect@@YA_NPEAVCRView@@JJJJ@Z:PANYARGS
?CRSetClipRect@@YA_NPEAVCRView@@JJJJ@Z TEXTEQU <__imp_?CRSetClipRect@@YA_NPEAVCRView@@JJJJ@Z>
extern __imp_?CRSetCompositeDirectlyToTarget@@YA_NPEAVCRView@@_N@Z:PANYARGS
?CRSetCompositeDirectlyToTarget@@YA_NPEAVCRView@@_N@Z TEXTEQU <__imp_?CRSetCompositeDirectlyToTarget@@YA_NPEAVCRView@@_N@Z>
extern __imp_?CRSetDC@@YA_NPEAVCRView@@PEAUHDC__@@@Z:PANYARGS
?CRSetDC@@YA_NPEAVCRView@@PEAUHDC__@@@Z TEXTEQU <__imp_?CRSetDC@@YA_NPEAVCRView@@PEAUHDC__@@@Z>
extern __imp_?CRSetDirectDrawSurface@@YA_NPEAVCRView@@PEAUIUnknown@@@Z:PANYARGS
?CRSetDirectDrawSurface@@YA_NPEAVCRView@@PEAUIUnknown@@@Z TEXTEQU <__imp_?CRSetDirectDrawSurface@@YA_NPEAVCRView@@PEAUIUnknown@@@Z>
extern __imp_?CRSetElement@@YA_NPEAVCRArray@@JPEAVCRBvr@@J@Z:PANYARGS
?CRSetElement@@YA_NPEAVCRArray@@JPEAVCRBvr@@J@Z TEXTEQU <__imp_?CRSetElement@@YA_NPEAVCRArray@@JPEAVCRBvr@@J@Z>
extern __imp_?CRSetImportPriority@@YA_NPEAVCRBvr@@M@Z:PANYARGS
?CRSetImportPriority@@YA_NPEAVCRBvr@@M@Z TEXTEQU <__imp_?CRSetImportPriority@@YA_NPEAVCRBvr@@M@Z>
extern __imp_?CRSetLastError@@YAXJPEBG@Z:PANYARGS
?CRSetLastError@@YAXJPEBG@Z TEXTEQU <__imp_?CRSetLastError@@YAXJPEBG@Z>
extern __imp_?CRSetServiceProvider@@YA_NPEAVCRView@@PEAUIServiceProvider@@@Z:PANYARGS
?CRSetServiceProvider@@YA_NPEAVCRView@@PEAUIServiceProvider@@@Z TEXTEQU <__imp_?CRSetServiceProvider@@YA_NPEAVCRView@@PEAUIServiceProvider@@@Z>
extern __imp_?CRSetSite@@YA_NPEAVCRView@@PEAVCRViewSite@@@Z:PANYARGS
?CRSetSite@@YA_NPEAVCRView@@PEAVCRViewSite@@@Z TEXTEQU <__imp_?CRSetSite@@YA_NPEAVCRView@@PEAVCRViewSite@@@Z>
extern __imp_?CRSetViewport@@YA_NPEAVCRView@@JJJJ@Z:PANYARGS
?CRSetViewport@@YA_NPEAVCRView@@JJJJ@Z TEXTEQU <__imp_?CRSetViewport@@YA_NPEAVCRView@@JJJJ@Z>
extern __imp_?CRSetWindow@@YA_NPEAVCRView@@PEAUHWND__@@@Z:PANYARGS
?CRSetWindow@@YA_NPEAVCRView@@PEAUHWND__@@@Z TEXTEQU <__imp_?CRSetWindow@@YA_NPEAVCRView@@PEAUHWND__@@@Z>
extern __imp_?CRShadow@@YAPEAVCRGeometry@@PEAV1@0PEAVCRPoint3@@PEAVCRVector3@@@Z:PANYARGS
?CRShadow@@YAPEAVCRGeometry@@PEAV1@0PEAVCRPoint3@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRShadow@@YAPEAVCRGeometry@@PEAV1@0PEAVCRPoint3@@PEAVCRVector3@@@Z>
extern __imp_?CRSilence@@YAPEAVCRSound@@XZ:PANYARGS
?CRSilence@@YAPEAVCRSound@@XZ TEXTEQU <__imp_?CRSilence@@YAPEAVCRSound@@XZ>
extern __imp_?CRSilver@@YAPEAVCRColor@@XZ:PANYARGS
?CRSilver@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRSilver@@YAPEAVCRColor@@XZ>
extern __imp_?CRSin@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRSin@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRSin@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRSinSynth@@YAPEAVCRSound@@XZ:PANYARGS
?CRSinSynth@@YAPEAVCRSound@@XZ TEXTEQU <__imp_?CRSinSynth@@YAPEAVCRSound@@XZ>
extern __imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@N@Z:PANYARGS
?CRSize@@YAPEAVCRFontStyle@@PEAV1@N@Z TEXTEQU <__imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@N@Z>
extern __imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRSize@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@NNNN@Z:PANYARGS
?CRSlowInSlowOut@@YAPEAVCRNumber@@NNNN@Z TEXTEQU <__imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@NNNN@Z>
extern __imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@PEAV1@000@Z:PANYARGS
?CRSlowInSlowOut@@YAPEAVCRNumber@@PEAV1@000@Z TEXTEQU <__imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@PEAV1@000@Z>
extern __imp_?CRSnapshot@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z:PANYARGS
?CRSnapshot@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z TEXTEQU <__imp_?CRSnapshot@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z>
extern __imp_?CRSolidColorImage@@YAPEAVCRImage@@PEAVCRColor@@@Z:PANYARGS
?CRSolidColorImage@@YAPEAVCRImage@@PEAVCRColor@@@Z TEXTEQU <__imp_?CRSolidColorImage@@YAPEAVCRImage@@PEAVCRColor@@@Z>
extern __imp_?CRSoundSource@@YAPEAVCRGeometry@@PEAVCRSound@@@Z:PANYARGS
?CRSoundSource@@YAPEAVCRGeometry@@PEAVCRSound@@@Z TEXTEQU <__imp_?CRSoundSource@@YAPEAVCRGeometry@@PEAVCRSound@@@Z>
extern __imp_?CRSpecularColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CRSpecularColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CRSpecularColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CRSpecularExponent@@YAPEAVCRGeometry@@PEAV1@N@Z:PANYARGS
?CRSpecularExponent@@YAPEAVCRGeometry@@PEAV1@N@Z TEXTEQU <__imp_?CRSpecularExponent@@YAPEAVCRGeometry@@PEAV1@N@Z>
extern __imp_?CRSpecularExponentAnim@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRSpecularExponentAnim@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRSpecularExponentAnim@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PANYARGS
?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>
extern __imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PANYARGS
?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>
extern __imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PANYARGS
?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>
extern __imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PANYARGS
?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>
extern __imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@0@Z:PANYARGS
?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@0@Z>
extern __imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@N@Z:PANYARGS
?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@N@Z TEXTEQU <__imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@N@Z>
extern __imp_?CRSqrt@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRSqrt@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRSqrt@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRStartModel@@YA_NPEAVCRView@@PEAVCRImage@@PEAVCRSound@@NKPEA_N@Z:PANYARGS
?CRStartModel@@YA_NPEAVCRView@@PEAVCRImage@@PEAVCRSound@@NKPEA_N@Z TEXTEQU <__imp_?CRStartModel@@YA_NPEAVCRView@@PEAVCRImage@@PEAVCRSound@@NKPEA_N@Z>
extern __imp_?CRStopModel@@YA_NPEAVCRView@@@Z:PANYARGS
?CRStopModel@@YA_NPEAVCRView@@@Z TEXTEQU <__imp_?CRStopModel@@YA_NPEAVCRView@@@Z>
extern __imp_?CRStrikethrough@@YAPEAVCRFontStyle@@PEAV1@@Z:PANYARGS
?CRStrikethrough@@YAPEAVCRFontStyle@@PEAV1@@Z TEXTEQU <__imp_?CRStrikethrough@@YAPEAVCRFontStyle@@PEAV1@@Z>
extern __imp_?CRStringImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z:PANYARGS
?CRStringImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRStringImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z>
extern __imp_?CRStringImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z:PANYARGS
?CRStringImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRStringImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z>
extern __imp_?CRStringPath@@YAPEAVCRPath2@@PEAGPEAVCRFontStyle@@@Z:PANYARGS
?CRStringPath@@YAPEAVCRPath2@@PEAGPEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRStringPath@@YAPEAVCRPath2@@PEAGPEAVCRFontStyle@@@Z>
extern __imp_?CRStringPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z:PANYARGS
?CRStringPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRStringPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z>
extern __imp_?CRSub@@YAPEAVCRNumber@@PEAV1@0@Z:PANYARGS
?CRSub@@YAPEAVCRNumber@@PEAV1@0@Z TEXTEQU <__imp_?CRSub@@YAPEAVCRNumber@@PEAV1@0@Z>
extern __imp_?CRSub@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z:PANYARGS
?CRSub@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRSub@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z>
extern __imp_?CRSub@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z:PANYARGS
?CRSub@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRSub@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z>
extern __imp_?CRSub@@YAPEAVCRVector2@@PEAV1@0@Z:PANYARGS
?CRSub@@YAPEAVCRVector2@@PEAV1@0@Z TEXTEQU <__imp_?CRSub@@YAPEAVCRVector2@@PEAV1@0@Z>
extern __imp_?CRSub@@YAPEAVCRVector2@@PEAVCRPoint2@@0@Z:PANYARGS
?CRSub@@YAPEAVCRVector2@@PEAVCRPoint2@@0@Z TEXTEQU <__imp_?CRSub@@YAPEAVCRVector2@@PEAVCRPoint2@@0@Z>
extern __imp_?CRSub@@YAPEAVCRVector3@@PEAV1@0@Z:PANYARGS
?CRSub@@YAPEAVCRVector3@@PEAV1@0@Z TEXTEQU <__imp_?CRSub@@YAPEAVCRVector3@@PEAV1@0@Z>
extern __imp_?CRSub@@YAPEAVCRVector3@@PEAVCRPoint3@@0@Z:PANYARGS
?CRSub@@YAPEAVCRVector3@@PEAVCRPoint3@@0@Z TEXTEQU <__imp_?CRSub@@YAPEAVCRVector3@@PEAVCRPoint3@@0@Z>
extern __imp_?CRSubstituteTime@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRSubstituteTime@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRSubstituteTime@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRSwitchTo@@YA_NPEAVCRBvr@@0_NKN@Z:PANYARGS
?CRSwitchTo@@YA_NPEAVCRBvr@@0_NKN@Z TEXTEQU <__imp_?CRSwitchTo@@YA_NPEAVCRBvr@@0_NKN@Z>
extern __imp_?CRSwitchToBool@@YA_NPEAVCRBoolean@@_N@Z:PANYARGS
?CRSwitchToBool@@YA_NPEAVCRBoolean@@_N@Z TEXTEQU <__imp_?CRSwitchToBool@@YA_NPEAVCRBoolean@@_N@Z>
extern __imp_?CRSwitchToNumber@@YA_NPEAVCRNumber@@N@Z:PANYARGS
?CRSwitchToNumber@@YA_NPEAVCRNumber@@N@Z TEXTEQU <__imp_?CRSwitchToNumber@@YA_NPEAVCRNumber@@N@Z>
extern __imp_?CRSwitchToString@@YA_NPEAVCRString@@PEAG@Z:PANYARGS
?CRSwitchToString@@YA_NPEAVCRString@@PEAG@Z TEXTEQU <__imp_?CRSwitchToString@@YA_NPEAVCRString@@PEAG@Z>
extern __imp_?CRTan@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRTan@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRTan@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRTeal@@YAPEAVCRColor@@XZ:PANYARGS
?CRTeal@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRTeal@@YAPEAVCRColor@@XZ>
extern __imp_?CRTextColor@@YAPEAVCRFontStyle@@PEAV1@PEAVCRColor@@@Z:PANYARGS
?CRTextColor@@YAPEAVCRFontStyle@@PEAV1@PEAVCRColor@@@Z TEXTEQU <__imp_?CRTextColor@@YAPEAVCRFontStyle@@PEAV1@PEAVCRColor@@@Z>
extern __imp_?CRTextImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z:PANYARGS
?CRTextImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRTextImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z>
extern __imp_?CRTextImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z:PANYARGS
?CRTextImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRTextImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z>
extern __imp_?CRTextMatte@@YAPEAVCRMatte@@PEAVCRString@@PEAVCRFontStyle@@@Z:PANYARGS
?CRTextMatte@@YAPEAVCRMatte@@PEAVCRString@@PEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRTextMatte@@YAPEAVCRMatte@@PEAVCRString@@PEAVCRFontStyle@@@Z>
extern __imp_?CRTextPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z:PANYARGS
?CRTextPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z TEXTEQU <__imp_?CRTextPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z>
extern __imp_?CRTexture@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z:PANYARGS
?CRTexture@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z TEXTEQU <__imp_?CRTexture@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z>
extern __imp_?CRTextureImage@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z:PANYARGS
?CRTextureImage@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z TEXTEQU <__imp_?CRTextureImage@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z>
extern __imp_?CRThenEvent@@YAPEAVCREvent@@PEAV1@0@Z:PANYARGS
?CRThenEvent@@YAPEAVCREvent@@PEAV1@0@Z TEXTEQU <__imp_?CRThenEvent@@YAPEAVCREvent@@PEAV1@0@Z>
extern __imp_?CRTick@@YA_NPEAVCRView@@NPEA_N@Z:PANYARGS
?CRTick@@YA_NPEAVCRView@@NPEA_N@Z TEXTEQU <__imp_?CRTick@@YA_NPEAVCRView@@NPEA_N@Z>
extern __imp_?CRTile@@YAPEAVCRImage@@PEAV1@@Z:PANYARGS
?CRTile@@YAPEAVCRImage@@PEAV1@@Z TEXTEQU <__imp_?CRTile@@YAPEAVCRImage@@PEAV1@@Z>
extern __imp_?CRTimer@@YAPEAVCREvent@@N@Z:PANYARGS
?CRTimer@@YAPEAVCREvent@@N@Z TEXTEQU <__imp_?CRTimer@@YAPEAVCREvent@@N@Z>
extern __imp_?CRTimer@@YAPEAVCREvent@@PEAVCRNumber@@@Z:PANYARGS
?CRTimer@@YAPEAVCREvent@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRTimer@@YAPEAVCREvent@@PEAVCRNumber@@@Z>
extern __imp_?CRToDegrees@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRToDegrees@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRToDegrees@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRToRadians@@YAPEAVCRNumber@@PEAV1@@Z:PANYARGS
?CRToRadians@@YAPEAVCRNumber@@PEAV1@@Z TEXTEQU <__imp_?CRToRadians@@YAPEAVCRNumber@@PEAV1@@Z>
extern __imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@0@Z:PANYARGS
?CRToString@@YAPEAVCRString@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@0@Z>
extern __imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@N@Z:PANYARGS
?CRToString@@YAPEAVCRString@@PEAVCRNumber@@N@Z TEXTEQU <__imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@N@Z>
extern __imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEANI@Z:PANYARGS
?CRTransform3x2@@YAPEAVCRTransform2@@PEANI@Z TEXTEQU <__imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEANI@Z>
extern __imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z:PANYARGS
?CRTransform3x2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z>
extern __imp_?CRTransform4x4@@YAPEAVCRTransform3@@PEAVCRArray@@@Z:PANYARGS
?CRTransform4x4@@YAPEAVCRTransform3@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRTransform4x4@@YAPEAVCRTransform3@@PEAVCRArray@@@Z>
extern __imp_?CRTransform@@YAPEAVCRCamera@@PEAV1@PEAVCRTransform3@@@Z:PANYARGS
?CRTransform@@YAPEAVCRCamera@@PEAV1@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRCamera@@PEAV1@PEAVCRTransform3@@@Z>
extern __imp_?CRTransform@@YAPEAVCRGeometry@@PEAV1@PEAVCRTransform3@@@Z:PANYARGS
?CRTransform@@YAPEAVCRGeometry@@PEAV1@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRGeometry@@PEAV1@PEAVCRTransform3@@@Z>
extern __imp_?CRTransform@@YAPEAVCRImage@@PEAV1@PEAVCRTransform2@@@Z:PANYARGS
?CRTransform@@YAPEAVCRImage@@PEAV1@PEAVCRTransform2@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRImage@@PEAV1@PEAVCRTransform2@@@Z>
extern __imp_?CRTransform@@YAPEAVCRMatte@@PEAV1@PEAVCRTransform2@@@Z:PANYARGS
?CRTransform@@YAPEAVCRMatte@@PEAV1@PEAVCRTransform2@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRMatte@@PEAV1@PEAVCRTransform2@@@Z>
extern __imp_?CRTransform@@YAPEAVCRMicrophone@@PEAV1@PEAVCRTransform3@@@Z:PANYARGS
?CRTransform@@YAPEAVCRMicrophone@@PEAV1@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRMicrophone@@PEAV1@PEAVCRTransform3@@@Z>
extern __imp_?CRTransform@@YAPEAVCRPath2@@PEAV1@PEAVCRTransform2@@@Z:PANYARGS
?CRTransform@@YAPEAVCRPath2@@PEAV1@PEAVCRTransform2@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRPath2@@PEAV1@PEAVCRTransform2@@@Z>
extern __imp_?CRTransform@@YAPEAVCRPoint2@@PEAV1@PEAVCRTransform2@@@Z:PANYARGS
?CRTransform@@YAPEAVCRPoint2@@PEAV1@PEAVCRTransform2@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRPoint2@@PEAV1@PEAVCRTransform2@@@Z>
extern __imp_?CRTransform@@YAPEAVCRPoint3@@PEAV1@PEAVCRTransform3@@@Z:PANYARGS
?CRTransform@@YAPEAVCRPoint3@@PEAV1@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRPoint3@@PEAV1@PEAVCRTransform3@@@Z>
extern __imp_?CRTransform@@YAPEAVCRVector2@@PEAV1@PEAVCRTransform2@@@Z:PANYARGS
?CRTransform@@YAPEAVCRVector2@@PEAV1@PEAVCRTransform2@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRVector2@@PEAV1@PEAVCRTransform2@@@Z>
extern __imp_?CRTransform@@YAPEAVCRVector3@@PEAV1@PEAVCRTransform3@@@Z:PANYARGS
?CRTransform@@YAPEAVCRVector3@@PEAV1@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRTransform@@YAPEAVCRVector3@@PEAV1@PEAVCRTransform3@@@Z>
extern __imp_?CRTransformCharacters@@YAPEAVCRFontStyle@@PEAV1@PEAVCRTransform2@@@Z:PANYARGS
?CRTransformCharacters@@YAPEAVCRFontStyle@@PEAV1@PEAVCRTransform2@@@Z TEXTEQU <__imp_?CRTransformCharacters@@YAPEAVCRFontStyle@@PEAV1@PEAVCRTransform2@@@Z>
extern __imp_?CRTransformColorRGB@@YAPEAVCRImage@@PEAV1@PEAVCRTransform3@@@Z:PANYARGS
?CRTransformColorRGB@@YAPEAVCRImage@@PEAV1@PEAVCRTransform3@@@Z TEXTEQU <__imp_?CRTransformColorRGB@@YAPEAVCRImage@@PEAV1@PEAVCRTransform3@@@Z>
extern __imp_?CRTranslate2@@YAPEAVCRTransform2@@NN@Z:PANYARGS
?CRTranslate2@@YAPEAVCRTransform2@@NN@Z TEXTEQU <__imp_?CRTranslate2@@YAPEAVCRTransform2@@NN@Z>
extern __imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z:PANYARGS
?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z>
extern __imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRPoint2@@@Z:PANYARGS
?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRPoint2@@@Z TEXTEQU <__imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRPoint2@@@Z>
extern __imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z:PANYARGS
?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z TEXTEQU <__imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z>
extern __imp_?CRTranslate3@@YAPEAVCRTransform3@@NNN@Z:PANYARGS
?CRTranslate3@@YAPEAVCRTransform3@@NNN@Z TEXTEQU <__imp_?CRTranslate3@@YAPEAVCRTransform3@@NNN@Z>
extern __imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z:PANYARGS
?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z>
extern __imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRPoint3@@@Z:PANYARGS
?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRPoint3@@@Z TEXTEQU <__imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRPoint3@@@Z>
extern __imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z:PANYARGS
?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z TEXTEQU <__imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z>
extern __imp_?CRTriMesh@@YAPEAVCRGeometry@@AEAVTriMeshData@@@Z:PANYARGS
?CRTriMesh@@YAPEAVCRGeometry@@AEAVTriMeshData@@@Z TEXTEQU <__imp_?CRTriMesh@@YAPEAVCRGeometry@@AEAVTriMeshData@@@Z>
extern __imp_?CRTriggerEvent@@YA_NPEAVCREvent@@PEAVCRBvr@@@Z:PANYARGS
?CRTriggerEvent@@YA_NPEAVCREvent@@PEAVCRBvr@@@Z TEXTEQU <__imp_?CRTriggerEvent@@YA_NPEAVCREvent@@PEAVCRBvr@@@Z>
extern __imp_?CRTrue@@YAPEAVCRBoolean@@XZ:PANYARGS
?CRTrue@@YAPEAVCRBoolean@@XZ TEXTEQU <__imp_?CRTrue@@YAPEAVCRBoolean@@XZ>
extern __imp_?CRUnderline@@YAPEAVCRFontStyle@@PEAV1@@Z:PANYARGS
?CRUnderline@@YAPEAVCRFontStyle@@PEAV1@@Z TEXTEQU <__imp_?CRUnderline@@YAPEAVCRFontStyle@@PEAV1@@Z>
extern __imp_?CRUndetectable@@YAPEAVCRGeometry@@PEAV1@@Z:PANYARGS
?CRUndetectable@@YAPEAVCRGeometry@@PEAV1@@Z TEXTEQU <__imp_?CRUndetectable@@YAPEAVCRGeometry@@PEAV1@@Z>
extern __imp_?CRUndetectable@@YAPEAVCRImage@@PEAV1@@Z:PANYARGS
?CRUndetectable@@YAPEAVCRImage@@PEAV1@@Z TEXTEQU <__imp_?CRUndetectable@@YAPEAVCRImage@@PEAV1@@Z>
extern __imp_?CRUninitializedArray@@YAPEAVCRArray@@PEAV1@@Z:PANYARGS
?CRUninitializedArray@@YAPEAVCRArray@@PEAV1@@Z TEXTEQU <__imp_?CRUninitializedArray@@YAPEAVCRArray@@PEAV1@@Z>
extern __imp_?CRUninitializedBvr@@YAPEAVCRBvr@@W4CR_BVR_TYPEID@@@Z:PANYARGS
?CRUninitializedBvr@@YAPEAVCRBvr@@W4CR_BVR_TYPEID@@@Z TEXTEQU <__imp_?CRUninitializedBvr@@YAPEAVCRBvr@@W4CR_BVR_TYPEID@@@Z>
extern __imp_?CRUninitializedTuple@@YAPEAVCRTuple@@PEAV1@@Z:PANYARGS
?CRUninitializedTuple@@YAPEAVCRTuple@@PEAV1@@Z TEXTEQU <__imp_?CRUninitializedTuple@@YAPEAVCRTuple@@PEAV1@@Z>
extern __imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAV1@0@Z:PANYARGS
?CRUnionGeometry@@YAPEAVCRGeometry@@PEAV1@0@Z TEXTEQU <__imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAV1@0@Z>
extern __imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAVCRArray@@@Z:PANYARGS
?CRUnionGeometry@@YAPEAVCRGeometry@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAVCRArray@@@Z>
extern __imp_?CRUnionMatte@@YAPEAVCRMatte@@PEAV1@0@Z:PANYARGS
?CRUnionMatte@@YAPEAVCRMatte@@PEAV1@0@Z TEXTEQU <__imp_?CRUnionMatte@@YAPEAVCRMatte@@PEAV1@0@Z>
extern __imp_?CRUnionMontage@@YAPEAVCRMontage@@PEAV1@0@Z:PANYARGS
?CRUnionMontage@@YAPEAVCRMontage@@PEAV1@0@Z TEXTEQU <__imp_?CRUnionMontage@@YAPEAVCRMontage@@PEAV1@0@Z>
extern __imp_?CRUnionMontageArray@@YAPEAVCRMontage@@PEAVCRArray@@@Z:PANYARGS
?CRUnionMontageArray@@YAPEAVCRMontage@@PEAVCRArray@@@Z TEXTEQU <__imp_?CRUnionMontageArray@@YAPEAVCRMontage@@PEAVCRArray@@@Z>
extern __imp_?CRUntil@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@0@Z:PANYARGS
?CRUntil@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@0@Z TEXTEQU <__imp_?CRUntil@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@0@Z>
extern __imp_?CRUntilEx@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@@Z:PANYARGS
?CRUntilEx@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@@Z TEXTEQU <__imp_?CRUntilEx@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@@Z>
extern __imp_?CRUntilNotify@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@PEAVCRUntilNotifier@@@Z:PANYARGS
?CRUntilNotify@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@PEAVCRUntilNotifier@@@Z TEXTEQU <__imp_?CRUntilNotify@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@PEAVCRUntilNotifier@@@Z>
extern __imp_?CRVector2Polar@@YAPEAVCRVector2@@NN@Z:PANYARGS
?CRVector2Polar@@YAPEAVCRVector2@@NN@Z TEXTEQU <__imp_?CRVector2Polar@@YAPEAVCRVector2@@NN@Z>
extern __imp_?CRVector2Polar@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z:PANYARGS
?CRVector2Polar@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRVector2Polar@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z>
extern __imp_?CRVector3Spherical@@YAPEAVCRVector3@@NNN@Z:PANYARGS
?CRVector3Spherical@@YAPEAVCRVector3@@NNN@Z TEXTEQU <__imp_?CRVector3Spherical@@YAPEAVCRVector3@@NNN@Z>
extern __imp_?CRVector3Spherical@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z:PANYARGS
?CRVector3Spherical@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z TEXTEQU <__imp_?CRVector3Spherical@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z>
extern __imp_?CRVersionString@@YAPEBGXZ:PANYARGS
?CRVersionString@@YAPEBGXZ TEXTEQU <__imp_?CRVersionString@@YAPEBGXZ>
extern __imp_?CRViewFrameRate@@YAPEAVCRNumber@@XZ:PANYARGS
?CRViewFrameRate@@YAPEAVCRNumber@@XZ TEXTEQU <__imp_?CRViewFrameRate@@YAPEAVCRNumber@@XZ>
extern __imp_?CRViewTimeDelta@@YAPEAVCRNumber@@XZ:PANYARGS
?CRViewTimeDelta@@YAPEAVCRNumber@@XZ TEXTEQU <__imp_?CRViewTimeDelta@@YAPEAVCRNumber@@XZ>
extern __imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@N@Z:PANYARGS
?CRWeight@@YAPEAVCRFontStyle@@PEAV1@N@Z TEXTEQU <__imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@N@Z>
extern __imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRWeight@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRWhite@@YAPEAVCRColor@@XZ:PANYARGS
?CRWhite@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRWhite@@YAPEAVCRColor@@XZ>
extern __imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@N@Z:PANYARGS
?CRWidth@@YAPEAVCRLineStyle@@PEAV1@N@Z TEXTEQU <__imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@N@Z>
extern __imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z:PANYARGS
?CRWidth@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z>
extern __imp_?CRXShear2@@YAPEAVCRTransform2@@N@Z:PANYARGS
?CRXShear2@@YAPEAVCRTransform2@@N@Z TEXTEQU <__imp_?CRXShear2@@YAPEAVCRTransform2@@N@Z>
extern __imp_?CRXShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PANYARGS
?CRXShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRXShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>
extern __imp_?CRXShear3@@YAPEAVCRTransform3@@NN@Z:PANYARGS
?CRXShear3@@YAPEAVCRTransform3@@NN@Z TEXTEQU <__imp_?CRXShear3@@YAPEAVCRTransform3@@NN@Z>
extern __imp_?CRXShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z:PANYARGS
?CRXShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRXShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z>
extern __imp_?CRXVector2@@YAPEAVCRVector2@@XZ:PANYARGS
?CRXVector2@@YAPEAVCRVector2@@XZ TEXTEQU <__imp_?CRXVector2@@YAPEAVCRVector2@@XZ>
extern __imp_?CRXVector3@@YAPEAVCRVector3@@XZ:PANYARGS
?CRXVector3@@YAPEAVCRVector3@@XZ TEXTEQU <__imp_?CRXVector3@@YAPEAVCRVector3@@XZ>
extern __imp_?CRYShear2@@YAPEAVCRTransform2@@N@Z:PANYARGS
?CRYShear2@@YAPEAVCRTransform2@@N@Z TEXTEQU <__imp_?CRYShear2@@YAPEAVCRTransform2@@N@Z>
extern __imp_?CRYShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PANYARGS
?CRYShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z TEXTEQU <__imp_?CRYShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>
extern __imp_?CRYShear3@@YAPEAVCRTransform3@@NN@Z:PANYARGS
?CRYShear3@@YAPEAVCRTransform3@@NN@Z TEXTEQU <__imp_?CRYShear3@@YAPEAVCRTransform3@@NN@Z>
extern __imp_?CRYShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z:PANYARGS
?CRYShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRYShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z>
extern __imp_?CRYVector2@@YAPEAVCRVector2@@XZ:PANYARGS
?CRYVector2@@YAPEAVCRVector2@@XZ TEXTEQU <__imp_?CRYVector2@@YAPEAVCRVector2@@XZ>
extern __imp_?CRYVector3@@YAPEAVCRVector3@@XZ:PANYARGS
?CRYVector3@@YAPEAVCRVector3@@XZ TEXTEQU <__imp_?CRYVector3@@YAPEAVCRVector3@@XZ>
extern __imp_?CRYellow@@YAPEAVCRColor@@XZ:PANYARGS
?CRYellow@@YAPEAVCRColor@@XZ TEXTEQU <__imp_?CRYellow@@YAPEAVCRColor@@XZ>
extern __imp_?CRZShear3@@YAPEAVCRTransform3@@NN@Z:PANYARGS
?CRZShear3@@YAPEAVCRTransform3@@NN@Z TEXTEQU <__imp_?CRZShear3@@YAPEAVCRTransform3@@NN@Z>
extern __imp_?CRZShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z:PANYARGS
?CRZShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z TEXTEQU <__imp_?CRZShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z>
extern __imp_?CRZVector3@@YAPEAVCRVector3@@XZ:PANYARGS
?CRZVector3@@YAPEAVCRVector3@@XZ TEXTEQU <__imp_?CRZVector3@@YAPEAVCRVector3@@XZ>
extern __imp_?CRZeroVector2@@YAPEAVCRVector2@@XZ:PANYARGS
?CRZeroVector2@@YAPEAVCRVector2@@XZ TEXTEQU <__imp_?CRZeroVector2@@YAPEAVCRVector2@@XZ>
extern __imp_?CRZeroVector3@@YAPEAVCRVector3@@XZ:PANYARGS
?CRZeroVector3@@YAPEAVCRVector3@@XZ TEXTEQU <__imp_?CRZeroVector3@@YAPEAVCRVector3@@XZ>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
