extern __imp_DavFreeUsedDiskSpace:PANYARGS
DavFreeUsedDiskSpace TEXTEQU <__imp_DavFreeUsedDiskSpace>
extern __imp_DavGetDiskSpaceUsage:PANYARGS
DavGetDiskSpaceUsage TEXTEQU <__imp_DavGetDiskSpaceUsage>
extern __imp_DavGetTheLockOwnerOfTheFile:PANYARGS
DavGetTheLockOwnerOfTheFile TEXTEQU <__imp_DavGetTheLockOwnerOfTheFile>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_NPAddConnection:PANYARGS
NPAddConnection TEXTEQU <__imp_NPAddConnection>
extern __imp_NPAddConnection3:PANYARGS
NPAddConnection3 TEXTEQU <__imp_NPAddConnection3>
extern __imp_NPCancelConnection:PANYARGS
NPCancelConnection TEXTEQU <__imp_NPCancelConnection>
extern __imp_NPCloseEnum:PANYARGS
NPCloseEnum TEXTEQU <__imp_NPCloseEnum>
extern __imp_NPEnumResource:PANYARGS
NPEnumResource TEXTEQU <__imp_NPEnumResource>
extern __imp_NPFormatNetworkName:PANYARGS
NPFormatNetworkName TEXTEQU <__imp_NPFormatNetworkName>
extern __imp_NPGetCaps:PANYARGS
NPGetCaps TEXTEQU <__imp_NPGetCaps>
extern __imp_NPGetConnection:PANYARGS
NPGetConnection TEXTEQU <__imp_NPGetConnection>
extern __imp_NPGetResourceInformation:PANYARGS
NPGetResourceInformation TEXTEQU <__imp_NPGetResourceInformation>
extern __imp_NPGetResourceParent:PANYARGS
NPGetResourceParent TEXTEQU <__imp_NPGetResourceParent>
extern __imp_NPGetUniversalName:PANYARGS
NPGetUniversalName TEXTEQU <__imp_NPGetUniversalName>
extern __imp_NPGetUser:PANYARGS
NPGetUser TEXTEQU <__imp_NPGetUser>
extern __imp_NPOpenEnum:PANYARGS
NPOpenEnum TEXTEQU <__imp_NPOpenEnum>
