extern __imp_DbgHelpCreateUserDump:PANYARGS
DbgHelpCreateUserDump TEXTEQU <__imp_DbgHelpCreateUserDump>
extern __imp_DbgHelpCreateUserDumpW:PANYARGS
DbgHelpCreateUserDumpW TEXTEQU <__imp_DbgHelpCreateUserDumpW>
extern __imp_EnumerateLoadedModules:PANYARGS
EnumerateLoadedModules TEXTEQU <__imp_EnumerateLoadedModules>
extern __imp_EnumerateLoadedModules64:PANYARGS
EnumerateLoadedModules64 TEXTEQU <__imp_EnumerateLoadedModules64>
extern __imp_ExtensionApiVersion:PANYARGS
ExtensionApiVersion TEXTEQU <__imp_ExtensionApiVersion>
extern __imp_FindDebugInfoFile:PANYARGS
FindDebugInfoFile TEXTEQU <__imp_FindDebugInfoFile>
extern __imp_FindDebugInfoFileEx:PANYARGS
FindDebugInfoFileEx TEXTEQU <__imp_FindDebugInfoFileEx>
extern __imp_FindExecutableImage:PANYARGS
FindExecutableImage TEXTEQU <__imp_FindExecutableImage>
extern __imp_FindExecutableImageEx:PANYARGS
FindExecutableImageEx TEXTEQU <__imp_FindExecutableImageEx>
extern __imp_FindFileInPath:PANYARGS
FindFileInPath TEXTEQU <__imp_FindFileInPath>
extern __imp_FindFileInSearchPath:PANYARGS
FindFileInSearchPath TEXTEQU <__imp_FindFileInSearchPath>
extern __imp_GetTimestampForLoadedLibrary:PANYARGS
GetTimestampForLoadedLibrary TEXTEQU <__imp_GetTimestampForLoadedLibrary>
extern __imp_ImageDirectoryEntryToData:PANYARGS
ImageDirectoryEntryToData TEXTEQU <__imp_ImageDirectoryEntryToData>
extern __imp_ImageDirectoryEntryToDataEx:PANYARGS
ImageDirectoryEntryToDataEx TEXTEQU <__imp_ImageDirectoryEntryToDataEx>
extern __imp_ImageNtHeader:PANYARGS
ImageNtHeader TEXTEQU <__imp_ImageNtHeader>
extern __imp_ImageRvaToSection:PANYARGS
ImageRvaToSection TEXTEQU <__imp_ImageRvaToSection>
extern __imp_ImageRvaToVa:PANYARGS
ImageRvaToVa TEXTEQU <__imp_ImageRvaToVa>
extern __imp_ImagehlpApiVersion:PANYARGS
ImagehlpApiVersion TEXTEQU <__imp_ImagehlpApiVersion>
extern __imp_ImagehlpApiVersionEx:PANYARGS
ImagehlpApiVersionEx TEXTEQU <__imp_ImagehlpApiVersionEx>
extern __imp_MakeSureDirectoryPathExists:PANYARGS
MakeSureDirectoryPathExists TEXTEQU <__imp_MakeSureDirectoryPathExists>
extern __imp_MiniDumpReadDumpStream:PANYARGS
MiniDumpReadDumpStream TEXTEQU <__imp_MiniDumpReadDumpStream>
extern __imp_MiniDumpWriteDump:PANYARGS
MiniDumpWriteDump TEXTEQU <__imp_MiniDumpWriteDump>
extern __imp_SearchTreeForFile:PANYARGS
SearchTreeForFile TEXTEQU <__imp_SearchTreeForFile>
extern __imp_StackWalk:PANYARGS
StackWalk TEXTEQU <__imp_StackWalk>
extern __imp_StackWalk64:PANYARGS
StackWalk64 TEXTEQU <__imp_StackWalk64>
extern __imp_SymAddSymbol:PANYARGS
SymAddSymbol TEXTEQU <__imp_SymAddSymbol>
extern __imp_SymCleanup:PANYARGS
SymCleanup TEXTEQU <__imp_SymCleanup>
extern __imp_SymDeleteSymbol:PANYARGS
SymDeleteSymbol TEXTEQU <__imp_SymDeleteSymbol>
extern __imp_SymEnumLines:PANYARGS
SymEnumLines TEXTEQU <__imp_SymEnumLines>
extern __imp_SymEnumSourceFiles:PANYARGS
SymEnumSourceFiles TEXTEQU <__imp_SymEnumSourceFiles>
extern __imp_SymEnumSym:PANYARGS
SymEnumSym TEXTEQU <__imp_SymEnumSym>
extern __imp_SymEnumSymbols:PANYARGS
SymEnumSymbols TEXTEQU <__imp_SymEnumSymbols>
extern __imp_SymEnumSymbolsForAddr:PANYARGS
SymEnumSymbolsForAddr TEXTEQU <__imp_SymEnumSymbolsForAddr>
extern __imp_SymEnumTypes:PANYARGS
SymEnumTypes TEXTEQU <__imp_SymEnumTypes>
extern __imp_SymEnumerateModules:PANYARGS
SymEnumerateModules TEXTEQU <__imp_SymEnumerateModules>
extern __imp_SymEnumerateModules64:PANYARGS
SymEnumerateModules64 TEXTEQU <__imp_SymEnumerateModules64>
extern __imp_SymEnumerateSymbols:PANYARGS
SymEnumerateSymbols TEXTEQU <__imp_SymEnumerateSymbols>
extern __imp_SymEnumerateSymbols64:PANYARGS
SymEnumerateSymbols64 TEXTEQU <__imp_SymEnumerateSymbols64>
extern __imp_SymEnumerateSymbolsW:PANYARGS
SymEnumerateSymbolsW TEXTEQU <__imp_SymEnumerateSymbolsW>
extern __imp_SymEnumerateSymbolsW64:PANYARGS
SymEnumerateSymbolsW64 TEXTEQU <__imp_SymEnumerateSymbolsW64>
extern __imp_SymFindFileInPath:PANYARGS
SymFindFileInPath TEXTEQU <__imp_SymFindFileInPath>
extern __imp_SymFromAddr:PANYARGS
SymFromAddr TEXTEQU <__imp_SymFromAddr>
extern __imp_SymFromName:PANYARGS
SymFromName TEXTEQU <__imp_SymFromName>
extern __imp_SymFromToken:PANYARGS
SymFromToken TEXTEQU <__imp_SymFromToken>
extern __imp_SymFunctionTableAccess:PANYARGS
SymFunctionTableAccess TEXTEQU <__imp_SymFunctionTableAccess>
extern __imp_SymFunctionTableAccess64:PANYARGS
SymFunctionTableAccess64 TEXTEQU <__imp_SymFunctionTableAccess64>
extern __imp_SymGetFileLineOffsets64:PANYARGS
SymGetFileLineOffsets64 TEXTEQU <__imp_SymGetFileLineOffsets64>
extern __imp_SymGetHomeDirectory:PANYARGS
SymGetHomeDirectory TEXTEQU <__imp_SymGetHomeDirectory>
extern __imp_SymGetLineFromAddr:PANYARGS
SymGetLineFromAddr TEXTEQU <__imp_SymGetLineFromAddr>
extern __imp_SymGetLineFromAddr64:PANYARGS
SymGetLineFromAddr64 TEXTEQU <__imp_SymGetLineFromAddr64>
extern __imp_SymGetLineFromName:PANYARGS
SymGetLineFromName TEXTEQU <__imp_SymGetLineFromName>
extern __imp_SymGetLineFromName64:PANYARGS
SymGetLineFromName64 TEXTEQU <__imp_SymGetLineFromName64>
extern __imp_SymGetLineNext:PANYARGS
SymGetLineNext TEXTEQU <__imp_SymGetLineNext>
extern __imp_SymGetLineNext64:PANYARGS
SymGetLineNext64 TEXTEQU <__imp_SymGetLineNext64>
extern __imp_SymGetLinePrev:PANYARGS
SymGetLinePrev TEXTEQU <__imp_SymGetLinePrev>
extern __imp_SymGetLinePrev64:PANYARGS
SymGetLinePrev64 TEXTEQU <__imp_SymGetLinePrev64>
extern __imp_SymGetModuleBase:PANYARGS
SymGetModuleBase TEXTEQU <__imp_SymGetModuleBase>
extern __imp_SymGetModuleBase64:PANYARGS
SymGetModuleBase64 TEXTEQU <__imp_SymGetModuleBase64>
extern __imp_SymGetModuleInfo:PANYARGS
SymGetModuleInfo TEXTEQU <__imp_SymGetModuleInfo>
extern __imp_SymGetModuleInfo64:PANYARGS
SymGetModuleInfo64 TEXTEQU <__imp_SymGetModuleInfo64>
extern __imp_SymGetModuleInfoW:PANYARGS
SymGetModuleInfoW TEXTEQU <__imp_SymGetModuleInfoW>
extern __imp_SymGetModuleInfoW64:PANYARGS
SymGetModuleInfoW64 TEXTEQU <__imp_SymGetModuleInfoW64>
extern __imp_SymGetOptions:PANYARGS
SymGetOptions TEXTEQU <__imp_SymGetOptions>
extern __imp_SymGetSearchPath:PANYARGS
SymGetSearchPath TEXTEQU <__imp_SymGetSearchPath>
extern __imp_SymGetSymFromAddr:PANYARGS
SymGetSymFromAddr TEXTEQU <__imp_SymGetSymFromAddr>
extern __imp_SymGetSymFromAddr64:PANYARGS
SymGetSymFromAddr64 TEXTEQU <__imp_SymGetSymFromAddr64>
extern __imp_SymGetSymFromName:PANYARGS
SymGetSymFromName TEXTEQU <__imp_SymGetSymFromName>
extern __imp_SymGetSymFromName64:PANYARGS
SymGetSymFromName64 TEXTEQU <__imp_SymGetSymFromName64>
extern __imp_SymGetSymNext:PANYARGS
SymGetSymNext TEXTEQU <__imp_SymGetSymNext>
extern __imp_SymGetSymNext64:PANYARGS
SymGetSymNext64 TEXTEQU <__imp_SymGetSymNext64>
extern __imp_SymGetSymPrev:PANYARGS
SymGetSymPrev TEXTEQU <__imp_SymGetSymPrev>
extern __imp_SymGetSymPrev64:PANYARGS
SymGetSymPrev64 TEXTEQU <__imp_SymGetSymPrev64>
extern __imp_SymGetTypeFromName:PANYARGS
SymGetTypeFromName TEXTEQU <__imp_SymGetTypeFromName>
extern __imp_SymGetTypeInfo:PANYARGS
SymGetTypeInfo TEXTEQU <__imp_SymGetTypeInfo>
extern __imp_SymInitialize:PANYARGS
SymInitialize TEXTEQU <__imp_SymInitialize>
extern __imp_SymLoadModule:PANYARGS
SymLoadModule TEXTEQU <__imp_SymLoadModule>
extern __imp_SymLoadModule64:PANYARGS
SymLoadModule64 TEXTEQU <__imp_SymLoadModule64>
extern __imp_SymLoadModuleEx:PANYARGS
SymLoadModuleEx TEXTEQU <__imp_SymLoadModuleEx>
extern __imp_SymMatchFileName:PANYARGS
SymMatchFileName TEXTEQU <__imp_SymMatchFileName>
extern __imp_SymMatchString:PANYARGS
SymMatchString TEXTEQU <__imp_SymMatchString>
extern __imp_SymRegisterCallback:PANYARGS
SymRegisterCallback TEXTEQU <__imp_SymRegisterCallback>
extern __imp_SymRegisterCallback64:PANYARGS
SymRegisterCallback64 TEXTEQU <__imp_SymRegisterCallback64>
extern __imp_SymRegisterFunctionEntryCallback:PANYARGS
SymRegisterFunctionEntryCallback TEXTEQU <__imp_SymRegisterFunctionEntryCallback>
extern __imp_SymRegisterFunctionEntryCallback64:PANYARGS
SymRegisterFunctionEntryCallback64 TEXTEQU <__imp_SymRegisterFunctionEntryCallback64>
extern __imp_SymSetContext:PANYARGS
SymSetContext TEXTEQU <__imp_SymSetContext>
extern __imp_SymSetHomeDirectory:PANYARGS
SymSetHomeDirectory TEXTEQU <__imp_SymSetHomeDirectory>
extern __imp_SymSetOptions:PANYARGS
SymSetOptions TEXTEQU <__imp_SymSetOptions>
extern __imp_SymSetParentWindow:PANYARGS
SymSetParentWindow TEXTEQU <__imp_SymSetParentWindow>
extern __imp_SymSetSearchPath:PANYARGS
SymSetSearchPath TEXTEQU <__imp_SymSetSearchPath>
extern __imp_SymUnDName:PANYARGS
SymUnDName TEXTEQU <__imp_SymUnDName>
extern __imp_SymUnDName64:PANYARGS
SymUnDName64 TEXTEQU <__imp_SymUnDName64>
extern __imp_SymUnloadModule:PANYARGS
SymUnloadModule TEXTEQU <__imp_SymUnloadModule>
extern __imp_SymUnloadModule64:PANYARGS
SymUnloadModule64 TEXTEQU <__imp_SymUnloadModule64>
extern __imp_UnDecorateSymbolName:PANYARGS
UnDecorateSymbolName TEXTEQU <__imp_UnDecorateSymbolName>
extern __imp_WinDbgExtensionDllInit:PANYARGS
WinDbgExtensionDllInit TEXTEQU <__imp_WinDbgExtensionDllInit>
extern __imp_dbghelp:PANYARGS
dbghelp TEXTEQU <__imp_dbghelp>
extern __imp_dh:PANYARGS
extern __imp_fptr:PANYARGS
fptr TEXTEQU <__imp_fptr>
extern __imp_lm:PANYARGS
lm TEXTEQU <__imp_lm>
extern __imp_lmi:PANYARGS
lmi TEXTEQU <__imp_lmi>
extern __imp_omap:PANYARGS
omap TEXTEQU <__imp_omap>
extern __imp_srcfiles:PANYARGS
srcfiles TEXTEQU <__imp_srcfiles>
extern __imp_stackdbg:PANYARGS
stackdbg TEXTEQU <__imp_stackdbg>
extern __imp_sym:PANYARGS
sym TEXTEQU <__imp_sym>
extern __imp_symsrv:PANYARGS
symsrv TEXTEQU <__imp_symsrv>
extern __imp_vc7fpo:PANYARGS
vc7fpo TEXTEQU <__imp_vc7fpo>
