extern __imp_ConnectionObjectSize:PANYARGS
ConnectionObjectSize TEXTEQU <__imp_ConnectionObjectSize>
extern __imp_ConnectionRead:PANYARGS
ConnectionRead TEXTEQU <__imp_ConnectionRead>
extern __imp_ConnectionWrite:PANYARGS
ConnectionWrite TEXTEQU <__imp_ConnectionWrite>
extern __imp_ConnectionTransact:PANYARGS
ConnectionTransact TEXTEQU <__imp_ConnectionTransact>
extern __imp_ConnectionWriteOOB:PANYARGS
ConnectionWriteOOB TEXTEQU <__imp_ConnectionWriteOOB>
extern __imp_ConnectionMode:PANYARGS
ConnectionMode TEXTEQU <__imp_ConnectionMode>
extern __imp_ConnectionStatus:PANYARGS
ConnectionStatus TEXTEQU <__imp_ConnectionStatus>
extern __imp_ConnectionOpen:PANYARGS
ConnectionOpen TEXTEQU <__imp_ConnectionOpen>
extern __imp_ConnectionClose:PANYARGS
ConnectionClose TEXTEQU <__imp_ConnectionClose>
extern __imp_ConnectionCheckForData:PANYARGS
ConnectionCheckForData TEXTEQU <__imp_ConnectionCheckForData>
extern __imp_ConnectionError:PANYARGS
ConnectionError TEXTEQU <__imp_ConnectionError>
extern __imp_ConnectionVer:PANYARGS
ConnectionVer TEXTEQU <__imp_ConnectionVer>
extern __imp_ConnectionSqlVer:PANYARGS
ConnectionSqlVer TEXTEQU <__imp_ConnectionSqlVer>
extern __imp_ConnectionServerEnum:PANYARGS
ConnectionServerEnum TEXTEQU <__imp_ConnectionServerEnum>
extern __imp_ConnectionServerEnumW:PANYARGS
ConnectionServerEnumW TEXTEQU <__imp_ConnectionServerEnumW>
extern __imp_ConnectionOpenW:PANYARGS
ConnectionOpenW TEXTEQU <__imp_ConnectionOpenW>
extern __imp_ConnectionErrorW:PANYARGS
ConnectionErrorW TEXTEQU <__imp_ConnectionErrorW>
extern __imp_ConnectionOption:PANYARGS
ConnectionOption TEXTEQU <__imp_ConnectionOption>
extern __imp_ConnectionGetSvrUser:PANYARGS
ConnectionGetSvrUser TEXTEQU <__imp_ConnectionGetSvrUser>
extern __imp_InitEnumServers:PANYARGS
InitEnumServers TEXTEQU <__imp_InitEnumServers>
extern __imp_GetNextEnumeration:PANYARGS
GetNextEnumeration TEXTEQU <__imp_GetNextEnumeration>
extern __imp_CloseEnumServers:PANYARGS
CloseEnumServers TEXTEQU <__imp_CloseEnumServers>
extern __imp_InitSSPIPackage:PANYARGS
InitSSPIPackage TEXTEQU <__imp_InitSSPIPackage>
extern __imp_TermSSPIPackage:PANYARGS
TermSSPIPackage TEXTEQU <__imp_TermSSPIPackage>
extern __imp_InitSession:PANYARGS
InitSession TEXTEQU <__imp_InitSession>
extern __imp_TermSession:PANYARGS
TermSession TEXTEQU <__imp_TermSession>
extern __imp_GenClientContext:PANYARGS
GenClientContext TEXTEQU <__imp_GenClientContext>
extern __imp_ConnectionFlushCache:PANYARGS
ConnectionFlushCache TEXTEQU <__imp_ConnectionFlushCache>
