extern __imp_DCIBeginAccess:PANYARGS
DCIBeginAccess TEXTEQU <__imp_DCIBeginAccess>
extern __imp_DCICloseProvider:PANYARGS
DCICloseProvider TEXTEQU <__imp_DCICloseProvider>
extern __imp_DCICreateOffscreen:PANYARGS
DCICreateOffscreen TEXTEQU <__imp_DCICreateOffscreen>
extern __imp_DCICreateOverlay:PANYARGS
DCICreateOverlay TEXTEQU <__imp_DCICreateOverlay>
extern __imp_DCICreatePrimary:PANYARGS
DCICreatePrimary TEXTEQU <__imp_DCICreatePrimary>
extern __imp_DCIDestroy:PANYARGS
DCIDestroy TEXTEQU <__imp_DCIDestroy>
extern __imp_DCIDraw:PANYARGS
DCIDraw TEXTEQU <__imp_DCIDraw>
extern __imp_DCIEndAccess:PANYARGS
DCIEndAccess TEXTEQU <__imp_DCIEndAccess>
extern __imp_DCIEnum:PANYARGS
DCIEnum TEXTEQU <__imp_DCIEnum>
extern __imp_DCIOpenProvider:PANYARGS
DCIOpenProvider TEXTEQU <__imp_DCIOpenProvider>
extern __imp_DCISetClipList:PANYARGS
DCISetClipList TEXTEQU <__imp_DCISetClipList>
extern __imp_DCISetDestination:PANYARGS
DCISetDestination TEXTEQU <__imp_DCISetDestination>
extern __imp_DCISetSrcDestClip:PANYARGS
DCISetSrcDestClip TEXTEQU <__imp_DCISetSrcDestClip>
extern __imp_GetDCRegionData:PANYARGS
GetDCRegionData TEXTEQU <__imp_GetDCRegionData>
extern __imp_GetWindowRegionData:PANYARGS
GetWindowRegionData TEXTEQU <__imp_GetWindowRegionData>
extern __imp_WinWatchClose:PANYARGS
WinWatchClose TEXTEQU <__imp_WinWatchClose>
extern __imp_WinWatchDidStatusChange:PANYARGS
WinWatchDidStatusChange TEXTEQU <__imp_WinWatchDidStatusChange>
extern __imp_WinWatchGetClipList:PANYARGS
WinWatchGetClipList TEXTEQU <__imp_WinWatchGetClipList>
extern __imp_WinWatchNotify:PANYARGS
WinWatchNotify TEXTEQU <__imp_WinWatchNotify>
extern __imp_WinWatchOpen:PANYARGS
WinWatchOpen TEXTEQU <__imp_WinWatchOpen>
