extern __imp_AcquireDDThreadLock:PANYARGS
AcquireDDThreadLock TEXTEQU <__imp_AcquireDDThreadLock>
extern __imp_CheckFullscreen:PANYARGS
CheckFullscreen TEXTEQU <__imp_CheckFullscreen>
extern __imp_CompleteCreateSysmemSurface:PANYARGS
CompleteCreateSysmemSurface TEXTEQU <__imp_CompleteCreateSysmemSurface>
extern __imp_D3DParseUnknownCommand:PANYARGS
D3DParseUnknownCommand TEXTEQU <__imp_D3DParseUnknownCommand>
extern __imp_DDGetAttachedSurfaceLcl:PANYARGS
DDGetAttachedSurfaceLcl TEXTEQU <__imp_DDGetAttachedSurfaceLcl>
extern __imp_DDInternalLock:PANYARGS
DDInternalLock TEXTEQU <__imp_DDInternalLock>
extern __imp_DDInternalUnlock:PANYARGS
DDInternalUnlock TEXTEQU <__imp_DDInternalUnlock>
extern __imp_DSoundHelp:PANYARGS
DSoundHelp TEXTEQU <__imp_DSoundHelp>
extern __imp_DirectDrawCreate:PANYARGS
DirectDrawCreate TEXTEQU <__imp_DirectDrawCreate>
extern __imp_DirectDrawCreateClipper:PANYARGS
DirectDrawCreateClipper TEXTEQU <__imp_DirectDrawCreateClipper>
extern __imp_DirectDrawCreateEx:PANYARGS
DirectDrawCreateEx TEXTEQU <__imp_DirectDrawCreateEx>
extern __imp_DirectDrawEnumerateA:PANYARGS
DirectDrawEnumerate  TEXTEQU <__imp_DirectDrawEnumerateA>
extern __imp_DirectDrawEnumerateExA:PANYARGS
DirectDrawEnumerateEx  TEXTEQU <__imp_DirectDrawEnumerateExA>
extern __imp_DirectDrawEnumerateExW:PANYARGS
DirectDrawEnumerateExW TEXTEQU <__imp_DirectDrawEnumerateExW>
extern __imp_DirectDrawEnumerateW:PANYARGS
DirectDrawEnumerateW TEXTEQU <__imp_DirectDrawEnumerateW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_GetDDSurfaceLocal:PANYARGS
GetDDSurfaceLocal TEXTEQU <__imp_GetDDSurfaceLocal>
extern __imp_GetOLEThunkData:PANYARGS
GetOLEThunkData TEXTEQU <__imp_GetOLEThunkData>
extern __imp_GetSurfaceFromDC:PANYARGS
GetSurfaceFromDC TEXTEQU <__imp_GetSurfaceFromDC>
extern __imp_RegisterSpecialCase:PANYARGS
RegisterSpecialCase TEXTEQU <__imp_RegisterSpecialCase>
extern __imp_ReleaseDDThreadLock:PANYARGS
ReleaseDDThreadLock TEXTEQU <__imp_ReleaseDDThreadLock>
