extern __imp_??0CDbgCallTracer@@QEAA@KPEBD@Z:PANYARGS
??0CDbgCallTracer@@QEAA@KPEBD@Z TEXTEQU <__imp_??0CDbgCallTracer@@QEAA@KPEBD@Z>
extern __imp_??0CDfrgAsyncObject@@QEAA@XZ:PANYARGS
??0CDfrgAsyncObject@@QEAA@XZ TEXTEQU <__imp_??0CDfrgAsyncObject@@QEAA@XZ>
extern __imp_??1CDbgCallTracer@@QEAA@XZ:PANYARGS
??1CDbgCallTracer@@QEAA@XZ TEXTEQU <__imp_??1CDbgCallTracer@@QEAA@XZ>
extern __imp_??1CDfrgAsyncObject@@QEAA@XZ:PANYARGS
??1CDfrgAsyncObject@@QEAA@XZ TEXTEQU <__imp_??1CDfrgAsyncObject@@QEAA@XZ>
extern __imp_?AllowCancel@CDfrgAsyncObject@@QEAAXXZ:PANYARGS
?AllowCancel@CDfrgAsyncObject@@QEAAXXZ TEXTEQU <__imp_?AllowCancel@CDfrgAsyncObject@@QEAAXXZ>
extern __imp_?Cancel@CDfrgAsyncObject@@UEAAJXZ:PANYARGS
?Cancel@CDfrgAsyncObject@@UEAAJXZ TEXTEQU <__imp_?Cancel@CDfrgAsyncObject@@UEAAJXZ>
extern __imp_?DisallowCancel@CDfrgAsyncObject@@QEAAXXZ:PANYARGS
?DisallowCancel@CDfrgAsyncObject@@QEAAXXZ TEXTEQU <__imp_?DisallowCancel@CDfrgAsyncObject@@QEAAXXZ>
extern __imp_?GetDefragReport@CDfrgAsyncObject@@UEAAJPEAU_DEFRAG_REPORT@@@Z:PANYARGS
?GetDefragReport@CDfrgAsyncObject@@UEAAJPEAU_DEFRAG_REPORT@@@Z TEXTEQU <__imp_?GetDefragReport@CDfrgAsyncObject@@UEAAJPEAU_DEFRAG_REPORT@@@Z>
extern __imp_?Initialize@CDfrgAsyncObject@@SAKXZ:PANYARGS
?Initialize@CDfrgAsyncObject@@SAKXZ TEXTEQU <__imp_?Initialize@CDfrgAsyncObject@@SAKXZ>
extern __imp_?IsCancelRequested@CDfrgAsyncObject@@QEAAHXZ:PANYARGS
?IsCancelRequested@CDfrgAsyncObject@@QEAAHXZ TEXTEQU <__imp_?IsCancelRequested@CDfrgAsyncObject@@QEAAHXZ>
extern __imp_?IsFinished@CDfrgAsyncObject@@QEAAHXZ:PANYARGS
?IsFinished@CDfrgAsyncObject@@QEAAHXZ TEXTEQU <__imp_?IsFinished@CDfrgAsyncObject@@QEAAHXZ>
extern __imp_?QueryStatus@CDfrgAsyncObject@@UEAAJPEAJPEAK@Z:PANYARGS
?QueryStatus@CDfrgAsyncObject@@UEAAJPEAJPEAK@Z TEXTEQU <__imp_?QueryStatus@CDfrgAsyncObject@@UEAAJPEAJPEAK@Z>
extern __imp_?SetCompletionStatus@CDfrgAsyncObject@@QEAAXJK@Z:PANYARGS
?SetCompletionStatus@CDfrgAsyncObject@@QEAAXJK@Z TEXTEQU <__imp_?SetCompletionStatus@CDfrgAsyncObject@@QEAAXJK@Z>
extern __imp_?Signal@CDfrgAsyncObject@@QEAAXXZ:PANYARGS
?Signal@CDfrgAsyncObject@@QEAAXXZ TEXTEQU <__imp_?Signal@CDfrgAsyncObject@@QEAAXXZ>
extern __imp_?Uninitialize@CDfrgAsyncObject@@SAXXZ:PANYARGS
?Uninitialize@CDfrgAsyncObject@@SAXXZ TEXTEQU <__imp_?Uninitialize@CDfrgAsyncObject@@SAXXZ>
extern __imp_?Wait@CDfrgAsyncObject@@UEAAJPEAJ@Z:PANYARGS
?Wait@CDfrgAsyncObject@@UEAAJPEAJ@Z TEXTEQU <__imp_?Wait@CDfrgAsyncObject@@UEAAJPEAJ@Z>
extern __imp_?WaitImpl@CDfrgAsyncObject@@QEAAJPEAJ@Z:PANYARGS
?WaitImpl@CDfrgAsyncObject@@QEAAJPEAJ@Z TEXTEQU <__imp_?WaitImpl@CDfrgAsyncObject@@QEAAJPEAJ@Z>
