extern __imp_KillService:PANYARGS
KillService TEXTEQU <__imp_KillService>
extern __imp_ShArpMaintain:PANYARGS
ShArpMaintain TEXTEQU <__imp_ShArpMaintain>
extern __imp_ShArpMaintainW:PANYARGS
ShArpMaintainW TEXTEQU <__imp_ShArpMaintainW>
extern __imp_ShOpenVerbApplication:PANYARGS
ShOpenVerbApplication TEXTEQU <__imp_ShOpenVerbApplication>
extern __imp_ShOpenVerbApplicationW:PANYARGS
ShOpenVerbApplicationW TEXTEQU <__imp_ShOpenVerbApplicationW>
extern __imp_ShOpenVerbShortcut:PANYARGS
ShOpenVerbShortcut TEXTEQU <__imp_ShOpenVerbShortcut>
extern __imp_ShOpenVerbShortcutW:PANYARGS
ShOpenVerbShortcutW TEXTEQU <__imp_ShOpenVerbShortcutW>
extern __imp_CleanOnlineAppCache:PANYARGS
CleanOnlineAppCache TEXTEQU <__imp_CleanOnlineAppCache>
extern __imp_CreateActContext:PANYARGS
CreateActContext TEXTEQU <__imp_CreateActContext>
extern __imp_CreateCMSFromXml:PANYARGS
CreateCMSFromXml TEXTEQU <__imp_CreateCMSFromXml>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_GetCurrentActContext:PANYARGS
GetCurrentActContext TEXTEQU <__imp_GetCurrentActContext>
extern __imp_GetDeploymentDataFromManifest:PANYARGS
GetDeploymentDataFromManifest TEXTEQU <__imp_GetDeploymentDataFromManifest>
extern __imp_GetUserStateManager:PANYARGS
GetUserStateManager TEXTEQU <__imp_GetUserStateManager>
extern __imp_GetUserStore:PANYARGS
GetUserStore TEXTEQU <__imp_GetUserStore>
extern __imp_ParseManifest:PANYARGS
ParseManifest TEXTEQU <__imp_ParseManifest>
