extern __imp_WlDimsLock:PANYARGS
WlDimsLock TEXTEQU <__imp_WlDimsLock>
extern __imp_WlDimsLogoff:PANYARGS
WlDimsLogoff TEXTEQU <__imp_WlDimsLogoff>
extern __imp_WlDimsLogon:PANYARGS
WlDimsLogon TEXTEQU <__imp_WlDimsLogon>
extern __imp_WlDimsShutdown:PANYARGS
WlDimsShutdown TEXTEQU <__imp_WlDimsShutdown>
extern __imp_WlDimsStartShell:PANYARGS
WlDimsStartShell TEXTEQU <__imp_WlDimsStartShell>
extern __imp_WlDimsStartup:PANYARGS
WlDimsStartup TEXTEQU <__imp_WlDimsStartup>
extern __imp_WlDimsUnlock:PANYARGS
WlDimsUnlock TEXTEQU <__imp_WlDimsUnlock>
