extern __imp_diskcopy_ordinal1:PANYARGS
diskcopy_ordinal1 TEXTEQU <__imp_diskcopy_ordinal1>
extern __imp_DiskCopyRunDll:PANYARGS
DiskCopyRunDll TEXTEQU <__imp_DiskCopyRunDll>
extern __imp_DiskCopyRunDllW:PANYARGS
DiskCopyRunDllW TEXTEQU <__imp_DiskCopyRunDllW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
