extern __imp_??0CDrCallTracer@@QEAA@KQEBD0PEBJ@Z:PANYARGS
??0CDrCallTracer@@QEAA@KQEBD0PEBJ@Z TEXTEQU <__imp_??0CDrCallTracer@@QEAA@KQEBD0PEBJ@Z>
extern __imp_??1CDrCallTracer@@QEAA@XZ:PANYARGS
??1CDrCallTracer@@QEAA@XZ TEXTEQU <__imp_??1CDrCallTracer@@QEAA@XZ>
extern __imp_?LogMessage@CDrCallTracer@@QEAAXKPEADZZ:PANYARGS
?LogMessage@CDrCallTracer@@QEAAXKPEADZZ TEXTEQU <__imp_?LogMessage@CDrCallTracer@@QEAAXKPEADZZ>
