extern __imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z:PANYARGS
?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z TEXTEQU <__imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z>
extern __imp_?FreeArrayOfStrings@@YAXPEAUarrayOfStrings@@@Z:PANYARGS
?FreeArrayOfStrings@@YAXPEAUarrayOfStrings@@@Z TEXTEQU <__imp_?FreeArrayOfStrings@@YAXPEAUarrayOfStrings@@@Z>
extern __imp_?GetDiskCount@CDataCache@@QEAAKXZ:PANYARGS
?GetDiskCount@CDataCache@@QEAAKXZ TEXTEQU <__imp_?GetDiskCount@CDataCache@@QEAAKXZ>
extern __imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ:PANYARGS
?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ TEXTEQU <__imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ>
extern __imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetNumMembers@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ:PANYARGS
?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ TEXTEQU <__imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ>
extern __imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z:PANYARGS
?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z TEXTEQU <__imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z>
extern __imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ:PANYARGS
?GetServerName@CDataCache@@QEAA?AVCString@@XZ TEXTEQU <__imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ>
extern __imp_?GetVolumeCount@CDataCache@@QEAAKXZ:PANYARGS
?GetVolumeCount@CDataCache@@QEAAKXZ TEXTEQU <__imp_?GetVolumeCount@CDataCache@@QEAAKXZ>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
