extern __imp_??0CDataCache@@QEAA@XZ:PANYARGS
??0CDataCache@@QEAA@XZ TEXTEQU <__imp_??0CDataCache@@QEAA@XZ>
extern __imp_??1CDMNodeObj@@QEAA@XZ:PANYARGS
??1CDMNodeObj@@QEAA@XZ TEXTEQU <__imp_??1CDMNodeObj@@QEAA@XZ>
extern __imp_??1CDataCache@@UEAA@XZ:PANYARGS
??1CDataCache@@UEAA@XZ TEXTEQU <__imp_??1CDataCache@@UEAA@XZ>
extern __imp_?AddFileSystemInfoToListAndMap@CDataCache@@QEAAXKPEAUfilesysteminfo@@@Z:PANYARGS
?AddFileSystemInfoToListAndMap@CDataCache@@QEAAXKPEAUfilesysteminfo@@@Z TEXTEQU <__imp_?AddFileSystemInfoToListAndMap@CDataCache@@QEAAXKPEAUfilesysteminfo@@@Z>
extern __imp_?AddInstalledFileSystemsToList@CDataCache@@QEAAXKPEAUifilesysteminfo@@@Z:PANYARGS
?AddInstalledFileSystemsToList@CDataCache@@QEAAXKPEAUifilesysteminfo@@@Z TEXTEQU <__imp_?AddInstalledFileSystemsToList@CDataCache@@QEAAXKPEAUifilesysteminfo@@@Z>
extern __imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z:PANYARGS
?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z TEXTEQU <__imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z>
extern __imp_?AddRegionToVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z:PANYARGS
?AddRegionToVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z TEXTEQU <__imp_?AddRegionToVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z>
extern __imp_?AddRow@CDMComponentData@@QEAAX_J@Z:PANYARGS
?AddRow@CDMComponentData@@QEAAX_J@Z TEXTEQU <__imp_?AddRow@CDMComponentData@@QEAAX_J@Z>
extern __imp_?AdjustRegionCountInLegendList@CDataCache@@QEAAXW4_REGIONTYPE@@H@Z:PANYARGS
?AdjustRegionCountInLegendList@CDataCache@@QEAAXW4_REGIONTYPE@@H@Z TEXTEQU <__imp_?AdjustRegionCountInLegendList@CDataCache@@QEAAXW4_REGIONTYPE@@H@Z>
extern __imp_?AdjustVolumeCountInLegendList@CDataCache@@QEAAXW4_VOLUMELAYOUT@@H@Z:PANYARGS
?AdjustVolumeCountInLegendList@CDataCache@@QEAAXW4_VOLUMELAYOUT@@H@Z TEXTEQU <__imp_?AdjustVolumeCountInLegendList@CDataCache@@QEAAXW4_VOLUMELAYOUT@@H@Z>
extern __imp_?CanHaveGPT@CDMNodeObj@@QEAAHXZ:PANYARGS
?CanHaveGPT@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?CanHaveGPT@CDMNodeObj@@QEAAHXZ>
extern __imp_?ChangeRow@CDMComponentData@@QEAAX_J@Z:PANYARGS
?ChangeRow@CDMComponentData@@QEAAX_J@Z TEXTEQU <__imp_?ChangeRow@CDMComponentData@@QEAAX_J@Z>
extern __imp_?Command@CContextMenu@@QEAAJJPEAUIDataObject@@_J@Z:PANYARGS
?Command@CContextMenu@@QEAAJJPEAUIDataObject@@_J@Z TEXTEQU <__imp_?Command@CContextMenu@@QEAAJJPEAUIDataObject@@_J@Z>
extern __imp_?CompareDiskNames@@YAH_J0@Z:PANYARGS
?CompareDiskNames@@YAH_J0@Z TEXTEQU <__imp_?CompareDiskNames@@YAH_J0@Z>
extern __imp_?ContainsActivePartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsActivePartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsActivePartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsBootIniPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsBootIniPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsBootIniPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsBootIniPartitionForWolfpack@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsBootIniPartitionForWolfpack@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsBootIniPartitionForWolfpack@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsBootVolumesNumberChange@CDMNodeObj@@QEAAH_JPEAH@Z:PANYARGS
?ContainsBootVolumesNumberChange@CDMNodeObj@@QEAAH_JPEAH@Z TEXTEQU <__imp_?ContainsBootVolumesNumberChange@CDMNodeObj@@QEAAH_JPEAH@Z>
extern __imp_?ContainsESPPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsESPPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsESPPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsLogicalDrvBootPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsLogicalDrvBootPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsLogicalDrvBootPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsPageFile@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsPageFile@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsPageFile@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsRealSystemPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsRealSystemPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsRealSystemPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsSubDiskNeedResync@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsSubDiskNeedResync@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsSubDiskNeedResync@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsSystemInformation@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsSystemInformation@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsSystemInformation@CDMNodeObj@@QEAAHXZ>
extern __imp_?ContainsSystemPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?ContainsSystemPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?ContainsSystemPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?ConvertBytesToMB@@YAK_J@Z:PANYARGS
?ConvertBytesToMB@@YAK_J@Z TEXTEQU <__imp_?ConvertBytesToMB@@YAK_J@Z>
extern __imp_?ConvertMBToBytes@@YA_J_J@Z:PANYARGS
?ConvertMBToBytes@@YA_J_J@Z TEXTEQU <__imp_?ConvertMBToBytes@@YA_J_J@Z>
extern __imp_?CookieSort@@YAXPEA_JJJP6AH_J1@Z@Z:PANYARGS
?CookieSort@@YAXPEA_JJJP6AH_J1@Z@Z TEXTEQU <__imp_?CookieSort@@YAXPEA_JJJP6AH_J1@Z@Z>
extern __imp_?CreateDiskList@CDataCache@@QEAAXXZ:PANYARGS
?CreateDiskList@CDataCache@@QEAAXXZ TEXTEQU <__imp_?CreateDiskList@CDataCache@@QEAAXXZ>
extern __imp_?CreateNodeObjAndAddToMap@CDataCache@@QEAAPEAVCDMNodeObj@@HW4_NODEOBJ_TYPES@@PEAV1@PEAX_J@Z:PANYARGS
?CreateNodeObjAndAddToMap@CDataCache@@QEAAPEAVCDMNodeObj@@HW4_NODEOBJ_TYPES@@PEAV1@PEAX_J@Z TEXTEQU <__imp_?CreateNodeObjAndAddToMap@CDataCache@@QEAAPEAVCDMNodeObj@@HW4_NODEOBJ_TYPES@@PEAV1@PEAX_J@Z>
extern __imp_?CreateRegionNodeObj@CDataCache@@QEAAPEAVCDMNodeObj@@PEAV2@PEAUregioninfoex@@@Z:PANYARGS
?CreateRegionNodeObj@CDataCache@@QEAAPEAVCDMNodeObj@@PEAV2@PEAUregioninfoex@@@Z TEXTEQU <__imp_?CreateRegionNodeObj@CDataCache@@QEAAPEAVCDMNodeObj@@PEAV2@PEAUregioninfoex@@@Z>
extern __imp_?CreateShortDiskName@CDataCache@@QEAAXAEAUdiskinfoex@@@Z:PANYARGS
?CreateShortDiskName@CDataCache@@QEAAXAEAUdiskinfoex@@@Z TEXTEQU <__imp_?CreateShortDiskName@CDataCache@@QEAAXAEAUdiskinfoex@@@Z>
extern __imp_?CreateVolumeList@CDataCache@@QEAAXXZ:PANYARGS
?CreateVolumeList@CDataCache@@QEAAXXZ TEXTEQU <__imp_?CreateVolumeList@CDataCache@@QEAAXXZ>
extern __imp_?DeleteDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z:PANYARGS
?DeleteDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z TEXTEQU <__imp_?DeleteDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z>
extern __imp_?DeleteEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z:PANYARGS
?DeleteEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z TEXTEQU <__imp_?DeleteEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z>
extern __imp_?DeleteLists@CDataCache@@QEAAXXZ:PANYARGS
?DeleteLists@CDataCache@@QEAAXXZ TEXTEQU <__imp_?DeleteLists@CDataCache@@QEAAXXZ>
extern __imp_?DeleteRegionFromVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z:PANYARGS
?DeleteRegionFromVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z TEXTEQU <__imp_?DeleteRegionFromVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z>
extern __imp_?DeleteRow@CDMComponentData@@QEAAX_J@Z:PANYARGS
?DeleteRow@CDMComponentData@@QEAAX_J@Z TEXTEQU <__imp_?DeleteRow@CDMComponentData@@QEAAX_J@Z>
extern __imp_?DoDelete@CContextMenu@@QEAAX_J@Z:PANYARGS
?DoDelete@CContextMenu@@QEAAX_J@Z TEXTEQU <__imp_?DoDelete@CContextMenu@@QEAAX_J@Z>
extern __imp_?EmptyOcxViewData@CDMComponentData@@QEAAXXZ:PANYARGS
?EmptyOcxViewData@CDMComponentData@@QEAAXXZ TEXTEQU <__imp_?EmptyOcxViewData@CDMComponentData@@QEAAXXZ>
extern __imp_?EnhancedIsUpgradeable@CDMNodeObj@@QEAAHPEAVCTaskData@@@Z:PANYARGS
?EnhancedIsUpgradeable@CDMNodeObj@@QEAAHPEAVCTaskData@@@Z TEXTEQU <__imp_?EnhancedIsUpgradeable@CDMNodeObj@@QEAAHPEAVCTaskData@@@Z>
extern __imp_?EnumDiskRegions@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z:PANYARGS
?EnumDiskRegions@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z TEXTEQU <__imp_?EnumDiskRegions@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z>
extern __imp_?EnumDisks@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PANYARGS
?EnumDisks@CTaskData@@QEAAXAEAKPEAPEA_J@Z TEXTEQU <__imp_?EnumDisks@CTaskData@@QEAAXAEAKPEAPEA_J@Z>
extern __imp_?EnumFirstVolumeMember@CDMNodeObj@@QEAAXAEA_JAEAJ@Z:PANYARGS
?EnumFirstVolumeMember@CDMNodeObj@@QEAAXAEA_JAEAJ@Z TEXTEQU <__imp_?EnumFirstVolumeMember@CDMNodeObj@@QEAAXAEA_JAEAJ@Z>
extern __imp_?EnumNTFSwithDriveLetter@CDataCache@@QEAAXPEAHPEAPEAG@Z:PANYARGS
?EnumNTFSwithDriveLetter@CDataCache@@QEAAXPEAHPEAPEAG@Z TEXTEQU <__imp_?EnumNTFSwithDriveLetter@CDataCache@@QEAAXPEAHPEAPEAG@Z>
extern __imp_?EnumNTFSwithDriveLetter@CTaskData@@QEAAXPEAHPEAPEAG@Z:PANYARGS
?EnumNTFSwithDriveLetter@CTaskData@@QEAAXPEAHPEAPEAG@Z TEXTEQU <__imp_?EnumNTFSwithDriveLetter@CTaskData@@QEAAXPEAHPEAPEAG@Z>
extern __imp_?EnumVolumeMembers@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z:PANYARGS
?EnumVolumeMembers@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z TEXTEQU <__imp_?EnumVolumeMembers@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z>
extern __imp_?EnumVolumes@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PANYARGS
?EnumVolumes@CTaskData@@QEAAXAEAKPEAPEA_J@Z TEXTEQU <__imp_?EnumVolumes@CTaskData@@QEAAXAEAKPEAPEA_J@Z>
extern __imp_?FillDeviceInstanceId@CDataCache@@QEAAXPEAG0@Z:PANYARGS
?FillDeviceInstanceId@CDataCache@@QEAAXPEAG0@Z TEXTEQU <__imp_?FillDeviceInstanceId@CDataCache@@QEAAXPEAG0@Z>
extern __imp_?FilterCookiesBigEnoughForFTRepair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z:PANYARGS
?FilterCookiesBigEnoughForFTRepair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z TEXTEQU <__imp_?FilterCookiesBigEnoughForFTRepair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z>
extern __imp_?FilterCookiesBigEnoughForRAID5Repair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z:PANYARGS
?FilterCookiesBigEnoughForRAID5Repair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z TEXTEQU <__imp_?FilterCookiesBigEnoughForRAID5Repair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z>
extern __imp_?FindCookieAndRemoveFromList@CDataCache@@QEAAH_JPEAV?$CList@PEAVCDMNodeObj@@PEAV1@@@@Z:PANYARGS
?FindCookieAndRemoveFromList@CDataCache@@QEAAH_JPEAV?$CList@PEAVCDMNodeObj@@PEAV1@@@@Z TEXTEQU <__imp_?FindCookieAndRemoveFromList@CDataCache@@QEAAH_JPEAV?$CList@PEAVCDMNodeObj@@PEAV1@@@@Z>
extern __imp_?FindDeviceInstanceId@CDataCache@@QEAAPEAG_J@Z:PANYARGS
?FindDeviceInstanceId@CDataCache@@QEAAPEAG_J@Z TEXTEQU <__imp_?FindDeviceInstanceId@CDataCache@@QEAAPEAG_J@Z>
extern __imp_?FindDiskPtrFromDiskId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z:PANYARGS
?FindDiskPtrFromDiskId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z TEXTEQU <__imp_?FindDiskPtrFromDiskId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z>
extern __imp_?FindDriveLetter@CDataCache@@QEAAH_JAEAG@Z:PANYARGS
?FindDriveLetter@CDataCache@@QEAAH_JAEAG@Z TEXTEQU <__imp_?FindDriveLetter@CDataCache@@QEAAH_JAEAG@Z>
extern __imp_?FindDriveLetter@CTaskData@@QEAAX_JAEAG@Z:PANYARGS
?FindDriveLetter@CTaskData@@QEAAX_JAEAG@Z TEXTEQU <__imp_?FindDriveLetter@CTaskData@@QEAAX_JAEAG@Z>
extern __imp_?FindDriveLetterHelper@@YAHPEAUdriveletterinfo@@H_JAEAG@Z:PANYARGS
?FindDriveLetterHelper@@YAHPEAUdriveletterinfo@@H_JAEAG@Z TEXTEQU <__imp_?FindDriveLetterHelper@@YAHPEAUdriveletterinfo@@H_JAEAG@Z>
extern __imp_?FindFileSystem@CDataCache@@QEAAH_JAEAUfilesysteminfo@@@Z:PANYARGS
?FindFileSystem@CDataCache@@QEAAH_JAEAUfilesysteminfo@@@Z TEXTEQU <__imp_?FindFileSystem@CDataCache@@QEAAH_JAEAUfilesysteminfo@@@Z>
extern __imp_?FindFileSystem@CTaskData@@QEAAH_JAEAUfilesysteminfo@@@Z:PANYARGS
?FindFileSystem@CTaskData@@QEAAH_JAEAUfilesysteminfo@@@Z TEXTEQU <__imp_?FindFileSystem@CTaskData@@QEAAH_JAEAUfilesysteminfo@@@Z>
extern __imp_?FindRegionPtrFromRegionId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z:PANYARGS
?FindRegionPtrFromRegionId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z TEXTEQU <__imp_?FindRegionPtrFromRegionId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z>
extern __imp_?FindRegionPtrFromRegionId@CTaskData@@QEAAH_JPEAPEAVCDMNodeObj@@@Z:PANYARGS
?FindRegionPtrFromRegionId@CTaskData@@QEAAH_JPEAPEAVCDMNodeObj@@@Z TEXTEQU <__imp_?FindRegionPtrFromRegionId@CTaskData@@QEAAH_JPEAPEAVCDMNodeObj@@@Z>
extern __imp_?FindRegionPtrOnDiskFromRegionId@CDataCache@@QEAAHPEAVCDMNodeObj@@_JPEAPEAV2@AEAPEAU__POSITION@@@Z:PANYARGS
?FindRegionPtrOnDiskFromRegionId@CDataCache@@QEAAHPEAVCDMNodeObj@@_JPEAPEAV2@AEAPEAU__POSITION@@@Z TEXTEQU <__imp_?FindRegionPtrOnDiskFromRegionId@CDataCache@@QEAAHPEAVCDMNodeObj@@_JPEAPEAV2@AEAPEAU__POSITION@@@Z>
extern __imp_?GetAssignedDriveLetter@CTaskData@@QEAAH_JAEAG@Z:PANYARGS
?GetAssignedDriveLetter@CTaskData@@QEAAH_JAEAG@Z TEXTEQU <__imp_?GetAssignedDriveLetter@CTaskData@@QEAAH_JAEAG@Z>
extern __imp_?GetBootPort@CTaskData@@QEAAHXZ:PANYARGS
?GetBootPort@CTaskData@@QEAAHXZ TEXTEQU <__imp_?GetBootPort@CTaskData@@QEAAHXZ>
extern __imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ:PANYARGS
?GetBottomViewStyle@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ>
extern __imp_?GetColorRef@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetColorRef@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetColorRef@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetDMDataObjPtrFromId@CTaskData@@QEAAPEAVCDMNodeObj@@_J@Z:PANYARGS
?GetDMDataObjPtrFromId@CTaskData@@QEAAPEAVCDMNodeObj@@_J@Z TEXTEQU <__imp_?GetDMDataObjPtrFromId@CTaskData@@QEAAPEAVCDMNodeObj@@_J@Z>
extern __imp_?GetDeviceState@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetDeviceState@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetDeviceState@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetDeviceType@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetDeviceType@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetDeviceType@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetDiskCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z:PANYARGS
?GetDiskCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z TEXTEQU <__imp_?GetDiskCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z>
extern __imp_?GetDiskCookies@CTaskData@@QEAAXAEAKPEAPEA_JHKH@Z:PANYARGS
?GetDiskCookies@CTaskData@@QEAAXAEAKPEAPEA_JHKH@Z TEXTEQU <__imp_?GetDiskCookies@CTaskData@@QEAAXAEAKPEAPEA_JHKH@Z>
extern __imp_?GetDiskCookiesForSig@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PANYARGS
?GetDiskCookiesForSig@CTaskData@@QEAAXAEAKPEAPEA_J@Z TEXTEQU <__imp_?GetDiskCookiesForSig@CTaskData@@QEAAXAEAKPEAPEA_J@Z>
extern __imp_?GetDiskCookiesForUpgrade@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PANYARGS
?GetDiskCookiesForUpgrade@CTaskData@@QEAAXAEAKPEAPEA_J@Z TEXTEQU <__imp_?GetDiskCookiesForUpgrade@CTaskData@@QEAAXAEAKPEAPEA_J@Z>
extern __imp_?GetDiskCookiesToEncap@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PANYARGS
?GetDiskCookiesToEncap@CTaskData@@QEAAXAEAKPEAPEA_J@Z TEXTEQU <__imp_?GetDiskCookiesToEncap@CTaskData@@QEAAXAEAKPEAPEA_J@Z>
extern __imp_?GetDiskCount@CDataCache@@QEAAKXZ:PANYARGS
?GetDiskCount@CDataCache@@QEAAKXZ TEXTEQU <__imp_?GetDiskCount@CDataCache@@QEAAKXZ>
extern __imp_?GetDiskInfo@CDMNodeObj@@QEAAHAEAUdiskinfoex@@@Z:PANYARGS
?GetDiskInfo@CDMNodeObj@@QEAAHAEAUdiskinfoex@@@Z TEXTEQU <__imp_?GetDiskInfo@CDMNodeObj@@QEAAHAEAUdiskinfoex@@@Z>
extern __imp_?GetDiskInfoFromVolCookie@CTaskData@@QEAAX_JAEAHAEAKPEAPEA_JKH@Z:PANYARGS
?GetDiskInfoFromVolCookie@CTaskData@@QEAAX_JAEAHAEAKPEAPEA_JKH@Z TEXTEQU <__imp_?GetDiskInfoFromVolCookie@CTaskData@@QEAAX_JAEAHAEAKPEAPEA_JKH@Z>
extern __imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ:PANYARGS
?GetDiskScaling@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ>
extern __imp_?GetDiskSpec@CDMNodeObj@@QEAAHAEAUdiskspec@@@Z:PANYARGS
?GetDiskSpec@CDMNodeObj@@QEAAHAEAUdiskspec@@@Z TEXTEQU <__imp_?GetDiskSpec@CDMNodeObj@@QEAAHAEAUdiskspec@@@Z>
extern __imp_?GetDiskStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z:PANYARGS
?GetDiskStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z TEXTEQU <__imp_?GetDiskStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z>
extern __imp_?GetDiskStatusHelper@@YAHPEAUdiskinfoex@@AEAVCString@@H@Z:PANYARGS
?GetDiskStatusHelper@@YAHPEAUdiskinfoex@@AEAVCString@@H@Z TEXTEQU <__imp_?GetDiskStatusHelper@@YAHPEAUdiskinfoex@@AEAVCString@@H@Z>
extern __imp_?GetDiskTypeName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PANYARGS
?GetDiskTypeName@CDMNodeObj@@QEAAXAEAVCString@@@Z TEXTEQU <__imp_?GetDiskTypeName@CDMNodeObj@@QEAAXAEAVCString@@@Z>
extern __imp_?GetDiskTypeNameHelper@@YAXPEAUdiskinfoex@@AEAVCString@@G@Z:PANYARGS
?GetDiskTypeNameHelper@@YAXPEAUdiskinfoex@@AEAVCString@@G@Z TEXTEQU <__imp_?GetDiskTypeNameHelper@@YAXPEAUdiskinfoex@@AEAVCString@@G@Z>
extern __imp_?GetDriveLetter@CDMNodeObj@@QEAAXAEAG@Z:PANYARGS
?GetDriveLetter@CDMNodeObj@@QEAAXAEAG@Z TEXTEQU <__imp_?GetDriveLetter@CDMNodeObj@@QEAAXAEAG@Z>
extern __imp_?GetDriveLetters@CDataCache@@IEAAXAEAFPEAPEAGG@Z:PANYARGS
?GetDriveLetters@CDataCache@@IEAAXAEAFPEAPEAGG@Z TEXTEQU <__imp_?GetDriveLetters@CDataCache@@IEAAXAEAFPEAPEAGG@Z>
extern __imp_?GetDriveLetters@CTaskData@@QEAAXAEAFPEAPEAGG@Z:PANYARGS
?GetDriveLetters@CTaskData@@QEAAXAEAFPEAPEAGG@Z TEXTEQU <__imp_?GetDriveLetters@CTaskData@@QEAAXAEAFPEAPEAGG@Z>
extern __imp_?GetExtendedRegionColor@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetExtendedRegionColor@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetExtendedRegionColor@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetExtraRegionStatus@CDMNodeObj@@QEAAHAEAVCString@@H@Z:PANYARGS
?GetExtraRegionStatus@CDMNodeObj@@QEAAHAEAVCString@@H@Z TEXTEQU <__imp_?GetExtraRegionStatus@CDMNodeObj@@QEAAHAEAVCString@@H@Z>
extern __imp_?GetFileSystemLabel@CDMNodeObj@@QEAAXAEAVCString@@@Z:PANYARGS
?GetFileSystemLabel@CDMNodeObj@@QEAAXAEAVCString@@@Z TEXTEQU <__imp_?GetFileSystemLabel@CDMNodeObj@@QEAAXAEAVCString@@@Z>
extern __imp_?GetFileSystemName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PANYARGS
?GetFileSystemName@CDMNodeObj@@QEAAXAEAVCString@@@Z TEXTEQU <__imp_?GetFileSystemName@CDMNodeObj@@QEAAXAEAVCString@@@Z>
extern __imp_?GetFileSystemSize@CDMNodeObj@@QEAAXAEAJ@Z:PANYARGS
?GetFileSystemSize@CDMNodeObj@@QEAAXAEAJ@Z TEXTEQU <__imp_?GetFileSystemSize@CDMNodeObj@@QEAAXAEAJ@Z>
extern __imp_?GetFileSystemType@CDMNodeObj@@QEAAHXZ:PANYARGS
?GetFileSystemType@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?GetFileSystemType@CDMNodeObj@@QEAAHXZ>
extern __imp_?GetFileSystemTypes@CDataCache@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z:PANYARGS
?GetFileSystemTypes@CDataCache@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z TEXTEQU <__imp_?GetFileSystemTypes@CDataCache@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z>
extern __imp_?GetFileSystemTypes@CTaskData@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z:PANYARGS
?GetFileSystemTypes@CTaskData@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z TEXTEQU <__imp_?GetFileSystemTypes@CTaskData@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z>
extern __imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ:PANYARGS
?GetFilterToggle@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ>
extern __imp_?GetFlags@CDMNodeObj@@QEAAJXZ:PANYARGS
?GetFlags@CDMNodeObj@@QEAAJXZ TEXTEQU <__imp_?GetFlags@CDMNodeObj@@QEAAJXZ>
extern __imp_?GetIVolumeClientVersion@CDMNodeObj@@QEAAFXZ:PANYARGS
?GetIVolumeClientVersion@CDMNodeObj@@QEAAFXZ TEXTEQU <__imp_?GetIVolumeClientVersion@CDMNodeObj@@QEAAFXZ>
extern __imp_?GetIVolumeClientVersion@CTaskData@@QEAAFXZ:PANYARGS
?GetIVolumeClientVersion@CTaskData@@QEAAFXZ TEXTEQU <__imp_?GetIVolumeClientVersion@CTaskData@@QEAAFXZ>
extern __imp_?GetIconId@CDMNodeObj@@QEAAIH@Z:PANYARGS
?GetIconId@CDMNodeObj@@QEAAIH@Z TEXTEQU <__imp_?GetIconId@CDMNodeObj@@QEAAIH@Z>
extern __imp_?GetImageNum@CDMNodeObj@@QEAAHXZ:PANYARGS
?GetImageNum@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?GetImageNum@CDMNodeObj@@QEAAHXZ>
extern __imp_?GetLastKnownState@CDataCache@@QEAA_J_J@Z:PANYARGS
?GetLastKnownState@CDataCache@@QEAA_J_J@Z TEXTEQU <__imp_?GetLastKnownState@CDataCache@@QEAA_J_J@Z>
extern __imp_?GetLayoutType@CDMNodeObj@@QEAA?AW4_LAYOUT_TYPES@@XZ:PANYARGS
?GetLayoutType@CDMNodeObj@@QEAA?AW4_LAYOUT_TYPES@@XZ TEXTEQU <__imp_?GetLayoutType@CDMNodeObj@@QEAA?AW4_LAYOUT_TYPES@@XZ>
extern __imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ:PANYARGS
?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ TEXTEQU <__imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ>
extern __imp_?GetListBehavior@CDMSnapin@@QEAAHXZ:PANYARGS
?GetListBehavior@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetListBehavior@CDMSnapin@@QEAAHXZ>
extern __imp_?GetLogicalDriveCount@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetLogicalDriveCount@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetLogicalDriveCount@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetLongName@CDMNodeObj@@QEAAXAEAVCString@@H@Z:PANYARGS
?GetLongName@CDMNodeObj@@QEAAXAEAVCString@@H@Z TEXTEQU <__imp_?GetLongName@CDMNodeObj@@QEAAXAEAVCString@@H@Z>
extern __imp_?GetMMCWindow@CDMComponentData@@QEAAPEAUHWND__@@XZ:PANYARGS
?GetMMCWindow@CDMComponentData@@QEAAPEAUHWND__@@XZ TEXTEQU <__imp_?GetMMCWindow@CDMComponentData@@QEAAPEAUHWND__@@XZ>
extern __imp_?GetMaxAdjustedFreeSize@CDMNodeObj@@QEAAXAEA_J@Z:PANYARGS
?GetMaxAdjustedFreeSize@CDMNodeObj@@QEAAXAEA_J@Z TEXTEQU <__imp_?GetMaxAdjustedFreeSize@CDMNodeObj@@QEAAXAEA_J@Z>
extern __imp_?GetMaxPartitionCount@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetMaxPartitionCount@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetMaxPartitionCount@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetMinMaxPartitionSizes@CDataCache@@IEAAX_JAEAK1@Z:PANYARGS
?GetMinMaxPartitionSizes@CDataCache@@IEAAX_JAEAK1@Z TEXTEQU <__imp_?GetMinMaxPartitionSizes@CDataCache@@IEAAX_JAEAK1@Z>
extern __imp_?GetMinMaxPartitionSizes@CTaskData@@QEAAX_JAEAK1@Z:PANYARGS
?GetMinMaxPartitionSizes@CTaskData@@QEAAX_JAEAK1@Z TEXTEQU <__imp_?GetMinMaxPartitionSizes@CTaskData@@QEAAX_JAEAK1@Z>
extern __imp_?GetName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PANYARGS
?GetName@CDMNodeObj@@QEAAXAEAVCString@@@Z TEXTEQU <__imp_?GetName@CDMNodeObj@@QEAAXAEAVCString@@@Z>
extern __imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetNumMembers@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetNumRegions@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetNumRegions@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetNumRegions@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetObjectId@CDMNodeObj@@QEAAXAEA_J@Z:PANYARGS
?GetObjectId@CDMNodeObj@@QEAAXAEA_J@Z TEXTEQU <__imp_?GetObjectId@CDMNodeObj@@QEAAXAEA_J@Z>
extern __imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ:PANYARGS
?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ TEXTEQU <__imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ>
extern __imp_?GetParentDiskPtr@CDMNodeObj@@QEAAPEAV1@XZ:PANYARGS
?GetParentDiskPtr@CDMNodeObj@@QEAAPEAV1@XZ TEXTEQU <__imp_?GetParentDiskPtr@CDMNodeObj@@QEAAPEAV1@XZ>
extern __imp_?GetParentVolumePtr@CDMNodeObj@@QEAAPEAV1@XZ:PANYARGS
?GetParentVolumePtr@CDMNodeObj@@QEAAPEAV1@XZ TEXTEQU <__imp_?GetParentVolumePtr@CDMNodeObj@@QEAAPEAV1@XZ>
extern __imp_?GetPartitionStyle@CDMNodeObj@@QEAA?AW4_PARTITIONSTYLE@@XZ:PANYARGS
?GetPartitionStyle@CDMNodeObj@@QEAA?AW4_PARTITIONSTYLE@@XZ TEXTEQU <__imp_?GetPartitionStyle@CDMNodeObj@@QEAA?AW4_PARTITIONSTYLE@@XZ>
extern __imp_?GetPartitionStyleString@CDMNodeObj@@QEAAXAEAVCString@@H@Z:PANYARGS
?GetPartitionStyleString@CDMNodeObj@@QEAAXAEAVCString@@H@Z TEXTEQU <__imp_?GetPartitionStyleString@CDMNodeObj@@QEAAXAEAVCString@@H@Z>
extern __imp_?GetPartitionStyleStringHelper@@YAXW4_PARTITIONSTYLE@@AEAVCString@@HKKH@Z:PANYARGS
?GetPartitionStyleStringHelper@@YAXW4_PARTITIONSTYLE@@AEAVCString@@HKKH@Z TEXTEQU <__imp_?GetPartitionStyleStringHelper@@YAXW4_PARTITIONSTYLE@@AEAVCString@@HKKH@Z>
extern __imp_?GetPatternRef@CDMNodeObj@@QEAAHXZ:PANYARGS
?GetPatternRef@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?GetPatternRef@CDMNodeObj@@QEAAHXZ>
extern __imp_?GetPort@CDMNodeObj@@QEAAHXZ:PANYARGS
?GetPort@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?GetPort@CDMNodeObj@@QEAAHXZ>
extern __imp_?GetPrimaryPartitionCount@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetPrimaryPartitionCount@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetPrimaryPartitionCount@CDMNodeObj@@QEAAKXZ>
extern __imp_GetPropertyPageData:PANYARGS
GetPropertyPageData TEXTEQU <__imp_GetPropertyPageData>
extern __imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z:PANYARGS
?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z TEXTEQU <__imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z>
extern __imp_?GetRegionInfo@CDMNodeObj@@QEAAHAEAUregioninfoex@@@Z:PANYARGS
?GetRegionInfo@CDMNodeObj@@QEAAHAEAUregioninfoex@@@Z TEXTEQU <__imp_?GetRegionInfo@CDMNodeObj@@QEAAHAEAUregioninfoex@@@Z>
extern __imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ:PANYARGS
?GetRegionScaling@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ>
extern __imp_?GetResultStringArray@CDMNodeObj@@QEAAHAEAVCStringArray@@@Z:PANYARGS
?GetResultStringArray@CDMNodeObj@@QEAAHAEAVCStringArray@@@Z TEXTEQU <__imp_?GetResultStringArray@CDMNodeObj@@QEAAHAEAVCStringArray@@@Z>
extern __imp_?GetRevertDiskName@CServerRequests@@QEAAAEAVCString@@XZ:PANYARGS
?GetRevertDiskName@CServerRequests@@QEAAAEAVCString@@XZ TEXTEQU <__imp_?GetRevertDiskName@CServerRequests@@QEAAAEAVCString@@XZ>
extern __imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ:PANYARGS
?GetServerName@CDataCache@@QEAA?AVCString@@XZ TEXTEQU <__imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ>
extern __imp_?GetServerName@CTaskData@@QEAA?AVCString@@XZ:PANYARGS
?GetServerName@CTaskData@@QEAA?AVCString@@XZ TEXTEQU <__imp_?GetServerName@CTaskData@@QEAA?AVCString@@XZ>
extern __imp_?GetShortName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PANYARGS
?GetShortName@CDMNodeObj@@QEAAXAEAVCString@@@Z TEXTEQU <__imp_?GetShortName@CDMNodeObj@@QEAAXAEAVCString@@@Z>
extern __imp_?GetSize@CDMNodeObj@@QEAAXAEAJ@Z:PANYARGS
?GetSize@CDMNodeObj@@QEAAXAEAJ@Z TEXTEQU <__imp_?GetSize@CDMNodeObj@@QEAAXAEAJ@Z>
extern __imp_?GetSize@CDMNodeObj@@QEAAXAEA_JH@Z:PANYARGS
?GetSize@CDMNodeObj@@QEAAXAEA_JH@Z TEXTEQU <__imp_?GetSize@CDMNodeObj@@QEAAXAEA_JH@Z>
extern __imp_?GetSizeString@CDMNodeObj@@QEAAXAEAVCString@@@Z:PANYARGS
?GetSizeString@CDMNodeObj@@QEAAXAEAVCString@@@Z TEXTEQU <__imp_?GetSizeString@CDMNodeObj@@QEAAXAEAVCString@@@Z>
extern __imp_?GetStartOffset@CDMNodeObj@@QEAA_JXZ:PANYARGS
?GetStartOffset@CDMNodeObj@@QEAA_JXZ TEXTEQU <__imp_?GetStartOffset@CDMNodeObj@@QEAA_JXZ>
extern __imp_?GetStatus@CDMNodeObj@@QEAAHXZ:PANYARGS
?GetStatus@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?GetStatus@CDMNodeObj@@QEAAHXZ>
extern __imp_?GetStorageType@CDMNodeObj@@QEAA?AW4_STORAGE_TYPES@@XZ:PANYARGS
?GetStorageType@CDMNodeObj@@QEAA?AW4_STORAGE_TYPES@@XZ TEXTEQU <__imp_?GetStorageType@CDMNodeObj@@QEAA?AW4_STORAGE_TYPES@@XZ>
extern __imp_?GetStorageType@CDMNodeObj@@QEAAXAEAVCString@@H@Z:PANYARGS
?GetStorageType@CDMNodeObj@@QEAAXAEAVCString@@H@Z TEXTEQU <__imp_?GetStorageType@CDMNodeObj@@QEAAXAEAVCString@@H@Z>
extern __imp_?GetStringFromRc@@YA?AVCString@@K@Z:PANYARGS
?GetStringFromRc@@YA?AVCString@@K@Z TEXTEQU <__imp_?GetStringFromRc@@YA?AVCString@@K@Z>
extern __imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ:PANYARGS
?GetTopViewStyle@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ>
extern __imp_?GetUIState@CTaskData@@QEAAKXZ:PANYARGS
?GetUIState@CTaskData@@QEAAKXZ TEXTEQU <__imp_?GetUIState@CTaskData@@QEAAKXZ>
extern __imp_?GetUnallocSpace@CDMNodeObj@@QEAA_JH@Z:PANYARGS
?GetUnallocSpace@CDMNodeObj@@QEAA_JH@Z TEXTEQU <__imp_?GetUnallocSpace@CDMNodeObj@@QEAA_JH@Z>
extern __imp_?GetVolumeCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z:PANYARGS
?GetVolumeCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z TEXTEQU <__imp_?GetVolumeCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z>
extern __imp_?GetVolumeCount@CDataCache@@QEAAKXZ:PANYARGS
?GetVolumeCount@CDataCache@@QEAAKXZ TEXTEQU <__imp_?GetVolumeCount@CDataCache@@QEAAKXZ>
extern __imp_?GetVolumeInfo@CDMNodeObj@@QEAAHAEAUvolumeinfo@@@Z:PANYARGS
?GetVolumeInfo@CDMNodeObj@@QEAAHAEAUvolumeinfo@@@Z TEXTEQU <__imp_?GetVolumeInfo@CDMNodeObj@@QEAAHAEAUvolumeinfo@@@Z>
extern __imp_?GetVolumeStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z:PANYARGS
?GetVolumeStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z TEXTEQU <__imp_?GetVolumeStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z>
extern __imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ:PANYARGS
?GetWaitCursor@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ>
extern __imp_?HasExtendedPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?HasExtendedPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?HasExtendedPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?HasNTFSwithDriveLetter@CDataCache@@QEAAHXZ:PANYARGS
?HasNTFSwithDriveLetter@CDataCache@@QEAAHXZ TEXTEQU <__imp_?HasNTFSwithDriveLetter@CDataCache@@QEAAHXZ>
extern __imp_?HasNTFSwithDriveLetter@CTaskData@@QEAAHXZ:PANYARGS
?HasNTFSwithDriveLetter@CTaskData@@QEAAHXZ TEXTEQU <__imp_?HasNTFSwithDriveLetter@CTaskData@@QEAAHXZ>
extern __imp_?HasVMDisk@CDataCache@@QEAAHXZ:PANYARGS
?HasVMDisk@CDataCache@@QEAAHXZ TEXTEQU <__imp_?HasVMDisk@CDataCache@@QEAAHXZ>
extern __imp_?IsActive@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsActive@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsActive@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsAlpha@CDataCache@@QEAAHXZ:PANYARGS
?IsAlpha@CDataCache@@QEAAHXZ TEXTEQU <__imp_?IsAlpha@CDataCache@@QEAAHXZ>
extern __imp_?IsAlpha@CTaskData@@QEAAHXZ:PANYARGS
?IsAlpha@CTaskData@@QEAAHXZ TEXTEQU <__imp_?IsAlpha@CTaskData@@QEAAHXZ>
extern __imp_?IsCurrBootVolume@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsCurrBootVolume@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsCurrBootVolume@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsCurrSystemVolume@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsCurrSystemVolume@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsCurrSystemVolume@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsDiskEmpty@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsDiskEmpty@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsDiskEmpty@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsDynamic1394@CDataCache@@QEAAHXZ:PANYARGS
?IsDynamic1394@CDataCache@@QEAAHXZ TEXTEQU <__imp_?IsDynamic1394@CDataCache@@QEAAHXZ>
extern __imp_?IsEECoveredGPTDisk@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsEECoveredGPTDisk@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsEECoveredGPTDisk@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsESPPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsESPPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsESPPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsEfi@CDataCache@@QEAAHXZ:PANYARGS
?IsEfi@CDataCache@@QEAAHXZ TEXTEQU <__imp_?IsEfi@CDataCache@@QEAAHXZ>
extern __imp_?IsEfi@CTaskData@@QEAAHXZ:PANYARGS
?IsEfi@CTaskData@@QEAAHXZ TEXTEQU <__imp_?IsEfi@CTaskData@@QEAAHXZ>
extern __imp_?IsFTVolume@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsFTVolume@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsFTVolume@CDMNodeObj@@QEAAHXZ>
extern __imp_IsFailPopupMgmtSupported:PANYARGS
IsFailPopupMgmtSupported TEXTEQU <__imp_IsFailPopupMgmtSupported>
extern __imp_?IsFakeVolume@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsFakeVolume@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsFakeVolume@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsFirstFreeRegion@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsFirstFreeRegion@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsFirstFreeRegion@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsHiddenRegion@@YAHAEAUregioninfoex@@@Z:PANYARGS
?IsHiddenRegion@@YAHAEAUregioninfoex@@@Z TEXTEQU <__imp_?IsHiddenRegion@@YAHAEAUregioninfoex@@@Z>
extern __imp_?IsHiddenRegion@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsHiddenRegion@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsHiddenRegion@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsInFlux@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsInFlux@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsInFlux@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsLocalMachine@CTaskData@@QEAAHXZ:PANYARGS
?IsLocalMachine@CTaskData@@QEAAHXZ TEXTEQU <__imp_?IsLocalMachine@CTaskData@@QEAAHXZ>
extern __imp_?IsMbrEEPartition@@YAHAEAUregioninfoex@@@Z:PANYARGS
?IsMbrEEPartition@@YAHAEAUregioninfoex@@@Z TEXTEQU <__imp_?IsMbrEEPartition@@YAHAEAUregioninfoex@@@Z>
extern __imp_?IsMbrEEPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsMbrEEPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsMbrEEPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsMember@CDMNodeObj@@QEAAHPEAV1@@Z:PANYARGS
?IsMember@CDMNodeObj@@QEAAHPEAV1@@Z TEXTEQU <__imp_?IsMember@CDMNodeObj@@QEAAHPEAV1@@Z>
extern __imp_?IsNEC_98Disk@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsNEC_98Disk@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsNEC_98Disk@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsNEC_98Server@CDataCache@@QEAAHXZ:PANYARGS
?IsNEC_98Server@CDataCache@@QEAAHXZ TEXTEQU <__imp_?IsNEC_98Server@CDataCache@@QEAAHXZ>
extern __imp_?IsNEC_98Server@CTaskData@@QEAAHXZ:PANYARGS
?IsNEC_98Server@CTaskData@@QEAAHXZ TEXTEQU <__imp_?IsNEC_98Server@CTaskData@@QEAAHXZ>
extern __imp_?IsNTServer@CTaskData@@QEAAHXZ:PANYARGS
?IsNTServer@CTaskData@@QEAAHXZ TEXTEQU <__imp_?IsNTServer@CTaskData@@QEAAHXZ>
extern __imp_?IsOemPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsOemPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsOemPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsPersonalOrLapTopServer@CDataCache@@QEAAHXZ:PANYARGS
?IsPersonalOrLapTopServer@CDataCache@@QEAAHXZ TEXTEQU <__imp_?IsPersonalOrLapTopServer@CDataCache@@QEAAHXZ>
extern __imp_IsRequestPending:PANYARGS
IsRequestPending TEXTEQU <__imp_IsRequestPending>
extern __imp_?IsRevertable@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsRevertable@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsRevertable@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsSecureSystemPartition@CTaskData@@QEAAHXZ:PANYARGS
?IsSecureSystemPartition@CTaskData@@QEAAHXZ TEXTEQU <__imp_?IsSecureSystemPartition@CTaskData@@QEAAHXZ>
extern __imp_?IsUnknownPartition@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsUnknownPartition@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsUnknownPartition@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsUpgradeable@CDMNodeObj@@QEAAHXZ:PANYARGS
?IsUpgradeable@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?IsUpgradeable@CDMNodeObj@@QEAAHXZ>
extern __imp_?IsWolfpack@CTaskData@@QEAAHXZ:PANYARGS
?IsWolfpack@CTaskData@@QEAAHXZ TEXTEQU <__imp_?IsWolfpack@CTaskData@@QEAAHXZ>
extern __imp_?LoadData@CDMComponentData@@QEAAXJ@Z:PANYARGS
?LoadData@CDMComponentData@@QEAAXJ@Z TEXTEQU <__imp_?LoadData@CDMComponentData@@QEAAXJ@Z>
extern __imp_LoadPropertyPageData:PANYARGS
LoadPropertyPageData TEXTEQU <__imp_LoadPropertyPageData>
extern __imp_?ParseDeviceName@@YAXPEAH00PEAG@Z:PANYARGS
?ParseDeviceName@@YAXPEAH00PEAG@Z TEXTEQU <__imp_?ParseDeviceName@@YAXPEAH00PEAG@Z>
extern __imp_?PopUpInit@CContextMenu@@QEAAXPEAVCDMNodeObj@@AEAHH@Z:PANYARGS
?PopUpInit@CContextMenu@@QEAAXPEAVCDMNodeObj@@AEAHH@Z TEXTEQU <__imp_?PopUpInit@CContextMenu@@QEAAXPEAVCDMNodeObj@@AEAHH@Z>
extern __imp_?PopulateDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z:PANYARGS
?PopulateDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z TEXTEQU <__imp_?PopulateDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z>
extern __imp_?PopulateEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z:PANYARGS
?PopulateEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z TEXTEQU <__imp_?PopulateEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z>
extern __imp_?RecalculateSpace@CDMNodeObj@@QEAAXXZ:PANYARGS
?RecalculateSpace@CDMNodeObj@@QEAAXXZ TEXTEQU <__imp_?RecalculateSpace@CDMNodeObj@@QEAAXXZ>
extern __imp_?RefreshDiskView@CDMComponentData@@QEAAXXZ:PANYARGS
?RefreshDiskView@CDMComponentData@@QEAAXXZ TEXTEQU <__imp_?RefreshDiskView@CDMComponentData@@QEAAXXZ>
extern __imp_?RefreshFileSys@CContextMenu@@QEAAX_J@Z:PANYARGS
?RefreshFileSys@CContextMenu@@QEAAX_J@Z TEXTEQU <__imp_?RefreshFileSys@CContextMenu@@QEAAX_J@Z>
extern __imp_?ReloadData@CDMComponentData@@QEAAXXZ:PANYARGS
?ReloadData@CDMComponentData@@QEAAXXZ TEXTEQU <__imp_?ReloadData@CDMComponentData@@QEAAXXZ>
extern __imp_?RoundUpToMB@@YA_J_J@Z:PANYARGS
?RoundUpToMB@@YA_J_J@Z TEXTEQU <__imp_?RoundUpToMB@@YA_J_J@Z>
extern __imp_?SetDescriptionBarText@CDMSnapin@@QEAAXXZ:PANYARGS
?SetDescriptionBarText@CDMSnapin@@QEAAXXZ TEXTEQU <__imp_?SetDescriptionBarText@CDMSnapin@@QEAAXXZ>
extern __imp_?SetDiskList@CDataCache@@QEAAXPEAUdiskinfoex@@K@Z:PANYARGS
?SetDiskList@CDataCache@@QEAAXPEAUdiskinfoex@@K@Z TEXTEQU <__imp_?SetDiskList@CDataCache@@QEAAXPEAUdiskinfoex@@K@Z>
extern __imp_?SetDriveLetterInUse@CDataCache@@QEAAXGH@Z:PANYARGS
?SetDriveLetterInUse@CDataCache@@QEAAXGH@Z TEXTEQU <__imp_?SetDriveLetterInUse@CDataCache@@QEAAXGH@Z>
extern __imp_?SetFSId@CDMNodeObj@@QEAAX_J@Z:PANYARGS
?SetFSId@CDMNodeObj@@QEAAX_J@Z TEXTEQU <__imp_?SetFSId@CDMNodeObj@@QEAAX_J@Z>
extern __imp_?SetOcxViewType@CDMComponentData@@QEAAXXZ:PANYARGS
?SetOcxViewType@CDMComponentData@@QEAAXXZ TEXTEQU <__imp_?SetOcxViewType@CDMComponentData@@QEAAXXZ>
extern __imp_?SetOcxViewTypeForce@CDMComponentData@@QEAAXXZ:PANYARGS
?SetOcxViewTypeForce@CDMComponentData@@QEAAXXZ TEXTEQU <__imp_?SetOcxViewTypeForce@CDMComponentData@@QEAAXXZ>
extern __imp_?SetUIState@CTaskData@@QEAAXK@Z:PANYARGS
?SetUIState@CTaskData@@QEAAXK@Z TEXTEQU <__imp_?SetUIState@CTaskData@@QEAAXK@Z>
extern __imp_?SetVolumeList@CDataCache@@QEAAXPEAUvolumeinfo@@K@Z:PANYARGS
?SetVolumeList@CDataCache@@QEAAXPEAUvolumeinfo@@K@Z TEXTEQU <__imp_?SetVolumeList@CDataCache@@QEAAXPEAUvolumeinfo@@K@Z>
extern __imp_?ShowContextMenu@CContextMenu@@QEAAJPEAVCWnd@@JJ_J@Z:PANYARGS
?ShowContextMenu@CContextMenu@@QEAAJPEAVCWnd@@JJ_J@Z TEXTEQU <__imp_?ShowContextMenu@CContextMenu@@QEAAJPEAVCWnd@@JJ_J@Z>
extern __imp_?SupportGpt@CDataCache@@QEAAHXZ:PANYARGS
?SupportGpt@CDataCache@@QEAAHXZ TEXTEQU <__imp_?SupportGpt@CDataCache@@QEAAHXZ>
extern __imp_?SupportGpt@CTaskData@@QEAAHXZ:PANYARGS
?SupportGpt@CTaskData@@QEAAHXZ TEXTEQU <__imp_?SupportGpt@CTaskData@@QEAAHXZ>
extern __imp_?UIStateChange@CDMComponentData@@QEAAXK@Z:PANYARGS
?UIStateChange@CDMComponentData@@QEAAXK@Z TEXTEQU <__imp_?UIStateChange@CDMComponentData@@QEAAXK@Z>
extern __imp_?UpDateConsoleView@CDMSnapin@@QEAAXXZ:PANYARGS
?UpDateConsoleView@CDMSnapin@@QEAAXXZ TEXTEQU <__imp_?UpDateConsoleView@CDMSnapin@@QEAAXXZ>
extern __imp_?VolumeContainsActiveRegion@CDMNodeObj@@QEAAHXZ:PANYARGS
?VolumeContainsActiveRegion@CDMNodeObj@@QEAAHXZ TEXTEQU <__imp_?VolumeContainsActiveRegion@CDMNodeObj@@QEAAHXZ>
extern __imp_?namecmp@@YAHPEBG0@Z:PANYARGS
?namecmp@@YAHPEBG0@Z TEXTEQU <__imp_?namecmp@@YAHPEBG0@Z>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
