extern __imp_CoDisableDynamicVolumes:PANYARGS
CoDisableDynamicVolumes TEXTEQU <__imp_CoDisableDynamicVolumes>
extern __imp_AddEntryBootFileGpt:PANYARGS
AddEntryBootFileGpt TEXTEQU <__imp_AddEntryBootFileGpt>
extern __imp_AddEntryBootFileMbr:PANYARGS
AddEntryBootFileMbr TEXTEQU <__imp_AddEntryBootFileMbr>
extern __imp_DisplayError:PANYARGS
DisplayError TEXTEQU <__imp_DisplayError>
extern __imp_DisplayErrorRgszw:PANYARGS
DisplayErrorRgszw TEXTEQU <__imp_DisplayErrorRgszw>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DmCommonNtOpenFile:PANYARGS
DmCommonNtOpenFile TEXTEQU <__imp_DmCommonNtOpenFile>
extern __imp_DynamicSupport:PANYARGS
DynamicSupport TEXTEQU <__imp_DynamicSupport>
extern __imp_FTrace:PANYARGS
FTrace TEXTEQU <__imp_FTrace>
extern __imp_FTraceValist:PANYARGS
FTraceValist TEXTEQU <__imp_FTraceValist>
extern __imp_FreeRgszw:PANYARGS
FreeRgszw TEXTEQU <__imp_FreeRgszw>
extern __imp_GetErrorData:PANYARGS
GetErrorData TEXTEQU <__imp_GetErrorData>
extern __imp_GetInstallDirectoryPath:PANYARGS
GetInstallDirectoryPath TEXTEQU <__imp_GetInstallDirectoryPath>
extern __imp_GetSystemVolume:PANYARGS
GetSystemVolume TEXTEQU <__imp_GetSystemVolume>
extern __imp_IsPersonalSKU:PANYARGS
IsPersonalSKU TEXTEQU <__imp_IsPersonalSKU>
extern __imp_LowAcquirePrivilege:PANYARGS
LowAcquirePrivilege TEXTEQU <__imp_LowAcquirePrivilege>
extern __imp_LowGetPartitionInfo:PANYARGS
LowGetPartitionInfo TEXTEQU <__imp_LowGetPartitionInfo>
extern __imp_LowNtAddBootEntry:PANYARGS
LowNtAddBootEntry TEXTEQU <__imp_LowNtAddBootEntry>
extern __imp_LowNtReadFile:PANYARGS
LowNtReadFile TEXTEQU <__imp_LowNtReadFile>
extern __imp_LowNtReadOnlyAttributeOff:PANYARGS
LowNtReadOnlyAttributeOff TEXTEQU <__imp_LowNtReadOnlyAttributeOff>
extern __imp_LowNtWriteFile:PANYARGS
LowNtWriteFile TEXTEQU <__imp_LowNtWriteFile>
extern __imp_RgszwDupRgszw:PANYARGS
RgszwDupRgszw TEXTEQU <__imp_RgszwDupRgszw>
extern __imp_RgszwFromArgs:PANYARGS
RgszwFromArgs TEXTEQU <__imp_RgszwFromArgs>
extern __imp_RgszwFromValist:PANYARGS
RgszwFromValist TEXTEQU <__imp_RgszwFromValist>
extern __imp_ShowMessage:PANYARGS
ShowMessage TEXTEQU <__imp_ShowMessage>
extern __imp_ShowMessageValist:PANYARGS
ShowMessageValist TEXTEQU <__imp_ShowMessageValist>
extern __imp_SzwDupSzw:PANYARGS
SzwDupSzw TEXTEQU <__imp_SzwDupSzw>
extern __imp_SzwFromSza:PANYARGS
SzwFromSza TEXTEQU <__imp_SzwFromSza>
extern __imp_TranslateError:PANYARGS
TranslateError TEXTEQU <__imp_TranslateError>
