extern __imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z:PANYARGS
?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z TEXTEQU <__imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z>
extern __imp_CreateDataCacheZ:PANYARGS
CreateDataCacheZ TEXTEQU <__imp_CreateDataCacheZ>
extern __imp_CreateServerRequestsZ:PANYARGS
CreateServerRequestsZ TEXTEQU <__imp_CreateServerRequestsZ>
extern __imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ:PANYARGS
?GetBottomViewStyle@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ>
extern __imp_?GetDiskCount@CDataCache@@QEAAKXZ:PANYARGS
?GetDiskCount@CDataCache@@QEAAKXZ TEXTEQU <__imp_?GetDiskCount@CDataCache@@QEAAKXZ>
extern __imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ:PANYARGS
?GetDiskScaling@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ>
extern __imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ:PANYARGS
?GetFilterToggle@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ>
extern __imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ:PANYARGS
?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ TEXTEQU <__imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ>
extern __imp_?GetListBehavior@CDMSnapin@@QEAAHXZ:PANYARGS
?GetListBehavior@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetListBehavior@CDMSnapin@@QEAAHXZ>
extern __imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ:PANYARGS
?GetNumMembers@CDMNodeObj@@QEAAKXZ TEXTEQU <__imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ>
extern __imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ:PANYARGS
?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ TEXTEQU <__imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ>
extern __imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z:PANYARGS
?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z TEXTEQU <__imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z>
extern __imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ:PANYARGS
?GetRegionScaling@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ>
extern __imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ:PANYARGS
?GetServerName@CDataCache@@QEAA?AVCString@@XZ TEXTEQU <__imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ>
extern __imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ:PANYARGS
?GetTopViewStyle@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ>
extern __imp_?GetVolumeCount@CDataCache@@QEAAKXZ:PANYARGS
?GetVolumeCount@CDataCache@@QEAAKXZ TEXTEQU <__imp_?GetVolumeCount@CDataCache@@QEAAKXZ>
extern __imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ:PANYARGS
?GetWaitCursor@CDMSnapin@@QEAAHXZ TEXTEQU <__imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ>
