extern __imp_NPAddConnection:PANYARGS
NPAddConnection TEXTEQU <__imp_NPAddConnection>
extern __imp_NPAddConnection3:PANYARGS
NPAddConnection3 TEXTEQU <__imp_NPAddConnection3>
extern __imp_NPCancelConnection:PANYARGS
NPCancelConnection TEXTEQU <__imp_NPCancelConnection>
extern __imp_NPCloseEnum:PANYARGS
NPCloseEnum TEXTEQU <__imp_NPCloseEnum>
extern __imp_NPEnumResource:PANYARGS
NPEnumResource TEXTEQU <__imp_NPEnumResource>
extern __imp_NPGetCaps:PANYARGS
NPGetCaps TEXTEQU <__imp_NPGetCaps>
extern __imp_NPGetConnection:PANYARGS
NPGetConnection TEXTEQU <__imp_NPGetConnection>
extern __imp_NPGetResourceInformation:PANYARGS
NPGetResourceInformation TEXTEQU <__imp_NPGetResourceInformation>
extern __imp_NPGetResourceParent:PANYARGS
NPGetResourceParent TEXTEQU <__imp_NPGetResourceParent>
extern __imp_NPGetUniversalName:PANYARGS
NPGetUniversalName TEXTEQU <__imp_NPGetUniversalName>
extern __imp_drprov_ordinal11:PANYARGS
drprov_ordinal11 TEXTEQU <__imp_drprov_ordinal11>
extern __imp_NPOpenEnum:PANYARGS
NPOpenEnum TEXTEQU <__imp_NPOpenEnum>
