extern __imp_DhcpAddServerDS:PANYARGS
DhcpAddServerDS TEXTEQU <__imp_DhcpAddServerDS>
extern __imp_DhcpDeleteServerDS:PANYARGS
DhcpDeleteServerDS TEXTEQU <__imp_DhcpDeleteServerDS>
extern __imp_DhcpDsAddServer:PANYARGS
DhcpDsAddServer TEXTEQU <__imp_DhcpDsAddServer>
extern __imp_DhcpDsCleanupDS:PANYARGS
DhcpDsCleanupDS TEXTEQU <__imp_DhcpDsCleanupDS>
extern __imp_DhcpDsDelServer:PANYARGS
DhcpDsDelServer TEXTEQU <__imp_DhcpDsDelServer>
extern __imp_DhcpDsEnumServers:PANYARGS
DhcpDsEnumServers TEXTEQU <__imp_DhcpDsEnumServers>
extern __imp_DhcpDsGetAttribs:PANYARGS
DhcpDsGetAttribs TEXTEQU <__imp_DhcpDsGetAttribs>
extern __imp_DhcpDsGetLists:PANYARGS
DhcpDsGetLists TEXTEQU <__imp_DhcpDsGetLists>
extern __imp_DhcpDsGetRoot:PANYARGS
DhcpDsGetRoot TEXTEQU <__imp_DhcpDsGetRoot>
extern __imp_DhcpDsInitDS:PANYARGS
DhcpDsInitDS TEXTEQU <__imp_DhcpDsInitDS>
extern __imp_DhcpDsSetLists:PANYARGS
DhcpDsSetLists TEXTEQU <__imp_DhcpDsSetLists>
extern __imp_DhcpDsValidateService:PANYARGS
DhcpDsValidateService TEXTEQU <__imp_DhcpDsValidateService>
extern __imp_DhcpEnumServersDS:PANYARGS
DhcpEnumServersDS TEXTEQU <__imp_DhcpEnumServersDS>
extern __imp_StoreBeginSearch:PANYARGS
StoreBeginSearch TEXTEQU <__imp_StoreBeginSearch>
extern __imp_StoreCleanupHandle:PANYARGS
StoreCleanupHandle TEXTEQU <__imp_StoreCleanupHandle>
extern __imp_StoreCollectAttributes:PANYARGS
StoreCollectAttributes TEXTEQU <__imp_StoreCollectAttributes>
extern __imp_StoreCreateObjectVA:PANYARGS
StoreCreateObjectV  TEXTEQU <__imp_StoreCreateObjectVA>
extern __imp_StoreDeleteObject:PANYARGS
StoreDeleteObject TEXTEQU <__imp_StoreDeleteObject>
extern __imp_StoreEndSearch:PANYARGS
StoreEndSearch TEXTEQU <__imp_StoreEndSearch>
extern __imp_StoreGetHandle:PANYARGS
StoreGetHandle TEXTEQU <__imp_StoreGetHandle>
extern __imp_StoreInitHandle:PANYARGS
StoreInitHandle TEXTEQU <__imp_StoreInitHandle>
extern __imp_StoreSearchGetNext:PANYARGS
StoreSearchGetNext TEXTEQU <__imp_StoreSearchGetNext>
extern __imp_StoreSetSearchOneLevel:PANYARGS
StoreSetSearchOneLevel TEXTEQU <__imp_StoreSetSearchOneLevel>
extern __imp_StoreSetSearchSubTree:PANYARGS
StoreSetSearchSubTree TEXTEQU <__imp_StoreSetSearchSubTree>
