extern __imp_CheckADsError:PANYARGS
CheckADsError TEXTEQU <__imp_CheckADsError>
extern __imp_CrackName:PANYARGS
CrackName TEXTEQU <__imp_CrackName>
extern __imp_DSPROP_GetGCSearchOnDomain:PANYARGS
DSPROP_GetGCSearchOnDomain TEXTEQU <__imp_DSPROP_GetGCSearchOnDomain>
extern __imp_ErrMsg:PANYARGS
ErrMsg TEXTEQU <__imp_ErrMsg>
extern __imp_ErrMsgParam:PANYARGS
ErrMsgParam TEXTEQU <__imp_ErrMsgParam>
extern __imp_FindSheet:PANYARGS
FindSheet TEXTEQU <__imp_FindSheet>
extern __imp_MsgBox:PANYARGS
MsgBox TEXTEQU <__imp_MsgBox>
extern __imp_ReportError:PANYARGS
ReportError TEXTEQU <__imp_ReportError>
extern __imp_Smart_PADS_ATTR_INFO__Empty:PANYARGS
Smart_PADS_ATTR_INFO__Empty TEXTEQU <__imp_Smart_PADS_ATTR_INFO__Empty>
extern __imp_ADsPropCheckIfWritable:PANYARGS
ADsPropCheckIfWritable TEXTEQU <__imp_ADsPropCheckIfWritable>
extern __imp_ADsPropCreateNotifyObj:PANYARGS
ADsPropCreateNotifyObj TEXTEQU <__imp_ADsPropCreateNotifyObj>
extern __imp_ADsPropGetInitInfo:PANYARGS
ADsPropGetInitInfo TEXTEQU <__imp_ADsPropGetInitInfo>
extern __imp_ADsPropSendErrorMessage:PANYARGS
ADsPropSendErrorMessage TEXTEQU <__imp_ADsPropSendErrorMessage>
extern __imp_ADsPropSetHwnd:PANYARGS
ADsPropSetHwnd TEXTEQU <__imp_ADsPropSetHwnd>
extern __imp_ADsPropSetHwndWithTitle:PANYARGS
ADsPropSetHwndWithTitle TEXTEQU <__imp_ADsPropSetHwndWithTitle>
extern __imp_ADsPropShowErrorDialog:PANYARGS
ADsPropShowErrorDialog TEXTEQU <__imp_ADsPropShowErrorDialog>
extern __imp_BringSheetToForeground:PANYARGS
BringSheetToForeground TEXTEQU <__imp_BringSheetToForeground>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_IsSheetAlreadyUp:PANYARGS
IsSheetAlreadyUp TEXTEQU <__imp_IsSheetAlreadyUp>
extern __imp_PostADsPropSheet:PANYARGS
PostADsPropSheet TEXTEQU <__imp_PostADsPropSheet>
