extern __imp_OpenSavedDsQuery:PANYARGS
OpenSavedDsQuery TEXTEQU <__imp_OpenSavedDsQuery>
extern __imp_OpenSavedDsQueryW:PANYARGS
OpenSavedDsQueryW TEXTEQU <__imp_OpenSavedDsQueryW>
extern __imp_OpenQueryWindow:PANYARGS
OpenQueryWindow TEXTEQU <__imp_OpenQueryWindow>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_dsquery_ordinal264:PANYARGS
dsquery_ordinal264 TEXTEQU <__imp_dsquery_ordinal264>
extern __imp_dsquery_ordinal265:PANYARGS
dsquery_ordinal265 TEXTEQU <__imp_dsquery_ordinal265>
extern __imp_dsquery_ordinal266:PANYARGS
dsquery_ordinal266 TEXTEQU <__imp_dsquery_ordinal266>
extern __imp_dsquery_ordinal267:PANYARGS
dsquery_ordinal267 TEXTEQU <__imp_dsquery_ordinal267>
extern __imp_dsquery_ordinal268:PANYARGS
dsquery_ordinal268 TEXTEQU <__imp_dsquery_ordinal268>
extern __imp_dsquery_ordinal269:PANYARGS
dsquery_ordinal269 TEXTEQU <__imp_dsquery_ordinal269>
extern __imp_dsquery_ordinal270:PANYARGS
dsquery_ordinal270 TEXTEQU <__imp_dsquery_ordinal270>
extern __imp_dsquery_ordinal271:PANYARGS
dsquery_ordinal271 TEXTEQU <__imp_dsquery_ordinal271>
extern __imp_dsquery_ordinal272:PANYARGS
dsquery_ordinal272 TEXTEQU <__imp_dsquery_ordinal272>
extern __imp_dsquery_ordinal273:PANYARGS
dsquery_ordinal273 TEXTEQU <__imp_dsquery_ordinal273>
extern __imp_dsquery_ordinal274:PANYARGS
dsquery_ordinal274 TEXTEQU <__imp_dsquery_ordinal274>
extern __imp_dsquery_ordinal275:PANYARGS
dsquery_ordinal275 TEXTEQU <__imp_dsquery_ordinal275>
extern __imp_dsquery_ordinal276:PANYARGS
dsquery_ordinal276 TEXTEQU <__imp_dsquery_ordinal276>
extern __imp_dsquery_ordinal277:PANYARGS
dsquery_ordinal277 TEXTEQU <__imp_dsquery_ordinal277>
extern __imp_dsquery_ordinal278:PANYARGS
dsquery_ordinal278 TEXTEQU <__imp_dsquery_ordinal278>
extern __imp_dsquery_ordinal279:PANYARGS
dsquery_ordinal279 TEXTEQU <__imp_dsquery_ordinal279>
extern __imp_dsquery_ordinal280:PANYARGS
dsquery_ordinal280 TEXTEQU <__imp_dsquery_ordinal280>
extern __imp_dsquery_ordinal281:PANYARGS
dsquery_ordinal281 TEXTEQU <__imp_dsquery_ordinal281>
extern __imp_dsquery_ordinal282:PANYARGS
dsquery_ordinal282 TEXTEQU <__imp_dsquery_ordinal282>
extern __imp_dsquery_ordinal283:PANYARGS
dsquery_ordinal283 TEXTEQU <__imp_dsquery_ordinal283>
extern __imp_dsquery_ordinal284:PANYARGS
dsquery_ordinal284 TEXTEQU <__imp_dsquery_ordinal284>
extern __imp_dsquery_ordinal285:PANYARGS
dsquery_ordinal285 TEXTEQU <__imp_dsquery_ordinal285>
extern __imp_dsquery_ordinal286:PANYARGS
dsquery_ordinal286 TEXTEQU <__imp_dsquery_ordinal286>
extern __imp_dsquery_ordinal287:PANYARGS
dsquery_ordinal287 TEXTEQU <__imp_dsquery_ordinal287>
extern __imp_dsquery_ordinal288:PANYARGS
dsquery_ordinal288 TEXTEQU <__imp_dsquery_ordinal288>
extern __imp_dsquery_ordinal289:PANYARGS
dsquery_ordinal289 TEXTEQU <__imp_dsquery_ordinal289>
extern __imp_dsquery_ordinal290:PANYARGS
dsquery_ordinal290 TEXTEQU <__imp_dsquery_ordinal290>
extern __imp_dsquery_ordinal291:PANYARGS
dsquery_ordinal291 TEXTEQU <__imp_dsquery_ordinal291>
extern __imp_dsquery_ordinal292:PANYARGS
dsquery_ordinal292 TEXTEQU <__imp_dsquery_ordinal292>
extern __imp_dsquery_ordinal293:PANYARGS
dsquery_ordinal293 TEXTEQU <__imp_dsquery_ordinal293>
extern __imp_dsquery_ordinal294:PANYARGS
dsquery_ordinal294 TEXTEQU <__imp_dsquery_ordinal294>
extern __imp_dsquery_ordinal295:PANYARGS
dsquery_ordinal295 TEXTEQU <__imp_dsquery_ordinal295>
extern __imp_dsquery_ordinal296:PANYARGS
dsquery_ordinal296 TEXTEQU <__imp_dsquery_ordinal296>
extern __imp_dsquery_ordinal297:PANYARGS
dsquery_ordinal297 TEXTEQU <__imp_dsquery_ordinal297>
extern __imp_dsquery_ordinal298:PANYARGS
dsquery_ordinal298 TEXTEQU <__imp_dsquery_ordinal298>
extern __imp_dsquery_ordinal299:PANYARGS
dsquery_ordinal299 TEXTEQU <__imp_dsquery_ordinal299>
extern __imp_dsquery_ordinal300:PANYARGS
dsquery_ordinal300 TEXTEQU <__imp_dsquery_ordinal300>
extern __imp_dsquery_ordinal301:PANYARGS
dsquery_ordinal301 TEXTEQU <__imp_dsquery_ordinal301>
extern __imp_dsquery_ordinal302:PANYARGS
dsquery_ordinal302 TEXTEQU <__imp_dsquery_ordinal302>
extern __imp_dsquery_ordinal303:PANYARGS
dsquery_ordinal303 TEXTEQU <__imp_dsquery_ordinal303>
extern __imp_dsquery_ordinal304:PANYARGS
dsquery_ordinal304 TEXTEQU <__imp_dsquery_ordinal304>
extern __imp_dsquery_ordinal305:PANYARGS
dsquery_ordinal305 TEXTEQU <__imp_dsquery_ordinal305>
extern __imp_dsquery_ordinal306:PANYARGS
dsquery_ordinal306 TEXTEQU <__imp_dsquery_ordinal306>
extern __imp_dsquery_ordinal307:PANYARGS
dsquery_ordinal307 TEXTEQU <__imp_dsquery_ordinal307>
extern __imp_dsquery_ordinal308:PANYARGS
dsquery_ordinal308 TEXTEQU <__imp_dsquery_ordinal308>
extern __imp_dsquery_ordinal309:PANYARGS
dsquery_ordinal309 TEXTEQU <__imp_dsquery_ordinal309>
extern __imp_dsquery_ordinal310:PANYARGS
dsquery_ordinal310 TEXTEQU <__imp_dsquery_ordinal310>
extern __imp_dsquery_ordinal311:PANYARGS
dsquery_ordinal311 TEXTEQU <__imp_dsquery_ordinal311>
extern __imp_dsquery_ordinal312:PANYARGS
dsquery_ordinal312 TEXTEQU <__imp_dsquery_ordinal312>
extern __imp_dsquery_ordinal313:PANYARGS
dsquery_ordinal313 TEXTEQU <__imp_dsquery_ordinal313>
extern __imp_dsquery_ordinal314:PANYARGS
dsquery_ordinal314 TEXTEQU <__imp_dsquery_ordinal314>
extern __imp_dsquery_ordinal315:PANYARGS
dsquery_ordinal315 TEXTEQU <__imp_dsquery_ordinal315>
extern __imp_dsquery_ordinal316:PANYARGS
dsquery_ordinal316 TEXTEQU <__imp_dsquery_ordinal316>
extern __imp_dsquery_ordinal317:PANYARGS
dsquery_ordinal317 TEXTEQU <__imp_dsquery_ordinal317>
extern __imp_dsquery_ordinal318:PANYARGS
dsquery_ordinal318 TEXTEQU <__imp_dsquery_ordinal318>
extern __imp_dsquery_ordinal319:PANYARGS
dsquery_ordinal319 TEXTEQU <__imp_dsquery_ordinal319>
extern __imp_dsquery_ordinal320:PANYARGS
dsquery_ordinal320 TEXTEQU <__imp_dsquery_ordinal320>
extern __imp_dsquery_ordinal321:PANYARGS
dsquery_ordinal321 TEXTEQU <__imp_dsquery_ordinal321>
extern __imp_dsquery_ordinal322:PANYARGS
dsquery_ordinal322 TEXTEQU <__imp_dsquery_ordinal322>
extern __imp_dsquery_ordinal323:PANYARGS
dsquery_ordinal323 TEXTEQU <__imp_dsquery_ordinal323>
extern __imp_dsquery_ordinal324:PANYARGS
dsquery_ordinal324 TEXTEQU <__imp_dsquery_ordinal324>
extern __imp_dsquery_ordinal325:PANYARGS
dsquery_ordinal325 TEXTEQU <__imp_dsquery_ordinal325>
extern __imp_dsquery_ordinal326:PANYARGS
dsquery_ordinal326 TEXTEQU <__imp_dsquery_ordinal326>
extern __imp_dsquery_ordinal327:PANYARGS
dsquery_ordinal327 TEXTEQU <__imp_dsquery_ordinal327>
extern __imp_dsquery_ordinal328:PANYARGS
dsquery_ordinal328 TEXTEQU <__imp_dsquery_ordinal328>
extern __imp_dsquery_ordinal329:PANYARGS
dsquery_ordinal329 TEXTEQU <__imp_dsquery_ordinal329>
extern __imp_dsquery_ordinal330:PANYARGS
dsquery_ordinal330 TEXTEQU <__imp_dsquery_ordinal330>
extern __imp_dsquery_ordinal331:PANYARGS
dsquery_ordinal331 TEXTEQU <__imp_dsquery_ordinal331>
extern __imp_dsquery_ordinal332:PANYARGS
dsquery_ordinal332 TEXTEQU <__imp_dsquery_ordinal332>
extern __imp_dsquery_ordinal333:PANYARGS
dsquery_ordinal333 TEXTEQU <__imp_dsquery_ordinal333>
extern __imp_dsquery_ordinal334:PANYARGS
dsquery_ordinal334 TEXTEQU <__imp_dsquery_ordinal334>
extern __imp_dsquery_ordinal335:PANYARGS
dsquery_ordinal335 TEXTEQU <__imp_dsquery_ordinal335>
extern __imp_dsquery_ordinal336:PANYARGS
dsquery_ordinal336 TEXTEQU <__imp_dsquery_ordinal336>
extern __imp_dsquery_ordinal337:PANYARGS
dsquery_ordinal337 TEXTEQU <__imp_dsquery_ordinal337>
extern __imp_dsquery_ordinal338:PANYARGS
dsquery_ordinal338 TEXTEQU <__imp_dsquery_ordinal338>
extern __imp_dsquery_ordinal339:PANYARGS
dsquery_ordinal339 TEXTEQU <__imp_dsquery_ordinal339>
extern __imp_dsquery_ordinal340:PANYARGS
dsquery_ordinal340 TEXTEQU <__imp_dsquery_ordinal340>
extern __imp_dsquery_ordinal341:PANYARGS
dsquery_ordinal341 TEXTEQU <__imp_dsquery_ordinal341>
extern __imp_dsquery_ordinal342:PANYARGS
dsquery_ordinal342 TEXTEQU <__imp_dsquery_ordinal342>
extern __imp_dsquery_ordinal343:PANYARGS
dsquery_ordinal343 TEXTEQU <__imp_dsquery_ordinal343>
extern __imp_dsquery_ordinal344:PANYARGS
dsquery_ordinal344 TEXTEQU <__imp_dsquery_ordinal344>
extern __imp_dsquery_ordinal345:PANYARGS
dsquery_ordinal345 TEXTEQU <__imp_dsquery_ordinal345>
extern __imp_dsquery_ordinal346:PANYARGS
dsquery_ordinal346 TEXTEQU <__imp_dsquery_ordinal346>
extern __imp_dsquery_ordinal347:PANYARGS
dsquery_ordinal347 TEXTEQU <__imp_dsquery_ordinal347>
extern __imp_dsquery_ordinal348:PANYARGS
dsquery_ordinal348 TEXTEQU <__imp_dsquery_ordinal348>
extern __imp_dsquery_ordinal349:PANYARGS
dsquery_ordinal349 TEXTEQU <__imp_dsquery_ordinal349>
extern __imp_dsquery_ordinal350:PANYARGS
dsquery_ordinal350 TEXTEQU <__imp_dsquery_ordinal350>
extern __imp_dsquery_ordinal351:PANYARGS
dsquery_ordinal351 TEXTEQU <__imp_dsquery_ordinal351>
extern __imp_dsquery_ordinal352:PANYARGS
dsquery_ordinal352 TEXTEQU <__imp_dsquery_ordinal352>
extern __imp_dsquery_ordinal353:PANYARGS
dsquery_ordinal353 TEXTEQU <__imp_dsquery_ordinal353>
extern __imp_dsquery_ordinal354:PANYARGS
dsquery_ordinal354 TEXTEQU <__imp_dsquery_ordinal354>
extern __imp_dsquery_ordinal355:PANYARGS
dsquery_ordinal355 TEXTEQU <__imp_dsquery_ordinal355>
extern __imp_dsquery_ordinal356:PANYARGS
dsquery_ordinal356 TEXTEQU <__imp_dsquery_ordinal356>
extern __imp_dsquery_ordinal357:PANYARGS
dsquery_ordinal357 TEXTEQU <__imp_dsquery_ordinal357>
extern __imp_dsquery_ordinal358:PANYARGS
dsquery_ordinal358 TEXTEQU <__imp_dsquery_ordinal358>
extern __imp_dsquery_ordinal359:PANYARGS
dsquery_ordinal359 TEXTEQU <__imp_dsquery_ordinal359>
extern __imp_dsquery_ordinal360:PANYARGS
dsquery_ordinal360 TEXTEQU <__imp_dsquery_ordinal360>
extern __imp_dsquery_ordinal361:PANYARGS
dsquery_ordinal361 TEXTEQU <__imp_dsquery_ordinal361>
extern __imp_dsquery_ordinal362:PANYARGS
dsquery_ordinal362 TEXTEQU <__imp_dsquery_ordinal362>
extern __imp_dsquery_ordinal363:PANYARGS
dsquery_ordinal363 TEXTEQU <__imp_dsquery_ordinal363>
extern __imp_dsquery_ordinal364:PANYARGS
dsquery_ordinal364 TEXTEQU <__imp_dsquery_ordinal364>
extern __imp_dsquery_ordinal365:PANYARGS
dsquery_ordinal365 TEXTEQU <__imp_dsquery_ordinal365>
extern __imp_dsquery_ordinal366:PANYARGS
dsquery_ordinal366 TEXTEQU <__imp_dsquery_ordinal366>
extern __imp_dsquery_ordinal367:PANYARGS
dsquery_ordinal367 TEXTEQU <__imp_dsquery_ordinal367>
extern __imp_dsquery_ordinal368:PANYARGS
dsquery_ordinal368 TEXTEQU <__imp_dsquery_ordinal368>
extern __imp_dsquery_ordinal369:PANYARGS
dsquery_ordinal369 TEXTEQU <__imp_dsquery_ordinal369>
extern __imp_dsquery_ordinal370:PANYARGS
dsquery_ordinal370 TEXTEQU <__imp_dsquery_ordinal370>
extern __imp_dsquery_ordinal371:PANYARGS
dsquery_ordinal371 TEXTEQU <__imp_dsquery_ordinal371>
extern __imp_dsquery_ordinal372:PANYARGS
dsquery_ordinal372 TEXTEQU <__imp_dsquery_ordinal372>
extern __imp_dsquery_ordinal373:PANYARGS
dsquery_ordinal373 TEXTEQU <__imp_dsquery_ordinal373>
extern __imp_dsquery_ordinal374:PANYARGS
dsquery_ordinal374 TEXTEQU <__imp_dsquery_ordinal374>
extern __imp_dsquery_ordinal375:PANYARGS
dsquery_ordinal375 TEXTEQU <__imp_dsquery_ordinal375>
extern __imp_dsquery_ordinal376:PANYARGS
dsquery_ordinal376 TEXTEQU <__imp_dsquery_ordinal376>
extern __imp_dsquery_ordinal377:PANYARGS
dsquery_ordinal377 TEXTEQU <__imp_dsquery_ordinal377>
extern __imp_dsquery_ordinal378:PANYARGS
dsquery_ordinal378 TEXTEQU <__imp_dsquery_ordinal378>
extern __imp_dsquery_ordinal379:PANYARGS
dsquery_ordinal379 TEXTEQU <__imp_dsquery_ordinal379>
extern __imp_dsquery_ordinal380:PANYARGS
dsquery_ordinal380 TEXTEQU <__imp_dsquery_ordinal380>
extern __imp_dsquery_ordinal381:PANYARGS
dsquery_ordinal381 TEXTEQU <__imp_dsquery_ordinal381>
extern __imp_dsquery_ordinal382:PANYARGS
dsquery_ordinal382 TEXTEQU <__imp_dsquery_ordinal382>
extern __imp_dsquery_ordinal383:PANYARGS
dsquery_ordinal383 TEXTEQU <__imp_dsquery_ordinal383>
extern __imp_dsquery_ordinal384:PANYARGS
dsquery_ordinal384 TEXTEQU <__imp_dsquery_ordinal384>
extern __imp_dsquery_ordinal385:PANYARGS
dsquery_ordinal385 TEXTEQU <__imp_dsquery_ordinal385>
extern __imp_dsquery_ordinal386:PANYARGS
dsquery_ordinal386 TEXTEQU <__imp_dsquery_ordinal386>
extern __imp_dsquery_ordinal387:PANYARGS
dsquery_ordinal387 TEXTEQU <__imp_dsquery_ordinal387>
extern __imp_dsquery_ordinal388:PANYARGS
dsquery_ordinal388 TEXTEQU <__imp_dsquery_ordinal388>
extern __imp_dsquery_ordinal389:PANYARGS
dsquery_ordinal389 TEXTEQU <__imp_dsquery_ordinal389>
extern __imp_dsquery_ordinal390:PANYARGS
dsquery_ordinal390 TEXTEQU <__imp_dsquery_ordinal390>
extern __imp_dsquery_ordinal391:PANYARGS
dsquery_ordinal391 TEXTEQU <__imp_dsquery_ordinal391>
extern __imp_dsquery_ordinal392:PANYARGS
dsquery_ordinal392 TEXTEQU <__imp_dsquery_ordinal392>
extern __imp_dsquery_ordinal393:PANYARGS
dsquery_ordinal393 TEXTEQU <__imp_dsquery_ordinal393>
extern __imp_dsquery_ordinal394:PANYARGS
dsquery_ordinal394 TEXTEQU <__imp_dsquery_ordinal394>
extern __imp_dsquery_ordinal395:PANYARGS
dsquery_ordinal395 TEXTEQU <__imp_dsquery_ordinal395>
extern __imp_dsquery_ordinal396:PANYARGS
dsquery_ordinal396 TEXTEQU <__imp_dsquery_ordinal396>
extern __imp_dsquery_ordinal397:PANYARGS
dsquery_ordinal397 TEXTEQU <__imp_dsquery_ordinal397>
extern __imp_dsquery_ordinal398:PANYARGS
dsquery_ordinal398 TEXTEQU <__imp_dsquery_ordinal398>
extern __imp_dsquery_ordinal399:PANYARGS
dsquery_ordinal399 TEXTEQU <__imp_dsquery_ordinal399>
extern __imp_dsquery_ordinal400:PANYARGS
dsquery_ordinal400 TEXTEQU <__imp_dsquery_ordinal400>
extern __imp_dsquery_ordinal401:PANYARGS
dsquery_ordinal401 TEXTEQU <__imp_dsquery_ordinal401>
extern __imp_dsquery_ordinal402:PANYARGS
dsquery_ordinal402 TEXTEQU <__imp_dsquery_ordinal402>
extern __imp_dsquery_ordinal403:PANYARGS
dsquery_ordinal403 TEXTEQU <__imp_dsquery_ordinal403>
extern __imp_dsquery_ordinal404:PANYARGS
dsquery_ordinal404 TEXTEQU <__imp_dsquery_ordinal404>
extern __imp_dsquery_ordinal405:PANYARGS
dsquery_ordinal405 TEXTEQU <__imp_dsquery_ordinal405>
extern __imp_dsquery_ordinal406:PANYARGS
dsquery_ordinal406 TEXTEQU <__imp_dsquery_ordinal406>
extern __imp_dsquery_ordinal407:PANYARGS
dsquery_ordinal407 TEXTEQU <__imp_dsquery_ordinal407>
extern __imp_dsquery_ordinal408:PANYARGS
dsquery_ordinal408 TEXTEQU <__imp_dsquery_ordinal408>
extern __imp_dsquery_ordinal409:PANYARGS
dsquery_ordinal409 TEXTEQU <__imp_dsquery_ordinal409>
extern __imp_dsquery_ordinal410:PANYARGS
dsquery_ordinal410 TEXTEQU <__imp_dsquery_ordinal410>
extern __imp_dsquery_ordinal411:PANYARGS
dsquery_ordinal411 TEXTEQU <__imp_dsquery_ordinal411>
extern __imp_dsquery_ordinal412:PANYARGS
dsquery_ordinal412 TEXTEQU <__imp_dsquery_ordinal412>
extern __imp_dsquery_ordinal413:PANYARGS
dsquery_ordinal413 TEXTEQU <__imp_dsquery_ordinal413>
extern __imp_dsquery_ordinal414:PANYARGS
dsquery_ordinal414 TEXTEQU <__imp_dsquery_ordinal414>
extern __imp_dsquery_ordinal415:PANYARGS
dsquery_ordinal415 TEXTEQU <__imp_dsquery_ordinal415>
extern __imp_dsquery_ordinal416:PANYARGS
dsquery_ordinal416 TEXTEQU <__imp_dsquery_ordinal416>
extern __imp_dsquery_ordinal417:PANYARGS
dsquery_ordinal417 TEXTEQU <__imp_dsquery_ordinal417>
extern __imp_dsquery_ordinal418:PANYARGS
dsquery_ordinal418 TEXTEQU <__imp_dsquery_ordinal418>
extern __imp_dsquery_ordinal419:PANYARGS
dsquery_ordinal419 TEXTEQU <__imp_dsquery_ordinal419>
extern __imp_dsquery_ordinal420:PANYARGS
dsquery_ordinal420 TEXTEQU <__imp_dsquery_ordinal420>
extern __imp_dsquery_ordinal421:PANYARGS
dsquery_ordinal421 TEXTEQU <__imp_dsquery_ordinal421>
extern __imp_dsquery_ordinal422:PANYARGS
dsquery_ordinal422 TEXTEQU <__imp_dsquery_ordinal422>
extern __imp_dsquery_ordinal423:PANYARGS
dsquery_ordinal423 TEXTEQU <__imp_dsquery_ordinal423>
extern __imp_dsquery_ordinal424:PANYARGS
dsquery_ordinal424 TEXTEQU <__imp_dsquery_ordinal424>
extern __imp_dsquery_ordinal425:PANYARGS
dsquery_ordinal425 TEXTEQU <__imp_dsquery_ordinal425>
extern __imp_dsquery_ordinal426:PANYARGS
dsquery_ordinal426 TEXTEQU <__imp_dsquery_ordinal426>
extern __imp_dsquery_ordinal427:PANYARGS
dsquery_ordinal427 TEXTEQU <__imp_dsquery_ordinal427>
extern __imp_dsquery_ordinal428:PANYARGS
dsquery_ordinal428 TEXTEQU <__imp_dsquery_ordinal428>
extern __imp_dsquery_ordinal429:PANYARGS
dsquery_ordinal429 TEXTEQU <__imp_dsquery_ordinal429>
extern __imp_dsquery_ordinal430:PANYARGS
dsquery_ordinal430 TEXTEQU <__imp_dsquery_ordinal430>
extern __imp_dsquery_ordinal431:PANYARGS
dsquery_ordinal431 TEXTEQU <__imp_dsquery_ordinal431>
extern __imp_dsquery_ordinal432:PANYARGS
dsquery_ordinal432 TEXTEQU <__imp_dsquery_ordinal432>
extern __imp_dsquery_ordinal433:PANYARGS
dsquery_ordinal433 TEXTEQU <__imp_dsquery_ordinal433>
extern __imp_dsquery_ordinal434:PANYARGS
dsquery_ordinal434 TEXTEQU <__imp_dsquery_ordinal434>
extern __imp_dsquery_ordinal435:PANYARGS
dsquery_ordinal435 TEXTEQU <__imp_dsquery_ordinal435>
extern __imp_dsquery_ordinal436:PANYARGS
dsquery_ordinal436 TEXTEQU <__imp_dsquery_ordinal436>
extern __imp_dsquery_ordinal437:PANYARGS
dsquery_ordinal437 TEXTEQU <__imp_dsquery_ordinal437>
extern __imp_dsquery_ordinal438:PANYARGS
dsquery_ordinal438 TEXTEQU <__imp_dsquery_ordinal438>
extern __imp_dsquery_ordinal439:PANYARGS
dsquery_ordinal439 TEXTEQU <__imp_dsquery_ordinal439>
extern __imp_dsquery_ordinal440:PANYARGS
dsquery_ordinal440 TEXTEQU <__imp_dsquery_ordinal440>
extern __imp_dsquery_ordinal441:PANYARGS
dsquery_ordinal441 TEXTEQU <__imp_dsquery_ordinal441>
extern __imp_dsquery_ordinal442:PANYARGS
dsquery_ordinal442 TEXTEQU <__imp_dsquery_ordinal442>
extern __imp_dsquery_ordinal443:PANYARGS
dsquery_ordinal443 TEXTEQU <__imp_dsquery_ordinal443>
extern __imp_dsquery_ordinal444:PANYARGS
dsquery_ordinal444 TEXTEQU <__imp_dsquery_ordinal444>
extern __imp_dsquery_ordinal445:PANYARGS
dsquery_ordinal445 TEXTEQU <__imp_dsquery_ordinal445>
extern __imp_dsquery_ordinal446:PANYARGS
dsquery_ordinal446 TEXTEQU <__imp_dsquery_ordinal446>
extern __imp_dsquery_ordinal447:PANYARGS
dsquery_ordinal447 TEXTEQU <__imp_dsquery_ordinal447>
extern __imp_dsquery_ordinal448:PANYARGS
dsquery_ordinal448 TEXTEQU <__imp_dsquery_ordinal448>
extern __imp_dsquery_ordinal449:PANYARGS
dsquery_ordinal449 TEXTEQU <__imp_dsquery_ordinal449>
extern __imp_dsquery_ordinal450:PANYARGS
dsquery_ordinal450 TEXTEQU <__imp_dsquery_ordinal450>
extern __imp_dsquery_ordinal451:PANYARGS
dsquery_ordinal451 TEXTEQU <__imp_dsquery_ordinal451>
extern __imp_dsquery_ordinal452:PANYARGS
dsquery_ordinal452 TEXTEQU <__imp_dsquery_ordinal452>
extern __imp_dsquery_ordinal453:PANYARGS
dsquery_ordinal453 TEXTEQU <__imp_dsquery_ordinal453>
extern __imp_dsquery_ordinal454:PANYARGS
dsquery_ordinal454 TEXTEQU <__imp_dsquery_ordinal454>
extern __imp_dsquery_ordinal455:PANYARGS
dsquery_ordinal455 TEXTEQU <__imp_dsquery_ordinal455>
extern __imp_dsquery_ordinal456:PANYARGS
dsquery_ordinal456 TEXTEQU <__imp_dsquery_ordinal456>
extern __imp_dsquery_ordinal457:PANYARGS
dsquery_ordinal457 TEXTEQU <__imp_dsquery_ordinal457>
extern __imp_dsquery_ordinal458:PANYARGS
dsquery_ordinal458 TEXTEQU <__imp_dsquery_ordinal458>
extern __imp_dsquery_ordinal459:PANYARGS
dsquery_ordinal459 TEXTEQU <__imp_dsquery_ordinal459>
extern __imp_dsquery_ordinal460:PANYARGS
dsquery_ordinal460 TEXTEQU <__imp_dsquery_ordinal460>
extern __imp_dsquery_ordinal461:PANYARGS
dsquery_ordinal461 TEXTEQU <__imp_dsquery_ordinal461>
extern __imp_dsquery_ordinal462:PANYARGS
dsquery_ordinal462 TEXTEQU <__imp_dsquery_ordinal462>
extern __imp_dsquery_ordinal463:PANYARGS
dsquery_ordinal463 TEXTEQU <__imp_dsquery_ordinal463>
extern __imp_dsquery_ordinal464:PANYARGS
dsquery_ordinal464 TEXTEQU <__imp_dsquery_ordinal464>
extern __imp_dsquery_ordinal465:PANYARGS
dsquery_ordinal465 TEXTEQU <__imp_dsquery_ordinal465>
extern __imp_dsquery_ordinal466:PANYARGS
dsquery_ordinal466 TEXTEQU <__imp_dsquery_ordinal466>
extern __imp_dsquery_ordinal467:PANYARGS
dsquery_ordinal467 TEXTEQU <__imp_dsquery_ordinal467>
extern __imp_dsquery_ordinal468:PANYARGS
dsquery_ordinal468 TEXTEQU <__imp_dsquery_ordinal468>
extern __imp_dsquery_ordinal469:PANYARGS
dsquery_ordinal469 TEXTEQU <__imp_dsquery_ordinal469>
extern __imp_dsquery_ordinal470:PANYARGS
dsquery_ordinal470 TEXTEQU <__imp_dsquery_ordinal470>
extern __imp_dsquery_ordinal471:PANYARGS
dsquery_ordinal471 TEXTEQU <__imp_dsquery_ordinal471>
extern __imp_dsquery_ordinal472:PANYARGS
dsquery_ordinal472 TEXTEQU <__imp_dsquery_ordinal472>
extern __imp_dsquery_ordinal473:PANYARGS
dsquery_ordinal473 TEXTEQU <__imp_dsquery_ordinal473>
extern __imp_dsquery_ordinal474:PANYARGS
dsquery_ordinal474 TEXTEQU <__imp_dsquery_ordinal474>
extern __imp_dsquery_ordinal475:PANYARGS
dsquery_ordinal475 TEXTEQU <__imp_dsquery_ordinal475>
extern __imp_dsquery_ordinal476:PANYARGS
dsquery_ordinal476 TEXTEQU <__imp_dsquery_ordinal476>
extern __imp_dsquery_ordinal477:PANYARGS
dsquery_ordinal477 TEXTEQU <__imp_dsquery_ordinal477>
extern __imp_dsquery_ordinal478:PANYARGS
dsquery_ordinal478 TEXTEQU <__imp_dsquery_ordinal478>
extern __imp_dsquery_ordinal479:PANYARGS
dsquery_ordinal479 TEXTEQU <__imp_dsquery_ordinal479>
extern __imp_dsquery_ordinal480:PANYARGS
dsquery_ordinal480 TEXTEQU <__imp_dsquery_ordinal480>
extern __imp_dsquery_ordinal481:PANYARGS
dsquery_ordinal481 TEXTEQU <__imp_dsquery_ordinal481>
extern __imp_dsquery_ordinal482:PANYARGS
dsquery_ordinal482 TEXTEQU <__imp_dsquery_ordinal482>
extern __imp_dsquery_ordinal483:PANYARGS
dsquery_ordinal483 TEXTEQU <__imp_dsquery_ordinal483>
extern __imp_dsquery_ordinal484:PANYARGS
dsquery_ordinal484 TEXTEQU <__imp_dsquery_ordinal484>
extern __imp_dsquery_ordinal485:PANYARGS
dsquery_ordinal485 TEXTEQU <__imp_dsquery_ordinal485>
extern __imp_dsquery_ordinal486:PANYARGS
dsquery_ordinal486 TEXTEQU <__imp_dsquery_ordinal486>
extern __imp_dsquery_ordinal487:PANYARGS
dsquery_ordinal487 TEXTEQU <__imp_dsquery_ordinal487>
extern __imp_dsquery_ordinal488:PANYARGS
dsquery_ordinal488 TEXTEQU <__imp_dsquery_ordinal488>
extern __imp_dsquery_ordinal489:PANYARGS
dsquery_ordinal489 TEXTEQU <__imp_dsquery_ordinal489>
extern __imp_dsquery_ordinal490:PANYARGS
dsquery_ordinal490 TEXTEQU <__imp_dsquery_ordinal490>
extern __imp_dsquery_ordinal491:PANYARGS
dsquery_ordinal491 TEXTEQU <__imp_dsquery_ordinal491>
extern __imp_dsquery_ordinal492:PANYARGS
dsquery_ordinal492 TEXTEQU <__imp_dsquery_ordinal492>
extern __imp_dsquery_ordinal493:PANYARGS
dsquery_ordinal493 TEXTEQU <__imp_dsquery_ordinal493>
extern __imp_dsquery_ordinal494:PANYARGS
dsquery_ordinal494 TEXTEQU <__imp_dsquery_ordinal494>
extern __imp_dsquery_ordinal495:PANYARGS
dsquery_ordinal495 TEXTEQU <__imp_dsquery_ordinal495>
extern __imp_dsquery_ordinal496:PANYARGS
dsquery_ordinal496 TEXTEQU <__imp_dsquery_ordinal496>
extern __imp_dsquery_ordinal497:PANYARGS
dsquery_ordinal497 TEXTEQU <__imp_dsquery_ordinal497>
extern __imp_dsquery_ordinal498:PANYARGS
dsquery_ordinal498 TEXTEQU <__imp_dsquery_ordinal498>
extern __imp_dsquery_ordinal499:PANYARGS
dsquery_ordinal499 TEXTEQU <__imp_dsquery_ordinal499>
extern __imp_dsquery_ordinal500:PANYARGS
dsquery_ordinal500 TEXTEQU <__imp_dsquery_ordinal500>
extern __imp_dsquery_ordinal501:PANYARGS
dsquery_ordinal501 TEXTEQU <__imp_dsquery_ordinal501>
extern __imp_dsquery_ordinal502:PANYARGS
dsquery_ordinal502 TEXTEQU <__imp_dsquery_ordinal502>
extern __imp_dsquery_ordinal503:PANYARGS
dsquery_ordinal503 TEXTEQU <__imp_dsquery_ordinal503>
extern __imp_dsquery_ordinal504:PANYARGS
dsquery_ordinal504 TEXTEQU <__imp_dsquery_ordinal504>
extern __imp_dsquery_ordinal505:PANYARGS
dsquery_ordinal505 TEXTEQU <__imp_dsquery_ordinal505>
extern __imp_dsquery_ordinal506:PANYARGS
dsquery_ordinal506 TEXTEQU <__imp_dsquery_ordinal506>
extern __imp_dsquery_ordinal507:PANYARGS
dsquery_ordinal507 TEXTEQU <__imp_dsquery_ordinal507>
extern __imp_dsquery_ordinal508:PANYARGS
dsquery_ordinal508 TEXTEQU <__imp_dsquery_ordinal508>
extern __imp_dsquery_ordinal509:PANYARGS
dsquery_ordinal509 TEXTEQU <__imp_dsquery_ordinal509>
extern __imp_dsquery_ordinal510:PANYARGS
dsquery_ordinal510 TEXTEQU <__imp_dsquery_ordinal510>
extern __imp_dsquery_ordinal511:PANYARGS
dsquery_ordinal511 TEXTEQU <__imp_dsquery_ordinal511>
extern __imp_dsquery_ordinal512:PANYARGS
dsquery_ordinal512 TEXTEQU <__imp_dsquery_ordinal512>
extern __imp_dsquery_ordinal513:PANYARGS
dsquery_ordinal513 TEXTEQU <__imp_dsquery_ordinal513>
extern __imp_dsquery_ordinal514:PANYARGS
dsquery_ordinal514 TEXTEQU <__imp_dsquery_ordinal514>
extern __imp_dsquery_ordinal515:PANYARGS
dsquery_ordinal515 TEXTEQU <__imp_dsquery_ordinal515>
extern __imp_dsquery_ordinal516:PANYARGS
dsquery_ordinal516 TEXTEQU <__imp_dsquery_ordinal516>
extern __imp_dsquery_ordinal517:PANYARGS
dsquery_ordinal517 TEXTEQU <__imp_dsquery_ordinal517>
extern __imp_dsquery_ordinal518:PANYARGS
dsquery_ordinal518 TEXTEQU <__imp_dsquery_ordinal518>
extern __imp_dsquery_ordinal519:PANYARGS
dsquery_ordinal519 TEXTEQU <__imp_dsquery_ordinal519>
extern __imp_dsquery_ordinal520:PANYARGS
dsquery_ordinal520 TEXTEQU <__imp_dsquery_ordinal520>
extern __imp_dsquery_ordinal521:PANYARGS
dsquery_ordinal521 TEXTEQU <__imp_dsquery_ordinal521>
