extern __imp_DsBrowseForContainerA:PANYARGS
DsBrowseForContainer  TEXTEQU <__imp_DsBrowseForContainerA>
extern __imp_DsBrowseForContainerW:PANYARGS
DsBrowseForContainerW TEXTEQU <__imp_DsBrowseForContainerW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_dsuiext_ordinal16:PANYARGS
dsuiext_ordinal16 TEXTEQU <__imp_dsuiext_ordinal16>
extern __imp_dsuiext_ordinal17:PANYARGS
dsuiext_ordinal17 TEXTEQU <__imp_dsuiext_ordinal17>
extern __imp_dsuiext_ordinal18:PANYARGS
dsuiext_ordinal18 TEXTEQU <__imp_dsuiext_ordinal18>
extern __imp_dsuiext_ordinal19:PANYARGS
dsuiext_ordinal19 TEXTEQU <__imp_dsuiext_ordinal19>
extern __imp_dsuiext_ordinal20:PANYARGS
dsuiext_ordinal20 TEXTEQU <__imp_dsuiext_ordinal20>
extern __imp_dsuiext_ordinal21:PANYARGS
dsuiext_ordinal21 TEXTEQU <__imp_dsuiext_ordinal21>
extern __imp_dsuiext_ordinal22:PANYARGS
dsuiext_ordinal22 TEXTEQU <__imp_dsuiext_ordinal22>
extern __imp_dsuiext_ordinal23:PANYARGS
dsuiext_ordinal23 TEXTEQU <__imp_dsuiext_ordinal23>
extern __imp_dsuiext_ordinal24:PANYARGS
dsuiext_ordinal24 TEXTEQU <__imp_dsuiext_ordinal24>
extern __imp_dsuiext_ordinal25:PANYARGS
dsuiext_ordinal25 TEXTEQU <__imp_dsuiext_ordinal25>
extern __imp_dsuiext_ordinal26:PANYARGS
dsuiext_ordinal26 TEXTEQU <__imp_dsuiext_ordinal26>
extern __imp_dsuiext_ordinal27:PANYARGS
dsuiext_ordinal27 TEXTEQU <__imp_dsuiext_ordinal27>
extern __imp_dsuiext_ordinal28:PANYARGS
dsuiext_ordinal28 TEXTEQU <__imp_dsuiext_ordinal28>
extern __imp_dsuiext_ordinal29:PANYARGS
dsuiext_ordinal29 TEXTEQU <__imp_dsuiext_ordinal29>
extern __imp_dsuiext_ordinal30:PANYARGS
dsuiext_ordinal30 TEXTEQU <__imp_dsuiext_ordinal30>
extern __imp_dsuiext_ordinal31:PANYARGS
dsuiext_ordinal31 TEXTEQU <__imp_dsuiext_ordinal31>
extern __imp_dsuiext_ordinal32:PANYARGS
dsuiext_ordinal32 TEXTEQU <__imp_dsuiext_ordinal32>
extern __imp_dsuiext_ordinal33:PANYARGS
dsuiext_ordinal33 TEXTEQU <__imp_dsuiext_ordinal33>
extern __imp_dsuiext_ordinal34:PANYARGS
dsuiext_ordinal34 TEXTEQU <__imp_dsuiext_ordinal34>
extern __imp_dsuiext_ordinal35:PANYARGS
dsuiext_ordinal35 TEXTEQU <__imp_dsuiext_ordinal35>
extern __imp_dsuiext_ordinal36:PANYARGS
dsuiext_ordinal36 TEXTEQU <__imp_dsuiext_ordinal36>
extern __imp_dsuiext_ordinal37:PANYARGS
dsuiext_ordinal37 TEXTEQU <__imp_dsuiext_ordinal37>
extern __imp_dsuiext_ordinal38:PANYARGS
dsuiext_ordinal38 TEXTEQU <__imp_dsuiext_ordinal38>
extern __imp_dsuiext_ordinal39:PANYARGS
dsuiext_ordinal39 TEXTEQU <__imp_dsuiext_ordinal39>
extern __imp_dsuiext_ordinal40:PANYARGS
dsuiext_ordinal40 TEXTEQU <__imp_dsuiext_ordinal40>
extern __imp_dsuiext_ordinal41:PANYARGS
dsuiext_ordinal41 TEXTEQU <__imp_dsuiext_ordinal41>
extern __imp_dsuiext_ordinal42:PANYARGS
dsuiext_ordinal42 TEXTEQU <__imp_dsuiext_ordinal42>
extern __imp_dsuiext_ordinal43:PANYARGS
dsuiext_ordinal43 TEXTEQU <__imp_dsuiext_ordinal43>
extern __imp_dsuiext_ordinal44:PANYARGS
dsuiext_ordinal44 TEXTEQU <__imp_dsuiext_ordinal44>
extern __imp_dsuiext_ordinal45:PANYARGS
dsuiext_ordinal45 TEXTEQU <__imp_dsuiext_ordinal45>
extern __imp_dsuiext_ordinal46:PANYARGS
dsuiext_ordinal46 TEXTEQU <__imp_dsuiext_ordinal46>
extern __imp_dsuiext_ordinal47:PANYARGS
dsuiext_ordinal47 TEXTEQU <__imp_dsuiext_ordinal47>
extern __imp_dsuiext_ordinal48:PANYARGS
dsuiext_ordinal48 TEXTEQU <__imp_dsuiext_ordinal48>
extern __imp_dsuiext_ordinal49:PANYARGS
dsuiext_ordinal49 TEXTEQU <__imp_dsuiext_ordinal49>
extern __imp_dsuiext_ordinal50:PANYARGS
dsuiext_ordinal50 TEXTEQU <__imp_dsuiext_ordinal50>
extern __imp_dsuiext_ordinal51:PANYARGS
dsuiext_ordinal51 TEXTEQU <__imp_dsuiext_ordinal51>
extern __imp_dsuiext_ordinal52:PANYARGS
dsuiext_ordinal52 TEXTEQU <__imp_dsuiext_ordinal52>
extern __imp_dsuiext_ordinal53:PANYARGS
dsuiext_ordinal53 TEXTEQU <__imp_dsuiext_ordinal53>
extern __imp_dsuiext_ordinal54:PANYARGS
dsuiext_ordinal54 TEXTEQU <__imp_dsuiext_ordinal54>
extern __imp_dsuiext_ordinal55:PANYARGS
dsuiext_ordinal55 TEXTEQU <__imp_dsuiext_ordinal55>
extern __imp_dsuiext_ordinal56:PANYARGS
dsuiext_ordinal56 TEXTEQU <__imp_dsuiext_ordinal56>
extern __imp_dsuiext_ordinal57:PANYARGS
dsuiext_ordinal57 TEXTEQU <__imp_dsuiext_ordinal57>
extern __imp_dsuiext_ordinal58:PANYARGS
dsuiext_ordinal58 TEXTEQU <__imp_dsuiext_ordinal58>
extern __imp_dsuiext_ordinal59:PANYARGS
dsuiext_ordinal59 TEXTEQU <__imp_dsuiext_ordinal59>
extern __imp_dsuiext_ordinal60:PANYARGS
dsuiext_ordinal60 TEXTEQU <__imp_dsuiext_ordinal60>
extern __imp_dsuiext_ordinal61:PANYARGS
dsuiext_ordinal61 TEXTEQU <__imp_dsuiext_ordinal61>
extern __imp_dsuiext_ordinal62:PANYARGS
dsuiext_ordinal62 TEXTEQU <__imp_dsuiext_ordinal62>
extern __imp_dsuiext_ordinal63:PANYARGS
dsuiext_ordinal63 TEXTEQU <__imp_dsuiext_ordinal63>
extern __imp_dsuiext_ordinal64:PANYARGS
dsuiext_ordinal64 TEXTEQU <__imp_dsuiext_ordinal64>
extern __imp_dsuiext_ordinal65:PANYARGS
dsuiext_ordinal65 TEXTEQU <__imp_dsuiext_ordinal65>
extern __imp_dsuiext_ordinal66:PANYARGS
dsuiext_ordinal66 TEXTEQU <__imp_dsuiext_ordinal66>
extern __imp_dsuiext_ordinal67:PANYARGS
dsuiext_ordinal67 TEXTEQU <__imp_dsuiext_ordinal67>
extern __imp_dsuiext_ordinal68:PANYARGS
dsuiext_ordinal68 TEXTEQU <__imp_dsuiext_ordinal68>
extern __imp_dsuiext_ordinal69:PANYARGS
dsuiext_ordinal69 TEXTEQU <__imp_dsuiext_ordinal69>
extern __imp_dsuiext_ordinal70:PANYARGS
dsuiext_ordinal70 TEXTEQU <__imp_dsuiext_ordinal70>
extern __imp_dsuiext_ordinal71:PANYARGS
dsuiext_ordinal71 TEXTEQU <__imp_dsuiext_ordinal71>
extern __imp_dsuiext_ordinal72:PANYARGS
dsuiext_ordinal72 TEXTEQU <__imp_dsuiext_ordinal72>
extern __imp_dsuiext_ordinal73:PANYARGS
dsuiext_ordinal73 TEXTEQU <__imp_dsuiext_ordinal73>
extern __imp_dsuiext_ordinal74:PANYARGS
dsuiext_ordinal74 TEXTEQU <__imp_dsuiext_ordinal74>
extern __imp_dsuiext_ordinal75:PANYARGS
dsuiext_ordinal75 TEXTEQU <__imp_dsuiext_ordinal75>
extern __imp_dsuiext_ordinal76:PANYARGS
dsuiext_ordinal76 TEXTEQU <__imp_dsuiext_ordinal76>
extern __imp_dsuiext_ordinal77:PANYARGS
dsuiext_ordinal77 TEXTEQU <__imp_dsuiext_ordinal77>
extern __imp_dsuiext_ordinal78:PANYARGS
dsuiext_ordinal78 TEXTEQU <__imp_dsuiext_ordinal78>
extern __imp_dsuiext_ordinal79:PANYARGS
dsuiext_ordinal79 TEXTEQU <__imp_dsuiext_ordinal79>
extern __imp_dsuiext_ordinal80:PANYARGS
dsuiext_ordinal80 TEXTEQU <__imp_dsuiext_ordinal80>
extern __imp_dsuiext_ordinal81:PANYARGS
dsuiext_ordinal81 TEXTEQU <__imp_dsuiext_ordinal81>
extern __imp_dsuiext_ordinal82:PANYARGS
dsuiext_ordinal82 TEXTEQU <__imp_dsuiext_ordinal82>
extern __imp_dsuiext_ordinal83:PANYARGS
dsuiext_ordinal83 TEXTEQU <__imp_dsuiext_ordinal83>
extern __imp_dsuiext_ordinal84:PANYARGS
dsuiext_ordinal84 TEXTEQU <__imp_dsuiext_ordinal84>
extern __imp_dsuiext_ordinal85:PANYARGS
dsuiext_ordinal85 TEXTEQU <__imp_dsuiext_ordinal85>
extern __imp_dsuiext_ordinal86:PANYARGS
dsuiext_ordinal86 TEXTEQU <__imp_dsuiext_ordinal86>
extern __imp_dsuiext_ordinal87:PANYARGS
dsuiext_ordinal87 TEXTEQU <__imp_dsuiext_ordinal87>
extern __imp_dsuiext_ordinal88:PANYARGS
dsuiext_ordinal88 TEXTEQU <__imp_dsuiext_ordinal88>
extern __imp_dsuiext_ordinal89:PANYARGS
dsuiext_ordinal89 TEXTEQU <__imp_dsuiext_ordinal89>
extern __imp_dsuiext_ordinal90:PANYARGS
dsuiext_ordinal90 TEXTEQU <__imp_dsuiext_ordinal90>
extern __imp_dsuiext_ordinal91:PANYARGS
dsuiext_ordinal91 TEXTEQU <__imp_dsuiext_ordinal91>
extern __imp_dsuiext_ordinal92:PANYARGS
dsuiext_ordinal92 TEXTEQU <__imp_dsuiext_ordinal92>
extern __imp_dsuiext_ordinal93:PANYARGS
dsuiext_ordinal93 TEXTEQU <__imp_dsuiext_ordinal93>
extern __imp_dsuiext_ordinal94:PANYARGS
dsuiext_ordinal94 TEXTEQU <__imp_dsuiext_ordinal94>
extern __imp_dsuiext_ordinal95:PANYARGS
dsuiext_ordinal95 TEXTEQU <__imp_dsuiext_ordinal95>
extern __imp_dsuiext_ordinal96:PANYARGS
dsuiext_ordinal96 TEXTEQU <__imp_dsuiext_ordinal96>
extern __imp_dsuiext_ordinal97:PANYARGS
dsuiext_ordinal97 TEXTEQU <__imp_dsuiext_ordinal97>
extern __imp_dsuiext_ordinal98:PANYARGS
dsuiext_ordinal98 TEXTEQU <__imp_dsuiext_ordinal98>
extern __imp_dsuiext_ordinal99:PANYARGS
dsuiext_ordinal99 TEXTEQU <__imp_dsuiext_ordinal99>
extern __imp_dsuiext_ordinal100:PANYARGS
dsuiext_ordinal100 TEXTEQU <__imp_dsuiext_ordinal100>
extern __imp_dsuiext_ordinal101:PANYARGS
dsuiext_ordinal101 TEXTEQU <__imp_dsuiext_ordinal101>
extern __imp_dsuiext_ordinal102:PANYARGS
dsuiext_ordinal102 TEXTEQU <__imp_dsuiext_ordinal102>
extern __imp_dsuiext_ordinal103:PANYARGS
dsuiext_ordinal103 TEXTEQU <__imp_dsuiext_ordinal103>
extern __imp_dsuiext_ordinal104:PANYARGS
dsuiext_ordinal104 TEXTEQU <__imp_dsuiext_ordinal104>
extern __imp_dsuiext_ordinal105:PANYARGS
dsuiext_ordinal105 TEXTEQU <__imp_dsuiext_ordinal105>
extern __imp_dsuiext_ordinal106:PANYARGS
dsuiext_ordinal106 TEXTEQU <__imp_dsuiext_ordinal106>
extern __imp_dsuiext_ordinal107:PANYARGS
dsuiext_ordinal107 TEXTEQU <__imp_dsuiext_ordinal107>
extern __imp_dsuiext_ordinal108:PANYARGS
dsuiext_ordinal108 TEXTEQU <__imp_dsuiext_ordinal108>
extern __imp_dsuiext_ordinal109:PANYARGS
dsuiext_ordinal109 TEXTEQU <__imp_dsuiext_ordinal109>
extern __imp_dsuiext_ordinal110:PANYARGS
dsuiext_ordinal110 TEXTEQU <__imp_dsuiext_ordinal110>
extern __imp_dsuiext_ordinal111:PANYARGS
dsuiext_ordinal111 TEXTEQU <__imp_dsuiext_ordinal111>
extern __imp_dsuiext_ordinal112:PANYARGS
dsuiext_ordinal112 TEXTEQU <__imp_dsuiext_ordinal112>
extern __imp_dsuiext_ordinal113:PANYARGS
dsuiext_ordinal113 TEXTEQU <__imp_dsuiext_ordinal113>
extern __imp_dsuiext_ordinal114:PANYARGS
dsuiext_ordinal114 TEXTEQU <__imp_dsuiext_ordinal114>
extern __imp_dsuiext_ordinal115:PANYARGS
dsuiext_ordinal115 TEXTEQU <__imp_dsuiext_ordinal115>
extern __imp_dsuiext_ordinal116:PANYARGS
dsuiext_ordinal116 TEXTEQU <__imp_dsuiext_ordinal116>
extern __imp_dsuiext_ordinal117:PANYARGS
dsuiext_ordinal117 TEXTEQU <__imp_dsuiext_ordinal117>
extern __imp_dsuiext_ordinal118:PANYARGS
dsuiext_ordinal118 TEXTEQU <__imp_dsuiext_ordinal118>
extern __imp_dsuiext_ordinal119:PANYARGS
dsuiext_ordinal119 TEXTEQU <__imp_dsuiext_ordinal119>
extern __imp_dsuiext_ordinal120:PANYARGS
dsuiext_ordinal120 TEXTEQU <__imp_dsuiext_ordinal120>
extern __imp_dsuiext_ordinal121:PANYARGS
dsuiext_ordinal121 TEXTEQU <__imp_dsuiext_ordinal121>
extern __imp_dsuiext_ordinal122:PANYARGS
dsuiext_ordinal122 TEXTEQU <__imp_dsuiext_ordinal122>
extern __imp_dsuiext_ordinal123:PANYARGS
dsuiext_ordinal123 TEXTEQU <__imp_dsuiext_ordinal123>
extern __imp_dsuiext_ordinal124:PANYARGS
dsuiext_ordinal124 TEXTEQU <__imp_dsuiext_ordinal124>
extern __imp_dsuiext_ordinal125:PANYARGS
dsuiext_ordinal125 TEXTEQU <__imp_dsuiext_ordinal125>
extern __imp_dsuiext_ordinal126:PANYARGS
dsuiext_ordinal126 TEXTEQU <__imp_dsuiext_ordinal126>
extern __imp_dsuiext_ordinal127:PANYARGS
dsuiext_ordinal127 TEXTEQU <__imp_dsuiext_ordinal127>
extern __imp_dsuiext_ordinal128:PANYARGS
dsuiext_ordinal128 TEXTEQU <__imp_dsuiext_ordinal128>
extern __imp_dsuiext_ordinal129:PANYARGS
dsuiext_ordinal129 TEXTEQU <__imp_dsuiext_ordinal129>
extern __imp_dsuiext_ordinal130:PANYARGS
dsuiext_ordinal130 TEXTEQU <__imp_dsuiext_ordinal130>
extern __imp_dsuiext_ordinal131:PANYARGS
dsuiext_ordinal131 TEXTEQU <__imp_dsuiext_ordinal131>
extern __imp_dsuiext_ordinal132:PANYARGS
dsuiext_ordinal132 TEXTEQU <__imp_dsuiext_ordinal132>
extern __imp_dsuiext_ordinal133:PANYARGS
dsuiext_ordinal133 TEXTEQU <__imp_dsuiext_ordinal133>
extern __imp_dsuiext_ordinal134:PANYARGS
dsuiext_ordinal134 TEXTEQU <__imp_dsuiext_ordinal134>
extern __imp_dsuiext_ordinal135:PANYARGS
dsuiext_ordinal135 TEXTEQU <__imp_dsuiext_ordinal135>
extern __imp_dsuiext_ordinal136:PANYARGS
dsuiext_ordinal136 TEXTEQU <__imp_dsuiext_ordinal136>
extern __imp_dsuiext_ordinal137:PANYARGS
dsuiext_ordinal137 TEXTEQU <__imp_dsuiext_ordinal137>
extern __imp_dsuiext_ordinal138:PANYARGS
dsuiext_ordinal138 TEXTEQU <__imp_dsuiext_ordinal138>
extern __imp_dsuiext_ordinal139:PANYARGS
dsuiext_ordinal139 TEXTEQU <__imp_dsuiext_ordinal139>
extern __imp_dsuiext_ordinal140:PANYARGS
dsuiext_ordinal140 TEXTEQU <__imp_dsuiext_ordinal140>
extern __imp_dsuiext_ordinal141:PANYARGS
dsuiext_ordinal141 TEXTEQU <__imp_dsuiext_ordinal141>
extern __imp_dsuiext_ordinal142:PANYARGS
dsuiext_ordinal142 TEXTEQU <__imp_dsuiext_ordinal142>
extern __imp_dsuiext_ordinal143:PANYARGS
dsuiext_ordinal143 TEXTEQU <__imp_dsuiext_ordinal143>
extern __imp_dsuiext_ordinal144:PANYARGS
dsuiext_ordinal144 TEXTEQU <__imp_dsuiext_ordinal144>
extern __imp_dsuiext_ordinal145:PANYARGS
dsuiext_ordinal145 TEXTEQU <__imp_dsuiext_ordinal145>
extern __imp_dsuiext_ordinal146:PANYARGS
dsuiext_ordinal146 TEXTEQU <__imp_dsuiext_ordinal146>
extern __imp_dsuiext_ordinal147:PANYARGS
dsuiext_ordinal147 TEXTEQU <__imp_dsuiext_ordinal147>
extern __imp_dsuiext_ordinal148:PANYARGS
dsuiext_ordinal148 TEXTEQU <__imp_dsuiext_ordinal148>
extern __imp_dsuiext_ordinal149:PANYARGS
dsuiext_ordinal149 TEXTEQU <__imp_dsuiext_ordinal149>
extern __imp_dsuiext_ordinal150:PANYARGS
dsuiext_ordinal150 TEXTEQU <__imp_dsuiext_ordinal150>
extern __imp_dsuiext_ordinal151:PANYARGS
dsuiext_ordinal151 TEXTEQU <__imp_dsuiext_ordinal151>
extern __imp_dsuiext_ordinal152:PANYARGS
dsuiext_ordinal152 TEXTEQU <__imp_dsuiext_ordinal152>
extern __imp_dsuiext_ordinal153:PANYARGS
dsuiext_ordinal153 TEXTEQU <__imp_dsuiext_ordinal153>
extern __imp_dsuiext_ordinal154:PANYARGS
dsuiext_ordinal154 TEXTEQU <__imp_dsuiext_ordinal154>
extern __imp_dsuiext_ordinal155:PANYARGS
dsuiext_ordinal155 TEXTEQU <__imp_dsuiext_ordinal155>
extern __imp_dsuiext_ordinal156:PANYARGS
dsuiext_ordinal156 TEXTEQU <__imp_dsuiext_ordinal156>
extern __imp_dsuiext_ordinal157:PANYARGS
dsuiext_ordinal157 TEXTEQU <__imp_dsuiext_ordinal157>
extern __imp_dsuiext_ordinal158:PANYARGS
dsuiext_ordinal158 TEXTEQU <__imp_dsuiext_ordinal158>
extern __imp_dsuiext_ordinal159:PANYARGS
dsuiext_ordinal159 TEXTEQU <__imp_dsuiext_ordinal159>
extern __imp_dsuiext_ordinal160:PANYARGS
dsuiext_ordinal160 TEXTEQU <__imp_dsuiext_ordinal160>
extern __imp_dsuiext_ordinal161:PANYARGS
dsuiext_ordinal161 TEXTEQU <__imp_dsuiext_ordinal161>
extern __imp_dsuiext_ordinal162:PANYARGS
dsuiext_ordinal162 TEXTEQU <__imp_dsuiext_ordinal162>
extern __imp_dsuiext_ordinal163:PANYARGS
dsuiext_ordinal163 TEXTEQU <__imp_dsuiext_ordinal163>
extern __imp_dsuiext_ordinal164:PANYARGS
dsuiext_ordinal164 TEXTEQU <__imp_dsuiext_ordinal164>
extern __imp_dsuiext_ordinal165:PANYARGS
dsuiext_ordinal165 TEXTEQU <__imp_dsuiext_ordinal165>
extern __imp_dsuiext_ordinal166:PANYARGS
dsuiext_ordinal166 TEXTEQU <__imp_dsuiext_ordinal166>
extern __imp_dsuiext_ordinal167:PANYARGS
dsuiext_ordinal167 TEXTEQU <__imp_dsuiext_ordinal167>
extern __imp_dsuiext_ordinal168:PANYARGS
dsuiext_ordinal168 TEXTEQU <__imp_dsuiext_ordinal168>
extern __imp_dsuiext_ordinal169:PANYARGS
dsuiext_ordinal169 TEXTEQU <__imp_dsuiext_ordinal169>
extern __imp_dsuiext_ordinal170:PANYARGS
dsuiext_ordinal170 TEXTEQU <__imp_dsuiext_ordinal170>
extern __imp_dsuiext_ordinal171:PANYARGS
dsuiext_ordinal171 TEXTEQU <__imp_dsuiext_ordinal171>
extern __imp_dsuiext_ordinal172:PANYARGS
dsuiext_ordinal172 TEXTEQU <__imp_dsuiext_ordinal172>
extern __imp_dsuiext_ordinal173:PANYARGS
dsuiext_ordinal173 TEXTEQU <__imp_dsuiext_ordinal173>
extern __imp_dsuiext_ordinal174:PANYARGS
dsuiext_ordinal174 TEXTEQU <__imp_dsuiext_ordinal174>
extern __imp_dsuiext_ordinal175:PANYARGS
dsuiext_ordinal175 TEXTEQU <__imp_dsuiext_ordinal175>
extern __imp_dsuiext_ordinal176:PANYARGS
dsuiext_ordinal176 TEXTEQU <__imp_dsuiext_ordinal176>
extern __imp_dsuiext_ordinal177:PANYARGS
dsuiext_ordinal177 TEXTEQU <__imp_dsuiext_ordinal177>
extern __imp_dsuiext_ordinal178:PANYARGS
dsuiext_ordinal178 TEXTEQU <__imp_dsuiext_ordinal178>
extern __imp_dsuiext_ordinal179:PANYARGS
dsuiext_ordinal179 TEXTEQU <__imp_dsuiext_ordinal179>
extern __imp_dsuiext_ordinal180:PANYARGS
dsuiext_ordinal180 TEXTEQU <__imp_dsuiext_ordinal180>
extern __imp_dsuiext_ordinal181:PANYARGS
dsuiext_ordinal181 TEXTEQU <__imp_dsuiext_ordinal181>
extern __imp_dsuiext_ordinal182:PANYARGS
dsuiext_ordinal182 TEXTEQU <__imp_dsuiext_ordinal182>
extern __imp_dsuiext_ordinal183:PANYARGS
dsuiext_ordinal183 TEXTEQU <__imp_dsuiext_ordinal183>
extern __imp_dsuiext_ordinal184:PANYARGS
dsuiext_ordinal184 TEXTEQU <__imp_dsuiext_ordinal184>
extern __imp_dsuiext_ordinal185:PANYARGS
dsuiext_ordinal185 TEXTEQU <__imp_dsuiext_ordinal185>
extern __imp_dsuiext_ordinal186:PANYARGS
dsuiext_ordinal186 TEXTEQU <__imp_dsuiext_ordinal186>
extern __imp_dsuiext_ordinal187:PANYARGS
dsuiext_ordinal187 TEXTEQU <__imp_dsuiext_ordinal187>
extern __imp_dsuiext_ordinal188:PANYARGS
dsuiext_ordinal188 TEXTEQU <__imp_dsuiext_ordinal188>
extern __imp_dsuiext_ordinal189:PANYARGS
dsuiext_ordinal189 TEXTEQU <__imp_dsuiext_ordinal189>
extern __imp_dsuiext_ordinal190:PANYARGS
dsuiext_ordinal190 TEXTEQU <__imp_dsuiext_ordinal190>
extern __imp_dsuiext_ordinal191:PANYARGS
dsuiext_ordinal191 TEXTEQU <__imp_dsuiext_ordinal191>
extern __imp_dsuiext_ordinal192:PANYARGS
dsuiext_ordinal192 TEXTEQU <__imp_dsuiext_ordinal192>
extern __imp_dsuiext_ordinal193:PANYARGS
dsuiext_ordinal193 TEXTEQU <__imp_dsuiext_ordinal193>
extern __imp_dsuiext_ordinal194:PANYARGS
dsuiext_ordinal194 TEXTEQU <__imp_dsuiext_ordinal194>
extern __imp_dsuiext_ordinal195:PANYARGS
dsuiext_ordinal195 TEXTEQU <__imp_dsuiext_ordinal195>
extern __imp_dsuiext_ordinal196:PANYARGS
dsuiext_ordinal196 TEXTEQU <__imp_dsuiext_ordinal196>
extern __imp_dsuiext_ordinal197:PANYARGS
dsuiext_ordinal197 TEXTEQU <__imp_dsuiext_ordinal197>
extern __imp_dsuiext_ordinal198:PANYARGS
dsuiext_ordinal198 TEXTEQU <__imp_dsuiext_ordinal198>
extern __imp_dsuiext_ordinal199:PANYARGS
dsuiext_ordinal199 TEXTEQU <__imp_dsuiext_ordinal199>
extern __imp_dsuiext_ordinal200:PANYARGS
dsuiext_ordinal200 TEXTEQU <__imp_dsuiext_ordinal200>
extern __imp_dsuiext_ordinal201:PANYARGS
dsuiext_ordinal201 TEXTEQU <__imp_dsuiext_ordinal201>
extern __imp_dsuiext_ordinal202:PANYARGS
dsuiext_ordinal202 TEXTEQU <__imp_dsuiext_ordinal202>
extern __imp_dsuiext_ordinal203:PANYARGS
dsuiext_ordinal203 TEXTEQU <__imp_dsuiext_ordinal203>
extern __imp_dsuiext_ordinal204:PANYARGS
dsuiext_ordinal204 TEXTEQU <__imp_dsuiext_ordinal204>
extern __imp_dsuiext_ordinal205:PANYARGS
dsuiext_ordinal205 TEXTEQU <__imp_dsuiext_ordinal205>
extern __imp_dsuiext_ordinal206:PANYARGS
dsuiext_ordinal206 TEXTEQU <__imp_dsuiext_ordinal206>
extern __imp_dsuiext_ordinal207:PANYARGS
dsuiext_ordinal207 TEXTEQU <__imp_dsuiext_ordinal207>
extern __imp_dsuiext_ordinal208:PANYARGS
dsuiext_ordinal208 TEXTEQU <__imp_dsuiext_ordinal208>
extern __imp_dsuiext_ordinal209:PANYARGS
dsuiext_ordinal209 TEXTEQU <__imp_dsuiext_ordinal209>
extern __imp_dsuiext_ordinal210:PANYARGS
dsuiext_ordinal210 TEXTEQU <__imp_dsuiext_ordinal210>
extern __imp_dsuiext_ordinal211:PANYARGS
dsuiext_ordinal211 TEXTEQU <__imp_dsuiext_ordinal211>
extern __imp_dsuiext_ordinal212:PANYARGS
dsuiext_ordinal212 TEXTEQU <__imp_dsuiext_ordinal212>
extern __imp_dsuiext_ordinal213:PANYARGS
dsuiext_ordinal213 TEXTEQU <__imp_dsuiext_ordinal213>
extern __imp_dsuiext_ordinal214:PANYARGS
dsuiext_ordinal214 TEXTEQU <__imp_dsuiext_ordinal214>
extern __imp_dsuiext_ordinal215:PANYARGS
dsuiext_ordinal215 TEXTEQU <__imp_dsuiext_ordinal215>
extern __imp_dsuiext_ordinal216:PANYARGS
dsuiext_ordinal216 TEXTEQU <__imp_dsuiext_ordinal216>
extern __imp_dsuiext_ordinal217:PANYARGS
dsuiext_ordinal217 TEXTEQU <__imp_dsuiext_ordinal217>
extern __imp_dsuiext_ordinal218:PANYARGS
dsuiext_ordinal218 TEXTEQU <__imp_dsuiext_ordinal218>
extern __imp_dsuiext_ordinal219:PANYARGS
dsuiext_ordinal219 TEXTEQU <__imp_dsuiext_ordinal219>
extern __imp_dsuiext_ordinal220:PANYARGS
dsuiext_ordinal220 TEXTEQU <__imp_dsuiext_ordinal220>
extern __imp_dsuiext_ordinal221:PANYARGS
dsuiext_ordinal221 TEXTEQU <__imp_dsuiext_ordinal221>
extern __imp_dsuiext_ordinal222:PANYARGS
dsuiext_ordinal222 TEXTEQU <__imp_dsuiext_ordinal222>
extern __imp_dsuiext_ordinal223:PANYARGS
dsuiext_ordinal223 TEXTEQU <__imp_dsuiext_ordinal223>
extern __imp_dsuiext_ordinal224:PANYARGS
dsuiext_ordinal224 TEXTEQU <__imp_dsuiext_ordinal224>
extern __imp_dsuiext_ordinal225:PANYARGS
dsuiext_ordinal225 TEXTEQU <__imp_dsuiext_ordinal225>
extern __imp_dsuiext_ordinal226:PANYARGS
dsuiext_ordinal226 TEXTEQU <__imp_dsuiext_ordinal226>
extern __imp_dsuiext_ordinal227:PANYARGS
dsuiext_ordinal227 TEXTEQU <__imp_dsuiext_ordinal227>
extern __imp_dsuiext_ordinal228:PANYARGS
dsuiext_ordinal228 TEXTEQU <__imp_dsuiext_ordinal228>
extern __imp_dsuiext_ordinal229:PANYARGS
dsuiext_ordinal229 TEXTEQU <__imp_dsuiext_ordinal229>
extern __imp_dsuiext_ordinal230:PANYARGS
dsuiext_ordinal230 TEXTEQU <__imp_dsuiext_ordinal230>
extern __imp_dsuiext_ordinal231:PANYARGS
dsuiext_ordinal231 TEXTEQU <__imp_dsuiext_ordinal231>
extern __imp_dsuiext_ordinal232:PANYARGS
dsuiext_ordinal232 TEXTEQU <__imp_dsuiext_ordinal232>
extern __imp_dsuiext_ordinal233:PANYARGS
dsuiext_ordinal233 TEXTEQU <__imp_dsuiext_ordinal233>
extern __imp_dsuiext_ordinal234:PANYARGS
dsuiext_ordinal234 TEXTEQU <__imp_dsuiext_ordinal234>
extern __imp_dsuiext_ordinal235:PANYARGS
dsuiext_ordinal235 TEXTEQU <__imp_dsuiext_ordinal235>
extern __imp_dsuiext_ordinal236:PANYARGS
dsuiext_ordinal236 TEXTEQU <__imp_dsuiext_ordinal236>
extern __imp_dsuiext_ordinal237:PANYARGS
dsuiext_ordinal237 TEXTEQU <__imp_dsuiext_ordinal237>
extern __imp_dsuiext_ordinal238:PANYARGS
dsuiext_ordinal238 TEXTEQU <__imp_dsuiext_ordinal238>
extern __imp_dsuiext_ordinal239:PANYARGS
dsuiext_ordinal239 TEXTEQU <__imp_dsuiext_ordinal239>
extern __imp_dsuiext_ordinal240:PANYARGS
dsuiext_ordinal240 TEXTEQU <__imp_dsuiext_ordinal240>
extern __imp_dsuiext_ordinal241:PANYARGS
dsuiext_ordinal241 TEXTEQU <__imp_dsuiext_ordinal241>
extern __imp_dsuiext_ordinal242:PANYARGS
dsuiext_ordinal242 TEXTEQU <__imp_dsuiext_ordinal242>
extern __imp_dsuiext_ordinal243:PANYARGS
dsuiext_ordinal243 TEXTEQU <__imp_dsuiext_ordinal243>
extern __imp_dsuiext_ordinal244:PANYARGS
dsuiext_ordinal244 TEXTEQU <__imp_dsuiext_ordinal244>
extern __imp_dsuiext_ordinal245:PANYARGS
dsuiext_ordinal245 TEXTEQU <__imp_dsuiext_ordinal245>
extern __imp_dsuiext_ordinal246:PANYARGS
dsuiext_ordinal246 TEXTEQU <__imp_dsuiext_ordinal246>
extern __imp_dsuiext_ordinal247:PANYARGS
dsuiext_ordinal247 TEXTEQU <__imp_dsuiext_ordinal247>
extern __imp_dsuiext_ordinal248:PANYARGS
dsuiext_ordinal248 TEXTEQU <__imp_dsuiext_ordinal248>
extern __imp_dsuiext_ordinal249:PANYARGS
dsuiext_ordinal249 TEXTEQU <__imp_dsuiext_ordinal249>
extern __imp_dsuiext_ordinal250:PANYARGS
dsuiext_ordinal250 TEXTEQU <__imp_dsuiext_ordinal250>
extern __imp_dsuiext_ordinal251:PANYARGS
dsuiext_ordinal251 TEXTEQU <__imp_dsuiext_ordinal251>
extern __imp_dsuiext_ordinal252:PANYARGS
dsuiext_ordinal252 TEXTEQU <__imp_dsuiext_ordinal252>
extern __imp_dsuiext_ordinal253:PANYARGS
dsuiext_ordinal253 TEXTEQU <__imp_dsuiext_ordinal253>
extern __imp_dsuiext_ordinal254:PANYARGS
dsuiext_ordinal254 TEXTEQU <__imp_dsuiext_ordinal254>
extern __imp_dsuiext_ordinal255:PANYARGS
dsuiext_ordinal255 TEXTEQU <__imp_dsuiext_ordinal255>
extern __imp_dsuiext_ordinal256:PANYARGS
dsuiext_ordinal256 TEXTEQU <__imp_dsuiext_ordinal256>
extern __imp_DsGetIcon:PANYARGS
DsGetIcon TEXTEQU <__imp_DsGetIcon>
extern __imp_dsuiext_ordinal258:PANYARGS
dsuiext_ordinal258 TEXTEQU <__imp_dsuiext_ordinal258>
extern __imp_DsGetFriendlyClassName:PANYARGS
DsGetFriendlyClassName TEXTEQU <__imp_DsGetFriendlyClassName>
extern __imp_dsuiext_ordinal260:PANYARGS
dsuiext_ordinal260 TEXTEQU <__imp_dsuiext_ordinal260>
extern __imp_dsuiext_ordinal261:PANYARGS
dsuiext_ordinal261 TEXTEQU <__imp_dsuiext_ordinal261>
extern __imp_dsuiext_ordinal262:PANYARGS
dsuiext_ordinal262 TEXTEQU <__imp_dsuiext_ordinal262>
extern __imp_dsuiext_ordinal263:PANYARGS
dsuiext_ordinal263 TEXTEQU <__imp_dsuiext_ordinal263>
extern __imp_dsuiext_ordinal264:PANYARGS
dsuiext_ordinal264 TEXTEQU <__imp_dsuiext_ordinal264>
extern __imp_dsuiext_ordinal265:PANYARGS
dsuiext_ordinal265 TEXTEQU <__imp_dsuiext_ordinal265>
extern __imp_dsuiext_ordinal266:PANYARGS
dsuiext_ordinal266 TEXTEQU <__imp_dsuiext_ordinal266>
extern __imp_dsuiext_ordinal267:PANYARGS
dsuiext_ordinal267 TEXTEQU <__imp_dsuiext_ordinal267>
extern __imp_dsuiext_ordinal268:PANYARGS
dsuiext_ordinal268 TEXTEQU <__imp_dsuiext_ordinal268>
extern __imp_dsuiext_ordinal269:PANYARGS
dsuiext_ordinal269 TEXTEQU <__imp_dsuiext_ordinal269>
extern __imp_dsuiext_ordinal270:PANYARGS
dsuiext_ordinal270 TEXTEQU <__imp_dsuiext_ordinal270>
extern __imp_dsuiext_ordinal271:PANYARGS
dsuiext_ordinal271 TEXTEQU <__imp_dsuiext_ordinal271>
extern __imp_dsuiext_ordinal272:PANYARGS
dsuiext_ordinal272 TEXTEQU <__imp_dsuiext_ordinal272>
extern __imp_dsuiext_ordinal273:PANYARGS
dsuiext_ordinal273 TEXTEQU <__imp_dsuiext_ordinal273>
extern __imp_dsuiext_ordinal274:PANYARGS
dsuiext_ordinal274 TEXTEQU <__imp_dsuiext_ordinal274>
extern __imp_dsuiext_ordinal275:PANYARGS
dsuiext_ordinal275 TEXTEQU <__imp_dsuiext_ordinal275>
extern __imp_dsuiext_ordinal276:PANYARGS
dsuiext_ordinal276 TEXTEQU <__imp_dsuiext_ordinal276>
extern __imp_dsuiext_ordinal277:PANYARGS
dsuiext_ordinal277 TEXTEQU <__imp_dsuiext_ordinal277>
extern __imp_dsuiext_ordinal278:PANYARGS
dsuiext_ordinal278 TEXTEQU <__imp_dsuiext_ordinal278>
extern __imp_dsuiext_ordinal279:PANYARGS
dsuiext_ordinal279 TEXTEQU <__imp_dsuiext_ordinal279>
extern __imp_dsuiext_ordinal280:PANYARGS
dsuiext_ordinal280 TEXTEQU <__imp_dsuiext_ordinal280>
extern __imp_dsuiext_ordinal281:PANYARGS
dsuiext_ordinal281 TEXTEQU <__imp_dsuiext_ordinal281>
extern __imp_dsuiext_ordinal282:PANYARGS
dsuiext_ordinal282 TEXTEQU <__imp_dsuiext_ordinal282>
extern __imp_dsuiext_ordinal283:PANYARGS
dsuiext_ordinal283 TEXTEQU <__imp_dsuiext_ordinal283>
extern __imp_dsuiext_ordinal284:PANYARGS
dsuiext_ordinal284 TEXTEQU <__imp_dsuiext_ordinal284>
extern __imp_dsuiext_ordinal285:PANYARGS
dsuiext_ordinal285 TEXTEQU <__imp_dsuiext_ordinal285>
extern __imp_dsuiext_ordinal286:PANYARGS
dsuiext_ordinal286 TEXTEQU <__imp_dsuiext_ordinal286>
extern __imp_dsuiext_ordinal287:PANYARGS
dsuiext_ordinal287 TEXTEQU <__imp_dsuiext_ordinal287>
extern __imp_dsuiext_ordinal288:PANYARGS
dsuiext_ordinal288 TEXTEQU <__imp_dsuiext_ordinal288>
extern __imp_dsuiext_ordinal289:PANYARGS
dsuiext_ordinal289 TEXTEQU <__imp_dsuiext_ordinal289>
extern __imp_dsuiext_ordinal290:PANYARGS
dsuiext_ordinal290 TEXTEQU <__imp_dsuiext_ordinal290>
extern __imp_dsuiext_ordinal291:PANYARGS
dsuiext_ordinal291 TEXTEQU <__imp_dsuiext_ordinal291>
extern __imp_dsuiext_ordinal292:PANYARGS
dsuiext_ordinal292 TEXTEQU <__imp_dsuiext_ordinal292>
extern __imp_dsuiext_ordinal293:PANYARGS
dsuiext_ordinal293 TEXTEQU <__imp_dsuiext_ordinal293>
extern __imp_dsuiext_ordinal294:PANYARGS
dsuiext_ordinal294 TEXTEQU <__imp_dsuiext_ordinal294>
extern __imp_dsuiext_ordinal295:PANYARGS
dsuiext_ordinal295 TEXTEQU <__imp_dsuiext_ordinal295>
extern __imp_dsuiext_ordinal296:PANYARGS
dsuiext_ordinal296 TEXTEQU <__imp_dsuiext_ordinal296>
extern __imp_dsuiext_ordinal297:PANYARGS
dsuiext_ordinal297 TEXTEQU <__imp_dsuiext_ordinal297>
extern __imp_dsuiext_ordinal298:PANYARGS
dsuiext_ordinal298 TEXTEQU <__imp_dsuiext_ordinal298>
extern __imp_dsuiext_ordinal299:PANYARGS
dsuiext_ordinal299 TEXTEQU <__imp_dsuiext_ordinal299>
extern __imp_dsuiext_ordinal300:PANYARGS
dsuiext_ordinal300 TEXTEQU <__imp_dsuiext_ordinal300>
extern __imp_dsuiext_ordinal301:PANYARGS
dsuiext_ordinal301 TEXTEQU <__imp_dsuiext_ordinal301>
extern __imp_dsuiext_ordinal302:PANYARGS
dsuiext_ordinal302 TEXTEQU <__imp_dsuiext_ordinal302>
extern __imp_dsuiext_ordinal303:PANYARGS
dsuiext_ordinal303 TEXTEQU <__imp_dsuiext_ordinal303>
extern __imp_dsuiext_ordinal304:PANYARGS
dsuiext_ordinal304 TEXTEQU <__imp_dsuiext_ordinal304>
extern __imp_dsuiext_ordinal305:PANYARGS
dsuiext_ordinal305 TEXTEQU <__imp_dsuiext_ordinal305>
extern __imp_dsuiext_ordinal306:PANYARGS
dsuiext_ordinal306 TEXTEQU <__imp_dsuiext_ordinal306>
extern __imp_dsuiext_ordinal307:PANYARGS
dsuiext_ordinal307 TEXTEQU <__imp_dsuiext_ordinal307>
extern __imp_dsuiext_ordinal308:PANYARGS
dsuiext_ordinal308 TEXTEQU <__imp_dsuiext_ordinal308>
extern __imp_dsuiext_ordinal309:PANYARGS
dsuiext_ordinal309 TEXTEQU <__imp_dsuiext_ordinal309>
extern __imp_dsuiext_ordinal310:PANYARGS
dsuiext_ordinal310 TEXTEQU <__imp_dsuiext_ordinal310>
extern __imp_dsuiext_ordinal311:PANYARGS
dsuiext_ordinal311 TEXTEQU <__imp_dsuiext_ordinal311>
extern __imp_dsuiext_ordinal312:PANYARGS
dsuiext_ordinal312 TEXTEQU <__imp_dsuiext_ordinal312>
extern __imp_dsuiext_ordinal313:PANYARGS
dsuiext_ordinal313 TEXTEQU <__imp_dsuiext_ordinal313>
extern __imp_dsuiext_ordinal314:PANYARGS
dsuiext_ordinal314 TEXTEQU <__imp_dsuiext_ordinal314>
extern __imp_dsuiext_ordinal315:PANYARGS
dsuiext_ordinal315 TEXTEQU <__imp_dsuiext_ordinal315>
extern __imp_dsuiext_ordinal316:PANYARGS
dsuiext_ordinal316 TEXTEQU <__imp_dsuiext_ordinal316>
extern __imp_dsuiext_ordinal317:PANYARGS
dsuiext_ordinal317 TEXTEQU <__imp_dsuiext_ordinal317>
extern __imp_dsuiext_ordinal318:PANYARGS
dsuiext_ordinal318 TEXTEQU <__imp_dsuiext_ordinal318>
extern __imp_dsuiext_ordinal319:PANYARGS
dsuiext_ordinal319 TEXTEQU <__imp_dsuiext_ordinal319>
extern __imp_dsuiext_ordinal320:PANYARGS
dsuiext_ordinal320 TEXTEQU <__imp_dsuiext_ordinal320>
extern __imp_dsuiext_ordinal321:PANYARGS
dsuiext_ordinal321 TEXTEQU <__imp_dsuiext_ordinal321>
extern __imp_dsuiext_ordinal322:PANYARGS
dsuiext_ordinal322 TEXTEQU <__imp_dsuiext_ordinal322>
extern __imp_dsuiext_ordinal323:PANYARGS
dsuiext_ordinal323 TEXTEQU <__imp_dsuiext_ordinal323>
extern __imp_dsuiext_ordinal324:PANYARGS
dsuiext_ordinal324 TEXTEQU <__imp_dsuiext_ordinal324>
extern __imp_dsuiext_ordinal325:PANYARGS
dsuiext_ordinal325 TEXTEQU <__imp_dsuiext_ordinal325>
extern __imp_dsuiext_ordinal326:PANYARGS
dsuiext_ordinal326 TEXTEQU <__imp_dsuiext_ordinal326>
extern __imp_dsuiext_ordinal327:PANYARGS
dsuiext_ordinal327 TEXTEQU <__imp_dsuiext_ordinal327>
extern __imp_dsuiext_ordinal328:PANYARGS
dsuiext_ordinal328 TEXTEQU <__imp_dsuiext_ordinal328>
extern __imp_dsuiext_ordinal329:PANYARGS
dsuiext_ordinal329 TEXTEQU <__imp_dsuiext_ordinal329>
extern __imp_dsuiext_ordinal330:PANYARGS
dsuiext_ordinal330 TEXTEQU <__imp_dsuiext_ordinal330>
extern __imp_dsuiext_ordinal331:PANYARGS
dsuiext_ordinal331 TEXTEQU <__imp_dsuiext_ordinal331>
extern __imp_dsuiext_ordinal332:PANYARGS
dsuiext_ordinal332 TEXTEQU <__imp_dsuiext_ordinal332>
extern __imp_dsuiext_ordinal333:PANYARGS
dsuiext_ordinal333 TEXTEQU <__imp_dsuiext_ordinal333>
extern __imp_dsuiext_ordinal334:PANYARGS
dsuiext_ordinal334 TEXTEQU <__imp_dsuiext_ordinal334>
extern __imp_dsuiext_ordinal335:PANYARGS
dsuiext_ordinal335 TEXTEQU <__imp_dsuiext_ordinal335>
extern __imp_dsuiext_ordinal336:PANYARGS
dsuiext_ordinal336 TEXTEQU <__imp_dsuiext_ordinal336>
extern __imp_dsuiext_ordinal337:PANYARGS
dsuiext_ordinal337 TEXTEQU <__imp_dsuiext_ordinal337>
extern __imp_dsuiext_ordinal338:PANYARGS
dsuiext_ordinal338 TEXTEQU <__imp_dsuiext_ordinal338>
extern __imp_dsuiext_ordinal339:PANYARGS
dsuiext_ordinal339 TEXTEQU <__imp_dsuiext_ordinal339>
extern __imp_dsuiext_ordinal340:PANYARGS
dsuiext_ordinal340 TEXTEQU <__imp_dsuiext_ordinal340>
extern __imp_dsuiext_ordinal341:PANYARGS
dsuiext_ordinal341 TEXTEQU <__imp_dsuiext_ordinal341>
extern __imp_dsuiext_ordinal342:PANYARGS
dsuiext_ordinal342 TEXTEQU <__imp_dsuiext_ordinal342>
extern __imp_dsuiext_ordinal343:PANYARGS
dsuiext_ordinal343 TEXTEQU <__imp_dsuiext_ordinal343>
extern __imp_dsuiext_ordinal344:PANYARGS
dsuiext_ordinal344 TEXTEQU <__imp_dsuiext_ordinal344>
extern __imp_dsuiext_ordinal345:PANYARGS
dsuiext_ordinal345 TEXTEQU <__imp_dsuiext_ordinal345>
extern __imp_dsuiext_ordinal346:PANYARGS
dsuiext_ordinal346 TEXTEQU <__imp_dsuiext_ordinal346>
extern __imp_dsuiext_ordinal347:PANYARGS
dsuiext_ordinal347 TEXTEQU <__imp_dsuiext_ordinal347>
extern __imp_dsuiext_ordinal348:PANYARGS
dsuiext_ordinal348 TEXTEQU <__imp_dsuiext_ordinal348>
extern __imp_dsuiext_ordinal349:PANYARGS
dsuiext_ordinal349 TEXTEQU <__imp_dsuiext_ordinal349>
extern __imp_dsuiext_ordinal350:PANYARGS
dsuiext_ordinal350 TEXTEQU <__imp_dsuiext_ordinal350>
extern __imp_dsuiext_ordinal351:PANYARGS
dsuiext_ordinal351 TEXTEQU <__imp_dsuiext_ordinal351>
extern __imp_dsuiext_ordinal352:PANYARGS
dsuiext_ordinal352 TEXTEQU <__imp_dsuiext_ordinal352>
extern __imp_dsuiext_ordinal353:PANYARGS
dsuiext_ordinal353 TEXTEQU <__imp_dsuiext_ordinal353>
extern __imp_dsuiext_ordinal354:PANYARGS
dsuiext_ordinal354 TEXTEQU <__imp_dsuiext_ordinal354>
extern __imp_dsuiext_ordinal355:PANYARGS
dsuiext_ordinal355 TEXTEQU <__imp_dsuiext_ordinal355>
extern __imp_dsuiext_ordinal356:PANYARGS
dsuiext_ordinal356 TEXTEQU <__imp_dsuiext_ordinal356>
extern __imp_dsuiext_ordinal357:PANYARGS
dsuiext_ordinal357 TEXTEQU <__imp_dsuiext_ordinal357>
extern __imp_dsuiext_ordinal358:PANYARGS
dsuiext_ordinal358 TEXTEQU <__imp_dsuiext_ordinal358>
extern __imp_dsuiext_ordinal359:PANYARGS
dsuiext_ordinal359 TEXTEQU <__imp_dsuiext_ordinal359>
extern __imp_dsuiext_ordinal360:PANYARGS
dsuiext_ordinal360 TEXTEQU <__imp_dsuiext_ordinal360>
extern __imp_dsuiext_ordinal361:PANYARGS
dsuiext_ordinal361 TEXTEQU <__imp_dsuiext_ordinal361>
extern __imp_dsuiext_ordinal362:PANYARGS
dsuiext_ordinal362 TEXTEQU <__imp_dsuiext_ordinal362>
extern __imp_dsuiext_ordinal363:PANYARGS
dsuiext_ordinal363 TEXTEQU <__imp_dsuiext_ordinal363>
extern __imp_dsuiext_ordinal364:PANYARGS
dsuiext_ordinal364 TEXTEQU <__imp_dsuiext_ordinal364>
extern __imp_dsuiext_ordinal365:PANYARGS
dsuiext_ordinal365 TEXTEQU <__imp_dsuiext_ordinal365>
extern __imp_dsuiext_ordinal366:PANYARGS
dsuiext_ordinal366 TEXTEQU <__imp_dsuiext_ordinal366>
extern __imp_dsuiext_ordinal367:PANYARGS
dsuiext_ordinal367 TEXTEQU <__imp_dsuiext_ordinal367>
extern __imp_dsuiext_ordinal368:PANYARGS
dsuiext_ordinal368 TEXTEQU <__imp_dsuiext_ordinal368>
extern __imp_dsuiext_ordinal369:PANYARGS
dsuiext_ordinal369 TEXTEQU <__imp_dsuiext_ordinal369>
extern __imp_dsuiext_ordinal370:PANYARGS
dsuiext_ordinal370 TEXTEQU <__imp_dsuiext_ordinal370>
extern __imp_dsuiext_ordinal371:PANYARGS
dsuiext_ordinal371 TEXTEQU <__imp_dsuiext_ordinal371>
extern __imp_dsuiext_ordinal372:PANYARGS
dsuiext_ordinal372 TEXTEQU <__imp_dsuiext_ordinal372>
extern __imp_dsuiext_ordinal373:PANYARGS
dsuiext_ordinal373 TEXTEQU <__imp_dsuiext_ordinal373>
extern __imp_dsuiext_ordinal374:PANYARGS
dsuiext_ordinal374 TEXTEQU <__imp_dsuiext_ordinal374>
extern __imp_dsuiext_ordinal375:PANYARGS
dsuiext_ordinal375 TEXTEQU <__imp_dsuiext_ordinal375>
extern __imp_dsuiext_ordinal376:PANYARGS
dsuiext_ordinal376 TEXTEQU <__imp_dsuiext_ordinal376>
extern __imp_dsuiext_ordinal377:PANYARGS
dsuiext_ordinal377 TEXTEQU <__imp_dsuiext_ordinal377>
extern __imp_dsuiext_ordinal378:PANYARGS
dsuiext_ordinal378 TEXTEQU <__imp_dsuiext_ordinal378>
extern __imp_dsuiext_ordinal379:PANYARGS
dsuiext_ordinal379 TEXTEQU <__imp_dsuiext_ordinal379>
extern __imp_dsuiext_ordinal380:PANYARGS
dsuiext_ordinal380 TEXTEQU <__imp_dsuiext_ordinal380>
extern __imp_dsuiext_ordinal381:PANYARGS
dsuiext_ordinal381 TEXTEQU <__imp_dsuiext_ordinal381>
extern __imp_dsuiext_ordinal382:PANYARGS
dsuiext_ordinal382 TEXTEQU <__imp_dsuiext_ordinal382>
extern __imp_dsuiext_ordinal383:PANYARGS
dsuiext_ordinal383 TEXTEQU <__imp_dsuiext_ordinal383>
extern __imp_dsuiext_ordinal384:PANYARGS
dsuiext_ordinal384 TEXTEQU <__imp_dsuiext_ordinal384>
extern __imp_dsuiext_ordinal385:PANYARGS
dsuiext_ordinal385 TEXTEQU <__imp_dsuiext_ordinal385>
extern __imp_dsuiext_ordinal386:PANYARGS
dsuiext_ordinal386 TEXTEQU <__imp_dsuiext_ordinal386>
extern __imp_dsuiext_ordinal387:PANYARGS
dsuiext_ordinal387 TEXTEQU <__imp_dsuiext_ordinal387>
extern __imp_dsuiext_ordinal388:PANYARGS
dsuiext_ordinal388 TEXTEQU <__imp_dsuiext_ordinal388>
extern __imp_dsuiext_ordinal389:PANYARGS
dsuiext_ordinal389 TEXTEQU <__imp_dsuiext_ordinal389>
extern __imp_dsuiext_ordinal390:PANYARGS
dsuiext_ordinal390 TEXTEQU <__imp_dsuiext_ordinal390>
extern __imp_dsuiext_ordinal391:PANYARGS
dsuiext_ordinal391 TEXTEQU <__imp_dsuiext_ordinal391>
extern __imp_dsuiext_ordinal392:PANYARGS
dsuiext_ordinal392 TEXTEQU <__imp_dsuiext_ordinal392>
extern __imp_dsuiext_ordinal393:PANYARGS
dsuiext_ordinal393 TEXTEQU <__imp_dsuiext_ordinal393>
extern __imp_dsuiext_ordinal394:PANYARGS
dsuiext_ordinal394 TEXTEQU <__imp_dsuiext_ordinal394>
extern __imp_dsuiext_ordinal395:PANYARGS
dsuiext_ordinal395 TEXTEQU <__imp_dsuiext_ordinal395>
extern __imp_dsuiext_ordinal396:PANYARGS
dsuiext_ordinal396 TEXTEQU <__imp_dsuiext_ordinal396>
extern __imp_dsuiext_ordinal397:PANYARGS
dsuiext_ordinal397 TEXTEQU <__imp_dsuiext_ordinal397>
extern __imp_dsuiext_ordinal398:PANYARGS
dsuiext_ordinal398 TEXTEQU <__imp_dsuiext_ordinal398>
extern __imp_dsuiext_ordinal399:PANYARGS
dsuiext_ordinal399 TEXTEQU <__imp_dsuiext_ordinal399>
extern __imp_dsuiext_ordinal400:PANYARGS
dsuiext_ordinal400 TEXTEQU <__imp_dsuiext_ordinal400>
extern __imp_dsuiext_ordinal401:PANYARGS
dsuiext_ordinal401 TEXTEQU <__imp_dsuiext_ordinal401>
extern __imp_dsuiext_ordinal402:PANYARGS
dsuiext_ordinal402 TEXTEQU <__imp_dsuiext_ordinal402>
extern __imp_dsuiext_ordinal403:PANYARGS
dsuiext_ordinal403 TEXTEQU <__imp_dsuiext_ordinal403>
extern __imp_dsuiext_ordinal404:PANYARGS
dsuiext_ordinal404 TEXTEQU <__imp_dsuiext_ordinal404>
extern __imp_dsuiext_ordinal405:PANYARGS
dsuiext_ordinal405 TEXTEQU <__imp_dsuiext_ordinal405>
extern __imp_dsuiext_ordinal406:PANYARGS
dsuiext_ordinal406 TEXTEQU <__imp_dsuiext_ordinal406>
extern __imp_dsuiext_ordinal407:PANYARGS
dsuiext_ordinal407 TEXTEQU <__imp_dsuiext_ordinal407>
extern __imp_dsuiext_ordinal408:PANYARGS
dsuiext_ordinal408 TEXTEQU <__imp_dsuiext_ordinal408>
extern __imp_dsuiext_ordinal409:PANYARGS
dsuiext_ordinal409 TEXTEQU <__imp_dsuiext_ordinal409>
extern __imp_dsuiext_ordinal410:PANYARGS
dsuiext_ordinal410 TEXTEQU <__imp_dsuiext_ordinal410>
extern __imp_dsuiext_ordinal411:PANYARGS
dsuiext_ordinal411 TEXTEQU <__imp_dsuiext_ordinal411>
extern __imp_dsuiext_ordinal412:PANYARGS
dsuiext_ordinal412 TEXTEQU <__imp_dsuiext_ordinal412>
extern __imp_dsuiext_ordinal413:PANYARGS
dsuiext_ordinal413 TEXTEQU <__imp_dsuiext_ordinal413>
extern __imp_dsuiext_ordinal414:PANYARGS
dsuiext_ordinal414 TEXTEQU <__imp_dsuiext_ordinal414>
extern __imp_dsuiext_ordinal415:PANYARGS
dsuiext_ordinal415 TEXTEQU <__imp_dsuiext_ordinal415>
extern __imp_dsuiext_ordinal416:PANYARGS
dsuiext_ordinal416 TEXTEQU <__imp_dsuiext_ordinal416>
extern __imp_dsuiext_ordinal417:PANYARGS
dsuiext_ordinal417 TEXTEQU <__imp_dsuiext_ordinal417>
extern __imp_dsuiext_ordinal418:PANYARGS
dsuiext_ordinal418 TEXTEQU <__imp_dsuiext_ordinal418>
extern __imp_dsuiext_ordinal419:PANYARGS
dsuiext_ordinal419 TEXTEQU <__imp_dsuiext_ordinal419>
extern __imp_dsuiext_ordinal420:PANYARGS
dsuiext_ordinal420 TEXTEQU <__imp_dsuiext_ordinal420>
extern __imp_dsuiext_ordinal421:PANYARGS
dsuiext_ordinal421 TEXTEQU <__imp_dsuiext_ordinal421>
extern __imp_dsuiext_ordinal422:PANYARGS
dsuiext_ordinal422 TEXTEQU <__imp_dsuiext_ordinal422>
extern __imp_dsuiext_ordinal423:PANYARGS
dsuiext_ordinal423 TEXTEQU <__imp_dsuiext_ordinal423>
extern __imp_dsuiext_ordinal424:PANYARGS
dsuiext_ordinal424 TEXTEQU <__imp_dsuiext_ordinal424>
extern __imp_dsuiext_ordinal425:PANYARGS
dsuiext_ordinal425 TEXTEQU <__imp_dsuiext_ordinal425>
extern __imp_dsuiext_ordinal426:PANYARGS
dsuiext_ordinal426 TEXTEQU <__imp_dsuiext_ordinal426>
extern __imp_dsuiext_ordinal427:PANYARGS
dsuiext_ordinal427 TEXTEQU <__imp_dsuiext_ordinal427>
extern __imp_dsuiext_ordinal428:PANYARGS
dsuiext_ordinal428 TEXTEQU <__imp_dsuiext_ordinal428>
extern __imp_dsuiext_ordinal429:PANYARGS
dsuiext_ordinal429 TEXTEQU <__imp_dsuiext_ordinal429>
extern __imp_dsuiext_ordinal430:PANYARGS
dsuiext_ordinal430 TEXTEQU <__imp_dsuiext_ordinal430>
extern __imp_dsuiext_ordinal431:PANYARGS
dsuiext_ordinal431 TEXTEQU <__imp_dsuiext_ordinal431>
extern __imp_dsuiext_ordinal432:PANYARGS
dsuiext_ordinal432 TEXTEQU <__imp_dsuiext_ordinal432>
extern __imp_dsuiext_ordinal433:PANYARGS
dsuiext_ordinal433 TEXTEQU <__imp_dsuiext_ordinal433>
extern __imp_dsuiext_ordinal434:PANYARGS
dsuiext_ordinal434 TEXTEQU <__imp_dsuiext_ordinal434>
extern __imp_dsuiext_ordinal435:PANYARGS
dsuiext_ordinal435 TEXTEQU <__imp_dsuiext_ordinal435>
extern __imp_dsuiext_ordinal436:PANYARGS
dsuiext_ordinal436 TEXTEQU <__imp_dsuiext_ordinal436>
extern __imp_dsuiext_ordinal437:PANYARGS
dsuiext_ordinal437 TEXTEQU <__imp_dsuiext_ordinal437>
extern __imp_dsuiext_ordinal438:PANYARGS
dsuiext_ordinal438 TEXTEQU <__imp_dsuiext_ordinal438>
extern __imp_dsuiext_ordinal439:PANYARGS
dsuiext_ordinal439 TEXTEQU <__imp_dsuiext_ordinal439>
extern __imp_dsuiext_ordinal440:PANYARGS
dsuiext_ordinal440 TEXTEQU <__imp_dsuiext_ordinal440>
extern __imp_dsuiext_ordinal441:PANYARGS
dsuiext_ordinal441 TEXTEQU <__imp_dsuiext_ordinal441>
extern __imp_dsuiext_ordinal442:PANYARGS
dsuiext_ordinal442 TEXTEQU <__imp_dsuiext_ordinal442>
extern __imp_dsuiext_ordinal443:PANYARGS
dsuiext_ordinal443 TEXTEQU <__imp_dsuiext_ordinal443>
extern __imp_dsuiext_ordinal444:PANYARGS
dsuiext_ordinal444 TEXTEQU <__imp_dsuiext_ordinal444>
extern __imp_dsuiext_ordinal445:PANYARGS
dsuiext_ordinal445 TEXTEQU <__imp_dsuiext_ordinal445>
extern __imp_dsuiext_ordinal446:PANYARGS
dsuiext_ordinal446 TEXTEQU <__imp_dsuiext_ordinal446>
extern __imp_dsuiext_ordinal447:PANYARGS
dsuiext_ordinal447 TEXTEQU <__imp_dsuiext_ordinal447>
extern __imp_dsuiext_ordinal448:PANYARGS
dsuiext_ordinal448 TEXTEQU <__imp_dsuiext_ordinal448>
extern __imp_dsuiext_ordinal449:PANYARGS
dsuiext_ordinal449 TEXTEQU <__imp_dsuiext_ordinal449>
extern __imp_dsuiext_ordinal450:PANYARGS
dsuiext_ordinal450 TEXTEQU <__imp_dsuiext_ordinal450>
extern __imp_dsuiext_ordinal451:PANYARGS
dsuiext_ordinal451 TEXTEQU <__imp_dsuiext_ordinal451>
extern __imp_dsuiext_ordinal452:PANYARGS
dsuiext_ordinal452 TEXTEQU <__imp_dsuiext_ordinal452>
extern __imp_dsuiext_ordinal453:PANYARGS
dsuiext_ordinal453 TEXTEQU <__imp_dsuiext_ordinal453>
extern __imp_dsuiext_ordinal454:PANYARGS
dsuiext_ordinal454 TEXTEQU <__imp_dsuiext_ordinal454>
extern __imp_dsuiext_ordinal455:PANYARGS
dsuiext_ordinal455 TEXTEQU <__imp_dsuiext_ordinal455>
extern __imp_dsuiext_ordinal456:PANYARGS
dsuiext_ordinal456 TEXTEQU <__imp_dsuiext_ordinal456>
extern __imp_dsuiext_ordinal457:PANYARGS
dsuiext_ordinal457 TEXTEQU <__imp_dsuiext_ordinal457>
extern __imp_dsuiext_ordinal458:PANYARGS
dsuiext_ordinal458 TEXTEQU <__imp_dsuiext_ordinal458>
extern __imp_dsuiext_ordinal459:PANYARGS
dsuiext_ordinal459 TEXTEQU <__imp_dsuiext_ordinal459>
extern __imp_dsuiext_ordinal460:PANYARGS
dsuiext_ordinal460 TEXTEQU <__imp_dsuiext_ordinal460>
extern __imp_dsuiext_ordinal461:PANYARGS
dsuiext_ordinal461 TEXTEQU <__imp_dsuiext_ordinal461>
extern __imp_dsuiext_ordinal462:PANYARGS
dsuiext_ordinal462 TEXTEQU <__imp_dsuiext_ordinal462>
extern __imp_dsuiext_ordinal463:PANYARGS
dsuiext_ordinal463 TEXTEQU <__imp_dsuiext_ordinal463>
extern __imp_dsuiext_ordinal464:PANYARGS
dsuiext_ordinal464 TEXTEQU <__imp_dsuiext_ordinal464>
extern __imp_dsuiext_ordinal465:PANYARGS
dsuiext_ordinal465 TEXTEQU <__imp_dsuiext_ordinal465>
extern __imp_dsuiext_ordinal466:PANYARGS
dsuiext_ordinal466 TEXTEQU <__imp_dsuiext_ordinal466>
extern __imp_dsuiext_ordinal467:PANYARGS
dsuiext_ordinal467 TEXTEQU <__imp_dsuiext_ordinal467>
extern __imp_dsuiext_ordinal468:PANYARGS
dsuiext_ordinal468 TEXTEQU <__imp_dsuiext_ordinal468>
extern __imp_dsuiext_ordinal469:PANYARGS
dsuiext_ordinal469 TEXTEQU <__imp_dsuiext_ordinal469>
extern __imp_dsuiext_ordinal470:PANYARGS
dsuiext_ordinal470 TEXTEQU <__imp_dsuiext_ordinal470>
extern __imp_dsuiext_ordinal471:PANYARGS
dsuiext_ordinal471 TEXTEQU <__imp_dsuiext_ordinal471>
extern __imp_dsuiext_ordinal472:PANYARGS
dsuiext_ordinal472 TEXTEQU <__imp_dsuiext_ordinal472>
extern __imp_dsuiext_ordinal473:PANYARGS
dsuiext_ordinal473 TEXTEQU <__imp_dsuiext_ordinal473>
extern __imp_dsuiext_ordinal474:PANYARGS
dsuiext_ordinal474 TEXTEQU <__imp_dsuiext_ordinal474>
extern __imp_dsuiext_ordinal475:PANYARGS
dsuiext_ordinal475 TEXTEQU <__imp_dsuiext_ordinal475>
extern __imp_dsuiext_ordinal476:PANYARGS
dsuiext_ordinal476 TEXTEQU <__imp_dsuiext_ordinal476>
extern __imp_dsuiext_ordinal477:PANYARGS
dsuiext_ordinal477 TEXTEQU <__imp_dsuiext_ordinal477>
extern __imp_dsuiext_ordinal478:PANYARGS
dsuiext_ordinal478 TEXTEQU <__imp_dsuiext_ordinal478>
extern __imp_dsuiext_ordinal479:PANYARGS
dsuiext_ordinal479 TEXTEQU <__imp_dsuiext_ordinal479>
extern __imp_dsuiext_ordinal480:PANYARGS
dsuiext_ordinal480 TEXTEQU <__imp_dsuiext_ordinal480>
extern __imp_dsuiext_ordinal481:PANYARGS
dsuiext_ordinal481 TEXTEQU <__imp_dsuiext_ordinal481>
extern __imp_dsuiext_ordinal482:PANYARGS
dsuiext_ordinal482 TEXTEQU <__imp_dsuiext_ordinal482>
extern __imp_dsuiext_ordinal483:PANYARGS
dsuiext_ordinal483 TEXTEQU <__imp_dsuiext_ordinal483>
extern __imp_dsuiext_ordinal484:PANYARGS
dsuiext_ordinal484 TEXTEQU <__imp_dsuiext_ordinal484>
extern __imp_dsuiext_ordinal485:PANYARGS
dsuiext_ordinal485 TEXTEQU <__imp_dsuiext_ordinal485>
extern __imp_dsuiext_ordinal486:PANYARGS
dsuiext_ordinal486 TEXTEQU <__imp_dsuiext_ordinal486>
extern __imp_dsuiext_ordinal487:PANYARGS
dsuiext_ordinal487 TEXTEQU <__imp_dsuiext_ordinal487>
extern __imp_dsuiext_ordinal488:PANYARGS
dsuiext_ordinal488 TEXTEQU <__imp_dsuiext_ordinal488>
extern __imp_dsuiext_ordinal489:PANYARGS
dsuiext_ordinal489 TEXTEQU <__imp_dsuiext_ordinal489>
extern __imp_dsuiext_ordinal490:PANYARGS
dsuiext_ordinal490 TEXTEQU <__imp_dsuiext_ordinal490>
extern __imp_dsuiext_ordinal491:PANYARGS
dsuiext_ordinal491 TEXTEQU <__imp_dsuiext_ordinal491>
extern __imp_dsuiext_ordinal492:PANYARGS
dsuiext_ordinal492 TEXTEQU <__imp_dsuiext_ordinal492>
extern __imp_dsuiext_ordinal493:PANYARGS
dsuiext_ordinal493 TEXTEQU <__imp_dsuiext_ordinal493>
extern __imp_dsuiext_ordinal494:PANYARGS
dsuiext_ordinal494 TEXTEQU <__imp_dsuiext_ordinal494>
extern __imp_dsuiext_ordinal495:PANYARGS
dsuiext_ordinal495 TEXTEQU <__imp_dsuiext_ordinal495>
extern __imp_dsuiext_ordinal496:PANYARGS
dsuiext_ordinal496 TEXTEQU <__imp_dsuiext_ordinal496>
extern __imp_dsuiext_ordinal497:PANYARGS
dsuiext_ordinal497 TEXTEQU <__imp_dsuiext_ordinal497>
extern __imp_dsuiext_ordinal498:PANYARGS
dsuiext_ordinal498 TEXTEQU <__imp_dsuiext_ordinal498>
extern __imp_dsuiext_ordinal499:PANYARGS
dsuiext_ordinal499 TEXTEQU <__imp_dsuiext_ordinal499>
extern __imp_dsuiext_ordinal500:PANYARGS
dsuiext_ordinal500 TEXTEQU <__imp_dsuiext_ordinal500>
extern __imp_dsuiext_ordinal501:PANYARGS
dsuiext_ordinal501 TEXTEQU <__imp_dsuiext_ordinal501>
extern __imp_dsuiext_ordinal502:PANYARGS
dsuiext_ordinal502 TEXTEQU <__imp_dsuiext_ordinal502>
extern __imp_dsuiext_ordinal503:PANYARGS
dsuiext_ordinal503 TEXTEQU <__imp_dsuiext_ordinal503>
extern __imp_dsuiext_ordinal504:PANYARGS
dsuiext_ordinal504 TEXTEQU <__imp_dsuiext_ordinal504>
extern __imp_dsuiext_ordinal505:PANYARGS
dsuiext_ordinal505 TEXTEQU <__imp_dsuiext_ordinal505>
extern __imp_dsuiext_ordinal506:PANYARGS
dsuiext_ordinal506 TEXTEQU <__imp_dsuiext_ordinal506>
extern __imp_dsuiext_ordinal507:PANYARGS
dsuiext_ordinal507 TEXTEQU <__imp_dsuiext_ordinal507>
extern __imp_dsuiext_ordinal508:PANYARGS
dsuiext_ordinal508 TEXTEQU <__imp_dsuiext_ordinal508>
extern __imp_dsuiext_ordinal509:PANYARGS
dsuiext_ordinal509 TEXTEQU <__imp_dsuiext_ordinal509>
extern __imp_dsuiext_ordinal510:PANYARGS
dsuiext_ordinal510 TEXTEQU <__imp_dsuiext_ordinal510>
extern __imp_dsuiext_ordinal511:PANYARGS
dsuiext_ordinal511 TEXTEQU <__imp_dsuiext_ordinal511>
extern __imp_dsuiext_ordinal512:PANYARGS
dsuiext_ordinal512 TEXTEQU <__imp_dsuiext_ordinal512>
extern __imp_dsuiext_ordinal513:PANYARGS
dsuiext_ordinal513 TEXTEQU <__imp_dsuiext_ordinal513>
extern __imp_dsuiext_ordinal514:PANYARGS
dsuiext_ordinal514 TEXTEQU <__imp_dsuiext_ordinal514>
extern __imp_dsuiext_ordinal515:PANYARGS
dsuiext_ordinal515 TEXTEQU <__imp_dsuiext_ordinal515>
extern __imp_dsuiext_ordinal516:PANYARGS
dsuiext_ordinal516 TEXTEQU <__imp_dsuiext_ordinal516>
extern __imp_dsuiext_ordinal517:PANYARGS
dsuiext_ordinal517 TEXTEQU <__imp_dsuiext_ordinal517>
extern __imp_dsuiext_ordinal518:PANYARGS
dsuiext_ordinal518 TEXTEQU <__imp_dsuiext_ordinal518>
extern __imp_dsuiext_ordinal519:PANYARGS
dsuiext_ordinal519 TEXTEQU <__imp_dsuiext_ordinal519>
extern __imp_dsuiext_ordinal520:PANYARGS
dsuiext_ordinal520 TEXTEQU <__imp_dsuiext_ordinal520>
extern __imp_dsuiext_ordinal521:PANYARGS
dsuiext_ordinal521 TEXTEQU <__imp_dsuiext_ordinal521>
extern __imp_dsuiext_ordinal522:PANYARGS
dsuiext_ordinal522 TEXTEQU <__imp_dsuiext_ordinal522>
extern __imp_dsuiext_ordinal523:PANYARGS
dsuiext_ordinal523 TEXTEQU <__imp_dsuiext_ordinal523>
extern __imp_dsuiext_ordinal524:PANYARGS
dsuiext_ordinal524 TEXTEQU <__imp_dsuiext_ordinal524>
extern __imp_dsuiext_ordinal525:PANYARGS
dsuiext_ordinal525 TEXTEQU <__imp_dsuiext_ordinal525>
extern __imp_dsuiext_ordinal526:PANYARGS
dsuiext_ordinal526 TEXTEQU <__imp_dsuiext_ordinal526>
extern __imp_dsuiext_ordinal527:PANYARGS
dsuiext_ordinal527 TEXTEQU <__imp_dsuiext_ordinal527>
extern __imp_dsuiext_ordinal528:PANYARGS
dsuiext_ordinal528 TEXTEQU <__imp_dsuiext_ordinal528>
extern __imp_dsuiext_ordinal529:PANYARGS
dsuiext_ordinal529 TEXTEQU <__imp_dsuiext_ordinal529>
extern __imp_dsuiext_ordinal530:PANYARGS
dsuiext_ordinal530 TEXTEQU <__imp_dsuiext_ordinal530>
extern __imp_dsuiext_ordinal531:PANYARGS
dsuiext_ordinal531 TEXTEQU <__imp_dsuiext_ordinal531>
extern __imp_dsuiext_ordinal532:PANYARGS
dsuiext_ordinal532 TEXTEQU <__imp_dsuiext_ordinal532>
extern __imp_dsuiext_ordinal533:PANYARGS
dsuiext_ordinal533 TEXTEQU <__imp_dsuiext_ordinal533>
extern __imp_dsuiext_ordinal534:PANYARGS
dsuiext_ordinal534 TEXTEQU <__imp_dsuiext_ordinal534>
extern __imp_dsuiext_ordinal535:PANYARGS
dsuiext_ordinal535 TEXTEQU <__imp_dsuiext_ordinal535>
extern __imp_dsuiext_ordinal536:PANYARGS
dsuiext_ordinal536 TEXTEQU <__imp_dsuiext_ordinal536>
extern __imp_dsuiext_ordinal537:PANYARGS
dsuiext_ordinal537 TEXTEQU <__imp_dsuiext_ordinal537>
extern __imp_dsuiext_ordinal538:PANYARGS
dsuiext_ordinal538 TEXTEQU <__imp_dsuiext_ordinal538>
extern __imp_dsuiext_ordinal539:PANYARGS
dsuiext_ordinal539 TEXTEQU <__imp_dsuiext_ordinal539>
extern __imp_dsuiext_ordinal540:PANYARGS
dsuiext_ordinal540 TEXTEQU <__imp_dsuiext_ordinal540>
extern __imp_dsuiext_ordinal541:PANYARGS
dsuiext_ordinal541 TEXTEQU <__imp_dsuiext_ordinal541>
extern __imp_dsuiext_ordinal542:PANYARGS
dsuiext_ordinal542 TEXTEQU <__imp_dsuiext_ordinal542>
extern __imp_dsuiext_ordinal543:PANYARGS
dsuiext_ordinal543 TEXTEQU <__imp_dsuiext_ordinal543>
extern __imp_dsuiext_ordinal544:PANYARGS
dsuiext_ordinal544 TEXTEQU <__imp_dsuiext_ordinal544>
extern __imp_dsuiext_ordinal545:PANYARGS
dsuiext_ordinal545 TEXTEQU <__imp_dsuiext_ordinal545>
extern __imp_dsuiext_ordinal546:PANYARGS
dsuiext_ordinal546 TEXTEQU <__imp_dsuiext_ordinal546>
extern __imp_dsuiext_ordinal547:PANYARGS
dsuiext_ordinal547 TEXTEQU <__imp_dsuiext_ordinal547>
extern __imp_dsuiext_ordinal548:PANYARGS
dsuiext_ordinal548 TEXTEQU <__imp_dsuiext_ordinal548>
extern __imp_dsuiext_ordinal549:PANYARGS
dsuiext_ordinal549 TEXTEQU <__imp_dsuiext_ordinal549>
extern __imp_dsuiext_ordinal550:PANYARGS
dsuiext_ordinal550 TEXTEQU <__imp_dsuiext_ordinal550>
extern __imp_dsuiext_ordinal551:PANYARGS
dsuiext_ordinal551 TEXTEQU <__imp_dsuiext_ordinal551>
extern __imp_dsuiext_ordinal552:PANYARGS
dsuiext_ordinal552 TEXTEQU <__imp_dsuiext_ordinal552>
extern __imp_dsuiext_ordinal553:PANYARGS
dsuiext_ordinal553 TEXTEQU <__imp_dsuiext_ordinal553>
extern __imp_dsuiext_ordinal554:PANYARGS
dsuiext_ordinal554 TEXTEQU <__imp_dsuiext_ordinal554>
extern __imp_dsuiext_ordinal555:PANYARGS
dsuiext_ordinal555 TEXTEQU <__imp_dsuiext_ordinal555>
extern __imp_dsuiext_ordinal556:PANYARGS
dsuiext_ordinal556 TEXTEQU <__imp_dsuiext_ordinal556>
extern __imp_dsuiext_ordinal557:PANYARGS
dsuiext_ordinal557 TEXTEQU <__imp_dsuiext_ordinal557>
extern __imp_dsuiext_ordinal558:PANYARGS
dsuiext_ordinal558 TEXTEQU <__imp_dsuiext_ordinal558>
extern __imp_dsuiext_ordinal559:PANYARGS
dsuiext_ordinal559 TEXTEQU <__imp_dsuiext_ordinal559>
extern __imp_dsuiext_ordinal560:PANYARGS
dsuiext_ordinal560 TEXTEQU <__imp_dsuiext_ordinal560>
extern __imp_dsuiext_ordinal561:PANYARGS
dsuiext_ordinal561 TEXTEQU <__imp_dsuiext_ordinal561>
extern __imp_dsuiext_ordinal562:PANYARGS
dsuiext_ordinal562 TEXTEQU <__imp_dsuiext_ordinal562>
extern __imp_dsuiext_ordinal563:PANYARGS
dsuiext_ordinal563 TEXTEQU <__imp_dsuiext_ordinal563>
extern __imp_dsuiext_ordinal564:PANYARGS
dsuiext_ordinal564 TEXTEQU <__imp_dsuiext_ordinal564>
extern __imp_dsuiext_ordinal565:PANYARGS
dsuiext_ordinal565 TEXTEQU <__imp_dsuiext_ordinal565>
extern __imp_dsuiext_ordinal566:PANYARGS
dsuiext_ordinal566 TEXTEQU <__imp_dsuiext_ordinal566>
extern __imp_dsuiext_ordinal567:PANYARGS
dsuiext_ordinal567 TEXTEQU <__imp_dsuiext_ordinal567>
extern __imp_dsuiext_ordinal568:PANYARGS
dsuiext_ordinal568 TEXTEQU <__imp_dsuiext_ordinal568>
extern __imp_dsuiext_ordinal569:PANYARGS
dsuiext_ordinal569 TEXTEQU <__imp_dsuiext_ordinal569>
extern __imp_dsuiext_ordinal570:PANYARGS
dsuiext_ordinal570 TEXTEQU <__imp_dsuiext_ordinal570>
extern __imp_dsuiext_ordinal571:PANYARGS
dsuiext_ordinal571 TEXTEQU <__imp_dsuiext_ordinal571>
extern __imp_dsuiext_ordinal572:PANYARGS
dsuiext_ordinal572 TEXTEQU <__imp_dsuiext_ordinal572>
extern __imp_dsuiext_ordinal573:PANYARGS
dsuiext_ordinal573 TEXTEQU <__imp_dsuiext_ordinal573>
extern __imp_dsuiext_ordinal574:PANYARGS
dsuiext_ordinal574 TEXTEQU <__imp_dsuiext_ordinal574>
extern __imp_dsuiext_ordinal575:PANYARGS
dsuiext_ordinal575 TEXTEQU <__imp_dsuiext_ordinal575>
extern __imp_dsuiext_ordinal576:PANYARGS
dsuiext_ordinal576 TEXTEQU <__imp_dsuiext_ordinal576>
extern __imp_dsuiext_ordinal577:PANYARGS
dsuiext_ordinal577 TEXTEQU <__imp_dsuiext_ordinal577>
extern __imp_dsuiext_ordinal578:PANYARGS
dsuiext_ordinal578 TEXTEQU <__imp_dsuiext_ordinal578>
