extern __imp_DUserCastHandle:PANYARGS
DUserCastHandle TEXTEQU <__imp_DUserCastHandle>
extern __imp_DUserDeleteGadget:PANYARGS
DUserDeleteGadget TEXTEQU <__imp_DUserDeleteGadget>
extern __imp_GetStdColorBrushF:PANYARGS
GetStdColorBrushF TEXTEQU <__imp_GetStdColorBrushF>
extern __imp_GetStdColorF:PANYARGS
GetStdColorF TEXTEQU <__imp_GetStdColorF>
extern __imp_GetStdColorPenF:PANYARGS
GetStdColorPenF TEXTEQU <__imp_GetStdColorPenF>
extern __imp_UtilDrawOutlineRect:PANYARGS
UtilDrawOutlineRect TEXTEQU <__imp_UtilDrawOutlineRect>
extern __imp_AddGadgetMessageHandler:PANYARGS
AddGadgetMessageHandler TEXTEQU <__imp_AddGadgetMessageHandler>
extern __imp_AttachWndProcA:PANYARGS
AttachWndProc  TEXTEQU <__imp_AttachWndProcA>
extern __imp_AttachWndProcW:PANYARGS
AttachWndProcW TEXTEQU <__imp_AttachWndProcW>
extern __imp_AutoTrace:PANYARGS
AutoTrace TEXTEQU <__imp_AutoTrace>
extern __imp_BeginTransition:PANYARGS
BeginTransition TEXTEQU <__imp_BeginTransition>
extern __imp_BuildAnimation:PANYARGS
BuildAnimation TEXTEQU <__imp_BuildAnimation>
extern __imp_BuildDropTarget:PANYARGS
BuildDropTarget TEXTEQU <__imp_BuildDropTarget>
extern __imp_BuildInterpolation:PANYARGS
BuildInterpolation TEXTEQU <__imp_BuildInterpolation>
extern __imp_CreateAction:PANYARGS
CreateAction TEXTEQU <__imp_CreateAction>
extern __imp_CreateGadget:PANYARGS
CreateGadget TEXTEQU <__imp_CreateGadget>
extern __imp_CreateTransition:PANYARGS
CreateTransition TEXTEQU <__imp_CreateTransition>
extern __imp_DUserBuildGadget:PANYARGS
DUserBuildGadget TEXTEQU <__imp_DUserBuildGadget>
extern __imp_DUserCastClass:PANYARGS
DUserCastClass TEXTEQU <__imp_DUserCastClass>
extern __imp_DUserCastDirect:PANYARGS
DUserCastDirect TEXTEQU <__imp_DUserCastDirect>
extern __imp_DUserFindClass:PANYARGS
DUserFindClass TEXTEQU <__imp_DUserFindClass>
extern __imp_DUserGetAlphaPRID:PANYARGS
DUserGetAlphaPRID TEXTEQU <__imp_DUserGetAlphaPRID>
extern __imp_DUserGetGutsData:PANYARGS
DUserGetGutsData TEXTEQU <__imp_DUserGetGutsData>
extern __imp_DUserGetRectPRID:PANYARGS
DUserGetRectPRID TEXTEQU <__imp_DUserGetRectPRID>
extern __imp_DUserGetRotatePRID:PANYARGS
DUserGetRotatePRID TEXTEQU <__imp_DUserGetRotatePRID>
extern __imp_DUserGetScalePRID:PANYARGS
DUserGetScalePRID TEXTEQU <__imp_DUserGetScalePRID>
extern __imp_DUserInstanceOf:PANYARGS
DUserInstanceOf TEXTEQU <__imp_DUserInstanceOf>
extern __imp_DUserPostEvent:PANYARGS
DUserPostEvent TEXTEQU <__imp_DUserPostEvent>
extern __imp_DUserPostMethod:PANYARGS
DUserPostMethod TEXTEQU <__imp_DUserPostMethod>
extern __imp_DUserRegisterGuts:PANYARGS
DUserRegisterGuts TEXTEQU <__imp_DUserRegisterGuts>
extern __imp_DUserRegisterStub:PANYARGS
DUserRegisterStub TEXTEQU <__imp_DUserRegisterStub>
extern __imp_DUserRegisterSuper:PANYARGS
DUserRegisterSuper TEXTEQU <__imp_DUserRegisterSuper>
extern __imp_DUserSendEvent:PANYARGS
DUserSendEvent TEXTEQU <__imp_DUserSendEvent>
extern __imp_DUserSendMethod:PANYARGS
DUserSendMethod TEXTEQU <__imp_DUserSendMethod>
extern __imp_DUserStopAnimation:PANYARGS
DUserStopAnimation TEXTEQU <__imp_DUserStopAnimation>
extern __imp_DeleteHandle:PANYARGS
DeleteHandle TEXTEQU <__imp_DeleteHandle>
extern __imp_DetachWndProc:PANYARGS
DetachWndProc TEXTEQU <__imp_DetachWndProc>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DrawGadgetTree:PANYARGS
DrawGadgetTree TEXTEQU <__imp_DrawGadgetTree>
extern __imp_EndTransition:PANYARGS
EndTransition TEXTEQU <__imp_EndTransition>
extern __imp_EnumGadgets:PANYARGS
EnumGadgets TEXTEQU <__imp_EnumGadgets>
extern __imp_FindGadgetFromPoint:PANYARGS
FindGadgetFromPoint TEXTEQU <__imp_FindGadgetFromPoint>
extern __imp_FindGadgetMessages:PANYARGS
FindGadgetMessages TEXTEQU <__imp_FindGadgetMessages>
extern __imp_FindStdColor:PANYARGS
FindStdColor TEXTEQU <__imp_FindStdColor>
extern __imp_FireGadgetMessages:PANYARGS
FireGadgetMessages TEXTEQU <__imp_FireGadgetMessages>
extern __imp_ForwardGadgetMessage:PANYARGS
ForwardGadgetMessage TEXTEQU <__imp_ForwardGadgetMessage>
extern __imp_GetActionTimeslice:PANYARGS
GetActionTimeslice TEXTEQU <__imp_GetActionTimeslice>
extern __imp_GetDebug:PANYARGS
GetDebug TEXTEQU <__imp_GetDebug>
extern __imp_GetGadget:PANYARGS
GetGadget TEXTEQU <__imp_GetGadget>
extern __imp_GetGadgetAnimation:PANYARGS
GetGadgetAnimation TEXTEQU <__imp_GetGadgetAnimation>
extern __imp_GetGadgetBufferInfo:PANYARGS
GetGadgetBufferInfo TEXTEQU <__imp_GetGadgetBufferInfo>
extern __imp_GetGadgetCenterPoint:PANYARGS
GetGadgetCenterPoint TEXTEQU <__imp_GetGadgetCenterPoint>
extern __imp_GetGadgetFocus:PANYARGS
GetGadgetFocus TEXTEQU <__imp_GetGadgetFocus>
extern __imp_GetGadgetMessageFilter:PANYARGS
GetGadgetMessageFilter TEXTEQU <__imp_GetGadgetMessageFilter>
extern __imp_GetGadgetProperty:PANYARGS
GetGadgetProperty TEXTEQU <__imp_GetGadgetProperty>
extern __imp_GetGadgetRect:PANYARGS
GetGadgetRect TEXTEQU <__imp_GetGadgetRect>
extern __imp_GetGadgetRgn:PANYARGS
GetGadgetRgn TEXTEQU <__imp_GetGadgetRgn>
extern __imp_GetGadgetRootInfo:PANYARGS
GetGadgetRootInfo TEXTEQU <__imp_GetGadgetRootInfo>
extern __imp_GetGadgetRotation:PANYARGS
GetGadgetRotation TEXTEQU <__imp_GetGadgetRotation>
extern __imp_GetGadgetScale:PANYARGS
GetGadgetScale TEXTEQU <__imp_GetGadgetScale>
extern __imp_GetGadgetSize:PANYARGS
GetGadgetSize TEXTEQU <__imp_GetGadgetSize>
extern __imp_GetGadgetStyle:PANYARGS
GetGadgetStyle TEXTEQU <__imp_GetGadgetStyle>
extern __imp_GetGadgetTicket:PANYARGS
GetGadgetTicket TEXTEQU <__imp_GetGadgetTicket>
extern __imp_GetMessageExA:PANYARGS
GetMessageEx  TEXTEQU <__imp_GetMessageExA>
extern __imp_GetMessageExW:PANYARGS
GetMessageExW TEXTEQU <__imp_GetMessageExW>
extern __imp_GetStdColorBrushI:PANYARGS
GetStdColorBrushI TEXTEQU <__imp_GetStdColorBrushI>
extern __imp_GetStdColorI:PANYARGS
GetStdColorI TEXTEQU <__imp_GetStdColorI>
extern __imp_GetStdColorName:PANYARGS
GetStdColorName TEXTEQU <__imp_GetStdColorName>
extern __imp_GetStdColorPenI:PANYARGS
GetStdColorPenI TEXTEQU <__imp_GetStdColorPenI>
extern __imp_GetStdPalette:PANYARGS
GetStdPalette TEXTEQU <__imp_GetStdPalette>
extern __imp_GetTransitionInterface:PANYARGS
GetTransitionInterface TEXTEQU <__imp_GetTransitionInterface>
extern __imp_InitGadgetComponent:PANYARGS
InitGadgetComponent TEXTEQU <__imp_InitGadgetComponent>
extern __imp_InitGadgets:PANYARGS
InitGadgets TEXTEQU <__imp_InitGadgets>
extern __imp_InvalidateGadget:PANYARGS
InvalidateGadget TEXTEQU <__imp_InvalidateGadget>
extern __imp_IsGadgetParentChainStyle:PANYARGS
IsGadgetParentChainStyle TEXTEQU <__imp_IsGadgetParentChainStyle>
extern __imp_IsInsideContext:PANYARGS
IsInsideContext TEXTEQU <__imp_IsInsideContext>
extern __imp_IsStartDelete:PANYARGS
IsStartDelete TEXTEQU <__imp_IsStartDelete>
extern __imp_LookupGadgetTicket:PANYARGS
LookupGadgetTicket TEXTEQU <__imp_LookupGadgetTicket>
extern __imp_MapGadgetPoints:PANYARGS
MapGadgetPoints TEXTEQU <__imp_MapGadgetPoints>
extern __imp_PeekMessageExA:PANYARGS
PeekMessageEx  TEXTEQU <__imp_PeekMessageExA>
extern __imp_PeekMessageExW:PANYARGS
PeekMessageExW TEXTEQU <__imp_PeekMessageExW>
extern __imp_PlayTransition:PANYARGS
PlayTransition TEXTEQU <__imp_PlayTransition>
extern __imp_PrintTransition:PANYARGS
PrintTransition TEXTEQU <__imp_PrintTransition>
extern __imp_RegisterGadgetMessage:PANYARGS
RegisterGadgetMessage TEXTEQU <__imp_RegisterGadgetMessage>
extern __imp_RegisterGadgetMessageString:PANYARGS
RegisterGadgetMessageString TEXTEQU <__imp_RegisterGadgetMessageString>
extern __imp_RegisterGadgetProperty:PANYARGS
RegisterGadgetProperty TEXTEQU <__imp_RegisterGadgetProperty>
extern __imp_RemoveGadgetMessageHandler:PANYARGS
RemoveGadgetMessageHandler TEXTEQU <__imp_RemoveGadgetMessageHandler>
extern __imp_RemoveGadgetProperty:PANYARGS
RemoveGadgetProperty TEXTEQU <__imp_RemoveGadgetProperty>
extern __imp_SetActionTimeslice:PANYARGS
SetActionTimeslice TEXTEQU <__imp_SetActionTimeslice>
extern __imp_SetGadgetBufferInfo:PANYARGS
SetGadgetBufferInfo TEXTEQU <__imp_SetGadgetBufferInfo>
extern __imp_SetGadgetCenterPoint:PANYARGS
SetGadgetCenterPoint TEXTEQU <__imp_SetGadgetCenterPoint>
extern __imp_SetGadgetFillF:PANYARGS
SetGadgetFillF TEXTEQU <__imp_SetGadgetFillF>
extern __imp_SetGadgetFillI:PANYARGS
SetGadgetFillI TEXTEQU <__imp_SetGadgetFillI>
extern __imp_SetGadgetFocus:PANYARGS
SetGadgetFocus TEXTEQU <__imp_SetGadgetFocus>
extern __imp_SetGadgetMessageFilter:PANYARGS
SetGadgetMessageFilter TEXTEQU <__imp_SetGadgetMessageFilter>
extern __imp_SetGadgetOrder:PANYARGS
SetGadgetOrder TEXTEQU <__imp_SetGadgetOrder>
extern __imp_SetGadgetParent:PANYARGS
SetGadgetParent TEXTEQU <__imp_SetGadgetParent>
extern __imp_SetGadgetProperty:PANYARGS
SetGadgetProperty TEXTEQU <__imp_SetGadgetProperty>
extern __imp_SetGadgetRect:PANYARGS
SetGadgetRect TEXTEQU <__imp_SetGadgetRect>
extern __imp_SetGadgetRootInfo:PANYARGS
SetGadgetRootInfo TEXTEQU <__imp_SetGadgetRootInfo>
extern __imp_SetGadgetRotation:PANYARGS
SetGadgetRotation TEXTEQU <__imp_SetGadgetRotation>
extern __imp_SetGadgetScale:PANYARGS
SetGadgetScale TEXTEQU <__imp_SetGadgetScale>
extern __imp_SetGadgetStyle:PANYARGS
SetGadgetStyle TEXTEQU <__imp_SetGadgetStyle>
extern __imp_UninitGadgetComponent:PANYARGS
UninitGadgetComponent TEXTEQU <__imp_UninitGadgetComponent>
extern __imp_UnregisterGadgetMessage:PANYARGS
UnregisterGadgetMessage TEXTEQU <__imp_UnregisterGadgetMessage>
extern __imp_UnregisterGadgetMessageString:PANYARGS
UnregisterGadgetMessageString TEXTEQU <__imp_UnregisterGadgetMessageString>
extern __imp_UnregisterGadgetProperty:PANYARGS
UnregisterGadgetProperty TEXTEQU <__imp_UnregisterGadgetProperty>
extern __imp_UtilBuildFont:PANYARGS
UtilBuildFont TEXTEQU <__imp_UtilBuildFont>
extern __imp_UtilDrawBlendRect:PANYARGS
UtilDrawBlendRect TEXTEQU <__imp_UtilDrawBlendRect>
extern __imp_UtilGetColor:PANYARGS
UtilGetColor TEXTEQU <__imp_UtilGetColor>
extern __imp_UtilSetBackground:PANYARGS
UtilSetBackground TEXTEQU <__imp_UtilSetBackground>
extern __imp_WaitMessageEx:PANYARGS
WaitMessageEx TEXTEQU <__imp_WaitMessageEx>
