extern __imp_?DXConstOverArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z:PANYARGS
?DXConstOverArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z TEXTEQU <__imp_?DXConstOverArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z>
extern __imp_?DXConstUnderArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z:PANYARGS
?DXConstUnderArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z TEXTEQU <__imp_?DXConstUnderArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z>
extern __imp_?DXDitherArray@@YAXPEBUDXDITHERDESC@@@Z:PANYARGS
?DXDitherArray@@YAXPEBUDXDITHERDESC@@@Z TEXTEQU <__imp_?DXDitherArray@@YAXPEBUDXDITHERDESC@@@Z>
extern __imp_?DXLinearInterpolateArray@@YAXPEBVDXBASESAMPLE@@PEAUDXLIMAPINFO@@PEAV1@K@Z:PANYARGS
?DXLinearInterpolateArray@@YAXPEBVDXBASESAMPLE@@PEAUDXLIMAPINFO@@PEAV1@K@Z TEXTEQU <__imp_?DXLinearInterpolateArray@@YAXPEBVDXBASESAMPLE@@PEAUDXLIMAPINFO@@PEAV1@K@Z>
extern __imp_?DXOverArray@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z:PANYARGS
?DXOverArray@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z TEXTEQU <__imp_?DXOverArray@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z>
extern __imp_?DXOverArrayMMX@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z:PANYARGS
?DXOverArrayMMX@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z TEXTEQU <__imp_?DXOverArrayMMX@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllEnumClassObjects:PANYARGS
DllEnumClassObjects TEXTEQU <__imp_DllEnumClassObjects>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
