extern __imp_JetAddColumn:PANYARGS
JetAddColumn TEXTEQU <__imp_JetAddColumn>
extern __imp_JetAttachDatabase:PANYARGS
JetAttachDatabase TEXTEQU <__imp_JetAttachDatabase>
extern __imp_JetAttachDatabase2:PANYARGS
JetAttachDatabase2 TEXTEQU <__imp_JetAttachDatabase2>
extern __imp_JetAttachDatabaseWithStreaming:PANYARGS
JetAttachDatabaseWithStreaming TEXTEQU <__imp_JetAttachDatabaseWithStreaming>
extern __imp_JetBackup:PANYARGS
JetBackup TEXTEQU <__imp_JetBackup>
extern __imp_JetBackupInstance:PANYARGS
JetBackupInstance TEXTEQU <__imp_JetBackupInstance>
extern __imp_JetBeginExternalBackup:PANYARGS
JetBeginExternalBackup TEXTEQU <__imp_JetBeginExternalBackup>
extern __imp_JetBeginExternalBackupInstance:PANYARGS
JetBeginExternalBackupInstance TEXTEQU <__imp_JetBeginExternalBackupInstance>
extern __imp_JetBeginSession:PANYARGS
JetBeginSession TEXTEQU <__imp_JetBeginSession>
extern __imp_JetBeginTransaction:PANYARGS
JetBeginTransaction TEXTEQU <__imp_JetBeginTransaction>
extern __imp_JetBeginTransaction2:PANYARGS
JetBeginTransaction2 TEXTEQU <__imp_JetBeginTransaction2>
extern __imp_JetCloseDatabase:PANYARGS
JetCloseDatabase TEXTEQU <__imp_JetCloseDatabase>
extern __imp_JetCloseFile:PANYARGS
JetCloseFile TEXTEQU <__imp_JetCloseFile>
extern __imp_JetCloseFileInstance:PANYARGS
JetCloseFileInstance TEXTEQU <__imp_JetCloseFileInstance>
extern __imp_JetCloseTable:PANYARGS
JetCloseTable TEXTEQU <__imp_JetCloseTable>
extern __imp_JetCommitTransaction:PANYARGS
JetCommitTransaction TEXTEQU <__imp_JetCommitTransaction>
extern __imp_JetCompact:PANYARGS
JetCompact TEXTEQU <__imp_JetCompact>
extern __imp_JetComputeStats:PANYARGS
JetComputeStats TEXTEQU <__imp_JetComputeStats>
extern __imp_JetConvertDDL:PANYARGS
JetConvertDDL TEXTEQU <__imp_JetConvertDDL>
extern __imp_JetCreateDatabase:PANYARGS
JetCreateDatabase TEXTEQU <__imp_JetCreateDatabase>
extern __imp_JetCreateDatabase2:PANYARGS
JetCreateDatabase2 TEXTEQU <__imp_JetCreateDatabase2>
extern __imp_JetCreateDatabaseWithStreaming:PANYARGS
JetCreateDatabaseWithStreaming TEXTEQU <__imp_JetCreateDatabaseWithStreaming>
extern __imp_JetCreateIndex:PANYARGS
JetCreateIndex TEXTEQU <__imp_JetCreateIndex>
extern __imp_JetCreateIndex2:PANYARGS
JetCreateIndex2 TEXTEQU <__imp_JetCreateIndex2>
extern __imp_JetCreateInstance:PANYARGS
JetCreateInstance TEXTEQU <__imp_JetCreateInstance>
extern __imp_JetCreateInstance2:PANYARGS
JetCreateInstance2 TEXTEQU <__imp_JetCreateInstance2>
extern __imp_JetCreateTable:PANYARGS
JetCreateTable TEXTEQU <__imp_JetCreateTable>
extern __imp_JetCreateTableColumnIndex:PANYARGS
JetCreateTableColumnIndex TEXTEQU <__imp_JetCreateTableColumnIndex>
extern __imp_JetCreateTableColumnIndex2:PANYARGS
JetCreateTableColumnIndex2 TEXTEQU <__imp_JetCreateTableColumnIndex2>
extern __imp_JetDBUtilities:PANYARGS
JetDBUtilities TEXTEQU <__imp_JetDBUtilities>
extern __imp_JetDefragment:PANYARGS
JetDefragment TEXTEQU <__imp_JetDefragment>
extern __imp_JetDefragment2:PANYARGS
JetDefragment2 TEXTEQU <__imp_JetDefragment2>
extern __imp_JetDelete:PANYARGS
JetDelete TEXTEQU <__imp_JetDelete>
extern __imp_JetDeleteColumn:PANYARGS
JetDeleteColumn TEXTEQU <__imp_JetDeleteColumn>
extern __imp_JetDeleteColumn2:PANYARGS
JetDeleteColumn2 TEXTEQU <__imp_JetDeleteColumn2>
extern __imp_JetDeleteIndex:PANYARGS
JetDeleteIndex TEXTEQU <__imp_JetDeleteIndex>
extern __imp_JetDeleteTable:PANYARGS
JetDeleteTable TEXTEQU <__imp_JetDeleteTable>
extern __imp_JetDetachDatabase:PANYARGS
JetDetachDatabase TEXTEQU <__imp_JetDetachDatabase>
extern __imp_JetDetachDatabase2:PANYARGS
JetDetachDatabase2 TEXTEQU <__imp_JetDetachDatabase2>
extern __imp_JetDupCursor:PANYARGS
JetDupCursor TEXTEQU <__imp_JetDupCursor>
extern __imp_JetDupSession:PANYARGS
JetDupSession TEXTEQU <__imp_JetDupSession>
extern __imp_JetEnableMultiInstance:PANYARGS
JetEnableMultiInstance TEXTEQU <__imp_JetEnableMultiInstance>
extern __imp_JetEndExternalBackup:PANYARGS
JetEndExternalBackup TEXTEQU <__imp_JetEndExternalBackup>
extern __imp_JetEndExternalBackupInstance:PANYARGS
JetEndExternalBackupInstance TEXTEQU <__imp_JetEndExternalBackupInstance>
extern __imp_JetEndExternalBackupInstance2:PANYARGS
JetEndExternalBackupInstance2 TEXTEQU <__imp_JetEndExternalBackupInstance2>
extern __imp_JetEndSession:PANYARGS
JetEndSession TEXTEQU <__imp_JetEndSession>
extern __imp_JetEnumerateColumns:PANYARGS
JetEnumerateColumns TEXTEQU <__imp_JetEnumerateColumns>
extern __imp_JetEscrowUpdate:PANYARGS
JetEscrowUpdate TEXTEQU <__imp_JetEscrowUpdate>
extern __imp_JetExternalRestore:PANYARGS
JetExternalRestore TEXTEQU <__imp_JetExternalRestore>
extern __imp_JetExternalRestore2:PANYARGS
JetExternalRestore2 TEXTEQU <__imp_JetExternalRestore2>
extern __imp_JetFreeBuffer:PANYARGS
JetFreeBuffer TEXTEQU <__imp_JetFreeBuffer>
extern __imp_JetGetAttachInfo:PANYARGS
JetGetAttachInfo TEXTEQU <__imp_JetGetAttachInfo>
extern __imp_JetGetAttachInfoInstance:PANYARGS
JetGetAttachInfoInstance TEXTEQU <__imp_JetGetAttachInfoInstance>
extern __imp_JetGetBookmark:PANYARGS
JetGetBookmark TEXTEQU <__imp_JetGetBookmark>
extern __imp_JetGetColumnInfo:PANYARGS
JetGetColumnInfo TEXTEQU <__imp_JetGetColumnInfo>
extern __imp_JetGetCounter:PANYARGS
JetGetCounter TEXTEQU <__imp_JetGetCounter>
extern __imp_JetGetCurrentIndex:PANYARGS
JetGetCurrentIndex TEXTEQU <__imp_JetGetCurrentIndex>
extern __imp_JetGetCursorInfo:PANYARGS
JetGetCursorInfo TEXTEQU <__imp_JetGetCursorInfo>
extern __imp_JetGetDatabaseFileInfo:PANYARGS
JetGetDatabaseFileInfo TEXTEQU <__imp_JetGetDatabaseFileInfo>
extern __imp_JetGetDatabaseInfo:PANYARGS
JetGetDatabaseInfo TEXTEQU <__imp_JetGetDatabaseInfo>
extern __imp_JetGetIndexInfo:PANYARGS
JetGetIndexInfo TEXTEQU <__imp_JetGetIndexInfo>
extern __imp_JetGetInstanceInfo:PANYARGS
JetGetInstanceInfo TEXTEQU <__imp_JetGetInstanceInfo>
extern __imp_JetGetLS:PANYARGS
JetGetLS TEXTEQU <__imp_JetGetLS>
extern __imp_JetGetLock:PANYARGS
JetGetLock TEXTEQU <__imp_JetGetLock>
extern __imp_JetGetLogInfo:PANYARGS
JetGetLogInfo TEXTEQU <__imp_JetGetLogInfo>
extern __imp_JetGetLogInfoInstance:PANYARGS
JetGetLogInfoInstance TEXTEQU <__imp_JetGetLogInfoInstance>
extern __imp_JetGetLogInfoInstance2:PANYARGS
JetGetLogInfoInstance2 TEXTEQU <__imp_JetGetLogInfoInstance2>
extern __imp_JetGetObjectInfo:PANYARGS
JetGetObjectInfo TEXTEQU <__imp_JetGetObjectInfo>
extern __imp_JetGetRecordPosition:PANYARGS
JetGetRecordPosition TEXTEQU <__imp_JetGetRecordPosition>
extern __imp_JetGetSecondaryIndexBookmark:PANYARGS
JetGetSecondaryIndexBookmark TEXTEQU <__imp_JetGetSecondaryIndexBookmark>
extern __imp_JetGetSystemParameter:PANYARGS
JetGetSystemParameter TEXTEQU <__imp_JetGetSystemParameter>
extern __imp_JetGetTableColumnInfo:PANYARGS
JetGetTableColumnInfo TEXTEQU <__imp_JetGetTableColumnInfo>
extern __imp_JetGetTableIndexInfo:PANYARGS
JetGetTableIndexInfo TEXTEQU <__imp_JetGetTableIndexInfo>
extern __imp_JetGetTableInfo:PANYARGS
JetGetTableInfo TEXTEQU <__imp_JetGetTableInfo>
extern __imp_JetGetTruncateLogInfoInstance:PANYARGS
JetGetTruncateLogInfoInstance TEXTEQU <__imp_JetGetTruncateLogInfoInstance>
extern __imp_JetGetVersion:PANYARGS
JetGetVersion TEXTEQU <__imp_JetGetVersion>
extern __imp_JetGotoBookmark:PANYARGS
JetGotoBookmark TEXTEQU <__imp_JetGotoBookmark>
extern __imp_JetGotoPosition:PANYARGS
JetGotoPosition TEXTEQU <__imp_JetGotoPosition>
extern __imp_JetGotoSecondaryIndexBookmark:PANYARGS
JetGotoSecondaryIndexBookmark TEXTEQU <__imp_JetGotoSecondaryIndexBookmark>
extern __imp_JetGrowDatabase:PANYARGS
JetGrowDatabase TEXTEQU <__imp_JetGrowDatabase>
extern __imp_JetIdle:PANYARGS
JetIdle TEXTEQU <__imp_JetIdle>
extern __imp_JetIndexRecordCount:PANYARGS
JetIndexRecordCount TEXTEQU <__imp_JetIndexRecordCount>
extern __imp_JetInit:PANYARGS
JetInit TEXTEQU <__imp_JetInit>
extern __imp_JetInit2:PANYARGS
JetInit2 TEXTEQU <__imp_JetInit2>
extern __imp_JetInit3:PANYARGS
JetInit3 TEXTEQU <__imp_JetInit3>
extern __imp_JetIntersectIndexes:PANYARGS
JetIntersectIndexes TEXTEQU <__imp_JetIntersectIndexes>
extern __imp_JetMakeKey:PANYARGS
JetMakeKey TEXTEQU <__imp_JetMakeKey>
extern __imp_JetMove:PANYARGS
JetMove TEXTEQU <__imp_JetMove>
extern __imp_JetOSSnapshotAbort:PANYARGS
JetOSSnapshotAbort TEXTEQU <__imp_JetOSSnapshotAbort>
extern __imp_JetOSSnapshotFreeze:PANYARGS
JetOSSnapshotFreeze TEXTEQU <__imp_JetOSSnapshotFreeze>
extern __imp_JetOSSnapshotPrepare:PANYARGS
JetOSSnapshotPrepare TEXTEQU <__imp_JetOSSnapshotPrepare>
extern __imp_JetOSSnapshotThaw:PANYARGS
JetOSSnapshotThaw TEXTEQU <__imp_JetOSSnapshotThaw>
extern __imp_JetOpenDatabase:PANYARGS
JetOpenDatabase TEXTEQU <__imp_JetOpenDatabase>
extern __imp_JetOpenFile:PANYARGS
JetOpenFile TEXTEQU <__imp_JetOpenFile>
extern __imp_JetOpenFileInstance:PANYARGS
JetOpenFileInstance TEXTEQU <__imp_JetOpenFileInstance>
extern __imp_JetOpenFileSectionInstance:PANYARGS
JetOpenFileSectionInstance TEXTEQU <__imp_JetOpenFileSectionInstance>
extern __imp_JetOpenTable:PANYARGS
JetOpenTable TEXTEQU <__imp_JetOpenTable>
extern __imp_JetOpenTempTable:PANYARGS
JetOpenTempTable TEXTEQU <__imp_JetOpenTempTable>
extern __imp_JetOpenTempTable2:PANYARGS
JetOpenTempTable2 TEXTEQU <__imp_JetOpenTempTable2>
extern __imp_JetOpenTempTable3:PANYARGS
JetOpenTempTable3 TEXTEQU <__imp_JetOpenTempTable3>
extern __imp_JetPrepareToCommitTransaction:PANYARGS
JetPrepareToCommitTransaction TEXTEQU <__imp_JetPrepareToCommitTransaction>
extern __imp_JetPrepareUpdate:PANYARGS
JetPrepareUpdate TEXTEQU <__imp_JetPrepareUpdate>
extern __imp_JetReadFile:PANYARGS
JetReadFile TEXTEQU <__imp_JetReadFile>
extern __imp_JetReadFileInstance:PANYARGS
JetReadFileInstance TEXTEQU <__imp_JetReadFileInstance>
extern __imp_JetRegisterCallback:PANYARGS
JetRegisterCallback TEXTEQU <__imp_JetRegisterCallback>
extern __imp_JetRenameColumn:PANYARGS
JetRenameColumn TEXTEQU <__imp_JetRenameColumn>
extern __imp_JetRenameTable:PANYARGS
JetRenameTable TEXTEQU <__imp_JetRenameTable>
extern __imp_JetResetCounter:PANYARGS
JetResetCounter TEXTEQU <__imp_JetResetCounter>
extern __imp_JetResetSessionContext:PANYARGS
JetResetSessionContext TEXTEQU <__imp_JetResetSessionContext>
extern __imp_JetResetTableSequential:PANYARGS
JetResetTableSequential TEXTEQU <__imp_JetResetTableSequential>
extern __imp_JetRestore:PANYARGS
JetRestore TEXTEQU <__imp_JetRestore>
extern __imp_JetRestore2:PANYARGS
JetRestore2 TEXTEQU <__imp_JetRestore2>
extern __imp_JetRestoreInstance:PANYARGS
JetRestoreInstance TEXTEQU <__imp_JetRestoreInstance>
extern __imp_JetRetrieveColumn:PANYARGS
JetRetrieveColumn TEXTEQU <__imp_JetRetrieveColumn>
extern __imp_JetRetrieveColumns:PANYARGS
JetRetrieveColumns TEXTEQU <__imp_JetRetrieveColumns>
extern __imp_JetRetrieveKey:PANYARGS
JetRetrieveKey TEXTEQU <__imp_JetRetrieveKey>
extern __imp_JetRetrieveTaggedColumnList:PANYARGS
JetRetrieveTaggedColumnList TEXTEQU <__imp_JetRetrieveTaggedColumnList>
extern __imp_JetRollback:PANYARGS
JetRollback TEXTEQU <__imp_JetRollback>
extern __imp_JetSeek:PANYARGS
JetSeek TEXTEQU <__imp_JetSeek>
extern __imp_JetSetColumn:PANYARGS
JetSetColumn TEXTEQU <__imp_JetSetColumn>
extern __imp_JetSetColumnDefaultValue:PANYARGS
JetSetColumnDefaultValue TEXTEQU <__imp_JetSetColumnDefaultValue>
extern __imp_JetSetColumns:PANYARGS
JetSetColumns TEXTEQU <__imp_JetSetColumns>
extern __imp_JetSetCurrentIndex:PANYARGS
JetSetCurrentIndex TEXTEQU <__imp_JetSetCurrentIndex>
extern __imp_JetSetCurrentIndex2:PANYARGS
JetSetCurrentIndex2 TEXTEQU <__imp_JetSetCurrentIndex2>
extern __imp_JetSetCurrentIndex3:PANYARGS
JetSetCurrentIndex3 TEXTEQU <__imp_JetSetCurrentIndex3>
extern __imp_JetSetCurrentIndex4:PANYARGS
JetSetCurrentIndex4 TEXTEQU <__imp_JetSetCurrentIndex4>
extern __imp_JetSetDatabaseSize:PANYARGS
JetSetDatabaseSize TEXTEQU <__imp_JetSetDatabaseSize>
extern __imp_JetSetIndexRange:PANYARGS
JetSetIndexRange TEXTEQU <__imp_JetSetIndexRange>
extern __imp_JetSetLS:PANYARGS
JetSetLS TEXTEQU <__imp_JetSetLS>
extern __imp_JetSetSessionContext:PANYARGS
JetSetSessionContext TEXTEQU <__imp_JetSetSessionContext>
extern __imp_JetSetSystemParameter:PANYARGS
JetSetSystemParameter TEXTEQU <__imp_JetSetSystemParameter>
extern __imp_JetSetTableSequential:PANYARGS
JetSetTableSequential TEXTEQU <__imp_JetSetTableSequential>
extern __imp_JetSnapshotStart:PANYARGS
JetSnapshotStart TEXTEQU <__imp_JetSnapshotStart>
extern __imp_JetSnapshotStop:PANYARGS
JetSnapshotStop TEXTEQU <__imp_JetSnapshotStop>
extern __imp_JetStopBackup:PANYARGS
JetStopBackup TEXTEQU <__imp_JetStopBackup>
extern __imp_JetStopBackupInstance:PANYARGS
JetStopBackupInstance TEXTEQU <__imp_JetStopBackupInstance>
extern __imp_JetStopService:PANYARGS
JetStopService TEXTEQU <__imp_JetStopService>
extern __imp_JetStopServiceInstance:PANYARGS
JetStopServiceInstance TEXTEQU <__imp_JetStopServiceInstance>
extern __imp_JetTerm:PANYARGS
JetTerm TEXTEQU <__imp_JetTerm>
extern __imp_JetTerm2:PANYARGS
JetTerm2 TEXTEQU <__imp_JetTerm2>
extern __imp_JetTruncateLog:PANYARGS
JetTruncateLog TEXTEQU <__imp_JetTruncateLog>
extern __imp_JetTruncateLogInstance:PANYARGS
JetTruncateLogInstance TEXTEQU <__imp_JetTruncateLogInstance>
extern __imp_JetUnregisterCallback:PANYARGS
JetUnregisterCallback TEXTEQU <__imp_JetUnregisterCallback>
extern __imp_JetUpdate:PANYARGS
JetUpdate TEXTEQU <__imp_JetUpdate>
extern __imp_JetUpdate2:PANYARGS
JetUpdate2 TEXTEQU <__imp_JetUpdate2>
extern __imp_JetUpgradeDatabase:PANYARGS
JetUpgradeDatabase TEXTEQU <__imp_JetUpgradeDatabase>
extern __imp_ese:PANYARGS
ese TEXTEQU <__imp_ese>
extern __imp_esent:PANYARGS
esent TEXTEQU <__imp_esent>
