extern __imp_AddERExcludedApplicationA:PANYARGS
AddERExcludedApplication  TEXTEQU <__imp_AddERExcludedApplicationA>
extern __imp_AddERExcludedApplicationW:PANYARGS
AddERExcludedApplicationW TEXTEQU <__imp_AddERExcludedApplicationW>
extern __imp_CreateMinidumpW:PANYARGS
CreateMinidumpW TEXTEQU <__imp_CreateMinidumpW>
extern __imp_ReportEREvent:PANYARGS
ReportEREvent TEXTEQU <__imp_ReportEREvent>
extern __imp_ReportEREventDW:PANYARGS
ReportEREventDW TEXTEQU <__imp_ReportEREventDW>
extern __imp_ReportFault:PANYARGS
ReportFault TEXTEQU <__imp_ReportFault>
extern __imp_ReportFaultDWM:PANYARGS
ReportFaultDWM TEXTEQU <__imp_ReportFaultDWM>
extern __imp_ReportFaultFromQueue:PANYARGS
ReportFaultFromQueue TEXTEQU <__imp_ReportFaultFromQueue>
extern __imp_ReportFaultToQueue:PANYARGS
ReportFaultToQueue TEXTEQU <__imp_ReportFaultToQueue>
extern __imp_ReportHang:PANYARGS
ReportHang TEXTEQU <__imp_ReportHang>
extern __imp_ReportKernelFaultDWW:PANYARGS
ReportKernelFaultDWW TEXTEQU <__imp_ReportKernelFaultDWW>
