extern __imp_Chkdsk:PANYARGS
Chkdsk TEXTEQU <__imp_Chkdsk>
extern __imp_ChkdskEx:PANYARGS
ChkdskEx TEXTEQU <__imp_ChkdskEx>
extern __imp_ComputeFmMediaType:PANYARGS
ComputeFmMediaType TEXTEQU <__imp_ComputeFmMediaType>
extern __imp_DiskCopy:PANYARGS
DiskCopy TEXTEQU <__imp_DiskCopy>
extern __imp_EnableVolumeCompression:PANYARGS
EnableVolumeCompression TEXTEQU <__imp_EnableVolumeCompression>
extern __imp_Extend:PANYARGS
Extend TEXTEQU <__imp_Extend>
extern __imp_Format:PANYARGS
Format TEXTEQU <__imp_Format>
extern __imp_FormatEx:PANYARGS
FormatEx TEXTEQU <__imp_FormatEx>
extern __imp_FormatEx2:PANYARGS
FormatEx2 TEXTEQU <__imp_FormatEx2>
extern __imp_QueryAvailableFileSystemFormat:PANYARGS
QueryAvailableFileSystemFormat TEXTEQU <__imp_QueryAvailableFileSystemFormat>
extern __imp_QueryDeviceInformation:PANYARGS
QueryDeviceInformation TEXTEQU <__imp_QueryDeviceInformation>
extern __imp_QueryDeviceInformationByHandle:PANYARGS
QueryDeviceInformationByHandle TEXTEQU <__imp_QueryDeviceInformationByHandle>
extern __imp_QueryFileSystemName:PANYARGS
QueryFileSystemName TEXTEQU <__imp_QueryFileSystemName>
extern __imp_QueryLatestFileSystemVersion:PANYARGS
QueryLatestFileSystemVersion TEXTEQU <__imp_QueryLatestFileSystemVersion>
extern __imp_QuerySupportedMedia:PANYARGS
QuerySupportedMedia TEXTEQU <__imp_QuerySupportedMedia>
extern __imp_SetLabel:PANYARGS
SetLabel TEXTEQU <__imp_SetLabel>
