extern __imp___glsParser_create:PANYARGS
__glsParser_create TEXTEQU <__imp___glsParser_create>
extern __imp___glsParser_print:PANYARGS
__glsParser_print TEXTEQU <__imp___glsParser_print>
extern __imp___glsString_appendChar:PANYARGS
__glsString_appendChar TEXTEQU <__imp___glsString_appendChar>
extern __imp___glsString_assign:PANYARGS
__glsString_assign TEXTEQU <__imp___glsString_assign>
extern __imp___glsString_init:PANYARGS
__glsString_init TEXTEQU <__imp___glsString_init>
extern __imp_glsAbortCall:PANYARGS
glsAbortCall TEXTEQU <__imp_glsAbortCall>
extern __imp_glsAppRef:PANYARGS
glsAppRef TEXTEQU <__imp_glsAppRef>
extern __imp_glsBeginCapture:PANYARGS
glsBeginCapture TEXTEQU <__imp_glsBeginCapture>
extern __imp_glsBeginGLS:PANYARGS
glsBeginGLS TEXTEQU <__imp_glsBeginGLS>
extern __imp_glsBeginObj:PANYARGS
glsBeginObj TEXTEQU <__imp_glsBeginObj>
extern __imp_glsBinary:PANYARGS
glsBinary TEXTEQU <__imp_glsBinary>
extern __imp_glsBlock:PANYARGS
glsBlock TEXTEQU <__imp_glsBlock>
extern __imp_glsCallArray:PANYARGS
glsCallArray TEXTEQU <__imp_glsCallArray>
extern __imp_glsCallArrayInContext:PANYARGS
glsCallArrayInContext TEXTEQU <__imp_glsCallArrayInContext>
extern __imp_glsCallStream:PANYARGS
glsCallStream TEXTEQU <__imp_glsCallStream>
extern __imp_glsCaptureFlags:PANYARGS
glsCaptureFlags TEXTEQU <__imp_glsCaptureFlags>
extern __imp_glsCaptureFunc:PANYARGS
glsCaptureFunc TEXTEQU <__imp_glsCaptureFunc>
extern __imp_glsChannel:PANYARGS
glsChannel TEXTEQU <__imp_glsChannel>
extern __imp_glsCharubz:PANYARGS
glsCharubz TEXTEQU <__imp_glsCharubz>
extern __imp_glsCommandAPI:PANYARGS
glsCommandAPI TEXTEQU <__imp_glsCommandAPI>
extern __imp_glsCommandFunc:PANYARGS
glsCommandFunc TEXTEQU <__imp_glsCommandFunc>
extern __imp_glsCommandString:PANYARGS
glsCommandString TEXTEQU <__imp_glsCommandString>
extern __imp_glsComment:PANYARGS
glsComment TEXTEQU <__imp_glsComment>
extern __imp_glsContext:PANYARGS
glsContext TEXTEQU <__imp_glsContext>
extern __imp_glsCopyStream:PANYARGS
glsCopyStream TEXTEQU <__imp_glsCopyStream>
extern __imp_glsDataPointer:PANYARGS
glsDataPointer TEXTEQU <__imp_glsDataPointer>
extern __imp_glsDeleteContext:PANYARGS
glsDeleteContext TEXTEQU <__imp_glsDeleteContext>
extern __imp_glsDeleteReadPrefix:PANYARGS
glsDeleteReadPrefix TEXTEQU <__imp_glsDeleteReadPrefix>
extern __imp_glsDeleteStream:PANYARGS
glsDeleteStream TEXTEQU <__imp_glsDeleteStream>
extern __imp_glsDisplayMapfv:PANYARGS
glsDisplayMapfv TEXTEQU <__imp_glsDisplayMapfv>
extern __imp_glsEndCapture:PANYARGS
glsEndCapture TEXTEQU <__imp_glsEndCapture>
extern __imp_glsEndGLS:PANYARGS
glsEndGLS TEXTEQU <__imp_glsEndGLS>
extern __imp_glsEndObj:PANYARGS
glsEndObj TEXTEQU <__imp_glsEndObj>
extern __imp_glsEnumString:PANYARGS
glsEnumString TEXTEQU <__imp_glsEnumString>
extern __imp_glsError:PANYARGS
glsError TEXTEQU <__imp_glsError>
extern __imp_glsFlush:PANYARGS
glsFlush TEXTEQU <__imp_glsFlush>
extern __imp_glsGLRC:PANYARGS
glsGLRC TEXTEQU <__imp_glsGLRC>
extern __imp_glsGLRCLayer:PANYARGS
glsGLRCLayer TEXTEQU <__imp_glsGLRCLayer>
extern __imp_glsGenContext:PANYARGS
glsGenContext TEXTEQU <__imp_glsGenContext>
extern __imp_glsGetAllContexts:PANYARGS
glsGetAllContexts TEXTEQU <__imp_glsGetAllContexts>
extern __imp_glsGetCaptureDispatchTable:PANYARGS
glsGetCaptureDispatchTable TEXTEQU <__imp_glsGetCaptureDispatchTable>
extern __imp_glsGetCaptureExecTable:PANYARGS
glsGetCaptureExecTable TEXTEQU <__imp_glsGetCaptureExecTable>
extern __imp_glsGetCaptureFlags:PANYARGS
glsGetCaptureFlags TEXTEQU <__imp_glsGetCaptureFlags>
extern __imp_glsGetCommandAlignment:PANYARGS
glsGetCommandAlignment TEXTEQU <__imp_glsGetCommandAlignment>
extern __imp_glsGetCommandAttrib:PANYARGS
glsGetCommandAttrib TEXTEQU <__imp_glsGetCommandAttrib>
extern __imp_glsGetCommandFunc:PANYARGS
glsGetCommandFunc TEXTEQU <__imp_glsGetCommandFunc>
extern __imp_glsGetConsti:PANYARGS
glsGetConsti TEXTEQU <__imp_glsGetConsti>
extern __imp_glsGetConstiv:PANYARGS
glsGetConstiv TEXTEQU <__imp_glsGetConstiv>
extern __imp_glsGetConstubz:PANYARGS
glsGetConstubz TEXTEQU <__imp_glsGetConstubz>
extern __imp_glsGetContextFunc:PANYARGS
glsGetContextFunc TEXTEQU <__imp_glsGetContextFunc>
extern __imp_glsGetContextListl:PANYARGS
glsGetContextListl TEXTEQU <__imp_glsGetContextListl>
extern __imp_glsGetContextListubz:PANYARGS
glsGetContextListubz TEXTEQU <__imp_glsGetContextListubz>
extern __imp_glsGetContextPointer:PANYARGS
glsGetContextPointer TEXTEQU <__imp_glsGetContextPointer>
extern __imp_glsGetContexti:PANYARGS
glsGetContexti TEXTEQU <__imp_glsGetContexti>
extern __imp_glsGetContextubz:PANYARGS
glsGetContextubz TEXTEQU <__imp_glsGetContextubz>
extern __imp_glsGetCurrentContext:PANYARGS
glsGetCurrentContext TEXTEQU <__imp_glsGetCurrentContext>
extern __imp_glsGetCurrentTime:PANYARGS
glsGetCurrentTime TEXTEQU <__imp_glsGetCurrentTime>
extern __imp_glsGetError:PANYARGS
glsGetError TEXTEQU <__imp_glsGetError>
extern __imp_glsGetGLRCi:PANYARGS
glsGetGLRCi TEXTEQU <__imp_glsGetGLRCi>
extern __imp_glsGetHeaderf:PANYARGS
glsGetHeaderf TEXTEQU <__imp_glsGetHeaderf>
extern __imp_glsGetHeaderfv:PANYARGS
glsGetHeaderfv TEXTEQU <__imp_glsGetHeaderfv>
extern __imp_glsGetHeaderi:PANYARGS
glsGetHeaderi TEXTEQU <__imp_glsGetHeaderi>
extern __imp_glsGetHeaderiv:PANYARGS
glsGetHeaderiv TEXTEQU <__imp_glsGetHeaderiv>
extern __imp_glsGetHeaderubz:PANYARGS
glsGetHeaderubz TEXTEQU <__imp_glsGetHeaderubz>
extern __imp_glsGetLayerf:PANYARGS
glsGetLayerf TEXTEQU <__imp_glsGetLayerf>
extern __imp_glsGetLayeri:PANYARGS
glsGetLayeri TEXTEQU <__imp_glsGetLayeri>
extern __imp_glsGetOpcodeCount:PANYARGS
glsGetOpcodeCount TEXTEQU <__imp_glsGetOpcodeCount>
extern __imp_glsGetOpcodes:PANYARGS
glsGetOpcodes TEXTEQU <__imp_glsGetOpcodes>
extern __imp_glsGetStreamAttrib:PANYARGS
glsGetStreamAttrib TEXTEQU <__imp_glsGetStreamAttrib>
extern __imp_glsGetStreamCRC32:PANYARGS
glsGetStreamCRC32 TEXTEQU <__imp_glsGetStreamCRC32>
extern __imp_glsGetStreamReadName:PANYARGS
glsGetStreamReadName TEXTEQU <__imp_glsGetStreamReadName>
extern __imp_glsGetStreamSize:PANYARGS
glsGetStreamSize TEXTEQU <__imp_glsGetStreamSize>
extern __imp_glsGetStreamType:PANYARGS
glsGetStreamType TEXTEQU <__imp_glsGetStreamType>
extern __imp_glsHeaderGLRCi:PANYARGS
glsHeaderGLRCi TEXTEQU <__imp_glsHeaderGLRCi>
extern __imp_glsHeaderLayerf:PANYARGS
glsHeaderLayerf TEXTEQU <__imp_glsHeaderLayerf>
extern __imp_glsHeaderLayeri:PANYARGS
glsHeaderLayeri TEXTEQU <__imp_glsHeaderLayeri>
extern __imp_glsHeaderf:PANYARGS
glsHeaderf TEXTEQU <__imp_glsHeaderf>
extern __imp_glsHeaderfv:PANYARGS
glsHeaderfv TEXTEQU <__imp_glsHeaderfv>
extern __imp_glsHeaderi:PANYARGS
glsHeaderi TEXTEQU <__imp_glsHeaderi>
extern __imp_glsHeaderiv:PANYARGS
glsHeaderiv TEXTEQU <__imp_glsHeaderiv>
extern __imp_glsHeaderubz:PANYARGS
glsHeaderubz TEXTEQU <__imp_glsHeaderubz>
extern __imp_glsIsContext:PANYARGS
glsIsContext TEXTEQU <__imp_glsIsContext>
extern __imp_glsIsContextStream:PANYARGS
glsIsContextStream TEXTEQU <__imp_glsIsContextStream>
extern __imp_glsIsExtensionSupported:PANYARGS
glsIsExtensionSupported TEXTEQU <__imp_glsIsExtensionSupported>
extern __imp_glsIsUTF8String:PANYARGS
glsIsUTF8String TEXTEQU <__imp_glsIsUTF8String>
extern __imp_glsLong:PANYARGS
glsLong TEXTEQU <__imp_glsLong>
extern __imp_glsLongHigh:PANYARGS
glsLongHigh TEXTEQU <__imp_glsLongHigh>
extern __imp_glsLongLow:PANYARGS
glsLongLow TEXTEQU <__imp_glsLongLow>
extern __imp_glsNullCommandFunc:PANYARGS
glsNullCommandFunc TEXTEQU <__imp_glsNullCommandFunc>
extern __imp_glsNumb:PANYARGS
glsNumb TEXTEQU <__imp_glsNumb>
extern __imp_glsNumbv:PANYARGS
glsNumbv TEXTEQU <__imp_glsNumbv>
extern __imp_glsNumd:PANYARGS
glsNumd TEXTEQU <__imp_glsNumd>
extern __imp_glsNumdv:PANYARGS
glsNumdv TEXTEQU <__imp_glsNumdv>
extern __imp_glsNumf:PANYARGS
glsNumf TEXTEQU <__imp_glsNumf>
extern __imp_glsNumfv:PANYARGS
glsNumfv TEXTEQU <__imp_glsNumfv>
extern __imp_glsNumi:PANYARGS
glsNumi TEXTEQU <__imp_glsNumi>
extern __imp_glsNumiv:PANYARGS
glsNumiv TEXTEQU <__imp_glsNumiv>
extern __imp_glsNuml:PANYARGS
glsNuml TEXTEQU <__imp_glsNuml>
extern __imp_glsNumlv:PANYARGS
glsNumlv TEXTEQU <__imp_glsNumlv>
extern __imp_glsNums:PANYARGS
glsNums TEXTEQU <__imp_glsNums>
extern __imp_glsNumsv:PANYARGS
glsNumsv TEXTEQU <__imp_glsNumsv>
extern __imp_glsNumub:PANYARGS
glsNumub TEXTEQU <__imp_glsNumub>
extern __imp_glsNumubv:PANYARGS
glsNumubv TEXTEQU <__imp_glsNumubv>
extern __imp_glsNumui:PANYARGS
glsNumui TEXTEQU <__imp_glsNumui>
extern __imp_glsNumuiv:PANYARGS
glsNumuiv TEXTEQU <__imp_glsNumuiv>
extern __imp_glsNumul:PANYARGS
glsNumul TEXTEQU <__imp_glsNumul>
extern __imp_glsNumulv:PANYARGS
glsNumulv TEXTEQU <__imp_glsNumulv>
extern __imp_glsNumus:PANYARGS
glsNumus TEXTEQU <__imp_glsNumus>
extern __imp_glsNumusv:PANYARGS
glsNumusv TEXTEQU <__imp_glsNumusv>
extern __imp_glsPad:PANYARGS
glsPad TEXTEQU <__imp_glsPad>
extern __imp_glsPixelSetup:PANYARGS
glsPixelSetup TEXTEQU <__imp_glsPixelSetup>
extern __imp_glsPixelSetupGen:PANYARGS
glsPixelSetupGen TEXTEQU <__imp_glsPixelSetupGen>
extern __imp_glsReadFunc:PANYARGS
glsReadFunc TEXTEQU <__imp_glsReadFunc>
extern __imp_glsReadPrefix:PANYARGS
glsReadPrefix TEXTEQU <__imp_glsReadPrefix>
extern __imp_glsRequireExtension:PANYARGS
glsRequireExtension TEXTEQU <__imp_glsRequireExtension>
extern __imp_glsSwapBuffers:PANYARGS
glsSwapBuffers TEXTEQU <__imp_glsSwapBuffers>
extern __imp_glsUCS1toUTF8z:PANYARGS
glsUCS1toUTF8z TEXTEQU <__imp_glsUCS1toUTF8z>
extern __imp_glsUCS2toUTF8z:PANYARGS
glsUCS2toUTF8z TEXTEQU <__imp_glsUCS2toUTF8z>
extern __imp_glsUCS4toUTF8:PANYARGS
glsUCS4toUTF8 TEXTEQU <__imp_glsUCS4toUTF8>
extern __imp_glsUCS4toUTF8z:PANYARGS
glsUCS4toUTF8z TEXTEQU <__imp_glsUCS4toUTF8z>
extern __imp_glsUCStoUTF8z:PANYARGS
glsUCStoUTF8z TEXTEQU <__imp_glsUCStoUTF8z>
extern __imp_glsULong:PANYARGS
glsULong TEXTEQU <__imp_glsULong>
extern __imp_glsULongHigh:PANYARGS
glsULongHigh TEXTEQU <__imp_glsULongHigh>
extern __imp_glsULongLow:PANYARGS
glsULongLow TEXTEQU <__imp_glsULongLow>
extern __imp_glsUTF8toUCS1z:PANYARGS
glsUTF8toUCS1z TEXTEQU <__imp_glsUTF8toUCS1z>
extern __imp_glsUTF8toUCS2z:PANYARGS
glsUTF8toUCS2z TEXTEQU <__imp_glsUTF8toUCS2z>
extern __imp_glsUTF8toUCS4:PANYARGS
glsUTF8toUCS4 TEXTEQU <__imp_glsUTF8toUCS4>
extern __imp_glsUTF8toUCS4z:PANYARGS
glsUTF8toUCS4z TEXTEQU <__imp_glsUTF8toUCS4z>
extern __imp_glsUTF8toUCSz:PANYARGS
glsUTF8toUCSz TEXTEQU <__imp_glsUTF8toUCSz>
extern __imp_glsUnreadFunc:PANYARGS
glsUnreadFunc TEXTEQU <__imp_glsUnreadFunc>
extern __imp_glsUnsupportedCommand:PANYARGS
glsUnsupportedCommand TEXTEQU <__imp_glsUnsupportedCommand>
extern __imp_glsUpdateCaptureExecTable:PANYARGS
glsUpdateCaptureExecTable TEXTEQU <__imp_glsUpdateCaptureExecTable>
extern __imp_glsWriteFunc:PANYARGS
glsWriteFunc TEXTEQU <__imp_glsWriteFunc>
extern __imp_glsWritePrefix:PANYARGS
glsWritePrefix TEXTEQU <__imp_glsWritePrefix>
