extern __imp_gluBeginCurve:PANYARGS
gluBeginCurve TEXTEQU <__imp_gluBeginCurve>
extern __imp_gluBeginPolygon:PANYARGS
gluBeginPolygon TEXTEQU <__imp_gluBeginPolygon>
extern __imp_gluBeginSurface:PANYARGS
gluBeginSurface TEXTEQU <__imp_gluBeginSurface>
extern __imp_gluBeginTrim:PANYARGS
gluBeginTrim TEXTEQU <__imp_gluBeginTrim>
extern __imp_gluBuild1DMipmaps:PANYARGS
gluBuild1DMipmaps TEXTEQU <__imp_gluBuild1DMipmaps>
extern __imp_gluBuild2DMipmaps:PANYARGS
gluBuild2DMipmaps TEXTEQU <__imp_gluBuild2DMipmaps>
extern __imp_gluCylinder:PANYARGS
gluCylinder TEXTEQU <__imp_gluCylinder>
extern __imp_gluDeleteNurbsRenderer:PANYARGS
gluDeleteNurbsRenderer TEXTEQU <__imp_gluDeleteNurbsRenderer>
extern __imp_gluDeleteQuadric:PANYARGS
gluDeleteQuadric TEXTEQU <__imp_gluDeleteQuadric>
extern __imp_gluDeleteTess:PANYARGS
gluDeleteTess TEXTEQU <__imp_gluDeleteTess>
extern __imp_gluDisk:PANYARGS
gluDisk TEXTEQU <__imp_gluDisk>
extern __imp_gluEndCurve:PANYARGS
gluEndCurve TEXTEQU <__imp_gluEndCurve>
extern __imp_gluEndPolygon:PANYARGS
gluEndPolygon TEXTEQU <__imp_gluEndPolygon>
extern __imp_gluEndSurface:PANYARGS
gluEndSurface TEXTEQU <__imp_gluEndSurface>
extern __imp_gluEndTrim:PANYARGS
gluEndTrim TEXTEQU <__imp_gluEndTrim>
extern __imp_gluErrorString:PANYARGS
gluErrorString TEXTEQU <__imp_gluErrorString>
extern __imp_gluErrorUnicodeStringEXT:PANYARGS
gluErrorUnicodeStringEXT TEXTEQU <__imp_gluErrorUnicodeStringEXT>
extern __imp_gluGetNurbsProperty:PANYARGS
gluGetNurbsProperty TEXTEQU <__imp_gluGetNurbsProperty>
extern __imp_gluGetString:PANYARGS
gluGetString TEXTEQU <__imp_gluGetString>
extern __imp_gluGetTessProperty:PANYARGS
gluGetTessProperty TEXTEQU <__imp_gluGetTessProperty>
extern __imp_gluLoadSamplingMatrices:PANYARGS
gluLoadSamplingMatrices TEXTEQU <__imp_gluLoadSamplingMatrices>
extern __imp_gluLookAt:PANYARGS
gluLookAt TEXTEQU <__imp_gluLookAt>
extern __imp_gluNewNurbsRenderer:PANYARGS
gluNewNurbsRenderer TEXTEQU <__imp_gluNewNurbsRenderer>
extern __imp_gluNewQuadric:PANYARGS
gluNewQuadric TEXTEQU <__imp_gluNewQuadric>
extern __imp_gluNewTess:PANYARGS
gluNewTess TEXTEQU <__imp_gluNewTess>
extern __imp_gluNextContour:PANYARGS
gluNextContour TEXTEQU <__imp_gluNextContour>
extern __imp_gluNurbsCallback:PANYARGS
gluNurbsCallback TEXTEQU <__imp_gluNurbsCallback>
extern __imp_gluNurbsCurve:PANYARGS
gluNurbsCurve TEXTEQU <__imp_gluNurbsCurve>
extern __imp_gluNurbsProperty:PANYARGS
gluNurbsProperty TEXTEQU <__imp_gluNurbsProperty>
extern __imp_gluNurbsSurface:PANYARGS
gluNurbsSurface TEXTEQU <__imp_gluNurbsSurface>
extern __imp_gluOrtho2D:PANYARGS
gluOrtho2D TEXTEQU <__imp_gluOrtho2D>
extern __imp_gluPartialDisk:PANYARGS
gluPartialDisk TEXTEQU <__imp_gluPartialDisk>
extern __imp_gluPerspective:PANYARGS
gluPerspective TEXTEQU <__imp_gluPerspective>
extern __imp_gluPickMatrix:PANYARGS
gluPickMatrix TEXTEQU <__imp_gluPickMatrix>
extern __imp_gluProject:PANYARGS
gluProject TEXTEQU <__imp_gluProject>
extern __imp_gluPwlCurve:PANYARGS
gluPwlCurve TEXTEQU <__imp_gluPwlCurve>
extern __imp_gluQuadricCallback:PANYARGS
gluQuadricCallback TEXTEQU <__imp_gluQuadricCallback>
extern __imp_gluQuadricDrawStyle:PANYARGS
gluQuadricDrawStyle TEXTEQU <__imp_gluQuadricDrawStyle>
extern __imp_gluQuadricNormals:PANYARGS
gluQuadricNormals TEXTEQU <__imp_gluQuadricNormals>
extern __imp_gluQuadricOrientation:PANYARGS
gluQuadricOrientation TEXTEQU <__imp_gluQuadricOrientation>
extern __imp_gluQuadricTexture:PANYARGS
gluQuadricTexture TEXTEQU <__imp_gluQuadricTexture>
extern __imp_gluScaleImage:PANYARGS
gluScaleImage TEXTEQU <__imp_gluScaleImage>
extern __imp_gluSphere:PANYARGS
gluSphere TEXTEQU <__imp_gluSphere>
extern __imp_gluTessBeginContour:PANYARGS
gluTessBeginContour TEXTEQU <__imp_gluTessBeginContour>
extern __imp_gluTessBeginPolygon:PANYARGS
gluTessBeginPolygon TEXTEQU <__imp_gluTessBeginPolygon>
extern __imp_gluTessCallback:PANYARGS
gluTessCallback TEXTEQU <__imp_gluTessCallback>
extern __imp_gluTessEndContour:PANYARGS
gluTessEndContour TEXTEQU <__imp_gluTessEndContour>
extern __imp_gluTessEndPolygon:PANYARGS
gluTessEndPolygon TEXTEQU <__imp_gluTessEndPolygon>
extern __imp_gluTessNormal:PANYARGS
gluTessNormal TEXTEQU <__imp_gluTessNormal>
extern __imp_gluTessProperty:PANYARGS
gluTessProperty TEXTEQU <__imp_gluTessProperty>
extern __imp_gluTessVertex:PANYARGS
gluTessVertex TEXTEQU <__imp_gluTessVertex>
extern __imp_gluUnProject:PANYARGS
gluUnProject TEXTEQU <__imp_gluUnProject>
