extern __imp_gpedit_ordinal100:PANYARGS
gpedit_ordinal100 TEXTEQU <__imp_gpedit_ordinal100>
extern __imp_gpedit_ordinal101:PANYARGS
gpedit_ordinal101 TEXTEQU <__imp_gpedit_ordinal101>
extern __imp_gpedit_ordinal102:PANYARGS
gpedit_ordinal102 TEXTEQU <__imp_gpedit_ordinal102>
extern __imp_gpedit_ordinal103:PANYARGS
gpedit_ordinal103 TEXTEQU <__imp_gpedit_ordinal103>
extern __imp_gpedit_ordinal104:PANYARGS
gpedit_ordinal104 TEXTEQU <__imp_gpedit_ordinal104>
extern __imp_BrowseForGPO:PANYARGS
BrowseForGPO TEXTEQU <__imp_BrowseForGPO>
extern __imp_CreateGPOLink:PANYARGS
CreateGPOLink TEXTEQU <__imp_CreateGPOLink>
extern __imp_DeleteAllGPOLinks:PANYARGS
DeleteAllGPOLinks TEXTEQU <__imp_DeleteAllGPOLinks>
extern __imp_DeleteGPOLink:PANYARGS
DeleteGPOLink TEXTEQU <__imp_DeleteGPOLink>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_ExportRSoPData:PANYARGS
ExportRSoPData TEXTEQU <__imp_ExportRSoPData>
extern __imp_ImportRSoPData:PANYARGS
ImportRSoPData TEXTEQU <__imp_ImportRSoPData>
