extern __imp_CPAcquireContext:PANYARGS
CPAcquireContext TEXTEQU <__imp_CPAcquireContext>
extern __imp_CPCreateHash:PANYARGS
CPCreateHash TEXTEQU <__imp_CPCreateHash>
extern __imp_CPDecrypt:PANYARGS
CPDecrypt TEXTEQU <__imp_CPDecrypt>
extern __imp_CPDeriveKey:PANYARGS
CPDeriveKey TEXTEQU <__imp_CPDeriveKey>
extern __imp_CPDestroyHash:PANYARGS
CPDestroyHash TEXTEQU <__imp_CPDestroyHash>
extern __imp_CPDestroyKey:PANYARGS
CPDestroyKey TEXTEQU <__imp_CPDestroyKey>
extern __imp_CPEncrypt:PANYARGS
CPEncrypt TEXTEQU <__imp_CPEncrypt>
extern __imp_CPExportKey:PANYARGS
CPExportKey TEXTEQU <__imp_CPExportKey>
extern __imp_CPGenKey:PANYARGS
CPGenKey TEXTEQU <__imp_CPGenKey>
extern __imp_CPGenRandom:PANYARGS
CPGenRandom TEXTEQU <__imp_CPGenRandom>
extern __imp_CPGetHashParam:PANYARGS
CPGetHashParam TEXTEQU <__imp_CPGetHashParam>
extern __imp_CPGetKeyParam:PANYARGS
CPGetKeyParam TEXTEQU <__imp_CPGetKeyParam>
extern __imp_CPGetProvParam:PANYARGS
CPGetProvParam TEXTEQU <__imp_CPGetProvParam>
extern __imp_CPGetUserKey:PANYARGS
CPGetUserKey TEXTEQU <__imp_CPGetUserKey>
extern __imp_CPHashData:PANYARGS
CPHashData TEXTEQU <__imp_CPHashData>
extern __imp_CPHashSessionKey:PANYARGS
CPHashSessionKey TEXTEQU <__imp_CPHashSessionKey>
extern __imp_CPImportKey:PANYARGS
CPImportKey TEXTEQU <__imp_CPImportKey>
extern __imp_CPReleaseContext:PANYARGS
CPReleaseContext TEXTEQU <__imp_CPReleaseContext>
extern __imp_CPSetHashParam:PANYARGS
CPSetHashParam TEXTEQU <__imp_CPSetHashParam>
extern __imp_CPSetKeyParam:PANYARGS
CPSetKeyParam TEXTEQU <__imp_CPSetKeyParam>
extern __imp_CPSetProvParam:PANYARGS
CPSetProvParam TEXTEQU <__imp_CPSetProvParam>
extern __imp_CPSignHash:PANYARGS
CPSignHash TEXTEQU <__imp_CPSignHash>
extern __imp_CPVerifySignature:PANYARGS
CPVerifySignature TEXTEQU <__imp_CPVerifySignature>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
