extern __imp_??0CCollection@@QEAA@XZ:PANYARGS
??0CCollection@@QEAA@XZ TEXTEQU <__imp_??0CCollection@@QEAA@XZ>
extern __imp_??0CFIFOString@@QEAA@XZ:PANYARGS
??0CFIFOString@@QEAA@XZ TEXTEQU <__imp_??0CFIFOString@@QEAA@XZ>
extern __imp_??0CFolder@@QEAA@XZ:PANYARGS
??0CFolder@@QEAA@XZ TEXTEQU <__imp_??0CFolder@@QEAA@XZ>
extern __imp_??0CLocation@@QEAA@XZ:PANYARGS
??0CLocation@@QEAA@XZ TEXTEQU <__imp_??0CLocation@@QEAA@XZ>
extern __imp_??0CPointerList@@QEAA@XZ:PANYARGS
??0CPointerList@@QEAA@XZ TEXTEQU <__imp_??0CPointerList@@QEAA@XZ>
extern __imp_??0CTitle@@QEAA@XZ:PANYARGS
??0CTitle@@QEAA@XZ TEXTEQU <__imp_??0CTitle@@QEAA@XZ>
extern __imp_??1CCollection@@QEAA@XZ:PANYARGS
??1CCollection@@QEAA@XZ TEXTEQU <__imp_??1CCollection@@QEAA@XZ>
extern __imp_??1CFIFOString@@QEAA@XZ:PANYARGS
??1CFIFOString@@QEAA@XZ TEXTEQU <__imp_??1CFIFOString@@QEAA@XZ>
extern __imp_??1CFolder@@QEAA@XZ:PANYARGS
??1CFolder@@QEAA@XZ TEXTEQU <__imp_??1CFolder@@QEAA@XZ>
extern __imp_??1CLocation@@QEAA@XZ:PANYARGS
??1CLocation@@QEAA@XZ TEXTEQU <__imp_??1CLocation@@QEAA@XZ>
extern __imp_??1CPointerList@@QEAA@XZ:PANYARGS
??1CPointerList@@QEAA@XZ TEXTEQU <__imp_??1CPointerList@@QEAA@XZ>
extern __imp_??1CTitle@@QEAA@XZ:PANYARGS
??1CTitle@@QEAA@XZ TEXTEQU <__imp_??1CTitle@@QEAA@XZ>
extern __imp_??4CCollection@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CCollection@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CCollection@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CFIFOString@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CFIFOString@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CFIFOString@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CFolder@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CFolder@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CFolder@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CLocation@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CLocation@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CLocation@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CPointerList@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CPointerList@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CPointerList@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CTitle@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CTitle@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CTitle@@QEAAAEAV0@AEBV0@@Z>
extern __imp_?Add@CPointerList@@QEAAPEAUListItem@@PEAX@Z:PANYARGS
?Add@CPointerList@@QEAAPEAUListItem@@PEAX@Z TEXTEQU <__imp_?Add@CPointerList@@QEAAPEAUListItem@@PEAX@Z>
extern __imp_?AddChildFolder@CFolder@@QEAAKPEAV1@@Z:PANYARGS
?AddChildFolder@CFolder@@QEAAKPEAV1@@Z TEXTEQU <__imp_?AddChildFolder@CFolder@@QEAAKPEAV1@@Z>
extern __imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBDKPEAKG@Z:PANYARGS
?AddChildFolder@CFolder@@QEAAPEAV1@PEBDKPEAKG@Z TEXTEQU <__imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBDKPEAKG@Z>
extern __imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBGKPEAKG@Z:PANYARGS
?AddChildFolder@CFolder@@QEAAPEAV1@PEBGKPEAKG@Z TEXTEQU <__imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBGKPEAKG@Z>
extern __imp_?AddCollection@CCollection@@QEAAPEAVCColList@@XZ:PANYARGS
?AddCollection@CCollection@@QEAAPEAVCColList@@XZ TEXTEQU <__imp_?AddCollection@CCollection@@QEAAPEAVCColList@@XZ>
extern __imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBDKPEAKG@Z:PANYARGS
?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBDKPEAKG@Z TEXTEQU <__imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBDKPEAKG@Z>
extern __imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBGKPEAKG@Z:PANYARGS
?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBGKPEAKG@Z TEXTEQU <__imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBGKPEAKG@Z>
extern __imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBD000PEAK@Z:PANYARGS
?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBD000PEAK@Z TEXTEQU <__imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBD000PEAK@Z>
extern __imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBG000PEAK@Z:PANYARGS
?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBG000PEAK@Z TEXTEQU <__imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBG000PEAK@Z>
extern __imp_?AddLocationHistory@CTitle@@QEAAKKPEBD00PEBVCLocation@@00H@Z:PANYARGS
?AddLocationHistory@CTitle@@QEAAKKPEBD00PEBVCLocation@@00H@Z TEXTEQU <__imp_?AddLocationHistory@CTitle@@QEAAKKPEBD00PEBVCLocation@@00H@Z>
extern __imp_?AddLocationHistory@CTitle@@QEAAKKPEBG00PEBVCLocation@@00H@Z:PANYARGS
?AddLocationHistory@CTitle@@QEAAKKPEBG00PEBVCLocation@@00H@Z TEXTEQU <__imp_?AddLocationHistory@CTitle@@QEAAKKPEBG00PEBVCLocation@@00H@Z>
extern __imp_?AddRef@CCollection@@QEAAXXZ:PANYARGS
?AddRef@CCollection@@QEAAXXZ TEXTEQU <__imp_?AddRef@CCollection@@QEAAXXZ>
extern __imp_?AddRefedTitle@CCollection@@AEAAKPEAVCFolder@@@Z:PANYARGS
?AddRefedTitle@CCollection@@AEAAKPEAVCFolder@@@Z TEXTEQU <__imp_?AddRefedTitle@CCollection@@AEAAKPEAVCFolder@@@Z>
extern __imp_?AddTail@CFIFOString@@QEAAKPEAD@Z:PANYARGS
?AddTail@CFIFOString@@QEAAKPEAD@Z TEXTEQU <__imp_?AddTail@CFIFOString@@QEAAKPEAD@Z>
extern __imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBD0000GIPEAVCLocation@@PEAKH0@Z:PANYARGS
?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBD0000GIPEAVCLocation@@PEAKH0@Z TEXTEQU <__imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBD0000GIPEAVCLocation@@PEAKH0@Z>
extern __imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBG0000GIPEAVCLocation@@PEAKH0@Z:PANYARGS
?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBG0000GIPEAVCLocation@@PEAKH0@Z TEXTEQU <__imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBG0000GIPEAVCLocation@@PEAKH0@Z>
extern __imp_?AllocCopyValue@CCollection@@AEAAKPEAVCParseXML@@PEADPEAPEAD@Z:PANYARGS
?AllocCopyValue@CCollection@@AEAAKPEAVCParseXML@@PEADPEAPEAD@Z TEXTEQU <__imp_?AllocCopyValue@CCollection@@AEAAKPEAVCParseXML@@PEADPEAPEAD@Z>
extern __imp_?AllocSetValue@@YAKPEBDPEAPEAD@Z:PANYARGS
?AllocSetValue@@YAKPEBDPEAPEAD@Z TEXTEQU <__imp_?AllocSetValue@@YAKPEBDPEAPEAD@Z>
extern __imp_?CheckTitleRef@CCollection@@AEAAKPEBDG@Z:PANYARGS
?CheckTitleRef@CCollection@@AEAAKPEBDG@Z TEXTEQU <__imp_?CheckTitleRef@CCollection@@AEAAKPEBDG@Z>
extern __imp_?CheckTitleRef@CCollection@@AEAAKPEBGG@Z:PANYARGS
?CheckTitleRef@CCollection@@AEAAKPEBGG@Z TEXTEQU <__imp_?CheckTitleRef@CCollection@@AEAAKPEBGG@Z>
extern __imp_?Close@CCollection@@QEAAKXZ:PANYARGS
?Close@CCollection@@QEAAKXZ TEXTEQU <__imp_?Close@CCollection@@QEAAKXZ>
extern __imp_?ConfirmTitles@CCollection@@QEAAXXZ:PANYARGS
?ConfirmTitles@CCollection@@QEAAXXZ TEXTEQU <__imp_?ConfirmTitles@CCollection@@QEAAXXZ>
extern __imp_?DecrementRefTitleCount@CCollection@@QEAAXXZ:PANYARGS
?DecrementRefTitleCount@CCollection@@QEAAXXZ TEXTEQU <__imp_?DecrementRefTitleCount@CCollection@@QEAAXXZ>
extern __imp_?DeleteChildren@CCollection@@AEAAXPEAPEAVCFolder@@@Z:PANYARGS
?DeleteChildren@CCollection@@AEAAXPEAPEAVCFolder@@@Z TEXTEQU <__imp_?DeleteChildren@CCollection@@AEAAXPEAPEAVCFolder@@@Z>
extern __imp_?DeleteFolder@CCollection@@QEAAKPEAVCFolder@@@Z:PANYARGS
?DeleteFolder@CCollection@@QEAAKPEAVCFolder@@@Z TEXTEQU <__imp_?DeleteFolder@CCollection@@QEAAKPEAVCFolder@@@Z>
extern __imp_?DeleteFolders@CCollection@@AEAAXPEAPEAVCFolder@@@Z:PANYARGS
?DeleteFolders@CCollection@@AEAAXPEAPEAVCFolder@@@Z TEXTEQU <__imp_?DeleteFolders@CCollection@@AEAAXPEAPEAVCFolder@@@Z>
extern __imp_?DeleteLocalFiles@CCollection@@AEAAXPEAULocationHistory@@PEAVCTitle@@@Z:PANYARGS
?DeleteLocalFiles@CCollection@@AEAAXPEAULocationHistory@@PEAVCTitle@@@Z TEXTEQU <__imp_?DeleteLocalFiles@CCollection@@AEAAXPEAULocationHistory@@PEAVCTitle@@@Z>
extern __imp_?DeleteLocation@CCollection@@AEAAKPEAVCLocation@@@Z:PANYARGS
?DeleteLocation@CCollection@@AEAAKPEAVCLocation@@@Z TEXTEQU <__imp_?DeleteLocation@CCollection@@AEAAKPEAVCLocation@@@Z>
extern __imp_?DeleteTitle@CCollection@@AEAAKPEAVCTitle@@@Z:PANYARGS
?DeleteTitle@CCollection@@AEAAKPEAVCTitle@@@Z TEXTEQU <__imp_?DeleteTitle@CCollection@@AEAAKPEAVCTitle@@@Z>
extern __imp_?Dirty@CCollection@@QEAAXXZ:PANYARGS
?Dirty@CCollection@@QEAAXXZ TEXTEQU <__imp_?Dirty@CCollection@@QEAAXXZ>
extern __imp_?FindCollection@CCollection@@QEAAPEAVCColList@@PEAD@Z:PANYARGS
?FindCollection@CCollection@@QEAAPEAVCColList@@PEAD@Z TEXTEQU <__imp_?FindCollection@CCollection@@QEAAPEAVCColList@@PEAD@Z>
extern __imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBDPEAI@Z:PANYARGS
?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBDPEAI@Z TEXTEQU <__imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBDPEAI@Z>
extern __imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBGPEAI@Z:PANYARGS
?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBGPEAI@Z TEXTEQU <__imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBGPEAI@Z>
extern __imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBDG@Z:PANYARGS
?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBDG@Z TEXTEQU <__imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBDG@Z>
extern __imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBGG@Z:PANYARGS
?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBGG@Z TEXTEQU <__imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBGG@Z>
extern __imp_?First@CPointerList@@QEAAPEAUListItem@@XZ:PANYARGS
?First@CPointerList@@QEAAPEAUListItem@@XZ TEXTEQU <__imp_?First@CPointerList@@QEAAPEAUListItem@@XZ>
extern __imp_?FirstLocation@CCollection@@QEAAPEAVCLocation@@XZ:PANYARGS
?FirstLocation@CCollection@@QEAAPEAVCLocation@@XZ TEXTEQU <__imp_?FirstLocation@CCollection@@QEAAPEAVCLocation@@XZ>
extern __imp_?GetColNo@CCollection@@QEAAKXZ:PANYARGS
?GetColNo@CCollection@@QEAAKXZ TEXTEQU <__imp_?GetColNo@CCollection@@QEAAKXZ>
extern __imp_?GetCollectionFileName@CCollection@@QEAAPEBDXZ:PANYARGS
?GetCollectionFileName@CCollection@@QEAAPEBDXZ TEXTEQU <__imp_?GetCollectionFileName@CCollection@@QEAAPEBDXZ>
extern __imp_?GetCollectionFileNameW@CCollection@@QEAAPEBGXZ:PANYARGS
?GetCollectionFileNameW@CCollection@@QEAAPEBGXZ TEXTEQU <__imp_?GetCollectionFileNameW@CCollection@@QEAAPEBGXZ>
extern __imp_?GetFindMergedCHMS@CCollection@@QEAAHXZ:PANYARGS
?GetFindMergedCHMS@CCollection@@QEAAHXZ TEXTEQU <__imp_?GetFindMergedCHMS@CCollection@@QEAAHXZ>
extern __imp_?GetFirstChildFolder@CFolder@@QEAAPEAV1@XZ:PANYARGS
?GetFirstChildFolder@CFolder@@QEAAPEAV1@XZ TEXTEQU <__imp_?GetFirstChildFolder@CFolder@@QEAAPEAV1@XZ>
extern __imp_?GetFirstTitle@CCollection@@QEAAPEAVCTitle@@XZ:PANYARGS
?GetFirstTitle@CCollection@@QEAAPEAVCTitle@@XZ TEXTEQU <__imp_?GetFirstTitle@CCollection@@QEAAPEAVCTitle@@XZ>
extern __imp_?GetId@CLocation@@QEBAPEADXZ:PANYARGS
?GetId@CLocation@@QEBAPEADXZ TEXTEQU <__imp_?GetId@CLocation@@QEBAPEADXZ>
extern __imp_?GetId@CTitle@@QEAAPEADXZ:PANYARGS
?GetId@CTitle@@QEAAPEADXZ TEXTEQU <__imp_?GetId@CTitle@@QEAAPEADXZ>
extern __imp_?GetIdW@CLocation@@QEAAPEBGXZ:PANYARGS
?GetIdW@CLocation@@QEAAPEBGXZ TEXTEQU <__imp_?GetIdW@CLocation@@QEAAPEBGXZ>
extern __imp_?GetIdW@CTitle@@QEAAPEBGXZ:PANYARGS
?GetIdW@CTitle@@QEAAPEBGXZ TEXTEQU <__imp_?GetIdW@CTitle@@QEAAPEBGXZ>
extern __imp_?GetLangId@CCollection@@QEAAGPEBD@Z:PANYARGS
?GetLangId@CCollection@@QEAAGPEBD@Z TEXTEQU <__imp_?GetLangId@CCollection@@QEAAGPEBD@Z>
extern __imp_?GetLangId@CCollection@@QEAAGPEBG@Z:PANYARGS
?GetLangId@CCollection@@QEAAGPEBG@Z TEXTEQU <__imp_?GetLangId@CCollection@@QEAAGPEBG@Z>
extern __imp_?GetLanguage@CFolder@@QEAAGXZ:PANYARGS
?GetLanguage@CFolder@@QEAAGXZ TEXTEQU <__imp_?GetLanguage@CFolder@@QEAAGXZ>
extern __imp_?GetLanguage@CTitle@@QEAAGXZ:PANYARGS
?GetLanguage@CTitle@@QEAAGXZ TEXTEQU <__imp_?GetLanguage@CTitle@@QEAAGXZ>
extern __imp_?GetLocation@CTitle@@QEAAPEAULocationHistory@@K@Z:PANYARGS
?GetLocation@CTitle@@QEAAPEAULocationHistory@@K@Z TEXTEQU <__imp_?GetLocation@CTitle@@QEAAPEAULocationHistory@@K@Z>
extern __imp_?GetMasterCHM@CCollection@@QEAAHPEAPEADPEAG@Z:PANYARGS
?GetMasterCHM@CCollection@@QEAAHPEAPEADPEAG@Z TEXTEQU <__imp_?GetMasterCHM@CCollection@@QEAAHPEAPEADPEAG@Z>
extern __imp_?GetMasterCHM@CCollection@@QEAAHPEAPEAGPEAG@Z:PANYARGS
?GetMasterCHM@CCollection@@QEAAHPEAPEAGPEAG@Z TEXTEQU <__imp_?GetMasterCHM@CCollection@@QEAAHPEAPEAGPEAG@Z>
extern __imp_?GetNextFolder@CFolder@@QEAAPEAV1@XZ:PANYARGS
?GetNextFolder@CFolder@@QEAAPEAV1@XZ TEXTEQU <__imp_?GetNextFolder@CFolder@@QEAAPEAV1@XZ>
extern __imp_?GetNextLocation@CLocation@@QEAAPEAV1@XZ:PANYARGS
?GetNextLocation@CLocation@@QEAAPEAV1@XZ TEXTEQU <__imp_?GetNextLocation@CLocation@@QEAAPEAV1@XZ>
extern __imp_?GetNextTitle@CTitle@@QEAAPEAV1@XZ:PANYARGS
?GetNextTitle@CTitle@@QEAAPEAV1@XZ TEXTEQU <__imp_?GetNextTitle@CTitle@@QEAAPEAV1@XZ>
extern __imp_?GetOrder@CFolder@@QEAAKXZ:PANYARGS
?GetOrder@CFolder@@QEAAKXZ TEXTEQU <__imp_?GetOrder@CFolder@@QEAAKXZ>
extern __imp_?GetParent@CFolder@@QEAAPEAV1@XZ:PANYARGS
?GetParent@CFolder@@QEAAPEAV1@XZ TEXTEQU <__imp_?GetParent@CFolder@@QEAAPEAV1@XZ>
extern __imp_?GetPath@CLocation@@QEAAPEADXZ:PANYARGS
?GetPath@CLocation@@QEAAPEADXZ TEXTEQU <__imp_?GetPath@CLocation@@QEAAPEADXZ>
extern __imp_?GetPathW@CLocation@@QEAAPEBGXZ:PANYARGS
?GetPathW@CLocation@@QEAAPEBGXZ TEXTEQU <__imp_?GetPathW@CLocation@@QEAAPEBGXZ>
extern __imp_?GetRefTitleCount@CCollection@@QEAAKXZ:PANYARGS
?GetRefTitleCount@CCollection@@QEAAKXZ TEXTEQU <__imp_?GetRefTitleCount@CCollection@@QEAAKXZ>
extern __imp_?GetRootFolder@CCollection@@QEAAPEAVCFolder@@XZ:PANYARGS
?GetRootFolder@CCollection@@QEAAPEAVCFolder@@XZ TEXTEQU <__imp_?GetRootFolder@CCollection@@QEAAPEAVCFolder@@XZ>
extern __imp_?GetSampleLocation@CCollection@@QEAAPEADXZ:PANYARGS
?GetSampleLocation@CCollection@@QEAAPEADXZ TEXTEQU <__imp_?GetSampleLocation@CCollection@@QEAAPEADXZ>
extern __imp_?GetSampleLocationW@CCollection@@QEAAPEBGXZ:PANYARGS
?GetSampleLocationW@CCollection@@QEAAPEBGXZ TEXTEQU <__imp_?GetSampleLocationW@CCollection@@QEAAPEBGXZ>
extern __imp_?GetTail@CFIFOString@@QEAAKPEAPEAD@Z:PANYARGS
?GetTail@CFIFOString@@QEAAKPEAPEAD@Z TEXTEQU <__imp_?GetTail@CFIFOString@@QEAAKPEAPEAD@Z>
extern __imp_?GetTitle@CFolder@@QEAAPEADXZ:PANYARGS
?GetTitle@CFolder@@QEAAPEADXZ TEXTEQU <__imp_?GetTitle@CFolder@@QEAAPEADXZ>
extern __imp_?GetTitle@CLocation@@QEAAPEADXZ:PANYARGS
?GetTitle@CLocation@@QEAAPEADXZ TEXTEQU <__imp_?GetTitle@CLocation@@QEAAPEADXZ>
extern __imp_?GetTitleW@CFolder@@QEAAPEBGXZ:PANYARGS
?GetTitleW@CFolder@@QEAAPEBGXZ TEXTEQU <__imp_?GetTitleW@CFolder@@QEAAPEBGXZ>
extern __imp_?GetTitleW@CLocation@@QEAAPEBGXZ:PANYARGS
?GetTitleW@CLocation@@QEAAPEBGXZ TEXTEQU <__imp_?GetTitleW@CLocation@@QEAAPEBGXZ>
extern __imp_?GetVersion@CCollection@@QEAAKXZ:PANYARGS
?GetVersion@CCollection@@QEAAKXZ TEXTEQU <__imp_?GetVersion@CCollection@@QEAAKXZ>
extern __imp_?GetVisableRootFolder@CCollection@@QEAAPEAVCFolder@@XZ:PANYARGS
?GetVisableRootFolder@CCollection@@QEAAPEAVCFolder@@XZ TEXTEQU <__imp_?GetVisableRootFolder@CCollection@@QEAAPEAVCFolder@@XZ>
extern __imp_?GetVolume@CLocation@@QEAAPEADXZ:PANYARGS
?GetVolume@CLocation@@QEAAPEADXZ TEXTEQU <__imp_?GetVolume@CLocation@@QEAAPEADXZ>
extern __imp_?GetVolumeW@CLocation@@QEAAPEBGXZ:PANYARGS
?GetVolumeW@CLocation@@QEAAPEBGXZ TEXTEQU <__imp_?GetVolumeW@CLocation@@QEAAPEBGXZ>
extern __imp_?HandleCollection@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PANYARGS
?HandleCollection@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z TEXTEQU <__imp_?HandleCollection@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>
extern __imp_?HandleCollectionEntry@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PANYARGS
?HandleCollectionEntry@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z TEXTEQU <__imp_?HandleCollectionEntry@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>
extern __imp_?HandleFolder@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PANYARGS
?HandleFolder@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z TEXTEQU <__imp_?HandleFolder@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>
extern __imp_?HandleLocation@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PANYARGS
?HandleLocation@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z TEXTEQU <__imp_?HandleLocation@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>
extern __imp_?HandleTitle@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PANYARGS
?HandleTitle@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z TEXTEQU <__imp_?HandleTitle@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>
extern __imp_?IncrementRefTitleCount@CCollection@@QEAAXXZ:PANYARGS
?IncrementRefTitleCount@CCollection@@QEAAXXZ TEXTEQU <__imp_?IncrementRefTitleCount@CCollection@@QEAAXXZ>
extern __imp_?IsDirty@CCollection@@QEAAHXZ:PANYARGS
?IsDirty@CCollection@@QEAAHXZ TEXTEQU <__imp_?IsDirty@CCollection@@QEAAHXZ>
extern __imp_?MergeKeywords@CCollection@@QEAAHPEAD@Z:PANYARGS
?MergeKeywords@CCollection@@QEAAHPEAD@Z TEXTEQU <__imp_?MergeKeywords@CCollection@@QEAAHPEAD@Z>
extern __imp_?MergeKeywords@CCollection@@QEAAHPEAG@Z:PANYARGS
?MergeKeywords@CCollection@@QEAAHPEAG@Z TEXTEQU <__imp_?MergeKeywords@CCollection@@QEAAHPEAG@Z>
extern __imp_?NewLocation@CCollection@@AEAAPEAVCLocation@@XZ:PANYARGS
?NewLocation@CCollection@@AEAAPEAVCLocation@@XZ TEXTEQU <__imp_?NewLocation@CCollection@@AEAAPEAVCLocation@@XZ>
extern __imp_?NewLocationHistory@CTitle@@QEAAPEAULocationHistory@@XZ:PANYARGS
?NewLocationHistory@CTitle@@QEAAPEAULocationHistory@@XZ TEXTEQU <__imp_?NewLocationHistory@CTitle@@QEAAPEAULocationHistory@@XZ>
extern __imp_?NewTitle@CCollection@@AEAAPEAVCTitle@@XZ:PANYARGS
?NewTitle@CCollection@@AEAAPEAVCTitle@@XZ TEXTEQU <__imp_?NewTitle@CCollection@@AEAAPEAVCTitle@@XZ>
extern __imp_?Next@CPointerList@@QEAAPEAUListItem@@PEAU2@@Z:PANYARGS
?Next@CPointerList@@QEAAPEAUListItem@@PEAU2@@Z TEXTEQU <__imp_?Next@CPointerList@@QEAAPEAUListItem@@PEAU2@@Z>
extern __imp_?Open@CCollection@@QEAAKPEBD@Z:PANYARGS
?Open@CCollection@@QEAAKPEBD@Z TEXTEQU <__imp_?Open@CCollection@@QEAAKPEBD@Z>
extern __imp_?Open@CCollection@@QEAAKPEBG@Z:PANYARGS
?Open@CCollection@@QEAAKPEBG@Z TEXTEQU <__imp_?Open@CCollection@@QEAAKPEBG@Z>
extern __imp_?ParseFile@CCollection@@AEAAKPEBD@Z:PANYARGS
?ParseFile@CCollection@@AEAAKPEBD@Z TEXTEQU <__imp_?ParseFile@CCollection@@AEAAKPEBD@Z>
extern __imp_?Release@CCollection@@AEAAKXZ:PANYARGS
?Release@CCollection@@AEAAKXZ TEXTEQU <__imp_?Release@CCollection@@AEAAKXZ>
extern __imp_?RemoveAll@CFIFOString@@QEAAXXZ:PANYARGS
?RemoveAll@CFIFOString@@QEAAXXZ TEXTEQU <__imp_?RemoveAll@CFIFOString@@QEAAXXZ>
extern __imp_?RemoveAll@CPointerList@@QEAAXXZ:PANYARGS
?RemoveAll@CPointerList@@QEAAXXZ TEXTEQU <__imp_?RemoveAll@CPointerList@@QEAAXXZ>
extern __imp_?RemoveCollection@CCollection@@QEAAKH@Z:PANYARGS
?RemoveCollection@CCollection@@QEAAKH@Z TEXTEQU <__imp_?RemoveCollection@CCollection@@QEAAKH@Z>
extern __imp_?RemoveCollectionEntry@CCollection@@QEAAXPEAD@Z:PANYARGS
?RemoveCollectionEntry@CCollection@@QEAAXPEAD@Z TEXTEQU <__imp_?RemoveCollectionEntry@CCollection@@QEAAXPEAD@Z>
extern __imp_?Save@CCollection@@QEAAKXZ:PANYARGS
?Save@CCollection@@QEAAKXZ TEXTEQU <__imp_?Save@CCollection@@QEAAKXZ>
extern __imp_?SetExTitlePtr@CFolder@@QEAAXPEAVCExTitle@@@Z:PANYARGS
?SetExTitlePtr@CFolder@@QEAAXPEAVCExTitle@@@Z TEXTEQU <__imp_?SetExTitlePtr@CFolder@@QEAAXPEAVCExTitle@@@Z>
extern __imp_?SetFindMergedCHMS@CCollection@@QEAAXH@Z:PANYARGS
?SetFindMergedCHMS@CCollection@@QEAAXH@Z TEXTEQU <__imp_?SetFindMergedCHMS@CCollection@@QEAAXH@Z>
extern __imp_?SetFirstChildFolder@CFolder@@QEAAXPEAV1@@Z:PANYARGS
?SetFirstChildFolder@CFolder@@QEAAXPEAV1@@Z TEXTEQU <__imp_?SetFirstChildFolder@CFolder@@QEAAXPEAV1@@Z>
extern __imp_?SetId@CLocation@@QEAAXPEBD@Z:PANYARGS
?SetId@CLocation@@QEAAXPEBD@Z TEXTEQU <__imp_?SetId@CLocation@@QEAAXPEBD@Z>
extern __imp_?SetId@CLocation@@QEAAXPEBG@Z:PANYARGS
?SetId@CLocation@@QEAAXPEBG@Z TEXTEQU <__imp_?SetId@CLocation@@QEAAXPEBG@Z>
extern __imp_?SetId@CTitle@@QEAAXPEBD@Z:PANYARGS
?SetId@CTitle@@QEAAXPEBD@Z TEXTEQU <__imp_?SetId@CTitle@@QEAAXPEBD@Z>
extern __imp_?SetId@CTitle@@QEAAXPEBG@Z:PANYARGS
?SetId@CTitle@@QEAAXPEBG@Z TEXTEQU <__imp_?SetId@CTitle@@QEAAXPEBG@Z>
extern __imp_?SetLanguage@CFolder@@QEAAXG@Z:PANYARGS
?SetLanguage@CFolder@@QEAAXG@Z TEXTEQU <__imp_?SetLanguage@CFolder@@QEAAXG@Z>
extern __imp_?SetLanguage@CTitle@@QEAAXG@Z:PANYARGS
?SetLanguage@CTitle@@QEAAXG@Z TEXTEQU <__imp_?SetLanguage@CTitle@@QEAAXG@Z>
extern __imp_?SetMasterCHM@CCollection@@QEAAXPEBDG@Z:PANYARGS
?SetMasterCHM@CCollection@@QEAAXPEBDG@Z TEXTEQU <__imp_?SetMasterCHM@CCollection@@QEAAXPEBDG@Z>
extern __imp_?SetMasterCHM@CCollection@@QEAAXPEBGG@Z:PANYARGS
?SetMasterCHM@CCollection@@QEAAXPEBGG@Z TEXTEQU <__imp_?SetMasterCHM@CCollection@@QEAAXPEBGG@Z>
extern __imp_?SetNextFolder@CFolder@@QEAAXPEAV1@@Z:PANYARGS
?SetNextFolder@CFolder@@QEAAXPEAV1@@Z TEXTEQU <__imp_?SetNextFolder@CFolder@@QEAAXPEAV1@@Z>
extern __imp_?SetNextLocation@CLocation@@QEAAXPEAV1@@Z:PANYARGS
?SetNextLocation@CLocation@@QEAAXPEAV1@@Z TEXTEQU <__imp_?SetNextLocation@CLocation@@QEAAXPEAV1@@Z>
extern __imp_?SetNextTitle@CTitle@@QEAAXPEAV1@@Z:PANYARGS
?SetNextTitle@CTitle@@QEAAXPEAV1@@Z TEXTEQU <__imp_?SetNextTitle@CTitle@@QEAAXPEAV1@@Z>
extern __imp_?SetOrder@CFolder@@QEAAXK@Z:PANYARGS
?SetOrder@CFolder@@QEAAXK@Z TEXTEQU <__imp_?SetOrder@CFolder@@QEAAXK@Z>
extern __imp_?SetParent@CFolder@@QEAAXPEAV1@@Z:PANYARGS
?SetParent@CFolder@@QEAAXPEAV1@@Z TEXTEQU <__imp_?SetParent@CFolder@@QEAAXPEAV1@@Z>
extern __imp_?SetPath@CLocation@@QEAAXPEBD@Z:PANYARGS
?SetPath@CLocation@@QEAAXPEBD@Z TEXTEQU <__imp_?SetPath@CLocation@@QEAAXPEBD@Z>
extern __imp_?SetPath@CLocation@@QEAAXPEBG@Z:PANYARGS
?SetPath@CLocation@@QEAAXPEBG@Z TEXTEQU <__imp_?SetPath@CLocation@@QEAAXPEBG@Z>
extern __imp_?SetSampleLocation@CCollection@@QEAAXPEBD@Z:PANYARGS
?SetSampleLocation@CCollection@@QEAAXPEBD@Z TEXTEQU <__imp_?SetSampleLocation@CCollection@@QEAAXPEBD@Z>
extern __imp_?SetSampleLocation@CCollection@@QEAAXPEBG@Z:PANYARGS
?SetSampleLocation@CCollection@@QEAAXPEBG@Z TEXTEQU <__imp_?SetSampleLocation@CCollection@@QEAAXPEBG@Z>
extern __imp_?SetTitle@CFolder@@QEAAXPEBD@Z:PANYARGS
?SetTitle@CFolder@@QEAAXPEBD@Z TEXTEQU <__imp_?SetTitle@CFolder@@QEAAXPEBD@Z>
extern __imp_?SetTitle@CFolder@@QEAAXPEBG@Z:PANYARGS
?SetTitle@CFolder@@QEAAXPEBG@Z TEXTEQU <__imp_?SetTitle@CFolder@@QEAAXPEBG@Z>
extern __imp_?SetTitle@CLocation@@QEAAXPEBD@Z:PANYARGS
?SetTitle@CLocation@@QEAAXPEBD@Z TEXTEQU <__imp_?SetTitle@CLocation@@QEAAXPEBD@Z>
extern __imp_?SetTitle@CLocation@@QEAAXPEBG@Z:PANYARGS
?SetTitle@CLocation@@QEAAXPEBG@Z TEXTEQU <__imp_?SetTitle@CLocation@@QEAAXPEBG@Z>
extern __imp_?SetVersion@CCollection@@QEAAXK@Z:PANYARGS
?SetVersion@CCollection@@QEAAXK@Z TEXTEQU <__imp_?SetVersion@CCollection@@QEAAXK@Z>
extern __imp_?SetVolume@CLocation@@QEAAXPEBD@Z:PANYARGS
?SetVolume@CLocation@@QEAAXPEBD@Z TEXTEQU <__imp_?SetVolume@CLocation@@QEAAXPEBD@Z>
extern __imp_?SetVolume@CLocation@@QEAAXPEBG@Z:PANYARGS
?SetVolume@CLocation@@QEAAXPEBG@Z TEXTEQU <__imp_?SetVolume@CLocation@@QEAAXPEBG@Z>
extern __imp_?WriteFolder@CCollection@@AEAAHPEAPEAVCFolder@@@Z:PANYARGS
?WriteFolder@CCollection@@AEAAHPEAPEAVCFolder@@@Z TEXTEQU <__imp_?WriteFolder@CCollection@@AEAAHPEAPEAVCFolder@@@Z>
extern __imp_?WriteFolders@CCollection@@AEAAHPEAPEAVCFolder@@@Z:PANYARGS
?WriteFolders@CCollection@@AEAAHPEAPEAVCFolder@@@Z TEXTEQU <__imp_?WriteFolders@CCollection@@AEAAHPEAPEAVCFolder@@@Z>
extern __imp_?bIsVisable@CFolder@@QEAAHXZ:PANYARGS
?bIsVisable@CFolder@@QEAAHXZ TEXTEQU <__imp_?bIsVisable@CFolder@@QEAAHXZ>
extern __imp_?wssResetNextColNum@CCollection@@AEAAXXZ:PANYARGS
?wssResetNextColNum@CCollection@@AEAAXXZ TEXTEQU <__imp_?wssResetNextColNum@CCollection@@AEAAXXZ>
