extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_InitInstance:PANYARGS
InitInstance TEXTEQU <__imp_InitInstance>
extern __imp_MessageLoop:PANYARGS
MessageLoop TEXTEQU <__imp_MessageLoop>
extern __imp_sessQuerySysFileHdl:PANYARGS
sessQuerySysFileHdl TEXTEQU <__imp_sessQuerySysFileHdl>
extern __imp_sessQueryTranslateHdl:PANYARGS
sessQueryTranslateHdl TEXTEQU <__imp_sessQueryTranslateHdl>
extern __imp_sfGetSessionItem:PANYARGS
sfGetSessionItem TEXTEQU <__imp_sfGetSessionItem>
extern __imp_sfPutSessionItem:PANYARGS
sfPutSessionItem TEXTEQU <__imp_sfPutSessionItem>
