extern __imp_AllocateAttributes:PANYARGS
AllocateAttributes TEXTEQU <__imp_AllocateAttributes>
extern __imp_ConfigureIas:PANYARGS
ConfigureIas TEXTEQU <__imp_ConfigureIas>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_DoRequest:PANYARGS
DoRequest TEXTEQU <__imp_DoRequest>
extern __imp_FreeAttributes:PANYARGS
FreeAttributes TEXTEQU <__imp_FreeAttributes>
extern __imp_InitializeIas:PANYARGS
InitializeIas TEXTEQU <__imp_InitializeIas>
extern __imp_MemAllocIas:PANYARGS
MemAllocIas TEXTEQU <__imp_MemAllocIas>
extern __imp_MemFreeIas:PANYARGS
MemFreeIas TEXTEQU <__imp_MemFreeIas>
extern __imp_MemReallocIas:PANYARGS
MemReallocIas TEXTEQU <__imp_MemReallocIas>
extern __imp_ShutdownIas:PANYARGS
ShutdownIas TEXTEQU <__imp_ShutdownIas>
