extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_IASAttributeAddRef:PANYARGS
IASAttributeAddRef TEXTEQU <__imp_IASAttributeAddRef>
extern __imp_IASAttributeAlloc:PANYARGS
IASAttributeAlloc TEXTEQU <__imp_IASAttributeAlloc>
extern __imp_IASAttributeAnsiAlloc:PANYARGS
IASAttributeAnsiAlloc TEXTEQU <__imp_IASAttributeAnsiAlloc>
extern __imp_IASAttributeRelease:PANYARGS
IASAttributeRelease TEXTEQU <__imp_IASAttributeRelease>
extern __imp_IASAttributeUnicodeAlloc:PANYARGS
IASAttributeUnicodeAlloc TEXTEQU <__imp_IASAttributeUnicodeAlloc>
