extern __imp_?initialize@VSAFilter@@QEAAJXZ:PANYARGS
?initialize@VSAFilter@@QEAAJXZ TEXTEQU <__imp_?initialize@VSAFilter@@QEAAJXZ>
extern __imp_?radiusFromIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z:PANYARGS
?radiusFromIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z TEXTEQU <__imp_?radiusFromIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z>
extern __imp_?radiusToIAS@VSAFilter@@QEBAJPEAEKAEAVIASAttributeVector@IASTL@@@Z:PANYARGS
?radiusToIAS@VSAFilter@@QEBAJPEAEKAEAVIASAttributeVector@IASTL@@@Z TEXTEQU <__imp_?radiusToIAS@VSAFilter@@QEBAJPEAEKAEAVIASAttributeVector@IASTL@@@Z>
extern __imp_?radiusToIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z:PANYARGS
?radiusToIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z TEXTEQU <__imp_?radiusToIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z>
extern __imp_?shutdown@VSAFilter@@QEAAJXZ:PANYARGS
?shutdown@VSAFilter@@QEAAJXZ TEXTEQU <__imp_?shutdown@VSAFilter@@QEAAJXZ>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
