extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_IASAdler32:PANYARGS
IASAdler32 TEXTEQU <__imp_IASAdler32>
extern __imp_IASAllocateUniqueID:PANYARGS
IASAllocateUniqueID TEXTEQU <__imp_IASAllocateUniqueID>
extern __imp_IASGetDictionary:PANYARGS
IASGetDictionary TEXTEQU <__imp_IASGetDictionary>
extern __imp_IASGetHostByName:PANYARGS
IASGetHostByName TEXTEQU <__imp_IASGetHostByName>
extern __imp_IASGetLocalDictionary:PANYARGS
IASGetLocalDictionary TEXTEQU <__imp_IASGetLocalDictionary>
extern __imp_IASGetProductLimits:PANYARGS
IASGetProductLimits TEXTEQU <__imp_IASGetProductLimits>
extern __imp_IASGlobalLock:PANYARGS
IASGlobalLock TEXTEQU <__imp_IASGlobalLock>
extern __imp_IASGlobalUnlock:PANYARGS
IASGlobalUnlock TEXTEQU <__imp_IASGlobalUnlock>
extern __imp_IASInitialize:PANYARGS
IASInitialize TEXTEQU <__imp_IASInitialize>
extern __imp_IASRadiusCrypt:PANYARGS
IASRadiusCrypt TEXTEQU <__imp_IASRadiusCrypt>
extern __imp_IASRegisterComponent:PANYARGS
IASRegisterComponent TEXTEQU <__imp_IASRegisterComponent>
extern __imp_IASReportEvent:PANYARGS
IASReportEvent TEXTEQU <__imp_IASReportEvent>
extern __imp_IASReportLicenseViolation:PANYARGS
IASReportLicenseViolation TEXTEQU <__imp_IASReportLicenseViolation>
extern __imp_IASRequestThread:PANYARGS
IASRequestThread TEXTEQU <__imp_IASRequestThread>
extern __imp_IASSetMaxNumberOfThreads:PANYARGS
IASSetMaxNumberOfThreads TEXTEQU <__imp_IASSetMaxNumberOfThreads>
extern __imp_IASSetMaxThreadIdle:PANYARGS
IASSetMaxThreadIdle TEXTEQU <__imp_IASSetMaxThreadIdle>
extern __imp_IASUninitialize:PANYARGS
IASUninitialize TEXTEQU <__imp_IASUninitialize>
extern __imp_IASVariantChangeType:PANYARGS
IASVariantChangeType TEXTEQU <__imp_IASVariantChangeType>
