extern __imp_IcaCdCreateThread:PANYARGS
IcaCdCreateThread TEXTEQU <__imp_IcaCdCreateThread>
extern __imp_IcaCdIoControl:PANYARGS
IcaCdIoControl TEXTEQU <__imp_IcaCdIoControl>
extern __imp_IcaCdWaitForMultipleObjects:PANYARGS
IcaCdWaitForMultipleObjects TEXTEQU <__imp_IcaCdWaitForMultipleObjects>
extern __imp_IcaCdWaitForSingleObject:PANYARGS
IcaCdWaitForSingleObject TEXTEQU <__imp_IcaCdWaitForSingleObject>
extern __imp_IcaChannelClose:PANYARGS
IcaChannelClose TEXTEQU <__imp_IcaChannelClose>
extern __imp_IcaChannelIoControl:PANYARGS
IcaChannelIoControl TEXTEQU <__imp_IcaChannelIoControl>
extern __imp_IcaChannelOpen:PANYARGS
IcaChannelOpen TEXTEQU <__imp_IcaChannelOpen>
extern __imp_IcaChannelTrace:PANYARGS
IcaChannelTrace TEXTEQU <__imp_IcaChannelTrace>
extern __imp_IcaClose:PANYARGS
IcaClose TEXTEQU <__imp_IcaClose>
extern __imp_IcaIoControl:PANYARGS
IcaIoControl TEXTEQU <__imp_IcaIoControl>
extern __imp_IcaMemoryAllocate:PANYARGS
IcaMemoryAllocate TEXTEQU <__imp_IcaMemoryAllocate>
extern __imp_IcaMemoryFree:PANYARGS
IcaMemoryFree TEXTEQU <__imp_IcaMemoryFree>
extern __imp_IcaOpen:PANYARGS
IcaOpen TEXTEQU <__imp_IcaOpen>
extern __imp_IcaPushConsoleStack:PANYARGS
IcaPushConsoleStack TEXTEQU <__imp_IcaPushConsoleStack>
extern __imp_IcaStackCallback:PANYARGS
IcaStackCallback TEXTEQU <__imp_IcaStackCallback>
extern __imp_IcaStackClose:PANYARGS
IcaStackClose TEXTEQU <__imp_IcaStackClose>
extern __imp_IcaStackConnectionAccept:PANYARGS
IcaStackConnectionAccept TEXTEQU <__imp_IcaStackConnectionAccept>
extern __imp_IcaStackConnectionClose:PANYARGS
IcaStackConnectionClose TEXTEQU <__imp_IcaStackConnectionClose>
extern __imp_IcaStackConnectionRequest:PANYARGS
IcaStackConnectionRequest TEXTEQU <__imp_IcaStackConnectionRequest>
extern __imp_IcaStackConnectionWait:PANYARGS
IcaStackConnectionWait TEXTEQU <__imp_IcaStackConnectionWait>
extern __imp_IcaStackCreateShadowEndpoint:PANYARGS
IcaStackCreateShadowEndpoint TEXTEQU <__imp_IcaStackCreateShadowEndpoint>
extern __imp_IcaStackDisconnect:PANYARGS
IcaStackDisconnect TEXTEQU <__imp_IcaStackDisconnect>
extern __imp_IcaStackIoControl:PANYARGS
IcaStackIoControl TEXTEQU <__imp_IcaStackIoControl>
extern __imp_IcaStackIoControlNoConnLock:PANYARGS
IcaStackIoControlNoConnLock TEXTEQU <__imp_IcaStackIoControlNoConnLock>
extern __imp_IcaStackOpen:PANYARGS
IcaStackOpen TEXTEQU <__imp_IcaStackOpen>
extern __imp_IcaStackQueryLocalAddress:PANYARGS
IcaStackQueryLocalAddress TEXTEQU <__imp_IcaStackQueryLocalAddress>
extern __imp_IcaStackQueryState:PANYARGS
IcaStackQueryState TEXTEQU <__imp_IcaStackQueryState>
extern __imp_IcaStackReconnect:PANYARGS
IcaStackReconnect TEXTEQU <__imp_IcaStackReconnect>
extern __imp_IcaStackTerminate:PANYARGS
IcaStackTerminate TEXTEQU <__imp_IcaStackTerminate>
extern __imp_IcaStackTrace:PANYARGS
IcaStackTrace TEXTEQU <__imp_IcaStackTrace>
extern __imp_IcaStackUnlock:PANYARGS
IcaStackUnlock TEXTEQU <__imp_IcaStackUnlock>
extern __imp_IcaSystemTrace:PANYARGS
IcaSystemTrace TEXTEQU <__imp_IcaSystemTrace>
extern __imp_IcaTrace:PANYARGS
IcaTrace TEXTEQU <__imp_IcaTrace>
extern __imp__IcaStackIoControl:PANYARGS
_IcaStackIoControl TEXTEQU <__imp__IcaStackIoControl>
