extern __imp_CMCheckColors:PANYARGS
CMCheckColors TEXTEQU <__imp_CMCheckColors>
extern __imp_CMCheckColorsInGamut:PANYARGS
CMCheckColorsInGamut TEXTEQU <__imp_CMCheckColorsInGamut>
extern __imp_CMCheckRGBs:PANYARGS
CMCheckRGBs TEXTEQU <__imp_CMCheckRGBs>
extern __imp_CMCreateDeviceLinkProfile:PANYARGS
CMCreateDeviceLinkProfile TEXTEQU <__imp_CMCreateDeviceLinkProfile>
extern __imp_CMCreateMultiProfileTransform:PANYARGS
CMCreateMultiProfileTransform TEXTEQU <__imp_CMCreateMultiProfileTransform>
extern __imp_CMCreateProfile:PANYARGS
CMCreateProfile TEXTEQU <__imp_CMCreateProfile>
extern __imp_CMCreateProfileW:PANYARGS
CMCreateProfileW TEXTEQU <__imp_CMCreateProfileW>
extern __imp_CMCreateTransform:PANYARGS
CMCreateTransform TEXTEQU <__imp_CMCreateTransform>
extern __imp_CMCreateTransformExt:PANYARGS
CMCreateTransformExt TEXTEQU <__imp_CMCreateTransformExt>
extern __imp_CMCreateTransformExtW:PANYARGS
CMCreateTransformExtW TEXTEQU <__imp_CMCreateTransformExtW>
extern __imp_CMCreateTransformW:PANYARGS
CMCreateTransformW TEXTEQU <__imp_CMCreateTransformW>
extern __imp_CMDeleteTransform:PANYARGS
CMDeleteTransform TEXTEQU <__imp_CMDeleteTransform>
extern __imp_CMGetInfo:PANYARGS
CMGetInfo TEXTEQU <__imp_CMGetInfo>
extern __imp_CMIsProfileValid:PANYARGS
CMIsProfileValid TEXTEQU <__imp_CMIsProfileValid>
extern __imp_CMTranslateColors:PANYARGS
CMTranslateColors TEXTEQU <__imp_CMTranslateColors>
extern __imp_CMTranslateRGB:PANYARGS
CMTranslateRGB TEXTEQU <__imp_CMTranslateRGB>
extern __imp_CMTranslateRGBs:PANYARGS
CMTranslateRGBs TEXTEQU <__imp_CMTranslateRGBs>
extern __imp_CMTranslateRGBsExt:PANYARGS
CMTranslateRGBsExt TEXTEQU <__imp_CMTranslateRGBsExt>
extern __imp_CMConvertColorNameToIndex:PANYARGS
CMConvertColorNameToIndex TEXTEQU <__imp_CMConvertColorNameToIndex>
extern __imp_CMConvertIndexToColorName:PANYARGS
CMConvertIndexToColorName TEXTEQU <__imp_CMConvertIndexToColorName>
extern __imp_CMGetNamedProfileInfo:PANYARGS
CMGetNamedProfileInfo TEXTEQU <__imp_CMGetNamedProfileInfo>
