extern __imp_IcmpCloseHandle:PANYARGS
IcmpCloseHandle TEXTEQU <__imp_IcmpCloseHandle>
extern __imp_IcmpCreateFile:PANYARGS
IcmpCreateFile TEXTEQU <__imp_IcmpCreateFile>
extern __imp_IcmpParseReplies:PANYARGS
IcmpParseReplies TEXTEQU <__imp_IcmpParseReplies>
extern __imp_IcmpSendEcho:PANYARGS
IcmpSendEcho TEXTEQU <__imp_IcmpSendEcho>
extern __imp_IcmpSendEcho2:PANYARGS
IcmpSendEcho2 TEXTEQU <__imp_IcmpSendEcho2>
extern __imp_do_echo_rep:PANYARGS
do_echo_rep TEXTEQU <__imp_do_echo_rep>
extern __imp_do_echo_req:PANYARGS
do_echo_req TEXTEQU <__imp_do_echo_req>
extern __imp_register_icmp:PANYARGS
register_icmp TEXTEQU <__imp_register_icmp>
