extern __imp_AutoDialHandler:PANYARGS
AutoDialHandler TEXTEQU <__imp_AutoDialHandler>
extern __imp_AutoDialInit:PANYARGS
AutoDialInit TEXTEQU <__imp_AutoDialInit>
extern __imp_RasSetEntryPropertiesScriptPatch:PANYARGS
RasSetEntryPropertiesScriptPatch TEXTEQU <__imp_RasSetEntryPropertiesScriptPatch>
extern __imp_DialingDownloadDialog:PANYARGS
DialingDownloadDialog TEXTEQU <__imp_DialingDownloadDialog>
extern __imp_DialingErrorDialog:PANYARGS
DialingErrorDialog TEXTEQU <__imp_DialingErrorDialog>
extern __imp_ICWGetRasEntry:PANYARGS
ICWGetRasEntry TEXTEQU <__imp_ICWGetRasEntry>
