extern __imp_AddADMItemA:PANYARGS
AddADMItem  TEXTEQU <__imp_AddADMItemA>
extern __imp_AddADMItemW:PANYARGS
AddADMItemW TEXTEQU <__imp_AddADMItemW>
extern __imp_BToolbar_Edit:PANYARGS
BToolbar_Edit TEXTEQU <__imp_BToolbar_Edit>
extern __imp_BToolbar_InitA:PANYARGS
BToolbar_Init  TEXTEQU <__imp_BToolbar_InitA>
extern __imp_BToolbar_InitW:PANYARGS
BToolbar_InitW TEXTEQU <__imp_BToolbar_InitW>
extern __imp_BToolbar_Remove:PANYARGS
BToolbar_Remove TEXTEQU <__imp_BToolbar_Remove>
extern __imp_BToolbar_SaveA:PANYARGS
BToolbar_Save  TEXTEQU <__imp_BToolbar_SaveA>
extern __imp_BToolbar_SaveW:PANYARGS
BToolbar_SaveW TEXTEQU <__imp_BToolbar_SaveW>
extern __imp_BrowseForFileA:PANYARGS
BrowseForFile  TEXTEQU <__imp_BrowseForFileA>
extern __imp_BrowseForFileW:PANYARGS
BrowseForFileW TEXTEQU <__imp_BrowseForFileW>
extern __imp_BrowseForFolderA:PANYARGS
BrowseForFolder  TEXTEQU <__imp_BrowseForFolderA>
extern __imp_BrowseForFolderW:PANYARGS
BrowseForFolderW TEXTEQU <__imp_BrowseForFolderW>
extern __imp_BuildPalette:PANYARGS
BuildPalette TEXTEQU <__imp_BuildPalette>
extern __imp_CanDeleteADM:PANYARGS
CanDeleteADM TEXTEQU <__imp_CanDeleteADM>
extern __imp_CheckField:PANYARGS
CheckField TEXTEQU <__imp_CheckField>
extern __imp_CheckForDupKeys:PANYARGS
CheckForDupKeys TEXTEQU <__imp_CheckForDupKeys>
extern __imp_CheckVerA:PANYARGS
CheckVer  TEXTEQU <__imp_CheckVerA>
extern __imp_CheckVerW:PANYARGS
CheckVerW TEXTEQU <__imp_CheckVerW>
extern __imp_CopyAnimBmpA:PANYARGS
CopyAnimBmp  TEXTEQU <__imp_CopyAnimBmpA>
extern __imp_CopyAnimBmpW:PANYARGS
CopyAnimBmpW TEXTEQU <__imp_CopyAnimBmpW>
extern __imp_CopyHttFileA:PANYARGS
CopyHttFile  TEXTEQU <__imp_CopyHttFileA>
extern __imp_CopyHttFileW:PANYARGS
CopyHttFileW TEXTEQU <__imp_CopyHttFileW>
extern __imp_CopyLogoBmpA:PANYARGS
CopyLogoBmp  TEXTEQU <__imp_CopyLogoBmpA>
extern __imp_CopyLogoBmpW:PANYARGS
CopyLogoBmpW TEXTEQU <__imp_CopyLogoBmpW>
extern __imp_CopyWallPaperA:PANYARGS
CopyWallPaper  TEXTEQU <__imp_CopyWallPaperA>
extern __imp_CopyWallPaperW:PANYARGS
CopyWallPaperW TEXTEQU <__imp_CopyWallPaperW>
extern __imp_CreateADMWindow:PANYARGS
CreateADMWindow TEXTEQU <__imp_CreateADMWindow>
extern __imp_DeleteADMItemA:PANYARGS
DeleteADMItem  TEXTEQU <__imp_DeleteADMItemA>
extern __imp_DeleteADMItemW:PANYARGS
DeleteADMItemW TEXTEQU <__imp_DeleteADMItemW>
extern __imp_DeleteADMItemsA:PANYARGS
DeleteADMItems  TEXTEQU <__imp_DeleteADMItemsA>
extern __imp_DeleteADMItemsW:PANYARGS
DeleteADMItemsW TEXTEQU <__imp_DeleteADMItemsW>
extern __imp_DeleteFavoriteA:PANYARGS
DeleteFavorite  TEXTEQU <__imp_DeleteFavoriteA>
extern __imp_DeleteFavoriteW:PANYARGS
DeleteFavoriteW TEXTEQU <__imp_DeleteFavoriteW>
extern __imp_DestroyADMWindow:PANYARGS
DestroyADMWindow TEXTEQU <__imp_DestroyADMWindow>
extern __imp_DisplayADMItem:PANYARGS
DisplayADMItem TEXTEQU <__imp_DisplayADMItem>
extern __imp_DoReboot:PANYARGS
DoReboot TEXTEQU <__imp_DoReboot>
extern __imp_EncodeSignatureA:PANYARGS
EncodeSignature  TEXTEQU <__imp_EncodeSignatureA>
extern __imp_EncodeSignatureW:PANYARGS
EncodeSignatureW TEXTEQU <__imp_EncodeSignatureW>
extern __imp_ErrorMessageBox:PANYARGS
ErrorMessageBox TEXTEQU <__imp_ErrorMessageBox>
extern __imp_ExportFavoritesA:PANYARGS
ExportFavorites  TEXTEQU <__imp_ExportFavoritesA>
extern __imp_ExportFavoritesW:PANYARGS
ExportFavoritesW TEXTEQU <__imp_ExportFavoritesW>
extern __imp_ExportQuickLinksA:PANYARGS
ExportQuickLinks  TEXTEQU <__imp_ExportQuickLinksA>
extern __imp_ExportQuickLinksW:PANYARGS
ExportQuickLinksW TEXTEQU <__imp_ExportQuickLinksW>
extern __imp_ExportRegKey2InfA:PANYARGS
ExportRegKey2Inf  TEXTEQU <__imp_ExportRegKey2InfA>
extern __imp_ExportRegKey2InfW:PANYARGS
ExportRegKey2InfW TEXTEQU <__imp_ExportRegKey2InfW>
extern __imp_ExportRegTree2InfA:PANYARGS
ExportRegTree2Inf  TEXTEQU <__imp_ExportRegTree2InfA>
extern __imp_ExportRegTree2InfW:PANYARGS
ExportRegTree2InfW TEXTEQU <__imp_ExportRegTree2InfW>
extern __imp_ExportRegValue2InfA:PANYARGS
ExportRegValue2Inf  TEXTEQU <__imp_ExportRegValue2InfA>
extern __imp_ExportRegValue2InfW:PANYARGS
ExportRegValue2InfW TEXTEQU <__imp_ExportRegValue2InfW>
extern __imp_GenerateNewVersionStrA:PANYARGS
GenerateNewVersionStr  TEXTEQU <__imp_GenerateNewVersionStrA>
extern __imp_GenerateNewVersionStrW:PANYARGS
GenerateNewVersionStrW TEXTEQU <__imp_GenerateNewVersionStrW>
extern __imp_GetAdmFileListA:PANYARGS
GetAdmFileList  TEXTEQU <__imp_GetAdmFileListA>
extern __imp_GetAdmFileListW:PANYARGS
GetAdmFileListW TEXTEQU <__imp_GetAdmFileListW>
extern __imp_GetAdmWindowHandle:PANYARGS
GetAdmWindowHandle TEXTEQU <__imp_GetAdmWindowHandle>
extern __imp_GetBaseFileNameA:PANYARGS
GetBaseFileName  TEXTEQU <__imp_GetBaseFileNameA>
extern __imp_GetBaseFileNameW:PANYARGS
GetBaseFileNameW TEXTEQU <__imp_GetBaseFileNameW>
extern __imp_GetFavoriteUrlA:PANYARGS
GetFavoriteUrl  TEXTEQU <__imp_GetFavoriteUrlA>
extern __imp_GetFavoriteUrlW:PANYARGS
GetFavoriteUrlW TEXTEQU <__imp_GetFavoriteUrlW>
extern __imp_GetFavoritesInfoTipA:PANYARGS
GetFavoritesInfoTip  TEXTEQU <__imp_GetFavoritesInfoTipA>
extern __imp_GetFavoritesInfoTipW:PANYARGS
GetFavoritesInfoTipW TEXTEQU <__imp_GetFavoritesInfoTipW>
extern __imp_GetFavoritesMaxNumber:PANYARGS
GetFavoritesMaxNumber TEXTEQU <__imp_GetFavoritesMaxNumber>
extern __imp_GetFavoritesNumber:PANYARGS
GetFavoritesNumber TEXTEQU <__imp_GetFavoritesNumber>
extern __imp_GetProxyDlgA:PANYARGS
GetProxyDlg  TEXTEQU <__imp_GetProxyDlgA>
extern __imp_GetProxyDlgW:PANYARGS
GetProxyDlgW TEXTEQU <__imp_GetProxyDlgW>
extern __imp_ImportADMFileA:PANYARGS
ImportADMFile  TEXTEQU <__imp_ImportADMFileA>
extern __imp_ImportADMFileW:PANYARGS
ImportADMFileW TEXTEQU <__imp_ImportADMFileW>
extern __imp_ImportADTInfoA:PANYARGS
ImportADTInfo  TEXTEQU <__imp_ImportADTInfoA>
extern __imp_ImportADTInfoW:PANYARGS
ImportADTInfoW TEXTEQU <__imp_ImportADTInfoW>
extern __imp_ImportAuthCodeA:PANYARGS
ImportAuthCode  TEXTEQU <__imp_ImportAuthCodeA>
extern __imp_ImportAuthCodeW:PANYARGS
ImportAuthCodeW TEXTEQU <__imp_ImportAuthCodeW>
extern __imp_ImportConnectSetA:PANYARGS
ImportConnectSet  TEXTEQU <__imp_ImportConnectSetA>
extern __imp_ImportConnectSetW:PANYARGS
ImportConnectSetW TEXTEQU <__imp_ImportConnectSetW>
extern __imp_ImportFavoritesA:PANYARGS
ImportFavorites  TEXTEQU <__imp_ImportFavoritesA>
extern __imp_ImportFavoritesCmdA:PANYARGS
ImportFavoritesCmd  TEXTEQU <__imp_ImportFavoritesCmdA>
extern __imp_ImportFavoritesCmdW:PANYARGS
ImportFavoritesCmdW TEXTEQU <__imp_ImportFavoritesCmdW>
extern __imp_ImportFavoritesW:PANYARGS
ImportFavoritesW TEXTEQU <__imp_ImportFavoritesW>
extern __imp_ImportLDAPBitmapA:PANYARGS
ImportLDAPBitmap  TEXTEQU <__imp_ImportLDAPBitmapA>
extern __imp_ImportLDAPBitmapW:PANYARGS
ImportLDAPBitmapW TEXTEQU <__imp_ImportLDAPBitmapW>
extern __imp_ImportOEInfoA:PANYARGS
ImportOEInfo  TEXTEQU <__imp_ImportOEInfoA>
extern __imp_ImportOEInfoW:PANYARGS
ImportOEInfoW TEXTEQU <__imp_ImportOEInfoW>
extern __imp_ImportProgramsA:PANYARGS
ImportPrograms  TEXTEQU <__imp_ImportProgramsA>
extern __imp_ImportProgramsW:PANYARGS
ImportProgramsW TEXTEQU <__imp_ImportProgramsW>
extern __imp_ImportQuickLinksA:PANYARGS
ImportQuickLinks  TEXTEQU <__imp_ImportQuickLinksA>
extern __imp_ImportQuickLinksW:PANYARGS
ImportQuickLinksW TEXTEQU <__imp_ImportQuickLinksW>
extern __imp_ImportRatingsA:PANYARGS
ImportRatings  TEXTEQU <__imp_ImportRatingsA>
extern __imp_ImportRatingsW:PANYARGS
ImportRatingsW TEXTEQU <__imp_ImportRatingsW>
extern __imp_ImportSiteCertA:PANYARGS
ImportSiteCert  TEXTEQU <__imp_ImportSiteCertA>
extern __imp_ImportSiteCertW:PANYARGS
ImportSiteCertW TEXTEQU <__imp_ImportSiteCertW>
extern __imp_ImportToolbarInfoA:PANYARGS
ImportToolbarInfo  TEXTEQU <__imp_ImportToolbarInfoA>
extern __imp_ImportToolbarInfoW:PANYARGS
ImportToolbarInfoW TEXTEQU <__imp_ImportToolbarInfoW>
extern __imp_ImportZonesA:PANYARGS
ImportZones  TEXTEQU <__imp_ImportZonesA>
extern __imp_ImportZonesW:PANYARGS
ImportZonesW TEXTEQU <__imp_ImportZonesW>
extern __imp_InitializeStartSearchA:PANYARGS
InitializeStartSearch  TEXTEQU <__imp_InitializeStartSearchA>
extern __imp_InitializeStartSearchW:PANYARGS
InitializeStartSearchW TEXTEQU <__imp_InitializeStartSearchW>
extern __imp_IsADMFileVisibleA:PANYARGS
IsADMFileVisible  TEXTEQU <__imp_IsADMFileVisibleA>
extern __imp_IsADMFileVisibleW:PANYARGS
IsADMFileVisibleW TEXTEQU <__imp_IsADMFileVisibleW>
extern __imp_IsAnimBitmapFileValidA:PANYARGS
IsAnimBitmapFileValid  TEXTEQU <__imp_IsAnimBitmapFileValidA>
extern __imp_IsAnimBitmapFileValidW:PANYARGS
IsAnimBitmapFileValidW TEXTEQU <__imp_IsAnimBitmapFileValidW>
extern __imp_IsBitmapFileValidA:PANYARGS
IsBitmapFileValid  TEXTEQU <__imp_IsBitmapFileValidA>
extern __imp_IsBitmapFileValidW:PANYARGS
IsBitmapFileValidW TEXTEQU <__imp_IsBitmapFileValidW>
extern __imp_IsFavoriteItem:PANYARGS
IsFavoriteItem TEXTEQU <__imp_IsFavoriteItem>
extern __imp_LoadADMFilesA:PANYARGS
LoadADMFiles  TEXTEQU <__imp_LoadADMFilesA>
extern __imp_LoadADMFilesW:PANYARGS
LoadADMFilesW TEXTEQU <__imp_LoadADMFilesW>
extern __imp_MigrateFavoritesA:PANYARGS
MigrateFavorites  TEXTEQU <__imp_MigrateFavoritesA>
extern __imp_MigrateFavoritesW:PANYARGS
MigrateFavoritesW TEXTEQU <__imp_MigrateFavoritesW>
extern __imp_MigrateToOldFavoritesA:PANYARGS
MigrateToOldFavorites  TEXTEQU <__imp_MigrateToOldFavoritesA>
extern __imp_MigrateToOldFavoritesW:PANYARGS
MigrateToOldFavoritesW TEXTEQU <__imp_MigrateToOldFavoritesW>
extern __imp_ModifyAuthCode:PANYARGS
ModifyAuthCode TEXTEQU <__imp_ModifyAuthCode>
extern __imp_ModifyFavoriteA:PANYARGS
ModifyFavorite  TEXTEQU <__imp_ModifyFavoriteA>
extern __imp_ModifyFavoriteW:PANYARGS
ModifyFavoriteW TEXTEQU <__imp_ModifyFavoriteW>
extern __imp_ModifyRatings:PANYARGS
ModifyRatings TEXTEQU <__imp_ModifyRatings>
extern __imp_ModifySiteCert:PANYARGS
ModifySiteCert TEXTEQU <__imp_ModifySiteCert>
extern __imp_ModifyZones:PANYARGS
ModifyZones TEXTEQU <__imp_ModifyZones>
extern __imp_MoveADMWindow:PANYARGS
MoveADMWindow TEXTEQU <__imp_MoveADMWindow>
extern __imp_MoveDownFavorite:PANYARGS
MoveDownFavorite TEXTEQU <__imp_MoveDownFavorite>
extern __imp_MoveUpFavorite:PANYARGS
MoveUpFavorite TEXTEQU <__imp_MoveUpFavorite>
extern __imp_NewFolder:PANYARGS
NewFolder TEXTEQU <__imp_NewFolder>
extern __imp_NewUrlA:PANYARGS
NewUrl  TEXTEQU <__imp_NewUrlA>
extern __imp_NewUrlW:PANYARGS
NewUrlW TEXTEQU <__imp_NewUrlW>
extern __imp_ProcessFavSelChange:PANYARGS
ProcessFavSelChange TEXTEQU <__imp_ProcessFavSelChange>
extern __imp_ResetAdmFilesA:PANYARGS
ResetAdmFiles  TEXTEQU <__imp_ResetAdmFilesA>
extern __imp_ResetAdmFilesW:PANYARGS
ResetAdmFilesW TEXTEQU <__imp_ResetAdmFilesW>
extern __imp_SaveADMItem:PANYARGS
SaveADMItem TEXTEQU <__imp_SaveADMItem>
extern __imp_SaveAdmFilesA:PANYARGS
SaveAdmFiles  TEXTEQU <__imp_SaveAdmFilesA>
extern __imp_SaveAdmFilesW:PANYARGS
SaveAdmFilesW TEXTEQU <__imp_SaveAdmFilesW>
extern __imp_SaveStartSearchA:PANYARGS
SaveStartSearch  TEXTEQU <__imp_SaveStartSearchA>
extern __imp_SaveStartSearchW:PANYARGS
SaveStartSearchW TEXTEQU <__imp_SaveStartSearchW>
extern __imp_SelectADMItem:PANYARGS
SelectADMItem TEXTEQU <__imp_SelectADMItem>
extern __imp_SetADMWindowTextA:PANYARGS
SetADMWindowText  TEXTEQU <__imp_SetADMWindowTextA>
extern __imp_SetADMWindowTextW:PANYARGS
SetADMWindowTextW TEXTEQU <__imp_SetADMWindowTextW>
extern __imp_SetLBWidth:PANYARGS
SetLBWidth TEXTEQU <__imp_SetLBWidth>
extern __imp_SetOrClearVersionInfoA:PANYARGS
SetOrClearVersionInfo  TEXTEQU <__imp_SetOrClearVersionInfoA>
extern __imp_SetOrClearVersionInfoW:PANYARGS
SetOrClearVersionInfoW TEXTEQU <__imp_SetOrClearVersionInfoW>
extern __imp_SetProxyDlgA:PANYARGS
SetProxyDlg  TEXTEQU <__imp_SetProxyDlgA>
extern __imp_SetProxyDlgW:PANYARGS
SetProxyDlgW TEXTEQU <__imp_SetProxyDlgW>
extern __imp_ShowADMWindow:PANYARGS
ShowADMWindow TEXTEQU <__imp_ShowADMWindow>
extern __imp_ShowBitmapA:PANYARGS
ShowBitmap  TEXTEQU <__imp_ShowBitmapA>
extern __imp_ShowBitmapW:PANYARGS
ShowBitmapW TEXTEQU <__imp_ShowBitmapW>
extern __imp_ShowDeskCpl:PANYARGS
ShowDeskCpl TEXTEQU <__imp_ShowDeskCpl>
extern __imp_ShowInetcpl:PANYARGS
ShowInetcpl TEXTEQU <__imp_ShowInetcpl>
extern __imp_SignFileA:PANYARGS
SignFile  TEXTEQU <__imp_SignFileA>
extern __imp_SignFileW:PANYARGS
SignFileW TEXTEQU <__imp_SignFileW>
extern __imp_TestURLA:PANYARGS
TestURL  TEXTEQU <__imp_TestURLA>
extern __imp_TestURLW:PANYARGS
TestURLW TEXTEQU <__imp_TestURLW>
