extern __imp_BrandExternal:PANYARGS
BrandExternal TEXTEQU <__imp_BrandExternal>
extern __imp_CloseRASConnections:PANYARGS
CloseRASConnections TEXTEQU <__imp_CloseRASConnections>
extern __imp_GenerateGroupPolicy:PANYARGS
GenerateGroupPolicy TEXTEQU <__imp_GenerateGroupPolicy>
extern __imp_ProcessGroupPolicy:PANYARGS
ProcessGroupPolicy TEXTEQU <__imp_ProcessGroupPolicy>
extern __imp_ProcessGroupPolicyEx:PANYARGS
ProcessGroupPolicyEx TEXTEQU <__imp_ProcessGroupPolicyEx>
extern __imp_ProcessGroupPolicyForZoneMap:PANYARGS
ProcessGroupPolicyForZoneMap TEXTEQU <__imp_ProcessGroupPolicyForZoneMap>
extern __imp_BrandCleanInstallStubs:PANYARGS
BrandCleanInstallStubs TEXTEQU <__imp_BrandCleanInstallStubs>
extern __imp_BrandICW:PANYARGS
BrandICW TEXTEQU <__imp_BrandICW>
extern __imp_BrandICW2:PANYARGS
BrandICW2 TEXTEQU <__imp_BrandICW2>
extern __imp_BrandIE4:PANYARGS
BrandIE4 TEXTEQU <__imp_BrandIE4>
extern __imp_BrandInfAndOutlookExpress:PANYARGS
BrandInfAndOutlookExpress TEXTEQU <__imp_BrandInfAndOutlookExpress>
extern __imp_BrandInternetExplorer:PANYARGS
BrandInternetExplorer TEXTEQU <__imp_BrandInternetExplorer>
extern __imp_BrandIntra:PANYARGS
BrandIntra TEXTEQU <__imp_BrandIntra>
extern __imp_BrandMe:PANYARGS
BrandMe TEXTEQU <__imp_BrandMe>
extern __imp_Clear:PANYARGS
Clear TEXTEQU <__imp_Clear>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_InternetInitializeAutoProxyDll:PANYARGS
InternetInitializeAutoProxyDll TEXTEQU <__imp_InternetInitializeAutoProxyDll>
