extern __imp_IEHardenAdmin:PANYARGS
IEHardenAdmin TEXTEQU <__imp_IEHardenAdmin>
extern __imp_IEHardenAdminNow:PANYARGS
IEHardenAdminNow TEXTEQU <__imp_IEHardenAdminNow>
extern __imp_IEHardenMachineNow:PANYARGS
IEHardenMachineNow TEXTEQU <__imp_IEHardenMachineNow>
extern __imp_IEHardenUser:PANYARGS
IEHardenUser TEXTEQU <__imp_IEHardenUser>
extern __imp_SetFirstHomepage:PANYARGS
SetFirstHomepage TEXTEQU <__imp_SetFirstHomepage>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_FixIE:PANYARGS
FixIE TEXTEQU <__imp_FixIE>
