extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_FInitIMEShare:PANYARGS
FInitIMEShare TEXTEQU <__imp_FInitIMEShare>
extern __imp_EndIMEShare:PANYARGS
EndIMEShare TEXTEQU <__imp_EndIMEShare>
extern __imp_FRefreshStyle:PANYARGS
FRefreshStyle TEXTEQU <__imp_FRefreshStyle>
extern __imp_FSupportSty:PANYARGS
FSupportSty TEXTEQU <__imp_FSupportSty>
extern __imp_PIMEStyleFromAttr:PANYARGS
PIMEStyleFromAttr TEXTEQU <__imp_PIMEStyleFromAttr>
extern __imp_PColorStyleTextFromIMEStyle:PANYARGS
PColorStyleTextFromIMEStyle TEXTEQU <__imp_PColorStyleTextFromIMEStyle>
extern __imp_PColorStyleBackFromIMEStyle:PANYARGS
PColorStyleBackFromIMEStyle TEXTEQU <__imp_PColorStyleBackFromIMEStyle>
extern __imp_FBoldIMEStyle:PANYARGS
FBoldIMEStyle TEXTEQU <__imp_FBoldIMEStyle>
extern __imp_FItalicIMEStyle:PANYARGS
FItalicIMEStyle TEXTEQU <__imp_FItalicIMEStyle>
extern __imp_FUlIMEStyle:PANYARGS
FUlIMEStyle TEXTEQU <__imp_FUlIMEStyle>
extern __imp_GrfStyIMEStyle:PANYARGS
GrfStyIMEStyle TEXTEQU <__imp_GrfStyIMEStyle>
extern __imp_IdUlIMEStyle:PANYARGS
IdUlIMEStyle TEXTEQU <__imp_IdUlIMEStyle>
extern __imp_FGetIMEStyleAttr:PANYARGS
FGetIMEStyleAttr TEXTEQU <__imp_FGetIMEStyleAttr>
extern __imp_FSetIMEStyleAttr:PANYARGS
FSetIMEStyleAttr TEXTEQU <__imp_FSetIMEStyleAttr>
extern __imp_FWinIMEColorStyle:PANYARGS
FWinIMEColorStyle TEXTEQU <__imp_FWinIMEColorStyle>
extern __imp_FFundamentalIMEColorStyle:PANYARGS
FFundamentalIMEColorStyle TEXTEQU <__imp_FFundamentalIMEColorStyle>
extern __imp_FRGBIMEColorStyle:PANYARGS
FRGBIMEColorStyle TEXTEQU <__imp_FRGBIMEColorStyle>
extern __imp_FSpecialIMEColorStyle:PANYARGS
FSpecialIMEColorStyle TEXTEQU <__imp_FSpecialIMEColorStyle>
extern __imp_IdSpecialFromIMEColorStyle:PANYARGS
IdSpecialFromIMEColorStyle TEXTEQU <__imp_IdSpecialFromIMEColorStyle>
extern __imp_IdWinFromIMEColorStyle:PANYARGS
IdWinFromIMEColorStyle TEXTEQU <__imp_IdWinFromIMEColorStyle>
extern __imp_IdFundamentalFromIMEColorStyle:PANYARGS
IdFundamentalFromIMEColorStyle TEXTEQU <__imp_IdFundamentalFromIMEColorStyle>
extern __imp_RGBFromIMEColorStyle:PANYARGS
RGBFromIMEColorStyle TEXTEQU <__imp_RGBFromIMEColorStyle>
extern __imp_FSetIMEColorStyle:PANYARGS
FSetIMEColorStyle TEXTEQU <__imp_FSetIMEColorStyle>
extern __imp_FSetIMEStyle:PANYARGS
FSetIMEStyle TEXTEQU <__imp_FSetIMEStyle>
extern __imp_FSpecialTextIMEColorStyle:PANYARGS
FSpecialTextIMEColorStyle TEXTEQU <__imp_FSpecialTextIMEColorStyle>
extern __imp_FSpecialWindowIMEColorStyle:PANYARGS
FSpecialWindowIMEColorStyle TEXTEQU <__imp_FSpecialWindowIMEColorStyle>
extern __imp_CustomizeIMEShare:PANYARGS
CustomizeIMEShare TEXTEQU <__imp_CustomizeIMEShare>
extern __imp_FSaveIMEShareSetting:PANYARGS
FSaveIMEShareSetting TEXTEQU <__imp_FSaveIMEShareSetting>
extern __imp_PIMEShareCreate:PANYARGS
PIMEShareCreate TEXTEQU <__imp_PIMEShareCreate>
