extern __imp_ComputeInvCMAP:PANYARGS
ComputeInvCMAP TEXTEQU <__imp_ComputeInvCMAP>
extern __imp_CreateDDrawSurfaceOnDIB:PANYARGS
CreateDDrawSurfaceOnDIB TEXTEQU <__imp_CreateDDrawSurfaceOnDIB>
extern __imp_CreateMIMEMap:PANYARGS
CreateMIMEMap TEXTEQU <__imp_CreateMIMEMap>
extern __imp_DecodeImage:PANYARGS
DecodeImage TEXTEQU <__imp_DecodeImage>
extern __imp_DitherTo8:PANYARGS
DitherTo8 TEXTEQU <__imp_DitherTo8>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetMaxMIMEIDBytes:PANYARGS
GetMaxMIMEIDBytes TEXTEQU <__imp_GetMaxMIMEIDBytes>
extern __imp_IdentifyMIMEType:PANYARGS
IdentifyMIMEType TEXTEQU <__imp_IdentifyMIMEType>
extern __imp_SniffStream:PANYARGS
SniffStream TEXTEQU <__imp_SniffStream>
