extern __imp_CtfAImmActivate:PANYARGS
CtfAImmActivate TEXTEQU <__imp_CtfAImmActivate>
extern __imp_CtfAImmDeactivate:PANYARGS
CtfAImmDeactivate TEXTEQU <__imp_CtfAImmDeactivate>
extern __imp_CtfAImmIsIME:PANYARGS
CtfAImmIsIME TEXTEQU <__imp_CtfAImmIsIME>
extern __imp_CtfImmCoUninitialize:PANYARGS
CtfImmCoUninitialize TEXTEQU <__imp_CtfImmCoUninitialize>
extern __imp_CtfImmDispatchDefImeMessage:PANYARGS
CtfImmDispatchDefImeMessage TEXTEQU <__imp_CtfImmDispatchDefImeMessage>
extern __imp_CtfImmEnterCoInitCountSkipMode:PANYARGS
CtfImmEnterCoInitCountSkipMode TEXTEQU <__imp_CtfImmEnterCoInitCountSkipMode>
extern __imp_CtfImmGenerateMessage:PANYARGS
CtfImmGenerateMessage TEXTEQU <__imp_CtfImmGenerateMessage>
extern __imp_CtfImmGetGuidAtom:PANYARGS
CtfImmGetGuidAtom TEXTEQU <__imp_CtfImmGetGuidAtom>
extern __imp_CtfImmHideToolbarWnd:PANYARGS
CtfImmHideToolbarWnd TEXTEQU <__imp_CtfImmHideToolbarWnd>
extern __imp_CtfImmIsCiceroEnabled:PANYARGS
CtfImmIsCiceroEnabled TEXTEQU <__imp_CtfImmIsCiceroEnabled>
extern __imp_CtfImmIsCiceroStartedInThread:PANYARGS
CtfImmIsCiceroStartedInThread TEXTEQU <__imp_CtfImmIsCiceroStartedInThread>
extern __imp_CtfImmIsGuidMapEnable:PANYARGS
CtfImmIsGuidMapEnable TEXTEQU <__imp_CtfImmIsGuidMapEnable>
extern __imp_CtfImmIsTextFrameServiceDisabled:PANYARGS
CtfImmIsTextFrameServiceDisabled TEXTEQU <__imp_CtfImmIsTextFrameServiceDisabled>
extern __imp_CtfImmLastEnabledWndDestroy:PANYARGS
CtfImmLastEnabledWndDestroy TEXTEQU <__imp_CtfImmLastEnabledWndDestroy>
extern __imp_CtfImmLeaveCoInitCountSkipMode:PANYARGS
CtfImmLeaveCoInitCountSkipMode TEXTEQU <__imp_CtfImmLeaveCoInitCountSkipMode>
extern __imp_CtfImmRestoreToolbarWnd:PANYARGS
CtfImmRestoreToolbarWnd TEXTEQU <__imp_CtfImmRestoreToolbarWnd>
extern __imp_CtfImmSetAppCompatFlags:PANYARGS
CtfImmSetAppCompatFlags TEXTEQU <__imp_CtfImmSetAppCompatFlags>
extern __imp_CtfImmSetCiceroStartInThread:PANYARGS
CtfImmSetCiceroStartInThread TEXTEQU <__imp_CtfImmSetCiceroStartInThread>
extern __imp_CtfImmTIMActivate:PANYARGS
CtfImmTIMActivate TEXTEQU <__imp_CtfImmTIMActivate>
extern __imp_GetKeyboardLayoutCP:PANYARGS
GetKeyboardLayoutCP TEXTEQU <__imp_GetKeyboardLayoutCP>
extern __imp_ImmActivateLayout:PANYARGS
ImmActivateLayout TEXTEQU <__imp_ImmActivateLayout>
extern __imp_ImmAssociateContext:PANYARGS
ImmAssociateContext TEXTEQU <__imp_ImmAssociateContext>
extern __imp_ImmAssociateContextEx:PANYARGS
ImmAssociateContextEx TEXTEQU <__imp_ImmAssociateContextEx>
extern __imp_ImmCallImeConsoleIME:PANYARGS
ImmCallImeConsoleIME TEXTEQU <__imp_ImmCallImeConsoleIME>
extern __imp_ImmConfigureIMEA:PANYARGS
ImmConfigureIME  TEXTEQU <__imp_ImmConfigureIMEA>
extern __imp_ImmConfigureIMEW:PANYARGS
ImmConfigureIMEW TEXTEQU <__imp_ImmConfigureIMEW>
extern __imp_ImmCreateContext:PANYARGS
ImmCreateContext TEXTEQU <__imp_ImmCreateContext>
extern __imp_ImmCreateIMCC:PANYARGS
ImmCreateIMCC TEXTEQU <__imp_ImmCreateIMCC>
extern __imp_ImmCreateSoftKeyboard:PANYARGS
ImmCreateSoftKeyboard TEXTEQU <__imp_ImmCreateSoftKeyboard>
extern __imp_ImmDestroyContext:PANYARGS
ImmDestroyContext TEXTEQU <__imp_ImmDestroyContext>
extern __imp_ImmDestroyIMCC:PANYARGS
ImmDestroyIMCC TEXTEQU <__imp_ImmDestroyIMCC>
extern __imp_ImmDestroySoftKeyboard:PANYARGS
ImmDestroySoftKeyboard TEXTEQU <__imp_ImmDestroySoftKeyboard>
extern __imp_ImmDisableIME:PANYARGS
ImmDisableIME TEXTEQU <__imp_ImmDisableIME>
extern __imp_ImmDisableIme:PANYARGS
ImmDisableIme TEXTEQU <__imp_ImmDisableIme>
extern __imp_ImmDisableTextFrameService:PANYARGS
ImmDisableTextFrameService TEXTEQU <__imp_ImmDisableTextFrameService>
extern __imp_ImmEnumInputContext:PANYARGS
ImmEnumInputContext TEXTEQU <__imp_ImmEnumInputContext>
extern __imp_ImmEnumRegisterWordA:PANYARGS
ImmEnumRegisterWord  TEXTEQU <__imp_ImmEnumRegisterWordA>
extern __imp_ImmEnumRegisterWordW:PANYARGS
ImmEnumRegisterWordW TEXTEQU <__imp_ImmEnumRegisterWordW>
extern __imp_ImmEscapeA:PANYARGS
ImmEscape  TEXTEQU <__imp_ImmEscapeA>
extern __imp_ImmEscapeW:PANYARGS
ImmEscapeW TEXTEQU <__imp_ImmEscapeW>
extern __imp_ImmFreeLayout:PANYARGS
ImmFreeLayout TEXTEQU <__imp_ImmFreeLayout>
extern __imp_ImmGenerateMessage:PANYARGS
ImmGenerateMessage TEXTEQU <__imp_ImmGenerateMessage>
extern __imp_ImmGetAppCompatFlags:PANYARGS
ImmGetAppCompatFlags TEXTEQU <__imp_ImmGetAppCompatFlags>
extern __imp_ImmGetCandidateListA:PANYARGS
ImmGetCandidateList  TEXTEQU <__imp_ImmGetCandidateListA>
extern __imp_ImmGetCandidateListCountA:PANYARGS
ImmGetCandidateListCount  TEXTEQU <__imp_ImmGetCandidateListCountA>
extern __imp_ImmGetCandidateListCountW:PANYARGS
ImmGetCandidateListCountW TEXTEQU <__imp_ImmGetCandidateListCountW>
extern __imp_ImmGetCandidateListW:PANYARGS
ImmGetCandidateListW TEXTEQU <__imp_ImmGetCandidateListW>
extern __imp_ImmGetCandidateWindow:PANYARGS
ImmGetCandidateWindow TEXTEQU <__imp_ImmGetCandidateWindow>
extern __imp_ImmGetCompositionFontA:PANYARGS
ImmGetCompositionFont  TEXTEQU <__imp_ImmGetCompositionFontA>
extern __imp_ImmGetCompositionFontW:PANYARGS
ImmGetCompositionFontW TEXTEQU <__imp_ImmGetCompositionFontW>
extern __imp_ImmGetCompositionStringA:PANYARGS
ImmGetCompositionString  TEXTEQU <__imp_ImmGetCompositionStringA>
extern __imp_ImmGetCompositionStringW:PANYARGS
ImmGetCompositionStringW TEXTEQU <__imp_ImmGetCompositionStringW>
extern __imp_ImmGetCompositionWindow:PANYARGS
ImmGetCompositionWindow TEXTEQU <__imp_ImmGetCompositionWindow>
extern __imp_ImmGetContext:PANYARGS
ImmGetContext TEXTEQU <__imp_ImmGetContext>
extern __imp_ImmGetConversionListA:PANYARGS
ImmGetConversionList  TEXTEQU <__imp_ImmGetConversionListA>
extern __imp_ImmGetConversionListW:PANYARGS
ImmGetConversionListW TEXTEQU <__imp_ImmGetConversionListW>
extern __imp_ImmGetConversionStatus:PANYARGS
ImmGetConversionStatus TEXTEQU <__imp_ImmGetConversionStatus>
extern __imp_ImmGetDefaultIMEWnd:PANYARGS
ImmGetDefaultIMEWnd TEXTEQU <__imp_ImmGetDefaultIMEWnd>
extern __imp_ImmGetDescriptionA:PANYARGS
ImmGetDescription  TEXTEQU <__imp_ImmGetDescriptionA>
extern __imp_ImmGetDescriptionW:PANYARGS
ImmGetDescriptionW TEXTEQU <__imp_ImmGetDescriptionW>
extern __imp_ImmGetGuideLineA:PANYARGS
ImmGetGuideLine  TEXTEQU <__imp_ImmGetGuideLineA>
extern __imp_ImmGetGuideLineW:PANYARGS
ImmGetGuideLineW TEXTEQU <__imp_ImmGetGuideLineW>
extern __imp_ImmGetHotKey:PANYARGS
ImmGetHotKey TEXTEQU <__imp_ImmGetHotKey>
extern __imp_ImmGetIMCCLockCount:PANYARGS
ImmGetIMCCLockCount TEXTEQU <__imp_ImmGetIMCCLockCount>
extern __imp_ImmGetIMCCSize:PANYARGS
ImmGetIMCCSize TEXTEQU <__imp_ImmGetIMCCSize>
extern __imp_ImmGetIMCLockCount:PANYARGS
ImmGetIMCLockCount TEXTEQU <__imp_ImmGetIMCLockCount>
extern __imp_ImmGetIMEFileNameA:PANYARGS
ImmGetIMEFileName  TEXTEQU <__imp_ImmGetIMEFileNameA>
extern __imp_ImmGetIMEFileNameW:PANYARGS
ImmGetIMEFileNameW TEXTEQU <__imp_ImmGetIMEFileNameW>
extern __imp_ImmGetImeInfoEx:PANYARGS
ImmGetImeInfoEx TEXTEQU <__imp_ImmGetImeInfoEx>
extern __imp_ImmGetImeMenuItemsA:PANYARGS
ImmGetImeMenuItems  TEXTEQU <__imp_ImmGetImeMenuItemsA>
extern __imp_ImmGetImeMenuItemsW:PANYARGS
ImmGetImeMenuItemsW TEXTEQU <__imp_ImmGetImeMenuItemsW>
extern __imp_ImmGetOpenStatus:PANYARGS
ImmGetOpenStatus TEXTEQU <__imp_ImmGetOpenStatus>
extern __imp_ImmGetProperty:PANYARGS
ImmGetProperty TEXTEQU <__imp_ImmGetProperty>
extern __imp_ImmGetRegisterWordStyleA:PANYARGS
ImmGetRegisterWordStyle  TEXTEQU <__imp_ImmGetRegisterWordStyleA>
extern __imp_ImmGetRegisterWordStyleW:PANYARGS
ImmGetRegisterWordStyleW TEXTEQU <__imp_ImmGetRegisterWordStyleW>
extern __imp_ImmGetStatusWindowPos:PANYARGS
ImmGetStatusWindowPos TEXTEQU <__imp_ImmGetStatusWindowPos>
extern __imp_ImmGetVirtualKey:PANYARGS
ImmGetVirtualKey TEXTEQU <__imp_ImmGetVirtualKey>
extern __imp_ImmIMPGetIMEA:PANYARGS
ImmIMPGetIME  TEXTEQU <__imp_ImmIMPGetIMEA>
extern __imp_ImmIMPGetIMEW:PANYARGS
ImmIMPGetIMEW TEXTEQU <__imp_ImmIMPGetIMEW>
extern __imp_ImmIMPQueryIMEA:PANYARGS
ImmIMPQueryIME  TEXTEQU <__imp_ImmIMPQueryIMEA>
extern __imp_ImmIMPQueryIMEW:PANYARGS
ImmIMPQueryIMEW TEXTEQU <__imp_ImmIMPQueryIMEW>
extern __imp_ImmIMPSetIMEA:PANYARGS
ImmIMPSetIME  TEXTEQU <__imp_ImmIMPSetIMEA>
extern __imp_ImmIMPSetIMEW:PANYARGS
ImmIMPSetIMEW TEXTEQU <__imp_ImmIMPSetIMEW>
extern __imp_ImmInstallIMEA:PANYARGS
ImmInstallIME  TEXTEQU <__imp_ImmInstallIMEA>
extern __imp_ImmInstallIMEW:PANYARGS
ImmInstallIMEW TEXTEQU <__imp_ImmInstallIMEW>
extern __imp_ImmIsIME:PANYARGS
ImmIsIME TEXTEQU <__imp_ImmIsIME>
extern __imp_ImmIsUIMessageA:PANYARGS
ImmIsUIMessage  TEXTEQU <__imp_ImmIsUIMessageA>
extern __imp_ImmIsUIMessageW:PANYARGS
ImmIsUIMessageW TEXTEQU <__imp_ImmIsUIMessageW>
extern __imp_ImmLoadIME:PANYARGS
ImmLoadIME TEXTEQU <__imp_ImmLoadIME>
extern __imp_ImmLoadLayout:PANYARGS
ImmLoadLayout TEXTEQU <__imp_ImmLoadLayout>
extern __imp_ImmLockClientImc:PANYARGS
ImmLockClientImc TEXTEQU <__imp_ImmLockClientImc>
extern __imp_ImmLockIMC:PANYARGS
ImmLockIMC TEXTEQU <__imp_ImmLockIMC>
extern __imp_ImmLockIMCC:PANYARGS
ImmLockIMCC TEXTEQU <__imp_ImmLockIMCC>
extern __imp_ImmLockImeDpi:PANYARGS
ImmLockImeDpi TEXTEQU <__imp_ImmLockImeDpi>
extern __imp_ImmNotifyIME:PANYARGS
ImmNotifyIME TEXTEQU <__imp_ImmNotifyIME>
extern __imp_ImmProcessKey:PANYARGS
ImmProcessKey TEXTEQU <__imp_ImmProcessKey>
extern __imp_ImmPutImeMenuItemsIntoMappedFile:PANYARGS
ImmPutImeMenuItemsIntoMappedFile TEXTEQU <__imp_ImmPutImeMenuItemsIntoMappedFile>
extern __imp_ImmReSizeIMCC:PANYARGS
ImmReSizeIMCC TEXTEQU <__imp_ImmReSizeIMCC>
extern __imp_ImmRegisterClient:PANYARGS
ImmRegisterClient TEXTEQU <__imp_ImmRegisterClient>
extern __imp_ImmRegisterWordA:PANYARGS
ImmRegisterWord  TEXTEQU <__imp_ImmRegisterWordA>
extern __imp_ImmRegisterWordW:PANYARGS
ImmRegisterWordW TEXTEQU <__imp_ImmRegisterWordW>
extern __imp_ImmReleaseContext:PANYARGS
ImmReleaseContext TEXTEQU <__imp_ImmReleaseContext>
extern __imp_ImmRequestMessageA:PANYARGS
ImmRequestMessage  TEXTEQU <__imp_ImmRequestMessageA>
extern __imp_ImmRequestMessageW:PANYARGS
ImmRequestMessageW TEXTEQU <__imp_ImmRequestMessageW>
extern __imp_ImmSendIMEMessageExA:PANYARGS
ImmSendIMEMessageEx  TEXTEQU <__imp_ImmSendIMEMessageExA>
extern __imp_ImmSendIMEMessageExW:PANYARGS
ImmSendIMEMessageExW TEXTEQU <__imp_ImmSendIMEMessageExW>
extern __imp_ImmSetActiveContext:PANYARGS
ImmSetActiveContext TEXTEQU <__imp_ImmSetActiveContext>
extern __imp_ImmSetActiveContextConsoleIME:PANYARGS
ImmSetActiveContextConsoleIME TEXTEQU <__imp_ImmSetActiveContextConsoleIME>
extern __imp_ImmSetCandidateWindow:PANYARGS
ImmSetCandidateWindow TEXTEQU <__imp_ImmSetCandidateWindow>
extern __imp_ImmSetCompositionFontA:PANYARGS
ImmSetCompositionFont  TEXTEQU <__imp_ImmSetCompositionFontA>
extern __imp_ImmSetCompositionFontW:PANYARGS
ImmSetCompositionFontW TEXTEQU <__imp_ImmSetCompositionFontW>
extern __imp_ImmSetCompositionStringA:PANYARGS
ImmSetCompositionString  TEXTEQU <__imp_ImmSetCompositionStringA>
extern __imp_ImmSetCompositionStringW:PANYARGS
ImmSetCompositionStringW TEXTEQU <__imp_ImmSetCompositionStringW>
extern __imp_ImmSetCompositionWindow:PANYARGS
ImmSetCompositionWindow TEXTEQU <__imp_ImmSetCompositionWindow>
extern __imp_ImmSetConversionStatus:PANYARGS
ImmSetConversionStatus TEXTEQU <__imp_ImmSetConversionStatus>
extern __imp_ImmSetHotKey:PANYARGS
ImmSetHotKey TEXTEQU <__imp_ImmSetHotKey>
extern __imp_ImmSetOpenStatus:PANYARGS
ImmSetOpenStatus TEXTEQU <__imp_ImmSetOpenStatus>
extern __imp_ImmSetStatusWindowPos:PANYARGS
ImmSetStatusWindowPos TEXTEQU <__imp_ImmSetStatusWindowPos>
extern __imp_ImmShowSoftKeyboard:PANYARGS
ImmShowSoftKeyboard TEXTEQU <__imp_ImmShowSoftKeyboard>
extern __imp_ImmSimulateHotKey:PANYARGS
ImmSimulateHotKey TEXTEQU <__imp_ImmSimulateHotKey>
extern __imp_ImmSystemHandler:PANYARGS
ImmSystemHandler TEXTEQU <__imp_ImmSystemHandler>
extern __imp_ImmTranslateMessage:PANYARGS
ImmTranslateMessage TEXTEQU <__imp_ImmTranslateMessage>
extern __imp_ImmUnlockClientImc:PANYARGS
ImmUnlockClientImc TEXTEQU <__imp_ImmUnlockClientImc>
extern __imp_ImmUnlockIMC:PANYARGS
ImmUnlockIMC TEXTEQU <__imp_ImmUnlockIMC>
extern __imp_ImmUnlockIMCC:PANYARGS
ImmUnlockIMCC TEXTEQU <__imp_ImmUnlockIMCC>
extern __imp_ImmUnlockImeDpi:PANYARGS
ImmUnlockImeDpi TEXTEQU <__imp_ImmUnlockImeDpi>
extern __imp_ImmUnregisterWordA:PANYARGS
ImmUnregisterWord  TEXTEQU <__imp_ImmUnregisterWordA>
extern __imp_ImmUnregisterWordW:PANYARGS
ImmUnregisterWordW TEXTEQU <__imp_ImmUnregisterWordW>
extern __imp_ImmWINNLSEnableIME:PANYARGS
ImmWINNLSEnableIME TEXTEQU <__imp_ImmWINNLSEnableIME>
extern __imp_ImmWINNLSGetEnableStatus:PANYARGS
ImmWINNLSGetEnableStatus TEXTEQU <__imp_ImmWINNLSGetEnableStatus>
extern __imp_ImmWINNLSGetIMEHotkey:PANYARGS
ImmWINNLSGetIMEHotkey TEXTEQU <__imp_ImmWINNLSGetIMEHotkey>
