extern __imp_CheckConnectionWizard:PANYARGS
CheckConnectionWizard TEXTEQU <__imp_CheckConnectionWizard>
extern __imp_ConfigureSystemForInternet:PANYARGS
ConfigureSystemForInternet TEXTEQU <__imp_ConfigureSystemForInternet>
extern __imp_ConfigureSystemForInternetA:PANYARGS
ConfigureSystemForInternet  TEXTEQU <__imp_ConfigureSystemForInternetA>
extern __imp_ConfigureSystemForInternetW:PANYARGS
ConfigureSystemForInternetW TEXTEQU <__imp_ConfigureSystemForInternetW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_FreeSignupWizard:PANYARGS
FreeSignupWizard TEXTEQU <__imp_FreeSignupWizard>
extern __imp_InetConfigClient:PANYARGS
InetConfigClient TEXTEQU <__imp_InetConfigClient>
extern __imp_InetConfigClientA:PANYARGS
InetConfigClient  TEXTEQU <__imp_InetConfigClientA>
extern __imp_InetConfigClientW:PANYARGS
InetConfigClientW TEXTEQU <__imp_InetConfigClientW>
extern __imp_InetConfigSystem:PANYARGS
InetConfigSystem TEXTEQU <__imp_InetConfigSystem>
extern __imp_InetConfigSystemFromPath:PANYARGS
InetConfigSystemFromPath TEXTEQU <__imp_InetConfigSystemFromPath>
extern __imp_InetConfigSystemFromPathA:PANYARGS
InetConfigSystemFromPath  TEXTEQU <__imp_InetConfigSystemFromPathA>
extern __imp_InetConfigSystemFromPathW:PANYARGS
InetConfigSystemFromPathW TEXTEQU <__imp_InetConfigSystemFromPathW>
extern __imp_InetGetAutodial:PANYARGS
InetGetAutodial TEXTEQU <__imp_InetGetAutodial>
extern __imp_InetGetAutodialA:PANYARGS
InetGetAutodial  TEXTEQU <__imp_InetGetAutodialA>
extern __imp_InetGetAutodialW:PANYARGS
InetGetAutodialW TEXTEQU <__imp_InetGetAutodialW>
extern __imp_InetGetClientInfo:PANYARGS
InetGetClientInfo TEXTEQU <__imp_InetGetClientInfo>
extern __imp_InetGetClientInfoA:PANYARGS
InetGetClientInfo  TEXTEQU <__imp_InetGetClientInfoA>
extern __imp_InetGetClientInfoW:PANYARGS
InetGetClientInfoW TEXTEQU <__imp_InetGetClientInfoW>
extern __imp_InetGetProxy:PANYARGS
InetGetProxy TEXTEQU <__imp_InetGetProxy>
extern __imp_InetGetProxyA:PANYARGS
InetGetProxy  TEXTEQU <__imp_InetGetProxyA>
extern __imp_InetGetProxyW:PANYARGS
InetGetProxyW TEXTEQU <__imp_InetGetProxyW>
extern __imp_InetNeedModem:PANYARGS
InetNeedModem TEXTEQU <__imp_InetNeedModem>
extern __imp_InetNeedSystemComponents:PANYARGS
InetNeedSystemComponents TEXTEQU <__imp_InetNeedSystemComponents>
extern __imp_InetPerformSecurityCheck:PANYARGS
InetPerformSecurityCheck TEXTEQU <__imp_InetPerformSecurityCheck>
extern __imp_InetSetAutodial:PANYARGS
InetSetAutodial TEXTEQU <__imp_InetSetAutodial>
extern __imp_InetSetAutodialA:PANYARGS
InetSetAutodial  TEXTEQU <__imp_InetSetAutodialA>
extern __imp_InetSetAutodialW:PANYARGS
InetSetAutodialW TEXTEQU <__imp_InetSetAutodialW>
extern __imp_InetSetClientInfo:PANYARGS
InetSetClientInfo TEXTEQU <__imp_InetSetClientInfo>
extern __imp_InetSetClientInfoA:PANYARGS
InetSetClientInfo  TEXTEQU <__imp_InetSetClientInfoA>
extern __imp_InetSetClientInfoW:PANYARGS
InetSetClientInfoW TEXTEQU <__imp_InetSetClientInfoW>
extern __imp_InetSetProxy:PANYARGS
InetSetProxy TEXTEQU <__imp_InetSetProxy>
extern __imp_InetSetProxyA:PANYARGS
InetSetProxy  TEXTEQU <__imp_InetSetProxyA>
extern __imp_InetSetProxyEx:PANYARGS
InetSetProxyEx TEXTEQU <__imp_InetSetProxyEx>
extern __imp_InetSetProxyExA:PANYARGS
InetSetProxyEx  TEXTEQU <__imp_InetSetProxyExA>
extern __imp_InetSetProxyExW:PANYARGS
InetSetProxyExW TEXTEQU <__imp_InetSetProxyExW>
extern __imp_InetSetProxyW:PANYARGS
InetSetProxyW TEXTEQU <__imp_InetSetProxyW>
extern __imp_InetStartServices:PANYARGS
InetStartServices TEXTEQU <__imp_InetStartServices>
extern __imp_IsSmartStart:PANYARGS
IsSmartStart TEXTEQU <__imp_IsSmartStart>
extern __imp_IsSmartStartEx:PANYARGS
IsSmartStartEx TEXTEQU <__imp_IsSmartStartEx>
extern __imp_LaunchSignupWizard:PANYARGS
LaunchSignupWizard TEXTEQU <__imp_LaunchSignupWizard>
extern __imp_LaunchSignupWizardEx:PANYARGS
LaunchSignupWizardEx TEXTEQU <__imp_LaunchSignupWizardEx>
extern __imp_SetAutoProxyConnectoid:PANYARGS
SetAutoProxyConnectoid TEXTEQU <__imp_SetAutoProxyConnectoid>
extern __imp_SetInternetPhoneNumber:PANYARGS
SetInternetPhoneNumber TEXTEQU <__imp_SetInternetPhoneNumber>
extern __imp_SetInternetPhoneNumberA:PANYARGS
SetInternetPhoneNumber  TEXTEQU <__imp_SetInternetPhoneNumberA>
extern __imp_SetInternetPhoneNumberW:PANYARGS
SetInternetPhoneNumberW TEXTEQU <__imp_SetInternetPhoneNumberW>
extern __imp_SetShellNext:PANYARGS
SetShellNext TEXTEQU <__imp_SetShellNext>
extern __imp_SetShellNextA:PANYARGS
SetShellNext  TEXTEQU <__imp_SetShellNextA>
extern __imp_SetShellNextW:PANYARGS
SetShellNextW TEXTEQU <__imp_SetShellNextW>
extern __imp__LaunchSignupWizardEx:PANYARGS
_LaunchSignupWizardEx TEXTEQU <__imp__LaunchSignupWizardEx>
