extern __imp_IIapp:PANYARGS
IIapp TEXTEQU <__imp_IIapp>
extern __imp_IIapp_mem:PANYARGS
IIapp_mem TEXTEQU <__imp_IIapp_mem>
extern __imp_IIbuf:PANYARGS
IIbuf TEXTEQU <__imp_IIbuf>
extern __imp_IIbuf_mem:PANYARGS
IIbuf_mem TEXTEQU <__imp_IIbuf_mem>
extern __imp_IIdb:PANYARGS
IIdb TEXTEQU <__imp_IIdb>
extern __imp_IIdb_mem:PANYARGS
IIdb_mem TEXTEQU <__imp_IIdb_mem>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_IIword:PANYARGS
IIword TEXTEQU <__imp_IIword>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_IIGetAppElem:PANYARGS
IIGetAppElem TEXTEQU <__imp_IIGetAppElem>
extern __imp_IIdiagoff:PANYARGS
IIdiagoff TEXTEQU <__imp_IIdiagoff>
extern __imp_IIGetFM:PANYARGS
IIGetFM TEXTEQU <__imp_IIGetFM>
extern __imp_IIdiagon:PANYARGS
IIdiagon TEXTEQU <__imp_IIdiagon>
extern __imp_NTFMClose:PANYARGS
NTFMClose TEXTEQU <__imp_NTFMClose>
extern __imp_NTFMCompare:PANYARGS
NTFMCompare TEXTEQU <__imp_NTFMCompare>
extern __imp_NTFMCopy:PANYARGS
NTFMCopy TEXTEQU <__imp_NTFMCopy>
extern __imp_NTFMCreate:PANYARGS
NTFMCreate TEXTEQU <__imp_NTFMCreate>
extern __imp_NTFMDelete:PANYARGS
NTFMDelete TEXTEQU <__imp_NTFMDelete>
extern __imp_NTFMDestruct:PANYARGS
NTFMDestruct TEXTEQU <__imp_NTFMDestruct>
extern __imp_NTFMFlushMapping:PANYARGS
NTFMFlushMapping TEXTEQU <__imp_NTFMFlushMapping>
extern __imp_NTFMGetDirtyBit:PANYARGS
NTFMGetDirtyBit TEXTEQU <__imp_NTFMGetDirtyBit>
extern __imp_NTFMGetLength:PANYARGS
NTFMGetLength TEXTEQU <__imp_NTFMGetLength>
extern __imp_NTFMGetMapHandle:PANYARGS
NTFMGetMapHandle TEXTEQU <__imp_NTFMGetMapHandle>
extern __imp_NTFMGetMapping:PANYARGS
NTFMGetMapping TEXTEQU <__imp_NTFMGetMapping>
extern __imp_NTFMGetName:PANYARGS
NTFMGetName TEXTEQU <__imp_NTFMGetName>
extern __imp_NTFMGetPosition:PANYARGS
NTFMGetPosition TEXTEQU <__imp_NTFMGetPosition>
extern __imp_NTFMGetStatus:PANYARGS
NTFMGetStatus TEXTEQU <__imp_NTFMGetStatus>
extern __imp_NTFMLockMapping:PANYARGS
NTFMLockMapping TEXTEQU <__imp_NTFMLockMapping>
extern __imp_NTFMOpen:PANYARGS
NTFMOpen TEXTEQU <__imp_NTFMOpen>
extern __imp_NTFMRead:PANYARGS
NTFMRead TEXTEQU <__imp_NTFMRead>
extern __imp_NTFMReleaseMapHandle:PANYARGS
NTFMReleaseMapHandle TEXTEQU <__imp_NTFMReleaseMapHandle>
extern __imp_NTFMSeek:PANYARGS
NTFMSeek TEXTEQU <__imp_NTFMSeek>
extern __imp_NTFMSetDirtyBit:PANYARGS
NTFMSetDirtyBit TEXTEQU <__imp_NTFMSetDirtyBit>
extern __imp_NTFMSetLength:PANYARGS
NTFMSetLength TEXTEQU <__imp_NTFMSetLength>
extern __imp_NTFMSetMapping:PANYARGS
NTFMSetMapping TEXTEQU <__imp_NTFMSetMapping>
extern __imp_NTFMSetMutexProc:PANYARGS
NTFMSetMutexProc TEXTEQU <__imp_NTFMSetMutexProc>
extern __imp_NTFMSetName:PANYARGS
NTFMSetName TEXTEQU <__imp_NTFMSetName>
extern __imp_NTFMUnlockMapping:PANYARGS
NTFMUnlockMapping TEXTEQU <__imp_NTFMUnlockMapping>
extern __imp_NTFMWrite:PANYARGS
NTFMWrite TEXTEQU <__imp_NTFMWrite>
