extern __imp_CPlApplet:PANYARGS
CPlApplet TEXTEQU <__imp_CPlApplet>
extern __imp_input_ordinal101:PANYARGS
input_ordinal101 TEXTEQU <__imp_input_ordinal101>
extern __imp_input_ordinal102:PANYARGS
input_ordinal102 TEXTEQU <__imp_input_ordinal102>
extern __imp_input_ordinal103:PANYARGS
input_ordinal103 TEXTEQU <__imp_input_ordinal103>
extern __imp_input_ordinal104:PANYARGS
input_ordinal104 TEXTEQU <__imp_input_ordinal104>
