extern __imp_CheckForVersionConflict:PANYARGS
CheckForVersionConflict TEXTEQU <__imp_CheckForVersionConflict>
extern __imp_CheckTrust:PANYARGS
CheckTrust TEXTEQU <__imp_CheckTrust>
extern __imp_CheckTrustEx:PANYARGS
CheckTrustEx TEXTEQU <__imp_CheckTrustEx>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_DownloadFile:PANYARGS
DownloadFile TEXTEQU <__imp_DownloadFile>
extern __imp_GetICifFileFromFile:PANYARGS
GetICifFileFromFile TEXTEQU <__imp_GetICifFileFromFile>
extern __imp_GetICifRWFileFromFile:PANYARGS
GetICifRWFileFromFile TEXTEQU <__imp_GetICifRWFileFromFile>
extern __imp_PurgeDownloadDirectory:PANYARGS
PurgeDownloadDirectory TEXTEQU <__imp_PurgeDownloadDirectory>
