extern __imp_FmtIdToPropStgName:PANYARGS
FmtIdToPropStgName TEXTEQU <__imp_FmtIdToPropStgName>
extern __imp_FreePropVariantArray:PANYARGS
FreePropVariantArray TEXTEQU <__imp_FreePropVariantArray>
extern __imp_PropStgNameToFmtId:PANYARGS
PropStgNameToFmtId TEXTEQU <__imp_PropStgNameToFmtId>
extern __imp_PropVariantClear:PANYARGS
PropVariantClear TEXTEQU <__imp_PropVariantClear>
extern __imp_PropVariantCopy:PANYARGS
PropVariantCopy TEXTEQU <__imp_PropVariantCopy>
extern __imp_StgCreatePropSetStg:PANYARGS
StgCreatePropSetStg TEXTEQU <__imp_StgCreatePropSetStg>
extern __imp_StgCreatePropStg:PANYARGS
StgCreatePropStg TEXTEQU <__imp_StgCreatePropStg>
extern __imp_StgOpenPropStg:PANYARGS
StgOpenPropStg TEXTEQU <__imp_StgOpenPropStg>
