extern __imp_AutoDialLogon:PANYARGS
AutoDialLogon TEXTEQU <__imp_AutoDialLogon>
extern __imp_AutoDialLogonA:PANYARGS
AutoDialLogon  TEXTEQU <__imp_AutoDialLogonA>
extern __imp_AutoDialLogonW:PANYARGS
AutoDialLogonW TEXTEQU <__imp_AutoDialLogonW>
extern __imp_AutoDialSignup:PANYARGS
AutoDialSignup TEXTEQU <__imp_AutoDialSignup>
extern __imp_AutoDialSignupA:PANYARGS
AutoDialSignup  TEXTEQU <__imp_AutoDialSignupA>
extern __imp_AutoDialSignupW:PANYARGS
AutoDialSignupW TEXTEQU <__imp_AutoDialSignupW>
extern __imp_IEAKProcessISP:PANYARGS
IEAKProcessISP TEXTEQU <__imp_IEAKProcessISP>
extern __imp_IEAKProcessISPA:PANYARGS
IEAKProcessISP  TEXTEQU <__imp_IEAKProcessISPA>
extern __imp_IEAKProcessISPW:PANYARGS
IEAKProcessISPW TEXTEQU <__imp_IEAKProcessISPW>
extern __imp_Signup:PANYARGS
Signup TEXTEQU <__imp_Signup>
