extern __imp_JetAddColumn:PANYARGS
JetAddColumn TEXTEQU <__imp_JetAddColumn>
extern __imp_JetAttachDatabase:PANYARGS
JetAttachDatabase TEXTEQU <__imp_JetAttachDatabase>
extern __imp_JetBackup:PANYARGS
JetBackup TEXTEQU <__imp_JetBackup>
extern __imp_JetBeginExternalBackup:PANYARGS
JetBeginExternalBackup TEXTEQU <__imp_JetBeginExternalBackup>
extern __imp_JetBeginSession:PANYARGS
JetBeginSession TEXTEQU <__imp_JetBeginSession>
extern __imp_JetBeginTransaction:PANYARGS
JetBeginTransaction TEXTEQU <__imp_JetBeginTransaction>
extern __imp_JetCloseDatabase:PANYARGS
JetCloseDatabase TEXTEQU <__imp_JetCloseDatabase>
extern __imp_JetCloseFile:PANYARGS
JetCloseFile TEXTEQU <__imp_JetCloseFile>
extern __imp_JetCloseTable:PANYARGS
JetCloseTable TEXTEQU <__imp_JetCloseTable>
extern __imp_JetCommitTransaction:PANYARGS
JetCommitTransaction TEXTEQU <__imp_JetCommitTransaction>
extern __imp_JetCompact:PANYARGS
JetCompact TEXTEQU <__imp_JetCompact>
extern __imp_JetComputeStats:PANYARGS
JetComputeStats TEXTEQU <__imp_JetComputeStats>
extern __imp_JetCreateDatabase:PANYARGS
JetCreateDatabase TEXTEQU <__imp_JetCreateDatabase>
extern __imp_JetCreateIndex:PANYARGS
JetCreateIndex TEXTEQU <__imp_JetCreateIndex>
extern __imp_JetCreateLink:PANYARGS
JetCreateLink TEXTEQU <__imp_JetCreateLink>
extern __imp_JetCreateQuery:PANYARGS
JetCreateQuery TEXTEQU <__imp_JetCreateQuery>
extern __imp_JetCreateTable:PANYARGS
JetCreateTable TEXTEQU <__imp_JetCreateTable>
extern __imp_JetCreateTableColumnIndex:PANYARGS
JetCreateTableColumnIndex TEXTEQU <__imp_JetCreateTableColumnIndex>
extern __imp_JetDBUtilities:PANYARGS
JetDBUtilities TEXTEQU <__imp_JetDBUtilities>
extern __imp_JetDelete:PANYARGS
JetDelete TEXTEQU <__imp_JetDelete>
extern __imp_JetDeleteColumn:PANYARGS
JetDeleteColumn TEXTEQU <__imp_JetDeleteColumn>
extern __imp_JetDeleteIndex:PANYARGS
JetDeleteIndex TEXTEQU <__imp_JetDeleteIndex>
extern __imp_JetDeleteTable:PANYARGS
JetDeleteTable TEXTEQU <__imp_JetDeleteTable>
extern __imp_JetDetachDatabase:PANYARGS
JetDetachDatabase TEXTEQU <__imp_JetDetachDatabase>
extern __imp_JetDupCursor:PANYARGS
JetDupCursor TEXTEQU <__imp_JetDupCursor>
extern __imp_JetDupSession:PANYARGS
JetDupSession TEXTEQU <__imp_JetDupSession>
extern __imp_JetEndExternalBackup:PANYARGS
JetEndExternalBackup TEXTEQU <__imp_JetEndExternalBackup>
extern __imp_JetEndSession:PANYARGS
JetEndSession TEXTEQU <__imp_JetEndSession>
extern __imp_JetExecuteSql:PANYARGS
JetExecuteSql TEXTEQU <__imp_JetExecuteSql>
extern __imp_JetExternalRestore:PANYARGS
JetExternalRestore TEXTEQU <__imp_JetExternalRestore>
extern __imp_JetGetAttachInfo:PANYARGS
JetGetAttachInfo TEXTEQU <__imp_JetGetAttachInfo>
extern __imp_JetGetBookmark:PANYARGS
JetGetBookmark TEXTEQU <__imp_JetGetBookmark>
extern __imp_JetGetChecksum:PANYARGS
JetGetChecksum TEXTEQU <__imp_JetGetChecksum>
extern __imp_JetGetColumnInfo:PANYARGS
JetGetColumnInfo TEXTEQU <__imp_JetGetColumnInfo>
extern __imp_JetGetCounter:PANYARGS
JetGetCounter TEXTEQU <__imp_JetGetCounter>
extern __imp_JetGetCurrentIndex:PANYARGS
JetGetCurrentIndex TEXTEQU <__imp_JetGetCurrentIndex>
extern __imp_JetGetCursorInfo:PANYARGS
JetGetCursorInfo TEXTEQU <__imp_JetGetCursorInfo>
extern __imp_JetGetDatabaseInfo:PANYARGS
JetGetDatabaseInfo TEXTEQU <__imp_JetGetDatabaseInfo>
extern __imp_JetGetIndexInfo:PANYARGS
JetGetIndexInfo TEXTEQU <__imp_JetGetIndexInfo>
extern __imp_JetGetLogInfo:PANYARGS
JetGetLogInfo TEXTEQU <__imp_JetGetLogInfo>
extern __imp_JetGetObjectInfo:PANYARGS
JetGetObjectInfo TEXTEQU <__imp_JetGetObjectInfo>
extern __imp_JetGetObjidFromName:PANYARGS
JetGetObjidFromName TEXTEQU <__imp_JetGetObjidFromName>
extern __imp_JetGetQueryParameterInfo:PANYARGS
JetGetQueryParameterInfo TEXTEQU <__imp_JetGetQueryParameterInfo>
extern __imp_JetGetRecordPosition:PANYARGS
JetGetRecordPosition TEXTEQU <__imp_JetGetRecordPosition>
extern __imp_JetGetSystemParameter:PANYARGS
JetGetSystemParameter TEXTEQU <__imp_JetGetSystemParameter>
extern __imp_JetGetTableColumnInfo:PANYARGS
JetGetTableColumnInfo TEXTEQU <__imp_JetGetTableColumnInfo>
extern __imp_JetGetTableIndexInfo:PANYARGS
JetGetTableIndexInfo TEXTEQU <__imp_JetGetTableIndexInfo>
extern __imp_JetGetTableInfo:PANYARGS
JetGetTableInfo TEXTEQU <__imp_JetGetTableInfo>
extern __imp_JetGetVersion:PANYARGS
JetGetVersion TEXTEQU <__imp_JetGetVersion>
extern __imp_JetGotoBookmark:PANYARGS
JetGotoBookmark TEXTEQU <__imp_JetGotoBookmark>
extern __imp_JetGotoPosition:PANYARGS
JetGotoPosition TEXTEQU <__imp_JetGotoPosition>
extern __imp_JetIdle:PANYARGS
JetIdle TEXTEQU <__imp_JetIdle>
extern __imp_JetIndexRecordCount:PANYARGS
JetIndexRecordCount TEXTEQU <__imp_JetIndexRecordCount>
extern __imp_JetInit:PANYARGS
JetInit TEXTEQU <__imp_JetInit>
extern __imp_JetMakeKey:PANYARGS
JetMakeKey TEXTEQU <__imp_JetMakeKey>
extern __imp_JetMove:PANYARGS
JetMove TEXTEQU <__imp_JetMove>
extern __imp_JetOpenDatabase:PANYARGS
JetOpenDatabase TEXTEQU <__imp_JetOpenDatabase>
extern __imp_JetOpenFile:PANYARGS
JetOpenFile TEXTEQU <__imp_JetOpenFile>
extern __imp_JetOpenQueryDef:PANYARGS
JetOpenQueryDef TEXTEQU <__imp_JetOpenQueryDef>
extern __imp_JetOpenTable:PANYARGS
JetOpenTable TEXTEQU <__imp_JetOpenTable>
extern __imp_JetOpenTempTable:PANYARGS
JetOpenTempTable TEXTEQU <__imp_JetOpenTempTable>
extern __imp_JetOpenTempTable2:PANYARGS
JetOpenTempTable2 TEXTEQU <__imp_JetOpenTempTable2>
extern __imp_JetPrepareUpdate:PANYARGS
JetPrepareUpdate TEXTEQU <__imp_JetPrepareUpdate>
extern __imp_JetReadFile:PANYARGS
JetReadFile TEXTEQU <__imp_JetReadFile>
extern __imp_JetResetCounter:PANYARGS
JetResetCounter TEXTEQU <__imp_JetResetCounter>
extern __imp_JetRestore:PANYARGS
JetRestore TEXTEQU <__imp_JetRestore>
extern __imp_JetRestore2:PANYARGS
JetRestore2 TEXTEQU <__imp_JetRestore2>
extern __imp_JetRetrieveColumn:PANYARGS
JetRetrieveColumn TEXTEQU <__imp_JetRetrieveColumn>
extern __imp_JetRetrieveColumns:PANYARGS
JetRetrieveColumns TEXTEQU <__imp_JetRetrieveColumns>
extern __imp_JetRetrieveKey:PANYARGS
JetRetrieveKey TEXTEQU <__imp_JetRetrieveKey>
extern __imp_JetRetrieveQoSql:PANYARGS
JetRetrieveQoSql TEXTEQU <__imp_JetRetrieveQoSql>
extern __imp_JetRollback:PANYARGS
JetRollback TEXTEQU <__imp_JetRollback>
extern __imp_JetSeek:PANYARGS
JetSeek TEXTEQU <__imp_JetSeek>
extern __imp_JetSetAccess:PANYARGS
JetSetAccess TEXTEQU <__imp_JetSetAccess>
extern __imp_JetSetColumn:PANYARGS
JetSetColumn TEXTEQU <__imp_JetSetColumn>
extern __imp_JetSetColumns:PANYARGS
JetSetColumns TEXTEQU <__imp_JetSetColumns>
extern __imp_JetSetCurrentIndex:PANYARGS
JetSetCurrentIndex TEXTEQU <__imp_JetSetCurrentIndex>
extern __imp_JetSetCurrentIndex2:PANYARGS
JetSetCurrentIndex2 TEXTEQU <__imp_JetSetCurrentIndex2>
extern __imp_JetSetIndexRange:PANYARGS
JetSetIndexRange TEXTEQU <__imp_JetSetIndexRange>
extern __imp_JetSetQoSql:PANYARGS
JetSetQoSql TEXTEQU <__imp_JetSetQoSql>
extern __imp_JetSetSystemParameter:PANYARGS
JetSetSystemParameter TEXTEQU <__imp_JetSetSystemParameter>
extern __imp_JetTerm:PANYARGS
JetTerm TEXTEQU <__imp_JetTerm>
extern __imp_JetTerm2:PANYARGS
JetTerm2 TEXTEQU <__imp_JetTerm2>
extern __imp_JetTruncateLog:PANYARGS
JetTruncateLog TEXTEQU <__imp_JetTruncateLog>
extern __imp_JetUpdate:PANYARGS
JetUpdate TEXTEQU <__imp_JetUpdate>
