extern __imp_KdD0Transition:PANYARGS
KdD0Transition TEXTEQU <__imp_KdD0Transition>
extern __imp_KdD3Transition:PANYARGS
KdD3Transition TEXTEQU <__imp_KdD3Transition>
extern __imp_KdDebuggerInitialize0:PANYARGS
KdDebuggerInitialize0 TEXTEQU <__imp_KdDebuggerInitialize0>
extern __imp_KdDebuggerInitialize1:PANYARGS
KdDebuggerInitialize1 TEXTEQU <__imp_KdDebuggerInitialize1>
extern __imp_KdReceivePacket:PANYARGS
KdReceivePacket TEXTEQU <__imp_KdReceivePacket>
extern __imp_KdRestore:PANYARGS
KdRestore TEXTEQU <__imp_KdRestore>
extern __imp_KdSave:PANYARGS
KdSave TEXTEQU <__imp_KdSave>
extern __imp_KdSendPacket:PANYARGS
KdSendPacket TEXTEQU <__imp_KdSendPacket>
