extern __imp_SpInitialize:PANYARGS
SpInitialize TEXTEQU <__imp_SpInitialize>
extern __imp_KerbDomainChangeCallback:PANYARGS
KerbDomainChangeCallback TEXTEQU <__imp_KerbDomainChangeCallback>
extern __imp_SpLsaModeInitialize:PANYARGS
SpLsaModeInitialize TEXTEQU <__imp_SpLsaModeInitialize>
extern __imp_SpUserModeInitialize:PANYARGS
SpUserModeInitialize TEXTEQU <__imp_SpUserModeInitialize>
extern __imp_KerbCreateTokenFromTicket:PANYARGS
KerbCreateTokenFromTicket TEXTEQU <__imp_KerbCreateTokenFromTicket>
extern __imp_KerbFree:PANYARGS
KerbFree TEXTEQU <__imp_KerbFree>
extern __imp_KerbIsInitialized:PANYARGS
KerbIsInitialized TEXTEQU <__imp_KerbIsInitialized>
extern __imp_KerbKdcCallBack:PANYARGS
KerbKdcCallBack TEXTEQU <__imp_KerbKdcCallBack>
extern __imp_KerbMakeKdcCall:PANYARGS
KerbMakeKdcCall TEXTEQU <__imp_KerbMakeKdcCall>
extern __imp_kerberos_ordinal10:PANYARGS
kerberos_ordinal10 TEXTEQU <__imp_kerberos_ordinal10>
extern __imp_kerberos_ordinal11:PANYARGS
kerberos_ordinal11 TEXTEQU <__imp_kerberos_ordinal11>
extern __imp_kerberos_ordinal12:PANYARGS
kerberos_ordinal12 TEXTEQU <__imp_kerberos_ordinal12>
extern __imp_kerberos_ordinal13:PANYARGS
kerberos_ordinal13 TEXTEQU <__imp_kerberos_ordinal13>
extern __imp_kerberos_ordinal14:PANYARGS
kerberos_ordinal14 TEXTEQU <__imp_kerberos_ordinal14>
extern __imp_kerberos_ordinal15:PANYARGS
kerberos_ordinal15 TEXTEQU <__imp_kerberos_ordinal15>
extern __imp_kerberos_ordinal16:PANYARGS
kerberos_ordinal16 TEXTEQU <__imp_kerberos_ordinal16>
extern __imp_kerberos_ordinal17:PANYARGS
kerberos_ordinal17 TEXTEQU <__imp_kerberos_ordinal17>
extern __imp_kerberos_ordinal18:PANYARGS
kerberos_ordinal18 TEXTEQU <__imp_kerberos_ordinal18>
extern __imp_kerberos_ordinal19:PANYARGS
kerberos_ordinal19 TEXTEQU <__imp_kerberos_ordinal19>
extern __imp_kerberos_ordinal20:PANYARGS
kerberos_ordinal20 TEXTEQU <__imp_kerberos_ordinal20>
extern __imp_kerberos_ordinal21:PANYARGS
kerberos_ordinal21 TEXTEQU <__imp_kerberos_ordinal21>
extern __imp_kerberos_ordinal22:PANYARGS
kerberos_ordinal22 TEXTEQU <__imp_kerberos_ordinal22>
extern __imp_kerberos_ordinal23:PANYARGS
kerberos_ordinal23 TEXTEQU <__imp_kerberos_ordinal23>
extern __imp_kerberos_ordinal24:PANYARGS
kerberos_ordinal24 TEXTEQU <__imp_kerberos_ordinal24>
extern __imp_kerberos_ordinal25:PANYARGS
kerberos_ordinal25 TEXTEQU <__imp_kerberos_ordinal25>
extern __imp_kerberos_ordinal26:PANYARGS
kerberos_ordinal26 TEXTEQU <__imp_kerberos_ordinal26>
extern __imp_kerberos_ordinal27:PANYARGS
kerberos_ordinal27 TEXTEQU <__imp_kerberos_ordinal27>
extern __imp_kerberos_ordinal28:PANYARGS
kerberos_ordinal28 TEXTEQU <__imp_kerberos_ordinal28>
extern __imp_kerberos_ordinal29:PANYARGS
kerberos_ordinal29 TEXTEQU <__imp_kerberos_ordinal29>
extern __imp_kerberos_ordinal30:PANYARGS
kerberos_ordinal30 TEXTEQU <__imp_kerberos_ordinal30>
extern __imp_kerberos_ordinal31:PANYARGS
kerberos_ordinal31 TEXTEQU <__imp_kerberos_ordinal31>
extern __imp_SpInstanceInit:PANYARGS
SpInstanceInit TEXTEQU <__imp_SpInstanceInit>
