extern __imp_CPlApplet:PANYARGS
CPlApplet TEXTEQU <__imp_CPlApplet>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_KRShowKeyMgr:PANYARGS
KRShowKeyMgr TEXTEQU <__imp_KRShowKeyMgr>
extern __imp_PRShowRestoreFromMsginaW:PANYARGS
PRShowRestoreFromMsginaW TEXTEQU <__imp_PRShowRestoreFromMsginaW>
extern __imp_PRShowRestoreWizardExW:PANYARGS
PRShowRestoreWizardExW TEXTEQU <__imp_PRShowRestoreWizardExW>
extern __imp_PRShowRestoreWizardW:PANYARGS
PRShowRestoreWizardW TEXTEQU <__imp_PRShowRestoreWizardW>
extern __imp_PRShowSaveFromMsginaW:PANYARGS
PRShowSaveFromMsginaW TEXTEQU <__imp_PRShowSaveFromMsginaW>
extern __imp_PRShowSaveWizardExW:PANYARGS
PRShowSaveWizardExW TEXTEQU <__imp_PRShowSaveWizardExW>
