extern __imp_licdll_ordinal124:PANYARGS
licdll_ordinal124 TEXTEQU <__imp_licdll_ordinal124>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_licdll_ordinal129:PANYARGS
licdll_ordinal129 TEXTEQU <__imp_licdll_ordinal129>
extern __imp_licdll_ordinal130:PANYARGS
licdll_ordinal130 TEXTEQU <__imp_licdll_ordinal130>
extern __imp_licdll_ordinal131:PANYARGS
licdll_ordinal131 TEXTEQU <__imp_licdll_ordinal131>
extern __imp_licdll_ordinal132:PANYARGS
licdll_ordinal132 TEXTEQU <__imp_licdll_ordinal132>
extern __imp_licdll_ordinal133:PANYARGS
licdll_ordinal133 TEXTEQU <__imp_licdll_ordinal133>
extern __imp_licdll_ordinal134:PANYARGS
licdll_ordinal134 TEXTEQU <__imp_licdll_ordinal134>
extern __imp_licdll_ordinal135:PANYARGS
licdll_ordinal135 TEXTEQU <__imp_licdll_ordinal135>
extern __imp_licdll_ordinal136:PANYARGS
licdll_ordinal136 TEXTEQU <__imp_licdll_ordinal136>
extern __imp_licdll_ordinal137:PANYARGS
licdll_ordinal137 TEXTEQU <__imp_licdll_ordinal137>
extern __imp_licdll_ordinal138:PANYARGS
licdll_ordinal138 TEXTEQU <__imp_licdll_ordinal138>
extern __imp_licdll_ordinal139:PANYARGS
licdll_ordinal139 TEXTEQU <__imp_licdll_ordinal139>
extern __imp_licdll_ordinal140:PANYARGS
licdll_ordinal140 TEXTEQU <__imp_licdll_ordinal140>
extern __imp_licdll_ordinal141:PANYARGS
licdll_ordinal141 TEXTEQU <__imp_licdll_ordinal141>
extern __imp_licdll_ordinal142:PANYARGS
licdll_ordinal142 TEXTEQU <__imp_licdll_ordinal142>
extern __imp_licdll_ordinal143:PANYARGS
licdll_ordinal143 TEXTEQU <__imp_licdll_ordinal143>
extern __imp_licdll_ordinal144:PANYARGS
licdll_ordinal144 TEXTEQU <__imp_licdll_ordinal144>
extern __imp_licdll_ordinal145:PANYARGS
licdll_ordinal145 TEXTEQU <__imp_licdll_ordinal145>
extern __imp_licdll_ordinal146:PANYARGS
licdll_ordinal146 TEXTEQU <__imp_licdll_ordinal146>
extern __imp_licdll_ordinal147:PANYARGS
licdll_ordinal147 TEXTEQU <__imp_licdll_ordinal147>
extern __imp_licdll_ordinal148:PANYARGS
licdll_ordinal148 TEXTEQU <__imp_licdll_ordinal148>
extern __imp_licdll_ordinal149:PANYARGS
licdll_ordinal149 TEXTEQU <__imp_licdll_ordinal149>
extern __imp_licdll_ordinal150:PANYARGS
licdll_ordinal150 TEXTEQU <__imp_licdll_ordinal150>
extern __imp_licdll_ordinal151:PANYARGS
licdll_ordinal151 TEXTEQU <__imp_licdll_ordinal151>
extern __imp_licdll_ordinal152:PANYARGS
licdll_ordinal152 TEXTEQU <__imp_licdll_ordinal152>
extern __imp_licdll_ordinal153:PANYARGS
licdll_ordinal153 TEXTEQU <__imp_licdll_ordinal153>
extern __imp_licdll_ordinal154:PANYARGS
licdll_ordinal154 TEXTEQU <__imp_licdll_ordinal154>
extern __imp_licdll_ordinal155:PANYARGS
licdll_ordinal155 TEXTEQU <__imp_licdll_ordinal155>
extern __imp_licdll_ordinal156:PANYARGS
licdll_ordinal156 TEXTEQU <__imp_licdll_ordinal156>
extern __imp_licdll_ordinal157:PANYARGS
licdll_ordinal157 TEXTEQU <__imp_licdll_ordinal157>
extern __imp_licdll_ordinal158:PANYARGS
licdll_ordinal158 TEXTEQU <__imp_licdll_ordinal158>
extern __imp_licdll_ordinal159:PANYARGS
licdll_ordinal159 TEXTEQU <__imp_licdll_ordinal159>
extern __imp_licdll_ordinal160:PANYARGS
licdll_ordinal160 TEXTEQU <__imp_licdll_ordinal160>
extern __imp_licdll_ordinal161:PANYARGS
licdll_ordinal161 TEXTEQU <__imp_licdll_ordinal161>
extern __imp_licdll_ordinal162:PANYARGS
licdll_ordinal162 TEXTEQU <__imp_licdll_ordinal162>
extern __imp_licdll_ordinal163:PANYARGS
licdll_ordinal163 TEXTEQU <__imp_licdll_ordinal163>
extern __imp_licdll_ordinal164:PANYARGS
licdll_ordinal164 TEXTEQU <__imp_licdll_ordinal164>
extern __imp_licdll_ordinal165:PANYARGS
licdll_ordinal165 TEXTEQU <__imp_licdll_ordinal165>
extern __imp_licdll_ordinal166:PANYARGS
licdll_ordinal166 TEXTEQU <__imp_licdll_ordinal166>
extern __imp_licdll_ordinal167:PANYARGS
licdll_ordinal167 TEXTEQU <__imp_licdll_ordinal167>
extern __imp_licdll_ordinal168:PANYARGS
licdll_ordinal168 TEXTEQU <__imp_licdll_ordinal168>
extern __imp_licdll_ordinal169:PANYARGS
licdll_ordinal169 TEXTEQU <__imp_licdll_ordinal169>
extern __imp_licdll_ordinal170:PANYARGS
licdll_ordinal170 TEXTEQU <__imp_licdll_ordinal170>
extern __imp_licdll_ordinal171:PANYARGS
licdll_ordinal171 TEXTEQU <__imp_licdll_ordinal171>
extern __imp_licdll_ordinal172:PANYARGS
licdll_ordinal172 TEXTEQU <__imp_licdll_ordinal172>
extern __imp_licdll_ordinal173:PANYARGS
licdll_ordinal173 TEXTEQU <__imp_licdll_ordinal173>
extern __imp_licdll_ordinal174:PANYARGS
licdll_ordinal174 TEXTEQU <__imp_licdll_ordinal174>
extern __imp_licdll_ordinal175:PANYARGS
licdll_ordinal175 TEXTEQU <__imp_licdll_ordinal175>
extern __imp_licdll_ordinal176:PANYARGS
licdll_ordinal176 TEXTEQU <__imp_licdll_ordinal176>
extern __imp_licdll_ordinal177:PANYARGS
licdll_ordinal177 TEXTEQU <__imp_licdll_ordinal177>
extern __imp_licdll_ordinal178:PANYARGS
licdll_ordinal178 TEXTEQU <__imp_licdll_ordinal178>
extern __imp_licdll_ordinal179:PANYARGS
licdll_ordinal179 TEXTEQU <__imp_licdll_ordinal179>
extern __imp_licdll_ordinal180:PANYARGS
licdll_ordinal180 TEXTEQU <__imp_licdll_ordinal180>
extern __imp_licdll_ordinal181:PANYARGS
licdll_ordinal181 TEXTEQU <__imp_licdll_ordinal181>
extern __imp_licdll_ordinal182:PANYARGS
licdll_ordinal182 TEXTEQU <__imp_licdll_ordinal182>
extern __imp_licdll_ordinal183:PANYARGS
licdll_ordinal183 TEXTEQU <__imp_licdll_ordinal183>
extern __imp_licdll_ordinal184:PANYARGS
licdll_ordinal184 TEXTEQU <__imp_licdll_ordinal184>
extern __imp_licdll_ordinal185:PANYARGS
licdll_ordinal185 TEXTEQU <__imp_licdll_ordinal185>
extern __imp_licdll_ordinal186:PANYARGS
licdll_ordinal186 TEXTEQU <__imp_licdll_ordinal186>
extern __imp_licdll_ordinal187:PANYARGS
licdll_ordinal187 TEXTEQU <__imp_licdll_ordinal187>
extern __imp_licdll_ordinal188:PANYARGS
licdll_ordinal188 TEXTEQU <__imp_licdll_ordinal188>
extern __imp_licdll_ordinal189:PANYARGS
licdll_ordinal189 TEXTEQU <__imp_licdll_ordinal189>
extern __imp_licdll_ordinal190:PANYARGS
licdll_ordinal190 TEXTEQU <__imp_licdll_ordinal190>
extern __imp_licdll_ordinal191:PANYARGS
licdll_ordinal191 TEXTEQU <__imp_licdll_ordinal191>
extern __imp_licdll_ordinal192:PANYARGS
licdll_ordinal192 TEXTEQU <__imp_licdll_ordinal192>
extern __imp_licdll_ordinal193:PANYARGS
licdll_ordinal193 TEXTEQU <__imp_licdll_ordinal193>
extern __imp_licdll_ordinal194:PANYARGS
licdll_ordinal194 TEXTEQU <__imp_licdll_ordinal194>
extern __imp_licdll_ordinal195:PANYARGS
licdll_ordinal195 TEXTEQU <__imp_licdll_ordinal195>
extern __imp_licdll_ordinal196:PANYARGS
licdll_ordinal196 TEXTEQU <__imp_licdll_ordinal196>
extern __imp_licdll_ordinal197:PANYARGS
licdll_ordinal197 TEXTEQU <__imp_licdll_ordinal197>
extern __imp_licdll_ordinal198:PANYARGS
licdll_ordinal198 TEXTEQU <__imp_licdll_ordinal198>
extern __imp_licdll_ordinal199:PANYARGS
licdll_ordinal199 TEXTEQU <__imp_licdll_ordinal199>
extern __imp_licdll_ordinal200:PANYARGS
licdll_ordinal200 TEXTEQU <__imp_licdll_ordinal200>
extern __imp_licdll_ordinal201:PANYARGS
licdll_ordinal201 TEXTEQU <__imp_licdll_ordinal201>
extern __imp_licdll_ordinal202:PANYARGS
licdll_ordinal202 TEXTEQU <__imp_licdll_ordinal202>
extern __imp_licdll_ordinal203:PANYARGS
licdll_ordinal203 TEXTEQU <__imp_licdll_ordinal203>
extern __imp_licdll_ordinal204:PANYARGS
licdll_ordinal204 TEXTEQU <__imp_licdll_ordinal204>
extern __imp_licdll_ordinal205:PANYARGS
licdll_ordinal205 TEXTEQU <__imp_licdll_ordinal205>
extern __imp_licdll_ordinal206:PANYARGS
licdll_ordinal206 TEXTEQU <__imp_licdll_ordinal206>
extern __imp_licdll_ordinal207:PANYARGS
licdll_ordinal207 TEXTEQU <__imp_licdll_ordinal207>
extern __imp_licdll_ordinal208:PANYARGS
licdll_ordinal208 TEXTEQU <__imp_licdll_ordinal208>
extern __imp_licdll_ordinal209:PANYARGS
licdll_ordinal209 TEXTEQU <__imp_licdll_ordinal209>
extern __imp_licdll_ordinal210:PANYARGS
licdll_ordinal210 TEXTEQU <__imp_licdll_ordinal210>
extern __imp_licdll_ordinal211:PANYARGS
licdll_ordinal211 TEXTEQU <__imp_licdll_ordinal211>
extern __imp_licdll_ordinal212:PANYARGS
licdll_ordinal212 TEXTEQU <__imp_licdll_ordinal212>
extern __imp_licdll_ordinal213:PANYARGS
licdll_ordinal213 TEXTEQU <__imp_licdll_ordinal213>
extern __imp_licdll_ordinal214:PANYARGS
licdll_ordinal214 TEXTEQU <__imp_licdll_ordinal214>
extern __imp_licdll_ordinal215:PANYARGS
licdll_ordinal215 TEXTEQU <__imp_licdll_ordinal215>
extern __imp_licdll_ordinal216:PANYARGS
licdll_ordinal216 TEXTEQU <__imp_licdll_ordinal216>
extern __imp_licdll_ordinal217:PANYARGS
licdll_ordinal217 TEXTEQU <__imp_licdll_ordinal217>
extern __imp_licdll_ordinal218:PANYARGS
licdll_ordinal218 TEXTEQU <__imp_licdll_ordinal218>
extern __imp_licdll_ordinal219:PANYARGS
licdll_ordinal219 TEXTEQU <__imp_licdll_ordinal219>
extern __imp_licdll_ordinal220:PANYARGS
licdll_ordinal220 TEXTEQU <__imp_licdll_ordinal220>
extern __imp_licdll_ordinal221:PANYARGS
licdll_ordinal221 TEXTEQU <__imp_licdll_ordinal221>
extern __imp_licdll_ordinal222:PANYARGS
licdll_ordinal222 TEXTEQU <__imp_licdll_ordinal222>
extern __imp_licdll_ordinal223:PANYARGS
licdll_ordinal223 TEXTEQU <__imp_licdll_ordinal223>
extern __imp_licdll_ordinal224:PANYARGS
licdll_ordinal224 TEXTEQU <__imp_licdll_ordinal224>
extern __imp_licdll_ordinal225:PANYARGS
licdll_ordinal225 TEXTEQU <__imp_licdll_ordinal225>
extern __imp_licdll_ordinal226:PANYARGS
licdll_ordinal226 TEXTEQU <__imp_licdll_ordinal226>
extern __imp_licdll_ordinal227:PANYARGS
licdll_ordinal227 TEXTEQU <__imp_licdll_ordinal227>
extern __imp_licdll_ordinal228:PANYARGS
licdll_ordinal228 TEXTEQU <__imp_licdll_ordinal228>
extern __imp_licdll_ordinal229:PANYARGS
licdll_ordinal229 TEXTEQU <__imp_licdll_ordinal229>
