extern __imp_CompareLinkInfoReferents:PANYARGS
CompareLinkInfoReferents TEXTEQU <__imp_CompareLinkInfoReferents>
extern __imp_CompareLinkInfoVolumes:PANYARGS
CompareLinkInfoVolumes TEXTEQU <__imp_CompareLinkInfoVolumes>
extern __imp_CreateLinkInfo:PANYARGS
CreateLinkInfo TEXTEQU <__imp_CreateLinkInfo>
extern __imp_CreateLinkInfoA:PANYARGS
CreateLinkInfo  TEXTEQU <__imp_CreateLinkInfoA>
extern __imp_CreateLinkInfoW:PANYARGS
CreateLinkInfoW TEXTEQU <__imp_CreateLinkInfoW>
extern __imp_DestroyLinkInfo:PANYARGS
DestroyLinkInfo TEXTEQU <__imp_DestroyLinkInfo>
extern __imp_DisconnectLinkInfo:PANYARGS
DisconnectLinkInfo TEXTEQU <__imp_DisconnectLinkInfo>
extern __imp_GetCanonicalPathInfo:PANYARGS
GetCanonicalPathInfo TEXTEQU <__imp_GetCanonicalPathInfo>
extern __imp_GetCanonicalPathInfoA:PANYARGS
GetCanonicalPathInfo  TEXTEQU <__imp_GetCanonicalPathInfoA>
extern __imp_GetCanonicalPathInfoW:PANYARGS
GetCanonicalPathInfoW TEXTEQU <__imp_GetCanonicalPathInfoW>
extern __imp_GetLinkInfoData:PANYARGS
GetLinkInfoData TEXTEQU <__imp_GetLinkInfoData>
extern __imp_IsValidLinkInfo:PANYARGS
IsValidLinkInfo TEXTEQU <__imp_IsValidLinkInfo>
extern __imp_ResolveLinkInfo:PANYARGS
ResolveLinkInfo TEXTEQU <__imp_ResolveLinkInfo>
extern __imp_ResolveLinkInfoA:PANYARGS
ResolveLinkInfo  TEXTEQU <__imp_ResolveLinkInfoA>
extern __imp_ResolveLinkInfoW:PANYARGS
ResolveLinkInfoW TEXTEQU <__imp_ResolveLinkInfoW>
