extern __imp_ClosePrintProcessor:PANYARGS
ClosePrintProcessor TEXTEQU <__imp_ClosePrintProcessor>
extern __imp_ControlPrintProcessor:PANYARGS
ControlPrintProcessor TEXTEQU <__imp_ControlPrintProcessor>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_EnumPrintProcessorDatatypesW:PANYARGS
EnumPrintProcessorDatatypesW TEXTEQU <__imp_EnumPrintProcessorDatatypesW>
extern __imp_GetPrintProcessorCapabilities:PANYARGS
GetPrintProcessorCapabilities TEXTEQU <__imp_GetPrintProcessorCapabilities>
extern __imp_InitializePrintMonitor:PANYARGS
InitializePrintMonitor TEXTEQU <__imp_InitializePrintMonitor>
extern __imp_InitializePrintProvidor:PANYARGS
InitializePrintProvidor TEXTEQU <__imp_InitializePrintProvidor>
extern __imp_LclIsSessionZero:PANYARGS
LclIsSessionZero TEXTEQU <__imp_LclIsSessionZero>
extern __imp_LclPromptUIPerSessionUser:PANYARGS
LclPromptUIPerSessionUser TEXTEQU <__imp_LclPromptUIPerSessionUser>
extern __imp_OpenPrintProcessor:PANYARGS
OpenPrintProcessor TEXTEQU <__imp_OpenPrintProcessor>
extern __imp_PrintDocumentOnPrintProcessor:PANYARGS
PrintDocumentOnPrintProcessor TEXTEQU <__imp_PrintDocumentOnPrintProcessor>
extern __imp_PrintProcLogEvent:PANYARGS
PrintProcLogEvent TEXTEQU <__imp_PrintProcLogEvent>
extern __imp_SplAddForm:PANYARGS
SplAddForm TEXTEQU <__imp_SplAddForm>
extern __imp_SplAddMonitor:PANYARGS
SplAddMonitor TEXTEQU <__imp_SplAddMonitor>
extern __imp_SplAddPort:PANYARGS
SplAddPort TEXTEQU <__imp_SplAddPort>
extern __imp_SplAddPortEx:PANYARGS
SplAddPortEx TEXTEQU <__imp_SplAddPortEx>
extern __imp_SplAddPrintProcessor:PANYARGS
SplAddPrintProcessor TEXTEQU <__imp_SplAddPrintProcessor>
extern __imp_SplAddPrinter:PANYARGS
SplAddPrinter TEXTEQU <__imp_SplAddPrinter>
extern __imp_SplAddPrinterDriverEx:PANYARGS
SplAddPrinterDriverEx TEXTEQU <__imp_SplAddPrinterDriverEx>
extern __imp_SplBroadcastChange:PANYARGS
SplBroadcastChange TEXTEQU <__imp_SplBroadcastChange>
extern __imp_SplClosePrinter:PANYARGS
SplClosePrinter TEXTEQU <__imp_SplClosePrinter>
extern __imp_SplCloseSpooler:PANYARGS
SplCloseSpooler TEXTEQU <__imp_SplCloseSpooler>
extern __imp_SplConfigChange:PANYARGS
SplConfigChange TEXTEQU <__imp_SplConfigChange>
extern __imp_SplCopyFileEvent:PANYARGS
SplCopyFileEvent TEXTEQU <__imp_SplCopyFileEvent>
extern __imp_SplCopyNumberOfFiles:PANYARGS
SplCopyNumberOfFiles TEXTEQU <__imp_SplCopyNumberOfFiles>
extern __imp_SplCreateSpooler:PANYARGS
SplCreateSpooler TEXTEQU <__imp_SplCreateSpooler>
extern __imp_SplDeleteForm:PANYARGS
SplDeleteForm TEXTEQU <__imp_SplDeleteForm>
extern __imp_SplDeleteMonitor:PANYARGS
SplDeleteMonitor TEXTEQU <__imp_SplDeleteMonitor>
extern __imp_SplDeletePort:PANYARGS
SplDeletePort TEXTEQU <__imp_SplDeletePort>
extern __imp_SplDeletePrintProcCacheData:PANYARGS
SplDeletePrintProcCacheData TEXTEQU <__imp_SplDeletePrintProcCacheData>
extern __imp_SplDeletePrintProcessor:PANYARGS
SplDeletePrintProcessor TEXTEQU <__imp_SplDeletePrintProcessor>
extern __imp_SplDeletePrinter:PANYARGS
SplDeletePrinter TEXTEQU <__imp_SplDeletePrinter>
extern __imp_SplDeletePrinterDriverEx:PANYARGS
SplDeletePrinterDriverEx TEXTEQU <__imp_SplDeletePrinterDriverEx>
extern __imp_SplDeletePrinterKey:PANYARGS
SplDeletePrinterKey TEXTEQU <__imp_SplDeletePrinterKey>
extern __imp_SplDeleteSpooler:PANYARGS
SplDeleteSpooler TEXTEQU <__imp_SplDeleteSpooler>
extern __imp_SplDriverEvent:PANYARGS
SplDriverEvent TEXTEQU <__imp_SplDriverEvent>
extern __imp_SplEnumForms:PANYARGS
SplEnumForms TEXTEQU <__imp_SplEnumForms>
extern __imp_SplEnumMonitors:PANYARGS
SplEnumMonitors TEXTEQU <__imp_SplEnumMonitors>
extern __imp_SplEnumPorts:PANYARGS
SplEnumPorts TEXTEQU <__imp_SplEnumPorts>
extern __imp_SplEnumPrintProcCacheData:PANYARGS
SplEnumPrintProcCacheData TEXTEQU <__imp_SplEnumPrintProcCacheData>
extern __imp_SplEnumPrintProcessorDatatypes:PANYARGS
SplEnumPrintProcessorDatatypes TEXTEQU <__imp_SplEnumPrintProcessorDatatypes>
extern __imp_SplEnumPrintProcessors:PANYARGS
SplEnumPrintProcessors TEXTEQU <__imp_SplEnumPrintProcessors>
extern __imp_SplEnumPrinterDataEx:PANYARGS
SplEnumPrinterDataEx TEXTEQU <__imp_SplEnumPrinterDataEx>
extern __imp_SplEnumPrinterKey:PANYARGS
SplEnumPrinterKey TEXTEQU <__imp_SplEnumPrinterKey>
extern __imp_SplEnumPrinters:PANYARGS
SplEnumPrinters TEXTEQU <__imp_SplEnumPrinters>
extern __imp_SplGetDriverDir:PANYARGS
SplGetDriverDir TEXTEQU <__imp_SplGetDriverDir>
extern __imp_SplGetForm:PANYARGS
SplGetForm TEXTEQU <__imp_SplGetForm>
extern __imp_SplGetPrintProcCacheData:PANYARGS
SplGetPrintProcCacheData TEXTEQU <__imp_SplGetPrintProcCacheData>
extern __imp_SplGetPrintProcessorDirectory:PANYARGS
SplGetPrintProcessorDirectory TEXTEQU <__imp_SplGetPrintProcessorDirectory>
extern __imp_SplGetPrinter:PANYARGS
SplGetPrinter TEXTEQU <__imp_SplGetPrinter>
extern __imp_SplGetPrinterData:PANYARGS
SplGetPrinterData TEXTEQU <__imp_SplGetPrinterData>
extern __imp_SplGetPrinterDataEx:PANYARGS
SplGetPrinterDataEx TEXTEQU <__imp_SplGetPrinterDataEx>
extern __imp_SplGetPrinterDriver:PANYARGS
SplGetPrinterDriver TEXTEQU <__imp_SplGetPrinterDriver>
extern __imp_SplGetPrinterDriverDirectory:PANYARGS
SplGetPrinterDriverDirectory TEXTEQU <__imp_SplGetPrinterDriverDirectory>
extern __imp_SplGetPrinterDriverEx:PANYARGS
SplGetPrinterDriverEx TEXTEQU <__imp_SplGetPrinterDriverEx>
extern __imp_SplGetPrinterExtra:PANYARGS
SplGetPrinterExtra TEXTEQU <__imp_SplGetPrinterExtra>
extern __imp_SplGetPrinterExtraEx:PANYARGS
SplGetPrinterExtraEx TEXTEQU <__imp_SplGetPrinterExtraEx>
extern __imp_SplLoadLibraryTheCopyFileModule:PANYARGS
SplLoadLibraryTheCopyFileModule TEXTEQU <__imp_SplLoadLibraryTheCopyFileModule>
extern __imp_SplLogEventExternal:PANYARGS
SplLogEventExternal TEXTEQU <__imp_SplLogEventExternal>
extern __imp_SplLogWmiTraceEventExternal:PANYARGS
SplLogWmiTraceEventExternal TEXTEQU <__imp_SplLogWmiTraceEventExternal>
extern __imp_SplMonitorIsInstalled:PANYARGS
SplMonitorIsInstalled TEXTEQU <__imp_SplMonitorIsInstalled>
extern __imp_SplOpenPrinter:PANYARGS
SplOpenPrinter TEXTEQU <__imp_SplOpenPrinter>
extern __imp_SplPowerEvent:PANYARGS
SplPowerEvent TEXTEQU <__imp_SplPowerEvent>
extern __imp_SplReenumeratePorts:PANYARGS
SplReenumeratePorts TEXTEQU <__imp_SplReenumeratePorts>
extern __imp_SplResetPrinter:PANYARGS
SplResetPrinter TEXTEQU <__imp_SplResetPrinter>
extern __imp_SplSetForm:PANYARGS
SplSetForm TEXTEQU <__imp_SplSetForm>
extern __imp_SplSetPrintProcCacheData:PANYARGS
SplSetPrintProcCacheData TEXTEQU <__imp_SplSetPrintProcCacheData>
extern __imp_SplSetPrinter:PANYARGS
SplSetPrinter TEXTEQU <__imp_SplSetPrinter>
extern __imp_SplSetPrinterData:PANYARGS
SplSetPrinterData TEXTEQU <__imp_SplSetPrinterData>
extern __imp_SplSetPrinterDataEx:PANYARGS
SplSetPrinterDataEx TEXTEQU <__imp_SplSetPrinterDataEx>
extern __imp_SplSetPrinterExtra:PANYARGS
SplSetPrinterExtra TEXTEQU <__imp_SplSetPrinterExtra>
extern __imp_SplSetPrinterExtraEx:PANYARGS
SplSetPrinterExtraEx TEXTEQU <__imp_SplSetPrinterExtraEx>
extern __imp_SplXcvData:PANYARGS
SplXcvData TEXTEQU <__imp_SplXcvData>
