extern __imp_LpkInitialize:PANYARGS
LpkInitialize TEXTEQU <__imp_LpkInitialize>
extern __imp_LpkTabbedTextOut:PANYARGS
LpkTabbedTextOut TEXTEQU <__imp_LpkTabbedTextOut>
extern __imp_LpkDllInitialize:PANYARGS
LpkDllInitialize TEXTEQU <__imp_LpkDllInitialize>
extern __imp_LpkDrawTextEx:PANYARGS
LpkDrawTextEx TEXTEQU <__imp_LpkDrawTextEx>
extern __imp_LpkEditControl:PANYARGS
LpkEditControl TEXTEQU <__imp_LpkEditControl>
extern __imp_LpkExtTextOut:PANYARGS
LpkExtTextOut TEXTEQU <__imp_LpkExtTextOut>
extern __imp_LpkGetCharacterPlacement:PANYARGS
LpkGetCharacterPlacement TEXTEQU <__imp_LpkGetCharacterPlacement>
extern __imp_LpkGetTextExtentExPoint:PANYARGS
LpkGetTextExtentExPoint TEXTEQU <__imp_LpkGetTextExtentExPoint>
extern __imp_LpkPSMTextOut:PANYARGS
LpkPSMTextOut TEXTEQU <__imp_LpkPSMTextOut>
extern __imp_LpkUseGDIWidthCache:PANYARGS
LpkUseGDIWidthCache TEXTEQU <__imp_LpkUseGDIWidthCache>
extern __imp_ftsWordBreak:PANYARGS
ftsWordBreak TEXTEQU <__imp_ftsWordBreak>
