extern __imp_CancelJob:PANYARGS
CancelJob TEXTEQU <__imp_CancelJob>
extern __imp_CloseLPR:PANYARGS
CloseLPR TEXTEQU <__imp_CloseLPR>
extern __imp_EndJob:PANYARGS
EndJob TEXTEQU <__imp_EndJob>
extern __imp_GetLongQueue:PANYARGS
GetLongQueue TEXTEQU <__imp_GetLongQueue>
extern __imp_GetShortQueue:PANYARGS
GetShortQueue TEXTEQU <__imp_GetShortQueue>
extern __imp_InitiateConnection:PANYARGS
InitiateConnection TEXTEQU <__imp_InitiateConnection>
extern __imp_OpenLPR:PANYARGS
OpenLPR TEXTEQU <__imp_OpenLPR>
extern __imp_PrintWaitingJobs:PANYARGS
PrintWaitingJobs TEXTEQU <__imp_PrintWaitingJobs>
extern __imp_SetLPRTimeouts:PANYARGS
SetLPRTimeouts TEXTEQU <__imp_SetLPRTimeouts>
extern __imp_StartJob:PANYARGS
StartJob TEXTEQU <__imp_StartJob>
extern __imp_WriteJobData:PANYARGS
WriteJobData TEXTEQU <__imp_WriteJobData>
