extern __imp_CopyLZFile:PANYARGS
CopyLZFile TEXTEQU <__imp_CopyLZFile>
extern __imp_GetExpandedNameA:PANYARGS
GetExpandedName  TEXTEQU <__imp_GetExpandedNameA>
extern __imp_GetExpandedNameW:PANYARGS
GetExpandedNameW TEXTEQU <__imp_GetExpandedNameW>
extern __imp_LZClose:PANYARGS
LZClose TEXTEQU <__imp_LZClose>
extern __imp_LZCloseFile:PANYARGS
LZCloseFile TEXTEQU <__imp_LZCloseFile>
extern __imp_LZCopy:PANYARGS
LZCopy TEXTEQU <__imp_LZCopy>
extern __imp_LZCreateFileW:PANYARGS
LZCreateFileW TEXTEQU <__imp_LZCreateFileW>
extern __imp_LZDone:PANYARGS
LZDone TEXTEQU <__imp_LZDone>
extern __imp_LZInit:PANYARGS
LZInit TEXTEQU <__imp_LZInit>
extern __imp_LZOpenFileA:PANYARGS
LZOpenFile  TEXTEQU <__imp_LZOpenFileA>
extern __imp_LZOpenFileW:PANYARGS
LZOpenFileW TEXTEQU <__imp_LZOpenFileW>
extern __imp_LZRead:PANYARGS
LZRead TEXTEQU <__imp_LZRead>
extern __imp_LZSeek:PANYARGS
LZSeek TEXTEQU <__imp_LZSeek>
extern __imp_LZStart:PANYARGS
LZStart TEXTEQU <__imp_LZStart>
