extern __imp_FakeCursorMove:PANYARGS
FakeCursorMove TEXTEQU <__imp_FakeCursorMove>
extern __imp_GetCursorHack:PANYARGS
GetCursorHack TEXTEQU <__imp_GetCursorHack>
extern __imp_GetPopupInfo:PANYARGS
GetPopupInfo TEXTEQU <__imp_GetPopupInfo>
extern __imp_InstallEventHook:PANYARGS
InstallEventHook TEXTEQU <__imp_InstallEventHook>
extern __imp_SetZoomRect:PANYARGS
SetZoomRect TEXTEQU <__imp_SetZoomRect>
