extern __imp_mapistub_ordinal8:PANYARGS
mapistub_ordinal8 TEXTEQU <__imp_mapistub_ordinal8>
extern __imp_mapistub_ordinal9:PANYARGS
mapistub_ordinal9 TEXTEQU <__imp_mapistub_ordinal9>
extern __imp_mapistub_ordinal10:PANYARGS
mapistub_ordinal10 TEXTEQU <__imp_mapistub_ordinal10>
extern __imp_MAPILogonEx:PANYARGS
MAPILogonEx TEXTEQU <__imp_MAPILogonEx>
extern __imp_mapistub_ordinal12:PANYARGS
mapistub_ordinal12 TEXTEQU <__imp_mapistub_ordinal12>
extern __imp_MAPIAllocateBuffer:PANYARGS
MAPIAllocateBuffer TEXTEQU <__imp_MAPIAllocateBuffer>
extern __imp_mapistub_ordinal14:PANYARGS
mapistub_ordinal14 TEXTEQU <__imp_mapistub_ordinal14>
extern __imp_MAPIAllocateMore:PANYARGS
MAPIAllocateMore TEXTEQU <__imp_MAPIAllocateMore>
extern __imp_mapistub_ordinal16:PANYARGS
mapistub_ordinal16 TEXTEQU <__imp_mapistub_ordinal16>
extern __imp_MAPIFreeBuffer:PANYARGS
MAPIFreeBuffer TEXTEQU <__imp_MAPIFreeBuffer>
extern __imp_mapistub_ordinal18:PANYARGS
mapistub_ordinal18 TEXTEQU <__imp_mapistub_ordinal18>
extern __imp_MAPIAdminProfiles:PANYARGS
MAPIAdminProfiles TEXTEQU <__imp_MAPIAdminProfiles>
extern __imp_mapistub_ordinal20:PANYARGS
mapistub_ordinal20 TEXTEQU <__imp_mapistub_ordinal20>
extern __imp_MAPIInitialize:PANYARGS
MAPIInitialize TEXTEQU <__imp_MAPIInitialize>
extern __imp_mapistub_ordinal22:PANYARGS
mapistub_ordinal22 TEXTEQU <__imp_mapistub_ordinal22>
extern __imp_MAPIUninitialize:PANYARGS
MAPIUninitialize TEXTEQU <__imp_MAPIUninitialize>
extern __imp_PRProviderInit:PANYARGS
PRProviderInit TEXTEQU <__imp_PRProviderInit>
extern __imp_LAUNCHWIZARD:PANYARGS
LAUNCHWIZARD TEXTEQU <__imp_LAUNCHWIZARD>
extern __imp_LaunchWizard:PANYARGS
LaunchWizard TEXTEQU <__imp_LaunchWizard>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_mapistub_ordinal29:PANYARGS
mapistub_ordinal29 TEXTEQU <__imp_mapistub_ordinal29>
extern __imp_MAPIOpenFormMgr:PANYARGS
MAPIOpenFormMgr TEXTEQU <__imp_MAPIOpenFormMgr>
extern __imp_mapistub_ordinal31:PANYARGS
mapistub_ordinal31 TEXTEQU <__imp_mapistub_ordinal31>
extern __imp_MAPIOpenLocalFormContainer:PANYARGS
MAPIOpenLocalFormContainer TEXTEQU <__imp_MAPIOpenLocalFormContainer>
extern __imp_ScInitMapiUtil:PANYARGS
ScInitMapiUtil TEXTEQU <__imp_ScInitMapiUtil>
extern __imp_DeinitMapiUtil:PANYARGS
DeinitMapiUtil TEXTEQU <__imp_DeinitMapiUtil>
extern __imp_ScGenerateMuid:PANYARGS
ScGenerateMuid TEXTEQU <__imp_ScGenerateMuid>
extern __imp_HrAllocAdviseSink:PANYARGS
HrAllocAdviseSink TEXTEQU <__imp_HrAllocAdviseSink>
extern __imp_mapistub_ordinal37:PANYARGS
mapistub_ordinal37 TEXTEQU <__imp_mapistub_ordinal37>
extern __imp_mapistub_ordinal38:PANYARGS
mapistub_ordinal38 TEXTEQU <__imp_mapistub_ordinal38>
extern __imp_mapistub_ordinal39:PANYARGS
mapistub_ordinal39 TEXTEQU <__imp_mapistub_ordinal39>
extern __imp_mapistub_ordinal40:PANYARGS
mapistub_ordinal40 TEXTEQU <__imp_mapistub_ordinal40>
extern __imp_WrapProgress:PANYARGS
WrapProgress TEXTEQU <__imp_WrapProgress>
extern __imp_HrThisThreadAdviseSink:PANYARGS
HrThisThreadAdviseSink TEXTEQU <__imp_HrThisThreadAdviseSink>
extern __imp_ScBinFromHexBounded:PANYARGS
ScBinFromHexBounded TEXTEQU <__imp_ScBinFromHexBounded>
extern __imp_FBinFromHex:PANYARGS
FBinFromHex TEXTEQU <__imp_FBinFromHex>
extern __imp_HexFromBin:PANYARGS
HexFromBin TEXTEQU <__imp_HexFromBin>
extern __imp_BuildDisplayTable:PANYARGS
BuildDisplayTable TEXTEQU <__imp_BuildDisplayTable>
extern __imp_SwapPlong:PANYARGS
SwapPlong TEXTEQU <__imp_SwapPlong>
extern __imp_SwapPword:PANYARGS
SwapPword TEXTEQU <__imp_SwapPword>
extern __imp_MAPIInitIdle:PANYARGS
MAPIInitIdle TEXTEQU <__imp_MAPIInitIdle>
extern __imp_MAPIDeinitIdle:PANYARGS
MAPIDeinitIdle TEXTEQU <__imp_MAPIDeinitIdle>
extern __imp_InstallFilterHook:PANYARGS
InstallFilterHook TEXTEQU <__imp_InstallFilterHook>
extern __imp_FtgRegisterIdleRoutine:PANYARGS
FtgRegisterIdleRoutine TEXTEQU <__imp_FtgRegisterIdleRoutine>
extern __imp_EnableIdleRoutine:PANYARGS
EnableIdleRoutine TEXTEQU <__imp_EnableIdleRoutine>
extern __imp_DeregisterIdleRoutine:PANYARGS
DeregisterIdleRoutine TEXTEQU <__imp_DeregisterIdleRoutine>
extern __imp_ChangeIdleRoutine:PANYARGS
ChangeIdleRoutine TEXTEQU <__imp_ChangeIdleRoutine>
extern __imp_mapistub_ordinal56:PANYARGS
mapistub_ordinal56 TEXTEQU <__imp_mapistub_ordinal56>
extern __imp_mapistub_ordinal57:PANYARGS
mapistub_ordinal57 TEXTEQU <__imp_mapistub_ordinal57>
extern __imp_mapistub_ordinal58:PANYARGS
mapistub_ordinal58 TEXTEQU <__imp_mapistub_ordinal58>
extern __imp_MAPIGetDefaultMalloc:PANYARGS
MAPIGetDefaultMalloc TEXTEQU <__imp_MAPIGetDefaultMalloc>
extern __imp_CreateIProp:PANYARGS
CreateIProp TEXTEQU <__imp_CreateIProp>
extern __imp_CreateTable:PANYARGS
CreateTable TEXTEQU <__imp_CreateTable>
extern __imp_MNLS_lstrlenW:PANYARGS
MNLS_lstrlenW TEXTEQU <__imp_MNLS_lstrlenW>
extern __imp_MNLS_lstrcmpW:PANYARGS
MNLS_lstrcmpW TEXTEQU <__imp_MNLS_lstrcmpW>
extern __imp_MNLS_lstrcpyW:PANYARGS
MNLS_lstrcpyW TEXTEQU <__imp_MNLS_lstrcpyW>
extern __imp_MNLS_CompareStringW:PANYARGS
MNLS_CompareStringW TEXTEQU <__imp_MNLS_CompareStringW>
extern __imp_MNLS_MultiByteToWideChar:PANYARGS
MNLS_MultiByteToWideChar TEXTEQU <__imp_MNLS_MultiByteToWideChar>
extern __imp_MNLS_WideCharToMultiByte:PANYARGS
MNLS_WideCharToMultiByte TEXTEQU <__imp_MNLS_WideCharToMultiByte>
extern __imp_MNLS_IsBadStringPtrW:PANYARGS
MNLS_IsBadStringPtrW TEXTEQU <__imp_MNLS_IsBadStringPtrW>
extern __imp_mapistub_ordinal69:PANYARGS
mapistub_ordinal69 TEXTEQU <__imp_mapistub_ordinal69>
extern __imp_mapistub_ordinal70:PANYARGS
mapistub_ordinal70 TEXTEQU <__imp_mapistub_ordinal70>
extern __imp_mapistub_ordinal71:PANYARGS
mapistub_ordinal71 TEXTEQU <__imp_mapistub_ordinal71>
extern __imp_FEqualNames:PANYARGS
FEqualNames TEXTEQU <__imp_FEqualNames>
extern __imp_WrapStoreEntryID:PANYARGS
WrapStoreEntryID TEXTEQU <__imp_WrapStoreEntryID>
extern __imp_IsBadBoundedStringPtr:PANYARGS
IsBadBoundedStringPtr TEXTEQU <__imp_IsBadBoundedStringPtr>
extern __imp_HrQueryAllRows:PANYARGS
HrQueryAllRows TEXTEQU <__imp_HrQueryAllRows>
extern __imp_PropCopyMore:PANYARGS
PropCopyMore TEXTEQU <__imp_PropCopyMore>
extern __imp_UlPropSize:PANYARGS
UlPropSize TEXTEQU <__imp_UlPropSize>
extern __imp_FPropContainsProp:PANYARGS
FPropContainsProp TEXTEQU <__imp_FPropContainsProp>
extern __imp_FPropCompareProp:PANYARGS
FPropCompareProp TEXTEQU <__imp_FPropCompareProp>
extern __imp_LPropCompareProp:PANYARGS
LPropCompareProp TEXTEQU <__imp_LPropCompareProp>
extern __imp_HrAddColumns:PANYARGS
HrAddColumns TEXTEQU <__imp_HrAddColumns>
extern __imp_HrAddColumnsEx:PANYARGS
HrAddColumnsEx TEXTEQU <__imp_HrAddColumnsEx>
extern __imp_mapistub_ordinal83:PANYARGS
mapistub_ordinal83 TEXTEQU <__imp_mapistub_ordinal83>
extern __imp_mapistub_ordinal84:PANYARGS
mapistub_ordinal84 TEXTEQU <__imp_mapistub_ordinal84>
extern __imp_mapistub_ordinal85:PANYARGS
mapistub_ordinal85 TEXTEQU <__imp_mapistub_ordinal85>
extern __imp_mapistub_ordinal86:PANYARGS
mapistub_ordinal86 TEXTEQU <__imp_mapistub_ordinal86>
extern __imp_mapistub_ordinal87:PANYARGS
mapistub_ordinal87 TEXTEQU <__imp_mapistub_ordinal87>
extern __imp_mapistub_ordinal88:PANYARGS
mapistub_ordinal88 TEXTEQU <__imp_mapistub_ordinal88>
extern __imp_mapistub_ordinal89:PANYARGS
mapistub_ordinal89 TEXTEQU <__imp_mapistub_ordinal89>
extern __imp_mapistub_ordinal90:PANYARGS
mapistub_ordinal90 TEXTEQU <__imp_mapistub_ordinal90>
extern __imp_mapistub_ordinal91:PANYARGS
mapistub_ordinal91 TEXTEQU <__imp_mapistub_ordinal91>
extern __imp_mapistub_ordinal92:PANYARGS
mapistub_ordinal92 TEXTEQU <__imp_mapistub_ordinal92>
extern __imp_mapistub_ordinal93:PANYARGS
mapistub_ordinal93 TEXTEQU <__imp_mapistub_ordinal93>
extern __imp_mapistub_ordinal94:PANYARGS
mapistub_ordinal94 TEXTEQU <__imp_mapistub_ordinal94>
extern __imp_mapistub_ordinal95:PANYARGS
mapistub_ordinal95 TEXTEQU <__imp_mapistub_ordinal95>
extern __imp_mapistub_ordinal96:PANYARGS
mapistub_ordinal96 TEXTEQU <__imp_mapistub_ordinal96>
extern __imp_mapistub_ordinal97:PANYARGS
mapistub_ordinal97 TEXTEQU <__imp_mapistub_ordinal97>
extern __imp_mapistub_ordinal98:PANYARGS
mapistub_ordinal98 TEXTEQU <__imp_mapistub_ordinal98>
extern __imp_mapistub_ordinal99:PANYARGS
mapistub_ordinal99 TEXTEQU <__imp_mapistub_ordinal99>
extern __imp_mapistub_ordinal100:PANYARGS
mapistub_ordinal100 TEXTEQU <__imp_mapistub_ordinal100>
extern __imp_mapistub_ordinal101:PANYARGS
mapistub_ordinal101 TEXTEQU <__imp_mapistub_ordinal101>
extern __imp_mapistub_ordinal102:PANYARGS
mapistub_ordinal102 TEXTEQU <__imp_mapistub_ordinal102>
extern __imp_mapistub_ordinal103:PANYARGS
mapistub_ordinal103 TEXTEQU <__imp_mapistub_ordinal103>
extern __imp_mapistub_ordinal104:PANYARGS
mapistub_ordinal104 TEXTEQU <__imp_mapistub_ordinal104>
extern __imp_mapistub_ordinal105:PANYARGS
mapistub_ordinal105 TEXTEQU <__imp_mapistub_ordinal105>
extern __imp_mapistub_ordinal106:PANYARGS
mapistub_ordinal106 TEXTEQU <__imp_mapistub_ordinal106>
extern __imp_mapistub_ordinal107:PANYARGS
mapistub_ordinal107 TEXTEQU <__imp_mapistub_ordinal107>
extern __imp_mapistub_ordinal108:PANYARGS
mapistub_ordinal108 TEXTEQU <__imp_mapistub_ordinal108>
extern __imp_mapistub_ordinal109:PANYARGS
mapistub_ordinal109 TEXTEQU <__imp_mapistub_ordinal109>
extern __imp_mapistub_ordinal110:PANYARGS
mapistub_ordinal110 TEXTEQU <__imp_mapistub_ordinal110>
extern __imp_mapistub_ordinal111:PANYARGS
mapistub_ordinal111 TEXTEQU <__imp_mapistub_ordinal111>
extern __imp_mapistub_ordinal112:PANYARGS
mapistub_ordinal112 TEXTEQU <__imp_mapistub_ordinal112>
extern __imp_mapistub_ordinal113:PANYARGS
mapistub_ordinal113 TEXTEQU <__imp_mapistub_ordinal113>
extern __imp_mapistub_ordinal114:PANYARGS
mapistub_ordinal114 TEXTEQU <__imp_mapistub_ordinal114>
extern __imp_mapistub_ordinal115:PANYARGS
mapistub_ordinal115 TEXTEQU <__imp_mapistub_ordinal115>
extern __imp_mapistub_ordinal116:PANYARGS
mapistub_ordinal116 TEXTEQU <__imp_mapistub_ordinal116>
extern __imp_mapistub_ordinal117:PANYARGS
mapistub_ordinal117 TEXTEQU <__imp_mapistub_ordinal117>
extern __imp_mapistub_ordinal118:PANYARGS
mapistub_ordinal118 TEXTEQU <__imp_mapistub_ordinal118>
extern __imp_mapistub_ordinal119:PANYARGS
mapistub_ordinal119 TEXTEQU <__imp_mapistub_ordinal119>
extern __imp_mapistub_ordinal120:PANYARGS
mapistub_ordinal120 TEXTEQU <__imp_mapistub_ordinal120>
extern __imp_FtAddFt:PANYARGS
FtAddFt TEXTEQU <__imp_FtAddFt>
extern __imp_FtAdcFt:PANYARGS
FtAdcFt TEXTEQU <__imp_FtAdcFt>
extern __imp_FtSubFt:PANYARGS
FtSubFt TEXTEQU <__imp_FtSubFt>
extern __imp_FtMulDw:PANYARGS
FtMulDw TEXTEQU <__imp_FtMulDw>
extern __imp_FtMulDwDw:PANYARGS
FtMulDwDw TEXTEQU <__imp_FtMulDwDw>
extern __imp_FtNegFt:PANYARGS
FtNegFt TEXTEQU <__imp_FtNegFt>
extern __imp_FtDivFtBogus:PANYARGS
FtDivFtBogus TEXTEQU <__imp_FtDivFtBogus>
extern __imp_UlAddRef:PANYARGS
UlAddRef TEXTEQU <__imp_UlAddRef>
extern __imp_UlRelease:PANYARGS
UlRelease TEXTEQU <__imp_UlRelease>
extern __imp_SzFindCh:PANYARGS
SzFindCh TEXTEQU <__imp_SzFindCh>
extern __imp_SzFindLastCh:PANYARGS
SzFindLastCh TEXTEQU <__imp_SzFindLastCh>
extern __imp_SzFindSz:PANYARGS
SzFindSz TEXTEQU <__imp_SzFindSz>
extern __imp_UFromSz:PANYARGS
UFromSz TEXTEQU <__imp_UFromSz>
extern __imp_mapistub_ordinal134:PANYARGS
mapistub_ordinal134 TEXTEQU <__imp_mapistub_ordinal134>
extern __imp_HrGetOneProp:PANYARGS
HrGetOneProp TEXTEQU <__imp_HrGetOneProp>
extern __imp_HrSetOneProp:PANYARGS
HrSetOneProp TEXTEQU <__imp_HrSetOneProp>
extern __imp_FPropExists:PANYARGS
FPropExists TEXTEQU <__imp_FPropExists>
extern __imp_PpropFindProp:PANYARGS
PpropFindProp TEXTEQU <__imp_PpropFindProp>
extern __imp_FreePadrlist:PANYARGS
FreePadrlist TEXTEQU <__imp_FreePadrlist>
extern __imp_FreeProws:PANYARGS
FreeProws TEXTEQU <__imp_FreeProws>
extern __imp_HrSzFromEntryID:PANYARGS
HrSzFromEntryID TEXTEQU <__imp_HrSzFromEntryID>
extern __imp_HrEntryIDFromSz:PANYARGS
HrEntryIDFromSz TEXTEQU <__imp_HrEntryIDFromSz>
extern __imp_HrComposeEID:PANYARGS
HrComposeEID TEXTEQU <__imp_HrComposeEID>
extern __imp_HrDecomposeEID:PANYARGS
HrDecomposeEID TEXTEQU <__imp_HrDecomposeEID>
extern __imp_HrComposeMsgID:PANYARGS
HrComposeMsgID TEXTEQU <__imp_HrComposeMsgID>
extern __imp_HrDecomposeMsgID:PANYARGS
HrDecomposeMsgID TEXTEQU <__imp_HrDecomposeMsgID>
extern __imp_OpenStreamOnFile:PANYARGS
OpenStreamOnFile TEXTEQU <__imp_OpenStreamOnFile>
extern __imp_mapistub_ordinal148:PANYARGS
mapistub_ordinal148 TEXTEQU <__imp_mapistub_ordinal148>
extern __imp_OpenTnefStream:PANYARGS
OpenTnefStream TEXTEQU <__imp_OpenTnefStream>
extern __imp_mapistub_ordinal150:PANYARGS
mapistub_ordinal150 TEXTEQU <__imp_mapistub_ordinal150>
extern __imp_OpenTnefStreamEx:PANYARGS
OpenTnefStreamEx TEXTEQU <__imp_OpenTnefStreamEx>
extern __imp_mapistub_ordinal152:PANYARGS
mapistub_ordinal152 TEXTEQU <__imp_mapistub_ordinal152>
extern __imp_GetTnefStreamCodepage:PANYARGS
GetTnefStreamCodepage TEXTEQU <__imp_GetTnefStreamCodepage>
extern __imp_mapistub_ordinal154:PANYARGS
mapistub_ordinal154 TEXTEQU <__imp_mapistub_ordinal154>
extern __imp_UlFromSzHex:PANYARGS
UlFromSzHex TEXTEQU <__imp_UlFromSzHex>
extern __imp_UNKOBJ_ScAllocate:PANYARGS
UNKOBJ_ScAllocate TEXTEQU <__imp_UNKOBJ_ScAllocate>
extern __imp_UNKOBJ_ScAllocateMore:PANYARGS
UNKOBJ_ScAllocateMore TEXTEQU <__imp_UNKOBJ_ScAllocateMore>
extern __imp_UNKOBJ_Free:PANYARGS
UNKOBJ_Free TEXTEQU <__imp_UNKOBJ_Free>
extern __imp_UNKOBJ_FreeRows:PANYARGS
UNKOBJ_FreeRows TEXTEQU <__imp_UNKOBJ_FreeRows>
extern __imp_UNKOBJ_ScCOAllocate:PANYARGS
UNKOBJ_ScCOAllocate TEXTEQU <__imp_UNKOBJ_ScCOAllocate>
extern __imp_UNKOBJ_ScCOReallocate:PANYARGS
UNKOBJ_ScCOReallocate TEXTEQU <__imp_UNKOBJ_ScCOReallocate>
extern __imp_UNKOBJ_COFree:PANYARGS
UNKOBJ_COFree TEXTEQU <__imp_UNKOBJ_COFree>
extern __imp_UNKOBJ_ScSzFromIdsAlloc:PANYARGS
UNKOBJ_ScSzFromIdsAlloc TEXTEQU <__imp_UNKOBJ_ScSzFromIdsAlloc>
extern __imp_ScCountNotifications:PANYARGS
ScCountNotifications TEXTEQU <__imp_ScCountNotifications>
extern __imp_ScCopyNotifications:PANYARGS
ScCopyNotifications TEXTEQU <__imp_ScCopyNotifications>
extern __imp_ScRelocNotifications:PANYARGS
ScRelocNotifications TEXTEQU <__imp_ScRelocNotifications>
extern __imp_mapistub_ordinal167:PANYARGS
mapistub_ordinal167 TEXTEQU <__imp_mapistub_ordinal167>
extern __imp_mapistub_ordinal168:PANYARGS
mapistub_ordinal168 TEXTEQU <__imp_mapistub_ordinal168>
extern __imp_mapistub_ordinal169:PANYARGS
mapistub_ordinal169 TEXTEQU <__imp_mapistub_ordinal169>
extern __imp_ScCountProps:PANYARGS
ScCountProps TEXTEQU <__imp_ScCountProps>
extern __imp_ScCopyProps:PANYARGS
ScCopyProps TEXTEQU <__imp_ScCopyProps>
extern __imp_ScRelocProps:PANYARGS
ScRelocProps TEXTEQU <__imp_ScRelocProps>
extern __imp_LpValFindProp:PANYARGS
LpValFindProp TEXTEQU <__imp_LpValFindProp>
extern __imp_ScDupPropset:PANYARGS
ScDupPropset TEXTEQU <__imp_ScDupPropset>
extern __imp_FBadRglpszA:PANYARGS
FBadRglpsz  TEXTEQU <__imp_FBadRglpszA>
extern __imp_FBadRglpszW:PANYARGS
FBadRglpszW TEXTEQU <__imp_FBadRglpszW>
extern __imp_FBadRowSet:PANYARGS
FBadRowSet TEXTEQU <__imp_FBadRowSet>
extern __imp_FBadRglpNameID:PANYARGS
FBadRglpNameID TEXTEQU <__imp_FBadRglpNameID>
extern __imp_FBadPropTag:PANYARGS
FBadPropTag TEXTEQU <__imp_FBadPropTag>
extern __imp_FBadRow:PANYARGS
FBadRow TEXTEQU <__imp_FBadRow>
extern __imp_FBadProp:PANYARGS
FBadProp TEXTEQU <__imp_FBadProp>
extern __imp_FBadColumnSet:PANYARGS
FBadColumnSet TEXTEQU <__imp_FBadColumnSet>
extern __imp_RTFSync:PANYARGS
RTFSync TEXTEQU <__imp_RTFSync>
extern __imp_mapistub_ordinal184:PANYARGS
mapistub_ordinal184 TEXTEQU <__imp_mapistub_ordinal184>
extern __imp_WrapCompressedRTFStream:PANYARGS
WrapCompressedRTFStream TEXTEQU <__imp_WrapCompressedRTFStream>
extern __imp_mapistub_ordinal186:PANYARGS
mapistub_ordinal186 TEXTEQU <__imp_mapistub_ordinal186>
extern __imp___ValidateParameters:PANYARGS
__ValidateParameters TEXTEQU <__imp___ValidateParameters>
extern __imp___CPPValidateParameters:PANYARGS
__CPPValidateParameters TEXTEQU <__imp___CPPValidateParameters>
extern __imp_FBadSortOrderSet:PANYARGS
FBadSortOrderSet TEXTEQU <__imp_FBadSortOrderSet>
extern __imp_FBadEntryList:PANYARGS
FBadEntryList TEXTEQU <__imp_FBadEntryList>
extern __imp_FBadRestriction:PANYARGS
FBadRestriction TEXTEQU <__imp_FBadRestriction>
extern __imp_ScUNCFromLocalPath:PANYARGS
ScUNCFromLocalPath TEXTEQU <__imp_ScUNCFromLocalPath>
extern __imp_ScLocalPathFromUNC:PANYARGS
ScLocalPathFromUNC TEXTEQU <__imp_ScLocalPathFromUNC>
extern __imp_HrIStorageFromStream:PANYARGS
HrIStorageFromStream TEXTEQU <__imp_HrIStorageFromStream>
extern __imp_HrValidateIPMSubtree:PANYARGS
HrValidateIPMSubtree TEXTEQU <__imp_HrValidateIPMSubtree>
extern __imp_OpenIMsgSession:PANYARGS
OpenIMsgSession TEXTEQU <__imp_OpenIMsgSession>
extern __imp_CloseIMsgSession:PANYARGS
CloseIMsgSession TEXTEQU <__imp_CloseIMsgSession>
extern __imp_OpenIMsgOnIStg:PANYARGS
OpenIMsgOnIStg TEXTEQU <__imp_OpenIMsgOnIStg>
extern __imp_SetAttribIMsgOnIStg:PANYARGS
SetAttribIMsgOnIStg TEXTEQU <__imp_SetAttribIMsgOnIStg>
extern __imp_GetAttribIMsgOnIStg:PANYARGS
GetAttribIMsgOnIStg TEXTEQU <__imp_GetAttribIMsgOnIStg>
extern __imp_MapStorageSCode:PANYARGS
MapStorageSCode TEXTEQU <__imp_MapStorageSCode>
extern __imp_ScMAPIXFromCMC:PANYARGS
ScMAPIXFromCMC TEXTEQU <__imp_ScMAPIXFromCMC>
extern __imp_ScMAPIXFromSMAPI:PANYARGS
ScMAPIXFromSMAPI TEXTEQU <__imp_ScMAPIXFromSMAPI>
extern __imp_EncodeID:PANYARGS
EncodeID TEXTEQU <__imp_EncodeID>
extern __imp_FDecodeID:PANYARGS
FDecodeID TEXTEQU <__imp_FDecodeID>
extern __imp_CchOfEncoding:PANYARGS
CchOfEncoding TEXTEQU <__imp_CchOfEncoding>
extern __imp_CbOfEncoded:PANYARGS
CbOfEncoded TEXTEQU <__imp_CbOfEncoded>
extern __imp_MAPISendDocuments:PANYARGS
MAPISendDocuments TEXTEQU <__imp_MAPISendDocuments>
extern __imp_MAPILogon:PANYARGS
MAPILogon TEXTEQU <__imp_MAPILogon>
extern __imp_MAPILogoff:PANYARGS
MAPILogoff TEXTEQU <__imp_MAPILogoff>
extern __imp_MAPISendMail:PANYARGS
MAPISendMail TEXTEQU <__imp_MAPISendMail>
extern __imp_MAPISaveMail:PANYARGS
MAPISaveMail TEXTEQU <__imp_MAPISaveMail>
extern __imp_MAPIReadMail:PANYARGS
MAPIReadMail TEXTEQU <__imp_MAPIReadMail>
extern __imp_MAPIFindNext:PANYARGS
MAPIFindNext TEXTEQU <__imp_MAPIFindNext>
extern __imp_MAPIDeleteMail:PANYARGS
MAPIDeleteMail TEXTEQU <__imp_MAPIDeleteMail>
extern __imp_mapistub_ordinal216:PANYARGS
mapistub_ordinal216 TEXTEQU <__imp_mapistub_ordinal216>
extern __imp_MAPIAddress:PANYARGS
MAPIAddress TEXTEQU <__imp_MAPIAddress>
extern __imp_MAPIDetails:PANYARGS
MAPIDetails TEXTEQU <__imp_MAPIDetails>
extern __imp_MAPIResolveName:PANYARGS
MAPIResolveName TEXTEQU <__imp_MAPIResolveName>
extern __imp_BMAPISendMail:PANYARGS
BMAPISendMail TEXTEQU <__imp_BMAPISendMail>
extern __imp_BMAPISaveMail:PANYARGS
BMAPISaveMail TEXTEQU <__imp_BMAPISaveMail>
extern __imp_BMAPIReadMail:PANYARGS
BMAPIReadMail TEXTEQU <__imp_BMAPIReadMail>
extern __imp_BMAPIGetReadMail:PANYARGS
BMAPIGetReadMail TEXTEQU <__imp_BMAPIGetReadMail>
extern __imp_BMAPIFindNext:PANYARGS
BMAPIFindNext TEXTEQU <__imp_BMAPIFindNext>
extern __imp_BMAPIAddress:PANYARGS
BMAPIAddress TEXTEQU <__imp_BMAPIAddress>
extern __imp_BMAPIGetAddress:PANYARGS
BMAPIGetAddress TEXTEQU <__imp_BMAPIGetAddress>
extern __imp_BMAPIDetails:PANYARGS
BMAPIDetails TEXTEQU <__imp_BMAPIDetails>
extern __imp_BMAPIResolveName:PANYARGS
BMAPIResolveName TEXTEQU <__imp_BMAPIResolveName>
extern __imp_cmc_act_on:PANYARGS
cmc_act_on TEXTEQU <__imp_cmc_act_on>
extern __imp_cmc_free:PANYARGS
cmc_free TEXTEQU <__imp_cmc_free>
extern __imp_cmc_list:PANYARGS
cmc_list TEXTEQU <__imp_cmc_list>
extern __imp_cmc_logoff:PANYARGS
cmc_logoff TEXTEQU <__imp_cmc_logoff>
extern __imp_cmc_logon:PANYARGS
cmc_logon TEXTEQU <__imp_cmc_logon>
extern __imp_cmc_look_up:PANYARGS
cmc_look_up TEXTEQU <__imp_cmc_look_up>
extern __imp_cmc_query_configuration:PANYARGS
cmc_query_configuration TEXTEQU <__imp_cmc_query_configuration>
extern __imp_cmc_read:PANYARGS
cmc_read TEXTEQU <__imp_cmc_read>
extern __imp_cmc_send:PANYARGS
cmc_send TEXTEQU <__imp_cmc_send>
extern __imp_cmc_send_documents:PANYARGS
cmc_send_documents TEXTEQU <__imp_cmc_send_documents>
extern __imp_HrDispatchNotifications:PANYARGS
HrDispatchNotifications TEXTEQU <__imp_HrDispatchNotifications>
extern __imp_mapistub_ordinal240:PANYARGS
mapistub_ordinal240 TEXTEQU <__imp_mapistub_ordinal240>
extern __imp_mapistub_ordinal241:PANYARGS
mapistub_ordinal241 TEXTEQU <__imp_mapistub_ordinal241>
extern __imp_HrValidateParametersV:PANYARGS
HrValidateParametersV TEXTEQU <__imp_HrValidateParametersV>
extern __imp_HrValidateParametersValist:PANYARGS
HrValidateParametersValist TEXTEQU <__imp_HrValidateParametersValist>
extern __imp_ScCreateConversationIndex:PANYARGS
ScCreateConversationIndex TEXTEQU <__imp_ScCreateConversationIndex>
extern __imp_mapistub_ordinal245:PANYARGS
mapistub_ordinal245 TEXTEQU <__imp_mapistub_ordinal245>
extern __imp_mapistub_ordinal246:PANYARGS
mapistub_ordinal246 TEXTEQU <__imp_mapistub_ordinal246>
extern __imp_HrGetOmiProvidersFlags:PANYARGS
HrGetOmiProvidersFlags TEXTEQU <__imp_HrGetOmiProvidersFlags>
extern __imp_mapistub_ordinal248:PANYARGS
mapistub_ordinal248 TEXTEQU <__imp_mapistub_ordinal248>
extern __imp_HrSetOmiProvidersFlagsInvalid:PANYARGS
HrSetOmiProvidersFlagsInvalid TEXTEQU <__imp_HrSetOmiProvidersFlagsInvalid>
extern __imp_mapistub_ordinal250:PANYARGS
mapistub_ordinal250 TEXTEQU <__imp_mapistub_ordinal250>
extern __imp_GetOutlookVersion:PANYARGS
GetOutlookVersion TEXTEQU <__imp_GetOutlookVersion>
extern __imp_mapistub_ordinal252:PANYARGS
mapistub_ordinal252 TEXTEQU <__imp_mapistub_ordinal252>
extern __imp_FixMAPI:PANYARGS
FixMAPI TEXTEQU <__imp_FixMAPI>
extern __imp_mapistub_ordinal254:PANYARGS
mapistub_ordinal254 TEXTEQU <__imp_mapistub_ordinal254>
extern __imp_FGetComponentPath:PANYARGS
FGetComponentPath TEXTEQU <__imp_FGetComponentPath>
