extern __imp_MCDAddState:PANYARGS
MCDAddState TEXTEQU <__imp_MCDAddState>
extern __imp_MCDAddStateStruct:PANYARGS
MCDAddStateStruct TEXTEQU <__imp_MCDAddStateStruct>
extern __imp_MCDAlloc:PANYARGS
MCDAlloc TEXTEQU <__imp_MCDAlloc>
extern __imp_MCDAllocBuffers:PANYARGS
MCDAllocBuffers TEXTEQU <__imp_MCDAllocBuffers>
extern __imp_MCDBeginState:PANYARGS
MCDBeginState TEXTEQU <__imp_MCDBeginState>
extern __imp_MCDBindContext:PANYARGS
MCDBindContext TEXTEQU <__imp_MCDBindContext>
extern __imp_MCDClear:PANYARGS
MCDClear TEXTEQU <__imp_MCDClear>
extern __imp_MCDCopyPixels:PANYARGS
MCDCopyPixels TEXTEQU <__imp_MCDCopyPixels>
extern __imp_MCDCreateContext:PANYARGS
MCDCreateContext TEXTEQU <__imp_MCDCreateContext>
extern __imp_MCDCreateTexture:PANYARGS
MCDCreateTexture TEXTEQU <__imp_MCDCreateTexture>
extern __imp_MCDDeleteContext:PANYARGS
MCDDeleteContext TEXTEQU <__imp_MCDDeleteContext>
extern __imp_MCDDeleteTexture:PANYARGS
MCDDeleteTexture TEXTEQU <__imp_MCDDeleteTexture>
extern __imp_MCDDescribeLayerPlane:PANYARGS
MCDDescribeLayerPlane TEXTEQU <__imp_MCDDescribeLayerPlane>
extern __imp_MCDDescribeMcdLayerPlane:PANYARGS
MCDDescribeMcdLayerPlane TEXTEQU <__imp_MCDDescribeMcdLayerPlane>
extern __imp_MCDDescribeMcdPixelFormat:PANYARGS
MCDDescribeMcdPixelFormat TEXTEQU <__imp_MCDDescribeMcdPixelFormat>
extern __imp_MCDDescribePixelFormat:PANYARGS
MCDDescribePixelFormat TEXTEQU <__imp_MCDDescribePixelFormat>
extern __imp_MCDDestroyWindow:PANYARGS
MCDDestroyWindow TEXTEQU <__imp_MCDDestroyWindow>
extern __imp_MCDDrawPixels:PANYARGS
MCDDrawPixels TEXTEQU <__imp_MCDDrawPixels>
extern __imp_MCDFlushState:PANYARGS
MCDFlushState TEXTEQU <__imp_MCDFlushState>
extern __imp_MCDFree:PANYARGS
MCDFree TEXTEQU <__imp_MCDFree>
extern __imp_MCDGetBuffers:PANYARGS
MCDGetBuffers TEXTEQU <__imp_MCDGetBuffers>
extern __imp_MCDGetDriverInfo:PANYARGS
MCDGetDriverInfo TEXTEQU <__imp_MCDGetDriverInfo>
extern __imp_MCDGetTextureFormats:PANYARGS
MCDGetTextureFormats TEXTEQU <__imp_MCDGetTextureFormats>
extern __imp_MCDLock:PANYARGS
MCDLock TEXTEQU <__imp_MCDLock>
extern __imp_MCDPixelMap:PANYARGS
MCDPixelMap TEXTEQU <__imp_MCDPixelMap>
extern __imp_MCDProcessBatch:PANYARGS
MCDProcessBatch TEXTEQU <__imp_MCDProcessBatch>
extern __imp_MCDProcessBatch2:PANYARGS
MCDProcessBatch2 TEXTEQU <__imp_MCDProcessBatch2>
extern __imp_MCDQueryMemStatus:PANYARGS
MCDQueryMemStatus TEXTEQU <__imp_MCDQueryMemStatus>
extern __imp_MCDReadPixels:PANYARGS
MCDReadPixels TEXTEQU <__imp_MCDReadPixels>
extern __imp_MCDReadSpan:PANYARGS
MCDReadSpan TEXTEQU <__imp_MCDReadSpan>
extern __imp_MCDSetLayerPalette:PANYARGS
MCDSetLayerPalette TEXTEQU <__imp_MCDSetLayerPalette>
extern __imp_MCDSetScissorRect:PANYARGS
MCDSetScissorRect TEXTEQU <__imp_MCDSetScissorRect>
extern __imp_MCDSetViewport:PANYARGS
MCDSetViewport TEXTEQU <__imp_MCDSetViewport>
extern __imp_MCDSwap:PANYARGS
MCDSwap TEXTEQU <__imp_MCDSwap>
extern __imp_MCDSwapMultiple:PANYARGS
MCDSwapMultiple TEXTEQU <__imp_MCDSwapMultiple>
extern __imp_MCDSync:PANYARGS
MCDSync TEXTEQU <__imp_MCDSync>
extern __imp_MCDTextureKey:PANYARGS
MCDTextureKey TEXTEQU <__imp_MCDTextureKey>
extern __imp_MCDTextureStatus:PANYARGS
MCDTextureStatus TEXTEQU <__imp_MCDTextureStatus>
extern __imp_MCDUnlock:PANYARGS
MCDUnlock TEXTEQU <__imp_MCDUnlock>
extern __imp_MCDUpdateSubTexture:PANYARGS
MCDUpdateSubTexture TEXTEQU <__imp_MCDUpdateSubTexture>
extern __imp_MCDUpdateTexturePalette:PANYARGS
MCDUpdateTexturePalette TEXTEQU <__imp_MCDUpdateTexturePalette>
extern __imp_MCDUpdateTexturePriority:PANYARGS
MCDUpdateTexturePriority TEXTEQU <__imp_MCDUpdateTexturePriority>
extern __imp_MCDUpdateTextureState:PANYARGS
MCDUpdateTextureState TEXTEQU <__imp_MCDUpdateTextureState>
extern __imp_MCDWriteSpan:PANYARGS
MCDWriteSpan TEXTEQU <__imp_MCDWriteSpan>
