extern __imp_MCDEngEscFilter:PANYARGS
MCDEngEscFilter TEXTEQU <__imp_MCDEngEscFilter>
extern __imp_MCDEngInit:PANYARGS
MCDEngInit TEXTEQU <__imp_MCDEngInit>
extern __imp_MCDEngInitEx:PANYARGS
MCDEngInitEx TEXTEQU <__imp_MCDEngInitEx>
extern __imp_MCDEngSetMemStatus:PANYARGS
MCDEngSetMemStatus TEXTEQU <__imp_MCDEngSetMemStatus>
extern __imp_MCDEngUninit:PANYARGS
MCDEngUninit TEXTEQU <__imp_MCDEngUninit>
