extern __imp_DllLoadFromStream:PANYARGS
DllLoadFromStream TEXTEQU <__imp_DllLoadFromStream>
extern __imp_DllCreateFromClip:PANYARGS
DllCreateFromClip TEXTEQU <__imp_DllCreateFromClip>
extern __imp_DllCreateLinkFromClip:PANYARGS
DllCreateLinkFromClip TEXTEQU <__imp_DllCreateLinkFromClip>
extern __imp_DllCreateFromTemplate:PANYARGS
DllCreateFromTemplate TEXTEQU <__imp_DllCreateFromTemplate>
extern __imp_DllCreate:PANYARGS
DllCreate TEXTEQU <__imp_DllCreate>
extern __imp_DllCreateFromFile:PANYARGS
DllCreateFromFile TEXTEQU <__imp_DllCreateFromFile>
extern __imp_DllCreateLinkFromFile:PANYARGS
DllCreateLinkFromFile TEXTEQU <__imp_DllCreateLinkFromFile>
extern __imp_GetMessageHook:PANYARGS
GetMessageHook TEXTEQU <__imp_GetMessageHook>
extern __imp_OleQueryObjPos:PANYARGS
OleQueryObjPos TEXTEQU <__imp_OleQueryObjPos>
extern __imp_InstallHook:PANYARGS
InstallHook TEXTEQU <__imp_InstallHook>
extern __imp_RemoveHook:PANYARGS
RemoveHook TEXTEQU <__imp_RemoveHook>
