extern __imp_??$ConstructElements@VCString@@@@YAXPEAVCString@@H@Z:PANYARGS
??$ConstructElements@VCString@@@@YAXPEAVCString@@H@Z TEXTEQU <__imp_??$ConstructElements@VCString@@@@YAXPEAVCString@@H@Z>
extern __imp_??$CopyElements@VCString@@@@YAXPEAVCString@@PEBV0@H@Z:PANYARGS
??$CopyElements@VCString@@@@YAXPEAVCString@@PEBV0@H@Z TEXTEQU <__imp_??$CopyElements@VCString@@@@YAXPEAVCString@@PEBV0@H@Z>
extern __imp_??$DestructElements@VCString@@@@YAXPEAVCString@@H@Z:PANYARGS
??$DestructElements@VCString@@@@YAXPEAVCString@@H@Z TEXTEQU <__imp_??$DestructElements@VCString@@@@YAXPEAVCString@@H@Z>
extern __imp_??$HashKey@AEBU_GUID@@@@YAIAEBU_GUID@@@Z:PANYARGS
??$HashKey@AEBU_GUID@@@@YAIAEBU_GUID@@@Z TEXTEQU <__imp_??$HashKey@AEBU_GUID@@@@YAIAEBU_GUID@@@Z>
extern __imp_??$HashKey@PEBD@@YAIPEBD@Z:PANYARGS
??$HashKey@PEBD@@YAIPEBD@Z TEXTEQU <__imp_??$HashKey@PEBD@@YAIPEBD@Z>
extern __imp_??$HashKey@PEBG@@YAIPEBG@Z:PANYARGS
??$HashKey@PEBG@@YAIPEBG@Z TEXTEQU <__imp_??$HashKey@PEBG@@YAIPEBG@Z>
extern __imp_??0CCriticalSection@@QEAA@XZ:PANYARGS
??0CCriticalSection@@QEAA@XZ TEXTEQU <__imp_??0CCriticalSection@@QEAA@XZ>
extern __imp_??0CMapStringToPtr@@QEAA@H@Z:PANYARGS
??0CMapStringToPtr@@QEAA@H@Z TEXTEQU <__imp_??0CMapStringToPtr@@QEAA@H@Z>
extern __imp_??0CObject@@IEAA@XZ:PANYARGS
??0CObject@@IEAA@XZ TEXTEQU <__imp_??0CObject@@IEAA@XZ>
extern __imp_??0CString@@QEAA@AEBV0@@Z:PANYARGS
??0CString@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CString@@QEAA@AEBV0@@Z>
extern __imp_??0CString@@QEAA@GH@Z:PANYARGS
??0CString@@QEAA@GH@Z TEXTEQU <__imp_??0CString@@QEAA@GH@Z>
extern __imp_??0CString@@QEAA@PEBD@Z:PANYARGS
??0CString@@QEAA@PEBD@Z TEXTEQU <__imp_??0CString@@QEAA@PEBD@Z>
extern __imp_??0CString@@QEAA@PEBE@Z:PANYARGS
??0CString@@QEAA@PEBE@Z TEXTEQU <__imp_??0CString@@QEAA@PEBE@Z>
extern __imp_??0CString@@QEAA@PEBG@Z:PANYARGS
??0CString@@QEAA@PEBG@Z TEXTEQU <__imp_??0CString@@QEAA@PEBG@Z>
extern __imp_??0CString@@QEAA@PEBGH@Z:PANYARGS
??0CString@@QEAA@PEBGH@Z TEXTEQU <__imp_??0CString@@QEAA@PEBGH@Z>
extern __imp_??0CString@@QEAA@XZ:PANYARGS
??0CString@@QEAA@XZ TEXTEQU <__imp_??0CString@@QEAA@XZ>
extern __imp_??0CStringArray@@QEAA@XZ:PANYARGS
??0CStringArray@@QEAA@XZ TEXTEQU <__imp_??0CStringArray@@QEAA@XZ>
extern __imp_??0CSyncObject@@QEAA@PEBG@Z:PANYARGS
??0CSyncObject@@QEAA@PEBG@Z TEXTEQU <__imp_??0CSyncObject@@QEAA@PEBG@Z>
extern __imp_??1CCriticalSection@@UEAA@XZ:PANYARGS
??1CCriticalSection@@UEAA@XZ TEXTEQU <__imp_??1CCriticalSection@@UEAA@XZ>
extern __imp_??1CMapStringToPtr@@UEAA@XZ:PANYARGS
??1CMapStringToPtr@@UEAA@XZ TEXTEQU <__imp_??1CMapStringToPtr@@UEAA@XZ>
extern __imp_??1CObject@@UEAA@XZ:PANYARGS
??1CObject@@UEAA@XZ TEXTEQU <__imp_??1CObject@@UEAA@XZ>
extern __imp_??1CString@@QEAA@XZ:PANYARGS
??1CString@@QEAA@XZ TEXTEQU <__imp_??1CString@@QEAA@XZ>
extern __imp_??1CStringArray@@UEAA@XZ:PANYARGS
??1CStringArray@@UEAA@XZ TEXTEQU <__imp_??1CStringArray@@UEAA@XZ>
extern __imp_??1CSyncObject@@UEAA@XZ:PANYARGS
??1CSyncObject@@UEAA@XZ TEXTEQU <__imp_??1CSyncObject@@UEAA@XZ>
extern __imp_??4CPlex@@QEAAAEAU0@AEBU0@@Z:PANYARGS
??4CPlex@@QEAAAEAU0@AEBU0@@Z TEXTEQU <__imp_??4CPlex@@QEAAAEAU0@AEBU0@@Z>
extern __imp_??4CString@@QEAAAEBV0@AEBV0@@Z:PANYARGS
??4CString@@QEAAAEBV0@AEBV0@@Z TEXTEQU <__imp_??4CString@@QEAAAEBV0@AEBV0@@Z>
extern __imp_??4CString@@QEAAAEBV0@D@Z:PANYARGS
??4CString@@QEAAAEBV0@D@Z TEXTEQU <__imp_??4CString@@QEAAAEBV0@D@Z>
extern __imp_??4CString@@QEAAAEBV0@G@Z:PANYARGS
??4CString@@QEAAAEBV0@G@Z TEXTEQU <__imp_??4CString@@QEAAAEBV0@G@Z>
extern __imp_??4CString@@QEAAAEBV0@PEBD@Z:PANYARGS
??4CString@@QEAAAEBV0@PEBD@Z TEXTEQU <__imp_??4CString@@QEAAAEBV0@PEBD@Z>
extern __imp_??4CString@@QEAAAEBV0@PEBE@Z:PANYARGS
??4CString@@QEAAAEBV0@PEBE@Z TEXTEQU <__imp_??4CString@@QEAAAEBV0@PEBE@Z>
extern __imp_??4CString@@QEAAAEBV0@PEBG@Z:PANYARGS
??4CString@@QEAAAEBV0@PEBG@Z TEXTEQU <__imp_??4CString@@QEAAAEBV0@PEBG@Z>
extern __imp_??8@YA_NAEBVCString@@0@Z:PANYARGS
??8@YA_NAEBVCString@@0@Z TEXTEQU <__imp_??8@YA_NAEBVCString@@0@Z>
extern __imp_??8@YA_NAEBVCString@@PEBG@Z:PANYARGS
??8@YA_NAEBVCString@@PEBG@Z TEXTEQU <__imp_??8@YA_NAEBVCString@@PEBG@Z>
extern __imp_??8@YA_NPEBGAEBVCString@@@Z:PANYARGS
??8@YA_NPEBGAEBVCString@@@Z TEXTEQU <__imp_??8@YA_NPEBGAEBVCString@@@Z>
extern __imp_??9@YA_NAEBVCString@@0@Z:PANYARGS
??9@YA_NAEBVCString@@0@Z TEXTEQU <__imp_??9@YA_NAEBVCString@@0@Z>
extern __imp_??9@YA_NAEBVCString@@PEBG@Z:PANYARGS
??9@YA_NAEBVCString@@PEBG@Z TEXTEQU <__imp_??9@YA_NAEBVCString@@PEBG@Z>
extern __imp_??9@YA_NPEBGAEBVCString@@@Z:PANYARGS
??9@YA_NPEBGAEBVCString@@@Z TEXTEQU <__imp_??9@YA_NPEBGAEBVCString@@@Z>
extern __imp_??ACMapStringToPtr@@QEAAAEAPEAXPEBG@Z:PANYARGS
??ACMapStringToPtr@@QEAAAEAPEAXPEBG@Z TEXTEQU <__imp_??ACMapStringToPtr@@QEAAAEAPEAXPEBG@Z>
extern __imp_??ACString@@QEBAGH@Z:PANYARGS
??ACString@@QEBAGH@Z TEXTEQU <__imp_??ACString@@QEBAGH@Z>
extern __imp_??ACStringArray@@QEAAAEAVCString@@H@Z:PANYARGS
??ACStringArray@@QEAAAEAVCString@@H@Z TEXTEQU <__imp_??ACStringArray@@QEAAAEAVCString@@H@Z>
extern __imp_??ACStringArray@@QEBA?AVCString@@H@Z:PANYARGS
??ACStringArray@@QEBA?AVCString@@H@Z TEXTEQU <__imp_??ACStringArray@@QEBA?AVCString@@H@Z>
extern __imp_??BCCriticalSection@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ:PANYARGS
??BCCriticalSection@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ TEXTEQU <__imp_??BCCriticalSection@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ>
extern __imp_??BCString@@QEBAPEBGXZ:PANYARGS
??BCString@@QEBAPEBGXZ TEXTEQU <__imp_??BCString@@QEBAPEBGXZ>
extern __imp_??BCSyncObject@@QEBAPEAXXZ:PANYARGS
??BCSyncObject@@QEBAPEAXXZ TEXTEQU <__imp_??BCSyncObject@@QEBAPEAXXZ>
extern __imp_??H@YA?AVCString@@AEBV0@0@Z:PANYARGS
??H@YA?AVCString@@AEBV0@0@Z TEXTEQU <__imp_??H@YA?AVCString@@AEBV0@0@Z>
extern __imp_??H@YA?AVCString@@AEBV0@D@Z:PANYARGS
??H@YA?AVCString@@AEBV0@D@Z TEXTEQU <__imp_??H@YA?AVCString@@AEBV0@D@Z>
extern __imp_??H@YA?AVCString@@AEBV0@G@Z:PANYARGS
??H@YA?AVCString@@AEBV0@G@Z TEXTEQU <__imp_??H@YA?AVCString@@AEBV0@G@Z>
extern __imp_??H@YA?AVCString@@AEBV0@PEBG@Z:PANYARGS
??H@YA?AVCString@@AEBV0@PEBG@Z TEXTEQU <__imp_??H@YA?AVCString@@AEBV0@PEBG@Z>
extern __imp_??H@YA?AVCString@@DAEBV0@@Z:PANYARGS
??H@YA?AVCString@@DAEBV0@@Z TEXTEQU <__imp_??H@YA?AVCString@@DAEBV0@@Z>
extern __imp_??H@YA?AVCString@@GAEBV0@@Z:PANYARGS
??H@YA?AVCString@@GAEBV0@@Z TEXTEQU <__imp_??H@YA?AVCString@@GAEBV0@@Z>
extern __imp_??H@YA?AVCString@@PEBGAEBV0@@Z:PANYARGS
??H@YA?AVCString@@PEBGAEBV0@@Z TEXTEQU <__imp_??H@YA?AVCString@@PEBGAEBV0@@Z>
extern __imp_??M@YA_NAEBVCString@@0@Z:PANYARGS
??M@YA_NAEBVCString@@0@Z TEXTEQU <__imp_??M@YA_NAEBVCString@@0@Z>
extern __imp_??M@YA_NAEBVCString@@PEBG@Z:PANYARGS
??M@YA_NAEBVCString@@PEBG@Z TEXTEQU <__imp_??M@YA_NAEBVCString@@PEBG@Z>
extern __imp_??M@YA_NPEBGAEBVCString@@@Z:PANYARGS
??M@YA_NPEBGAEBVCString@@@Z TEXTEQU <__imp_??M@YA_NPEBGAEBVCString@@@Z>
extern __imp_??N@YA_NAEBVCString@@0@Z:PANYARGS
??N@YA_NAEBVCString@@0@Z TEXTEQU <__imp_??N@YA_NAEBVCString@@0@Z>
extern __imp_??N@YA_NAEBVCString@@PEBG@Z:PANYARGS
??N@YA_NAEBVCString@@PEBG@Z TEXTEQU <__imp_??N@YA_NAEBVCString@@PEBG@Z>
extern __imp_??N@YA_NPEBGAEBVCString@@@Z:PANYARGS
??N@YA_NPEBGAEBVCString@@@Z TEXTEQU <__imp_??N@YA_NPEBGAEBVCString@@@Z>
extern __imp_??O@YA_NAEBVCString@@0@Z:PANYARGS
??O@YA_NAEBVCString@@0@Z TEXTEQU <__imp_??O@YA_NAEBVCString@@0@Z>
extern __imp_??O@YA_NAEBVCString@@PEBG@Z:PANYARGS
??O@YA_NAEBVCString@@PEBG@Z TEXTEQU <__imp_??O@YA_NAEBVCString@@PEBG@Z>
extern __imp_??O@YA_NPEBGAEBVCString@@@Z:PANYARGS
??O@YA_NPEBGAEBVCString@@@Z TEXTEQU <__imp_??O@YA_NPEBGAEBVCString@@@Z>
extern __imp_??P@YA_NAEBVCString@@0@Z:PANYARGS
??P@YA_NAEBVCString@@0@Z TEXTEQU <__imp_??P@YA_NAEBVCString@@0@Z>
extern __imp_??P@YA_NAEBVCString@@PEBG@Z:PANYARGS
??P@YA_NAEBVCString@@PEBG@Z TEXTEQU <__imp_??P@YA_NAEBVCString@@PEBG@Z>
extern __imp_??P@YA_NPEBGAEBVCString@@@Z:PANYARGS
??P@YA_NPEBGAEBVCString@@@Z TEXTEQU <__imp_??P@YA_NPEBGAEBVCString@@@Z>
extern __imp_??YCString@@QEAAAEBV0@AEBV0@@Z:PANYARGS
??YCString@@QEAAAEBV0@AEBV0@@Z TEXTEQU <__imp_??YCString@@QEAAAEBV0@AEBV0@@Z>
extern __imp_??YCString@@QEAAAEBV0@D@Z:PANYARGS
??YCString@@QEAAAEBV0@D@Z TEXTEQU <__imp_??YCString@@QEAAAEBV0@D@Z>
extern __imp_??YCString@@QEAAAEBV0@G@Z:PANYARGS
??YCString@@QEAAAEBV0@G@Z TEXTEQU <__imp_??YCString@@QEAAAEBV0@G@Z>
extern __imp_??YCString@@QEAAAEBV0@PEBG@Z:PANYARGS
??YCString@@QEAAAEBV0@PEBG@Z TEXTEQU <__imp_??YCString@@QEAAAEBV0@PEBG@Z>
extern __imp_??_7CCriticalSection@@6B@:PANYARGS
??_7CCriticalSection@@6B@ TEXTEQU <__imp_??_7CCriticalSection@@6B@>
extern __imp_??_7CMapStringToPtr@@6B@:PANYARGS
??_7CMapStringToPtr@@6B@ TEXTEQU <__imp_??_7CMapStringToPtr@@6B@>
extern __imp_??_7CObject@@6B@:PANYARGS
??_7CObject@@6B@ TEXTEQU <__imp_??_7CObject@@6B@>
extern __imp_??_7CStringArray@@6B@:PANYARGS
??_7CStringArray@@6B@ TEXTEQU <__imp_??_7CStringArray@@6B@>
extern __imp_??_7CSyncObject@@6B@:PANYARGS
??_7CSyncObject@@6B@ TEXTEQU <__imp_??_7CSyncObject@@6B@>
extern __imp_??_FCMapStringToPtr@@QEAAXXZ:PANYARGS
??_FCMapStringToPtr@@QEAAXXZ TEXTEQU <__imp_??_FCMapStringToPtr@@QEAAXXZ>
extern __imp_?Add@CStringArray@@QEAAHPEBG@Z:PANYARGS
?Add@CStringArray@@QEAAHPEBG@Z TEXTEQU <__imp_?Add@CStringArray@@QEAAHPEBG@Z>
extern __imp_?AfxA2WHelper@@YAPEAGPEAGPEBDH@Z:PANYARGS
?AfxA2WHelper@@YAPEAGPEAGPEBDH@Z TEXTEQU <__imp_?AfxA2WHelper@@YAPEAGPEAGPEBDH@Z>
extern __imp_?AfxExtractSubString@@YAHAEAVCString@@PEBGHG@Z:PANYARGS
?AfxExtractSubString@@YAHAEAVCString@@PEBGHG@Z TEXTEQU <__imp_?AfxExtractSubString@@YAHAEAVCString@@PEBGHG@Z>
extern __imp_?AfxGetEmptyString@@YAAEBVCString@@XZ:PANYARGS
?AfxGetEmptyString@@YAAEBVCString@@XZ TEXTEQU <__imp_?AfxGetEmptyString@@YAAEBVCString@@XZ>
extern __imp_?AfxLoadString@@YAHIPEAGI@Z:PANYARGS
?AfxLoadString@@YAHIPEAGI@Z TEXTEQU <__imp_?AfxLoadString@@YAHIPEAGI@Z>
extern __imp_?AfxW2AHelper@@YAPEADPEADPEBGH@Z:PANYARGS
?AfxW2AHelper@@YAPEADPEADPEBGH@Z TEXTEQU <__imp_?AfxW2AHelper@@YAPEADPEADPEBGH@Z>
extern __imp_?AllocBeforeWrite@CString@@IEAAXH@Z:PANYARGS
?AllocBeforeWrite@CString@@IEAAXH@Z TEXTEQU <__imp_?AllocBeforeWrite@CString@@IEAAXH@Z>
extern __imp_?AllocBuffer@CString@@IEAAXH@Z:PANYARGS
?AllocBuffer@CString@@IEAAXH@Z TEXTEQU <__imp_?AllocBuffer@CString@@IEAAXH@Z>
extern __imp_?AllocCopy@CString@@IEBAXAEAV1@HHH@Z:PANYARGS
?AllocCopy@CString@@IEBAXAEAV1@HHH@Z TEXTEQU <__imp_?AllocCopy@CString@@IEBAXAEAV1@HHH@Z>
extern __imp_?Append@CStringArray@@QEAAHAEBV1@@Z:PANYARGS
?Append@CStringArray@@QEAAHAEBV1@@Z TEXTEQU <__imp_?Append@CStringArray@@QEAAHAEBV1@@Z>
extern __imp_?AssignCopy@CString@@IEAAXHPEBG@Z:PANYARGS
?AssignCopy@CString@@IEAAXHPEBG@Z TEXTEQU <__imp_?AssignCopy@CString@@IEAAXHPEBG@Z>
extern __imp_?Collate@CString@@QEBAHPEBG@Z:PANYARGS
?Collate@CString@@QEBAHPEBG@Z TEXTEQU <__imp_?Collate@CString@@QEBAHPEBG@Z>
extern __imp_?Compare@CString@@QEBAHPEBG@Z:PANYARGS
?Compare@CString@@QEBAHPEBG@Z TEXTEQU <__imp_?Compare@CString@@QEBAHPEBG@Z>
extern __imp_?CompareNoCase@CString@@QEBAHPEBG@Z:PANYARGS
?CompareNoCase@CString@@QEBAHPEBG@Z TEXTEQU <__imp_?CompareNoCase@CString@@QEBAHPEBG@Z>
extern __imp_?ConcatCopy@CString@@IEAAXHPEBGH0@Z:PANYARGS
?ConcatCopy@CString@@IEAAXHPEBGH0@Z TEXTEQU <__imp_?ConcatCopy@CString@@IEAAXHPEBGH0@Z>
extern __imp_?ConcatInPlace@CString@@IEAAXHPEBG@Z:PANYARGS
?ConcatInPlace@CString@@IEAAXHPEBG@Z TEXTEQU <__imp_?ConcatInPlace@CString@@IEAAXHPEBG@Z>
extern __imp_?Copy@CStringArray@@QEAAXAEBV1@@Z:PANYARGS
?Copy@CStringArray@@QEAAXAEBV1@@Z TEXTEQU <__imp_?Copy@CStringArray@@QEAAXAEBV1@@Z>
extern __imp_?CopyBeforeWrite@CString@@IEAAXXZ:PANYARGS
?CopyBeforeWrite@CString@@IEAAXXZ TEXTEQU <__imp_?CopyBeforeWrite@CString@@IEAAXXZ>
extern __imp_?Create@CPlex@@SAPEAU1@AEAPEAU1@II@Z:PANYARGS
?Create@CPlex@@SAPEAU1@AEAPEAU1@II@Z TEXTEQU <__imp_?Create@CPlex@@SAPEAU1@AEAPEAU1@II@Z>
extern __imp_?ElementAt@CStringArray@@QEAAAEAVCString@@H@Z:PANYARGS
?ElementAt@CStringArray@@QEAAAEAVCString@@H@Z TEXTEQU <__imp_?ElementAt@CStringArray@@QEAAAEAVCString@@H@Z>
extern __imp_?Empty@CString@@QEAAXXZ:PANYARGS
?Empty@CString@@QEAAXXZ TEXTEQU <__imp_?Empty@CString@@QEAAXXZ>
extern __imp_?Find@CString@@QEBAHG@Z:PANYARGS
?Find@CString@@QEBAHG@Z TEXTEQU <__imp_?Find@CString@@QEBAHG@Z>
extern __imp_?Find@CString@@QEBAHPEBG@Z:PANYARGS
?Find@CString@@QEBAHPEBG@Z TEXTEQU <__imp_?Find@CString@@QEBAHPEBG@Z>
extern __imp_?FindOneOf@CString@@QEBAHPEBG@Z:PANYARGS
?FindOneOf@CString@@QEBAHPEBG@Z TEXTEQU <__imp_?FindOneOf@CString@@QEBAHPEBG@Z>
extern __imp_?Format@CString@@QEAAXIZZ:PANYARGS
?Format@CString@@QEAAXIZZ TEXTEQU <__imp_?Format@CString@@QEAAXIZZ>
extern __imp_?Format@CString@@QEAAXPEBGZZ:PANYARGS
?Format@CString@@QEAAXPEBGZZ TEXTEQU <__imp_?Format@CString@@QEAAXPEBGZZ>
extern __imp_?FormatMessageW@CString@@QEAAXIZZ:PANYARGS
?FormatMessageW@CString@@QEAAXIZZ TEXTEQU <__imp_?FormatMessageW@CString@@QEAAXIZZ>
extern __imp_?FormatMessageW@CString@@QEAAXPEBGZZ:PANYARGS
?FormatMessageW@CString@@QEAAXPEBGZZ TEXTEQU <__imp_?FormatMessageW@CString@@QEAAXPEBGZZ>
extern __imp_?FormatV@CString@@IEAAXPEBGPEAD@Z:PANYARGS
?FormatV@CString@@IEAAXPEBGPEAD@Z TEXTEQU <__imp_?FormatV@CString@@IEAAXPEBGPEAD@Z>
extern __imp_?FreeAssoc@CMapStringToPtr@@IEAAXPEAUCAssoc@1@@Z:PANYARGS
?FreeAssoc@CMapStringToPtr@@IEAAXPEAUCAssoc@1@@Z TEXTEQU <__imp_?FreeAssoc@CMapStringToPtr@@IEAAXPEAUCAssoc@1@@Z>
extern __imp_?FreeDataChain@CPlex@@QEAAXXZ:PANYARGS
?FreeDataChain@CPlex@@QEAAXXZ TEXTEQU <__imp_?FreeDataChain@CPlex@@QEAAXXZ>
extern __imp_?FreeExtra@CString@@QEAAXXZ:PANYARGS
?FreeExtra@CString@@QEAAXXZ TEXTEQU <__imp_?FreeExtra@CString@@QEAAXXZ>
extern __imp_?FreeExtra@CStringArray@@QEAAXXZ:PANYARGS
?FreeExtra@CStringArray@@QEAAXXZ TEXTEQU <__imp_?FreeExtra@CStringArray@@QEAAXXZ>
extern __imp_?GetAllocLength@CString@@QEBAHXZ:PANYARGS
?GetAllocLength@CString@@QEBAHXZ TEXTEQU <__imp_?GetAllocLength@CString@@QEBAHXZ>
extern __imp_?GetAssocAt@CMapStringToPtr@@IEBAPEAUCAssoc@1@PEBGAEAI@Z:PANYARGS
?GetAssocAt@CMapStringToPtr@@IEBAPEAUCAssoc@1@PEBGAEAI@Z TEXTEQU <__imp_?GetAssocAt@CMapStringToPtr@@IEBAPEAUCAssoc@1@PEBGAEAI@Z>
extern __imp_?GetAt@CString@@QEBAGH@Z:PANYARGS
?GetAt@CString@@QEBAGH@Z TEXTEQU <__imp_?GetAt@CString@@QEBAGH@Z>
extern __imp_?GetAt@CStringArray@@QEBA?AVCString@@H@Z:PANYARGS
?GetAt@CStringArray@@QEBA?AVCString@@H@Z TEXTEQU <__imp_?GetAt@CStringArray@@QEBA?AVCString@@H@Z>
extern __imp_?GetBuffer@CString@@QEAAPEAGH@Z:PANYARGS
?GetBuffer@CString@@QEAAPEAGH@Z TEXTEQU <__imp_?GetBuffer@CString@@QEAAPEAGH@Z>
extern __imp_?GetBufferSetLength@CString@@QEAAPEAGH@Z:PANYARGS
?GetBufferSetLength@CString@@QEAAPEAGH@Z TEXTEQU <__imp_?GetBufferSetLength@CString@@QEAAPEAGH@Z>
extern __imp_?GetCount@CMapStringToPtr@@QEBAHXZ:PANYARGS
?GetCount@CMapStringToPtr@@QEBAHXZ TEXTEQU <__imp_?GetCount@CMapStringToPtr@@QEBAHXZ>
extern __imp_?GetData@CString@@IEBAPEAUCStringData@@XZ:PANYARGS
?GetData@CString@@IEBAPEAUCStringData@@XZ TEXTEQU <__imp_?GetData@CString@@IEBAPEAUCStringData@@XZ>
extern __imp_?GetData@CStringArray@@QEAAPEAVCString@@XZ:PANYARGS
?GetData@CStringArray@@QEAAPEAVCString@@XZ TEXTEQU <__imp_?GetData@CStringArray@@QEAAPEAVCString@@XZ>
extern __imp_?GetData@CStringArray@@QEBAPEBVCString@@XZ:PANYARGS
?GetData@CStringArray@@QEBAPEBVCString@@XZ TEXTEQU <__imp_?GetData@CStringArray@@QEBAPEBVCString@@XZ>
extern __imp_?GetHashTableSize@CMapStringToPtr@@QEBAIXZ:PANYARGS
?GetHashTableSize@CMapStringToPtr@@QEBAIXZ TEXTEQU <__imp_?GetHashTableSize@CMapStringToPtr@@QEBAIXZ>
extern __imp_?GetLength@CString@@QEBAHXZ:PANYARGS
?GetLength@CString@@QEBAHXZ TEXTEQU <__imp_?GetLength@CString@@QEBAHXZ>
extern __imp_?GetNextAssoc@CMapStringToPtr@@QEBAXAEAPEAU__POSITION@@AEAVCString@@AEAPEAX@Z:PANYARGS
?GetNextAssoc@CMapStringToPtr@@QEBAXAEAPEAU__POSITION@@AEAVCString@@AEAPEAX@Z TEXTEQU <__imp_?GetNextAssoc@CMapStringToPtr@@QEBAXAEAPEAU__POSITION@@AEAVCString@@AEAPEAX@Z>
extern __imp_?GetSize@CStringArray@@QEBAHXZ:PANYARGS
?GetSize@CStringArray@@QEBAHXZ TEXTEQU <__imp_?GetSize@CStringArray@@QEBAHXZ>
extern __imp_?GetStartPosition@CMapStringToPtr@@QEBAPEAU__POSITION@@XZ:PANYARGS
?GetStartPosition@CMapStringToPtr@@QEBAPEAU__POSITION@@XZ TEXTEQU <__imp_?GetStartPosition@CMapStringToPtr@@QEBAPEAU__POSITION@@XZ>
extern __imp_?GetUpperBound@CStringArray@@QEBAHXZ:PANYARGS
?GetUpperBound@CStringArray@@QEBAHXZ TEXTEQU <__imp_?GetUpperBound@CStringArray@@QEBAHXZ>
extern __imp_?HashKey@CMapStringToPtr@@QEBAIPEBG@Z:PANYARGS
?HashKey@CMapStringToPtr@@QEBAIPEBG@Z TEXTEQU <__imp_?HashKey@CMapStringToPtr@@QEBAIPEBG@Z>
extern __imp_?Init@CString@@IEAAXXZ:PANYARGS
?Init@CString@@IEAAXXZ TEXTEQU <__imp_?Init@CString@@IEAAXXZ>
extern __imp_?InitHashTable@CMapStringToPtr@@QEAAXIH@Z:PANYARGS
?InitHashTable@CMapStringToPtr@@QEAAXIH@Z TEXTEQU <__imp_?InitHashTable@CMapStringToPtr@@QEAAXIH@Z>
extern __imp_?InsertAt@CStringArray@@QEAAXHPEAV1@@Z:PANYARGS
?InsertAt@CStringArray@@QEAAXHPEAV1@@Z TEXTEQU <__imp_?InsertAt@CStringArray@@QEAAXHPEAV1@@Z>
extern __imp_?InsertAt@CStringArray@@QEAAXHPEBGH@Z:PANYARGS
?InsertAt@CStringArray@@QEAAXHPEBGH@Z TEXTEQU <__imp_?InsertAt@CStringArray@@QEAAXHPEBGH@Z>
extern __imp_?IsEmpty@CMapStringToPtr@@QEBAHXZ:PANYARGS
?IsEmpty@CMapStringToPtr@@QEBAHXZ TEXTEQU <__imp_?IsEmpty@CMapStringToPtr@@QEBAHXZ>
extern __imp_?IsEmpty@CString@@QEBAHXZ:PANYARGS
?IsEmpty@CString@@QEBAHXZ TEXTEQU <__imp_?IsEmpty@CString@@QEBAHXZ>
extern __imp_?Left@CString@@QEBA?AV1@H@Z:PANYARGS
?Left@CString@@QEBA?AV1@H@Z TEXTEQU <__imp_?Left@CString@@QEBA?AV1@H@Z>
extern __imp_?LoadStringW@CString@@QEAAHI@Z:PANYARGS
?LoadStringW@CString@@QEAAHI@Z TEXTEQU <__imp_?LoadStringW@CString@@QEAAHI@Z>
extern __imp_?Lock@CCriticalSection@@QEAAHXZ:PANYARGS
?Lock@CCriticalSection@@QEAAHXZ TEXTEQU <__imp_?Lock@CCriticalSection@@QEAAHXZ>
extern __imp_?Lock@CCriticalSection@@UEAAHK@Z:PANYARGS
?Lock@CCriticalSection@@UEAAHK@Z TEXTEQU <__imp_?Lock@CCriticalSection@@UEAAHK@Z>
extern __imp_?Lock@CSyncObject@@UEAAHK@Z:PANYARGS
?Lock@CSyncObject@@UEAAHK@Z TEXTEQU <__imp_?Lock@CSyncObject@@UEAAHK@Z>
extern __imp_?LockBuffer@CString@@QEAAPEAGXZ:PANYARGS
?LockBuffer@CString@@QEAAPEAGXZ TEXTEQU <__imp_?LockBuffer@CString@@QEAAPEAGXZ>
extern __imp_?Lookup@CMapStringToPtr@@QEBAHPEBGAEAPEAX@Z:PANYARGS
?Lookup@CMapStringToPtr@@QEBAHPEBGAEAPEAX@Z TEXTEQU <__imp_?Lookup@CMapStringToPtr@@QEBAHPEBGAEAPEAX@Z>
extern __imp_?LookupKey@CMapStringToPtr@@QEBAHPEBGAEAPEBG@Z:PANYARGS
?LookupKey@CMapStringToPtr@@QEBAHPEBGAEAPEBG@Z TEXTEQU <__imp_?LookupKey@CMapStringToPtr@@QEBAHPEBGAEAPEBG@Z>
extern __imp_?MakeLower@CString@@QEAAXXZ:PANYARGS
?MakeLower@CString@@QEAAXXZ TEXTEQU <__imp_?MakeLower@CString@@QEAAXXZ>
extern __imp_?MakeReverse@CString@@QEAAXXZ:PANYARGS
?MakeReverse@CString@@QEAAXXZ TEXTEQU <__imp_?MakeReverse@CString@@QEAAXXZ>
extern __imp_?MakeUpper@CString@@QEAAXXZ:PANYARGS
?MakeUpper@CString@@QEAAXXZ TEXTEQU <__imp_?MakeUpper@CString@@QEAAXXZ>
extern __imp_?Mid@CString@@QEBA?AV1@H@Z:PANYARGS
?Mid@CString@@QEBA?AV1@H@Z TEXTEQU <__imp_?Mid@CString@@QEBA?AV1@H@Z>
extern __imp_?Mid@CString@@QEBA?AV1@HH@Z:PANYARGS
?Mid@CString@@QEBA?AV1@HH@Z TEXTEQU <__imp_?Mid@CString@@QEBA?AV1@HH@Z>
extern __imp_?NewAssoc@CMapStringToPtr@@IEAAPEAUCAssoc@1@XZ:PANYARGS
?NewAssoc@CMapStringToPtr@@IEAAPEAUCAssoc@1@XZ TEXTEQU <__imp_?NewAssoc@CMapStringToPtr@@IEAAPEAUCAssoc@1@XZ>
extern __imp_?Release@CString@@IEAAXXZ:PANYARGS
?Release@CString@@IEAAXXZ TEXTEQU <__imp_?Release@CString@@IEAAXXZ>
extern __imp_?Release@CString@@KAXPEAUCStringData@@@Z:PANYARGS
?Release@CString@@KAXPEAUCStringData@@@Z TEXTEQU <__imp_?Release@CString@@KAXPEAUCStringData@@@Z>
extern __imp_?ReleaseBuffer@CString@@QEAAXH@Z:PANYARGS
?ReleaseBuffer@CString@@QEAAXH@Z TEXTEQU <__imp_?ReleaseBuffer@CString@@QEAAXH@Z>
extern __imp_?RemoveAll@CMapStringToPtr@@QEAAXXZ:PANYARGS
?RemoveAll@CMapStringToPtr@@QEAAXXZ TEXTEQU <__imp_?RemoveAll@CMapStringToPtr@@QEAAXXZ>
extern __imp_?RemoveAll@CStringArray@@QEAAXXZ:PANYARGS
?RemoveAll@CStringArray@@QEAAXXZ TEXTEQU <__imp_?RemoveAll@CStringArray@@QEAAXXZ>
extern __imp_?RemoveAt@CStringArray@@QEAAXHH@Z:PANYARGS
?RemoveAt@CStringArray@@QEAAXHH@Z TEXTEQU <__imp_?RemoveAt@CStringArray@@QEAAXHH@Z>
extern __imp_?RemoveKey@CMapStringToPtr@@QEAAHPEBG@Z:PANYARGS
?RemoveKey@CMapStringToPtr@@QEAAHPEBG@Z TEXTEQU <__imp_?RemoveKey@CMapStringToPtr@@QEAAHPEBG@Z>
extern __imp_?ReverseFind@CString@@QEBAHG@Z:PANYARGS
?ReverseFind@CString@@QEBAHG@Z TEXTEQU <__imp_?ReverseFind@CString@@QEBAHG@Z>
extern __imp_?Right@CString@@QEBA?AV1@H@Z:PANYARGS
?Right@CString@@QEBA?AV1@H@Z TEXTEQU <__imp_?Right@CString@@QEBA?AV1@H@Z>
extern __imp_?SafeStrlen@CString@@KAHPEBG@Z:PANYARGS
?SafeStrlen@CString@@KAHPEBG@Z TEXTEQU <__imp_?SafeStrlen@CString@@KAHPEBG@Z>
extern __imp_?SetAt@CMapStringToPtr@@QEAAXPEBGPEAX@Z:PANYARGS
?SetAt@CMapStringToPtr@@QEAAXPEBGPEAX@Z TEXTEQU <__imp_?SetAt@CMapStringToPtr@@QEAAXPEBGPEAX@Z>
extern __imp_?SetAt@CString@@QEAAXHG@Z:PANYARGS
?SetAt@CString@@QEAAXHG@Z TEXTEQU <__imp_?SetAt@CString@@QEAAXHG@Z>
extern __imp_?SetAt@CStringArray@@QEAAXHPEBG@Z:PANYARGS
?SetAt@CStringArray@@QEAAXHPEBG@Z TEXTEQU <__imp_?SetAt@CStringArray@@QEAAXHPEBG@Z>
extern __imp_?SetAtGrow@CStringArray@@QEAAXHPEBG@Z:PANYARGS
?SetAtGrow@CStringArray@@QEAAXHPEBG@Z TEXTEQU <__imp_?SetAtGrow@CStringArray@@QEAAXHPEBG@Z>
extern __imp_?SetSize@CStringArray@@QEAAXHH@Z:PANYARGS
?SetSize@CStringArray@@QEAAXHH@Z TEXTEQU <__imp_?SetSize@CStringArray@@QEAAXHH@Z>
extern __imp_?SpanExcluding@CString@@QEBA?AV1@PEBG@Z:PANYARGS
?SpanExcluding@CString@@QEBA?AV1@PEBG@Z TEXTEQU <__imp_?SpanExcluding@CString@@QEBA?AV1@PEBG@Z>
extern __imp_?SpanIncluding@CString@@QEBA?AV1@PEBG@Z:PANYARGS
?SpanIncluding@CString@@QEBA?AV1@PEBG@Z TEXTEQU <__imp_?SpanIncluding@CString@@QEBA?AV1@PEBG@Z>
extern __imp_?TrimLeft@CString@@QEAAXXZ:PANYARGS
?TrimLeft@CString@@QEAAXXZ TEXTEQU <__imp_?TrimLeft@CString@@QEAAXXZ>
extern __imp_?TrimRight@CString@@QEAAXXZ:PANYARGS
?TrimRight@CString@@QEAAXXZ TEXTEQU <__imp_?TrimRight@CString@@QEAAXXZ>
extern __imp_?Unlock@CCriticalSection@@UEAAHXZ:PANYARGS
?Unlock@CCriticalSection@@UEAAHXZ TEXTEQU <__imp_?Unlock@CCriticalSection@@UEAAHXZ>
extern __imp_?Unlock@CSyncObject@@UEAAHJPEAJ@Z:PANYARGS
?Unlock@CSyncObject@@UEAAHJPEAJ@Z TEXTEQU <__imp_?Unlock@CSyncObject@@UEAAHJPEAJ@Z>
extern __imp_?UnlockBuffer@CString@@QEAAXXZ:PANYARGS
?UnlockBuffer@CString@@QEAAXXZ TEXTEQU <__imp_?UnlockBuffer@CString@@QEAAXXZ>
extern __imp_?data@CPlex@@QEAAPEAXXZ:PANYARGS
?data@CPlex@@QEAAPEAXXZ TEXTEQU <__imp_?data@CPlex@@QEAAPEAXXZ>
