extern __imp_SnmpMgrClose:PANYARGS
SnmpMgrClose TEXTEQU <__imp_SnmpMgrClose>
extern __imp_SnmpMgrCtl:PANYARGS
SnmpMgrCtl TEXTEQU <__imp_SnmpMgrCtl>
extern __imp_SnmpMgrGetTrap:PANYARGS
SnmpMgrGetTrap TEXTEQU <__imp_SnmpMgrGetTrap>
extern __imp_SnmpMgrGetTrapEx:PANYARGS
SnmpMgrGetTrapEx TEXTEQU <__imp_SnmpMgrGetTrapEx>
extern __imp_SnmpMgrOidToStr:PANYARGS
SnmpMgrOidToStr TEXTEQU <__imp_SnmpMgrOidToStr>
extern __imp_SnmpMgrOpen:PANYARGS
SnmpMgrOpen TEXTEQU <__imp_SnmpMgrOpen>
extern __imp_SnmpMgrRequest:PANYARGS
SnmpMgrRequest TEXTEQU <__imp_SnmpMgrRequest>
extern __imp_SnmpMgrStrToOid:PANYARGS
SnmpMgrStrToOid TEXTEQU <__imp_SnmpMgrStrToOid>
extern __imp_SnmpMgrTrapListen:PANYARGS
SnmpMgrTrapListen TEXTEQU <__imp_SnmpMgrTrapListen>
