extern __imp_MigDllAddDllToListW:PANYARGS
MigDllAddDllToListW TEXTEQU <__imp_MigDllAddDllToListW>
extern __imp_MigDllApplySystemSettingsW:PANYARGS
MigDllApplySystemSettingsW TEXTEQU <__imp_MigDllApplySystemSettingsW>
extern __imp_MigDllCloseW:PANYARGS
MigDllCloseW TEXTEQU <__imp_MigDllCloseW>
extern __imp_MigDllCreateList:PANYARGS
MigDllCreateList TEXTEQU <__imp_MigDllCreateList>
extern __imp_MigDllEnumFirstW:PANYARGS
MigDllEnumFirstW TEXTEQU <__imp_MigDllEnumFirstW>
extern __imp_MigDllEnumNextW:PANYARGS
MigDllEnumNextW TEXTEQU <__imp_MigDllEnumNextW>
extern __imp_MigDllFreeList:PANYARGS
MigDllFreeList TEXTEQU <__imp_MigDllFreeList>
extern __imp_MigDllInit:PANYARGS
MigDllInit TEXTEQU <__imp_MigDllInit>
extern __imp_MigDllInitializeDstW:PANYARGS
MigDllInitializeDstW TEXTEQU <__imp_MigDllInitializeDstW>
extern __imp_MigDllOpenW:PANYARGS
MigDllOpenW TEXTEQU <__imp_MigDllOpenW>
extern __imp_MigDllShutdown:PANYARGS
MigDllShutdown TEXTEQU <__imp_MigDllShutdown>
