extern __imp_IsConvertINetStringAvailable:PANYARGS
IsConvertINetStringAvailable TEXTEQU <__imp_IsConvertINetStringAvailable>
extern __imp_ConvertINetString:PANYARGS
ConvertINetString TEXTEQU <__imp_ConvertINetString>
extern __imp_ConvertINetUnicodeToMultiByte:PANYARGS
ConvertINetUnicodeToMultiByte TEXTEQU <__imp_ConvertINetUnicodeToMultiByte>
extern __imp_ConvertINetMultiByteToUnicode:PANYARGS
ConvertINetMultiByteToUnicode TEXTEQU <__imp_ConvertINetMultiByteToUnicode>
extern __imp_ConvertINetReset:PANYARGS
ConvertINetReset TEXTEQU <__imp_ConvertINetReset>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetGlobalFontLinkObject:PANYARGS
GetGlobalFontLinkObject TEXTEQU <__imp_GetGlobalFontLinkObject>
extern __imp_LcidToRfc1766A:PANYARGS
LcidToRfc1766  TEXTEQU <__imp_LcidToRfc1766A>
extern __imp_LcidToRfc1766W:PANYARGS
LcidToRfc1766W TEXTEQU <__imp_LcidToRfc1766W>
extern __imp_Rfc1766ToLcidA:PANYARGS
Rfc1766ToLcid  TEXTEQU <__imp_Rfc1766ToLcidA>
extern __imp_Rfc1766ToLcidW:PANYARGS
Rfc1766ToLcidW TEXTEQU <__imp_Rfc1766ToLcidW>
