extern __imp_??0?$CEventLock@UAppEvents@@@@QEAA@XZ:PANYARGS
??0?$CEventLock@UAppEvents@@@@QEAA@XZ TEXTEQU <__imp_??0?$CEventLock@UAppEvents@@@@QEAA@XZ>
extern __imp_??0CEventBuffer@@QEAA@AEBV0@@Z:PANYARGS
??0CEventBuffer@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CEventBuffer@@QEAA@AEBV0@@Z>
extern __imp_??0CEventBuffer@@QEAA@XZ:PANYARGS
??0CEventBuffer@@QEAA@XZ TEXTEQU <__imp_??0CEventBuffer@@QEAA@XZ>
extern __imp_??0CMMCStrongReferences@@AEAA@XZ:PANYARGS
??0CMMCStrongReferences@@AEAA@XZ TEXTEQU <__imp_??0CMMCStrongReferences@@AEAA@XZ>
extern __imp_??0SC@mmcerror@@QEAA@AEBV01@@Z:PANYARGS
??0SC@mmcerror@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0SC@mmcerror@@QEAA@AEBV01@@Z>
extern __imp_??0SC@mmcerror@@QEAA@J@Z:PANYARGS
??0SC@mmcerror@@QEAA@J@Z TEXTEQU <__imp_??0SC@mmcerror@@QEAA@J@Z>
extern __imp_??1?$CEventLock@UAppEvents@@@@QEAA@XZ:PANYARGS
??1?$CEventLock@UAppEvents@@@@QEAA@XZ TEXTEQU <__imp_??1?$CEventLock@UAppEvents@@@@QEAA@XZ>
extern __imp_??1CEventBuffer@@QEAA@XZ:PANYARGS
??1CEventBuffer@@QEAA@XZ TEXTEQU <__imp_??1CEventBuffer@@QEAA@XZ>
extern __imp_??1SC@mmcerror@@QEAA@XZ:PANYARGS
??1SC@mmcerror@@QEAA@XZ TEXTEQU <__imp_??1SC@mmcerror@@QEAA@XZ>
extern __imp_??4?$CEventLock@UAppEvents@@@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CEventLock@UAppEvents@@@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CEventLock@UAppEvents@@@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CEventBuffer@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CEventBuffer@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CEventBuffer@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CMMCStrongReferences@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CMMCStrongReferences@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CMMCStrongReferences@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4SC@mmcerror@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4SC@mmcerror@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4SC@mmcerror@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4SC@mmcerror@@QEAAAEAV01@J@Z:PANYARGS
??4SC@mmcerror@@QEAAAEAV01@J@Z TEXTEQU <__imp_??4SC@mmcerror@@QEAAAEAV01@J@Z>
extern __imp_??7SC@mmcerror@@QEBAHXZ:PANYARGS
??7SC@mmcerror@@QEBAHXZ TEXTEQU <__imp_??7SC@mmcerror@@QEBAHXZ>
extern __imp_??8SC@mmcerror@@QEBA_NAEBV01@@Z:PANYARGS
??8SC@mmcerror@@QEBA_NAEBV01@@Z TEXTEQU <__imp_??8SC@mmcerror@@QEBA_NAEBV01@@Z>
extern __imp_??8SC@mmcerror@@QEBA_NJ@Z:PANYARGS
??8SC@mmcerror@@QEBA_NJ@Z TEXTEQU <__imp_??8SC@mmcerror@@QEBA_NJ@Z>
extern __imp_??9SC@mmcerror@@QEBA_NAEBV01@@Z:PANYARGS
??9SC@mmcerror@@QEBA_NAEBV01@@Z TEXTEQU <__imp_??9SC@mmcerror@@QEBA_NAEBV01@@Z>
extern __imp_??9SC@mmcerror@@QEBA_NJ@Z:PANYARGS
??9SC@mmcerror@@QEBA_NJ@Z TEXTEQU <__imp_??9SC@mmcerror@@QEBA_NJ@Z>
extern __imp_??BSC@mmcerror@@QEBA_NXZ:PANYARGS
??BSC@mmcerror@@QEBA_NXZ TEXTEQU <__imp_??BSC@mmcerror@@QEBA_NXZ>
extern __imp_??_FSC@mmcerror@@QEAAXXZ:PANYARGS
??_FSC@mmcerror@@QEAAXXZ TEXTEQU <__imp_??_FSC@mmcerror@@QEAAXXZ>
extern __imp_?AddItem@BookKeeping@@SAJAEAVItemHandle@@@Z:PANYARGS
?AddItem@BookKeeping@@SAJAEAVItemHandle@@@Z TEXTEQU <__imp_?AddItem@BookKeeping@@SAJAEAVItemHandle@@@Z>
extern __imp_?AddRef@CMMCStrongReferences@@SAKXZ:PANYARGS
?AddRef@CMMCStrongReferences@@SAKXZ TEXTEQU <__imp_?AddRef@CMMCStrongReferences@@SAKXZ>
extern __imp_?AddSnapin@BookKeeping@@SAJPEBGAEAH@Z:PANYARGS
?AddSnapin@BookKeeping@@SAJPEBGAEAH@Z TEXTEQU <__imp_?AddSnapin@BookKeeping@@SAJPEBGAEAH@Z>
extern __imp_?AddSnapinInterface@BookKeeping@@SA_NPEAUIUnknown@@PEBGAEAH@Z:PANYARGS
?AddSnapinInterface@BookKeeping@@SA_NPEAUIUnknown@@PEBGAEAH@Z TEXTEQU <__imp_?AddSnapinInterface@BookKeeping@@SA_NPEAUIUnknown@@PEBGAEAH@Z>
extern __imp_?CheckCallingThreadID@SC@mmcerror@@QEAAXXZ:PANYARGS
?CheckCallingThreadID@SC@mmcerror@@QEAAXXZ TEXTEQU <__imp_?CheckCallingThreadID@SC@mmcerror@@QEAAXXZ>
extern __imp_?Clear@SC@mmcerror@@QEAAXXZ:PANYARGS
?Clear@SC@mmcerror@@QEAAXXZ TEXTEQU <__imp_?Clear@SC@mmcerror@@QEAAXXZ>
extern __imp_?DumpWatsonTables@BookKeeping@@SAJPEAXPEBGH@Z:PANYARGS
?DumpWatsonTables@BookKeeping@@SAJPEAXPEBGH@Z TEXTEQU <__imp_?DumpWatsonTables@BookKeeping@@SAJPEAXPEBGH@Z>
extern __imp_?EnableDiagnosticMessageBox@BookKeeping@@SA_N_N@Z:PANYARGS
?EnableDiagnosticMessageBox@BookKeeping@@SA_N_N@Z TEXTEQU <__imp_?EnableDiagnosticMessageBox@BookKeeping@@SA_N_N@Z>
extern __imp_?ExceptionFilter@CMMCWatsonAPI@@SAJPEAU_EXCEPTION_POINTERS@@H@Z:PANYARGS
?ExceptionFilter@CMMCWatsonAPI@@SAJPEAU_EXCEPTION_POINTERS@@H@Z TEXTEQU <__imp_?ExceptionFilter@CMMCWatsonAPI@@SAJPEAU_EXCEPTION_POINTERS@@H@Z>
extern __imp_?FatalError@SC@mmcerror@@QEBAXXZ:PANYARGS
?FatalError@SC@mmcerror@@QEBAXXZ TEXTEQU <__imp_?FatalError@SC@mmcerror@@QEBAXXZ>
extern __imp_?FindAllSnapinUIThreads@BookKeeping@@SAJHPEAPEAKPEAK@Z:PANYARGS
?FindAllSnapinUIThreads@BookKeeping@@SAJHPEAPEAKPEAK@Z TEXTEQU <__imp_?FindAllSnapinUIThreads@BookKeeping@@SAJHPEAPEAKPEAK@Z>
extern __imp_?FindAllSnapinUIThreads@BookKeeping@@SAJPEAPEAKPEAK@Z:PANYARGS
?FindAllSnapinUIThreads@BookKeeping@@SAJPEAPEAKPEAK@Z TEXTEQU <__imp_?FindAllSnapinUIThreads@BookKeeping@@SAJPEAPEAKPEAK@Z>
extern __imp_?FindItem@BookKeeping@@SAPEAVItemHandle@@PEAX@Z:PANYARGS
?FindItem@BookKeeping@@SAPEAVItemHandle@@PEAX@Z TEXTEQU <__imp_?FindItem@BookKeeping@@SAPEAVItemHandle@@PEAX@Z>
extern __imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@H@Z:PANYARGS
?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@H@Z TEXTEQU <__imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@H@Z>
extern __imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEAUIUnknown@@@Z:PANYARGS
?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEAUIUnknown@@@Z TEXTEQU <__imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEAUIUnknown@@@Z>
extern __imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEBG@Z:PANYARGS
?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEBG@Z TEXTEQU <__imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEBG@Z>
extern __imp_?ForceException@CMMCWatsonAPI@@SAXH@Z:PANYARGS
?ForceException@CMMCWatsonAPI@@SAXH@Z TEXTEQU <__imp_?ForceException@CMMCWatsonAPI@@SAXH@Z>
extern __imp_?FormatErrorIds@@YAXIVSC@mmcerror@@IPEAG@Z:PANYARGS
?FormatErrorIds@@YAXIVSC@mmcerror@@IPEAG@Z TEXTEQU <__imp_?FormatErrorIds@@YAXIVSC@mmcerror@@IPEAG@Z>
extern __imp_?FormatErrorShort@@YAXVSC@mmcerror@@IPEAG@Z:PANYARGS
?FormatErrorShort@@YAXVSC@mmcerror@@IPEAG@Z TEXTEQU <__imp_?FormatErrorShort@@YAXVSC@mmcerror@@IPEAG@Z>
extern __imp_?FormatErrorString@@YAXPEBGVSC@mmcerror@@IPEAGH@Z:PANYARGS
?FormatErrorString@@YAXPEBGVSC@mmcerror@@IPEAGH@Z TEXTEQU <__imp_?FormatErrorString@@YAXPEBGVSC@mmcerror@@IPEAGH@Z>
extern __imp_?FromLastError@SC@mmcerror@@QEAAAEAV12@XZ:PANYARGS
?FromLastError@SC@mmcerror@@QEAAAEAV12@XZ TEXTEQU <__imp_?FromLastError@SC@mmcerror@@QEAAAEAV12@XZ>
extern __imp_?FromMMC@SC@mmcerror@@QEAAAEAV12@J@Z:PANYARGS
?FromMMC@SC@mmcerror@@QEAAAEAV12@J@Z TEXTEQU <__imp_?FromMMC@SC@mmcerror@@QEAAAEAV12@J@Z>
extern __imp_?FromWin32@SC@mmcerror@@QEAAAEAV12@J@Z:PANYARGS
?FromWin32@SC@mmcerror@@QEAAAEAV12@J@Z TEXTEQU <__imp_?FromWin32@SC@mmcerror@@QEAAAEAV12@J@Z>
extern __imp_?FxSnapinException@BookKeeping@@SA_NHPEBG000H@Z:PANYARGS
?FxSnapinException@BookKeeping@@SA_NHPEBG000H@Z TEXTEQU <__imp_?FxSnapinException@BookKeeping@@SA_NHPEBG000H@Z>
extern __imp_?GetCode@SC@mmcerror@@QEBAJXZ:PANYARGS
?GetCode@SC@mmcerror@@QEBAJXZ TEXTEQU <__imp_?GetCode@SC@mmcerror@@QEBAJXZ>
extern __imp_?GetComObjectEventSource@@YAAEAV?$CEventSource@VCComObjectObserver@@VCVoid@@V2@V2@V2@@@XZ:PANYARGS
?GetComObjectEventSource@@YAAEAV?$CEventSource@VCComObjectObserver@@VCVoid@@V2@V2@V2@@@XZ TEXTEQU <__imp_?GetComObjectEventSource@@YAAEAV?$CEventSource@VCComObjectObserver@@VCVoid@@V2@V2@V2@@@XZ>
extern __imp_?GetErrorMessage@SC@mmcerror@@QEBAXIPEAG@Z:PANYARGS
?GetErrorMessage@SC@mmcerror@@QEBAXIPEAG@Z TEXTEQU <__imp_?GetErrorMessage@SC@mmcerror@@QEBAXIPEAG@Z>
extern __imp_?GetEventBuffer@@YAAEAVCEventBuffer@@XZ:PANYARGS
?GetEventBuffer@@YAAEAVCEventBuffer@@XZ TEXTEQU <__imp_?GetEventBuffer@@YAAEAVCEventBuffer@@XZ>
extern __imp_?GetFacility@SC@mmcerror@@AEBA?AW4facility_type@12@XZ:PANYARGS
?GetFacility@SC@mmcerror@@AEBA?AW4facility_type@12@XZ TEXTEQU <__imp_?GetFacility@SC@mmcerror@@AEBA?AW4facility_type@12@XZ>
extern __imp_?GetFunctionName@SC@mmcerror@@QEBAPEBGXZ:PANYARGS
?GetFunctionName@SC@mmcerror@@QEBAPEBGXZ TEXTEQU <__imp_?GetFunctionName@SC@mmcerror@@QEBAPEBGXZ>
extern __imp_?GetHWnd@SC@mmcerror@@SAPEAUHWND__@@XZ:PANYARGS
?GetHWnd@SC@mmcerror@@SAPEAUHWND__@@XZ TEXTEQU <__imp_?GetHWnd@SC@mmcerror@@SAPEAUHWND__@@XZ>
extern __imp_?GetHelpFile@SC@mmcerror@@SAPEBGXZ:PANYARGS
?GetHelpFile@SC@mmcerror@@SAPEBGXZ TEXTEQU <__imp_?GetHelpFile@SC@mmcerror@@SAPEBGXZ>
extern __imp_?GetHelpID@SC@mmcerror@@QEAAKXZ:PANYARGS
?GetHelpID@SC@mmcerror@@QEAAKXZ TEXTEQU <__imp_?GetHelpID@SC@mmcerror@@QEAAKXZ>
extern __imp_?GetHinst@SC@mmcerror@@SAPEAUHINSTANCE__@@XZ:PANYARGS
?GetHinst@SC@mmcerror@@SAPEAUHINSTANCE__@@XZ TEXTEQU <__imp_?GetHinst@SC@mmcerror@@SAPEAUHINSTANCE__@@XZ>
extern __imp_?GetMainThreadID@SC@mmcerror@@SAKXZ:PANYARGS
?GetMainThreadID@SC@mmcerror@@SAKXZ TEXTEQU <__imp_?GetMainThreadID@SC@mmcerror@@SAKXZ>
extern __imp_?GetModalHWND@SC@mmcerror@@SAPEAUHWND__@@XZ:PANYARGS
?GetModalHWND@SC@mmcerror@@SAPEAUHWND__@@XZ TEXTEQU <__imp_?GetModalHWND@SC@mmcerror@@SAPEAUHWND__@@XZ>
extern __imp_?GetNewSnapinInstanceId@BookKeeping@@SAHXZ:PANYARGS
?GetNewSnapinInstanceId@BookKeeping@@SAHXZ TEXTEQU <__imp_?GetNewSnapinInstanceId@BookKeeping@@SAHXZ>
extern __imp_?GetSingletonObject@CMMCStrongReferences@@CAAEAV1@XZ:PANYARGS
?GetSingletonObject@CMMCStrongReferences@@CAAEAV1@XZ TEXTEQU <__imp_?GetSingletonObject@CMMCStrongReferences@@CAAEAV1@XZ>
extern __imp_?GetSnapinModuleName@BookKeeping@@SAPEBGH@Z:PANYARGS
?GetSnapinModuleName@BookKeeping@@SAPEBGH@Z TEXTEQU <__imp_?GetSnapinModuleName@BookKeeping@@SAPEBGH@Z>
extern __imp_?GetSnapinName@BookKeeping@@SAPEBGH@Z:PANYARGS
?GetSnapinName@BookKeeping@@SAPEBGH@Z TEXTEQU <__imp_?GetSnapinName@BookKeeping@@SAPEBGH@Z>
extern __imp_?GetSnapinName@SC@mmcerror@@QEBAPEBGXZ:PANYARGS
?GetSnapinName@SC@mmcerror@@QEBAPEBGXZ TEXTEQU <__imp_?GetSnapinName@SC@mmcerror@@QEBAPEBGXZ>
extern __imp_?GetStringModule@@YAPEAUHINSTANCE__@@XZ:PANYARGS
?GetStringModule@@YAPEAUHINSTANCE__@@XZ TEXTEQU <__imp_?GetStringModule@@YAPEAUHINSTANCE__@@XZ>
extern __imp_?HrFromSc@@YAJAEBVSC@mmcerror@@@Z:PANYARGS
?HrFromSc@@YAJAEBVSC@mmcerror@@@Z TEXTEQU <__imp_?HrFromSc@@YAJAEBVSC@mmcerror@@@Z>
extern __imp_?InitInstance@BookKeeping@@SAJXZ:PANYARGS
?InitInstance@BookKeeping@@SAJXZ TEXTEQU <__imp_?InitInstance@BookKeeping@@SAJXZ>
extern __imp_?InterfaceFailure@BookKeeping@@SAXHPEBG0@Z:PANYARGS
?InterfaceFailure@BookKeeping@@SAXHPEBG0@Z TEXTEQU <__imp_?InterfaceFailure@BookKeeping@@SAXHPEBG0@Z>
extern __imp_?InterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@@Z:PANYARGS
?InterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@@Z TEXTEQU <__imp_?InterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@@Z>
extern __imp_?InterfaceNotFound@BookKeeping@@SAXHPEBG@Z:PANYARGS
?InterfaceNotFound@BookKeeping@@SAXHPEBG@Z TEXTEQU <__imp_?InterfaceNotFound@BookKeeping@@SAXHPEBG@Z>
extern __imp_?InternalAddRef@CMMCStrongReferences@@AEAAKXZ:PANYARGS
?InternalAddRef@CMMCStrongReferences@@AEAAKXZ TEXTEQU <__imp_?InternalAddRef@CMMCStrongReferences@@AEAAKXZ>
extern __imp_?InternalLastRefReleased@CMMCStrongReferences@@AEAA_NXZ:PANYARGS
?InternalLastRefReleased@CMMCStrongReferences@@AEAA_NXZ TEXTEQU <__imp_?InternalLastRefReleased@CMMCStrongReferences@@AEAA_NXZ>
extern __imp_?InternalRelease@CMMCStrongReferences@@AEAAKXZ:PANYARGS
?InternalRelease@CMMCStrongReferences@@AEAAKXZ TEXTEQU <__imp_?InternalRelease@CMMCStrongReferences@@AEAAKXZ>
extern __imp_?InvalidInterface@BookKeeping@@SAXHPEBG0@Z:PANYARGS
?InvalidInterface@BookKeeping@@SAXHPEBG0@Z TEXTEQU <__imp_?InvalidInterface@BookKeeping@@SAXHPEBG0@Z>
extern __imp_?InvalidMMCInterface@BookKeeping@@SAXHPEBG0@Z:PANYARGS
?InvalidMMCInterface@BookKeeping@@SAXHPEBG0@Z TEXTEQU <__imp_?InvalidMMCInterface@BookKeeping@@SAXHPEBG0@Z>
extern __imp_?InvalidMMCInterfaceRelease@BookKeeping@@SAXHPEBG0@Z:PANYARGS
?InvalidMMCInterfaceRelease@BookKeeping@@SAXHPEBG0@Z TEXTEQU <__imp_?InvalidMMCInterfaceRelease@BookKeeping@@SAXHPEBG0@Z>
extern __imp_?IsError@SC@mmcerror@@QEBA_NXZ:PANYARGS
?IsError@SC@mmcerror@@QEBA_NXZ TEXTEQU <__imp_?IsError@SC@mmcerror@@QEBA_NXZ>
extern __imp_?IsLocked@CEventBuffer@@QEAA_NXZ:PANYARGS
?IsLocked@CEventBuffer@@QEAA_NXZ TEXTEQU <__imp_?IsLocked@CEventBuffer@@QEAA_NXZ>
extern __imp_?IsValid@ItemHandle@@SA_NPEBV1@@Z:PANYARGS
?IsValid@ItemHandle@@SA_NPEBV1@@Z TEXTEQU <__imp_?IsValid@ItemHandle@@SA_NPEBV1@@Z>
extern __imp_?LKResult2HRESULT@BookKeeping@@SAJ_J@Z:PANYARGS
?LKResult2HRESULT@BookKeeping@@SAJ_J@Z TEXTEQU <__imp_?LKResult2HRESULT@BookKeeping@@SAJ_J@Z>
extern __imp_?LastRefReleased@CMMCStrongReferences@@SA_NXZ:PANYARGS
?LastRefReleased@CMMCStrongReferences@@SA_NXZ TEXTEQU <__imp_?LastRefReleased@CMMCStrongReferences@@SA_NXZ>
extern __imp_?LoadStandardOverlays@@YAJPEAU_IMAGELIST@@HPEAH1@Z:PANYARGS
?LoadStandardOverlays@@YAJPEAU_IMAGELIST@@HPEAH1@Z TEXTEQU <__imp_?LoadStandardOverlays@@YAJPEAU_IMAGELIST@@HPEAH1@Z>
extern __imp_?Lock@CEventBuffer@@QEAAXXZ:PANYARGS
?Lock@CEventBuffer@@QEAAXXZ TEXTEQU <__imp_?Lock@CEventBuffer@@QEAAXXZ>
extern __imp_?MMCErrorBox@@YAHII@Z:PANYARGS
?MMCErrorBox@@YAHII@Z TEXTEQU <__imp_?MMCErrorBox@@YAHII@Z>
extern __imp_?MMCErrorBox@@YAHIVSC@mmcerror@@I@Z:PANYARGS
?MMCErrorBox@@YAHIVSC@mmcerror@@I@Z TEXTEQU <__imp_?MMCErrorBox@@YAHIVSC@mmcerror@@I@Z>
extern __imp_?MMCErrorBox@@YAHPEBGI@Z:PANYARGS
?MMCErrorBox@@YAHPEBGI@Z TEXTEQU <__imp_?MMCErrorBox@@YAHPEBGI@Z>
extern __imp_?MMCErrorBox@@YAHPEBGVSC@mmcerror@@I@Z:PANYARGS
?MMCErrorBox@@YAHPEBGVSC@mmcerror@@I@Z TEXTEQU <__imp_?MMCErrorBox@@YAHPEBGVSC@mmcerror@@I@Z>
extern __imp_?MMCErrorBox@@YAHVSC@mmcerror@@I@Z:PANYARGS
?MMCErrorBox@@YAHVSC@mmcerror@@I@Z TEXTEQU <__imp_?MMCErrorBox@@YAHVSC@mmcerror@@I@Z>
extern __imp_?MMCInterfaceError@BookKeeping@@SAXHPEBG0@Z:PANYARGS
?MMCInterfaceError@BookKeeping@@SAXHPEBG0@Z TEXTEQU <__imp_?MMCInterfaceError@BookKeeping@@SAXHPEBG0@Z>
extern __imp_?MMCInterfaceLeak@BookKeeping@@SAXHPEBG@Z:PANYARGS
?MMCInterfaceLeak@BookKeeping@@SAXHPEBG@Z TEXTEQU <__imp_?MMCInterfaceLeak@BookKeeping@@SAXHPEBG@Z>
extern __imp_?MMCInterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@W4_SnapinError@1@@Z:PANYARGS
?MMCInterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@W4_SnapinError@1@@Z TEXTEQU <__imp_?MMCInterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@W4_SnapinError@1@@Z>
extern __imp_?MMCNullInterface@BookKeeping@@SAXHPEBG0@Z:PANYARGS
?MMCNullInterface@BookKeeping@@SAXHPEBG0@Z TEXTEQU <__imp_?MMCNullInterface@BookKeeping@@SAXHPEBG0@Z>
extern __imp_?MMCUpdateRegistry@@YAJHPEBVCObjectRegParams@@PEBVCControlRegParams@@@Z:PANYARGS
?MMCUpdateRegistry@@YAJHPEBVCObjectRegParams@@PEBVCControlRegParams@@@Z TEXTEQU <__imp_?MMCUpdateRegistry@@YAJHPEBVCObjectRegParams@@PEBVCControlRegParams@@@Z>
extern __imp_?MMC_PickIconDlg@@YA_JPEAUHWND__@@PEAGIPEAH@Z:PANYARGS
?MMC_PickIconDlg@@YA_JPEAUHWND__@@PEAGIPEAH@Z TEXTEQU <__imp_?MMC_PickIconDlg@@YA_JPEAUHWND__@@PEAGIPEAH@Z>
extern __imp_?MakeSc@SC@mmcerror@@AEAAXW4facility_type@12@J@Z:PANYARGS
?MakeSc@SC@mmcerror@@AEAAXW4facility_type@12@J@Z TEXTEQU <__imp_?MakeSc@SC@mmcerror@@AEAAXW4facility_type@12@J@Z>
extern __imp_?RegisterSnapinInterfaceErrorHandler@BookKeeping@@SAP6A_NAEAVSnapinBookkeepingInfo@@W4_SnapinError@1@PEBG222KPEAU_EXCEPTION_POINTERS@@@ZP6A_N012222K3@Z@Z:PANYARGS
?RegisterSnapinInterfaceErrorHandler@BookKeeping@@SAP6A_NAEAVSnapinBookkeepingInfo@@W4_SnapinError@1@PEBG222KPEAU_EXCEPTION_POINTERS@@@ZP6A_N012222K3@Z@Z TEXTEQU <__imp_?RegisterSnapinInterfaceErrorHandler@BookKeeping@@SAP6A_NAEAVSnapinBookkeepingInfo@@W4_SnapinError@1@PEBG222KPEAU_EXCEPTION_POINTERS@@@ZP6A_N012222K3@Z@Z>
extern __imp_?RegisterThread@BookKeeping@@SAJHHKW4SnapinThreadFlags@1@@Z:PANYARGS
?RegisterThread@BookKeeping@@SAJHHKW4SnapinThreadFlags@1@@Z TEXTEQU <__imp_?RegisterThread@BookKeeping@@SAJHHKW4SnapinThreadFlags@1@@Z>
extern __imp_?Release@CMMCStrongReferences@@SAKXZ:PANYARGS
?Release@CMMCStrongReferences@@SAKXZ TEXTEQU <__imp_?Release@CMMCStrongReferences@@SAKXZ>
extern __imp_?ReleaseSnapinInterface@BookKeeping@@SAJPEAUIUnknown@@H@Z:PANYARGS
?ReleaseSnapinInterface@BookKeeping@@SAJPEAUIUnknown@@H@Z TEXTEQU <__imp_?ReleaseSnapinInterface@BookKeeping@@SAJPEAUIUnknown@@H@Z>
extern __imp_?RemoveItem@BookKeeping@@SAJPEAX@Z:PANYARGS
?RemoveItem@BookKeeping@@SAJPEAX@Z TEXTEQU <__imp_?RemoveItem@BookKeeping@@SAJPEAX@Z>
extern __imp_?SCODEFromSc@@YAJAEBVSC@mmcerror@@@Z:PANYARGS
?SCODEFromSc@@YAJAEBVSC@mmcerror@@@Z TEXTEQU <__imp_?SCODEFromSc@@YAJAEBVSC@mmcerror@@@Z>
extern __imp_?ScEmitOrPostpone@CEventBuffer@@QEAA?AVSC@mmcerror@@PEAUIDispatch@@JPEAVCComVariant@ATL@@H@Z:PANYARGS
?ScEmitOrPostpone@CEventBuffer@@QEAA?AVSC@mmcerror@@PEAUIDispatch@@JPEAVCComVariant@ATL@@H@Z TEXTEQU <__imp_?ScEmitOrPostpone@CEventBuffer@@QEAA?AVSC@mmcerror@@PEAUIDispatch@@JPEAVCComVariant@ATL@@H@Z>
extern __imp_?ScFlushPostponed@CEventBuffer@@AEAA?AVSC@mmcerror@@XZ:PANYARGS
?ScFlushPostponed@CEventBuffer@@AEAA?AVSC@mmcerror@@XZ TEXTEQU <__imp_?ScFlushPostponed@CEventBuffer@@AEAA?AVSC@mmcerror@@XZ>
extern __imp_?ScFromMMC@@YA?AVSC@mmcerror@@J@Z:PANYARGS
?ScFromMMC@@YA?AVSC@mmcerror@@J@Z TEXTEQU <__imp_?ScFromMMC@@YA?AVSC@mmcerror@@J@Z>
extern __imp_?ScGetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@AEAPEAVCConsoleEventDispatcher@@@Z:PANYARGS
?ScGetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@AEAPEAVCConsoleEventDispatcher@@@Z TEXTEQU <__imp_?ScGetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@AEAPEAVCConsoleEventDispatcher@@@Z>
extern __imp_?ScSetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@PEAVCConsoleEventDispatcher@@@Z:PANYARGS
?ScSetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@PEAVCConsoleEventDispatcher@@@Z TEXTEQU <__imp_?ScSetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@PEAVCConsoleEventDispatcher@@@Z>
extern __imp_?SetFunctionName@SC@mmcerror@@QEAAXPEBG@Z:PANYARGS
?SetFunctionName@SC@mmcerror@@QEAAXPEBG@Z TEXTEQU <__imp_?SetFunctionName@SC@mmcerror@@QEAAXPEBG@Z>
extern __imp_?SetHWnd@SC@mmcerror@@SAXPEAUHWND__@@@Z:PANYARGS
?SetHWnd@SC@mmcerror@@SAXPEAUHWND__@@@Z TEXTEQU <__imp_?SetHWnd@SC@mmcerror@@SAXPEAUHWND__@@@Z>
extern __imp_?SetHinst@SC@mmcerror@@SAXPEAUHINSTANCE__@@@Z:PANYARGS
?SetHinst@SC@mmcerror@@SAXPEAUHINSTANCE__@@@Z TEXTEQU <__imp_?SetHinst@SC@mmcerror@@SAXPEAUHINSTANCE__@@@Z>
extern __imp_?SetMainThreadID@SC@mmcerror@@SAXK@Z:PANYARGS
?SetMainThreadID@SC@mmcerror@@SAXK@Z TEXTEQU <__imp_?SetMainThreadID@SC@mmcerror@@SAXK@Z>
extern __imp_?SetModalHWND@SC@mmcerror@@SAPEAUHWND__@@PEAU3@@Z:PANYARGS
?SetModalHWND@SC@mmcerror@@SAPEAUHWND__@@PEAU3@@Z TEXTEQU <__imp_?SetModalHWND@SC@mmcerror@@SAPEAUHWND__@@PEAU3@@Z>
extern __imp_?SetSnapinName@SC@mmcerror@@QEAAXPEBG@Z:PANYARGS
?SetSnapinName@SC@mmcerror@@QEAAXPEBG@Z TEXTEQU <__imp_?SetSnapinName@SC@mmcerror@@QEAAXPEBG@Z>
extern __imp_?Throw@SC@mmcerror@@QEAAXJ@Z:PANYARGS
?Throw@SC@mmcerror@@QEAAXJ@Z TEXTEQU <__imp_?Throw@SC@mmcerror@@QEAAXJ@Z>
extern __imp_?Throw@SC@mmcerror@@QEAAXXZ:PANYARGS
?Throw@SC@mmcerror@@QEAAXXZ TEXTEQU <__imp_?Throw@SC@mmcerror@@QEAAXXZ>
extern __imp_?ToHr@SC@mmcerror@@QEBAJXZ:PANYARGS
?ToHr@SC@mmcerror@@QEBAJXZ TEXTEQU <__imp_?ToHr@SC@mmcerror@@QEBAJXZ>
extern __imp_?TraceAndClear@SC@mmcerror@@QEAAXXZ:PANYARGS
?TraceAndClear@SC@mmcerror@@QEAAXXZ TEXTEQU <__imp_?TraceAndClear@SC@mmcerror@@QEAAXXZ>
extern __imp_?TraceError@@YAXPEBGAEBVSC@mmcerror@@@Z:PANYARGS
?TraceError@@YAXPEBGAEBVSC@mmcerror@@@Z TEXTEQU <__imp_?TraceError@@YAXPEBGAEBVSC@mmcerror@@@Z>
extern __imp_?TraceSnapinError@@YAXPEBGAEBVSC@mmcerror@@@Z:PANYARGS
?TraceSnapinError@@YAXPEBGAEBVSC@mmcerror@@@Z TEXTEQU <__imp_?TraceSnapinError@@YAXPEBGAEBVSC@mmcerror@@@Z>
extern __imp_?Trace_@SC@mmcerror@@QEBAXXZ:PANYARGS
?Trace_@SC@mmcerror@@QEBAXXZ TEXTEQU <__imp_?Trace_@SC@mmcerror@@QEBAXXZ>
extern __imp_?Unlock@CEventBuffer@@QEAAXXZ:PANYARGS
?Unlock@CEventBuffer@@QEAAXXZ TEXTEQU <__imp_?Unlock@CEventBuffer@@QEAAXXZ>
extern __imp_?UnregisterAllSnapinInstanceThreads@BookKeeping@@SAJH@Z:PANYARGS
?UnregisterAllSnapinInstanceThreads@BookKeeping@@SAJH@Z TEXTEQU <__imp_?UnregisterAllSnapinInstanceThreads@BookKeeping@@SAJH@Z>
extern __imp_?UnregisterThread@BookKeeping@@SAJHK@Z:PANYARGS
?UnregisterThread@BookKeeping@@SAJHK@Z TEXTEQU <__imp_?UnregisterThread@BookKeeping@@SAJHK@Z>
extern __imp_?WrongThreadCall@BookKeeping@@SAXHPEBG0@Z:PANYARGS
?WrongThreadCall@BookKeeping@@SAXHPEBG0@Z TEXTEQU <__imp_?WrongThreadCall@BookKeeping@@SAXHPEBG0@Z>
extern __imp_?s_CallDepth@SC@mmcerror@@0IA:PANYARGS
?s_CallDepth@SC@mmcerror@@0I  TEXTEQU <__imp_?s_CallDepth@SC@mmcerror@@0IA>
extern __imp_?s_dwMainThreadID@SC@mmcerror@@0KA:PANYARGS
?s_dwMainThreadID@SC@mmcerror@@0K  TEXTEQU <__imp_?s_dwMainThreadID@SC@mmcerror@@0KA>
extern __imp_?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@EA:PANYARGS
?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@E  TEXTEQU <__imp_?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@EA>
extern __imp_?s_hWnd@SC@mmcerror@@0PEAUHWND__@@EA:PANYARGS
?s_hWnd@SC@mmcerror@@0PEAUHWND__@@E  TEXTEQU <__imp_?s_hWnd@SC@mmcerror@@0PEAUHWND__@@EA>
extern __imp_?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@EA:PANYARGS
?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@E  TEXTEQU <__imp_?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@EA>
extern __imp_?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@EA:PANYARGS
?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@E  TEXTEQU <__imp_?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@EA>
extern __imp_GetAllocCounters:PANYARGS
GetAllocCounters TEXTEQU <__imp_GetAllocCounters>
extern __imp_ReportFxSnapinException:PANYARGS
ReportFxSnapinException TEXTEQU <__imp_ReportFxSnapinException>
