extern __imp_CreateExecutivePlatform:PANYARGS
CreateExecutivePlatform TEXTEQU <__imp_CreateExecutivePlatform>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetAllocCounters:PANYARGS
GetAllocCounters TEXTEQU <__imp_GetAllocCounters>
