extern __imp_?DisplayAVIBox@@YA_JPEAUHWND__@@PEBG1PEAPEAU1@@Z:PANYARGS
?DisplayAVIBox@@YA_JPEAUHWND__@@PEBG1PEAPEAU1@@Z TEXTEQU <__imp_?DisplayAVIBox@@YA_JPEAUHWND__@@PEBG1PEAPEAU1@@Z>
extern __imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEAUHINSTANCE__@@IIW4ERROR_SRC@@JI@Z:PANYARGS
?DisplayUserMessage@@YAHPEAUHWND__@@PEAUHINSTANCE__@@IIW4ERROR_SRC@@JI@Z TEXTEQU <__imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEAUHINSTANCE__@@IIW4ERROR_SRC@@JI@Z>
extern __imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEBG1W4ERROR_SRC@@JI@Z:PANYARGS
?DisplayUserMessage@@YAHPEAUHWND__@@PEBG1W4ERROR_SRC@@JI@Z TEXTEQU <__imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEBG1W4ERROR_SRC@@JI@Z>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_ErrorStringEx:PANYARGS
ErrorStringEx TEXTEQU <__imp_ErrorStringEx>
