extern __imp_??0CDirectDrawSurface@IHammer@@QEAA@PEAUHPALETTE__@@KPEBUtagSIZE@@PEAJ@Z:PANYARGS
??0CDirectDrawSurface@IHammer@@QEAA@PEAUHPALETTE__@@KPEBUtagSIZE@@PEAJ@Z TEXTEQU <__imp_??0CDirectDrawSurface@IHammer@@QEAA@PEAUHPALETTE__@@KPEBUtagSIZE@@PEAJ@Z>
extern __imp_??0CHalftone@@QEAA@PEAUHPALETTE__@@@Z:PANYARGS
??0CHalftone@@QEAA@PEAUHPALETTE__@@@Z TEXTEQU <__imp_??0CHalftone@@QEAA@PEAUHPALETTE__@@@Z>
extern __imp_??0CHalftonePalette@@QEAA@PEAUHPALETTE__@@@Z:PANYARGS
??0CHalftonePalette@@QEAA@PEAUHPALETTE__@@@Z TEXTEQU <__imp_??0CHalftonePalette@@QEAA@PEAUHPALETTE__@@@Z>
extern __imp_??0CHalftonePalette@@QEAA@XZ:PANYARGS
??0CHalftonePalette@@QEAA@XZ TEXTEQU <__imp_??0CHalftonePalette@@QEAA@XZ>
extern __imp_??0CMemManager@@QEAA@XZ:PANYARGS
??0CMemManager@@QEAA@XZ TEXTEQU <__imp_??0CMemManager@@QEAA@XZ>
extern __imp_??0CMemUser@@QEAA@XZ:PANYARGS
??0CMemUser@@QEAA@XZ TEXTEQU <__imp_??0CMemUser@@QEAA@XZ>
extern __imp_??0CTStr@@QEAA@AEAV0@@Z:PANYARGS
??0CTStr@@QEAA@AEAV0@@Z TEXTEQU <__imp_??0CTStr@@QEAA@AEAV0@@Z>
extern __imp_??0CTStr@@QEAA@H@Z:PANYARGS
??0CTStr@@QEAA@H@Z TEXTEQU <__imp_??0CTStr@@QEAA@H@Z>
extern __imp_??0CTStr@@QEAA@PEAD@Z:PANYARGS
??0CTStr@@QEAA@PEAD@Z TEXTEQU <__imp_??0CTStr@@QEAA@PEAD@Z>
extern __imp_??0CTStr@@QEAA@PEAG@Z:PANYARGS
??0CTStr@@QEAA@PEAG@Z TEXTEQU <__imp_??0CTStr@@QEAA@PEAG@Z>
extern __imp_??0CURLArchive@@QEAA@PEAUIUnknown@@@Z:PANYARGS
??0CURLArchive@@QEAA@PEAUIUnknown@@@Z TEXTEQU <__imp_??0CURLArchive@@QEAA@PEAUIUnknown@@@Z>
extern __imp_??0OTrig@@QEAA@XZ:PANYARGS
??0OTrig@@QEAA@XZ TEXTEQU <__imp_??0OTrig@@QEAA@XZ>
extern __imp_??1CMemManager@@UEAA@XZ:PANYARGS
??1CMemManager@@UEAA@XZ TEXTEQU <__imp_??1CMemManager@@UEAA@XZ>
extern __imp_??1CMemUser@@UEAA@XZ:PANYARGS
??1CMemUser@@UEAA@XZ TEXTEQU <__imp_??1CMemUser@@UEAA@XZ>
extern __imp_??1CTStr@@QEAA@XZ:PANYARGS
??1CTStr@@QEAA@XZ TEXTEQU <__imp_??1CTStr@@QEAA@XZ>
extern __imp_??1CURLArchive@@UEAA@XZ:PANYARGS
??1CURLArchive@@UEAA@XZ TEXTEQU <__imp_??1CURLArchive@@UEAA@XZ>
extern __imp_??_FCTStr@@QEAAXXZ:PANYARGS
??_FCTStr@@QEAAXXZ TEXTEQU <__imp_??_FCTStr@@QEAAXXZ>
extern __imp_??_FCURLArchive@@QEAAXXZ:PANYARGS
??_FCURLArchive@@QEAAXXZ TEXTEQU <__imp_??_FCURLArchive@@QEAAXXZ>
extern __imp_?AllocBuffer@CMemManager@@QEAAPEAXKG@Z:PANYARGS
?AllocBuffer@CMemManager@@QEAAPEAXKG@Z TEXTEQU <__imp_?AllocBuffer@CMemManager@@QEAAPEAXKG@Z>
extern __imp_?AllocBuffer@CMemUser@@QEAAPEAUMEMBLOCK_tag@@KG@Z:PANYARGS
?AllocBuffer@CMemUser@@QEAAPEAUMEMBLOCK_tag@@KG@Z TEXTEQU <__imp_?AllocBuffer@CMemUser@@QEAAPEAUMEMBLOCK_tag@@KG@Z>
extern __imp_?AllocBuffer@CTStr@@QEAAHHH@Z:PANYARGS
?AllocBuffer@CTStr@@QEAAHHH@Z TEXTEQU <__imp_?AllocBuffer@CTStr@@QEAAHHH@Z>
extern __imp_?AllocBufferGlb@CMemManager@@SAPEAXKG@Z:PANYARGS
?AllocBufferGlb@CMemManager@@SAPEAXKG@Z TEXTEQU <__imp_?AllocBufferGlb@CMemManager@@SAPEAXKG@Z>
extern __imp_?Atoi@CStringWrapper@@SAHPEBD@Z:PANYARGS
?Atoi@CStringWrapper@@SAHPEBD@Z TEXTEQU <__imp_?Atoi@CStringWrapper@@SAHPEBD@Z>
extern __imp_?Atol@CStringWrapper@@SAJPEBD@Z:PANYARGS
?Atol@CStringWrapper@@SAJPEBD@Z TEXTEQU <__imp_?Atol@CStringWrapper@@SAJPEBD@Z>
extern __imp_?BitCountFromDDPIXELFORMAT@@YAJAEBU_DDPIXELFORMAT@@@Z:PANYARGS
?BitCountFromDDPIXELFORMAT@@YAJAEBU_DDPIXELFORMAT@@@Z TEXTEQU <__imp_?BitCountFromDDPIXELFORMAT@@YAJAEBU_DDPIXELFORMAT@@@Z>
extern __imp_?Close@CURLArchive@@UEAAJXZ:PANYARGS
?Close@CURLArchive@@UEAAJXZ TEXTEQU <__imp_?Close@CURLArchive@@UEAAJXZ>
extern __imp_?CopyFrom@CNonCollapsingDrg@@UEAAHPEAVCDrg@@@Z:PANYARGS
?CopyFrom@CNonCollapsingDrg@@UEAAHPEAVCDrg@@@Z TEXTEQU <__imp_?CopyFrom@CNonCollapsingDrg@@UEAAHPEAVCDrg@@@Z>
extern __imp_?CopyLocal@CURLArchive@@UEAAJPEADH@Z:PANYARGS
?CopyLocal@CURLArchive@@UEAAJPEADH@Z TEXTEQU <__imp_?CopyLocal@CURLArchive@@UEAAJPEADH@Z>
extern __imp_?CopyLocal@CURLArchive@@UEAAJPEAGH@Z:PANYARGS
?CopyLocal@CURLArchive@@UEAAJPEAGH@Z TEXTEQU <__imp_?CopyLocal@CURLArchive@@UEAAJPEAGH@Z>
extern __imp_?Cos@OTrig@@QEAAMJ@Z:PANYARGS
?Cos@OTrig@@QEAAMJ@Z TEXTEQU <__imp_?Cos@OTrig@@QEAAMJ@Z>
extern __imp_?Cos@OTrig@@QEAAMM@Z:PANYARGS
?Cos@OTrig@@QEAAMM@Z TEXTEQU <__imp_?Cos@OTrig@@QEAAMM@Z>
extern __imp_?CosDeg@CMathWrapper@@SAMJ@Z:PANYARGS
?CosDeg@CMathWrapper@@SAMJ@Z TEXTEQU <__imp_?CosDeg@CMathWrapper@@SAMJ@Z>
extern __imp_?CosDeg@CMathWrapper@@SAMM@Z:PANYARGS
?CosDeg@CMathWrapper@@SAMM@Z TEXTEQU <__imp_?CosDeg@CMathWrapper@@SAMM@Z>
extern __imp_?CosDegWrap@CMathWrapper@@SAMJ@Z:PANYARGS
?CosDegWrap@CMathWrapper@@SAMJ@Z TEXTEQU <__imp_?CosDegWrap@CMathWrapper@@SAMJ@Z>
extern __imp_?CosDegWrap@CMathWrapper@@SAMM@Z:PANYARGS
?CosDegWrap@CMathWrapper@@SAMM@Z TEXTEQU <__imp_?CosDegWrap@CMathWrapper@@SAMM@Z>
extern __imp_?CosRad@CMathWrapper@@SANN@Z:PANYARGS
?CosRad@CMathWrapper@@SANN@Z TEXTEQU <__imp_?CosRad@CMathWrapper@@SANN@Z>
extern __imp_?CosWrap@OTrig@@QEAAMJ@Z:PANYARGS
?CosWrap@OTrig@@QEAAMJ@Z TEXTEQU <__imp_?CosWrap@OTrig@@QEAAMJ@Z>
extern __imp_?CosWrap@OTrig@@QEAAMM@Z:PANYARGS
?CosWrap@OTrig@@QEAAMM@Z TEXTEQU <__imp_?CosWrap@OTrig@@QEAAMM@Z>
extern __imp_?Create@CURLArchive@@UEAAJPEBD@Z:PANYARGS
?Create@CURLArchive@@UEAAJPEBD@Z TEXTEQU <__imp_?Create@CURLArchive@@UEAAJPEBD@Z>
extern __imp_?Create@CURLArchive@@UEAAJPEBG@Z:PANYARGS
?Create@CURLArchive@@UEAAJPEBG@Z TEXTEQU <__imp_?Create@CURLArchive@@UEAAJPEBG@Z>
extern __imp_?CreateIDispatchCollection@@YAHPEAPEAUIUnknown@@@Z:PANYARGS
?CreateIDispatchCollection@@YAHPEAPEAUIUnknown@@@Z TEXTEQU <__imp_?CreateIDispatchCollection@@YAHPEAPEAUIUnknown@@@Z>
extern __imp_?DumpAllocations@CMemManager@@QEAAXPEAD@Z:PANYARGS
?DumpAllocations@CMemManager@@QEAAXPEAD@Z TEXTEQU <__imp_?DumpAllocations@CMemManager@@QEAAXPEAD@Z>
extern __imp_?DumpAllocationsGlb@CMemManager@@SAXPEAD@Z:PANYARGS
?DumpAllocationsGlb@CMemManager@@SAXPEAD@Z TEXTEQU <__imp_?DumpAllocationsGlb@CMemManager@@SAXPEAD@Z>
extern __imp_?DumpHeapHeader@CMemManager@@AEAAXPEAUHEAPHEADER_tag@@PEAU_iobuf@@@Z:PANYARGS
?DumpHeapHeader@CMemManager@@AEAAXPEAUHEAPHEADER_tag@@PEAU_iobuf@@@Z TEXTEQU <__imp_?DumpHeapHeader@CMemManager@@AEAAXPEAUHEAPHEADER_tag@@PEAU_iobuf@@@Z>
extern __imp_?DumpMemBlock@CMemManager@@AEAAXPEAUMEMBLOCK_tag@@PEAU_iobuf@@@Z:PANYARGS
?DumpMemBlock@CMemManager@@AEAAXPEAUMEMBLOCK_tag@@PEAU_iobuf@@@Z TEXTEQU <__imp_?DumpMemBlock@CMemManager@@AEAAXPEAUMEMBLOCK_tag@@PEAU_iobuf@@@Z>
extern __imp_?DumpMemUserInfo@CMemManager@@AEAAXPEAUMEMUSERINFO_tag@@PEAU_iobuf@@@Z:PANYARGS
?DumpMemUserInfo@CMemManager@@AEAAXPEAUMEMUSERINFO_tag@@PEAU_iobuf@@@Z TEXTEQU <__imp_?DumpMemUserInfo@CMemManager@@AEAAXPEAUMEMUSERINFO_tag@@PEAU_iobuf@@@Z>
extern __imp_?ExternalDumpAllocations@@YAXPEAD@Z:PANYARGS
?ExternalDumpAllocations@@YAXPEAD@Z TEXTEQU <__imp_?ExternalDumpAllocations@@YAXPEAD@Z>
extern __imp_?FreeBuffer@CMemManager@@QEAAXPEAX@Z:PANYARGS
?FreeBuffer@CMemManager@@QEAAXPEAX@Z TEXTEQU <__imp_?FreeBuffer@CMemManager@@QEAAXPEAX@Z>
extern __imp_?FreeBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z:PANYARGS
?FreeBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z TEXTEQU <__imp_?FreeBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z>
extern __imp_?FreeBuffer@CTStr@@QEAAXXZ:PANYARGS
?FreeBuffer@CTStr@@QEAAXXZ TEXTEQU <__imp_?FreeBuffer@CTStr@@QEAAXXZ>
extern __imp_?FreeBufferGlb@CMemManager@@SAXPEAX@Z:PANYARGS
?FreeBufferGlb@CMemManager@@SAXPEAX@Z TEXTEQU <__imp_?FreeBufferGlb@CMemManager@@SAXPEAX@Z>
extern __imp_?FreeBufferMemBlock@CMemManager@@QEAAXPEAUMEMBLOCK_tag@@@Z:PANYARGS
?FreeBufferMemBlock@CMemManager@@QEAAXPEAUMEMBLOCK_tag@@@Z TEXTEQU <__imp_?FreeBufferMemBlock@CMemManager@@QEAAXPEAUMEMBLOCK_tag@@@Z>
extern __imp_?Gcvt@CStringWrapper@@SAPEADNHPEAD@Z:PANYARGS
?Gcvt@CStringWrapper@@SAPEADNHPEAD@Z TEXTEQU <__imp_?Gcvt@CStringWrapper@@SAPEADNHPEAD@Z>
extern __imp_?GetAt@CNonCollapsingDrg@@UEAAPEAXJ@Z:PANYARGS
?GetAt@CNonCollapsingDrg@@UEAAPEAXJ@Z TEXTEQU <__imp_?GetAt@CNonCollapsingDrg@@UEAAPEAXJ@Z>
extern __imp_?GetFileSize@CURLArchive@@UEAAJAEAJ@Z:PANYARGS
?GetFileSize@CURLArchive@@UEAAJAEAJ@Z TEXTEQU <__imp_?GetFileSize@CURLArchive@@UEAAJAEAJ@Z>
extern __imp_?GetFirst@CNonCollapsingDrg@@UEAAPEAXXZ:PANYARGS
?GetFirst@CNonCollapsingDrg@@UEAAPEAXXZ TEXTEQU <__imp_?GetFirst@CNonCollapsingDrg@@UEAAPEAXXZ>
extern __imp_?GetNext@CNonCollapsingDrg@@UEAAPEAXXZ:PANYARGS
?GetNext@CNonCollapsingDrg@@UEAAPEAXXZ TEXTEQU <__imp_?GetNext@CNonCollapsingDrg@@UEAAPEAXXZ>
extern __imp_?GetSigBitsFrom16BPP@@YAKPEAUHDC__@@@Z:PANYARGS
?GetSigBitsFrom16BPP@@YAKPEAUHDC__@@@Z TEXTEQU <__imp_?GetSigBitsFrom16BPP@@YAKPEAUHDC__@@@Z>
extern __imp_?GetStreamInterface@CURLArchive@@UEBAPEAUIStream@@XZ:PANYARGS
?GetStreamInterface@CURLArchive@@UEBAPEAUIStream@@XZ TEXTEQU <__imp_?GetStreamInterface@CURLArchive@@UEBAPEAUIStream@@XZ>
extern __imp_?Insert@CDrg@@UEAAHPEAXJ@Z:PANYARGS
?Insert@CDrg@@UEAAHPEAXJ@Z TEXTEQU <__imp_?Insert@CDrg@@UEAAHPEAXJ@Z>
extern __imp_?IsMMXCpu@@YAHXZ:PANYARGS
?IsMMXCpu@@YAHXZ TEXTEQU <__imp_?IsMMXCpu@@YAHXZ>
extern __imp_?Iswspace@CStringWrapper@@SAHG@Z:PANYARGS
?Iswspace@CStringWrapper@@SAHG@Z TEXTEQU <__imp_?Iswspace@CStringWrapper@@SAHG@Z>
extern __imp_?Itoa@CStringWrapper@@SAPEADHPEADH@Z:PANYARGS
?Itoa@CStringWrapper@@SAPEADHPEADH@Z TEXTEQU <__imp_?Itoa@CStringWrapper@@SAPEADHPEADH@Z>
extern __imp_?Len@CTStr@@QEAAHXZ:PANYARGS
?Len@CTStr@@QEAAHXZ TEXTEQU <__imp_?Len@CTStr@@QEAAHXZ>
extern __imp_?LoadStringW@CStringWrapper@@SAHPEAUHINSTANCE__@@IPEAGH@Z:PANYARGS
?LoadStringW@CStringWrapper@@SAHPEAUHINSTANCE__@@IPEAGH@Z TEXTEQU <__imp_?LoadStringW@CStringWrapper@@SAHPEAUHINSTANCE__@@IPEAGH@Z>
extern __imp_?LockBuffer@CMemUser@@QEAAPEAXPEAUMEMBLOCK_tag@@@Z:PANYARGS
?LockBuffer@CMemUser@@QEAAPEAXPEAUMEMBLOCK_tag@@@Z TEXTEQU <__imp_?LockBuffer@CMemUser@@QEAAPEAXPEAUMEMBLOCK_tag@@@Z>
extern __imp_?Ltoa@CStringWrapper@@SAPEADJPEADH@Z:PANYARGS
?Ltoa@CStringWrapper@@SAPEADJPEADH@Z TEXTEQU <__imp_?Ltoa@CStringWrapper@@SAPEADJPEADH@Z>
extern __imp_?Mbstowcs@CStringWrapper@@SA_KPEAGPEBD_K@Z:PANYARGS
?Mbstowcs@CStringWrapper@@SA_KPEAGPEBD_K@Z TEXTEQU <__imp_?Mbstowcs@CStringWrapper@@SA_KPEAGPEBD_K@Z>
extern __imp_?Memcmp@CStringWrapper@@SAHPEBX0_K@Z:PANYARGS
?Memcmp@CStringWrapper@@SAHPEBX0_K@Z TEXTEQU <__imp_?Memcmp@CStringWrapper@@SAHPEBX0_K@Z>
extern __imp_?Memcpy@CStringWrapper@@SAPEAXPEAXPEBX_K@Z:PANYARGS
?Memcpy@CStringWrapper@@SAPEAXPEAXPEBX_K@Z TEXTEQU <__imp_?Memcpy@CStringWrapper@@SAPEAXPEAXPEBX_K@Z>
extern __imp_?Memset@CStringWrapper@@SAPEAXPEAXH_K@Z:PANYARGS
?Memset@CStringWrapper@@SAPEAXPEAXH_K@Z TEXTEQU <__imp_?Memset@CStringWrapper@@SAPEAXPEAXH_K@Z>
extern __imp_?NotifyMemUser@CMemUser@@UEAAHPEAUMEMNOTIFY_tag@@@Z:PANYARGS
?NotifyMemUser@CMemUser@@UEAAHPEAUMEMNOTIFY_tag@@@Z TEXTEQU <__imp_?NotifyMemUser@CMemUser@@UEAAHPEAUMEMNOTIFY_tag@@@Z>
extern __imp_?OverheadOfSavePtrDrg@@YAKXZ:PANYARGS
?OverheadOfSavePtrDrg@@YAKXZ TEXTEQU <__imp_?OverheadOfSavePtrDrg@@YAKXZ>
extern __imp_?Pow@CMathWrapper@@SAMNN@Z:PANYARGS
?Pow@CMathWrapper@@SAMNN@Z TEXTEQU <__imp_?Pow@CMathWrapper@@SAMNN@Z>
extern __imp_?ReAllocBuffer@CMemManager@@QEAAPEAXPEAXKG@Z:PANYARGS
?ReAllocBuffer@CMemManager@@QEAAPEAXPEAXKG@Z TEXTEQU <__imp_?ReAllocBuffer@CMemManager@@QEAAPEAXPEAXKG@Z>
extern __imp_?ReAllocBufferGlb@CMemManager@@SAPEAXPEAXKG@Z:PANYARGS
?ReAllocBufferGlb@CMemManager@@SAPEAXPEAXKG@Z TEXTEQU <__imp_?ReAllocBufferGlb@CMemManager@@SAPEAXPEAXKG@Z>
extern __imp_?Read@CURLArchive@@UEAAKPEAEK@Z:PANYARGS
?Read@CURLArchive@@UEAAKPEAEK@Z TEXTEQU <__imp_?Read@CURLArchive@@UEAAKPEAEK@Z>
extern __imp_?ReadBstrFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAPEAG@Z:PANYARGS
?ReadBstrFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAPEAG@Z TEXTEQU <__imp_?ReadBstrFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAPEAG@Z>
extern __imp_?ReadLine@CURLArchive@@UEAAKPEADK@Z:PANYARGS
?ReadLine@CURLArchive@@UEAAKPEADK@Z TEXTEQU <__imp_?ReadLine@CURLArchive@@UEAAKPEADK@Z>
extern __imp_?ReadLine@CURLArchive@@UEAAKPEAGK@Z:PANYARGS
?ReadLine@CURLArchive@@UEAAKPEAGK@Z TEXTEQU <__imp_?ReadLine@CURLArchive@@UEAAKPEAGK@Z>
extern __imp_?ReadLongFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAJ@Z:PANYARGS
?ReadLongFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAJ@Z TEXTEQU <__imp_?ReadLongFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAJ@Z>
extern __imp_?RegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z:PANYARGS
?RegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z TEXTEQU <__imp_?RegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z>
extern __imp_?RegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z:PANYARGS
?RegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z TEXTEQU <__imp_?RegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z>
extern __imp_?Remove@CDrg@@UEAAHPEAXJ@Z:PANYARGS
?Remove@CDrg@@UEAAHPEAXJ@Z TEXTEQU <__imp_?Remove@CDrg@@UEAAHPEAXJ@Z>
extern __imp_?Remove@CNonCollapsingDrg@@UEAAHPEAXJ@Z:PANYARGS
?Remove@CNonCollapsingDrg@@UEAAHPEAXJ@Z TEXTEQU <__imp_?Remove@CNonCollapsingDrg@@UEAAHPEAXJ@Z>
extern __imp_?ResetLength@CTStr@@QEAAXXZ:PANYARGS
?ResetLength@CTStr@@QEAAXXZ TEXTEQU <__imp_?ResetLength@CTStr@@QEAAXXZ>
extern __imp_?RetailEcho@@YAXPEADZZ:PANYARGS
?RetailEcho@@YAXPEADZZ TEXTEQU <__imp_?RetailEcho@@YAXPEADZZ>
extern __imp_?Seek@CURLArchive@@UEAAJJW4origin@1@@Z:PANYARGS
?Seek@CURLArchive@@UEAAJJW4origin@1@@Z TEXTEQU <__imp_?Seek@CURLArchive@@UEAAJJW4origin@1@@Z>
extern __imp_?SetArray@CNonCollapsingDrg@@UEAAXPEAEJI@Z:PANYARGS
?SetArray@CNonCollapsingDrg@@UEAAXPEAEJI@Z TEXTEQU <__imp_?SetArray@CNonCollapsingDrg@@UEAAXPEAEJI@Z>
extern __imp_?SetAt@CNonCollapsingDrg@@UEAAHPEAXJ@Z:PANYARGS
?SetAt@CNonCollapsingDrg@@UEAAHPEAXJ@Z TEXTEQU <__imp_?SetAt@CNonCollapsingDrg@@UEAAHPEAXJ@Z>
extern __imp_?SetNonDefaultSizes@CDrg@@UEAAXII@Z:PANYARGS
?SetNonDefaultSizes@CDrg@@UEAAXII@Z TEXTEQU <__imp_?SetNonDefaultSizes@CDrg@@UEAAXII@Z>
extern __imp_?SetString@CTStr@@QEAAHPEAD@Z:PANYARGS
?SetString@CTStr@@QEAAHPEAD@Z TEXTEQU <__imp_?SetString@CTStr@@QEAAHPEAD@Z>
extern __imp_?SetString@CTStr@@QEAAHPEAG@Z:PANYARGS
?SetString@CTStr@@QEAAHPEAG@Z TEXTEQU <__imp_?SetString@CTStr@@QEAAHPEAG@Z>
extern __imp_?SetStringPointer@CTStr@@QEAAHPEADH@Z:PANYARGS
?SetStringPointer@CTStr@@QEAAHPEADH@Z TEXTEQU <__imp_?SetStringPointer@CTStr@@QEAAHPEADH@Z>
extern __imp_?Sin@OTrig@@QEAAMJ@Z:PANYARGS
?Sin@OTrig@@QEAAMJ@Z TEXTEQU <__imp_?Sin@OTrig@@QEAAMJ@Z>
extern __imp_?Sin@OTrig@@QEAAMM@Z:PANYARGS
?Sin@OTrig@@QEAAMM@Z TEXTEQU <__imp_?Sin@OTrig@@QEAAMM@Z>
extern __imp_?SinDeg@CMathWrapper@@SAMJ@Z:PANYARGS
?SinDeg@CMathWrapper@@SAMJ@Z TEXTEQU <__imp_?SinDeg@CMathWrapper@@SAMJ@Z>
extern __imp_?SinDeg@CMathWrapper@@SAMM@Z:PANYARGS
?SinDeg@CMathWrapper@@SAMM@Z TEXTEQU <__imp_?SinDeg@CMathWrapper@@SAMM@Z>
extern __imp_?SinDegWrap@CMathWrapper@@SAMJ@Z:PANYARGS
?SinDegWrap@CMathWrapper@@SAMJ@Z TEXTEQU <__imp_?SinDegWrap@CMathWrapper@@SAMJ@Z>
extern __imp_?SinDegWrap@CMathWrapper@@SAMM@Z:PANYARGS
?SinDegWrap@CMathWrapper@@SAMM@Z TEXTEQU <__imp_?SinDegWrap@CMathWrapper@@SAMM@Z>
extern __imp_?SinRad@CMathWrapper@@SANN@Z:PANYARGS
?SinRad@CMathWrapper@@SANN@Z TEXTEQU <__imp_?SinRad@CMathWrapper@@SANN@Z>
extern __imp_?SinWrap@OTrig@@QEAAMJ@Z:PANYARGS
?SinWrap@OTrig@@QEAAMJ@Z TEXTEQU <__imp_?SinWrap@OTrig@@QEAAMJ@Z>
extern __imp_?SinWrap@OTrig@@QEAAMM@Z:PANYARGS
?SinWrap@OTrig@@QEAAMM@Z TEXTEQU <__imp_?SinWrap@OTrig@@QEAAMM@Z>
extern __imp_?SizeBuffer@CMemManager@@QEAAKPEAX@Z:PANYARGS
?SizeBuffer@CMemManager@@QEAAKPEAX@Z TEXTEQU <__imp_?SizeBuffer@CMemManager@@QEAAKPEAX@Z>
extern __imp_?SizeBufferGlb@CMemManager@@SAKPEAX@Z:PANYARGS
?SizeBufferGlb@CMemManager@@SAKPEAX@Z TEXTEQU <__imp_?SizeBufferGlb@CMemManager@@SAKPEAX@Z>
extern __imp_?Sprintf@CStringWrapper@@SAHPEADPEBDZZ:PANYARGS
?Sprintf@CStringWrapper@@SAHPEADPEBDZZ TEXTEQU <__imp_?Sprintf@CStringWrapper@@SAHPEADPEBDZZ>
extern __imp_?Sqrt@CMathWrapper@@SAMM@Z:PANYARGS
?Sqrt@CMathWrapper@@SAMM@Z TEXTEQU <__imp_?Sqrt@CMathWrapper@@SAMM@Z>
extern __imp_?Sscanf1@CStringWrapper@@SAHPEBD0PEAX@Z:PANYARGS
?Sscanf1@CStringWrapper@@SAHPEBD0PEAX@Z TEXTEQU <__imp_?Sscanf1@CStringWrapper@@SAHPEBD0PEAX@Z>
extern __imp_?Sscanf2@CStringWrapper@@SAHPEBD0PEAX1@Z:PANYARGS
?Sscanf2@CStringWrapper@@SAHPEBD0PEAX1@Z TEXTEQU <__imp_?Sscanf2@CStringWrapper@@SAHPEBD0PEAX1@Z>
extern __imp_?Sscanf3@CStringWrapper@@SAHPEBD0PEAX11@Z:PANYARGS
?Sscanf3@CStringWrapper@@SAHPEBD0PEAX11@Z TEXTEQU <__imp_?Sscanf3@CStringWrapper@@SAHPEBD0PEAX11@Z>
extern __imp_?Strcat@CStringWrapper@@SAPEADPEADPEBD@Z:PANYARGS
?Strcat@CStringWrapper@@SAPEADPEADPEBD@Z TEXTEQU <__imp_?Strcat@CStringWrapper@@SAPEADPEADPEBD@Z>
extern __imp_?Strchr@CStringWrapper@@SAPEADPEBDD@Z:PANYARGS
?Strchr@CStringWrapper@@SAPEADPEBDD@Z TEXTEQU <__imp_?Strchr@CStringWrapper@@SAPEADPEBDD@Z>
extern __imp_?Strcmp@CStringWrapper@@SAHPEBD0@Z:PANYARGS
?Strcmp@CStringWrapper@@SAHPEBD0@Z TEXTEQU <__imp_?Strcmp@CStringWrapper@@SAHPEBD0@Z>
extern __imp_?Strcpy@CStringWrapper@@SAPEADPEADPEBD@Z:PANYARGS
?Strcpy@CStringWrapper@@SAPEADPEADPEBD@Z TEXTEQU <__imp_?Strcpy@CStringWrapper@@SAPEADPEADPEBD@Z>
extern __imp_?Stricmp@CStringWrapper@@SAHPEBD0@Z:PANYARGS
?Stricmp@CStringWrapper@@SAHPEBD0@Z TEXTEQU <__imp_?Stricmp@CStringWrapper@@SAHPEBD0@Z>
extern __imp_?Strinc@CStringWrapper@@SAPEADPEBD@Z:PANYARGS
?Strinc@CStringWrapper@@SAPEADPEBD@Z TEXTEQU <__imp_?Strinc@CStringWrapper@@SAPEADPEBD@Z>
extern __imp_?Strlen@CStringWrapper@@SAHPEBD@Z:PANYARGS
?Strlen@CStringWrapper@@SAHPEBD@Z TEXTEQU <__imp_?Strlen@CStringWrapper@@SAHPEBD@Z>
extern __imp_?Strncmp@CStringWrapper@@SAHPEBD0_K@Z:PANYARGS
?Strncmp@CStringWrapper@@SAHPEBD0_K@Z TEXTEQU <__imp_?Strncmp@CStringWrapper@@SAHPEBD0_K@Z>
extern __imp_?Strncpy@CStringWrapper@@SAPEADPEADPEBD_K@Z:PANYARGS
?Strncpy@CStringWrapper@@SAPEADPEADPEBD_K@Z TEXTEQU <__imp_?Strncpy@CStringWrapper@@SAPEADPEADPEBD_K@Z>
extern __imp_?Strnicmp@CStringWrapper@@SAHPEBD0_K@Z:PANYARGS
?Strnicmp@CStringWrapper@@SAHPEBD0_K@Z TEXTEQU <__imp_?Strnicmp@CStringWrapper@@SAHPEBD0_K@Z>
extern __imp_?Strrchr@CStringWrapper@@SAPEADPEBDD@Z:PANYARGS
?Strrchr@CStringWrapper@@SAPEADPEBDD@Z TEXTEQU <__imp_?Strrchr@CStringWrapper@@SAPEADPEBDD@Z>
extern __imp_?Strstr@CStringWrapper@@SAPEADPEBD0@Z:PANYARGS
?Strstr@CStringWrapper@@SAPEADPEBD0@Z TEXTEQU <__imp_?Strstr@CStringWrapper@@SAPEADPEBD0@Z>
extern __imp_?Strtok@CStringWrapper@@SAPEADPEADPEBD@Z:PANYARGS
?Strtok@CStringWrapper@@SAPEADPEADPEBD@Z TEXTEQU <__imp_?Strtok@CStringWrapper@@SAPEADPEADPEBD@Z>
extern __imp_?SysAllocString@CTStr@@QEAAPEAGXZ:PANYARGS
?SysAllocString@CTStr@@QEAAPEAGXZ TEXTEQU <__imp_?SysAllocString@CTStr@@QEAAPEAGXZ>
extern __imp_?UnLockBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z:PANYARGS
?UnLockBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z TEXTEQU <__imp_?UnLockBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z>
extern __imp_?UnRegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z:PANYARGS
?UnRegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z TEXTEQU <__imp_?UnRegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z>
extern __imp_?UnRegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z:PANYARGS
?UnRegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z TEXTEQU <__imp_?UnRegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z>
extern __imp_?WStrCmpin@CStringWrapper@@SAHPEBG0_K@Z:PANYARGS
?WStrCmpin@CStringWrapper@@SAHPEBG0_K@Z TEXTEQU <__imp_?WStrCmpin@CStringWrapper@@SAHPEBG0_K@Z>
extern __imp_?WStrcat@CStringWrapper@@SAPEAGPEAGPEBG@Z:PANYARGS
?WStrcat@CStringWrapper@@SAPEAGPEAGPEBG@Z TEXTEQU <__imp_?WStrcat@CStringWrapper@@SAPEAGPEAGPEBG@Z>
extern __imp_?WStrcpy@CStringWrapper@@SAPEAGPEAGPEBG@Z:PANYARGS
?WStrcpy@CStringWrapper@@SAPEAGPEAGPEBG@Z TEXTEQU <__imp_?WStrcpy@CStringWrapper@@SAPEAGPEAGPEBG@Z>
extern __imp_?WStrlen@CStringWrapper@@SAHPEBG@Z:PANYARGS
?WStrlen@CStringWrapper@@SAHPEBG@Z TEXTEQU <__imp_?WStrlen@CStringWrapper@@SAHPEBG@Z>
extern __imp_?WStrncpy@CStringWrapper@@SAPEAGPEAGPEBG_K@Z:PANYARGS
?WStrncpy@CStringWrapper@@SAPEAGPEAGPEBG_K@Z TEXTEQU <__imp_?WStrncpy@CStringWrapper@@SAPEAGPEAGPEBG_K@Z>
extern __imp_?Wcstombs@CStringWrapper@@SA_KPEADPEBG_K@Z:PANYARGS
?Wcstombs@CStringWrapper@@SA_KPEADPEBG_K@Z TEXTEQU <__imp_?Wcstombs@CStringWrapper@@SA_KPEADPEBG_K@Z>
extern __imp_?Write@CURLArchive@@UEAAKPEAEK@Z:PANYARGS
?Write@CURLArchive@@UEAAKPEAEK@Z TEXTEQU <__imp_?Write@CURLArchive@@UEAAKPEAEK@Z>
extern __imp_?WriteBstrToPropBag@@YAJPEAUIPropertyBag@@PEADPEAG@Z:PANYARGS
?WriteBstrToPropBag@@YAJPEAUIPropertyBag@@PEADPEAG@Z TEXTEQU <__imp_?WriteBstrToPropBag@@YAJPEAUIPropertyBag@@PEADPEAG@Z>
extern __imp_?WriteLongToPropBag@@YAJPEAUIPropertyBag@@PEADJ@Z:PANYARGS
?WriteLongToPropBag@@YAJPEAUIPropertyBag@@PEADJ@Z TEXTEQU <__imp_?WriteLongToPropBag@@YAJPEAUIPropertyBag@@PEADJ@Z>
extern __imp_?psz@CTStr@@QEAAPEADXZ:PANYARGS
?psz@CTStr@@QEAAPEADXZ TEXTEQU <__imp_?psz@CTStr@@QEAAPEADXZ>
extern __imp_?pszA@CTStr@@QEAAPEADXZ:PANYARGS
?pszA@CTStr@@QEAAPEADXZ TEXTEQU <__imp_?pszA@CTStr@@QEAAPEADXZ>
extern __imp_?pszW@CTStr@@QEAAPEAGXZ:PANYARGS
?pszW@CTStr@@QEAAPEAGXZ TEXTEQU <__imp_?pszW@CTStr@@QEAAPEAGXZ>
extern __imp__wcsicmp:PANYARGS
_wcsicmp TEXTEQU <__imp__wcsicmp>
extern __imp__wtoi:PANYARGS
_wtoi TEXTEQU <__imp__wtoi>
extern __imp_fmod:PANYARGS
fmod TEXTEQU <__imp_fmod>
extern __imp_memcmp:PANYARGS
memcmp TEXTEQU <__imp_memcmp>
extern __imp_memset:PANYARGS
memset TEXTEQU <__imp_memset>
extern __imp_setlocale:PANYARGS
setlocale TEXTEQU <__imp_setlocale>
extern __imp_strcpy:PANYARGS
strcpy TEXTEQU <__imp_strcpy>
extern __imp_strlen:PANYARGS
strlen TEXTEQU <__imp_strlen>
extern __imp_swprintf:PANYARGS
swprintf TEXTEQU <__imp_swprintf>
