extern __imp_WNetConnectionDialog2:PANYARGS
WNetConnectionDialog2 TEXTEQU <__imp_WNetConnectionDialog2>
extern __imp_WNetDisconnectDialog2:PANYARGS
WNetDisconnectDialog2 TEXTEQU <__imp_WNetDisconnectDialog2>
extern __imp_I_MprSaveConn:PANYARGS
I_MprSaveConn TEXTEQU <__imp_I_MprSaveConn>
extern __imp_MultinetGetConnectionPerformanceA:PANYARGS
MultinetGetConnectionPerformance  TEXTEQU <__imp_MultinetGetConnectionPerformanceA>
extern __imp_MultinetGetConnectionPerformanceW:PANYARGS
MultinetGetConnectionPerformanceW TEXTEQU <__imp_MultinetGetConnectionPerformanceW>
extern __imp_MultinetGetErrorTextA:PANYARGS
MultinetGetErrorText  TEXTEQU <__imp_MultinetGetErrorTextA>
extern __imp_MultinetGetErrorTextW:PANYARGS
MultinetGetErrorTextW TEXTEQU <__imp_MultinetGetErrorTextW>
extern __imp_RestoreConnectionA0:PANYARGS
RestoreConnectionA0 TEXTEQU <__imp_RestoreConnectionA0>
extern __imp_WNetAddConnection2A:PANYARGS
WNetAddConnection2  TEXTEQU <__imp_WNetAddConnection2A>
extern __imp_WNetAddConnection2W:PANYARGS
WNetAddConnection2W TEXTEQU <__imp_WNetAddConnection2W>
extern __imp_WNetAddConnection3A:PANYARGS
WNetAddConnection3  TEXTEQU <__imp_WNetAddConnection3A>
extern __imp_WNetAddConnection3W:PANYARGS
WNetAddConnection3W TEXTEQU <__imp_WNetAddConnection3W>
extern __imp_WNetAddConnectionA:PANYARGS
WNetAddConnection  TEXTEQU <__imp_WNetAddConnectionA>
extern __imp_WNetAddConnectionW:PANYARGS
WNetAddConnectionW TEXTEQU <__imp_WNetAddConnectionW>
extern __imp_WNetCancelConnection2A:PANYARGS
WNetCancelConnection2  TEXTEQU <__imp_WNetCancelConnection2A>
extern __imp_WNetCancelConnection2W:PANYARGS
WNetCancelConnection2W TEXTEQU <__imp_WNetCancelConnection2W>
extern __imp_WNetCancelConnectionA:PANYARGS
WNetCancelConnection  TEXTEQU <__imp_WNetCancelConnectionA>
extern __imp_WNetCancelConnectionW:PANYARGS
WNetCancelConnectionW TEXTEQU <__imp_WNetCancelConnectionW>
extern __imp_WNetClearConnections:PANYARGS
WNetClearConnections TEXTEQU <__imp_WNetClearConnections>
extern __imp_WNetCloseEnum:PANYARGS
WNetCloseEnum TEXTEQU <__imp_WNetCloseEnum>
extern __imp_WNetConnectionDialog:PANYARGS
WNetConnectionDialog TEXTEQU <__imp_WNetConnectionDialog>
extern __imp_WNetConnectionDialog1A:PANYARGS
WNetConnectionDialog1  TEXTEQU <__imp_WNetConnectionDialog1A>
extern __imp_WNetConnectionDialog1W:PANYARGS
WNetConnectionDialog1W TEXTEQU <__imp_WNetConnectionDialog1W>
extern __imp_WNetDirectoryNotifyA:PANYARGS
WNetDirectoryNotify  TEXTEQU <__imp_WNetDirectoryNotifyA>
extern __imp_WNetDirectoryNotifyW:PANYARGS
WNetDirectoryNotifyW TEXTEQU <__imp_WNetDirectoryNotifyW>
extern __imp_WNetDisconnectDialog:PANYARGS
WNetDisconnectDialog TEXTEQU <__imp_WNetDisconnectDialog>
extern __imp_WNetDisconnectDialog1A:PANYARGS
WNetDisconnectDialog1  TEXTEQU <__imp_WNetDisconnectDialog1A>
extern __imp_WNetDisconnectDialog1W:PANYARGS
WNetDisconnectDialog1W TEXTEQU <__imp_WNetDisconnectDialog1W>
extern __imp_WNetEnumResourceA:PANYARGS
WNetEnumResource  TEXTEQU <__imp_WNetEnumResourceA>
extern __imp_WNetEnumResourceW:PANYARGS
WNetEnumResourceW TEXTEQU <__imp_WNetEnumResourceW>
extern __imp_WNetFMXEditPerm:PANYARGS
WNetFMXEditPerm TEXTEQU <__imp_WNetFMXEditPerm>
extern __imp_WNetFMXGetPermCaps:PANYARGS
WNetFMXGetPermCaps TEXTEQU <__imp_WNetFMXGetPermCaps>
extern __imp_WNetFMXGetPermHelp:PANYARGS
WNetFMXGetPermHelp TEXTEQU <__imp_WNetFMXGetPermHelp>
extern __imp_WNetFormatNetworkNameA:PANYARGS
WNetFormatNetworkName  TEXTEQU <__imp_WNetFormatNetworkNameA>
extern __imp_WNetFormatNetworkNameW:PANYARGS
WNetFormatNetworkNameW TEXTEQU <__imp_WNetFormatNetworkNameW>
extern __imp_WNetGetConnection2A:PANYARGS
WNetGetConnection2  TEXTEQU <__imp_WNetGetConnection2A>
extern __imp_WNetGetConnection2W:PANYARGS
WNetGetConnection2W TEXTEQU <__imp_WNetGetConnection2W>
extern __imp_WNetGetConnection3A:PANYARGS
WNetGetConnection3  TEXTEQU <__imp_WNetGetConnection3A>
extern __imp_WNetGetConnection3W:PANYARGS
WNetGetConnection3W TEXTEQU <__imp_WNetGetConnection3W>
extern __imp_WNetGetConnectionA:PANYARGS
WNetGetConnection  TEXTEQU <__imp_WNetGetConnectionA>
extern __imp_WNetGetConnectionW:PANYARGS
WNetGetConnectionW TEXTEQU <__imp_WNetGetConnectionW>
extern __imp_WNetGetDirectoryTypeA:PANYARGS
WNetGetDirectoryType  TEXTEQU <__imp_WNetGetDirectoryTypeA>
extern __imp_WNetGetDirectoryTypeW:PANYARGS
WNetGetDirectoryTypeW TEXTEQU <__imp_WNetGetDirectoryTypeW>
extern __imp_WNetGetHomeDirectoryW:PANYARGS
WNetGetHomeDirectoryW TEXTEQU <__imp_WNetGetHomeDirectoryW>
extern __imp_WNetGetLastErrorA:PANYARGS
WNetGetLastError  TEXTEQU <__imp_WNetGetLastErrorA>
extern __imp_WNetGetLastErrorW:PANYARGS
WNetGetLastErrorW TEXTEQU <__imp_WNetGetLastErrorW>
extern __imp_WNetGetNetworkInformationA:PANYARGS
WNetGetNetworkInformation  TEXTEQU <__imp_WNetGetNetworkInformationA>
extern __imp_WNetGetNetworkInformationW:PANYARGS
WNetGetNetworkInformationW TEXTEQU <__imp_WNetGetNetworkInformationW>
extern __imp_WNetGetPropertyTextA:PANYARGS
WNetGetPropertyText  TEXTEQU <__imp_WNetGetPropertyTextA>
extern __imp_WNetGetPropertyTextW:PANYARGS
WNetGetPropertyTextW TEXTEQU <__imp_WNetGetPropertyTextW>
extern __imp_WNetGetProviderNameA:PANYARGS
WNetGetProviderName  TEXTEQU <__imp_WNetGetProviderNameA>
extern __imp_WNetGetProviderNameW:PANYARGS
WNetGetProviderNameW TEXTEQU <__imp_WNetGetProviderNameW>
extern __imp_WNetGetProviderTypeA:PANYARGS
WNetGetProviderType  TEXTEQU <__imp_WNetGetProviderTypeA>
extern __imp_WNetGetProviderTypeW:PANYARGS
WNetGetProviderTypeW TEXTEQU <__imp_WNetGetProviderTypeW>
extern __imp_WNetGetResourceInformationA:PANYARGS
WNetGetResourceInformation  TEXTEQU <__imp_WNetGetResourceInformationA>
extern __imp_WNetGetResourceInformationW:PANYARGS
WNetGetResourceInformationW TEXTEQU <__imp_WNetGetResourceInformationW>
extern __imp_WNetGetResourceParentA:PANYARGS
WNetGetResourceParent  TEXTEQU <__imp_WNetGetResourceParentA>
extern __imp_WNetGetResourceParentW:PANYARGS
WNetGetResourceParentW TEXTEQU <__imp_WNetGetResourceParentW>
extern __imp_WNetGetSearchDialog:PANYARGS
WNetGetSearchDialog TEXTEQU <__imp_WNetGetSearchDialog>
extern __imp_WNetGetUniversalNameA:PANYARGS
WNetGetUniversalName  TEXTEQU <__imp_WNetGetUniversalNameA>
extern __imp_WNetGetUniversalNameW:PANYARGS
WNetGetUniversalNameW TEXTEQU <__imp_WNetGetUniversalNameW>
extern __imp_WNetGetUserA:PANYARGS
WNetGetUser  TEXTEQU <__imp_WNetGetUserA>
extern __imp_WNetGetUserW:PANYARGS
WNetGetUserW TEXTEQU <__imp_WNetGetUserW>
extern __imp_WNetLogonNotify:PANYARGS
WNetLogonNotify TEXTEQU <__imp_WNetLogonNotify>
extern __imp_WNetOpenEnumA:PANYARGS
WNetOpenEnum  TEXTEQU <__imp_WNetOpenEnumA>
extern __imp_WNetOpenEnumW:PANYARGS
WNetOpenEnumW TEXTEQU <__imp_WNetOpenEnumW>
extern __imp_WNetPasswordChangeNotify:PANYARGS
WNetPasswordChangeNotify TEXTEQU <__imp_WNetPasswordChangeNotify>
extern __imp_WNetPropertyDialogA:PANYARGS
WNetPropertyDialog  TEXTEQU <__imp_WNetPropertyDialogA>
extern __imp_WNetPropertyDialogW:PANYARGS
WNetPropertyDialogW TEXTEQU <__imp_WNetPropertyDialogW>
extern __imp_WNetRestoreConnection2W:PANYARGS
WNetRestoreConnection2W TEXTEQU <__imp_WNetRestoreConnection2W>
extern __imp_WNetRestoreConnectionW:PANYARGS
WNetRestoreConnectionW TEXTEQU <__imp_WNetRestoreConnectionW>
extern __imp_WNetSetConnectionA:PANYARGS
WNetSetConnection  TEXTEQU <__imp_WNetSetConnectionA>
extern __imp_WNetSetConnectionW:PANYARGS
WNetSetConnectionW TEXTEQU <__imp_WNetSetConnectionW>
extern __imp_WNetSetLastErrorA:PANYARGS
WNetSetLastError  TEXTEQU <__imp_WNetSetLastErrorA>
extern __imp_WNetSetLastErrorW:PANYARGS
WNetSetLastErrorW TEXTEQU <__imp_WNetSetLastErrorW>
extern __imp_WNetSupportGlobalEnum:PANYARGS
WNetSupportGlobalEnum TEXTEQU <__imp_WNetSupportGlobalEnum>
extern __imp_WNetUseConnectionA:PANYARGS
WNetUseConnection  TEXTEQU <__imp_WNetUseConnectionA>
extern __imp_WNetUseConnectionW:PANYARGS
WNetUseConnectionW TEXTEQU <__imp_WNetUseConnectionW>
