extern __imp_DSBeginDeleteNotification:PANYARGS
DSBeginDeleteNotification TEXTEQU <__imp_DSBeginDeleteNotification>
extern __imp_DSClientInit:PANYARGS
DSClientInit TEXTEQU <__imp_DSClientInit>
extern __imp_DSCreateObject:PANYARGS
DSCreateObject TEXTEQU <__imp_DSCreateObject>
extern __imp_DSCreateServersCache:PANYARGS
DSCreateServersCache TEXTEQU <__imp_DSCreateServersCache>
extern __imp_DSDeleteObject:PANYARGS
DSDeleteObject TEXTEQU <__imp_DSDeleteObject>
extern __imp_DSDeleteObjectGuid:PANYARGS
DSDeleteObjectGuid TEXTEQU <__imp_DSDeleteObjectGuid>
extern __imp_DSEndDeleteNotification:PANYARGS
DSEndDeleteNotification TEXTEQU <__imp_DSEndDeleteNotification>
extern __imp_DSFreeMemory:PANYARGS
DSFreeMemory TEXTEQU <__imp_DSFreeMemory>
extern __imp_DSGetComputerSites:PANYARGS
DSGetComputerSites TEXTEQU <__imp_DSGetComputerSites>
extern __imp_DSGetObjectProperties:PANYARGS
DSGetObjectProperties TEXTEQU <__imp_DSGetObjectProperties>
extern __imp_DSGetObjectPropertiesEx:PANYARGS
DSGetObjectPropertiesEx TEXTEQU <__imp_DSGetObjectPropertiesEx>
extern __imp_DSGetObjectPropertiesGuid:PANYARGS
DSGetObjectPropertiesGuid TEXTEQU <__imp_DSGetObjectPropertiesGuid>
extern __imp_DSGetObjectPropertiesGuidEx:PANYARGS
DSGetObjectPropertiesGuidEx TEXTEQU <__imp_DSGetObjectPropertiesGuidEx>
extern __imp_DSGetObjectSecurity:PANYARGS
DSGetObjectSecurity TEXTEQU <__imp_DSGetObjectSecurity>
extern __imp_DSGetObjectSecurityGuid:PANYARGS
DSGetObjectSecurityGuid TEXTEQU <__imp_DSGetObjectSecurityGuid>
extern __imp_DSGetUserParams:PANYARGS
DSGetUserParams TEXTEQU <__imp_DSGetUserParams>
extern __imp_DSLookupBegin:PANYARGS
DSLookupBegin TEXTEQU <__imp_DSLookupBegin>
extern __imp_DSLookupEnd:PANYARGS
DSLookupEnd TEXTEQU <__imp_DSLookupEnd>
extern __imp_DSLookupNext:PANYARGS
DSLookupNext TEXTEQU <__imp_DSLookupNext>
extern __imp_DSNotifyDelete:PANYARGS
DSNotifyDelete TEXTEQU <__imp_DSNotifyDelete>
extern __imp_DSQMGetObjectSecurity:PANYARGS
DSQMGetObjectSecurity TEXTEQU <__imp_DSQMGetObjectSecurity>
extern __imp_DSSetObjectProperties:PANYARGS
DSSetObjectProperties TEXTEQU <__imp_DSSetObjectProperties>
extern __imp_DSSetObjectPropertiesGuid:PANYARGS
DSSetObjectPropertiesGuid TEXTEQU <__imp_DSSetObjectPropertiesGuid>
extern __imp_DSSetObjectSecurity:PANYARGS
DSSetObjectSecurity TEXTEQU <__imp_DSSetObjectSecurity>
extern __imp_DSSetObjectSecurityGuid:PANYARGS
DSSetObjectSecurityGuid TEXTEQU <__imp_DSSetObjectSecurityGuid>
extern __imp_DSTerminate:PANYARGS
DSTerminate TEXTEQU <__imp_DSTerminate>
