extern __imp_?CreateInstance@CLogMgr@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PANYARGS
?CreateInstance@CLogMgr@@SAJPEAPEAV1@PEAUIUnknown@@@Z TEXTEQU <__imp_?CreateInstance@CLogMgr@@SAJPEAPEAV1@PEAUIUnknown@@@Z>
extern __imp_DllGetDTCLOG2:PANYARGS
DllGetDTCLOG2 TEXTEQU <__imp_DllGetDTCLOG2>
extern __imp_?DllGetDTCLOG@@YAHAEBU_GUID@@0PEAPEAX@Z:PANYARGS
?DllGetDTCLOG@@YAHAEBU_GUID@@0PEAPEAX@Z TEXTEQU <__imp_?DllGetDTCLOG@@YAHAEBU_GUID@@0PEAPEAX@Z>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
