extern __imp_MQLogHR:PANYARGS
MQLogHR TEXTEQU <__imp_MQLogHR>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_MQADsPathToFormatName:PANYARGS
MQADsPathToFormatName TEXTEQU <__imp_MQADsPathToFormatName>
extern __imp_MQAllocateMemory:PANYARGS
MQAllocateMemory TEXTEQU <__imp_MQAllocateMemory>
extern __imp_MQBeginTransaction:PANYARGS
MQBeginTransaction TEXTEQU <__imp_MQBeginTransaction>
extern __imp_MQCloseCursor:PANYARGS
MQCloseCursor TEXTEQU <__imp_MQCloseCursor>
extern __imp_MQCloseQueue:PANYARGS
MQCloseQueue TEXTEQU <__imp_MQCloseQueue>
extern __imp_MQCreateCursor:PANYARGS
MQCreateCursor TEXTEQU <__imp_MQCreateCursor>
extern __imp_MQCreateQueue:PANYARGS
MQCreateQueue TEXTEQU <__imp_MQCreateQueue>
extern __imp_MQDeleteQueue:PANYARGS
MQDeleteQueue TEXTEQU <__imp_MQDeleteQueue>
extern __imp_MQFreeMemory:PANYARGS
MQFreeMemory TEXTEQU <__imp_MQFreeMemory>
extern __imp_MQFreeSecurityContext:PANYARGS
MQFreeSecurityContext TEXTEQU <__imp_MQFreeSecurityContext>
extern __imp_MQGetMachineProperties:PANYARGS
MQGetMachineProperties TEXTEQU <__imp_MQGetMachineProperties>
extern __imp_MQGetOverlappedResult:PANYARGS
MQGetOverlappedResult TEXTEQU <__imp_MQGetOverlappedResult>
extern __imp_MQGetPrivateComputerInformation:PANYARGS
MQGetPrivateComputerInformation TEXTEQU <__imp_MQGetPrivateComputerInformation>
extern __imp_MQGetQueueProperties:PANYARGS
MQGetQueueProperties TEXTEQU <__imp_MQGetQueueProperties>
extern __imp_MQGetQueueSecurity:PANYARGS
MQGetQueueSecurity TEXTEQU <__imp_MQGetQueueSecurity>
extern __imp_MQGetSecurityContext:PANYARGS
MQGetSecurityContext TEXTEQU <__imp_MQGetSecurityContext>
extern __imp_MQGetSecurityContextEx:PANYARGS
MQGetSecurityContextEx TEXTEQU <__imp_MQGetSecurityContextEx>
extern __imp_MQHandleToFormatName:PANYARGS
MQHandleToFormatName TEXTEQU <__imp_MQHandleToFormatName>
extern __imp_MQInstanceToFormatName:PANYARGS
MQInstanceToFormatName TEXTEQU <__imp_MQInstanceToFormatName>
extern __imp_MQLocateBegin:PANYARGS
MQLocateBegin TEXTEQU <__imp_MQLocateBegin>
extern __imp_MQLocateEnd:PANYARGS
MQLocateEnd TEXTEQU <__imp_MQLocateEnd>
extern __imp_MQLocateNext:PANYARGS
MQLocateNext TEXTEQU <__imp_MQLocateNext>
extern __imp_MQMgmtAction:PANYARGS
MQMgmtAction TEXTEQU <__imp_MQMgmtAction>
extern __imp_MQMgmtGetInfo:PANYARGS
MQMgmtGetInfo TEXTEQU <__imp_MQMgmtGetInfo>
extern __imp_MQOpenQueue:PANYARGS
MQOpenQueue TEXTEQU <__imp_MQOpenQueue>
extern __imp_MQPathNameToFormatName:PANYARGS
MQPathNameToFormatName TEXTEQU <__imp_MQPathNameToFormatName>
extern __imp_MQPurgeQueue:PANYARGS
MQPurgeQueue TEXTEQU <__imp_MQPurgeQueue>
extern __imp_MQReceiveMessage:PANYARGS
MQReceiveMessage TEXTEQU <__imp_MQReceiveMessage>
extern __imp_MQReceiveMessageByLookupId:PANYARGS
MQReceiveMessageByLookupId TEXTEQU <__imp_MQReceiveMessageByLookupId>
extern __imp_MQRegisterCertificate:PANYARGS
MQRegisterCertificate TEXTEQU <__imp_MQRegisterCertificate>
extern __imp_MQSendMessage:PANYARGS
MQSendMessage TEXTEQU <__imp_MQSendMessage>
extern __imp_MQSetQueueProperties:PANYARGS
MQSetQueueProperties TEXTEQU <__imp_MQSetQueueProperties>
extern __imp_MQSetQueueSecurity:PANYARGS
MQSetQueueSecurity TEXTEQU <__imp_MQSetQueueSecurity>
extern __imp_RTCreateInternalCertificate:PANYARGS
RTCreateInternalCertificate TEXTEQU <__imp_RTCreateInternalCertificate>
extern __imp_RTDeleteInternalCert:PANYARGS
RTDeleteInternalCert TEXTEQU <__imp_RTDeleteInternalCert>
extern __imp_RTGetInternalCert:PANYARGS
RTGetInternalCert TEXTEQU <__imp_RTGetInternalCert>
extern __imp_RTGetUserCerts:PANYARGS
RTGetUserCerts TEXTEQU <__imp_RTGetUserCerts>
extern __imp_RTIsDependentClient:PANYARGS
RTIsDependentClient TEXTEQU <__imp_RTIsDependentClient>
extern __imp_RTLogOnRegisterCert:PANYARGS
RTLogOnRegisterCert TEXTEQU <__imp_RTLogOnRegisterCert>
extern __imp_RTOpenInternalCertStore:PANYARGS
RTOpenInternalCertStore TEXTEQU <__imp_RTOpenInternalCertStore>
extern __imp_RTRegisterUserCert:PANYARGS
RTRegisterUserCert TEXTEQU <__imp_RTRegisterUserCert>
extern __imp_RTRemoveUserCert:PANYARGS
RTRemoveUserCert TEXTEQU <__imp_RTRemoveUserCert>
extern __imp_RTRemoveUserCertSid:PANYARGS
RTRemoveUserCertSid TEXTEQU <__imp_RTRemoveUserCertSid>
extern __imp_RTXactGetDTC:PANYARGS
RTXactGetDTC TEXTEQU <__imp_RTXactGetDTC>
