extern __imp_DepBeginTransaction:PANYARGS
DepBeginTransaction TEXTEQU <__imp_DepBeginTransaction>
extern __imp_DepCloseCursor:PANYARGS
DepCloseCursor TEXTEQU <__imp_DepCloseCursor>
extern __imp_DepCloseQueue:PANYARGS
DepCloseQueue TEXTEQU <__imp_DepCloseQueue>
extern __imp_DepCreateCursor:PANYARGS
DepCreateCursor TEXTEQU <__imp_DepCreateCursor>
extern __imp_DepCreateInternalCertificate:PANYARGS
DepCreateInternalCertificate TEXTEQU <__imp_DepCreateInternalCertificate>
extern __imp_DepCreateQueue:PANYARGS
DepCreateQueue TEXTEQU <__imp_DepCreateQueue>
extern __imp_DepDeleteInternalCert:PANYARGS
DepDeleteInternalCert TEXTEQU <__imp_DepDeleteInternalCert>
extern __imp_DepDeleteQueue:PANYARGS
DepDeleteQueue TEXTEQU <__imp_DepDeleteQueue>
extern __imp_DepFreeMemory:PANYARGS
DepFreeMemory TEXTEQU <__imp_DepFreeMemory>
extern __imp_DepFreeSecurityContext:PANYARGS
DepFreeSecurityContext TEXTEQU <__imp_DepFreeSecurityContext>
extern __imp_DepGetInternalCert:PANYARGS
DepGetInternalCert TEXTEQU <__imp_DepGetInternalCert>
extern __imp_DepGetMachineProperties:PANYARGS
DepGetMachineProperties TEXTEQU <__imp_DepGetMachineProperties>
extern __imp_DepGetOverlappedResult:PANYARGS
DepGetOverlappedResult TEXTEQU <__imp_DepGetOverlappedResult>
extern __imp_DepGetPrivateComputerInformation:PANYARGS
DepGetPrivateComputerInformation TEXTEQU <__imp_DepGetPrivateComputerInformation>
extern __imp_DepGetQueueProperties:PANYARGS
DepGetQueueProperties TEXTEQU <__imp_DepGetQueueProperties>
extern __imp_DepGetQueueSecurity:PANYARGS
DepGetQueueSecurity TEXTEQU <__imp_DepGetQueueSecurity>
extern __imp_DepGetSecurityContext:PANYARGS
DepGetSecurityContext TEXTEQU <__imp_DepGetSecurityContext>
extern __imp_DepGetSecurityContextEx:PANYARGS
DepGetSecurityContextEx TEXTEQU <__imp_DepGetSecurityContextEx>
extern __imp_DepGetUserCerts:PANYARGS
DepGetUserCerts TEXTEQU <__imp_DepGetUserCerts>
extern __imp_DepHandleToFormatName:PANYARGS
DepHandleToFormatName TEXTEQU <__imp_DepHandleToFormatName>
extern __imp_DepInstanceToFormatName:PANYARGS
DepInstanceToFormatName TEXTEQU <__imp_DepInstanceToFormatName>
extern __imp_DepLocateBegin:PANYARGS
DepLocateBegin TEXTEQU <__imp_DepLocateBegin>
extern __imp_DepLocateEnd:PANYARGS
DepLocateEnd TEXTEQU <__imp_DepLocateEnd>
extern __imp_DepLocateNext:PANYARGS
DepLocateNext TEXTEQU <__imp_DepLocateNext>
extern __imp_DepMgmtAction:PANYARGS
DepMgmtAction TEXTEQU <__imp_DepMgmtAction>
extern __imp_DepMgmtGetInfo:PANYARGS
DepMgmtGetInfo TEXTEQU <__imp_DepMgmtGetInfo>
extern __imp_DepOpenInternalCertStore:PANYARGS
DepOpenInternalCertStore TEXTEQU <__imp_DepOpenInternalCertStore>
extern __imp_DepOpenQueue:PANYARGS
DepOpenQueue TEXTEQU <__imp_DepOpenQueue>
extern __imp_DepPathNameToFormatName:PANYARGS
DepPathNameToFormatName TEXTEQU <__imp_DepPathNameToFormatName>
extern __imp_DepPurgeQueue:PANYARGS
DepPurgeQueue TEXTEQU <__imp_DepPurgeQueue>
extern __imp_DepReceiveMessage:PANYARGS
DepReceiveMessage TEXTEQU <__imp_DepReceiveMessage>
extern __imp_DepRegisterCertificate:PANYARGS
DepRegisterCertificate TEXTEQU <__imp_DepRegisterCertificate>
extern __imp_DepRegisterServer:PANYARGS
DepRegisterServer TEXTEQU <__imp_DepRegisterServer>
extern __imp_DepRegisterUserCert:PANYARGS
DepRegisterUserCert TEXTEQU <__imp_DepRegisterUserCert>
extern __imp_DepRemoveUserCert:PANYARGS
DepRemoveUserCert TEXTEQU <__imp_DepRemoveUserCert>
extern __imp_DepSendMessage:PANYARGS
DepSendMessage TEXTEQU <__imp_DepSendMessage>
extern __imp_DepSetQueueProperties:PANYARGS
DepSetQueueProperties TEXTEQU <__imp_DepSetQueueProperties>
extern __imp_DepSetQueueSecurity:PANYARGS
DepSetQueueSecurity TEXTEQU <__imp_DepSetQueueSecurity>
extern __imp_DepXactGetDTC:PANYARGS
DepXactGetDTC TEXTEQU <__imp_DepXactGetDTC>
