extern __imp_??0CCancelRpc@@QEAA@AEBV0@@Z:PANYARGS
??0CCancelRpc@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CCancelRpc@@QEAA@AEBV0@@Z>
extern __imp_??0CCancelRpc@@QEAA@XZ:PANYARGS
??0CCancelRpc@@QEAA@XZ TEXTEQU <__imp_??0CCancelRpc@@QEAA@XZ>
extern __imp_??0CColumns@@QEAA@AEBV0@@Z:PANYARGS
??0CColumns@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CColumns@@QEAA@AEBV0@@Z>
extern __imp_??0CColumns@@QEAA@I@Z:PANYARGS
??0CColumns@@QEAA@I@Z TEXTEQU <__imp_??0CColumns@@QEAA@I@Z>
extern __imp_??0CDSBaseUpdate@@QEAA@AEBV0@@Z:PANYARGS
??0CDSBaseUpdate@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CDSBaseUpdate@@QEAA@AEBV0@@Z>
extern __imp_??0CDSBaseUpdate@@QEAA@XZ:PANYARGS
??0CDSBaseUpdate@@QEAA@XZ TEXTEQU <__imp_??0CDSBaseUpdate@@QEAA@XZ>
extern __imp_??0COutputReport@@QEAA@XZ:PANYARGS
??0COutputReport@@QEAA@XZ TEXTEQU <__imp_??0COutputReport@@QEAA@XZ>
extern __imp_??0CPropertyRestriction@@QEAA@AEBV0@@Z:PANYARGS
??0CPropertyRestriction@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CPropertyRestriction@@QEAA@AEBV0@@Z>
extern __imp_??0CPropertyRestriction@@QEAA@KAEBKAEBVCMQVariant@@@Z:PANYARGS
??0CPropertyRestriction@@QEAA@KAEBKAEBVCMQVariant@@@Z TEXTEQU <__imp_??0CPropertyRestriction@@QEAA@KAEBKAEBVCMQVariant@@@Z>
extern __imp_??0CPropertyRestriction@@QEAA@XZ:PANYARGS
??0CPropertyRestriction@@QEAA@XZ TEXTEQU <__imp_??0CPropertyRestriction@@QEAA@XZ>
extern __imp_??0CRestriction@@QEAA@AEBV0@@Z:PANYARGS
??0CRestriction@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CRestriction@@QEAA@AEBV0@@Z>
extern __imp_??0CRestriction@@QEAA@I@Z:PANYARGS
??0CRestriction@@QEAA@I@Z TEXTEQU <__imp_??0CRestriction@@QEAA@I@Z>
extern __imp_??0CSort@@QEAA@AEBV0@@Z:PANYARGS
??0CSort@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CSort@@QEAA@AEBV0@@Z>
extern __imp_??0CSort@@QEAA@I@Z:PANYARGS
??0CSort@@QEAA@I@Z TEXTEQU <__imp_??0CSort@@QEAA@I@Z>
extern __imp_??0CSortKey@@QEAA@AEBKK@Z:PANYARGS
??0CSortKey@@QEAA@AEBKK@Z TEXTEQU <__imp_??0CSortKey@@QEAA@AEBKK@Z>
extern __imp_??0CSortKey@@QEAA@XZ:PANYARGS
??0CSortKey@@QEAA@XZ TEXTEQU <__imp_??0CSortKey@@QEAA@XZ>
extern __imp_??1CCancelRpc@@QEAA@XZ:PANYARGS
??1CCancelRpc@@QEAA@XZ TEXTEQU <__imp_??1CCancelRpc@@QEAA@XZ>
extern __imp_??1CColumns@@QEAA@XZ:PANYARGS
??1CColumns@@QEAA@XZ TEXTEQU <__imp_??1CColumns@@QEAA@XZ>
extern __imp_??1CDSBaseUpdate@@QEAA@XZ:PANYARGS
??1CDSBaseUpdate@@QEAA@XZ TEXTEQU <__imp_??1CDSBaseUpdate@@QEAA@XZ>
extern __imp_??1COutputReport@@QEAA@XZ:PANYARGS
??1COutputReport@@QEAA@XZ TEXTEQU <__imp_??1COutputReport@@QEAA@XZ>
extern __imp_??1CPropertyRestriction@@QEAA@XZ:PANYARGS
??1CPropertyRestriction@@QEAA@XZ TEXTEQU <__imp_??1CPropertyRestriction@@QEAA@XZ>
extern __imp_??1CRestriction@@QEAA@XZ:PANYARGS
??1CRestriction@@QEAA@XZ TEXTEQU <__imp_??1CRestriction@@QEAA@XZ>
extern __imp_??1CSort@@QEAA@XZ:PANYARGS
??1CSort@@QEAA@XZ TEXTEQU <__imp_??1CSort@@QEAA@XZ>
extern __imp_??1CSortKey@@QEAA@XZ:PANYARGS
??1CSortKey@@QEAA@XZ TEXTEQU <__imp_??1CSortKey@@QEAA@XZ>
extern __imp_??4CCancelRpc@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CCancelRpc@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CCancelRpc@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CDSBaseUpdate@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CDSBaseUpdate@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CDSBaseUpdate@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4COutputReport@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4COutputReport@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4COutputReport@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CPropertyRestriction@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CPropertyRestriction@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CPropertyRestriction@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CRestriction@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CRestriction@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CRestriction@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CSortKey@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CSortKey@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CSortKey@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_FCColumns@@QEAAXXZ:PANYARGS
??_FCColumns@@QEAAXXZ TEXTEQU <__imp_??_FCColumns@@QEAAXXZ>
extern __imp_??_FCRestriction@@QEAAXXZ:PANYARGS
??_FCRestriction@@QEAAXXZ TEXTEQU <__imp_??_FCRestriction@@QEAAXXZ>
extern __imp_??_FCSort@@QEAAXXZ:PANYARGS
??_FCSort@@QEAAXXZ TEXTEQU <__imp_??_FCSort@@QEAAXXZ>
extern __imp_?Add@CCancelRpc@@QEAAXPEAX_J@Z:PANYARGS
?Add@CCancelRpc@@QEAAXPEAX_J@Z TEXTEQU <__imp_?Add@CCancelRpc@@QEAAXPEAX_J@Z>
extern __imp_?Add@CColumns@@QEAAXAEBK@Z:PANYARGS
?Add@CColumns@@QEAAXAEBK@Z TEXTEQU <__imp_?Add@CColumns@@QEAAXAEBK@Z>
extern __imp_?Add@CSort@@QEAAXAEBKK@Z:PANYARGS
?Add@CSort@@QEAAXAEBKK@Z TEXTEQU <__imp_?Add@CSort@@QEAAXAEBKK@Z>
extern __imp_?Add@CSort@@QEAAXAEBVCSortKey@@@Z:PANYARGS
?Add@CSort@@QEAAXAEBVCSortKey@@@Z TEXTEQU <__imp_?Add@CSort@@QEAAXAEBVCSortKey@@@Z>
extern __imp_?AddChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@@Z:PANYARGS
?AddChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@@Z TEXTEQU <__imp_?AddChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXAEAUtagBLOB@@KK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXAEAUtagBLOB@@KK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXAEAUtagBLOB@@KK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXAEBVCMQVariant@@KK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXAEBVCMQVariant@@KK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXAEBVCMQVariant@@KK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXEKK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXEKK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXEKK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXFKK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXFKK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXFKK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXJKK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXJKK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXJKK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXKKK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXKKK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXKKK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXPEAGKK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXPEAGKK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXPEAGKK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXPEAU_GUID@@KK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXPEAU_GUID@@KK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXPEAU_GUID@@KK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCACLSID@@KK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXPEAUtagCACLSID@@KK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCACLSID@@KK@Z>
extern __imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCALPWSTR@@KK@Z:PANYARGS
?AddRestriction@CRestriction@@QEAAXPEAUtagCALPWSTR@@KK@Z TEXTEQU <__imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCALPWSTR@@KK@Z>
extern __imp_?CancelRequests@CCancelRpc@@QEAAX_J@Z:PANYARGS
?CancelRequests@CCancelRpc@@QEAAX_J@Z TEXTEQU <__imp_?CancelRequests@CCancelRpc@@QEAAX_J@Z>
extern __imp_?CancelThread@CCancelRpc@@CAKPEAX@Z:PANYARGS
?CancelThread@CCancelRpc@@CAKPEAX@Z TEXTEQU <__imp_?CancelThread@CCancelRpc@@CAKPEAX@Z>
extern __imp_?CastToStruct@CColumns@@QEAAPEAUtagMQCOLUMNSET@@XZ:PANYARGS
?CastToStruct@CColumns@@QEAAPEAUtagMQCOLUMNSET@@XZ TEXTEQU <__imp_?CastToStruct@CColumns@@QEAAPEAUtagMQCOLUMNSET@@XZ>
extern __imp_?CastToStruct@CRestriction@@QEAAPEAUtagMQRESTRICTION@@XZ:PANYARGS
?CastToStruct@CRestriction@@QEAAPEAUtagMQRESTRICTION@@XZ TEXTEQU <__imp_?CastToStruct@CRestriction@@QEAAPEAUtagMQRESTRICTION@@XZ>
extern __imp_?CastToStruct@CSort@@QEAAPEAUtagMQSORTSET@@XZ:PANYARGS
?CastToStruct@CSort@@QEAAPEAUtagMQSORTSET@@XZ TEXTEQU <__imp_?CastToStruct@CSort@@QEAAPEAUtagMQSORTSET@@XZ>
extern __imp_?ComposeRPCEndPointName@@YAXPEBG0PEAPEAG@Z:PANYARGS
?ComposeRPCEndPointName@@YAXPEBG0PEAPEAG@Z TEXTEQU <__imp_?ComposeRPCEndPointName@@YAXPEBG0PEAPEAG@Z>
extern __imp_?CopyProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAU2@@Z:PANYARGS
?CopyProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAU2@@Z TEXTEQU <__imp_?CopyProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAU2@@Z>
extern __imp_?Count@CColumns@@QEBAIXZ:PANYARGS
?Count@CColumns@@QEBAIXZ TEXTEQU <__imp_?Count@CColumns@@QEBAIXZ>
extern __imp_?Count@CRestriction@@QEBAIXZ:PANYARGS
?Count@CRestriction@@QEBAIXZ TEXTEQU <__imp_?Count@CRestriction@@QEBAIXZ>
extern __imp_?Count@CSort@@QEBAIXZ:PANYARGS
?Count@CSort@@QEBAIXZ TEXTEQU <__imp_?Count@CSort@@QEBAIXZ>
extern __imp_?DeleteFalconKeyValue@@YAJPEBG@Z:PANYARGS
?DeleteFalconKeyValue@@YAJPEBG@Z TEXTEQU <__imp_?DeleteFalconKeyValue@@YAJPEBG@Z>
extern __imp_?DeleteProperty@CDSBaseUpdate@@AEAAXAEAUtagPROPVARIANT@@@Z:PANYARGS
?DeleteProperty@CDSBaseUpdate@@AEAAXAEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?DeleteProperty@CDSBaseUpdate@@AEAAXAEAUtagPROPVARIANT@@@Z>
extern __imp_FreeContextHandle:PANYARGS
FreeContextHandle TEXTEQU <__imp_FreeContextHandle>
extern __imp_?Get@CColumns@@QEBAAEBKI@Z:PANYARGS
?Get@CColumns@@QEBAAEBKI@Z TEXTEQU <__imp_?Get@CColumns@@QEBAAEBKI@Z>
extern __imp_?Get@CSort@@QEBAAEBVCSortKey@@I@Z:PANYARGS
?Get@CSort@@QEBAAEBVCSortKey@@I@Z TEXTEQU <__imp_?Get@CSort@@QEBAAEBVCSortKey@@I@Z>
extern __imp_?GetChild@CRestriction@@QEBAAEBVCPropertyRestriction@@I@Z:PANYARGS
?GetChild@CRestriction@@QEBAAEBVCPropertyRestriction@@I@Z TEXTEQU <__imp_?GetChild@CRestriction@@QEBAAEBVCPropertyRestriction@@I@Z>
extern __imp_?GetCommand@CDSBaseUpdate@@QEAAEXZ:PANYARGS
?GetCommand@CDSBaseUpdate@@QEAAEXZ TEXTEQU <__imp_?GetCommand@CDSBaseUpdate@@QEAAEXZ>
extern __imp_?GetComputerDnsNameInternal@@YAJPEAGPEAK@Z:PANYARGS
?GetComputerDnsNameInternal@@YAJPEAGPEAK@Z TEXTEQU <__imp_?GetComputerDnsNameInternal@@YAJPEAGPEAK@Z>
extern __imp_?GetComputerNameInternal@@YAJPEAGPEAK@Z:PANYARGS
?GetComputerNameInternal@@YAJPEAGPEAK@Z TEXTEQU <__imp_?GetComputerNameInternal@@YAJPEAGPEAK@Z>
extern __imp_GetDomainFQDNName:PANYARGS
GetDomainFQDNName TEXTEQU <__imp_GetDomainFQDNName>
extern __imp_?GetFalconKey@@YAJPEBGPEAPEAUHKEY__@@@Z:PANYARGS
?GetFalconKey@@YAJPEBGPEAPEAUHKEY__@@@Z TEXTEQU <__imp_?GetFalconKey@@YAJPEBGPEAPEAUHKEY__@@@Z>
extern __imp_GetFalconKeyValue:PANYARGS
GetFalconKeyValue TEXTEQU <__imp_GetFalconKeyValue>
extern __imp_?GetFalconSectionName@@YAPEBGXZ:PANYARGS
?GetFalconSectionName@@YAPEBGXZ TEXTEQU <__imp_?GetFalconSectionName@@YAPEBGXZ>
extern __imp_?GetFalconServiceName@@YAKPEAGK@Z:PANYARGS
?GetFalconServiceName@@YAKPEAGK@Z TEXTEQU <__imp_?GetFalconServiceName@@YAKPEAGK@Z>
extern __imp_?GetGuidIdentifier@CDSBaseUpdate@@QEAAPEAU_GUID@@XZ:PANYARGS
?GetGuidIdentifier@CDSBaseUpdate@@QEAAPEAU_GUID@@XZ TEXTEQU <__imp_?GetGuidIdentifier@CDSBaseUpdate@@QEAAPEAU_GUID@@XZ>
extern __imp_?GetMasterId@CDSBaseUpdate@@QEAAPEBU_GUID@@XZ:PANYARGS
?GetMasterId@CDSBaseUpdate@@QEAAPEBU_GUID@@XZ TEXTEQU <__imp_?GetMasterId@CDSBaseUpdate@@QEAAPEBU_GUID@@XZ>
extern __imp_?GetObjectType@CDSBaseUpdate@@QEAAKXZ:PANYARGS
?GetObjectType@CDSBaseUpdate@@QEAAKXZ TEXTEQU <__imp_?GetObjectType@CDSBaseUpdate@@QEAAKXZ>
extern __imp_?GetOrder@CSortKey@@QEBAKXZ:PANYARGS
?GetOrder@CSortKey@@QEBAKXZ TEXTEQU <__imp_?GetOrder@CSortKey@@QEBAKXZ>
extern __imp_?GetPathName@CDSBaseUpdate@@QEAAPEAGXZ:PANYARGS
?GetPathName@CDSBaseUpdate@@QEAAPEAGXZ TEXTEQU <__imp_?GetPathName@CDSBaseUpdate@@QEAAPEAGXZ>
extern __imp_?GetPrevSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ:PANYARGS
?GetPrevSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ TEXTEQU <__imp_?GetPrevSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ>
extern __imp_?GetProperty@CSortKey@@QEBAAEBKXZ:PANYARGS
?GetProperty@CSortKey@@QEBAAEBKXZ TEXTEQU <__imp_?GetProperty@CSortKey@@QEBAAEBKXZ>
extern __imp_?GetProps@CDSBaseUpdate@@QEAAPEAKXZ:PANYARGS
?GetProps@CDSBaseUpdate@@QEAAPEAKXZ TEXTEQU <__imp_?GetProps@CDSBaseUpdate@@QEAAPEAKXZ>
extern __imp_?GetPurgeSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ:PANYARGS
?GetPurgeSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ TEXTEQU <__imp_?GetPurgeSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ>
extern __imp_?GetSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ:PANYARGS
?GetSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ TEXTEQU <__imp_?GetSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ>
extern __imp_?GetSerializeSize@CDSBaseUpdate@@QEAAJPEAK@Z:PANYARGS
?GetSerializeSize@CDSBaseUpdate@@QEAAJPEAK@Z TEXTEQU <__imp_?GetSerializeSize@CDSBaseUpdate@@QEAAJPEAK@Z>
extern __imp_GetSizes:PANYARGS
GetSizes TEXTEQU <__imp_GetSizes>
extern __imp_?GetThisServerIpPort@@YAJPEAGK@Z:PANYARGS
?GetThisServerIpPort@@YAJPEAGK@Z TEXTEQU <__imp_?GetThisServerIpPort@@YAJPEAGK@Z>
extern __imp_?GetVars@CDSBaseUpdate@@QEAAPEAUtagPROPVARIANT@@XZ:PANYARGS
?GetVars@CDSBaseUpdate@@QEAAPEAUtagPROPVARIANT@@XZ TEXTEQU <__imp_?GetVars@CDSBaseUpdate@@QEAAPEAUtagPROPVARIANT@@XZ>
extern __imp_?Grow@CRestriction@@AEAAXXZ:PANYARGS
?Grow@CRestriction@@AEAAXXZ TEXTEQU <__imp_?Grow@CRestriction@@AEAAXXZ>
extern __imp_?HashMessageProperties@@YAJ_KPEBEKK1KPEBGKPEBUQUEUE_FORMAT@@3@Z:PANYARGS
?HashMessageProperties@@YAJ_KPEBEKK1KPEBGKPEBUQUEUE_FORMAT@@3@Z TEXTEQU <__imp_?HashMessageProperties@@YAJ_KPEBEKK1KPEBGKPEBUQUEUE_FORMAT@@3@Z>
extern __imp_?HashProperties@@YAJ_KKPEAKPEAUtagPROPVARIANT@@@Z:PANYARGS
?HashProperties@@YAJ_KKPEAKPEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?HashProperties@@YAJ_KKPEAKPEAUtagPROPVARIANT@@@Z>
extern __imp_?Init@CCancelRpc@@QEAAXXZ:PANYARGS
?Init@CCancelRpc@@QEAAXXZ TEXTEQU <__imp_?Init@CCancelRpc@@QEAAXXZ>
extern __imp_?Init@CDSBaseUpdate@@QEAAJPEBEPEAKH@Z:PANYARGS
?Init@CDSBaseUpdate@@QEAAJPEBEPEAKH@Z TEXTEQU <__imp_?Init@CDSBaseUpdate@@QEAAJPEBEPEAKH@Z>
extern __imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEK0KPEAKPEAUtagPROPVARIANT@@@Z:PANYARGS
?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEK0KPEAKPEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEK0KPEAKPEAUtagPROPVARIANT@@@Z>
extern __imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEKPEAGKPEAKPEAUtagPROPVARIANT@@@Z:PANYARGS
?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEKPEAGKPEAKPEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEKPEAGKPEAKPEAUtagPROPVARIANT@@@Z>
extern __imp_?InitProperty@CDSBaseUpdate@@AEAAJPEBEPEAKKAEAUtagPROPVARIANT@@@Z:PANYARGS
?InitProperty@CDSBaseUpdate@@AEAAJPEBEPEAKKAEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?InitProperty@CDSBaseUpdate@@AEAAJPEBEPEAKKAEAUtagPROPVARIANT@@@Z>
extern __imp_?IsLocalSystemCluster@@YA_NXZ:PANYARGS
?IsLocalSystemCluster@@YA_NXZ TEXTEQU <__imp_?IsLocalSystemCluster@@YA_NXZ>
extern __imp_?KeepErrorHistory@COutputReport@@QEAAXPEBGGJ@Z:PANYARGS
?KeepErrorHistory@COutputReport@@QEAAXPEBGGJ@Z TEXTEQU <__imp_?KeepErrorHistory@COutputReport@@QEAAXPEBGGJ@Z>
extern __imp_MQSealBuffer:PANYARGS
MQSealBuffer TEXTEQU <__imp_MQSealBuffer>
extern __imp_MQSec_AccessCheck:PANYARGS
MQSec_AccessCheck TEXTEQU <__imp_MQSec_AccessCheck>
extern __imp_MQSec_AccessCheckForSelf:PANYARGS
MQSec_AccessCheckForSelf TEXTEQU <__imp_MQSec_AccessCheckForSelf>
extern __imp_MQSec_AcquireCryptoProvider:PANYARGS
MQSec_AcquireCryptoProvider TEXTEQU <__imp_MQSec_AcquireCryptoProvider>
extern __imp_MQSec_CanGenerateAudit:PANYARGS
MQSec_CanGenerateAudit TEXTEQU <__imp_MQSec_CanGenerateAudit>
extern __imp_MQSec_ConvertSDToNT4Format:PANYARGS
MQSec_ConvertSDToNT4Format TEXTEQU <__imp_MQSec_ConvertSDToNT4Format>
extern __imp_MQSec_ConvertSDToNT5Format:PANYARGS
MQSec_ConvertSDToNT5Format TEXTEQU <__imp_MQSec_ConvertSDToNT5Format>
extern __imp_MQSec_CopySecurityDescriptor:PANYARGS
MQSec_CopySecurityDescriptor TEXTEQU <__imp_MQSec_CopySecurityDescriptor>
extern __imp_MQSec_GetAdminSid:PANYARGS
MQSec_GetAdminSid TEXTEQU <__imp_MQSec_GetAdminSid>
extern __imp_MQSec_GetAnonymousSid:PANYARGS
MQSec_GetAnonymousSid TEXTEQU <__imp_MQSec_GetAnonymousSid>
extern __imp_MQSec_GetCryptoProvProperty:PANYARGS
MQSec_GetCryptoProvProperty TEXTEQU <__imp_MQSec_GetCryptoProvProperty>
extern __imp_MQSec_GetDefaultSecDescriptor:PANYARGS
MQSec_GetDefaultSecDescriptor TEXTEQU <__imp_MQSec_GetDefaultSecDescriptor>
extern __imp_MQSec_GetImpersonationObject:PANYARGS
MQSec_GetImpersonationObject TEXTEQU <__imp_MQSec_GetImpersonationObject>
extern __imp_MQSec_GetLocalMachineSid:PANYARGS
MQSec_GetLocalMachineSid TEXTEQU <__imp_MQSec_GetLocalMachineSid>
extern __imp_MQSec_GetLocalSystemSid:PANYARGS
MQSec_GetLocalSystemSid TEXTEQU <__imp_MQSec_GetLocalSystemSid>
extern __imp_MQSec_GetNetworkServiceSid:PANYARGS
MQSec_GetNetworkServiceSid TEXTEQU <__imp_MQSec_GetNetworkServiceSid>
extern __imp_MQSec_GetProcessSid:PANYARGS
MQSec_GetProcessSid TEXTEQU <__imp_MQSec_GetProcessSid>
extern __imp_MQSec_GetProcessUserSid:PANYARGS
MQSec_GetProcessUserSid TEXTEQU <__imp_MQSec_GetProcessUserSid>
extern __imp_MQSec_GetPubKeysFromDS:PANYARGS
MQSec_GetPubKeysFromDS TEXTEQU <__imp_MQSec_GetPubKeysFromDS>
extern __imp_MQSec_GetThreadUserSid:PANYARGS
MQSec_GetThreadUserSid TEXTEQU <__imp_MQSec_GetThreadUserSid>
extern __imp_MQSec_GetUserType:PANYARGS
MQSec_GetUserType TEXTEQU <__imp_MQSec_GetUserType>
extern __imp_MQSec_GetWorldSid:PANYARGS
MQSec_GetWorldSid TEXTEQU <__imp_MQSec_GetWorldSid>
extern __imp_MQSec_IsAnonymusSid:PANYARGS
MQSec_IsAnonymusSid TEXTEQU <__imp_MQSec_IsAnonymusSid>
extern __imp_MQSec_IsDC:PANYARGS
MQSec_IsDC TEXTEQU <__imp_MQSec_IsDC>
extern __imp_MQSec_IsGuestSid:PANYARGS
MQSec_IsGuestSid TEXTEQU <__imp_MQSec_IsGuestSid>
extern __imp_MQSec_IsNetworkServiceSid:PANYARGS
MQSec_IsNetworkServiceSid TEXTEQU <__imp_MQSec_IsNetworkServiceSid>
extern __imp_MQSec_IsSystemSid:PANYARGS
MQSec_IsSystemSid TEXTEQU <__imp_MQSec_IsSystemSid>
extern __imp_MQSec_IsUnAuthenticatedUser:PANYARGS
MQSec_IsUnAuthenticatedUser TEXTEQU <__imp_MQSec_IsUnAuthenticatedUser>
extern __imp_MQSec_MakeAbsoluteSD:PANYARGS
MQSec_MakeAbsoluteSD TEXTEQU <__imp_MQSec_MakeAbsoluteSD>
extern __imp_MQSec_MakeSelfRelative:PANYARGS
MQSec_MakeSelfRelative TEXTEQU <__imp_MQSec_MakeSelfRelative>
extern __imp_MQSec_MergeSecurityDescriptors:PANYARGS
MQSec_MergeSecurityDescriptors TEXTEQU <__imp_MQSec_MergeSecurityDescriptors>
extern __imp_MQSec_PackPublicKey:PANYARGS
MQSec_PackPublicKey TEXTEQU <__imp_MQSec_PackPublicKey>
extern __imp_MQSec_RpcAuthnLevel:PANYARGS
MQSec_RpcAuthnLevel TEXTEQU <__imp_MQSec_RpcAuthnLevel>
extern __imp_MQSec_SetLocalRpcMutualAuth:PANYARGS
MQSec_SetLocalRpcMutualAuth TEXTEQU <__imp_MQSec_SetLocalRpcMutualAuth>
extern __imp_MQSec_SetPrivilegeInThread:PANYARGS
MQSec_SetPrivilegeInThread TEXTEQU <__imp_MQSec_SetPrivilegeInThread>
extern __imp_MQSec_SetSecurityDescriptorDacl:PANYARGS
MQSec_SetSecurityDescriptorDacl TEXTEQU <__imp_MQSec_SetSecurityDescriptorDacl>
extern __imp_MQSec_StorePubKeys:PANYARGS
MQSec_StorePubKeys TEXTEQU <__imp_MQSec_StorePubKeys>
extern __imp_MQSec_StorePubKeysInDS:PANYARGS
MQSec_StorePubKeysInDS TEXTEQU <__imp_MQSec_StorePubKeysInDS>
extern __imp_MQSec_TraceThreadTokenInfo:PANYARGS
MQSec_TraceThreadTokenInfo TEXTEQU <__imp_MQSec_TraceThreadTokenInfo>
extern __imp_MQSec_UnpackPublicKey:PANYARGS
MQSec_UnpackPublicKey TEXTEQU <__imp_MQSec_UnpackPublicKey>
extern __imp_MQSec_UpdateLocalMachineSid:PANYARGS
MQSec_UpdateLocalMachineSid TEXTEQU <__imp_MQSec_UpdateLocalMachineSid>
extern __imp_?MQSetCaConfig@@YAJKPEAVMQ_CA_CONFIG@@@Z:PANYARGS
?MQSetCaConfig@@YAJKPEAVMQ_CA_CONFIG@@@Z TEXTEQU <__imp_?MQSetCaConfig@@YAJKPEAVMQ_CA_CONFIG@@@Z>
extern __imp_MQSigHashMessageProperties:PANYARGS
MQSigHashMessageProperties TEXTEQU <__imp_MQSigHashMessageProperties>
extern __imp_MQUInitGlobalScurityVars:PANYARGS
MQUInitGlobalScurityVars TEXTEQU <__imp_MQUInitGlobalScurityVars>
extern __imp_MQsspi_InitServerAuthntication:PANYARGS
MQsspi_InitServerAuthntication TEXTEQU <__imp_MQsspi_InitServerAuthntication>
extern __imp_?ProcessEvents@CCancelRpc@@AEAAXXZ:PANYARGS
?ProcessEvents@CCancelRpc@@AEAAXXZ TEXTEQU <__imp_?ProcessEvents@CCancelRpc@@AEAAXXZ>
extern __imp_?ProduceRPCErrorTracing@@YAXPEAGK@Z:PANYARGS
?ProduceRPCErrorTracing@@YAXPEAGK@Z TEXTEQU <__imp_?ProduceRPCErrorTracing@@YAXPEAGK@Z>
extern __imp_?Relation@CPropertyRestriction@@QEAAKXZ:PANYARGS
?Relation@CPropertyRestriction@@QEAAKXZ TEXTEQU <__imp_?Relation@CPropertyRestriction@@QEAAKXZ>
extern __imp_?Remove@CCancelRpc@@QEAAXPEAX@Z:PANYARGS
?Remove@CCancelRpc@@QEAAXPEAX@Z TEXTEQU <__imp_?Remove@CCancelRpc@@QEAAXPEAX@Z>
extern __imp_?Remove@CColumns@@QEAAXI@Z:PANYARGS
?Remove@CColumns@@QEAAXI@Z TEXTEQU <__imp_?Remove@CColumns@@QEAAXI@Z>
extern __imp_?Remove@CSort@@QEAAXI@Z:PANYARGS
?Remove@CSort@@QEAAXI@Z TEXTEQU <__imp_?Remove@CSort@@QEAAXI@Z>
extern __imp_?Report@@3VCOutputReport@@A:PANYARGS
?Report@@3VCOutputReport@@  TEXTEQU <__imp_?Report@@3VCOutputReport@@A>
extern __imp_?RpcCancelTimeout@CCancelRpc@@QEAAKXZ:PANYARGS
?RpcCancelTimeout@CCancelRpc@@QEAAKXZ TEXTEQU <__imp_?RpcCancelTimeout@CCancelRpc@@QEAAKXZ>
extern __imp_?Serialize@CDSBaseUpdate@@QEAAJPEAEPEAKH@Z:PANYARGS
?Serialize@CDSBaseUpdate@@QEAAJPEAEPEAKH@Z TEXTEQU <__imp_?Serialize@CDSBaseUpdate@@QEAAJPEAEPEAKH@Z>
extern __imp_?SerializeProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAEPEAK@Z:PANYARGS
?SerializeProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAEPEAK@Z TEXTEQU <__imp_?SerializeProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAEPEAK@Z>
extern __imp_ServerAcceptSecCtx:PANYARGS
ServerAcceptSecCtx TEXTEQU <__imp_ServerAcceptSecCtx>
extern __imp_?SetChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@I@Z:PANYARGS
?SetChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@I@Z TEXTEQU <__imp_?SetChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@I@Z>
extern __imp_SetFalconKeyValue:PANYARGS
SetFalconKeyValue TEXTEQU <__imp_SetFalconKeyValue>
extern __imp_SetFalconServiceName:PANYARGS
SetFalconServiceName TEXTEQU <__imp_SetFalconServiceName>
extern __imp_?SetOrder@CSortKey@@QEAAXAEBK@Z:PANYARGS
?SetOrder@CSortKey@@QEAAXAEBK@Z TEXTEQU <__imp_?SetOrder@CSortKey@@QEAAXAEBK@Z>
extern __imp_?SetPrevSeqNum@CDSBaseUpdate@@QEAAXAEAVCSeqNum@@@Z:PANYARGS
?SetPrevSeqNum@CDSBaseUpdate@@QEAAXAEAVCSeqNum@@@Z TEXTEQU <__imp_?SetPrevSeqNum@CDSBaseUpdate@@QEAAXAEAVCSeqNum@@@Z>
extern __imp_?SetProperty@CPropertyRestriction@@QEAAXAEBK@Z:PANYARGS
?SetProperty@CPropertyRestriction@@QEAAXAEBK@Z TEXTEQU <__imp_?SetProperty@CPropertyRestriction@@QEAAXAEBK@Z>
extern __imp_?SetProperty@CSortKey@@QEAAXAEBK@Z:PANYARGS
?SetProperty@CSortKey@@QEAAXAEBK@Z TEXTEQU <__imp_?SetProperty@CSortKey@@QEAAXAEBK@Z>
extern __imp_?SetRelation@CPropertyRestriction@@QEAAXK@Z:PANYARGS
?SetRelation@CPropertyRestriction@@QEAAXK@Z TEXTEQU <__imp_?SetRelation@CPropertyRestriction@@QEAAXK@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXAEBVCMQVariant@@@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXAEBVCMQVariant@@@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXAEBVCMQVariant@@@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXE@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXE@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXE@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXF@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXF@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXF@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXJ@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXJ@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXJ@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXK@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXK@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXK@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXPEAG@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCACLSID@@@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXPEAUtagCACLSID@@@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCACLSID@@@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCALPWSTR@@@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXPEAUtagCALPWSTR@@@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCALPWSTR@@@Z>
extern __imp_?ShutDownCancelThread@CCancelRpc@@QEAAXXZ:PANYARGS
?ShutDownCancelThread@CCancelRpc@@QEAAXXZ TEXTEQU <__imp_?ShutDownCancelThread@CCancelRpc@@QEAAXXZ>
extern __imp_ShutDownDebugWindow:PANYARGS
ShutDownDebugWindow TEXTEQU <__imp_ShutDownDebugWindow>
extern __imp_?UnalignedWcslen@@YA_KPEFBG@Z:PANYARGS
?UnalignedWcslen@@YA_KPEFBG@Z TEXTEQU <__imp_?UnalignedWcslen@@YA_KPEFBG@Z>
extern __imp_?Value@CPropertyRestriction@@QEAAAEBVCMQVariant@@XZ:PANYARGS
?Value@CPropertyRestriction@@QEAAAEBVCMQVariant@@XZ TEXTEQU <__imp_?Value@CPropertyRestriction@@QEAAAEBVCMQVariant@@XZ>
extern __imp_?XactGetDTC@@YAJPEAPEAUIUnknown@@@Z:PANYARGS
?XactGetDTC@@YAJPEAPEAUIUnknown@@@Z TEXTEQU <__imp_?XactGetDTC@@YAJPEAPEAUIUnknown@@@Z>
extern __imp_?XactGetWhereabouts@@YAJPEAKPEAE@Z:PANYARGS
?XactGetWhereabouts@@YAJPEAKPEAE@Z TEXTEQU <__imp_?XactGetWhereabouts@@YAJPEAKPEAE@Z>
extern __imp_?g_CancelRpc@@3VCCancelRpc@@A:PANYARGS
?g_CancelRpc@@3VCCancelRpc@@  TEXTEQU <__imp_?g_CancelRpc@@3VCCancelRpc@@A>
extern __imp_?g_hProvVer@@3VCHCryptProv@@A:PANYARGS
?g_hProvVer@@3VCHCryptProv@@  TEXTEQU <__imp_?g_hProvVer@@3VCHCryptProv@@A>
extern __imp_?getNumOfProps@CDSBaseUpdate@@QEAAEXZ:PANYARGS
?getNumOfProps@CDSBaseUpdate@@QEAAEXZ TEXTEQU <__imp_?getNumOfProps@CDSBaseUpdate@@QEAAEXZ>
extern __imp_?mqrpcBindQMService@@YAJPEAG0PEAKPEAPEAXW4PORTTYPE@@P6AKPEAXK@ZK@Z:PANYARGS
?mqrpcBindQMService@@YAJPEAG0PEAKPEAPEAXW4PORTTYPE@@P6AKPEAXK@ZK@Z TEXTEQU <__imp_?mqrpcBindQMService@@YAJPEAG0PEAKPEAPEAXW4PORTTYPE@@P6AKPEAXK@ZK@Z>
extern __imp_?mqrpcGetLocalCallPID@@YAKPEAX@Z:PANYARGS
?mqrpcGetLocalCallPID@@YAKPEAX@Z TEXTEQU <__imp_?mqrpcGetLocalCallPID@@YAKPEAX@Z>
extern __imp_?mqrpcIsLocalCall@@YAHPEAX@Z:PANYARGS
?mqrpcIsLocalCall@@YAHPEAX@Z TEXTEQU <__imp_?mqrpcIsLocalCall@@YAHPEAX@Z>
extern __imp_?mqrpcIsTcpipTransport@@YAHPEAX@Z:PANYARGS
?mqrpcIsTcpipTransport@@YAHPEAX@Z TEXTEQU <__imp_?mqrpcIsTcpipTransport@@YAHPEAX@Z>
extern __imp_?mqrpcUnbindQMService@@YAJPEAPEAXPEAPEAG@Z:PANYARGS
?mqrpcUnbindQMService@@YAJPEAPEAXPEAPEAG@Z TEXTEQU <__imp_?mqrpcUnbindQMService@@YAJPEAPEAXPEAPEAG@Z>
extern __imp_MQSigCloneCertFromReg:PANYARGS
MQSigCloneCertFromReg TEXTEQU <__imp_MQSigCloneCertFromReg>
extern __imp_MQSigCloneCertFromSysStore:PANYARGS
MQSigCloneCertFromSysStore TEXTEQU <__imp_MQSigCloneCertFromSysStore>
extern __imp_MQSigCreateCertificate:PANYARGS
MQSigCreateCertificate TEXTEQU <__imp_MQSigCreateCertificate>
extern __imp_MQSigOpenUserCertStore:PANYARGS
MQSigOpenUserCertStore TEXTEQU <__imp_MQSigOpenUserCertStore>
extern __imp_MSMQGetOperatingSystem:PANYARGS
MSMQGetOperatingSystem TEXTEQU <__imp_MSMQGetOperatingSystem>
