extern __imp_acmDriverAddA:PANYARGS
acmDriverAdd  TEXTEQU <__imp_acmDriverAddA>
extern __imp_acmDriverAddW:PANYARGS
acmDriverAddW TEXTEQU <__imp_acmDriverAddW>
extern __imp_acmDriverClose:PANYARGS
acmDriverClose TEXTEQU <__imp_acmDriverClose>
extern __imp_acmDriverDetailsA:PANYARGS
acmDriverDetails  TEXTEQU <__imp_acmDriverDetailsA>
extern __imp_acmDriverDetailsW:PANYARGS
acmDriverDetailsW TEXTEQU <__imp_acmDriverDetailsW>
extern __imp_acmDriverEnum:PANYARGS
acmDriverEnum TEXTEQU <__imp_acmDriverEnum>
extern __imp_acmDriverID:PANYARGS
acmDriverID TEXTEQU <__imp_acmDriverID>
extern __imp_acmDriverMessage:PANYARGS
acmDriverMessage TEXTEQU <__imp_acmDriverMessage>
extern __imp_acmDriverOpen:PANYARGS
acmDriverOpen TEXTEQU <__imp_acmDriverOpen>
extern __imp_acmDriverPriority:PANYARGS
acmDriverPriority TEXTEQU <__imp_acmDriverPriority>
extern __imp_acmDriverRemove:PANYARGS
acmDriverRemove TEXTEQU <__imp_acmDriverRemove>
extern __imp_acmFilterChooseA:PANYARGS
acmFilterChoose  TEXTEQU <__imp_acmFilterChooseA>
extern __imp_acmFilterChooseW:PANYARGS
acmFilterChooseW TEXTEQU <__imp_acmFilterChooseW>
extern __imp_acmFilterDetailsA:PANYARGS
acmFilterDetails  TEXTEQU <__imp_acmFilterDetailsA>
extern __imp_acmFilterDetailsW:PANYARGS
acmFilterDetailsW TEXTEQU <__imp_acmFilterDetailsW>
extern __imp_acmFilterEnumA:PANYARGS
acmFilterEnum  TEXTEQU <__imp_acmFilterEnumA>
extern __imp_acmFilterEnumW:PANYARGS
acmFilterEnumW TEXTEQU <__imp_acmFilterEnumW>
extern __imp_acmFilterTagDetailsA:PANYARGS
acmFilterTagDetails  TEXTEQU <__imp_acmFilterTagDetailsA>
extern __imp_acmFilterTagDetailsW:PANYARGS
acmFilterTagDetailsW TEXTEQU <__imp_acmFilterTagDetailsW>
extern __imp_acmFilterTagEnumA:PANYARGS
acmFilterTagEnum  TEXTEQU <__imp_acmFilterTagEnumA>
extern __imp_acmFilterTagEnumW:PANYARGS
acmFilterTagEnumW TEXTEQU <__imp_acmFilterTagEnumW>
extern __imp_acmFormatChooseA:PANYARGS
acmFormatChoose  TEXTEQU <__imp_acmFormatChooseA>
extern __imp_acmFormatChooseW:PANYARGS
acmFormatChooseW TEXTEQU <__imp_acmFormatChooseW>
extern __imp_acmFormatDetailsA:PANYARGS
acmFormatDetails  TEXTEQU <__imp_acmFormatDetailsA>
extern __imp_acmFormatDetailsW:PANYARGS
acmFormatDetailsW TEXTEQU <__imp_acmFormatDetailsW>
extern __imp_acmFormatEnumA:PANYARGS
acmFormatEnum  TEXTEQU <__imp_acmFormatEnumA>
extern __imp_acmFormatEnumW:PANYARGS
acmFormatEnumW TEXTEQU <__imp_acmFormatEnumW>
extern __imp_acmFormatSuggest:PANYARGS
acmFormatSuggest TEXTEQU <__imp_acmFormatSuggest>
extern __imp_acmFormatTagDetailsA:PANYARGS
acmFormatTagDetails  TEXTEQU <__imp_acmFormatTagDetailsA>
extern __imp_acmFormatTagDetailsW:PANYARGS
acmFormatTagDetailsW TEXTEQU <__imp_acmFormatTagDetailsW>
extern __imp_acmFormatTagEnumA:PANYARGS
acmFormatTagEnum  TEXTEQU <__imp_acmFormatTagEnumA>
extern __imp_acmFormatTagEnumW:PANYARGS
acmFormatTagEnumW TEXTEQU <__imp_acmFormatTagEnumW>
extern __imp_acmGetVersion:PANYARGS
acmGetVersion TEXTEQU <__imp_acmGetVersion>
extern __imp_acmMetrics:PANYARGS
acmMetrics TEXTEQU <__imp_acmMetrics>
extern __imp_acmStreamClose:PANYARGS
acmStreamClose TEXTEQU <__imp_acmStreamClose>
extern __imp_acmStreamConvert:PANYARGS
acmStreamConvert TEXTEQU <__imp_acmStreamConvert>
extern __imp_acmStreamMessage:PANYARGS
acmStreamMessage TEXTEQU <__imp_acmStreamMessage>
extern __imp_acmStreamOpen:PANYARGS
acmStreamOpen TEXTEQU <__imp_acmStreamOpen>
extern __imp_acmStreamPrepareHeader:PANYARGS
acmStreamPrepareHeader TEXTEQU <__imp_acmStreamPrepareHeader>
extern __imp_acmStreamReset:PANYARGS
acmStreamReset TEXTEQU <__imp_acmStreamReset>
extern __imp_acmStreamSize:PANYARGS
acmStreamSize TEXTEQU <__imp_acmStreamSize>
extern __imp_acmStreamUnprepareHeader:PANYARGS
acmStreamUnprepareHeader TEXTEQU <__imp_acmStreamUnprepareHeader>
