extern __imp_InitErrors:PANYARGS
InitErrors TEXTEQU <__imp_InitErrors>
extern __imp_PostError:PANYARGS
PostError TEXTEQU <__imp_PostError>
extern __imp_InitSSAutoEnterThread:PANYARGS
InitSSAutoEnterThread TEXTEQU <__imp_InitSSAutoEnterThread>
extern __imp_UpdateError:PANYARGS
UpdateError TEXTEQU <__imp_UpdateError>
extern __imp_CloseCtrs:PANYARGS
CloseCtrs TEXTEQU <__imp_CloseCtrs>
extern __imp_LoadStringRC:PANYARGS
LoadStringRC TEXTEQU <__imp_LoadStringRC>
extern __imp_ReOpenMetaDataWithMemory:PANYARGS
ReOpenMetaDataWithMemory TEXTEQU <__imp_ReOpenMetaDataWithMemory>
extern __imp_CollectCtrs:PANYARGS
CollectCtrs TEXTEQU <__imp_CollectCtrs>
extern __imp_CorDllMainWorker:PANYARGS
CorDllMainWorker TEXTEQU <__imp_CorDllMainWorker>
extern __imp_EEDllGetClassObjectFromClass:PANYARGS
EEDllGetClassObjectFromClass TEXTEQU <__imp_EEDllGetClassObjectFromClass>
extern __imp_GetPrivateContextsPerfCounters:PANYARGS
GetPrivateContextsPerfCounters TEXTEQU <__imp_GetPrivateContextsPerfCounters>
extern __imp_GetProcessExecutableHeap:PANYARGS
GetProcessExecutableHeap TEXTEQU <__imp_GetProcessExecutableHeap>
extern __imp_GetStartupFlags:PANYARGS
GetStartupFlags TEXTEQU <__imp_GetStartupFlags>
extern __imp_GetTargetForVTableEntry:PANYARGS
GetTargetForVTableEntry TEXTEQU <__imp_GetTargetForVTableEntry>
extern __imp_GetTokenForVTableEntry:PANYARGS
GetTokenForVTableEntry TEXTEQU <__imp_GetTokenForVTableEntry>
extern __imp_LogHelp_LogAssert:PANYARGS
LogHelp_LogAssert TEXTEQU <__imp_LogHelp_LogAssert>
extern __imp_LogHelp_NoGuiOnAssert:PANYARGS
LogHelp_NoGuiOnAssert TEXTEQU <__imp_LogHelp_NoGuiOnAssert>
extern __imp_LogHelp_TerminateOnAssert:PANYARGS
LogHelp_TerminateOnAssert TEXTEQU <__imp_LogHelp_TerminateOnAssert>
extern __imp_OpenCtrs:PANYARGS
OpenCtrs TEXTEQU <__imp_OpenCtrs>
extern __imp_SetTargetForVTableEntry:PANYARGS
SetTargetForVTableEntry TEXTEQU <__imp_SetTargetForVTableEntry>
extern __imp_CallFunctionShim:PANYARGS
CallFunctionShim TEXTEQU <__imp_CallFunctionShim>
extern __imp_ClrCreateManagedInstance:PANYARGS
ClrCreateManagedInstance TEXTEQU <__imp_ClrCreateManagedInstance>
extern __imp_CoEEShutDownCOM:PANYARGS
CoEEShutDownCOM TEXTEQU <__imp_CoEEShutDownCOM>
extern __imp_CoInitializeCor:PANYARGS
CoInitializeCor TEXTEQU <__imp_CoInitializeCor>
extern __imp_CoInitializeEE:PANYARGS
CoInitializeEE TEXTEQU <__imp_CoInitializeEE>
extern __imp_CoUninitializeCor:PANYARGS
CoUninitializeCor TEXTEQU <__imp_CoUninitializeCor>
extern __imp_CoUninitializeEE:PANYARGS
CoUninitializeEE TEXTEQU <__imp_CoUninitializeEE>
extern __imp_CorBindToCurrentRuntime:PANYARGS
CorBindToCurrentRuntime TEXTEQU <__imp_CorBindToCurrentRuntime>
extern __imp_CorBindToRuntime:PANYARGS
CorBindToRuntime TEXTEQU <__imp_CorBindToRuntime>
extern __imp_CorBindToRuntimeByCfg:PANYARGS
CorBindToRuntimeByCfg TEXTEQU <__imp_CorBindToRuntimeByCfg>
extern __imp_CorBindToRuntimeByPath:PANYARGS
CorBindToRuntimeByPath TEXTEQU <__imp_CorBindToRuntimeByPath>
extern __imp_CorBindToRuntimeByPathEx:PANYARGS
CorBindToRuntimeByPathEx TEXTEQU <__imp_CorBindToRuntimeByPathEx>
extern __imp_CorBindToRuntimeEx:PANYARGS
CorBindToRuntimeEx TEXTEQU <__imp_CorBindToRuntimeEx>
extern __imp_CorBindToRuntimeHost:PANYARGS
CorBindToRuntimeHost TEXTEQU <__imp_CorBindToRuntimeHost>
extern __imp_CorExitProcess:PANYARGS
CorExitProcess TEXTEQU <__imp_CorExitProcess>
extern __imp_CorGetSvc:PANYARGS
CorGetSvc TEXTEQU <__imp_CorGetSvc>
extern __imp_CorIsLatestSvc:PANYARGS
CorIsLatestSvc TEXTEQU <__imp_CorIsLatestSvc>
extern __imp_CorMarkThreadInThreadPool:PANYARGS
CorMarkThreadInThreadPool TEXTEQU <__imp_CorMarkThreadInThreadPool>
extern __imp_CorTickleSvc:PANYARGS
CorTickleSvc TEXTEQU <__imp_CorTickleSvc>
extern __imp_CreateConfigStream:PANYARGS
CreateConfigStream TEXTEQU <__imp_CreateConfigStream>
extern __imp_CreateDebuggingInterfaceFromVersion:PANYARGS
CreateDebuggingInterfaceFromVersion TEXTEQU <__imp_CreateDebuggingInterfaceFromVersion>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_EEDllRegisterServer:PANYARGS
EEDllRegisterServer TEXTEQU <__imp_EEDllRegisterServer>
extern __imp_EEDllUnregisterServer:PANYARGS
EEDllUnregisterServer TEXTEQU <__imp_EEDllUnregisterServer>
extern __imp_GetAssemblyMDImport:PANYARGS
GetAssemblyMDImport TEXTEQU <__imp_GetAssemblyMDImport>
extern __imp_GetCORRequiredVersion:PANYARGS
GetCORRequiredVersion TEXTEQU <__imp_GetCORRequiredVersion>
extern __imp_GetCORRootDirectory:PANYARGS
GetCORRootDirectory TEXTEQU <__imp_GetCORRootDirectory>
extern __imp_GetCORSystemDirectory:PANYARGS
GetCORSystemDirectory TEXTEQU <__imp_GetCORSystemDirectory>
extern __imp_GetCORVersion:PANYARGS
GetCORVersion TEXTEQU <__imp_GetCORVersion>
extern __imp_GetCompileInfo:PANYARGS
GetCompileInfo TEXTEQU <__imp_GetCompileInfo>
extern __imp_GetFileVersion:PANYARGS
GetFileVersion TEXTEQU <__imp_GetFileVersion>
extern __imp_GetHashFromAssemblyFile:PANYARGS
GetHashFromAssemblyFile TEXTEQU <__imp_GetHashFromAssemblyFile>
extern __imp_GetHashFromAssemblyFileW:PANYARGS
GetHashFromAssemblyFileW TEXTEQU <__imp_GetHashFromAssemblyFileW>
extern __imp_GetHashFromBlob:PANYARGS
GetHashFromBlob TEXTEQU <__imp_GetHashFromBlob>
extern __imp_GetHashFromFile:PANYARGS
GetHashFromFile TEXTEQU <__imp_GetHashFromFile>
extern __imp_GetHashFromFileW:PANYARGS
GetHashFromFileW TEXTEQU <__imp_GetHashFromFileW>
extern __imp_GetHashFromHandle:PANYARGS
GetHashFromHandle TEXTEQU <__imp_GetHashFromHandle>
extern __imp_GetHostConfigurationFile:PANYARGS
GetHostConfigurationFile TEXTEQU <__imp_GetHostConfigurationFile>
extern __imp_GetMetaDataInternalInterface:PANYARGS
GetMetaDataInternalInterface TEXTEQU <__imp_GetMetaDataInternalInterface>
extern __imp_GetMetaDataInternalInterfaceFromPublic:PANYARGS
GetMetaDataInternalInterfaceFromPublic TEXTEQU <__imp_GetMetaDataInternalInterfaceFromPublic>
extern __imp_GetMetaDataPublicInterfaceFromInternal:PANYARGS
GetMetaDataPublicInterfaceFromInternal TEXTEQU <__imp_GetMetaDataPublicInterfaceFromInternal>
extern __imp_GetPermissionRequests:PANYARGS
GetPermissionRequests TEXTEQU <__imp_GetPermissionRequests>
extern __imp_GetRealProcAddress:PANYARGS
GetRealProcAddress TEXTEQU <__imp_GetRealProcAddress>
extern __imp_GetRequestedRuntimeInfo:PANYARGS
GetRequestedRuntimeInfo TEXTEQU <__imp_GetRequestedRuntimeInfo>
extern __imp_GetRequestedRuntimeVersion:PANYARGS
GetRequestedRuntimeVersion TEXTEQU <__imp_GetRequestedRuntimeVersion>
extern __imp_GetRequestedRuntimeVersionForCLSID:PANYARGS
GetRequestedRuntimeVersionForCLSID TEXTEQU <__imp_GetRequestedRuntimeVersionForCLSID>
extern __imp_GetVersionFromProcess:PANYARGS
GetVersionFromProcess TEXTEQU <__imp_GetVersionFromProcess>
extern __imp_GetXMLElement:PANYARGS
GetXMLElement TEXTEQU <__imp_GetXMLElement>
extern __imp_GetXMLElementAttribute:PANYARGS
GetXMLElementAttribute TEXTEQU <__imp_GetXMLElementAttribute>
extern __imp_GetXMLObject:PANYARGS
GetXMLObject TEXTEQU <__imp_GetXMLObject>
extern __imp_IEE:PANYARGS
IEE TEXTEQU <__imp_IEE>
extern __imp_LoadLibraryShim:PANYARGS
LoadLibraryShim TEXTEQU <__imp_LoadLibraryShim>
extern __imp_LoadLibraryWithPolicyShim:PANYARGS
LoadLibraryWithPolicyShim TEXTEQU <__imp_LoadLibraryWithPolicyShim>
extern __imp_LoadStringRCEx:PANYARGS
LoadStringRCEx TEXTEQU <__imp_LoadStringRCEx>
extern __imp_LockClrVersion:PANYARGS
LockClrVersion TEXTEQU <__imp_LockClrVersion>
extern __imp_MetaDataGetDispenser:PANYARGS
MetaDataGetDispenser TEXTEQU <__imp_MetaDataGetDispenser>
extern __imp_ND_CopyObjDst:PANYARGS
ND_CopyObjDst TEXTEQU <__imp_ND_CopyObjDst>
extern __imp_ND_CopyObjSrc:PANYARGS
ND_CopyObjSrc TEXTEQU <__imp_ND_CopyObjSrc>
extern __imp_ND_RI2:PANYARGS
ND_RI2 TEXTEQU <__imp_ND_RI2>
extern __imp_ND_RI4:PANYARGS
ND_RI4 TEXTEQU <__imp_ND_RI4>
extern __imp_ND_RI8:PANYARGS
ND_RI8 TEXTEQU <__imp_ND_RI8>
extern __imp_ND_RU1:PANYARGS
ND_RU1 TEXTEQU <__imp_ND_RU1>
extern __imp_ND_WI2:PANYARGS
ND_WI2 TEXTEQU <__imp_ND_WI2>
extern __imp_ND_WI4:PANYARGS
ND_WI4 TEXTEQU <__imp_ND_WI4>
extern __imp_ND_WI8:PANYARGS
ND_WI8 TEXTEQU <__imp_ND_WI8>
extern __imp_ND_WU1:PANYARGS
ND_WU1 TEXTEQU <__imp_ND_WU1>
extern __imp_ReOpenMetaDataWithMemoryEx:PANYARGS
ReOpenMetaDataWithMemoryEx TEXTEQU <__imp_ReOpenMetaDataWithMemoryEx>
extern __imp_RunDll32ShimW:PANYARGS
RunDll32ShimW TEXTEQU <__imp_RunDll32ShimW>
extern __imp_RuntimeOSHandle:PANYARGS
RuntimeOSHandle TEXTEQU <__imp_RuntimeOSHandle>
extern __imp_RuntimeOpenImage:PANYARGS
RuntimeOpenImage TEXTEQU <__imp_RuntimeOpenImage>
extern __imp_RuntimeReleaseHandle:PANYARGS
RuntimeReleaseHandle TEXTEQU <__imp_RuntimeReleaseHandle>
extern __imp_StrongNameCompareAssemblies:PANYARGS
StrongNameCompareAssemblies TEXTEQU <__imp_StrongNameCompareAssemblies>
extern __imp_StrongNameErrorInfo:PANYARGS
StrongNameErrorInfo TEXTEQU <__imp_StrongNameErrorInfo>
extern __imp_StrongNameFreeBuffer:PANYARGS
StrongNameFreeBuffer TEXTEQU <__imp_StrongNameFreeBuffer>
extern __imp_StrongNameGetBlob:PANYARGS
StrongNameGetBlob TEXTEQU <__imp_StrongNameGetBlob>
extern __imp_StrongNameGetBlobFromImage:PANYARGS
StrongNameGetBlobFromImage TEXTEQU <__imp_StrongNameGetBlobFromImage>
extern __imp_StrongNameGetPublicKey:PANYARGS
StrongNameGetPublicKey TEXTEQU <__imp_StrongNameGetPublicKey>
extern __imp_StrongNameHashSize:PANYARGS
StrongNameHashSize TEXTEQU <__imp_StrongNameHashSize>
extern __imp_StrongNameKeyDelete:PANYARGS
StrongNameKeyDelete TEXTEQU <__imp_StrongNameKeyDelete>
extern __imp_StrongNameKeyGen:PANYARGS
StrongNameKeyGen TEXTEQU <__imp_StrongNameKeyGen>
extern __imp_StrongNameKeyGenEx:PANYARGS
StrongNameKeyGenEx TEXTEQU <__imp_StrongNameKeyGenEx>
extern __imp_StrongNameKeyInstall:PANYARGS
StrongNameKeyInstall TEXTEQU <__imp_StrongNameKeyInstall>
extern __imp_StrongNameSignatureGeneration:PANYARGS
StrongNameSignatureGeneration TEXTEQU <__imp_StrongNameSignatureGeneration>
extern __imp_StrongNameSignatureGenerationEx:PANYARGS
StrongNameSignatureGenerationEx TEXTEQU <__imp_StrongNameSignatureGenerationEx>
extern __imp_StrongNameSignatureSize:PANYARGS
StrongNameSignatureSize TEXTEQU <__imp_StrongNameSignatureSize>
extern __imp_StrongNameSignatureVerification:PANYARGS
StrongNameSignatureVerification TEXTEQU <__imp_StrongNameSignatureVerification>
extern __imp_StrongNameSignatureVerificationEx:PANYARGS
StrongNameSignatureVerificationEx TEXTEQU <__imp_StrongNameSignatureVerificationEx>
extern __imp_StrongNameSignatureVerificationFromImage:PANYARGS
StrongNameSignatureVerificationFromImage TEXTEQU <__imp_StrongNameSignatureVerificationFromImage>
extern __imp_StrongNameTokenFromAssembly:PANYARGS
StrongNameTokenFromAssembly TEXTEQU <__imp_StrongNameTokenFromAssembly>
extern __imp_StrongNameTokenFromAssemblyEx:PANYARGS
StrongNameTokenFromAssemblyEx TEXTEQU <__imp_StrongNameTokenFromAssemblyEx>
extern __imp_StrongNameTokenFromPublicKey:PANYARGS
StrongNameTokenFromPublicKey TEXTEQU <__imp_StrongNameTokenFromPublicKey>
extern __imp_TranslateSecurityAttributes:PANYARGS
TranslateSecurityAttributes TEXTEQU <__imp_TranslateSecurityAttributes>
extern __imp__CorDllMain:PANYARGS
_CorDllMain TEXTEQU <__imp__CorDllMain>
extern __imp__CorExeMain:PANYARGS
_CorExeMain TEXTEQU <__imp__CorExeMain>
extern __imp__CorExeMain2:PANYARGS
_CorExeMain2 TEXTEQU <__imp__CorExeMain2>
extern __imp__CorImageUnloading:PANYARGS
_CorImageUnloading TEXTEQU <__imp__CorImageUnloading>
extern __imp__CorValidateImage:PANYARGS
_CorValidateImage TEXTEQU <__imp__CorValidateImage>
