extern __imp_??0CCritSec@@QEAA@XZ:PANYARGS
??0CCritSec@@QEAA@XZ TEXTEQU <__imp_??0CCritSec@@QEAA@XZ>
extern __imp_??0CDoubleList@@QEAA@XZ:PANYARGS
??0CDoubleList@@QEAA@XZ TEXTEQU <__imp_??0CDoubleList@@QEAA@XZ>
extern __imp_??0CEXAutoBackupFile@@QEAA@PEBG@Z:PANYARGS
??0CEXAutoBackupFile@@QEAA@PEBG@Z TEXTEQU <__imp_??0CEXAutoBackupFile@@QEAA@PEBG@Z>
extern __imp_??0CEXAutoBackupFile@@QEAA@XZ:PANYARGS
??0CEXAutoBackupFile@@QEAA@XZ TEXTEQU <__imp_??0CEXAutoBackupFile@@QEAA@XZ>
extern __imp_??0CExFileOperation@@QEAA@XZ:PANYARGS
??0CExFileOperation@@QEAA@XZ TEXTEQU <__imp_??0CExFileOperation@@QEAA@XZ>
extern __imp_??0CFakeLock@@QEAA@XZ:PANYARGS
??0CFakeLock@@QEAA@XZ TEXTEQU <__imp_??0CFakeLock@@QEAA@XZ>
extern __imp_??0CLKRHashTable@@AEAA@AEBV0@@Z:PANYARGS
??0CLKRHashTable@@AEAA@AEBV0@@Z TEXTEQU <__imp_??0CLKRHashTable@@AEAA@AEBV0@@Z>
extern __imp_??0CLKRHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z:PANYARGS
??0CLKRHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z TEXTEQU <__imp_??0CLKRHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z>
extern __imp_??0CLKRHashTableStats@@QEAA@XZ:PANYARGS
??0CLKRHashTableStats@@QEAA@XZ TEXTEQU <__imp_??0CLKRHashTableStats@@QEAA@XZ>
extern __imp_??0CLKRLinearHashTable@@AEAA@AEBV0@@Z:PANYARGS
??0CLKRLinearHashTable@@AEAA@AEBV0@@Z TEXTEQU <__imp_??0CLKRLinearHashTable@@AEAA@AEBV0@@Z>
extern __imp_??0CLKRLinearHashTable@@AEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAVCLKRHashTable@@@Z:PANYARGS
??0CLKRLinearHashTable@@AEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAVCLKRHashTable@@@Z TEXTEQU <__imp_??0CLKRLinearHashTable@@AEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAVCLKRHashTable@@@Z>
extern __imp_??0CLKRLinearHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z:PANYARGS
??0CLKRLinearHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z TEXTEQU <__imp_??0CLKRLinearHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z>
extern __imp_??0CLockedDoubleList@@QEAA@XZ:PANYARGS
??0CLockedDoubleList@@QEAA@XZ TEXTEQU <__imp_??0CLockedDoubleList@@QEAA@XZ>
extern __imp_??0CLockedSingleList@@QEAA@XZ:PANYARGS
??0CLockedSingleList@@QEAA@XZ TEXTEQU <__imp_??0CLockedSingleList@@QEAA@XZ>
extern __imp_??0CReaderWriterLock2@@QEAA@XZ:PANYARGS
??0CReaderWriterLock2@@QEAA@XZ TEXTEQU <__imp_??0CReaderWriterLock2@@QEAA@XZ>
extern __imp_??0CReaderWriterLock3@@QEAA@XZ:PANYARGS
??0CReaderWriterLock3@@QEAA@XZ TEXTEQU <__imp_??0CReaderWriterLock3@@QEAA@XZ>
extern __imp_??0CReaderWriterLock@@QEAA@XZ:PANYARGS
??0CReaderWriterLock@@QEAA@XZ TEXTEQU <__imp_??0CReaderWriterLock@@QEAA@XZ>
extern __imp_??0CSingleList@@QEAA@XZ:PANYARGS
??0CSingleList@@QEAA@XZ TEXTEQU <__imp_??0CSingleList@@QEAA@XZ>
extern __imp_??0CSmallSpinLock@@QEAA@XZ:PANYARGS
??0CSmallSpinLock@@QEAA@XZ TEXTEQU <__imp_??0CSmallSpinLock@@QEAA@XZ>
extern __imp_??0CSpinLock@@QEAA@XZ:PANYARGS
??0CSpinLock@@QEAA@XZ TEXTEQU <__imp_??0CSpinLock@@QEAA@XZ>
extern __imp_??1CCritSec@@QEAA@XZ:PANYARGS
??1CCritSec@@QEAA@XZ TEXTEQU <__imp_??1CCritSec@@QEAA@XZ>
extern __imp_??1CDoubleList@@QEAA@XZ:PANYARGS
??1CDoubleList@@QEAA@XZ TEXTEQU <__imp_??1CDoubleList@@QEAA@XZ>
extern __imp_??1CEXAutoBackupFile@@QEAA@XZ:PANYARGS
??1CEXAutoBackupFile@@QEAA@XZ TEXTEQU <__imp_??1CEXAutoBackupFile@@QEAA@XZ>
extern __imp_??1CExFileOperation@@QEAA@XZ:PANYARGS
??1CExFileOperation@@QEAA@XZ TEXTEQU <__imp_??1CExFileOperation@@QEAA@XZ>
extern __imp_??1CFakeLock@@QEAA@XZ:PANYARGS
??1CFakeLock@@QEAA@XZ TEXTEQU <__imp_??1CFakeLock@@QEAA@XZ>
extern __imp_??1CLKRHashTable@@QEAA@XZ:PANYARGS
??1CLKRHashTable@@QEAA@XZ TEXTEQU <__imp_??1CLKRHashTable@@QEAA@XZ>
extern __imp_??1CLKRLinearHashTable@@QEAA@XZ:PANYARGS
??1CLKRLinearHashTable@@QEAA@XZ TEXTEQU <__imp_??1CLKRLinearHashTable@@QEAA@XZ>
extern __imp_??1CLockedDoubleList@@QEAA@XZ:PANYARGS
??1CLockedDoubleList@@QEAA@XZ TEXTEQU <__imp_??1CLockedDoubleList@@QEAA@XZ>
extern __imp_??1CLockedSingleList@@QEAA@XZ:PANYARGS
??1CLockedSingleList@@QEAA@XZ TEXTEQU <__imp_??1CLockedSingleList@@QEAA@XZ>
extern __imp_??1CReaderWriterLock2@@QEAA@XZ:PANYARGS
??1CReaderWriterLock2@@QEAA@XZ TEXTEQU <__imp_??1CReaderWriterLock2@@QEAA@XZ>
extern __imp_??1CReaderWriterLock3@@QEAA@XZ:PANYARGS
??1CReaderWriterLock3@@QEAA@XZ TEXTEQU <__imp_??1CReaderWriterLock3@@QEAA@XZ>
extern __imp_??1CReaderWriterLock@@QEAA@XZ:PANYARGS
??1CReaderWriterLock@@QEAA@XZ TEXTEQU <__imp_??1CReaderWriterLock@@QEAA@XZ>
extern __imp_??1CSingleList@@QEAA@XZ:PANYARGS
??1CSingleList@@QEAA@XZ TEXTEQU <__imp_??1CSingleList@@QEAA@XZ>
extern __imp_??1CSmallSpinLock@@QEAA@XZ:PANYARGS
??1CSmallSpinLock@@QEAA@XZ TEXTEQU <__imp_??1CSmallSpinLock@@QEAA@XZ>
extern __imp_??1CSpinLock@@QEAA@XZ:PANYARGS
??1CSpinLock@@QEAA@XZ TEXTEQU <__imp_??1CSpinLock@@QEAA@XZ>
extern __imp_??4?$CLockBase@$00$00$02$00$02$01@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CLockBase@$00$00$02$00$02$01@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CLockBase@$00$00$02$00$02$01@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4?$CLockBase@$01$00$00$00$02$01@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CLockBase@$01$00$00$00$02$01@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CLockBase@$01$00$00$00$02$01@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4?$CLockBase@$02$00$00$00$00$00@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CLockBase@$02$00$00$00$00$00@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CLockBase@$02$00$00$00$00$00@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4?$CLockBase@$03$00$00$01$02$02@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CLockBase@$03$00$00$01$02$02@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CLockBase@$03$00$00$01$02$02@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4?$CLockBase@$04$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CLockBase@$04$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CLockBase@$04$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4?$CLockBase@$05$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CLockBase@$05$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CLockBase@$05$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4?$CLockBase@$06$01$00$00$02$01@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4?$CLockBase@$06$01$00$00$02$01@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4?$CLockBase@$06$01$00$00$02$01@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CCritSec@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CCritSec@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CCritSec@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CDoubleList@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CDoubleList@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CDoubleList@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CEXAutoBackupFile@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CEXAutoBackupFile@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CEXAutoBackupFile@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CExFileOperation@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CExFileOperation@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CExFileOperation@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CFakeLock@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CFakeLock@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CFakeLock@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CLKRHashTable@@AEAAAEAV0@AEBV0@@Z:PANYARGS
??4CLKRHashTable@@AEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CLKRHashTable@@AEAAAEAV0@AEBV0@@Z>
extern __imp_??4CLKRHashTableStats@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CLKRHashTableStats@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CLKRHashTableStats@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CLKRLinearHashTable@@AEAAAEAV0@AEBV0@@Z:PANYARGS
??4CLKRLinearHashTable@@AEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CLKRLinearHashTable@@AEAAAEAV0@AEBV0@@Z>
extern __imp_??4CLockedDoubleList@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CLockedDoubleList@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CLockedDoubleList@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CLockedSingleList@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CLockedSingleList@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CLockedSingleList@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CMdVersionInfo@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CMdVersionInfo@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CMdVersionInfo@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CReaderWriterLock2@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CReaderWriterLock2@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CReaderWriterLock2@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CReaderWriterLock3@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CReaderWriterLock3@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CReaderWriterLock3@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CReaderWriterLock@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CReaderWriterLock@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CReaderWriterLock@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CSingleList@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CSingleList@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CSingleList@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CSmallSpinLock@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CSmallSpinLock@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CSmallSpinLock@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CSpinLock@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CSpinLock@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CSpinLock@@QEAAAEAV0@AEBV0@@Z>
extern __imp_?Apply@CLKRHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z:PANYARGS
?Apply@CLKRHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z TEXTEQU <__imp_?Apply@CLKRHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z>
extern __imp_?Apply@CLKRLinearHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z:PANYARGS
?Apply@CLKRLinearHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z TEXTEQU <__imp_?Apply@CLKRLinearHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z>
extern __imp_?ApplyIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z:PANYARGS
?ApplyIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z TEXTEQU <__imp_?ApplyIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z>
extern __imp_?ApplyIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z:PANYARGS
?ApplyIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z TEXTEQU <__imp_?ApplyIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z>
extern __imp_?BackupFile@CEXAutoBackupFile@@QEAAJPEBG@Z:PANYARGS
?BackupFile@CEXAutoBackupFile@@QEAAJPEBG@Z TEXTEQU <__imp_?BackupFile@CEXAutoBackupFile@@QEAAJPEBG@Z>
extern __imp_?BucketIndex@CLKRHashTableStats@@SAJJ@Z:PANYARGS
?BucketIndex@CLKRHashTableStats@@SAJJ@Z TEXTEQU <__imp_?BucketIndex@CLKRHashTableStats@@SAJJ@Z>
extern __imp_?BucketSize@CLKRHashTableStats@@SAJJ@Z:PANYARGS
?BucketSize@CLKRHashTableStats@@SAJJ@Z TEXTEQU <__imp_?BucketSize@CLKRHashTableStats@@SAJJ@Z>
extern __imp_?BucketSizes@CLKRHashTableStats@@SAPEBJXZ:PANYARGS
?BucketSizes@CLKRHashTableStats@@SAPEBJXZ TEXTEQU <__imp_?BucketSizes@CLKRHashTableStats@@SAPEBJXZ>
extern __imp_?CheckTable@CLKRHashTable@@QEBAHXZ:PANYARGS
?CheckTable@CLKRHashTable@@QEBAHXZ TEXTEQU <__imp_?CheckTable@CLKRHashTable@@QEBAHXZ>
extern __imp_?CheckTable@CLKRLinearHashTable@@QEBAHXZ:PANYARGS
?CheckTable@CLKRLinearHashTable@@QEBAHXZ TEXTEQU <__imp_?CheckTable@CLKRLinearHashTable@@QEBAHXZ>
extern __imp_?ClassName@CCritSec@@SAPEBDXZ:PANYARGS
?ClassName@CCritSec@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CCritSec@@SAPEBDXZ>
extern __imp_?ClassName@CFakeLock@@SAPEBDXZ:PANYARGS
?ClassName@CFakeLock@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CFakeLock@@SAPEBDXZ>
extern __imp_?ClassName@CLKRHashTable@@SAPEBDXZ:PANYARGS
?ClassName@CLKRHashTable@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CLKRHashTable@@SAPEBDXZ>
extern __imp_?ClassName@CLKRLinearHashTable@@SAPEBDXZ:PANYARGS
?ClassName@CLKRLinearHashTable@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CLKRLinearHashTable@@SAPEBDXZ>
extern __imp_?ClassName@CReaderWriterLock2@@SAPEBDXZ:PANYARGS
?ClassName@CReaderWriterLock2@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CReaderWriterLock2@@SAPEBDXZ>
extern __imp_?ClassName@CReaderWriterLock3@@SAPEBDXZ:PANYARGS
?ClassName@CReaderWriterLock3@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CReaderWriterLock3@@SAPEBDXZ>
extern __imp_?ClassName@CReaderWriterLock@@SAPEBDXZ:PANYARGS
?ClassName@CReaderWriterLock@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CReaderWriterLock@@SAPEBDXZ>
extern __imp_?ClassName@CSmallSpinLock@@SAPEBDXZ:PANYARGS
?ClassName@CSmallSpinLock@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CSmallSpinLock@@SAPEBDXZ>
extern __imp_?ClassName@CSpinLock@@SAPEBDXZ:PANYARGS
?ClassName@CSpinLock@@SAPEBDXZ TEXTEQU <__imp_?ClassName@CSpinLock@@SAPEBDXZ>
extern __imp_?Clear@CLKRHashTable@@QEAAXXZ:PANYARGS
?Clear@CLKRHashTable@@QEAAXXZ TEXTEQU <__imp_?Clear@CLKRHashTable@@QEAAXXZ>
extern __imp_?Clear@CLKRLinearHashTable@@QEAAXXZ:PANYARGS
?Clear@CLKRLinearHashTable@@QEAAXXZ TEXTEQU <__imp_?Clear@CLKRLinearHashTable@@QEAAXXZ>
extern __imp_?CloseIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?CloseIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?CloseIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?CloseIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PANYARGS
?CloseIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z TEXTEQU <__imp_?CloseIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>
extern __imp_?CloseIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?CloseIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?CloseIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?CloseIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PANYARGS
?CloseIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z TEXTEQU <__imp_?CloseIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>
extern __imp_?ConvertExclusiveToShared@CCritSec@@QEAAXXZ:PANYARGS
?ConvertExclusiveToShared@CCritSec@@QEAAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CCritSec@@QEAAXXZ>
extern __imp_?ConvertExclusiveToShared@CFakeLock@@QEAAXXZ:PANYARGS
?ConvertExclusiveToShared@CFakeLock@@QEAAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CFakeLock@@QEAAXXZ>
extern __imp_?ConvertExclusiveToShared@CLKRHashTable@@QEBAXXZ:PANYARGS
?ConvertExclusiveToShared@CLKRHashTable@@QEBAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CLKRHashTable@@QEBAXXZ>
extern __imp_?ConvertExclusiveToShared@CLKRLinearHashTable@@QEBAXXZ:PANYARGS
?ConvertExclusiveToShared@CLKRLinearHashTable@@QEBAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CLKRLinearHashTable@@QEBAXXZ>
extern __imp_?ConvertExclusiveToShared@CReaderWriterLock2@@QEAAXXZ:PANYARGS
?ConvertExclusiveToShared@CReaderWriterLock2@@QEAAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CReaderWriterLock2@@QEAAXXZ>
extern __imp_?ConvertExclusiveToShared@CReaderWriterLock3@@QEAAXXZ:PANYARGS
?ConvertExclusiveToShared@CReaderWriterLock3@@QEAAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CReaderWriterLock3@@QEAAXXZ>
extern __imp_?ConvertExclusiveToShared@CReaderWriterLock@@QEAAXXZ:PANYARGS
?ConvertExclusiveToShared@CReaderWriterLock@@QEAAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CReaderWriterLock@@QEAAXXZ>
extern __imp_?ConvertExclusiveToShared@CSmallSpinLock@@QEAAXXZ:PANYARGS
?ConvertExclusiveToShared@CSmallSpinLock@@QEAAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CSmallSpinLock@@QEAAXXZ>
extern __imp_?ConvertExclusiveToShared@CSpinLock@@QEAAXXZ:PANYARGS
?ConvertExclusiveToShared@CSpinLock@@QEAAXXZ TEXTEQU <__imp_?ConvertExclusiveToShared@CSpinLock@@QEAAXXZ>
extern __imp_?ConvertSharedToExclusive@CCritSec@@QEAAXXZ:PANYARGS
?ConvertSharedToExclusive@CCritSec@@QEAAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CCritSec@@QEAAXXZ>
extern __imp_?ConvertSharedToExclusive@CFakeLock@@QEAAXXZ:PANYARGS
?ConvertSharedToExclusive@CFakeLock@@QEAAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CFakeLock@@QEAAXXZ>
extern __imp_?ConvertSharedToExclusive@CLKRHashTable@@QEBAXXZ:PANYARGS
?ConvertSharedToExclusive@CLKRHashTable@@QEBAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CLKRHashTable@@QEBAXXZ>
extern __imp_?ConvertSharedToExclusive@CLKRLinearHashTable@@QEBAXXZ:PANYARGS
?ConvertSharedToExclusive@CLKRLinearHashTable@@QEBAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CLKRLinearHashTable@@QEBAXXZ>
extern __imp_?ConvertSharedToExclusive@CReaderWriterLock2@@QEAAXXZ:PANYARGS
?ConvertSharedToExclusive@CReaderWriterLock2@@QEAAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CReaderWriterLock2@@QEAAXXZ>
extern __imp_?ConvertSharedToExclusive@CReaderWriterLock3@@QEAAXXZ:PANYARGS
?ConvertSharedToExclusive@CReaderWriterLock3@@QEAAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CReaderWriterLock3@@QEAAXXZ>
extern __imp_?ConvertSharedToExclusive@CReaderWriterLock@@QEAAXXZ:PANYARGS
?ConvertSharedToExclusive@CReaderWriterLock@@QEAAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CReaderWriterLock@@QEAAXXZ>
extern __imp_?ConvertSharedToExclusive@CSmallSpinLock@@QEAAXXZ:PANYARGS
?ConvertSharedToExclusive@CSmallSpinLock@@QEAAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CSmallSpinLock@@QEAAXXZ>
extern __imp_?ConvertSharedToExclusive@CSpinLock@@QEAAXXZ:PANYARGS
?ConvertSharedToExclusive@CSpinLock@@QEAAXXZ TEXTEQU <__imp_?ConvertSharedToExclusive@CSpinLock@@QEAAXXZ>
extern __imp_?CreateHolder@@YAJPEAUIGPDispenser@@HIPEAPEAUIGPHolder@@@Z:PANYARGS
?CreateHolder@@YAJPEAUIGPDispenser@@HIPEAPEAUIGPHolder@@@Z TEXTEQU <__imp_?CreateHolder@@YAJPEAUIGPDispenser@@HIPEAPEAUIGPHolder@@@Z>
extern __imp_?DeleteIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z:PANYARGS
?DeleteIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z TEXTEQU <__imp_?DeleteIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z>
extern __imp_?DeleteIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z:PANYARGS
?DeleteIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z TEXTEQU <__imp_?DeleteIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z>
extern __imp_?DeleteKey@CLKRHashTable@@QEAA?AW4LK_RETCODE@@_K@Z:PANYARGS
?DeleteKey@CLKRHashTable@@QEAA?AW4LK_RETCODE@@_K@Z TEXTEQU <__imp_?DeleteKey@CLKRHashTable@@QEAA?AW4LK_RETCODE@@_K@Z>
extern __imp_?DeleteKey@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@_K@Z:PANYARGS
?DeleteKey@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@_K@Z TEXTEQU <__imp_?DeleteKey@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@_K@Z>
extern __imp_?DeleteRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z:PANYARGS
?DeleteRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z TEXTEQU <__imp_?DeleteRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z>
extern __imp_?DeleteRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z:PANYARGS
?DeleteRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z TEXTEQU <__imp_?DeleteRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z>
extern __imp_?FOCopyFile@CExFileOperation@@QEAAJPEBG0H@Z:PANYARGS
?FOCopyFile@CExFileOperation@@QEAAJPEBG0H@Z TEXTEQU <__imp_?FOCopyFile@CExFileOperation@@QEAAJPEBG0H@Z>
extern __imp_?FOCopyFileDACLS@CExFileOperation@@QEAAJPEBG0@Z:PANYARGS
?FOCopyFileDACLS@CExFileOperation@@QEAAJPEBG0@Z TEXTEQU <__imp_?FOCopyFileDACLS@CExFileOperation@@QEAAJPEBG0@Z>
extern __imp_?FODeleteFile@CExFileOperation@@QEAAJPEBG@Z:PANYARGS
?FODeleteFile@CExFileOperation@@QEAAJPEBG@Z TEXTEQU <__imp_?FODeleteFile@CExFileOperation@@QEAAJPEBG@Z>
extern __imp_?FOMoveFile@CExFileOperation@@QEAAJPEBG0@Z:PANYARGS
?FOMoveFile@CExFileOperation@@QEAAJPEBG0@Z TEXTEQU <__imp_?FOMoveFile@CExFileOperation@@QEAAJPEBG0@Z>
extern __imp_?FOReplaceFile@CExFileOperation@@QEAAJPEBG0@Z:PANYARGS
?FOReplaceFile@CExFileOperation@@QEAAJPEBG0@Z TEXTEQU <__imp_?FOReplaceFile@CExFileOperation@@QEAAJPEBG0@Z>
extern __imp_?FindKey@CLKRHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z:PANYARGS
?FindKey@CLKRHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z TEXTEQU <__imp_?FindKey@CLKRHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z>
extern __imp_?FindKey@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z:PANYARGS
?FindKey@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z TEXTEQU <__imp_?FindKey@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z>
extern __imp_?FindRecord@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z:PANYARGS
?FindRecord@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z TEXTEQU <__imp_?FindRecord@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z>
extern __imp_?FindRecord@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z:PANYARGS
?FindRecord@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z TEXTEQU <__imp_?FindRecord@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z>
extern __imp_?First@CDoubleList@@QEBAQEAVCListEntry@@XZ:PANYARGS
?First@CDoubleList@@QEBAQEAVCListEntry@@XZ TEXTEQU <__imp_?First@CDoubleList@@QEBAQEAVCListEntry@@XZ>
extern __imp_?First@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PANYARGS
?First@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ TEXTEQU <__imp_?First@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>
extern __imp_?GetBackupFile@CEXAutoBackupFile@@QEAAHPEAPEAG@Z:PANYARGS
?GetBackupFile@CEXAutoBackupFile@@QEAAHPEAPEAG@Z TEXTEQU <__imp_?GetBackupFile@CEXAutoBackupFile@@QEAAHPEAPEAG@Z>
extern __imp_?GetBucketLockSpinCount@CLKRHashTable@@QEAAGXZ:PANYARGS
?GetBucketLockSpinCount@CLKRHashTable@@QEAAGXZ TEXTEQU <__imp_?GetBucketLockSpinCount@CLKRHashTable@@QEAAGXZ>
extern __imp_?GetBucketLockSpinCount@CLKRLinearHashTable@@QEAAGXZ:PANYARGS
?GetBucketLockSpinCount@CLKRLinearHashTable@@QEAAGXZ TEXTEQU <__imp_?GetBucketLockSpinCount@CLKRLinearHashTable@@QEAAGXZ>
extern __imp_?GetDefaultSpinAdjustmentFactor@CCritSec@@SANXZ:PANYARGS
?GetDefaultSpinAdjustmentFactor@CCritSec@@SANXZ TEXTEQU <__imp_?GetDefaultSpinAdjustmentFactor@CCritSec@@SANXZ>
extern __imp_?GetDefaultSpinAdjustmentFactor@CFakeLock@@SANXZ:PANYARGS
?GetDefaultSpinAdjustmentFactor@CFakeLock@@SANXZ TEXTEQU <__imp_?GetDefaultSpinAdjustmentFactor@CFakeLock@@SANXZ>
extern __imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SANXZ:PANYARGS
?GetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SANXZ TEXTEQU <__imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SANXZ>
extern __imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SANXZ:PANYARGS
?GetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SANXZ TEXTEQU <__imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SANXZ>
extern __imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SANXZ:PANYARGS
?GetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SANXZ TEXTEQU <__imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SANXZ>
extern __imp_?GetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SANXZ:PANYARGS
?GetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SANXZ TEXTEQU <__imp_?GetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SANXZ>
extern __imp_?GetDefaultSpinAdjustmentFactor@CSpinLock@@SANXZ:PANYARGS
?GetDefaultSpinAdjustmentFactor@CSpinLock@@SANXZ TEXTEQU <__imp_?GetDefaultSpinAdjustmentFactor@CSpinLock@@SANXZ>
extern __imp_?GetDefaultSpinCount@CCritSec@@SAGXZ:PANYARGS
?GetDefaultSpinCount@CCritSec@@SAGXZ TEXTEQU <__imp_?GetDefaultSpinCount@CCritSec@@SAGXZ>
extern __imp_?GetDefaultSpinCount@CFakeLock@@SAGXZ:PANYARGS
?GetDefaultSpinCount@CFakeLock@@SAGXZ TEXTEQU <__imp_?GetDefaultSpinCount@CFakeLock@@SAGXZ>
extern __imp_?GetDefaultSpinCount@CReaderWriterLock2@@SAGXZ:PANYARGS
?GetDefaultSpinCount@CReaderWriterLock2@@SAGXZ TEXTEQU <__imp_?GetDefaultSpinCount@CReaderWriterLock2@@SAGXZ>
extern __imp_?GetDefaultSpinCount@CReaderWriterLock3@@SAGXZ:PANYARGS
?GetDefaultSpinCount@CReaderWriterLock3@@SAGXZ TEXTEQU <__imp_?GetDefaultSpinCount@CReaderWriterLock3@@SAGXZ>
extern __imp_?GetDefaultSpinCount@CReaderWriterLock@@SAGXZ:PANYARGS
?GetDefaultSpinCount@CReaderWriterLock@@SAGXZ TEXTEQU <__imp_?GetDefaultSpinCount@CReaderWriterLock@@SAGXZ>
extern __imp_?GetDefaultSpinCount@CSmallSpinLock@@SAGXZ:PANYARGS
?GetDefaultSpinCount@CSmallSpinLock@@SAGXZ TEXTEQU <__imp_?GetDefaultSpinCount@CSmallSpinLock@@SAGXZ>
extern __imp_?GetDefaultSpinCount@CSpinLock@@SAGXZ:PANYARGS
?GetDefaultSpinCount@CSpinLock@@SAGXZ TEXTEQU <__imp_?GetDefaultSpinCount@CSpinLock@@SAGXZ>
extern __imp_?GetSpinCount@CCritSec@@QEBAGXZ:PANYARGS
?GetSpinCount@CCritSec@@QEBAGXZ TEXTEQU <__imp_?GetSpinCount@CCritSec@@QEBAGXZ>
extern __imp_?GetSpinCount@CFakeLock@@QEBAGXZ:PANYARGS
?GetSpinCount@CFakeLock@@QEBAGXZ TEXTEQU <__imp_?GetSpinCount@CFakeLock@@QEBAGXZ>
extern __imp_?GetSpinCount@CReaderWriterLock2@@QEBAGXZ:PANYARGS
?GetSpinCount@CReaderWriterLock2@@QEBAGXZ TEXTEQU <__imp_?GetSpinCount@CReaderWriterLock2@@QEBAGXZ>
extern __imp_?GetSpinCount@CReaderWriterLock3@@QEBAGXZ:PANYARGS
?GetSpinCount@CReaderWriterLock3@@QEBAGXZ TEXTEQU <__imp_?GetSpinCount@CReaderWriterLock3@@QEBAGXZ>
extern __imp_?GetSpinCount@CReaderWriterLock@@QEBAGXZ:PANYARGS
?GetSpinCount@CReaderWriterLock@@QEBAGXZ TEXTEQU <__imp_?GetSpinCount@CReaderWriterLock@@QEBAGXZ>
extern __imp_?GetSpinCount@CSmallSpinLock@@QEBAGXZ:PANYARGS
?GetSpinCount@CSmallSpinLock@@QEBAGXZ TEXTEQU <__imp_?GetSpinCount@CSmallSpinLock@@QEBAGXZ>
extern __imp_?GetSpinCount@CSpinLock@@QEBAGXZ:PANYARGS
?GetSpinCount@CSpinLock@@QEBAGXZ TEXTEQU <__imp_?GetSpinCount@CSpinLock@@QEBAGXZ>
extern __imp_?GetStatistics@CLKRHashTable@@QEBA?AVCLKRHashTableStats@@XZ:PANYARGS
?GetStatistics@CLKRHashTable@@QEBA?AVCLKRHashTableStats@@XZ TEXTEQU <__imp_?GetStatistics@CLKRHashTable@@QEBA?AVCLKRHashTableStats@@XZ>
extern __imp_?GetStatistics@CLKRLinearHashTable@@QEBA?AVCLKRHashTableStats@@XZ:PANYARGS
?GetStatistics@CLKRLinearHashTable@@QEBA?AVCLKRHashTableStats@@XZ TEXTEQU <__imp_?GetStatistics@CLKRLinearHashTable@@QEBA?AVCLKRHashTableStats@@XZ>
extern __imp_?GetTableLockSpinCount@CLKRHashTable@@QEAAGXZ:PANYARGS
?GetTableLockSpinCount@CLKRHashTable@@QEAAGXZ TEXTEQU <__imp_?GetTableLockSpinCount@CLKRHashTable@@QEAAGXZ>
extern __imp_?GetTableLockSpinCount@CLKRLinearHashTable@@QEAAGXZ:PANYARGS
?GetTableLockSpinCount@CLKRLinearHashTable@@QEAAGXZ TEXTEQU <__imp_?GetTableLockSpinCount@CLKRLinearHashTable@@QEAAGXZ>
extern __imp_?GetVersionExW@CMdVersionInfo@@SAHPEAU_OSVERSIONINFOW@@@Z:PANYARGS
?GetVersionExW@CMdVersionInfo@@SAHPEAU_OSVERSIONINFOW@@@Z TEXTEQU <__imp_?GetVersionExW@CMdVersionInfo@@SAHPEAU_OSVERSIONINFOW@@@Z>
extern __imp_?HeadNode@CDoubleList@@QEBAQEBVCListEntry@@XZ:PANYARGS
?HeadNode@CDoubleList@@QEBAQEBVCListEntry@@XZ TEXTEQU <__imp_?HeadNode@CDoubleList@@QEBAQEBVCListEntry@@XZ>
extern __imp_?HeadNode@CLockedDoubleList@@QEBAQEBVCListEntry@@XZ:PANYARGS
?HeadNode@CLockedDoubleList@@QEBAQEBVCListEntry@@XZ TEXTEQU <__imp_?HeadNode@CLockedDoubleList@@QEBAQEBVCListEntry@@XZ>
extern __imp_?IncrementIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?IncrementIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?IncrementIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?IncrementIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PANYARGS
?IncrementIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z TEXTEQU <__imp_?IncrementIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>
extern __imp_?IncrementIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?IncrementIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?IncrementIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?IncrementIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PANYARGS
?IncrementIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z TEXTEQU <__imp_?IncrementIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>
extern __imp_?InitializeIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?InitializeIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?InitializeIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?InitializeIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PANYARGS
?InitializeIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z TEXTEQU <__imp_?InitializeIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>
extern __imp_?InitializeIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?InitializeIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?InitializeIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?InitializeIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PANYARGS
?InitializeIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z TEXTEQU <__imp_?InitializeIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>
extern __imp_?InitializeVersionInfo@CMdVersionInfo@@CAHXZ:PANYARGS
?InitializeVersionInfo@CMdVersionInfo@@CAHXZ TEXTEQU <__imp_?InitializeVersionInfo@CMdVersionInfo@@CAHXZ>
extern __imp_?InsertHead@CDoubleList@@QEAAXQEAVCListEntry@@@Z:PANYARGS
?InsertHead@CDoubleList@@QEAAXQEAVCListEntry@@@Z TEXTEQU <__imp_?InsertHead@CDoubleList@@QEAAXQEAVCListEntry@@@Z>
extern __imp_?InsertHead@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z:PANYARGS
?InsertHead@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z TEXTEQU <__imp_?InsertHead@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z>
extern __imp_?InsertRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z:PANYARGS
?InsertRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z TEXTEQU <__imp_?InsertRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z>
extern __imp_?InsertRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z:PANYARGS
?InsertRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z TEXTEQU <__imp_?InsertRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z>
extern __imp_?InsertTail@CDoubleList@@QEAAXQEAVCListEntry@@@Z:PANYARGS
?InsertTail@CDoubleList@@QEAAXQEAVCListEntry@@@Z TEXTEQU <__imp_?InsertTail@CDoubleList@@QEAAXQEAVCListEntry@@@Z>
extern __imp_?InsertTail@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z:PANYARGS
?InsertTail@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z TEXTEQU <__imp_?InsertTail@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z>
extern __imp_?IsEmpty@CDoubleList@@QEBA_NXZ:PANYARGS
?IsEmpty@CDoubleList@@QEBA_NXZ TEXTEQU <__imp_?IsEmpty@CDoubleList@@QEBA_NXZ>
extern __imp_?IsEmpty@CLockedDoubleList@@QEBA_NXZ:PANYARGS
?IsEmpty@CLockedDoubleList@@QEBA_NXZ TEXTEQU <__imp_?IsEmpty@CLockedDoubleList@@QEBA_NXZ>
extern __imp_?IsEmpty@CLockedSingleList@@QEBA_NXZ:PANYARGS
?IsEmpty@CLockedSingleList@@QEBA_NXZ TEXTEQU <__imp_?IsEmpty@CLockedSingleList@@QEBA_NXZ>
extern __imp_?IsEmpty@CSingleList@@QEBA_NXZ:PANYARGS
?IsEmpty@CSingleList@@QEBA_NXZ TEXTEQU <__imp_?IsEmpty@CSingleList@@QEBA_NXZ>
extern __imp_?IsLocked@CLockedDoubleList@@QEBA_NXZ:PANYARGS
?IsLocked@CLockedDoubleList@@QEBA_NXZ TEXTEQU <__imp_?IsLocked@CLockedDoubleList@@QEBA_NXZ>
extern __imp_?IsLocked@CLockedSingleList@@QEBA_NXZ:PANYARGS
?IsLocked@CLockedSingleList@@QEBA_NXZ TEXTEQU <__imp_?IsLocked@CLockedSingleList@@QEBA_NXZ>
extern __imp_?IsMillnm@CMdVersionInfo@@SAHXZ:PANYARGS
?IsMillnm@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsMillnm@CMdVersionInfo@@SAHXZ>
extern __imp_?IsReadLocked@CCritSec@@QEBA_NXZ:PANYARGS
?IsReadLocked@CCritSec@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CCritSec@@QEBA_NXZ>
extern __imp_?IsReadLocked@CFakeLock@@QEBA_NXZ:PANYARGS
?IsReadLocked@CFakeLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CFakeLock@@QEBA_NXZ>
extern __imp_?IsReadLocked@CLKRHashTable@@QEBA_NXZ:PANYARGS
?IsReadLocked@CLKRHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CLKRHashTable@@QEBA_NXZ>
extern __imp_?IsReadLocked@CLKRLinearHashTable@@QEBA_NXZ:PANYARGS
?IsReadLocked@CLKRLinearHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CLKRLinearHashTable@@QEBA_NXZ>
extern __imp_?IsReadLocked@CReaderWriterLock2@@QEBA_NXZ:PANYARGS
?IsReadLocked@CReaderWriterLock2@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CReaderWriterLock2@@QEBA_NXZ>
extern __imp_?IsReadLocked@CReaderWriterLock3@@QEBA_NXZ:PANYARGS
?IsReadLocked@CReaderWriterLock3@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CReaderWriterLock3@@QEBA_NXZ>
extern __imp_?IsReadLocked@CReaderWriterLock@@QEBA_NXZ:PANYARGS
?IsReadLocked@CReaderWriterLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CReaderWriterLock@@QEBA_NXZ>
extern __imp_?IsReadLocked@CSmallSpinLock@@QEBA_NXZ:PANYARGS
?IsReadLocked@CSmallSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CSmallSpinLock@@QEBA_NXZ>
extern __imp_?IsReadLocked@CSpinLock@@QEBA_NXZ:PANYARGS
?IsReadLocked@CSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadLocked@CSpinLock@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CCritSec@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CCritSec@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CCritSec@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CFakeLock@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CFakeLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CFakeLock@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CLKRHashTable@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CLKRHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CLKRHashTable@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CLKRLinearHashTable@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CLKRLinearHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CLKRLinearHashTable@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CReaderWriterLock2@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CReaderWriterLock2@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CReaderWriterLock2@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CReaderWriterLock3@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CReaderWriterLock3@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CReaderWriterLock3@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CReaderWriterLock@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CReaderWriterLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CReaderWriterLock@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CSmallSpinLock@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CSmallSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CSmallSpinLock@@QEBA_NXZ>
extern __imp_?IsReadUnlocked@CSpinLock@@QEBA_NXZ:PANYARGS
?IsReadUnlocked@CSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsReadUnlocked@CSpinLock@@QEBA_NXZ>
extern __imp_?IsUnlocked@CLockedDoubleList@@QEBA_NXZ:PANYARGS
?IsUnlocked@CLockedDoubleList@@QEBA_NXZ TEXTEQU <__imp_?IsUnlocked@CLockedDoubleList@@QEBA_NXZ>
extern __imp_?IsUnlocked@CLockedSingleList@@QEBA_NXZ:PANYARGS
?IsUnlocked@CLockedSingleList@@QEBA_NXZ TEXTEQU <__imp_?IsUnlocked@CLockedSingleList@@QEBA_NXZ>
extern __imp_?IsUsable@CLKRHashTable@@QEBA_NXZ:PANYARGS
?IsUsable@CLKRHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsUsable@CLKRHashTable@@QEBA_NXZ>
extern __imp_?IsUsable@CLKRLinearHashTable@@QEBA_NXZ:PANYARGS
?IsUsable@CLKRLinearHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsUsable@CLKRLinearHashTable@@QEBA_NXZ>
extern __imp_?IsValid@CLKRHashTable@@QEBA_NXZ:PANYARGS
?IsValid@CLKRHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsValid@CLKRHashTable@@QEBA_NXZ>
extern __imp_?IsValid@CLKRLinearHashTable@@QEBA_NXZ:PANYARGS
?IsValid@CLKRLinearHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsValid@CLKRLinearHashTable@@QEBA_NXZ>
extern __imp_?IsWin2k@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWin2k@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWin2k@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWin2korLater@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWin2korLater@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWin2korLater@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWin95@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWin95@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWin95@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWin98@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWin98@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWin98@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWin98orLater@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWin98orLater@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWin98orLater@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWin9x@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWin9x@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWin9x@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWinNT4@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWinNT4@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWinNT4@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWinNT@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWinNT@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWinNT@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWinNt4orLater@CMdVersionInfo@@SAHXZ:PANYARGS
?IsWinNt4orLater@CMdVersionInfo@@SAHXZ TEXTEQU <__imp_?IsWinNt4orLater@CMdVersionInfo@@SAHXZ>
extern __imp_?IsWriteLocked@CCritSec@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CCritSec@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CCritSec@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CFakeLock@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CFakeLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CFakeLock@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CLKRHashTable@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CLKRHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CLKRHashTable@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CLKRLinearHashTable@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CLKRLinearHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CLKRLinearHashTable@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CReaderWriterLock2@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CReaderWriterLock2@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CReaderWriterLock2@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CReaderWriterLock3@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CReaderWriterLock3@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CReaderWriterLock3@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CReaderWriterLock@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CReaderWriterLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CReaderWriterLock@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CSmallSpinLock@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CSmallSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CSmallSpinLock@@QEBA_NXZ>
extern __imp_?IsWriteLocked@CSpinLock@@QEBA_NXZ:PANYARGS
?IsWriteLocked@CSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteLocked@CSpinLock@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CCritSec@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CCritSec@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CCritSec@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CFakeLock@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CFakeLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CFakeLock@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CLKRHashTable@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CLKRHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CLKRHashTable@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CLKRLinearHashTable@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CLKRLinearHashTable@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CLKRLinearHashTable@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CReaderWriterLock2@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CReaderWriterLock2@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CReaderWriterLock2@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CReaderWriterLock3@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CReaderWriterLock3@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CReaderWriterLock3@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CReaderWriterLock@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CReaderWriterLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CReaderWriterLock@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CSmallSpinLock@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CSmallSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CSmallSpinLock@@QEBA_NXZ>
extern __imp_?IsWriteUnlocked@CSpinLock@@QEBA_NXZ:PANYARGS
?IsWriteUnlocked@CSpinLock@@QEBA_NXZ TEXTEQU <__imp_?IsWriteUnlocked@CSpinLock@@QEBA_NXZ>
extern __imp_?Last@CDoubleList@@QEBAQEAVCListEntry@@XZ:PANYARGS
?Last@CDoubleList@@QEBAQEAVCListEntry@@XZ TEXTEQU <__imp_?Last@CDoubleList@@QEBAQEAVCListEntry@@XZ>
extern __imp_?Last@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PANYARGS
?Last@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ TEXTEQU <__imp_?Last@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>
extern __imp_?Lock@CLockedDoubleList@@QEAAXXZ:PANYARGS
?Lock@CLockedDoubleList@@QEAAXXZ TEXTEQU <__imp_?Lock@CLockedDoubleList@@QEAAXXZ>
extern __imp_?Lock@CLockedSingleList@@QEAAXXZ:PANYARGS
?Lock@CLockedSingleList@@QEAAXXZ TEXTEQU <__imp_?Lock@CLockedSingleList@@QEAAXXZ>
extern __imp_?LockType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PANYARGS
?LockType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ TEXTEQU <__imp_?LockType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>
extern __imp_?LockType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PANYARGS
?LockType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ TEXTEQU <__imp_?LockType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>
extern __imp_?LockType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_LOCKTYPE@@XZ:PANYARGS
?LockType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_LOCKTYPE@@XZ TEXTEQU <__imp_?LockType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_LOCKTYPE@@XZ>
extern __imp_?LockType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_LOCKTYPE@@XZ:PANYARGS
?LockType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_LOCKTYPE@@XZ TEXTEQU <__imp_?LockType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_LOCKTYPE@@XZ>
extern __imp_?LockType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PANYARGS
?LockType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ TEXTEQU <__imp_?LockType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>
extern __imp_?LockType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PANYARGS
?LockType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ TEXTEQU <__imp_?LockType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>
extern __imp_?LockType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PANYARGS
?LockType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ TEXTEQU <__imp_?LockType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>
extern __imp_?MaxSize@CLKRHashTable@@QEBAKXZ:PANYARGS
?MaxSize@CLKRHashTable@@QEBAKXZ TEXTEQU <__imp_?MaxSize@CLKRHashTable@@QEBAKXZ>
extern __imp_?MaxSize@CLKRLinearHashTable@@QEBAKXZ:PANYARGS
?MaxSize@CLKRLinearHashTable@@QEBAKXZ TEXTEQU <__imp_?MaxSize@CLKRLinearHashTable@@QEBAKXZ>
extern __imp_?MpHeapCompact@@YA_KPEAX@Z:PANYARGS
?MpHeapCompact@@YA_KPEAX@Z TEXTEQU <__imp_?MpHeapCompact@@YA_KPEAX@Z>
extern __imp_?MutexType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PANYARGS
?MutexType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ TEXTEQU <__imp_?MutexType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>
extern __imp_?MutexType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PANYARGS
?MutexType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ TEXTEQU <__imp_?MutexType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>
extern __imp_?MutexType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RW_MUTEX@@XZ:PANYARGS
?MutexType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RW_MUTEX@@XZ TEXTEQU <__imp_?MutexType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RW_MUTEX@@XZ>
extern __imp_?MutexType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RW_MUTEX@@XZ:PANYARGS
?MutexType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RW_MUTEX@@XZ TEXTEQU <__imp_?MutexType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RW_MUTEX@@XZ>
extern __imp_?MutexType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PANYARGS
?MutexType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ TEXTEQU <__imp_?MutexType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>
extern __imp_?MutexType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PANYARGS
?MutexType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ TEXTEQU <__imp_?MutexType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>
extern __imp_?MutexType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PANYARGS
?MutexType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ TEXTEQU <__imp_?MutexType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>
extern __imp_?NumSubTables@CLKRHashTable@@QEBAHXZ:PANYARGS
?NumSubTables@CLKRHashTable@@QEBAHXZ TEXTEQU <__imp_?NumSubTables@CLKRHashTable@@QEBAHXZ>
extern __imp_?NumSubTables@CLKRHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z:PANYARGS
?NumSubTables@CLKRHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z TEXTEQU <__imp_?NumSubTables@CLKRHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z>
extern __imp_?NumSubTables@CLKRLinearHashTable@@QEBAHXZ:PANYARGS
?NumSubTables@CLKRLinearHashTable@@QEBAHXZ TEXTEQU <__imp_?NumSubTables@CLKRLinearHashTable@@QEBAHXZ>
extern __imp_?NumSubTables@CLKRLinearHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z:PANYARGS
?NumSubTables@CLKRLinearHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z TEXTEQU <__imp_?NumSubTables@CLKRLinearHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z>
extern __imp_?OnUnicodeSystem@@YAHXZ:PANYARGS
?OnUnicodeSystem@@YAHXZ TEXTEQU <__imp_?OnUnicodeSystem@@YAHXZ>
extern __imp_?PerLockSpin@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PANYARGS
?PerLockSpin@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ TEXTEQU <__imp_?PerLockSpin@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>
extern __imp_?PerLockSpin@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PANYARGS
?PerLockSpin@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ TEXTEQU <__imp_?PerLockSpin@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>
extern __imp_?PerLockSpin@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PANYARGS
?PerLockSpin@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_PERLOCK_SPIN@@XZ TEXTEQU <__imp_?PerLockSpin@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>
extern __imp_?PerLockSpin@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PANYARGS
?PerLockSpin@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_PERLOCK_SPIN@@XZ TEXTEQU <__imp_?PerLockSpin@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>
extern __imp_?PerLockSpin@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PANYARGS
?PerLockSpin@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ TEXTEQU <__imp_?PerLockSpin@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>
extern __imp_?PerLockSpin@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PANYARGS
?PerLockSpin@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ TEXTEQU <__imp_?PerLockSpin@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>
extern __imp_?PerLockSpin@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PANYARGS
?PerLockSpin@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ TEXTEQU <__imp_?PerLockSpin@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>
extern __imp_?Pop@CLockedSingleList@@QEAAQEAVCSingleListEntry@@XZ:PANYARGS
?Pop@CLockedSingleList@@QEAAQEAVCSingleListEntry@@XZ TEXTEQU <__imp_?Pop@CLockedSingleList@@QEAAQEAVCSingleListEntry@@XZ>
extern __imp_?Pop@CSingleList@@QEAAQEAVCSingleListEntry@@XZ:PANYARGS
?Pop@CSingleList@@QEAAQEAVCSingleListEntry@@XZ TEXTEQU <__imp_?Pop@CSingleList@@QEAAQEAVCSingleListEntry@@XZ>
extern __imp_?Print@CLKRHashTable@@QEBAXXZ:PANYARGS
?Print@CLKRHashTable@@QEBAXXZ TEXTEQU <__imp_?Print@CLKRHashTable@@QEBAXXZ>
extern __imp_?Print@CLKRLinearHashTable@@QEBAXXZ:PANYARGS
?Print@CLKRLinearHashTable@@QEBAXXZ TEXTEQU <__imp_?Print@CLKRLinearHashTable@@QEBAXXZ>
extern __imp_?Push@CLockedSingleList@@QEAAXQEAVCSingleListEntry@@@Z:PANYARGS
?Push@CLockedSingleList@@QEAAXQEAVCSingleListEntry@@@Z TEXTEQU <__imp_?Push@CLockedSingleList@@QEAAXQEAVCSingleListEntry@@@Z>
extern __imp_?Push@CSingleList@@QEAAXQEAVCSingleListEntry@@@Z:PANYARGS
?Push@CSingleList@@QEAAXQEAVCSingleListEntry@@@Z TEXTEQU <__imp_?Push@CSingleList@@QEAAXQEAVCSingleListEntry@@@Z>
extern __imp_?QueueType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PANYARGS
?QueueType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ TEXTEQU <__imp_?QueueType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>
extern __imp_?QueueType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PANYARGS
?QueueType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ TEXTEQU <__imp_?QueueType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>
extern __imp_?QueueType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PANYARGS
?QueueType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_QUEUE_TYPE@@XZ TEXTEQU <__imp_?QueueType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_QUEUE_TYPE@@XZ>
extern __imp_?QueueType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PANYARGS
?QueueType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_QUEUE_TYPE@@XZ TEXTEQU <__imp_?QueueType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_QUEUE_TYPE@@XZ>
extern __imp_?QueueType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PANYARGS
?QueueType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ TEXTEQU <__imp_?QueueType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>
extern __imp_?QueueType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PANYARGS
?QueueType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ TEXTEQU <__imp_?QueueType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>
extern __imp_?QueueType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PANYARGS
?QueueType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ TEXTEQU <__imp_?QueueType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>
extern __imp_?ReadLock@CCritSec@@QEAAXXZ:PANYARGS
?ReadLock@CCritSec@@QEAAXXZ TEXTEQU <__imp_?ReadLock@CCritSec@@QEAAXXZ>
extern __imp_?ReadLock@CFakeLock@@QEAAXXZ:PANYARGS
?ReadLock@CFakeLock@@QEAAXXZ TEXTEQU <__imp_?ReadLock@CFakeLock@@QEAAXXZ>
extern __imp_?ReadLock@CLKRHashTable@@QEBAXXZ:PANYARGS
?ReadLock@CLKRHashTable@@QEBAXXZ TEXTEQU <__imp_?ReadLock@CLKRHashTable@@QEBAXXZ>
extern __imp_?ReadLock@CLKRLinearHashTable@@QEBAXXZ:PANYARGS
?ReadLock@CLKRLinearHashTable@@QEBAXXZ TEXTEQU <__imp_?ReadLock@CLKRLinearHashTable@@QEBAXXZ>
extern __imp_?ReadLock@CReaderWriterLock2@@QEAAXXZ:PANYARGS
?ReadLock@CReaderWriterLock2@@QEAAXXZ TEXTEQU <__imp_?ReadLock@CReaderWriterLock2@@QEAAXXZ>
extern __imp_?ReadLock@CReaderWriterLock3@@QEAAXXZ:PANYARGS
?ReadLock@CReaderWriterLock3@@QEAAXXZ TEXTEQU <__imp_?ReadLock@CReaderWriterLock3@@QEAAXXZ>
extern __imp_?ReadLock@CReaderWriterLock@@QEAAXXZ:PANYARGS
?ReadLock@CReaderWriterLock@@QEAAXXZ TEXTEQU <__imp_?ReadLock@CReaderWriterLock@@QEAAXXZ>
extern __imp_?ReadLock@CSmallSpinLock@@QEAAXXZ:PANYARGS
?ReadLock@CSmallSpinLock@@QEAAXXZ TEXTEQU <__imp_?ReadLock@CSmallSpinLock@@QEAAXXZ>
extern __imp_?ReadLock@CSpinLock@@QEAAXXZ:PANYARGS
?ReadLock@CSpinLock@@QEAAXXZ TEXTEQU <__imp_?ReadLock@CSpinLock@@QEAAXXZ>
extern __imp_?ReadOrWriteLock@CCritSec@@QEAA_NXZ:PANYARGS
?ReadOrWriteLock@CCritSec@@QEAA_NXZ TEXTEQU <__imp_?ReadOrWriteLock@CCritSec@@QEAA_NXZ>
extern __imp_?ReadOrWriteLock@CFakeLock@@QEAA_NXZ:PANYARGS
?ReadOrWriteLock@CFakeLock@@QEAA_NXZ TEXTEQU <__imp_?ReadOrWriteLock@CFakeLock@@QEAA_NXZ>
extern __imp_?ReadOrWriteLock@CReaderWriterLock3@@QEAA_NXZ:PANYARGS
?ReadOrWriteLock@CReaderWriterLock3@@QEAA_NXZ TEXTEQU <__imp_?ReadOrWriteLock@CReaderWriterLock3@@QEAA_NXZ>
extern __imp_?ReadOrWriteLock@CSpinLock@@QEAA_NXZ:PANYARGS
?ReadOrWriteLock@CSpinLock@@QEAA_NXZ TEXTEQU <__imp_?ReadOrWriteLock@CSpinLock@@QEAA_NXZ>
extern __imp_?ReadOrWriteUnlock@CCritSec@@QEAAX_N@Z:PANYARGS
?ReadOrWriteUnlock@CCritSec@@QEAAX_N@Z TEXTEQU <__imp_?ReadOrWriteUnlock@CCritSec@@QEAAX_N@Z>
extern __imp_?ReadOrWriteUnlock@CFakeLock@@QEAAX_N@Z:PANYARGS
?ReadOrWriteUnlock@CFakeLock@@QEAAX_N@Z TEXTEQU <__imp_?ReadOrWriteUnlock@CFakeLock@@QEAAX_N@Z>
extern __imp_?ReadOrWriteUnlock@CReaderWriterLock3@@QEAAX_N@Z:PANYARGS
?ReadOrWriteUnlock@CReaderWriterLock3@@QEAAX_N@Z TEXTEQU <__imp_?ReadOrWriteUnlock@CReaderWriterLock3@@QEAAX_N@Z>
extern __imp_?ReadOrWriteUnlock@CSpinLock@@QEAAX_N@Z:PANYARGS
?ReadOrWriteUnlock@CSpinLock@@QEAAX_N@Z TEXTEQU <__imp_?ReadOrWriteUnlock@CSpinLock@@QEAAX_N@Z>
extern __imp_?ReadUnlock@CCritSec@@QEAAXXZ:PANYARGS
?ReadUnlock@CCritSec@@QEAAXXZ TEXTEQU <__imp_?ReadUnlock@CCritSec@@QEAAXXZ>
extern __imp_?ReadUnlock@CFakeLock@@QEAAXXZ:PANYARGS
?ReadUnlock@CFakeLock@@QEAAXXZ TEXTEQU <__imp_?ReadUnlock@CFakeLock@@QEAAXXZ>
extern __imp_?ReadUnlock@CLKRHashTable@@QEBAXXZ:PANYARGS
?ReadUnlock@CLKRHashTable@@QEBAXXZ TEXTEQU <__imp_?ReadUnlock@CLKRHashTable@@QEBAXXZ>
extern __imp_?ReadUnlock@CLKRLinearHashTable@@QEBAXXZ:PANYARGS
?ReadUnlock@CLKRLinearHashTable@@QEBAXXZ TEXTEQU <__imp_?ReadUnlock@CLKRLinearHashTable@@QEBAXXZ>
extern __imp_?ReadUnlock@CReaderWriterLock2@@QEAAXXZ:PANYARGS
?ReadUnlock@CReaderWriterLock2@@QEAAXXZ TEXTEQU <__imp_?ReadUnlock@CReaderWriterLock2@@QEAAXXZ>
extern __imp_?ReadUnlock@CReaderWriterLock3@@QEAAXXZ:PANYARGS
?ReadUnlock@CReaderWriterLock3@@QEAAXXZ TEXTEQU <__imp_?ReadUnlock@CReaderWriterLock3@@QEAAXXZ>
extern __imp_?ReadUnlock@CReaderWriterLock@@QEAAXXZ:PANYARGS
?ReadUnlock@CReaderWriterLock@@QEAAXXZ TEXTEQU <__imp_?ReadUnlock@CReaderWriterLock@@QEAAXXZ>
extern __imp_?ReadUnlock@CSmallSpinLock@@QEAAXXZ:PANYARGS
?ReadUnlock@CSmallSpinLock@@QEAAXXZ TEXTEQU <__imp_?ReadUnlock@CSmallSpinLock@@QEAAXXZ>
extern __imp_?ReadUnlock@CSpinLock@@QEAAXXZ:PANYARGS
?ReadUnlock@CSpinLock@@QEAAXXZ TEXTEQU <__imp_?ReadUnlock@CSpinLock@@QEAAXXZ>
extern __imp_?Recursion@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PANYARGS
?Recursion@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RECURSION@@XZ TEXTEQU <__imp_?Recursion@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>
extern __imp_?Recursion@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PANYARGS
?Recursion@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ TEXTEQU <__imp_?Recursion@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>
extern __imp_?Recursion@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RECURSION@@XZ:PANYARGS
?Recursion@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RECURSION@@XZ TEXTEQU <__imp_?Recursion@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RECURSION@@XZ>
extern __imp_?Recursion@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RECURSION@@XZ:PANYARGS
?Recursion@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RECURSION@@XZ TEXTEQU <__imp_?Recursion@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RECURSION@@XZ>
extern __imp_?Recursion@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PANYARGS
?Recursion@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ TEXTEQU <__imp_?Recursion@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>
extern __imp_?Recursion@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PANYARGS
?Recursion@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ TEXTEQU <__imp_?Recursion@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>
extern __imp_?Recursion@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PANYARGS
?Recursion@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ TEXTEQU <__imp_?Recursion@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>
extern __imp_?ReleaseVersionInfo@CMdVersionInfo@@SAXXZ:PANYARGS
?ReleaseVersionInfo@CMdVersionInfo@@SAXXZ TEXTEQU <__imp_?ReleaseVersionInfo@CMdVersionInfo@@SAXXZ>
extern __imp_?RemoveEntry@CDoubleList@@SAXQEAVCListEntry@@@Z:PANYARGS
?RemoveEntry@CDoubleList@@SAXQEAVCListEntry@@@Z TEXTEQU <__imp_?RemoveEntry@CDoubleList@@SAXQEAVCListEntry@@@Z>
extern __imp_?RemoveEntry@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z:PANYARGS
?RemoveEntry@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z TEXTEQU <__imp_?RemoveEntry@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z>
extern __imp_?RemoveHead@CDoubleList@@QEAAQEAVCListEntry@@XZ:PANYARGS
?RemoveHead@CDoubleList@@QEAAQEAVCListEntry@@XZ TEXTEQU <__imp_?RemoveHead@CDoubleList@@QEAAQEAVCListEntry@@XZ>
extern __imp_?RemoveHead@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PANYARGS
?RemoveHead@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ TEXTEQU <__imp_?RemoveHead@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>
extern __imp_?RemoveTail@CDoubleList@@QEAAQEAVCListEntry@@XZ:PANYARGS
?RemoveTail@CDoubleList@@QEAAQEAVCListEntry@@XZ TEXTEQU <__imp_?RemoveTail@CDoubleList@@QEAAQEAVCListEntry@@XZ>
extern __imp_?RemoveTail@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PANYARGS
?RemoveTail@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ TEXTEQU <__imp_?RemoveTail@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>
extern __imp_?RestoreFile@CEXAutoBackupFile@@QEAAJXZ:PANYARGS
?RestoreFile@CEXAutoBackupFile@@QEAAJXZ TEXTEQU <__imp_?RestoreFile@CEXAutoBackupFile@@QEAAJXZ>
extern __imp_?SetBucketLockSpinCount@CLKRHashTable@@QEAAXG@Z:PANYARGS
?SetBucketLockSpinCount@CLKRHashTable@@QEAAXG@Z TEXTEQU <__imp_?SetBucketLockSpinCount@CLKRHashTable@@QEAAXG@Z>
extern __imp_?SetBucketLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z:PANYARGS
?SetBucketLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z TEXTEQU <__imp_?SetBucketLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z>
extern __imp_?SetDefaultSpinAdjustmentFactor@CCritSec@@SAXN@Z:PANYARGS
?SetDefaultSpinAdjustmentFactor@CCritSec@@SAXN@Z TEXTEQU <__imp_?SetDefaultSpinAdjustmentFactor@CCritSec@@SAXN@Z>
extern __imp_?SetDefaultSpinAdjustmentFactor@CFakeLock@@SAXN@Z:PANYARGS
?SetDefaultSpinAdjustmentFactor@CFakeLock@@SAXN@Z TEXTEQU <__imp_?SetDefaultSpinAdjustmentFactor@CFakeLock@@SAXN@Z>
extern __imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SAXN@Z:PANYARGS
?SetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SAXN@Z TEXTEQU <__imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SAXN@Z>
extern __imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SAXN@Z:PANYARGS
?SetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SAXN@Z TEXTEQU <__imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SAXN@Z>
extern __imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SAXN@Z:PANYARGS
?SetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SAXN@Z TEXTEQU <__imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SAXN@Z>
extern __imp_?SetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SAXN@Z:PANYARGS
?SetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SAXN@Z TEXTEQU <__imp_?SetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SAXN@Z>
extern __imp_?SetDefaultSpinAdjustmentFactor@CSpinLock@@SAXN@Z:PANYARGS
?SetDefaultSpinAdjustmentFactor@CSpinLock@@SAXN@Z TEXTEQU <__imp_?SetDefaultSpinAdjustmentFactor@CSpinLock@@SAXN@Z>
extern __imp_?SetDefaultSpinCount@CCritSec@@SAXG@Z:PANYARGS
?SetDefaultSpinCount@CCritSec@@SAXG@Z TEXTEQU <__imp_?SetDefaultSpinCount@CCritSec@@SAXG@Z>
extern __imp_?SetDefaultSpinCount@CFakeLock@@SAXG@Z:PANYARGS
?SetDefaultSpinCount@CFakeLock@@SAXG@Z TEXTEQU <__imp_?SetDefaultSpinCount@CFakeLock@@SAXG@Z>
extern __imp_?SetDefaultSpinCount@CReaderWriterLock2@@SAXG@Z:PANYARGS
?SetDefaultSpinCount@CReaderWriterLock2@@SAXG@Z TEXTEQU <__imp_?SetDefaultSpinCount@CReaderWriterLock2@@SAXG@Z>
extern __imp_?SetDefaultSpinCount@CReaderWriterLock3@@SAXG@Z:PANYARGS
?SetDefaultSpinCount@CReaderWriterLock3@@SAXG@Z TEXTEQU <__imp_?SetDefaultSpinCount@CReaderWriterLock3@@SAXG@Z>
extern __imp_?SetDefaultSpinCount@CReaderWriterLock@@SAXG@Z:PANYARGS
?SetDefaultSpinCount@CReaderWriterLock@@SAXG@Z TEXTEQU <__imp_?SetDefaultSpinCount@CReaderWriterLock@@SAXG@Z>
extern __imp_?SetDefaultSpinCount@CSmallSpinLock@@SAXG@Z:PANYARGS
?SetDefaultSpinCount@CSmallSpinLock@@SAXG@Z TEXTEQU <__imp_?SetDefaultSpinCount@CSmallSpinLock@@SAXG@Z>
extern __imp_?SetDefaultSpinCount@CSpinLock@@SAXG@Z:PANYARGS
?SetDefaultSpinCount@CSpinLock@@SAXG@Z TEXTEQU <__imp_?SetDefaultSpinCount@CSpinLock@@SAXG@Z>
extern __imp_?SetSpinCount@CCritSec@@QEAA_NG@Z:PANYARGS
?SetSpinCount@CCritSec@@QEAA_NG@Z TEXTEQU <__imp_?SetSpinCount@CCritSec@@QEAA_NG@Z>
extern __imp_?SetSpinCount@CCritSec@@SAKPEAPEAVCCriticalSection@@K@Z:PANYARGS
?SetSpinCount@CCritSec@@SAKPEAPEAVCCriticalSection@@K@Z TEXTEQU <__imp_?SetSpinCount@CCritSec@@SAKPEAPEAVCCriticalSection@@K@Z>
extern __imp_?SetSpinCount@CFakeLock@@QEAA_NG@Z:PANYARGS
?SetSpinCount@CFakeLock@@QEAA_NG@Z TEXTEQU <__imp_?SetSpinCount@CFakeLock@@QEAA_NG@Z>
extern __imp_?SetSpinCount@CReaderWriterLock2@@QEAA_NG@Z:PANYARGS
?SetSpinCount@CReaderWriterLock2@@QEAA_NG@Z TEXTEQU <__imp_?SetSpinCount@CReaderWriterLock2@@QEAA_NG@Z>
extern __imp_?SetSpinCount@CReaderWriterLock3@@QEAA_NG@Z:PANYARGS
?SetSpinCount@CReaderWriterLock3@@QEAA_NG@Z TEXTEQU <__imp_?SetSpinCount@CReaderWriterLock3@@QEAA_NG@Z>
extern __imp_?SetSpinCount@CReaderWriterLock@@QEAA_NG@Z:PANYARGS
?SetSpinCount@CReaderWriterLock@@QEAA_NG@Z TEXTEQU <__imp_?SetSpinCount@CReaderWriterLock@@QEAA_NG@Z>
extern __imp_?SetSpinCount@CSmallSpinLock@@QEAA_NG@Z:PANYARGS
?SetSpinCount@CSmallSpinLock@@QEAA_NG@Z TEXTEQU <__imp_?SetSpinCount@CSmallSpinLock@@QEAA_NG@Z>
extern __imp_?SetSpinCount@CSpinLock@@QEAA_NG@Z:PANYARGS
?SetSpinCount@CSpinLock@@QEAA_NG@Z TEXTEQU <__imp_?SetSpinCount@CSpinLock@@QEAA_NG@Z>
extern __imp_?SetTableLockSpinCount@CLKRHashTable@@QEAAXG@Z:PANYARGS
?SetTableLockSpinCount@CLKRHashTable@@QEAAXG@Z TEXTEQU <__imp_?SetTableLockSpinCount@CLKRHashTable@@QEAAXG@Z>
extern __imp_?SetTableLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z:PANYARGS
?SetTableLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z TEXTEQU <__imp_?SetTableLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z>
extern __imp_?Size@CLKRHashTable@@QEBAKXZ:PANYARGS
?Size@CLKRHashTable@@QEBAKXZ TEXTEQU <__imp_?Size@CLKRHashTable@@QEBAKXZ>
extern __imp_?Size@CLKRLinearHashTable@@QEBAKXZ:PANYARGS
?Size@CLKRLinearHashTable@@QEBAKXZ TEXTEQU <__imp_?Size@CLKRLinearHashTable@@QEBAKXZ>
extern __imp_?TryReadLock@CCritSec@@QEAA_NXZ:PANYARGS
?TryReadLock@CCritSec@@QEAA_NXZ TEXTEQU <__imp_?TryReadLock@CCritSec@@QEAA_NXZ>
extern __imp_?TryReadLock@CFakeLock@@QEAA_NXZ:PANYARGS
?TryReadLock@CFakeLock@@QEAA_NXZ TEXTEQU <__imp_?TryReadLock@CFakeLock@@QEAA_NXZ>
extern __imp_?TryReadLock@CReaderWriterLock2@@QEAA_NXZ:PANYARGS
?TryReadLock@CReaderWriterLock2@@QEAA_NXZ TEXTEQU <__imp_?TryReadLock@CReaderWriterLock2@@QEAA_NXZ>
extern __imp_?TryReadLock@CReaderWriterLock3@@QEAA_NXZ:PANYARGS
?TryReadLock@CReaderWriterLock3@@QEAA_NXZ TEXTEQU <__imp_?TryReadLock@CReaderWriterLock3@@QEAA_NXZ>
extern __imp_?TryReadLock@CReaderWriterLock@@QEAA_NXZ:PANYARGS
?TryReadLock@CReaderWriterLock@@QEAA_NXZ TEXTEQU <__imp_?TryReadLock@CReaderWriterLock@@QEAA_NXZ>
extern __imp_?TryReadLock@CSmallSpinLock@@QEAA_NXZ:PANYARGS
?TryReadLock@CSmallSpinLock@@QEAA_NXZ TEXTEQU <__imp_?TryReadLock@CSmallSpinLock@@QEAA_NXZ>
extern __imp_?TryReadLock@CSpinLock@@QEAA_NXZ:PANYARGS
?TryReadLock@CSpinLock@@QEAA_NXZ TEXTEQU <__imp_?TryReadLock@CSpinLock@@QEAA_NXZ>
extern __imp_?TryWriteLock@CCritSec@@QEAA_NXZ:PANYARGS
?TryWriteLock@CCritSec@@QEAA_NXZ TEXTEQU <__imp_?TryWriteLock@CCritSec@@QEAA_NXZ>
extern __imp_?TryWriteLock@CFakeLock@@QEAA_NXZ:PANYARGS
?TryWriteLock@CFakeLock@@QEAA_NXZ TEXTEQU <__imp_?TryWriteLock@CFakeLock@@QEAA_NXZ>
extern __imp_?TryWriteLock@CReaderWriterLock2@@QEAA_NXZ:PANYARGS
?TryWriteLock@CReaderWriterLock2@@QEAA_NXZ TEXTEQU <__imp_?TryWriteLock@CReaderWriterLock2@@QEAA_NXZ>
extern __imp_?TryWriteLock@CReaderWriterLock3@@QEAA_NXZ:PANYARGS
?TryWriteLock@CReaderWriterLock3@@QEAA_NXZ TEXTEQU <__imp_?TryWriteLock@CReaderWriterLock3@@QEAA_NXZ>
extern __imp_?TryWriteLock@CReaderWriterLock@@QEAA_NXZ:PANYARGS
?TryWriteLock@CReaderWriterLock@@QEAA_NXZ TEXTEQU <__imp_?TryWriteLock@CReaderWriterLock@@QEAA_NXZ>
extern __imp_?TryWriteLock@CSmallSpinLock@@QEAA_NXZ:PANYARGS
?TryWriteLock@CSmallSpinLock@@QEAA_NXZ TEXTEQU <__imp_?TryWriteLock@CSmallSpinLock@@QEAA_NXZ>
extern __imp_?TryWriteLock@CSpinLock@@QEAA_NXZ:PANYARGS
?TryWriteLock@CSpinLock@@QEAA_NXZ TEXTEQU <__imp_?TryWriteLock@CSpinLock@@QEAA_NXZ>
extern __imp_?UndoBackup@CEXAutoBackupFile@@QEAAJXZ:PANYARGS
?UndoBackup@CEXAutoBackupFile@@QEAAJXZ TEXTEQU <__imp_?UndoBackup@CEXAutoBackupFile@@QEAAJXZ>
extern __imp_?Unlock@CLockedDoubleList@@QEAAXXZ:PANYARGS
?Unlock@CLockedDoubleList@@QEAAXXZ TEXTEQU <__imp_?Unlock@CLockedDoubleList@@QEAAXXZ>
extern __imp_?Unlock@CLockedSingleList@@QEAAXXZ:PANYARGS
?Unlock@CLockedSingleList@@QEAAXXZ TEXTEQU <__imp_?Unlock@CLockedSingleList@@QEAAXXZ>
extern __imp_?ValidSignature@CLKRHashTable@@QEBA_NXZ:PANYARGS
?ValidSignature@CLKRHashTable@@QEBA_NXZ TEXTEQU <__imp_?ValidSignature@CLKRHashTable@@QEBA_NXZ>
extern __imp_?ValidSignature@CLKRLinearHashTable@@QEBA_NXZ:PANYARGS
?ValidSignature@CLKRLinearHashTable@@QEBA_NXZ TEXTEQU <__imp_?ValidSignature@CLKRLinearHashTable@@QEBA_NXZ>
extern __imp_?WaitType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PANYARGS
?WaitType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ TEXTEQU <__imp_?WaitType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>
extern __imp_?WaitType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PANYARGS
?WaitType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ TEXTEQU <__imp_?WaitType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>
extern __imp_?WaitType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_WAIT_TYPE@@XZ:PANYARGS
?WaitType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_WAIT_TYPE@@XZ TEXTEQU <__imp_?WaitType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_WAIT_TYPE@@XZ>
extern __imp_?WaitType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_WAIT_TYPE@@XZ:PANYARGS
?WaitType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_WAIT_TYPE@@XZ TEXTEQU <__imp_?WaitType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_WAIT_TYPE@@XZ>
extern __imp_?WaitType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PANYARGS
?WaitType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ TEXTEQU <__imp_?WaitType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>
extern __imp_?WaitType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PANYARGS
?WaitType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ TEXTEQU <__imp_?WaitType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>
extern __imp_?WaitType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PANYARGS
?WaitType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ TEXTEQU <__imp_?WaitType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>
extern __imp_?WriteLock@CCritSec@@QEAAXXZ:PANYARGS
?WriteLock@CCritSec@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CCritSec@@QEAAXXZ>
extern __imp_?WriteLock@CFakeLock@@QEAAXXZ:PANYARGS
?WriteLock@CFakeLock@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CFakeLock@@QEAAXXZ>
extern __imp_?WriteLock@CLKRHashTable@@QEAAXXZ:PANYARGS
?WriteLock@CLKRHashTable@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CLKRHashTable@@QEAAXXZ>
extern __imp_?WriteLock@CLKRLinearHashTable@@QEAAXXZ:PANYARGS
?WriteLock@CLKRLinearHashTable@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CLKRLinearHashTable@@QEAAXXZ>
extern __imp_?WriteLock@CReaderWriterLock2@@QEAAXXZ:PANYARGS
?WriteLock@CReaderWriterLock2@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CReaderWriterLock2@@QEAAXXZ>
extern __imp_?WriteLock@CReaderWriterLock3@@QEAAXXZ:PANYARGS
?WriteLock@CReaderWriterLock3@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CReaderWriterLock3@@QEAAXXZ>
extern __imp_?WriteLock@CReaderWriterLock@@QEAAXXZ:PANYARGS
?WriteLock@CReaderWriterLock@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CReaderWriterLock@@QEAAXXZ>
extern __imp_?WriteLock@CSmallSpinLock@@QEAAXXZ:PANYARGS
?WriteLock@CSmallSpinLock@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CSmallSpinLock@@QEAAXXZ>
extern __imp_?WriteLock@CSpinLock@@QEAAXXZ:PANYARGS
?WriteLock@CSpinLock@@QEAAXXZ TEXTEQU <__imp_?WriteLock@CSpinLock@@QEAAXXZ>
extern __imp_?WriteUnlock@CCritSec@@QEAAXXZ:PANYARGS
?WriteUnlock@CCritSec@@QEAAXXZ TEXTEQU <__imp_?WriteUnlock@CCritSec@@QEAAXXZ>
extern __imp_?WriteUnlock@CFakeLock@@QEAAXXZ:PANYARGS
?WriteUnlock@CFakeLock@@QEAAXXZ TEXTEQU <__imp_?WriteUnlock@CFakeLock@@QEAAXXZ>
extern __imp_?WriteUnlock@CLKRHashTable@@QEBAXXZ:PANYARGS
?WriteUnlock@CLKRHashTable@@QEBAXXZ TEXTEQU <__imp_?WriteUnlock@CLKRHashTable@@QEBAXXZ>
extern __imp_?WriteUnlock@CLKRLinearHashTable@@QEBAXXZ:PANYARGS
?WriteUnlock@CLKRLinearHashTable@@QEBAXXZ TEXTEQU <__imp_?WriteUnlock@CLKRLinearHashTable@@QEBAXXZ>
extern __imp_?WriteUnlock@CReaderWriterLock2@@QEAAXXZ:PANYARGS
?WriteUnlock@CReaderWriterLock2@@QEAAXXZ TEXTEQU <__imp_?WriteUnlock@CReaderWriterLock2@@QEAAXXZ>
extern __imp_?WriteUnlock@CReaderWriterLock3@@QEAAXXZ:PANYARGS
?WriteUnlock@CReaderWriterLock3@@QEAAXXZ TEXTEQU <__imp_?WriteUnlock@CReaderWriterLock3@@QEAAXXZ>
extern __imp_?WriteUnlock@CReaderWriterLock@@QEAAXXZ:PANYARGS
?WriteUnlock@CReaderWriterLock@@QEAAXXZ TEXTEQU <__imp_?WriteUnlock@CReaderWriterLock@@QEAAXXZ>
extern __imp_?WriteUnlock@CSmallSpinLock@@QEAAXXZ:PANYARGS
?WriteUnlock@CSmallSpinLock@@QEAAXXZ TEXTEQU <__imp_?WriteUnlock@CSmallSpinLock@@QEAAXXZ>
extern __imp_?WriteUnlock@CSpinLock@@QEAAXXZ:PANYARGS
?WriteUnlock@CSpinLock@@QEAAXXZ TEXTEQU <__imp_?WriteUnlock@CSpinLock@@QEAAXXZ>
extern __imp_?_AddRefRecord@CLKRLinearHashTable@@AEBAXPEBXH@Z:PANYARGS
?_AddRefRecord@CLKRLinearHashTable@@AEBAXPEBXH@Z TEXTEQU <__imp_?_AddRefRecord@CLKRLinearHashTable@@AEBAXPEBXH@Z>
extern __imp_?_AllocateNodeClump@CLKRLinearHashTable@@CAQEAVCNodeClump@1@XZ:PANYARGS
?_AllocateNodeClump@CLKRLinearHashTable@@CAQEAVCNodeClump@1@XZ TEXTEQU <__imp_?_AllocateNodeClump@CLKRLinearHashTable@@CAQEAVCNodeClump@1@XZ>
extern __imp_?_AllocateSegment@CLKRLinearHashTable@@AEBAQEAVCSegment@1@XZ:PANYARGS
?_AllocateSegment@CLKRLinearHashTable@@AEBAQEAVCSegment@1@XZ TEXTEQU <__imp_?_AllocateSegment@CLKRLinearHashTable@@AEBAQEAVCSegment@1@XZ>
extern __imp_?_AllocateSegmentDirectory@CLKRLinearHashTable@@CAQEAVCDirEntry@1@_K@Z:PANYARGS
?_AllocateSegmentDirectory@CLKRLinearHashTable@@CAQEAVCDirEntry@1@_K@Z TEXTEQU <__imp_?_AllocateSegmentDirectory@CLKRLinearHashTable@@CAQEAVCDirEntry@1@_K@Z>
extern __imp_?_AllocateSubTable@CLKRHashTable@@CAQEAVCLKRLinearHashTable@@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAV1@@Z:PANYARGS
?_AllocateSubTable@CLKRHashTable@@CAQEAVCLKRLinearHashTable@@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAV1@@Z TEXTEQU <__imp_?_AllocateSubTable@CLKRHashTable@@CAQEAVCLKRLinearHashTable@@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAV1@@Z>
extern __imp_?_AllocateSubTableArray@CLKRHashTable@@CAQEAPEAVCLKRLinearHashTable@@_K@Z:PANYARGS
?_AllocateSubTableArray@CLKRHashTable@@CAQEAPEAVCLKRLinearHashTable@@_K@Z TEXTEQU <__imp_?_AllocateSubTableArray@CLKRHashTable@@CAQEAPEAVCLKRLinearHashTable@@_K@Z>
extern __imp_?_Apply@CLKRLinearHashTable@@AEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@AEAW4LK_PREDICATE@@@Z:PANYARGS
?_Apply@CLKRLinearHashTable@@AEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@AEAW4LK_PREDICATE@@@Z TEXTEQU <__imp_?_Apply@CLKRLinearHashTable@@AEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@AEAW4LK_PREDICATE@@@Z>
extern __imp_?_ApplyIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@AEAW42@@Z:PANYARGS
?_ApplyIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@AEAW42@@Z TEXTEQU <__imp_?_ApplyIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@AEAW42@@Z>
extern __imp_?_Bucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K@Z:PANYARGS
?_Bucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K@Z TEXTEQU <__imp_?_Bucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K@Z>
extern __imp_?_BucketAddress@CLKRLinearHashTable@@AEBAKK@Z:PANYARGS
?_BucketAddress@CLKRLinearHashTable@@AEBAKK@Z TEXTEQU <__imp_?_BucketAddress@CLKRLinearHashTable@@AEBAKK@Z>
extern __imp_?_CalcKeyHash@CLKRHashTable@@AEBAK_K@Z:PANYARGS
?_CalcKeyHash@CLKRHashTable@@AEBAK_K@Z TEXTEQU <__imp_?_CalcKeyHash@CLKRHashTable@@AEBAK_K@Z>
extern __imp_?_CalcKeyHash@CLKRLinearHashTable@@AEBAK_K@Z:PANYARGS
?_CalcKeyHash@CLKRLinearHashTable@@AEBAK_K@Z TEXTEQU <__imp_?_CalcKeyHash@CLKRLinearHashTable@@AEBAK_K@Z>
extern __imp_?_Clear@CLKRLinearHashTable@@AEAAX_N@Z:PANYARGS
?_Clear@CLKRLinearHashTable@@AEAAX_N@Z TEXTEQU <__imp_?_Clear@CLKRLinearHashTable@@AEAAX_N@Z>
extern __imp_?_CloseIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?_CloseIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?_CloseIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?_CmpExch@CReaderWriterLock2@@AEAA_NJJ@Z:PANYARGS
?_CmpExch@CReaderWriterLock2@@AEAA_NJJ@Z TEXTEQU <__imp_?_CmpExch@CReaderWriterLock2@@AEAA_NJJ@Z>
extern __imp_?_CmpExch@CReaderWriterLock3@@AEAA_NJJ@Z:PANYARGS
?_CmpExch@CReaderWriterLock3@@AEAA_NJJ@Z TEXTEQU <__imp_?_CmpExch@CReaderWriterLock3@@AEAA_NJJ@Z>
extern __imp_?_CmpExch@CReaderWriterLock@@AEAA_NJJ@Z:PANYARGS
?_CmpExch@CReaderWriterLock@@AEAA_NJJ@Z TEXTEQU <__imp_?_CmpExch@CReaderWriterLock@@AEAA_NJJ@Z>
extern __imp_?_Contract@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ:PANYARGS
?_Contract@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ TEXTEQU <__imp_?_Contract@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ>
extern __imp_?_CurrentThreadId@CReaderWriterLock3@@CAJXZ:PANYARGS
?_CurrentThreadId@CReaderWriterLock3@@CAJXZ TEXTEQU <__imp_?_CurrentThreadId@CReaderWriterLock3@@CAJXZ>
extern __imp_?_CurrentThreadId@CSmallSpinLock@@CAJXZ:PANYARGS
?_CurrentThreadId@CSmallSpinLock@@CAJXZ TEXTEQU <__imp_?_CurrentThreadId@CSmallSpinLock@@CAJXZ>
extern __imp_?_CurrentThreadId@CSpinLock@@CAJXZ:PANYARGS
?_CurrentThreadId@CSpinLock@@CAJXZ TEXTEQU <__imp_?_CurrentThreadId@CSpinLock@@CAJXZ>
extern __imp_?_DeleteIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1AEAW42@@Z:PANYARGS
?_DeleteIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1AEAW42@@Z TEXTEQU <__imp_?_DeleteIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1AEAW42@@Z>
extern __imp_?_DeleteKey@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@_KK@Z:PANYARGS
?_DeleteKey@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@_KK@Z TEXTEQU <__imp_?_DeleteKey@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@_KK@Z>
extern __imp_?_DeleteNode@CLKRLinearHashTable@@AEAA_NPEAVCBucket@1@AEAPEAVCNodeClump@1@1AEAH@Z:PANYARGS
?_DeleteNode@CLKRLinearHashTable@@AEAA_NPEAVCBucket@1@AEAPEAVCNodeClump@1@1AEAH@Z TEXTEQU <__imp_?_DeleteNode@CLKRLinearHashTable@@AEAA_NPEAVCBucket@1@AEAPEAVCNodeClump@1@1AEAH@Z>
extern __imp_?_DeleteRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK@Z:PANYARGS
?_DeleteRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK@Z TEXTEQU <__imp_?_DeleteRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK@Z>
extern __imp_?_EqualKeys@CLKRLinearHashTable@@AEBA_N_K0@Z:PANYARGS
?_EqualKeys@CLKRLinearHashTable@@AEBA_N_K0@Z TEXTEQU <__imp_?_EqualKeys@CLKRLinearHashTable@@AEBA_N_K0@Z>
extern __imp_?_Expand@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ:PANYARGS
?_Expand@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ TEXTEQU <__imp_?_Expand@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ>
extern __imp_?_ExtractKey@CLKRHashTable@@AEBA?B_KPEBX@Z:PANYARGS
?_ExtractKey@CLKRHashTable@@AEBA?B_KPEBX@Z TEXTEQU <__imp_?_ExtractKey@CLKRHashTable@@AEBA?B_KPEBX@Z>
extern __imp_?_ExtractKey@CLKRLinearHashTable@@AEBA?B_KPEBX@Z:PANYARGS
?_ExtractKey@CLKRLinearHashTable@@AEBA?B_KPEBX@Z TEXTEQU <__imp_?_ExtractKey@CLKRLinearHashTable@@AEBA?B_KPEBX@Z>
extern __imp_?_FindBucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K_N@Z:PANYARGS
?_FindBucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K_N@Z TEXTEQU <__imp_?_FindBucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K_N@Z>
extern __imp_?_FindKey@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@_KKPEAPEBX@Z:PANYARGS
?_FindKey@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@_KKPEAPEBX@Z TEXTEQU <__imp_?_FindKey@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@_KKPEAPEBX@Z>
extern __imp_?_FindRecord@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@PEBXK@Z:PANYARGS
?_FindRecord@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@PEBXK@Z TEXTEQU <__imp_?_FindRecord@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@PEBXK@Z>
extern __imp_?_FreeNodeClump@CLKRLinearHashTable@@CA_NPEAVCNodeClump@1@@Z:PANYARGS
?_FreeNodeClump@CLKRLinearHashTable@@CA_NPEAVCNodeClump@1@@Z TEXTEQU <__imp_?_FreeNodeClump@CLKRLinearHashTable@@CA_NPEAVCNodeClump@1@@Z>
extern __imp_?_FreeSegment@CLKRLinearHashTable@@AEBA_NPEAVCSegment@1@@Z:PANYARGS
?_FreeSegment@CLKRLinearHashTable@@AEBA_NPEAVCSegment@1@@Z TEXTEQU <__imp_?_FreeSegment@CLKRLinearHashTable@@AEBA_NPEAVCSegment@1@@Z>
extern __imp_?_FreeSegmentDirectory@CLKRLinearHashTable@@CA_NPEAVCDirEntry@1@@Z:PANYARGS
?_FreeSegmentDirectory@CLKRLinearHashTable@@CA_NPEAVCDirEntry@1@@Z TEXTEQU <__imp_?_FreeSegmentDirectory@CLKRLinearHashTable@@CA_NPEAVCDirEntry@1@@Z>
extern __imp_?_FreeSubTable@CLKRHashTable@@CA_NPEAVCLKRLinearHashTable@@@Z:PANYARGS
?_FreeSubTable@CLKRHashTable@@CA_NPEAVCLKRLinearHashTable@@@Z TEXTEQU <__imp_?_FreeSubTable@CLKRHashTable@@CA_NPEAVCLKRLinearHashTable@@@Z>
extern __imp_?_FreeSubTableArray@CLKRHashTable@@CA_NPEAPEAVCLKRLinearHashTable@@@Z:PANYARGS
?_FreeSubTableArray@CLKRHashTable@@CA_NPEAPEAVCLKRLinearHashTable@@@Z TEXTEQU <__imp_?_FreeSubTableArray@CLKRHashTable@@CA_NPEAPEAVCLKRLinearHashTable@@@Z>
extern __imp_?_H0@CLKRLinearHashTable@@AEBAKK@Z:PANYARGS
?_H0@CLKRLinearHashTable@@AEBAKK@Z TEXTEQU <__imp_?_H0@CLKRLinearHashTable@@AEBAKK@Z>
extern __imp_?_H0@CLKRLinearHashTable@@CAKKK@Z:PANYARGS
?_H0@CLKRLinearHashTable@@CAKKK@Z TEXTEQU <__imp_?_H0@CLKRLinearHashTable@@CAKKK@Z>
extern __imp_?_H1@CLKRLinearHashTable@@AEBAKK@Z:PANYARGS
?_H1@CLKRLinearHashTable@@AEBAKK@Z TEXTEQU <__imp_?_H1@CLKRLinearHashTable@@AEBAKK@Z>
extern __imp_?_H1@CLKRLinearHashTable@@CAKKK@Z:PANYARGS
?_H1@CLKRLinearHashTable@@CAKKK@Z TEXTEQU <__imp_?_H1@CLKRLinearHashTable@@CAKKK@Z>
extern __imp_?_Initialize@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@P6A?B_KPEBX@ZP6AK_K@ZP6A_N22@ZP6AX0H@ZPEBDNK@Z:PANYARGS
?_Initialize@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@P6A?B_KPEBX@ZP6AK_K@ZP6A_N22@ZP6AX0H@ZPEBDNK@Z TEXTEQU <__imp_?_Initialize@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@P6A?B_KPEBX@ZP6AK_K@ZP6A_N22@ZP6AX0H@ZPEBDNK@Z>
extern __imp_?_InitializeIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PANYARGS
?_InitializeIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z TEXTEQU <__imp_?_InitializeIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>
extern __imp_?_InsertRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK_N@Z:PANYARGS
?_InsertRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK_N@Z TEXTEQU <__imp_?_InsertRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK_N@Z>
extern __imp_?_InsertThisIntoGlobalList@CLKRHashTable@@AEAAXXZ:PANYARGS
?_InsertThisIntoGlobalList@CLKRHashTable@@AEAAXXZ TEXTEQU <__imp_?_InsertThisIntoGlobalList@CLKRHashTable@@AEAAXXZ>
extern __imp_?_InsertThisIntoGlobalList@CLKRLinearHashTable@@AEAAXXZ:PANYARGS
?_InsertThisIntoGlobalList@CLKRLinearHashTable@@AEAAXXZ TEXTEQU <__imp_?_InsertThisIntoGlobalList@CLKRLinearHashTable@@AEAAXXZ>
extern __imp_?_IsLocked@CSpinLock@@AEBA_NXZ:PANYARGS
?_IsLocked@CSpinLock@@AEBA_NXZ TEXTEQU <__imp_?_IsLocked@CSpinLock@@AEBA_NXZ>
extern __imp_?_IsNodeCompact@CLKRLinearHashTable@@AEBAHQEAVCBucket@1@@Z:PANYARGS
?_IsNodeCompact@CLKRLinearHashTable@@AEBAHQEAVCBucket@1@@Z TEXTEQU <__imp_?_IsNodeCompact@CLKRLinearHashTable@@AEBAHQEAVCBucket@1@@Z>
extern __imp_?_Lock@CSpinLock@@AEAAXXZ:PANYARGS
?_Lock@CSpinLock@@AEAAXXZ TEXTEQU <__imp_?_Lock@CSpinLock@@AEAAXXZ>
extern __imp_?_LockSpin@CReaderWriterLock2@@AEAAX_N@Z:PANYARGS
?_LockSpin@CReaderWriterLock2@@AEAAX_N@Z TEXTEQU <__imp_?_LockSpin@CReaderWriterLock2@@AEAAX_N@Z>
extern __imp_?_LockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z:PANYARGS
?_LockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z TEXTEQU <__imp_?_LockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z>
extern __imp_?_LockSpin@CReaderWriterLock@@AEAAX_N@Z:PANYARGS
?_LockSpin@CReaderWriterLock@@AEAAX_N@Z TEXTEQU <__imp_?_LockSpin@CReaderWriterLock@@AEAAX_N@Z>
extern __imp_?_LockSpin@CSmallSpinLock@@AEAAXXZ:PANYARGS
?_LockSpin@CSmallSpinLock@@AEAAXXZ TEXTEQU <__imp_?_LockSpin@CSmallSpinLock@@AEAAXXZ>
extern __imp_?_LockSpin@CSpinLock@@AEAAXXZ:PANYARGS
?_LockSpin@CSpinLock@@AEAAXXZ TEXTEQU <__imp_?_LockSpin@CSpinLock@@AEAAXXZ>
extern __imp_?_MergeRecordSets@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCBucket@1@PEAVCNodeClump@1@1@Z:PANYARGS
?_MergeRecordSets@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCBucket@1@PEAVCNodeClump@1@1@Z TEXTEQU <__imp_?_MergeRecordSets@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCBucket@1@PEAVCNodeClump@1@1@Z>
extern __imp_?_PredTrue@CLKRLinearHashTable@@CA?AW4LK_PREDICATE@@PEBXPEAX@Z:PANYARGS
?_PredTrue@CLKRLinearHashTable@@CA?AW4LK_PREDICATE@@PEBXPEAX@Z TEXTEQU <__imp_?_PredTrue@CLKRLinearHashTable@@CA?AW4LK_PREDICATE@@PEBXPEAX@Z>
extern __imp_?_ReadLockSpin@CReaderWriterLock2@@AEAAXXZ:PANYARGS
?_ReadLockSpin@CReaderWriterLock2@@AEAAXXZ TEXTEQU <__imp_?_ReadLockSpin@CReaderWriterLock2@@AEAAXXZ>
extern __imp_?_ReadLockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z:PANYARGS
?_ReadLockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z TEXTEQU <__imp_?_ReadLockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z>
extern __imp_?_ReadLockSpin@CReaderWriterLock@@AEAAXXZ:PANYARGS
?_ReadLockSpin@CReaderWriterLock@@AEAAXXZ TEXTEQU <__imp_?_ReadLockSpin@CReaderWriterLock@@AEAAXXZ>
extern __imp_?_ReadOrWriteLock@CLKRLinearHashTable@@AEBA_NXZ:PANYARGS
?_ReadOrWriteLock@CLKRLinearHashTable@@AEBA_NXZ TEXTEQU <__imp_?_ReadOrWriteLock@CLKRLinearHashTable@@AEBA_NXZ>
extern __imp_?_ReadOrWriteUnlock@CLKRLinearHashTable@@AEBAX_N@Z:PANYARGS
?_ReadOrWriteUnlock@CLKRLinearHashTable@@AEBAX_N@Z TEXTEQU <__imp_?_ReadOrWriteUnlock@CLKRLinearHashTable@@AEBAX_N@Z>
extern __imp_?_RemoveThisFromGlobalList@CLKRHashTable@@AEAAXXZ:PANYARGS
?_RemoveThisFromGlobalList@CLKRHashTable@@AEAAXXZ TEXTEQU <__imp_?_RemoveThisFromGlobalList@CLKRHashTable@@AEAAXXZ>
extern __imp_?_RemoveThisFromGlobalList@CLKRLinearHashTable@@AEAAXXZ:PANYARGS
?_RemoveThisFromGlobalList@CLKRLinearHashTable@@AEAAXXZ TEXTEQU <__imp_?_RemoveThisFromGlobalList@CLKRLinearHashTable@@AEAAXXZ>
extern __imp_?_SegIndex@CLKRLinearHashTable@@AEBAKK@Z:PANYARGS
?_SegIndex@CLKRLinearHashTable@@AEBAKK@Z TEXTEQU <__imp_?_SegIndex@CLKRLinearHashTable@@AEBAKK@Z>
extern __imp_?_Segment@CLKRLinearHashTable@@AEBAAEAPEAVCSegment@1@K@Z:PANYARGS
?_Segment@CLKRLinearHashTable@@AEBAAEAPEAVCSegment@1@K@Z TEXTEQU <__imp_?_Segment@CLKRLinearHashTable@@AEBAAEAPEAVCSegment@1@K@Z>
extern __imp_?_SetSegVars@CLKRLinearHashTable@@AEAAXW4LK_TABLESIZE@@@Z:PANYARGS
?_SetSegVars@CLKRLinearHashTable@@AEAAXW4LK_TABLESIZE@@@Z TEXTEQU <__imp_?_SetSegVars@CLKRLinearHashTable@@AEAAXW4LK_TABLESIZE@@@Z>
extern __imp_?_SplitRecordSet@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCNodeClump@1@0KKK0@Z:PANYARGS
?_SplitRecordSet@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCNodeClump@1@0KKK0@Z TEXTEQU <__imp_?_SplitRecordSet@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCNodeClump@1@0KKK0@Z>
extern __imp_?_SubTable@CLKRHashTable@@AEBAPEAVCLKRLinearHashTable@@K@Z:PANYARGS
?_SubTable@CLKRHashTable@@AEBAPEAVCLKRLinearHashTable@@K@Z TEXTEQU <__imp_?_SubTable@CLKRHashTable@@AEBAPEAVCLKRLinearHashTable@@K@Z>
extern __imp_?_TryLock@CSmallSpinLock@@AEAA_NXZ:PANYARGS
?_TryLock@CSmallSpinLock@@AEAA_NXZ TEXTEQU <__imp_?_TryLock@CSmallSpinLock@@AEAA_NXZ>
extern __imp_?_TryLock@CSpinLock@@AEAA_NXZ:PANYARGS
?_TryLock@CSpinLock@@AEAA_NXZ TEXTEQU <__imp_?_TryLock@CSpinLock@@AEAA_NXZ>
extern __imp_?_TryReadLock@CReaderWriterLock2@@AEAA_NXZ:PANYARGS
?_TryReadLock@CReaderWriterLock2@@AEAA_NXZ TEXTEQU <__imp_?_TryReadLock@CReaderWriterLock2@@AEAA_NXZ>
extern __imp_?_TryReadLock@CReaderWriterLock3@@AEAA_NXZ:PANYARGS
?_TryReadLock@CReaderWriterLock3@@AEAA_NXZ TEXTEQU <__imp_?_TryReadLock@CReaderWriterLock3@@AEAA_NXZ>
extern __imp_?_TryReadLock@CReaderWriterLock@@AEAA_NXZ:PANYARGS
?_TryReadLock@CReaderWriterLock@@AEAA_NXZ TEXTEQU <__imp_?_TryReadLock@CReaderWriterLock@@AEAA_NXZ>
extern __imp_?_TryReadLockRecursive@CReaderWriterLock3@@AEAA_NXZ:PANYARGS
?_TryReadLockRecursive@CReaderWriterLock3@@AEAA_NXZ TEXTEQU <__imp_?_TryReadLockRecursive@CReaderWriterLock3@@AEAA_NXZ>
extern __imp_?_TryWriteLock2@CReaderWriterLock3@@AEAA_NXZ:PANYARGS
?_TryWriteLock2@CReaderWriterLock3@@AEAA_NXZ TEXTEQU <__imp_?_TryWriteLock2@CReaderWriterLock3@@AEAA_NXZ>
extern __imp_?_TryWriteLock@CReaderWriterLock2@@AEAA_NJ@Z:PANYARGS
?_TryWriteLock@CReaderWriterLock2@@AEAA_NJ@Z TEXTEQU <__imp_?_TryWriteLock@CReaderWriterLock2@@AEAA_NJ@Z>
extern __imp_?_TryWriteLock@CReaderWriterLock3@@AEAA_NJ@Z:PANYARGS
?_TryWriteLock@CReaderWriterLock3@@AEAA_NJ@Z TEXTEQU <__imp_?_TryWriteLock@CReaderWriterLock3@@AEAA_NJ@Z>
extern __imp_?_TryWriteLock@CReaderWriterLock@@AEAA_NXZ:PANYARGS
?_TryWriteLock@CReaderWriterLock@@AEAA_NXZ TEXTEQU <__imp_?_TryWriteLock@CReaderWriterLock@@AEAA_NXZ>
extern __imp_?_Unlock@CSpinLock@@AEAAXXZ:PANYARGS
?_Unlock@CSpinLock@@AEAAXXZ TEXTEQU <__imp_?_Unlock@CSpinLock@@AEAAXXZ>
extern __imp_?_WriteLockSpin@CReaderWriterLock2@@AEAAXXZ:PANYARGS
?_WriteLockSpin@CReaderWriterLock2@@AEAAXXZ TEXTEQU <__imp_?_WriteLockSpin@CReaderWriterLock2@@AEAAXXZ>
extern __imp_?_WriteLockSpin@CReaderWriterLock3@@AEAAXXZ:PANYARGS
?_WriteLockSpin@CReaderWriterLock3@@AEAAXXZ TEXTEQU <__imp_?_WriteLockSpin@CReaderWriterLock3@@AEAAXXZ>
extern __imp_?_WriteLockSpin@CReaderWriterLock@@AEAAXXZ:PANYARGS
?_WriteLockSpin@CReaderWriterLock@@AEAAXXZ TEXTEQU <__imp_?_WriteLockSpin@CReaderWriterLock@@AEAAXXZ>
extern __imp_?_getFileSecurity@CExFileOperation@@AEAAJPEBG@Z:PANYARGS
?_getFileSecurity@CExFileOperation@@AEAAJPEBG@Z TEXTEQU <__imp_?_getFileSecurity@CExFileOperation@@AEAAJPEBG@Z>
extern __imp_?_setFileSecurity@CExFileOperation@@AEAAJPEBG@Z:PANYARGS
?_setFileSecurity@CExFileOperation@@AEAAJPEBG@Z TEXTEQU <__imp_?_setFileSecurity@CExFileOperation@@AEAAJPEBG@Z>
extern __imp_?fHaveBackup@CEXAutoBackupFile@@QEAAHXZ:PANYARGS
?fHaveBackup@CEXAutoBackupFile@@QEAAHXZ TEXTEQU <__imp_?fHaveBackup@CEXAutoBackupFile@@QEAAHXZ>
extern __imp_?s_aBucketSizes@?1??BucketSizes@CLKRHashTableStats@@SAPEBJXZ@4QBJB:PANYARGS
?s_aBucketSizes@?1??BucketSizes@CLKRHashTableStats@@SAPEBJXZ@4QBJB TEXTEQU <__imp_?s_aBucketSizes@?1??BucketSizes@CLKRHashTableStats@@SAPEBJXZ@4QBJB>
extern __imp_?sm_dblDfltSpinAdjFctr@CCritSec@@1NA:PANYARGS
?sm_dblDfltSpinAdjFctr@CCritSec@@1N  TEXTEQU <__imp_?sm_dblDfltSpinAdjFctr@CCritSec@@1NA>
extern __imp_?sm_dblDfltSpinAdjFctr@CFakeLock@@1NA:PANYARGS
?sm_dblDfltSpinAdjFctr@CFakeLock@@1N  TEXTEQU <__imp_?sm_dblDfltSpinAdjFctr@CFakeLock@@1NA>
extern __imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1NA:PANYARGS
?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1N  TEXTEQU <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1NA>
extern __imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1NA:PANYARGS
?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1N  TEXTEQU <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1NA>
extern __imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1NA:PANYARGS
?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1N  TEXTEQU <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1NA>
extern __imp_?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1NA:PANYARGS
?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1N  TEXTEQU <__imp_?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1NA>
extern __imp_?sm_dblDfltSpinAdjFctr@CSpinLock@@1NA:PANYARGS
?sm_dblDfltSpinAdjFctr@CSpinLock@@1N  TEXTEQU <__imp_?sm_dblDfltSpinAdjFctr@CSpinLock@@1NA>
extern __imp_?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@A:PANYARGS
?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@  TEXTEQU <__imp_?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@A>
extern __imp_?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@A:PANYARGS
?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@  TEXTEQU <__imp_?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@A>
extern __imp_?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@EA:PANYARGS
?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@E  TEXTEQU <__imp_?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@EA>
extern __imp_?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZEA:PANYARGS
?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZE  TEXTEQU <__imp_?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZEA>
extern __imp_?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZEA:PANYARGS
?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZE  TEXTEQU <__imp_?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZEA>
extern __imp_?sm_wDefaultSpinCount@CCritSec@@1GA:PANYARGS
?sm_wDefaultSpinCount@CCritSec@@1G  TEXTEQU <__imp_?sm_wDefaultSpinCount@CCritSec@@1GA>
extern __imp_?sm_wDefaultSpinCount@CFakeLock@@1GA:PANYARGS
?sm_wDefaultSpinCount@CFakeLock@@1G  TEXTEQU <__imp_?sm_wDefaultSpinCount@CFakeLock@@1GA>
extern __imp_?sm_wDefaultSpinCount@CReaderWriterLock2@@1GA:PANYARGS
?sm_wDefaultSpinCount@CReaderWriterLock2@@1G  TEXTEQU <__imp_?sm_wDefaultSpinCount@CReaderWriterLock2@@1GA>
extern __imp_?sm_wDefaultSpinCount@CReaderWriterLock3@@1GA:PANYARGS
?sm_wDefaultSpinCount@CReaderWriterLock3@@1G  TEXTEQU <__imp_?sm_wDefaultSpinCount@CReaderWriterLock3@@1GA>
extern __imp_?sm_wDefaultSpinCount@CReaderWriterLock@@1GA:PANYARGS
?sm_wDefaultSpinCount@CReaderWriterLock@@1G  TEXTEQU <__imp_?sm_wDefaultSpinCount@CReaderWriterLock@@1GA>
extern __imp_?sm_wDefaultSpinCount@CSmallSpinLock@@1GA:PANYARGS
?sm_wDefaultSpinCount@CSmallSpinLock@@1G  TEXTEQU <__imp_?sm_wDefaultSpinCount@CSmallSpinLock@@1GA>
extern __imp_?sm_wDefaultSpinCount@CSpinLock@@1GA:PANYARGS
?sm_wDefaultSpinCount@CSpinLock@@1G  TEXTEQU <__imp_?sm_wDefaultSpinCount@CSpinLock@@1GA>
extern __imp_DllBidEntryPoint:PANYARGS
DllBidEntryPoint TEXTEQU <__imp_DllBidEntryPoint>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_FXMemAttach:PANYARGS
FXMemAttach TEXTEQU <__imp_FXMemAttach>
extern __imp_FXMemDetach:PANYARGS
FXMemDetach TEXTEQU <__imp_FXMemDetach>
extern __imp_GetIUMS:PANYARGS
GetIUMS TEXTEQU <__imp_GetIUMS>
extern __imp_IrtlTrace:PANYARGS
IrtlTrace TEXTEQU <__imp_IrtlTrace>
extern __imp_IsValidAddress:PANYARGS
IsValidAddress TEXTEQU <__imp_IsValidAddress>
extern __imp_IsValidString:PANYARGS
IsValidString TEXTEQU <__imp_IsValidString>
extern __imp_LoadVersionedResourceEx:PANYARGS
LoadVersionedResourceEx TEXTEQU <__imp_LoadVersionedResourceEx>
extern __imp_MPCSInitialize:PANYARGS
MPCSInitialize TEXTEQU <__imp_MPCSInitialize>
extern __imp_MPCSUninitialize:PANYARGS
MPCSUninitialize TEXTEQU <__imp_MPCSUninitialize>
extern __imp_MPDeleteCriticalSection:PANYARGS
MPDeleteCriticalSection TEXTEQU <__imp_MPDeleteCriticalSection>
extern __imp_MPInitializeCriticalSection:PANYARGS
MPInitializeCriticalSection TEXTEQU <__imp_MPInitializeCriticalSection>
extern __imp_MPInitializeCriticalSectionAndSpinCount:PANYARGS
MPInitializeCriticalSectionAndSpinCount TEXTEQU <__imp_MPInitializeCriticalSectionAndSpinCount>
extern __imp_MpGetHeapHandle:PANYARGS
MpGetHeapHandle TEXTEQU <__imp_MpGetHeapHandle>
extern __imp_MpHeapAlloc:PANYARGS
MpHeapAlloc TEXTEQU <__imp_MpHeapAlloc>
extern __imp_MpHeapCreate:PANYARGS
MpHeapCreate TEXTEQU <__imp_MpHeapCreate>
extern __imp_MpHeapDestroy:PANYARGS
MpHeapDestroy TEXTEQU <__imp_MpHeapDestroy>
extern __imp_MpHeapFree:PANYARGS
MpHeapFree TEXTEQU <__imp_MpHeapFree>
extern __imp_MpHeapReAlloc:PANYARGS
MpHeapReAlloc TEXTEQU <__imp_MpHeapReAlloc>
extern __imp_MpHeapSize:PANYARGS
MpHeapSize TEXTEQU <__imp_MpHeapSize>
extern __imp_MpHeapValidate:PANYARGS
MpHeapValidate TEXTEQU <__imp_MpHeapValidate>
extern __imp_SetIUMS:PANYARGS
SetIUMS TEXTEQU <__imp_SetIUMS>
extern __imp_SetMemHook:PANYARGS
SetMemHook TEXTEQU <__imp_SetMemHook>
extern __imp_UMSEnterCSWraper:PANYARGS
UMSEnterCSWraper TEXTEQU <__imp_UMSEnterCSWraper>
extern __imp_mpCalloc:PANYARGS
mpCalloc TEXTEQU <__imp_mpCalloc>
extern __imp_mpFree:PANYARGS
mpFree TEXTEQU <__imp_mpFree>
extern __imp_mpMalloc:PANYARGS
mpMalloc TEXTEQU <__imp_mpMalloc>
extern __imp_mpRealloc:PANYARGS
mpRealloc TEXTEQU <__imp_mpRealloc>
