extern __imp_DMOEnum:PANYARGS
DMOEnum TEXTEQU <__imp_DMOEnum>
extern __imp_DMOGetName:PANYARGS
DMOGetName TEXTEQU <__imp_DMOGetName>
extern __imp_DMOGetTypes:PANYARGS
DMOGetTypes TEXTEQU <__imp_DMOGetTypes>
extern __imp_DMOGuidToStrA:PANYARGS
DMOGuidToStr  TEXTEQU <__imp_DMOGuidToStrA>
extern __imp_DMOGuidToStrW:PANYARGS
DMOGuidToStrW TEXTEQU <__imp_DMOGuidToStrW>
extern __imp_DMORegister:PANYARGS
DMORegister TEXTEQU <__imp_DMORegister>
extern __imp_DMOStrToGuidA:PANYARGS
DMOStrToGuid  TEXTEQU <__imp_DMOStrToGuidA>
extern __imp_DMOStrToGuidW:PANYARGS
DMOStrToGuidW TEXTEQU <__imp_DMOStrToGuidW>
extern __imp_DMOUnregister:PANYARGS
DMOUnregister TEXTEQU <__imp_DMOUnregister>
extern __imp_MoCopyMediaType:PANYARGS
MoCopyMediaType TEXTEQU <__imp_MoCopyMediaType>
extern __imp_MoCreateMediaType:PANYARGS
MoCreateMediaType TEXTEQU <__imp_MoCreateMediaType>
extern __imp_MoDeleteMediaType:PANYARGS
MoDeleteMediaType TEXTEQU <__imp_MoDeleteMediaType>
extern __imp_MoDuplicateMediaType:PANYARGS
MoDuplicateMediaType TEXTEQU <__imp_MoDuplicateMediaType>
extern __imp_MoFreeMediaType:PANYARGS
MoFreeMediaType TEXTEQU <__imp_MoFreeMediaType>
extern __imp_MoInitMediaType:PANYARGS
MoInitMediaType TEXTEQU <__imp_MoInitMediaType>
