extern __imp_DtcMainExt:PANYARGS
DtcMainExt TEXTEQU <__imp_DtcMainExt>
extern __imp_ASCWrapObject:PANYARGS
ASCWrapObject TEXTEQU <__imp_ASCWrapObject>
extern __imp_ASCDeliverDeferred:PANYARGS
ASCDeliverDeferred TEXTEQU <__imp_ASCDeliverDeferred>
extern __imp_ASCDefer:PANYARGS
ASCDefer TEXTEQU <__imp_ASCDefer>
extern __imp_ASCGetSafeReference:PANYARGS
ASCGetSafeReference TEXTEQU <__imp_ASCGetSafeReference>
extern __imp_?Create@CUISCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PANYARGS
?Create@CUISCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z TEXTEQU <__imp_?Create@CUISCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z>
extern __imp_?CreateInstance@CTm@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PANYARGS
?CreateInstance@CTm@@SAJPEAPEAV1@PEAUIUnknown@@@Z TEXTEQU <__imp_?CreateInstance@CTm@@SAJPEAPEAV1@PEAUIUnknown@@@Z>
extern __imp_?CreateInstance@CXaTmCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PANYARGS
?CreateInstance@CXaTmCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z TEXTEQU <__imp_?CreateInstance@CXaTmCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z>
extern __imp_?CreateThreadPool@@YAJXZ:PANYARGS
?CreateThreadPool@@YAJXZ TEXTEQU <__imp_?CreateThreadPool@@YAJXZ>
extern __imp_ASCWrapClassFactory:PANYARGS
ASCWrapClassFactory TEXTEQU <__imp_ASCWrapClassFactory>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetTipFunctionalityWorking:PANYARGS
GetTipFunctionalityWorking TEXTEQU <__imp_GetTipFunctionalityWorking>
extern __imp_SetTipFunctionalityWorking:PANYARGS
SetTipFunctionalityWorking TEXTEQU <__imp_SetTipFunctionalityWorking>
