extern __imp_InitDACDLL:PANYARGS
InitDACDLL TEXTEQU <__imp_InitDACDLL>
extern __imp_TermDACDLL:PANYARGS
TermDACDLL TEXTEQU <__imp_TermDACDLL>
extern __imp_TermDACInstance:PANYARGS
TermDACInstance TEXTEQU <__imp_TermDACInstance>
extern __imp_DoDACPropSheet:PANYARGS
DoDACPropSheet TEXTEQU <__imp_DoDACPropSheet>
extern __imp_DoDACAdvanced:PANYARGS
DoDACAdvanced TEXTEQU <__imp_DoDACAdvanced>
extern __imp_GetDACStatsMinMaxInfo:PANYARGS
GetDACStatsMinMaxInfo TEXTEQU <__imp_GetDACStatsMinMaxInfo>
extern __imp_??0CDac@@QEAA@AEBV0@@Z:PANYARGS
??0CDac@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CDac@@QEAA@AEBV0@@Z>
extern __imp_??0CDac@@QEAA@K@Z:PANYARGS
??0CDac@@QEAA@K@Z TEXTEQU <__imp_??0CDac@@QEAA@K@Z>
extern __imp_??1CDac@@QEAA@XZ:PANYARGS
??1CDac@@QEAA@XZ TEXTEQU <__imp_??1CDac@@QEAA@XZ>
extern __imp_??4CDac@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CDac@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CDac@@QEAAAEAV0@AEBV0@@Z>
extern __imp_?Connect@CDac@@QEAAHPEAUHWND__@@PEAUINTServiceControl@@@Z:PANYARGS
?Connect@CDac@@QEAAHPEAUHWND__@@PEAUINTServiceControl@@@Z TEXTEQU <__imp_?Connect@CDac@@QEAAHPEAUHWND__@@PEAUINTServiceControl@@@Z>
extern __imp_?Create@CUicCore@@SAJPEAPEAV1@@Z:PANYARGS
?Create@CUicCore@@SAJPEAPEAV1@@Z TEXTEQU <__imp_?Create@CUicCore@@SAJPEAPEAV1@@Z>
extern __imp_?CreateAdvancedPropertySheet@CDac@@QEAAPEAVCDialog@@PEAVCWnd@@@Z:PANYARGS
?CreateAdvancedPropertySheet@CDac@@QEAAPEAVCDialog@@PEAVCWnd@@@Z TEXTEQU <__imp_?CreateAdvancedPropertySheet@CDac@@QEAAPEAVCDialog@@PEAVCWnd@@@Z>
extern __imp_?ErrorMessage@CDac@@QEAAHKI@Z:PANYARGS
?ErrorMessage@CDac@@QEAAHKI@Z TEXTEQU <__imp_?ErrorMessage@CDac@@QEAAHKI@Z>
extern __imp_?GetAdminAccess@CDac@@QEAAKXZ:PANYARGS
?GetAdminAccess@CDac@@QEAAKXZ TEXTEQU <__imp_?GetAdminAccess@CDac@@QEAAKXZ>
extern __imp_?GetHostNameA@CDac@@QEAAPEADXZ:PANYARGS
?GetHostNameA@CDac@@QEAAPEADXZ TEXTEQU <__imp_?GetHostNameA@CDac@@QEAAPEADXZ>
extern __imp_?GetHostNameW@CDac@@QEAAPEAGXZ:PANYARGS
?GetHostNameW@CDac@@QEAAPEAGXZ TEXTEQU <__imp_?GetHostNameW@CDac@@QEAAPEAGXZ>
extern __imp_?GetOwnerHwnd@CDac@@QEAAPEAUHWND__@@XZ:PANYARGS
?GetOwnerHwnd@CDac@@QEAAPEAUHWND__@@XZ TEXTEQU <__imp_?GetOwnerHwnd@CDac@@QEAAPEAUHWND__@@XZ>
extern __imp_?GetVirtualHostName@CDac@@QEAAPEAGXZ:PANYARGS
?GetVirtualHostName@CDac@@QEAAPEAGXZ TEXTEQU <__imp_?GetVirtualHostName@CDac@@QEAAPEAGXZ>
extern __imp_?Init@CDac@@QEAAJPEAG@Z:PANYARGS
?Init@CDac@@QEAAJPEAG@Z TEXTEQU <__imp_?Init@CDac@@QEAAJPEAG@Z>
extern __imp_?IsConnected@CDac@@QEAAHXZ:PANYARGS
?IsConnected@CDac@@QEAAHXZ TEXTEQU <__imp_?IsConnected@CDac@@QEAAHXZ>
extern __imp_?ProcessCommand@CDac@@QEAAH_K_J@Z:PANYARGS
?ProcessCommand@CDac@@QEAAH_K_J@Z TEXTEQU <__imp_?ProcessCommand@CDac@@QEAAH_K_J@Z>
extern __imp_?RegisterErrorSink@@YAXPEAUIDacErrorSink@@@Z:PANYARGS
?RegisterErrorSink@@YAXPEAUIDacErrorSink@@@Z TEXTEQU <__imp_?RegisterErrorSink@@YAXPEAUIDacErrorSink@@@Z>
extern __imp_RunDACExe:PANYARGS
RunDACExe TEXTEQU <__imp_RunDACExe>
extern __imp_?ServiceRequest@CDac@@QEAAJKPEAXK_N@Z:PANYARGS
?ServiceRequest@CDac@@QEAAJKPEAXK_N@Z TEXTEQU <__imp_?ServiceRequest@CDac@@QEAAJKPEAXK_N@Z>
extern __imp_?SetHostNameA@CDac@@QEAAXPEAD@Z:PANYARGS
?SetHostNameA@CDac@@QEAAXPEAD@Z TEXTEQU <__imp_?SetHostNameA@CDac@@QEAAXPEAD@Z>
extern __imp_?SetHostNameW@CDac@@QEAAXPEAG@Z:PANYARGS
?SetHostNameW@CDac@@QEAAXPEAG@Z TEXTEQU <__imp_?SetHostNameW@CDac@@QEAAXPEAG@Z>
extern __imp_?SetOwnerWnd@CDac@@QEAAXPEAVCWnd@@@Z:PANYARGS
?SetOwnerWnd@CDac@@QEAAXPEAVCWnd@@@Z TEXTEQU <__imp_?SetOwnerWnd@CDac@@QEAAXPEAVCWnd@@@Z>
extern __imp_?ValidateDACInstance@@YAPEAVCDac@@PEAPEAXPEAG@Z:PANYARGS
?ValidateDACInstance@@YAPEAVCDac@@PEAPEAXPEAG@Z TEXTEQU <__imp_?ValidateDACInstance@@YAPEAVCDac@@PEAPEAXPEAG@Z>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllGetDTCUIC:PANYARGS
DllGetDTCUIC TEXTEQU <__imp_DllGetDTCUIC>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_DtcPerfClose:PANYARGS
DtcPerfClose TEXTEQU <__imp_DtcPerfClose>
extern __imp_DtcPerfCollect:PANYARGS
DtcPerfCollect TEXTEQU <__imp_DtcPerfCollect>
extern __imp_DtcPerfOpen:PANYARGS
DtcPerfOpen TEXTEQU <__imp_DtcPerfOpen>
extern __imp_PerfDllRegisterServer:PANYARGS
PerfDllRegisterServer TEXTEQU <__imp_PerfDllRegisterServer>
extern __imp_ShutDownUIC:PANYARGS
ShutDownUIC TEXTEQU <__imp_ShutDownUIC>
