extern __imp_DllGetDTCProxy:PANYARGS
DllGetDTCProxy TEXTEQU <__imp_DllGetDTCProxy>
extern __imp_??0CSecurityDescriptor@@QEAA@XZ:PANYARGS
??0CSecurityDescriptor@@QEAA@XZ TEXTEQU <__imp_??0CSecurityDescriptor@@QEAA@XZ>
extern __imp_??0CService@@IEAA@XZ:PANYARGS
??0CService@@IEAA@XZ TEXTEQU <__imp_??0CService@@IEAA@XZ>
extern __imp_??0CServiceControlManager@@IEAA@XZ:PANYARGS
??0CServiceControlManager@@IEAA@XZ TEXTEQU <__imp_??0CServiceControlManager@@IEAA@XZ>
extern __imp_??1CSecurityDescriptor@@QEAA@XZ:PANYARGS
??1CSecurityDescriptor@@QEAA@XZ TEXTEQU <__imp_??1CSecurityDescriptor@@QEAA@XZ>
extern __imp_??1CService@@IEAA@XZ:PANYARGS
??1CService@@IEAA@XZ TEXTEQU <__imp_??1CService@@IEAA@XZ>
extern __imp_DTC_XaOpen:PANYARGS
DTC_XaOpen TEXTEQU <__imp_DTC_XaOpen>
extern __imp_DTC_XaStart:PANYARGS
DTC_XaStart TEXTEQU <__imp_DTC_XaStart>
extern __imp_DTC_XaEnd:PANYARGS
DTC_XaEnd TEXTEQU <__imp_DTC_XaEnd>
extern __imp_DTC_XaPrepare:PANYARGS
DTC_XaPrepare TEXTEQU <__imp_DTC_XaPrepare>
extern __imp_DTC_XaCommit:PANYARGS
DTC_XaCommit TEXTEQU <__imp_DTC_XaCommit>
extern __imp_DTC_XaRollback:PANYARGS
DTC_XaRollback TEXTEQU <__imp_DTC_XaRollback>
extern __imp_DTC_XaRecover:PANYARGS
DTC_XaRecover TEXTEQU <__imp_DTC_XaRecover>
extern __imp_DTC_XaForget:PANYARGS
DTC_XaForget TEXTEQU <__imp_DTC_XaForget>
extern __imp_DTC_XaComplete:PANYARGS
DTC_XaComplete TEXTEQU <__imp_DTC_XaComplete>
extern __imp_DTC_XaClose:PANYARGS
DTC_XaClose TEXTEQU <__imp_DTC_XaClose>
extern __imp_DTC_AxReg:PANYARGS
DTC_AxReg TEXTEQU <__imp_DTC_AxReg>
extern __imp_DTC_AxUnReg:PANYARGS
DTC_AxUnReg TEXTEQU <__imp_DTC_AxUnReg>
extern __imp_ax_reg:PANYARGS
ax_reg TEXTEQU <__imp_ax_reg>
extern __imp_ax_unreg:PANYARGS
ax_unreg TEXTEQU <__imp_ax_unreg>
extern __imp_ShutDownCM:PANYARGS
ShutDownCM TEXTEQU <__imp_ShutDownCM>
extern __imp_DllGetDTCConnectionManager:PANYARGS
DllGetDTCConnectionManager TEXTEQU <__imp_DllGetDTCConnectionManager>
extern __imp_DllGetDTCUtilObject:PANYARGS
DllGetDTCUtilObject TEXTEQU <__imp_DllGetDTCUtilObject>
extern __imp_ContactToNameObject:PANYARGS
ContactToNameObject TEXTEQU <__imp_ContactToNameObject>
extern __imp_SysPrepDtcReinstall:PANYARGS
SysPrepDtcReinstall TEXTEQU <__imp_SysPrepDtcReinstall>
extern __imp_??1CServiceControlManager@@IEAA@XZ:PANYARGS
??1CServiceControlManager@@IEAA@XZ TEXTEQU <__imp_??1CServiceControlManager@@IEAA@XZ>
extern __imp_??4CSecurityDescriptor@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CSecurityDescriptor@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CSecurityDescriptor@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CService@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CService@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CService@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CServiceControlManager@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CServiceControlManager@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CServiceControlManager@@QEAAAEAV0@AEBV0@@Z>
extern __imp_?AddRef@CService@@QEAAKXZ:PANYARGS
?AddRef@CService@@QEAAKXZ TEXTEQU <__imp_?AddRef@CService@@QEAAKXZ>
extern __imp_?AddRef@CServiceControlManager@@QEAAKXZ:PANYARGS
?AddRef@CServiceControlManager@@QEAAKXZ TEXTEQU <__imp_?AddRef@CServiceControlManager@@QEAAKXZ>
extern __imp_?AddSid@CSecurityDescriptor@@QEAAJPEAGKK@Z:PANYARGS
?AddSid@CSecurityDescriptor@@QEAAJPEAGKK@Z TEXTEQU <__imp_?AddSid@CSecurityDescriptor@@QEAAJPEAGKK@Z>
extern __imp_?AddSid@CSecurityDescriptor@@QEAAJPEAXKK@Z:PANYARGS
?AddSid@CSecurityDescriptor@@QEAAJPEAXKK@Z TEXTEQU <__imp_?AddSid@CSecurityDescriptor@@QEAAJPEAXKK@Z>
extern __imp_?Alloc@CSecurityDescriptor@@IEAAJK@Z:PANYARGS
?Alloc@CSecurityDescriptor@@IEAAJK@Z TEXTEQU <__imp_?Alloc@CSecurityDescriptor@@IEAAJK@Z>
extern __imp_?ApplyAccountSettings@@YAJHPEAGK000H@Z:PANYARGS
?ApplyAccountSettings@@YAJHPEAGK000H@Z TEXTEQU <__imp_?ApplyAccountSettings@@YAJHPEAGK000H@Z>
extern __imp_?ApplyNamedSecurityChange@@YAJPEAGW4_SE_OBJECT_TYPE@@PEAX2K@Z:PANYARGS
?ApplyNamedSecurityChange@@YAJPEAGW4_SE_OBJECT_TYPE@@PEAX2K@Z TEXTEQU <__imp_?ApplyNamedSecurityChange@@YAJPEAGW4_SE_OBJECT_TYPE@@PEAX2K@Z>
extern __imp_?CheckForDCPromotionDemotion@@YAJPEAG@Z:PANYARGS
?CheckForDCPromotionDemotion@@YAJPEAG@Z TEXTEQU <__imp_?CheckForDCPromotionDemotion@@YAJPEAG@Z>
extern __imp_?ClearAcl@CSecurityDescriptor@@QEAAJXZ:PANYARGS
?ClearAcl@CSecurityDescriptor@@QEAAJXZ TEXTEQU <__imp_?ClearAcl@CSecurityDescriptor@@QEAAJXZ>
extern __imp_?ClearInMemoryAcl@CSecurityDescriptor@@QEAAJXZ:PANYARGS
?ClearInMemoryAcl@CSecurityDescriptor@@QEAAJXZ TEXTEQU <__imp_?ClearInMemoryAcl@CSecurityDescriptor@@QEAAJXZ>
extern __imp_?CloseNetpEventLogHandle@@YAXXZ:PANYARGS
?CloseNetpEventLogHandle@@YAXXZ TEXTEQU <__imp_?CloseNetpEventLogHandle@@YAXXZ>
extern __imp_?Create@CConnectionManager@@SAJPEAPEAV1@@Z:PANYARGS
?Create@CConnectionManager@@SAJPEAPEAV1@@Z TEXTEQU <__imp_?Create@CConnectionManager@@SAJPEAPEAV1@@Z>
extern __imp_?Create@CNameService@@SAJPEAPEAV1@@Z:PANYARGS
?Create@CNameService@@SAJPEAPEAV1@@Z TEXTEQU <__imp_?Create@CNameService@@SAJPEAPEAV1@@Z>
extern __imp_?Create@CService@@SAJPEAPEAV1@PEAGPEAVCServiceControlManager@@K1@Z:PANYARGS
?Create@CService@@SAJPEAPEAV1@PEAGPEAVCServiceControlManager@@K1@Z TEXTEQU <__imp_?Create@CService@@SAJPEAPEAV1@PEAGPEAVCServiceControlManager@@K1@Z>
extern __imp_?Create@CServiceControlManager@@SAJPEAPEAV1@KPEAG1@Z:PANYARGS
?Create@CServiceControlManager@@SAJPEAPEAV1@KPEAG1@Z TEXTEQU <__imp_?Create@CServiceControlManager@@SAJPEAPEAV1@KPEAG1@Z>
extern __imp_?CreateASRKey@@YAXXZ:PANYARGS
?CreateASRKey@@YAXXZ TEXTEQU <__imp_?CreateASRKey@@YAXXZ>
extern __imp_?CreateInstance@CTmProxyCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PANYARGS
?CreateInstance@CTmProxyCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z TEXTEQU <__imp_?CreateInstance@CTmProxyCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z>
extern __imp_?CreateNewContact@@YAJPEAPEAUIProperties@@@Z:PANYARGS
?CreateNewContact@@YAJPEAPEAUIProperties@@@Z TEXTEQU <__imp_?CreateNewContact@@YAJPEAPEAUIProperties@@@Z>
extern __imp_?CreateOrOpenMutexW@@YAJPEAPEAXPEBGH@Z:PANYARGS
?CreateOrOpenMutexW@@YAJPEAPEAXPEBGH@Z TEXTEQU <__imp_?CreateOrOpenMutexW@@YAJPEAPEAXPEBGH@Z>
extern __imp_?DeleteExistingContacts@@YAXPEAGPEAUIContactPool@@0@Z:PANYARGS
?DeleteExistingContacts@@YAXPEAGPEAUIContactPool@@0@Z TEXTEQU <__imp_?DeleteExistingContacts@@YAXPEAGPEAUIContactPool@@0@Z>
extern __imp_?DllGetDTCAdmin@@YAHAEBU_GUID@@0PEAPEAX@Z:PANYARGS
?DllGetDTCAdmin@@YAHAEBU_GUID@@0PEAPEAX@Z TEXTEQU <__imp_?DllGetDTCAdmin@@YAHAEBU_GUID@@0PEAPEAX@Z>
extern __imp_?DtcWriteToEventLogger@@YAJKKKKPEAXPEAD@Z:PANYARGS
?DtcWriteToEventLogger@@YAJKKKKPEAXPEAD@Z TEXTEQU <__imp_?DtcWriteToEventLogger@@YAJKKKKPEAXPEAD@Z>
extern __imp_?DtcWriteToEventLoggerEx@@YAJGGKPEAXGKPEAPEBD0@Z:PANYARGS
?DtcWriteToEventLoggerEx@@YAJGGKPEAXGKPEAPEBD0@Z TEXTEQU <__imp_?DtcWriteToEventLoggerEx@@YAJGGKPEAXGKPEAPEBD0@Z>
extern __imp_?DtcWriteToEventLoggerExUnFiltered@@YAJGGKPEAXGKPEAPEBD0@Z:PANYARGS
?DtcWriteToEventLoggerExUnFiltered@@YAJGGKPEAXGKPEAPEBD0@Z TEXTEQU <__imp_?DtcWriteToEventLoggerExUnFiltered@@YAJGGKPEAXGKPEAPEBD0@Z>
extern __imp_?DtcWriteToEventLoggerExUnFilteredA@@YAJGGKPEAXGKPEAPEBD0@Z:PANYARGS
?DtcWriteToEventLoggerExUnFilteredA@@YAJGGKPEAXGKPEAPEBD0@Z TEXTEQU <__imp_?DtcWriteToEventLoggerExUnFilteredA@@YAJGGKPEAXGKPEAPEBD0@Z>
extern __imp_?EraseDtcClient@@YAJPEAG@Z:PANYARGS
?EraseDtcClient@@YAJPEAG@Z TEXTEQU <__imp_?EraseDtcClient@@YAJPEAG@Z>
extern __imp_?GetAccount@CService@@QEAAJPEAGPEAK@Z:PANYARGS
?GetAccount@CService@@QEAAJPEAGPEAK@Z TEXTEQU <__imp_?GetAccount@CService@@QEAAJPEAGPEAK@Z>
extern __imp_?GetAccountSid@@YAJPEAG0PEAPEAX@Z:PANYARGS
?GetAccountSid@@YAJPEAG0PEAPEAX@Z TEXTEQU <__imp_?GetAccountSid@@YAJPEAG0PEAPEAX@Z>
extern __imp_?GetControl@CSecurityDescriptor@@QEAAJPEAG@Z:PANYARGS
?GetControl@CSecurityDescriptor@@QEAAJPEAG@Z TEXTEQU <__imp_?GetControl@CSecurityDescriptor@@QEAAJPEAG@Z>
extern __imp_?GetDefaultLogPath@@YAPEAGXZ:PANYARGS
?GetDefaultLogPath@@YAPEAGXZ TEXTEQU <__imp_?GetDefaultLogPath@@YAPEAGXZ>
extern __imp_?GetDefaultLogSize@@YAKXZ:PANYARGS
?GetDefaultLogSize@@YAKXZ TEXTEQU <__imp_?GetDefaultLogSize@@YAKXZ>
extern __imp_?GetDefaultSecurityConfigurationOptions@@YAJPEAGPEAK1@Z:PANYARGS
?GetDefaultSecurityConfigurationOptions@@YAJPEAGPEAK1@Z TEXTEQU <__imp_?GetDefaultSecurityConfigurationOptions@@YAJPEAGPEAK1@Z>
extern __imp_?GetDefaultServiceNameA@@YAPEADXZ:PANYARGS
?GetDefaultServiceNameA@@YAPEADXZ TEXTEQU <__imp_?GetDefaultServiceNameA@@YAPEADXZ>
extern __imp_?GetDefaultServiceNameW@@YAPEAGXZ:PANYARGS
?GetDefaultServiceNameW@@YAPEAGXZ TEXTEQU <__imp_?GetDefaultServiceNameW@@YAPEAGXZ>
extern __imp_?GetDefaultServicePath@@YAPEAGXZ:PANYARGS
?GetDefaultServicePath@@YAPEAGXZ TEXTEQU <__imp_?GetDefaultServicePath@@YAPEAGXZ>
extern __imp_?GetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z:PANYARGS
?GetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z TEXTEQU <__imp_?GetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z>
extern __imp_?GetDtcLogPath@@YAHKPEAG@Z:PANYARGS
?GetDtcLogPath@@YAHKPEAG@Z TEXTEQU <__imp_?GetDtcLogPath@@YAHKPEAG@Z>
extern __imp_?GetDtcPath@@YAHKPEAG@Z:PANYARGS
?GetDtcPath@@YAHKPEAG@Z TEXTEQU <__imp_?GetDtcPath@@YAHKPEAG@Z>
extern __imp_?GetDtcRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z:PANYARGS
?GetDtcRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z TEXTEQU <__imp_?GetDtcRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z>
extern __imp_?GetDtcRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z:PANYARGS
?GetDtcRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z TEXTEQU <__imp_?GetDtcRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z>
extern __imp_?GetDtcRpcSecurityLevel@@YAJPEAGPEAW4_DTC_SECURITY_LEVEL@@H@Z:PANYARGS
?GetDtcRpcSecurityLevel@@YAJPEAGPEAW4_DTC_SECURITY_LEVEL@@H@Z TEXTEQU <__imp_?GetDtcRpcSecurityLevel@@YAJPEAGPEAW4_DTC_SECURITY_LEVEL@@H@Z>
extern __imp_?GetEventLogSource@@YAPEAGXZ:PANYARGS
?GetEventLogSource@@YAPEAGXZ TEXTEQU <__imp_?GetEventLogSource@@YAPEAGXZ>
extern __imp_?GetHandle@CService@@QEAAJAEAPEAUSC_HANDLE__@@@Z:PANYARGS
?GetHandle@CService@@QEAAJAEAPEAUSC_HANDLE__@@@Z TEXTEQU <__imp_?GetHandle@CService@@QEAAJAEAPEAUSC_HANDLE__@@@Z>
extern __imp_?GetHandle@CServiceControlManager@@QEAAJAEAPEAUSC_HANDLE__@@@Z:PANYARGS
?GetHandle@CServiceControlManager@@QEAAJAEAPEAUSC_HANDLE__@@@Z TEXTEQU <__imp_?GetHandle@CServiceControlManager@@QEAAJAEAPEAUSC_HANDLE__@@@Z>
extern __imp_?GetLastKnownDomainControllerState@@YAJPEAGPEAK@Z:PANYARGS
?GetLastKnownDomainControllerState@@YAJPEAGPEAK@Z TEXTEQU <__imp_?GetLastKnownDomainControllerState@@YAJPEAGPEAK@Z>
extern __imp_?GetLocalDtcClusteringVersion@@YAJPEAK@Z:PANYARGS
?GetLocalDtcClusteringVersion@@YAJPEAK@Z TEXTEQU <__imp_?GetLocalDtcClusteringVersion@@YAJPEAK@Z>
extern __imp_?GetMsDtcSPN@@YAJPEAGPEAPEAG@Z:PANYARGS
?GetMsDtcSPN@@YAJPEAGPEAPEAG@Z TEXTEQU <__imp_?GetMsDtcSPN@@YAJPEAGPEAPEAG@Z>
extern __imp_?GetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@@Z:PANYARGS
?GetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@@Z TEXTEQU <__imp_?GetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@@Z>
extern __imp_?GetOldDefaultLogPath@@YAPEAGXZ:PANYARGS
?GetOldDefaultLogPath@@YAPEAGXZ TEXTEQU <__imp_?GetOldDefaultLogPath@@YAPEAGXZ>
extern __imp_?GetSecurityConfigurationOptions@@YAJPEAGPEAK1H@Z:PANYARGS
?GetSecurityConfigurationOptions@@YAJPEAGPEAK1H@Z TEXTEQU <__imp_?GetSecurityConfigurationOptions@@YAJPEAGPEAK1H@Z>
extern __imp_?GetSecurityDescriptor@CSecurityDescriptor@@QEAAJPEAPEAX@Z:PANYARGS
?GetSecurityDescriptor@CSecurityDescriptor@@QEAAJPEAPEAX@Z TEXTEQU <__imp_?GetSecurityDescriptor@CSecurityDescriptor@@QEAAJPEAPEAX@Z>
extern __imp_?GetSecurityRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z:PANYARGS
?GetSecurityRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z TEXTEQU <__imp_?GetSecurityRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z>
extern __imp_?GetSecurityRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z:PANYARGS
?GetSecurityRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z TEXTEQU <__imp_?GetSecurityRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z>
extern __imp_?GetSharedDtcClusteringVersion@@YAJPEAK@Z:PANYARGS
?GetSharedDtcClusteringVersion@@YAJPEAK@Z TEXTEQU <__imp_?GetSharedDtcClusteringVersion@@YAJPEAK@Z>
extern __imp_?GetTmContactA@@YAJPEAD0PEAPEAUIProperties@@@Z:PANYARGS
?GetTmContactA@@YAJPEAD0PEAPEAUIProperties@@@Z TEXTEQU <__imp_?GetTmContactA@@YAJPEAD0PEAPEAUIProperties@@@Z>
extern __imp_?GetTmContactW@@YAJPEAG0PEAPEAUIProperties@@@Z:PANYARGS
?GetTmContactW@@YAJPEAG0PEAPEAUIProperties@@@Z TEXTEQU <__imp_?GetTmContactW@@YAJPEAG0PEAPEAUIProperties@@@Z>
extern __imp_?GetTmUIContactA@@YAJPEAD0PEAPEAUIProperties@@@Z:PANYARGS
?GetTmUIContactA@@YAJPEAD0PEAPEAUIProperties@@@Z TEXTEQU <__imp_?GetTmUIContactA@@YAJPEAD0PEAPEAUIProperties@@@Z>
extern __imp_?GetTmUIContactW@@YAJPEAG0PEAPEAUIProperties@@@Z:PANYARGS
?GetTmUIContactW@@YAJPEAG0PEAPEAUIProperties@@@Z TEXTEQU <__imp_?GetTmUIContactW@@YAJPEAG0PEAPEAUIProperties@@@Z>
extern __imp_?GetXATmSecurityKey@@YAJPEAG0PEAK@Z:PANYARGS
?GetXATmSecurityKey@@YAJPEAG0PEAK@Z TEXTEQU <__imp_?GetXATmSecurityKey@@YAJPEAG0PEAK@Z>
extern __imp_?InstallDtc@@YAJPEAG0000K0H@Z:PANYARGS
?InstallDtc@@YAJPEAG0000K0H@Z TEXTEQU <__imp_?InstallDtc@@YAJPEAG0000K0H@Z>
extern __imp_?InstallDtcClient@@YAJPEAGKK@Z:PANYARGS
?InstallDtcClient@@YAJPEAGKK@Z TEXTEQU <__imp_?InstallDtcClient@@YAJPEAGKK@Z>
extern __imp_?InstallTipGw@@YAJPEAG@Z:PANYARGS
?InstallTipGw@@YAJPEAG@Z TEXTEQU <__imp_?InstallTipGw@@YAJPEAG@Z>
extern __imp_?InstallXaTm@@YAJPEAG@Z:PANYARGS
?InstallXaTm@@YAJPEAG@Z TEXTEQU <__imp_?InstallXaTm@@YAJPEAG@Z>
extern __imp_?InternalInit@CService@@IEAAJPEAGPEAVCServiceControlManager@@K0@Z:PANYARGS
?InternalInit@CService@@IEAAJPEAGPEAVCServiceControlManager@@K0@Z TEXTEQU <__imp_?InternalInit@CService@@IEAAJPEAGPEAVCServiceControlManager@@K0@Z>
extern __imp_?InternalInit@CServiceControlManager@@IEAAJKPEAG0@Z:PANYARGS
?InternalInit@CServiceControlManager@@IEAAJKPEAG0@Z TEXTEQU <__imp_?InternalInit@CServiceControlManager@@IEAAJKPEAG0@Z>
extern __imp_?IsNtVersion5OrMore@@YAHXZ:PANYARGS
?IsNtVersion5OrMore@@YAHXZ TEXTEQU <__imp_?IsNtVersion5OrMore@@YAHXZ>
extern __imp_?JoinDtc@@YAJXZ:PANYARGS
?JoinDtc@@YAJXZ TEXTEQU <__imp_?JoinDtc@@YAJXZ>
extern __imp_?JoinDtcEx@@YAJPEAG@Z:PANYARGS
?JoinDtcEx@@YAJPEAG@Z TEXTEQU <__imp_?JoinDtcEx@@YAJPEAG@Z>
extern __imp_?LookupSpecialAccount@@YAJPEAGPEAPEAU_SPECIAL_ACCOUNT_@@@Z:PANYARGS
?LookupSpecialAccount@@YAJPEAGPEAPEAU_SPECIAL_ACCOUNT_@@@Z TEXTEQU <__imp_?LookupSpecialAccount@@YAJPEAGPEAPEAU_SPECIAL_ACCOUNT_@@@Z>
extern __imp_?MakeAbsolute@CSecurityDescriptor@@IEAAJXZ:PANYARGS
?MakeAbsolute@CSecurityDescriptor@@IEAAJXZ TEXTEQU <__imp_?MakeAbsolute@CSecurityDescriptor@@IEAAJXZ>
extern __imp_?MirrorXaTmSecurityKey@@YAJPEAG@Z:PANYARGS
?MirrorXaTmSecurityKey@@YAJPEAG@Z TEXTEQU <__imp_?MirrorXaTmSecurityKey@@YAJPEAG@Z>
extern __imp_?MsDtcSPNFree@@YAJPEAPEAG@Z:PANYARGS
?MsDtcSPNFree@@YAJPEAPEAG@Z TEXTEQU <__imp_?MsDtcSPNFree@@YAJPEAPEAG@Z>
extern __imp_?OpenServiceA@CServiceControlManager@@QEAAJPEAPEAVCService@@PEAGK@Z:PANYARGS
?OpenServiceA@CServiceControlManager@@QEAAJPEAPEAVCService@@PEAGK@Z TEXTEQU <__imp_?OpenServiceA@CServiceControlManager@@QEAAJPEAPEAVCService@@PEAGK@Z>
extern __imp_?PopulateLocalRegistry@@YAJXZ:PANYARGS
?PopulateLocalRegistry@@YAJXZ TEXTEQU <__imp_?PopulateLocalRegistry@@YAJXZ>
extern __imp_?PopulateSharedClusterRegistryWithContacts@@YAJXZ:PANYARGS
?PopulateSharedClusterRegistryWithContacts@@YAJXZ TEXTEQU <__imp_?PopulateSharedClusterRegistryWithContacts@@YAJXZ>
extern __imp_?PopulateSharedClusterRegistryWithLogInfo@@YAJXZ:PANYARGS
?PopulateSharedClusterRegistryWithLogInfo@@YAJXZ TEXTEQU <__imp_?PopulateSharedClusterRegistryWithLogInfo@@YAJXZ>
extern __imp_?QueryServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z:PANYARGS
?QueryServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z TEXTEQU <__imp_?QueryServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z>
extern __imp_?Release@CService@@QEAAKXZ:PANYARGS
?Release@CService@@QEAAKXZ TEXTEQU <__imp_?Release@CService@@QEAAKXZ>
extern __imp_?Release@CServiceControlManager@@QEAAKXZ:PANYARGS
?Release@CServiceControlManager@@QEAAKXZ TEXTEQU <__imp_?Release@CServiceControlManager@@QEAAKXZ>
extern __imp_?RemoveDtc@@YAJPEAG00@Z:PANYARGS
?RemoveDtc@@YAJPEAG00@Z TEXTEQU <__imp_?RemoveDtc@@YAJPEAG00@Z>
extern __imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAG@Z:PANYARGS
?RemoveSid@CSecurityDescriptor@@QEAAJPEAG@Z TEXTEQU <__imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAG@Z>
extern __imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAX@Z:PANYARGS
?RemoveSid@CSecurityDescriptor@@QEAAJPEAX@Z TEXTEQU <__imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAX@Z>
extern __imp_?Reset@CSecurityDescriptor@@IEAAXXZ:PANYARGS
?Reset@CSecurityDescriptor@@IEAAXXZ TEXTEQU <__imp_?Reset@CSecurityDescriptor@@IEAAXXZ>
extern __imp_?RidToSid@@YAJKPEAPEAX@Z:PANYARGS
?RidToSid@@YAJKPEAPEAX@Z TEXTEQU <__imp_?RidToSid@@YAJKPEAPEAX@Z>
extern __imp_?SetAccount@CService@@QEAAJPEAG0@Z:PANYARGS
?SetAccount@CService@@QEAAJPEAG0@Z TEXTEQU <__imp_?SetAccount@CService@@QEAAJPEAG0@Z>
extern __imp_?SetAccountInfoInRegistryW@@YAJPEAG@Z:PANYARGS
?SetAccountInfoInRegistryW@@YAJPEAG@Z TEXTEQU <__imp_?SetAccountInfoInRegistryW@@YAJPEAG@Z>
extern __imp_?SetControl@CSecurityDescriptor@@QEAAJGG@Z:PANYARGS
?SetControl@CSecurityDescriptor@@QEAAJGG@Z TEXTEQU <__imp_?SetControl@CSecurityDescriptor@@QEAAJGG@Z>
extern __imp_?SetDomainControllerState@@YAJPEAG@Z:PANYARGS
?SetDomainControllerState@@YAJPEAG@Z TEXTEQU <__imp_?SetDomainControllerState@@YAJPEAG@Z>
extern __imp_?SetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z:PANYARGS
?SetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z TEXTEQU <__imp_?SetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z>
extern __imp_?SetDtcClient@@YAJPEAGPEAD0@Z:PANYARGS
?SetDtcClient@@YAJPEAGPEAD0@Z TEXTEQU <__imp_?SetDtcClient@@YAJPEAGPEAD0@Z>
extern __imp_?SetDtcRpcSecurityLevel@@YAJPEAGW4_DTC_SECURITY_LEVEL@@H@Z:PANYARGS
?SetDtcRpcSecurityLevel@@YAJPEAGW4_DTC_SECURITY_LEVEL@@H@Z TEXTEQU <__imp_?SetDtcRpcSecurityLevel@@YAJPEAGW4_DTC_SECURITY_LEVEL@@H@Z>
extern __imp_?SetDtcServerProtocol@@YAJPEAD0@Z:PANYARGS
?SetDtcServerProtocol@@YAJPEAD0@Z TEXTEQU <__imp_?SetDtcServerProtocol@@YAJPEAD0@Z>
extern __imp_?SetEventLogSourceToMsdtcCore@@YAXXZ:PANYARGS
?SetEventLogSourceToMsdtcCore@@YAXXZ TEXTEQU <__imp_?SetEventLogSourceToMsdtcCore@@YAXXZ>
extern __imp_?SetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@K@Z:PANYARGS
?SetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@K@Z TEXTEQU <__imp_?SetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@K@Z>
extern __imp_?SetNewAcl@CSecurityDescriptor@@IEAAJPEAU_ACL@@KHH@Z:PANYARGS
?SetNewAcl@CSecurityDescriptor@@IEAAJPEAU_ACL@@KHH@Z TEXTEQU <__imp_?SetNewAcl@CSecurityDescriptor@@IEAAJPEAU_ACL@@KHH@Z>
extern __imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAGH@Z:PANYARGS
?SetOwner@CSecurityDescriptor@@QEAAJPEAGH@Z TEXTEQU <__imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAGH@Z>
extern __imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAXH@Z:PANYARGS
?SetOwner@CSecurityDescriptor@@QEAAJPEAXH@Z TEXTEQU <__imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAXH@Z>
extern __imp_?SetSecurityConfigurationOptions@@YAJPEAGKK@Z:PANYARGS
?SetSecurityConfigurationOptions@@YAJPEAGKK@Z TEXTEQU <__imp_?SetSecurityConfigurationOptions@@YAJPEAGKK@Z>
extern __imp_?SetSecurityRegValueNonClusterW@@YAJPEAGPEBGKPEAEK@Z:PANYARGS
?SetSecurityRegValueNonClusterW@@YAJPEAGPEBGKPEAEK@Z TEXTEQU <__imp_?SetSecurityRegValueNonClusterW@@YAJPEAGPEBGKPEAEK@Z>
extern __imp_?SetSecurityRegValueW@@YAJPEAGPEBGKPEAEK@Z:PANYARGS
?SetSecurityRegValueW@@YAJPEAGPEBGKPEAEK@Z TEXTEQU <__imp_?SetSecurityRegValueW@@YAJPEAGPEBGKPEAEK@Z>
extern __imp_?SetServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z:PANYARGS
?SetServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z TEXTEQU <__imp_?SetServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z>
extern __imp_?SetSpecialAccounts@CSecurityDescriptor@@QEAAJK@Z:PANYARGS
?SetSpecialAccounts@CSecurityDescriptor@@QEAAJK@Z TEXTEQU <__imp_?SetSpecialAccounts@CSecurityDescriptor@@QEAAJK@Z>
extern __imp_?StringToSid@@YAJPEAGPEAPEAX@Z:PANYARGS
?StringToSid@@YAJPEAGPEAPEAX@Z TEXTEQU <__imp_?StringToSid@@YAJPEAGPEAPEAX@Z>
extern __imp_?UpdateTmNameObject@@YAJPEAUINameObject@@PEAPEAU1@@Z:PANYARGS
?UpdateTmNameObject@@YAJPEAUINameObject@@PEAPEAU1@@Z TEXTEQU <__imp_?UpdateTmNameObject@@YAJPEAUINameObject@@PEAPEAU1@@Z>
extern __imp_?UpgradeDtc@@YAJH@Z:PANYARGS
?UpgradeDtc@@YAJH@Z TEXTEQU <__imp_?UpgradeDtc@@YAJH@Z>
extern __imp_?VerifyAccountInfo@@YAJXZ:PANYARGS
?VerifyAccountInfo@@YAJXZ TEXTEQU <__imp_?VerifyAccountInfo@@YAJXZ>
extern __imp_?Win95Present@@YAHXZ:PANYARGS
?Win95Present@@YAHXZ TEXTEQU <__imp_?Win95Present@@YAHXZ>
extern __imp_?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@A:PANYARGS
?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@  TEXTEQU <__imp_?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@A>
extern __imp_ClusterChangeDtcUserAccount:PANYARGS
ClusterChangeDtcUserAccount TEXTEQU <__imp_ClusterChangeDtcUserAccount>
extern __imp_ClusterCryptoContainerCreate:PANYARGS
ClusterCryptoContainerCreate TEXTEQU <__imp_ClusterCryptoContainerCreate>
extern __imp_ClusterCryptoContainerDelete:PANYARGS
ClusterCryptoContainerDelete TEXTEQU <__imp_ClusterCryptoContainerDelete>
extern __imp_ClusterDaclCryptoContainer:PANYARGS
ClusterDaclCryptoContainer TEXTEQU <__imp_ClusterDaclCryptoContainer>
extern __imp_ClusterUpdateAccountInformation:PANYARGS
ClusterUpdateAccountInformation TEXTEQU <__imp_ClusterUpdateAccountInformation>
extern __imp_DecryptAccountInformation:PANYARGS
DecryptAccountInformation TEXTEQU <__imp_DecryptAccountInformation>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllGetTransactionManagerCore:PANYARGS
DllGetTransactionManagerCore TEXTEQU <__imp_DllGetTransactionManagerCore>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_EncryptAccountInformation:PANYARGS
EncryptAccountInformation TEXTEQU <__imp_EncryptAccountInformation>
