extern __imp_IID_IRichEditOle:PANYARGS
IID_IRichEditOle TEXTEQU <__imp_IID_IRichEditOle>
extern __imp_IID_IRichEditOleCallback:PANYARGS
IID_IRichEditOleCallback TEXTEQU <__imp_IID_IRichEditOleCallback>
extern __imp_CreateTextServices:PANYARGS
CreateTextServices TEXTEQU <__imp_CreateTextServices>
extern __imp_IID_ITextServices:PANYARGS
IID_ITextServices TEXTEQU <__imp_IID_ITextServices>
extern __imp_IID_ITextHost:PANYARGS
IID_ITextHost TEXTEQU <__imp_IID_ITextHost>
extern __imp_IID_ITextHost2:PANYARGS
IID_ITextHost2 TEXTEQU <__imp_IID_ITextHost2>
extern __imp_REExtendedRegisterClass:PANYARGS
REExtendedRegisterClass TEXTEQU <__imp_REExtendedRegisterClass>
extern __imp_RichEditANSIWndProc:PANYARGS
RichEditANSIWndProc TEXTEQU <__imp_RichEditANSIWndProc>
extern __imp_RichEdit10ANSIWndProc:PANYARGS
RichEdit10ANSIWndProc TEXTEQU <__imp_RichEdit10ANSIWndProc>
extern __imp_SetCustomTextOutHandlerEx:PANYARGS
SetCustomTextOutHandlerEx TEXTEQU <__imp_SetCustomTextOutHandlerEx>
extern __imp_DllGetVersion:PANYARGS
DllGetVersion TEXTEQU <__imp_DllGetVersion>
extern __imp_RichEditWndProc:PANYARGS
RichEditWndProc TEXTEQU <__imp_RichEditWndProc>
extern __imp_RichListBoxWndProc:PANYARGS
RichListBoxWndProc TEXTEQU <__imp_RichListBoxWndProc>
extern __imp_RichComboBoxWndProc:PANYARGS
RichComboBoxWndProc TEXTEQU <__imp_RichComboBoxWndProc>
