extern __imp_msgina_ordinal1:PANYARGS
msgina_ordinal1 TEXTEQU <__imp_msgina_ordinal1>
extern __imp_msgina_ordinal2:PANYARGS
msgina_ordinal2 TEXTEQU <__imp_msgina_ordinal2>
extern __imp_msgina_ordinal3:PANYARGS
msgina_ordinal3 TEXTEQU <__imp_msgina_ordinal3>
extern __imp_msgina_ordinal4:PANYARGS
msgina_ordinal4 TEXTEQU <__imp_msgina_ordinal4>
extern __imp_msgina_ordinal5:PANYARGS
msgina_ordinal5 TEXTEQU <__imp_msgina_ordinal5>
extern __imp_msgina_ordinal6:PANYARGS
msgina_ordinal6 TEXTEQU <__imp_msgina_ordinal6>
extern __imp_msgina_ordinal7:PANYARGS
msgina_ordinal7 TEXTEQU <__imp_msgina_ordinal7>
extern __imp_msgina_ordinal8:PANYARGS
msgina_ordinal8 TEXTEQU <__imp_msgina_ordinal8>
extern __imp_msgina_ordinal9:PANYARGS
msgina_ordinal9 TEXTEQU <__imp_msgina_ordinal9>
extern __imp_msgina_ordinal10:PANYARGS
msgina_ordinal10 TEXTEQU <__imp_msgina_ordinal10>
extern __imp_msgina_ordinal11:PANYARGS
msgina_ordinal11 TEXTEQU <__imp_msgina_ordinal11>
extern __imp_msgina_ordinal12:PANYARGS
msgina_ordinal12 TEXTEQU <__imp_msgina_ordinal12>
extern __imp_msgina_ordinal13:PANYARGS
msgina_ordinal13 TEXTEQU <__imp_msgina_ordinal13>
extern __imp_msgina_ordinal14:PANYARGS
msgina_ordinal14 TEXTEQU <__imp_msgina_ordinal14>
extern __imp_msgina_ordinal15:PANYARGS
msgina_ordinal15 TEXTEQU <__imp_msgina_ordinal15>
extern __imp_msgina_ordinal16:PANYARGS
msgina_ordinal16 TEXTEQU <__imp_msgina_ordinal16>
extern __imp_msgina_ordinal17:PANYARGS
msgina_ordinal17 TEXTEQU <__imp_msgina_ordinal17>
extern __imp_msgina_ordinal18:PANYARGS
msgina_ordinal18 TEXTEQU <__imp_msgina_ordinal18>
extern __imp_msgina_ordinal19:PANYARGS
msgina_ordinal19 TEXTEQU <__imp_msgina_ordinal19>
extern __imp_msgina_ordinal20:PANYARGS
msgina_ordinal20 TEXTEQU <__imp_msgina_ordinal20>
extern __imp_msgina_ordinal21:PANYARGS
msgina_ordinal21 TEXTEQU <__imp_msgina_ordinal21>
extern __imp_msgina_ordinal22:PANYARGS
msgina_ordinal22 TEXTEQU <__imp_msgina_ordinal22>
extern __imp_msgina_ordinal23:PANYARGS
msgina_ordinal23 TEXTEQU <__imp_msgina_ordinal23>
extern __imp_msgina_ordinal24:PANYARGS
msgina_ordinal24 TEXTEQU <__imp_msgina_ordinal24>
extern __imp_msgina_ordinal25:PANYARGS
msgina_ordinal25 TEXTEQU <__imp_msgina_ordinal25>
extern __imp_msgina_ordinal26:PANYARGS
msgina_ordinal26 TEXTEQU <__imp_msgina_ordinal26>
extern __imp_msgina_ordinal27:PANYARGS
msgina_ordinal27 TEXTEQU <__imp_msgina_ordinal27>
extern __imp_msgina_ordinal28:PANYARGS
msgina_ordinal28 TEXTEQU <__imp_msgina_ordinal28>
extern __imp_ShellShutdownDialog:PANYARGS
ShellShutdownDialog TEXTEQU <__imp_ShellShutdownDialog>
extern __imp_WlxActivateUserShell:PANYARGS
WlxActivateUserShell TEXTEQU <__imp_WlxActivateUserShell>
extern __imp_WlxDisconnectNotify:PANYARGS
WlxDisconnectNotify TEXTEQU <__imp_WlxDisconnectNotify>
extern __imp_WlxDisplayLockedNotice:PANYARGS
WlxDisplayLockedNotice TEXTEQU <__imp_WlxDisplayLockedNotice>
extern __imp_WlxDisplaySASNotice:PANYARGS
WlxDisplaySASNotice TEXTEQU <__imp_WlxDisplaySASNotice>
extern __imp_WlxDisplayStatusMessage:PANYARGS
WlxDisplayStatusMessage TEXTEQU <__imp_WlxDisplayStatusMessage>
extern __imp_WlxGetConsoleSwitchCredentials:PANYARGS
WlxGetConsoleSwitchCredentials TEXTEQU <__imp_WlxGetConsoleSwitchCredentials>
extern __imp_WlxGetStatusMessage:PANYARGS
WlxGetStatusMessage TEXTEQU <__imp_WlxGetStatusMessage>
extern __imp_WlxInitialize:PANYARGS
WlxInitialize TEXTEQU <__imp_WlxInitialize>
extern __imp_WlxIsLockOk:PANYARGS
WlxIsLockOk TEXTEQU <__imp_WlxIsLockOk>
extern __imp_WlxIsLogoffOk:PANYARGS
WlxIsLogoffOk TEXTEQU <__imp_WlxIsLogoffOk>
extern __imp_WlxLoggedOnSAS:PANYARGS
WlxLoggedOnSAS TEXTEQU <__imp_WlxLoggedOnSAS>
extern __imp_WlxLoggedOutSAS:PANYARGS
WlxLoggedOutSAS TEXTEQU <__imp_WlxLoggedOutSAS>
extern __imp_WlxLogoff:PANYARGS
WlxLogoff TEXTEQU <__imp_WlxLogoff>
extern __imp_WlxNegotiate:PANYARGS
WlxNegotiate TEXTEQU <__imp_WlxNegotiate>
extern __imp_WlxNetworkProviderLoad:PANYARGS
WlxNetworkProviderLoad TEXTEQU <__imp_WlxNetworkProviderLoad>
extern __imp_WlxReconnectNotify:PANYARGS
WlxReconnectNotify TEXTEQU <__imp_WlxReconnectNotify>
extern __imp_WlxRemoveStatusMessage:PANYARGS
WlxRemoveStatusMessage TEXTEQU <__imp_WlxRemoveStatusMessage>
extern __imp_WlxScreenSaverNotify:PANYARGS
WlxScreenSaverNotify TEXTEQU <__imp_WlxScreenSaverNotify>
extern __imp_WlxShutdown:PANYARGS
WlxShutdown TEXTEQU <__imp_WlxShutdown>
extern __imp_WlxStartApplication:PANYARGS
WlxStartApplication TEXTEQU <__imp_WlxStartApplication>
extern __imp_WlxWkstaLockedSAS:PANYARGS
WlxWkstaLockedSAS TEXTEQU <__imp_WlxWkstaLockedSAS>
