extern __imp_msidle_ordinal3:PANYARGS
msidle_ordinal3 TEXTEQU <__imp_msidle_ordinal3>
extern __imp_msidle_ordinal4:PANYARGS
msidle_ordinal4 TEXTEQU <__imp_msidle_ordinal4>
extern __imp_msidle_ordinal5:PANYARGS
msidle_ordinal5 TEXTEQU <__imp_msidle_ordinal5>
extern __imp_msidle_ordinal6:PANYARGS
msidle_ordinal6 TEXTEQU <__imp_msidle_ordinal6>
extern __imp_msidle_ordinal7:PANYARGS
msidle_ordinal7 TEXTEQU <__imp_msidle_ordinal7>
extern __imp_msidle_ordinal8:PANYARGS
msidle_ordinal8 TEXTEQU <__imp_msidle_ordinal8>
