extern __imp_vSetDdrawflag:PANYARGS
vSetDdrawflag TEXTEQU <__imp_vSetDdrawflag>
extern __imp_AlphaBlend:PANYARGS
AlphaBlend TEXTEQU <__imp_AlphaBlend>
extern __imp_DllInitialize:PANYARGS
DllInitialize TEXTEQU <__imp_DllInitialize>
extern __imp_GradientFill:PANYARGS
GradientFill TEXTEQU <__imp_GradientFill>
extern __imp_TransparentBlt:PANYARGS
TransparentBlt TEXTEQU <__imp_TransparentBlt>
