extern __imp_LsCreateContext:PANYARGS
LsCreateContext TEXTEQU <__imp_LsCreateContext>
extern __imp_LsDestroyContext:PANYARGS
LsDestroyContext TEXTEQU <__imp_LsDestroyContext>
extern __imp_LsCreateLine:PANYARGS
LsCreateLine TEXTEQU <__imp_LsCreateLine>
extern __imp_LsModifyLineHeight:PANYARGS
LsModifyLineHeight TEXTEQU <__imp_LsModifyLineHeight>
extern __imp_LsDestroyLine:PANYARGS
LsDestroyLine TEXTEQU <__imp_LsDestroyLine>
extern __imp_LsCreateSubline:PANYARGS
LsCreateSubline TEXTEQU <__imp_LsCreateSubline>
extern __imp_LsFetchAppendToCurrentSubline:PANYARGS
LsFetchAppendToCurrentSubline TEXTEQU <__imp_LsFetchAppendToCurrentSubline>
extern __imp_LsAppendRunToCurrentSubline:PANYARGS
LsAppendRunToCurrentSubline TEXTEQU <__imp_LsAppendRunToCurrentSubline>
extern __imp_LsResetRMInCurrentSubline:PANYARGS
LsResetRMInCurrentSubline TEXTEQU <__imp_LsResetRMInCurrentSubline>
extern __imp_LsFinishCurrentSubline:PANYARGS
LsFinishCurrentSubline TEXTEQU <__imp_LsFinishCurrentSubline>
extern __imp_LsTruncateSubline:PANYARGS
LsTruncateSubline TEXTEQU <__imp_LsTruncateSubline>
extern __imp_LsFindPrevBreakSubline:PANYARGS
LsFindPrevBreakSubline TEXTEQU <__imp_LsFindPrevBreakSubline>
extern __imp_LsFindNextBreakSubline:PANYARGS
LsFindNextBreakSubline TEXTEQU <__imp_LsFindNextBreakSubline>
extern __imp_LsForceBreakSubline:PANYARGS
LsForceBreakSubline TEXTEQU <__imp_LsForceBreakSubline>
extern __imp_LsSetBreakSubline:PANYARGS
LsSetBreakSubline TEXTEQU <__imp_LsSetBreakSubline>
extern __imp_LsDestroySubline:PANYARGS
LsDestroySubline TEXTEQU <__imp_LsDestroySubline>
extern __imp_LsMatchPresSubline:PANYARGS
LsMatchPresSubline TEXTEQU <__imp_LsMatchPresSubline>
extern __imp_LsExpandSubline:PANYARGS
LsExpandSubline TEXTEQU <__imp_LsExpandSubline>
extern __imp_LsGetSpecialEffectsSubline:PANYARGS
LsGetSpecialEffectsSubline TEXTEQU <__imp_LsGetSpecialEffectsSubline>
extern __imp_LsdnFinishRegular:PANYARGS
LsdnFinishRegular TEXTEQU <__imp_LsdnFinishRegular>
extern __imp_LsdnFinishRegularAddAdvancePen:PANYARGS
LsdnFinishRegularAddAdvancePen TEXTEQU <__imp_LsdnFinishRegularAddAdvancePen>
extern __imp_LsdnFinishDelete:PANYARGS
LsdnFinishDelete TEXTEQU <__imp_LsdnFinishDelete>
extern __imp_LsdnFinishByPen:PANYARGS
LsdnFinishByPen TEXTEQU <__imp_LsdnFinishByPen>
extern __imp_LsdnFinishBySubline:PANYARGS
LsdnFinishBySubline TEXTEQU <__imp_LsdnFinishBySubline>
extern __imp_LsdnFinishDeleteAll:PANYARGS
LsdnFinishDeleteAll TEXTEQU <__imp_LsdnFinishDeleteAll>
extern __imp_LsdnFinishByOneChar:PANYARGS
LsdnFinishByOneChar TEXTEQU <__imp_LsdnFinishByOneChar>
extern __imp_LsdnQueryObjDimRange:PANYARGS
LsdnQueryObjDimRange TEXTEQU <__imp_LsdnQueryObjDimRange>
extern __imp_LsdnResetObjDim:PANYARGS
LsdnResetObjDim TEXTEQU <__imp_LsdnResetObjDim>
extern __imp_LsdnQueryPenNode:PANYARGS
LsdnQueryPenNode TEXTEQU <__imp_LsdnQueryPenNode>
extern __imp_LsdnResetPenNode:PANYARGS
LsdnResetPenNode TEXTEQU <__imp_LsdnResetPenNode>
extern __imp_LsdnSetRigidDup:PANYARGS
LsdnSetRigidDup TEXTEQU <__imp_LsdnSetRigidDup>
extern __imp_LsdnGetDup:PANYARGS
LsdnGetDup TEXTEQU <__imp_LsdnGetDup>
extern __imp_LsdnSetAbsBaseLine:PANYARGS
LsdnSetAbsBaseLine TEXTEQU <__imp_LsdnSetAbsBaseLine>
extern __imp_LsdnResolvePrevTab:PANYARGS
LsdnResolvePrevTab TEXTEQU <__imp_LsdnResolvePrevTab>
extern __imp_LsdnGetCurTabInfo:PANYARGS
LsdnGetCurTabInfo TEXTEQU <__imp_LsdnGetCurTabInfo>
extern __imp_LsdnSkipCurTab:PANYARGS
LsdnSkipCurTab TEXTEQU <__imp_LsdnSkipCurTab>
extern __imp_LsdnDistribute:PANYARGS
LsdnDistribute TEXTEQU <__imp_LsdnDistribute>
extern __imp_msls31_ordinal38:PANYARGS
msls31_ordinal38 TEXTEQU <__imp_msls31_ordinal38>
extern __imp_LsdnSubmitSublines:PANYARGS
LsdnSubmitSublines TEXTEQU <__imp_LsdnSubmitSublines>
extern __imp_LsDisplayLine:PANYARGS
LsDisplayLine TEXTEQU <__imp_LsDisplayLine>
extern __imp_LsDisplaySubline:PANYARGS
LsDisplaySubline TEXTEQU <__imp_LsDisplaySubline>
extern __imp_LsQueryLineCpPpoint:PANYARGS
LsQueryLineCpPpoint TEXTEQU <__imp_LsQueryLineCpPpoint>
extern __imp_LsQueryLinePointPcp:PANYARGS
LsQueryLinePointPcp TEXTEQU <__imp_LsQueryLinePointPcp>
extern __imp_LsQueryLineDup:PANYARGS
LsQueryLineDup TEXTEQU <__imp_LsQueryLineDup>
extern __imp_LsQueryFLineEmpty:PANYARGS
LsQueryFLineEmpty TEXTEQU <__imp_LsQueryFLineEmpty>
extern __imp_LsQueryPointPcpSubline:PANYARGS
LsQueryPointPcpSubline TEXTEQU <__imp_LsQueryPointPcpSubline>
extern __imp_LsQueryCpPpointSubline:PANYARGS
LsQueryCpPpointSubline TEXTEQU <__imp_LsQueryCpPpointSubline>
extern __imp_LsSetDoc:PANYARGS
LsSetDoc TEXTEQU <__imp_LsSetDoc>
extern __imp_LsSetModWidthPairs:PANYARGS
LsSetModWidthPairs TEXTEQU <__imp_LsSetModWidthPairs>
extern __imp_LsSetCompression:PANYARGS
LsSetCompression TEXTEQU <__imp_LsSetCompression>
extern __imp_LsSetExpansion:PANYARGS
LsSetExpansion TEXTEQU <__imp_LsSetExpansion>
extern __imp_LsSetBreaking:PANYARGS
LsSetBreaking TEXTEQU <__imp_LsSetBreaking>
extern __imp_LssbGetObjDimSubline:PANYARGS
LssbGetObjDimSubline TEXTEQU <__imp_LssbGetObjDimSubline>
extern __imp_LssbGetDupSubline:PANYARGS
LssbGetDupSubline TEXTEQU <__imp_LssbGetDupSubline>
extern __imp_LssbFDonePresSubline:PANYARGS
LssbFDonePresSubline TEXTEQU <__imp_LssbFDonePresSubline>
extern __imp_LssbGetPlsrunsFromSubline:PANYARGS
LssbGetPlsrunsFromSubline TEXTEQU <__imp_LssbGetPlsrunsFromSubline>
extern __imp_LssbGetNumberDnodesInSubline:PANYARGS
LssbGetNumberDnodesInSubline TEXTEQU <__imp_LssbGetNumberDnodesInSubline>
extern __imp_LssbGetVisibleDcpInSubline:PANYARGS
LssbGetVisibleDcpInSubline TEXTEQU <__imp_LssbGetVisibleDcpInSubline>
extern __imp_LsPointXYFromPointUV:PANYARGS
LsPointXYFromPointUV TEXTEQU <__imp_LsPointXYFromPointUV>
extern __imp_LsPointUV2FromPointUV1:PANYARGS
LsPointUV2FromPointUV1 TEXTEQU <__imp_LsPointUV2FromPointUV1>
extern __imp_LsGetWarichuLsimethods:PANYARGS
LsGetWarichuLsimethods TEXTEQU <__imp_LsGetWarichuLsimethods>
extern __imp_LsGetRubyLsimethods:PANYARGS
LsGetRubyLsimethods TEXTEQU <__imp_LsGetRubyLsimethods>
extern __imp_LsGetTatenakayokoLsimethods:PANYARGS
LsGetTatenakayokoLsimethods TEXTEQU <__imp_LsGetTatenakayokoLsimethods>
extern __imp_LsSqueezeSubline:PANYARGS
LsSqueezeSubline TEXTEQU <__imp_LsSqueezeSubline>
extern __imp_LsCompressSubline:PANYARGS
LsCompressSubline TEXTEQU <__imp_LsCompressSubline>
extern __imp_LsGetHihLsimethods:PANYARGS
LsGetHihLsimethods TEXTEQU <__imp_LsGetHihLsimethods>
extern __imp_LsQueryTextCellDetails:PANYARGS
LsQueryTextCellDetails TEXTEQU <__imp_LsQueryTextCellDetails>
extern __imp_LsFetchAppendToCurrentSublineResume:PANYARGS
LsFetchAppendToCurrentSublineResume TEXTEQU <__imp_LsFetchAppendToCurrentSublineResume>
extern __imp_LsdnGetFormatDepth:PANYARGS
LsdnGetFormatDepth TEXTEQU <__imp_LsdnGetFormatDepth>
extern __imp_LssbFDoneDisplay:PANYARGS
LssbFDoneDisplay TEXTEQU <__imp_LssbFDoneDisplay>
extern __imp_LsGetReverseLsimethods:PANYARGS
LsGetReverseLsimethods TEXTEQU <__imp_LsGetReverseLsimethods>
extern __imp_LsEnumLine:PANYARGS
LsEnumLine TEXTEQU <__imp_LsEnumLine>
extern __imp_LsGetMinDurBreaks:PANYARGS
LsGetMinDurBreaks TEXTEQU <__imp_LsGetMinDurBreaks>
extern __imp_LsGetLineDur:PANYARGS
LsGetLineDur TEXTEQU <__imp_LsGetLineDur>
extern __imp_LsEnumSubline:PANYARGS
LsEnumSubline TEXTEQU <__imp_LsEnumSubline>
extern __imp_LsdnModifyParaEnding:PANYARGS
LsdnModifyParaEnding TEXTEQU <__imp_LsdnModifyParaEnding>
extern __imp_LssbGetDurTrailInSubline:PANYARGS
LssbGetDurTrailInSubline TEXTEQU <__imp_LssbGetDurTrailInSubline>
extern __imp_LssbGetDurTrailWithPensInSubline:PANYARGS
LssbGetDurTrailWithPensInSubline TEXTEQU <__imp_LssbGetDurTrailWithPensInSubline>
extern __imp_LssbFIsSublineEmpty:PANYARGS
LssbFIsSublineEmpty TEXTEQU <__imp_LssbFIsSublineEmpty>
extern __imp_LsLwMultDivR:PANYARGS
LsLwMultDivR TEXTEQU <__imp_LsLwMultDivR>
