extern __imp_CreateSystemHandleName:PANYARGS
CreateSystemHandleName TEXTEQU <__imp_CreateSystemHandleName>
extern __imp_CryptAllocFunc:PANYARGS
CryptAllocFunc TEXTEQU <__imp_CryptAllocFunc>
extern __imp_CryptFreeFunc:PANYARGS
CryptFreeFunc TEXTEQU <__imp_CryptFreeFunc>
extern __imp_FInitializeRichEdit:PANYARGS
FInitializeRichEdit TEXTEQU <__imp_FInitializeRichEdit>
extern __imp_GetDllMajorVersion:PANYARGS
GetDllMajorVersion TEXTEQU <__imp_GetDllMajorVersion>
extern __imp_GetHtmlCharset:PANYARGS
GetHtmlCharset TEXTEQU <__imp_GetHtmlCharset>
extern __imp_GetRichEdClassStringW:PANYARGS
GetRichEdClassStringW TEXTEQU <__imp_GetRichEdClassStringW>
extern __imp_HrGetCertKeyUsage:PANYARGS
HrGetCertKeyUsage TEXTEQU <__imp_HrGetCertKeyUsage>
extern __imp_HrVerifyCertEnhKeyUsage:PANYARGS
HrVerifyCertEnhKeyUsage TEXTEQU <__imp_HrVerifyCertEnhKeyUsage>
extern __imp_IUnknownList_CreateInstance:PANYARGS
IUnknownList_CreateInstance TEXTEQU <__imp_IUnknownList_CreateInstance>
extern __imp_IVoidPtrList_CreateInstance:PANYARGS
IVoidPtrList_CreateInstance TEXTEQU <__imp_IVoidPtrList_CreateInstance>
extern __imp_IsHttpUrlA:PANYARGS
IsHttpUrl  TEXTEQU <__imp_IsHttpUrlA>
extern __imp_SetFontOnRichEd:PANYARGS
SetFontOnRichEd TEXTEQU <__imp_SetFontOnRichEd>
extern __imp_AppendTempFileList:PANYARGS
AppendTempFileList TEXTEQU <__imp_AppendTempFileList>
extern __imp_AthwsprintfW:PANYARGS
AthwsprintfW TEXTEQU <__imp_AthwsprintfW>
extern __imp_BrowseForFolder:PANYARGS
BrowseForFolder TEXTEQU <__imp_BrowseForFolder>
extern __imp_BrowseForFolderW:PANYARGS
BrowseForFolderW TEXTEQU <__imp_BrowseForFolderW>
extern __imp_BuildNotificationPackage:PANYARGS
BuildNotificationPackage TEXTEQU <__imp_BuildNotificationPackage>
extern __imp_CchFileTimeToDateTimeSz:PANYARGS
CchFileTimeToDateTimeSz TEXTEQU <__imp_CchFileTimeToDateTimeSz>
extern __imp_CchFileTimeToDateTimeW:PANYARGS
CchFileTimeToDateTimeW TEXTEQU <__imp_CchFileTimeToDateTimeW>
extern __imp_CenterDialog:PANYARGS
CenterDialog TEXTEQU <__imp_CenterDialog>
extern __imp_ChConvertFromHex:PANYARGS
ChConvertFromHex TEXTEQU <__imp_ChConvertFromHex>
extern __imp_CleanupFileNameInPlaceA:PANYARGS
CleanupFileNameInPlace  TEXTEQU <__imp_CleanupFileNameInPlaceA>
extern __imp_CleanupFileNameInPlaceW:PANYARGS
CleanupFileNameInPlaceW TEXTEQU <__imp_CleanupFileNameInPlaceW>
extern __imp_CleanupGlobalTempFiles:PANYARGS
CleanupGlobalTempFiles TEXTEQU <__imp_CleanupGlobalTempFiles>
extern __imp_CopyRegistry:PANYARGS
CopyRegistry TEXTEQU <__imp_CopyRegistry>
extern __imp_CrackNotificationPackage:PANYARGS
CrackNotificationPackage TEXTEQU <__imp_CrackNotificationPackage>
extern __imp_CreateDataObject:PANYARGS
CreateDataObject TEXTEQU <__imp_CreateDataObject>
extern __imp_CreateEnumFormatEtc:PANYARGS
CreateEnumFormatEtc TEXTEQU <__imp_CreateEnumFormatEtc>
extern __imp_CreateInfoWindow:PANYARGS
CreateInfoWindow TEXTEQU <__imp_CreateInfoWindow>
extern __imp_CreateLogFile:PANYARGS
CreateLogFile TEXTEQU <__imp_CreateLogFile>
extern __imp_CreateNotify:PANYARGS
CreateNotify TEXTEQU <__imp_CreateNotify>
extern __imp_CreateStreamOnHFile:PANYARGS
CreateStreamOnHFile TEXTEQU <__imp_CreateStreamOnHFile>
extern __imp_CreateStreamOnHFileW:PANYARGS
CreateStreamOnHFileW TEXTEQU <__imp_CreateStreamOnHFileW>
extern __imp_CreateTempFile:PANYARGS
CreateTempFile TEXTEQU <__imp_CreateTempFile>
extern __imp_CreateTempFileStream:PANYARGS
CreateTempFileStream TEXTEQU <__imp_CreateTempFileStream>
extern __imp_DeleteTempFile:PANYARGS
DeleteTempFile TEXTEQU <__imp_DeleteTempFile>
extern __imp_DeleteTempFileOnShutdown:PANYARGS
DeleteTempFileOnShutdown TEXTEQU <__imp_DeleteTempFileOnShutdown>
extern __imp_DeleteTempFileOnShutdownEx:PANYARGS
DeleteTempFileOnShutdownEx TEXTEQU <__imp_DeleteTempFileOnShutdownEx>
extern __imp_DoHotMailWizard:PANYARGS
DoHotMailWizard TEXTEQU <__imp_DoHotMailWizard>
extern __imp_FBuildTempPath:PANYARGS
FBuildTempPath TEXTEQU <__imp_FBuildTempPath>
extern __imp_FBuildTempPathW:PANYARGS
FBuildTempPathW TEXTEQU <__imp_FBuildTempPathW>
extern __imp_FIsEmptyA:PANYARGS
FIsEmpty  TEXTEQU <__imp_FIsEmptyA>
extern __imp_FIsEmptyW:PANYARGS
FIsEmptyW TEXTEQU <__imp_FIsEmptyW>
extern __imp_FIsHTMLFile:PANYARGS
FIsHTMLFile TEXTEQU <__imp_FIsHTMLFile>
extern __imp_FIsHTMLFileW:PANYARGS
FIsHTMLFileW TEXTEQU <__imp_FIsHTMLFileW>
extern __imp_FIsSpaceA:PANYARGS
FIsSpace  TEXTEQU <__imp_FIsSpaceA>
extern __imp_FIsSpaceW:PANYARGS
FIsSpaceW TEXTEQU <__imp_FIsSpaceW>
extern __imp_FIsValidFileNameCharA:PANYARGS
FIsValidFileNameChar  TEXTEQU <__imp_FIsValidFileNameCharA>
extern __imp_FIsValidFileNameCharW:PANYARGS
FIsValidFileNameCharW TEXTEQU <__imp_FIsValidFileNameCharW>
extern __imp_FMissingCert:PANYARGS
FMissingCert TEXTEQU <__imp_FMissingCert>
extern __imp_FreeTempFileList:PANYARGS
FreeTempFileList TEXTEQU <__imp_FreeTempFileList>
extern __imp_GenerateUniqueFileName:PANYARGS
GenerateUniqueFileName TEXTEQU <__imp_GenerateUniqueFileName>
extern __imp_GetExePath:PANYARGS
GetExePath TEXTEQU <__imp_GetExePath>
extern __imp_HrBSTRToLPSZ:PANYARGS
HrBSTRToLPSZ TEXTEQU <__imp_HrBSTRToLPSZ>
extern __imp_HrByteToStream:PANYARGS
HrByteToStream TEXTEQU <__imp_HrByteToStream>
extern __imp_HrCheckTridentMenu:PANYARGS
HrCheckTridentMenu TEXTEQU <__imp_HrCheckTridentMenu>
extern __imp_HrCopyLockBytesToStream:PANYARGS
HrCopyLockBytesToStream TEXTEQU <__imp_HrCopyLockBytesToStream>
extern __imp_HrCopyStream:PANYARGS
HrCopyStream TEXTEQU <__imp_HrCopyStream>
extern __imp_HrCopyStreamCB:PANYARGS
HrCopyStreamCB TEXTEQU <__imp_HrCopyStreamCB>
extern __imp_HrCopyStreamCBEndOnCRLF:PANYARGS
HrCopyStreamCBEndOnCRLF TEXTEQU <__imp_HrCopyStreamCBEndOnCRLF>
extern __imp_HrCopyStreamToByte:PANYARGS
HrCopyStreamToByte TEXTEQU <__imp_HrCopyStreamToByte>
extern __imp_HrCreatePhonebookEntry:PANYARGS
HrCreatePhonebookEntry TEXTEQU <__imp_HrCreatePhonebookEntry>
extern __imp_HrCreateTridentMenu:PANYARGS
HrCreateTridentMenu TEXTEQU <__imp_HrCreateTridentMenu>
extern __imp_HrDecodeObject:PANYARGS
HrDecodeObject TEXTEQU <__imp_HrDecodeObject>
extern __imp_HrEditPhonebookEntry:PANYARGS
HrEditPhonebookEntry TEXTEQU <__imp_HrEditPhonebookEntry>
extern __imp_HrFillRasCombo:PANYARGS
HrFillRasCombo TEXTEQU <__imp_HrFillRasCombo>
extern __imp_HrFindInetTimeZone:PANYARGS
HrFindInetTimeZone TEXTEQU <__imp_HrFindInetTimeZone>
extern __imp_HrGetBodyElement:PANYARGS
HrGetBodyElement TEXTEQU <__imp_HrGetBodyElement>
extern __imp_HrGetCertificateParam:PANYARGS
HrGetCertificateParam TEXTEQU <__imp_HrGetCertificateParam>
extern __imp_HrGetElementImpl:PANYARGS
HrGetElementImpl TEXTEQU <__imp_HrGetElementImpl>
extern __imp_HrGetMsgParam:PANYARGS
HrGetMsgParam TEXTEQU <__imp_HrGetMsgParam>
extern __imp_HrGetStreamPos:PANYARGS
HrGetStreamPos TEXTEQU <__imp_HrGetStreamPos>
extern __imp_HrGetStreamSize:PANYARGS
HrGetStreamSize TEXTEQU <__imp_HrGetStreamSize>
extern __imp_HrGetStyleSheet:PANYARGS
HrGetStyleSheet TEXTEQU <__imp_HrGetStyleSheet>
extern __imp_HrIStreamToBSTR:PANYARGS
HrIStreamToBSTR TEXTEQU <__imp_HrIStreamToBSTR>
extern __imp_HrIStreamWToBSTR:PANYARGS
HrIStreamWToBSTR TEXTEQU <__imp_HrIStreamWToBSTR>
extern __imp_HrIndexOfMonth:PANYARGS
HrIndexOfMonth TEXTEQU <__imp_HrIndexOfMonth>
extern __imp_HrIndexOfWeek:PANYARGS
HrIndexOfWeek TEXTEQU <__imp_HrIndexOfWeek>
extern __imp_HrIsStreamUnicode:PANYARGS
HrIsStreamUnicode TEXTEQU <__imp_HrIsStreamUnicode>
extern __imp_HrLPSZCPToBSTR:PANYARGS
HrLPSZCPToBSTR TEXTEQU <__imp_HrLPSZCPToBSTR>
extern __imp_HrLPSZToBSTR:PANYARGS
HrLPSZToBSTR TEXTEQU <__imp_HrLPSZToBSTR>
extern __imp_HrRewindStream:PANYARGS
HrRewindStream TEXTEQU <__imp_HrRewindStream>
extern __imp_HrSafeGetStreamSize:PANYARGS
HrSafeGetStreamSize TEXTEQU <__imp_HrSafeGetStreamSize>
extern __imp_HrSetDirtyFlagImpl:PANYARGS
HrSetDirtyFlagImpl TEXTEQU <__imp_HrSetDirtyFlagImpl>
extern __imp_HrStreamSeekBegin:PANYARGS
HrStreamSeekBegin TEXTEQU <__imp_HrStreamSeekBegin>
extern __imp_HrStreamSeekCur:PANYARGS
HrStreamSeekCur TEXTEQU <__imp_HrStreamSeekCur>
extern __imp_HrStreamSeekEnd:PANYARGS
HrStreamSeekEnd TEXTEQU <__imp_HrStreamSeekEnd>
extern __imp_HrStreamSeekSet:PANYARGS
HrStreamSeekSet TEXTEQU <__imp_HrStreamSeekSet>
extern __imp_HrStreamToByte:PANYARGS
HrStreamToByte TEXTEQU <__imp_HrStreamToByte>
extern __imp_IDrawText:PANYARGS
IDrawText TEXTEQU <__imp_IDrawText>
extern __imp_IsDigit:PANYARGS
IsDigit TEXTEQU <__imp_IsDigit>
extern __imp_IsPlatformWinNT:PANYARGS
IsPlatformWinNT TEXTEQU <__imp_IsPlatformWinNT>
extern __imp_IsPrint:PANYARGS
IsPrint TEXTEQU <__imp_IsPrint>
extern __imp_IsUpper:PANYARGS
IsUpper TEXTEQU <__imp_IsUpper>
extern __imp_IsValidFileIfFileUrl:PANYARGS
IsValidFileIfFileUrl TEXTEQU <__imp_IsValidFileIfFileUrl>
extern __imp_IsValidFileIfFileUrlW:PANYARGS
IsValidFileIfFileUrlW TEXTEQU <__imp_IsValidFileIfFileUrlW>
extern __imp_LoadMappedToolbarBitmap:PANYARGS
LoadMappedToolbarBitmap TEXTEQU <__imp_LoadMappedToolbarBitmap>
extern __imp_MessageBoxInst:PANYARGS
MessageBoxInst TEXTEQU <__imp_MessageBoxInst>
extern __imp_MessageBoxInstW:PANYARGS
MessageBoxInstW TEXTEQU <__imp_MessageBoxInstW>
extern __imp_OpenFileStream:PANYARGS
OpenFileStream TEXTEQU <__imp_OpenFileStream>
extern __imp_OpenFileStreamShare:PANYARGS
OpenFileStreamShare TEXTEQU <__imp_OpenFileStreamShare>
extern __imp_OpenFileStreamShareW:PANYARGS
OpenFileStreamShareW TEXTEQU <__imp_OpenFileStreamShareW>
extern __imp_OpenFileStreamW:PANYARGS
OpenFileStreamW TEXTEQU <__imp_OpenFileStreamW>
extern __imp_OpenFileStreamWithFlags:PANYARGS
OpenFileStreamWithFlags TEXTEQU <__imp_OpenFileStreamWithFlags>
extern __imp_OpenFileStreamWithFlagsW:PANYARGS
OpenFileStreamWithFlagsW TEXTEQU <__imp_OpenFileStreamWithFlagsW>
extern __imp_PSTCreateTypeSubType_NoUI:PANYARGS
PSTCreateTypeSubType_NoUI TEXTEQU <__imp_PSTCreateTypeSubType_NoUI>
extern __imp_PSTFreeHandle:PANYARGS
PSTFreeHandle TEXTEQU <__imp_PSTFreeHandle>
extern __imp_PSTGetData:PANYARGS
PSTGetData TEXTEQU <__imp_PSTGetData>
extern __imp_PSTSetNewData:PANYARGS
PSTSetNewData TEXTEQU <__imp_PSTSetNewData>
extern __imp_PVDecodeObject:PANYARGS
PVDecodeObject TEXTEQU <__imp_PVDecodeObject>
extern __imp_PVGetCertificateParam:PANYARGS
PVGetCertificateParam TEXTEQU <__imp_PVGetCertificateParam>
extern __imp_PVGetMsgParam:PANYARGS
PVGetMsgParam TEXTEQU <__imp_PVGetMsgParam>
extern __imp_PszAllocA:PANYARGS
PszAlloc  TEXTEQU <__imp_PszAllocA>
extern __imp_PszAllocW:PANYARGS
PszAllocW TEXTEQU <__imp_PszAllocW>
extern __imp_PszDayFromIndex:PANYARGS
PszDayFromIndex TEXTEQU <__imp_PszDayFromIndex>
extern __imp_PszDupA:PANYARGS
PszDup  TEXTEQU <__imp_PszDupA>
extern __imp_PszDupLenA:PANYARGS
PszDupLen  TEXTEQU <__imp_PszDupLenA>
extern __imp_PszDupW:PANYARGS
PszDupW TEXTEQU <__imp_PszDupW>
extern __imp_PszEscapeMenuStringA:PANYARGS
PszEscapeMenuString  TEXTEQU <__imp_PszEscapeMenuStringA>
extern __imp_PszFromANSIStreamA:PANYARGS
PszFromANSIStream  TEXTEQU <__imp_PszFromANSIStreamA>
extern __imp_PszMonthFromIndex:PANYARGS
PszMonthFromIndex TEXTEQU <__imp_PszMonthFromIndex>
extern __imp_PszScanToCharA:PANYARGS
PszScanToChar  TEXTEQU <__imp_PszScanToCharA>
extern __imp_PszScanToWhiteA:PANYARGS
PszScanToWhite  TEXTEQU <__imp_PszScanToWhiteA>
extern __imp_PszSkipWhiteA:PANYARGS
PszSkipWhite  TEXTEQU <__imp_PszSkipWhiteA>
extern __imp_PszSkipWhiteW:PANYARGS
PszSkipWhiteW TEXTEQU <__imp_PszSkipWhiteW>
extern __imp_PszToANSI:PANYARGS
PszToANSI TEXTEQU <__imp_PszToANSI>
extern __imp_PszToUnicode:PANYARGS
PszToUnicode TEXTEQU <__imp_PszToUnicode>
extern __imp_ReplaceChars:PANYARGS
ReplaceChars TEXTEQU <__imp_ReplaceChars>
extern __imp_ReplaceCharsW:PANYARGS
ReplaceCharsW TEXTEQU <__imp_ReplaceCharsW>
extern __imp_RicheditStreamIn:PANYARGS
RicheditStreamIn TEXTEQU <__imp_RicheditStreamIn>
extern __imp_RicheditStreamOut:PANYARGS
RicheditStreamOut TEXTEQU <__imp_RicheditStreamOut>
extern __imp_SetIntlFont:PANYARGS
SetIntlFont TEXTEQU <__imp_SetIntlFont>
extern __imp_SetWindowLongPtrAthW:PANYARGS
SetWindowLongPtrAthW TEXTEQU <__imp_SetWindowLongPtrAthW>
extern __imp_ShellUtil_GetSpecialFolderPath:PANYARGS
ShellUtil_GetSpecialFolderPath TEXTEQU <__imp_ShellUtil_GetSpecialFolderPath>
extern __imp_StrChrExA:PANYARGS
StrChrEx  TEXTEQU <__imp_StrChrExA>
extern __imp_StrToUintA:PANYARGS
StrToUint  TEXTEQU <__imp_StrToUintA>
extern __imp_StrToUintW:PANYARGS
StrToUintW TEXTEQU <__imp_StrToUintW>
extern __imp_StrTokEx:PANYARGS
StrTokEx TEXTEQU <__imp_StrTokEx>
extern __imp_StreamSubStringMatch:PANYARGS
StreamSubStringMatch TEXTEQU <__imp_StreamSubStringMatch>
extern __imp_StripCRLF:PANYARGS
StripCRLF TEXTEQU <__imp_StripCRLF>
extern __imp_SzGetCertificateEmailAddress:PANYARGS
SzGetCertificateEmailAddress TEXTEQU <__imp_SzGetCertificateEmailAddress>
extern __imp_UlStripWhitespace:PANYARGS
UlStripWhitespace TEXTEQU <__imp_UlStripWhitespace>
extern __imp_UlStripWhitespaceW:PANYARGS
UlStripWhitespaceW TEXTEQU <__imp_UlStripWhitespaceW>
extern __imp_UnlocStrEqNW:PANYARGS
UnlocStrEqNW TEXTEQU <__imp_UnlocStrEqNW>
extern __imp_UpdateRebarBandColors:PANYARGS
UpdateRebarBandColors TEXTEQU <__imp_UpdateRebarBandColors>
extern __imp_WriteStreamToFile:PANYARGS
WriteStreamToFile TEXTEQU <__imp_WriteStreamToFile>
extern __imp_WriteStreamToFileHandle:PANYARGS
WriteStreamToFileHandle TEXTEQU <__imp_WriteStreamToFileHandle>
extern __imp_WriteStreamToFileW:PANYARGS
WriteStreamToFileW TEXTEQU <__imp_WriteStreamToFileW>
extern __imp_WszGenerateNameFromBlob:PANYARGS
WszGenerateNameFromBlob TEXTEQU <__imp_WszGenerateNameFromBlob>
extern __imp__MSG:PANYARGS
_MSG TEXTEQU <__imp__MSG>
extern __imp_fGetBrowserUrlEncoding:PANYARGS
fGetBrowserUrlEncoding TEXTEQU <__imp_fGetBrowserUrlEncoding>
extern __imp_strtrim:PANYARGS
strtrim TEXTEQU <__imp_strtrim>
extern __imp_strtrimW:PANYARGS
strtrimW TEXTEQU <__imp_strtrimW>
