extern __imp_msswch_ordinal1:PANYARGS
msswch_ordinal1 TEXTEQU <__imp_msswch_ordinal1>
extern __imp_msswch_ordinal2:PANYARGS
msswch_ordinal2 TEXTEQU <__imp_msswch_ordinal2>
extern __imp_msswch_ordinal3:PANYARGS
msswch_ordinal3 TEXTEQU <__imp_msswch_ordinal3>
extern __imp_msswch_ordinal4:PANYARGS
msswch_ordinal4 TEXTEQU <__imp_msswch_ordinal4>
extern __imp_msswch_ordinal5:PANYARGS
msswch_ordinal5 TEXTEQU <__imp_msswch_ordinal5>
extern __imp_msswch_ordinal6:PANYARGS
msswch_ordinal6 TEXTEQU <__imp_msswch_ordinal6>
extern __imp_msswch_ordinal7:PANYARGS
msswch_ordinal7 TEXTEQU <__imp_msswch_ordinal7>
extern __imp_msswch_ordinal8:PANYARGS
msswch_ordinal8 TEXTEQU <__imp_msswch_ordinal8>
extern __imp_msswch_ordinal9:PANYARGS
msswch_ordinal9 TEXTEQU <__imp_msswch_ordinal9>
extern __imp_msswch_ordinal10:PANYARGS
msswch_ordinal10 TEXTEQU <__imp_msswch_ordinal10>
extern __imp_msswch_ordinal11:PANYARGS
msswch_ordinal11 TEXTEQU <__imp_msswch_ordinal11>
extern __imp_msswch_ordinal12:PANYARGS
msswch_ordinal12 TEXTEQU <__imp_msswch_ordinal12>
extern __imp_msswch_ordinal13:PANYARGS
msswch_ordinal13 TEXTEQU <__imp_msswch_ordinal13>
extern __imp_msswch_ordinal14:PANYARGS
msswch_ordinal14 TEXTEQU <__imp_msswch_ordinal14>
