extern __imp_TLSGetVersion:PANYARGS
TLSGetVersion TEXTEQU <__imp_TLSGetVersion>
extern __imp_MIDL_user_allocate:PANYARGS
MIDL_user_allocate TEXTEQU <__imp_MIDL_user_allocate>
extern __imp_MIDL_user_free:PANYARGS
MIDL_user_free TEXTEQU <__imp_MIDL_user_free>
extern __imp_EnumerateTlsServer:PANYARGS
EnumerateTlsServer TEXTEQU <__imp_EnumerateTlsServer>
extern __imp_TLSSendServerCertificate:PANYARGS
TLSSendServerCertificate TEXTEQU <__imp_TLSSendServerCertificate>
extern __imp_TLSGetServerName:PANYARGS
TLSGetServerName TEXTEQU <__imp_TLSGetServerName>
extern __imp_TLSGetServerScope:PANYARGS
TLSGetServerScope TEXTEQU <__imp_TLSGetServerScope>
extern __imp_mstlsapi_ordinal9:PANYARGS
mstlsapi_ordinal9 TEXTEQU <__imp_mstlsapi_ordinal9>
extern __imp_TLSIssuePlatformChallenge:PANYARGS
TLSIssuePlatformChallenge TEXTEQU <__imp_TLSIssuePlatformChallenge>
extern __imp_TLSIssueNewLicense:PANYARGS
TLSIssueNewLicense TEXTEQU <__imp_TLSIssueNewLicense>
extern __imp_TLSUpgradeLicense:PANYARGS
TLSUpgradeLicense TEXTEQU <__imp_TLSUpgradeLicense>
extern __imp_TLSAllocateConcurrentLicense:PANYARGS
TLSAllocateConcurrentLicense TEXTEQU <__imp_TLSAllocateConcurrentLicense>
extern __imp_TLSGetLastError:PANYARGS
TLSGetLastError TEXTEQU <__imp_TLSGetLastError>
extern __imp_TLSKeyPackEnumBegin:PANYARGS
TLSKeyPackEnumBegin TEXTEQU <__imp_TLSKeyPackEnumBegin>
extern __imp_TLSKeyPackEnumNext:PANYARGS
TLSKeyPackEnumNext TEXTEQU <__imp_TLSKeyPackEnumNext>
extern __imp_TLSKeyPackEnumEnd:PANYARGS
TLSKeyPackEnumEnd TEXTEQU <__imp_TLSKeyPackEnumEnd>
extern __imp_TLSLicenseEnumBegin:PANYARGS
TLSLicenseEnumBegin TEXTEQU <__imp_TLSLicenseEnumBegin>
extern __imp_TLSLicenseEnumNext:PANYARGS
TLSLicenseEnumNext TEXTEQU <__imp_TLSLicenseEnumNext>
extern __imp_TLSLicenseEnumEnd:PANYARGS
TLSLicenseEnumEnd TEXTEQU <__imp_TLSLicenseEnumEnd>
extern __imp_TLSGetAvailableLicenses:PANYARGS
TLSGetAvailableLicenses TEXTEQU <__imp_TLSGetAvailableLicenses>
extern __imp_mstlsapi_ordinal22:PANYARGS
mstlsapi_ordinal22 TEXTEQU <__imp_mstlsapi_ordinal22>
extern __imp_mstlsapi_ordinal23:PANYARGS
mstlsapi_ordinal23 TEXTEQU <__imp_mstlsapi_ordinal23>
extern __imp_TLSConnectToLsServer:PANYARGS
TLSConnectToLsServer TEXTEQU <__imp_TLSConnectToLsServer>
extern __imp_TLSConnectToAnyLsServer:PANYARGS
TLSConnectToAnyLsServer TEXTEQU <__imp_TLSConnectToAnyLsServer>
extern __imp_TLSDisconnectFromServer:PANYARGS
TLSDisconnectFromServer TEXTEQU <__imp_TLSDisconnectFromServer>
extern __imp_FindEnterpriseServer:PANYARGS
FindEnterpriseServer TEXTEQU <__imp_FindEnterpriseServer>
extern __imp_GetAllEnterpriseServers:PANYARGS
GetAllEnterpriseServers TEXTEQU <__imp_GetAllEnterpriseServers>
extern __imp_TLSInit:PANYARGS
TLSInit TEXTEQU <__imp_TLSInit>
extern __imp_TLSGetTSCertificate:PANYARGS
TLSGetTSCertificate TEXTEQU <__imp_TLSGetTSCertificate>
extern __imp_LsCsp_GetServerData:PANYARGS
LsCsp_GetServerData TEXTEQU <__imp_LsCsp_GetServerData>
extern __imp_LsCsp_DecryptEnvelopedData:PANYARGS
LsCsp_DecryptEnvelopedData TEXTEQU <__imp_LsCsp_DecryptEnvelopedData>
extern __imp_LsCsp_EncryptHwid:PANYARGS
LsCsp_EncryptHwid TEXTEQU <__imp_LsCsp_EncryptHwid>
extern __imp_LsCsp_StoreSecret:PANYARGS
LsCsp_StoreSecret TEXTEQU <__imp_LsCsp_StoreSecret>
extern __imp_LsCsp_RetrieveSecret:PANYARGS
LsCsp_RetrieveSecret TEXTEQU <__imp_LsCsp_RetrieveSecret>
extern __imp_TLSStartDiscovery:PANYARGS
TLSStartDiscovery TEXTEQU <__imp_TLSStartDiscovery>
extern __imp_TLSStopDiscovery:PANYARGS
TLSStopDiscovery TEXTEQU <__imp_TLSStopDiscovery>
extern __imp_TLSShutdown:PANYARGS
TLSShutdown TEXTEQU <__imp_TLSShutdown>
extern __imp_TLSFreeTSCertificate:PANYARGS
TLSFreeTSCertificate TEXTEQU <__imp_TLSFreeTSCertificate>
extern __imp_TLSIssueNewLicenseEx:PANYARGS
TLSIssueNewLicenseEx TEXTEQU <__imp_TLSIssueNewLicenseEx>
extern __imp_TLSUpgradeLicenseEx:PANYARGS
TLSUpgradeLicenseEx TEXTEQU <__imp_TLSUpgradeLicenseEx>
extern __imp_TLSCheckLicenseMark:PANYARGS
TLSCheckLicenseMark TEXTEQU <__imp_TLSCheckLicenseMark>
extern __imp_TLSIssueNewLicenseExEx:PANYARGS
TLSIssueNewLicenseExEx TEXTEQU <__imp_TLSIssueNewLicenseExEx>
extern __imp_TLSGetServerNameEx:PANYARGS
TLSGetServerNameEx TEXTEQU <__imp_TLSGetServerNameEx>
extern __imp_TLSLicenseEnumNextEx:PANYARGS
TLSLicenseEnumNextEx TEXTEQU <__imp_TLSLicenseEnumNextEx>
extern __imp_TLSGetServerNameFixed:PANYARGS
TLSGetServerNameFixed TEXTEQU <__imp_TLSGetServerNameFixed>
extern __imp_TLSGetServerScopeFixed:PANYARGS
TLSGetServerScopeFixed TEXTEQU <__imp_TLSGetServerScopeFixed>
extern __imp_TLSGetLastErrorFixed:PANYARGS
TLSGetLastErrorFixed TEXTEQU <__imp_TLSGetLastErrorFixed>
extern __imp_GetLicenseServersFromReg:PANYARGS
GetLicenseServersFromReg TEXTEQU <__imp_GetLicenseServersFromReg>
extern __imp_TLSConnectToAnyLsServerNoCertInstall:PANYARGS
TLSConnectToAnyLsServerNoCertInstall TEXTEQU <__imp_TLSConnectToAnyLsServerNoCertInstall>
extern __imp_mstlsapi_ordinal51:PANYARGS
mstlsapi_ordinal51 TEXTEQU <__imp_mstlsapi_ordinal51>
extern __imp_mstlsapi_ordinal52:PANYARGS
mstlsapi_ordinal52 TEXTEQU <__imp_mstlsapi_ordinal52>
extern __imp_mstlsapi_ordinal53:PANYARGS
mstlsapi_ordinal53 TEXTEQU <__imp_mstlsapi_ordinal53>
extern __imp_mstlsapi_ordinal54:PANYARGS
mstlsapi_ordinal54 TEXTEQU <__imp_mstlsapi_ordinal54>
extern __imp_mstlsapi_ordinal55:PANYARGS
mstlsapi_ordinal55 TEXTEQU <__imp_mstlsapi_ordinal55>
extern __imp_mstlsapi_ordinal56:PANYARGS
mstlsapi_ordinal56 TEXTEQU <__imp_mstlsapi_ordinal56>
extern __imp_mstlsapi_ordinal57:PANYARGS
mstlsapi_ordinal57 TEXTEQU <__imp_mstlsapi_ordinal57>
extern __imp_mstlsapi_ordinal58:PANYARGS
mstlsapi_ordinal58 TEXTEQU <__imp_mstlsapi_ordinal58>
extern __imp_mstlsapi_ordinal59:PANYARGS
mstlsapi_ordinal59 TEXTEQU <__imp_mstlsapi_ordinal59>
extern __imp_mstlsapi_ordinal60:PANYARGS
mstlsapi_ordinal60 TEXTEQU <__imp_mstlsapi_ordinal60>
extern __imp_mstlsapi_ordinal61:PANYARGS
mstlsapi_ordinal61 TEXTEQU <__imp_mstlsapi_ordinal61>
extern __imp_mstlsapi_ordinal62:PANYARGS
mstlsapi_ordinal62 TEXTEQU <__imp_mstlsapi_ordinal62>
extern __imp_mstlsapi_ordinal63:PANYARGS
mstlsapi_ordinal63 TEXTEQU <__imp_mstlsapi_ordinal63>
extern __imp_mstlsapi_ordinal64:PANYARGS
mstlsapi_ordinal64 TEXTEQU <__imp_mstlsapi_ordinal64>
extern __imp_mstlsapi_ordinal65:PANYARGS
mstlsapi_ordinal65 TEXTEQU <__imp_mstlsapi_ordinal65>
extern __imp_mstlsapi_ordinal66:PANYARGS
mstlsapi_ordinal66 TEXTEQU <__imp_mstlsapi_ordinal66>
extern __imp_mstlsapi_ordinal67:PANYARGS
mstlsapi_ordinal67 TEXTEQU <__imp_mstlsapi_ordinal67>
extern __imp_mstlsapi_ordinal68:PANYARGS
mstlsapi_ordinal68 TEXTEQU <__imp_mstlsapi_ordinal68>
extern __imp_mstlsapi_ordinal69:PANYARGS
mstlsapi_ordinal69 TEXTEQU <__imp_mstlsapi_ordinal69>
extern __imp_mstlsapi_ordinal70:PANYARGS
mstlsapi_ordinal70 TEXTEQU <__imp_mstlsapi_ordinal70>
extern __imp_mstlsapi_ordinal71:PANYARGS
mstlsapi_ordinal71 TEXTEQU <__imp_mstlsapi_ordinal71>
extern __imp_mstlsapi_ordinal72:PANYARGS
mstlsapi_ordinal72 TEXTEQU <__imp_mstlsapi_ordinal72>
extern __imp_mstlsapi_ordinal73:PANYARGS
mstlsapi_ordinal73 TEXTEQU <__imp_mstlsapi_ordinal73>
extern __imp_mstlsapi_ordinal74:PANYARGS
mstlsapi_ordinal74 TEXTEQU <__imp_mstlsapi_ordinal74>
extern __imp_mstlsapi_ordinal75:PANYARGS
mstlsapi_ordinal75 TEXTEQU <__imp_mstlsapi_ordinal75>
extern __imp_mstlsapi_ordinal76:PANYARGS
mstlsapi_ordinal76 TEXTEQU <__imp_mstlsapi_ordinal76>
extern __imp_mstlsapi_ordinal77:PANYARGS
mstlsapi_ordinal77 TEXTEQU <__imp_mstlsapi_ordinal77>
extern __imp_mstlsapi_ordinal78:PANYARGS
mstlsapi_ordinal78 TEXTEQU <__imp_mstlsapi_ordinal78>
extern __imp_mstlsapi_ordinal79:PANYARGS
mstlsapi_ordinal79 TEXTEQU <__imp_mstlsapi_ordinal79>
extern __imp_mstlsapi_ordinal80:PANYARGS
mstlsapi_ordinal80 TEXTEQU <__imp_mstlsapi_ordinal80>
extern __imp_mstlsapi_ordinal81:PANYARGS
mstlsapi_ordinal81 TEXTEQU <__imp_mstlsapi_ordinal81>
extern __imp_mstlsapi_ordinal82:PANYARGS
mstlsapi_ordinal82 TEXTEQU <__imp_mstlsapi_ordinal82>
extern __imp_mstlsapi_ordinal83:PANYARGS
mstlsapi_ordinal83 TEXTEQU <__imp_mstlsapi_ordinal83>
extern __imp_mstlsapi_ordinal84:PANYARGS
mstlsapi_ordinal84 TEXTEQU <__imp_mstlsapi_ordinal84>
extern __imp_mstlsapi_ordinal85:PANYARGS
mstlsapi_ordinal85 TEXTEQU <__imp_mstlsapi_ordinal85>
extern __imp_mstlsapi_ordinal86:PANYARGS
mstlsapi_ordinal86 TEXTEQU <__imp_mstlsapi_ordinal86>
extern __imp_mstlsapi_ordinal87:PANYARGS
mstlsapi_ordinal87 TEXTEQU <__imp_mstlsapi_ordinal87>
extern __imp_mstlsapi_ordinal88:PANYARGS
mstlsapi_ordinal88 TEXTEQU <__imp_mstlsapi_ordinal88>
extern __imp_mstlsapi_ordinal89:PANYARGS
mstlsapi_ordinal89 TEXTEQU <__imp_mstlsapi_ordinal89>
extern __imp_mstlsapi_ordinal90:PANYARGS
mstlsapi_ordinal90 TEXTEQU <__imp_mstlsapi_ordinal90>
extern __imp_mstlsapi_ordinal91:PANYARGS
mstlsapi_ordinal91 TEXTEQU <__imp_mstlsapi_ordinal91>
extern __imp_mstlsapi_ordinal92:PANYARGS
mstlsapi_ordinal92 TEXTEQU <__imp_mstlsapi_ordinal92>
extern __imp_mstlsapi_ordinal93:PANYARGS
mstlsapi_ordinal93 TEXTEQU <__imp_mstlsapi_ordinal93>
extern __imp_mstlsapi_ordinal94:PANYARGS
mstlsapi_ordinal94 TEXTEQU <__imp_mstlsapi_ordinal94>
extern __imp_mstlsapi_ordinal95:PANYARGS
mstlsapi_ordinal95 TEXTEQU <__imp_mstlsapi_ordinal95>
extern __imp_mstlsapi_ordinal96:PANYARGS
mstlsapi_ordinal96 TEXTEQU <__imp_mstlsapi_ordinal96>
extern __imp_mstlsapi_ordinal97:PANYARGS
mstlsapi_ordinal97 TEXTEQU <__imp_mstlsapi_ordinal97>
extern __imp_mstlsapi_ordinal98:PANYARGS
mstlsapi_ordinal98 TEXTEQU <__imp_mstlsapi_ordinal98>
extern __imp_mstlsapi_ordinal99:PANYARGS
mstlsapi_ordinal99 TEXTEQU <__imp_mstlsapi_ordinal99>
extern __imp_mstlsapi_ordinal100:PANYARGS
mstlsapi_ordinal100 TEXTEQU <__imp_mstlsapi_ordinal100>
extern __imp_RequestToTlsRequest:PANYARGS
RequestToTlsRequest TEXTEQU <__imp_RequestToTlsRequest>
extern __imp_mstlsapi_ordinal102:PANYARGS
mstlsapi_ordinal102 TEXTEQU <__imp_mstlsapi_ordinal102>
extern __imp_TLSRequestTermServCert:PANYARGS
TLSRequestTermServCert TEXTEQU <__imp_TLSRequestTermServCert>
extern __imp_TLSRetrieveTermServCert:PANYARGS
TLSRetrieveTermServCert TEXTEQU <__imp_TLSRetrieveTermServCert>
extern __imp_TLSInstallCertificate:PANYARGS
TLSInstallCertificate TEXTEQU <__imp_TLSInstallCertificate>
extern __imp_TLSGetServerCertificate:PANYARGS
TLSGetServerCertificate TEXTEQU <__imp_TLSGetServerCertificate>
extern __imp_TLSRegisterLicenseKeyPack:PANYARGS
TLSRegisterLicenseKeyPack TEXTEQU <__imp_TLSRegisterLicenseKeyPack>
extern __imp_TLSGetLSPKCS10CertRequest:PANYARGS
TLSGetLSPKCS10CertRequest TEXTEQU <__imp_TLSGetLSPKCS10CertRequest>
extern __imp_TLSKeyPackAdd:PANYARGS
TLSKeyPackAdd TEXTEQU <__imp_TLSKeyPackAdd>
extern __imp_TLSKeyPackSetStatus:PANYARGS
TLSKeyPackSetStatus TEXTEQU <__imp_TLSKeyPackSetStatus>
extern __imp_mstlsapi_ordinal111:PANYARGS
mstlsapi_ordinal111 TEXTEQU <__imp_mstlsapi_ordinal111>
extern __imp_mstlsapi_ordinal112:PANYARGS
mstlsapi_ordinal112 TEXTEQU <__imp_mstlsapi_ordinal112>
extern __imp_TLSReturnLicense:PANYARGS
TLSReturnLicense TEXTEQU <__imp_TLSReturnLicense>
extern __imp_TLSAnnounceServer:PANYARGS
TLSAnnounceServer TEXTEQU <__imp_TLSAnnounceServer>
extern __imp_TLSLookupServer:PANYARGS
TLSLookupServer TEXTEQU <__imp_TLSLookupServer>
extern __imp_TLSAnnounceLicensePack:PANYARGS
TLSAnnounceLicensePack TEXTEQU <__imp_TLSAnnounceLicensePack>
extern __imp_TLSReturnLicensedProduct:PANYARGS
TLSReturnLicensedProduct TEXTEQU <__imp_TLSReturnLicensedProduct>
extern __imp_TLSTelephoneRegisterLKP:PANYARGS
TLSTelephoneRegisterLKP TEXTEQU <__imp_TLSTelephoneRegisterLKP>
extern __imp_TLSChallengeServer:PANYARGS
TLSChallengeServer TEXTEQU <__imp_TLSChallengeServer>
extern __imp_TLSResponseServerChallenge:PANYARGS
TLSResponseServerChallenge TEXTEQU <__imp_TLSResponseServerChallenge>
extern __imp_TLSGetTlsPrivateData:PANYARGS
TLSGetTlsPrivateData TEXTEQU <__imp_TLSGetTlsPrivateData>
extern __imp_mstlsapi_ordinal122:PANYARGS
mstlsapi_ordinal122 TEXTEQU <__imp_mstlsapi_ordinal122>
extern __imp_TLSTriggerReGenKey:PANYARGS
TLSTriggerReGenKey TEXTEQU <__imp_TLSTriggerReGenKey>
extern __imp_TLSGetServerPID:PANYARGS
TLSGetServerPID TEXTEQU <__imp_TLSGetServerPID>
extern __imp_mstlsapi_ordinal125:PANYARGS
mstlsapi_ordinal125 TEXTEQU <__imp_mstlsapi_ordinal125>
extern __imp_TLSGetServerSPK:PANYARGS
TLSGetServerSPK TEXTEQU <__imp_TLSGetServerSPK>
extern __imp_TLSDepositeServerSPK:PANYARGS
TLSDepositeServerSPK TEXTEQU <__imp_TLSDepositeServerSPK>
extern __imp_mstlsapi_ordinal128:PANYARGS
mstlsapi_ordinal128 TEXTEQU <__imp_mstlsapi_ordinal128>
extern __imp_mstlsapi_ordinal129:PANYARGS
mstlsapi_ordinal129 TEXTEQU <__imp_mstlsapi_ordinal129>
extern __imp_TLSAllocateInternetLicenseEx:PANYARGS
TLSAllocateInternetLicenseEx TEXTEQU <__imp_TLSAllocateInternetLicenseEx>
extern __imp_TLSReturnInternetLicenseEx:PANYARGS
TLSReturnInternetLicenseEx TEXTEQU <__imp_TLSReturnInternetLicenseEx>
extern __imp_TLSIsBetaNTServer:PANYARGS
TLSIsBetaNTServer TEXTEQU <__imp_TLSIsBetaNTServer>
extern __imp_TLSIsLicenseEnforceEnable:PANYARGS
TLSIsLicenseEnforceEnable TEXTEQU <__imp_TLSIsLicenseEnforceEnable>
extern __imp_TLSInDomain:PANYARGS
TLSInDomain TEXTEQU <__imp_TLSInDomain>
extern __imp_TLSMarkLicense:PANYARGS
TLSMarkLicense TEXTEQU <__imp_TLSMarkLicense>
extern __imp_TLSGetSupportFlags:PANYARGS
TLSGetSupportFlags TEXTEQU <__imp_TLSGetSupportFlags>
extern __imp_mstlsapi_ordinal137:PANYARGS
mstlsapi_ordinal137 TEXTEQU <__imp_mstlsapi_ordinal137>
extern __imp_TLSLookupServerFixed:PANYARGS
TLSLookupServerFixed TEXTEQU <__imp_TLSLookupServerFixed>
