extern __imp_ClosePopupTipbar:PANYARGS
ClosePopupTipbar TEXTEQU <__imp_ClosePopupTipbar>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetLibTls:PANYARGS
GetLibTls TEXTEQU <__imp_GetLibTls>
extern __imp_GetPopupTipbar:PANYARGS
GetPopupTipbar TEXTEQU <__imp_GetPopupTipbar>
extern __imp_SetRegisterLangBand:PANYARGS
SetRegisterLangBand TEXTEQU <__imp_SetRegisterLangBand>
