extern __imp_SpInitialize:PANYARGS
SpInitialize TEXTEQU <__imp_SpInitialize>
extern __imp_SpLsaModeInitialize:PANYARGS
SpLsaModeInitialize TEXTEQU <__imp_SpLsaModeInitialize>
extern __imp_SpUserModeInitialize:PANYARGS
SpUserModeInitialize TEXTEQU <__imp_SpUserModeInitialize>
extern __imp_LsaApCallPackage:PANYARGS
LsaApCallPackage TEXTEQU <__imp_LsaApCallPackage>
extern __imp_LsaApCallPackagePassthrough:PANYARGS
LsaApCallPackagePassthrough TEXTEQU <__imp_LsaApCallPackagePassthrough>
extern __imp_LsaApCallPackageUntrusted:PANYARGS
LsaApCallPackageUntrusted TEXTEQU <__imp_LsaApCallPackageUntrusted>
extern __imp_LsaApInitializePackage:PANYARGS
LsaApInitializePackage TEXTEQU <__imp_LsaApInitializePackage>
extern __imp_LsaApLogonTerminated:PANYARGS
LsaApLogonTerminated TEXTEQU <__imp_LsaApLogonTerminated>
extern __imp_LsaApLogonUserEx2:PANYARGS
LsaApLogonUserEx2 TEXTEQU <__imp_LsaApLogonUserEx2>
extern __imp_Msv1_0ExportSubAuthenticationRoutine:PANYARGS
Msv1_0ExportSubAuthenticationRoutine TEXTEQU <__imp_Msv1_0ExportSubAuthenticationRoutine>
extern __imp_Msv1_0SubAuthenticationPresent:PANYARGS
Msv1_0SubAuthenticationPresent TEXTEQU <__imp_Msv1_0SubAuthenticationPresent>
extern __imp_MsvGetLogonAttemptCount:PANYARGS
MsvGetLogonAttemptCount TEXTEQU <__imp_MsvGetLogonAttemptCount>
extern __imp_MsvSamLogoff:PANYARGS
MsvSamLogoff TEXTEQU <__imp_MsvSamLogoff>
extern __imp_MsvSamValidate:PANYARGS
MsvSamValidate TEXTEQU <__imp_MsvSamValidate>
extern __imp_MsvValidateTarget:PANYARGS
MsvValidateTarget TEXTEQU <__imp_MsvValidateTarget>
extern __imp_msv1_0_ordinal16:PANYARGS
msv1_0_ordinal16 TEXTEQU <__imp_msv1_0_ordinal16>
extern __imp_msv1_0_ordinal17:PANYARGS
msv1_0_ordinal17 TEXTEQU <__imp_msv1_0_ordinal17>
extern __imp_msv1_0_ordinal18:PANYARGS
msv1_0_ordinal18 TEXTEQU <__imp_msv1_0_ordinal18>
extern __imp_msv1_0_ordinal19:PANYARGS
msv1_0_ordinal19 TEXTEQU <__imp_msv1_0_ordinal19>
extern __imp_msv1_0_ordinal20:PANYARGS
msv1_0_ordinal20 TEXTEQU <__imp_msv1_0_ordinal20>
extern __imp_msv1_0_ordinal21:PANYARGS
msv1_0_ordinal21 TEXTEQU <__imp_msv1_0_ordinal21>
extern __imp_msv1_0_ordinal22:PANYARGS
msv1_0_ordinal22 TEXTEQU <__imp_msv1_0_ordinal22>
extern __imp_msv1_0_ordinal23:PANYARGS
msv1_0_ordinal23 TEXTEQU <__imp_msv1_0_ordinal23>
extern __imp_msv1_0_ordinal24:PANYARGS
msv1_0_ordinal24 TEXTEQU <__imp_msv1_0_ordinal24>
extern __imp_msv1_0_ordinal25:PANYARGS
msv1_0_ordinal25 TEXTEQU <__imp_msv1_0_ordinal25>
extern __imp_msv1_0_ordinal26:PANYARGS
msv1_0_ordinal26 TEXTEQU <__imp_msv1_0_ordinal26>
extern __imp_msv1_0_ordinal27:PANYARGS
msv1_0_ordinal27 TEXTEQU <__imp_msv1_0_ordinal27>
extern __imp_msv1_0_ordinal28:PANYARGS
msv1_0_ordinal28 TEXTEQU <__imp_msv1_0_ordinal28>
extern __imp_msv1_0_ordinal29:PANYARGS
msv1_0_ordinal29 TEXTEQU <__imp_msv1_0_ordinal29>
extern __imp_msv1_0_ordinal30:PANYARGS
msv1_0_ordinal30 TEXTEQU <__imp_msv1_0_ordinal30>
extern __imp_msv1_0_ordinal31:PANYARGS
msv1_0_ordinal31 TEXTEQU <__imp_msv1_0_ordinal31>
extern __imp_SpInstanceInit:PANYARGS
SpInstanceInit TEXTEQU <__imp_SpInstanceInit>
