extern __imp_??0Iostream_init@@QEAA@AEAVios@@H@Z:PANYARGS
??0Iostream_init@@QEAA@AEAVios@@H@Z TEXTEQU <__imp_??0Iostream_init@@QEAA@AEAVios@@H@Z>
extern __imp_??0Iostream_init@@QEAA@XZ:PANYARGS
??0Iostream_init@@QEAA@XZ TEXTEQU <__imp_??0Iostream_init@@QEAA@XZ>
extern __imp_??0exception@@QEAA@AEBQEBD@Z:PANYARGS
??0exception@@QEAA@AEBQEBD@Z TEXTEQU <__imp_??0exception@@QEAA@AEBQEBD@Z>
extern __imp_??0exception@@QEAA@AEBV0@@Z:PANYARGS
??0exception@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0exception@@QEAA@AEBV0@@Z>
extern __imp_??0exception@@QEAA@XZ:PANYARGS
??0exception@@QEAA@XZ TEXTEQU <__imp_??0exception@@QEAA@XZ>
extern __imp_??0filebuf@@QEAA@AEBV0@@Z:PANYARGS
??0filebuf@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0filebuf@@QEAA@AEBV0@@Z>
extern __imp_??0filebuf@@QEAA@H@Z:PANYARGS
??0filebuf@@QEAA@H@Z TEXTEQU <__imp_??0filebuf@@QEAA@H@Z>
extern __imp_??0filebuf@@QEAA@HPEADH@Z:PANYARGS
??0filebuf@@QEAA@HPEADH@Z TEXTEQU <__imp_??0filebuf@@QEAA@HPEADH@Z>
extern __imp_??0filebuf@@QEAA@XZ:PANYARGS
??0filebuf@@QEAA@XZ TEXTEQU <__imp_??0filebuf@@QEAA@XZ>
extern __imp_??0fstream@@QEAA@AEBV0@@Z:PANYARGS
??0fstream@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0fstream@@QEAA@AEBV0@@Z>
extern __imp_??0fstream@@QEAA@H@Z:PANYARGS
??0fstream@@QEAA@H@Z TEXTEQU <__imp_??0fstream@@QEAA@H@Z>
extern __imp_??0fstream@@QEAA@HPEADH@Z:PANYARGS
??0fstream@@QEAA@HPEADH@Z TEXTEQU <__imp_??0fstream@@QEAA@HPEADH@Z>
extern __imp_??0fstream@@QEAA@PEBDHH@Z:PANYARGS
??0fstream@@QEAA@PEBDHH@Z TEXTEQU <__imp_??0fstream@@QEAA@PEBDHH@Z>
extern __imp_??0fstream@@QEAA@XZ:PANYARGS
??0fstream@@QEAA@XZ TEXTEQU <__imp_??0fstream@@QEAA@XZ>
extern __imp_??0ifstream@@QEAA@AEBV0@@Z:PANYARGS
??0ifstream@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ifstream@@QEAA@AEBV0@@Z>
extern __imp_??0ifstream@@QEAA@H@Z:PANYARGS
??0ifstream@@QEAA@H@Z TEXTEQU <__imp_??0ifstream@@QEAA@H@Z>
extern __imp_??0ifstream@@QEAA@HPEADH@Z:PANYARGS
??0ifstream@@QEAA@HPEADH@Z TEXTEQU <__imp_??0ifstream@@QEAA@HPEADH@Z>
extern __imp_??0ifstream@@QEAA@PEBDHH@Z:PANYARGS
??0ifstream@@QEAA@PEBDHH@Z TEXTEQU <__imp_??0ifstream@@QEAA@PEBDHH@Z>
extern __imp_??0ifstream@@QEAA@XZ:PANYARGS
??0ifstream@@QEAA@XZ TEXTEQU <__imp_??0ifstream@@QEAA@XZ>
extern __imp_??0ios@@IEAA@AEBV0@@Z:PANYARGS
??0ios@@IEAA@AEBV0@@Z TEXTEQU <__imp_??0ios@@IEAA@AEBV0@@Z>
extern __imp_??0ios@@IEAA@XZ:PANYARGS
??0ios@@IEAA@XZ TEXTEQU <__imp_??0ios@@IEAA@XZ>
extern __imp_??0ios@@QEAA@PEAVstreambuf@@@Z:PANYARGS
??0ios@@QEAA@PEAVstreambuf@@@Z TEXTEQU <__imp_??0ios@@QEAA@PEAVstreambuf@@@Z>
extern __imp_??0iostream@@IEAA@AEBV0@@Z:PANYARGS
??0iostream@@IEAA@AEBV0@@Z TEXTEQU <__imp_??0iostream@@IEAA@AEBV0@@Z>
extern __imp_??0iostream@@IEAA@XZ:PANYARGS
??0iostream@@IEAA@XZ TEXTEQU <__imp_??0iostream@@IEAA@XZ>
extern __imp_??0iostream@@QEAA@PEAVstreambuf@@@Z:PANYARGS
??0iostream@@QEAA@PEAVstreambuf@@@Z TEXTEQU <__imp_??0iostream@@QEAA@PEAVstreambuf@@@Z>
extern __imp_??0istream@@IEAA@AEBV0@@Z:PANYARGS
??0istream@@IEAA@AEBV0@@Z TEXTEQU <__imp_??0istream@@IEAA@AEBV0@@Z>
extern __imp_??0istream@@IEAA@XZ:PANYARGS
??0istream@@IEAA@XZ TEXTEQU <__imp_??0istream@@IEAA@XZ>
extern __imp_??0istream@@QEAA@PEAVstreambuf@@@Z:PANYARGS
??0istream@@QEAA@PEAVstreambuf@@@Z TEXTEQU <__imp_??0istream@@QEAA@PEAVstreambuf@@@Z>
extern __imp_??0istream_withassign@@QEAA@AEBV0@@Z:PANYARGS
??0istream_withassign@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0istream_withassign@@QEAA@AEBV0@@Z>
extern __imp_??0istream_withassign@@QEAA@PEAVstreambuf@@@Z:PANYARGS
??0istream_withassign@@QEAA@PEAVstreambuf@@@Z TEXTEQU <__imp_??0istream_withassign@@QEAA@PEAVstreambuf@@@Z>
extern __imp_??0istream_withassign@@QEAA@XZ:PANYARGS
??0istream_withassign@@QEAA@XZ TEXTEQU <__imp_??0istream_withassign@@QEAA@XZ>
extern __imp_??0istrstream@@QEAA@AEBV0@@Z:PANYARGS
??0istrstream@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0istrstream@@QEAA@AEBV0@@Z>
extern __imp_??0istrstream@@QEAA@PEAD@Z:PANYARGS
??0istrstream@@QEAA@PEAD@Z TEXTEQU <__imp_??0istrstream@@QEAA@PEAD@Z>
extern __imp_??0istrstream@@QEAA@PEADH@Z:PANYARGS
??0istrstream@@QEAA@PEADH@Z TEXTEQU <__imp_??0istrstream@@QEAA@PEADH@Z>
extern __imp_??0logic_error@@QEAA@AEBQEBD@Z:PANYARGS
??0logic_error@@QEAA@AEBQEBD@Z TEXTEQU <__imp_??0logic_error@@QEAA@AEBQEBD@Z>
extern __imp_??0logic_error@@QEAA@AEBV0@@Z:PANYARGS
??0logic_error@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0logic_error@@QEAA@AEBV0@@Z>
extern __imp_??0ofstream@@QEAA@AEBV0@@Z:PANYARGS
??0ofstream@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ofstream@@QEAA@AEBV0@@Z>
extern __imp_??0ofstream@@QEAA@H@Z:PANYARGS
??0ofstream@@QEAA@H@Z TEXTEQU <__imp_??0ofstream@@QEAA@H@Z>
extern __imp_??0ofstream@@QEAA@HPEADH@Z:PANYARGS
??0ofstream@@QEAA@HPEADH@Z TEXTEQU <__imp_??0ofstream@@QEAA@HPEADH@Z>
extern __imp_??0ofstream@@QEAA@PEBDHH@Z:PANYARGS
??0ofstream@@QEAA@PEBDHH@Z TEXTEQU <__imp_??0ofstream@@QEAA@PEBDHH@Z>
extern __imp_??0ofstream@@QEAA@XZ:PANYARGS
??0ofstream@@QEAA@XZ TEXTEQU <__imp_??0ofstream@@QEAA@XZ>
extern __imp_??0ostream@@IEAA@AEBV0@@Z:PANYARGS
??0ostream@@IEAA@AEBV0@@Z TEXTEQU <__imp_??0ostream@@IEAA@AEBV0@@Z>
extern __imp_??0ostream@@IEAA@XZ:PANYARGS
??0ostream@@IEAA@XZ TEXTEQU <__imp_??0ostream@@IEAA@XZ>
extern __imp_??0ostream@@QEAA@PEAVstreambuf@@@Z:PANYARGS
??0ostream@@QEAA@PEAVstreambuf@@@Z TEXTEQU <__imp_??0ostream@@QEAA@PEAVstreambuf@@@Z>
extern __imp_??0ostream_withassign@@QEAA@AEBV0@@Z:PANYARGS
??0ostream_withassign@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ostream_withassign@@QEAA@AEBV0@@Z>
extern __imp_??0ostream_withassign@@QEAA@PEAVstreambuf@@@Z:PANYARGS
??0ostream_withassign@@QEAA@PEAVstreambuf@@@Z TEXTEQU <__imp_??0ostream_withassign@@QEAA@PEAVstreambuf@@@Z>
extern __imp_??0ostream_withassign@@QEAA@XZ:PANYARGS
??0ostream_withassign@@QEAA@XZ TEXTEQU <__imp_??0ostream_withassign@@QEAA@XZ>
extern __imp_??0ostrstream@@QEAA@AEBV0@@Z:PANYARGS
??0ostrstream@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0ostrstream@@QEAA@AEBV0@@Z>
extern __imp_??0ostrstream@@QEAA@PEADHH@Z:PANYARGS
??0ostrstream@@QEAA@PEADHH@Z TEXTEQU <__imp_??0ostrstream@@QEAA@PEADHH@Z>
extern __imp_??0ostrstream@@QEAA@XZ:PANYARGS
??0ostrstream@@QEAA@XZ TEXTEQU <__imp_??0ostrstream@@QEAA@XZ>
extern __imp_??0stdiobuf@@QEAA@AEBV0@@Z:PANYARGS
??0stdiobuf@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0stdiobuf@@QEAA@AEBV0@@Z>
extern __imp_??0stdiobuf@@QEAA@PEAU_iobuf@@@Z:PANYARGS
??0stdiobuf@@QEAA@PEAU_iobuf@@@Z TEXTEQU <__imp_??0stdiobuf@@QEAA@PEAU_iobuf@@@Z>
extern __imp_??0stdiostream@@QEAA@AEBV0@@Z:PANYARGS
??0stdiostream@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0stdiostream@@QEAA@AEBV0@@Z>
extern __imp_??0stdiostream@@QEAA@PEAU_iobuf@@@Z:PANYARGS
??0stdiostream@@QEAA@PEAU_iobuf@@@Z TEXTEQU <__imp_??0stdiostream@@QEAA@PEAU_iobuf@@@Z>
extern __imp_??0streambuf@@IEAA@PEADH@Z:PANYARGS
??0streambuf@@IEAA@PEADH@Z TEXTEQU <__imp_??0streambuf@@IEAA@PEADH@Z>
extern __imp_??0streambuf@@IEAA@XZ:PANYARGS
??0streambuf@@IEAA@XZ TEXTEQU <__imp_??0streambuf@@IEAA@XZ>
extern __imp_??0streambuf@@QEAA@AEBV0@@Z:PANYARGS
??0streambuf@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0streambuf@@QEAA@AEBV0@@Z>
extern __imp_??0strstream@@QEAA@AEBV0@@Z:PANYARGS
??0strstream@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0strstream@@QEAA@AEBV0@@Z>
extern __imp_??0strstream@@QEAA@PEADHH@Z:PANYARGS
??0strstream@@QEAA@PEADHH@Z TEXTEQU <__imp_??0strstream@@QEAA@PEADHH@Z>
extern __imp_??0strstream@@QEAA@XZ:PANYARGS
??0strstream@@QEAA@XZ TEXTEQU <__imp_??0strstream@@QEAA@XZ>
extern __imp_??0strstreambuf@@QEAA@AEBV0@@Z:PANYARGS
??0strstreambuf@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0strstreambuf@@QEAA@AEBV0@@Z>
extern __imp_??0strstreambuf@@QEAA@H@Z:PANYARGS
??0strstreambuf@@QEAA@H@Z TEXTEQU <__imp_??0strstreambuf@@QEAA@H@Z>
extern __imp_??0strstreambuf@@QEAA@P6APEAXJ@ZP6AXPEAX@Z@Z:PANYARGS
??0strstreambuf@@QEAA@P6APEAXJ@ZP6AXPEAX@Z@Z TEXTEQU <__imp_??0strstreambuf@@QEAA@P6APEAXJ@ZP6AXPEAX@Z@Z>
extern __imp_??0strstreambuf@@QEAA@PEADH0@Z:PANYARGS
??0strstreambuf@@QEAA@PEADH0@Z TEXTEQU <__imp_??0strstreambuf@@QEAA@PEADH0@Z>
extern __imp_??0strstreambuf@@QEAA@PEAEH0@Z:PANYARGS
??0strstreambuf@@QEAA@PEAEH0@Z TEXTEQU <__imp_??0strstreambuf@@QEAA@PEAEH0@Z>
extern __imp_??0strstreambuf@@QEAA@XZ:PANYARGS
??0strstreambuf@@QEAA@XZ TEXTEQU <__imp_??0strstreambuf@@QEAA@XZ>
extern __imp_??1Iostream_init@@QEAA@XZ:PANYARGS
??1Iostream_init@@QEAA@XZ TEXTEQU <__imp_??1Iostream_init@@QEAA@XZ>
extern __imp_??1exception@@UEAA@XZ:PANYARGS
??1exception@@UEAA@XZ TEXTEQU <__imp_??1exception@@UEAA@XZ>
extern __imp_??1filebuf@@UEAA@XZ:PANYARGS
??1filebuf@@UEAA@XZ TEXTEQU <__imp_??1filebuf@@UEAA@XZ>
extern __imp_??1fstream@@UEAA@XZ:PANYARGS
??1fstream@@UEAA@XZ TEXTEQU <__imp_??1fstream@@UEAA@XZ>
extern __imp_??1ifstream@@UEAA@XZ:PANYARGS
??1ifstream@@UEAA@XZ TEXTEQU <__imp_??1ifstream@@UEAA@XZ>
extern __imp_??1ios@@UEAA@XZ:PANYARGS
??1ios@@UEAA@XZ TEXTEQU <__imp_??1ios@@UEAA@XZ>
extern __imp_??1iostream@@UEAA@XZ:PANYARGS
??1iostream@@UEAA@XZ TEXTEQU <__imp_??1iostream@@UEAA@XZ>
extern __imp_??1istream@@UEAA@XZ:PANYARGS
??1istream@@UEAA@XZ TEXTEQU <__imp_??1istream@@UEAA@XZ>
extern __imp_??1istream_withassign@@UEAA@XZ:PANYARGS
??1istream_withassign@@UEAA@XZ TEXTEQU <__imp_??1istream_withassign@@UEAA@XZ>
extern __imp_??1istrstream@@UEAA@XZ:PANYARGS
??1istrstream@@UEAA@XZ TEXTEQU <__imp_??1istrstream@@UEAA@XZ>
extern __imp_??1logic_error@@UEAA@XZ:PANYARGS
??1logic_error@@UEAA@XZ TEXTEQU <__imp_??1logic_error@@UEAA@XZ>
extern __imp_??1ofstream@@UEAA@XZ:PANYARGS
??1ofstream@@UEAA@XZ TEXTEQU <__imp_??1ofstream@@UEAA@XZ>
extern __imp_??1ostream@@UEAA@XZ:PANYARGS
??1ostream@@UEAA@XZ TEXTEQU <__imp_??1ostream@@UEAA@XZ>
extern __imp_??1ostream_withassign@@UEAA@XZ:PANYARGS
??1ostream_withassign@@UEAA@XZ TEXTEQU <__imp_??1ostream_withassign@@UEAA@XZ>
extern __imp_??1ostrstream@@UEAA@XZ:PANYARGS
??1ostrstream@@UEAA@XZ TEXTEQU <__imp_??1ostrstream@@UEAA@XZ>
extern __imp_??1stdiobuf@@UEAA@XZ:PANYARGS
??1stdiobuf@@UEAA@XZ TEXTEQU <__imp_??1stdiobuf@@UEAA@XZ>
extern __imp_??1stdiostream@@UEAA@XZ:PANYARGS
??1stdiostream@@UEAA@XZ TEXTEQU <__imp_??1stdiostream@@UEAA@XZ>
extern __imp_??1streambuf@@UEAA@XZ:PANYARGS
??1streambuf@@UEAA@XZ TEXTEQU <__imp_??1streambuf@@UEAA@XZ>
extern __imp_??1strstream@@UEAA@XZ:PANYARGS
??1strstream@@UEAA@XZ TEXTEQU <__imp_??1strstream@@UEAA@XZ>
extern __imp_??1strstreambuf@@UEAA@XZ:PANYARGS
??1strstreambuf@@UEAA@XZ TEXTEQU <__imp_??1strstreambuf@@UEAA@XZ>
extern __imp_??4Iostream_init@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4Iostream_init@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4Iostream_init@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4exception@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4exception@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4exception@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4filebuf@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4filebuf@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4filebuf@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4fstream@@QEAAAEAV0@AEAV0@@Z:PANYARGS
??4fstream@@QEAAAEAV0@AEAV0@@Z TEXTEQU <__imp_??4fstream@@QEAAAEAV0@AEAV0@@Z>
extern __imp_??4ifstream@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ifstream@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ifstream@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4ios@@IEAAAEAV0@AEBV0@@Z:PANYARGS
??4ios@@IEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ios@@IEAAAEAV0@AEBV0@@Z>
extern __imp_??4iostream@@IEAAAEAV0@AEAV0@@Z:PANYARGS
??4iostream@@IEAAAEAV0@AEAV0@@Z TEXTEQU <__imp_??4iostream@@IEAAAEAV0@AEAV0@@Z>
extern __imp_??4iostream@@IEAAAEAV0@PEAVstreambuf@@@Z:PANYARGS
??4iostream@@IEAAAEAV0@PEAVstreambuf@@@Z TEXTEQU <__imp_??4iostream@@IEAAAEAV0@PEAVstreambuf@@@Z>
extern __imp_??4istream@@IEAAAEAV0@AEBV0@@Z:PANYARGS
??4istream@@IEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4istream@@IEAAAEAV0@AEBV0@@Z>
extern __imp_??4istream@@IEAAAEAV0@PEAVstreambuf@@@Z:PANYARGS
??4istream@@IEAAAEAV0@PEAVstreambuf@@@Z TEXTEQU <__imp_??4istream@@IEAAAEAV0@PEAVstreambuf@@@Z>
extern __imp_??4istream_withassign@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4istream_withassign@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4istream_withassign@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4istream_withassign@@QEAAAEAVistream@@AEBV1@@Z:PANYARGS
??4istream_withassign@@QEAAAEAVistream@@AEBV1@@Z TEXTEQU <__imp_??4istream_withassign@@QEAAAEAVistream@@AEBV1@@Z>
extern __imp_??4istream_withassign@@QEAAAEAVistream@@PEAVstreambuf@@@Z:PANYARGS
??4istream_withassign@@QEAAAEAVistream@@PEAVstreambuf@@@Z TEXTEQU <__imp_??4istream_withassign@@QEAAAEAVistream@@PEAVstreambuf@@@Z>
extern __imp_??4istrstream@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4istrstream@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4istrstream@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4logic_error@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4logic_error@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4logic_error@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4ofstream@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ofstream@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ofstream@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4ostream@@IEAAAEAV0@AEBV0@@Z:PANYARGS
??4ostream@@IEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ostream@@IEAAAEAV0@AEBV0@@Z>
extern __imp_??4ostream@@IEAAAEAV0@PEAVstreambuf@@@Z:PANYARGS
??4ostream@@IEAAAEAV0@PEAVstreambuf@@@Z TEXTEQU <__imp_??4ostream@@IEAAAEAV0@PEAVstreambuf@@@Z>
extern __imp_??4ostream_withassign@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ostream_withassign@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ostream_withassign@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4ostream_withassign@@QEAAAEAVostream@@AEBV1@@Z:PANYARGS
??4ostream_withassign@@QEAAAEAVostream@@AEBV1@@Z TEXTEQU <__imp_??4ostream_withassign@@QEAAAEAVostream@@AEBV1@@Z>
extern __imp_??4ostream_withassign@@QEAAAEAVostream@@PEAVstreambuf@@@Z:PANYARGS
??4ostream_withassign@@QEAAAEAVostream@@PEAVstreambuf@@@Z TEXTEQU <__imp_??4ostream_withassign@@QEAAAEAVostream@@PEAVstreambuf@@@Z>
extern __imp_??4ostrstream@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4ostrstream@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4ostrstream@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4stdiobuf@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4stdiobuf@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4stdiobuf@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4stdiostream@@QEAAAEAV0@AEAV0@@Z:PANYARGS
??4stdiostream@@QEAAAEAV0@AEAV0@@Z TEXTEQU <__imp_??4stdiostream@@QEAAAEAV0@AEAV0@@Z>
extern __imp_??4streambuf@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4streambuf@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4streambuf@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4strstream@@QEAAAEAV0@AEAV0@@Z:PANYARGS
??4strstream@@QEAAAEAV0@AEAV0@@Z TEXTEQU <__imp_??4strstream@@QEAAAEAV0@AEAV0@@Z>
extern __imp_??4strstreambuf@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4strstreambuf@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4strstreambuf@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAC@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAC@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAC@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAD@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAD@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAD@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAE@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAE@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAE@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAF@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAF@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAF@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAG@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAG@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAG@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAH@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAH@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAH@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAI@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAI@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAI@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAJ@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAJ@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAJ@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAK@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAK@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAK@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAM@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAM@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAM@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAN@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAN@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAN@Z>
extern __imp_??5istream@@QEAAAEAV0@AEAO@Z:PANYARGS
??5istream@@QEAAAEAV0@AEAO@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@AEAO@Z>
extern __imp_??5istream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z:PANYARGS
??5istream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z>
extern __imp_??5istream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z:PANYARGS
??5istream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z>
extern __imp_??5istream@@QEAAAEAV0@PEAC@Z:PANYARGS
??5istream@@QEAAAEAV0@PEAC@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@PEAC@Z>
extern __imp_??5istream@@QEAAAEAV0@PEAD@Z:PANYARGS
??5istream@@QEAAAEAV0@PEAD@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@PEAD@Z>
extern __imp_??5istream@@QEAAAEAV0@PEAE@Z:PANYARGS
??5istream@@QEAAAEAV0@PEAE@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@PEAE@Z>
extern __imp_??5istream@@QEAAAEAV0@PEAVstreambuf@@@Z:PANYARGS
??5istream@@QEAAAEAV0@PEAVstreambuf@@@Z TEXTEQU <__imp_??5istream@@QEAAAEAV0@PEAVstreambuf@@@Z>
extern __imp_??6ostream@@QEAAAEAV0@C@Z:PANYARGS
??6ostream@@QEAAAEAV0@C@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@C@Z>
extern __imp_??6ostream@@QEAAAEAV0@D@Z:PANYARGS
??6ostream@@QEAAAEAV0@D@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@D@Z>
extern __imp_??6ostream@@QEAAAEAV0@E@Z:PANYARGS
??6ostream@@QEAAAEAV0@E@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@E@Z>
extern __imp_??6ostream@@QEAAAEAV0@F@Z:PANYARGS
??6ostream@@QEAAAEAV0@F@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@F@Z>
extern __imp_??6ostream@@QEAAAEAV0@G@Z:PANYARGS
??6ostream@@QEAAAEAV0@G@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@G@Z>
extern __imp_??6ostream@@QEAAAEAV0@H@Z:PANYARGS
??6ostream@@QEAAAEAV0@H@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@H@Z>
extern __imp_??6ostream@@QEAAAEAV0@I@Z:PANYARGS
??6ostream@@QEAAAEAV0@I@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@I@Z>
extern __imp_??6ostream@@QEAAAEAV0@J@Z:PANYARGS
??6ostream@@QEAAAEAV0@J@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@J@Z>
extern __imp_??6ostream@@QEAAAEAV0@K@Z:PANYARGS
??6ostream@@QEAAAEAV0@K@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@K@Z>
extern __imp_??6ostream@@QEAAAEAV0@M@Z:PANYARGS
??6ostream@@QEAAAEAV0@M@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@M@Z>
extern __imp_??6ostream@@QEAAAEAV0@N@Z:PANYARGS
??6ostream@@QEAAAEAV0@N@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@N@Z>
extern __imp_??6ostream@@QEAAAEAV0@O@Z:PANYARGS
??6ostream@@QEAAAEAV0@O@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@O@Z>
extern __imp_??6ostream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z:PANYARGS
??6ostream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z>
extern __imp_??6ostream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z:PANYARGS
??6ostream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z>
extern __imp_??6ostream@@QEAAAEAV0@PEAVstreambuf@@@Z:PANYARGS
??6ostream@@QEAAAEAV0@PEAVstreambuf@@@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@PEAVstreambuf@@@Z>
extern __imp_??6ostream@@QEAAAEAV0@PEBC@Z:PANYARGS
??6ostream@@QEAAAEAV0@PEBC@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@PEBC@Z>
extern __imp_??6ostream@@QEAAAEAV0@PEBD@Z:PANYARGS
??6ostream@@QEAAAEAV0@PEBD@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@PEBD@Z>
extern __imp_??6ostream@@QEAAAEAV0@PEBE@Z:PANYARGS
??6ostream@@QEAAAEAV0@PEBE@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@PEBE@Z>
extern __imp_??6ostream@@QEAAAEAV0@PEBX@Z:PANYARGS
??6ostream@@QEAAAEAV0@PEBX@Z TEXTEQU <__imp_??6ostream@@QEAAAEAV0@PEBX@Z>
extern __imp_??7ios@@QEBAHXZ:PANYARGS
??7ios@@QEBAHXZ TEXTEQU <__imp_??7ios@@QEBAHXZ>
extern __imp_??Bios@@QEBAPEAXXZ:PANYARGS
??Bios@@QEBAPEAXXZ TEXTEQU <__imp_??Bios@@QEBAPEAXXZ>
extern __imp_??_7exception@@6B@:PANYARGS
??_7exception@@6B@ TEXTEQU <__imp_??_7exception@@6B@>
extern __imp_??_7filebuf@@6B@:PANYARGS
??_7filebuf@@6B@ TEXTEQU <__imp_??_7filebuf@@6B@>
extern __imp_??_7fstream@@6B@:PANYARGS
??_7fstream@@6B@ TEXTEQU <__imp_??_7fstream@@6B@>
extern __imp_??_7ifstream@@6B@:PANYARGS
??_7ifstream@@6B@ TEXTEQU <__imp_??_7ifstream@@6B@>
extern __imp_??_7ios@@6B@:PANYARGS
??_7ios@@6B@ TEXTEQU <__imp_??_7ios@@6B@>
extern __imp_??_7iostream@@6B@:PANYARGS
??_7iostream@@6B@ TEXTEQU <__imp_??_7iostream@@6B@>
extern __imp_??_7istream@@6B@:PANYARGS
??_7istream@@6B@ TEXTEQU <__imp_??_7istream@@6B@>
extern __imp_??_7istream_withassign@@6B@:PANYARGS
??_7istream_withassign@@6B@ TEXTEQU <__imp_??_7istream_withassign@@6B@>
extern __imp_??_7istrstream@@6B@:PANYARGS
??_7istrstream@@6B@ TEXTEQU <__imp_??_7istrstream@@6B@>
extern __imp_??_7logic_error@@6B@:PANYARGS
??_7logic_error@@6B@ TEXTEQU <__imp_??_7logic_error@@6B@>
extern __imp_??_7ofstream@@6B@:PANYARGS
??_7ofstream@@6B@ TEXTEQU <__imp_??_7ofstream@@6B@>
extern __imp_??_7ostream@@6B@:PANYARGS
??_7ostream@@6B@ TEXTEQU <__imp_??_7ostream@@6B@>
extern __imp_??_7ostream_withassign@@6B@:PANYARGS
??_7ostream_withassign@@6B@ TEXTEQU <__imp_??_7ostream_withassign@@6B@>
extern __imp_??_7ostrstream@@6B@:PANYARGS
??_7ostrstream@@6B@ TEXTEQU <__imp_??_7ostrstream@@6B@>
extern __imp_??_7stdiobuf@@6B@:PANYARGS
??_7stdiobuf@@6B@ TEXTEQU <__imp_??_7stdiobuf@@6B@>
extern __imp_??_7stdiostream@@6B@:PANYARGS
??_7stdiostream@@6B@ TEXTEQU <__imp_??_7stdiostream@@6B@>
extern __imp_??_7streambuf@@6B@:PANYARGS
??_7streambuf@@6B@ TEXTEQU <__imp_??_7streambuf@@6B@>
extern __imp_??_7strstream@@6B@:PANYARGS
??_7strstream@@6B@ TEXTEQU <__imp_??_7strstream@@6B@>
extern __imp_??_7strstreambuf@@6B@:PANYARGS
??_7strstreambuf@@6B@ TEXTEQU <__imp_??_7strstreambuf@@6B@>
extern __imp_??_8fstream@@7Bistream@@@:PANYARGS
??_8fstream@@7Bistream@@@ TEXTEQU <__imp_??_8fstream@@7Bistream@@@>
extern __imp_??_8fstream@@7Bostream@@@:PANYARGS
??_8fstream@@7Bostream@@@ TEXTEQU <__imp_??_8fstream@@7Bostream@@@>
extern __imp_??_8ifstream@@7B@:PANYARGS
??_8ifstream@@7B@ TEXTEQU <__imp_??_8ifstream@@7B@>
extern __imp_??_8iostream@@7Bistream@@@:PANYARGS
??_8iostream@@7Bistream@@@ TEXTEQU <__imp_??_8iostream@@7Bistream@@@>
extern __imp_??_8iostream@@7Bostream@@@:PANYARGS
??_8iostream@@7Bostream@@@ TEXTEQU <__imp_??_8iostream@@7Bostream@@@>
extern __imp_??_8istream@@7B@:PANYARGS
??_8istream@@7B@ TEXTEQU <__imp_??_8istream@@7B@>
extern __imp_??_8istream_withassign@@7B@:PANYARGS
??_8istream_withassign@@7B@ TEXTEQU <__imp_??_8istream_withassign@@7B@>
extern __imp_??_8istrstream@@7B@:PANYARGS
??_8istrstream@@7B@ TEXTEQU <__imp_??_8istrstream@@7B@>
extern __imp_??_8ofstream@@7B@:PANYARGS
??_8ofstream@@7B@ TEXTEQU <__imp_??_8ofstream@@7B@>
extern __imp_??_8ostream@@7B@:PANYARGS
??_8ostream@@7B@ TEXTEQU <__imp_??_8ostream@@7B@>
extern __imp_??_8ostream_withassign@@7B@:PANYARGS
??_8ostream_withassign@@7B@ TEXTEQU <__imp_??_8ostream_withassign@@7B@>
extern __imp_??_8ostrstream@@7B@:PANYARGS
??_8ostrstream@@7B@ TEXTEQU <__imp_??_8ostrstream@@7B@>
extern __imp_??_8stdiostream@@7Bistream@@@:PANYARGS
??_8stdiostream@@7Bistream@@@ TEXTEQU <__imp_??_8stdiostream@@7Bistream@@@>
extern __imp_??_8stdiostream@@7Bostream@@@:PANYARGS
??_8stdiostream@@7Bostream@@@ TEXTEQU <__imp_??_8stdiostream@@7Bostream@@@>
extern __imp_??_8strstream@@7Bistream@@@:PANYARGS
??_8strstream@@7Bistream@@@ TEXTEQU <__imp_??_8strstream@@7Bistream@@@>
extern __imp_??_8strstream@@7Bostream@@@:PANYARGS
??_8strstream@@7Bostream@@@ TEXTEQU <__imp_??_8strstream@@7Bostream@@@>
extern __imp_??_Dfstream@@QEAAXXZ:PANYARGS
??_Dfstream@@QEAAXXZ TEXTEQU <__imp_??_Dfstream@@QEAAXXZ>
extern __imp_??_Difstream@@QEAAXXZ:PANYARGS
??_Difstream@@QEAAXXZ TEXTEQU <__imp_??_Difstream@@QEAAXXZ>
extern __imp_??_Diostream@@QEAAXXZ:PANYARGS
??_Diostream@@QEAAXXZ TEXTEQU <__imp_??_Diostream@@QEAAXXZ>
extern __imp_??_Distream@@QEAAXXZ:PANYARGS
??_Distream@@QEAAXXZ TEXTEQU <__imp_??_Distream@@QEAAXXZ>
extern __imp_??_Distream_withassign@@QEAAXXZ:PANYARGS
??_Distream_withassign@@QEAAXXZ TEXTEQU <__imp_??_Distream_withassign@@QEAAXXZ>
extern __imp_??_Distrstream@@QEAAXXZ:PANYARGS
??_Distrstream@@QEAAXXZ TEXTEQU <__imp_??_Distrstream@@QEAAXXZ>
extern __imp_??_Dofstream@@QEAAXXZ:PANYARGS
??_Dofstream@@QEAAXXZ TEXTEQU <__imp_??_Dofstream@@QEAAXXZ>
extern __imp_??_Dostream@@QEAAXXZ:PANYARGS
??_Dostream@@QEAAXXZ TEXTEQU <__imp_??_Dostream@@QEAAXXZ>
extern __imp_??_Dostream_withassign@@QEAAXXZ:PANYARGS
??_Dostream_withassign@@QEAAXXZ TEXTEQU <__imp_??_Dostream_withassign@@QEAAXXZ>
extern __imp_??_Dostrstream@@QEAAXXZ:PANYARGS
??_Dostrstream@@QEAAXXZ TEXTEQU <__imp_??_Dostrstream@@QEAAXXZ>
extern __imp_??_Dstdiostream@@QEAAXXZ:PANYARGS
??_Dstdiostream@@QEAAXXZ TEXTEQU <__imp_??_Dstdiostream@@QEAAXXZ>
extern __imp_??_Dstrstream@@QEAAXXZ:PANYARGS
??_Dstrstream@@QEAAXXZ TEXTEQU <__imp_??_Dstrstream@@QEAAXXZ>
extern __imp_?adjustfield@ios@@2JB:PANYARGS
?adjustfield@ios@@2JB TEXTEQU <__imp_?adjustfield@ios@@2JB>
extern __imp_?allocate@streambuf@@IEAAHXZ:PANYARGS
?allocate@streambuf@@IEAAHXZ TEXTEQU <__imp_?allocate@streambuf@@IEAAHXZ>
extern __imp_?attach@filebuf@@QEAAPEAV1@H@Z:PANYARGS
?attach@filebuf@@QEAAPEAV1@H@Z TEXTEQU <__imp_?attach@filebuf@@QEAAPEAV1@H@Z>
extern __imp_?attach@fstream@@QEAAXH@Z:PANYARGS
?attach@fstream@@QEAAXH@Z TEXTEQU <__imp_?attach@fstream@@QEAAXH@Z>
extern __imp_?attach@ifstream@@QEAAXH@Z:PANYARGS
?attach@ifstream@@QEAAXH@Z TEXTEQU <__imp_?attach@ifstream@@QEAAXH@Z>
extern __imp_?attach@ofstream@@QEAAXH@Z:PANYARGS
?attach@ofstream@@QEAAXH@Z TEXTEQU <__imp_?attach@ofstream@@QEAAXH@Z>
extern __imp_?bad@ios@@QEBAHXZ:PANYARGS
?bad@ios@@QEBAHXZ TEXTEQU <__imp_?bad@ios@@QEBAHXZ>
extern __imp_?base@streambuf@@IEBAPEADXZ:PANYARGS
?base@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?base@streambuf@@IEBAPEADXZ>
extern __imp_?basefield@ios@@2JB:PANYARGS
?basefield@ios@@2JB TEXTEQU <__imp_?basefield@ios@@2JB>
extern __imp_?binary@filebuf@@2HB:PANYARGS
?binary@filebuf@@2HB TEXTEQU <__imp_?binary@filebuf@@2HB>
extern __imp_?bitalloc@ios@@SAJXZ:PANYARGS
?bitalloc@ios@@SAJXZ TEXTEQU <__imp_?bitalloc@ios@@SAJXZ>
extern __imp_?blen@streambuf@@IEBAHXZ:PANYARGS
?blen@streambuf@@IEBAHXZ TEXTEQU <__imp_?blen@streambuf@@IEBAHXZ>
extern __imp_?cerr@@3Vostream_withassign@@A:PANYARGS
?cerr@@3Vostream_withassign@@  TEXTEQU <__imp_?cerr@@3Vostream_withassign@@A>
extern __imp_?cin@@3Vistream_withassign@@A:PANYARGS
?cin@@3Vistream_withassign@@  TEXTEQU <__imp_?cin@@3Vistream_withassign@@A>
extern __imp_?clear@ios@@QEAAXH@Z:PANYARGS
?clear@ios@@QEAAXH@Z TEXTEQU <__imp_?clear@ios@@QEAAXH@Z>
extern __imp_?clog@@3Vostream_withassign@@A:PANYARGS
?clog@@3Vostream_withassign@@  TEXTEQU <__imp_?clog@@3Vostream_withassign@@A>
extern __imp_?close@filebuf@@QEAAPEAV1@XZ:PANYARGS
?close@filebuf@@QEAAPEAV1@XZ TEXTEQU <__imp_?close@filebuf@@QEAAPEAV1@XZ>
extern __imp_?close@fstream@@QEAAXXZ:PANYARGS
?close@fstream@@QEAAXXZ TEXTEQU <__imp_?close@fstream@@QEAAXXZ>
extern __imp_?close@ifstream@@QEAAXXZ:PANYARGS
?close@ifstream@@QEAAXXZ TEXTEQU <__imp_?close@ifstream@@QEAAXXZ>
extern __imp_?close@ofstream@@QEAAXXZ:PANYARGS
?close@ofstream@@QEAAXXZ TEXTEQU <__imp_?close@ofstream@@QEAAXXZ>
extern __imp_?clrlock@ios@@QEAAXXZ:PANYARGS
?clrlock@ios@@QEAAXXZ TEXTEQU <__imp_?clrlock@ios@@QEAAXXZ>
extern __imp_?clrlock@streambuf@@QEAAXXZ:PANYARGS
?clrlock@streambuf@@QEAAXXZ TEXTEQU <__imp_?clrlock@streambuf@@QEAAXXZ>
extern __imp_?cout@@3Vostream_withassign@@A:PANYARGS
?cout@@3Vostream_withassign@@  TEXTEQU <__imp_?cout@@3Vostream_withassign@@A>
extern __imp_?dbp@streambuf@@QEAAXXZ:PANYARGS
?dbp@streambuf@@QEAAXXZ TEXTEQU <__imp_?dbp@streambuf@@QEAAXXZ>
extern __imp_?dec@@YAAEAVios@@AEAV1@@Z:PANYARGS
?dec@@YAAEAVios@@AEAV1@@Z TEXTEQU <__imp_?dec@@YAAEAVios@@AEAV1@@Z>
extern __imp_?delbuf@ios@@QEAAXH@Z:PANYARGS
?delbuf@ios@@QEAAXH@Z TEXTEQU <__imp_?delbuf@ios@@QEAAXH@Z>
extern __imp_?delbuf@ios@@QEBAHXZ:PANYARGS
?delbuf@ios@@QEBAHXZ TEXTEQU <__imp_?delbuf@ios@@QEBAHXZ>
extern __imp_?doallocate@streambuf@@MEAAHXZ:PANYARGS
?doallocate@streambuf@@MEAAHXZ TEXTEQU <__imp_?doallocate@streambuf@@MEAAHXZ>
extern __imp_?doallocate@strstreambuf@@MEAAHXZ:PANYARGS
?doallocate@strstreambuf@@MEAAHXZ TEXTEQU <__imp_?doallocate@strstreambuf@@MEAAHXZ>
extern __imp_?eatwhite@istream@@QEAAXXZ:PANYARGS
?eatwhite@istream@@QEAAXXZ TEXTEQU <__imp_?eatwhite@istream@@QEAAXXZ>
extern __imp_?eback@streambuf@@IEBAPEADXZ:PANYARGS
?eback@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?eback@streambuf@@IEBAPEADXZ>
extern __imp_?ebuf@streambuf@@IEBAPEADXZ:PANYARGS
?ebuf@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?ebuf@streambuf@@IEBAPEADXZ>
extern __imp_?egptr@streambuf@@IEBAPEADXZ:PANYARGS
?egptr@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?egptr@streambuf@@IEBAPEADXZ>
extern __imp_?endl@@YAAEAVostream@@AEAV1@@Z:PANYARGS
?endl@@YAAEAVostream@@AEAV1@@Z TEXTEQU <__imp_?endl@@YAAEAVostream@@AEAV1@@Z>
extern __imp_?ends@@YAAEAVostream@@AEAV1@@Z:PANYARGS
?ends@@YAAEAVostream@@AEAV1@@Z TEXTEQU <__imp_?ends@@YAAEAVostream@@AEAV1@@Z>
extern __imp_?eof@ios@@QEBAHXZ:PANYARGS
?eof@ios@@QEBAHXZ TEXTEQU <__imp_?eof@ios@@QEBAHXZ>
extern __imp_?epptr@streambuf@@IEBAPEADXZ:PANYARGS
?epptr@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?epptr@streambuf@@IEBAPEADXZ>
extern __imp_?fLockcInit@ios@@0HA:PANYARGS
?fLockcInit@ios@@0H  TEXTEQU <__imp_?fLockcInit@ios@@0HA>
extern __imp_?fail@ios@@QEBAHXZ:PANYARGS
?fail@ios@@QEBAHXZ TEXTEQU <__imp_?fail@ios@@QEBAHXZ>
extern __imp_?fd@filebuf@@QEBAHXZ:PANYARGS
?fd@filebuf@@QEBAHXZ TEXTEQU <__imp_?fd@filebuf@@QEBAHXZ>
extern __imp_?fd@fstream@@QEBAHXZ:PANYARGS
?fd@fstream@@QEBAHXZ TEXTEQU <__imp_?fd@fstream@@QEBAHXZ>
extern __imp_?fd@ifstream@@QEBAHXZ:PANYARGS
?fd@ifstream@@QEBAHXZ TEXTEQU <__imp_?fd@ifstream@@QEBAHXZ>
extern __imp_?fd@ofstream@@QEBAHXZ:PANYARGS
?fd@ofstream@@QEBAHXZ TEXTEQU <__imp_?fd@ofstream@@QEBAHXZ>
extern __imp_?fill@ios@@QEAADD@Z:PANYARGS
?fill@ios@@QEAADD@Z TEXTEQU <__imp_?fill@ios@@QEAADD@Z>
extern __imp_?fill@ios@@QEBADXZ:PANYARGS
?fill@ios@@QEBADXZ TEXTEQU <__imp_?fill@ios@@QEBADXZ>
extern __imp_?flags@ios@@QEAAJJ@Z:PANYARGS
?flags@ios@@QEAAJJ@Z TEXTEQU <__imp_?flags@ios@@QEAAJJ@Z>
extern __imp_?flags@ios@@QEBAJXZ:PANYARGS
?flags@ios@@QEBAJXZ TEXTEQU <__imp_?flags@ios@@QEBAJXZ>
extern __imp_?floatfield@ios@@2JB:PANYARGS
?floatfield@ios@@2JB TEXTEQU <__imp_?floatfield@ios@@2JB>
extern __imp_?flush@@YAAEAVostream@@AEAV1@@Z:PANYARGS
?flush@@YAAEAVostream@@AEAV1@@Z TEXTEQU <__imp_?flush@@YAAEAVostream@@AEAV1@@Z>
extern __imp_?flush@ostream@@QEAAAEAV1@XZ:PANYARGS
?flush@ostream@@QEAAAEAV1@XZ TEXTEQU <__imp_?flush@ostream@@QEAAAEAV1@XZ>
extern __imp_?freeze@strstreambuf@@QEAAXH@Z:PANYARGS
?freeze@strstreambuf@@QEAAXH@Z TEXTEQU <__imp_?freeze@strstreambuf@@QEAAXH@Z>
extern __imp_?gbump@streambuf@@IEAAXH@Z:PANYARGS
?gbump@streambuf@@IEAAXH@Z TEXTEQU <__imp_?gbump@streambuf@@IEAAXH@Z>
extern __imp_?gcount@istream@@QEBAHXZ:PANYARGS
?gcount@istream@@QEBAHXZ TEXTEQU <__imp_?gcount@istream@@QEBAHXZ>
extern __imp_?get@istream@@IEAAAEAV1@PEADHH@Z:PANYARGS
?get@istream@@IEAAAEAV1@PEADHH@Z TEXTEQU <__imp_?get@istream@@IEAAAEAV1@PEADHH@Z>
extern __imp_?get@istream@@QEAAAEAV1@AEAC@Z:PANYARGS
?get@istream@@QEAAAEAV1@AEAC@Z TEXTEQU <__imp_?get@istream@@QEAAAEAV1@AEAC@Z>
extern __imp_?get@istream@@QEAAAEAV1@AEAD@Z:PANYARGS
?get@istream@@QEAAAEAV1@AEAD@Z TEXTEQU <__imp_?get@istream@@QEAAAEAV1@AEAD@Z>
extern __imp_?get@istream@@QEAAAEAV1@AEAE@Z:PANYARGS
?get@istream@@QEAAAEAV1@AEAE@Z TEXTEQU <__imp_?get@istream@@QEAAAEAV1@AEAE@Z>
extern __imp_?get@istream@@QEAAAEAV1@AEAVstreambuf@@D@Z:PANYARGS
?get@istream@@QEAAAEAV1@AEAVstreambuf@@D@Z TEXTEQU <__imp_?get@istream@@QEAAAEAV1@AEAVstreambuf@@D@Z>
extern __imp_?get@istream@@QEAAAEAV1@PEACHD@Z:PANYARGS
?get@istream@@QEAAAEAV1@PEACHD@Z TEXTEQU <__imp_?get@istream@@QEAAAEAV1@PEACHD@Z>
extern __imp_?get@istream@@QEAAAEAV1@PEADHD@Z:PANYARGS
?get@istream@@QEAAAEAV1@PEADHD@Z TEXTEQU <__imp_?get@istream@@QEAAAEAV1@PEADHD@Z>
extern __imp_?get@istream@@QEAAAEAV1@PEAEHD@Z:PANYARGS
?get@istream@@QEAAAEAV1@PEAEHD@Z TEXTEQU <__imp_?get@istream@@QEAAAEAV1@PEAEHD@Z>
extern __imp_?get@istream@@QEAAHXZ:PANYARGS
?get@istream@@QEAAHXZ TEXTEQU <__imp_?get@istream@@QEAAHXZ>
extern __imp_?getdouble@istream@@AEAAHPEADH@Z:PANYARGS
?getdouble@istream@@AEAAHPEADH@Z TEXTEQU <__imp_?getdouble@istream@@AEAAHPEADH@Z>
extern __imp_?getint@istream@@AEAAHPEAD@Z:PANYARGS
?getint@istream@@AEAAHPEAD@Z TEXTEQU <__imp_?getint@istream@@AEAAHPEAD@Z>
extern __imp_?getline@istream@@QEAAAEAV1@PEACHD@Z:PANYARGS
?getline@istream@@QEAAAEAV1@PEACHD@Z TEXTEQU <__imp_?getline@istream@@QEAAAEAV1@PEACHD@Z>
extern __imp_?getline@istream@@QEAAAEAV1@PEADHD@Z:PANYARGS
?getline@istream@@QEAAAEAV1@PEADHD@Z TEXTEQU <__imp_?getline@istream@@QEAAAEAV1@PEADHD@Z>
extern __imp_?getline@istream@@QEAAAEAV1@PEAEHD@Z:PANYARGS
?getline@istream@@QEAAAEAV1@PEAEHD@Z TEXTEQU <__imp_?getline@istream@@QEAAAEAV1@PEAEHD@Z>
extern __imp_?good@ios@@QEBAHXZ:PANYARGS
?good@ios@@QEBAHXZ TEXTEQU <__imp_?good@ios@@QEBAHXZ>
extern __imp_?gptr@streambuf@@IEBAPEADXZ:PANYARGS
?gptr@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?gptr@streambuf@@IEBAPEADXZ>
extern __imp_?hex@@YAAEAVios@@AEAV1@@Z:PANYARGS
?hex@@YAAEAVios@@AEAV1@@Z TEXTEQU <__imp_?hex@@YAAEAVios@@AEAV1@@Z>
extern __imp_?ignore@istream@@QEAAAEAV1@HH@Z:PANYARGS
?ignore@istream@@QEAAAEAV1@HH@Z TEXTEQU <__imp_?ignore@istream@@QEAAAEAV1@HH@Z>
extern __imp_?in_avail@streambuf@@QEBAHXZ:PANYARGS
?in_avail@streambuf@@QEBAHXZ TEXTEQU <__imp_?in_avail@streambuf@@QEBAHXZ>
extern __imp_?init@ios@@IEAAXPEAVstreambuf@@@Z:PANYARGS
?init@ios@@IEAAXPEAVstreambuf@@@Z TEXTEQU <__imp_?init@ios@@IEAAXPEAVstreambuf@@@Z>
extern __imp_?ipfx@istream@@QEAAHH@Z:PANYARGS
?ipfx@istream@@QEAAHH@Z TEXTEQU <__imp_?ipfx@istream@@QEAAHH@Z>
extern __imp_?is_open@filebuf@@QEBAHXZ:PANYARGS
?is_open@filebuf@@QEBAHXZ TEXTEQU <__imp_?is_open@filebuf@@QEBAHXZ>
extern __imp_?is_open@fstream@@QEBAHXZ:PANYARGS
?is_open@fstream@@QEBAHXZ TEXTEQU <__imp_?is_open@fstream@@QEBAHXZ>
extern __imp_?is_open@ifstream@@QEBAHXZ:PANYARGS
?is_open@ifstream@@QEBAHXZ TEXTEQU <__imp_?is_open@ifstream@@QEBAHXZ>
extern __imp_?is_open@ofstream@@QEBAHXZ:PANYARGS
?is_open@ofstream@@QEBAHXZ TEXTEQU <__imp_?is_open@ofstream@@QEBAHXZ>
extern __imp_?isfx@istream@@QEAAXXZ:PANYARGS
?isfx@istream@@QEAAXXZ TEXTEQU <__imp_?isfx@istream@@QEAAXXZ>
extern __imp_?iword@ios@@QEBAAEAJH@Z:PANYARGS
?iword@ios@@QEBAAEAJH@Z TEXTEQU <__imp_?iword@ios@@QEBAAEAJH@Z>
extern __imp_?lock@ios@@QEAAXXZ:PANYARGS
?lock@ios@@QEAAXXZ TEXTEQU <__imp_?lock@ios@@QEAAXXZ>
extern __imp_?lock@streambuf@@QEAAXXZ:PANYARGS
?lock@streambuf@@QEAAXXZ TEXTEQU <__imp_?lock@streambuf@@QEAAXXZ>
extern __imp_?lockbuf@ios@@QEAAXXZ:PANYARGS
?lockbuf@ios@@QEAAXXZ TEXTEQU <__imp_?lockbuf@ios@@QEAAXXZ>
extern __imp_?lockc@ios@@KAXXZ:PANYARGS
?lockc@ios@@KAXXZ TEXTEQU <__imp_?lockc@ios@@KAXXZ>
extern __imp_?lockptr@ios@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ:PANYARGS
?lockptr@ios@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ TEXTEQU <__imp_?lockptr@ios@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ>
extern __imp_?lockptr@streambuf@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ:PANYARGS
?lockptr@streambuf@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ TEXTEQU <__imp_?lockptr@streambuf@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ>
extern __imp_?oct@@YAAEAVios@@AEAV1@@Z:PANYARGS
?oct@@YAAEAVios@@AEAV1@@Z TEXTEQU <__imp_?oct@@YAAEAVios@@AEAV1@@Z>
extern __imp_?open@filebuf@@QEAAPEAV1@PEBDHH@Z:PANYARGS
?open@filebuf@@QEAAPEAV1@PEBDHH@Z TEXTEQU <__imp_?open@filebuf@@QEAAPEAV1@PEBDHH@Z>
extern __imp_?open@fstream@@QEAAXPEBDHH@Z:PANYARGS
?open@fstream@@QEAAXPEBDHH@Z TEXTEQU <__imp_?open@fstream@@QEAAXPEBDHH@Z>
extern __imp_?open@ifstream@@QEAAXPEBDHH@Z:PANYARGS
?open@ifstream@@QEAAXPEBDHH@Z TEXTEQU <__imp_?open@ifstream@@QEAAXPEBDHH@Z>
extern __imp_?open@ofstream@@QEAAXPEBDHH@Z:PANYARGS
?open@ofstream@@QEAAXPEBDHH@Z TEXTEQU <__imp_?open@ofstream@@QEAAXPEBDHH@Z>
extern __imp_?openprot@filebuf@@2HB:PANYARGS
?openprot@filebuf@@2HB TEXTEQU <__imp_?openprot@filebuf@@2HB>
extern __imp_?opfx@ostream@@QEAAHXZ:PANYARGS
?opfx@ostream@@QEAAHXZ TEXTEQU <__imp_?opfx@ostream@@QEAAHXZ>
extern __imp_?osfx@ostream@@QEAAXXZ:PANYARGS
?osfx@ostream@@QEAAXXZ TEXTEQU <__imp_?osfx@ostream@@QEAAXXZ>
extern __imp_?out_waiting@streambuf@@QEBAHXZ:PANYARGS
?out_waiting@streambuf@@QEBAHXZ TEXTEQU <__imp_?out_waiting@streambuf@@QEBAHXZ>
extern __imp_?overflow@filebuf@@UEAAHH@Z:PANYARGS
?overflow@filebuf@@UEAAHH@Z TEXTEQU <__imp_?overflow@filebuf@@UEAAHH@Z>
extern __imp_?overflow@stdiobuf@@UEAAHH@Z:PANYARGS
?overflow@stdiobuf@@UEAAHH@Z TEXTEQU <__imp_?overflow@stdiobuf@@UEAAHH@Z>
extern __imp_?overflow@strstreambuf@@UEAAHH@Z:PANYARGS
?overflow@strstreambuf@@UEAAHH@Z TEXTEQU <__imp_?overflow@strstreambuf@@UEAAHH@Z>
extern __imp_?pbackfail@stdiobuf@@UEAAHH@Z:PANYARGS
?pbackfail@stdiobuf@@UEAAHH@Z TEXTEQU <__imp_?pbackfail@stdiobuf@@UEAAHH@Z>
extern __imp_?pbackfail@streambuf@@UEAAHH@Z:PANYARGS
?pbackfail@streambuf@@UEAAHH@Z TEXTEQU <__imp_?pbackfail@streambuf@@UEAAHH@Z>
extern __imp_?pbase@streambuf@@IEBAPEADXZ:PANYARGS
?pbase@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?pbase@streambuf@@IEBAPEADXZ>
extern __imp_?pbump@streambuf@@IEAAXH@Z:PANYARGS
?pbump@streambuf@@IEAAXH@Z TEXTEQU <__imp_?pbump@streambuf@@IEAAXH@Z>
extern __imp_?pcount@ostrstream@@QEBAHXZ:PANYARGS
?pcount@ostrstream@@QEBAHXZ TEXTEQU <__imp_?pcount@ostrstream@@QEBAHXZ>
extern __imp_?pcount@strstream@@QEBAHXZ:PANYARGS
?pcount@strstream@@QEBAHXZ TEXTEQU <__imp_?pcount@strstream@@QEBAHXZ>
extern __imp_?peek@istream@@QEAAHXZ:PANYARGS
?peek@istream@@QEAAHXZ TEXTEQU <__imp_?peek@istream@@QEAAHXZ>
extern __imp_?pptr@streambuf@@IEBAPEADXZ:PANYARGS
?pptr@streambuf@@IEBAPEADXZ TEXTEQU <__imp_?pptr@streambuf@@IEBAPEADXZ>
extern __imp_?precision@ios@@QEAAHH@Z:PANYARGS
?precision@ios@@QEAAHH@Z TEXTEQU <__imp_?precision@ios@@QEAAHH@Z>
extern __imp_?precision@ios@@QEBAHXZ:PANYARGS
?precision@ios@@QEBAHXZ TEXTEQU <__imp_?precision@ios@@QEBAHXZ>
extern __imp_?put@ostream@@QEAAAEAV1@C@Z:PANYARGS
?put@ostream@@QEAAAEAV1@C@Z TEXTEQU <__imp_?put@ostream@@QEAAAEAV1@C@Z>
extern __imp_?put@ostream@@QEAAAEAV1@D@Z:PANYARGS
?put@ostream@@QEAAAEAV1@D@Z TEXTEQU <__imp_?put@ostream@@QEAAAEAV1@D@Z>
extern __imp_?put@ostream@@QEAAAEAV1@E@Z:PANYARGS
?put@ostream@@QEAAAEAV1@E@Z TEXTEQU <__imp_?put@ostream@@QEAAAEAV1@E@Z>
extern __imp_?putback@istream@@QEAAAEAV1@D@Z:PANYARGS
?putback@istream@@QEAAAEAV1@D@Z TEXTEQU <__imp_?putback@istream@@QEAAAEAV1@D@Z>
extern __imp_?pword@ios@@QEBAAEAPEAXH@Z:PANYARGS
?pword@ios@@QEBAAEAPEAXH@Z TEXTEQU <__imp_?pword@ios@@QEBAAEAPEAXH@Z>
extern __imp_?rdbuf@fstream@@QEBAPEAVfilebuf@@XZ:PANYARGS
?rdbuf@fstream@@QEBAPEAVfilebuf@@XZ TEXTEQU <__imp_?rdbuf@fstream@@QEBAPEAVfilebuf@@XZ>
extern __imp_?rdbuf@ifstream@@QEBAPEAVfilebuf@@XZ:PANYARGS
?rdbuf@ifstream@@QEBAPEAVfilebuf@@XZ TEXTEQU <__imp_?rdbuf@ifstream@@QEBAPEAVfilebuf@@XZ>
extern __imp_?rdbuf@ios@@QEBAPEAVstreambuf@@XZ:PANYARGS
?rdbuf@ios@@QEBAPEAVstreambuf@@XZ TEXTEQU <__imp_?rdbuf@ios@@QEBAPEAVstreambuf@@XZ>
extern __imp_?rdbuf@istrstream@@QEBAPEAVstrstreambuf@@XZ:PANYARGS
?rdbuf@istrstream@@QEBAPEAVstrstreambuf@@XZ TEXTEQU <__imp_?rdbuf@istrstream@@QEBAPEAVstrstreambuf@@XZ>
extern __imp_?rdbuf@ofstream@@QEBAPEAVfilebuf@@XZ:PANYARGS
?rdbuf@ofstream@@QEBAPEAVfilebuf@@XZ TEXTEQU <__imp_?rdbuf@ofstream@@QEBAPEAVfilebuf@@XZ>
extern __imp_?rdbuf@ostrstream@@QEBAPEAVstrstreambuf@@XZ:PANYARGS
?rdbuf@ostrstream@@QEBAPEAVstrstreambuf@@XZ TEXTEQU <__imp_?rdbuf@ostrstream@@QEBAPEAVstrstreambuf@@XZ>
extern __imp_?rdbuf@stdiostream@@QEBAPEAVstdiobuf@@XZ:PANYARGS
?rdbuf@stdiostream@@QEBAPEAVstdiobuf@@XZ TEXTEQU <__imp_?rdbuf@stdiostream@@QEBAPEAVstdiobuf@@XZ>
extern __imp_?rdbuf@strstream@@QEBAPEAVstrstreambuf@@XZ:PANYARGS
?rdbuf@strstream@@QEBAPEAVstrstreambuf@@XZ TEXTEQU <__imp_?rdbuf@strstream@@QEBAPEAVstrstreambuf@@XZ>
extern __imp_?rdstate@ios@@QEBAHXZ:PANYARGS
?rdstate@ios@@QEBAHXZ TEXTEQU <__imp_?rdstate@ios@@QEBAHXZ>
extern __imp_?read@istream@@QEAAAEAV1@PEACH@Z:PANYARGS
?read@istream@@QEAAAEAV1@PEACH@Z TEXTEQU <__imp_?read@istream@@QEAAAEAV1@PEACH@Z>
extern __imp_?read@istream@@QEAAAEAV1@PEADH@Z:PANYARGS
?read@istream@@QEAAAEAV1@PEADH@Z TEXTEQU <__imp_?read@istream@@QEAAAEAV1@PEADH@Z>
extern __imp_?read@istream@@QEAAAEAV1@PEAEH@Z:PANYARGS
?read@istream@@QEAAAEAV1@PEAEH@Z TEXTEQU <__imp_?read@istream@@QEAAAEAV1@PEAEH@Z>
extern __imp_?sbumpc@streambuf@@QEAAHXZ:PANYARGS
?sbumpc@streambuf@@QEAAHXZ TEXTEQU <__imp_?sbumpc@streambuf@@QEAAHXZ>
extern __imp_?seekg@istream@@QEAAAEAV1@J@Z:PANYARGS
?seekg@istream@@QEAAAEAV1@J@Z TEXTEQU <__imp_?seekg@istream@@QEAAAEAV1@J@Z>
extern __imp_?seekg@istream@@QEAAAEAV1@JW4seek_dir@ios@@@Z:PANYARGS
?seekg@istream@@QEAAAEAV1@JW4seek_dir@ios@@@Z TEXTEQU <__imp_?seekg@istream@@QEAAAEAV1@JW4seek_dir@ios@@@Z>
extern __imp_?seekoff@filebuf@@UEAAJJW4seek_dir@ios@@H@Z:PANYARGS
?seekoff@filebuf@@UEAAJJW4seek_dir@ios@@H@Z TEXTEQU <__imp_?seekoff@filebuf@@UEAAJJW4seek_dir@ios@@H@Z>
extern __imp_?seekoff@stdiobuf@@UEAAJJW4seek_dir@ios@@H@Z:PANYARGS
?seekoff@stdiobuf@@UEAAJJW4seek_dir@ios@@H@Z TEXTEQU <__imp_?seekoff@stdiobuf@@UEAAJJW4seek_dir@ios@@H@Z>
extern __imp_?seekoff@streambuf@@UEAAJJW4seek_dir@ios@@H@Z:PANYARGS
?seekoff@streambuf@@UEAAJJW4seek_dir@ios@@H@Z TEXTEQU <__imp_?seekoff@streambuf@@UEAAJJW4seek_dir@ios@@H@Z>
extern __imp_?seekoff@strstreambuf@@UEAAJJW4seek_dir@ios@@H@Z:PANYARGS
?seekoff@strstreambuf@@UEAAJJW4seek_dir@ios@@H@Z TEXTEQU <__imp_?seekoff@strstreambuf@@UEAAJJW4seek_dir@ios@@H@Z>
extern __imp_?seekp@ostream@@QEAAAEAV1@J@Z:PANYARGS
?seekp@ostream@@QEAAAEAV1@J@Z TEXTEQU <__imp_?seekp@ostream@@QEAAAEAV1@J@Z>
extern __imp_?seekp@ostream@@QEAAAEAV1@JW4seek_dir@ios@@@Z:PANYARGS
?seekp@ostream@@QEAAAEAV1@JW4seek_dir@ios@@@Z TEXTEQU <__imp_?seekp@ostream@@QEAAAEAV1@JW4seek_dir@ios@@@Z>
extern __imp_?seekpos@streambuf@@UEAAJJH@Z:PANYARGS
?seekpos@streambuf@@UEAAJJH@Z TEXTEQU <__imp_?seekpos@streambuf@@UEAAJJH@Z>
extern __imp_?setb@streambuf@@IEAAXPEAD0H@Z:PANYARGS
?setb@streambuf@@IEAAXPEAD0H@Z TEXTEQU <__imp_?setb@streambuf@@IEAAXPEAD0H@Z>
extern __imp_?setbuf@filebuf@@UEAAPEAVstreambuf@@PEADH@Z:PANYARGS
?setbuf@filebuf@@UEAAPEAVstreambuf@@PEADH@Z TEXTEQU <__imp_?setbuf@filebuf@@UEAAPEAVstreambuf@@PEADH@Z>
extern __imp_?setbuf@fstream@@QEAAPEAVstreambuf@@PEADH@Z:PANYARGS
?setbuf@fstream@@QEAAPEAVstreambuf@@PEADH@Z TEXTEQU <__imp_?setbuf@fstream@@QEAAPEAVstreambuf@@PEADH@Z>
extern __imp_?setbuf@ifstream@@QEAAPEAVstreambuf@@PEADH@Z:PANYARGS
?setbuf@ifstream@@QEAAPEAVstreambuf@@PEADH@Z TEXTEQU <__imp_?setbuf@ifstream@@QEAAPEAVstreambuf@@PEADH@Z>
extern __imp_?setbuf@ofstream@@QEAAPEAVstreambuf@@PEADH@Z:PANYARGS
?setbuf@ofstream@@QEAAPEAVstreambuf@@PEADH@Z TEXTEQU <__imp_?setbuf@ofstream@@QEAAPEAVstreambuf@@PEADH@Z>
extern __imp_?setbuf@streambuf@@UEAAPEAV1@PEADH@Z:PANYARGS
?setbuf@streambuf@@UEAAPEAV1@PEADH@Z TEXTEQU <__imp_?setbuf@streambuf@@UEAAPEAV1@PEADH@Z>
extern __imp_?setbuf@strstreambuf@@UEAAPEAVstreambuf@@PEADH@Z:PANYARGS
?setbuf@strstreambuf@@UEAAPEAVstreambuf@@PEADH@Z TEXTEQU <__imp_?setbuf@strstreambuf@@UEAAPEAVstreambuf@@PEADH@Z>
extern __imp_?setf@ios@@QEAAJJ@Z:PANYARGS
?setf@ios@@QEAAJJ@Z TEXTEQU <__imp_?setf@ios@@QEAAJJ@Z>
extern __imp_?setf@ios@@QEAAJJJ@Z:PANYARGS
?setf@ios@@QEAAJJJ@Z TEXTEQU <__imp_?setf@ios@@QEAAJJJ@Z>
extern __imp_?setg@streambuf@@IEAAXPEAD00@Z:PANYARGS
?setg@streambuf@@IEAAXPEAD00@Z TEXTEQU <__imp_?setg@streambuf@@IEAAXPEAD00@Z>
extern __imp_?setlock@ios@@QEAAXXZ:PANYARGS
?setlock@ios@@QEAAXXZ TEXTEQU <__imp_?setlock@ios@@QEAAXXZ>
extern __imp_?setlock@streambuf@@QEAAXXZ:PANYARGS
?setlock@streambuf@@QEAAXXZ TEXTEQU <__imp_?setlock@streambuf@@QEAAXXZ>
extern __imp_?setmode@filebuf@@QEAAHH@Z:PANYARGS
?setmode@filebuf@@QEAAHH@Z TEXTEQU <__imp_?setmode@filebuf@@QEAAHH@Z>
extern __imp_?setmode@fstream@@QEAAHH@Z:PANYARGS
?setmode@fstream@@QEAAHH@Z TEXTEQU <__imp_?setmode@fstream@@QEAAHH@Z>
extern __imp_?setmode@ifstream@@QEAAHH@Z:PANYARGS
?setmode@ifstream@@QEAAHH@Z TEXTEQU <__imp_?setmode@ifstream@@QEAAHH@Z>
extern __imp_?setmode@ofstream@@QEAAHH@Z:PANYARGS
?setmode@ofstream@@QEAAHH@Z TEXTEQU <__imp_?setmode@ofstream@@QEAAHH@Z>
extern __imp_?setp@streambuf@@IEAAXPEAD0@Z:PANYARGS
?setp@streambuf@@IEAAXPEAD0@Z TEXTEQU <__imp_?setp@streambuf@@IEAAXPEAD0@Z>
extern __imp_?setrwbuf@stdiobuf@@QEAAHHH@Z:PANYARGS
?setrwbuf@stdiobuf@@QEAAHHH@Z TEXTEQU <__imp_?setrwbuf@stdiobuf@@QEAAHHH@Z>
extern __imp_?sgetc@streambuf@@QEAAHXZ:PANYARGS
?sgetc@streambuf@@QEAAHXZ TEXTEQU <__imp_?sgetc@streambuf@@QEAAHXZ>
extern __imp_?sgetn@streambuf@@QEAAHPEADH@Z:PANYARGS
?sgetn@streambuf@@QEAAHPEADH@Z TEXTEQU <__imp_?sgetn@streambuf@@QEAAHPEADH@Z>
extern __imp_?sh_none@filebuf@@2HB:PANYARGS
?sh_none@filebuf@@2HB TEXTEQU <__imp_?sh_none@filebuf@@2HB>
extern __imp_?sh_read@filebuf@@2HB:PANYARGS
?sh_read@filebuf@@2HB TEXTEQU <__imp_?sh_read@filebuf@@2HB>
extern __imp_?sh_write@filebuf@@2HB:PANYARGS
?sh_write@filebuf@@2HB TEXTEQU <__imp_?sh_write@filebuf@@2HB>
extern __imp_?snextc@streambuf@@QEAAHXZ:PANYARGS
?snextc@streambuf@@QEAAHXZ TEXTEQU <__imp_?snextc@streambuf@@QEAAHXZ>
extern __imp_?sputbackc@streambuf@@QEAAHD@Z:PANYARGS
?sputbackc@streambuf@@QEAAHD@Z TEXTEQU <__imp_?sputbackc@streambuf@@QEAAHD@Z>
extern __imp_?sputc@streambuf@@QEAAHH@Z:PANYARGS
?sputc@streambuf@@QEAAHH@Z TEXTEQU <__imp_?sputc@streambuf@@QEAAHH@Z>
extern __imp_?sputn@streambuf@@QEAAHPEBDH@Z:PANYARGS
?sputn@streambuf@@QEAAHPEBDH@Z TEXTEQU <__imp_?sputn@streambuf@@QEAAHPEBDH@Z>
extern __imp_?stdiofile@stdiobuf@@QEAAPEAU_iobuf@@XZ:PANYARGS
?stdiofile@stdiobuf@@QEAAPEAU_iobuf@@XZ TEXTEQU <__imp_?stdiofile@stdiobuf@@QEAAPEAU_iobuf@@XZ>
extern __imp_?stossc@streambuf@@QEAAXXZ:PANYARGS
?stossc@streambuf@@QEAAXXZ TEXTEQU <__imp_?stossc@streambuf@@QEAAXXZ>
extern __imp_?str@istrstream@@QEAAPEADXZ:PANYARGS
?str@istrstream@@QEAAPEADXZ TEXTEQU <__imp_?str@istrstream@@QEAAPEADXZ>
extern __imp_?str@ostrstream@@QEAAPEADXZ:PANYARGS
?str@ostrstream@@QEAAPEADXZ TEXTEQU <__imp_?str@ostrstream@@QEAAPEADXZ>
extern __imp_?str@strstream@@QEAAPEADXZ:PANYARGS
?str@strstream@@QEAAPEADXZ TEXTEQU <__imp_?str@strstream@@QEAAPEADXZ>
extern __imp_?str@strstreambuf@@QEAAPEADXZ:PANYARGS
?str@strstreambuf@@QEAAPEADXZ TEXTEQU <__imp_?str@strstreambuf@@QEAAPEADXZ>
extern __imp_?sunk_with_stdio@ios@@0HA:PANYARGS
?sunk_with_stdio@ios@@0H  TEXTEQU <__imp_?sunk_with_stdio@ios@@0HA>
extern __imp_?sync@filebuf@@UEAAHXZ:PANYARGS
?sync@filebuf@@UEAAHXZ TEXTEQU <__imp_?sync@filebuf@@UEAAHXZ>
extern __imp_?sync@istream@@QEAAHXZ:PANYARGS
?sync@istream@@QEAAHXZ TEXTEQU <__imp_?sync@istream@@QEAAHXZ>
extern __imp_?sync@stdiobuf@@UEAAHXZ:PANYARGS
?sync@stdiobuf@@UEAAHXZ TEXTEQU <__imp_?sync@stdiobuf@@UEAAHXZ>
extern __imp_?sync@streambuf@@UEAAHXZ:PANYARGS
?sync@streambuf@@UEAAHXZ TEXTEQU <__imp_?sync@streambuf@@UEAAHXZ>
extern __imp_?sync@strstreambuf@@UEAAHXZ:PANYARGS
?sync@strstreambuf@@UEAAHXZ TEXTEQU <__imp_?sync@strstreambuf@@UEAAHXZ>
extern __imp_?sync_with_stdio@ios@@SAXXZ:PANYARGS
?sync_with_stdio@ios@@SAXXZ TEXTEQU <__imp_?sync_with_stdio@ios@@SAXXZ>
extern __imp_?tellg@istream@@QEAAJXZ:PANYARGS
?tellg@istream@@QEAAJXZ TEXTEQU <__imp_?tellg@istream@@QEAAJXZ>
extern __imp_?tellp@ostream@@QEAAJXZ:PANYARGS
?tellp@ostream@@QEAAJXZ TEXTEQU <__imp_?tellp@ostream@@QEAAJXZ>
extern __imp_?text@filebuf@@2HB:PANYARGS
?text@filebuf@@2HB TEXTEQU <__imp_?text@filebuf@@2HB>
extern __imp_?tie@ios@@QEAAPEAVostream@@PEAV2@@Z:PANYARGS
?tie@ios@@QEAAPEAVostream@@PEAV2@@Z TEXTEQU <__imp_?tie@ios@@QEAAPEAVostream@@PEAV2@@Z>
extern __imp_?tie@ios@@QEBAPEAVostream@@XZ:PANYARGS
?tie@ios@@QEBAPEAVostream@@XZ TEXTEQU <__imp_?tie@ios@@QEBAPEAVostream@@XZ>
extern __imp_?unbuffered@streambuf@@IEAAXH@Z:PANYARGS
?unbuffered@streambuf@@IEAAXH@Z TEXTEQU <__imp_?unbuffered@streambuf@@IEAAXH@Z>
extern __imp_?unbuffered@streambuf@@IEBAHXZ:PANYARGS
?unbuffered@streambuf@@IEBAHXZ TEXTEQU <__imp_?unbuffered@streambuf@@IEBAHXZ>
extern __imp_?underflow@filebuf@@UEAAHXZ:PANYARGS
?underflow@filebuf@@UEAAHXZ TEXTEQU <__imp_?underflow@filebuf@@UEAAHXZ>
extern __imp_?underflow@stdiobuf@@UEAAHXZ:PANYARGS
?underflow@stdiobuf@@UEAAHXZ TEXTEQU <__imp_?underflow@stdiobuf@@UEAAHXZ>
extern __imp_?underflow@strstreambuf@@UEAAHXZ:PANYARGS
?underflow@strstreambuf@@UEAAHXZ TEXTEQU <__imp_?underflow@strstreambuf@@UEAAHXZ>
extern __imp_?unlock@ios@@QEAAXXZ:PANYARGS
?unlock@ios@@QEAAXXZ TEXTEQU <__imp_?unlock@ios@@QEAAXXZ>
extern __imp_?unlock@streambuf@@QEAAXXZ:PANYARGS
?unlock@streambuf@@QEAAXXZ TEXTEQU <__imp_?unlock@streambuf@@QEAAXXZ>
extern __imp_?unlockbuf@ios@@QEAAXXZ:PANYARGS
?unlockbuf@ios@@QEAAXXZ TEXTEQU <__imp_?unlockbuf@ios@@QEAAXXZ>
extern __imp_?unlockc@ios@@KAXXZ:PANYARGS
?unlockc@ios@@KAXXZ TEXTEQU <__imp_?unlockc@ios@@KAXXZ>
extern __imp_?unsetf@ios@@QEAAJJ@Z:PANYARGS
?unsetf@ios@@QEAAJJ@Z TEXTEQU <__imp_?unsetf@ios@@QEAAJJ@Z>
extern __imp_?what@exception@@UEBAPEBDXZ:PANYARGS
?what@exception@@UEBAPEBDXZ TEXTEQU <__imp_?what@exception@@UEBAPEBDXZ>
extern __imp_?width@ios@@QEAAHH@Z:PANYARGS
?width@ios@@QEAAHH@Z TEXTEQU <__imp_?width@ios@@QEAAHH@Z>
extern __imp_?width@ios@@QEBAHXZ:PANYARGS
?width@ios@@QEBAHXZ TEXTEQU <__imp_?width@ios@@QEBAHXZ>
extern __imp_?write@ostream@@QEAAAEAV1@PEBCH@Z:PANYARGS
?write@ostream@@QEAAAEAV1@PEBCH@Z TEXTEQU <__imp_?write@ostream@@QEAAAEAV1@PEBCH@Z>
extern __imp_?write@ostream@@QEAAAEAV1@PEBDH@Z:PANYARGS
?write@ostream@@QEAAAEAV1@PEBDH@Z TEXTEQU <__imp_?write@ostream@@QEAAAEAV1@PEBDH@Z>
extern __imp_?write@ostream@@QEAAAEAV1@PEBEH@Z:PANYARGS
?write@ostream@@QEAAAEAV1@PEBEH@Z TEXTEQU <__imp_?write@ostream@@QEAAAEAV1@PEBEH@Z>
extern __imp_?writepad@ostream@@AEAAAEAV1@PEBD0@Z:PANYARGS
?writepad@ostream@@AEAAAEAV1@PEBD0@Z TEXTEQU <__imp_?writepad@ostream@@AEAAAEAV1@PEBD0@Z>
extern __imp_?ws@@YAAEAVistream@@AEAV1@@Z:PANYARGS
?ws@@YAAEAVistream@@AEAV1@@Z TEXTEQU <__imp_?ws@@YAAEAVistream@@AEAV1@@Z>
extern __imp_?x_curindex@ios@@0HA:PANYARGS
?x_curindex@ios@@0H  TEXTEQU <__imp_?x_curindex@ios@@0HA>
extern __imp_?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@A:PANYARGS
?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@  TEXTEQU <__imp_?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@A>
extern __imp_?x_maxbit@ios@@0JA:PANYARGS
?x_maxbit@ios@@0J  TEXTEQU <__imp_?x_maxbit@ios@@0JA>
extern __imp_?x_statebuf@ios@@0PAJA:PANYARGS
?x_statebuf@ios@@0PAJ  TEXTEQU <__imp_?x_statebuf@ios@@0PAJA>
extern __imp_?xalloc@ios@@SAHXZ:PANYARGS
?xalloc@ios@@SAHXZ TEXTEQU <__imp_?xalloc@ios@@SAHXZ>
extern __imp_?xsgetn@streambuf@@UEAAHPEADH@Z:PANYARGS
?xsgetn@streambuf@@UEAAHPEADH@Z TEXTEQU <__imp_?xsgetn@streambuf@@UEAAHPEADH@Z>
extern __imp_?xsputn@streambuf@@UEAAHPEBDH@Z:PANYARGS
?xsputn@streambuf@@UEAAHPEBDH@Z TEXTEQU <__imp_?xsputn@streambuf@@UEAAHPEBDH@Z>
extern __imp___dummy_export:PANYARGS
__dummy_export TEXTEQU <__imp___dummy_export>
extern __imp__mtlock:PANYARGS
_mtlock TEXTEQU <__imp__mtlock>
extern __imp__mtunlock:PANYARGS
_mtunlock TEXTEQU <__imp__mtunlock>
