extern __imp_$I10_OUTPUT:PANYARGS
$I10_OUTPUT TEXTEQU <__imp_$I10_OUTPUT>
extern __imp_??0__non_rtti_object@@QEAA@AEBV0@@Z:PANYARGS
??0__non_rtti_object@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0__non_rtti_object@@QEAA@AEBV0@@Z>
extern __imp_??0__non_rtti_object@@QEAA@PEBD@Z:PANYARGS
??0__non_rtti_object@@QEAA@PEBD@Z TEXTEQU <__imp_??0__non_rtti_object@@QEAA@PEBD@Z>
extern __imp_??0bad_cast@@AEAA@PEBQEBD@Z:PANYARGS
??0bad_cast@@AEAA@PEBQEBD@Z TEXTEQU <__imp_??0bad_cast@@AEAA@PEBQEBD@Z>
extern __imp_??0bad_cast@@QEAA@AEBQEBD@Z:PANYARGS
??0bad_cast@@QEAA@AEBQEBD@Z TEXTEQU <__imp_??0bad_cast@@QEAA@AEBQEBD@Z>
extern __imp_??0bad_cast@@QEAA@AEBV0@@Z:PANYARGS
??0bad_cast@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0bad_cast@@QEAA@AEBV0@@Z>
extern __imp_??0bad_cast@@QEAA@PEBD@Z:PANYARGS
??0bad_cast@@QEAA@PEBD@Z TEXTEQU <__imp_??0bad_cast@@QEAA@PEBD@Z>
extern __imp_??0bad_typeid@@QEAA@AEBV0@@Z:PANYARGS
??0bad_typeid@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0bad_typeid@@QEAA@AEBV0@@Z>
extern __imp_??0bad_typeid@@QEAA@PEBD@Z:PANYARGS
??0bad_typeid@@QEAA@PEBD@Z TEXTEQU <__imp_??0bad_typeid@@QEAA@PEBD@Z>
extern __imp_??0exception@@QEAA@AEBQEBD@Z:PANYARGS
??0exception@@QEAA@AEBQEBD@Z TEXTEQU <__imp_??0exception@@QEAA@AEBQEBD@Z>
extern __imp_??0exception@@QEAA@AEBQEBDH@Z:PANYARGS
??0exception@@QEAA@AEBQEBDH@Z TEXTEQU <__imp_??0exception@@QEAA@AEBQEBDH@Z>
extern __imp_??0exception@@QEAA@AEBV0@@Z:PANYARGS
??0exception@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0exception@@QEAA@AEBV0@@Z>
extern __imp_??0exception@@QEAA@XZ:PANYARGS
??0exception@@QEAA@XZ TEXTEQU <__imp_??0exception@@QEAA@XZ>
extern __imp_??1__non_rtti_object@@UEAA@XZ:PANYARGS
??1__non_rtti_object@@UEAA@XZ TEXTEQU <__imp_??1__non_rtti_object@@UEAA@XZ>
extern __imp_??1bad_cast@@UEAA@XZ:PANYARGS
??1bad_cast@@UEAA@XZ TEXTEQU <__imp_??1bad_cast@@UEAA@XZ>
extern __imp_??1bad_typeid@@UEAA@XZ:PANYARGS
??1bad_typeid@@UEAA@XZ TEXTEQU <__imp_??1bad_typeid@@UEAA@XZ>
extern __imp_??1exception@@UEAA@XZ:PANYARGS
??1exception@@UEAA@XZ TEXTEQU <__imp_??1exception@@UEAA@XZ>
extern __imp_??1type_info@@UEAA@XZ:PANYARGS
??1type_info@@UEAA@XZ TEXTEQU <__imp_??1type_info@@UEAA@XZ>
extern __imp_??2@YAPEAX_K@Z:PANYARGS
??2@YAPEAX_K@Z TEXTEQU <__imp_??2@YAPEAX_K@Z>
extern __imp_??3@YAXPEAX@Z:PANYARGS
??3@YAXPEAX@Z TEXTEQU <__imp_??3@YAXPEAX@Z>
extern __imp_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4bad_cast@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4bad_cast@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4bad_cast@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4bad_typeid@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4exception@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4exception@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4exception@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??8type_info@@QEBAHAEBV0@@Z:PANYARGS
??8type_info@@QEBAHAEBV0@@Z TEXTEQU <__imp_??8type_info@@QEBAHAEBV0@@Z>
extern __imp_??9type_info@@QEBAHAEBV0@@Z:PANYARGS
??9type_info@@QEBAHAEBV0@@Z TEXTEQU <__imp_??9type_info@@QEBAHAEBV0@@Z>
extern __imp_??_7__non_rtti_object@@6B@:PANYARGS
??_7__non_rtti_object@@6B@ TEXTEQU <__imp_??_7__non_rtti_object@@6B@>
extern __imp_??_7bad_cast@@6B@:PANYARGS
??_7bad_cast@@6B@ TEXTEQU <__imp_??_7bad_cast@@6B@>
extern __imp_??_7bad_typeid@@6B@:PANYARGS
??_7bad_typeid@@6B@ TEXTEQU <__imp_??_7bad_typeid@@6B@>
extern __imp_??_7exception@@6B@:PANYARGS
??_7exception@@6B@ TEXTEQU <__imp_??_7exception@@6B@>
extern __imp_??_Fbad_cast@@QEAAXXZ:PANYARGS
??_Fbad_cast@@QEAAXXZ TEXTEQU <__imp_??_Fbad_cast@@QEAAXXZ>
extern __imp_??_Fbad_typeid@@QEAAXXZ:PANYARGS
??_Fbad_typeid@@QEAAXXZ TEXTEQU <__imp_??_Fbad_typeid@@QEAAXXZ>
extern __imp_??_U@YAPEAX_K@Z:PANYARGS
??_U@YAPEAX_K@Z TEXTEQU <__imp_??_U@YAPEAX_K@Z>
extern __imp_??_V@YAXPEAX@Z:PANYARGS
??_V@YAXPEAX@Z TEXTEQU <__imp_??_V@YAXPEAX@Z>
extern __imp___uncaught_exception:PANYARGS
__uncaught_exception TEXTEQU <__imp___uncaught_exception>
extern __imp_?_query_new_handler@@YAP6AH_K@ZXZ:PANYARGS
?_query_new_handler@@YAP6AH_K@ZXZ TEXTEQU <__imp_?_query_new_handler@@YAP6AH_K@ZXZ>
extern __imp_?_query_new_mode@@YAHXZ:PANYARGS
?_query_new_mode@@YAHXZ TEXTEQU <__imp_?_query_new_mode@@YAHXZ>
extern __imp_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z:PANYARGS
?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z TEXTEQU <__imp_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z>
extern __imp_?_set_new_mode@@YAHH@Z:PANYARGS
?_set_new_mode@@YAHH@Z TEXTEQU <__imp_?_set_new_mode@@YAHH@Z>
extern __imp_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z:PANYARGS
?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z TEXTEQU <__imp_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z>
extern __imp_?before@type_info@@QEBAHAEBV1@@Z:PANYARGS
?before@type_info@@QEBAHAEBV1@@Z TEXTEQU <__imp_?before@type_info@@QEBAHAEBV1@@Z>
extern __imp_?name@type_info@@QEBAPEBDXZ:PANYARGS
?name@type_info@@QEBAPEBDXZ TEXTEQU <__imp_?name@type_info@@QEBAPEBDXZ>
extern __imp_?raw_name@type_info@@QEBAPEBDXZ:PANYARGS
?raw_name@type_info@@QEBAPEBDXZ TEXTEQU <__imp_?raw_name@type_info@@QEBAPEBDXZ>
extern __imp_?set_new_handler@@YAP6AXXZP6AXXZ@Z:PANYARGS
?set_new_handler@@YAP6AXXZP6AXXZ@Z TEXTEQU <__imp_?set_new_handler@@YAP6AXXZP6AXXZ@Z>
extern __imp_?set_terminate@@YAP6AXXZP6AXXZ@Z:PANYARGS
?set_terminate@@YAP6AXXZP6AXXZ@Z TEXTEQU <__imp_?set_terminate@@YAP6AXXZP6AXXZ@Z>
extern __imp_?set_unexpected@@YAP6AXXZP6AXXZ@Z:PANYARGS
?set_unexpected@@YAP6AXXZP6AXXZ@Z TEXTEQU <__imp_?set_unexpected@@YAP6AXXZP6AXXZ@Z>
extern __imp_?terminate@@YAXXZ:PANYARGS
?terminate@@YAXXZ TEXTEQU <__imp_?terminate@@YAXXZ>
extern __imp_?unexpected@@YAXXZ:PANYARGS
?unexpected@@YAXXZ TEXTEQU <__imp_?unexpected@@YAXXZ>
extern __imp_?what@exception@@UEBAPEBDXZ:PANYARGS
?what@exception@@UEBAPEBDXZ TEXTEQU <__imp_?what@exception@@UEBAPEBDXZ>
extern __imp__CxxThrowException:PANYARGS
_CxxThrowException TEXTEQU <__imp__CxxThrowException>
extern __imp__Getdays:PANYARGS
_Getdays TEXTEQU <__imp__Getdays>
extern __imp__Getmonths:PANYARGS
_Getmonths TEXTEQU <__imp__Getmonths>
extern __imp__Gettnames:PANYARGS
_Gettnames TEXTEQU <__imp__Gettnames>
extern __imp__HUGE:PANYARGS
_HUGE TEXTEQU <__imp__HUGE>
extern __imp__Strftime:PANYARGS
_Strftime TEXTEQU <__imp__Strftime>
extern __imp__XcptFilter:PANYARGS
_XcptFilter TEXTEQU <__imp__XcptFilter>
extern __imp___C_specific_handler:PANYARGS
__C_specific_handler TEXTEQU <__imp___C_specific_handler>
extern __imp___CppXcptFilter:PANYARGS
__CppXcptFilter TEXTEQU <__imp___CppXcptFilter>
extern __imp___CxxFrameHandler:PANYARGS
__CxxFrameHandler TEXTEQU <__imp___CxxFrameHandler>
extern __imp___DestructExceptionObject:PANYARGS
__DestructExceptionObject TEXTEQU <__imp___DestructExceptionObject>
extern __imp___RTCastToVoid:PANYARGS
__RTCastToVoid TEXTEQU <__imp___RTCastToVoid>
extern __imp___RTDynamicCast:PANYARGS
__RTDynamicCast TEXTEQU <__imp___RTDynamicCast>
extern __imp___RTtypeid:PANYARGS
__RTtypeid TEXTEQU <__imp___RTtypeid>
extern __imp___STRINGTOLD:PANYARGS
__STRINGTOLD TEXTEQU <__imp___STRINGTOLD>
extern __imp____lc_codepage_func:PANYARGS
___lc_codepage_func TEXTEQU <__imp____lc_codepage_func>
extern __imp____lc_collate_cp_func:PANYARGS
___lc_collate_cp_func TEXTEQU <__imp____lc_collate_cp_func>
extern __imp____lc_handle_func:PANYARGS
___lc_handle_func TEXTEQU <__imp____lc_handle_func>
extern __imp____mb_cur_max_func:PANYARGS
___mb_cur_max_func TEXTEQU <__imp____mb_cur_max_func>
extern __imp____setlc_active_func:PANYARGS
___setlc_active_func TEXTEQU <__imp____setlc_active_func>
extern __imp____unguarded_readlc_active_add_func:PANYARGS
___unguarded_readlc_active_add_func TEXTEQU <__imp____unguarded_readlc_active_add_func>
extern __imp___argc:PANYARGS
__argc TEXTEQU <__imp___argc>
extern __imp___argv:PANYARGS
__argv TEXTEQU <__imp___argv>
extern __imp___badioinfo:PANYARGS
__badioinfo TEXTEQU <__imp___badioinfo>
extern __imp___crtCompareStringA:PANYARGS
__crtCompareString  TEXTEQU <__imp___crtCompareStringA>
extern __imp___crtCompareStringW:PANYARGS
__crtCompareStringW TEXTEQU <__imp___crtCompareStringW>
extern __imp___crtGetLocaleInfoW:PANYARGS
__crtGetLocaleInfoW TEXTEQU <__imp___crtGetLocaleInfoW>
extern __imp___crtGetStringTypeW:PANYARGS
__crtGetStringTypeW TEXTEQU <__imp___crtGetStringTypeW>
extern __imp___crtLCMapStringA:PANYARGS
__crtLCMapString  TEXTEQU <__imp___crtLCMapStringA>
extern __imp___crtLCMapStringW:PANYARGS
__crtLCMapStringW TEXTEQU <__imp___crtLCMapStringW>
extern __imp___dllonexit:PANYARGS
__dllonexit TEXTEQU <__imp___dllonexit>
extern __imp___doserrno:PANYARGS
__doserrno TEXTEQU <__imp___doserrno>
extern __imp___fpecode:PANYARGS
__fpecode TEXTEQU <__imp___fpecode>
extern __imp___getmainargs:PANYARGS
__getmainargs TEXTEQU <__imp___getmainargs>
extern __imp___initenv:PANYARGS
__initenv TEXTEQU <__imp___initenv>
extern __imp___iob_func:PANYARGS
__iob_func TEXTEQU <__imp___iob_func>
extern __imp___isascii:PANYARGS
__isascii TEXTEQU <__imp___isascii>
extern __imp___iscsym:PANYARGS
__iscsym TEXTEQU <__imp___iscsym>
extern __imp___iscsymf:PANYARGS
__iscsymf TEXTEQU <__imp___iscsymf>
extern __imp___lc_codepage:PANYARGS
__lc_codepage TEXTEQU <__imp___lc_codepage>
extern __imp___lc_collate_cp:PANYARGS
__lc_collate_cp TEXTEQU <__imp___lc_collate_cp>
extern __imp___lc_handle:PANYARGS
__lc_handle TEXTEQU <__imp___lc_handle>
extern __imp___lconv_init:PANYARGS
__lconv_init TEXTEQU <__imp___lconv_init>
extern __imp___mb_cur_max:PANYARGS
__mb_cur_max TEXTEQU <__imp___mb_cur_max>
extern __imp___pctype_func:PANYARGS
__pctype_func TEXTEQU <__imp___pctype_func>
extern __imp___pioinfo:PANYARGS
__pioinfo TEXTEQU <__imp___pioinfo>
extern __imp___pwctype_func:PANYARGS
__pwctype_func TEXTEQU <__imp___pwctype_func>
extern __imp___pxcptinfoptrs:PANYARGS
__pxcptinfoptrs TEXTEQU <__imp___pxcptinfoptrs>
extern __imp___set_app_type:PANYARGS
__set_app_type TEXTEQU <__imp___set_app_type>
extern __imp___setlc_active:PANYARGS
__setlc_active TEXTEQU <__imp___setlc_active>
extern __imp___setusermatherr:PANYARGS
__setusermatherr TEXTEQU <__imp___setusermatherr>
extern __imp___threadhandle:PANYARGS
__threadhandle TEXTEQU <__imp___threadhandle>
extern __imp___threadid:PANYARGS
__threadid TEXTEQU <__imp___threadid>
extern __imp___toascii:PANYARGS
__toascii TEXTEQU <__imp___toascii>
extern __imp___unDName:PANYARGS
__unDName TEXTEQU <__imp___unDName>
extern __imp___unDNameEx:PANYARGS
__unDNameEx TEXTEQU <__imp___unDNameEx>
extern __imp___unguarded_readlc_active:PANYARGS
__unguarded_readlc_active TEXTEQU <__imp___unguarded_readlc_active>
extern __imp___wargv:PANYARGS
__wargv TEXTEQU <__imp___wargv>
extern __imp___wcserror:PANYARGS
__wcserror TEXTEQU <__imp___wcserror>
extern __imp___wgetmainargs:PANYARGS
__wgetmainargs TEXTEQU <__imp___wgetmainargs>
extern __imp___winitenv:PANYARGS
__winitenv TEXTEQU <__imp___winitenv>
extern __imp__abs64:PANYARGS
_abs64 TEXTEQU <__imp__abs64>
extern __imp__access:PANYARGS
_access TEXTEQU <__imp__access>
extern __imp__acmdln:PANYARGS
_acmdln TEXTEQU <__imp__acmdln>
extern __imp__aexit_rtn:PANYARGS
_aexit_rtn TEXTEQU <__imp__aexit_rtn>
extern __imp__aligned_free:PANYARGS
_aligned_free TEXTEQU <__imp__aligned_free>
extern __imp__aligned_malloc:PANYARGS
_aligned_malloc TEXTEQU <__imp__aligned_malloc>
extern __imp__aligned_offset_malloc:PANYARGS
_aligned_offset_malloc TEXTEQU <__imp__aligned_offset_malloc>
extern __imp__aligned_offset_realloc:PANYARGS
_aligned_offset_realloc TEXTEQU <__imp__aligned_offset_realloc>
extern __imp__aligned_realloc:PANYARGS
_aligned_realloc TEXTEQU <__imp__aligned_realloc>
extern __imp__amsg_exit:PANYARGS
_amsg_exit TEXTEQU <__imp__amsg_exit>
extern __imp__assert:PANYARGS
_assert TEXTEQU <__imp__assert>
extern __imp__atodbl:PANYARGS
_atodbl TEXTEQU <__imp__atodbl>
extern __imp__atoi64:PANYARGS
_atoi64 TEXTEQU <__imp__atoi64>
extern __imp__atoldbl:PANYARGS
_atoldbl TEXTEQU <__imp__atoldbl>
extern __imp__beep:PANYARGS
_beep TEXTEQU <__imp__beep>
extern __imp__beginthread:PANYARGS
_beginthread TEXTEQU <__imp__beginthread>
extern __imp__beginthreadex:PANYARGS
_beginthreadex TEXTEQU <__imp__beginthreadex>
extern __imp__c_exit:PANYARGS
_c_exit TEXTEQU <__imp__c_exit>
extern __imp__cabs:PANYARGS
_cabs TEXTEQU <__imp__cabs>
extern __imp__callnewh:PANYARGS
_callnewh TEXTEQU <__imp__callnewh>
extern __imp__cexit:PANYARGS
_cexit TEXTEQU <__imp__cexit>
extern __imp__cgets:PANYARGS
_cgets TEXTEQU <__imp__cgets>
extern __imp__cgetws:PANYARGS
_cgetws TEXTEQU <__imp__cgetws>
extern __imp__chdir:PANYARGS
_chdir TEXTEQU <__imp__chdir>
extern __imp__chdrive:PANYARGS
_chdrive TEXTEQU <__imp__chdrive>
extern __imp__chgsign:PANYARGS
_chgsign TEXTEQU <__imp__chgsign>
extern __imp__chgsignf:PANYARGS
_chgsignf TEXTEQU <__imp__chgsignf>
extern __imp__chmod:PANYARGS
_chmod TEXTEQU <__imp__chmod>
extern __imp__chsize:PANYARGS
_chsize TEXTEQU <__imp__chsize>
extern __imp__clearfp:PANYARGS
_clearfp TEXTEQU <__imp__clearfp>
extern __imp__close:PANYARGS
_close TEXTEQU <__imp__close>
extern __imp__commit:PANYARGS
_commit TEXTEQU <__imp__commit>
extern __imp__commode:PANYARGS
_commode TEXTEQU <__imp__commode>
extern __imp__control87:PANYARGS
_control87 TEXTEQU <__imp__control87>
extern __imp__controlfp:PANYARGS
_controlfp TEXTEQU <__imp__controlfp>
extern __imp__copysign:PANYARGS
_copysign TEXTEQU <__imp__copysign>
extern __imp__copysignf:PANYARGS
_copysignf TEXTEQU <__imp__copysignf>
extern __imp__cprintf:PANYARGS
_cprintf TEXTEQU <__imp__cprintf>
extern __imp__cputs:PANYARGS
_cputs TEXTEQU <__imp__cputs>
extern __imp__cputws:PANYARGS
_cputws TEXTEQU <__imp__cputws>
extern __imp__creat:PANYARGS
_creat TEXTEQU <__imp__creat>
extern __imp__cscanf:PANYARGS
_cscanf TEXTEQU <__imp__cscanf>
extern __imp__ctime64:PANYARGS
_ctime64 TEXTEQU <__imp__ctime64>
extern __imp__ctype:PANYARGS
_ctype TEXTEQU <__imp__ctype>
extern __imp__cwait:PANYARGS
_cwait TEXTEQU <__imp__cwait>
extern __imp__cwprintf:PANYARGS
_cwprintf TEXTEQU <__imp__cwprintf>
extern __imp__cwscanf:PANYARGS
_cwscanf TEXTEQU <__imp__cwscanf>
extern __imp__daylight:PANYARGS
_daylight TEXTEQU <__imp__daylight>
extern __imp__dstbias:PANYARGS
_dstbias TEXTEQU <__imp__dstbias>
extern __imp__dup:PANYARGS
_dup TEXTEQU <__imp__dup>
extern __imp__dup2:PANYARGS
_dup2 TEXTEQU <__imp__dup2>
extern __imp__ecvt:PANYARGS
_ecvt TEXTEQU <__imp__ecvt>
extern __imp__endthread:PANYARGS
_endthread TEXTEQU <__imp__endthread>
extern __imp__endthreadex:PANYARGS
_endthreadex TEXTEQU <__imp__endthreadex>
extern __imp__environ:PANYARGS
_environ TEXTEQU <__imp__environ>
extern __imp__eof:PANYARGS
_eof TEXTEQU <__imp__eof>
extern __imp__errno:PANYARGS
_errno TEXTEQU <__imp__errno>
extern __imp__execl:PANYARGS
_execl TEXTEQU <__imp__execl>
extern __imp__execle:PANYARGS
_execle TEXTEQU <__imp__execle>
extern __imp__execlp:PANYARGS
_execlp TEXTEQU <__imp__execlp>
extern __imp__execlpe:PANYARGS
_execlpe TEXTEQU <__imp__execlpe>
extern __imp__execv:PANYARGS
_execv TEXTEQU <__imp__execv>
extern __imp__execve:PANYARGS
_execve TEXTEQU <__imp__execve>
extern __imp__execvp:PANYARGS
_execvp TEXTEQU <__imp__execvp>
extern __imp__execvpe:PANYARGS
_execvpe TEXTEQU <__imp__execvpe>
extern __imp__exit:PANYARGS
_exit TEXTEQU <__imp__exit>
extern __imp__expand:PANYARGS
_expand TEXTEQU <__imp__expand>
extern __imp__fcloseall:PANYARGS
_fcloseall TEXTEQU <__imp__fcloseall>
extern __imp__fcvt:PANYARGS
_fcvt TEXTEQU <__imp__fcvt>
extern __imp__fdopen:PANYARGS
_fdopen TEXTEQU <__imp__fdopen>
extern __imp__fgetchar:PANYARGS
_fgetchar TEXTEQU <__imp__fgetchar>
extern __imp__fgetwchar:PANYARGS
_fgetwchar TEXTEQU <__imp__fgetwchar>
extern __imp__filbuf:PANYARGS
_filbuf TEXTEQU <__imp__filbuf>
extern __imp__fileinfo:PANYARGS
_fileinfo TEXTEQU <__imp__fileinfo>
extern __imp__filelength:PANYARGS
_filelength TEXTEQU <__imp__filelength>
extern __imp__filelengthi64:PANYARGS
_filelengthi64 TEXTEQU <__imp__filelengthi64>
extern __imp__fileno:PANYARGS
_fileno TEXTEQU <__imp__fileno>
extern __imp__findclose:PANYARGS
_findclose TEXTEQU <__imp__findclose>
extern __imp__findfirst:PANYARGS
_findfirst TEXTEQU <__imp__findfirst>
extern __imp__findfirst64:PANYARGS
_findfirst64 TEXTEQU <__imp__findfirst64>
extern __imp__findfirsti64:PANYARGS
_findfirsti64 TEXTEQU <__imp__findfirsti64>
extern __imp__findnext:PANYARGS
_findnext TEXTEQU <__imp__findnext>
extern __imp__findnext64:PANYARGS
_findnext64 TEXTEQU <__imp__findnext64>
extern __imp__findnexti64:PANYARGS
_findnexti64 TEXTEQU <__imp__findnexti64>
extern __imp__finite:PANYARGS
_finite TEXTEQU <__imp__finite>
extern __imp__finitef:PANYARGS
_finitef TEXTEQU <__imp__finitef>
extern __imp__flsbuf:PANYARGS
_flsbuf TEXTEQU <__imp__flsbuf>
extern __imp__flushall:PANYARGS
_flushall TEXTEQU <__imp__flushall>
extern __imp__fmode:PANYARGS
_fmode TEXTEQU <__imp__fmode>
extern __imp__fpclass:PANYARGS
_fpclass TEXTEQU <__imp__fpclass>
extern __imp__fpclassf:PANYARGS
_fpclassf TEXTEQU <__imp__fpclassf>
extern __imp__fpreset:PANYARGS
_fpreset TEXTEQU <__imp__fpreset>
extern __imp__fputchar:PANYARGS
_fputchar TEXTEQU <__imp__fputchar>
extern __imp__fputwchar:PANYARGS
_fputwchar TEXTEQU <__imp__fputwchar>
extern __imp__fsopen:PANYARGS
_fsopen TEXTEQU <__imp__fsopen>
extern __imp__fstat:PANYARGS
_fstat TEXTEQU <__imp__fstat>
extern __imp__fstat64:PANYARGS
_fstat64 TEXTEQU <__imp__fstat64>
extern __imp__fstati64:PANYARGS
_fstati64 TEXTEQU <__imp__fstati64>
extern __imp__ftime:PANYARGS
_ftime TEXTEQU <__imp__ftime>
extern __imp__ftime64:PANYARGS
_ftime64 TEXTEQU <__imp__ftime64>
extern __imp__fullpath:PANYARGS
_fullpath TEXTEQU <__imp__fullpath>
extern __imp__futime:PANYARGS
_futime TEXTEQU <__imp__futime>
extern __imp__futime64:PANYARGS
_futime64 TEXTEQU <__imp__futime64>
extern __imp__gcvt:PANYARGS
_gcvt TEXTEQU <__imp__gcvt>
extern __imp__get_heap_handle:PANYARGS
_get_heap_handle TEXTEQU <__imp__get_heap_handle>
extern __imp__get_osfhandle:PANYARGS
_get_osfhandle TEXTEQU <__imp__get_osfhandle>
extern __imp__get_sbh_threshold:PANYARGS
_get_sbh_threshold TEXTEQU <__imp__get_sbh_threshold>
extern __imp__getch:PANYARGS
_getch TEXTEQU <__imp__getch>
extern __imp__getche:PANYARGS
_getche TEXTEQU <__imp__getche>
extern __imp__getcwd:PANYARGS
_getcwd TEXTEQU <__imp__getcwd>
extern __imp__getdcwd:PANYARGS
_getdcwd TEXTEQU <__imp__getdcwd>
extern __imp__getdiskfree:PANYARGS
_getdiskfree TEXTEQU <__imp__getdiskfree>
extern __imp__getdllprocaddr:PANYARGS
_getdllprocaddr TEXTEQU <__imp__getdllprocaddr>
extern __imp__getdrive:PANYARGS
_getdrive TEXTEQU <__imp__getdrive>
extern __imp__getdrives:PANYARGS
_getdrives TEXTEQU <__imp__getdrives>
extern __imp__getmaxstdio:PANYARGS
_getmaxstdio TEXTEQU <__imp__getmaxstdio>
extern __imp__getmbcp:PANYARGS
_getmbcp TEXTEQU <__imp__getmbcp>
extern __imp__getpid:PANYARGS
_getpid TEXTEQU <__imp__getpid>
extern __imp__getsystime:PANYARGS
_getsystime TEXTEQU <__imp__getsystime>
extern __imp__getw:PANYARGS
_getw TEXTEQU <__imp__getw>
extern __imp__getwch:PANYARGS
_getwch TEXTEQU <__imp__getwch>
extern __imp__getwche:PANYARGS
_getwche TEXTEQU <__imp__getwche>
extern __imp__getws:PANYARGS
_getws TEXTEQU <__imp__getws>
extern __imp__gmtime64:PANYARGS
_gmtime64 TEXTEQU <__imp__gmtime64>
extern __imp__heapadd:PANYARGS
_heapadd TEXTEQU <__imp__heapadd>
extern __imp__heapchk:PANYARGS
_heapchk TEXTEQU <__imp__heapchk>
extern __imp__heapmin:PANYARGS
_heapmin TEXTEQU <__imp__heapmin>
extern __imp__heapset:PANYARGS
_heapset TEXTEQU <__imp__heapset>
extern __imp__heapused:PANYARGS
_heapused TEXTEQU <__imp__heapused>
extern __imp__heapwalk:PANYARGS
_heapwalk TEXTEQU <__imp__heapwalk>
extern __imp__hypot:PANYARGS
_hypot TEXTEQU <__imp__hypot>
extern __imp__hypotf:PANYARGS
_hypotf TEXTEQU <__imp__hypotf>
extern __imp__i64toa:PANYARGS
_i64toa TEXTEQU <__imp__i64toa>
extern __imp__i64tow:PANYARGS
_i64tow TEXTEQU <__imp__i64tow>
extern __imp__initterm:PANYARGS
_initterm TEXTEQU <__imp__initterm>
extern __imp__iob:PANYARGS
_iob TEXTEQU <__imp__iob>
extern __imp__isatty:PANYARGS
_isatty TEXTEQU <__imp__isatty>
extern __imp__isctype:PANYARGS
_isctype TEXTEQU <__imp__isctype>
extern __imp__ismbbalnum:PANYARGS
_ismbbalnum TEXTEQU <__imp__ismbbalnum>
extern __imp__ismbbalpha:PANYARGS
_ismbbalpha TEXTEQU <__imp__ismbbalpha>
extern __imp__ismbbgraph:PANYARGS
_ismbbgraph TEXTEQU <__imp__ismbbgraph>
extern __imp__ismbbkalnum:PANYARGS
_ismbbkalnum TEXTEQU <__imp__ismbbkalnum>
extern __imp__ismbbkana:PANYARGS
_ismbbkana TEXTEQU <__imp__ismbbkana>
extern __imp__ismbbkprint:PANYARGS
_ismbbkprint TEXTEQU <__imp__ismbbkprint>
extern __imp__ismbbkpunct:PANYARGS
_ismbbkpunct TEXTEQU <__imp__ismbbkpunct>
extern __imp__ismbblead:PANYARGS
_ismbblead TEXTEQU <__imp__ismbblead>
extern __imp__ismbbprint:PANYARGS
_ismbbprint TEXTEQU <__imp__ismbbprint>
extern __imp__ismbbpunct:PANYARGS
_ismbbpunct TEXTEQU <__imp__ismbbpunct>
extern __imp__ismbbtrail:PANYARGS
_ismbbtrail TEXTEQU <__imp__ismbbtrail>
extern __imp__ismbcalnum:PANYARGS
_ismbcalnum TEXTEQU <__imp__ismbcalnum>
extern __imp__ismbcalpha:PANYARGS
_ismbcalpha TEXTEQU <__imp__ismbcalpha>
extern __imp__ismbcdigit:PANYARGS
_ismbcdigit TEXTEQU <__imp__ismbcdigit>
extern __imp__ismbcgraph:PANYARGS
_ismbcgraph TEXTEQU <__imp__ismbcgraph>
extern __imp__ismbchira:PANYARGS
_ismbchira TEXTEQU <__imp__ismbchira>
extern __imp__ismbckata:PANYARGS
_ismbckata TEXTEQU <__imp__ismbckata>
extern __imp__ismbcl0:PANYARGS
_ismbcl0 TEXTEQU <__imp__ismbcl0>
extern __imp__ismbcl1:PANYARGS
_ismbcl1 TEXTEQU <__imp__ismbcl1>
extern __imp__ismbcl2:PANYARGS
_ismbcl2 TEXTEQU <__imp__ismbcl2>
extern __imp__ismbclegal:PANYARGS
_ismbclegal TEXTEQU <__imp__ismbclegal>
extern __imp__ismbclower:PANYARGS
_ismbclower TEXTEQU <__imp__ismbclower>
extern __imp__ismbcprint:PANYARGS
_ismbcprint TEXTEQU <__imp__ismbcprint>
extern __imp__ismbcpunct:PANYARGS
_ismbcpunct TEXTEQU <__imp__ismbcpunct>
extern __imp__ismbcspace:PANYARGS
_ismbcspace TEXTEQU <__imp__ismbcspace>
extern __imp__ismbcsymbol:PANYARGS
_ismbcsymbol TEXTEQU <__imp__ismbcsymbol>
extern __imp__ismbcupper:PANYARGS
_ismbcupper TEXTEQU <__imp__ismbcupper>
extern __imp__ismbslead:PANYARGS
_ismbslead TEXTEQU <__imp__ismbslead>
extern __imp__ismbstrail:PANYARGS
_ismbstrail TEXTEQU <__imp__ismbstrail>
extern __imp__isnan:PANYARGS
_isnan TEXTEQU <__imp__isnan>
extern __imp__isnanf:PANYARGS
_isnanf TEXTEQU <__imp__isnanf>
extern __imp__itoa:PANYARGS
_itoa TEXTEQU <__imp__itoa>
extern __imp__itow:PANYARGS
_itow TEXTEQU <__imp__itow>
extern __imp__j0:PANYARGS
_j0 TEXTEQU <__imp__j0>
extern __imp__j1:PANYARGS
_j1 TEXTEQU <__imp__j1>
extern __imp__jn:PANYARGS
_jn TEXTEQU <__imp__jn>
extern __imp__kbhit:PANYARGS
_kbhit TEXTEQU <__imp__kbhit>
extern __imp__lfind:PANYARGS
_lfind TEXTEQU <__imp__lfind>
extern __imp__loaddll:PANYARGS
_loaddll TEXTEQU <__imp__loaddll>
extern __imp__local_unwind:PANYARGS
_local_unwind TEXTEQU <__imp__local_unwind>
extern __imp__localtime64:PANYARGS
_localtime64 TEXTEQU <__imp__localtime64>
extern __imp__lock:PANYARGS
_lock TEXTEQU <__imp__lock>
extern __imp__locking:PANYARGS
_locking TEXTEQU <__imp__locking>
extern __imp__logb:PANYARGS
_logb TEXTEQU <__imp__logb>
extern __imp__logbf:PANYARGS
_logbf TEXTEQU <__imp__logbf>
extern __imp__lrotl:PANYARGS
_lrotl TEXTEQU <__imp__lrotl>
extern __imp__lrotr:PANYARGS
_lrotr TEXTEQU <__imp__lrotr>
extern __imp__lsearch:PANYARGS
_lsearch TEXTEQU <__imp__lsearch>
extern __imp__lseek:PANYARGS
_lseek TEXTEQU <__imp__lseek>
extern __imp__lseeki64:PANYARGS
_lseeki64 TEXTEQU <__imp__lseeki64>
extern __imp__ltoa:PANYARGS
_ltoa TEXTEQU <__imp__ltoa>
extern __imp__ltow:PANYARGS
_ltow TEXTEQU <__imp__ltow>
extern __imp__makepath:PANYARGS
_makepath TEXTEQU <__imp__makepath>
extern __imp__mbbtombc:PANYARGS
_mbbtombc TEXTEQU <__imp__mbbtombc>
extern __imp__mbbtype:PANYARGS
_mbbtype TEXTEQU <__imp__mbbtype>
extern __imp__mbcasemap:PANYARGS
_mbcasemap TEXTEQU <__imp__mbcasemap>
extern __imp__mbccpy:PANYARGS
_mbccpy TEXTEQU <__imp__mbccpy>
extern __imp__mbcjistojms:PANYARGS
_mbcjistojms TEXTEQU <__imp__mbcjistojms>
extern __imp__mbcjmstojis:PANYARGS
_mbcjmstojis TEXTEQU <__imp__mbcjmstojis>
extern __imp__mbclen:PANYARGS
_mbclen TEXTEQU <__imp__mbclen>
extern __imp__mbctohira:PANYARGS
_mbctohira TEXTEQU <__imp__mbctohira>
extern __imp__mbctokata:PANYARGS
_mbctokata TEXTEQU <__imp__mbctokata>
extern __imp__mbctolower:PANYARGS
_mbctolower TEXTEQU <__imp__mbctolower>
extern __imp__mbctombb:PANYARGS
_mbctombb TEXTEQU <__imp__mbctombb>
extern __imp__mbctoupper:PANYARGS
_mbctoupper TEXTEQU <__imp__mbctoupper>
extern __imp__mbctype:PANYARGS
_mbctype TEXTEQU <__imp__mbctype>
extern __imp__mbsbtype:PANYARGS
_mbsbtype TEXTEQU <__imp__mbsbtype>
extern __imp__mbscat:PANYARGS
_mbscat TEXTEQU <__imp__mbscat>
extern __imp__mbschr:PANYARGS
_mbschr TEXTEQU <__imp__mbschr>
extern __imp__mbscmp:PANYARGS
_mbscmp TEXTEQU <__imp__mbscmp>
extern __imp__mbscoll:PANYARGS
_mbscoll TEXTEQU <__imp__mbscoll>
extern __imp__mbscpy:PANYARGS
_mbscpy TEXTEQU <__imp__mbscpy>
extern __imp__mbscspn:PANYARGS
_mbscspn TEXTEQU <__imp__mbscspn>
extern __imp__mbsdec:PANYARGS
_mbsdec TEXTEQU <__imp__mbsdec>
extern __imp__mbsdup:PANYARGS
_mbsdup TEXTEQU <__imp__mbsdup>
extern __imp__mbsicmp:PANYARGS
_mbsicmp TEXTEQU <__imp__mbsicmp>
extern __imp__mbsicoll:PANYARGS
_mbsicoll TEXTEQU <__imp__mbsicoll>
extern __imp__mbsinc:PANYARGS
_mbsinc TEXTEQU <__imp__mbsinc>
extern __imp__mbslen:PANYARGS
_mbslen TEXTEQU <__imp__mbslen>
extern __imp__mbslwr:PANYARGS
_mbslwr TEXTEQU <__imp__mbslwr>
extern __imp__mbsnbcat:PANYARGS
_mbsnbcat TEXTEQU <__imp__mbsnbcat>
extern __imp__mbsnbcmp:PANYARGS
_mbsnbcmp TEXTEQU <__imp__mbsnbcmp>
extern __imp__mbsnbcnt:PANYARGS
_mbsnbcnt TEXTEQU <__imp__mbsnbcnt>
extern __imp__mbsnbcoll:PANYARGS
_mbsnbcoll TEXTEQU <__imp__mbsnbcoll>
extern __imp__mbsnbcpy:PANYARGS
_mbsnbcpy TEXTEQU <__imp__mbsnbcpy>
extern __imp__mbsnbicmp:PANYARGS
_mbsnbicmp TEXTEQU <__imp__mbsnbicmp>
extern __imp__mbsnbicoll:PANYARGS
_mbsnbicoll TEXTEQU <__imp__mbsnbicoll>
extern __imp__mbsnbset:PANYARGS
_mbsnbset TEXTEQU <__imp__mbsnbset>
extern __imp__mbsncat:PANYARGS
_mbsncat TEXTEQU <__imp__mbsncat>
extern __imp__mbsnccnt:PANYARGS
_mbsnccnt TEXTEQU <__imp__mbsnccnt>
extern __imp__mbsncmp:PANYARGS
_mbsncmp TEXTEQU <__imp__mbsncmp>
extern __imp__mbsncoll:PANYARGS
_mbsncoll TEXTEQU <__imp__mbsncoll>
extern __imp__mbsncpy:PANYARGS
_mbsncpy TEXTEQU <__imp__mbsncpy>
extern __imp__mbsnextc:PANYARGS
_mbsnextc TEXTEQU <__imp__mbsnextc>
extern __imp__mbsnicmp:PANYARGS
_mbsnicmp TEXTEQU <__imp__mbsnicmp>
extern __imp__mbsnicoll:PANYARGS
_mbsnicoll TEXTEQU <__imp__mbsnicoll>
extern __imp__mbsninc:PANYARGS
_mbsninc TEXTEQU <__imp__mbsninc>
extern __imp__mbsnset:PANYARGS
_mbsnset TEXTEQU <__imp__mbsnset>
extern __imp__mbspbrk:PANYARGS
_mbspbrk TEXTEQU <__imp__mbspbrk>
extern __imp__mbsrchr:PANYARGS
_mbsrchr TEXTEQU <__imp__mbsrchr>
extern __imp__mbsrev:PANYARGS
_mbsrev TEXTEQU <__imp__mbsrev>
extern __imp__mbsset:PANYARGS
_mbsset TEXTEQU <__imp__mbsset>
extern __imp__mbsspn:PANYARGS
_mbsspn TEXTEQU <__imp__mbsspn>
extern __imp__mbsspnp:PANYARGS
_mbsspnp TEXTEQU <__imp__mbsspnp>
extern __imp__mbsstr:PANYARGS
_mbsstr TEXTEQU <__imp__mbsstr>
extern __imp__mbstok:PANYARGS
_mbstok TEXTEQU <__imp__mbstok>
extern __imp__mbstrlen:PANYARGS
_mbstrlen TEXTEQU <__imp__mbstrlen>
extern __imp__mbsupr:PANYARGS
_mbsupr TEXTEQU <__imp__mbsupr>
extern __imp__memccpy:PANYARGS
_memccpy TEXTEQU <__imp__memccpy>
extern __imp__memicmp:PANYARGS
_memicmp TEXTEQU <__imp__memicmp>
extern __imp__mkdir:PANYARGS
_mkdir TEXTEQU <__imp__mkdir>
extern __imp__mkgmtime:PANYARGS
_mkgmtime TEXTEQU <__imp__mkgmtime>
extern __imp__mkgmtime64:PANYARGS
_mkgmtime64 TEXTEQU <__imp__mkgmtime64>
extern __imp__mktemp:PANYARGS
_mktemp TEXTEQU <__imp__mktemp>
extern __imp__mktime64:PANYARGS
_mktime64 TEXTEQU <__imp__mktime64>
extern __imp__msize:PANYARGS
_msize TEXTEQU <__imp__msize>
extern __imp__nextafter:PANYARGS
_nextafter TEXTEQU <__imp__nextafter>
extern __imp__nextafterf:PANYARGS
_nextafterf TEXTEQU <__imp__nextafterf>
extern __imp__onexit:PANYARGS
_onexit TEXTEQU <__imp__onexit>
extern __imp__open:PANYARGS
_open TEXTEQU <__imp__open>
extern __imp__open_osfhandle:PANYARGS
_open_osfhandle TEXTEQU <__imp__open_osfhandle>
extern __imp__osplatform:PANYARGS
_osplatform TEXTEQU <__imp__osplatform>
extern __imp__osver:PANYARGS
_osver TEXTEQU <__imp__osver>
extern __imp__pclose:PANYARGS
_pclose TEXTEQU <__imp__pclose>
extern __imp__pctype:PANYARGS
_pctype TEXTEQU <__imp__pctype>
extern __imp__pgmptr:PANYARGS
_pgmptr TEXTEQU <__imp__pgmptr>
extern __imp__pipe:PANYARGS
_pipe TEXTEQU <__imp__pipe>
extern __imp__popen:PANYARGS
_popen TEXTEQU <__imp__popen>
extern __imp__purecall:PANYARGS
_purecall TEXTEQU <__imp__purecall>
extern __imp__putch:PANYARGS
_putch TEXTEQU <__imp__putch>
extern __imp__putenv:PANYARGS
_putenv TEXTEQU <__imp__putenv>
extern __imp__putw:PANYARGS
_putw TEXTEQU <__imp__putw>
extern __imp__putwch:PANYARGS
_putwch TEXTEQU <__imp__putwch>
extern __imp__putws:PANYARGS
_putws TEXTEQU <__imp__putws>
extern __imp__pwctype:PANYARGS
_pwctype TEXTEQU <__imp__pwctype>
extern __imp__read:PANYARGS
_read TEXTEQU <__imp__read>
extern __imp__resetstkoflw:PANYARGS
_resetstkoflw TEXTEQU <__imp__resetstkoflw>
extern __imp__rmdir:PANYARGS
_rmdir TEXTEQU <__imp__rmdir>
extern __imp__rmtmp:PANYARGS
_rmtmp TEXTEQU <__imp__rmtmp>
extern __imp__rotl:PANYARGS
_rotl TEXTEQU <__imp__rotl>
extern __imp__rotl64:PANYARGS
_rotl64 TEXTEQU <__imp__rotl64>
extern __imp__rotr:PANYARGS
_rotr TEXTEQU <__imp__rotr>
extern __imp__rotr64:PANYARGS
_rotr64 TEXTEQU <__imp__rotr64>
extern __imp__scalb:PANYARGS
_scalb TEXTEQU <__imp__scalb>
extern __imp__scalbf:PANYARGS
_scalbf TEXTEQU <__imp__scalbf>
extern __imp__scprintf:PANYARGS
_scprintf TEXTEQU <__imp__scprintf>
extern __imp__scwprintf:PANYARGS
_scwprintf TEXTEQU <__imp__scwprintf>
extern __imp__searchenv:PANYARGS
_searchenv TEXTEQU <__imp__searchenv>
extern __imp__set_error_mode:PANYARGS
_set_error_mode TEXTEQU <__imp__set_error_mode>
extern __imp__set_sbh_threshold:PANYARGS
_set_sbh_threshold TEXTEQU <__imp__set_sbh_threshold>
extern __imp__seterrormode:PANYARGS
_seterrormode TEXTEQU <__imp__seterrormode>
extern __imp__setjmp:PANYARGS
_setjmp TEXTEQU <__imp__setjmp>
extern __imp__setjmpex:PANYARGS
_setjmpex TEXTEQU <__imp__setjmpex>
extern __imp__setmaxstdio:PANYARGS
_setmaxstdio TEXTEQU <__imp__setmaxstdio>
extern __imp__setmbcp:PANYARGS
_setmbcp TEXTEQU <__imp__setmbcp>
extern __imp__setmode:PANYARGS
_setmode TEXTEQU <__imp__setmode>
extern __imp__setsystime:PANYARGS
_setsystime TEXTEQU <__imp__setsystime>
extern __imp__sleep:PANYARGS
_sleep TEXTEQU <__imp__sleep>
extern __imp__snprintf:PANYARGS
_snprintf TEXTEQU <__imp__snprintf>
extern __imp__snscanf:PANYARGS
_snscanf TEXTEQU <__imp__snscanf>
extern __imp__snwprintf:PANYARGS
_snwprintf TEXTEQU <__imp__snwprintf>
extern __imp__snwscanf:PANYARGS
_snwscanf TEXTEQU <__imp__snwscanf>
extern __imp__sopen:PANYARGS
_sopen TEXTEQU <__imp__sopen>
extern __imp__spawnl:PANYARGS
_spawnl TEXTEQU <__imp__spawnl>
extern __imp__spawnle:PANYARGS
_spawnle TEXTEQU <__imp__spawnle>
extern __imp__spawnlp:PANYARGS
_spawnlp TEXTEQU <__imp__spawnlp>
extern __imp__spawnlpe:PANYARGS
_spawnlpe TEXTEQU <__imp__spawnlpe>
extern __imp__spawnv:PANYARGS
_spawnv TEXTEQU <__imp__spawnv>
extern __imp__spawnve:PANYARGS
_spawnve TEXTEQU <__imp__spawnve>
extern __imp__spawnvp:PANYARGS
_spawnvp TEXTEQU <__imp__spawnvp>
extern __imp__spawnvpe:PANYARGS
_spawnvpe TEXTEQU <__imp__spawnvpe>
extern __imp__splitpath:PANYARGS
_splitpath TEXTEQU <__imp__splitpath>
extern __imp__stat:PANYARGS
_stat TEXTEQU <__imp__stat>
extern __imp__stat64:PANYARGS
_stat64 TEXTEQU <__imp__stat64>
extern __imp__stati64:PANYARGS
_stati64 TEXTEQU <__imp__stati64>
extern __imp__statusfp:PANYARGS
_statusfp TEXTEQU <__imp__statusfp>
extern __imp__strcmpi:PANYARGS
_strcmpi TEXTEQU <__imp__strcmpi>
extern __imp__strdate:PANYARGS
_strdate TEXTEQU <__imp__strdate>
extern __imp__strdup:PANYARGS
_strdup TEXTEQU <__imp__strdup>
extern __imp__strerror:PANYARGS
_strerror TEXTEQU <__imp__strerror>
extern __imp__stricmp:PANYARGS
_stricmp TEXTEQU <__imp__stricmp>
extern __imp__stricoll:PANYARGS
_stricoll TEXTEQU <__imp__stricoll>
extern __imp__strlwr:PANYARGS
_strlwr TEXTEQU <__imp__strlwr>
extern __imp__strncoll:PANYARGS
_strncoll TEXTEQU <__imp__strncoll>
extern __imp__strnicmp:PANYARGS
_strnicmp TEXTEQU <__imp__strnicmp>
extern __imp__strnicoll:PANYARGS
_strnicoll TEXTEQU <__imp__strnicoll>
extern __imp__strnset:PANYARGS
_strnset TEXTEQU <__imp__strnset>
extern __imp__strrev:PANYARGS
_strrev TEXTEQU <__imp__strrev>
extern __imp__strset:PANYARGS
_strset TEXTEQU <__imp__strset>
extern __imp__strtime:PANYARGS
_strtime TEXTEQU <__imp__strtime>
extern __imp__strtoi64:PANYARGS
_strtoi64 TEXTEQU <__imp__strtoi64>
extern __imp__strtoui64:PANYARGS
_strtoui64 TEXTEQU <__imp__strtoui64>
extern __imp__strupr:PANYARGS
_strupr TEXTEQU <__imp__strupr>
extern __imp__swab:PANYARGS
_swab TEXTEQU <__imp__swab>
extern __imp__sys_errlist:PANYARGS
_sys_errlist TEXTEQU <__imp__sys_errlist>
extern __imp__sys_nerr:PANYARGS
_sys_nerr TEXTEQU <__imp__sys_nerr>
extern __imp__tell:PANYARGS
_tell TEXTEQU <__imp__tell>
extern __imp__telli64:PANYARGS
_telli64 TEXTEQU <__imp__telli64>
extern __imp__tempnam:PANYARGS
_tempnam TEXTEQU <__imp__tempnam>
extern __imp__time64:PANYARGS
_time64 TEXTEQU <__imp__time64>
extern __imp__timezone:PANYARGS
_timezone TEXTEQU <__imp__timezone>
extern __imp__tolower:PANYARGS
_tolower TEXTEQU <__imp__tolower>
extern __imp__toupper:PANYARGS
_toupper TEXTEQU <__imp__toupper>
extern __imp__tzname:PANYARGS
_tzname TEXTEQU <__imp__tzname>
extern __imp__tzset:PANYARGS
_tzset TEXTEQU <__imp__tzset>
extern __imp__ui64toa:PANYARGS
_ui64toa TEXTEQU <__imp__ui64toa>
extern __imp__ui64tow:PANYARGS
_ui64tow TEXTEQU <__imp__ui64tow>
extern __imp__ultoa:PANYARGS
_ultoa TEXTEQU <__imp__ultoa>
extern __imp__ultow:PANYARGS
_ultow TEXTEQU <__imp__ultow>
extern __imp__umask:PANYARGS
_umask TEXTEQU <__imp__umask>
extern __imp__ungetch:PANYARGS
_ungetch TEXTEQU <__imp__ungetch>
extern __imp__ungetwch:PANYARGS
_ungetwch TEXTEQU <__imp__ungetwch>
extern __imp__unlink:PANYARGS
_unlink TEXTEQU <__imp__unlink>
extern __imp__unloaddll:PANYARGS
_unloaddll TEXTEQU <__imp__unloaddll>
extern __imp__unlock:PANYARGS
_unlock TEXTEQU <__imp__unlock>
extern __imp__utime:PANYARGS
_utime TEXTEQU <__imp__utime>
extern __imp__utime64:PANYARGS
_utime64 TEXTEQU <__imp__utime64>
extern __imp__vscprintf:PANYARGS
_vscprintf TEXTEQU <__imp__vscprintf>
extern __imp__vscwprintf:PANYARGS
_vscwprintf TEXTEQU <__imp__vscwprintf>
extern __imp__vsnprintf:PANYARGS
_vsnprintf TEXTEQU <__imp__vsnprintf>
extern __imp__vsnwprintf:PANYARGS
_vsnwprintf TEXTEQU <__imp__vsnwprintf>
extern __imp__waccess:PANYARGS
_waccess TEXTEQU <__imp__waccess>
extern __imp__wasctime:PANYARGS
_wasctime TEXTEQU <__imp__wasctime>
extern __imp__wchdir:PANYARGS
_wchdir TEXTEQU <__imp__wchdir>
extern __imp__wchmod:PANYARGS
_wchmod TEXTEQU <__imp__wchmod>
extern __imp__wcmdln:PANYARGS
_wcmdln TEXTEQU <__imp__wcmdln>
extern __imp__wcreat:PANYARGS
_wcreat TEXTEQU <__imp__wcreat>
extern __imp__wcsdup:PANYARGS
_wcsdup TEXTEQU <__imp__wcsdup>
extern __imp__wcserror:PANYARGS
_wcserror TEXTEQU <__imp__wcserror>
extern __imp__wcsicmp:PANYARGS
_wcsicmp TEXTEQU <__imp__wcsicmp>
extern __imp__wcsicoll:PANYARGS
_wcsicoll TEXTEQU <__imp__wcsicoll>
extern __imp__wcslwr:PANYARGS
_wcslwr TEXTEQU <__imp__wcslwr>
extern __imp__wcsncoll:PANYARGS
_wcsncoll TEXTEQU <__imp__wcsncoll>
extern __imp__wcsnicmp:PANYARGS
_wcsnicmp TEXTEQU <__imp__wcsnicmp>
extern __imp__wcsnicoll:PANYARGS
_wcsnicoll TEXTEQU <__imp__wcsnicoll>
extern __imp__wcsnset:PANYARGS
_wcsnset TEXTEQU <__imp__wcsnset>
extern __imp__wcsrev:PANYARGS
_wcsrev TEXTEQU <__imp__wcsrev>
extern __imp__wcsset:PANYARGS
_wcsset TEXTEQU <__imp__wcsset>
extern __imp__wcstoi64:PANYARGS
_wcstoi64 TEXTEQU <__imp__wcstoi64>
extern __imp__wcstoui64:PANYARGS
_wcstoui64 TEXTEQU <__imp__wcstoui64>
extern __imp__wcsupr:PANYARGS
_wcsupr TEXTEQU <__imp__wcsupr>
extern __imp__wctime:PANYARGS
_wctime TEXTEQU <__imp__wctime>
extern __imp__wctime64:PANYARGS
_wctime64 TEXTEQU <__imp__wctime64>
extern __imp__wctype:PANYARGS
_wctype TEXTEQU <__imp__wctype>
extern __imp__wenviron:PANYARGS
_wenviron TEXTEQU <__imp__wenviron>
extern __imp__wexecl:PANYARGS
_wexecl TEXTEQU <__imp__wexecl>
extern __imp__wexecle:PANYARGS
_wexecle TEXTEQU <__imp__wexecle>
extern __imp__wexeclp:PANYARGS
_wexeclp TEXTEQU <__imp__wexeclp>
extern __imp__wexeclpe:PANYARGS
_wexeclpe TEXTEQU <__imp__wexeclpe>
extern __imp__wexecv:PANYARGS
_wexecv TEXTEQU <__imp__wexecv>
extern __imp__wexecve:PANYARGS
_wexecve TEXTEQU <__imp__wexecve>
extern __imp__wexecvp:PANYARGS
_wexecvp TEXTEQU <__imp__wexecvp>
extern __imp__wexecvpe:PANYARGS
_wexecvpe TEXTEQU <__imp__wexecvpe>
extern __imp__wfdopen:PANYARGS
_wfdopen TEXTEQU <__imp__wfdopen>
extern __imp__wfindfirst:PANYARGS
_wfindfirst TEXTEQU <__imp__wfindfirst>
extern __imp__wfindfirst64:PANYARGS
_wfindfirst64 TEXTEQU <__imp__wfindfirst64>
extern __imp__wfindfirsti64:PANYARGS
_wfindfirsti64 TEXTEQU <__imp__wfindfirsti64>
extern __imp__wfindnext:PANYARGS
_wfindnext TEXTEQU <__imp__wfindnext>
extern __imp__wfindnext64:PANYARGS
_wfindnext64 TEXTEQU <__imp__wfindnext64>
extern __imp__wfindnexti64:PANYARGS
_wfindnexti64 TEXTEQU <__imp__wfindnexti64>
extern __imp__wfopen:PANYARGS
_wfopen TEXTEQU <__imp__wfopen>
extern __imp__wfreopen:PANYARGS
_wfreopen TEXTEQU <__imp__wfreopen>
extern __imp__wfsopen:PANYARGS
_wfsopen TEXTEQU <__imp__wfsopen>
extern __imp__wfullpath:PANYARGS
_wfullpath TEXTEQU <__imp__wfullpath>
extern __imp__wgetcwd:PANYARGS
_wgetcwd TEXTEQU <__imp__wgetcwd>
extern __imp__wgetdcwd:PANYARGS
_wgetdcwd TEXTEQU <__imp__wgetdcwd>
extern __imp__wgetenv:PANYARGS
_wgetenv TEXTEQU <__imp__wgetenv>
extern __imp__winmajor:PANYARGS
_winmajor TEXTEQU <__imp__winmajor>
extern __imp__winminor:PANYARGS
_winminor TEXTEQU <__imp__winminor>
extern __imp__winver:PANYARGS
_winver TEXTEQU <__imp__winver>
extern __imp__wmakepath:PANYARGS
_wmakepath TEXTEQU <__imp__wmakepath>
extern __imp__wmkdir:PANYARGS
_wmkdir TEXTEQU <__imp__wmkdir>
extern __imp__wmktemp:PANYARGS
_wmktemp TEXTEQU <__imp__wmktemp>
extern __imp__wopen:PANYARGS
_wopen TEXTEQU <__imp__wopen>
extern __imp__wperror:PANYARGS
_wperror TEXTEQU <__imp__wperror>
extern __imp__wpgmptr:PANYARGS
_wpgmptr TEXTEQU <__imp__wpgmptr>
extern __imp__wpopen:PANYARGS
_wpopen TEXTEQU <__imp__wpopen>
extern __imp__wputenv:PANYARGS
_wputenv TEXTEQU <__imp__wputenv>
extern __imp__wremove:PANYARGS
_wremove TEXTEQU <__imp__wremove>
extern __imp__wrename:PANYARGS
_wrename TEXTEQU <__imp__wrename>
extern __imp__write:PANYARGS
_write TEXTEQU <__imp__write>
extern __imp__wrmdir:PANYARGS
_wrmdir TEXTEQU <__imp__wrmdir>
extern __imp__wsearchenv:PANYARGS
_wsearchenv TEXTEQU <__imp__wsearchenv>
extern __imp__wsetlocale:PANYARGS
_wsetlocale TEXTEQU <__imp__wsetlocale>
extern __imp__wsopen:PANYARGS
_wsopen TEXTEQU <__imp__wsopen>
extern __imp__wspawnl:PANYARGS
_wspawnl TEXTEQU <__imp__wspawnl>
extern __imp__wspawnle:PANYARGS
_wspawnle TEXTEQU <__imp__wspawnle>
extern __imp__wspawnlp:PANYARGS
_wspawnlp TEXTEQU <__imp__wspawnlp>
extern __imp__wspawnlpe:PANYARGS
_wspawnlpe TEXTEQU <__imp__wspawnlpe>
extern __imp__wspawnv:PANYARGS
_wspawnv TEXTEQU <__imp__wspawnv>
extern __imp__wspawnve:PANYARGS
_wspawnve TEXTEQU <__imp__wspawnve>
extern __imp__wspawnvp:PANYARGS
_wspawnvp TEXTEQU <__imp__wspawnvp>
extern __imp__wspawnvpe:PANYARGS
_wspawnvpe TEXTEQU <__imp__wspawnvpe>
extern __imp__wsplitpath:PANYARGS
_wsplitpath TEXTEQU <__imp__wsplitpath>
extern __imp__wstat:PANYARGS
_wstat TEXTEQU <__imp__wstat>
extern __imp__wstat64:PANYARGS
_wstat64 TEXTEQU <__imp__wstat64>
extern __imp__wstati64:PANYARGS
_wstati64 TEXTEQU <__imp__wstati64>
extern __imp__wstrdate:PANYARGS
_wstrdate TEXTEQU <__imp__wstrdate>
extern __imp__wstrtime:PANYARGS
_wstrtime TEXTEQU <__imp__wstrtime>
extern __imp__wsystem:PANYARGS
_wsystem TEXTEQU <__imp__wsystem>
extern __imp__wtempnam:PANYARGS
_wtempnam TEXTEQU <__imp__wtempnam>
extern __imp__wtmpnam:PANYARGS
_wtmpnam TEXTEQU <__imp__wtmpnam>
extern __imp__wtof:PANYARGS
_wtof TEXTEQU <__imp__wtof>
extern __imp__wtoi:PANYARGS
_wtoi TEXTEQU <__imp__wtoi>
extern __imp__wtoi64:PANYARGS
_wtoi64 TEXTEQU <__imp__wtoi64>
extern __imp__wtol:PANYARGS
_wtol TEXTEQU <__imp__wtol>
extern __imp__wunlink:PANYARGS
_wunlink TEXTEQU <__imp__wunlink>
extern __imp__wutime:PANYARGS
_wutime TEXTEQU <__imp__wutime>
extern __imp__wutime64:PANYARGS
_wutime64 TEXTEQU <__imp__wutime64>
extern __imp__y0:PANYARGS
_y0 TEXTEQU <__imp__y0>
extern __imp__y1:PANYARGS
_y1 TEXTEQU <__imp__y1>
extern __imp__yn:PANYARGS
_yn TEXTEQU <__imp__yn>
extern __imp_abort:PANYARGS
abort TEXTEQU <__imp_abort>
extern __imp_abs:PANYARGS
abs TEXTEQU <__imp_abs>
extern __imp_acos:PANYARGS
acos TEXTEQU <__imp_acos>
extern __imp_acosf:PANYARGS
acosf TEXTEQU <__imp_acosf>
extern __imp_asctime:PANYARGS
asctime TEXTEQU <__imp_asctime>
extern __imp_asin:PANYARGS
asin TEXTEQU <__imp_asin>
extern __imp_asinf:PANYARGS
asinf TEXTEQU <__imp_asinf>
extern __imp_atan:PANYARGS
atan TEXTEQU <__imp_atan>
extern __imp_atan2:PANYARGS
atan2 TEXTEQU <__imp_atan2>
extern __imp_atan2f:PANYARGS
atan2f TEXTEQU <__imp_atan2f>
extern __imp_atanf:PANYARGS
atanf TEXTEQU <__imp_atanf>
extern __imp_atexit:PANYARGS
atexit TEXTEQU <__imp_atexit>
extern __imp_atof:PANYARGS
atof TEXTEQU <__imp_atof>
extern __imp_atoi:PANYARGS
atoi TEXTEQU <__imp_atoi>
extern __imp_atol:PANYARGS
atol TEXTEQU <__imp_atol>
extern __imp_bsearch:PANYARGS
bsearch TEXTEQU <__imp_bsearch>
extern __imp_calloc:PANYARGS
calloc TEXTEQU <__imp_calloc>
extern __imp_ceil:PANYARGS
ceil TEXTEQU <__imp_ceil>
extern __imp_ceilf:PANYARGS
ceilf TEXTEQU <__imp_ceilf>
extern __imp_clearerr:PANYARGS
clearerr TEXTEQU <__imp_clearerr>
extern __imp_clock:PANYARGS
clock TEXTEQU <__imp_clock>
extern __imp_cos:PANYARGS
cos TEXTEQU <__imp_cos>
extern __imp_cosf:PANYARGS
cosf TEXTEQU <__imp_cosf>
extern __imp_cosh:PANYARGS
cosh TEXTEQU <__imp_cosh>
extern __imp_coshf:PANYARGS
coshf TEXTEQU <__imp_coshf>
extern __imp_ctime:PANYARGS
ctime TEXTEQU <__imp_ctime>
extern __imp_difftime:PANYARGS
difftime TEXTEQU <__imp_difftime>
extern __imp_div:PANYARGS
_div TEXTEQU <__imp_div>
extern __imp_exit:PANYARGS
exit TEXTEQU <__imp_exit>
extern __imp_exp:PANYARGS
exp TEXTEQU <__imp_exp>
extern __imp_expf:PANYARGS
expf TEXTEQU <__imp_expf>
extern __imp_fabs:PANYARGS
_fabs TEXTEQU <__imp_fabs>
extern __imp_fclose:PANYARGS
fclose TEXTEQU <__imp_fclose>
extern __imp_feof:PANYARGS
feof TEXTEQU <__imp_feof>
extern __imp_ferror:PANYARGS
ferror TEXTEQU <__imp_ferror>
extern __imp_fflush:PANYARGS
fflush TEXTEQU <__imp_fflush>
extern __imp_fgetc:PANYARGS
fgetc TEXTEQU <__imp_fgetc>
extern __imp_fgetpos:PANYARGS
fgetpos TEXTEQU <__imp_fgetpos>
extern __imp_fgets:PANYARGS
fgets TEXTEQU <__imp_fgets>
extern __imp_fgetwc:PANYARGS
fgetwc TEXTEQU <__imp_fgetwc>
extern __imp_fgetws:PANYARGS
fgetws TEXTEQU <__imp_fgetws>
extern __imp_floor:PANYARGS
floor TEXTEQU <__imp_floor>
extern __imp_floorf:PANYARGS
floorf TEXTEQU <__imp_floorf>
extern __imp_fmod:PANYARGS
fmod TEXTEQU <__imp_fmod>
extern __imp_fmodf:PANYARGS
fmodf TEXTEQU <__imp_fmodf>
extern __imp_fopen:PANYARGS
fopen TEXTEQU <__imp_fopen>
extern __imp_fprintf:PANYARGS
fprintf TEXTEQU <__imp_fprintf>
extern __imp_fputc:PANYARGS
fputc TEXTEQU <__imp_fputc>
extern __imp_fputs:PANYARGS
fputs TEXTEQU <__imp_fputs>
extern __imp_fputwc:PANYARGS
fputwc TEXTEQU <__imp_fputwc>
extern __imp_fputws:PANYARGS
fputws TEXTEQU <__imp_fputws>
extern __imp_fread:PANYARGS
fread TEXTEQU <__imp_fread>
extern __imp_free:PANYARGS
free TEXTEQU <__imp_free>
extern __imp_freopen:PANYARGS
freopen TEXTEQU <__imp_freopen>
extern __imp_frexp:PANYARGS
frexp TEXTEQU <__imp_frexp>
extern __imp_fscanf:PANYARGS
fscanf TEXTEQU <__imp_fscanf>
extern __imp_fseek:PANYARGS
fseek TEXTEQU <__imp_fseek>
extern __imp_fsetpos:PANYARGS
fsetpos TEXTEQU <__imp_fsetpos>
extern __imp_ftell:PANYARGS
ftell TEXTEQU <__imp_ftell>
extern __imp_fwprintf:PANYARGS
fwprintf TEXTEQU <__imp_fwprintf>
extern __imp_fwrite:PANYARGS
fwrite TEXTEQU <__imp_fwrite>
extern __imp_fwscanf:PANYARGS
fwscanf TEXTEQU <__imp_fwscanf>
extern __imp_getc:PANYARGS
getc TEXTEQU <__imp_getc>
extern __imp_getchar:PANYARGS
getchar TEXTEQU <__imp_getchar>
extern __imp_getenv:PANYARGS
getenv TEXTEQU <__imp_getenv>
extern __imp_gets:PANYARGS
gets TEXTEQU <__imp_gets>
extern __imp_getwc:PANYARGS
getwc TEXTEQU <__imp_getwc>
extern __imp_getwchar:PANYARGS
getwchar TEXTEQU <__imp_getwchar>
extern __imp_gmtime:PANYARGS
gmtime TEXTEQU <__imp_gmtime>
extern __imp_is_wctype:PANYARGS
is_wctype TEXTEQU <__imp_is_wctype>
extern __imp_isalnum:PANYARGS
isalnum TEXTEQU <__imp_isalnum>
extern __imp_isalpha:PANYARGS
isalpha TEXTEQU <__imp_isalpha>
extern __imp_iscntrl:PANYARGS
iscntrl TEXTEQU <__imp_iscntrl>
extern __imp_isdigit:PANYARGS
isdigit TEXTEQU <__imp_isdigit>
extern __imp_isgraph:PANYARGS
isgraph TEXTEQU <__imp_isgraph>
extern __imp_isleadbyte:PANYARGS
isleadbyte TEXTEQU <__imp_isleadbyte>
extern __imp_islower:PANYARGS
islower TEXTEQU <__imp_islower>
extern __imp_isprint:PANYARGS
isprint TEXTEQU <__imp_isprint>
extern __imp_ispunct:PANYARGS
ispunct TEXTEQU <__imp_ispunct>
extern __imp_isspace:PANYARGS
isspace TEXTEQU <__imp_isspace>
extern __imp_isupper:PANYARGS
isupper TEXTEQU <__imp_isupper>
extern __imp_iswalnum:PANYARGS
iswalnum TEXTEQU <__imp_iswalnum>
extern __imp_iswalpha:PANYARGS
iswalpha TEXTEQU <__imp_iswalpha>
extern __imp_iswascii:PANYARGS
iswascii TEXTEQU <__imp_iswascii>
extern __imp_iswcntrl:PANYARGS
iswcntrl TEXTEQU <__imp_iswcntrl>
extern __imp_iswctype:PANYARGS
iswctype TEXTEQU <__imp_iswctype>
extern __imp_iswdigit:PANYARGS
iswdigit TEXTEQU <__imp_iswdigit>
extern __imp_iswgraph:PANYARGS
iswgraph TEXTEQU <__imp_iswgraph>
extern __imp_iswlower:PANYARGS
iswlower TEXTEQU <__imp_iswlower>
extern __imp_iswprint:PANYARGS
iswprint TEXTEQU <__imp_iswprint>
extern __imp_iswpunct:PANYARGS
iswpunct TEXTEQU <__imp_iswpunct>
extern __imp_iswspace:PANYARGS
iswspace TEXTEQU <__imp_iswspace>
extern __imp_iswupper:PANYARGS
iswupper TEXTEQU <__imp_iswupper>
extern __imp_iswxdigit:PANYARGS
iswxdigit TEXTEQU <__imp_iswxdigit>
extern __imp_isxdigit:PANYARGS
isxdigit TEXTEQU <__imp_isxdigit>
extern __imp_labs:PANYARGS
labs TEXTEQU <__imp_labs>
extern __imp_ldexp:PANYARGS
ldexp TEXTEQU <__imp_ldexp>
extern __imp_ldiv:PANYARGS
ldiv TEXTEQU <__imp_ldiv>
extern __imp_localeconv:PANYARGS
localeconv TEXTEQU <__imp_localeconv>
extern __imp_localtime:PANYARGS
localtime TEXTEQU <__imp_localtime>
extern __imp_log:PANYARGS
log TEXTEQU <__imp_log>
extern __imp_log10:PANYARGS
log10 TEXTEQU <__imp_log10>
extern __imp_log10f:PANYARGS
log10f TEXTEQU <__imp_log10f>
extern __imp_logf:PANYARGS
logf TEXTEQU <__imp_logf>
extern __imp_longjmp:PANYARGS
longjmp TEXTEQU <__imp_longjmp>
extern __imp_malloc:PANYARGS
malloc TEXTEQU <__imp_malloc>
extern __imp_mblen:PANYARGS
mblen TEXTEQU <__imp_mblen>
extern __imp_mbstowcs:PANYARGS
mbstowcs TEXTEQU <__imp_mbstowcs>
extern __imp_mbtowc:PANYARGS
mbtowc TEXTEQU <__imp_mbtowc>
extern __imp_memchr:PANYARGS
memchr TEXTEQU <__imp_memchr>
extern __imp_memcmp:PANYARGS
memcmp TEXTEQU <__imp_memcmp>
extern __imp_memcpy:PANYARGS
memcpy TEXTEQU <__imp_memcpy>
extern __imp_memmove:PANYARGS
memmove TEXTEQU <__imp_memmove>
extern __imp_memset:PANYARGS
memset TEXTEQU <__imp_memset>
extern __imp_mktime:PANYARGS
mktime TEXTEQU <__imp_mktime>
extern __imp_modf:PANYARGS
modf TEXTEQU <__imp_modf>
extern __imp_modff:PANYARGS
modff TEXTEQU <__imp_modff>
extern __imp_perror:PANYARGS
perror TEXTEQU <__imp_perror>
extern __imp_pow:PANYARGS
pow TEXTEQU <__imp_pow>
extern __imp_powf:PANYARGS
powf TEXTEQU <__imp_powf>
extern __imp_printf:PANYARGS
printf TEXTEQU <__imp_printf>
extern __imp_putc:PANYARGS
putc TEXTEQU <__imp_putc>
extern __imp_putchar:PANYARGS
putchar TEXTEQU <__imp_putchar>
extern __imp_puts:PANYARGS
puts TEXTEQU <__imp_puts>
extern __imp_putwc:PANYARGS
putwc TEXTEQU <__imp_putwc>
extern __imp_putwchar:PANYARGS
putwchar TEXTEQU <__imp_putwchar>
extern __imp_qsort:PANYARGS
qsort TEXTEQU <__imp_qsort>
extern __imp_raise:PANYARGS
raise TEXTEQU <__imp_raise>
extern __imp_rand:PANYARGS
rand TEXTEQU <__imp_rand>
extern __imp_realloc:PANYARGS
realloc TEXTEQU <__imp_realloc>
extern __imp_remove:PANYARGS
remove TEXTEQU <__imp_remove>
extern __imp_rename:PANYARGS
rename TEXTEQU <__imp_rename>
extern __imp_rewind:PANYARGS
rewind TEXTEQU <__imp_rewind>
extern __imp_scanf:PANYARGS
scanf TEXTEQU <__imp_scanf>
extern __imp_setbuf:PANYARGS
setbuf TEXTEQU <__imp_setbuf>
extern __imp_setjmp:PANYARGS
setjmp TEXTEQU <__imp_setjmp>
extern __imp_setlocale:PANYARGS
setlocale TEXTEQU <__imp_setlocale>
extern __imp_setvbuf:PANYARGS
setvbuf TEXTEQU <__imp_setvbuf>
extern __imp_signal:PANYARGS
signal TEXTEQU <__imp_signal>
extern __imp_sin:PANYARGS
sin TEXTEQU <__imp_sin>
extern __imp_sinf:PANYARGS
sinf TEXTEQU <__imp_sinf>
extern __imp_sinh:PANYARGS
sinh TEXTEQU <__imp_sinh>
extern __imp_sinhf:PANYARGS
sinhf TEXTEQU <__imp_sinhf>
extern __imp_sprintf:PANYARGS
sprintf TEXTEQU <__imp_sprintf>
extern __imp_sqrt:PANYARGS
sqrt TEXTEQU <__imp_sqrt>
extern __imp_sqrtf:PANYARGS
sqrtf TEXTEQU <__imp_sqrtf>
extern __imp_srand:PANYARGS
srand TEXTEQU <__imp_srand>
extern __imp_sscanf:PANYARGS
sscanf TEXTEQU <__imp_sscanf>
extern __imp_strcat:PANYARGS
strcat TEXTEQU <__imp_strcat>
extern __imp_strchr:PANYARGS
strchr TEXTEQU <__imp_strchr>
extern __imp_strcmp:PANYARGS
strcmp TEXTEQU <__imp_strcmp>
extern __imp_strcoll:PANYARGS
strcoll TEXTEQU <__imp_strcoll>
extern __imp_strcpy:PANYARGS
strcpy TEXTEQU <__imp_strcpy>
extern __imp_strcspn:PANYARGS
strcspn TEXTEQU <__imp_strcspn>
extern __imp_strerror:PANYARGS
strerror TEXTEQU <__imp_strerror>
extern __imp_strftime:PANYARGS
strftime TEXTEQU <__imp_strftime>
extern __imp_strlen:PANYARGS
strlen TEXTEQU <__imp_strlen>
extern __imp_strncat:PANYARGS
strncat TEXTEQU <__imp_strncat>
extern __imp_strncmp:PANYARGS
strncmp TEXTEQU <__imp_strncmp>
extern __imp_strncpy:PANYARGS
strncpy TEXTEQU <__imp_strncpy>
extern __imp_strpbrk:PANYARGS
strpbrk TEXTEQU <__imp_strpbrk>
extern __imp_strrchr:PANYARGS
strrchr TEXTEQU <__imp_strrchr>
extern __imp_strspn:PANYARGS
strspn TEXTEQU <__imp_strspn>
extern __imp_strstr:PANYARGS
strstr TEXTEQU <__imp_strstr>
extern __imp_strtod:PANYARGS
strtod TEXTEQU <__imp_strtod>
extern __imp_strtok:PANYARGS
strtok TEXTEQU <__imp_strtok>
extern __imp_strtol:PANYARGS
strtol TEXTEQU <__imp_strtol>
extern __imp_strtoul:PANYARGS
strtoul TEXTEQU <__imp_strtoul>
extern __imp_strxfrm:PANYARGS
strxfrm TEXTEQU <__imp_strxfrm>
extern __imp_swprintf:PANYARGS
swprintf TEXTEQU <__imp_swprintf>
extern __imp_swscanf:PANYARGS
swscanf TEXTEQU <__imp_swscanf>
extern __imp_system:PANYARGS
system TEXTEQU <__imp_system>
extern __imp_tan:PANYARGS
tan TEXTEQU <__imp_tan>
extern __imp_tanf:PANYARGS
tanf TEXTEQU <__imp_tanf>
extern __imp_tanh:PANYARGS
tanh TEXTEQU <__imp_tanh>
extern __imp_time:PANYARGS
time TEXTEQU <__imp_time>
extern __imp_tmpfile:PANYARGS
tmpfile TEXTEQU <__imp_tmpfile>
extern __imp_tmpnam:PANYARGS
tmpnam TEXTEQU <__imp_tmpnam>
extern __imp_tolower:PANYARGS
tolower TEXTEQU <__imp_tolower>
extern __imp_toupper:PANYARGS
toupper TEXTEQU <__imp_toupper>
extern __imp_towlower:PANYARGS
towlower TEXTEQU <__imp_towlower>
extern __imp_towupper:PANYARGS
towupper TEXTEQU <__imp_towupper>
extern __imp_ungetc:PANYARGS
ungetc TEXTEQU <__imp_ungetc>
extern __imp_ungetwc:PANYARGS
ungetwc TEXTEQU <__imp_ungetwc>
extern __imp_vfprintf:PANYARGS
vfprintf TEXTEQU <__imp_vfprintf>
extern __imp_vfwprintf:PANYARGS
vfwprintf TEXTEQU <__imp_vfwprintf>
extern __imp_vprintf:PANYARGS
vprintf TEXTEQU <__imp_vprintf>
extern __imp_vsprintf:PANYARGS
vsprintf TEXTEQU <__imp_vsprintf>
extern __imp_vswprintf:PANYARGS
vswprintf TEXTEQU <__imp_vswprintf>
extern __imp_vwprintf:PANYARGS
vwprintf TEXTEQU <__imp_vwprintf>
extern __imp_wcscat:PANYARGS
wcscat TEXTEQU <__imp_wcscat>
extern __imp_wcschr:PANYARGS
wcschr TEXTEQU <__imp_wcschr>
extern __imp_wcscmp:PANYARGS
wcscmp TEXTEQU <__imp_wcscmp>
extern __imp_wcscoll:PANYARGS
wcscoll TEXTEQU <__imp_wcscoll>
extern __imp_wcscpy:PANYARGS
wcscpy TEXTEQU <__imp_wcscpy>
extern __imp_wcscspn:PANYARGS
wcscspn TEXTEQU <__imp_wcscspn>
extern __imp_wcsftime:PANYARGS
wcsftime TEXTEQU <__imp_wcsftime>
extern __imp_wcslen:PANYARGS
wcslen TEXTEQU <__imp_wcslen>
extern __imp_wcsncat:PANYARGS
wcsncat TEXTEQU <__imp_wcsncat>
extern __imp_wcsncmp:PANYARGS
wcsncmp TEXTEQU <__imp_wcsncmp>
extern __imp_wcsncpy:PANYARGS
wcsncpy TEXTEQU <__imp_wcsncpy>
extern __imp_wcspbrk:PANYARGS
wcspbrk TEXTEQU <__imp_wcspbrk>
extern __imp_wcsrchr:PANYARGS
wcsrchr TEXTEQU <__imp_wcsrchr>
extern __imp_wcsspn:PANYARGS
wcsspn TEXTEQU <__imp_wcsspn>
extern __imp_wcsstr:PANYARGS
wcsstr TEXTEQU <__imp_wcsstr>
extern __imp_wcstod:PANYARGS
wcstod TEXTEQU <__imp_wcstod>
extern __imp_wcstok:PANYARGS
wcstok TEXTEQU <__imp_wcstok>
extern __imp_wcstol:PANYARGS
wcstol TEXTEQU <__imp_wcstol>
extern __imp_wcstombs:PANYARGS
wcstombs TEXTEQU <__imp_wcstombs>
extern __imp_wcstoul:PANYARGS
wcstoul TEXTEQU <__imp_wcstoul>
extern __imp_wcsxfrm:PANYARGS
wcsxfrm TEXTEQU <__imp_wcsxfrm>
extern __imp_wctomb:PANYARGS
wctomb TEXTEQU <__imp_wctomb>
extern __imp_wprintf:PANYARGS
wprintf TEXTEQU <__imp_wprintf>
extern __imp_wscanf:PANYARGS
wscanf TEXTEQU <__imp_wscanf>
