extern __imp_VideoForWindowsVersion:PANYARGS
VideoForWindowsVersion TEXTEQU <__imp_VideoForWindowsVersion>
extern __imp_DrawDibBegin:PANYARGS
DrawDibBegin TEXTEQU <__imp_DrawDibBegin>
extern __imp_DrawDibChangePalette:PANYARGS
DrawDibChangePalette TEXTEQU <__imp_DrawDibChangePalette>
extern __imp_DrawDibClose:PANYARGS
DrawDibClose TEXTEQU <__imp_DrawDibClose>
extern __imp_DrawDibDraw:PANYARGS
DrawDibDraw TEXTEQU <__imp_DrawDibDraw>
extern __imp_DrawDibEnd:PANYARGS
DrawDibEnd TEXTEQU <__imp_DrawDibEnd>
extern __imp_DrawDibGetBuffer:PANYARGS
DrawDibGetBuffer TEXTEQU <__imp_DrawDibGetBuffer>
extern __imp_DrawDibGetPalette:PANYARGS
DrawDibGetPalette TEXTEQU <__imp_DrawDibGetPalette>
extern __imp_DrawDibOpen:PANYARGS
DrawDibOpen TEXTEQU <__imp_DrawDibOpen>
extern __imp_DrawDibProfileDisplay:PANYARGS
DrawDibProfileDisplay TEXTEQU <__imp_DrawDibProfileDisplay>
extern __imp_DrawDibRealize:PANYARGS
DrawDibRealize TEXTEQU <__imp_DrawDibRealize>
extern __imp_DrawDibSetPalette:PANYARGS
DrawDibSetPalette TEXTEQU <__imp_DrawDibSetPalette>
extern __imp_DrawDibStart:PANYARGS
DrawDibStart TEXTEQU <__imp_DrawDibStart>
extern __imp_DrawDibStop:PANYARGS
DrawDibStop TEXTEQU <__imp_DrawDibStop>
extern __imp_DrawDibTime:PANYARGS
DrawDibTime TEXTEQU <__imp_DrawDibTime>
extern __imp_GetOpenFileNamePreview:PANYARGS
GetOpenFileNamePreview TEXTEQU <__imp_GetOpenFileNamePreview>
extern __imp_GetOpenFileNamePreviewA:PANYARGS
GetOpenFileNamePreview  TEXTEQU <__imp_GetOpenFileNamePreviewA>
extern __imp_GetOpenFileNamePreviewW:PANYARGS
GetOpenFileNamePreviewW TEXTEQU <__imp_GetOpenFileNamePreviewW>
extern __imp_GetSaveFileNamePreviewA:PANYARGS
GetSaveFileNamePreview  TEXTEQU <__imp_GetSaveFileNamePreviewA>
extern __imp_GetSaveFileNamePreviewW:PANYARGS
GetSaveFileNamePreviewW TEXTEQU <__imp_GetSaveFileNamePreviewW>
extern __imp_ICClose:PANYARGS
ICClose TEXTEQU <__imp_ICClose>
extern __imp_ICCompress:PANYARGS
ICCompress TEXTEQU <__imp_ICCompress>
extern __imp_ICCompressorChoose:PANYARGS
ICCompressorChoose TEXTEQU <__imp_ICCompressorChoose>
extern __imp_ICCompressorFree:PANYARGS
ICCompressorFree TEXTEQU <__imp_ICCompressorFree>
extern __imp_ICDecompress:PANYARGS
ICDecompress TEXTEQU <__imp_ICDecompress>
extern __imp_ICDraw:PANYARGS
ICDraw TEXTEQU <__imp_ICDraw>
extern __imp_ICDrawBegin:PANYARGS
ICDrawBegin TEXTEQU <__imp_ICDrawBegin>
extern __imp_ICGetDisplayFormat:PANYARGS
ICGetDisplayFormat TEXTEQU <__imp_ICGetDisplayFormat>
extern __imp_ICGetInfo:PANYARGS
ICGetInfo TEXTEQU <__imp_ICGetInfo>
extern __imp_ICImageCompress:PANYARGS
ICImageCompress TEXTEQU <__imp_ICImageCompress>
extern __imp_ICImageDecompress:PANYARGS
ICImageDecompress TEXTEQU <__imp_ICImageDecompress>
extern __imp_ICInfo:PANYARGS
ICInfo TEXTEQU <__imp_ICInfo>
extern __imp_ICInstall:PANYARGS
ICInstall TEXTEQU <__imp_ICInstall>
extern __imp_ICLocate:PANYARGS
ICLocate TEXTEQU <__imp_ICLocate>
extern __imp_ICMThunk32:PANYARGS
ICMThunk32 TEXTEQU <__imp_ICMThunk32>
extern __imp_ICOpen:PANYARGS
ICOpen TEXTEQU <__imp_ICOpen>
extern __imp_ICOpenFunction:PANYARGS
ICOpenFunction TEXTEQU <__imp_ICOpenFunction>
extern __imp_ICRemove:PANYARGS
ICRemove TEXTEQU <__imp_ICRemove>
extern __imp_ICSendMessage:PANYARGS
ICSendMessage TEXTEQU <__imp_ICSendMessage>
extern __imp_ICSeqCompressFrame:PANYARGS
ICSeqCompressFrame TEXTEQU <__imp_ICSeqCompressFrame>
extern __imp_ICSeqCompressFrameEnd:PANYARGS
ICSeqCompressFrameEnd TEXTEQU <__imp_ICSeqCompressFrameEnd>
extern __imp_ICSeqCompressFrameStart:PANYARGS
ICSeqCompressFrameStart TEXTEQU <__imp_ICSeqCompressFrameStart>
extern __imp_MCIWndCreate:PANYARGS
MCIWndCreate TEXTEQU <__imp_MCIWndCreate>
extern __imp_MCIWndCreateA:PANYARGS
MCIWndCreate  TEXTEQU <__imp_MCIWndCreateA>
extern __imp_MCIWndCreateW:PANYARGS
MCIWndCreateW TEXTEQU <__imp_MCIWndCreateW>
extern __imp_MCIWndRegisterClass:PANYARGS
MCIWndRegisterClass TEXTEQU <__imp_MCIWndRegisterClass>
extern __imp_StretchDIB:PANYARGS
StretchDIB TEXTEQU <__imp_StretchDIB>
