extern __imp_ServiceMain:PANYARGS
ServiceMain TEXTEQU <__imp_ServiceMain>
extern __imp_SvchostPushServiceGlobals:PANYARGS
SvchostPushServiceGlobals TEXTEQU <__imp_SvchostPushServiceGlobals>
extern __imp_AcceptEx:PANYARGS
AcceptEx TEXTEQU <__imp_AcceptEx>
extern __imp_EnumProtocolsA:PANYARGS
EnumProtocols  TEXTEQU <__imp_EnumProtocolsA>
extern __imp_EnumProtocolsW:PANYARGS
EnumProtocolsW TEXTEQU <__imp_EnumProtocolsW>
extern __imp_GetAcceptExSockaddrs:PANYARGS
GetAcceptExSockaddrs TEXTEQU <__imp_GetAcceptExSockaddrs>
extern __imp_GetAddressByNameA:PANYARGS
GetAddressByName  TEXTEQU <__imp_GetAddressByNameA>
extern __imp_GetAddressByNameW:PANYARGS
GetAddressByNameW TEXTEQU <__imp_GetAddressByNameW>
extern __imp_GetNameByTypeA:PANYARGS
GetNameByType  TEXTEQU <__imp_GetNameByTypeA>
extern __imp_GetNameByTypeW:PANYARGS
GetNameByTypeW TEXTEQU <__imp_GetNameByTypeW>
extern __imp_GetServiceA:PANYARGS
GetService  TEXTEQU <__imp_GetServiceA>
extern __imp_GetServiceW:PANYARGS
GetServiceW TEXTEQU <__imp_GetServiceW>
extern __imp_GetTypeByNameA:PANYARGS
GetTypeByName  TEXTEQU <__imp_GetTypeByNameA>
extern __imp_GetTypeByNameW:PANYARGS
GetTypeByNameW TEXTEQU <__imp_GetTypeByNameW>
extern __imp_MigrateWinsockConfiguration:PANYARGS
MigrateWinsockConfiguration TEXTEQU <__imp_MigrateWinsockConfiguration>
extern __imp_NPLoadNameSpaces:PANYARGS
NPLoadNameSpaces TEXTEQU <__imp_NPLoadNameSpaces>
extern __imp_NSPStartup:PANYARGS
NSPStartup TEXTEQU <__imp_NSPStartup>
extern __imp_SetServiceA:PANYARGS
SetService  TEXTEQU <__imp_SetServiceA>
extern __imp_SetServiceW:PANYARGS
SetServiceW TEXTEQU <__imp_SetServiceW>
extern __imp_StartWsdpService:PANYARGS
StartWsdpService TEXTEQU <__imp_StartWsdpService>
extern __imp_StopWsdpService:PANYARGS
StopWsdpService TEXTEQU <__imp_StopWsdpService>
extern __imp_TransmitFile:PANYARGS
TransmitFile TEXTEQU <__imp_TransmitFile>
extern __imp_WSARecvEx:PANYARGS
WSARecvEx TEXTEQU <__imp_WSARecvEx>
extern __imp_WSPStartup:PANYARGS
WSPStartup TEXTEQU <__imp_WSPStartup>
extern __imp_dn_expand:PANYARGS
dn_expand TEXTEQU <__imp_dn_expand>
extern __imp_getnetbyname:PANYARGS
getnetbyname TEXTEQU <__imp_getnetbyname>
extern __imp_inet_network:PANYARGS
inet_network TEXTEQU <__imp_inet_network>
extern __imp_rcmd:PANYARGS
rcmd TEXTEQU <__imp_rcmd>
extern __imp_rexec:PANYARGS
rexec TEXTEQU <__imp_rexec>
extern __imp_rresvport:PANYARGS
rresvport TEXTEQU <__imp_rresvport>
extern __imp_s_perror:PANYARGS
s_perror TEXTEQU <__imp_s_perror>
extern __imp_sethostname:PANYARGS
sethostname TEXTEQU <__imp_sethostname>
