extern __imp_obndra:PANYARGS
obndra TEXTEQU <__imp_obndra>
extern __imp_obndrn:PANYARGS
obndrn TEXTEQU <__imp_obndrn>
extern __imp_obndrv:PANYARGS
obndrv TEXTEQU <__imp_obndrv>
extern __imp_obreak:PANYARGS
obreak TEXTEQU <__imp_obreak>
extern __imp_ocan:PANYARGS
ocan TEXTEQU <__imp_ocan>
extern __imp_oclose:PANYARGS
oclose TEXTEQU <__imp_oclose>
extern __imp_ocof:PANYARGS
ocof TEXTEQU <__imp_ocof>
extern __imp_ocom:PANYARGS
ocom TEXTEQU <__imp_ocom>
extern __imp_ocon:PANYARGS
ocon TEXTEQU <__imp_ocon>
extern __imp_odefin:PANYARGS
odefin TEXTEQU <__imp_odefin>
extern __imp_odescr:PANYARGS
odescr TEXTEQU <__imp_odescr>
extern __imp_odessp:PANYARGS
odessp TEXTEQU <__imp_odessp>
extern __imp_oerhms:PANYARGS
oerhms TEXTEQU <__imp_oerhms>
extern __imp_oermsg:PANYARGS
oermsg TEXTEQU <__imp_oermsg>
extern __imp_oexec:PANYARGS
oexec TEXTEQU <__imp_oexec>
extern __imp_oexfet:PANYARGS
oexfet TEXTEQU <__imp_oexfet>
extern __imp_oexn:PANYARGS
oexn TEXTEQU <__imp_oexn>
extern __imp_ofen:PANYARGS
ofen TEXTEQU <__imp_ofen>
extern __imp_ofetch:PANYARGS
ofetch TEXTEQU <__imp_ofetch>
extern __imp_oflng:PANYARGS
oflng TEXTEQU <__imp_oflng>
extern __imp_olog:PANYARGS
olog TEXTEQU <__imp_olog>
extern __imp_ologof:PANYARGS
ologof TEXTEQU <__imp_ologof>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_mtxoci_ordinal25:PANYARGS
mtxoci_ordinal25 TEXTEQU <__imp_mtxoci_ordinal25>
extern __imp_oopen:PANYARGS
oopen TEXTEQU <__imp_oopen>
extern __imp_oopt:PANYARGS
oopt TEXTEQU <__imp_oopt>
extern __imp_oparse:PANYARGS
oparse TEXTEQU <__imp_oparse>
extern __imp_orol:PANYARGS
orol TEXTEQU <__imp_orol>
extern __imp_mtxoci_ordinal30:PANYARGS
mtxoci_ordinal30 TEXTEQU <__imp_mtxoci_ordinal30>
extern __imp_mtxoci_ordinal31:PANYARGS
mtxoci_ordinal31 TEXTEQU <__imp_mtxoci_ordinal31>
extern __imp_mtxoci_ordinal32:PANYARGS
mtxoci_ordinal32 TEXTEQU <__imp_mtxoci_ordinal32>
extern __imp_mtxoci_ordinal33:PANYARGS
mtxoci_ordinal33 TEXTEQU <__imp_mtxoci_ordinal33>
extern __imp_mtxoci_ordinal34:PANYARGS
mtxoci_ordinal34 TEXTEQU <__imp_mtxoci_ordinal34>
extern __imp_mtxoci_ordinal35:PANYARGS
mtxoci_ordinal35 TEXTEQU <__imp_mtxoci_ordinal35>
extern __imp_mtxoci_ordinal36:PANYARGS
mtxoci_ordinal36 TEXTEQU <__imp_mtxoci_ordinal36>
extern __imp_obindps:PANYARGS
obindps TEXTEQU <__imp_obindps>
extern __imp_odefinps:PANYARGS
odefinps TEXTEQU <__imp_odefinps>
extern __imp_ogetpi:PANYARGS
ogetpi TEXTEQU <__imp_ogetpi>
extern __imp_osetpi:PANYARGS
osetpi TEXTEQU <__imp_osetpi>
extern __imp_opinit:PANYARGS
opinit TEXTEQU <__imp_opinit>
extern __imp_mtxoci_ordinal42:PANYARGS
mtxoci_ordinal42 TEXTEQU <__imp_mtxoci_ordinal42>
extern __imp_mtxoci_ordinal43:PANYARGS
mtxoci_ordinal43 TEXTEQU <__imp_mtxoci_ordinal43>
extern __imp_mtxoci_ordinal44:PANYARGS
mtxoci_ordinal44 TEXTEQU <__imp_mtxoci_ordinal44>
extern __imp_mtxoci_ordinal45:PANYARGS
mtxoci_ordinal45 TEXTEQU <__imp_mtxoci_ordinal45>
extern __imp_mtxoci_ordinal46:PANYARGS
mtxoci_ordinal46 TEXTEQU <__imp_mtxoci_ordinal46>
extern __imp_mtxoci_ordinal47:PANYARGS
mtxoci_ordinal47 TEXTEQU <__imp_mtxoci_ordinal47>
extern __imp_mtxoci_ordinal48:PANYARGS
mtxoci_ordinal48 TEXTEQU <__imp_mtxoci_ordinal48>
extern __imp_mtxoci_ordinal49:PANYARGS
mtxoci_ordinal49 TEXTEQU <__imp_mtxoci_ordinal49>
extern __imp_mtxoci_ordinal50:PANYARGS
mtxoci_ordinal50 TEXTEQU <__imp_mtxoci_ordinal50>
extern __imp_mtxoci_ordinal51:PANYARGS
mtxoci_ordinal51 TEXTEQU <__imp_mtxoci_ordinal51>
extern __imp_mtxoci_ordinal52:PANYARGS
mtxoci_ordinal52 TEXTEQU <__imp_mtxoci_ordinal52>
extern __imp_mtxoci_ordinal53:PANYARGS
mtxoci_ordinal53 TEXTEQU <__imp_mtxoci_ordinal53>
extern __imp_mtxoci_ordinal54:PANYARGS
mtxoci_ordinal54 TEXTEQU <__imp_mtxoci_ordinal54>
extern __imp_mtxoci_ordinal55:PANYARGS
mtxoci_ordinal55 TEXTEQU <__imp_mtxoci_ordinal55>
extern __imp_mtxoci_ordinal56:PANYARGS
mtxoci_ordinal56 TEXTEQU <__imp_mtxoci_ordinal56>
extern __imp_mtxoci_ordinal57:PANYARGS
mtxoci_ordinal57 TEXTEQU <__imp_mtxoci_ordinal57>
extern __imp_mtxoci_ordinal58:PANYARGS
mtxoci_ordinal58 TEXTEQU <__imp_mtxoci_ordinal58>
extern __imp_mtxoci_ordinal59:PANYARGS
mtxoci_ordinal59 TEXTEQU <__imp_mtxoci_ordinal59>
extern __imp_mtxoci_ordinal60:PANYARGS
mtxoci_ordinal60 TEXTEQU <__imp_mtxoci_ordinal60>
extern __imp_mtxoci_ordinal61:PANYARGS
mtxoci_ordinal61 TEXTEQU <__imp_mtxoci_ordinal61>
extern __imp_mtxoci_ordinal62:PANYARGS
mtxoci_ordinal62 TEXTEQU <__imp_mtxoci_ordinal62>
extern __imp_mtxoci_ordinal63:PANYARGS
mtxoci_ordinal63 TEXTEQU <__imp_mtxoci_ordinal63>
extern __imp_mtxoci_ordinal64:PANYARGS
mtxoci_ordinal64 TEXTEQU <__imp_mtxoci_ordinal64>
extern __imp_mtxoci_ordinal65:PANYARGS
mtxoci_ordinal65 TEXTEQU <__imp_mtxoci_ordinal65>
extern __imp_mtxoci_ordinal66:PANYARGS
mtxoci_ordinal66 TEXTEQU <__imp_mtxoci_ordinal66>
extern __imp_mtxoci_ordinal67:PANYARGS
mtxoci_ordinal67 TEXTEQU <__imp_mtxoci_ordinal67>
extern __imp_mtxoci_ordinal68:PANYARGS
mtxoci_ordinal68 TEXTEQU <__imp_mtxoci_ordinal68>
extern __imp_mtxoci_ordinal69:PANYARGS
mtxoci_ordinal69 TEXTEQU <__imp_mtxoci_ordinal69>
extern __imp_mtxoci_ordinal70:PANYARGS
mtxoci_ordinal70 TEXTEQU <__imp_mtxoci_ordinal70>
extern __imp_mtxoci_ordinal71:PANYARGS
mtxoci_ordinal71 TEXTEQU <__imp_mtxoci_ordinal71>
extern __imp_mtxoci_ordinal72:PANYARGS
mtxoci_ordinal72 TEXTEQU <__imp_mtxoci_ordinal72>
extern __imp_mtxoci_ordinal73:PANYARGS
mtxoci_ordinal73 TEXTEQU <__imp_mtxoci_ordinal73>
extern __imp_mtxoci_ordinal74:PANYARGS
mtxoci_ordinal74 TEXTEQU <__imp_mtxoci_ordinal74>
extern __imp_mtxoci_ordinal75:PANYARGS
mtxoci_ordinal75 TEXTEQU <__imp_mtxoci_ordinal75>
extern __imp_mtxoci_ordinal76:PANYARGS
mtxoci_ordinal76 TEXTEQU <__imp_mtxoci_ordinal76>
extern __imp_mtxoci_ordinal77:PANYARGS
mtxoci_ordinal77 TEXTEQU <__imp_mtxoci_ordinal77>
extern __imp_mtxoci_ordinal78:PANYARGS
mtxoci_ordinal78 TEXTEQU <__imp_mtxoci_ordinal78>
extern __imp_mtxoci_ordinal79:PANYARGS
mtxoci_ordinal79 TEXTEQU <__imp_mtxoci_ordinal79>
extern __imp_mtxoci_ordinal80:PANYARGS
mtxoci_ordinal80 TEXTEQU <__imp_mtxoci_ordinal80>
extern __imp_mtxoci_ordinal81:PANYARGS
mtxoci_ordinal81 TEXTEQU <__imp_mtxoci_ordinal81>
extern __imp_mtxoci_ordinal82:PANYARGS
mtxoci_ordinal82 TEXTEQU <__imp_mtxoci_ordinal82>
extern __imp_mtxoci_ordinal83:PANYARGS
mtxoci_ordinal83 TEXTEQU <__imp_mtxoci_ordinal83>
extern __imp_mtxoci_ordinal84:PANYARGS
mtxoci_ordinal84 TEXTEQU <__imp_mtxoci_ordinal84>
extern __imp_mtxoci_ordinal85:PANYARGS
mtxoci_ordinal85 TEXTEQU <__imp_mtxoci_ordinal85>
extern __imp_mtxoci_ordinal86:PANYARGS
mtxoci_ordinal86 TEXTEQU <__imp_mtxoci_ordinal86>
extern __imp_mtxoci_ordinal87:PANYARGS
mtxoci_ordinal87 TEXTEQU <__imp_mtxoci_ordinal87>
extern __imp_mtxoci_ordinal88:PANYARGS
mtxoci_ordinal88 TEXTEQU <__imp_mtxoci_ordinal88>
extern __imp_mtxoci_ordinal89:PANYARGS
mtxoci_ordinal89 TEXTEQU <__imp_mtxoci_ordinal89>
extern __imp_mtxoci_ordinal90:PANYARGS
mtxoci_ordinal90 TEXTEQU <__imp_mtxoci_ordinal90>
extern __imp_mtxoci_ordinal91:PANYARGS
mtxoci_ordinal91 TEXTEQU <__imp_mtxoci_ordinal91>
extern __imp_mtxoci_ordinal92:PANYARGS
mtxoci_ordinal92 TEXTEQU <__imp_mtxoci_ordinal92>
extern __imp_mtxoci_ordinal93:PANYARGS
mtxoci_ordinal93 TEXTEQU <__imp_mtxoci_ordinal93>
extern __imp_mtxoci_ordinal94:PANYARGS
mtxoci_ordinal94 TEXTEQU <__imp_mtxoci_ordinal94>
extern __imp_mtxoci_ordinal95:PANYARGS
mtxoci_ordinal95 TEXTEQU <__imp_mtxoci_ordinal95>
extern __imp_mtxoci_ordinal96:PANYARGS
mtxoci_ordinal96 TEXTEQU <__imp_mtxoci_ordinal96>
extern __imp_mtxoci_ordinal97:PANYARGS
mtxoci_ordinal97 TEXTEQU <__imp_mtxoci_ordinal97>
extern __imp_mtxoci_ordinal98:PANYARGS
mtxoci_ordinal98 TEXTEQU <__imp_mtxoci_ordinal98>
extern __imp_mtxoci_ordinal99:PANYARGS
mtxoci_ordinal99 TEXTEQU <__imp_mtxoci_ordinal99>
extern __imp_mtxoci_ordinal100:PANYARGS
mtxoci_ordinal100 TEXTEQU <__imp_mtxoci_ordinal100>
extern __imp_mtxoci_ordinal101:PANYARGS
mtxoci_ordinal101 TEXTEQU <__imp_mtxoci_ordinal101>
extern __imp_mtxoci_ordinal102:PANYARGS
mtxoci_ordinal102 TEXTEQU <__imp_mtxoci_ordinal102>
extern __imp_mtxoci_ordinal103:PANYARGS
mtxoci_ordinal103 TEXTEQU <__imp_mtxoci_ordinal103>
extern __imp_mtxoci_ordinal104:PANYARGS
mtxoci_ordinal104 TEXTEQU <__imp_mtxoci_ordinal104>
extern __imp_mtxoci_ordinal105:PANYARGS
mtxoci_ordinal105 TEXTEQU <__imp_mtxoci_ordinal105>
extern __imp_mtxoci_ordinal106:PANYARGS
mtxoci_ordinal106 TEXTEQU <__imp_mtxoci_ordinal106>
extern __imp_mtxoci_ordinal107:PANYARGS
mtxoci_ordinal107 TEXTEQU <__imp_mtxoci_ordinal107>
extern __imp_mtxoci_ordinal108:PANYARGS
mtxoci_ordinal108 TEXTEQU <__imp_mtxoci_ordinal108>
extern __imp_mtxoci_ordinal109:PANYARGS
mtxoci_ordinal109 TEXTEQU <__imp_mtxoci_ordinal109>
extern __imp_mtxoci_ordinal110:PANYARGS
mtxoci_ordinal110 TEXTEQU <__imp_mtxoci_ordinal110>
extern __imp_mtxoci_ordinal111:PANYARGS
mtxoci_ordinal111 TEXTEQU <__imp_mtxoci_ordinal111>
extern __imp_mtxoci_ordinal112:PANYARGS
mtxoci_ordinal112 TEXTEQU <__imp_mtxoci_ordinal112>
extern __imp_mtxoci_ordinal113:PANYARGS
mtxoci_ordinal113 TEXTEQU <__imp_mtxoci_ordinal113>
extern __imp_mtxoci_ordinal114:PANYARGS
mtxoci_ordinal114 TEXTEQU <__imp_mtxoci_ordinal114>
extern __imp_mtxoci_ordinal115:PANYARGS
mtxoci_ordinal115 TEXTEQU <__imp_mtxoci_ordinal115>
extern __imp_mtxoci_ordinal116:PANYARGS
mtxoci_ordinal116 TEXTEQU <__imp_mtxoci_ordinal116>
extern __imp_mtxoci_ordinal117:PANYARGS
mtxoci_ordinal117 TEXTEQU <__imp_mtxoci_ordinal117>
extern __imp_mtxoci_ordinal118:PANYARGS
mtxoci_ordinal118 TEXTEQU <__imp_mtxoci_ordinal118>
extern __imp_mtxoci_ordinal119:PANYARGS
mtxoci_ordinal119 TEXTEQU <__imp_mtxoci_ordinal119>
extern __imp_mtxoci_ordinal120:PANYARGS
mtxoci_ordinal120 TEXTEQU <__imp_mtxoci_ordinal120>
extern __imp_mtxoci_ordinal121:PANYARGS
mtxoci_ordinal121 TEXTEQU <__imp_mtxoci_ordinal121>
extern __imp_mtxoci_ordinal122:PANYARGS
mtxoci_ordinal122 TEXTEQU <__imp_mtxoci_ordinal122>
extern __imp_mtxoci_ordinal123:PANYARGS
mtxoci_ordinal123 TEXTEQU <__imp_mtxoci_ordinal123>
extern __imp_mtxoci_ordinal124:PANYARGS
mtxoci_ordinal124 TEXTEQU <__imp_mtxoci_ordinal124>
extern __imp_mtxoci_ordinal125:PANYARGS
mtxoci_ordinal125 TEXTEQU <__imp_mtxoci_ordinal125>
extern __imp_mtxoci_ordinal126:PANYARGS
mtxoci_ordinal126 TEXTEQU <__imp_mtxoci_ordinal126>
extern __imp_mtxoci_ordinal127:PANYARGS
mtxoci_ordinal127 TEXTEQU <__imp_mtxoci_ordinal127>
extern __imp_mtxoci_ordinal128:PANYARGS
mtxoci_ordinal128 TEXTEQU <__imp_mtxoci_ordinal128>
extern __imp_mtxoci_ordinal129:PANYARGS
mtxoci_ordinal129 TEXTEQU <__imp_mtxoci_ordinal129>
extern __imp_mtxoci_ordinal130:PANYARGS
mtxoci_ordinal130 TEXTEQU <__imp_mtxoci_ordinal130>
extern __imp_mtxoci_ordinal131:PANYARGS
mtxoci_ordinal131 TEXTEQU <__imp_mtxoci_ordinal131>
extern __imp_mtxoci_ordinal132:PANYARGS
mtxoci_ordinal132 TEXTEQU <__imp_mtxoci_ordinal132>
extern __imp_mtxoci_ordinal133:PANYARGS
mtxoci_ordinal133 TEXTEQU <__imp_mtxoci_ordinal133>
extern __imp_mtxoci_ordinal134:PANYARGS
mtxoci_ordinal134 TEXTEQU <__imp_mtxoci_ordinal134>
extern __imp_mtxoci_ordinal135:PANYARGS
mtxoci_ordinal135 TEXTEQU <__imp_mtxoci_ordinal135>
extern __imp_mtxoci_ordinal136:PANYARGS
mtxoci_ordinal136 TEXTEQU <__imp_mtxoci_ordinal136>
extern __imp_mtxoci_ordinal137:PANYARGS
mtxoci_ordinal137 TEXTEQU <__imp_mtxoci_ordinal137>
extern __imp_mtxoci_ordinal138:PANYARGS
mtxoci_ordinal138 TEXTEQU <__imp_mtxoci_ordinal138>
extern __imp_mtxoci_ordinal139:PANYARGS
mtxoci_ordinal139 TEXTEQU <__imp_mtxoci_ordinal139>
extern __imp_mtxoci_ordinal140:PANYARGS
mtxoci_ordinal140 TEXTEQU <__imp_mtxoci_ordinal140>
extern __imp_mtxoci_ordinal141:PANYARGS
mtxoci_ordinal141 TEXTEQU <__imp_mtxoci_ordinal141>
extern __imp_mtxoci_ordinal142:PANYARGS
mtxoci_ordinal142 TEXTEQU <__imp_mtxoci_ordinal142>
extern __imp_mtxoci_ordinal143:PANYARGS
mtxoci_ordinal143 TEXTEQU <__imp_mtxoci_ordinal143>
extern __imp_mtxoci_ordinal144:PANYARGS
mtxoci_ordinal144 TEXTEQU <__imp_mtxoci_ordinal144>
extern __imp_mtxoci_ordinal145:PANYARGS
mtxoci_ordinal145 TEXTEQU <__imp_mtxoci_ordinal145>
extern __imp_mtxoci_ordinal146:PANYARGS
mtxoci_ordinal146 TEXTEQU <__imp_mtxoci_ordinal146>
extern __imp_mtxoci_ordinal147:PANYARGS
mtxoci_ordinal147 TEXTEQU <__imp_mtxoci_ordinal147>
extern __imp_mtxoci_ordinal148:PANYARGS
mtxoci_ordinal148 TEXTEQU <__imp_mtxoci_ordinal148>
extern __imp_mtxoci_ordinal149:PANYARGS
mtxoci_ordinal149 TEXTEQU <__imp_mtxoci_ordinal149>
extern __imp_mtxoci_ordinal150:PANYARGS
mtxoci_ordinal150 TEXTEQU <__imp_mtxoci_ordinal150>
extern __imp_mtxoci_ordinal151:PANYARGS
mtxoci_ordinal151 TEXTEQU <__imp_mtxoci_ordinal151>
extern __imp_mtxoci_ordinal152:PANYARGS
mtxoci_ordinal152 TEXTEQU <__imp_mtxoci_ordinal152>
extern __imp_mtxoci_ordinal153:PANYARGS
mtxoci_ordinal153 TEXTEQU <__imp_mtxoci_ordinal153>
extern __imp_mtxoci_ordinal154:PANYARGS
mtxoci_ordinal154 TEXTEQU <__imp_mtxoci_ordinal154>
extern __imp_mtxoci_ordinal155:PANYARGS
mtxoci_ordinal155 TEXTEQU <__imp_mtxoci_ordinal155>
extern __imp_mtxoci_ordinal156:PANYARGS
mtxoci_ordinal156 TEXTEQU <__imp_mtxoci_ordinal156>
extern __imp_mtxoci_ordinal157:PANYARGS
mtxoci_ordinal157 TEXTEQU <__imp_mtxoci_ordinal157>
extern __imp_mtxoci_ordinal158:PANYARGS
mtxoci_ordinal158 TEXTEQU <__imp_mtxoci_ordinal158>
extern __imp_mtxoci_ordinal159:PANYARGS
mtxoci_ordinal159 TEXTEQU <__imp_mtxoci_ordinal159>
extern __imp_mtxoci_ordinal160:PANYARGS
mtxoci_ordinal160 TEXTEQU <__imp_mtxoci_ordinal160>
extern __imp_mtxoci_ordinal161:PANYARGS
mtxoci_ordinal161 TEXTEQU <__imp_mtxoci_ordinal161>
extern __imp_mtxoci_ordinal162:PANYARGS
mtxoci_ordinal162 TEXTEQU <__imp_mtxoci_ordinal162>
extern __imp_mtxoci_ordinal163:PANYARGS
mtxoci_ordinal163 TEXTEQU <__imp_mtxoci_ordinal163>
extern __imp_mtxoci_ordinal164:PANYARGS
mtxoci_ordinal164 TEXTEQU <__imp_mtxoci_ordinal164>
extern __imp_mtxoci_ordinal165:PANYARGS
mtxoci_ordinal165 TEXTEQU <__imp_mtxoci_ordinal165>
extern __imp_mtxoci_ordinal166:PANYARGS
mtxoci_ordinal166 TEXTEQU <__imp_mtxoci_ordinal166>
extern __imp_mtxoci_ordinal167:PANYARGS
mtxoci_ordinal167 TEXTEQU <__imp_mtxoci_ordinal167>
extern __imp_mtxoci_ordinal168:PANYARGS
mtxoci_ordinal168 TEXTEQU <__imp_mtxoci_ordinal168>
extern __imp_mtxoci_ordinal169:PANYARGS
mtxoci_ordinal169 TEXTEQU <__imp_mtxoci_ordinal169>
extern __imp_mtxoci_ordinal170:PANYARGS
mtxoci_ordinal170 TEXTEQU <__imp_mtxoci_ordinal170>
extern __imp_mtxoci_ordinal171:PANYARGS
mtxoci_ordinal171 TEXTEQU <__imp_mtxoci_ordinal171>
extern __imp_mtxoci_ordinal172:PANYARGS
mtxoci_ordinal172 TEXTEQU <__imp_mtxoci_ordinal172>
extern __imp_mtxoci_ordinal173:PANYARGS
mtxoci_ordinal173 TEXTEQU <__imp_mtxoci_ordinal173>
extern __imp_mtxoci_ordinal174:PANYARGS
mtxoci_ordinal174 TEXTEQU <__imp_mtxoci_ordinal174>
extern __imp_mtxoci_ordinal175:PANYARGS
mtxoci_ordinal175 TEXTEQU <__imp_mtxoci_ordinal175>
extern __imp_mtxoci_ordinal176:PANYARGS
mtxoci_ordinal176 TEXTEQU <__imp_mtxoci_ordinal176>
extern __imp_mtxoci_ordinal177:PANYARGS
mtxoci_ordinal177 TEXTEQU <__imp_mtxoci_ordinal177>
extern __imp_mtxoci_ordinal178:PANYARGS
mtxoci_ordinal178 TEXTEQU <__imp_mtxoci_ordinal178>
extern __imp_mtxoci_ordinal179:PANYARGS
mtxoci_ordinal179 TEXTEQU <__imp_mtxoci_ordinal179>
extern __imp_mtxoci_ordinal180:PANYARGS
mtxoci_ordinal180 TEXTEQU <__imp_mtxoci_ordinal180>
extern __imp_mtxoci_ordinal181:PANYARGS
mtxoci_ordinal181 TEXTEQU <__imp_mtxoci_ordinal181>
extern __imp_mtxoci_ordinal182:PANYARGS
mtxoci_ordinal182 TEXTEQU <__imp_mtxoci_ordinal182>
extern __imp_mtxoci_ordinal183:PANYARGS
mtxoci_ordinal183 TEXTEQU <__imp_mtxoci_ordinal183>
extern __imp_mtxoci_ordinal184:PANYARGS
mtxoci_ordinal184 TEXTEQU <__imp_mtxoci_ordinal184>
extern __imp_mtxoci_ordinal185:PANYARGS
mtxoci_ordinal185 TEXTEQU <__imp_mtxoci_ordinal185>
extern __imp_mtxoci_ordinal186:PANYARGS
mtxoci_ordinal186 TEXTEQU <__imp_mtxoci_ordinal186>
extern __imp_mtxoci_ordinal187:PANYARGS
mtxoci_ordinal187 TEXTEQU <__imp_mtxoci_ordinal187>
extern __imp_mtxoci_ordinal188:PANYARGS
mtxoci_ordinal188 TEXTEQU <__imp_mtxoci_ordinal188>
extern __imp_mtxoci_ordinal189:PANYARGS
mtxoci_ordinal189 TEXTEQU <__imp_mtxoci_ordinal189>
extern __imp_mtxoci_ordinal190:PANYARGS
mtxoci_ordinal190 TEXTEQU <__imp_mtxoci_ordinal190>
extern __imp_mtxoci_ordinal191:PANYARGS
mtxoci_ordinal191 TEXTEQU <__imp_mtxoci_ordinal191>
extern __imp_mtxoci_ordinal192:PANYARGS
mtxoci_ordinal192 TEXTEQU <__imp_mtxoci_ordinal192>
extern __imp_mtxoci_ordinal193:PANYARGS
mtxoci_ordinal193 TEXTEQU <__imp_mtxoci_ordinal193>
extern __imp_mtxoci_ordinal194:PANYARGS
mtxoci_ordinal194 TEXTEQU <__imp_mtxoci_ordinal194>
extern __imp_mtxoci_ordinal195:PANYARGS
mtxoci_ordinal195 TEXTEQU <__imp_mtxoci_ordinal195>
extern __imp_mtxoci_ordinal196:PANYARGS
mtxoci_ordinal196 TEXTEQU <__imp_mtxoci_ordinal196>
extern __imp_mtxoci_ordinal197:PANYARGS
mtxoci_ordinal197 TEXTEQU <__imp_mtxoci_ordinal197>
extern __imp_mtxoci_ordinal198:PANYARGS
mtxoci_ordinal198 TEXTEQU <__imp_mtxoci_ordinal198>
extern __imp_mtxoci_ordinal199:PANYARGS
mtxoci_ordinal199 TEXTEQU <__imp_mtxoci_ordinal199>
extern __imp_mtxoci_ordinal200:PANYARGS
mtxoci_ordinal200 TEXTEQU <__imp_mtxoci_ordinal200>
extern __imp_mtxoci_ordinal201:PANYARGS
mtxoci_ordinal201 TEXTEQU <__imp_mtxoci_ordinal201>
extern __imp_mtxoci_ordinal202:PANYARGS
mtxoci_ordinal202 TEXTEQU <__imp_mtxoci_ordinal202>
extern __imp_mtxoci_ordinal203:PANYARGS
mtxoci_ordinal203 TEXTEQU <__imp_mtxoci_ordinal203>
extern __imp_mtxoci_ordinal204:PANYARGS
mtxoci_ordinal204 TEXTEQU <__imp_mtxoci_ordinal204>
extern __imp_mtxoci_ordinal205:PANYARGS
mtxoci_ordinal205 TEXTEQU <__imp_mtxoci_ordinal205>
extern __imp_mtxoci_ordinal206:PANYARGS
mtxoci_ordinal206 TEXTEQU <__imp_mtxoci_ordinal206>
extern __imp_mtxoci_ordinal207:PANYARGS
mtxoci_ordinal207 TEXTEQU <__imp_mtxoci_ordinal207>
extern __imp_mtxoci_ordinal208:PANYARGS
mtxoci_ordinal208 TEXTEQU <__imp_mtxoci_ordinal208>
extern __imp_mtxoci_ordinal209:PANYARGS
mtxoci_ordinal209 TEXTEQU <__imp_mtxoci_ordinal209>
extern __imp_mtxoci_ordinal210:PANYARGS
mtxoci_ordinal210 TEXTEQU <__imp_mtxoci_ordinal210>
extern __imp_mtxoci_ordinal211:PANYARGS
mtxoci_ordinal211 TEXTEQU <__imp_mtxoci_ordinal211>
extern __imp_mtxoci_ordinal212:PANYARGS
mtxoci_ordinal212 TEXTEQU <__imp_mtxoci_ordinal212>
extern __imp_mtxoci_ordinal213:PANYARGS
mtxoci_ordinal213 TEXTEQU <__imp_mtxoci_ordinal213>
extern __imp_mtxoci_ordinal214:PANYARGS
mtxoci_ordinal214 TEXTEQU <__imp_mtxoci_ordinal214>
extern __imp_mtxoci_ordinal215:PANYARGS
mtxoci_ordinal215 TEXTEQU <__imp_mtxoci_ordinal215>
extern __imp_mtxoci_ordinal216:PANYARGS
mtxoci_ordinal216 TEXTEQU <__imp_mtxoci_ordinal216>
extern __imp_mtxoci_ordinal217:PANYARGS
mtxoci_ordinal217 TEXTEQU <__imp_mtxoci_ordinal217>
extern __imp_mtxoci_ordinal218:PANYARGS
mtxoci_ordinal218 TEXTEQU <__imp_mtxoci_ordinal218>
extern __imp_mtxoci_ordinal219:PANYARGS
mtxoci_ordinal219 TEXTEQU <__imp_mtxoci_ordinal219>
extern __imp_mtxoci_ordinal220:PANYARGS
mtxoci_ordinal220 TEXTEQU <__imp_mtxoci_ordinal220>
extern __imp_mtxoci_ordinal221:PANYARGS
mtxoci_ordinal221 TEXTEQU <__imp_mtxoci_ordinal221>
extern __imp_mtxoci_ordinal222:PANYARGS
mtxoci_ordinal222 TEXTEQU <__imp_mtxoci_ordinal222>
extern __imp_mtxoci_ordinal223:PANYARGS
mtxoci_ordinal223 TEXTEQU <__imp_mtxoci_ordinal223>
extern __imp_mtxoci_ordinal224:PANYARGS
mtxoci_ordinal224 TEXTEQU <__imp_mtxoci_ordinal224>
extern __imp_mtxoci_ordinal225:PANYARGS
mtxoci_ordinal225 TEXTEQU <__imp_mtxoci_ordinal225>
extern __imp_mtxoci_ordinal226:PANYARGS
mtxoci_ordinal226 TEXTEQU <__imp_mtxoci_ordinal226>
extern __imp_mtxoci_ordinal227:PANYARGS
mtxoci_ordinal227 TEXTEQU <__imp_mtxoci_ordinal227>
extern __imp_mtxoci_ordinal228:PANYARGS
mtxoci_ordinal228 TEXTEQU <__imp_mtxoci_ordinal228>
extern __imp_mtxoci_ordinal229:PANYARGS
mtxoci_ordinal229 TEXTEQU <__imp_mtxoci_ordinal229>
extern __imp_mtxoci_ordinal230:PANYARGS
mtxoci_ordinal230 TEXTEQU <__imp_mtxoci_ordinal230>
extern __imp_mtxoci_ordinal231:PANYARGS
mtxoci_ordinal231 TEXTEQU <__imp_mtxoci_ordinal231>
extern __imp_mtxoci_ordinal232:PANYARGS
mtxoci_ordinal232 TEXTEQU <__imp_mtxoci_ordinal232>
extern __imp_mtxoci_ordinal233:PANYARGS
mtxoci_ordinal233 TEXTEQU <__imp_mtxoci_ordinal233>
extern __imp_mtxoci_ordinal234:PANYARGS
mtxoci_ordinal234 TEXTEQU <__imp_mtxoci_ordinal234>
extern __imp_mtxoci_ordinal235:PANYARGS
mtxoci_ordinal235 TEXTEQU <__imp_mtxoci_ordinal235>
extern __imp_mtxoci_ordinal236:PANYARGS
mtxoci_ordinal236 TEXTEQU <__imp_mtxoci_ordinal236>
extern __imp_mtxoci_ordinal237:PANYARGS
mtxoci_ordinal237 TEXTEQU <__imp_mtxoci_ordinal237>
extern __imp_mtxoci_ordinal238:PANYARGS
mtxoci_ordinal238 TEXTEQU <__imp_mtxoci_ordinal238>
extern __imp_mtxoci_ordinal239:PANYARGS
mtxoci_ordinal239 TEXTEQU <__imp_mtxoci_ordinal239>
extern __imp_mtxoci_ordinal240:PANYARGS
mtxoci_ordinal240 TEXTEQU <__imp_mtxoci_ordinal240>
extern __imp_mtxoci_ordinal241:PANYARGS
mtxoci_ordinal241 TEXTEQU <__imp_mtxoci_ordinal241>
extern __imp_mtxoci_ordinal242:PANYARGS
mtxoci_ordinal242 TEXTEQU <__imp_mtxoci_ordinal242>
extern __imp_mtxoci_ordinal243:PANYARGS
mtxoci_ordinal243 TEXTEQU <__imp_mtxoci_ordinal243>
extern __imp_mtxoci_ordinal244:PANYARGS
mtxoci_ordinal244 TEXTEQU <__imp_mtxoci_ordinal244>
extern __imp_mtxoci_ordinal245:PANYARGS
mtxoci_ordinal245 TEXTEQU <__imp_mtxoci_ordinal245>
extern __imp_mtxoci_ordinal246:PANYARGS
mtxoci_ordinal246 TEXTEQU <__imp_mtxoci_ordinal246>
extern __imp_mtxoci_ordinal247:PANYARGS
mtxoci_ordinal247 TEXTEQU <__imp_mtxoci_ordinal247>
extern __imp_mtxoci_ordinal248:PANYARGS
mtxoci_ordinal248 TEXTEQU <__imp_mtxoci_ordinal248>
extern __imp_mtxoci_ordinal249:PANYARGS
mtxoci_ordinal249 TEXTEQU <__imp_mtxoci_ordinal249>
extern __imp_mtxoci_ordinal250:PANYARGS
mtxoci_ordinal250 TEXTEQU <__imp_mtxoci_ordinal250>
extern __imp_mtxoci_ordinal251:PANYARGS
mtxoci_ordinal251 TEXTEQU <__imp_mtxoci_ordinal251>
extern __imp_mtxoci_ordinal252:PANYARGS
mtxoci_ordinal252 TEXTEQU <__imp_mtxoci_ordinal252>
extern __imp_mtxoci_ordinal253:PANYARGS
mtxoci_ordinal253 TEXTEQU <__imp_mtxoci_ordinal253>
extern __imp_mtxoci_ordinal254:PANYARGS
mtxoci_ordinal254 TEXTEQU <__imp_mtxoci_ordinal254>
extern __imp_mtxoci_ordinal255:PANYARGS
mtxoci_ordinal255 TEXTEQU <__imp_mtxoci_ordinal255>
extern __imp_mtxoci_ordinal256:PANYARGS
mtxoci_ordinal256 TEXTEQU <__imp_mtxoci_ordinal256>
extern __imp_mtxoci_ordinal257:PANYARGS
mtxoci_ordinal257 TEXTEQU <__imp_mtxoci_ordinal257>
extern __imp_mtxoci_ordinal258:PANYARGS
mtxoci_ordinal258 TEXTEQU <__imp_mtxoci_ordinal258>
extern __imp_mtxoci_ordinal259:PANYARGS
mtxoci_ordinal259 TEXTEQU <__imp_mtxoci_ordinal259>
extern __imp_mtxoci_ordinal260:PANYARGS
mtxoci_ordinal260 TEXTEQU <__imp_mtxoci_ordinal260>
extern __imp_mtxoci_ordinal261:PANYARGS
mtxoci_ordinal261 TEXTEQU <__imp_mtxoci_ordinal261>
extern __imp_mtxoci_ordinal262:PANYARGS
mtxoci_ordinal262 TEXTEQU <__imp_mtxoci_ordinal262>
extern __imp_mtxoci_ordinal263:PANYARGS
mtxoci_ordinal263 TEXTEQU <__imp_mtxoci_ordinal263>
extern __imp_mtxoci_ordinal264:PANYARGS
mtxoci_ordinal264 TEXTEQU <__imp_mtxoci_ordinal264>
extern __imp_mtxoci_ordinal265:PANYARGS
mtxoci_ordinal265 TEXTEQU <__imp_mtxoci_ordinal265>
extern __imp_mtxoci_ordinal266:PANYARGS
mtxoci_ordinal266 TEXTEQU <__imp_mtxoci_ordinal266>
extern __imp_mtxoci_ordinal267:PANYARGS
mtxoci_ordinal267 TEXTEQU <__imp_mtxoci_ordinal267>
extern __imp_mtxoci_ordinal268:PANYARGS
mtxoci_ordinal268 TEXTEQU <__imp_mtxoci_ordinal268>
extern __imp_mtxoci_ordinal269:PANYARGS
mtxoci_ordinal269 TEXTEQU <__imp_mtxoci_ordinal269>
extern __imp_mtxoci_ordinal270:PANYARGS
mtxoci_ordinal270 TEXTEQU <__imp_mtxoci_ordinal270>
extern __imp_mtxoci_ordinal271:PANYARGS
mtxoci_ordinal271 TEXTEQU <__imp_mtxoci_ordinal271>
extern __imp_mtxoci_ordinal272:PANYARGS
mtxoci_ordinal272 TEXTEQU <__imp_mtxoci_ordinal272>
extern __imp_mtxoci_ordinal273:PANYARGS
mtxoci_ordinal273 TEXTEQU <__imp_mtxoci_ordinal273>
extern __imp_mtxoci_ordinal274:PANYARGS
mtxoci_ordinal274 TEXTEQU <__imp_mtxoci_ordinal274>
extern __imp_mtxoci_ordinal275:PANYARGS
mtxoci_ordinal275 TEXTEQU <__imp_mtxoci_ordinal275>
extern __imp_mtxoci_ordinal276:PANYARGS
mtxoci_ordinal276 TEXTEQU <__imp_mtxoci_ordinal276>
extern __imp_mtxoci_ordinal277:PANYARGS
mtxoci_ordinal277 TEXTEQU <__imp_mtxoci_ordinal277>
extern __imp_mtxoci_ordinal278:PANYARGS
mtxoci_ordinal278 TEXTEQU <__imp_mtxoci_ordinal278>
extern __imp_mtxoci_ordinal279:PANYARGS
mtxoci_ordinal279 TEXTEQU <__imp_mtxoci_ordinal279>
extern __imp_mtxoci_ordinal280:PANYARGS
mtxoci_ordinal280 TEXTEQU <__imp_mtxoci_ordinal280>
extern __imp_mtxoci_ordinal281:PANYARGS
mtxoci_ordinal281 TEXTEQU <__imp_mtxoci_ordinal281>
extern __imp_mtxoci_ordinal282:PANYARGS
mtxoci_ordinal282 TEXTEQU <__imp_mtxoci_ordinal282>
extern __imp_mtxoci_ordinal283:PANYARGS
mtxoci_ordinal283 TEXTEQU <__imp_mtxoci_ordinal283>
extern __imp_mtxoci_ordinal284:PANYARGS
mtxoci_ordinal284 TEXTEQU <__imp_mtxoci_ordinal284>
extern __imp_mtxoci_ordinal285:PANYARGS
mtxoci_ordinal285 TEXTEQU <__imp_mtxoci_ordinal285>
extern __imp_mtxoci_ordinal286:PANYARGS
mtxoci_ordinal286 TEXTEQU <__imp_mtxoci_ordinal286>
extern __imp_mtxoci_ordinal287:PANYARGS
mtxoci_ordinal287 TEXTEQU <__imp_mtxoci_ordinal287>
extern __imp_mtxoci_ordinal288:PANYARGS
mtxoci_ordinal288 TEXTEQU <__imp_mtxoci_ordinal288>
extern __imp_mtxoci_ordinal289:PANYARGS
mtxoci_ordinal289 TEXTEQU <__imp_mtxoci_ordinal289>
extern __imp_mtxoci_ordinal290:PANYARGS
mtxoci_ordinal290 TEXTEQU <__imp_mtxoci_ordinal290>
extern __imp_mtxoci_ordinal291:PANYARGS
mtxoci_ordinal291 TEXTEQU <__imp_mtxoci_ordinal291>
extern __imp_mtxoci_ordinal292:PANYARGS
mtxoci_ordinal292 TEXTEQU <__imp_mtxoci_ordinal292>
extern __imp_mtxoci_ordinal293:PANYARGS
mtxoci_ordinal293 TEXTEQU <__imp_mtxoci_ordinal293>
extern __imp_mtxoci_ordinal294:PANYARGS
mtxoci_ordinal294 TEXTEQU <__imp_mtxoci_ordinal294>
extern __imp_mtxoci_ordinal295:PANYARGS
mtxoci_ordinal295 TEXTEQU <__imp_mtxoci_ordinal295>
extern __imp_mtxoci_ordinal296:PANYARGS
mtxoci_ordinal296 TEXTEQU <__imp_mtxoci_ordinal296>
extern __imp_mtxoci_ordinal297:PANYARGS
mtxoci_ordinal297 TEXTEQU <__imp_mtxoci_ordinal297>
extern __imp_mtxoci_ordinal298:PANYARGS
mtxoci_ordinal298 TEXTEQU <__imp_mtxoci_ordinal298>
extern __imp_mtxoci_ordinal299:PANYARGS
mtxoci_ordinal299 TEXTEQU <__imp_mtxoci_ordinal299>
extern __imp_mtxoci_ordinal300:PANYARGS
mtxoci_ordinal300 TEXTEQU <__imp_mtxoci_ordinal300>
extern __imp_mtxoci_ordinal301:PANYARGS
mtxoci_ordinal301 TEXTEQU <__imp_mtxoci_ordinal301>
extern __imp_mtxoci_ordinal302:PANYARGS
mtxoci_ordinal302 TEXTEQU <__imp_mtxoci_ordinal302>
extern __imp_mtxoci_ordinal303:PANYARGS
mtxoci_ordinal303 TEXTEQU <__imp_mtxoci_ordinal303>
extern __imp_mtxoci_ordinal304:PANYARGS
mtxoci_ordinal304 TEXTEQU <__imp_mtxoci_ordinal304>
extern __imp_mtxoci_ordinal305:PANYARGS
mtxoci_ordinal305 TEXTEQU <__imp_mtxoci_ordinal305>
extern __imp_mtxoci_ordinal306:PANYARGS
mtxoci_ordinal306 TEXTEQU <__imp_mtxoci_ordinal306>
extern __imp_mtxoci_ordinal307:PANYARGS
mtxoci_ordinal307 TEXTEQU <__imp_mtxoci_ordinal307>
extern __imp_mtxoci_ordinal308:PANYARGS
mtxoci_ordinal308 TEXTEQU <__imp_mtxoci_ordinal308>
extern __imp_mtxoci_ordinal309:PANYARGS
mtxoci_ordinal309 TEXTEQU <__imp_mtxoci_ordinal309>
extern __imp_mtxoci_ordinal310:PANYARGS
mtxoci_ordinal310 TEXTEQU <__imp_mtxoci_ordinal310>
extern __imp_mtxoci_ordinal311:PANYARGS
mtxoci_ordinal311 TEXTEQU <__imp_mtxoci_ordinal311>
extern __imp_mtxoci_ordinal312:PANYARGS
mtxoci_ordinal312 TEXTEQU <__imp_mtxoci_ordinal312>
extern __imp_mtxoci_ordinal313:PANYARGS
mtxoci_ordinal313 TEXTEQU <__imp_mtxoci_ordinal313>
extern __imp_mtxoci_ordinal314:PANYARGS
mtxoci_ordinal314 TEXTEQU <__imp_mtxoci_ordinal314>
extern __imp_mtxoci_ordinal315:PANYARGS
mtxoci_ordinal315 TEXTEQU <__imp_mtxoci_ordinal315>
extern __imp_mtxoci_ordinal316:PANYARGS
mtxoci_ordinal316 TEXTEQU <__imp_mtxoci_ordinal316>
extern __imp_mtxoci_ordinal317:PANYARGS
mtxoci_ordinal317 TEXTEQU <__imp_mtxoci_ordinal317>
extern __imp_mtxoci_ordinal318:PANYARGS
mtxoci_ordinal318 TEXTEQU <__imp_mtxoci_ordinal318>
extern __imp_mtxoci_ordinal319:PANYARGS
mtxoci_ordinal319 TEXTEQU <__imp_mtxoci_ordinal319>
extern __imp_mtxoci_ordinal320:PANYARGS
mtxoci_ordinal320 TEXTEQU <__imp_mtxoci_ordinal320>
extern __imp_mtxoci_ordinal321:PANYARGS
mtxoci_ordinal321 TEXTEQU <__imp_mtxoci_ordinal321>
extern __imp_mtxoci_ordinal322:PANYARGS
mtxoci_ordinal322 TEXTEQU <__imp_mtxoci_ordinal322>
extern __imp_mtxoci_ordinal323:PANYARGS
mtxoci_ordinal323 TEXTEQU <__imp_mtxoci_ordinal323>
extern __imp_mtxoci_ordinal324:PANYARGS
mtxoci_ordinal324 TEXTEQU <__imp_mtxoci_ordinal324>
extern __imp_mtxoci_ordinal325:PANYARGS
mtxoci_ordinal325 TEXTEQU <__imp_mtxoci_ordinal325>
extern __imp_mtxoci_ordinal326:PANYARGS
mtxoci_ordinal326 TEXTEQU <__imp_mtxoci_ordinal326>
extern __imp_mtxoci_ordinal327:PANYARGS
mtxoci_ordinal327 TEXTEQU <__imp_mtxoci_ordinal327>
extern __imp_mtxoci_ordinal328:PANYARGS
mtxoci_ordinal328 TEXTEQU <__imp_mtxoci_ordinal328>
extern __imp_mtxoci_ordinal329:PANYARGS
mtxoci_ordinal329 TEXTEQU <__imp_mtxoci_ordinal329>
extern __imp_mtxoci_ordinal330:PANYARGS
mtxoci_ordinal330 TEXTEQU <__imp_mtxoci_ordinal330>
extern __imp_mtxoci_ordinal331:PANYARGS
mtxoci_ordinal331 TEXTEQU <__imp_mtxoci_ordinal331>
extern __imp_mtxoci_ordinal332:PANYARGS
mtxoci_ordinal332 TEXTEQU <__imp_mtxoci_ordinal332>
extern __imp_mtxoci_ordinal333:PANYARGS
mtxoci_ordinal333 TEXTEQU <__imp_mtxoci_ordinal333>
extern __imp_mtxoci_ordinal334:PANYARGS
mtxoci_ordinal334 TEXTEQU <__imp_mtxoci_ordinal334>
extern __imp_mtxoci_ordinal335:PANYARGS
mtxoci_ordinal335 TEXTEQU <__imp_mtxoci_ordinal335>
extern __imp_mtxoci_ordinal336:PANYARGS
mtxoci_ordinal336 TEXTEQU <__imp_mtxoci_ordinal336>
extern __imp_mtxoci_ordinal337:PANYARGS
mtxoci_ordinal337 TEXTEQU <__imp_mtxoci_ordinal337>
extern __imp_mtxoci_ordinal338:PANYARGS
mtxoci_ordinal338 TEXTEQU <__imp_mtxoci_ordinal338>
extern __imp_mtxoci_ordinal339:PANYARGS
mtxoci_ordinal339 TEXTEQU <__imp_mtxoci_ordinal339>
extern __imp_mtxoci_ordinal340:PANYARGS
mtxoci_ordinal340 TEXTEQU <__imp_mtxoci_ordinal340>
extern __imp_mtxoci_ordinal341:PANYARGS
mtxoci_ordinal341 TEXTEQU <__imp_mtxoci_ordinal341>
extern __imp_mtxoci_ordinal342:PANYARGS
mtxoci_ordinal342 TEXTEQU <__imp_mtxoci_ordinal342>
extern __imp_mtxoci_ordinal343:PANYARGS
mtxoci_ordinal343 TEXTEQU <__imp_mtxoci_ordinal343>
extern __imp_mtxoci_ordinal344:PANYARGS
mtxoci_ordinal344 TEXTEQU <__imp_mtxoci_ordinal344>
extern __imp_mtxoci_ordinal345:PANYARGS
mtxoci_ordinal345 TEXTEQU <__imp_mtxoci_ordinal345>
extern __imp_mtxoci_ordinal346:PANYARGS
mtxoci_ordinal346 TEXTEQU <__imp_mtxoci_ordinal346>
extern __imp_mtxoci_ordinal347:PANYARGS
mtxoci_ordinal347 TEXTEQU <__imp_mtxoci_ordinal347>
extern __imp_mtxoci_ordinal348:PANYARGS
mtxoci_ordinal348 TEXTEQU <__imp_mtxoci_ordinal348>
extern __imp_mtxoci_ordinal349:PANYARGS
mtxoci_ordinal349 TEXTEQU <__imp_mtxoci_ordinal349>
extern __imp_mtxoci_ordinal350:PANYARGS
mtxoci_ordinal350 TEXTEQU <__imp_mtxoci_ordinal350>
extern __imp_mtxoci_ordinal351:PANYARGS
mtxoci_ordinal351 TEXTEQU <__imp_mtxoci_ordinal351>
extern __imp_mtxoci_ordinal352:PANYARGS
mtxoci_ordinal352 TEXTEQU <__imp_mtxoci_ordinal352>
extern __imp_mtxoci_ordinal353:PANYARGS
mtxoci_ordinal353 TEXTEQU <__imp_mtxoci_ordinal353>
extern __imp_mtxoci_ordinal354:PANYARGS
mtxoci_ordinal354 TEXTEQU <__imp_mtxoci_ordinal354>
extern __imp_mtxoci_ordinal355:PANYARGS
mtxoci_ordinal355 TEXTEQU <__imp_mtxoci_ordinal355>
extern __imp_mtxoci_ordinal356:PANYARGS
mtxoci_ordinal356 TEXTEQU <__imp_mtxoci_ordinal356>
extern __imp_mtxoci_ordinal357:PANYARGS
mtxoci_ordinal357 TEXTEQU <__imp_mtxoci_ordinal357>
extern __imp_mtxoci_ordinal358:PANYARGS
mtxoci_ordinal358 TEXTEQU <__imp_mtxoci_ordinal358>
extern __imp_mtxoci_ordinal359:PANYARGS
mtxoci_ordinal359 TEXTEQU <__imp_mtxoci_ordinal359>
extern __imp_mtxoci_ordinal360:PANYARGS
mtxoci_ordinal360 TEXTEQU <__imp_mtxoci_ordinal360>
extern __imp_mtxoci_ordinal361:PANYARGS
mtxoci_ordinal361 TEXTEQU <__imp_mtxoci_ordinal361>
extern __imp_mtxoci_ordinal362:PANYARGS
mtxoci_ordinal362 TEXTEQU <__imp_mtxoci_ordinal362>
extern __imp_mtxoci_ordinal363:PANYARGS
mtxoci_ordinal363 TEXTEQU <__imp_mtxoci_ordinal363>
extern __imp_mtxoci_ordinal364:PANYARGS
mtxoci_ordinal364 TEXTEQU <__imp_mtxoci_ordinal364>
extern __imp_mtxoci_ordinal365:PANYARGS
mtxoci_ordinal365 TEXTEQU <__imp_mtxoci_ordinal365>
extern __imp_mtxoci_ordinal366:PANYARGS
mtxoci_ordinal366 TEXTEQU <__imp_mtxoci_ordinal366>
extern __imp_mtxoci_ordinal367:PANYARGS
mtxoci_ordinal367 TEXTEQU <__imp_mtxoci_ordinal367>
extern __imp_mtxoci_ordinal368:PANYARGS
mtxoci_ordinal368 TEXTEQU <__imp_mtxoci_ordinal368>
extern __imp_mtxoci_ordinal369:PANYARGS
mtxoci_ordinal369 TEXTEQU <__imp_mtxoci_ordinal369>
extern __imp_mtxoci_ordinal370:PANYARGS
mtxoci_ordinal370 TEXTEQU <__imp_mtxoci_ordinal370>
extern __imp_mtxoci_ordinal371:PANYARGS
mtxoci_ordinal371 TEXTEQU <__imp_mtxoci_ordinal371>
extern __imp_mtxoci_ordinal372:PANYARGS
mtxoci_ordinal372 TEXTEQU <__imp_mtxoci_ordinal372>
extern __imp_mtxoci_ordinal373:PANYARGS
mtxoci_ordinal373 TEXTEQU <__imp_mtxoci_ordinal373>
extern __imp_mtxoci_ordinal374:PANYARGS
mtxoci_ordinal374 TEXTEQU <__imp_mtxoci_ordinal374>
extern __imp_mtxoci_ordinal375:PANYARGS
mtxoci_ordinal375 TEXTEQU <__imp_mtxoci_ordinal375>
extern __imp_mtxoci_ordinal376:PANYARGS
mtxoci_ordinal376 TEXTEQU <__imp_mtxoci_ordinal376>
extern __imp_mtxoci_ordinal377:PANYARGS
mtxoci_ordinal377 TEXTEQU <__imp_mtxoci_ordinal377>
extern __imp_mtxoci_ordinal378:PANYARGS
mtxoci_ordinal378 TEXTEQU <__imp_mtxoci_ordinal378>
extern __imp_mtxoci_ordinal379:PANYARGS
mtxoci_ordinal379 TEXTEQU <__imp_mtxoci_ordinal379>
extern __imp_mtxoci_ordinal380:PANYARGS
mtxoci_ordinal380 TEXTEQU <__imp_mtxoci_ordinal380>
extern __imp_mtxoci_ordinal381:PANYARGS
mtxoci_ordinal381 TEXTEQU <__imp_mtxoci_ordinal381>
extern __imp_mtxoci_ordinal382:PANYARGS
mtxoci_ordinal382 TEXTEQU <__imp_mtxoci_ordinal382>
extern __imp_mtxoci_ordinal383:PANYARGS
mtxoci_ordinal383 TEXTEQU <__imp_mtxoci_ordinal383>
extern __imp_mtxoci_ordinal384:PANYARGS
mtxoci_ordinal384 TEXTEQU <__imp_mtxoci_ordinal384>
extern __imp_mtxoci_ordinal385:PANYARGS
mtxoci_ordinal385 TEXTEQU <__imp_mtxoci_ordinal385>
extern __imp_mtxoci_ordinal386:PANYARGS
mtxoci_ordinal386 TEXTEQU <__imp_mtxoci_ordinal386>
extern __imp_mtxoci_ordinal387:PANYARGS
mtxoci_ordinal387 TEXTEQU <__imp_mtxoci_ordinal387>
extern __imp_mtxoci_ordinal388:PANYARGS
mtxoci_ordinal388 TEXTEQU <__imp_mtxoci_ordinal388>
extern __imp_mtxoci_ordinal389:PANYARGS
mtxoci_ordinal389 TEXTEQU <__imp_mtxoci_ordinal389>
extern __imp_mtxoci_ordinal390:PANYARGS
mtxoci_ordinal390 TEXTEQU <__imp_mtxoci_ordinal390>
extern __imp_mtxoci_ordinal391:PANYARGS
mtxoci_ordinal391 TEXTEQU <__imp_mtxoci_ordinal391>
extern __imp_mtxoci_ordinal392:PANYARGS
mtxoci_ordinal392 TEXTEQU <__imp_mtxoci_ordinal392>
extern __imp_mtxoci_ordinal393:PANYARGS
mtxoci_ordinal393 TEXTEQU <__imp_mtxoci_ordinal393>
extern __imp_mtxoci_ordinal394:PANYARGS
mtxoci_ordinal394 TEXTEQU <__imp_mtxoci_ordinal394>
extern __imp_mtxoci_ordinal395:PANYARGS
mtxoci_ordinal395 TEXTEQU <__imp_mtxoci_ordinal395>
extern __imp_mtxoci_ordinal396:PANYARGS
mtxoci_ordinal396 TEXTEQU <__imp_mtxoci_ordinal396>
extern __imp_mtxoci_ordinal397:PANYARGS
mtxoci_ordinal397 TEXTEQU <__imp_mtxoci_ordinal397>
extern __imp_mtxoci_ordinal398:PANYARGS
mtxoci_ordinal398 TEXTEQU <__imp_mtxoci_ordinal398>
extern __imp_mtxoci_ordinal399:PANYARGS
mtxoci_ordinal399 TEXTEQU <__imp_mtxoci_ordinal399>
extern __imp_mtxoci_ordinal400:PANYARGS
mtxoci_ordinal400 TEXTEQU <__imp_mtxoci_ordinal400>
extern __imp_mtxoci_ordinal401:PANYARGS
mtxoci_ordinal401 TEXTEQU <__imp_mtxoci_ordinal401>
extern __imp_mtxoci_ordinal402:PANYARGS
mtxoci_ordinal402 TEXTEQU <__imp_mtxoci_ordinal402>
extern __imp_mtxoci_ordinal403:PANYARGS
mtxoci_ordinal403 TEXTEQU <__imp_mtxoci_ordinal403>
extern __imp_mtxoci_ordinal404:PANYARGS
mtxoci_ordinal404 TEXTEQU <__imp_mtxoci_ordinal404>
extern __imp_mtxoci_ordinal405:PANYARGS
mtxoci_ordinal405 TEXTEQU <__imp_mtxoci_ordinal405>
extern __imp_mtxoci_ordinal406:PANYARGS
mtxoci_ordinal406 TEXTEQU <__imp_mtxoci_ordinal406>
extern __imp_mtxoci_ordinal407:PANYARGS
mtxoci_ordinal407 TEXTEQU <__imp_mtxoci_ordinal407>
extern __imp_mtxoci_ordinal408:PANYARGS
mtxoci_ordinal408 TEXTEQU <__imp_mtxoci_ordinal408>
extern __imp_mtxoci_ordinal409:PANYARGS
mtxoci_ordinal409 TEXTEQU <__imp_mtxoci_ordinal409>
extern __imp_mtxoci_ordinal410:PANYARGS
mtxoci_ordinal410 TEXTEQU <__imp_mtxoci_ordinal410>
extern __imp_mtxoci_ordinal411:PANYARGS
mtxoci_ordinal411 TEXTEQU <__imp_mtxoci_ordinal411>
extern __imp_mtxoci_ordinal412:PANYARGS
mtxoci_ordinal412 TEXTEQU <__imp_mtxoci_ordinal412>
extern __imp_mtxoci_ordinal413:PANYARGS
mtxoci_ordinal413 TEXTEQU <__imp_mtxoci_ordinal413>
extern __imp_mtxoci_ordinal414:PANYARGS
mtxoci_ordinal414 TEXTEQU <__imp_mtxoci_ordinal414>
extern __imp_mtxoci_ordinal415:PANYARGS
mtxoci_ordinal415 TEXTEQU <__imp_mtxoci_ordinal415>
extern __imp_mtxoci_ordinal416:PANYARGS
mtxoci_ordinal416 TEXTEQU <__imp_mtxoci_ordinal416>
extern __imp_mtxoci_ordinal417:PANYARGS
mtxoci_ordinal417 TEXTEQU <__imp_mtxoci_ordinal417>
extern __imp_mtxoci_ordinal418:PANYARGS
mtxoci_ordinal418 TEXTEQU <__imp_mtxoci_ordinal418>
extern __imp_mtxoci_ordinal419:PANYARGS
mtxoci_ordinal419 TEXTEQU <__imp_mtxoci_ordinal419>
extern __imp_mtxoci_ordinal420:PANYARGS
mtxoci_ordinal420 TEXTEQU <__imp_mtxoci_ordinal420>
extern __imp_mtxoci_ordinal421:PANYARGS
mtxoci_ordinal421 TEXTEQU <__imp_mtxoci_ordinal421>
extern __imp_mtxoci_ordinal422:PANYARGS
mtxoci_ordinal422 TEXTEQU <__imp_mtxoci_ordinal422>
extern __imp_mtxoci_ordinal423:PANYARGS
mtxoci_ordinal423 TEXTEQU <__imp_mtxoci_ordinal423>
extern __imp_mtxoci_ordinal424:PANYARGS
mtxoci_ordinal424 TEXTEQU <__imp_mtxoci_ordinal424>
extern __imp_mtxoci_ordinal425:PANYARGS
mtxoci_ordinal425 TEXTEQU <__imp_mtxoci_ordinal425>
extern __imp_mtxoci_ordinal426:PANYARGS
mtxoci_ordinal426 TEXTEQU <__imp_mtxoci_ordinal426>
extern __imp_mtxoci_ordinal427:PANYARGS
mtxoci_ordinal427 TEXTEQU <__imp_mtxoci_ordinal427>
extern __imp_mtxoci_ordinal428:PANYARGS
mtxoci_ordinal428 TEXTEQU <__imp_mtxoci_ordinal428>
extern __imp_mtxoci_ordinal429:PANYARGS
mtxoci_ordinal429 TEXTEQU <__imp_mtxoci_ordinal429>
extern __imp_mtxoci_ordinal430:PANYARGS
mtxoci_ordinal430 TEXTEQU <__imp_mtxoci_ordinal430>
extern __imp_mtxoci_ordinal431:PANYARGS
mtxoci_ordinal431 TEXTEQU <__imp_mtxoci_ordinal431>
extern __imp_mtxoci_ordinal432:PANYARGS
mtxoci_ordinal432 TEXTEQU <__imp_mtxoci_ordinal432>
extern __imp_mtxoci_ordinal433:PANYARGS
mtxoci_ordinal433 TEXTEQU <__imp_mtxoci_ordinal433>
extern __imp_mtxoci_ordinal434:PANYARGS
mtxoci_ordinal434 TEXTEQU <__imp_mtxoci_ordinal434>
extern __imp_mtxoci_ordinal435:PANYARGS
mtxoci_ordinal435 TEXTEQU <__imp_mtxoci_ordinal435>
extern __imp_mtxoci_ordinal436:PANYARGS
mtxoci_ordinal436 TEXTEQU <__imp_mtxoci_ordinal436>
extern __imp_mtxoci_ordinal437:PANYARGS
mtxoci_ordinal437 TEXTEQU <__imp_mtxoci_ordinal437>
extern __imp_mtxoci_ordinal438:PANYARGS
mtxoci_ordinal438 TEXTEQU <__imp_mtxoci_ordinal438>
extern __imp_mtxoci_ordinal439:PANYARGS
mtxoci_ordinal439 TEXTEQU <__imp_mtxoci_ordinal439>
extern __imp_mtxoci_ordinal440:PANYARGS
mtxoci_ordinal440 TEXTEQU <__imp_mtxoci_ordinal440>
extern __imp_mtxoci_ordinal441:PANYARGS
mtxoci_ordinal441 TEXTEQU <__imp_mtxoci_ordinal441>
extern __imp_mtxoci_ordinal442:PANYARGS
mtxoci_ordinal442 TEXTEQU <__imp_mtxoci_ordinal442>
extern __imp_mtxoci_ordinal443:PANYARGS
mtxoci_ordinal443 TEXTEQU <__imp_mtxoci_ordinal443>
extern __imp_mtxoci_ordinal444:PANYARGS
mtxoci_ordinal444 TEXTEQU <__imp_mtxoci_ordinal444>
extern __imp_mtxoci_ordinal445:PANYARGS
mtxoci_ordinal445 TEXTEQU <__imp_mtxoci_ordinal445>
extern __imp_mtxoci_ordinal446:PANYARGS
mtxoci_ordinal446 TEXTEQU <__imp_mtxoci_ordinal446>
extern __imp_mtxoci_ordinal447:PANYARGS
mtxoci_ordinal447 TEXTEQU <__imp_mtxoci_ordinal447>
extern __imp_mtxoci_ordinal448:PANYARGS
mtxoci_ordinal448 TEXTEQU <__imp_mtxoci_ordinal448>
extern __imp_mtxoci_ordinal449:PANYARGS
mtxoci_ordinal449 TEXTEQU <__imp_mtxoci_ordinal449>
extern __imp_mtxoci_ordinal450:PANYARGS
mtxoci_ordinal450 TEXTEQU <__imp_mtxoci_ordinal450>
extern __imp_mtxoci_ordinal451:PANYARGS
mtxoci_ordinal451 TEXTEQU <__imp_mtxoci_ordinal451>
extern __imp_mtxoci_ordinal452:PANYARGS
mtxoci_ordinal452 TEXTEQU <__imp_mtxoci_ordinal452>
extern __imp_mtxoci_ordinal453:PANYARGS
mtxoci_ordinal453 TEXTEQU <__imp_mtxoci_ordinal453>
extern __imp_mtxoci_ordinal454:PANYARGS
mtxoci_ordinal454 TEXTEQU <__imp_mtxoci_ordinal454>
extern __imp_mtxoci_ordinal455:PANYARGS
mtxoci_ordinal455 TEXTEQU <__imp_mtxoci_ordinal455>
extern __imp_mtxoci_ordinal456:PANYARGS
mtxoci_ordinal456 TEXTEQU <__imp_mtxoci_ordinal456>
extern __imp_mtxoci_ordinal457:PANYARGS
mtxoci_ordinal457 TEXTEQU <__imp_mtxoci_ordinal457>
extern __imp_mtxoci_ordinal458:PANYARGS
mtxoci_ordinal458 TEXTEQU <__imp_mtxoci_ordinal458>
extern __imp_mtxoci_ordinal459:PANYARGS
mtxoci_ordinal459 TEXTEQU <__imp_mtxoci_ordinal459>
extern __imp_mtxoci_ordinal460:PANYARGS
mtxoci_ordinal460 TEXTEQU <__imp_mtxoci_ordinal460>
extern __imp_mtxoci_ordinal461:PANYARGS
mtxoci_ordinal461 TEXTEQU <__imp_mtxoci_ordinal461>
extern __imp_mtxoci_ordinal462:PANYARGS
mtxoci_ordinal462 TEXTEQU <__imp_mtxoci_ordinal462>
extern __imp_mtxoci_ordinal463:PANYARGS
mtxoci_ordinal463 TEXTEQU <__imp_mtxoci_ordinal463>
extern __imp_mtxoci_ordinal464:PANYARGS
mtxoci_ordinal464 TEXTEQU <__imp_mtxoci_ordinal464>
extern __imp_mtxoci_ordinal465:PANYARGS
mtxoci_ordinal465 TEXTEQU <__imp_mtxoci_ordinal465>
extern __imp_mtxoci_ordinal466:PANYARGS
mtxoci_ordinal466 TEXTEQU <__imp_mtxoci_ordinal466>
extern __imp_mtxoci_ordinal467:PANYARGS
mtxoci_ordinal467 TEXTEQU <__imp_mtxoci_ordinal467>
extern __imp_mtxoci_ordinal468:PANYARGS
mtxoci_ordinal468 TEXTEQU <__imp_mtxoci_ordinal468>
extern __imp_mtxoci_ordinal469:PANYARGS
mtxoci_ordinal469 TEXTEQU <__imp_mtxoci_ordinal469>
extern __imp_mtxoci_ordinal470:PANYARGS
mtxoci_ordinal470 TEXTEQU <__imp_mtxoci_ordinal470>
extern __imp_mtxoci_ordinal471:PANYARGS
mtxoci_ordinal471 TEXTEQU <__imp_mtxoci_ordinal471>
extern __imp_mtxoci_ordinal472:PANYARGS
mtxoci_ordinal472 TEXTEQU <__imp_mtxoci_ordinal472>
extern __imp_mtxoci_ordinal473:PANYARGS
mtxoci_ordinal473 TEXTEQU <__imp_mtxoci_ordinal473>
extern __imp_mtxoci_ordinal474:PANYARGS
mtxoci_ordinal474 TEXTEQU <__imp_mtxoci_ordinal474>
extern __imp_mtxoci_ordinal475:PANYARGS
mtxoci_ordinal475 TEXTEQU <__imp_mtxoci_ordinal475>
extern __imp_mtxoci_ordinal476:PANYARGS
mtxoci_ordinal476 TEXTEQU <__imp_mtxoci_ordinal476>
extern __imp_mtxoci_ordinal477:PANYARGS
mtxoci_ordinal477 TEXTEQU <__imp_mtxoci_ordinal477>
extern __imp_mtxoci_ordinal478:PANYARGS
mtxoci_ordinal478 TEXTEQU <__imp_mtxoci_ordinal478>
extern __imp_mtxoci_ordinal479:PANYARGS
mtxoci_ordinal479 TEXTEQU <__imp_mtxoci_ordinal479>
extern __imp_mtxoci_ordinal480:PANYARGS
mtxoci_ordinal480 TEXTEQU <__imp_mtxoci_ordinal480>
extern __imp_mtxoci_ordinal481:PANYARGS
mtxoci_ordinal481 TEXTEQU <__imp_mtxoci_ordinal481>
extern __imp_mtxoci_ordinal482:PANYARGS
mtxoci_ordinal482 TEXTEQU <__imp_mtxoci_ordinal482>
extern __imp_mtxoci_ordinal483:PANYARGS
mtxoci_ordinal483 TEXTEQU <__imp_mtxoci_ordinal483>
extern __imp_mtxoci_ordinal484:PANYARGS
mtxoci_ordinal484 TEXTEQU <__imp_mtxoci_ordinal484>
extern __imp_mtxoci_ordinal485:PANYARGS
mtxoci_ordinal485 TEXTEQU <__imp_mtxoci_ordinal485>
extern __imp_mtxoci_ordinal486:PANYARGS
mtxoci_ordinal486 TEXTEQU <__imp_mtxoci_ordinal486>
extern __imp_mtxoci_ordinal487:PANYARGS
mtxoci_ordinal487 TEXTEQU <__imp_mtxoci_ordinal487>
extern __imp_mtxoci_ordinal488:PANYARGS
mtxoci_ordinal488 TEXTEQU <__imp_mtxoci_ordinal488>
extern __imp_mtxoci_ordinal489:PANYARGS
mtxoci_ordinal489 TEXTEQU <__imp_mtxoci_ordinal489>
extern __imp_mtxoci_ordinal490:PANYARGS
mtxoci_ordinal490 TEXTEQU <__imp_mtxoci_ordinal490>
extern __imp_mtxoci_ordinal491:PANYARGS
mtxoci_ordinal491 TEXTEQU <__imp_mtxoci_ordinal491>
extern __imp_mtxoci_ordinal492:PANYARGS
mtxoci_ordinal492 TEXTEQU <__imp_mtxoci_ordinal492>
extern __imp_mtxoci_ordinal493:PANYARGS
mtxoci_ordinal493 TEXTEQU <__imp_mtxoci_ordinal493>
extern __imp_mtxoci_ordinal494:PANYARGS
mtxoci_ordinal494 TEXTEQU <__imp_mtxoci_ordinal494>
extern __imp_mtxoci_ordinal495:PANYARGS
mtxoci_ordinal495 TEXTEQU <__imp_mtxoci_ordinal495>
extern __imp_mtxoci_ordinal496:PANYARGS
mtxoci_ordinal496 TEXTEQU <__imp_mtxoci_ordinal496>
extern __imp_mtxoci_ordinal497:PANYARGS
mtxoci_ordinal497 TEXTEQU <__imp_mtxoci_ordinal497>
extern __imp_mtxoci_ordinal498:PANYARGS
mtxoci_ordinal498 TEXTEQU <__imp_mtxoci_ordinal498>
extern __imp_mtxoci_ordinal499:PANYARGS
mtxoci_ordinal499 TEXTEQU <__imp_mtxoci_ordinal499>
extern __imp_mtxoci_ordinal500:PANYARGS
mtxoci_ordinal500 TEXTEQU <__imp_mtxoci_ordinal500>
extern __imp_mtxoci_ordinal501:PANYARGS
mtxoci_ordinal501 TEXTEQU <__imp_mtxoci_ordinal501>
extern __imp_mtxoci_ordinal502:PANYARGS
mtxoci_ordinal502 TEXTEQU <__imp_mtxoci_ordinal502>
extern __imp_mtxoci_ordinal503:PANYARGS
mtxoci_ordinal503 TEXTEQU <__imp_mtxoci_ordinal503>
extern __imp_mtxoci_ordinal504:PANYARGS
mtxoci_ordinal504 TEXTEQU <__imp_mtxoci_ordinal504>
extern __imp_mtxoci_ordinal505:PANYARGS
mtxoci_ordinal505 TEXTEQU <__imp_mtxoci_ordinal505>
extern __imp_mtxoci_ordinal506:PANYARGS
mtxoci_ordinal506 TEXTEQU <__imp_mtxoci_ordinal506>
extern __imp_mtxoci_ordinal507:PANYARGS
mtxoci_ordinal507 TEXTEQU <__imp_mtxoci_ordinal507>
extern __imp_mtxoci_ordinal508:PANYARGS
mtxoci_ordinal508 TEXTEQU <__imp_mtxoci_ordinal508>
extern __imp_mtxoci_ordinal509:PANYARGS
mtxoci_ordinal509 TEXTEQU <__imp_mtxoci_ordinal509>
extern __imp_mtxoci_ordinal510:PANYARGS
mtxoci_ordinal510 TEXTEQU <__imp_mtxoci_ordinal510>
extern __imp_mtxoci_ordinal511:PANYARGS
mtxoci_ordinal511 TEXTEQU <__imp_mtxoci_ordinal511>
extern __imp_mtxoci_ordinal512:PANYARGS
mtxoci_ordinal512 TEXTEQU <__imp_mtxoci_ordinal512>
extern __imp_mtxoci_ordinal513:PANYARGS
mtxoci_ordinal513 TEXTEQU <__imp_mtxoci_ordinal513>
extern __imp_mtxoci_ordinal514:PANYARGS
mtxoci_ordinal514 TEXTEQU <__imp_mtxoci_ordinal514>
extern __imp_mtxoci_ordinal515:PANYARGS
mtxoci_ordinal515 TEXTEQU <__imp_mtxoci_ordinal515>
extern __imp_mtxoci_ordinal516:PANYARGS
mtxoci_ordinal516 TEXTEQU <__imp_mtxoci_ordinal516>
extern __imp_mtxoci_ordinal517:PANYARGS
mtxoci_ordinal517 TEXTEQU <__imp_mtxoci_ordinal517>
extern __imp_mtxoci_ordinal518:PANYARGS
mtxoci_ordinal518 TEXTEQU <__imp_mtxoci_ordinal518>
extern __imp_mtxoci_ordinal519:PANYARGS
mtxoci_ordinal519 TEXTEQU <__imp_mtxoci_ordinal519>
extern __imp_mtxoci_ordinal520:PANYARGS
mtxoci_ordinal520 TEXTEQU <__imp_mtxoci_ordinal520>
extern __imp_mtxoci_ordinal521:PANYARGS
mtxoci_ordinal521 TEXTEQU <__imp_mtxoci_ordinal521>
extern __imp_mtxoci_ordinal522:PANYARGS
mtxoci_ordinal522 TEXTEQU <__imp_mtxoci_ordinal522>
extern __imp_mtxoci_ordinal523:PANYARGS
mtxoci_ordinal523 TEXTEQU <__imp_mtxoci_ordinal523>
extern __imp_mtxoci_ordinal524:PANYARGS
mtxoci_ordinal524 TEXTEQU <__imp_mtxoci_ordinal524>
extern __imp_mtxoci_ordinal525:PANYARGS
mtxoci_ordinal525 TEXTEQU <__imp_mtxoci_ordinal525>
extern __imp_mtxoci_ordinal526:PANYARGS
mtxoci_ordinal526 TEXTEQU <__imp_mtxoci_ordinal526>
extern __imp_mtxoci_ordinal527:PANYARGS
mtxoci_ordinal527 TEXTEQU <__imp_mtxoci_ordinal527>
extern __imp_mtxoci_ordinal528:PANYARGS
mtxoci_ordinal528 TEXTEQU <__imp_mtxoci_ordinal528>
extern __imp_mtxoci_ordinal529:PANYARGS
mtxoci_ordinal529 TEXTEQU <__imp_mtxoci_ordinal529>
extern __imp_mtxoci_ordinal530:PANYARGS
mtxoci_ordinal530 TEXTEQU <__imp_mtxoci_ordinal530>
extern __imp_mtxoci_ordinal531:PANYARGS
mtxoci_ordinal531 TEXTEQU <__imp_mtxoci_ordinal531>
extern __imp_mtxoci_ordinal532:PANYARGS
mtxoci_ordinal532 TEXTEQU <__imp_mtxoci_ordinal532>
extern __imp_mtxoci_ordinal533:PANYARGS
mtxoci_ordinal533 TEXTEQU <__imp_mtxoci_ordinal533>
extern __imp_mtxoci_ordinal534:PANYARGS
mtxoci_ordinal534 TEXTEQU <__imp_mtxoci_ordinal534>
extern __imp_mtxoci_ordinal535:PANYARGS
mtxoci_ordinal535 TEXTEQU <__imp_mtxoci_ordinal535>
extern __imp_mtxoci_ordinal536:PANYARGS
mtxoci_ordinal536 TEXTEQU <__imp_mtxoci_ordinal536>
extern __imp_mtxoci_ordinal537:PANYARGS
mtxoci_ordinal537 TEXTEQU <__imp_mtxoci_ordinal537>
extern __imp_mtxoci_ordinal538:PANYARGS
mtxoci_ordinal538 TEXTEQU <__imp_mtxoci_ordinal538>
extern __imp_mtxoci_ordinal539:PANYARGS
mtxoci_ordinal539 TEXTEQU <__imp_mtxoci_ordinal539>
extern __imp_mtxoci_ordinal540:PANYARGS
mtxoci_ordinal540 TEXTEQU <__imp_mtxoci_ordinal540>
extern __imp_mtxoci_ordinal541:PANYARGS
mtxoci_ordinal541 TEXTEQU <__imp_mtxoci_ordinal541>
extern __imp_mtxoci_ordinal542:PANYARGS
mtxoci_ordinal542 TEXTEQU <__imp_mtxoci_ordinal542>
extern __imp_mtxoci_ordinal543:PANYARGS
mtxoci_ordinal543 TEXTEQU <__imp_mtxoci_ordinal543>
extern __imp_mtxoci_ordinal544:PANYARGS
mtxoci_ordinal544 TEXTEQU <__imp_mtxoci_ordinal544>
extern __imp_mtxoci_ordinal545:PANYARGS
mtxoci_ordinal545 TEXTEQU <__imp_mtxoci_ordinal545>
extern __imp_mtxoci_ordinal546:PANYARGS
mtxoci_ordinal546 TEXTEQU <__imp_mtxoci_ordinal546>
extern __imp_mtxoci_ordinal547:PANYARGS
mtxoci_ordinal547 TEXTEQU <__imp_mtxoci_ordinal547>
extern __imp_mtxoci_ordinal548:PANYARGS
mtxoci_ordinal548 TEXTEQU <__imp_mtxoci_ordinal548>
extern __imp_mtxoci_ordinal549:PANYARGS
mtxoci_ordinal549 TEXTEQU <__imp_mtxoci_ordinal549>
extern __imp_mtxoci_ordinal550:PANYARGS
mtxoci_ordinal550 TEXTEQU <__imp_mtxoci_ordinal550>
extern __imp_mtxoci_ordinal551:PANYARGS
mtxoci_ordinal551 TEXTEQU <__imp_mtxoci_ordinal551>
extern __imp_mtxoci_ordinal552:PANYARGS
mtxoci_ordinal552 TEXTEQU <__imp_mtxoci_ordinal552>
extern __imp_mtxoci_ordinal553:PANYARGS
mtxoci_ordinal553 TEXTEQU <__imp_mtxoci_ordinal553>
extern __imp_mtxoci_ordinal554:PANYARGS
mtxoci_ordinal554 TEXTEQU <__imp_mtxoci_ordinal554>
extern __imp_mtxoci_ordinal555:PANYARGS
mtxoci_ordinal555 TEXTEQU <__imp_mtxoci_ordinal555>
extern __imp_mtxoci_ordinal556:PANYARGS
mtxoci_ordinal556 TEXTEQU <__imp_mtxoci_ordinal556>
extern __imp_mtxoci_ordinal557:PANYARGS
mtxoci_ordinal557 TEXTEQU <__imp_mtxoci_ordinal557>
extern __imp_mtxoci_ordinal558:PANYARGS
mtxoci_ordinal558 TEXTEQU <__imp_mtxoci_ordinal558>
extern __imp_mtxoci_ordinal559:PANYARGS
mtxoci_ordinal559 TEXTEQU <__imp_mtxoci_ordinal559>
extern __imp_mtxoci_ordinal560:PANYARGS
mtxoci_ordinal560 TEXTEQU <__imp_mtxoci_ordinal560>
extern __imp_mtxoci_ordinal561:PANYARGS
mtxoci_ordinal561 TEXTEQU <__imp_mtxoci_ordinal561>
extern __imp_mtxoci_ordinal562:PANYARGS
mtxoci_ordinal562 TEXTEQU <__imp_mtxoci_ordinal562>
extern __imp_mtxoci_ordinal563:PANYARGS
mtxoci_ordinal563 TEXTEQU <__imp_mtxoci_ordinal563>
extern __imp_mtxoci_ordinal564:PANYARGS
mtxoci_ordinal564 TEXTEQU <__imp_mtxoci_ordinal564>
extern __imp_mtxoci_ordinal565:PANYARGS
mtxoci_ordinal565 TEXTEQU <__imp_mtxoci_ordinal565>
extern __imp_mtxoci_ordinal566:PANYARGS
mtxoci_ordinal566 TEXTEQU <__imp_mtxoci_ordinal566>
extern __imp_mtxoci_ordinal567:PANYARGS
mtxoci_ordinal567 TEXTEQU <__imp_mtxoci_ordinal567>
extern __imp_mtxoci_ordinal568:PANYARGS
mtxoci_ordinal568 TEXTEQU <__imp_mtxoci_ordinal568>
extern __imp_mtxoci_ordinal569:PANYARGS
mtxoci_ordinal569 TEXTEQU <__imp_mtxoci_ordinal569>
extern __imp_mtxoci_ordinal570:PANYARGS
mtxoci_ordinal570 TEXTEQU <__imp_mtxoci_ordinal570>
extern __imp_mtxoci_ordinal571:PANYARGS
mtxoci_ordinal571 TEXTEQU <__imp_mtxoci_ordinal571>
extern __imp_mtxoci_ordinal572:PANYARGS
mtxoci_ordinal572 TEXTEQU <__imp_mtxoci_ordinal572>
extern __imp_mtxoci_ordinal573:PANYARGS
mtxoci_ordinal573 TEXTEQU <__imp_mtxoci_ordinal573>
extern __imp_mtxoci_ordinal574:PANYARGS
mtxoci_ordinal574 TEXTEQU <__imp_mtxoci_ordinal574>
extern __imp_mtxoci_ordinal575:PANYARGS
mtxoci_ordinal575 TEXTEQU <__imp_mtxoci_ordinal575>
extern __imp_mtxoci_ordinal576:PANYARGS
mtxoci_ordinal576 TEXTEQU <__imp_mtxoci_ordinal576>
extern __imp_mtxoci_ordinal577:PANYARGS
mtxoci_ordinal577 TEXTEQU <__imp_mtxoci_ordinal577>
extern __imp_mtxoci_ordinal578:PANYARGS
mtxoci_ordinal578 TEXTEQU <__imp_mtxoci_ordinal578>
extern __imp_mtxoci_ordinal579:PANYARGS
mtxoci_ordinal579 TEXTEQU <__imp_mtxoci_ordinal579>
extern __imp_mtxoci_ordinal580:PANYARGS
mtxoci_ordinal580 TEXTEQU <__imp_mtxoci_ordinal580>
extern __imp_mtxoci_ordinal581:PANYARGS
mtxoci_ordinal581 TEXTEQU <__imp_mtxoci_ordinal581>
extern __imp_mtxoci_ordinal582:PANYARGS
mtxoci_ordinal582 TEXTEQU <__imp_mtxoci_ordinal582>
extern __imp_mtxoci_ordinal583:PANYARGS
mtxoci_ordinal583 TEXTEQU <__imp_mtxoci_ordinal583>
extern __imp_mtxoci_ordinal584:PANYARGS
mtxoci_ordinal584 TEXTEQU <__imp_mtxoci_ordinal584>
extern __imp_mtxoci_ordinal585:PANYARGS
mtxoci_ordinal585 TEXTEQU <__imp_mtxoci_ordinal585>
extern __imp_mtxoci_ordinal586:PANYARGS
mtxoci_ordinal586 TEXTEQU <__imp_mtxoci_ordinal586>
extern __imp_mtxoci_ordinal587:PANYARGS
mtxoci_ordinal587 TEXTEQU <__imp_mtxoci_ordinal587>
extern __imp_mtxoci_ordinal588:PANYARGS
mtxoci_ordinal588 TEXTEQU <__imp_mtxoci_ordinal588>
extern __imp_mtxoci_ordinal589:PANYARGS
mtxoci_ordinal589 TEXTEQU <__imp_mtxoci_ordinal589>
extern __imp_mtxoci_ordinal590:PANYARGS
mtxoci_ordinal590 TEXTEQU <__imp_mtxoci_ordinal590>
extern __imp_mtxoci_ordinal591:PANYARGS
mtxoci_ordinal591 TEXTEQU <__imp_mtxoci_ordinal591>
extern __imp_mtxoci_ordinal592:PANYARGS
mtxoci_ordinal592 TEXTEQU <__imp_mtxoci_ordinal592>
extern __imp_mtxoci_ordinal593:PANYARGS
mtxoci_ordinal593 TEXTEQU <__imp_mtxoci_ordinal593>
extern __imp_mtxoci_ordinal594:PANYARGS
mtxoci_ordinal594 TEXTEQU <__imp_mtxoci_ordinal594>
extern __imp_mtxoci_ordinal595:PANYARGS
mtxoci_ordinal595 TEXTEQU <__imp_mtxoci_ordinal595>
extern __imp_mtxoci_ordinal596:PANYARGS
mtxoci_ordinal596 TEXTEQU <__imp_mtxoci_ordinal596>
extern __imp_mtxoci_ordinal597:PANYARGS
mtxoci_ordinal597 TEXTEQU <__imp_mtxoci_ordinal597>
extern __imp_mtxoci_ordinal598:PANYARGS
mtxoci_ordinal598 TEXTEQU <__imp_mtxoci_ordinal598>
extern __imp_mtxoci_ordinal599:PANYARGS
mtxoci_ordinal599 TEXTEQU <__imp_mtxoci_ordinal599>
extern __imp_mtxoci_ordinal600:PANYARGS
mtxoci_ordinal600 TEXTEQU <__imp_mtxoci_ordinal600>
extern __imp_mtxoci_ordinal601:PANYARGS
mtxoci_ordinal601 TEXTEQU <__imp_mtxoci_ordinal601>
extern __imp_mtxoci_ordinal602:PANYARGS
mtxoci_ordinal602 TEXTEQU <__imp_mtxoci_ordinal602>
extern __imp_mtxoci_ordinal603:PANYARGS
mtxoci_ordinal603 TEXTEQU <__imp_mtxoci_ordinal603>
extern __imp_mtxoci_ordinal604:PANYARGS
mtxoci_ordinal604 TEXTEQU <__imp_mtxoci_ordinal604>
extern __imp_mtxoci_ordinal605:PANYARGS
mtxoci_ordinal605 TEXTEQU <__imp_mtxoci_ordinal605>
extern __imp_mtxoci_ordinal606:PANYARGS
mtxoci_ordinal606 TEXTEQU <__imp_mtxoci_ordinal606>
extern __imp_mtxoci_ordinal607:PANYARGS
mtxoci_ordinal607 TEXTEQU <__imp_mtxoci_ordinal607>
extern __imp_mtxoci_ordinal608:PANYARGS
mtxoci_ordinal608 TEXTEQU <__imp_mtxoci_ordinal608>
extern __imp_mtxoci_ordinal609:PANYARGS
mtxoci_ordinal609 TEXTEQU <__imp_mtxoci_ordinal609>
extern __imp_mtxoci_ordinal610:PANYARGS
mtxoci_ordinal610 TEXTEQU <__imp_mtxoci_ordinal610>
extern __imp_mtxoci_ordinal611:PANYARGS
mtxoci_ordinal611 TEXTEQU <__imp_mtxoci_ordinal611>
extern __imp_mtxoci_ordinal612:PANYARGS
mtxoci_ordinal612 TEXTEQU <__imp_mtxoci_ordinal612>
extern __imp_mtxoci_ordinal613:PANYARGS
mtxoci_ordinal613 TEXTEQU <__imp_mtxoci_ordinal613>
extern __imp_mtxoci_ordinal614:PANYARGS
mtxoci_ordinal614 TEXTEQU <__imp_mtxoci_ordinal614>
extern __imp_mtxoci_ordinal615:PANYARGS
mtxoci_ordinal615 TEXTEQU <__imp_mtxoci_ordinal615>
extern __imp_mtxoci_ordinal616:PANYARGS
mtxoci_ordinal616 TEXTEQU <__imp_mtxoci_ordinal616>
extern __imp_mtxoci_ordinal617:PANYARGS
mtxoci_ordinal617 TEXTEQU <__imp_mtxoci_ordinal617>
extern __imp_mtxoci_ordinal618:PANYARGS
mtxoci_ordinal618 TEXTEQU <__imp_mtxoci_ordinal618>
extern __imp_mtxoci_ordinal619:PANYARGS
mtxoci_ordinal619 TEXTEQU <__imp_mtxoci_ordinal619>
extern __imp_mtxoci_ordinal620:PANYARGS
mtxoci_ordinal620 TEXTEQU <__imp_mtxoci_ordinal620>
extern __imp_mtxoci_ordinal621:PANYARGS
mtxoci_ordinal621 TEXTEQU <__imp_mtxoci_ordinal621>
extern __imp_mtxoci_ordinal622:PANYARGS
mtxoci_ordinal622 TEXTEQU <__imp_mtxoci_ordinal622>
extern __imp_mtxoci_ordinal623:PANYARGS
mtxoci_ordinal623 TEXTEQU <__imp_mtxoci_ordinal623>
extern __imp_mtxoci_ordinal624:PANYARGS
mtxoci_ordinal624 TEXTEQU <__imp_mtxoci_ordinal624>
extern __imp_mtxoci_ordinal625:PANYARGS
mtxoci_ordinal625 TEXTEQU <__imp_mtxoci_ordinal625>
extern __imp_mtxoci_ordinal626:PANYARGS
mtxoci_ordinal626 TEXTEQU <__imp_mtxoci_ordinal626>
extern __imp_mtxoci_ordinal627:PANYARGS
mtxoci_ordinal627 TEXTEQU <__imp_mtxoci_ordinal627>
extern __imp_mtxoci_ordinal628:PANYARGS
mtxoci_ordinal628 TEXTEQU <__imp_mtxoci_ordinal628>
extern __imp_mtxoci_ordinal629:PANYARGS
mtxoci_ordinal629 TEXTEQU <__imp_mtxoci_ordinal629>
extern __imp_mtxoci_ordinal630:PANYARGS
mtxoci_ordinal630 TEXTEQU <__imp_mtxoci_ordinal630>
extern __imp_mtxoci_ordinal631:PANYARGS
mtxoci_ordinal631 TEXTEQU <__imp_mtxoci_ordinal631>
extern __imp_mtxoci_ordinal632:PANYARGS
mtxoci_ordinal632 TEXTEQU <__imp_mtxoci_ordinal632>
extern __imp_mtxoci_ordinal633:PANYARGS
mtxoci_ordinal633 TEXTEQU <__imp_mtxoci_ordinal633>
extern __imp_mtxoci_ordinal634:PANYARGS
mtxoci_ordinal634 TEXTEQU <__imp_mtxoci_ordinal634>
extern __imp_mtxoci_ordinal635:PANYARGS
mtxoci_ordinal635 TEXTEQU <__imp_mtxoci_ordinal635>
extern __imp_mtxoci_ordinal636:PANYARGS
mtxoci_ordinal636 TEXTEQU <__imp_mtxoci_ordinal636>
extern __imp_mtxoci_ordinal637:PANYARGS
mtxoci_ordinal637 TEXTEQU <__imp_mtxoci_ordinal637>
extern __imp_mtxoci_ordinal638:PANYARGS
mtxoci_ordinal638 TEXTEQU <__imp_mtxoci_ordinal638>
extern __imp_mtxoci_ordinal639:PANYARGS
mtxoci_ordinal639 TEXTEQU <__imp_mtxoci_ordinal639>
extern __imp_mtxoci_ordinal640:PANYARGS
mtxoci_ordinal640 TEXTEQU <__imp_mtxoci_ordinal640>
extern __imp_mtxoci_ordinal641:PANYARGS
mtxoci_ordinal641 TEXTEQU <__imp_mtxoci_ordinal641>
extern __imp_mtxoci_ordinal642:PANYARGS
mtxoci_ordinal642 TEXTEQU <__imp_mtxoci_ordinal642>
extern __imp_mtxoci_ordinal643:PANYARGS
mtxoci_ordinal643 TEXTEQU <__imp_mtxoci_ordinal643>
extern __imp_mtxoci_ordinal644:PANYARGS
mtxoci_ordinal644 TEXTEQU <__imp_mtxoci_ordinal644>
extern __imp_mtxoci_ordinal645:PANYARGS
mtxoci_ordinal645 TEXTEQU <__imp_mtxoci_ordinal645>
extern __imp_mtxoci_ordinal646:PANYARGS
mtxoci_ordinal646 TEXTEQU <__imp_mtxoci_ordinal646>
extern __imp_mtxoci_ordinal647:PANYARGS
mtxoci_ordinal647 TEXTEQU <__imp_mtxoci_ordinal647>
extern __imp_mtxoci_ordinal648:PANYARGS
mtxoci_ordinal648 TEXTEQU <__imp_mtxoci_ordinal648>
extern __imp_mtxoci_ordinal649:PANYARGS
mtxoci_ordinal649 TEXTEQU <__imp_mtxoci_ordinal649>
extern __imp_mtxoci_ordinal650:PANYARGS
mtxoci_ordinal650 TEXTEQU <__imp_mtxoci_ordinal650>
extern __imp_mtxoci_ordinal651:PANYARGS
mtxoci_ordinal651 TEXTEQU <__imp_mtxoci_ordinal651>
extern __imp_mtxoci_ordinal652:PANYARGS
mtxoci_ordinal652 TEXTEQU <__imp_mtxoci_ordinal652>
extern __imp_mtxoci_ordinal653:PANYARGS
mtxoci_ordinal653 TEXTEQU <__imp_mtxoci_ordinal653>
extern __imp_mtxoci_ordinal654:PANYARGS
mtxoci_ordinal654 TEXTEQU <__imp_mtxoci_ordinal654>
extern __imp_mtxoci_ordinal655:PANYARGS
mtxoci_ordinal655 TEXTEQU <__imp_mtxoci_ordinal655>
extern __imp_mtxoci_ordinal656:PANYARGS
mtxoci_ordinal656 TEXTEQU <__imp_mtxoci_ordinal656>
extern __imp_mtxoci_ordinal657:PANYARGS
mtxoci_ordinal657 TEXTEQU <__imp_mtxoci_ordinal657>
extern __imp_mtxoci_ordinal658:PANYARGS
mtxoci_ordinal658 TEXTEQU <__imp_mtxoci_ordinal658>
extern __imp_mtxoci_ordinal659:PANYARGS
mtxoci_ordinal659 TEXTEQU <__imp_mtxoci_ordinal659>
extern __imp_mtxoci_ordinal660:PANYARGS
mtxoci_ordinal660 TEXTEQU <__imp_mtxoci_ordinal660>
extern __imp_mtxoci_ordinal661:PANYARGS
mtxoci_ordinal661 TEXTEQU <__imp_mtxoci_ordinal661>
extern __imp_mtxoci_ordinal662:PANYARGS
mtxoci_ordinal662 TEXTEQU <__imp_mtxoci_ordinal662>
extern __imp_mtxoci_ordinal663:PANYARGS
mtxoci_ordinal663 TEXTEQU <__imp_mtxoci_ordinal663>
extern __imp_mtxoci_ordinal664:PANYARGS
mtxoci_ordinal664 TEXTEQU <__imp_mtxoci_ordinal664>
extern __imp_mtxoci_ordinal665:PANYARGS
mtxoci_ordinal665 TEXTEQU <__imp_mtxoci_ordinal665>
extern __imp_mtxoci_ordinal666:PANYARGS
mtxoci_ordinal666 TEXTEQU <__imp_mtxoci_ordinal666>
extern __imp_mtxoci_ordinal667:PANYARGS
mtxoci_ordinal667 TEXTEQU <__imp_mtxoci_ordinal667>
extern __imp_mtxoci_ordinal668:PANYARGS
mtxoci_ordinal668 TEXTEQU <__imp_mtxoci_ordinal668>
extern __imp_mtxoci_ordinal669:PANYARGS
mtxoci_ordinal669 TEXTEQU <__imp_mtxoci_ordinal669>
extern __imp_mtxoci_ordinal670:PANYARGS
mtxoci_ordinal670 TEXTEQU <__imp_mtxoci_ordinal670>
extern __imp_mtxoci_ordinal671:PANYARGS
mtxoci_ordinal671 TEXTEQU <__imp_mtxoci_ordinal671>
extern __imp_mtxoci_ordinal672:PANYARGS
mtxoci_ordinal672 TEXTEQU <__imp_mtxoci_ordinal672>
extern __imp_mtxoci_ordinal673:PANYARGS
mtxoci_ordinal673 TEXTEQU <__imp_mtxoci_ordinal673>
extern __imp_mtxoci_ordinal674:PANYARGS
mtxoci_ordinal674 TEXTEQU <__imp_mtxoci_ordinal674>
extern __imp_mtxoci_ordinal675:PANYARGS
mtxoci_ordinal675 TEXTEQU <__imp_mtxoci_ordinal675>
extern __imp_mtxoci_ordinal676:PANYARGS
mtxoci_ordinal676 TEXTEQU <__imp_mtxoci_ordinal676>
extern __imp_mtxoci_ordinal677:PANYARGS
mtxoci_ordinal677 TEXTEQU <__imp_mtxoci_ordinal677>
extern __imp_mtxoci_ordinal678:PANYARGS
mtxoci_ordinal678 TEXTEQU <__imp_mtxoci_ordinal678>
extern __imp_mtxoci_ordinal679:PANYARGS
mtxoci_ordinal679 TEXTEQU <__imp_mtxoci_ordinal679>
extern __imp_mtxoci_ordinal680:PANYARGS
mtxoci_ordinal680 TEXTEQU <__imp_mtxoci_ordinal680>
extern __imp_mtxoci_ordinal681:PANYARGS
mtxoci_ordinal681 TEXTEQU <__imp_mtxoci_ordinal681>
extern __imp_mtxoci_ordinal682:PANYARGS
mtxoci_ordinal682 TEXTEQU <__imp_mtxoci_ordinal682>
extern __imp_mtxoci_ordinal683:PANYARGS
mtxoci_ordinal683 TEXTEQU <__imp_mtxoci_ordinal683>
extern __imp_mtxoci_ordinal684:PANYARGS
mtxoci_ordinal684 TEXTEQU <__imp_mtxoci_ordinal684>
extern __imp_mtxoci_ordinal685:PANYARGS
mtxoci_ordinal685 TEXTEQU <__imp_mtxoci_ordinal685>
extern __imp_mtxoci_ordinal686:PANYARGS
mtxoci_ordinal686 TEXTEQU <__imp_mtxoci_ordinal686>
extern __imp_mtxoci_ordinal687:PANYARGS
mtxoci_ordinal687 TEXTEQU <__imp_mtxoci_ordinal687>
extern __imp_mtxoci_ordinal688:PANYARGS
mtxoci_ordinal688 TEXTEQU <__imp_mtxoci_ordinal688>
extern __imp_mtxoci_ordinal689:PANYARGS
mtxoci_ordinal689 TEXTEQU <__imp_mtxoci_ordinal689>
extern __imp_mtxoci_ordinal690:PANYARGS
mtxoci_ordinal690 TEXTEQU <__imp_mtxoci_ordinal690>
extern __imp_mtxoci_ordinal691:PANYARGS
mtxoci_ordinal691 TEXTEQU <__imp_mtxoci_ordinal691>
extern __imp_mtxoci_ordinal692:PANYARGS
mtxoci_ordinal692 TEXTEQU <__imp_mtxoci_ordinal692>
extern __imp_mtxoci_ordinal693:PANYARGS
mtxoci_ordinal693 TEXTEQU <__imp_mtxoci_ordinal693>
extern __imp_mtxoci_ordinal694:PANYARGS
mtxoci_ordinal694 TEXTEQU <__imp_mtxoci_ordinal694>
extern __imp_mtxoci_ordinal695:PANYARGS
mtxoci_ordinal695 TEXTEQU <__imp_mtxoci_ordinal695>
extern __imp_mtxoci_ordinal696:PANYARGS
mtxoci_ordinal696 TEXTEQU <__imp_mtxoci_ordinal696>
extern __imp_mtxoci_ordinal697:PANYARGS
mtxoci_ordinal697 TEXTEQU <__imp_mtxoci_ordinal697>
extern __imp_mtxoci_ordinal698:PANYARGS
mtxoci_ordinal698 TEXTEQU <__imp_mtxoci_ordinal698>
extern __imp_mtxoci_ordinal699:PANYARGS
mtxoci_ordinal699 TEXTEQU <__imp_mtxoci_ordinal699>
extern __imp_mtxoci_ordinal700:PANYARGS
mtxoci_ordinal700 TEXTEQU <__imp_mtxoci_ordinal700>
extern __imp_mtxoci_ordinal701:PANYARGS
mtxoci_ordinal701 TEXTEQU <__imp_mtxoci_ordinal701>
extern __imp_mtxoci_ordinal702:PANYARGS
mtxoci_ordinal702 TEXTEQU <__imp_mtxoci_ordinal702>
extern __imp_mtxoci_ordinal703:PANYARGS
mtxoci_ordinal703 TEXTEQU <__imp_mtxoci_ordinal703>
extern __imp_mtxoci_ordinal704:PANYARGS
mtxoci_ordinal704 TEXTEQU <__imp_mtxoci_ordinal704>
extern __imp_mtxoci_ordinal705:PANYARGS
mtxoci_ordinal705 TEXTEQU <__imp_mtxoci_ordinal705>
extern __imp_mtxoci_ordinal706:PANYARGS
mtxoci_ordinal706 TEXTEQU <__imp_mtxoci_ordinal706>
extern __imp_mtxoci_ordinal707:PANYARGS
mtxoci_ordinal707 TEXTEQU <__imp_mtxoci_ordinal707>
extern __imp_mtxoci_ordinal708:PANYARGS
mtxoci_ordinal708 TEXTEQU <__imp_mtxoci_ordinal708>
extern __imp_mtxoci_ordinal709:PANYARGS
mtxoci_ordinal709 TEXTEQU <__imp_mtxoci_ordinal709>
extern __imp_mtxoci_ordinal710:PANYARGS
mtxoci_ordinal710 TEXTEQU <__imp_mtxoci_ordinal710>
extern __imp_mtxoci_ordinal711:PANYARGS
mtxoci_ordinal711 TEXTEQU <__imp_mtxoci_ordinal711>
extern __imp_mtxoci_ordinal712:PANYARGS
mtxoci_ordinal712 TEXTEQU <__imp_mtxoci_ordinal712>
extern __imp_mtxoci_ordinal713:PANYARGS
mtxoci_ordinal713 TEXTEQU <__imp_mtxoci_ordinal713>
extern __imp_mtxoci_ordinal714:PANYARGS
mtxoci_ordinal714 TEXTEQU <__imp_mtxoci_ordinal714>
extern __imp_mtxoci_ordinal715:PANYARGS
mtxoci_ordinal715 TEXTEQU <__imp_mtxoci_ordinal715>
extern __imp_mtxoci_ordinal716:PANYARGS
mtxoci_ordinal716 TEXTEQU <__imp_mtxoci_ordinal716>
extern __imp_mtxoci_ordinal717:PANYARGS
mtxoci_ordinal717 TEXTEQU <__imp_mtxoci_ordinal717>
extern __imp_mtxoci_ordinal718:PANYARGS
mtxoci_ordinal718 TEXTEQU <__imp_mtxoci_ordinal718>
extern __imp_mtxoci_ordinal719:PANYARGS
mtxoci_ordinal719 TEXTEQU <__imp_mtxoci_ordinal719>
extern __imp_mtxoci_ordinal720:PANYARGS
mtxoci_ordinal720 TEXTEQU <__imp_mtxoci_ordinal720>
extern __imp_mtxoci_ordinal721:PANYARGS
mtxoci_ordinal721 TEXTEQU <__imp_mtxoci_ordinal721>
extern __imp_mtxoci_ordinal722:PANYARGS
mtxoci_ordinal722 TEXTEQU <__imp_mtxoci_ordinal722>
extern __imp_mtxoci_ordinal723:PANYARGS
mtxoci_ordinal723 TEXTEQU <__imp_mtxoci_ordinal723>
extern __imp_mtxoci_ordinal724:PANYARGS
mtxoci_ordinal724 TEXTEQU <__imp_mtxoci_ordinal724>
extern __imp_mtxoci_ordinal725:PANYARGS
mtxoci_ordinal725 TEXTEQU <__imp_mtxoci_ordinal725>
extern __imp_mtxoci_ordinal726:PANYARGS
mtxoci_ordinal726 TEXTEQU <__imp_mtxoci_ordinal726>
extern __imp_mtxoci_ordinal727:PANYARGS
mtxoci_ordinal727 TEXTEQU <__imp_mtxoci_ordinal727>
extern __imp_mtxoci_ordinal728:PANYARGS
mtxoci_ordinal728 TEXTEQU <__imp_mtxoci_ordinal728>
extern __imp_mtxoci_ordinal729:PANYARGS
mtxoci_ordinal729 TEXTEQU <__imp_mtxoci_ordinal729>
extern __imp_mtxoci_ordinal730:PANYARGS
mtxoci_ordinal730 TEXTEQU <__imp_mtxoci_ordinal730>
extern __imp_mtxoci_ordinal731:PANYARGS
mtxoci_ordinal731 TEXTEQU <__imp_mtxoci_ordinal731>
extern __imp_mtxoci_ordinal732:PANYARGS
mtxoci_ordinal732 TEXTEQU <__imp_mtxoci_ordinal732>
extern __imp_mtxoci_ordinal733:PANYARGS
mtxoci_ordinal733 TEXTEQU <__imp_mtxoci_ordinal733>
extern __imp_mtxoci_ordinal734:PANYARGS
mtxoci_ordinal734 TEXTEQU <__imp_mtxoci_ordinal734>
extern __imp_mtxoci_ordinal735:PANYARGS
mtxoci_ordinal735 TEXTEQU <__imp_mtxoci_ordinal735>
extern __imp_mtxoci_ordinal736:PANYARGS
mtxoci_ordinal736 TEXTEQU <__imp_mtxoci_ordinal736>
extern __imp_mtxoci_ordinal737:PANYARGS
mtxoci_ordinal737 TEXTEQU <__imp_mtxoci_ordinal737>
extern __imp_mtxoci_ordinal738:PANYARGS
mtxoci_ordinal738 TEXTEQU <__imp_mtxoci_ordinal738>
extern __imp_mtxoci_ordinal739:PANYARGS
mtxoci_ordinal739 TEXTEQU <__imp_mtxoci_ordinal739>
extern __imp_mtxoci_ordinal740:PANYARGS
mtxoci_ordinal740 TEXTEQU <__imp_mtxoci_ordinal740>
extern __imp_mtxoci_ordinal741:PANYARGS
mtxoci_ordinal741 TEXTEQU <__imp_mtxoci_ordinal741>
extern __imp_mtxoci_ordinal742:PANYARGS
mtxoci_ordinal742 TEXTEQU <__imp_mtxoci_ordinal742>
extern __imp_mtxoci_ordinal743:PANYARGS
mtxoci_ordinal743 TEXTEQU <__imp_mtxoci_ordinal743>
extern __imp_mtxoci_ordinal744:PANYARGS
mtxoci_ordinal744 TEXTEQU <__imp_mtxoci_ordinal744>
extern __imp_mtxoci_ordinal745:PANYARGS
mtxoci_ordinal745 TEXTEQU <__imp_mtxoci_ordinal745>
extern __imp_mtxoci_ordinal746:PANYARGS
mtxoci_ordinal746 TEXTEQU <__imp_mtxoci_ordinal746>
extern __imp_mtxoci_ordinal747:PANYARGS
mtxoci_ordinal747 TEXTEQU <__imp_mtxoci_ordinal747>
extern __imp_mtxoci_ordinal748:PANYARGS
mtxoci_ordinal748 TEXTEQU <__imp_mtxoci_ordinal748>
extern __imp_mtxoci_ordinal749:PANYARGS
mtxoci_ordinal749 TEXTEQU <__imp_mtxoci_ordinal749>
extern __imp_mtxoci_ordinal750:PANYARGS
mtxoci_ordinal750 TEXTEQU <__imp_mtxoci_ordinal750>
extern __imp_mtxoci_ordinal751:PANYARGS
mtxoci_ordinal751 TEXTEQU <__imp_mtxoci_ordinal751>
extern __imp_mtxoci_ordinal752:PANYARGS
mtxoci_ordinal752 TEXTEQU <__imp_mtxoci_ordinal752>
extern __imp_mtxoci_ordinal753:PANYARGS
mtxoci_ordinal753 TEXTEQU <__imp_mtxoci_ordinal753>
extern __imp_mtxoci_ordinal754:PANYARGS
mtxoci_ordinal754 TEXTEQU <__imp_mtxoci_ordinal754>
extern __imp_mtxoci_ordinal755:PANYARGS
mtxoci_ordinal755 TEXTEQU <__imp_mtxoci_ordinal755>
extern __imp_mtxoci_ordinal756:PANYARGS
mtxoci_ordinal756 TEXTEQU <__imp_mtxoci_ordinal756>
extern __imp_mtxoci_ordinal757:PANYARGS
mtxoci_ordinal757 TEXTEQU <__imp_mtxoci_ordinal757>
extern __imp_mtxoci_ordinal758:PANYARGS
mtxoci_ordinal758 TEXTEQU <__imp_mtxoci_ordinal758>
extern __imp_mtxoci_ordinal759:PANYARGS
mtxoci_ordinal759 TEXTEQU <__imp_mtxoci_ordinal759>
extern __imp_mtxoci_ordinal760:PANYARGS
mtxoci_ordinal760 TEXTEQU <__imp_mtxoci_ordinal760>
extern __imp_mtxoci_ordinal761:PANYARGS
mtxoci_ordinal761 TEXTEQU <__imp_mtxoci_ordinal761>
extern __imp_mtxoci_ordinal762:PANYARGS
mtxoci_ordinal762 TEXTEQU <__imp_mtxoci_ordinal762>
extern __imp_mtxoci_ordinal763:PANYARGS
mtxoci_ordinal763 TEXTEQU <__imp_mtxoci_ordinal763>
extern __imp_mtxoci_ordinal764:PANYARGS
mtxoci_ordinal764 TEXTEQU <__imp_mtxoci_ordinal764>
extern __imp_mtxoci_ordinal765:PANYARGS
mtxoci_ordinal765 TEXTEQU <__imp_mtxoci_ordinal765>
extern __imp_mtxoci_ordinal766:PANYARGS
mtxoci_ordinal766 TEXTEQU <__imp_mtxoci_ordinal766>
extern __imp_mtxoci_ordinal767:PANYARGS
mtxoci_ordinal767 TEXTEQU <__imp_mtxoci_ordinal767>
extern __imp_mtxoci_ordinal768:PANYARGS
mtxoci_ordinal768 TEXTEQU <__imp_mtxoci_ordinal768>
extern __imp_mtxoci_ordinal769:PANYARGS
mtxoci_ordinal769 TEXTEQU <__imp_mtxoci_ordinal769>
extern __imp_mtxoci_ordinal770:PANYARGS
mtxoci_ordinal770 TEXTEQU <__imp_mtxoci_ordinal770>
extern __imp_mtxoci_ordinal771:PANYARGS
mtxoci_ordinal771 TEXTEQU <__imp_mtxoci_ordinal771>
extern __imp_mtxoci_ordinal772:PANYARGS
mtxoci_ordinal772 TEXTEQU <__imp_mtxoci_ordinal772>
extern __imp_mtxoci_ordinal773:PANYARGS
mtxoci_ordinal773 TEXTEQU <__imp_mtxoci_ordinal773>
extern __imp_mtxoci_ordinal774:PANYARGS
mtxoci_ordinal774 TEXTEQU <__imp_mtxoci_ordinal774>
extern __imp_mtxoci_ordinal775:PANYARGS
mtxoci_ordinal775 TEXTEQU <__imp_mtxoci_ordinal775>
extern __imp_mtxoci_ordinal776:PANYARGS
mtxoci_ordinal776 TEXTEQU <__imp_mtxoci_ordinal776>
extern __imp_mtxoci_ordinal777:PANYARGS
mtxoci_ordinal777 TEXTEQU <__imp_mtxoci_ordinal777>
extern __imp_mtxoci_ordinal778:PANYARGS
mtxoci_ordinal778 TEXTEQU <__imp_mtxoci_ordinal778>
extern __imp_mtxoci_ordinal779:PANYARGS
mtxoci_ordinal779 TEXTEQU <__imp_mtxoci_ordinal779>
extern __imp_mtxoci_ordinal780:PANYARGS
mtxoci_ordinal780 TEXTEQU <__imp_mtxoci_ordinal780>
extern __imp_mtxoci_ordinal781:PANYARGS
mtxoci_ordinal781 TEXTEQU <__imp_mtxoci_ordinal781>
extern __imp_mtxoci_ordinal782:PANYARGS
mtxoci_ordinal782 TEXTEQU <__imp_mtxoci_ordinal782>
extern __imp_mtxoci_ordinal783:PANYARGS
mtxoci_ordinal783 TEXTEQU <__imp_mtxoci_ordinal783>
extern __imp_mtxoci_ordinal784:PANYARGS
mtxoci_ordinal784 TEXTEQU <__imp_mtxoci_ordinal784>
extern __imp_mtxoci_ordinal785:PANYARGS
mtxoci_ordinal785 TEXTEQU <__imp_mtxoci_ordinal785>
extern __imp_mtxoci_ordinal786:PANYARGS
mtxoci_ordinal786 TEXTEQU <__imp_mtxoci_ordinal786>
extern __imp_mtxoci_ordinal787:PANYARGS
mtxoci_ordinal787 TEXTEQU <__imp_mtxoci_ordinal787>
extern __imp_mtxoci_ordinal788:PANYARGS
mtxoci_ordinal788 TEXTEQU <__imp_mtxoci_ordinal788>
extern __imp_mtxoci_ordinal789:PANYARGS
mtxoci_ordinal789 TEXTEQU <__imp_mtxoci_ordinal789>
extern __imp_mtxoci_ordinal790:PANYARGS
mtxoci_ordinal790 TEXTEQU <__imp_mtxoci_ordinal790>
extern __imp_mtxoci_ordinal791:PANYARGS
mtxoci_ordinal791 TEXTEQU <__imp_mtxoci_ordinal791>
extern __imp_mtxoci_ordinal792:PANYARGS
mtxoci_ordinal792 TEXTEQU <__imp_mtxoci_ordinal792>
extern __imp_mtxoci_ordinal793:PANYARGS
mtxoci_ordinal793 TEXTEQU <__imp_mtxoci_ordinal793>
extern __imp_mtxoci_ordinal794:PANYARGS
mtxoci_ordinal794 TEXTEQU <__imp_mtxoci_ordinal794>
extern __imp_mtxoci_ordinal795:PANYARGS
mtxoci_ordinal795 TEXTEQU <__imp_mtxoci_ordinal795>
extern __imp_mtxoci_ordinal796:PANYARGS
mtxoci_ordinal796 TEXTEQU <__imp_mtxoci_ordinal796>
extern __imp_mtxoci_ordinal797:PANYARGS
mtxoci_ordinal797 TEXTEQU <__imp_mtxoci_ordinal797>
extern __imp_mtxoci_ordinal798:PANYARGS
mtxoci_ordinal798 TEXTEQU <__imp_mtxoci_ordinal798>
extern __imp_mtxoci_ordinal799:PANYARGS
mtxoci_ordinal799 TEXTEQU <__imp_mtxoci_ordinal799>
extern __imp_mtxoci_ordinal800:PANYARGS
mtxoci_ordinal800 TEXTEQU <__imp_mtxoci_ordinal800>
extern __imp_mtxoci_ordinal801:PANYARGS
mtxoci_ordinal801 TEXTEQU <__imp_mtxoci_ordinal801>
extern __imp_mtxoci_ordinal802:PANYARGS
mtxoci_ordinal802 TEXTEQU <__imp_mtxoci_ordinal802>
extern __imp_mtxoci_ordinal803:PANYARGS
mtxoci_ordinal803 TEXTEQU <__imp_mtxoci_ordinal803>
extern __imp_mtxoci_ordinal804:PANYARGS
mtxoci_ordinal804 TEXTEQU <__imp_mtxoci_ordinal804>
extern __imp_mtxoci_ordinal805:PANYARGS
mtxoci_ordinal805 TEXTEQU <__imp_mtxoci_ordinal805>
extern __imp_mtxoci_ordinal806:PANYARGS
mtxoci_ordinal806 TEXTEQU <__imp_mtxoci_ordinal806>
extern __imp_mtxoci_ordinal807:PANYARGS
mtxoci_ordinal807 TEXTEQU <__imp_mtxoci_ordinal807>
extern __imp_mtxoci_ordinal808:PANYARGS
mtxoci_ordinal808 TEXTEQU <__imp_mtxoci_ordinal808>
extern __imp_mtxoci_ordinal809:PANYARGS
mtxoci_ordinal809 TEXTEQU <__imp_mtxoci_ordinal809>
extern __imp_mtxoci_ordinal810:PANYARGS
mtxoci_ordinal810 TEXTEQU <__imp_mtxoci_ordinal810>
extern __imp_mtxoci_ordinal811:PANYARGS
mtxoci_ordinal811 TEXTEQU <__imp_mtxoci_ordinal811>
extern __imp_mtxoci_ordinal812:PANYARGS
mtxoci_ordinal812 TEXTEQU <__imp_mtxoci_ordinal812>
extern __imp_mtxoci_ordinal813:PANYARGS
mtxoci_ordinal813 TEXTEQU <__imp_mtxoci_ordinal813>
extern __imp_mtxoci_ordinal814:PANYARGS
mtxoci_ordinal814 TEXTEQU <__imp_mtxoci_ordinal814>
extern __imp_mtxoci_ordinal815:PANYARGS
mtxoci_ordinal815 TEXTEQU <__imp_mtxoci_ordinal815>
extern __imp_mtxoci_ordinal816:PANYARGS
mtxoci_ordinal816 TEXTEQU <__imp_mtxoci_ordinal816>
extern __imp_mtxoci_ordinal817:PANYARGS
mtxoci_ordinal817 TEXTEQU <__imp_mtxoci_ordinal817>
extern __imp_mtxoci_ordinal818:PANYARGS
mtxoci_ordinal818 TEXTEQU <__imp_mtxoci_ordinal818>
extern __imp_mtxoci_ordinal819:PANYARGS
mtxoci_ordinal819 TEXTEQU <__imp_mtxoci_ordinal819>
extern __imp_mtxoci_ordinal820:PANYARGS
mtxoci_ordinal820 TEXTEQU <__imp_mtxoci_ordinal820>
extern __imp_mtxoci_ordinal821:PANYARGS
mtxoci_ordinal821 TEXTEQU <__imp_mtxoci_ordinal821>
extern __imp_mtxoci_ordinal822:PANYARGS
mtxoci_ordinal822 TEXTEQU <__imp_mtxoci_ordinal822>
extern __imp_mtxoci_ordinal823:PANYARGS
mtxoci_ordinal823 TEXTEQU <__imp_mtxoci_ordinal823>
extern __imp_mtxoci_ordinal824:PANYARGS
mtxoci_ordinal824 TEXTEQU <__imp_mtxoci_ordinal824>
extern __imp_mtxoci_ordinal825:PANYARGS
mtxoci_ordinal825 TEXTEQU <__imp_mtxoci_ordinal825>
extern __imp_mtxoci_ordinal826:PANYARGS
mtxoci_ordinal826 TEXTEQU <__imp_mtxoci_ordinal826>
extern __imp_mtxoci_ordinal827:PANYARGS
mtxoci_ordinal827 TEXTEQU <__imp_mtxoci_ordinal827>
extern __imp_mtxoci_ordinal828:PANYARGS
mtxoci_ordinal828 TEXTEQU <__imp_mtxoci_ordinal828>
extern __imp_mtxoci_ordinal829:PANYARGS
mtxoci_ordinal829 TEXTEQU <__imp_mtxoci_ordinal829>
extern __imp_mtxoci_ordinal830:PANYARGS
mtxoci_ordinal830 TEXTEQU <__imp_mtxoci_ordinal830>
extern __imp_mtxoci_ordinal831:PANYARGS
mtxoci_ordinal831 TEXTEQU <__imp_mtxoci_ordinal831>
extern __imp_mtxoci_ordinal832:PANYARGS
mtxoci_ordinal832 TEXTEQU <__imp_mtxoci_ordinal832>
extern __imp_mtxoci_ordinal833:PANYARGS
mtxoci_ordinal833 TEXTEQU <__imp_mtxoci_ordinal833>
extern __imp_mtxoci_ordinal834:PANYARGS
mtxoci_ordinal834 TEXTEQU <__imp_mtxoci_ordinal834>
extern __imp_mtxoci_ordinal835:PANYARGS
mtxoci_ordinal835 TEXTEQU <__imp_mtxoci_ordinal835>
extern __imp_mtxoci_ordinal836:PANYARGS
mtxoci_ordinal836 TEXTEQU <__imp_mtxoci_ordinal836>
extern __imp_mtxoci_ordinal837:PANYARGS
mtxoci_ordinal837 TEXTEQU <__imp_mtxoci_ordinal837>
extern __imp_mtxoci_ordinal838:PANYARGS
mtxoci_ordinal838 TEXTEQU <__imp_mtxoci_ordinal838>
extern __imp_mtxoci_ordinal839:PANYARGS
mtxoci_ordinal839 TEXTEQU <__imp_mtxoci_ordinal839>
extern __imp_mtxoci_ordinal840:PANYARGS
mtxoci_ordinal840 TEXTEQU <__imp_mtxoci_ordinal840>
extern __imp_mtxoci_ordinal841:PANYARGS
mtxoci_ordinal841 TEXTEQU <__imp_mtxoci_ordinal841>
extern __imp_mtxoci_ordinal842:PANYARGS
mtxoci_ordinal842 TEXTEQU <__imp_mtxoci_ordinal842>
extern __imp_mtxoci_ordinal843:PANYARGS
mtxoci_ordinal843 TEXTEQU <__imp_mtxoci_ordinal843>
extern __imp_mtxoci_ordinal844:PANYARGS
mtxoci_ordinal844 TEXTEQU <__imp_mtxoci_ordinal844>
extern __imp_mtxoci_ordinal845:PANYARGS
mtxoci_ordinal845 TEXTEQU <__imp_mtxoci_ordinal845>
extern __imp_mtxoci_ordinal846:PANYARGS
mtxoci_ordinal846 TEXTEQU <__imp_mtxoci_ordinal846>
extern __imp_mtxoci_ordinal847:PANYARGS
mtxoci_ordinal847 TEXTEQU <__imp_mtxoci_ordinal847>
extern __imp_mtxoci_ordinal848:PANYARGS
mtxoci_ordinal848 TEXTEQU <__imp_mtxoci_ordinal848>
extern __imp_mtxoci_ordinal849:PANYARGS
mtxoci_ordinal849 TEXTEQU <__imp_mtxoci_ordinal849>
extern __imp_mtxoci_ordinal850:PANYARGS
mtxoci_ordinal850 TEXTEQU <__imp_mtxoci_ordinal850>
extern __imp_mtxoci_ordinal851:PANYARGS
mtxoci_ordinal851 TEXTEQU <__imp_mtxoci_ordinal851>
extern __imp_mtxoci_ordinal852:PANYARGS
mtxoci_ordinal852 TEXTEQU <__imp_mtxoci_ordinal852>
extern __imp_mtxoci_ordinal853:PANYARGS
mtxoci_ordinal853 TEXTEQU <__imp_mtxoci_ordinal853>
extern __imp_mtxoci_ordinal854:PANYARGS
mtxoci_ordinal854 TEXTEQU <__imp_mtxoci_ordinal854>
extern __imp_mtxoci_ordinal855:PANYARGS
mtxoci_ordinal855 TEXTEQU <__imp_mtxoci_ordinal855>
extern __imp_mtxoci_ordinal856:PANYARGS
mtxoci_ordinal856 TEXTEQU <__imp_mtxoci_ordinal856>
extern __imp_mtxoci_ordinal857:PANYARGS
mtxoci_ordinal857 TEXTEQU <__imp_mtxoci_ordinal857>
extern __imp_mtxoci_ordinal858:PANYARGS
mtxoci_ordinal858 TEXTEQU <__imp_mtxoci_ordinal858>
extern __imp_mtxoci_ordinal859:PANYARGS
mtxoci_ordinal859 TEXTEQU <__imp_mtxoci_ordinal859>
extern __imp_mtxoci_ordinal860:PANYARGS
mtxoci_ordinal860 TEXTEQU <__imp_mtxoci_ordinal860>
extern __imp_mtxoci_ordinal861:PANYARGS
mtxoci_ordinal861 TEXTEQU <__imp_mtxoci_ordinal861>
extern __imp_mtxoci_ordinal862:PANYARGS
mtxoci_ordinal862 TEXTEQU <__imp_mtxoci_ordinal862>
extern __imp_mtxoci_ordinal863:PANYARGS
mtxoci_ordinal863 TEXTEQU <__imp_mtxoci_ordinal863>
extern __imp_mtxoci_ordinal864:PANYARGS
mtxoci_ordinal864 TEXTEQU <__imp_mtxoci_ordinal864>
extern __imp_mtxoci_ordinal865:PANYARGS
mtxoci_ordinal865 TEXTEQU <__imp_mtxoci_ordinal865>
extern __imp_mtxoci_ordinal866:PANYARGS
mtxoci_ordinal866 TEXTEQU <__imp_mtxoci_ordinal866>
extern __imp_mtxoci_ordinal867:PANYARGS
mtxoci_ordinal867 TEXTEQU <__imp_mtxoci_ordinal867>
extern __imp_mtxoci_ordinal868:PANYARGS
mtxoci_ordinal868 TEXTEQU <__imp_mtxoci_ordinal868>
extern __imp_mtxoci_ordinal869:PANYARGS
mtxoci_ordinal869 TEXTEQU <__imp_mtxoci_ordinal869>
extern __imp_mtxoci_ordinal870:PANYARGS
mtxoci_ordinal870 TEXTEQU <__imp_mtxoci_ordinal870>
extern __imp_mtxoci_ordinal871:PANYARGS
mtxoci_ordinal871 TEXTEQU <__imp_mtxoci_ordinal871>
extern __imp_mtxoci_ordinal872:PANYARGS
mtxoci_ordinal872 TEXTEQU <__imp_mtxoci_ordinal872>
extern __imp_mtxoci_ordinal873:PANYARGS
mtxoci_ordinal873 TEXTEQU <__imp_mtxoci_ordinal873>
extern __imp_mtxoci_ordinal874:PANYARGS
mtxoci_ordinal874 TEXTEQU <__imp_mtxoci_ordinal874>
extern __imp_mtxoci_ordinal875:PANYARGS
mtxoci_ordinal875 TEXTEQU <__imp_mtxoci_ordinal875>
extern __imp_mtxoci_ordinal876:PANYARGS
mtxoci_ordinal876 TEXTEQU <__imp_mtxoci_ordinal876>
extern __imp_mtxoci_ordinal877:PANYARGS
mtxoci_ordinal877 TEXTEQU <__imp_mtxoci_ordinal877>
extern __imp_mtxoci_ordinal878:PANYARGS
mtxoci_ordinal878 TEXTEQU <__imp_mtxoci_ordinal878>
extern __imp_mtxoci_ordinal879:PANYARGS
mtxoci_ordinal879 TEXTEQU <__imp_mtxoci_ordinal879>
extern __imp_mtxoci_ordinal880:PANYARGS
mtxoci_ordinal880 TEXTEQU <__imp_mtxoci_ordinal880>
extern __imp_mtxoci_ordinal881:PANYARGS
mtxoci_ordinal881 TEXTEQU <__imp_mtxoci_ordinal881>
extern __imp_mtxoci_ordinal882:PANYARGS
mtxoci_ordinal882 TEXTEQU <__imp_mtxoci_ordinal882>
extern __imp_mtxoci_ordinal883:PANYARGS
mtxoci_ordinal883 TEXTEQU <__imp_mtxoci_ordinal883>
extern __imp_mtxoci_ordinal884:PANYARGS
mtxoci_ordinal884 TEXTEQU <__imp_mtxoci_ordinal884>
extern __imp_mtxoci_ordinal885:PANYARGS
mtxoci_ordinal885 TEXTEQU <__imp_mtxoci_ordinal885>
extern __imp_mtxoci_ordinal886:PANYARGS
mtxoci_ordinal886 TEXTEQU <__imp_mtxoci_ordinal886>
extern __imp_mtxoci_ordinal887:PANYARGS
mtxoci_ordinal887 TEXTEQU <__imp_mtxoci_ordinal887>
extern __imp_mtxoci_ordinal888:PANYARGS
mtxoci_ordinal888 TEXTEQU <__imp_mtxoci_ordinal888>
extern __imp_mtxoci_ordinal889:PANYARGS
mtxoci_ordinal889 TEXTEQU <__imp_mtxoci_ordinal889>
extern __imp_mtxoci_ordinal890:PANYARGS
mtxoci_ordinal890 TEXTEQU <__imp_mtxoci_ordinal890>
extern __imp_mtxoci_ordinal891:PANYARGS
mtxoci_ordinal891 TEXTEQU <__imp_mtxoci_ordinal891>
extern __imp_mtxoci_ordinal892:PANYARGS
mtxoci_ordinal892 TEXTEQU <__imp_mtxoci_ordinal892>
extern __imp_mtxoci_ordinal893:PANYARGS
mtxoci_ordinal893 TEXTEQU <__imp_mtxoci_ordinal893>
extern __imp_mtxoci_ordinal894:PANYARGS
mtxoci_ordinal894 TEXTEQU <__imp_mtxoci_ordinal894>
extern __imp_mtxoci_ordinal895:PANYARGS
mtxoci_ordinal895 TEXTEQU <__imp_mtxoci_ordinal895>
extern __imp_mtxoci_ordinal896:PANYARGS
mtxoci_ordinal896 TEXTEQU <__imp_mtxoci_ordinal896>
extern __imp_mtxoci_ordinal897:PANYARGS
mtxoci_ordinal897 TEXTEQU <__imp_mtxoci_ordinal897>
extern __imp_mtxoci_ordinal898:PANYARGS
mtxoci_ordinal898 TEXTEQU <__imp_mtxoci_ordinal898>
extern __imp_mtxoci_ordinal899:PANYARGS
mtxoci_ordinal899 TEXTEQU <__imp_mtxoci_ordinal899>
extern __imp_mtxoci_ordinal900:PANYARGS
mtxoci_ordinal900 TEXTEQU <__imp_mtxoci_ordinal900>
extern __imp_mtxoci_ordinal901:PANYARGS
mtxoci_ordinal901 TEXTEQU <__imp_mtxoci_ordinal901>
extern __imp_mtxoci_ordinal902:PANYARGS
mtxoci_ordinal902 TEXTEQU <__imp_mtxoci_ordinal902>
extern __imp_mtxoci_ordinal903:PANYARGS
mtxoci_ordinal903 TEXTEQU <__imp_mtxoci_ordinal903>
extern __imp_mtxoci_ordinal904:PANYARGS
mtxoci_ordinal904 TEXTEQU <__imp_mtxoci_ordinal904>
extern __imp_mtxoci_ordinal905:PANYARGS
mtxoci_ordinal905 TEXTEQU <__imp_mtxoci_ordinal905>
extern __imp_mtxoci_ordinal906:PANYARGS
mtxoci_ordinal906 TEXTEQU <__imp_mtxoci_ordinal906>
extern __imp_mtxoci_ordinal907:PANYARGS
mtxoci_ordinal907 TEXTEQU <__imp_mtxoci_ordinal907>
extern __imp_mtxoci_ordinal908:PANYARGS
mtxoci_ordinal908 TEXTEQU <__imp_mtxoci_ordinal908>
extern __imp_mtxoci_ordinal909:PANYARGS
mtxoci_ordinal909 TEXTEQU <__imp_mtxoci_ordinal909>
extern __imp_mtxoci_ordinal910:PANYARGS
mtxoci_ordinal910 TEXTEQU <__imp_mtxoci_ordinal910>
extern __imp_mtxoci_ordinal911:PANYARGS
mtxoci_ordinal911 TEXTEQU <__imp_mtxoci_ordinal911>
extern __imp_mtxoci_ordinal912:PANYARGS
mtxoci_ordinal912 TEXTEQU <__imp_mtxoci_ordinal912>
extern __imp_mtxoci_ordinal913:PANYARGS
mtxoci_ordinal913 TEXTEQU <__imp_mtxoci_ordinal913>
extern __imp_mtxoci_ordinal914:PANYARGS
mtxoci_ordinal914 TEXTEQU <__imp_mtxoci_ordinal914>
extern __imp_mtxoci_ordinal915:PANYARGS
mtxoci_ordinal915 TEXTEQU <__imp_mtxoci_ordinal915>
extern __imp_mtxoci_ordinal916:PANYARGS
mtxoci_ordinal916 TEXTEQU <__imp_mtxoci_ordinal916>
extern __imp_mtxoci_ordinal917:PANYARGS
mtxoci_ordinal917 TEXTEQU <__imp_mtxoci_ordinal917>
extern __imp_mtxoci_ordinal918:PANYARGS
mtxoci_ordinal918 TEXTEQU <__imp_mtxoci_ordinal918>
extern __imp_mtxoci_ordinal919:PANYARGS
mtxoci_ordinal919 TEXTEQU <__imp_mtxoci_ordinal919>
extern __imp_mtxoci_ordinal920:PANYARGS
mtxoci_ordinal920 TEXTEQU <__imp_mtxoci_ordinal920>
extern __imp_mtxoci_ordinal921:PANYARGS
mtxoci_ordinal921 TEXTEQU <__imp_mtxoci_ordinal921>
extern __imp_mtxoci_ordinal922:PANYARGS
mtxoci_ordinal922 TEXTEQU <__imp_mtxoci_ordinal922>
extern __imp_mtxoci_ordinal923:PANYARGS
mtxoci_ordinal923 TEXTEQU <__imp_mtxoci_ordinal923>
extern __imp_mtxoci_ordinal924:PANYARGS
mtxoci_ordinal924 TEXTEQU <__imp_mtxoci_ordinal924>
extern __imp_mtxoci_ordinal925:PANYARGS
mtxoci_ordinal925 TEXTEQU <__imp_mtxoci_ordinal925>
extern __imp_mtxoci_ordinal926:PANYARGS
mtxoci_ordinal926 TEXTEQU <__imp_mtxoci_ordinal926>
extern __imp_mtxoci_ordinal927:PANYARGS
mtxoci_ordinal927 TEXTEQU <__imp_mtxoci_ordinal927>
extern __imp_mtxoci_ordinal928:PANYARGS
mtxoci_ordinal928 TEXTEQU <__imp_mtxoci_ordinal928>
extern __imp_mtxoci_ordinal929:PANYARGS
mtxoci_ordinal929 TEXTEQU <__imp_mtxoci_ordinal929>
extern __imp_mtxoci_ordinal930:PANYARGS
mtxoci_ordinal930 TEXTEQU <__imp_mtxoci_ordinal930>
extern __imp_mtxoci_ordinal931:PANYARGS
mtxoci_ordinal931 TEXTEQU <__imp_mtxoci_ordinal931>
extern __imp_mtxoci_ordinal932:PANYARGS
mtxoci_ordinal932 TEXTEQU <__imp_mtxoci_ordinal932>
extern __imp_mtxoci_ordinal933:PANYARGS
mtxoci_ordinal933 TEXTEQU <__imp_mtxoci_ordinal933>
extern __imp_mtxoci_ordinal934:PANYARGS
mtxoci_ordinal934 TEXTEQU <__imp_mtxoci_ordinal934>
extern __imp_mtxoci_ordinal935:PANYARGS
mtxoci_ordinal935 TEXTEQU <__imp_mtxoci_ordinal935>
extern __imp_mtxoci_ordinal936:PANYARGS
mtxoci_ordinal936 TEXTEQU <__imp_mtxoci_ordinal936>
extern __imp_mtxoci_ordinal937:PANYARGS
mtxoci_ordinal937 TEXTEQU <__imp_mtxoci_ordinal937>
extern __imp_mtxoci_ordinal938:PANYARGS
mtxoci_ordinal938 TEXTEQU <__imp_mtxoci_ordinal938>
extern __imp_mtxoci_ordinal939:PANYARGS
mtxoci_ordinal939 TEXTEQU <__imp_mtxoci_ordinal939>
extern __imp_mtxoci_ordinal940:PANYARGS
mtxoci_ordinal940 TEXTEQU <__imp_mtxoci_ordinal940>
extern __imp_mtxoci_ordinal941:PANYARGS
mtxoci_ordinal941 TEXTEQU <__imp_mtxoci_ordinal941>
extern __imp_mtxoci_ordinal942:PANYARGS
mtxoci_ordinal942 TEXTEQU <__imp_mtxoci_ordinal942>
extern __imp_mtxoci_ordinal943:PANYARGS
mtxoci_ordinal943 TEXTEQU <__imp_mtxoci_ordinal943>
extern __imp_mtxoci_ordinal944:PANYARGS
mtxoci_ordinal944 TEXTEQU <__imp_mtxoci_ordinal944>
extern __imp_mtxoci_ordinal945:PANYARGS
mtxoci_ordinal945 TEXTEQU <__imp_mtxoci_ordinal945>
extern __imp_mtxoci_ordinal946:PANYARGS
mtxoci_ordinal946 TEXTEQU <__imp_mtxoci_ordinal946>
extern __imp_mtxoci_ordinal947:PANYARGS
mtxoci_ordinal947 TEXTEQU <__imp_mtxoci_ordinal947>
extern __imp_mtxoci_ordinal948:PANYARGS
mtxoci_ordinal948 TEXTEQU <__imp_mtxoci_ordinal948>
extern __imp_mtxoci_ordinal949:PANYARGS
mtxoci_ordinal949 TEXTEQU <__imp_mtxoci_ordinal949>
extern __imp_mtxoci_ordinal950:PANYARGS
mtxoci_ordinal950 TEXTEQU <__imp_mtxoci_ordinal950>
extern __imp_mtxoci_ordinal951:PANYARGS
mtxoci_ordinal951 TEXTEQU <__imp_mtxoci_ordinal951>
extern __imp_mtxoci_ordinal952:PANYARGS
mtxoci_ordinal952 TEXTEQU <__imp_mtxoci_ordinal952>
extern __imp_mtxoci_ordinal953:PANYARGS
mtxoci_ordinal953 TEXTEQU <__imp_mtxoci_ordinal953>
extern __imp_mtxoci_ordinal954:PANYARGS
mtxoci_ordinal954 TEXTEQU <__imp_mtxoci_ordinal954>
extern __imp_mtxoci_ordinal955:PANYARGS
mtxoci_ordinal955 TEXTEQU <__imp_mtxoci_ordinal955>
extern __imp_mtxoci_ordinal956:PANYARGS
mtxoci_ordinal956 TEXTEQU <__imp_mtxoci_ordinal956>
extern __imp_mtxoci_ordinal957:PANYARGS
mtxoci_ordinal957 TEXTEQU <__imp_mtxoci_ordinal957>
extern __imp_mtxoci_ordinal958:PANYARGS
mtxoci_ordinal958 TEXTEQU <__imp_mtxoci_ordinal958>
extern __imp_mtxoci_ordinal959:PANYARGS
mtxoci_ordinal959 TEXTEQU <__imp_mtxoci_ordinal959>
extern __imp_mtxoci_ordinal960:PANYARGS
mtxoci_ordinal960 TEXTEQU <__imp_mtxoci_ordinal960>
extern __imp_mtxoci_ordinal961:PANYARGS
mtxoci_ordinal961 TEXTEQU <__imp_mtxoci_ordinal961>
extern __imp_mtxoci_ordinal962:PANYARGS
mtxoci_ordinal962 TEXTEQU <__imp_mtxoci_ordinal962>
extern __imp_mtxoci_ordinal963:PANYARGS
mtxoci_ordinal963 TEXTEQU <__imp_mtxoci_ordinal963>
extern __imp_mtxoci_ordinal964:PANYARGS
mtxoci_ordinal964 TEXTEQU <__imp_mtxoci_ordinal964>
extern __imp_mtxoci_ordinal965:PANYARGS
mtxoci_ordinal965 TEXTEQU <__imp_mtxoci_ordinal965>
extern __imp_mtxoci_ordinal966:PANYARGS
mtxoci_ordinal966 TEXTEQU <__imp_mtxoci_ordinal966>
extern __imp_mtxoci_ordinal967:PANYARGS
mtxoci_ordinal967 TEXTEQU <__imp_mtxoci_ordinal967>
extern __imp_mtxoci_ordinal968:PANYARGS
mtxoci_ordinal968 TEXTEQU <__imp_mtxoci_ordinal968>
extern __imp_mtxoci_ordinal969:PANYARGS
mtxoci_ordinal969 TEXTEQU <__imp_mtxoci_ordinal969>
extern __imp_mtxoci_ordinal970:PANYARGS
mtxoci_ordinal970 TEXTEQU <__imp_mtxoci_ordinal970>
extern __imp_mtxoci_ordinal971:PANYARGS
mtxoci_ordinal971 TEXTEQU <__imp_mtxoci_ordinal971>
extern __imp_mtxoci_ordinal972:PANYARGS
mtxoci_ordinal972 TEXTEQU <__imp_mtxoci_ordinal972>
extern __imp_mtxoci_ordinal973:PANYARGS
mtxoci_ordinal973 TEXTEQU <__imp_mtxoci_ordinal973>
extern __imp_mtxoci_ordinal974:PANYARGS
mtxoci_ordinal974 TEXTEQU <__imp_mtxoci_ordinal974>
extern __imp_mtxoci_ordinal975:PANYARGS
mtxoci_ordinal975 TEXTEQU <__imp_mtxoci_ordinal975>
extern __imp_mtxoci_ordinal976:PANYARGS
mtxoci_ordinal976 TEXTEQU <__imp_mtxoci_ordinal976>
extern __imp_mtxoci_ordinal977:PANYARGS
mtxoci_ordinal977 TEXTEQU <__imp_mtxoci_ordinal977>
extern __imp_mtxoci_ordinal978:PANYARGS
mtxoci_ordinal978 TEXTEQU <__imp_mtxoci_ordinal978>
extern __imp_mtxoci_ordinal979:PANYARGS
mtxoci_ordinal979 TEXTEQU <__imp_mtxoci_ordinal979>
extern __imp_mtxoci_ordinal980:PANYARGS
mtxoci_ordinal980 TEXTEQU <__imp_mtxoci_ordinal980>
extern __imp_mtxoci_ordinal981:PANYARGS
mtxoci_ordinal981 TEXTEQU <__imp_mtxoci_ordinal981>
extern __imp_mtxoci_ordinal982:PANYARGS
mtxoci_ordinal982 TEXTEQU <__imp_mtxoci_ordinal982>
extern __imp_mtxoci_ordinal983:PANYARGS
mtxoci_ordinal983 TEXTEQU <__imp_mtxoci_ordinal983>
extern __imp_mtxoci_ordinal984:PANYARGS
mtxoci_ordinal984 TEXTEQU <__imp_mtxoci_ordinal984>
extern __imp_mtxoci_ordinal985:PANYARGS
mtxoci_ordinal985 TEXTEQU <__imp_mtxoci_ordinal985>
extern __imp_mtxoci_ordinal986:PANYARGS
mtxoci_ordinal986 TEXTEQU <__imp_mtxoci_ordinal986>
extern __imp_mtxoci_ordinal987:PANYARGS
mtxoci_ordinal987 TEXTEQU <__imp_mtxoci_ordinal987>
extern __imp_mtxoci_ordinal988:PANYARGS
mtxoci_ordinal988 TEXTEQU <__imp_mtxoci_ordinal988>
extern __imp_mtxoci_ordinal989:PANYARGS
mtxoci_ordinal989 TEXTEQU <__imp_mtxoci_ordinal989>
extern __imp_mtxoci_ordinal990:PANYARGS
mtxoci_ordinal990 TEXTEQU <__imp_mtxoci_ordinal990>
extern __imp_mtxoci_ordinal991:PANYARGS
mtxoci_ordinal991 TEXTEQU <__imp_mtxoci_ordinal991>
extern __imp_mtxoci_ordinal992:PANYARGS
mtxoci_ordinal992 TEXTEQU <__imp_mtxoci_ordinal992>
extern __imp_mtxoci_ordinal993:PANYARGS
mtxoci_ordinal993 TEXTEQU <__imp_mtxoci_ordinal993>
extern __imp_mtxoci_ordinal994:PANYARGS
mtxoci_ordinal994 TEXTEQU <__imp_mtxoci_ordinal994>
extern __imp_mtxoci_ordinal995:PANYARGS
mtxoci_ordinal995 TEXTEQU <__imp_mtxoci_ordinal995>
extern __imp_mtxoci_ordinal996:PANYARGS
mtxoci_ordinal996 TEXTEQU <__imp_mtxoci_ordinal996>
extern __imp_mtxoci_ordinal997:PANYARGS
mtxoci_ordinal997 TEXTEQU <__imp_mtxoci_ordinal997>
extern __imp_mtxoci_ordinal998:PANYARGS
mtxoci_ordinal998 TEXTEQU <__imp_mtxoci_ordinal998>
extern __imp_mtxoci_ordinal999:PANYARGS
mtxoci_ordinal999 TEXTEQU <__imp_mtxoci_ordinal999>
extern __imp_ologTransacted:PANYARGS
ologTransacted TEXTEQU <__imp_ologTransacted>
extern __imp_Enlist:PANYARGS
Enlist TEXTEQU <__imp_Enlist>
extern __imp_GetXaSwitch:PANYARGS
GetXaSwitch TEXTEQU <__imp_GetXaSwitch>
extern __imp_MTxOciInit:PANYARGS
MTxOciInit TEXTEQU <__imp_MTxOciInit>
extern __imp_MTxolog:PANYARGS
MTxolog TEXTEQU <__imp_MTxolog>
extern __imp_MTxOciGetVersion:PANYARGS
MTxOciGetVersion TEXTEQU <__imp_MTxOciGetVersion>
extern __imp_MTxOciRegisterCursor:PANYARGS
MTxOciRegisterCursor TEXTEQU <__imp_MTxOciRegisterCursor>
