extern __imp_?BackToApplication@@YAXXZ:PANYARGS
?BackToApplication@@YAXXZ TEXTEQU <__imp_?BackToApplication@@YAXXZ>
extern __imp_?GetAnnounceMenu@@YAHXZ:PANYARGS
?GetAnnounceMenu@@YAHXZ TEXTEQU <__imp_?GetAnnounceMenu@@YAHXZ>
extern __imp_?GetAnnouncePopup@@YAHXZ:PANYARGS
?GetAnnouncePopup@@YAHXZ TEXTEQU <__imp_?GetAnnouncePopup@@YAHXZ>
extern __imp_?GetAnnounceToolTips@@YAHXZ:PANYARGS
?GetAnnounceToolTips@@YAHXZ TEXTEQU <__imp_?GetAnnounceToolTips@@YAHXZ>
extern __imp_?GetAnnounceWindow@@YAHXZ:PANYARGS
?GetAnnounceWindow@@YAHXZ TEXTEQU <__imp_?GetAnnounceWindow@@YAHXZ>
extern __imp_?GetCurrentText@@YAXPEAGH@Z:PANYARGS
?GetCurrentText@@YAXPEAGH@Z TEXTEQU <__imp_?GetCurrentText@@YAXPEAGH@Z>
extern __imp_?GetEchoChars@@YAHXZ:PANYARGS
?GetEchoChars@@YAHXZ TEXTEQU <__imp_?GetEchoChars@@YAHXZ>
extern __imp_?GetReviewLevel@@YAHXZ:PANYARGS
?GetReviewLevel@@YAHXZ TEXTEQU <__imp_?GetReviewLevel@@YAHXZ>
extern __imp_?GetReviewStyle@@YAHXZ:PANYARGS
?GetReviewStyle@@YAHXZ TEXTEQU <__imp_?GetReviewStyle@@YAHXZ>
extern __imp_?GetTrackCaret@@YAHXZ:PANYARGS
?GetTrackCaret@@YAHXZ TEXTEQU <__imp_?GetTrackCaret@@YAHXZ>
extern __imp_?GetTrackInputFocus@@YAHXZ:PANYARGS
?GetTrackInputFocus@@YAHXZ TEXTEQU <__imp_?GetTrackInputFocus@@YAHXZ>
extern __imp_?GetTrackSecondary@@YAHXZ:PANYARGS
?GetTrackSecondary@@YAHXZ TEXTEQU <__imp_?GetTrackSecondary@@YAHXZ>
extern __imp_?InitKeys@@YAHPEAUHWND__@@@Z:PANYARGS
?InitKeys@@YAHPEAUHWND__@@@Z TEXTEQU <__imp_?InitKeys@@YAHPEAUHWND__@@@Z>
extern __imp_?InitMSAA@@YAHXZ:PANYARGS
?InitMSAA@@YAHXZ TEXTEQU <__imp_?InitMSAA@@YAHXZ>
extern __imp_?SetAnnounceMenu@@YAXH@Z:PANYARGS
?SetAnnounceMenu@@YAXH@Z TEXTEQU <__imp_?SetAnnounceMenu@@YAXH@Z>
extern __imp_?SetAnnouncePopup@@YAXH@Z:PANYARGS
?SetAnnouncePopup@@YAXH@Z TEXTEQU <__imp_?SetAnnouncePopup@@YAXH@Z>
extern __imp_?SetAnnounceToolTips@@YAXH@Z:PANYARGS
?SetAnnounceToolTips@@YAXH@Z TEXTEQU <__imp_?SetAnnounceToolTips@@YAXH@Z>
extern __imp_?SetAnnounceWindow@@YAXH@Z:PANYARGS
?SetAnnounceWindow@@YAXH@Z TEXTEQU <__imp_?SetAnnounceWindow@@YAXH@Z>
extern __imp_?SetCurrentText@@YAXPEBG@Z:PANYARGS
?SetCurrentText@@YAXPEBG@Z TEXTEQU <__imp_?SetCurrentText@@YAXPEBG@Z>
extern __imp_?SetEchoChars@@YAXH@Z:PANYARGS
?SetEchoChars@@YAXH@Z TEXTEQU <__imp_?SetEchoChars@@YAXH@Z>
extern __imp_?SetReviewLevel@@YAXH@Z:PANYARGS
?SetReviewLevel@@YAXH@Z TEXTEQU <__imp_?SetReviewLevel@@YAXH@Z>
extern __imp_?SetReviewStyle@@YAXH@Z:PANYARGS
?SetReviewStyle@@YAXH@Z TEXTEQU <__imp_?SetReviewStyle@@YAXH@Z>
extern __imp_?SetTrackCaret@@YAXH@Z:PANYARGS
?SetTrackCaret@@YAXH@Z TEXTEQU <__imp_?SetTrackCaret@@YAXH@Z>
extern __imp_?SetTrackInputFocus@@YAXH@Z:PANYARGS
?SetTrackInputFocus@@YAXH@Z TEXTEQU <__imp_?SetTrackInputFocus@@YAXH@Z>
extern __imp_?SetTrackSecondary@@YAXH@Z:PANYARGS
?SetTrackSecondary@@YAXH@Z TEXTEQU <__imp_?SetTrackSecondary@@YAXH@Z>
extern __imp_?UnInitMSAA@@YAHXZ:PANYARGS
?UnInitMSAA@@YAHXZ TEXTEQU <__imp_?UnInitMSAA@@YAHXZ>
extern __imp_?UninitKeys@@YAHXZ:PANYARGS
?UninitKeys@@YAHXZ TEXTEQU <__imp_?UninitKeys@@YAHXZ>
extern __imp_?lstrcatn@@YAPEAGPEAG0H@Z:PANYARGS
?lstrcatn@@YAPEAGPEAG0H@Z TEXTEQU <__imp_?lstrcatn@@YAPEAGPEAG0H@Z>
