extern __imp_EnableAutodial:PANYARGS
EnableAutodial TEXTEQU <__imp_EnableAutodial>
extern __imp_GetDefaultDialupConnection:PANYARGS
GetDefaultDialupConnection TEXTEQU <__imp_GetDefaultDialupConnection>
extern __imp_IsAutodialEnabled:PANYARGS
IsAutodialEnabled TEXTEQU <__imp_IsAutodialEnabled>
extern __imp_SetDefaultDialupConnection:PANYARGS
SetDefaultDialupConnection TEXTEQU <__imp_SetDefaultDialupConnection>
extern __imp_TestRunDll:PANYARGS
TestRunDll TEXTEQU <__imp_TestRunDll>
extern __imp_DisableUserLevelAccessControl:PANYARGS
DisableUserLevelAccessControl TEXTEQU <__imp_DisableUserLevelAccessControl>
extern __imp_EnumMatchingNetBindings:PANYARGS
EnumMatchingNetBindings TEXTEQU <__imp_EnumMatchingNetBindings>
extern __imp_EnumNetAdapters:PANYARGS
EnumNetAdapters TEXTEQU <__imp_EnumNetAdapters>
extern __imp_HrEnableDhcp:PANYARGS
HrEnableDhcp TEXTEQU <__imp_HrEnableDhcp>
extern __imp_HrFromLastWin32Error:PANYARGS
HrFromLastWin32Error TEXTEQU <__imp_HrFromLastWin32Error>
extern __imp_HrWideCharToMultiByte:PANYARGS
HrWideCharToMultiByte TEXTEQU <__imp_HrWideCharToMultiByte>
extern __imp_InstallMSClient:PANYARGS
InstallMSClient TEXTEQU <__imp_InstallMSClient>
extern __imp_InstallSharing:PANYARGS
InstallSharing TEXTEQU <__imp_InstallSharing>
extern __imp_InstallTCPIP:PANYARGS
InstallTCPIP TEXTEQU <__imp_InstallTCPIP>
extern __imp_IsAccessControlUserLevel:PANYARGS
IsAccessControlUserLevel TEXTEQU <__imp_IsAccessControlUserLevel>
extern __imp_IsAdapterDisconnected:PANYARGS
IsAdapterDisconnected TEXTEQU <__imp_IsAdapterDisconnected>
extern __imp_IsClientInstalled:PANYARGS
IsClientInstalled TEXTEQU <__imp_IsClientInstalled>
extern __imp_IsMSClientInstalled:PANYARGS
IsMSClientInstalled TEXTEQU <__imp_IsMSClientInstalled>
extern __imp_IsProtocolInstalled:PANYARGS
IsProtocolInstalled TEXTEQU <__imp_IsProtocolInstalled>
extern __imp_IsSharingInstalled:PANYARGS
IsSharingInstalled TEXTEQU <__imp_IsSharingInstalled>
extern __imp_NetConnAlloc:PANYARGS
NetConnAlloc TEXTEQU <__imp_NetConnAlloc>
extern __imp_NetConnFree:PANYARGS
NetConnFree TEXTEQU <__imp_NetConnFree>
extern __imp_RestartNetAdapter:PANYARGS
RestartNetAdapter TEXTEQU <__imp_RestartNetAdapter>
