extern __imp_NDdeShareAddA:PANYARGS
NDdeShareAdd  TEXTEQU <__imp_NDdeShareAddA>
extern __imp_NDdeShareDelA:PANYARGS
NDdeShareDel  TEXTEQU <__imp_NDdeShareDelA>
extern __imp_NDdeShareEnumA:PANYARGS
NDdeShareEnum  TEXTEQU <__imp_NDdeShareEnumA>
extern __imp_NDdeShareGetInfoA:PANYARGS
NDdeShareGetInfo  TEXTEQU <__imp_NDdeShareGetInfoA>
extern __imp_NDdeShareSetInfoA:PANYARGS
NDdeShareSetInfo  TEXTEQU <__imp_NDdeShareSetInfoA>
extern __imp_NDdeGetErrorStringA:PANYARGS
NDdeGetErrorString  TEXTEQU <__imp_NDdeGetErrorStringA>
extern __imp_NDdeIsValidShareNameA:PANYARGS
NDdeIsValidShareName  TEXTEQU <__imp_NDdeIsValidShareNameA>
extern __imp_NDdeIsValidAppTopicListA:PANYARGS
NDdeIsValidAppTopicList  TEXTEQU <__imp_NDdeIsValidAppTopicListA>
extern __imp_NDdeSpecialCommandA:PANYARGS
NDdeSpecialCommand  TEXTEQU <__imp_NDdeSpecialCommandA>
extern __imp_NDdeGetShareSecurityA:PANYARGS
NDdeGetShareSecurity  TEXTEQU <__imp_NDdeGetShareSecurityA>
extern __imp_NDdeSetShareSecurityA:PANYARGS
NDdeSetShareSecurity  TEXTEQU <__imp_NDdeSetShareSecurityA>
extern __imp_NDdeGetTrustedShareA:PANYARGS
NDdeGetTrustedShare  TEXTEQU <__imp_NDdeGetTrustedShareA>
extern __imp_NDdeSetTrustedShareA:PANYARGS
NDdeSetTrustedShare  TEXTEQU <__imp_NDdeSetTrustedShareA>
extern __imp_NDdeTrustedShareEnumA:PANYARGS
NDdeTrustedShareEnum  TEXTEQU <__imp_NDdeTrustedShareEnumA>
extern __imp_nddeapi_ordinal514:PANYARGS
nddeapi_ordinal514 TEXTEQU <__imp_nddeapi_ordinal514>
extern __imp_nddeapi_ordinal515:PANYARGS
nddeapi_ordinal515 TEXTEQU <__imp_nddeapi_ordinal515>
extern __imp_nddeapi_ordinal516:PANYARGS
nddeapi_ordinal516 TEXTEQU <__imp_nddeapi_ordinal516>
extern __imp_nddeapi_ordinal517:PANYARGS
nddeapi_ordinal517 TEXTEQU <__imp_nddeapi_ordinal517>
extern __imp_nddeapi_ordinal518:PANYARGS
nddeapi_ordinal518 TEXTEQU <__imp_nddeapi_ordinal518>
extern __imp_nddeapi_ordinal519:PANYARGS
nddeapi_ordinal519 TEXTEQU <__imp_nddeapi_ordinal519>
extern __imp_nddeapi_ordinal520:PANYARGS
nddeapi_ordinal520 TEXTEQU <__imp_nddeapi_ordinal520>
extern __imp_nddeapi_ordinal521:PANYARGS
nddeapi_ordinal521 TEXTEQU <__imp_nddeapi_ordinal521>
extern __imp_nddeapi_ordinal522:PANYARGS
nddeapi_ordinal522 TEXTEQU <__imp_nddeapi_ordinal522>
extern __imp_nddeapi_ordinal523:PANYARGS
nddeapi_ordinal523 TEXTEQU <__imp_nddeapi_ordinal523>
extern __imp_nddeapi_ordinal524:PANYARGS
nddeapi_ordinal524 TEXTEQU <__imp_nddeapi_ordinal524>
extern __imp_nddeapi_ordinal525:PANYARGS
nddeapi_ordinal525 TEXTEQU <__imp_nddeapi_ordinal525>
extern __imp_nddeapi_ordinal526:PANYARGS
nddeapi_ordinal526 TEXTEQU <__imp_nddeapi_ordinal526>
extern __imp_nddeapi_ordinal527:PANYARGS
nddeapi_ordinal527 TEXTEQU <__imp_nddeapi_ordinal527>
extern __imp_nddeapi_ordinal528:PANYARGS
nddeapi_ordinal528 TEXTEQU <__imp_nddeapi_ordinal528>
extern __imp_nddeapi_ordinal529:PANYARGS
nddeapi_ordinal529 TEXTEQU <__imp_nddeapi_ordinal529>
extern __imp_nddeapi_ordinal530:PANYARGS
nddeapi_ordinal530 TEXTEQU <__imp_nddeapi_ordinal530>
extern __imp_nddeapi_ordinal531:PANYARGS
nddeapi_ordinal531 TEXTEQU <__imp_nddeapi_ordinal531>
extern __imp_nddeapi_ordinal532:PANYARGS
nddeapi_ordinal532 TEXTEQU <__imp_nddeapi_ordinal532>
extern __imp_nddeapi_ordinal533:PANYARGS
nddeapi_ordinal533 TEXTEQU <__imp_nddeapi_ordinal533>
extern __imp_nddeapi_ordinal534:PANYARGS
nddeapi_ordinal534 TEXTEQU <__imp_nddeapi_ordinal534>
extern __imp_nddeapi_ordinal535:PANYARGS
nddeapi_ordinal535 TEXTEQU <__imp_nddeapi_ordinal535>
extern __imp_nddeapi_ordinal536:PANYARGS
nddeapi_ordinal536 TEXTEQU <__imp_nddeapi_ordinal536>
extern __imp_nddeapi_ordinal537:PANYARGS
nddeapi_ordinal537 TEXTEQU <__imp_nddeapi_ordinal537>
extern __imp_nddeapi_ordinal538:PANYARGS
nddeapi_ordinal538 TEXTEQU <__imp_nddeapi_ordinal538>
extern __imp_nddeapi_ordinal539:PANYARGS
nddeapi_ordinal539 TEXTEQU <__imp_nddeapi_ordinal539>
extern __imp_nddeapi_ordinal540:PANYARGS
nddeapi_ordinal540 TEXTEQU <__imp_nddeapi_ordinal540>
extern __imp_nddeapi_ordinal541:PANYARGS
nddeapi_ordinal541 TEXTEQU <__imp_nddeapi_ordinal541>
extern __imp_nddeapi_ordinal542:PANYARGS
nddeapi_ordinal542 TEXTEQU <__imp_nddeapi_ordinal542>
extern __imp_nddeapi_ordinal543:PANYARGS
nddeapi_ordinal543 TEXTEQU <__imp_nddeapi_ordinal543>
extern __imp_nddeapi_ordinal544:PANYARGS
nddeapi_ordinal544 TEXTEQU <__imp_nddeapi_ordinal544>
extern __imp_nddeapi_ordinal545:PANYARGS
nddeapi_ordinal545 TEXTEQU <__imp_nddeapi_ordinal545>
extern __imp_nddeapi_ordinal546:PANYARGS
nddeapi_ordinal546 TEXTEQU <__imp_nddeapi_ordinal546>
extern __imp_nddeapi_ordinal547:PANYARGS
nddeapi_ordinal547 TEXTEQU <__imp_nddeapi_ordinal547>
extern __imp_nddeapi_ordinal548:PANYARGS
nddeapi_ordinal548 TEXTEQU <__imp_nddeapi_ordinal548>
extern __imp_nddeapi_ordinal549:PANYARGS
nddeapi_ordinal549 TEXTEQU <__imp_nddeapi_ordinal549>
extern __imp_nddeapi_ordinal550:PANYARGS
nddeapi_ordinal550 TEXTEQU <__imp_nddeapi_ordinal550>
extern __imp_nddeapi_ordinal551:PANYARGS
nddeapi_ordinal551 TEXTEQU <__imp_nddeapi_ordinal551>
extern __imp_nddeapi_ordinal552:PANYARGS
nddeapi_ordinal552 TEXTEQU <__imp_nddeapi_ordinal552>
extern __imp_nddeapi_ordinal553:PANYARGS
nddeapi_ordinal553 TEXTEQU <__imp_nddeapi_ordinal553>
extern __imp_nddeapi_ordinal554:PANYARGS
nddeapi_ordinal554 TEXTEQU <__imp_nddeapi_ordinal554>
extern __imp_nddeapi_ordinal555:PANYARGS
nddeapi_ordinal555 TEXTEQU <__imp_nddeapi_ordinal555>
extern __imp_nddeapi_ordinal556:PANYARGS
nddeapi_ordinal556 TEXTEQU <__imp_nddeapi_ordinal556>
extern __imp_nddeapi_ordinal557:PANYARGS
nddeapi_ordinal557 TEXTEQU <__imp_nddeapi_ordinal557>
extern __imp_nddeapi_ordinal558:PANYARGS
nddeapi_ordinal558 TEXTEQU <__imp_nddeapi_ordinal558>
extern __imp_nddeapi_ordinal559:PANYARGS
nddeapi_ordinal559 TEXTEQU <__imp_nddeapi_ordinal559>
extern __imp_nddeapi_ordinal560:PANYARGS
nddeapi_ordinal560 TEXTEQU <__imp_nddeapi_ordinal560>
extern __imp_nddeapi_ordinal561:PANYARGS
nddeapi_ordinal561 TEXTEQU <__imp_nddeapi_ordinal561>
extern __imp_nddeapi_ordinal562:PANYARGS
nddeapi_ordinal562 TEXTEQU <__imp_nddeapi_ordinal562>
extern __imp_nddeapi_ordinal563:PANYARGS
nddeapi_ordinal563 TEXTEQU <__imp_nddeapi_ordinal563>
extern __imp_nddeapi_ordinal564:PANYARGS
nddeapi_ordinal564 TEXTEQU <__imp_nddeapi_ordinal564>
extern __imp_nddeapi_ordinal565:PANYARGS
nddeapi_ordinal565 TEXTEQU <__imp_nddeapi_ordinal565>
extern __imp_nddeapi_ordinal566:PANYARGS
nddeapi_ordinal566 TEXTEQU <__imp_nddeapi_ordinal566>
extern __imp_nddeapi_ordinal567:PANYARGS
nddeapi_ordinal567 TEXTEQU <__imp_nddeapi_ordinal567>
extern __imp_nddeapi_ordinal568:PANYARGS
nddeapi_ordinal568 TEXTEQU <__imp_nddeapi_ordinal568>
extern __imp_nddeapi_ordinal569:PANYARGS
nddeapi_ordinal569 TEXTEQU <__imp_nddeapi_ordinal569>
extern __imp_nddeapi_ordinal570:PANYARGS
nddeapi_ordinal570 TEXTEQU <__imp_nddeapi_ordinal570>
extern __imp_nddeapi_ordinal571:PANYARGS
nddeapi_ordinal571 TEXTEQU <__imp_nddeapi_ordinal571>
extern __imp_nddeapi_ordinal572:PANYARGS
nddeapi_ordinal572 TEXTEQU <__imp_nddeapi_ordinal572>
extern __imp_nddeapi_ordinal573:PANYARGS
nddeapi_ordinal573 TEXTEQU <__imp_nddeapi_ordinal573>
extern __imp_nddeapi_ordinal574:PANYARGS
nddeapi_ordinal574 TEXTEQU <__imp_nddeapi_ordinal574>
extern __imp_nddeapi_ordinal575:PANYARGS
nddeapi_ordinal575 TEXTEQU <__imp_nddeapi_ordinal575>
extern __imp_nddeapi_ordinal576:PANYARGS
nddeapi_ordinal576 TEXTEQU <__imp_nddeapi_ordinal576>
extern __imp_nddeapi_ordinal577:PANYARGS
nddeapi_ordinal577 TEXTEQU <__imp_nddeapi_ordinal577>
extern __imp_nddeapi_ordinal578:PANYARGS
nddeapi_ordinal578 TEXTEQU <__imp_nddeapi_ordinal578>
extern __imp_nddeapi_ordinal579:PANYARGS
nddeapi_ordinal579 TEXTEQU <__imp_nddeapi_ordinal579>
extern __imp_nddeapi_ordinal580:PANYARGS
nddeapi_ordinal580 TEXTEQU <__imp_nddeapi_ordinal580>
extern __imp_nddeapi_ordinal581:PANYARGS
nddeapi_ordinal581 TEXTEQU <__imp_nddeapi_ordinal581>
extern __imp_nddeapi_ordinal582:PANYARGS
nddeapi_ordinal582 TEXTEQU <__imp_nddeapi_ordinal582>
extern __imp_nddeapi_ordinal583:PANYARGS
nddeapi_ordinal583 TEXTEQU <__imp_nddeapi_ordinal583>
extern __imp_nddeapi_ordinal584:PANYARGS
nddeapi_ordinal584 TEXTEQU <__imp_nddeapi_ordinal584>
extern __imp_nddeapi_ordinal585:PANYARGS
nddeapi_ordinal585 TEXTEQU <__imp_nddeapi_ordinal585>
extern __imp_nddeapi_ordinal586:PANYARGS
nddeapi_ordinal586 TEXTEQU <__imp_nddeapi_ordinal586>
extern __imp_nddeapi_ordinal587:PANYARGS
nddeapi_ordinal587 TEXTEQU <__imp_nddeapi_ordinal587>
extern __imp_nddeapi_ordinal588:PANYARGS
nddeapi_ordinal588 TEXTEQU <__imp_nddeapi_ordinal588>
extern __imp_nddeapi_ordinal589:PANYARGS
nddeapi_ordinal589 TEXTEQU <__imp_nddeapi_ordinal589>
extern __imp_nddeapi_ordinal590:PANYARGS
nddeapi_ordinal590 TEXTEQU <__imp_nddeapi_ordinal590>
extern __imp_nddeapi_ordinal591:PANYARGS
nddeapi_ordinal591 TEXTEQU <__imp_nddeapi_ordinal591>
extern __imp_nddeapi_ordinal592:PANYARGS
nddeapi_ordinal592 TEXTEQU <__imp_nddeapi_ordinal592>
extern __imp_nddeapi_ordinal593:PANYARGS
nddeapi_ordinal593 TEXTEQU <__imp_nddeapi_ordinal593>
extern __imp_nddeapi_ordinal594:PANYARGS
nddeapi_ordinal594 TEXTEQU <__imp_nddeapi_ordinal594>
extern __imp_nddeapi_ordinal595:PANYARGS
nddeapi_ordinal595 TEXTEQU <__imp_nddeapi_ordinal595>
extern __imp_nddeapi_ordinal596:PANYARGS
nddeapi_ordinal596 TEXTEQU <__imp_nddeapi_ordinal596>
extern __imp_nddeapi_ordinal597:PANYARGS
nddeapi_ordinal597 TEXTEQU <__imp_nddeapi_ordinal597>
extern __imp_nddeapi_ordinal598:PANYARGS
nddeapi_ordinal598 TEXTEQU <__imp_nddeapi_ordinal598>
extern __imp_nddeapi_ordinal599:PANYARGS
nddeapi_ordinal599 TEXTEQU <__imp_nddeapi_ordinal599>
extern __imp_NDdeShareAddW:PANYARGS
NDdeShareAddW TEXTEQU <__imp_NDdeShareAddW>
extern __imp_NDdeShareDelW:PANYARGS
NDdeShareDelW TEXTEQU <__imp_NDdeShareDelW>
extern __imp_NDdeShareEnumW:PANYARGS
NDdeShareEnumW TEXTEQU <__imp_NDdeShareEnumW>
extern __imp_NDdeShareGetInfoW:PANYARGS
NDdeShareGetInfoW TEXTEQU <__imp_NDdeShareGetInfoW>
extern __imp_NDdeShareSetInfoW:PANYARGS
NDdeShareSetInfoW TEXTEQU <__imp_NDdeShareSetInfoW>
extern __imp_NDdeGetErrorStringW:PANYARGS
NDdeGetErrorStringW TEXTEQU <__imp_NDdeGetErrorStringW>
extern __imp_NDdeIsValidShareNameW:PANYARGS
NDdeIsValidShareNameW TEXTEQU <__imp_NDdeIsValidShareNameW>
extern __imp_NDdeIsValidAppTopicListW:PANYARGS
NDdeIsValidAppTopicListW TEXTEQU <__imp_NDdeIsValidAppTopicListW>
extern __imp_NDdeSpecialCommandW:PANYARGS
NDdeSpecialCommandW TEXTEQU <__imp_NDdeSpecialCommandW>
extern __imp_NDdeGetShareSecurityW:PANYARGS
NDdeGetShareSecurityW TEXTEQU <__imp_NDdeGetShareSecurityW>
extern __imp_NDdeSetShareSecurityW:PANYARGS
NDdeSetShareSecurityW TEXTEQU <__imp_NDdeSetShareSecurityW>
extern __imp_NDdeGetTrustedShareW:PANYARGS
NDdeGetTrustedShareW TEXTEQU <__imp_NDdeGetTrustedShareW>
extern __imp_NDdeSetTrustedShareW:PANYARGS
NDdeSetTrustedShareW TEXTEQU <__imp_NDdeSetTrustedShareW>
extern __imp_NDdeTrustedShareEnumW:PANYARGS
NDdeTrustedShareEnumW TEXTEQU <__imp_NDdeTrustedShareEnumW>
