extern __imp_NDDEInit:PANYARGS
NDDEInit TEXTEQU <__imp_NDDEInit>
extern __imp_NDDEGetCAPS:PANYARGS
NDDEGetCAPS TEXTEQU <__imp_NDDEGetCAPS>
extern __imp_NDDEGetNewConnection:PANYARGS
NDDEGetNewConnection TEXTEQU <__imp_NDDEGetNewConnection>
extern __imp_NDDEAddConnection:PANYARGS
NDDEAddConnection TEXTEQU <__imp_NDDEAddConnection>
extern __imp_NDDEDeleteConnection:PANYARGS
NDDEDeleteConnection TEXTEQU <__imp_NDDEDeleteConnection>
extern __imp_NDDEGetConnectionStatus:PANYARGS
NDDEGetConnectionStatus TEXTEQU <__imp_NDDEGetConnectionStatus>
extern __imp_NDDERcvPacket:PANYARGS
NDDERcvPacket TEXTEQU <__imp_NDDERcvPacket>
extern __imp_NDDEXmtPacket:PANYARGS
NDDEXmtPacket TEXTEQU <__imp_NDDEXmtPacket>
extern __imp_NDDESetConnectionConfig:PANYARGS
NDDESetConnectionConfig TEXTEQU <__imp_NDDESetConnectionConfig>
extern __imp_NDDEShutdown:PANYARGS
NDDEShutdown TEXTEQU <__imp_NDDEShutdown>
extern __imp_NDDETimeSlice:PANYARGS
NDDETimeSlice TEXTEQU <__imp_NDDETimeSlice>
extern __imp_NDDEGetConnectionConfig:PANYARGS
NDDEGetConnectionConfig TEXTEQU <__imp_NDDEGetConnectionConfig>
extern __imp_Configure:PANYARGS
Configure TEXTEQU <__imp_Configure>
extern __imp_LogDebugInfo:PANYARGS
LogDebugInfo TEXTEQU <__imp_LogDebugInfo>
extern __imp_ConfigureDlgProc:PANYARGS
ConfigureDlgProc TEXTEQU <__imp_ConfigureDlgProc>
