extern __imp_??4WLBS_REG_PARAMS@@QEAAAEAU0@AEBU0@@Z:PANYARGS
??4WLBS_REG_PARAMS@@QEAAAEAU0@AEBU0@@Z TEXTEQU <__imp_??4WLBS_REG_PARAMS@@QEAAAEAU0@AEBU0@@Z>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_HrDiAddComponentToINetCfg:PANYARGS
HrDiAddComponentToINetCfg TEXTEQU <__imp_HrDiAddComponentToINetCfg>
extern __imp_LanaCfgFromCommandArgs:PANYARGS
LanaCfgFromCommandArgs TEXTEQU <__imp_LanaCfgFromCommandArgs>
extern __imp_ModemClassCoInstaller:PANYARGS
ModemClassCoInstaller TEXTEQU <__imp_ModemClassCoInstaller>
extern __imp_NetCfgDiagFromCommandArgs:PANYARGS
NetCfgDiagFromCommandArgs TEXTEQU <__imp_NetCfgDiagFromCommandArgs>
extern __imp_NetCfgDiagRepairRegistryBindings:PANYARGS
NetCfgDiagRepairRegistryBindings TEXTEQU <__imp_NetCfgDiagRepairRegistryBindings>
extern __imp_NetClassInstaller:PANYARGS
NetClassInstaller TEXTEQU <__imp_NetClassInstaller>
extern __imp_NetPropPageProvider:PANYARGS
NetPropPageProvider TEXTEQU <__imp_NetPropPageProvider>
extern __imp_RasAddBindings:PANYARGS
RasAddBindings TEXTEQU <__imp_RasAddBindings>
extern __imp_RasCountBindings:PANYARGS
RasCountBindings TEXTEQU <__imp_RasCountBindings>
extern __imp_RasRemoveBindings:PANYARGS
RasRemoveBindings TEXTEQU <__imp_RasRemoveBindings>
extern __imp_SvchostChangeSvchostGroup:PANYARGS
SvchostChangeSvchostGroup TEXTEQU <__imp_SvchostChangeSvchostGroup>
extern __imp_UpdateLanaConfigUsingAnswerfile:PANYARGS
UpdateLanaConfigUsingAnswerfile TEXTEQU <__imp_UpdateLanaConfigUsingAnswerfile>
