extern __imp_AddNetPlaceRunDll:PANYARGS
AddNetPlaceRunDll TEXTEQU <__imp_AddNetPlaceRunDll>
extern __imp_PassportWizardRunDll:PANYARGS
PassportWizardRunDll TEXTEQU <__imp_PassportWizardRunDll>
extern __imp_PublishRunDll:PANYARGS
PublishRunDll TEXTEQU <__imp_PublishRunDll>
extern __imp_UsersRunDll:PANYARGS
UsersRunDll TEXTEQU <__imp_UsersRunDll>
extern __imp_ClearAutoLogon:PANYARGS
ClearAutoLogon TEXTEQU <__imp_ClearAutoLogon>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_NetAccessWizard:PANYARGS
NetAccessWizard TEXTEQU <__imp_NetAccessWizard>
extern __imp_NetPlacesWizardDoModal:PANYARGS
NetPlacesWizardDoModal TEXTEQU <__imp_NetPlacesWizardDoModal>
extern __imp_SHDisconnectNetDrives:PANYARGS
SHDisconnectNetDrives TEXTEQU <__imp_SHDisconnectNetDrives>
