extern __imp_RapArrayLength:PANYARGS
RapArrayLength TEXTEQU <__imp_RapArrayLength>
extern __imp_RapAsciiToDecimal:PANYARGS
RapAsciiToDecimal TEXTEQU <__imp_RapAsciiToDecimal>
extern __imp_RapAuxDataCount:PANYARGS
RapAuxDataCount TEXTEQU <__imp_RapAuxDataCount>
extern __imp_RapAuxDataCountOffset:PANYARGS
RapAuxDataCountOffset TEXTEQU <__imp_RapAuxDataCountOffset>
extern __imp_RapConvertSingleEntry:PANYARGS
RapConvertSingleEntry TEXTEQU <__imp_RapConvertSingleEntry>
extern __imp_RapConvertSingleEntryEx:PANYARGS
RapConvertSingleEntryEx TEXTEQU <__imp_RapConvertSingleEntryEx>
extern __imp_RapExamineDescriptor:PANYARGS
RapExamineDescriptor TEXTEQU <__imp_RapExamineDescriptor>
extern __imp_RapGetFieldSize:PANYARGS
RapGetFieldSize TEXTEQU <__imp_RapGetFieldSize>
extern __imp_RapIsValidDescriptorSmb:PANYARGS
RapIsValidDescriptorSmb TEXTEQU <__imp_RapIsValidDescriptorSmb>
extern __imp_RapLastPointerOffset:PANYARGS
RapLastPointerOffset TEXTEQU <__imp_RapLastPointerOffset>
extern __imp_RapParmNumDescriptor:PANYARGS
RapParmNumDescriptor TEXTEQU <__imp_RapParmNumDescriptor>
extern __imp_RapStructureAlignment:PANYARGS
RapStructureAlignment TEXTEQU <__imp_RapStructureAlignment>
extern __imp_RapStructureSize:PANYARGS
RapStructureSize TEXTEQU <__imp_RapStructureSize>
extern __imp_RapTotalSize:PANYARGS
RapTotalSize TEXTEQU <__imp_RapTotalSize>
