extern __imp_ConvertGuidToString:PANYARGS
ConvertGuidToString TEXTEQU <__imp_ConvertGuidToString>
extern __imp_ConvertStringToGuid:PANYARGS
ConvertStringToGuid TEXTEQU <__imp_ConvertStringToGuid>
extern __imp_DisplayMessageM:PANYARGS
DisplayMessageM TEXTEQU <__imp_DisplayMessageM>
extern __imp_DisplayMessageToConsole:PANYARGS
DisplayMessageToConsole TEXTEQU <__imp_DisplayMessageToConsole>
extern __imp_FreeQuotedString:PANYARGS
FreeQuotedString TEXTEQU <__imp_FreeQuotedString>
extern __imp_FreeString:PANYARGS
FreeString TEXTEQU <__imp_FreeString>
extern __imp_GenericMonitor:PANYARGS
GenericMonitor TEXTEQU <__imp_GenericMonitor>
extern __imp_GetEnumString:PANYARGS
GetEnumString TEXTEQU <__imp_GetEnumString>
extern __imp_GetHostMachineInfo:PANYARGS
GetHostMachineInfo TEXTEQU <__imp_GetHostMachineInfo>
extern __imp_InitializeConsole:PANYARGS
InitializeConsole TEXTEQU <__imp_InitializeConsole>
extern __imp_MakeQuotedString:PANYARGS
MakeQuotedString TEXTEQU <__imp_MakeQuotedString>
extern __imp_MakeString:PANYARGS
MakeString TEXTEQU <__imp_MakeString>
extern __imp_MatchCmdLine:PANYARGS
MatchCmdLine TEXTEQU <__imp_MatchCmdLine>
extern __imp_MatchEnumTag:PANYARGS
MatchEnumTag TEXTEQU <__imp_MatchEnumTag>
extern __imp_MatchTagsInCmdLine:PANYARGS
MatchTagsInCmdLine TEXTEQU <__imp_MatchTagsInCmdLine>
extern __imp_MatchToken:PANYARGS
MatchToken TEXTEQU <__imp_MatchToken>
extern __imp_NsGetFriendlyNameFromIfName:PANYARGS
NsGetFriendlyNameFromIfName TEXTEQU <__imp_NsGetFriendlyNameFromIfName>
extern __imp_NsGetIfNameFromFriendlyName:PANYARGS
NsGetIfNameFromFriendlyName TEXTEQU <__imp_NsGetIfNameFromFriendlyName>
extern __imp_PreprocessCommand:PANYARGS
PreprocessCommand TEXTEQU <__imp_PreprocessCommand>
extern __imp_PrintError:PANYARGS
PrintError TEXTEQU <__imp_PrintError>
extern __imp_PrintMessage:PANYARGS
PrintMessage TEXTEQU <__imp_PrintMessage>
extern __imp_PrintMessageFromModule:PANYARGS
PrintMessageFromModule TEXTEQU <__imp_PrintMessageFromModule>
extern __imp_ProcessCommand:PANYARGS
ProcessCommand TEXTEQU <__imp_ProcessCommand>
extern __imp_RefreshConsole:PANYARGS
RefreshConsole TEXTEQU <__imp_RefreshConsole>
extern __imp_RegisterContext:PANYARGS
RegisterContext TEXTEQU <__imp_RegisterContext>
extern __imp_RegisterHelper:PANYARGS
RegisterHelper TEXTEQU <__imp_RegisterHelper>
