extern __imp_ClearEventData:PANYARGS
ClearEventData TEXTEQU <__imp_ClearEventData>
extern __imp_ReleaseEventSystem:PANYARGS
ReleaseEventSystem TEXTEQU <__imp_ReleaseEventSystem>
extern __imp_SendEvent:PANYARGS
SendEvent TEXTEQU <__imp_SendEvent>
extern __imp_ConvertHexStringToWString:PANYARGS
ConvertHexStringToWString TEXTEQU <__imp_ConvertHexStringToWString>
extern __imp_ConvertWStringToHexString:PANYARGS
ConvertWStringToHexString TEXTEQU <__imp_ConvertWStringToHexString>
extern __imp_CreateBlob:PANYARGS
CreateBlob TEXTEQU <__imp_CreateBlob>
extern __imp_CreateNPPInterface:PANYARGS
CreateNPPInterface TEXTEQU <__imp_CreateNPPInterface>
extern __imp_DestroyBlob:PANYARGS
DestroyBlob TEXTEQU <__imp_DestroyBlob>
extern __imp_DuplicateBlob:PANYARGS
DuplicateBlob TEXTEQU <__imp_DuplicateBlob>
extern __imp_FilterNPPBlob:PANYARGS
FilterNPPBlob TEXTEQU <__imp_FilterNPPBlob>
extern __imp_FindOneOf:PANYARGS
FindOneOf TEXTEQU <__imp_FindOneOf>
extern __imp_FindUnknownBlobCategories:PANYARGS
FindUnknownBlobCategories TEXTEQU <__imp_FindUnknownBlobCategories>
extern __imp_FindUnknownBlobTags:PANYARGS
FindUnknownBlobTags TEXTEQU <__imp_FindUnknownBlobTags>
extern __imp_GetBoolFromBlob:PANYARGS
GetBoolFromBlob TEXTEQU <__imp_GetBoolFromBlob>
extern __imp_GetClassIDFromBlob:PANYARGS
GetClassIDFromBlob TEXTEQU <__imp_GetClassIDFromBlob>
extern __imp_GetDwordFromBlob:PANYARGS
GetDwordFromBlob TEXTEQU <__imp_GetDwordFromBlob>
extern __imp_GetMacAddressFromBlob:PANYARGS
GetMacAddressFromBlob TEXTEQU <__imp_GetMacAddressFromBlob>
extern __imp_GetNPPAddress2FilterFromBlob:PANYARGS
GetNPPAddress2FilterFromBlob TEXTEQU <__imp_GetNPPAddress2FilterFromBlob>
extern __imp_GetNPPAddressFilterFromBlob:PANYARGS
GetNPPAddressFilterFromBlob TEXTEQU <__imp_GetNPPAddressFilterFromBlob>
extern __imp_GetNPPBlobFromUI:PANYARGS
GetNPPBlobFromUI TEXTEQU <__imp_GetNPPBlobFromUI>
extern __imp_GetNPPBlobTable:PANYARGS
GetNPPBlobTable TEXTEQU <__imp_GetNPPBlobTable>
extern __imp_GetNPPEtypeSapFilter:PANYARGS
GetNPPEtypeSapFilter TEXTEQU <__imp_GetNPPEtypeSapFilter>
extern __imp_GetNPPMacTypeAsNumber:PANYARGS
GetNPPMacTypeAsNumber TEXTEQU <__imp_GetNPPMacTypeAsNumber>
extern __imp_GetNPPPatternFilterFromBlob:PANYARGS
GetNPPPatternFilterFromBlob TEXTEQU <__imp_GetNPPPatternFilterFromBlob>
extern __imp_GetNPPTriggerFromBlob:PANYARGS
GetNPPTriggerFromBlob TEXTEQU <__imp_GetNPPTriggerFromBlob>
extern __imp_GetNetworkInfoFromBlob:PANYARGS
GetNetworkInfoFromBlob TEXTEQU <__imp_GetNetworkInfoFromBlob>
extern __imp_GetStringFromBlob:PANYARGS
GetStringFromBlob TEXTEQU <__imp_GetStringFromBlob>
extern __imp_GetStringsFromBlob:PANYARGS
GetStringsFromBlob TEXTEQU <__imp_GetStringsFromBlob>
extern __imp_GetWStringFromBlob:PANYARGS
GetWStringFromBlob TEXTEQU <__imp_GetWStringFromBlob>
extern __imp_IsRemoteNPP:PANYARGS
IsRemoteNPP TEXTEQU <__imp_IsRemoteNPP>
extern __imp_LockBlob:PANYARGS
LockBlob TEXTEQU <__imp_LockBlob>
extern __imp_MarshalBlob:PANYARGS
MarshalBlob TEXTEQU <__imp_MarshalBlob>
extern __imp_MergeBlob:PANYARGS
MergeBlob TEXTEQU <__imp_MergeBlob>
extern __imp_NmAddUsedEntry:PANYARGS
NmAddUsedEntry TEXTEQU <__imp_NmAddUsedEntry>
extern __imp_NmHeapAllocate:PANYARGS
NmHeapAllocate TEXTEQU <__imp_NmHeapAllocate>
extern __imp_NmHeapFree:PANYARGS
NmHeapFree TEXTEQU <__imp_NmHeapFree>
extern __imp_NmHeapReallocate:PANYARGS
NmHeapReallocate TEXTEQU <__imp_NmHeapReallocate>
extern __imp_NmHeapSetMaxSize:PANYARGS
NmHeapSetMaxSize TEXTEQU <__imp_NmHeapSetMaxSize>
extern __imp_NmHeapSize:PANYARGS
NmHeapSize TEXTEQU <__imp_NmHeapSize>
extern __imp_NmRemoveUsedEntry:PANYARGS
NmRemoveUsedEntry TEXTEQU <__imp_NmRemoveUsedEntry>
extern __imp_RaiseNMEvent:PANYARGS
RaiseNMEvent TEXTEQU <__imp_RaiseNMEvent>
extern __imp_ReadBlobFromFile:PANYARGS
ReadBlobFromFile TEXTEQU <__imp_ReadBlobFromFile>
extern __imp_RegCreateBlobKey:PANYARGS
RegCreateBlobKey TEXTEQU <__imp_RegCreateBlobKey>
extern __imp_RegOpenBlobKey:PANYARGS
RegOpenBlobKey TEXTEQU <__imp_RegOpenBlobKey>
extern __imp_RemoveFromBlob:PANYARGS
RemoveFromBlob TEXTEQU <__imp_RemoveFromBlob>
extern __imp_SelectNPPBlobFromTable:PANYARGS
SelectNPPBlobFromTable TEXTEQU <__imp_SelectNPPBlobFromTable>
extern __imp_SetBoolInBlob:PANYARGS
SetBoolInBlob TEXTEQU <__imp_SetBoolInBlob>
extern __imp_SetClassIDInBlob:PANYARGS
SetClassIDInBlob TEXTEQU <__imp_SetClassIDInBlob>
extern __imp_SetDwordInBlob:PANYARGS
SetDwordInBlob TEXTEQU <__imp_SetDwordInBlob>
extern __imp_SetMacAddressInBlob:PANYARGS
SetMacAddressInBlob TEXTEQU <__imp_SetMacAddressInBlob>
extern __imp_SetNPPAddress2FilterInBlob:PANYARGS
SetNPPAddress2FilterInBlob TEXTEQU <__imp_SetNPPAddress2FilterInBlob>
extern __imp_SetNPPAddressFilterInBlob:PANYARGS
SetNPPAddressFilterInBlob TEXTEQU <__imp_SetNPPAddressFilterInBlob>
extern __imp_SetNPPEtypeSapFilter:PANYARGS
SetNPPEtypeSapFilter TEXTEQU <__imp_SetNPPEtypeSapFilter>
extern __imp_SetNPPPatternFilterInBlob:PANYARGS
SetNPPPatternFilterInBlob TEXTEQU <__imp_SetNPPPatternFilterInBlob>
extern __imp_SetNPPTriggerInBlob:PANYARGS
SetNPPTriggerInBlob TEXTEQU <__imp_SetNPPTriggerInBlob>
extern __imp_SetNetworkInfoInBlob:PANYARGS
SetNetworkInfoInBlob TEXTEQU <__imp_SetNetworkInfoInBlob>
extern __imp_SetStringInBlob:PANYARGS
SetStringInBlob TEXTEQU <__imp_SetStringInBlob>
extern __imp_SetWStringInBlob:PANYARGS
SetWStringInBlob TEXTEQU <__imp_SetWStringInBlob>
extern __imp_SubkeyExists:PANYARGS
SubkeyExists TEXTEQU <__imp_SubkeyExists>
extern __imp_UnMarshalBlob:PANYARGS
UnMarshalBlob TEXTEQU <__imp_UnMarshalBlob>
extern __imp_UnlockBlob:PANYARGS
UnlockBlob TEXTEQU <__imp_UnlockBlob>
extern __imp_WriteBlobToFile:PANYARGS
WriteBlobToFile TEXTEQU <__imp_WriteBlobToFile>
extern __imp_WriteCrackedBlobToFile:PANYARGS
WriteCrackedBlobToFile TEXTEQU <__imp_WriteCrackedBlobToFile>
extern __imp_recursiveDeleteKey:PANYARGS
recursiveDeleteKey TEXTEQU <__imp_recursiveDeleteKey>
extern __imp_setKeyAndValue:PANYARGS
setKeyAndValue TEXTEQU <__imp_setKeyAndValue>
