extern __imp_DsBackupClose:PANYARGS
DsBackupClose TEXTEQU <__imp_DsBackupClose>
extern __imp_DsBackupEnd:PANYARGS
DsBackupEnd TEXTEQU <__imp_DsBackupEnd>
extern __imp_DsBackupFree:PANYARGS
DsBackupFree TEXTEQU <__imp_DsBackupFree>
extern __imp_DsBackupGetBackupLogsA:PANYARGS
DsBackupGetBackupLogs  TEXTEQU <__imp_DsBackupGetBackupLogsA>
extern __imp_DsBackupGetBackupLogsW:PANYARGS
DsBackupGetBackupLogsW TEXTEQU <__imp_DsBackupGetBackupLogsW>
extern __imp_DsBackupGetDatabaseNamesA:PANYARGS
DsBackupGetDatabaseNames  TEXTEQU <__imp_DsBackupGetDatabaseNamesA>
extern __imp_DsBackupGetDatabaseNamesW:PANYARGS
DsBackupGetDatabaseNamesW TEXTEQU <__imp_DsBackupGetDatabaseNamesW>
extern __imp_DsBackupOpenFileA:PANYARGS
DsBackupOpenFile  TEXTEQU <__imp_DsBackupOpenFileA>
extern __imp_DsBackupOpenFileW:PANYARGS
DsBackupOpenFileW TEXTEQU <__imp_DsBackupOpenFileW>
extern __imp_DsBackupPrepareA:PANYARGS
DsBackupPrepare  TEXTEQU <__imp_DsBackupPrepareA>
extern __imp_DsBackupPrepareW:PANYARGS
DsBackupPrepareW TEXTEQU <__imp_DsBackupPrepareW>
extern __imp_DsBackupRead:PANYARGS
DsBackupRead TEXTEQU <__imp_DsBackupRead>
extern __imp_DsBackupTruncateLogs:PANYARGS
DsBackupTruncateLogs TEXTEQU <__imp_DsBackupTruncateLogs>
extern __imp_DsIsNTDSOnlineA:PANYARGS
DsIsNTDSOnline  TEXTEQU <__imp_DsIsNTDSOnlineA>
extern __imp_DsIsNTDSOnlineW:PANYARGS
DsIsNTDSOnlineW TEXTEQU <__imp_DsIsNTDSOnlineW>
extern __imp_DsRestoreCheckExpiryToken:PANYARGS
DsRestoreCheckExpiryToken TEXTEQU <__imp_DsRestoreCheckExpiryToken>
extern __imp_DsRestoreEnd:PANYARGS
DsRestoreEnd TEXTEQU <__imp_DsRestoreEnd>
extern __imp_DsRestoreGetDatabaseLocationsA:PANYARGS
DsRestoreGetDatabaseLocations  TEXTEQU <__imp_DsRestoreGetDatabaseLocationsA>
extern __imp_DsRestoreGetDatabaseLocationsW:PANYARGS
DsRestoreGetDatabaseLocationsW TEXTEQU <__imp_DsRestoreGetDatabaseLocationsW>
extern __imp_DsRestorePrepareA:PANYARGS
DsRestorePrepare  TEXTEQU <__imp_DsRestorePrepareA>
extern __imp_DsRestorePrepareW:PANYARGS
DsRestorePrepareW TEXTEQU <__imp_DsRestorePrepareW>
extern __imp_DsRestoreRegisterA:PANYARGS
DsRestoreRegister  TEXTEQU <__imp_DsRestoreRegisterA>
extern __imp_DsRestoreRegisterComplete:PANYARGS
DsRestoreRegisterComplete TEXTEQU <__imp_DsRestoreRegisterComplete>
extern __imp_DsRestoreRegisterW:PANYARGS
DsRestoreRegisterW TEXTEQU <__imp_DsRestoreRegisterW>
extern __imp_DsSetAuthIdentityA:PANYARGS
DsSetAuthIdentity  TEXTEQU <__imp_DsSetAuthIdentityA>
extern __imp_DsSetAuthIdentityW:PANYARGS
DsSetAuthIdentityW TEXTEQU <__imp_DsSetAuthIdentityW>
extern __imp_DsSetCurrentBackupLogA:PANYARGS
DsSetCurrentBackupLog  TEXTEQU <__imp_DsSetCurrentBackupLogA>
extern __imp_DsSetCurrentBackupLogW:PANYARGS
DsSetCurrentBackupLogW TEXTEQU <__imp_DsSetCurrentBackupLogW>
