extern __imp_DsAddSidHistoryA:PANYARGS
DsAddSidHistory  TEXTEQU <__imp_DsAddSidHistoryA>
extern __imp_DsAddSidHistoryW:PANYARGS
DsAddSidHistoryW TEXTEQU <__imp_DsAddSidHistoryW>
extern __imp_DsBindA:PANYARGS
DsBind  TEXTEQU <__imp_DsBindA>
extern __imp_DsBindToISTGA:PANYARGS
DsBindToISTG  TEXTEQU <__imp_DsBindToISTGA>
extern __imp_DsBindToISTGW:PANYARGS
DsBindToISTGW TEXTEQU <__imp_DsBindToISTGW>
extern __imp_DsBindW:PANYARGS
DsBindW TEXTEQU <__imp_DsBindW>
extern __imp_DsBindWithCredA:PANYARGS
DsBindWithCred  TEXTEQU <__imp_DsBindWithCredA>
extern __imp_DsBindWithCredW:PANYARGS
DsBindWithCredW TEXTEQU <__imp_DsBindWithCredW>
extern __imp_DsBindWithSpnA:PANYARGS
DsBindWithSpn  TEXTEQU <__imp_DsBindWithSpnA>
extern __imp_DsBindWithSpnExA:PANYARGS
DsBindWithSpnEx  TEXTEQU <__imp_DsBindWithSpnExA>
extern __imp_DsBindWithSpnExW:PANYARGS
DsBindWithSpnExW TEXTEQU <__imp_DsBindWithSpnExW>
extern __imp_DsBindWithSpnW:PANYARGS
DsBindWithSpnW TEXTEQU <__imp_DsBindWithSpnW>
extern __imp_DsBindingSetTimeout:PANYARGS
DsBindingSetTimeout TEXTEQU <__imp_DsBindingSetTimeout>
extern __imp_DsClientMakeSpnForTargetServerA:PANYARGS
DsClientMakeSpnForTargetServer  TEXTEQU <__imp_DsClientMakeSpnForTargetServerA>
extern __imp_DsClientMakeSpnForTargetServerW:PANYARGS
DsClientMakeSpnForTargetServerW TEXTEQU <__imp_DsClientMakeSpnForTargetServerW>
extern __imp_DsCrackNamesA:PANYARGS
DsCrackNames  TEXTEQU <__imp_DsCrackNamesA>
extern __imp_DsCrackNamesW:PANYARGS
DsCrackNamesW TEXTEQU <__imp_DsCrackNamesW>
extern __imp_DsCrackSpn2A:PANYARGS
DsCrackSpn2  TEXTEQU <__imp_DsCrackSpn2A>
extern __imp_DsCrackSpn2W:PANYARGS
DsCrackSpn2W TEXTEQU <__imp_DsCrackSpn2W>
extern __imp_DsCrackSpn3W:PANYARGS
DsCrackSpn3W TEXTEQU <__imp_DsCrackSpn3W>
extern __imp_DsCrackSpnA:PANYARGS
DsCrackSpn  TEXTEQU <__imp_DsCrackSpnA>
extern __imp_DsCrackSpnW:PANYARGS
DsCrackSpnW TEXTEQU <__imp_DsCrackSpnW>
extern __imp_DsCrackUnquotedMangledRdnA:PANYARGS
DsCrackUnquotedMangledRdn  TEXTEQU <__imp_DsCrackUnquotedMangledRdnA>
extern __imp_DsCrackUnquotedMangledRdnW:PANYARGS
DsCrackUnquotedMangledRdnW TEXTEQU <__imp_DsCrackUnquotedMangledRdnW>
extern __imp_DsFreeDomainControllerInfoA:PANYARGS
DsFreeDomainControllerInfo  TEXTEQU <__imp_DsFreeDomainControllerInfoA>
extern __imp_DsFreeDomainControllerInfoW:PANYARGS
DsFreeDomainControllerInfoW TEXTEQU <__imp_DsFreeDomainControllerInfoW>
extern __imp_DsFreeNameResultA:PANYARGS
DsFreeNameResult  TEXTEQU <__imp_DsFreeNameResultA>
extern __imp_DsFreeNameResultW:PANYARGS
DsFreeNameResultW TEXTEQU <__imp_DsFreeNameResultW>
extern __imp_DsFreePasswordCredentials:PANYARGS
DsFreePasswordCredentials TEXTEQU <__imp_DsFreePasswordCredentials>
extern __imp_DsFreeSchemaGuidMapA:PANYARGS
DsFreeSchemaGuidMap  TEXTEQU <__imp_DsFreeSchemaGuidMapA>
extern __imp_DsFreeSchemaGuidMapW:PANYARGS
DsFreeSchemaGuidMapW TEXTEQU <__imp_DsFreeSchemaGuidMapW>
extern __imp_DsFreeSpnArrayA:PANYARGS
DsFreeSpnArray  TEXTEQU <__imp_DsFreeSpnArrayA>
extern __imp_DsFreeSpnArrayW:PANYARGS
DsFreeSpnArrayW TEXTEQU <__imp_DsFreeSpnArrayW>
extern __imp_DsGetDomainControllerInfoA:PANYARGS
DsGetDomainControllerInfo  TEXTEQU <__imp_DsGetDomainControllerInfoA>
extern __imp_DsGetDomainControllerInfoW:PANYARGS
DsGetDomainControllerInfoW TEXTEQU <__imp_DsGetDomainControllerInfoW>
extern __imp_DsGetRdnW:PANYARGS
DsGetRdnW TEXTEQU <__imp_DsGetRdnW>
extern __imp_DsGetSpnA:PANYARGS
DsGetSpn  TEXTEQU <__imp_DsGetSpnA>
extern __imp_DsGetSpnW:PANYARGS
DsGetSpnW TEXTEQU <__imp_DsGetSpnW>
extern __imp_DsInheritSecurityIdentityA:PANYARGS
DsInheritSecurityIdentity  TEXTEQU <__imp_DsInheritSecurityIdentityA>
extern __imp_DsInheritSecurityIdentityW:PANYARGS
DsInheritSecurityIdentityW TEXTEQU <__imp_DsInheritSecurityIdentityW>
extern __imp_DsIsMangledDnA:PANYARGS
DsIsMangledDn  TEXTEQU <__imp_DsIsMangledDnA>
extern __imp_DsIsMangledDnW:PANYARGS
DsIsMangledDnW TEXTEQU <__imp_DsIsMangledDnW>
extern __imp_DsIsMangledRdnValueA:PANYARGS
DsIsMangledRdnValue  TEXTEQU <__imp_DsIsMangledRdnValueA>
extern __imp_DsIsMangledRdnValueW:PANYARGS
DsIsMangledRdnValueW TEXTEQU <__imp_DsIsMangledRdnValueW>
extern __imp_DsListDomainsInSiteA:PANYARGS
DsListDomainsInSite  TEXTEQU <__imp_DsListDomainsInSiteA>
extern __imp_DsListDomainsInSiteW:PANYARGS
DsListDomainsInSiteW TEXTEQU <__imp_DsListDomainsInSiteW>
extern __imp_DsListInfoForServerA:PANYARGS
DsListInfoForServer  TEXTEQU <__imp_DsListInfoForServerA>
extern __imp_DsListInfoForServerW:PANYARGS
DsListInfoForServerW TEXTEQU <__imp_DsListInfoForServerW>
extern __imp_DsListRolesA:PANYARGS
DsListRoles  TEXTEQU <__imp_DsListRolesA>
extern __imp_DsListRolesW:PANYARGS
DsListRolesW TEXTEQU <__imp_DsListRolesW>
extern __imp_DsListServersForDomainInSiteA:PANYARGS
DsListServersForDomainInSite  TEXTEQU <__imp_DsListServersForDomainInSiteA>
extern __imp_DsListServersForDomainInSiteW:PANYARGS
DsListServersForDomainInSiteW TEXTEQU <__imp_DsListServersForDomainInSiteW>
extern __imp_DsListServersInSiteA:PANYARGS
DsListServersInSite  TEXTEQU <__imp_DsListServersInSiteA>
extern __imp_DsListServersInSiteW:PANYARGS
DsListServersInSiteW TEXTEQU <__imp_DsListServersInSiteW>
extern __imp_DsListSitesA:PANYARGS
DsListSites  TEXTEQU <__imp_DsListSitesA>
extern __imp_DsListSitesW:PANYARGS
DsListSitesW TEXTEQU <__imp_DsListSitesW>
extern __imp_DsLogEntry:PANYARGS
DsLogEntry TEXTEQU <__imp_DsLogEntry>
extern __imp_DsMakePasswordCredentialsA:PANYARGS
DsMakePasswordCredentials  TEXTEQU <__imp_DsMakePasswordCredentialsA>
extern __imp_DsMakePasswordCredentialsW:PANYARGS
DsMakePasswordCredentialsW TEXTEQU <__imp_DsMakePasswordCredentialsW>
extern __imp_DsMakeSpnA:PANYARGS
DsMakeSpn  TEXTEQU <__imp_DsMakeSpnA>
extern __imp_DsMakeSpnW:PANYARGS
DsMakeSpnW TEXTEQU <__imp_DsMakeSpnW>
extern __imp_DsMapSchemaGuidsA:PANYARGS
DsMapSchemaGuids  TEXTEQU <__imp_DsMapSchemaGuidsA>
extern __imp_DsMapSchemaGuidsW:PANYARGS
DsMapSchemaGuidsW TEXTEQU <__imp_DsMapSchemaGuidsW>
extern __imp_DsQuerySitesByCostA:PANYARGS
DsQuerySitesByCost  TEXTEQU <__imp_DsQuerySitesByCostA>
extern __imp_DsQuerySitesByCostW:PANYARGS
DsQuerySitesByCostW TEXTEQU <__imp_DsQuerySitesByCostW>
extern __imp_DsQuerySitesFree:PANYARGS
DsQuerySitesFree TEXTEQU <__imp_DsQuerySitesFree>
extern __imp_DsQuoteRdnValueA:PANYARGS
DsQuoteRdnValue  TEXTEQU <__imp_DsQuoteRdnValueA>
extern __imp_DsQuoteRdnValueW:PANYARGS
DsQuoteRdnValueW TEXTEQU <__imp_DsQuoteRdnValueW>
extern __imp_DsRemoveDsDomainA:PANYARGS
DsRemoveDsDomain  TEXTEQU <__imp_DsRemoveDsDomainA>
extern __imp_DsRemoveDsDomainW:PANYARGS
DsRemoveDsDomainW TEXTEQU <__imp_DsRemoveDsDomainW>
extern __imp_DsRemoveDsServerA:PANYARGS
DsRemoveDsServer  TEXTEQU <__imp_DsRemoveDsServerA>
extern __imp_DsRemoveDsServerW:PANYARGS
DsRemoveDsServerW TEXTEQU <__imp_DsRemoveDsServerW>
extern __imp_DsReplicaAddA:PANYARGS
DsReplicaAdd  TEXTEQU <__imp_DsReplicaAddA>
extern __imp_DsReplicaAddW:PANYARGS
DsReplicaAddW TEXTEQU <__imp_DsReplicaAddW>
extern __imp_DsReplicaConsistencyCheck:PANYARGS
DsReplicaConsistencyCheck TEXTEQU <__imp_DsReplicaConsistencyCheck>
extern __imp_DsReplicaDelA:PANYARGS
DsReplicaDel  TEXTEQU <__imp_DsReplicaDelA>
extern __imp_DsReplicaDelW:PANYARGS
DsReplicaDelW TEXTEQU <__imp_DsReplicaDelW>
extern __imp_DsReplicaFreeInfo:PANYARGS
DsReplicaFreeInfo TEXTEQU <__imp_DsReplicaFreeInfo>
extern __imp_DsReplicaGetInfo2W:PANYARGS
DsReplicaGetInfo2W TEXTEQU <__imp_DsReplicaGetInfo2W>
extern __imp_DsReplicaGetInfoW:PANYARGS
DsReplicaGetInfoW TEXTEQU <__imp_DsReplicaGetInfoW>
extern __imp_DsReplicaModifyA:PANYARGS
DsReplicaModify  TEXTEQU <__imp_DsReplicaModifyA>
extern __imp_DsReplicaModifyW:PANYARGS
DsReplicaModifyW TEXTEQU <__imp_DsReplicaModifyW>
extern __imp_DsReplicaSyncA:PANYARGS
DsReplicaSync  TEXTEQU <__imp_DsReplicaSyncA>
extern __imp_DsReplicaSyncAllA:PANYARGS
DsReplicaSyncAll  TEXTEQU <__imp_DsReplicaSyncAllA>
extern __imp_DsReplicaSyncAllW:PANYARGS
DsReplicaSyncAllW TEXTEQU <__imp_DsReplicaSyncAllW>
extern __imp_DsReplicaSyncW:PANYARGS
DsReplicaSyncW TEXTEQU <__imp_DsReplicaSyncW>
extern __imp_DsReplicaUpdateRefsA:PANYARGS
DsReplicaUpdateRefs  TEXTEQU <__imp_DsReplicaUpdateRefsA>
extern __imp_DsReplicaUpdateRefsW:PANYARGS
DsReplicaUpdateRefsW TEXTEQU <__imp_DsReplicaUpdateRefsW>
extern __imp_DsReplicaVerifyObjectsA:PANYARGS
DsReplicaVerifyObjects  TEXTEQU <__imp_DsReplicaVerifyObjectsA>
extern __imp_DsReplicaVerifyObjectsW:PANYARGS
DsReplicaVerifyObjectsW TEXTEQU <__imp_DsReplicaVerifyObjectsW>
extern __imp_DsServerRegisterSpnA:PANYARGS
DsServerRegisterSpn  TEXTEQU <__imp_DsServerRegisterSpnA>
extern __imp_DsServerRegisterSpnW:PANYARGS
DsServerRegisterSpnW TEXTEQU <__imp_DsServerRegisterSpnW>
extern __imp_DsUnBindA:PANYARGS
DsUnBind  TEXTEQU <__imp_DsUnBindA>
extern __imp_DsUnBindW:PANYARGS
DsUnBindW TEXTEQU <__imp_DsUnBindW>
extern __imp_DsUnquoteRdnValueA:PANYARGS
DsUnquoteRdnValue  TEXTEQU <__imp_DsUnquoteRdnValueA>
extern __imp_DsUnquoteRdnValueW:PANYARGS
DsUnquoteRdnValueW TEXTEQU <__imp_DsUnquoteRdnValueW>
extern __imp_DsWriteAccountSpnA:PANYARGS
DsWriteAccountSpn  TEXTEQU <__imp_DsWriteAccountSpnA>
extern __imp_DsWriteAccountSpnW:PANYARGS
DsWriteAccountSpnW TEXTEQU <__imp_DsWriteAccountSpnW>
extern __imp_DsaopBind:PANYARGS
DsaopBind TEXTEQU <__imp_DsaopBind>
extern __imp_DsaopBindWithCred:PANYARGS
DsaopBindWithCred TEXTEQU <__imp_DsaopBindWithCred>
extern __imp_DsaopBindWithSpn:PANYARGS
DsaopBindWithSpn TEXTEQU <__imp_DsaopBindWithSpn>
extern __imp_DsaopExecuteScript:PANYARGS
DsaopExecuteScript TEXTEQU <__imp_DsaopExecuteScript>
extern __imp_DsaopPrepareScript:PANYARGS
DsaopPrepareScript TEXTEQU <__imp_DsaopPrepareScript>
extern __imp_DsaopUnBind:PANYARGS
DsaopUnBind TEXTEQU <__imp_DsaopUnBind>
