extern __imp_ShareAsDialogA0:PANYARGS
ShareAsDialogA0 TEXTEQU <__imp_ShareAsDialogA0>
extern __imp_StopShareDialogA0:PANYARGS
StopShareDialogA0 TEXTEQU <__imp_StopShareDialogA0>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_I_SystemFocusDialog:PANYARGS
I_SystemFocusDialog TEXTEQU <__imp_I_SystemFocusDialog>
extern __imp_NPGetPropertyText:PANYARGS
NPGetPropertyText TEXTEQU <__imp_NPGetPropertyText>
extern __imp_NPPropertyDialog:PANYARGS
NPPropertyDialog TEXTEQU <__imp_NPPropertyDialog>
extern __imp_ServerBrowseDialogA0:PANYARGS
ServerBrowseDialogA0 TEXTEQU <__imp_ServerBrowseDialogA0>
extern __imp_ShareCreate:PANYARGS
ShareCreate TEXTEQU <__imp_ShareCreate>
extern __imp_ShareManage:PANYARGS
ShareManage TEXTEQU <__imp_ShareManage>
extern __imp_ShareStop:PANYARGS
ShareStop TEXTEQU <__imp_ShareStop>
