extern __imp_NPGetConnection:PANYARGS
NPGetConnection TEXTEQU <__imp_NPGetConnection>
extern __imp_NPGetCaps:PANYARGS
NPGetCaps TEXTEQU <__imp_NPGetCaps>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_I_SystemFocusDialog:PANYARGS
I_SystemFocusDialog TEXTEQU <__imp_I_SystemFocusDialog>
extern __imp_NPGetUser:PANYARGS
NPGetUser TEXTEQU <__imp_NPGetUser>
extern __imp_NPAddConnection:PANYARGS
NPAddConnection TEXTEQU <__imp_NPAddConnection>
extern __imp_NPCancelConnection:PANYARGS
NPCancelConnection TEXTEQU <__imp_NPCancelConnection>
extern __imp_IsDfsPathEx:PANYARGS
IsDfsPathEx TEXTEQU <__imp_IsDfsPathEx>
extern __imp_NPAddConnection3ForCSCAgent:PANYARGS
NPAddConnection3ForCSCAgent TEXTEQU <__imp_NPAddConnection3ForCSCAgent>
extern __imp_NPCancelConnectionForCSCAgent:PANYARGS
NPCancelConnectionForCSCAgent TEXTEQU <__imp_NPCancelConnectionForCSCAgent>
extern __imp_ServerBrowseDialogA0:PANYARGS
ServerBrowseDialogA0 TEXTEQU <__imp_ServerBrowseDialogA0>
extern __imp_ShareAsDialogA0:PANYARGS
ShareAsDialogA0 TEXTEQU <__imp_ShareAsDialogA0>
extern __imp_ShareCreate:PANYARGS
ShareCreate TEXTEQU <__imp_ShareCreate>
extern __imp_ShareManage:PANYARGS
ShareManage TEXTEQU <__imp_ShareManage>
extern __imp_ShareStop:PANYARGS
ShareStop TEXTEQU <__imp_ShareStop>
extern __imp_StopShareDialogA0:PANYARGS
StopShareDialogA0 TEXTEQU <__imp_StopShareDialogA0>
extern __imp_ntlanman_ordinal28:PANYARGS
ntlanman_ordinal28 TEXTEQU <__imp_ntlanman_ordinal28>
extern __imp_NPPropertyDialog:PANYARGS
NPPropertyDialog TEXTEQU <__imp_NPPropertyDialog>
extern __imp_NPGetDirectoryType:PANYARGS
NPGetDirectoryType TEXTEQU <__imp_NPGetDirectoryType>
extern __imp_NPDirectoryNotify:PANYARGS
NPDirectoryNotify TEXTEQU <__imp_NPDirectoryNotify>
extern __imp_NPGetPropertyText:PANYARGS
NPGetPropertyText TEXTEQU <__imp_NPGetPropertyText>
extern __imp_NPOpenEnum:PANYARGS
NPOpenEnum TEXTEQU <__imp_NPOpenEnum>
extern __imp_NPEnumResource:PANYARGS
NPEnumResource TEXTEQU <__imp_NPEnumResource>
extern __imp_NPCloseEnum:PANYARGS
NPCloseEnum TEXTEQU <__imp_NPCloseEnum>
extern __imp_NPFormatNetworkName:PANYARGS
NPFormatNetworkName TEXTEQU <__imp_NPFormatNetworkName>
extern __imp_ntlanman_ordinal37:PANYARGS
ntlanman_ordinal37 TEXTEQU <__imp_ntlanman_ordinal37>
extern __imp_NPAddConnection3:PANYARGS
NPAddConnection3 TEXTEQU <__imp_NPAddConnection3>
extern __imp_ntlanman_ordinal39:PANYARGS
ntlanman_ordinal39 TEXTEQU <__imp_ntlanman_ordinal39>
extern __imp_NPGetUniversalName:PANYARGS
NPGetUniversalName TEXTEQU <__imp_NPGetUniversalName>
extern __imp_NPGetResourceParent:PANYARGS
NPGetResourceParent TEXTEQU <__imp_NPGetResourceParent>
extern __imp_ntlanman_ordinal42:PANYARGS
ntlanman_ordinal42 TEXTEQU <__imp_ntlanman_ordinal42>
extern __imp_ntlanman_ordinal43:PANYARGS
ntlanman_ordinal43 TEXTEQU <__imp_ntlanman_ordinal43>
extern __imp_ntlanman_ordinal44:PANYARGS
ntlanman_ordinal44 TEXTEQU <__imp_ntlanman_ordinal44>
extern __imp_ntlanman_ordinal45:PANYARGS
ntlanman_ordinal45 TEXTEQU <__imp_ntlanman_ordinal45>
extern __imp_ntlanman_ordinal46:PANYARGS
ntlanman_ordinal46 TEXTEQU <__imp_ntlanman_ordinal46>
extern __imp_ntlanman_ordinal47:PANYARGS
ntlanman_ordinal47 TEXTEQU <__imp_ntlanman_ordinal47>
extern __imp_ntlanman_ordinal48:PANYARGS
ntlanman_ordinal48 TEXTEQU <__imp_ntlanman_ordinal48>
extern __imp_NPGetConnectionPerformance:PANYARGS
NPGetConnectionPerformance TEXTEQU <__imp_NPGetConnectionPerformance>
extern __imp_ntlanman_ordinal50:PANYARGS
ntlanman_ordinal50 TEXTEQU <__imp_ntlanman_ordinal50>
extern __imp_ntlanman_ordinal51:PANYARGS
ntlanman_ordinal51 TEXTEQU <__imp_ntlanman_ordinal51>
extern __imp_NPGetResourceInformation:PANYARGS
NPGetResourceInformation TEXTEQU <__imp_NPGetResourceInformation>
extern __imp_NPGetReconnectFlags:PANYARGS
NPGetReconnectFlags TEXTEQU <__imp_NPGetReconnectFlags>
extern __imp_NPGetConnection3:PANYARGS
NPGetConnection3 TEXTEQU <__imp_NPGetConnection3>
