extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_GetServiceItemFromList:PANYARGS
GetServiceItemFromList TEXTEQU <__imp_GetServiceItemFromList>
extern __imp_InitializePrintProvidor:PANYARGS
InitializePrintProvidor TEXTEQU <__imp_InitializePrintProvidor>
extern __imp_LsaApCallPackage:PANYARGS
LsaApCallPackage TEXTEQU <__imp_LsaApCallPackage>
extern __imp_LsaApInitializePackage:PANYARGS
LsaApInitializePackage TEXTEQU <__imp_LsaApInitializePackage>
extern __imp_LsaApLogonTerminated:PANYARGS
LsaApLogonTerminated TEXTEQU <__imp_LsaApLogonTerminated>
extern __imp_LsaApLogonUser:PANYARGS
LsaApLogonUser TEXTEQU <__imp_LsaApLogonUser>
extern __imp_NPAddConnection:PANYARGS
NPAddConnection TEXTEQU <__imp_NPAddConnection>
extern __imp_NPAddConnection3:PANYARGS
NPAddConnection3 TEXTEQU <__imp_NPAddConnection3>
extern __imp_NPCancelConnection:PANYARGS
NPCancelConnection TEXTEQU <__imp_NPCancelConnection>
extern __imp_NPCloseEnum:PANYARGS
NPCloseEnum TEXTEQU <__imp_NPCloseEnum>
extern __imp_NPEnumResource:PANYARGS
NPEnumResource TEXTEQU <__imp_NPEnumResource>
extern __imp_NPFormatNetworkName:PANYARGS
NPFormatNetworkName TEXTEQU <__imp_NPFormatNetworkName>
extern __imp_NPGetCaps:PANYARGS
NPGetCaps TEXTEQU <__imp_NPGetCaps>
extern __imp_NPGetConnection:PANYARGS
NPGetConnection TEXTEQU <__imp_NPGetConnection>
extern __imp_NPGetConnectionPerformance:PANYARGS
NPGetConnectionPerformance TEXTEQU <__imp_NPGetConnectionPerformance>
extern __imp_NPGetResourceInformation:PANYARGS
NPGetResourceInformation TEXTEQU <__imp_NPGetResourceInformation>
extern __imp_NPGetResourceParent:PANYARGS
NPGetResourceParent TEXTEQU <__imp_NPGetResourceParent>
extern __imp_NPGetUniversalName:PANYARGS
NPGetUniversalName TEXTEQU <__imp_NPGetUniversalName>
extern __imp_NPGetUser:PANYARGS
NPGetUser TEXTEQU <__imp_NPGetUser>
extern __imp_NPLoadNameSpaces:PANYARGS
NPLoadNameSpaces TEXTEQU <__imp_NPLoadNameSpaces>
extern __imp_NPLogonNotify:PANYARGS
NPLogonNotify TEXTEQU <__imp_NPLogonNotify>
extern __imp_NPOpenEnum:PANYARGS
NPOpenEnum TEXTEQU <__imp_NPOpenEnum>
extern __imp_NPPasswordChangeNotify:PANYARGS
NPPasswordChangeNotify TEXTEQU <__imp_NPPasswordChangeNotify>
extern __imp_NSPStartup:PANYARGS
NSPStartup TEXTEQU <__imp_NSPStartup>
extern __imp_NwDeregisterService:PANYARGS
NwDeregisterService TEXTEQU <__imp_NwDeregisterService>
extern __imp_NwEncryptChallenge:PANYARGS
NwEncryptChallenge TEXTEQU <__imp_NwEncryptChallenge>
extern __imp_NwEnumConnections:PANYARGS
NwEnumConnections TEXTEQU <__imp_NwEnumConnections>
extern __imp_NwGetService:PANYARGS
NwGetService TEXTEQU <__imp_NwGetService>
extern __imp_NwGetUserNameForServer:PANYARGS
NwGetUserNameForServer TEXTEQU <__imp_NwGetUserNameForServer>
extern __imp_NwInitializeServiceProvider:PANYARGS
NwInitializeServiceProvider TEXTEQU <__imp_NwInitializeServiceProvider>
extern __imp_NwQueryInfo:PANYARGS
NwQueryInfo TEXTEQU <__imp_NwQueryInfo>
extern __imp_NwQueryLogonOptions:PANYARGS
NwQueryLogonOptions TEXTEQU <__imp_NwQueryLogonOptions>
extern __imp_NwRegisterService:PANYARGS
NwRegisterService TEXTEQU <__imp_NwRegisterService>
extern __imp_NwSetInfoInRegistry:PANYARGS
NwSetInfoInRegistry TEXTEQU <__imp_NwSetInfoInRegistry>
extern __imp_NwSetInfoInWksta:PANYARGS
NwSetInfoInWksta TEXTEQU <__imp_NwSetInfoInWksta>
extern __imp_NwSetLogonOptionsInRegistry:PANYARGS
NwSetLogonOptionsInRegistry TEXTEQU <__imp_NwSetLogonOptionsInRegistry>
extern __imp_NwSetLogonScript:PANYARGS
NwSetLogonScript TEXTEQU <__imp_NwSetLogonScript>
extern __imp_NwTerminateServiceProvider:PANYARGS
NwTerminateServiceProvider TEXTEQU <__imp_NwTerminateServiceProvider>
extern __imp_NwValidateUser:PANYARGS
NwValidateUser TEXTEQU <__imp_NwValidateUser>
