extern __imp_FindControlClose:PANYARGS
FindControlClose TEXTEQU <__imp_FindControlClose>
extern __imp_FindFirstControl:PANYARGS
FindFirstControl TEXTEQU <__imp_FindFirstControl>
extern __imp_FindNextControl:PANYARGS
FindNextControl TEXTEQU <__imp_FindNextControl>
extern __imp_GetControlDependentFile:PANYARGS
GetControlDependentFile TEXTEQU <__imp_GetControlDependentFile>
extern __imp_GetControlInfo:PANYARGS
GetControlInfo TEXTEQU <__imp_GetControlInfo>
extern __imp_IsModuleRemovable:PANYARGS
IsModuleRemovable TEXTEQU <__imp_IsModuleRemovable>
extern __imp_ReleaseControlHandle:PANYARGS
ReleaseControlHandle TEXTEQU <__imp_ReleaseControlHandle>
extern __imp_RemoveControlByHandle:PANYARGS
RemoveControlByHandle TEXTEQU <__imp_RemoveControlByHandle>
extern __imp_RemoveControlByName:PANYARGS
RemoveControlByName TEXTEQU <__imp_RemoveControlByName>
extern __imp_RemoveExpiredControls:PANYARGS
RemoveExpiredControls TEXTEQU <__imp_RemoveExpiredControls>
extern __imp_SweepControlsByLastAccessDate:PANYARGS
SweepControlsByLastAccessDate TEXTEQU <__imp_SweepControlsByLastAccessDate>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
