extern __imp_OcComponentState:PANYARGS
OcComponentState TEXTEQU <__imp_OcComponentState>
extern __imp_OcCreateOcPage:PANYARGS
OcCreateOcPage TEXTEQU <__imp_OcCreateOcPage>
extern __imp_OcCreateSetupPage:PANYARGS
OcCreateSetupPage TEXTEQU <__imp_OcCreateSetupPage>
extern __imp_OcGetWizardPages:PANYARGS
OcGetWizardPages TEXTEQU <__imp_OcGetWizardPages>
extern __imp_OcInitialize:PANYARGS
OcInitialize TEXTEQU <__imp_OcInitialize>
extern __imp_OcRememberWizardDialogHandle:PANYARGS
OcRememberWizardDialogHandle TEXTEQU <__imp_OcRememberWizardDialogHandle>
extern __imp_OcSubComponentsPresent:PANYARGS
OcSubComponentsPresent TEXTEQU <__imp_OcSubComponentsPresent>
extern __imp_OcTerminate:PANYARGS
OcTerminate TEXTEQU <__imp_OcTerminate>
