extern __imp_SQLAllocConnect:PANYARGS
SQLAllocConnect TEXTEQU <__imp_SQLAllocConnect>
extern __imp_SQLAllocEnv:PANYARGS
SQLAllocEnv TEXTEQU <__imp_SQLAllocEnv>
extern __imp_SQLAllocStmt:PANYARGS
SQLAllocStmt TEXTEQU <__imp_SQLAllocStmt>
extern __imp_SQLBindCol:PANYARGS
SQLBindCol TEXTEQU <__imp_SQLBindCol>
extern __imp_SQLCancel:PANYARGS
SQLCancel TEXTEQU <__imp_SQLCancel>
extern __imp_SQLColAttributes:PANYARGS
SQLColAttributes TEXTEQU <__imp_SQLColAttributes>
extern __imp_SQLConnect:PANYARGS
SQLConnect TEXTEQU <__imp_SQLConnect>
extern __imp_SQLDescribeCol:PANYARGS
SQLDescribeCol TEXTEQU <__imp_SQLDescribeCol>
extern __imp_SQLDisconnect:PANYARGS
SQLDisconnect TEXTEQU <__imp_SQLDisconnect>
extern __imp_SQLError:PANYARGS
SQLError TEXTEQU <__imp_SQLError>
extern __imp_SQLExecDirect:PANYARGS
SQLExecDirect TEXTEQU <__imp_SQLExecDirect>
extern __imp_SQLExecute:PANYARGS
SQLExecute TEXTEQU <__imp_SQLExecute>
extern __imp_SQLFetch:PANYARGS
SQLFetch TEXTEQU <__imp_SQLFetch>
extern __imp_SQLFreeConnect:PANYARGS
SQLFreeConnect TEXTEQU <__imp_SQLFreeConnect>
extern __imp_SQLFreeEnv:PANYARGS
SQLFreeEnv TEXTEQU <__imp_SQLFreeEnv>
extern __imp_SQLFreeStmt:PANYARGS
SQLFreeStmt TEXTEQU <__imp_SQLFreeStmt>
extern __imp_SQLGetCursorName:PANYARGS
SQLGetCursorName TEXTEQU <__imp_SQLGetCursorName>
extern __imp_SQLNumResultCols:PANYARGS
SQLNumResultCols TEXTEQU <__imp_SQLNumResultCols>
extern __imp_SQLPrepare:PANYARGS
SQLPrepare TEXTEQU <__imp_SQLPrepare>
extern __imp_SQLRowCount:PANYARGS
SQLRowCount TEXTEQU <__imp_SQLRowCount>
extern __imp_SQLSetCursorName:PANYARGS
SQLSetCursorName TEXTEQU <__imp_SQLSetCursorName>
extern __imp_SQLSetParam:PANYARGS
SQLSetParam TEXTEQU <__imp_SQLSetParam>
extern __imp_SQLTransact:PANYARGS
SQLTransact TEXTEQU <__imp_SQLTransact>
extern __imp_SQLAllocHandle:PANYARGS
SQLAllocHandle TEXTEQU <__imp_SQLAllocHandle>
extern __imp_SQLBindParam:PANYARGS
SQLBindParam TEXTEQU <__imp_SQLBindParam>
extern __imp_SQLCloseCursor:PANYARGS
SQLCloseCursor TEXTEQU <__imp_SQLCloseCursor>
extern __imp_SQLColAttribute:PANYARGS
SQLColAttribute TEXTEQU <__imp_SQLColAttribute>
extern __imp_SQLCopyDesc:PANYARGS
SQLCopyDesc TEXTEQU <__imp_SQLCopyDesc>
extern __imp_SQLEndTran:PANYARGS
SQLEndTran TEXTEQU <__imp_SQLEndTran>
extern __imp_SQLFetchScroll:PANYARGS
SQLFetchScroll TEXTEQU <__imp_SQLFetchScroll>
extern __imp_SQLFreeHandle:PANYARGS
SQLFreeHandle TEXTEQU <__imp_SQLFreeHandle>
extern __imp_SQLGetConnectAttr:PANYARGS
SQLGetConnectAttr TEXTEQU <__imp_SQLGetConnectAttr>
extern __imp_SQLGetDescField:PANYARGS
SQLGetDescField TEXTEQU <__imp_SQLGetDescField>
extern __imp_SQLGetDescRec:PANYARGS
SQLGetDescRec TEXTEQU <__imp_SQLGetDescRec>
extern __imp_SQLGetDiagField:PANYARGS
SQLGetDiagField TEXTEQU <__imp_SQLGetDiagField>
extern __imp_SQLGetDiagRec:PANYARGS
SQLGetDiagRec TEXTEQU <__imp_SQLGetDiagRec>
extern __imp_SQLGetEnvAttr:PANYARGS
SQLGetEnvAttr TEXTEQU <__imp_SQLGetEnvAttr>
extern __imp_SQLGetStmtAttr:PANYARGS
SQLGetStmtAttr TEXTEQU <__imp_SQLGetStmtAttr>
extern __imp_SQLSetConnectAttr:PANYARGS
SQLSetConnectAttr TEXTEQU <__imp_SQLSetConnectAttr>
extern __imp_SQLColumns:PANYARGS
SQLColumns TEXTEQU <__imp_SQLColumns>
extern __imp_SQLDriverConnect:PANYARGS
SQLDriverConnect TEXTEQU <__imp_SQLDriverConnect>
extern __imp_SQLGetConnectOption:PANYARGS
SQLGetConnectOption TEXTEQU <__imp_SQLGetConnectOption>
extern __imp_SQLGetData:PANYARGS
SQLGetData TEXTEQU <__imp_SQLGetData>
extern __imp_SQLGetFunctions:PANYARGS
SQLGetFunctions TEXTEQU <__imp_SQLGetFunctions>
extern __imp_SQLGetInfo:PANYARGS
SQLGetInfo TEXTEQU <__imp_SQLGetInfo>
extern __imp_SQLGetStmtOption:PANYARGS
SQLGetStmtOption TEXTEQU <__imp_SQLGetStmtOption>
extern __imp_SQLGetTypeInfo:PANYARGS
SQLGetTypeInfo TEXTEQU <__imp_SQLGetTypeInfo>
extern __imp_SQLParamData:PANYARGS
SQLParamData TEXTEQU <__imp_SQLParamData>
extern __imp_SQLPutData:PANYARGS
SQLPutData TEXTEQU <__imp_SQLPutData>
extern __imp_SQLSetConnectOption:PANYARGS
SQLSetConnectOption TEXTEQU <__imp_SQLSetConnectOption>
extern __imp_SQLSetStmtOption:PANYARGS
SQLSetStmtOption TEXTEQU <__imp_SQLSetStmtOption>
extern __imp_SQLSpecialColumns:PANYARGS
SQLSpecialColumns TEXTEQU <__imp_SQLSpecialColumns>
extern __imp_SQLStatistics:PANYARGS
SQLStatistics TEXTEQU <__imp_SQLStatistics>
extern __imp_SQLTables:PANYARGS
SQLTables TEXTEQU <__imp_SQLTables>
extern __imp_SQLBrowseConnect:PANYARGS
SQLBrowseConnect TEXTEQU <__imp_SQLBrowseConnect>
extern __imp_SQLColumnPrivileges:PANYARGS
SQLColumnPrivileges TEXTEQU <__imp_SQLColumnPrivileges>
extern __imp_SQLDataSources:PANYARGS
SQLDataSources TEXTEQU <__imp_SQLDataSources>
extern __imp_SQLDescribeParam:PANYARGS
SQLDescribeParam TEXTEQU <__imp_SQLDescribeParam>
extern __imp_SQLExtendedFetch:PANYARGS
SQLExtendedFetch TEXTEQU <__imp_SQLExtendedFetch>
extern __imp_SQLForeignKeys:PANYARGS
SQLForeignKeys TEXTEQU <__imp_SQLForeignKeys>
extern __imp_SQLMoreResults:PANYARGS
SQLMoreResults TEXTEQU <__imp_SQLMoreResults>
extern __imp_SQLNativeSql:PANYARGS
SQLNativeSql TEXTEQU <__imp_SQLNativeSql>
extern __imp_SQLNumParams:PANYARGS
SQLNumParams TEXTEQU <__imp_SQLNumParams>
extern __imp_SQLParamOptions:PANYARGS
SQLParamOptions TEXTEQU <__imp_SQLParamOptions>
extern __imp_SQLPrimaryKeys:PANYARGS
SQLPrimaryKeys TEXTEQU <__imp_SQLPrimaryKeys>
extern __imp_SQLProcedureColumns:PANYARGS
SQLProcedureColumns TEXTEQU <__imp_SQLProcedureColumns>
extern __imp_SQLProcedures:PANYARGS
SQLProcedures TEXTEQU <__imp_SQLProcedures>
extern __imp_SQLSetPos:PANYARGS
SQLSetPos TEXTEQU <__imp_SQLSetPos>
extern __imp_SQLSetScrollOptions:PANYARGS
SQLSetScrollOptions TEXTEQU <__imp_SQLSetScrollOptions>
extern __imp_SQLTablePrivileges:PANYARGS
SQLTablePrivileges TEXTEQU <__imp_SQLTablePrivileges>
extern __imp_SQLDrivers:PANYARGS
SQLDrivers TEXTEQU <__imp_SQLDrivers>
extern __imp_SQLBindParameter:PANYARGS
SQLBindParameter TEXTEQU <__imp_SQLBindParameter>
extern __imp_SQLSetDescField:PANYARGS
SQLSetDescField TEXTEQU <__imp_SQLSetDescField>
extern __imp_SQLSetDescRec:PANYARGS
SQLSetDescRec TEXTEQU <__imp_SQLSetDescRec>
extern __imp_SQLSetEnvAttr:PANYARGS
SQLSetEnvAttr TEXTEQU <__imp_SQLSetEnvAttr>
extern __imp_SQLSetStmtAttr:PANYARGS
SQLSetStmtAttr TEXTEQU <__imp_SQLSetStmtAttr>
extern __imp_SQLAllocHandleStd:PANYARGS
SQLAllocHandleStd TEXTEQU <__imp_SQLAllocHandleStd>
extern __imp_SQLBulkOperations:PANYARGS
SQLBulkOperations TEXTEQU <__imp_SQLBulkOperations>
extern __imp_CloseODBCPerfData:PANYARGS
CloseODBCPerfData TEXTEQU <__imp_CloseODBCPerfData>
extern __imp_CollectODBCPerfData:PANYARGS
CollectODBCPerfData TEXTEQU <__imp_CollectODBCPerfData>
extern __imp_CursorLibLockDbc:PANYARGS
CursorLibLockDbc TEXTEQU <__imp_CursorLibLockDbc>
extern __imp_CursorLibLockDesc:PANYARGS
CursorLibLockDesc TEXTEQU <__imp_CursorLibLockDesc>
extern __imp_CursorLibLockStmt:PANYARGS
CursorLibLockStmt TEXTEQU <__imp_CursorLibLockStmt>
extern __imp_ODBCGetTryWaitValue:PANYARGS
ODBCGetTryWaitValue TEXTEQU <__imp_ODBCGetTryWaitValue>
extern __imp_CursorLibTransact:PANYARGS
CursorLibTransact TEXTEQU <__imp_CursorLibTransact>
extern __imp_ODBCSetTryWaitValue:PANYARGS
ODBCSetTryWaitValue TEXTEQU <__imp_ODBCSetTryWaitValue>
extern __imp_DllBidEntryPoint:PANYARGS
DllBidEntryPoint TEXTEQU <__imp_DllBidEntryPoint>
extern __imp_GetODBCSharedData:PANYARGS
GetODBCSharedData TEXTEQU <__imp_GetODBCSharedData>
extern __imp_LockHandle:PANYARGS
LockHandle TEXTEQU <__imp_LockHandle>
extern __imp_MpHeapAlloc:PANYARGS
MpHeapAlloc TEXTEQU <__imp_MpHeapAlloc>
extern __imp_MpHeapCompact:PANYARGS
MpHeapCompact TEXTEQU <__imp_MpHeapCompact>
extern __imp_MpHeapCreate:PANYARGS
MpHeapCreate TEXTEQU <__imp_MpHeapCreate>
extern __imp_MpHeapDestroy:PANYARGS
MpHeapDestroy TEXTEQU <__imp_MpHeapDestroy>
extern __imp_MpHeapFree:PANYARGS
MpHeapFree TEXTEQU <__imp_MpHeapFree>
extern __imp_MpHeapReAlloc:PANYARGS
MpHeapReAlloc TEXTEQU <__imp_MpHeapReAlloc>
extern __imp_MpHeapSize:PANYARGS
MpHeapSize TEXTEQU <__imp_MpHeapSize>
extern __imp_MpHeapValidate:PANYARGS
MpHeapValidate TEXTEQU <__imp_MpHeapValidate>
extern __imp_ODBCInternalConnectW:PANYARGS
ODBCInternalConnectW TEXTEQU <__imp_ODBCInternalConnectW>
extern __imp_OpenODBCPerfData:PANYARGS
OpenODBCPerfData TEXTEQU <__imp_OpenODBCPerfData>
extern __imp_PostComponentError:PANYARGS
PostComponentError TEXTEQU <__imp_PostComponentError>
extern __imp_PostODBCComponentError:PANYARGS
PostODBCComponentError TEXTEQU <__imp_PostODBCComponentError>
extern __imp_PostODBCError:PANYARGS
PostODBCError TEXTEQU <__imp_PostODBCError>
extern __imp_SearchStatusCode:PANYARGS
SearchStatusCode TEXTEQU <__imp_SearchStatusCode>
extern __imp_VFreeErrors:PANYARGS
VFreeErrors TEXTEQU <__imp_VFreeErrors>
extern __imp_VRetrieveDriverErrorsRowCol:PANYARGS
VRetrieveDriverErrorsRowCol TEXTEQU <__imp_VRetrieveDriverErrorsRowCol>
extern __imp_SQLColAttributesW:PANYARGS
SQLColAttributesW TEXTEQU <__imp_SQLColAttributesW>
extern __imp_SQLConnectW:PANYARGS
SQLConnectW TEXTEQU <__imp_SQLConnectW>
extern __imp_SQLDescribeColW:PANYARGS
SQLDescribeColW TEXTEQU <__imp_SQLDescribeColW>
extern __imp_ValidateErrorQueue:PANYARGS
ValidateErrorQueue TEXTEQU <__imp_ValidateErrorQueue>
extern __imp_SQLErrorW:PANYARGS
SQLErrorW TEXTEQU <__imp_SQLErrorW>
extern __imp_SQLExecDirectW:PANYARGS
SQLExecDirectW TEXTEQU <__imp_SQLExecDirectW>
extern __imp_g_hHeapMalloc:PANYARGS
g_hHeapMalloc TEXTEQU <__imp_g_hHeapMalloc>
extern __imp_odbc32_ordinal113:PANYARGS
odbc32_ordinal113 TEXTEQU <__imp_odbc32_ordinal113>
extern __imp_odbc32_ordinal114:PANYARGS
odbc32_ordinal114 TEXTEQU <__imp_odbc32_ordinal114>
extern __imp_odbc32_ordinal115:PANYARGS
odbc32_ordinal115 TEXTEQU <__imp_odbc32_ordinal115>
extern __imp_odbc32_ordinal116:PANYARGS
odbc32_ordinal116 TEXTEQU <__imp_odbc32_ordinal116>
extern __imp_SQLGetCursorNameW:PANYARGS
SQLGetCursorNameW TEXTEQU <__imp_SQLGetCursorNameW>
extern __imp_odbc32_ordinal118:PANYARGS
odbc32_ordinal118 TEXTEQU <__imp_odbc32_ordinal118>
extern __imp_SQLPrepareW:PANYARGS
SQLPrepareW TEXTEQU <__imp_SQLPrepareW>
extern __imp_odbc32_ordinal120:PANYARGS
odbc32_ordinal120 TEXTEQU <__imp_odbc32_ordinal120>
extern __imp_SQLSetCursorNameW:PANYARGS
SQLSetCursorNameW TEXTEQU <__imp_SQLSetCursorNameW>
extern __imp_odbc32_ordinal122:PANYARGS
odbc32_ordinal122 TEXTEQU <__imp_odbc32_ordinal122>
extern __imp_odbc32_ordinal123:PANYARGS
odbc32_ordinal123 TEXTEQU <__imp_odbc32_ordinal123>
extern __imp_odbc32_ordinal124:PANYARGS
odbc32_ordinal124 TEXTEQU <__imp_odbc32_ordinal124>
extern __imp_odbc32_ordinal125:PANYARGS
odbc32_ordinal125 TEXTEQU <__imp_odbc32_ordinal125>
extern __imp_odbc32_ordinal126:PANYARGS
odbc32_ordinal126 TEXTEQU <__imp_odbc32_ordinal126>
extern __imp_SQLColAttributeW:PANYARGS
SQLColAttributeW TEXTEQU <__imp_SQLColAttributeW>
extern __imp_odbc32_ordinal128:PANYARGS
odbc32_ordinal128 TEXTEQU <__imp_odbc32_ordinal128>
extern __imp_odbc32_ordinal129:PANYARGS
odbc32_ordinal129 TEXTEQU <__imp_odbc32_ordinal129>
extern __imp_odbc32_ordinal130:PANYARGS
odbc32_ordinal130 TEXTEQU <__imp_odbc32_ordinal130>
extern __imp_odbc32_ordinal131:PANYARGS
odbc32_ordinal131 TEXTEQU <__imp_odbc32_ordinal131>
extern __imp_SQLGetConnectAttrW:PANYARGS
SQLGetConnectAttrW TEXTEQU <__imp_SQLGetConnectAttrW>
extern __imp_SQLGetDescFieldW:PANYARGS
SQLGetDescFieldW TEXTEQU <__imp_SQLGetDescFieldW>
extern __imp_SQLGetDescRecW:PANYARGS
SQLGetDescRecW TEXTEQU <__imp_SQLGetDescRecW>
extern __imp_SQLGetDiagFieldW:PANYARGS
SQLGetDiagFieldW TEXTEQU <__imp_SQLGetDiagFieldW>
extern __imp_SQLGetDiagRecW:PANYARGS
SQLGetDiagRecW TEXTEQU <__imp_SQLGetDiagRecW>
extern __imp_odbc32_ordinal137:PANYARGS
odbc32_ordinal137 TEXTEQU <__imp_odbc32_ordinal137>
extern __imp_SQLGetStmtAttrW:PANYARGS
SQLGetStmtAttrW TEXTEQU <__imp_SQLGetStmtAttrW>
extern __imp_SQLSetConnectAttrW:PANYARGS
SQLSetConnectAttrW TEXTEQU <__imp_SQLSetConnectAttrW>
extern __imp_SQLColumnsW:PANYARGS
SQLColumnsW TEXTEQU <__imp_SQLColumnsW>
extern __imp_SQLDriverConnectW:PANYARGS
SQLDriverConnectW TEXTEQU <__imp_SQLDriverConnectW>
extern __imp_SQLGetConnectOptionW:PANYARGS
SQLGetConnectOptionW TEXTEQU <__imp_SQLGetConnectOptionW>
extern __imp_odbc32_ordinal143:PANYARGS
odbc32_ordinal143 TEXTEQU <__imp_odbc32_ordinal143>
extern __imp_odbc32_ordinal144:PANYARGS
odbc32_ordinal144 TEXTEQU <__imp_odbc32_ordinal144>
extern __imp_SQLGetInfoW:PANYARGS
SQLGetInfoW TEXTEQU <__imp_SQLGetInfoW>
extern __imp_odbc32_ordinal146:PANYARGS
odbc32_ordinal146 TEXTEQU <__imp_odbc32_ordinal146>
extern __imp_SQLGetTypeInfoW:PANYARGS
SQLGetTypeInfoW TEXTEQU <__imp_SQLGetTypeInfoW>
extern __imp_odbc32_ordinal148:PANYARGS
odbc32_ordinal148 TEXTEQU <__imp_odbc32_ordinal148>
extern __imp_odbc32_ordinal149:PANYARGS
odbc32_ordinal149 TEXTEQU <__imp_odbc32_ordinal149>
extern __imp_SQLSetConnectOptionW:PANYARGS
SQLSetConnectOptionW TEXTEQU <__imp_SQLSetConnectOptionW>
extern __imp_odbc32_ordinal151:PANYARGS
odbc32_ordinal151 TEXTEQU <__imp_odbc32_ordinal151>
extern __imp_SQLSpecialColumnsW:PANYARGS
SQLSpecialColumnsW TEXTEQU <__imp_SQLSpecialColumnsW>
extern __imp_SQLStatisticsW:PANYARGS
SQLStatisticsW TEXTEQU <__imp_SQLStatisticsW>
extern __imp_SQLTablesW:PANYARGS
SQLTablesW TEXTEQU <__imp_SQLTablesW>
extern __imp_SQLBrowseConnectW:PANYARGS
SQLBrowseConnectW TEXTEQU <__imp_SQLBrowseConnectW>
extern __imp_SQLColumnPrivilegesW:PANYARGS
SQLColumnPrivilegesW TEXTEQU <__imp_SQLColumnPrivilegesW>
extern __imp_SQLDataSourcesW:PANYARGS
SQLDataSourcesW TEXTEQU <__imp_SQLDataSourcesW>
extern __imp_odbc32_ordinal158:PANYARGS
odbc32_ordinal158 TEXTEQU <__imp_odbc32_ordinal158>
extern __imp_odbc32_ordinal159:PANYARGS
odbc32_ordinal159 TEXTEQU <__imp_odbc32_ordinal159>
extern __imp_SQLForeignKeysW:PANYARGS
SQLForeignKeysW TEXTEQU <__imp_SQLForeignKeysW>
extern __imp_odbc32_ordinal161:PANYARGS
odbc32_ordinal161 TEXTEQU <__imp_odbc32_ordinal161>
extern __imp_SQLNativeSqlW:PANYARGS
SQLNativeSqlW TEXTEQU <__imp_SQLNativeSqlW>
extern __imp_odbc32_ordinal163:PANYARGS
odbc32_ordinal163 TEXTEQU <__imp_odbc32_ordinal163>
extern __imp_odbc32_ordinal164:PANYARGS
odbc32_ordinal164 TEXTEQU <__imp_odbc32_ordinal164>
extern __imp_SQLPrimaryKeysW:PANYARGS
SQLPrimaryKeysW TEXTEQU <__imp_SQLPrimaryKeysW>
extern __imp_SQLProcedureColumnsW:PANYARGS
SQLProcedureColumnsW TEXTEQU <__imp_SQLProcedureColumnsW>
extern __imp_SQLProceduresW:PANYARGS
SQLProceduresW TEXTEQU <__imp_SQLProceduresW>
extern __imp_odbc32_ordinal168:PANYARGS
odbc32_ordinal168 TEXTEQU <__imp_odbc32_ordinal168>
extern __imp_odbc32_ordinal169:PANYARGS
odbc32_ordinal169 TEXTEQU <__imp_odbc32_ordinal169>
extern __imp_SQLTablePrivilegesW:PANYARGS
SQLTablePrivilegesW TEXTEQU <__imp_SQLTablePrivilegesW>
extern __imp_SQLDriversW:PANYARGS
SQLDriversW TEXTEQU <__imp_SQLDriversW>
extern __imp_odbc32_ordinal172:PANYARGS
odbc32_ordinal172 TEXTEQU <__imp_odbc32_ordinal172>
extern __imp_SQLSetDescFieldW:PANYARGS
SQLSetDescFieldW TEXTEQU <__imp_SQLSetDescFieldW>
extern __imp_odbc32_ordinal174:PANYARGS
odbc32_ordinal174 TEXTEQU <__imp_odbc32_ordinal174>
extern __imp_odbc32_ordinal175:PANYARGS
odbc32_ordinal175 TEXTEQU <__imp_odbc32_ordinal175>
extern __imp_SQLSetStmtAttrW:PANYARGS
SQLSetStmtAttrW TEXTEQU <__imp_SQLSetStmtAttrW>
extern __imp_odbc32_ordinal177:PANYARGS
odbc32_ordinal177 TEXTEQU <__imp_odbc32_ordinal177>
extern __imp_odbc32_ordinal178:PANYARGS
odbc32_ordinal178 TEXTEQU <__imp_odbc32_ordinal178>
extern __imp_odbc32_ordinal179:PANYARGS
odbc32_ordinal179 TEXTEQU <__imp_odbc32_ordinal179>
extern __imp_odbc32_ordinal180:PANYARGS
odbc32_ordinal180 TEXTEQU <__imp_odbc32_ordinal180>
extern __imp_odbc32_ordinal181:PANYARGS
odbc32_ordinal181 TEXTEQU <__imp_odbc32_ordinal181>
extern __imp_odbc32_ordinal182:PANYARGS
odbc32_ordinal182 TEXTEQU <__imp_odbc32_ordinal182>
extern __imp_odbc32_ordinal183:PANYARGS
odbc32_ordinal183 TEXTEQU <__imp_odbc32_ordinal183>
extern __imp_odbc32_ordinal184:PANYARGS
odbc32_ordinal184 TEXTEQU <__imp_odbc32_ordinal184>
extern __imp_odbc32_ordinal185:PANYARGS
odbc32_ordinal185 TEXTEQU <__imp_odbc32_ordinal185>
extern __imp_odbc32_ordinal186:PANYARGS
odbc32_ordinal186 TEXTEQU <__imp_odbc32_ordinal186>
extern __imp_odbc32_ordinal187:PANYARGS
odbc32_ordinal187 TEXTEQU <__imp_odbc32_ordinal187>
extern __imp_odbc32_ordinal188:PANYARGS
odbc32_ordinal188 TEXTEQU <__imp_odbc32_ordinal188>
extern __imp_odbc32_ordinal189:PANYARGS
odbc32_ordinal189 TEXTEQU <__imp_odbc32_ordinal189>
extern __imp_odbc32_ordinal190:PANYARGS
odbc32_ordinal190 TEXTEQU <__imp_odbc32_ordinal190>
extern __imp_odbc32_ordinal191:PANYARGS
odbc32_ordinal191 TEXTEQU <__imp_odbc32_ordinal191>
extern __imp_odbc32_ordinal192:PANYARGS
odbc32_ordinal192 TEXTEQU <__imp_odbc32_ordinal192>
extern __imp_odbc32_ordinal193:PANYARGS
odbc32_ordinal193 TEXTEQU <__imp_odbc32_ordinal193>
extern __imp_odbc32_ordinal194:PANYARGS
odbc32_ordinal194 TEXTEQU <__imp_odbc32_ordinal194>
extern __imp_odbc32_ordinal195:PANYARGS
odbc32_ordinal195 TEXTEQU <__imp_odbc32_ordinal195>
extern __imp_odbc32_ordinal196:PANYARGS
odbc32_ordinal196 TEXTEQU <__imp_odbc32_ordinal196>
extern __imp_odbc32_ordinal197:PANYARGS
odbc32_ordinal197 TEXTEQU <__imp_odbc32_ordinal197>
extern __imp_odbc32_ordinal198:PANYARGS
odbc32_ordinal198 TEXTEQU <__imp_odbc32_ordinal198>
extern __imp_odbc32_ordinal199:PANYARGS
odbc32_ordinal199 TEXTEQU <__imp_odbc32_ordinal199>
extern __imp_odbc32_ordinal200:PANYARGS
odbc32_ordinal200 TEXTEQU <__imp_odbc32_ordinal200>
extern __imp_odbc32_ordinal201:PANYARGS
odbc32_ordinal201 TEXTEQU <__imp_odbc32_ordinal201>
extern __imp_odbc32_ordinal202:PANYARGS
odbc32_ordinal202 TEXTEQU <__imp_odbc32_ordinal202>
extern __imp_odbc32_ordinal203:PANYARGS
odbc32_ordinal203 TEXTEQU <__imp_odbc32_ordinal203>
extern __imp_odbc32_ordinal204:PANYARGS
odbc32_ordinal204 TEXTEQU <__imp_odbc32_ordinal204>
extern __imp_odbc32_ordinal205:PANYARGS
odbc32_ordinal205 TEXTEQU <__imp_odbc32_ordinal205>
extern __imp_SQLColAttributesA:PANYARGS
SQLColAttributes  TEXTEQU <__imp_SQLColAttributesA>
extern __imp_SQLConnectA:PANYARGS
SQLConnect  TEXTEQU <__imp_SQLConnectA>
extern __imp_SQLDescribeColA:PANYARGS
SQLDescribeCol  TEXTEQU <__imp_SQLDescribeColA>
extern __imp_odbc32_ordinal209:PANYARGS
odbc32_ordinal209 TEXTEQU <__imp_odbc32_ordinal209>
extern __imp_SQLErrorA:PANYARGS
SQLError  TEXTEQU <__imp_SQLErrorA>
extern __imp_SQLExecDirectA:PANYARGS
SQLExecDirect  TEXTEQU <__imp_SQLExecDirectA>
extern __imp_odbc32_ordinal212:PANYARGS
odbc32_ordinal212 TEXTEQU <__imp_odbc32_ordinal212>
extern __imp_odbc32_ordinal213:PANYARGS
odbc32_ordinal213 TEXTEQU <__imp_odbc32_ordinal213>
extern __imp_odbc32_ordinal214:PANYARGS
odbc32_ordinal214 TEXTEQU <__imp_odbc32_ordinal214>
extern __imp_odbc32_ordinal215:PANYARGS
odbc32_ordinal215 TEXTEQU <__imp_odbc32_ordinal215>
extern __imp_odbc32_ordinal216:PANYARGS
odbc32_ordinal216 TEXTEQU <__imp_odbc32_ordinal216>
extern __imp_SQLGetCursorNameA:PANYARGS
SQLGetCursorName  TEXTEQU <__imp_SQLGetCursorNameA>
extern __imp_odbc32_ordinal218:PANYARGS
odbc32_ordinal218 TEXTEQU <__imp_odbc32_ordinal218>
extern __imp_SQLPrepareA:PANYARGS
SQLPrepare  TEXTEQU <__imp_SQLPrepareA>
extern __imp_odbc32_ordinal220:PANYARGS
odbc32_ordinal220 TEXTEQU <__imp_odbc32_ordinal220>
extern __imp_SQLSetCursorNameA:PANYARGS
SQLSetCursorName  TEXTEQU <__imp_SQLSetCursorNameA>
extern __imp_odbc32_ordinal222:PANYARGS
odbc32_ordinal222 TEXTEQU <__imp_odbc32_ordinal222>
extern __imp_odbc32_ordinal223:PANYARGS
odbc32_ordinal223 TEXTEQU <__imp_odbc32_ordinal223>
extern __imp_odbc32_ordinal224:PANYARGS
odbc32_ordinal224 TEXTEQU <__imp_odbc32_ordinal224>
extern __imp_odbc32_ordinal225:PANYARGS
odbc32_ordinal225 TEXTEQU <__imp_odbc32_ordinal225>
extern __imp_odbc32_ordinal226:PANYARGS
odbc32_ordinal226 TEXTEQU <__imp_odbc32_ordinal226>
extern __imp_SQLColAttributeA:PANYARGS
SQLColAttribute  TEXTEQU <__imp_SQLColAttributeA>
extern __imp_odbc32_ordinal228:PANYARGS
odbc32_ordinal228 TEXTEQU <__imp_odbc32_ordinal228>
extern __imp_odbc32_ordinal229:PANYARGS
odbc32_ordinal229 TEXTEQU <__imp_odbc32_ordinal229>
extern __imp_odbc32_ordinal230:PANYARGS
odbc32_ordinal230 TEXTEQU <__imp_odbc32_ordinal230>
extern __imp_odbc32_ordinal231:PANYARGS
odbc32_ordinal231 TEXTEQU <__imp_odbc32_ordinal231>
extern __imp_SQLGetConnectAttrA:PANYARGS
SQLGetConnectAttr  TEXTEQU <__imp_SQLGetConnectAttrA>
extern __imp_SQLGetDescFieldA:PANYARGS
SQLGetDescField  TEXTEQU <__imp_SQLGetDescFieldA>
extern __imp_SQLGetDescRecA:PANYARGS
SQLGetDescRec  TEXTEQU <__imp_SQLGetDescRecA>
extern __imp_SQLGetDiagFieldA:PANYARGS
SQLGetDiagField  TEXTEQU <__imp_SQLGetDiagFieldA>
extern __imp_SQLGetDiagRecA:PANYARGS
SQLGetDiagRec  TEXTEQU <__imp_SQLGetDiagRecA>
extern __imp_odbc32_ordinal237:PANYARGS
odbc32_ordinal237 TEXTEQU <__imp_odbc32_ordinal237>
extern __imp_SQLGetStmtAttrA:PANYARGS
SQLGetStmtAttr  TEXTEQU <__imp_SQLGetStmtAttrA>
extern __imp_SQLSetConnectAttrA:PANYARGS
SQLSetConnectAttr  TEXTEQU <__imp_SQLSetConnectAttrA>
extern __imp_SQLColumnsA:PANYARGS
SQLColumns  TEXTEQU <__imp_SQLColumnsA>
extern __imp_SQLDriverConnectA:PANYARGS
SQLDriverConnect  TEXTEQU <__imp_SQLDriverConnectA>
extern __imp_SQLGetConnectOptionA:PANYARGS
SQLGetConnectOption  TEXTEQU <__imp_SQLGetConnectOptionA>
extern __imp_odbc32_ordinal243:PANYARGS
odbc32_ordinal243 TEXTEQU <__imp_odbc32_ordinal243>
extern __imp_odbc32_ordinal244:PANYARGS
odbc32_ordinal244 TEXTEQU <__imp_odbc32_ordinal244>
extern __imp_SQLGetInfoA:PANYARGS
SQLGetInfo  TEXTEQU <__imp_SQLGetInfoA>
extern __imp_odbc32_ordinal246:PANYARGS
odbc32_ordinal246 TEXTEQU <__imp_odbc32_ordinal246>
extern __imp_SQLGetTypeInfoA:PANYARGS
SQLGetTypeInfo  TEXTEQU <__imp_SQLGetTypeInfoA>
extern __imp_odbc32_ordinal248:PANYARGS
odbc32_ordinal248 TEXTEQU <__imp_odbc32_ordinal248>
extern __imp_odbc32_ordinal249:PANYARGS
odbc32_ordinal249 TEXTEQU <__imp_odbc32_ordinal249>
extern __imp_SQLSetConnectOptionA:PANYARGS
SQLSetConnectOption  TEXTEQU <__imp_SQLSetConnectOptionA>
extern __imp_odbc32_ordinal251:PANYARGS
odbc32_ordinal251 TEXTEQU <__imp_odbc32_ordinal251>
extern __imp_SQLSpecialColumnsA:PANYARGS
SQLSpecialColumns  TEXTEQU <__imp_SQLSpecialColumnsA>
extern __imp_SQLStatisticsA:PANYARGS
SQLStatistics  TEXTEQU <__imp_SQLStatisticsA>
extern __imp_SQLTablesA:PANYARGS
SQLTables  TEXTEQU <__imp_SQLTablesA>
extern __imp_SQLBrowseConnectA:PANYARGS
SQLBrowseConnect  TEXTEQU <__imp_SQLBrowseConnectA>
extern __imp_SQLColumnPrivilegesA:PANYARGS
SQLColumnPrivileges  TEXTEQU <__imp_SQLColumnPrivilegesA>
extern __imp_SQLDataSourcesA:PANYARGS
SQLDataSources  TEXTEQU <__imp_SQLDataSourcesA>
extern __imp_odbc32_ordinal258:PANYARGS
odbc32_ordinal258 TEXTEQU <__imp_odbc32_ordinal258>
extern __imp_odbc32_ordinal259:PANYARGS
odbc32_ordinal259 TEXTEQU <__imp_odbc32_ordinal259>
extern __imp_SQLForeignKeysA:PANYARGS
SQLForeignKeys  TEXTEQU <__imp_SQLForeignKeysA>
extern __imp_odbc32_ordinal261:PANYARGS
odbc32_ordinal261 TEXTEQU <__imp_odbc32_ordinal261>
extern __imp_SQLNativeSqlA:PANYARGS
SQLNativeSql  TEXTEQU <__imp_SQLNativeSqlA>
extern __imp_odbc32_ordinal263:PANYARGS
odbc32_ordinal263 TEXTEQU <__imp_odbc32_ordinal263>
extern __imp_odbc32_ordinal264:PANYARGS
odbc32_ordinal264 TEXTEQU <__imp_odbc32_ordinal264>
extern __imp_SQLPrimaryKeysA:PANYARGS
SQLPrimaryKeys  TEXTEQU <__imp_SQLPrimaryKeysA>
extern __imp_SQLProcedureColumnsA:PANYARGS
SQLProcedureColumns  TEXTEQU <__imp_SQLProcedureColumnsA>
extern __imp_SQLProceduresA:PANYARGS
SQLProcedures  TEXTEQU <__imp_SQLProceduresA>
extern __imp_odbc32_ordinal268:PANYARGS
odbc32_ordinal268 TEXTEQU <__imp_odbc32_ordinal268>
extern __imp_odbc32_ordinal269:PANYARGS
odbc32_ordinal269 TEXTEQU <__imp_odbc32_ordinal269>
extern __imp_SQLTablePrivilegesA:PANYARGS
SQLTablePrivileges  TEXTEQU <__imp_SQLTablePrivilegesA>
extern __imp_SQLDriversA:PANYARGS
SQLDrivers  TEXTEQU <__imp_SQLDriversA>
extern __imp_odbc32_ordinal272:PANYARGS
odbc32_ordinal272 TEXTEQU <__imp_odbc32_ordinal272>
extern __imp_SQLSetDescFieldA:PANYARGS
SQLSetDescField  TEXTEQU <__imp_SQLSetDescFieldA>
extern __imp_odbc32_ordinal274:PANYARGS
odbc32_ordinal274 TEXTEQU <__imp_odbc32_ordinal274>
extern __imp_odbc32_ordinal275:PANYARGS
odbc32_ordinal275 TEXTEQU <__imp_odbc32_ordinal275>
extern __imp_SQLSetStmtAttrA:PANYARGS
SQLSetStmtAttr  TEXTEQU <__imp_SQLSetStmtAttrA>
extern __imp_odbc32_ordinal277:PANYARGS
odbc32_ordinal277 TEXTEQU <__imp_odbc32_ordinal277>
extern __imp_odbc32_ordinal278:PANYARGS
odbc32_ordinal278 TEXTEQU <__imp_odbc32_ordinal278>
extern __imp_odbc32_ordinal279:PANYARGS
odbc32_ordinal279 TEXTEQU <__imp_odbc32_ordinal279>
extern __imp_odbc32_ordinal280:PANYARGS
odbc32_ordinal280 TEXTEQU <__imp_odbc32_ordinal280>
extern __imp_odbc32_ordinal281:PANYARGS
odbc32_ordinal281 TEXTEQU <__imp_odbc32_ordinal281>
extern __imp_odbc32_ordinal282:PANYARGS
odbc32_ordinal282 TEXTEQU <__imp_odbc32_ordinal282>
extern __imp_odbc32_ordinal283:PANYARGS
odbc32_ordinal283 TEXTEQU <__imp_odbc32_ordinal283>
extern __imp_odbc32_ordinal284:PANYARGS
odbc32_ordinal284 TEXTEQU <__imp_odbc32_ordinal284>
extern __imp_odbc32_ordinal285:PANYARGS
odbc32_ordinal285 TEXTEQU <__imp_odbc32_ordinal285>
extern __imp_odbc32_ordinal286:PANYARGS
odbc32_ordinal286 TEXTEQU <__imp_odbc32_ordinal286>
extern __imp_odbc32_ordinal287:PANYARGS
odbc32_ordinal287 TEXTEQU <__imp_odbc32_ordinal287>
extern __imp_odbc32_ordinal288:PANYARGS
odbc32_ordinal288 TEXTEQU <__imp_odbc32_ordinal288>
extern __imp_odbc32_ordinal289:PANYARGS
odbc32_ordinal289 TEXTEQU <__imp_odbc32_ordinal289>
extern __imp_odbc32_ordinal290:PANYARGS
odbc32_ordinal290 TEXTEQU <__imp_odbc32_ordinal290>
extern __imp_odbc32_ordinal291:PANYARGS
odbc32_ordinal291 TEXTEQU <__imp_odbc32_ordinal291>
extern __imp_odbc32_ordinal292:PANYARGS
odbc32_ordinal292 TEXTEQU <__imp_odbc32_ordinal292>
extern __imp_odbc32_ordinal293:PANYARGS
odbc32_ordinal293 TEXTEQU <__imp_odbc32_ordinal293>
extern __imp_odbc32_ordinal294:PANYARGS
odbc32_ordinal294 TEXTEQU <__imp_odbc32_ordinal294>
extern __imp_odbc32_ordinal295:PANYARGS
odbc32_ordinal295 TEXTEQU <__imp_odbc32_ordinal295>
extern __imp_odbc32_ordinal296:PANYARGS
odbc32_ordinal296 TEXTEQU <__imp_odbc32_ordinal296>
extern __imp_odbc32_ordinal297:PANYARGS
odbc32_ordinal297 TEXTEQU <__imp_odbc32_ordinal297>
extern __imp_odbc32_ordinal298:PANYARGS
odbc32_ordinal298 TEXTEQU <__imp_odbc32_ordinal298>
extern __imp_odbc32_ordinal299:PANYARGS
odbc32_ordinal299 TEXTEQU <__imp_odbc32_ordinal299>
extern __imp_odbc32_ordinal300:PANYARGS
odbc32_ordinal300 TEXTEQU <__imp_odbc32_ordinal300>
extern __imp_ODBCQualifyFileDSNW:PANYARGS
ODBCQualifyFileDSNW TEXTEQU <__imp_ODBCQualifyFileDSNW>
