extern __imp_SetSilent:PANYARGS
SetSilent TEXTEQU <__imp_SetSilent>
extern __imp_SetActionLogFile:PANYARGS
SetActionLogFile TEXTEQU <__imp_SetActionLogFile>
extern __imp_SetActionLogModeSz:PANYARGS
SetActionLogModeSz TEXTEQU <__imp_SetActionLogModeSz>
extern __imp_SetActionLogMode:PANYARGS
SetActionLogMode TEXTEQU <__imp_SetActionLogMode>
extern __imp_ExecuteAction:PANYARGS
ExecuteAction TEXTEQU <__imp_ExecuteAction>
extern __imp_SetActionEnum:PANYARGS
SetActionEnum TEXTEQU <__imp_SetActionEnum>
extern __imp_SetActionName:PANYARGS
SetActionName TEXTEQU <__imp_SetActionName>
extern __imp_ExpandPath:PANYARGS
ExpandPath TEXTEQU <__imp_ExpandPath>
extern __imp_GetPathFromID:PANYARGS
GetPathFromID TEXTEQU <__imp_GetPathFromID>
extern __imp_ApplyW2KXPak:PANYARGS
ApplyW2KXPak TEXTEQU <__imp_ApplyW2KXPak>
extern __imp_ApplyMillenCat:PANYARGS
ApplyMillenCat TEXTEQU <__imp_ApplyMillenCat>
extern __imp_UnregW2KXPak:PANYARGS
UnregW2KXPak TEXTEQU <__imp_UnregW2KXPak>
extern __imp_AppRegEnum:PANYARGS
AppRegEnum TEXTEQU <__imp_AppRegEnum>
extern __imp_CloseAppRegEnum:PANYARGS
CloseAppRegEnum TEXTEQU <__imp_CloseAppRegEnum>
extern __imp_OpenAppRegEnum:PANYARGS
OpenAppRegEnum TEXTEQU <__imp_OpenAppRegEnum>
extern __imp_QueryApplication:PANYARGS
QueryApplication TEXTEQU <__imp_QueryApplication>
extern __imp_RefreshAppRegEnum:PANYARGS
RefreshAppRegEnum TEXTEQU <__imp_RefreshAppRegEnum>
extern __imp_RegisterApplication:PANYARGS
RegisterApplication TEXTEQU <__imp_RegisterApplication>
extern __imp_RunDLL32_RegisterApplication:PANYARGS
RunDLL32_RegisterApplication TEXTEQU <__imp_RunDLL32_RegisterApplication>
extern __imp_RunDLL32_UnregisterApplication:PANYARGS
RunDLL32_UnregisterApplication TEXTEQU <__imp_RunDLL32_UnregisterApplication>
extern __imp_UnregisterApplication:PANYARGS
UnregisterApplication TEXTEQU <__imp_UnregisterApplication>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_SLListCreate:PANYARGS
SLListCreate TEXTEQU <__imp_SLListCreate>
extern __imp_SLListDestroy:PANYARGS
SLListDestroy TEXTEQU <__imp_SLListDestroy>
extern __imp_SLListAddNode:PANYARGS
SLListAddNode TEXTEQU <__imp_SLListAddNode>
extern __imp_SLListRemoveNode:PANYARGS
SLListRemoveNode TEXTEQU <__imp_SLListRemoveNode>
extern __imp_SLListGetHead:PANYARGS
SLListGetHead TEXTEQU <__imp_SLListGetHead>
extern __imp_SLListGetNext:PANYARGS
SLListGetNext TEXTEQU <__imp_SLListGetNext>
extern __imp_SLListGetData:PANYARGS
SLListGetData TEXTEQU <__imp_SLListGetData>
extern __imp_SLListSetData:PANYARGS
SLListSetData TEXTEQU <__imp_SLListSetData>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_odbcconf_ordinal39:PANYARGS
odbcconf_ordinal39 TEXTEQU <__imp_odbcconf_ordinal39>
extern __imp_DLListCreate:PANYARGS
DLListCreate TEXTEQU <__imp_DLListCreate>
extern __imp_DLListDestroy:PANYARGS
DLListDestroy TEXTEQU <__imp_DLListDestroy>
extern __imp_DLListAddNode:PANYARGS
DLListAddNode TEXTEQU <__imp_DLListAddNode>
extern __imp_DLListRemoveNode:PANYARGS
DLListRemoveNode TEXTEQU <__imp_DLListRemoveNode>
extern __imp_DLListGetHead:PANYARGS
DLListGetHead TEXTEQU <__imp_DLListGetHead>
extern __imp_DLListGetNext:PANYARGS
DLListGetNext TEXTEQU <__imp_DLListGetNext>
extern __imp_DLListGetPrev:PANYARGS
DLListGetPrev TEXTEQU <__imp_DLListGetPrev>
extern __imp_DLListGetData:PANYARGS
DLListGetData TEXTEQU <__imp_DLListGetData>
extern __imp_DLListSetData:PANYARGS
DLListSetData TEXTEQU <__imp_DLListSetData>
extern __imp_odbcconf_ordinal49:PANYARGS
odbcconf_ordinal49 TEXTEQU <__imp_odbcconf_ordinal49>
extern __imp_odbcconf_ordinal50:PANYARGS
odbcconf_ordinal50 TEXTEQU <__imp_odbcconf_ordinal50>
extern __imp_odbcconf_ordinal51:PANYARGS
odbcconf_ordinal51 TEXTEQU <__imp_odbcconf_ordinal51>
extern __imp_odbcconf_ordinal52:PANYARGS
odbcconf_ordinal52 TEXTEQU <__imp_odbcconf_ordinal52>
extern __imp_odbcconf_ordinal53:PANYARGS
odbcconf_ordinal53 TEXTEQU <__imp_odbcconf_ordinal53>
extern __imp_odbcconf_ordinal54:PANYARGS
odbcconf_ordinal54 TEXTEQU <__imp_odbcconf_ordinal54>
extern __imp_odbcconf_ordinal55:PANYARGS
odbcconf_ordinal55 TEXTEQU <__imp_odbcconf_ordinal55>
extern __imp_odbcconf_ordinal56:PANYARGS
odbcconf_ordinal56 TEXTEQU <__imp_odbcconf_ordinal56>
extern __imp_odbcconf_ordinal57:PANYARGS
odbcconf_ordinal57 TEXTEQU <__imp_odbcconf_ordinal57>
extern __imp_odbcconf_ordinal58:PANYARGS
odbcconf_ordinal58 TEXTEQU <__imp_odbcconf_ordinal58>
extern __imp_odbcconf_ordinal59:PANYARGS
odbcconf_ordinal59 TEXTEQU <__imp_odbcconf_ordinal59>
extern __imp_odbcconf_ordinal60:PANYARGS
odbcconf_ordinal60 TEXTEQU <__imp_odbcconf_ordinal60>
extern __imp_odbcconf_ordinal61:PANYARGS
odbcconf_ordinal61 TEXTEQU <__imp_odbcconf_ordinal61>
extern __imp_odbcconf_ordinal62:PANYARGS
odbcconf_ordinal62 TEXTEQU <__imp_odbcconf_ordinal62>
extern __imp_odbcconf_ordinal63:PANYARGS
odbcconf_ordinal63 TEXTEQU <__imp_odbcconf_ordinal63>
extern __imp_odbcconf_ordinal64:PANYARGS
odbcconf_ordinal64 TEXTEQU <__imp_odbcconf_ordinal64>
extern __imp_odbcconf_ordinal65:PANYARGS
odbcconf_ordinal65 TEXTEQU <__imp_odbcconf_ordinal65>
extern __imp_odbcconf_ordinal66:PANYARGS
odbcconf_ordinal66 TEXTEQU <__imp_odbcconf_ordinal66>
extern __imp_odbcconf_ordinal67:PANYARGS
odbcconf_ordinal67 TEXTEQU <__imp_odbcconf_ordinal67>
extern __imp_odbcconf_ordinal68:PANYARGS
odbcconf_ordinal68 TEXTEQU <__imp_odbcconf_ordinal68>
extern __imp_odbcconf_ordinal69:PANYARGS
odbcconf_ordinal69 TEXTEQU <__imp_odbcconf_ordinal69>
extern __imp_OpenProcessInfo:PANYARGS
OpenProcessInfo TEXTEQU <__imp_OpenProcessInfo>
extern __imp_CloseProcessInfo:PANYARGS
CloseProcessInfo TEXTEQU <__imp_CloseProcessInfo>
extern __imp_odbcconf_ordinal72:PANYARGS
odbcconf_ordinal72 TEXTEQU <__imp_odbcconf_ordinal72>
extern __imp_odbcconf_ordinal73:PANYARGS
odbcconf_ordinal73 TEXTEQU <__imp_odbcconf_ordinal73>
extern __imp_odbcconf_ordinal74:PANYARGS
odbcconf_ordinal74 TEXTEQU <__imp_odbcconf_ordinal74>
extern __imp_odbcconf_ordinal75:PANYARGS
odbcconf_ordinal75 TEXTEQU <__imp_odbcconf_ordinal75>
extern __imp_odbcconf_ordinal76:PANYARGS
odbcconf_ordinal76 TEXTEQU <__imp_odbcconf_ordinal76>
extern __imp_odbcconf_ordinal77:PANYARGS
odbcconf_ordinal77 TEXTEQU <__imp_odbcconf_ordinal77>
extern __imp_odbcconf_ordinal78:PANYARGS
odbcconf_ordinal78 TEXTEQU <__imp_odbcconf_ordinal78>
extern __imp_odbcconf_ordinal79:PANYARGS
odbcconf_ordinal79 TEXTEQU <__imp_odbcconf_ordinal79>
extern __imp_IsFileLocked:PANYARGS
IsFileLocked TEXTEQU <__imp_IsFileLocked>
extern __imp_odbcconf_ordinal81:PANYARGS
odbcconf_ordinal81 TEXTEQU <__imp_odbcconf_ordinal81>
extern __imp_odbcconf_ordinal82:PANYARGS
odbcconf_ordinal82 TEXTEQU <__imp_odbcconf_ordinal82>
extern __imp_odbcconf_ordinal83:PANYARGS
odbcconf_ordinal83 TEXTEQU <__imp_odbcconf_ordinal83>
extern __imp_odbcconf_ordinal84:PANYARGS
odbcconf_ordinal84 TEXTEQU <__imp_odbcconf_ordinal84>
extern __imp_EnableNTPrivilege:PANYARGS
EnableNTPrivilege TEXTEQU <__imp_EnableNTPrivilege>
extern __imp_DisableNTPrivilege:PANYARGS
DisableNTPrivilege TEXTEQU <__imp_DisableNTPrivilege>
extern __imp_odbcconf_ordinal87:PANYARGS
odbcconf_ordinal87 TEXTEQU <__imp_odbcconf_ordinal87>
extern __imp_odbcconf_ordinal88:PANYARGS
odbcconf_ordinal88 TEXTEQU <__imp_odbcconf_ordinal88>
extern __imp_odbcconf_ordinal89:PANYARGS
odbcconf_ordinal89 TEXTEQU <__imp_odbcconf_ordinal89>
extern __imp_EnableDebugPrivileges:PANYARGS
EnableDebugPrivileges TEXTEQU <__imp_EnableDebugPrivileges>
extern __imp_DisableDebugPrivileges:PANYARGS
DisableDebugPrivileges TEXTEQU <__imp_DisableDebugPrivileges>
extern __imp_odbcconf_ordinal92:PANYARGS
odbcconf_ordinal92 TEXTEQU <__imp_odbcconf_ordinal92>
extern __imp_odbcconf_ordinal93:PANYARGS
odbcconf_ordinal93 TEXTEQU <__imp_odbcconf_ordinal93>
extern __imp_odbcconf_ordinal94:PANYARGS
odbcconf_ordinal94 TEXTEQU <__imp_odbcconf_ordinal94>
extern __imp_LookupAppFriendlyName:PANYARGS
LookupAppFriendlyName TEXTEQU <__imp_LookupAppFriendlyName>
extern __imp_odbcconf_ordinal96:PANYARGS
odbcconf_ordinal96 TEXTEQU <__imp_odbcconf_ordinal96>
extern __imp_odbcconf_ordinal97:PANYARGS
odbcconf_ordinal97 TEXTEQU <__imp_odbcconf_ordinal97>
extern __imp_odbcconf_ordinal98:PANYARGS
odbcconf_ordinal98 TEXTEQU <__imp_odbcconf_ordinal98>
extern __imp_odbcconf_ordinal99:PANYARGS
odbcconf_ordinal99 TEXTEQU <__imp_odbcconf_ordinal99>
extern __imp_IsModuleLoadedByProcess:PANYARGS
IsModuleLoadedByProcess TEXTEQU <__imp_IsModuleLoadedByProcess>
extern __imp_IsModuleLoadedByProcessEx:PANYARGS
IsModuleLoadedByProcessEx TEXTEQU <__imp_IsModuleLoadedByProcessEx>
extern __imp_odbcconf_ordinal102:PANYARGS
odbcconf_ordinal102 TEXTEQU <__imp_odbcconf_ordinal102>
extern __imp_odbcconf_ordinal103:PANYARGS
odbcconf_ordinal103 TEXTEQU <__imp_odbcconf_ordinal103>
extern __imp_odbcconf_ordinal104:PANYARGS
odbcconf_ordinal104 TEXTEQU <__imp_odbcconf_ordinal104>
extern __imp_ShutdownProcess:PANYARGS
ShutdownProcess TEXTEQU <__imp_ShutdownProcess>
extern __imp_odbcconf_ordinal106:PANYARGS
odbcconf_ordinal106 TEXTEQU <__imp_odbcconf_ordinal106>
extern __imp_odbcconf_ordinal107:PANYARGS
odbcconf_ordinal107 TEXTEQU <__imp_odbcconf_ordinal107>
extern __imp_odbcconf_ordinal108:PANYARGS
odbcconf_ordinal108 TEXTEQU <__imp_odbcconf_ordinal108>
extern __imp_odbcconf_ordinal109:PANYARGS
odbcconf_ordinal109 TEXTEQU <__imp_odbcconf_ordinal109>
extern __imp_OpenProcessDisplayNames:PANYARGS
OpenProcessDisplayNames TEXTEQU <__imp_OpenProcessDisplayNames>
extern __imp_CloseProcessDisplayNames:PANYARGS
CloseProcessDisplayNames TEXTEQU <__imp_CloseProcessDisplayNames>
extern __imp_odbcconf_ordinal112:PANYARGS
odbcconf_ordinal112 TEXTEQU <__imp_odbcconf_ordinal112>
extern __imp_odbcconf_ordinal113:PANYARGS
odbcconf_ordinal113 TEXTEQU <__imp_odbcconf_ordinal113>
extern __imp_odbcconf_ordinal114:PANYARGS
odbcconf_ordinal114 TEXTEQU <__imp_odbcconf_ordinal114>
extern __imp_GetProcessListFromFileList:PANYARGS
GetProcessListFromFileList TEXTEQU <__imp_GetProcessListFromFileList>
extern __imp_odbcconf_ordinal116:PANYARGS
odbcconf_ordinal116 TEXTEQU <__imp_odbcconf_ordinal116>
extern __imp_odbcconf_ordinal117:PANYARGS
odbcconf_ordinal117 TEXTEQU <__imp_odbcconf_ordinal117>
extern __imp_odbcconf_ordinal118:PANYARGS
odbcconf_ordinal118 TEXTEQU <__imp_odbcconf_ordinal118>
extern __imp_odbcconf_ordinal119:PANYARGS
odbcconf_ordinal119 TEXTEQU <__imp_odbcconf_ordinal119>
extern __imp_OpenProcessList:PANYARGS
OpenProcessList TEXTEQU <__imp_OpenProcessList>
extern __imp_CloseProcessList:PANYARGS
CloseProcessList TEXTEQU <__imp_CloseProcessList>
extern __imp_EnumerateProcesses:PANYARGS
EnumerateProcesses TEXTEQU <__imp_EnumerateProcesses>
extern __imp_AddInfToList:PANYARGS
AddInfToList TEXTEQU <__imp_AddInfToList>
extern __imp_CreateInfList:PANYARGS
CreateInfList TEXTEQU <__imp_CreateInfList>
extern __imp_PopulateInfFileList:PANYARGS
PopulateInfFileList TEXTEQU <__imp_PopulateInfFileList>
extern __imp_DestroyInfList:PANYARGS
DestroyInfList TEXTEQU <__imp_DestroyInfList>
extern __imp_odbcconf_ordinal127:PANYARGS
odbcconf_ordinal127 TEXTEQU <__imp_odbcconf_ordinal127>
extern __imp_odbcconf_ordinal128:PANYARGS
odbcconf_ordinal128 TEXTEQU <__imp_odbcconf_ordinal128>
extern __imp_odbcconf_ordinal129:PANYARGS
odbcconf_ordinal129 TEXTEQU <__imp_odbcconf_ordinal129>
extern __imp_OpenDriveSpaceList:PANYARGS
OpenDriveSpaceList TEXTEQU <__imp_OpenDriveSpaceList>
extern __imp_CloseDriveSpaceList:PANYARGS
CloseDriveSpaceList TEXTEQU <__imp_CloseDriveSpaceList>
extern __imp_CalculateRequiredDriveSpace:PANYARGS
CalculateRequiredDriveSpace TEXTEQU <__imp_CalculateRequiredDriveSpace>
extern __imp_OpenDriveSpaceListFromInfList:PANYARGS
OpenDriveSpaceListFromInfList TEXTEQU <__imp_OpenDriveSpaceListFromInfList>
extern __imp_odbcconf_ordinal134:PANYARGS
odbcconf_ordinal134 TEXTEQU <__imp_odbcconf_ordinal134>
extern __imp_odbcconf_ordinal135:PANYARGS
odbcconf_ordinal135 TEXTEQU <__imp_odbcconf_ordinal135>
extern __imp_odbcconf_ordinal136:PANYARGS
odbcconf_ordinal136 TEXTEQU <__imp_odbcconf_ordinal136>
extern __imp_odbcconf_ordinal137:PANYARGS
odbcconf_ordinal137 TEXTEQU <__imp_odbcconf_ordinal137>
extern __imp_odbcconf_ordinal138:PANYARGS
odbcconf_ordinal138 TEXTEQU <__imp_odbcconf_ordinal138>
extern __imp_odbcconf_ordinal139:PANYARGS
odbcconf_ordinal139 TEXTEQU <__imp_odbcconf_ordinal139>
extern __imp_RunDLL32_FilterRunOnceExRegistration:PANYARGS
RunDLL32_FilterRunOnceExRegistration TEXTEQU <__imp_RunDLL32_FilterRunOnceExRegistration>
extern __imp_AddFilterRunOnceExRegistrationToRegistry:PANYARGS
AddFilterRunOnceExRegistrationToRegistry TEXTEQU <__imp_AddFilterRunOnceExRegistrationToRegistry>
extern __imp_RemoveFilterRunOnceExRegistrationFromRegistry:PANYARGS
RemoveFilterRunOnceExRegistrationFromRegistry TEXTEQU <__imp_RemoveFilterRunOnceExRegistrationFromRegistry>
extern __imp_FilterRunOnceExRegistration:PANYARGS
FilterRunOnceExRegistration TEXTEQU <__imp_FilterRunOnceExRegistration>
extern __imp_odbcconf_ordinal144:PANYARGS
odbcconf_ordinal144 TEXTEQU <__imp_odbcconf_ordinal144>
extern __imp_odbcconf_ordinal145:PANYARGS
odbcconf_ordinal145 TEXTEQU <__imp_odbcconf_ordinal145>
extern __imp_odbcconf_ordinal146:PANYARGS
odbcconf_ordinal146 TEXTEQU <__imp_odbcconf_ordinal146>
extern __imp_odbcconf_ordinal147:PANYARGS
odbcconf_ordinal147 TEXTEQU <__imp_odbcconf_ordinal147>
extern __imp_odbcconf_ordinal148:PANYARGS
odbcconf_ordinal148 TEXTEQU <__imp_odbcconf_ordinal148>
extern __imp_odbcconf_ordinal149:PANYARGS
odbcconf_ordinal149 TEXTEQU <__imp_odbcconf_ordinal149>
extern __imp_BackupRegKey:PANYARGS
BackupRegKey TEXTEQU <__imp_BackupRegKey>
extern __imp_RestoreRegKey:PANYARGS
RestoreRegKey TEXTEQU <__imp_RestoreRegKey>
extern __imp_RegVersion:PANYARGS
RegVersion TEXTEQU <__imp_RegVersion>
extern __imp_RegVersionEx:PANYARGS
RegVersionEx TEXTEQU <__imp_RegVersionEx>
extern __imp_LoadRegVersion:PANYARGS
LoadRegVersion TEXTEQU <__imp_LoadRegVersion>
extern __imp_LoadRegVersionEx:PANYARGS
LoadRegVersionEx TEXTEQU <__imp_LoadRegVersionEx>
extern __imp_odbcconf_ordinal156:PANYARGS
odbcconf_ordinal156 TEXTEQU <__imp_odbcconf_ordinal156>
extern __imp_odbcconf_ordinal157:PANYARGS
odbcconf_ordinal157 TEXTEQU <__imp_odbcconf_ordinal157>
extern __imp_odbcconf_ordinal158:PANYARGS
odbcconf_ordinal158 TEXTEQU <__imp_odbcconf_ordinal158>
extern __imp_odbcconf_ordinal159:PANYARGS
odbcconf_ordinal159 TEXTEQU <__imp_odbcconf_ordinal159>
extern __imp_GetProgramFilesDirectory:PANYARGS
GetProgramFilesDirectory TEXTEQU <__imp_GetProgramFilesDirectory>
extern __imp_GetProgramFilesCommonFilesDirectory:PANYARGS
GetProgramFilesCommonFilesDirectory TEXTEQU <__imp_GetProgramFilesCommonFilesDirectory>
extern __imp_odbcconf_ordinal162:PANYARGS
odbcconf_ordinal162 TEXTEQU <__imp_odbcconf_ordinal162>
extern __imp_odbcconf_ordinal163:PANYARGS
odbcconf_ordinal163 TEXTEQU <__imp_odbcconf_ordinal163>
extern __imp_odbcconf_ordinal164:PANYARGS
odbcconf_ordinal164 TEXTEQU <__imp_odbcconf_ordinal164>
extern __imp_odbcconf_ordinal165:PANYARGS
odbcconf_ordinal165 TEXTEQU <__imp_odbcconf_ordinal165>
extern __imp_odbcconf_ordinal166:PANYARGS
odbcconf_ordinal166 TEXTEQU <__imp_odbcconf_ordinal166>
extern __imp_odbcconf_ordinal167:PANYARGS
odbcconf_ordinal167 TEXTEQU <__imp_odbcconf_ordinal167>
extern __imp_odbcconf_ordinal168:PANYARGS
odbcconf_ordinal168 TEXTEQU <__imp_odbcconf_ordinal168>
extern __imp_odbcconf_ordinal169:PANYARGS
odbcconf_ordinal169 TEXTEQU <__imp_odbcconf_ordinal169>
extern __imp_OpenPendingRenameList:PANYARGS
OpenPendingRenameList TEXTEQU <__imp_OpenPendingRenameList>
extern __imp_ClosePendingRenameList:PANYARGS
ClosePendingRenameList TEXTEQU <__imp_ClosePendingRenameList>
extern __imp_odbcconf_ordinal172:PANYARGS
odbcconf_ordinal172 TEXTEQU <__imp_odbcconf_ordinal172>
extern __imp_odbcconf_ordinal173:PANYARGS
odbcconf_ordinal173 TEXTEQU <__imp_odbcconf_ordinal173>
extern __imp_odbcconf_ordinal174:PANYARGS
odbcconf_ordinal174 TEXTEQU <__imp_odbcconf_ordinal174>
extern __imp_ParseVersionDataFromString:PANYARGS
ParseVersionDataFromString TEXTEQU <__imp_ParseVersionDataFromString>
extern __imp_ParseVersionDataFromStringEx:PANYARGS
ParseVersionDataFromStringEx TEXTEQU <__imp_ParseVersionDataFromStringEx>
extern __imp_CompareVersionData:PANYARGS
CompareVersionData TEXTEQU <__imp_CompareVersionData>
extern __imp_CompareVersionDataEx:PANYARGS
CompareVersionDataEx TEXTEQU <__imp_CompareVersionDataEx>
extern __imp_odbcconf_ordinal179:PANYARGS
odbcconf_ordinal179 TEXTEQU <__imp_odbcconf_ordinal179>
extern __imp_odbcconf_ordinal180:PANYARGS
odbcconf_ordinal180 TEXTEQU <__imp_odbcconf_ordinal180>
extern __imp_odbcconf_ordinal181:PANYARGS
odbcconf_ordinal181 TEXTEQU <__imp_odbcconf_ordinal181>
extern __imp_odbcconf_ordinal182:PANYARGS
odbcconf_ordinal182 TEXTEQU <__imp_odbcconf_ordinal182>
extern __imp_odbcconf_ordinal183:PANYARGS
odbcconf_ordinal183 TEXTEQU <__imp_odbcconf_ordinal183>
extern __imp_odbcconf_ordinal184:PANYARGS
odbcconf_ordinal184 TEXTEQU <__imp_odbcconf_ordinal184>
extern __imp_odbcconf_ordinal185:PANYARGS
odbcconf_ordinal185 TEXTEQU <__imp_odbcconf_ordinal185>
extern __imp_odbcconf_ordinal186:PANYARGS
odbcconf_ordinal186 TEXTEQU <__imp_odbcconf_ordinal186>
extern __imp_odbcconf_ordinal187:PANYARGS
odbcconf_ordinal187 TEXTEQU <__imp_odbcconf_ordinal187>
extern __imp_odbcconf_ordinal188:PANYARGS
odbcconf_ordinal188 TEXTEQU <__imp_odbcconf_ordinal188>
extern __imp_odbcconf_ordinal189:PANYARGS
odbcconf_ordinal189 TEXTEQU <__imp_odbcconf_ordinal189>
extern __imp_odbcconf_ordinal190:PANYARGS
odbcconf_ordinal190 TEXTEQU <__imp_odbcconf_ordinal190>
extern __imp_odbcconf_ordinal191:PANYARGS
odbcconf_ordinal191 TEXTEQU <__imp_odbcconf_ordinal191>
extern __imp_odbcconf_ordinal192:PANYARGS
odbcconf_ordinal192 TEXTEQU <__imp_odbcconf_ordinal192>
extern __imp_odbcconf_ordinal193:PANYARGS
odbcconf_ordinal193 TEXTEQU <__imp_odbcconf_ordinal193>
extern __imp_odbcconf_ordinal194:PANYARGS
odbcconf_ordinal194 TEXTEQU <__imp_odbcconf_ordinal194>
extern __imp_odbcconf_ordinal195:PANYARGS
odbcconf_ordinal195 TEXTEQU <__imp_odbcconf_ordinal195>
extern __imp_odbcconf_ordinal196:PANYARGS
odbcconf_ordinal196 TEXTEQU <__imp_odbcconf_ordinal196>
extern __imp_odbcconf_ordinal197:PANYARGS
odbcconf_ordinal197 TEXTEQU <__imp_odbcconf_ordinal197>
extern __imp_odbcconf_ordinal198:PANYARGS
odbcconf_ordinal198 TEXTEQU <__imp_odbcconf_ordinal198>
extern __imp_odbcconf_ordinal199:PANYARGS
odbcconf_ordinal199 TEXTEQU <__imp_odbcconf_ordinal199>
extern __imp_IsExceptionInf:PANYARGS
IsExceptionInf TEXTEQU <__imp_IsExceptionInf>
extern __imp_IsExceptionInfEx:PANYARGS
IsExceptionInfEx TEXTEQU <__imp_IsExceptionInfEx>
extern __imp_odbcconf_ordinal202:PANYARGS
odbcconf_ordinal202 TEXTEQU <__imp_odbcconf_ordinal202>
extern __imp_odbcconf_ordinal203:PANYARGS
odbcconf_ordinal203 TEXTEQU <__imp_odbcconf_ordinal203>
extern __imp_odbcconf_ordinal204:PANYARGS
odbcconf_ordinal204 TEXTEQU <__imp_odbcconf_ordinal204>
extern __imp_CreateRegKeyBackupList:PANYARGS
CreateRegKeyBackupList TEXTEQU <__imp_CreateRegKeyBackupList>
extern __imp_DestroyRegKeyBackupList:PANYARGS
DestroyRegKeyBackupList TEXTEQU <__imp_DestroyRegKeyBackupList>
extern __imp_RegKeyBackup:PANYARGS
RegKeyBackup TEXTEQU <__imp_RegKeyBackup>
extern __imp_RegKeyRestore:PANYARGS
RegKeyRestore TEXTEQU <__imp_RegKeyRestore>
extern __imp_SaveRegKeyBackupToFile:PANYARGS
SaveRegKeyBackupToFile TEXTEQU <__imp_SaveRegKeyBackupToFile>
extern __imp_LoadRegKeyBackupFromFile:PANYARGS
LoadRegKeyBackupFromFile TEXTEQU <__imp_LoadRegKeyBackupFromFile>
extern __imp_BackupCatalog:PANYARGS
BackupCatalog TEXTEQU <__imp_BackupCatalog>
extern __imp_RestoreCatalog:PANYARGS
RestoreCatalog TEXTEQU <__imp_RestoreCatalog>
extern __imp_DoesFileExist:PANYARGS
DoesFileExist TEXTEQU <__imp_DoesFileExist>
