extern __imp_SQLInstallDriver:PANYARGS
SQLInstallDriver TEXTEQU <__imp_SQLInstallDriver>
extern __imp_SQLInstallDriverManager:PANYARGS
SQLInstallDriverManager TEXTEQU <__imp_SQLInstallDriverManager>
extern __imp_SQLGetInstalledDrivers:PANYARGS
SQLGetInstalledDrivers TEXTEQU <__imp_SQLGetInstalledDrivers>
extern __imp_SQLGetAvailableDrivers:PANYARGS
SQLGetAvailableDrivers TEXTEQU <__imp_SQLGetAvailableDrivers>
extern __imp_SQLConfigDataSource:PANYARGS
SQLConfigDataSource TEXTEQU <__imp_SQLConfigDataSource>
extern __imp_SQLRemoveDefaultDataSource:PANYARGS
SQLRemoveDefaultDataSource TEXTEQU <__imp_SQLRemoveDefaultDataSource>
extern __imp_SQLWriteDSNToIni:PANYARGS
SQLWriteDSNToIni TEXTEQU <__imp_SQLWriteDSNToIni>
extern __imp_SQLRemoveDSNFromIni:PANYARGS
SQLRemoveDSNFromIni TEXTEQU <__imp_SQLRemoveDSNFromIni>
extern __imp_SQLInstallODBC:PANYARGS
SQLInstallODBC TEXTEQU <__imp_SQLInstallODBC>
extern __imp_SQLManageDataSources:PANYARGS
SQLManageDataSources TEXTEQU <__imp_SQLManageDataSources>
extern __imp_SQLCreateDataSource:PANYARGS
SQLCreateDataSource TEXTEQU <__imp_SQLCreateDataSource>
extern __imp_SQLGetTranslator:PANYARGS
SQLGetTranslator TEXTEQU <__imp_SQLGetTranslator>
extern __imp_SQLWritePrivateProfileString:PANYARGS
SQLWritePrivateProfileString TEXTEQU <__imp_SQLWritePrivateProfileString>
extern __imp_SQLGetPrivateProfileString:PANYARGS
SQLGetPrivateProfileString TEXTEQU <__imp_SQLGetPrivateProfileString>
extern __imp_SQLValidDSN:PANYARGS
SQLValidDSN TEXTEQU <__imp_SQLValidDSN>
extern __imp_SQLRemoveDriverManager:PANYARGS
SQLRemoveDriverManager TEXTEQU <__imp_SQLRemoveDriverManager>
extern __imp_SQLInstallTranslator:PANYARGS
SQLInstallTranslator TEXTEQU <__imp_SQLInstallTranslator>
extern __imp_SQLRemoveTranslator:PANYARGS
SQLRemoveTranslator TEXTEQU <__imp_SQLRemoveTranslator>
extern __imp_SQLRemoveDriver:PANYARGS
SQLRemoveDriver TEXTEQU <__imp_SQLRemoveDriver>
extern __imp_SQLConfigDriver:PANYARGS
SQLConfigDriver TEXTEQU <__imp_SQLConfigDriver>
extern __imp_SQLInstallerError:PANYARGS
SQLInstallerError TEXTEQU <__imp_SQLInstallerError>
extern __imp_SQLPostInstallerError:PANYARGS
SQLPostInstallerError TEXTEQU <__imp_SQLPostInstallerError>
extern __imp_SQLReadFileDSN:PANYARGS
SQLReadFileDSN TEXTEQU <__imp_SQLReadFileDSN>
extern __imp_SQLWriteFileDSN:PANYARGS
SQLWriteFileDSN TEXTEQU <__imp_SQLWriteFileDSN>
extern __imp_SQLInstallDriverEx:PANYARGS
SQLInstallDriverEx TEXTEQU <__imp_SQLInstallDriverEx>
extern __imp_SQLGetConfigMode:PANYARGS
SQLGetConfigMode TEXTEQU <__imp_SQLGetConfigMode>
extern __imp_SQLSetConfigMode:PANYARGS
SQLSetConfigMode TEXTEQU <__imp_SQLSetConfigMode>
extern __imp_SQLInstallTranslatorEx:PANYARGS
SQLInstallTranslatorEx TEXTEQU <__imp_SQLInstallTranslatorEx>
extern __imp_SQLCreateDataSourceEx:PANYARGS
SQLCreateDataSourceEx TEXTEQU <__imp_SQLCreateDataSourceEx>
extern __imp_odbccp32_ordinal31:PANYARGS
odbccp32_ordinal31 TEXTEQU <__imp_odbccp32_ordinal31>
extern __imp_odbccp32_ordinal32:PANYARGS
odbccp32_ordinal32 TEXTEQU <__imp_odbccp32_ordinal32>
extern __imp_odbccp32_ordinal33:PANYARGS
odbccp32_ordinal33 TEXTEQU <__imp_odbccp32_ordinal33>
extern __imp_odbccp32_ordinal34:PANYARGS
odbccp32_ordinal34 TEXTEQU <__imp_odbccp32_ordinal34>
extern __imp_odbccp32_ordinal35:PANYARGS
odbccp32_ordinal35 TEXTEQU <__imp_odbccp32_ordinal35>
extern __imp_odbccp32_ordinal36:PANYARGS
odbccp32_ordinal36 TEXTEQU <__imp_odbccp32_ordinal36>
extern __imp_odbccp32_ordinal37:PANYARGS
odbccp32_ordinal37 TEXTEQU <__imp_odbccp32_ordinal37>
extern __imp_odbccp32_ordinal38:PANYARGS
odbccp32_ordinal38 TEXTEQU <__imp_odbccp32_ordinal38>
extern __imp_odbccp32_ordinal39:PANYARGS
odbccp32_ordinal39 TEXTEQU <__imp_odbccp32_ordinal39>
extern __imp_odbccp32_ordinal40:PANYARGS
odbccp32_ordinal40 TEXTEQU <__imp_odbccp32_ordinal40>
extern __imp_odbccp32_ordinal41:PANYARGS
odbccp32_ordinal41 TEXTEQU <__imp_odbccp32_ordinal41>
extern __imp_odbccp32_ordinal42:PANYARGS
odbccp32_ordinal42 TEXTEQU <__imp_odbccp32_ordinal42>
extern __imp_odbccp32_ordinal43:PANYARGS
odbccp32_ordinal43 TEXTEQU <__imp_odbccp32_ordinal43>
extern __imp_odbccp32_ordinal44:PANYARGS
odbccp32_ordinal44 TEXTEQU <__imp_odbccp32_ordinal44>
extern __imp_odbccp32_ordinal45:PANYARGS
odbccp32_ordinal45 TEXTEQU <__imp_odbccp32_ordinal45>
extern __imp_odbccp32_ordinal46:PANYARGS
odbccp32_ordinal46 TEXTEQU <__imp_odbccp32_ordinal46>
extern __imp_odbccp32_ordinal47:PANYARGS
odbccp32_ordinal47 TEXTEQU <__imp_odbccp32_ordinal47>
extern __imp_odbccp32_ordinal48:PANYARGS
odbccp32_ordinal48 TEXTEQU <__imp_odbccp32_ordinal48>
extern __imp_odbccp32_ordinal49:PANYARGS
odbccp32_ordinal49 TEXTEQU <__imp_odbccp32_ordinal49>
extern __imp_odbccp32_ordinal50:PANYARGS
odbccp32_ordinal50 TEXTEQU <__imp_odbccp32_ordinal50>
extern __imp_odbccp32_ordinal51:PANYARGS
odbccp32_ordinal51 TEXTEQU <__imp_odbccp32_ordinal51>
extern __imp_odbccp32_ordinal52:PANYARGS
odbccp32_ordinal52 TEXTEQU <__imp_odbccp32_ordinal52>
extern __imp_odbccp32_ordinal53:PANYARGS
odbccp32_ordinal53 TEXTEQU <__imp_odbccp32_ordinal53>
extern __imp_odbccp32_ordinal54:PANYARGS
odbccp32_ordinal54 TEXTEQU <__imp_odbccp32_ordinal54>
extern __imp_odbccp32_ordinal55:PANYARGS
odbccp32_ordinal55 TEXTEQU <__imp_odbccp32_ordinal55>
extern __imp_odbccp32_ordinal56:PANYARGS
odbccp32_ordinal56 TEXTEQU <__imp_odbccp32_ordinal56>
extern __imp_odbccp32_ordinal57:PANYARGS
odbccp32_ordinal57 TEXTEQU <__imp_odbccp32_ordinal57>
extern __imp_odbccp32_ordinal58:PANYARGS
odbccp32_ordinal58 TEXTEQU <__imp_odbccp32_ordinal58>
extern __imp_odbccp32_ordinal59:PANYARGS
odbccp32_ordinal59 TEXTEQU <__imp_odbccp32_ordinal59>
extern __imp_odbccp32_ordinal60:PANYARGS
odbccp32_ordinal60 TEXTEQU <__imp_odbccp32_ordinal60>
extern __imp_odbccp32_ordinal61:PANYARGS
odbccp32_ordinal61 TEXTEQU <__imp_odbccp32_ordinal61>
extern __imp_odbccp32_ordinal62:PANYARGS
odbccp32_ordinal62 TEXTEQU <__imp_odbccp32_ordinal62>
extern __imp_odbccp32_ordinal63:PANYARGS
odbccp32_ordinal63 TEXTEQU <__imp_odbccp32_ordinal63>
extern __imp_odbccp32_ordinal64:PANYARGS
odbccp32_ordinal64 TEXTEQU <__imp_odbccp32_ordinal64>
extern __imp_odbccp32_ordinal65:PANYARGS
odbccp32_ordinal65 TEXTEQU <__imp_odbccp32_ordinal65>
extern __imp_odbccp32_ordinal66:PANYARGS
odbccp32_ordinal66 TEXTEQU <__imp_odbccp32_ordinal66>
extern __imp_odbccp32_ordinal67:PANYARGS
odbccp32_ordinal67 TEXTEQU <__imp_odbccp32_ordinal67>
extern __imp_odbccp32_ordinal68:PANYARGS
odbccp32_ordinal68 TEXTEQU <__imp_odbccp32_ordinal68>
extern __imp_odbccp32_ordinal69:PANYARGS
odbccp32_ordinal69 TEXTEQU <__imp_odbccp32_ordinal69>
extern __imp_odbccp32_ordinal70:PANYARGS
odbccp32_ordinal70 TEXTEQU <__imp_odbccp32_ordinal70>
extern __imp_odbccp32_ordinal71:PANYARGS
odbccp32_ordinal71 TEXTEQU <__imp_odbccp32_ordinal71>
extern __imp_odbccp32_ordinal72:PANYARGS
odbccp32_ordinal72 TEXTEQU <__imp_odbccp32_ordinal72>
extern __imp_odbccp32_ordinal73:PANYARGS
odbccp32_ordinal73 TEXTEQU <__imp_odbccp32_ordinal73>
extern __imp_odbccp32_ordinal74:PANYARGS
odbccp32_ordinal74 TEXTEQU <__imp_odbccp32_ordinal74>
extern __imp_odbccp32_ordinal75:PANYARGS
odbccp32_ordinal75 TEXTEQU <__imp_odbccp32_ordinal75>
extern __imp_odbccp32_ordinal76:PANYARGS
odbccp32_ordinal76 TEXTEQU <__imp_odbccp32_ordinal76>
extern __imp_odbccp32_ordinal77:PANYARGS
odbccp32_ordinal77 TEXTEQU <__imp_odbccp32_ordinal77>
extern __imp_odbccp32_ordinal78:PANYARGS
odbccp32_ordinal78 TEXTEQU <__imp_odbccp32_ordinal78>
extern __imp_odbccp32_ordinal79:PANYARGS
odbccp32_ordinal79 TEXTEQU <__imp_odbccp32_ordinal79>
extern __imp_odbccp32_ordinal80:PANYARGS
odbccp32_ordinal80 TEXTEQU <__imp_odbccp32_ordinal80>
extern __imp_odbccp32_ordinal81:PANYARGS
odbccp32_ordinal81 TEXTEQU <__imp_odbccp32_ordinal81>
extern __imp_odbccp32_ordinal82:PANYARGS
odbccp32_ordinal82 TEXTEQU <__imp_odbccp32_ordinal82>
extern __imp_odbccp32_ordinal83:PANYARGS
odbccp32_ordinal83 TEXTEQU <__imp_odbccp32_ordinal83>
extern __imp_odbccp32_ordinal84:PANYARGS
odbccp32_ordinal84 TEXTEQU <__imp_odbccp32_ordinal84>
extern __imp_odbccp32_ordinal85:PANYARGS
odbccp32_ordinal85 TEXTEQU <__imp_odbccp32_ordinal85>
extern __imp_odbccp32_ordinal86:PANYARGS
odbccp32_ordinal86 TEXTEQU <__imp_odbccp32_ordinal86>
extern __imp_odbccp32_ordinal87:PANYARGS
odbccp32_ordinal87 TEXTEQU <__imp_odbccp32_ordinal87>
extern __imp_odbccp32_ordinal88:PANYARGS
odbccp32_ordinal88 TEXTEQU <__imp_odbccp32_ordinal88>
extern __imp_odbccp32_ordinal89:PANYARGS
odbccp32_ordinal89 TEXTEQU <__imp_odbccp32_ordinal89>
extern __imp_odbccp32_ordinal90:PANYARGS
odbccp32_ordinal90 TEXTEQU <__imp_odbccp32_ordinal90>
extern __imp_odbccp32_ordinal91:PANYARGS
odbccp32_ordinal91 TEXTEQU <__imp_odbccp32_ordinal91>
extern __imp_odbccp32_ordinal92:PANYARGS
odbccp32_ordinal92 TEXTEQU <__imp_odbccp32_ordinal92>
extern __imp_odbccp32_ordinal93:PANYARGS
odbccp32_ordinal93 TEXTEQU <__imp_odbccp32_ordinal93>
extern __imp_odbccp32_ordinal94:PANYARGS
odbccp32_ordinal94 TEXTEQU <__imp_odbccp32_ordinal94>
extern __imp_odbccp32_ordinal95:PANYARGS
odbccp32_ordinal95 TEXTEQU <__imp_odbccp32_ordinal95>
extern __imp_odbccp32_ordinal96:PANYARGS
odbccp32_ordinal96 TEXTEQU <__imp_odbccp32_ordinal96>
extern __imp_odbccp32_ordinal97:PANYARGS
odbccp32_ordinal97 TEXTEQU <__imp_odbccp32_ordinal97>
extern __imp_odbccp32_ordinal98:PANYARGS
odbccp32_ordinal98 TEXTEQU <__imp_odbccp32_ordinal98>
extern __imp_odbccp32_ordinal99:PANYARGS
odbccp32_ordinal99 TEXTEQU <__imp_odbccp32_ordinal99>
extern __imp_odbccp32_ordinal100:PANYARGS
odbccp32_ordinal100 TEXTEQU <__imp_odbccp32_ordinal100>
extern __imp_ODBCCPlApplet:PANYARGS
ODBCCPlApplet TEXTEQU <__imp_ODBCCPlApplet>
extern __imp_odbccp32_ordinal102:PANYARGS
odbccp32_ordinal102 TEXTEQU <__imp_odbccp32_ordinal102>
extern __imp_odbccp32_ordinal103:PANYARGS
odbccp32_ordinal103 TEXTEQU <__imp_odbccp32_ordinal103>
extern __imp_odbccp32_ordinal104:PANYARGS
odbccp32_ordinal104 TEXTEQU <__imp_odbccp32_ordinal104>
extern __imp_odbccp32_ordinal105:PANYARGS
odbccp32_ordinal105 TEXTEQU <__imp_odbccp32_ordinal105>
extern __imp_odbccp32_ordinal106:PANYARGS
odbccp32_ordinal106 TEXTEQU <__imp_odbccp32_ordinal106>
extern __imp_odbccp32_ordinal107:PANYARGS
odbccp32_ordinal107 TEXTEQU <__imp_odbccp32_ordinal107>
extern __imp_odbccp32_ordinal108:PANYARGS
odbccp32_ordinal108 TEXTEQU <__imp_odbccp32_ordinal108>
extern __imp_odbccp32_ordinal109:PANYARGS
odbccp32_ordinal109 TEXTEQU <__imp_odbccp32_ordinal109>
extern __imp_odbccp32_ordinal110:PANYARGS
odbccp32_ordinal110 TEXTEQU <__imp_odbccp32_ordinal110>
extern __imp_odbccp32_ordinal111:PANYARGS
odbccp32_ordinal111 TEXTEQU <__imp_odbccp32_ordinal111>
extern __imp_SelectTransDlg:PANYARGS
SelectTransDlg TEXTEQU <__imp_SelectTransDlg>
extern __imp_odbccp32_ordinal113:PANYARGS
odbccp32_ordinal113 TEXTEQU <__imp_odbccp32_ordinal113>
extern __imp_odbccp32_ordinal114:PANYARGS
odbccp32_ordinal114 TEXTEQU <__imp_odbccp32_ordinal114>
extern __imp_odbccp32_ordinal115:PANYARGS
odbccp32_ordinal115 TEXTEQU <__imp_odbccp32_ordinal115>
extern __imp_odbccp32_ordinal116:PANYARGS
odbccp32_ordinal116 TEXTEQU <__imp_odbccp32_ordinal116>
extern __imp_odbccp32_ordinal117:PANYARGS
odbccp32_ordinal117 TEXTEQU <__imp_odbccp32_ordinal117>
extern __imp_odbccp32_ordinal118:PANYARGS
odbccp32_ordinal118 TEXTEQU <__imp_odbccp32_ordinal118>
extern __imp_odbccp32_ordinal119:PANYARGS
odbccp32_ordinal119 TEXTEQU <__imp_odbccp32_ordinal119>
extern __imp_odbccp32_ordinal120:PANYARGS
odbccp32_ordinal120 TEXTEQU <__imp_odbccp32_ordinal120>
extern __imp_odbccp32_ordinal121:PANYARGS
odbccp32_ordinal121 TEXTEQU <__imp_odbccp32_ordinal121>
extern __imp_odbccp32_ordinal122:PANYARGS
odbccp32_ordinal122 TEXTEQU <__imp_odbccp32_ordinal122>
extern __imp_odbccp32_ordinal123:PANYARGS
odbccp32_ordinal123 TEXTEQU <__imp_odbccp32_ordinal123>
extern __imp_odbccp32_ordinal124:PANYARGS
odbccp32_ordinal124 TEXTEQU <__imp_odbccp32_ordinal124>
extern __imp_odbccp32_ordinal125:PANYARGS
odbccp32_ordinal125 TEXTEQU <__imp_odbccp32_ordinal125>
extern __imp_odbccp32_ordinal126:PANYARGS
odbccp32_ordinal126 TEXTEQU <__imp_odbccp32_ordinal126>
extern __imp_odbccp32_ordinal127:PANYARGS
odbccp32_ordinal127 TEXTEQU <__imp_odbccp32_ordinal127>
extern __imp_odbccp32_ordinal128:PANYARGS
odbccp32_ordinal128 TEXTEQU <__imp_odbccp32_ordinal128>
extern __imp_odbccp32_ordinal129:PANYARGS
odbccp32_ordinal129 TEXTEQU <__imp_odbccp32_ordinal129>
extern __imp_odbccp32_ordinal130:PANYARGS
odbccp32_ordinal130 TEXTEQU <__imp_odbccp32_ordinal130>
extern __imp_odbccp32_ordinal131:PANYARGS
odbccp32_ordinal131 TEXTEQU <__imp_odbccp32_ordinal131>
extern __imp_odbccp32_ordinal132:PANYARGS
odbccp32_ordinal132 TEXTEQU <__imp_odbccp32_ordinal132>
extern __imp_odbccp32_ordinal133:PANYARGS
odbccp32_ordinal133 TEXTEQU <__imp_odbccp32_ordinal133>
extern __imp_odbccp32_ordinal134:PANYARGS
odbccp32_ordinal134 TEXTEQU <__imp_odbccp32_ordinal134>
extern __imp_odbccp32_ordinal135:PANYARGS
odbccp32_ordinal135 TEXTEQU <__imp_odbccp32_ordinal135>
extern __imp_odbccp32_ordinal136:PANYARGS
odbccp32_ordinal136 TEXTEQU <__imp_odbccp32_ordinal136>
extern __imp_odbccp32_ordinal137:PANYARGS
odbccp32_ordinal137 TEXTEQU <__imp_odbccp32_ordinal137>
extern __imp_odbccp32_ordinal138:PANYARGS
odbccp32_ordinal138 TEXTEQU <__imp_odbccp32_ordinal138>
extern __imp_odbccp32_ordinal139:PANYARGS
odbccp32_ordinal139 TEXTEQU <__imp_odbccp32_ordinal139>
extern __imp_odbccp32_ordinal140:PANYARGS
odbccp32_ordinal140 TEXTEQU <__imp_odbccp32_ordinal140>
extern __imp_odbccp32_ordinal141:PANYARGS
odbccp32_ordinal141 TEXTEQU <__imp_odbccp32_ordinal141>
extern __imp_odbccp32_ordinal142:PANYARGS
odbccp32_ordinal142 TEXTEQU <__imp_odbccp32_ordinal142>
extern __imp_odbccp32_ordinal143:PANYARGS
odbccp32_ordinal143 TEXTEQU <__imp_odbccp32_ordinal143>
extern __imp_odbccp32_ordinal144:PANYARGS
odbccp32_ordinal144 TEXTEQU <__imp_odbccp32_ordinal144>
extern __imp_odbccp32_ordinal145:PANYARGS
odbccp32_ordinal145 TEXTEQU <__imp_odbccp32_ordinal145>
extern __imp_odbccp32_ordinal146:PANYARGS
odbccp32_ordinal146 TEXTEQU <__imp_odbccp32_ordinal146>
extern __imp_odbccp32_ordinal147:PANYARGS
odbccp32_ordinal147 TEXTEQU <__imp_odbccp32_ordinal147>
extern __imp_odbccp32_ordinal148:PANYARGS
odbccp32_ordinal148 TEXTEQU <__imp_odbccp32_ordinal148>
extern __imp_odbccp32_ordinal149:PANYARGS
odbccp32_ordinal149 TEXTEQU <__imp_odbccp32_ordinal149>
extern __imp_odbccp32_ordinal150:PANYARGS
odbccp32_ordinal150 TEXTEQU <__imp_odbccp32_ordinal150>
extern __imp_odbccp32_ordinal151:PANYARGS
odbccp32_ordinal151 TEXTEQU <__imp_odbccp32_ordinal151>
extern __imp_odbccp32_ordinal152:PANYARGS
odbccp32_ordinal152 TEXTEQU <__imp_odbccp32_ordinal152>
extern __imp_odbccp32_ordinal153:PANYARGS
odbccp32_ordinal153 TEXTEQU <__imp_odbccp32_ordinal153>
extern __imp_odbccp32_ordinal154:PANYARGS
odbccp32_ordinal154 TEXTEQU <__imp_odbccp32_ordinal154>
extern __imp_odbccp32_ordinal155:PANYARGS
odbccp32_ordinal155 TEXTEQU <__imp_odbccp32_ordinal155>
extern __imp_odbccp32_ordinal156:PANYARGS
odbccp32_ordinal156 TEXTEQU <__imp_odbccp32_ordinal156>
extern __imp_odbccp32_ordinal157:PANYARGS
odbccp32_ordinal157 TEXTEQU <__imp_odbccp32_ordinal157>
extern __imp_odbccp32_ordinal158:PANYARGS
odbccp32_ordinal158 TEXTEQU <__imp_odbccp32_ordinal158>
extern __imp_odbccp32_ordinal159:PANYARGS
odbccp32_ordinal159 TEXTEQU <__imp_odbccp32_ordinal159>
extern __imp_odbccp32_ordinal160:PANYARGS
odbccp32_ordinal160 TEXTEQU <__imp_odbccp32_ordinal160>
extern __imp_odbccp32_ordinal161:PANYARGS
odbccp32_ordinal161 TEXTEQU <__imp_odbccp32_ordinal161>
extern __imp_odbccp32_ordinal162:PANYARGS
odbccp32_ordinal162 TEXTEQU <__imp_odbccp32_ordinal162>
extern __imp_odbccp32_ordinal163:PANYARGS
odbccp32_ordinal163 TEXTEQU <__imp_odbccp32_ordinal163>
extern __imp_odbccp32_ordinal164:PANYARGS
odbccp32_ordinal164 TEXTEQU <__imp_odbccp32_ordinal164>
extern __imp_odbccp32_ordinal165:PANYARGS
odbccp32_ordinal165 TEXTEQU <__imp_odbccp32_ordinal165>
extern __imp_odbccp32_ordinal166:PANYARGS
odbccp32_ordinal166 TEXTEQU <__imp_odbccp32_ordinal166>
extern __imp_odbccp32_ordinal167:PANYARGS
odbccp32_ordinal167 TEXTEQU <__imp_odbccp32_ordinal167>
extern __imp_odbccp32_ordinal168:PANYARGS
odbccp32_ordinal168 TEXTEQU <__imp_odbccp32_ordinal168>
extern __imp_odbccp32_ordinal169:PANYARGS
odbccp32_ordinal169 TEXTEQU <__imp_odbccp32_ordinal169>
extern __imp_odbccp32_ordinal170:PANYARGS
odbccp32_ordinal170 TEXTEQU <__imp_odbccp32_ordinal170>
extern __imp_odbccp32_ordinal171:PANYARGS
odbccp32_ordinal171 TEXTEQU <__imp_odbccp32_ordinal171>
extern __imp_odbccp32_ordinal172:PANYARGS
odbccp32_ordinal172 TEXTEQU <__imp_odbccp32_ordinal172>
extern __imp_odbccp32_ordinal173:PANYARGS
odbccp32_ordinal173 TEXTEQU <__imp_odbccp32_ordinal173>
extern __imp_odbccp32_ordinal174:PANYARGS
odbccp32_ordinal174 TEXTEQU <__imp_odbccp32_ordinal174>
extern __imp_odbccp32_ordinal175:PANYARGS
odbccp32_ordinal175 TEXTEQU <__imp_odbccp32_ordinal175>
extern __imp_odbccp32_ordinal176:PANYARGS
odbccp32_ordinal176 TEXTEQU <__imp_odbccp32_ordinal176>
extern __imp_odbccp32_ordinal177:PANYARGS
odbccp32_ordinal177 TEXTEQU <__imp_odbccp32_ordinal177>
extern __imp_odbccp32_ordinal178:PANYARGS
odbccp32_ordinal178 TEXTEQU <__imp_odbccp32_ordinal178>
extern __imp_odbccp32_ordinal179:PANYARGS
odbccp32_ordinal179 TEXTEQU <__imp_odbccp32_ordinal179>
extern __imp_odbccp32_ordinal180:PANYARGS
odbccp32_ordinal180 TEXTEQU <__imp_odbccp32_ordinal180>
extern __imp_odbccp32_ordinal181:PANYARGS
odbccp32_ordinal181 TEXTEQU <__imp_odbccp32_ordinal181>
extern __imp_odbccp32_ordinal182:PANYARGS
odbccp32_ordinal182 TEXTEQU <__imp_odbccp32_ordinal182>
extern __imp_odbccp32_ordinal183:PANYARGS
odbccp32_ordinal183 TEXTEQU <__imp_odbccp32_ordinal183>
extern __imp_odbccp32_ordinal184:PANYARGS
odbccp32_ordinal184 TEXTEQU <__imp_odbccp32_ordinal184>
extern __imp_odbccp32_ordinal185:PANYARGS
odbccp32_ordinal185 TEXTEQU <__imp_odbccp32_ordinal185>
extern __imp_odbccp32_ordinal186:PANYARGS
odbccp32_ordinal186 TEXTEQU <__imp_odbccp32_ordinal186>
extern __imp_odbccp32_ordinal187:PANYARGS
odbccp32_ordinal187 TEXTEQU <__imp_odbccp32_ordinal187>
extern __imp_odbccp32_ordinal188:PANYARGS
odbccp32_ordinal188 TEXTEQU <__imp_odbccp32_ordinal188>
extern __imp_odbccp32_ordinal189:PANYARGS
odbccp32_ordinal189 TEXTEQU <__imp_odbccp32_ordinal189>
extern __imp_odbccp32_ordinal190:PANYARGS
odbccp32_ordinal190 TEXTEQU <__imp_odbccp32_ordinal190>
extern __imp_odbccp32_ordinal191:PANYARGS
odbccp32_ordinal191 TEXTEQU <__imp_odbccp32_ordinal191>
extern __imp_odbccp32_ordinal192:PANYARGS
odbccp32_ordinal192 TEXTEQU <__imp_odbccp32_ordinal192>
extern __imp_odbccp32_ordinal193:PANYARGS
odbccp32_ordinal193 TEXTEQU <__imp_odbccp32_ordinal193>
extern __imp_odbccp32_ordinal194:PANYARGS
odbccp32_ordinal194 TEXTEQU <__imp_odbccp32_ordinal194>
extern __imp_odbccp32_ordinal195:PANYARGS
odbccp32_ordinal195 TEXTEQU <__imp_odbccp32_ordinal195>
extern __imp_odbccp32_ordinal196:PANYARGS
odbccp32_ordinal196 TEXTEQU <__imp_odbccp32_ordinal196>
extern __imp_odbccp32_ordinal197:PANYARGS
odbccp32_ordinal197 TEXTEQU <__imp_odbccp32_ordinal197>
extern __imp_odbccp32_ordinal198:PANYARGS
odbccp32_ordinal198 TEXTEQU <__imp_odbccp32_ordinal198>
extern __imp_odbccp32_ordinal199:PANYARGS
odbccp32_ordinal199 TEXTEQU <__imp_odbccp32_ordinal199>
extern __imp_odbccp32_ordinal200:PANYARGS
odbccp32_ordinal200 TEXTEQU <__imp_odbccp32_ordinal200>
extern __imp_odbccp32_ordinal201:PANYARGS
odbccp32_ordinal201 TEXTEQU <__imp_odbccp32_ordinal201>
extern __imp_SQLInstallDriverW:PANYARGS
SQLInstallDriverW TEXTEQU <__imp_SQLInstallDriverW>
extern __imp_SQLInstallDriverManagerW:PANYARGS
SQLInstallDriverManagerW TEXTEQU <__imp_SQLInstallDriverManagerW>
extern __imp_SQLGetInstalledDriversW:PANYARGS
SQLGetInstalledDriversW TEXTEQU <__imp_SQLGetInstalledDriversW>
extern __imp_SQLGetAvailableDriversW:PANYARGS
SQLGetAvailableDriversW TEXTEQU <__imp_SQLGetAvailableDriversW>
extern __imp_SQLConfigDataSourceW:PANYARGS
SQLConfigDataSourceW TEXTEQU <__imp_SQLConfigDataSourceW>
extern __imp_odbccp32_ordinal207:PANYARGS
odbccp32_ordinal207 TEXTEQU <__imp_odbccp32_ordinal207>
extern __imp_SQLWriteDSNToIniW:PANYARGS
SQLWriteDSNToIniW TEXTEQU <__imp_SQLWriteDSNToIniW>
extern __imp_SQLRemoveDSNFromIniW:PANYARGS
SQLRemoveDSNFromIniW TEXTEQU <__imp_SQLRemoveDSNFromIniW>
extern __imp_SQLInstallODBCW:PANYARGS
SQLInstallODBCW TEXTEQU <__imp_SQLInstallODBCW>
extern __imp_odbccp32_ordinal211:PANYARGS
odbccp32_ordinal211 TEXTEQU <__imp_odbccp32_ordinal211>
extern __imp_SQLCreateDataSourceW:PANYARGS
SQLCreateDataSourceW TEXTEQU <__imp_SQLCreateDataSourceW>
extern __imp_SQLGetTranslatorW:PANYARGS
SQLGetTranslatorW TEXTEQU <__imp_SQLGetTranslatorW>
extern __imp_SQLWritePrivateProfileStringW:PANYARGS
SQLWritePrivateProfileStringW TEXTEQU <__imp_SQLWritePrivateProfileStringW>
extern __imp_SQLGetPrivateProfileStringW:PANYARGS
SQLGetPrivateProfileStringW TEXTEQU <__imp_SQLGetPrivateProfileStringW>
extern __imp_SQLValidDSNW:PANYARGS
SQLValidDSNW TEXTEQU <__imp_SQLValidDSNW>
extern __imp_odbccp32_ordinal217:PANYARGS
odbccp32_ordinal217 TEXTEQU <__imp_odbccp32_ordinal217>
extern __imp_SQLInstallTranslatorW:PANYARGS
SQLInstallTranslatorW TEXTEQU <__imp_SQLInstallTranslatorW>
extern __imp_SQLRemoveTranslatorW:PANYARGS
SQLRemoveTranslatorW TEXTEQU <__imp_SQLRemoveTranslatorW>
extern __imp_SQLRemoveDriverW:PANYARGS
SQLRemoveDriverW TEXTEQU <__imp_SQLRemoveDriverW>
extern __imp_SQLConfigDriverW:PANYARGS
SQLConfigDriverW TEXTEQU <__imp_SQLConfigDriverW>
extern __imp_SQLInstallerErrorW:PANYARGS
SQLInstallerErrorW TEXTEQU <__imp_SQLInstallerErrorW>
extern __imp_SQLPostInstallerErrorW:PANYARGS
SQLPostInstallerErrorW TEXTEQU <__imp_SQLPostInstallerErrorW>
extern __imp_SQLReadFileDSNW:PANYARGS
SQLReadFileDSNW TEXTEQU <__imp_SQLReadFileDSNW>
extern __imp_SQLWriteFileDSNW:PANYARGS
SQLWriteFileDSNW TEXTEQU <__imp_SQLWriteFileDSNW>
extern __imp_SQLInstallDriverExW:PANYARGS
SQLInstallDriverExW TEXTEQU <__imp_SQLInstallDriverExW>
extern __imp_odbccp32_ordinal227:PANYARGS
odbccp32_ordinal227 TEXTEQU <__imp_odbccp32_ordinal227>
extern __imp_odbccp32_ordinal228:PANYARGS
odbccp32_ordinal228 TEXTEQU <__imp_odbccp32_ordinal228>
extern __imp_SQLInstallTranslatorExW:PANYARGS
SQLInstallTranslatorExW TEXTEQU <__imp_SQLInstallTranslatorExW>
extern __imp_SQLCreateDataSourceExW:PANYARGS
SQLCreateDataSourceExW TEXTEQU <__imp_SQLCreateDataSourceExW>
extern __imp_SQLLoadDriverListBox:PANYARGS
SQLLoadDriverListBox TEXTEQU <__imp_SQLLoadDriverListBox>
extern __imp_SQLLoadDataSourcesListBox:PANYARGS
SQLLoadDataSourcesListBox TEXTEQU <__imp_SQLLoadDataSourcesListBox>
