extern __imp_dbprtypeA:PANYARGS
dbprtype  TEXTEQU <__imp_dbprtypeA>
extern __imp_bcp_batch:PANYARGS
bcp_batch TEXTEQU <__imp_bcp_batch>
extern __imp_bcp_bind:PANYARGS
bcp_bind TEXTEQU <__imp_bcp_bind>
extern __imp_bcp_colfmt:PANYARGS
bcp_colfmt TEXTEQU <__imp_bcp_colfmt>
extern __imp_bcp_collen:PANYARGS
bcp_collen TEXTEQU <__imp_bcp_collen>
extern __imp_bcp_colptr:PANYARGS
bcp_colptr TEXTEQU <__imp_bcp_colptr>
extern __imp_odbcbcp_ordinal7:PANYARGS
odbcbcp_ordinal7 TEXTEQU <__imp_odbcbcp_ordinal7>
extern __imp_bcp_columns:PANYARGS
bcp_columns TEXTEQU <__imp_bcp_columns>
extern __imp_bcp_control:PANYARGS
bcp_control TEXTEQU <__imp_bcp_control>
extern __imp_bcp_done:PANYARGS
bcp_done TEXTEQU <__imp_bcp_done>
extern __imp_bcp_initA:PANYARGS
bcp_init  TEXTEQU <__imp_bcp_initA>
extern __imp_bcp_exec:PANYARGS
bcp_exec TEXTEQU <__imp_bcp_exec>
extern __imp_bcp_moretext:PANYARGS
bcp_moretext TEXTEQU <__imp_bcp_moretext>
extern __imp_bcp_sendrow:PANYARGS
bcp_sendrow TEXTEQU <__imp_bcp_sendrow>
extern __imp_bcp_readfmtA:PANYARGS
bcp_readfmt  TEXTEQU <__imp_bcp_readfmtA>
extern __imp_bcp_writefmtA:PANYARGS
bcp_writefmt  TEXTEQU <__imp_bcp_writefmtA>
extern __imp_dbprtypeW:PANYARGS
dbprtypeW TEXTEQU <__imp_dbprtypeW>
extern __imp_bcp_initW:PANYARGS
bcp_initW TEXTEQU <__imp_bcp_initW>
extern __imp_bcp_readfmtW:PANYARGS
bcp_readfmtW TEXTEQU <__imp_bcp_readfmtW>
extern __imp_bcp_writefmtW:PANYARGS
bcp_writefmtW TEXTEQU <__imp_bcp_writefmtW>
extern __imp_SQLLinkedServers:PANYARGS
SQLLinkedServers TEXTEQU <__imp_SQLLinkedServers>
extern __imp_SQLLinkedCatalogsW:PANYARGS
SQLLinkedCatalogsW TEXTEQU <__imp_SQLLinkedCatalogsW>
extern __imp_SQLLinkedCatalogsA:PANYARGS
SQLLinkedCatalogs  TEXTEQU <__imp_SQLLinkedCatalogsA>
extern __imp_LibMain:PANYARGS
LibMain TEXTEQU <__imp_LibMain>
extern __imp_SQLInitEnumServers:PANYARGS
SQLInitEnumServers TEXTEQU <__imp_SQLInitEnumServers>
extern __imp_SQLGetNextEnumeration:PANYARGS
SQLGetNextEnumeration TEXTEQU <__imp_SQLGetNextEnumeration>
extern __imp_SQLCloseEnumServers:PANYARGS
SQLCloseEnumServers TEXTEQU <__imp_SQLCloseEnumServers>
extern __imp_bcp_getcolfmt:PANYARGS
bcp_getcolfmt TEXTEQU <__imp_bcp_getcolfmt>
extern __imp_bcp_setcolfmt:PANYARGS
bcp_setcolfmt TEXTEQU <__imp_bcp_setcolfmt>
