extern __imp_TraceSQLAllocConnect:PANYARGS
TraceSQLAllocConnect TEXTEQU <__imp_TraceSQLAllocConnect>
extern __imp_TraceSQLAllocEnv:PANYARGS
TraceSQLAllocEnv TEXTEQU <__imp_TraceSQLAllocEnv>
extern __imp_TraceSQLAllocStmt:PANYARGS
TraceSQLAllocStmt TEXTEQU <__imp_TraceSQLAllocStmt>
extern __imp_TraceSQLBindCol:PANYARGS
TraceSQLBindCol TEXTEQU <__imp_TraceSQLBindCol>
extern __imp_TraceSQLCancel:PANYARGS
TraceSQLCancel TEXTEQU <__imp_TraceSQLCancel>
extern __imp_TraceSQLColAttributes:PANYARGS
TraceSQLColAttributes TEXTEQU <__imp_TraceSQLColAttributes>
extern __imp_TraceSQLConnect:PANYARGS
TraceSQLConnect TEXTEQU <__imp_TraceSQLConnect>
extern __imp_TraceSQLDescribeCol:PANYARGS
TraceSQLDescribeCol TEXTEQU <__imp_TraceSQLDescribeCol>
extern __imp_TraceSQLDisconnect:PANYARGS
TraceSQLDisconnect TEXTEQU <__imp_TraceSQLDisconnect>
extern __imp_TraceSQLError:PANYARGS
TraceSQLError TEXTEQU <__imp_TraceSQLError>
extern __imp_TraceSQLExecDirect:PANYARGS
TraceSQLExecDirect TEXTEQU <__imp_TraceSQLExecDirect>
extern __imp_TraceSQLExecute:PANYARGS
TraceSQLExecute TEXTEQU <__imp_TraceSQLExecute>
extern __imp_TraceSQLFetch:PANYARGS
TraceSQLFetch TEXTEQU <__imp_TraceSQLFetch>
extern __imp_TraceSQLFreeConnect:PANYARGS
TraceSQLFreeConnect TEXTEQU <__imp_TraceSQLFreeConnect>
extern __imp_TraceSQLFreeEnv:PANYARGS
TraceSQLFreeEnv TEXTEQU <__imp_TraceSQLFreeEnv>
extern __imp_TraceSQLFreeStmt:PANYARGS
TraceSQLFreeStmt TEXTEQU <__imp_TraceSQLFreeStmt>
extern __imp_TraceSQLGetCursorName:PANYARGS
TraceSQLGetCursorName TEXTEQU <__imp_TraceSQLGetCursorName>
extern __imp_TraceSQLNumResultCols:PANYARGS
TraceSQLNumResultCols TEXTEQU <__imp_TraceSQLNumResultCols>
extern __imp_TraceSQLPrepare:PANYARGS
TraceSQLPrepare TEXTEQU <__imp_TraceSQLPrepare>
extern __imp_TraceSQLRowCount:PANYARGS
TraceSQLRowCount TEXTEQU <__imp_TraceSQLRowCount>
extern __imp_TraceSQLSetCursorName:PANYARGS
TraceSQLSetCursorName TEXTEQU <__imp_TraceSQLSetCursorName>
extern __imp_TraceSQLSetParam:PANYARGS
TraceSQLSetParam TEXTEQU <__imp_TraceSQLSetParam>
extern __imp_TraceSQLTransact:PANYARGS
TraceSQLTransact TEXTEQU <__imp_TraceSQLTransact>
extern __imp_TraceSQLAllocHandle:PANYARGS
TraceSQLAllocHandle TEXTEQU <__imp_TraceSQLAllocHandle>
extern __imp_TraceSQLBindParam:PANYARGS
TraceSQLBindParam TEXTEQU <__imp_TraceSQLBindParam>
extern __imp_TraceSQLCloseCursor:PANYARGS
TraceSQLCloseCursor TEXTEQU <__imp_TraceSQLCloseCursor>
extern __imp_TraceSQLColAttribute:PANYARGS
TraceSQLColAttribute TEXTEQU <__imp_TraceSQLColAttribute>
extern __imp_TraceSQLCopyDesc:PANYARGS
TraceSQLCopyDesc TEXTEQU <__imp_TraceSQLCopyDesc>
extern __imp_TraceSQLEndTran:PANYARGS
TraceSQLEndTran TEXTEQU <__imp_TraceSQLEndTran>
extern __imp_TraceSQLFetchScroll:PANYARGS
TraceSQLFetchScroll TEXTEQU <__imp_TraceSQLFetchScroll>
extern __imp_TraceSQLFreeHandle:PANYARGS
TraceSQLFreeHandle TEXTEQU <__imp_TraceSQLFreeHandle>
extern __imp_TraceSQLGetConnectAttr:PANYARGS
TraceSQLGetConnectAttr TEXTEQU <__imp_TraceSQLGetConnectAttr>
extern __imp_TraceSQLGetDescField:PANYARGS
TraceSQLGetDescField TEXTEQU <__imp_TraceSQLGetDescField>
extern __imp_TraceSQLGetDescRec:PANYARGS
TraceSQLGetDescRec TEXTEQU <__imp_TraceSQLGetDescRec>
extern __imp_TraceSQLGetDiagField:PANYARGS
TraceSQLGetDiagField TEXTEQU <__imp_TraceSQLGetDiagField>
extern __imp_TraceSQLGetDiagRec:PANYARGS
TraceSQLGetDiagRec TEXTEQU <__imp_TraceSQLGetDiagRec>
extern __imp_TraceSQLGetEnvAttr:PANYARGS
TraceSQLGetEnvAttr TEXTEQU <__imp_TraceSQLGetEnvAttr>
extern __imp_TraceSQLGetStmtAttr:PANYARGS
TraceSQLGetStmtAttr TEXTEQU <__imp_TraceSQLGetStmtAttr>
extern __imp_TraceSQLSetConnectAttr:PANYARGS
TraceSQLSetConnectAttr TEXTEQU <__imp_TraceSQLSetConnectAttr>
extern __imp_TraceSQLColumns:PANYARGS
TraceSQLColumns TEXTEQU <__imp_TraceSQLColumns>
extern __imp_TraceSQLDriverConnect:PANYARGS
TraceSQLDriverConnect TEXTEQU <__imp_TraceSQLDriverConnect>
extern __imp_TraceSQLGetConnectOption:PANYARGS
TraceSQLGetConnectOption TEXTEQU <__imp_TraceSQLGetConnectOption>
extern __imp_TraceSQLGetData:PANYARGS
TraceSQLGetData TEXTEQU <__imp_TraceSQLGetData>
extern __imp_TraceSQLGetFunctions:PANYARGS
TraceSQLGetFunctions TEXTEQU <__imp_TraceSQLGetFunctions>
extern __imp_TraceSQLGetInfo:PANYARGS
TraceSQLGetInfo TEXTEQU <__imp_TraceSQLGetInfo>
extern __imp_TraceSQLGetStmtOption:PANYARGS
TraceSQLGetStmtOption TEXTEQU <__imp_TraceSQLGetStmtOption>
extern __imp_TraceSQLGetTypeInfo:PANYARGS
TraceSQLGetTypeInfo TEXTEQU <__imp_TraceSQLGetTypeInfo>
extern __imp_TraceSQLParamData:PANYARGS
TraceSQLParamData TEXTEQU <__imp_TraceSQLParamData>
extern __imp_TraceSQLPutData:PANYARGS
TraceSQLPutData TEXTEQU <__imp_TraceSQLPutData>
extern __imp_TraceSQLSetConnectOption:PANYARGS
TraceSQLSetConnectOption TEXTEQU <__imp_TraceSQLSetConnectOption>
extern __imp_TraceSQLSetStmtOption:PANYARGS
TraceSQLSetStmtOption TEXTEQU <__imp_TraceSQLSetStmtOption>
extern __imp_TraceSQLSpecialColumns:PANYARGS
TraceSQLSpecialColumns TEXTEQU <__imp_TraceSQLSpecialColumns>
extern __imp_TraceSQLStatistics:PANYARGS
TraceSQLStatistics TEXTEQU <__imp_TraceSQLStatistics>
extern __imp_TraceSQLTables:PANYARGS
TraceSQLTables TEXTEQU <__imp_TraceSQLTables>
extern __imp_TraceSQLBrowseConnect:PANYARGS
TraceSQLBrowseConnect TEXTEQU <__imp_TraceSQLBrowseConnect>
extern __imp_TraceSQLColumnPrivileges:PANYARGS
TraceSQLColumnPrivileges TEXTEQU <__imp_TraceSQLColumnPrivileges>
extern __imp_TraceSQLDataSources:PANYARGS
TraceSQLDataSources TEXTEQU <__imp_TraceSQLDataSources>
extern __imp_TraceSQLDescribeParam:PANYARGS
TraceSQLDescribeParam TEXTEQU <__imp_TraceSQLDescribeParam>
extern __imp_TraceSQLExtendedFetch:PANYARGS
TraceSQLExtendedFetch TEXTEQU <__imp_TraceSQLExtendedFetch>
extern __imp_TraceSQLForeignKeys:PANYARGS
TraceSQLForeignKeys TEXTEQU <__imp_TraceSQLForeignKeys>
extern __imp_TraceSQLMoreResults:PANYARGS
TraceSQLMoreResults TEXTEQU <__imp_TraceSQLMoreResults>
extern __imp_TraceSQLNativeSql:PANYARGS
TraceSQLNativeSql TEXTEQU <__imp_TraceSQLNativeSql>
extern __imp_TraceSQLNumParams:PANYARGS
TraceSQLNumParams TEXTEQU <__imp_TraceSQLNumParams>
extern __imp_TraceSQLParamOptions:PANYARGS
TraceSQLParamOptions TEXTEQU <__imp_TraceSQLParamOptions>
extern __imp_TraceSQLPrimaryKeys:PANYARGS
TraceSQLPrimaryKeys TEXTEQU <__imp_TraceSQLPrimaryKeys>
extern __imp_TraceSQLProcedureColumns:PANYARGS
TraceSQLProcedureColumns TEXTEQU <__imp_TraceSQLProcedureColumns>
extern __imp_TraceSQLProcedures:PANYARGS
TraceSQLProcedures TEXTEQU <__imp_TraceSQLProcedures>
extern __imp_TraceSQLSetPos:PANYARGS
TraceSQLSetPos TEXTEQU <__imp_TraceSQLSetPos>
extern __imp_TraceSQLSetScrollOptions:PANYARGS
TraceSQLSetScrollOptions TEXTEQU <__imp_TraceSQLSetScrollOptions>
extern __imp_TraceSQLTablePrivileges:PANYARGS
TraceSQLTablePrivileges TEXTEQU <__imp_TraceSQLTablePrivileges>
extern __imp_TraceSQLDrivers:PANYARGS
TraceSQLDrivers TEXTEQU <__imp_TraceSQLDrivers>
extern __imp_TraceSQLBindParameter:PANYARGS
TraceSQLBindParameter TEXTEQU <__imp_TraceSQLBindParameter>
extern __imp_TraceSQLSetDescField:PANYARGS
TraceSQLSetDescField TEXTEQU <__imp_TraceSQLSetDescField>
extern __imp_TraceSQLSetDescRec:PANYARGS
TraceSQLSetDescRec TEXTEQU <__imp_TraceSQLSetDescRec>
extern __imp_TraceSQLSetEnvAttr:PANYARGS
TraceSQLSetEnvAttr TEXTEQU <__imp_TraceSQLSetEnvAttr>
extern __imp_TraceSQLSetStmtAttr:PANYARGS
TraceSQLSetStmtAttr TEXTEQU <__imp_TraceSQLSetStmtAttr>
extern __imp_TraceSQLAllocHandleStd:PANYARGS
TraceSQLAllocHandleStd TEXTEQU <__imp_TraceSQLAllocHandleStd>
extern __imp_TraceSQLBulkOperations:PANYARGS
TraceSQLBulkOperations TEXTEQU <__imp_TraceSQLBulkOperations>
extern __imp_FireVSDebugEvent:PANYARGS
FireVSDebugEvent TEXTEQU <__imp_FireVSDebugEvent>
extern __imp_TraceVSControl:PANYARGS
TraceVSControl TEXTEQU <__imp_TraceVSControl>
extern __imp_odbctrac_ordinal81:PANYARGS
odbctrac_ordinal81 TEXTEQU <__imp_odbctrac_ordinal81>
extern __imp_odbctrac_ordinal82:PANYARGS
odbctrac_ordinal82 TEXTEQU <__imp_odbctrac_ordinal82>
extern __imp_odbctrac_ordinal83:PANYARGS
odbctrac_ordinal83 TEXTEQU <__imp_odbctrac_ordinal83>
extern __imp_odbctrac_ordinal84:PANYARGS
odbctrac_ordinal84 TEXTEQU <__imp_odbctrac_ordinal84>
extern __imp_odbctrac_ordinal85:PANYARGS
odbctrac_ordinal85 TEXTEQU <__imp_odbctrac_ordinal85>
extern __imp_odbctrac_ordinal86:PANYARGS
odbctrac_ordinal86 TEXTEQU <__imp_odbctrac_ordinal86>
extern __imp_odbctrac_ordinal87:PANYARGS
odbctrac_ordinal87 TEXTEQU <__imp_odbctrac_ordinal87>
extern __imp_odbctrac_ordinal88:PANYARGS
odbctrac_ordinal88 TEXTEQU <__imp_odbctrac_ordinal88>
extern __imp_odbctrac_ordinal89:PANYARGS
odbctrac_ordinal89 TEXTEQU <__imp_odbctrac_ordinal89>
extern __imp_odbctrac_ordinal90:PANYARGS
odbctrac_ordinal90 TEXTEQU <__imp_odbctrac_ordinal90>
extern __imp_odbctrac_ordinal91:PANYARGS
odbctrac_ordinal91 TEXTEQU <__imp_odbctrac_ordinal91>
extern __imp_odbctrac_ordinal92:PANYARGS
odbctrac_ordinal92 TEXTEQU <__imp_odbctrac_ordinal92>
extern __imp_odbctrac_ordinal93:PANYARGS
odbctrac_ordinal93 TEXTEQU <__imp_odbctrac_ordinal93>
extern __imp_odbctrac_ordinal94:PANYARGS
odbctrac_ordinal94 TEXTEQU <__imp_odbctrac_ordinal94>
extern __imp_odbctrac_ordinal95:PANYARGS
odbctrac_ordinal95 TEXTEQU <__imp_odbctrac_ordinal95>
extern __imp_odbctrac_ordinal96:PANYARGS
odbctrac_ordinal96 TEXTEQU <__imp_odbctrac_ordinal96>
extern __imp_odbctrac_ordinal97:PANYARGS
odbctrac_ordinal97 TEXTEQU <__imp_odbctrac_ordinal97>
extern __imp_odbctrac_ordinal98:PANYARGS
odbctrac_ordinal98 TEXTEQU <__imp_odbctrac_ordinal98>
extern __imp_odbctrac_ordinal99:PANYARGS
odbctrac_ordinal99 TEXTEQU <__imp_odbctrac_ordinal99>
extern __imp_odbctrac_ordinal100:PANYARGS
odbctrac_ordinal100 TEXTEQU <__imp_odbctrac_ordinal100>
extern __imp_odbctrac_ordinal101:PANYARGS
odbctrac_ordinal101 TEXTEQU <__imp_odbctrac_ordinal101>
extern __imp_odbctrac_ordinal102:PANYARGS
odbctrac_ordinal102 TEXTEQU <__imp_odbctrac_ordinal102>
extern __imp_odbctrac_ordinal103:PANYARGS
odbctrac_ordinal103 TEXTEQU <__imp_odbctrac_ordinal103>
extern __imp_odbctrac_ordinal104:PANYARGS
odbctrac_ordinal104 TEXTEQU <__imp_odbctrac_ordinal104>
extern __imp_odbctrac_ordinal105:PANYARGS
odbctrac_ordinal105 TEXTEQU <__imp_odbctrac_ordinal105>
extern __imp_TraceSQLColAttributesW:PANYARGS
TraceSQLColAttributesW TEXTEQU <__imp_TraceSQLColAttributesW>
extern __imp_TraceSQLConnectW:PANYARGS
TraceSQLConnectW TEXTEQU <__imp_TraceSQLConnectW>
extern __imp_TraceSQLDescribeColW:PANYARGS
TraceSQLDescribeColW TEXTEQU <__imp_TraceSQLDescribeColW>
extern __imp_odbctrac_ordinal109:PANYARGS
odbctrac_ordinal109 TEXTEQU <__imp_odbctrac_ordinal109>
extern __imp_TraceSQLErrorW:PANYARGS
TraceSQLErrorW TEXTEQU <__imp_TraceSQLErrorW>
extern __imp_TraceSQLExecDirectW:PANYARGS
TraceSQLExecDirectW TEXTEQU <__imp_TraceSQLExecDirectW>
extern __imp_odbctrac_ordinal112:PANYARGS
odbctrac_ordinal112 TEXTEQU <__imp_odbctrac_ordinal112>
extern __imp_odbctrac_ordinal113:PANYARGS
odbctrac_ordinal113 TEXTEQU <__imp_odbctrac_ordinal113>
extern __imp_odbctrac_ordinal114:PANYARGS
odbctrac_ordinal114 TEXTEQU <__imp_odbctrac_ordinal114>
extern __imp_odbctrac_ordinal115:PANYARGS
odbctrac_ordinal115 TEXTEQU <__imp_odbctrac_ordinal115>
extern __imp_odbctrac_ordinal116:PANYARGS
odbctrac_ordinal116 TEXTEQU <__imp_odbctrac_ordinal116>
extern __imp_TraceSQLGetCursorNameW:PANYARGS
TraceSQLGetCursorNameW TEXTEQU <__imp_TraceSQLGetCursorNameW>
extern __imp_odbctrac_ordinal118:PANYARGS
odbctrac_ordinal118 TEXTEQU <__imp_odbctrac_ordinal118>
extern __imp_TraceSQLPrepareW:PANYARGS
TraceSQLPrepareW TEXTEQU <__imp_TraceSQLPrepareW>
extern __imp_odbctrac_ordinal120:PANYARGS
odbctrac_ordinal120 TEXTEQU <__imp_odbctrac_ordinal120>
extern __imp_TraceSQLSetCursorNameW:PANYARGS
TraceSQLSetCursorNameW TEXTEQU <__imp_TraceSQLSetCursorNameW>
extern __imp_odbctrac_ordinal122:PANYARGS
odbctrac_ordinal122 TEXTEQU <__imp_odbctrac_ordinal122>
extern __imp_odbctrac_ordinal123:PANYARGS
odbctrac_ordinal123 TEXTEQU <__imp_odbctrac_ordinal123>
extern __imp_odbctrac_ordinal124:PANYARGS
odbctrac_ordinal124 TEXTEQU <__imp_odbctrac_ordinal124>
extern __imp_odbctrac_ordinal125:PANYARGS
odbctrac_ordinal125 TEXTEQU <__imp_odbctrac_ordinal125>
extern __imp_odbctrac_ordinal126:PANYARGS
odbctrac_ordinal126 TEXTEQU <__imp_odbctrac_ordinal126>
extern __imp_TraceSQLColAttributeW:PANYARGS
TraceSQLColAttributeW TEXTEQU <__imp_TraceSQLColAttributeW>
extern __imp_odbctrac_ordinal128:PANYARGS
odbctrac_ordinal128 TEXTEQU <__imp_odbctrac_ordinal128>
extern __imp_odbctrac_ordinal129:PANYARGS
odbctrac_ordinal129 TEXTEQU <__imp_odbctrac_ordinal129>
extern __imp_odbctrac_ordinal130:PANYARGS
odbctrac_ordinal130 TEXTEQU <__imp_odbctrac_ordinal130>
extern __imp_odbctrac_ordinal131:PANYARGS
odbctrac_ordinal131 TEXTEQU <__imp_odbctrac_ordinal131>
extern __imp_TraceSQLGetConnectAttrW:PANYARGS
TraceSQLGetConnectAttrW TEXTEQU <__imp_TraceSQLGetConnectAttrW>
extern __imp_TraceSQLGetDescFieldW:PANYARGS
TraceSQLGetDescFieldW TEXTEQU <__imp_TraceSQLGetDescFieldW>
extern __imp_TraceSQLGetDescRecW:PANYARGS
TraceSQLGetDescRecW TEXTEQU <__imp_TraceSQLGetDescRecW>
extern __imp_TraceSQLGetDiagFieldW:PANYARGS
TraceSQLGetDiagFieldW TEXTEQU <__imp_TraceSQLGetDiagFieldW>
extern __imp_TraceSQLGetDiagRecW:PANYARGS
TraceSQLGetDiagRecW TEXTEQU <__imp_TraceSQLGetDiagRecW>
extern __imp_odbctrac_ordinal137:PANYARGS
odbctrac_ordinal137 TEXTEQU <__imp_odbctrac_ordinal137>
extern __imp_TraceSQLGetStmtAttrW:PANYARGS
TraceSQLGetStmtAttrW TEXTEQU <__imp_TraceSQLGetStmtAttrW>
extern __imp_TraceSQLSetConnectAttrW:PANYARGS
TraceSQLSetConnectAttrW TEXTEQU <__imp_TraceSQLSetConnectAttrW>
extern __imp_TraceSQLColumnsW:PANYARGS
TraceSQLColumnsW TEXTEQU <__imp_TraceSQLColumnsW>
extern __imp_TraceSQLDriverConnectW:PANYARGS
TraceSQLDriverConnectW TEXTEQU <__imp_TraceSQLDriverConnectW>
extern __imp_TraceSQLGetConnectOptionW:PANYARGS
TraceSQLGetConnectOptionW TEXTEQU <__imp_TraceSQLGetConnectOptionW>
extern __imp_odbctrac_ordinal143:PANYARGS
odbctrac_ordinal143 TEXTEQU <__imp_odbctrac_ordinal143>
extern __imp_odbctrac_ordinal144:PANYARGS
odbctrac_ordinal144 TEXTEQU <__imp_odbctrac_ordinal144>
extern __imp_TraceSQLGetInfoW:PANYARGS
TraceSQLGetInfoW TEXTEQU <__imp_TraceSQLGetInfoW>
extern __imp_odbctrac_ordinal146:PANYARGS
odbctrac_ordinal146 TEXTEQU <__imp_odbctrac_ordinal146>
extern __imp_TraceSQLGetTypeInfoW:PANYARGS
TraceSQLGetTypeInfoW TEXTEQU <__imp_TraceSQLGetTypeInfoW>
extern __imp_odbctrac_ordinal148:PANYARGS
odbctrac_ordinal148 TEXTEQU <__imp_odbctrac_ordinal148>
extern __imp_odbctrac_ordinal149:PANYARGS
odbctrac_ordinal149 TEXTEQU <__imp_odbctrac_ordinal149>
extern __imp_TraceSQLSetConnectOptionW:PANYARGS
TraceSQLSetConnectOptionW TEXTEQU <__imp_TraceSQLSetConnectOptionW>
extern __imp_odbctrac_ordinal151:PANYARGS
odbctrac_ordinal151 TEXTEQU <__imp_odbctrac_ordinal151>
extern __imp_TraceSQLSpecialColumnsW:PANYARGS
TraceSQLSpecialColumnsW TEXTEQU <__imp_TraceSQLSpecialColumnsW>
extern __imp_TraceSQLStatisticsW:PANYARGS
TraceSQLStatisticsW TEXTEQU <__imp_TraceSQLStatisticsW>
extern __imp_TraceSQLTablesW:PANYARGS
TraceSQLTablesW TEXTEQU <__imp_TraceSQLTablesW>
extern __imp_TraceSQLBrowseConnectW:PANYARGS
TraceSQLBrowseConnectW TEXTEQU <__imp_TraceSQLBrowseConnectW>
extern __imp_TraceSQLColumnPrivilegesW:PANYARGS
TraceSQLColumnPrivilegesW TEXTEQU <__imp_TraceSQLColumnPrivilegesW>
extern __imp_TraceSQLDataSourcesW:PANYARGS
TraceSQLDataSourcesW TEXTEQU <__imp_TraceSQLDataSourcesW>
extern __imp_odbctrac_ordinal158:PANYARGS
odbctrac_ordinal158 TEXTEQU <__imp_odbctrac_ordinal158>
extern __imp_odbctrac_ordinal159:PANYARGS
odbctrac_ordinal159 TEXTEQU <__imp_odbctrac_ordinal159>
extern __imp_TraceSQLForeignKeysW:PANYARGS
TraceSQLForeignKeysW TEXTEQU <__imp_TraceSQLForeignKeysW>
extern __imp_odbctrac_ordinal161:PANYARGS
odbctrac_ordinal161 TEXTEQU <__imp_odbctrac_ordinal161>
extern __imp_TraceSQLNativeSqlW:PANYARGS
TraceSQLNativeSqlW TEXTEQU <__imp_TraceSQLNativeSqlW>
extern __imp_odbctrac_ordinal163:PANYARGS
odbctrac_ordinal163 TEXTEQU <__imp_odbctrac_ordinal163>
extern __imp_odbctrac_ordinal164:PANYARGS
odbctrac_ordinal164 TEXTEQU <__imp_odbctrac_ordinal164>
extern __imp_TraceSQLPrimaryKeysW:PANYARGS
TraceSQLPrimaryKeysW TEXTEQU <__imp_TraceSQLPrimaryKeysW>
extern __imp_TraceSQLProcedureColumnsW:PANYARGS
TraceSQLProcedureColumnsW TEXTEQU <__imp_TraceSQLProcedureColumnsW>
extern __imp_TraceSQLProceduresW:PANYARGS
TraceSQLProceduresW TEXTEQU <__imp_TraceSQLProceduresW>
extern __imp_odbctrac_ordinal168:PANYARGS
odbctrac_ordinal168 TEXTEQU <__imp_odbctrac_ordinal168>
extern __imp_odbctrac_ordinal169:PANYARGS
odbctrac_ordinal169 TEXTEQU <__imp_odbctrac_ordinal169>
extern __imp_TraceSQLTablePrivilegesW:PANYARGS
TraceSQLTablePrivilegesW TEXTEQU <__imp_TraceSQLTablePrivilegesW>
extern __imp_TraceSQLDriversW:PANYARGS
TraceSQLDriversW TEXTEQU <__imp_TraceSQLDriversW>
extern __imp_odbctrac_ordinal172:PANYARGS
odbctrac_ordinal172 TEXTEQU <__imp_odbctrac_ordinal172>
extern __imp_TraceSQLSetDescFieldW:PANYARGS
TraceSQLSetDescFieldW TEXTEQU <__imp_TraceSQLSetDescFieldW>
extern __imp_odbctrac_ordinal174:PANYARGS
odbctrac_ordinal174 TEXTEQU <__imp_odbctrac_ordinal174>
extern __imp_odbctrac_ordinal175:PANYARGS
odbctrac_ordinal175 TEXTEQU <__imp_odbctrac_ordinal175>
extern __imp_TraceSQLSetStmtAttrW:PANYARGS
TraceSQLSetStmtAttrW TEXTEQU <__imp_TraceSQLSetStmtAttrW>
extern __imp_TraceSQLAllocHandleStdW:PANYARGS
TraceSQLAllocHandleStdW TEXTEQU <__imp_TraceSQLAllocHandleStdW>
extern __imp_odbctrac_ordinal178:PANYARGS
odbctrac_ordinal178 TEXTEQU <__imp_odbctrac_ordinal178>
extern __imp_odbctrac_ordinal179:PANYARGS
odbctrac_ordinal179 TEXTEQU <__imp_odbctrac_ordinal179>
extern __imp_odbctrac_ordinal180:PANYARGS
odbctrac_ordinal180 TEXTEQU <__imp_odbctrac_ordinal180>
extern __imp_odbctrac_ordinal181:PANYARGS
odbctrac_ordinal181 TEXTEQU <__imp_odbctrac_ordinal181>
extern __imp_odbctrac_ordinal182:PANYARGS
odbctrac_ordinal182 TEXTEQU <__imp_odbctrac_ordinal182>
extern __imp_odbctrac_ordinal183:PANYARGS
odbctrac_ordinal183 TEXTEQU <__imp_odbctrac_ordinal183>
extern __imp_odbctrac_ordinal184:PANYARGS
odbctrac_ordinal184 TEXTEQU <__imp_odbctrac_ordinal184>
extern __imp_odbctrac_ordinal185:PANYARGS
odbctrac_ordinal185 TEXTEQU <__imp_odbctrac_ordinal185>
extern __imp_odbctrac_ordinal186:PANYARGS
odbctrac_ordinal186 TEXTEQU <__imp_odbctrac_ordinal186>
extern __imp_odbctrac_ordinal187:PANYARGS
odbctrac_ordinal187 TEXTEQU <__imp_odbctrac_ordinal187>
extern __imp_odbctrac_ordinal188:PANYARGS
odbctrac_ordinal188 TEXTEQU <__imp_odbctrac_ordinal188>
extern __imp_odbctrac_ordinal189:PANYARGS
odbctrac_ordinal189 TEXTEQU <__imp_odbctrac_ordinal189>
extern __imp_odbctrac_ordinal190:PANYARGS
odbctrac_ordinal190 TEXTEQU <__imp_odbctrac_ordinal190>
extern __imp_odbctrac_ordinal191:PANYARGS
odbctrac_ordinal191 TEXTEQU <__imp_odbctrac_ordinal191>
extern __imp_odbctrac_ordinal192:PANYARGS
odbctrac_ordinal192 TEXTEQU <__imp_odbctrac_ordinal192>
extern __imp_odbctrac_ordinal193:PANYARGS
odbctrac_ordinal193 TEXTEQU <__imp_odbctrac_ordinal193>
extern __imp_odbctrac_ordinal194:PANYARGS
odbctrac_ordinal194 TEXTEQU <__imp_odbctrac_ordinal194>
extern __imp_odbctrac_ordinal195:PANYARGS
odbctrac_ordinal195 TEXTEQU <__imp_odbctrac_ordinal195>
extern __imp_odbctrac_ordinal196:PANYARGS
odbctrac_ordinal196 TEXTEQU <__imp_odbctrac_ordinal196>
extern __imp_odbctrac_ordinal197:PANYARGS
odbctrac_ordinal197 TEXTEQU <__imp_odbctrac_ordinal197>
extern __imp_odbctrac_ordinal198:PANYARGS
odbctrac_ordinal198 TEXTEQU <__imp_odbctrac_ordinal198>
extern __imp_odbctrac_ordinal199:PANYARGS
odbctrac_ordinal199 TEXTEQU <__imp_odbctrac_ordinal199>
extern __imp_odbctrac_ordinal200:PANYARGS
odbctrac_ordinal200 TEXTEQU <__imp_odbctrac_ordinal200>
extern __imp_odbctrac_ordinal201:PANYARGS
odbctrac_ordinal201 TEXTEQU <__imp_odbctrac_ordinal201>
extern __imp_odbctrac_ordinal202:PANYARGS
odbctrac_ordinal202 TEXTEQU <__imp_odbctrac_ordinal202>
extern __imp_odbctrac_ordinal203:PANYARGS
odbctrac_ordinal203 TEXTEQU <__imp_odbctrac_ordinal203>
extern __imp_odbctrac_ordinal204:PANYARGS
odbctrac_ordinal204 TEXTEQU <__imp_odbctrac_ordinal204>
extern __imp_odbctrac_ordinal205:PANYARGS
odbctrac_ordinal205 TEXTEQU <__imp_odbctrac_ordinal205>
extern __imp_odbctrac_ordinal206:PANYARGS
odbctrac_ordinal206 TEXTEQU <__imp_odbctrac_ordinal206>
extern __imp_odbctrac_ordinal207:PANYARGS
odbctrac_ordinal207 TEXTEQU <__imp_odbctrac_ordinal207>
extern __imp_odbctrac_ordinal208:PANYARGS
odbctrac_ordinal208 TEXTEQU <__imp_odbctrac_ordinal208>
extern __imp_odbctrac_ordinal209:PANYARGS
odbctrac_ordinal209 TEXTEQU <__imp_odbctrac_ordinal209>
extern __imp_odbctrac_ordinal210:PANYARGS
odbctrac_ordinal210 TEXTEQU <__imp_odbctrac_ordinal210>
extern __imp_odbctrac_ordinal211:PANYARGS
odbctrac_ordinal211 TEXTEQU <__imp_odbctrac_ordinal211>
extern __imp_odbctrac_ordinal212:PANYARGS
odbctrac_ordinal212 TEXTEQU <__imp_odbctrac_ordinal212>
extern __imp_odbctrac_ordinal213:PANYARGS
odbctrac_ordinal213 TEXTEQU <__imp_odbctrac_ordinal213>
extern __imp_odbctrac_ordinal214:PANYARGS
odbctrac_ordinal214 TEXTEQU <__imp_odbctrac_ordinal214>
extern __imp_odbctrac_ordinal215:PANYARGS
odbctrac_ordinal215 TEXTEQU <__imp_odbctrac_ordinal215>
extern __imp_odbctrac_ordinal216:PANYARGS
odbctrac_ordinal216 TEXTEQU <__imp_odbctrac_ordinal216>
extern __imp_odbctrac_ordinal217:PANYARGS
odbctrac_ordinal217 TEXTEQU <__imp_odbctrac_ordinal217>
extern __imp_odbctrac_ordinal218:PANYARGS
odbctrac_ordinal218 TEXTEQU <__imp_odbctrac_ordinal218>
extern __imp_odbctrac_ordinal219:PANYARGS
odbctrac_ordinal219 TEXTEQU <__imp_odbctrac_ordinal219>
extern __imp_odbctrac_ordinal220:PANYARGS
odbctrac_ordinal220 TEXTEQU <__imp_odbctrac_ordinal220>
extern __imp_odbctrac_ordinal221:PANYARGS
odbctrac_ordinal221 TEXTEQU <__imp_odbctrac_ordinal221>
extern __imp_odbctrac_ordinal222:PANYARGS
odbctrac_ordinal222 TEXTEQU <__imp_odbctrac_ordinal222>
extern __imp_odbctrac_ordinal223:PANYARGS
odbctrac_ordinal223 TEXTEQU <__imp_odbctrac_ordinal223>
extern __imp_odbctrac_ordinal224:PANYARGS
odbctrac_ordinal224 TEXTEQU <__imp_odbctrac_ordinal224>
extern __imp_odbctrac_ordinal225:PANYARGS
odbctrac_ordinal225 TEXTEQU <__imp_odbctrac_ordinal225>
extern __imp_odbctrac_ordinal226:PANYARGS
odbctrac_ordinal226 TEXTEQU <__imp_odbctrac_ordinal226>
extern __imp_odbctrac_ordinal227:PANYARGS
odbctrac_ordinal227 TEXTEQU <__imp_odbctrac_ordinal227>
extern __imp_odbctrac_ordinal228:PANYARGS
odbctrac_ordinal228 TEXTEQU <__imp_odbctrac_ordinal228>
extern __imp_odbctrac_ordinal229:PANYARGS
odbctrac_ordinal229 TEXTEQU <__imp_odbctrac_ordinal229>
extern __imp_odbctrac_ordinal230:PANYARGS
odbctrac_ordinal230 TEXTEQU <__imp_odbctrac_ordinal230>
extern __imp_odbctrac_ordinal231:PANYARGS
odbctrac_ordinal231 TEXTEQU <__imp_odbctrac_ordinal231>
extern __imp_odbctrac_ordinal232:PANYARGS
odbctrac_ordinal232 TEXTEQU <__imp_odbctrac_ordinal232>
extern __imp_odbctrac_ordinal233:PANYARGS
odbctrac_ordinal233 TEXTEQU <__imp_odbctrac_ordinal233>
extern __imp_odbctrac_ordinal234:PANYARGS
odbctrac_ordinal234 TEXTEQU <__imp_odbctrac_ordinal234>
extern __imp_odbctrac_ordinal235:PANYARGS
odbctrac_ordinal235 TEXTEQU <__imp_odbctrac_ordinal235>
extern __imp_odbctrac_ordinal236:PANYARGS
odbctrac_ordinal236 TEXTEQU <__imp_odbctrac_ordinal236>
extern __imp_odbctrac_ordinal237:PANYARGS
odbctrac_ordinal237 TEXTEQU <__imp_odbctrac_ordinal237>
extern __imp_odbctrac_ordinal238:PANYARGS
odbctrac_ordinal238 TEXTEQU <__imp_odbctrac_ordinal238>
extern __imp_odbctrac_ordinal239:PANYARGS
odbctrac_ordinal239 TEXTEQU <__imp_odbctrac_ordinal239>
extern __imp_odbctrac_ordinal240:PANYARGS
odbctrac_ordinal240 TEXTEQU <__imp_odbctrac_ordinal240>
extern __imp_odbctrac_ordinal241:PANYARGS
odbctrac_ordinal241 TEXTEQU <__imp_odbctrac_ordinal241>
extern __imp_odbctrac_ordinal242:PANYARGS
odbctrac_ordinal242 TEXTEQU <__imp_odbctrac_ordinal242>
extern __imp_odbctrac_ordinal243:PANYARGS
odbctrac_ordinal243 TEXTEQU <__imp_odbctrac_ordinal243>
extern __imp_odbctrac_ordinal244:PANYARGS
odbctrac_ordinal244 TEXTEQU <__imp_odbctrac_ordinal244>
extern __imp_odbctrac_ordinal245:PANYARGS
odbctrac_ordinal245 TEXTEQU <__imp_odbctrac_ordinal245>
extern __imp_odbctrac_ordinal246:PANYARGS
odbctrac_ordinal246 TEXTEQU <__imp_odbctrac_ordinal246>
extern __imp_odbctrac_ordinal247:PANYARGS
odbctrac_ordinal247 TEXTEQU <__imp_odbctrac_ordinal247>
extern __imp_odbctrac_ordinal248:PANYARGS
odbctrac_ordinal248 TEXTEQU <__imp_odbctrac_ordinal248>
extern __imp_odbctrac_ordinal249:PANYARGS
odbctrac_ordinal249 TEXTEQU <__imp_odbctrac_ordinal249>
extern __imp_odbctrac_ordinal250:PANYARGS
odbctrac_ordinal250 TEXTEQU <__imp_odbctrac_ordinal250>
extern __imp_odbctrac_ordinal251:PANYARGS
odbctrac_ordinal251 TEXTEQU <__imp_odbctrac_ordinal251>
extern __imp_odbctrac_ordinal252:PANYARGS
odbctrac_ordinal252 TEXTEQU <__imp_odbctrac_ordinal252>
extern __imp_odbctrac_ordinal253:PANYARGS
odbctrac_ordinal253 TEXTEQU <__imp_odbctrac_ordinal253>
extern __imp_odbctrac_ordinal254:PANYARGS
odbctrac_ordinal254 TEXTEQU <__imp_odbctrac_ordinal254>
extern __imp_odbctrac_ordinal255:PANYARGS
odbctrac_ordinal255 TEXTEQU <__imp_odbctrac_ordinal255>
extern __imp_odbctrac_ordinal256:PANYARGS
odbctrac_ordinal256 TEXTEQU <__imp_odbctrac_ordinal256>
extern __imp_odbctrac_ordinal257:PANYARGS
odbctrac_ordinal257 TEXTEQU <__imp_odbctrac_ordinal257>
extern __imp_odbctrac_ordinal258:PANYARGS
odbctrac_ordinal258 TEXTEQU <__imp_odbctrac_ordinal258>
extern __imp_odbctrac_ordinal259:PANYARGS
odbctrac_ordinal259 TEXTEQU <__imp_odbctrac_ordinal259>
extern __imp_odbctrac_ordinal260:PANYARGS
odbctrac_ordinal260 TEXTEQU <__imp_odbctrac_ordinal260>
extern __imp_odbctrac_ordinal261:PANYARGS
odbctrac_ordinal261 TEXTEQU <__imp_odbctrac_ordinal261>
extern __imp_odbctrac_ordinal262:PANYARGS
odbctrac_ordinal262 TEXTEQU <__imp_odbctrac_ordinal262>
extern __imp_odbctrac_ordinal263:PANYARGS
odbctrac_ordinal263 TEXTEQU <__imp_odbctrac_ordinal263>
extern __imp_odbctrac_ordinal264:PANYARGS
odbctrac_ordinal264 TEXTEQU <__imp_odbctrac_ordinal264>
extern __imp_odbctrac_ordinal265:PANYARGS
odbctrac_ordinal265 TEXTEQU <__imp_odbctrac_ordinal265>
extern __imp_odbctrac_ordinal266:PANYARGS
odbctrac_ordinal266 TEXTEQU <__imp_odbctrac_ordinal266>
extern __imp_odbctrac_ordinal267:PANYARGS
odbctrac_ordinal267 TEXTEQU <__imp_odbctrac_ordinal267>
extern __imp_odbctrac_ordinal268:PANYARGS
odbctrac_ordinal268 TEXTEQU <__imp_odbctrac_ordinal268>
extern __imp_odbctrac_ordinal269:PANYARGS
odbctrac_ordinal269 TEXTEQU <__imp_odbctrac_ordinal269>
extern __imp_odbctrac_ordinal270:PANYARGS
odbctrac_ordinal270 TEXTEQU <__imp_odbctrac_ordinal270>
extern __imp_odbctrac_ordinal271:PANYARGS
odbctrac_ordinal271 TEXTEQU <__imp_odbctrac_ordinal271>
extern __imp_odbctrac_ordinal272:PANYARGS
odbctrac_ordinal272 TEXTEQU <__imp_odbctrac_ordinal272>
extern __imp_odbctrac_ordinal273:PANYARGS
odbctrac_ordinal273 TEXTEQU <__imp_odbctrac_ordinal273>
extern __imp_odbctrac_ordinal274:PANYARGS
odbctrac_ordinal274 TEXTEQU <__imp_odbctrac_ordinal274>
extern __imp_odbctrac_ordinal275:PANYARGS
odbctrac_ordinal275 TEXTEQU <__imp_odbctrac_ordinal275>
extern __imp_odbctrac_ordinal276:PANYARGS
odbctrac_ordinal276 TEXTEQU <__imp_odbctrac_ordinal276>
extern __imp_odbctrac_ordinal277:PANYARGS
odbctrac_ordinal277 TEXTEQU <__imp_odbctrac_ordinal277>
extern __imp_odbctrac_ordinal278:PANYARGS
odbctrac_ordinal278 TEXTEQU <__imp_odbctrac_ordinal278>
extern __imp_odbctrac_ordinal279:PANYARGS
odbctrac_ordinal279 TEXTEQU <__imp_odbctrac_ordinal279>
extern __imp_odbctrac_ordinal280:PANYARGS
odbctrac_ordinal280 TEXTEQU <__imp_odbctrac_ordinal280>
extern __imp_odbctrac_ordinal281:PANYARGS
odbctrac_ordinal281 TEXTEQU <__imp_odbctrac_ordinal281>
extern __imp_odbctrac_ordinal282:PANYARGS
odbctrac_ordinal282 TEXTEQU <__imp_odbctrac_ordinal282>
extern __imp_odbctrac_ordinal283:PANYARGS
odbctrac_ordinal283 TEXTEQU <__imp_odbctrac_ordinal283>
extern __imp_odbctrac_ordinal284:PANYARGS
odbctrac_ordinal284 TEXTEQU <__imp_odbctrac_ordinal284>
extern __imp_odbctrac_ordinal285:PANYARGS
odbctrac_ordinal285 TEXTEQU <__imp_odbctrac_ordinal285>
extern __imp_odbctrac_ordinal286:PANYARGS
odbctrac_ordinal286 TEXTEQU <__imp_odbctrac_ordinal286>
extern __imp_odbctrac_ordinal287:PANYARGS
odbctrac_ordinal287 TEXTEQU <__imp_odbctrac_ordinal287>
extern __imp_odbctrac_ordinal288:PANYARGS
odbctrac_ordinal288 TEXTEQU <__imp_odbctrac_ordinal288>
extern __imp_odbctrac_ordinal289:PANYARGS
odbctrac_ordinal289 TEXTEQU <__imp_odbctrac_ordinal289>
extern __imp_odbctrac_ordinal290:PANYARGS
odbctrac_ordinal290 TEXTEQU <__imp_odbctrac_ordinal290>
extern __imp_odbctrac_ordinal291:PANYARGS
odbctrac_ordinal291 TEXTEQU <__imp_odbctrac_ordinal291>
extern __imp_odbctrac_ordinal292:PANYARGS
odbctrac_ordinal292 TEXTEQU <__imp_odbctrac_ordinal292>
extern __imp_odbctrac_ordinal293:PANYARGS
odbctrac_ordinal293 TEXTEQU <__imp_odbctrac_ordinal293>
extern __imp_odbctrac_ordinal294:PANYARGS
odbctrac_ordinal294 TEXTEQU <__imp_odbctrac_ordinal294>
extern __imp_odbctrac_ordinal295:PANYARGS
odbctrac_ordinal295 TEXTEQU <__imp_odbctrac_ordinal295>
extern __imp_odbctrac_ordinal296:PANYARGS
odbctrac_ordinal296 TEXTEQU <__imp_odbctrac_ordinal296>
extern __imp_odbctrac_ordinal297:PANYARGS
odbctrac_ordinal297 TEXTEQU <__imp_odbctrac_ordinal297>
extern __imp_odbctrac_ordinal298:PANYARGS
odbctrac_ordinal298 TEXTEQU <__imp_odbctrac_ordinal298>
extern __imp_odbctrac_ordinal299:PANYARGS
odbctrac_ordinal299 TEXTEQU <__imp_odbctrac_ordinal299>
extern __imp_TraceReturn:PANYARGS
TraceReturn TEXTEQU <__imp_TraceReturn>
extern __imp_TraceOpenLogFile:PANYARGS
TraceOpenLogFile TEXTEQU <__imp_TraceOpenLogFile>
extern __imp_TraceCloseLogFile:PANYARGS
TraceCloseLogFile TEXTEQU <__imp_TraceCloseLogFile>
extern __imp_TraceVersion:PANYARGS
TraceVersion TEXTEQU <__imp_TraceVersion>
