extern __imp_SQLBindCol:PANYARGS
SQLBindCol TEXTEQU <__imp_SQLBindCol>
extern __imp_SQLCancel:PANYARGS
SQLCancel TEXTEQU <__imp_SQLCancel>
extern __imp_ReleaseCLStmtResources:PANYARGS
ReleaseCLStmtResources TEXTEQU <__imp_ReleaseCLStmtResources>
extern __imp_odbccu32_ordinal7:PANYARGS
odbccu32_ordinal7 TEXTEQU <__imp_odbccu32_ordinal7>
extern __imp_odbccu32_ordinal8:PANYARGS
odbccu32_ordinal8 TEXTEQU <__imp_odbccu32_ordinal8>
extern __imp_odbccu32_ordinal9:PANYARGS
odbccu32_ordinal9 TEXTEQU <__imp_odbccu32_ordinal9>
extern __imp_odbccu32_ordinal10:PANYARGS
odbccu32_ordinal10 TEXTEQU <__imp_odbccu32_ordinal10>
extern __imp_SQLExecDirect:PANYARGS
SQLExecDirect TEXTEQU <__imp_SQLExecDirect>
extern __imp_SQLExecute:PANYARGS
SQLExecute TEXTEQU <__imp_SQLExecute>
extern __imp_SQLFetch:PANYARGS
SQLFetch TEXTEQU <__imp_SQLFetch>
extern __imp_odbccu32_ordinal14:PANYARGS
odbccu32_ordinal14 TEXTEQU <__imp_odbccu32_ordinal14>
extern __imp_odbccu32_ordinal15:PANYARGS
odbccu32_ordinal15 TEXTEQU <__imp_odbccu32_ordinal15>
extern __imp_SQLFreeStmt:PANYARGS
SQLFreeStmt TEXTEQU <__imp_SQLFreeStmt>
extern __imp_odbccu32_ordinal17:PANYARGS
odbccu32_ordinal17 TEXTEQU <__imp_odbccu32_ordinal17>
extern __imp_odbccu32_ordinal18:PANYARGS
odbccu32_ordinal18 TEXTEQU <__imp_odbccu32_ordinal18>
extern __imp_SQLPrepare:PANYARGS
SQLPrepare TEXTEQU <__imp_SQLPrepare>
extern __imp_SQLRowCount:PANYARGS
SQLRowCount TEXTEQU <__imp_SQLRowCount>
extern __imp_odbccu32_ordinal21:PANYARGS
odbccu32_ordinal21 TEXTEQU <__imp_odbccu32_ordinal21>
extern __imp_odbccu32_ordinal22:PANYARGS
odbccu32_ordinal22 TEXTEQU <__imp_odbccu32_ordinal22>
extern __imp_SQLTransact:PANYARGS
SQLTransact TEXTEQU <__imp_SQLTransact>
extern __imp_odbccu32_ordinal24:PANYARGS
odbccu32_ordinal24 TEXTEQU <__imp_odbccu32_ordinal24>
extern __imp_odbccu32_ordinal25:PANYARGS
odbccu32_ordinal25 TEXTEQU <__imp_odbccu32_ordinal25>
extern __imp_SQLCloseCursor:PANYARGS
SQLCloseCursor TEXTEQU <__imp_SQLCloseCursor>
extern __imp_odbccu32_ordinal27:PANYARGS
odbccu32_ordinal27 TEXTEQU <__imp_odbccu32_ordinal27>
extern __imp_odbccu32_ordinal28:PANYARGS
odbccu32_ordinal28 TEXTEQU <__imp_odbccu32_ordinal28>
extern __imp_SQLEndTran:PANYARGS
SQLEndTran TEXTEQU <__imp_SQLEndTran>
extern __imp_SQLFetchScroll:PANYARGS
SQLFetchScroll TEXTEQU <__imp_SQLFetchScroll>
extern __imp_SQLFreeHandle:PANYARGS
SQLFreeHandle TEXTEQU <__imp_SQLFreeHandle>
extern __imp_odbccu32_ordinal32:PANYARGS
odbccu32_ordinal32 TEXTEQU <__imp_odbccu32_ordinal32>
extern __imp_SQLGetDescField:PANYARGS
SQLGetDescField TEXTEQU <__imp_SQLGetDescField>
extern __imp_SQLGetDescRec:PANYARGS
SQLGetDescRec TEXTEQU <__imp_SQLGetDescRec>
extern __imp_odbccu32_ordinal35:PANYARGS
odbccu32_ordinal35 TEXTEQU <__imp_odbccu32_ordinal35>
extern __imp_odbccu32_ordinal36:PANYARGS
odbccu32_ordinal36 TEXTEQU <__imp_odbccu32_ordinal36>
extern __imp_odbccu32_ordinal37:PANYARGS
odbccu32_ordinal37 TEXTEQU <__imp_odbccu32_ordinal37>
extern __imp_SQLGetStmtAttr:PANYARGS
SQLGetStmtAttr TEXTEQU <__imp_SQLGetStmtAttr>
extern __imp_SQLSetConnectAttr:PANYARGS
SQLSetConnectAttr TEXTEQU <__imp_SQLSetConnectAttr>
extern __imp_odbccu32_ordinal40:PANYARGS
odbccu32_ordinal40 TEXTEQU <__imp_odbccu32_ordinal40>
extern __imp_odbccu32_ordinal41:PANYARGS
odbccu32_ordinal41 TEXTEQU <__imp_odbccu32_ordinal41>
extern __imp_odbccu32_ordinal42:PANYARGS
odbccu32_ordinal42 TEXTEQU <__imp_odbccu32_ordinal42>
extern __imp_SQLGetData:PANYARGS
SQLGetData TEXTEQU <__imp_SQLGetData>
extern __imp_odbccu32_ordinal44:PANYARGS
odbccu32_ordinal44 TEXTEQU <__imp_odbccu32_ordinal44>
extern __imp_SQLGetInfo:PANYARGS
SQLGetInfo TEXTEQU <__imp_SQLGetInfo>
extern __imp_SQLGetStmtOption:PANYARGS
SQLGetStmtOption TEXTEQU <__imp_SQLGetStmtOption>
extern __imp_odbccu32_ordinal47:PANYARGS
odbccu32_ordinal47 TEXTEQU <__imp_odbccu32_ordinal47>
extern __imp_SQLParamData:PANYARGS
SQLParamData TEXTEQU <__imp_SQLParamData>
extern __imp_SQLPutData:PANYARGS
SQLPutData TEXTEQU <__imp_SQLPutData>
extern __imp_SQLSetConnectOption:PANYARGS
SQLSetConnectOption TEXTEQU <__imp_SQLSetConnectOption>
extern __imp_SQLSetStmtOption:PANYARGS
SQLSetStmtOption TEXTEQU <__imp_SQLSetStmtOption>
extern __imp_odbccu32_ordinal52:PANYARGS
odbccu32_ordinal52 TEXTEQU <__imp_odbccu32_ordinal52>
extern __imp_odbccu32_ordinal53:PANYARGS
odbccu32_ordinal53 TEXTEQU <__imp_odbccu32_ordinal53>
extern __imp_odbccu32_ordinal54:PANYARGS
odbccu32_ordinal54 TEXTEQU <__imp_odbccu32_ordinal54>
extern __imp_odbccu32_ordinal55:PANYARGS
odbccu32_ordinal55 TEXTEQU <__imp_odbccu32_ordinal55>
extern __imp_odbccu32_ordinal56:PANYARGS
odbccu32_ordinal56 TEXTEQU <__imp_odbccu32_ordinal56>
extern __imp_odbccu32_ordinal57:PANYARGS
odbccu32_ordinal57 TEXTEQU <__imp_odbccu32_ordinal57>
extern __imp_odbccu32_ordinal58:PANYARGS
odbccu32_ordinal58 TEXTEQU <__imp_odbccu32_ordinal58>
extern __imp_SQLExtendedFetch:PANYARGS
SQLExtendedFetch TEXTEQU <__imp_SQLExtendedFetch>
extern __imp_odbccu32_ordinal60:PANYARGS
odbccu32_ordinal60 TEXTEQU <__imp_odbccu32_ordinal60>
extern __imp_SQLMoreResults:PANYARGS
SQLMoreResults TEXTEQU <__imp_SQLMoreResults>
extern __imp_SQLNativeSql:PANYARGS
SQLNativeSql TEXTEQU <__imp_SQLNativeSql>
extern __imp_SQLNumParams:PANYARGS
SQLNumParams TEXTEQU <__imp_SQLNumParams>
extern __imp_SQLParamOptions:PANYARGS
SQLParamOptions TEXTEQU <__imp_SQLParamOptions>
extern __imp_odbccu32_ordinal65:PANYARGS
odbccu32_ordinal65 TEXTEQU <__imp_odbccu32_ordinal65>
extern __imp_odbccu32_ordinal66:PANYARGS
odbccu32_ordinal66 TEXTEQU <__imp_odbccu32_ordinal66>
extern __imp_odbccu32_ordinal67:PANYARGS
odbccu32_ordinal67 TEXTEQU <__imp_odbccu32_ordinal67>
extern __imp_SQLSetPos:PANYARGS
SQLSetPos TEXTEQU <__imp_SQLSetPos>
extern __imp_SQLSetScrollOptions:PANYARGS
SQLSetScrollOptions TEXTEQU <__imp_SQLSetScrollOptions>
extern __imp_odbccu32_ordinal70:PANYARGS
odbccu32_ordinal70 TEXTEQU <__imp_odbccu32_ordinal70>
extern __imp_odbccu32_ordinal71:PANYARGS
odbccu32_ordinal71 TEXTEQU <__imp_odbccu32_ordinal71>
extern __imp_SQLBindParameter:PANYARGS
SQLBindParameter TEXTEQU <__imp_SQLBindParameter>
extern __imp_SQLSetDescField:PANYARGS
SQLSetDescField TEXTEQU <__imp_SQLSetDescField>
extern __imp_SQLSetDescRec:PANYARGS
SQLSetDescRec TEXTEQU <__imp_SQLSetDescRec>
extern __imp_odbccu32_ordinal75:PANYARGS
odbccu32_ordinal75 TEXTEQU <__imp_odbccu32_ordinal75>
extern __imp_SQLSetStmtAttr:PANYARGS
SQLSetStmtAttr TEXTEQU <__imp_SQLSetStmtAttr>
extern __imp_odbccu32_ordinal77:PANYARGS
odbccu32_ordinal77 TEXTEQU <__imp_odbccu32_ordinal77>
extern __imp_SQLBulkOperations:PANYARGS
SQLBulkOperations TEXTEQU <__imp_SQLBulkOperations>
