extern __imp_CoVrfCheckThreadState:PANYARGS
CoVrfCheckThreadState TEXTEQU <__imp_CoVrfCheckThreadState>
extern __imp_CoVrfGetThreadState:PANYARGS
CoVrfGetThreadState TEXTEQU <__imp_CoVrfGetThreadState>
extern __imp_CoVrfReleaseThreadState:PANYARGS
CoVrfReleaseThreadState TEXTEQU <__imp_CoVrfReleaseThreadState>
extern __imp_PropVariantChangeType:PANYARGS
PropVariantChangeType TEXTEQU <__imp_PropVariantChangeType>
extern __imp_BindMoniker:PANYARGS
BindMoniker TEXTEQU <__imp_BindMoniker>
extern __imp_CLIPFORMAT_UserFree:PANYARGS
CLIPFORMAT_UserFree TEXTEQU <__imp_CLIPFORMAT_UserFree>
extern __imp_CLIPFORMAT_UserFree64:PANYARGS
CLIPFORMAT_UserFree64 TEXTEQU <__imp_CLIPFORMAT_UserFree64>
extern __imp_CLIPFORMAT_UserMarshal:PANYARGS
CLIPFORMAT_UserMarshal TEXTEQU <__imp_CLIPFORMAT_UserMarshal>
extern __imp_CLIPFORMAT_UserMarshal64:PANYARGS
CLIPFORMAT_UserMarshal64 TEXTEQU <__imp_CLIPFORMAT_UserMarshal64>
extern __imp_CLIPFORMAT_UserSize:PANYARGS
CLIPFORMAT_UserSize TEXTEQU <__imp_CLIPFORMAT_UserSize>
extern __imp_CLIPFORMAT_UserSize64:PANYARGS
CLIPFORMAT_UserSize64 TEXTEQU <__imp_CLIPFORMAT_UserSize64>
extern __imp_CLIPFORMAT_UserUnmarshal:PANYARGS
CLIPFORMAT_UserUnmarshal TEXTEQU <__imp_CLIPFORMAT_UserUnmarshal>
extern __imp_CLIPFORMAT_UserUnmarshal64:PANYARGS
CLIPFORMAT_UserUnmarshal64 TEXTEQU <__imp_CLIPFORMAT_UserUnmarshal64>
extern __imp_CLSIDFromOle1Class:PANYARGS
CLSIDFromOle1Class TEXTEQU <__imp_CLSIDFromOle1Class>
extern __imp_CLSIDFromProgID:PANYARGS
CLSIDFromProgID TEXTEQU <__imp_CLSIDFromProgID>
extern __imp_CLSIDFromProgIDEx:PANYARGS
CLSIDFromProgIDEx TEXTEQU <__imp_CLSIDFromProgIDEx>
extern __imp_CLSIDFromString:PANYARGS
CLSIDFromString TEXTEQU <__imp_CLSIDFromString>
extern __imp_CoAddRefServerProcess:PANYARGS
CoAddRefServerProcess TEXTEQU <__imp_CoAddRefServerProcess>
extern __imp_CoAllowSetForegroundWindow:PANYARGS
CoAllowSetForegroundWindow TEXTEQU <__imp_CoAllowSetForegroundWindow>
extern __imp_CoBuildVersion:PANYARGS
CoBuildVersion TEXTEQU <__imp_CoBuildVersion>
extern __imp_CoCancelCall:PANYARGS
CoCancelCall TEXTEQU <__imp_CoCancelCall>
extern __imp_CoCopyProxy:PANYARGS
CoCopyProxy TEXTEQU <__imp_CoCopyProxy>
extern __imp_CoCreateFreeThreadedMarshaler:PANYARGS
CoCreateFreeThreadedMarshaler TEXTEQU <__imp_CoCreateFreeThreadedMarshaler>
extern __imp_CoCreateGuid:PANYARGS
CoCreateGuid TEXTEQU <__imp_CoCreateGuid>
extern __imp_CoCreateInstance:PANYARGS
CoCreateInstance TEXTEQU <__imp_CoCreateInstance>
extern __imp_CoCreateInstanceEx:PANYARGS
CoCreateInstanceEx TEXTEQU <__imp_CoCreateInstanceEx>
extern __imp_CoCreateObjectInContext:PANYARGS
CoCreateObjectInContext TEXTEQU <__imp_CoCreateObjectInContext>
extern __imp_CoDeactivateObject:PANYARGS
CoDeactivateObject TEXTEQU <__imp_CoDeactivateObject>
extern __imp_CoDisableCallCancellation:PANYARGS
CoDisableCallCancellation TEXTEQU <__imp_CoDisableCallCancellation>
extern __imp_CoDisconnectObject:PANYARGS
CoDisconnectObject TEXTEQU <__imp_CoDisconnectObject>
extern __imp_CoDosDateTimeToFileTime:PANYARGS
CoDosDateTimeToFileTime TEXTEQU <__imp_CoDosDateTimeToFileTime>
extern __imp_CoEnableCallCancellation:PANYARGS
CoEnableCallCancellation TEXTEQU <__imp_CoEnableCallCancellation>
extern __imp_CoFileTimeNow:PANYARGS
CoFileTimeNow TEXTEQU <__imp_CoFileTimeNow>
extern __imp_CoFileTimeToDosDateTime:PANYARGS
CoFileTimeToDosDateTime TEXTEQU <__imp_CoFileTimeToDosDateTime>
extern __imp_CoFreeAllLibraries:PANYARGS
CoFreeAllLibraries TEXTEQU <__imp_CoFreeAllLibraries>
extern __imp_CoFreeLibrary:PANYARGS
CoFreeLibrary TEXTEQU <__imp_CoFreeLibrary>
extern __imp_CoFreeUnusedLibraries:PANYARGS
CoFreeUnusedLibraries TEXTEQU <__imp_CoFreeUnusedLibraries>
extern __imp_CoFreeUnusedLibrariesEx:PANYARGS
CoFreeUnusedLibrariesEx TEXTEQU <__imp_CoFreeUnusedLibrariesEx>
extern __imp_CoGetApartmentID:PANYARGS
CoGetApartmentID TEXTEQU <__imp_CoGetApartmentID>
extern __imp_CoGetCallContext:PANYARGS
CoGetCallContext TEXTEQU <__imp_CoGetCallContext>
extern __imp_CoGetCallerTID:PANYARGS
CoGetCallerTID TEXTEQU <__imp_CoGetCallerTID>
extern __imp_CoGetCancelObject:PANYARGS
CoGetCancelObject TEXTEQU <__imp_CoGetCancelObject>
extern __imp_CoGetClassObject:PANYARGS
CoGetClassObject TEXTEQU <__imp_CoGetClassObject>
extern __imp_CoGetClassVersion:PANYARGS
CoGetClassVersion TEXTEQU <__imp_CoGetClassVersion>
extern __imp_CoGetComCatalog:PANYARGS
CoGetComCatalog TEXTEQU <__imp_CoGetComCatalog>
extern __imp_CoGetContextToken:PANYARGS
CoGetContextToken TEXTEQU <__imp_CoGetContextToken>
extern __imp_CoGetCurrentLogicalThreadId:PANYARGS
CoGetCurrentLogicalThreadId TEXTEQU <__imp_CoGetCurrentLogicalThreadId>
extern __imp_CoGetCurrentProcess:PANYARGS
CoGetCurrentProcess TEXTEQU <__imp_CoGetCurrentProcess>
extern __imp_CoGetDefaultContext:PANYARGS
CoGetDefaultContext TEXTEQU <__imp_CoGetDefaultContext>
extern __imp_CoGetInstanceFromFile:PANYARGS
CoGetInstanceFromFile TEXTEQU <__imp_CoGetInstanceFromFile>
extern __imp_CoGetInstanceFromIStorage:PANYARGS
CoGetInstanceFromIStorage TEXTEQU <__imp_CoGetInstanceFromIStorage>
extern __imp_CoGetInterceptor:PANYARGS
CoGetInterceptor TEXTEQU <__imp_CoGetInterceptor>
extern __imp_CoGetInterceptorFromTypeInfo:PANYARGS
CoGetInterceptorFromTypeInfo TEXTEQU <__imp_CoGetInterceptorFromTypeInfo>
extern __imp_CoGetInterfaceAndReleaseStream:PANYARGS
CoGetInterfaceAndReleaseStream TEXTEQU <__imp_CoGetInterfaceAndReleaseStream>
extern __imp_CoGetMalloc:PANYARGS
CoGetMalloc TEXTEQU <__imp_CoGetMalloc>
extern __imp_CoGetMarshalSizeMax:PANYARGS
CoGetMarshalSizeMax TEXTEQU <__imp_CoGetMarshalSizeMax>
extern __imp_CoGetModuleType:PANYARGS
CoGetModuleType TEXTEQU <__imp_CoGetModuleType>
extern __imp_CoGetObject:PANYARGS
CoGetObject TEXTEQU <__imp_CoGetObject>
extern __imp_CoGetObjectContext:PANYARGS
CoGetObjectContext TEXTEQU <__imp_CoGetObjectContext>
extern __imp_CoGetPSClsid:PANYARGS
CoGetPSClsid TEXTEQU <__imp_CoGetPSClsid>
extern __imp_CoGetProcessIdentifier:PANYARGS
CoGetProcessIdentifier TEXTEQU <__imp_CoGetProcessIdentifier>
extern __imp_CoGetStandardMarshal:PANYARGS
CoGetStandardMarshal TEXTEQU <__imp_CoGetStandardMarshal>
extern __imp_CoGetState:PANYARGS
CoGetState TEXTEQU <__imp_CoGetState>
extern __imp_CoGetStdMarshalEx:PANYARGS
CoGetStdMarshalEx TEXTEQU <__imp_CoGetStdMarshalEx>
extern __imp_CoGetSystemSecurityPermissions:PANYARGS
CoGetSystemSecurityPermissions TEXTEQU <__imp_CoGetSystemSecurityPermissions>
extern __imp_CoGetTreatAsClass:PANYARGS
CoGetTreatAsClass TEXTEQU <__imp_CoGetTreatAsClass>
extern __imp_CoImpersonateClient:PANYARGS
CoImpersonateClient TEXTEQU <__imp_CoImpersonateClient>
extern __imp_CoInitialize:PANYARGS
CoInitialize TEXTEQU <__imp_CoInitialize>
extern __imp_CoInitializeEx:PANYARGS
CoInitializeEx TEXTEQU <__imp_CoInitializeEx>
extern __imp_CoInitializeSecurity:PANYARGS
CoInitializeSecurity TEXTEQU <__imp_CoInitializeSecurity>
extern __imp_CoInitializeWOW:PANYARGS
CoInitializeWOW TEXTEQU <__imp_CoInitializeWOW>
extern __imp_CoInstall:PANYARGS
CoInstall TEXTEQU <__imp_CoInstall>
extern __imp_CoInvalidateRemoteMachineBindings:PANYARGS
CoInvalidateRemoteMachineBindings TEXTEQU <__imp_CoInvalidateRemoteMachineBindings>
extern __imp_CoIsHandlerConnected:PANYARGS
CoIsHandlerConnected TEXTEQU <__imp_CoIsHandlerConnected>
extern __imp_CoIsOle1Class:PANYARGS
CoIsOle1Class TEXTEQU <__imp_CoIsOle1Class>
extern __imp_CoLoadLibrary:PANYARGS
CoLoadLibrary TEXTEQU <__imp_CoLoadLibrary>
extern __imp_CoLockObjectExternal:PANYARGS
CoLockObjectExternal TEXTEQU <__imp_CoLockObjectExternal>
extern __imp_CoMarshalHresult:PANYARGS
CoMarshalHresult TEXTEQU <__imp_CoMarshalHresult>
extern __imp_CoMarshalInterThreadInterfaceInStream:PANYARGS
CoMarshalInterThreadInterfaceInStream TEXTEQU <__imp_CoMarshalInterThreadInterfaceInStream>
extern __imp_CoMarshalInterface:PANYARGS
CoMarshalInterface TEXTEQU <__imp_CoMarshalInterface>
extern __imp_CoPopServiceDomain:PANYARGS
CoPopServiceDomain TEXTEQU <__imp_CoPopServiceDomain>
extern __imp_CoPushServiceDomain:PANYARGS
CoPushServiceDomain TEXTEQU <__imp_CoPushServiceDomain>
extern __imp_CoQueryAuthenticationServices:PANYARGS
CoQueryAuthenticationServices TEXTEQU <__imp_CoQueryAuthenticationServices>
extern __imp_CoQueryClientBlanket:PANYARGS
CoQueryClientBlanket TEXTEQU <__imp_CoQueryClientBlanket>
extern __imp_CoQueryProxyBlanket:PANYARGS
CoQueryProxyBlanket TEXTEQU <__imp_CoQueryProxyBlanket>
extern __imp_CoQueryReleaseObject:PANYARGS
CoQueryReleaseObject TEXTEQU <__imp_CoQueryReleaseObject>
extern __imp_CoReactivateObject:PANYARGS
CoReactivateObject TEXTEQU <__imp_CoReactivateObject>
extern __imp_CoRegisterChannelHook:PANYARGS
CoRegisterChannelHook TEXTEQU <__imp_CoRegisterChannelHook>
extern __imp_CoRegisterClassObject:PANYARGS
CoRegisterClassObject TEXTEQU <__imp_CoRegisterClassObject>
extern __imp_CoRegisterInitializeSpy:PANYARGS
CoRegisterInitializeSpy TEXTEQU <__imp_CoRegisterInitializeSpy>
extern __imp_CoRegisterMallocSpy:PANYARGS
CoRegisterMallocSpy TEXTEQU <__imp_CoRegisterMallocSpy>
extern __imp_CoRegisterMessageFilter:PANYARGS
CoRegisterMessageFilter TEXTEQU <__imp_CoRegisterMessageFilter>
extern __imp_CoRegisterPSClsid:PANYARGS
CoRegisterPSClsid TEXTEQU <__imp_CoRegisterPSClsid>
extern __imp_CoRegisterSurrogate:PANYARGS
CoRegisterSurrogate TEXTEQU <__imp_CoRegisterSurrogate>
extern __imp_CoRegisterSurrogateEx:PANYARGS
CoRegisterSurrogateEx TEXTEQU <__imp_CoRegisterSurrogateEx>
extern __imp_CoReleaseMarshalData:PANYARGS
CoReleaseMarshalData TEXTEQU <__imp_CoReleaseMarshalData>
extern __imp_CoReleaseServerProcess:PANYARGS
CoReleaseServerProcess TEXTEQU <__imp_CoReleaseServerProcess>
extern __imp_CoResumeClassObjects:PANYARGS
CoResumeClassObjects TEXTEQU <__imp_CoResumeClassObjects>
extern __imp_CoRetireServer:PANYARGS
CoRetireServer TEXTEQU <__imp_CoRetireServer>
extern __imp_CoRevertToSelf:PANYARGS
CoRevertToSelf TEXTEQU <__imp_CoRevertToSelf>
extern __imp_CoRevokeClassObject:PANYARGS
CoRevokeClassObject TEXTEQU <__imp_CoRevokeClassObject>
extern __imp_CoRevokeInitializeSpy:PANYARGS
CoRevokeInitializeSpy TEXTEQU <__imp_CoRevokeInitializeSpy>
extern __imp_CoRevokeMallocSpy:PANYARGS
CoRevokeMallocSpy TEXTEQU <__imp_CoRevokeMallocSpy>
extern __imp_CoSetCancelObject:PANYARGS
CoSetCancelObject TEXTEQU <__imp_CoSetCancelObject>
extern __imp_CoSetProxyBlanket:PANYARGS
CoSetProxyBlanket TEXTEQU <__imp_CoSetProxyBlanket>
extern __imp_CoSetState:PANYARGS
CoSetState TEXTEQU <__imp_CoSetState>
extern __imp_CoSuspendClassObjects:PANYARGS
CoSuspendClassObjects TEXTEQU <__imp_CoSuspendClassObjects>
extern __imp_CoSwitchCallContext:PANYARGS
CoSwitchCallContext TEXTEQU <__imp_CoSwitchCallContext>
extern __imp_CoTaskMemAlloc:PANYARGS
CoTaskMemAlloc TEXTEQU <__imp_CoTaskMemAlloc>
extern __imp_CoTaskMemFree:PANYARGS
CoTaskMemFree TEXTEQU <__imp_CoTaskMemFree>
extern __imp_CoTaskMemRealloc:PANYARGS
CoTaskMemRealloc TEXTEQU <__imp_CoTaskMemRealloc>
extern __imp_CoTestCancel:PANYARGS
CoTestCancel TEXTEQU <__imp_CoTestCancel>
extern __imp_CoTreatAsClass:PANYARGS
CoTreatAsClass TEXTEQU <__imp_CoTreatAsClass>
extern __imp_CoUninitialize:PANYARGS
CoUninitialize TEXTEQU <__imp_CoUninitialize>
extern __imp_CoUnloadingWOW:PANYARGS
CoUnloadingWOW TEXTEQU <__imp_CoUnloadingWOW>
extern __imp_CoUnmarshalHresult:PANYARGS
CoUnmarshalHresult TEXTEQU <__imp_CoUnmarshalHresult>
extern __imp_CoUnmarshalInterface:PANYARGS
CoUnmarshalInterface TEXTEQU <__imp_CoUnmarshalInterface>
extern __imp_CoWaitForMultipleHandles:PANYARGS
CoWaitForMultipleHandles TEXTEQU <__imp_CoWaitForMultipleHandles>
extern __imp_ComPs_NdrDllCanUnloadNow:PANYARGS
ComPs_NdrDllCanUnloadNow TEXTEQU <__imp_ComPs_NdrDllCanUnloadNow>
extern __imp_ComPs_NdrDllGetClassObject:PANYARGS
ComPs_NdrDllGetClassObject TEXTEQU <__imp_ComPs_NdrDllGetClassObject>
extern __imp_ComPs_NdrDllRegisterProxy:PANYARGS
ComPs_NdrDllRegisterProxy TEXTEQU <__imp_ComPs_NdrDllRegisterProxy>
extern __imp_ComPs_NdrDllUnregisterProxy:PANYARGS
ComPs_NdrDllUnregisterProxy TEXTEQU <__imp_ComPs_NdrDllUnregisterProxy>
extern __imp_CreateAntiMoniker:PANYARGS
CreateAntiMoniker TEXTEQU <__imp_CreateAntiMoniker>
extern __imp_CreateBindCtx:PANYARGS
CreateBindCtx TEXTEQU <__imp_CreateBindCtx>
extern __imp_CreateClassMoniker:PANYARGS
CreateClassMoniker TEXTEQU <__imp_CreateClassMoniker>
extern __imp_CreateDataAdviseHolder:PANYARGS
CreateDataAdviseHolder TEXTEQU <__imp_CreateDataAdviseHolder>
extern __imp_CreateDataCache:PANYARGS
CreateDataCache TEXTEQU <__imp_CreateDataCache>
extern __imp_CreateErrorInfo:PANYARGS
CreateErrorInfo TEXTEQU <__imp_CreateErrorInfo>
extern __imp_CreateFileMoniker:PANYARGS
CreateFileMoniker TEXTEQU <__imp_CreateFileMoniker>
extern __imp_CreateGenericComposite:PANYARGS
CreateGenericComposite TEXTEQU <__imp_CreateGenericComposite>
extern __imp_CreateILockBytesOnHGlobal:PANYARGS
CreateILockBytesOnHGlobal TEXTEQU <__imp_CreateILockBytesOnHGlobal>
extern __imp_CreateItemMoniker:PANYARGS
CreateItemMoniker TEXTEQU <__imp_CreateItemMoniker>
extern __imp_CreateObjrefMoniker:PANYARGS
CreateObjrefMoniker TEXTEQU <__imp_CreateObjrefMoniker>
extern __imp_CreateOleAdviseHolder:PANYARGS
CreateOleAdviseHolder TEXTEQU <__imp_CreateOleAdviseHolder>
extern __imp_CreatePointerMoniker:PANYARGS
CreatePointerMoniker TEXTEQU <__imp_CreatePointerMoniker>
extern __imp_CreateStdProgressIndicator:PANYARGS
CreateStdProgressIndicator TEXTEQU <__imp_CreateStdProgressIndicator>
extern __imp_CreateStreamOnHGlobal:PANYARGS
CreateStreamOnHGlobal TEXTEQU <__imp_CreateStreamOnHGlobal>
extern __imp_DcomChannelSetHResult:PANYARGS
DcomChannelSetHResult TEXTEQU <__imp_DcomChannelSetHResult>
extern __imp_DllDebugObjectRPCHook:PANYARGS
DllDebugObjectRPCHook TEXTEQU <__imp_DllDebugObjectRPCHook>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllGetClassObjectWOW:PANYARGS
DllGetClassObjectWOW TEXTEQU <__imp_DllGetClassObjectWOW>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DoDragDrop:PANYARGS
DoDragDrop TEXTEQU <__imp_DoDragDrop>
extern __imp_EnableHookObject:PANYARGS
EnableHookObject TEXTEQU <__imp_EnableHookObject>
extern __imp_FmtIdToPropStgName:PANYARGS
FmtIdToPropStgName TEXTEQU <__imp_FmtIdToPropStgName>
extern __imp_FreePropVariantArray:PANYARGS
FreePropVariantArray TEXTEQU <__imp_FreePropVariantArray>
extern __imp_GetClassFile:PANYARGS
GetClassFile TEXTEQU <__imp_GetClassFile>
extern __imp_GetConvertStg:PANYARGS
GetConvertStg TEXTEQU <__imp_GetConvertStg>
extern __imp_GetDocumentBitStg:PANYARGS
GetDocumentBitStg TEXTEQU <__imp_GetDocumentBitStg>
extern __imp_GetErrorInfo:PANYARGS
GetErrorInfo TEXTEQU <__imp_GetErrorInfo>
extern __imp_GetHGlobalFromILockBytes:PANYARGS
GetHGlobalFromILockBytes TEXTEQU <__imp_GetHGlobalFromILockBytes>
extern __imp_GetHGlobalFromStream:PANYARGS
GetHGlobalFromStream TEXTEQU <__imp_GetHGlobalFromStream>
extern __imp_GetHookInterface:PANYARGS
GetHookInterface TEXTEQU <__imp_GetHookInterface>
extern __imp_GetRunningObjectTable:PANYARGS
GetRunningObjectTable TEXTEQU <__imp_GetRunningObjectTable>
extern __imp_HACCEL_UserFree:PANYARGS
HACCEL_UserFree TEXTEQU <__imp_HACCEL_UserFree>
extern __imp_HACCEL_UserFree64:PANYARGS
HACCEL_UserFree64 TEXTEQU <__imp_HACCEL_UserFree64>
extern __imp_HACCEL_UserMarshal:PANYARGS
HACCEL_UserMarshal TEXTEQU <__imp_HACCEL_UserMarshal>
extern __imp_HACCEL_UserMarshal64:PANYARGS
HACCEL_UserMarshal64 TEXTEQU <__imp_HACCEL_UserMarshal64>
extern __imp_HACCEL_UserSize:PANYARGS
HACCEL_UserSize TEXTEQU <__imp_HACCEL_UserSize>
extern __imp_HACCEL_UserSize64:PANYARGS
HACCEL_UserSize64 TEXTEQU <__imp_HACCEL_UserSize64>
extern __imp_HACCEL_UserUnmarshal:PANYARGS
HACCEL_UserUnmarshal TEXTEQU <__imp_HACCEL_UserUnmarshal>
extern __imp_HACCEL_UserUnmarshal64:PANYARGS
HACCEL_UserUnmarshal64 TEXTEQU <__imp_HACCEL_UserUnmarshal64>
extern __imp_HBITMAP_UserFree:PANYARGS
HBITMAP_UserFree TEXTEQU <__imp_HBITMAP_UserFree>
extern __imp_HBITMAP_UserFree64:PANYARGS
HBITMAP_UserFree64 TEXTEQU <__imp_HBITMAP_UserFree64>
extern __imp_HBITMAP_UserMarshal:PANYARGS
HBITMAP_UserMarshal TEXTEQU <__imp_HBITMAP_UserMarshal>
extern __imp_HBITMAP_UserMarshal64:PANYARGS
HBITMAP_UserMarshal64 TEXTEQU <__imp_HBITMAP_UserMarshal64>
extern __imp_HBITMAP_UserSize:PANYARGS
HBITMAP_UserSize TEXTEQU <__imp_HBITMAP_UserSize>
extern __imp_HBITMAP_UserSize64:PANYARGS
HBITMAP_UserSize64 TEXTEQU <__imp_HBITMAP_UserSize64>
extern __imp_HBITMAP_UserUnmarshal:PANYARGS
HBITMAP_UserUnmarshal TEXTEQU <__imp_HBITMAP_UserUnmarshal>
extern __imp_HBITMAP_UserUnmarshal64:PANYARGS
HBITMAP_UserUnmarshal64 TEXTEQU <__imp_HBITMAP_UserUnmarshal64>
extern __imp_HBRUSH_UserFree:PANYARGS
HBRUSH_UserFree TEXTEQU <__imp_HBRUSH_UserFree>
extern __imp_HBRUSH_UserFree64:PANYARGS
HBRUSH_UserFree64 TEXTEQU <__imp_HBRUSH_UserFree64>
extern __imp_HBRUSH_UserMarshal:PANYARGS
HBRUSH_UserMarshal TEXTEQU <__imp_HBRUSH_UserMarshal>
extern __imp_HBRUSH_UserMarshal64:PANYARGS
HBRUSH_UserMarshal64 TEXTEQU <__imp_HBRUSH_UserMarshal64>
extern __imp_HBRUSH_UserSize:PANYARGS
HBRUSH_UserSize TEXTEQU <__imp_HBRUSH_UserSize>
extern __imp_HBRUSH_UserSize64:PANYARGS
HBRUSH_UserSize64 TEXTEQU <__imp_HBRUSH_UserSize64>
extern __imp_HBRUSH_UserUnmarshal:PANYARGS
HBRUSH_UserUnmarshal TEXTEQU <__imp_HBRUSH_UserUnmarshal>
extern __imp_HBRUSH_UserUnmarshal64:PANYARGS
HBRUSH_UserUnmarshal64 TEXTEQU <__imp_HBRUSH_UserUnmarshal64>
extern __imp_HDC_UserFree:PANYARGS
HDC_UserFree TEXTEQU <__imp_HDC_UserFree>
extern __imp_HDC_UserFree64:PANYARGS
HDC_UserFree64 TEXTEQU <__imp_HDC_UserFree64>
extern __imp_HDC_UserMarshal:PANYARGS
HDC_UserMarshal TEXTEQU <__imp_HDC_UserMarshal>
extern __imp_HDC_UserMarshal64:PANYARGS
HDC_UserMarshal64 TEXTEQU <__imp_HDC_UserMarshal64>
extern __imp_HDC_UserSize:PANYARGS
HDC_UserSize TEXTEQU <__imp_HDC_UserSize>
extern __imp_HDC_UserSize64:PANYARGS
HDC_UserSize64 TEXTEQU <__imp_HDC_UserSize64>
extern __imp_HDC_UserUnmarshal:PANYARGS
HDC_UserUnmarshal TEXTEQU <__imp_HDC_UserUnmarshal>
extern __imp_HDC_UserUnmarshal64:PANYARGS
HDC_UserUnmarshal64 TEXTEQU <__imp_HDC_UserUnmarshal64>
extern __imp_HENHMETAFILE_UserFree:PANYARGS
HENHMETAFILE_UserFree TEXTEQU <__imp_HENHMETAFILE_UserFree>
extern __imp_HENHMETAFILE_UserFree64:PANYARGS
HENHMETAFILE_UserFree64 TEXTEQU <__imp_HENHMETAFILE_UserFree64>
extern __imp_HENHMETAFILE_UserMarshal:PANYARGS
HENHMETAFILE_UserMarshal TEXTEQU <__imp_HENHMETAFILE_UserMarshal>
extern __imp_HENHMETAFILE_UserMarshal64:PANYARGS
HENHMETAFILE_UserMarshal64 TEXTEQU <__imp_HENHMETAFILE_UserMarshal64>
extern __imp_HENHMETAFILE_UserSize:PANYARGS
HENHMETAFILE_UserSize TEXTEQU <__imp_HENHMETAFILE_UserSize>
extern __imp_HENHMETAFILE_UserSize64:PANYARGS
HENHMETAFILE_UserSize64 TEXTEQU <__imp_HENHMETAFILE_UserSize64>
extern __imp_HENHMETAFILE_UserUnmarshal:PANYARGS
HENHMETAFILE_UserUnmarshal TEXTEQU <__imp_HENHMETAFILE_UserUnmarshal>
extern __imp_HENHMETAFILE_UserUnmarshal64:PANYARGS
HENHMETAFILE_UserUnmarshal64 TEXTEQU <__imp_HENHMETAFILE_UserUnmarshal64>
extern __imp_HGLOBAL_UserFree:PANYARGS
HGLOBAL_UserFree TEXTEQU <__imp_HGLOBAL_UserFree>
extern __imp_HGLOBAL_UserFree64:PANYARGS
HGLOBAL_UserFree64 TEXTEQU <__imp_HGLOBAL_UserFree64>
extern __imp_HGLOBAL_UserMarshal:PANYARGS
HGLOBAL_UserMarshal TEXTEQU <__imp_HGLOBAL_UserMarshal>
extern __imp_HGLOBAL_UserMarshal64:PANYARGS
HGLOBAL_UserMarshal64 TEXTEQU <__imp_HGLOBAL_UserMarshal64>
extern __imp_HGLOBAL_UserSize:PANYARGS
HGLOBAL_UserSize TEXTEQU <__imp_HGLOBAL_UserSize>
extern __imp_HGLOBAL_UserSize64:PANYARGS
HGLOBAL_UserSize64 TEXTEQU <__imp_HGLOBAL_UserSize64>
extern __imp_HGLOBAL_UserUnmarshal:PANYARGS
HGLOBAL_UserUnmarshal TEXTEQU <__imp_HGLOBAL_UserUnmarshal>
extern __imp_HGLOBAL_UserUnmarshal64:PANYARGS
HGLOBAL_UserUnmarshal64 TEXTEQU <__imp_HGLOBAL_UserUnmarshal64>
extern __imp_HICON_UserFree:PANYARGS
HICON_UserFree TEXTEQU <__imp_HICON_UserFree>
extern __imp_HICON_UserFree64:PANYARGS
HICON_UserFree64 TEXTEQU <__imp_HICON_UserFree64>
extern __imp_HICON_UserMarshal:PANYARGS
HICON_UserMarshal TEXTEQU <__imp_HICON_UserMarshal>
extern __imp_HICON_UserMarshal64:PANYARGS
HICON_UserMarshal64 TEXTEQU <__imp_HICON_UserMarshal64>
extern __imp_HICON_UserSize:PANYARGS
HICON_UserSize TEXTEQU <__imp_HICON_UserSize>
extern __imp_HICON_UserSize64:PANYARGS
HICON_UserSize64 TEXTEQU <__imp_HICON_UserSize64>
extern __imp_HICON_UserUnmarshal:PANYARGS
HICON_UserUnmarshal TEXTEQU <__imp_HICON_UserUnmarshal>
extern __imp_HICON_UserUnmarshal64:PANYARGS
HICON_UserUnmarshal64 TEXTEQU <__imp_HICON_UserUnmarshal64>
extern __imp_HMENU_UserFree:PANYARGS
HMENU_UserFree TEXTEQU <__imp_HMENU_UserFree>
extern __imp_HMENU_UserFree64:PANYARGS
HMENU_UserFree64 TEXTEQU <__imp_HMENU_UserFree64>
extern __imp_HMENU_UserMarshal:PANYARGS
HMENU_UserMarshal TEXTEQU <__imp_HMENU_UserMarshal>
extern __imp_HMENU_UserMarshal64:PANYARGS
HMENU_UserMarshal64 TEXTEQU <__imp_HMENU_UserMarshal64>
extern __imp_HMENU_UserSize:PANYARGS
HMENU_UserSize TEXTEQU <__imp_HMENU_UserSize>
extern __imp_HMENU_UserSize64:PANYARGS
HMENU_UserSize64 TEXTEQU <__imp_HMENU_UserSize64>
extern __imp_HMENU_UserUnmarshal:PANYARGS
HMENU_UserUnmarshal TEXTEQU <__imp_HMENU_UserUnmarshal>
extern __imp_HMENU_UserUnmarshal64:PANYARGS
HMENU_UserUnmarshal64 TEXTEQU <__imp_HMENU_UserUnmarshal64>
extern __imp_HMETAFILEPICT_UserFree:PANYARGS
HMETAFILEPICT_UserFree TEXTEQU <__imp_HMETAFILEPICT_UserFree>
extern __imp_HMETAFILEPICT_UserFree64:PANYARGS
HMETAFILEPICT_UserFree64 TEXTEQU <__imp_HMETAFILEPICT_UserFree64>
extern __imp_HMETAFILEPICT_UserMarshal:PANYARGS
HMETAFILEPICT_UserMarshal TEXTEQU <__imp_HMETAFILEPICT_UserMarshal>
extern __imp_HMETAFILEPICT_UserMarshal64:PANYARGS
HMETAFILEPICT_UserMarshal64 TEXTEQU <__imp_HMETAFILEPICT_UserMarshal64>
extern __imp_HMETAFILEPICT_UserSize:PANYARGS
HMETAFILEPICT_UserSize TEXTEQU <__imp_HMETAFILEPICT_UserSize>
extern __imp_HMETAFILEPICT_UserSize64:PANYARGS
HMETAFILEPICT_UserSize64 TEXTEQU <__imp_HMETAFILEPICT_UserSize64>
extern __imp_HMETAFILEPICT_UserUnmarshal:PANYARGS
HMETAFILEPICT_UserUnmarshal TEXTEQU <__imp_HMETAFILEPICT_UserUnmarshal>
extern __imp_HMETAFILEPICT_UserUnmarshal64:PANYARGS
HMETAFILEPICT_UserUnmarshal64 TEXTEQU <__imp_HMETAFILEPICT_UserUnmarshal64>
extern __imp_HMETAFILE_UserFree:PANYARGS
HMETAFILE_UserFree TEXTEQU <__imp_HMETAFILE_UserFree>
extern __imp_HMETAFILE_UserFree64:PANYARGS
HMETAFILE_UserFree64 TEXTEQU <__imp_HMETAFILE_UserFree64>
extern __imp_HMETAFILE_UserMarshal:PANYARGS
HMETAFILE_UserMarshal TEXTEQU <__imp_HMETAFILE_UserMarshal>
extern __imp_HMETAFILE_UserMarshal64:PANYARGS
HMETAFILE_UserMarshal64 TEXTEQU <__imp_HMETAFILE_UserMarshal64>
extern __imp_HMETAFILE_UserSize:PANYARGS
HMETAFILE_UserSize TEXTEQU <__imp_HMETAFILE_UserSize>
extern __imp_HMETAFILE_UserSize64:PANYARGS
HMETAFILE_UserSize64 TEXTEQU <__imp_HMETAFILE_UserSize64>
extern __imp_HMETAFILE_UserUnmarshal:PANYARGS
HMETAFILE_UserUnmarshal TEXTEQU <__imp_HMETAFILE_UserUnmarshal>
extern __imp_HMETAFILE_UserUnmarshal64:PANYARGS
HMETAFILE_UserUnmarshal64 TEXTEQU <__imp_HMETAFILE_UserUnmarshal64>
extern __imp_HPALETTE_UserFree:PANYARGS
HPALETTE_UserFree TEXTEQU <__imp_HPALETTE_UserFree>
extern __imp_HPALETTE_UserFree64:PANYARGS
HPALETTE_UserFree64 TEXTEQU <__imp_HPALETTE_UserFree64>
extern __imp_HPALETTE_UserMarshal:PANYARGS
HPALETTE_UserMarshal TEXTEQU <__imp_HPALETTE_UserMarshal>
extern __imp_HPALETTE_UserMarshal64:PANYARGS
HPALETTE_UserMarshal64 TEXTEQU <__imp_HPALETTE_UserMarshal64>
extern __imp_HPALETTE_UserSize:PANYARGS
HPALETTE_UserSize TEXTEQU <__imp_HPALETTE_UserSize>
extern __imp_HPALETTE_UserSize64:PANYARGS
HPALETTE_UserSize64 TEXTEQU <__imp_HPALETTE_UserSize64>
extern __imp_HPALETTE_UserUnmarshal:PANYARGS
HPALETTE_UserUnmarshal TEXTEQU <__imp_HPALETTE_UserUnmarshal>
extern __imp_HPALETTE_UserUnmarshal64:PANYARGS
HPALETTE_UserUnmarshal64 TEXTEQU <__imp_HPALETTE_UserUnmarshal64>
extern __imp_HWND_UserFree:PANYARGS
HWND_UserFree TEXTEQU <__imp_HWND_UserFree>
extern __imp_HWND_UserFree64:PANYARGS
HWND_UserFree64 TEXTEQU <__imp_HWND_UserFree64>
extern __imp_HWND_UserMarshal:PANYARGS
HWND_UserMarshal TEXTEQU <__imp_HWND_UserMarshal>
extern __imp_HWND_UserMarshal64:PANYARGS
HWND_UserMarshal64 TEXTEQU <__imp_HWND_UserMarshal64>
extern __imp_HWND_UserSize:PANYARGS
HWND_UserSize TEXTEQU <__imp_HWND_UserSize>
extern __imp_HWND_UserSize64:PANYARGS
HWND_UserSize64 TEXTEQU <__imp_HWND_UserSize64>
extern __imp_HWND_UserUnmarshal:PANYARGS
HWND_UserUnmarshal TEXTEQU <__imp_HWND_UserUnmarshal>
extern __imp_HWND_UserUnmarshal64:PANYARGS
HWND_UserUnmarshal64 TEXTEQU <__imp_HWND_UserUnmarshal64>
extern __imp_HkOleRegisterObject:PANYARGS
HkOleRegisterObject TEXTEQU <__imp_HkOleRegisterObject>
extern __imp_IIDFromString:PANYARGS
IIDFromString TEXTEQU <__imp_IIDFromString>
extern __imp_IsAccelerator:PANYARGS
IsAccelerator TEXTEQU <__imp_IsAccelerator>
extern __imp_IsEqualGUID:PANYARGS
IsEqualGUID TEXTEQU <__imp_IsEqualGUID>
extern __imp_IsValidIid:PANYARGS
IsValidIid TEXTEQU <__imp_IsValidIid>
extern __imp_IsValidInterface:PANYARGS
IsValidInterface TEXTEQU <__imp_IsValidInterface>
extern __imp_IsValidPtrIn:PANYARGS
IsValidPtrIn TEXTEQU <__imp_IsValidPtrIn>
extern __imp_IsValidPtrOut:PANYARGS
IsValidPtrOut TEXTEQU <__imp_IsValidPtrOut>
extern __imp_MkParseDisplayName:PANYARGS
MkParseDisplayName TEXTEQU <__imp_MkParseDisplayName>
extern __imp_MonikerCommonPrefixWith:PANYARGS
MonikerCommonPrefixWith TEXTEQU <__imp_MonikerCommonPrefixWith>
extern __imp_MonikerRelativePathTo:PANYARGS
MonikerRelativePathTo TEXTEQU <__imp_MonikerRelativePathTo>
extern __imp_OleBuildVersion:PANYARGS
OleBuildVersion TEXTEQU <__imp_OleBuildVersion>
extern __imp_OleConvertIStorageToOLESTREAM:PANYARGS
OleConvertIStorageToOLESTREAM TEXTEQU <__imp_OleConvertIStorageToOLESTREAM>
extern __imp_OleConvertIStorageToOLESTREAMEx:PANYARGS
OleConvertIStorageToOLESTREAMEx TEXTEQU <__imp_OleConvertIStorageToOLESTREAMEx>
extern __imp_OleConvertOLESTREAMToIStorage:PANYARGS
OleConvertOLESTREAMToIStorage TEXTEQU <__imp_OleConvertOLESTREAMToIStorage>
extern __imp_OleConvertOLESTREAMToIStorageEx:PANYARGS
OleConvertOLESTREAMToIStorageEx TEXTEQU <__imp_OleConvertOLESTREAMToIStorageEx>
extern __imp_OleCreate:PANYARGS
OleCreate TEXTEQU <__imp_OleCreate>
extern __imp_OleCreateDefaultHandler:PANYARGS
OleCreateDefaultHandler TEXTEQU <__imp_OleCreateDefaultHandler>
extern __imp_OleCreateEmbeddingHelper:PANYARGS
OleCreateEmbeddingHelper TEXTEQU <__imp_OleCreateEmbeddingHelper>
extern __imp_OleCreateEx:PANYARGS
OleCreateEx TEXTEQU <__imp_OleCreateEx>
extern __imp_OleCreateFromData:PANYARGS
OleCreateFromData TEXTEQU <__imp_OleCreateFromData>
extern __imp_OleCreateFromDataEx:PANYARGS
OleCreateFromDataEx TEXTEQU <__imp_OleCreateFromDataEx>
extern __imp_OleCreateFromFile:PANYARGS
OleCreateFromFile TEXTEQU <__imp_OleCreateFromFile>
extern __imp_OleCreateFromFileEx:PANYARGS
OleCreateFromFileEx TEXTEQU <__imp_OleCreateFromFileEx>
extern __imp_OleCreateLink:PANYARGS
OleCreateLink TEXTEQU <__imp_OleCreateLink>
extern __imp_OleCreateLinkEx:PANYARGS
OleCreateLinkEx TEXTEQU <__imp_OleCreateLinkEx>
extern __imp_OleCreateLinkFromData:PANYARGS
OleCreateLinkFromData TEXTEQU <__imp_OleCreateLinkFromData>
extern __imp_OleCreateLinkFromDataEx:PANYARGS
OleCreateLinkFromDataEx TEXTEQU <__imp_OleCreateLinkFromDataEx>
extern __imp_OleCreateLinkToFile:PANYARGS
OleCreateLinkToFile TEXTEQU <__imp_OleCreateLinkToFile>
extern __imp_OleCreateLinkToFileEx:PANYARGS
OleCreateLinkToFileEx TEXTEQU <__imp_OleCreateLinkToFileEx>
extern __imp_OleCreateMenuDescriptor:PANYARGS
OleCreateMenuDescriptor TEXTEQU <__imp_OleCreateMenuDescriptor>
extern __imp_OleCreateStaticFromData:PANYARGS
OleCreateStaticFromData TEXTEQU <__imp_OleCreateStaticFromData>
extern __imp_OleDestroyMenuDescriptor:PANYARGS
OleDestroyMenuDescriptor TEXTEQU <__imp_OleDestroyMenuDescriptor>
extern __imp_OleDoAutoConvert:PANYARGS
OleDoAutoConvert TEXTEQU <__imp_OleDoAutoConvert>
extern __imp_OleDraw:PANYARGS
OleDraw TEXTEQU <__imp_OleDraw>
extern __imp_OleDuplicateData:PANYARGS
OleDuplicateData TEXTEQU <__imp_OleDuplicateData>
extern __imp_OleFlushClipboard:PANYARGS
OleFlushClipboard TEXTEQU <__imp_OleFlushClipboard>
extern __imp_OleGetAutoConvert:PANYARGS
OleGetAutoConvert TEXTEQU <__imp_OleGetAutoConvert>
extern __imp_OleGetClipboard:PANYARGS
OleGetClipboard TEXTEQU <__imp_OleGetClipboard>
extern __imp_OleGetIconOfClass:PANYARGS
OleGetIconOfClass TEXTEQU <__imp_OleGetIconOfClass>
extern __imp_OleGetIconOfFile:PANYARGS
OleGetIconOfFile TEXTEQU <__imp_OleGetIconOfFile>
extern __imp_OleInitialize:PANYARGS
OleInitialize TEXTEQU <__imp_OleInitialize>
extern __imp_OleInitializeWOW:PANYARGS
OleInitializeWOW TEXTEQU <__imp_OleInitializeWOW>
extern __imp_OleIsCurrentClipboard:PANYARGS
OleIsCurrentClipboard TEXTEQU <__imp_OleIsCurrentClipboard>
extern __imp_OleIsRunning:PANYARGS
OleIsRunning TEXTEQU <__imp_OleIsRunning>
extern __imp_OleLoad:PANYARGS
OleLoad TEXTEQU <__imp_OleLoad>
extern __imp_OleLoadFromStream:PANYARGS
OleLoadFromStream TEXTEQU <__imp_OleLoadFromStream>
extern __imp_OleLockRunning:PANYARGS
OleLockRunning TEXTEQU <__imp_OleLockRunning>
extern __imp_OleMetafilePictFromIconAndLabel:PANYARGS
OleMetafilePictFromIconAndLabel TEXTEQU <__imp_OleMetafilePictFromIconAndLabel>
extern __imp_OleNoteObjectVisible:PANYARGS
OleNoteObjectVisible TEXTEQU <__imp_OleNoteObjectVisible>
extern __imp_OleQueryCreateFromData:PANYARGS
OleQueryCreateFromData TEXTEQU <__imp_OleQueryCreateFromData>
extern __imp_OleQueryLinkFromData:PANYARGS
OleQueryLinkFromData TEXTEQU <__imp_OleQueryLinkFromData>
extern __imp_OleRegEnumFormatEtc:PANYARGS
OleRegEnumFormatEtc TEXTEQU <__imp_OleRegEnumFormatEtc>
extern __imp_OleRegEnumVerbs:PANYARGS
OleRegEnumVerbs TEXTEQU <__imp_OleRegEnumVerbs>
extern __imp_OleRegGetMiscStatus:PANYARGS
OleRegGetMiscStatus TEXTEQU <__imp_OleRegGetMiscStatus>
extern __imp_OleRegGetUserType:PANYARGS
OleRegGetUserType TEXTEQU <__imp_OleRegGetUserType>
extern __imp_OleRun:PANYARGS
OleRun TEXTEQU <__imp_OleRun>
extern __imp_OleSave:PANYARGS
OleSave TEXTEQU <__imp_OleSave>
extern __imp_OleSaveToStream:PANYARGS
OleSaveToStream TEXTEQU <__imp_OleSaveToStream>
extern __imp_OleSetAutoConvert:PANYARGS
OleSetAutoConvert TEXTEQU <__imp_OleSetAutoConvert>
extern __imp_OleSetClipboard:PANYARGS
OleSetClipboard TEXTEQU <__imp_OleSetClipboard>
extern __imp_OleSetContainedObject:PANYARGS
OleSetContainedObject TEXTEQU <__imp_OleSetContainedObject>
extern __imp_OleSetMenuDescriptor:PANYARGS
OleSetMenuDescriptor TEXTEQU <__imp_OleSetMenuDescriptor>
extern __imp_OleTranslateAccelerator:PANYARGS
OleTranslateAccelerator TEXTEQU <__imp_OleTranslateAccelerator>
extern __imp_OleUninitialize:PANYARGS
OleUninitialize TEXTEQU <__imp_OleUninitialize>
extern __imp_OpenOrCreateStream:PANYARGS
OpenOrCreateStream TEXTEQU <__imp_OpenOrCreateStream>
extern __imp_ProgIDFromCLSID:PANYARGS
ProgIDFromCLSID TEXTEQU <__imp_ProgIDFromCLSID>
extern __imp_PropStgNameToFmtId:PANYARGS
PropStgNameToFmtId TEXTEQU <__imp_PropStgNameToFmtId>
extern __imp_PropSysAllocString:PANYARGS
PropSysAllocString TEXTEQU <__imp_PropSysAllocString>
extern __imp_PropSysFreeString:PANYARGS
PropSysFreeString TEXTEQU <__imp_PropSysFreeString>
extern __imp_PropVariantClear:PANYARGS
PropVariantClear TEXTEQU <__imp_PropVariantClear>
extern __imp_PropVariantCopy:PANYARGS
PropVariantCopy TEXTEQU <__imp_PropVariantCopy>
extern __imp_ReadClassStg:PANYARGS
ReadClassStg TEXTEQU <__imp_ReadClassStg>
extern __imp_ReadClassStm:PANYARGS
ReadClassStm TEXTEQU <__imp_ReadClassStm>
extern __imp_ReadFmtUserTypeStg:PANYARGS
ReadFmtUserTypeStg TEXTEQU <__imp_ReadFmtUserTypeStg>
extern __imp_ReadOleStg:PANYARGS
ReadOleStg TEXTEQU <__imp_ReadOleStg>
extern __imp_ReadStringStream:PANYARGS
ReadStringStream TEXTEQU <__imp_ReadStringStream>
extern __imp_RegisterDragDrop:PANYARGS
RegisterDragDrop TEXTEQU <__imp_RegisterDragDrop>
extern __imp_ReleaseStgMedium:PANYARGS
ReleaseStgMedium TEXTEQU <__imp_ReleaseStgMedium>
extern __imp_RevokeDragDrop:PANYARGS
RevokeDragDrop TEXTEQU <__imp_RevokeDragDrop>
extern __imp_SNB_UserFree:PANYARGS
SNB_UserFree TEXTEQU <__imp_SNB_UserFree>
extern __imp_SNB_UserFree64:PANYARGS
SNB_UserFree64 TEXTEQU <__imp_SNB_UserFree64>
extern __imp_SNB_UserMarshal:PANYARGS
SNB_UserMarshal TEXTEQU <__imp_SNB_UserMarshal>
extern __imp_SNB_UserMarshal64:PANYARGS
SNB_UserMarshal64 TEXTEQU <__imp_SNB_UserMarshal64>
extern __imp_SNB_UserSize:PANYARGS
SNB_UserSize TEXTEQU <__imp_SNB_UserSize>
extern __imp_SNB_UserSize64:PANYARGS
SNB_UserSize64 TEXTEQU <__imp_SNB_UserSize64>
extern __imp_SNB_UserUnmarshal:PANYARGS
SNB_UserUnmarshal TEXTEQU <__imp_SNB_UserUnmarshal>
extern __imp_SNB_UserUnmarshal64:PANYARGS
SNB_UserUnmarshal64 TEXTEQU <__imp_SNB_UserUnmarshal64>
extern __imp_STGMEDIUM_UserFree:PANYARGS
STGMEDIUM_UserFree TEXTEQU <__imp_STGMEDIUM_UserFree>
extern __imp_STGMEDIUM_UserFree64:PANYARGS
STGMEDIUM_UserFree64 TEXTEQU <__imp_STGMEDIUM_UserFree64>
extern __imp_STGMEDIUM_UserMarshal:PANYARGS
STGMEDIUM_UserMarshal TEXTEQU <__imp_STGMEDIUM_UserMarshal>
extern __imp_STGMEDIUM_UserMarshal64:PANYARGS
STGMEDIUM_UserMarshal64 TEXTEQU <__imp_STGMEDIUM_UserMarshal64>
extern __imp_STGMEDIUM_UserSize:PANYARGS
STGMEDIUM_UserSize TEXTEQU <__imp_STGMEDIUM_UserSize>
extern __imp_STGMEDIUM_UserSize64:PANYARGS
STGMEDIUM_UserSize64 TEXTEQU <__imp_STGMEDIUM_UserSize64>
extern __imp_STGMEDIUM_UserUnmarshal:PANYARGS
STGMEDIUM_UserUnmarshal TEXTEQU <__imp_STGMEDIUM_UserUnmarshal>
extern __imp_STGMEDIUM_UserUnmarshal64:PANYARGS
STGMEDIUM_UserUnmarshal64 TEXTEQU <__imp_STGMEDIUM_UserUnmarshal64>
extern __imp_SetConvertStg:PANYARGS
SetConvertStg TEXTEQU <__imp_SetConvertStg>
extern __imp_SetDocumentBitStg:PANYARGS
SetDocumentBitStg TEXTEQU <__imp_SetDocumentBitStg>
extern __imp_SetErrorInfo:PANYARGS
SetErrorInfo TEXTEQU <__imp_SetErrorInfo>
extern __imp_StgConvertPropertyToVariant:PANYARGS
StgConvertPropertyToVariant TEXTEQU <__imp_StgConvertPropertyToVariant>
extern __imp_StgConvertVariantToProperty:PANYARGS
StgConvertVariantToProperty TEXTEQU <__imp_StgConvertVariantToProperty>
extern __imp_StgCreateDocfile:PANYARGS
StgCreateDocfile TEXTEQU <__imp_StgCreateDocfile>
extern __imp_StgCreateDocfileOnILockBytes:PANYARGS
StgCreateDocfileOnILockBytes TEXTEQU <__imp_StgCreateDocfileOnILockBytes>
extern __imp_StgCreatePropSetStg:PANYARGS
StgCreatePropSetStg TEXTEQU <__imp_StgCreatePropSetStg>
extern __imp_StgCreatePropStg:PANYARGS
StgCreatePropStg TEXTEQU <__imp_StgCreatePropStg>
extern __imp_StgCreateStorageEx:PANYARGS
StgCreateStorageEx TEXTEQU <__imp_StgCreateStorageEx>
extern __imp_StgGetIFillLockBytesOnFile:PANYARGS
StgGetIFillLockBytesOnFile TEXTEQU <__imp_StgGetIFillLockBytesOnFile>
extern __imp_StgGetIFillLockBytesOnILockBytes:PANYARGS
StgGetIFillLockBytesOnILockBytes TEXTEQU <__imp_StgGetIFillLockBytesOnILockBytes>
extern __imp_StgIsStorageFile:PANYARGS
StgIsStorageFile TEXTEQU <__imp_StgIsStorageFile>
extern __imp_StgIsStorageILockBytes:PANYARGS
StgIsStorageILockBytes TEXTEQU <__imp_StgIsStorageILockBytes>
extern __imp_StgOpenAsyncDocfileOnIFillLockBytes:PANYARGS
StgOpenAsyncDocfileOnIFillLockBytes TEXTEQU <__imp_StgOpenAsyncDocfileOnIFillLockBytes>
extern __imp_StgOpenPropStg:PANYARGS
StgOpenPropStg TEXTEQU <__imp_StgOpenPropStg>
extern __imp_StgOpenStorage:PANYARGS
StgOpenStorage TEXTEQU <__imp_StgOpenStorage>
extern __imp_StgOpenStorageEx:PANYARGS
StgOpenStorageEx TEXTEQU <__imp_StgOpenStorageEx>
extern __imp_StgOpenStorageOnHandle:PANYARGS
StgOpenStorageOnHandle TEXTEQU <__imp_StgOpenStorageOnHandle>
extern __imp_StgOpenStorageOnILockBytes:PANYARGS
StgOpenStorageOnILockBytes TEXTEQU <__imp_StgOpenStorageOnILockBytes>
extern __imp_StgPropertyLengthAsVariant:PANYARGS
StgPropertyLengthAsVariant TEXTEQU <__imp_StgPropertyLengthAsVariant>
extern __imp_StgSetTimes:PANYARGS
StgSetTimes TEXTEQU <__imp_StgSetTimes>
extern __imp_StringFromCLSID:PANYARGS
StringFromCLSID TEXTEQU <__imp_StringFromCLSID>
extern __imp_StringFromGUID2:PANYARGS
StringFromGUID2 TEXTEQU <__imp_StringFromGUID2>
extern __imp_StringFromIID:PANYARGS
StringFromIID TEXTEQU <__imp_StringFromIID>
extern __imp_UpdateDCOMSettings:PANYARGS
UpdateDCOMSettings TEXTEQU <__imp_UpdateDCOMSettings>
extern __imp_UpdateProcessTracing:PANYARGS
UpdateProcessTracing TEXTEQU <__imp_UpdateProcessTracing>
extern __imp_UtConvertDvtd16toDvtd32:PANYARGS
UtConvertDvtd16toDvtd32 TEXTEQU <__imp_UtConvertDvtd16toDvtd32>
extern __imp_UtConvertDvtd32toDvtd16:PANYARGS
UtConvertDvtd32toDvtd16 TEXTEQU <__imp_UtConvertDvtd32toDvtd16>
extern __imp_UtGetDvtd16Info:PANYARGS
UtGetDvtd16Info TEXTEQU <__imp_UtGetDvtd16Info>
extern __imp_UtGetDvtd32Info:PANYARGS
UtGetDvtd32Info TEXTEQU <__imp_UtGetDvtd32Info>
extern __imp_WdtpInterfacePointer_UserFree:PANYARGS
WdtpInterfacePointer_UserFree TEXTEQU <__imp_WdtpInterfacePointer_UserFree>
extern __imp_WdtpInterfacePointer_UserFree64:PANYARGS
WdtpInterfacePointer_UserFree64 TEXTEQU <__imp_WdtpInterfacePointer_UserFree64>
extern __imp_WdtpInterfacePointer_UserMarshal:PANYARGS
WdtpInterfacePointer_UserMarshal TEXTEQU <__imp_WdtpInterfacePointer_UserMarshal>
extern __imp_WdtpInterfacePointer_UserMarshal64:PANYARGS
WdtpInterfacePointer_UserMarshal64 TEXTEQU <__imp_WdtpInterfacePointer_UserMarshal64>
extern __imp_WdtpInterfacePointer_UserSize:PANYARGS
WdtpInterfacePointer_UserSize TEXTEQU <__imp_WdtpInterfacePointer_UserSize>
extern __imp_WdtpInterfacePointer_UserSize64:PANYARGS
WdtpInterfacePointer_UserSize64 TEXTEQU <__imp_WdtpInterfacePointer_UserSize64>
extern __imp_WdtpInterfacePointer_UserUnmarshal:PANYARGS
WdtpInterfacePointer_UserUnmarshal TEXTEQU <__imp_WdtpInterfacePointer_UserUnmarshal>
extern __imp_WdtpInterfacePointer_UserUnmarshal64:PANYARGS
WdtpInterfacePointer_UserUnmarshal64 TEXTEQU <__imp_WdtpInterfacePointer_UserUnmarshal64>
extern __imp_WriteClassStg:PANYARGS
WriteClassStg TEXTEQU <__imp_WriteClassStg>
extern __imp_WriteClassStm:PANYARGS
WriteClassStm TEXTEQU <__imp_WriteClassStm>
extern __imp_WriteFmtUserTypeStg:PANYARGS
WriteFmtUserTypeStg TEXTEQU <__imp_WriteFmtUserTypeStg>
extern __imp_WriteOleStg:PANYARGS
WriteOleStg TEXTEQU <__imp_WriteOleStg>
extern __imp_WriteStringStream:PANYARGS
WriteStringStream TEXTEQU <__imp_WriteStringStream>
