extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_AccessibleChildren:PANYARGS
AccessibleChildren TEXTEQU <__imp_AccessibleChildren>
extern __imp_AccessibleObjectFromEvent:PANYARGS
AccessibleObjectFromEvent TEXTEQU <__imp_AccessibleObjectFromEvent>
extern __imp_AccessibleObjectFromPoint:PANYARGS
AccessibleObjectFromPoint TEXTEQU <__imp_AccessibleObjectFromPoint>
extern __imp_AccessibleObjectFromWindow:PANYARGS
AccessibleObjectFromWindow TEXTEQU <__imp_AccessibleObjectFromWindow>
extern __imp_CreateStdAccessibleObject:PANYARGS
CreateStdAccessibleObject TEXTEQU <__imp_CreateStdAccessibleObject>
extern __imp_CreateStdAccessibleProxyA:PANYARGS
CreateStdAccessibleProxy  TEXTEQU <__imp_CreateStdAccessibleProxyA>
extern __imp_CreateStdAccessibleProxyW:PANYARGS
CreateStdAccessibleProxyW TEXTEQU <__imp_CreateStdAccessibleProxyW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_GetOleaccVersionInfo:PANYARGS
GetOleaccVersionInfo TEXTEQU <__imp_GetOleaccVersionInfo>
extern __imp_GetRoleTextA:PANYARGS
GetRoleText  TEXTEQU <__imp_GetRoleTextA>
extern __imp_GetRoleTextW:PANYARGS
GetRoleTextW TEXTEQU <__imp_GetRoleTextW>
extern __imp_GetStateTextA:PANYARGS
GetStateText  TEXTEQU <__imp_GetStateTextA>
extern __imp_GetStateTextW:PANYARGS
GetStateTextW TEXTEQU <__imp_GetStateTextW>
extern __imp_IID_IAccessible:PANYARGS
IID_IAccessible TEXTEQU <__imp_IID_IAccessible>
extern __imp_IID_IAccessibleHandler:PANYARGS
IID_IAccessibleHandler TEXTEQU <__imp_IID_IAccessibleHandler>
extern __imp_LIBID_Accessibility:PANYARGS
LIBID_Accessibility TEXTEQU <__imp_LIBID_Accessibility>
extern __imp_LresultFromObject:PANYARGS
LresultFromObject TEXTEQU <__imp_LresultFromObject>
extern __imp_ObjectFromLresult:PANYARGS
ObjectFromLresult TEXTEQU <__imp_ObjectFromLresult>
extern __imp_WindowFromAccessibleObject:PANYARGS
WindowFromAccessibleObject TEXTEQU <__imp_WindowFromAccessibleObject>
