extern __imp_SysAllocString:PANYARGS
SysAllocString TEXTEQU <__imp_SysAllocString>
extern __imp_SysReAllocString:PANYARGS
SysReAllocString TEXTEQU <__imp_SysReAllocString>
extern __imp_SysAllocStringLen:PANYARGS
SysAllocStringLen TEXTEQU <__imp_SysAllocStringLen>
extern __imp_SysReAllocStringLen:PANYARGS
SysReAllocStringLen TEXTEQU <__imp_SysReAllocStringLen>
extern __imp_SysFreeString:PANYARGS
SysFreeString TEXTEQU <__imp_SysFreeString>
extern __imp_SysStringLen:PANYARGS
SysStringLen TEXTEQU <__imp_SysStringLen>
extern __imp_VariantInit:PANYARGS
VariantInit TEXTEQU <__imp_VariantInit>
extern __imp_VariantClear:PANYARGS
VariantClear TEXTEQU <__imp_VariantClear>
extern __imp_VariantCopy:PANYARGS
VariantCopy TEXTEQU <__imp_VariantCopy>
extern __imp_VariantCopyInd:PANYARGS
VariantCopyInd TEXTEQU <__imp_VariantCopyInd>
extern __imp_VariantChangeType:PANYARGS
VariantChangeType TEXTEQU <__imp_VariantChangeType>
extern __imp_VariantTimeToDosDateTime:PANYARGS
VariantTimeToDosDateTime TEXTEQU <__imp_VariantTimeToDosDateTime>
extern __imp_DosDateTimeToVariantTime:PANYARGS
DosDateTimeToVariantTime TEXTEQU <__imp_DosDateTimeToVariantTime>
extern __imp_SafeArrayCreate:PANYARGS
SafeArrayCreate TEXTEQU <__imp_SafeArrayCreate>
extern __imp_SafeArrayDestroy:PANYARGS
SafeArrayDestroy TEXTEQU <__imp_SafeArrayDestroy>
extern __imp_SafeArrayGetDim:PANYARGS
SafeArrayGetDim TEXTEQU <__imp_SafeArrayGetDim>
extern __imp_SafeArrayGetElemsize:PANYARGS
SafeArrayGetElemsize TEXTEQU <__imp_SafeArrayGetElemsize>
extern __imp_SafeArrayGetUBound:PANYARGS
SafeArrayGetUBound TEXTEQU <__imp_SafeArrayGetUBound>
extern __imp_SafeArrayGetLBound:PANYARGS
SafeArrayGetLBound TEXTEQU <__imp_SafeArrayGetLBound>
extern __imp_SafeArrayLock:PANYARGS
SafeArrayLock TEXTEQU <__imp_SafeArrayLock>
extern __imp_SafeArrayUnlock:PANYARGS
SafeArrayUnlock TEXTEQU <__imp_SafeArrayUnlock>
extern __imp_SafeArrayAccessData:PANYARGS
SafeArrayAccessData TEXTEQU <__imp_SafeArrayAccessData>
extern __imp_SafeArrayUnaccessData:PANYARGS
SafeArrayUnaccessData TEXTEQU <__imp_SafeArrayUnaccessData>
extern __imp_SafeArrayGetElement:PANYARGS
SafeArrayGetElement TEXTEQU <__imp_SafeArrayGetElement>
extern __imp_SafeArrayPutElement:PANYARGS
SafeArrayPutElement TEXTEQU <__imp_SafeArrayPutElement>
extern __imp_SafeArrayCopy:PANYARGS
SafeArrayCopy TEXTEQU <__imp_SafeArrayCopy>
extern __imp_DispGetParam:PANYARGS
DispGetParam TEXTEQU <__imp_DispGetParam>
extern __imp_DispGetIDsOfNames:PANYARGS
DispGetIDsOfNames TEXTEQU <__imp_DispGetIDsOfNames>
extern __imp_DispInvoke:PANYARGS
DispInvoke TEXTEQU <__imp_DispInvoke>
extern __imp_CreateDispTypeInfo:PANYARGS
CreateDispTypeInfo TEXTEQU <__imp_CreateDispTypeInfo>
extern __imp_CreateStdDispatch:PANYARGS
CreateStdDispatch TEXTEQU <__imp_CreateStdDispatch>
extern __imp_RegisterActiveObject:PANYARGS
RegisterActiveObject TEXTEQU <__imp_RegisterActiveObject>
extern __imp_RevokeActiveObject:PANYARGS
RevokeActiveObject TEXTEQU <__imp_RevokeActiveObject>
extern __imp_GetActiveObject:PANYARGS
GetActiveObject TEXTEQU <__imp_GetActiveObject>
extern __imp_SafeArrayAllocDescriptor:PANYARGS
SafeArrayAllocDescriptor TEXTEQU <__imp_SafeArrayAllocDescriptor>
extern __imp_SafeArrayAllocData:PANYARGS
SafeArrayAllocData TEXTEQU <__imp_SafeArrayAllocData>
extern __imp_SafeArrayDestroyDescriptor:PANYARGS
SafeArrayDestroyDescriptor TEXTEQU <__imp_SafeArrayDestroyDescriptor>
extern __imp_SafeArrayDestroyData:PANYARGS
SafeArrayDestroyData TEXTEQU <__imp_SafeArrayDestroyData>
extern __imp_SafeArrayRedim:PANYARGS
SafeArrayRedim TEXTEQU <__imp_SafeArrayRedim>
extern __imp_SafeArrayAllocDescriptorEx:PANYARGS
SafeArrayAllocDescriptorEx TEXTEQU <__imp_SafeArrayAllocDescriptorEx>
extern __imp_SafeArrayCreateEx:PANYARGS
SafeArrayCreateEx TEXTEQU <__imp_SafeArrayCreateEx>
extern __imp_SafeArrayCreateVectorEx:PANYARGS
SafeArrayCreateVectorEx TEXTEQU <__imp_SafeArrayCreateVectorEx>
extern __imp_SafeArraySetRecordInfo:PANYARGS
SafeArraySetRecordInfo TEXTEQU <__imp_SafeArraySetRecordInfo>
extern __imp_SafeArrayGetRecordInfo:PANYARGS
SafeArrayGetRecordInfo TEXTEQU <__imp_SafeArrayGetRecordInfo>
extern __imp_VarParseNumFromStr:PANYARGS
VarParseNumFromStr TEXTEQU <__imp_VarParseNumFromStr>
extern __imp_VarNumFromParseNum:PANYARGS
VarNumFromParseNum TEXTEQU <__imp_VarNumFromParseNum>
extern __imp_VarI2FromUI1:PANYARGS
VarI2FromUI1 TEXTEQU <__imp_VarI2FromUI1>
extern __imp_VarI2FromI4:PANYARGS
VarI2FromI4 TEXTEQU <__imp_VarI2FromI4>
extern __imp_VarI2FromR4:PANYARGS
VarI2FromR4 TEXTEQU <__imp_VarI2FromR4>
extern __imp_VarI2FromR8:PANYARGS
VarI2FromR8 TEXTEQU <__imp_VarI2FromR8>
extern __imp_VarI2FromCy:PANYARGS
VarI2FromCy TEXTEQU <__imp_VarI2FromCy>
extern __imp_VarI2FromDate:PANYARGS
VarI2FromDate TEXTEQU <__imp_VarI2FromDate>
extern __imp_VarI2FromStr:PANYARGS
VarI2FromStr TEXTEQU <__imp_VarI2FromStr>
extern __imp_VarI2FromDisp:PANYARGS
VarI2FromDisp TEXTEQU <__imp_VarI2FromDisp>
extern __imp_VarI2FromBool:PANYARGS
VarI2FromBool TEXTEQU <__imp_VarI2FromBool>
extern __imp_SafeArraySetIID:PANYARGS
SafeArraySetIID TEXTEQU <__imp_SafeArraySetIID>
extern __imp_VarI4FromUI1:PANYARGS
VarI4FromUI1 TEXTEQU <__imp_VarI4FromUI1>
extern __imp_VarI4FromI2:PANYARGS
VarI4FromI2 TEXTEQU <__imp_VarI4FromI2>
extern __imp_VarI4FromR4:PANYARGS
VarI4FromR4 TEXTEQU <__imp_VarI4FromR4>
extern __imp_VarI4FromR8:PANYARGS
VarI4FromR8 TEXTEQU <__imp_VarI4FromR8>
extern __imp_VarI4FromCy:PANYARGS
VarI4FromCy TEXTEQU <__imp_VarI4FromCy>
extern __imp_VarI4FromDate:PANYARGS
VarI4FromDate TEXTEQU <__imp_VarI4FromDate>
extern __imp_VarI4FromStr:PANYARGS
VarI4FromStr TEXTEQU <__imp_VarI4FromStr>
extern __imp_VarI4FromDisp:PANYARGS
VarI4FromDisp TEXTEQU <__imp_VarI4FromDisp>
extern __imp_VarI4FromBool:PANYARGS
VarI4FromBool TEXTEQU <__imp_VarI4FromBool>
extern __imp_SafeArrayGetIID:PANYARGS
SafeArrayGetIID TEXTEQU <__imp_SafeArrayGetIID>
extern __imp_VarR4FromUI1:PANYARGS
VarR4FromUI1 TEXTEQU <__imp_VarR4FromUI1>
extern __imp_VarR4FromI2:PANYARGS
VarR4FromI2 TEXTEQU <__imp_VarR4FromI2>
extern __imp_VarR4FromI4:PANYARGS
VarR4FromI4 TEXTEQU <__imp_VarR4FromI4>
extern __imp_VarR4FromR8:PANYARGS
VarR4FromR8 TEXTEQU <__imp_VarR4FromR8>
extern __imp_VarR4FromCy:PANYARGS
VarR4FromCy TEXTEQU <__imp_VarR4FromCy>
extern __imp_VarR4FromDate:PANYARGS
VarR4FromDate TEXTEQU <__imp_VarR4FromDate>
extern __imp_VarR4FromStr:PANYARGS
VarR4FromStr TEXTEQU <__imp_VarR4FromStr>
extern __imp_VarR4FromDisp:PANYARGS
VarR4FromDisp TEXTEQU <__imp_VarR4FromDisp>
extern __imp_VarR4FromBool:PANYARGS
VarR4FromBool TEXTEQU <__imp_VarR4FromBool>
extern __imp_SafeArrayGetVartype:PANYARGS
SafeArrayGetVartype TEXTEQU <__imp_SafeArrayGetVartype>
extern __imp_VarR8FromUI1:PANYARGS
VarR8FromUI1 TEXTEQU <__imp_VarR8FromUI1>
extern __imp_VarR8FromI2:PANYARGS
VarR8FromI2 TEXTEQU <__imp_VarR8FromI2>
extern __imp_VarR8FromI4:PANYARGS
VarR8FromI4 TEXTEQU <__imp_VarR8FromI4>
extern __imp_VarR8FromR4:PANYARGS
VarR8FromR4 TEXTEQU <__imp_VarR8FromR4>
extern __imp_VarR8FromCy:PANYARGS
VarR8FromCy TEXTEQU <__imp_VarR8FromCy>
extern __imp_VarR8FromDate:PANYARGS
VarR8FromDate TEXTEQU <__imp_VarR8FromDate>
extern __imp_VarR8FromStr:PANYARGS
VarR8FromStr TEXTEQU <__imp_VarR8FromStr>
extern __imp_VarR8FromDisp:PANYARGS
VarR8FromDisp TEXTEQU <__imp_VarR8FromDisp>
extern __imp_VarR8FromBool:PANYARGS
VarR8FromBool TEXTEQU <__imp_VarR8FromBool>
extern __imp_VarFormat:PANYARGS
VarFormat TEXTEQU <__imp_VarFormat>
extern __imp_VarDateFromUI1:PANYARGS
VarDateFromUI1 TEXTEQU <__imp_VarDateFromUI1>
extern __imp_VarDateFromI2:PANYARGS
VarDateFromI2 TEXTEQU <__imp_VarDateFromI2>
extern __imp_VarDateFromI4:PANYARGS
VarDateFromI4 TEXTEQU <__imp_VarDateFromI4>
extern __imp_VarDateFromR4:PANYARGS
VarDateFromR4 TEXTEQU <__imp_VarDateFromR4>
extern __imp_VarDateFromR8:PANYARGS
VarDateFromR8 TEXTEQU <__imp_VarDateFromR8>
extern __imp_VarDateFromCy:PANYARGS
VarDateFromCy TEXTEQU <__imp_VarDateFromCy>
extern __imp_VarDateFromStr:PANYARGS
VarDateFromStr TEXTEQU <__imp_VarDateFromStr>
extern __imp_VarDateFromDisp:PANYARGS
VarDateFromDisp TEXTEQU <__imp_VarDateFromDisp>
extern __imp_VarDateFromBool:PANYARGS
VarDateFromBool TEXTEQU <__imp_VarDateFromBool>
extern __imp_VarFormatDateTime:PANYARGS
VarFormatDateTime TEXTEQU <__imp_VarFormatDateTime>
extern __imp_VarCyFromUI1:PANYARGS
VarCyFromUI1 TEXTEQU <__imp_VarCyFromUI1>
extern __imp_VarCyFromI2:PANYARGS
VarCyFromI2 TEXTEQU <__imp_VarCyFromI2>
extern __imp_VarCyFromI4:PANYARGS
VarCyFromI4 TEXTEQU <__imp_VarCyFromI4>
extern __imp_VarCyFromR4:PANYARGS
VarCyFromR4 TEXTEQU <__imp_VarCyFromR4>
extern __imp_VarCyFromR8:PANYARGS
VarCyFromR8 TEXTEQU <__imp_VarCyFromR8>
extern __imp_VarCyFromDate:PANYARGS
VarCyFromDate TEXTEQU <__imp_VarCyFromDate>
extern __imp_VarCyFromStr:PANYARGS
VarCyFromStr TEXTEQU <__imp_VarCyFromStr>
extern __imp_VarCyFromDisp:PANYARGS
VarCyFromDisp TEXTEQU <__imp_VarCyFromDisp>
extern __imp_VarCyFromBool:PANYARGS
VarCyFromBool TEXTEQU <__imp_VarCyFromBool>
extern __imp_VarFormatNumber:PANYARGS
VarFormatNumber TEXTEQU <__imp_VarFormatNumber>
extern __imp_VarBstrFromUI1:PANYARGS
VarBstrFromUI1 TEXTEQU <__imp_VarBstrFromUI1>
extern __imp_VarBstrFromI2:PANYARGS
VarBstrFromI2 TEXTEQU <__imp_VarBstrFromI2>
extern __imp_VarBstrFromI4:PANYARGS
VarBstrFromI4 TEXTEQU <__imp_VarBstrFromI4>
extern __imp_VarBstrFromR4:PANYARGS
VarBstrFromR4 TEXTEQU <__imp_VarBstrFromR4>
extern __imp_VarBstrFromR8:PANYARGS
VarBstrFromR8 TEXTEQU <__imp_VarBstrFromR8>
extern __imp_VarBstrFromCy:PANYARGS
VarBstrFromCy TEXTEQU <__imp_VarBstrFromCy>
extern __imp_VarBstrFromDate:PANYARGS
VarBstrFromDate TEXTEQU <__imp_VarBstrFromDate>
extern __imp_VarBstrFromDisp:PANYARGS
VarBstrFromDisp TEXTEQU <__imp_VarBstrFromDisp>
extern __imp_VarBstrFromBool:PANYARGS
VarBstrFromBool TEXTEQU <__imp_VarBstrFromBool>
extern __imp_VarFormatPercent:PANYARGS
VarFormatPercent TEXTEQU <__imp_VarFormatPercent>
extern __imp_VarBoolFromUI1:PANYARGS
VarBoolFromUI1 TEXTEQU <__imp_VarBoolFromUI1>
extern __imp_VarBoolFromI2:PANYARGS
VarBoolFromI2 TEXTEQU <__imp_VarBoolFromI2>
extern __imp_VarBoolFromI4:PANYARGS
VarBoolFromI4 TEXTEQU <__imp_VarBoolFromI4>
extern __imp_VarBoolFromR4:PANYARGS
VarBoolFromR4 TEXTEQU <__imp_VarBoolFromR4>
extern __imp_VarBoolFromR8:PANYARGS
VarBoolFromR8 TEXTEQU <__imp_VarBoolFromR8>
extern __imp_VarBoolFromDate:PANYARGS
VarBoolFromDate TEXTEQU <__imp_VarBoolFromDate>
extern __imp_VarBoolFromCy:PANYARGS
VarBoolFromCy TEXTEQU <__imp_VarBoolFromCy>
extern __imp_VarBoolFromStr:PANYARGS
VarBoolFromStr TEXTEQU <__imp_VarBoolFromStr>
extern __imp_VarBoolFromDisp:PANYARGS
VarBoolFromDisp TEXTEQU <__imp_VarBoolFromDisp>
extern __imp_VarFormatCurrency:PANYARGS
VarFormatCurrency TEXTEQU <__imp_VarFormatCurrency>
extern __imp_VarWeekdayName:PANYARGS
VarWeekdayName TEXTEQU <__imp_VarWeekdayName>
extern __imp_VarMonthName:PANYARGS
VarMonthName TEXTEQU <__imp_VarMonthName>
extern __imp_VarUI1FromI2:PANYARGS
VarUI1FromI2 TEXTEQU <__imp_VarUI1FromI2>
extern __imp_VarUI1FromI4:PANYARGS
VarUI1FromI4 TEXTEQU <__imp_VarUI1FromI4>
extern __imp_VarUI1FromR4:PANYARGS
VarUI1FromR4 TEXTEQU <__imp_VarUI1FromR4>
extern __imp_VarUI1FromR8:PANYARGS
VarUI1FromR8 TEXTEQU <__imp_VarUI1FromR8>
extern __imp_VarUI1FromCy:PANYARGS
VarUI1FromCy TEXTEQU <__imp_VarUI1FromCy>
extern __imp_VarUI1FromDate:PANYARGS
VarUI1FromDate TEXTEQU <__imp_VarUI1FromDate>
extern __imp_VarUI1FromStr:PANYARGS
VarUI1FromStr TEXTEQU <__imp_VarUI1FromStr>
extern __imp_VarUI1FromDisp:PANYARGS
VarUI1FromDisp TEXTEQU <__imp_VarUI1FromDisp>
extern __imp_VarUI1FromBool:PANYARGS
VarUI1FromBool TEXTEQU <__imp_VarUI1FromBool>
extern __imp_VarFormatFromTokens:PANYARGS
VarFormatFromTokens TEXTEQU <__imp_VarFormatFromTokens>
extern __imp_VarTokenizeFormatString:PANYARGS
VarTokenizeFormatString TEXTEQU <__imp_VarTokenizeFormatString>
extern __imp_VarAdd:PANYARGS
VarAdd TEXTEQU <__imp_VarAdd>
extern __imp_VarAnd:PANYARGS
VarAnd TEXTEQU <__imp_VarAnd>
extern __imp_VarDiv:PANYARGS
VarDiv TEXTEQU <__imp_VarDiv>
extern __imp_BSTR_UserFree64:PANYARGS
BSTR_UserFree64 TEXTEQU <__imp_BSTR_UserFree64>
extern __imp_BSTR_UserMarshal64:PANYARGS
BSTR_UserMarshal64 TEXTEQU <__imp_BSTR_UserMarshal64>
extern __imp_DispCallFunc:PANYARGS
DispCallFunc TEXTEQU <__imp_DispCallFunc>
extern __imp_VariantChangeTypeEx:PANYARGS
VariantChangeTypeEx TEXTEQU <__imp_VariantChangeTypeEx>
extern __imp_SafeArrayPtrOfIndex:PANYARGS
SafeArrayPtrOfIndex TEXTEQU <__imp_SafeArrayPtrOfIndex>
extern __imp_SysStringByteLen:PANYARGS
SysStringByteLen TEXTEQU <__imp_SysStringByteLen>
extern __imp_SysAllocStringByteLen:PANYARGS
SysAllocStringByteLen TEXTEQU <__imp_SysAllocStringByteLen>
extern __imp_BSTR_UserSize64:PANYARGS
BSTR_UserSize64 TEXTEQU <__imp_BSTR_UserSize64>
extern __imp_VarEqv:PANYARGS
VarEqv TEXTEQU <__imp_VarEqv>
extern __imp_VarIdiv:PANYARGS
VarIdiv TEXTEQU <__imp_VarIdiv>
extern __imp_VarImp:PANYARGS
VarImp TEXTEQU <__imp_VarImp>
extern __imp_VarMod:PANYARGS
VarMod TEXTEQU <__imp_VarMod>
extern __imp_VarMul:PANYARGS
VarMul TEXTEQU <__imp_VarMul>
extern __imp_VarOr:PANYARGS
VarOr TEXTEQU <__imp_VarOr>
extern __imp_VarPow:PANYARGS
VarPow TEXTEQU <__imp_VarPow>
extern __imp_VarSub:PANYARGS
VarSub TEXTEQU <__imp_VarSub>
extern __imp_CreateTypeLib:PANYARGS
CreateTypeLib TEXTEQU <__imp_CreateTypeLib>
extern __imp_LoadTypeLib:PANYARGS
LoadTypeLib TEXTEQU <__imp_LoadTypeLib>
extern __imp_LoadRegTypeLib:PANYARGS
LoadRegTypeLib TEXTEQU <__imp_LoadRegTypeLib>
extern __imp_RegisterTypeLib:PANYARGS
RegisterTypeLib TEXTEQU <__imp_RegisterTypeLib>
extern __imp_QueryPathOfRegTypeLib:PANYARGS
QueryPathOfRegTypeLib TEXTEQU <__imp_QueryPathOfRegTypeLib>
extern __imp_LHashValOfNameSys:PANYARGS
LHashValOfNameSys TEXTEQU <__imp_LHashValOfNameSys>
extern __imp_LHashValOfNameSysA:PANYARGS
LHashValOfNameSys  TEXTEQU <__imp_LHashValOfNameSysA>
extern __imp_VarXor:PANYARGS
VarXor TEXTEQU <__imp_VarXor>
extern __imp_VarAbs:PANYARGS
VarAbs TEXTEQU <__imp_VarAbs>
extern __imp_VarFix:PANYARGS
VarFix TEXTEQU <__imp_VarFix>
extern __imp_OaBuildVersion:PANYARGS
OaBuildVersion TEXTEQU <__imp_OaBuildVersion>
extern __imp_ClearCustData:PANYARGS
ClearCustData TEXTEQU <__imp_ClearCustData>
extern __imp_VarInt:PANYARGS
VarInt TEXTEQU <__imp_VarInt>
extern __imp_VarNeg:PANYARGS
VarNeg TEXTEQU <__imp_VarNeg>
extern __imp_VarNot:PANYARGS
VarNot TEXTEQU <__imp_VarNot>
extern __imp_VarRound:PANYARGS
VarRound TEXTEQU <__imp_VarRound>
extern __imp_VarCmp:PANYARGS
VarCmp TEXTEQU <__imp_VarCmp>
extern __imp_VarDecAdd:PANYARGS
VarDecAdd TEXTEQU <__imp_VarDecAdd>
extern __imp_VarDecDiv:PANYARGS
VarDecDiv TEXTEQU <__imp_VarDecDiv>
extern __imp_VarDecMul:PANYARGS
VarDecMul TEXTEQU <__imp_VarDecMul>
extern __imp_CreateTypeLib2:PANYARGS
CreateTypeLib2 TEXTEQU <__imp_CreateTypeLib2>
extern __imp_VarDecSub:PANYARGS
VarDecSub TEXTEQU <__imp_VarDecSub>
extern __imp_VarDecAbs:PANYARGS
VarDecAbs TEXTEQU <__imp_VarDecAbs>
extern __imp_LoadTypeLibEx:PANYARGS
LoadTypeLibEx TEXTEQU <__imp_LoadTypeLibEx>
extern __imp_SystemTimeToVariantTime:PANYARGS
SystemTimeToVariantTime TEXTEQU <__imp_SystemTimeToVariantTime>
extern __imp_VariantTimeToSystemTime:PANYARGS
VariantTimeToSystemTime TEXTEQU <__imp_VariantTimeToSystemTime>
extern __imp_UnRegisterTypeLib:PANYARGS
UnRegisterTypeLib TEXTEQU <__imp_UnRegisterTypeLib>
extern __imp_VarDecFix:PANYARGS
VarDecFix TEXTEQU <__imp_VarDecFix>
extern __imp_VarDecInt:PANYARGS
VarDecInt TEXTEQU <__imp_VarDecInt>
extern __imp_VarDecNeg:PANYARGS
VarDecNeg TEXTEQU <__imp_VarDecNeg>
extern __imp_VarDecFromUI1:PANYARGS
VarDecFromUI1 TEXTEQU <__imp_VarDecFromUI1>
extern __imp_VarDecFromI2:PANYARGS
VarDecFromI2 TEXTEQU <__imp_VarDecFromI2>
extern __imp_VarDecFromI4:PANYARGS
VarDecFromI4 TEXTEQU <__imp_VarDecFromI4>
extern __imp_VarDecFromR4:PANYARGS
VarDecFromR4 TEXTEQU <__imp_VarDecFromR4>
extern __imp_VarDecFromR8:PANYARGS
VarDecFromR8 TEXTEQU <__imp_VarDecFromR8>
extern __imp_VarDecFromDate:PANYARGS
VarDecFromDate TEXTEQU <__imp_VarDecFromDate>
extern __imp_VarDecFromCy:PANYARGS
VarDecFromCy TEXTEQU <__imp_VarDecFromCy>
extern __imp_VarDecFromStr:PANYARGS
VarDecFromStr TEXTEQU <__imp_VarDecFromStr>
extern __imp_VarDecFromDisp:PANYARGS
VarDecFromDisp TEXTEQU <__imp_VarDecFromDisp>
extern __imp_VarDecFromBool:PANYARGS
VarDecFromBool TEXTEQU <__imp_VarDecFromBool>
extern __imp_GetErrorInfo:PANYARGS
GetErrorInfo TEXTEQU <__imp_GetErrorInfo>
extern __imp_SetErrorInfo:PANYARGS
SetErrorInfo TEXTEQU <__imp_SetErrorInfo>
extern __imp_CreateErrorInfo:PANYARGS
CreateErrorInfo TEXTEQU <__imp_CreateErrorInfo>
extern __imp_VarDecRound:PANYARGS
VarDecRound TEXTEQU <__imp_VarDecRound>
extern __imp_VarDecCmp:PANYARGS
VarDecCmp TEXTEQU <__imp_VarDecCmp>
extern __imp_VarI2FromI1:PANYARGS
VarI2FromI1 TEXTEQU <__imp_VarI2FromI1>
extern __imp_VarI2FromUI2:PANYARGS
VarI2FromUI2 TEXTEQU <__imp_VarI2FromUI2>
extern __imp_VarI2FromUI4:PANYARGS
VarI2FromUI4 TEXTEQU <__imp_VarI2FromUI4>
extern __imp_VarI2FromDec:PANYARGS
VarI2FromDec TEXTEQU <__imp_VarI2FromDec>
extern __imp_VarI4FromI1:PANYARGS
VarI4FromI1 TEXTEQU <__imp_VarI4FromI1>
extern __imp_VarI4FromUI2:PANYARGS
VarI4FromUI2 TEXTEQU <__imp_VarI4FromUI2>
extern __imp_VarI4FromUI4:PANYARGS
VarI4FromUI4 TEXTEQU <__imp_VarI4FromUI4>
extern __imp_VarI4FromDec:PANYARGS
VarI4FromDec TEXTEQU <__imp_VarI4FromDec>
extern __imp_VarR4FromI1:PANYARGS
VarR4FromI1 TEXTEQU <__imp_VarR4FromI1>
extern __imp_VarR4FromUI2:PANYARGS
VarR4FromUI2 TEXTEQU <__imp_VarR4FromUI2>
extern __imp_VarR4FromUI4:PANYARGS
VarR4FromUI4 TEXTEQU <__imp_VarR4FromUI4>
extern __imp_VarR4FromDec:PANYARGS
VarR4FromDec TEXTEQU <__imp_VarR4FromDec>
extern __imp_VarR8FromI1:PANYARGS
VarR8FromI1 TEXTEQU <__imp_VarR8FromI1>
extern __imp_VarR8FromUI2:PANYARGS
VarR8FromUI2 TEXTEQU <__imp_VarR8FromUI2>
extern __imp_VarR8FromUI4:PANYARGS
VarR8FromUI4 TEXTEQU <__imp_VarR8FromUI4>
extern __imp_VarR8FromDec:PANYARGS
VarR8FromDec TEXTEQU <__imp_VarR8FromDec>
extern __imp_VarDateFromI1:PANYARGS
VarDateFromI1 TEXTEQU <__imp_VarDateFromI1>
extern __imp_VarDateFromUI2:PANYARGS
VarDateFromUI2 TEXTEQU <__imp_VarDateFromUI2>
extern __imp_VarDateFromUI4:PANYARGS
VarDateFromUI4 TEXTEQU <__imp_VarDateFromUI4>
extern __imp_VarDateFromDec:PANYARGS
VarDateFromDec TEXTEQU <__imp_VarDateFromDec>
extern __imp_VarCyFromI1:PANYARGS
VarCyFromI1 TEXTEQU <__imp_VarCyFromI1>
extern __imp_VarCyFromUI2:PANYARGS
VarCyFromUI2 TEXTEQU <__imp_VarCyFromUI2>
extern __imp_VarCyFromUI4:PANYARGS
VarCyFromUI4 TEXTEQU <__imp_VarCyFromUI4>
extern __imp_VarCyFromDec:PANYARGS
VarCyFromDec TEXTEQU <__imp_VarCyFromDec>
extern __imp_VarBstrFromI1:PANYARGS
VarBstrFromI1 TEXTEQU <__imp_VarBstrFromI1>
extern __imp_VarBstrFromUI2:PANYARGS
VarBstrFromUI2 TEXTEQU <__imp_VarBstrFromUI2>
extern __imp_VarBstrFromUI4:PANYARGS
VarBstrFromUI4 TEXTEQU <__imp_VarBstrFromUI4>
extern __imp_VarBstrFromDec:PANYARGS
VarBstrFromDec TEXTEQU <__imp_VarBstrFromDec>
extern __imp_VarBoolFromI1:PANYARGS
VarBoolFromI1 TEXTEQU <__imp_VarBoolFromI1>
extern __imp_VarBoolFromUI2:PANYARGS
VarBoolFromUI2 TEXTEQU <__imp_VarBoolFromUI2>
extern __imp_VarBoolFromUI4:PANYARGS
VarBoolFromUI4 TEXTEQU <__imp_VarBoolFromUI4>
extern __imp_VarBoolFromDec:PANYARGS
VarBoolFromDec TEXTEQU <__imp_VarBoolFromDec>
extern __imp_VarUI1FromI1:PANYARGS
VarUI1FromI1 TEXTEQU <__imp_VarUI1FromI1>
extern __imp_VarUI1FromUI2:PANYARGS
VarUI1FromUI2 TEXTEQU <__imp_VarUI1FromUI2>
extern __imp_VarUI1FromUI4:PANYARGS
VarUI1FromUI4 TEXTEQU <__imp_VarUI1FromUI4>
extern __imp_VarUI1FromDec:PANYARGS
VarUI1FromDec TEXTEQU <__imp_VarUI1FromDec>
extern __imp_VarDecFromI1:PANYARGS
VarDecFromI1 TEXTEQU <__imp_VarDecFromI1>
extern __imp_VarDecFromUI2:PANYARGS
VarDecFromUI2 TEXTEQU <__imp_VarDecFromUI2>
extern __imp_VarDecFromUI4:PANYARGS
VarDecFromUI4 TEXTEQU <__imp_VarDecFromUI4>
extern __imp_VarI1FromUI1:PANYARGS
VarI1FromUI1 TEXTEQU <__imp_VarI1FromUI1>
extern __imp_VarI1FromI2:PANYARGS
VarI1FromI2 TEXTEQU <__imp_VarI1FromI2>
extern __imp_VarI1FromI4:PANYARGS
VarI1FromI4 TEXTEQU <__imp_VarI1FromI4>
extern __imp_VarI1FromR4:PANYARGS
VarI1FromR4 TEXTEQU <__imp_VarI1FromR4>
extern __imp_VarI1FromR8:PANYARGS
VarI1FromR8 TEXTEQU <__imp_VarI1FromR8>
extern __imp_VarI1FromDate:PANYARGS
VarI1FromDate TEXTEQU <__imp_VarI1FromDate>
extern __imp_VarI1FromCy:PANYARGS
VarI1FromCy TEXTEQU <__imp_VarI1FromCy>
extern __imp_VarI1FromStr:PANYARGS
VarI1FromStr TEXTEQU <__imp_VarI1FromStr>
extern __imp_VarI1FromDisp:PANYARGS
VarI1FromDisp TEXTEQU <__imp_VarI1FromDisp>
extern __imp_VarI1FromBool:PANYARGS
VarI1FromBool TEXTEQU <__imp_VarI1FromBool>
extern __imp_VarI1FromUI2:PANYARGS
VarI1FromUI2 TEXTEQU <__imp_VarI1FromUI2>
extern __imp_VarI1FromUI4:PANYARGS
VarI1FromUI4 TEXTEQU <__imp_VarI1FromUI4>
extern __imp_VarI1FromDec:PANYARGS
VarI1FromDec TEXTEQU <__imp_VarI1FromDec>
extern __imp_VarUI2FromUI1:PANYARGS
VarUI2FromUI1 TEXTEQU <__imp_VarUI2FromUI1>
extern __imp_VarUI2FromI2:PANYARGS
VarUI2FromI2 TEXTEQU <__imp_VarUI2FromI2>
extern __imp_VarUI2FromI4:PANYARGS
VarUI2FromI4 TEXTEQU <__imp_VarUI2FromI4>
extern __imp_VarUI2FromR4:PANYARGS
VarUI2FromR4 TEXTEQU <__imp_VarUI2FromR4>
extern __imp_VarUI2FromR8:PANYARGS
VarUI2FromR8 TEXTEQU <__imp_VarUI2FromR8>
extern __imp_VarUI2FromDate:PANYARGS
VarUI2FromDate TEXTEQU <__imp_VarUI2FromDate>
extern __imp_VarUI2FromCy:PANYARGS
VarUI2FromCy TEXTEQU <__imp_VarUI2FromCy>
extern __imp_VarUI2FromStr:PANYARGS
VarUI2FromStr TEXTEQU <__imp_VarUI2FromStr>
extern __imp_VarUI2FromDisp:PANYARGS
VarUI2FromDisp TEXTEQU <__imp_VarUI2FromDisp>
extern __imp_VarUI2FromBool:PANYARGS
VarUI2FromBool TEXTEQU <__imp_VarUI2FromBool>
extern __imp_VarUI2FromI1:PANYARGS
VarUI2FromI1 TEXTEQU <__imp_VarUI2FromI1>
extern __imp_VarUI2FromUI4:PANYARGS
VarUI2FromUI4 TEXTEQU <__imp_VarUI2FromUI4>
extern __imp_VarUI2FromDec:PANYARGS
VarUI2FromDec TEXTEQU <__imp_VarUI2FromDec>
extern __imp_VarUI4FromUI1:PANYARGS
VarUI4FromUI1 TEXTEQU <__imp_VarUI4FromUI1>
extern __imp_VarUI4FromI2:PANYARGS
VarUI4FromI2 TEXTEQU <__imp_VarUI4FromI2>
extern __imp_VarUI4FromI4:PANYARGS
VarUI4FromI4 TEXTEQU <__imp_VarUI4FromI4>
extern __imp_VarUI4FromR4:PANYARGS
VarUI4FromR4 TEXTEQU <__imp_VarUI4FromR4>
extern __imp_VarUI4FromR8:PANYARGS
VarUI4FromR8 TEXTEQU <__imp_VarUI4FromR8>
extern __imp_VarUI4FromDate:PANYARGS
VarUI4FromDate TEXTEQU <__imp_VarUI4FromDate>
extern __imp_VarUI4FromCy:PANYARGS
VarUI4FromCy TEXTEQU <__imp_VarUI4FromCy>
extern __imp_VarUI4FromStr:PANYARGS
VarUI4FromStr TEXTEQU <__imp_VarUI4FromStr>
extern __imp_VarUI4FromDisp:PANYARGS
VarUI4FromDisp TEXTEQU <__imp_VarUI4FromDisp>
extern __imp_VarUI4FromBool:PANYARGS
VarUI4FromBool TEXTEQU <__imp_VarUI4FromBool>
extern __imp_VarUI4FromI1:PANYARGS
VarUI4FromI1 TEXTEQU <__imp_VarUI4FromI1>
extern __imp_VarUI4FromUI2:PANYARGS
VarUI4FromUI2 TEXTEQU <__imp_VarUI4FromUI2>
extern __imp_VarUI4FromDec:PANYARGS
VarUI4FromDec TEXTEQU <__imp_VarUI4FromDec>
extern __imp_BSTR_UserSize:PANYARGS
BSTR_UserSize TEXTEQU <__imp_BSTR_UserSize>
extern __imp_BSTR_UserMarshal:PANYARGS
BSTR_UserMarshal TEXTEQU <__imp_BSTR_UserMarshal>
extern __imp_BSTR_UserUnmarshal:PANYARGS
BSTR_UserUnmarshal TEXTEQU <__imp_BSTR_UserUnmarshal>
extern __imp_BSTR_UserFree:PANYARGS
BSTR_UserFree TEXTEQU <__imp_BSTR_UserFree>
extern __imp_VARIANT_UserSize:PANYARGS
VARIANT_UserSize TEXTEQU <__imp_VARIANT_UserSize>
extern __imp_VARIANT_UserMarshal:PANYARGS
VARIANT_UserMarshal TEXTEQU <__imp_VARIANT_UserMarshal>
extern __imp_VARIANT_UserUnmarshal:PANYARGS
VARIANT_UserUnmarshal TEXTEQU <__imp_VARIANT_UserUnmarshal>
extern __imp_VARIANT_UserFree:PANYARGS
VARIANT_UserFree TEXTEQU <__imp_VARIANT_UserFree>
extern __imp_LPSAFEARRAY_UserSize:PANYARGS
LPSAFEARRAY_UserSize TEXTEQU <__imp_LPSAFEARRAY_UserSize>
extern __imp_LPSAFEARRAY_UserMarshal:PANYARGS
LPSAFEARRAY_UserMarshal TEXTEQU <__imp_LPSAFEARRAY_UserMarshal>
extern __imp_LPSAFEARRAY_UserUnmarshal:PANYARGS
LPSAFEARRAY_UserUnmarshal TEXTEQU <__imp_LPSAFEARRAY_UserUnmarshal>
extern __imp_LPSAFEARRAY_UserFree:PANYARGS
LPSAFEARRAY_UserFree TEXTEQU <__imp_LPSAFEARRAY_UserFree>
extern __imp_LPSAFEARRAY_Size:PANYARGS
LPSAFEARRAY_Size TEXTEQU <__imp_LPSAFEARRAY_Size>
extern __imp_LPSAFEARRAY_Marshal:PANYARGS
LPSAFEARRAY_Marshal TEXTEQU <__imp_LPSAFEARRAY_Marshal>
extern __imp_LPSAFEARRAY_Unmarshal:PANYARGS
LPSAFEARRAY_Unmarshal TEXTEQU <__imp_LPSAFEARRAY_Unmarshal>
extern __imp_VarDecCmpR8:PANYARGS
VarDecCmpR8 TEXTEQU <__imp_VarDecCmpR8>
extern __imp_VarCyAdd:PANYARGS
VarCyAdd TEXTEQU <__imp_VarCyAdd>
extern __imp_BSTR_UserUnmarshal64:PANYARGS
BSTR_UserUnmarshal64 TEXTEQU <__imp_BSTR_UserUnmarshal64>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_VarCyMul:PANYARGS
VarCyMul TEXTEQU <__imp_VarCyMul>
extern __imp_VarCyMulI4:PANYARGS
VarCyMulI4 TEXTEQU <__imp_VarCyMulI4>
extern __imp_VarCySub:PANYARGS
VarCySub TEXTEQU <__imp_VarCySub>
extern __imp_VarCyAbs:PANYARGS
VarCyAbs TEXTEQU <__imp_VarCyAbs>
extern __imp_VarCyFix:PANYARGS
VarCyFix TEXTEQU <__imp_VarCyFix>
extern __imp_VarCyInt:PANYARGS
VarCyInt TEXTEQU <__imp_VarCyInt>
extern __imp_VarCyNeg:PANYARGS
VarCyNeg TEXTEQU <__imp_VarCyNeg>
extern __imp_VarCyRound:PANYARGS
VarCyRound TEXTEQU <__imp_VarCyRound>
extern __imp_VarCyCmp:PANYARGS
VarCyCmp TEXTEQU <__imp_VarCyCmp>
extern __imp_VarCyCmpR8:PANYARGS
VarCyCmpR8 TEXTEQU <__imp_VarCyCmpR8>
extern __imp_VarBstrCat:PANYARGS
VarBstrCat TEXTEQU <__imp_VarBstrCat>
extern __imp_VarBstrCmp:PANYARGS
VarBstrCmp TEXTEQU <__imp_VarBstrCmp>
extern __imp_VarR8Pow:PANYARGS
VarR8Pow TEXTEQU <__imp_VarR8Pow>
extern __imp_VarR4CmpR8:PANYARGS
VarR4CmpR8 TEXTEQU <__imp_VarR4CmpR8>
extern __imp_VarR8Round:PANYARGS
VarR8Round TEXTEQU <__imp_VarR8Round>
extern __imp_VarCat:PANYARGS
VarCat TEXTEQU <__imp_VarCat>
extern __imp_VarDateFromUdateEx:PANYARGS
VarDateFromUdateEx TEXTEQU <__imp_VarDateFromUdateEx>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetRecordInfoFromGuids:PANYARGS
GetRecordInfoFromGuids TEXTEQU <__imp_GetRecordInfoFromGuids>
extern __imp_GetRecordInfoFromTypeInfo:PANYARGS
GetRecordInfoFromTypeInfo TEXTEQU <__imp_GetRecordInfoFromTypeInfo>
extern __imp_LPSAFEARRAY_UserFree64:PANYARGS
LPSAFEARRAY_UserFree64 TEXTEQU <__imp_LPSAFEARRAY_UserFree64>
extern __imp_SetVarConversionLocaleSetting:PANYARGS
SetVarConversionLocaleSetting TEXTEQU <__imp_SetVarConversionLocaleSetting>
extern __imp_GetVarConversionLocaleSetting:PANYARGS
GetVarConversionLocaleSetting TEXTEQU <__imp_GetVarConversionLocaleSetting>
extern __imp_SetOaNoCache:PANYARGS
SetOaNoCache TEXTEQU <__imp_SetOaNoCache>
extern __imp_LPSAFEARRAY_UserMarshal64:PANYARGS
LPSAFEARRAY_UserMarshal64 TEXTEQU <__imp_LPSAFEARRAY_UserMarshal64>
extern __imp_VarCyMulI8:PANYARGS
VarCyMulI8 TEXTEQU <__imp_VarCyMulI8>
extern __imp_VarDateFromUdate:PANYARGS
VarDateFromUdate TEXTEQU <__imp_VarDateFromUdate>
extern __imp_VarUdateFromDate:PANYARGS
VarUdateFromDate TEXTEQU <__imp_VarUdateFromDate>
extern __imp_GetAltMonthNames:PANYARGS
GetAltMonthNames TEXTEQU <__imp_GetAltMonthNames>
extern __imp_VarI8FromUI1:PANYARGS
VarI8FromUI1 TEXTEQU <__imp_VarI8FromUI1>
extern __imp_VarI8FromI2:PANYARGS
VarI8FromI2 TEXTEQU <__imp_VarI8FromI2>
extern __imp_VarI8FromR4:PANYARGS
VarI8FromR4 TEXTEQU <__imp_VarI8FromR4>
extern __imp_VarI8FromR8:PANYARGS
VarI8FromR8 TEXTEQU <__imp_VarI8FromR8>
extern __imp_VarI8FromCy:PANYARGS
VarI8FromCy TEXTEQU <__imp_VarI8FromCy>
extern __imp_VarI8FromDate:PANYARGS
VarI8FromDate TEXTEQU <__imp_VarI8FromDate>
extern __imp_VarI8FromStr:PANYARGS
VarI8FromStr TEXTEQU <__imp_VarI8FromStr>
extern __imp_VarI8FromDisp:PANYARGS
VarI8FromDisp TEXTEQU <__imp_VarI8FromDisp>
extern __imp_VarI8FromBool:PANYARGS
VarI8FromBool TEXTEQU <__imp_VarI8FromBool>
extern __imp_VarI8FromI1:PANYARGS
VarI8FromI1 TEXTEQU <__imp_VarI8FromI1>
extern __imp_VarI8FromUI2:PANYARGS
VarI8FromUI2 TEXTEQU <__imp_VarI8FromUI2>
extern __imp_VarI8FromUI4:PANYARGS
VarI8FromUI4 TEXTEQU <__imp_VarI8FromUI4>
extern __imp_VarI8FromDec:PANYARGS
VarI8FromDec TEXTEQU <__imp_VarI8FromDec>
extern __imp_VarI2FromI8:PANYARGS
VarI2FromI8 TEXTEQU <__imp_VarI2FromI8>
extern __imp_VarI2FromUI8:PANYARGS
VarI2FromUI8 TEXTEQU <__imp_VarI2FromUI8>
extern __imp_VarI4FromI8:PANYARGS
VarI4FromI8 TEXTEQU <__imp_VarI4FromI8>
extern __imp_VarI4FromUI8:PANYARGS
VarI4FromUI8 TEXTEQU <__imp_VarI4FromUI8>
extern __imp_LPSAFEARRAY_UserSize64:PANYARGS
LPSAFEARRAY_UserSize64 TEXTEQU <__imp_LPSAFEARRAY_UserSize64>
extern __imp_LPSAFEARRAY_UserUnmarshal64:PANYARGS
LPSAFEARRAY_UserUnmarshal64 TEXTEQU <__imp_LPSAFEARRAY_UserUnmarshal64>
extern __imp_OACreateTypeLib2:PANYARGS
OACreateTypeLib2 TEXTEQU <__imp_OACreateTypeLib2>
extern __imp_VARIANT_UserFree64:PANYARGS
VARIANT_UserFree64 TEXTEQU <__imp_VARIANT_UserFree64>
extern __imp_VARIANT_UserMarshal64:PANYARGS
VARIANT_UserMarshal64 TEXTEQU <__imp_VARIANT_UserMarshal64>
extern __imp_VARIANT_UserSize64:PANYARGS
VARIANT_UserSize64 TEXTEQU <__imp_VARIANT_UserSize64>
extern __imp_VARIANT_UserUnmarshal64:PANYARGS
VARIANT_UserUnmarshal64 TEXTEQU <__imp_VARIANT_UserUnmarshal64>
extern __imp_oleaut32_ordinal357:PANYARGS
oleaut32_ordinal357 TEXTEQU <__imp_oleaut32_ordinal357>
extern __imp_oleaut32_ordinal358:PANYARGS
oleaut32_ordinal358 TEXTEQU <__imp_oleaut32_ordinal358>
extern __imp_oleaut32_ordinal359:PANYARGS
oleaut32_ordinal359 TEXTEQU <__imp_oleaut32_ordinal359>
extern __imp_VarR4FromI8:PANYARGS
VarR4FromI8 TEXTEQU <__imp_VarR4FromI8>
extern __imp_VarR4FromUI8:PANYARGS
VarR4FromUI8 TEXTEQU <__imp_VarR4FromUI8>
extern __imp_VarR8FromI8:PANYARGS
VarR8FromI8 TEXTEQU <__imp_VarR8FromI8>
extern __imp_VarR8FromUI8:PANYARGS
VarR8FromUI8 TEXTEQU <__imp_VarR8FromUI8>
extern __imp_VarDateFromI8:PANYARGS
VarDateFromI8 TEXTEQU <__imp_VarDateFromI8>
extern __imp_VarDateFromUI8:PANYARGS
VarDateFromUI8 TEXTEQU <__imp_VarDateFromUI8>
extern __imp_VarCyFromI8:PANYARGS
VarCyFromI8 TEXTEQU <__imp_VarCyFromI8>
extern __imp_VarCyFromUI8:PANYARGS
VarCyFromUI8 TEXTEQU <__imp_VarCyFromUI8>
extern __imp_VarBstrFromI8:PANYARGS
VarBstrFromI8 TEXTEQU <__imp_VarBstrFromI8>
extern __imp_VarBstrFromUI8:PANYARGS
VarBstrFromUI8 TEXTEQU <__imp_VarBstrFromUI8>
extern __imp_VarBoolFromI8:PANYARGS
VarBoolFromI8 TEXTEQU <__imp_VarBoolFromI8>
extern __imp_VarBoolFromUI8:PANYARGS
VarBoolFromUI8 TEXTEQU <__imp_VarBoolFromUI8>
extern __imp_VarUI1FromI8:PANYARGS
VarUI1FromI8 TEXTEQU <__imp_VarUI1FromI8>
extern __imp_VarUI1FromUI8:PANYARGS
VarUI1FromUI8 TEXTEQU <__imp_VarUI1FromUI8>
extern __imp_VarDecFromI8:PANYARGS
VarDecFromI8 TEXTEQU <__imp_VarDecFromI8>
extern __imp_VarDecFromUI8:PANYARGS
VarDecFromUI8 TEXTEQU <__imp_VarDecFromUI8>
extern __imp_VarI1FromI8:PANYARGS
VarI1FromI8 TEXTEQU <__imp_VarI1FromI8>
extern __imp_VarI1FromUI8:PANYARGS
VarI1FromUI8 TEXTEQU <__imp_VarI1FromUI8>
extern __imp_VarUI2FromI8:PANYARGS
VarUI2FromI8 TEXTEQU <__imp_VarUI2FromI8>
extern __imp_VarUI2FromUI8:PANYARGS
VarUI2FromUI8 TEXTEQU <__imp_VarUI2FromUI8>
extern __imp_oleaut32_ordinal380:PANYARGS
oleaut32_ordinal380 TEXTEQU <__imp_oleaut32_ordinal380>
extern __imp_oleaut32_ordinal381:PANYARGS
oleaut32_ordinal381 TEXTEQU <__imp_oleaut32_ordinal381>
extern __imp_oleaut32_ordinal382:PANYARGS
oleaut32_ordinal382 TEXTEQU <__imp_oleaut32_ordinal382>
extern __imp_oleaut32_ordinal383:PANYARGS
oleaut32_ordinal383 TEXTEQU <__imp_oleaut32_ordinal383>
extern __imp_oleaut32_ordinal384:PANYARGS
oleaut32_ordinal384 TEXTEQU <__imp_oleaut32_ordinal384>
extern __imp_oleaut32_ordinal385:PANYARGS
oleaut32_ordinal385 TEXTEQU <__imp_oleaut32_ordinal385>
extern __imp_oleaut32_ordinal386:PANYARGS
oleaut32_ordinal386 TEXTEQU <__imp_oleaut32_ordinal386>
extern __imp_oleaut32_ordinal387:PANYARGS
oleaut32_ordinal387 TEXTEQU <__imp_oleaut32_ordinal387>
extern __imp_oleaut32_ordinal388:PANYARGS
oleaut32_ordinal388 TEXTEQU <__imp_oleaut32_ordinal388>
extern __imp_oleaut32_ordinal389:PANYARGS
oleaut32_ordinal389 TEXTEQU <__imp_oleaut32_ordinal389>
extern __imp_oleaut32_ordinal390:PANYARGS
oleaut32_ordinal390 TEXTEQU <__imp_oleaut32_ordinal390>
extern __imp_oleaut32_ordinal391:PANYARGS
oleaut32_ordinal391 TEXTEQU <__imp_oleaut32_ordinal391>
extern __imp_oleaut32_ordinal392:PANYARGS
oleaut32_ordinal392 TEXTEQU <__imp_oleaut32_ordinal392>
extern __imp_oleaut32_ordinal393:PANYARGS
oleaut32_ordinal393 TEXTEQU <__imp_oleaut32_ordinal393>
extern __imp_oleaut32_ordinal394:PANYARGS
oleaut32_ordinal394 TEXTEQU <__imp_oleaut32_ordinal394>
extern __imp_oleaut32_ordinal395:PANYARGS
oleaut32_ordinal395 TEXTEQU <__imp_oleaut32_ordinal395>
extern __imp_oleaut32_ordinal396:PANYARGS
oleaut32_ordinal396 TEXTEQU <__imp_oleaut32_ordinal396>
extern __imp_oleaut32_ordinal397:PANYARGS
oleaut32_ordinal397 TEXTEQU <__imp_oleaut32_ordinal397>
extern __imp_oleaut32_ordinal398:PANYARGS
oleaut32_ordinal398 TEXTEQU <__imp_oleaut32_ordinal398>
extern __imp_oleaut32_ordinal399:PANYARGS
oleaut32_ordinal399 TEXTEQU <__imp_oleaut32_ordinal399>
extern __imp_oleaut32_ordinal400:PANYARGS
oleaut32_ordinal400 TEXTEQU <__imp_oleaut32_ordinal400>
extern __imp_OleLoadPictureEx:PANYARGS
OleLoadPictureEx TEXTEQU <__imp_OleLoadPictureEx>
extern __imp_OleLoadPictureFileEx:PANYARGS
OleLoadPictureFileEx TEXTEQU <__imp_OleLoadPictureFileEx>
extern __imp_oleaut32_ordinal403:PANYARGS
oleaut32_ordinal403 TEXTEQU <__imp_oleaut32_ordinal403>
extern __imp_oleaut32_ordinal404:PANYARGS
oleaut32_ordinal404 TEXTEQU <__imp_oleaut32_ordinal404>
extern __imp_oleaut32_ordinal405:PANYARGS
oleaut32_ordinal405 TEXTEQU <__imp_oleaut32_ordinal405>
extern __imp_oleaut32_ordinal406:PANYARGS
oleaut32_ordinal406 TEXTEQU <__imp_oleaut32_ordinal406>
extern __imp_oleaut32_ordinal407:PANYARGS
oleaut32_ordinal407 TEXTEQU <__imp_oleaut32_ordinal407>
extern __imp_oleaut32_ordinal408:PANYARGS
oleaut32_ordinal408 TEXTEQU <__imp_oleaut32_ordinal408>
extern __imp_oleaut32_ordinal409:PANYARGS
oleaut32_ordinal409 TEXTEQU <__imp_oleaut32_ordinal409>
extern __imp_oleaut32_ordinal410:PANYARGS
oleaut32_ordinal410 TEXTEQU <__imp_oleaut32_ordinal410>
extern __imp_SafeArrayCreateVector:PANYARGS
SafeArrayCreateVector TEXTEQU <__imp_SafeArrayCreateVector>
extern __imp_SafeArrayCopyData:PANYARGS
SafeArrayCopyData TEXTEQU <__imp_SafeArrayCopyData>
extern __imp_VectorFromBstr:PANYARGS
VectorFromBstr TEXTEQU <__imp_VectorFromBstr>
extern __imp_BstrFromVector:PANYARGS
BstrFromVector TEXTEQU <__imp_BstrFromVector>
extern __imp_OleIconToCursor:PANYARGS
OleIconToCursor TEXTEQU <__imp_OleIconToCursor>
extern __imp_OleCreatePropertyFrameIndirect:PANYARGS
OleCreatePropertyFrameIndirect TEXTEQU <__imp_OleCreatePropertyFrameIndirect>
extern __imp_OleCreatePropertyFrame:PANYARGS
OleCreatePropertyFrame TEXTEQU <__imp_OleCreatePropertyFrame>
extern __imp_OleLoadPicture:PANYARGS
OleLoadPicture TEXTEQU <__imp_OleLoadPicture>
extern __imp_OleCreatePictureIndirect:PANYARGS
OleCreatePictureIndirect TEXTEQU <__imp_OleCreatePictureIndirect>
extern __imp_OleCreateFontIndirect:PANYARGS
OleCreateFontIndirect TEXTEQU <__imp_OleCreateFontIndirect>
extern __imp_OleTranslateColor:PANYARGS
OleTranslateColor TEXTEQU <__imp_OleTranslateColor>
extern __imp_OleLoadPictureFile:PANYARGS
OleLoadPictureFile TEXTEQU <__imp_OleLoadPictureFile>
extern __imp_OleSavePictureFile:PANYARGS
OleSavePictureFile TEXTEQU <__imp_OleSavePictureFile>
extern __imp_OleLoadPicturePath:PANYARGS
OleLoadPicturePath TEXTEQU <__imp_OleLoadPicturePath>
extern __imp_VarUI4FromI8:PANYARGS
VarUI4FromI8 TEXTEQU <__imp_VarUI4FromI8>
extern __imp_VarUI4FromUI8:PANYARGS
VarUI4FromUI8 TEXTEQU <__imp_VarUI4FromUI8>
extern __imp_VarI8FromUI8:PANYARGS
VarI8FromUI8 TEXTEQU <__imp_VarI8FromUI8>
extern __imp_VarUI8FromI8:PANYARGS
VarUI8FromI8 TEXTEQU <__imp_VarUI8FromI8>
extern __imp_VarUI8FromUI1:PANYARGS
VarUI8FromUI1 TEXTEQU <__imp_VarUI8FromUI1>
extern __imp_VarUI8FromI2:PANYARGS
VarUI8FromI2 TEXTEQU <__imp_VarUI8FromI2>
extern __imp_VarUI8FromR4:PANYARGS
VarUI8FromR4 TEXTEQU <__imp_VarUI8FromR4>
extern __imp_VarUI8FromR8:PANYARGS
VarUI8FromR8 TEXTEQU <__imp_VarUI8FromR8>
extern __imp_VarUI8FromCy:PANYARGS
VarUI8FromCy TEXTEQU <__imp_VarUI8FromCy>
extern __imp_VarUI8FromDate:PANYARGS
VarUI8FromDate TEXTEQU <__imp_VarUI8FromDate>
extern __imp_VarUI8FromStr:PANYARGS
VarUI8FromStr TEXTEQU <__imp_VarUI8FromStr>
extern __imp_VarUI8FromDisp:PANYARGS
VarUI8FromDisp TEXTEQU <__imp_VarUI8FromDisp>
extern __imp_VarUI8FromBool:PANYARGS
VarUI8FromBool TEXTEQU <__imp_VarUI8FromBool>
extern __imp_VarUI8FromI1:PANYARGS
VarUI8FromI1 TEXTEQU <__imp_VarUI8FromI1>
extern __imp_VarUI8FromUI2:PANYARGS
VarUI8FromUI2 TEXTEQU <__imp_VarUI8FromUI2>
extern __imp_VarUI8FromUI4:PANYARGS
VarUI8FromUI4 TEXTEQU <__imp_VarUI8FromUI4>
extern __imp_VarUI8FromDec:PANYARGS
VarUI8FromDec TEXTEQU <__imp_VarUI8FromDec>
extern __imp_RegisterTypeLibForUser:PANYARGS
RegisterTypeLibForUser TEXTEQU <__imp_RegisterTypeLibForUser>
extern __imp_UnRegisterTypeLibForUser:PANYARGS
UnRegisterTypeLibForUser TEXTEQU <__imp_UnRegisterTypeLibForUser>
