extern __imp_WEP:PANYARGS
WEP TEXTEQU <__imp_WEP>
extern __imp_OleDelete:PANYARGS
OleDelete TEXTEQU <__imp_OleDelete>
extern __imp_OleSaveToStream:PANYARGS
OleSaveToStream TEXTEQU <__imp_OleSaveToStream>
extern __imp_OleLoadFromStream:PANYARGS
OleLoadFromStream TEXTEQU <__imp_OleLoadFromStream>
extern __imp_olecli32_ordinal5:PANYARGS
olecli32_ordinal5 TEXTEQU <__imp_olecli32_ordinal5>
extern __imp_OleClone:PANYARGS
OleClone TEXTEQU <__imp_OleClone>
extern __imp_OleCopyFromLink:PANYARGS
OleCopyFromLink TEXTEQU <__imp_OleCopyFromLink>
extern __imp_OleEqual:PANYARGS
OleEqual TEXTEQU <__imp_OleEqual>
extern __imp_OleQueryLinkFromClip:PANYARGS
OleQueryLinkFromClip TEXTEQU <__imp_OleQueryLinkFromClip>
extern __imp_OleQueryCreateFromClip:PANYARGS
OleQueryCreateFromClip TEXTEQU <__imp_OleQueryCreateFromClip>
extern __imp_OleCreateLinkFromClip:PANYARGS
OleCreateLinkFromClip TEXTEQU <__imp_OleCreateLinkFromClip>
extern __imp_OleCreateFromClip:PANYARGS
OleCreateFromClip TEXTEQU <__imp_OleCreateFromClip>
extern __imp_OleCopyToClipboard:PANYARGS
OleCopyToClipboard TEXTEQU <__imp_OleCopyToClipboard>
extern __imp_OleQueryType:PANYARGS
OleQueryType TEXTEQU <__imp_OleQueryType>
extern __imp_OleSetHostNames:PANYARGS
OleSetHostNames TEXTEQU <__imp_OleSetHostNames>
extern __imp_OleSetTargetDevice:PANYARGS
OleSetTargetDevice TEXTEQU <__imp_OleSetTargetDevice>
extern __imp_OleSetBounds:PANYARGS
OleSetBounds TEXTEQU <__imp_OleSetBounds>
extern __imp_OleQueryBounds:PANYARGS
OleQueryBounds TEXTEQU <__imp_OleQueryBounds>
extern __imp_OleDraw:PANYARGS
OleDraw TEXTEQU <__imp_OleDraw>
extern __imp_OleQueryOpen:PANYARGS
OleQueryOpen TEXTEQU <__imp_OleQueryOpen>
extern __imp_OleActivate:PANYARGS
OleActivate TEXTEQU <__imp_OleActivate>
extern __imp_OleUpdate:PANYARGS
OleUpdate TEXTEQU <__imp_OleUpdate>
extern __imp_OleReconnect:PANYARGS
OleReconnect TEXTEQU <__imp_OleReconnect>
extern __imp_OleGetLinkUpdateOptions:PANYARGS
OleGetLinkUpdateOptions TEXTEQU <__imp_OleGetLinkUpdateOptions>
extern __imp_OleSetLinkUpdateOptions:PANYARGS
OleSetLinkUpdateOptions TEXTEQU <__imp_OleSetLinkUpdateOptions>
extern __imp_OleEnumFormats:PANYARGS
OleEnumFormats TEXTEQU <__imp_OleEnumFormats>
extern __imp_OleClose:PANYARGS
OleClose TEXTEQU <__imp_OleClose>
extern __imp_OleGetData:PANYARGS
OleGetData TEXTEQU <__imp_OleGetData>
extern __imp_OleSetData:PANYARGS
OleSetData TEXTEQU <__imp_OleSetData>
extern __imp_OleQueryProtocol:PANYARGS
OleQueryProtocol TEXTEQU <__imp_OleQueryProtocol>
extern __imp_OleQueryOutOfDate:PANYARGS
OleQueryOutOfDate TEXTEQU <__imp_OleQueryOutOfDate>
extern __imp_OleObjectConvert:PANYARGS
OleObjectConvert TEXTEQU <__imp_OleObjectConvert>
extern __imp_OleCreateFromTemplate:PANYARGS
OleCreateFromTemplate TEXTEQU <__imp_OleCreateFromTemplate>
extern __imp_OleCreate:PANYARGS
OleCreate TEXTEQU <__imp_OleCreate>
extern __imp_OleQueryReleaseStatus:PANYARGS
OleQueryReleaseStatus TEXTEQU <__imp_OleQueryReleaseStatus>
extern __imp_OleQueryReleaseError:PANYARGS
OleQueryReleaseError TEXTEQU <__imp_OleQueryReleaseError>
extern __imp_OleQueryReleaseMethod:PANYARGS
OleQueryReleaseMethod TEXTEQU <__imp_OleQueryReleaseMethod>
extern __imp_OleCreateFromFile:PANYARGS
OleCreateFromFile TEXTEQU <__imp_OleCreateFromFile>
extern __imp_OleCreateLinkFromFile:PANYARGS
OleCreateLinkFromFile TEXTEQU <__imp_OleCreateLinkFromFile>
extern __imp_OleRelease:PANYARGS
OleRelease TEXTEQU <__imp_OleRelease>
extern __imp_OleRegisterClientDoc:PANYARGS
OleRegisterClientDoc TEXTEQU <__imp_OleRegisterClientDoc>
extern __imp_OleRevokeClientDoc:PANYARGS
OleRevokeClientDoc TEXTEQU <__imp_OleRevokeClientDoc>
extern __imp_OleRenameClientDoc:PANYARGS
OleRenameClientDoc TEXTEQU <__imp_OleRenameClientDoc>
extern __imp_OleRevertClientDoc:PANYARGS
OleRevertClientDoc TEXTEQU <__imp_OleRevertClientDoc>
extern __imp_OleSavedClientDoc:PANYARGS
OleSavedClientDoc TEXTEQU <__imp_OleSavedClientDoc>
extern __imp_OleRename:PANYARGS
OleRename TEXTEQU <__imp_OleRename>
extern __imp_OleEnumObjects:PANYARGS
OleEnumObjects TEXTEQU <__imp_OleEnumObjects>
extern __imp_OleQueryName:PANYARGS
OleQueryName TEXTEQU <__imp_OleQueryName>
extern __imp_OleSetColorScheme:PANYARGS
OleSetColorScheme TEXTEQU <__imp_OleSetColorScheme>
extern __imp_OleRequestData:PANYARGS
OleRequestData TEXTEQU <__imp_OleRequestData>
extern __imp_olecli32_ordinal51:PANYARGS
olecli32_ordinal51 TEXTEQU <__imp_olecli32_ordinal51>
extern __imp_olecli32_ordinal52:PANYARGS
olecli32_ordinal52 TEXTEQU <__imp_olecli32_ordinal52>
extern __imp_olecli32_ordinal53:PANYARGS
olecli32_ordinal53 TEXTEQU <__imp_olecli32_ordinal53>
extern __imp_OleLockServer:PANYARGS
OleLockServer TEXTEQU <__imp_OleLockServer>
extern __imp_OleUnlockServer:PANYARGS
OleUnlockServer TEXTEQU <__imp_OleUnlockServer>
extern __imp_OleQuerySize:PANYARGS
OleQuerySize TEXTEQU <__imp_OleQuerySize>
extern __imp_OleExecute:PANYARGS
OleExecute TEXTEQU <__imp_OleExecute>
extern __imp_OleCreateInvisible:PANYARGS
OleCreateInvisible TEXTEQU <__imp_OleCreateInvisible>
extern __imp_OleQueryClientVersion:PANYARGS
OleQueryClientVersion TEXTEQU <__imp_OleQueryClientVersion>
extern __imp_OleIsDcMeta:PANYARGS
OleIsDcMeta TEXTEQU <__imp_OleIsDcMeta>
extern __imp_olecli32_ordinal61:PANYARGS
olecli32_ordinal61 TEXTEQU <__imp_olecli32_ordinal61>
extern __imp_olecli32_ordinal62:PANYARGS
olecli32_ordinal62 TEXTEQU <__imp_olecli32_ordinal62>
extern __imp_olecli32_ordinal63:PANYARGS
olecli32_ordinal63 TEXTEQU <__imp_olecli32_ordinal63>
extern __imp_olecli32_ordinal64:PANYARGS
olecli32_ordinal64 TEXTEQU <__imp_olecli32_ordinal64>
extern __imp_olecli32_ordinal65:PANYARGS
olecli32_ordinal65 TEXTEQU <__imp_olecli32_ordinal65>
extern __imp_olecli32_ordinal66:PANYARGS
olecli32_ordinal66 TEXTEQU <__imp_olecli32_ordinal66>
extern __imp_olecli32_ordinal67:PANYARGS
olecli32_ordinal67 TEXTEQU <__imp_olecli32_ordinal67>
extern __imp_olecli32_ordinal68:PANYARGS
olecli32_ordinal68 TEXTEQU <__imp_olecli32_ordinal68>
extern __imp_olecli32_ordinal69:PANYARGS
olecli32_ordinal69 TEXTEQU <__imp_olecli32_ordinal69>
extern __imp_olecli32_ordinal70:PANYARGS
olecli32_ordinal70 TEXTEQU <__imp_olecli32_ordinal70>
extern __imp_olecli32_ordinal71:PANYARGS
olecli32_ordinal71 TEXTEQU <__imp_olecli32_ordinal71>
extern __imp_olecli32_ordinal72:PANYARGS
olecli32_ordinal72 TEXTEQU <__imp_olecli32_ordinal72>
extern __imp_olecli32_ordinal73:PANYARGS
olecli32_ordinal73 TEXTEQU <__imp_olecli32_ordinal73>
extern __imp_olecli32_ordinal74:PANYARGS
olecli32_ordinal74 TEXTEQU <__imp_olecli32_ordinal74>
extern __imp_olecli32_ordinal75:PANYARGS
olecli32_ordinal75 TEXTEQU <__imp_olecli32_ordinal75>
extern __imp_olecli32_ordinal76:PANYARGS
olecli32_ordinal76 TEXTEQU <__imp_olecli32_ordinal76>
extern __imp_olecli32_ordinal77:PANYARGS
olecli32_ordinal77 TEXTEQU <__imp_olecli32_ordinal77>
extern __imp_olecli32_ordinal78:PANYARGS
olecli32_ordinal78 TEXTEQU <__imp_olecli32_ordinal78>
extern __imp_olecli32_ordinal79:PANYARGS
olecli32_ordinal79 TEXTEQU <__imp_olecli32_ordinal79>
extern __imp_olecli32_ordinal80:PANYARGS
olecli32_ordinal80 TEXTEQU <__imp_olecli32_ordinal80>
extern __imp_olecli32_ordinal81:PANYARGS
olecli32_ordinal81 TEXTEQU <__imp_olecli32_ordinal81>
extern __imp_olecli32_ordinal82:PANYARGS
olecli32_ordinal82 TEXTEQU <__imp_olecli32_ordinal82>
extern __imp_olecli32_ordinal83:PANYARGS
olecli32_ordinal83 TEXTEQU <__imp_olecli32_ordinal83>
extern __imp_olecli32_ordinal84:PANYARGS
olecli32_ordinal84 TEXTEQU <__imp_olecli32_ordinal84>
extern __imp_olecli32_ordinal85:PANYARGS
olecli32_ordinal85 TEXTEQU <__imp_olecli32_ordinal85>
extern __imp_olecli32_ordinal86:PANYARGS
olecli32_ordinal86 TEXTEQU <__imp_olecli32_ordinal86>
extern __imp_olecli32_ordinal87:PANYARGS
olecli32_ordinal87 TEXTEQU <__imp_olecli32_ordinal87>
extern __imp_olecli32_ordinal88:PANYARGS
olecli32_ordinal88 TEXTEQU <__imp_olecli32_ordinal88>
extern __imp_olecli32_ordinal89:PANYARGS
olecli32_ordinal89 TEXTEQU <__imp_olecli32_ordinal89>
extern __imp_olecli32_ordinal90:PANYARGS
olecli32_ordinal90 TEXTEQU <__imp_olecli32_ordinal90>
extern __imp_olecli32_ordinal91:PANYARGS
olecli32_ordinal91 TEXTEQU <__imp_olecli32_ordinal91>
extern __imp_olecli32_ordinal92:PANYARGS
olecli32_ordinal92 TEXTEQU <__imp_olecli32_ordinal92>
extern __imp_olecli32_ordinal93:PANYARGS
olecli32_ordinal93 TEXTEQU <__imp_olecli32_ordinal93>
extern __imp_olecli32_ordinal94:PANYARGS
olecli32_ordinal94 TEXTEQU <__imp_olecli32_ordinal94>
extern __imp_olecli32_ordinal95:PANYARGS
olecli32_ordinal95 TEXTEQU <__imp_olecli32_ordinal95>
extern __imp_olecli32_ordinal96:PANYARGS
olecli32_ordinal96 TEXTEQU <__imp_olecli32_ordinal96>
extern __imp_olecli32_ordinal97:PANYARGS
olecli32_ordinal97 TEXTEQU <__imp_olecli32_ordinal97>
extern __imp_olecli32_ordinal98:PANYARGS
olecli32_ordinal98 TEXTEQU <__imp_olecli32_ordinal98>
extern __imp_olecli32_ordinal99:PANYARGS
olecli32_ordinal99 TEXTEQU <__imp_olecli32_ordinal99>
extern __imp_DocWndProc:PANYARGS
DocWndProc TEXTEQU <__imp_DocWndProc>
extern __imp_SrvrWndProc:PANYARGS
SrvrWndProc TEXTEQU <__imp_SrvrWndProc>
extern __imp_MfCallbackFunc:PANYARGS
MfCallbackFunc TEXTEQU <__imp_MfCallbackFunc>
extern __imp_olecli32_ordinal103:PANYARGS
olecli32_ordinal103 TEXTEQU <__imp_olecli32_ordinal103>
extern __imp_olecli32_ordinal104:PANYARGS
olecli32_ordinal104 TEXTEQU <__imp_olecli32_ordinal104>
extern __imp_olecli32_ordinal105:PANYARGS
olecli32_ordinal105 TEXTEQU <__imp_olecli32_ordinal105>
extern __imp_olecli32_ordinal106:PANYARGS
olecli32_ordinal106 TEXTEQU <__imp_olecli32_ordinal106>
extern __imp_olecli32_ordinal107:PANYARGS
olecli32_ordinal107 TEXTEQU <__imp_olecli32_ordinal107>
extern __imp_olecli32_ordinal108:PANYARGS
olecli32_ordinal108 TEXTEQU <__imp_olecli32_ordinal108>
extern __imp_olecli32_ordinal109:PANYARGS
olecli32_ordinal109 TEXTEQU <__imp_olecli32_ordinal109>
extern __imp_DefLoadFromStream:PANYARGS
DefLoadFromStream TEXTEQU <__imp_DefLoadFromStream>
extern __imp_DefCreateFromClip:PANYARGS
DefCreateFromClip TEXTEQU <__imp_DefCreateFromClip>
extern __imp_DefCreateLinkFromClip:PANYARGS
DefCreateLinkFromClip TEXTEQU <__imp_DefCreateLinkFromClip>
extern __imp_DefCreateFromTemplate:PANYARGS
DefCreateFromTemplate TEXTEQU <__imp_DefCreateFromTemplate>
extern __imp_DefCreate:PANYARGS
DefCreate TEXTEQU <__imp_DefCreate>
extern __imp_DefCreateFromFile:PANYARGS
DefCreateFromFile TEXTEQU <__imp_DefCreateFromFile>
extern __imp_DefCreateLinkFromFile:PANYARGS
DefCreateLinkFromFile TEXTEQU <__imp_DefCreateLinkFromFile>
extern __imp_DefCreateInvisible:PANYARGS
DefCreateInvisible TEXTEQU <__imp_DefCreateInvisible>
extern __imp_olecli32_ordinal118:PANYARGS
olecli32_ordinal118 TEXTEQU <__imp_olecli32_ordinal118>
extern __imp_olecli32_ordinal119:PANYARGS
olecli32_ordinal119 TEXTEQU <__imp_olecli32_ordinal119>
extern __imp_olecli32_ordinal120:PANYARGS
olecli32_ordinal120 TEXTEQU <__imp_olecli32_ordinal120>
extern __imp_olecli32_ordinal121:PANYARGS
olecli32_ordinal121 TEXTEQU <__imp_olecli32_ordinal121>
extern __imp_olecli32_ordinal122:PANYARGS
olecli32_ordinal122 TEXTEQU <__imp_olecli32_ordinal122>
extern __imp_olecli32_ordinal123:PANYARGS
olecli32_ordinal123 TEXTEQU <__imp_olecli32_ordinal123>
extern __imp_olecli32_ordinal124:PANYARGS
olecli32_ordinal124 TEXTEQU <__imp_olecli32_ordinal124>
extern __imp_olecli32_ordinal125:PANYARGS
olecli32_ordinal125 TEXTEQU <__imp_olecli32_ordinal125>
extern __imp_olecli32_ordinal126:PANYARGS
olecli32_ordinal126 TEXTEQU <__imp_olecli32_ordinal126>
extern __imp_olecli32_ordinal127:PANYARGS
olecli32_ordinal127 TEXTEQU <__imp_olecli32_ordinal127>
extern __imp_olecli32_ordinal128:PANYARGS
olecli32_ordinal128 TEXTEQU <__imp_olecli32_ordinal128>
extern __imp_olecli32_ordinal129:PANYARGS
olecli32_ordinal129 TEXTEQU <__imp_olecli32_ordinal129>
extern __imp_olecli32_ordinal130:PANYARGS
olecli32_ordinal130 TEXTEQU <__imp_olecli32_ordinal130>
extern __imp_olecli32_ordinal131:PANYARGS
olecli32_ordinal131 TEXTEQU <__imp_olecli32_ordinal131>
extern __imp_olecli32_ordinal132:PANYARGS
olecli32_ordinal132 TEXTEQU <__imp_olecli32_ordinal132>
extern __imp_olecli32_ordinal133:PANYARGS
olecli32_ordinal133 TEXTEQU <__imp_olecli32_ordinal133>
extern __imp_olecli32_ordinal134:PANYARGS
olecli32_ordinal134 TEXTEQU <__imp_olecli32_ordinal134>
extern __imp_olecli32_ordinal135:PANYARGS
olecli32_ordinal135 TEXTEQU <__imp_olecli32_ordinal135>
extern __imp_olecli32_ordinal136:PANYARGS
olecli32_ordinal136 TEXTEQU <__imp_olecli32_ordinal136>
extern __imp_olecli32_ordinal137:PANYARGS
olecli32_ordinal137 TEXTEQU <__imp_olecli32_ordinal137>
extern __imp_olecli32_ordinal138:PANYARGS
olecli32_ordinal138 TEXTEQU <__imp_olecli32_ordinal138>
extern __imp_olecli32_ordinal139:PANYARGS
olecli32_ordinal139 TEXTEQU <__imp_olecli32_ordinal139>
extern __imp_olecli32_ordinal140:PANYARGS
olecli32_ordinal140 TEXTEQU <__imp_olecli32_ordinal140>
extern __imp_olecli32_ordinal141:PANYARGS
olecli32_ordinal141 TEXTEQU <__imp_olecli32_ordinal141>
extern __imp_olecli32_ordinal142:PANYARGS
olecli32_ordinal142 TEXTEQU <__imp_olecli32_ordinal142>
extern __imp_olecli32_ordinal143:PANYARGS
olecli32_ordinal143 TEXTEQU <__imp_olecli32_ordinal143>
extern __imp_olecli32_ordinal144:PANYARGS
olecli32_ordinal144 TEXTEQU <__imp_olecli32_ordinal144>
extern __imp_olecli32_ordinal145:PANYARGS
olecli32_ordinal145 TEXTEQU <__imp_olecli32_ordinal145>
extern __imp_olecli32_ordinal146:PANYARGS
olecli32_ordinal146 TEXTEQU <__imp_olecli32_ordinal146>
extern __imp_olecli32_ordinal147:PANYARGS
olecli32_ordinal147 TEXTEQU <__imp_olecli32_ordinal147>
extern __imp_olecli32_ordinal148:PANYARGS
olecli32_ordinal148 TEXTEQU <__imp_olecli32_ordinal148>
extern __imp_olecli32_ordinal149:PANYARGS
olecli32_ordinal149 TEXTEQU <__imp_olecli32_ordinal149>
extern __imp_olecli32_ordinal150:PANYARGS
olecli32_ordinal150 TEXTEQU <__imp_olecli32_ordinal150>
extern __imp_olecli32_ordinal151:PANYARGS
olecli32_ordinal151 TEXTEQU <__imp_olecli32_ordinal151>
extern __imp_olecli32_ordinal152:PANYARGS
olecli32_ordinal152 TEXTEQU <__imp_olecli32_ordinal152>
extern __imp_olecli32_ordinal153:PANYARGS
olecli32_ordinal153 TEXTEQU <__imp_olecli32_ordinal153>
extern __imp_olecli32_ordinal154:PANYARGS
olecli32_ordinal154 TEXTEQU <__imp_olecli32_ordinal154>
extern __imp_olecli32_ordinal155:PANYARGS
olecli32_ordinal155 TEXTEQU <__imp_olecli32_ordinal155>
extern __imp_olecli32_ordinal156:PANYARGS
olecli32_ordinal156 TEXTEQU <__imp_olecli32_ordinal156>
extern __imp_olecli32_ordinal157:PANYARGS
olecli32_ordinal157 TEXTEQU <__imp_olecli32_ordinal157>
extern __imp_olecli32_ordinal158:PANYARGS
olecli32_ordinal158 TEXTEQU <__imp_olecli32_ordinal158>
extern __imp_olecli32_ordinal159:PANYARGS
olecli32_ordinal159 TEXTEQU <__imp_olecli32_ordinal159>
extern __imp_olecli32_ordinal160:PANYARGS
olecli32_ordinal160 TEXTEQU <__imp_olecli32_ordinal160>
extern __imp_olecli32_ordinal161:PANYARGS
olecli32_ordinal161 TEXTEQU <__imp_olecli32_ordinal161>
extern __imp_olecli32_ordinal162:PANYARGS
olecli32_ordinal162 TEXTEQU <__imp_olecli32_ordinal162>
extern __imp_olecli32_ordinal163:PANYARGS
olecli32_ordinal163 TEXTEQU <__imp_olecli32_ordinal163>
extern __imp_olecli32_ordinal164:PANYARGS
olecli32_ordinal164 TEXTEQU <__imp_olecli32_ordinal164>
extern __imp_olecli32_ordinal165:PANYARGS
olecli32_ordinal165 TEXTEQU <__imp_olecli32_ordinal165>
extern __imp_olecli32_ordinal166:PANYARGS
olecli32_ordinal166 TEXTEQU <__imp_olecli32_ordinal166>
extern __imp_olecli32_ordinal167:PANYARGS
olecli32_ordinal167 TEXTEQU <__imp_olecli32_ordinal167>
extern __imp_olecli32_ordinal168:PANYARGS
olecli32_ordinal168 TEXTEQU <__imp_olecli32_ordinal168>
extern __imp_olecli32_ordinal169:PANYARGS
olecli32_ordinal169 TEXTEQU <__imp_olecli32_ordinal169>
extern __imp_olecli32_ordinal170:PANYARGS
olecli32_ordinal170 TEXTEQU <__imp_olecli32_ordinal170>
extern __imp_olecli32_ordinal171:PANYARGS
olecli32_ordinal171 TEXTEQU <__imp_olecli32_ordinal171>
extern __imp_olecli32_ordinal172:PANYARGS
olecli32_ordinal172 TEXTEQU <__imp_olecli32_ordinal172>
extern __imp_olecli32_ordinal173:PANYARGS
olecli32_ordinal173 TEXTEQU <__imp_olecli32_ordinal173>
extern __imp_olecli32_ordinal174:PANYARGS
olecli32_ordinal174 TEXTEQU <__imp_olecli32_ordinal174>
extern __imp_olecli32_ordinal175:PANYARGS
olecli32_ordinal175 TEXTEQU <__imp_olecli32_ordinal175>
extern __imp_olecli32_ordinal176:PANYARGS
olecli32_ordinal176 TEXTEQU <__imp_olecli32_ordinal176>
extern __imp_olecli32_ordinal177:PANYARGS
olecli32_ordinal177 TEXTEQU <__imp_olecli32_ordinal177>
extern __imp_olecli32_ordinal178:PANYARGS
olecli32_ordinal178 TEXTEQU <__imp_olecli32_ordinal178>
extern __imp_olecli32_ordinal179:PANYARGS
olecli32_ordinal179 TEXTEQU <__imp_olecli32_ordinal179>
extern __imp_olecli32_ordinal180:PANYARGS
olecli32_ordinal180 TEXTEQU <__imp_olecli32_ordinal180>
extern __imp_olecli32_ordinal181:PANYARGS
olecli32_ordinal181 TEXTEQU <__imp_olecli32_ordinal181>
extern __imp_olecli32_ordinal182:PANYARGS
olecli32_ordinal182 TEXTEQU <__imp_olecli32_ordinal182>
extern __imp_olecli32_ordinal183:PANYARGS
olecli32_ordinal183 TEXTEQU <__imp_olecli32_ordinal183>
extern __imp_olecli32_ordinal184:PANYARGS
olecli32_ordinal184 TEXTEQU <__imp_olecli32_ordinal184>
extern __imp_olecli32_ordinal185:PANYARGS
olecli32_ordinal185 TEXTEQU <__imp_olecli32_ordinal185>
extern __imp_olecli32_ordinal186:PANYARGS
olecli32_ordinal186 TEXTEQU <__imp_olecli32_ordinal186>
extern __imp_olecli32_ordinal187:PANYARGS
olecli32_ordinal187 TEXTEQU <__imp_olecli32_ordinal187>
extern __imp_olecli32_ordinal188:PANYARGS
olecli32_ordinal188 TEXTEQU <__imp_olecli32_ordinal188>
extern __imp_olecli32_ordinal189:PANYARGS
olecli32_ordinal189 TEXTEQU <__imp_olecli32_ordinal189>
extern __imp_olecli32_ordinal190:PANYARGS
olecli32_ordinal190 TEXTEQU <__imp_olecli32_ordinal190>
extern __imp_olecli32_ordinal191:PANYARGS
olecli32_ordinal191 TEXTEQU <__imp_olecli32_ordinal191>
extern __imp_olecli32_ordinal192:PANYARGS
olecli32_ordinal192 TEXTEQU <__imp_olecli32_ordinal192>
extern __imp_olecli32_ordinal193:PANYARGS
olecli32_ordinal193 TEXTEQU <__imp_olecli32_ordinal193>
extern __imp_olecli32_ordinal194:PANYARGS
olecli32_ordinal194 TEXTEQU <__imp_olecli32_ordinal194>
extern __imp_olecli32_ordinal195:PANYARGS
olecli32_ordinal195 TEXTEQU <__imp_olecli32_ordinal195>
extern __imp_olecli32_ordinal196:PANYARGS
olecli32_ordinal196 TEXTEQU <__imp_olecli32_ordinal196>
extern __imp_olecli32_ordinal197:PANYARGS
olecli32_ordinal197 TEXTEQU <__imp_olecli32_ordinal197>
extern __imp_olecli32_ordinal198:PANYARGS
olecli32_ordinal198 TEXTEQU <__imp_olecli32_ordinal198>
extern __imp_olecli32_ordinal199:PANYARGS
olecli32_ordinal199 TEXTEQU <__imp_olecli32_ordinal199>
extern __imp_LeRelease:PANYARGS
LeRelease TEXTEQU <__imp_LeRelease>
extern __imp_LeShow:PANYARGS
LeShow TEXTEQU <__imp_LeShow>
extern __imp_LeGetData:PANYARGS
LeGetData TEXTEQU <__imp_LeGetData>
extern __imp_LeSetData:PANYARGS
LeSetData TEXTEQU <__imp_LeSetData>
extern __imp_LeSetHostNames:PANYARGS
LeSetHostNames TEXTEQU <__imp_LeSetHostNames>
extern __imp_LeSetTargetDevice:PANYARGS
LeSetTargetDevice TEXTEQU <__imp_LeSetTargetDevice>
extern __imp_LeSetBounds:PANYARGS
LeSetBounds TEXTEQU <__imp_LeSetBounds>
extern __imp_LeSaveToStream:PANYARGS
LeSaveToStream TEXTEQU <__imp_LeSaveToStream>
extern __imp_LeClone:PANYARGS
LeClone TEXTEQU <__imp_LeClone>
extern __imp_LeCopyFromLink:PANYARGS
LeCopyFromLink TEXTEQU <__imp_LeCopyFromLink>
extern __imp_LeEqual:PANYARGS
LeEqual TEXTEQU <__imp_LeEqual>
extern __imp_LeCopy:PANYARGS
LeCopy TEXTEQU <__imp_LeCopy>
extern __imp_LeQueryType:PANYARGS
LeQueryType TEXTEQU <__imp_LeQueryType>
extern __imp_LeQueryBounds:PANYARGS
LeQueryBounds TEXTEQU <__imp_LeQueryBounds>
extern __imp_LeDraw:PANYARGS
LeDraw TEXTEQU <__imp_LeDraw>
extern __imp_LeQueryOpen:PANYARGS
LeQueryOpen TEXTEQU <__imp_LeQueryOpen>
extern __imp_LeActivate:PANYARGS
LeActivate TEXTEQU <__imp_LeActivate>
extern __imp_olecli32_ordinal217:PANYARGS
olecli32_ordinal217 TEXTEQU <__imp_olecli32_ordinal217>
extern __imp_LeUpdate:PANYARGS
LeUpdate TEXTEQU <__imp_LeUpdate>
extern __imp_LeReconnect:PANYARGS
LeReconnect TEXTEQU <__imp_LeReconnect>
extern __imp_LeEnumFormat:PANYARGS
LeEnumFormat TEXTEQU <__imp_LeEnumFormat>
extern __imp_LeQueryProtocol:PANYARGS
LeQueryProtocol TEXTEQU <__imp_LeQueryProtocol>
extern __imp_LeQueryOutOfDate:PANYARGS
LeQueryOutOfDate TEXTEQU <__imp_LeQueryOutOfDate>
extern __imp_LeObjectConvert:PANYARGS
LeObjectConvert TEXTEQU <__imp_LeObjectConvert>
extern __imp_LeChangeData:PANYARGS
LeChangeData TEXTEQU <__imp_LeChangeData>
extern __imp_LeClose:PANYARGS
LeClose TEXTEQU <__imp_LeClose>
extern __imp_LeGetUpdateOptions:PANYARGS
LeGetUpdateOptions TEXTEQU <__imp_LeGetUpdateOptions>
extern __imp_LeSetUpdateOptions:PANYARGS
LeSetUpdateOptions TEXTEQU <__imp_LeSetUpdateOptions>
extern __imp_LeExecute:PANYARGS
LeExecute TEXTEQU <__imp_LeExecute>
extern __imp_LeObjectLong:PANYARGS
LeObjectLong TEXTEQU <__imp_LeObjectLong>
extern __imp_LeCreateInvisible:PANYARGS
LeCreateInvisible TEXTEQU <__imp_LeCreateInvisible>
extern __imp_olecli32_ordinal231:PANYARGS
olecli32_ordinal231 TEXTEQU <__imp_olecli32_ordinal231>
extern __imp_olecli32_ordinal232:PANYARGS
olecli32_ordinal232 TEXTEQU <__imp_olecli32_ordinal232>
extern __imp_olecli32_ordinal233:PANYARGS
olecli32_ordinal233 TEXTEQU <__imp_olecli32_ordinal233>
extern __imp_olecli32_ordinal234:PANYARGS
olecli32_ordinal234 TEXTEQU <__imp_olecli32_ordinal234>
extern __imp_olecli32_ordinal235:PANYARGS
olecli32_ordinal235 TEXTEQU <__imp_olecli32_ordinal235>
extern __imp_olecli32_ordinal236:PANYARGS
olecli32_ordinal236 TEXTEQU <__imp_olecli32_ordinal236>
extern __imp_olecli32_ordinal237:PANYARGS
olecli32_ordinal237 TEXTEQU <__imp_olecli32_ordinal237>
extern __imp_olecli32_ordinal238:PANYARGS
olecli32_ordinal238 TEXTEQU <__imp_olecli32_ordinal238>
extern __imp_olecli32_ordinal239:PANYARGS
olecli32_ordinal239 TEXTEQU <__imp_olecli32_ordinal239>
extern __imp_olecli32_ordinal240:PANYARGS
olecli32_ordinal240 TEXTEQU <__imp_olecli32_ordinal240>
extern __imp_olecli32_ordinal241:PANYARGS
olecli32_ordinal241 TEXTEQU <__imp_olecli32_ordinal241>
extern __imp_olecli32_ordinal242:PANYARGS
olecli32_ordinal242 TEXTEQU <__imp_olecli32_ordinal242>
extern __imp_olecli32_ordinal243:PANYARGS
olecli32_ordinal243 TEXTEQU <__imp_olecli32_ordinal243>
extern __imp_olecli32_ordinal244:PANYARGS
olecli32_ordinal244 TEXTEQU <__imp_olecli32_ordinal244>
extern __imp_olecli32_ordinal245:PANYARGS
olecli32_ordinal245 TEXTEQU <__imp_olecli32_ordinal245>
extern __imp_olecli32_ordinal246:PANYARGS
olecli32_ordinal246 TEXTEQU <__imp_olecli32_ordinal246>
extern __imp_olecli32_ordinal247:PANYARGS
olecli32_ordinal247 TEXTEQU <__imp_olecli32_ordinal247>
extern __imp_olecli32_ordinal248:PANYARGS
olecli32_ordinal248 TEXTEQU <__imp_olecli32_ordinal248>
extern __imp_olecli32_ordinal249:PANYARGS
olecli32_ordinal249 TEXTEQU <__imp_olecli32_ordinal249>
extern __imp_olecli32_ordinal250:PANYARGS
olecli32_ordinal250 TEXTEQU <__imp_olecli32_ordinal250>
extern __imp_olecli32_ordinal251:PANYARGS
olecli32_ordinal251 TEXTEQU <__imp_olecli32_ordinal251>
extern __imp_olecli32_ordinal252:PANYARGS
olecli32_ordinal252 TEXTEQU <__imp_olecli32_ordinal252>
extern __imp_olecli32_ordinal253:PANYARGS
olecli32_ordinal253 TEXTEQU <__imp_olecli32_ordinal253>
extern __imp_olecli32_ordinal254:PANYARGS
olecli32_ordinal254 TEXTEQU <__imp_olecli32_ordinal254>
extern __imp_olecli32_ordinal255:PANYARGS
olecli32_ordinal255 TEXTEQU <__imp_olecli32_ordinal255>
extern __imp_olecli32_ordinal256:PANYARGS
olecli32_ordinal256 TEXTEQU <__imp_olecli32_ordinal256>
extern __imp_olecli32_ordinal257:PANYARGS
olecli32_ordinal257 TEXTEQU <__imp_olecli32_ordinal257>
extern __imp_olecli32_ordinal258:PANYARGS
olecli32_ordinal258 TEXTEQU <__imp_olecli32_ordinal258>
extern __imp_olecli32_ordinal259:PANYARGS
olecli32_ordinal259 TEXTEQU <__imp_olecli32_ordinal259>
extern __imp_olecli32_ordinal260:PANYARGS
olecli32_ordinal260 TEXTEQU <__imp_olecli32_ordinal260>
extern __imp_olecli32_ordinal261:PANYARGS
olecli32_ordinal261 TEXTEQU <__imp_olecli32_ordinal261>
extern __imp_olecli32_ordinal262:PANYARGS
olecli32_ordinal262 TEXTEQU <__imp_olecli32_ordinal262>
extern __imp_olecli32_ordinal263:PANYARGS
olecli32_ordinal263 TEXTEQU <__imp_olecli32_ordinal263>
extern __imp_olecli32_ordinal264:PANYARGS
olecli32_ordinal264 TEXTEQU <__imp_olecli32_ordinal264>
extern __imp_olecli32_ordinal265:PANYARGS
olecli32_ordinal265 TEXTEQU <__imp_olecli32_ordinal265>
extern __imp_olecli32_ordinal266:PANYARGS
olecli32_ordinal266 TEXTEQU <__imp_olecli32_ordinal266>
extern __imp_olecli32_ordinal267:PANYARGS
olecli32_ordinal267 TEXTEQU <__imp_olecli32_ordinal267>
extern __imp_olecli32_ordinal268:PANYARGS
olecli32_ordinal268 TEXTEQU <__imp_olecli32_ordinal268>
extern __imp_olecli32_ordinal269:PANYARGS
olecli32_ordinal269 TEXTEQU <__imp_olecli32_ordinal269>
extern __imp_olecli32_ordinal270:PANYARGS
olecli32_ordinal270 TEXTEQU <__imp_olecli32_ordinal270>
extern __imp_olecli32_ordinal271:PANYARGS
olecli32_ordinal271 TEXTEQU <__imp_olecli32_ordinal271>
extern __imp_olecli32_ordinal272:PANYARGS
olecli32_ordinal272 TEXTEQU <__imp_olecli32_ordinal272>
extern __imp_olecli32_ordinal273:PANYARGS
olecli32_ordinal273 TEXTEQU <__imp_olecli32_ordinal273>
extern __imp_olecli32_ordinal274:PANYARGS
olecli32_ordinal274 TEXTEQU <__imp_olecli32_ordinal274>
extern __imp_olecli32_ordinal275:PANYARGS
olecli32_ordinal275 TEXTEQU <__imp_olecli32_ordinal275>
extern __imp_olecli32_ordinal276:PANYARGS
olecli32_ordinal276 TEXTEQU <__imp_olecli32_ordinal276>
extern __imp_olecli32_ordinal277:PANYARGS
olecli32_ordinal277 TEXTEQU <__imp_olecli32_ordinal277>
extern __imp_olecli32_ordinal278:PANYARGS
olecli32_ordinal278 TEXTEQU <__imp_olecli32_ordinal278>
extern __imp_olecli32_ordinal279:PANYARGS
olecli32_ordinal279 TEXTEQU <__imp_olecli32_ordinal279>
extern __imp_olecli32_ordinal280:PANYARGS
olecli32_ordinal280 TEXTEQU <__imp_olecli32_ordinal280>
extern __imp_olecli32_ordinal281:PANYARGS
olecli32_ordinal281 TEXTEQU <__imp_olecli32_ordinal281>
extern __imp_olecli32_ordinal282:PANYARGS
olecli32_ordinal282 TEXTEQU <__imp_olecli32_ordinal282>
extern __imp_olecli32_ordinal283:PANYARGS
olecli32_ordinal283 TEXTEQU <__imp_olecli32_ordinal283>
extern __imp_olecli32_ordinal284:PANYARGS
olecli32_ordinal284 TEXTEQU <__imp_olecli32_ordinal284>
extern __imp_olecli32_ordinal285:PANYARGS
olecli32_ordinal285 TEXTEQU <__imp_olecli32_ordinal285>
extern __imp_olecli32_ordinal286:PANYARGS
olecli32_ordinal286 TEXTEQU <__imp_olecli32_ordinal286>
extern __imp_olecli32_ordinal287:PANYARGS
olecli32_ordinal287 TEXTEQU <__imp_olecli32_ordinal287>
extern __imp_olecli32_ordinal288:PANYARGS
olecli32_ordinal288 TEXTEQU <__imp_olecli32_ordinal288>
extern __imp_olecli32_ordinal289:PANYARGS
olecli32_ordinal289 TEXTEQU <__imp_olecli32_ordinal289>
extern __imp_olecli32_ordinal290:PANYARGS
olecli32_ordinal290 TEXTEQU <__imp_olecli32_ordinal290>
extern __imp_olecli32_ordinal291:PANYARGS
olecli32_ordinal291 TEXTEQU <__imp_olecli32_ordinal291>
extern __imp_olecli32_ordinal292:PANYARGS
olecli32_ordinal292 TEXTEQU <__imp_olecli32_ordinal292>
extern __imp_olecli32_ordinal293:PANYARGS
olecli32_ordinal293 TEXTEQU <__imp_olecli32_ordinal293>
extern __imp_olecli32_ordinal294:PANYARGS
olecli32_ordinal294 TEXTEQU <__imp_olecli32_ordinal294>
extern __imp_olecli32_ordinal295:PANYARGS
olecli32_ordinal295 TEXTEQU <__imp_olecli32_ordinal295>
extern __imp_olecli32_ordinal296:PANYARGS
olecli32_ordinal296 TEXTEQU <__imp_olecli32_ordinal296>
extern __imp_olecli32_ordinal297:PANYARGS
olecli32_ordinal297 TEXTEQU <__imp_olecli32_ordinal297>
extern __imp_olecli32_ordinal298:PANYARGS
olecli32_ordinal298 TEXTEQU <__imp_olecli32_ordinal298>
extern __imp_olecli32_ordinal299:PANYARGS
olecli32_ordinal299 TEXTEQU <__imp_olecli32_ordinal299>
extern __imp_MfRelease:PANYARGS
MfRelease TEXTEQU <__imp_MfRelease>
extern __imp_MfGetData:PANYARGS
MfGetData TEXTEQU <__imp_MfGetData>
extern __imp_MfSaveToStream:PANYARGS
MfSaveToStream TEXTEQU <__imp_MfSaveToStream>
extern __imp_MfClone:PANYARGS
MfClone TEXTEQU <__imp_MfClone>
extern __imp_MfEqual:PANYARGS
MfEqual TEXTEQU <__imp_MfEqual>
extern __imp_MfCopy:PANYARGS
MfCopy TEXTEQU <__imp_MfCopy>
extern __imp_olecli32_ordinal306:PANYARGS
olecli32_ordinal306 TEXTEQU <__imp_olecli32_ordinal306>
extern __imp_MfQueryBounds:PANYARGS
MfQueryBounds TEXTEQU <__imp_MfQueryBounds>
extern __imp_MfDraw:PANYARGS
MfDraw TEXTEQU <__imp_MfDraw>
extern __imp_MfEnumFormat:PANYARGS
MfEnumFormat TEXTEQU <__imp_MfEnumFormat>
extern __imp_MfChangeData:PANYARGS
MfChangeData TEXTEQU <__imp_MfChangeData>
extern __imp_olecli32_ordinal311:PANYARGS
olecli32_ordinal311 TEXTEQU <__imp_olecli32_ordinal311>
extern __imp_olecli32_ordinal312:PANYARGS
olecli32_ordinal312 TEXTEQU <__imp_olecli32_ordinal312>
extern __imp_olecli32_ordinal313:PANYARGS
olecli32_ordinal313 TEXTEQU <__imp_olecli32_ordinal313>
extern __imp_olecli32_ordinal314:PANYARGS
olecli32_ordinal314 TEXTEQU <__imp_olecli32_ordinal314>
extern __imp_olecli32_ordinal315:PANYARGS
olecli32_ordinal315 TEXTEQU <__imp_olecli32_ordinal315>
extern __imp_olecli32_ordinal316:PANYARGS
olecli32_ordinal316 TEXTEQU <__imp_olecli32_ordinal316>
extern __imp_olecli32_ordinal317:PANYARGS
olecli32_ordinal317 TEXTEQU <__imp_olecli32_ordinal317>
extern __imp_olecli32_ordinal318:PANYARGS
olecli32_ordinal318 TEXTEQU <__imp_olecli32_ordinal318>
extern __imp_olecli32_ordinal319:PANYARGS
olecli32_ordinal319 TEXTEQU <__imp_olecli32_ordinal319>
extern __imp_olecli32_ordinal320:PANYARGS
olecli32_ordinal320 TEXTEQU <__imp_olecli32_ordinal320>
extern __imp_olecli32_ordinal321:PANYARGS
olecli32_ordinal321 TEXTEQU <__imp_olecli32_ordinal321>
extern __imp_olecli32_ordinal322:PANYARGS
olecli32_ordinal322 TEXTEQU <__imp_olecli32_ordinal322>
extern __imp_olecli32_ordinal323:PANYARGS
olecli32_ordinal323 TEXTEQU <__imp_olecli32_ordinal323>
extern __imp_olecli32_ordinal324:PANYARGS
olecli32_ordinal324 TEXTEQU <__imp_olecli32_ordinal324>
extern __imp_olecli32_ordinal325:PANYARGS
olecli32_ordinal325 TEXTEQU <__imp_olecli32_ordinal325>
extern __imp_olecli32_ordinal326:PANYARGS
olecli32_ordinal326 TEXTEQU <__imp_olecli32_ordinal326>
extern __imp_olecli32_ordinal327:PANYARGS
olecli32_ordinal327 TEXTEQU <__imp_olecli32_ordinal327>
extern __imp_olecli32_ordinal328:PANYARGS
olecli32_ordinal328 TEXTEQU <__imp_olecli32_ordinal328>
extern __imp_olecli32_ordinal329:PANYARGS
olecli32_ordinal329 TEXTEQU <__imp_olecli32_ordinal329>
extern __imp_olecli32_ordinal330:PANYARGS
olecli32_ordinal330 TEXTEQU <__imp_olecli32_ordinal330>
extern __imp_olecli32_ordinal331:PANYARGS
olecli32_ordinal331 TEXTEQU <__imp_olecli32_ordinal331>
extern __imp_olecli32_ordinal332:PANYARGS
olecli32_ordinal332 TEXTEQU <__imp_olecli32_ordinal332>
extern __imp_olecli32_ordinal333:PANYARGS
olecli32_ordinal333 TEXTEQU <__imp_olecli32_ordinal333>
extern __imp_olecli32_ordinal334:PANYARGS
olecli32_ordinal334 TEXTEQU <__imp_olecli32_ordinal334>
extern __imp_olecli32_ordinal335:PANYARGS
olecli32_ordinal335 TEXTEQU <__imp_olecli32_ordinal335>
extern __imp_olecli32_ordinal336:PANYARGS
olecli32_ordinal336 TEXTEQU <__imp_olecli32_ordinal336>
extern __imp_olecli32_ordinal337:PANYARGS
olecli32_ordinal337 TEXTEQU <__imp_olecli32_ordinal337>
extern __imp_olecli32_ordinal338:PANYARGS
olecli32_ordinal338 TEXTEQU <__imp_olecli32_ordinal338>
extern __imp_olecli32_ordinal339:PANYARGS
olecli32_ordinal339 TEXTEQU <__imp_olecli32_ordinal339>
extern __imp_olecli32_ordinal340:PANYARGS
olecli32_ordinal340 TEXTEQU <__imp_olecli32_ordinal340>
extern __imp_olecli32_ordinal341:PANYARGS
olecli32_ordinal341 TEXTEQU <__imp_olecli32_ordinal341>
extern __imp_olecli32_ordinal342:PANYARGS
olecli32_ordinal342 TEXTEQU <__imp_olecli32_ordinal342>
extern __imp_olecli32_ordinal343:PANYARGS
olecli32_ordinal343 TEXTEQU <__imp_olecli32_ordinal343>
extern __imp_olecli32_ordinal344:PANYARGS
olecli32_ordinal344 TEXTEQU <__imp_olecli32_ordinal344>
extern __imp_olecli32_ordinal345:PANYARGS
olecli32_ordinal345 TEXTEQU <__imp_olecli32_ordinal345>
extern __imp_olecli32_ordinal346:PANYARGS
olecli32_ordinal346 TEXTEQU <__imp_olecli32_ordinal346>
extern __imp_olecli32_ordinal347:PANYARGS
olecli32_ordinal347 TEXTEQU <__imp_olecli32_ordinal347>
extern __imp_olecli32_ordinal348:PANYARGS
olecli32_ordinal348 TEXTEQU <__imp_olecli32_ordinal348>
extern __imp_olecli32_ordinal349:PANYARGS
olecli32_ordinal349 TEXTEQU <__imp_olecli32_ordinal349>
extern __imp_olecli32_ordinal350:PANYARGS
olecli32_ordinal350 TEXTEQU <__imp_olecli32_ordinal350>
extern __imp_olecli32_ordinal351:PANYARGS
olecli32_ordinal351 TEXTEQU <__imp_olecli32_ordinal351>
extern __imp_olecli32_ordinal352:PANYARGS
olecli32_ordinal352 TEXTEQU <__imp_olecli32_ordinal352>
extern __imp_olecli32_ordinal353:PANYARGS
olecli32_ordinal353 TEXTEQU <__imp_olecli32_ordinal353>
extern __imp_olecli32_ordinal354:PANYARGS
olecli32_ordinal354 TEXTEQU <__imp_olecli32_ordinal354>
extern __imp_olecli32_ordinal355:PANYARGS
olecli32_ordinal355 TEXTEQU <__imp_olecli32_ordinal355>
extern __imp_olecli32_ordinal356:PANYARGS
olecli32_ordinal356 TEXTEQU <__imp_olecli32_ordinal356>
extern __imp_olecli32_ordinal357:PANYARGS
olecli32_ordinal357 TEXTEQU <__imp_olecli32_ordinal357>
extern __imp_olecli32_ordinal358:PANYARGS
olecli32_ordinal358 TEXTEQU <__imp_olecli32_ordinal358>
extern __imp_olecli32_ordinal359:PANYARGS
olecli32_ordinal359 TEXTEQU <__imp_olecli32_ordinal359>
extern __imp_olecli32_ordinal360:PANYARGS
olecli32_ordinal360 TEXTEQU <__imp_olecli32_ordinal360>
extern __imp_olecli32_ordinal361:PANYARGS
olecli32_ordinal361 TEXTEQU <__imp_olecli32_ordinal361>
extern __imp_olecli32_ordinal362:PANYARGS
olecli32_ordinal362 TEXTEQU <__imp_olecli32_ordinal362>
extern __imp_olecli32_ordinal363:PANYARGS
olecli32_ordinal363 TEXTEQU <__imp_olecli32_ordinal363>
extern __imp_olecli32_ordinal364:PANYARGS
olecli32_ordinal364 TEXTEQU <__imp_olecli32_ordinal364>
extern __imp_olecli32_ordinal365:PANYARGS
olecli32_ordinal365 TEXTEQU <__imp_olecli32_ordinal365>
extern __imp_olecli32_ordinal366:PANYARGS
olecli32_ordinal366 TEXTEQU <__imp_olecli32_ordinal366>
extern __imp_olecli32_ordinal367:PANYARGS
olecli32_ordinal367 TEXTEQU <__imp_olecli32_ordinal367>
extern __imp_olecli32_ordinal368:PANYARGS
olecli32_ordinal368 TEXTEQU <__imp_olecli32_ordinal368>
extern __imp_olecli32_ordinal369:PANYARGS
olecli32_ordinal369 TEXTEQU <__imp_olecli32_ordinal369>
extern __imp_olecli32_ordinal370:PANYARGS
olecli32_ordinal370 TEXTEQU <__imp_olecli32_ordinal370>
extern __imp_olecli32_ordinal371:PANYARGS
olecli32_ordinal371 TEXTEQU <__imp_olecli32_ordinal371>
extern __imp_olecli32_ordinal372:PANYARGS
olecli32_ordinal372 TEXTEQU <__imp_olecli32_ordinal372>
extern __imp_olecli32_ordinal373:PANYARGS
olecli32_ordinal373 TEXTEQU <__imp_olecli32_ordinal373>
extern __imp_olecli32_ordinal374:PANYARGS
olecli32_ordinal374 TEXTEQU <__imp_olecli32_ordinal374>
extern __imp_olecli32_ordinal375:PANYARGS
olecli32_ordinal375 TEXTEQU <__imp_olecli32_ordinal375>
extern __imp_olecli32_ordinal376:PANYARGS
olecli32_ordinal376 TEXTEQU <__imp_olecli32_ordinal376>
extern __imp_olecli32_ordinal377:PANYARGS
olecli32_ordinal377 TEXTEQU <__imp_olecli32_ordinal377>
extern __imp_olecli32_ordinal378:PANYARGS
olecli32_ordinal378 TEXTEQU <__imp_olecli32_ordinal378>
extern __imp_olecli32_ordinal379:PANYARGS
olecli32_ordinal379 TEXTEQU <__imp_olecli32_ordinal379>
extern __imp_olecli32_ordinal380:PANYARGS
olecli32_ordinal380 TEXTEQU <__imp_olecli32_ordinal380>
extern __imp_olecli32_ordinal381:PANYARGS
olecli32_ordinal381 TEXTEQU <__imp_olecli32_ordinal381>
extern __imp_olecli32_ordinal382:PANYARGS
olecli32_ordinal382 TEXTEQU <__imp_olecli32_ordinal382>
extern __imp_olecli32_ordinal383:PANYARGS
olecli32_ordinal383 TEXTEQU <__imp_olecli32_ordinal383>
extern __imp_olecli32_ordinal384:PANYARGS
olecli32_ordinal384 TEXTEQU <__imp_olecli32_ordinal384>
extern __imp_olecli32_ordinal385:PANYARGS
olecli32_ordinal385 TEXTEQU <__imp_olecli32_ordinal385>
extern __imp_olecli32_ordinal386:PANYARGS
olecli32_ordinal386 TEXTEQU <__imp_olecli32_ordinal386>
extern __imp_olecli32_ordinal387:PANYARGS
olecli32_ordinal387 TEXTEQU <__imp_olecli32_ordinal387>
extern __imp_olecli32_ordinal388:PANYARGS
olecli32_ordinal388 TEXTEQU <__imp_olecli32_ordinal388>
extern __imp_olecli32_ordinal389:PANYARGS
olecli32_ordinal389 TEXTEQU <__imp_olecli32_ordinal389>
extern __imp_olecli32_ordinal390:PANYARGS
olecli32_ordinal390 TEXTEQU <__imp_olecli32_ordinal390>
extern __imp_olecli32_ordinal391:PANYARGS
olecli32_ordinal391 TEXTEQU <__imp_olecli32_ordinal391>
extern __imp_olecli32_ordinal392:PANYARGS
olecli32_ordinal392 TEXTEQU <__imp_olecli32_ordinal392>
extern __imp_olecli32_ordinal393:PANYARGS
olecli32_ordinal393 TEXTEQU <__imp_olecli32_ordinal393>
extern __imp_olecli32_ordinal394:PANYARGS
olecli32_ordinal394 TEXTEQU <__imp_olecli32_ordinal394>
extern __imp_olecli32_ordinal395:PANYARGS
olecli32_ordinal395 TEXTEQU <__imp_olecli32_ordinal395>
extern __imp_olecli32_ordinal396:PANYARGS
olecli32_ordinal396 TEXTEQU <__imp_olecli32_ordinal396>
extern __imp_olecli32_ordinal397:PANYARGS
olecli32_ordinal397 TEXTEQU <__imp_olecli32_ordinal397>
extern __imp_olecli32_ordinal398:PANYARGS
olecli32_ordinal398 TEXTEQU <__imp_olecli32_ordinal398>
extern __imp_olecli32_ordinal399:PANYARGS
olecli32_ordinal399 TEXTEQU <__imp_olecli32_ordinal399>
extern __imp_BmRelease:PANYARGS
BmRelease TEXTEQU <__imp_BmRelease>
extern __imp_BmGetData:PANYARGS
BmGetData TEXTEQU <__imp_BmGetData>
extern __imp_BmSaveToStream:PANYARGS
BmSaveToStream TEXTEQU <__imp_BmSaveToStream>
extern __imp_BmClone:PANYARGS
BmClone TEXTEQU <__imp_BmClone>
extern __imp_BmEqual:PANYARGS
BmEqual TEXTEQU <__imp_BmEqual>
extern __imp_BmCopy:PANYARGS
BmCopy TEXTEQU <__imp_BmCopy>
extern __imp_olecli32_ordinal406:PANYARGS
olecli32_ordinal406 TEXTEQU <__imp_olecli32_ordinal406>
extern __imp_BmQueryBounds:PANYARGS
BmQueryBounds TEXTEQU <__imp_BmQueryBounds>
extern __imp_BmDraw:PANYARGS
BmDraw TEXTEQU <__imp_BmDraw>
extern __imp_BmEnumFormat:PANYARGS
BmEnumFormat TEXTEQU <__imp_BmEnumFormat>
extern __imp_BmChangeData:PANYARGS
BmChangeData TEXTEQU <__imp_BmChangeData>
extern __imp_olecli32_ordinal411:PANYARGS
olecli32_ordinal411 TEXTEQU <__imp_olecli32_ordinal411>
extern __imp_olecli32_ordinal412:PANYARGS
olecli32_ordinal412 TEXTEQU <__imp_olecli32_ordinal412>
extern __imp_olecli32_ordinal413:PANYARGS
olecli32_ordinal413 TEXTEQU <__imp_olecli32_ordinal413>
extern __imp_olecli32_ordinal414:PANYARGS
olecli32_ordinal414 TEXTEQU <__imp_olecli32_ordinal414>
extern __imp_olecli32_ordinal415:PANYARGS
olecli32_ordinal415 TEXTEQU <__imp_olecli32_ordinal415>
extern __imp_olecli32_ordinal416:PANYARGS
olecli32_ordinal416 TEXTEQU <__imp_olecli32_ordinal416>
extern __imp_olecli32_ordinal417:PANYARGS
olecli32_ordinal417 TEXTEQU <__imp_olecli32_ordinal417>
extern __imp_olecli32_ordinal418:PANYARGS
olecli32_ordinal418 TEXTEQU <__imp_olecli32_ordinal418>
extern __imp_olecli32_ordinal419:PANYARGS
olecli32_ordinal419 TEXTEQU <__imp_olecli32_ordinal419>
extern __imp_olecli32_ordinal420:PANYARGS
olecli32_ordinal420 TEXTEQU <__imp_olecli32_ordinal420>
extern __imp_olecli32_ordinal421:PANYARGS
olecli32_ordinal421 TEXTEQU <__imp_olecli32_ordinal421>
extern __imp_olecli32_ordinal422:PANYARGS
olecli32_ordinal422 TEXTEQU <__imp_olecli32_ordinal422>
extern __imp_olecli32_ordinal423:PANYARGS
olecli32_ordinal423 TEXTEQU <__imp_olecli32_ordinal423>
extern __imp_olecli32_ordinal424:PANYARGS
olecli32_ordinal424 TEXTEQU <__imp_olecli32_ordinal424>
extern __imp_olecli32_ordinal425:PANYARGS
olecli32_ordinal425 TEXTEQU <__imp_olecli32_ordinal425>
extern __imp_olecli32_ordinal426:PANYARGS
olecli32_ordinal426 TEXTEQU <__imp_olecli32_ordinal426>
extern __imp_olecli32_ordinal427:PANYARGS
olecli32_ordinal427 TEXTEQU <__imp_olecli32_ordinal427>
extern __imp_olecli32_ordinal428:PANYARGS
olecli32_ordinal428 TEXTEQU <__imp_olecli32_ordinal428>
extern __imp_olecli32_ordinal429:PANYARGS
olecli32_ordinal429 TEXTEQU <__imp_olecli32_ordinal429>
extern __imp_olecli32_ordinal430:PANYARGS
olecli32_ordinal430 TEXTEQU <__imp_olecli32_ordinal430>
extern __imp_olecli32_ordinal431:PANYARGS
olecli32_ordinal431 TEXTEQU <__imp_olecli32_ordinal431>
extern __imp_olecli32_ordinal432:PANYARGS
olecli32_ordinal432 TEXTEQU <__imp_olecli32_ordinal432>
extern __imp_olecli32_ordinal433:PANYARGS
olecli32_ordinal433 TEXTEQU <__imp_olecli32_ordinal433>
extern __imp_olecli32_ordinal434:PANYARGS
olecli32_ordinal434 TEXTEQU <__imp_olecli32_ordinal434>
extern __imp_olecli32_ordinal435:PANYARGS
olecli32_ordinal435 TEXTEQU <__imp_olecli32_ordinal435>
extern __imp_olecli32_ordinal436:PANYARGS
olecli32_ordinal436 TEXTEQU <__imp_olecli32_ordinal436>
extern __imp_olecli32_ordinal437:PANYARGS
olecli32_ordinal437 TEXTEQU <__imp_olecli32_ordinal437>
extern __imp_olecli32_ordinal438:PANYARGS
olecli32_ordinal438 TEXTEQU <__imp_olecli32_ordinal438>
extern __imp_olecli32_ordinal439:PANYARGS
olecli32_ordinal439 TEXTEQU <__imp_olecli32_ordinal439>
extern __imp_olecli32_ordinal440:PANYARGS
olecli32_ordinal440 TEXTEQU <__imp_olecli32_ordinal440>
extern __imp_olecli32_ordinal441:PANYARGS
olecli32_ordinal441 TEXTEQU <__imp_olecli32_ordinal441>
extern __imp_olecli32_ordinal442:PANYARGS
olecli32_ordinal442 TEXTEQU <__imp_olecli32_ordinal442>
extern __imp_olecli32_ordinal443:PANYARGS
olecli32_ordinal443 TEXTEQU <__imp_olecli32_ordinal443>
extern __imp_olecli32_ordinal444:PANYARGS
olecli32_ordinal444 TEXTEQU <__imp_olecli32_ordinal444>
extern __imp_olecli32_ordinal445:PANYARGS
olecli32_ordinal445 TEXTEQU <__imp_olecli32_ordinal445>
extern __imp_olecli32_ordinal446:PANYARGS
olecli32_ordinal446 TEXTEQU <__imp_olecli32_ordinal446>
extern __imp_olecli32_ordinal447:PANYARGS
olecli32_ordinal447 TEXTEQU <__imp_olecli32_ordinal447>
extern __imp_olecli32_ordinal448:PANYARGS
olecli32_ordinal448 TEXTEQU <__imp_olecli32_ordinal448>
extern __imp_olecli32_ordinal449:PANYARGS
olecli32_ordinal449 TEXTEQU <__imp_olecli32_ordinal449>
extern __imp_olecli32_ordinal450:PANYARGS
olecli32_ordinal450 TEXTEQU <__imp_olecli32_ordinal450>
extern __imp_olecli32_ordinal451:PANYARGS
olecli32_ordinal451 TEXTEQU <__imp_olecli32_ordinal451>
extern __imp_olecli32_ordinal452:PANYARGS
olecli32_ordinal452 TEXTEQU <__imp_olecli32_ordinal452>
extern __imp_olecli32_ordinal453:PANYARGS
olecli32_ordinal453 TEXTEQU <__imp_olecli32_ordinal453>
extern __imp_olecli32_ordinal454:PANYARGS
olecli32_ordinal454 TEXTEQU <__imp_olecli32_ordinal454>
extern __imp_olecli32_ordinal455:PANYARGS
olecli32_ordinal455 TEXTEQU <__imp_olecli32_ordinal455>
extern __imp_olecli32_ordinal456:PANYARGS
olecli32_ordinal456 TEXTEQU <__imp_olecli32_ordinal456>
extern __imp_olecli32_ordinal457:PANYARGS
olecli32_ordinal457 TEXTEQU <__imp_olecli32_ordinal457>
extern __imp_olecli32_ordinal458:PANYARGS
olecli32_ordinal458 TEXTEQU <__imp_olecli32_ordinal458>
extern __imp_olecli32_ordinal459:PANYARGS
olecli32_ordinal459 TEXTEQU <__imp_olecli32_ordinal459>
extern __imp_olecli32_ordinal460:PANYARGS
olecli32_ordinal460 TEXTEQU <__imp_olecli32_ordinal460>
extern __imp_olecli32_ordinal461:PANYARGS
olecli32_ordinal461 TEXTEQU <__imp_olecli32_ordinal461>
extern __imp_olecli32_ordinal462:PANYARGS
olecli32_ordinal462 TEXTEQU <__imp_olecli32_ordinal462>
extern __imp_olecli32_ordinal463:PANYARGS
olecli32_ordinal463 TEXTEQU <__imp_olecli32_ordinal463>
extern __imp_olecli32_ordinal464:PANYARGS
olecli32_ordinal464 TEXTEQU <__imp_olecli32_ordinal464>
extern __imp_olecli32_ordinal465:PANYARGS
olecli32_ordinal465 TEXTEQU <__imp_olecli32_ordinal465>
extern __imp_olecli32_ordinal466:PANYARGS
olecli32_ordinal466 TEXTEQU <__imp_olecli32_ordinal466>
extern __imp_olecli32_ordinal467:PANYARGS
olecli32_ordinal467 TEXTEQU <__imp_olecli32_ordinal467>
extern __imp_olecli32_ordinal468:PANYARGS
olecli32_ordinal468 TEXTEQU <__imp_olecli32_ordinal468>
extern __imp_olecli32_ordinal469:PANYARGS
olecli32_ordinal469 TEXTEQU <__imp_olecli32_ordinal469>
extern __imp_olecli32_ordinal470:PANYARGS
olecli32_ordinal470 TEXTEQU <__imp_olecli32_ordinal470>
extern __imp_olecli32_ordinal471:PANYARGS
olecli32_ordinal471 TEXTEQU <__imp_olecli32_ordinal471>
extern __imp_olecli32_ordinal472:PANYARGS
olecli32_ordinal472 TEXTEQU <__imp_olecli32_ordinal472>
extern __imp_olecli32_ordinal473:PANYARGS
olecli32_ordinal473 TEXTEQU <__imp_olecli32_ordinal473>
extern __imp_olecli32_ordinal474:PANYARGS
olecli32_ordinal474 TEXTEQU <__imp_olecli32_ordinal474>
extern __imp_olecli32_ordinal475:PANYARGS
olecli32_ordinal475 TEXTEQU <__imp_olecli32_ordinal475>
extern __imp_olecli32_ordinal476:PANYARGS
olecli32_ordinal476 TEXTEQU <__imp_olecli32_ordinal476>
extern __imp_olecli32_ordinal477:PANYARGS
olecli32_ordinal477 TEXTEQU <__imp_olecli32_ordinal477>
extern __imp_olecli32_ordinal478:PANYARGS
olecli32_ordinal478 TEXTEQU <__imp_olecli32_ordinal478>
extern __imp_olecli32_ordinal479:PANYARGS
olecli32_ordinal479 TEXTEQU <__imp_olecli32_ordinal479>
extern __imp_olecli32_ordinal480:PANYARGS
olecli32_ordinal480 TEXTEQU <__imp_olecli32_ordinal480>
extern __imp_olecli32_ordinal481:PANYARGS
olecli32_ordinal481 TEXTEQU <__imp_olecli32_ordinal481>
extern __imp_olecli32_ordinal482:PANYARGS
olecli32_ordinal482 TEXTEQU <__imp_olecli32_ordinal482>
extern __imp_olecli32_ordinal483:PANYARGS
olecli32_ordinal483 TEXTEQU <__imp_olecli32_ordinal483>
extern __imp_olecli32_ordinal484:PANYARGS
olecli32_ordinal484 TEXTEQU <__imp_olecli32_ordinal484>
extern __imp_olecli32_ordinal485:PANYARGS
olecli32_ordinal485 TEXTEQU <__imp_olecli32_ordinal485>
extern __imp_olecli32_ordinal486:PANYARGS
olecli32_ordinal486 TEXTEQU <__imp_olecli32_ordinal486>
extern __imp_olecli32_ordinal487:PANYARGS
olecli32_ordinal487 TEXTEQU <__imp_olecli32_ordinal487>
extern __imp_olecli32_ordinal488:PANYARGS
olecli32_ordinal488 TEXTEQU <__imp_olecli32_ordinal488>
extern __imp_olecli32_ordinal489:PANYARGS
olecli32_ordinal489 TEXTEQU <__imp_olecli32_ordinal489>
extern __imp_olecli32_ordinal490:PANYARGS
olecli32_ordinal490 TEXTEQU <__imp_olecli32_ordinal490>
extern __imp_olecli32_ordinal491:PANYARGS
olecli32_ordinal491 TEXTEQU <__imp_olecli32_ordinal491>
extern __imp_olecli32_ordinal492:PANYARGS
olecli32_ordinal492 TEXTEQU <__imp_olecli32_ordinal492>
extern __imp_olecli32_ordinal493:PANYARGS
olecli32_ordinal493 TEXTEQU <__imp_olecli32_ordinal493>
extern __imp_olecli32_ordinal494:PANYARGS
olecli32_ordinal494 TEXTEQU <__imp_olecli32_ordinal494>
extern __imp_olecli32_ordinal495:PANYARGS
olecli32_ordinal495 TEXTEQU <__imp_olecli32_ordinal495>
extern __imp_olecli32_ordinal496:PANYARGS
olecli32_ordinal496 TEXTEQU <__imp_olecli32_ordinal496>
extern __imp_olecli32_ordinal497:PANYARGS
olecli32_ordinal497 TEXTEQU <__imp_olecli32_ordinal497>
extern __imp_olecli32_ordinal498:PANYARGS
olecli32_ordinal498 TEXTEQU <__imp_olecli32_ordinal498>
extern __imp_olecli32_ordinal499:PANYARGS
olecli32_ordinal499 TEXTEQU <__imp_olecli32_ordinal499>
extern __imp_DibRelease:PANYARGS
DibRelease TEXTEQU <__imp_DibRelease>
extern __imp_DibGetData:PANYARGS
DibGetData TEXTEQU <__imp_DibGetData>
extern __imp_DibSaveToStream:PANYARGS
DibSaveToStream TEXTEQU <__imp_DibSaveToStream>
extern __imp_DibClone:PANYARGS
DibClone TEXTEQU <__imp_DibClone>
extern __imp_DibEqual:PANYARGS
DibEqual TEXTEQU <__imp_DibEqual>
extern __imp_DibCopy:PANYARGS
DibCopy TEXTEQU <__imp_DibCopy>
extern __imp_olecli32_ordinal506:PANYARGS
olecli32_ordinal506 TEXTEQU <__imp_olecli32_ordinal506>
extern __imp_DibQueryBounds:PANYARGS
DibQueryBounds TEXTEQU <__imp_DibQueryBounds>
extern __imp_DibDraw:PANYARGS
DibDraw TEXTEQU <__imp_DibDraw>
extern __imp_DibEnumFormat:PANYARGS
DibEnumFormat TEXTEQU <__imp_DibEnumFormat>
extern __imp_DibChangeData:PANYARGS
DibChangeData TEXTEQU <__imp_DibChangeData>
extern __imp_olecli32_ordinal511:PANYARGS
olecli32_ordinal511 TEXTEQU <__imp_olecli32_ordinal511>
extern __imp_olecli32_ordinal512:PANYARGS
olecli32_ordinal512 TEXTEQU <__imp_olecli32_ordinal512>
extern __imp_olecli32_ordinal513:PANYARGS
olecli32_ordinal513 TEXTEQU <__imp_olecli32_ordinal513>
extern __imp_olecli32_ordinal514:PANYARGS
olecli32_ordinal514 TEXTEQU <__imp_olecli32_ordinal514>
extern __imp_olecli32_ordinal515:PANYARGS
olecli32_ordinal515 TEXTEQU <__imp_olecli32_ordinal515>
extern __imp_olecli32_ordinal516:PANYARGS
olecli32_ordinal516 TEXTEQU <__imp_olecli32_ordinal516>
extern __imp_olecli32_ordinal517:PANYARGS
olecli32_ordinal517 TEXTEQU <__imp_olecli32_ordinal517>
extern __imp_olecli32_ordinal518:PANYARGS
olecli32_ordinal518 TEXTEQU <__imp_olecli32_ordinal518>
extern __imp_olecli32_ordinal519:PANYARGS
olecli32_ordinal519 TEXTEQU <__imp_olecli32_ordinal519>
extern __imp_olecli32_ordinal520:PANYARGS
olecli32_ordinal520 TEXTEQU <__imp_olecli32_ordinal520>
extern __imp_olecli32_ordinal521:PANYARGS
olecli32_ordinal521 TEXTEQU <__imp_olecli32_ordinal521>
extern __imp_olecli32_ordinal522:PANYARGS
olecli32_ordinal522 TEXTEQU <__imp_olecli32_ordinal522>
extern __imp_olecli32_ordinal523:PANYARGS
olecli32_ordinal523 TEXTEQU <__imp_olecli32_ordinal523>
extern __imp_olecli32_ordinal524:PANYARGS
olecli32_ordinal524 TEXTEQU <__imp_olecli32_ordinal524>
extern __imp_olecli32_ordinal525:PANYARGS
olecli32_ordinal525 TEXTEQU <__imp_olecli32_ordinal525>
extern __imp_olecli32_ordinal526:PANYARGS
olecli32_ordinal526 TEXTEQU <__imp_olecli32_ordinal526>
extern __imp_olecli32_ordinal527:PANYARGS
olecli32_ordinal527 TEXTEQU <__imp_olecli32_ordinal527>
extern __imp_olecli32_ordinal528:PANYARGS
olecli32_ordinal528 TEXTEQU <__imp_olecli32_ordinal528>
extern __imp_olecli32_ordinal529:PANYARGS
olecli32_ordinal529 TEXTEQU <__imp_olecli32_ordinal529>
extern __imp_olecli32_ordinal530:PANYARGS
olecli32_ordinal530 TEXTEQU <__imp_olecli32_ordinal530>
extern __imp_olecli32_ordinal531:PANYARGS
olecli32_ordinal531 TEXTEQU <__imp_olecli32_ordinal531>
extern __imp_olecli32_ordinal532:PANYARGS
olecli32_ordinal532 TEXTEQU <__imp_olecli32_ordinal532>
extern __imp_olecli32_ordinal533:PANYARGS
olecli32_ordinal533 TEXTEQU <__imp_olecli32_ordinal533>
extern __imp_olecli32_ordinal534:PANYARGS
olecli32_ordinal534 TEXTEQU <__imp_olecli32_ordinal534>
extern __imp_olecli32_ordinal535:PANYARGS
olecli32_ordinal535 TEXTEQU <__imp_olecli32_ordinal535>
extern __imp_olecli32_ordinal536:PANYARGS
olecli32_ordinal536 TEXTEQU <__imp_olecli32_ordinal536>
extern __imp_olecli32_ordinal537:PANYARGS
olecli32_ordinal537 TEXTEQU <__imp_olecli32_ordinal537>
extern __imp_olecli32_ordinal538:PANYARGS
olecli32_ordinal538 TEXTEQU <__imp_olecli32_ordinal538>
extern __imp_olecli32_ordinal539:PANYARGS
olecli32_ordinal539 TEXTEQU <__imp_olecli32_ordinal539>
extern __imp_olecli32_ordinal540:PANYARGS
olecli32_ordinal540 TEXTEQU <__imp_olecli32_ordinal540>
extern __imp_olecli32_ordinal541:PANYARGS
olecli32_ordinal541 TEXTEQU <__imp_olecli32_ordinal541>
extern __imp_olecli32_ordinal542:PANYARGS
olecli32_ordinal542 TEXTEQU <__imp_olecli32_ordinal542>
extern __imp_olecli32_ordinal543:PANYARGS
olecli32_ordinal543 TEXTEQU <__imp_olecli32_ordinal543>
extern __imp_olecli32_ordinal544:PANYARGS
olecli32_ordinal544 TEXTEQU <__imp_olecli32_ordinal544>
extern __imp_olecli32_ordinal545:PANYARGS
olecli32_ordinal545 TEXTEQU <__imp_olecli32_ordinal545>
extern __imp_olecli32_ordinal546:PANYARGS
olecli32_ordinal546 TEXTEQU <__imp_olecli32_ordinal546>
extern __imp_olecli32_ordinal547:PANYARGS
olecli32_ordinal547 TEXTEQU <__imp_olecli32_ordinal547>
extern __imp_olecli32_ordinal548:PANYARGS
olecli32_ordinal548 TEXTEQU <__imp_olecli32_ordinal548>
extern __imp_olecli32_ordinal549:PANYARGS
olecli32_ordinal549 TEXTEQU <__imp_olecli32_ordinal549>
extern __imp_olecli32_ordinal550:PANYARGS
olecli32_ordinal550 TEXTEQU <__imp_olecli32_ordinal550>
extern __imp_olecli32_ordinal551:PANYARGS
olecli32_ordinal551 TEXTEQU <__imp_olecli32_ordinal551>
extern __imp_olecli32_ordinal552:PANYARGS
olecli32_ordinal552 TEXTEQU <__imp_olecli32_ordinal552>
extern __imp_olecli32_ordinal553:PANYARGS
olecli32_ordinal553 TEXTEQU <__imp_olecli32_ordinal553>
extern __imp_olecli32_ordinal554:PANYARGS
olecli32_ordinal554 TEXTEQU <__imp_olecli32_ordinal554>
extern __imp_olecli32_ordinal555:PANYARGS
olecli32_ordinal555 TEXTEQU <__imp_olecli32_ordinal555>
extern __imp_olecli32_ordinal556:PANYARGS
olecli32_ordinal556 TEXTEQU <__imp_olecli32_ordinal556>
extern __imp_olecli32_ordinal557:PANYARGS
olecli32_ordinal557 TEXTEQU <__imp_olecli32_ordinal557>
extern __imp_olecli32_ordinal558:PANYARGS
olecli32_ordinal558 TEXTEQU <__imp_olecli32_ordinal558>
extern __imp_olecli32_ordinal559:PANYARGS
olecli32_ordinal559 TEXTEQU <__imp_olecli32_ordinal559>
extern __imp_olecli32_ordinal560:PANYARGS
olecli32_ordinal560 TEXTEQU <__imp_olecli32_ordinal560>
extern __imp_olecli32_ordinal561:PANYARGS
olecli32_ordinal561 TEXTEQU <__imp_olecli32_ordinal561>
extern __imp_olecli32_ordinal562:PANYARGS
olecli32_ordinal562 TEXTEQU <__imp_olecli32_ordinal562>
extern __imp_olecli32_ordinal563:PANYARGS
olecli32_ordinal563 TEXTEQU <__imp_olecli32_ordinal563>
extern __imp_olecli32_ordinal564:PANYARGS
olecli32_ordinal564 TEXTEQU <__imp_olecli32_ordinal564>
extern __imp_olecli32_ordinal565:PANYARGS
olecli32_ordinal565 TEXTEQU <__imp_olecli32_ordinal565>
extern __imp_olecli32_ordinal566:PANYARGS
olecli32_ordinal566 TEXTEQU <__imp_olecli32_ordinal566>
extern __imp_olecli32_ordinal567:PANYARGS
olecli32_ordinal567 TEXTEQU <__imp_olecli32_ordinal567>
extern __imp_olecli32_ordinal568:PANYARGS
olecli32_ordinal568 TEXTEQU <__imp_olecli32_ordinal568>
extern __imp_olecli32_ordinal569:PANYARGS
olecli32_ordinal569 TEXTEQU <__imp_olecli32_ordinal569>
extern __imp_olecli32_ordinal570:PANYARGS
olecli32_ordinal570 TEXTEQU <__imp_olecli32_ordinal570>
extern __imp_olecli32_ordinal571:PANYARGS
olecli32_ordinal571 TEXTEQU <__imp_olecli32_ordinal571>
extern __imp_olecli32_ordinal572:PANYARGS
olecli32_ordinal572 TEXTEQU <__imp_olecli32_ordinal572>
extern __imp_olecli32_ordinal573:PANYARGS
olecli32_ordinal573 TEXTEQU <__imp_olecli32_ordinal573>
extern __imp_olecli32_ordinal574:PANYARGS
olecli32_ordinal574 TEXTEQU <__imp_olecli32_ordinal574>
extern __imp_olecli32_ordinal575:PANYARGS
olecli32_ordinal575 TEXTEQU <__imp_olecli32_ordinal575>
extern __imp_olecli32_ordinal576:PANYARGS
olecli32_ordinal576 TEXTEQU <__imp_olecli32_ordinal576>
extern __imp_olecli32_ordinal577:PANYARGS
olecli32_ordinal577 TEXTEQU <__imp_olecli32_ordinal577>
extern __imp_olecli32_ordinal578:PANYARGS
olecli32_ordinal578 TEXTEQU <__imp_olecli32_ordinal578>
extern __imp_olecli32_ordinal579:PANYARGS
olecli32_ordinal579 TEXTEQU <__imp_olecli32_ordinal579>
extern __imp_olecli32_ordinal580:PANYARGS
olecli32_ordinal580 TEXTEQU <__imp_olecli32_ordinal580>
extern __imp_olecli32_ordinal581:PANYARGS
olecli32_ordinal581 TEXTEQU <__imp_olecli32_ordinal581>
extern __imp_olecli32_ordinal582:PANYARGS
olecli32_ordinal582 TEXTEQU <__imp_olecli32_ordinal582>
extern __imp_olecli32_ordinal583:PANYARGS
olecli32_ordinal583 TEXTEQU <__imp_olecli32_ordinal583>
extern __imp_olecli32_ordinal584:PANYARGS
olecli32_ordinal584 TEXTEQU <__imp_olecli32_ordinal584>
extern __imp_olecli32_ordinal585:PANYARGS
olecli32_ordinal585 TEXTEQU <__imp_olecli32_ordinal585>
extern __imp_olecli32_ordinal586:PANYARGS
olecli32_ordinal586 TEXTEQU <__imp_olecli32_ordinal586>
extern __imp_olecli32_ordinal587:PANYARGS
olecli32_ordinal587 TEXTEQU <__imp_olecli32_ordinal587>
extern __imp_olecli32_ordinal588:PANYARGS
olecli32_ordinal588 TEXTEQU <__imp_olecli32_ordinal588>
extern __imp_olecli32_ordinal589:PANYARGS
olecli32_ordinal589 TEXTEQU <__imp_olecli32_ordinal589>
extern __imp_olecli32_ordinal590:PANYARGS
olecli32_ordinal590 TEXTEQU <__imp_olecli32_ordinal590>
extern __imp_olecli32_ordinal591:PANYARGS
olecli32_ordinal591 TEXTEQU <__imp_olecli32_ordinal591>
extern __imp_olecli32_ordinal592:PANYARGS
olecli32_ordinal592 TEXTEQU <__imp_olecli32_ordinal592>
extern __imp_olecli32_ordinal593:PANYARGS
olecli32_ordinal593 TEXTEQU <__imp_olecli32_ordinal593>
extern __imp_olecli32_ordinal594:PANYARGS
olecli32_ordinal594 TEXTEQU <__imp_olecli32_ordinal594>
extern __imp_olecli32_ordinal595:PANYARGS
olecli32_ordinal595 TEXTEQU <__imp_olecli32_ordinal595>
extern __imp_olecli32_ordinal596:PANYARGS
olecli32_ordinal596 TEXTEQU <__imp_olecli32_ordinal596>
extern __imp_olecli32_ordinal597:PANYARGS
olecli32_ordinal597 TEXTEQU <__imp_olecli32_ordinal597>
extern __imp_olecli32_ordinal598:PANYARGS
olecli32_ordinal598 TEXTEQU <__imp_olecli32_ordinal598>
extern __imp_olecli32_ordinal599:PANYARGS
olecli32_ordinal599 TEXTEQU <__imp_olecli32_ordinal599>
extern __imp_GenRelease:PANYARGS
GenRelease TEXTEQU <__imp_GenRelease>
extern __imp_GenGetData:PANYARGS
GenGetData TEXTEQU <__imp_GenGetData>
extern __imp_GenSetData:PANYARGS
GenSetData TEXTEQU <__imp_GenSetData>
extern __imp_GenSaveToStream:PANYARGS
GenSaveToStream TEXTEQU <__imp_GenSaveToStream>
extern __imp_GenClone:PANYARGS
GenClone TEXTEQU <__imp_GenClone>
extern __imp_GenEqual:PANYARGS
GenEqual TEXTEQU <__imp_GenEqual>
extern __imp_GenCopy:PANYARGS
GenCopy TEXTEQU <__imp_GenCopy>
extern __imp_olecli32_ordinal607:PANYARGS
olecli32_ordinal607 TEXTEQU <__imp_olecli32_ordinal607>
extern __imp_GenQueryBounds:PANYARGS
GenQueryBounds TEXTEQU <__imp_GenQueryBounds>
extern __imp_GenDraw:PANYARGS
GenDraw TEXTEQU <__imp_GenDraw>
extern __imp_GenEnumFormat:PANYARGS
GenEnumFormat TEXTEQU <__imp_GenEnumFormat>
extern __imp_GenChangeData:PANYARGS
GenChangeData TEXTEQU <__imp_GenChangeData>
extern __imp_olecli32_ordinal612:PANYARGS
olecli32_ordinal612 TEXTEQU <__imp_olecli32_ordinal612>
extern __imp_olecli32_ordinal613:PANYARGS
olecli32_ordinal613 TEXTEQU <__imp_olecli32_ordinal613>
extern __imp_olecli32_ordinal614:PANYARGS
olecli32_ordinal614 TEXTEQU <__imp_olecli32_ordinal614>
extern __imp_olecli32_ordinal615:PANYARGS
olecli32_ordinal615 TEXTEQU <__imp_olecli32_ordinal615>
extern __imp_olecli32_ordinal616:PANYARGS
olecli32_ordinal616 TEXTEQU <__imp_olecli32_ordinal616>
extern __imp_olecli32_ordinal617:PANYARGS
olecli32_ordinal617 TEXTEQU <__imp_olecli32_ordinal617>
extern __imp_olecli32_ordinal618:PANYARGS
olecli32_ordinal618 TEXTEQU <__imp_olecli32_ordinal618>
extern __imp_olecli32_ordinal619:PANYARGS
olecli32_ordinal619 TEXTEQU <__imp_olecli32_ordinal619>
extern __imp_olecli32_ordinal620:PANYARGS
olecli32_ordinal620 TEXTEQU <__imp_olecli32_ordinal620>
extern __imp_olecli32_ordinal621:PANYARGS
olecli32_ordinal621 TEXTEQU <__imp_olecli32_ordinal621>
extern __imp_olecli32_ordinal622:PANYARGS
olecli32_ordinal622 TEXTEQU <__imp_olecli32_ordinal622>
extern __imp_olecli32_ordinal623:PANYARGS
olecli32_ordinal623 TEXTEQU <__imp_olecli32_ordinal623>
extern __imp_olecli32_ordinal624:PANYARGS
olecli32_ordinal624 TEXTEQU <__imp_olecli32_ordinal624>
extern __imp_olecli32_ordinal625:PANYARGS
olecli32_ordinal625 TEXTEQU <__imp_olecli32_ordinal625>
extern __imp_olecli32_ordinal626:PANYARGS
olecli32_ordinal626 TEXTEQU <__imp_olecli32_ordinal626>
extern __imp_olecli32_ordinal627:PANYARGS
olecli32_ordinal627 TEXTEQU <__imp_olecli32_ordinal627>
extern __imp_olecli32_ordinal628:PANYARGS
olecli32_ordinal628 TEXTEQU <__imp_olecli32_ordinal628>
extern __imp_olecli32_ordinal629:PANYARGS
olecli32_ordinal629 TEXTEQU <__imp_olecli32_ordinal629>
extern __imp_olecli32_ordinal630:PANYARGS
olecli32_ordinal630 TEXTEQU <__imp_olecli32_ordinal630>
extern __imp_olecli32_ordinal631:PANYARGS
olecli32_ordinal631 TEXTEQU <__imp_olecli32_ordinal631>
extern __imp_olecli32_ordinal632:PANYARGS
olecli32_ordinal632 TEXTEQU <__imp_olecli32_ordinal632>
extern __imp_olecli32_ordinal633:PANYARGS
olecli32_ordinal633 TEXTEQU <__imp_olecli32_ordinal633>
extern __imp_olecli32_ordinal634:PANYARGS
olecli32_ordinal634 TEXTEQU <__imp_olecli32_ordinal634>
extern __imp_olecli32_ordinal635:PANYARGS
olecli32_ordinal635 TEXTEQU <__imp_olecli32_ordinal635>
extern __imp_olecli32_ordinal636:PANYARGS
olecli32_ordinal636 TEXTEQU <__imp_olecli32_ordinal636>
extern __imp_olecli32_ordinal637:PANYARGS
olecli32_ordinal637 TEXTEQU <__imp_olecli32_ordinal637>
extern __imp_olecli32_ordinal638:PANYARGS
olecli32_ordinal638 TEXTEQU <__imp_olecli32_ordinal638>
extern __imp_olecli32_ordinal639:PANYARGS
olecli32_ordinal639 TEXTEQU <__imp_olecli32_ordinal639>
extern __imp_olecli32_ordinal640:PANYARGS
olecli32_ordinal640 TEXTEQU <__imp_olecli32_ordinal640>
extern __imp_olecli32_ordinal641:PANYARGS
olecli32_ordinal641 TEXTEQU <__imp_olecli32_ordinal641>
extern __imp_olecli32_ordinal642:PANYARGS
olecli32_ordinal642 TEXTEQU <__imp_olecli32_ordinal642>
extern __imp_olecli32_ordinal643:PANYARGS
olecli32_ordinal643 TEXTEQU <__imp_olecli32_ordinal643>
extern __imp_olecli32_ordinal644:PANYARGS
olecli32_ordinal644 TEXTEQU <__imp_olecli32_ordinal644>
extern __imp_olecli32_ordinal645:PANYARGS
olecli32_ordinal645 TEXTEQU <__imp_olecli32_ordinal645>
extern __imp_olecli32_ordinal646:PANYARGS
olecli32_ordinal646 TEXTEQU <__imp_olecli32_ordinal646>
extern __imp_olecli32_ordinal647:PANYARGS
olecli32_ordinal647 TEXTEQU <__imp_olecli32_ordinal647>
extern __imp_olecli32_ordinal648:PANYARGS
olecli32_ordinal648 TEXTEQU <__imp_olecli32_ordinal648>
extern __imp_olecli32_ordinal649:PANYARGS
olecli32_ordinal649 TEXTEQU <__imp_olecli32_ordinal649>
extern __imp_olecli32_ordinal650:PANYARGS
olecli32_ordinal650 TEXTEQU <__imp_olecli32_ordinal650>
extern __imp_olecli32_ordinal651:PANYARGS
olecli32_ordinal651 TEXTEQU <__imp_olecli32_ordinal651>
extern __imp_olecli32_ordinal652:PANYARGS
olecli32_ordinal652 TEXTEQU <__imp_olecli32_ordinal652>
extern __imp_olecli32_ordinal653:PANYARGS
olecli32_ordinal653 TEXTEQU <__imp_olecli32_ordinal653>
extern __imp_olecli32_ordinal654:PANYARGS
olecli32_ordinal654 TEXTEQU <__imp_olecli32_ordinal654>
extern __imp_olecli32_ordinal655:PANYARGS
olecli32_ordinal655 TEXTEQU <__imp_olecli32_ordinal655>
extern __imp_olecli32_ordinal656:PANYARGS
olecli32_ordinal656 TEXTEQU <__imp_olecli32_ordinal656>
extern __imp_olecli32_ordinal657:PANYARGS
olecli32_ordinal657 TEXTEQU <__imp_olecli32_ordinal657>
extern __imp_olecli32_ordinal658:PANYARGS
olecli32_ordinal658 TEXTEQU <__imp_olecli32_ordinal658>
extern __imp_olecli32_ordinal659:PANYARGS
olecli32_ordinal659 TEXTEQU <__imp_olecli32_ordinal659>
extern __imp_olecli32_ordinal660:PANYARGS
olecli32_ordinal660 TEXTEQU <__imp_olecli32_ordinal660>
extern __imp_olecli32_ordinal661:PANYARGS
olecli32_ordinal661 TEXTEQU <__imp_olecli32_ordinal661>
extern __imp_olecli32_ordinal662:PANYARGS
olecli32_ordinal662 TEXTEQU <__imp_olecli32_ordinal662>
extern __imp_olecli32_ordinal663:PANYARGS
olecli32_ordinal663 TEXTEQU <__imp_olecli32_ordinal663>
extern __imp_olecli32_ordinal664:PANYARGS
olecli32_ordinal664 TEXTEQU <__imp_olecli32_ordinal664>
extern __imp_olecli32_ordinal665:PANYARGS
olecli32_ordinal665 TEXTEQU <__imp_olecli32_ordinal665>
extern __imp_olecli32_ordinal666:PANYARGS
olecli32_ordinal666 TEXTEQU <__imp_olecli32_ordinal666>
extern __imp_olecli32_ordinal667:PANYARGS
olecli32_ordinal667 TEXTEQU <__imp_olecli32_ordinal667>
extern __imp_olecli32_ordinal668:PANYARGS
olecli32_ordinal668 TEXTEQU <__imp_olecli32_ordinal668>
extern __imp_olecli32_ordinal669:PANYARGS
olecli32_ordinal669 TEXTEQU <__imp_olecli32_ordinal669>
extern __imp_olecli32_ordinal670:PANYARGS
olecli32_ordinal670 TEXTEQU <__imp_olecli32_ordinal670>
extern __imp_olecli32_ordinal671:PANYARGS
olecli32_ordinal671 TEXTEQU <__imp_olecli32_ordinal671>
extern __imp_olecli32_ordinal672:PANYARGS
olecli32_ordinal672 TEXTEQU <__imp_olecli32_ordinal672>
extern __imp_olecli32_ordinal673:PANYARGS
olecli32_ordinal673 TEXTEQU <__imp_olecli32_ordinal673>
extern __imp_olecli32_ordinal674:PANYARGS
olecli32_ordinal674 TEXTEQU <__imp_olecli32_ordinal674>
extern __imp_olecli32_ordinal675:PANYARGS
olecli32_ordinal675 TEXTEQU <__imp_olecli32_ordinal675>
extern __imp_olecli32_ordinal676:PANYARGS
olecli32_ordinal676 TEXTEQU <__imp_olecli32_ordinal676>
extern __imp_olecli32_ordinal677:PANYARGS
olecli32_ordinal677 TEXTEQU <__imp_olecli32_ordinal677>
extern __imp_olecli32_ordinal678:PANYARGS
olecli32_ordinal678 TEXTEQU <__imp_olecli32_ordinal678>
extern __imp_olecli32_ordinal679:PANYARGS
olecli32_ordinal679 TEXTEQU <__imp_olecli32_ordinal679>
extern __imp_olecli32_ordinal680:PANYARGS
olecli32_ordinal680 TEXTEQU <__imp_olecli32_ordinal680>
extern __imp_olecli32_ordinal681:PANYARGS
olecli32_ordinal681 TEXTEQU <__imp_olecli32_ordinal681>
extern __imp_olecli32_ordinal682:PANYARGS
olecli32_ordinal682 TEXTEQU <__imp_olecli32_ordinal682>
extern __imp_olecli32_ordinal683:PANYARGS
olecli32_ordinal683 TEXTEQU <__imp_olecli32_ordinal683>
extern __imp_olecli32_ordinal684:PANYARGS
olecli32_ordinal684 TEXTEQU <__imp_olecli32_ordinal684>
extern __imp_olecli32_ordinal685:PANYARGS
olecli32_ordinal685 TEXTEQU <__imp_olecli32_ordinal685>
extern __imp_olecli32_ordinal686:PANYARGS
olecli32_ordinal686 TEXTEQU <__imp_olecli32_ordinal686>
extern __imp_olecli32_ordinal687:PANYARGS
olecli32_ordinal687 TEXTEQU <__imp_olecli32_ordinal687>
extern __imp_olecli32_ordinal688:PANYARGS
olecli32_ordinal688 TEXTEQU <__imp_olecli32_ordinal688>
extern __imp_olecli32_ordinal689:PANYARGS
olecli32_ordinal689 TEXTEQU <__imp_olecli32_ordinal689>
extern __imp_olecli32_ordinal690:PANYARGS
olecli32_ordinal690 TEXTEQU <__imp_olecli32_ordinal690>
extern __imp_olecli32_ordinal691:PANYARGS
olecli32_ordinal691 TEXTEQU <__imp_olecli32_ordinal691>
extern __imp_olecli32_ordinal692:PANYARGS
olecli32_ordinal692 TEXTEQU <__imp_olecli32_ordinal692>
extern __imp_olecli32_ordinal693:PANYARGS
olecli32_ordinal693 TEXTEQU <__imp_olecli32_ordinal693>
extern __imp_olecli32_ordinal694:PANYARGS
olecli32_ordinal694 TEXTEQU <__imp_olecli32_ordinal694>
extern __imp_olecli32_ordinal695:PANYARGS
olecli32_ordinal695 TEXTEQU <__imp_olecli32_ordinal695>
extern __imp_olecli32_ordinal696:PANYARGS
olecli32_ordinal696 TEXTEQU <__imp_olecli32_ordinal696>
extern __imp_olecli32_ordinal697:PANYARGS
olecli32_ordinal697 TEXTEQU <__imp_olecli32_ordinal697>
extern __imp_olecli32_ordinal698:PANYARGS
olecli32_ordinal698 TEXTEQU <__imp_olecli32_ordinal698>
extern __imp_olecli32_ordinal699:PANYARGS
olecli32_ordinal699 TEXTEQU <__imp_olecli32_ordinal699>
extern __imp_olecli32_ordinal700:PANYARGS
olecli32_ordinal700 TEXTEQU <__imp_olecli32_ordinal700>
extern __imp_ErrShow:PANYARGS
ErrShow TEXTEQU <__imp_ErrShow>
extern __imp_ErrSetData:PANYARGS
ErrSetData TEXTEQU <__imp_ErrSetData>
extern __imp_ErrSetHostNames:PANYARGS
ErrSetHostNames TEXTEQU <__imp_ErrSetHostNames>
extern __imp_ErrSetTargetDevice:PANYARGS
ErrSetTargetDevice TEXTEQU <__imp_ErrSetTargetDevice>
extern __imp_ErrSetBounds:PANYARGS
ErrSetBounds TEXTEQU <__imp_ErrSetBounds>
extern __imp_ErrCopyFromLink:PANYARGS
ErrCopyFromLink TEXTEQU <__imp_ErrCopyFromLink>
extern __imp_ErrQueryOpen:PANYARGS
ErrQueryOpen TEXTEQU <__imp_ErrQueryOpen>
extern __imp_ErrActivate:PANYARGS
ErrActivate TEXTEQU <__imp_ErrActivate>
extern __imp_ErrClose:PANYARGS
ErrClose TEXTEQU <__imp_ErrClose>
extern __imp_ErrUpdate:PANYARGS
ErrUpdate TEXTEQU <__imp_ErrUpdate>
extern __imp_ErrReconnect:PANYARGS
ErrReconnect TEXTEQU <__imp_ErrReconnect>
extern __imp_ErrQueryProtocol:PANYARGS
ErrQueryProtocol TEXTEQU <__imp_ErrQueryProtocol>
extern __imp_ErrQueryOutOfDate:PANYARGS
ErrQueryOutOfDate TEXTEQU <__imp_ErrQueryOutOfDate>
extern __imp_ErrObjectConvert:PANYARGS
ErrObjectConvert TEXTEQU <__imp_ErrObjectConvert>
extern __imp_ErrGetUpdateOptions:PANYARGS
ErrGetUpdateOptions TEXTEQU <__imp_ErrGetUpdateOptions>
extern __imp_ErrSetUpdateOptions:PANYARGS
ErrSetUpdateOptions TEXTEQU <__imp_ErrSetUpdateOptions>
extern __imp_ErrExecute:PANYARGS
ErrExecute TEXTEQU <__imp_ErrExecute>
extern __imp_ErrObjectLong:PANYARGS
ErrObjectLong TEXTEQU <__imp_ErrObjectLong>
extern __imp_olecli32_ordinal719:PANYARGS
olecli32_ordinal719 TEXTEQU <__imp_olecli32_ordinal719>
extern __imp_olecli32_ordinal720:PANYARGS
olecli32_ordinal720 TEXTEQU <__imp_olecli32_ordinal720>
extern __imp_olecli32_ordinal721:PANYARGS
olecli32_ordinal721 TEXTEQU <__imp_olecli32_ordinal721>
extern __imp_olecli32_ordinal722:PANYARGS
olecli32_ordinal722 TEXTEQU <__imp_olecli32_ordinal722>
extern __imp_olecli32_ordinal723:PANYARGS
olecli32_ordinal723 TEXTEQU <__imp_olecli32_ordinal723>
extern __imp_olecli32_ordinal724:PANYARGS
olecli32_ordinal724 TEXTEQU <__imp_olecli32_ordinal724>
extern __imp_olecli32_ordinal725:PANYARGS
olecli32_ordinal725 TEXTEQU <__imp_olecli32_ordinal725>
extern __imp_olecli32_ordinal726:PANYARGS
olecli32_ordinal726 TEXTEQU <__imp_olecli32_ordinal726>
extern __imp_olecli32_ordinal727:PANYARGS
olecli32_ordinal727 TEXTEQU <__imp_olecli32_ordinal727>
extern __imp_olecli32_ordinal728:PANYARGS
olecli32_ordinal728 TEXTEQU <__imp_olecli32_ordinal728>
extern __imp_olecli32_ordinal729:PANYARGS
olecli32_ordinal729 TEXTEQU <__imp_olecli32_ordinal729>
extern __imp_olecli32_ordinal730:PANYARGS
olecli32_ordinal730 TEXTEQU <__imp_olecli32_ordinal730>
extern __imp_olecli32_ordinal731:PANYARGS
olecli32_ordinal731 TEXTEQU <__imp_olecli32_ordinal731>
extern __imp_olecli32_ordinal732:PANYARGS
olecli32_ordinal732 TEXTEQU <__imp_olecli32_ordinal732>
extern __imp_olecli32_ordinal733:PANYARGS
olecli32_ordinal733 TEXTEQU <__imp_olecli32_ordinal733>
extern __imp_olecli32_ordinal734:PANYARGS
olecli32_ordinal734 TEXTEQU <__imp_olecli32_ordinal734>
extern __imp_olecli32_ordinal735:PANYARGS
olecli32_ordinal735 TEXTEQU <__imp_olecli32_ordinal735>
extern __imp_olecli32_ordinal736:PANYARGS
olecli32_ordinal736 TEXTEQU <__imp_olecli32_ordinal736>
extern __imp_olecli32_ordinal737:PANYARGS
olecli32_ordinal737 TEXTEQU <__imp_olecli32_ordinal737>
extern __imp_olecli32_ordinal738:PANYARGS
olecli32_ordinal738 TEXTEQU <__imp_olecli32_ordinal738>
extern __imp_olecli32_ordinal739:PANYARGS
olecli32_ordinal739 TEXTEQU <__imp_olecli32_ordinal739>
extern __imp_olecli32_ordinal740:PANYARGS
olecli32_ordinal740 TEXTEQU <__imp_olecli32_ordinal740>
extern __imp_olecli32_ordinal741:PANYARGS
olecli32_ordinal741 TEXTEQU <__imp_olecli32_ordinal741>
extern __imp_olecli32_ordinal742:PANYARGS
olecli32_ordinal742 TEXTEQU <__imp_olecli32_ordinal742>
extern __imp_olecli32_ordinal743:PANYARGS
olecli32_ordinal743 TEXTEQU <__imp_olecli32_ordinal743>
extern __imp_olecli32_ordinal744:PANYARGS
olecli32_ordinal744 TEXTEQU <__imp_olecli32_ordinal744>
extern __imp_olecli32_ordinal745:PANYARGS
olecli32_ordinal745 TEXTEQU <__imp_olecli32_ordinal745>
extern __imp_olecli32_ordinal746:PANYARGS
olecli32_ordinal746 TEXTEQU <__imp_olecli32_ordinal746>
extern __imp_olecli32_ordinal747:PANYARGS
olecli32_ordinal747 TEXTEQU <__imp_olecli32_ordinal747>
extern __imp_olecli32_ordinal748:PANYARGS
olecli32_ordinal748 TEXTEQU <__imp_olecli32_ordinal748>
extern __imp_olecli32_ordinal749:PANYARGS
olecli32_ordinal749 TEXTEQU <__imp_olecli32_ordinal749>
extern __imp_olecli32_ordinal750:PANYARGS
olecli32_ordinal750 TEXTEQU <__imp_olecli32_ordinal750>
extern __imp_olecli32_ordinal751:PANYARGS
olecli32_ordinal751 TEXTEQU <__imp_olecli32_ordinal751>
extern __imp_olecli32_ordinal752:PANYARGS
olecli32_ordinal752 TEXTEQU <__imp_olecli32_ordinal752>
extern __imp_olecli32_ordinal753:PANYARGS
olecli32_ordinal753 TEXTEQU <__imp_olecli32_ordinal753>
extern __imp_olecli32_ordinal754:PANYARGS
olecli32_ordinal754 TEXTEQU <__imp_olecli32_ordinal754>
extern __imp_olecli32_ordinal755:PANYARGS
olecli32_ordinal755 TEXTEQU <__imp_olecli32_ordinal755>
extern __imp_olecli32_ordinal756:PANYARGS
olecli32_ordinal756 TEXTEQU <__imp_olecli32_ordinal756>
extern __imp_olecli32_ordinal757:PANYARGS
olecli32_ordinal757 TEXTEQU <__imp_olecli32_ordinal757>
extern __imp_olecli32_ordinal758:PANYARGS
olecli32_ordinal758 TEXTEQU <__imp_olecli32_ordinal758>
extern __imp_olecli32_ordinal759:PANYARGS
olecli32_ordinal759 TEXTEQU <__imp_olecli32_ordinal759>
extern __imp_olecli32_ordinal760:PANYARGS
olecli32_ordinal760 TEXTEQU <__imp_olecli32_ordinal760>
extern __imp_olecli32_ordinal761:PANYARGS
olecli32_ordinal761 TEXTEQU <__imp_olecli32_ordinal761>
extern __imp_olecli32_ordinal762:PANYARGS
olecli32_ordinal762 TEXTEQU <__imp_olecli32_ordinal762>
extern __imp_olecli32_ordinal763:PANYARGS
olecli32_ordinal763 TEXTEQU <__imp_olecli32_ordinal763>
extern __imp_olecli32_ordinal764:PANYARGS
olecli32_ordinal764 TEXTEQU <__imp_olecli32_ordinal764>
extern __imp_olecli32_ordinal765:PANYARGS
olecli32_ordinal765 TEXTEQU <__imp_olecli32_ordinal765>
extern __imp_olecli32_ordinal766:PANYARGS
olecli32_ordinal766 TEXTEQU <__imp_olecli32_ordinal766>
extern __imp_olecli32_ordinal767:PANYARGS
olecli32_ordinal767 TEXTEQU <__imp_olecli32_ordinal767>
extern __imp_olecli32_ordinal768:PANYARGS
olecli32_ordinal768 TEXTEQU <__imp_olecli32_ordinal768>
extern __imp_olecli32_ordinal769:PANYARGS
olecli32_ordinal769 TEXTEQU <__imp_olecli32_ordinal769>
extern __imp_olecli32_ordinal770:PANYARGS
olecli32_ordinal770 TEXTEQU <__imp_olecli32_ordinal770>
extern __imp_olecli32_ordinal771:PANYARGS
olecli32_ordinal771 TEXTEQU <__imp_olecli32_ordinal771>
extern __imp_olecli32_ordinal772:PANYARGS
olecli32_ordinal772 TEXTEQU <__imp_olecli32_ordinal772>
extern __imp_olecli32_ordinal773:PANYARGS
olecli32_ordinal773 TEXTEQU <__imp_olecli32_ordinal773>
extern __imp_olecli32_ordinal774:PANYARGS
olecli32_ordinal774 TEXTEQU <__imp_olecli32_ordinal774>
extern __imp_olecli32_ordinal775:PANYARGS
olecli32_ordinal775 TEXTEQU <__imp_olecli32_ordinal775>
extern __imp_olecli32_ordinal776:PANYARGS
olecli32_ordinal776 TEXTEQU <__imp_olecli32_ordinal776>
extern __imp_olecli32_ordinal777:PANYARGS
olecli32_ordinal777 TEXTEQU <__imp_olecli32_ordinal777>
extern __imp_olecli32_ordinal778:PANYARGS
olecli32_ordinal778 TEXTEQU <__imp_olecli32_ordinal778>
extern __imp_olecli32_ordinal779:PANYARGS
olecli32_ordinal779 TEXTEQU <__imp_olecli32_ordinal779>
extern __imp_olecli32_ordinal780:PANYARGS
olecli32_ordinal780 TEXTEQU <__imp_olecli32_ordinal780>
extern __imp_olecli32_ordinal781:PANYARGS
olecli32_ordinal781 TEXTEQU <__imp_olecli32_ordinal781>
extern __imp_olecli32_ordinal782:PANYARGS
olecli32_ordinal782 TEXTEQU <__imp_olecli32_ordinal782>
extern __imp_olecli32_ordinal783:PANYARGS
olecli32_ordinal783 TEXTEQU <__imp_olecli32_ordinal783>
extern __imp_olecli32_ordinal784:PANYARGS
olecli32_ordinal784 TEXTEQU <__imp_olecli32_ordinal784>
extern __imp_olecli32_ordinal785:PANYARGS
olecli32_ordinal785 TEXTEQU <__imp_olecli32_ordinal785>
extern __imp_olecli32_ordinal786:PANYARGS
olecli32_ordinal786 TEXTEQU <__imp_olecli32_ordinal786>
extern __imp_olecli32_ordinal787:PANYARGS
olecli32_ordinal787 TEXTEQU <__imp_olecli32_ordinal787>
extern __imp_olecli32_ordinal788:PANYARGS
olecli32_ordinal788 TEXTEQU <__imp_olecli32_ordinal788>
extern __imp_olecli32_ordinal789:PANYARGS
olecli32_ordinal789 TEXTEQU <__imp_olecli32_ordinal789>
extern __imp_olecli32_ordinal790:PANYARGS
olecli32_ordinal790 TEXTEQU <__imp_olecli32_ordinal790>
extern __imp_olecli32_ordinal791:PANYARGS
olecli32_ordinal791 TEXTEQU <__imp_olecli32_ordinal791>
extern __imp_olecli32_ordinal792:PANYARGS
olecli32_ordinal792 TEXTEQU <__imp_olecli32_ordinal792>
extern __imp_olecli32_ordinal793:PANYARGS
olecli32_ordinal793 TEXTEQU <__imp_olecli32_ordinal793>
extern __imp_olecli32_ordinal794:PANYARGS
olecli32_ordinal794 TEXTEQU <__imp_olecli32_ordinal794>
extern __imp_olecli32_ordinal795:PANYARGS
olecli32_ordinal795 TEXTEQU <__imp_olecli32_ordinal795>
extern __imp_olecli32_ordinal796:PANYARGS
olecli32_ordinal796 TEXTEQU <__imp_olecli32_ordinal796>
extern __imp_olecli32_ordinal797:PANYARGS
olecli32_ordinal797 TEXTEQU <__imp_olecli32_ordinal797>
extern __imp_olecli32_ordinal798:PANYARGS
olecli32_ordinal798 TEXTEQU <__imp_olecli32_ordinal798>
extern __imp_olecli32_ordinal799:PANYARGS
olecli32_ordinal799 TEXTEQU <__imp_olecli32_ordinal799>
extern __imp_PbLoadFromStream:PANYARGS
PbLoadFromStream TEXTEQU <__imp_PbLoadFromStream>
extern __imp_PbCreateFromClip:PANYARGS
PbCreateFromClip TEXTEQU <__imp_PbCreateFromClip>
extern __imp_PbCreateLinkFromClip:PANYARGS
PbCreateLinkFromClip TEXTEQU <__imp_PbCreateLinkFromClip>
extern __imp_PbCreateFromTemplate:PANYARGS
PbCreateFromTemplate TEXTEQU <__imp_PbCreateFromTemplate>
extern __imp_PbCreate:PANYARGS
PbCreate TEXTEQU <__imp_PbCreate>
extern __imp_PbDraw:PANYARGS
PbDraw TEXTEQU <__imp_PbDraw>
extern __imp_PbQueryBounds:PANYARGS
PbQueryBounds TEXTEQU <__imp_PbQueryBounds>
extern __imp_PbCopyToClipboard:PANYARGS
PbCopyToClipboard TEXTEQU <__imp_PbCopyToClipboard>
extern __imp_PbCreateFromFile:PANYARGS
PbCreateFromFile TEXTEQU <__imp_PbCreateFromFile>
extern __imp_PbCreateLinkFromFile:PANYARGS
PbCreateLinkFromFile TEXTEQU <__imp_PbCreateLinkFromFile>
extern __imp_PbEnumFormats:PANYARGS
PbEnumFormats TEXTEQU <__imp_PbEnumFormats>
extern __imp_PbGetData:PANYARGS
PbGetData TEXTEQU <__imp_PbGetData>
extern __imp_PbCreateInvisible:PANYARGS
PbCreateInvisible TEXTEQU <__imp_PbCreateInvisible>
extern __imp_olecli32_ordinal813:PANYARGS
olecli32_ordinal813 TEXTEQU <__imp_olecli32_ordinal813>
extern __imp_olecli32_ordinal814:PANYARGS
olecli32_ordinal814 TEXTEQU <__imp_olecli32_ordinal814>
extern __imp_olecli32_ordinal815:PANYARGS
olecli32_ordinal815 TEXTEQU <__imp_olecli32_ordinal815>
extern __imp_olecli32_ordinal816:PANYARGS
olecli32_ordinal816 TEXTEQU <__imp_olecli32_ordinal816>
extern __imp_olecli32_ordinal817:PANYARGS
olecli32_ordinal817 TEXTEQU <__imp_olecli32_ordinal817>
extern __imp_olecli32_ordinal818:PANYARGS
olecli32_ordinal818 TEXTEQU <__imp_olecli32_ordinal818>
extern __imp_olecli32_ordinal819:PANYARGS
olecli32_ordinal819 TEXTEQU <__imp_olecli32_ordinal819>
extern __imp_olecli32_ordinal820:PANYARGS
olecli32_ordinal820 TEXTEQU <__imp_olecli32_ordinal820>
extern __imp_olecli32_ordinal821:PANYARGS
olecli32_ordinal821 TEXTEQU <__imp_olecli32_ordinal821>
extern __imp_olecli32_ordinal822:PANYARGS
olecli32_ordinal822 TEXTEQU <__imp_olecli32_ordinal822>
extern __imp_olecli32_ordinal823:PANYARGS
olecli32_ordinal823 TEXTEQU <__imp_olecli32_ordinal823>
extern __imp_olecli32_ordinal824:PANYARGS
olecli32_ordinal824 TEXTEQU <__imp_olecli32_ordinal824>
extern __imp_olecli32_ordinal825:PANYARGS
olecli32_ordinal825 TEXTEQU <__imp_olecli32_ordinal825>
extern __imp_olecli32_ordinal826:PANYARGS
olecli32_ordinal826 TEXTEQU <__imp_olecli32_ordinal826>
extern __imp_olecli32_ordinal827:PANYARGS
olecli32_ordinal827 TEXTEQU <__imp_olecli32_ordinal827>
extern __imp_olecli32_ordinal828:PANYARGS
olecli32_ordinal828 TEXTEQU <__imp_olecli32_ordinal828>
extern __imp_olecli32_ordinal829:PANYARGS
olecli32_ordinal829 TEXTEQU <__imp_olecli32_ordinal829>
extern __imp_olecli32_ordinal830:PANYARGS
olecli32_ordinal830 TEXTEQU <__imp_olecli32_ordinal830>
extern __imp_olecli32_ordinal831:PANYARGS
olecli32_ordinal831 TEXTEQU <__imp_olecli32_ordinal831>
extern __imp_olecli32_ordinal832:PANYARGS
olecli32_ordinal832 TEXTEQU <__imp_olecli32_ordinal832>
extern __imp_olecli32_ordinal833:PANYARGS
olecli32_ordinal833 TEXTEQU <__imp_olecli32_ordinal833>
extern __imp_olecli32_ordinal834:PANYARGS
olecli32_ordinal834 TEXTEQU <__imp_olecli32_ordinal834>
extern __imp_olecli32_ordinal835:PANYARGS
olecli32_ordinal835 TEXTEQU <__imp_olecli32_ordinal835>
extern __imp_olecli32_ordinal836:PANYARGS
olecli32_ordinal836 TEXTEQU <__imp_olecli32_ordinal836>
extern __imp_olecli32_ordinal837:PANYARGS
olecli32_ordinal837 TEXTEQU <__imp_olecli32_ordinal837>
extern __imp_olecli32_ordinal838:PANYARGS
olecli32_ordinal838 TEXTEQU <__imp_olecli32_ordinal838>
extern __imp_olecli32_ordinal839:PANYARGS
olecli32_ordinal839 TEXTEQU <__imp_olecli32_ordinal839>
extern __imp_olecli32_ordinal840:PANYARGS
olecli32_ordinal840 TEXTEQU <__imp_olecli32_ordinal840>
extern __imp_olecli32_ordinal841:PANYARGS
olecli32_ordinal841 TEXTEQU <__imp_olecli32_ordinal841>
extern __imp_olecli32_ordinal842:PANYARGS
olecli32_ordinal842 TEXTEQU <__imp_olecli32_ordinal842>
extern __imp_olecli32_ordinal843:PANYARGS
olecli32_ordinal843 TEXTEQU <__imp_olecli32_ordinal843>
extern __imp_olecli32_ordinal844:PANYARGS
olecli32_ordinal844 TEXTEQU <__imp_olecli32_ordinal844>
extern __imp_olecli32_ordinal845:PANYARGS
olecli32_ordinal845 TEXTEQU <__imp_olecli32_ordinal845>
extern __imp_olecli32_ordinal846:PANYARGS
olecli32_ordinal846 TEXTEQU <__imp_olecli32_ordinal846>
extern __imp_olecli32_ordinal847:PANYARGS
olecli32_ordinal847 TEXTEQU <__imp_olecli32_ordinal847>
extern __imp_olecli32_ordinal848:PANYARGS
olecli32_ordinal848 TEXTEQU <__imp_olecli32_ordinal848>
extern __imp_olecli32_ordinal849:PANYARGS
olecli32_ordinal849 TEXTEQU <__imp_olecli32_ordinal849>
extern __imp_olecli32_ordinal850:PANYARGS
olecli32_ordinal850 TEXTEQU <__imp_olecli32_ordinal850>
extern __imp_olecli32_ordinal851:PANYARGS
olecli32_ordinal851 TEXTEQU <__imp_olecli32_ordinal851>
extern __imp_olecli32_ordinal852:PANYARGS
olecli32_ordinal852 TEXTEQU <__imp_olecli32_ordinal852>
extern __imp_olecli32_ordinal853:PANYARGS
olecli32_ordinal853 TEXTEQU <__imp_olecli32_ordinal853>
extern __imp_olecli32_ordinal854:PANYARGS
olecli32_ordinal854 TEXTEQU <__imp_olecli32_ordinal854>
extern __imp_olecli32_ordinal855:PANYARGS
olecli32_ordinal855 TEXTEQU <__imp_olecli32_ordinal855>
extern __imp_olecli32_ordinal856:PANYARGS
olecli32_ordinal856 TEXTEQU <__imp_olecli32_ordinal856>
extern __imp_olecli32_ordinal857:PANYARGS
olecli32_ordinal857 TEXTEQU <__imp_olecli32_ordinal857>
extern __imp_olecli32_ordinal858:PANYARGS
olecli32_ordinal858 TEXTEQU <__imp_olecli32_ordinal858>
extern __imp_olecli32_ordinal859:PANYARGS
olecli32_ordinal859 TEXTEQU <__imp_olecli32_ordinal859>
extern __imp_olecli32_ordinal860:PANYARGS
olecli32_ordinal860 TEXTEQU <__imp_olecli32_ordinal860>
extern __imp_olecli32_ordinal861:PANYARGS
olecli32_ordinal861 TEXTEQU <__imp_olecli32_ordinal861>
extern __imp_olecli32_ordinal862:PANYARGS
olecli32_ordinal862 TEXTEQU <__imp_olecli32_ordinal862>
extern __imp_olecli32_ordinal863:PANYARGS
olecli32_ordinal863 TEXTEQU <__imp_olecli32_ordinal863>
extern __imp_olecli32_ordinal864:PANYARGS
olecli32_ordinal864 TEXTEQU <__imp_olecli32_ordinal864>
extern __imp_olecli32_ordinal865:PANYARGS
olecli32_ordinal865 TEXTEQU <__imp_olecli32_ordinal865>
extern __imp_olecli32_ordinal866:PANYARGS
olecli32_ordinal866 TEXTEQU <__imp_olecli32_ordinal866>
extern __imp_olecli32_ordinal867:PANYARGS
olecli32_ordinal867 TEXTEQU <__imp_olecli32_ordinal867>
extern __imp_olecli32_ordinal868:PANYARGS
olecli32_ordinal868 TEXTEQU <__imp_olecli32_ordinal868>
extern __imp_olecli32_ordinal869:PANYARGS
olecli32_ordinal869 TEXTEQU <__imp_olecli32_ordinal869>
extern __imp_olecli32_ordinal870:PANYARGS
olecli32_ordinal870 TEXTEQU <__imp_olecli32_ordinal870>
extern __imp_olecli32_ordinal871:PANYARGS
olecli32_ordinal871 TEXTEQU <__imp_olecli32_ordinal871>
extern __imp_olecli32_ordinal872:PANYARGS
olecli32_ordinal872 TEXTEQU <__imp_olecli32_ordinal872>
extern __imp_olecli32_ordinal873:PANYARGS
olecli32_ordinal873 TEXTEQU <__imp_olecli32_ordinal873>
extern __imp_olecli32_ordinal874:PANYARGS
olecli32_ordinal874 TEXTEQU <__imp_olecli32_ordinal874>
extern __imp_olecli32_ordinal875:PANYARGS
olecli32_ordinal875 TEXTEQU <__imp_olecli32_ordinal875>
extern __imp_olecli32_ordinal876:PANYARGS
olecli32_ordinal876 TEXTEQU <__imp_olecli32_ordinal876>
extern __imp_olecli32_ordinal877:PANYARGS
olecli32_ordinal877 TEXTEQU <__imp_olecli32_ordinal877>
extern __imp_olecli32_ordinal878:PANYARGS
olecli32_ordinal878 TEXTEQU <__imp_olecli32_ordinal878>
extern __imp_olecli32_ordinal879:PANYARGS
olecli32_ordinal879 TEXTEQU <__imp_olecli32_ordinal879>
extern __imp_olecli32_ordinal880:PANYARGS
olecli32_ordinal880 TEXTEQU <__imp_olecli32_ordinal880>
extern __imp_olecli32_ordinal881:PANYARGS
olecli32_ordinal881 TEXTEQU <__imp_olecli32_ordinal881>
extern __imp_olecli32_ordinal882:PANYARGS
olecli32_ordinal882 TEXTEQU <__imp_olecli32_ordinal882>
extern __imp_olecli32_ordinal883:PANYARGS
olecli32_ordinal883 TEXTEQU <__imp_olecli32_ordinal883>
extern __imp_olecli32_ordinal884:PANYARGS
olecli32_ordinal884 TEXTEQU <__imp_olecli32_ordinal884>
extern __imp_olecli32_ordinal885:PANYARGS
olecli32_ordinal885 TEXTEQU <__imp_olecli32_ordinal885>
extern __imp_olecli32_ordinal886:PANYARGS
olecli32_ordinal886 TEXTEQU <__imp_olecli32_ordinal886>
extern __imp_olecli32_ordinal887:PANYARGS
olecli32_ordinal887 TEXTEQU <__imp_olecli32_ordinal887>
extern __imp_olecli32_ordinal888:PANYARGS
olecli32_ordinal888 TEXTEQU <__imp_olecli32_ordinal888>
extern __imp_olecli32_ordinal889:PANYARGS
olecli32_ordinal889 TEXTEQU <__imp_olecli32_ordinal889>
extern __imp_olecli32_ordinal890:PANYARGS
olecli32_ordinal890 TEXTEQU <__imp_olecli32_ordinal890>
extern __imp_olecli32_ordinal891:PANYARGS
olecli32_ordinal891 TEXTEQU <__imp_olecli32_ordinal891>
extern __imp_olecli32_ordinal892:PANYARGS
olecli32_ordinal892 TEXTEQU <__imp_olecli32_ordinal892>
extern __imp_olecli32_ordinal893:PANYARGS
olecli32_ordinal893 TEXTEQU <__imp_olecli32_ordinal893>
extern __imp_olecli32_ordinal894:PANYARGS
olecli32_ordinal894 TEXTEQU <__imp_olecli32_ordinal894>
extern __imp_olecli32_ordinal895:PANYARGS
olecli32_ordinal895 TEXTEQU <__imp_olecli32_ordinal895>
extern __imp_olecli32_ordinal896:PANYARGS
olecli32_ordinal896 TEXTEQU <__imp_olecli32_ordinal896>
extern __imp_olecli32_ordinal897:PANYARGS
olecli32_ordinal897 TEXTEQU <__imp_olecli32_ordinal897>
extern __imp_olecli32_ordinal898:PANYARGS
olecli32_ordinal898 TEXTEQU <__imp_olecli32_ordinal898>
extern __imp_olecli32_ordinal899:PANYARGS
olecli32_ordinal899 TEXTEQU <__imp_olecli32_ordinal899>
extern __imp_olecli32_ordinal900:PANYARGS
olecli32_ordinal900 TEXTEQU <__imp_olecli32_ordinal900>
extern __imp_olecli32_ordinal901:PANYARGS
olecli32_ordinal901 TEXTEQU <__imp_olecli32_ordinal901>
extern __imp_olecli32_ordinal902:PANYARGS
olecli32_ordinal902 TEXTEQU <__imp_olecli32_ordinal902>
extern __imp_olecli32_ordinal903:PANYARGS
olecli32_ordinal903 TEXTEQU <__imp_olecli32_ordinal903>
extern __imp_olecli32_ordinal904:PANYARGS
olecli32_ordinal904 TEXTEQU <__imp_olecli32_ordinal904>
extern __imp_olecli32_ordinal905:PANYARGS
olecli32_ordinal905 TEXTEQU <__imp_olecli32_ordinal905>
extern __imp_olecli32_ordinal906:PANYARGS
olecli32_ordinal906 TEXTEQU <__imp_olecli32_ordinal906>
extern __imp_olecli32_ordinal907:PANYARGS
olecli32_ordinal907 TEXTEQU <__imp_olecli32_ordinal907>
extern __imp_olecli32_ordinal908:PANYARGS
olecli32_ordinal908 TEXTEQU <__imp_olecli32_ordinal908>
extern __imp_olecli32_ordinal909:PANYARGS
olecli32_ordinal909 TEXTEQU <__imp_olecli32_ordinal909>
extern __imp_ObjQueryName:PANYARGS
ObjQueryName TEXTEQU <__imp_ObjQueryName>
extern __imp_ObjRename:PANYARGS
ObjRename TEXTEQU <__imp_ObjRename>
extern __imp_ObjQueryType:PANYARGS
ObjQueryType TEXTEQU <__imp_ObjQueryType>
extern __imp_ObjQuerySize:PANYARGS
ObjQuerySize TEXTEQU <__imp_ObjQuerySize>
extern __imp_olecli32_ordinal914:PANYARGS
olecli32_ordinal914 TEXTEQU <__imp_olecli32_ordinal914>
extern __imp_olecli32_ordinal915:PANYARGS
olecli32_ordinal915 TEXTEQU <__imp_olecli32_ordinal915>
extern __imp_olecli32_ordinal916:PANYARGS
olecli32_ordinal916 TEXTEQU <__imp_olecli32_ordinal916>
extern __imp_olecli32_ordinal917:PANYARGS
olecli32_ordinal917 TEXTEQU <__imp_olecli32_ordinal917>
extern __imp_olecli32_ordinal918:PANYARGS
olecli32_ordinal918 TEXTEQU <__imp_olecli32_ordinal918>
extern __imp_olecli32_ordinal919:PANYARGS
olecli32_ordinal919 TEXTEQU <__imp_olecli32_ordinal919>
extern __imp_olecli32_ordinal920:PANYARGS
olecli32_ordinal920 TEXTEQU <__imp_olecli32_ordinal920>
extern __imp_olecli32_ordinal921:PANYARGS
olecli32_ordinal921 TEXTEQU <__imp_olecli32_ordinal921>
extern __imp_olecli32_ordinal922:PANYARGS
olecli32_ordinal922 TEXTEQU <__imp_olecli32_ordinal922>
extern __imp_olecli32_ordinal923:PANYARGS
olecli32_ordinal923 TEXTEQU <__imp_olecli32_ordinal923>
extern __imp_olecli32_ordinal924:PANYARGS
olecli32_ordinal924 TEXTEQU <__imp_olecli32_ordinal924>
extern __imp_olecli32_ordinal925:PANYARGS
olecli32_ordinal925 TEXTEQU <__imp_olecli32_ordinal925>
extern __imp_olecli32_ordinal926:PANYARGS
olecli32_ordinal926 TEXTEQU <__imp_olecli32_ordinal926>
extern __imp_olecli32_ordinal927:PANYARGS
olecli32_ordinal927 TEXTEQU <__imp_olecli32_ordinal927>
extern __imp_olecli32_ordinal928:PANYARGS
olecli32_ordinal928 TEXTEQU <__imp_olecli32_ordinal928>
extern __imp_olecli32_ordinal929:PANYARGS
olecli32_ordinal929 TEXTEQU <__imp_olecli32_ordinal929>
extern __imp_olecli32_ordinal930:PANYARGS
olecli32_ordinal930 TEXTEQU <__imp_olecli32_ordinal930>
extern __imp_olecli32_ordinal931:PANYARGS
olecli32_ordinal931 TEXTEQU <__imp_olecli32_ordinal931>
extern __imp_olecli32_ordinal932:PANYARGS
olecli32_ordinal932 TEXTEQU <__imp_olecli32_ordinal932>
extern __imp_olecli32_ordinal933:PANYARGS
olecli32_ordinal933 TEXTEQU <__imp_olecli32_ordinal933>
extern __imp_olecli32_ordinal934:PANYARGS
olecli32_ordinal934 TEXTEQU <__imp_olecli32_ordinal934>
extern __imp_olecli32_ordinal935:PANYARGS
olecli32_ordinal935 TEXTEQU <__imp_olecli32_ordinal935>
extern __imp_olecli32_ordinal936:PANYARGS
olecli32_ordinal936 TEXTEQU <__imp_olecli32_ordinal936>
extern __imp_olecli32_ordinal937:PANYARGS
olecli32_ordinal937 TEXTEQU <__imp_olecli32_ordinal937>
extern __imp_olecli32_ordinal938:PANYARGS
olecli32_ordinal938 TEXTEQU <__imp_olecli32_ordinal938>
extern __imp_olecli32_ordinal939:PANYARGS
olecli32_ordinal939 TEXTEQU <__imp_olecli32_ordinal939>
extern __imp_olecli32_ordinal940:PANYARGS
olecli32_ordinal940 TEXTEQU <__imp_olecli32_ordinal940>
extern __imp_olecli32_ordinal941:PANYARGS
olecli32_ordinal941 TEXTEQU <__imp_olecli32_ordinal941>
extern __imp_olecli32_ordinal942:PANYARGS
olecli32_ordinal942 TEXTEQU <__imp_olecli32_ordinal942>
extern __imp_olecli32_ordinal943:PANYARGS
olecli32_ordinal943 TEXTEQU <__imp_olecli32_ordinal943>
extern __imp_olecli32_ordinal944:PANYARGS
olecli32_ordinal944 TEXTEQU <__imp_olecli32_ordinal944>
extern __imp_olecli32_ordinal945:PANYARGS
olecli32_ordinal945 TEXTEQU <__imp_olecli32_ordinal945>
extern __imp_olecli32_ordinal946:PANYARGS
olecli32_ordinal946 TEXTEQU <__imp_olecli32_ordinal946>
extern __imp_olecli32_ordinal947:PANYARGS
olecli32_ordinal947 TEXTEQU <__imp_olecli32_ordinal947>
extern __imp_olecli32_ordinal948:PANYARGS
olecli32_ordinal948 TEXTEQU <__imp_olecli32_ordinal948>
extern __imp_olecli32_ordinal949:PANYARGS
olecli32_ordinal949 TEXTEQU <__imp_olecli32_ordinal949>
extern __imp_ConnectDlgProc:PANYARGS
ConnectDlgProc TEXTEQU <__imp_ConnectDlgProc>
extern __imp_SetNetName:PANYARGS
SetNetName TEXTEQU <__imp_SetNetName>
extern __imp_CheckNetDrive:PANYARGS
CheckNetDrive TEXTEQU <__imp_CheckNetDrive>
extern __imp_SetNextNetDrive:PANYARGS
SetNextNetDrive TEXTEQU <__imp_SetNextNetDrive>
extern __imp_GetTaskVisibleWindow:PANYARGS
GetTaskVisibleWindow TEXTEQU <__imp_GetTaskVisibleWindow>
