extern __imp_OleUIAddVerbMenuA:PANYARGS
OleUIAddVerbMenu  TEXTEQU <__imp_OleUIAddVerbMenuA>
extern __imp_OleUICanConvertOrActivateAs:PANYARGS
OleUICanConvertOrActivateAs TEXTEQU <__imp_OleUICanConvertOrActivateAs>
extern __imp_OleUIInsertObjectA:PANYARGS
OleUIInsertObject  TEXTEQU <__imp_OleUIInsertObjectA>
extern __imp_OleUIPasteSpecialA:PANYARGS
OleUIPasteSpecial  TEXTEQU <__imp_OleUIPasteSpecialA>
extern __imp_OleUIEditLinksA:PANYARGS
OleUIEditLinks  TEXTEQU <__imp_OleUIEditLinksA>
extern __imp_OleUIChangeIconA:PANYARGS
OleUIChangeIcon  TEXTEQU <__imp_OleUIChangeIconA>
extern __imp_OleUIConvertA:PANYARGS
OleUIConvert  TEXTEQU <__imp_OleUIConvertA>
extern __imp_OleUIBusyA:PANYARGS
OleUIBusy  TEXTEQU <__imp_OleUIBusyA>
extern __imp_OleUIUpdateLinksA:PANYARGS
OleUIUpdateLinks  TEXTEQU <__imp_OleUIUpdateLinksA>
extern __imp_OleUIPromptUserA:PANYARGS
OleUIPromptUser  TEXTEQU <__imp_OleUIPromptUserA>
extern __imp_OleUIObjectPropertiesA:PANYARGS
OleUIObjectProperties  TEXTEQU <__imp_OleUIObjectPropertiesA>
extern __imp_OleUIChangeSourceA:PANYARGS
OleUIChangeSource  TEXTEQU <__imp_OleUIChangeSourceA>
extern __imp_OleUIAddVerbMenuW:PANYARGS
OleUIAddVerbMenuW TEXTEQU <__imp_OleUIAddVerbMenuW>
extern __imp_OleUIBusyW:PANYARGS
OleUIBusyW TEXTEQU <__imp_OleUIBusyW>
extern __imp_OleUIChangeIconW:PANYARGS
OleUIChangeIconW TEXTEQU <__imp_OleUIChangeIconW>
extern __imp_OleUIChangeSourceW:PANYARGS
OleUIChangeSourceW TEXTEQU <__imp_OleUIChangeSourceW>
extern __imp_OleUIConvertW:PANYARGS
OleUIConvertW TEXTEQU <__imp_OleUIConvertW>
extern __imp_OleUIEditLinksW:PANYARGS
OleUIEditLinksW TEXTEQU <__imp_OleUIEditLinksW>
extern __imp_OleUIInsertObjectW:PANYARGS
OleUIInsertObjectW TEXTEQU <__imp_OleUIInsertObjectW>
extern __imp_OleUIObjectPropertiesW:PANYARGS
OleUIObjectPropertiesW TEXTEQU <__imp_OleUIObjectPropertiesW>
extern __imp_OleUIPasteSpecialW:PANYARGS
OleUIPasteSpecialW TEXTEQU <__imp_OleUIPasteSpecialW>
extern __imp_OleUIPromptUserW:PANYARGS
OleUIPromptUserW TEXTEQU <__imp_OleUIPromptUserW>
extern __imp_OleUIUpdateLinksW:PANYARGS
OleUIUpdateLinksW TEXTEQU <__imp_OleUIUpdateLinksW>
