extern __imp_WEP:PANYARGS
WEP TEXTEQU <__imp_WEP>
extern __imp_OleRegisterServer:PANYARGS
OleRegisterServer TEXTEQU <__imp_OleRegisterServer>
extern __imp_OleRevokeServer:PANYARGS
OleRevokeServer TEXTEQU <__imp_OleRevokeServer>
extern __imp_OleBlockServer:PANYARGS
OleBlockServer TEXTEQU <__imp_OleBlockServer>
extern __imp_OleUnblockServer:PANYARGS
OleUnblockServer TEXTEQU <__imp_OleUnblockServer>
extern __imp_OleRegisterServerDoc:PANYARGS
OleRegisterServerDoc TEXTEQU <__imp_OleRegisterServerDoc>
extern __imp_OleRevokeServerDoc:PANYARGS
OleRevokeServerDoc TEXTEQU <__imp_OleRevokeServerDoc>
extern __imp_OleRenameServerDoc:PANYARGS
OleRenameServerDoc TEXTEQU <__imp_OleRenameServerDoc>
extern __imp_OleRevertServerDoc:PANYARGS
OleRevertServerDoc TEXTEQU <__imp_OleRevertServerDoc>
extern __imp_OleSavedServerDoc:PANYARGS
OleSavedServerDoc TEXTEQU <__imp_OleSavedServerDoc>
extern __imp_OleRevokeObject:PANYARGS
OleRevokeObject TEXTEQU <__imp_OleRevokeObject>
extern __imp_OleQueryServerVersion:PANYARGS
OleQueryServerVersion TEXTEQU <__imp_OleQueryServerVersion>
extern __imp_olesvr32_ordinal13:PANYARGS
olesvr32_ordinal13 TEXTEQU <__imp_olesvr32_ordinal13>
extern __imp_olesvr32_ordinal14:PANYARGS
olesvr32_ordinal14 TEXTEQU <__imp_olesvr32_ordinal14>
extern __imp_olesvr32_ordinal15:PANYARGS
olesvr32_ordinal15 TEXTEQU <__imp_olesvr32_ordinal15>
extern __imp_olesvr32_ordinal16:PANYARGS
olesvr32_ordinal16 TEXTEQU <__imp_olesvr32_ordinal16>
extern __imp_olesvr32_ordinal17:PANYARGS
olesvr32_ordinal17 TEXTEQU <__imp_olesvr32_ordinal17>
extern __imp_olesvr32_ordinal18:PANYARGS
olesvr32_ordinal18 TEXTEQU <__imp_olesvr32_ordinal18>
extern __imp_olesvr32_ordinal19:PANYARGS
olesvr32_ordinal19 TEXTEQU <__imp_olesvr32_ordinal19>
extern __imp_olesvr32_ordinal20:PANYARGS
olesvr32_ordinal20 TEXTEQU <__imp_olesvr32_ordinal20>
extern __imp_SrvrWndProc:PANYARGS
SrvrWndProc TEXTEQU <__imp_SrvrWndProc>
extern __imp_DocWndProc:PANYARGS
DocWndProc TEXTEQU <__imp_DocWndProc>
extern __imp_ItemWndProc:PANYARGS
ItemWndProc TEXTEQU <__imp_ItemWndProc>
extern __imp_SendDataMsg:PANYARGS
SendDataMsg TEXTEQU <__imp_SendDataMsg>
extern __imp_FindItemWnd:PANYARGS
FindItemWnd TEXTEQU <__imp_FindItemWnd>
extern __imp_ItemCallBack:PANYARGS
ItemCallBack TEXTEQU <__imp_ItemCallBack>
extern __imp_TerminateClients:PANYARGS
TerminateClients TEXTEQU <__imp_TerminateClients>
extern __imp_TerminateDocClients:PANYARGS
TerminateDocClients TEXTEQU <__imp_TerminateDocClients>
extern __imp_DeleteClientInfo:PANYARGS
DeleteClientInfo TEXTEQU <__imp_DeleteClientInfo>
extern __imp_SendRenameMsg:PANYARGS
SendRenameMsg TEXTEQU <__imp_SendRenameMsg>
extern __imp_EnumForTerminate:PANYARGS
EnumForTerminate TEXTEQU <__imp_EnumForTerminate>
