extern __imp_GlmfBeginGlsBlock:PANYARGS
GlmfBeginGlsBlock TEXTEQU <__imp_GlmfBeginGlsBlock>
extern __imp_GlmfCloseMetaFile:PANYARGS
GlmfCloseMetaFile TEXTEQU <__imp_GlmfCloseMetaFile>
extern __imp_GlmfEndGlsBlock:PANYARGS
GlmfEndGlsBlock TEXTEQU <__imp_GlmfEndGlsBlock>
extern __imp_GlmfEndPlayback:PANYARGS
GlmfEndPlayback TEXTEQU <__imp_GlmfEndPlayback>
extern __imp_GlmfInitPlayback:PANYARGS
GlmfInitPlayback TEXTEQU <__imp_GlmfInitPlayback>
extern __imp_GlmfPlayGlsRecord:PANYARGS
GlmfPlayGlsRecord TEXTEQU <__imp_GlmfPlayGlsRecord>
extern __imp_glAccum:PANYARGS
glAccum TEXTEQU <__imp_glAccum>
extern __imp_glAlphaFunc:PANYARGS
glAlphaFunc TEXTEQU <__imp_glAlphaFunc>
extern __imp_glAreTexturesResident:PANYARGS
glAreTexturesResident TEXTEQU <__imp_glAreTexturesResident>
extern __imp_glArrayElement:PANYARGS
glArrayElement TEXTEQU <__imp_glArrayElement>
extern __imp_glBegin:PANYARGS
glBegin TEXTEQU <__imp_glBegin>
extern __imp_glBindTexture:PANYARGS
glBindTexture TEXTEQU <__imp_glBindTexture>
extern __imp_glBitmap:PANYARGS
glBitmap TEXTEQU <__imp_glBitmap>
extern __imp_glBlendFunc:PANYARGS
glBlendFunc TEXTEQU <__imp_glBlendFunc>
extern __imp_glCallList:PANYARGS
glCallList TEXTEQU <__imp_glCallList>
extern __imp_glCallLists:PANYARGS
glCallLists TEXTEQU <__imp_glCallLists>
extern __imp_glClear:PANYARGS
glClear TEXTEQU <__imp_glClear>
extern __imp_glClearAccum:PANYARGS
glClearAccum TEXTEQU <__imp_glClearAccum>
extern __imp_glClearColor:PANYARGS
glClearColor TEXTEQU <__imp_glClearColor>
extern __imp_glClearDepth:PANYARGS
glClearDepth TEXTEQU <__imp_glClearDepth>
extern __imp_glClearIndex:PANYARGS
glClearIndex TEXTEQU <__imp_glClearIndex>
extern __imp_glClearStencil:PANYARGS
glClearStencil TEXTEQU <__imp_glClearStencil>
extern __imp_glClipPlane:PANYARGS
glClipPlane TEXTEQU <__imp_glClipPlane>
extern __imp_glColor3b:PANYARGS
glColor3b TEXTEQU <__imp_glColor3b>
extern __imp_glColor3bv:PANYARGS
glColor3bv TEXTEQU <__imp_glColor3bv>
extern __imp_glColor3d:PANYARGS
glColor3d TEXTEQU <__imp_glColor3d>
extern __imp_glColor3dv:PANYARGS
glColor3dv TEXTEQU <__imp_glColor3dv>
extern __imp_glColor3f:PANYARGS
glColor3f TEXTEQU <__imp_glColor3f>
extern __imp_glColor3fv:PANYARGS
glColor3fv TEXTEQU <__imp_glColor3fv>
extern __imp_glColor3i:PANYARGS
glColor3i TEXTEQU <__imp_glColor3i>
extern __imp_glColor3iv:PANYARGS
glColor3iv TEXTEQU <__imp_glColor3iv>
extern __imp_glColor3s:PANYARGS
glColor3s TEXTEQU <__imp_glColor3s>
extern __imp_glColor3sv:PANYARGS
glColor3sv TEXTEQU <__imp_glColor3sv>
extern __imp_glColor3ub:PANYARGS
glColor3ub TEXTEQU <__imp_glColor3ub>
extern __imp_glColor3ubv:PANYARGS
glColor3ubv TEXTEQU <__imp_glColor3ubv>
extern __imp_glColor3ui:PANYARGS
glColor3ui TEXTEQU <__imp_glColor3ui>
extern __imp_glColor3uiv:PANYARGS
glColor3uiv TEXTEQU <__imp_glColor3uiv>
extern __imp_glColor3us:PANYARGS
glColor3us TEXTEQU <__imp_glColor3us>
extern __imp_glColor3usv:PANYARGS
glColor3usv TEXTEQU <__imp_glColor3usv>
extern __imp_glColor4b:PANYARGS
glColor4b TEXTEQU <__imp_glColor4b>
extern __imp_glColor4bv:PANYARGS
glColor4bv TEXTEQU <__imp_glColor4bv>
extern __imp_glColor4d:PANYARGS
glColor4d TEXTEQU <__imp_glColor4d>
extern __imp_glColor4dv:PANYARGS
glColor4dv TEXTEQU <__imp_glColor4dv>
extern __imp_glColor4f:PANYARGS
glColor4f TEXTEQU <__imp_glColor4f>
extern __imp_glColor4fv:PANYARGS
glColor4fv TEXTEQU <__imp_glColor4fv>
extern __imp_glColor4i:PANYARGS
glColor4i TEXTEQU <__imp_glColor4i>
extern __imp_glColor4iv:PANYARGS
glColor4iv TEXTEQU <__imp_glColor4iv>
extern __imp_glColor4s:PANYARGS
glColor4s TEXTEQU <__imp_glColor4s>
extern __imp_glColor4sv:PANYARGS
glColor4sv TEXTEQU <__imp_glColor4sv>
extern __imp_glColor4ub:PANYARGS
glColor4ub TEXTEQU <__imp_glColor4ub>
extern __imp_glColor4ubv:PANYARGS
glColor4ubv TEXTEQU <__imp_glColor4ubv>
extern __imp_glColor4ui:PANYARGS
glColor4ui TEXTEQU <__imp_glColor4ui>
extern __imp_glColor4uiv:PANYARGS
glColor4uiv TEXTEQU <__imp_glColor4uiv>
extern __imp_glColor4us:PANYARGS
glColor4us TEXTEQU <__imp_glColor4us>
extern __imp_glColor4usv:PANYARGS
glColor4usv TEXTEQU <__imp_glColor4usv>
extern __imp_glColorMask:PANYARGS
glColorMask TEXTEQU <__imp_glColorMask>
extern __imp_glColorMaterial:PANYARGS
glColorMaterial TEXTEQU <__imp_glColorMaterial>
extern __imp_glColorPointer:PANYARGS
glColorPointer TEXTEQU <__imp_glColorPointer>
extern __imp_glCopyPixels:PANYARGS
glCopyPixels TEXTEQU <__imp_glCopyPixels>
extern __imp_glCopyTexImage1D:PANYARGS
glCopyTexImage1D TEXTEQU <__imp_glCopyTexImage1D>
extern __imp_glCopyTexImage2D:PANYARGS
glCopyTexImage2D TEXTEQU <__imp_glCopyTexImage2D>
extern __imp_glCopyTexSubImage1D:PANYARGS
glCopyTexSubImage1D TEXTEQU <__imp_glCopyTexSubImage1D>
extern __imp_glCopyTexSubImage2D:PANYARGS
glCopyTexSubImage2D TEXTEQU <__imp_glCopyTexSubImage2D>
extern __imp_glCullFace:PANYARGS
glCullFace TEXTEQU <__imp_glCullFace>
extern __imp_glDebugEntry:PANYARGS
glDebugEntry TEXTEQU <__imp_glDebugEntry>
extern __imp_glDeleteLists:PANYARGS
glDeleteLists TEXTEQU <__imp_glDeleteLists>
extern __imp_glDeleteTextures:PANYARGS
glDeleteTextures TEXTEQU <__imp_glDeleteTextures>
extern __imp_glDepthFunc:PANYARGS
glDepthFunc TEXTEQU <__imp_glDepthFunc>
extern __imp_glDepthMask:PANYARGS
glDepthMask TEXTEQU <__imp_glDepthMask>
extern __imp_glDepthRange:PANYARGS
glDepthRange TEXTEQU <__imp_glDepthRange>
extern __imp_glDisable:PANYARGS
glDisable TEXTEQU <__imp_glDisable>
extern __imp_glDisableClientState:PANYARGS
glDisableClientState TEXTEQU <__imp_glDisableClientState>
extern __imp_glDrawArrays:PANYARGS
glDrawArrays TEXTEQU <__imp_glDrawArrays>
extern __imp_glDrawBuffer:PANYARGS
glDrawBuffer TEXTEQU <__imp_glDrawBuffer>
extern __imp_glDrawElements:PANYARGS
glDrawElements TEXTEQU <__imp_glDrawElements>
extern __imp_glDrawPixels:PANYARGS
glDrawPixels TEXTEQU <__imp_glDrawPixels>
extern __imp_glEdgeFlag:PANYARGS
glEdgeFlag TEXTEQU <__imp_glEdgeFlag>
extern __imp_glEdgeFlagPointer:PANYARGS
glEdgeFlagPointer TEXTEQU <__imp_glEdgeFlagPointer>
extern __imp_glEdgeFlagv:PANYARGS
glEdgeFlagv TEXTEQU <__imp_glEdgeFlagv>
extern __imp_glEnable:PANYARGS
glEnable TEXTEQU <__imp_glEnable>
extern __imp_glEnableClientState:PANYARGS
glEnableClientState TEXTEQU <__imp_glEnableClientState>
extern __imp_glEnd:PANYARGS
glEnd TEXTEQU <__imp_glEnd>
extern __imp_glEndList:PANYARGS
glEndList TEXTEQU <__imp_glEndList>
extern __imp_glEvalCoord1d:PANYARGS
glEvalCoord1d TEXTEQU <__imp_glEvalCoord1d>
extern __imp_glEvalCoord1dv:PANYARGS
glEvalCoord1dv TEXTEQU <__imp_glEvalCoord1dv>
extern __imp_glEvalCoord1f:PANYARGS
glEvalCoord1f TEXTEQU <__imp_glEvalCoord1f>
extern __imp_glEvalCoord1fv:PANYARGS
glEvalCoord1fv TEXTEQU <__imp_glEvalCoord1fv>
extern __imp_glEvalCoord2d:PANYARGS
glEvalCoord2d TEXTEQU <__imp_glEvalCoord2d>
extern __imp_glEvalCoord2dv:PANYARGS
glEvalCoord2dv TEXTEQU <__imp_glEvalCoord2dv>
extern __imp_glEvalCoord2f:PANYARGS
glEvalCoord2f TEXTEQU <__imp_glEvalCoord2f>
extern __imp_glEvalCoord2fv:PANYARGS
glEvalCoord2fv TEXTEQU <__imp_glEvalCoord2fv>
extern __imp_glEvalMesh1:PANYARGS
glEvalMesh1 TEXTEQU <__imp_glEvalMesh1>
extern __imp_glEvalMesh2:PANYARGS
glEvalMesh2 TEXTEQU <__imp_glEvalMesh2>
extern __imp_glEvalPoint1:PANYARGS
glEvalPoint1 TEXTEQU <__imp_glEvalPoint1>
extern __imp_glEvalPoint2:PANYARGS
glEvalPoint2 TEXTEQU <__imp_glEvalPoint2>
extern __imp_glFeedbackBuffer:PANYARGS
glFeedbackBuffer TEXTEQU <__imp_glFeedbackBuffer>
extern __imp_glFinish:PANYARGS
glFinish TEXTEQU <__imp_glFinish>
extern __imp_glFlush:PANYARGS
glFlush TEXTEQU <__imp_glFlush>
extern __imp_glFogf:PANYARGS
glFogf TEXTEQU <__imp_glFogf>
extern __imp_glFogfv:PANYARGS
glFogfv TEXTEQU <__imp_glFogfv>
extern __imp_glFogi:PANYARGS
glFogi TEXTEQU <__imp_glFogi>
extern __imp_glFogiv:PANYARGS
glFogiv TEXTEQU <__imp_glFogiv>
extern __imp_glFrontFace:PANYARGS
glFrontFace TEXTEQU <__imp_glFrontFace>
extern __imp_glFrustum:PANYARGS
glFrustum TEXTEQU <__imp_glFrustum>
extern __imp_glGenLists:PANYARGS
glGenLists TEXTEQU <__imp_glGenLists>
extern __imp_glGenTextures:PANYARGS
glGenTextures TEXTEQU <__imp_glGenTextures>
extern __imp_glGetBooleanv:PANYARGS
glGetBooleanv TEXTEQU <__imp_glGetBooleanv>
extern __imp_glGetClipPlane:PANYARGS
glGetClipPlane TEXTEQU <__imp_glGetClipPlane>
extern __imp_glGetDoublev:PANYARGS
glGetDoublev TEXTEQU <__imp_glGetDoublev>
extern __imp_glGetError:PANYARGS
glGetError TEXTEQU <__imp_glGetError>
extern __imp_glGetFloatv:PANYARGS
glGetFloatv TEXTEQU <__imp_glGetFloatv>
extern __imp_glGetIntegerv:PANYARGS
glGetIntegerv TEXTEQU <__imp_glGetIntegerv>
extern __imp_glGetLightfv:PANYARGS
glGetLightfv TEXTEQU <__imp_glGetLightfv>
extern __imp_glGetLightiv:PANYARGS
glGetLightiv TEXTEQU <__imp_glGetLightiv>
extern __imp_glGetMapdv:PANYARGS
glGetMapdv TEXTEQU <__imp_glGetMapdv>
extern __imp_glGetMapfv:PANYARGS
glGetMapfv TEXTEQU <__imp_glGetMapfv>
extern __imp_glGetMapiv:PANYARGS
glGetMapiv TEXTEQU <__imp_glGetMapiv>
extern __imp_glGetMaterialfv:PANYARGS
glGetMaterialfv TEXTEQU <__imp_glGetMaterialfv>
extern __imp_glGetMaterialiv:PANYARGS
glGetMaterialiv TEXTEQU <__imp_glGetMaterialiv>
extern __imp_glGetPixelMapfv:PANYARGS
glGetPixelMapfv TEXTEQU <__imp_glGetPixelMapfv>
extern __imp_glGetPixelMapuiv:PANYARGS
glGetPixelMapuiv TEXTEQU <__imp_glGetPixelMapuiv>
extern __imp_glGetPixelMapusv:PANYARGS
glGetPixelMapusv TEXTEQU <__imp_glGetPixelMapusv>
extern __imp_glGetPointerv:PANYARGS
glGetPointerv TEXTEQU <__imp_glGetPointerv>
extern __imp_glGetPolygonStipple:PANYARGS
glGetPolygonStipple TEXTEQU <__imp_glGetPolygonStipple>
extern __imp_glGetString:PANYARGS
glGetString TEXTEQU <__imp_glGetString>
extern __imp_glGetTexEnvfv:PANYARGS
glGetTexEnvfv TEXTEQU <__imp_glGetTexEnvfv>
extern __imp_glGetTexEnviv:PANYARGS
glGetTexEnviv TEXTEQU <__imp_glGetTexEnviv>
extern __imp_glGetTexGendv:PANYARGS
glGetTexGendv TEXTEQU <__imp_glGetTexGendv>
extern __imp_glGetTexGenfv:PANYARGS
glGetTexGenfv TEXTEQU <__imp_glGetTexGenfv>
extern __imp_glGetTexGeniv:PANYARGS
glGetTexGeniv TEXTEQU <__imp_glGetTexGeniv>
extern __imp_glGetTexImage:PANYARGS
glGetTexImage TEXTEQU <__imp_glGetTexImage>
extern __imp_glGetTexLevelParameterfv:PANYARGS
glGetTexLevelParameterfv TEXTEQU <__imp_glGetTexLevelParameterfv>
extern __imp_glGetTexLevelParameteriv:PANYARGS
glGetTexLevelParameteriv TEXTEQU <__imp_glGetTexLevelParameteriv>
extern __imp_glGetTexParameterfv:PANYARGS
glGetTexParameterfv TEXTEQU <__imp_glGetTexParameterfv>
extern __imp_glGetTexParameteriv:PANYARGS
glGetTexParameteriv TEXTEQU <__imp_glGetTexParameteriv>
extern __imp_glHint:PANYARGS
glHint TEXTEQU <__imp_glHint>
extern __imp_glIndexMask:PANYARGS
glIndexMask TEXTEQU <__imp_glIndexMask>
extern __imp_glIndexPointer:PANYARGS
glIndexPointer TEXTEQU <__imp_glIndexPointer>
extern __imp_glIndexd:PANYARGS
glIndexd TEXTEQU <__imp_glIndexd>
extern __imp_glIndexdv:PANYARGS
glIndexdv TEXTEQU <__imp_glIndexdv>
extern __imp_glIndexf:PANYARGS
glIndexf TEXTEQU <__imp_glIndexf>
extern __imp_glIndexfv:PANYARGS
glIndexfv TEXTEQU <__imp_glIndexfv>
extern __imp_glIndexi:PANYARGS
glIndexi TEXTEQU <__imp_glIndexi>
extern __imp_glIndexiv:PANYARGS
glIndexiv TEXTEQU <__imp_glIndexiv>
extern __imp_glIndexs:PANYARGS
glIndexs TEXTEQU <__imp_glIndexs>
extern __imp_glIndexsv:PANYARGS
glIndexsv TEXTEQU <__imp_glIndexsv>
extern __imp_glIndexub:PANYARGS
glIndexub TEXTEQU <__imp_glIndexub>
extern __imp_glIndexubv:PANYARGS
glIndexubv TEXTEQU <__imp_glIndexubv>
extern __imp_glInitNames:PANYARGS
glInitNames TEXTEQU <__imp_glInitNames>
extern __imp_glInterleavedArrays:PANYARGS
glInterleavedArrays TEXTEQU <__imp_glInterleavedArrays>
extern __imp_glIsEnabled:PANYARGS
glIsEnabled TEXTEQU <__imp_glIsEnabled>
extern __imp_glIsList:PANYARGS
glIsList TEXTEQU <__imp_glIsList>
extern __imp_glIsTexture:PANYARGS
glIsTexture TEXTEQU <__imp_glIsTexture>
extern __imp_glLightModelf:PANYARGS
glLightModelf TEXTEQU <__imp_glLightModelf>
extern __imp_glLightModelfv:PANYARGS
glLightModelfv TEXTEQU <__imp_glLightModelfv>
extern __imp_glLightModeli:PANYARGS
glLightModeli TEXTEQU <__imp_glLightModeli>
extern __imp_glLightModeliv:PANYARGS
glLightModeliv TEXTEQU <__imp_glLightModeliv>
extern __imp_glLightf:PANYARGS
glLightf TEXTEQU <__imp_glLightf>
extern __imp_glLightfv:PANYARGS
glLightfv TEXTEQU <__imp_glLightfv>
extern __imp_glLighti:PANYARGS
glLighti TEXTEQU <__imp_glLighti>
extern __imp_glLightiv:PANYARGS
glLightiv TEXTEQU <__imp_glLightiv>
extern __imp_glLineStipple:PANYARGS
glLineStipple TEXTEQU <__imp_glLineStipple>
extern __imp_glLineWidth:PANYARGS
glLineWidth TEXTEQU <__imp_glLineWidth>
extern __imp_glListBase:PANYARGS
glListBase TEXTEQU <__imp_glListBase>
extern __imp_glLoadIdentity:PANYARGS
glLoadIdentity TEXTEQU <__imp_glLoadIdentity>
extern __imp_glLoadMatrixd:PANYARGS
glLoadMatrixd TEXTEQU <__imp_glLoadMatrixd>
extern __imp_glLoadMatrixf:PANYARGS
glLoadMatrixf TEXTEQU <__imp_glLoadMatrixf>
extern __imp_glLoadName:PANYARGS
glLoadName TEXTEQU <__imp_glLoadName>
extern __imp_glLogicOp:PANYARGS
glLogicOp TEXTEQU <__imp_glLogicOp>
extern __imp_glMap1d:PANYARGS
glMap1d TEXTEQU <__imp_glMap1d>
extern __imp_glMap1f:PANYARGS
glMap1f TEXTEQU <__imp_glMap1f>
extern __imp_glMap2d:PANYARGS
glMap2d TEXTEQU <__imp_glMap2d>
extern __imp_glMap2f:PANYARGS
glMap2f TEXTEQU <__imp_glMap2f>
extern __imp_glMapGrid1d:PANYARGS
glMapGrid1d TEXTEQU <__imp_glMapGrid1d>
extern __imp_glMapGrid1f:PANYARGS
glMapGrid1f TEXTEQU <__imp_glMapGrid1f>
extern __imp_glMapGrid2d:PANYARGS
glMapGrid2d TEXTEQU <__imp_glMapGrid2d>
extern __imp_glMapGrid2f:PANYARGS
glMapGrid2f TEXTEQU <__imp_glMapGrid2f>
extern __imp_glMaterialf:PANYARGS
glMaterialf TEXTEQU <__imp_glMaterialf>
extern __imp_glMaterialfv:PANYARGS
glMaterialfv TEXTEQU <__imp_glMaterialfv>
extern __imp_glMateriali:PANYARGS
glMateriali TEXTEQU <__imp_glMateriali>
extern __imp_glMaterialiv:PANYARGS
glMaterialiv TEXTEQU <__imp_glMaterialiv>
extern __imp_glMatrixMode:PANYARGS
glMatrixMode TEXTEQU <__imp_glMatrixMode>
extern __imp_glMultMatrixd:PANYARGS
glMultMatrixd TEXTEQU <__imp_glMultMatrixd>
extern __imp_glMultMatrixf:PANYARGS
glMultMatrixf TEXTEQU <__imp_glMultMatrixf>
extern __imp_glNewList:PANYARGS
glNewList TEXTEQU <__imp_glNewList>
extern __imp_glNormal3b:PANYARGS
glNormal3b TEXTEQU <__imp_glNormal3b>
extern __imp_glNormal3bv:PANYARGS
glNormal3bv TEXTEQU <__imp_glNormal3bv>
extern __imp_glNormal3d:PANYARGS
glNormal3d TEXTEQU <__imp_glNormal3d>
extern __imp_glNormal3dv:PANYARGS
glNormal3dv TEXTEQU <__imp_glNormal3dv>
extern __imp_glNormal3f:PANYARGS
glNormal3f TEXTEQU <__imp_glNormal3f>
extern __imp_glNormal3fv:PANYARGS
glNormal3fv TEXTEQU <__imp_glNormal3fv>
extern __imp_glNormal3i:PANYARGS
glNormal3i TEXTEQU <__imp_glNormal3i>
extern __imp_glNormal3iv:PANYARGS
glNormal3iv TEXTEQU <__imp_glNormal3iv>
extern __imp_glNormal3s:PANYARGS
glNormal3s TEXTEQU <__imp_glNormal3s>
extern __imp_glNormal3sv:PANYARGS
glNormal3sv TEXTEQU <__imp_glNormal3sv>
extern __imp_glNormalPointer:PANYARGS
glNormalPointer TEXTEQU <__imp_glNormalPointer>
extern __imp_glOrtho:PANYARGS
glOrtho TEXTEQU <__imp_glOrtho>
extern __imp_glPassThrough:PANYARGS
glPassThrough TEXTEQU <__imp_glPassThrough>
extern __imp_glPixelMapfv:PANYARGS
glPixelMapfv TEXTEQU <__imp_glPixelMapfv>
extern __imp_glPixelMapuiv:PANYARGS
glPixelMapuiv TEXTEQU <__imp_glPixelMapuiv>
extern __imp_glPixelMapusv:PANYARGS
glPixelMapusv TEXTEQU <__imp_glPixelMapusv>
extern __imp_glPixelStoref:PANYARGS
glPixelStoref TEXTEQU <__imp_glPixelStoref>
extern __imp_glPixelStorei:PANYARGS
glPixelStorei TEXTEQU <__imp_glPixelStorei>
extern __imp_glPixelTransferf:PANYARGS
glPixelTransferf TEXTEQU <__imp_glPixelTransferf>
extern __imp_glPixelTransferi:PANYARGS
glPixelTransferi TEXTEQU <__imp_glPixelTransferi>
extern __imp_glPixelZoom:PANYARGS
glPixelZoom TEXTEQU <__imp_glPixelZoom>
extern __imp_glPointSize:PANYARGS
glPointSize TEXTEQU <__imp_glPointSize>
extern __imp_glPolygonMode:PANYARGS
glPolygonMode TEXTEQU <__imp_glPolygonMode>
extern __imp_glPolygonOffset:PANYARGS
glPolygonOffset TEXTEQU <__imp_glPolygonOffset>
extern __imp_glPolygonStipple:PANYARGS
glPolygonStipple TEXTEQU <__imp_glPolygonStipple>
extern __imp_glPopAttrib:PANYARGS
glPopAttrib TEXTEQU <__imp_glPopAttrib>
extern __imp_glPopClientAttrib:PANYARGS
glPopClientAttrib TEXTEQU <__imp_glPopClientAttrib>
extern __imp_glPopMatrix:PANYARGS
glPopMatrix TEXTEQU <__imp_glPopMatrix>
extern __imp_glPopName:PANYARGS
glPopName TEXTEQU <__imp_glPopName>
extern __imp_glPrioritizeTextures:PANYARGS
glPrioritizeTextures TEXTEQU <__imp_glPrioritizeTextures>
extern __imp_glPushAttrib:PANYARGS
glPushAttrib TEXTEQU <__imp_glPushAttrib>
extern __imp_glPushClientAttrib:PANYARGS
glPushClientAttrib TEXTEQU <__imp_glPushClientAttrib>
extern __imp_glPushMatrix:PANYARGS
glPushMatrix TEXTEQU <__imp_glPushMatrix>
extern __imp_glPushName:PANYARGS
glPushName TEXTEQU <__imp_glPushName>
extern __imp_glRasterPos2d:PANYARGS
glRasterPos2d TEXTEQU <__imp_glRasterPos2d>
extern __imp_glRasterPos2dv:PANYARGS
glRasterPos2dv TEXTEQU <__imp_glRasterPos2dv>
extern __imp_glRasterPos2f:PANYARGS
glRasterPos2f TEXTEQU <__imp_glRasterPos2f>
extern __imp_glRasterPos2fv:PANYARGS
glRasterPos2fv TEXTEQU <__imp_glRasterPos2fv>
extern __imp_glRasterPos2i:PANYARGS
glRasterPos2i TEXTEQU <__imp_glRasterPos2i>
extern __imp_glRasterPos2iv:PANYARGS
glRasterPos2iv TEXTEQU <__imp_glRasterPos2iv>
extern __imp_glRasterPos2s:PANYARGS
glRasterPos2s TEXTEQU <__imp_glRasterPos2s>
extern __imp_glRasterPos2sv:PANYARGS
glRasterPos2sv TEXTEQU <__imp_glRasterPos2sv>
extern __imp_glRasterPos3d:PANYARGS
glRasterPos3d TEXTEQU <__imp_glRasterPos3d>
extern __imp_glRasterPos3dv:PANYARGS
glRasterPos3dv TEXTEQU <__imp_glRasterPos3dv>
extern __imp_glRasterPos3f:PANYARGS
glRasterPos3f TEXTEQU <__imp_glRasterPos3f>
extern __imp_glRasterPos3fv:PANYARGS
glRasterPos3fv TEXTEQU <__imp_glRasterPos3fv>
extern __imp_glRasterPos3i:PANYARGS
glRasterPos3i TEXTEQU <__imp_glRasterPos3i>
extern __imp_glRasterPos3iv:PANYARGS
glRasterPos3iv TEXTEQU <__imp_glRasterPos3iv>
extern __imp_glRasterPos3s:PANYARGS
glRasterPos3s TEXTEQU <__imp_glRasterPos3s>
extern __imp_glRasterPos3sv:PANYARGS
glRasterPos3sv TEXTEQU <__imp_glRasterPos3sv>
extern __imp_glRasterPos4d:PANYARGS
glRasterPos4d TEXTEQU <__imp_glRasterPos4d>
extern __imp_glRasterPos4dv:PANYARGS
glRasterPos4dv TEXTEQU <__imp_glRasterPos4dv>
extern __imp_glRasterPos4f:PANYARGS
glRasterPos4f TEXTEQU <__imp_glRasterPos4f>
extern __imp_glRasterPos4fv:PANYARGS
glRasterPos4fv TEXTEQU <__imp_glRasterPos4fv>
extern __imp_glRasterPos4i:PANYARGS
glRasterPos4i TEXTEQU <__imp_glRasterPos4i>
extern __imp_glRasterPos4iv:PANYARGS
glRasterPos4iv TEXTEQU <__imp_glRasterPos4iv>
extern __imp_glRasterPos4s:PANYARGS
glRasterPos4s TEXTEQU <__imp_glRasterPos4s>
extern __imp_glRasterPos4sv:PANYARGS
glRasterPos4sv TEXTEQU <__imp_glRasterPos4sv>
extern __imp_glReadBuffer:PANYARGS
glReadBuffer TEXTEQU <__imp_glReadBuffer>
extern __imp_glReadPixels:PANYARGS
glReadPixels TEXTEQU <__imp_glReadPixels>
extern __imp_glRectd:PANYARGS
glRectd TEXTEQU <__imp_glRectd>
extern __imp_glRectdv:PANYARGS
glRectdv TEXTEQU <__imp_glRectdv>
extern __imp_glRectf:PANYARGS
glRectf TEXTEQU <__imp_glRectf>
extern __imp_glRectfv:PANYARGS
glRectfv TEXTEQU <__imp_glRectfv>
extern __imp_glRecti:PANYARGS
glRecti TEXTEQU <__imp_glRecti>
extern __imp_glRectiv:PANYARGS
glRectiv TEXTEQU <__imp_glRectiv>
extern __imp_glRects:PANYARGS
glRects TEXTEQU <__imp_glRects>
extern __imp_glRectsv:PANYARGS
glRectsv TEXTEQU <__imp_glRectsv>
extern __imp_glRenderMode:PANYARGS
glRenderMode TEXTEQU <__imp_glRenderMode>
extern __imp_glRotated:PANYARGS
glRotated TEXTEQU <__imp_glRotated>
extern __imp_glRotatef:PANYARGS
glRotatef TEXTEQU <__imp_glRotatef>
extern __imp_glScaled:PANYARGS
glScaled TEXTEQU <__imp_glScaled>
extern __imp_glScalef:PANYARGS
glScalef TEXTEQU <__imp_glScalef>
extern __imp_glScissor:PANYARGS
glScissor TEXTEQU <__imp_glScissor>
extern __imp_glSelectBuffer:PANYARGS
glSelectBuffer TEXTEQU <__imp_glSelectBuffer>
extern __imp_glShadeModel:PANYARGS
glShadeModel TEXTEQU <__imp_glShadeModel>
extern __imp_glStencilFunc:PANYARGS
glStencilFunc TEXTEQU <__imp_glStencilFunc>
extern __imp_glStencilMask:PANYARGS
glStencilMask TEXTEQU <__imp_glStencilMask>
extern __imp_glStencilOp:PANYARGS
glStencilOp TEXTEQU <__imp_glStencilOp>
extern __imp_glTexCoord1d:PANYARGS
glTexCoord1d TEXTEQU <__imp_glTexCoord1d>
extern __imp_glTexCoord1dv:PANYARGS
glTexCoord1dv TEXTEQU <__imp_glTexCoord1dv>
extern __imp_glTexCoord1f:PANYARGS
glTexCoord1f TEXTEQU <__imp_glTexCoord1f>
extern __imp_glTexCoord1fv:PANYARGS
glTexCoord1fv TEXTEQU <__imp_glTexCoord1fv>
extern __imp_glTexCoord1i:PANYARGS
glTexCoord1i TEXTEQU <__imp_glTexCoord1i>
extern __imp_glTexCoord1iv:PANYARGS
glTexCoord1iv TEXTEQU <__imp_glTexCoord1iv>
extern __imp_glTexCoord1s:PANYARGS
glTexCoord1s TEXTEQU <__imp_glTexCoord1s>
extern __imp_glTexCoord1sv:PANYARGS
glTexCoord1sv TEXTEQU <__imp_glTexCoord1sv>
extern __imp_glTexCoord2d:PANYARGS
glTexCoord2d TEXTEQU <__imp_glTexCoord2d>
extern __imp_glTexCoord2dv:PANYARGS
glTexCoord2dv TEXTEQU <__imp_glTexCoord2dv>
extern __imp_glTexCoord2f:PANYARGS
glTexCoord2f TEXTEQU <__imp_glTexCoord2f>
extern __imp_glTexCoord2fv:PANYARGS
glTexCoord2fv TEXTEQU <__imp_glTexCoord2fv>
extern __imp_glTexCoord2i:PANYARGS
glTexCoord2i TEXTEQU <__imp_glTexCoord2i>
extern __imp_glTexCoord2iv:PANYARGS
glTexCoord2iv TEXTEQU <__imp_glTexCoord2iv>
extern __imp_glTexCoord2s:PANYARGS
glTexCoord2s TEXTEQU <__imp_glTexCoord2s>
extern __imp_glTexCoord2sv:PANYARGS
glTexCoord2sv TEXTEQU <__imp_glTexCoord2sv>
extern __imp_glTexCoord3d:PANYARGS
glTexCoord3d TEXTEQU <__imp_glTexCoord3d>
extern __imp_glTexCoord3dv:PANYARGS
glTexCoord3dv TEXTEQU <__imp_glTexCoord3dv>
extern __imp_glTexCoord3f:PANYARGS
glTexCoord3f TEXTEQU <__imp_glTexCoord3f>
extern __imp_glTexCoord3fv:PANYARGS
glTexCoord3fv TEXTEQU <__imp_glTexCoord3fv>
extern __imp_glTexCoord3i:PANYARGS
glTexCoord3i TEXTEQU <__imp_glTexCoord3i>
extern __imp_glTexCoord3iv:PANYARGS
glTexCoord3iv TEXTEQU <__imp_glTexCoord3iv>
extern __imp_glTexCoord3s:PANYARGS
glTexCoord3s TEXTEQU <__imp_glTexCoord3s>
extern __imp_glTexCoord3sv:PANYARGS
glTexCoord3sv TEXTEQU <__imp_glTexCoord3sv>
extern __imp_glTexCoord4d:PANYARGS
glTexCoord4d TEXTEQU <__imp_glTexCoord4d>
extern __imp_glTexCoord4dv:PANYARGS
glTexCoord4dv TEXTEQU <__imp_glTexCoord4dv>
extern __imp_glTexCoord4f:PANYARGS
glTexCoord4f TEXTEQU <__imp_glTexCoord4f>
extern __imp_glTexCoord4fv:PANYARGS
glTexCoord4fv TEXTEQU <__imp_glTexCoord4fv>
extern __imp_glTexCoord4i:PANYARGS
glTexCoord4i TEXTEQU <__imp_glTexCoord4i>
extern __imp_glTexCoord4iv:PANYARGS
glTexCoord4iv TEXTEQU <__imp_glTexCoord4iv>
extern __imp_glTexCoord4s:PANYARGS
glTexCoord4s TEXTEQU <__imp_glTexCoord4s>
extern __imp_glTexCoord4sv:PANYARGS
glTexCoord4sv TEXTEQU <__imp_glTexCoord4sv>
extern __imp_glTexCoordPointer:PANYARGS
glTexCoordPointer TEXTEQU <__imp_glTexCoordPointer>
extern __imp_glTexEnvf:PANYARGS
glTexEnvf TEXTEQU <__imp_glTexEnvf>
extern __imp_glTexEnvfv:PANYARGS
glTexEnvfv TEXTEQU <__imp_glTexEnvfv>
extern __imp_glTexEnvi:PANYARGS
glTexEnvi TEXTEQU <__imp_glTexEnvi>
extern __imp_glTexEnviv:PANYARGS
glTexEnviv TEXTEQU <__imp_glTexEnviv>
extern __imp_glTexGend:PANYARGS
glTexGend TEXTEQU <__imp_glTexGend>
extern __imp_glTexGendv:PANYARGS
glTexGendv TEXTEQU <__imp_glTexGendv>
extern __imp_glTexGenf:PANYARGS
glTexGenf TEXTEQU <__imp_glTexGenf>
extern __imp_glTexGenfv:PANYARGS
glTexGenfv TEXTEQU <__imp_glTexGenfv>
extern __imp_glTexGeni:PANYARGS
glTexGeni TEXTEQU <__imp_glTexGeni>
extern __imp_glTexGeniv:PANYARGS
glTexGeniv TEXTEQU <__imp_glTexGeniv>
extern __imp_glTexImage1D:PANYARGS
glTexImage1D TEXTEQU <__imp_glTexImage1D>
extern __imp_glTexImage2D:PANYARGS
glTexImage2D TEXTEQU <__imp_glTexImage2D>
extern __imp_glTexParameterf:PANYARGS
glTexParameterf TEXTEQU <__imp_glTexParameterf>
extern __imp_glTexParameterfv:PANYARGS
glTexParameterfv TEXTEQU <__imp_glTexParameterfv>
extern __imp_glTexParameteri:PANYARGS
glTexParameteri TEXTEQU <__imp_glTexParameteri>
extern __imp_glTexParameteriv:PANYARGS
glTexParameteriv TEXTEQU <__imp_glTexParameteriv>
extern __imp_glTexSubImage1D:PANYARGS
glTexSubImage1D TEXTEQU <__imp_glTexSubImage1D>
extern __imp_glTexSubImage2D:PANYARGS
glTexSubImage2D TEXTEQU <__imp_glTexSubImage2D>
extern __imp_glTranslated:PANYARGS
glTranslated TEXTEQU <__imp_glTranslated>
extern __imp_glTranslatef:PANYARGS
glTranslatef TEXTEQU <__imp_glTranslatef>
extern __imp_glVertex2d:PANYARGS
glVertex2d TEXTEQU <__imp_glVertex2d>
extern __imp_glVertex2dv:PANYARGS
glVertex2dv TEXTEQU <__imp_glVertex2dv>
extern __imp_glVertex2f:PANYARGS
glVertex2f TEXTEQU <__imp_glVertex2f>
extern __imp_glVertex2fv:PANYARGS
glVertex2fv TEXTEQU <__imp_glVertex2fv>
extern __imp_glVertex2i:PANYARGS
glVertex2i TEXTEQU <__imp_glVertex2i>
extern __imp_glVertex2iv:PANYARGS
glVertex2iv TEXTEQU <__imp_glVertex2iv>
extern __imp_glVertex2s:PANYARGS
glVertex2s TEXTEQU <__imp_glVertex2s>
extern __imp_glVertex2sv:PANYARGS
glVertex2sv TEXTEQU <__imp_glVertex2sv>
extern __imp_glVertex3d:PANYARGS
glVertex3d TEXTEQU <__imp_glVertex3d>
extern __imp_glVertex3dv:PANYARGS
glVertex3dv TEXTEQU <__imp_glVertex3dv>
extern __imp_glVertex3f:PANYARGS
glVertex3f TEXTEQU <__imp_glVertex3f>
extern __imp_glVertex3fv:PANYARGS
glVertex3fv TEXTEQU <__imp_glVertex3fv>
extern __imp_glVertex3i:PANYARGS
glVertex3i TEXTEQU <__imp_glVertex3i>
extern __imp_glVertex3iv:PANYARGS
glVertex3iv TEXTEQU <__imp_glVertex3iv>
extern __imp_glVertex3s:PANYARGS
glVertex3s TEXTEQU <__imp_glVertex3s>
extern __imp_glVertex3sv:PANYARGS
glVertex3sv TEXTEQU <__imp_glVertex3sv>
extern __imp_glVertex4d:PANYARGS
glVertex4d TEXTEQU <__imp_glVertex4d>
extern __imp_glVertex4dv:PANYARGS
glVertex4dv TEXTEQU <__imp_glVertex4dv>
extern __imp_glVertex4f:PANYARGS
glVertex4f TEXTEQU <__imp_glVertex4f>
extern __imp_glVertex4fv:PANYARGS
glVertex4fv TEXTEQU <__imp_glVertex4fv>
extern __imp_glVertex4i:PANYARGS
glVertex4i TEXTEQU <__imp_glVertex4i>
extern __imp_glVertex4iv:PANYARGS
glVertex4iv TEXTEQU <__imp_glVertex4iv>
extern __imp_glVertex4s:PANYARGS
glVertex4s TEXTEQU <__imp_glVertex4s>
extern __imp_glVertex4sv:PANYARGS
glVertex4sv TEXTEQU <__imp_glVertex4sv>
extern __imp_glVertexPointer:PANYARGS
glVertexPointer TEXTEQU <__imp_glVertexPointer>
extern __imp_glViewport:PANYARGS
glViewport TEXTEQU <__imp_glViewport>
extern __imp_wglChoosePixelFormat:PANYARGS
wglChoosePixelFormat TEXTEQU <__imp_wglChoosePixelFormat>
extern __imp_wglCopyContext:PANYARGS
wglCopyContext TEXTEQU <__imp_wglCopyContext>
extern __imp_wglCreateContext:PANYARGS
wglCreateContext TEXTEQU <__imp_wglCreateContext>
extern __imp_wglCreateLayerContext:PANYARGS
wglCreateLayerContext TEXTEQU <__imp_wglCreateLayerContext>
extern __imp_wglDeleteContext:PANYARGS
wglDeleteContext TEXTEQU <__imp_wglDeleteContext>
extern __imp_wglDescribeLayerPlane:PANYARGS
wglDescribeLayerPlane TEXTEQU <__imp_wglDescribeLayerPlane>
extern __imp_wglDescribePixelFormat:PANYARGS
wglDescribePixelFormat TEXTEQU <__imp_wglDescribePixelFormat>
extern __imp_wglGetCurrentContext:PANYARGS
wglGetCurrentContext TEXTEQU <__imp_wglGetCurrentContext>
extern __imp_wglGetCurrentDC:PANYARGS
wglGetCurrentDC TEXTEQU <__imp_wglGetCurrentDC>
extern __imp_wglGetDefaultProcAddress:PANYARGS
wglGetDefaultProcAddress TEXTEQU <__imp_wglGetDefaultProcAddress>
extern __imp_wglGetLayerPaletteEntries:PANYARGS
wglGetLayerPaletteEntries TEXTEQU <__imp_wglGetLayerPaletteEntries>
extern __imp_wglGetPixelFormat:PANYARGS
wglGetPixelFormat TEXTEQU <__imp_wglGetPixelFormat>
extern __imp_wglGetProcAddress:PANYARGS
wglGetProcAddress TEXTEQU <__imp_wglGetProcAddress>
extern __imp_wglMakeCurrent:PANYARGS
wglMakeCurrent TEXTEQU <__imp_wglMakeCurrent>
extern __imp_wglRealizeLayerPalette:PANYARGS
wglRealizeLayerPalette TEXTEQU <__imp_wglRealizeLayerPalette>
extern __imp_wglSetLayerPaletteEntries:PANYARGS
wglSetLayerPaletteEntries TEXTEQU <__imp_wglSetLayerPaletteEntries>
extern __imp_wglSetPixelFormat:PANYARGS
wglSetPixelFormat TEXTEQU <__imp_wglSetPixelFormat>
extern __imp_wglShareLists:PANYARGS
wglShareLists TEXTEQU <__imp_wglShareLists>
extern __imp_wglSwapBuffers:PANYARGS
wglSwapBuffers TEXTEQU <__imp_wglSwapBuffers>
extern __imp_wglSwapLayerBuffers:PANYARGS
wglSwapLayerBuffers TEXTEQU <__imp_wglSwapLayerBuffers>
extern __imp_wglSwapMultipleBuffers:PANYARGS
wglSwapMultipleBuffers TEXTEQU <__imp_wglSwapMultipleBuffers>
extern __imp_wglUseFontBitmapsA:PANYARGS
wglUseFontBitmaps  TEXTEQU <__imp_wglUseFontBitmapsA>
extern __imp_wglUseFontBitmapsW:PANYARGS
wglUseFontBitmapsW TEXTEQU <__imp_wglUseFontBitmapsW>
extern __imp_wglUseFontOutlinesA:PANYARGS
wglUseFontOutlines  TEXTEQU <__imp_wglUseFontOutlinesA>
extern __imp_wglUseFontOutlinesW:PANYARGS
wglUseFontOutlinesW TEXTEQU <__imp_wglUseFontOutlinesW>
