extern __imp_ExecuteUninstall:PANYARGS
ExecuteUninstall TEXTEQU <__imp_ExecuteUninstall>
extern __imp_GetUninstallImageSize:PANYARGS
GetUninstallImageSize TEXTEQU <__imp_GetUninstallImageSize>
extern __imp_IsUninstallImageValid:PANYARGS
IsUninstallImageValid TEXTEQU <__imp_IsUninstallImageValid>
extern __imp_ProvideUiAlerts:PANYARGS
ProvideUiAlerts TEXTEQU <__imp_ProvideUiAlerts>
extern __imp_RemoveUninstallImage:PANYARGS
RemoveUninstallImage TEXTEQU <__imp_RemoveUninstallImage>
