extern __imp_PdhPlaGetLogFileNameA:PANYARGS
PdhPlaGetLogFileName  TEXTEQU <__imp_PdhPlaGetLogFileNameA>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_PdhAdd009CounterA:PANYARGS
PdhAdd009Counter  TEXTEQU <__imp_PdhAdd009CounterA>
extern __imp_PdhAdd009CounterW:PANYARGS
PdhAdd009CounterW TEXTEQU <__imp_PdhAdd009CounterW>
extern __imp_PdhAddCounterA:PANYARGS
PdhAddCounter  TEXTEQU <__imp_PdhAddCounterA>
extern __imp_PdhAddCounterW:PANYARGS
PdhAddCounterW TEXTEQU <__imp_PdhAddCounterW>
extern __imp_PdhBindInputDataSourceA:PANYARGS
PdhBindInputDataSource  TEXTEQU <__imp_PdhBindInputDataSourceA>
extern __imp_PdhBindInputDataSourceW:PANYARGS
PdhBindInputDataSourceW TEXTEQU <__imp_PdhBindInputDataSourceW>
extern __imp_PdhBrowseCountersA:PANYARGS
PdhBrowseCounters  TEXTEQU <__imp_PdhBrowseCountersA>
extern __imp_PdhBrowseCountersHA:PANYARGS
PdhBrowseCountersH  TEXTEQU <__imp_PdhBrowseCountersHA>
extern __imp_PdhBrowseCountersHW:PANYARGS
PdhBrowseCountersHW TEXTEQU <__imp_PdhBrowseCountersHW>
extern __imp_PdhBrowseCountersW:PANYARGS
PdhBrowseCountersW TEXTEQU <__imp_PdhBrowseCountersW>
extern __imp_PdhCalculateCounterFromRawValue:PANYARGS
PdhCalculateCounterFromRawValue TEXTEQU <__imp_PdhCalculateCounterFromRawValue>
extern __imp_PdhCloseLog:PANYARGS
PdhCloseLog TEXTEQU <__imp_PdhCloseLog>
extern __imp_PdhCloseQuery:PANYARGS
PdhCloseQuery TEXTEQU <__imp_PdhCloseQuery>
extern __imp_PdhCollectQueryData:PANYARGS
PdhCollectQueryData TEXTEQU <__imp_PdhCollectQueryData>
extern __imp_PdhCollectQueryDataEx:PANYARGS
PdhCollectQueryDataEx TEXTEQU <__imp_PdhCollectQueryDataEx>
extern __imp_PdhComputeCounterStatistics:PANYARGS
PdhComputeCounterStatistics TEXTEQU <__imp_PdhComputeCounterStatistics>
extern __imp_PdhConnectMachineA:PANYARGS
PdhConnectMachine  TEXTEQU <__imp_PdhConnectMachineA>
extern __imp_PdhConnectMachineW:PANYARGS
PdhConnectMachineW TEXTEQU <__imp_PdhConnectMachineW>
extern __imp_PdhCreateSQLTablesA:PANYARGS
PdhCreateSQLTables  TEXTEQU <__imp_PdhCreateSQLTablesA>
extern __imp_PdhCreateSQLTablesW:PANYARGS
PdhCreateSQLTablesW TEXTEQU <__imp_PdhCreateSQLTablesW>
extern __imp_PdhEnumLogSetNamesA:PANYARGS
PdhEnumLogSetNames  TEXTEQU <__imp_PdhEnumLogSetNamesA>
extern __imp_PdhEnumLogSetNamesW:PANYARGS
PdhEnumLogSetNamesW TEXTEQU <__imp_PdhEnumLogSetNamesW>
extern __imp_PdhEnumMachinesA:PANYARGS
PdhEnumMachines  TEXTEQU <__imp_PdhEnumMachinesA>
extern __imp_PdhEnumMachinesHA:PANYARGS
PdhEnumMachinesH  TEXTEQU <__imp_PdhEnumMachinesHA>
extern __imp_PdhEnumMachinesHW:PANYARGS
PdhEnumMachinesHW TEXTEQU <__imp_PdhEnumMachinesHW>
extern __imp_PdhEnumMachinesW:PANYARGS
PdhEnumMachinesW TEXTEQU <__imp_PdhEnumMachinesW>
extern __imp_PdhEnumObjectItemsA:PANYARGS
PdhEnumObjectItems  TEXTEQU <__imp_PdhEnumObjectItemsA>
extern __imp_PdhEnumObjectItemsHA:PANYARGS
PdhEnumObjectItemsH  TEXTEQU <__imp_PdhEnumObjectItemsHA>
extern __imp_PdhEnumObjectItemsHW:PANYARGS
PdhEnumObjectItemsHW TEXTEQU <__imp_PdhEnumObjectItemsHW>
extern __imp_PdhEnumObjectItemsW:PANYARGS
PdhEnumObjectItemsW TEXTEQU <__imp_PdhEnumObjectItemsW>
extern __imp_PdhEnumObjectsA:PANYARGS
PdhEnumObjects  TEXTEQU <__imp_PdhEnumObjectsA>
extern __imp_PdhEnumObjectsHA:PANYARGS
PdhEnumObjectsH  TEXTEQU <__imp_PdhEnumObjectsHA>
extern __imp_PdhEnumObjectsHW:PANYARGS
PdhEnumObjectsHW TEXTEQU <__imp_PdhEnumObjectsHW>
extern __imp_PdhEnumObjectsW:PANYARGS
PdhEnumObjectsW TEXTEQU <__imp_PdhEnumObjectsW>
extern __imp_PdhExpandCounterPathA:PANYARGS
PdhExpandCounterPath  TEXTEQU <__imp_PdhExpandCounterPathA>
extern __imp_PdhExpandCounterPathW:PANYARGS
PdhExpandCounterPathW TEXTEQU <__imp_PdhExpandCounterPathW>
extern __imp_PdhExpandWildCardPathA:PANYARGS
PdhExpandWildCardPath  TEXTEQU <__imp_PdhExpandWildCardPathA>
extern __imp_PdhExpandWildCardPathHA:PANYARGS
PdhExpandWildCardPathH  TEXTEQU <__imp_PdhExpandWildCardPathHA>
extern __imp_PdhExpandWildCardPathHW:PANYARGS
PdhExpandWildCardPathHW TEXTEQU <__imp_PdhExpandWildCardPathHW>
extern __imp_PdhExpandWildCardPathW:PANYARGS
PdhExpandWildCardPathW TEXTEQU <__imp_PdhExpandWildCardPathW>
extern __imp_PdhFormatFromRawValue:PANYARGS
PdhFormatFromRawValue TEXTEQU <__imp_PdhFormatFromRawValue>
extern __imp_PdhGetCounterInfoA:PANYARGS
PdhGetCounterInfo  TEXTEQU <__imp_PdhGetCounterInfoA>
extern __imp_PdhGetCounterInfoW:PANYARGS
PdhGetCounterInfoW TEXTEQU <__imp_PdhGetCounterInfoW>
extern __imp_PdhGetCounterTimeBase:PANYARGS
PdhGetCounterTimeBase TEXTEQU <__imp_PdhGetCounterTimeBase>
extern __imp_PdhGetDataSourceTimeRangeA:PANYARGS
PdhGetDataSourceTimeRange  TEXTEQU <__imp_PdhGetDataSourceTimeRangeA>
extern __imp_PdhGetDataSourceTimeRangeH:PANYARGS
PdhGetDataSourceTimeRangeH TEXTEQU <__imp_PdhGetDataSourceTimeRangeH>
extern __imp_PdhGetDataSourceTimeRangeW:PANYARGS
PdhGetDataSourceTimeRangeW TEXTEQU <__imp_PdhGetDataSourceTimeRangeW>
extern __imp_PdhGetDefaultPerfCounterA:PANYARGS
PdhGetDefaultPerfCounter  TEXTEQU <__imp_PdhGetDefaultPerfCounterA>
extern __imp_PdhGetDefaultPerfCounterHA:PANYARGS
PdhGetDefaultPerfCounterH  TEXTEQU <__imp_PdhGetDefaultPerfCounterHA>
extern __imp_PdhGetDefaultPerfCounterHW:PANYARGS
PdhGetDefaultPerfCounterHW TEXTEQU <__imp_PdhGetDefaultPerfCounterHW>
extern __imp_PdhGetDefaultPerfCounterW:PANYARGS
PdhGetDefaultPerfCounterW TEXTEQU <__imp_PdhGetDefaultPerfCounterW>
extern __imp_PdhGetDefaultPerfObjectA:PANYARGS
PdhGetDefaultPerfObject  TEXTEQU <__imp_PdhGetDefaultPerfObjectA>
extern __imp_PdhGetDefaultPerfObjectHA:PANYARGS
PdhGetDefaultPerfObjectH  TEXTEQU <__imp_PdhGetDefaultPerfObjectHA>
extern __imp_PdhGetDefaultPerfObjectHW:PANYARGS
PdhGetDefaultPerfObjectHW TEXTEQU <__imp_PdhGetDefaultPerfObjectHW>
extern __imp_PdhGetDefaultPerfObjectW:PANYARGS
PdhGetDefaultPerfObjectW TEXTEQU <__imp_PdhGetDefaultPerfObjectW>
extern __imp_PdhGetDllVersion:PANYARGS
PdhGetDllVersion TEXTEQU <__imp_PdhGetDllVersion>
extern __imp_PdhGetFormattedCounterArrayA:PANYARGS
PdhGetFormattedCounterArray  TEXTEQU <__imp_PdhGetFormattedCounterArrayA>
extern __imp_PdhGetFormattedCounterArrayW:PANYARGS
PdhGetFormattedCounterArrayW TEXTEQU <__imp_PdhGetFormattedCounterArrayW>
extern __imp_PdhGetFormattedCounterValue:PANYARGS
PdhGetFormattedCounterValue TEXTEQU <__imp_PdhGetFormattedCounterValue>
extern __imp_PdhGetLogFileSize:PANYARGS
PdhGetLogFileSize TEXTEQU <__imp_PdhGetLogFileSize>
extern __imp_PdhGetLogFileTypeA:PANYARGS
PdhGetLogFileType  TEXTEQU <__imp_PdhGetLogFileTypeA>
extern __imp_PdhGetLogFileTypeW:PANYARGS
PdhGetLogFileTypeW TEXTEQU <__imp_PdhGetLogFileTypeW>
extern __imp_PdhGetLogSetGUID:PANYARGS
PdhGetLogSetGUID TEXTEQU <__imp_PdhGetLogSetGUID>
extern __imp_PdhGetRawCounterArrayA:PANYARGS
PdhGetRawCounterArray  TEXTEQU <__imp_PdhGetRawCounterArrayA>
extern __imp_PdhGetRawCounterArrayW:PANYARGS
PdhGetRawCounterArrayW TEXTEQU <__imp_PdhGetRawCounterArrayW>
extern __imp_PdhGetRawCounterValue:PANYARGS
PdhGetRawCounterValue TEXTEQU <__imp_PdhGetRawCounterValue>
extern __imp_PdhIsRealTimeQuery:PANYARGS
PdhIsRealTimeQuery TEXTEQU <__imp_PdhIsRealTimeQuery>
extern __imp_PdhListLogFileHeaderA:PANYARGS
PdhListLogFileHeader  TEXTEQU <__imp_PdhListLogFileHeaderA>
extern __imp_PdhListLogFileHeaderW:PANYARGS
PdhListLogFileHeaderW TEXTEQU <__imp_PdhListLogFileHeaderW>
extern __imp_PdhLookupPerfIndexByNameA:PANYARGS
PdhLookupPerfIndexByName  TEXTEQU <__imp_PdhLookupPerfIndexByNameA>
extern __imp_PdhLookupPerfIndexByNameW:PANYARGS
PdhLookupPerfIndexByNameW TEXTEQU <__imp_PdhLookupPerfIndexByNameW>
extern __imp_PdhLookupPerfNameByIndexA:PANYARGS
PdhLookupPerfNameByIndex  TEXTEQU <__imp_PdhLookupPerfNameByIndexA>
extern __imp_PdhLookupPerfNameByIndexW:PANYARGS
PdhLookupPerfNameByIndexW TEXTEQU <__imp_PdhLookupPerfNameByIndexW>
extern __imp_PdhMakeCounterPathA:PANYARGS
PdhMakeCounterPath  TEXTEQU <__imp_PdhMakeCounterPathA>
extern __imp_PdhMakeCounterPathW:PANYARGS
PdhMakeCounterPathW TEXTEQU <__imp_PdhMakeCounterPathW>
extern __imp_PdhOpenLogA:PANYARGS
PdhOpenLog  TEXTEQU <__imp_PdhOpenLogA>
extern __imp_PdhOpenLogW:PANYARGS
PdhOpenLogW TEXTEQU <__imp_PdhOpenLogW>
extern __imp_PdhOpenQuery:PANYARGS
PdhOpenQuery TEXTEQU <__imp_PdhOpenQuery>
extern __imp_PdhOpenQueryA:PANYARGS
PdhOpenQuery  TEXTEQU <__imp_PdhOpenQueryA>
extern __imp_PdhOpenQueryH:PANYARGS
PdhOpenQueryH TEXTEQU <__imp_PdhOpenQueryH>
extern __imp_PdhOpenQueryW:PANYARGS
PdhOpenQueryW TEXTEQU <__imp_PdhOpenQueryW>
extern __imp_PdhParseCounterPathA:PANYARGS
PdhParseCounterPath  TEXTEQU <__imp_PdhParseCounterPathA>
extern __imp_PdhParseCounterPathW:PANYARGS
PdhParseCounterPathW TEXTEQU <__imp_PdhParseCounterPathW>
extern __imp_PdhParseInstanceNameA:PANYARGS
PdhParseInstanceName  TEXTEQU <__imp_PdhParseInstanceNameA>
extern __imp_PdhParseInstanceNameW:PANYARGS
PdhParseInstanceNameW TEXTEQU <__imp_PdhParseInstanceNameW>
extern __imp_PdhPlaAddItemA:PANYARGS
PdhPlaAddItem  TEXTEQU <__imp_PdhPlaAddItemA>
extern __imp_PdhPlaAddItemW:PANYARGS
PdhPlaAddItemW TEXTEQU <__imp_PdhPlaAddItemW>
extern __imp_PdhPlaCreateA:PANYARGS
PdhPlaCreate  TEXTEQU <__imp_PdhPlaCreateA>
extern __imp_PdhPlaCreateW:PANYARGS
PdhPlaCreateW TEXTEQU <__imp_PdhPlaCreateW>
extern __imp_PdhPlaDeleteA:PANYARGS
PdhPlaDelete  TEXTEQU <__imp_PdhPlaDeleteA>
extern __imp_PdhPlaDeleteW:PANYARGS
PdhPlaDeleteW TEXTEQU <__imp_PdhPlaDeleteW>
extern __imp_PdhPlaDowngradeW:PANYARGS
PdhPlaDowngradeW TEXTEQU <__imp_PdhPlaDowngradeW>
extern __imp_PdhPlaEnumCollectionsA:PANYARGS
PdhPlaEnumCollections  TEXTEQU <__imp_PdhPlaEnumCollectionsA>
extern __imp_PdhPlaEnumCollectionsW:PANYARGS
PdhPlaEnumCollectionsW TEXTEQU <__imp_PdhPlaEnumCollectionsW>
extern __imp_PdhPlaGetInfoA:PANYARGS
PdhPlaGetInfo  TEXTEQU <__imp_PdhPlaGetInfoA>
extern __imp_PdhPlaGetInfoW:PANYARGS
PdhPlaGetInfoW TEXTEQU <__imp_PdhPlaGetInfoW>
extern __imp_PdhPlaGetLogFileNameW:PANYARGS
PdhPlaGetLogFileNameW TEXTEQU <__imp_PdhPlaGetLogFileNameW>
extern __imp_PdhPlaGetScheduleA:PANYARGS
PdhPlaGetSchedule  TEXTEQU <__imp_PdhPlaGetScheduleA>
extern __imp_PdhPlaGetScheduleW:PANYARGS
PdhPlaGetScheduleW TEXTEQU <__imp_PdhPlaGetScheduleW>
extern __imp_PdhPlaRemoveAllItemsA:PANYARGS
PdhPlaRemoveAllItems  TEXTEQU <__imp_PdhPlaRemoveAllItemsA>
extern __imp_PdhPlaRemoveAllItemsW:PANYARGS
PdhPlaRemoveAllItemsW TEXTEQU <__imp_PdhPlaRemoveAllItemsW>
extern __imp_PdhPlaScheduleA:PANYARGS
PdhPlaSchedule  TEXTEQU <__imp_PdhPlaScheduleA>
extern __imp_PdhPlaScheduleW:PANYARGS
PdhPlaScheduleW TEXTEQU <__imp_PdhPlaScheduleW>
extern __imp_PdhPlaSetInfoA:PANYARGS
PdhPlaSetInfo  TEXTEQU <__imp_PdhPlaSetInfoA>
extern __imp_PdhPlaSetInfoW:PANYARGS
PdhPlaSetInfoW TEXTEQU <__imp_PdhPlaSetInfoW>
extern __imp_PdhPlaSetItemListA:PANYARGS
PdhPlaSetItemList  TEXTEQU <__imp_PdhPlaSetItemListA>
extern __imp_PdhPlaSetItemListW:PANYARGS
PdhPlaSetItemListW TEXTEQU <__imp_PdhPlaSetItemListW>
extern __imp_PdhPlaSetRunAsA:PANYARGS
PdhPlaSetRunAs  TEXTEQU <__imp_PdhPlaSetRunAsA>
extern __imp_PdhPlaSetRunAsW:PANYARGS
PdhPlaSetRunAsW TEXTEQU <__imp_PdhPlaSetRunAsW>
extern __imp_PdhPlaStartA:PANYARGS
PdhPlaStart  TEXTEQU <__imp_PdhPlaStartA>
extern __imp_PdhPlaStartW:PANYARGS
PdhPlaStartW TEXTEQU <__imp_PdhPlaStartW>
extern __imp_PdhPlaStopA:PANYARGS
PdhPlaStop  TEXTEQU <__imp_PdhPlaStopA>
extern __imp_PdhPlaStopW:PANYARGS
PdhPlaStopW TEXTEQU <__imp_PdhPlaStopW>
extern __imp_PdhPlaUpgradeW:PANYARGS
PdhPlaUpgradeW TEXTEQU <__imp_PdhPlaUpgradeW>
extern __imp_PdhPlaValidateInfoA:PANYARGS
PdhPlaValidateInfo  TEXTEQU <__imp_PdhPlaValidateInfoA>
extern __imp_PdhPlaValidateInfoW:PANYARGS
PdhPlaValidateInfoW TEXTEQU <__imp_PdhPlaValidateInfoW>
extern __imp_PdhReadRawLogRecord:PANYARGS
PdhReadRawLogRecord TEXTEQU <__imp_PdhReadRawLogRecord>
extern __imp_PdhRelogA:PANYARGS
PdhRelog  TEXTEQU <__imp_PdhRelogA>
extern __imp_PdhRelogW:PANYARGS
PdhRelogW TEXTEQU <__imp_PdhRelogW>
extern __imp_PdhRemoveCounter:PANYARGS
PdhRemoveCounter TEXTEQU <__imp_PdhRemoveCounter>
extern __imp_PdhSelectDataSourceA:PANYARGS
PdhSelectDataSource  TEXTEQU <__imp_PdhSelectDataSourceA>
extern __imp_PdhSelectDataSourceW:PANYARGS
PdhSelectDataSourceW TEXTEQU <__imp_PdhSelectDataSourceW>
extern __imp_PdhSetCounterScaleFactor:PANYARGS
PdhSetCounterScaleFactor TEXTEQU <__imp_PdhSetCounterScaleFactor>
extern __imp_PdhSetDefaultRealTimeDataSource:PANYARGS
PdhSetDefaultRealTimeDataSource TEXTEQU <__imp_PdhSetDefaultRealTimeDataSource>
extern __imp_PdhSetLogSetRunID:PANYARGS
PdhSetLogSetRunID TEXTEQU <__imp_PdhSetLogSetRunID>
extern __imp_PdhSetQueryTimeRange:PANYARGS
PdhSetQueryTimeRange TEXTEQU <__imp_PdhSetQueryTimeRange>
extern __imp_PdhTranslate009CounterA:PANYARGS
PdhTranslate009Counter  TEXTEQU <__imp_PdhTranslate009CounterA>
extern __imp_PdhTranslate009CounterW:PANYARGS
PdhTranslate009CounterW TEXTEQU <__imp_PdhTranslate009CounterW>
extern __imp_PdhTranslateLocaleCounterA:PANYARGS
PdhTranslateLocaleCounter  TEXTEQU <__imp_PdhTranslateLocaleCounterA>
extern __imp_PdhTranslateLocaleCounterW:PANYARGS
PdhTranslateLocaleCounterW TEXTEQU <__imp_PdhTranslateLocaleCounterW>
extern __imp_PdhUpdateLogA:PANYARGS
PdhUpdateLog  TEXTEQU <__imp_PdhUpdateLogA>
extern __imp_PdhUpdateLogFileCatalog:PANYARGS
PdhUpdateLogFileCatalog TEXTEQU <__imp_PdhUpdateLogFileCatalog>
extern __imp_PdhUpdateLogW:PANYARGS
PdhUpdateLogW TEXTEQU <__imp_PdhUpdateLogW>
extern __imp_PdhValidatePathA:PANYARGS
PdhValidatePath  TEXTEQU <__imp_PdhValidatePathA>
extern __imp_PdhValidatePathW:PANYARGS
PdhValidatePathW TEXTEQU <__imp_PdhValidatePathW>
extern __imp_PdhVbAddCounter:PANYARGS
PdhVbAddCounter TEXTEQU <__imp_PdhVbAddCounter>
extern __imp_PdhVbCreateCounterPathList:PANYARGS
PdhVbCreateCounterPathList TEXTEQU <__imp_PdhVbCreateCounterPathList>
extern __imp_PdhVbGetCounterPathElements:PANYARGS
PdhVbGetCounterPathElements TEXTEQU <__imp_PdhVbGetCounterPathElements>
extern __imp_PdhVbGetCounterPathFromList:PANYARGS
PdhVbGetCounterPathFromList TEXTEQU <__imp_PdhVbGetCounterPathFromList>
extern __imp_PdhVbGetDoubleCounterValue:PANYARGS
PdhVbGetDoubleCounterValue TEXTEQU <__imp_PdhVbGetDoubleCounterValue>
extern __imp_PdhVbGetLogFileSize:PANYARGS
PdhVbGetLogFileSize TEXTEQU <__imp_PdhVbGetLogFileSize>
extern __imp_PdhVbGetOneCounterPath:PANYARGS
PdhVbGetOneCounterPath TEXTEQU <__imp_PdhVbGetOneCounterPath>
extern __imp_PdhVbIsGoodStatus:PANYARGS
PdhVbIsGoodStatus TEXTEQU <__imp_PdhVbIsGoodStatus>
extern __imp_PdhVbOpenLog:PANYARGS
PdhVbOpenLog TEXTEQU <__imp_PdhVbOpenLog>
extern __imp_PdhVbOpenQuery:PANYARGS
PdhVbOpenQuery TEXTEQU <__imp_PdhVbOpenQuery>
extern __imp_PdhVbUpdateLog:PANYARGS
PdhVbUpdateLog TEXTEQU <__imp_PdhVbUpdateLog>
extern __imp_PdhVerifySQLDBA:PANYARGS
PdhVerifySQLDB  TEXTEQU <__imp_PdhVerifySQLDBA>
extern __imp_PdhVerifySQLDBW:PANYARGS
PdhVerifySQLDBW TEXTEQU <__imp_PdhVerifySQLDBW>
extern __imp_PdhiPla2003SP1Installed:PANYARGS
PdhiPla2003SP1Installed TEXTEQU <__imp_PdhiPla2003SP1Installed>
extern __imp_PdhiPlaDowngrade:PANYARGS
PdhiPlaDowngrade TEXTEQU <__imp_PdhiPlaDowngrade>
extern __imp_PdhiPlaFormatBlanksA:PANYARGS
PdhiPlaFormatBlanks  TEXTEQU <__imp_PdhiPlaFormatBlanksA>
extern __imp_PdhiPlaFormatBlanksW:PANYARGS
PdhiPlaFormatBlanksW TEXTEQU <__imp_PdhiPlaFormatBlanksW>
extern __imp_PdhiPlaGetVersion:PANYARGS
PdhiPlaGetVersion TEXTEQU <__imp_PdhiPlaGetVersion>
extern __imp_PdhiPlaRunAs:PANYARGS
PdhiPlaRunAs TEXTEQU <__imp_PdhiPlaRunAs>
extern __imp_PdhiPlaSetRunAs:PANYARGS
PdhiPlaSetRunAs TEXTEQU <__imp_PdhiPlaSetRunAs>
extern __imp_PdhiPlaUpgrade:PANYARGS
PdhiPlaUpgrade TEXTEQU <__imp_PdhiPlaUpgrade>
extern __imp_PlaTimeInfoToMilliSeconds:PANYARGS
PlaTimeInfoToMilliSeconds TEXTEQU <__imp_PlaTimeInfoToMilliSeconds>
