extern __imp_UsePPWForPrintTo:PANYARGS
UsePPWForPrintTo TEXTEQU <__imp_UsePPWForPrintTo>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
