extern __imp_PIDGenA:PANYARGS
PIDGen  TEXTEQU <__imp_PIDGenA>
extern __imp_PIDGenW:PANYARGS
PIDGenW TEXTEQU <__imp_PIDGenW>
extern __imp_PIDGenSimpA:PANYARGS
PIDGenSimp  TEXTEQU <__imp_PIDGenSimpA>
extern __imp_PIDGenSimpW:PANYARGS
PIDGenSimpW TEXTEQU <__imp_PIDGenSimpW>
extern __imp_SetupPIDGenA:PANYARGS
SetupPIDGen  TEXTEQU <__imp_SetupPIDGenA>
extern __imp_SetupPIDGenW:PANYARGS
SetupPIDGenW TEXTEQU <__imp_SetupPIDGenW>
extern __imp_PIDGenExA:PANYARGS
PIDGenEx  TEXTEQU <__imp_PIDGenExA>
extern __imp_PIDGenExW:PANYARGS
PIDGenExW TEXTEQU <__imp_PIDGenExW>
extern __imp_SetupPIDGenExA:PANYARGS
SetupPIDGenEx  TEXTEQU <__imp_SetupPIDGenExA>
extern __imp_SetupPIDGenExW:PANYARGS
SetupPIDGenExW TEXTEQU <__imp_SetupPIDGenExW>
extern __imp_PIDGenEx2A:PANYARGS
PIDGenEx2  TEXTEQU <__imp_PIDGenEx2A>
extern __imp_PIDGenEx2W:PANYARGS
PIDGenEx2W TEXTEQU <__imp_PIDGenEx2W>
