extern __imp_ConstructPrinterFriendlyName:PANYARGS
ConstructPrinterFriendlyName TEXTEQU <__imp_ConstructPrinterFriendlyName>
extern __imp_DocumentPropertiesWrap:PANYARGS
DocumentPropertiesWrap TEXTEQU <__imp_DocumentPropertiesWrap>
extern __imp_PnPInterface:PANYARGS
PnPInterface TEXTEQU <__imp_PnPInterface>
extern __imp_PrintUIEntryW:PANYARGS
PrintUIEntryW TEXTEQU <__imp_PrintUIEntryW>
extern __imp_PrinterPropPageProvider:PANYARGS
PrinterPropPageProvider TEXTEQU <__imp_PrinterPropPageProvider>
extern __imp_ConnectToPrinterDlg:PANYARGS
ConnectToPrinterDlg TEXTEQU <__imp_ConnectToPrinterDlg>
extern __imp_ConnectToPrinterPropertyPage:PANYARGS
ConnectToPrinterPropertyPage TEXTEQU <__imp_ConnectToPrinterPropertyPage>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_GetLegacyPrintUI:PANYARGS
GetLegacyPrintUI TEXTEQU <__imp_GetLegacyPrintUI>
extern __imp_PrintNotifyTray_Exit:PANYARGS
PrintNotifyTray_Exit TEXTEQU <__imp_PrintNotifyTray_Exit>
extern __imp_PrintNotifyTray_Init:PANYARGS
PrintNotifyTray_Init TEXTEQU <__imp_PrintNotifyTray_Init>
extern __imp_RegisterPrintNotify:PANYARGS
RegisterPrintNotify TEXTEQU <__imp_RegisterPrintNotify>
extern __imp_ShowErrorMessageHR:PANYARGS
ShowErrorMessageHR TEXTEQU <__imp_ShowErrorMessageHR>
extern __imp_ShowErrorMessageSC:PANYARGS
ShowErrorMessageSC TEXTEQU <__imp_ShowErrorMessageSC>
extern __imp_UnregisterPrintNotify:PANYARGS
UnregisterPrintNotify TEXTEQU <__imp_UnregisterPrintNotify>
extern __imp_bFolderEnumPrinters:PANYARGS
bFolderEnumPrinters TEXTEQU <__imp_bFolderEnumPrinters>
extern __imp_bFolderGetPrinter:PANYARGS
bFolderGetPrinter TEXTEQU <__imp_bFolderGetPrinter>
extern __imp_bFolderRefresh:PANYARGS
bFolderRefresh TEXTEQU <__imp_bFolderRefresh>
extern __imp_bPrinterSetup:PANYARGS
bPrinterSetup TEXTEQU <__imp_bPrinterSetup>
extern __imp_vDocumentDefaults:PANYARGS
vDocumentDefaults TEXTEQU <__imp_vDocumentDefaults>
extern __imp_vPrinterPropPages:PANYARGS
vPrinterPropPages TEXTEQU <__imp_vPrinterPropPages>
extern __imp_vQueueCreate:PANYARGS
vQueueCreate TEXTEQU <__imp_vQueueCreate>
extern __imp_vServerPropPages:PANYARGS
vServerPropPages TEXTEQU <__imp_vServerPropPages>
extern __imp_printui_ordinal26:PANYARGS
printui_ordinal26 TEXTEQU <__imp_printui_ordinal26>
extern __imp_printui_ordinal27:PANYARGS
printui_ordinal27 TEXTEQU <__imp_printui_ordinal27>
extern __imp_printui_ordinal28:PANYARGS
printui_ordinal28 TEXTEQU <__imp_printui_ordinal28>
extern __imp_printui_ordinal29:PANYARGS
printui_ordinal29 TEXTEQU <__imp_printui_ordinal29>
extern __imp_printui_ordinal30:PANYARGS
printui_ordinal30 TEXTEQU <__imp_printui_ordinal30>
extern __imp_printui_ordinal31:PANYARGS
printui_ordinal31 TEXTEQU <__imp_printui_ordinal31>
extern __imp_printui_ordinal32:PANYARGS
printui_ordinal32 TEXTEQU <__imp_printui_ordinal32>
extern __imp_printui_ordinal33:PANYARGS
printui_ordinal33 TEXTEQU <__imp_printui_ordinal33>
extern __imp_printui_ordinal34:PANYARGS
printui_ordinal34 TEXTEQU <__imp_printui_ordinal34>
extern __imp_printui_ordinal35:PANYARGS
printui_ordinal35 TEXTEQU <__imp_printui_ordinal35>
extern __imp_printui_ordinal36:PANYARGS
printui_ordinal36 TEXTEQU <__imp_printui_ordinal36>
extern __imp_printui_ordinal37:PANYARGS
printui_ordinal37 TEXTEQU <__imp_printui_ordinal37>
extern __imp_printui_ordinal38:PANYARGS
printui_ordinal38 TEXTEQU <__imp_printui_ordinal38>
extern __imp_printui_ordinal39:PANYARGS
printui_ordinal39 TEXTEQU <__imp_printui_ordinal39>
extern __imp_printui_ordinal40:PANYARGS
printui_ordinal40 TEXTEQU <__imp_printui_ordinal40>
extern __imp_printui_ordinal41:PANYARGS
printui_ordinal41 TEXTEQU <__imp_printui_ordinal41>
extern __imp_printui_ordinal42:PANYARGS
printui_ordinal42 TEXTEQU <__imp_printui_ordinal42>
extern __imp_printui_ordinal43:PANYARGS
printui_ordinal43 TEXTEQU <__imp_printui_ordinal43>
extern __imp_printui_ordinal44:PANYARGS
printui_ordinal44 TEXTEQU <__imp_printui_ordinal44>
extern __imp_printui_ordinal45:PANYARGS
printui_ordinal45 TEXTEQU <__imp_printui_ordinal45>
extern __imp_printui_ordinal46:PANYARGS
printui_ordinal46 TEXTEQU <__imp_printui_ordinal46>
extern __imp_printui_ordinal47:PANYARGS
printui_ordinal47 TEXTEQU <__imp_printui_ordinal47>
extern __imp_printui_ordinal48:PANYARGS
printui_ordinal48 TEXTEQU <__imp_printui_ordinal48>
extern __imp_printui_ordinal49:PANYARGS
printui_ordinal49 TEXTEQU <__imp_printui_ordinal49>
extern __imp_printui_ordinal50:PANYARGS
printui_ordinal50 TEXTEQU <__imp_printui_ordinal50>
extern __imp_printui_ordinal51:PANYARGS
printui_ordinal51 TEXTEQU <__imp_printui_ordinal51>
extern __imp_printui_ordinal52:PANYARGS
printui_ordinal52 TEXTEQU <__imp_printui_ordinal52>
extern __imp_printui_ordinal53:PANYARGS
printui_ordinal53 TEXTEQU <__imp_printui_ordinal53>
extern __imp_printui_ordinal54:PANYARGS
printui_ordinal54 TEXTEQU <__imp_printui_ordinal54>
extern __imp_printui_ordinal55:PANYARGS
printui_ordinal55 TEXTEQU <__imp_printui_ordinal55>
extern __imp_printui_ordinal56:PANYARGS
printui_ordinal56 TEXTEQU <__imp_printui_ordinal56>
extern __imp_printui_ordinal57:PANYARGS
printui_ordinal57 TEXTEQU <__imp_printui_ordinal57>
extern __imp_printui_ordinal58:PANYARGS
printui_ordinal58 TEXTEQU <__imp_printui_ordinal58>
extern __imp_printui_ordinal59:PANYARGS
printui_ordinal59 TEXTEQU <__imp_printui_ordinal59>
extern __imp_printui_ordinal60:PANYARGS
printui_ordinal60 TEXTEQU <__imp_printui_ordinal60>
extern __imp_printui_ordinal61:PANYARGS
printui_ordinal61 TEXTEQU <__imp_printui_ordinal61>
extern __imp_printui_ordinal62:PANYARGS
printui_ordinal62 TEXTEQU <__imp_printui_ordinal62>
extern __imp_printui_ordinal63:PANYARGS
printui_ordinal63 TEXTEQU <__imp_printui_ordinal63>
extern __imp_printui_ordinal64:PANYARGS
printui_ordinal64 TEXTEQU <__imp_printui_ordinal64>
extern __imp_printui_ordinal65:PANYARGS
printui_ordinal65 TEXTEQU <__imp_printui_ordinal65>
extern __imp_printui_ordinal66:PANYARGS
printui_ordinal66 TEXTEQU <__imp_printui_ordinal66>
extern __imp_printui_ordinal67:PANYARGS
printui_ordinal67 TEXTEQU <__imp_printui_ordinal67>
extern __imp_printui_ordinal68:PANYARGS
printui_ordinal68 TEXTEQU <__imp_printui_ordinal68>
extern __imp_printui_ordinal69:PANYARGS
printui_ordinal69 TEXTEQU <__imp_printui_ordinal69>
extern __imp_printui_ordinal70:PANYARGS
printui_ordinal70 TEXTEQU <__imp_printui_ordinal70>
extern __imp_printui_ordinal71:PANYARGS
printui_ordinal71 TEXTEQU <__imp_printui_ordinal71>
extern __imp_printui_ordinal72:PANYARGS
printui_ordinal72 TEXTEQU <__imp_printui_ordinal72>
extern __imp_printui_ordinal73:PANYARGS
printui_ordinal73 TEXTEQU <__imp_printui_ordinal73>
extern __imp_printui_ordinal74:PANYARGS
printui_ordinal74 TEXTEQU <__imp_printui_ordinal74>
extern __imp_printui_ordinal75:PANYARGS
printui_ordinal75 TEXTEQU <__imp_printui_ordinal75>
extern __imp_printui_ordinal76:PANYARGS
printui_ordinal76 TEXTEQU <__imp_printui_ordinal76>
extern __imp_printui_ordinal77:PANYARGS
printui_ordinal77 TEXTEQU <__imp_printui_ordinal77>
extern __imp_printui_ordinal78:PANYARGS
printui_ordinal78 TEXTEQU <__imp_printui_ordinal78>
extern __imp_printui_ordinal79:PANYARGS
printui_ordinal79 TEXTEQU <__imp_printui_ordinal79>
extern __imp_printui_ordinal80:PANYARGS
printui_ordinal80 TEXTEQU <__imp_printui_ordinal80>
extern __imp_printui_ordinal81:PANYARGS
printui_ordinal81 TEXTEQU <__imp_printui_ordinal81>
extern __imp_printui_ordinal82:PANYARGS
printui_ordinal82 TEXTEQU <__imp_printui_ordinal82>
extern __imp_printui_ordinal83:PANYARGS
printui_ordinal83 TEXTEQU <__imp_printui_ordinal83>
extern __imp_printui_ordinal84:PANYARGS
printui_ordinal84 TEXTEQU <__imp_printui_ordinal84>
extern __imp_printui_ordinal85:PANYARGS
printui_ordinal85 TEXTEQU <__imp_printui_ordinal85>
extern __imp_printui_ordinal86:PANYARGS
printui_ordinal86 TEXTEQU <__imp_printui_ordinal86>
extern __imp_printui_ordinal87:PANYARGS
printui_ordinal87 TEXTEQU <__imp_printui_ordinal87>
extern __imp_printui_ordinal88:PANYARGS
printui_ordinal88 TEXTEQU <__imp_printui_ordinal88>
extern __imp_printui_ordinal89:PANYARGS
printui_ordinal89 TEXTEQU <__imp_printui_ordinal89>
extern __imp_printui_ordinal90:PANYARGS
printui_ordinal90 TEXTEQU <__imp_printui_ordinal90>
extern __imp_printui_ordinal91:PANYARGS
printui_ordinal91 TEXTEQU <__imp_printui_ordinal91>
extern __imp_printui_ordinal92:PANYARGS
printui_ordinal92 TEXTEQU <__imp_printui_ordinal92>
extern __imp_printui_ordinal93:PANYARGS
printui_ordinal93 TEXTEQU <__imp_printui_ordinal93>
extern __imp_printui_ordinal94:PANYARGS
printui_ordinal94 TEXTEQU <__imp_printui_ordinal94>
extern __imp_printui_ordinal95:PANYARGS
printui_ordinal95 TEXTEQU <__imp_printui_ordinal95>
extern __imp_printui_ordinal96:PANYARGS
printui_ordinal96 TEXTEQU <__imp_printui_ordinal96>
extern __imp_printui_ordinal97:PANYARGS
printui_ordinal97 TEXTEQU <__imp_printui_ordinal97>
extern __imp_printui_ordinal98:PANYARGS
printui_ordinal98 TEXTEQU <__imp_printui_ordinal98>
extern __imp_printui_ordinal99:PANYARGS
printui_ordinal99 TEXTEQU <__imp_printui_ordinal99>
extern __imp_printui_ordinal100:PANYARGS
printui_ordinal100 TEXTEQU <__imp_printui_ordinal100>
extern __imp_printui_ordinal101:PANYARGS
printui_ordinal101 TEXTEQU <__imp_printui_ordinal101>
extern __imp_printui_ordinal102:PANYARGS
printui_ordinal102 TEXTEQU <__imp_printui_ordinal102>
extern __imp_printui_ordinal103:PANYARGS
printui_ordinal103 TEXTEQU <__imp_printui_ordinal103>
extern __imp_printui_ordinal104:PANYARGS
printui_ordinal104 TEXTEQU <__imp_printui_ordinal104>
extern __imp_printui_ordinal105:PANYARGS
printui_ordinal105 TEXTEQU <__imp_printui_ordinal105>
extern __imp_printui_ordinal106:PANYARGS
printui_ordinal106 TEXTEQU <__imp_printui_ordinal106>
extern __imp_printui_ordinal107:PANYARGS
printui_ordinal107 TEXTEQU <__imp_printui_ordinal107>
extern __imp_printui_ordinal108:PANYARGS
printui_ordinal108 TEXTEQU <__imp_printui_ordinal108>
extern __imp_printui_ordinal109:PANYARGS
printui_ordinal109 TEXTEQU <__imp_printui_ordinal109>
extern __imp_printui_ordinal110:PANYARGS
printui_ordinal110 TEXTEQU <__imp_printui_ordinal110>
extern __imp_printui_ordinal111:PANYARGS
printui_ordinal111 TEXTEQU <__imp_printui_ordinal111>
extern __imp_printui_ordinal112:PANYARGS
printui_ordinal112 TEXTEQU <__imp_printui_ordinal112>
extern __imp_printui_ordinal113:PANYARGS
printui_ordinal113 TEXTEQU <__imp_printui_ordinal113>
extern __imp_printui_ordinal114:PANYARGS
printui_ordinal114 TEXTEQU <__imp_printui_ordinal114>
extern __imp_printui_ordinal115:PANYARGS
printui_ordinal115 TEXTEQU <__imp_printui_ordinal115>
extern __imp_printui_ordinal116:PANYARGS
printui_ordinal116 TEXTEQU <__imp_printui_ordinal116>
extern __imp_printui_ordinal117:PANYARGS
printui_ordinal117 TEXTEQU <__imp_printui_ordinal117>
extern __imp_printui_ordinal118:PANYARGS
printui_ordinal118 TEXTEQU <__imp_printui_ordinal118>
extern __imp_printui_ordinal119:PANYARGS
printui_ordinal119 TEXTEQU <__imp_printui_ordinal119>
extern __imp_printui_ordinal120:PANYARGS
printui_ordinal120 TEXTEQU <__imp_printui_ordinal120>
extern __imp_printui_ordinal121:PANYARGS
printui_ordinal121 TEXTEQU <__imp_printui_ordinal121>
extern __imp_printui_ordinal122:PANYARGS
printui_ordinal122 TEXTEQU <__imp_printui_ordinal122>
extern __imp_printui_ordinal123:PANYARGS
printui_ordinal123 TEXTEQU <__imp_printui_ordinal123>
extern __imp_printui_ordinal124:PANYARGS
printui_ordinal124 TEXTEQU <__imp_printui_ordinal124>
extern __imp_printui_ordinal125:PANYARGS
printui_ordinal125 TEXTEQU <__imp_printui_ordinal125>
extern __imp_printui_ordinal126:PANYARGS
printui_ordinal126 TEXTEQU <__imp_printui_ordinal126>
extern __imp_printui_ordinal127:PANYARGS
printui_ordinal127 TEXTEQU <__imp_printui_ordinal127>
extern __imp_printui_ordinal128:PANYARGS
printui_ordinal128 TEXTEQU <__imp_printui_ordinal128>
extern __imp_printui_ordinal129:PANYARGS
printui_ordinal129 TEXTEQU <__imp_printui_ordinal129>
extern __imp_printui_ordinal130:PANYARGS
printui_ordinal130 TEXTEQU <__imp_printui_ordinal130>
extern __imp_printui_ordinal131:PANYARGS
printui_ordinal131 TEXTEQU <__imp_printui_ordinal131>
extern __imp_printui_ordinal132:PANYARGS
printui_ordinal132 TEXTEQU <__imp_printui_ordinal132>
extern __imp_printui_ordinal133:PANYARGS
printui_ordinal133 TEXTEQU <__imp_printui_ordinal133>
extern __imp_printui_ordinal134:PANYARGS
printui_ordinal134 TEXTEQU <__imp_printui_ordinal134>
extern __imp_printui_ordinal135:PANYARGS
printui_ordinal135 TEXTEQU <__imp_printui_ordinal135>
extern __imp_printui_ordinal136:PANYARGS
printui_ordinal136 TEXTEQU <__imp_printui_ordinal136>
extern __imp_printui_ordinal137:PANYARGS
printui_ordinal137 TEXTEQU <__imp_printui_ordinal137>
extern __imp_printui_ordinal138:PANYARGS
printui_ordinal138 TEXTEQU <__imp_printui_ordinal138>
extern __imp_printui_ordinal139:PANYARGS
printui_ordinal139 TEXTEQU <__imp_printui_ordinal139>
extern __imp_printui_ordinal140:PANYARGS
printui_ordinal140 TEXTEQU <__imp_printui_ordinal140>
extern __imp_printui_ordinal141:PANYARGS
printui_ordinal141 TEXTEQU <__imp_printui_ordinal141>
extern __imp_printui_ordinal142:PANYARGS
printui_ordinal142 TEXTEQU <__imp_printui_ordinal142>
extern __imp_printui_ordinal143:PANYARGS
printui_ordinal143 TEXTEQU <__imp_printui_ordinal143>
extern __imp_printui_ordinal144:PANYARGS
printui_ordinal144 TEXTEQU <__imp_printui_ordinal144>
extern __imp_printui_ordinal145:PANYARGS
printui_ordinal145 TEXTEQU <__imp_printui_ordinal145>
extern __imp_printui_ordinal146:PANYARGS
printui_ordinal146 TEXTEQU <__imp_printui_ordinal146>
extern __imp_printui_ordinal147:PANYARGS
printui_ordinal147 TEXTEQU <__imp_printui_ordinal147>
extern __imp_printui_ordinal148:PANYARGS
printui_ordinal148 TEXTEQU <__imp_printui_ordinal148>
extern __imp_printui_ordinal149:PANYARGS
printui_ordinal149 TEXTEQU <__imp_printui_ordinal149>
extern __imp_printui_ordinal150:PANYARGS
printui_ordinal150 TEXTEQU <__imp_printui_ordinal150>
extern __imp_printui_ordinal151:PANYARGS
printui_ordinal151 TEXTEQU <__imp_printui_ordinal151>
extern __imp_printui_ordinal152:PANYARGS
printui_ordinal152 TEXTEQU <__imp_printui_ordinal152>
extern __imp_printui_ordinal153:PANYARGS
printui_ordinal153 TEXTEQU <__imp_printui_ordinal153>
extern __imp_printui_ordinal154:PANYARGS
printui_ordinal154 TEXTEQU <__imp_printui_ordinal154>
extern __imp_printui_ordinal155:PANYARGS
printui_ordinal155 TEXTEQU <__imp_printui_ordinal155>
extern __imp_printui_ordinal156:PANYARGS
printui_ordinal156 TEXTEQU <__imp_printui_ordinal156>
extern __imp_printui_ordinal157:PANYARGS
printui_ordinal157 TEXTEQU <__imp_printui_ordinal157>
extern __imp_printui_ordinal158:PANYARGS
printui_ordinal158 TEXTEQU <__imp_printui_ordinal158>
extern __imp_printui_ordinal159:PANYARGS
printui_ordinal159 TEXTEQU <__imp_printui_ordinal159>
extern __imp_printui_ordinal160:PANYARGS
printui_ordinal160 TEXTEQU <__imp_printui_ordinal160>
extern __imp_printui_ordinal161:PANYARGS
printui_ordinal161 TEXTEQU <__imp_printui_ordinal161>
extern __imp_printui_ordinal162:PANYARGS
printui_ordinal162 TEXTEQU <__imp_printui_ordinal162>
extern __imp_printui_ordinal163:PANYARGS
printui_ordinal163 TEXTEQU <__imp_printui_ordinal163>
extern __imp_printui_ordinal164:PANYARGS
printui_ordinal164 TEXTEQU <__imp_printui_ordinal164>
extern __imp_printui_ordinal165:PANYARGS
printui_ordinal165 TEXTEQU <__imp_printui_ordinal165>
extern __imp_printui_ordinal166:PANYARGS
printui_ordinal166 TEXTEQU <__imp_printui_ordinal166>
extern __imp_printui_ordinal167:PANYARGS
printui_ordinal167 TEXTEQU <__imp_printui_ordinal167>
extern __imp_printui_ordinal168:PANYARGS
printui_ordinal168 TEXTEQU <__imp_printui_ordinal168>
extern __imp_printui_ordinal169:PANYARGS
printui_ordinal169 TEXTEQU <__imp_printui_ordinal169>
extern __imp_printui_ordinal170:PANYARGS
printui_ordinal170 TEXTEQU <__imp_printui_ordinal170>
extern __imp_printui_ordinal171:PANYARGS
printui_ordinal171 TEXTEQU <__imp_printui_ordinal171>
extern __imp_printui_ordinal172:PANYARGS
printui_ordinal172 TEXTEQU <__imp_printui_ordinal172>
extern __imp_printui_ordinal173:PANYARGS
printui_ordinal173 TEXTEQU <__imp_printui_ordinal173>
extern __imp_printui_ordinal174:PANYARGS
printui_ordinal174 TEXTEQU <__imp_printui_ordinal174>
extern __imp_printui_ordinal175:PANYARGS
printui_ordinal175 TEXTEQU <__imp_printui_ordinal175>
extern __imp_printui_ordinal176:PANYARGS
printui_ordinal176 TEXTEQU <__imp_printui_ordinal176>
extern __imp_printui_ordinal177:PANYARGS
printui_ordinal177 TEXTEQU <__imp_printui_ordinal177>
extern __imp_printui_ordinal178:PANYARGS
printui_ordinal178 TEXTEQU <__imp_printui_ordinal178>
extern __imp_printui_ordinal179:PANYARGS
printui_ordinal179 TEXTEQU <__imp_printui_ordinal179>
extern __imp_printui_ordinal180:PANYARGS
printui_ordinal180 TEXTEQU <__imp_printui_ordinal180>
extern __imp_printui_ordinal181:PANYARGS
printui_ordinal181 TEXTEQU <__imp_printui_ordinal181>
extern __imp_printui_ordinal182:PANYARGS
printui_ordinal182 TEXTEQU <__imp_printui_ordinal182>
extern __imp_printui_ordinal183:PANYARGS
printui_ordinal183 TEXTEQU <__imp_printui_ordinal183>
extern __imp_printui_ordinal184:PANYARGS
printui_ordinal184 TEXTEQU <__imp_printui_ordinal184>
extern __imp_printui_ordinal185:PANYARGS
printui_ordinal185 TEXTEQU <__imp_printui_ordinal185>
extern __imp_printui_ordinal186:PANYARGS
printui_ordinal186 TEXTEQU <__imp_printui_ordinal186>
extern __imp_printui_ordinal187:PANYARGS
printui_ordinal187 TEXTEQU <__imp_printui_ordinal187>
extern __imp_printui_ordinal188:PANYARGS
printui_ordinal188 TEXTEQU <__imp_printui_ordinal188>
extern __imp_printui_ordinal189:PANYARGS
printui_ordinal189 TEXTEQU <__imp_printui_ordinal189>
extern __imp_printui_ordinal190:PANYARGS
printui_ordinal190 TEXTEQU <__imp_printui_ordinal190>
extern __imp_printui_ordinal191:PANYARGS
printui_ordinal191 TEXTEQU <__imp_printui_ordinal191>
extern __imp_printui_ordinal192:PANYARGS
printui_ordinal192 TEXTEQU <__imp_printui_ordinal192>
extern __imp_printui_ordinal193:PANYARGS
printui_ordinal193 TEXTEQU <__imp_printui_ordinal193>
extern __imp_printui_ordinal194:PANYARGS
printui_ordinal194 TEXTEQU <__imp_printui_ordinal194>
extern __imp_printui_ordinal195:PANYARGS
printui_ordinal195 TEXTEQU <__imp_printui_ordinal195>
extern __imp_printui_ordinal196:PANYARGS
printui_ordinal196 TEXTEQU <__imp_printui_ordinal196>
extern __imp_printui_ordinal197:PANYARGS
printui_ordinal197 TEXTEQU <__imp_printui_ordinal197>
extern __imp_printui_ordinal198:PANYARGS
printui_ordinal198 TEXTEQU <__imp_printui_ordinal198>
extern __imp_printui_ordinal199:PANYARGS
printui_ordinal199 TEXTEQU <__imp_printui_ordinal199>
extern __imp_printui_ordinal200:PANYARGS
printui_ordinal200 TEXTEQU <__imp_printui_ordinal200>
