extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_InitializeProfileMappingApi:PANYARGS
InitializeProfileMappingApi TEXTEQU <__imp_InitializeProfileMappingApi>
extern __imp_RemapAndMoveUserA:PANYARGS
RemapAndMoveUser  TEXTEQU <__imp_RemapAndMoveUserA>
extern __imp_RemapAndMoveUserW:PANYARGS
RemapAndMoveUserW TEXTEQU <__imp_RemapAndMoveUserW>
extern __imp_RemapUserProfileA:PANYARGS
RemapUserProfile  TEXTEQU <__imp_RemapUserProfileA>
extern __imp_RemapUserProfileW:PANYARGS
RemapUserProfileW TEXTEQU <__imp_RemapUserProfileW>
