extern __imp_EmptyWorkingSet:PANYARGS
EmptyWorkingSet TEXTEQU <__imp_EmptyWorkingSet>
extern __imp_EnumDeviceDrivers:PANYARGS
EnumDeviceDrivers TEXTEQU <__imp_EnumDeviceDrivers>
extern __imp_EnumPageFilesA:PANYARGS
EnumPageFiles  TEXTEQU <__imp_EnumPageFilesA>
extern __imp_EnumPageFilesW:PANYARGS
EnumPageFilesW TEXTEQU <__imp_EnumPageFilesW>
extern __imp_EnumProcessModules:PANYARGS
EnumProcessModules TEXTEQU <__imp_EnumProcessModules>
extern __imp_EnumProcesses:PANYARGS
EnumProcesses TEXTEQU <__imp_EnumProcesses>
extern __imp_GetDeviceDriverBaseNameA:PANYARGS
GetDeviceDriverBaseName  TEXTEQU <__imp_GetDeviceDriverBaseNameA>
extern __imp_GetDeviceDriverBaseNameW:PANYARGS
GetDeviceDriverBaseNameW TEXTEQU <__imp_GetDeviceDriverBaseNameW>
extern __imp_GetDeviceDriverFileNameA:PANYARGS
GetDeviceDriverFileName  TEXTEQU <__imp_GetDeviceDriverFileNameA>
extern __imp_GetDeviceDriverFileNameW:PANYARGS
GetDeviceDriverFileNameW TEXTEQU <__imp_GetDeviceDriverFileNameW>
extern __imp_GetMappedFileNameA:PANYARGS
GetMappedFileName  TEXTEQU <__imp_GetMappedFileNameA>
extern __imp_GetMappedFileNameW:PANYARGS
GetMappedFileNameW TEXTEQU <__imp_GetMappedFileNameW>
extern __imp_GetModuleBaseNameA:PANYARGS
GetModuleBaseName  TEXTEQU <__imp_GetModuleBaseNameA>
extern __imp_GetModuleBaseNameW:PANYARGS
GetModuleBaseNameW TEXTEQU <__imp_GetModuleBaseNameW>
extern __imp_GetModuleFileNameExA:PANYARGS
GetModuleFileNameEx  TEXTEQU <__imp_GetModuleFileNameExA>
extern __imp_GetModuleFileNameExW:PANYARGS
GetModuleFileNameExW TEXTEQU <__imp_GetModuleFileNameExW>
extern __imp_GetModuleInformation:PANYARGS
GetModuleInformation TEXTEQU <__imp_GetModuleInformation>
extern __imp_GetPerformanceInfo:PANYARGS
GetPerformanceInfo TEXTEQU <__imp_GetPerformanceInfo>
extern __imp_GetProcessImageFileNameA:PANYARGS
GetProcessImageFileName  TEXTEQU <__imp_GetProcessImageFileNameA>
extern __imp_GetProcessImageFileNameW:PANYARGS
GetProcessImageFileNameW TEXTEQU <__imp_GetProcessImageFileNameW>
extern __imp_GetProcessMemoryInfo:PANYARGS
GetProcessMemoryInfo TEXTEQU <__imp_GetProcessMemoryInfo>
extern __imp_GetWsChanges:PANYARGS
GetWsChanges TEXTEQU <__imp_GetWsChanges>
extern __imp_InitializeProcessForWsWatch:PANYARGS
InitializeProcessForWsWatch TEXTEQU <__imp_InitializeProcessForWsWatch>
extern __imp_QueryWorkingSet:PANYARGS
QueryWorkingSet TEXTEQU <__imp_QueryWorkingSet>
extern __imp_QueryWorkingSetEx:PANYARGS
QueryWorkingSetEx TEXTEQU <__imp_QueryWorkingSetEx>
