extern __imp_FPasswordChangeNotify:PANYARGS
FPasswordChangeNotify TEXTEQU <__imp_FPasswordChangeNotify>
extern __imp_SPCloseItem:PANYARGS
SPCloseItem TEXTEQU <__imp_SPCloseItem>
extern __imp_SPOpenItem:PANYARGS
SPOpenItem TEXTEQU <__imp_SPOpenItem>
extern __imp_SPAcquireContext:PANYARGS
SPAcquireContext TEXTEQU <__imp_SPAcquireContext>
extern __imp_SPCreateSubtype:PANYARGS
SPCreateSubtype TEXTEQU <__imp_SPCreateSubtype>
extern __imp_SPCreateType:PANYARGS
SPCreateType TEXTEQU <__imp_SPCreateType>
extern __imp_SPDeleteItem:PANYARGS
SPDeleteItem TEXTEQU <__imp_SPDeleteItem>
extern __imp_SPDeleteSubtype:PANYARGS
SPDeleteSubtype TEXTEQU <__imp_SPDeleteSubtype>
extern __imp_SPDeleteType:PANYARGS
SPDeleteType TEXTEQU <__imp_SPDeleteType>
extern __imp_SPEnumItems:PANYARGS
SPEnumItems TEXTEQU <__imp_SPEnumItems>
extern __imp_SPEnumSubtypes:PANYARGS
SPEnumSubtypes TEXTEQU <__imp_SPEnumSubtypes>
extern __imp_SPEnumTypes:PANYARGS
SPEnumTypes TEXTEQU <__imp_SPEnumTypes>
extern __imp_SPGetProvInfo:PANYARGS
SPGetProvInfo TEXTEQU <__imp_SPGetProvInfo>
extern __imp_SPGetProvParam:PANYARGS
SPGetProvParam TEXTEQU <__imp_SPGetProvParam>
extern __imp_SPGetSubtypeInfo:PANYARGS
SPGetSubtypeInfo TEXTEQU <__imp_SPGetSubtypeInfo>
extern __imp_SPGetTypeInfo:PANYARGS
SPGetTypeInfo TEXTEQU <__imp_SPGetTypeInfo>
extern __imp_SPProviderInitialize:PANYARGS
SPProviderInitialize TEXTEQU <__imp_SPProviderInitialize>
extern __imp_SPReadItem:PANYARGS
SPReadItem TEXTEQU <__imp_SPReadItem>
extern __imp_SPReleaseContext:PANYARGS
SPReleaseContext TEXTEQU <__imp_SPReleaseContext>
extern __imp_SPSetProvParam:PANYARGS
SPSetProvParam TEXTEQU <__imp_SPSetProvParam>
extern __imp_SPWriteItem:PANYARGS
SPWriteItem TEXTEQU <__imp_SPWriteItem>
