extern __imp_??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z:PANYARGS
??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z TEXTEQU <__imp_??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z>
extern __imp_??0CNestedImpersonation@@QEAA@PEAX@Z:PANYARGS
??0CNestedImpersonation@@QEAA@PEAX@Z TEXTEQU <__imp_??0CNestedImpersonation@@QEAA@PEAX@Z>
extern __imp_??0CNestedImpersonation@@QEAA@XZ:PANYARGS
??0CNestedImpersonation@@QEAA@XZ TEXTEQU <__imp_??0CNestedImpersonation@@QEAA@XZ>
extern __imp_??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z:PANYARGS
??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z TEXTEQU <__imp_??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z>
extern __imp_?BITSAlloc@@YAPEAX_K@Z:PANYARGS
?BITSAlloc@@YAPEAX_K@Z TEXTEQU <__imp_?BITSAlloc@@YAPEAX_K@Z>
extern __imp_?BITSFree@@YAXPEAX@Z:PANYARGS
?BITSFree@@YAXPEAX@Z TEXTEQU <__imp_?BITSFree@@YAXPEAX@Z>
extern __imp_?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ:PANYARGS
?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ TEXTEQU <__imp_?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ>
extern __imp_?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ:PANYARGS
?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ TEXTEQU <__imp_?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ>
extern __imp_?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z:PANYARGS
?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z TEXTEQU <__imp_?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z>
extern __imp_?FindInterfaceIndex@@YAKPEBG@Z:PANYARGS
?FindInterfaceIndex@@YAKPEBG@Z TEXTEQU <__imp_?FindInterfaceIndex@@YAKPEBG@Z>
extern __imp_?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z:PANYARGS
?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z TEXTEQU <__imp_?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z>
extern __imp_?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z:PANYARGS
?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z TEXTEQU <__imp_?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z>
extern __imp_ServiceMain:PANYARGS
ServiceMain TEXTEQU <__imp_ServiceMain>
extern __imp_?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A:PANYARGS
?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@  TEXTEQU <__imp_?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A>
extern __imp_BITSServiceMain:PANYARGS
BITSServiceMain TEXTEQU <__imp_BITSServiceMain>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
