extern __imp_AMGetErrorTextA:PANYARGS
AMGetErrorText  TEXTEQU <__imp_AMGetErrorTextA>
extern __imp_AMGetErrorTextW:PANYARGS
AMGetErrorTextW TEXTEQU <__imp_AMGetErrorTextW>
extern __imp_AmpFactorToDB:PANYARGS
AmpFactorToDB TEXTEQU <__imp_AmpFactorToDB>
extern __imp_DBToAmpFactor:PANYARGS
DBToAmpFactor TEXTEQU <__imp_DBToAmpFactor>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetProxyDllInfo:PANYARGS
GetProxyDllInfo TEXTEQU <__imp_GetProxyDllInfo>
