extern __imp_?CoTaskAllocator@@3VCCoTaskAllocator@@A:PANYARGS
?CoTaskAllocator@@3VCCoTaskAllocator@@  TEXTEQU <__imp_?CoTaskAllocator@@3VCCoTaskAllocator@@A>
extern __imp_??0CAllocStorageVariant@@QEAA@AEAUtagPROPVARIANT@@AEAVPMemoryAllocator@@@Z:PANYARGS
??0CAllocStorageVariant@@QEAA@AEAUtagPROPVARIANT@@AEAVPMemoryAllocator@@@Z TEXTEQU <__imp_??0CAllocStorageVariant@@QEAA@AEAUtagPROPVARIANT@@AEAVPMemoryAllocator@@@Z>
extern __imp_??0CAllocStorageVariant@@QEAA@AEAVPDeSerStream@@AEAVPMemoryAllocator@@@Z:PANYARGS
??0CAllocStorageVariant@@QEAA@AEAVPDeSerStream@@AEAVPMemoryAllocator@@@Z TEXTEQU <__imp_??0CAllocStorageVariant@@QEAA@AEAVPDeSerStream@@AEAVPMemoryAllocator@@@Z>
extern __imp_??0CAllocStorageVariant@@QEAA@PEBDAEAVPMemoryAllocator@@@Z:PANYARGS
??0CAllocStorageVariant@@QEAA@PEBDAEAVPMemoryAllocator@@@Z TEXTEQU <__imp_??0CAllocStorageVariant@@QEAA@PEBDAEAVPMemoryAllocator@@@Z>
extern __imp_??0CAllocStorageVariant@@QEAA@PEBGAEAVPMemoryAllocator@@@Z:PANYARGS
??0CAllocStorageVariant@@QEAA@PEBGAEAVPMemoryAllocator@@@Z TEXTEQU <__imp_??0CAllocStorageVariant@@QEAA@PEBGAEAVPMemoryAllocator@@@Z>
extern __imp_??0CAllocStorageVariant@@QEAA@PEBU_GUID@@AEAVPMemoryAllocator@@@Z:PANYARGS
??0CAllocStorageVariant@@QEAA@PEBU_GUID@@AEAVPMemoryAllocator@@@Z TEXTEQU <__imp_??0CAllocStorageVariant@@QEAA@PEBU_GUID@@AEAVPMemoryAllocator@@@Z>
extern __imp_??0CAllocStorageVariant@@QEAA@W4VARENUM@@KAEAVPMemoryAllocator@@@Z:PANYARGS
??0CAllocStorageVariant@@QEAA@W4VARENUM@@KAEAVPMemoryAllocator@@@Z TEXTEQU <__imp_??0CAllocStorageVariant@@QEAA@W4VARENUM@@KAEAVPMemoryAllocator@@@Z>
extern __imp_??0CCatState@@QEAA@XZ:PANYARGS
??0CCatState@@QEAA@XZ TEXTEQU <__imp_??0CCatState@@QEAA@XZ>
extern __imp_??0CCategorizationSet@@QEAA@AEBV0@@Z:PANYARGS
??0CCategorizationSet@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CCategorizationSet@@QEAA@AEBV0@@Z>
extern __imp_??0CCategorizationSet@@QEAA@I@Z:PANYARGS
??0CCategorizationSet@@QEAA@I@Z TEXTEQU <__imp_??0CCategorizationSet@@QEAA@I@Z>
extern __imp_??0CCiAdminParams@@QEAA@PEAVCLangList@@@Z:PANYARGS
??0CCiAdminParams@@QEAA@PEAVCLangList@@@Z TEXTEQU <__imp_??0CCiAdminParams@@QEAA@PEAVCLangList@@@Z>
extern __imp_??0CCiRegParams@@QEAA@PEBG@Z:PANYARGS
??0CCiRegParams@@QEAA@PEBG@Z TEXTEQU <__imp_??0CCiRegParams@@QEAA@PEBG@Z>
extern __imp_??0CColumnSet@@QEAA@I@Z:PANYARGS
??0CColumnSet@@QEAA@I@Z TEXTEQU <__imp_??0CColumnSet@@QEAA@I@Z>
extern __imp_??0CColumns@@QEAA@AEBV0@@Z:PANYARGS
??0CColumns@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CColumns@@QEAA@AEBV0@@Z>
extern __imp_??0CColumns@@QEAA@I@Z:PANYARGS
??0CColumns@@QEAA@I@Z TEXTEQU <__imp_??0CColumns@@QEAA@I@Z>
extern __imp_??0CContentRestriction@@QEAA@PEBGAEBVCFullPropSpec@@KK@Z:PANYARGS
??0CContentRestriction@@QEAA@PEBGAEBVCFullPropSpec@@KK@Z TEXTEQU <__imp_??0CContentRestriction@@QEAA@PEBGAEBVCFullPropSpec@@KK@Z>
extern __imp_??0CDFA@@QEAA@PEBGAEAVCTimeLimit@@E@Z:PANYARGS
??0CDFA@@QEAA@PEBGAEAVCTimeLimit@@E@Z TEXTEQU <__imp_??0CDFA@@QEAA@PEBGAEAVCTimeLimit@@E@Z>
extern __imp_??0CDbColId@@QEAA@AEBU_GUID@@PEBG@Z:PANYARGS
??0CDbColId@@QEAA@AEBU_GUID@@PEBG@Z TEXTEQU <__imp_??0CDbColId@@QEAA@AEBU_GUID@@PEBG@Z>
extern __imp_??0CDbColId@@QEAA@AEBUtagDBID@@@Z:PANYARGS
??0CDbColId@@QEAA@AEBUtagDBID@@@Z TEXTEQU <__imp_??0CDbColId@@QEAA@AEBUtagDBID@@@Z>
extern __imp_??0CDbColId@@QEAA@AEBV0@@Z:PANYARGS
??0CDbColId@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CDbColId@@QEAA@AEBV0@@Z>
extern __imp_??0CDbColId@@QEAA@XZ:PANYARGS
??0CDbColId@@QEAA@XZ TEXTEQU <__imp_??0CDbColId@@QEAA@XZ>
extern __imp_??0CDbColumns@@QEAA@I@Z:PANYARGS
??0CDbColumns@@QEAA@I@Z TEXTEQU <__imp_??0CDbColumns@@QEAA@I@Z>
extern __imp_??0CDbContentRestriction@@QEAA@PEBGAEBUtagDBID@@KK@Z:PANYARGS
??0CDbContentRestriction@@QEAA@PEBGAEBUtagDBID@@KK@Z TEXTEQU <__imp_??0CDbContentRestriction@@QEAA@PEBGAEBUtagDBID@@KK@Z>
extern __imp_??0CDbContentRestriction@@QEAA@PEBGAEBVCDbColumnNode@@KK@Z:PANYARGS
??0CDbContentRestriction@@QEAA@PEBGAEBVCDbColumnNode@@KK@Z TEXTEQU <__imp_??0CDbContentRestriction@@QEAA@PEBGAEBVCDbColumnNode@@KK@Z>
extern __imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBUtagDBID@@K@Z:PANYARGS
??0CDbNatLangRestriction@@QEAA@PEBGAEBUtagDBID@@K@Z TEXTEQU <__imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBUtagDBID@@K@Z>
extern __imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBVCDbColumnNode@@K@Z:PANYARGS
??0CDbNatLangRestriction@@QEAA@PEBGAEBVCDbColumnNode@@K@Z TEXTEQU <__imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBVCDbColumnNode@@K@Z>
extern __imp_??0CDbQueryResults@@QEAA@XZ:PANYARGS
??0CDbQueryResults@@QEAA@XZ TEXTEQU <__imp_??0CDbQueryResults@@QEAA@XZ>
extern __imp_??0CDbSelectNode@@QEAA@XZ:PANYARGS
??0CDbSelectNode@@QEAA@XZ TEXTEQU <__imp_??0CDbSelectNode@@QEAA@XZ>
extern __imp_??0CDbSortSet@@QEAA@I@Z:PANYARGS
??0CDbSortSet@@QEAA@I@Z TEXTEQU <__imp_??0CDbSortSet@@QEAA@I@Z>
extern __imp_??0CDefColumnRegEntry@@QEAA@XZ:PANYARGS
??0CDefColumnRegEntry@@QEAA@XZ TEXTEQU <__imp_??0CDefColumnRegEntry@@QEAA@XZ>
extern __imp_??0CDriveInfo@@QEAA@PEBGK@Z:PANYARGS
??0CDriveInfo@@QEAA@PEBGK@Z TEXTEQU <__imp_??0CDriveInfo@@QEAA@PEBGK@Z>
extern __imp_??0CDynStream@@QEAA@PEAVPMmStream@@@Z:PANYARGS
??0CDynStream@@QEAA@PEAVPMmStream@@@Z TEXTEQU <__imp_??0CDynStream@@QEAA@PEAVPMmStream@@@Z>
extern __imp_??0CEventItem@@QEAA@GGKGKPEBX@Z:PANYARGS
??0CEventItem@@QEAA@GGKGKPEBX@Z TEXTEQU <__imp_??0CEventItem@@QEAA@GGKGKPEBX@Z>
extern __imp_??0CEventLog@@QEAA@PEBG0@Z:PANYARGS
??0CEventLog@@QEAA@PEBG0@Z TEXTEQU <__imp_??0CEventLog@@QEAA@PEBG0@Z>
extern __imp_??0CException@@QEAA@J@Z:PANYARGS
??0CException@@QEAA@J@Z TEXTEQU <__imp_??0CException@@QEAA@J@Z>
extern __imp_??0CException@@QEAA@XZ:PANYARGS
??0CException@@QEAA@XZ TEXTEQU <__imp_??0CException@@QEAA@XZ>
extern __imp_??0CFileBuffer@@QEAA@AEAVCFileMapView@@I@Z:PANYARGS
??0CFileBuffer@@QEAA@AEAVCFileMapView@@I@Z TEXTEQU <__imp_??0CFileBuffer@@QEAA@AEAVCFileMapView@@I@Z>
extern __imp_??0CFileMapView@@QEAA@PEBG@Z:PANYARGS
??0CFileMapView@@QEAA@PEBG@Z TEXTEQU <__imp_??0CFileMapView@@QEAA@PEBG@Z>
extern __imp_??0CFilterDaemon@@QEAA@AEAVCiProxy@@AEAVCCiFrameworkParams@@AEAVCLangList@@PEAEKPEAUICiCFilterClient@@@Z:PANYARGS
??0CFilterDaemon@@QEAA@AEAVCiProxy@@AEAVCCiFrameworkParams@@AEAVCLangList@@PEAEKPEAUICiCFilterClient@@@Z TEXTEQU <__imp_??0CFilterDaemon@@QEAA@AEAVCiProxy@@AEAVCCiFrameworkParams@@AEAVCLangList@@PEAEKPEAUICiCFilterClient@@@Z>
extern __imp_??0CFullPath@@QEAA@PEBG@Z:PANYARGS
??0CFullPath@@QEAA@PEBG@Z TEXTEQU <__imp_??0CFullPath@@QEAA@PEBG@Z>
extern __imp_??0CFullPath@@QEAA@PEBGI@Z:PANYARGS
??0CFullPath@@QEAA@PEBGI@Z TEXTEQU <__imp_??0CFullPath@@QEAA@PEBGI@Z>
extern __imp_??0CFullPropSpec@@QEAA@AEAVPDeSerStream@@@Z:PANYARGS
??0CFullPropSpec@@QEAA@AEAVPDeSerStream@@@Z TEXTEQU <__imp_??0CFullPropSpec@@QEAA@AEAVPDeSerStream@@@Z>
extern __imp_??0CFullPropSpec@@QEAA@AEBV0@@Z:PANYARGS
??0CFullPropSpec@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CFullPropSpec@@QEAA@AEBV0@@Z>
extern __imp_??0CFullPropSpec@@QEAA@XZ:PANYARGS
??0CFullPropSpec@@QEAA@XZ TEXTEQU <__imp_??0CFullPropSpec@@QEAA@XZ>
extern __imp_??0CFwAsyncWorkItem@@QEAA@AEAVCWorkManager@@AEAVCWorkQueue@@@Z:PANYARGS
??0CFwAsyncWorkItem@@QEAA@AEAVCWorkManager@@AEAVCWorkQueue@@@Z TEXTEQU <__imp_??0CFwAsyncWorkItem@@QEAA@AEAVCWorkManager@@AEAVCWorkQueue@@@Z>
extern __imp_??0CFwEventItem@@QEAA@GKGKPEAX@Z:PANYARGS
??0CFwEventItem@@QEAA@GKGKPEAX@Z TEXTEQU <__imp_??0CFwEventItem@@QEAA@GKGKPEAX@Z>
extern __imp_??0CGenericCiProxy@@QEAA@AEAVCSharedNameGen@@KK@Z:PANYARGS
??0CGenericCiProxy@@QEAA@AEAVCSharedNameGen@@KK@Z TEXTEQU <__imp_??0CGenericCiProxy@@QEAA@AEAVCSharedNameGen@@KK@Z>
extern __imp_??0CGetDbProps@@QEAA@XZ:PANYARGS
??0CGetDbProps@@QEAA@XZ TEXTEQU <__imp_??0CGetDbProps@@QEAA@XZ>
extern __imp_??0CImpersonateRemoteAccess@@QEAA@PEAVCImpersonationTokenCache@@@Z:PANYARGS
??0CImpersonateRemoteAccess@@QEAA@PEAVCImpersonationTokenCache@@@Z TEXTEQU <__imp_??0CImpersonateRemoteAccess@@QEAA@PEAVCImpersonationTokenCache@@@Z>
extern __imp_??0CImpersonationTokenCache@@QEAA@PEBG@Z:PANYARGS
??0CImpersonationTokenCache@@QEAA@PEBG@Z TEXTEQU <__imp_??0CImpersonationTokenCache@@QEAA@PEBG@Z>
extern __imp_??0CIndexTable@@QEAA@AEAVCiStorage@@AEAVCTransaction@@@Z:PANYARGS
??0CIndexTable@@QEAA@AEAVCiStorage@@AEAVCTransaction@@@Z TEXTEQU <__imp_??0CIndexTable@@QEAA@AEAVCiStorage@@AEAVCTransaction@@@Z>
extern __imp_??0CInternalPropertyRestriction@@QEAA@KKAEBVCStorageVariant@@PEAVCRestriction@@@Z:PANYARGS
??0CInternalPropertyRestriction@@QEAA@KKAEBVCStorageVariant@@PEAVCRestriction@@@Z TEXTEQU <__imp_??0CInternalPropertyRestriction@@QEAA@KKAEBVCStorageVariant@@PEAVCRestriction@@@Z>
extern __imp_??0CKeyArray@@QEAA@HH@Z:PANYARGS
??0CKeyArray@@QEAA@HH@Z TEXTEQU <__imp_??0CKeyArray@@QEAA@HH@Z>
extern __imp_??0CLangList@@QEAA@PEAUICiCLangRes@@K@Z:PANYARGS
??0CLangList@@QEAA@PEAUICiCLangRes@@K@Z TEXTEQU <__imp_??0CLangList@@QEAA@PEAUICiCLangRes@@K@Z>
extern __imp_??0CLocalGlobalPropertyList@@QEAA@K@Z:PANYARGS
??0CLocalGlobalPropertyList@@QEAA@K@Z TEXTEQU <__imp_??0CLocalGlobalPropertyList@@QEAA@K@Z>
extern __imp_??0CLocalGlobalPropertyList@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z:PANYARGS
??0CLocalGlobalPropertyList@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z TEXTEQU <__imp_??0CLocalGlobalPropertyList@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z>
extern __imp_??0CMachineAdmin@@QEAA@PEBGH@Z:PANYARGS
??0CMachineAdmin@@QEAA@PEBGH@Z TEXTEQU <__imp_??0CMachineAdmin@@QEAA@PEBGH@Z>
extern __imp_??0CMemSerStream@@QEAA@I@Z:PANYARGS
??0CMemSerStream@@QEAA@I@Z TEXTEQU <__imp_??0CMemSerStream@@QEAA@I@Z>
extern __imp_??0CMemSerStream@@QEAA@PEAEK@Z:PANYARGS
??0CMemSerStream@@QEAA@PEAEK@Z TEXTEQU <__imp_??0CMemSerStream@@QEAA@PEAEK@Z>
extern __imp_??0CMetaDataMgr@@QEAA@HW4CiVRootTypeEnum@@KPEBG@Z:PANYARGS
??0CMetaDataMgr@@QEAA@HW4CiVRootTypeEnum@@KPEBG@Z TEXTEQU <__imp_??0CMetaDataMgr@@QEAA@HW4CiVRootTypeEnum@@KPEBG@Z>
extern __imp_??0CMmStream@@QEAA@KH@Z:PANYARGS
??0CMmStream@@QEAA@KH@Z TEXTEQU <__imp_??0CMmStream@@QEAA@KH@Z>
extern __imp_??0CMmStreamConsecBuf@@QEAA@XZ:PANYARGS
??0CMmStreamConsecBuf@@QEAA@XZ TEXTEQU <__imp_??0CMmStreamConsecBuf@@QEAA@XZ>
extern __imp_??0CNatLanguageRestriction@@QEAA@PEBGAEBVCFullPropSpec@@K@Z:PANYARGS
??0CNatLanguageRestriction@@QEAA@PEBGAEBVCFullPropSpec@@K@Z TEXTEQU <__imp_??0CNatLanguageRestriction@@QEAA@PEBGAEBVCFullPropSpec@@K@Z>
extern __imp_??0CNodeRestriction@@QEAA@KI@Z:PANYARGS
??0CNodeRestriction@@QEAA@KI@Z TEXTEQU <__imp_??0CNodeRestriction@@QEAA@KI@Z>
extern __imp_??0CNormalizer@@QEAA@AEAVPNoiseList@@@Z:PANYARGS
??0CNormalizer@@QEAA@AEAVPNoiseList@@@Z TEXTEQU <__imp_??0CNormalizer@@QEAA@AEAVPNoiseList@@@Z>
extern __imp_??0CPathParser@@QEAA@PEBGK@Z:PANYARGS
??0CPathParser@@QEAA@PEBGK@Z TEXTEQU <__imp_??0CPathParser@@QEAA@PEBGK@Z>
extern __imp_??0CPerfMon@@QEAA@PEBG@Z:PANYARGS
??0CPerfMon@@QEAA@PEBG@Z TEXTEQU <__imp_??0CPerfMon@@QEAA@PEBG@Z>
extern __imp_??0CPersDeComp@@QEAA@AEAVPDirectory@@KAEAVCPhysIndex@@KHH@Z:PANYARGS
??0CPersDeComp@@QEAA@AEAVPDirectory@@KAEAVCPhysIndex@@KHH@Z TEXTEQU <__imp_??0CPersDeComp@@QEAA@AEAVPDirectory@@KAEAVCPhysIndex@@KHH@Z>
extern __imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KIPEAVPMmStream@@HIH@Z:PANYARGS
??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KIPEAVPMmStream@@HIH@Z TEXTEQU <__imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KIPEAVPMmStream@@HIH@Z>
extern __imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KPEAVPMmStream@@W4EOpenMode@1@HIH@Z:PANYARGS
??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KPEAVPMmStream@@W4EOpenMode@1@HIH@Z TEXTEQU <__imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KPEAVPMmStream@@W4EOpenMode@1@HIH@Z>
extern __imp_??0CPidLookupTable@@QEAA@XZ:PANYARGS
??0CPidLookupTable@@QEAA@XZ TEXTEQU <__imp_??0CPidLookupTable@@QEAA@XZ>
extern __imp_??0CPidRemapper@@QEAA@AEAV?$XInterface@UIPropertyMapper@@@@@Z:PANYARGS
??0CPidRemapper@@QEAA@AEAV?$XInterface@UIPropertyMapper@@@@@Z TEXTEQU <__imp_??0CPidRemapper@@QEAA@AEAV?$XInterface@UIPropertyMapper@@@@@Z>
extern __imp_??0CPidRemapper@@QEAA@AEBVCPidMapper@@AEAV?$XInterface@UIPropertyMapper@@@@PEAVCRestriction@@PEAVCColumnSet@@PEAVCSortSet@@@Z:PANYARGS
??0CPidRemapper@@QEAA@AEBVCPidMapper@@AEAV?$XInterface@UIPropertyMapper@@@@PEAVCRestriction@@PEAVCColumnSet@@PEAVCSortSet@@@Z TEXTEQU <__imp_??0CPidRemapper@@QEAA@AEBVCPidMapper@@AEAV?$XInterface@UIPropertyMapper@@@@PEAVCRestriction@@PEAVCColumnSet@@PEAVCSortSet@@@Z>
extern __imp_??0CPropListFile@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z:PANYARGS
??0CPropListFile@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z TEXTEQU <__imp_??0CPropListFile@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z>
extern __imp_??0CPropNameArray@@QEAA@AEAVPDeSerStream@@@Z:PANYARGS
??0CPropNameArray@@QEAA@AEAVPDeSerStream@@@Z TEXTEQU <__imp_??0CPropNameArray@@QEAA@AEAVPDeSerStream@@@Z>
extern __imp_??0CPropNameArray@@QEAA@I@Z:PANYARGS
??0CPropNameArray@@QEAA@I@Z TEXTEQU <__imp_??0CPropNameArray@@QEAA@I@Z>
extern __imp_??0CPropStoreManager@@QEAA@K@Z:PANYARGS
??0CPropStoreManager@@QEAA@K@Z TEXTEQU <__imp_??0CPropStoreManager@@QEAA@K@Z>
extern __imp_??0CPropertyRestriction@@QEAA@KAEBVCFullPropSpec@@AEBVCStorageVariant@@@Z:PANYARGS
??0CPropertyRestriction@@QEAA@KAEBVCFullPropSpec@@AEBVCStorageVariant@@@Z TEXTEQU <__imp_??0CPropertyRestriction@@QEAA@KAEBVCFullPropSpec@@AEBVCStorageVariant@@@Z>
extern __imp_??0CPropertyRestriction@@QEAA@XZ:PANYARGS
??0CPropertyRestriction@@QEAA@XZ TEXTEQU <__imp_??0CPropertyRestriction@@QEAA@XZ>
extern __imp_??0CPropertyStoreWids@@QEAA@AEAVCPropStoreManager@@@Z:PANYARGS
??0CPropertyStoreWids@@QEAA@AEAVCPropStoreManager@@@Z TEXTEQU <__imp_??0CPropertyStoreWids@@QEAA@AEAVCPropStoreManager@@@Z>
extern __imp_??0CPropertyValueParser@@QEAA@AEAVCQueryScanner@@GK@Z:PANYARGS
??0CPropertyValueParser@@QEAA@AEAVCQueryScanner@@GK@Z TEXTEQU <__imp_??0CPropertyValueParser@@QEAA@AEAVCQueryScanner@@GK@Z>
extern __imp_??0CQueryScanner@@QEAA@PEBGHKH@Z:PANYARGS
??0CQueryScanner@@QEAA@PEBGHKH@Z TEXTEQU <__imp_??0CQueryScanner@@QEAA@PEBGHKH@Z>
extern __imp_??0CRangeKeyRepository@@QEAA@XZ:PANYARGS
??0CRangeKeyRepository@@QEAA@XZ TEXTEQU <__imp_??0CRangeKeyRepository@@QEAA@XZ>
extern __imp_??0CRcovStrmAppendTrans@@QEAA@AEAVPRcovStorageObj@@@Z:PANYARGS
??0CRcovStrmAppendTrans@@QEAA@AEAVPRcovStorageObj@@@Z TEXTEQU <__imp_??0CRcovStrmAppendTrans@@QEAA@AEAVPRcovStorageObj@@@Z>
extern __imp_??0CRcovStrmMDTrans@@QEAA@AEAVPRcovStorageObj@@W4MDOp@0@K@Z:PANYARGS
??0CRcovStrmMDTrans@@QEAA@AEAVPRcovStorageObj@@W4MDOp@0@K@Z TEXTEQU <__imp_??0CRcovStrmMDTrans@@QEAA@AEAVPRcovStorageObj@@W4MDOp@0@K@Z>
extern __imp_??0CRcovStrmTrans@@IEAA@AEAVPRcovStorageObj@@W4RcovOpType@@@Z:PANYARGS
??0CRcovStrmTrans@@IEAA@AEAVPRcovStorageObj@@W4RcovOpType@@@Z TEXTEQU <__imp_??0CRcovStrmTrans@@IEAA@AEAVPRcovStorageObj@@W4RcovOpType@@@Z>
extern __imp_??0CRegAccess@@QEAA@KPEBG@Z:PANYARGS
??0CRegAccess@@QEAA@KPEBG@Z TEXTEQU <__imp_??0CRegAccess@@QEAA@KPEBG@Z>
extern __imp_??0CRegChangeEvent@@QEAA@PEBGH@Z:PANYARGS
??0CRegChangeEvent@@QEAA@PEBGH@Z TEXTEQU <__imp_??0CRegChangeEvent@@QEAA@PEBGH@Z>
extern __imp_??0CRegNotify@@QEAA@PEBG@Z:PANYARGS
??0CRegNotify@@QEAA@PEBG@Z TEXTEQU <__imp_??0CRegNotify@@QEAA@PEBG@Z>
extern __imp_??0CRequestClient@@QEAA@PEBGPEAUIDBProperties@@@Z:PANYARGS
??0CRequestClient@@QEAA@PEBGPEAUIDBProperties@@@Z TEXTEQU <__imp_??0CRequestClient@@QEAA@PEBGPEAUIDBProperties@@@Z>
extern __imp_??0CRequestQueue@@QEAA@IIIHIIAEBU_GUID@@@Z:PANYARGS
??0CRequestQueue@@QEAA@IIIHIIAEBU_GUID@@@Z TEXTEQU <__imp_??0CRequestQueue@@QEAA@IIIHIIAEBU_GUID@@@Z>
extern __imp_??0CScopeRestriction@@QEAA@PEBGHH@Z:PANYARGS
??0CScopeRestriction@@QEAA@PEBGHH@Z TEXTEQU <__imp_??0CScopeRestriction@@QEAA@PEBGHH@Z>
extern __imp_??0CSdidLookupTable@@QEAA@XZ:PANYARGS
??0CSdidLookupTable@@QEAA@XZ TEXTEQU <__imp_??0CSdidLookupTable@@QEAA@XZ>
extern __imp_??0CSizeSerStream@@QEAA@XZ:PANYARGS
??0CSizeSerStream@@QEAA@XZ TEXTEQU <__imp_??0CSizeSerStream@@QEAA@XZ>
extern __imp_??0CSort@@QEAA@I@Z:PANYARGS
??0CSort@@QEAA@I@Z TEXTEQU <__imp_??0CSort@@QEAA@I@Z>
extern __imp_??0CSortSet@@QEAA@I@Z:PANYARGS
??0CSortSet@@QEAA@I@Z TEXTEQU <__imp_??0CSortSet@@QEAA@I@Z>
extern __imp_??0CStandardPropMapper@@QEAA@XZ:PANYARGS
??0CStandardPropMapper@@QEAA@XZ TEXTEQU <__imp_??0CStandardPropMapper@@QEAA@XZ>
extern __imp_??0CSvcQuery@@QEAA@PEBGPEAUIDBProperties@@@Z:PANYARGS
??0CSvcQuery@@QEAA@PEBGPEAUIDBProperties@@@Z TEXTEQU <__imp_??0CSvcQuery@@QEAA@PEBGPEAUIDBProperties@@@Z>
extern __imp_??0CSynRestriction@@QEAA@AEBVCKey@@KKKH@Z:PANYARGS
??0CSynRestriction@@QEAA@AEBVCKey@@KKKH@Z TEXTEQU <__imp_??0CSynRestriction@@QEAA@AEBVCKey@@KKKH@Z>
extern __imp_??0CTimeLimit@@QEAA@KK@Z:PANYARGS
??0CTimeLimit@@QEAA@KK@Z TEXTEQU <__imp_??0CTimeLimit@@QEAA@KK@Z>
extern __imp_??0CTransaction@@QEAA@XZ:PANYARGS
??0CTransaction@@QEAA@XZ TEXTEQU <__imp_??0CTransaction@@QEAA@XZ>
extern __imp_??0CUnfilteredRestriction@@QEAA@XZ:PANYARGS
??0CUnfilteredRestriction@@QEAA@XZ TEXTEQU <__imp_??0CUnfilteredRestriction@@QEAA@XZ>
extern __imp_??0CValueNormalizer@@QEAA@AEAVPKeyRepository@@@Z:PANYARGS
??0CValueNormalizer@@QEAA@AEAVPKeyRepository@@@Z TEXTEQU <__imp_??0CValueNormalizer@@QEAA@AEAVPKeyRepository@@@Z>
extern __imp_??0CVirtualString@@QEAA@I@Z:PANYARGS
??0CVirtualString@@QEAA@I@Z TEXTEQU <__imp_??0CVirtualString@@QEAA@I@Z>
extern __imp_??0CWin32RegAccess@@QEAA@PEAUHKEY__@@PEBG@Z:PANYARGS
??0CWin32RegAccess@@QEAA@PEAUHKEY__@@PEBG@Z TEXTEQU <__imp_??0CWin32RegAccess@@QEAA@PEAUHKEY__@@PEBG@Z>
extern __imp_??0CWordRestriction@@QEAA@AEBVCKeyBuf@@KKKH@Z:PANYARGS
??0CWordRestriction@@QEAA@AEBVCKeyBuf@@KKKH@Z TEXTEQU <__imp_??0CWordRestriction@@QEAA@AEBVCKeyBuf@@KKKH@Z>
extern __imp_??0CWorkQueue@@QEAA@IW4WorkQueueType@0@@Z:PANYARGS
??0CWorkQueue@@QEAA@IW4WorkQueueType@0@@Z TEXTEQU <__imp_??0CWorkQueue@@QEAA@IW4WorkQueueType@0@@Z>
extern __imp_??0CiStorage@@QEAA@PEBGAEAUICiCAdviseStatus@@KKH@Z:PANYARGS
??0CiStorage@@QEAA@PEBGAEAUICiCAdviseStatus@@KKH@Z TEXTEQU <__imp_??0CiStorage@@QEAA@PEBGAEAUICiCAdviseStatus@@KKH@Z>
extern __imp_??0SStorageObject@@QEAA@PEAVPStorageObject@@@Z:PANYARGS
??0SStorageObject@@QEAA@PEAVPStorageObject@@@Z TEXTEQU <__imp_??0SStorageObject@@QEAA@PEAVPStorageObject@@@Z>
extern __imp_??1CAllocStorageVariant@@IEAA@XZ:PANYARGS
??1CAllocStorageVariant@@IEAA@XZ TEXTEQU <__imp_??1CAllocStorageVariant@@IEAA@XZ>
extern __imp_??1CCatState@@QEAA@XZ:PANYARGS
??1CCatState@@QEAA@XZ TEXTEQU <__imp_??1CCatState@@QEAA@XZ>
extern __imp_??1CCatalogAdmin@@QEAA@XZ:PANYARGS
??1CCatalogAdmin@@QEAA@XZ TEXTEQU <__imp_??1CCatalogAdmin@@QEAA@XZ>
extern __imp_??1CCatalogEnum@@QEAA@XZ:PANYARGS
??1CCatalogEnum@@QEAA@XZ TEXTEQU <__imp_??1CCatalogEnum@@QEAA@XZ>
extern __imp_??1CColumns@@QEAA@XZ:PANYARGS
??1CColumns@@QEAA@XZ TEXTEQU <__imp_??1CColumns@@QEAA@XZ>
extern __imp_??1CContentRestriction@@QEAA@XZ:PANYARGS
??1CContentRestriction@@QEAA@XZ TEXTEQU <__imp_??1CContentRestriction@@QEAA@XZ>
extern __imp_??1CDFA@@QEAA@XZ:PANYARGS
??1CDFA@@QEAA@XZ TEXTEQU <__imp_??1CDFA@@QEAA@XZ>
extern __imp_??1CDbCmdTreeNode@@QEAA@XZ:PANYARGS
??1CDbCmdTreeNode@@QEAA@XZ TEXTEQU <__imp_??1CDbCmdTreeNode@@QEAA@XZ>
extern __imp_??1CDbColumns@@QEAA@XZ:PANYARGS
??1CDbColumns@@QEAA@XZ TEXTEQU <__imp_??1CDbColumns@@QEAA@XZ>
extern __imp_??1CDbPropSet@@QEAA@XZ:PANYARGS
??1CDbPropSet@@QEAA@XZ TEXTEQU <__imp_??1CDbPropSet@@QEAA@XZ>
extern __imp_??1CDbQueryResults@@QEAA@XZ:PANYARGS
??1CDbQueryResults@@QEAA@XZ TEXTEQU <__imp_??1CDbQueryResults@@QEAA@XZ>
extern __imp_??1CDbSortSet@@QEAA@XZ:PANYARGS
??1CDbSortSet@@QEAA@XZ TEXTEQU <__imp_??1CDbSortSet@@QEAA@XZ>
extern __imp_??1CDynStream@@QEAA@XZ:PANYARGS
??1CDynStream@@QEAA@XZ TEXTEQU <__imp_??1CDynStream@@QEAA@XZ>
extern __imp_??1CEventItem@@QEAA@XZ:PANYARGS
??1CEventItem@@QEAA@XZ TEXTEQU <__imp_??1CEventItem@@QEAA@XZ>
extern __imp_??1CEventLog@@QEAA@XZ:PANYARGS
??1CEventLog@@QEAA@XZ TEXTEQU <__imp_??1CEventLog@@QEAA@XZ>
extern __imp_??1CFileMapView@@QEAA@XZ:PANYARGS
??1CFileMapView@@QEAA@XZ TEXTEQU <__imp_??1CFileMapView@@QEAA@XZ>
extern __imp_??1CFilterDaemon@@QEAA@XZ:PANYARGS
??1CFilterDaemon@@QEAA@XZ TEXTEQU <__imp_??1CFilterDaemon@@QEAA@XZ>
extern __imp_??1CFwAsyncWorkItem@@UEAA@XZ:PANYARGS
??1CFwAsyncWorkItem@@UEAA@XZ TEXTEQU <__imp_??1CFwAsyncWorkItem@@UEAA@XZ>
extern __imp_??1CFwEventItem@@QEAA@XZ:PANYARGS
??1CFwEventItem@@QEAA@XZ TEXTEQU <__imp_??1CFwEventItem@@QEAA@XZ>
extern __imp_??1CGenericCiProxy@@UEAA@XZ:PANYARGS
??1CGenericCiProxy@@UEAA@XZ TEXTEQU <__imp_??1CGenericCiProxy@@UEAA@XZ>
extern __imp_??1CImpersonateClient@@QEAA@XZ:PANYARGS
??1CImpersonateClient@@QEAA@XZ TEXTEQU <__imp_??1CImpersonateClient@@QEAA@XZ>
extern __imp_??1CImpersonateSystem@@QEAA@XZ:PANYARGS
??1CImpersonateSystem@@QEAA@XZ TEXTEQU <__imp_??1CImpersonateSystem@@QEAA@XZ>
extern __imp_??1CImpersonationTokenCache@@QEAA@XZ:PANYARGS
??1CImpersonationTokenCache@@QEAA@XZ TEXTEQU <__imp_??1CImpersonationTokenCache@@QEAA@XZ>
extern __imp_??1CInternalPropertyRestriction@@QEAA@XZ:PANYARGS
??1CInternalPropertyRestriction@@QEAA@XZ TEXTEQU <__imp_??1CInternalPropertyRestriction@@QEAA@XZ>
extern __imp_??1CKeyArray@@QEAA@XZ:PANYARGS
??1CKeyArray@@QEAA@XZ TEXTEQU <__imp_??1CKeyArray@@QEAA@XZ>
extern __imp_??1CLangList@@QEAA@XZ:PANYARGS
??1CLangList@@QEAA@XZ TEXTEQU <__imp_??1CLangList@@QEAA@XZ>
extern __imp_??1CMachineAdmin@@QEAA@XZ:PANYARGS
??1CMachineAdmin@@QEAA@XZ TEXTEQU <__imp_??1CMachineAdmin@@QEAA@XZ>
extern __imp_??1CMemSerStream@@UEAA@XZ:PANYARGS
??1CMemSerStream@@UEAA@XZ TEXTEQU <__imp_??1CMemSerStream@@UEAA@XZ>
extern __imp_??1CMetaDataMgr@@QEAA@XZ:PANYARGS
??1CMetaDataMgr@@QEAA@XZ TEXTEQU <__imp_??1CMetaDataMgr@@QEAA@XZ>
extern __imp_??1CMmStream@@UEAA@XZ:PANYARGS
??1CMmStream@@UEAA@XZ TEXTEQU <__imp_??1CMmStream@@UEAA@XZ>
extern __imp_??1CMmStreamConsecBuf@@QEAA@XZ:PANYARGS
??1CMmStreamConsecBuf@@QEAA@XZ TEXTEQU <__imp_??1CMmStreamConsecBuf@@QEAA@XZ>
extern __imp_??1CNatLanguageRestriction@@QEAA@XZ:PANYARGS
??1CNatLanguageRestriction@@QEAA@XZ TEXTEQU <__imp_??1CNatLanguageRestriction@@QEAA@XZ>
extern __imp_??1CNodeRestriction@@QEAA@XZ:PANYARGS
??1CNodeRestriction@@QEAA@XZ TEXTEQU <__imp_??1CNodeRestriction@@QEAA@XZ>
extern __imp_??1CNotRestriction@@QEAA@XZ:PANYARGS
??1CNotRestriction@@QEAA@XZ TEXTEQU <__imp_??1CNotRestriction@@QEAA@XZ>
extern __imp_??1COccRestriction@@QEAA@XZ:PANYARGS
??1COccRestriction@@QEAA@XZ TEXTEQU <__imp_??1COccRestriction@@QEAA@XZ>
extern __imp_??1CParseCommandTree@@QEAA@XZ:PANYARGS
??1CParseCommandTree@@QEAA@XZ TEXTEQU <__imp_??1CParseCommandTree@@QEAA@XZ>
extern __imp_??1CPerfMon@@QEAA@XZ:PANYARGS
??1CPerfMon@@QEAA@XZ TEXTEQU <__imp_??1CPerfMon@@QEAA@XZ>
extern __imp_??1CPhraseRestriction@@QEAA@XZ:PANYARGS
??1CPhraseRestriction@@QEAA@XZ TEXTEQU <__imp_??1CPhraseRestriction@@QEAA@XZ>
extern __imp_??1CPhysStorage@@UEAA@XZ:PANYARGS
??1CPhysStorage@@UEAA@XZ TEXTEQU <__imp_??1CPhysStorage@@UEAA@XZ>
extern __imp_??1CPidLookupTable@@QEAA@XZ:PANYARGS
??1CPidLookupTable@@QEAA@XZ TEXTEQU <__imp_??1CPidLookupTable@@QEAA@XZ>
extern __imp_??1CPidRemapper@@QEAA@XZ:PANYARGS
??1CPidRemapper@@QEAA@XZ TEXTEQU <__imp_??1CPidRemapper@@QEAA@XZ>
extern __imp_??1CProcess@@QEAA@XZ:PANYARGS
??1CProcess@@QEAA@XZ TEXTEQU <__imp_??1CProcess@@QEAA@XZ>
extern __imp_??1CPropStoreManager@@QEAA@XZ:PANYARGS
??1CPropStoreManager@@QEAA@XZ TEXTEQU <__imp_??1CPropStoreManager@@QEAA@XZ>
extern __imp_??1CPropertyList@@UEAA@XZ:PANYARGS
??1CPropertyList@@UEAA@XZ TEXTEQU <__imp_??1CPropertyList@@UEAA@XZ>
extern __imp_??1CPropertyRestriction@@QEAA@XZ:PANYARGS
??1CPropertyRestriction@@QEAA@XZ TEXTEQU <__imp_??1CPropertyRestriction@@QEAA@XZ>
extern __imp_??1CPropertyStore@@QEAA@XZ:PANYARGS
??1CPropertyStore@@QEAA@XZ TEXTEQU <__imp_??1CPropertyStore@@QEAA@XZ>
extern __imp_??1CPropertyStoreWids@@QEAA@XZ:PANYARGS
??1CPropertyStoreWids@@QEAA@XZ TEXTEQU <__imp_??1CPropertyStoreWids@@QEAA@XZ>
extern __imp_??1CQueryUnknown@@QEAA@XZ:PANYARGS
??1CQueryUnknown@@QEAA@XZ TEXTEQU <__imp_??1CQueryUnknown@@QEAA@XZ>
extern __imp_??1CRangeKeyRepository@@UEAA@XZ:PANYARGS
??1CRangeKeyRepository@@UEAA@XZ TEXTEQU <__imp_??1CRangeKeyRepository@@UEAA@XZ>
extern __imp_??1CRegChangeEvent@@QEAA@XZ:PANYARGS
??1CRegChangeEvent@@QEAA@XZ TEXTEQU <__imp_??1CRegChangeEvent@@QEAA@XZ>
extern __imp_??1CRegNotify@@MEAA@XZ:PANYARGS
??1CRegNotify@@MEAA@XZ TEXTEQU <__imp_??1CRegNotify@@MEAA@XZ>
extern __imp_??1CRestriction@@QEAA@XZ:PANYARGS
??1CRestriction@@QEAA@XZ TEXTEQU <__imp_??1CRestriction@@QEAA@XZ>
extern __imp_??1CScopeAdmin@@QEAA@XZ:PANYARGS
??1CScopeAdmin@@QEAA@XZ TEXTEQU <__imp_??1CScopeAdmin@@QEAA@XZ>
extern __imp_??1CScopeEnum@@QEAA@XZ:PANYARGS
??1CScopeEnum@@QEAA@XZ TEXTEQU <__imp_??1CScopeEnum@@QEAA@XZ>
extern __imp_??1CScopeRestriction@@QEAA@XZ:PANYARGS
??1CScopeRestriction@@QEAA@XZ TEXTEQU <__imp_??1CScopeRestriction@@QEAA@XZ>
extern __imp_??1CSdidLookupTable@@QEAA@XZ:PANYARGS
??1CSdidLookupTable@@QEAA@XZ TEXTEQU <__imp_??1CSdidLookupTable@@QEAA@XZ>
extern __imp_??1CSizeSerStream@@UEAA@XZ:PANYARGS
??1CSizeSerStream@@UEAA@XZ TEXTEQU <__imp_??1CSizeSerStream@@UEAA@XZ>
extern __imp_??1CSort@@QEAA@XZ:PANYARGS
??1CSort@@QEAA@XZ TEXTEQU <__imp_??1CSort@@QEAA@XZ>
extern __imp_??1CSynRestriction@@QEAA@XZ:PANYARGS
??1CSynRestriction@@QEAA@XZ TEXTEQU <__imp_??1CSynRestriction@@QEAA@XZ>
extern __imp_??1CVirtualString@@QEAA@XZ:PANYARGS
??1CVirtualString@@QEAA@XZ TEXTEQU <__imp_??1CVirtualString@@QEAA@XZ>
extern __imp_??1CWin32RegAccess@@QEAA@XZ:PANYARGS
??1CWin32RegAccess@@QEAA@XZ TEXTEQU <__imp_??1CWin32RegAccess@@QEAA@XZ>
extern __imp_??1CWordRestriction@@QEAA@XZ:PANYARGS
??1CWordRestriction@@QEAA@XZ TEXTEQU <__imp_??1CWordRestriction@@QEAA@XZ>
extern __imp_??1CWorkManager@@QEAA@XZ:PANYARGS
??1CWorkManager@@QEAA@XZ TEXTEQU <__imp_??1CWorkManager@@QEAA@XZ>
extern __imp_??1CWorkQueue@@QEAA@XZ:PANYARGS
??1CWorkQueue@@QEAA@XZ TEXTEQU <__imp_??1CWorkQueue@@QEAA@XZ>
extern __imp_??1SStorageObject@@QEAA@XZ:PANYARGS
??1SStorageObject@@QEAA@XZ TEXTEQU <__imp_??1SStorageObject@@QEAA@XZ>
extern __imp_??4CDbColId@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CDbColId@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CDbColId@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??8CDbColId@@QEBAHAEBV0@@Z:PANYARGS
??8CDbColId@@QEBAHAEBV0@@Z TEXTEQU <__imp_??8CDbColId@@QEBAHAEBV0@@Z>
extern __imp_?AbortWorkItems@CWorkManager@@QEAAXXZ:PANYARGS
?AbortWorkItems@CWorkManager@@QEAAXXZ TEXTEQU <__imp_?AbortWorkItems@CWorkManager@@QEAAXXZ>
extern __imp_?Accept@CQueryScanner@@QEAAXXZ:PANYARGS
?Accept@CQueryScanner@@QEAAXXZ TEXTEQU <__imp_?Accept@CQueryScanner@@QEAAXXZ>
extern __imp_?AcceptCommand@CQueryScanner@@QEAAXXZ:PANYARGS
?AcceptCommand@CQueryScanner@@QEAAXXZ TEXTEQU <__imp_?AcceptCommand@CQueryScanner@@QEAAXXZ>
extern __imp_?AcceptWord@CQueryScanner@@QEAAXXZ:PANYARGS
?AcceptWord@CQueryScanner@@QEAAXXZ TEXTEQU <__imp_?AcceptWord@CQueryScanner@@QEAAXXZ>
extern __imp_?AccessCheck@CSdidLookupTable@@QEAAHKPEAXKAEAH@Z:PANYARGS
?AccessCheck@CSdidLookupTable@@QEAAHKPEAXKAEAH@Z TEXTEQU <__imp_?AccessCheck@CSdidLookupTable@@QEAAHKPEAXKAEAH@Z>
extern __imp_?AcqLine@CQueryScanner@@QEAAPEAGH@Z:PANYARGS
?AcqLine@CQueryScanner@@QEAAPEAGH@Z TEXTEQU <__imp_?AcqLine@CQueryScanner@@QEAAPEAGH@Z>
extern __imp_?AcqPath@CQueryScanner@@QEAAPEAGXZ:PANYARGS
?AcqPath@CQueryScanner@@QEAAPEAGXZ TEXTEQU <__imp_?AcqPath@CQueryScanner@@QEAAPEAGXZ>
extern __imp_?AcqPhrase@CQueryScanner@@QEAAPEAGXZ:PANYARGS
?AcqPhrase@CQueryScanner@@QEAAPEAGXZ TEXTEQU <__imp_?AcqPhrase@CQueryScanner@@QEAAPEAGXZ>
extern __imp_?AcqRst@CRangeKeyRepository@@QEAAPEAVCRangeRestriction@@XZ:PANYARGS
?AcqRst@CRangeKeyRepository@@QEAAPEAVCRangeRestriction@@XZ TEXTEQU <__imp_?AcqRst@CRangeKeyRepository@@QEAAPEAVCRangeRestriction@@XZ>
extern __imp_?AcqWord@CQueryScanner@@QEAAPEAGXZ:PANYARGS
?AcqWord@CQueryScanner@@QEAAPEAGXZ TEXTEQU <__imp_?AcqWord@CQueryScanner@@QEAAPEAGXZ>
extern __imp_?AcquireRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z:PANYARGS
?AcquireRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z TEXTEQU <__imp_?AcquireRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z>
extern __imp_?Add@CDbColumns@@QEAAHAEBVCDbColId@@I@Z:PANYARGS
?Add@CDbColumns@@QEAAHAEBVCDbColId@@I@Z TEXTEQU <__imp_?Add@CDbColumns@@QEAAHAEBVCDbColId@@I@Z>
extern __imp_?Add@CDbQueryResults@@QEAAXPEAGK@Z:PANYARGS
?Add@CDbQueryResults@@QEAAXPEAGK@Z TEXTEQU <__imp_?Add@CDbQueryResults@@QEAAXPEAGK@Z>
extern __imp_?Add@CDbSortSet@@QEAAHAEBVCDbColId@@KI@Z:PANYARGS
?Add@CDbSortSet@@QEAAHAEBVCDbColId@@KI@Z TEXTEQU <__imp_?Add@CDbSortSet@@QEAAHAEBVCDbColId@@KI@Z>
extern __imp_?Add@CDbSortSet@@QEAAHAEBVCDbSortKey@@I@Z:PANYARGS
?Add@CDbSortSet@@QEAAHAEBVCDbSortKey@@I@Z TEXTEQU <__imp_?Add@CDbSortSet@@QEAAHAEBVCDbSortKey@@I@Z>
extern __imp_?Add@CKeyArray@@QEAAHHAEBVCKey@@@Z:PANYARGS
?Add@CKeyArray@@QEAAHHAEBVCKey@@@Z TEXTEQU <__imp_?Add@CKeyArray@@QEAAHHAEBVCKey@@@Z>
extern __imp_?Add@CKeyArray@@QEAAHHAEBVCKeyBuf@@@Z:PANYARGS
?Add@CKeyArray@@QEAAHHAEBVCKeyBuf@@@Z TEXTEQU <__imp_?Add@CKeyArray@@QEAAHHAEBVCKeyBuf@@@Z>
extern __imp_?Add@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z:PANYARGS
?Add@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z TEXTEQU <__imp_?Add@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z>
extern __imp_?AddArg@CEventItem@@QEAAXK@Z:PANYARGS
?AddArg@CEventItem@@QEAAXK@Z TEXTEQU <__imp_?AddArg@CEventItem@@QEAAXK@Z>
extern __imp_?AddArg@CEventItem@@QEAAXPEBG@Z:PANYARGS
?AddArg@CEventItem@@QEAAXPEBG@Z TEXTEQU <__imp_?AddArg@CEventItem@@QEAAXPEBG@Z>
extern __imp_?AddArg@CFwEventItem@@QEAAXK@Z:PANYARGS
?AddArg@CFwEventItem@@QEAAXK@Z TEXTEQU <__imp_?AddArg@CFwEventItem@@QEAAXK@Z>
extern __imp_?AddArg@CFwEventItem@@QEAAXPEBG@Z:PANYARGS
?AddArg@CFwEventItem@@QEAAXPEBG@Z TEXTEQU <__imp_?AddArg@CFwEventItem@@QEAAXPEBG@Z>
extern __imp_?AddCachedProperty@CCatalogAdmin@@QEAAXAEBVCFullPropSpec@@KKKH@Z:PANYARGS
?AddCachedProperty@CCatalogAdmin@@QEAAXAEBVCFullPropSpec@@KKKH@Z TEXTEQU <__imp_?AddCachedProperty@CCatalogAdmin@@QEAAXAEBVCFullPropSpec@@KKKH@Z>
extern __imp_?AddCatalog@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z:PANYARGS
?AddCatalog@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z TEXTEQU <__imp_?AddCatalog@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z>
extern __imp_?AddCatalog@CMachineAdmin@@QEAAXPEBG0@Z:PANYARGS
?AddCatalog@CMachineAdmin@@QEAAXPEBG0@Z TEXTEQU <__imp_?AddCatalog@CMachineAdmin@@QEAAXPEBG0@Z>
extern __imp_?AddChild@CNodeRestriction@@QEAAXPEAVCRestriction@@AEAI@Z:PANYARGS
?AddChild@CNodeRestriction@@QEAAXPEAVCRestriction@@AEAI@Z TEXTEQU <__imp_?AddChild@CNodeRestriction@@QEAAXPEAVCRestriction@@AEAI@Z>
extern __imp_?AddDir@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z:PANYARGS
?AddDir@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z TEXTEQU <__imp_?AddDir@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z>
extern __imp_?AddEntry@CPropertyList@@UEAAXPEAVCPropEntry@@H@Z:PANYARGS
?AddEntry@CPropertyList@@UEAAXPEAVCPropEntry@@H@Z TEXTEQU <__imp_?AddEntry@CPropertyList@@UEAAXPEAVCPropEntry@@H@Z>
extern __imp_?AddError@CEventItem@@QEAAXK@Z:PANYARGS
?AddError@CEventItem@@QEAAXK@Z TEXTEQU <__imp_?AddError@CEventItem@@QEAAXK@Z>
extern __imp_?AddKey@CSynRestriction@@QEAAXAEBVCKeyBuf@@@Z:PANYARGS
?AddKey@CSynRestriction@@QEAAXAEBVCKeyBuf@@@Z TEXTEQU <__imp_?AddKey@CSynRestriction@@QEAAXAEBVCKeyBuf@@@Z>
extern __imp_?AddMachine@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z:PANYARGS
?AddMachine@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z TEXTEQU <__imp_?AddMachine@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z>
extern __imp_?AddRef@CDbProperties@@UEAAKXZ:PANYARGS
?AddRef@CDbProperties@@UEAAKXZ TEXTEQU <__imp_?AddRef@CDbProperties@@UEAAKXZ>
extern __imp_?AddRef@CEmptyPropertyList@@UEAAKXZ:PANYARGS
?AddRef@CEmptyPropertyList@@UEAAKXZ TEXTEQU <__imp_?AddRef@CEmptyPropertyList@@UEAAKXZ>
extern __imp_?AddRef@CEnumString@@UEAAKXZ:PANYARGS
?AddRef@CEnumString@@UEAAKXZ TEXTEQU <__imp_?AddRef@CEnumString@@UEAAKXZ>
extern __imp_?AddRef@CEnumWorkid@@UEAAKXZ:PANYARGS
?AddRef@CEnumWorkid@@UEAAKXZ TEXTEQU <__imp_?AddRef@CEnumWorkid@@UEAAKXZ>
extern __imp_?AddRef@CFwPropertyMapper@@UEAAKXZ:PANYARGS
?AddRef@CFwPropertyMapper@@UEAAKXZ TEXTEQU <__imp_?AddRef@CFwPropertyMapper@@UEAAKXZ>
extern __imp_?AddRef@CQueryUnknown@@UEAAKXZ:PANYARGS
?AddRef@CQueryUnknown@@UEAAKXZ TEXTEQU <__imp_?AddRef@CQueryUnknown@@UEAAKXZ>
extern __imp_?AddRefWorkThreads@CWorkQueue@@QEAAXXZ:PANYARGS
?AddRefWorkThreads@CWorkQueue@@QEAAXXZ TEXTEQU <__imp_?AddRefWorkThreads@CWorkQueue@@QEAAXXZ>
extern __imp_?AddScope@CCatalogAdmin@@QEAAXPEBG0H00@Z:PANYARGS
?AddScope@CCatalogAdmin@@QEAAXPEBG0H00@Z TEXTEQU <__imp_?AddScope@CCatalogAdmin@@QEAAXPEBG0H00@Z>
extern __imp_?AddSortColumn@CDbSortNode@@QEAAHAEBUtagDBID@@HK@Z:PANYARGS
?AddSortColumn@CDbSortNode@@QEAAHAEBUtagDBID@@HK@Z TEXTEQU <__imp_?AddSortColumn@CDbSortNode@@QEAAHAEBUtagDBID@@HK@Z>
extern __imp_?AddTable@CDbNestingNode@@QEAAHPEAVCDbCmdTreeNode@@@Z:PANYARGS
?AddTable@CDbNestingNode@@QEAAHPEAVCDbCmdTreeNode@@@Z TEXTEQU <__imp_?AddTable@CDbNestingNode@@QEAAHPEAVCDbCmdTreeNode@@@Z>
extern __imp_?AddToWorkList@CWorkManager@@QEAAXPEAVCFwAsyncWorkItem@@@Z:PANYARGS
?AddToWorkList@CWorkManager@@QEAAXPEAVCFwAsyncWorkItem@@@Z TEXTEQU <__imp_?AddToWorkList@CWorkManager@@QEAAXPEAVCFwAsyncWorkItem@@@Z>
extern __imp_?AddToWorkQueue@CFwAsyncWorkItem@@QEAAXXZ:PANYARGS
?AddToWorkQueue@CFwAsyncWorkItem@@QEAAXXZ TEXTEQU <__imp_?AddToWorkQueue@CFwAsyncWorkItem@@QEAAXXZ>
extern __imp_?AllocAndCopyWString@CDbCmdTreeNode@@SAPEAGPEBG@Z:PANYARGS
?AllocAndCopyWString@CDbCmdTreeNode@@SAPEAGPEBG@Z TEXTEQU <__imp_?AllocAndCopyWString@CDbCmdTreeNode@@SAPEAGPEBG@Z>
extern __imp_?AllocHeapAndCopy@@YAPEAGPEBGAEAK@Z:PANYARGS
?AllocHeapAndCopy@@YAPEAGPEBGAEAK@Z TEXTEQU <__imp_?AllocHeapAndCopy@@YAPEAGPEBGAEAK@Z>
extern __imp_?AllocHeapAndGetWString@@YAPEAGAEAVPDeSerStream@@@Z:PANYARGS
?AllocHeapAndGetWString@@YAPEAGAEAVPDeSerStream@@@Z TEXTEQU <__imp_?AllocHeapAndGetWString@@YAPEAGAEAVPDeSerStream@@@Z>
extern __imp_?Append@CEnumString@@QEAAXPEBG@Z:PANYARGS
?Append@CEnumString@@QEAAXPEBG@Z TEXTEQU <__imp_?Append@CEnumString@@QEAAXPEBG@Z>
extern __imp_?Append@CEnumWorkid@@QEAAXK@Z:PANYARGS
?Append@CEnumWorkid@@QEAAXK@Z TEXTEQU <__imp_?Append@CEnumWorkid@@QEAAXK@Z>
extern __imp_?AppendChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z:PANYARGS
?AppendChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z TEXTEQU <__imp_?AppendChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z>
extern __imp_?AppendListElement@CDbListAnchor@@IEAAHGAEBUtagDBID@@@Z:PANYARGS
?AppendListElement@CDbListAnchor@@IEAAHGAEBUtagDBID@@@Z TEXTEQU <__imp_?AppendListElement@CDbListAnchor@@IEAAHGAEBUtagDBID@@@Z>
extern __imp_?AppendListElement@CDbListAnchor@@IEAAHPEAVCDbCmdTreeNode@@@Z:PANYARGS
?AppendListElement@CDbListAnchor@@IEAAHPEAVCDbCmdTreeNode@@@Z TEXTEQU <__imp_?AppendListElement@CDbListAnchor@@IEAAHPEAVCDbCmdTreeNode@@@Z>
extern __imp_?AppendListElement@CDbProjectListAnchor@@QEAAHAEBUtagDBID@@PEAG@Z:PANYARGS
?AppendListElement@CDbProjectListAnchor@@QEAAHAEBUtagDBID@@PEAG@Z TEXTEQU <__imp_?AppendListElement@CDbProjectListAnchor@@QEAAHAEBUtagDBID@@PEAG@Z>
extern __imp_?BeginTransaction@CPropStoreManager@@QEAA_KXZ:PANYARGS
?BeginTransaction@CPropStoreManager@@QEAA_KXZ TEXTEQU <__imp_?BeginTransaction@CPropStoreManager@@QEAA_KXZ>
extern __imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@AEBU_GUID@@PEAPEAUIFilter@@H@Z:PANYARGS
?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@AEBU_GUID@@PEAPEAUIFilter@@H@Z TEXTEQU <__imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@AEBU_GUID@@PEAPEAUIFilter@@H@Z>
extern __imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@PEAPEAUIFilter@@H@Z:PANYARGS
?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@PEAPEAUIFilter@@H@Z TEXTEQU <__imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@PEAPEAUIFilter@@H@Z>
extern __imp_?BorrowBuffer@CPhysStorage@@QEAAPEAKKHH@Z:PANYARGS
?BorrowBuffer@CPhysStorage@@QEAAPEAKKHH@Z TEXTEQU <__imp_?BorrowBuffer@CPhysStorage@@QEAAPEAKKHH@Z>
extern __imp_?BorrowNewBuffer@CPhysStorage@@QEAAPEAKK@Z:PANYARGS
?BorrowNewBuffer@CPhysStorage@@QEAAPEAKK@Z TEXTEQU <__imp_?BorrowNewBuffer@CPhysStorage@@QEAAPEAKK@Z>
extern __imp_?BuildRegistryPropertiesKey@@YAXAEAV?$XArray@G@@PEBG@Z:PANYARGS
?BuildRegistryPropertiesKey@@YAXAEAV?$XArray@G@@PEBG@Z TEXTEQU <__imp_?BuildRegistryPropertiesKey@@YAXAEAV?$XArray@G@@PEBG@Z>
extern __imp_?BuildRegistryScopesKey@@YAXAEAV?$XArray@G@@PEBG@Z:PANYARGS
?BuildRegistryScopesKey@@YAXAEAV?$XArray@G@@PEBG@Z TEXTEQU <__imp_?BuildRegistryScopesKey@@YAXAEAV?$XArray@G@@PEBG@Z>
extern __imp_?CIShutdown@@YAXXZ:PANYARGS
?CIShutdown@@YAXXZ TEXTEQU <__imp_?CIShutdown@@YAXXZ>
extern __imp_?ChangeCurrentCatalog@CCatState@@QEAAXPEBG@Z:PANYARGS
?ChangeCurrentCatalog@CCatState@@QEAAXPEBG@Z TEXTEQU <__imp_?ChangeCurrentCatalog@CCatState@@QEAAXPEBG@Z>
extern __imp_?ChangeCurrentDepth@CCatState@@QEAAXH@Z:PANYARGS
?ChangeCurrentDepth@CCatState@@QEAAXH@Z TEXTEQU <__imp_?ChangeCurrentDepth@CCatState@@QEAAXH@Z>
extern __imp_?ChangeCurrentMachine@CCatState@@QEAAXPEBG@Z:PANYARGS
?ChangeCurrentMachine@CCatState@@QEAAXPEBG@Z TEXTEQU <__imp_?ChangeCurrentMachine@CCatState@@QEAAXPEBG@Z>
extern __imp_?ChangeCurrentScope@CCatState@@QEAAXPEBG@Z:PANYARGS
?ChangeCurrentScope@CCatState@@QEAAXPEBG@Z TEXTEQU <__imp_?ChangeCurrentScope@CCatState@@QEAAXPEBG@Z>
extern __imp_?ChangeDirty@CPropStoreInfo@@AEAAXH@Z:PANYARGS
?ChangeDirty@CPropStoreInfo@@AEAAXH@Z TEXTEQU <__imp_?ChangeDirty@CPropStoreInfo@@AEAAXH@Z>
extern __imp_?CheckError@CLocalGlobalPropertyList@@QEAAJAEAKPEAPEAG@Z:PANYARGS
?CheckError@CLocalGlobalPropertyList@@QEAAJAEAKPEAPEAG@Z TEXTEQU <__imp_?CheckError@CLocalGlobalPropertyList@@QEAAJAEAKPEAPEAG@Z>
extern __imp_?CheckError@CPropListFile@@QEAAJAEAKPEAPEAG@Z:PANYARGS
?CheckError@CPropListFile@@QEAAJAEAKPEAPEAG@Z TEXTEQU <__imp_?CheckError@CPropListFile@@QEAAJAEAKPEAPEAG@Z>
extern __imp_?CheckHasIndexTable@CiStorage@@SAHPEBG@Z:PANYARGS
?CheckHasIndexTable@CiStorage@@SAHPEBG@Z TEXTEQU <__imp_?CheckHasIndexTable@CiStorage@@SAHPEBG@Z>
extern __imp_CiCreateSecurityDescriptor:PANYARGS
CiCreateSecurityDescriptor TEXTEQU <__imp_CiCreateSecurityDescriptor>
extern __imp_?CiGetPassword@@YAHPEBG0PEAG@Z:PANYARGS
?CiGetPassword@@YAHPEBG0PEAG@Z TEXTEQU <__imp_?CiGetPassword@@YAHPEBG0PEAG@Z>
extern __imp_?CiNtOpen@@YAPEAXPEBGKKK@Z:PANYARGS
?CiNtOpen@@YAPEAXPEBGKKK@Z TEXTEQU <__imp_?CiNtOpen@@YAPEAXPEBGKKK@Z>
extern __imp_?CiNtOpenNoThrow@@YAJAEAPEAXPEBGKKK@Z:PANYARGS
?CiNtOpenNoThrow@@YAJAEAPEAXPEBGKKK@Z TEXTEQU <__imp_?CiNtOpenNoThrow@@YAJAEAPEAXPEBGKKK@Z>
extern __imp_?Cleanup@CDbColId@@QEAAXXZ:PANYARGS
?Cleanup@CDbColId@@QEAAXXZ TEXTEQU <__imp_?Cleanup@CDbColId@@QEAAXXZ>
extern __imp_?CleanupDataValue@CDbCmdTreeNode@@IEAAXXZ:PANYARGS
?CleanupDataValue@CDbCmdTreeNode@@IEAAXXZ TEXTEQU <__imp_?CleanupDataValue@CDbCmdTreeNode@@IEAAXXZ>
extern __imp_?ClearList@CCombinedPropertyList@@QEAAXXZ:PANYARGS
?ClearList@CCombinedPropertyList@@QEAAXXZ TEXTEQU <__imp_?ClearList@CCombinedPropertyList@@QEAAXXZ>
extern __imp_?ClearList@CPropertyList@@QEAAXXZ:PANYARGS
?ClearList@CPropertyList@@QEAAXXZ TEXTEQU <__imp_?ClearList@CPropertyList@@QEAAXXZ>
extern __imp_?Clone@CDbCmdTreeNode@@QEBAPEAV1@H@Z:PANYARGS
?Clone@CDbCmdTreeNode@@QEBAPEAV1@H@Z TEXTEQU <__imp_?Clone@CDbCmdTreeNode@@QEBAPEAV1@H@Z>
extern __imp_?Clone@CEnumString@@UEAAJPEAPEAUIEnumString@@@Z:PANYARGS
?Clone@CEnumString@@UEAAJPEAPEAUIEnumString@@@Z TEXTEQU <__imp_?Clone@CEnumString@@UEAAJPEAPEAUIEnumString@@@Z>
extern __imp_?Clone@CNodeRestriction@@QEBAPEAV1@XZ:PANYARGS
?Clone@CNodeRestriction@@QEBAPEAV1@XZ TEXTEQU <__imp_?Clone@CNodeRestriction@@QEBAPEAV1@XZ>
extern __imp_?Clone@COccRestriction@@QEBAPEAV1@XZ:PANYARGS
?Clone@COccRestriction@@QEBAPEAV1@XZ TEXTEQU <__imp_?Clone@COccRestriction@@QEBAPEAV1@XZ>
extern __imp_?Clone@CRestriction@@QEBAPEAV1@XZ:PANYARGS
?Clone@CRestriction@@QEBAPEAV1@XZ TEXTEQU <__imp_?Clone@CRestriction@@QEBAPEAV1@XZ>
extern __imp_?Close@CPhysStorage@@QEAAXXZ:PANYARGS
?Close@CPhysStorage@@QEAAXXZ TEXTEQU <__imp_?Close@CPhysStorage@@QEAAXXZ>
extern __imp_?Close@CPipeClient@@IEAAXXZ:PANYARGS
?Close@CPipeClient@@IEAAXXZ TEXTEQU <__imp_?Close@CPipeClient@@IEAAXXZ>
extern __imp_?Close@CPropSetMap@COLEPropManager@@QEAAXXZ:PANYARGS
?Close@CPropSetMap@COLEPropManager@@QEAAXXZ TEXTEQU <__imp_?Close@CPropSetMap@COLEPropManager@@QEAAXXZ>
extern __imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecord@@@Z:PANYARGS
?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecord@@@Z TEXTEQU <__imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecord@@@Z>
extern __imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecordForWrites@@@Z:PANYARGS
?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecordForWrites@@@Z TEXTEQU <__imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecordForWrites@@@Z>
extern __imp_?Commit@CRcovStrmAppendTrans@@QEAAXXZ:PANYARGS
?Commit@CRcovStrmAppendTrans@@QEAAXXZ TEXTEQU <__imp_?Commit@CRcovStrmAppendTrans@@QEAAXXZ>
extern __imp_?Commit@CRcovStrmMDTrans@@QEAAXXZ:PANYARGS
?Commit@CRcovStrmMDTrans@@QEAAXXZ TEXTEQU <__imp_?Commit@CRcovStrmMDTrans@@QEAAXXZ>
extern __imp_?Commit@CRcovStrmWriteTrans@@QEAAXXZ:PANYARGS
?Commit@CRcovStrmWriteTrans@@QEAAXXZ TEXTEQU <__imp_?Commit@CRcovStrmWriteTrans@@QEAAXXZ>
extern __imp_?ContainsDrive@CDriveInfo@@SAHPEBG@Z:PANYARGS
?ContainsDrive@CDriveInfo@@SAHPEBG@Z TEXTEQU <__imp_?ContainsDrive@CDriveInfo@@SAHPEBG@Z>
extern __imp_?CreateSubdirs@CMachineAdmin@@QEAAXPEBG@Z:PANYARGS
?CreateSubdirs@CMachineAdmin@@QEAAXPEBG@Z TEXTEQU <__imp_?CreateSubdirs@CMachineAdmin@@QEAAXPEBG@Z>
extern __imp_?DataWriteRead@CRequestClient@@QEAAXPEAXK0KAEAK@Z:PANYARGS
?DataWriteRead@CRequestClient@@QEAAXPEAXK0KAEAK@Z TEXTEQU <__imp_?DataWriteRead@CRequestClient@@QEAAXPEAXK0KAEAK@Z>
extern __imp_?DecodeEscapes@@YAXPEAGAEAK0@Z:PANYARGS
?DecodeEscapes@@YAXPEAGAEAK0@Z TEXTEQU <__imp_?DecodeEscapes@@YAXPEAGAEAK0@Z>
extern __imp_?DecodeHtmlNumeric@@YAXPEAG@Z:PANYARGS
?DecodeHtmlNumeric@@YAXPEAG@Z TEXTEQU <__imp_?DecodeHtmlNumeric@@YAXPEAG@Z>
extern __imp_?DecodeURLEscapes@@YAXPEAEAEAKPEAGK@Z:PANYARGS
?DecodeURLEscapes@@YAXPEAEAEAKPEAGK@Z TEXTEQU <__imp_?DecodeURLEscapes@@YAXPEAEAEAKPEAGK@Z>
extern __imp_?DeleteRecord@CPropStoreManager@@QEAAXK@Z:PANYARGS
?DeleteRecord@CPropStoreManager@@QEAAXK@Z TEXTEQU <__imp_?DeleteRecord@CPropStoreManager@@QEAAXK@Z>
extern __imp_?DeleteRegistryParamNoThrow@CCatalogAdmin@@QEAAXPEBG@Z:PANYARGS
?DeleteRegistryParamNoThrow@CCatalogAdmin@@QEAAXPEBG@Z TEXTEQU <__imp_?DeleteRegistryParamNoThrow@CCatalogAdmin@@QEAAXPEBG@Z>
extern __imp_?DetermineDriveType@CiStorage@@SAIPEBG@Z:PANYARGS
?DetermineDriveType@CiStorage@@SAIPEBG@Z TEXTEQU <__imp_?DetermineDriveType@CiStorage@@SAIPEBG@Z>
extern __imp_?DisableCI@CMachineAdmin@@QEAAHXZ:PANYARGS
?DisableCI@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?DisableCI@CMachineAdmin@@QEAAHXZ>
extern __imp_?DisableNotification@CRegNotify@@QEAAXXZ:PANYARGS
?DisableNotification@CRegNotify@@QEAAXXZ TEXTEQU <__imp_?DisableNotification@CRegNotify@@QEAAXXZ>
extern __imp_?DisableVPathNotify@CMetaDataMgr@@QEAAXXZ:PANYARGS
?DisableVPathNotify@CMetaDataMgr@@QEAAXXZ TEXTEQU <__imp_?DisableVPathNotify@CMetaDataMgr@@QEAAXXZ>
extern __imp_?Disconnect@CRequestClient@@QEAAXXZ:PANYARGS
?Disconnect@CRequestClient@@QEAAXXZ TEXTEQU <__imp_?Disconnect@CRequestClient@@QEAAXXZ>
extern __imp_?DoIt@CCopyRcovObject@@QEAAJXZ:PANYARGS
?DoIt@CCopyRcovObject@@QEAAJXZ TEXTEQU <__imp_?DoIt@CCopyRcovObject@@QEAAJXZ>
extern __imp_?DoUpdates@CFilterDaemon@@QEAAJXZ:PANYARGS
?DoUpdates@CFilterDaemon@@QEAAJXZ TEXTEQU <__imp_?DoUpdates@CFilterDaemon@@QEAAJXZ>
extern __imp_?Done@CFwAsyncWorkItem@@QEAAXXZ:PANYARGS
?Done@CFwAsyncWorkItem@@QEAAXXZ TEXTEQU <__imp_?Done@CFwAsyncWorkItem@@QEAAXXZ>
extern __imp_?DumpWorkId@@YAJPEBGKPEAEAEAK00K@Z:PANYARGS
?DumpWorkId@@YAJPEBGKPEAEAEAK00K@Z TEXTEQU <__imp_?DumpWorkId@@YAJPEBGKPEAEAEAK00K@Z>
extern __imp_?Empty@CPidLookupTable@@QEAAXXZ:PANYARGS
?Empty@CPidLookupTable@@QEAAXXZ TEXTEQU <__imp_?Empty@CPidLookupTable@@QEAAXXZ>
extern __imp_?Empty@CPropStoreManager@@QEAAXXZ:PANYARGS
?Empty@CPropStoreManager@@QEAAXXZ TEXTEQU <__imp_?Empty@CPropStoreManager@@QEAAXXZ>
extern __imp_?Empty@CRcovStrmWriteTrans@@QEAAXXZ:PANYARGS
?Empty@CRcovStrmWriteTrans@@QEAAXXZ TEXTEQU <__imp_?Empty@CRcovStrmWriteTrans@@QEAAXXZ>
extern __imp_?Empty@CSdidLookupTable@@QEAAXXZ:PANYARGS
?Empty@CSdidLookupTable@@QEAAXXZ TEXTEQU <__imp_?Empty@CSdidLookupTable@@QEAAXXZ>
extern __imp_?EnableCI@CMachineAdmin@@QEAAHXZ:PANYARGS
?EnableCI@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?EnableCI@CMachineAdmin@@QEAAHXZ>
extern __imp_?EnableVPathNotify@CMetaDataMgr@@QEAAXPEAVCMetaDataVPathChangeCallBack@@@Z:PANYARGS
?EnableVPathNotify@CMetaDataMgr@@QEAAXPEAVCMetaDataVPathChangeCallBack@@@Z TEXTEQU <__imp_?EnableVPathNotify@CMetaDataMgr@@QEAAXPEAVCMetaDataVPathChangeCallBack@@@Z>
extern __imp_?EndTransaction@CPropStoreManager@@QEAAX_KHKK@Z:PANYARGS
?EndTransaction@CPropStoreManager@@QEAAX_KHKK@Z TEXTEQU <__imp_?EndTransaction@CPropStoreManager@@QEAAX_KHKK@Z>
extern __imp_?Enum@CWin32RegAccess@@QEAAHPEAGK@Z:PANYARGS
?Enum@CWin32RegAccess@@QEAAHPEAGK@Z TEXTEQU <__imp_?Enum@CWin32RegAccess@@QEAAHPEAGK@Z>
extern __imp_?EnumPropInfo@CEmptyPropertyList@@UEAAJKPEAPEBGPEAPEAUtagDBID@@PEAGPEAI@Z:PANYARGS
?EnumPropInfo@CEmptyPropertyList@@UEAAJKPEAPEBGPEAPEAUtagDBID@@PEAGPEAI@Z TEXTEQU <__imp_?EnumPropInfo@CEmptyPropertyList@@UEAAJKPEAPEBGPEAPEAUtagDBID@@PEAGPEAI@Z>
extern __imp_?EnumVPaths@CMetaDataMgr@@QEAAXAEAVCMetaDataCallBack@@@Z:PANYARGS
?EnumVPaths@CMetaDataMgr@@QEAAXAEAVCMetaDataCallBack@@@Z TEXTEQU <__imp_?EnumVPaths@CMetaDataMgr@@QEAAXAEAVCMetaDataCallBack@@@Z>
extern __imp_?EnumVServers@CMetaDataMgr@@QEAAXAEAVCMetaDataVirtualServerCallBack@@@Z:PANYARGS
?EnumVServers@CMetaDataMgr@@QEAAXAEAVCMetaDataVirtualServerCallBack@@@Z TEXTEQU <__imp_?EnumVServers@CMetaDataMgr@@QEAAXAEAVCMetaDataVirtualServerCallBack@@@Z>
extern __imp_?EnumerateFilesInDir@CiStorage@@SAXPEBGAEAVCEnumString@@@Z:PANYARGS
?EnumerateFilesInDir@CiStorage@@SAXPEBGAEAVCEnumString@@@Z TEXTEQU <__imp_?EnumerateFilesInDir@CiStorage@@SAXPEBGAEAVCEnumString@@@Z>
extern __imp_?EnumerateProperty@CPidLookupTable@@QEAAHAEAVCFullPropSpec@@AEAI@Z:PANYARGS
?EnumerateProperty@CPidLookupTable@@QEAAHAEAVCFullPropSpec@@AEAI@Z TEXTEQU <__imp_?EnumerateProperty@CPidLookupTable@@QEAAHAEAVCFullPropSpec@@AEAI@Z>
extern __imp_?EnumerateValues@CRegAccess@@QEAAXPEAGAEAVCRegCallBack@@@Z:PANYARGS
?EnumerateValues@CRegAccess@@QEAAXPEAGAEAVCRegCallBack@@@Z TEXTEQU <__imp_?EnumerateValues@CRegAccess@@QEAAXPEAGAEAVCRegCallBack@@@Z>
extern __imp_?Eof@CMmStreamConsecBuf@@QEAAHXZ:PANYARGS
?Eof@CMmStreamConsecBuf@@QEAAHXZ TEXTEQU <__imp_?Eof@CMmStreamConsecBuf@@QEAAHXZ>
extern __imp_?ExtensionHasScriptMap@CMetaDataMgr@@QEAAHPEBG@Z:PANYARGS
?ExtensionHasScriptMap@CMetaDataMgr@@QEAAHPEBG@Z TEXTEQU <__imp_?ExtensionHasScriptMap@CMetaDataMgr@@QEAAHPEBG@Z>
extern __imp_?FPSToPROPID@CPidConverter@@UEAAJAEBVCFullPropSpec@@AEAK@Z:PANYARGS
?FPSToPROPID@CPidConverter@@UEAAJAEBVCFullPropSpec@@AEAK@Z TEXTEQU <__imp_?FPSToPROPID@CPidConverter@@UEAAJAEBVCFullPropSpec@@AEAK@Z>
extern __imp_?FastInit@CPropStoreManager@@QEAAXPEAVCiStorage@@@Z:PANYARGS
?FastInit@CPropStoreManager@@QEAAXPEAVCiStorage@@@Z TEXTEQU <__imp_?FastInit@CPropStoreManager@@QEAAXPEAVCiStorage@@@Z>
extern __imp_?FetchProperty@COLEPropManager@@QEAAXAEBU_GUID@@AEBUtagPROPSPEC@@PEAUtagPROPVARIANT@@PEAI@Z:PANYARGS
?FetchProperty@COLEPropManager@@QEAAXAEBU_GUID@@AEBUtagPROPSPEC@@PEAUtagPROPVARIANT@@PEAI@Z TEXTEQU <__imp_?FetchProperty@COLEPropManager@@QEAAXAEBU_GUID@@AEBUtagPROPSPEC@@PEAUtagPROPVARIANT@@PEAI@Z>
extern __imp_?FillMax@CKeyArray@@QEAAHH@Z:PANYARGS
?FillMax@CKeyArray@@QEAAHH@Z TEXTEQU <__imp_?FillMax@CKeyArray@@QEAAHH@Z>
extern __imp_?Find@CEmptyPropertyList@@QEAAPEBVCPropEntry@@AEBVCDbColId@@@Z:PANYARGS
?Find@CEmptyPropertyList@@QEAAPEBVCPropEntry@@AEBVCDbColId@@@Z TEXTEQU <__imp_?Find@CEmptyPropertyList@@QEAAPEBVCPropEntry@@AEBVCDbColId@@@Z>
extern __imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@AEBVCDbColId@@@Z:PANYARGS
?Find@CPropertyList@@UEAAPEBVCPropEntry@@AEBVCDbColId@@@Z TEXTEQU <__imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@AEBVCDbColId@@@Z>
extern __imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@PEBG@Z:PANYARGS
?Find@CPropertyList@@UEAAPEBVCPropEntry@@PEBG@Z TEXTEQU <__imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@PEBG@Z>
extern __imp_?FindPropid@CPidLookupTable@@QEAAHAEBVCFullPropSpec@@AEAKH@Z:PANYARGS
?FindPropid@CPidLookupTable@@QEAAHAEBVCFullPropSpec@@AEAKH@Z TEXTEQU <__imp_?FindPropid@CPidLookupTable@@QEAAHAEBVCFullPropSpec@@AEAKH@Z>
extern __imp_?Flush@CDynStream@@QEAAXXZ:PANYARGS
?Flush@CDynStream@@QEAAXXZ TEXTEQU <__imp_?Flush@CDynStream@@QEAAXXZ>
extern __imp_?Flush@CPhysStorage@@QEAAXH@Z:PANYARGS
?Flush@CPhysStorage@@QEAAXH@Z TEXTEQU <__imp_?Flush@CPhysStorage@@QEAAXH@Z>
extern __imp_?Flush@CPropStoreManager@@QEAAXXZ:PANYARGS
?Flush@CPropStoreManager@@QEAAXXZ TEXTEQU <__imp_?Flush@CPropStoreManager@@QEAAXXZ>
extern __imp_?FlushIdle@CCiOle@@SAXXZ:PANYARGS
?FlushIdle@CCiOle@@SAXXZ TEXTEQU <__imp_?FlushIdle@CCiOle@@SAXXZ>
extern __imp_?FormFullTree@CTextToTree@@QEAAPEAUtagDBCOMMANDTREE@@XZ:PANYARGS
?FormFullTree@CTextToTree@@QEAAPEAUtagDBCOMMANDTREE@@XZ TEXTEQU <__imp_?FormFullTree@CTextToTree@@QEAAPEAUtagDBCOMMANDTREE@@XZ>
extern __imp_?FormQueryTree@@YAPEAVCDbCmdTreeNode@@AEAV1@AEAVCCatState@@PEAUIColumnMapper@@HH@Z:PANYARGS
?FormQueryTree@@YAPEAVCDbCmdTreeNode@@AEAV1@AEAVCCatState@@PEAUIColumnMapper@@HH@Z TEXTEQU <__imp_?FormQueryTree@@YAPEAVCDbCmdTreeNode@@AEAV1@AEAVCCatState@@PEAUIColumnMapper@@HH@Z>
extern __imp_FsCiShutdown:PANYARGS
FsCiShutdown TEXTEQU <__imp_FsCiShutdown>
extern __imp_?Get@CRegAccess@@QEAAKPEBG@Z:PANYARGS
?Get@CRegAccess@@QEAAKPEBG@Z TEXTEQU <__imp_?Get@CRegAccess@@QEAAKPEBG@Z>
extern __imp_?Get@CRegAccess@@QEAAXPEBGPEAGI@Z:PANYARGS
?Get@CRegAccess@@QEAAXPEBGPEAGI@Z TEXTEQU <__imp_?Get@CRegAccess@@QEAAXPEBGPEAGI@Z>
extern __imp_?Get@CWin32RegAccess@@QEAAHPEBGAEAK@Z:PANYARGS
?Get@CWin32RegAccess@@QEAAHPEBGAEAK@Z TEXTEQU <__imp_?Get@CWin32RegAccess@@QEAAHPEBGAEAK@Z>
extern __imp_?Get@CWin32RegAccess@@QEAAHPEBGPEAGIH@Z:PANYARGS
?Get@CWin32RegAccess@@QEAAHPEBGPEAGIH@Z TEXTEQU <__imp_?Get@CWin32RegAccess@@QEAAHPEBGPEAGIH@Z>
extern __imp_?GetAllEntries@CPropertyList@@UEAAJPEAPEAVCPropEntry@@K@Z:PANYARGS
?GetAllEntries@CPropertyList@@UEAAJPEAPEAVCPropEntry@@K@Z TEXTEQU <__imp_?GetAllEntries@CPropertyList@@UEAAJPEAPEAVCPropEntry@@K@Z>
extern __imp_?GetBOOL@CAllocStorageVariant@@QEBAFI@Z:PANYARGS
?GetBOOL@CAllocStorageVariant@@QEBAFI@Z TEXTEQU <__imp_?GetBOOL@CAllocStorageVariant@@QEBAFI@Z>
extern __imp_?GetBackupSize@CPropStoreManager@@QEAAKK@Z:PANYARGS
?GetBackupSize@CPropStoreManager@@QEAAKK@Z TEXTEQU <__imp_?GetBackupSize@CPropStoreManager@@QEAAKK@Z>
extern __imp_?GetBlob@CMemDeSerStream@@UEAAXPEAEK@Z:PANYARGS
?GetBlob@CMemDeSerStream@@UEAAXPEAEK@Z TEXTEQU <__imp_?GetBlob@CMemDeSerStream@@UEAAXPEAEK@Z>
extern __imp_?GetBrowserCodepage@@YAKAEAVCWebServer@@K@Z:PANYARGS
?GetBrowserCodepage@@YAKAEAVCWebServer@@K@Z TEXTEQU <__imp_?GetBrowserCodepage@@YAKAEAVCWebServer@@K@Z>
extern __imp_?GetByte@CMemDeSerStream@@UEAAEXZ:PANYARGS
?GetByte@CMemDeSerStream@@UEAAEXZ TEXTEQU <__imp_?GetByte@CMemDeSerStream@@UEAAEXZ>
extern __imp_?GetCD@CCatState@@QEAAPEBGXZ:PANYARGS
?GetCD@CCatState@@QEAAPEBGXZ TEXTEQU <__imp_?GetCD@CCatState@@QEAAPEBGXZ>
extern __imp_?GetCGIVariable@CWebServer@@QEAAHPEBDAEAV?$XArray@G@@AEAK@Z:PANYARGS
?GetCGIVariable@CWebServer@@QEAAHPEBDAEAV?$XArray@G@@AEAK@Z TEXTEQU <__imp_?GetCGIVariable@CWebServer@@QEAAHPEBDAEAV?$XArray@G@@AEAK@Z>
extern __imp_?GetCGIVariableW@CWebServer@@QEAAHPEBGAEAV?$XArray@G@@AEAK@Z:PANYARGS
?GetCGIVariableW@CWebServer@@QEAAHPEBGAEAV?$XArray@G@@AEAK@Z TEXTEQU <__imp_?GetCGIVariableW@CWebServer@@QEAAHPEBGAEAV?$XArray@G@@AEAK@Z>
extern __imp_?GetCLSID@CAllocStorageVariant@@QEBA?AU_GUID@@I@Z:PANYARGS
?GetCLSID@CAllocStorageVariant@@QEBA?AU_GUID@@I@Z TEXTEQU <__imp_?GetCLSID@CAllocStorageVariant@@QEBA?AU_GUID@@I@Z>
extern __imp_?GetCY@CAllocStorageVariant@@QEBA?ATtagCY@@I@Z:PANYARGS
?GetCY@CAllocStorageVariant@@QEBA?ATtagCY@@I@Z TEXTEQU <__imp_?GetCY@CAllocStorageVariant@@QEBA?ATtagCY@@I@Z>
extern __imp_?GetCategory@CCatState@@QEBAPEBGI@Z:PANYARGS
?GetCategory@CCatState@@QEBAPEBGI@Z TEXTEQU <__imp_?GetCategory@CCatState@@QEBAPEBGI@Z>
extern __imp_?GetChar@CMemDeSerStream@@UEAAXPEADK@Z:PANYARGS
?GetChar@CMemDeSerStream@@UEAAXPEADK@Z TEXTEQU <__imp_?GetChar@CMemDeSerStream@@UEAAXPEADK@Z>
extern __imp_?GetColumn@CCatState@@QEBAPEBGI@Z:PANYARGS
?GetColumn@CCatState@@QEBAPEBGI@Z TEXTEQU <__imp_?GetColumn@CCatState@@QEBAPEBGI@Z>
extern __imp_?GetCommandChar@CQueryScanner@@QEAAGXZ:PANYARGS
?GetCommandChar@CQueryScanner@@QEAAGXZ TEXTEQU <__imp_?GetCommandChar@CQueryScanner@@QEAAGXZ>
extern __imp_?GetDATE@CAllocStorageVariant@@QEBANI@Z:PANYARGS
?GetDATE@CAllocStorageVariant@@QEBANI@Z TEXTEQU <__imp_?GetDATE@CAllocStorageVariant@@QEBANI@Z>
extern __imp_?GetDWORDParam@CCatalogAdmin@@QEAAHPEBGAEAK@Z:PANYARGS
?GetDWORDParam@CCatalogAdmin@@QEAAHPEBGAEAK@Z TEXTEQU <__imp_?GetDWORDParam@CCatalogAdmin@@QEAAHPEBGAEAK@Z>
extern __imp_?GetDWORDParam@CMachineAdmin@@QEAAHPEBGAEAK@Z:PANYARGS
?GetDWORDParam@CMachineAdmin@@QEAAHPEBGAEAK@Z TEXTEQU <__imp_?GetDWORDParam@CMachineAdmin@@QEAAHPEBGAEAK@Z>
extern __imp_?GetDiskSpace@CDriveInfo@@QEAAXAEA_J0@Z:PANYARGS
?GetDiskSpace@CDriveInfo@@QEAAXAEA_J0@Z TEXTEQU <__imp_?GetDiskSpace@CDriveInfo@@QEAAXAEA_J0@Z>
extern __imp_?GetDouble@CMemDeSerStream@@UEAANXZ:PANYARGS
?GetDouble@CMemDeSerStream@@UEAANXZ TEXTEQU <__imp_?GetDouble@CMemDeSerStream@@UEAANXZ>
extern __imp_?GetDrive@CDriveInfo@@SAXPEBGPEAG@Z:PANYARGS
?GetDrive@CDriveInfo@@SAXPEBGPEAG@Z TEXTEQU <__imp_?GetDrive@CDriveInfo@@SAXPEBGPEAG@Z>
extern __imp_?GetEntryBuffer@CGenericCiProxy@@QEAAPEAEAEAK@Z:PANYARGS
?GetEntryBuffer@CGenericCiProxy@@QEAAPEAEAEAK@Z TEXTEQU <__imp_?GetEntryBuffer@CGenericCiProxy@@QEAAPEAEAEAK@Z>
extern __imp_?GetFILETIME@CAllocStorageVariant@@QEBA?AU_FILETIME@@I@Z:PANYARGS
?GetFILETIME@CAllocStorageVariant@@QEBA?AU_FILETIME@@I@Z TEXTEQU <__imp_?GetFILETIME@CAllocStorageVariant@@QEBA?AU_FILETIME@@I@Z>
extern __imp_?GetFileName@CPathParser@@QEBAHPEAGAEAK@Z:PANYARGS
?GetFileName@CPathParser@@QEBAHPEAGAEAK@Z TEXTEQU <__imp_?GetFileName@CPathParser@@QEBAHPEAGAEAK@Z>
extern __imp_?GetFileSystem@CDriveInfo@@QEAA?AW4eFileSystem@1@H@Z:PANYARGS
?GetFileSystem@CDriveInfo@@QEAA?AW4eFileSystem@1@H@Z TEXTEQU <__imp_?GetFileSystem@CDriveInfo@@QEAA?AW4eFileSystem@1@H@Z>
extern __imp_?GetFloat@CMemDeSerStream@@UEAAMXZ:PANYARGS
?GetFloat@CMemDeSerStream@@UEAAMXZ TEXTEQU <__imp_?GetFloat@CMemDeSerStream@@UEAAMXZ>
extern __imp_?GetGUID@CMemDeSerStream@@UEAAXAEAU_GUID@@@Z:PANYARGS
?GetGUID@CMemDeSerStream@@UEAAXAEAU_GUID@@@Z TEXTEQU <__imp_?GetGUID@CMemDeSerStream@@UEAAXAEAU_GUID@@@Z>
extern __imp_?GetGlobalPropListFile@@YAPEAVCPropListFile@@XZ:PANYARGS
?GetGlobalPropListFile@@YAPEAVCPropListFile@@XZ TEXTEQU <__imp_?GetGlobalPropListFile@@YAPEAVCPropListFile@@XZ>
extern __imp_?GetGlobalStaticPropertyList@@YAPEAVCStaticPropertyList@@XZ:PANYARGS
?GetGlobalStaticPropertyList@@YAPEAVCStaticPropertyList@@XZ TEXTEQU <__imp_?GetGlobalStaticPropertyList@@YAPEAVCStaticPropertyList@@XZ>
extern __imp_?GetI2@CAllocStorageVariant@@QEBAFI@Z:PANYARGS
?GetI2@CAllocStorageVariant@@QEBAFI@Z TEXTEQU <__imp_?GetI2@CAllocStorageVariant@@QEBAFI@Z>
extern __imp_?GetI4@CAllocStorageVariant@@QEBAJI@Z:PANYARGS
?GetI4@CAllocStorageVariant@@QEBAJI@Z TEXTEQU <__imp_?GetI4@CAllocStorageVariant@@QEBAJI@Z>
extern __imp_?GetI8@CAllocStorageVariant@@QEBA?AT_LARGE_INTEGER@@I@Z:PANYARGS
?GetI8@CAllocStorageVariant@@QEBA?AT_LARGE_INTEGER@@I@Z TEXTEQU <__imp_?GetI8@CAllocStorageVariant@@QEBA?AT_LARGE_INTEGER@@I@Z>
extern __imp_?GetLCIDFromString@@YAKPEAG@Z:PANYARGS
?GetLCIDFromString@@YAKPEAG@Z TEXTEQU <__imp_?GetLCIDFromString@@YAKPEAG@Z>
extern __imp_?GetLPSTR@CAllocStorageVariant@@QEBAPEADI@Z:PANYARGS
?GetLPSTR@CAllocStorageVariant@@QEBAPEADI@Z TEXTEQU <__imp_?GetLPSTR@CAllocStorageVariant@@QEBAPEADI@Z>
extern __imp_?GetLPWSTR@CAllocStorageVariant@@QEBAPEAGI@Z:PANYARGS
?GetLPWSTR@CAllocStorageVariant@@QEBAPEAGI@Z TEXTEQU <__imp_?GetLPWSTR@CAllocStorageVariant@@QEBAPEAGI@Z>
extern __imp_?GetLocation@CCatalogAdmin@@QEAAPEBGXZ:PANYARGS
?GetLocation@CCatalogAdmin@@QEAAPEBGXZ TEXTEQU <__imp_?GetLocation@CCatalogAdmin@@QEAAPEBGXZ>
extern __imp_?GetLong@CMemDeSerStream@@UEAAJXZ:PANYARGS
?GetLong@CMemDeSerStream@@UEAAJXZ TEXTEQU <__imp_?GetLong@CMemDeSerStream@@UEAAJXZ>
extern __imp_?GetNumber@CQueryScanner@@QEAAHAEAKAEAH@Z:PANYARGS
?GetNumber@CQueryScanner@@QEAAHAEAKAEAH@Z TEXTEQU <__imp_?GetNumber@CQueryScanner@@QEAAHAEAKAEAH@Z>
extern __imp_?GetNumber@CQueryScanner@@QEAAHAEAN@Z:PANYARGS
?GetNumber@CQueryScanner@@QEAAHAEAN@Z TEXTEQU <__imp_?GetNumber@CQueryScanner@@QEAAHAEAN@Z>
extern __imp_?GetNumber@CQueryScanner@@QEAAHAEA_JAEAH@Z:PANYARGS
?GetNumber@CQueryScanner@@QEAAHAEA_JAEAH@Z TEXTEQU <__imp_?GetNumber@CQueryScanner@@QEAAHAEA_JAEAH@Z>
extern __imp_?GetNumber@CQueryScanner@@QEAAHAEA_KAEAH@Z:PANYARGS
?GetNumber@CQueryScanner@@QEAAHAEA_KAEAH@Z TEXTEQU <__imp_?GetNumber@CQueryScanner@@QEAAHAEA_KAEAH@Z>
extern __imp_?GetOffset@CKeyDeComp@@QEAAXAEAUBitOffset@@@Z:PANYARGS
?GetOffset@CKeyDeComp@@QEAAXAEAUBitOffset@@@Z TEXTEQU <__imp_?GetOffset@CKeyDeComp@@QEAAXAEAUBitOffset@@@Z>
extern __imp_?GetOleDBErrorInfo@@YAJPEAUIUnknown@@AEBU_GUID@@KIPEAUtagERRORINFO@@PEAPEAUIErrorInfo@@@Z:PANYARGS
?GetOleDBErrorInfo@@YAJPEAUIUnknown@@AEBU_GUID@@KIPEAUtagERRORINFO@@PEAPEAUIErrorInfo@@@Z TEXTEQU <__imp_?GetOleDBErrorInfo@@YAJPEAUIUnknown@@AEBU_GUID@@KIPEAUtagERRORINFO@@PEAPEAUIErrorInfo@@@Z>
extern __imp_?GetOleError@@YAJAEAVCException@@@Z:PANYARGS
?GetOleError@@YAJAEAVCException@@@Z TEXTEQU <__imp_?GetOleError@@YAJAEAVCException@@@Z>
extern __imp_?GetPhysicalPath@CWebServer@@QEAAKPEBGPEAGKK@Z:PANYARGS
?GetPhysicalPath@CWebServer@@QEAAKPEBGPEAGKK@Z TEXTEQU <__imp_?GetPhysicalPath@CWebServer@@QEAAKPEBGPEAGKK@Z>
extern __imp_?GetPropInfo@CEmptyPropertyList@@QEAAHAEBVCDbColId@@PEAPEBGPEAGPEAI@Z:PANYARGS
?GetPropInfo@CEmptyPropertyList@@QEAAHAEBVCDbColId@@PEAPEBGPEAGPEAI@Z TEXTEQU <__imp_?GetPropInfo@CEmptyPropertyList@@QEAAHAEBVCDbColId@@PEAPEBGPEAGPEAI@Z>
extern __imp_?GetPropInfo@CEmptyPropertyList@@QEAAHPEBGPEAPEAVCDbColId@@PEAGPEAI@Z:PANYARGS
?GetPropInfo@CEmptyPropertyList@@QEAAHPEBGPEAPEAVCDbColId@@PEAGPEAI@Z TEXTEQU <__imp_?GetPropInfo@CEmptyPropertyList@@QEAAHPEBGPEAPEAVCDbColId@@PEAGPEAI@Z>
extern __imp_?GetPropInfoFromId@CEmptyPropertyList@@UEAAJPEBUtagDBID@@PEAPEAGPEAGPEAI@Z:PANYARGS
?GetPropInfoFromId@CEmptyPropertyList@@UEAAJPEBUtagDBID@@PEAPEAGPEAGPEAI@Z TEXTEQU <__imp_?GetPropInfoFromId@CEmptyPropertyList@@UEAAJPEBUtagDBID@@PEAPEAGPEAGPEAI@Z>
extern __imp_?GetPropInfoFromName@CEmptyPropertyList@@UEAAJPEBGPEAPEAUtagDBID@@PEAGPEAI@Z:PANYARGS
?GetPropInfoFromName@CEmptyPropertyList@@UEAAJPEBGPEAPEAUtagDBID@@PEAGPEAI@Z TEXTEQU <__imp_?GetPropInfoFromName@CEmptyPropertyList@@UEAAJPEBGPEAPEAUtagDBID@@PEAGPEAI@Z>
extern __imp_?GetPropType@CEmptyPropertyList@@SAGI@Z:PANYARGS
?GetPropType@CEmptyPropertyList@@SAGI@Z TEXTEQU <__imp_?GetPropType@CEmptyPropertyList@@SAGI@Z>
extern __imp_?GetPropTypeCount@CEmptyPropertyList@@SAIXZ:PANYARGS
?GetPropTypeCount@CEmptyPropertyList@@SAIXZ TEXTEQU <__imp_?GetPropTypeCount@CEmptyPropertyList@@SAIXZ>
extern __imp_?GetPropTypeName@CEmptyPropertyList@@SAPEBGI@Z:PANYARGS
?GetPropTypeName@CEmptyPropertyList@@SAPEBGI@Z TEXTEQU <__imp_?GetPropTypeName@CEmptyPropertyList@@SAPEBGI@Z>
extern __imp_?GetProperties@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPSET@@@Z:PANYARGS
?GetProperties@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPSET@@@Z TEXTEQU <__imp_?GetProperties@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPSET@@@Z>
extern __imp_?GetProperties@CGetDbProps@@QEAAXPEAUIDBProperties@@K@Z:PANYARGS
?GetProperties@CGetDbProps@@QEAAXPEAUIDBProperties@@K@Z TEXTEQU <__imp_?GetProperties@CGetDbProps@@QEAAXPEAUIDBProperties@@K@Z>
extern __imp_?GetPropertyInfo@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPINFOSET@@PEAPEAG@Z:PANYARGS
?GetPropertyInfo@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPINFOSET@@PEAPEAG@Z TEXTEQU <__imp_?GetPropertyInfo@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPINFOSET@@PEAPEAG@Z>
extern __imp_?GetR4@CAllocStorageVariant@@QEBAMI@Z:PANYARGS
?GetR4@CAllocStorageVariant@@QEBAMI@Z TEXTEQU <__imp_?GetR4@CAllocStorageVariant@@QEBAMI@Z>
extern __imp_?GetR8@CAllocStorageVariant@@QEBANI@Z:PANYARGS
?GetR8@CAllocStorageVariant@@QEBANI@Z TEXTEQU <__imp_?GetR8@CAllocStorageVariant@@QEBANI@Z>
extern __imp_?GetSZParam@CMachineAdmin@@QEAAHPEBGPEAGK@Z:PANYARGS
?GetSZParam@CMachineAdmin@@QEAAHPEBGPEAGK@Z TEXTEQU <__imp_?GetSZParam@CMachineAdmin@@QEAAHPEBGPEAGK@Z>
extern __imp_?GetScodeError@@YAJAEAVCException@@@Z:PANYARGS
?GetScodeError@@YAJAEAVCException@@@Z TEXTEQU <__imp_?GetScodeError@@YAJAEAVCException@@@Z>
extern __imp_?GetSecret@@YAHPEBG0PEAPEAGPEAK@Z:PANYARGS
?GetSecret@@YAHPEBG0PEAPEAGPEAK@Z TEXTEQU <__imp_?GetSecret@@YAHPEBG0PEAPEAGPEAK@Z>
extern __imp_?GetSectorSize@CDriveInfo@@QEAAKXZ:PANYARGS
?GetSectorSize@CDriveInfo@@QEAAKXZ TEXTEQU <__imp_?GetSectorSize@CDriveInfo@@QEAAKXZ>
extern __imp_?GetSortProp@CCatState@@QEBAXIPEAPEBGPEAW4SORTDIR@@@Z:PANYARGS
?GetSortProp@CCatState@@QEBAXIPEAPEBGPEAW4SORTDIR@@@Z TEXTEQU <__imp_?GetSortProp@CCatState@@QEBAXIPEAPEBGPEAW4SORTDIR@@@Z>
extern __imp_?GetStackTrace@@YAXPEADK@Z:PANYARGS
?GetStackTrace@@YAXPEADK@Z TEXTEQU <__imp_?GetStackTrace@@YAXPEADK@Z>
extern __imp_?GetStartupData@CGenericCiProxy@@QEAAPEBEAEAU_GUID@@AEAK@Z:PANYARGS
?GetStartupData@CGenericCiProxy@@QEAAPEBEAEAU_GUID@@AEAK@Z TEXTEQU <__imp_?GetStartupData@CGenericCiProxy@@QEAAPEBEAEAU_GUID@@AEAK@Z>
extern __imp_?GetStorage@CPropStoreManager@@QEAAAEAVPStorage@@K@Z:PANYARGS
?GetStorage@CPropStoreManager@@QEAAAEAVPStorage@@K@Z TEXTEQU <__imp_?GetStorage@CPropStoreManager@@QEAAAEAVPStorage@@K@Z>
extern __imp_?GetStr@CKey@@QEBAPEAGXZ:PANYARGS
?GetStr@CKey@@QEBAPEAGXZ TEXTEQU <__imp_?GetStr@CKey@@QEBAPEAGXZ>
extern __imp_?GetStr@CKeyBuf@@QEBAPEAGXZ:PANYARGS
?GetStr@CKeyBuf@@QEBAPEAGXZ TEXTEQU <__imp_?GetStr@CKeyBuf@@QEBAPEAGXZ>
extern __imp_?GetString@CMemDeSerStream@@UEAAPEADXZ:PANYARGS
?GetString@CMemDeSerStream@@UEAAPEADXZ TEXTEQU <__imp_?GetString@CMemDeSerStream@@UEAAPEADXZ>
extern __imp_?GetStringDbRestriction@@YAPEAVCDbRestriction@@PEBGKPEAUIColumnMapper@@K@Z:PANYARGS
?GetStringDbRestriction@@YAPEAVCDbRestriction@@PEBGKPEAUIColumnMapper@@K@Z TEXTEQU <__imp_?GetStringDbRestriction@@YAPEAVCDbRestriction@@PEBGKPEAUIColumnMapper@@K@Z>
extern __imp_?GetStringFromLCID@@YAXKPEAG@Z:PANYARGS
?GetStringFromLCID@@YAXKPEAG@Z TEXTEQU <__imp_?GetStringFromLCID@@YAXKPEAG@Z>
extern __imp_?GetTotalSizeInKB@CPropStoreManager@@QEAAKXZ:PANYARGS
?GetTotalSizeInKB@CPropStoreManager@@QEAAKXZ TEXTEQU <__imp_?GetTotalSizeInKB@CPropStoreManager@@QEAAKXZ>
extern __imp_?GetTotalSizeInKB@CPropertyStore@@QEAAKXZ:PANYARGS
?GetTotalSizeInKB@CPropertyStore@@QEAAKXZ TEXTEQU <__imp_?GetTotalSizeInKB@CPropertyStore@@QEAAKXZ>
extern __imp_?GetULong@CMemDeSerStream@@UEAAKXZ:PANYARGS
?GetULong@CMemDeSerStream@@UEAAKXZ TEXTEQU <__imp_?GetULong@CMemDeSerStream@@UEAAKXZ>
extern __imp_?GetUShort@CMemDeSerStream@@UEAAGXZ:PANYARGS
?GetUShort@CMemDeSerStream@@UEAAGXZ TEXTEQU <__imp_?GetUShort@CMemDeSerStream@@UEAAGXZ>
extern __imp_?GetUserHdrInfo@CIndexTable@@QEAAXAEAIAEAH@Z:PANYARGS
?GetUserHdrInfo@CIndexTable@@QEAAXAEAIAEAH@Z TEXTEQU <__imp_?GetUserHdrInfo@CIndexTable@@QEAAXAEAIAEAH@Z>
extern __imp_?GetVPathAccess@CMetaDataMgr@@QEAAKPEBG@Z:PANYARGS
?GetVPathAccess@CMetaDataMgr@@QEAAKPEBG@Z TEXTEQU <__imp_?GetVPathAccess@CMetaDataMgr@@QEAAKPEBG@Z>
extern __imp_?GetVPathAuthorization@CMetaDataMgr@@QEAAKPEBG@Z:PANYARGS
?GetVPathAuthorization@CMetaDataMgr@@QEAAKPEBG@Z TEXTEQU <__imp_?GetVPathAuthorization@CMetaDataMgr@@QEAAKPEBG@Z>
extern __imp_?GetVPathSSLAccess@CMetaDataMgr@@QEAAKPEBG@Z:PANYARGS
?GetVPathSSLAccess@CMetaDataMgr@@QEAAKPEBG@Z TEXTEQU <__imp_?GetVPathSSLAccess@CMetaDataMgr@@QEAAKPEBG@Z>
extern __imp_?GetVolumeName@CDriveInfo@@QEAAPEBGH@Z:PANYARGS
?GetVolumeName@CDriveInfo@@QEAAPEBGH@Z TEXTEQU <__imp_?GetVolumeName@CDriveInfo@@QEAAPEBGH@Z>
extern __imp_?GetWChar@CMemDeSerStream@@UEAAXPEAGK@Z:PANYARGS
?GetWChar@CMemDeSerStream@@UEAAXPEAGK@Z TEXTEQU <__imp_?GetWChar@CMemDeSerStream@@UEAAXPEAGK@Z>
extern __imp_?GetWString@CMemDeSerStream@@UEAAPEAGXZ:PANYARGS
?GetWString@CMemDeSerStream@@UEAAPEAGXZ TEXTEQU <__imp_?GetWString@CMemDeSerStream@@UEAAPEAGXZ>
extern __imp_?GetWeight@CDbCmdTreeNode@@QEBAJXZ:PANYARGS
?GetWeight@CDbCmdTreeNode@@QEBAJXZ TEXTEQU <__imp_?GetWeight@CDbCmdTreeNode@@QEBAJXZ>
extern __imp_?Grow@CDynStream@@QEAAXAEAVPStorage@@K@Z:PANYARGS
?Grow@CDynStream@@QEAAXAEAVPStorage@@K@Z TEXTEQU <__imp_?Grow@CDynStream@@QEAAXAEAVPStorage@@K@Z>
extern __imp_?GrowBuffer@CVirtualString@@AEAAXK@Z:PANYARGS
?GrowBuffer@CVirtualString@@AEAAXK@Z TEXTEQU <__imp_?GrowBuffer@CVirtualString@@AEAAXK@Z>
extern __imp_?HTMLEscapeW@@YAXPEBGAEAVCVirtualString@@K@Z:PANYARGS
?HTMLEscapeW@@YAXPEBGAEAVCVirtualString@@K@Z TEXTEQU <__imp_?HTMLEscapeW@@YAXPEBGAEAVCVirtualString@@K@Z>
extern __imp_?Impersonate@CImpersonateClient@@AEAAXXZ:PANYARGS
?Impersonate@CImpersonateClient@@AEAAXXZ TEXTEQU <__imp_?Impersonate@CImpersonateClient@@AEAAXXZ>
extern __imp_?Init@CFileMapView@@QEAAXXZ:PANYARGS
?Init@CFileMapView@@QEAAXXZ TEXTEQU <__imp_?Init@CFileMapView@@QEAAXXZ>
extern __imp_?Init@CMmStreamConsecBuf@@QEAAXPEAVPMmStream@@@Z:PANYARGS
?Init@CMmStreamConsecBuf@@QEAAXPEAVPMmStream@@@Z TEXTEQU <__imp_?Init@CMmStreamConsecBuf@@QEAAXPEAVPMmStream@@@Z>
extern __imp_?Init@CPidLookupTable@@QEAAHPEAVPRcovStorageObj@@@Z:PANYARGS
?Init@CPidLookupTable@@QEAAHPEAVPRcovStorageObj@@@Z TEXTEQU <__imp_?Init@CPidLookupTable@@QEAAHPEAVPRcovStorageObj@@@Z>
extern __imp_?Init@CRcovStorageHdr@@QEAAXK@Z:PANYARGS
?Init@CRcovStorageHdr@@QEAAXK@Z TEXTEQU <__imp_?Init@CRcovStorageHdr@@QEAAXK@Z>
extern __imp_?Init@CRegChangeEvent@@QEAAXXZ:PANYARGS
?Init@CRegChangeEvent@@QEAAXXZ TEXTEQU <__imp_?Init@CRegChangeEvent@@QEAAXXZ>
extern __imp_?Init@CSdidLookupTable@@QEAAHPEAVCiStorage@@@Z:PANYARGS
?Init@CSdidLookupTable@@QEAAHPEAVCiStorage@@@Z TEXTEQU <__imp_?Init@CSdidLookupTable@@QEAAHPEAVCiStorage@@@Z>
extern __imp_?InitIterator@CPropertyList@@UEAAXXZ:PANYARGS
?InitIterator@CPropertyList@@UEAAXXZ TEXTEQU <__imp_?InitIterator@CPropertyList@@UEAAXXZ>
extern __imp_?Initialize@CImpersonationTokenCache@@QEAAXPEBGHHHKKK@Z:PANYARGS
?Initialize@CImpersonationTokenCache@@QEAAXPEBGHHHKKK@Z TEXTEQU <__imp_?Initialize@CImpersonationTokenCache@@QEAAXPEBGHHHKKK@Z>
extern __imp_?InitializeForRead@CDynStream@@QEAAXXZ:PANYARGS
?InitializeForRead@CDynStream@@QEAAXXZ TEXTEQU <__imp_?InitializeForRead@CDynStream@@QEAAXXZ>
extern __imp_?InitializeForWrite@CDynStream@@QEAAXK@Z:PANYARGS
?InitializeForWrite@CDynStream@@QEAAXK@Z TEXTEQU <__imp_?InitializeForWrite@CDynStream@@QEAAXK@Z>
extern __imp_?InsertChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z:PANYARGS
?InsertChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z TEXTEQU <__imp_?InsertChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z>
extern __imp_?IsCIEnabled@CMachineAdmin@@QEAAHXZ:PANYARGS
?IsCIEnabled@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?IsCIEnabled@CMachineAdmin@@QEAAHXZ>
extern __imp_?IsCIPaused@CMachineAdmin@@QEAAHXZ:PANYARGS
?IsCIPaused@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?IsCIPaused@CMachineAdmin@@QEAAHXZ>
extern __imp_?IsCIStarted@CMachineAdmin@@QEAAHXZ:PANYARGS
?IsCIStarted@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?IsCIStarted@CMachineAdmin@@QEAAHXZ>
extern __imp_?IsCIStopped@CMachineAdmin@@QEAAHXZ:PANYARGS
?IsCIStopped@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?IsCIStopped@CMachineAdmin@@QEAAHXZ>
extern __imp_?IsCatalogInactive@CCatalogAdmin@@QEAAHXZ:PANYARGS
?IsCatalogInactive@CCatalogAdmin@@QEAAHXZ TEXTEQU <__imp_?IsCatalogInactive@CCatalogAdmin@@QEAAHXZ>
extern __imp_?IsDirectoryWritable@@YAHPEBG@Z:PANYARGS
?IsDirectoryWritable@@YAHPEBG@Z TEXTEQU <__imp_?IsDirectoryWritable@@YAHPEBG@Z>
extern __imp_?IsIISAdminUp@CMetaDataMgr@@SAHAEAH@Z:PANYARGS
?IsIISAdminUp@CMetaDataMgr@@SAHAEAH@Z TEXTEQU <__imp_?IsIISAdminUp@CMetaDataMgr@@SAHAEAH@Z>
extern __imp_?IsImpersonated@CImpersonateSystem@@SAHXZ:PANYARGS
?IsImpersonated@CImpersonateSystem@@SAHXZ TEXTEQU <__imp_?IsImpersonated@CImpersonateSystem@@SAHXZ>
extern __imp_?IsLeaf@CRestriction@@QEBAHXZ:PANYARGS
?IsLeaf@CRestriction@@QEBAHXZ TEXTEQU <__imp_?IsLeaf@CRestriction@@QEBAHXZ>
extern __imp_?IsNullPointerVariant@@YAHPEAUtagPROPVARIANT@@@Z:PANYARGS
?IsNullPointerVariant@@YAHPEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?IsNullPointerVariant@@YAHPEAUtagPROPVARIANT@@@Z>
extern __imp_?IsPaused@CCatalogAdmin@@QEAAHXZ:PANYARGS
?IsPaused@CCatalogAdmin@@QEAAHXZ TEXTEQU <__imp_?IsPaused@CCatalogAdmin@@QEAAHXZ>
extern __imp_?IsRunningAsSystem@CImpersonateSystem@@SAHXZ:PANYARGS
?IsRunningAsSystem@CImpersonateSystem@@SAHXZ TEXTEQU <__imp_?IsRunningAsSystem@CImpersonateSystem@@SAHXZ>
extern __imp_?IsSameDrive@CDriveInfo@@QEAAHPEBG@Z:PANYARGS
?IsSameDrive@CDriveInfo@@QEAAHPEBG@Z TEXTEQU <__imp_?IsSameDrive@CDriveInfo@@QEAAHPEBG@Z>
extern __imp_?IsScopeValid@@YAJPEBGIH@Z:PANYARGS
?IsScopeValid@@YAJPEBGIH@Z TEXTEQU <__imp_?IsScopeValid@@YAJPEBGIH@Z>
extern __imp_?IsStarted@CCatalogAdmin@@QEAAHXZ:PANYARGS
?IsStarted@CCatalogAdmin@@QEAAHXZ TEXTEQU <__imp_?IsStarted@CCatalogAdmin@@QEAAHXZ>
extern __imp_?IsStopped@CCatalogAdmin@@QEAAHXZ:PANYARGS
?IsStopped@CCatalogAdmin@@QEAAHXZ TEXTEQU <__imp_?IsStopped@CCatalogAdmin@@QEAAHXZ>
extern __imp_?IsValid@CAllocStorageVariant@@QEBAHXZ:PANYARGS
?IsValid@CAllocStorageVariant@@QEBAHXZ TEXTEQU <__imp_?IsValid@CAllocStorageVariant@@QEBAHXZ>
extern __imp_?IsValid@CNodeRestriction@@QEBAHXZ:PANYARGS
?IsValid@CNodeRestriction@@QEBAHXZ TEXTEQU <__imp_?IsValid@CNodeRestriction@@QEBAHXZ>
extern __imp_?IsValid@COccRestriction@@QEBAHXZ:PANYARGS
?IsValid@COccRestriction@@QEBAHXZ TEXTEQU <__imp_?IsValid@COccRestriction@@QEBAHXZ>
extern __imp_?IsValid@CRestriction@@QEBAHXZ:PANYARGS
?IsValid@CRestriction@@QEBAHXZ TEXTEQU <__imp_?IsValid@CRestriction@@QEBAHXZ>
extern __imp_?IsWaitingForDocument@CFilterDaemon@@QEAAHXZ:PANYARGS
?IsWaitingForDocument@CFilterDaemon@@QEAAHXZ TEXTEQU <__imp_?IsWaitingForDocument@CFilterDaemon@@QEAAHXZ>
extern __imp_?IsWriteProtected@CDriveInfo@@QEAAHXZ:PANYARGS
?IsWriteProtected@CDriveInfo@@QEAAHXZ TEXTEQU <__imp_?IsWriteProtected@CDriveInfo@@QEAAHXZ>
extern __imp_?Load@CLocalGlobalPropertyList@@QEAAXQEBG@Z:PANYARGS
?Load@CLocalGlobalPropertyList@@QEAAXQEBG@Z TEXTEQU <__imp_?Load@CLocalGlobalPropertyList@@QEAAXQEBG@Z>
extern __imp_?LocaleToCodepage@@YAKK@Z:PANYARGS
?LocaleToCodepage@@YAKK@Z TEXTEQU <__imp_?LocaleToCodepage@@YAKK@Z>
extern __imp_?LokNewWorkId@CPropertyStore@@AEAAKKHH@Z:PANYARGS
?LokNewWorkId@CPropertyStore@@AEAAKKHH@Z TEXTEQU <__imp_?LokNewWorkId@CPropertyStore@@AEAAKKHH@Z>
extern __imp_?LokUpdate@CCatStateInfo@@QEAAHXZ:PANYARGS
?LokUpdate@CCatStateInfo@@QEAAHXZ TEXTEQU <__imp_?LokUpdate@CCatStateInfo@@QEAAHXZ>
extern __imp_?LongInit@CPropStoreManager@@QEAAXAEAHAEAKP6AXKHPEBX@Z2@Z:PANYARGS
?LongInit@CPropStoreManager@@QEAAXAEAHAEAKP6AXKHPEBX@Z2@Z TEXTEQU <__imp_?LongInit@CPropStoreManager@@QEAAXAEAHAEAKP6AXKHPEBX@Z2@Z>
extern __imp_?Lookup@CPropStoreInfo@@AEAAIK@Z:PANYARGS
?Lookup@CPropStoreInfo@@AEAAIK@Z TEXTEQU <__imp_?Lookup@CPropStoreInfo@@AEAAIK@Z>
extern __imp_?LookupSDID@CSdidLookupTable@@QEAAKPEAXK@Z:PANYARGS
?LookupSDID@CSdidLookupTable@@QEAAKPEAXK@Z TEXTEQU <__imp_?LookupSDID@CSdidLookupTable@@QEAAKPEAXK@Z>
extern __imp_?MakeBackupCopy@CPhysStorage@@QEAAXAEAV1@AEAVPSaveProgressTracker@@@Z:PANYARGS
?MakeBackupCopy@CPhysStorage@@QEAAXAEAV1@AEAVPSaveProgressTracker@@@Z TEXTEQU <__imp_?MakeBackupCopy@CPhysStorage@@QEAAXAEAV1@AEAVPSaveProgressTracker@@@Z>
extern __imp_?MakeBackupCopy@CPidLookupTable@@QEAAXAEAVPRcovStorageObj@@AEAVPSaveProgressTracker@@@Z:PANYARGS
?MakeBackupCopy@CPidLookupTable@@QEAAXAEAVPRcovStorageObj@@AEAVPSaveProgressTracker@@@Z TEXTEQU <__imp_?MakeBackupCopy@CPidLookupTable@@QEAAXAEAVPRcovStorageObj@@AEAVPSaveProgressTracker@@@Z>
extern __imp_?MakeBackupCopy@CPropStoreManager@@QEAAXPEAUIProgressNotify@@AEAHAEAVCiStorage@@PEAUICiEnumWorkids@@PEAPEAUIEnumString@@@Z:PANYARGS
?MakeBackupCopy@CPropStoreManager@@QEAAXPEAUIProgressNotify@@AEAHAEAVCiStorage@@PEAUICiEnumWorkids@@PEAPEAUIEnumString@@@Z TEXTEQU <__imp_?MakeBackupCopy@CPropStoreManager@@QEAAXPEAUIProgressNotify@@AEAHAEAVCiStorage@@PEAUICiEnumWorkids@@PEAPEAUIEnumString@@@Z>
extern __imp_?MakeICommand@@YAJPEAPEAUIUnknown@@PEBG1PEAU1@@Z:PANYARGS
?MakeICommand@@YAJPEAPEAUIUnknown@@PEBG1PEAU1@@Z TEXTEQU <__imp_?MakeICommand@@YAJPEAPEAUIUnknown@@PEBG1PEAU1@@Z>
extern __imp_?MakeISearch@@YAJPEAPEAUISearchQueryHits@@PEAVCDbRestriction@@PEBG@Z:PANYARGS
?MakeISearch@@YAJPEAPEAUISearchQueryHits@@PEAVCDbRestriction@@PEBG@Z TEXTEQU <__imp_?MakeISearch@@YAJPEAPEAUISearchQueryHits@@PEAVCDbRestriction@@PEBG@Z>
extern __imp_?MakeLocalICommand@@YAJPEAPEAUIUnknown@@PEAUICiCDocStore@@PEAU1@@Z:PANYARGS
?MakeLocalICommand@@YAJPEAPEAUIUnknown@@PEAUICiCDocStore@@PEAU1@@Z TEXTEQU <__imp_?MakeLocalICommand@@YAJPEAPEAUIUnknown@@PEAUICiCDocStore@@PEAU1@@Z>
extern __imp_?MakeMetadataICommand@@YAJPEAPEAUIUnknown@@W4CiMetaData@@PEBG2PEAU1@@Z:PANYARGS
?MakeMetadataICommand@@YAJPEAPEAUIUnknown@@W4CiMetaData@@PEBG2PEAU1@@Z TEXTEQU <__imp_?MakeMetadataICommand@@YAJPEAPEAUIUnknown@@W4CiMetaData@@PEBG2PEAU1@@Z>
extern __imp_?MakePath@CFullPath@@QEAAXPEBG@Z:PANYARGS
?MakePath@CFullPath@@QEAAXPEBG@Z TEXTEQU <__imp_?MakePath@CFullPath@@QEAAXPEBG@Z>
extern __imp_?MakePath@CFullPath@@QEAAXPEBGI@Z:PANYARGS
?MakePath@CFullPath@@QEAAXPEBGI@Z TEXTEQU <__imp_?MakePath@CFullPath@@QEAAXPEBGI@Z>
extern __imp_?MakePrivileged@CImpersonateSystem@@AEAAXXZ:PANYARGS
?MakePrivileged@CImpersonateSystem@@AEAAXXZ TEXTEQU <__imp_?MakePrivileged@CImpersonateSystem@@AEAAXXZ>
extern __imp_?Map@CMmStreamConsecBuf@@QEAAXK@Z:PANYARGS
?Map@CMmStreamConsecBuf@@QEAAXK@Z TEXTEQU <__imp_?Map@CMmStreamConsecBuf@@QEAAXK@Z>
extern __imp_?MarkDirty@CDynStream@@QEAAHXZ:PANYARGS
?MarkDirty@CDynStream@@QEAAHXZ TEXTEQU <__imp_?MarkDirty@CDynStream@@QEAAHXZ>
extern __imp_?Marshall@CBaseStorageVariant@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CBaseStorageVariant@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CBaseStorageVariant@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CContentRestriction@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CContentRestriction@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CContentRestriction@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CDbCmdTreeNode@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CDbCmdTreeNode@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CDbCmdTreeNode@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CFullPropSpec@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CFullPropSpec@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CFullPropSpec@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CNatLanguageRestriction@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CNatLanguageRestriction@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CNatLanguageRestriction@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CNodeRestriction@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CNodeRestriction@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CNodeRestriction@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CNotRestriction@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CNotRestriction@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CNotRestriction@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CPropNameArray@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CPropNameArray@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CPropNameArray@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CPropertyRestriction@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CPropertyRestriction@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CPropertyRestriction@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CRestriction@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CRestriction@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CRestriction@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Marshall@CVectorRestriction@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Marshall@CVectorRestriction@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Marshall@CVectorRestriction@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?MinPageInUse@CBufferCache@@QEAAHAEAK@Z:PANYARGS
?MinPageInUse@CBufferCache@@QEAAHAEAK@Z TEXTEQU <__imp_?MinPageInUse@CBufferCache@@QEAAHAEAK@Z>
extern __imp_?MinPageInUse@CPhysStorage@@QEAAHAEAK@Z:PANYARGS
?MinPageInUse@CPhysStorage@@QEAAHAEAK@Z TEXTEQU <__imp_?MinPageInUse@CPhysStorage@@QEAAHAEAK@Z>
extern __imp_?MultiByteToXArrayWideChar@@YAKPEBEKIAEAV?$XArray@G@@@Z:PANYARGS
?MultiByteToXArrayWideChar@@YAKPEBEKIAEAV?$XArray@G@@@Z TEXTEQU <__imp_?MultiByteToXArrayWideChar@@YAKPEBEKIAEAV?$XArray@G@@@Z>
extern __imp_?My_wcstoui64@@YA_KPEBGPEAPEAGH@Z:PANYARGS
?My_wcstoui64@@YA_KPEBGPEAPEAGH@Z TEXTEQU <__imp_?My_wcstoui64@@YA_KPEBGPEAPEAGH@Z>
extern __imp_?NameToReal@CPidRemapper@@QEAAKPEBVCFullPropSpec@@@Z:PANYARGS
?NameToReal@CPidRemapper@@QEAAKPEBVCFullPropSpec@@@Z TEXTEQU <__imp_?NameToReal@CPidRemapper@@QEAAKPEBVCFullPropSpec@@@Z>
extern __imp_?NewStemmer@CCiOle@@SAPEAUIStemmer@@AEBU_GUID@@@Z:PANYARGS
?NewStemmer@CCiOle@@SAPEAUIStemmer@@AEBU_GUID@@@Z TEXTEQU <__imp_?NewStemmer@CCiOle@@SAPEAUIStemmer@@AEBU_GUID@@@Z>
extern __imp_?NewWordBreaker@CCiOle@@SAPEAUIWordBreaker@@AEBU_GUID@@@Z:PANYARGS
?NewWordBreaker@CCiOle@@SAPEAUIWordBreaker@@AEBU_GUID@@@Z TEXTEQU <__imp_?NewWordBreaker@CCiOle@@SAPEAUIWordBreaker@@AEBU_GUID@@@Z>
extern __imp_?Next@CCatalogEnum@@QEAAHXZ:PANYARGS
?Next@CCatalogEnum@@QEAAHXZ TEXTEQU <__imp_?Next@CCatalogEnum@@QEAAHXZ>
extern __imp_?Next@CEnumString@@UEAAJKPEAPEAGPEAK@Z:PANYARGS
?Next@CEnumString@@UEAAJKPEAPEAGPEAK@Z TEXTEQU <__imp_?Next@CEnumString@@UEAAJKPEAPEAGPEAK@Z>
extern __imp_?Next@CEnumWorkid@@UEAAJKPEAK0@Z:PANYARGS
?Next@CEnumWorkid@@UEAAJKPEAK0@Z TEXTEQU <__imp_?Next@CEnumWorkid@@UEAAJKPEAK0@Z>
extern __imp_?Next@CPropertyList@@UEAAPEBVCPropEntry@@XZ:PANYARGS
?Next@CPropertyList@@UEAAPEBVCPropEntry@@XZ TEXTEQU <__imp_?Next@CPropertyList@@UEAAPEBVCPropEntry@@XZ>
extern __imp_?Next@CScopeEnum@@QEAAHXZ:PANYARGS
?Next@CScopeEnum@@QEAAHXZ TEXTEQU <__imp_?Next@CScopeEnum@@QEAAHXZ>
extern __imp_?NextWorkId@CPropertyStoreWids@@QEAAKXZ:PANYARGS
?NextWorkId@CPropertyStoreWids@@QEAAKXZ TEXTEQU <__imp_?NextWorkId@CPropertyStoreWids@@QEAAKXZ>
extern __imp_?NumberOfColumns@CCatState@@QEBAIXZ:PANYARGS
?NumberOfColumns@CCatState@@QEBAIXZ TEXTEQU <__imp_?NumberOfColumns@CCatState@@QEBAIXZ>
extern __imp_?NumberOfSortProps@CCatState@@QEBAIXZ:PANYARGS
?NumberOfSortProps@CCatState@@QEBAIXZ TEXTEQU <__imp_?NumberOfSortProps@CCatState@@QEBAIXZ>
extern __imp_?Open@CMmStream@@QEAAXPEBGKKKKH@Z:PANYARGS
?Open@CMmStream@@QEAAXPEBGKKKKH@Z TEXTEQU <__imp_?Open@CMmStream@@QEAAXPEBGKKKKH@Z>
extern __imp_?Open@COLEPropManager@@QEAAHAEBVCFunnyPath@@@Z:PANYARGS
?Open@COLEPropManager@@QEAAHAEBVCFunnyPath@@@Z TEXTEQU <__imp_?Open@COLEPropManager@@QEAAHAEBVCFunnyPath@@@Z>
extern __imp_?OpenExclusive@CMmStream@@QEAAXPEAGH@Z:PANYARGS
?OpenExclusive@CMmStream@@QEAAXPEAGH@Z TEXTEQU <__imp_?OpenExclusive@CMmStream@@QEAAXPEAGH@Z>
extern __imp_?OpenFileFromPath@@YAPEAU_iobuf@@PEBG@Z:PANYARGS
?OpenFileFromPath@@YAPEAU_iobuf@@PEBG@Z TEXTEQU <__imp_?OpenFileFromPath@@YAPEAU_iobuf@@PEBG@Z>
extern __imp_?OpenRecord@CPropStoreManager@@QEAAPEAVCCompositePropRecord@@KPEAE@Z:PANYARGS
?OpenRecord@CPropStoreManager@@QEAAPEAVCCompositePropRecord@@KPEAE@Z TEXTEQU <__imp_?OpenRecord@CPropStoreManager@@QEAAPEAVCCompositePropRecord@@KPEAE@Z>
extern __imp_?OpenRecordForWrites@CPropStoreManager@@QEAAPEAVCCompositePropRecordForWrites@@KPEAE@Z:PANYARGS
?OpenRecordForWrites@CPropStoreManager@@QEAAPEAVCCompositePropRecordForWrites@@KPEAE@Z TEXTEQU <__imp_?OpenRecordForWrites@CPropStoreManager@@QEAAPEAVCCompositePropRecordForWrites@@KPEAE@Z>
extern __imp_?ParseCatalogURL@@YAJPEBGAEAV?$XPtrST@G@@1@Z:PANYARGS
?ParseCatalogURL@@YAJPEBGAEAV?$XPtrST@G@@1@Z TEXTEQU <__imp_?ParseCatalogURL@@YAJPEBGAEAV?$XPtrST@G@@1@Z>
extern __imp_?ParseExpression@CParseCommandTree@@QEAAPEAVCRestriction@@PEAVCDbCmdTreeNode@@@Z:PANYARGS
?ParseExpression@CParseCommandTree@@QEAAPEAVCRestriction@@PEAVCDbCmdTreeNode@@@Z TEXTEQU <__imp_?ParseExpression@CParseCommandTree@@QEAAPEAVCRestriction@@PEAVCDbCmdTreeNode@@@Z>
extern __imp_?ParseOneLine@CPropertyList@@SAXAEAVCQueryScanner@@HAEAV?$XPtr@VCPropEntry@@@@@Z:PANYARGS
?ParseOneLine@CPropertyList@@SAXAEAVCQueryScanner@@HAEAV?$XPtr@VCPropEntry@@@@@Z TEXTEQU <__imp_?ParseOneLine@CPropertyList@@SAXAEAVCQueryScanner@@HAEAV?$XPtr@VCPropEntry@@@@@Z>
extern __imp_?ParseQueryPhrase@CQueryParser@@QEAAPEAVCDbRestriction@@XZ:PANYARGS
?ParseQueryPhrase@CQueryParser@@QEAAPEAVCDbRestriction@@XZ TEXTEQU <__imp_?ParseQueryPhrase@CQueryParser@@QEAAPEAVCDbRestriction@@XZ>
extern __imp_?ParseStringColumns@@YAPEAVCDbColumns@@PEBGPEAUIColumnMapper@@KPEAVPVariableSet@@PEAV?$CDynArray@G@@@Z:PANYARGS
?ParseStringColumns@@YAPEAVCDbColumns@@PEBGPEAUIColumnMapper@@KPEAVPVariableSet@@PEAV?$CDynArray@G@@@Z TEXTEQU <__imp_?ParseStringColumns@@YAPEAVCDbColumns@@PEBGPEAUIColumnMapper@@KPEAVPVariableSet@@PEAV?$CDynArray@G@@@Z>
extern __imp_?Pause@CCatalogAdmin@@QEAAHXZ:PANYARGS
?Pause@CCatalogAdmin@@QEAAHXZ TEXTEQU <__imp_?Pause@CCatalogAdmin@@QEAAHXZ>
extern __imp_?PauseCI@CMachineAdmin@@QEAAHXZ:PANYARGS
?PauseCI@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?PauseCI@CMachineAdmin@@QEAAHXZ>
extern __imp_?PeekULong@CMemDeSerStream@@UEAAKXZ:PANYARGS
?PeekULong@CMemDeSerStream@@UEAAKXZ TEXTEQU <__imp_?PeekULong@CMemDeSerStream@@UEAAKXZ>
extern __imp_?PidToRealPid@CPidMapper@@QEAAKK@Z:PANYARGS
?PidToRealPid@CPidMapper@@QEAAKK@Z TEXTEQU <__imp_?PidToRealPid@CPidMapper@@QEAAKK@Z>
extern __imp_?PropertyToPropId@CStandardPropMapper@@QEAAKAEBVCFullPropSpec@@H@Z:PANYARGS
?PropertyToPropId@CStandardPropMapper@@QEAAKAEBVCFullPropSpec@@H@Z TEXTEQU <__imp_?PropertyToPropId@CStandardPropMapper@@QEAAKAEBVCFullPropSpec@@H@Z>
extern __imp_?PropertyToPropid@CFwPropertyMapper@@UEAAJPEBUtagFULLPROPSPEC@@HPEAK@Z:PANYARGS
?PropertyToPropid@CFwPropertyMapper@@UEAAJPEBUtagFULLPROPSPEC@@HPEAK@Z TEXTEQU <__imp_?PropertyToPropid@CFwPropertyMapper@@UEAAJPEBUtagFULLPROPSPEC@@HPEAK@Z>
extern __imp_?PutMaxValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z:PANYARGS
?PutMaxValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z TEXTEQU <__imp_?PutMaxValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z>
extern __imp_?PutMinValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z:PANYARGS
?PutMinValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z TEXTEQU <__imp_?PutMinValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z>
extern __imp_?PutValue@CValueNormalizer@@QEAAXKAEAKAEBVCStorageVariant@@@Z:PANYARGS
?PutValue@CValueNormalizer@@QEAAXKAEAKAEBVCStorageVariant@@@Z TEXTEQU <__imp_?PutValue@CValueNormalizer@@QEAAXKAEAKAEBVCStorageVariant@@@Z>
extern __imp_?PutWString@@YAXAEAVPSerStream@@PEBG@Z:PANYARGS
?PutWString@@YAXAEAVPSerStream@@PEBG@Z TEXTEQU <__imp_?PutWString@@YAXAEAVPSerStream@@PEBG@Z>
extern __imp_?Query@CQueryParser@@AEAAPEAVCDbRestriction@@PEAVCDbNodeRestriction@@@Z:PANYARGS
?Query@CQueryParser@@AEAAPEAVCDbRestriction@@PEAVCDbNodeRestriction@@@Z TEXTEQU <__imp_?Query@CQueryParser@@AEAAPEAVCDbRestriction@@PEAVCDbNodeRestriction@@@Z>
extern __imp_?QueryCatalogAdmin@CCatalogEnum@@QEAAPEAVCCatalogAdmin@@XZ:PANYARGS
?QueryCatalogAdmin@CCatalogEnum@@QEAAPEAVCCatalogAdmin@@XZ TEXTEQU <__imp_?QueryCatalogAdmin@CCatalogEnum@@QEAAPEAVCCatalogAdmin@@XZ>
extern __imp_?QueryCatalogAdmin@CMachineAdmin@@QEAAPEAVCCatalogAdmin@@PEBG@Z:PANYARGS
?QueryCatalogAdmin@CMachineAdmin@@QEAAPEAVCCatalogAdmin@@PEBG@Z TEXTEQU <__imp_?QueryCatalogAdmin@CMachineAdmin@@QEAAPEAVCCatalogAdmin@@PEBG@Z>
extern __imp_?QueryCatalogEnum@CMachineAdmin@@QEAAPEAVCCatalogEnum@@XZ:PANYARGS
?QueryCatalogEnum@CMachineAdmin@@QEAAPEAVCCatalogEnum@@XZ TEXTEQU <__imp_?QueryCatalogEnum@CMachineAdmin@@QEAAPEAVCCatalogEnum@@XZ>
extern __imp_?QueryInterface@CDbProperties@@UEAAJAEBU_GUID@@PEAPEAX@Z:PANYARGS
?QueryInterface@CDbProperties@@UEAAJAEBU_GUID@@PEAPEAX@Z TEXTEQU <__imp_?QueryInterface@CDbProperties@@UEAAJAEBU_GUID@@PEAPEAX@Z>
extern __imp_?QueryInterface@CEmptyPropertyList@@UEAAJAEBU_GUID@@PEAPEAX@Z:PANYARGS
?QueryInterface@CEmptyPropertyList@@UEAAJAEBU_GUID@@PEAPEAX@Z TEXTEQU <__imp_?QueryInterface@CEmptyPropertyList@@UEAAJAEBU_GUID@@PEAPEAX@Z>
extern __imp_?QueryInterface@CEnumString@@UEAAJAEBU_GUID@@PEAPEAX@Z:PANYARGS
?QueryInterface@CEnumString@@UEAAJAEBU_GUID@@PEAPEAX@Z TEXTEQU <__imp_?QueryInterface@CEnumString@@UEAAJAEBU_GUID@@PEAPEAX@Z>
extern __imp_?QueryInterface@CEnumWorkid@@UEAAJAEBU_GUID@@PEAPEAX@Z:PANYARGS
?QueryInterface@CEnumWorkid@@UEAAJAEBU_GUID@@PEAPEAX@Z TEXTEQU <__imp_?QueryInterface@CEnumWorkid@@UEAAJAEBU_GUID@@PEAPEAX@Z>
extern __imp_?QueryInterface@CFwPropertyMapper@@UEAAJAEBU_GUID@@PEAPEAX@Z:PANYARGS
?QueryInterface@CFwPropertyMapper@@UEAAJAEBU_GUID@@PEAPEAX@Z TEXTEQU <__imp_?QueryInterface@CFwPropertyMapper@@UEAAJAEBU_GUID@@PEAPEAX@Z>
extern __imp_?QueryInterface@CQueryUnknown@@UEAAJAEBU_GUID@@PEAPEAX@Z:PANYARGS
?QueryInterface@CQueryUnknown@@UEAAJAEBU_GUID@@PEAPEAX@Z TEXTEQU <__imp_?QueryInterface@CQueryUnknown@@UEAAJAEBU_GUID@@PEAPEAX@Z>
extern __imp_?QueryPidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PANYARGS
?QueryPidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z TEXTEQU <__imp_?QueryPidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>
extern __imp_?QueryScopeAdmin@CCatalogAdmin@@QEAAPEAVCScopeAdmin@@PEBG@Z:PANYARGS
?QueryScopeAdmin@CCatalogAdmin@@QEAAPEAVCScopeAdmin@@PEBG@Z TEXTEQU <__imp_?QueryScopeAdmin@CCatalogAdmin@@QEAAPEAVCScopeAdmin@@PEBG@Z>
extern __imp_?QueryScopeAdmin@CScopeEnum@@QEAAPEAVCScopeAdmin@@XZ:PANYARGS
?QueryScopeAdmin@CScopeEnum@@QEAAPEAVCScopeAdmin@@XZ TEXTEQU <__imp_?QueryScopeAdmin@CScopeEnum@@QEAAPEAVCScopeAdmin@@XZ>
extern __imp_?QueryScopeEnum@CCatalogAdmin@@QEAAPEAVCScopeEnum@@XZ:PANYARGS
?QueryScopeEnum@CCatalogAdmin@@QEAAPEAVCScopeEnum@@XZ TEXTEQU <__imp_?QueryScopeEnum@CCatalogAdmin@@QEAAPEAVCScopeEnum@@XZ>
extern __imp_?QueryScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PANYARGS
?QueryScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z TEXTEQU <__imp_?QueryScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>
extern __imp_?QuerySdidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PANYARGS
?QuerySdidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z TEXTEQU <__imp_?QuerySdidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>
extern __imp_?QueryVirtualScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PANYARGS
?QueryVirtualScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z TEXTEQU <__imp_?QueryVirtualScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>
extern __imp_?ReBuild@CPidRemapper@@QEAAXAEBVCPidMapper@@@Z:PANYARGS
?ReBuild@CPidRemapper@@QEAAXAEBVCPidMapper@@@Z TEXTEQU <__imp_?ReBuild@CPidRemapper@@QEAAXAEBVCPidMapper@@@Z>
extern __imp_?ReInit@CQueryUnknown@@QEAAXKPEAPEAVCRowset@@@Z:PANYARGS
?ReInit@CQueryUnknown@@QEAAXKPEAPEAVCRowset@@@Z TEXTEQU <__imp_?ReInit@CQueryUnknown@@QEAAXKPEAPEAVCRowset@@@Z>
extern __imp_?ReInitializeIISScopes@CImpersonationTokenCache@@QEAAXXZ:PANYARGS
?ReInitializeIISScopes@CImpersonationTokenCache@@QEAAXXZ TEXTEQU <__imp_?ReInitializeIISScopes@CImpersonationTokenCache@@QEAAXXZ>
extern __imp_?ReOpenStream@CPhysIndex@@EEAAXXZ:PANYARGS
?ReOpenStream@CPhysIndex@@EEAAXXZ TEXTEQU <__imp_?ReOpenStream@CPhysIndex@@EEAAXXZ>
extern __imp_?Read@CDynStream@@QEAAKPEAXK@Z:PANYARGS
?Read@CDynStream@@QEAAKPEAXK@Z TEXTEQU <__imp_?Read@CDynStream@@QEAAKPEAXK@Z>
extern __imp_?Read@CRcovStrmTrans@@QEAAKPEAXK@Z:PANYARGS
?Read@CRcovStrmTrans@@QEAAKPEAXK@Z TEXTEQU <__imp_?Read@CRcovStrmTrans@@QEAAKPEAXK@Z>
extern __imp_?Read@CRegAccess@@QEAAKPEBGK@Z:PANYARGS
?Read@CRegAccess@@QEAAKPEBGK@Z TEXTEQU <__imp_?Read@CRegAccess@@QEAAKPEBGK@Z>
extern __imp_?Read@CRegAccess@@QEAAPEAGPEBG0@Z:PANYARGS
?Read@CRegAccess@@QEAAPEAGPEBG0@Z TEXTEQU <__imp_?Read@CRegAccess@@QEAAPEAGPEBG0@Z>
extern __imp_?ReadPrimaryProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z:PANYARGS
?ReadPrimaryProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?ReadPrimaryProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z>
extern __imp_?ReadProperty@COLEPropManager@@QEAAHAEBVCFullPropSpec@@AEAUtagPROPVARIANT@@@Z:PANYARGS
?ReadProperty@COLEPropManager@@QEAAHAEBVCFullPropSpec@@AEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?ReadProperty@COLEPropManager@@QEAAHAEBVCFullPropSpec@@AEAUtagPROPVARIANT@@@Z>
extern __imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@@Z:PANYARGS
?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@@Z>
extern __imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@PEAEPEAI@Z:PANYARGS
?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@PEAEPEAI@Z TEXTEQU <__imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@PEAEPEAI@Z>
extern __imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KPEAUtagPROPVARIANT@@PEAI@Z:PANYARGS
?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KPEAUtagPROPVARIANT@@PEAI@Z TEXTEQU <__imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KPEAUtagPROPVARIANT@@PEAI@Z>
extern __imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z:PANYARGS
?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z>
extern __imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@PEAEPEAI@Z:PANYARGS
?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@PEAEPEAI@Z TEXTEQU <__imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@PEAEPEAI@Z>
extern __imp_?ReadProperty@CPropStoreManager@@QEAAHKKPEAUtagPROPVARIANT@@PEAI@Z:PANYARGS
?ReadProperty@CPropStoreManager@@QEAAHKKPEAUtagPROPVARIANT@@PEAI@Z TEXTEQU <__imp_?ReadProperty@CPropStoreManager@@QEAAHKKPEAUtagPROPVARIANT@@PEAI@Z>
extern __imp_?ReadProperty@CPropertyStore@@QEAAHAEAVCPropRecordNoLock@@KPEAUtagPROPVARIANT@@PEAI@Z:PANYARGS
?ReadProperty@CPropertyStore@@QEAAHAEAVCPropRecordNoLock@@KPEAUtagPROPVARIANT@@PEAI@Z TEXTEQU <__imp_?ReadProperty@CPropertyStore@@QEAAHAEAVCPropRecordNoLock@@KPEAUtagPROPVARIANT@@PEAI@Z>
extern __imp_?ReadProperty@CPropertyStore@@QEAAHKKAEAUtagPROPVARIANT@@@Z:PANYARGS
?ReadProperty@CPropertyStore@@QEAAHKKAEAUtagPROPVARIANT@@@Z TEXTEQU <__imp_?ReadProperty@CPropertyStore@@QEAAHKKAEAUtagPROPVARIANT@@@Z>
extern __imp_?Recognize@CDFA@@QEAAEPEBG@Z:PANYARGS
?Recognize@CDFA@@QEAAEPEBG@Z TEXTEQU <__imp_?Recognize@CDFA@@QEAAEPEBG@Z>
extern __imp_?Refresh@CCiRegParams@@QEAAXPEAUICiAdminParams@@H@Z:PANYARGS
?Refresh@CCiRegParams@@QEAAXPEAUICiAdminParams@@H@Z TEXTEQU <__imp_?Refresh@CCiRegParams@@QEAAXPEAUICiAdminParams@@H@Z>
extern __imp_?Refresh@CDefColumnRegEntry@@QEAAXH@Z:PANYARGS
?Refresh@CDefColumnRegEntry@@QEAAXH@Z TEXTEQU <__imp_?Refresh@CDefColumnRegEntry@@QEAAXH@Z>
extern __imp_?RefreshParams@CWorkQueue@@QEAAXKK@Z:PANYARGS
?RefreshParams@CWorkQueue@@QEAAXKK@Z TEXTEQU <__imp_?RefreshParams@CWorkQueue@@QEAAXKK@Z>
extern __imp_?Release@CDbProperties@@UEAAKXZ:PANYARGS
?Release@CDbProperties@@UEAAKXZ TEXTEQU <__imp_?Release@CDbProperties@@UEAAKXZ>
extern __imp_?Release@CEmptyPropertyList@@UEAAKXZ:PANYARGS
?Release@CEmptyPropertyList@@UEAAKXZ TEXTEQU <__imp_?Release@CEmptyPropertyList@@UEAAKXZ>
extern __imp_?Release@CEnumString@@UEAAKXZ:PANYARGS
?Release@CEnumString@@UEAAKXZ TEXTEQU <__imp_?Release@CEnumString@@UEAAKXZ>
extern __imp_?Release@CEnumWorkid@@UEAAKXZ:PANYARGS
?Release@CEnumWorkid@@UEAAKXZ TEXTEQU <__imp_?Release@CEnumWorkid@@UEAAKXZ>
extern __imp_?Release@CFwPropertyMapper@@UEAAKXZ:PANYARGS
?Release@CFwPropertyMapper@@UEAAKXZ TEXTEQU <__imp_?Release@CFwPropertyMapper@@UEAAKXZ>
extern __imp_?Release@CImpersonateRemoteAccess@@QEAAXXZ:PANYARGS
?Release@CImpersonateRemoteAccess@@QEAAXXZ TEXTEQU <__imp_?Release@CImpersonateRemoteAccess@@QEAAXXZ>
extern __imp_?Release@CQueryUnknown@@UEAAKXZ:PANYARGS
?Release@CQueryUnknown@@UEAAKXZ TEXTEQU <__imp_?Release@CQueryUnknown@@UEAAKXZ>
extern __imp_?Release@CWorkQueue@@QEAAXPEAVCWorkThread@@@Z:PANYARGS
?Release@CWorkQueue@@QEAAXPEAVCWorkThread@@@Z TEXTEQU <__imp_?Release@CWorkQueue@@QEAAXPEAVCWorkThread@@@Z>
extern __imp_?ReleaseRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z:PANYARGS
?ReleaseRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z TEXTEQU <__imp_?ReleaseRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z>
extern __imp_?ReleaseWorkThreads@CWorkQueue@@QEAAXXZ:PANYARGS
?ReleaseWorkThreads@CWorkQueue@@QEAAXXZ TEXTEQU <__imp_?ReleaseWorkThreads@CWorkQueue@@QEAAXXZ>
extern __imp_?Remove@CColumns@@QEAAXI@Z:PANYARGS
?Remove@CColumns@@QEAAXI@Z TEXTEQU <__imp_?Remove@CColumns@@QEAAXI@Z>
extern __imp_?Remove@CDbSortSet@@QEAAXI@Z:PANYARGS
?Remove@CDbSortSet@@QEAAXI@Z TEXTEQU <__imp_?Remove@CDbSortSet@@QEAAXI@Z>
extern __imp_?Remove@CSort@@QEAAXI@Z:PANYARGS
?Remove@CSort@@QEAAXI@Z TEXTEQU <__imp_?Remove@CSort@@QEAAXI@Z>
extern __imp_?Remove@CWorkQueue@@AEAAXAEAVCWorkThread@@@Z:PANYARGS
?Remove@CWorkQueue@@AEAAXAEAVCWorkThread@@@Z TEXTEQU <__imp_?Remove@CWorkQueue@@AEAAXAEAVCWorkThread@@@Z>
extern __imp_?Remove@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z:PANYARGS
?Remove@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z TEXTEQU <__imp_?Remove@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z>
extern __imp_?RemoveCatalog@CMachineAdmin@@QEAAXPEBGH@Z:PANYARGS
?RemoveCatalog@CMachineAdmin@@QEAAXPEBGH@Z TEXTEQU <__imp_?RemoveCatalog@CMachineAdmin@@QEAAXPEBGH@Z>
extern __imp_?RemoveCatalogFiles@CMachineAdmin@@QEAAXPEBG@Z:PANYARGS
?RemoveCatalogFiles@CMachineAdmin@@QEAAXPEBG@Z TEXTEQU <__imp_?RemoveCatalogFiles@CMachineAdmin@@QEAAXPEBG@Z>
extern __imp_?RemoveChild@CNodeRestriction@@QEAAPEAVCRestriction@@I@Z:PANYARGS
?RemoveChild@CNodeRestriction@@QEAAPEAVCRestriction@@I@Z TEXTEQU <__imp_?RemoveChild@CNodeRestriction@@QEAAPEAVCRestriction@@I@Z>
extern __imp_?RemoveFirstChild@CDbCmdTreeNode@@IEAAPEAV1@XZ:PANYARGS
?RemoveFirstChild@CDbCmdTreeNode@@IEAAPEAV1@XZ TEXTEQU <__imp_?RemoveFirstChild@CDbCmdTreeNode@@IEAAPEAV1@XZ>
extern __imp_?RemoveScope@CCatalogAdmin@@QEAAXPEBG@Z:PANYARGS
?RemoveScope@CCatalogAdmin@@QEAAXPEBG@Z TEXTEQU <__imp_?RemoveScope@CCatalogAdmin@@QEAAXPEBG@Z>
extern __imp_?Reopen@CPhysStorage@@QEAAXH@Z:PANYARGS
?Reopen@CPhysStorage@@QEAAXH@Z TEXTEQU <__imp_?Reopen@CPhysStorage@@QEAAXH@Z>
extern __imp_?ReportEventW@CEventLog@@QEAAXAEAVCEventItem@@@Z:PANYARGS
?ReportEventW@CEventLog@@QEAAXAEAVCEventItem@@@Z TEXTEQU <__imp_?ReportEventW@CEventLog@@QEAAXAEAVCEventItem@@@Z>
extern __imp_?ReportEventW@CFwEventItem@@QEAAXAEAUICiCAdviseStatus@@@Z:PANYARGS
?ReportEventW@CFwEventItem@@QEAAXAEAUICiCAdviseStatus@@@Z TEXTEQU <__imp_?ReportEventW@CFwEventItem@@QEAAXAEAUICiCAdviseStatus@@@Z>
extern __imp_?RequiresFlush@CPhysStorage@@QEAAHK@Z:PANYARGS
?RequiresFlush@CPhysStorage@@QEAAHK@Z TEXTEQU <__imp_?RequiresFlush@CPhysStorage@@QEAAHK@Z>
extern __imp_?Reset@CRegChangeEvent@@QEAAXXZ:PANYARGS
?Reset@CRegChangeEvent@@QEAAXXZ TEXTEQU <__imp_?Reset@CRegChangeEvent@@QEAAXXZ>
extern __imp_?ResetBuffer@CQueryScanner@@QEAAXPEBG@Z:PANYARGS
?ResetBuffer@CQueryScanner@@QEAAXPEBG@Z TEXTEQU <__imp_?ResetBuffer@CQueryScanner@@QEAAXPEBG@Z>
extern __imp_?ResetType@CAllocStorageVariant@@IEAAXAEAVPMemoryAllocator@@@Z:PANYARGS
?ResetType@CAllocStorageVariant@@IEAAXAEAVPMemoryAllocator@@@Z TEXTEQU <__imp_?ResetType@CAllocStorageVariant@@IEAAXAEAVPMemoryAllocator@@@Z>
extern __imp_?Resume@CProcess@@QEAAXXZ:PANYARGS
?Resume@CProcess@@QEAAXXZ TEXTEQU <__imp_?Resume@CProcess@@QEAAXXZ>
extern __imp_?ReturnBuffer@CPhysStorage@@QEAAXKHH@Z:PANYARGS
?ReturnBuffer@CPhysStorage@@QEAAXKHH@Z TEXTEQU <__imp_?ReturnBuffer@CPhysStorage@@QEAAXKHH@Z>
extern __imp_?Rewind@CMmStreamConsecBuf@@QEAAXXZ:PANYARGS
?Rewind@CMmStreamConsecBuf@@QEAAXXZ TEXTEQU <__imp_?Rewind@CMmStreamConsecBuf@@QEAAXXZ>
extern __imp_?SaComputeSize@@YAKGAEAUtagSAFEARRAY@@@Z:PANYARGS
?SaComputeSize@@YAKGAEAUtagSAFEARRAY@@@Z TEXTEQU <__imp_?SaComputeSize@@YAKGAEAUtagSAFEARRAY@@@Z>
extern __imp_?SaCreateAndCopy@@YAHAEAVPMemoryAllocator@@PEAUtagSAFEARRAY@@PEAPEAU2@@Z:PANYARGS
?SaCreateAndCopy@@YAHAEAVPMemoryAllocator@@PEAUtagSAFEARRAY@@PEAPEAU2@@Z TEXTEQU <__imp_?SaCreateAndCopy@@YAHAEAVPMemoryAllocator@@PEAUtagSAFEARRAY@@PEAPEAU2@@Z>
extern __imp_?SaCreateData@@YAHAEAVPVarAllocator@@GAEAUtagSAFEARRAY@@1H@Z:PANYARGS
?SaCreateData@@YAHAEAVPVarAllocator@@GAEAUtagSAFEARRAY@@1H@Z TEXTEQU <__imp_?SaCreateData@@YAHAEAVPVarAllocator@@GAEAUtagSAFEARRAY@@1H@Z>
extern __imp_?Seek@CRcovStrmTrans@@QEAAHK@Z:PANYARGS
?Seek@CRcovStrmTrans@@QEAAHK@Z TEXTEQU <__imp_?Seek@CRcovStrmTrans@@QEAAHK@Z>
extern __imp_?Serialize@CDbQueryResults@@QEBAXAEAVPSerStream@@@Z:PANYARGS
?Serialize@CDbQueryResults@@QEBAXAEAVPSerStream@@@Z TEXTEQU <__imp_?Serialize@CDbQueryResults@@QEBAXAEAVPSerStream@@@Z>
extern __imp_?Set@CPidRemapper@@QEAAXAEAV?$XArray@K@@@Z:PANYARGS
?Set@CPidRemapper@@QEAAXAEAV?$XArray@K@@@Z TEXTEQU <__imp_?Set@CPidRemapper@@QEAAXAEAV?$XArray@K@@@Z>
extern __imp_?SetAlias@CScopeAdmin@@QEAAXPEBG@Z:PANYARGS
?SetAlias@CScopeAdmin@@QEAAXPEBG@Z TEXTEQU <__imp_?SetAlias@CScopeAdmin@@QEAAXPEBG@Z>
extern __imp_?SetBOOL@CStorageVariant@@QEAAXFI@Z:PANYARGS
?SetBOOL@CStorageVariant@@QEAAXFI@Z TEXTEQU <__imp_?SetBOOL@CStorageVariant@@QEAAXFI@Z>
extern __imp_?SetBSTR@CAllocStorageVariant@@QEAAXPEAGAEAVPMemoryAllocator@@@Z:PANYARGS
?SetBSTR@CAllocStorageVariant@@QEAAXPEAGAEAVPMemoryAllocator@@@Z TEXTEQU <__imp_?SetBSTR@CAllocStorageVariant@@QEAAXPEAGAEAVPMemoryAllocator@@@Z>
extern __imp_?SetBSTR@CStorageVariant@@QEAAXPEAGI@Z:PANYARGS
?SetBSTR@CStorageVariant@@QEAAXPEAGI@Z TEXTEQU <__imp_?SetBSTR@CStorageVariant@@QEAAXPEAGI@Z>
extern __imp_?SetBackupSize@CPropStoreManager@@QEAAXKK@Z:PANYARGS
?SetBackupSize@CPropStoreManager@@QEAAXKK@Z TEXTEQU <__imp_?SetBackupSize@CPropStoreManager@@QEAAXKK@Z>
extern __imp_?SetCD@CCatState@@QEAAXPEBG@Z:PANYARGS
?SetCD@CCatState@@QEAAXPEBG@Z TEXTEQU <__imp_?SetCD@CCatState@@QEAAXPEBG@Z>
extern __imp_?SetCLSID@CStorageVariant@@QEAAXPEBU_GUID@@@Z:PANYARGS
?SetCLSID@CStorageVariant@@QEAAXPEBU_GUID@@@Z TEXTEQU <__imp_?SetCLSID@CStorageVariant@@QEAAXPEBU_GUID@@@Z>
extern __imp_?SetCLSID@CStorageVariant@@QEAAXU_GUID@@I@Z:PANYARGS
?SetCLSID@CStorageVariant@@QEAAXU_GUID@@I@Z TEXTEQU <__imp_?SetCLSID@CStorageVariant@@QEAAXU_GUID@@I@Z>
extern __imp_?SetCY@CStorageVariant@@QEAAXTtagCY@@I@Z:PANYARGS
?SetCY@CStorageVariant@@QEAAXTtagCY@@I@Z TEXTEQU <__imp_?SetCY@CStorageVariant@@QEAAXTtagCY@@I@Z>
extern __imp_?SetCatalog@CCatState@@QEAAXPEBG@Z:PANYARGS
?SetCatalog@CCatState@@QEAAXPEBG@Z TEXTEQU <__imp_?SetCatalog@CCatState@@QEAAXPEBG@Z>
extern __imp_?SetColumn@CCatState@@QEAAXPEBGI@Z:PANYARGS
?SetColumn@CCatState@@QEAAXPEBGI@Z TEXTEQU <__imp_?SetColumn@CCatState@@QEAAXPEBGI@Z>
extern __imp_?SetCurrentProperty@CQueryParser@@AEAAXPEBGW4PropertyType@@@Z:PANYARGS
?SetCurrentProperty@CQueryParser@@AEAAXPEBGW4PropertyType@@@Z TEXTEQU <__imp_?SetCurrentProperty@CQueryParser@@AEAAXPEBGW4PropertyType@@@Z>
extern __imp_?SetDATE@CStorageVariant@@QEAAXNI@Z:PANYARGS
?SetDATE@CStorageVariant@@QEAAXNI@Z TEXTEQU <__imp_?SetDATE@CStorageVariant@@QEAAXNI@Z>
extern __imp_?SetDWORDParam@CCatalogAdmin@@QEAAXPEBGK@Z:PANYARGS
?SetDWORDParam@CCatalogAdmin@@QEAAXPEBGK@Z TEXTEQU <__imp_?SetDWORDParam@CCatalogAdmin@@QEAAXPEBGK@Z>
extern __imp_?SetDWORDParam@CMachineAdmin@@QEAAXPEBGK@Z:PANYARGS
?SetDWORDParam@CMachineAdmin@@QEAAXPEBGK@Z TEXTEQU <__imp_?SetDWORDParam@CMachineAdmin@@QEAAXPEBGK@Z>
extern __imp_?SetDefaultProperty@CCatState@@QEAAXPEBG@Z:PANYARGS
?SetDefaultProperty@CCatState@@QEAAXPEBG@Z TEXTEQU <__imp_?SetDefaultProperty@CCatState@@QEAAXPEBG@Z>
extern __imp_?SetExclude@CScopeAdmin@@QEAAXH@Z:PANYARGS
?SetExclude@CScopeAdmin@@QEAAXH@Z TEXTEQU <__imp_?SetExclude@CScopeAdmin@@QEAAXH@Z>
extern __imp_?SetFILETIME@CStorageVariant@@QEAAXU_FILETIME@@I@Z:PANYARGS
?SetFILETIME@CStorageVariant@@QEAAXU_FILETIME@@I@Z TEXTEQU <__imp_?SetFILETIME@CStorageVariant@@QEAAXU_FILETIME@@I@Z>
extern __imp_?SetI2@CStorageVariant@@QEAAXFI@Z:PANYARGS
?SetI2@CStorageVariant@@QEAAXFI@Z TEXTEQU <__imp_?SetI2@CStorageVariant@@QEAAXFI@Z>
extern __imp_?SetI4@CStorageVariant@@QEAAXJI@Z:PANYARGS
?SetI4@CStorageVariant@@QEAAXJI@Z TEXTEQU <__imp_?SetI4@CStorageVariant@@QEAAXJI@Z>
extern __imp_?SetI8@CStorageVariant@@QEAAXT_LARGE_INTEGER@@I@Z:PANYARGS
?SetI8@CStorageVariant@@QEAAXT_LARGE_INTEGER@@I@Z TEXTEQU <__imp_?SetI8@CStorageVariant@@QEAAXT_LARGE_INTEGER@@I@Z>
extern __imp_?SetLPSTR@CStorageVariant@@QEAAXPEBDI@Z:PANYARGS
?SetLPSTR@CStorageVariant@@QEAAXPEBDI@Z TEXTEQU <__imp_?SetLPSTR@CStorageVariant@@QEAAXPEBDI@Z>
extern __imp_?SetLPWSTR@CStorageVariant@@QEAAXPEBGI@Z:PANYARGS
?SetLPWSTR@CStorageVariant@@QEAAXPEBGI@Z TEXTEQU <__imp_?SetLPWSTR@CStorageVariant@@QEAAXPEBGI@Z>
extern __imp_?SetLocale@CCatState@@QEAAXPEBG@Z:PANYARGS
?SetLocale@CCatState@@QEAAXPEBG@Z TEXTEQU <__imp_?SetLocale@CCatState@@QEAAXPEBG@Z>
extern __imp_?SetLogonInfo@CScopeAdmin@@QEAAXPEBG0AEAVCCatalogAdmin@@@Z:PANYARGS
?SetLogonInfo@CScopeAdmin@@QEAAXPEBG0AEAVCCatalogAdmin@@@Z TEXTEQU <__imp_?SetLogonInfo@CScopeAdmin@@QEAAXPEBG0AEAVCCatalogAdmin@@@Z>
extern __imp_?SetMappedCacheSize@CPropStoreManager@@QEAAXKK@Z:PANYARGS
?SetMappedCacheSize@CPropStoreManager@@QEAAXKK@Z TEXTEQU <__imp_?SetMappedCacheSize@CPropStoreManager@@QEAAXKK@Z>
extern __imp_?SetNumberOfColumns@CCatState@@QEAAXI@Z:PANYARGS
?SetNumberOfColumns@CCatState@@QEAAXI@Z TEXTEQU <__imp_?SetNumberOfColumns@CCatState@@QEAAXI@Z>
extern __imp_?SetNumberOfSortProps@CCatState@@QEAAXI@Z:PANYARGS
?SetNumberOfSortProps@CCatState@@QEAAXI@Z TEXTEQU <__imp_?SetNumberOfSortProps@CCatState@@QEAAXI@Z>
extern __imp_?SetPath@CScopeAdmin@@QEAAXPEBG@Z:PANYARGS
?SetPath@CScopeAdmin@@QEAAXPEBG@Z TEXTEQU <__imp_?SetPath@CScopeAdmin@@QEAAXPEBG@Z>
extern __imp_?SetPhrase@CContentRestriction@@QEAAXPEBG@Z:PANYARGS
?SetPhrase@CContentRestriction@@QEAAXPEBG@Z TEXTEQU <__imp_?SetPhrase@CContentRestriction@@QEAAXPEBG@Z>
extern __imp_?SetPhrase@CNatLanguageRestriction@@QEAAXPEBG@Z:PANYARGS
?SetPhrase@CNatLanguageRestriction@@QEAAXPEBG@Z TEXTEQU <__imp_?SetPhrase@CNatLanguageRestriction@@QEAAXPEBG@Z>
extern __imp_?SetPriority@CGenericCiProxy@@QEAAXKK@Z:PANYARGS
?SetPriority@CGenericCiProxy@@QEAAXKK@Z TEXTEQU <__imp_?SetPriority@CGenericCiProxy@@QEAAXKK@Z>
extern __imp_?SetProperties@CDbProperties@@UEAAJKQEAUtagDBPROPSET@@@Z:PANYARGS
?SetProperties@CDbProperties@@UEAAJKQEAUtagDBPROPSET@@@Z TEXTEQU <__imp_?SetProperties@CDbProperties@@UEAAJKQEAUtagDBPROPSET@@@Z>
extern __imp_?SetProperty@CDbColId@@QEAAHPEBG@Z:PANYARGS
?SetProperty@CDbColId@@QEAAHPEBG@Z TEXTEQU <__imp_?SetProperty@CDbColId@@QEAAHPEBG@Z>
extern __imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBUtagDBID@@@Z:PANYARGS
?SetProperty@CDbPropBaseRestriction@@QEAAHAEBUtagDBID@@@Z TEXTEQU <__imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBUtagDBID@@@Z>
extern __imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBVCDbColumnNode@@@Z:PANYARGS
?SetProperty@CDbPropBaseRestriction@@QEAAHAEBVCDbColumnNode@@@Z TEXTEQU <__imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBVCDbColumnNode@@@Z>
extern __imp_?SetProperty@CFullPropSpec@@QEAAHPEBG@Z:PANYARGS
?SetProperty@CFullPropSpec@@QEAAHPEBG@Z TEXTEQU <__imp_?SetProperty@CFullPropSpec@@QEAAHPEBG@Z>
extern __imp_?SetProperty@CFullPropSpec@@QEAAXK@Z:PANYARGS
?SetProperty@CFullPropSpec@@QEAAXK@Z TEXTEQU <__imp_?SetProperty@CFullPropSpec@@QEAAXK@Z>
extern __imp_?SetR4@CStorageVariant@@QEAAXMI@Z:PANYARGS
?SetR4@CStorageVariant@@QEAAXMI@Z TEXTEQU <__imp_?SetR4@CStorageVariant@@QEAAXMI@Z>
extern __imp_?SetR8@CStorageVariant@@QEAAXNI@Z:PANYARGS
?SetR8@CStorageVariant@@QEAAXNI@Z TEXTEQU <__imp_?SetR8@CStorageVariant@@QEAAXNI@Z>
extern __imp_?SetRestriction@CDbSelectNode@@QEAAHPEAVCDbCmdTreeNode@@@Z:PANYARGS
?SetRestriction@CDbSelectNode@@QEAAHPEAVCDbCmdTreeNode@@@Z TEXTEQU <__imp_?SetRestriction@CDbSelectNode@@QEAAHPEAVCDbCmdTreeNode@@@Z>
extern __imp_?SetRunningAsSystem@CImpersonateSystem@@SAXXZ:PANYARGS
?SetRunningAsSystem@CImpersonateSystem@@SAXXZ TEXTEQU <__imp_?SetRunningAsSystem@CImpersonateSystem@@SAXXZ>
extern __imp_?SetSZParam@CMachineAdmin@@QEAAXPEBG0K@Z:PANYARGS
?SetSZParam@CMachineAdmin@@QEAAXPEBG0K@Z TEXTEQU <__imp_?SetSZParam@CMachineAdmin@@QEAAXPEBG0K@Z>
extern __imp_?SetScopeProperties@@YAXPEAUICommand@@IPEBQEBGPEBK11@Z:PANYARGS
?SetScopeProperties@@YAXPEAUICommand@@IPEBQEBGPEBK11@Z TEXTEQU <__imp_?SetScopeProperties@@YAXPEAUICommand@@IPEBQEBGPEBK11@Z>
extern __imp_?SetScopePropertiesNoThrow@@YAJPEAUICommand@@IPEBQEBGPEBK11@Z:PANYARGS
?SetScopePropertiesNoThrow@@YAJPEAUICommand@@IPEBQEBGPEBK11@Z TEXTEQU <__imp_?SetScopePropertiesNoThrow@@YAJPEAUICommand@@IPEBQEBGPEBK11@Z>
extern __imp_?SetSecret@@YAXPEBG00K@Z:PANYARGS
?SetSecret@@YAXPEBG00K@Z TEXTEQU <__imp_?SetSecret@@YAXPEBG00K@Z>
extern __imp_?SetSortProp@CCatState@@QEAAXPEBGW4SORTDIR@@I@Z:PANYARGS
?SetSortProp@CCatState@@QEAAXPEBGW4SORTDIR@@I@Z TEXTEQU <__imp_?SetSortProp@CCatState@@QEAAXPEBGW4SORTDIR@@I@Z>
extern __imp_?SetUI1@CStorageVariant@@QEAAXEI@Z:PANYARGS
?SetUI1@CStorageVariant@@QEAAXEI@Z TEXTEQU <__imp_?SetUI1@CStorageVariant@@QEAAXEI@Z>
extern __imp_?SetUI2@CStorageVariant@@QEAAXGI@Z:PANYARGS
?SetUI2@CStorageVariant@@QEAAXGI@Z TEXTEQU <__imp_?SetUI2@CStorageVariant@@QEAAXGI@Z>
extern __imp_?SetUI4@CStorageVariant@@QEAAXKI@Z:PANYARGS
?SetUI4@CStorageVariant@@QEAAXKI@Z TEXTEQU <__imp_?SetUI4@CStorageVariant@@QEAAXKI@Z>
extern __imp_?SetUI8@CStorageVariant@@QEAAXT_ULARGE_INTEGER@@I@Z:PANYARGS
?SetUI8@CStorageVariant@@QEAAXT_ULARGE_INTEGER@@I@Z TEXTEQU <__imp_?SetUI8@CStorageVariant@@QEAAXT_ULARGE_INTEGER@@I@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXPEAG@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z>
extern __imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z:PANYARGS
?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z TEXTEQU <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z>
extern __imp_?SetWeight@CDbCmdTreeNode@@QEAAXJ@Z:PANYARGS
?SetWeight@CDbCmdTreeNode@@QEAAXJ@Z TEXTEQU <__imp_?SetWeight@CDbCmdTreeNode@@QEAAXJ@Z>
extern __imp_?Setup@CPropStoreManager@@QEAAXKKK_KHK@Z:PANYARGS
?Setup@CPropStoreManager@@QEAAXKKK_KHK@Z TEXTEQU <__imp_?Setup@CPropStoreManager@@QEAAXKKK_KHK@Z>
extern __imp_?Shrink@CDynStream@@QEAAXAEAVPStorage@@K@Z:PANYARGS
?Shrink@CDynStream@@QEAAXAEAVPStorage@@K@Z TEXTEQU <__imp_?Shrink@CDynStream@@QEAAXAEAVPStorage@@K@Z>
extern __imp_?ShrinkFromFront@CPhysStorage@@QEAAKKK@Z:PANYARGS
?ShrinkFromFront@CPhysStorage@@QEAAKKK@Z TEXTEQU <__imp_?ShrinkFromFront@CPhysStorage@@QEAAKKK@Z>
extern __imp_?ShrinkToFit@CPhysStorage@@QEAAXXZ:PANYARGS
?ShrinkToFit@CPhysStorage@@QEAAXXZ TEXTEQU <__imp_?ShrinkToFit@CPhysStorage@@QEAAXXZ>
extern __imp_?Shutdown@CCiOle@@SAXXZ:PANYARGS
?Shutdown@CCiOle@@SAXXZ TEXTEQU <__imp_?Shutdown@CCiOle@@SAXXZ>
extern __imp_?Shutdown@CPropStoreManager@@QEAAXXZ:PANYARGS
?Shutdown@CPropStoreManager@@QEAAXXZ TEXTEQU <__imp_?Shutdown@CPropStoreManager@@QEAAXXZ>
extern __imp_?Shutdown@CWorkQueue@@QEAAXXZ:PANYARGS
?Shutdown@CWorkQueue@@QEAAXXZ TEXTEQU <__imp_?Shutdown@CWorkQueue@@QEAAXXZ>
extern __imp_?Size@CDbQueryResults@@QEAAKXZ:PANYARGS
?Size@CDbQueryResults@@QEAAKXZ TEXTEQU <__imp_?Size@CDbQueryResults@@QEAAKXZ>
extern __imp_?Skip@CEnumString@@UEAAJK@Z:PANYARGS
?Skip@CEnumString@@UEAAJK@Z TEXTEQU <__imp_?Skip@CEnumString@@UEAAJK@Z>
extern __imp_?Skip@CEnumWorkid@@UEAAJK@Z:PANYARGS
?Skip@CEnumWorkid@@UEAAJK@Z TEXTEQU <__imp_?Skip@CEnumWorkid@@UEAAJK@Z>
extern __imp_?SkipBlob@CMemDeSerStream@@UEAAXK@Z:PANYARGS
?SkipBlob@CMemDeSerStream@@UEAAXK@Z TEXTEQU <__imp_?SkipBlob@CMemDeSerStream@@UEAAXK@Z>
extern __imp_?SkipByte@CMemDeSerStream@@UEAAXXZ:PANYARGS
?SkipByte@CMemDeSerStream@@UEAAXXZ TEXTEQU <__imp_?SkipByte@CMemDeSerStream@@UEAAXXZ>
extern __imp_?SkipChar@CMemDeSerStream@@UEAAXK@Z:PANYARGS
?SkipChar@CMemDeSerStream@@UEAAXK@Z TEXTEQU <__imp_?SkipChar@CMemDeSerStream@@UEAAXK@Z>
extern __imp_?SkipDouble@CMemDeSerStream@@UEAAXXZ:PANYARGS
?SkipDouble@CMemDeSerStream@@UEAAXXZ TEXTEQU <__imp_?SkipDouble@CMemDeSerStream@@UEAAXXZ>
extern __imp_?SkipFloat@CMemDeSerStream@@UEAAXXZ:PANYARGS
?SkipFloat@CMemDeSerStream@@UEAAXXZ TEXTEQU <__imp_?SkipFloat@CMemDeSerStream@@UEAAXXZ>
extern __imp_?SkipGUID@CMemDeSerStream@@UEAAXXZ:PANYARGS
?SkipGUID@CMemDeSerStream@@UEAAXXZ TEXTEQU <__imp_?SkipGUID@CMemDeSerStream@@UEAAXXZ>
extern __imp_?SkipLong@CMemDeSerStream@@UEAAXXZ:PANYARGS
?SkipLong@CMemDeSerStream@@UEAAXXZ TEXTEQU <__imp_?SkipLong@CMemDeSerStream@@UEAAXXZ>
extern __imp_?SkipULong@CMemDeSerStream@@UEAAXXZ:PANYARGS
?SkipULong@CMemDeSerStream@@UEAAXXZ TEXTEQU <__imp_?SkipULong@CMemDeSerStream@@UEAAXXZ>
extern __imp_?SkipUShort@CMemDeSerStream@@UEAAXXZ:PANYARGS
?SkipUShort@CMemDeSerStream@@UEAAXXZ TEXTEQU <__imp_?SkipUShort@CMemDeSerStream@@UEAAXXZ>
extern __imp_?SkipWChar@CMemDeSerStream@@UEAAXK@Z:PANYARGS
?SkipWChar@CMemDeSerStream@@UEAAXK@Z TEXTEQU <__imp_?SkipWChar@CMemDeSerStream@@UEAAXK@Z>
extern __imp_?Start@CCatalogAdmin@@QEAAHXZ:PANYARGS
?Start@CCatalogAdmin@@QEAAHXZ TEXTEQU <__imp_?Start@CCatalogAdmin@@QEAAHXZ>
extern __imp_?StartCI@CMachineAdmin@@QEAAHXZ:PANYARGS
?StartCI@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?StartCI@CMachineAdmin@@QEAAHXZ>
extern __imp_?Stop@CCatalogAdmin@@QEAAHXZ:PANYARGS
?Stop@CCatalogAdmin@@QEAAHXZ TEXTEQU <__imp_?Stop@CCatalogAdmin@@QEAAHXZ>
extern __imp_?StopCI@CMachineAdmin@@QEAAHXZ:PANYARGS
?StopCI@CMachineAdmin@@QEAAHXZ TEXTEQU <__imp_?StopCI@CMachineAdmin@@QEAAHXZ>
extern __imp_?StopFiltering@CFilterDaemon@@QEAAXXZ:PANYARGS
?StopFiltering@CFilterDaemon@@QEAAXXZ TEXTEQU <__imp_?StopFiltering@CFilterDaemon@@QEAAXXZ>
extern __imp_?StrLen@CKey@@QEBAIXZ:PANYARGS
?StrLen@CKey@@QEBAIXZ TEXTEQU <__imp_?StrLen@CKey@@QEBAIXZ>
extern __imp_?StrLen@CKeyBuf@@QEBAIXZ:PANYARGS
?StrLen@CKeyBuf@@QEBAIXZ TEXTEQU <__imp_?StrLen@CKeyBuf@@QEBAIXZ>
extern __imp_?SystemExceptionTranslator@@YAXIPEAU_EXCEPTION_POINTERS@@@Z:PANYARGS
?SystemExceptionTranslator@@YAXIPEAU_EXCEPTION_POINTERS@@@Z TEXTEQU <__imp_?SystemExceptionTranslator@@YAXIPEAU_EXCEPTION_POINTERS@@@Z>
extern __imp_?TreeCount@CRestriction@@QEBAKXZ:PANYARGS
?TreeCount@CRestriction@@QEBAKXZ TEXTEQU <__imp_?TreeCount@CRestriction@@QEBAKXZ>
extern __imp_?TunePerformance@CMachineAdmin@@QEAAXHGG@Z:PANYARGS
?TunePerformance@CMachineAdmin@@QEAAXHGG@Z TEXTEQU <__imp_?TunePerformance@CMachineAdmin@@QEAAXHGG@Z>
extern __imp_?URLEscapeW@@YAXPEBGAEAVCVirtualString@@KH@Z:PANYARGS
?URLEscapeW@@YAXPEBGAEAVCVirtualString@@KH@Z TEXTEQU <__imp_?URLEscapeW@@YAXPEBGAEAVCVirtualString@@KH@Z>
extern __imp_?UnMarshall@CDbProperties@@QEAAHAEAVPDeSerStream@@@Z:PANYARGS
?UnMarshall@CDbProperties@@QEAAHAEAVPDeSerStream@@@Z TEXTEQU <__imp_?UnMarshall@CDbProperties@@QEAAHAEAVPDeSerStream@@@Z>
extern __imp_?UnMarshall@CRestriction@@SAPEAV1@AEAVPDeSerStream@@@Z:PANYARGS
?UnMarshall@CRestriction@@SAPEAV1@AEAVPDeSerStream@@@Z TEXTEQU <__imp_?UnMarshall@CRestriction@@SAPEAV1@AEAVPDeSerStream@@@Z>
extern __imp_?UnMarshallTree@CDbCmdTreeNode@@SAPEAV1@AEAVPDeSerStream@@@Z:PANYARGS
?UnMarshallTree@CDbCmdTreeNode@@SAPEAV1@AEAVPDeSerStream@@@Z TEXTEQU <__imp_?UnMarshallTree@CDbCmdTreeNode@@SAPEAV1@AEAVPDeSerStream@@@Z>
extern __imp_?UnPickle@@YAXHAEAV?$XPtr@VCColumnSet@@@@AEAV?$XPtr@VCRestriction@@@@AEAV?$XPtr@VCSortSet@@@@AEAV?$XPtr@VCCategorizationSet@@@@AEAVCRowsetProperties@@AEAV?$XPtr@VCPidMapper@@@@PEAEK@Z:PANYARGS
?UnPickle@@YAXHAEAV?$XPtr@VCColumnSet@@@@AEAV?$XPtr@VCRestriction@@@@AEAV?$XPtr@VCSortSet@@@@AEAV?$XPtr@VCCategorizationSet@@@@AEAVCRowsetProperties@@AEAV?$XPtr@VCPidMapper@@@@PEAEK@Z TEXTEQU <__imp_?UnPickle@@YAXHAEAV?$XPtr@VCColumnSet@@@@AEAV?$XPtr@VCRestriction@@@@AEAV?$XPtr@VCSortSet@@@@AEAV?$XPtr@VCCategorizationSet@@@@AEAVCRowsetProperties@@AEAV?$XPtr@VCPidMapper@@@@PEAEK@Z>
extern __imp_?Unmap@CRcovStrmTrans@@IEAAXW4DataCopyNum@CRcovStorageHdr@@@Z:PANYARGS
?Unmap@CRcovStrmTrans@@IEAAXW4DataCopyNum@CRcovStorageHdr@@@Z TEXTEQU <__imp_?Unmap@CRcovStrmTrans@@IEAAXW4DataCopyNum@CRcovStorageHdr@@@Z>
extern __imp_?UpdateContentIndex@@YAKPEBG00H@Z:PANYARGS
?UpdateContentIndex@@YAKPEBG00H@Z TEXTEQU <__imp_?UpdateContentIndex@@YAKPEBG00H@Z>
extern __imp_?UpdateDiskLowInfo@CDiskFreeStatus@@QEAAXXZ:PANYARGS
?UpdateDiskLowInfo@CDiskFreeStatus@@QEAAXXZ TEXTEQU <__imp_?UpdateDiskLowInfo@CDiskFreeStatus@@QEAAXXZ>
extern __imp_?VT_VARIANT_EQ@@YAHAEBUtagPROPVARIANT@@0@Z:PANYARGS
?VT_VARIANT_EQ@@YAHAEBUtagPROPVARIANT@@0@Z TEXTEQU <__imp_?VT_VARIANT_EQ@@YAHAEBUtagPROPVARIANT@@0@Z>
extern __imp_?VT_VARIANT_GE@@YAHAEBUtagPROPVARIANT@@0@Z:PANYARGS
?VT_VARIANT_GE@@YAHAEBUtagPROPVARIANT@@0@Z TEXTEQU <__imp_?VT_VARIANT_GE@@YAHAEBUtagPROPVARIANT@@0@Z>
extern __imp_?VT_VARIANT_GT@@YAHAEBUtagPROPVARIANT@@0@Z:PANYARGS
?VT_VARIANT_GT@@YAHAEBUtagPROPVARIANT@@0@Z TEXTEQU <__imp_?VT_VARIANT_GT@@YAHAEBUtagPROPVARIANT@@0@Z>
extern __imp_?VT_VARIANT_LE@@YAHAEBUtagPROPVARIANT@@0@Z:PANYARGS
?VT_VARIANT_LE@@YAHAEBUtagPROPVARIANT@@0@Z TEXTEQU <__imp_?VT_VARIANT_LE@@YAHAEBUtagPROPVARIANT@@0@Z>
extern __imp_?VT_VARIANT_LT@@YAHAEBUtagPROPVARIANT@@0@Z:PANYARGS
?VT_VARIANT_LT@@YAHAEBUtagPROPVARIANT@@0@Z TEXTEQU <__imp_?VT_VARIANT_LT@@YAHAEBUtagPROPVARIANT@@0@Z>
extern __imp_?VT_VARIANT_NE@@YAHAEBUtagPROPVARIANT@@0@Z:PANYARGS
?VT_VARIANT_NE@@YAHAEBUtagPROPVARIANT@@0@Z TEXTEQU <__imp_?VT_VARIANT_NE@@YAHAEBUtagPROPVARIANT@@0@Z>
extern __imp_?ValidateScopeRestriction@@YAHPEAVCRestriction@@@Z:PANYARGS
?ValidateScopeRestriction@@YAHPEAVCRestriction@@@Z TEXTEQU <__imp_?ValidateScopeRestriction@@YAHPEAVCRestriction@@@Z>
extern __imp_?VerifyConsistency@PRcovStorageObj@@QEAAXXZ:PANYARGS
?VerifyConsistency@PRcovStorageObj@@QEAAXXZ TEXTEQU <__imp_?VerifyConsistency@PRcovStorageObj@@QEAAXXZ>
extern __imp_?VerifyThreadHasAdminPrivilege@@YAXXZ:PANYARGS
?VerifyThreadHasAdminPrivilege@@YAXXZ TEXTEQU <__imp_?VerifyThreadHasAdminPrivilege@@YAXXZ>
extern __imp_?WideCharToXArrayMultiByte@@YAKPEBGKIAEAV?$XArray@E@@@Z:PANYARGS
?WideCharToXArrayMultiByte@@YAKPEBGKIAEAV?$XArray@E@@@Z TEXTEQU <__imp_?WideCharToXArrayMultiByte@@YAKPEBGKIAEAV?$XArray@E@@@Z>
extern __imp_?Write@CDynStream@@QEAAXPEAXK@Z:PANYARGS
?Write@CDynStream@@QEAAXPEAXK@Z TEXTEQU <__imp_?Write@CDynStream@@QEAAXPEAXK@Z>
extern __imp_?Write@CRcovStrmTrans@@IEAAXPEBXK@Z:PANYARGS
?Write@CRcovStrmTrans@@IEAAXPEBXK@Z TEXTEQU <__imp_?Write@CRcovStrmTrans@@IEAAXPEBXK@Z>
extern __imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z:PANYARGS
?WritePrimaryProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z TEXTEQU <__imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z>
extern __imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z:PANYARGS
?WritePrimaryProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z TEXTEQU <__imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z>
extern __imp_?WriteProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z:PANYARGS
?WriteProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z TEXTEQU <__imp_?WriteProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z>
extern __imp_?WriteProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z:PANYARGS
?WriteProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z TEXTEQU <__imp_?WriteProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z>
extern __imp_?WritePropertyInNewRecord@CPropStoreManager@@QEAAKKAEBVCStorageVariant@@@Z:PANYARGS
?WritePropertyInNewRecord@CPropStoreManager@@QEAAKKAEBVCStorageVariant@@@Z TEXTEQU <__imp_?WritePropertyInNewRecord@CPropStoreManager@@QEAAKKAEBVCStorageVariant@@@Z>
extern __imp_?_FindGroupListAnchor@CDbNestingNode@@AEAAPEAVCDbProjectListAnchor@@XZ:PANYARGS
?_FindGroupListAnchor@CDbNestingNode@@AEAAPEAVCDbProjectListAnchor@@XZ TEXTEQU <__imp_?_FindGroupListAnchor@CDbNestingNode@@AEAAPEAVCDbProjectListAnchor@@XZ>
extern __imp_?_FindOrAddAnchor@CDbProjectNode@@AEAAPEAVCDbProjectListAnchor@@XZ:PANYARGS
?_FindOrAddAnchor@CDbProjectNode@@AEAAPEAVCDbProjectListAnchor@@XZ TEXTEQU <__imp_?_FindOrAddAnchor@CDbProjectNode@@AEAAPEAVCDbProjectListAnchor@@XZ>
extern __imp_?_FindOrAddAnchor@CDbSortNode@@AEAAPEAVCDbSortListAnchor@@XZ:PANYARGS
?_FindOrAddAnchor@CDbSortNode@@AEAAPEAVCDbSortListAnchor@@XZ TEXTEQU <__imp_?_FindOrAddAnchor@CDbSortNode@@AEAAPEAVCDbSortListAnchor@@XZ>
extern __imp_?_FindOrAddValueNode@CDbPropertyRestriction@@AEAAPEAVCDbScalarValue@@XZ:PANYARGS
?_FindOrAddValueNode@CDbPropertyRestriction@@AEAAPEAVCDbScalarValue@@XZ TEXTEQU <__imp_?_FindOrAddValueNode@CDbPropertyRestriction@@AEAAPEAVCDbScalarValue@@XZ>
extern __imp_?_ImpersonateIf@CImpersonateRemoteAccess@@AEAAHPEBG0K@Z:PANYARGS
?_ImpersonateIf@CImpersonateRemoteAccess@@AEAAHPEBG0K@Z TEXTEQU <__imp_?_ImpersonateIf@CImpersonateRemoteAccess@@AEAAHPEBG0K@Z>
extern __imp_?_wcstoui64@@YA_KPEBGPEAPEAGH@Z:PANYARGS
?_wcstoui64@@YA_KPEBGPEAPEAGH@Z TEXTEQU <__imp_?_wcstoui64@@YA_KPEBGPEAPEAGH@Z>
extern __imp_?ciDelete@@YAXPEAX@Z:PANYARGS
?ciDelete@@YAXPEAX@Z TEXTEQU <__imp_?ciDelete@@YAXPEAX@Z>
extern __imp_?ciIsValidPointer@@YAHPEBX@Z:PANYARGS
?ciIsValidPointer@@YAHPEBX@Z TEXTEQU <__imp_?ciIsValidPointer@@YAHPEBX@Z>
extern __imp_?ciNew@@YAPEAX_K@Z:PANYARGS
?ciNew@@YAPEAX_K@Z TEXTEQU <__imp_?ciNew@@YAPEAX_K@Z>
extern __imp_?fgetsw@CFileBuffer@@QEAAKAEAV?$XGrowable@G$0BAE@@@@Z:PANYARGS
?fgetsw@CFileBuffer@@QEAAKAEAV?$XGrowable@G$0BAE@@@@Z TEXTEQU <__imp_?fgetsw@CFileBuffer@@QEAAKAEAV?$XGrowable@G$0BAE@@@@Z>
extern __imp_?wcsipattern@@YAPEAGPEAGPEBG@Z:PANYARGS
?wcsipattern@@YAPEAGPEAGPEBG@Z TEXTEQU <__imp_?wcsipattern@@YAPEAGPEAGPEBG@Z>
extern __imp_AbortMerges:PANYARGS
AbortMerges TEXTEQU <__imp_AbortMerges>
extern __imp_BeginCacheTransaction:PANYARGS
BeginCacheTransaction TEXTEQU <__imp_BeginCacheTransaction>
extern __imp_BindIFilterFromStorage:PANYARGS
BindIFilterFromStorage TEXTEQU <__imp_BindIFilterFromStorage>
extern __imp_BindIFilterFromStream:PANYARGS
BindIFilterFromStream TEXTEQU <__imp_BindIFilterFromStream>
extern __imp_CIBuildQueryNode:PANYARGS
CIBuildQueryNode TEXTEQU <__imp_CIBuildQueryNode>
extern __imp_CIBuildQueryTree:PANYARGS
CIBuildQueryTree TEXTEQU <__imp_CIBuildQueryTree>
extern __imp_CICreateCommand:PANYARGS
CICreateCommand TEXTEQU <__imp_CICreateCommand>
extern __imp_CIGetGlobalPropertyList:PANYARGS
CIGetGlobalPropertyList TEXTEQU <__imp_CIGetGlobalPropertyList>
extern __imp_CIMakeICommand:PANYARGS
CIMakeICommand TEXTEQU <__imp_CIMakeICommand>
extern __imp_CIRestrictionToFullTree:PANYARGS
CIRestrictionToFullTree TEXTEQU <__imp_CIRestrictionToFullTree>
extern __imp_CIState:PANYARGS
CIState TEXTEQU <__imp_CIState>
extern __imp_CITextToFullTree:PANYARGS
CITextToFullTree TEXTEQU <__imp_CITextToFullTree>
extern __imp_CITextToFullTreeEx:PANYARGS
CITextToFullTreeEx TEXTEQU <__imp_CITextToFullTreeEx>
extern __imp_CITextToSelectTree:PANYARGS
CITextToSelectTree TEXTEQU <__imp_CITextToSelectTree>
extern __imp_CITextToSelectTreeEx:PANYARGS
CITextToSelectTreeEx TEXTEQU <__imp_CITextToSelectTreeEx>
extern __imp_CiSvcMain:PANYARGS
CiSvcMain TEXTEQU <__imp_CiSvcMain>
extern __imp_CollectCIISAPIPerformanceData:PANYARGS
CollectCIISAPIPerformanceData TEXTEQU <__imp_CollectCIISAPIPerformanceData>
extern __imp_CollectCIPerformanceData:PANYARGS
CollectCIPerformanceData TEXTEQU <__imp_CollectCIPerformanceData>
extern __imp_CollectFILTERPerformanceData:PANYARGS
CollectFILTERPerformanceData TEXTEQU <__imp_CollectFILTERPerformanceData>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_DoneCIISAPIPerformanceData:PANYARGS
DoneCIISAPIPerformanceData TEXTEQU <__imp_DoneCIISAPIPerformanceData>
extern __imp_DoneCIPerformanceData:PANYARGS
DoneCIPerformanceData TEXTEQU <__imp_DoneCIPerformanceData>
extern __imp_DoneFILTERPerformanceData:PANYARGS
DoneFILTERPerformanceData TEXTEQU <__imp_DoneFILTERPerformanceData>
extern __imp_EndCacheTransaction:PANYARGS
EndCacheTransaction TEXTEQU <__imp_EndCacheTransaction>
extern __imp_ForceMasterMerge:PANYARGS
ForceMasterMerge TEXTEQU <__imp_ForceMasterMerge>
extern __imp_InitializeCIISAPIPerformanceData:PANYARGS
InitializeCIISAPIPerformanceData TEXTEQU <__imp_InitializeCIISAPIPerformanceData>
extern __imp_InitializeCIPerformanceData:PANYARGS
InitializeCIPerformanceData TEXTEQU <__imp_InitializeCIPerformanceData>
extern __imp_InitializeFILTERPerformanceData:PANYARGS
InitializeFILTERPerformanceData TEXTEQU <__imp_InitializeFILTERPerformanceData>
extern __imp_LoadBHIFilter:PANYARGS
LoadBHIFilter TEXTEQU <__imp_LoadBHIFilter>
extern __imp_LoadBinaryFilter:PANYARGS
LoadBinaryFilter TEXTEQU <__imp_LoadBinaryFilter>
extern __imp_LoadIFilter:PANYARGS
LoadIFilter TEXTEQU <__imp_LoadIFilter>
extern __imp_LoadIFilterEx:PANYARGS
LoadIFilterEx TEXTEQU <__imp_LoadIFilterEx>
extern __imp_LoadTextFilter:PANYARGS
LoadTextFilter TEXTEQU <__imp_LoadTextFilter>
extern __imp_LocateCatalogs:PANYARGS
LocateCatalogs TEXTEQU <__imp_LocateCatalogs>
extern __imp_LocateCatalogsA:PANYARGS
LocateCatalogs  TEXTEQU <__imp_LocateCatalogsA>
extern __imp_LocateCatalogsW:PANYARGS
LocateCatalogsW TEXTEQU <__imp_LocateCatalogsW>
extern __imp_SetCatalogState:PANYARGS
SetCatalogState TEXTEQU <__imp_SetCatalogState>
extern __imp_SetupCache:PANYARGS
SetupCache TEXTEQU <__imp_SetupCache>
extern __imp_SetupCacheEx:PANYARGS
SetupCacheEx TEXTEQU <__imp_SetupCacheEx>
extern __imp_StartFWCiSvcWork:PANYARGS
StartFWCiSvcWork TEXTEQU <__imp_StartFWCiSvcWork>
extern __imp_StopFWCiSvcWork:PANYARGS
StopFWCiSvcWork TEXTEQU <__imp_StopFWCiSvcWork>
extern __imp_SvcEntry_CiSvc:PANYARGS
SvcEntry_CiSvc TEXTEQU <__imp_SvcEntry_CiSvc>
