extern __imp_DDMFreePhonebookContext:PANYARGS
DDMFreePhonebookContext TEXTEQU <__imp_DDMFreePhonebookContext>
extern __imp_DDMGetPhonebookInfo:PANYARGS
DDMGetPhonebookInfo TEXTEQU <__imp_DDMGetPhonebookInfo>
extern __imp_DwCloneEntry:PANYARGS
DwCloneEntry TEXTEQU <__imp_DwCloneEntry>
extern __imp_DwDeleteSubEntry:PANYARGS
DwDeleteSubEntry TEXTEQU <__imp_DwDeleteSubEntry>
extern __imp_DwEnumEntriesForAllUsers:PANYARGS
DwEnumEntriesForAllUsers TEXTEQU <__imp_DwEnumEntriesForAllUsers>
extern __imp_DwEnumEntryDetails:PANYARGS
DwEnumEntryDetails TEXTEQU <__imp_DwEnumEntryDetails>
extern __imp_DwRasUninitialize:PANYARGS
DwRasUninitialize TEXTEQU <__imp_DwRasUninitialize>
extern __imp_RasAutoDialSharedConnection:PANYARGS
RasAutoDialSharedConnection TEXTEQU <__imp_RasAutoDialSharedConnection>
extern __imp_RasAutodialAddressToNetwork:PANYARGS
RasAutodialAddressToNetwork TEXTEQU <__imp_RasAutodialAddressToNetwork>
extern __imp_RasAutodialEntryToNetwork:PANYARGS
RasAutodialEntryToNetwork TEXTEQU <__imp_RasAutodialEntryToNetwork>
extern __imp_RasClearConnectionStatistics:PANYARGS
RasClearConnectionStatistics TEXTEQU <__imp_RasClearConnectionStatistics>
extern __imp_RasClearLinkStatistics:PANYARGS
RasClearLinkStatistics TEXTEQU <__imp_RasClearLinkStatistics>
extern __imp_RasConnectionNotificationA:PANYARGS
RasConnectionNotification  TEXTEQU <__imp_RasConnectionNotificationA>
extern __imp_RasConnectionNotificationW:PANYARGS
RasConnectionNotificationW TEXTEQU <__imp_RasConnectionNotificationW>
extern __imp_RasCreatePhonebookEntryA:PANYARGS
RasCreatePhonebookEntry  TEXTEQU <__imp_RasCreatePhonebookEntryA>
extern __imp_RasCreatePhonebookEntryW:PANYARGS
RasCreatePhonebookEntryW TEXTEQU <__imp_RasCreatePhonebookEntryW>
extern __imp_RasDeleteEntryA:PANYARGS
RasDeleteEntry  TEXTEQU <__imp_RasDeleteEntryA>
extern __imp_RasDeleteEntryW:PANYARGS
RasDeleteEntryW TEXTEQU <__imp_RasDeleteEntryW>
extern __imp_RasDeleteSubEntryA:PANYARGS
RasDeleteSubEntry  TEXTEQU <__imp_RasDeleteSubEntryA>
extern __imp_RasDeleteSubEntryW:PANYARGS
RasDeleteSubEntryW TEXTEQU <__imp_RasDeleteSubEntryW>
extern __imp_RasDialA:PANYARGS
RasDial  TEXTEQU <__imp_RasDialA>
extern __imp_RasDialW:PANYARGS
RasDialW TEXTEQU <__imp_RasDialW>
extern __imp_RasDialWow:PANYARGS
RasDialWow TEXTEQU <__imp_RasDialWow>
extern __imp_RasEditPhonebookEntryA:PANYARGS
RasEditPhonebookEntry  TEXTEQU <__imp_RasEditPhonebookEntryA>
extern __imp_RasEditPhonebookEntryW:PANYARGS
RasEditPhonebookEntryW TEXTEQU <__imp_RasEditPhonebookEntryW>
extern __imp_RasEnumAutodialAddressesA:PANYARGS
RasEnumAutodialAddresses  TEXTEQU <__imp_RasEnumAutodialAddressesA>
extern __imp_RasEnumAutodialAddressesW:PANYARGS
RasEnumAutodialAddressesW TEXTEQU <__imp_RasEnumAutodialAddressesW>
extern __imp_RasEnumConnectionsA:PANYARGS
RasEnumConnections  TEXTEQU <__imp_RasEnumConnectionsA>
extern __imp_RasEnumConnectionsW:PANYARGS
RasEnumConnectionsW TEXTEQU <__imp_RasEnumConnectionsW>
extern __imp_RasEnumConnectionsWow:PANYARGS
RasEnumConnectionsWow TEXTEQU <__imp_RasEnumConnectionsWow>
extern __imp_RasEnumDevicesA:PANYARGS
RasEnumDevices  TEXTEQU <__imp_RasEnumDevicesA>
extern __imp_RasEnumDevicesW:PANYARGS
RasEnumDevicesW TEXTEQU <__imp_RasEnumDevicesW>
extern __imp_RasEnumEntriesA:PANYARGS
RasEnumEntries  TEXTEQU <__imp_RasEnumEntriesA>
extern __imp_RasEnumEntriesW:PANYARGS
RasEnumEntriesW TEXTEQU <__imp_RasEnumEntriesW>
extern __imp_RasEnumEntriesWow:PANYARGS
RasEnumEntriesWow TEXTEQU <__imp_RasEnumEntriesWow>
extern __imp_RasFreeEapUserIdentityA:PANYARGS
RasFreeEapUserIdentity  TEXTEQU <__imp_RasFreeEapUserIdentityA>
extern __imp_RasFreeEapUserIdentityW:PANYARGS
RasFreeEapUserIdentityW TEXTEQU <__imp_RasFreeEapUserIdentityW>
extern __imp_RasGetAutodialAddressA:PANYARGS
RasGetAutodialAddress  TEXTEQU <__imp_RasGetAutodialAddressA>
extern __imp_RasGetAutodialAddressW:PANYARGS
RasGetAutodialAddressW TEXTEQU <__imp_RasGetAutodialAddressW>
extern __imp_RasGetAutodialEnableA:PANYARGS
RasGetAutodialEnable  TEXTEQU <__imp_RasGetAutodialEnableA>
extern __imp_RasGetAutodialEnableW:PANYARGS
RasGetAutodialEnableW TEXTEQU <__imp_RasGetAutodialEnableW>
extern __imp_RasGetAutodialParamA:PANYARGS
RasGetAutodialParam  TEXTEQU <__imp_RasGetAutodialParamA>
extern __imp_RasGetAutodialParamW:PANYARGS
RasGetAutodialParamW TEXTEQU <__imp_RasGetAutodialParamW>
extern __imp_RasGetConnectResponse:PANYARGS
RasGetConnectResponse TEXTEQU <__imp_RasGetConnectResponse>
extern __imp_RasGetConnectStatusA:PANYARGS
RasGetConnectStatus  TEXTEQU <__imp_RasGetConnectStatusA>
extern __imp_RasGetConnectStatusW:PANYARGS
RasGetConnectStatusW TEXTEQU <__imp_RasGetConnectStatusW>
extern __imp_RasGetConnectStatusWow:PANYARGS
RasGetConnectStatusWow TEXTEQU <__imp_RasGetConnectStatusWow>
extern __imp_RasGetConnectionStatistics:PANYARGS
RasGetConnectionStatistics TEXTEQU <__imp_RasGetConnectionStatistics>
extern __imp_RasGetCountryInfoA:PANYARGS
RasGetCountryInfo  TEXTEQU <__imp_RasGetCountryInfoA>
extern __imp_RasGetCountryInfoW:PANYARGS
RasGetCountryInfoW TEXTEQU <__imp_RasGetCountryInfoW>
extern __imp_RasGetCredentialsA:PANYARGS
RasGetCredentials  TEXTEQU <__imp_RasGetCredentialsA>
extern __imp_RasGetCredentialsW:PANYARGS
RasGetCredentialsW TEXTEQU <__imp_RasGetCredentialsW>
extern __imp_RasGetCustomAuthDataA:PANYARGS
RasGetCustomAuthData  TEXTEQU <__imp_RasGetCustomAuthDataA>
extern __imp_RasGetCustomAuthDataW:PANYARGS
RasGetCustomAuthDataW TEXTEQU <__imp_RasGetCustomAuthDataW>
extern __imp_RasGetEapUserDataA:PANYARGS
RasGetEapUserData  TEXTEQU <__imp_RasGetEapUserDataA>
extern __imp_RasGetEapUserDataW:PANYARGS
RasGetEapUserDataW TEXTEQU <__imp_RasGetEapUserDataW>
extern __imp_RasGetEapUserIdentityA:PANYARGS
RasGetEapUserIdentity  TEXTEQU <__imp_RasGetEapUserIdentityA>
extern __imp_RasGetEapUserIdentityW:PANYARGS
RasGetEapUserIdentityW TEXTEQU <__imp_RasGetEapUserIdentityW>
extern __imp_RasGetEntryDialParamsA:PANYARGS
RasGetEntryDialParams  TEXTEQU <__imp_RasGetEntryDialParamsA>
extern __imp_RasGetEntryDialParamsW:PANYARGS
RasGetEntryDialParamsW TEXTEQU <__imp_RasGetEntryDialParamsW>
extern __imp_RasGetEntryHrasconnA:PANYARGS
RasGetEntryHrasconn  TEXTEQU <__imp_RasGetEntryHrasconnA>
extern __imp_RasGetEntryHrasconnW:PANYARGS
RasGetEntryHrasconnW TEXTEQU <__imp_RasGetEntryHrasconnW>
extern __imp_RasGetEntryPropertiesA:PANYARGS
RasGetEntryProperties  TEXTEQU <__imp_RasGetEntryPropertiesA>
extern __imp_RasGetEntryPropertiesW:PANYARGS
RasGetEntryPropertiesW TEXTEQU <__imp_RasGetEntryPropertiesW>
extern __imp_RasGetErrorStringA:PANYARGS
RasGetErrorString  TEXTEQU <__imp_RasGetErrorStringA>
extern __imp_RasGetErrorStringW:PANYARGS
RasGetErrorStringW TEXTEQU <__imp_RasGetErrorStringW>
extern __imp_RasGetErrorStringWow:PANYARGS
RasGetErrorStringWow TEXTEQU <__imp_RasGetErrorStringWow>
extern __imp_RasGetHport:PANYARGS
RasGetHport TEXTEQU <__imp_RasGetHport>
extern __imp_RasGetLinkStatistics:PANYARGS
RasGetLinkStatistics TEXTEQU <__imp_RasGetLinkStatistics>
extern __imp_RasGetProjectionInfoA:PANYARGS
RasGetProjectionInfo  TEXTEQU <__imp_RasGetProjectionInfoA>
extern __imp_RasGetProjectionInfoW:PANYARGS
RasGetProjectionInfoW TEXTEQU <__imp_RasGetProjectionInfoW>
extern __imp_RasGetSubEntryHandleA:PANYARGS
RasGetSubEntryHandle  TEXTEQU <__imp_RasGetSubEntryHandleA>
extern __imp_RasGetSubEntryHandleW:PANYARGS
RasGetSubEntryHandleW TEXTEQU <__imp_RasGetSubEntryHandleW>
extern __imp_RasGetSubEntryPropertiesA:PANYARGS
RasGetSubEntryProperties  TEXTEQU <__imp_RasGetSubEntryPropertiesA>
extern __imp_RasGetSubEntryPropertiesW:PANYARGS
RasGetSubEntryPropertiesW TEXTEQU <__imp_RasGetSubEntryPropertiesW>
extern __imp_RasHangUpA:PANYARGS
RasHangUp  TEXTEQU <__imp_RasHangUpA>
extern __imp_RasHangUpW:PANYARGS
RasHangUpW TEXTEQU <__imp_RasHangUpW>
extern __imp_RasHangUpWow:PANYARGS
RasHangUpWow TEXTEQU <__imp_RasHangUpWow>
extern __imp_RasInvokeEapUI:PANYARGS
RasInvokeEapUI TEXTEQU <__imp_RasInvokeEapUI>
extern __imp_RasIsRouterConnection:PANYARGS
RasIsRouterConnection TEXTEQU <__imp_RasIsRouterConnection>
extern __imp_RasIsSharedConnection:PANYARGS
RasIsSharedConnection TEXTEQU <__imp_RasIsSharedConnection>
extern __imp_RasQueryRedialOnLinkFailure:PANYARGS
RasQueryRedialOnLinkFailure TEXTEQU <__imp_RasQueryRedialOnLinkFailure>
extern __imp_RasQuerySharedAutoDial:PANYARGS
RasQuerySharedAutoDial TEXTEQU <__imp_RasQuerySharedAutoDial>
extern __imp_RasQuerySharedConnection:PANYARGS
RasQuerySharedConnection TEXTEQU <__imp_RasQuerySharedConnection>
extern __imp_RasRenameEntryA:PANYARGS
RasRenameEntry  TEXTEQU <__imp_RasRenameEntryA>
extern __imp_RasRenameEntryW:PANYARGS
RasRenameEntryW TEXTEQU <__imp_RasRenameEntryW>
extern __imp_RasScriptExecute:PANYARGS
RasScriptExecute TEXTEQU <__imp_RasScriptExecute>
extern __imp_RasScriptGetEventCode:PANYARGS
RasScriptGetEventCode TEXTEQU <__imp_RasScriptGetEventCode>
extern __imp_RasScriptGetIpAddress:PANYARGS
RasScriptGetIpAddress TEXTEQU <__imp_RasScriptGetIpAddress>
extern __imp_RasScriptInit:PANYARGS
RasScriptInit TEXTEQU <__imp_RasScriptInit>
extern __imp_RasScriptReceive:PANYARGS
RasScriptReceive TEXTEQU <__imp_RasScriptReceive>
extern __imp_RasScriptSend:PANYARGS
RasScriptSend TEXTEQU <__imp_RasScriptSend>
extern __imp_RasScriptTerm:PANYARGS
RasScriptTerm TEXTEQU <__imp_RasScriptTerm>
extern __imp_RasSetAutodialAddressA:PANYARGS
RasSetAutodialAddress  TEXTEQU <__imp_RasSetAutodialAddressA>
extern __imp_RasSetAutodialAddressW:PANYARGS
RasSetAutodialAddressW TEXTEQU <__imp_RasSetAutodialAddressW>
extern __imp_RasSetAutodialEnableA:PANYARGS
RasSetAutodialEnable  TEXTEQU <__imp_RasSetAutodialEnableA>
extern __imp_RasSetAutodialEnableW:PANYARGS
RasSetAutodialEnableW TEXTEQU <__imp_RasSetAutodialEnableW>
extern __imp_RasSetAutodialParamA:PANYARGS
RasSetAutodialParam  TEXTEQU <__imp_RasSetAutodialParamA>
extern __imp_RasSetAutodialParamW:PANYARGS
RasSetAutodialParamW TEXTEQU <__imp_RasSetAutodialParamW>
extern __imp_RasSetCredentialsA:PANYARGS
RasSetCredentials  TEXTEQU <__imp_RasSetCredentialsA>
extern __imp_RasSetCredentialsW:PANYARGS
RasSetCredentialsW TEXTEQU <__imp_RasSetCredentialsW>
extern __imp_RasSetCustomAuthDataA:PANYARGS
RasSetCustomAuthData  TEXTEQU <__imp_RasSetCustomAuthDataA>
extern __imp_RasSetCustomAuthDataW:PANYARGS
RasSetCustomAuthDataW TEXTEQU <__imp_RasSetCustomAuthDataW>
extern __imp_RasSetEapUserDataA:PANYARGS
RasSetEapUserData  TEXTEQU <__imp_RasSetEapUserDataA>
extern __imp_RasSetEapUserDataW:PANYARGS
RasSetEapUserDataW TEXTEQU <__imp_RasSetEapUserDataW>
extern __imp_RasSetEntryDialParamsA:PANYARGS
RasSetEntryDialParams  TEXTEQU <__imp_RasSetEntryDialParamsA>
extern __imp_RasSetEntryDialParamsW:PANYARGS
RasSetEntryDialParamsW TEXTEQU <__imp_RasSetEntryDialParamsW>
extern __imp_RasSetEntryPropertiesA:PANYARGS
RasSetEntryProperties  TEXTEQU <__imp_RasSetEntryPropertiesA>
extern __imp_RasSetEntryPropertiesW:PANYARGS
RasSetEntryPropertiesW TEXTEQU <__imp_RasSetEntryPropertiesW>
extern __imp_RasSetOldPassword:PANYARGS
RasSetOldPassword TEXTEQU <__imp_RasSetOldPassword>
extern __imp_RasSetSharedAutoDial:PANYARGS
RasSetSharedAutoDial TEXTEQU <__imp_RasSetSharedAutoDial>
extern __imp_RasSetSubEntryPropertiesA:PANYARGS
RasSetSubEntryProperties  TEXTEQU <__imp_RasSetSubEntryPropertiesA>
extern __imp_RasSetSubEntryPropertiesW:PANYARGS
RasSetSubEntryPropertiesW TEXTEQU <__imp_RasSetSubEntryPropertiesW>
extern __imp_RasValidateEntryNameA:PANYARGS
RasValidateEntryName  TEXTEQU <__imp_RasValidateEntryNameA>
extern __imp_RasValidateEntryNameW:PANYARGS
RasValidateEntryNameW TEXTEQU <__imp_RasValidateEntryNameW>
extern __imp_RasfileClose:PANYARGS
RasfileClose TEXTEQU <__imp_RasfileClose>
extern __imp_RasfileDeleteLine:PANYARGS
RasfileDeleteLine TEXTEQU <__imp_RasfileDeleteLine>
extern __imp_RasfileFindFirstLine:PANYARGS
RasfileFindFirstLine TEXTEQU <__imp_RasfileFindFirstLine>
extern __imp_RasfileFindLastLine:PANYARGS
RasfileFindLastLine TEXTEQU <__imp_RasfileFindLastLine>
extern __imp_RasfileFindMarkedLine:PANYARGS
RasfileFindMarkedLine TEXTEQU <__imp_RasfileFindMarkedLine>
extern __imp_RasfileFindNextKeyLine:PANYARGS
RasfileFindNextKeyLine TEXTEQU <__imp_RasfileFindNextKeyLine>
extern __imp_RasfileFindNextLine:PANYARGS
RasfileFindNextLine TEXTEQU <__imp_RasfileFindNextLine>
extern __imp_RasfileFindPrevLine:PANYARGS
RasfileFindPrevLine TEXTEQU <__imp_RasfileFindPrevLine>
extern __imp_RasfileFindSectionLine:PANYARGS
RasfileFindSectionLine TEXTEQU <__imp_RasfileFindSectionLine>
extern __imp_RasfileGetKeyValueFields:PANYARGS
RasfileGetKeyValueFields TEXTEQU <__imp_RasfileGetKeyValueFields>
extern __imp_RasfileGetLine:PANYARGS
RasfileGetLine TEXTEQU <__imp_RasfileGetLine>
extern __imp_RasfileGetLineMark:PANYARGS
RasfileGetLineMark TEXTEQU <__imp_RasfileGetLineMark>
extern __imp_RasfileGetLineText:PANYARGS
RasfileGetLineText TEXTEQU <__imp_RasfileGetLineText>
extern __imp_RasfileGetLineType:PANYARGS
RasfileGetLineType TEXTEQU <__imp_RasfileGetLineType>
extern __imp_RasfileGetSectionName:PANYARGS
RasfileGetSectionName TEXTEQU <__imp_RasfileGetSectionName>
extern __imp_RasfileInsertLine:PANYARGS
RasfileInsertLine TEXTEQU <__imp_RasfileInsertLine>
extern __imp_RasfileLoad:PANYARGS
RasfileLoad TEXTEQU <__imp_RasfileLoad>
extern __imp_RasfileLoadEx:PANYARGS
RasfileLoadEx TEXTEQU <__imp_RasfileLoadEx>
extern __imp_RasfileLoadInfo:PANYARGS
RasfileLoadInfo TEXTEQU <__imp_RasfileLoadInfo>
extern __imp_RasfilePutKeyValueFields:PANYARGS
RasfilePutKeyValueFields TEXTEQU <__imp_RasfilePutKeyValueFields>
extern __imp_RasfilePutLineMark:PANYARGS
RasfilePutLineMark TEXTEQU <__imp_RasfilePutLineMark>
extern __imp_RasfilePutLineText:PANYARGS
RasfilePutLineText TEXTEQU <__imp_RasfilePutLineText>
extern __imp_RasfilePutSectionName:PANYARGS
RasfilePutSectionName TEXTEQU <__imp_RasfilePutSectionName>
extern __imp_RasfileWrite:PANYARGS
RasfileWrite TEXTEQU <__imp_RasfileWrite>
extern __imp_SharedAccessResponseListToString:PANYARGS
SharedAccessResponseListToString TEXTEQU <__imp_SharedAccessResponseListToString>
extern __imp_SharedAccessResponseStringToList:PANYARGS
SharedAccessResponseStringToList TEXTEQU <__imp_SharedAccessResponseStringToList>
extern __imp_UnInitializeRAS:PANYARGS
UnInitializeRAS TEXTEQU <__imp_UnInitializeRAS>
