extern __imp_DwTerminalDlg:PANYARGS
DwTerminalDlg TEXTEQU <__imp_DwTerminalDlg>
extern __imp_GetRasDialOutProtocols:PANYARGS
GetRasDialOutProtocols TEXTEQU <__imp_GetRasDialOutProtocols>
extern __imp_RasAutodialDisableDlgA:PANYARGS
RasAutodialDisableDlg  TEXTEQU <__imp_RasAutodialDisableDlgA>
extern __imp_RasAutodialDisableDlgW:PANYARGS
RasAutodialDisableDlgW TEXTEQU <__imp_RasAutodialDisableDlgW>
extern __imp_RasAutodialQueryDlgA:PANYARGS
RasAutodialQueryDlg  TEXTEQU <__imp_RasAutodialQueryDlgA>
extern __imp_RasAutodialQueryDlgW:PANYARGS
RasAutodialQueryDlgW TEXTEQU <__imp_RasAutodialQueryDlgW>
extern __imp_RasDialDlgA:PANYARGS
RasDialDlg  TEXTEQU <__imp_RasDialDlgA>
extern __imp_RasDialDlgW:PANYARGS
RasDialDlgW TEXTEQU <__imp_RasDialDlgW>
extern __imp_RasEntryDlgA:PANYARGS
RasEntryDlg  TEXTEQU <__imp_RasEntryDlgA>
extern __imp_RasEntryDlgW:PANYARGS
RasEntryDlgW TEXTEQU <__imp_RasEntryDlgW>
extern __imp_RasMonitorDlgA:PANYARGS
RasMonitorDlg  TEXTEQU <__imp_RasMonitorDlgA>
extern __imp_RasMonitorDlgW:PANYARGS
RasMonitorDlgW TEXTEQU <__imp_RasMonitorDlgW>
extern __imp_RasPhonebookDlgA:PANYARGS
RasPhonebookDlg  TEXTEQU <__imp_RasPhonebookDlgA>
extern __imp_RasPhonebookDlgW:PANYARGS
RasPhonebookDlgW TEXTEQU <__imp_RasPhonebookDlgW>
extern __imp_RasSrvAddPropPages:PANYARGS
RasSrvAddPropPages TEXTEQU <__imp_RasSrvAddPropPages>
extern __imp_RasSrvAddWizPages:PANYARGS
RasSrvAddWizPages TEXTEQU <__imp_RasSrvAddWizPages>
extern __imp_RasSrvAllowConnectionsConfig:PANYARGS
RasSrvAllowConnectionsConfig TEXTEQU <__imp_RasSrvAllowConnectionsConfig>
extern __imp_RasSrvCleanupService:PANYARGS
RasSrvCleanupService TEXTEQU <__imp_RasSrvCleanupService>
extern __imp_RasSrvEnumConnections:PANYARGS
RasSrvEnumConnections TEXTEQU <__imp_RasSrvEnumConnections>
extern __imp_RasSrvHangupConnection:PANYARGS
RasSrvHangupConnection TEXTEQU <__imp_RasSrvHangupConnection>
extern __imp_RasSrvInitializeService:PANYARGS
RasSrvInitializeService TEXTEQU <__imp_RasSrvInitializeService>
extern __imp_RasSrvIsConnectionConnected:PANYARGS
RasSrvIsConnectionConnected TEXTEQU <__imp_RasSrvIsConnectionConnected>
extern __imp_RasSrvIsICConfigured:PANYARGS
RasSrvIsICConfigured TEXTEQU <__imp_RasSrvIsICConfigured>
extern __imp_RasSrvIsServiceRunning:PANYARGS
RasSrvIsServiceRunning TEXTEQU <__imp_RasSrvIsServiceRunning>
extern __imp_RasSrvQueryShowIcon:PANYARGS
RasSrvQueryShowIcon TEXTEQU <__imp_RasSrvQueryShowIcon>
extern __imp_RasUserEnableManualDial:PANYARGS
RasUserEnableManualDial TEXTEQU <__imp_RasUserEnableManualDial>
extern __imp_RasUserGetManualDial:PANYARGS
RasUserGetManualDial TEXTEQU <__imp_RasUserGetManualDial>
extern __imp_RasUserPrefsDlg:PANYARGS
RasUserPrefsDlg TEXTEQU <__imp_RasUserPrefsDlg>
extern __imp_RasWizCreateNewEntry:PANYARGS
RasWizCreateNewEntry TEXTEQU <__imp_RasWizCreateNewEntry>
extern __imp_RasWizGetNCCFlags:PANYARGS
RasWizGetNCCFlags TEXTEQU <__imp_RasWizGetNCCFlags>
extern __imp_RasWizGetSuggestedEntryName:PANYARGS
RasWizGetSuggestedEntryName TEXTEQU <__imp_RasWizGetSuggestedEntryName>
extern __imp_RasWizGetUserInputConnectionName:PANYARGS
RasWizGetUserInputConnectionName TEXTEQU <__imp_RasWizGetUserInputConnectionName>
extern __imp_RasWizIsEntryRenamable:PANYARGS
RasWizIsEntryRenamable TEXTEQU <__imp_RasWizIsEntryRenamable>
extern __imp_RasWizQueryMaxPageCount:PANYARGS
RasWizQueryMaxPageCount TEXTEQU <__imp_RasWizQueryMaxPageCount>
extern __imp_RasWizSetEntryName:PANYARGS
RasWizSetEntryName TEXTEQU <__imp_RasWizSetEntryName>
extern __imp_RouterEntryDlgA:PANYARGS
RouterEntryDlg  TEXTEQU <__imp_RouterEntryDlgA>
extern __imp_RouterEntryDlgW:PANYARGS
RouterEntryDlgW TEXTEQU <__imp_RouterEntryDlgW>
