extern __imp_DeviceConnect:PANYARGS
DeviceConnect TEXTEQU <__imp_DeviceConnect>
extern __imp_DeviceDone:PANYARGS
DeviceDone TEXTEQU <__imp_DeviceDone>
extern __imp_DeviceEnum:PANYARGS
DeviceEnum TEXTEQU <__imp_DeviceEnum>
extern __imp_DeviceGetInfo:PANYARGS
DeviceGetInfo TEXTEQU <__imp_DeviceGetInfo>
extern __imp_DeviceListen:PANYARGS
DeviceListen TEXTEQU <__imp_DeviceListen>
extern __imp_DeviceSetInfo:PANYARGS
DeviceSetInfo TEXTEQU <__imp_DeviceSetInfo>
extern __imp_DeviceWork:PANYARGS
DeviceWork TEXTEQU <__imp_DeviceWork>
