extern __imp_ServiceMain:PANYARGS
ServiceMain TEXTEQU <__imp_ServiceMain>
extern __imp_ServiceRequestInProcess:PANYARGS
ServiceRequestInProcess TEXTEQU <__imp_ServiceRequestInProcess>
extern __imp_SetEntryDialParams:PANYARGS
SetEntryDialParams TEXTEQU <__imp_SetEntryDialParams>
extern __imp__RasmanEngine:PANYARGS
_RasmanEngine TEXTEQU <__imp__RasmanEngine>
extern __imp__RasmanInit:PANYARGS
_RasmanInit TEXTEQU <__imp__RasmanInit>
