extern __imp_DwRasGetHostByName:PANYARGS
DwRasGetHostByName TEXTEQU <__imp_DwRasGetHostByName>
extern __imp_IsRasmanProcess:PANYARGS
IsRasmanProcess TEXTEQU <__imp_IsRasmanProcess>
extern __imp_RasActivateRoute:PANYARGS
RasActivateRoute TEXTEQU <__imp_RasActivateRoute>
extern __imp_RasActivateRouteEx:PANYARGS
RasActivateRouteEx TEXTEQU <__imp_RasActivateRouteEx>
extern __imp_RasAddConnectionPort:PANYARGS
RasAddConnectionPort TEXTEQU <__imp_RasAddConnectionPort>
extern __imp_RasAddNotification:PANYARGS
RasAddNotification TEXTEQU <__imp_RasAddNotification>
extern __imp_RasAllocateRoute:PANYARGS
RasAllocateRoute TEXTEQU <__imp_RasAllocateRoute>
extern __imp_RasBundleClearStatistics:PANYARGS
RasBundleClearStatistics TEXTEQU <__imp_RasBundleClearStatistics>
extern __imp_RasBundleClearStatisticsEx:PANYARGS
RasBundleClearStatisticsEx TEXTEQU <__imp_RasBundleClearStatisticsEx>
extern __imp_RasBundleGetPort:PANYARGS
RasBundleGetPort TEXTEQU <__imp_RasBundleGetPort>
extern __imp_RasBundleGetStatistics:PANYARGS
RasBundleGetStatistics TEXTEQU <__imp_RasBundleGetStatistics>
extern __imp_RasBundleGetStatisticsEx:PANYARGS
RasBundleGetStatisticsEx TEXTEQU <__imp_RasBundleGetStatisticsEx>
extern __imp_RasCompressionGetInfo:PANYARGS
RasCompressionGetInfo TEXTEQU <__imp_RasCompressionGetInfo>
extern __imp_RasCompressionSetInfo:PANYARGS
RasCompressionSetInfo TEXTEQU <__imp_RasCompressionSetInfo>
extern __imp_RasConnectionEnum:PANYARGS
RasConnectionEnum TEXTEQU <__imp_RasConnectionEnum>
extern __imp_RasConnectionGetStatistics:PANYARGS
RasConnectionGetStatistics TEXTEQU <__imp_RasConnectionGetStatistics>
extern __imp_RasCreateConnection:PANYARGS
RasCreateConnection TEXTEQU <__imp_RasCreateConnection>
extern __imp_RasDeAllocateRoute:PANYARGS
RasDeAllocateRoute TEXTEQU <__imp_RasDeAllocateRoute>
extern __imp_RasDestroyConnection:PANYARGS
RasDestroyConnection TEXTEQU <__imp_RasDestroyConnection>
extern __imp_RasDeviceConnect:PANYARGS
RasDeviceConnect TEXTEQU <__imp_RasDeviceConnect>
extern __imp_RasDeviceEnum:PANYARGS
RasDeviceEnum TEXTEQU <__imp_RasDeviceEnum>
extern __imp_RasDeviceGetInfo:PANYARGS
RasDeviceGetInfo TEXTEQU <__imp_RasDeviceGetInfo>
extern __imp_RasDeviceSetInfo:PANYARGS
RasDeviceSetInfo TEXTEQU <__imp_RasDeviceSetInfo>
extern __imp_RasDoIke:PANYARGS
RasDoIke TEXTEQU <__imp_RasDoIke>
extern __imp_RasEnableIpSec:PANYARGS
RasEnableIpSec TEXTEQU <__imp_RasEnableIpSec>
extern __imp_RasEnumConnectionPorts:PANYARGS
RasEnumConnectionPorts TEXTEQU <__imp_RasEnumConnectionPorts>
extern __imp_RasEnumLanNets:PANYARGS
RasEnumLanNets TEXTEQU <__imp_RasEnumLanNets>
extern __imp_RasFindPrerequisiteEntry:PANYARGS
RasFindPrerequisiteEntry TEXTEQU <__imp_RasFindPrerequisiteEntry>
extern __imp_RasFreeBuffer:PANYARGS
RasFreeBuffer TEXTEQU <__imp_RasFreeBuffer>
extern __imp_RasGetBandwidthUtilization:PANYARGS
RasGetBandwidthUtilization TEXTEQU <__imp_RasGetBandwidthUtilization>
extern __imp_RasGetBestInterface:PANYARGS
RasGetBestInterface TEXTEQU <__imp_RasGetBestInterface>
extern __imp_RasGetBuffer:PANYARGS
RasGetBuffer TEXTEQU <__imp_RasGetBuffer>
extern __imp_RasGetCalledIdInfo:PANYARGS
RasGetCalledIdInfo TEXTEQU <__imp_RasGetCalledIdInfo>
extern __imp_RasGetConnectInfo:PANYARGS
RasGetConnectInfo TEXTEQU <__imp_RasGetConnectInfo>
extern __imp_RasGetConnectionParams:PANYARGS
RasGetConnectionParams TEXTEQU <__imp_RasGetConnectionParams>
extern __imp_RasGetConnectionUserData:PANYARGS
RasGetConnectionUserData TEXTEQU <__imp_RasGetConnectionUserData>
extern __imp_RasGetCustomScriptDll:PANYARGS
RasGetCustomScriptDll TEXTEQU <__imp_RasGetCustomScriptDll>
extern __imp_RasGetDevConfig:PANYARGS
RasGetDevConfig TEXTEQU <__imp_RasGetDevConfig>
extern __imp_RasGetDevConfigEx:PANYARGS
RasGetDevConfigEx TEXTEQU <__imp_RasGetDevConfigEx>
extern __imp_RasGetDeviceConfigInfo:PANYARGS
RasGetDeviceConfigInfo TEXTEQU <__imp_RasGetDeviceConfigInfo>
extern __imp_RasGetDeviceName:PANYARGS
RasGetDeviceName TEXTEQU <__imp_RasGetDeviceName>
extern __imp_RasGetDeviceNameW:PANYARGS
RasGetDeviceNameW TEXTEQU <__imp_RasGetDeviceNameW>
extern __imp_RasGetDialParams:PANYARGS
RasGetDialParams TEXTEQU <__imp_RasGetDialParams>
extern __imp_RasGetEapUserInfo:PANYARGS
RasGetEapUserInfo TEXTEQU <__imp_RasGetEapUserInfo>
extern __imp_RasGetFramingCapabilities:PANYARGS
RasGetFramingCapabilities TEXTEQU <__imp_RasGetFramingCapabilities>
extern __imp_RasGetHConnFromEntry:PANYARGS
RasGetHConnFromEntry TEXTEQU <__imp_RasGetHConnFromEntry>
extern __imp_RasGetHportFromConnection:PANYARGS
RasGetHportFromConnection TEXTEQU <__imp_RasGetHportFromConnection>
extern __imp_RasGetInfo:PANYARGS
RasGetInfo TEXTEQU <__imp_RasGetInfo>
extern __imp_RasGetInfoEx:PANYARGS
RasGetInfoEx TEXTEQU <__imp_RasGetInfoEx>
extern __imp_RasGetKey:PANYARGS
RasGetKey TEXTEQU <__imp_RasGetKey>
extern __imp_RasGetNdiswanDriverCaps:PANYARGS
RasGetNdiswanDriverCaps TEXTEQU <__imp_RasGetNdiswanDriverCaps>
extern __imp_RasGetNumPortOpen:PANYARGS
RasGetNumPortOpen TEXTEQU <__imp_RasGetNumPortOpen>
extern __imp_RasGetPortUserData:PANYARGS
RasGetPortUserData TEXTEQU <__imp_RasGetPortUserData>
extern __imp_RasGetProtocolInfo:PANYARGS
RasGetProtocolInfo TEXTEQU <__imp_RasGetProtocolInfo>
extern __imp_RasGetTimeSinceLastActivity:PANYARGS
RasGetTimeSinceLastActivity TEXTEQU <__imp_RasGetTimeSinceLastActivity>
extern __imp_RasGetUnicodeDeviceName:PANYARGS
RasGetUnicodeDeviceName TEXTEQU <__imp_RasGetUnicodeDeviceName>
extern __imp_RasGetUserCredentials:PANYARGS
RasGetUserCredentials TEXTEQU <__imp_RasGetUserCredentials>
extern __imp_RasInitialize:PANYARGS
RasInitialize TEXTEQU <__imp_RasInitialize>
extern __imp_RasInitializeNoWait:PANYARGS
RasInitializeNoWait TEXTEQU <__imp_RasInitializeNoWait>
extern __imp_RasIsIpSecEnabled:PANYARGS
RasIsIpSecEnabled TEXTEQU <__imp_RasIsIpSecEnabled>
extern __imp_RasIsPulseDial:PANYARGS
RasIsPulseDial TEXTEQU <__imp_RasIsPulseDial>
extern __imp_RasIsTrustedCustomDll:PANYARGS
RasIsTrustedCustomDll TEXTEQU <__imp_RasIsTrustedCustomDll>
extern __imp_RasLinkGetStatistics:PANYARGS
RasLinkGetStatistics TEXTEQU <__imp_RasLinkGetStatistics>
extern __imp_RasPnPControl:PANYARGS
RasPnPControl TEXTEQU <__imp_RasPnPControl>
extern __imp_RasPortBundle:PANYARGS
RasPortBundle TEXTEQU <__imp_RasPortBundle>
extern __imp_RasPortCancelReceive:PANYARGS
RasPortCancelReceive TEXTEQU <__imp_RasPortCancelReceive>
extern __imp_RasPortClearStatistics:PANYARGS
RasPortClearStatistics TEXTEQU <__imp_RasPortClearStatistics>
extern __imp_RasPortClose:PANYARGS
RasPortClose TEXTEQU <__imp_RasPortClose>
extern __imp_RasPortConnectComplete:PANYARGS
RasPortConnectComplete TEXTEQU <__imp_RasPortConnectComplete>
extern __imp_RasPortDisconnect:PANYARGS
RasPortDisconnect TEXTEQU <__imp_RasPortDisconnect>
extern __imp_RasPortEnum:PANYARGS
RasPortEnum TEXTEQU <__imp_RasPortEnum>
extern __imp_RasPortEnumProtocols:PANYARGS
RasPortEnumProtocols TEXTEQU <__imp_RasPortEnumProtocols>
extern __imp_RasPortFree:PANYARGS
RasPortFree TEXTEQU <__imp_RasPortFree>
extern __imp_RasPortGetBundle:PANYARGS
RasPortGetBundle TEXTEQU <__imp_RasPortGetBundle>
extern __imp_RasPortGetBundledPort:PANYARGS
RasPortGetBundledPort TEXTEQU <__imp_RasPortGetBundledPort>
extern __imp_RasPortGetFramingEx:PANYARGS
RasPortGetFramingEx TEXTEQU <__imp_RasPortGetFramingEx>
extern __imp_RasPortGetInfo:PANYARGS
RasPortGetInfo TEXTEQU <__imp_RasPortGetInfo>
extern __imp_RasPortGetProtocolCompression:PANYARGS
RasPortGetProtocolCompression TEXTEQU <__imp_RasPortGetProtocolCompression>
extern __imp_RasPortGetStatistics:PANYARGS
RasPortGetStatistics TEXTEQU <__imp_RasPortGetStatistics>
extern __imp_RasPortGetStatisticsEx:PANYARGS
RasPortGetStatisticsEx TEXTEQU <__imp_RasPortGetStatisticsEx>
extern __imp_RasPortListen:PANYARGS
RasPortListen TEXTEQU <__imp_RasPortListen>
extern __imp_RasPortOpen:PANYARGS
RasPortOpen TEXTEQU <__imp_RasPortOpen>
extern __imp_RasPortOpenEx:PANYARGS
RasPortOpenEx TEXTEQU <__imp_RasPortOpenEx>
extern __imp_RasPortReceive:PANYARGS
RasPortReceive TEXTEQU <__imp_RasPortReceive>
extern __imp_RasPortReceiveEx:PANYARGS
RasPortReceiveEx TEXTEQU <__imp_RasPortReceiveEx>
extern __imp_RasPortRegisterSlip:PANYARGS
RasPortRegisterSlip TEXTEQU <__imp_RasPortRegisterSlip>
extern __imp_RasPortReserve:PANYARGS
RasPortReserve TEXTEQU <__imp_RasPortReserve>
extern __imp_RasPortRetrieveUserData:PANYARGS
RasPortRetrieveUserData TEXTEQU <__imp_RasPortRetrieveUserData>
extern __imp_RasPortSend:PANYARGS
RasPortSend TEXTEQU <__imp_RasPortSend>
extern __imp_RasPortSetFraming:PANYARGS
RasPortSetFraming TEXTEQU <__imp_RasPortSetFraming>
extern __imp_RasPortSetFramingEx:PANYARGS
RasPortSetFramingEx TEXTEQU <__imp_RasPortSetFramingEx>
extern __imp_RasPortSetInfo:PANYARGS
RasPortSetInfo TEXTEQU <__imp_RasPortSetInfo>
extern __imp_RasPortSetProtocolCompression:PANYARGS
RasPortSetProtocolCompression TEXTEQU <__imp_RasPortSetProtocolCompression>
extern __imp_RasPortStoreUserData:PANYARGS
RasPortStoreUserData TEXTEQU <__imp_RasPortStoreUserData>
extern __imp_RasPppCallback:PANYARGS
RasPppCallback TEXTEQU <__imp_RasPppCallback>
extern __imp_RasPppChangePassword:PANYARGS
RasPppChangePassword TEXTEQU <__imp_RasPppChangePassword>
extern __imp_RasPppGetEapInfo:PANYARGS
RasPppGetEapInfo TEXTEQU <__imp_RasPppGetEapInfo>
extern __imp_RasPppGetInfo:PANYARGS
RasPppGetInfo TEXTEQU <__imp_RasPppGetInfo>
extern __imp_RasPppRetry:PANYARGS
RasPppRetry TEXTEQU <__imp_RasPppRetry>
extern __imp_RasPppSetEapInfo:PANYARGS
RasPppSetEapInfo TEXTEQU <__imp_RasPppSetEapInfo>
extern __imp_RasPppStart:PANYARGS
RasPppStart TEXTEQU <__imp_RasPppStart>
extern __imp_RasPppStarted:PANYARGS
RasPppStarted TEXTEQU <__imp_RasPppStarted>
extern __imp_RasPppStop:PANYARGS
RasPppStop TEXTEQU <__imp_RasPppStop>
extern __imp_RasProtocolEnum:PANYARGS
RasProtocolEnum TEXTEQU <__imp_RasProtocolEnum>
extern __imp_RasRPCBind:PANYARGS
RasRPCBind TEXTEQU <__imp_RasRPCBind>
extern __imp_RasRefConnection:PANYARGS
RasRefConnection TEXTEQU <__imp_RasRefConnection>
extern __imp_RasReferenceCustomCount:PANYARGS
RasReferenceCustomCount TEXTEQU <__imp_RasReferenceCustomCount>
extern __imp_RasReferenceRasman:PANYARGS
RasReferenceRasman TEXTEQU <__imp_RasReferenceRasman>
extern __imp_RasRegisterPnPEvent:PANYARGS
RasRegisterPnPEvent TEXTEQU <__imp_RasRegisterPnPEvent>
extern __imp_RasRegisterPnPHandler:PANYARGS
RasRegisterPnPHandler TEXTEQU <__imp_RasRegisterPnPHandler>
extern __imp_RasRegisterRedialCallback:PANYARGS
RasRegisterRedialCallback TEXTEQU <__imp_RasRegisterRedialCallback>
extern __imp_RasRequestNotification:PANYARGS
RasRequestNotification TEXTEQU <__imp_RasRequestNotification>
extern __imp_RasRpcConnect:PANYARGS
RasRpcConnect TEXTEQU <__imp_RasRpcConnect>
extern __imp_RasRpcConnectServer:PANYARGS
RasRpcConnectServer TEXTEQU <__imp_RasRpcConnectServer>
extern __imp_RasRpcDeleteEntry:PANYARGS
RasRpcDeleteEntry TEXTEQU <__imp_RasRpcDeleteEntry>
extern __imp_RasRpcDeviceEnum:PANYARGS
RasRpcDeviceEnum TEXTEQU <__imp_RasRpcDeviceEnum>
extern __imp_RasRpcDisconnect:PANYARGS
RasRpcDisconnect TEXTEQU <__imp_RasRpcDisconnect>
extern __imp_RasRpcDisconnectServer:PANYARGS
RasRpcDisconnectServer TEXTEQU <__imp_RasRpcDisconnectServer>
extern __imp_RasRpcEnumConnections:PANYARGS
RasRpcEnumConnections TEXTEQU <__imp_RasRpcEnumConnections>
extern __imp_RasRpcGetCountryInfo:PANYARGS
RasRpcGetCountryInfo TEXTEQU <__imp_RasRpcGetCountryInfo>
extern __imp_RasRpcGetDevConfig:PANYARGS
RasRpcGetDevConfig TEXTEQU <__imp_RasRpcGetDevConfig>
extern __imp_RasRpcGetErrorString:PANYARGS
RasRpcGetErrorString TEXTEQU <__imp_RasRpcGetErrorString>
extern __imp_RasRpcGetInstalledProtocols:PANYARGS
RasRpcGetInstalledProtocols TEXTEQU <__imp_RasRpcGetInstalledProtocols>
extern __imp_RasRpcGetInstalledProtocolsEx:PANYARGS
RasRpcGetInstalledProtocolsEx TEXTEQU <__imp_RasRpcGetInstalledProtocolsEx>
extern __imp_RasRpcGetSystemDirectory:PANYARGS
RasRpcGetSystemDirectory TEXTEQU <__imp_RasRpcGetSystemDirectory>
extern __imp_RasRpcGetUserPreferences:PANYARGS
RasRpcGetUserPreferences TEXTEQU <__imp_RasRpcGetUserPreferences>
extern __imp_RasRpcGetVersion:PANYARGS
RasRpcGetVersion TEXTEQU <__imp_RasRpcGetVersion>
extern __imp_RasRpcPortEnum:PANYARGS
RasRpcPortEnum TEXTEQU <__imp_RasRpcPortEnum>
extern __imp_RasRpcPortGetInfo:PANYARGS
RasRpcPortGetInfo TEXTEQU <__imp_RasRpcPortGetInfo>
extern __imp_RasRpcRemoteGetSystemDirectory:PANYARGS
RasRpcRemoteGetSystemDirectory TEXTEQU <__imp_RasRpcRemoteGetSystemDirectory>
extern __imp_RasRpcRemoteGetUserPreferences:PANYARGS
RasRpcRemoteGetUserPreferences TEXTEQU <__imp_RasRpcRemoteGetUserPreferences>
extern __imp_RasRpcRemoteRasDeleteEntry:PANYARGS
RasRpcRemoteRasDeleteEntry TEXTEQU <__imp_RasRpcRemoteRasDeleteEntry>
extern __imp_RasRpcRemoteSetUserPreferences:PANYARGS
RasRpcRemoteSetUserPreferences TEXTEQU <__imp_RasRpcRemoteSetUserPreferences>
extern __imp_RasRpcSetUserPreferences:PANYARGS
RasRpcSetUserPreferences TEXTEQU <__imp_RasRpcSetUserPreferences>
extern __imp_RasRpcUnloadDll:PANYARGS
RasRpcUnloadDll TEXTEQU <__imp_RasRpcUnloadDll>
extern __imp_RasSecurityDialogGetInfo:PANYARGS
RasSecurityDialogGetInfo TEXTEQU <__imp_RasSecurityDialogGetInfo>
extern __imp_RasSecurityDialogReceive:PANYARGS
RasSecurityDialogReceive TEXTEQU <__imp_RasSecurityDialogReceive>
extern __imp_RasSecurityDialogSend:PANYARGS
RasSecurityDialogSend TEXTEQU <__imp_RasSecurityDialogSend>
extern __imp_RasSendCreds:PANYARGS
RasSendCreds TEXTEQU <__imp_RasSendCreds>
extern __imp_RasSendNotification:PANYARGS
RasSendNotification TEXTEQU <__imp_RasSendNotification>
extern __imp_RasSendPppMessageToRasman:PANYARGS
RasSendPppMessageToRasman TEXTEQU <__imp_RasSendPppMessageToRasman>
extern __imp_RasServerPortClose:PANYARGS
RasServerPortClose TEXTEQU <__imp_RasServerPortClose>
extern __imp_RasSetAddressDisable:PANYARGS
RasSetAddressDisable TEXTEQU <__imp_RasSetAddressDisable>
extern __imp_RasSetBapPolicy:PANYARGS
RasSetBapPolicy TEXTEQU <__imp_RasSetBapPolicy>
extern __imp_RasSetCachedCredentials:PANYARGS
RasSetCachedCredentials TEXTEQU <__imp_RasSetCachedCredentials>
extern __imp_RasSetCalledIdInfo:PANYARGS
RasSetCalledIdInfo TEXTEQU <__imp_RasSetCalledIdInfo>
extern __imp_RasSetCommSettings:PANYARGS
RasSetCommSettings TEXTEQU <__imp_RasSetCommSettings>
extern __imp_RasSetConnectionParams:PANYARGS
RasSetConnectionParams TEXTEQU <__imp_RasSetConnectionParams>
extern __imp_RasSetConnectionUserData:PANYARGS
RasSetConnectionUserData TEXTEQU <__imp_RasSetConnectionUserData>
extern __imp_RasSetDevConfig:PANYARGS
RasSetDevConfig TEXTEQU <__imp_RasSetDevConfig>
extern __imp_RasSetDeviceConfigInfo:PANYARGS
RasSetDeviceConfigInfo TEXTEQU <__imp_RasSetDeviceConfigInfo>
extern __imp_RasSetDialParams:PANYARGS
RasSetDialParams TEXTEQU <__imp_RasSetDialParams>
extern __imp_RasSetEapLogonInfo:PANYARGS
RasSetEapLogonInfo TEXTEQU <__imp_RasSetEapLogonInfo>
extern __imp_RasSetEapUserInfo:PANYARGS
RasSetEapUserInfo TEXTEQU <__imp_RasSetEapUserInfo>
extern __imp_RasSetIoCompletionPort:PANYARGS
RasSetIoCompletionPort TEXTEQU <__imp_RasSetIoCompletionPort>
extern __imp_RasSetKey:PANYARGS
RasSetKey TEXTEQU <__imp_RasSetKey>
extern __imp_RasSetPortUserData:PANYARGS
RasSetPortUserData TEXTEQU <__imp_RasSetPortUserData>
extern __imp_RasSetRasdialInfo:PANYARGS
RasSetRasdialInfo TEXTEQU <__imp_RasSetRasdialInfo>
extern __imp_RasSetRouterUsage:PANYARGS
RasSetRouterUsage TEXTEQU <__imp_RasSetRouterUsage>
extern __imp_RasSignalNewConnection:PANYARGS
RasSignalNewConnection TEXTEQU <__imp_RasSignalNewConnection>
extern __imp_RasStartRasAutoIfRequired:PANYARGS
RasStartRasAutoIfRequired TEXTEQU <__imp_RasStartRasAutoIfRequired>
extern __imp_RasmanUninitialize:PANYARGS
RasmanUninitialize TEXTEQU <__imp_RasmanUninitialize>
