extern __imp_GetDiagnosticFunctions:PANYARGS
GetDiagnosticFunctions TEXTEQU <__imp_GetDiagnosticFunctions>
extern __imp_InitHelperDll:PANYARGS
InitHelperDll TEXTEQU <__imp_InitHelperDll>
extern __imp_RutlAlloc:PANYARGS
RutlAlloc TEXTEQU <__imp_RutlAlloc>
extern __imp_RutlAssignmentFromTokenAndDword:PANYARGS
RutlAssignmentFromTokenAndDword TEXTEQU <__imp_RutlAssignmentFromTokenAndDword>
extern __imp_RutlAssignmentFromTokens:PANYARGS
RutlAssignmentFromTokens TEXTEQU <__imp_RutlAssignmentFromTokens>
extern __imp_RutlCloseDumpFile:PANYARGS
RutlCloseDumpFile TEXTEQU <__imp_RutlCloseDumpFile>
extern __imp_RutlCreateDumpFile:PANYARGS
RutlCreateDumpFile TEXTEQU <__imp_RutlCreateDumpFile>
extern __imp_RutlDwordDup:PANYARGS
RutlDwordDup TEXTEQU <__imp_RutlDwordDup>
extern __imp_RutlFree:PANYARGS
RutlFree TEXTEQU <__imp_RutlFree>
extern __imp_RutlGetOsVersion:PANYARGS
RutlGetOsVersion TEXTEQU <__imp_RutlGetOsVersion>
extern __imp_RutlGetTagToken:PANYARGS
RutlGetTagToken TEXTEQU <__imp_RutlGetTagToken>
extern __imp_RutlIsHelpToken:PANYARGS
RutlIsHelpToken TEXTEQU <__imp_RutlIsHelpToken>
extern __imp_RutlParse:PANYARGS
RutlParse TEXTEQU <__imp_RutlParse>
extern __imp_RutlStrDup:PANYARGS
RutlStrDup TEXTEQU <__imp_RutlStrDup>
