extern __imp_HelperResetDefaultInterfaceNet:PANYARGS
HelperResetDefaultInterfaceNet TEXTEQU <__imp_HelperResetDefaultInterfaceNet>
extern __imp_HelperResetDefaultInterfaceNetEx:PANYARGS
HelperResetDefaultInterfaceNetEx TEXTEQU <__imp_HelperResetDefaultInterfaceNetEx>
extern __imp_HelperSetDefaultInterfaceNet:PANYARGS
HelperSetDefaultInterfaceNet TEXTEQU <__imp_HelperSetDefaultInterfaceNet>
extern __imp_HelperSetDefaultInterfaceNetEx:PANYARGS
HelperSetDefaultInterfaceNetEx TEXTEQU <__imp_HelperSetDefaultInterfaceNetEx>
extern __imp_IpxCpInit:PANYARGS
IpxCpInit TEXTEQU <__imp_IpxCpInit>
extern __imp_IpxcpBind:PANYARGS
IpxcpBind TEXTEQU <__imp_IpxcpBind>
extern __imp_PppDdmBapCallbackResult:PANYARGS
PppDdmBapCallbackResult TEXTEQU <__imp_PppDdmBapCallbackResult>
extern __imp_PppDdmCallbackDone:PANYARGS
PppDdmCallbackDone TEXTEQU <__imp_PppDdmCallbackDone>
extern __imp_PppDdmChangeNotification:PANYARGS
PppDdmChangeNotification TEXTEQU <__imp_PppDdmChangeNotification>
extern __imp_PppDdmDeInit:PANYARGS
PppDdmDeInit TEXTEQU <__imp_PppDdmDeInit>
extern __imp_PppDdmInit:PANYARGS
PppDdmInit TEXTEQU <__imp_PppDdmInit>
extern __imp_PppDdmRemoveQuarantine:PANYARGS
PppDdmRemoveQuarantine TEXTEQU <__imp_PppDdmRemoveQuarantine>
extern __imp_PppDdmSendInterfaceInfo:PANYARGS
PppDdmSendInterfaceInfo TEXTEQU <__imp_PppDdmSendInterfaceInfo>
extern __imp_PppDdmStart:PANYARGS
PppDdmStart TEXTEQU <__imp_PppDdmStart>
extern __imp_PppDdmStop:PANYARGS
PppDdmStop TEXTEQU <__imp_PppDdmStop>
extern __imp_PppStop:PANYARGS
PppStop TEXTEQU <__imp_PppStop>
extern __imp_RasCpEnumProtocolIds:PANYARGS
RasCpEnumProtocolIds TEXTEQU <__imp_RasCpEnumProtocolIds>
extern __imp_RasCpGetInfo:PANYARGS
RasCpGetInfo TEXTEQU <__imp_RasCpGetInfo>
extern __imp_RasSrvrAcquireAddress:PANYARGS
RasSrvrAcquireAddress TEXTEQU <__imp_RasSrvrAcquireAddress>
extern __imp_RasSrvrActivateIp:PANYARGS
RasSrvrActivateIp TEXTEQU <__imp_RasSrvrActivateIp>
extern __imp_RasSrvrInitialize:PANYARGS
RasSrvrInitialize TEXTEQU <__imp_RasSrvrInitialize>
extern __imp_RasSrvrQueryServerAddresses:PANYARGS
RasSrvrQueryServerAddresses TEXTEQU <__imp_RasSrvrQueryServerAddresses>
extern __imp_RasSrvrReleaseAddress:PANYARGS
RasSrvrReleaseAddress TEXTEQU <__imp_RasSrvrReleaseAddress>
extern __imp_RasSrvrUninitialize:PANYARGS
RasSrvrUninitialize TEXTEQU <__imp_RasSrvrUninitialize>
extern __imp_SendPPPMessageToEngine:PANYARGS
SendPPPMessageToEngine TEXTEQU <__imp_SendPPPMessageToEngine>
extern __imp_StartPPP:PANYARGS
StartPPP TEXTEQU <__imp_StartPPP>
extern __imp_StopPPP:PANYARGS
StopPPP TEXTEQU <__imp_StopPPP>
