extern __imp_PortChangeCallback:PANYARGS
PortChangeCallback TEXTEQU <__imp_PortChangeCallback>
extern __imp_PortClearStatistics:PANYARGS
PortClearStatistics TEXTEQU <__imp_PortClearStatistics>
extern __imp_PortClose:PANYARGS
PortClose TEXTEQU <__imp_PortClose>
extern __imp_PortCompressionSetInfo:PANYARGS
PortCompressionSetInfo TEXTEQU <__imp_PortCompressionSetInfo>
extern __imp_PortConnect:PANYARGS
PortConnect TEXTEQU <__imp_PortConnect>
extern __imp_PortDisconnect:PANYARGS
PortDisconnect TEXTEQU <__imp_PortDisconnect>
extern __imp_PortEnum:PANYARGS
PortEnum TEXTEQU <__imp_PortEnum>
extern __imp_PortGetInfo:PANYARGS
PortGetInfo TEXTEQU <__imp_PortGetInfo>
extern __imp_PortGetPortState:PANYARGS
PortGetPortState TEXTEQU <__imp_PortGetPortState>
extern __imp_PortGetStatistics:PANYARGS
PortGetStatistics TEXTEQU <__imp_PortGetStatistics>
extern __imp_PortInit:PANYARGS
PortInit TEXTEQU <__imp_PortInit>
extern __imp_PortOpen:PANYARGS
PortOpen TEXTEQU <__imp_PortOpen>
extern __imp_PortReceive:PANYARGS
PortReceive TEXTEQU <__imp_PortReceive>
extern __imp_PortReceiveComplete:PANYARGS
PortReceiveComplete TEXTEQU <__imp_PortReceiveComplete>
extern __imp_PortSend:PANYARGS
PortSend TEXTEQU <__imp_PortSend>
extern __imp_PortSetFraming:PANYARGS
PortSetFraming TEXTEQU <__imp_PortSetFraming>
extern __imp_PortSetINetCfg:PANYARGS
PortSetINetCfg TEXTEQU <__imp_PortSetINetCfg>
extern __imp_PortSetInfo:PANYARGS
PortSetInfo TEXTEQU <__imp_PortSetInfo>
extern __imp_PortTestSignalState:PANYARGS
PortTestSignalState TEXTEQU <__imp_PortTestSignalState>
