extern __imp_AddPorts:PANYARGS
AddPorts TEXTEQU <__imp_AddPorts>
extern __imp_DeviceConnect:PANYARGS
DeviceConnect TEXTEQU <__imp_DeviceConnect>
extern __imp_DeviceDone:PANYARGS
DeviceDone TEXTEQU <__imp_DeviceDone>
extern __imp_DeviceEnum:PANYARGS
DeviceEnum TEXTEQU <__imp_DeviceEnum>
extern __imp_DeviceGetDevConfig:PANYARGS
DeviceGetDevConfig TEXTEQU <__imp_DeviceGetDevConfig>
extern __imp_DeviceGetDevConfigEx:PANYARGS
DeviceGetDevConfigEx TEXTEQU <__imp_DeviceGetDevConfigEx>
extern __imp_DeviceGetInfo:PANYARGS
DeviceGetInfo TEXTEQU <__imp_DeviceGetInfo>
extern __imp_DeviceListen:PANYARGS
DeviceListen TEXTEQU <__imp_DeviceListen>
extern __imp_DeviceSetDevConfig:PANYARGS
DeviceSetDevConfig TEXTEQU <__imp_DeviceSetDevConfig>
extern __imp_DeviceSetInfo:PANYARGS
DeviceSetInfo TEXTEQU <__imp_DeviceSetInfo>
extern __imp_DeviceWork:PANYARGS
DeviceWork TEXTEQU <__imp_DeviceWork>
extern __imp_EnableDeviceForDialIn:PANYARGS
EnableDeviceForDialIn TEXTEQU <__imp_EnableDeviceForDialIn>
extern __imp_GetConnectInfo:PANYARGS
GetConnectInfo TEXTEQU <__imp_GetConnectInfo>
extern __imp_GetZeroDeviceInfo:PANYARGS
GetZeroDeviceInfo TEXTEQU <__imp_GetZeroDeviceInfo>
extern __imp_PortChangeCallback:PANYARGS
PortChangeCallback TEXTEQU <__imp_PortChangeCallback>
extern __imp_PortClearStatistics:PANYARGS
PortClearStatistics TEXTEQU <__imp_PortClearStatistics>
extern __imp_PortClose:PANYARGS
PortClose TEXTEQU <__imp_PortClose>
extern __imp_PortCompressionSetInfo:PANYARGS
PortCompressionSetInfo TEXTEQU <__imp_PortCompressionSetInfo>
extern __imp_PortConnect:PANYARGS
PortConnect TEXTEQU <__imp_PortConnect>
extern __imp_PortDisconnect:PANYARGS
PortDisconnect TEXTEQU <__imp_PortDisconnect>
extern __imp_PortEnum:PANYARGS
PortEnum TEXTEQU <__imp_PortEnum>
extern __imp_PortGetIOHandle:PANYARGS
PortGetIOHandle TEXTEQU <__imp_PortGetIOHandle>
extern __imp_PortGetInfo:PANYARGS
PortGetInfo TEXTEQU <__imp_PortGetInfo>
extern __imp_PortGetPortState:PANYARGS
PortGetPortState TEXTEQU <__imp_PortGetPortState>
extern __imp_PortGetStatistics:PANYARGS
PortGetStatistics TEXTEQU <__imp_PortGetStatistics>
extern __imp_PortInit:PANYARGS
PortInit TEXTEQU <__imp_PortInit>
extern __imp_PortOpen:PANYARGS
PortOpen TEXTEQU <__imp_PortOpen>
extern __imp_PortOpenExternal:PANYARGS
PortOpenExternal TEXTEQU <__imp_PortOpenExternal>
extern __imp_PortReceive:PANYARGS
PortReceive TEXTEQU <__imp_PortReceive>
extern __imp_PortReceiveComplete:PANYARGS
PortReceiveComplete TEXTEQU <__imp_PortReceiveComplete>
extern __imp_PortSend:PANYARGS
PortSend TEXTEQU <__imp_PortSend>
extern __imp_PortSetFraming:PANYARGS
PortSetFraming TEXTEQU <__imp_PortSetFraming>
extern __imp_PortSetInfo:PANYARGS
PortSetInfo TEXTEQU <__imp_PortSetInfo>
extern __imp_PortSetIoCompletionPort:PANYARGS
PortSetIoCompletionPort TEXTEQU <__imp_PortSetIoCompletionPort>
extern __imp_PortTestSignalState:PANYARGS
PortTestSignalState TEXTEQU <__imp_PortTestSignalState>
extern __imp_RasTapiIsPulseDial:PANYARGS
RasTapiIsPulseDial TEXTEQU <__imp_RasTapiIsPulseDial>
extern __imp_RastapiGetCalledID:PANYARGS
RastapiGetCalledID TEXTEQU <__imp_RastapiGetCalledID>
extern __imp_RastapiSetCalledID:PANYARGS
RastapiSetCalledID TEXTEQU <__imp_RastapiSetCalledID>
extern __imp_RemovePort:PANYARGS
RemovePort TEXTEQU <__imp_RemovePort>
extern __imp_SetCommSettings:PANYARGS
SetCommSettings TEXTEQU <__imp_SetCommSettings>
extern __imp_UnloadRastapiDll:PANYARGS
UnloadRastapiDll TEXTEQU <__imp_UnloadRastapiDll>
