extern __imp_DriverProc:PANYARGS
DriverProc TEXTEQU <__imp_DriverProc>
extern __imp_auxMessage:PANYARGS
auxMessage TEXTEQU <__imp_auxMessage>
extern __imp_midMessage:PANYARGS
midMessage TEXTEQU <__imp_midMessage>
extern __imp_modMessage:PANYARGS
modMessage TEXTEQU <__imp_modMessage>
extern __imp_mxdMessage:PANYARGS
mxdMessage TEXTEQU <__imp_mxdMessage>
extern __imp_widMessage:PANYARGS
widMessage TEXTEQU <__imp_widMessage>
extern __imp_wodMessage:PANYARGS
wodMessage TEXTEQU <__imp_wodMessage>
