extern __imp_WsxBrokenConnection:PANYARGS
WsxBrokenConnection TEXTEQU <__imp_WsxBrokenConnection>
extern __imp_WsxCanLogonProceed:PANYARGS
WsxCanLogonProceed TEXTEQU <__imp_WsxCanLogonProceed>
extern __imp_WsxClearContext:PANYARGS
WsxClearContext TEXTEQU <__imp_WsxClearContext>
extern __imp_WsxConnect:PANYARGS
WsxConnect TEXTEQU <__imp_WsxConnect>
extern __imp_WsxConvertPublishedApp:PANYARGS
WsxConvertPublishedApp TEXTEQU <__imp_WsxConvertPublishedApp>
extern __imp_WsxCopyContext:PANYARGS
WsxCopyContext TEXTEQU <__imp_WsxCopyContext>
extern __imp_WsxDisconnect:PANYARGS
WsxDisconnect TEXTEQU <__imp_WsxDisconnect>
extern __imp_WsxDuplicateContext:PANYARGS
WsxDuplicateContext TEXTEQU <__imp_WsxDuplicateContext>
extern __imp_WsxEscape:PANYARGS
WsxEscape TEXTEQU <__imp_WsxEscape>
extern __imp_WsxIcaStackIoControl:PANYARGS
WsxIcaStackIoControl TEXTEQU <__imp_WsxIcaStackIoControl>
extern __imp_WsxInitialize:PANYARGS
WsxInitialize TEXTEQU <__imp_WsxInitialize>
extern __imp_WsxInitializeClientData:PANYARGS
WsxInitializeClientData TEXTEQU <__imp_WsxInitializeClientData>
extern __imp_WsxLogonNotify:PANYARGS
WsxLogonNotify TEXTEQU <__imp_WsxLogonNotify>
extern __imp_WsxSendAutoReconnectStatus:PANYARGS
WsxSendAutoReconnectStatus TEXTEQU <__imp_WsxSendAutoReconnectStatus>
extern __imp_WsxSetErrorInfo:PANYARGS
WsxSetErrorInfo TEXTEQU <__imp_WsxSetErrorInfo>
extern __imp_WsxVirtualChannelSecurity:PANYARGS
WsxVirtualChannelSecurity TEXTEQU <__imp_WsxVirtualChannelSecurity>
extern __imp_WsxWinStationInitialize:PANYARGS
WsxWinStationInitialize TEXTEQU <__imp_WsxWinStationInitialize>
extern __imp_WsxWinStationReInitialize:PANYARGS
WsxWinStationReInitialize TEXTEQU <__imp_WsxWinStationReInitialize>
extern __imp_WsxWinStationRundown:PANYARGS
WsxWinStationRundown TEXTEQU <__imp_WsxWinStationRundown>
