extern __imp_GetDomainName:PANYARGS
GetDomainName TEXTEQU <__imp_GetDomainName>
extern __imp_QueryUserProperty:PANYARGS
QueryUserProperty TEXTEQU <__imp_QueryUserProperty>
extern __imp_RegBuildNumberQuery:PANYARGS
RegBuildNumberQuery TEXTEQU <__imp_RegBuildNumberQuery>
extern __imp_RegCdCreateA:PANYARGS
RegCdCreate  TEXTEQU <__imp_RegCdCreateA>
extern __imp_RegCdCreateW:PANYARGS
RegCdCreateW TEXTEQU <__imp_RegCdCreateW>
extern __imp_RegCdDeleteA:PANYARGS
RegCdDelete  TEXTEQU <__imp_RegCdDeleteA>
extern __imp_RegCdDeleteW:PANYARGS
RegCdDeleteW TEXTEQU <__imp_RegCdDeleteW>
extern __imp_RegCdEnumerateA:PANYARGS
RegCdEnumerate  TEXTEQU <__imp_RegCdEnumerateA>
extern __imp_RegCdEnumerateW:PANYARGS
RegCdEnumerateW TEXTEQU <__imp_RegCdEnumerateW>
extern __imp_RegCdQueryA:PANYARGS
RegCdQuery  TEXTEQU <__imp_RegCdQueryA>
extern __imp_RegCdQueryW:PANYARGS
RegCdQueryW TEXTEQU <__imp_RegCdQueryW>
extern __imp_RegCloseServer:PANYARGS
RegCloseServer TEXTEQU <__imp_RegCloseServer>
extern __imp_RegConsoleShadowQueryA:PANYARGS
RegConsoleShadowQuery  TEXTEQU <__imp_RegConsoleShadowQueryA>
extern __imp_RegConsoleShadowQueryW:PANYARGS
RegConsoleShadowQueryW TEXTEQU <__imp_RegConsoleShadowQueryW>
extern __imp_RegCreateUserConfigW:PANYARGS
RegCreateUserConfigW TEXTEQU <__imp_RegCreateUserConfigW>
extern __imp_RegDefaultUserConfigQueryA:PANYARGS
RegDefaultUserConfigQuery  TEXTEQU <__imp_RegDefaultUserConfigQueryA>
extern __imp_RegDefaultUserConfigQueryW:PANYARGS
RegDefaultUserConfigQueryW TEXTEQU <__imp_RegDefaultUserConfigQueryW>
extern __imp_RegDenyTSConnectionsPolicy:PANYARGS
RegDenyTSConnectionsPolicy TEXTEQU <__imp_RegDenyTSConnectionsPolicy>
extern __imp_RegFreeUtilityCommandList:PANYARGS
RegFreeUtilityCommandList TEXTEQU <__imp_RegFreeUtilityCommandList>
extern __imp_RegGetLicensingModePolicy:PANYARGS
RegGetLicensingModePolicy TEXTEQU <__imp_RegGetLicensingModePolicy>
extern __imp_RegGetMachinePolicy:PANYARGS
RegGetMachinePolicy TEXTEQU <__imp_RegGetMachinePolicy>
extern __imp_RegGetMachinePolicyEx:PANYARGS
RegGetMachinePolicyEx TEXTEQU <__imp_RegGetMachinePolicyEx>
extern __imp_RegGetMachinePolicyNew:PANYARGS
RegGetMachinePolicyNew TEXTEQU <__imp_RegGetMachinePolicyNew>
extern __imp_RegGetTServerVersion:PANYARGS
RegGetTServerVersion TEXTEQU <__imp_RegGetTServerVersion>
extern __imp_RegGetUserConfigFromUserParameters:PANYARGS
RegGetUserConfigFromUserParameters TEXTEQU <__imp_RegGetUserConfigFromUserParameters>
extern __imp_RegGetUserPolicy:PANYARGS
RegGetUserPolicy TEXTEQU <__imp_RegGetUserPolicy>
extern __imp_RegIsMachineInHelpMode:PANYARGS
RegIsMachineInHelpMode TEXTEQU <__imp_RegIsMachineInHelpMode>
extern __imp_RegIsMachinePolicyAllowHelp:PANYARGS
RegIsMachinePolicyAllowHelp TEXTEQU <__imp_RegIsMachinePolicyAllowHelp>
extern __imp_RegIsTServer:PANYARGS
RegIsTServer TEXTEQU <__imp_RegIsTServer>
extern __imp_RegIsTimeZoneRedirectionEnabled:PANYARGS
RegIsTimeZoneRedirectionEnabled TEXTEQU <__imp_RegIsTimeZoneRedirectionEnabled>
extern __imp_RegMergeUserConfigWithUserParameters:PANYARGS
RegMergeUserConfigWithUserParameters TEXTEQU <__imp_RegMergeUserConfigWithUserParameters>
extern __imp_RegOpenServerA:PANYARGS
RegOpenServer  TEXTEQU <__imp_RegOpenServerA>
extern __imp_RegOpenServerW:PANYARGS
RegOpenServerW TEXTEQU <__imp_RegOpenServerW>
extern __imp_RegPdCreateA:PANYARGS
RegPdCreate  TEXTEQU <__imp_RegPdCreateA>
extern __imp_RegPdCreateW:PANYARGS
RegPdCreateW TEXTEQU <__imp_RegPdCreateW>
extern __imp_RegPdDeleteA:PANYARGS
RegPdDelete  TEXTEQU <__imp_RegPdDeleteA>
extern __imp_RegPdDeleteW:PANYARGS
RegPdDeleteW TEXTEQU <__imp_RegPdDeleteW>
extern __imp_RegPdEnumerateA:PANYARGS
RegPdEnumerate  TEXTEQU <__imp_RegPdEnumerateA>
extern __imp_RegPdEnumerateW:PANYARGS
RegPdEnumerateW TEXTEQU <__imp_RegPdEnumerateW>
extern __imp_RegPdQueryA:PANYARGS
RegPdQuery  TEXTEQU <__imp_RegPdQueryA>
extern __imp_RegPdQueryW:PANYARGS
RegPdQueryW TEXTEQU <__imp_RegPdQueryW>
extern __imp_RegQueryOEMId:PANYARGS
RegQueryOEMId TEXTEQU <__imp_RegQueryOEMId>
extern __imp_RegQueryUtilityCommandList:PANYARGS
RegQueryUtilityCommandList TEXTEQU <__imp_RegQueryUtilityCommandList>
extern __imp_RegSAMUserConfig:PANYARGS
RegSAMUserConfig TEXTEQU <__imp_RegSAMUserConfig>
extern __imp_RegUserConfigDelete:PANYARGS
RegUserConfigDelete TEXTEQU <__imp_RegUserConfigDelete>
extern __imp_RegUserConfigQuery:PANYARGS
RegUserConfigQuery TEXTEQU <__imp_RegUserConfigQuery>
extern __imp_RegUserConfigRename:PANYARGS
RegUserConfigRename TEXTEQU <__imp_RegUserConfigRename>
extern __imp_RegUserConfigSet:PANYARGS
RegUserConfigSet TEXTEQU <__imp_RegUserConfigSet>
extern __imp_RegWdCreateA:PANYARGS
RegWdCreate  TEXTEQU <__imp_RegWdCreateA>
extern __imp_RegWdCreateW:PANYARGS
RegWdCreateW TEXTEQU <__imp_RegWdCreateW>
extern __imp_RegWdDeleteA:PANYARGS
RegWdDelete  TEXTEQU <__imp_RegWdDeleteA>
extern __imp_RegWdDeleteW:PANYARGS
RegWdDeleteW TEXTEQU <__imp_RegWdDeleteW>
extern __imp_RegWdEnumerateA:PANYARGS
RegWdEnumerate  TEXTEQU <__imp_RegWdEnumerateA>
extern __imp_RegWdEnumerateW:PANYARGS
RegWdEnumerateW TEXTEQU <__imp_RegWdEnumerateW>
extern __imp_RegWdQueryA:PANYARGS
RegWdQuery  TEXTEQU <__imp_RegWdQueryA>
extern __imp_RegWdQueryW:PANYARGS
RegWdQueryW TEXTEQU <__imp_RegWdQueryW>
extern __imp_RegWinStationAccessCheck:PANYARGS
RegWinStationAccessCheck TEXTEQU <__imp_RegWinStationAccessCheck>
extern __imp_RegWinStationCreateA:PANYARGS
RegWinStationCreate  TEXTEQU <__imp_RegWinStationCreateA>
extern __imp_RegWinStationCreateW:PANYARGS
RegWinStationCreateW TEXTEQU <__imp_RegWinStationCreateW>
extern __imp_RegWinStationDeleteA:PANYARGS
RegWinStationDelete  TEXTEQU <__imp_RegWinStationDeleteA>
extern __imp_RegWinStationDeleteW:PANYARGS
RegWinStationDeleteW TEXTEQU <__imp_RegWinStationDeleteW>
extern __imp_RegWinStationEnumerateA:PANYARGS
RegWinStationEnumerate  TEXTEQU <__imp_RegWinStationEnumerateA>
extern __imp_RegWinStationEnumerateW:PANYARGS
RegWinStationEnumerateW TEXTEQU <__imp_RegWinStationEnumerateW>
extern __imp_RegWinStationQueryA:PANYARGS
RegWinStationQuery  TEXTEQU <__imp_RegWinStationQueryA>
extern __imp_RegWinStationQueryDefaultSecurity:PANYARGS
RegWinStationQueryDefaultSecurity TEXTEQU <__imp_RegWinStationQueryDefaultSecurity>
extern __imp_RegWinStationQueryEx:PANYARGS
RegWinStationQueryEx TEXTEQU <__imp_RegWinStationQueryEx>
extern __imp_RegWinStationQueryExNew:PANYARGS
RegWinStationQueryExNew TEXTEQU <__imp_RegWinStationQueryExNew>
extern __imp_RegWinStationQueryNumValueW:PANYARGS
RegWinStationQueryNumValueW TEXTEQU <__imp_RegWinStationQueryNumValueW>
extern __imp_RegWinStationQuerySecurityA:PANYARGS
RegWinStationQuerySecurity  TEXTEQU <__imp_RegWinStationQuerySecurityA>
extern __imp_RegWinStationQuerySecurityW:PANYARGS
RegWinStationQuerySecurityW TEXTEQU <__imp_RegWinStationQuerySecurityW>
extern __imp_RegWinStationQueryValueW:PANYARGS
RegWinStationQueryValueW TEXTEQU <__imp_RegWinStationQueryValueW>
extern __imp_RegWinStationQueryW:PANYARGS
RegWinStationQueryW TEXTEQU <__imp_RegWinStationQueryW>
extern __imp_RegWinStationSetNumValueW:PANYARGS
RegWinStationSetNumValueW TEXTEQU <__imp_RegWinStationSetNumValueW>
extern __imp_RegWinStationSetSecurityA:PANYARGS
RegWinStationSetSecurity  TEXTEQU <__imp_RegWinStationSetSecurityA>
extern __imp_RegWinStationSetSecurityW:PANYARGS
RegWinStationSetSecurityW TEXTEQU <__imp_RegWinStationSetSecurityW>
extern __imp_RegWinstationQuerySecurityConfig_Machine:PANYARGS
RegWinstationQuerySecurityConfig_Machine TEXTEQU <__imp_RegWinstationQuerySecurityConfig_Machine>
extern __imp_RegWinstationQuerySecurityConfig_Merged:PANYARGS
RegWinstationQuerySecurityConfig_Merged TEXTEQU <__imp_RegWinstationQuerySecurityConfig_Merged>
extern __imp_RegWinstationSetSecurityConfig:PANYARGS
RegWinstationSetSecurityConfig TEXTEQU <__imp_RegWinstationSetSecurityConfig>
extern __imp_SetUserProperty:PANYARGS
SetUserProperty TEXTEQU <__imp_SetUserProperty>
extern __imp_UsrPropGetString:PANYARGS
UsrPropGetString TEXTEQU <__imp_UsrPropGetString>
extern __imp_UsrPropGetValue:PANYARGS
UsrPropGetValue TEXTEQU <__imp_UsrPropGetValue>
extern __imp_UsrPropSetString:PANYARGS
UsrPropSetString TEXTEQU <__imp_UsrPropSetString>
extern __imp_UsrPropSetValue:PANYARGS
UsrPropSetValue TEXTEQU <__imp_UsrPropSetValue>
extern __imp_WaitForTSConnectionsPolicyChanges:PANYARGS
WaitForTSConnectionsPolicyChanges TEXTEQU <__imp_WaitForTSConnectionsPolicyChanges>
