extern __imp_AddRoute:PANYARGS
AddRoute TEXTEQU <__imp_AddRoute>
extern __imp_DeleteRoute:PANYARGS
DeleteRoute TEXTEQU <__imp_DeleteRoute>
extern __imp_FreeIPAddressTable:PANYARGS
FreeIPAddressTable TEXTEQU <__imp_FreeIPAddressTable>
extern __imp_FreeRouteTable:PANYARGS
FreeRouteTable TEXTEQU <__imp_FreeRouteTable>
extern __imp_GetIPAddressTable:PANYARGS
GetIPAddressTable TEXTEQU <__imp_GetIPAddressTable>
extern __imp_GetIfEntry:PANYARGS
GetIfEntry TEXTEQU <__imp_GetIfEntry>
extern __imp_GetRouteTable:PANYARGS
GetRouteTable TEXTEQU <__imp_GetRouteTable>
extern __imp_RefreshAddresses:PANYARGS
RefreshAddresses TEXTEQU <__imp_RefreshAddresses>
extern __imp_ReloadIPAddressTable:PANYARGS
ReloadIPAddressTable TEXTEQU <__imp_ReloadIPAddressTable>
extern __imp_SetAddrChangeNotifyEvent:PANYARGS
SetAddrChangeNotifyEvent TEXTEQU <__imp_SetAddrChangeNotifyEvent>
