extern __imp_LogErrorA:PANYARGS
LogError  TEXTEQU <__imp_LogErrorA>
extern __imp_LogErrorW:PANYARGS
LogErrorW TEXTEQU <__imp_LogErrorW>
extern __imp_LogEventA:PANYARGS
LogEvent  TEXTEQU <__imp_LogEventA>
extern __imp_LogEventW:PANYARGS
LogEventW TEXTEQU <__imp_LogEventW>
extern __imp_MprSetupProtocolEnum:PANYARGS
MprSetupProtocolEnum TEXTEQU <__imp_MprSetupProtocolEnum>
extern __imp_MprSetupProtocolFree:PANYARGS
MprSetupProtocolFree TEXTEQU <__imp_MprSetupProtocolFree>
extern __imp_QueueWorkItem:PANYARGS
QueueWorkItem TEXTEQU <__imp_QueueWorkItem>
extern __imp_RouterAssert:PANYARGS
RouterAssert TEXTEQU <__imp_RouterAssert>
extern __imp_RouterGetErrorStringA:PANYARGS
RouterGetErrorString  TEXTEQU <__imp_RouterGetErrorStringA>
extern __imp_RouterGetErrorStringW:PANYARGS
RouterGetErrorStringW TEXTEQU <__imp_RouterGetErrorStringW>
extern __imp_RouterLogDeregisterA:PANYARGS
RouterLogDeregister  TEXTEQU <__imp_RouterLogDeregisterA>
extern __imp_RouterLogDeregisterW:PANYARGS
RouterLogDeregisterW TEXTEQU <__imp_RouterLogDeregisterW>
extern __imp_RouterLogEventA:PANYARGS
RouterLogEvent  TEXTEQU <__imp_RouterLogEventA>
extern __imp_RouterLogEventDataA:PANYARGS
RouterLogEventData  TEXTEQU <__imp_RouterLogEventDataA>
extern __imp_RouterLogEventDataW:PANYARGS
RouterLogEventDataW TEXTEQU <__imp_RouterLogEventDataW>
extern __imp_RouterLogEventExA:PANYARGS
RouterLogEventEx  TEXTEQU <__imp_RouterLogEventExA>
extern __imp_RouterLogEventExW:PANYARGS
RouterLogEventExW TEXTEQU <__imp_RouterLogEventExW>
extern __imp_RouterLogEventStringA:PANYARGS
RouterLogEventString  TEXTEQU <__imp_RouterLogEventStringA>
extern __imp_RouterLogEventStringW:PANYARGS
RouterLogEventStringW TEXTEQU <__imp_RouterLogEventStringW>
extern __imp_RouterLogEventValistExA:PANYARGS
RouterLogEventValistEx  TEXTEQU <__imp_RouterLogEventValistExA>
extern __imp_RouterLogEventValistExW:PANYARGS
RouterLogEventValistExW TEXTEQU <__imp_RouterLogEventValistExW>
extern __imp_RouterLogEventW:PANYARGS
RouterLogEventW TEXTEQU <__imp_RouterLogEventW>
extern __imp_RouterLogRegisterA:PANYARGS
RouterLogRegister  TEXTEQU <__imp_RouterLogRegisterA>
extern __imp_RouterLogRegisterW:PANYARGS
RouterLogRegisterW TEXTEQU <__imp_RouterLogRegisterW>
extern __imp_SetIoCompletionProc:PANYARGS
SetIoCompletionProc TEXTEQU <__imp_SetIoCompletionProc>
extern __imp_TraceDeregisterA:PANYARGS
TraceDeregister  TEXTEQU <__imp_TraceDeregisterA>
extern __imp_TraceDeregisterExA:PANYARGS
TraceDeregisterEx  TEXTEQU <__imp_TraceDeregisterExA>
extern __imp_TraceDeregisterExW:PANYARGS
TraceDeregisterExW TEXTEQU <__imp_TraceDeregisterExW>
extern __imp_TraceDeregisterW:PANYARGS
TraceDeregisterW TEXTEQU <__imp_TraceDeregisterW>
extern __imp_TraceDumpExA:PANYARGS
TraceDumpEx  TEXTEQU <__imp_TraceDumpExA>
extern __imp_TraceDumpExW:PANYARGS
TraceDumpExW TEXTEQU <__imp_TraceDumpExW>
extern __imp_TraceGetConsoleA:PANYARGS
TraceGetConsole  TEXTEQU <__imp_TraceGetConsoleA>
extern __imp_TraceGetConsoleW:PANYARGS
TraceGetConsoleW TEXTEQU <__imp_TraceGetConsoleW>
extern __imp_TracePrintfA:PANYARGS
TracePrintf  TEXTEQU <__imp_TracePrintfA>
extern __imp_TracePrintfExA:PANYARGS
TracePrintfEx  TEXTEQU <__imp_TracePrintfExA>
extern __imp_TracePrintfExW:PANYARGS
TracePrintfExW TEXTEQU <__imp_TracePrintfExW>
extern __imp_TracePrintfW:PANYARGS
TracePrintfW TEXTEQU <__imp_TracePrintfW>
extern __imp_TracePutsExA:PANYARGS
TracePutsEx  TEXTEQU <__imp_TracePutsExA>
extern __imp_TracePutsExW:PANYARGS
TracePutsExW TEXTEQU <__imp_TracePutsExW>
extern __imp_TraceRegisterExA:PANYARGS
TraceRegisterEx  TEXTEQU <__imp_TraceRegisterExA>
extern __imp_TraceRegisterExW:PANYARGS
TraceRegisterExW TEXTEQU <__imp_TraceRegisterExW>
extern __imp_TraceVprintfExA:PANYARGS
TraceVprintfEx  TEXTEQU <__imp_TraceVprintfExA>
extern __imp_TraceVprintfExW:PANYARGS
TraceVprintfExW TEXTEQU <__imp_TraceVprintfExW>
