extern __imp_GetOpenCardNameA:PANYARGS
GetOpenCardName  TEXTEQU <__imp_GetOpenCardNameA>
extern __imp_GetOpenCardNameW:PANYARGS
GetOpenCardNameW TEXTEQU <__imp_GetOpenCardNameW>
extern __imp_SCardDlgExtendedError:PANYARGS
SCardDlgExtendedError TEXTEQU <__imp_SCardDlgExtendedError>
extern __imp_SCardUIDlgSelectCardA:PANYARGS
SCardUIDlgSelectCard  TEXTEQU <__imp_SCardUIDlgSelectCardA>
extern __imp_SCardUIDlgSelectCardW:PANYARGS
SCardUIDlgSelectCardW TEXTEQU <__imp_SCardUIDlgSelectCardW>
extern __imp_SCardUIDlgGetPINA:PANYARGS
SCardUIDlgGetPIN  TEXTEQU <__imp_SCardUIDlgGetPINA>
extern __imp_SCardUIDlgChangePINA:PANYARGS
SCardUIDlgChangePIN  TEXTEQU <__imp_SCardUIDlgChangePINA>
