extern __imp_SPUninstall:PANYARGS
SPUninstall TEXTEQU <__imp_SPUninstall>
extern __imp_SPUninstallCallback:PANYARGS
SPUninstallCallback TEXTEQU <__imp_SPUninstallCallback>
extern __imp_SchedServiceMain:PANYARGS
SchedServiceMain TEXTEQU <__imp_SchedServiceMain>
extern __imp_SysPrepBackup:PANYARGS
SysPrepBackup TEXTEQU <__imp_SysPrepBackup>
extern __imp_SysPrepRestore:PANYARGS
SysPrepRestore TEXTEQU <__imp_SysPrepRestore>
extern __imp_CloseProc:PANYARGS
CloseProc TEXTEQU <__imp_CloseProc>
extern __imp_SysPrepCallback:PANYARGS
SysPrepCallback TEXTEQU <__imp_SysPrepCallback>
