extern __imp_WLEventLock:PANYARGS
WLEventLock TEXTEQU <__imp_WLEventLock>
extern __imp_WLEventLogoff:PANYARGS
WLEventLogoff TEXTEQU <__imp_WLEventLogoff>
extern __imp_WLEventLogon:PANYARGS
WLEventLogon TEXTEQU <__imp_WLEventLogon>
extern __imp_WLEventShutdown:PANYARGS
WLEventShutdown TEXTEQU <__imp_WLEventShutdown>
extern __imp_WLEventStartScreenSaver:PANYARGS
WLEventStartScreenSaver TEXTEQU <__imp_WLEventStartScreenSaver>
extern __imp_WLEventStartShell:PANYARGS
WLEventStartShell TEXTEQU <__imp_WLEventStartShell>
extern __imp_WLEventStartup:PANYARGS
WLEventStartup TEXTEQU <__imp_WLEventStartup>
extern __imp_WLEventStopScreenSaver:PANYARGS
WLEventStopScreenSaver TEXTEQU <__imp_WLEventStopScreenSaver>
extern __imp_WLEventUnlock:PANYARGS
WLEventUnlock TEXTEQU <__imp_WLEventUnlock>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GenerateDefaultEFSRecoveryPolicy:PANYARGS
GenerateDefaultEFSRecoveryPolicy TEXTEQU <__imp_GenerateDefaultEFSRecoveryPolicy>
