extern __imp_GenerateTypeLib:PANYARGS
GenerateTypeLib TEXTEQU <__imp_GenerateTypeLib>
extern __imp_GenerateTypeLibW:PANYARGS
GenerateTypeLibW TEXTEQU <__imp_GenerateTypeLibW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllRegisterServerEx:PANYARGS
DllRegisterServerEx TEXTEQU <__imp_DllRegisterServerEx>
extern __imp_DllRegisterServerExA:PANYARGS
DllRegisterServerEx  TEXTEQU <__imp_DllRegisterServerExA>
extern __imp_DllRegisterServerExW:PANYARGS
DllRegisterServerExW TEXTEQU <__imp_DllRegisterServerExW>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_DllUnregisterServerEx:PANYARGS
DllUnregisterServerEx TEXTEQU <__imp_DllUnregisterServerEx>
