extern __imp_sfc_ordinal1:PANYARGS
sfc_ordinal1 TEXTEQU <__imp_sfc_ordinal1>
extern __imp_sfc_ordinal2:PANYARGS
sfc_ordinal2 TEXTEQU <__imp_sfc_ordinal2>
extern __imp_sfc_ordinal3:PANYARGS
sfc_ordinal3 TEXTEQU <__imp_sfc_ordinal3>
extern __imp_sfc_ordinal4:PANYARGS
sfc_ordinal4 TEXTEQU <__imp_sfc_ordinal4>
extern __imp_sfc_ordinal5:PANYARGS
sfc_ordinal5 TEXTEQU <__imp_sfc_ordinal5>
extern __imp_sfc_ordinal6:PANYARGS
sfc_ordinal6 TEXTEQU <__imp_sfc_ordinal6>
extern __imp_sfc_ordinal7:PANYARGS
sfc_ordinal7 TEXTEQU <__imp_sfc_ordinal7>
extern __imp_sfc_ordinal8:PANYARGS
sfc_ordinal8 TEXTEQU <__imp_sfc_ordinal8>
extern __imp_sfc_ordinal9:PANYARGS
sfc_ordinal9 TEXTEQU <__imp_sfc_ordinal9>
extern __imp_SRSetRestorePoint:PANYARGS
SRSetRestorePoint TEXTEQU <__imp_SRSetRestorePoint>
extern __imp_SRSetRestorePointA:PANYARGS
SRSetRestorePoint  TEXTEQU <__imp_SRSetRestorePointA>
extern __imp_SRSetRestorePointW:PANYARGS
SRSetRestorePointW TEXTEQU <__imp_SRSetRestorePointW>
extern __imp_SfcGetNextProtectedFile:PANYARGS
SfcGetNextProtectedFile TEXTEQU <__imp_SfcGetNextProtectedFile>
extern __imp_SfcIsFileProtected:PANYARGS
SfcIsFileProtected TEXTEQU <__imp_SfcIsFileProtected>
extern __imp_SfcWLEventLogoff:PANYARGS
SfcWLEventLogoff TEXTEQU <__imp_SfcWLEventLogoff>
extern __imp_SfcWLEventLogon:PANYARGS
SfcWLEventLogon TEXTEQU <__imp_SfcWLEventLogon>
extern __imp_SfpVerifyFile:PANYARGS
SfpVerifyFile TEXTEQU <__imp_SfpVerifyFile>
