extern __imp_sfc_os_ordinal1:PANYARGS
sfc_os_ordinal1 TEXTEQU <__imp_sfc_os_ordinal1>
extern __imp_sfc_os_ordinal2:PANYARGS
sfc_os_ordinal2 TEXTEQU <__imp_sfc_os_ordinal2>
extern __imp_sfc_os_ordinal3:PANYARGS
sfc_os_ordinal3 TEXTEQU <__imp_sfc_os_ordinal3>
extern __imp_sfc_os_ordinal4:PANYARGS
sfc_os_ordinal4 TEXTEQU <__imp_sfc_os_ordinal4>
extern __imp_sfc_os_ordinal5:PANYARGS
sfc_os_ordinal5 TEXTEQU <__imp_sfc_os_ordinal5>
extern __imp_sfc_os_ordinal6:PANYARGS
sfc_os_ordinal6 TEXTEQU <__imp_sfc_os_ordinal6>
extern __imp_sfc_os_ordinal7:PANYARGS
sfc_os_ordinal7 TEXTEQU <__imp_sfc_os_ordinal7>
extern __imp_SfcGetNextProtectedFile:PANYARGS
SfcGetNextProtectedFile TEXTEQU <__imp_SfcGetNextProtectedFile>
extern __imp_SfcIsFileProtected:PANYARGS
SfcIsFileProtected TEXTEQU <__imp_SfcIsFileProtected>
extern __imp_SfcWLEventLogoff:PANYARGS
SfcWLEventLogoff TEXTEQU <__imp_SfcWLEventLogoff>
extern __imp_SfcWLEventLogon:PANYARGS
SfcWLEventLogon TEXTEQU <__imp_SfcWLEventLogon>
