extern __imp_shdocvw_ordinal101:PANYARGS
shdocvw_ordinal101 TEXTEQU <__imp_shdocvw_ordinal101>
extern __imp_shdocvw_ordinal102:PANYARGS
shdocvw_ordinal102 TEXTEQU <__imp_shdocvw_ordinal102>
extern __imp_shdocvw_ordinal103:PANYARGS
shdocvw_ordinal103 TEXTEQU <__imp_shdocvw_ordinal103>
extern __imp_shdocvw_ordinal104:PANYARGS
shdocvw_ordinal104 TEXTEQU <__imp_shdocvw_ordinal104>
extern __imp_shdocvw_ordinal105:PANYARGS
shdocvw_ordinal105 TEXTEQU <__imp_shdocvw_ordinal105>
extern __imp_AddUrlToFavorites:PANYARGS
AddUrlToFavorites TEXTEQU <__imp_AddUrlToFavorites>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllGetVersion:PANYARGS
DllGetVersion TEXTEQU <__imp_DllGetVersion>
extern __imp_shdocvw_ordinal110:PANYARGS
shdocvw_ordinal110 TEXTEQU <__imp_shdocvw_ordinal110>
extern __imp_shdocvw_ordinal111:PANYARGS
shdocvw_ordinal111 TEXTEQU <__imp_shdocvw_ordinal111>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllRegisterWindowClasses:PANYARGS
DllRegisterWindowClasses TEXTEQU <__imp_DllRegisterWindowClasses>
extern __imp_shdocvw_ordinal115:PANYARGS
shdocvw_ordinal115 TEXTEQU <__imp_shdocvw_ordinal115>
extern __imp_shdocvw_ordinal116:PANYARGS
shdocvw_ordinal116 TEXTEQU <__imp_shdocvw_ordinal116>
extern __imp_shdocvw_ordinal117:PANYARGS
shdocvw_ordinal117 TEXTEQU <__imp_shdocvw_ordinal117>
extern __imp_shdocvw_ordinal118:PANYARGS
shdocvw_ordinal118 TEXTEQU <__imp_shdocvw_ordinal118>
extern __imp_shdocvw_ordinal119:PANYARGS
shdocvw_ordinal119 TEXTEQU <__imp_shdocvw_ordinal119>
extern __imp_shdocvw_ordinal120:PANYARGS
shdocvw_ordinal120 TEXTEQU <__imp_shdocvw_ordinal120>
extern __imp_shdocvw_ordinal121:PANYARGS
shdocvw_ordinal121 TEXTEQU <__imp_shdocvw_ordinal121>
extern __imp_shdocvw_ordinal122:PANYARGS
shdocvw_ordinal122 TEXTEQU <__imp_shdocvw_ordinal122>
extern __imp_shdocvw_ordinal123:PANYARGS
shdocvw_ordinal123 TEXTEQU <__imp_shdocvw_ordinal123>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_shdocvw_ordinal125:PANYARGS
shdocvw_ordinal125 TEXTEQU <__imp_shdocvw_ordinal125>
extern __imp_DoAddToFavDlg:PANYARGS
DoAddToFavDlg TEXTEQU <__imp_DoAddToFavDlg>
extern __imp_DoAddToFavDlgW:PANYARGS
DoAddToFavDlgW TEXTEQU <__imp_DoAddToFavDlgW>
extern __imp_DoFileDownload:PANYARGS
DoFileDownload TEXTEQU <__imp_DoFileDownload>
extern __imp_DoFileDownloadEx:PANYARGS
DoFileDownloadEx TEXTEQU <__imp_DoFileDownloadEx>
extern __imp_shdocvw_ordinal130:PANYARGS
shdocvw_ordinal130 TEXTEQU <__imp_shdocvw_ordinal130>
extern __imp_shdocvw_ordinal131:PANYARGS
shdocvw_ordinal131 TEXTEQU <__imp_shdocvw_ordinal131>
extern __imp_DoOrganizeFavDlg:PANYARGS
DoOrganizeFavDlg TEXTEQU <__imp_DoOrganizeFavDlg>
extern __imp_DoOrganizeFavDlgW:PANYARGS
DoOrganizeFavDlgW TEXTEQU <__imp_DoOrganizeFavDlgW>
extern __imp_DoPrivacyDlg:PANYARGS
DoPrivacyDlg TEXTEQU <__imp_DoPrivacyDlg>
extern __imp_shdocvw_ordinal135:PANYARGS
shdocvw_ordinal135 TEXTEQU <__imp_shdocvw_ordinal135>
extern __imp_shdocvw_ordinal136:PANYARGS
shdocvw_ordinal136 TEXTEQU <__imp_shdocvw_ordinal136>
extern __imp_shdocvw_ordinal137:PANYARGS
shdocvw_ordinal137 TEXTEQU <__imp_shdocvw_ordinal137>
extern __imp_shdocvw_ordinal138:PANYARGS
shdocvw_ordinal138 TEXTEQU <__imp_shdocvw_ordinal138>
extern __imp_shdocvw_ordinal139:PANYARGS
shdocvw_ordinal139 TEXTEQU <__imp_shdocvw_ordinal139>
extern __imp_shdocvw_ordinal140:PANYARGS
shdocvw_ordinal140 TEXTEQU <__imp_shdocvw_ordinal140>
extern __imp_shdocvw_ordinal141:PANYARGS
shdocvw_ordinal141 TEXTEQU <__imp_shdocvw_ordinal141>
extern __imp_shdocvw_ordinal142:PANYARGS
shdocvw_ordinal142 TEXTEQU <__imp_shdocvw_ordinal142>
extern __imp_shdocvw_ordinal143:PANYARGS
shdocvw_ordinal143 TEXTEQU <__imp_shdocvw_ordinal143>
extern __imp_HlinkFindFrame:PANYARGS
HlinkFindFrame TEXTEQU <__imp_HlinkFindFrame>
extern __imp_shdocvw_ordinal145:PANYARGS
shdocvw_ordinal145 TEXTEQU <__imp_shdocvw_ordinal145>
extern __imp_shdocvw_ordinal146:PANYARGS
shdocvw_ordinal146 TEXTEQU <__imp_shdocvw_ordinal146>
extern __imp_shdocvw_ordinal147:PANYARGS
shdocvw_ordinal147 TEXTEQU <__imp_shdocvw_ordinal147>
extern __imp_shdocvw_ordinal148:PANYARGS
shdocvw_ordinal148 TEXTEQU <__imp_shdocvw_ordinal148>
extern __imp_shdocvw_ordinal149:PANYARGS
shdocvw_ordinal149 TEXTEQU <__imp_shdocvw_ordinal149>
extern __imp_shdocvw_ordinal150:PANYARGS
shdocvw_ordinal150 TEXTEQU <__imp_shdocvw_ordinal150>
extern __imp_shdocvw_ordinal151:PANYARGS
shdocvw_ordinal151 TEXTEQU <__imp_shdocvw_ordinal151>
extern __imp_shdocvw_ordinal152:PANYARGS
shdocvw_ordinal152 TEXTEQU <__imp_shdocvw_ordinal152>
extern __imp_shdocvw_ordinal153:PANYARGS
shdocvw_ordinal153 TEXTEQU <__imp_shdocvw_ordinal153>
extern __imp_HlinkFrameNavigate:PANYARGS
HlinkFrameNavigate TEXTEQU <__imp_HlinkFrameNavigate>
extern __imp_HlinkFrameNavigateNHL:PANYARGS
HlinkFrameNavigateNHL TEXTEQU <__imp_HlinkFrameNavigateNHL>
extern __imp_IEWriteErrorLog:PANYARGS
IEWriteErrorLog TEXTEQU <__imp_IEWriteErrorLog>
extern __imp_ImportPrivacySettings:PANYARGS
ImportPrivacySettings TEXTEQU <__imp_ImportPrivacySettings>
extern __imp_shdocvw_ordinal158:PANYARGS
shdocvw_ordinal158 TEXTEQU <__imp_shdocvw_ordinal158>
extern __imp_shdocvw_ordinal159:PANYARGS
shdocvw_ordinal159 TEXTEQU <__imp_shdocvw_ordinal159>
extern __imp_shdocvw_ordinal160:PANYARGS
shdocvw_ordinal160 TEXTEQU <__imp_shdocvw_ordinal160>
extern __imp_shdocvw_ordinal161:PANYARGS
shdocvw_ordinal161 TEXTEQU <__imp_shdocvw_ordinal161>
extern __imp_shdocvw_ordinal162:PANYARGS
shdocvw_ordinal162 TEXTEQU <__imp_shdocvw_ordinal162>
extern __imp_SHAddSubscribeFavorite:PANYARGS
SHAddSubscribeFavorite TEXTEQU <__imp_SHAddSubscribeFavorite>
extern __imp_shdocvw_ordinal164:PANYARGS
shdocvw_ordinal164 TEXTEQU <__imp_shdocvw_ordinal164>
extern __imp_shdocvw_ordinal165:PANYARGS
shdocvw_ordinal165 TEXTEQU <__imp_shdocvw_ordinal165>
extern __imp_OpenURL:PANYARGS
OpenURL TEXTEQU <__imp_OpenURL>
extern __imp_shdocvw_ordinal167:PANYARGS
shdocvw_ordinal167 TEXTEQU <__imp_shdocvw_ordinal167>
extern __imp_SHGetIDispatchForFolder:PANYARGS
SHGetIDispatchForFolder TEXTEQU <__imp_SHGetIDispatchForFolder>
extern __imp_shdocvw_ordinal169:PANYARGS
shdocvw_ordinal169 TEXTEQU <__imp_shdocvw_ordinal169>
extern __imp_shdocvw_ordinal170:PANYARGS
shdocvw_ordinal170 TEXTEQU <__imp_shdocvw_ordinal170>
extern __imp_shdocvw_ordinal171:PANYARGS
shdocvw_ordinal171 TEXTEQU <__imp_shdocvw_ordinal171>
extern __imp_shdocvw_ordinal172:PANYARGS
shdocvw_ordinal172 TEXTEQU <__imp_shdocvw_ordinal172>
extern __imp_shdocvw_ordinal173:PANYARGS
shdocvw_ordinal173 TEXTEQU <__imp_shdocvw_ordinal173>
extern __imp_shdocvw_ordinal174:PANYARGS
shdocvw_ordinal174 TEXTEQU <__imp_shdocvw_ordinal174>
extern __imp_shdocvw_ordinal175:PANYARGS
shdocvw_ordinal175 TEXTEQU <__imp_shdocvw_ordinal175>
extern __imp_shdocvw_ordinal176:PANYARGS
shdocvw_ordinal176 TEXTEQU <__imp_shdocvw_ordinal176>
extern __imp_shdocvw_ordinal177:PANYARGS
shdocvw_ordinal177 TEXTEQU <__imp_shdocvw_ordinal177>
extern __imp_shdocvw_ordinal178:PANYARGS
shdocvw_ordinal178 TEXTEQU <__imp_shdocvw_ordinal178>
extern __imp_shdocvw_ordinal179:PANYARGS
shdocvw_ordinal179 TEXTEQU <__imp_shdocvw_ordinal179>
extern __imp_shdocvw_ordinal180:PANYARGS
shdocvw_ordinal180 TEXTEQU <__imp_shdocvw_ordinal180>
extern __imp_shdocvw_ordinal181:PANYARGS
shdocvw_ordinal181 TEXTEQU <__imp_shdocvw_ordinal181>
extern __imp_SetQueryNetSessionCount:PANYARGS
SetQueryNetSessionCount TEXTEQU <__imp_SetQueryNetSessionCount>
extern __imp_shdocvw_ordinal183:PANYARGS
shdocvw_ordinal183 TEXTEQU <__imp_shdocvw_ordinal183>
extern __imp_SetShellOfflineState:PANYARGS
SetShellOfflineState TEXTEQU <__imp_SetShellOfflineState>
extern __imp_shdocvw_ordinal185:PANYARGS
shdocvw_ordinal185 TEXTEQU <__imp_shdocvw_ordinal185>
extern __imp_SoftwareUpdateMessageBox:PANYARGS
SoftwareUpdateMessageBox TEXTEQU <__imp_SoftwareUpdateMessageBox>
extern __imp_shdocvw_ordinal187:PANYARGS
shdocvw_ordinal187 TEXTEQU <__imp_shdocvw_ordinal187>
extern __imp_shdocvw_ordinal188:PANYARGS
shdocvw_ordinal188 TEXTEQU <__imp_shdocvw_ordinal188>
extern __imp_shdocvw_ordinal189:PANYARGS
shdocvw_ordinal189 TEXTEQU <__imp_shdocvw_ordinal189>
extern __imp_shdocvw_ordinal190:PANYARGS
shdocvw_ordinal190 TEXTEQU <__imp_shdocvw_ordinal190>
extern __imp_shdocvw_ordinal191:PANYARGS
shdocvw_ordinal191 TEXTEQU <__imp_shdocvw_ordinal191>
extern __imp_shdocvw_ordinal192:PANYARGS
shdocvw_ordinal192 TEXTEQU <__imp_shdocvw_ordinal192>
extern __imp_URLQualifyA:PANYARGS
URLQualify  TEXTEQU <__imp_URLQualifyA>
extern __imp_shdocvw_ordinal194:PANYARGS
shdocvw_ordinal194 TEXTEQU <__imp_shdocvw_ordinal194>
extern __imp_shdocvw_ordinal195:PANYARGS
shdocvw_ordinal195 TEXTEQU <__imp_shdocvw_ordinal195>
extern __imp_shdocvw_ordinal196:PANYARGS
shdocvw_ordinal196 TEXTEQU <__imp_shdocvw_ordinal196>
extern __imp_shdocvw_ordinal197:PANYARGS
shdocvw_ordinal197 TEXTEQU <__imp_shdocvw_ordinal197>
extern __imp_shdocvw_ordinal198:PANYARGS
shdocvw_ordinal198 TEXTEQU <__imp_shdocvw_ordinal198>
extern __imp_URLQualifyW:PANYARGS
URLQualifyW TEXTEQU <__imp_URLQualifyW>
extern __imp_shdocvw_ordinal200:PANYARGS
shdocvw_ordinal200 TEXTEQU <__imp_shdocvw_ordinal200>
extern __imp_shdocvw_ordinal201:PANYARGS
shdocvw_ordinal201 TEXTEQU <__imp_shdocvw_ordinal201>
extern __imp_shdocvw_ordinal202:PANYARGS
shdocvw_ordinal202 TEXTEQU <__imp_shdocvw_ordinal202>
extern __imp_shdocvw_ordinal203:PANYARGS
shdocvw_ordinal203 TEXTEQU <__imp_shdocvw_ordinal203>
extern __imp_shdocvw_ordinal204:PANYARGS
shdocvw_ordinal204 TEXTEQU <__imp_shdocvw_ordinal204>
extern __imp_shdocvw_ordinal205:PANYARGS
shdocvw_ordinal205 TEXTEQU <__imp_shdocvw_ordinal205>
extern __imp_shdocvw_ordinal206:PANYARGS
shdocvw_ordinal206 TEXTEQU <__imp_shdocvw_ordinal206>
extern __imp_shdocvw_ordinal207:PANYARGS
shdocvw_ordinal207 TEXTEQU <__imp_shdocvw_ordinal207>
extern __imp_shdocvw_ordinal208:PANYARGS
shdocvw_ordinal208 TEXTEQU <__imp_shdocvw_ordinal208>
extern __imp_shdocvw_ordinal209:PANYARGS
shdocvw_ordinal209 TEXTEQU <__imp_shdocvw_ordinal209>
extern __imp_shdocvw_ordinal210:PANYARGS
shdocvw_ordinal210 TEXTEQU <__imp_shdocvw_ordinal210>
extern __imp_shdocvw_ordinal211:PANYARGS
shdocvw_ordinal211 TEXTEQU <__imp_shdocvw_ordinal211>
extern __imp_shdocvw_ordinal212:PANYARGS
shdocvw_ordinal212 TEXTEQU <__imp_shdocvw_ordinal212>
extern __imp_shdocvw_ordinal213:PANYARGS
shdocvw_ordinal213 TEXTEQU <__imp_shdocvw_ordinal213>
extern __imp_shdocvw_ordinal214:PANYARGS
shdocvw_ordinal214 TEXTEQU <__imp_shdocvw_ordinal214>
extern __imp_shdocvw_ordinal215:PANYARGS
shdocvw_ordinal215 TEXTEQU <__imp_shdocvw_ordinal215>
extern __imp_shdocvw_ordinal216:PANYARGS
shdocvw_ordinal216 TEXTEQU <__imp_shdocvw_ordinal216>
extern __imp_shdocvw_ordinal217:PANYARGS
shdocvw_ordinal217 TEXTEQU <__imp_shdocvw_ordinal217>
extern __imp_shdocvw_ordinal218:PANYARGS
shdocvw_ordinal218 TEXTEQU <__imp_shdocvw_ordinal218>
extern __imp_shdocvw_ordinal219:PANYARGS
shdocvw_ordinal219 TEXTEQU <__imp_shdocvw_ordinal219>
extern __imp_shdocvw_ordinal220:PANYARGS
shdocvw_ordinal220 TEXTEQU <__imp_shdocvw_ordinal220>
extern __imp_shdocvw_ordinal221:PANYARGS
shdocvw_ordinal221 TEXTEQU <__imp_shdocvw_ordinal221>
extern __imp_shdocvw_ordinal222:PANYARGS
shdocvw_ordinal222 TEXTEQU <__imp_shdocvw_ordinal222>
extern __imp_shdocvw_ordinal223:PANYARGS
shdocvw_ordinal223 TEXTEQU <__imp_shdocvw_ordinal223>
extern __imp_shdocvw_ordinal224:PANYARGS
shdocvw_ordinal224 TEXTEQU <__imp_shdocvw_ordinal224>
extern __imp_shdocvw_ordinal225:PANYARGS
shdocvw_ordinal225 TEXTEQU <__imp_shdocvw_ordinal225>
extern __imp_shdocvw_ordinal226:PANYARGS
shdocvw_ordinal226 TEXTEQU <__imp_shdocvw_ordinal226>
extern __imp_shdocvw_ordinal227:PANYARGS
shdocvw_ordinal227 TEXTEQU <__imp_shdocvw_ordinal227>
extern __imp_shdocvw_ordinal228:PANYARGS
shdocvw_ordinal228 TEXTEQU <__imp_shdocvw_ordinal228>
extern __imp_shdocvw_ordinal229:PANYARGS
shdocvw_ordinal229 TEXTEQU <__imp_shdocvw_ordinal229>
extern __imp_shdocvw_ordinal230:PANYARGS
shdocvw_ordinal230 TEXTEQU <__imp_shdocvw_ordinal230>
extern __imp_shdocvw_ordinal231:PANYARGS
shdocvw_ordinal231 TEXTEQU <__imp_shdocvw_ordinal231>
extern __imp_shdocvw_ordinal232:PANYARGS
shdocvw_ordinal232 TEXTEQU <__imp_shdocvw_ordinal232>
extern __imp_shdocvw_ordinal233:PANYARGS
shdocvw_ordinal233 TEXTEQU <__imp_shdocvw_ordinal233>
extern __imp_shdocvw_ordinal234:PANYARGS
shdocvw_ordinal234 TEXTEQU <__imp_shdocvw_ordinal234>
