extern __imp_SHChangeNotifyRegister:PANYARGS
SHChangeNotifyRegister TEXTEQU <__imp_SHChangeNotifyRegister>
extern __imp_SHDefExtractIconA:PANYARGS
SHDefExtractIcon  TEXTEQU <__imp_SHDefExtractIconA>
extern __imp_SHChangeNotifyDeregister:PANYARGS
SHChangeNotifyDeregister TEXTEQU <__imp_SHChangeNotifyDeregister>
extern __imp_shell32_ordinal5:PANYARGS
shell32_ordinal5 TEXTEQU <__imp_shell32_ordinal5>
extern __imp_SHDefExtractIconW:PANYARGS
SHDefExtractIconW TEXTEQU <__imp_SHDefExtractIconW>
extern __imp_shell32_ordinal7:PANYARGS
shell32_ordinal7 TEXTEQU <__imp_shell32_ordinal7>
extern __imp_shell32_ordinal8:PANYARGS
shell32_ordinal8 TEXTEQU <__imp_shell32_ordinal8>
extern __imp_PifMgr_OpenProperties:PANYARGS
PifMgr_OpenProperties TEXTEQU <__imp_PifMgr_OpenProperties>
extern __imp_PifMgr_GetProperties:PANYARGS
PifMgr_GetProperties TEXTEQU <__imp_PifMgr_GetProperties>
extern __imp_PifMgr_SetProperties:PANYARGS
PifMgr_SetProperties TEXTEQU <__imp_PifMgr_SetProperties>
extern __imp_shell32_ordinal12:PANYARGS
shell32_ordinal12 TEXTEQU <__imp_shell32_ordinal12>
extern __imp_PifMgr_CloseProperties:PANYARGS
PifMgr_CloseProperties TEXTEQU <__imp_PifMgr_CloseProperties>
extern __imp_SHStartNetConnectionDialogW:PANYARGS
SHStartNetConnectionDialogW TEXTEQU <__imp_SHStartNetConnectionDialogW>
extern __imp_shell32_ordinal15:PANYARGS
shell32_ordinal15 TEXTEQU <__imp_shell32_ordinal15>
extern __imp_ILFindLastID:PANYARGS
ILFindLastID TEXTEQU <__imp_ILFindLastID>
extern __imp_ILRemoveLastID:PANYARGS
ILRemoveLastID TEXTEQU <__imp_ILRemoveLastID>
extern __imp_ILClone:PANYARGS
ILClone TEXTEQU <__imp_ILClone>
extern __imp_ILCloneFirst:PANYARGS
ILCloneFirst TEXTEQU <__imp_ILCloneFirst>
extern __imp_shell32_ordinal20:PANYARGS
shell32_ordinal20 TEXTEQU <__imp_shell32_ordinal20>
extern __imp_ILIsEqual:PANYARGS
ILIsEqual TEXTEQU <__imp_ILIsEqual>
extern __imp_DAD_DragEnterEx2:PANYARGS
DAD_DragEnterEx2 TEXTEQU <__imp_DAD_DragEnterEx2>
extern __imp_ILIsParent:PANYARGS
ILIsParent TEXTEQU <__imp_ILIsParent>
extern __imp_ILFindChild:PANYARGS
ILFindChild TEXTEQU <__imp_ILFindChild>
extern __imp_ILCombine:PANYARGS
ILCombine TEXTEQU <__imp_ILCombine>
extern __imp_ILLoadFromStream:PANYARGS
ILLoadFromStream TEXTEQU <__imp_ILLoadFromStream>
extern __imp_ILSaveToStream:PANYARGS
ILSaveToStream TEXTEQU <__imp_ILSaveToStream>
extern __imp_SHILCreateFromPath:PANYARGS
SHILCreateFromPath TEXTEQU <__imp_SHILCreateFromPath>
extern __imp_shell32_ordinal29:PANYARGS
shell32_ordinal29 TEXTEQU <__imp_shell32_ordinal29>
extern __imp_shell32_ordinal30:PANYARGS
shell32_ordinal30 TEXTEQU <__imp_shell32_ordinal30>
extern __imp_shell32_ordinal31:PANYARGS
shell32_ordinal31 TEXTEQU <__imp_shell32_ordinal31>
extern __imp_shell32_ordinal32:PANYARGS
shell32_ordinal32 TEXTEQU <__imp_shell32_ordinal32>
extern __imp_shell32_ordinal33:PANYARGS
shell32_ordinal33 TEXTEQU <__imp_shell32_ordinal33>
extern __imp_shell32_ordinal34:PANYARGS
shell32_ordinal34 TEXTEQU <__imp_shell32_ordinal34>
extern __imp_shell32_ordinal35:PANYARGS
shell32_ordinal35 TEXTEQU <__imp_shell32_ordinal35>
extern __imp_shell32_ordinal36:PANYARGS
shell32_ordinal36 TEXTEQU <__imp_shell32_ordinal36>
extern __imp_shell32_ordinal37:PANYARGS
shell32_ordinal37 TEXTEQU <__imp_shell32_ordinal37>
extern __imp_shell32_ordinal38:PANYARGS
shell32_ordinal38 TEXTEQU <__imp_shell32_ordinal38>
extern __imp_shell32_ordinal39:PANYARGS
shell32_ordinal39 TEXTEQU <__imp_shell32_ordinal39>
extern __imp_shell32_ordinal40:PANYARGS
shell32_ordinal40 TEXTEQU <__imp_shell32_ordinal40>
extern __imp_IsLFNDriveA:PANYARGS
IsLFNDrive  TEXTEQU <__imp_IsLFNDriveA>
extern __imp_IsLFNDriveW:PANYARGS
IsLFNDriveW TEXTEQU <__imp_IsLFNDriveW>
extern __imp_PathIsExe:PANYARGS
PathIsExe TEXTEQU <__imp_PathIsExe>
extern __imp_shell32_ordinal44:PANYARGS
shell32_ordinal44 TEXTEQU <__imp_shell32_ordinal44>
extern __imp_shell32_ordinal45:PANYARGS
shell32_ordinal45 TEXTEQU <__imp_shell32_ordinal45>
extern __imp_shell32_ordinal46:PANYARGS
shell32_ordinal46 TEXTEQU <__imp_shell32_ordinal46>
extern __imp_PathMakeUniqueName:PANYARGS
PathMakeUniqueName TEXTEQU <__imp_PathMakeUniqueName>
extern __imp_shell32_ordinal48:PANYARGS
shell32_ordinal48 TEXTEQU <__imp_shell32_ordinal48>
extern __imp_PathQualify:PANYARGS
PathQualify TEXTEQU <__imp_PathQualify>
extern __imp_shell32_ordinal50:PANYARGS
shell32_ordinal50 TEXTEQU <__imp_shell32_ordinal50>
extern __imp_PathResolve:PANYARGS
PathResolve TEXTEQU <__imp_PathResolve>
extern __imp_shell32_ordinal52:PANYARGS
shell32_ordinal52 TEXTEQU <__imp_shell32_ordinal52>
extern __imp_shell32_ordinal53:PANYARGS
shell32_ordinal53 TEXTEQU <__imp_shell32_ordinal53>
extern __imp_shell32_ordinal54:PANYARGS
shell32_ordinal54 TEXTEQU <__imp_shell32_ordinal54>
extern __imp_shell32_ordinal55:PANYARGS
shell32_ordinal55 TEXTEQU <__imp_shell32_ordinal55>
extern __imp_shell32_ordinal56:PANYARGS
shell32_ordinal56 TEXTEQU <__imp_shell32_ordinal56>
extern __imp_shell32_ordinal57:PANYARGS
shell32_ordinal57 TEXTEQU <__imp_shell32_ordinal57>
extern __imp_shell32_ordinal58:PANYARGS
shell32_ordinal58 TEXTEQU <__imp_shell32_ordinal58>
extern __imp_RestartDialog:PANYARGS
RestartDialog TEXTEQU <__imp_RestartDialog>
extern __imp_shell32_ordinal60:PANYARGS
shell32_ordinal60 TEXTEQU <__imp_shell32_ordinal60>
extern __imp_shell32_ordinal61:PANYARGS
shell32_ordinal61 TEXTEQU <__imp_shell32_ordinal61>
extern __imp_PickIconDlg:PANYARGS
PickIconDlg TEXTEQU <__imp_PickIconDlg>
extern __imp_GetFileNameFromBrowse:PANYARGS
GetFileNameFromBrowse TEXTEQU <__imp_GetFileNameFromBrowse>
extern __imp_DriveType:PANYARGS
DriveType TEXTEQU <__imp_DriveType>
extern __imp_shell32_ordinal65:PANYARGS
shell32_ordinal65 TEXTEQU <__imp_shell32_ordinal65>
extern __imp_IsNetDrive:PANYARGS
IsNetDrive TEXTEQU <__imp_IsNetDrive>
extern __imp_Shell_MergeMenus:PANYARGS
Shell_MergeMenus TEXTEQU <__imp_Shell_MergeMenus>
extern __imp_SHGetSetSettings:PANYARGS
SHGetSetSettings TEXTEQU <__imp_SHGetSetSettings>
extern __imp_shell32_ordinal69:PANYARGS
shell32_ordinal69 TEXTEQU <__imp_shell32_ordinal69>
extern __imp_shell32_ordinal70:PANYARGS
shell32_ordinal70 TEXTEQU <__imp_shell32_ordinal70>
extern __imp_Shell_GetImageLists:PANYARGS
Shell_GetImageLists TEXTEQU <__imp_Shell_GetImageLists>
extern __imp_Shell_GetCachedImageIndex:PANYARGS
Shell_GetCachedImageIndex TEXTEQU <__imp_Shell_GetCachedImageIndex>
extern __imp_SHShellFolderView_Message:PANYARGS
SHShellFolderView_Message TEXTEQU <__imp_SHShellFolderView_Message>
extern __imp_SHCreateStdEnumFmtEtc:PANYARGS
SHCreateStdEnumFmtEtc TEXTEQU <__imp_SHCreateStdEnumFmtEtc>
extern __imp_PathYetAnotherMakeUniqueName:PANYARGS
PathYetAnotherMakeUniqueName TEXTEQU <__imp_PathYetAnotherMakeUniqueName>
extern __imp_shell32_ordinal76:PANYARGS
shell32_ordinal76 TEXTEQU <__imp_shell32_ordinal76>
extern __imp_SHMapPIDLToSystemImageListIndex:PANYARGS
SHMapPIDLToSystemImageListIndex TEXTEQU <__imp_SHMapPIDLToSystemImageListIndex>
extern __imp_shell32_ordinal78:PANYARGS
shell32_ordinal78 TEXTEQU <__imp_shell32_ordinal78>
extern __imp_shell32_ordinal79:PANYARGS
shell32_ordinal79 TEXTEQU <__imp_shell32_ordinal79>
extern __imp_SHOpenPropSheetW:PANYARGS
SHOpenPropSheetW TEXTEQU <__imp_SHOpenPropSheetW>
extern __imp_OpenAs_RunDLL:PANYARGS
OpenAs_RunDLL TEXTEQU <__imp_OpenAs_RunDLL>
extern __imp_shell32_ordinal82:PANYARGS
shell32_ordinal82 TEXTEQU <__imp_shell32_ordinal82>
extern __imp_shell32_ordinal83:PANYARGS
shell32_ordinal83 TEXTEQU <__imp_shell32_ordinal83>
extern __imp_shell32_ordinal84:PANYARGS
shell32_ordinal84 TEXTEQU <__imp_shell32_ordinal84>
extern __imp_OpenRegStream:PANYARGS
OpenRegStream TEXTEQU <__imp_OpenRegStream>
extern __imp_shell32_ordinal86:PANYARGS
shell32_ordinal86 TEXTEQU <__imp_shell32_ordinal86>
extern __imp_shell32_ordinal87:PANYARGS
shell32_ordinal87 TEXTEQU <__imp_shell32_ordinal87>
extern __imp_SHDoDragDrop:PANYARGS
SHDoDragDrop TEXTEQU <__imp_SHDoDragDrop>
extern __imp_SHCloneSpecialIDList:PANYARGS
SHCloneSpecialIDList TEXTEQU <__imp_SHCloneSpecialIDList>
extern __imp_SHFindFiles:PANYARGS
SHFindFiles TEXTEQU <__imp_SHFindFiles>
extern __imp_shell32_ordinal91:PANYARGS
shell32_ordinal91 TEXTEQU <__imp_shell32_ordinal91>
extern __imp_PathGetShortPath:PANYARGS
PathGetShortPath TEXTEQU <__imp_PathGetShortPath>
extern __imp_shell32_ordinal93:PANYARGS
shell32_ordinal93 TEXTEQU <__imp_shell32_ordinal93>
extern __imp_shell32_ordinal94:PANYARGS
shell32_ordinal94 TEXTEQU <__imp_shell32_ordinal94>
extern __imp_shell32_ordinal95:PANYARGS
shell32_ordinal95 TEXTEQU <__imp_shell32_ordinal95>
extern __imp_shell32_ordinal96:PANYARGS
shell32_ordinal96 TEXTEQU <__imp_shell32_ordinal96>
extern __imp_shell32_ordinal97:PANYARGS
shell32_ordinal97 TEXTEQU <__imp_shell32_ordinal97>
extern __imp_SHGetRealIDL:PANYARGS
SHGetRealIDL TEXTEQU <__imp_SHGetRealIDL>
extern __imp_shell32_ordinal99:PANYARGS
shell32_ordinal99 TEXTEQU <__imp_shell32_ordinal99>
extern __imp_SHRestricted:PANYARGS
SHRestricted TEXTEQU <__imp_SHRestricted>
extern __imp_OpenAs_RunDLLA:PANYARGS
OpenAs_RunDLL  TEXTEQU <__imp_OpenAs_RunDLLA>
extern __imp_SHCoCreateInstance:PANYARGS
SHCoCreateInstance TEXTEQU <__imp_SHCoCreateInstance>
extern __imp_SignalFileOpen:PANYARGS
SignalFileOpen TEXTEQU <__imp_SignalFileOpen>
extern __imp_OpenAs_RunDLLW:PANYARGS
OpenAs_RunDLLW TEXTEQU <__imp_OpenAs_RunDLLW>
extern __imp_Activate_RunDLL:PANYARGS
Activate_RunDLL TEXTEQU <__imp_Activate_RunDLL>
extern __imp_AppCompat_RunDLLW:PANYARGS
AppCompat_RunDLLW TEXTEQU <__imp_AppCompat_RunDLLW>
extern __imp_CheckEscapesA:PANYARGS
CheckEscapes  TEXTEQU <__imp_CheckEscapesA>
extern __imp_CheckEscapesW:PANYARGS
CheckEscapesW TEXTEQU <__imp_CheckEscapesW>
extern __imp_CommandLineToArgvW:PANYARGS
CommandLineToArgvW TEXTEQU <__imp_CommandLineToArgvW>
extern __imp_Control_FillCache_RunDLL:PANYARGS
Control_FillCache_RunDLL TEXTEQU <__imp_Control_FillCache_RunDLL>
extern __imp_Control_FillCache_RunDLLA:PANYARGS
Control_FillCache_RunDLL  TEXTEQU <__imp_Control_FillCache_RunDLLA>
extern __imp_Control_FillCache_RunDLLW:PANYARGS
Control_FillCache_RunDLLW TEXTEQU <__imp_Control_FillCache_RunDLLW>
extern __imp_Control_RunDLL:PANYARGS
Control_RunDLL TEXTEQU <__imp_Control_RunDLL>
extern __imp_Control_RunDLLA:PANYARGS
Control_RunDLL  TEXTEQU <__imp_Control_RunDLLA>
extern __imp_Control_RunDLLAsUserW:PANYARGS
Control_RunDLLAsUserW TEXTEQU <__imp_Control_RunDLLAsUserW>
extern __imp_Control_RunDLLW:PANYARGS
Control_RunDLLW TEXTEQU <__imp_Control_RunDLLW>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_IsLFNDrive:PANYARGS
IsLFNDrive TEXTEQU <__imp_IsLFNDrive>
extern __imp_DllGetVersion:PANYARGS
DllGetVersion TEXTEQU <__imp_DllGetVersion>
extern __imp_SHFlushClipboard:PANYARGS
SHFlushClipboard TEXTEQU <__imp_SHFlushClipboard>
extern __imp_shell32_ordinal122:PANYARGS
shell32_ordinal122 TEXTEQU <__imp_shell32_ordinal122>
extern __imp_shell32_ordinal123:PANYARGS
shell32_ordinal123 TEXTEQU <__imp_shell32_ordinal123>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_shell32_ordinal126:PANYARGS
shell32_ordinal126 TEXTEQU <__imp_shell32_ordinal126>
extern __imp_shell32_ordinal127:PANYARGS
shell32_ordinal127 TEXTEQU <__imp_shell32_ordinal127>
extern __imp_shell32_ordinal128:PANYARGS
shell32_ordinal128 TEXTEQU <__imp_shell32_ordinal128>
extern __imp_DAD_AutoScroll:PANYARGS
DAD_AutoScroll TEXTEQU <__imp_DAD_AutoScroll>
extern __imp_shell32_ordinal130:PANYARGS
shell32_ordinal130 TEXTEQU <__imp_shell32_ordinal130>
extern __imp_DAD_DragEnterEx:PANYARGS
DAD_DragEnterEx TEXTEQU <__imp_DAD_DragEnterEx>
extern __imp_DAD_DragLeave:PANYARGS
DAD_DragLeave TEXTEQU <__imp_DAD_DragLeave>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_DAD_DragMove:PANYARGS
DAD_DragMove TEXTEQU <__imp_DAD_DragMove>
extern __imp_DoEnvironmentSubstA:PANYARGS
DoEnvironmentSubst  TEXTEQU <__imp_DoEnvironmentSubstA>
extern __imp_DAD_SetDragImage:PANYARGS
DAD_SetDragImage TEXTEQU <__imp_DAD_SetDragImage>
extern __imp_DAD_ShowDragImage:PANYARGS
DAD_ShowDragImage TEXTEQU <__imp_DAD_ShowDragImage>
extern __imp_DoEnvironmentSubstW:PANYARGS
DoEnvironmentSubstW TEXTEQU <__imp_DoEnvironmentSubstW>
extern __imp_DragAcceptFiles:PANYARGS
DragAcceptFiles TEXTEQU <__imp_DragAcceptFiles>
extern __imp_DragFinish:PANYARGS
DragFinish TEXTEQU <__imp_DragFinish>
extern __imp_DragQueryFile:PANYARGS
DragQueryFile TEXTEQU <__imp_DragQueryFile>
extern __imp_DragQueryFileA:PANYARGS
DragQueryFile  TEXTEQU <__imp_DragQueryFileA>
extern __imp_DragQueryFileAorW:PANYARGS
DragQueryFileAorW TEXTEQU <__imp_DragQueryFileAorW>
extern __imp_DragQueryFileW:PANYARGS
DragQueryFileW TEXTEQU <__imp_DragQueryFileW>
extern __imp_shell32_ordinal145:PANYARGS
shell32_ordinal145 TEXTEQU <__imp_shell32_ordinal145>
extern __imp_shell32_ordinal146:PANYARGS
shell32_ordinal146 TEXTEQU <__imp_shell32_ordinal146>
extern __imp_SHCLSIDFromString:PANYARGS
SHCLSIDFromString TEXTEQU <__imp_SHCLSIDFromString>
extern __imp_SHMapIDListToImageListIndexAsync:PANYARGS
SHMapIDListToImageListIndexAsync TEXTEQU <__imp_SHMapIDListToImageListIndexAsync>
extern __imp_SHFind_InitMenuPopup:PANYARGS
SHFind_InitMenuPopup TEXTEQU <__imp_SHFind_InitMenuPopup>
extern __imp_DragQueryPoint:PANYARGS
DragQueryPoint TEXTEQU <__imp_DragQueryPoint>
extern __imp_SHLoadOLE:PANYARGS
SHLoadOLE TEXTEQU <__imp_SHLoadOLE>
extern __imp_ILGetSize:PANYARGS
ILGetSize TEXTEQU <__imp_ILGetSize>
extern __imp_ILGetNext:PANYARGS
ILGetNext TEXTEQU <__imp_ILGetNext>
extern __imp_ILAppendID:PANYARGS
ILAppendID TEXTEQU <__imp_ILAppendID>
extern __imp_ILFree:PANYARGS
ILFree TEXTEQU <__imp_ILFree>
extern __imp_shell32_ordinal156:PANYARGS
shell32_ordinal156 TEXTEQU <__imp_shell32_ordinal156>
extern __imp_ILCreateFromPath:PANYARGS
ILCreateFromPath TEXTEQU <__imp_ILCreateFromPath>
extern __imp_shell32_ordinal158:PANYARGS
shell32_ordinal158 TEXTEQU <__imp_shell32_ordinal158>
extern __imp_shell32_ordinal159:PANYARGS
shell32_ordinal159 TEXTEQU <__imp_shell32_ordinal159>
extern __imp_shell32_ordinal160:PANYARGS
shell32_ordinal160 TEXTEQU <__imp_shell32_ordinal160>
extern __imp_SHRunControlPanel:PANYARGS
SHRunControlPanel TEXTEQU <__imp_SHRunControlPanel>
extern __imp_SHSimpleIDListFromPath:PANYARGS
SHSimpleIDListFromPath TEXTEQU <__imp_SHSimpleIDListFromPath>
extern __imp_shell32_ordinal163:PANYARGS
shell32_ordinal163 TEXTEQU <__imp_shell32_ordinal163>
extern __imp_Win32DeleteFile:PANYARGS
Win32DeleteFile TEXTEQU <__imp_Win32DeleteFile>
extern __imp_SHCreateDirectory:PANYARGS
SHCreateDirectory TEXTEQU <__imp_SHCreateDirectory>
extern __imp_CallCPLEntry16:PANYARGS
CallCPLEntry16 TEXTEQU <__imp_CallCPLEntry16>
extern __imp_SHAddFromPropSheetExtArray:PANYARGS
SHAddFromPropSheetExtArray TEXTEQU <__imp_SHAddFromPropSheetExtArray>
extern __imp_SHCreatePropSheetExtArray:PANYARGS
SHCreatePropSheetExtArray TEXTEQU <__imp_SHCreatePropSheetExtArray>
extern __imp_SHDestroyPropSheetExtArray:PANYARGS
SHDestroyPropSheetExtArray TEXTEQU <__imp_SHDestroyPropSheetExtArray>
extern __imp_SHReplaceFromPropSheetExtArray:PANYARGS
SHReplaceFromPropSheetExtArray TEXTEQU <__imp_SHReplaceFromPropSheetExtArray>
extern __imp_PathCleanupSpec:PANYARGS
PathCleanupSpec TEXTEQU <__imp_PathCleanupSpec>
extern __imp_shell32_ordinal172:PANYARGS
shell32_ordinal172 TEXTEQU <__imp_shell32_ordinal172>
extern __imp_SHValidateUNC:PANYARGS
SHValidateUNC TEXTEQU <__imp_SHValidateUNC>
extern __imp_SHCreateShellFolderViewEx:PANYARGS
SHCreateShellFolderViewEx TEXTEQU <__imp_SHCreateShellFolderViewEx>
extern __imp_shell32_ordinal175:PANYARGS
shell32_ordinal175 TEXTEQU <__imp_shell32_ordinal175>
extern __imp_SHSetInstanceExplorer:PANYARGS
SHSetInstanceExplorer TEXTEQU <__imp_SHSetInstanceExplorer>
extern __imp_shell32_ordinal177:PANYARGS
shell32_ordinal177 TEXTEQU <__imp_shell32_ordinal177>
extern __imp_SHObjectProperties:PANYARGS
SHObjectProperties TEXTEQU <__imp_SHObjectProperties>
extern __imp_SHGetNewLinkInfoA:PANYARGS
SHGetNewLinkInfo  TEXTEQU <__imp_SHGetNewLinkInfoA>
extern __imp_SHGetNewLinkInfoW:PANYARGS
SHGetNewLinkInfoW TEXTEQU <__imp_SHGetNewLinkInfoW>
extern __imp_shell32_ordinal181:PANYARGS
shell32_ordinal181 TEXTEQU <__imp_shell32_ordinal181>
extern __imp_ShellMessageBoxW:PANYARGS
ShellMessageBoxW TEXTEQU <__imp_ShellMessageBoxW>
extern __imp_ShellMessageBoxA:PANYARGS
ShellMessageBox  TEXTEQU <__imp_ShellMessageBoxA>
extern __imp_shell32_ordinal184:PANYARGS
shell32_ordinal184 TEXTEQU <__imp_shell32_ordinal184>
extern __imp_shell32_ordinal185:PANYARGS
shell32_ordinal185 TEXTEQU <__imp_shell32_ordinal185>
extern __imp_shell32_ordinal186:PANYARGS
shell32_ordinal186 TEXTEQU <__imp_shell32_ordinal186>
extern __imp_shell32_ordinal187:PANYARGS
shell32_ordinal187 TEXTEQU <__imp_shell32_ordinal187>
extern __imp_shell32_ordinal188:PANYARGS
shell32_ordinal188 TEXTEQU <__imp_shell32_ordinal188>
extern __imp_ILCreateFromPathA:PANYARGS
ILCreateFromPath  TEXTEQU <__imp_ILCreateFromPathA>
extern __imp_ILCreateFromPathW:PANYARGS
ILCreateFromPathW TEXTEQU <__imp_ILCreateFromPathW>
extern __imp_SHUpdateImageA:PANYARGS
SHUpdateImage  TEXTEQU <__imp_SHUpdateImageA>
extern __imp_SHUpdateImageW:PANYARGS
SHUpdateImageW TEXTEQU <__imp_SHUpdateImageW>
extern __imp_SHHandleUpdateImage:PANYARGS
SHHandleUpdateImage TEXTEQU <__imp_SHHandleUpdateImage>
extern __imp_shell32_ordinal194:PANYARGS
shell32_ordinal194 TEXTEQU <__imp_shell32_ordinal194>
extern __imp_SHFree:PANYARGS
SHFree TEXTEQU <__imp_SHFree>
extern __imp_SHAlloc:PANYARGS
SHAlloc TEXTEQU <__imp_SHAlloc>
extern __imp_shell32_ordinal197:PANYARGS
shell32_ordinal197 TEXTEQU <__imp_shell32_ordinal197>
extern __imp_shell32_ordinal198:PANYARGS
shell32_ordinal198 TEXTEQU <__imp_shell32_ordinal198>
extern __imp_DuplicateIcon:PANYARGS
DuplicateIcon TEXTEQU <__imp_DuplicateIcon>
extern __imp_shell32_ordinal200:PANYARGS
shell32_ordinal200 TEXTEQU <__imp_shell32_ordinal200>
extern __imp_shell32_ordinal201:PANYARGS
shell32_ordinal201 TEXTEQU <__imp_shell32_ordinal201>
extern __imp_shell32_ordinal202:PANYARGS
shell32_ordinal202 TEXTEQU <__imp_shell32_ordinal202>
extern __imp_shell32_ordinal203:PANYARGS
shell32_ordinal203 TEXTEQU <__imp_shell32_ordinal203>
extern __imp_shell32_ordinal204:PANYARGS
shell32_ordinal204 TEXTEQU <__imp_shell32_ordinal204>
extern __imp_shell32_ordinal205:PANYARGS
shell32_ordinal205 TEXTEQU <__imp_shell32_ordinal205>
extern __imp_ExtractAssociatedIconA:PANYARGS
ExtractAssociatedIcon  TEXTEQU <__imp_ExtractAssociatedIconA>
extern __imp_ExtractAssociatedIconExA:PANYARGS
ExtractAssociatedIconEx  TEXTEQU <__imp_ExtractAssociatedIconExA>
extern __imp_ExtractAssociatedIconExW:PANYARGS
ExtractAssociatedIconExW TEXTEQU <__imp_ExtractAssociatedIconExW>
extern __imp_shell32_ordinal209:PANYARGS
shell32_ordinal209 TEXTEQU <__imp_shell32_ordinal209>
extern __imp_shell32_ordinal210:PANYARGS
shell32_ordinal210 TEXTEQU <__imp_shell32_ordinal210>
extern __imp_shell32_ordinal211:PANYARGS
shell32_ordinal211 TEXTEQU <__imp_shell32_ordinal211>
extern __imp_shell32_ordinal212:PANYARGS
shell32_ordinal212 TEXTEQU <__imp_shell32_ordinal212>
extern __imp_shell32_ordinal213:PANYARGS
shell32_ordinal213 TEXTEQU <__imp_shell32_ordinal213>
extern __imp_shell32_ordinal214:PANYARGS
shell32_ordinal214 TEXTEQU <__imp_shell32_ordinal214>
extern __imp_shell32_ordinal215:PANYARGS
shell32_ordinal215 TEXTEQU <__imp_shell32_ordinal215>
extern __imp_ExtractAssociatedIconW:PANYARGS
ExtractAssociatedIconW TEXTEQU <__imp_ExtractAssociatedIconW>
extern __imp_ExtractIconA:PANYARGS
ExtractIcon  TEXTEQU <__imp_ExtractIconA>
extern __imp_ExtractIconEx:PANYARGS
ExtractIconEx TEXTEQU <__imp_ExtractIconEx>
extern __imp_ExtractIconExA:PANYARGS
ExtractIconEx  TEXTEQU <__imp_ExtractIconExA>
extern __imp_ExtractIconExW:PANYARGS
ExtractIconExW TEXTEQU <__imp_ExtractIconExW>
extern __imp_ExtractIconResInfoA:PANYARGS
ExtractIconResInfo  TEXTEQU <__imp_ExtractIconResInfoA>
extern __imp_ExtractIconResInfoW:PANYARGS
ExtractIconResInfoW TEXTEQU <__imp_ExtractIconResInfoW>
extern __imp_ExtractIconW:PANYARGS
ExtractIconW TEXTEQU <__imp_ExtractIconW>
extern __imp_ExtractVersionResource16W:PANYARGS
ExtractVersionResource16W TEXTEQU <__imp_ExtractVersionResource16W>
extern __imp_FindExeDlgProc:PANYARGS
FindExeDlgProc TEXTEQU <__imp_FindExeDlgProc>
extern __imp_FindExecutableA:PANYARGS
FindExecutable  TEXTEQU <__imp_FindExecutableA>
extern __imp_FindExecutableW:PANYARGS
FindExecutableW TEXTEQU <__imp_FindExecutableW>
extern __imp_FreeIconList:PANYARGS
FreeIconList TEXTEQU <__imp_FreeIconList>
extern __imp_InternalExtractIconListA:PANYARGS
InternalExtractIconList  TEXTEQU <__imp_InternalExtractIconListA>
extern __imp_shell32_ordinal230:PANYARGS
shell32_ordinal230 TEXTEQU <__imp_shell32_ordinal230>
extern __imp_shell32_ordinal231:PANYARGS
shell32_ordinal231 TEXTEQU <__imp_shell32_ordinal231>
extern __imp_shell32_ordinal232:PANYARGS
shell32_ordinal232 TEXTEQU <__imp_shell32_ordinal232>
extern __imp_shell32_ordinal233:PANYARGS
shell32_ordinal233 TEXTEQU <__imp_shell32_ordinal233>
extern __imp_shell32_ordinal234:PANYARGS
shell32_ordinal234 TEXTEQU <__imp_shell32_ordinal234>
extern __imp_shell32_ordinal235:PANYARGS
shell32_ordinal235 TEXTEQU <__imp_shell32_ordinal235>
extern __imp_shell32_ordinal236:PANYARGS
shell32_ordinal236 TEXTEQU <__imp_shell32_ordinal236>
extern __imp_shell32_ordinal237:PANYARGS
shell32_ordinal237 TEXTEQU <__imp_shell32_ordinal237>
extern __imp_InternalExtractIconListW:PANYARGS
InternalExtractIconListW TEXTEQU <__imp_InternalExtractIconListW>
extern __imp_PathIsSlowW:PANYARGS
PathIsSlowW TEXTEQU <__imp_PathIsSlowW>
extern __imp_PathIsSlowA:PANYARGS
PathIsSlow  TEXTEQU <__imp_PathIsSlowA>
extern __imp_shell32_ordinal241:PANYARGS
shell32_ordinal241 TEXTEQU <__imp_shell32_ordinal241>
extern __imp_shell32_ordinal242:PANYARGS
shell32_ordinal242 TEXTEQU <__imp_shell32_ordinal242>
extern __imp_shell32_ordinal243:PANYARGS
shell32_ordinal243 TEXTEQU <__imp_shell32_ordinal243>
extern __imp_shell32_ordinal244:PANYARGS
shell32_ordinal244 TEXTEQU <__imp_shell32_ordinal244>
extern __imp_SHTestTokenMembership:PANYARGS
SHTestTokenMembership TEXTEQU <__imp_SHTestTokenMembership>
extern __imp_shell32_ordinal246:PANYARGS
shell32_ordinal246 TEXTEQU <__imp_shell32_ordinal246>
extern __imp_shell32_ordinal247:PANYARGS
shell32_ordinal247 TEXTEQU <__imp_shell32_ordinal247>
extern __imp_shell32_ordinal248:PANYARGS
shell32_ordinal248 TEXTEQU <__imp_shell32_ordinal248>
extern __imp_shell32_ordinal249:PANYARGS
shell32_ordinal249 TEXTEQU <__imp_shell32_ordinal249>
extern __imp_shell32_ordinal250:PANYARGS
shell32_ordinal250 TEXTEQU <__imp_shell32_ordinal250>
extern __imp_shell32_ordinal251:PANYARGS
shell32_ordinal251 TEXTEQU <__imp_shell32_ordinal251>
extern __imp_shell32_ordinal252:PANYARGS
shell32_ordinal252 TEXTEQU <__imp_shell32_ordinal252>
extern __imp_shell32_ordinal253:PANYARGS
shell32_ordinal253 TEXTEQU <__imp_shell32_ordinal253>
extern __imp_shell32_ordinal254:PANYARGS
shell32_ordinal254 TEXTEQU <__imp_shell32_ordinal254>
extern __imp_Options_RunDLL:PANYARGS
Options_RunDLL TEXTEQU <__imp_Options_RunDLL>
extern __imp_SHCreateShellFolderView:PANYARGS
SHCreateShellFolderView TEXTEQU <__imp_SHCreateShellFolderView>
extern __imp_shell32_ordinal257:PANYARGS
shell32_ordinal257 TEXTEQU <__imp_shell32_ordinal257>
extern __imp_shell32_ordinal258:PANYARGS
shell32_ordinal258 TEXTEQU <__imp_shell32_ordinal258>
extern __imp_shell32_ordinal259:PANYARGS
shell32_ordinal259 TEXTEQU <__imp_shell32_ordinal259>
extern __imp_Options_RunDLLA:PANYARGS
Options_RunDLL  TEXTEQU <__imp_Options_RunDLLA>
extern __imp_Options_RunDLLW:PANYARGS
Options_RunDLLW TEXTEQU <__imp_Options_RunDLLW>
extern __imp_PrintersGetCommand_RunDLL:PANYARGS
PrintersGetCommand_RunDLL TEXTEQU <__imp_PrintersGetCommand_RunDLL>
extern __imp_PrintersGetCommand_RunDLLA:PANYARGS
PrintersGetCommand_RunDLL  TEXTEQU <__imp_PrintersGetCommand_RunDLLA>
extern __imp_PrintersGetCommand_RunDLLW:PANYARGS
PrintersGetCommand_RunDLLW TEXTEQU <__imp_PrintersGetCommand_RunDLLW>
extern __imp_RealShellExecuteA:PANYARGS
RealShellExecute  TEXTEQU <__imp_RealShellExecuteA>
extern __imp_RealShellExecuteExA:PANYARGS
RealShellExecuteEx  TEXTEQU <__imp_RealShellExecuteExA>
extern __imp_RealShellExecuteExW:PANYARGS
RealShellExecuteExW TEXTEQU <__imp_RealShellExecuteExW>
extern __imp_RealShellExecuteW:PANYARGS
RealShellExecuteW TEXTEQU <__imp_RealShellExecuteW>
extern __imp_RegenerateUserEnvironment:PANYARGS
RegenerateUserEnvironment TEXTEQU <__imp_RegenerateUserEnvironment>
extern __imp_SHAddToRecentDocs:PANYARGS
SHAddToRecentDocs TEXTEQU <__imp_SHAddToRecentDocs>
extern __imp_SHAppBarMessage:PANYARGS
SHAppBarMessage TEXTEQU <__imp_SHAppBarMessage>
extern __imp_SHBindToParent:PANYARGS
SHBindToParent TEXTEQU <__imp_SHBindToParent>
extern __imp_SHBrowseForFolder:PANYARGS
SHBrowseForFolder TEXTEQU <__imp_SHBrowseForFolder>
extern __imp_SHBrowseForFolderA:PANYARGS
SHBrowseForFolder  TEXTEQU <__imp_SHBrowseForFolderA>
extern __imp_SHBrowseForFolderW:PANYARGS
SHBrowseForFolderW TEXTEQU <__imp_SHBrowseForFolderW>
extern __imp_SHChangeNotify:PANYARGS
SHChangeNotify TEXTEQU <__imp_SHChangeNotify>
extern __imp_SHChangeNotifySuspendResume:PANYARGS
SHChangeNotifySuspendResume TEXTEQU <__imp_SHChangeNotifySuspendResume>
extern __imp_SHCreateDirectoryExA:PANYARGS
SHCreateDirectoryEx  TEXTEQU <__imp_SHCreateDirectoryExA>
extern __imp_SHCreateDirectoryExW:PANYARGS
SHCreateDirectoryExW TEXTEQU <__imp_SHCreateDirectoryExW>
extern __imp_SHCreateLocalServerRunDll:PANYARGS
SHCreateLocalServerRunDll TEXTEQU <__imp_SHCreateLocalServerRunDll>
extern __imp_SHCreateProcessAsUserW:PANYARGS
SHCreateProcessAsUserW TEXTEQU <__imp_SHCreateProcessAsUserW>
extern __imp_SHCreateQueryCancelAutoPlayMoniker:PANYARGS
SHCreateQueryCancelAutoPlayMoniker TEXTEQU <__imp_SHCreateQueryCancelAutoPlayMoniker>
extern __imp_SHCreateShellItem:PANYARGS
SHCreateShellItem TEXTEQU <__imp_SHCreateShellItem>
extern __imp_SHEmptyRecycleBinA:PANYARGS
SHEmptyRecycleBin  TEXTEQU <__imp_SHEmptyRecycleBinA>
extern __imp_SHEmptyRecycleBinW:PANYARGS
SHEmptyRecycleBinW TEXTEQU <__imp_SHEmptyRecycleBinW>
extern __imp_SHEnableServiceObject:PANYARGS
SHEnableServiceObject TEXTEQU <__imp_SHEnableServiceObject>
extern __imp_SHEnumerateUnreadMailAccountsW:PANYARGS
SHEnumerateUnreadMailAccountsW TEXTEQU <__imp_SHEnumerateUnreadMailAccountsW>
extern __imp_SHExtractIconsW:PANYARGS
SHExtractIconsW TEXTEQU <__imp_SHExtractIconsW>
extern __imp_SHFileOperation:PANYARGS
SHFileOperation TEXTEQU <__imp_SHFileOperation>
extern __imp_SHFileOperationA:PANYARGS
SHFileOperation  TEXTEQU <__imp_SHFileOperationA>
extern __imp_SHFileOperationW:PANYARGS
SHFileOperationW TEXTEQU <__imp_SHFileOperationW>
extern __imp_SHFormatDrive:PANYARGS
SHFormatDrive TEXTEQU <__imp_SHFormatDrive>
extern __imp_SHFreeNameMappings:PANYARGS
SHFreeNameMappings TEXTEQU <__imp_SHFreeNameMappings>
extern __imp_SHGetDataFromIDListA:PANYARGS
SHGetDataFromIDList  TEXTEQU <__imp_SHGetDataFromIDListA>
extern __imp_SHGetDataFromIDListW:PANYARGS
SHGetDataFromIDListW TEXTEQU <__imp_SHGetDataFromIDListW>
extern __imp_SHGetDesktopFolder:PANYARGS
SHGetDesktopFolder TEXTEQU <__imp_SHGetDesktopFolder>
extern __imp_SHGetDiskFreeSpaceA:PANYARGS
SHGetDiskFreeSpace  TEXTEQU <__imp_SHGetDiskFreeSpaceA>
extern __imp_SHGetDiskFreeSpaceExA:PANYARGS
SHGetDiskFreeSpaceEx  TEXTEQU <__imp_SHGetDiskFreeSpaceExA>
extern __imp_SHGetDiskFreeSpaceExW:PANYARGS
SHGetDiskFreeSpaceExW TEXTEQU <__imp_SHGetDiskFreeSpaceExW>
extern __imp_SHGetFileInfo:PANYARGS
SHGetFileInfo TEXTEQU <__imp_SHGetFileInfo>
extern __imp_SHGetFileInfoA:PANYARGS
SHGetFileInfo  TEXTEQU <__imp_SHGetFileInfoA>
extern __imp_SHGetFileInfoW:PANYARGS
SHGetFileInfoW TEXTEQU <__imp_SHGetFileInfoW>
extern __imp_SHGetFolderLocation:PANYARGS
SHGetFolderLocation TEXTEQU <__imp_SHGetFolderLocation>
extern __imp_SHGetFolderPathA:PANYARGS
SHGetFolderPath  TEXTEQU <__imp_SHGetFolderPathA>
extern __imp_SHGetFolderPathAndSubDirA:PANYARGS
SHGetFolderPathAndSubDir  TEXTEQU <__imp_SHGetFolderPathAndSubDirA>
extern __imp_SHGetFolderPathAndSubDirW:PANYARGS
SHGetFolderPathAndSubDirW TEXTEQU <__imp_SHGetFolderPathAndSubDirW>
extern __imp_SHGetFolderPathW:PANYARGS
SHGetFolderPathW TEXTEQU <__imp_SHGetFolderPathW>
extern __imp_SHGetIconOverlayIndexA:PANYARGS
SHGetIconOverlayIndex  TEXTEQU <__imp_SHGetIconOverlayIndexA>
extern __imp_SHGetIconOverlayIndexW:PANYARGS
SHGetIconOverlayIndexW TEXTEQU <__imp_SHGetIconOverlayIndexW>
extern __imp_SHGetInstanceExplorer:PANYARGS
SHGetInstanceExplorer TEXTEQU <__imp_SHGetInstanceExplorer>
extern __imp_SHGetMalloc:PANYARGS
SHGetMalloc TEXTEQU <__imp_SHGetMalloc>
extern __imp_SHGetNewLinkInfo:PANYARGS
SHGetNewLinkInfo TEXTEQU <__imp_SHGetNewLinkInfo>
extern __imp_SHGetPathFromIDList:PANYARGS
SHGetPathFromIDList TEXTEQU <__imp_SHGetPathFromIDList>
extern __imp_SHGetPathFromIDListA:PANYARGS
SHGetPathFromIDList  TEXTEQU <__imp_SHGetPathFromIDListA>
extern __imp_SHGetPathFromIDListW:PANYARGS
SHGetPathFromIDListW TEXTEQU <__imp_SHGetPathFromIDListW>
extern __imp_SHGetSettings:PANYARGS
SHGetSettings TEXTEQU <__imp_SHGetSettings>
extern __imp_SHGetSpecialFolderLocation:PANYARGS
SHGetSpecialFolderLocation TEXTEQU <__imp_SHGetSpecialFolderLocation>
extern __imp_SHGetSpecialFolderPathA:PANYARGS
SHGetSpecialFolderPath  TEXTEQU <__imp_SHGetSpecialFolderPathA>
extern __imp_SHGetSpecialFolderPathW:PANYARGS
SHGetSpecialFolderPathW TEXTEQU <__imp_SHGetSpecialFolderPathW>
extern __imp_SHGetUnreadMailCountW:PANYARGS
SHGetUnreadMailCountW TEXTEQU <__imp_SHGetUnreadMailCountW>
extern __imp_SHHelpShortcuts_RunDLL:PANYARGS
SHHelpShortcuts_RunDLL TEXTEQU <__imp_SHHelpShortcuts_RunDLL>
extern __imp_SHHelpShortcuts_RunDLLA:PANYARGS
SHHelpShortcuts_RunDLL  TEXTEQU <__imp_SHHelpShortcuts_RunDLLA>
extern __imp_SHHelpShortcuts_RunDLLW:PANYARGS
SHHelpShortcuts_RunDLLW TEXTEQU <__imp_SHHelpShortcuts_RunDLLW>
extern __imp_SHInvokePrinterCommandA:PANYARGS
SHInvokePrinterCommand  TEXTEQU <__imp_SHInvokePrinterCommandA>
extern __imp_SHInvokePrinterCommandW:PANYARGS
SHInvokePrinterCommandW TEXTEQU <__imp_SHInvokePrinterCommandW>
extern __imp_SHIsFileAvailableOffline:PANYARGS
SHIsFileAvailableOffline TEXTEQU <__imp_SHIsFileAvailableOffline>
extern __imp_SHLoadInProc:PANYARGS
SHLoadInProc TEXTEQU <__imp_SHLoadInProc>
extern __imp_SHLoadNonloadedIconOverlayIdentifiers:PANYARGS
SHLoadNonloadedIconOverlayIdentifiers TEXTEQU <__imp_SHLoadNonloadedIconOverlayIdentifiers>
extern __imp_SHOpenFolderAndSelectItems:PANYARGS
SHOpenFolderAndSelectItems TEXTEQU <__imp_SHOpenFolderAndSelectItems>
extern __imp_SHParseDisplayName:PANYARGS
SHParseDisplayName TEXTEQU <__imp_SHParseDisplayName>
extern __imp_SHPathPrepareForWriteA:PANYARGS
SHPathPrepareForWrite  TEXTEQU <__imp_SHPathPrepareForWriteA>
extern __imp_SHPathPrepareForWriteW:PANYARGS
SHPathPrepareForWriteW TEXTEQU <__imp_SHPathPrepareForWriteW>
extern __imp_SHQueryRecycleBinA:PANYARGS
SHQueryRecycleBin  TEXTEQU <__imp_SHQueryRecycleBinA>
extern __imp_SHQueryRecycleBinW:PANYARGS
SHQueryRecycleBinW TEXTEQU <__imp_SHQueryRecycleBinW>
extern __imp_SHSetLocalizedName:PANYARGS
SHSetLocalizedName TEXTEQU <__imp_SHSetLocalizedName>
extern __imp_SHSetUnreadMailCountW:PANYARGS
SHSetUnreadMailCountW TEXTEQU <__imp_SHSetUnreadMailCountW>
extern __imp_SHUpdateRecycleBinIcon:PANYARGS
SHUpdateRecycleBinIcon TEXTEQU <__imp_SHUpdateRecycleBinIcon>
extern __imp_SheChangeDirA:PANYARGS
SheChangeDir  TEXTEQU <__imp_SheChangeDirA>
extern __imp_SheChangeDirExA:PANYARGS
SheChangeDirEx  TEXTEQU <__imp_SheChangeDirExA>
extern __imp_SheChangeDirExW:PANYARGS
SheChangeDirExW TEXTEQU <__imp_SheChangeDirExW>
extern __imp_SheChangeDirW:PANYARGS
SheChangeDirW TEXTEQU <__imp_SheChangeDirW>
extern __imp_SheConvertPathW:PANYARGS
SheConvertPathW TEXTEQU <__imp_SheConvertPathW>
extern __imp_SheFullPathA:PANYARGS
SheFullPath  TEXTEQU <__imp_SheFullPathA>
extern __imp_SheFullPathW:PANYARGS
SheFullPathW TEXTEQU <__imp_SheFullPathW>
extern __imp_SheGetCurDrive:PANYARGS
SheGetCurDrive TEXTEQU <__imp_SheGetCurDrive>
extern __imp_SheGetDirA:PANYARGS
SheGetDir  TEXTEQU <__imp_SheGetDirA>
extern __imp_SheGetDirExW:PANYARGS
SheGetDirExW TEXTEQU <__imp_SheGetDirExW>
extern __imp_SheGetDirW:PANYARGS
SheGetDirW TEXTEQU <__imp_SheGetDirW>
extern __imp_SheGetPathOffsetW:PANYARGS
SheGetPathOffsetW TEXTEQU <__imp_SheGetPathOffsetW>
extern __imp_SheRemoveQuotesA:PANYARGS
SheRemoveQuotes  TEXTEQU <__imp_SheRemoveQuotesA>
extern __imp_SheRemoveQuotesW:PANYARGS
SheRemoveQuotesW TEXTEQU <__imp_SheRemoveQuotesW>
extern __imp_SheSetCurDrive:PANYARGS
SheSetCurDrive TEXTEQU <__imp_SheSetCurDrive>
extern __imp_SheShortenPathA:PANYARGS
SheShortenPath  TEXTEQU <__imp_SheShortenPathA>
extern __imp_SheShortenPathW:PANYARGS
SheShortenPathW TEXTEQU <__imp_SheShortenPathW>
extern __imp_ShellAboutA:PANYARGS
ShellAbout  TEXTEQU <__imp_ShellAboutA>
extern __imp_ShellAboutW:PANYARGS
ShellAboutW TEXTEQU <__imp_ShellAboutW>
extern __imp_ShellExec_RunDLL:PANYARGS
ShellExec_RunDLL TEXTEQU <__imp_ShellExec_RunDLL>
extern __imp_ShellExec_RunDLLA:PANYARGS
ShellExec_RunDLL  TEXTEQU <__imp_ShellExec_RunDLLA>
extern __imp_ShellExec_RunDLLW:PANYARGS
ShellExec_RunDLLW TEXTEQU <__imp_ShellExec_RunDLLW>
extern __imp_ShellExecuteA:PANYARGS
ShellExecute  TEXTEQU <__imp_ShellExecuteA>
extern __imp_ShellExecuteEx:PANYARGS
ShellExecuteEx TEXTEQU <__imp_ShellExecuteEx>
extern __imp_ShellExecuteExA:PANYARGS
ShellExecuteEx  TEXTEQU <__imp_ShellExecuteExA>
extern __imp_ShellExecuteExW:PANYARGS
ShellExecuteExW TEXTEQU <__imp_ShellExecuteExW>
extern __imp_ShellExecuteW:PANYARGS
ShellExecuteW TEXTEQU <__imp_ShellExecuteW>
extern __imp_ShellHookProc:PANYARGS
ShellHookProc TEXTEQU <__imp_ShellHookProc>
extern __imp_Shell_NotifyIcon:PANYARGS
Shell_NotifyIcon TEXTEQU <__imp_Shell_NotifyIcon>
extern __imp_Shell_NotifyIconA:PANYARGS
Shell_NotifyIcon  TEXTEQU <__imp_Shell_NotifyIconA>
extern __imp_Shell_NotifyIconW:PANYARGS
Shell_NotifyIconW TEXTEQU <__imp_Shell_NotifyIconW>
extern __imp_StrChrA:PANYARGS
StrChr  TEXTEQU <__imp_StrChrA>
extern __imp_StrChrIA:PANYARGS
StrChrI  TEXTEQU <__imp_StrChrIA>
extern __imp_StrChrIW:PANYARGS
StrChrIW TEXTEQU <__imp_StrChrIW>
extern __imp_StrChrW:PANYARGS
StrChrW TEXTEQU <__imp_StrChrW>
extern __imp_StrCmpNA:PANYARGS
StrCmpN  TEXTEQU <__imp_StrCmpNA>
extern __imp_StrCmpNIA:PANYARGS
StrCmpNI  TEXTEQU <__imp_StrCmpNIA>
extern __imp_StrCmpNIW:PANYARGS
StrCmpNIW TEXTEQU <__imp_StrCmpNIW>
extern __imp_StrCmpNW:PANYARGS
StrCmpNW TEXTEQU <__imp_StrCmpNW>
extern __imp_StrCpyNA:PANYARGS
StrCpyN  TEXTEQU <__imp_StrCpyNA>
extern __imp_StrCpyNW:PANYARGS
StrCpyNW TEXTEQU <__imp_StrCpyNW>
extern __imp_StrNCmpA:PANYARGS
StrNCmp  TEXTEQU <__imp_StrNCmpA>
extern __imp_StrNCmpIA:PANYARGS
StrNCmpI  TEXTEQU <__imp_StrNCmpIA>
extern __imp_StrNCmpIW:PANYARGS
StrNCmpIW TEXTEQU <__imp_StrNCmpIW>
extern __imp_StrNCmpW:PANYARGS
StrNCmpW TEXTEQU <__imp_StrNCmpW>
extern __imp_StrNCpyA:PANYARGS
StrNCpy  TEXTEQU <__imp_StrNCpyA>
extern __imp_StrNCpyW:PANYARGS
StrNCpyW TEXTEQU <__imp_StrNCpyW>
extern __imp_StrRChrA:PANYARGS
StrRChr  TEXTEQU <__imp_StrRChrA>
extern __imp_StrRChrIA:PANYARGS
StrRChrI  TEXTEQU <__imp_StrRChrIA>
extern __imp_StrRChrIW:PANYARGS
StrRChrIW TEXTEQU <__imp_StrRChrIW>
extern __imp_StrRChrW:PANYARGS
StrRChrW TEXTEQU <__imp_StrRChrW>
extern __imp_StrRStrA:PANYARGS
StrRStr  TEXTEQU <__imp_StrRStrA>
extern __imp_StrRStrIA:PANYARGS
StrRStrI  TEXTEQU <__imp_StrRStrIA>
extern __imp_StrRStrIW:PANYARGS
StrRStrIW TEXTEQU <__imp_StrRStrIW>
extern __imp_StrRStrW:PANYARGS
StrRStrW TEXTEQU <__imp_StrRStrW>
extern __imp_StrStrA:PANYARGS
StrStr  TEXTEQU <__imp_StrStrA>
extern __imp_StrStrIA:PANYARGS
StrStrI  TEXTEQU <__imp_StrStrIA>
extern __imp_StrStrIW:PANYARGS
StrStrIW TEXTEQU <__imp_StrStrIW>
extern __imp_StrStrW:PANYARGS
StrStrW TEXTEQU <__imp_StrStrW>
extern __imp_WOWShellExecute:PANYARGS
WOWShellExecute TEXTEQU <__imp_WOWShellExecute>
extern __imp_shell32_ordinal398:PANYARGS
shell32_ordinal398 TEXTEQU <__imp_shell32_ordinal398>
extern __imp_shell32_ordinal399:PANYARGS
shell32_ordinal399 TEXTEQU <__imp_shell32_ordinal399>
extern __imp_shell32_ordinal400:PANYARGS
shell32_ordinal400 TEXTEQU <__imp_shell32_ordinal400>
extern __imp_shell32_ordinal401:PANYARGS
shell32_ordinal401 TEXTEQU <__imp_shell32_ordinal401>
extern __imp_shell32_ordinal402:PANYARGS
shell32_ordinal402 TEXTEQU <__imp_shell32_ordinal402>
extern __imp_shell32_ordinal403:PANYARGS
shell32_ordinal403 TEXTEQU <__imp_shell32_ordinal403>
extern __imp_shell32_ordinal404:PANYARGS
shell32_ordinal404 TEXTEQU <__imp_shell32_ordinal404>
extern __imp_shell32_ordinal405:PANYARGS
shell32_ordinal405 TEXTEQU <__imp_shell32_ordinal405>
extern __imp_shell32_ordinal406:PANYARGS
shell32_ordinal406 TEXTEQU <__imp_shell32_ordinal406>
extern __imp_shell32_ordinal407:PANYARGS
shell32_ordinal407 TEXTEQU <__imp_shell32_ordinal407>
extern __imp_shell32_ordinal408:PANYARGS
shell32_ordinal408 TEXTEQU <__imp_shell32_ordinal408>
extern __imp_shell32_ordinal409:PANYARGS
shell32_ordinal409 TEXTEQU <__imp_shell32_ordinal409>
extern __imp_shell32_ordinal410:PANYARGS
shell32_ordinal410 TEXTEQU <__imp_shell32_ordinal410>
extern __imp_shell32_ordinal411:PANYARGS
shell32_ordinal411 TEXTEQU <__imp_shell32_ordinal411>
extern __imp_shell32_ordinal412:PANYARGS
shell32_ordinal412 TEXTEQU <__imp_shell32_ordinal412>
extern __imp_shell32_ordinal413:PANYARGS
shell32_ordinal413 TEXTEQU <__imp_shell32_ordinal413>
extern __imp_shell32_ordinal414:PANYARGS
shell32_ordinal414 TEXTEQU <__imp_shell32_ordinal414>
extern __imp_shell32_ordinal415:PANYARGS
shell32_ordinal415 TEXTEQU <__imp_shell32_ordinal415>
extern __imp_shell32_ordinal416:PANYARGS
shell32_ordinal416 TEXTEQU <__imp_shell32_ordinal416>
extern __imp_shell32_ordinal417:PANYARGS
shell32_ordinal417 TEXTEQU <__imp_shell32_ordinal417>
extern __imp_shell32_ordinal418:PANYARGS
shell32_ordinal418 TEXTEQU <__imp_shell32_ordinal418>
extern __imp_shell32_ordinal419:PANYARGS
shell32_ordinal419 TEXTEQU <__imp_shell32_ordinal419>
extern __imp_shell32_ordinal420:PANYARGS
shell32_ordinal420 TEXTEQU <__imp_shell32_ordinal420>
extern __imp_shell32_ordinal421:PANYARGS
shell32_ordinal421 TEXTEQU <__imp_shell32_ordinal421>
extern __imp_shell32_ordinal422:PANYARGS
shell32_ordinal422 TEXTEQU <__imp_shell32_ordinal422>
extern __imp_shell32_ordinal423:PANYARGS
shell32_ordinal423 TEXTEQU <__imp_shell32_ordinal423>
extern __imp_shell32_ordinal424:PANYARGS
shell32_ordinal424 TEXTEQU <__imp_shell32_ordinal424>
extern __imp_shell32_ordinal425:PANYARGS
shell32_ordinal425 TEXTEQU <__imp_shell32_ordinal425>
extern __imp_shell32_ordinal426:PANYARGS
shell32_ordinal426 TEXTEQU <__imp_shell32_ordinal426>
extern __imp_shell32_ordinal427:PANYARGS
shell32_ordinal427 TEXTEQU <__imp_shell32_ordinal427>
extern __imp_shell32_ordinal428:PANYARGS
shell32_ordinal428 TEXTEQU <__imp_shell32_ordinal428>
extern __imp_shell32_ordinal429:PANYARGS
shell32_ordinal429 TEXTEQU <__imp_shell32_ordinal429>
extern __imp_shell32_ordinal430:PANYARGS
shell32_ordinal430 TEXTEQU <__imp_shell32_ordinal430>
extern __imp_shell32_ordinal431:PANYARGS
shell32_ordinal431 TEXTEQU <__imp_shell32_ordinal431>
extern __imp_shell32_ordinal432:PANYARGS
shell32_ordinal432 TEXTEQU <__imp_shell32_ordinal432>
extern __imp_shell32_ordinal433:PANYARGS
shell32_ordinal433 TEXTEQU <__imp_shell32_ordinal433>
extern __imp_shell32_ordinal434:PANYARGS
shell32_ordinal434 TEXTEQU <__imp_shell32_ordinal434>
extern __imp_shell32_ordinal435:PANYARGS
shell32_ordinal435 TEXTEQU <__imp_shell32_ordinal435>
extern __imp_shell32_ordinal436:PANYARGS
shell32_ordinal436 TEXTEQU <__imp_shell32_ordinal436>
extern __imp_shell32_ordinal437:PANYARGS
shell32_ordinal437 TEXTEQU <__imp_shell32_ordinal437>
extern __imp_shell32_ordinal438:PANYARGS
shell32_ordinal438 TEXTEQU <__imp_shell32_ordinal438>
extern __imp_shell32_ordinal439:PANYARGS
shell32_ordinal439 TEXTEQU <__imp_shell32_ordinal439>
extern __imp_shell32_ordinal440:PANYARGS
shell32_ordinal440 TEXTEQU <__imp_shell32_ordinal440>
extern __imp_shell32_ordinal441:PANYARGS
shell32_ordinal441 TEXTEQU <__imp_shell32_ordinal441>
extern __imp_shell32_ordinal442:PANYARGS
shell32_ordinal442 TEXTEQU <__imp_shell32_ordinal442>
extern __imp_shell32_ordinal443:PANYARGS
shell32_ordinal443 TEXTEQU <__imp_shell32_ordinal443>
extern __imp_shell32_ordinal444:PANYARGS
shell32_ordinal444 TEXTEQU <__imp_shell32_ordinal444>
extern __imp_shell32_ordinal445:PANYARGS
shell32_ordinal445 TEXTEQU <__imp_shell32_ordinal445>
extern __imp_shell32_ordinal446:PANYARGS
shell32_ordinal446 TEXTEQU <__imp_shell32_ordinal446>
extern __imp_shell32_ordinal447:PANYARGS
shell32_ordinal447 TEXTEQU <__imp_shell32_ordinal447>
extern __imp_shell32_ordinal448:PANYARGS
shell32_ordinal448 TEXTEQU <__imp_shell32_ordinal448>
extern __imp_shell32_ordinal449:PANYARGS
shell32_ordinal449 TEXTEQU <__imp_shell32_ordinal449>
extern __imp_shell32_ordinal450:PANYARGS
shell32_ordinal450 TEXTEQU <__imp_shell32_ordinal450>
extern __imp_shell32_ordinal451:PANYARGS
shell32_ordinal451 TEXTEQU <__imp_shell32_ordinal451>
extern __imp_shell32_ordinal452:PANYARGS
shell32_ordinal452 TEXTEQU <__imp_shell32_ordinal452>
extern __imp_shell32_ordinal453:PANYARGS
shell32_ordinal453 TEXTEQU <__imp_shell32_ordinal453>
extern __imp_shell32_ordinal454:PANYARGS
shell32_ordinal454 TEXTEQU <__imp_shell32_ordinal454>
extern __imp_shell32_ordinal455:PANYARGS
shell32_ordinal455 TEXTEQU <__imp_shell32_ordinal455>
extern __imp_shell32_ordinal456:PANYARGS
shell32_ordinal456 TEXTEQU <__imp_shell32_ordinal456>
extern __imp_shell32_ordinal457:PANYARGS
shell32_ordinal457 TEXTEQU <__imp_shell32_ordinal457>
extern __imp_shell32_ordinal458:PANYARGS
shell32_ordinal458 TEXTEQU <__imp_shell32_ordinal458>
extern __imp_shell32_ordinal459:PANYARGS
shell32_ordinal459 TEXTEQU <__imp_shell32_ordinal459>
extern __imp_shell32_ordinal460:PANYARGS
shell32_ordinal460 TEXTEQU <__imp_shell32_ordinal460>
extern __imp_shell32_ordinal461:PANYARGS
shell32_ordinal461 TEXTEQU <__imp_shell32_ordinal461>
extern __imp_shell32_ordinal462:PANYARGS
shell32_ordinal462 TEXTEQU <__imp_shell32_ordinal462>
extern __imp_shell32_ordinal463:PANYARGS
shell32_ordinal463 TEXTEQU <__imp_shell32_ordinal463>
extern __imp_shell32_ordinal464:PANYARGS
shell32_ordinal464 TEXTEQU <__imp_shell32_ordinal464>
extern __imp_shell32_ordinal465:PANYARGS
shell32_ordinal465 TEXTEQU <__imp_shell32_ordinal465>
extern __imp_shell32_ordinal466:PANYARGS
shell32_ordinal466 TEXTEQU <__imp_shell32_ordinal466>
extern __imp_shell32_ordinal467:PANYARGS
shell32_ordinal467 TEXTEQU <__imp_shell32_ordinal467>
extern __imp_shell32_ordinal468:PANYARGS
shell32_ordinal468 TEXTEQU <__imp_shell32_ordinal468>
extern __imp_shell32_ordinal469:PANYARGS
shell32_ordinal469 TEXTEQU <__imp_shell32_ordinal469>
extern __imp_shell32_ordinal470:PANYARGS
shell32_ordinal470 TEXTEQU <__imp_shell32_ordinal470>
extern __imp_shell32_ordinal471:PANYARGS
shell32_ordinal471 TEXTEQU <__imp_shell32_ordinal471>
extern __imp_shell32_ordinal472:PANYARGS
shell32_ordinal472 TEXTEQU <__imp_shell32_ordinal472>
extern __imp_shell32_ordinal473:PANYARGS
shell32_ordinal473 TEXTEQU <__imp_shell32_ordinal473>
extern __imp_shell32_ordinal474:PANYARGS
shell32_ordinal474 TEXTEQU <__imp_shell32_ordinal474>
extern __imp_shell32_ordinal475:PANYARGS
shell32_ordinal475 TEXTEQU <__imp_shell32_ordinal475>
extern __imp_shell32_ordinal476:PANYARGS
shell32_ordinal476 TEXTEQU <__imp_shell32_ordinal476>
extern __imp_shell32_ordinal477:PANYARGS
shell32_ordinal477 TEXTEQU <__imp_shell32_ordinal477>
extern __imp_shell32_ordinal478:PANYARGS
shell32_ordinal478 TEXTEQU <__imp_shell32_ordinal478>
extern __imp_shell32_ordinal479:PANYARGS
shell32_ordinal479 TEXTEQU <__imp_shell32_ordinal479>
extern __imp_shell32_ordinal480:PANYARGS
shell32_ordinal480 TEXTEQU <__imp_shell32_ordinal480>
extern __imp_shell32_ordinal481:PANYARGS
shell32_ordinal481 TEXTEQU <__imp_shell32_ordinal481>
extern __imp_shell32_ordinal482:PANYARGS
shell32_ordinal482 TEXTEQU <__imp_shell32_ordinal482>
extern __imp_shell32_ordinal483:PANYARGS
shell32_ordinal483 TEXTEQU <__imp_shell32_ordinal483>
extern __imp_shell32_ordinal484:PANYARGS
shell32_ordinal484 TEXTEQU <__imp_shell32_ordinal484>
extern __imp_shell32_ordinal485:PANYARGS
shell32_ordinal485 TEXTEQU <__imp_shell32_ordinal485>
extern __imp_shell32_ordinal486:PANYARGS
shell32_ordinal486 TEXTEQU <__imp_shell32_ordinal486>
extern __imp_shell32_ordinal487:PANYARGS
shell32_ordinal487 TEXTEQU <__imp_shell32_ordinal487>
extern __imp_shell32_ordinal488:PANYARGS
shell32_ordinal488 TEXTEQU <__imp_shell32_ordinal488>
extern __imp_shell32_ordinal489:PANYARGS
shell32_ordinal489 TEXTEQU <__imp_shell32_ordinal489>
extern __imp_shell32_ordinal490:PANYARGS
shell32_ordinal490 TEXTEQU <__imp_shell32_ordinal490>
extern __imp_shell32_ordinal491:PANYARGS
shell32_ordinal491 TEXTEQU <__imp_shell32_ordinal491>
extern __imp_shell32_ordinal492:PANYARGS
shell32_ordinal492 TEXTEQU <__imp_shell32_ordinal492>
extern __imp_shell32_ordinal493:PANYARGS
shell32_ordinal493 TEXTEQU <__imp_shell32_ordinal493>
extern __imp_shell32_ordinal494:PANYARGS
shell32_ordinal494 TEXTEQU <__imp_shell32_ordinal494>
extern __imp_shell32_ordinal495:PANYARGS
shell32_ordinal495 TEXTEQU <__imp_shell32_ordinal495>
extern __imp_shell32_ordinal496:PANYARGS
shell32_ordinal496 TEXTEQU <__imp_shell32_ordinal496>
extern __imp_shell32_ordinal497:PANYARGS
shell32_ordinal497 TEXTEQU <__imp_shell32_ordinal497>
extern __imp_shell32_ordinal498:PANYARGS
shell32_ordinal498 TEXTEQU <__imp_shell32_ordinal498>
extern __imp_shell32_ordinal499:PANYARGS
shell32_ordinal499 TEXTEQU <__imp_shell32_ordinal499>
extern __imp_shell32_ordinal500:PANYARGS
shell32_ordinal500 TEXTEQU <__imp_shell32_ordinal500>
extern __imp_shell32_ordinal501:PANYARGS
shell32_ordinal501 TEXTEQU <__imp_shell32_ordinal501>
extern __imp_shell32_ordinal502:PANYARGS
shell32_ordinal502 TEXTEQU <__imp_shell32_ordinal502>
extern __imp_shell32_ordinal503:PANYARGS
shell32_ordinal503 TEXTEQU <__imp_shell32_ordinal503>
extern __imp_shell32_ordinal504:PANYARGS
shell32_ordinal504 TEXTEQU <__imp_shell32_ordinal504>
extern __imp_shell32_ordinal505:PANYARGS
shell32_ordinal505 TEXTEQU <__imp_shell32_ordinal505>
extern __imp_shell32_ordinal506:PANYARGS
shell32_ordinal506 TEXTEQU <__imp_shell32_ordinal506>
extern __imp_shell32_ordinal507:PANYARGS
shell32_ordinal507 TEXTEQU <__imp_shell32_ordinal507>
extern __imp_shell32_ordinal508:PANYARGS
shell32_ordinal508 TEXTEQU <__imp_shell32_ordinal508>
extern __imp_shell32_ordinal509:PANYARGS
shell32_ordinal509 TEXTEQU <__imp_shell32_ordinal509>
extern __imp_shell32_ordinal510:PANYARGS
shell32_ordinal510 TEXTEQU <__imp_shell32_ordinal510>
extern __imp_shell32_ordinal511:PANYARGS
shell32_ordinal511 TEXTEQU <__imp_shell32_ordinal511>
extern __imp_shell32_ordinal512:PANYARGS
shell32_ordinal512 TEXTEQU <__imp_shell32_ordinal512>
extern __imp_shell32_ordinal513:PANYARGS
shell32_ordinal513 TEXTEQU <__imp_shell32_ordinal513>
extern __imp_shell32_ordinal514:PANYARGS
shell32_ordinal514 TEXTEQU <__imp_shell32_ordinal514>
extern __imp_shell32_ordinal515:PANYARGS
shell32_ordinal515 TEXTEQU <__imp_shell32_ordinal515>
extern __imp_shell32_ordinal516:PANYARGS
shell32_ordinal516 TEXTEQU <__imp_shell32_ordinal516>
extern __imp_shell32_ordinal517:PANYARGS
shell32_ordinal517 TEXTEQU <__imp_shell32_ordinal517>
extern __imp_shell32_ordinal518:PANYARGS
shell32_ordinal518 TEXTEQU <__imp_shell32_ordinal518>
extern __imp_shell32_ordinal519:PANYARGS
shell32_ordinal519 TEXTEQU <__imp_shell32_ordinal519>
extern __imp_SHAllocShared:PANYARGS
SHAllocShared TEXTEQU <__imp_SHAllocShared>
extern __imp_SHLockShared:PANYARGS
SHLockShared TEXTEQU <__imp_SHLockShared>
extern __imp_SHUnlockShared:PANYARGS
SHUnlockShared TEXTEQU <__imp_SHUnlockShared>
extern __imp_SHFreeShared:PANYARGS
SHFreeShared TEXTEQU <__imp_SHFreeShared>
extern __imp_RealDriveType:PANYARGS
RealDriveType TEXTEQU <__imp_RealDriveType>
extern __imp_shell32_ordinal525:PANYARGS
shell32_ordinal525 TEXTEQU <__imp_shell32_ordinal525>
extern __imp_SHFlushSFCache:PANYARGS
SHFlushSFCache TEXTEQU <__imp_SHFlushSFCache>
extern __imp_shell32_ordinal527:PANYARGS
shell32_ordinal527 TEXTEQU <__imp_shell32_ordinal527>
extern __imp_shell32_ordinal528:PANYARGS
shell32_ordinal528 TEXTEQU <__imp_shell32_ordinal528>
extern __imp_shell32_ordinal529:PANYARGS
shell32_ordinal529 TEXTEQU <__imp_shell32_ordinal529>
extern __imp_shell32_ordinal530:PANYARGS
shell32_ordinal530 TEXTEQU <__imp_shell32_ordinal530>
extern __imp_shell32_ordinal531:PANYARGS
shell32_ordinal531 TEXTEQU <__imp_shell32_ordinal531>
extern __imp_shell32_ordinal532:PANYARGS
shell32_ordinal532 TEXTEQU <__imp_shell32_ordinal532>
extern __imp_shell32_ordinal533:PANYARGS
shell32_ordinal533 TEXTEQU <__imp_shell32_ordinal533>
extern __imp_shell32_ordinal534:PANYARGS
shell32_ordinal534 TEXTEQU <__imp_shell32_ordinal534>
extern __imp_shell32_ordinal535:PANYARGS
shell32_ordinal535 TEXTEQU <__imp_shell32_ordinal535>
extern __imp_shell32_ordinal536:PANYARGS
shell32_ordinal536 TEXTEQU <__imp_shell32_ordinal536>
extern __imp_shell32_ordinal537:PANYARGS
shell32_ordinal537 TEXTEQU <__imp_shell32_ordinal537>
extern __imp_shell32_ordinal538:PANYARGS
shell32_ordinal538 TEXTEQU <__imp_shell32_ordinal538>
extern __imp_shell32_ordinal539:PANYARGS
shell32_ordinal539 TEXTEQU <__imp_shell32_ordinal539>
extern __imp_shell32_ordinal540:PANYARGS
shell32_ordinal540 TEXTEQU <__imp_shell32_ordinal540>
extern __imp_shell32_ordinal541:PANYARGS
shell32_ordinal541 TEXTEQU <__imp_shell32_ordinal541>
extern __imp_shell32_ordinal542:PANYARGS
shell32_ordinal542 TEXTEQU <__imp_shell32_ordinal542>
extern __imp_shell32_ordinal543:PANYARGS
shell32_ordinal543 TEXTEQU <__imp_shell32_ordinal543>
extern __imp_shell32_ordinal544:PANYARGS
shell32_ordinal544 TEXTEQU <__imp_shell32_ordinal544>
extern __imp_shell32_ordinal545:PANYARGS
shell32_ordinal545 TEXTEQU <__imp_shell32_ordinal545>
extern __imp_shell32_ordinal546:PANYARGS
shell32_ordinal546 TEXTEQU <__imp_shell32_ordinal546>
extern __imp_shell32_ordinal547:PANYARGS
shell32_ordinal547 TEXTEQU <__imp_shell32_ordinal547>
extern __imp_shell32_ordinal548:PANYARGS
shell32_ordinal548 TEXTEQU <__imp_shell32_ordinal548>
extern __imp_shell32_ordinal549:PANYARGS
shell32_ordinal549 TEXTEQU <__imp_shell32_ordinal549>
extern __imp_shell32_ordinal550:PANYARGS
shell32_ordinal550 TEXTEQU <__imp_shell32_ordinal550>
extern __imp_shell32_ordinal551:PANYARGS
shell32_ordinal551 TEXTEQU <__imp_shell32_ordinal551>
extern __imp_shell32_ordinal552:PANYARGS
shell32_ordinal552 TEXTEQU <__imp_shell32_ordinal552>
extern __imp_shell32_ordinal553:PANYARGS
shell32_ordinal553 TEXTEQU <__imp_shell32_ordinal553>
extern __imp_shell32_ordinal554:PANYARGS
shell32_ordinal554 TEXTEQU <__imp_shell32_ordinal554>
extern __imp_shell32_ordinal555:PANYARGS
shell32_ordinal555 TEXTEQU <__imp_shell32_ordinal555>
extern __imp_shell32_ordinal556:PANYARGS
shell32_ordinal556 TEXTEQU <__imp_shell32_ordinal556>
extern __imp_shell32_ordinal557:PANYARGS
shell32_ordinal557 TEXTEQU <__imp_shell32_ordinal557>
extern __imp_shell32_ordinal558:PANYARGS
shell32_ordinal558 TEXTEQU <__imp_shell32_ordinal558>
extern __imp_shell32_ordinal559:PANYARGS
shell32_ordinal559 TEXTEQU <__imp_shell32_ordinal559>
extern __imp_shell32_ordinal560:PANYARGS
shell32_ordinal560 TEXTEQU <__imp_shell32_ordinal560>
extern __imp_shell32_ordinal561:PANYARGS
shell32_ordinal561 TEXTEQU <__imp_shell32_ordinal561>
extern __imp_shell32_ordinal562:PANYARGS
shell32_ordinal562 TEXTEQU <__imp_shell32_ordinal562>
extern __imp_shell32_ordinal563:PANYARGS
shell32_ordinal563 TEXTEQU <__imp_shell32_ordinal563>
extern __imp_shell32_ordinal564:PANYARGS
shell32_ordinal564 TEXTEQU <__imp_shell32_ordinal564>
extern __imp_shell32_ordinal565:PANYARGS
shell32_ordinal565 TEXTEQU <__imp_shell32_ordinal565>
extern __imp_shell32_ordinal566:PANYARGS
shell32_ordinal566 TEXTEQU <__imp_shell32_ordinal566>
extern __imp_shell32_ordinal567:PANYARGS
shell32_ordinal567 TEXTEQU <__imp_shell32_ordinal567>
extern __imp_shell32_ordinal568:PANYARGS
shell32_ordinal568 TEXTEQU <__imp_shell32_ordinal568>
extern __imp_shell32_ordinal569:PANYARGS
shell32_ordinal569 TEXTEQU <__imp_shell32_ordinal569>
extern __imp_shell32_ordinal570:PANYARGS
shell32_ordinal570 TEXTEQU <__imp_shell32_ordinal570>
extern __imp_shell32_ordinal571:PANYARGS
shell32_ordinal571 TEXTEQU <__imp_shell32_ordinal571>
extern __imp_shell32_ordinal572:PANYARGS
shell32_ordinal572 TEXTEQU <__imp_shell32_ordinal572>
extern __imp_shell32_ordinal573:PANYARGS
shell32_ordinal573 TEXTEQU <__imp_shell32_ordinal573>
extern __imp_shell32_ordinal574:PANYARGS
shell32_ordinal574 TEXTEQU <__imp_shell32_ordinal574>
extern __imp_shell32_ordinal575:PANYARGS
shell32_ordinal575 TEXTEQU <__imp_shell32_ordinal575>
extern __imp_shell32_ordinal576:PANYARGS
shell32_ordinal576 TEXTEQU <__imp_shell32_ordinal576>
extern __imp_shell32_ordinal577:PANYARGS
shell32_ordinal577 TEXTEQU <__imp_shell32_ordinal577>
extern __imp_shell32_ordinal578:PANYARGS
shell32_ordinal578 TEXTEQU <__imp_shell32_ordinal578>
extern __imp_shell32_ordinal579:PANYARGS
shell32_ordinal579 TEXTEQU <__imp_shell32_ordinal579>
extern __imp_shell32_ordinal580:PANYARGS
shell32_ordinal580 TEXTEQU <__imp_shell32_ordinal580>
extern __imp_shell32_ordinal581:PANYARGS
shell32_ordinal581 TEXTEQU <__imp_shell32_ordinal581>
extern __imp_shell32_ordinal582:PANYARGS
shell32_ordinal582 TEXTEQU <__imp_shell32_ordinal582>
extern __imp_shell32_ordinal583:PANYARGS
shell32_ordinal583 TEXTEQU <__imp_shell32_ordinal583>
extern __imp_shell32_ordinal584:PANYARGS
shell32_ordinal584 TEXTEQU <__imp_shell32_ordinal584>
extern __imp_shell32_ordinal585:PANYARGS
shell32_ordinal585 TEXTEQU <__imp_shell32_ordinal585>
extern __imp_shell32_ordinal586:PANYARGS
shell32_ordinal586 TEXTEQU <__imp_shell32_ordinal586>
extern __imp_shell32_ordinal587:PANYARGS
shell32_ordinal587 TEXTEQU <__imp_shell32_ordinal587>
extern __imp_shell32_ordinal588:PANYARGS
shell32_ordinal588 TEXTEQU <__imp_shell32_ordinal588>
extern __imp_shell32_ordinal589:PANYARGS
shell32_ordinal589 TEXTEQU <__imp_shell32_ordinal589>
extern __imp_shell32_ordinal590:PANYARGS
shell32_ordinal590 TEXTEQU <__imp_shell32_ordinal590>
extern __imp_shell32_ordinal591:PANYARGS
shell32_ordinal591 TEXTEQU <__imp_shell32_ordinal591>
extern __imp_shell32_ordinal592:PANYARGS
shell32_ordinal592 TEXTEQU <__imp_shell32_ordinal592>
extern __imp_shell32_ordinal593:PANYARGS
shell32_ordinal593 TEXTEQU <__imp_shell32_ordinal593>
extern __imp_shell32_ordinal594:PANYARGS
shell32_ordinal594 TEXTEQU <__imp_shell32_ordinal594>
extern __imp_shell32_ordinal595:PANYARGS
shell32_ordinal595 TEXTEQU <__imp_shell32_ordinal595>
extern __imp_shell32_ordinal596:PANYARGS
shell32_ordinal596 TEXTEQU <__imp_shell32_ordinal596>
extern __imp_shell32_ordinal597:PANYARGS
shell32_ordinal597 TEXTEQU <__imp_shell32_ordinal597>
extern __imp_shell32_ordinal598:PANYARGS
shell32_ordinal598 TEXTEQU <__imp_shell32_ordinal598>
extern __imp_shell32_ordinal599:PANYARGS
shell32_ordinal599 TEXTEQU <__imp_shell32_ordinal599>
extern __imp_shell32_ordinal600:PANYARGS
shell32_ordinal600 TEXTEQU <__imp_shell32_ordinal600>
extern __imp_shell32_ordinal601:PANYARGS
shell32_ordinal601 TEXTEQU <__imp_shell32_ordinal601>
extern __imp_shell32_ordinal602:PANYARGS
shell32_ordinal602 TEXTEQU <__imp_shell32_ordinal602>
extern __imp_shell32_ordinal603:PANYARGS
shell32_ordinal603 TEXTEQU <__imp_shell32_ordinal603>
extern __imp_shell32_ordinal604:PANYARGS
shell32_ordinal604 TEXTEQU <__imp_shell32_ordinal604>
extern __imp_shell32_ordinal605:PANYARGS
shell32_ordinal605 TEXTEQU <__imp_shell32_ordinal605>
extern __imp_shell32_ordinal606:PANYARGS
shell32_ordinal606 TEXTEQU <__imp_shell32_ordinal606>
extern __imp_shell32_ordinal607:PANYARGS
shell32_ordinal607 TEXTEQU <__imp_shell32_ordinal607>
extern __imp_shell32_ordinal608:PANYARGS
shell32_ordinal608 TEXTEQU <__imp_shell32_ordinal608>
extern __imp_shell32_ordinal609:PANYARGS
shell32_ordinal609 TEXTEQU <__imp_shell32_ordinal609>
extern __imp_shell32_ordinal610:PANYARGS
shell32_ordinal610 TEXTEQU <__imp_shell32_ordinal610>
extern __imp_shell32_ordinal611:PANYARGS
shell32_ordinal611 TEXTEQU <__imp_shell32_ordinal611>
extern __imp_shell32_ordinal612:PANYARGS
shell32_ordinal612 TEXTEQU <__imp_shell32_ordinal612>
extern __imp_shell32_ordinal613:PANYARGS
shell32_ordinal613 TEXTEQU <__imp_shell32_ordinal613>
extern __imp_shell32_ordinal614:PANYARGS
shell32_ordinal614 TEXTEQU <__imp_shell32_ordinal614>
extern __imp_shell32_ordinal615:PANYARGS
shell32_ordinal615 TEXTEQU <__imp_shell32_ordinal615>
extern __imp_shell32_ordinal616:PANYARGS
shell32_ordinal616 TEXTEQU <__imp_shell32_ordinal616>
extern __imp_shell32_ordinal617:PANYARGS
shell32_ordinal617 TEXTEQU <__imp_shell32_ordinal617>
extern __imp_shell32_ordinal618:PANYARGS
shell32_ordinal618 TEXTEQU <__imp_shell32_ordinal618>
extern __imp_shell32_ordinal619:PANYARGS
shell32_ordinal619 TEXTEQU <__imp_shell32_ordinal619>
extern __imp_shell32_ordinal620:PANYARGS
shell32_ordinal620 TEXTEQU <__imp_shell32_ordinal620>
extern __imp_shell32_ordinal621:PANYARGS
shell32_ordinal621 TEXTEQU <__imp_shell32_ordinal621>
extern __imp_shell32_ordinal622:PANYARGS
shell32_ordinal622 TEXTEQU <__imp_shell32_ordinal622>
extern __imp_shell32_ordinal623:PANYARGS
shell32_ordinal623 TEXTEQU <__imp_shell32_ordinal623>
extern __imp_shell32_ordinal624:PANYARGS
shell32_ordinal624 TEXTEQU <__imp_shell32_ordinal624>
extern __imp_shell32_ordinal625:PANYARGS
shell32_ordinal625 TEXTEQU <__imp_shell32_ordinal625>
extern __imp_shell32_ordinal626:PANYARGS
shell32_ordinal626 TEXTEQU <__imp_shell32_ordinal626>
extern __imp_shell32_ordinal627:PANYARGS
shell32_ordinal627 TEXTEQU <__imp_shell32_ordinal627>
extern __imp_shell32_ordinal628:PANYARGS
shell32_ordinal628 TEXTEQU <__imp_shell32_ordinal628>
extern __imp_shell32_ordinal629:PANYARGS
shell32_ordinal629 TEXTEQU <__imp_shell32_ordinal629>
extern __imp_shell32_ordinal630:PANYARGS
shell32_ordinal630 TEXTEQU <__imp_shell32_ordinal630>
extern __imp_shell32_ordinal631:PANYARGS
shell32_ordinal631 TEXTEQU <__imp_shell32_ordinal631>
extern __imp_shell32_ordinal632:PANYARGS
shell32_ordinal632 TEXTEQU <__imp_shell32_ordinal632>
extern __imp_shell32_ordinal633:PANYARGS
shell32_ordinal633 TEXTEQU <__imp_shell32_ordinal633>
extern __imp_shell32_ordinal634:PANYARGS
shell32_ordinal634 TEXTEQU <__imp_shell32_ordinal634>
extern __imp_shell32_ordinal635:PANYARGS
shell32_ordinal635 TEXTEQU <__imp_shell32_ordinal635>
extern __imp_shell32_ordinal636:PANYARGS
shell32_ordinal636 TEXTEQU <__imp_shell32_ordinal636>
extern __imp_shell32_ordinal637:PANYARGS
shell32_ordinal637 TEXTEQU <__imp_shell32_ordinal637>
extern __imp_shell32_ordinal638:PANYARGS
shell32_ordinal638 TEXTEQU <__imp_shell32_ordinal638>
extern __imp_shell32_ordinal639:PANYARGS
shell32_ordinal639 TEXTEQU <__imp_shell32_ordinal639>
extern __imp_shell32_ordinal640:PANYARGS
shell32_ordinal640 TEXTEQU <__imp_shell32_ordinal640>
extern __imp_shell32_ordinal641:PANYARGS
shell32_ordinal641 TEXTEQU <__imp_shell32_ordinal641>
extern __imp_shell32_ordinal642:PANYARGS
shell32_ordinal642 TEXTEQU <__imp_shell32_ordinal642>
extern __imp_shell32_ordinal643:PANYARGS
shell32_ordinal643 TEXTEQU <__imp_shell32_ordinal643>
extern __imp_SHChangeNotification_Lock:PANYARGS
SHChangeNotification_Lock TEXTEQU <__imp_SHChangeNotification_Lock>
extern __imp_SHChangeNotification_Unlock:PANYARGS
SHChangeNotification_Unlock TEXTEQU <__imp_SHChangeNotification_Unlock>
extern __imp_shell32_ordinal646:PANYARGS
shell32_ordinal646 TEXTEQU <__imp_shell32_ordinal646>
extern __imp_shell32_ordinal647:PANYARGS
shell32_ordinal647 TEXTEQU <__imp_shell32_ordinal647>
extern __imp_shell32_ordinal648:PANYARGS
shell32_ordinal648 TEXTEQU <__imp_shell32_ordinal648>
extern __imp_shell32_ordinal649:PANYARGS
shell32_ordinal649 TEXTEQU <__imp_shell32_ordinal649>
extern __imp_shell32_ordinal650:PANYARGS
shell32_ordinal650 TEXTEQU <__imp_shell32_ordinal650>
extern __imp_shell32_ordinal651:PANYARGS
shell32_ordinal651 TEXTEQU <__imp_shell32_ordinal651>
extern __imp_WriteCabinetState:PANYARGS
WriteCabinetState TEXTEQU <__imp_WriteCabinetState>
extern __imp_PathProcessCommand:PANYARGS
PathProcessCommand TEXTEQU <__imp_PathProcessCommand>
extern __imp_ReadCabinetState:PANYARGS
ReadCabinetState TEXTEQU <__imp_ReadCabinetState>
extern __imp_shell32_ordinal655:PANYARGS
shell32_ordinal655 TEXTEQU <__imp_shell32_ordinal655>
extern __imp_shell32_ordinal656:PANYARGS
shell32_ordinal656 TEXTEQU <__imp_shell32_ordinal656>
extern __imp_shell32_ordinal657:PANYARGS
shell32_ordinal657 TEXTEQU <__imp_shell32_ordinal657>
extern __imp_shell32_ordinal658:PANYARGS
shell32_ordinal658 TEXTEQU <__imp_shell32_ordinal658>
extern __imp_shell32_ordinal659:PANYARGS
shell32_ordinal659 TEXTEQU <__imp_shell32_ordinal659>
extern __imp_shell32_ordinal660:PANYARGS
shell32_ordinal660 TEXTEQU <__imp_shell32_ordinal660>
extern __imp_shell32_ordinal661:PANYARGS
shell32_ordinal661 TEXTEQU <__imp_shell32_ordinal661>
extern __imp_shell32_ordinal662:PANYARGS
shell32_ordinal662 TEXTEQU <__imp_shell32_ordinal662>
extern __imp_shell32_ordinal663:PANYARGS
shell32_ordinal663 TEXTEQU <__imp_shell32_ordinal663>
extern __imp_shell32_ordinal664:PANYARGS
shell32_ordinal664 TEXTEQU <__imp_shell32_ordinal664>
extern __imp_shell32_ordinal665:PANYARGS
shell32_ordinal665 TEXTEQU <__imp_shell32_ordinal665>
extern __imp_shell32_ordinal666:PANYARGS
shell32_ordinal666 TEXTEQU <__imp_shell32_ordinal666>
extern __imp_shell32_ordinal667:PANYARGS
shell32_ordinal667 TEXTEQU <__imp_shell32_ordinal667>
extern __imp_shell32_ordinal668:PANYARGS
shell32_ordinal668 TEXTEQU <__imp_shell32_ordinal668>
extern __imp_shell32_ordinal669:PANYARGS
shell32_ordinal669 TEXTEQU <__imp_shell32_ordinal669>
extern __imp_shell32_ordinal670:PANYARGS
shell32_ordinal670 TEXTEQU <__imp_shell32_ordinal670>
extern __imp_shell32_ordinal671:PANYARGS
shell32_ordinal671 TEXTEQU <__imp_shell32_ordinal671>
extern __imp_shell32_ordinal672:PANYARGS
shell32_ordinal672 TEXTEQU <__imp_shell32_ordinal672>
extern __imp_shell32_ordinal673:PANYARGS
shell32_ordinal673 TEXTEQU <__imp_shell32_ordinal673>
extern __imp_shell32_ordinal674:PANYARGS
shell32_ordinal674 TEXTEQU <__imp_shell32_ordinal674>
extern __imp_shell32_ordinal675:PANYARGS
shell32_ordinal675 TEXTEQU <__imp_shell32_ordinal675>
extern __imp_shell32_ordinal676:PANYARGS
shell32_ordinal676 TEXTEQU <__imp_shell32_ordinal676>
extern __imp_shell32_ordinal677:PANYARGS
shell32_ordinal677 TEXTEQU <__imp_shell32_ordinal677>
extern __imp_shell32_ordinal678:PANYARGS
shell32_ordinal678 TEXTEQU <__imp_shell32_ordinal678>
extern __imp_shell32_ordinal679:PANYARGS
shell32_ordinal679 TEXTEQU <__imp_shell32_ordinal679>
extern __imp_IsUserAnAdmin:PANYARGS
IsUserAnAdmin TEXTEQU <__imp_IsUserAnAdmin>
extern __imp_shell32_ordinal681:PANYARGS
shell32_ordinal681 TEXTEQU <__imp_shell32_ordinal681>
extern __imp_shell32_ordinal682:PANYARGS
shell32_ordinal682 TEXTEQU <__imp_shell32_ordinal682>
extern __imp_shell32_ordinal683:PANYARGS
shell32_ordinal683 TEXTEQU <__imp_shell32_ordinal683>
extern __imp_shell32_ordinal684:PANYARGS
shell32_ordinal684 TEXTEQU <__imp_shell32_ordinal684>
extern __imp_SHPropStgCreate:PANYARGS
SHPropStgCreate TEXTEQU <__imp_SHPropStgCreate>
extern __imp_shell32_ordinal686:PANYARGS
shell32_ordinal686 TEXTEQU <__imp_shell32_ordinal686>
extern __imp_shell32_ordinal687:PANYARGS
shell32_ordinal687 TEXTEQU <__imp_shell32_ordinal687>
extern __imp_SHPropStgReadMultiple:PANYARGS
SHPropStgReadMultiple TEXTEQU <__imp_SHPropStgReadMultiple>
extern __imp_SHPropStgWriteMultiple:PANYARGS
SHPropStgWriteMultiple TEXTEQU <__imp_SHPropStgWriteMultiple>
extern __imp_shell32_ordinal690:PANYARGS
shell32_ordinal690 TEXTEQU <__imp_shell32_ordinal690>
extern __imp_shell32_ordinal691:PANYARGS
shell32_ordinal691 TEXTEQU <__imp_shell32_ordinal691>
extern __imp_shell32_ordinal692:PANYARGS
shell32_ordinal692 TEXTEQU <__imp_shell32_ordinal692>
extern __imp_shell32_ordinal693:PANYARGS
shell32_ordinal693 TEXTEQU <__imp_shell32_ordinal693>
extern __imp_shell32_ordinal694:PANYARGS
shell32_ordinal694 TEXTEQU <__imp_shell32_ordinal694>
extern __imp_shell32_ordinal695:PANYARGS
shell32_ordinal695 TEXTEQU <__imp_shell32_ordinal695>
extern __imp_shell32_ordinal696:PANYARGS
shell32_ordinal696 TEXTEQU <__imp_shell32_ordinal696>
extern __imp_shell32_ordinal697:PANYARGS
shell32_ordinal697 TEXTEQU <__imp_shell32_ordinal697>
extern __imp_shell32_ordinal698:PANYARGS
shell32_ordinal698 TEXTEQU <__imp_shell32_ordinal698>
extern __imp_shell32_ordinal699:PANYARGS
shell32_ordinal699 TEXTEQU <__imp_shell32_ordinal699>
extern __imp_CDefFolderMenu_Create:PANYARGS
CDefFolderMenu_Create TEXTEQU <__imp_CDefFolderMenu_Create>
extern __imp_CDefFolderMenu_Create2:PANYARGS
CDefFolderMenu_Create2 TEXTEQU <__imp_CDefFolderMenu_Create2>
extern __imp_shell32_ordinal702:PANYARGS
shell32_ordinal702 TEXTEQU <__imp_shell32_ordinal702>
extern __imp_shell32_ordinal703:PANYARGS
shell32_ordinal703 TEXTEQU <__imp_shell32_ordinal703>
extern __imp_shell32_ordinal704:PANYARGS
shell32_ordinal704 TEXTEQU <__imp_shell32_ordinal704>
extern __imp_shell32_ordinal705:PANYARGS
shell32_ordinal705 TEXTEQU <__imp_shell32_ordinal705>
extern __imp_shell32_ordinal706:PANYARGS
shell32_ordinal706 TEXTEQU <__imp_shell32_ordinal706>
extern __imp_shell32_ordinal707:PANYARGS
shell32_ordinal707 TEXTEQU <__imp_shell32_ordinal707>
extern __imp_shell32_ordinal708:PANYARGS
shell32_ordinal708 TEXTEQU <__imp_shell32_ordinal708>
extern __imp_SHGetSetFolderCustomSettingsW:PANYARGS
SHGetSetFolderCustomSettingsW TEXTEQU <__imp_SHGetSetFolderCustomSettingsW>
extern __imp_shell32_ordinal710:PANYARGS
shell32_ordinal710 TEXTEQU <__imp_shell32_ordinal710>
extern __imp_shell32_ordinal711:PANYARGS
shell32_ordinal711 TEXTEQU <__imp_shell32_ordinal711>
extern __imp_shell32_ordinal712:PANYARGS
shell32_ordinal712 TEXTEQU <__imp_shell32_ordinal712>
extern __imp_shell32_ordinal713:PANYARGS
shell32_ordinal713 TEXTEQU <__imp_shell32_ordinal713>
extern __imp_shell32_ordinal714:PANYARGS
shell32_ordinal714 TEXTEQU <__imp_shell32_ordinal714>
extern __imp_shell32_ordinal715:PANYARGS
shell32_ordinal715 TEXTEQU <__imp_shell32_ordinal715>
extern __imp_SHMultiFileProperties:PANYARGS
SHMultiFileProperties TEXTEQU <__imp_SHMultiFileProperties>
extern __imp_shell32_ordinal717:PANYARGS
shell32_ordinal717 TEXTEQU <__imp_shell32_ordinal717>
extern __imp_shell32_ordinal718:PANYARGS
shell32_ordinal718 TEXTEQU <__imp_shell32_ordinal718>
extern __imp_shell32_ordinal719:PANYARGS
shell32_ordinal719 TEXTEQU <__imp_shell32_ordinal719>
extern __imp_shell32_ordinal720:PANYARGS
shell32_ordinal720 TEXTEQU <__imp_shell32_ordinal720>
extern __imp_shell32_ordinal721:PANYARGS
shell32_ordinal721 TEXTEQU <__imp_shell32_ordinal721>
extern __imp_shell32_ordinal722:PANYARGS
shell32_ordinal722 TEXTEQU <__imp_shell32_ordinal722>
extern __imp_shell32_ordinal723:PANYARGS
shell32_ordinal723 TEXTEQU <__imp_shell32_ordinal723>
extern __imp_shell32_ordinal724:PANYARGS
shell32_ordinal724 TEXTEQU <__imp_shell32_ordinal724>
extern __imp_shell32_ordinal725:PANYARGS
shell32_ordinal725 TEXTEQU <__imp_shell32_ordinal725>
extern __imp_shell32_ordinal726:PANYARGS
shell32_ordinal726 TEXTEQU <__imp_shell32_ordinal726>
extern __imp_SHGetImageList:PANYARGS
SHGetImageList TEXTEQU <__imp_SHGetImageList>
extern __imp_shell32_ordinal728:PANYARGS
shell32_ordinal728 TEXTEQU <__imp_shell32_ordinal728>
extern __imp_shell32_ordinal729:PANYARGS
shell32_ordinal729 TEXTEQU <__imp_shell32_ordinal729>
extern __imp_RestartDialogEx:PANYARGS
RestartDialogEx TEXTEQU <__imp_RestartDialogEx>
extern __imp_shell32_ordinal731:PANYARGS
shell32_ordinal731 TEXTEQU <__imp_shell32_ordinal731>
extern __imp_shell32_ordinal732:PANYARGS
shell32_ordinal732 TEXTEQU <__imp_shell32_ordinal732>
extern __imp_shell32_ordinal733:PANYARGS
shell32_ordinal733 TEXTEQU <__imp_shell32_ordinal733>
extern __imp_shell32_ordinal734:PANYARGS
shell32_ordinal734 TEXTEQU <__imp_shell32_ordinal734>
extern __imp_shell32_ordinal735:PANYARGS
shell32_ordinal735 TEXTEQU <__imp_shell32_ordinal735>
extern __imp_shell32_ordinal736:PANYARGS
shell32_ordinal736 TEXTEQU <__imp_shell32_ordinal736>
extern __imp_shell32_ordinal737:PANYARGS
shell32_ordinal737 TEXTEQU <__imp_shell32_ordinal737>
extern __imp_shell32_ordinal738:PANYARGS
shell32_ordinal738 TEXTEQU <__imp_shell32_ordinal738>
extern __imp_shell32_ordinal739:PANYARGS
shell32_ordinal739 TEXTEQU <__imp_shell32_ordinal739>
extern __imp_shell32_ordinal740:PANYARGS
shell32_ordinal740 TEXTEQU <__imp_shell32_ordinal740>
extern __imp_shell32_ordinal741:PANYARGS
shell32_ordinal741 TEXTEQU <__imp_shell32_ordinal741>
extern __imp_shell32_ordinal742:PANYARGS
shell32_ordinal742 TEXTEQU <__imp_shell32_ordinal742>
extern __imp_SHCreateFileExtractIconW:PANYARGS
SHCreateFileExtractIconW TEXTEQU <__imp_SHCreateFileExtractIconW>
extern __imp_shell32_ordinal744:PANYARGS
shell32_ordinal744 TEXTEQU <__imp_shell32_ordinal744>
extern __imp_shell32_ordinal745:PANYARGS
shell32_ordinal745 TEXTEQU <__imp_shell32_ordinal745>
extern __imp_shell32_ordinal746:PANYARGS
shell32_ordinal746 TEXTEQU <__imp_shell32_ordinal746>
extern __imp_SHLimitInputEdit:PANYARGS
SHLimitInputEdit TEXTEQU <__imp_SHLimitInputEdit>
extern __imp_shell32_ordinal748:PANYARGS
shell32_ordinal748 TEXTEQU <__imp_shell32_ordinal748>
extern __imp_SHGetShellStyleHInstance:PANYARGS
SHGetShellStyleHInstance TEXTEQU <__imp_SHGetShellStyleHInstance>
extern __imp_SHGetAttributesFromDataObject:PANYARGS
SHGetAttributesFromDataObject TEXTEQU <__imp_SHGetAttributesFromDataObject>
extern __imp_shell32_ordinal751:PANYARGS
shell32_ordinal751 TEXTEQU <__imp_shell32_ordinal751>
extern __imp_shell32_ordinal752:PANYARGS
shell32_ordinal752 TEXTEQU <__imp_shell32_ordinal752>
extern __imp_shell32_ordinal753:PANYARGS
shell32_ordinal753 TEXTEQU <__imp_shell32_ordinal753>
extern __imp_shell32_ordinal754:PANYARGS
shell32_ordinal754 TEXTEQU <__imp_shell32_ordinal754>
extern __imp_shell32_ordinal755:PANYARGS
shell32_ordinal755 TEXTEQU <__imp_shell32_ordinal755>
extern __imp_shell32_ordinal756:PANYARGS
shell32_ordinal756 TEXTEQU <__imp_shell32_ordinal756>
