extern __imp_ImageView_COMServer:PANYARGS
ImageView_COMServer TEXTEQU <__imp_ImageView_COMServer>
extern __imp_ImageView_Fullscreen:PANYARGS
ImageView_Fullscreen TEXTEQU <__imp_ImageView_Fullscreen>
extern __imp_ImageView_FullscreenA:PANYARGS
ImageView_Fullscreen  TEXTEQU <__imp_ImageView_FullscreenA>
extern __imp_ImageView_FullscreenW:PANYARGS
ImageView_FullscreenW TEXTEQU <__imp_ImageView_FullscreenW>
extern __imp_ImageView_PrintTo:PANYARGS
ImageView_PrintTo TEXTEQU <__imp_ImageView_PrintTo>
extern __imp_ImageView_PrintToA:PANYARGS
ImageView_PrintTo  TEXTEQU <__imp_ImageView_PrintToA>
extern __imp_ImageView_PrintToW:PANYARGS
ImageView_PrintToW TEXTEQU <__imp_ImageView_PrintToW>
extern __imp_imageview_fullscreenW:PANYARGS
imageview_fullscreenW TEXTEQU <__imp_imageview_fullscreenW>
extern __imp_ConvertDIBSECTIONToThumbnail:PANYARGS
ConvertDIBSECTIONToThumbnail TEXTEQU <__imp_ConvertDIBSECTIONToThumbnail>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
