extern __imp_SE_DllLoaded:PANYARGS
SE_DllLoaded TEXTEQU <__imp_SE_DllLoaded>
extern __imp_SE_DllUnloaded:PANYARGS
SE_DllUnloaded TEXTEQU <__imp_SE_DllUnloaded>
extern __imp_SE_DynamicShim:PANYARGS
SE_DynamicShim TEXTEQU <__imp_SE_DynamicShim>
extern __imp_SE_DynamicUnshim:PANYARGS
SE_DynamicUnshim TEXTEQU <__imp_SE_DynamicUnshim>
extern __imp_SE_InstallAfterInit:PANYARGS
SE_InstallAfterInit TEXTEQU <__imp_SE_InstallAfterInit>
extern __imp_SE_InstallBeforeInit:PANYARGS
SE_InstallBeforeInit TEXTEQU <__imp_SE_InstallBeforeInit>
extern __imp_SE_IsShimDll:PANYARGS
SE_IsShimDll TEXTEQU <__imp_SE_IsShimDll>
extern __imp_SE_ProcessDying:PANYARGS
SE_ProcessDying TEXTEQU <__imp_SE_ProcessDying>
extern __imp_SE_RemoveNTVDMTask:PANYARGS
SE_RemoveNTVDMTask TEXTEQU <__imp_SE_RemoveNTVDMTask>
extern __imp_SE_ShimNTVDM:PANYARGS
SE_ShimNTVDM TEXTEQU <__imp_SE_ShimNTVDM>
