extern __imp_shlwapi_ordinal1:PANYARGS
shlwapi_ordinal1 TEXTEQU <__imp_shlwapi_ordinal1>
extern __imp_shlwapi_ordinal2:PANYARGS
shlwapi_ordinal2 TEXTEQU <__imp_shlwapi_ordinal2>
extern __imp_shlwapi_ordinal3:PANYARGS
shlwapi_ordinal3 TEXTEQU <__imp_shlwapi_ordinal3>
extern __imp_shlwapi_ordinal4:PANYARGS
shlwapi_ordinal4 TEXTEQU <__imp_shlwapi_ordinal4>
extern __imp_shlwapi_ordinal5:PANYARGS
shlwapi_ordinal5 TEXTEQU <__imp_shlwapi_ordinal5>
extern __imp_shlwapi_ordinal6:PANYARGS
shlwapi_ordinal6 TEXTEQU <__imp_shlwapi_ordinal6>
extern __imp_SHAllocShared:PANYARGS
SHAllocShared TEXTEQU <__imp_SHAllocShared>
extern __imp_SHLockShared:PANYARGS
SHLockShared TEXTEQU <__imp_SHLockShared>
extern __imp_SHUnlockShared:PANYARGS
SHUnlockShared TEXTEQU <__imp_SHUnlockShared>
extern __imp_SHFreeShared:PANYARGS
SHFreeShared TEXTEQU <__imp_SHFreeShared>
extern __imp_shlwapi_ordinal11:PANYARGS
shlwapi_ordinal11 TEXTEQU <__imp_shlwapi_ordinal11>
extern __imp_shlwapi_ordinal12:PANYARGS
shlwapi_ordinal12 TEXTEQU <__imp_shlwapi_ordinal12>
extern __imp_shlwapi_ordinal13:PANYARGS
shlwapi_ordinal13 TEXTEQU <__imp_shlwapi_ordinal13>
extern __imp_GetAcceptLanguagesA:PANYARGS
GetAcceptLanguages  TEXTEQU <__imp_GetAcceptLanguagesA>
extern __imp_GetAcceptLanguagesW:PANYARGS
GetAcceptLanguagesW TEXTEQU <__imp_GetAcceptLanguagesW>
extern __imp_SHCreateThread:PANYARGS
SHCreateThread TEXTEQU <__imp_SHCreateThread>
extern __imp_shlwapi_ordinal17:PANYARGS
shlwapi_ordinal17 TEXTEQU <__imp_shlwapi_ordinal17>
extern __imp_shlwapi_ordinal18:PANYARGS
shlwapi_ordinal18 TEXTEQU <__imp_shlwapi_ordinal18>
extern __imp_shlwapi_ordinal19:PANYARGS
shlwapi_ordinal19 TEXTEQU <__imp_shlwapi_ordinal19>
extern __imp_shlwapi_ordinal20:PANYARGS
shlwapi_ordinal20 TEXTEQU <__imp_shlwapi_ordinal20>
extern __imp_shlwapi_ordinal21:PANYARGS
shlwapi_ordinal21 TEXTEQU <__imp_shlwapi_ordinal21>
extern __imp_shlwapi_ordinal22:PANYARGS
shlwapi_ordinal22 TEXTEQU <__imp_shlwapi_ordinal22>
extern __imp_shlwapi_ordinal23:PANYARGS
shlwapi_ordinal23 TEXTEQU <__imp_shlwapi_ordinal23>
extern __imp_shlwapi_ordinal24:PANYARGS
shlwapi_ordinal24 TEXTEQU <__imp_shlwapi_ordinal24>
extern __imp_shlwapi_ordinal25:PANYARGS
shlwapi_ordinal25 TEXTEQU <__imp_shlwapi_ordinal25>
extern __imp_shlwapi_ordinal26:PANYARGS
shlwapi_ordinal26 TEXTEQU <__imp_shlwapi_ordinal26>
extern __imp_shlwapi_ordinal27:PANYARGS
shlwapi_ordinal27 TEXTEQU <__imp_shlwapi_ordinal27>
extern __imp_shlwapi_ordinal28:PANYARGS
shlwapi_ordinal28 TEXTEQU <__imp_shlwapi_ordinal28>
extern __imp_IsCharSpaceW:PANYARGS
IsCharSpaceW TEXTEQU <__imp_IsCharSpaceW>
extern __imp_shlwapi_ordinal30:PANYARGS
shlwapi_ordinal30 TEXTEQU <__imp_shlwapi_ordinal30>
extern __imp_shlwapi_ordinal31:PANYARGS
shlwapi_ordinal31 TEXTEQU <__imp_shlwapi_ordinal31>
extern __imp_shlwapi_ordinal32:PANYARGS
shlwapi_ordinal32 TEXTEQU <__imp_shlwapi_ordinal32>
extern __imp_shlwapi_ordinal33:PANYARGS
shlwapi_ordinal33 TEXTEQU <__imp_shlwapi_ordinal33>
extern __imp_shlwapi_ordinal34:PANYARGS
shlwapi_ordinal34 TEXTEQU <__imp_shlwapi_ordinal34>
extern __imp_shlwapi_ordinal35:PANYARGS
shlwapi_ordinal35 TEXTEQU <__imp_shlwapi_ordinal35>
extern __imp_shlwapi_ordinal36:PANYARGS
shlwapi_ordinal36 TEXTEQU <__imp_shlwapi_ordinal36>
extern __imp_shlwapi_ordinal37:PANYARGS
shlwapi_ordinal37 TEXTEQU <__imp_shlwapi_ordinal37>
extern __imp_shlwapi_ordinal38:PANYARGS
shlwapi_ordinal38 TEXTEQU <__imp_shlwapi_ordinal38>
extern __imp_shlwapi_ordinal39:PANYARGS
shlwapi_ordinal39 TEXTEQU <__imp_shlwapi_ordinal39>
extern __imp_shlwapi_ordinal40:PANYARGS
shlwapi_ordinal40 TEXTEQU <__imp_shlwapi_ordinal40>
extern __imp_shlwapi_ordinal41:PANYARGS
shlwapi_ordinal41 TEXTEQU <__imp_shlwapi_ordinal41>
extern __imp_shlwapi_ordinal42:PANYARGS
shlwapi_ordinal42 TEXTEQU <__imp_shlwapi_ordinal42>
extern __imp_shlwapi_ordinal43:PANYARGS
shlwapi_ordinal43 TEXTEQU <__imp_shlwapi_ordinal43>
extern __imp_shlwapi_ordinal44:PANYARGS
shlwapi_ordinal44 TEXTEQU <__imp_shlwapi_ordinal44>
extern __imp_shlwapi_ordinal45:PANYARGS
shlwapi_ordinal45 TEXTEQU <__imp_shlwapi_ordinal45>
extern __imp_shlwapi_ordinal46:PANYARGS
shlwapi_ordinal46 TEXTEQU <__imp_shlwapi_ordinal46>
extern __imp_shlwapi_ordinal47:PANYARGS
shlwapi_ordinal47 TEXTEQU <__imp_shlwapi_ordinal47>
extern __imp_shlwapi_ordinal48:PANYARGS
shlwapi_ordinal48 TEXTEQU <__imp_shlwapi_ordinal48>
extern __imp_shlwapi_ordinal49:PANYARGS
shlwapi_ordinal49 TEXTEQU <__imp_shlwapi_ordinal49>
extern __imp_shlwapi_ordinal50:PANYARGS
shlwapi_ordinal50 TEXTEQU <__imp_shlwapi_ordinal50>
extern __imp_shlwapi_ordinal51:PANYARGS
shlwapi_ordinal51 TEXTEQU <__imp_shlwapi_ordinal51>
extern __imp_shlwapi_ordinal52:PANYARGS
shlwapi_ordinal52 TEXTEQU <__imp_shlwapi_ordinal52>
extern __imp_shlwapi_ordinal53:PANYARGS
shlwapi_ordinal53 TEXTEQU <__imp_shlwapi_ordinal53>
extern __imp_shlwapi_ordinal54:PANYARGS
shlwapi_ordinal54 TEXTEQU <__imp_shlwapi_ordinal54>
extern __imp_shlwapi_ordinal55:PANYARGS
shlwapi_ordinal55 TEXTEQU <__imp_shlwapi_ordinal55>
extern __imp_shlwapi_ordinal56:PANYARGS
shlwapi_ordinal56 TEXTEQU <__imp_shlwapi_ordinal56>
extern __imp_shlwapi_ordinal57:PANYARGS
shlwapi_ordinal57 TEXTEQU <__imp_shlwapi_ordinal57>
extern __imp_shlwapi_ordinal58:PANYARGS
shlwapi_ordinal58 TEXTEQU <__imp_shlwapi_ordinal58>
extern __imp_shlwapi_ordinal59:PANYARGS
shlwapi_ordinal59 TEXTEQU <__imp_shlwapi_ordinal59>
extern __imp_shlwapi_ordinal60:PANYARGS
shlwapi_ordinal60 TEXTEQU <__imp_shlwapi_ordinal60>
extern __imp_shlwapi_ordinal61:PANYARGS
shlwapi_ordinal61 TEXTEQU <__imp_shlwapi_ordinal61>
extern __imp_shlwapi_ordinal62:PANYARGS
shlwapi_ordinal62 TEXTEQU <__imp_shlwapi_ordinal62>
extern __imp_shlwapi_ordinal63:PANYARGS
shlwapi_ordinal63 TEXTEQU <__imp_shlwapi_ordinal63>
extern __imp_shlwapi_ordinal64:PANYARGS
shlwapi_ordinal64 TEXTEQU <__imp_shlwapi_ordinal64>
extern __imp_shlwapi_ordinal65:PANYARGS
shlwapi_ordinal65 TEXTEQU <__imp_shlwapi_ordinal65>
extern __imp_shlwapi_ordinal66:PANYARGS
shlwapi_ordinal66 TEXTEQU <__imp_shlwapi_ordinal66>
extern __imp_shlwapi_ordinal67:PANYARGS
shlwapi_ordinal67 TEXTEQU <__imp_shlwapi_ordinal67>
extern __imp_shlwapi_ordinal68:PANYARGS
shlwapi_ordinal68 TEXTEQU <__imp_shlwapi_ordinal68>
extern __imp_shlwapi_ordinal69:PANYARGS
shlwapi_ordinal69 TEXTEQU <__imp_shlwapi_ordinal69>
extern __imp_shlwapi_ordinal70:PANYARGS
shlwapi_ordinal70 TEXTEQU <__imp_shlwapi_ordinal70>
extern __imp_shlwapi_ordinal71:PANYARGS
shlwapi_ordinal71 TEXTEQU <__imp_shlwapi_ordinal71>
extern __imp_shlwapi_ordinal72:PANYARGS
shlwapi_ordinal72 TEXTEQU <__imp_shlwapi_ordinal72>
extern __imp_shlwapi_ordinal73:PANYARGS
shlwapi_ordinal73 TEXTEQU <__imp_shlwapi_ordinal73>
extern __imp_shlwapi_ordinal74:PANYARGS
shlwapi_ordinal74 TEXTEQU <__imp_shlwapi_ordinal74>
extern __imp_shlwapi_ordinal75:PANYARGS
shlwapi_ordinal75 TEXTEQU <__imp_shlwapi_ordinal75>
extern __imp_shlwapi_ordinal76:PANYARGS
shlwapi_ordinal76 TEXTEQU <__imp_shlwapi_ordinal76>
extern __imp_shlwapi_ordinal77:PANYARGS
shlwapi_ordinal77 TEXTEQU <__imp_shlwapi_ordinal77>
extern __imp_shlwapi_ordinal78:PANYARGS
shlwapi_ordinal78 TEXTEQU <__imp_shlwapi_ordinal78>
extern __imp_shlwapi_ordinal79:PANYARGS
shlwapi_ordinal79 TEXTEQU <__imp_shlwapi_ordinal79>
extern __imp_shlwapi_ordinal80:PANYARGS
shlwapi_ordinal80 TEXTEQU <__imp_shlwapi_ordinal80>
extern __imp_shlwapi_ordinal81:PANYARGS
shlwapi_ordinal81 TEXTEQU <__imp_shlwapi_ordinal81>
extern __imp_shlwapi_ordinal82:PANYARGS
shlwapi_ordinal82 TEXTEQU <__imp_shlwapi_ordinal82>
extern __imp_shlwapi_ordinal83:PANYARGS
shlwapi_ordinal83 TEXTEQU <__imp_shlwapi_ordinal83>
extern __imp_shlwapi_ordinal84:PANYARGS
shlwapi_ordinal84 TEXTEQU <__imp_shlwapi_ordinal84>
extern __imp_shlwapi_ordinal85:PANYARGS
shlwapi_ordinal85 TEXTEQU <__imp_shlwapi_ordinal85>
extern __imp_shlwapi_ordinal86:PANYARGS
shlwapi_ordinal86 TEXTEQU <__imp_shlwapi_ordinal86>
extern __imp_shlwapi_ordinal87:PANYARGS
shlwapi_ordinal87 TEXTEQU <__imp_shlwapi_ordinal87>
extern __imp_shlwapi_ordinal88:PANYARGS
shlwapi_ordinal88 TEXTEQU <__imp_shlwapi_ordinal88>
extern __imp_shlwapi_ordinal89:PANYARGS
shlwapi_ordinal89 TEXTEQU <__imp_shlwapi_ordinal89>
extern __imp_shlwapi_ordinal90:PANYARGS
shlwapi_ordinal90 TEXTEQU <__imp_shlwapi_ordinal90>
extern __imp_shlwapi_ordinal91:PANYARGS
shlwapi_ordinal91 TEXTEQU <__imp_shlwapi_ordinal91>
extern __imp_shlwapi_ordinal92:PANYARGS
shlwapi_ordinal92 TEXTEQU <__imp_shlwapi_ordinal92>
extern __imp_shlwapi_ordinal93:PANYARGS
shlwapi_ordinal93 TEXTEQU <__imp_shlwapi_ordinal93>
extern __imp_shlwapi_ordinal94:PANYARGS
shlwapi_ordinal94 TEXTEQU <__imp_shlwapi_ordinal94>
extern __imp_shlwapi_ordinal95:PANYARGS
shlwapi_ordinal95 TEXTEQU <__imp_shlwapi_ordinal95>
extern __imp_shlwapi_ordinal96:PANYARGS
shlwapi_ordinal96 TEXTEQU <__imp_shlwapi_ordinal96>
extern __imp_shlwapi_ordinal97:PANYARGS
shlwapi_ordinal97 TEXTEQU <__imp_shlwapi_ordinal97>
extern __imp_shlwapi_ordinal98:PANYARGS
shlwapi_ordinal98 TEXTEQU <__imp_shlwapi_ordinal98>
extern __imp_shlwapi_ordinal99:PANYARGS
shlwapi_ordinal99 TEXTEQU <__imp_shlwapi_ordinal99>
extern __imp_shlwapi_ordinal100:PANYARGS
shlwapi_ordinal100 TEXTEQU <__imp_shlwapi_ordinal100>
extern __imp_shlwapi_ordinal101:PANYARGS
shlwapi_ordinal101 TEXTEQU <__imp_shlwapi_ordinal101>
extern __imp_shlwapi_ordinal102:PANYARGS
shlwapi_ordinal102 TEXTEQU <__imp_shlwapi_ordinal102>
extern __imp_shlwapi_ordinal103:PANYARGS
shlwapi_ordinal103 TEXTEQU <__imp_shlwapi_ordinal103>
extern __imp_shlwapi_ordinal104:PANYARGS
shlwapi_ordinal104 TEXTEQU <__imp_shlwapi_ordinal104>
extern __imp_shlwapi_ordinal105:PANYARGS
shlwapi_ordinal105 TEXTEQU <__imp_shlwapi_ordinal105>
extern __imp_shlwapi_ordinal106:PANYARGS
shlwapi_ordinal106 TEXTEQU <__imp_shlwapi_ordinal106>
extern __imp_shlwapi_ordinal107:PANYARGS
shlwapi_ordinal107 TEXTEQU <__imp_shlwapi_ordinal107>
extern __imp_shlwapi_ordinal108:PANYARGS
shlwapi_ordinal108 TEXTEQU <__imp_shlwapi_ordinal108>
extern __imp_shlwapi_ordinal109:PANYARGS
shlwapi_ordinal109 TEXTEQU <__imp_shlwapi_ordinal109>
extern __imp_shlwapi_ordinal110:PANYARGS
shlwapi_ordinal110 TEXTEQU <__imp_shlwapi_ordinal110>
extern __imp_shlwapi_ordinal111:PANYARGS
shlwapi_ordinal111 TEXTEQU <__imp_shlwapi_ordinal111>
extern __imp_shlwapi_ordinal112:PANYARGS
shlwapi_ordinal112 TEXTEQU <__imp_shlwapi_ordinal112>
extern __imp_shlwapi_ordinal113:PANYARGS
shlwapi_ordinal113 TEXTEQU <__imp_shlwapi_ordinal113>
extern __imp_shlwapi_ordinal114:PANYARGS
shlwapi_ordinal114 TEXTEQU <__imp_shlwapi_ordinal114>
extern __imp_shlwapi_ordinal115:PANYARGS
shlwapi_ordinal115 TEXTEQU <__imp_shlwapi_ordinal115>
extern __imp_shlwapi_ordinal116:PANYARGS
shlwapi_ordinal116 TEXTEQU <__imp_shlwapi_ordinal116>
extern __imp_shlwapi_ordinal117:PANYARGS
shlwapi_ordinal117 TEXTEQU <__imp_shlwapi_ordinal117>
extern __imp_shlwapi_ordinal118:PANYARGS
shlwapi_ordinal118 TEXTEQU <__imp_shlwapi_ordinal118>
extern __imp_shlwapi_ordinal119:PANYARGS
shlwapi_ordinal119 TEXTEQU <__imp_shlwapi_ordinal119>
extern __imp_shlwapi_ordinal120:PANYARGS
shlwapi_ordinal120 TEXTEQU <__imp_shlwapi_ordinal120>
extern __imp_shlwapi_ordinal121:PANYARGS
shlwapi_ordinal121 TEXTEQU <__imp_shlwapi_ordinal121>
extern __imp_shlwapi_ordinal122:PANYARGS
shlwapi_ordinal122 TEXTEQU <__imp_shlwapi_ordinal122>
extern __imp_shlwapi_ordinal123:PANYARGS
shlwapi_ordinal123 TEXTEQU <__imp_shlwapi_ordinal123>
extern __imp_shlwapi_ordinal124:PANYARGS
shlwapi_ordinal124 TEXTEQU <__imp_shlwapi_ordinal124>
extern __imp_shlwapi_ordinal125:PANYARGS
shlwapi_ordinal125 TEXTEQU <__imp_shlwapi_ordinal125>
extern __imp_shlwapi_ordinal126:PANYARGS
shlwapi_ordinal126 TEXTEQU <__imp_shlwapi_ordinal126>
extern __imp_shlwapi_ordinal127:PANYARGS
shlwapi_ordinal127 TEXTEQU <__imp_shlwapi_ordinal127>
extern __imp_shlwapi_ordinal128:PANYARGS
shlwapi_ordinal128 TEXTEQU <__imp_shlwapi_ordinal128>
extern __imp_shlwapi_ordinal129:PANYARGS
shlwapi_ordinal129 TEXTEQU <__imp_shlwapi_ordinal129>
extern __imp_shlwapi_ordinal130:PANYARGS
shlwapi_ordinal130 TEXTEQU <__imp_shlwapi_ordinal130>
extern __imp_shlwapi_ordinal131:PANYARGS
shlwapi_ordinal131 TEXTEQU <__imp_shlwapi_ordinal131>
extern __imp_shlwapi_ordinal132:PANYARGS
shlwapi_ordinal132 TEXTEQU <__imp_shlwapi_ordinal132>
extern __imp_shlwapi_ordinal133:PANYARGS
shlwapi_ordinal133 TEXTEQU <__imp_shlwapi_ordinal133>
extern __imp_shlwapi_ordinal134:PANYARGS
shlwapi_ordinal134 TEXTEQU <__imp_shlwapi_ordinal134>
extern __imp_shlwapi_ordinal135:PANYARGS
shlwapi_ordinal135 TEXTEQU <__imp_shlwapi_ordinal135>
extern __imp_shlwapi_ordinal136:PANYARGS
shlwapi_ordinal136 TEXTEQU <__imp_shlwapi_ordinal136>
extern __imp_shlwapi_ordinal137:PANYARGS
shlwapi_ordinal137 TEXTEQU <__imp_shlwapi_ordinal137>
extern __imp_shlwapi_ordinal138:PANYARGS
shlwapi_ordinal138 TEXTEQU <__imp_shlwapi_ordinal138>
extern __imp_shlwapi_ordinal139:PANYARGS
shlwapi_ordinal139 TEXTEQU <__imp_shlwapi_ordinal139>
extern __imp_shlwapi_ordinal140:PANYARGS
shlwapi_ordinal140 TEXTEQU <__imp_shlwapi_ordinal140>
extern __imp_shlwapi_ordinal141:PANYARGS
shlwapi_ordinal141 TEXTEQU <__imp_shlwapi_ordinal141>
extern __imp_shlwapi_ordinal142:PANYARGS
shlwapi_ordinal142 TEXTEQU <__imp_shlwapi_ordinal142>
extern __imp_shlwapi_ordinal143:PANYARGS
shlwapi_ordinal143 TEXTEQU <__imp_shlwapi_ordinal143>
extern __imp_shlwapi_ordinal144:PANYARGS
shlwapi_ordinal144 TEXTEQU <__imp_shlwapi_ordinal144>
extern __imp_shlwapi_ordinal145:PANYARGS
shlwapi_ordinal145 TEXTEQU <__imp_shlwapi_ordinal145>
extern __imp_shlwapi_ordinal146:PANYARGS
shlwapi_ordinal146 TEXTEQU <__imp_shlwapi_ordinal146>
extern __imp_shlwapi_ordinal147:PANYARGS
shlwapi_ordinal147 TEXTEQU <__imp_shlwapi_ordinal147>
extern __imp_shlwapi_ordinal148:PANYARGS
shlwapi_ordinal148 TEXTEQU <__imp_shlwapi_ordinal148>
extern __imp_shlwapi_ordinal149:PANYARGS
shlwapi_ordinal149 TEXTEQU <__imp_shlwapi_ordinal149>
extern __imp_shlwapi_ordinal150:PANYARGS
shlwapi_ordinal150 TEXTEQU <__imp_shlwapi_ordinal150>
extern __imp_shlwapi_ordinal151:PANYARGS
shlwapi_ordinal151 TEXTEQU <__imp_shlwapi_ordinal151>
extern __imp_shlwapi_ordinal152:PANYARGS
shlwapi_ordinal152 TEXTEQU <__imp_shlwapi_ordinal152>
extern __imp_shlwapi_ordinal153:PANYARGS
shlwapi_ordinal153 TEXTEQU <__imp_shlwapi_ordinal153>
extern __imp_shlwapi_ordinal154:PANYARGS
shlwapi_ordinal154 TEXTEQU <__imp_shlwapi_ordinal154>
extern __imp_StrCmpCA:PANYARGS
StrCmpC  TEXTEQU <__imp_StrCmpCA>
extern __imp_StrCmpCW:PANYARGS
StrCmpCW TEXTEQU <__imp_StrCmpCW>
extern __imp_StrCmpICA:PANYARGS
StrCmpIC  TEXTEQU <__imp_StrCmpICA>
extern __imp_StrCmpICW:PANYARGS
StrCmpICW TEXTEQU <__imp_StrCmpICW>
extern __imp_shlwapi_ordinal159:PANYARGS
shlwapi_ordinal159 TEXTEQU <__imp_shlwapi_ordinal159>
extern __imp_shlwapi_ordinal160:PANYARGS
shlwapi_ordinal160 TEXTEQU <__imp_shlwapi_ordinal160>
extern __imp_shlwapi_ordinal161:PANYARGS
shlwapi_ordinal161 TEXTEQU <__imp_shlwapi_ordinal161>
extern __imp_shlwapi_ordinal162:PANYARGS
shlwapi_ordinal162 TEXTEQU <__imp_shlwapi_ordinal162>
extern __imp_shlwapi_ordinal163:PANYARGS
shlwapi_ordinal163 TEXTEQU <__imp_shlwapi_ordinal163>
extern __imp_shlwapi_ordinal164:PANYARGS
shlwapi_ordinal164 TEXTEQU <__imp_shlwapi_ordinal164>
extern __imp_shlwapi_ordinal165:PANYARGS
shlwapi_ordinal165 TEXTEQU <__imp_shlwapi_ordinal165>
extern __imp_shlwapi_ordinal166:PANYARGS
shlwapi_ordinal166 TEXTEQU <__imp_shlwapi_ordinal166>
extern __imp_shlwapi_ordinal167:PANYARGS
shlwapi_ordinal167 TEXTEQU <__imp_shlwapi_ordinal167>
extern __imp_shlwapi_ordinal168:PANYARGS
shlwapi_ordinal168 TEXTEQU <__imp_shlwapi_ordinal168>
extern __imp_shlwapi_ordinal169:PANYARGS
shlwapi_ordinal169 TEXTEQU <__imp_shlwapi_ordinal169>
extern __imp_shlwapi_ordinal170:PANYARGS
shlwapi_ordinal170 TEXTEQU <__imp_shlwapi_ordinal170>
extern __imp_shlwapi_ordinal171:PANYARGS
shlwapi_ordinal171 TEXTEQU <__imp_shlwapi_ordinal171>
extern __imp_shlwapi_ordinal172:PANYARGS
shlwapi_ordinal172 TEXTEQU <__imp_shlwapi_ordinal172>
extern __imp_shlwapi_ordinal173:PANYARGS
shlwapi_ordinal173 TEXTEQU <__imp_shlwapi_ordinal173>
extern __imp_shlwapi_ordinal174:PANYARGS
shlwapi_ordinal174 TEXTEQU <__imp_shlwapi_ordinal174>
extern __imp_shlwapi_ordinal175:PANYARGS
shlwapi_ordinal175 TEXTEQU <__imp_shlwapi_ordinal175>
extern __imp_shlwapi_ordinal176:PANYARGS
shlwapi_ordinal176 TEXTEQU <__imp_shlwapi_ordinal176>
extern __imp_shlwapi_ordinal177:PANYARGS
shlwapi_ordinal177 TEXTEQU <__imp_shlwapi_ordinal177>
extern __imp_shlwapi_ordinal178:PANYARGS
shlwapi_ordinal178 TEXTEQU <__imp_shlwapi_ordinal178>
extern __imp_shlwapi_ordinal179:PANYARGS
shlwapi_ordinal179 TEXTEQU <__imp_shlwapi_ordinal179>
extern __imp_shlwapi_ordinal180:PANYARGS
shlwapi_ordinal180 TEXTEQU <__imp_shlwapi_ordinal180>
extern __imp_shlwapi_ordinal181:PANYARGS
shlwapi_ordinal181 TEXTEQU <__imp_shlwapi_ordinal181>
extern __imp_shlwapi_ordinal182:PANYARGS
shlwapi_ordinal182 TEXTEQU <__imp_shlwapi_ordinal182>
extern __imp_shlwapi_ordinal183:PANYARGS
shlwapi_ordinal183 TEXTEQU <__imp_shlwapi_ordinal183>
extern __imp_shlwapi_ordinal184:PANYARGS
shlwapi_ordinal184 TEXTEQU <__imp_shlwapi_ordinal184>
extern __imp_shlwapi_ordinal185:PANYARGS
shlwapi_ordinal185 TEXTEQU <__imp_shlwapi_ordinal185>
extern __imp_shlwapi_ordinal186:PANYARGS
shlwapi_ordinal186 TEXTEQU <__imp_shlwapi_ordinal186>
extern __imp_shlwapi_ordinal187:PANYARGS
shlwapi_ordinal187 TEXTEQU <__imp_shlwapi_ordinal187>
extern __imp_shlwapi_ordinal188:PANYARGS
shlwapi_ordinal188 TEXTEQU <__imp_shlwapi_ordinal188>
extern __imp_shlwapi_ordinal189:PANYARGS
shlwapi_ordinal189 TEXTEQU <__imp_shlwapi_ordinal189>
extern __imp_shlwapi_ordinal190:PANYARGS
shlwapi_ordinal190 TEXTEQU <__imp_shlwapi_ordinal190>
extern __imp_shlwapi_ordinal191:PANYARGS
shlwapi_ordinal191 TEXTEQU <__imp_shlwapi_ordinal191>
extern __imp_shlwapi_ordinal192:PANYARGS
shlwapi_ordinal192 TEXTEQU <__imp_shlwapi_ordinal192>
extern __imp_shlwapi_ordinal193:PANYARGS
shlwapi_ordinal193 TEXTEQU <__imp_shlwapi_ordinal193>
extern __imp_shlwapi_ordinal194:PANYARGS
shlwapi_ordinal194 TEXTEQU <__imp_shlwapi_ordinal194>
extern __imp_shlwapi_ordinal195:PANYARGS
shlwapi_ordinal195 TEXTEQU <__imp_shlwapi_ordinal195>
extern __imp_shlwapi_ordinal196:PANYARGS
shlwapi_ordinal196 TEXTEQU <__imp_shlwapi_ordinal196>
extern __imp_shlwapi_ordinal197:PANYARGS
shlwapi_ordinal197 TEXTEQU <__imp_shlwapi_ordinal197>
extern __imp_shlwapi_ordinal198:PANYARGS
shlwapi_ordinal198 TEXTEQU <__imp_shlwapi_ordinal198>
extern __imp_shlwapi_ordinal199:PANYARGS
shlwapi_ordinal199 TEXTEQU <__imp_shlwapi_ordinal199>
extern __imp_shlwapi_ordinal200:PANYARGS
shlwapi_ordinal200 TEXTEQU <__imp_shlwapi_ordinal200>
extern __imp_shlwapi_ordinal201:PANYARGS
shlwapi_ordinal201 TEXTEQU <__imp_shlwapi_ordinal201>
extern __imp_shlwapi_ordinal202:PANYARGS
shlwapi_ordinal202 TEXTEQU <__imp_shlwapi_ordinal202>
extern __imp_shlwapi_ordinal203:PANYARGS
shlwapi_ordinal203 TEXTEQU <__imp_shlwapi_ordinal203>
extern __imp_shlwapi_ordinal204:PANYARGS
shlwapi_ordinal204 TEXTEQU <__imp_shlwapi_ordinal204>
extern __imp_shlwapi_ordinal205:PANYARGS
shlwapi_ordinal205 TEXTEQU <__imp_shlwapi_ordinal205>
extern __imp_shlwapi_ordinal206:PANYARGS
shlwapi_ordinal206 TEXTEQU <__imp_shlwapi_ordinal206>
extern __imp_shlwapi_ordinal207:PANYARGS
shlwapi_ordinal207 TEXTEQU <__imp_shlwapi_ordinal207>
extern __imp_shlwapi_ordinal208:PANYARGS
shlwapi_ordinal208 TEXTEQU <__imp_shlwapi_ordinal208>
extern __imp_shlwapi_ordinal209:PANYARGS
shlwapi_ordinal209 TEXTEQU <__imp_shlwapi_ordinal209>
extern __imp_shlwapi_ordinal210:PANYARGS
shlwapi_ordinal210 TEXTEQU <__imp_shlwapi_ordinal210>
extern __imp_shlwapi_ordinal211:PANYARGS
shlwapi_ordinal211 TEXTEQU <__imp_shlwapi_ordinal211>
extern __imp_shlwapi_ordinal212:PANYARGS
shlwapi_ordinal212 TEXTEQU <__imp_shlwapi_ordinal212>
extern __imp_shlwapi_ordinal213:PANYARGS
shlwapi_ordinal213 TEXTEQU <__imp_shlwapi_ordinal213>
extern __imp_shlwapi_ordinal214:PANYARGS
shlwapi_ordinal214 TEXTEQU <__imp_shlwapi_ordinal214>
extern __imp_shlwapi_ordinal215:PANYARGS
shlwapi_ordinal215 TEXTEQU <__imp_shlwapi_ordinal215>
extern __imp_shlwapi_ordinal216:PANYARGS
shlwapi_ordinal216 TEXTEQU <__imp_shlwapi_ordinal216>
extern __imp_shlwapi_ordinal217:PANYARGS
shlwapi_ordinal217 TEXTEQU <__imp_shlwapi_ordinal217>
extern __imp_shlwapi_ordinal218:PANYARGS
shlwapi_ordinal218 TEXTEQU <__imp_shlwapi_ordinal218>
extern __imp_shlwapi_ordinal219:PANYARGS
shlwapi_ordinal219 TEXTEQU <__imp_shlwapi_ordinal219>
extern __imp_shlwapi_ordinal220:PANYARGS
shlwapi_ordinal220 TEXTEQU <__imp_shlwapi_ordinal220>
extern __imp_shlwapi_ordinal221:PANYARGS
shlwapi_ordinal221 TEXTEQU <__imp_shlwapi_ordinal221>
extern __imp_shlwapi_ordinal222:PANYARGS
shlwapi_ordinal222 TEXTEQU <__imp_shlwapi_ordinal222>
extern __imp_shlwapi_ordinal223:PANYARGS
shlwapi_ordinal223 TEXTEQU <__imp_shlwapi_ordinal223>
extern __imp_shlwapi_ordinal224:PANYARGS
shlwapi_ordinal224 TEXTEQU <__imp_shlwapi_ordinal224>
extern __imp_shlwapi_ordinal225:PANYARGS
shlwapi_ordinal225 TEXTEQU <__imp_shlwapi_ordinal225>
extern __imp_shlwapi_ordinal226:PANYARGS
shlwapi_ordinal226 TEXTEQU <__imp_shlwapi_ordinal226>
extern __imp_shlwapi_ordinal227:PANYARGS
shlwapi_ordinal227 TEXTEQU <__imp_shlwapi_ordinal227>
extern __imp_shlwapi_ordinal228:PANYARGS
shlwapi_ordinal228 TEXTEQU <__imp_shlwapi_ordinal228>
extern __imp_shlwapi_ordinal229:PANYARGS
shlwapi_ordinal229 TEXTEQU <__imp_shlwapi_ordinal229>
extern __imp_shlwapi_ordinal230:PANYARGS
shlwapi_ordinal230 TEXTEQU <__imp_shlwapi_ordinal230>
extern __imp_shlwapi_ordinal231:PANYARGS
shlwapi_ordinal231 TEXTEQU <__imp_shlwapi_ordinal231>
extern __imp_shlwapi_ordinal232:PANYARGS
shlwapi_ordinal232 TEXTEQU <__imp_shlwapi_ordinal232>
extern __imp_shlwapi_ordinal233:PANYARGS
shlwapi_ordinal233 TEXTEQU <__imp_shlwapi_ordinal233>
extern __imp_shlwapi_ordinal234:PANYARGS
shlwapi_ordinal234 TEXTEQU <__imp_shlwapi_ordinal234>
extern __imp_shlwapi_ordinal235:PANYARGS
shlwapi_ordinal235 TEXTEQU <__imp_shlwapi_ordinal235>
extern __imp_shlwapi_ordinal236:PANYARGS
shlwapi_ordinal236 TEXTEQU <__imp_shlwapi_ordinal236>
extern __imp_shlwapi_ordinal237:PANYARGS
shlwapi_ordinal237 TEXTEQU <__imp_shlwapi_ordinal237>
extern __imp_shlwapi_ordinal238:PANYARGS
shlwapi_ordinal238 TEXTEQU <__imp_shlwapi_ordinal238>
extern __imp_shlwapi_ordinal239:PANYARGS
shlwapi_ordinal239 TEXTEQU <__imp_shlwapi_ordinal239>
extern __imp_shlwapi_ordinal240:PANYARGS
shlwapi_ordinal240 TEXTEQU <__imp_shlwapi_ordinal240>
extern __imp_shlwapi_ordinal241:PANYARGS
shlwapi_ordinal241 TEXTEQU <__imp_shlwapi_ordinal241>
extern __imp_shlwapi_ordinal242:PANYARGS
shlwapi_ordinal242 TEXTEQU <__imp_shlwapi_ordinal242>
extern __imp_shlwapi_ordinal243:PANYARGS
shlwapi_ordinal243 TEXTEQU <__imp_shlwapi_ordinal243>
extern __imp_shlwapi_ordinal244:PANYARGS
shlwapi_ordinal244 TEXTEQU <__imp_shlwapi_ordinal244>
extern __imp_shlwapi_ordinal245:PANYARGS
shlwapi_ordinal245 TEXTEQU <__imp_shlwapi_ordinal245>
extern __imp_shlwapi_ordinal246:PANYARGS
shlwapi_ordinal246 TEXTEQU <__imp_shlwapi_ordinal246>
extern __imp_shlwapi_ordinal247:PANYARGS
shlwapi_ordinal247 TEXTEQU <__imp_shlwapi_ordinal247>
extern __imp_shlwapi_ordinal248:PANYARGS
shlwapi_ordinal248 TEXTEQU <__imp_shlwapi_ordinal248>
extern __imp_shlwapi_ordinal249:PANYARGS
shlwapi_ordinal249 TEXTEQU <__imp_shlwapi_ordinal249>
extern __imp_shlwapi_ordinal250:PANYARGS
shlwapi_ordinal250 TEXTEQU <__imp_shlwapi_ordinal250>
extern __imp_shlwapi_ordinal251:PANYARGS
shlwapi_ordinal251 TEXTEQU <__imp_shlwapi_ordinal251>
extern __imp_shlwapi_ordinal252:PANYARGS
shlwapi_ordinal252 TEXTEQU <__imp_shlwapi_ordinal252>
extern __imp_shlwapi_ordinal253:PANYARGS
shlwapi_ordinal253 TEXTEQU <__imp_shlwapi_ordinal253>
extern __imp_shlwapi_ordinal254:PANYARGS
shlwapi_ordinal254 TEXTEQU <__imp_shlwapi_ordinal254>
extern __imp_shlwapi_ordinal255:PANYARGS
shlwapi_ordinal255 TEXTEQU <__imp_shlwapi_ordinal255>
extern __imp_shlwapi_ordinal256:PANYARGS
shlwapi_ordinal256 TEXTEQU <__imp_shlwapi_ordinal256>
extern __imp_shlwapi_ordinal257:PANYARGS
shlwapi_ordinal257 TEXTEQU <__imp_shlwapi_ordinal257>
extern __imp_shlwapi_ordinal258:PANYARGS
shlwapi_ordinal258 TEXTEQU <__imp_shlwapi_ordinal258>
extern __imp_shlwapi_ordinal259:PANYARGS
shlwapi_ordinal259 TEXTEQU <__imp_shlwapi_ordinal259>
extern __imp_shlwapi_ordinal260:PANYARGS
shlwapi_ordinal260 TEXTEQU <__imp_shlwapi_ordinal260>
extern __imp_shlwapi_ordinal261:PANYARGS
shlwapi_ordinal261 TEXTEQU <__imp_shlwapi_ordinal261>
extern __imp_shlwapi_ordinal262:PANYARGS
shlwapi_ordinal262 TEXTEQU <__imp_shlwapi_ordinal262>
extern __imp_shlwapi_ordinal263:PANYARGS
shlwapi_ordinal263 TEXTEQU <__imp_shlwapi_ordinal263>
extern __imp_shlwapi_ordinal264:PANYARGS
shlwapi_ordinal264 TEXTEQU <__imp_shlwapi_ordinal264>
extern __imp_shlwapi_ordinal265:PANYARGS
shlwapi_ordinal265 TEXTEQU <__imp_shlwapi_ordinal265>
extern __imp_shlwapi_ordinal266:PANYARGS
shlwapi_ordinal266 TEXTEQU <__imp_shlwapi_ordinal266>
extern __imp_shlwapi_ordinal267:PANYARGS
shlwapi_ordinal267 TEXTEQU <__imp_shlwapi_ordinal267>
extern __imp_shlwapi_ordinal268:PANYARGS
shlwapi_ordinal268 TEXTEQU <__imp_shlwapi_ordinal268>
extern __imp_shlwapi_ordinal269:PANYARGS
shlwapi_ordinal269 TEXTEQU <__imp_shlwapi_ordinal269>
extern __imp_shlwapi_ordinal270:PANYARGS
shlwapi_ordinal270 TEXTEQU <__imp_shlwapi_ordinal270>
extern __imp_shlwapi_ordinal271:PANYARGS
shlwapi_ordinal271 TEXTEQU <__imp_shlwapi_ordinal271>
extern __imp_shlwapi_ordinal272:PANYARGS
shlwapi_ordinal272 TEXTEQU <__imp_shlwapi_ordinal272>
extern __imp_shlwapi_ordinal273:PANYARGS
shlwapi_ordinal273 TEXTEQU <__imp_shlwapi_ordinal273>
extern __imp_shlwapi_ordinal274:PANYARGS
shlwapi_ordinal274 TEXTEQU <__imp_shlwapi_ordinal274>
extern __imp_shlwapi_ordinal275:PANYARGS
shlwapi_ordinal275 TEXTEQU <__imp_shlwapi_ordinal275>
extern __imp_shlwapi_ordinal276:PANYARGS
shlwapi_ordinal276 TEXTEQU <__imp_shlwapi_ordinal276>
extern __imp_shlwapi_ordinal277:PANYARGS
shlwapi_ordinal277 TEXTEQU <__imp_shlwapi_ordinal277>
extern __imp_shlwapi_ordinal278:PANYARGS
shlwapi_ordinal278 TEXTEQU <__imp_shlwapi_ordinal278>
extern __imp_shlwapi_ordinal279:PANYARGS
shlwapi_ordinal279 TEXTEQU <__imp_shlwapi_ordinal279>
extern __imp_shlwapi_ordinal280:PANYARGS
shlwapi_ordinal280 TEXTEQU <__imp_shlwapi_ordinal280>
extern __imp_shlwapi_ordinal281:PANYARGS
shlwapi_ordinal281 TEXTEQU <__imp_shlwapi_ordinal281>
extern __imp_shlwapi_ordinal282:PANYARGS
shlwapi_ordinal282 TEXTEQU <__imp_shlwapi_ordinal282>
extern __imp_shlwapi_ordinal283:PANYARGS
shlwapi_ordinal283 TEXTEQU <__imp_shlwapi_ordinal283>
extern __imp_shlwapi_ordinal284:PANYARGS
shlwapi_ordinal284 TEXTEQU <__imp_shlwapi_ordinal284>
extern __imp_shlwapi_ordinal285:PANYARGS
shlwapi_ordinal285 TEXTEQU <__imp_shlwapi_ordinal285>
extern __imp_shlwapi_ordinal286:PANYARGS
shlwapi_ordinal286 TEXTEQU <__imp_shlwapi_ordinal286>
extern __imp_shlwapi_ordinal287:PANYARGS
shlwapi_ordinal287 TEXTEQU <__imp_shlwapi_ordinal287>
extern __imp_shlwapi_ordinal288:PANYARGS
shlwapi_ordinal288 TEXTEQU <__imp_shlwapi_ordinal288>
extern __imp_shlwapi_ordinal289:PANYARGS
shlwapi_ordinal289 TEXTEQU <__imp_shlwapi_ordinal289>
extern __imp_shlwapi_ordinal290:PANYARGS
shlwapi_ordinal290 TEXTEQU <__imp_shlwapi_ordinal290>
extern __imp_shlwapi_ordinal291:PANYARGS
shlwapi_ordinal291 TEXTEQU <__imp_shlwapi_ordinal291>
extern __imp_shlwapi_ordinal292:PANYARGS
shlwapi_ordinal292 TEXTEQU <__imp_shlwapi_ordinal292>
extern __imp_shlwapi_ordinal293:PANYARGS
shlwapi_ordinal293 TEXTEQU <__imp_shlwapi_ordinal293>
extern __imp_shlwapi_ordinal294:PANYARGS
shlwapi_ordinal294 TEXTEQU <__imp_shlwapi_ordinal294>
extern __imp_shlwapi_ordinal295:PANYARGS
shlwapi_ordinal295 TEXTEQU <__imp_shlwapi_ordinal295>
extern __imp_shlwapi_ordinal296:PANYARGS
shlwapi_ordinal296 TEXTEQU <__imp_shlwapi_ordinal296>
extern __imp_shlwapi_ordinal297:PANYARGS
shlwapi_ordinal297 TEXTEQU <__imp_shlwapi_ordinal297>
extern __imp_shlwapi_ordinal298:PANYARGS
shlwapi_ordinal298 TEXTEQU <__imp_shlwapi_ordinal298>
extern __imp_shlwapi_ordinal299:PANYARGS
shlwapi_ordinal299 TEXTEQU <__imp_shlwapi_ordinal299>
extern __imp_shlwapi_ordinal300:PANYARGS
shlwapi_ordinal300 TEXTEQU <__imp_shlwapi_ordinal300>
extern __imp_shlwapi_ordinal301:PANYARGS
shlwapi_ordinal301 TEXTEQU <__imp_shlwapi_ordinal301>
extern __imp_shlwapi_ordinal302:PANYARGS
shlwapi_ordinal302 TEXTEQU <__imp_shlwapi_ordinal302>
extern __imp_shlwapi_ordinal303:PANYARGS
shlwapi_ordinal303 TEXTEQU <__imp_shlwapi_ordinal303>
extern __imp_shlwapi_ordinal304:PANYARGS
shlwapi_ordinal304 TEXTEQU <__imp_shlwapi_ordinal304>
extern __imp_shlwapi_ordinal305:PANYARGS
shlwapi_ordinal305 TEXTEQU <__imp_shlwapi_ordinal305>
extern __imp_shlwapi_ordinal306:PANYARGS
shlwapi_ordinal306 TEXTEQU <__imp_shlwapi_ordinal306>
extern __imp_shlwapi_ordinal307:PANYARGS
shlwapi_ordinal307 TEXTEQU <__imp_shlwapi_ordinal307>
extern __imp_shlwapi_ordinal308:PANYARGS
shlwapi_ordinal308 TEXTEQU <__imp_shlwapi_ordinal308>
extern __imp_shlwapi_ordinal309:PANYARGS
shlwapi_ordinal309 TEXTEQU <__imp_shlwapi_ordinal309>
extern __imp_shlwapi_ordinal310:PANYARGS
shlwapi_ordinal310 TEXTEQU <__imp_shlwapi_ordinal310>
extern __imp_shlwapi_ordinal311:PANYARGS
shlwapi_ordinal311 TEXTEQU <__imp_shlwapi_ordinal311>
extern __imp_shlwapi_ordinal312:PANYARGS
shlwapi_ordinal312 TEXTEQU <__imp_shlwapi_ordinal312>
extern __imp_shlwapi_ordinal313:PANYARGS
shlwapi_ordinal313 TEXTEQU <__imp_shlwapi_ordinal313>
extern __imp_shlwapi_ordinal314:PANYARGS
shlwapi_ordinal314 TEXTEQU <__imp_shlwapi_ordinal314>
extern __imp_shlwapi_ordinal315:PANYARGS
shlwapi_ordinal315 TEXTEQU <__imp_shlwapi_ordinal315>
extern __imp_shlwapi_ordinal316:PANYARGS
shlwapi_ordinal316 TEXTEQU <__imp_shlwapi_ordinal316>
extern __imp_shlwapi_ordinal317:PANYARGS
shlwapi_ordinal317 TEXTEQU <__imp_shlwapi_ordinal317>
extern __imp_shlwapi_ordinal318:PANYARGS
shlwapi_ordinal318 TEXTEQU <__imp_shlwapi_ordinal318>
extern __imp_shlwapi_ordinal319:PANYARGS
shlwapi_ordinal319 TEXTEQU <__imp_shlwapi_ordinal319>
extern __imp_shlwapi_ordinal320:PANYARGS
shlwapi_ordinal320 TEXTEQU <__imp_shlwapi_ordinal320>
extern __imp_shlwapi_ordinal321:PANYARGS
shlwapi_ordinal321 TEXTEQU <__imp_shlwapi_ordinal321>
extern __imp_shlwapi_ordinal322:PANYARGS
shlwapi_ordinal322 TEXTEQU <__imp_shlwapi_ordinal322>
extern __imp_shlwapi_ordinal323:PANYARGS
shlwapi_ordinal323 TEXTEQU <__imp_shlwapi_ordinal323>
extern __imp_shlwapi_ordinal324:PANYARGS
shlwapi_ordinal324 TEXTEQU <__imp_shlwapi_ordinal324>
extern __imp_shlwapi_ordinal325:PANYARGS
shlwapi_ordinal325 TEXTEQU <__imp_shlwapi_ordinal325>
extern __imp_shlwapi_ordinal326:PANYARGS
shlwapi_ordinal326 TEXTEQU <__imp_shlwapi_ordinal326>
extern __imp_shlwapi_ordinal327:PANYARGS
shlwapi_ordinal327 TEXTEQU <__imp_shlwapi_ordinal327>
extern __imp_shlwapi_ordinal328:PANYARGS
shlwapi_ordinal328 TEXTEQU <__imp_shlwapi_ordinal328>
extern __imp_shlwapi_ordinal329:PANYARGS
shlwapi_ordinal329 TEXTEQU <__imp_shlwapi_ordinal329>
extern __imp_shlwapi_ordinal330:PANYARGS
shlwapi_ordinal330 TEXTEQU <__imp_shlwapi_ordinal330>
extern __imp_shlwapi_ordinal331:PANYARGS
shlwapi_ordinal331 TEXTEQU <__imp_shlwapi_ordinal331>
extern __imp_shlwapi_ordinal332:PANYARGS
shlwapi_ordinal332 TEXTEQU <__imp_shlwapi_ordinal332>
extern __imp_shlwapi_ordinal333:PANYARGS
shlwapi_ordinal333 TEXTEQU <__imp_shlwapi_ordinal333>
extern __imp_shlwapi_ordinal334:PANYARGS
shlwapi_ordinal334 TEXTEQU <__imp_shlwapi_ordinal334>
extern __imp_shlwapi_ordinal335:PANYARGS
shlwapi_ordinal335 TEXTEQU <__imp_shlwapi_ordinal335>
extern __imp_shlwapi_ordinal336:PANYARGS
shlwapi_ordinal336 TEXTEQU <__imp_shlwapi_ordinal336>
extern __imp_shlwapi_ordinal337:PANYARGS
shlwapi_ordinal337 TEXTEQU <__imp_shlwapi_ordinal337>
extern __imp_shlwapi_ordinal338:PANYARGS
shlwapi_ordinal338 TEXTEQU <__imp_shlwapi_ordinal338>
extern __imp_shlwapi_ordinal339:PANYARGS
shlwapi_ordinal339 TEXTEQU <__imp_shlwapi_ordinal339>
extern __imp_shlwapi_ordinal340:PANYARGS
shlwapi_ordinal340 TEXTEQU <__imp_shlwapi_ordinal340>
extern __imp_shlwapi_ordinal341:PANYARGS
shlwapi_ordinal341 TEXTEQU <__imp_shlwapi_ordinal341>
extern __imp_shlwapi_ordinal342:PANYARGS
shlwapi_ordinal342 TEXTEQU <__imp_shlwapi_ordinal342>
extern __imp_shlwapi_ordinal343:PANYARGS
shlwapi_ordinal343 TEXTEQU <__imp_shlwapi_ordinal343>
extern __imp_shlwapi_ordinal344:PANYARGS
shlwapi_ordinal344 TEXTEQU <__imp_shlwapi_ordinal344>
extern __imp_shlwapi_ordinal345:PANYARGS
shlwapi_ordinal345 TEXTEQU <__imp_shlwapi_ordinal345>
extern __imp_shlwapi_ordinal346:PANYARGS
shlwapi_ordinal346 TEXTEQU <__imp_shlwapi_ordinal346>
extern __imp_shlwapi_ordinal347:PANYARGS
shlwapi_ordinal347 TEXTEQU <__imp_shlwapi_ordinal347>
extern __imp_shlwapi_ordinal348:PANYARGS
shlwapi_ordinal348 TEXTEQU <__imp_shlwapi_ordinal348>
extern __imp_shlwapi_ordinal349:PANYARGS
shlwapi_ordinal349 TEXTEQU <__imp_shlwapi_ordinal349>
extern __imp_shlwapi_ordinal350:PANYARGS
shlwapi_ordinal350 TEXTEQU <__imp_shlwapi_ordinal350>
extern __imp_shlwapi_ordinal351:PANYARGS
shlwapi_ordinal351 TEXTEQU <__imp_shlwapi_ordinal351>
extern __imp_shlwapi_ordinal352:PANYARGS
shlwapi_ordinal352 TEXTEQU <__imp_shlwapi_ordinal352>
extern __imp_shlwapi_ordinal353:PANYARGS
shlwapi_ordinal353 TEXTEQU <__imp_shlwapi_ordinal353>
extern __imp_shlwapi_ordinal354:PANYARGS
shlwapi_ordinal354 TEXTEQU <__imp_shlwapi_ordinal354>
extern __imp_shlwapi_ordinal355:PANYARGS
shlwapi_ordinal355 TEXTEQU <__imp_shlwapi_ordinal355>
extern __imp_AssocCreate:PANYARGS
AssocCreate TEXTEQU <__imp_AssocCreate>
extern __imp_shlwapi_ordinal357:PANYARGS
shlwapi_ordinal357 TEXTEQU <__imp_shlwapi_ordinal357>
extern __imp_shlwapi_ordinal358:PANYARGS
shlwapi_ordinal358 TEXTEQU <__imp_shlwapi_ordinal358>
extern __imp_shlwapi_ordinal359:PANYARGS
shlwapi_ordinal359 TEXTEQU <__imp_shlwapi_ordinal359>
extern __imp_shlwapi_ordinal360:PANYARGS
shlwapi_ordinal360 TEXTEQU <__imp_shlwapi_ordinal360>
extern __imp_shlwapi_ordinal361:PANYARGS
shlwapi_ordinal361 TEXTEQU <__imp_shlwapi_ordinal361>
extern __imp_shlwapi_ordinal362:PANYARGS
shlwapi_ordinal362 TEXTEQU <__imp_shlwapi_ordinal362>
extern __imp_shlwapi_ordinal363:PANYARGS
shlwapi_ordinal363 TEXTEQU <__imp_shlwapi_ordinal363>
extern __imp_shlwapi_ordinal364:PANYARGS
shlwapi_ordinal364 TEXTEQU <__imp_shlwapi_ordinal364>
extern __imp_shlwapi_ordinal365:PANYARGS
shlwapi_ordinal365 TEXTEQU <__imp_shlwapi_ordinal365>
extern __imp_shlwapi_ordinal366:PANYARGS
shlwapi_ordinal366 TEXTEQU <__imp_shlwapi_ordinal366>
extern __imp_shlwapi_ordinal367:PANYARGS
shlwapi_ordinal367 TEXTEQU <__imp_shlwapi_ordinal367>
extern __imp_shlwapi_ordinal368:PANYARGS
shlwapi_ordinal368 TEXTEQU <__imp_shlwapi_ordinal368>
extern __imp_shlwapi_ordinal369:PANYARGS
shlwapi_ordinal369 TEXTEQU <__imp_shlwapi_ordinal369>
extern __imp_shlwapi_ordinal370:PANYARGS
shlwapi_ordinal370 TEXTEQU <__imp_shlwapi_ordinal370>
extern __imp_shlwapi_ordinal371:PANYARGS
shlwapi_ordinal371 TEXTEQU <__imp_shlwapi_ordinal371>
extern __imp_shlwapi_ordinal372:PANYARGS
shlwapi_ordinal372 TEXTEQU <__imp_shlwapi_ordinal372>
extern __imp_shlwapi_ordinal373:PANYARGS
shlwapi_ordinal373 TEXTEQU <__imp_shlwapi_ordinal373>
extern __imp_shlwapi_ordinal374:PANYARGS
shlwapi_ordinal374 TEXTEQU <__imp_shlwapi_ordinal374>
extern __imp_shlwapi_ordinal375:PANYARGS
shlwapi_ordinal375 TEXTEQU <__imp_shlwapi_ordinal375>
extern __imp_shlwapi_ordinal376:PANYARGS
shlwapi_ordinal376 TEXTEQU <__imp_shlwapi_ordinal376>
extern __imp_shlwapi_ordinal377:PANYARGS
shlwapi_ordinal377 TEXTEQU <__imp_shlwapi_ordinal377>
extern __imp_shlwapi_ordinal378:PANYARGS
shlwapi_ordinal378 TEXTEQU <__imp_shlwapi_ordinal378>
extern __imp_shlwapi_ordinal379:PANYARGS
shlwapi_ordinal379 TEXTEQU <__imp_shlwapi_ordinal379>
extern __imp_shlwapi_ordinal380:PANYARGS
shlwapi_ordinal380 TEXTEQU <__imp_shlwapi_ordinal380>
extern __imp_shlwapi_ordinal381:PANYARGS
shlwapi_ordinal381 TEXTEQU <__imp_shlwapi_ordinal381>
extern __imp_shlwapi_ordinal382:PANYARGS
shlwapi_ordinal382 TEXTEQU <__imp_shlwapi_ordinal382>
extern __imp_shlwapi_ordinal383:PANYARGS
shlwapi_ordinal383 TEXTEQU <__imp_shlwapi_ordinal383>
extern __imp_shlwapi_ordinal384:PANYARGS
shlwapi_ordinal384 TEXTEQU <__imp_shlwapi_ordinal384>
extern __imp_shlwapi_ordinal385:PANYARGS
shlwapi_ordinal385 TEXTEQU <__imp_shlwapi_ordinal385>
extern __imp_shlwapi_ordinal386:PANYARGS
shlwapi_ordinal386 TEXTEQU <__imp_shlwapi_ordinal386>
extern __imp_shlwapi_ordinal387:PANYARGS
shlwapi_ordinal387 TEXTEQU <__imp_shlwapi_ordinal387>
extern __imp_shlwapi_ordinal388:PANYARGS
shlwapi_ordinal388 TEXTEQU <__imp_shlwapi_ordinal388>
extern __imp_shlwapi_ordinal389:PANYARGS
shlwapi_ordinal389 TEXTEQU <__imp_shlwapi_ordinal389>
extern __imp_shlwapi_ordinal390:PANYARGS
shlwapi_ordinal390 TEXTEQU <__imp_shlwapi_ordinal390>
extern __imp_shlwapi_ordinal391:PANYARGS
shlwapi_ordinal391 TEXTEQU <__imp_shlwapi_ordinal391>
extern __imp_shlwapi_ordinal392:PANYARGS
shlwapi_ordinal392 TEXTEQU <__imp_shlwapi_ordinal392>
extern __imp_shlwapi_ordinal393:PANYARGS
shlwapi_ordinal393 TEXTEQU <__imp_shlwapi_ordinal393>
extern __imp_shlwapi_ordinal394:PANYARGS
shlwapi_ordinal394 TEXTEQU <__imp_shlwapi_ordinal394>
extern __imp_shlwapi_ordinal395:PANYARGS
shlwapi_ordinal395 TEXTEQU <__imp_shlwapi_ordinal395>
extern __imp_shlwapi_ordinal396:PANYARGS
shlwapi_ordinal396 TEXTEQU <__imp_shlwapi_ordinal396>
extern __imp_shlwapi_ordinal397:PANYARGS
shlwapi_ordinal397 TEXTEQU <__imp_shlwapi_ordinal397>
extern __imp_shlwapi_ordinal398:PANYARGS
shlwapi_ordinal398 TEXTEQU <__imp_shlwapi_ordinal398>
extern __imp_shlwapi_ordinal399:PANYARGS
shlwapi_ordinal399 TEXTEQU <__imp_shlwapi_ordinal399>
extern __imp_shlwapi_ordinal400:PANYARGS
shlwapi_ordinal400 TEXTEQU <__imp_shlwapi_ordinal400>
extern __imp_shlwapi_ordinal401:PANYARGS
shlwapi_ordinal401 TEXTEQU <__imp_shlwapi_ordinal401>
extern __imp_shlwapi_ordinal402:PANYARGS
shlwapi_ordinal402 TEXTEQU <__imp_shlwapi_ordinal402>
extern __imp_shlwapi_ordinal403:PANYARGS
shlwapi_ordinal403 TEXTEQU <__imp_shlwapi_ordinal403>
extern __imp_shlwapi_ordinal404:PANYARGS
shlwapi_ordinal404 TEXTEQU <__imp_shlwapi_ordinal404>
extern __imp_shlwapi_ordinal405:PANYARGS
shlwapi_ordinal405 TEXTEQU <__imp_shlwapi_ordinal405>
extern __imp_shlwapi_ordinal406:PANYARGS
shlwapi_ordinal406 TEXTEQU <__imp_shlwapi_ordinal406>
extern __imp_shlwapi_ordinal407:PANYARGS
shlwapi_ordinal407 TEXTEQU <__imp_shlwapi_ordinal407>
extern __imp_shlwapi_ordinal408:PANYARGS
shlwapi_ordinal408 TEXTEQU <__imp_shlwapi_ordinal408>
extern __imp_shlwapi_ordinal409:PANYARGS
shlwapi_ordinal409 TEXTEQU <__imp_shlwapi_ordinal409>
extern __imp_shlwapi_ordinal410:PANYARGS
shlwapi_ordinal410 TEXTEQU <__imp_shlwapi_ordinal410>
extern __imp_shlwapi_ordinal411:PANYARGS
shlwapi_ordinal411 TEXTEQU <__imp_shlwapi_ordinal411>
extern __imp_shlwapi_ordinal412:PANYARGS
shlwapi_ordinal412 TEXTEQU <__imp_shlwapi_ordinal412>
extern __imp_shlwapi_ordinal413:PANYARGS
shlwapi_ordinal413 TEXTEQU <__imp_shlwapi_ordinal413>
extern __imp_shlwapi_ordinal414:PANYARGS
shlwapi_ordinal414 TEXTEQU <__imp_shlwapi_ordinal414>
extern __imp_shlwapi_ordinal415:PANYARGS
shlwapi_ordinal415 TEXTEQU <__imp_shlwapi_ordinal415>
extern __imp_shlwapi_ordinal416:PANYARGS
shlwapi_ordinal416 TEXTEQU <__imp_shlwapi_ordinal416>
extern __imp_shlwapi_ordinal417:PANYARGS
shlwapi_ordinal417 TEXTEQU <__imp_shlwapi_ordinal417>
extern __imp_shlwapi_ordinal418:PANYARGS
shlwapi_ordinal418 TEXTEQU <__imp_shlwapi_ordinal418>
extern __imp_shlwapi_ordinal419:PANYARGS
shlwapi_ordinal419 TEXTEQU <__imp_shlwapi_ordinal419>
extern __imp_shlwapi_ordinal420:PANYARGS
shlwapi_ordinal420 TEXTEQU <__imp_shlwapi_ordinal420>
extern __imp_shlwapi_ordinal421:PANYARGS
shlwapi_ordinal421 TEXTEQU <__imp_shlwapi_ordinal421>
extern __imp_shlwapi_ordinal422:PANYARGS
shlwapi_ordinal422 TEXTEQU <__imp_shlwapi_ordinal422>
extern __imp_shlwapi_ordinal423:PANYARGS
shlwapi_ordinal423 TEXTEQU <__imp_shlwapi_ordinal423>
extern __imp_shlwapi_ordinal424:PANYARGS
shlwapi_ordinal424 TEXTEQU <__imp_shlwapi_ordinal424>
extern __imp_shlwapi_ordinal425:PANYARGS
shlwapi_ordinal425 TEXTEQU <__imp_shlwapi_ordinal425>
extern __imp_shlwapi_ordinal426:PANYARGS
shlwapi_ordinal426 TEXTEQU <__imp_shlwapi_ordinal426>
extern __imp_shlwapi_ordinal427:PANYARGS
shlwapi_ordinal427 TEXTEQU <__imp_shlwapi_ordinal427>
extern __imp_shlwapi_ordinal428:PANYARGS
shlwapi_ordinal428 TEXTEQU <__imp_shlwapi_ordinal428>
extern __imp_shlwapi_ordinal429:PANYARGS
shlwapi_ordinal429 TEXTEQU <__imp_shlwapi_ordinal429>
extern __imp_shlwapi_ordinal430:PANYARGS
shlwapi_ordinal430 TEXTEQU <__imp_shlwapi_ordinal430>
extern __imp_shlwapi_ordinal431:PANYARGS
shlwapi_ordinal431 TEXTEQU <__imp_shlwapi_ordinal431>
extern __imp_shlwapi_ordinal432:PANYARGS
shlwapi_ordinal432 TEXTEQU <__imp_shlwapi_ordinal432>
extern __imp_shlwapi_ordinal433:PANYARGS
shlwapi_ordinal433 TEXTEQU <__imp_shlwapi_ordinal433>
extern __imp_shlwapi_ordinal434:PANYARGS
shlwapi_ordinal434 TEXTEQU <__imp_shlwapi_ordinal434>
extern __imp_shlwapi_ordinal435:PANYARGS
shlwapi_ordinal435 TEXTEQU <__imp_shlwapi_ordinal435>
extern __imp_shlwapi_ordinal436:PANYARGS
shlwapi_ordinal436 TEXTEQU <__imp_shlwapi_ordinal436>
extern __imp_shlwapi_ordinal437:PANYARGS
shlwapi_ordinal437 TEXTEQU <__imp_shlwapi_ordinal437>
extern __imp_shlwapi_ordinal438:PANYARGS
shlwapi_ordinal438 TEXTEQU <__imp_shlwapi_ordinal438>
extern __imp_shlwapi_ordinal439:PANYARGS
shlwapi_ordinal439 TEXTEQU <__imp_shlwapi_ordinal439>
extern __imp_shlwapi_ordinal440:PANYARGS
shlwapi_ordinal440 TEXTEQU <__imp_shlwapi_ordinal440>
extern __imp_shlwapi_ordinal441:PANYARGS
shlwapi_ordinal441 TEXTEQU <__imp_shlwapi_ordinal441>
extern __imp_shlwapi_ordinal442:PANYARGS
shlwapi_ordinal442 TEXTEQU <__imp_shlwapi_ordinal442>
extern __imp_shlwapi_ordinal443:PANYARGS
shlwapi_ordinal443 TEXTEQU <__imp_shlwapi_ordinal443>
extern __imp_shlwapi_ordinal444:PANYARGS
shlwapi_ordinal444 TEXTEQU <__imp_shlwapi_ordinal444>
extern __imp_shlwapi_ordinal445:PANYARGS
shlwapi_ordinal445 TEXTEQU <__imp_shlwapi_ordinal445>
extern __imp_shlwapi_ordinal446:PANYARGS
shlwapi_ordinal446 TEXTEQU <__imp_shlwapi_ordinal446>
extern __imp_shlwapi_ordinal447:PANYARGS
shlwapi_ordinal447 TEXTEQU <__imp_shlwapi_ordinal447>
extern __imp_shlwapi_ordinal448:PANYARGS
shlwapi_ordinal448 TEXTEQU <__imp_shlwapi_ordinal448>
extern __imp_shlwapi_ordinal449:PANYARGS
shlwapi_ordinal449 TEXTEQU <__imp_shlwapi_ordinal449>
extern __imp_shlwapi_ordinal450:PANYARGS
shlwapi_ordinal450 TEXTEQU <__imp_shlwapi_ordinal450>
extern __imp_shlwapi_ordinal451:PANYARGS
shlwapi_ordinal451 TEXTEQU <__imp_shlwapi_ordinal451>
extern __imp_shlwapi_ordinal452:PANYARGS
shlwapi_ordinal452 TEXTEQU <__imp_shlwapi_ordinal452>
extern __imp_shlwapi_ordinal453:PANYARGS
shlwapi_ordinal453 TEXTEQU <__imp_shlwapi_ordinal453>
extern __imp_shlwapi_ordinal454:PANYARGS
shlwapi_ordinal454 TEXTEQU <__imp_shlwapi_ordinal454>
extern __imp_shlwapi_ordinal455:PANYARGS
shlwapi_ordinal455 TEXTEQU <__imp_shlwapi_ordinal455>
extern __imp_shlwapi_ordinal456:PANYARGS
shlwapi_ordinal456 TEXTEQU <__imp_shlwapi_ordinal456>
extern __imp_shlwapi_ordinal457:PANYARGS
shlwapi_ordinal457 TEXTEQU <__imp_shlwapi_ordinal457>
extern __imp_shlwapi_ordinal458:PANYARGS
shlwapi_ordinal458 TEXTEQU <__imp_shlwapi_ordinal458>
extern __imp_shlwapi_ordinal459:PANYARGS
shlwapi_ordinal459 TEXTEQU <__imp_shlwapi_ordinal459>
extern __imp_shlwapi_ordinal460:PANYARGS
shlwapi_ordinal460 TEXTEQU <__imp_shlwapi_ordinal460>
extern __imp_shlwapi_ordinal461:PANYARGS
shlwapi_ordinal461 TEXTEQU <__imp_shlwapi_ordinal461>
extern __imp_shlwapi_ordinal462:PANYARGS
shlwapi_ordinal462 TEXTEQU <__imp_shlwapi_ordinal462>
extern __imp_shlwapi_ordinal463:PANYARGS
shlwapi_ordinal463 TEXTEQU <__imp_shlwapi_ordinal463>
extern __imp_shlwapi_ordinal464:PANYARGS
shlwapi_ordinal464 TEXTEQU <__imp_shlwapi_ordinal464>
extern __imp_shlwapi_ordinal465:PANYARGS
shlwapi_ordinal465 TEXTEQU <__imp_shlwapi_ordinal465>
extern __imp_shlwapi_ordinal466:PANYARGS
shlwapi_ordinal466 TEXTEQU <__imp_shlwapi_ordinal466>
extern __imp_shlwapi_ordinal467:PANYARGS
shlwapi_ordinal467 TEXTEQU <__imp_shlwapi_ordinal467>
extern __imp_shlwapi_ordinal468:PANYARGS
shlwapi_ordinal468 TEXTEQU <__imp_shlwapi_ordinal468>
extern __imp_shlwapi_ordinal469:PANYARGS
shlwapi_ordinal469 TEXTEQU <__imp_shlwapi_ordinal469>
extern __imp_shlwapi_ordinal470:PANYARGS
shlwapi_ordinal470 TEXTEQU <__imp_shlwapi_ordinal470>
extern __imp_shlwapi_ordinal471:PANYARGS
shlwapi_ordinal471 TEXTEQU <__imp_shlwapi_ordinal471>
extern __imp_shlwapi_ordinal472:PANYARGS
shlwapi_ordinal472 TEXTEQU <__imp_shlwapi_ordinal472>
extern __imp_shlwapi_ordinal473:PANYARGS
shlwapi_ordinal473 TEXTEQU <__imp_shlwapi_ordinal473>
extern __imp_shlwapi_ordinal474:PANYARGS
shlwapi_ordinal474 TEXTEQU <__imp_shlwapi_ordinal474>
extern __imp_shlwapi_ordinal475:PANYARGS
shlwapi_ordinal475 TEXTEQU <__imp_shlwapi_ordinal475>
extern __imp_shlwapi_ordinal476:PANYARGS
shlwapi_ordinal476 TEXTEQU <__imp_shlwapi_ordinal476>
extern __imp_shlwapi_ordinal477:PANYARGS
shlwapi_ordinal477 TEXTEQU <__imp_shlwapi_ordinal477>
extern __imp_shlwapi_ordinal478:PANYARGS
shlwapi_ordinal478 TEXTEQU <__imp_shlwapi_ordinal478>
extern __imp_shlwapi_ordinal479:PANYARGS
shlwapi_ordinal479 TEXTEQU <__imp_shlwapi_ordinal479>
extern __imp_shlwapi_ordinal480:PANYARGS
shlwapi_ordinal480 TEXTEQU <__imp_shlwapi_ordinal480>
extern __imp_shlwapi_ordinal481:PANYARGS
shlwapi_ordinal481 TEXTEQU <__imp_shlwapi_ordinal481>
extern __imp_shlwapi_ordinal482:PANYARGS
shlwapi_ordinal482 TEXTEQU <__imp_shlwapi_ordinal482>
extern __imp_shlwapi_ordinal483:PANYARGS
shlwapi_ordinal483 TEXTEQU <__imp_shlwapi_ordinal483>
extern __imp_shlwapi_ordinal484:PANYARGS
shlwapi_ordinal484 TEXTEQU <__imp_shlwapi_ordinal484>
extern __imp_shlwapi_ordinal485:PANYARGS
shlwapi_ordinal485 TEXTEQU <__imp_shlwapi_ordinal485>
extern __imp_shlwapi_ordinal486:PANYARGS
shlwapi_ordinal486 TEXTEQU <__imp_shlwapi_ordinal486>
extern __imp_SHLoadIndirectString:PANYARGS
SHLoadIndirectString TEXTEQU <__imp_SHLoadIndirectString>
extern __imp_shlwapi_ordinal488:PANYARGS
shlwapi_ordinal488 TEXTEQU <__imp_shlwapi_ordinal488>
extern __imp_shlwapi_ordinal489:PANYARGS
shlwapi_ordinal489 TEXTEQU <__imp_shlwapi_ordinal489>
extern __imp_shlwapi_ordinal490:PANYARGS
shlwapi_ordinal490 TEXTEQU <__imp_shlwapi_ordinal490>
extern __imp_shlwapi_ordinal491:PANYARGS
shlwapi_ordinal491 TEXTEQU <__imp_shlwapi_ordinal491>
extern __imp_shlwapi_ordinal492:PANYARGS
shlwapi_ordinal492 TEXTEQU <__imp_shlwapi_ordinal492>
extern __imp_shlwapi_ordinal493:PANYARGS
shlwapi_ordinal493 TEXTEQU <__imp_shlwapi_ordinal493>
extern __imp_shlwapi_ordinal494:PANYARGS
shlwapi_ordinal494 TEXTEQU <__imp_shlwapi_ordinal494>
extern __imp_shlwapi_ordinal495:PANYARGS
shlwapi_ordinal495 TEXTEQU <__imp_shlwapi_ordinal495>
extern __imp_shlwapi_ordinal496:PANYARGS
shlwapi_ordinal496 TEXTEQU <__imp_shlwapi_ordinal496>
extern __imp_shlwapi_ordinal497:PANYARGS
shlwapi_ordinal497 TEXTEQU <__imp_shlwapi_ordinal497>
extern __imp_shlwapi_ordinal498:PANYARGS
shlwapi_ordinal498 TEXTEQU <__imp_shlwapi_ordinal498>
extern __imp_shlwapi_ordinal499:PANYARGS
shlwapi_ordinal499 TEXTEQU <__imp_shlwapi_ordinal499>
extern __imp_shlwapi_ordinal500:PANYARGS
shlwapi_ordinal500 TEXTEQU <__imp_shlwapi_ordinal500>
extern __imp_shlwapi_ordinal501:PANYARGS
shlwapi_ordinal501 TEXTEQU <__imp_shlwapi_ordinal501>
extern __imp_shlwapi_ordinal502:PANYARGS
shlwapi_ordinal502 TEXTEQU <__imp_shlwapi_ordinal502>
extern __imp_shlwapi_ordinal503:PANYARGS
shlwapi_ordinal503 TEXTEQU <__imp_shlwapi_ordinal503>
extern __imp_shlwapi_ordinal504:PANYARGS
shlwapi_ordinal504 TEXTEQU <__imp_shlwapi_ordinal504>
extern __imp_shlwapi_ordinal505:PANYARGS
shlwapi_ordinal505 TEXTEQU <__imp_shlwapi_ordinal505>
extern __imp_shlwapi_ordinal506:PANYARGS
shlwapi_ordinal506 TEXTEQU <__imp_shlwapi_ordinal506>
extern __imp_shlwapi_ordinal507:PANYARGS
shlwapi_ordinal507 TEXTEQU <__imp_shlwapi_ordinal507>
extern __imp_shlwapi_ordinal508:PANYARGS
shlwapi_ordinal508 TEXTEQU <__imp_shlwapi_ordinal508>
extern __imp_shlwapi_ordinal509:PANYARGS
shlwapi_ordinal509 TEXTEQU <__imp_shlwapi_ordinal509>
extern __imp_shlwapi_ordinal510:PANYARGS
shlwapi_ordinal510 TEXTEQU <__imp_shlwapi_ordinal510>
extern __imp_shlwapi_ordinal511:PANYARGS
shlwapi_ordinal511 TEXTEQU <__imp_shlwapi_ordinal511>
extern __imp_shlwapi_ordinal512:PANYARGS
shlwapi_ordinal512 TEXTEQU <__imp_shlwapi_ordinal512>
extern __imp_shlwapi_ordinal513:PANYARGS
shlwapi_ordinal513 TEXTEQU <__imp_shlwapi_ordinal513>
extern __imp_shlwapi_ordinal514:PANYARGS
shlwapi_ordinal514 TEXTEQU <__imp_shlwapi_ordinal514>
extern __imp_SHGetViewStatePropertyBag:PANYARGS
SHGetViewStatePropertyBag TEXTEQU <__imp_SHGetViewStatePropertyBag>
extern __imp_shlwapi_ordinal516:PANYARGS
shlwapi_ordinal516 TEXTEQU <__imp_shlwapi_ordinal516>
extern __imp_shlwapi_ordinal517:PANYARGS
shlwapi_ordinal517 TEXTEQU <__imp_shlwapi_ordinal517>
extern __imp_shlwapi_ordinal518:PANYARGS
shlwapi_ordinal518 TEXTEQU <__imp_shlwapi_ordinal518>
extern __imp_shlwapi_ordinal519:PANYARGS
shlwapi_ordinal519 TEXTEQU <__imp_shlwapi_ordinal519>
extern __imp_shlwapi_ordinal520:PANYARGS
shlwapi_ordinal520 TEXTEQU <__imp_shlwapi_ordinal520>
extern __imp_shlwapi_ordinal521:PANYARGS
shlwapi_ordinal521 TEXTEQU <__imp_shlwapi_ordinal521>
extern __imp_shlwapi_ordinal522:PANYARGS
shlwapi_ordinal522 TEXTEQU <__imp_shlwapi_ordinal522>
extern __imp_shlwapi_ordinal523:PANYARGS
shlwapi_ordinal523 TEXTEQU <__imp_shlwapi_ordinal523>
extern __imp_shlwapi_ordinal524:PANYARGS
shlwapi_ordinal524 TEXTEQU <__imp_shlwapi_ordinal524>
extern __imp_shlwapi_ordinal525:PANYARGS
shlwapi_ordinal525 TEXTEQU <__imp_shlwapi_ordinal525>
extern __imp_shlwapi_ordinal526:PANYARGS
shlwapi_ordinal526 TEXTEQU <__imp_shlwapi_ordinal526>
extern __imp_shlwapi_ordinal527:PANYARGS
shlwapi_ordinal527 TEXTEQU <__imp_shlwapi_ordinal527>
extern __imp_shlwapi_ordinal528:PANYARGS
shlwapi_ordinal528 TEXTEQU <__imp_shlwapi_ordinal528>
extern __imp_shlwapi_ordinal529:PANYARGS
shlwapi_ordinal529 TEXTEQU <__imp_shlwapi_ordinal529>
extern __imp_shlwapi_ordinal530:PANYARGS
shlwapi_ordinal530 TEXTEQU <__imp_shlwapi_ordinal530>
extern __imp_shlwapi_ordinal531:PANYARGS
shlwapi_ordinal531 TEXTEQU <__imp_shlwapi_ordinal531>
extern __imp_shlwapi_ordinal532:PANYARGS
shlwapi_ordinal532 TEXTEQU <__imp_shlwapi_ordinal532>
extern __imp_shlwapi_ordinal533:PANYARGS
shlwapi_ordinal533 TEXTEQU <__imp_shlwapi_ordinal533>
extern __imp_shlwapi_ordinal534:PANYARGS
shlwapi_ordinal534 TEXTEQU <__imp_shlwapi_ordinal534>
extern __imp_shlwapi_ordinal535:PANYARGS
shlwapi_ordinal535 TEXTEQU <__imp_shlwapi_ordinal535>
extern __imp_shlwapi_ordinal536:PANYARGS
shlwapi_ordinal536 TEXTEQU <__imp_shlwapi_ordinal536>
extern __imp_shlwapi_ordinal537:PANYARGS
shlwapi_ordinal537 TEXTEQU <__imp_shlwapi_ordinal537>
extern __imp_shlwapi_ordinal538:PANYARGS
shlwapi_ordinal538 TEXTEQU <__imp_shlwapi_ordinal538>
extern __imp_shlwapi_ordinal539:PANYARGS
shlwapi_ordinal539 TEXTEQU <__imp_shlwapi_ordinal539>
extern __imp_shlwapi_ordinal540:PANYARGS
shlwapi_ordinal540 TEXTEQU <__imp_shlwapi_ordinal540>
extern __imp_shlwapi_ordinal541:PANYARGS
shlwapi_ordinal541 TEXTEQU <__imp_shlwapi_ordinal541>
extern __imp_shlwapi_ordinal542:PANYARGS
shlwapi_ordinal542 TEXTEQU <__imp_shlwapi_ordinal542>
extern __imp_shlwapi_ordinal543:PANYARGS
shlwapi_ordinal543 TEXTEQU <__imp_shlwapi_ordinal543>
extern __imp_shlwapi_ordinal544:PANYARGS
shlwapi_ordinal544 TEXTEQU <__imp_shlwapi_ordinal544>
extern __imp_shlwapi_ordinal545:PANYARGS
shlwapi_ordinal545 TEXTEQU <__imp_shlwapi_ordinal545>
extern __imp_shlwapi_ordinal546:PANYARGS
shlwapi_ordinal546 TEXTEQU <__imp_shlwapi_ordinal546>
extern __imp_DelayLoadFailureHook:PANYARGS
DelayLoadFailureHook TEXTEQU <__imp_DelayLoadFailureHook>
extern __imp_shlwapi_ordinal548:PANYARGS
shlwapi_ordinal548 TEXTEQU <__imp_shlwapi_ordinal548>
extern __imp_shlwapi_ordinal549:PANYARGS
shlwapi_ordinal549 TEXTEQU <__imp_shlwapi_ordinal549>
extern __imp_shlwapi_ordinal550:PANYARGS
shlwapi_ordinal550 TEXTEQU <__imp_shlwapi_ordinal550>
extern __imp_shlwapi_ordinal551:PANYARGS
shlwapi_ordinal551 TEXTEQU <__imp_shlwapi_ordinal551>
extern __imp_shlwapi_ordinal552:PANYARGS
shlwapi_ordinal552 TEXTEQU <__imp_shlwapi_ordinal552>
extern __imp_IsInternetESCEnabled:PANYARGS
IsInternetESCEnabled TEXTEQU <__imp_IsInternetESCEnabled>
extern __imp_shlwapi_ordinal554:PANYARGS
shlwapi_ordinal554 TEXTEQU <__imp_shlwapi_ordinal554>
extern __imp_AssocGetPerceivedType:PANYARGS
AssocGetPerceivedType TEXTEQU <__imp_AssocGetPerceivedType>
extern __imp_shlwapi_ordinal556:PANYARGS
shlwapi_ordinal556 TEXTEQU <__imp_shlwapi_ordinal556>
extern __imp_shlwapi_ordinal557:PANYARGS
shlwapi_ordinal557 TEXTEQU <__imp_shlwapi_ordinal557>
extern __imp_shlwapi_ordinal558:PANYARGS
shlwapi_ordinal558 TEXTEQU <__imp_shlwapi_ordinal558>
extern __imp_shlwapi_ordinal559:PANYARGS
shlwapi_ordinal559 TEXTEQU <__imp_shlwapi_ordinal559>
extern __imp_shlwapi_ordinal560:PANYARGS
shlwapi_ordinal560 TEXTEQU <__imp_shlwapi_ordinal560>
extern __imp_shlwapi_ordinal561:PANYARGS
shlwapi_ordinal561 TEXTEQU <__imp_shlwapi_ordinal561>
extern __imp_shlwapi_ordinal562:PANYARGS
shlwapi_ordinal562 TEXTEQU <__imp_shlwapi_ordinal562>
extern __imp_shlwapi_ordinal563:PANYARGS
shlwapi_ordinal563 TEXTEQU <__imp_shlwapi_ordinal563>
extern __imp_shlwapi_ordinal564:PANYARGS
shlwapi_ordinal564 TEXTEQU <__imp_shlwapi_ordinal564>
extern __imp_shlwapi_ordinal565:PANYARGS
shlwapi_ordinal565 TEXTEQU <__imp_shlwapi_ordinal565>
extern __imp_shlwapi_ordinal566:PANYARGS
shlwapi_ordinal566 TEXTEQU <__imp_shlwapi_ordinal566>
extern __imp_AssocIsDangerous:PANYARGS
AssocIsDangerous TEXTEQU <__imp_AssocIsDangerous>
extern __imp_AssocQueryKeyA:PANYARGS
AssocQueryKey  TEXTEQU <__imp_AssocQueryKeyA>
extern __imp_AssocQueryKeyW:PANYARGS
AssocQueryKeyW TEXTEQU <__imp_AssocQueryKeyW>
extern __imp_AssocQueryStringA:PANYARGS
AssocQueryString  TEXTEQU <__imp_AssocQueryStringA>
extern __imp_AssocQueryStringByKeyA:PANYARGS
AssocQueryStringByKey  TEXTEQU <__imp_AssocQueryStringByKeyA>
extern __imp_AssocQueryStringByKeyW:PANYARGS
AssocQueryStringByKeyW TEXTEQU <__imp_AssocQueryStringByKeyW>
extern __imp_AssocQueryStringW:PANYARGS
AssocQueryStringW TEXTEQU <__imp_AssocQueryStringW>
extern __imp_ChrCmpIA:PANYARGS
ChrCmpI  TEXTEQU <__imp_ChrCmpIA>
extern __imp_ChrCmpIW:PANYARGS
ChrCmpIW TEXTEQU <__imp_ChrCmpIW>
extern __imp_ColorAdjustLuma:PANYARGS
ColorAdjustLuma TEXTEQU <__imp_ColorAdjustLuma>
extern __imp_ColorHLSToRGB:PANYARGS
ColorHLSToRGB TEXTEQU <__imp_ColorHLSToRGB>
extern __imp_ColorRGBToHLS:PANYARGS
ColorRGBToHLS TEXTEQU <__imp_ColorRGBToHLS>
extern __imp_DllGetVersion:PANYARGS
DllGetVersion TEXTEQU <__imp_DllGetVersion>
extern __imp_GetMenuPosFromID:PANYARGS
GetMenuPosFromID TEXTEQU <__imp_GetMenuPosFromID>
extern __imp_HashData:PANYARGS
HashData TEXTEQU <__imp_HashData>
extern __imp_IntlStrEqWorkerA:PANYARGS
IntlStrEqWorker  TEXTEQU <__imp_IntlStrEqWorkerA>
extern __imp_IntlStrEqWorkerW:PANYARGS
IntlStrEqWorkerW TEXTEQU <__imp_IntlStrEqWorkerW>
extern __imp_IsCharSpaceA:PANYARGS
IsCharSpace  TEXTEQU <__imp_IsCharSpaceA>
extern __imp_PathAddBackslashA:PANYARGS
PathAddBackslash  TEXTEQU <__imp_PathAddBackslashA>
extern __imp_PathAddBackslashW:PANYARGS
PathAddBackslashW TEXTEQU <__imp_PathAddBackslashW>
extern __imp_PathAddExtensionA:PANYARGS
PathAddExtension  TEXTEQU <__imp_PathAddExtensionA>
extern __imp_PathAddExtensionW:PANYARGS
PathAddExtensionW TEXTEQU <__imp_PathAddExtensionW>
extern __imp_PathAppendA:PANYARGS
PathAppend  TEXTEQU <__imp_PathAppendA>
extern __imp_PathAppendW:PANYARGS
PathAppendW TEXTEQU <__imp_PathAppendW>
extern __imp_PathBuildRootA:PANYARGS
PathBuildRoot  TEXTEQU <__imp_PathBuildRootA>
extern __imp_PathBuildRootW:PANYARGS
PathBuildRootW TEXTEQU <__imp_PathBuildRootW>
extern __imp_PathCanonicalizeA:PANYARGS
PathCanonicalize  TEXTEQU <__imp_PathCanonicalizeA>
extern __imp_PathCanonicalizeW:PANYARGS
PathCanonicalizeW TEXTEQU <__imp_PathCanonicalizeW>
extern __imp_PathCombineA:PANYARGS
PathCombine  TEXTEQU <__imp_PathCombineA>
extern __imp_PathCombineW:PANYARGS
PathCombineW TEXTEQU <__imp_PathCombineW>
extern __imp_PathCommonPrefixA:PANYARGS
PathCommonPrefix  TEXTEQU <__imp_PathCommonPrefixA>
extern __imp_PathCommonPrefixW:PANYARGS
PathCommonPrefixW TEXTEQU <__imp_PathCommonPrefixW>
extern __imp_PathCompactPathA:PANYARGS
PathCompactPath  TEXTEQU <__imp_PathCompactPathA>
extern __imp_PathCompactPathExA:PANYARGS
PathCompactPathEx  TEXTEQU <__imp_PathCompactPathExA>
extern __imp_PathCompactPathExW:PANYARGS
PathCompactPathExW TEXTEQU <__imp_PathCompactPathExW>
extern __imp_PathCompactPathW:PANYARGS
PathCompactPathW TEXTEQU <__imp_PathCompactPathW>
extern __imp_PathCreateFromUrlA:PANYARGS
PathCreateFromUrl  TEXTEQU <__imp_PathCreateFromUrlA>
extern __imp_PathCreateFromUrlW:PANYARGS
PathCreateFromUrlW TEXTEQU <__imp_PathCreateFromUrlW>
extern __imp_PathFileExistsA:PANYARGS
PathFileExists  TEXTEQU <__imp_PathFileExistsA>
extern __imp_PathFileExistsW:PANYARGS
PathFileExistsW TEXTEQU <__imp_PathFileExistsW>
extern __imp_PathFindExtensionA:PANYARGS
PathFindExtension  TEXTEQU <__imp_PathFindExtensionA>
extern __imp_PathFindExtensionW:PANYARGS
PathFindExtensionW TEXTEQU <__imp_PathFindExtensionW>
extern __imp_PathFindFileNameA:PANYARGS
PathFindFileName  TEXTEQU <__imp_PathFindFileNameA>
extern __imp_PathFindFileNameW:PANYARGS
PathFindFileNameW TEXTEQU <__imp_PathFindFileNameW>
extern __imp_PathFindNextComponentA:PANYARGS
PathFindNextComponent  TEXTEQU <__imp_PathFindNextComponentA>
extern __imp_PathFindNextComponentW:PANYARGS
PathFindNextComponentW TEXTEQU <__imp_PathFindNextComponentW>
extern __imp_PathFindOnPathA:PANYARGS
PathFindOnPath  TEXTEQU <__imp_PathFindOnPathA>
extern __imp_PathFindOnPathW:PANYARGS
PathFindOnPathW TEXTEQU <__imp_PathFindOnPathW>
extern __imp_PathFindSuffixArrayA:PANYARGS
PathFindSuffixArray  TEXTEQU <__imp_PathFindSuffixArrayA>
extern __imp_PathFindSuffixArrayW:PANYARGS
PathFindSuffixArrayW TEXTEQU <__imp_PathFindSuffixArrayW>
extern __imp_PathGetArgsA:PANYARGS
PathGetArgs  TEXTEQU <__imp_PathGetArgsA>
extern __imp_PathGetArgsW:PANYARGS
PathGetArgsW TEXTEQU <__imp_PathGetArgsW>
extern __imp_PathGetCharTypeA:PANYARGS
PathGetCharType  TEXTEQU <__imp_PathGetCharTypeA>
extern __imp_PathGetCharTypeW:PANYARGS
PathGetCharTypeW TEXTEQU <__imp_PathGetCharTypeW>
extern __imp_PathGetDriveNumberA:PANYARGS
PathGetDriveNumber  TEXTEQU <__imp_PathGetDriveNumberA>
extern __imp_PathGetDriveNumberW:PANYARGS
PathGetDriveNumberW TEXTEQU <__imp_PathGetDriveNumberW>
extern __imp_PathIsContentTypeA:PANYARGS
PathIsContentType  TEXTEQU <__imp_PathIsContentTypeA>
extern __imp_PathIsContentTypeW:PANYARGS
PathIsContentTypeW TEXTEQU <__imp_PathIsContentTypeW>
extern __imp_PathIsDirectoryA:PANYARGS
PathIsDirectory  TEXTEQU <__imp_PathIsDirectoryA>
extern __imp_PathIsDirectoryEmptyA:PANYARGS
PathIsDirectoryEmpty  TEXTEQU <__imp_PathIsDirectoryEmptyA>
extern __imp_PathIsDirectoryEmptyW:PANYARGS
PathIsDirectoryEmptyW TEXTEQU <__imp_PathIsDirectoryEmptyW>
extern __imp_PathIsDirectoryW:PANYARGS
PathIsDirectoryW TEXTEQU <__imp_PathIsDirectoryW>
extern __imp_PathIsFileSpecA:PANYARGS
PathIsFileSpec  TEXTEQU <__imp_PathIsFileSpecA>
extern __imp_PathIsFileSpecW:PANYARGS
PathIsFileSpecW TEXTEQU <__imp_PathIsFileSpecW>
extern __imp_PathIsLFNFileSpecA:PANYARGS
PathIsLFNFileSpec  TEXTEQU <__imp_PathIsLFNFileSpecA>
extern __imp_PathIsLFNFileSpecW:PANYARGS
PathIsLFNFileSpecW TEXTEQU <__imp_PathIsLFNFileSpecW>
extern __imp_PathIsNetworkPathA:PANYARGS
PathIsNetworkPath  TEXTEQU <__imp_PathIsNetworkPathA>
extern __imp_PathIsNetworkPathW:PANYARGS
PathIsNetworkPathW TEXTEQU <__imp_PathIsNetworkPathW>
extern __imp_PathIsPrefixA:PANYARGS
PathIsPrefix  TEXTEQU <__imp_PathIsPrefixA>
extern __imp_PathIsPrefixW:PANYARGS
PathIsPrefixW TEXTEQU <__imp_PathIsPrefixW>
extern __imp_PathIsRelativeA:PANYARGS
PathIsRelative  TEXTEQU <__imp_PathIsRelativeA>
extern __imp_PathIsRelativeW:PANYARGS
PathIsRelativeW TEXTEQU <__imp_PathIsRelativeW>
extern __imp_PathIsRootA:PANYARGS
PathIsRoot  TEXTEQU <__imp_PathIsRootA>
extern __imp_PathIsRootW:PANYARGS
PathIsRootW TEXTEQU <__imp_PathIsRootW>
extern __imp_PathIsSameRootA:PANYARGS
PathIsSameRoot  TEXTEQU <__imp_PathIsSameRootA>
extern __imp_PathIsSameRootW:PANYARGS
PathIsSameRootW TEXTEQU <__imp_PathIsSameRootW>
extern __imp_PathIsSystemFolderA:PANYARGS
PathIsSystemFolder  TEXTEQU <__imp_PathIsSystemFolderA>
extern __imp_PathIsSystemFolderW:PANYARGS
PathIsSystemFolderW TEXTEQU <__imp_PathIsSystemFolderW>
extern __imp_PathIsUNCA:PANYARGS
PathIsUNC  TEXTEQU <__imp_PathIsUNCA>
extern __imp_PathIsUNCServerA:PANYARGS
PathIsUNCServer  TEXTEQU <__imp_PathIsUNCServerA>
extern __imp_PathIsUNCServerShareA:PANYARGS
PathIsUNCServerShare  TEXTEQU <__imp_PathIsUNCServerShareA>
extern __imp_PathIsUNCServerShareW:PANYARGS
PathIsUNCServerShareW TEXTEQU <__imp_PathIsUNCServerShareW>
extern __imp_PathIsUNCServerW:PANYARGS
PathIsUNCServerW TEXTEQU <__imp_PathIsUNCServerW>
extern __imp_PathIsUNCW:PANYARGS
PathIsUNCW TEXTEQU <__imp_PathIsUNCW>
extern __imp_PathIsURLA:PANYARGS
PathIsURL  TEXTEQU <__imp_PathIsURLA>
extern __imp_PathIsURLW:PANYARGS
PathIsURLW TEXTEQU <__imp_PathIsURLW>
extern __imp_PathMakePrettyA:PANYARGS
PathMakePretty  TEXTEQU <__imp_PathMakePrettyA>
extern __imp_PathMakePrettyW:PANYARGS
PathMakePrettyW TEXTEQU <__imp_PathMakePrettyW>
extern __imp_PathMakeSystemFolderA:PANYARGS
PathMakeSystemFolder  TEXTEQU <__imp_PathMakeSystemFolderA>
extern __imp_PathMakeSystemFolderW:PANYARGS
PathMakeSystemFolderW TEXTEQU <__imp_PathMakeSystemFolderW>
extern __imp_PathMatchSpecA:PANYARGS
PathMatchSpec  TEXTEQU <__imp_PathMatchSpecA>
extern __imp_PathMatchSpecW:PANYARGS
PathMatchSpecW TEXTEQU <__imp_PathMatchSpecW>
extern __imp_PathParseIconLocationA:PANYARGS
PathParseIconLocation  TEXTEQU <__imp_PathParseIconLocationA>
extern __imp_PathParseIconLocationW:PANYARGS
PathParseIconLocationW TEXTEQU <__imp_PathParseIconLocationW>
extern __imp_PathQuoteSpacesA:PANYARGS
PathQuoteSpaces  TEXTEQU <__imp_PathQuoteSpacesA>
extern __imp_PathQuoteSpacesW:PANYARGS
PathQuoteSpacesW TEXTEQU <__imp_PathQuoteSpacesW>
extern __imp_PathRelativePathToA:PANYARGS
PathRelativePathTo  TEXTEQU <__imp_PathRelativePathToA>
extern __imp_PathRelativePathToW:PANYARGS
PathRelativePathToW TEXTEQU <__imp_PathRelativePathToW>
extern __imp_PathRemoveArgsA:PANYARGS
PathRemoveArgs  TEXTEQU <__imp_PathRemoveArgsA>
extern __imp_PathRemoveArgsW:PANYARGS
PathRemoveArgsW TEXTEQU <__imp_PathRemoveArgsW>
extern __imp_PathRemoveBackslashA:PANYARGS
PathRemoveBackslash  TEXTEQU <__imp_PathRemoveBackslashA>
extern __imp_PathRemoveBackslashW:PANYARGS
PathRemoveBackslashW TEXTEQU <__imp_PathRemoveBackslashW>
extern __imp_PathRemoveBlanksA:PANYARGS
PathRemoveBlanks  TEXTEQU <__imp_PathRemoveBlanksA>
extern __imp_PathRemoveBlanksW:PANYARGS
PathRemoveBlanksW TEXTEQU <__imp_PathRemoveBlanksW>
extern __imp_PathRemoveExtensionA:PANYARGS
PathRemoveExtension  TEXTEQU <__imp_PathRemoveExtensionA>
extern __imp_PathRemoveExtensionW:PANYARGS
PathRemoveExtensionW TEXTEQU <__imp_PathRemoveExtensionW>
extern __imp_PathRemoveFileSpecA:PANYARGS
PathRemoveFileSpec  TEXTEQU <__imp_PathRemoveFileSpecA>
extern __imp_PathRemoveFileSpecW:PANYARGS
PathRemoveFileSpecW TEXTEQU <__imp_PathRemoveFileSpecW>
extern __imp_PathRenameExtensionA:PANYARGS
PathRenameExtension  TEXTEQU <__imp_PathRenameExtensionA>
extern __imp_PathRenameExtensionW:PANYARGS
PathRenameExtensionW TEXTEQU <__imp_PathRenameExtensionW>
extern __imp_PathSearchAndQualifyA:PANYARGS
PathSearchAndQualify  TEXTEQU <__imp_PathSearchAndQualifyA>
extern __imp_PathSearchAndQualifyW:PANYARGS
PathSearchAndQualifyW TEXTEQU <__imp_PathSearchAndQualifyW>
extern __imp_PathSetDlgItemPathA:PANYARGS
PathSetDlgItemPath  TEXTEQU <__imp_PathSetDlgItemPathA>
extern __imp_PathSetDlgItemPathW:PANYARGS
PathSetDlgItemPathW TEXTEQU <__imp_PathSetDlgItemPathW>
extern __imp_PathSkipRootA:PANYARGS
PathSkipRoot  TEXTEQU <__imp_PathSkipRootA>
extern __imp_PathSkipRootW:PANYARGS
PathSkipRootW TEXTEQU <__imp_PathSkipRootW>
extern __imp_PathStripPathA:PANYARGS
PathStripPath  TEXTEQU <__imp_PathStripPathA>
extern __imp_PathStripPathW:PANYARGS
PathStripPathW TEXTEQU <__imp_PathStripPathW>
extern __imp_PathStripToRootA:PANYARGS
PathStripToRoot  TEXTEQU <__imp_PathStripToRootA>
extern __imp_PathStripToRootW:PANYARGS
PathStripToRootW TEXTEQU <__imp_PathStripToRootW>
extern __imp_PathUnExpandEnvStringsA:PANYARGS
PathUnExpandEnvStrings  TEXTEQU <__imp_PathUnExpandEnvStringsA>
extern __imp_PathUnExpandEnvStringsW:PANYARGS
PathUnExpandEnvStringsW TEXTEQU <__imp_PathUnExpandEnvStringsW>
extern __imp_PathUndecorateA:PANYARGS
PathUndecorate  TEXTEQU <__imp_PathUndecorateA>
extern __imp_PathUndecorateW:PANYARGS
PathUndecorateW TEXTEQU <__imp_PathUndecorateW>
extern __imp_PathUnmakeSystemFolderA:PANYARGS
PathUnmakeSystemFolder  TEXTEQU <__imp_PathUnmakeSystemFolderA>
extern __imp_PathUnmakeSystemFolderW:PANYARGS
PathUnmakeSystemFolderW TEXTEQU <__imp_PathUnmakeSystemFolderW>
extern __imp_PathUnquoteSpacesA:PANYARGS
PathUnquoteSpaces  TEXTEQU <__imp_PathUnquoteSpacesA>
extern __imp_PathUnquoteSpacesW:PANYARGS
PathUnquoteSpacesW TEXTEQU <__imp_PathUnquoteSpacesW>
extern __imp_SHAutoComplete:PANYARGS
SHAutoComplete TEXTEQU <__imp_SHAutoComplete>
extern __imp_SHCopyKeyA:PANYARGS
SHCopyKey  TEXTEQU <__imp_SHCopyKeyA>
extern __imp_SHCopyKeyW:PANYARGS
SHCopyKeyW TEXTEQU <__imp_SHCopyKeyW>
extern __imp_SHCreateShellPalette:PANYARGS
SHCreateShellPalette TEXTEQU <__imp_SHCreateShellPalette>
extern __imp_SHCreateStreamOnFileA:PANYARGS
SHCreateStreamOnFile  TEXTEQU <__imp_SHCreateStreamOnFileA>
extern __imp_SHCreateStreamOnFileEx:PANYARGS
SHCreateStreamOnFileEx TEXTEQU <__imp_SHCreateStreamOnFileEx>
extern __imp_SHCreateStreamOnFileW:PANYARGS
SHCreateStreamOnFileW TEXTEQU <__imp_SHCreateStreamOnFileW>
extern __imp_SHCreateStreamWrapper:PANYARGS
SHCreateStreamWrapper TEXTEQU <__imp_SHCreateStreamWrapper>
extern __imp_SHCreateThreadRef:PANYARGS
SHCreateThreadRef TEXTEQU <__imp_SHCreateThreadRef>
extern __imp_SHDeleteEmptyKeyA:PANYARGS
SHDeleteEmptyKey  TEXTEQU <__imp_SHDeleteEmptyKeyA>
extern __imp_SHDeleteEmptyKeyW:PANYARGS
SHDeleteEmptyKeyW TEXTEQU <__imp_SHDeleteEmptyKeyW>
extern __imp_SHDeleteKeyA:PANYARGS
SHDeleteKey  TEXTEQU <__imp_SHDeleteKeyA>
extern __imp_SHDeleteKeyW:PANYARGS
SHDeleteKeyW TEXTEQU <__imp_SHDeleteKeyW>
extern __imp_SHDeleteOrphanKeyA:PANYARGS
SHDeleteOrphanKey  TEXTEQU <__imp_SHDeleteOrphanKeyA>
extern __imp_SHDeleteOrphanKeyW:PANYARGS
SHDeleteOrphanKeyW TEXTEQU <__imp_SHDeleteOrphanKeyW>
extern __imp_SHDeleteValueA:PANYARGS
SHDeleteValue  TEXTEQU <__imp_SHDeleteValueA>
extern __imp_SHDeleteValueW:PANYARGS
SHDeleteValueW TEXTEQU <__imp_SHDeleteValueW>
extern __imp_SHEnumKeyExA:PANYARGS
SHEnumKeyEx  TEXTEQU <__imp_SHEnumKeyExA>
extern __imp_SHEnumKeyExW:PANYARGS
SHEnumKeyExW TEXTEQU <__imp_SHEnumKeyExW>
extern __imp_SHEnumValueA:PANYARGS
SHEnumValue  TEXTEQU <__imp_SHEnumValueA>
extern __imp_SHEnumValueW:PANYARGS
SHEnumValueW TEXTEQU <__imp_SHEnumValueW>
extern __imp_SHGetInverseCMAP:PANYARGS
SHGetInverseCMAP TEXTEQU <__imp_SHGetInverseCMAP>
extern __imp_SHGetThreadRef:PANYARGS
SHGetThreadRef TEXTEQU <__imp_SHGetThreadRef>
extern __imp_SHGetValueA:PANYARGS
SHGetValue  TEXTEQU <__imp_SHGetValueA>
extern __imp_SHGetValueW:PANYARGS
SHGetValueW TEXTEQU <__imp_SHGetValueW>
extern __imp_SHIsLowMemoryMachine:PANYARGS
SHIsLowMemoryMachine TEXTEQU <__imp_SHIsLowMemoryMachine>
extern __imp_SHOpenRegStream2A:PANYARGS
SHOpenRegStream2  TEXTEQU <__imp_SHOpenRegStream2A>
extern __imp_SHOpenRegStream2W:PANYARGS
SHOpenRegStream2W TEXTEQU <__imp_SHOpenRegStream2W>
extern __imp_SHOpenRegStreamA:PANYARGS
SHOpenRegStream  TEXTEQU <__imp_SHOpenRegStreamA>
extern __imp_SHOpenRegStreamW:PANYARGS
SHOpenRegStreamW TEXTEQU <__imp_SHOpenRegStreamW>
extern __imp_SHQueryInfoKeyA:PANYARGS
SHQueryInfoKey  TEXTEQU <__imp_SHQueryInfoKeyA>
extern __imp_SHQueryInfoKeyW:PANYARGS
SHQueryInfoKeyW TEXTEQU <__imp_SHQueryInfoKeyW>
extern __imp_SHQueryValueExA:PANYARGS
SHQueryValueEx  TEXTEQU <__imp_SHQueryValueExA>
extern __imp_SHQueryValueExW:PANYARGS
SHQueryValueExW TEXTEQU <__imp_SHQueryValueExW>
extern __imp_SHRegCloseUSKey:PANYARGS
SHRegCloseUSKey TEXTEQU <__imp_SHRegCloseUSKey>
extern __imp_SHRegCreateUSKeyA:PANYARGS
SHRegCreateUSKey  TEXTEQU <__imp_SHRegCreateUSKeyA>
extern __imp_SHRegCreateUSKeyW:PANYARGS
SHRegCreateUSKeyW TEXTEQU <__imp_SHRegCreateUSKeyW>
extern __imp_SHRegDeleteEmptyUSKeyA:PANYARGS
SHRegDeleteEmptyUSKey  TEXTEQU <__imp_SHRegDeleteEmptyUSKeyA>
extern __imp_SHRegDeleteEmptyUSKeyW:PANYARGS
SHRegDeleteEmptyUSKeyW TEXTEQU <__imp_SHRegDeleteEmptyUSKeyW>
extern __imp_SHRegDeleteUSValueA:PANYARGS
SHRegDeleteUSValue  TEXTEQU <__imp_SHRegDeleteUSValueA>
extern __imp_SHRegDeleteUSValueW:PANYARGS
SHRegDeleteUSValueW TEXTEQU <__imp_SHRegDeleteUSValueW>
extern __imp_SHRegDuplicateHKey:PANYARGS
SHRegDuplicateHKey TEXTEQU <__imp_SHRegDuplicateHKey>
extern __imp_SHRegEnumUSKeyA:PANYARGS
SHRegEnumUSKey  TEXTEQU <__imp_SHRegEnumUSKeyA>
extern __imp_SHRegEnumUSKeyW:PANYARGS
SHRegEnumUSKeyW TEXTEQU <__imp_SHRegEnumUSKeyW>
extern __imp_SHRegEnumUSValueA:PANYARGS
SHRegEnumUSValue  TEXTEQU <__imp_SHRegEnumUSValueA>
extern __imp_SHRegEnumUSValueW:PANYARGS
SHRegEnumUSValueW TEXTEQU <__imp_SHRegEnumUSValueW>
extern __imp_SHRegGetBoolUSValueA:PANYARGS
SHRegGetBoolUSValue  TEXTEQU <__imp_SHRegGetBoolUSValueA>
extern __imp_SHRegGetBoolUSValueW:PANYARGS
SHRegGetBoolUSValueW TEXTEQU <__imp_SHRegGetBoolUSValueW>
extern __imp_SHRegGetPathA:PANYARGS
SHRegGetPath  TEXTEQU <__imp_SHRegGetPathA>
extern __imp_SHRegGetPathW:PANYARGS
SHRegGetPathW TEXTEQU <__imp_SHRegGetPathW>
extern __imp_SHRegGetUSValueA:PANYARGS
SHRegGetUSValue  TEXTEQU <__imp_SHRegGetUSValueA>
extern __imp_SHRegGetUSValueW:PANYARGS
SHRegGetUSValueW TEXTEQU <__imp_SHRegGetUSValueW>
extern __imp_SHRegGetValueA:PANYARGS
SHRegGetValue  TEXTEQU <__imp_SHRegGetValueA>
extern __imp_SHRegGetValueW:PANYARGS
SHRegGetValueW TEXTEQU <__imp_SHRegGetValueW>
extern __imp_SHRegOpenUSKeyA:PANYARGS
SHRegOpenUSKey  TEXTEQU <__imp_SHRegOpenUSKeyA>
extern __imp_SHRegOpenUSKeyW:PANYARGS
SHRegOpenUSKeyW TEXTEQU <__imp_SHRegOpenUSKeyW>
extern __imp_SHRegQueryInfoUSKeyA:PANYARGS
SHRegQueryInfoUSKey  TEXTEQU <__imp_SHRegQueryInfoUSKeyA>
extern __imp_SHRegQueryInfoUSKeyW:PANYARGS
SHRegQueryInfoUSKeyW TEXTEQU <__imp_SHRegQueryInfoUSKeyW>
extern __imp_SHRegQueryUSValueA:PANYARGS
SHRegQueryUSValue  TEXTEQU <__imp_SHRegQueryUSValueA>
extern __imp_SHRegQueryUSValueW:PANYARGS
SHRegQueryUSValueW TEXTEQU <__imp_SHRegQueryUSValueW>
extern __imp_SHRegSetPathA:PANYARGS
SHRegSetPath  TEXTEQU <__imp_SHRegSetPathA>
extern __imp_SHRegSetPathW:PANYARGS
SHRegSetPathW TEXTEQU <__imp_SHRegSetPathW>
extern __imp_SHRegSetUSValueA:PANYARGS
SHRegSetUSValue  TEXTEQU <__imp_SHRegSetUSValueA>
extern __imp_SHRegSetUSValueW:PANYARGS
SHRegSetUSValueW TEXTEQU <__imp_SHRegSetUSValueW>
extern __imp_SHRegWriteUSValueA:PANYARGS
SHRegWriteUSValue  TEXTEQU <__imp_SHRegWriteUSValueA>
extern __imp_SHRegWriteUSValueW:PANYARGS
SHRegWriteUSValueW TEXTEQU <__imp_SHRegWriteUSValueW>
extern __imp_SHRegisterValidateTemplate:PANYARGS
SHRegisterValidateTemplate TEXTEQU <__imp_SHRegisterValidateTemplate>
extern __imp_SHReleaseThreadRef:PANYARGS
SHReleaseThreadRef TEXTEQU <__imp_SHReleaseThreadRef>
extern __imp_SHSetThreadRef:PANYARGS
SHSetThreadRef TEXTEQU <__imp_SHSetThreadRef>
extern __imp_SHSetValueA:PANYARGS
SHSetValue  TEXTEQU <__imp_SHSetValueA>
extern __imp_SHSetValueW:PANYARGS
SHSetValueW TEXTEQU <__imp_SHSetValueW>
extern __imp_SHSkipJunction:PANYARGS
SHSkipJunction TEXTEQU <__imp_SHSkipJunction>
extern __imp_SHStrDupA:PANYARGS
SHStrDup  TEXTEQU <__imp_SHStrDupA>
extern __imp_SHStrDupW:PANYARGS
SHStrDupW TEXTEQU <__imp_SHStrDupW>
extern __imp_StrCSpnA:PANYARGS
StrCSpn  TEXTEQU <__imp_StrCSpnA>
extern __imp_StrCSpnIA:PANYARGS
StrCSpnI  TEXTEQU <__imp_StrCSpnIA>
extern __imp_StrCSpnIW:PANYARGS
StrCSpnIW TEXTEQU <__imp_StrCSpnIW>
extern __imp_StrCSpnW:PANYARGS
StrCSpnW TEXTEQU <__imp_StrCSpnW>
extern __imp_StrCatBuffA:PANYARGS
StrCatBuff  TEXTEQU <__imp_StrCatBuffA>
extern __imp_StrCatBuffW:PANYARGS
StrCatBuffW TEXTEQU <__imp_StrCatBuffW>
extern __imp_StrCatChainW:PANYARGS
StrCatChainW TEXTEQU <__imp_StrCatChainW>
extern __imp_StrCatW:PANYARGS
StrCatW TEXTEQU <__imp_StrCatW>
extern __imp_StrChrA:PANYARGS
StrChr  TEXTEQU <__imp_StrChrA>
extern __imp_StrChrIA:PANYARGS
StrChrI  TEXTEQU <__imp_StrChrIA>
extern __imp_StrChrIW:PANYARGS
StrChrIW TEXTEQU <__imp_StrChrIW>
extern __imp_StrChrNIW:PANYARGS
StrChrNIW TEXTEQU <__imp_StrChrNIW>
extern __imp_StrChrNW:PANYARGS
StrChrNW TEXTEQU <__imp_StrChrNW>
extern __imp_StrChrW:PANYARGS
StrChrW TEXTEQU <__imp_StrChrW>
extern __imp_StrCmpIW:PANYARGS
StrCmpIW TEXTEQU <__imp_StrCmpIW>
extern __imp_StrCmpLogicalW:PANYARGS
StrCmpLogicalW TEXTEQU <__imp_StrCmpLogicalW>
extern __imp_StrCmpNA:PANYARGS
StrCmpN  TEXTEQU <__imp_StrCmpNA>
extern __imp_StrCmpNIA:PANYARGS
StrCmpNI  TEXTEQU <__imp_StrCmpNIA>
extern __imp_StrCmpNIW:PANYARGS
StrCmpNIW TEXTEQU <__imp_StrCmpNIW>
extern __imp_StrCmpNW:PANYARGS
StrCmpNW TEXTEQU <__imp_StrCmpNW>
extern __imp_StrCmpW:PANYARGS
StrCmpW TEXTEQU <__imp_StrCmpW>
extern __imp_StrCpyNW:PANYARGS
StrCpyNW TEXTEQU <__imp_StrCpyNW>
extern __imp_StrCpyW:PANYARGS
StrCpyW TEXTEQU <__imp_StrCpyW>
extern __imp_StrDupA:PANYARGS
StrDup  TEXTEQU <__imp_StrDupA>
extern __imp_StrDupW:PANYARGS
StrDupW TEXTEQU <__imp_StrDupW>
extern __imp_StrFormatByteSize64A:PANYARGS
StrFormatByteSize64  TEXTEQU <__imp_StrFormatByteSize64A>
extern __imp_StrFormatByteSizeA:PANYARGS
StrFormatByteSize  TEXTEQU <__imp_StrFormatByteSizeA>
extern __imp_StrFormatByteSizeW:PANYARGS
StrFormatByteSizeW TEXTEQU <__imp_StrFormatByteSizeW>
extern __imp_StrFormatKBSizeA:PANYARGS
StrFormatKBSize  TEXTEQU <__imp_StrFormatKBSizeA>
extern __imp_StrFormatKBSizeW:PANYARGS
StrFormatKBSizeW TEXTEQU <__imp_StrFormatKBSizeW>
extern __imp_StrFromTimeIntervalA:PANYARGS
StrFromTimeInterval  TEXTEQU <__imp_StrFromTimeIntervalA>
extern __imp_StrFromTimeIntervalW:PANYARGS
StrFromTimeIntervalW TEXTEQU <__imp_StrFromTimeIntervalW>
extern __imp_StrIsIntlEqualA:PANYARGS
StrIsIntlEqual  TEXTEQU <__imp_StrIsIntlEqualA>
extern __imp_StrIsIntlEqualW:PANYARGS
StrIsIntlEqualW TEXTEQU <__imp_StrIsIntlEqualW>
extern __imp_StrNCatA:PANYARGS
StrNCat  TEXTEQU <__imp_StrNCatA>
extern __imp_StrNCatW:PANYARGS
StrNCatW TEXTEQU <__imp_StrNCatW>
extern __imp_StrPBrkA:PANYARGS
StrPBrk  TEXTEQU <__imp_StrPBrkA>
extern __imp_StrPBrkW:PANYARGS
StrPBrkW TEXTEQU <__imp_StrPBrkW>
extern __imp_StrRChrA:PANYARGS
StrRChr  TEXTEQU <__imp_StrRChrA>
extern __imp_StrRChrIA:PANYARGS
StrRChrI  TEXTEQU <__imp_StrRChrIA>
extern __imp_StrRChrIW:PANYARGS
StrRChrIW TEXTEQU <__imp_StrRChrIW>
extern __imp_StrRChrW:PANYARGS
StrRChrW TEXTEQU <__imp_StrRChrW>
extern __imp_StrRStrIA:PANYARGS
StrRStrI  TEXTEQU <__imp_StrRStrIA>
extern __imp_StrRStrIW:PANYARGS
StrRStrIW TEXTEQU <__imp_StrRStrIW>
extern __imp_StrRetToBSTR:PANYARGS
StrRetToBSTR TEXTEQU <__imp_StrRetToBSTR>
extern __imp_StrRetToBufA:PANYARGS
StrRetToBuf  TEXTEQU <__imp_StrRetToBufA>
extern __imp_StrRetToBufW:PANYARGS
StrRetToBufW TEXTEQU <__imp_StrRetToBufW>
extern __imp_StrRetToStrA:PANYARGS
StrRetToStr  TEXTEQU <__imp_StrRetToStrA>
extern __imp_StrRetToStrW:PANYARGS
StrRetToStrW TEXTEQU <__imp_StrRetToStrW>
extern __imp_StrSpnA:PANYARGS
StrSpn  TEXTEQU <__imp_StrSpnA>
extern __imp_StrSpnW:PANYARGS
StrSpnW TEXTEQU <__imp_StrSpnW>
extern __imp_StrStrA:PANYARGS
StrStr  TEXTEQU <__imp_StrStrA>
extern __imp_StrStrIA:PANYARGS
StrStrI  TEXTEQU <__imp_StrStrIA>
extern __imp_StrStrIW:PANYARGS
StrStrIW TEXTEQU <__imp_StrStrIW>
extern __imp_StrStrNIW:PANYARGS
StrStrNIW TEXTEQU <__imp_StrStrNIW>
extern __imp_StrStrNW:PANYARGS
StrStrNW TEXTEQU <__imp_StrStrNW>
extern __imp_StrStrW:PANYARGS
StrStrW TEXTEQU <__imp_StrStrW>
extern __imp_StrToInt64ExA:PANYARGS
StrToInt64Ex  TEXTEQU <__imp_StrToInt64ExA>
extern __imp_StrToInt64ExW:PANYARGS
StrToInt64ExW TEXTEQU <__imp_StrToInt64ExW>
extern __imp_StrToIntA:PANYARGS
StrToIntA  TEXTEQU <__imp_StrToIntA>
extern __imp_StrToIntExA:PANYARGS
StrToIntEx  TEXTEQU <__imp_StrToIntExA>
extern __imp_StrToIntExW:PANYARGS
StrToIntExW TEXTEQU <__imp_StrToIntExW>
extern __imp_StrToIntW:PANYARGS
StrToIntW TEXTEQU <__imp_StrToIntW>
extern __imp_StrTrimA:PANYARGS
StrTrim  TEXTEQU <__imp_StrTrimA>
extern __imp_StrTrimW:PANYARGS
StrTrimW TEXTEQU <__imp_StrTrimW>
extern __imp_UrlApplySchemeA:PANYARGS
UrlApplyScheme  TEXTEQU <__imp_UrlApplySchemeA>
extern __imp_UrlApplySchemeW:PANYARGS
UrlApplySchemeW TEXTEQU <__imp_UrlApplySchemeW>
extern __imp_UrlCanonicalizeA:PANYARGS
UrlCanonicalize  TEXTEQU <__imp_UrlCanonicalizeA>
extern __imp_UrlCanonicalizeW:PANYARGS
UrlCanonicalizeW TEXTEQU <__imp_UrlCanonicalizeW>
extern __imp_UrlCombineA:PANYARGS
UrlCombine  TEXTEQU <__imp_UrlCombineA>
extern __imp_UrlCombineW:PANYARGS
UrlCombineW TEXTEQU <__imp_UrlCombineW>
extern __imp_UrlCompareA:PANYARGS
UrlCompare  TEXTEQU <__imp_UrlCompareA>
extern __imp_UrlCompareW:PANYARGS
UrlCompareW TEXTEQU <__imp_UrlCompareW>
extern __imp_UrlCreateFromPathA:PANYARGS
UrlCreateFromPath  TEXTEQU <__imp_UrlCreateFromPathA>
extern __imp_UrlCreateFromPathW:PANYARGS
UrlCreateFromPathW TEXTEQU <__imp_UrlCreateFromPathW>
extern __imp_UrlEscapeA:PANYARGS
UrlEscape  TEXTEQU <__imp_UrlEscapeA>
extern __imp_UrlEscapeW:PANYARGS
UrlEscapeW TEXTEQU <__imp_UrlEscapeW>
extern __imp_UrlGetLocationA:PANYARGS
UrlGetLocation  TEXTEQU <__imp_UrlGetLocationA>
extern __imp_UrlGetLocationW:PANYARGS
UrlGetLocationW TEXTEQU <__imp_UrlGetLocationW>
extern __imp_UrlGetPartA:PANYARGS
UrlGetPart  TEXTEQU <__imp_UrlGetPartA>
extern __imp_UrlGetPartW:PANYARGS
UrlGetPartW TEXTEQU <__imp_UrlGetPartW>
extern __imp_UrlHashA:PANYARGS
UrlHash  TEXTEQU <__imp_UrlHashA>
extern __imp_UrlHashW:PANYARGS
UrlHashW TEXTEQU <__imp_UrlHashW>
extern __imp_UrlIsA:PANYARGS
UrlIs  TEXTEQU <__imp_UrlIsA>
extern __imp_UrlIsNoHistoryA:PANYARGS
UrlIsNoHistory  TEXTEQU <__imp_UrlIsNoHistoryA>
extern __imp_UrlIsNoHistoryW:PANYARGS
UrlIsNoHistoryW TEXTEQU <__imp_UrlIsNoHistoryW>
extern __imp_UrlIsOpaqueA:PANYARGS
UrlIsOpaque  TEXTEQU <__imp_UrlIsOpaqueA>
extern __imp_UrlIsOpaqueW:PANYARGS
UrlIsOpaqueW TEXTEQU <__imp_UrlIsOpaqueW>
extern __imp_UrlIsW:PANYARGS
UrlIsW TEXTEQU <__imp_UrlIsW>
extern __imp_UrlUnescapeA:PANYARGS
UrlUnescape  TEXTEQU <__imp_UrlUnescapeA>
extern __imp_UrlUnescapeW:PANYARGS
UrlUnescapeW TEXTEQU <__imp_UrlUnescapeW>
extern __imp_wnsprintfA:PANYARGS
wnsprintf  TEXTEQU <__imp_wnsprintfA>
extern __imp_wnsprintfW:PANYARGS
wnsprintfW TEXTEQU <__imp_wnsprintfW>
extern __imp_wvnsprintfA:PANYARGS
wvnsprintf  TEXTEQU <__imp_wvnsprintfA>
extern __imp_wvnsprintfW:PANYARGS
wvnsprintfW TEXTEQU <__imp_wvnsprintfW>
