extern __imp_Scrap_CreateFromDataObject:PANYARGS
Scrap_CreateFromDataObject TEXTEQU <__imp_Scrap_CreateFromDataObject>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_OpenScrap_RunDLL:PANYARGS
OpenScrap_RunDLL TEXTEQU <__imp_OpenScrap_RunDLL>
extern __imp_OpenScrap_RunDLLA:PANYARGS
OpenScrap_RunDLL  TEXTEQU <__imp_OpenScrap_RunDLLA>
extern __imp_OpenScrap_RunDLLW:PANYARGS
OpenScrap_RunDLLW TEXTEQU <__imp_OpenScrap_RunDLLW>
