extern __imp_shsvcs_ordinal1:PANYARGS
shsvcs_ordinal1 TEXTEQU <__imp_shsvcs_ordinal1>
extern __imp_shsvcs_ordinal2:PANYARGS
shsvcs_ordinal2 TEXTEQU <__imp_shsvcs_ordinal2>
extern __imp_shsvcs_ordinal3:PANYARGS
shsvcs_ordinal3 TEXTEQU <__imp_shsvcs_ordinal3>
extern __imp_shsvcs_ordinal4:PANYARGS
shsvcs_ordinal4 TEXTEQU <__imp_shsvcs_ordinal4>
extern __imp_shsvcs_ordinal5:PANYARGS
shsvcs_ordinal5 TEXTEQU <__imp_shsvcs_ordinal5>
extern __imp_shsvcs_ordinal6:PANYARGS
shsvcs_ordinal6 TEXTEQU <__imp_shsvcs_ordinal6>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_HardwareDetectionServiceMain:PANYARGS
HardwareDetectionServiceMain TEXTEQU <__imp_HardwareDetectionServiceMain>
extern __imp_ThemeServiceMain:PANYARGS
ThemeServiceMain TEXTEQU <__imp_ThemeServiceMain>
extern __imp_CreateHardwareEventMoniker:PANYARGS
CreateHardwareEventMoniker TEXTEQU <__imp_CreateHardwareEventMoniker>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
