extern __imp_??0?$ExcTemplate@$01K@scu@@QEAA@AEBV01@@Z:PANYARGS
??0?$ExcTemplate@$01K@scu@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0?$ExcTemplate@$01K@scu@@QEAA@AEBV01@@Z>
extern __imp_??0?$ExcTemplate@$01K@scu@@QEAA@K@Z:PANYARGS
??0?$ExcTemplate@$01K@scu@@QEAA@K@Z TEXTEQU <__imp_??0?$ExcTemplate@$01K@scu@@QEAA@K@Z>
extern __imp_??0?$SecureArray@D@scu@@QEAA@AEBV01@@Z:PANYARGS
??0?$SecureArray@D@scu@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0?$SecureArray@D@scu@@QEAA@AEBV01@@Z>
extern __imp_??0?$SecureArray@D@scu@@QEAA@PEAD_K@Z:PANYARGS
??0?$SecureArray@D@scu@@QEAA@PEAD_K@Z TEXTEQU <__imp_??0?$SecureArray@D@scu@@QEAA@PEAD_K@Z>
extern __imp_??0?$SecureArray@D@scu@@QEAA@PEBD_K@Z:PANYARGS
??0?$SecureArray@D@scu@@QEAA@PEBD_K@Z TEXTEQU <__imp_??0?$SecureArray@D@scu@@QEAA@PEBD_K@Z>
extern __imp_??0?$SecureArray@D@scu@@QEAA@XZ:PANYARGS
??0?$SecureArray@D@scu@@QEAA@XZ TEXTEQU <__imp_??0?$SecureArray@D@scu@@QEAA@XZ>
extern __imp_??0?$SecureArray@D@scu@@QEAA@_K@Z:PANYARGS
??0?$SecureArray@D@scu@@QEAA@_K@Z TEXTEQU <__imp_??0?$SecureArray@D@scu@@QEAA@_K@Z>
extern __imp_??0?$SecureArray@D@scu@@QEAA@_KAEBD@Z:PANYARGS
??0?$SecureArray@D@scu@@QEAA@_KAEBD@Z TEXTEQU <__imp_??0?$SecureArray@D@scu@@QEAA@_KAEBD@Z>
extern __imp_??0?$SecureArray@E@scu@@QEAA@AEBV01@@Z:PANYARGS
??0?$SecureArray@E@scu@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0?$SecureArray@E@scu@@QEAA@AEBV01@@Z>
extern __imp_??0?$SecureArray@E@scu@@QEAA@PEAE_K@Z:PANYARGS
??0?$SecureArray@E@scu@@QEAA@PEAE_K@Z TEXTEQU <__imp_??0?$SecureArray@E@scu@@QEAA@PEAE_K@Z>
extern __imp_??0?$SecureArray@E@scu@@QEAA@PEBE_K@Z:PANYARGS
??0?$SecureArray@E@scu@@QEAA@PEBE_K@Z TEXTEQU <__imp_??0?$SecureArray@E@scu@@QEAA@PEBE_K@Z>
extern __imp_??0?$SecureArray@E@scu@@QEAA@XZ:PANYARGS
??0?$SecureArray@E@scu@@QEAA@XZ TEXTEQU <__imp_??0?$SecureArray@E@scu@@QEAA@XZ>
extern __imp_??0?$SecureArray@E@scu@@QEAA@_K@Z:PANYARGS
??0?$SecureArray@E@scu@@QEAA@_K@Z TEXTEQU <__imp_??0?$SecureArray@E@scu@@QEAA@_K@Z>
extern __imp_??0?$SecureArray@E@scu@@QEAA@_KAEBE@Z:PANYARGS
??0?$SecureArray@E@scu@@QEAA@_KAEBE@Z TEXTEQU <__imp_??0?$SecureArray@E@scu@@QEAA@_KAEBE@Z>
extern __imp_??0?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@AEBV01@@Z:PANYARGS
??0?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@AEBV01@@Z>
extern __imp_??0?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@PEAVCSharedMarker@iop@@@Z:PANYARGS
??0?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@PEAVCSharedMarker@iop@@@Z TEXTEQU <__imp_??0?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@PEAVCSharedMarker@iop@@@Z>
extern __imp_??0?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@AEBV01@@Z:PANYARGS
??0?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@AEBV01@@Z>
extern __imp_??0?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@PEAVRMHangProcDeathSynchObjects@iop@@@Z:PANYARGS
??0?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@PEAVRMHangProcDeathSynchObjects@iop@@@Z TEXTEQU <__imp_??0?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@PEAVRMHangProcDeathSynchObjects@iop@@@Z>
extern __imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@AEBV01@@Z:PANYARGS
??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@AEBV01@@Z>
extern __imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@AEBV?$allocator@VFilePathComponent@iop@@@1@@Z:PANYARGS
??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@AEBV?$allocator@VFilePathComponent@iop@@@1@@Z TEXTEQU <__imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@AEBV?$allocator@VFilePathComponent@iop@@@1@@Z>
extern __imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@PEBVFilePathComponent@iop@@0AEBV?$allocator@VFilePathComponent@iop@@@1@@Z:PANYARGS
??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@PEBVFilePathComponent@iop@@0AEBV?$allocator@VFilePathComponent@iop@@@1@@Z TEXTEQU <__imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@PEBVFilePathComponent@iop@@0AEBV?$allocator@VFilePathComponent@iop@@@1@@Z>
extern __imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@Vconst_iterator@01@0AEBV?$allocator@VFilePathComponent@iop@@@1@@Z:PANYARGS
??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@Vconst_iterator@01@0AEBV?$allocator@VFilePathComponent@iop@@@1@@Z TEXTEQU <__imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@Vconst_iterator@01@0AEBV?$allocator@VFilePathComponent@iop@@@1@@Z>
extern __imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@_KAEBVFilePathComponent@iop@@AEBV?$allocator@VFilePathComponent@iop@@@1@@Z:PANYARGS
??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@_KAEBVFilePathComponent@iop@@AEBV?$allocator@VFilePathComponent@iop@@@1@@Z TEXTEQU <__imp_??0?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@_KAEBVFilePathComponent@iop@@AEBV?$allocator@VFilePathComponent@iop@@@1@@Z>
extern __imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@AEBV01@@Z:PANYARGS
??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@AEBV01@@Z>
extern __imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z:PANYARGS
??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z TEXTEQU <__imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z>
extern __imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@PEBQEAUEventInfo@iop@@0AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z:PANYARGS
??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@PEBQEAUEventInfo@iop@@0AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z TEXTEQU <__imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@PEBQEAUEventInfo@iop@@0AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z>
extern __imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@_KAEBQEAUEventInfo@iop@@AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z:PANYARGS
??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@_KAEBQEAUEventInfo@iop@@AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z TEXTEQU <__imp_??0?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@_KAEBQEAUEventInfo@iop@@AEBV?$allocator@PEAUEventInfo@iop@@@1@@Z>
extern __imp_??0CAccessCard@iop@@QEAA@_KPEBD0K@Z:PANYARGS
??0CAccessCard@iop@@QEAA@_KPEBD0K@Z TEXTEQU <__imp_??0CAccessCard@iop@@QEAA@_KPEBD0K@Z>
extern __imp_??0CCryptoCard@iop@@QEAA@_KPEBD0K@Z:PANYARGS
??0CCryptoCard@iop@@QEAA@_KPEBD0K@Z TEXTEQU <__imp_??0CCryptoCard@iop@@QEAA@_KPEBD0K@Z>
extern __imp_??0CIOP@iop@@QEAA@XZ:PANYARGS
??0CIOP@iop@@QEAA@XZ TEXTEQU <__imp_??0CIOP@iop@@QEAA@XZ>
extern __imp_??0CIOPCriticalSection@iop@@QEAA@PEAVCIOPLock@1@@Z:PANYARGS
??0CIOPCriticalSection@iop@@QEAA@PEAVCIOPLock@1@@Z TEXTEQU <__imp_??0CIOPCriticalSection@iop@@QEAA@PEAVCIOPLock@1@@Z>
extern __imp_??0CIOPLock@iop@@QEAA@PEBD@Z:PANYARGS
??0CIOPLock@iop@@QEAA@PEBD@Z TEXTEQU <__imp_??0CIOPLock@iop@@QEAA@PEBD@Z>
extern __imp_??0CIOPMutex@iop@@QEAA@PEAVCIOPLock@1@@Z:PANYARGS
??0CIOPMutex@iop@@QEAA@PEAVCIOPLock@1@@Z TEXTEQU <__imp_??0CIOPMutex@iop@@QEAA@PEAVCIOPLock@1@@Z>
extern __imp_??0CLockWrap@iop@@QEAA@PEAVCIOPLock@1@@Z:PANYARGS
??0CLockWrap@iop@@QEAA@PEAVCIOPLock@1@@Z TEXTEQU <__imp_??0CLockWrap@iop@@QEAA@PEAVCIOPLock@1@@Z>
extern __imp_??0CMarker@iop@@QEAA@AEBV01@@Z:PANYARGS
??0CMarker@iop@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0CMarker@iop@@QEAA@AEBV01@@Z>
extern __imp_??0CMarker@iop@@QEAA@AEBW4MarkerType@01@@Z:PANYARGS
??0CMarker@iop@@QEAA@AEBW4MarkerType@01@@Z TEXTEQU <__imp_??0CMarker@iop@@QEAA@AEBW4MarkerType@01@@Z>
extern __imp_??0CMarker@iop@@QEAA@W4MarkerType@01@AEBU_GUID@@AEB_J@Z:PANYARGS
??0CMarker@iop@@QEAA@W4MarkerType@01@AEBU_GUID@@AEB_J@Z TEXTEQU <__imp_??0CMarker@iop@@QEAA@W4MarkerType@01@AEBU_GUID@@AEB_J@Z>
extern __imp_??0CPrivateKeyBlob@iop@@QEAA@AEBV01@@Z:PANYARGS
??0CPrivateKeyBlob@iop@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0CPrivateKeyBlob@iop@@QEAA@AEBV01@@Z>
extern __imp_??0CPrivateKeyBlob@iop@@QEAA@XZ:PANYARGS
??0CPrivateKeyBlob@iop@@QEAA@XZ TEXTEQU <__imp_??0CPrivateKeyBlob@iop@@QEAA@XZ>
extern __imp_??0CPublicKeyBlob@iop@@QEAA@AEBV01@@Z:PANYARGS
??0CPublicKeyBlob@iop@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0CPublicKeyBlob@iop@@QEAA@AEBV01@@Z>
extern __imp_??0CPublicKeyBlob@iop@@QEAA@XZ:PANYARGS
??0CPublicKeyBlob@iop@@QEAA@XZ TEXTEQU <__imp_??0CPublicKeyBlob@iop@@QEAA@XZ>
extern __imp_??0CSCardLock@iop@@QEAA@PEAVCIOPLock@1@@Z:PANYARGS
??0CSCardLock@iop@@QEAA@PEAVCIOPLock@1@@Z TEXTEQU <__imp_??0CSCardLock@iop@@QEAA@PEAVCIOPLock@1@@Z>
extern __imp_??0CSmartCard@iop@@QEAA@_KPEBD0K@Z:PANYARGS
??0CSmartCard@iop@@QEAA@_KPEBD0K@Z TEXTEQU <__imp_??0CSmartCard@iop@@QEAA@_KPEBD0K@Z>
extern __imp_??0Exception@CSmartCard@iop@@QEAA@AEBV012@@Z:PANYARGS
??0Exception@CSmartCard@iop@@QEAA@AEBV012@@Z TEXTEQU <__imp_??0Exception@CSmartCard@iop@@QEAA@AEBV012@@Z>
extern __imp_??0Exception@CSmartCard@iop@@QEAA@W4CauseCode@12@EEG@Z:PANYARGS
??0Exception@CSmartCard@iop@@QEAA@W4CauseCode@12@EEG@Z TEXTEQU <__imp_??0Exception@CSmartCard@iop@@QEAA@W4CauseCode@12@EEG@Z>
extern __imp_??0Exception@scu@@IEAA@W4FacilityCode@01@@Z:PANYARGS
??0Exception@scu@@IEAA@W4FacilityCode@01@@Z TEXTEQU <__imp_??0Exception@scu@@IEAA@W4FacilityCode@01@@Z>
extern __imp_??0Exception@scu@@QEAA@AEBV01@@Z:PANYARGS
??0Exception@scu@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0Exception@scu@@QEAA@AEBV01@@Z>
extern __imp_??0FilePath@iop@@QEAA@AEBV01@@Z:PANYARGS
??0FilePath@iop@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0FilePath@iop@@QEAA@AEBV01@@Z>
extern __imp_??0FilePath@iop@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PANYARGS
??0FilePath@iop@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z TEXTEQU <__imp_??0FilePath@iop@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>
extern __imp_??0FilePath@iop@@QEAA@XZ:PANYARGS
??0FilePath@iop@@QEAA@XZ TEXTEQU <__imp_??0FilePath@iop@@QEAA@XZ>
extern __imp_??0FilePathComponent@iop@@QEAA@AEBV01@@Z:PANYARGS
??0FilePathComponent@iop@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0FilePathComponent@iop@@QEAA@AEBV01@@Z>
extern __imp_??0FilePathComponent@iop@@QEAA@G@Z:PANYARGS
??0FilePathComponent@iop@@QEAA@G@Z TEXTEQU <__imp_??0FilePathComponent@iop@@QEAA@G@Z>
extern __imp_??0FilePathComponent@iop@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PANYARGS
??0FilePathComponent@iop@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z TEXTEQU <__imp_??0FilePathComponent@iop@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>
extern __imp_??0OsException@scu@@QEAA@AEBV01@@Z:PANYARGS
??0OsException@scu@@QEAA@AEBV01@@Z TEXTEQU <__imp_??0OsException@scu@@QEAA@AEBV01@@Z>
extern __imp_??0OsException@scu@@QEAA@J@Z:PANYARGS
??0OsException@scu@@QEAA@J@Z TEXTEQU <__imp_??0OsException@scu@@QEAA@J@Z>
extern __imp_??0OsException@scu@@QEAA@K@Z:PANYARGS
??0OsException@scu@@QEAA@K@Z TEXTEQU <__imp_??0OsException@scu@@QEAA@K@Z>
extern __imp_??1?$ExcTemplate@$01K@scu@@UEAA@XZ:PANYARGS
??1?$ExcTemplate@$01K@scu@@UEAA@XZ TEXTEQU <__imp_??1?$ExcTemplate@$01K@scu@@UEAA@XZ>
extern __imp_??1?$SecureArray@D@scu@@QEAA@XZ:PANYARGS
??1?$SecureArray@D@scu@@QEAA@XZ TEXTEQU <__imp_??1?$SecureArray@D@scu@@QEAA@XZ>
extern __imp_??1?$SecureArray@E@scu@@QEAA@XZ:PANYARGS
??1?$SecureArray@E@scu@@QEAA@XZ TEXTEQU <__imp_??1?$SecureArray@E@scu@@QEAA@XZ>
extern __imp_??1?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@XZ:PANYARGS
??1?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@XZ TEXTEQU <__imp_??1?$auto_ptr@VCSharedMarker@iop@@@std@@QEAA@XZ>
extern __imp_??1?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@XZ:PANYARGS
??1?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@XZ TEXTEQU <__imp_??1?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAA@XZ>
extern __imp_??1?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@XZ:PANYARGS
??1?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@XZ TEXTEQU <__imp_??1?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA@XZ>
extern __imp_??1?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@XZ:PANYARGS
??1?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@XZ TEXTEQU <__imp_??1?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA@XZ>
extern __imp_??1CAccessCard@iop@@UEAA@XZ:PANYARGS
??1CAccessCard@iop@@UEAA@XZ TEXTEQU <__imp_??1CAccessCard@iop@@UEAA@XZ>
extern __imp_??1CCryptoCard@iop@@UEAA@XZ:PANYARGS
??1CCryptoCard@iop@@UEAA@XZ TEXTEQU <__imp_??1CCryptoCard@iop@@UEAA@XZ>
extern __imp_??1CIOP@iop@@QEAA@XZ:PANYARGS
??1CIOP@iop@@QEAA@XZ TEXTEQU <__imp_??1CIOP@iop@@QEAA@XZ>
extern __imp_??1CIOPCriticalSection@iop@@QEAA@XZ:PANYARGS
??1CIOPCriticalSection@iop@@QEAA@XZ TEXTEQU <__imp_??1CIOPCriticalSection@iop@@QEAA@XZ>
extern __imp_??1CIOPLock@iop@@UEAA@XZ:PANYARGS
??1CIOPLock@iop@@UEAA@XZ TEXTEQU <__imp_??1CIOPLock@iop@@UEAA@XZ>
extern __imp_??1CIOPMutex@iop@@QEAA@XZ:PANYARGS
??1CIOPMutex@iop@@QEAA@XZ TEXTEQU <__imp_??1CIOPMutex@iop@@QEAA@XZ>
extern __imp_??1CLockWrap@iop@@QEAA@XZ:PANYARGS
??1CLockWrap@iop@@QEAA@XZ TEXTEQU <__imp_??1CLockWrap@iop@@QEAA@XZ>
extern __imp_??1CMarker@iop@@UEAA@XZ:PANYARGS
??1CMarker@iop@@UEAA@XZ TEXTEQU <__imp_??1CMarker@iop@@UEAA@XZ>
extern __imp_??1CPrivateKeyBlob@iop@@UEAA@XZ:PANYARGS
??1CPrivateKeyBlob@iop@@UEAA@XZ TEXTEQU <__imp_??1CPrivateKeyBlob@iop@@UEAA@XZ>
extern __imp_??1CPublicKeyBlob@iop@@UEAA@XZ:PANYARGS
??1CPublicKeyBlob@iop@@UEAA@XZ TEXTEQU <__imp_??1CPublicKeyBlob@iop@@UEAA@XZ>
extern __imp_??1CSCardLock@iop@@QEAA@XZ:PANYARGS
??1CSCardLock@iop@@QEAA@XZ TEXTEQU <__imp_??1CSCardLock@iop@@QEAA@XZ>
extern __imp_??1CSmartCard@iop@@UEAA@XZ:PANYARGS
??1CSmartCard@iop@@UEAA@XZ TEXTEQU <__imp_??1CSmartCard@iop@@UEAA@XZ>
extern __imp_??1Exception@CSmartCard@iop@@UEAA@XZ:PANYARGS
??1Exception@CSmartCard@iop@@UEAA@XZ TEXTEQU <__imp_??1Exception@CSmartCard@iop@@UEAA@XZ>
extern __imp_??1Exception@scu@@UEAA@XZ:PANYARGS
??1Exception@scu@@UEAA@XZ TEXTEQU <__imp_??1Exception@scu@@UEAA@XZ>
extern __imp_??1FilePath@iop@@UEAA@XZ:PANYARGS
??1FilePath@iop@@UEAA@XZ TEXTEQU <__imp_??1FilePath@iop@@UEAA@XZ>
extern __imp_??1FilePathComponent@iop@@UEAA@XZ:PANYARGS
??1FilePathComponent@iop@@UEAA@XZ TEXTEQU <__imp_??1FilePathComponent@iop@@UEAA@XZ>
extern __imp_??1OsException@scu@@UEAA@XZ:PANYARGS
??1OsException@scu@@UEAA@XZ TEXTEQU <__imp_??1OsException@scu@@UEAA@XZ>
extern __imp_??4?$ExcTemplate@$01K@scu@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4?$ExcTemplate@$01K@scu@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4?$ExcTemplate@$01K@scu@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4?$SecureArray@D@scu@@QEAAAEAV01@AEBD@Z:PANYARGS
??4?$SecureArray@D@scu@@QEAAAEAV01@AEBD@Z TEXTEQU <__imp_??4?$SecureArray@D@scu@@QEAAAEAV01@AEBD@Z>
extern __imp_??4?$SecureArray@D@scu@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4?$SecureArray@D@scu@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4?$SecureArray@D@scu@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4?$SecureArray@E@scu@@QEAAAEAV01@AEBE@Z:PANYARGS
??4?$SecureArray@E@scu@@QEAAAEAV01@AEBE@Z TEXTEQU <__imp_??4?$SecureArray@E@scu@@QEAAAEAV01@AEBE@Z>
extern __imp_??4?$SecureArray@E@scu@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4?$SecureArray@E@scu@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4?$SecureArray@E@scu@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4?$auto_ptr@VCSharedMarker@iop@@@std@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4?$auto_ptr@VCSharedMarker@iop@@@std@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4?$auto_ptr@VCSharedMarker@iop@@@std@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CIOP@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CIOP@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CIOP@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CIOPCriticalSection@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CIOPCriticalSection@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CIOPCriticalSection@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CIOPMutex@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CIOPMutex@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CIOPMutex@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CLockWrap@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CLockWrap@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CLockWrap@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CMarker@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CMarker@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CMarker@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CPrivateKeyBlob@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CPrivateKeyBlob@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CPrivateKeyBlob@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CPublicKeyBlob@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CPublicKeyBlob@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CPublicKeyBlob@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4CSCardLock@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4CSCardLock@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4CSCardLock@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4Exception@CSmartCard@iop@@QEAAAEAV012@AEBV012@@Z:PANYARGS
??4Exception@CSmartCard@iop@@QEAAAEAV012@AEBV012@@Z TEXTEQU <__imp_??4Exception@CSmartCard@iop@@QEAAAEAV012@AEBV012@@Z>
extern __imp_??4Exception@scu@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4Exception@scu@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4Exception@scu@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4FilePath@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4FilePath@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4FilePath@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4FilePathComponent@iop@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4FilePathComponent@iop@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4FilePathComponent@iop@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??4OsException@scu@@QEAAAEAV01@AEBV01@@Z:PANYARGS
??4OsException@scu@@QEAAAEAV01@AEBV01@@Z TEXTEQU <__imp_??4OsException@scu@@QEAAAEAV01@AEBV01@@Z>
extern __imp_??8iop@@YA_NAEBVCMarker@0@0@Z:PANYARGS
??8iop@@YA_NAEBVCMarker@0@0@Z TEXTEQU <__imp_??8iop@@YA_NAEBVCMarker@0@0@Z>
extern __imp_??9iop@@YA_NAEBVCMarker@0@0@Z:PANYARGS
??9iop@@YA_NAEBVCMarker@0@0@Z TEXTEQU <__imp_??9iop@@YA_NAEBVCMarker@0@0@Z>
extern __imp_??A?$SecureArray@D@scu@@QEAAAEAD_K@Z:PANYARGS
??A?$SecureArray@D@scu@@QEAAAEAD_K@Z TEXTEQU <__imp_??A?$SecureArray@D@scu@@QEAAAEAD_K@Z>
extern __imp_??A?$SecureArray@D@scu@@QEBAAEBD_K@Z:PANYARGS
??A?$SecureArray@D@scu@@QEBAAEBD_K@Z TEXTEQU <__imp_??A?$SecureArray@D@scu@@QEBAAEBD_K@Z>
extern __imp_??A?$SecureArray@E@scu@@QEAAAEAE_K@Z:PANYARGS
??A?$SecureArray@E@scu@@QEAAAEAE_K@Z TEXTEQU <__imp_??A?$SecureArray@E@scu@@QEAAAEAE_K@Z>
extern __imp_??A?$SecureArray@E@scu@@QEBAAEBE_K@Z:PANYARGS
??A?$SecureArray@E@scu@@QEBAAEBE_K@Z TEXTEQU <__imp_??A?$SecureArray@E@scu@@QEBAAEBE_K@Z>
extern __imp_??A?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@_K@Z:PANYARGS
??A?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@_K@Z TEXTEQU <__imp_??A?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@_K@Z>
extern __imp_??A?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@_K@Z:PANYARGS
??A?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@_K@Z TEXTEQU <__imp_??A?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@_K@Z>
extern __imp_??AFilePath@iop@@QEAAAEAVFilePathComponent@1@I@Z:PANYARGS
??AFilePath@iop@@QEAAAEAVFilePathComponent@1@I@Z TEXTEQU <__imp_??AFilePath@iop@@QEAAAEAVFilePathComponent@1@I@Z>
extern __imp_??C?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ:PANYARGS
??C?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ TEXTEQU <__imp_??C?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ>
extern __imp_??C?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ:PANYARGS
??C?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ TEXTEQU <__imp_??C?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ>
extern __imp_??D?$SecureArray@D@scu@@QEAAAEADXZ:PANYARGS
??D?$SecureArray@D@scu@@QEAAAEADXZ TEXTEQU <__imp_??D?$SecureArray@D@scu@@QEAAAEADXZ>
extern __imp_??D?$SecureArray@D@scu@@QEBAAEBDXZ:PANYARGS
??D?$SecureArray@D@scu@@QEBAAEBDXZ TEXTEQU <__imp_??D?$SecureArray@D@scu@@QEBAAEBDXZ>
extern __imp_??D?$SecureArray@E@scu@@QEAAAEAEXZ:PANYARGS
??D?$SecureArray@E@scu@@QEAAAEAEXZ TEXTEQU <__imp_??D?$SecureArray@E@scu@@QEAAAEAEXZ>
extern __imp_??D?$SecureArray@E@scu@@QEBAAEBEXZ:PANYARGS
??D?$SecureArray@E@scu@@QEBAAEBEXZ TEXTEQU <__imp_??D?$SecureArray@E@scu@@QEBAAEBEXZ>
extern __imp_??D?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAAEAVCSharedMarker@iop@@XZ:PANYARGS
??D?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAAEAVCSharedMarker@iop@@XZ TEXTEQU <__imp_??D?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAAEAVCSharedMarker@iop@@XZ>
extern __imp_??D?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAAEAVRMHangProcDeathSynchObjects@iop@@XZ:PANYARGS
??D?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAAEAVRMHangProcDeathSynchObjects@iop@@XZ TEXTEQU <__imp_??D?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAAEAVRMHangProcDeathSynchObjects@iop@@XZ>
extern __imp_??YFilePath@iop@@QEAAAEBV01@VFilePathComponent@1@@Z:PANYARGS
??YFilePath@iop@@QEAAAEBV01@VFilePathComponent@1@@Z TEXTEQU <__imp_??YFilePath@iop@@QEAAAEBV01@VFilePathComponent@1@@Z>
extern __imp_??_7?$ExcTemplate@$01K@scu@@6B@:PANYARGS
??_7?$ExcTemplate@$01K@scu@@6B@ TEXTEQU <__imp_??_7?$ExcTemplate@$01K@scu@@6B@>
extern __imp_??_7CAccessCard@iop@@6B@:PANYARGS
??_7CAccessCard@iop@@6B@ TEXTEQU <__imp_??_7CAccessCard@iop@@6B@>
extern __imp_??_7CCryptoCard@iop@@6B@:PANYARGS
??_7CCryptoCard@iop@@6B@ TEXTEQU <__imp_??_7CCryptoCard@iop@@6B@>
extern __imp_??_7CIOPLock@iop@@6B@:PANYARGS
??_7CIOPLock@iop@@6B@ TEXTEQU <__imp_??_7CIOPLock@iop@@6B@>
extern __imp_??_7CMarker@iop@@6B@:PANYARGS
??_7CMarker@iop@@6B@ TEXTEQU <__imp_??_7CMarker@iop@@6B@>
extern __imp_??_7CPrivateKeyBlob@iop@@6B@:PANYARGS
??_7CPrivateKeyBlob@iop@@6B@ TEXTEQU <__imp_??_7CPrivateKeyBlob@iop@@6B@>
extern __imp_??_7CPublicKeyBlob@iop@@6B@:PANYARGS
??_7CPublicKeyBlob@iop@@6B@ TEXTEQU <__imp_??_7CPublicKeyBlob@iop@@6B@>
extern __imp_??_7CSmartCard@iop@@6B@:PANYARGS
??_7CSmartCard@iop@@6B@ TEXTEQU <__imp_??_7CSmartCard@iop@@6B@>
extern __imp_??_7Exception@CSmartCard@iop@@6B@:PANYARGS
??_7Exception@CSmartCard@iop@@6B@ TEXTEQU <__imp_??_7Exception@CSmartCard@iop@@6B@>
extern __imp_??_7Exception@scu@@6B@:PANYARGS
??_7Exception@scu@@6B@ TEXTEQU <__imp_??_7Exception@scu@@6B@>
extern __imp_??_7FilePath@iop@@6B@:PANYARGS
??_7FilePath@iop@@6B@ TEXTEQU <__imp_??_7FilePath@iop@@6B@>
extern __imp_??_7FilePathComponent@iop@@6B@:PANYARGS
??_7FilePathComponent@iop@@6B@ TEXTEQU <__imp_??_7FilePathComponent@iop@@6B@>
extern __imp_??_7OsException@scu@@6B@:PANYARGS
??_7OsException@scu@@6B@ TEXTEQU <__imp_??_7OsException@scu@@6B@>
extern __imp_??_F?$auto_ptr@VCSharedMarker@iop@@@std@@QEAAXXZ:PANYARGS
??_F?$auto_ptr@VCSharedMarker@iop@@@std@@QEAAXXZ TEXTEQU <__imp_??_F?$auto_ptr@VCSharedMarker@iop@@@std@@QEAAXXZ>
extern __imp_??_F?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAAXXZ:PANYARGS
??_F?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAAXXZ TEXTEQU <__imp_??_F?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEAAXXZ>
extern __imp_??_F?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ:PANYARGS
??_F?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_??_F?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ>
extern __imp_??_F?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ:PANYARGS
??_F?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_??_F?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?AccessToCryptoACL@CCryptoCard@iop@@IEAAXPEA_NPEAUCryptoACL@2@@Z:PANYARGS
?AccessToCryptoACL@CCryptoCard@iop@@IEAAXPEA_NPEAUCryptoACL@2@@Z TEXTEQU <__imp_?AccessToCryptoACL@CCryptoCard@iop@@IEAAXPEA_NPEAUCryptoACL@2@@Z>
extern __imp_?BlockApplet@CAccessCard@iop@@UEAAXXZ:PANYARGS
?BlockApplet@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?BlockApplet@CAccessCard@iop@@UEAAXXZ>
extern __imp_?BlockApplet@CSmartCard@iop@@UEAAXXZ:PANYARGS
?BlockApplet@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?BlockApplet@CSmartCard@iop@@UEAAXXZ>
extern __imp_?Cause@?$ExcTemplate@$01K@scu@@QEBAKXZ:PANYARGS
?Cause@?$ExcTemplate@$01K@scu@@QEBAKXZ TEXTEQU <__imp_?Cause@?$ExcTemplate@$01K@scu@@QEBAKXZ>
extern __imp_?Cause@Exception@CSmartCard@iop@@QEBA?AW4CauseCode@23@XZ:PANYARGS
?Cause@Exception@CSmartCard@iop@@QEBA?AW4CauseCode@23@XZ TEXTEQU <__imp_?Cause@Exception@CSmartCard@iop@@QEBA?AW4CauseCode@23@XZ>
extern __imp_?ChangeACL@CAccessCard@iop@@UEAAXPEBE@Z:PANYARGS
?ChangeACL@CAccessCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?ChangeACL@CAccessCard@iop@@UEAAXPEBE@Z>
extern __imp_?ChangeACL@CCryptoCard@iop@@UEAAXPEBE@Z:PANYARGS
?ChangeACL@CCryptoCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?ChangeACL@CCryptoCard@iop@@UEAAXPEBE@Z>
extern __imp_?ChangeACL@CSmartCard@iop@@UEAAXPEBE@Z:PANYARGS
?ChangeACL@CSmartCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?ChangeACL@CSmartCard@iop@@UEAAXPEBE@Z>
extern __imp_?ChangeCHV@CAccessCard@iop@@UEAAXEPEBE0@Z:PANYARGS
?ChangeCHV@CAccessCard@iop@@UEAAXEPEBE0@Z TEXTEQU <__imp_?ChangeCHV@CAccessCard@iop@@UEAAXEPEBE0@Z>
extern __imp_?ChangeCHV@CAccessCard@iop@@UEAAXEPEBE@Z:PANYARGS
?ChangeCHV@CAccessCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?ChangeCHV@CAccessCard@iop@@UEAAXEPEBE@Z>
extern __imp_?ChangeCHV@CCryptoCard@iop@@UEAAXEPEBE0@Z:PANYARGS
?ChangeCHV@CCryptoCard@iop@@UEAAXEPEBE0@Z TEXTEQU <__imp_?ChangeCHV@CCryptoCard@iop@@UEAAXEPEBE0@Z>
extern __imp_?ChangeCHV@CCryptoCard@iop@@UEAAXEPEBE@Z:PANYARGS
?ChangeCHV@CCryptoCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?ChangeCHV@CCryptoCard@iop@@UEAAXEPEBE@Z>
extern __imp_?ChangeCHV@CSmartCard@iop@@UEAAXEPEBE0@Z:PANYARGS
?ChangeCHV@CSmartCard@iop@@UEAAXEPEBE0@Z TEXTEQU <__imp_?ChangeCHV@CSmartCard@iop@@UEAAXEPEBE0@Z>
extern __imp_?ChangeCHV@CSmartCard@iop@@UEAAXEPEBE@Z:PANYARGS
?ChangeCHV@CSmartCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?ChangeCHV@CSmartCard@iop@@UEAAXEPEBE@Z>
extern __imp_?ChangeTransportKey@CAccessCard@iop@@UEAAXPEBE@Z:PANYARGS
?ChangeTransportKey@CAccessCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?ChangeTransportKey@CAccessCard@iop@@UEAAXPEBE@Z>
extern __imp_?ChangeTransportKey@CCryptoCard@iop@@UEAAXPEBE@Z:PANYARGS
?ChangeTransportKey@CCryptoCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?ChangeTransportKey@CCryptoCard@iop@@UEAAXPEBE@Z>
extern __imp_?ChangeTransportKey@CSmartCard@iop@@UEAAXPEBE@Z:PANYARGS
?ChangeTransportKey@CSmartCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?ChangeTransportKey@CSmartCard@iop@@UEAAXPEBE@Z>
extern __imp_?ChangeUnblockKey@CAccessCard@iop@@UEAAXEPEBE@Z:PANYARGS
?ChangeUnblockKey@CAccessCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?ChangeUnblockKey@CAccessCard@iop@@UEAAXEPEBE@Z>
extern __imp_?ChangeUnblockKey@CCryptoCard@iop@@UEAAXEPEBE@Z:PANYARGS
?ChangeUnblockKey@CCryptoCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?ChangeUnblockKey@CCryptoCard@iop@@UEAAXEPEBE@Z>
extern __imp_?ChangeUnblockKey@CSmartCard@iop@@UEAAXEPEBE@Z:PANYARGS
?ChangeUnblockKey@CSmartCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?ChangeUnblockKey@CSmartCard@iop@@UEAAXEPEBE@Z>
extern __imp_?ChopTail@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ:PANYARGS
?ChopTail@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ TEXTEQU <__imp_?ChopTail@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ>
extern __imp_?Class@Exception@CSmartCard@iop@@QEBAEXZ:PANYARGS
?Class@Exception@CSmartCard@iop@@QEBAEXZ TEXTEQU <__imp_?Class@Exception@CSmartCard@iop@@QEBAEXZ>
extern __imp_?Clear@FilePath@iop@@QEAAXXZ:PANYARGS
?Clear@FilePath@iop@@QEAAXXZ TEXTEQU <__imp_?Clear@FilePath@iop@@QEAAXXZ>
extern __imp_?Clear@iop@@YAXAEAVCPrivateKeyBlob@1@@Z:PANYARGS
?Clear@iop@@YAXAEAVCPrivateKeyBlob@1@@Z TEXTEQU <__imp_?Clear@iop@@YAXAEAVCPrivateKeyBlob@1@@Z>
extern __imp_?Clear@iop@@YAXAEAVCPublicKeyBlob@1@@Z:PANYARGS
?Clear@iop@@YAXAEAVCPublicKeyBlob@1@@Z TEXTEQU <__imp_?Clear@iop@@YAXAEAVCPublicKeyBlob@1@@Z>
extern __imp_?ClearDataStore@?$SecureArray@D@scu@@AEAAXXZ:PANYARGS
?ClearDataStore@?$SecureArray@D@scu@@AEAAXXZ TEXTEQU <__imp_?ClearDataStore@?$SecureArray@D@scu@@AEAAXXZ>
extern __imp_?ClearDataStore@?$SecureArray@E@scu@@AEAAXXZ:PANYARGS
?ClearDataStore@?$SecureArray@E@scu@@AEAAXXZ TEXTEQU <__imp_?ClearDataStore@?$SecureArray@E@scu@@AEAAXXZ>
extern __imp_?Clone@?$ExcTemplate@$01K@scu@@UEBAPEAVException@2@XZ:PANYARGS
?Clone@?$ExcTemplate@$01K@scu@@UEBAPEAVException@2@XZ TEXTEQU <__imp_?Clone@?$ExcTemplate@$01K@scu@@UEBAPEAVException@2@XZ>
extern __imp_?Clone@Exception@CSmartCard@iop@@UEBAPEAV1scu@@XZ:PANYARGS
?Clone@Exception@CSmartCard@iop@@UEBAPEAV1scu@@XZ TEXTEQU <__imp_?Clone@Exception@CSmartCard@iop@@UEBAPEAV1scu@@XZ>
extern __imp_?Clone@OsException@scu@@UEBAPEAVException@2@XZ:PANYARGS
?Clone@OsException@scu@@UEBAPEAVException@2@XZ TEXTEQU <__imp_?Clone@OsException@scu@@UEBAPEAVException@2@XZ>
extern __imp_?Components@FilePath@iop@@QEAA?AV?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@XZ:PANYARGS
?Components@FilePath@iop@@QEAA?AV?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@XZ TEXTEQU <__imp_?Components@FilePath@iop@@QEAA?AV?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@XZ>
extern __imp_?Connect@CIOP@iop@@QEAAPEAVCSmartCard@2@PEBD_N@Z:PANYARGS
?Connect@CIOP@iop@@QEAAPEAVCSmartCard@2@PEBD_N@Z TEXTEQU <__imp_?Connect@CIOP@iop@@QEAAPEAVCSmartCard@2@PEBD_N@Z>
extern __imp_?CreateCard@CIOP@iop@@AEAAPEAVCSmartCard@2@PEBEK_KPEBDK@Z:PANYARGS
?CreateCard@CIOP@iop@@AEAAPEAVCSmartCard@2@PEBEK_KPEBDK@Z TEXTEQU <__imp_?CreateCard@CIOP@iop@@AEAAPEAVCSmartCard@2@PEBEK_KPEBDK@Z>
extern __imp_?CreateFileA@CAccessCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z:PANYARGS
?CreateFileA@CAccessCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z TEXTEQU <__imp_?CreateFileA@CAccessCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z>
extern __imp_?CreateFileA@CCryptoCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z:PANYARGS
?CreateFileA@CCryptoCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z TEXTEQU <__imp_?CreateFileA@CCryptoCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z>
extern __imp_?CreateFileA@CSmartCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z:PANYARGS
?CreateFileA@CSmartCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z TEXTEQU <__imp_?CreateFileA@CSmartCard@iop@@UEAAXPEBUFILE_HEADER@2@@Z>
extern __imp_?CriticalSection@CIOPLock@iop@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ:PANYARGS
?CriticalSection@CIOPLock@iop@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ TEXTEQU <__imp_?CriticalSection@CIOPLock@iop@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ>
extern __imp_?CryptoToAccessACL@CCryptoCard@iop@@IEAAXPEAEEEE@Z:PANYARGS
?CryptoToAccessACL@CCryptoCard@iop@@IEAAXPEAEEEE@Z TEXTEQU <__imp_?CryptoToAccessACL@CCryptoCard@iop@@IEAAXPEAEEEE@Z>
extern __imp_?DecrementRefCount@CIOPLock@iop@@QEAAXXZ:PANYARGS
?DecrementRefCount@CIOPLock@iop@@QEAAXXZ TEXTEQU <__imp_?DecrementRefCount@CIOPLock@iop@@QEAAXXZ>
extern __imp_?DefaultDispatchError@CAccessCard@iop@@MEBAXEEG@Z:PANYARGS
?DefaultDispatchError@CAccessCard@iop@@MEBAXEEG@Z TEXTEQU <__imp_?DefaultDispatchError@CAccessCard@iop@@MEBAXEEG@Z>
extern __imp_?DefaultDispatchError@CCryptoCard@iop@@MEBAXEEG@Z:PANYARGS
?DefaultDispatchError@CCryptoCard@iop@@MEBAXEEG@Z TEXTEQU <__imp_?DefaultDispatchError@CCryptoCard@iop@@MEBAXEEG@Z>
extern __imp_?DefaultDispatchError@CSmartCard@iop@@MEBAXEEG@Z:PANYARGS
?DefaultDispatchError@CSmartCard@iop@@MEBAXEEG@Z TEXTEQU <__imp_?DefaultDispatchError@CSmartCard@iop@@MEBAXEEG@Z>
extern __imp_?DeleteApplet@CAccessCard@iop@@UEAAXXZ:PANYARGS
?DeleteApplet@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?DeleteApplet@CAccessCard@iop@@UEAAXXZ>
extern __imp_?DeleteApplet@CSmartCard@iop@@UEAAXXZ:PANYARGS
?DeleteApplet@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?DeleteApplet@CSmartCard@iop@@UEAAXXZ>
extern __imp_?DeleteFileA@CAccessCard@iop@@UEAAXG@Z:PANYARGS
?DeleteFileA@CAccessCard@iop@@UEAAXG@Z TEXTEQU <__imp_?DeleteFileA@CAccessCard@iop@@UEAAXG@Z>
extern __imp_?DeleteFileA@CCryptoCard@iop@@UEAAXG@Z:PANYARGS
?DeleteFileA@CCryptoCard@iop@@UEAAXG@Z TEXTEQU <__imp_?DeleteFileA@CCryptoCard@iop@@UEAAXG@Z>
extern __imp_?DeleteFileA@CSmartCard@iop@@UEAAXG@Z:PANYARGS
?DeleteFileA@CSmartCard@iop@@UEAAXG@Z TEXTEQU <__imp_?DeleteFileA@CSmartCard@iop@@UEAAXG@Z>
extern __imp_?Description@?$ExcTemplate@$01K@scu@@UEBAPEBDXZ:PANYARGS
?Description@?$ExcTemplate@$01K@scu@@UEBAPEBDXZ TEXTEQU <__imp_?Description@?$ExcTemplate@$01K@scu@@UEBAPEBDXZ>
extern __imp_?Description@Exception@CSmartCard@iop@@UEBAPEBDXZ:PANYARGS
?Description@Exception@CSmartCard@iop@@UEBAPEBDXZ TEXTEQU <__imp_?Description@Exception@CSmartCard@iop@@UEBAPEBDXZ>
extern __imp_?Description@Exception@scu@@UEBAPEBDXZ:PANYARGS
?Description@Exception@scu@@UEBAPEBDXZ TEXTEQU <__imp_?Description@Exception@scu@@UEBAPEBDXZ>
extern __imp_?Description@OsException@scu@@UEBAPEBDXZ:PANYARGS
?Description@OsException@scu@@UEBAPEBDXZ TEXTEQU <__imp_?Description@OsException@scu@@UEBAPEBDXZ>
extern __imp_?Directory@CAccessCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z:PANYARGS
?Directory@CAccessCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z TEXTEQU <__imp_?Directory@CAccessCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z>
extern __imp_?Directory@CCryptoCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z:PANYARGS
?Directory@CCryptoCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z TEXTEQU <__imp_?Directory@CCryptoCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z>
extern __imp_?Directory@CSmartCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z:PANYARGS
?Directory@CSmartCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z TEXTEQU <__imp_?Directory@CSmartCard@iop@@UEAAXEPEAUFILE_HEADER@2@@Z>
extern __imp_?Dirty@CSmartCard@iop@@QEAAX_N@Z:PANYARGS
?Dirty@CSmartCard@iop@@QEAAX_N@Z TEXTEQU <__imp_?Dirty@CSmartCard@iop@@QEAAX_N@Z>
extern __imp_?Dirty@CSmartCard@iop@@QEBA_NXZ:PANYARGS
?Dirty@CSmartCard@iop@@QEBA_NXZ TEXTEQU <__imp_?Dirty@CSmartCard@iop@@QEBA_NXZ>
extern __imp_?DispatchError@CAccessCard@iop@@MEBAXEEG@Z:PANYARGS
?DispatchError@CAccessCard@iop@@MEBAXEEG@Z TEXTEQU <__imp_?DispatchError@CAccessCard@iop@@MEBAXEEG@Z>
extern __imp_?DispatchError@CCryptoCard@iop@@MEBAXEEG@Z:PANYARGS
?DispatchError@CCryptoCard@iop@@MEBAXEEG@Z TEXTEQU <__imp_?DispatchError@CCryptoCard@iop@@MEBAXEEG@Z>
extern __imp_?DispatchError@CSmartCard@iop@@MEBAXEEG@Z:PANYARGS
?DispatchError@CSmartCard@iop@@MEBAXEEG@Z TEXTEQU <__imp_?DispatchError@CSmartCard@iop@@MEBAXEEG@Z>
extern __imp_?DoReadBlock@CAccessCard@iop@@MEAAXGPEAEE@Z:PANYARGS
?DoReadBlock@CAccessCard@iop@@MEAAXGPEAEE@Z TEXTEQU <__imp_?DoReadBlock@CAccessCard@iop@@MEAAXGPEAEE@Z>
extern __imp_?DoReadBlock@CCryptoCard@iop@@MEAAXGPEAEE@Z:PANYARGS
?DoReadBlock@CCryptoCard@iop@@MEAAXGPEAEE@Z TEXTEQU <__imp_?DoReadBlock@CCryptoCard@iop@@MEAAXGPEAEE@Z>
extern __imp_?DoWriteBlock@CAccessCard@iop@@MEAAXGPEBEE@Z:PANYARGS
?DoWriteBlock@CAccessCard@iop@@MEAAXGPEBEE@Z TEXTEQU <__imp_?DoWriteBlock@CAccessCard@iop@@MEAAXGPEBEE@Z>
extern __imp_?DoWriteBlock@CCryptoCard@iop@@MEAAXGPEBEE@Z:PANYARGS
?DoWriteBlock@CCryptoCard@iop@@MEAAXGPEBEE@Z TEXTEQU <__imp_?DoWriteBlock@CCryptoCard@iop@@MEAAXGPEBEE@Z>
extern __imp_?Error@?$ExcTemplate@$01K@scu@@UEBAKXZ:PANYARGS
?Error@?$ExcTemplate@$01K@scu@@UEBAKXZ TEXTEQU <__imp_?Error@?$ExcTemplate@$01K@scu@@UEBAKXZ>
extern __imp_?Error@Exception@CSmartCard@iop@@UEBAKXZ:PANYARGS
?Error@Exception@CSmartCard@iop@@UEBAKXZ TEXTEQU <__imp_?Error@Exception@CSmartCard@iop@@UEBAKXZ>
extern __imp_?ExecuteInstall@CAccessCard@iop@@UEAAXPEBEE@Z:PANYARGS
?ExecuteInstall@CAccessCard@iop@@UEAAXPEBEE@Z TEXTEQU <__imp_?ExecuteInstall@CAccessCard@iop@@UEAAXPEBEE@Z>
extern __imp_?ExecuteInstall@CSmartCard@iop@@UEAAXPEBEE@Z:PANYARGS
?ExecuteInstall@CSmartCard@iop@@UEAAXPEBEE@Z TEXTEQU <__imp_?ExecuteInstall@CSmartCard@iop@@UEAAXPEBEE@Z>
extern __imp_?ExecuteMain@CAccessCard@iop@@UEAAXXZ:PANYARGS
?ExecuteMain@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?ExecuteMain@CAccessCard@iop@@UEAAXXZ>
extern __imp_?ExecuteMain@CSmartCard@iop@@UEAAXXZ:PANYARGS
?ExecuteMain@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?ExecuteMain@CSmartCard@iop@@UEAAXXZ>
extern __imp_?ExternalAuth@CAccessCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z:PANYARGS
?ExternalAuth@CAccessCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z TEXTEQU <__imp_?ExternalAuth@CAccessCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z>
extern __imp_?ExternalAuth@CCryptoCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z:PANYARGS
?ExternalAuth@CCryptoCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z TEXTEQU <__imp_?ExternalAuth@CCryptoCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z>
extern __imp_?ExternalAuth@CSmartCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z:PANYARGS
?ExternalAuth@CSmartCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z TEXTEQU <__imp_?ExternalAuth@CSmartCard@iop@@UEAAXW4KeyType@2@EEPEBE@Z>
extern __imp_?Facility@Exception@scu@@QEBA?AW4FacilityCode@12@XZ:PANYARGS
?Facility@Exception@scu@@QEBA?AW4FacilityCode@12@XZ TEXTEQU <__imp_?Facility@Exception@scu@@QEBA?AW4FacilityCode@12@XZ>
extern __imp_?FireEvents@CSmartCard@iop@@QEAAXHKPEAE@Z:PANYARGS
?FireEvents@CSmartCard@iop@@QEAAXHKPEAE@Z TEXTEQU <__imp_?FireEvents@CSmartCard@iop@@QEAAXHKPEAE@Z>
extern __imp_?FormatPath@CSmartCard@iop@@IEAAEPEADPEBD@Z:PANYARGS
?FormatPath@CSmartCard@iop@@IEAAEPEADPEBD@Z TEXTEQU <__imp_?FormatPath@CSmartCard@iop@@IEAAEPEADPEBD@Z>
extern __imp_?GenerateKeyPair@CCryptoCard@iop@@UEAA?AVCPublicKeyBlob@2@PEBEGEW4KeyType@2@@Z:PANYARGS
?GenerateKeyPair@CCryptoCard@iop@@UEAA?AVCPublicKeyBlob@2@PEBEGEW4KeyType@2@@Z TEXTEQU <__imp_?GenerateKeyPair@CCryptoCard@iop@@UEAA?AVCPublicKeyBlob@2@PEBEGEW4KeyType@2@@Z>
extern __imp_?GenerateKeyPair@CSmartCard@iop@@UEAA?AVCPublicKeyBlob@2@PEBEGEW4KeyType@2@@Z:PANYARGS
?GenerateKeyPair@CSmartCard@iop@@UEAA?AVCPublicKeyBlob@2@PEBEGEW4KeyType@2@@Z TEXTEQU <__imp_?GenerateKeyPair@CSmartCard@iop@@UEAA?AVCPublicKeyBlob@2@PEBEGEW4KeyType@2@@Z>
extern __imp_?GetACL@CCryptoCard@iop@@UEAAXPEAE@Z:PANYARGS
?GetACL@CCryptoCard@iop@@UEAAXPEAE@Z TEXTEQU <__imp_?GetACL@CCryptoCard@iop@@UEAAXPEAE@Z>
extern __imp_?GetACL@CSmartCard@iop@@UEAAXPEAE@Z:PANYARGS
?GetACL@CSmartCard@iop@@UEAAXPEAE@Z TEXTEQU <__imp_?GetACL@CSmartCard@iop@@UEAAXPEAE@Z>
extern __imp_?GetChallenge@CAccessCard@iop@@UEAAXKPEAE@Z:PANYARGS
?GetChallenge@CAccessCard@iop@@UEAAXKPEAE@Z TEXTEQU <__imp_?GetChallenge@CAccessCard@iop@@UEAAXKPEAE@Z>
extern __imp_?GetChallenge@CCryptoCard@iop@@UEAAXKPEAE@Z:PANYARGS
?GetChallenge@CCryptoCard@iop@@UEAAXKPEAE@Z TEXTEQU <__imp_?GetChallenge@CCryptoCard@iop@@UEAAXKPEAE@Z>
extern __imp_?GetChallenge@CSmartCard@iop@@UEAAXKPEAE@Z:PANYARGS
?GetChallenge@CSmartCard@iop@@UEAAXKPEAE@Z TEXTEQU <__imp_?GetChallenge@CSmartCard@iop@@UEAAXKPEAE@Z>
extern __imp_?GetCurrentDir@CSmartCard@iop@@QEAAXPEAD@Z:PANYARGS
?GetCurrentDir@CSmartCard@iop@@QEAAXPEAD@Z TEXTEQU <__imp_?GetCurrentDir@CSmartCard@iop@@QEAAXPEAD@Z>
extern __imp_?GetCurrentFile@CSmartCard@iop@@QEAAXPEAD@Z:PANYARGS
?GetCurrentFile@CSmartCard@iop@@QEAAXPEAD@Z TEXTEQU <__imp_?GetCurrentFile@CSmartCard@iop@@QEAAXPEAD@Z>
extern __imp_?GetResponse@CSmartCard@iop@@UEAAXEEPEAE@Z:PANYARGS
?GetResponse@CSmartCard@iop@@UEAAXEEPEAE@Z TEXTEQU <__imp_?GetResponse@CSmartCard@iop@@UEAAXEEPEAE@Z>
extern __imp_?GetSerial@CAccessCard@iop@@UEAAXPEAEAEA_K@Z:PANYARGS
?GetSerial@CAccessCard@iop@@UEAAXPEAEAEA_K@Z TEXTEQU <__imp_?GetSerial@CAccessCard@iop@@UEAAXPEAEAEA_K@Z>
extern __imp_?GetSerial@CCryptoCard@iop@@UEAAXPEAEAEA_K@Z:PANYARGS
?GetSerial@CCryptoCard@iop@@UEAAXPEAEAEA_K@Z TEXTEQU <__imp_?GetSerial@CCryptoCard@iop@@UEAAXPEAEAEA_K@Z>
extern __imp_?GetSerial@CSmartCard@iop@@UEAAXPEAEAEA_K@Z:PANYARGS
?GetSerial@CSmartCard@iop@@UEAAXPEAEAEA_K@Z TEXTEQU <__imp_?GetSerial@CSmartCard@iop@@UEAAXPEAEAEA_K@Z>
extern __imp_?GetShortID@FilePathComponent@iop@@QEAAGXZ:PANYARGS
?GetShortID@FilePathComponent@iop@@QEAAGXZ TEXTEQU <__imp_?GetShortID@FilePathComponent@iop@@QEAAGXZ>
extern __imp_?GetState@CSmartCard@iop@@QEAAXAEAK0@Z:PANYARGS
?GetState@CSmartCard@iop@@QEAAXAEAK0@Z TEXTEQU <__imp_?GetState@CSmartCard@iop@@QEAAXAEAK0@Z>
extern __imp_?GetStringID@FilePathComponent@iop@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ:PANYARGS
?GetStringID@FilePathComponent@iop@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ TEXTEQU <__imp_?GetStringID@FilePathComponent@iop@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ>
extern __imp_?GetStringPath@FilePath@iop@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ:PANYARGS
?GetStringPath@FilePath@iop@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ TEXTEQU <__imp_?GetStringPath@FilePath@iop@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ>
extern __imp_?GreatestCommonPrefix@FilePath@iop@@QEAA?AV12@AEAV12@@Z:PANYARGS
?GreatestCommonPrefix@FilePath@iop@@QEAA?AV12@AEAV12@@Z TEXTEQU <__imp_?GreatestCommonPrefix@FilePath@iop@@QEAA?AV12@AEAV12@@Z>
extern __imp_?HasProperty@CSmartCard@iop@@QEAA_NG@Z:PANYARGS
?HasProperty@CSmartCard@iop@@QEAA_NG@Z TEXTEQU <__imp_?HasProperty@CSmartCard@iop@@QEAA_NG@Z>
extern __imp_?Head@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ:PANYARGS
?Head@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ TEXTEQU <__imp_?Head@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ>
extern __imp_?IncrementRefCount@CIOPLock@iop@@QEAAXXZ:PANYARGS
?IncrementRefCount@CIOPLock@iop@@QEAAXXZ TEXTEQU <__imp_?IncrementRefCount@CIOPLock@iop@@QEAAXXZ>
extern __imp_?Init@CIOPLock@iop@@QEAAXPEAVCSmartCard@2@@Z:PANYARGS
?Init@CIOPLock@iop@@QEAAXPEAVCSmartCard@2@@Z TEXTEQU <__imp_?Init@CIOPLock@iop@@QEAAXPEAVCSmartCard@2@@Z>
extern __imp_?InitIOPSecurityAttrs@CIOP@iop@@SAXPEAVCSecurityAttributes@@@Z:PANYARGS
?InitIOPSecurityAttrs@CIOP@iop@@SAXPEAVCSecurityAttributes@@@Z TEXTEQU <__imp_?InitIOPSecurityAttrs@CIOP@iop@@SAXPEAVCSecurityAttributes@@@Z>
extern __imp_?Ins@Exception@CSmartCard@iop@@QEBAEXZ:PANYARGS
?Ins@Exception@CSmartCard@iop@@QEBAEXZ TEXTEQU <__imp_?Ins@Exception@CSmartCard@iop@@QEBAEXZ>
extern __imp_?InternalAuth@CAccessCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z:PANYARGS
?InternalAuth@CAccessCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z TEXTEQU <__imp_?InternalAuth@CAccessCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z>
extern __imp_?InternalAuth@CCryptoCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z:PANYARGS
?InternalAuth@CCryptoCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z TEXTEQU <__imp_?InternalAuth@CCryptoCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z>
extern __imp_?InternalAuth@CSmartCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z:PANYARGS
?InternalAuth@CSmartCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z TEXTEQU <__imp_?InternalAuth@CSmartCard@iop@@UEAAXW4KeyType@2@EEPEBEPEAE@Z>
extern __imp_?IsEmpty@FilePath@iop@@QEAA_NXZ:PANYARGS
?IsEmpty@FilePath@iop@@QEAA_NXZ TEXTEQU <__imp_?IsEmpty@FilePath@iop@@QEAA_NXZ>
extern __imp_?ListKnownCards@CIOP@iop@@SAXPEADAEAH@Z:PANYARGS
?ListKnownCards@CIOP@iop@@SAXPEADAEAH@Z TEXTEQU <__imp_?ListKnownCards@CIOP@iop@@SAXPEADAEAH@Z>
extern __imp_?ListReaders@CIOP@iop@@QEAAXPEADAEAH@Z:PANYARGS
?ListReaders@CIOP@iop@@QEAAXPEADAEAH@Z TEXTEQU <__imp_?ListReaders@CIOP@iop@@QEAAXPEADAEAH@Z>
extern __imp_?Lock@CSmartCard@iop@@QEAAPEAVCIOPLock@2@XZ:PANYARGS
?Lock@CSmartCard@iop@@QEAAPEAVCIOPLock@2@XZ TEXTEQU <__imp_?Lock@CSmartCard@iop@@QEAAPEAVCIOPLock@2@XZ>
extern __imp_?LogoutAll@CAccessCard@iop@@UEAAXXZ:PANYARGS
?LogoutAll@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?LogoutAll@CAccessCard@iop@@UEAAXXZ>
extern __imp_?LogoutAll@CCryptoCard@iop@@UEAAXXZ:PANYARGS
?LogoutAll@CCryptoCard@iop@@UEAAXXZ TEXTEQU <__imp_?LogoutAll@CCryptoCard@iop@@UEAAXXZ>
extern __imp_?LogoutAll@CSmartCard@iop@@UEAAXXZ:PANYARGS
?LogoutAll@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?LogoutAll@CSmartCard@iop@@UEAAXXZ>
extern __imp_?MutexHandle@CIOPLock@iop@@QEAAPEAXXZ:PANYARGS
?MutexHandle@CIOPLock@iop@@QEAAPEAXXZ TEXTEQU <__imp_?MutexHandle@CIOPLock@iop@@QEAAPEAXXZ>
extern __imp_?NumComponents@FilePath@iop@@QEAAEXZ:PANYARGS
?NumComponents@FilePath@iop@@QEAAEXZ TEXTEQU <__imp_?NumComponents@FilePath@iop@@QEAAEXZ>
extern __imp_?ProcessReturnStatus@CSmartCard@iop@@AEAAXEEG@Z:PANYARGS
?ProcessReturnStatus@CSmartCard@iop@@AEAAXEEG@Z TEXTEQU <__imp_?ProcessReturnStatus@CSmartCard@iop@@AEAAXEEG@Z>
extern __imp_?Raise@?$ExcTemplate@$01K@scu@@UEBAXXZ:PANYARGS
?Raise@?$ExcTemplate@$01K@scu@@UEBAXXZ TEXTEQU <__imp_?Raise@?$ExcTemplate@$01K@scu@@UEBAXXZ>
extern __imp_?Raise@Exception@CSmartCard@iop@@UEBAXXZ:PANYARGS
?Raise@Exception@CSmartCard@iop@@UEBAXXZ TEXTEQU <__imp_?Raise@Exception@CSmartCard@iop@@UEBAXXZ>
extern __imp_?Raise@OsException@scu@@UEBAXXZ:PANYARGS
?Raise@OsException@scu@@UEBAXXZ TEXTEQU <__imp_?Raise@OsException@scu@@UEBAXXZ>
extern __imp_?ReConnect@CSmartCard@iop@@QEAAXXZ:PANYARGS
?ReConnect@CSmartCard@iop@@QEAAXXZ TEXTEQU <__imp_?ReConnect@CSmartCard@iop@@QEAAXXZ>
extern __imp_?ReadBinary@CSmartCard@iop@@UEAAXGGPEAE@Z:PANYARGS
?ReadBinary@CSmartCard@iop@@UEAAXGGPEAE@Z TEXTEQU <__imp_?ReadBinary@CSmartCard@iop@@UEAAXGGPEAE@Z>
extern __imp_?ReadPublicKey@CAccessCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z:PANYARGS
?ReadPublicKey@CAccessCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z TEXTEQU <__imp_?ReadPublicKey@CAccessCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z>
extern __imp_?ReadPublicKey@CCryptoCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z:PANYARGS
?ReadPublicKey@CCryptoCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z TEXTEQU <__imp_?ReadPublicKey@CCryptoCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z>
extern __imp_?ReadPublicKey@CSmartCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z:PANYARGS
?ReadPublicKey@CSmartCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z TEXTEQU <__imp_?ReadPublicKey@CSmartCard@iop@@UEAAXPEAVCPublicKeyBlob@2@E@Z>
extern __imp_?ReadRecord@CAccessCard@iop@@UEAAXEEEPEAE@Z:PANYARGS
?ReadRecord@CAccessCard@iop@@UEAAXEEEPEAE@Z TEXTEQU <__imp_?ReadRecord@CAccessCard@iop@@UEAAXEEEPEAE@Z>
extern __imp_?ReadRecord@CSmartCard@iop@@UEAAXEEEPEAE@Z:PANYARGS
?ReadRecord@CSmartCard@iop@@UEAAXEEEPEAE@Z TEXTEQU <__imp_?ReadRecord@CSmartCard@iop@@UEAAXEEEPEAE@Z>
extern __imp_?RefCount@CIOPLock@iop@@QEAAJXZ:PANYARGS
?RefCount@CIOPLock@iop@@QEAAJXZ TEXTEQU <__imp_?RefCount@CIOPLock@iop@@QEAAJXZ>
extern __imp_?RegisterCard@CIOP@iop@@SAXPEBDPEBEE1E1W4cardType@2@@Z:PANYARGS
?RegisterCard@CIOP@iop@@SAXPEBDPEBEE1E1W4cardType@2@@Z TEXTEQU <__imp_?RegisterCard@CIOP@iop@@SAXPEBDPEBEE1E1W4cardType@2@@Z>
extern __imp_?RegisterDefaultCards@CIOP@iop@@SAXXZ:PANYARGS
?RegisterDefaultCards@CIOP@iop@@SAXXZ TEXTEQU <__imp_?RegisterDefaultCards@CIOP@iop@@SAXXZ>
extern __imp_?RegisterEvent@CSmartCard@iop@@QEAAKP6AXPEAXHKPEAE@Z0@Z:PANYARGS
?RegisterEvent@CSmartCard@iop@@QEAAKP6AXPEAXHKPEAE@Z0@Z TEXTEQU <__imp_?RegisterEvent@CSmartCard@iop@@QEAAKP6AXPEAXHKPEAE@Z0@Z>
extern __imp_?RequireSelect@CSmartCard@iop@@IEAAXXZ:PANYARGS
?RequireSelect@CSmartCard@iop@@IEAAXXZ TEXTEQU <__imp_?RequireSelect@CSmartCard@iop@@IEAAXXZ>
extern __imp_?ResetCard@CSmartCard@iop@@QEAAXXZ:PANYARGS
?ResetCard@CSmartCard@iop@@QEAAXXZ TEXTEQU <__imp_?ResetCard@CSmartCard@iop@@QEAAXXZ>
extern __imp_?ResetInstance@CAccessCard@iop@@UEAAXXZ:PANYARGS
?ResetInstance@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?ResetInstance@CAccessCard@iop@@UEAAXXZ>
extern __imp_?ResetInstance@CSmartCard@iop@@UEAAXXZ:PANYARGS
?ResetInstance@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?ResetInstance@CSmartCard@iop@@UEAAXXZ>
extern __imp_?ResetProgram@CAccessCard@iop@@UEAAXXZ:PANYARGS
?ResetProgram@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?ResetProgram@CAccessCard@iop@@UEAAXXZ>
extern __imp_?ResetProgram@CSmartCard@iop@@UEAAXXZ:PANYARGS
?ResetProgram@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?ResetProgram@CSmartCard@iop@@UEAAXXZ>
extern __imp_?ResetSelect@CSmartCard@iop@@QEAAXXZ:PANYARGS
?ResetSelect@CSmartCard@iop@@QEAAXXZ TEXTEQU <__imp_?ResetSelect@CSmartCard@iop@@QEAAXXZ>
extern __imp_?ResponseLengthAvailable@CSmartCard@iop@@IEAAXE@Z:PANYARGS
?ResponseLengthAvailable@CSmartCard@iop@@IEAAXE@Z TEXTEQU <__imp_?ResponseLengthAvailable@CSmartCard@iop@@IEAAXE@Z>
extern __imp_?ResponseLengthAvailable@CSmartCard@iop@@IEBAEXZ:PANYARGS
?ResponseLengthAvailable@CSmartCard@iop@@IEBAEXZ TEXTEQU <__imp_?ResponseLengthAvailable@CSmartCard@iop@@IEBAEXZ>
extern __imp_?Root@FilePath@iop@@SA?AV12@XZ:PANYARGS
?Root@FilePath@iop@@SA?AV12@XZ TEXTEQU <__imp_?Root@FilePath@iop@@SA?AV12@XZ>
extern __imp_?Select@CAccessCard@iop@@MEAAXG@Z:PANYARGS
?Select@CAccessCard@iop@@MEAAXG@Z TEXTEQU <__imp_?Select@CAccessCard@iop@@MEAAXG@Z>
extern __imp_?Select@CAccessCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z:PANYARGS
?Select@CAccessCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z TEXTEQU <__imp_?Select@CAccessCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z>
extern __imp_?Select@CCryptoCard@iop@@MEAAXG@Z:PANYARGS
?Select@CCryptoCard@iop@@MEAAXG@Z TEXTEQU <__imp_?Select@CCryptoCard@iop@@MEAAXG@Z>
extern __imp_?Select@CCryptoCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z:PANYARGS
?Select@CCryptoCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z TEXTEQU <__imp_?Select@CCryptoCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z>
extern __imp_?Select@CSmartCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z:PANYARGS
?Select@CSmartCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z TEXTEQU <__imp_?Select@CSmartCard@iop@@UEAAXPEBDPEAUFILE_HEADER@2@_N@Z>
extern __imp_?SelectCardlet@CAccessCard@iop@@UEAAXPEBEE@Z:PANYARGS
?SelectCardlet@CAccessCard@iop@@UEAAXPEBEE@Z TEXTEQU <__imp_?SelectCardlet@CAccessCard@iop@@UEAAXPEBEE@Z>
extern __imp_?SelectCardlet@CSmartCard@iop@@UEAAXPEBEE@Z:PANYARGS
?SelectCardlet@CSmartCard@iop@@UEAAXPEBEE@Z TEXTEQU <__imp_?SelectCardlet@CSmartCard@iop@@UEAAXPEBEE@Z>
extern __imp_?SelectLoader@CAccessCard@iop@@UEAAXXZ:PANYARGS
?SelectLoader@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?SelectLoader@CAccessCard@iop@@UEAAXXZ>
extern __imp_?SelectLoader@CSmartCard@iop@@UEAAXXZ:PANYARGS
?SelectLoader@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?SelectLoader@CSmartCard@iop@@UEAAXXZ>
extern __imp_?SelectParent@CAccessCard@iop@@UEAAXXZ:PANYARGS
?SelectParent@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?SelectParent@CAccessCard@iop@@UEAAXXZ>
extern __imp_?SelectParent@CCryptoCard@iop@@UEAAXXZ:PANYARGS
?SelectParent@CCryptoCard@iop@@UEAAXXZ TEXTEQU <__imp_?SelectParent@CCryptoCard@iop@@UEAAXXZ>
extern __imp_?SelectParent@CSmartCard@iop@@UEAAXXZ:PANYARGS
?SelectParent@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?SelectParent@CSmartCard@iop@@UEAAXXZ>
extern __imp_?SendCardAPDU@CSmartCard@iop@@QEAAXEEEEEPEBEEPEAE@Z:PANYARGS
?SendCardAPDU@CSmartCard@iop@@QEAAXEEEEEPEBEEPEAE@Z TEXTEQU <__imp_?SendCardAPDU@CSmartCard@iop@@QEAAXEEEEEPEBEEPEAE@Z>
extern __imp_?SetCurrentAsLoader@CAccessCard@iop@@UEAAXXZ:PANYARGS
?SetCurrentAsLoader@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?SetCurrentAsLoader@CAccessCard@iop@@UEAAXXZ>
extern __imp_?SetCurrentAsLoader@CSmartCard@iop@@UEAAXXZ:PANYARGS
?SetCurrentAsLoader@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?SetCurrentAsLoader@CSmartCard@iop@@UEAAXXZ>
extern __imp_?SetDefaultAsLoader@CAccessCard@iop@@UEAAXXZ:PANYARGS
?SetDefaultAsLoader@CAccessCard@iop@@UEAAXXZ TEXTEQU <__imp_?SetDefaultAsLoader@CAccessCard@iop@@UEAAXXZ>
extern __imp_?SetDefaultAsLoader@CSmartCard@iop@@UEAAXXZ:PANYARGS
?SetDefaultAsLoader@CSmartCard@iop@@UEAAXXZ TEXTEQU <__imp_?SetDefaultAsLoader@CSmartCard@iop@@UEAAXXZ>
extern __imp_?SetupFromBuffer@?$SecureArray@D@scu@@AEAAXPEBD_K@Z:PANYARGS
?SetupFromBuffer@?$SecureArray@D@scu@@AEAAXPEBD_K@Z TEXTEQU <__imp_?SetupFromBuffer@?$SecureArray@D@scu@@AEAAXPEBD_K@Z>
extern __imp_?SetupFromBuffer@?$SecureArray@E@scu@@AEAAXPEBE_K@Z:PANYARGS
?SetupFromBuffer@?$SecureArray@E@scu@@AEAAXPEBE_K@Z TEXTEQU <__imp_?SetupFromBuffer@?$SecureArray@E@scu@@AEAAXPEBE_K@Z>
extern __imp_?SmartCard@CIOPLock@iop@@QEAAPEAVCSmartCard@2@XZ:PANYARGS
?SmartCard@CIOPLock@iop@@QEAAPEAVCSmartCard@2@XZ TEXTEQU <__imp_?SmartCard@CIOPLock@iop@@QEAAPEAVCSmartCard@2@XZ>
extern __imp_?Status@Exception@CSmartCard@iop@@QEBAGXZ:PANYARGS
?Status@Exception@CSmartCard@iop@@QEBAGXZ TEXTEQU <__imp_?Status@Exception@CSmartCard@iop@@QEBAGXZ>
extern __imp_?SupportLogout@CAccessCard@iop@@MEAA_NXZ:PANYARGS
?SupportLogout@CAccessCard@iop@@MEAA_NXZ TEXTEQU <__imp_?SupportLogout@CAccessCard@iop@@MEAA_NXZ>
extern __imp_?SupportLogout@CCryptoCard@iop@@MEAA_NXZ:PANYARGS
?SupportLogout@CCryptoCard@iop@@MEAA_NXZ TEXTEQU <__imp_?SupportLogout@CCryptoCard@iop@@MEAA_NXZ>
extern __imp_?Tail@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ:PANYARGS
?Tail@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ TEXTEQU <__imp_?Tail@FilePath@iop@@QEAA?AVFilePathComponent@2@XZ>
extern __imp_?UnblockCHV@CAccessCard@iop@@UEAAXEPEBE0@Z:PANYARGS
?UnblockCHV@CAccessCard@iop@@UEAAXEPEBE0@Z TEXTEQU <__imp_?UnblockCHV@CAccessCard@iop@@UEAAXEPEBE0@Z>
extern __imp_?UnblockCHV@CCryptoCard@iop@@UEAAXEPEBE0@Z:PANYARGS
?UnblockCHV@CCryptoCard@iop@@UEAAXEPEBE0@Z TEXTEQU <__imp_?UnblockCHV@CCryptoCard@iop@@UEAAXEPEBE0@Z>
extern __imp_?UnblockCHV@CSmartCard@iop@@UEAAXEPEBE0@Z:PANYARGS
?UnblockCHV@CSmartCard@iop@@UEAAXEPEBE0@Z TEXTEQU <__imp_?UnblockCHV@CSmartCard@iop@@UEAAXEPEBE0@Z>
extern __imp_?UnregisterEvent@CSmartCard@iop@@QEAA_NK@Z:PANYARGS
?UnregisterEvent@CSmartCard@iop@@QEAA_NK@Z TEXTEQU <__imp_?UnregisterEvent@CSmartCard@iop@@QEAA_NK@Z>
extern __imp_?UpdateRecord@CAccessCard@iop@@UEAAXEEEPEAE@Z:PANYARGS
?UpdateRecord@CAccessCard@iop@@UEAAXEEEPEAE@Z TEXTEQU <__imp_?UpdateRecord@CAccessCard@iop@@UEAAXEEEPEAE@Z>
extern __imp_?UpdateRecord@CSmartCard@iop@@UEAAXEEEPEAE@Z:PANYARGS
?UpdateRecord@CSmartCard@iop@@UEAAXEEEPEAE@Z TEXTEQU <__imp_?UpdateRecord@CSmartCard@iop@@UEAAXEEEPEAE@Z>
extern __imp_?ValidClassByte@CAccessCard@iop@@AEAA_NE@Z:PANYARGS
?ValidClassByte@CAccessCard@iop@@AEAA_NE@Z TEXTEQU <__imp_?ValidClassByte@CAccessCard@iop@@AEAA_NE@Z>
extern __imp_?ValidateProgram@CAccessCard@iop@@UEAAXPEBEE@Z:PANYARGS
?ValidateProgram@CAccessCard@iop@@UEAAXPEBEE@Z TEXTEQU <__imp_?ValidateProgram@CAccessCard@iop@@UEAAXPEBEE@Z>
extern __imp_?ValidateProgram@CSmartCard@iop@@UEAAXPEBEE@Z:PANYARGS
?ValidateProgram@CSmartCard@iop@@UEAAXPEBEE@Z TEXTEQU <__imp_?ValidateProgram@CSmartCard@iop@@UEAAXPEBEE@Z>
extern __imp_?VerifyCHV@CAccessCard@iop@@UEAAXEPEBE@Z:PANYARGS
?VerifyCHV@CAccessCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?VerifyCHV@CAccessCard@iop@@UEAAXEPEBE@Z>
extern __imp_?VerifyCHV@CCryptoCard@iop@@UEAAXEPEBE@Z:PANYARGS
?VerifyCHV@CCryptoCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?VerifyCHV@CCryptoCard@iop@@UEAAXEPEBE@Z>
extern __imp_?VerifyCHV@CSmartCard@iop@@UEAAXEPEBE@Z:PANYARGS
?VerifyCHV@CSmartCard@iop@@UEAAXEPEBE@Z TEXTEQU <__imp_?VerifyCHV@CSmartCard@iop@@UEAAXEPEBE@Z>
extern __imp_?VerifyKey@CAccessCard@iop@@UEAAXEEPEBE@Z:PANYARGS
?VerifyKey@CAccessCard@iop@@UEAAXEEPEBE@Z TEXTEQU <__imp_?VerifyKey@CAccessCard@iop@@UEAAXEEPEBE@Z>
extern __imp_?VerifyKey@CCryptoCard@iop@@UEAAXEEPEBE@Z:PANYARGS
?VerifyKey@CCryptoCard@iop@@UEAAXEEPEBE@Z TEXTEQU <__imp_?VerifyKey@CCryptoCard@iop@@UEAAXEEPEBE@Z>
extern __imp_?VerifyKey@CSmartCard@iop@@UEAAXEEPEBE@Z:PANYARGS
?VerifyKey@CSmartCard@iop@@UEAAXEEPEBE@Z TEXTEQU <__imp_?VerifyKey@CSmartCard@iop@@UEAAXEEPEBE@Z>
extern __imp_?VerifyTransportKey@CAccessCard@iop@@UEAAXPEBE@Z:PANYARGS
?VerifyTransportKey@CAccessCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?VerifyTransportKey@CAccessCard@iop@@UEAAXPEBE@Z>
extern __imp_?VerifyTransportKey@CCryptoCard@iop@@UEAAXPEBE@Z:PANYARGS
?VerifyTransportKey@CCryptoCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?VerifyTransportKey@CCryptoCard@iop@@UEAAXPEBE@Z>
extern __imp_?VerifyTransportKey@CSmartCard@iop@@UEAAXPEBE@Z:PANYARGS
?VerifyTransportKey@CSmartCard@iop@@UEAAXPEBE@Z TEXTEQU <__imp_?VerifyTransportKey@CSmartCard@iop@@UEAAXPEBE@Z>
extern __imp_?WaitForSCManager@CIOP@iop@@SA_NXZ:PANYARGS
?WaitForSCManager@CIOP@iop@@SA_NXZ TEXTEQU <__imp_?WaitForSCManager@CIOP@iop@@SA_NXZ>
extern __imp_?WriteBinary@CSmartCard@iop@@UEAAXGGPEBE@Z:PANYARGS
?WriteBinary@CSmartCard@iop@@UEAAXGGPEBE@Z TEXTEQU <__imp_?WriteBinary@CSmartCard@iop@@UEAAXGGPEBE@Z>
extern __imp_?WriteBlock@CSmartCard@iop@@AEAAXGPEBEE@Z:PANYARGS
?WriteBlock@CSmartCard@iop@@AEAAXGPEBEE@Z TEXTEQU <__imp_?WriteBlock@CSmartCard@iop@@AEAAXGPEBEE@Z>
extern __imp_?WritePrivateKey@CAccessCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z:PANYARGS
?WritePrivateKey@CAccessCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z TEXTEQU <__imp_?WritePrivateKey@CAccessCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z>
extern __imp_?WritePrivateKey@CCryptoCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z:PANYARGS
?WritePrivateKey@CCryptoCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z TEXTEQU <__imp_?WritePrivateKey@CCryptoCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z>
extern __imp_?WritePrivateKey@CSmartCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z:PANYARGS
?WritePrivateKey@CSmartCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z TEXTEQU <__imp_?WritePrivateKey@CSmartCard@iop@@UEAAXVCPrivateKeyBlob@2@E@Z>
extern __imp_?WritePublicKey@CAccessCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z:PANYARGS
?WritePublicKey@CAccessCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z TEXTEQU <__imp_?WritePublicKey@CAccessCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z>
extern __imp_?WritePublicKey@CCryptoCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z:PANYARGS
?WritePublicKey@CCryptoCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z TEXTEQU <__imp_?WritePublicKey@CCryptoCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z>
extern __imp_?WritePublicKey@CSmartCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z:PANYARGS
?WritePublicKey@CSmartCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z TEXTEQU <__imp_?WritePublicKey@CSmartCard@iop@@UEAAXVCPublicKeyBlob@2@E@Z>
extern __imp_?_Buynode@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAPEAU_Node@12@PEAU312@0@Z:PANYARGS
?_Buynode@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAPEAU_Node@12@PEAU312@0@Z TEXTEQU <__imp_?_Buynode@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAPEAU_Node@12@PEAU312@0@Z>
extern __imp_?_Destroy@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAXPEAPEAUEventInfo@iop@@0@Z:PANYARGS
?_Destroy@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAXPEAPEAUEventInfo@iop@@0@Z TEXTEQU <__imp_?_Destroy@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAXPEAPEAUEventInfo@iop@@0@Z>
extern __imp_?_Eq@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NAEBV12@@Z:PANYARGS
?_Eq@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NAEBV12@@Z TEXTEQU <__imp_?_Eq@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NAEBV12@@Z>
extern __imp_?_Freenode@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAXPEAU_Node@12@@Z:PANYARGS
?_Freenode@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAXPEAU_Node@12@@Z TEXTEQU <__imp_?_Freenode@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAXPEAU_Node@12@@Z>
extern __imp_?_Lt@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NAEBV12@@Z:PANYARGS
?_Lt@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NAEBV12@@Z TEXTEQU <__imp_?_Lt@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NAEBV12@@Z>
extern __imp_?_Splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAXViterator@12@AEAV12@00@Z:PANYARGS
?_Splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAXViterator@12@AEAV12@00@Z TEXTEQU <__imp_?_Splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEAAXViterator@12@AEAV12@00@Z>
extern __imp_?_Ucopy@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAPEAPEAUEventInfo@iop@@PEBQEAU34@0PEAPEAU34@@Z:PANYARGS
?_Ucopy@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAPEAPEAUEventInfo@iop@@PEBQEAU34@0PEAPEAU34@@Z TEXTEQU <__imp_?_Ucopy@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAPEAPEAUEventInfo@iop@@PEBQEAU34@0PEAPEAU34@@Z>
extern __imp_?_Ufill@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAXPEAPEAUEventInfo@iop@@_KAEBQEAU34@@Z:PANYARGS
?_Ufill@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAXPEAPEAUEventInfo@iop@@_KAEBQEAU34@@Z TEXTEQU <__imp_?_Ufill@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEAAXPEAPEAUEventInfo@iop@@_KAEBQEAU34@@Z>
extern __imp_?_Xran@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEBAXXZ:PANYARGS
?_Xran@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEBAXXZ TEXTEQU <__imp_?_Xran@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@IEBAXXZ>
extern __imp_?_Xran@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEBAXXZ:PANYARGS
?_Xran@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEBAXXZ TEXTEQU <__imp_?_Xran@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@IEBAXXZ>
extern __imp_?append@?$SecureArray@D@scu@@QEAAAEAV12@PEBD_K@Z:PANYARGS
?append@?$SecureArray@D@scu@@QEAAAEAV12@PEBD_K@Z TEXTEQU <__imp_?append@?$SecureArray@D@scu@@QEAAAEAV12@PEBD_K@Z>
extern __imp_?append@?$SecureArray@D@scu@@QEAAAEAV12@_KAEBD@Z:PANYARGS
?append@?$SecureArray@D@scu@@QEAAAEAV12@_KAEBD@Z TEXTEQU <__imp_?append@?$SecureArray@D@scu@@QEAAAEAV12@_KAEBD@Z>
extern __imp_?append@?$SecureArray@E@scu@@QEAAAEAV12@PEBE_K@Z:PANYARGS
?append@?$SecureArray@E@scu@@QEAAAEAV12@PEBE_K@Z TEXTEQU <__imp_?append@?$SecureArray@E@scu@@QEAAAEAV12@PEBE_K@Z>
extern __imp_?append@?$SecureArray@E@scu@@QEAAAEAV12@_KAEBE@Z:PANYARGS
?append@?$SecureArray@E@scu@@QEAAAEAV12@_KAEBE@Z TEXTEQU <__imp_?append@?$SecureArray@E@scu@@QEAAAEAV12@_KAEBE@Z>
extern __imp_?append_string@?$SecureArray@D@scu@@QEAAAEAV12@_KAEBD@Z:PANYARGS
?append_string@?$SecureArray@D@scu@@QEAAAEAV12@_KAEBD@Z TEXTEQU <__imp_?append_string@?$SecureArray@D@scu@@QEAAAEAV12@_KAEBD@Z>
extern __imp_?append_string@?$SecureArray@E@scu@@QEAAAEAV12@_KAEBE@Z:PANYARGS
?append_string@?$SecureArray@E@scu@@QEAAAEAV12@_KAEBE@Z TEXTEQU <__imp_?append_string@?$SecureArray@E@scu@@QEAAAEAV12@_KAEBE@Z>
extern __imp_?assign@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXVconst_iterator@12@0@Z:PANYARGS
?assign@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXVconst_iterator@12@0@Z TEXTEQU <__imp_?assign@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXVconst_iterator@12@0@Z>
extern __imp_?assign@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAX_KAEBVFilePathComponent@iop@@@Z:PANYARGS
?assign@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAX_KAEBVFilePathComponent@iop@@@Z TEXTEQU <__imp_?assign@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAX_KAEBVFilePathComponent@iop@@@Z>
extern __imp_?assign@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEBQEAUEventInfo@iop@@0@Z:PANYARGS
?assign@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEBQEAUEventInfo@iop@@0@Z TEXTEQU <__imp_?assign@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEBQEAUEventInfo@iop@@0@Z>
extern __imp_?assign@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_KAEBQEAUEventInfo@iop@@@Z:PANYARGS
?assign@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_KAEBQEAUEventInfo@iop@@@Z TEXTEQU <__imp_?assign@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_KAEBQEAUEventInfo@iop@@@Z>
extern __imp_?at@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@_K@Z:PANYARGS
?at@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@_K@Z TEXTEQU <__imp_?at@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@_K@Z>
extern __imp_?at@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@_K@Z:PANYARGS
?at@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@_K@Z TEXTEQU <__imp_?at@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@_K@Z>
extern __imp_?back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAVFilePathComponent@iop@@XZ:PANYARGS
?back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAVFilePathComponent@iop@@XZ TEXTEQU <__imp_?back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAVFilePathComponent@iop@@XZ>
extern __imp_?back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBAAEBVFilePathComponent@iop@@XZ:PANYARGS
?back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBAAEBVFilePathComponent@iop@@XZ TEXTEQU <__imp_?back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBAAEBVFilePathComponent@iop@@XZ>
extern __imp_?back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@XZ:PANYARGS
?back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@XZ TEXTEQU <__imp_?back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@XZ>
extern __imp_?back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@XZ:PANYARGS
?back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@XZ TEXTEQU <__imp_?back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@XZ>
extern __imp_?begin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@XZ:PANYARGS
?begin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@XZ TEXTEQU <__imp_?begin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@XZ>
extern __imp_?begin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AVconst_iterator@12@XZ:PANYARGS
?begin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AVconst_iterator@12@XZ TEXTEQU <__imp_?begin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AVconst_iterator@12@XZ>
extern __imp_?begin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@XZ:PANYARGS
?begin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@XZ TEXTEQU <__imp_?begin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@XZ>
extern __imp_?begin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAPEBQEAUEventInfo@iop@@XZ:PANYARGS
?begin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAPEBQEAUEventInfo@iop@@XZ TEXTEQU <__imp_?begin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAPEBQEAUEventInfo@iop@@XZ>
extern __imp_?capacity@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ:PANYARGS
?capacity@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ TEXTEQU <__imp_?capacity@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ>
extern __imp_?clear@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?clear@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?clear@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?clear@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?clear@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?clear@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?data@?$SecureArray@D@scu@@QEAAPEADXZ:PANYARGS
?data@?$SecureArray@D@scu@@QEAAPEADXZ TEXTEQU <__imp_?data@?$SecureArray@D@scu@@QEAAPEADXZ>
extern __imp_?data@?$SecureArray@D@scu@@QEBAPEBDXZ:PANYARGS
?data@?$SecureArray@D@scu@@QEBAPEBDXZ TEXTEQU <__imp_?data@?$SecureArray@D@scu@@QEBAPEBDXZ>
extern __imp_?data@?$SecureArray@E@scu@@QEAAPEAEXZ:PANYARGS
?data@?$SecureArray@E@scu@@QEAAPEAEXZ TEXTEQU <__imp_?data@?$SecureArray@E@scu@@QEAAPEAEXZ>
extern __imp_?data@?$SecureArray@E@scu@@QEBAPEBEXZ:PANYARGS
?data@?$SecureArray@E@scu@@QEBAPEBEXZ TEXTEQU <__imp_?data@?$SecureArray@E@scu@@QEBAPEBEXZ>
extern __imp_?empty@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_NXZ:PANYARGS
?empty@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_NXZ TEXTEQU <__imp_?empty@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_NXZ>
extern __imp_?empty@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NXZ:PANYARGS
?empty@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NXZ TEXTEQU <__imp_?empty@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_NXZ>
extern __imp_?end@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@XZ:PANYARGS
?end@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@XZ TEXTEQU <__imp_?end@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@XZ>
extern __imp_?end@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AVconst_iterator@12@XZ:PANYARGS
?end@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AVconst_iterator@12@XZ TEXTEQU <__imp_?end@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AVconst_iterator@12@XZ>
extern __imp_?end@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@XZ:PANYARGS
?end@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@XZ TEXTEQU <__imp_?end@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@XZ>
extern __imp_?end@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAPEBQEAUEventInfo@iop@@XZ:PANYARGS
?end@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAPEBQEAUEventInfo@iop@@XZ TEXTEQU <__imp_?end@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAPEBQEAUEventInfo@iop@@XZ>
extern __imp_?erase@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@0@Z:PANYARGS
?erase@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@0@Z TEXTEQU <__imp_?erase@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@0@Z>
extern __imp_?erase@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@@Z:PANYARGS
?erase@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@@Z TEXTEQU <__imp_?erase@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@@Z>
extern __imp_?erase@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@0@Z:PANYARGS
?erase@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@0@Z TEXTEQU <__imp_?erase@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@0@Z>
extern __imp_?erase@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@@Z:PANYARGS
?erase@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@@Z TEXTEQU <__imp_?erase@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@@Z>
extern __imp_?front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAVFilePathComponent@iop@@XZ:PANYARGS
?front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAVFilePathComponent@iop@@XZ TEXTEQU <__imp_?front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAAEAVFilePathComponent@iop@@XZ>
extern __imp_?front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBAAEBVFilePathComponent@iop@@XZ:PANYARGS
?front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBAAEBVFilePathComponent@iop@@XZ TEXTEQU <__imp_?front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBAAEBVFilePathComponent@iop@@XZ>
extern __imp_?front@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@XZ:PANYARGS
?front@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@XZ TEXTEQU <__imp_?front@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAAEAPEAUEventInfo@iop@@XZ>
extern __imp_?front@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@XZ:PANYARGS
?front@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@XZ TEXTEQU <__imp_?front@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBAAEBQEAUEventInfo@iop@@XZ>
extern __imp_?get@?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ:PANYARGS
?get@?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ TEXTEQU <__imp_?get@?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ>
extern __imp_?get@?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ:PANYARGS
?get@?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ TEXTEQU <__imp_?get@?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ>
extern __imp_?getATR@CSmartCard@iop@@QEAAXPEAEAEAE@Z:PANYARGS
?getATR@CSmartCard@iop@@QEAAXPEAEAEAE@Z TEXTEQU <__imp_?getATR@CSmartCard@iop@@QEAAXPEAEAEAE@Z>
extern __imp_?getCardHandle@CSmartCard@iop@@QEAA_KXZ:PANYARGS
?getCardHandle@CSmartCard@iop@@QEAA_KXZ TEXTEQU <__imp_?getCardHandle@CSmartCard@iop@@QEAA_KXZ>
extern __imp_?getCardName@CSmartCard@iop@@QEBAPEBDXZ:PANYARGS
?getCardName@CSmartCard@iop@@QEBAPEBDXZ TEXTEQU <__imp_?getCardName@CSmartCard@iop@@QEBAPEBDXZ>
extern __imp_?get_allocator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$allocator@VFilePathComponent@iop@@@2@XZ:PANYARGS
?get_allocator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$allocator@VFilePathComponent@iop@@@2@XZ TEXTEQU <__imp_?get_allocator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$allocator@VFilePathComponent@iop@@@2@XZ>
extern __imp_?get_allocator@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$allocator@PEAUEventInfo@iop@@@2@XZ:PANYARGS
?get_allocator@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$allocator@PEAUEventInfo@iop@@@2@XZ TEXTEQU <__imp_?get_allocator@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$allocator@PEAUEventInfo@iop@@@2@XZ>
extern __imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@AEBVFilePathComponent@iop@@@Z:PANYARGS
?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@AEBVFilePathComponent@iop@@@Z TEXTEQU <__imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AViterator@12@V312@AEBVFilePathComponent@iop@@@Z>
extern __imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@PEBVFilePathComponent@iop@@1@Z:PANYARGS
?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@PEBVFilePathComponent@iop@@1@Z TEXTEQU <__imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@PEBVFilePathComponent@iop@@1@Z>
extern __imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@Vconst_iterator@12@1@Z:PANYARGS
?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@Vconst_iterator@12@1@Z TEXTEQU <__imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@Vconst_iterator@12@1@Z>
extern __imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@_KAEBVFilePathComponent@iop@@@Z:PANYARGS
?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@_KAEBVFilePathComponent@iop@@@Z TEXTEQU <__imp_?insert@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@_KAEBVFilePathComponent@iop@@@Z>
extern __imp_?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@AEBQEAU34@@Z:PANYARGS
?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@AEBQEAU34@@Z TEXTEQU <__imp_?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAPEAPEAUEventInfo@iop@@PEAPEAU34@AEBQEAU34@@Z>
extern __imp_?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEAPEAUEventInfo@iop@@PEBQEAU34@1@Z:PANYARGS
?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEAPEAUEventInfo@iop@@PEBQEAU34@1@Z TEXTEQU <__imp_?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEAPEAUEventInfo@iop@@PEBQEAU34@1@Z>
extern __imp_?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEAPEAUEventInfo@iop@@_KAEBQEAU34@@Z:PANYARGS
?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEAPEAUEventInfo@iop@@_KAEBQEAU34@@Z TEXTEQU <__imp_?insert@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXPEAPEAUEventInfo@iop@@_KAEBQEAU34@@Z>
extern __imp_?length@?$SecureArray@D@scu@@QEBA_KXZ:PANYARGS
?length@?$SecureArray@D@scu@@QEBA_KXZ TEXTEQU <__imp_?length@?$SecureArray@D@scu@@QEBA_KXZ>
extern __imp_?length@?$SecureArray@E@scu@@QEBA_KXZ:PANYARGS
?length@?$SecureArray@E@scu@@QEBA_KXZ TEXTEQU <__imp_?length@?$SecureArray@E@scu@@QEBA_KXZ>
extern __imp_?length_string@?$SecureArray@D@scu@@QEBA_KXZ:PANYARGS
?length_string@?$SecureArray@D@scu@@QEBA_KXZ TEXTEQU <__imp_?length_string@?$SecureArray@D@scu@@QEBA_KXZ>
extern __imp_?length_string@?$SecureArray@E@scu@@QEBA_KXZ:PANYARGS
?length_string@?$SecureArray@E@scu@@QEBA_KXZ TEXTEQU <__imp_?length_string@?$SecureArray@E@scu@@QEBA_KXZ>
extern __imp_?max_size@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_KXZ:PANYARGS
?max_size@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_KXZ TEXTEQU <__imp_?max_size@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_KXZ>
extern __imp_?max_size@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ:PANYARGS
?max_size@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ TEXTEQU <__imp_?max_size@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ>
extern __imp_?merge@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@@Z:PANYARGS
?merge@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@@Z TEXTEQU <__imp_?merge@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@@Z>
extern __imp_?merge@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@U?$greater@VFilePathComponent@iop@@@2@@Z:PANYARGS
?merge@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@U?$greater@VFilePathComponent@iop@@@2@@Z TEXTEQU <__imp_?merge@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@U?$greater@VFilePathComponent@iop@@@2@@Z>
extern __imp_?pop_back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?pop_back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?pop_back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?pop_back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?pop_back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?pop_back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?pop_front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?pop_front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?pop_front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?push_back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z:PANYARGS
?push_back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z TEXTEQU <__imp_?push_back@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z>
extern __imp_?push_back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXAEBQEAUEventInfo@iop@@@Z:PANYARGS
?push_back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXAEBQEAUEventInfo@iop@@@Z TEXTEQU <__imp_?push_back@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXAEBQEAUEventInfo@iop@@@Z>
extern __imp_?push_front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z:PANYARGS
?push_front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z TEXTEQU <__imp_?push_front@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z>
extern __imp_?rbegin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AV?$reverse_bidirectional_iterator@Viterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEAV45@PEAV45@_J@2@XZ:PANYARGS
?rbegin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AV?$reverse_bidirectional_iterator@Viterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEAV45@PEAV45@_J@2@XZ TEXTEQU <__imp_?rbegin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AV?$reverse_bidirectional_iterator@Viterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEAV45@PEAV45@_J@2@XZ>
extern __imp_?rbegin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$reverse_bidirectional_iterator@Vconst_iterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEBV45@PEBV45@_J@2@XZ:PANYARGS
?rbegin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$reverse_bidirectional_iterator@Vconst_iterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEBV45@PEBV45@_J@2@XZ TEXTEQU <__imp_?rbegin@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$reverse_bidirectional_iterator@Vconst_iterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEBV45@PEBV45@_J@2@XZ>
extern __imp_?rbegin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA?AV?$reverse_iterator@PEAPEAUEventInfo@iop@@PEAU12@AEAPEAU12@PEAPEAU12@_J@2@XZ:PANYARGS
?rbegin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA?AV?$reverse_iterator@PEAPEAUEventInfo@iop@@PEAU12@AEAPEAU12@PEAPEAU12@_J@2@XZ TEXTEQU <__imp_?rbegin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA?AV?$reverse_iterator@PEAPEAUEventInfo@iop@@PEAU12@AEAPEAU12@PEAPEAU12@_J@2@XZ>
extern __imp_?rbegin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$reverse_iterator@PEBQEAUEventInfo@iop@@PEAU12@AEBQEAU12@PEBQEAU12@_J@2@XZ:PANYARGS
?rbegin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$reverse_iterator@PEBQEAUEventInfo@iop@@PEAU12@AEBQEAU12@PEBQEAU12@_J@2@XZ TEXTEQU <__imp_?rbegin@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$reverse_iterator@PEBQEAUEventInfo@iop@@PEAU12@AEBQEAU12@PEBQEAU12@_J@2@XZ>
extern __imp_?release@?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ:PANYARGS
?release@?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ TEXTEQU <__imp_?release@?$auto_ptr@VCSharedMarker@iop@@@std@@QEBAPEAVCSharedMarker@iop@@XZ>
extern __imp_?release@?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ:PANYARGS
?release@?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ TEXTEQU <__imp_?release@?$auto_ptr@VRMHangProcDeathSynchObjects@iop@@@std@@QEBAPEAVRMHangProcDeathSynchObjects@iop@@XZ>
extern __imp_?remove@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z:PANYARGS
?remove@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z TEXTEQU <__imp_?remove@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEBVFilePathComponent@iop@@@Z>
extern __imp_?remove_if@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXV?$binder2nd@U?$not_equal_to@VFilePathComponent@iop@@@std@@@2@@Z:PANYARGS
?remove_if@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXV?$binder2nd@U?$not_equal_to@VFilePathComponent@iop@@@std@@@2@@Z TEXTEQU <__imp_?remove_if@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXV?$binder2nd@U?$not_equal_to@VFilePathComponent@iop@@@std@@@2@@Z>
extern __imp_?rend@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AV?$reverse_bidirectional_iterator@Viterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEAV45@PEAV45@_J@2@XZ:PANYARGS
?rend@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AV?$reverse_bidirectional_iterator@Viterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEAV45@PEAV45@_J@2@XZ TEXTEQU <__imp_?rend@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAA?AV?$reverse_bidirectional_iterator@Viterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEAV45@PEAV45@_J@2@XZ>
extern __imp_?rend@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$reverse_bidirectional_iterator@Vconst_iterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEBV45@PEBV45@_J@2@XZ:PANYARGS
?rend@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$reverse_bidirectional_iterator@Vconst_iterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEBV45@PEBV45@_J@2@XZ TEXTEQU <__imp_?rend@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA?AV?$reverse_bidirectional_iterator@Vconst_iterator@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@VFilePathComponent@iop@@AEBV45@PEBV45@_J@2@XZ>
extern __imp_?rend@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA?AV?$reverse_iterator@PEAPEAUEventInfo@iop@@PEAU12@AEAPEAU12@PEAPEAU12@_J@2@XZ:PANYARGS
?rend@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA?AV?$reverse_iterator@PEAPEAUEventInfo@iop@@PEAU12@AEAPEAU12@PEAPEAU12@_J@2@XZ TEXTEQU <__imp_?rend@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAA?AV?$reverse_iterator@PEAPEAUEventInfo@iop@@PEAU12@AEAPEAU12@PEAPEAU12@_J@2@XZ>
extern __imp_?rend@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$reverse_iterator@PEBQEAUEventInfo@iop@@PEAU12@AEBQEAU12@PEBQEAU12@_J@2@XZ:PANYARGS
?rend@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$reverse_iterator@PEBQEAUEventInfo@iop@@PEAU12@AEBQEAU12@PEBQEAU12@_J@2@XZ TEXTEQU <__imp_?rend@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA?AV?$reverse_iterator@PEBQEAUEventInfo@iop@@PEAU12@AEBQEAU12@PEBQEAU12@_J@2@XZ>
extern __imp_?reserve@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_K@Z:PANYARGS
?reserve@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_K@Z TEXTEQU <__imp_?reserve@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_K@Z>
extern __imp_?resize@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAX_KVFilePathComponent@iop@@@Z:PANYARGS
?resize@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAX_KVFilePathComponent@iop@@@Z TEXTEQU <__imp_?resize@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAX_KVFilePathComponent@iop@@@Z>
extern __imp_?resize@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_KAEBQEAUEventInfo@iop@@@Z:PANYARGS
?resize@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_KAEBQEAUEventInfo@iop@@@Z TEXTEQU <__imp_?resize@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAX_KAEBQEAUEventInfo@iop@@@Z>
extern __imp_?reverse@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?reverse@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?reverse@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?setCardName@CSmartCard@iop@@QEAAXPEBD@Z:PANYARGS
?setCardName@CSmartCard@iop@@QEAAXPEBD@Z TEXTEQU <__imp_?setCardName@CSmartCard@iop@@QEAAXPEBD@Z>
extern __imp_?size@?$SecureArray@D@scu@@QEBA_KXZ:PANYARGS
?size@?$SecureArray@D@scu@@QEBA_KXZ TEXTEQU <__imp_?size@?$SecureArray@D@scu@@QEBA_KXZ>
extern __imp_?size@?$SecureArray@E@scu@@QEBA_KXZ:PANYARGS
?size@?$SecureArray@E@scu@@QEBA_KXZ TEXTEQU <__imp_?size@?$SecureArray@E@scu@@QEBA_KXZ>
extern __imp_?size@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_KXZ:PANYARGS
?size@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_KXZ TEXTEQU <__imp_?size@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEBA_KXZ>
extern __imp_?size@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ:PANYARGS
?size@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ TEXTEQU <__imp_?size@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEBA_KXZ>
extern __imp_?sort@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXU?$greater@VFilePathComponent@iop@@@2@@Z:PANYARGS
?sort@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXU?$greater@VFilePathComponent@iop@@@2@@Z TEXTEQU <__imp_?sort@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXU?$greater@VFilePathComponent@iop@@@2@@Z>
extern __imp_?sort@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?sort@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?sort@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ>
extern __imp_?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@00@Z:PANYARGS
?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@00@Z TEXTEQU <__imp_?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@00@Z>
extern __imp_?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@0@Z:PANYARGS
?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@0@Z TEXTEQU <__imp_?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@0@Z>
extern __imp_?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@@Z:PANYARGS
?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@@Z TEXTEQU <__imp_?splice@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXViterator@12@AEAV12@@Z>
extern __imp_?swap@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@@Z:PANYARGS
?swap@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@@Z TEXTEQU <__imp_?swap@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXAEAV12@@Z>
extern __imp_?swap@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXAEAV12@@Z:PANYARGS
?swap@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXAEAV12@@Z TEXTEQU <__imp_?swap@?$vector@PEAUEventInfo@iop@@V?$allocator@PEAUEventInfo@iop@@@std@@@std@@QEAAXAEAV12@@Z>
extern __imp_?unique@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXU?$not_equal_to@VFilePathComponent@iop@@@2@@Z:PANYARGS
?unique@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXU?$not_equal_to@VFilePathComponent@iop@@@2@@Z TEXTEQU <__imp_?unique@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXU?$not_equal_to@VFilePathComponent@iop@@@2@@Z>
extern __imp_?unique@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ:PANYARGS
?unique@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ TEXTEQU <__imp_?unique@?$list@VFilePathComponent@iop@@V?$allocator@VFilePathComponent@iop@@@std@@@std@@QEAAXXZ>
extern __imp_DllGetVersion:PANYARGS
DllGetVersion TEXTEQU <__imp_DllGetVersion>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
