extern __imp_SnmpSvcAddrIsIpx:PANYARGS
SnmpSvcAddrIsIpx TEXTEQU <__imp_SnmpSvcAddrIsIpx>
extern __imp_SnmpSvcAddrToSocket:PANYARGS
SnmpSvcAddrToSocket TEXTEQU <__imp_SnmpSvcAddrToSocket>
extern __imp_SnmpSvcGetEnterpriseOID:PANYARGS
SnmpSvcGetEnterpriseOID TEXTEQU <__imp_SnmpSvcGetEnterpriseOID>
extern __imp_SnmpSvcGetUptime:PANYARGS
SnmpSvcGetUptime TEXTEQU <__imp_SnmpSvcGetUptime>
extern __imp_SnmpSvcGetUptimeFromTime:PANYARGS
SnmpSvcGetUptimeFromTime TEXTEQU <__imp_SnmpSvcGetUptimeFromTime>
extern __imp_SnmpSvcInitUptime:PANYARGS
SnmpSvcInitUptime TEXTEQU <__imp_SnmpSvcInitUptime>
extern __imp_SnmpSvcSetLogLevel:PANYARGS
SnmpSvcSetLogLevel TEXTEQU <__imp_SnmpSvcSetLogLevel>
extern __imp_SnmpSvcSetLogType:PANYARGS
SnmpSvcSetLogType TEXTEQU <__imp_SnmpSvcSetLogType>
extern __imp_SnmpTfxClose:PANYARGS
SnmpTfxClose TEXTEQU <__imp_SnmpTfxClose>
extern __imp_SnmpTfxOpen:PANYARGS
SnmpTfxOpen TEXTEQU <__imp_SnmpTfxOpen>
extern __imp_SnmpTfxQuery:PANYARGS
SnmpTfxQuery TEXTEQU <__imp_SnmpTfxQuery>
extern __imp_SnmpUtilAnsiToUnicode:PANYARGS
SnmpUtilAnsiToUnicode TEXTEQU <__imp_SnmpUtilAnsiToUnicode>
extern __imp_SnmpUtilAsnAnyCpy:PANYARGS
SnmpUtilAsnAnyCpy TEXTEQU <__imp_SnmpUtilAsnAnyCpy>
extern __imp_SnmpUtilAsnAnyFree:PANYARGS
SnmpUtilAsnAnyFree TEXTEQU <__imp_SnmpUtilAsnAnyFree>
extern __imp_SnmpUtilDbgPrint:PANYARGS
SnmpUtilDbgPrint TEXTEQU <__imp_SnmpUtilDbgPrint>
extern __imp_SnmpUtilIdsToA:PANYARGS
SnmpUtilIdsTo  TEXTEQU <__imp_SnmpUtilIdsToA>
extern __imp_SnmpUtilMemAlloc:PANYARGS
SnmpUtilMemAlloc TEXTEQU <__imp_SnmpUtilMemAlloc>
extern __imp_SnmpUtilMemFree:PANYARGS
SnmpUtilMemFree TEXTEQU <__imp_SnmpUtilMemFree>
extern __imp_SnmpUtilMemReAlloc:PANYARGS
SnmpUtilMemReAlloc TEXTEQU <__imp_SnmpUtilMemReAlloc>
extern __imp_SnmpUtilOctetsCmp:PANYARGS
SnmpUtilOctetsCmp TEXTEQU <__imp_SnmpUtilOctetsCmp>
extern __imp_SnmpUtilOctetsCpy:PANYARGS
SnmpUtilOctetsCpy TEXTEQU <__imp_SnmpUtilOctetsCpy>
extern __imp_SnmpUtilOctetsFree:PANYARGS
SnmpUtilOctetsFree TEXTEQU <__imp_SnmpUtilOctetsFree>
extern __imp_SnmpUtilOctetsNCmp:PANYARGS
SnmpUtilOctetsNCmp TEXTEQU <__imp_SnmpUtilOctetsNCmp>
extern __imp_SnmpUtilOidAppend:PANYARGS
SnmpUtilOidAppend TEXTEQU <__imp_SnmpUtilOidAppend>
extern __imp_SnmpUtilOidCmp:PANYARGS
SnmpUtilOidCmp TEXTEQU <__imp_SnmpUtilOidCmp>
extern __imp_SnmpUtilOidCpy:PANYARGS
SnmpUtilOidCpy TEXTEQU <__imp_SnmpUtilOidCpy>
extern __imp_SnmpUtilOidFree:PANYARGS
SnmpUtilOidFree TEXTEQU <__imp_SnmpUtilOidFree>
extern __imp_SnmpUtilOidNCmp:PANYARGS
SnmpUtilOidNCmp TEXTEQU <__imp_SnmpUtilOidNCmp>
extern __imp_SnmpUtilOidToA:PANYARGS
SnmpUtilOidTo  TEXTEQU <__imp_SnmpUtilOidToA>
extern __imp_SnmpUtilPrintAsnAny:PANYARGS
SnmpUtilPrintAsnAny TEXTEQU <__imp_SnmpUtilPrintAsnAny>
extern __imp_SnmpUtilPrintOid:PANYARGS
SnmpUtilPrintOid TEXTEQU <__imp_SnmpUtilPrintOid>
extern __imp_SnmpUtilUTF8ToUnicode:PANYARGS
SnmpUtilUTF8ToUnicode TEXTEQU <__imp_SnmpUtilUTF8ToUnicode>
extern __imp_SnmpUtilUnicodeToAnsi:PANYARGS
SnmpUtilUnicodeToAnsi TEXTEQU <__imp_SnmpUtilUnicodeToAnsi>
extern __imp_SnmpUtilUnicodeToUTF8:PANYARGS
SnmpUtilUnicodeToUTF8 TEXTEQU <__imp_SnmpUtilUnicodeToUTF8>
extern __imp_SnmpUtilVarBindCpy:PANYARGS
SnmpUtilVarBindCpy TEXTEQU <__imp_SnmpUtilVarBindCpy>
extern __imp_SnmpUtilVarBindFree:PANYARGS
SnmpUtilVarBindFree TEXTEQU <__imp_SnmpUtilVarBindFree>
extern __imp_SnmpUtilVarBindListCpy:PANYARGS
SnmpUtilVarBindListCpy TEXTEQU <__imp_SnmpUtilVarBindListCpy>
extern __imp_SnmpUtilVarBindListFree:PANYARGS
SnmpUtilVarBindListFree TEXTEQU <__imp_SnmpUtilVarBindListFree>
