extern __imp_pszDbgAllocMsgA:PANYARGS
pszDbgAllocMsg  TEXTEQU <__imp_pszDbgAllocMsgA>
extern __imp_vDbgLogError:PANYARGS
vDbgLogError TEXTEQU <__imp_vDbgLogError>
extern __imp_AbortPrinter:PANYARGS
AbortPrinter TEXTEQU <__imp_AbortPrinter>
extern __imp_AddDriverCatalog:PANYARGS
AddDriverCatalog TEXTEQU <__imp_AddDriverCatalog>
extern __imp_AddFormW:PANYARGS
AddFormW TEXTEQU <__imp_AddFormW>
extern __imp_AddJobW:PANYARGS
AddJobW TEXTEQU <__imp_AddJobW>
extern __imp_AddMonitorW:PANYARGS
AddMonitorW TEXTEQU <__imp_AddMonitorW>
extern __imp_AddPerMachineConnectionW:PANYARGS
AddPerMachineConnectionW TEXTEQU <__imp_AddPerMachineConnectionW>
extern __imp_AddPortExW:PANYARGS
AddPortExW TEXTEQU <__imp_AddPortExW>
extern __imp_AddPortW:PANYARGS
AddPortW TEXTEQU <__imp_AddPortW>
extern __imp_AddPrintProcessorW:PANYARGS
AddPrintProcessorW TEXTEQU <__imp_AddPrintProcessorW>
extern __imp_AddPrintProvidorW:PANYARGS
AddPrintProvidorW TEXTEQU <__imp_AddPrintProvidorW>
extern __imp_AddPrinterConnectionW:PANYARGS
AddPrinterConnectionW TEXTEQU <__imp_AddPrinterConnectionW>
extern __imp_AddPrinterDriverExW:PANYARGS
AddPrinterDriverExW TEXTEQU <__imp_AddPrinterDriverExW>
extern __imp_AddPrinterDriverW:PANYARGS
AddPrinterDriverW TEXTEQU <__imp_AddPrinterDriverW>
extern __imp_AddPrinterExW:PANYARGS
AddPrinterExW TEXTEQU <__imp_AddPrinterExW>
extern __imp_AddPrinterW:PANYARGS
AddPrinterW TEXTEQU <__imp_AddPrinterW>
extern __imp_AdjustPointers:PANYARGS
AdjustPointers TEXTEQU <__imp_AdjustPointers>
extern __imp_AdjustPointersInStructuresArray:PANYARGS
AdjustPointersInStructuresArray TEXTEQU <__imp_AdjustPointersInStructuresArray>
extern __imp_AlignKMPtr:PANYARGS
AlignKMPtr TEXTEQU <__imp_AlignKMPtr>
extern __imp_AlignRpcPtr:PANYARGS
AlignRpcPtr TEXTEQU <__imp_AlignRpcPtr>
extern __imp_AllocSplStr:PANYARGS
AllocSplStr TEXTEQU <__imp_AllocSplStr>
extern __imp_AllowRemoteCalls:PANYARGS
AllowRemoteCalls TEXTEQU <__imp_AllowRemoteCalls>
extern __imp_AppendPrinterNotifyInfoData:PANYARGS
AppendPrinterNotifyInfoData TEXTEQU <__imp_AppendPrinterNotifyInfoData>
extern __imp_BuildOtherNamesFromMachineName:PANYARGS
BuildOtherNamesFromMachineName TEXTEQU <__imp_BuildOtherNamesFromMachineName>
extern __imp_CacheAddName:PANYARGS
CacheAddName TEXTEQU <__imp_CacheAddName>
extern __imp_CacheCreateAndAddNode:PANYARGS
CacheCreateAndAddNode TEXTEQU <__imp_CacheCreateAndAddNode>
extern __imp_CacheCreateAndAddNodeWithIPAddresses:PANYARGS
CacheCreateAndAddNodeWithIPAddresses TEXTEQU <__imp_CacheCreateAndAddNodeWithIPAddresses>
extern __imp_CacheDeleteNode:PANYARGS
CacheDeleteNode TEXTEQU <__imp_CacheDeleteNode>
extern __imp_CacheIsNameCluster:PANYARGS
CacheIsNameCluster TEXTEQU <__imp_CacheIsNameCluster>
extern __imp_CacheIsNameInNodeList:PANYARGS
CacheIsNameInNodeList TEXTEQU <__imp_CacheIsNameInNodeList>
extern __imp_CallDrvDevModeConversion:PANYARGS
CallDrvDevModeConversion TEXTEQU <__imp_CallDrvDevModeConversion>
extern __imp_CallRouterFindFirstPrinterChangeNotification:PANYARGS
CallRouterFindFirstPrinterChangeNotification TEXTEQU <__imp_CallRouterFindFirstPrinterChangeNotification>
extern __imp_CheckLocalCall:PANYARGS
CheckLocalCall TEXTEQU <__imp_CheckLocalCall>
extern __imp_ClosePrinter:PANYARGS
ClosePrinter TEXTEQU <__imp_ClosePrinter>
extern __imp_ClusterSplClose:PANYARGS
ClusterSplClose TEXTEQU <__imp_ClusterSplClose>
extern __imp_ClusterSplIsAlive:PANYARGS
ClusterSplIsAlive TEXTEQU <__imp_ClusterSplIsAlive>
extern __imp_ClusterSplOpen:PANYARGS
ClusterSplOpen TEXTEQU <__imp_ClusterSplOpen>
extern __imp_ConfigurePortW:PANYARGS
ConfigurePortW TEXTEQU <__imp_ConfigurePortW>
extern __imp_CreatePrinterIC:PANYARGS
CreatePrinterIC TEXTEQU <__imp_CreatePrinterIC>
extern __imp_DbgGetPointers:PANYARGS
DbgGetPointers TEXTEQU <__imp_DbgGetPointers>
extern __imp_DeleteFormW:PANYARGS
DeleteFormW TEXTEQU <__imp_DeleteFormW>
extern __imp_DeleteMonitorW:PANYARGS
DeleteMonitorW TEXTEQU <__imp_DeleteMonitorW>
extern __imp_DeletePerMachineConnectionW:PANYARGS
DeletePerMachineConnectionW TEXTEQU <__imp_DeletePerMachineConnectionW>
extern __imp_DeletePortW:PANYARGS
DeletePortW TEXTEQU <__imp_DeletePortW>
extern __imp_DeletePrintProcessorW:PANYARGS
DeletePrintProcessorW TEXTEQU <__imp_DeletePrintProcessorW>
extern __imp_DeletePrintProvidorW:PANYARGS
DeletePrintProvidorW TEXTEQU <__imp_DeletePrintProvidorW>
extern __imp_DeletePrinter:PANYARGS
DeletePrinter TEXTEQU <__imp_DeletePrinter>
extern __imp_DeletePrinterConnectionW:PANYARGS
DeletePrinterConnectionW TEXTEQU <__imp_DeletePrinterConnectionW>
extern __imp_DeletePrinterDataExW:PANYARGS
DeletePrinterDataExW TEXTEQU <__imp_DeletePrinterDataExW>
extern __imp_DeletePrinterDataW:PANYARGS
DeletePrinterDataW TEXTEQU <__imp_DeletePrinterDataW>
extern __imp_DeletePrinterDriverExW:PANYARGS
DeletePrinterDriverExW TEXTEQU <__imp_DeletePrinterDriverExW>
extern __imp_DeletePrinterDriverW:PANYARGS
DeletePrinterDriverW TEXTEQU <__imp_DeletePrinterDriverW>
extern __imp_DeletePrinterIC:PANYARGS
DeletePrinterIC TEXTEQU <__imp_DeletePrinterIC>
extern __imp_DeletePrinterKeyW:PANYARGS
DeletePrinterKeyW TEXTEQU <__imp_DeletePrinterKeyW>
extern __imp_DllAllocSplMem:PANYARGS
DllAllocSplMem TEXTEQU <__imp_DllAllocSplMem>
extern __imp_DllFreeSplMem:PANYARGS
DllFreeSplMem TEXTEQU <__imp_DllFreeSplMem>
extern __imp_DllFreeSplStr:PANYARGS
DllFreeSplStr TEXTEQU <__imp_DllFreeSplStr>
extern __imp_EndDocPrinter:PANYARGS
EndDocPrinter TEXTEQU <__imp_EndDocPrinter>
extern __imp_EndPagePrinter:PANYARGS
EndPagePrinter TEXTEQU <__imp_EndPagePrinter>
extern __imp_EnumFormsW:PANYARGS
EnumFormsW TEXTEQU <__imp_EnumFormsW>
extern __imp_EnumJobsW:PANYARGS
EnumJobsW TEXTEQU <__imp_EnumJobsW>
extern __imp_EnumMonitorsW:PANYARGS
EnumMonitorsW TEXTEQU <__imp_EnumMonitorsW>
extern __imp_EnumPerMachineConnectionsW:PANYARGS
EnumPerMachineConnectionsW TEXTEQU <__imp_EnumPerMachineConnectionsW>
extern __imp_EnumPortsW:PANYARGS
EnumPortsW TEXTEQU <__imp_EnumPortsW>
extern __imp_EnumPrintProcessorDatatypesW:PANYARGS
EnumPrintProcessorDatatypesW TEXTEQU <__imp_EnumPrintProcessorDatatypesW>
extern __imp_EnumPrintProcessorsW:PANYARGS
EnumPrintProcessorsW TEXTEQU <__imp_EnumPrintProcessorsW>
extern __imp_EnumPrinterDataExW:PANYARGS
EnumPrinterDataExW TEXTEQU <__imp_EnumPrinterDataExW>
extern __imp_EnumPrinterDataW:PANYARGS
EnumPrinterDataW TEXTEQU <__imp_EnumPrinterDataW>
extern __imp_EnumPrinterDriversW:PANYARGS
EnumPrinterDriversW TEXTEQU <__imp_EnumPrinterDriversW>
extern __imp_EnumPrinterKeyW:PANYARGS
EnumPrinterKeyW TEXTEQU <__imp_EnumPrinterKeyW>
extern __imp_EnumPrintersW:PANYARGS
EnumPrintersW TEXTEQU <__imp_EnumPrintersW>
extern __imp_FindClosePrinterChangeNotification:PANYARGS
FindClosePrinterChangeNotification TEXTEQU <__imp_FindClosePrinterChangeNotification>
extern __imp_FlushPrinter:PANYARGS
FlushPrinter TEXTEQU <__imp_FlushPrinter>
extern __imp_FormatPrinterForRegistryKey:PANYARGS
FormatPrinterForRegistryKey TEXTEQU <__imp_FormatPrinterForRegistryKey>
extern __imp_FormatRegistryKeyForPrinter:PANYARGS
FormatRegistryKeyForPrinter TEXTEQU <__imp_FormatRegistryKeyForPrinter>
extern __imp_FreeOtherNames:PANYARGS
FreeOtherNames TEXTEQU <__imp_FreeOtherNames>
extern __imp_GetClientUserHandle:PANYARGS
GetClientUserHandle TEXTEQU <__imp_GetClientUserHandle>
extern __imp_GetFormW:PANYARGS
GetFormW TEXTEQU <__imp_GetFormW>
extern __imp_GetJobAttributes:PANYARGS
GetJobAttributes TEXTEQU <__imp_GetJobAttributes>
extern __imp_GetJobW:PANYARGS
GetJobW TEXTEQU <__imp_GetJobW>
extern __imp_GetNetworkId:PANYARGS
GetNetworkId TEXTEQU <__imp_GetNetworkId>
extern __imp_GetPrintProcessorDirectoryW:PANYARGS
GetPrintProcessorDirectoryW TEXTEQU <__imp_GetPrintProcessorDirectoryW>
extern __imp_GetPrinterDataExW:PANYARGS
GetPrinterDataExW TEXTEQU <__imp_GetPrinterDataExW>
extern __imp_GetPrinterDataW:PANYARGS
GetPrinterDataW TEXTEQU <__imp_GetPrinterDataW>
extern __imp_GetPrinterDriverDirectoryW:PANYARGS
GetPrinterDriverDirectoryW TEXTEQU <__imp_GetPrinterDriverDirectoryW>
extern __imp_GetPrinterDriverExW:PANYARGS
GetPrinterDriverExW TEXTEQU <__imp_GetPrinterDriverExW>
extern __imp_GetPrinterDriverW:PANYARGS
GetPrinterDriverW TEXTEQU <__imp_GetPrinterDriverW>
extern __imp_GetPrinterW:PANYARGS
GetPrinterW TEXTEQU <__imp_GetPrinterW>
extern __imp_GetServerPolicy:PANYARGS
GetServerPolicy TEXTEQU <__imp_GetServerPolicy>
extern __imp_GetShrinkedSize:PANYARGS
GetShrinkedSize TEXTEQU <__imp_GetShrinkedSize>
extern __imp_ImpersonatePrinterClient:PANYARGS
ImpersonatePrinterClient TEXTEQU <__imp_ImpersonatePrinterClient>
extern __imp_InitializeRouter:PANYARGS
InitializeRouter TEXTEQU <__imp_InitializeRouter>
extern __imp_IsNamedPipeRpcCall:PANYARGS
IsNamedPipeRpcCall TEXTEQU <__imp_IsNamedPipeRpcCall>
extern __imp_LoadDriver:PANYARGS
LoadDriver TEXTEQU <__imp_LoadDriver>
extern __imp_LoadDriverFiletoConvertDevmode:PANYARGS
LoadDriverFiletoConvertDevmode TEXTEQU <__imp_LoadDriverFiletoConvertDevmode>
extern __imp_LoadDriverWithVersion:PANYARGS
LoadDriverWithVersion TEXTEQU <__imp_LoadDriverWithVersion>
extern __imp_LogWmiTraceEvent:PANYARGS
LogWmiTraceEvent TEXTEQU <__imp_LogWmiTraceEvent>
extern __imp_MIDL_user_allocate1:PANYARGS
MIDL_user_allocate1 TEXTEQU <__imp_MIDL_user_allocate1>
extern __imp_MIDL_user_free1:PANYARGS
MIDL_user_free1 TEXTEQU <__imp_MIDL_user_free1>
extern __imp_MarshallDownStructure:PANYARGS
MarshallDownStructure TEXTEQU <__imp_MarshallDownStructure>
extern __imp_MarshallDownStructuresArray:PANYARGS
MarshallDownStructuresArray TEXTEQU <__imp_MarshallDownStructuresArray>
extern __imp_MarshallUpStructure:PANYARGS
MarshallUpStructure TEXTEQU <__imp_MarshallUpStructure>
extern __imp_MarshallUpStructuresArray:PANYARGS
MarshallUpStructuresArray TEXTEQU <__imp_MarshallUpStructuresArray>
extern __imp_OldGetPrinterDriverW:PANYARGS
OldGetPrinterDriverW TEXTEQU <__imp_OldGetPrinterDriverW>
extern __imp_OpenPrinterExW:PANYARGS
OpenPrinterExW TEXTEQU <__imp_OpenPrinterExW>
extern __imp_OpenPrinterPortW:PANYARGS
OpenPrinterPortW TEXTEQU <__imp_OpenPrinterPortW>
extern __imp_OpenPrinterW:PANYARGS
OpenPrinterW TEXTEQU <__imp_OpenPrinterW>
extern __imp_PackStrings:PANYARGS
PackStrings TEXTEQU <__imp_PackStrings>
extern __imp_PartialReplyPrinterChangeNotification:PANYARGS
PartialReplyPrinterChangeNotification TEXTEQU <__imp_PartialReplyPrinterChangeNotification>
extern __imp_PlayGdiScriptOnPrinterIC:PANYARGS
PlayGdiScriptOnPrinterIC TEXTEQU <__imp_PlayGdiScriptOnPrinterIC>
extern __imp_PrinterHandleRundown:PANYARGS
PrinterHandleRundown TEXTEQU <__imp_PrinterHandleRundown>
extern __imp_PrinterMessageBoxW:PANYARGS
PrinterMessageBoxW TEXTEQU <__imp_PrinterMessageBoxW>
extern __imp_ProvidorFindClosePrinterChangeNotification:PANYARGS
ProvidorFindClosePrinterChangeNotification TEXTEQU <__imp_ProvidorFindClosePrinterChangeNotification>
extern __imp_ProvidorFindFirstPrinterChangeNotification:PANYARGS
ProvidorFindFirstPrinterChangeNotification TEXTEQU <__imp_ProvidorFindFirstPrinterChangeNotification>
extern __imp_ReadPrinter:PANYARGS
ReadPrinter TEXTEQU <__imp_ReadPrinter>
extern __imp_ReallocSplMem:PANYARGS
ReallocSplMem TEXTEQU <__imp_ReallocSplMem>
extern __imp_ReallocSplStr:PANYARGS
ReallocSplStr TEXTEQU <__imp_ReallocSplStr>
extern __imp_RemoteFindFirstPrinterChangeNotification:PANYARGS
RemoteFindFirstPrinterChangeNotification TEXTEQU <__imp_RemoteFindFirstPrinterChangeNotification>
extern __imp_ReplyClosePrinter:PANYARGS
ReplyClosePrinter TEXTEQU <__imp_ReplyClosePrinter>
extern __imp_ReplyOpenPrinter:PANYARGS
ReplyOpenPrinter TEXTEQU <__imp_ReplyOpenPrinter>
extern __imp_ReplyPrinterChangeNotification:PANYARGS
ReplyPrinterChangeNotification TEXTEQU <__imp_ReplyPrinterChangeNotification>
extern __imp_ResetPrinterW:PANYARGS
ResetPrinterW TEXTEQU <__imp_ResetPrinterW>
extern __imp_RevertToPrinterSelf:PANYARGS
RevertToPrinterSelf TEXTEQU <__imp_RevertToPrinterSelf>
extern __imp_RouterAllocBidiMem:PANYARGS
RouterAllocBidiMem TEXTEQU <__imp_RouterAllocBidiMem>
extern __imp_RouterAllocBidiResponseContainer:PANYARGS
RouterAllocBidiResponseContainer TEXTEQU <__imp_RouterAllocBidiResponseContainer>
extern __imp_RouterAllocPrinterNotifyInfo:PANYARGS
RouterAllocPrinterNotifyInfo TEXTEQU <__imp_RouterAllocPrinterNotifyInfo>
extern __imp_RouterFindFirstPrinterChangeNotification:PANYARGS
RouterFindFirstPrinterChangeNotification TEXTEQU <__imp_RouterFindFirstPrinterChangeNotification>
extern __imp_RouterFindNextPrinterChangeNotification:PANYARGS
RouterFindNextPrinterChangeNotification TEXTEQU <__imp_RouterFindNextPrinterChangeNotification>
extern __imp_RouterFreeBidiMem:PANYARGS
RouterFreeBidiMem TEXTEQU <__imp_RouterFreeBidiMem>
extern __imp_RouterFreePrinterNotifyInfo:PANYARGS
RouterFreePrinterNotifyInfo TEXTEQU <__imp_RouterFreePrinterNotifyInfo>
extern __imp_RouterRefreshPrinterChangeNotification:PANYARGS
RouterRefreshPrinterChangeNotification TEXTEQU <__imp_RouterRefreshPrinterChangeNotification>
extern __imp_RouterReplyPrinter:PANYARGS
RouterReplyPrinter TEXTEQU <__imp_RouterReplyPrinter>
extern __imp_ScheduleJob:PANYARGS
ScheduleJob TEXTEQU <__imp_ScheduleJob>
extern __imp_SeekPrinter:PANYARGS
SeekPrinter TEXTEQU <__imp_SeekPrinter>
extern __imp_SendRecvBidiData:PANYARGS
SendRecvBidiData TEXTEQU <__imp_SendRecvBidiData>
extern __imp_SetAllocFailCount:PANYARGS
SetAllocFailCount TEXTEQU <__imp_SetAllocFailCount>
extern __imp_SetFormW:PANYARGS
SetFormW TEXTEQU <__imp_SetFormW>
extern __imp_SetJobW:PANYARGS
SetJobW TEXTEQU <__imp_SetJobW>
extern __imp_SetPortW:PANYARGS
SetPortW TEXTEQU <__imp_SetPortW>
extern __imp_SetPrinterDataExW:PANYARGS
SetPrinterDataExW TEXTEQU <__imp_SetPrinterDataExW>
extern __imp_SetPrinterDataW:PANYARGS
SetPrinterDataW TEXTEQU <__imp_SetPrinterDataW>
extern __imp_SetPrinterW:PANYARGS
SetPrinterW TEXTEQU <__imp_SetPrinterW>
extern __imp_SplCloseSpoolFileHandle:PANYARGS
SplCloseSpoolFileHandle TEXTEQU <__imp_SplCloseSpoolFileHandle>
extern __imp_SplCommitSpoolData:PANYARGS
SplCommitSpoolData TEXTEQU <__imp_SplCommitSpoolData>
extern __imp_SplDriverUnloadComplete:PANYARGS
SplDriverUnloadComplete TEXTEQU <__imp_SplDriverUnloadComplete>
extern __imp_SplGetSpoolFileInfo:PANYARGS
SplGetSpoolFileInfo TEXTEQU <__imp_SplGetSpoolFileInfo>
extern __imp_SplInitializeWinSpoolDrv:PANYARGS
SplInitializeWinSpoolDrv TEXTEQU <__imp_SplInitializeWinSpoolDrv>
extern __imp_SplIsSessionZero:PANYARGS
SplIsSessionZero TEXTEQU <__imp_SplIsSessionZero>
extern __imp_SplIsUpgrade:PANYARGS
SplIsUpgrade TEXTEQU <__imp_SplIsUpgrade>
extern __imp_SplPowerEvent:PANYARGS
SplPowerEvent TEXTEQU <__imp_SplPowerEvent>
extern __imp_SplProcessPnPEvent:PANYARGS
SplProcessPnPEvent TEXTEQU <__imp_SplProcessPnPEvent>
extern __imp_SplPromptUIInUsersSession:PANYARGS
SplPromptUIInUsersSession TEXTEQU <__imp_SplPromptUIInUsersSession>
extern __imp_SplReadPrinter:PANYARGS
SplReadPrinter TEXTEQU <__imp_SplReadPrinter>
extern __imp_SplRegisterForDeviceEvents:PANYARGS
SplRegisterForDeviceEvents TEXTEQU <__imp_SplRegisterForDeviceEvents>
extern __imp_SplShutDownRouter:PANYARGS
SplShutDownRouter TEXTEQU <__imp_SplShutDownRouter>
extern __imp_SplUnregisterForDeviceEvents:PANYARGS
SplUnregisterForDeviceEvents TEXTEQU <__imp_SplUnregisterForDeviceEvents>
extern __imp_SpoolerFindClosePrinterChangeNotification:PANYARGS
SpoolerFindClosePrinterChangeNotification TEXTEQU <__imp_SpoolerFindClosePrinterChangeNotification>
extern __imp_SpoolerFindFirstPrinterChangeNotification:PANYARGS
SpoolerFindFirstPrinterChangeNotification TEXTEQU <__imp_SpoolerFindFirstPrinterChangeNotification>
extern __imp_SpoolerFindNextPrinterChangeNotification:PANYARGS
SpoolerFindNextPrinterChangeNotification TEXTEQU <__imp_SpoolerFindNextPrinterChangeNotification>
extern __imp_SpoolerFreePrinterNotifyInfo:PANYARGS
SpoolerFreePrinterNotifyInfo TEXTEQU <__imp_SpoolerFreePrinterNotifyInfo>
extern __imp_SpoolerHasInitialized:PANYARGS
SpoolerHasInitialized TEXTEQU <__imp_SpoolerHasInitialized>
extern __imp_SpoolerInit:PANYARGS
SpoolerInit TEXTEQU <__imp_SpoolerInit>
extern __imp_StartDocPrinterW:PANYARGS
StartDocPrinterW TEXTEQU <__imp_StartDocPrinterW>
extern __imp_StartPagePrinter:PANYARGS
StartPagePrinter TEXTEQU <__imp_StartPagePrinter>
extern __imp_UndoAlignKMPtr:PANYARGS
UndoAlignKMPtr TEXTEQU <__imp_UndoAlignKMPtr>
extern __imp_UndoAlignRpcPtr:PANYARGS
UndoAlignRpcPtr TEXTEQU <__imp_UndoAlignRpcPtr>
extern __imp_UnloadDriver:PANYARGS
UnloadDriver TEXTEQU <__imp_UnloadDriver>
extern __imp_UnloadDriverFile:PANYARGS
UnloadDriverFile TEXTEQU <__imp_UnloadDriverFile>
extern __imp_UpdateBufferSize:PANYARGS
UpdateBufferSize TEXTEQU <__imp_UpdateBufferSize>
extern __imp_UpdatePrinterRegAll:PANYARGS
UpdatePrinterRegAll TEXTEQU <__imp_UpdatePrinterRegAll>
extern __imp_UpdatePrinterRegUser:PANYARGS
UpdatePrinterRegUser TEXTEQU <__imp_UpdatePrinterRegUser>
extern __imp_WaitForPrinterChange:PANYARGS
WaitForPrinterChange TEXTEQU <__imp_WaitForPrinterChange>
extern __imp_WaitForSpoolerInitialization:PANYARGS
WaitForSpoolerInitialization TEXTEQU <__imp_WaitForSpoolerInitialization>
extern __imp_WritePrinter:PANYARGS
WritePrinter TEXTEQU <__imp_WritePrinter>
extern __imp_XcvDataW:PANYARGS
XcvDataW TEXTEQU <__imp_XcvDataW>
extern __imp_bGetDevModePerUser:PANYARGS
bGetDevModePerUser TEXTEQU <__imp_bGetDevModePerUser>
extern __imp_bSetDevModePerUser:PANYARGS
bSetDevModePerUser TEXTEQU <__imp_bSetDevModePerUser>
