extern __imp_YDriverUnloadComplete:PANYARGS
YDriverUnloadComplete TEXTEQU <__imp_YDriverUnloadComplete>
extern __imp_YEndDocPrinter:PANYARGS
YEndDocPrinter TEXTEQU <__imp_YEndDocPrinter>
extern __imp_YFlushPrinter:PANYARGS
YFlushPrinter TEXTEQU <__imp_YFlushPrinter>
extern __imp_YGetPrinter:PANYARGS
YGetPrinter TEXTEQU <__imp_YGetPrinter>
extern __imp_YGetPrinterDriver2:PANYARGS
YGetPrinterDriver2 TEXTEQU <__imp_YGetPrinterDriver2>
extern __imp_YGetPrinterDriverDirectory:PANYARGS
YGetPrinterDriverDirectory TEXTEQU <__imp_YGetPrinterDriverDirectory>
extern __imp_YReadPrinter:PANYARGS
YReadPrinter TEXTEQU <__imp_YReadPrinter>
extern __imp_YSeekPrinter:PANYARGS
YSeekPrinter TEXTEQU <__imp_YSeekPrinter>
extern __imp_YSetJob:PANYARGS
YSetJob TEXTEQU <__imp_YSetJob>
extern __imp_YSetPort:PANYARGS
YSetPort TEXTEQU <__imp_YSetPort>
extern __imp_YSplReadPrinter:PANYARGS
YSplReadPrinter TEXTEQU <__imp_YSplReadPrinter>
extern __imp_YWritePrinter:PANYARGS
YWritePrinter TEXTEQU <__imp_YWritePrinter>
