extern __imp_SQLBindCol:PANYARGS
SQLBindCol TEXTEQU <__imp_SQLBindCol>
extern __imp_SQLCancel:PANYARGS
SQLCancel TEXTEQU <__imp_SQLCancel>
extern __imp_SQLColAttributeW:PANYARGS
SQLColAttributeW TEXTEQU <__imp_SQLColAttributeW>
extern __imp_SQLConnectW:PANYARGS
SQLConnectW TEXTEQU <__imp_SQLConnectW>
extern __imp_SQLDescribeColW:PANYARGS
SQLDescribeColW TEXTEQU <__imp_SQLDescribeColW>
extern __imp_SQLDisconnect:PANYARGS
SQLDisconnect TEXTEQU <__imp_SQLDisconnect>
extern __imp_sqlsrv32_ordinal10:PANYARGS
sqlsrv32_ordinal10 TEXTEQU <__imp_sqlsrv32_ordinal10>
extern __imp_SQLExecDirectW:PANYARGS
SQLExecDirectW TEXTEQU <__imp_SQLExecDirectW>
extern __imp_SQLExecute:PANYARGS
SQLExecute TEXTEQU <__imp_SQLExecute>
extern __imp_SQLFetch:PANYARGS
SQLFetch TEXTEQU <__imp_SQLFetch>
extern __imp_sqlsrv32_ordinal14:PANYARGS
sqlsrv32_ordinal14 TEXTEQU <__imp_sqlsrv32_ordinal14>
extern __imp_sqlsrv32_ordinal15:PANYARGS
sqlsrv32_ordinal15 TEXTEQU <__imp_sqlsrv32_ordinal15>
extern __imp_SQLFreeStmt:PANYARGS
SQLFreeStmt TEXTEQU <__imp_SQLFreeStmt>
extern __imp_SQLGetCursorNameW:PANYARGS
SQLGetCursorNameW TEXTEQU <__imp_SQLGetCursorNameW>
extern __imp_SQLNumResultCols:PANYARGS
SQLNumResultCols TEXTEQU <__imp_SQLNumResultCols>
extern __imp_SQLPrepareW:PANYARGS
SQLPrepareW TEXTEQU <__imp_SQLPrepareW>
extern __imp_SQLRowCount:PANYARGS
SQLRowCount TEXTEQU <__imp_SQLRowCount>
extern __imp_SQLSetCursorNameW:PANYARGS
SQLSetCursorNameW TEXTEQU <__imp_SQLSetCursorNameW>
extern __imp_sqlsrv32_ordinal22:PANYARGS
sqlsrv32_ordinal22 TEXTEQU <__imp_sqlsrv32_ordinal22>
extern __imp_sqlsrv32_ordinal23:PANYARGS
sqlsrv32_ordinal23 TEXTEQU <__imp_sqlsrv32_ordinal23>
extern __imp_SQLBulkOperations:PANYARGS
SQLBulkOperations TEXTEQU <__imp_SQLBulkOperations>
extern __imp_sqlsrv32_ordinal25:PANYARGS
sqlsrv32_ordinal25 TEXTEQU <__imp_sqlsrv32_ordinal25>
extern __imp_sqlsrv32_ordinal26:PANYARGS
sqlsrv32_ordinal26 TEXTEQU <__imp_sqlsrv32_ordinal26>
extern __imp_sqlsrv32_ordinal27:PANYARGS
sqlsrv32_ordinal27 TEXTEQU <__imp_sqlsrv32_ordinal27>
extern __imp_sqlsrv32_ordinal28:PANYARGS
sqlsrv32_ordinal28 TEXTEQU <__imp_sqlsrv32_ordinal28>
extern __imp_sqlsrv32_ordinal29:PANYARGS
sqlsrv32_ordinal29 TEXTEQU <__imp_sqlsrv32_ordinal29>
extern __imp_sqlsrv32_ordinal30:PANYARGS
sqlsrv32_ordinal30 TEXTEQU <__imp_sqlsrv32_ordinal30>
extern __imp_sqlsrv32_ordinal31:PANYARGS
sqlsrv32_ordinal31 TEXTEQU <__imp_sqlsrv32_ordinal31>
extern __imp_sqlsrv32_ordinal32:PANYARGS
sqlsrv32_ordinal32 TEXTEQU <__imp_sqlsrv32_ordinal32>
extern __imp_sqlsrv32_ordinal33:PANYARGS
sqlsrv32_ordinal33 TEXTEQU <__imp_sqlsrv32_ordinal33>
extern __imp_sqlsrv32_ordinal34:PANYARGS
sqlsrv32_ordinal34 TEXTEQU <__imp_sqlsrv32_ordinal34>
extern __imp_sqlsrv32_ordinal35:PANYARGS
sqlsrv32_ordinal35 TEXTEQU <__imp_sqlsrv32_ordinal35>
extern __imp_sqlsrv32_ordinal36:PANYARGS
sqlsrv32_ordinal36 TEXTEQU <__imp_sqlsrv32_ordinal36>
extern __imp_sqlsrv32_ordinal37:PANYARGS
sqlsrv32_ordinal37 TEXTEQU <__imp_sqlsrv32_ordinal37>
extern __imp_sqlsrv32_ordinal38:PANYARGS
sqlsrv32_ordinal38 TEXTEQU <__imp_sqlsrv32_ordinal38>
extern __imp_sqlsrv32_ordinal39:PANYARGS
sqlsrv32_ordinal39 TEXTEQU <__imp_sqlsrv32_ordinal39>
extern __imp_SQLColumnsW:PANYARGS
SQLColumnsW TEXTEQU <__imp_SQLColumnsW>
extern __imp_SQLDriverConnectW:PANYARGS
SQLDriverConnectW TEXTEQU <__imp_SQLDriverConnectW>
extern __imp_SQLGetConnectOptionW:PANYARGS
SQLGetConnectOptionW TEXTEQU <__imp_SQLGetConnectOptionW>
extern __imp_SQLGetData:PANYARGS
SQLGetData TEXTEQU <__imp_SQLGetData>
extern __imp_SQLGetFunctions:PANYARGS
SQLGetFunctions TEXTEQU <__imp_SQLGetFunctions>
extern __imp_SQLGetInfoW:PANYARGS
SQLGetInfoW TEXTEQU <__imp_SQLGetInfoW>
extern __imp_sqlsrv32_ordinal46:PANYARGS
sqlsrv32_ordinal46 TEXTEQU <__imp_sqlsrv32_ordinal46>
extern __imp_SQLGetTypeInfoW:PANYARGS
SQLGetTypeInfoW TEXTEQU <__imp_SQLGetTypeInfoW>
extern __imp_SQLParamData:PANYARGS
SQLParamData TEXTEQU <__imp_SQLParamData>
extern __imp_SQLPutData:PANYARGS
SQLPutData TEXTEQU <__imp_SQLPutData>
extern __imp_SQLSetConnectOptionW:PANYARGS
SQLSetConnectOptionW TEXTEQU <__imp_SQLSetConnectOptionW>
extern __imp_sqlsrv32_ordinal51:PANYARGS
sqlsrv32_ordinal51 TEXTEQU <__imp_sqlsrv32_ordinal51>
extern __imp_SQLSpecialColumnsW:PANYARGS
SQLSpecialColumnsW TEXTEQU <__imp_SQLSpecialColumnsW>
extern __imp_SQLStatisticsW:PANYARGS
SQLStatisticsW TEXTEQU <__imp_SQLStatisticsW>
extern __imp_SQLTablesW:PANYARGS
SQLTablesW TEXTEQU <__imp_SQLTablesW>
extern __imp_SQLBrowseConnectW:PANYARGS
SQLBrowseConnectW TEXTEQU <__imp_SQLBrowseConnectW>
extern __imp_SQLColumnPrivilegesW:PANYARGS
SQLColumnPrivilegesW TEXTEQU <__imp_SQLColumnPrivilegesW>
extern __imp_sqlsrv32_ordinal57:PANYARGS
sqlsrv32_ordinal57 TEXTEQU <__imp_sqlsrv32_ordinal57>
extern __imp_SQLDescribeParam:PANYARGS
SQLDescribeParam TEXTEQU <__imp_SQLDescribeParam>
extern __imp_SQLExtendedFetch:PANYARGS
SQLExtendedFetch TEXTEQU <__imp_SQLExtendedFetch>
extern __imp_SQLForeignKeysW:PANYARGS
SQLForeignKeysW TEXTEQU <__imp_SQLForeignKeysW>
extern __imp_SQLMoreResults:PANYARGS
SQLMoreResults TEXTEQU <__imp_SQLMoreResults>
extern __imp_SQLNativeSqlW:PANYARGS
SQLNativeSqlW TEXTEQU <__imp_SQLNativeSqlW>
extern __imp_SQLNumParams:PANYARGS
SQLNumParams TEXTEQU <__imp_SQLNumParams>
extern __imp_SQLParamOptions:PANYARGS
SQLParamOptions TEXTEQU <__imp_SQLParamOptions>
extern __imp_SQLPrimaryKeysW:PANYARGS
SQLPrimaryKeysW TEXTEQU <__imp_SQLPrimaryKeysW>
extern __imp_SQLProcedureColumnsW:PANYARGS
SQLProcedureColumnsW TEXTEQU <__imp_SQLProcedureColumnsW>
extern __imp_SQLProceduresW:PANYARGS
SQLProceduresW TEXTEQU <__imp_SQLProceduresW>
extern __imp_SQLSetPos:PANYARGS
SQLSetPos TEXTEQU <__imp_SQLSetPos>
extern __imp_SQLSetScrollOptions:PANYARGS
SQLSetScrollOptions TEXTEQU <__imp_SQLSetScrollOptions>
extern __imp_SQLTablePrivilegesW:PANYARGS
SQLTablePrivilegesW TEXTEQU <__imp_SQLTablePrivilegesW>
extern __imp_sqlsrv32_ordinal71:PANYARGS
sqlsrv32_ordinal71 TEXTEQU <__imp_sqlsrv32_ordinal71>
extern __imp_SQLBindParameter:PANYARGS
SQLBindParameter TEXTEQU <__imp_SQLBindParameter>
extern __imp_sqlsrv32_ordinal73:PANYARGS
sqlsrv32_ordinal73 TEXTEQU <__imp_sqlsrv32_ordinal73>
extern __imp_sqlsrv32_ordinal74:PANYARGS
sqlsrv32_ordinal74 TEXTEQU <__imp_sqlsrv32_ordinal74>
extern __imp_sqlsrv32_ordinal75:PANYARGS
sqlsrv32_ordinal75 TEXTEQU <__imp_sqlsrv32_ordinal75>
extern __imp_sqlsrv32_ordinal76:PANYARGS
sqlsrv32_ordinal76 TEXTEQU <__imp_sqlsrv32_ordinal76>
extern __imp_sqlsrv32_ordinal77:PANYARGS
sqlsrv32_ordinal77 TEXTEQU <__imp_sqlsrv32_ordinal77>
extern __imp_sqlsrv32_ordinal78:PANYARGS
sqlsrv32_ordinal78 TEXTEQU <__imp_sqlsrv32_ordinal78>
extern __imp_sqlsrv32_ordinal79:PANYARGS
sqlsrv32_ordinal79 TEXTEQU <__imp_sqlsrv32_ordinal79>
extern __imp_sqlsrv32_ordinal80:PANYARGS
sqlsrv32_ordinal80 TEXTEQU <__imp_sqlsrv32_ordinal80>
extern __imp_sqlsrv32_ordinal81:PANYARGS
sqlsrv32_ordinal81 TEXTEQU <__imp_sqlsrv32_ordinal81>
extern __imp_sqlsrv32_ordinal82:PANYARGS
sqlsrv32_ordinal82 TEXTEQU <__imp_sqlsrv32_ordinal82>
extern __imp_sqlsrv32_ordinal83:PANYARGS
sqlsrv32_ordinal83 TEXTEQU <__imp_sqlsrv32_ordinal83>
extern __imp_sqlsrv32_ordinal84:PANYARGS
sqlsrv32_ordinal84 TEXTEQU <__imp_sqlsrv32_ordinal84>
extern __imp_sqlsrv32_ordinal85:PANYARGS
sqlsrv32_ordinal85 TEXTEQU <__imp_sqlsrv32_ordinal85>
extern __imp_sqlsrv32_ordinal86:PANYARGS
sqlsrv32_ordinal86 TEXTEQU <__imp_sqlsrv32_ordinal86>
extern __imp_sqlsrv32_ordinal87:PANYARGS
sqlsrv32_ordinal87 TEXTEQU <__imp_sqlsrv32_ordinal87>
extern __imp_sqlsrv32_ordinal88:PANYARGS
sqlsrv32_ordinal88 TEXTEQU <__imp_sqlsrv32_ordinal88>
extern __imp_sqlsrv32_ordinal89:PANYARGS
sqlsrv32_ordinal89 TEXTEQU <__imp_sqlsrv32_ordinal89>
extern __imp_sqlsrv32_ordinal90:PANYARGS
sqlsrv32_ordinal90 TEXTEQU <__imp_sqlsrv32_ordinal90>
extern __imp_sqlsrv32_ordinal91:PANYARGS
sqlsrv32_ordinal91 TEXTEQU <__imp_sqlsrv32_ordinal91>
extern __imp_sqlsrv32_ordinal92:PANYARGS
sqlsrv32_ordinal92 TEXTEQU <__imp_sqlsrv32_ordinal92>
extern __imp_sqlsrv32_ordinal93:PANYARGS
sqlsrv32_ordinal93 TEXTEQU <__imp_sqlsrv32_ordinal93>
extern __imp_sqlsrv32_ordinal94:PANYARGS
sqlsrv32_ordinal94 TEXTEQU <__imp_sqlsrv32_ordinal94>
extern __imp_sqlsrv32_ordinal95:PANYARGS
sqlsrv32_ordinal95 TEXTEQU <__imp_sqlsrv32_ordinal95>
extern __imp_sqlsrv32_ordinal96:PANYARGS
sqlsrv32_ordinal96 TEXTEQU <__imp_sqlsrv32_ordinal96>
extern __imp_sqlsrv32_ordinal97:PANYARGS
sqlsrv32_ordinal97 TEXTEQU <__imp_sqlsrv32_ordinal97>
extern __imp_sqlsrv32_ordinal98:PANYARGS
sqlsrv32_ordinal98 TEXTEQU <__imp_sqlsrv32_ordinal98>
extern __imp_sqlsrv32_ordinal99:PANYARGS
sqlsrv32_ordinal99 TEXTEQU <__imp_sqlsrv32_ordinal99>
extern __imp_sqlsrv32_ordinal100:PANYARGS
sqlsrv32_ordinal100 TEXTEQU <__imp_sqlsrv32_ordinal100>
extern __imp_SQLAllocHandle:PANYARGS
SQLAllocHandle TEXTEQU <__imp_SQLAllocHandle>
extern __imp_sqlsrv32_ordinal102:PANYARGS
sqlsrv32_ordinal102 TEXTEQU <__imp_sqlsrv32_ordinal102>
extern __imp_SQLCloseCursor:PANYARGS
SQLCloseCursor TEXTEQU <__imp_SQLCloseCursor>
extern __imp_SQLCopyDesc:PANYARGS
SQLCopyDesc TEXTEQU <__imp_SQLCopyDesc>
extern __imp_SQLEndTran:PANYARGS
SQLEndTran TEXTEQU <__imp_SQLEndTran>
extern __imp_SQLFreeHandle:PANYARGS
SQLFreeHandle TEXTEQU <__imp_SQLFreeHandle>
extern __imp_SQLGetConnectAttrW:PANYARGS
SQLGetConnectAttrW TEXTEQU <__imp_SQLGetConnectAttrW>
extern __imp_SQLGetDescFieldW:PANYARGS
SQLGetDescFieldW TEXTEQU <__imp_SQLGetDescFieldW>
extern __imp_SQLGetDescRecW:PANYARGS
SQLGetDescRecW TEXTEQU <__imp_SQLGetDescRecW>
extern __imp_SQLGetDiagFieldW:PANYARGS
SQLGetDiagFieldW TEXTEQU <__imp_SQLGetDiagFieldW>
extern __imp_SQLGetDiagRecW:PANYARGS
SQLGetDiagRecW TEXTEQU <__imp_SQLGetDiagRecW>
extern __imp_SQLGetEnvAttr:PANYARGS
SQLGetEnvAttr TEXTEQU <__imp_SQLGetEnvAttr>
extern __imp_sqlsrv32_ordinal113:PANYARGS
sqlsrv32_ordinal113 TEXTEQU <__imp_sqlsrv32_ordinal113>
extern __imp_SQLGetStmtAttrW:PANYARGS
SQLGetStmtAttrW TEXTEQU <__imp_SQLGetStmtAttrW>
extern __imp_sqlsrv32_ordinal115:PANYARGS
sqlsrv32_ordinal115 TEXTEQU <__imp_sqlsrv32_ordinal115>
extern __imp_SQLSetConnectAttrW:PANYARGS
SQLSetConnectAttrW TEXTEQU <__imp_SQLSetConnectAttrW>
extern __imp_SQLSetDescFieldW:PANYARGS
SQLSetDescFieldW TEXTEQU <__imp_SQLSetDescFieldW>
extern __imp_SQLSetDescRec:PANYARGS
SQLSetDescRec TEXTEQU <__imp_SQLSetDescRec>
extern __imp_SQLSetEnvAttr:PANYARGS
SQLSetEnvAttr TEXTEQU <__imp_SQLSetEnvAttr>
extern __imp_SQLSetStmtAttrW:PANYARGS
SQLSetStmtAttrW TEXTEQU <__imp_SQLSetStmtAttrW>
extern __imp_SQLFetchScroll:PANYARGS
SQLFetchScroll TEXTEQU <__imp_SQLFetchScroll>
extern __imp_sqlsrv32_ordinal122:PANYARGS
sqlsrv32_ordinal122 TEXTEQU <__imp_sqlsrv32_ordinal122>
extern __imp_sqlsrv32_ordinal123:PANYARGS
sqlsrv32_ordinal123 TEXTEQU <__imp_sqlsrv32_ordinal123>
extern __imp_sqlsrv32_ordinal124:PANYARGS
sqlsrv32_ordinal124 TEXTEQU <__imp_sqlsrv32_ordinal124>
extern __imp_sqlsrv32_ordinal125:PANYARGS
sqlsrv32_ordinal125 TEXTEQU <__imp_sqlsrv32_ordinal125>
extern __imp_sqlsrv32_ordinal126:PANYARGS
sqlsrv32_ordinal126 TEXTEQU <__imp_sqlsrv32_ordinal126>
extern __imp_sqlsrv32_ordinal127:PANYARGS
sqlsrv32_ordinal127 TEXTEQU <__imp_sqlsrv32_ordinal127>
extern __imp_sqlsrv32_ordinal128:PANYARGS
sqlsrv32_ordinal128 TEXTEQU <__imp_sqlsrv32_ordinal128>
extern __imp_sqlsrv32_ordinal129:PANYARGS
sqlsrv32_ordinal129 TEXTEQU <__imp_sqlsrv32_ordinal129>
extern __imp_sqlsrv32_ordinal130:PANYARGS
sqlsrv32_ordinal130 TEXTEQU <__imp_sqlsrv32_ordinal130>
extern __imp_sqlsrv32_ordinal131:PANYARGS
sqlsrv32_ordinal131 TEXTEQU <__imp_sqlsrv32_ordinal131>
extern __imp_sqlsrv32_ordinal132:PANYARGS
sqlsrv32_ordinal132 TEXTEQU <__imp_sqlsrv32_ordinal132>
extern __imp_sqlsrv32_ordinal133:PANYARGS
sqlsrv32_ordinal133 TEXTEQU <__imp_sqlsrv32_ordinal133>
extern __imp_sqlsrv32_ordinal134:PANYARGS
sqlsrv32_ordinal134 TEXTEQU <__imp_sqlsrv32_ordinal134>
extern __imp_sqlsrv32_ordinal135:PANYARGS
sqlsrv32_ordinal135 TEXTEQU <__imp_sqlsrv32_ordinal135>
extern __imp_sqlsrv32_ordinal136:PANYARGS
sqlsrv32_ordinal136 TEXTEQU <__imp_sqlsrv32_ordinal136>
extern __imp_sqlsrv32_ordinal137:PANYARGS
sqlsrv32_ordinal137 TEXTEQU <__imp_sqlsrv32_ordinal137>
extern __imp_sqlsrv32_ordinal138:PANYARGS
sqlsrv32_ordinal138 TEXTEQU <__imp_sqlsrv32_ordinal138>
extern __imp_sqlsrv32_ordinal139:PANYARGS
sqlsrv32_ordinal139 TEXTEQU <__imp_sqlsrv32_ordinal139>
extern __imp_sqlsrv32_ordinal140:PANYARGS
sqlsrv32_ordinal140 TEXTEQU <__imp_sqlsrv32_ordinal140>
extern __imp_sqlsrv32_ordinal141:PANYARGS
sqlsrv32_ordinal141 TEXTEQU <__imp_sqlsrv32_ordinal141>
extern __imp_sqlsrv32_ordinal142:PANYARGS
sqlsrv32_ordinal142 TEXTEQU <__imp_sqlsrv32_ordinal142>
extern __imp_sqlsrv32_ordinal143:PANYARGS
sqlsrv32_ordinal143 TEXTEQU <__imp_sqlsrv32_ordinal143>
extern __imp_sqlsrv32_ordinal144:PANYARGS
sqlsrv32_ordinal144 TEXTEQU <__imp_sqlsrv32_ordinal144>
extern __imp_sqlsrv32_ordinal145:PANYARGS
sqlsrv32_ordinal145 TEXTEQU <__imp_sqlsrv32_ordinal145>
extern __imp_sqlsrv32_ordinal146:PANYARGS
sqlsrv32_ordinal146 TEXTEQU <__imp_sqlsrv32_ordinal146>
extern __imp_sqlsrv32_ordinal147:PANYARGS
sqlsrv32_ordinal147 TEXTEQU <__imp_sqlsrv32_ordinal147>
extern __imp_sqlsrv32_ordinal148:PANYARGS
sqlsrv32_ordinal148 TEXTEQU <__imp_sqlsrv32_ordinal148>
extern __imp_sqlsrv32_ordinal149:PANYARGS
sqlsrv32_ordinal149 TEXTEQU <__imp_sqlsrv32_ordinal149>
extern __imp_sqlsrv32_ordinal150:PANYARGS
sqlsrv32_ordinal150 TEXTEQU <__imp_sqlsrv32_ordinal150>
extern __imp_sqlsrv32_ordinal151:PANYARGS
sqlsrv32_ordinal151 TEXTEQU <__imp_sqlsrv32_ordinal151>
extern __imp_sqlsrv32_ordinal152:PANYARGS
sqlsrv32_ordinal152 TEXTEQU <__imp_sqlsrv32_ordinal152>
extern __imp_sqlsrv32_ordinal153:PANYARGS
sqlsrv32_ordinal153 TEXTEQU <__imp_sqlsrv32_ordinal153>
extern __imp_sqlsrv32_ordinal154:PANYARGS
sqlsrv32_ordinal154 TEXTEQU <__imp_sqlsrv32_ordinal154>
extern __imp_sqlsrv32_ordinal155:PANYARGS
sqlsrv32_ordinal155 TEXTEQU <__imp_sqlsrv32_ordinal155>
extern __imp_sqlsrv32_ordinal156:PANYARGS
sqlsrv32_ordinal156 TEXTEQU <__imp_sqlsrv32_ordinal156>
extern __imp_sqlsrv32_ordinal157:PANYARGS
sqlsrv32_ordinal157 TEXTEQU <__imp_sqlsrv32_ordinal157>
extern __imp_sqlsrv32_ordinal158:PANYARGS
sqlsrv32_ordinal158 TEXTEQU <__imp_sqlsrv32_ordinal158>
extern __imp_sqlsrv32_ordinal159:PANYARGS
sqlsrv32_ordinal159 TEXTEQU <__imp_sqlsrv32_ordinal159>
extern __imp_sqlsrv32_ordinal160:PANYARGS
sqlsrv32_ordinal160 TEXTEQU <__imp_sqlsrv32_ordinal160>
extern __imp_sqlsrv32_ordinal161:PANYARGS
sqlsrv32_ordinal161 TEXTEQU <__imp_sqlsrv32_ordinal161>
extern __imp_sqlsrv32_ordinal162:PANYARGS
sqlsrv32_ordinal162 TEXTEQU <__imp_sqlsrv32_ordinal162>
extern __imp_sqlsrv32_ordinal163:PANYARGS
sqlsrv32_ordinal163 TEXTEQU <__imp_sqlsrv32_ordinal163>
extern __imp_sqlsrv32_ordinal164:PANYARGS
sqlsrv32_ordinal164 TEXTEQU <__imp_sqlsrv32_ordinal164>
extern __imp_sqlsrv32_ordinal165:PANYARGS
sqlsrv32_ordinal165 TEXTEQU <__imp_sqlsrv32_ordinal165>
extern __imp_sqlsrv32_ordinal166:PANYARGS
sqlsrv32_ordinal166 TEXTEQU <__imp_sqlsrv32_ordinal166>
extern __imp_sqlsrv32_ordinal167:PANYARGS
sqlsrv32_ordinal167 TEXTEQU <__imp_sqlsrv32_ordinal167>
extern __imp_sqlsrv32_ordinal168:PANYARGS
sqlsrv32_ordinal168 TEXTEQU <__imp_sqlsrv32_ordinal168>
extern __imp_sqlsrv32_ordinal169:PANYARGS
sqlsrv32_ordinal169 TEXTEQU <__imp_sqlsrv32_ordinal169>
extern __imp_sqlsrv32_ordinal170:PANYARGS
sqlsrv32_ordinal170 TEXTEQU <__imp_sqlsrv32_ordinal170>
extern __imp_sqlsrv32_ordinal171:PANYARGS
sqlsrv32_ordinal171 TEXTEQU <__imp_sqlsrv32_ordinal171>
extern __imp_sqlsrv32_ordinal172:PANYARGS
sqlsrv32_ordinal172 TEXTEQU <__imp_sqlsrv32_ordinal172>
extern __imp_sqlsrv32_ordinal173:PANYARGS
sqlsrv32_ordinal173 TEXTEQU <__imp_sqlsrv32_ordinal173>
extern __imp_sqlsrv32_ordinal174:PANYARGS
sqlsrv32_ordinal174 TEXTEQU <__imp_sqlsrv32_ordinal174>
extern __imp_sqlsrv32_ordinal175:PANYARGS
sqlsrv32_ordinal175 TEXTEQU <__imp_sqlsrv32_ordinal175>
extern __imp_sqlsrv32_ordinal176:PANYARGS
sqlsrv32_ordinal176 TEXTEQU <__imp_sqlsrv32_ordinal176>
extern __imp_sqlsrv32_ordinal177:PANYARGS
sqlsrv32_ordinal177 TEXTEQU <__imp_sqlsrv32_ordinal177>
extern __imp_sqlsrv32_ordinal178:PANYARGS
sqlsrv32_ordinal178 TEXTEQU <__imp_sqlsrv32_ordinal178>
extern __imp_sqlsrv32_ordinal179:PANYARGS
sqlsrv32_ordinal179 TEXTEQU <__imp_sqlsrv32_ordinal179>
extern __imp_sqlsrv32_ordinal180:PANYARGS
sqlsrv32_ordinal180 TEXTEQU <__imp_sqlsrv32_ordinal180>
extern __imp_sqlsrv32_ordinal181:PANYARGS
sqlsrv32_ordinal181 TEXTEQU <__imp_sqlsrv32_ordinal181>
extern __imp_sqlsrv32_ordinal182:PANYARGS
sqlsrv32_ordinal182 TEXTEQU <__imp_sqlsrv32_ordinal182>
extern __imp_sqlsrv32_ordinal183:PANYARGS
sqlsrv32_ordinal183 TEXTEQU <__imp_sqlsrv32_ordinal183>
extern __imp_sqlsrv32_ordinal184:PANYARGS
sqlsrv32_ordinal184 TEXTEQU <__imp_sqlsrv32_ordinal184>
extern __imp_sqlsrv32_ordinal185:PANYARGS
sqlsrv32_ordinal185 TEXTEQU <__imp_sqlsrv32_ordinal185>
extern __imp_sqlsrv32_ordinal186:PANYARGS
sqlsrv32_ordinal186 TEXTEQU <__imp_sqlsrv32_ordinal186>
extern __imp_sqlsrv32_ordinal187:PANYARGS
sqlsrv32_ordinal187 TEXTEQU <__imp_sqlsrv32_ordinal187>
extern __imp_sqlsrv32_ordinal188:PANYARGS
sqlsrv32_ordinal188 TEXTEQU <__imp_sqlsrv32_ordinal188>
extern __imp_sqlsrv32_ordinal189:PANYARGS
sqlsrv32_ordinal189 TEXTEQU <__imp_sqlsrv32_ordinal189>
extern __imp_sqlsrv32_ordinal190:PANYARGS
sqlsrv32_ordinal190 TEXTEQU <__imp_sqlsrv32_ordinal190>
extern __imp_sqlsrv32_ordinal191:PANYARGS
sqlsrv32_ordinal191 TEXTEQU <__imp_sqlsrv32_ordinal191>
extern __imp_sqlsrv32_ordinal192:PANYARGS
sqlsrv32_ordinal192 TEXTEQU <__imp_sqlsrv32_ordinal192>
extern __imp_sqlsrv32_ordinal193:PANYARGS
sqlsrv32_ordinal193 TEXTEQU <__imp_sqlsrv32_ordinal193>
extern __imp_sqlsrv32_ordinal194:PANYARGS
sqlsrv32_ordinal194 TEXTEQU <__imp_sqlsrv32_ordinal194>
extern __imp_sqlsrv32_ordinal195:PANYARGS
sqlsrv32_ordinal195 TEXTEQU <__imp_sqlsrv32_ordinal195>
extern __imp_sqlsrv32_ordinal196:PANYARGS
sqlsrv32_ordinal196 TEXTEQU <__imp_sqlsrv32_ordinal196>
extern __imp_sqlsrv32_ordinal197:PANYARGS
sqlsrv32_ordinal197 TEXTEQU <__imp_sqlsrv32_ordinal197>
extern __imp_sqlsrv32_ordinal198:PANYARGS
sqlsrv32_ordinal198 TEXTEQU <__imp_sqlsrv32_ordinal198>
extern __imp_sqlsrv32_ordinal199:PANYARGS
sqlsrv32_ordinal199 TEXTEQU <__imp_sqlsrv32_ordinal199>
extern __imp_LibMain:PANYARGS
LibMain TEXTEQU <__imp_LibMain>
extern __imp_ConfigDSNW:PANYARGS
ConfigDSNW TEXTEQU <__imp_ConfigDSNW>
extern __imp_ConfigDriverW:PANYARGS
ConfigDriverW TEXTEQU <__imp_ConfigDriverW>
extern __imp_SQLDebug:PANYARGS
SQLDebug TEXTEQU <__imp_SQLDebug>
extern __imp_BCP_batch:PANYARGS
BCP_batch TEXTEQU <__imp_BCP_batch>
extern __imp_BCP_bind:PANYARGS
BCP_bind TEXTEQU <__imp_BCP_bind>
extern __imp_BCP_colfmt:PANYARGS
BCP_colfmt TEXTEQU <__imp_BCP_colfmt>
extern __imp_sqlsrv32_ordinal207:PANYARGS
sqlsrv32_ordinal207 TEXTEQU <__imp_sqlsrv32_ordinal207>
extern __imp_BCP_collen:PANYARGS
BCP_collen TEXTEQU <__imp_BCP_collen>
extern __imp_BCP_colptr:PANYARGS
BCP_colptr TEXTEQU <__imp_BCP_colptr>
extern __imp_BCP_columns:PANYARGS
BCP_columns TEXTEQU <__imp_BCP_columns>
extern __imp_BCP_control:PANYARGS
BCP_control TEXTEQU <__imp_BCP_control>
extern __imp_BCP_done:PANYARGS
BCP_done TEXTEQU <__imp_BCP_done>
extern __imp_BCP_init:PANYARGS
BCP_init TEXTEQU <__imp_BCP_init>
extern __imp_BCP_exec:PANYARGS
BCP_exec TEXTEQU <__imp_BCP_exec>
extern __imp_BCP_moretext:PANYARGS
BCP_moretext TEXTEQU <__imp_BCP_moretext>
extern __imp_BCP_sendrow:PANYARGS
BCP_sendrow TEXTEQU <__imp_BCP_sendrow>
extern __imp_BCP_readfmt:PANYARGS
BCP_readfmt TEXTEQU <__imp_BCP_readfmt>
extern __imp_BCP_writefmt:PANYARGS
BCP_writefmt TEXTEQU <__imp_BCP_writefmt>
extern __imp_ConnectDlgProc:PANYARGS
ConnectDlgProc TEXTEQU <__imp_ConnectDlgProc>
extern __imp_WizDSNDlgProc:PANYARGS
WizDSNDlgProc TEXTEQU <__imp_WizDSNDlgProc>
extern __imp_WizIntSecurityDlgProc:PANYARGS
WizIntSecurityDlgProc TEXTEQU <__imp_WizIntSecurityDlgProc>
extern __imp_WizDatabaseDlgProc:PANYARGS
WizDatabaseDlgProc TEXTEQU <__imp_WizDatabaseDlgProc>
extern __imp_WizLanguageDlgProc:PANYARGS
WizLanguageDlgProc TEXTEQU <__imp_WizLanguageDlgProc>
extern __imp_FinishDlgProc:PANYARGS
FinishDlgProc TEXTEQU <__imp_FinishDlgProc>
extern __imp_TestDlgProc:PANYARGS
TestDlgProc TEXTEQU <__imp_TestDlgProc>
extern __imp_BCP_getcolfmt:PANYARGS
BCP_getcolfmt TEXTEQU <__imp_BCP_getcolfmt>
extern __imp_BCP_setcolfmt:PANYARGS
BCP_setcolfmt TEXTEQU <__imp_BCP_setcolfmt>
