extern __imp_CreateFirstRunRp:PANYARGS
CreateFirstRunRp TEXTEQU <__imp_CreateFirstRunRp>
extern __imp_CreateSnapshot:PANYARGS
CreateSnapshot TEXTEQU <__imp_CreateSnapshot>
extern __imp_DisableFIFO:PANYARGS
DisableFIFO TEXTEQU <__imp_DisableFIFO>
extern __imp_DisableSR:PANYARGS
DisableSR TEXTEQU <__imp_DisableSR>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_EnableFIFO:PANYARGS
EnableFIFO TEXTEQU <__imp_EnableFIFO>
extern __imp_EnableSR:PANYARGS
EnableSR TEXTEQU <__imp_EnableSR>
extern __imp_EnableSREx:PANYARGS
EnableSREx TEXTEQU <__imp_EnableSREx>
extern __imp_ResetSR:PANYARGS
ResetSR TEXTEQU <__imp_ResetSR>
extern __imp_RestoreSnapshot:PANYARGS
RestoreSnapshot TEXTEQU <__imp_RestoreSnapshot>
extern __imp_SRCompress:PANYARGS
SRCompress TEXTEQU <__imp_SRCompress>
extern __imp_SRFifo:PANYARGS
SRFifo TEXTEQU <__imp_SRFifo>
extern __imp_SRFreeze:PANYARGS
SRFreeze TEXTEQU <__imp_SRFreeze>
extern __imp_SRNotify:PANYARGS
SRNotify TEXTEQU <__imp_SRNotify>
extern __imp_SRPrintState:PANYARGS
SRPrintState TEXTEQU <__imp_SRPrintState>
extern __imp_SRRegisterSnapshotCallback:PANYARGS
SRRegisterSnapshotCallback TEXTEQU <__imp_SRRegisterSnapshotCallback>
extern __imp_SRRemoveRestorePoint:PANYARGS
SRRemoveRestorePoint TEXTEQU <__imp_SRRemoveRestorePoint>
extern __imp_SRSetRestorePointA:PANYARGS
SRSetRestorePoint  TEXTEQU <__imp_SRSetRestorePointA>
extern __imp_SRSetRestorePointW:PANYARGS
SRSetRestorePointW TEXTEQU <__imp_SRSetRestorePointW>
extern __imp_SRSwitchLog:PANYARGS
SRSwitchLog TEXTEQU <__imp_SRSwitchLog>
extern __imp_SRUnregisterSnapshotCallback:PANYARGS
SRUnregisterSnapshotCallback TEXTEQU <__imp_SRUnregisterSnapshotCallback>
extern __imp_SRUpdateDSSize:PANYARGS
SRUpdateDSSize TEXTEQU <__imp_SRUpdateDSSize>
extern __imp_SRUpdateMonitoredListA:PANYARGS
SRUpdateMonitoredList  TEXTEQU <__imp_SRUpdateMonitoredListA>
extern __imp_SRUpdateMonitoredListW:PANYARGS
SRUpdateMonitoredListW TEXTEQU <__imp_SRUpdateMonitoredListW>
