extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_IsSRFrozen:PANYARGS
IsSRFrozen TEXTEQU <__imp_IsSRFrozen>
extern __imp_CheckPrivilegesForRestore:PANYARGS
CheckPrivilegesForRestore TEXTEQU <__imp_CheckPrivilegesForRestore>
extern __imp_SRGetCplPropPage:PANYARGS
SRGetCplPropPage TEXTEQU <__imp_SRGetCplPropPage>
extern __imp_PrepareRestore:PANYARGS
PrepareRestore TEXTEQU <__imp_PrepareRestore>
extern __imp_InitiateRestore:PANYARGS
InitiateRestore TEXTEQU <__imp_InitiateRestore>
extern __imp_ResumeRestore:PANYARGS
ResumeRestore TEXTEQU <__imp_ResumeRestore>
extern __imp_InitializeChangeNotify:PANYARGS
InitializeChangeNotify TEXTEQU <__imp_InitializeChangeNotify>
extern __imp_PasswordChangeNotify:PANYARGS
PasswordChangeNotify TEXTEQU <__imp_PasswordChangeNotify>
extern __imp_InvokeDiskCleanup:PANYARGS
InvokeDiskCleanup TEXTEQU <__imp_InvokeDiskCleanup>
