extern __imp_CleanupCache:PANYARGS
CleanupCache TEXTEQU <__imp_CleanupCache>
extern __imp_DHDisableDeviceHost:PANYARGS
DHDisableDeviceHost TEXTEQU <__imp_DHDisableDeviceHost>
extern __imp_DHEnableDeviceHost:PANYARGS
DHEnableDeviceHost TEXTEQU <__imp_DHEnableDeviceHost>
extern __imp_DHSetICSInterfaces:PANYARGS
DHSetICSInterfaces TEXTEQU <__imp_DHSetICSInterfaces>
extern __imp_DHSetICSOff:PANYARGS
DHSetICSOff TEXTEQU <__imp_DHSetICSOff>
extern __imp_DeregisterNotification:PANYARGS
DeregisterNotification TEXTEQU <__imp_DeregisterNotification>
extern __imp_DeregisterService:PANYARGS
DeregisterService TEXTEQU <__imp_DeregisterService>
extern __imp_DeregisterServiceByUSN:PANYARGS
DeregisterServiceByUSN TEXTEQU <__imp_DeregisterServiceByUSN>
extern __imp_FindServices:PANYARGS
FindServices TEXTEQU <__imp_FindServices>
extern __imp_FindServicesCallback:PANYARGS
FindServicesCallback TEXTEQU <__imp_FindServicesCallback>
extern __imp_FindServicesCancel:PANYARGS
FindServicesCancel TEXTEQU <__imp_FindServicesCancel>
extern __imp_FindServicesClose:PANYARGS
FindServicesClose TEXTEQU <__imp_FindServicesClose>
extern __imp_FreeSsdpMessage:PANYARGS
FreeSsdpMessage TEXTEQU <__imp_FreeSsdpMessage>
extern __imp_GetFirstService:PANYARGS
GetFirstService TEXTEQU <__imp_GetFirstService>
extern __imp_GetNextService:PANYARGS
GetNextService TEXTEQU <__imp_GetNextService>
extern __imp_RegisterNotification:PANYARGS
RegisterNotification TEXTEQU <__imp_RegisterNotification>
extern __imp_RegisterService:PANYARGS
RegisterService TEXTEQU <__imp_RegisterService>
extern __imp_SsdpCleanup:PANYARGS
SsdpCleanup TEXTEQU <__imp_SsdpCleanup>
extern __imp_SsdpStartup:PANYARGS
SsdpStartup TEXTEQU <__imp_SsdpStartup>
