extern __imp_??0BUFFER@@QEAA@I@Z:PANYARGS
??0BUFFER@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER@@QEAA@I@Z>
extern __imp_??0BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??0BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??0BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z:PANYARGS
??0BUFFER_CHAIN_ITEM@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z>
extern __imp_??1BUFFER@@QEAA@XZ:PANYARGS
??1BUFFER@@QEAA@XZ TEXTEQU <__imp_??1BUFFER@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN_ITEM@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ>
extern __imp_??_FBUFFER@@QEAAXXZ:PANYARGS
??_FBUFFER@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER@@QEAAXXZ>
extern __imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ:PANYARGS
??_FBUFFER_CHAIN_ITEM@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ>
extern __imp_?QueryPtr@BUFFER@@QEBAPEAXXZ:PANYARGS
?QueryPtr@BUFFER@@QEBAPEAXXZ TEXTEQU <__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ>
extern __imp_?QuerySize@BUFFER@@QEBAIXZ:PANYARGS
?QuerySize@BUFFER@@QEBAIXZ TEXTEQU <__imp_?QuerySize@BUFFER@@QEBAIXZ>
extern __imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ:PANYARGS
?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ TEXTEQU <__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ>
extern __imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z:PANYARGS
?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z TEXTEQU <__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_GetProxyDllInfo:PANYARGS
GetProxyDllInfo TEXTEQU <__imp_GetProxyDllInfo>
extern __imp_MigrateRegisteredSTIAppsForWIAEvents:PANYARGS
MigrateRegisteredSTIAppsForWIAEvents TEXTEQU <__imp_MigrateRegisteredSTIAppsForWIAEvents>
extern __imp_RegSTIforWia:PANYARGS
RegSTIforWia TEXTEQU <__imp_RegSTIforWia>
extern __imp_StiCreateInstance:PANYARGS
StiCreateInstance TEXTEQU <__imp_StiCreateInstance>
extern __imp_StiCreateInstanceA:PANYARGS
StiCreateInstance  TEXTEQU <__imp_StiCreateInstanceA>
extern __imp_StiCreateInstanceW:PANYARGS
StiCreateInstanceW TEXTEQU <__imp_StiCreateInstanceW>
