extern __imp_??0BUFFER@@QEAA@I@Z:PANYARGS
??0BUFFER@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER@@QEAA@I@Z>
extern __imp_??0BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??0BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??0BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z:PANYARGS
??0BUFFER_CHAIN_ITEM@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z>
extern __imp_??1BUFFER@@QEAA@XZ:PANYARGS
??1BUFFER@@QEAA@XZ TEXTEQU <__imp_??1BUFFER@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN_ITEM@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ>
extern __imp_??_FBUFFER@@QEAAXXZ:PANYARGS
??_FBUFFER@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER@@QEAAXXZ>
extern __imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ:PANYARGS
??_FBUFFER_CHAIN_ITEM@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ>
extern __imp_AddDevice:PANYARGS
AddDevice TEXTEQU <__imp_AddDevice>
extern __imp_InstallWiaService:PANYARGS
InstallWiaService TEXTEQU <__imp_InstallWiaService>
extern __imp_MigrateDevice:PANYARGS
MigrateDevice TEXTEQU <__imp_MigrateDevice>
extern __imp_?QueryPtr@BUFFER@@QEBAPEAXXZ:PANYARGS
?QueryPtr@BUFFER@@QEBAPEAXXZ TEXTEQU <__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ>
extern __imp_?QuerySize@BUFFER@@QEBAIXZ:PANYARGS
?QuerySize@BUFFER@@QEBAIXZ TEXTEQU <__imp_?QuerySize@BUFFER@@QEBAIXZ>
extern __imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ:PANYARGS
?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ TEXTEQU <__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ>
extern __imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z:PANYARGS
?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z TEXTEQU <__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z>
extern __imp_WiaAddDevice:PANYARGS
WiaAddDevice TEXTEQU <__imp_WiaAddDevice>
extern __imp_WiaCreatePortList:PANYARGS
WiaCreatePortList TEXTEQU <__imp_WiaCreatePortList>
extern __imp_WiaCreateWizardMenu:PANYARGS
WiaCreateWizardMenu TEXTEQU <__imp_WiaCreateWizardMenu>
extern __imp_WiaDestroyPortList:PANYARGS
WiaDestroyPortList TEXTEQU <__imp_WiaDestroyPortList>
extern __imp_WiaRemoveDevice:PANYARGS
WiaRemoveDevice TEXTEQU <__imp_WiaRemoveDevice>
extern __imp_ClassInstall:PANYARGS
ClassInstall TEXTEQU <__imp_ClassInstall>
extern __imp_CoinstallerEntry:PANYARGS
CoinstallerEntry TEXTEQU <__imp_CoinstallerEntry>
extern __imp_PTPCoinstallerEntry:PANYARGS
PTPCoinstallerEntry TEXTEQU <__imp_PTPCoinstallerEntry>
