extern __imp_ServiceMain:PANYARGS
ServiceMain TEXTEQU <__imp_ServiceMain>
extern __imp_?VssFreeSnapshotProperties@@YAXPEAU_VSS_SNAPSHOT_PROP@@@Z:PANYARGS
?VssFreeSnapshotProperties@@YAXPEAU_VSS_SNAPSHOT_PROP@@@Z TEXTEQU <__imp_?VssFreeSnapshotProperties@@YAXPEAU_VSS_SNAPSHOT_PROP@@@Z>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
