extern __imp_AddAllTwinsToTwinList:PANYARGS
AddAllTwinsToTwinList TEXTEQU <__imp_AddAllTwinsToTwinList>
extern __imp_AddFolderTwin:PANYARGS
AddFolderTwin TEXTEQU <__imp_AddFolderTwin>
extern __imp_AddObjectTwin:PANYARGS
AddObjectTwin TEXTEQU <__imp_AddObjectTwin>
extern __imp_AddTwinToTwinList:PANYARGS
AddTwinToTwinList TEXTEQU <__imp_AddTwinToTwinList>
extern __imp_AnyTwins:PANYARGS
AnyTwins TEXTEQU <__imp_AnyTwins>
extern __imp_BeginReconciliation:PANYARGS
BeginReconciliation TEXTEQU <__imp_BeginReconciliation>
extern __imp_ClearBriefcaseCache:PANYARGS
ClearBriefcaseCache TEXTEQU <__imp_ClearBriefcaseCache>
extern __imp_CloseBriefcase:PANYARGS
CloseBriefcase TEXTEQU <__imp_CloseBriefcase>
extern __imp_CompareFileStamps:PANYARGS
CompareFileStamps TEXTEQU <__imp_CompareFileStamps>
extern __imp_CountSourceFolderTwins:PANYARGS
CountSourceFolderTwins TEXTEQU <__imp_CountSourceFolderTwins>
extern __imp_CreateFolderTwinList:PANYARGS
CreateFolderTwinList TEXTEQU <__imp_CreateFolderTwinList>
extern __imp_CreateRecList:PANYARGS
CreateRecList TEXTEQU <__imp_CreateRecList>
extern __imp_CreateTwinList:PANYARGS
CreateTwinList TEXTEQU <__imp_CreateTwinList>
extern __imp_DeleteBriefcase:PANYARGS
DeleteBriefcase TEXTEQU <__imp_DeleteBriefcase>
extern __imp_DeleteTwin:PANYARGS
DeleteTwin TEXTEQU <__imp_DeleteTwin>
extern __imp_DestroyFolderTwinList:PANYARGS
DestroyFolderTwinList TEXTEQU <__imp_DestroyFolderTwinList>
extern __imp_DestroyRecList:PANYARGS
DestroyRecList TEXTEQU <__imp_DestroyRecList>
extern __imp_DestroyTwinList:PANYARGS
DestroyTwinList TEXTEQU <__imp_DestroyTwinList>
extern __imp_EndReconciliation:PANYARGS
EndReconciliation TEXTEQU <__imp_EndReconciliation>
extern __imp_FindBriefcaseClose:PANYARGS
FindBriefcaseClose TEXTEQU <__imp_FindBriefcaseClose>
extern __imp_FindFirstBriefcase:PANYARGS
FindFirstBriefcase TEXTEQU <__imp_FindFirstBriefcase>
extern __imp_FindNextBriefcase:PANYARGS
FindNextBriefcase TEXTEQU <__imp_FindNextBriefcase>
extern __imp_GetFileStamp:PANYARGS
GetFileStamp TEXTEQU <__imp_GetFileStamp>
extern __imp_GetFolderTwinStatus:PANYARGS
GetFolderTwinStatus TEXTEQU <__imp_GetFolderTwinStatus>
extern __imp_GetObjectTwinHandle:PANYARGS
GetObjectTwinHandle TEXTEQU <__imp_GetObjectTwinHandle>
extern __imp_GetOpenBriefcaseInfo:PANYARGS
GetOpenBriefcaseInfo TEXTEQU <__imp_GetOpenBriefcaseInfo>
extern __imp_GetVolumeDescription:PANYARGS
GetVolumeDescription TEXTEQU <__imp_GetVolumeDescription>
extern __imp_IsFolderTwin:PANYARGS
IsFolderTwin TEXTEQU <__imp_IsFolderTwin>
extern __imp_IsOrphanObjectTwin:PANYARGS
IsOrphanObjectTwin TEXTEQU <__imp_IsOrphanObjectTwin>
extern __imp_IsPathOnVolume:PANYARGS
IsPathOnVolume TEXTEQU <__imp_IsPathOnVolume>
extern __imp_OpenBriefcase:PANYARGS
OpenBriefcase TEXTEQU <__imp_OpenBriefcase>
extern __imp_ReconcileItem:PANYARGS
ReconcileItem TEXTEQU <__imp_ReconcileItem>
extern __imp_ReleaseTwinHandle:PANYARGS
ReleaseTwinHandle TEXTEQU <__imp_ReleaseTwinHandle>
extern __imp_RemoveAllTwinsFromTwinList:PANYARGS
RemoveAllTwinsFromTwinList TEXTEQU <__imp_RemoveAllTwinsFromTwinList>
extern __imp_RemoveTwinFromTwinList:PANYARGS
RemoveTwinFromTwinList TEXTEQU <__imp_RemoveTwinFromTwinList>
extern __imp_SaveBriefcase:PANYARGS
SaveBriefcase TEXTEQU <__imp_SaveBriefcase>
