extern __imp_Briefcase_Create:PANYARGS
Briefcase_Create TEXTEQU <__imp_Briefcase_Create>
extern __imp_Briefcase_Intro:PANYARGS
Briefcase_Intro TEXTEQU <__imp_Briefcase_Intro>
extern __imp_Briefcase_CreateW:PANYARGS
Briefcase_CreateW TEXTEQU <__imp_Briefcase_CreateW>
extern __imp_Briefcase_CreateA:PANYARGS
Briefcase_Create  TEXTEQU <__imp_Briefcase_CreateA>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
