extern __imp_GetTapi16CallbackMsg:PANYARGS
GetTapi16CallbackMsg TEXTEQU <__imp_GetTapi16CallbackMsg>
extern __imp_LAddrParamsInited:PANYARGS
LAddrParamsInited TEXTEQU <__imp_LAddrParamsInited>
extern __imp_LOpenDialAsst:PANYARGS
LOpenDialAsst TEXTEQU <__imp_LOpenDialAsst>
extern __imp_LocWizardDlgProc:PANYARGS
LocWizardDlgProc TEXTEQU <__imp_LocWizardDlgProc>
extern __imp_MMCAddProvider:PANYARGS
MMCAddProvider TEXTEQU <__imp_MMCAddProvider>
extern __imp_MMCConfigProvider:PANYARGS
MMCConfigProvider TEXTEQU <__imp_MMCConfigProvider>
extern __imp_MMCGetAvailableProviders:PANYARGS
MMCGetAvailableProviders TEXTEQU <__imp_MMCGetAvailableProviders>
extern __imp_MMCGetDeviceFlags:PANYARGS
MMCGetDeviceFlags TEXTEQU <__imp_MMCGetDeviceFlags>
extern __imp_MMCGetLineInfo:PANYARGS
MMCGetLineInfo TEXTEQU <__imp_MMCGetLineInfo>
extern __imp_MMCGetLineStatus:PANYARGS
MMCGetLineStatus TEXTEQU <__imp_MMCGetLineStatus>
extern __imp_MMCGetPhoneInfo:PANYARGS
MMCGetPhoneInfo TEXTEQU <__imp_MMCGetPhoneInfo>
extern __imp_MMCGetPhoneStatus:PANYARGS
MMCGetPhoneStatus TEXTEQU <__imp_MMCGetPhoneStatus>
extern __imp_MMCGetProviderList:PANYARGS
MMCGetProviderList TEXTEQU <__imp_MMCGetProviderList>
extern __imp_MMCGetServerConfig:PANYARGS
MMCGetServerConfig TEXTEQU <__imp_MMCGetServerConfig>
extern __imp_MMCInitialize:PANYARGS
MMCInitialize TEXTEQU <__imp_MMCInitialize>
extern __imp_MMCRemoveProvider:PANYARGS
MMCRemoveProvider TEXTEQU <__imp_MMCRemoveProvider>
extern __imp_MMCSetLineInfo:PANYARGS
MMCSetLineInfo TEXTEQU <__imp_MMCSetLineInfo>
extern __imp_MMCSetPhoneInfo:PANYARGS
MMCSetPhoneInfo TEXTEQU <__imp_MMCSetPhoneInfo>
extern __imp_MMCSetServerConfig:PANYARGS
MMCSetServerConfig TEXTEQU <__imp_MMCSetServerConfig>
extern __imp_MMCShutdown:PANYARGS
MMCShutdown TEXTEQU <__imp_MMCShutdown>
extern __imp_NonAsyncEventThread:PANYARGS
NonAsyncEventThread TEXTEQU <__imp_NonAsyncEventThread>
extern __imp_TAPIWndProc:PANYARGS
TAPIWndProc TEXTEQU <__imp_TAPIWndProc>
extern __imp_TUISPIDLLCallback:PANYARGS
TUISPIDLLCallback TEXTEQU <__imp_TUISPIDLLCallback>
extern __imp_internalConfig:PANYARGS
internalConfig TEXTEQU <__imp_internalConfig>
extern __imp_internalCreateDefLocation:PANYARGS
internalCreateDefLocation TEXTEQU <__imp_internalCreateDefLocation>
extern __imp_internalNewLocationW:PANYARGS
internalNewLocationW TEXTEQU <__imp_internalNewLocationW>
extern __imp_internalPerformance:PANYARGS
internalPerformance TEXTEQU <__imp_internalPerformance>
extern __imp_internalRemoveLocation:PANYARGS
internalRemoveLocation TEXTEQU <__imp_internalRemoveLocation>
extern __imp_internalRenameLocationW:PANYARGS
internalRenameLocationW TEXTEQU <__imp_internalRenameLocationW>
extern __imp_lineAccept:PANYARGS
lineAccept TEXTEQU <__imp_lineAccept>
extern __imp_lineAddProvider:PANYARGS
lineAddProvider TEXTEQU <__imp_lineAddProvider>
extern __imp_lineAddProviderA:PANYARGS
lineAddProvider  TEXTEQU <__imp_lineAddProviderA>
extern __imp_lineAddProviderW:PANYARGS
lineAddProviderW TEXTEQU <__imp_lineAddProviderW>
extern __imp_lineAddToConference:PANYARGS
lineAddToConference TEXTEQU <__imp_lineAddToConference>
extern __imp_lineAgentSpecific:PANYARGS
lineAgentSpecific TEXTEQU <__imp_lineAgentSpecific>
extern __imp_lineAnswer:PANYARGS
lineAnswer TEXTEQU <__imp_lineAnswer>
extern __imp_lineBlindTransfer:PANYARGS
lineBlindTransfer TEXTEQU <__imp_lineBlindTransfer>
extern __imp_lineBlindTransferA:PANYARGS
lineBlindTransfer  TEXTEQU <__imp_lineBlindTransferA>
extern __imp_lineBlindTransferW:PANYARGS
lineBlindTransferW TEXTEQU <__imp_lineBlindTransferW>
extern __imp_lineClose:PANYARGS
lineClose TEXTEQU <__imp_lineClose>
extern __imp_lineCompleteCall:PANYARGS
lineCompleteCall TEXTEQU <__imp_lineCompleteCall>
extern __imp_lineCompleteTransfer:PANYARGS
lineCompleteTransfer TEXTEQU <__imp_lineCompleteTransfer>
extern __imp_lineConfigDialog:PANYARGS
lineConfigDialog TEXTEQU <__imp_lineConfigDialog>
extern __imp_lineConfigDialogA:PANYARGS
lineConfigDialog  TEXTEQU <__imp_lineConfigDialogA>
extern __imp_lineConfigDialogEdit:PANYARGS
lineConfigDialogEdit TEXTEQU <__imp_lineConfigDialogEdit>
extern __imp_lineConfigDialogEditA:PANYARGS
lineConfigDialogEdit  TEXTEQU <__imp_lineConfigDialogEditA>
extern __imp_lineConfigDialogEditW:PANYARGS
lineConfigDialogEditW TEXTEQU <__imp_lineConfigDialogEditW>
extern __imp_lineConfigDialogW:PANYARGS
lineConfigDialogW TEXTEQU <__imp_lineConfigDialogW>
extern __imp_lineConfigProvider:PANYARGS
lineConfigProvider TEXTEQU <__imp_lineConfigProvider>
extern __imp_lineCreateAgentA:PANYARGS
lineCreateAgent  TEXTEQU <__imp_lineCreateAgentA>
extern __imp_lineCreateAgentSessionA:PANYARGS
lineCreateAgentSession  TEXTEQU <__imp_lineCreateAgentSessionA>
extern __imp_lineCreateAgentSessionW:PANYARGS
lineCreateAgentSessionW TEXTEQU <__imp_lineCreateAgentSessionW>
extern __imp_lineCreateAgentW:PANYARGS
lineCreateAgentW TEXTEQU <__imp_lineCreateAgentW>
extern __imp_lineDeallocateCall:PANYARGS
lineDeallocateCall TEXTEQU <__imp_lineDeallocateCall>
extern __imp_lineDevSpecific:PANYARGS
lineDevSpecific TEXTEQU <__imp_lineDevSpecific>
extern __imp_lineDevSpecificFeature:PANYARGS
lineDevSpecificFeature TEXTEQU <__imp_lineDevSpecificFeature>
extern __imp_lineDial:PANYARGS
lineDial TEXTEQU <__imp_lineDial>
extern __imp_lineDialA:PANYARGS
lineDial  TEXTEQU <__imp_lineDialA>
extern __imp_lineDialW:PANYARGS
lineDialW TEXTEQU <__imp_lineDialW>
extern __imp_lineDrop:PANYARGS
lineDrop TEXTEQU <__imp_lineDrop>
extern __imp_lineForward:PANYARGS
lineForward TEXTEQU <__imp_lineForward>
extern __imp_lineForwardA:PANYARGS
lineForward  TEXTEQU <__imp_lineForwardA>
extern __imp_lineForwardW:PANYARGS
lineForwardW TEXTEQU <__imp_lineForwardW>
extern __imp_lineGatherDigits:PANYARGS
lineGatherDigits TEXTEQU <__imp_lineGatherDigits>
extern __imp_lineGatherDigitsA:PANYARGS
lineGatherDigits  TEXTEQU <__imp_lineGatherDigitsA>
extern __imp_lineGatherDigitsW:PANYARGS
lineGatherDigitsW TEXTEQU <__imp_lineGatherDigitsW>
extern __imp_lineGenerateDigits:PANYARGS
lineGenerateDigits TEXTEQU <__imp_lineGenerateDigits>
extern __imp_lineGenerateDigitsA:PANYARGS
lineGenerateDigits  TEXTEQU <__imp_lineGenerateDigitsA>
extern __imp_lineGenerateDigitsW:PANYARGS
lineGenerateDigitsW TEXTEQU <__imp_lineGenerateDigitsW>
extern __imp_lineGenerateTone:PANYARGS
lineGenerateTone TEXTEQU <__imp_lineGenerateTone>
extern __imp_lineGetAddressCaps:PANYARGS
lineGetAddressCaps TEXTEQU <__imp_lineGetAddressCaps>
extern __imp_lineGetAddressCapsA:PANYARGS
lineGetAddressCaps  TEXTEQU <__imp_lineGetAddressCapsA>
extern __imp_lineGetAddressCapsW:PANYARGS
lineGetAddressCapsW TEXTEQU <__imp_lineGetAddressCapsW>
extern __imp_lineGetAddressID:PANYARGS
lineGetAddressID TEXTEQU <__imp_lineGetAddressID>
extern __imp_lineGetAddressIDA:PANYARGS
lineGetAddressID  TEXTEQU <__imp_lineGetAddressIDA>
extern __imp_lineGetAddressIDW:PANYARGS
lineGetAddressIDW TEXTEQU <__imp_lineGetAddressIDW>
extern __imp_lineGetAddressStatus:PANYARGS
lineGetAddressStatus TEXTEQU <__imp_lineGetAddressStatus>
extern __imp_lineGetAddressStatusA:PANYARGS
lineGetAddressStatus  TEXTEQU <__imp_lineGetAddressStatusA>
extern __imp_lineGetAddressStatusW:PANYARGS
lineGetAddressStatusW TEXTEQU <__imp_lineGetAddressStatusW>
extern __imp_lineGetAgentActivityListA:PANYARGS
lineGetAgentActivityList  TEXTEQU <__imp_lineGetAgentActivityListA>
extern __imp_lineGetAgentActivityListW:PANYARGS
lineGetAgentActivityListW TEXTEQU <__imp_lineGetAgentActivityListW>
extern __imp_lineGetAgentCapsA:PANYARGS
lineGetAgentCaps  TEXTEQU <__imp_lineGetAgentCapsA>
extern __imp_lineGetAgentCapsW:PANYARGS
lineGetAgentCapsW TEXTEQU <__imp_lineGetAgentCapsW>
extern __imp_lineGetAgentGroupListA:PANYARGS
lineGetAgentGroupList  TEXTEQU <__imp_lineGetAgentGroupListA>
extern __imp_lineGetAgentGroupListW:PANYARGS
lineGetAgentGroupListW TEXTEQU <__imp_lineGetAgentGroupListW>
extern __imp_lineGetAgentInfo:PANYARGS
lineGetAgentInfo TEXTEQU <__imp_lineGetAgentInfo>
extern __imp_lineGetAgentSessionInfo:PANYARGS
lineGetAgentSessionInfo TEXTEQU <__imp_lineGetAgentSessionInfo>
extern __imp_lineGetAgentSessionList:PANYARGS
lineGetAgentSessionList TEXTEQU <__imp_lineGetAgentSessionList>
extern __imp_lineGetAgentStatusA:PANYARGS
lineGetAgentStatus  TEXTEQU <__imp_lineGetAgentStatusA>
extern __imp_lineGetAgentStatusW:PANYARGS
lineGetAgentStatusW TEXTEQU <__imp_lineGetAgentStatusW>
extern __imp_lineGetAppPriority:PANYARGS
lineGetAppPriority TEXTEQU <__imp_lineGetAppPriority>
extern __imp_lineGetAppPriorityA:PANYARGS
lineGetAppPriority  TEXTEQU <__imp_lineGetAppPriorityA>
extern __imp_lineGetAppPriorityW:PANYARGS
lineGetAppPriorityW TEXTEQU <__imp_lineGetAppPriorityW>
extern __imp_lineGetCallInfo:PANYARGS
lineGetCallInfo TEXTEQU <__imp_lineGetCallInfo>
extern __imp_lineGetCallInfoA:PANYARGS
lineGetCallInfo  TEXTEQU <__imp_lineGetCallInfoA>
extern __imp_lineGetCallInfoW:PANYARGS
lineGetCallInfoW TEXTEQU <__imp_lineGetCallInfoW>
extern __imp_lineGetCallStatus:PANYARGS
lineGetCallStatus TEXTEQU <__imp_lineGetCallStatus>
extern __imp_lineGetConfRelatedCalls:PANYARGS
lineGetConfRelatedCalls TEXTEQU <__imp_lineGetConfRelatedCalls>
extern __imp_lineGetCountry:PANYARGS
lineGetCountry TEXTEQU <__imp_lineGetCountry>
extern __imp_lineGetCountryA:PANYARGS
lineGetCountry  TEXTEQU <__imp_lineGetCountryA>
extern __imp_lineGetCountryW:PANYARGS
lineGetCountryW TEXTEQU <__imp_lineGetCountryW>
extern __imp_lineGetDevCaps:PANYARGS
lineGetDevCaps TEXTEQU <__imp_lineGetDevCaps>
extern __imp_lineGetDevCapsA:PANYARGS
lineGetDevCaps  TEXTEQU <__imp_lineGetDevCapsA>
extern __imp_lineGetDevCapsW:PANYARGS
lineGetDevCapsW TEXTEQU <__imp_lineGetDevCapsW>
extern __imp_lineGetDevConfig:PANYARGS
lineGetDevConfig TEXTEQU <__imp_lineGetDevConfig>
extern __imp_lineGetDevConfigA:PANYARGS
lineGetDevConfig  TEXTEQU <__imp_lineGetDevConfigA>
extern __imp_lineGetDevConfigW:PANYARGS
lineGetDevConfigW TEXTEQU <__imp_lineGetDevConfigW>
extern __imp_lineGetGroupListA:PANYARGS
lineGetGroupList  TEXTEQU <__imp_lineGetGroupListA>
extern __imp_lineGetGroupListW:PANYARGS
lineGetGroupListW TEXTEQU <__imp_lineGetGroupListW>
extern __imp_lineGetID:PANYARGS
lineGetID TEXTEQU <__imp_lineGetID>
extern __imp_lineGetIDA:PANYARGS
lineGetID  TEXTEQU <__imp_lineGetIDA>
extern __imp_lineGetIDW:PANYARGS
lineGetIDW TEXTEQU <__imp_lineGetIDW>
extern __imp_lineGetIcon:PANYARGS
lineGetIcon TEXTEQU <__imp_lineGetIcon>
extern __imp_lineGetIconA:PANYARGS
lineGetIcon  TEXTEQU <__imp_lineGetIconA>
extern __imp_lineGetIconW:PANYARGS
lineGetIconW TEXTEQU <__imp_lineGetIconW>
extern __imp_lineGetLineDevStatus:PANYARGS
lineGetLineDevStatus TEXTEQU <__imp_lineGetLineDevStatus>
extern __imp_lineGetLineDevStatusA:PANYARGS
lineGetLineDevStatus  TEXTEQU <__imp_lineGetLineDevStatusA>
extern __imp_lineGetLineDevStatusW:PANYARGS
lineGetLineDevStatusW TEXTEQU <__imp_lineGetLineDevStatusW>
extern __imp_lineGetMessage:PANYARGS
lineGetMessage TEXTEQU <__imp_lineGetMessage>
extern __imp_lineGetNewCalls:PANYARGS
lineGetNewCalls TEXTEQU <__imp_lineGetNewCalls>
extern __imp_lineGetNumRings:PANYARGS
lineGetNumRings TEXTEQU <__imp_lineGetNumRings>
extern __imp_lineGetProviderList:PANYARGS
lineGetProviderList TEXTEQU <__imp_lineGetProviderList>
extern __imp_lineGetProviderListA:PANYARGS
lineGetProviderList  TEXTEQU <__imp_lineGetProviderListA>
extern __imp_lineGetProviderListW:PANYARGS
lineGetProviderListW TEXTEQU <__imp_lineGetProviderListW>
extern __imp_lineGetProxyStatus:PANYARGS
lineGetProxyStatus TEXTEQU <__imp_lineGetProxyStatus>
extern __imp_lineGetQueueInfo:PANYARGS
lineGetQueueInfo TEXTEQU <__imp_lineGetQueueInfo>
extern __imp_lineGetQueueListA:PANYARGS
lineGetQueueList  TEXTEQU <__imp_lineGetQueueListA>
extern __imp_lineGetQueueListW:PANYARGS
lineGetQueueListW TEXTEQU <__imp_lineGetQueueListW>
extern __imp_lineGetRequest:PANYARGS
lineGetRequest TEXTEQU <__imp_lineGetRequest>
extern __imp_lineGetRequestA:PANYARGS
lineGetRequest  TEXTEQU <__imp_lineGetRequestA>
extern __imp_lineGetRequestW:PANYARGS
lineGetRequestW TEXTEQU <__imp_lineGetRequestW>
extern __imp_lineGetStatusMessages:PANYARGS
lineGetStatusMessages TEXTEQU <__imp_lineGetStatusMessages>
extern __imp_lineGetTranslateCaps:PANYARGS
lineGetTranslateCaps TEXTEQU <__imp_lineGetTranslateCaps>
extern __imp_lineGetTranslateCapsA:PANYARGS
lineGetTranslateCaps  TEXTEQU <__imp_lineGetTranslateCapsA>
extern __imp_lineGetTranslateCapsW:PANYARGS
lineGetTranslateCapsW TEXTEQU <__imp_lineGetTranslateCapsW>
extern __imp_lineHandoff:PANYARGS
lineHandoff TEXTEQU <__imp_lineHandoff>
extern __imp_lineHandoffA:PANYARGS
lineHandoff  TEXTEQU <__imp_lineHandoffA>
extern __imp_lineHandoffW:PANYARGS
lineHandoffW TEXTEQU <__imp_lineHandoffW>
extern __imp_lineHold:PANYARGS
lineHold TEXTEQU <__imp_lineHold>
extern __imp_lineInitialize:PANYARGS
lineInitialize TEXTEQU <__imp_lineInitialize>
extern __imp_lineInitializeExA:PANYARGS
lineInitializeEx  TEXTEQU <__imp_lineInitializeExA>
extern __imp_lineInitializeExW:PANYARGS
lineInitializeExW TEXTEQU <__imp_lineInitializeExW>
extern __imp_lineMakeCall:PANYARGS
lineMakeCall TEXTEQU <__imp_lineMakeCall>
extern __imp_lineMakeCallA:PANYARGS
lineMakeCall  TEXTEQU <__imp_lineMakeCallA>
extern __imp_lineMakeCallW:PANYARGS
lineMakeCallW TEXTEQU <__imp_lineMakeCallW>
extern __imp_lineMonitorDigits:PANYARGS
lineMonitorDigits TEXTEQU <__imp_lineMonitorDigits>
extern __imp_lineMonitorMedia:PANYARGS
lineMonitorMedia TEXTEQU <__imp_lineMonitorMedia>
extern __imp_lineMonitorTones:PANYARGS
lineMonitorTones TEXTEQU <__imp_lineMonitorTones>
extern __imp_lineNegotiateAPIVersion:PANYARGS
lineNegotiateAPIVersion TEXTEQU <__imp_lineNegotiateAPIVersion>
extern __imp_lineNegotiateExtVersion:PANYARGS
lineNegotiateExtVersion TEXTEQU <__imp_lineNegotiateExtVersion>
extern __imp_lineOpen:PANYARGS
lineOpen TEXTEQU <__imp_lineOpen>
extern __imp_lineOpenA:PANYARGS
lineOpen  TEXTEQU <__imp_lineOpenA>
extern __imp_lineOpenW:PANYARGS
lineOpenW TEXTEQU <__imp_lineOpenW>
extern __imp_linePark:PANYARGS
linePark TEXTEQU <__imp_linePark>
extern __imp_lineParkA:PANYARGS
linePark  TEXTEQU <__imp_lineParkA>
extern __imp_lineParkW:PANYARGS
lineParkW TEXTEQU <__imp_lineParkW>
extern __imp_linePickup:PANYARGS
linePickup TEXTEQU <__imp_linePickup>
extern __imp_linePickupA:PANYARGS
linePickup  TEXTEQU <__imp_linePickupA>
extern __imp_linePickupW:PANYARGS
linePickupW TEXTEQU <__imp_linePickupW>
extern __imp_linePrepareAddToConference:PANYARGS
linePrepareAddToConference TEXTEQU <__imp_linePrepareAddToConference>
extern __imp_linePrepareAddToConferenceA:PANYARGS
linePrepareAddToConference  TEXTEQU <__imp_linePrepareAddToConferenceA>
extern __imp_linePrepareAddToConferenceW:PANYARGS
linePrepareAddToConferenceW TEXTEQU <__imp_linePrepareAddToConferenceW>
extern __imp_lineProxyMessage:PANYARGS
lineProxyMessage TEXTEQU <__imp_lineProxyMessage>
extern __imp_lineProxyResponse:PANYARGS
lineProxyResponse TEXTEQU <__imp_lineProxyResponse>
extern __imp_lineRedirect:PANYARGS
lineRedirect TEXTEQU <__imp_lineRedirect>
extern __imp_lineRedirectA:PANYARGS
lineRedirect  TEXTEQU <__imp_lineRedirectA>
extern __imp_lineRedirectW:PANYARGS
lineRedirectW TEXTEQU <__imp_lineRedirectW>
extern __imp_lineRegisterRequestRecipient:PANYARGS
lineRegisterRequestRecipient TEXTEQU <__imp_lineRegisterRequestRecipient>
extern __imp_lineReleaseUserUserInfo:PANYARGS
lineReleaseUserUserInfo TEXTEQU <__imp_lineReleaseUserUserInfo>
extern __imp_lineRemoveFromConference:PANYARGS
lineRemoveFromConference TEXTEQU <__imp_lineRemoveFromConference>
extern __imp_lineRemoveProvider:PANYARGS
lineRemoveProvider TEXTEQU <__imp_lineRemoveProvider>
extern __imp_lineSecureCall:PANYARGS
lineSecureCall TEXTEQU <__imp_lineSecureCall>
extern __imp_lineSendUserUserInfo:PANYARGS
lineSendUserUserInfo TEXTEQU <__imp_lineSendUserUserInfo>
extern __imp_lineSetAgentActivity:PANYARGS
lineSetAgentActivity TEXTEQU <__imp_lineSetAgentActivity>
extern __imp_lineSetAgentGroup:PANYARGS
lineSetAgentGroup TEXTEQU <__imp_lineSetAgentGroup>
extern __imp_lineSetAgentMeasurementPeriod:PANYARGS
lineSetAgentMeasurementPeriod TEXTEQU <__imp_lineSetAgentMeasurementPeriod>
extern __imp_lineSetAgentSessionState:PANYARGS
lineSetAgentSessionState TEXTEQU <__imp_lineSetAgentSessionState>
extern __imp_lineSetAgentState:PANYARGS
lineSetAgentState TEXTEQU <__imp_lineSetAgentState>
extern __imp_lineSetAgentStateEx:PANYARGS
lineSetAgentStateEx TEXTEQU <__imp_lineSetAgentStateEx>
extern __imp_lineSetAppPriority:PANYARGS
lineSetAppPriority TEXTEQU <__imp_lineSetAppPriority>
extern __imp_lineSetAppPriorityA:PANYARGS
lineSetAppPriority  TEXTEQU <__imp_lineSetAppPriorityA>
extern __imp_lineSetAppPriorityW:PANYARGS
lineSetAppPriorityW TEXTEQU <__imp_lineSetAppPriorityW>
extern __imp_lineSetAppSpecific:PANYARGS
lineSetAppSpecific TEXTEQU <__imp_lineSetAppSpecific>
extern __imp_lineSetCallData:PANYARGS
lineSetCallData TEXTEQU <__imp_lineSetCallData>
extern __imp_lineSetCallParams:PANYARGS
lineSetCallParams TEXTEQU <__imp_lineSetCallParams>
extern __imp_lineSetCallPrivilege:PANYARGS
lineSetCallPrivilege TEXTEQU <__imp_lineSetCallPrivilege>
extern __imp_lineSetCallQualityOfService:PANYARGS
lineSetCallQualityOfService TEXTEQU <__imp_lineSetCallQualityOfService>
extern __imp_lineSetCallTreatment:PANYARGS
lineSetCallTreatment TEXTEQU <__imp_lineSetCallTreatment>
extern __imp_lineSetCurrentLocation:PANYARGS
lineSetCurrentLocation TEXTEQU <__imp_lineSetCurrentLocation>
extern __imp_lineSetDevConfig:PANYARGS
lineSetDevConfig TEXTEQU <__imp_lineSetDevConfig>
extern __imp_lineSetDevConfigA:PANYARGS
lineSetDevConfig  TEXTEQU <__imp_lineSetDevConfigA>
extern __imp_lineSetDevConfigW:PANYARGS
lineSetDevConfigW TEXTEQU <__imp_lineSetDevConfigW>
extern __imp_lineSetLineDevStatus:PANYARGS
lineSetLineDevStatus TEXTEQU <__imp_lineSetLineDevStatus>
extern __imp_lineSetMediaControl:PANYARGS
lineSetMediaControl TEXTEQU <__imp_lineSetMediaControl>
extern __imp_lineSetMediaMode:PANYARGS
lineSetMediaMode TEXTEQU <__imp_lineSetMediaMode>
extern __imp_lineSetNumRings:PANYARGS
lineSetNumRings TEXTEQU <__imp_lineSetNumRings>
extern __imp_lineSetQueueMeasurementPeriod:PANYARGS
lineSetQueueMeasurementPeriod TEXTEQU <__imp_lineSetQueueMeasurementPeriod>
extern __imp_lineSetStatusMessages:PANYARGS
lineSetStatusMessages TEXTEQU <__imp_lineSetStatusMessages>
extern __imp_lineSetTerminal:PANYARGS
lineSetTerminal TEXTEQU <__imp_lineSetTerminal>
extern __imp_lineSetTollList:PANYARGS
lineSetTollList TEXTEQU <__imp_lineSetTollList>
extern __imp_lineSetTollListA:PANYARGS
lineSetTollList  TEXTEQU <__imp_lineSetTollListA>
extern __imp_lineSetTollListW:PANYARGS
lineSetTollListW TEXTEQU <__imp_lineSetTollListW>
extern __imp_lineSetupConference:PANYARGS
lineSetupConference TEXTEQU <__imp_lineSetupConference>
extern __imp_lineSetupConferenceA:PANYARGS
lineSetupConference  TEXTEQU <__imp_lineSetupConferenceA>
extern __imp_lineSetupConferenceW:PANYARGS
lineSetupConferenceW TEXTEQU <__imp_lineSetupConferenceW>
extern __imp_lineSetupTransfer:PANYARGS
lineSetupTransfer TEXTEQU <__imp_lineSetupTransfer>
extern __imp_lineSetupTransferA:PANYARGS
lineSetupTransfer  TEXTEQU <__imp_lineSetupTransferA>
extern __imp_lineSetupTransferW:PANYARGS
lineSetupTransferW TEXTEQU <__imp_lineSetupTransferW>
extern __imp_lineShutdown:PANYARGS
lineShutdown TEXTEQU <__imp_lineShutdown>
extern __imp_lineSwapHold:PANYARGS
lineSwapHold TEXTEQU <__imp_lineSwapHold>
extern __imp_lineTranslateAddress:PANYARGS
lineTranslateAddress TEXTEQU <__imp_lineTranslateAddress>
extern __imp_lineTranslateAddressA:PANYARGS
lineTranslateAddress  TEXTEQU <__imp_lineTranslateAddressA>
extern __imp_lineTranslateAddressW:PANYARGS
lineTranslateAddressW TEXTEQU <__imp_lineTranslateAddressW>
extern __imp_lineTranslateDialog:PANYARGS
lineTranslateDialog TEXTEQU <__imp_lineTranslateDialog>
extern __imp_lineTranslateDialogA:PANYARGS
lineTranslateDialog  TEXTEQU <__imp_lineTranslateDialogA>
extern __imp_lineTranslateDialogW:PANYARGS
lineTranslateDialogW TEXTEQU <__imp_lineTranslateDialogW>
extern __imp_lineUncompleteCall:PANYARGS
lineUncompleteCall TEXTEQU <__imp_lineUncompleteCall>
extern __imp_lineUnhold:PANYARGS
lineUnhold TEXTEQU <__imp_lineUnhold>
extern __imp_lineUnpark:PANYARGS
lineUnpark TEXTEQU <__imp_lineUnpark>
extern __imp_lineUnparkA:PANYARGS
lineUnpark  TEXTEQU <__imp_lineUnparkA>
extern __imp_lineUnparkW:PANYARGS
lineUnparkW TEXTEQU <__imp_lineUnparkW>
extern __imp_phoneClose:PANYARGS
phoneClose TEXTEQU <__imp_phoneClose>
extern __imp_phoneConfigDialog:PANYARGS
phoneConfigDialog TEXTEQU <__imp_phoneConfigDialog>
extern __imp_phoneConfigDialogA:PANYARGS
phoneConfigDialog  TEXTEQU <__imp_phoneConfigDialogA>
extern __imp_phoneConfigDialogW:PANYARGS
phoneConfigDialogW TEXTEQU <__imp_phoneConfigDialogW>
extern __imp_phoneDevSpecific:PANYARGS
phoneDevSpecific TEXTEQU <__imp_phoneDevSpecific>
extern __imp_phoneGetButtonInfo:PANYARGS
phoneGetButtonInfo TEXTEQU <__imp_phoneGetButtonInfo>
extern __imp_phoneGetButtonInfoA:PANYARGS
phoneGetButtonInfo  TEXTEQU <__imp_phoneGetButtonInfoA>
extern __imp_phoneGetButtonInfoW:PANYARGS
phoneGetButtonInfoW TEXTEQU <__imp_phoneGetButtonInfoW>
extern __imp_phoneGetData:PANYARGS
phoneGetData TEXTEQU <__imp_phoneGetData>
extern __imp_phoneGetDevCaps:PANYARGS
phoneGetDevCaps TEXTEQU <__imp_phoneGetDevCaps>
extern __imp_phoneGetDevCapsA:PANYARGS
phoneGetDevCaps  TEXTEQU <__imp_phoneGetDevCapsA>
extern __imp_phoneGetDevCapsW:PANYARGS
phoneGetDevCapsW TEXTEQU <__imp_phoneGetDevCapsW>
extern __imp_phoneGetDisplay:PANYARGS
phoneGetDisplay TEXTEQU <__imp_phoneGetDisplay>
extern __imp_phoneGetGain:PANYARGS
phoneGetGain TEXTEQU <__imp_phoneGetGain>
extern __imp_phoneGetHookSwitch:PANYARGS
phoneGetHookSwitch TEXTEQU <__imp_phoneGetHookSwitch>
extern __imp_phoneGetID:PANYARGS
phoneGetID TEXTEQU <__imp_phoneGetID>
extern __imp_phoneGetIDA:PANYARGS
phoneGetID  TEXTEQU <__imp_phoneGetIDA>
extern __imp_phoneGetIDW:PANYARGS
phoneGetIDW TEXTEQU <__imp_phoneGetIDW>
extern __imp_phoneGetIcon:PANYARGS
phoneGetIcon TEXTEQU <__imp_phoneGetIcon>
extern __imp_phoneGetIconA:PANYARGS
phoneGetIcon  TEXTEQU <__imp_phoneGetIconA>
extern __imp_phoneGetIconW:PANYARGS
phoneGetIconW TEXTEQU <__imp_phoneGetIconW>
extern __imp_phoneGetLamp:PANYARGS
phoneGetLamp TEXTEQU <__imp_phoneGetLamp>
extern __imp_phoneGetMessage:PANYARGS
phoneGetMessage TEXTEQU <__imp_phoneGetMessage>
extern __imp_phoneGetRing:PANYARGS
phoneGetRing TEXTEQU <__imp_phoneGetRing>
extern __imp_phoneGetStatus:PANYARGS
phoneGetStatus TEXTEQU <__imp_phoneGetStatus>
extern __imp_phoneGetStatusA:PANYARGS
phoneGetStatus  TEXTEQU <__imp_phoneGetStatusA>
extern __imp_phoneGetStatusMessages:PANYARGS
phoneGetStatusMessages TEXTEQU <__imp_phoneGetStatusMessages>
extern __imp_phoneGetStatusW:PANYARGS
phoneGetStatusW TEXTEQU <__imp_phoneGetStatusW>
extern __imp_phoneGetVolume:PANYARGS
phoneGetVolume TEXTEQU <__imp_phoneGetVolume>
extern __imp_phoneInitialize:PANYARGS
phoneInitialize TEXTEQU <__imp_phoneInitialize>
extern __imp_phoneInitializeExA:PANYARGS
phoneInitializeEx  TEXTEQU <__imp_phoneInitializeExA>
extern __imp_phoneInitializeExW:PANYARGS
phoneInitializeExW TEXTEQU <__imp_phoneInitializeExW>
extern __imp_phoneNegotiateAPIVersion:PANYARGS
phoneNegotiateAPIVersion TEXTEQU <__imp_phoneNegotiateAPIVersion>
extern __imp_phoneNegotiateExtVersion:PANYARGS
phoneNegotiateExtVersion TEXTEQU <__imp_phoneNegotiateExtVersion>
extern __imp_phoneOpen:PANYARGS
phoneOpen TEXTEQU <__imp_phoneOpen>
extern __imp_phoneSetButtonInfo:PANYARGS
phoneSetButtonInfo TEXTEQU <__imp_phoneSetButtonInfo>
extern __imp_phoneSetButtonInfoA:PANYARGS
phoneSetButtonInfo  TEXTEQU <__imp_phoneSetButtonInfoA>
extern __imp_phoneSetButtonInfoW:PANYARGS
phoneSetButtonInfoW TEXTEQU <__imp_phoneSetButtonInfoW>
extern __imp_phoneSetData:PANYARGS
phoneSetData TEXTEQU <__imp_phoneSetData>
extern __imp_phoneSetDisplay:PANYARGS
phoneSetDisplay TEXTEQU <__imp_phoneSetDisplay>
extern __imp_phoneSetGain:PANYARGS
phoneSetGain TEXTEQU <__imp_phoneSetGain>
extern __imp_phoneSetHookSwitch:PANYARGS
phoneSetHookSwitch TEXTEQU <__imp_phoneSetHookSwitch>
extern __imp_phoneSetLamp:PANYARGS
phoneSetLamp TEXTEQU <__imp_phoneSetLamp>
extern __imp_phoneSetRing:PANYARGS
phoneSetRing TEXTEQU <__imp_phoneSetRing>
extern __imp_phoneSetStatusMessages:PANYARGS
phoneSetStatusMessages TEXTEQU <__imp_phoneSetStatusMessages>
extern __imp_phoneSetVolume:PANYARGS
phoneSetVolume TEXTEQU <__imp_phoneSetVolume>
extern __imp_phoneShutdown:PANYARGS
phoneShutdown TEXTEQU <__imp_phoneShutdown>
extern __imp_tapiGetLocationInfo:PANYARGS
tapiGetLocationInfo TEXTEQU <__imp_tapiGetLocationInfo>
extern __imp_tapiGetLocationInfoA:PANYARGS
tapiGetLocationInfo  TEXTEQU <__imp_tapiGetLocationInfoA>
extern __imp_tapiGetLocationInfoW:PANYARGS
tapiGetLocationInfoW TEXTEQU <__imp_tapiGetLocationInfoW>
extern __imp_tapiRequestDrop:PANYARGS
tapiRequestDrop TEXTEQU <__imp_tapiRequestDrop>
extern __imp_tapiRequestMakeCall:PANYARGS
tapiRequestMakeCall TEXTEQU <__imp_tapiRequestMakeCall>
extern __imp_tapiRequestMakeCallA:PANYARGS
tapiRequestMakeCall  TEXTEQU <__imp_tapiRequestMakeCallA>
extern __imp_tapiRequestMakeCallW:PANYARGS
tapiRequestMakeCallW TEXTEQU <__imp_tapiRequestMakeCallW>
extern __imp_tapiRequestMediaCall:PANYARGS
tapiRequestMediaCall TEXTEQU <__imp_tapiRequestMediaCall>
extern __imp_tapiRequestMediaCallA:PANYARGS
tapiRequestMediaCall  TEXTEQU <__imp_tapiRequestMediaCallA>
extern __imp_tapiRequestMediaCallW:PANYARGS
tapiRequestMediaCallW TEXTEQU <__imp_tapiRequestMediaCallW>
