extern __imp_??0CPortABC@@QEAA@AEBV0@@Z:PANYARGS
??0CPortABC@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CPortABC@@QEAA@AEBV0@@Z>
extern __imp_??0CPortABC@@QEAA@XZ:PANYARGS
??0CPortABC@@QEAA@XZ TEXTEQU <__imp_??0CPortABC@@QEAA@XZ>
extern __imp_??0CTcpMibABC@@QEAA@AEBV0@@Z:PANYARGS
??0CTcpMibABC@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CTcpMibABC@@QEAA@AEBV0@@Z>
extern __imp_??0CTcpMibABC@@QEAA@XZ:PANYARGS
??0CTcpMibABC@@QEAA@XZ TEXTEQU <__imp_??0CTcpMibABC@@QEAA@XZ>
extern __imp_??1CPortABC@@UEAA@XZ:PANYARGS
??1CPortABC@@UEAA@XZ TEXTEQU <__imp_??1CPortABC@@UEAA@XZ>
extern __imp_??1CTcpMibABC@@UEAA@XZ:PANYARGS
??1CTcpMibABC@@UEAA@XZ TEXTEQU <__imp_??1CTcpMibABC@@UEAA@XZ>
extern __imp_??4CPortABC@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CPortABC@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CPortABC@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_7CPortABC@@6B@:PANYARGS
??_7CPortABC@@6B@ TEXTEQU <__imp_??_7CPortABC@@6B@>
extern __imp_??_7CTcpMibABC@@6B@:PANYARGS
??_7CTcpMibABC@@6B@ TEXTEQU <__imp_??_7CTcpMibABC@@6B@>
extern __imp_?Read@CPortABC@@UEAAKQEAXPEAEKPEAK@Z:PANYARGS
?Read@CPortABC@@UEAAKQEAXPEAEKPEAK@Z TEXTEQU <__imp_?Read@CPortABC@@UEAAKQEAXPEAEKPEAK@Z>
extern __imp_InitializePrintMonitor2:PANYARGS
InitializePrintMonitor2 TEXTEQU <__imp_InitializePrintMonitor2>
