extern __imp_??0CTcpMib@@QEAA@AEBV0@@Z:PANYARGS
??0CTcpMib@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CTcpMib@@QEAA@AEBV0@@Z>
extern __imp_??0CTcpMib@@QEAA@XZ:PANYARGS
??0CTcpMib@@QEAA@XZ TEXTEQU <__imp_??0CTcpMib@@QEAA@XZ>
extern __imp_??0CTcpMibABC@@QEAA@AEBV0@@Z:PANYARGS
??0CTcpMibABC@@QEAA@AEBV0@@Z TEXTEQU <__imp_??0CTcpMibABC@@QEAA@AEBV0@@Z>
extern __imp_??0CTcpMibABC@@QEAA@XZ:PANYARGS
??0CTcpMibABC@@QEAA@XZ TEXTEQU <__imp_??0CTcpMibABC@@QEAA@XZ>
extern __imp_??1CTcpMib@@UEAA@XZ:PANYARGS
??1CTcpMib@@UEAA@XZ TEXTEQU <__imp_??1CTcpMib@@UEAA@XZ>
extern __imp_??1CTcpMibABC@@UEAA@XZ:PANYARGS
??1CTcpMibABC@@UEAA@XZ TEXTEQU <__imp_??1CTcpMibABC@@UEAA@XZ>
extern __imp_??4CTcpMib@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CTcpMib@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CTcpMib@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z:PANYARGS
??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z TEXTEQU <__imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z>
extern __imp_??_7CTcpMib@@6B@:PANYARGS
??_7CTcpMib@@6B@ TEXTEQU <__imp_??_7CTcpMib@@6B@>
extern __imp_??_7CTcpMibABC@@6B@:PANYARGS
??_7CTcpMibABC@@6B@ TEXTEQU <__imp_??_7CTcpMibABC@@6B@>
extern __imp_?EnterCSection@CTcpMib@@AEAAXXZ:PANYARGS
?EnterCSection@CTcpMib@@AEAAXXZ TEXTEQU <__imp_?EnterCSection@CTcpMib@@AEAAXXZ>
extern __imp_?ExitCSection@CTcpMib@@AEAAXXZ:PANYARGS
?ExitCSection@CTcpMib@@AEAAXXZ TEXTEQU <__imp_?ExitCSection@CTcpMib@@AEAAXXZ>
extern __imp_?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z:PANYARGS
?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z TEXTEQU <__imp_?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z>
extern __imp_?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z:PANYARGS
?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z TEXTEQU <__imp_?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z>
extern __imp_?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z:PANYARGS
?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z TEXTEQU <__imp_?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z>
extern __imp_?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z:PANYARGS
?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z TEXTEQU <__imp_?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z>
extern __imp_?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z:PANYARGS
?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z TEXTEQU <__imp_?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z>
extern __imp_?InitSnmp@CTcpMib@@UEAAKXZ:PANYARGS
?InitSnmp@CTcpMib@@UEAAKXZ TEXTEQU <__imp_?InitSnmp@CTcpMib@@UEAAKXZ>
extern __imp_?IsValid@CTcpMib@@QEBAHXZ:PANYARGS
?IsValid@CTcpMib@@QEBAHXZ TEXTEQU <__imp_?IsValid@CTcpMib@@QEBAHXZ>
extern __imp_?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z:PANYARGS
?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z TEXTEQU <__imp_?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z>
extern __imp_?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z:PANYARGS
?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z TEXTEQU <__imp_?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z>
extern __imp_?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z:PANYARGS
?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z TEXTEQU <__imp_?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z>
extern __imp_?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z:PANYARGS
?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z TEXTEQU <__imp_?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z>
extern __imp_?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z:PANYARGS
?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z TEXTEQU <__imp_?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z>
extern __imp_?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z:PANYARGS
?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z TEXTEQU <__imp_?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z>
extern __imp_?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z:PANYARGS
?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z TEXTEQU <__imp_?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z>
extern __imp_?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z:PANYARGS
?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z TEXTEQU <__imp_?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z>
extern __imp_?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z:PANYARGS
?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z TEXTEQU <__imp_?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z>
extern __imp_?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z:PANYARGS
?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z TEXTEQU <__imp_?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z>
extern __imp_?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z:PANYARGS
?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z TEXTEQU <__imp_?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z>
extern __imp_?UnInitSnmp@CTcpMib@@UEAAXXZ:PANYARGS
?UnInitSnmp@CTcpMib@@UEAAXXZ TEXTEQU <__imp_?UnInitSnmp@CTcpMib@@UEAAXXZ>
extern __imp_GetTcpMibPtr:PANYARGS
GetTcpMibPtr TEXTEQU <__imp_GetTcpMibPtr>
extern __imp_Ping:PANYARGS
Ping TEXTEQU <__imp_Ping>
