extern __imp_TcAddFilter:PANYARGS
TcAddFilter TEXTEQU <__imp_TcAddFilter>
extern __imp_TcAddFlow:PANYARGS
TcAddFlow TEXTEQU <__imp_TcAddFlow>
extern __imp_TcCloseInterface:PANYARGS
TcCloseInterface TEXTEQU <__imp_TcCloseInterface>
extern __imp_TcDeleteFilter:PANYARGS
TcDeleteFilter TEXTEQU <__imp_TcDeleteFilter>
extern __imp_TcDeleteFlow:PANYARGS
TcDeleteFlow TEXTEQU <__imp_TcDeleteFlow>
extern __imp_TcDeregisterClient:PANYARGS
TcDeregisterClient TEXTEQU <__imp_TcDeregisterClient>
extern __imp_TcEnumerateFlows:PANYARGS
TcEnumerateFlows TEXTEQU <__imp_TcEnumerateFlows>
extern __imp_TcEnumerateInterfaces:PANYARGS
TcEnumerateInterfaces TEXTEQU <__imp_TcEnumerateInterfaces>
extern __imp_TcGetFlowNameA:PANYARGS
TcGetFlowName  TEXTEQU <__imp_TcGetFlowNameA>
extern __imp_TcGetFlowNameW:PANYARGS
TcGetFlowNameW TEXTEQU <__imp_TcGetFlowNameW>
extern __imp_TcModifyFlow:PANYARGS
TcModifyFlow TEXTEQU <__imp_TcModifyFlow>
extern __imp_TcOpenInterfaceA:PANYARGS
TcOpenInterface  TEXTEQU <__imp_TcOpenInterfaceA>
extern __imp_TcOpenInterfaceW:PANYARGS
TcOpenInterfaceW TEXTEQU <__imp_TcOpenInterfaceW>
extern __imp_TcQueryFlowA:PANYARGS
TcQueryFlow  TEXTEQU <__imp_TcQueryFlowA>
extern __imp_TcQueryFlowW:PANYARGS
TcQueryFlowW TEXTEQU <__imp_TcQueryFlowW>
extern __imp_TcQueryInterface:PANYARGS
TcQueryInterface TEXTEQU <__imp_TcQueryInterface>
extern __imp_TcRegisterClient:PANYARGS
TcRegisterClient TEXTEQU <__imp_TcRegisterClient>
extern __imp_TcSetFlowA:PANYARGS
TcSetFlow  TEXTEQU <__imp_TcSetFlowA>
extern __imp_TcSetFlowW:PANYARGS
TcSetFlowW TEXTEQU <__imp_TcSetFlowW>
extern __imp_TcSetInterface:PANYARGS
TcSetInterface TEXTEQU <__imp_TcSetInterface>
