extern __imp_TrueSpeech_Version:PANYARGS
TrueSpeech_Version TEXTEQU <__imp_TrueSpeech_Version>
extern __imp_TrueSpeech_Init:PANYARGS
TrueSpeech_Init TEXTEQU <__imp_TrueSpeech_Init>
extern __imp_TrueSpeech_Term:PANYARGS
TrueSpeech_Term TEXTEQU <__imp_TrueSpeech_Term>
extern __imp_TrueSpeech_Encod:PANYARGS
TrueSpeech_Encod TEXTEQU <__imp_TrueSpeech_Encod>
extern __imp_TrueSpeech_Decod:PANYARGS
TrueSpeech_Decod TEXTEQU <__imp_TrueSpeech_Decod>
extern __imp_TrueSpeech_Reset:PANYARGS
TrueSpeech_Reset TEXTEQU <__imp_TrueSpeech_Reset>
