extern __imp_UmInitializeModemDriver:PANYARGS
UmInitializeModemDriver TEXTEQU <__imp_UmInitializeModemDriver>
extern __imp_UmDeinitializeModemDriver:PANYARGS
UmDeinitializeModemDriver TEXTEQU <__imp_UmDeinitializeModemDriver>
extern __imp_UmOpenModem:PANYARGS
UmOpenModem TEXTEQU <__imp_UmOpenModem>
extern __imp_UmCloseModem:PANYARGS
UmCloseModem TEXTEQU <__imp_UmCloseModem>
extern __imp_UmInitModem:PANYARGS
UmInitModem TEXTEQU <__imp_UmInitModem>
extern __imp_UmMonitorModem:PANYARGS
UmMonitorModem TEXTEQU <__imp_UmMonitorModem>
extern __imp_UmAnswerModem:PANYARGS
UmAnswerModem TEXTEQU <__imp_UmAnswerModem>
extern __imp_UmDialModem:PANYARGS
UmDialModem TEXTEQU <__imp_UmDialModem>
extern __imp_UmHangupModem:PANYARGS
UmHangupModem TEXTEQU <__imp_UmHangupModem>
extern __imp_UmGenerateDigit:PANYARGS
UmGenerateDigit TEXTEQU <__imp_UmGenerateDigit>
extern __imp_UmSetSpeakerPhoneState:PANYARGS
UmSetSpeakerPhoneState TEXTEQU <__imp_UmSetSpeakerPhoneState>
extern __imp_UmDuplicateDeviceHandle:PANYARGS
UmDuplicateDeviceHandle TEXTEQU <__imp_UmDuplicateDeviceHandle>
extern __imp_UmAbortCurrentModemCommand:PANYARGS
UmAbortCurrentModemCommand TEXTEQU <__imp_UmAbortCurrentModemCommand>
extern __imp_UmSetPassthroughMode:PANYARGS
UmSetPassthroughMode TEXTEQU <__imp_UmSetPassthroughMode>
extern __imp_UmIssueCommand:PANYARGS
UmIssueCommand TEXTEQU <__imp_UmIssueCommand>
extern __imp_UmWaveAction:PANYARGS
UmWaveAction TEXTEQU <__imp_UmWaveAction>
extern __imp_UmLogStringA:PANYARGS
UmLogString  TEXTEQU <__imp_UmLogStringA>
extern __imp_UmGetDiagnostics:PANYARGS
UmGetDiagnostics TEXTEQU <__imp_UmGetDiagnostics>
extern __imp_UmLogDiagnostics:PANYARGS
UmLogDiagnostics TEXTEQU <__imp_UmLogDiagnostics>
