extern __imp_UmPlatformInitialize:PANYARGS
UmPlatformInitialize TEXTEQU <__imp_UmPlatformInitialize>
extern __imp_UmPlatformDeinitialize:PANYARGS
UmPlatformDeinitialize TEXTEQU <__imp_UmPlatformDeinitialize>
extern __imp_UnimodemReadFileEx:PANYARGS
UnimodemReadFileEx TEXTEQU <__imp_UnimodemReadFileEx>
extern __imp_UnimodemWriteFileEx:PANYARGS
UnimodemWriteFileEx TEXTEQU <__imp_UnimodemWriteFileEx>
extern __imp_UnimodemDeviceIoControlEx:PANYARGS
UnimodemDeviceIoControlEx TEXTEQU <__imp_UnimodemDeviceIoControlEx>
extern __imp_UnimodemWaitCommEventEx:PANYARGS
UnimodemWaitCommEventEx TEXTEQU <__imp_UnimodemWaitCommEventEx>
extern __imp_UnimodemQueueUserAPC:PANYARGS
UnimodemQueueUserAPC TEXTEQU <__imp_UnimodemQueueUserAPC>
extern __imp_CreateUnimodemTimer:PANYARGS
CreateUnimodemTimer TEXTEQU <__imp_CreateUnimodemTimer>
extern __imp_FreeUnimodemTimer:PANYARGS
FreeUnimodemTimer TEXTEQU <__imp_FreeUnimodemTimer>
extern __imp_SetUnimodemTimer:PANYARGS
SetUnimodemTimer TEXTEQU <__imp_SetUnimodemTimer>
extern __imp_CancelUnimodemTimer:PANYARGS
CancelUnimodemTimer TEXTEQU <__imp_CancelUnimodemTimer>
extern __imp_CreateOverStructPool:PANYARGS
CreateOverStructPool TEXTEQU <__imp_CreateOverStructPool>
extern __imp_DestroyOverStructPool:PANYARGS
DestroyOverStructPool TEXTEQU <__imp_DestroyOverStructPool>
extern __imp_AllocateOverStructEx:PANYARGS
AllocateOverStructEx TEXTEQU <__imp_AllocateOverStructEx>
extern __imp_FreeOverStruct:PANYARGS
FreeOverStruct TEXTEQU <__imp_FreeOverStruct>
extern __imp_ReinitOverStruct:PANYARGS
ReinitOverStruct TEXTEQU <__imp_ReinitOverStruct>
extern __imp_SyncDeviceIoControl:PANYARGS
SyncDeviceIoControl TEXTEQU <__imp_SyncDeviceIoControl>
extern __imp_WinntIsWorkstation:PANYARGS
WinntIsWorkstation TEXTEQU <__imp_WinntIsWorkstation>
extern __imp_uniplat_ordinal118:PANYARGS
uniplat_ordinal118 TEXTEQU <__imp_uniplat_ordinal118>
extern __imp_uniplat_ordinal119:PANYARGS
uniplat_ordinal119 TEXTEQU <__imp_uniplat_ordinal119>
extern __imp_uniplat_ordinal120:PANYARGS
uniplat_ordinal120 TEXTEQU <__imp_uniplat_ordinal120>
extern __imp_uniplat_ordinal121:PANYARGS
uniplat_ordinal121 TEXTEQU <__imp_uniplat_ordinal121>
extern __imp_uniplat_ordinal122:PANYARGS
uniplat_ordinal122 TEXTEQU <__imp_uniplat_ordinal122>
extern __imp_uniplat_ordinal123:PANYARGS
uniplat_ordinal123 TEXTEQU <__imp_uniplat_ordinal123>
extern __imp_uniplat_ordinal124:PANYARGS
uniplat_ordinal124 TEXTEQU <__imp_uniplat_ordinal124>
extern __imp_uniplat_ordinal125:PANYARGS
uniplat_ordinal125 TEXTEQU <__imp_uniplat_ordinal125>
extern __imp_uniplat_ordinal126:PANYARGS
uniplat_ordinal126 TEXTEQU <__imp_uniplat_ordinal126>
extern __imp_uniplat_ordinal127:PANYARGS
uniplat_ordinal127 TEXTEQU <__imp_uniplat_ordinal127>
extern __imp_uniplat_ordinal128:PANYARGS
uniplat_ordinal128 TEXTEQU <__imp_uniplat_ordinal128>
extern __imp_uniplat_ordinal129:PANYARGS
uniplat_ordinal129 TEXTEQU <__imp_uniplat_ordinal129>
extern __imp_uniplat_ordinal130:PANYARGS
uniplat_ordinal130 TEXTEQU <__imp_uniplat_ordinal130>
extern __imp_uniplat_ordinal131:PANYARGS
uniplat_ordinal131 TEXTEQU <__imp_uniplat_ordinal131>
extern __imp_uniplat_ordinal132:PANYARGS
uniplat_ordinal132 TEXTEQU <__imp_uniplat_ordinal132>
extern __imp_uniplat_ordinal133:PANYARGS
uniplat_ordinal133 TEXTEQU <__imp_uniplat_ordinal133>
extern __imp_uniplat_ordinal134:PANYARGS
uniplat_ordinal134 TEXTEQU <__imp_uniplat_ordinal134>
extern __imp_uniplat_ordinal135:PANYARGS
uniplat_ordinal135 TEXTEQU <__imp_uniplat_ordinal135>
extern __imp_uniplat_ordinal136:PANYARGS
uniplat_ordinal136 TEXTEQU <__imp_uniplat_ordinal136>
extern __imp_uniplat_ordinal137:PANYARGS
uniplat_ordinal137 TEXTEQU <__imp_uniplat_ordinal137>
extern __imp_uniplat_ordinal138:PANYARGS
uniplat_ordinal138 TEXTEQU <__imp_uniplat_ordinal138>
extern __imp_uniplat_ordinal139:PANYARGS
uniplat_ordinal139 TEXTEQU <__imp_uniplat_ordinal139>
extern __imp_uniplat_ordinal140:PANYARGS
uniplat_ordinal140 TEXTEQU <__imp_uniplat_ordinal140>
extern __imp_uniplat_ordinal141:PANYARGS
uniplat_ordinal141 TEXTEQU <__imp_uniplat_ordinal141>
extern __imp_uniplat_ordinal142:PANYARGS
uniplat_ordinal142 TEXTEQU <__imp_uniplat_ordinal142>
extern __imp_uniplat_ordinal143:PANYARGS
uniplat_ordinal143 TEXTEQU <__imp_uniplat_ordinal143>
extern __imp_uniplat_ordinal144:PANYARGS
uniplat_ordinal144 TEXTEQU <__imp_uniplat_ordinal144>
extern __imp_uniplat_ordinal145:PANYARGS
uniplat_ordinal145 TEXTEQU <__imp_uniplat_ordinal145>
extern __imp_uniplat_ordinal146:PANYARGS
uniplat_ordinal146 TEXTEQU <__imp_uniplat_ordinal146>
extern __imp_uniplat_ordinal147:PANYARGS
uniplat_ordinal147 TEXTEQU <__imp_uniplat_ordinal147>
extern __imp_uniplat_ordinal148:PANYARGS
uniplat_ordinal148 TEXTEQU <__imp_uniplat_ordinal148>
extern __imp_uniplat_ordinal149:PANYARGS
uniplat_ordinal149 TEXTEQU <__imp_uniplat_ordinal149>
extern __imp_uniplat_ordinal150:PANYARGS
uniplat_ordinal150 TEXTEQU <__imp_uniplat_ordinal150>
extern __imp_uniplat_ordinal151:PANYARGS
uniplat_ordinal151 TEXTEQU <__imp_uniplat_ordinal151>
extern __imp_uniplat_ordinal152:PANYARGS
uniplat_ordinal152 TEXTEQU <__imp_uniplat_ordinal152>
extern __imp_uniplat_ordinal153:PANYARGS
uniplat_ordinal153 TEXTEQU <__imp_uniplat_ordinal153>
extern __imp_uniplat_ordinal154:PANYARGS
uniplat_ordinal154 TEXTEQU <__imp_uniplat_ordinal154>
extern __imp_uniplat_ordinal155:PANYARGS
uniplat_ordinal155 TEXTEQU <__imp_uniplat_ordinal155>
extern __imp_uniplat_ordinal156:PANYARGS
uniplat_ordinal156 TEXTEQU <__imp_uniplat_ordinal156>
extern __imp_uniplat_ordinal157:PANYARGS
uniplat_ordinal157 TEXTEQU <__imp_uniplat_ordinal157>
extern __imp_uniplat_ordinal158:PANYARGS
uniplat_ordinal158 TEXTEQU <__imp_uniplat_ordinal158>
extern __imp_uniplat_ordinal159:PANYARGS
uniplat_ordinal159 TEXTEQU <__imp_uniplat_ordinal159>
extern __imp_uniplat_ordinal160:PANYARGS
uniplat_ordinal160 TEXTEQU <__imp_uniplat_ordinal160>
extern __imp_uniplat_ordinal161:PANYARGS
uniplat_ordinal161 TEXTEQU <__imp_uniplat_ordinal161>
extern __imp_uniplat_ordinal162:PANYARGS
uniplat_ordinal162 TEXTEQU <__imp_uniplat_ordinal162>
extern __imp_uniplat_ordinal163:PANYARGS
uniplat_ordinal163 TEXTEQU <__imp_uniplat_ordinal163>
extern __imp_uniplat_ordinal164:PANYARGS
uniplat_ordinal164 TEXTEQU <__imp_uniplat_ordinal164>
extern __imp_uniplat_ordinal165:PANYARGS
uniplat_ordinal165 TEXTEQU <__imp_uniplat_ordinal165>
extern __imp_uniplat_ordinal166:PANYARGS
uniplat_ordinal166 TEXTEQU <__imp_uniplat_ordinal166>
extern __imp_uniplat_ordinal167:PANYARGS
uniplat_ordinal167 TEXTEQU <__imp_uniplat_ordinal167>
extern __imp_uniplat_ordinal168:PANYARGS
uniplat_ordinal168 TEXTEQU <__imp_uniplat_ordinal168>
extern __imp_uniplat_ordinal169:PANYARGS
uniplat_ordinal169 TEXTEQU <__imp_uniplat_ordinal169>
extern __imp_uniplat_ordinal170:PANYARGS
uniplat_ordinal170 TEXTEQU <__imp_uniplat_ordinal170>
extern __imp_uniplat_ordinal171:PANYARGS
uniplat_ordinal171 TEXTEQU <__imp_uniplat_ordinal171>
extern __imp_uniplat_ordinal172:PANYARGS
uniplat_ordinal172 TEXTEQU <__imp_uniplat_ordinal172>
extern __imp_uniplat_ordinal173:PANYARGS
uniplat_ordinal173 TEXTEQU <__imp_uniplat_ordinal173>
extern __imp_uniplat_ordinal174:PANYARGS
uniplat_ordinal174 TEXTEQU <__imp_uniplat_ordinal174>
extern __imp_uniplat_ordinal175:PANYARGS
uniplat_ordinal175 TEXTEQU <__imp_uniplat_ordinal175>
extern __imp_uniplat_ordinal176:PANYARGS
uniplat_ordinal176 TEXTEQU <__imp_uniplat_ordinal176>
extern __imp_uniplat_ordinal177:PANYARGS
uniplat_ordinal177 TEXTEQU <__imp_uniplat_ordinal177>
extern __imp_uniplat_ordinal178:PANYARGS
uniplat_ordinal178 TEXTEQU <__imp_uniplat_ordinal178>
extern __imp_uniplat_ordinal179:PANYARGS
uniplat_ordinal179 TEXTEQU <__imp_uniplat_ordinal179>
extern __imp_uniplat_ordinal180:PANYARGS
uniplat_ordinal180 TEXTEQU <__imp_uniplat_ordinal180>
extern __imp_uniplat_ordinal181:PANYARGS
uniplat_ordinal181 TEXTEQU <__imp_uniplat_ordinal181>
extern __imp_uniplat_ordinal182:PANYARGS
uniplat_ordinal182 TEXTEQU <__imp_uniplat_ordinal182>
extern __imp_uniplat_ordinal183:PANYARGS
uniplat_ordinal183 TEXTEQU <__imp_uniplat_ordinal183>
extern __imp_uniplat_ordinal184:PANYARGS
uniplat_ordinal184 TEXTEQU <__imp_uniplat_ordinal184>
extern __imp_uniplat_ordinal185:PANYARGS
uniplat_ordinal185 TEXTEQU <__imp_uniplat_ordinal185>
extern __imp_uniplat_ordinal186:PANYARGS
uniplat_ordinal186 TEXTEQU <__imp_uniplat_ordinal186>
extern __imp_uniplat_ordinal187:PANYARGS
uniplat_ordinal187 TEXTEQU <__imp_uniplat_ordinal187>
extern __imp_uniplat_ordinal188:PANYARGS
uniplat_ordinal188 TEXTEQU <__imp_uniplat_ordinal188>
extern __imp_uniplat_ordinal189:PANYARGS
uniplat_ordinal189 TEXTEQU <__imp_uniplat_ordinal189>
extern __imp_uniplat_ordinal190:PANYARGS
uniplat_ordinal190 TEXTEQU <__imp_uniplat_ordinal190>
extern __imp_uniplat_ordinal191:PANYARGS
uniplat_ordinal191 TEXTEQU <__imp_uniplat_ordinal191>
extern __imp_uniplat_ordinal192:PANYARGS
uniplat_ordinal192 TEXTEQU <__imp_uniplat_ordinal192>
extern __imp_uniplat_ordinal193:PANYARGS
uniplat_ordinal193 TEXTEQU <__imp_uniplat_ordinal193>
extern __imp_uniplat_ordinal194:PANYARGS
uniplat_ordinal194 TEXTEQU <__imp_uniplat_ordinal194>
extern __imp_uniplat_ordinal195:PANYARGS
uniplat_ordinal195 TEXTEQU <__imp_uniplat_ordinal195>
extern __imp_uniplat_ordinal196:PANYARGS
uniplat_ordinal196 TEXTEQU <__imp_uniplat_ordinal196>
extern __imp_uniplat_ordinal197:PANYARGS
uniplat_ordinal197 TEXTEQU <__imp_uniplat_ordinal197>
extern __imp_uniplat_ordinal198:PANYARGS
uniplat_ordinal198 TEXTEQU <__imp_uniplat_ordinal198>
extern __imp_uniplat_ordinal199:PANYARGS
uniplat_ordinal199 TEXTEQU <__imp_uniplat_ordinal199>
extern __imp_uniplat_ordinal200:PANYARGS
uniplat_ordinal200 TEXTEQU <__imp_uniplat_ordinal200>
extern __imp_uniplat_ordinal201:PANYARGS
uniplat_ordinal201 TEXTEQU <__imp_uniplat_ordinal201>
extern __imp_uniplat_ordinal202:PANYARGS
uniplat_ordinal202 TEXTEQU <__imp_uniplat_ordinal202>
extern __imp_uniplat_ordinal203:PANYARGS
uniplat_ordinal203 TEXTEQU <__imp_uniplat_ordinal203>
extern __imp_uniplat_ordinal204:PANYARGS
uniplat_ordinal204 TEXTEQU <__imp_uniplat_ordinal204>
extern __imp_uniplat_ordinal205:PANYARGS
uniplat_ordinal205 TEXTEQU <__imp_uniplat_ordinal205>
extern __imp_uniplat_ordinal206:PANYARGS
uniplat_ordinal206 TEXTEQU <__imp_uniplat_ordinal206>
extern __imp_UnimodemNotifyTSP:PANYARGS
UnimodemNotifyTSP TEXTEQU <__imp_UnimodemNotifyTSP>
extern __imp_uniplat_ordinal208:PANYARGS
uniplat_ordinal208 TEXTEQU <__imp_uniplat_ordinal208>
extern __imp_uniplat_ordinal209:PANYARGS
uniplat_ordinal209 TEXTEQU <__imp_uniplat_ordinal209>
extern __imp_StartMonitorThread:PANYARGS
StartMonitorThread TEXTEQU <__imp_StartMonitorThread>
extern __imp_StopMonitorThread:PANYARGS
StopMonitorThread TEXTEQU <__imp_StopMonitorThread>
extern __imp_MonitorHandle:PANYARGS
MonitorHandle TEXTEQU <__imp_MonitorHandle>
extern __imp_StopMonitoringHandle:PANYARGS
StopMonitoringHandle TEXTEQU <__imp_StopMonitoringHandle>
extern __imp_CallBeginning:PANYARGS
CallBeginning TEXTEQU <__imp_CallBeginning>
extern __imp_CallEnding:PANYARGS
CallEnding TEXTEQU <__imp_CallEnding>
extern __imp_ResetCallCount:PANYARGS
ResetCallCount TEXTEQU <__imp_ResetCallCount>
