extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_InstallUPnPUI:PANYARGS
InstallUPnPUI TEXTEQU <__imp_InstallUPnPUI>
extern __imp_IsUPnPUIInstalled:PANYARGS
IsUPnPUIInstalled TEXTEQU <__imp_IsUPnPUIInstalled>
extern __imp_UnInstallUPnPUI:PANYARGS
UnInstallUPnPUI TEXTEQU <__imp_UnInstallUPnPUI>
