extern __imp_url_ordinal101:PANYARGS
url_ordinal101 TEXTEQU <__imp_url_ordinal101>
extern __imp_AddMIMEFileTypesPS:PANYARGS
AddMIMEFileTypesPS TEXTEQU <__imp_AddMIMEFileTypesPS>
extern __imp_AutodialHookCallback:PANYARGS
AutodialHookCallback TEXTEQU <__imp_AutodialHookCallback>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_FileProtocolHandler:PANYARGS
FileProtocolHandler TEXTEQU <__imp_FileProtocolHandler>
extern __imp_FileProtocolHandlerA:PANYARGS
FileProtocolHandler  TEXTEQU <__imp_FileProtocolHandlerA>
extern __imp_InetIsOffline:PANYARGS
InetIsOffline TEXTEQU <__imp_InetIsOffline>
extern __imp_MIMEAssociationDialogA:PANYARGS
MIMEAssociationDialog  TEXTEQU <__imp_MIMEAssociationDialogA>
extern __imp_MIMEAssociationDialogW:PANYARGS
MIMEAssociationDialogW TEXTEQU <__imp_MIMEAssociationDialogW>
extern __imp_MailToProtocolHandler:PANYARGS
MailToProtocolHandler TEXTEQU <__imp_MailToProtocolHandler>
extern __imp_MailToProtocolHandlerA:PANYARGS
MailToProtocolHandler  TEXTEQU <__imp_MailToProtocolHandlerA>
extern __imp_NewsProtocolHandler:PANYARGS
NewsProtocolHandler TEXTEQU <__imp_NewsProtocolHandler>
extern __imp_NewsProtocolHandlerA:PANYARGS
NewsProtocolHandler  TEXTEQU <__imp_NewsProtocolHandlerA>
extern __imp_OpenURL:PANYARGS
OpenURL TEXTEQU <__imp_OpenURL>
extern __imp_OpenURLA:PANYARGS
OpenURL  TEXTEQU <__imp_OpenURLA>
extern __imp_TelnetProtocolHandler:PANYARGS
TelnetProtocolHandler TEXTEQU <__imp_TelnetProtocolHandler>
extern __imp_TelnetProtocolHandlerA:PANYARGS
TelnetProtocolHandler  TEXTEQU <__imp_TelnetProtocolHandlerA>
extern __imp_TranslateURLA:PANYARGS
TranslateURL  TEXTEQU <__imp_TranslateURLA>
extern __imp_TranslateURLW:PANYARGS
TranslateURLW TEXTEQU <__imp_TranslateURLW>
extern __imp_URLAssociationDialogA:PANYARGS
URLAssociationDialog  TEXTEQU <__imp_URLAssociationDialogA>
extern __imp_URLAssociationDialogW:PANYARGS
URLAssociationDialogW TEXTEQU <__imp_URLAssociationDialogW>
