extern __imp_urlmon_ordinal100:PANYARGS
urlmon_ordinal100 TEXTEQU <__imp_urlmon_ordinal100>
extern __imp_AsyncGetClassBits:PANYARGS
AsyncGetClassBits TEXTEQU <__imp_AsyncGetClassBits>
extern __imp_AsyncInstallDistributionUnit:PANYARGS
AsyncInstallDistributionUnit TEXTEQU <__imp_AsyncInstallDistributionUnit>
extern __imp_BindAsyncMoniker:PANYARGS
BindAsyncMoniker TEXTEQU <__imp_BindAsyncMoniker>
extern __imp_CDLGetLongPathNameA:PANYARGS
CDLGetLongPathName  TEXTEQU <__imp_CDLGetLongPathNameA>
extern __imp_CDLGetLongPathNameW:PANYARGS
CDLGetLongPathNameW TEXTEQU <__imp_CDLGetLongPathNameW>
extern __imp_CoGetClassObjectFromURL:PANYARGS
CoGetClassObjectFromURL TEXTEQU <__imp_CoGetClassObjectFromURL>
extern __imp_CoInstall:PANYARGS
CoInstall TEXTEQU <__imp_CoInstall>
extern __imp_CoInternetCombineUrl:PANYARGS
CoInternetCombineUrl TEXTEQU <__imp_CoInternetCombineUrl>
extern __imp_CoInternetCompareUrl:PANYARGS
CoInternetCompareUrl TEXTEQU <__imp_CoInternetCompareUrl>
extern __imp_CoInternetCreateSecurityManager:PANYARGS
CoInternetCreateSecurityManager TEXTEQU <__imp_CoInternetCreateSecurityManager>
extern __imp_CoInternetCreateZoneManager:PANYARGS
CoInternetCreateZoneManager TEXTEQU <__imp_CoInternetCreateZoneManager>
extern __imp_CoInternetFeatureSettingsChanged:PANYARGS
CoInternetFeatureSettingsChanged TEXTEQU <__imp_CoInternetFeatureSettingsChanged>
extern __imp_CoInternetGetProtocolFlags:PANYARGS
CoInternetGetProtocolFlags TEXTEQU <__imp_CoInternetGetProtocolFlags>
extern __imp_CoInternetGetSecurityUrl:PANYARGS
CoInternetGetSecurityUrl TEXTEQU <__imp_CoInternetGetSecurityUrl>
extern __imp_CoInternetGetSession:PANYARGS
CoInternetGetSession TEXTEQU <__imp_CoInternetGetSession>
extern __imp_CoInternetIsFeatureEnabled:PANYARGS
CoInternetIsFeatureEnabled TEXTEQU <__imp_CoInternetIsFeatureEnabled>
extern __imp_CoInternetIsFeatureEnabledForUrl:PANYARGS
CoInternetIsFeatureEnabledForUrl TEXTEQU <__imp_CoInternetIsFeatureEnabledForUrl>
extern __imp_CoInternetIsFeatureZoneElevationEnabled:PANYARGS
CoInternetIsFeatureZoneElevationEnabled TEXTEQU <__imp_CoInternetIsFeatureZoneElevationEnabled>
extern __imp_CoInternetParseUrl:PANYARGS
CoInternetParseUrl TEXTEQU <__imp_CoInternetParseUrl>
extern __imp_CoInternetQueryInfo:PANYARGS
CoInternetQueryInfo TEXTEQU <__imp_CoInternetQueryInfo>
extern __imp_CoInternetSetFeatureEnabled:PANYARGS
CoInternetSetFeatureEnabled TEXTEQU <__imp_CoInternetSetFeatureEnabled>
extern __imp_CompareSecurityIds:PANYARGS
CompareSecurityIds TEXTEQU <__imp_CompareSecurityIds>
extern __imp_CompatFlagsFromClsid:PANYARGS
CompatFlagsFromClsid TEXTEQU <__imp_CompatFlagsFromClsid>
extern __imp_CopyBindInfo:PANYARGS
CopyBindInfo TEXTEQU <__imp_CopyBindInfo>
extern __imp_CopyStgMedium:PANYARGS
CopyStgMedium TEXTEQU <__imp_CopyStgMedium>
extern __imp_CreateAsyncBindCtx:PANYARGS
CreateAsyncBindCtx TEXTEQU <__imp_CreateAsyncBindCtx>
extern __imp_CreateAsyncBindCtxEx:PANYARGS
CreateAsyncBindCtxEx TEXTEQU <__imp_CreateAsyncBindCtxEx>
extern __imp_CreateFormatEnumerator:PANYARGS
CreateFormatEnumerator TEXTEQU <__imp_CreateFormatEnumerator>
extern __imp_CreateURLMoniker:PANYARGS
CreateURLMoniker TEXTEQU <__imp_CreateURLMoniker>
extern __imp_CreateURLMonikerEx:PANYARGS
CreateURLMonikerEx TEXTEQU <__imp_CreateURLMonikerEx>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllRegisterServerEx:PANYARGS
DllRegisterServerEx TEXTEQU <__imp_DllRegisterServerEx>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_Extract:PANYARGS
Extract TEXTEQU <__imp_Extract>
extern __imp_FaultInIEFeature:PANYARGS
FaultInIEFeature TEXTEQU <__imp_FaultInIEFeature>
extern __imp_FindMediaType:PANYARGS
FindMediaType TEXTEQU <__imp_FindMediaType>
extern __imp_FindMediaTypeClass:PANYARGS
FindMediaTypeClass TEXTEQU <__imp_FindMediaTypeClass>
extern __imp_FindMimeFromData:PANYARGS
FindMimeFromData TEXTEQU <__imp_FindMimeFromData>
extern __imp_GetAddSitesFileUrl:PANYARGS
GetAddSitesFileUrl TEXTEQU <__imp_GetAddSitesFileUrl>
extern __imp_GetClassFileOrMime:PANYARGS
GetClassFileOrMime TEXTEQU <__imp_GetClassFileOrMime>
extern __imp_GetClassURL:PANYARGS
GetClassURL TEXTEQU <__imp_GetClassURL>
extern __imp_GetComponentIDFromCLSSPEC:PANYARGS
GetComponentIDFromCLSSPEC TEXTEQU <__imp_GetComponentIDFromCLSSPEC>
extern __imp_GetMarkOfTheWeb:PANYARGS
GetMarkOfTheWeb TEXTEQU <__imp_GetMarkOfTheWeb>
extern __imp_GetSoftwareUpdateInfo:PANYARGS
GetSoftwareUpdateInfo TEXTEQU <__imp_GetSoftwareUpdateInfo>
extern __imp_HlinkGoBack:PANYARGS
HlinkGoBack TEXTEQU <__imp_HlinkGoBack>
extern __imp_HlinkGoForward:PANYARGS
HlinkGoForward TEXTEQU <__imp_HlinkGoForward>
extern __imp_HlinkNavigateMoniker:PANYARGS
HlinkNavigateMoniker TEXTEQU <__imp_HlinkNavigateMoniker>
extern __imp_HlinkNavigateString:PANYARGS
HlinkNavigateString TEXTEQU <__imp_HlinkNavigateString>
extern __imp_HlinkSimpleNavigateToMoniker:PANYARGS
HlinkSimpleNavigateToMoniker TEXTEQU <__imp_HlinkSimpleNavigateToMoniker>
extern __imp_HlinkSimpleNavigateToString:PANYARGS
HlinkSimpleNavigateToString TEXTEQU <__imp_HlinkSimpleNavigateToString>
extern __imp_InstallFlash:PANYARGS
InstallFlash TEXTEQU <__imp_InstallFlash>
extern __imp_IsAsyncMoniker:PANYARGS
IsAsyncMoniker TEXTEQU <__imp_IsAsyncMoniker>
extern __imp_IsJITInProgress:PANYARGS
IsJITInProgress TEXTEQU <__imp_IsJITInProgress>
extern __imp_IsLoggingEnabledA:PANYARGS
IsLoggingEnabled  TEXTEQU <__imp_IsLoggingEnabledA>
extern __imp_IsLoggingEnabledW:PANYARGS
IsLoggingEnabledW TEXTEQU <__imp_IsLoggingEnabledW>
extern __imp_IsValidURL:PANYARGS
IsValidURL TEXTEQU <__imp_IsValidURL>
extern __imp_MkParseDisplayNameEx:PANYARGS
MkParseDisplayNameEx TEXTEQU <__imp_MkParseDisplayNameEx>
extern __imp_ObtainUserAgentString:PANYARGS
ObtainUserAgentString TEXTEQU <__imp_ObtainUserAgentString>
extern __imp_PrivateCoInstall:PANYARGS
PrivateCoInstall TEXTEQU <__imp_PrivateCoInstall>
extern __imp_RegisterBindStatusCallback:PANYARGS
RegisterBindStatusCallback TEXTEQU <__imp_RegisterBindStatusCallback>
extern __imp_RegisterFormatEnumerator:PANYARGS
RegisterFormatEnumerator TEXTEQU <__imp_RegisterFormatEnumerator>
extern __imp_RegisterMediaTypeClass:PANYARGS
RegisterMediaTypeClass TEXTEQU <__imp_RegisterMediaTypeClass>
extern __imp_RegisterMediaTypes:PANYARGS
RegisterMediaTypes TEXTEQU <__imp_RegisterMediaTypes>
extern __imp_ReleaseBindInfo:PANYARGS
ReleaseBindInfo TEXTEQU <__imp_ReleaseBindInfo>
extern __imp_RevokeBindStatusCallback:PANYARGS
RevokeBindStatusCallback TEXTEQU <__imp_RevokeBindStatusCallback>
extern __imp_RevokeFormatEnumerator:PANYARGS
RevokeFormatEnumerator TEXTEQU <__imp_RevokeFormatEnumerator>
extern __imp_SetSoftwareUpdateAdvertisementState:PANYARGS
SetSoftwareUpdateAdvertisementState TEXTEQU <__imp_SetSoftwareUpdateAdvertisementState>
extern __imp_ShowTrustAlertDialog:PANYARGS
ShowTrustAlertDialog TEXTEQU <__imp_ShowTrustAlertDialog>
extern __imp_URLDownloadA:PANYARGS
URLDownload  TEXTEQU <__imp_URLDownloadA>
extern __imp_URLDownloadToCacheFileA:PANYARGS
URLDownloadToCacheFile  TEXTEQU <__imp_URLDownloadToCacheFileA>
extern __imp_URLDownloadToCacheFileW:PANYARGS
URLDownloadToCacheFileW TEXTEQU <__imp_URLDownloadToCacheFileW>
extern __imp_URLDownloadToFileA:PANYARGS
URLDownloadToFile  TEXTEQU <__imp_URLDownloadToFileA>
extern __imp_URLDownloadToFileW:PANYARGS
URLDownloadToFileW TEXTEQU <__imp_URLDownloadToFileW>
extern __imp_URLDownloadW:PANYARGS
URLDownloadW TEXTEQU <__imp_URLDownloadW>
extern __imp_URLOpenBlockingStreamA:PANYARGS
URLOpenBlockingStream  TEXTEQU <__imp_URLOpenBlockingStreamA>
extern __imp_URLOpenBlockingStreamW:PANYARGS
URLOpenBlockingStreamW TEXTEQU <__imp_URLOpenBlockingStreamW>
extern __imp_URLOpenPullStreamA:PANYARGS
URLOpenPullStream  TEXTEQU <__imp_URLOpenPullStreamA>
extern __imp_URLOpenPullStreamW:PANYARGS
URLOpenPullStreamW TEXTEQU <__imp_URLOpenPullStreamW>
extern __imp_URLOpenStreamA:PANYARGS
URLOpenStream  TEXTEQU <__imp_URLOpenStreamA>
extern __imp_URLOpenStreamW:PANYARGS
URLOpenStreamW TEXTEQU <__imp_URLOpenStreamW>
extern __imp_UrlMkBuildVersion:PANYARGS
UrlMkBuildVersion TEXTEQU <__imp_UrlMkBuildVersion>
extern __imp_UrlMkGetSessionOption:PANYARGS
UrlMkGetSessionOption TEXTEQU <__imp_UrlMkGetSessionOption>
extern __imp_UrlMkSetSessionOption:PANYARGS
UrlMkSetSessionOption TEXTEQU <__imp_UrlMkSetSessionOption>
extern __imp_WriteHitLogging:PANYARGS
WriteHitLogging TEXTEQU <__imp_WriteHitLogging>
extern __imp_ZonesReInit:PANYARGS
ZonesReInit TEXTEQU <__imp_ZonesReInit>
