extern __imp_LpkPresent:PANYARGS
LpkPresent TEXTEQU <__imp_LpkPresent>
extern __imp_ScriptApplyDigitSubstitution:PANYARGS
ScriptApplyDigitSubstitution TEXTEQU <__imp_ScriptApplyDigitSubstitution>
extern __imp_ScriptApplyLogicalWidth:PANYARGS
ScriptApplyLogicalWidth TEXTEQU <__imp_ScriptApplyLogicalWidth>
extern __imp_ScriptBreak:PANYARGS
ScriptBreak TEXTEQU <__imp_ScriptBreak>
extern __imp_ScriptCPtoX:PANYARGS
ScriptCPtoX TEXTEQU <__imp_ScriptCPtoX>
extern __imp_ScriptCacheGetHeight:PANYARGS
ScriptCacheGetHeight TEXTEQU <__imp_ScriptCacheGetHeight>
extern __imp_ScriptFreeCache:PANYARGS
ScriptFreeCache TEXTEQU <__imp_ScriptFreeCache>
extern __imp_ScriptGetCMap:PANYARGS
ScriptGetCMap TEXTEQU <__imp_ScriptGetCMap>
extern __imp_ScriptGetFontProperties:PANYARGS
ScriptGetFontProperties TEXTEQU <__imp_ScriptGetFontProperties>
extern __imp_ScriptGetGlyphABCWidth:PANYARGS
ScriptGetGlyphABCWidth TEXTEQU <__imp_ScriptGetGlyphABCWidth>
extern __imp_ScriptGetLogicalWidths:PANYARGS
ScriptGetLogicalWidths TEXTEQU <__imp_ScriptGetLogicalWidths>
extern __imp_ScriptGetProperties:PANYARGS
ScriptGetProperties TEXTEQU <__imp_ScriptGetProperties>
extern __imp_ScriptIsComplex:PANYARGS
ScriptIsComplex TEXTEQU <__imp_ScriptIsComplex>
extern __imp_ScriptItemize:PANYARGS
ScriptItemize TEXTEQU <__imp_ScriptItemize>
extern __imp_ScriptJustify:PANYARGS
ScriptJustify TEXTEQU <__imp_ScriptJustify>
extern __imp_ScriptLayout:PANYARGS
ScriptLayout TEXTEQU <__imp_ScriptLayout>
extern __imp_ScriptPlace:PANYARGS
ScriptPlace TEXTEQU <__imp_ScriptPlace>
extern __imp_ScriptRecordDigitSubstitution:PANYARGS
ScriptRecordDigitSubstitution TEXTEQU <__imp_ScriptRecordDigitSubstitution>
extern __imp_ScriptShape:PANYARGS
ScriptShape TEXTEQU <__imp_ScriptShape>
extern __imp_ScriptStringAnalyse:PANYARGS
ScriptStringAnalyse TEXTEQU <__imp_ScriptStringAnalyse>
extern __imp_ScriptStringCPtoX:PANYARGS
ScriptStringCPtoX TEXTEQU <__imp_ScriptStringCPtoX>
extern __imp_ScriptStringFree:PANYARGS
ScriptStringFree TEXTEQU <__imp_ScriptStringFree>
extern __imp_ScriptStringGetLogicalWidths:PANYARGS
ScriptStringGetLogicalWidths TEXTEQU <__imp_ScriptStringGetLogicalWidths>
extern __imp_ScriptStringGetOrder:PANYARGS
ScriptStringGetOrder TEXTEQU <__imp_ScriptStringGetOrder>
extern __imp_ScriptStringOut:PANYARGS
ScriptStringOut TEXTEQU <__imp_ScriptStringOut>
extern __imp_ScriptStringValidate:PANYARGS
ScriptStringValidate TEXTEQU <__imp_ScriptStringValidate>
extern __imp_ScriptStringXtoCP:PANYARGS
ScriptStringXtoCP TEXTEQU <__imp_ScriptStringXtoCP>
extern __imp_ScriptString_pLogAttr:PANYARGS
ScriptString_pLogAttr TEXTEQU <__imp_ScriptString_pLogAttr>
extern __imp_ScriptString_pSize:PANYARGS
ScriptString_pSize TEXTEQU <__imp_ScriptString_pSize>
extern __imp_ScriptString_pcOutChars:PANYARGS
ScriptString_pcOutChars TEXTEQU <__imp_ScriptString_pcOutChars>
extern __imp_ScriptTextOut:PANYARGS
ScriptTextOut TEXTEQU <__imp_ScriptTextOut>
extern __imp_ScriptXtoCP:PANYARGS
ScriptXtoCP TEXTEQU <__imp_ScriptXtoCP>
extern __imp_UspAllocCache:PANYARGS
UspAllocCache TEXTEQU <__imp_UspAllocCache>
extern __imp_UspAllocTemp:PANYARGS
UspAllocTemp TEXTEQU <__imp_UspAllocTemp>
extern __imp_UspFreeMem:PANYARGS
UspFreeMem TEXTEQU <__imp_UspFreeMem>
