extern __imp_uxtheme_ordinal1:PANYARGS
uxtheme_ordinal1 TEXTEQU <__imp_uxtheme_ordinal1>
extern __imp_uxtheme_ordinal2:PANYARGS
uxtheme_ordinal2 TEXTEQU <__imp_uxtheme_ordinal2>
extern __imp_uxtheme_ordinal3:PANYARGS
uxtheme_ordinal3 TEXTEQU <__imp_uxtheme_ordinal3>
extern __imp_uxtheme_ordinal4:PANYARGS
uxtheme_ordinal4 TEXTEQU <__imp_uxtheme_ordinal4>
extern __imp_CloseThemeData:PANYARGS
CloseThemeData TEXTEQU <__imp_CloseThemeData>
extern __imp_DrawThemeBackground:PANYARGS
DrawThemeBackground TEXTEQU <__imp_DrawThemeBackground>
extern __imp_uxtheme_ordinal7:PANYARGS
uxtheme_ordinal7 TEXTEQU <__imp_uxtheme_ordinal7>
extern __imp_uxtheme_ordinal8:PANYARGS
uxtheme_ordinal8 TEXTEQU <__imp_uxtheme_ordinal8>
extern __imp_uxtheme_ordinal9:PANYARGS
uxtheme_ordinal9 TEXTEQU <__imp_uxtheme_ordinal9>
extern __imp_uxtheme_ordinal10:PANYARGS
uxtheme_ordinal10 TEXTEQU <__imp_uxtheme_ordinal10>
extern __imp_uxtheme_ordinal11:PANYARGS
uxtheme_ordinal11 TEXTEQU <__imp_uxtheme_ordinal11>
extern __imp_DrawThemeEdge:PANYARGS
DrawThemeEdge TEXTEQU <__imp_DrawThemeEdge>
extern __imp_uxtheme_ordinal13:PANYARGS
uxtheme_ordinal13 TEXTEQU <__imp_uxtheme_ordinal13>
extern __imp_uxtheme_ordinal14:PANYARGS
uxtheme_ordinal14 TEXTEQU <__imp_uxtheme_ordinal14>
extern __imp_uxtheme_ordinal15:PANYARGS
uxtheme_ordinal15 TEXTEQU <__imp_uxtheme_ordinal15>
extern __imp_uxtheme_ordinal16:PANYARGS
uxtheme_ordinal16 TEXTEQU <__imp_uxtheme_ordinal16>
extern __imp_uxtheme_ordinal17:PANYARGS
uxtheme_ordinal17 TEXTEQU <__imp_uxtheme_ordinal17>
extern __imp_uxtheme_ordinal18:PANYARGS
uxtheme_ordinal18 TEXTEQU <__imp_uxtheme_ordinal18>
extern __imp_uxtheme_ordinal19:PANYARGS
uxtheme_ordinal19 TEXTEQU <__imp_uxtheme_ordinal19>
extern __imp_uxtheme_ordinal20:PANYARGS
uxtheme_ordinal20 TEXTEQU <__imp_uxtheme_ordinal20>
extern __imp_uxtheme_ordinal21:PANYARGS
uxtheme_ordinal21 TEXTEQU <__imp_uxtheme_ordinal21>
extern __imp_uxtheme_ordinal22:PANYARGS
uxtheme_ordinal22 TEXTEQU <__imp_uxtheme_ordinal22>
extern __imp_uxtheme_ordinal23:PANYARGS
uxtheme_ordinal23 TEXTEQU <__imp_uxtheme_ordinal23>
extern __imp_uxtheme_ordinal24:PANYARGS
uxtheme_ordinal24 TEXTEQU <__imp_uxtheme_ordinal24>
extern __imp_uxtheme_ordinal25:PANYARGS
uxtheme_ordinal25 TEXTEQU <__imp_uxtheme_ordinal25>
extern __imp_uxtheme_ordinal26:PANYARGS
uxtheme_ordinal26 TEXTEQU <__imp_uxtheme_ordinal26>
extern __imp_uxtheme_ordinal27:PANYARGS
uxtheme_ordinal27 TEXTEQU <__imp_uxtheme_ordinal27>
extern __imp_uxtheme_ordinal28:PANYARGS
uxtheme_ordinal28 TEXTEQU <__imp_uxtheme_ordinal28>
extern __imp_uxtheme_ordinal29:PANYARGS
uxtheme_ordinal29 TEXTEQU <__imp_uxtheme_ordinal29>
extern __imp_uxtheme_ordinal30:PANYARGS
uxtheme_ordinal30 TEXTEQU <__imp_uxtheme_ordinal30>
extern __imp_uxtheme_ordinal31:PANYARGS
uxtheme_ordinal31 TEXTEQU <__imp_uxtheme_ordinal31>
extern __imp_uxtheme_ordinal32:PANYARGS
uxtheme_ordinal32 TEXTEQU <__imp_uxtheme_ordinal32>
extern __imp_uxtheme_ordinal33:PANYARGS
uxtheme_ordinal33 TEXTEQU <__imp_uxtheme_ordinal33>
extern __imp_uxtheme_ordinal34:PANYARGS
uxtheme_ordinal34 TEXTEQU <__imp_uxtheme_ordinal34>
extern __imp_uxtheme_ordinal35:PANYARGS
uxtheme_ordinal35 TEXTEQU <__imp_uxtheme_ordinal35>
extern __imp_uxtheme_ordinal36:PANYARGS
uxtheme_ordinal36 TEXTEQU <__imp_uxtheme_ordinal36>
extern __imp_DrawThemeIcon:PANYARGS
DrawThemeIcon TEXTEQU <__imp_DrawThemeIcon>
extern __imp_DrawThemeParentBackground:PANYARGS
DrawThemeParentBackground TEXTEQU <__imp_DrawThemeParentBackground>
extern __imp_DrawThemeText:PANYARGS
DrawThemeText TEXTEQU <__imp_DrawThemeText>
extern __imp_EnableThemeDialogTexture:PANYARGS
EnableThemeDialogTexture TEXTEQU <__imp_EnableThemeDialogTexture>
extern __imp_EnableTheming:PANYARGS
EnableTheming TEXTEQU <__imp_EnableTheming>
extern __imp_GetCurrentThemeName:PANYARGS
GetCurrentThemeName TEXTEQU <__imp_GetCurrentThemeName>
extern __imp_uxtheme_ordinal43:PANYARGS
uxtheme_ordinal43 TEXTEQU <__imp_uxtheme_ordinal43>
extern __imp_uxtheme_ordinal44:PANYARGS
uxtheme_ordinal44 TEXTEQU <__imp_uxtheme_ordinal44>
extern __imp_uxtheme_ordinal45:PANYARGS
uxtheme_ordinal45 TEXTEQU <__imp_uxtheme_ordinal45>
extern __imp_uxtheme_ordinal46:PANYARGS
uxtheme_ordinal46 TEXTEQU <__imp_uxtheme_ordinal46>
extern __imp_DrawThemeBackgroundEx:PANYARGS
DrawThemeBackgroundEx TEXTEQU <__imp_DrawThemeBackgroundEx>
extern __imp_uxtheme_ordinal48:PANYARGS
uxtheme_ordinal48 TEXTEQU <__imp_uxtheme_ordinal48>
extern __imp_GetThemeAppProperties:PANYARGS
GetThemeAppProperties TEXTEQU <__imp_GetThemeAppProperties>
extern __imp_GetThemeBackgroundContentRect:PANYARGS
GetThemeBackgroundContentRect TEXTEQU <__imp_GetThemeBackgroundContentRect>
extern __imp_GetThemeBackgroundExtent:PANYARGS
GetThemeBackgroundExtent TEXTEQU <__imp_GetThemeBackgroundExtent>
extern __imp_GetThemeBackgroundRegion:PANYARGS
GetThemeBackgroundRegion TEXTEQU <__imp_GetThemeBackgroundRegion>
extern __imp_GetThemeBool:PANYARGS
GetThemeBool TEXTEQU <__imp_GetThemeBool>
extern __imp_GetThemeColor:PANYARGS
GetThemeColor TEXTEQU <__imp_GetThemeColor>
extern __imp_GetThemeDocumentationProperty:PANYARGS
GetThemeDocumentationProperty TEXTEQU <__imp_GetThemeDocumentationProperty>
extern __imp_GetThemeEnumValue:PANYARGS
GetThemeEnumValue TEXTEQU <__imp_GetThemeEnumValue>
extern __imp_GetThemeFilename:PANYARGS
GetThemeFilename TEXTEQU <__imp_GetThemeFilename>
extern __imp_GetThemeFont:PANYARGS
GetThemeFont TEXTEQU <__imp_GetThemeFont>
extern __imp_GetThemeInt:PANYARGS
GetThemeInt TEXTEQU <__imp_GetThemeInt>
extern __imp_uxtheme_ordinal60:PANYARGS
uxtheme_ordinal60 TEXTEQU <__imp_uxtheme_ordinal60>
extern __imp_uxtheme_ordinal61:PANYARGS
uxtheme_ordinal61 TEXTEQU <__imp_uxtheme_ordinal61>
extern __imp_uxtheme_ordinal62:PANYARGS
uxtheme_ordinal62 TEXTEQU <__imp_uxtheme_ordinal62>
extern __imp_uxtheme_ordinal63:PANYARGS
uxtheme_ordinal63 TEXTEQU <__imp_uxtheme_ordinal63>
extern __imp_uxtheme_ordinal64:PANYARGS
uxtheme_ordinal64 TEXTEQU <__imp_uxtheme_ordinal64>
extern __imp_uxtheme_ordinal65:PANYARGS
uxtheme_ordinal65 TEXTEQU <__imp_uxtheme_ordinal65>
extern __imp_uxtheme_ordinal66:PANYARGS
uxtheme_ordinal66 TEXTEQU <__imp_uxtheme_ordinal66>
extern __imp_GetThemeIntList:PANYARGS
GetThemeIntList TEXTEQU <__imp_GetThemeIntList>
extern __imp_GetThemeMargins:PANYARGS
GetThemeMargins TEXTEQU <__imp_GetThemeMargins>
extern __imp_GetThemeMetric:PANYARGS
GetThemeMetric TEXTEQU <__imp_GetThemeMetric>
extern __imp_GetThemePartSize:PANYARGS
GetThemePartSize TEXTEQU <__imp_GetThemePartSize>
extern __imp_GetThemePosition:PANYARGS
GetThemePosition TEXTEQU <__imp_GetThemePosition>
extern __imp_GetThemePropertyOrigin:PANYARGS
GetThemePropertyOrigin TEXTEQU <__imp_GetThemePropertyOrigin>
extern __imp_uxtheme_ordinal73:PANYARGS
uxtheme_ordinal73 TEXTEQU <__imp_uxtheme_ordinal73>
extern __imp_GetThemeRect:PANYARGS
GetThemeRect TEXTEQU <__imp_GetThemeRect>
extern __imp_GetThemeString:PANYARGS
GetThemeString TEXTEQU <__imp_GetThemeString>
extern __imp_GetThemeSysBool:PANYARGS
GetThemeSysBool TEXTEQU <__imp_GetThemeSysBool>
extern __imp_GetThemeSysColor:PANYARGS
GetThemeSysColor TEXTEQU <__imp_GetThemeSysColor>
extern __imp_GetThemeSysColorBrush:PANYARGS
GetThemeSysColorBrush TEXTEQU <__imp_GetThemeSysColorBrush>
extern __imp_GetThemeSysFont:PANYARGS
GetThemeSysFont TEXTEQU <__imp_GetThemeSysFont>
extern __imp_GetThemeSysInt:PANYARGS
GetThemeSysInt TEXTEQU <__imp_GetThemeSysInt>
extern __imp_GetThemeSysSize:PANYARGS
GetThemeSysSize TEXTEQU <__imp_GetThemeSysSize>
extern __imp_GetThemeSysString:PANYARGS
GetThemeSysString TEXTEQU <__imp_GetThemeSysString>
extern __imp_GetThemeTextExtent:PANYARGS
GetThemeTextExtent TEXTEQU <__imp_GetThemeTextExtent>
extern __imp_GetThemeTextMetrics:PANYARGS
GetThemeTextMetrics TEXTEQU <__imp_GetThemeTextMetrics>
extern __imp_GetWindowTheme:PANYARGS
GetWindowTheme TEXTEQU <__imp_GetWindowTheme>
extern __imp_HitTestThemeBackground:PANYARGS
HitTestThemeBackground TEXTEQU <__imp_HitTestThemeBackground>
extern __imp_IsAppThemed:PANYARGS
IsAppThemed TEXTEQU <__imp_IsAppThemed>
extern __imp_IsThemeActive:PANYARGS
IsThemeActive TEXTEQU <__imp_IsThemeActive>
extern __imp_IsThemeBackgroundPartiallyTransparent:PANYARGS
IsThemeBackgroundPartiallyTransparent TEXTEQU <__imp_IsThemeBackgroundPartiallyTransparent>
extern __imp_IsThemeDialogTextureEnabled:PANYARGS
IsThemeDialogTextureEnabled TEXTEQU <__imp_IsThemeDialogTextureEnabled>
extern __imp_IsThemePartDefined:PANYARGS
IsThemePartDefined TEXTEQU <__imp_IsThemePartDefined>
extern __imp_OpenThemeData:PANYARGS
OpenThemeData TEXTEQU <__imp_OpenThemeData>
extern __imp_SetThemeAppProperties:PANYARGS
SetThemeAppProperties TEXTEQU <__imp_SetThemeAppProperties>
extern __imp_SetWindowTheme:PANYARGS
SetWindowTheme TEXTEQU <__imp_SetWindowTheme>
extern __imp_ThemeInitApiHook:PANYARGS
ThemeInitApiHook TEXTEQU <__imp_ThemeInitApiHook>
