extern __imp_??0CPrvEnumObject@@QEAA@XZ:PANYARGS
??0CPrvEnumObject@@QEAA@XZ TEXTEQU <__imp_??0CPrvEnumObject@@QEAA@XZ>
extern __imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z:PANYARGS
??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z TEXTEQU <__imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z>
extern __imp_??0CVdsPnPNotificationBase@@QEAA@XZ:PANYARGS
??0CVdsPnPNotificationBase@@QEAA@XZ TEXTEQU <__imp_??0CVdsPnPNotificationBase@@QEAA@XZ>
extern __imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ:PANYARGS
??0CVdsStructuredExceptionTranslator@@QEAA@XZ TEXTEQU <__imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ>
extern __imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z:PANYARGS
??0CVdsUnlockIt@@QEAA@AEAJ@Z TEXTEQU <__imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z>
extern __imp_??1CPrvEnumObject@@QEAA@XZ:PANYARGS
??1CPrvEnumObject@@QEAA@XZ TEXTEQU <__imp_??1CPrvEnumObject@@QEAA@XZ>
extern __imp_??1CVdsCriticalSection@@QEAA@XZ:PANYARGS
??1CVdsCriticalSection@@QEAA@XZ TEXTEQU <__imp_??1CVdsCriticalSection@@QEAA@XZ>
extern __imp_??1CVdsDebugLog@@QEAA@XZ:PANYARGS
??1CVdsDebugLog@@QEAA@XZ TEXTEQU <__imp_??1CVdsDebugLog@@QEAA@XZ>
extern __imp_??1CVdsPnPNotificationBase@@QEAA@XZ:PANYARGS
??1CVdsPnPNotificationBase@@QEAA@XZ TEXTEQU <__imp_??1CVdsPnPNotificationBase@@QEAA@XZ>
extern __imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ:PANYARGS
??1CVdsStructuredExceptionTranslator@@QEAA@XZ TEXTEQU <__imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ>
extern __imp_??1CVdsUnlockIt@@QEAA@XZ:PANYARGS
??1CVdsUnlockIt@@QEAA@XZ TEXTEQU <__imp_??1CVdsUnlockIt@@QEAA@XZ>
extern __imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PANYARGS
?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ TEXTEQU <__imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ>
extern __imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PANYARGS
?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ TEXTEQU <__imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ>
extern __imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ:PANYARGS
?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ TEXTEQU <__imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ>
extern __imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ:PANYARGS
?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ TEXTEQU <__imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ>
extern __imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z:PANYARGS
?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z TEXTEQU <__imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z>
extern __imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ:PANYARGS
?SetPositionToLast@CPrvEnumObject@@QEAAXXZ TEXTEQU <__imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ>
extern __imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ:PANYARGS
?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ TEXTEQU <__imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ>
extern __imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ:PANYARGS
?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ TEXTEQU <__imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
