extern __imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ:PANYARGS
??0CVdsStructuredExceptionTranslator@@QEAA@XZ TEXTEQU <__imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ>
extern __imp_??1CVdsDebugLog@@QEAA@XZ:PANYARGS
??1CVdsDebugLog@@QEAA@XZ TEXTEQU <__imp_??1CVdsDebugLog@@QEAA@XZ>
extern __imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ:PANYARGS
??1CVdsStructuredExceptionTranslator@@QEAA@XZ TEXTEQU <__imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ>
extern __imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ:PANYARGS
?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ TEXTEQU <__imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ>
