extern __imp_??0?$CVdsHandleImpl@$0?0@@QEAA@XZ:PANYARGS
??0?$CVdsHandleImpl@$0?0@@QEAA@XZ TEXTEQU <__imp_??0?$CVdsHandleImpl@$0?0@@QEAA@XZ>
extern __imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PANYARGS
??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ TEXTEQU <__imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>
extern __imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PANYARGS
??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ TEXTEQU <__imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>
extern __imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PANYARGS
??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ TEXTEQU <__imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>
extern __imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PANYARGS
??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ TEXTEQU <__imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>
extern __imp_??0CPrvEnumObject@@QEAA@XZ:PANYARGS
??0CPrvEnumObject@@QEAA@XZ TEXTEQU <__imp_??0CPrvEnumObject@@QEAA@XZ>
extern __imp_??0CVdsAsyncObjectBase@@QEAA@XZ:PANYARGS
??0CVdsAsyncObjectBase@@QEAA@XZ TEXTEQU <__imp_??0CVdsAsyncObjectBase@@QEAA@XZ>
extern __imp_??0CVdsCallTracer@@QEAA@KPEBD@Z:PANYARGS
??0CVdsCallTracer@@QEAA@KPEBD@Z TEXTEQU <__imp_??0CVdsCallTracer@@QEAA@KPEBD@Z>
extern __imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z:PANYARGS
??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z TEXTEQU <__imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z>
extern __imp_??0CVdsDebugLog@@QEAA@H@Z:PANYARGS
??0CVdsDebugLog@@QEAA@H@Z TEXTEQU <__imp_??0CVdsDebugLog@@QEAA@H@Z>
extern __imp_??0CVdsPnPNotificationBase@@QEAA@XZ:PANYARGS
??0CVdsPnPNotificationBase@@QEAA@XZ TEXTEQU <__imp_??0CVdsPnPNotificationBase@@QEAA@XZ>
extern __imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ:PANYARGS
??0CVdsStructuredExceptionTranslator@@QEAA@XZ TEXTEQU <__imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ>
extern __imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z:PANYARGS
??0CVdsUnlockIt@@QEAA@AEAJ@Z TEXTEQU <__imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z>
extern __imp_??0CVdsWmiVariantObjectArrayEnum@@QEAA@XZ:PANYARGS
??0CVdsWmiVariantObjectArrayEnum@@QEAA@XZ TEXTEQU <__imp_??0CVdsWmiVariantObjectArrayEnum@@QEAA@XZ>
extern __imp_??1?$CVdsHandleImpl@$0?0@@QEAA@XZ:PANYARGS
??1?$CVdsHandleImpl@$0?0@@QEAA@XZ TEXTEQU <__imp_??1?$CVdsHandleImpl@$0?0@@QEAA@XZ>
extern __imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PANYARGS
??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ TEXTEQU <__imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>
extern __imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PANYARGS
??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ TEXTEQU <__imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>
extern __imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PANYARGS
??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ TEXTEQU <__imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>
extern __imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PANYARGS
??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ TEXTEQU <__imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>
extern __imp_??1CPrvEnumObject@@QEAA@XZ:PANYARGS
??1CPrvEnumObject@@QEAA@XZ TEXTEQU <__imp_??1CPrvEnumObject@@QEAA@XZ>
extern __imp_??1CVdsAsyncObjectBase@@QEAA@XZ:PANYARGS
??1CVdsAsyncObjectBase@@QEAA@XZ TEXTEQU <__imp_??1CVdsAsyncObjectBase@@QEAA@XZ>
extern __imp_??1CVdsCallTracer@@QEAA@XZ:PANYARGS
??1CVdsCallTracer@@QEAA@XZ TEXTEQU <__imp_??1CVdsCallTracer@@QEAA@XZ>
extern __imp_??1CVdsCriticalSection@@QEAA@XZ:PANYARGS
??1CVdsCriticalSection@@QEAA@XZ TEXTEQU <__imp_??1CVdsCriticalSection@@QEAA@XZ>
extern __imp_??1CVdsDebugLog@@QEAA@XZ:PANYARGS
??1CVdsDebugLog@@QEAA@XZ TEXTEQU <__imp_??1CVdsDebugLog@@QEAA@XZ>
extern __imp_??1CVdsPnPNotificationBase@@QEAA@XZ:PANYARGS
??1CVdsPnPNotificationBase@@QEAA@XZ TEXTEQU <__imp_??1CVdsPnPNotificationBase@@QEAA@XZ>
extern __imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ:PANYARGS
??1CVdsStructuredExceptionTranslator@@QEAA@XZ TEXTEQU <__imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ>
extern __imp_??1CVdsUnlockIt@@QEAA@XZ:PANYARGS
??1CVdsUnlockIt@@QEAA@XZ TEXTEQU <__imp_??1CVdsUnlockIt@@QEAA@XZ>
extern __imp_??1CVdsWmiVariantObjectArrayEnum@@QEAA@XZ:PANYARGS
??1CVdsWmiVariantObjectArrayEnum@@QEAA@XZ TEXTEQU <__imp_??1CVdsWmiVariantObjectArrayEnum@@QEAA@XZ>
extern __imp_??4?$CVdsHandleImpl@$0?0@@QEAAPEAXPEAX@Z:PANYARGS
??4?$CVdsHandleImpl@$0?0@@QEAAPEAXPEAX@Z TEXTEQU <__imp_??4?$CVdsHandleImpl@$0?0@@QEAAPEAXPEAX@Z>
extern __imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINT@@PEAU1@@Z:PANYARGS
??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINT@@PEAU1@@Z TEXTEQU <__imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINT@@PEAU1@@Z>
extern __imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINTS@@PEAU1@@Z:PANYARGS
??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINTS@@PEAU1@@Z TEXTEQU <__imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINTS@@PEAU1@@Z>
extern __imp_??8?$CVdsHandleImpl@$0?0@@QEBA_NPEAX@Z:PANYARGS
??8?$CVdsHandleImpl@$0?0@@QEBA_NPEAX@Z TEXTEQU <__imp_??8?$CVdsHandleImpl@$0?0@@QEBA_NPEAX@Z>
extern __imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINT@@@Z:PANYARGS
??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINT@@@Z TEXTEQU <__imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINT@@@Z>
extern __imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINTS@@@Z:PANYARGS
??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINTS@@@Z TEXTEQU <__imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINTS@@@Z>
extern __imp_??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ:PANYARGS
??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ TEXTEQU <__imp_??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ>
extern __imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ:PANYARGS
??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ TEXTEQU <__imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ>
extern __imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ:PANYARGS
??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ TEXTEQU <__imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ>
extern __imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ:PANYARGS
??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ TEXTEQU <__imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ>
extern __imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ:PANYARGS
??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ TEXTEQU <__imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ>
extern __imp_??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ:PANYARGS
??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ TEXTEQU <__imp_??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ>
extern __imp_??M@YA_NAEBU_GUID@@0@Z:PANYARGS
??M@YA_NAEBU_GUID@@0@Z TEXTEQU <__imp_??M@YA_NAEBU_GUID@@0@Z>
extern __imp_?AddEventSource@@YAKPEAGPEAUHINSTANCE__@@@Z:PANYARGS
?AddEventSource@@YAKPEAGPEAUHINSTANCE__@@@Z TEXTEQU <__imp_?AddEventSource@@YAKPEAGPEAUHINSTANCE__@@@Z>
extern __imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PANYARGS
?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ TEXTEQU <__imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ>
extern __imp_?Append@CPrvEnumObject@@QEAAJPEAUIUnknown@@@Z:PANYARGS
?Append@CPrvEnumObject@@QEAAJPEAUIUnknown@@@Z TEXTEQU <__imp_?Append@CPrvEnumObject@@QEAAJPEAUIUnknown@@@Z>
extern __imp_?AssignTempVolumeName@@YAJPEAGQEAG@Z:PANYARGS
?AssignTempVolumeName@@YAJPEAGQEAG@Z TEXTEQU <__imp_?AssignTempVolumeName@@YAJPEAGQEAG@Z>
extern __imp_?Attach@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAUtagVARIANT@@@Z:PANYARGS
?Attach@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAUtagVARIANT@@@Z TEXTEQU <__imp_?Attach@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAUtagVARIANT@@@Z>
extern __imp_?Cancel@CVdsAsyncObjectBase@@UEAAJXZ:PANYARGS
?Cancel@CVdsAsyncObjectBase@@UEAAJXZ TEXTEQU <__imp_?Cancel@CVdsAsyncObjectBase@@UEAAJXZ>
extern __imp_?Clear@CPrvEnumObject@@QEAAXXZ:PANYARGS
?Clear@CPrvEnumObject@@QEAAXXZ TEXTEQU <__imp_?Clear@CPrvEnumObject@@QEAAXXZ>
extern __imp_?Clone@CPrvEnumObject@@UEAAJPEAPEAUIEnumVdsObject@@@Z:PANYARGS
?Clone@CPrvEnumObject@@UEAAJPEAPEAUIEnumVdsObject@@@Z TEXTEQU <__imp_?Clone@CPrvEnumObject@@UEAAJPEAPEAUIEnumVdsObject@@@Z>
extern __imp_?CoFreeStringArray@@YAXPEAPEAGJ@Z:PANYARGS
?CoFreeStringArray@@YAXPEAPEAGJ@Z TEXTEQU <__imp_?CoFreeStringArray@@YAXPEAPEAGJ@Z>
extern __imp_?CreateDeviceInfoSet@@YAKPEAGPEAPEAXPEAU_SP_DEVINFO_DATA@@@Z:PANYARGS
?CreateDeviceInfoSet@@YAKPEAGPEAPEAXPEAU_SP_DEVINFO_DATA@@@Z TEXTEQU <__imp_?CreateDeviceInfoSet@@YAKPEAGPEAPEAXPEAU_SP_DEVINFO_DATA@@@Z>
extern __imp_?CreateListenThread@CVdsPnPNotificationBase@@AEAAKXZ:PANYARGS
?CreateListenThread@CVdsPnPNotificationBase@@AEAAKXZ TEXTEQU <__imp_?CreateListenThread@CVdsPnPNotificationBase@@AEAAKXZ>
extern __imp_?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ:PANYARGS
?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ TEXTEQU <__imp_?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ>
extern __imp_?Detach@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ:PANYARGS
?Detach@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ TEXTEQU <__imp_?Detach@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ>
extern __imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PANYARGS
?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ TEXTEQU <__imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ>
extern __imp_?GarbageCollectDriveLetters@@YAXXZ:PANYARGS
?GarbageCollectDriveLetters@@YAXXZ TEXTEQU <__imp_?GarbageCollectDriveLetters@@YAXXZ>
extern __imp_?GetDeviceAndMediaType@@YAKPEAXPEAK1@Z:PANYARGS
?GetDeviceAndMediaType@@YAKPEAXPEAK1@Z TEXTEQU <__imp_?GetDeviceAndMediaType@@YAKPEAXPEAK1@Z>
extern __imp_?GetDeviceLocation@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z:PANYARGS
?GetDeviceLocation@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z TEXTEQU <__imp_?GetDeviceLocation@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z>
extern __imp_?GetDeviceName@@YAKPEAXHQEAG@Z:PANYARGS
?GetDeviceName@@YAKPEAXHQEAG@Z TEXTEQU <__imp_?GetDeviceName@@YAKPEAXHQEAG@Z>
extern __imp_?GetDeviceNumber@@YAKPEAXPEAU_STORAGE_DEVICE_NUMBER@@@Z:PANYARGS
?GetDeviceNumber@@YAKPEAXPEAU_STORAGE_DEVICE_NUMBER@@@Z TEXTEQU <__imp_?GetDeviceNumber@@YAKPEAXPEAU_STORAGE_DEVICE_NUMBER@@@Z>
extern __imp_?GetDeviceRegistryProperty@@YAKKKPEAPEAEK@Z:PANYARGS
?GetDeviceRegistryProperty@@YAKKKPEAPEAEK@Z TEXTEQU <__imp_?GetDeviceRegistryProperty@@YAKKKPEAPEAEK@Z>
extern __imp_?GetDeviceRegistryProperty@@YAKPEAXPEAU_SP_DEVINFO_DATA@@KPEAPEAEK@Z:PANYARGS
?GetDeviceRegistryProperty@@YAKPEAXPEAU_SP_DEVINFO_DATA@@KPEAPEAEK@Z TEXTEQU <__imp_?GetDeviceRegistryProperty@@YAKPEAXPEAU_SP_DEVINFO_DATA@@KPEAPEAEK@Z>
extern __imp_?GetDiskLayout@@YAKPEAXPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z:PANYARGS
?GetDiskLayout@@YAKPEAXPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z TEXTEQU <__imp_?GetDiskLayout@@YAKPEAXPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z>
extern __imp_?GetInterfaceDetailData@@YAKPEAXPEAU_SP_DEVICE_INTERFACE_DATA@@PEAPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z:PANYARGS
?GetInterfaceDetailData@@YAKPEAXPEAU_SP_DEVICE_INTERFACE_DATA@@PEAPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z TEXTEQU <__imp_?GetInterfaceDetailData@@YAKPEAXPEAU_SP_DEVICE_INTERFACE_DATA@@PEAPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z>
extern __imp_?GetIsRemovable@@YAKPEAXPEAH@Z:PANYARGS
?GetIsRemovable@@YAKPEAXPEAH@Z TEXTEQU <__imp_?GetIsRemovable@@YAKPEAXPEAH@Z>
extern __imp_?GetMediaGeometry@@YAKPEAXKPEAU_DISK_GEOMETRY@@@Z:PANYARGS
?GetMediaGeometry@@YAKPEAXKPEAU_DISK_GEOMETRY@@@Z TEXTEQU <__imp_?GetMediaGeometry@@YAKPEAXKPEAU_DISK_GEOMETRY@@@Z>
extern __imp_?GetMediaGeometry@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z:PANYARGS
?GetMediaGeometry@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z TEXTEQU <__imp_?GetMediaGeometry@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z>
extern __imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@XZ:PANYARGS
?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@XZ TEXTEQU <__imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@XZ>
extern __imp_?GetPartitionInformation@@YAKPEAXPEAU_PARTITION_INFORMATION_EX@@@Z:PANYARGS
?GetPartitionInformation@@YAKPEAXPEAU_PARTITION_INFORMATION_EX@@@Z TEXTEQU <__imp_?GetPartitionInformation@@YAKPEAXPEAU_PARTITION_INFORMATION_EX@@@Z>
extern __imp_?GetVolumeDiskExtentInfo@@YAKPEAXPEAPEAU_VOLUME_DISK_EXTENTS@@@Z:PANYARGS
?GetVolumeDiskExtentInfo@@YAKPEAXPEAPEAU_VOLUME_DISK_EXTENTS@@@Z TEXTEQU <__imp_?GetVolumeDiskExtentInfo@@YAKPEAXPEAPEAU_VOLUME_DISK_EXTENTS@@@Z>
extern __imp_?GetVolumeName@@YAJPEAG0@Z:PANYARGS
?GetVolumeName@@YAJPEAG0@Z TEXTEQU <__imp_?GetVolumeName@@YAJPEAG0@Z>
extern __imp_?GetVolumeSize@@YAKPEAGPEA_K@Z:PANYARGS
?GetVolumeSize@@YAKPEAGPEA_K@Z TEXTEQU <__imp_?GetVolumeSize@@YAKPEAGPEA_K@Z>
extern __imp_?GetWindowHandle@CVdsPnPNotificationBase@@QEAAPEAUHWND__@@XZ:PANYARGS
?GetWindowHandle@CVdsPnPNotificationBase@@QEAAPEAUHWND__@@XZ TEXTEQU <__imp_?GetWindowHandle@CVdsPnPNotificationBase@@QEAAPEAUHWND__@@XZ>
extern __imp_?HasMatchingNotification@CVdsPnPNotificationBase@@IEAAH_KK@Z:PANYARGS
?HasMatchingNotification@CVdsPnPNotificationBase@@IEAAH_KK@Z TEXTEQU <__imp_?HasMatchingNotification@CVdsPnPNotificationBase@@IEAAH_KK@Z>
extern __imp_?Initialize@CVdsAsyncObjectBase@@SAKXZ:PANYARGS
?Initialize@CVdsAsyncObjectBase@@SAKXZ TEXTEQU <__imp_?Initialize@CVdsAsyncObjectBase@@SAKXZ>
extern __imp_?Initialize@CVdsPnPNotificationBase@@QEAAKXZ:PANYARGS
?Initialize@CVdsPnPNotificationBase@@QEAAKXZ TEXTEQU <__imp_?Initialize@CVdsPnPNotificationBase@@QEAAKXZ>
extern __imp_?InitializeSecurityDescriptor@@YAKKPEAXPEAPEAU_ACL@@PEAPEAX22@Z:PANYARGS
?InitializeSecurityDescriptor@@YAKKPEAXPEAPEAU_ACL@@PEAPEAX22@Z TEXTEQU <__imp_?InitializeSecurityDescriptor@@YAKKPEAXPEAPEAU_ACL@@PEAPEAX22@Z>
extern __imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ:PANYARGS
?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ TEXTEQU <__imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ>
extern __imp_?IsDeviceFullyInstalled@@YAHPEAG@Z:PANYARGS
?IsDeviceFullyInstalled@@YAHPEAG@Z TEXTEQU <__imp_?IsDeviceFullyInstalled@@YAHPEAG@Z>
extern __imp_?IsDiskClustered@@YAHPEAX@Z:PANYARGS
?IsDiskClustered@@YAHPEAX@Z TEXTEQU <__imp_?IsDiskClustered@@YAHPEAX@Z>
extern __imp_?IsFinished@CVdsAsyncObjectBase@@QEAAHXZ:PANYARGS
?IsFinished@CVdsAsyncObjectBase@@QEAAHXZ TEXTEQU <__imp_?IsFinished@CVdsAsyncObjectBase@@QEAAHXZ>
extern __imp_?IsLocalComputer@@YAJPEAG@Z:PANYARGS
?IsLocalComputer@@YAJPEAG@Z TEXTEQU <__imp_?IsLocalComputer@@YAJPEAG@Z>
extern __imp_?IsMediaPresent@@YAHPEAX@Z:PANYARGS
?IsMediaPresent@@YAHPEAX@Z TEXTEQU <__imp_?IsMediaPresent@@YAHPEAX@Z>
extern __imp_?IsNoAutoMount@@YAHXZ:PANYARGS
?IsNoAutoMount@@YAHXZ TEXTEQU <__imp_?IsNoAutoMount@@YAHXZ>
extern __imp_?IsWinPE@@YAHXZ:PANYARGS
?IsWinPE@@YAHXZ TEXTEQU <__imp_?IsWinPE@@YAHXZ>
extern __imp_?LockDismountVolume@@YAKPEAXH@Z:PANYARGS
?LockDismountVolume@@YAKPEAXH@Z TEXTEQU <__imp_?LockDismountVolume@@YAKPEAXH@Z>
extern __imp_?LockVolume@@YAKPEAX@Z:PANYARGS
?LockVolume@@YAKPEAX@Z TEXTEQU <__imp_?LockVolume@@YAKPEAX@Z>
extern __imp_?Log@CVdsDebugLog@@QEAAXKKHPEAD0@Z:PANYARGS
?Log@CVdsDebugLog@@QEAAXKKHPEAD0@Z TEXTEQU <__imp_?Log@CVdsDebugLog@@QEAAXKKHPEAD0@Z>
extern __imp_?Log@CVdsDebugLog@@QEAAXKKHPEADZZ:PANYARGS
?Log@CVdsDebugLog@@QEAAXKKHPEADZZ TEXTEQU <__imp_?Log@CVdsDebugLog@@QEAAXKKHPEADZZ>
extern __imp_?LogError@@YAXPEAGKKPEAXKK0PEAD@Z:PANYARGS
?LogError@@YAXPEAGKKPEAXKK0PEAD@Z TEXTEQU <__imp_?LogError@@YAXPEAGKKPEAXKK0PEAD@Z>
extern __imp_?LogEvent@@YAXPEAGKGKPEAXKQEAPEAG@Z:PANYARGS
?LogEvent@@YAXPEAGKGKPEAXKQEAPEAG@Z TEXTEQU <__imp_?LogEvent@@YAXPEAGKGKPEAXKQEAPEAG@Z>
extern __imp_?LogInfo@@YAXPEAGKKPEAXK0PEAD@Z:PANYARGS
?LogInfo@@YAXPEAGKKPEAXK0PEAD@Z TEXTEQU <__imp_?LogInfo@@YAXPEAGKKPEAXK0PEAD@Z>
extern __imp_?LogWarning@@YAXPEAGKKPEAXKK0PEAD@Z:PANYARGS
?LogWarning@@YAXPEAGKKPEAXKK0PEAD@Z TEXTEQU <__imp_?LogWarning@@YAXPEAGKKPEAXKK0PEAD@Z>
extern __imp_?MountVolume@@YAKPEAG@Z:PANYARGS
?MountVolume@@YAKPEAG@Z TEXTEQU <__imp_?MountVolume@@YAKPEAG@Z>
extern __imp_?Next@CPrvEnumObject@@UEAAJKPEAPEAUIUnknown@@PEAK@Z:PANYARGS
?Next@CPrvEnumObject@@UEAAJKPEAPEAUIUnknown@@PEAK@Z TEXTEQU <__imp_?Next@CPrvEnumObject@@UEAAJKPEAPEAUIUnknown@@PEAK@Z>
extern __imp_?Next@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAPEAUIWbemClassObject@@@Z:PANYARGS
?Next@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAPEAUIWbemClassObject@@@Z TEXTEQU <__imp_?Next@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAPEAUIWbemClassObject@@@Z>
extern __imp_?NotificationThread@CVdsPnPNotificationBase@@AEAAKPEAX@Z:PANYARGS
?NotificationThread@CVdsPnPNotificationBase@@AEAAKPEAX@Z TEXTEQU <__imp_?NotificationThread@CVdsPnPNotificationBase@@AEAAKPEAX@Z>
extern __imp_?NotificationThreadEntry@CVdsPnPNotificationBase@@CAKPEAX@Z:PANYARGS
?NotificationThreadEntry@CVdsPnPNotificationBase@@CAKPEAX@Z TEXTEQU <__imp_?NotificationThreadEntry@CVdsPnPNotificationBase@@CAKPEAX@Z>
extern __imp_?OpenDevice@@YAKPEAGKPEAPEAX@Z:PANYARGS
?OpenDevice@@YAKPEAGKPEAPEAX@Z TEXTEQU <__imp_?OpenDevice@@YAKPEAGKPEAPEAX@Z>
extern __imp_?QueryObjects@@YAJPEAUIUnknown@@PEAPEAUIEnumVdsObject@@AEAU_RTL_CRITICAL_SECTION@@@Z:PANYARGS
?QueryObjects@@YAJPEAUIUnknown@@PEAPEAUIEnumVdsObject@@AEAU_RTL_CRITICAL_SECTION@@@Z TEXTEQU <__imp_?QueryObjects@@YAJPEAUIUnknown@@PEAPEAUIEnumVdsObject@@AEAU_RTL_CRITICAL_SECTION@@@Z>
extern __imp_?QueryStatus@CVdsAsyncObjectBase@@UEAAJPEAJPEAK@Z:PANYARGS
?QueryStatus@CVdsAsyncObjectBase@@UEAAJPEAJPEAK@Z TEXTEQU <__imp_?QueryStatus@CVdsAsyncObjectBase@@UEAAJPEAJPEAK@Z>
extern __imp_?Register@CVdsPnPNotificationBase@@QEAAKPEAU_NotificationListeningRequest@@K@Z:PANYARGS
?Register@CVdsPnPNotificationBase@@QEAAKPEAU_NotificationListeningRequest@@K@Z TEXTEQU <__imp_?Register@CVdsPnPNotificationBase@@QEAAKPEAU_NotificationListeningRequest@@K@Z>
extern __imp_?RegisterHandle@CVdsPnPNotificationBase@@QEAAKPEAXPEAPEAX@Z:PANYARGS
?RegisterHandle@CVdsPnPNotificationBase@@QEAAKPEAXPEAPEAX@Z TEXTEQU <__imp_?RegisterHandle@CVdsPnPNotificationBase@@QEAAKPEAXPEAPEAX@Z>
extern __imp_?RegisterProvider@@YAJU_GUID@@0PEAGW4_VDS_PROVIDER_TYPE@@110@Z:PANYARGS
?RegisterProvider@@YAJU_GUID@@0PEAGW4_VDS_PROVIDER_TYPE@@110@Z TEXTEQU <__imp_?RegisterProvider@@YAJU_GUID@@0PEAGW4_VDS_PROVIDER_TYPE@@110@Z>
extern __imp_?RemoveEventSource@@YAKPEAG@Z:PANYARGS
?RemoveEventSource@@YAKPEAG@Z TEXTEQU <__imp_?RemoveEventSource@@YAKPEAG@Z>
extern __imp_?RemoveTempVolumeName@@YAXPEAG0@Z:PANYARGS
?RemoveTempVolumeName@@YAXPEAG0@Z TEXTEQU <__imp_?RemoveTempVolumeName@@YAXPEAG0@Z>
extern __imp_?Reset@CPrvEnumObject@@UEAAJXZ:PANYARGS
?Reset@CPrvEnumObject@@UEAAJXZ TEXTEQU <__imp_?Reset@CPrvEnumObject@@UEAAJXZ>
extern __imp_?Reset@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ:PANYARGS
?Reset@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ TEXTEQU <__imp_?Reset@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ>
extern __imp_?SetCompletionStatus@CVdsAsyncObjectBase@@QEAAXJK@Z:PANYARGS
?SetCompletionStatus@CVdsAsyncObjectBase@@QEAAXJK@Z TEXTEQU <__imp_?SetCompletionStatus@CVdsAsyncObjectBase@@QEAAXJK@Z>
extern __imp_?SetDiskLayout@@YAKPEAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z:PANYARGS
?SetDiskLayout@@YAKPEAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z TEXTEQU <__imp_?SetDiskLayout@@YAKPEAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z>
extern __imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@@Z:PANYARGS
?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@@Z TEXTEQU <__imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@@Z>
extern __imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ:PANYARGS
?SetPositionToLast@CPrvEnumObject@@QEAAXXZ TEXTEQU <__imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ>
extern __imp_?Signal@CVdsAsyncObjectBase@@QEAAXXZ:PANYARGS
?Signal@CVdsAsyncObjectBase@@QEAAXXZ TEXTEQU <__imp_?Signal@CVdsAsyncObjectBase@@QEAAXXZ>
extern __imp_?Skip@CPrvEnumObject@@UEAAJK@Z:PANYARGS
?Skip@CPrvEnumObject@@UEAAJK@Z TEXTEQU <__imp_?Skip@CPrvEnumObject@@UEAAJK@Z>
extern __imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ:PANYARGS
?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ TEXTEQU <__imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ>
extern __imp_?Uninitialize@CVdsAsyncObjectBase@@SAXXZ:PANYARGS
?Uninitialize@CVdsAsyncObjectBase@@SAXXZ TEXTEQU <__imp_?Uninitialize@CVdsAsyncObjectBase@@SAXXZ>
extern __imp_?Uninitialize@CVdsPnPNotificationBase@@QEAAXXZ:PANYARGS
?Uninitialize@CVdsPnPNotificationBase@@QEAAXXZ TEXTEQU <__imp_?Uninitialize@CVdsPnPNotificationBase@@QEAAXXZ>
extern __imp_?Unregister@CVdsPnPNotificationBase@@QEAAXPEAU_NotificationListeningRequest@@@Z:PANYARGS
?Unregister@CVdsPnPNotificationBase@@QEAAXPEAU_NotificationListeningRequest@@@Z TEXTEQU <__imp_?Unregister@CVdsPnPNotificationBase@@QEAAXPEAU_NotificationListeningRequest@@@Z>
extern __imp_?UnregisterHandle@CVdsPnPNotificationBase@@QEAAXPEAX@Z:PANYARGS
?UnregisterHandle@CVdsPnPNotificationBase@@QEAAXPEAX@Z TEXTEQU <__imp_?UnregisterHandle@CVdsPnPNotificationBase@@QEAAXPEAX@Z>
extern __imp_?UnregisterProvider@@YAJU_GUID@@@Z:PANYARGS
?UnregisterProvider@@YAJU_GUID@@@Z TEXTEQU <__imp_?UnregisterProvider@@YAJU_GUID@@@Z>
extern __imp_?VdsAllocateEmptyString@@YAPEAGXZ:PANYARGS
?VdsAllocateEmptyString@@YAPEAGXZ TEXTEQU <__imp_?VdsAllocateEmptyString@@YAPEAGXZ>
extern __imp_?VdsHeapAlloc@@YAPEAXPEAXK_K@Z:PANYARGS
?VdsHeapAlloc@@YAPEAXPEAXK_K@Z TEXTEQU <__imp_?VdsHeapAlloc@@YAPEAXPEAXK_K@Z>
extern __imp_?VdsHeapFree@@YAHPEAXK0@Z:PANYARGS
?VdsHeapFree@@YAHPEAXK0@Z TEXTEQU <__imp_?VdsHeapFree@@YAHPEAXK0@Z>
extern __imp_?VdsInitializeCriticalSection@@YAKPEAU_RTL_CRITICAL_SECTION@@@Z:PANYARGS
?VdsInitializeCriticalSection@@YAKPEAU_RTL_CRITICAL_SECTION@@@Z TEXTEQU <__imp_?VdsInitializeCriticalSection@@YAKPEAU_RTL_CRITICAL_SECTION@@@Z>
extern __imp_?VdsIscsiCacheSessionDevices@@YAJPEAUIEnumWbemClassObject@@PEAPEAU_VDSISCSI_SESSION_DEVICES_CACHE@@@Z:PANYARGS
?VdsIscsiCacheSessionDevices@@YAJPEAUIEnumWbemClassObject@@PEAPEAU_VDSISCSI_SESSION_DEVICES_CACHE@@@Z TEXTEQU <__imp_?VdsIscsiCacheSessionDevices@@YAJPEAUIEnumWbemClassObject@@PEAPEAU_VDSISCSI_SESSION_DEVICES_CACHE@@@Z>
extern __imp_?VdsIscsiCheckEqualIpAddress@@YAHU_VDS_IPADDRESS@@0@Z:PANYARGS
?VdsIscsiCheckEqualIpAddress@@YAHU_VDS_IPADDRESS@@0@Z TEXTEQU <__imp_?VdsIscsiCheckEqualIpAddress@@YAHU_VDS_IPADDRESS@@0@Z>
extern __imp_?VdsIscsiGetIpAddressFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z:PANYARGS
?VdsIscsiGetIpAddressFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z TEXTEQU <__imp_?VdsIscsiGetIpAddressFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z>
extern __imp_?VdsIscsiIpAddressToIpsecId@@YAJPEAU_VDS_IPADDRESS@@PEAEPEAKPEAPEAE@Z:PANYARGS
?VdsIscsiIpAddressToIpsecId@@YAJPEAU_VDS_IPADDRESS@@PEAEPEAKPEAPEAE@Z TEXTEQU <__imp_?VdsIscsiIpAddressToIpsecId@@YAJPEAU_VDS_IPADDRESS@@PEAEPEAKPEAPEAE@Z>
extern __imp_?VdsIscsiIpAddressToString@@YAJPEAU_VDS_IPADDRESS@@KPEAG@Z:PANYARGS
?VdsIscsiIpAddressToString@@YAJPEAU_VDS_IPADDRESS@@KPEAG@Z TEXTEQU <__imp_?VdsIscsiIpAddressToString@@YAJPEAU_VDS_IPADDRESS@@KPEAG@Z>
extern __imp_?VdsIscsiIpsecIdToIpAddress@@YAJEKPEAEPEAU_VDS_IPADDRESS@@@Z:PANYARGS
?VdsIscsiIpsecIdToIpAddress@@YAJEKPEAEPEAU_VDS_IPADDRESS@@@Z TEXTEQU <__imp_?VdsIscsiIpsecIdToIpAddress@@YAJEKPEAEPEAU_VDS_IPADDRESS@@@Z>
extern __imp_?VdsIscsiIsIscsiLun@@YAJPEAUIWbemClassObject@@PEAU_VDSISCSI_SESSION_DEVICES_CACHE@@PEAH@Z:PANYARGS
?VdsIscsiIsIscsiLun@@YAJPEAUIWbemClassObject@@PEAU_VDSISCSI_SESSION_DEVICES_CACHE@@PEAH@Z TEXTEQU <__imp_?VdsIscsiIsIscsiLun@@YAJPEAUIWbemClassObject@@PEAU_VDSISCSI_SESSION_DEVICES_CACHE@@PEAH@Z>
extern __imp_?VdsIscsiSetIpAddressInInstance@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z:PANYARGS
?VdsIscsiSetIpAddressInInstance@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z TEXTEQU <__imp_?VdsIscsiSetIpAddressInInstance@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z>
extern __imp_?VdsSeTranslator@CVdsStructuredExceptionTranslator@@SAXIPEAU_EXCEPTION_POINTERS@@@Z:PANYARGS
?VdsSeTranslator@CVdsStructuredExceptionTranslator@@SAXIPEAU_EXCEPTION_POINTERS@@@Z TEXTEQU <__imp_?VdsSeTranslator@CVdsStructuredExceptionTranslator@@SAXIPEAU_EXCEPTION_POINTERS@@@Z>
extern __imp_?VdsTrace@@YAXKPEADZZ:PANYARGS
?VdsTrace@@YAXKPEADZZ TEXTEQU <__imp_?VdsTrace@@YAXKPEADZZ>
extern __imp_?VdsTraceEx@@YAXKKPEADZZ:PANYARGS
?VdsTraceEx@@YAXKKPEADZZ TEXTEQU <__imp_?VdsTraceEx@@YAXKKPEADZZ>
extern __imp_?VdsTraceExHelper@@YAXKKPEAD0@Z:PANYARGS
?VdsTraceExHelper@@YAXKKPEAD0@Z TEXTEQU <__imp_?VdsTraceExHelper@@YAXKKPEAD0@Z>
extern __imp_?VdsTraceExW@@YAXKKPEAGZZ:PANYARGS
?VdsTraceExW@@YAXKKPEAGZZ TEXTEQU <__imp_?VdsTraceExW@@YAXKKPEAGZZ>
extern __imp_?VdsTraceExWHelper@@YAXKKPEAGPEAD@Z:PANYARGS
?VdsTraceExWHelper@@YAXKKPEAGPEAD@Z TEXTEQU <__imp_?VdsTraceExWHelper@@YAXKKPEAGPEAD@Z>
extern __imp_?VdsTraceW@@YAXKPEAGZZ:PANYARGS
?VdsTraceW@@YAXKPEAGZZ TEXTEQU <__imp_?VdsTraceW@@YAXKPEAGZZ>
extern __imp_?VdsWmiCallMethod@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAG1PEAPEAU2@@Z:PANYARGS
?VdsWmiCallMethod@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAG1PEAPEAU2@@Z TEXTEQU <__imp_?VdsWmiCallMethod@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAG1PEAPEAU2@@Z>
extern __imp_?VdsWmiConnectToNamespace@@YAJPEAGPEAPEAUIWbemLocator@@PEAPEAUIWbemServices@@@Z:PANYARGS
?VdsWmiConnectToNamespace@@YAJPEAGPEAPEAUIWbemLocator@@PEAPEAUIWbemServices@@@Z TEXTEQU <__imp_?VdsWmiConnectToNamespace@@YAJPEAGPEAPEAUIWbemLocator@@PEAPEAUIWbemServices@@@Z>
extern __imp_?VdsWmiCopyFromVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z:PANYARGS
?VdsWmiCopyFromVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z TEXTEQU <__imp_?VdsWmiCopyFromVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z>
extern __imp_?VdsWmiCopyToVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z:PANYARGS
?VdsWmiCopyToVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z TEXTEQU <__imp_?VdsWmiCopyToVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z>
extern __imp_?VdsWmiCreateClassInstance@@YAJPEAUIWbemServices@@PEAGPEAPEAUIWbemClassObject@@@Z:PANYARGS
?VdsWmiCreateClassInstance@@YAJPEAUIWbemServices@@PEAGPEAPEAUIWbemClassObject@@@Z TEXTEQU <__imp_?VdsWmiCreateClassInstance@@YAJPEAUIWbemServices@@PEAGPEAPEAUIWbemClassObject@@@Z>
extern __imp_?VdsWmiCreateVariantArray@@YAJGJPEAUtagVARIANT@@@Z:PANYARGS
?VdsWmiCreateVariantArray@@YAJGJPEAUtagVARIANT@@@Z TEXTEQU <__imp_?VdsWmiCreateVariantArray@@YAJGJPEAUtagVARIANT@@@Z>
extern __imp_?VdsWmiFindInstanceOfClass@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z:PANYARGS
?VdsWmiFindInstanceOfClass@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z TEXTEQU <__imp_?VdsWmiFindInstanceOfClass@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z>
extern __imp_?VdsWmiGetBoolFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAH@Z:PANYARGS
?VdsWmiGetBoolFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAH@Z TEXTEQU <__imp_?VdsWmiGetBoolFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAH@Z>
extern __imp_?VdsWmiGetByteFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAE@Z:PANYARGS
?VdsWmiGetByteFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAE@Z TEXTEQU <__imp_?VdsWmiGetByteFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAE@Z>
extern __imp_?VdsWmiGetByteInVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z:PANYARGS
?VdsWmiGetByteInVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z TEXTEQU <__imp_?VdsWmiGetByteInVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z>
extern __imp_?VdsWmiGetMethodArgumentObject@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z:PANYARGS
?VdsWmiGetMethodArgumentObject@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z TEXTEQU <__imp_?VdsWmiGetMethodArgumentObject@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z>
extern __imp_?VdsWmiGetObjectFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAPEAU1@@Z:PANYARGS
?VdsWmiGetObjectFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAPEAU1@@Z TEXTEQU <__imp_?VdsWmiGetObjectFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAPEAU1@@Z>
extern __imp_?VdsWmiGetObjectInVariantObjectArray@@YAJPEAUIWbemClassObject@@PEAGJPEAPEAU1@@Z:PANYARGS
?VdsWmiGetObjectInVariantObjectArray@@YAJPEAUIWbemClassObject@@PEAGJPEAPEAU1@@Z TEXTEQU <__imp_?VdsWmiGetObjectInVariantObjectArray@@YAJPEAUIWbemClassObject@@PEAGJPEAPEAU1@@Z>
extern __imp_?VdsWmiGetUlongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAK@Z:PANYARGS
?VdsWmiGetUlongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAK@Z TEXTEQU <__imp_?VdsWmiGetUlongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAK@Z>
extern __imp_?VdsWmiGetUlonglongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEA_K@Z:PANYARGS
?VdsWmiGetUlonglongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEA_K@Z TEXTEQU <__imp_?VdsWmiGetUlonglongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEA_K@Z>
extern __imp_?VdsWmiSetBoolInInstance@@YAJPEAUIWbemClassObject@@PEAGH@Z:PANYARGS
?VdsWmiSetBoolInInstance@@YAJPEAUIWbemClassObject@@PEAGH@Z TEXTEQU <__imp_?VdsWmiSetBoolInInstance@@YAJPEAUIWbemClassObject@@PEAGH@Z>
extern __imp_?VdsWmiSetByteInInstance@@YAJPEAUIWbemClassObject@@PEAGE@Z:PANYARGS
?VdsWmiSetByteInInstance@@YAJPEAUIWbemClassObject@@PEAGE@Z TEXTEQU <__imp_?VdsWmiSetByteInInstance@@YAJPEAUIWbemClassObject@@PEAGE@Z>
extern __imp_?VdsWmiSetObjectInInstance@@YAJPEAUIWbemClassObject@@PEAG0@Z:PANYARGS
?VdsWmiSetObjectInInstance@@YAJPEAUIWbemClassObject@@PEAG0@Z TEXTEQU <__imp_?VdsWmiSetObjectInInstance@@YAJPEAUIWbemClassObject@@PEAG0@Z>
extern __imp_?VdsWmiSetStringInInstance@@YAJPEAUIWbemClassObject@@PEAG1@Z:PANYARGS
?VdsWmiSetStringInInstance@@YAJPEAUIWbemClassObject@@PEAG1@Z TEXTEQU <__imp_?VdsWmiSetStringInInstance@@YAJPEAUIWbemClassObject@@PEAG1@Z>
extern __imp_?VdsWmiSetUlongInInstance@@YAJPEAUIWbemClassObject@@PEAGK@Z:PANYARGS
?VdsWmiSetUlongInInstance@@YAJPEAUIWbemClassObject@@PEAGK@Z TEXTEQU <__imp_?VdsWmiSetUlongInInstance@@YAJPEAUIWbemClassObject@@PEAGK@Z>
extern __imp_?VdsWmiSetUlonglongInInstance@@YAJPEAUIWbemClassObject@@PEAG_K@Z:PANYARGS
?VdsWmiSetUlonglongInInstance@@YAJPEAUIWbemClassObject@@PEAG_K@Z TEXTEQU <__imp_?VdsWmiSetUlonglongInInstance@@YAJPEAUIWbemClassObject@@PEAG_K@Z>
extern __imp_?WaitImpl@CVdsAsyncObjectBase@@QEAAJPEAJ@Z:PANYARGS
?WaitImpl@CVdsAsyncObjectBase@@QEAAJPEAJ@Z TEXTEQU <__imp_?WaitImpl@CVdsAsyncObjectBase@@QEAAJPEAJ@Z>
extern __imp_?WindowProcEntry@CVdsPnPNotificationBase@@CA_JPEAUHWND__@@I_K_J@Z:PANYARGS
?WindowProcEntry@CVdsPnPNotificationBase@@CA_JPEAUHWND__@@I_K_J@Z TEXTEQU <__imp_?WindowProcEntry@CVdsPnPNotificationBase@@CA_JPEAUHWND__@@I_K_J@Z>
extern __imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ:PANYARGS
?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ TEXTEQU <__imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_RegisterVdsFabric:PANYARGS
RegisterVdsFabric TEXTEQU <__imp_RegisterVdsFabric>
extern __imp_UnregisterVdsFabric:PANYARGS
UnregisterVdsFabric TEXTEQU <__imp_UnregisterVdsFabric>
