extern __imp_GetFileVersionInfoA:PANYARGS
GetFileVersionInfo  TEXTEQU <__imp_GetFileVersionInfoA>
extern __imp_GetFileVersionInfoSizeA:PANYARGS
GetFileVersionInfoSize  TEXTEQU <__imp_GetFileVersionInfoSizeA>
extern __imp_GetFileVersionInfoSizeW:PANYARGS
GetFileVersionInfoSizeW TEXTEQU <__imp_GetFileVersionInfoSizeW>
extern __imp_GetFileVersionInfoW:PANYARGS
GetFileVersionInfoW TEXTEQU <__imp_GetFileVersionInfoW>
extern __imp_VerFindFileA:PANYARGS
VerFindFile  TEXTEQU <__imp_VerFindFileA>
extern __imp_VerFindFileW:PANYARGS
VerFindFileW TEXTEQU <__imp_VerFindFileW>
extern __imp_VerInstallFileA:PANYARGS
VerInstallFile  TEXTEQU <__imp_VerInstallFileA>
extern __imp_VerInstallFileW:PANYARGS
VerInstallFileW TEXTEQU <__imp_VerInstallFileW>
extern __imp_VerLanguageNameA:PANYARGS
VerLanguageName  TEXTEQU <__imp_VerLanguageNameA>
extern __imp_VerLanguageNameW:PANYARGS
VerLanguageNameW TEXTEQU <__imp_VerLanguageNameW>
extern __imp_VerQueryValueA:PANYARGS
VerQueryValue  TEXTEQU <__imp_VerQueryValueA>
extern __imp_VerQueryValueIndexA:PANYARGS
VerQueryValueIndex  TEXTEQU <__imp_VerQueryValueIndexA>
extern __imp_VerQueryValueIndexW:PANYARGS
VerQueryValueIndexW TEXTEQU <__imp_VerQueryValueIndexW>
extern __imp_VerQueryValueW:PANYARGS
VerQueryValueW TEXTEQU <__imp_VerQueryValueW>
