extern __imp_SimulateSnapshotFreeze:PANYARGS
SimulateSnapshotFreeze TEXTEQU <__imp_SimulateSnapshotFreeze>
extern __imp_SimulateSnapshotThaw:PANYARGS
SimulateSnapshotThaw TEXTEQU <__imp_SimulateSnapshotThaw>
extern __imp_IsVolumeSnapshotted:PANYARGS
IsVolumeSnapshotted TEXTEQU <__imp_IsVolumeSnapshotted>
extern __imp_VssFreeSnapshotProperties:PANYARGS
VssFreeSnapshotProperties TEXTEQU <__imp_VssFreeSnapshotProperties>
extern __imp_ShouldBlockRevert:PANYARGS
ShouldBlockRevert TEXTEQU <__imp_ShouldBlockRevert>
extern __imp_??0CVssJetWriter@@QEAA@XZ:PANYARGS
??0CVssJetWriter@@QEAA@XZ TEXTEQU <__imp_??0CVssJetWriter@@QEAA@XZ>
extern __imp_??0CVssWriter@@QEAA@XZ:PANYARGS
??0CVssWriter@@QEAA@XZ TEXTEQU <__imp_??0CVssWriter@@QEAA@XZ>
extern __imp_??1CVssJetWriter@@UEAA@XZ:PANYARGS
??1CVssJetWriter@@UEAA@XZ TEXTEQU <__imp_??1CVssJetWriter@@UEAA@XZ>
extern __imp_??1CVssWriter@@UEAA@XZ:PANYARGS
??1CVssWriter@@UEAA@XZ TEXTEQU <__imp_??1CVssWriter@@UEAA@XZ>
extern __imp_?AreComponentsSelected@CVssWriter@@IEBA_NXZ:PANYARGS
?AreComponentsSelected@CVssWriter@@IEBA_NXZ TEXTEQU <__imp_?AreComponentsSelected@CVssWriter@@IEBA_NXZ>
extern __imp_?CreateVssBackupComponents@@YAJPEAPEAVIVssBackupComponents@@@Z:PANYARGS
?CreateVssBackupComponents@@YAJPEAPEAVIVssBackupComponents@@@Z TEXTEQU <__imp_?CreateVssBackupComponents@@YAJPEAPEAVIVssBackupComponents@@@Z>
extern __imp_?CreateVssExamineWriterMetadata@@YAJPEAGPEAPEAVIVssExamineWriterMetadata@@@Z:PANYARGS
?CreateVssExamineWriterMetadata@@YAJPEAGPEAPEAVIVssExamineWriterMetadata@@@Z TEXTEQU <__imp_?CreateVssExamineWriterMetadata@@YAJPEAGPEAPEAVIVssExamineWriterMetadata@@@Z>
extern __imp_?CreateVssSnapshotSetDescription@@YAJU_GUID@@JPEAPEAVIVssSnapshotSetDescription@@@Z:PANYARGS
?CreateVssSnapshotSetDescription@@YAJU_GUID@@JPEAPEAVIVssSnapshotSetDescription@@@Z TEXTEQU <__imp_?CreateVssSnapshotSetDescription@@YAJU_GUID@@JPEAPEAVIVssSnapshotSetDescription@@@Z>
extern __imp_?GetBackupType@CVssWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ:PANYARGS
?GetBackupType@CVssWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ TEXTEQU <__imp_?GetBackupType@CVssWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ>
extern __imp_?GetContext@CVssWriter@@IEBAJXZ:PANYARGS
?GetContext@CVssWriter@@IEBAJXZ TEXTEQU <__imp_?GetContext@CVssWriter@@IEBAJXZ>
extern __imp_?GetCurrentLevel@CVssWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ:PANYARGS
?GetCurrentLevel@CVssWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ TEXTEQU <__imp_?GetCurrentLevel@CVssWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ>
extern __imp_?GetCurrentSnapshotSetId@CVssWriter@@IEBA?AU_GUID@@XZ:PANYARGS
?GetCurrentSnapshotSetId@CVssWriter@@IEBA?AU_GUID@@XZ TEXTEQU <__imp_?GetCurrentSnapshotSetId@CVssWriter@@IEBA?AU_GUID@@XZ>
extern __imp_?GetCurrentVolumeArray@CVssWriter@@IEBAPEAPEBGXZ:PANYARGS
?GetCurrentVolumeArray@CVssWriter@@IEBAPEAPEBGXZ TEXTEQU <__imp_?GetCurrentVolumeArray@CVssWriter@@IEBAPEAPEBGXZ>
extern __imp_?GetCurrentVolumeCount@CVssWriter@@IEBAIXZ:PANYARGS
?GetCurrentVolumeCount@CVssWriter@@IEBAIXZ TEXTEQU <__imp_?GetCurrentVolumeCount@CVssWriter@@IEBAIXZ>
extern __imp_?GetRestoreType@CVssWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ:PANYARGS
?GetRestoreType@CVssWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ TEXTEQU <__imp_?GetRestoreType@CVssWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ>
extern __imp_?GetSnapshotDeviceName@CVssWriter@@IEBAJPEBGPEAPEBG@Z:PANYARGS
?GetSnapshotDeviceName@CVssWriter@@IEBAJPEBGPEAPEBG@Z TEXTEQU <__imp_?GetSnapshotDeviceName@CVssWriter@@IEBAJPEBGPEAPEBG@Z>
extern __imp_?Initialize@CVssJetWriter@@QEAAJU_GUID@@PEBG_N211@Z:PANYARGS
?Initialize@CVssJetWriter@@QEAAJU_GUID@@PEBG_N211@Z TEXTEQU <__imp_?Initialize@CVssJetWriter@@QEAAJU_GUID@@PEBG_N211@Z>
extern __imp_?Initialize@CVssWriter@@QEAAJU_GUID@@PEBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z:PANYARGS
?Initialize@CVssWriter@@QEAAJU_GUID@@PEBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z TEXTEQU <__imp_?Initialize@CVssWriter@@QEAAJU_GUID@@PEBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z>
extern __imp_?InstallAlternateWriter@CVssWriter@@QEAAJU_GUID@@0@Z:PANYARGS
?InstallAlternateWriter@CVssWriter@@QEAAJU_GUID@@0@Z TEXTEQU <__imp_?InstallAlternateWriter@CVssWriter@@QEAAJU_GUID@@0@Z>
extern __imp_?IsBootableSystemStateBackedUp@CVssWriter@@IEBA_NXZ:PANYARGS
?IsBootableSystemStateBackedUp@CVssWriter@@IEBA_NXZ TEXTEQU <__imp_?IsBootableSystemStateBackedUp@CVssWriter@@IEBA_NXZ>
extern __imp_?IsPartialFileSupportEnabled@CVssWriter@@IEBA_NXZ:PANYARGS
?IsPartialFileSupportEnabled@CVssWriter@@IEBA_NXZ TEXTEQU <__imp_?IsPartialFileSupportEnabled@CVssWriter@@IEBA_NXZ>
extern __imp_?IsPathAffected@CVssWriter@@IEBA_NPEBG@Z:PANYARGS
?IsPathAffected@CVssWriter@@IEBA_NPEBG@Z TEXTEQU <__imp_?IsPathAffected@CVssWriter@@IEBA_NPEBG@Z>
extern __imp_?LoadVssSnapshotSetDescription@@YAJPEBGPEAPEAVIVssSnapshotSetDescription@@U_GUID@@@Z:PANYARGS
?LoadVssSnapshotSetDescription@@YAJPEBGPEAPEAVIVssSnapshotSetDescription@@U_GUID@@@Z TEXTEQU <__imp_?LoadVssSnapshotSetDescription@@YAJPEBGPEAPEAVIVssSnapshotSetDescription@@U_GUID@@@Z>
extern __imp_?OnAbortBegin@CVssJetWriter@@UEAAXXZ:PANYARGS
?OnAbortBegin@CVssJetWriter@@UEAAXXZ TEXTEQU <__imp_?OnAbortBegin@CVssJetWriter@@UEAAXXZ>
extern __imp_?OnAbortEnd@CVssJetWriter@@UEAAXXZ:PANYARGS
?OnAbortEnd@CVssJetWriter@@UEAAXXZ TEXTEQU <__imp_?OnAbortEnd@CVssJetWriter@@UEAAXXZ>
extern __imp_?OnBackOffIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z:PANYARGS
?OnBackOffIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z TEXTEQU <__imp_?OnBackOffIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z>
extern __imp_?OnBackupComplete@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnBackupComplete@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnBackupComplete@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnBackupCompleteBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnBackupCompleteBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnBackupCompleteBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnBackupCompleteEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PANYARGS
?OnBackupCompleteEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z TEXTEQU <__imp_?OnBackupCompleteEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>
extern __imp_?OnBackupShutdown@CVssWriter@@UEAA_NU_GUID@@@Z:PANYARGS
?OnBackupShutdown@CVssWriter@@UEAA_NU_GUID@@@Z TEXTEQU <__imp_?OnBackupShutdown@CVssWriter@@UEAA_NU_GUID@@@Z>
extern __imp_?OnContinueIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z:PANYARGS
?OnContinueIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z TEXTEQU <__imp_?OnContinueIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z>
extern __imp_?OnFreezeBegin@CVssJetWriter@@UEAA_NXZ:PANYARGS
?OnFreezeBegin@CVssJetWriter@@UEAA_NXZ TEXTEQU <__imp_?OnFreezeBegin@CVssJetWriter@@UEAA_NXZ>
extern __imp_?OnFreezeEnd@CVssJetWriter@@UEAA_N_N@Z:PANYARGS
?OnFreezeEnd@CVssJetWriter@@UEAA_N_N@Z TEXTEQU <__imp_?OnFreezeEnd@CVssJetWriter@@UEAA_N_N@Z>
extern __imp_?OnIdentify@CVssJetWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z:PANYARGS
?OnIdentify@CVssJetWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z TEXTEQU <__imp_?OnIdentify@CVssJetWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z>
extern __imp_?OnIdentify@CVssWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z:PANYARGS
?OnIdentify@CVssWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z TEXTEQU <__imp_?OnIdentify@CVssWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z>
extern __imp_?OnPostRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPostRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPostRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPostRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPostRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPostRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPostRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PANYARGS
?OnPostRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z TEXTEQU <__imp_?OnPostRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>
extern __imp_?OnPostSnapshot@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPostSnapshot@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPostSnapshot@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPostSnapshot@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPostSnapshot@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPostSnapshot@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPreRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPreRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPreRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPreRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPreRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPreRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPreRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PANYARGS
?OnPreRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z TEXTEQU <__imp_?OnPreRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>
extern __imp_?OnPrepareBackup@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPrepareBackup@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPrepareBackup@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPrepareBackupBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PANYARGS
?OnPrepareBackupBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z TEXTEQU <__imp_?OnPrepareBackupBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>
extern __imp_?OnPrepareBackupEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PANYARGS
?OnPrepareBackupEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z TEXTEQU <__imp_?OnPrepareBackupEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>
extern __imp_?OnPrepareSnapshotBegin@CVssJetWriter@@UEAA_NXZ:PANYARGS
?OnPrepareSnapshotBegin@CVssJetWriter@@UEAA_NXZ TEXTEQU <__imp_?OnPrepareSnapshotBegin@CVssJetWriter@@UEAA_NXZ>
extern __imp_?OnPrepareSnapshotEnd@CVssJetWriter@@UEAA_N_N@Z:PANYARGS
?OnPrepareSnapshotEnd@CVssJetWriter@@UEAA_N_N@Z TEXTEQU <__imp_?OnPrepareSnapshotEnd@CVssJetWriter@@UEAA_N_N@Z>
extern __imp_?OnThawBegin@CVssJetWriter@@UEAA_NXZ:PANYARGS
?OnThawBegin@CVssJetWriter@@UEAA_NXZ TEXTEQU <__imp_?OnThawBegin@CVssJetWriter@@UEAA_NXZ>
extern __imp_?OnThawEnd@CVssJetWriter@@UEAA_N_N@Z:PANYARGS
?OnThawEnd@CVssJetWriter@@UEAA_N_N@Z TEXTEQU <__imp_?OnThawEnd@CVssJetWriter@@UEAA_N_N@Z>
extern __imp_?OnVSSApplicationStartup@CVssWriter@@UEAA_NXZ:PANYARGS
?OnVSSApplicationStartup@CVssWriter@@UEAA_NXZ TEXTEQU <__imp_?OnVSSApplicationStartup@CVssWriter@@UEAA_NXZ>
extern __imp_?OnVSSShutdown@CVssWriter@@UEAA_NXZ:PANYARGS
?OnVSSShutdown@CVssWriter@@UEAA_NXZ TEXTEQU <__imp_?OnVSSShutdown@CVssWriter@@UEAA_NXZ>
extern __imp_?SetWriterFailure@CVssWriter@@IEAAJJ@Z:PANYARGS
?SetWriterFailure@CVssWriter@@IEAAJJ@Z TEXTEQU <__imp_?SetWriterFailure@CVssWriter@@IEAAJJ@Z>
extern __imp_?Subscribe@CVssWriter@@QEAAJK@Z:PANYARGS
?Subscribe@CVssWriter@@QEAAJK@Z TEXTEQU <__imp_?Subscribe@CVssWriter@@QEAAJK@Z>
extern __imp_?Uninitialize@CVssJetWriter@@QEAAXXZ:PANYARGS
?Uninitialize@CVssJetWriter@@QEAAXXZ TEXTEQU <__imp_?Uninitialize@CVssJetWriter@@QEAAXXZ>
extern __imp_?Unsubscribe@CVssWriter@@QEAAJXZ:PANYARGS
?Unsubscribe@CVssWriter@@QEAAJXZ TEXTEQU <__imp_?Unsubscribe@CVssWriter@@QEAAJXZ>
