extern __imp_ToplAddEdgeSetToGraph:PANYARGS
ToplAddEdgeSetToGraph TEXTEQU <__imp_ToplAddEdgeSetToGraph>
extern __imp_ToplAddEdgeToGraph:PANYARGS
ToplAddEdgeToGraph TEXTEQU <__imp_ToplAddEdgeToGraph>
extern __imp_ToplDeleteComponents:PANYARGS
ToplDeleteComponents TEXTEQU <__imp_ToplDeleteComponents>
extern __imp_ToplDeleteGraphState:PANYARGS
ToplDeleteGraphState TEXTEQU <__imp_ToplDeleteGraphState>
extern __imp_ToplDeleteSpanningTreeEdges:PANYARGS
ToplDeleteSpanningTreeEdges TEXTEQU <__imp_ToplDeleteSpanningTreeEdges>
extern __imp_ToplEdgeAssociate:PANYARGS
ToplEdgeAssociate TEXTEQU <__imp_ToplEdgeAssociate>
extern __imp_ToplEdgeCreate:PANYARGS
ToplEdgeCreate TEXTEQU <__imp_ToplEdgeCreate>
extern __imp_ToplEdgeDestroy:PANYARGS
ToplEdgeDestroy TEXTEQU <__imp_ToplEdgeDestroy>
extern __imp_ToplEdgeDisassociate:PANYARGS
ToplEdgeDisassociate TEXTEQU <__imp_ToplEdgeDisassociate>
extern __imp_ToplEdgeFree:PANYARGS
ToplEdgeFree TEXTEQU <__imp_ToplEdgeFree>
extern __imp_ToplEdgeGetFromVertex:PANYARGS
ToplEdgeGetFromVertex TEXTEQU <__imp_ToplEdgeGetFromVertex>
extern __imp_ToplEdgeGetToVertex:PANYARGS
ToplEdgeGetToVertex TEXTEQU <__imp_ToplEdgeGetToVertex>
extern __imp_ToplEdgeGetWeight:PANYARGS
ToplEdgeGetWeight TEXTEQU <__imp_ToplEdgeGetWeight>
extern __imp_ToplEdgeInit:PANYARGS
ToplEdgeInit TEXTEQU <__imp_ToplEdgeInit>
extern __imp_ToplEdgeSetFromVertex:PANYARGS
ToplEdgeSetFromVertex TEXTEQU <__imp_ToplEdgeSetFromVertex>
extern __imp_ToplEdgeSetToVertex:PANYARGS
ToplEdgeSetToVertex TEXTEQU <__imp_ToplEdgeSetToVertex>
extern __imp_ToplEdgeSetVtx:PANYARGS
ToplEdgeSetVtx TEXTEQU <__imp_ToplEdgeSetVtx>
extern __imp_ToplEdgeSetWeight:PANYARGS
ToplEdgeSetWeight TEXTEQU <__imp_ToplEdgeSetWeight>
extern __imp_ToplFree:PANYARGS
ToplFree TEXTEQU <__imp_ToplFree>
extern __imp_ToplGetAlwaysSchedule:PANYARGS
ToplGetAlwaysSchedule TEXTEQU <__imp_ToplGetAlwaysSchedule>
extern __imp_ToplGetSpanningTreeEdgesForVtx:PANYARGS
ToplGetSpanningTreeEdgesForVtx TEXTEQU <__imp_ToplGetSpanningTreeEdgesForVtx>
extern __imp_ToplGraphAddVertex:PANYARGS
ToplGraphAddVertex TEXTEQU <__imp_ToplGraphAddVertex>
extern __imp_ToplGraphCreate:PANYARGS
ToplGraphCreate TEXTEQU <__imp_ToplGraphCreate>
extern __imp_ToplGraphDestroy:PANYARGS
ToplGraphDestroy TEXTEQU <__imp_ToplGraphDestroy>
extern __imp_ToplGraphFindEdgesForMST:PANYARGS
ToplGraphFindEdgesForMST TEXTEQU <__imp_ToplGraphFindEdgesForMST>
extern __imp_ToplGraphFree:PANYARGS
ToplGraphFree TEXTEQU <__imp_ToplGraphFree>
extern __imp_ToplGraphInit:PANYARGS
ToplGraphInit TEXTEQU <__imp_ToplGraphInit>
extern __imp_ToplGraphMakeRing:PANYARGS
ToplGraphMakeRing TEXTEQU <__imp_ToplGraphMakeRing>
extern __imp_ToplGraphNumberOfVertices:PANYARGS
ToplGraphNumberOfVertices TEXTEQU <__imp_ToplGraphNumberOfVertices>
extern __imp_ToplGraphRemoveVertex:PANYARGS
ToplGraphRemoveVertex TEXTEQU <__imp_ToplGraphRemoveVertex>
extern __imp_ToplGraphSetVertexIter:PANYARGS
ToplGraphSetVertexIter TEXTEQU <__imp_ToplGraphSetVertexIter>
extern __imp_ToplHeapCreate:PANYARGS
ToplHeapCreate TEXTEQU <__imp_ToplHeapCreate>
extern __imp_ToplHeapDestroy:PANYARGS
ToplHeapDestroy TEXTEQU <__imp_ToplHeapDestroy>
extern __imp_ToplHeapExtractMin:PANYARGS
ToplHeapExtractMin TEXTEQU <__imp_ToplHeapExtractMin>
extern __imp_ToplHeapInsert:PANYARGS
ToplHeapInsert TEXTEQU <__imp_ToplHeapInsert>
extern __imp_ToplHeapIsElementOf:PANYARGS
ToplHeapIsElementOf TEXTEQU <__imp_ToplHeapIsElementOf>
extern __imp_ToplHeapIsEmpty:PANYARGS
ToplHeapIsEmpty TEXTEQU <__imp_ToplHeapIsEmpty>
extern __imp_ToplIsToplException:PANYARGS
ToplIsToplException TEXTEQU <__imp_ToplIsToplException>
extern __imp_ToplIterAdvance:PANYARGS
ToplIterAdvance TEXTEQU <__imp_ToplIterAdvance>
extern __imp_ToplIterCreate:PANYARGS
ToplIterCreate TEXTEQU <__imp_ToplIterCreate>
extern __imp_ToplIterFree:PANYARGS
ToplIterFree TEXTEQU <__imp_ToplIterFree>
extern __imp_ToplIterGetObject:PANYARGS
ToplIterGetObject TEXTEQU <__imp_ToplIterGetObject>
extern __imp_ToplListAddElem:PANYARGS
ToplListAddElem TEXTEQU <__imp_ToplListAddElem>
extern __imp_ToplListCreate:PANYARGS
ToplListCreate TEXTEQU <__imp_ToplListCreate>
extern __imp_ToplListFree:PANYARGS
ToplListFree TEXTEQU <__imp_ToplListFree>
extern __imp_ToplListNumberOfElements:PANYARGS
ToplListNumberOfElements TEXTEQU <__imp_ToplListNumberOfElements>
extern __imp_ToplListRemoveElem:PANYARGS
ToplListRemoveElem TEXTEQU <__imp_ToplListRemoveElem>
extern __imp_ToplListSetIter:PANYARGS
ToplListSetIter TEXTEQU <__imp_ToplListSetIter>
extern __imp_ToplMakeGraphState:PANYARGS
ToplMakeGraphState TEXTEQU <__imp_ToplMakeGraphState>
extern __imp_ToplPScheduleValid:PANYARGS
ToplPScheduleValid TEXTEQU <__imp_ToplPScheduleValid>
extern __imp_ToplSTHeapAdd:PANYARGS
ToplSTHeapAdd TEXTEQU <__imp_ToplSTHeapAdd>
extern __imp_ToplSTHeapCostReduced:PANYARGS
ToplSTHeapCostReduced TEXTEQU <__imp_ToplSTHeapCostReduced>
extern __imp_ToplSTHeapDestroy:PANYARGS
ToplSTHeapDestroy TEXTEQU <__imp_ToplSTHeapDestroy>
extern __imp_ToplSTHeapExtractMin:PANYARGS
ToplSTHeapExtractMin TEXTEQU <__imp_ToplSTHeapExtractMin>
extern __imp_ToplSTHeapInit:PANYARGS
ToplSTHeapInit TEXTEQU <__imp_ToplSTHeapInit>
extern __imp_ToplScheduleCacheCreate:PANYARGS
ToplScheduleCacheCreate TEXTEQU <__imp_ToplScheduleCacheCreate>
extern __imp_ToplScheduleCacheDestroy:PANYARGS
ToplScheduleCacheDestroy TEXTEQU <__imp_ToplScheduleCacheDestroy>
extern __imp_ToplScheduleCreate:PANYARGS
ToplScheduleCreate TEXTEQU <__imp_ToplScheduleCreate>
extern __imp_ToplScheduleDuration:PANYARGS
ToplScheduleDuration TEXTEQU <__imp_ToplScheduleDuration>
extern __imp_ToplScheduleExportReadonly:PANYARGS
ToplScheduleExportReadonly TEXTEQU <__imp_ToplScheduleExportReadonly>
extern __imp_ToplScheduleImport:PANYARGS
ToplScheduleImport TEXTEQU <__imp_ToplScheduleImport>
extern __imp_ToplScheduleIsEqual:PANYARGS
ToplScheduleIsEqual TEXTEQU <__imp_ToplScheduleIsEqual>
extern __imp_ToplScheduleMaxUnavailable:PANYARGS
ToplScheduleMaxUnavailable TEXTEQU <__imp_ToplScheduleMaxUnavailable>
extern __imp_ToplScheduleMerge:PANYARGS
ToplScheduleMerge TEXTEQU <__imp_ToplScheduleMerge>
extern __imp_ToplScheduleNumEntries:PANYARGS
ToplScheduleNumEntries TEXTEQU <__imp_ToplScheduleNumEntries>
extern __imp_ToplScheduleValid:PANYARGS
ToplScheduleValid TEXTEQU <__imp_ToplScheduleValid>
extern __imp_ToplSetAllocator:PANYARGS
ToplSetAllocator TEXTEQU <__imp_ToplSetAllocator>
extern __imp_ToplVertexCreate:PANYARGS
ToplVertexCreate TEXTEQU <__imp_ToplVertexCreate>
extern __imp_ToplVertexDestroy:PANYARGS
ToplVertexDestroy TEXTEQU <__imp_ToplVertexDestroy>
extern __imp_ToplVertexFree:PANYARGS
ToplVertexFree TEXTEQU <__imp_ToplVertexFree>
extern __imp_ToplVertexGetId:PANYARGS
ToplVertexGetId TEXTEQU <__imp_ToplVertexGetId>
extern __imp_ToplVertexGetInEdge:PANYARGS
ToplVertexGetInEdge TEXTEQU <__imp_ToplVertexGetInEdge>
extern __imp_ToplVertexGetOutEdge:PANYARGS
ToplVertexGetOutEdge TEXTEQU <__imp_ToplVertexGetOutEdge>
extern __imp_ToplVertexGetParent:PANYARGS
ToplVertexGetParent TEXTEQU <__imp_ToplVertexGetParent>
extern __imp_ToplVertexInit:PANYARGS
ToplVertexInit TEXTEQU <__imp_ToplVertexInit>
extern __imp_ToplVertexNumberOfInEdges:PANYARGS
ToplVertexNumberOfInEdges TEXTEQU <__imp_ToplVertexNumberOfInEdges>
extern __imp_ToplVertexNumberOfOutEdges:PANYARGS
ToplVertexNumberOfOutEdges TEXTEQU <__imp_ToplVertexNumberOfOutEdges>
extern __imp_ToplVertexSetId:PANYARGS
ToplVertexSetId TEXTEQU <__imp_ToplVertexSetId>
extern __imp_ToplVertexSetParent:PANYARGS
ToplVertexSetParent TEXTEQU <__imp_ToplVertexSetParent>
