extern __imp_WdfCoInstaller:PANYARGS
WdfCoInstaller TEXTEQU <__imp_WdfCoInstaller>
extern __imp_WdfPostDeviceInstall:PANYARGS
WdfPostDeviceInstall TEXTEQU <__imp_WdfPostDeviceInstall>
extern __imp_WdfPostDeviceRemove:PANYARGS
WdfPostDeviceRemove TEXTEQU <__imp_WdfPostDeviceRemove>
extern __imp_WdfPreDeviceInstall:PANYARGS
WdfPreDeviceInstall TEXTEQU <__imp_WdfPreDeviceInstall>
extern __imp_WdfPreDeviceRemove:PANYARGS
WdfPreDeviceRemove TEXTEQU <__imp_WdfPreDeviceRemove>
