extern __imp_SpInitialize:PANYARGS
SpInitialize TEXTEQU <__imp_SpInitialize>
extern __imp_CredentialUpdateRegister:PANYARGS
CredentialUpdateRegister TEXTEQU <__imp_CredentialUpdateRegister>
extern __imp_SsiCredentialsUpdateNotify:PANYARGS
SsiCredentialsUpdateNotify TEXTEQU <__imp_SsiCredentialsUpdateNotify>
extern __imp_CredentialUpdateFree:PANYARGS
CredentialUpdateFree TEXTEQU <__imp_CredentialUpdateFree>
extern __imp_CredentialUpdateNotify:PANYARGS
CredentialUpdateNotify TEXTEQU <__imp_CredentialUpdateNotify>
extern __imp_SpLsaModeInitialize:PANYARGS
SpLsaModeInitialize TEXTEQU <__imp_SpLsaModeInitialize>
extern __imp_SpUserModeInitialize:PANYARGS
SpUserModeInitialize TEXTEQU <__imp_SpUserModeInitialize>
extern __imp_SsiCredentialsUpdateFree:PANYARGS
SsiCredentialsUpdateFree TEXTEQU <__imp_SsiCredentialsUpdateFree>
extern __imp_wdigest_ordinal9:PANYARGS
wdigest_ordinal9 TEXTEQU <__imp_wdigest_ordinal9>
extern __imp_wdigest_ordinal10:PANYARGS
wdigest_ordinal10 TEXTEQU <__imp_wdigest_ordinal10>
extern __imp_wdigest_ordinal11:PANYARGS
wdigest_ordinal11 TEXTEQU <__imp_wdigest_ordinal11>
extern __imp_wdigest_ordinal12:PANYARGS
wdigest_ordinal12 TEXTEQU <__imp_wdigest_ordinal12>
extern __imp_wdigest_ordinal13:PANYARGS
wdigest_ordinal13 TEXTEQU <__imp_wdigest_ordinal13>
extern __imp_wdigest_ordinal14:PANYARGS
wdigest_ordinal14 TEXTEQU <__imp_wdigest_ordinal14>
extern __imp_wdigest_ordinal15:PANYARGS
wdigest_ordinal15 TEXTEQU <__imp_wdigest_ordinal15>
extern __imp_wdigest_ordinal16:PANYARGS
wdigest_ordinal16 TEXTEQU <__imp_wdigest_ordinal16>
extern __imp_wdigest_ordinal17:PANYARGS
wdigest_ordinal17 TEXTEQU <__imp_wdigest_ordinal17>
extern __imp_wdigest_ordinal18:PANYARGS
wdigest_ordinal18 TEXTEQU <__imp_wdigest_ordinal18>
extern __imp_wdigest_ordinal19:PANYARGS
wdigest_ordinal19 TEXTEQU <__imp_wdigest_ordinal19>
extern __imp_wdigest_ordinal20:PANYARGS
wdigest_ordinal20 TEXTEQU <__imp_wdigest_ordinal20>
extern __imp_wdigest_ordinal21:PANYARGS
wdigest_ordinal21 TEXTEQU <__imp_wdigest_ordinal21>
extern __imp_wdigest_ordinal22:PANYARGS
wdigest_ordinal22 TEXTEQU <__imp_wdigest_ordinal22>
extern __imp_wdigest_ordinal23:PANYARGS
wdigest_ordinal23 TEXTEQU <__imp_wdigest_ordinal23>
extern __imp_wdigest_ordinal24:PANYARGS
wdigest_ordinal24 TEXTEQU <__imp_wdigest_ordinal24>
extern __imp_wdigest_ordinal25:PANYARGS
wdigest_ordinal25 TEXTEQU <__imp_wdigest_ordinal25>
extern __imp_wdigest_ordinal26:PANYARGS
wdigest_ordinal26 TEXTEQU <__imp_wdigest_ordinal26>
extern __imp_wdigest_ordinal27:PANYARGS
wdigest_ordinal27 TEXTEQU <__imp_wdigest_ordinal27>
extern __imp_wdigest_ordinal28:PANYARGS
wdigest_ordinal28 TEXTEQU <__imp_wdigest_ordinal28>
extern __imp_wdigest_ordinal29:PANYARGS
wdigest_ordinal29 TEXTEQU <__imp_wdigest_ordinal29>
extern __imp_wdigest_ordinal30:PANYARGS
wdigest_ordinal30 TEXTEQU <__imp_wdigest_ordinal30>
extern __imp_wdigest_ordinal31:PANYARGS
wdigest_ordinal31 TEXTEQU <__imp_wdigest_ordinal31>
extern __imp_SpInstanceInit:PANYARGS
SpInstanceInit TEXTEQU <__imp_SpInstanceInit>
