extern __imp_webcheck_ordinal7:PANYARGS
webcheck_ordinal7 TEXTEQU <__imp_webcheck_ordinal7>
extern __imp_webcheck_ordinal8:PANYARGS
webcheck_ordinal8 TEXTEQU <__imp_webcheck_ordinal8>
extern __imp_XMLScheduleElementToTaskTrigger:PANYARGS
XMLScheduleElementToTaskTrigger TEXTEQU <__imp_XMLScheduleElementToTaskTrigger>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
