extern __imp_FindFirstImportDS:PANYARGS
FindFirstImportDS TEXTEQU <__imp_FindFirstImportDS>
extern __imp_FindNextImportDS:PANYARGS
FindNextImportDS TEXTEQU <__imp_FindNextImportDS>
extern __imp_CloseFindContext:PANYARGS
CloseFindContext TEXTEQU <__imp_CloseFindContext>
extern __imp_LoadImportDS:PANYARGS
LoadImportDS TEXTEQU <__imp_LoadImportDS>
extern __imp_UnloadImportDS:PANYARGS
UnloadImportDS TEXTEQU <__imp_UnloadImportDS>
extern __imp_GetLoaderStatus:PANYARGS
GetLoaderStatus TEXTEQU <__imp_GetLoaderStatus>
extern __imp_FindImportDSByDeviceName:PANYARGS
FindImportDSByDeviceName TEXTEQU <__imp_FindImportDSByDeviceName>
extern __imp_??0BUFFER@@QEAA@I@Z:PANYARGS
??0BUFFER@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER@@QEAA@I@Z>
extern __imp_??0BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??0BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??0BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z:PANYARGS
??0BUFFER_CHAIN_ITEM@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z>
extern __imp_??1BUFFER@@QEAA@XZ:PANYARGS
??1BUFFER@@QEAA@XZ TEXTEQU <__imp_??1BUFFER@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN_ITEM@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ>
extern __imp_??_FBUFFER@@QEAAXXZ:PANYARGS
??_FBUFFER@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER@@QEAAXXZ>
extern __imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ:PANYARGS
??_FBUFFER_CHAIN_ITEM@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ>
extern __imp_?QueryPtr@BUFFER@@QEBAPEAXXZ:PANYARGS
?QueryPtr@BUFFER@@QEBAPEAXXZ TEXTEQU <__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ>
extern __imp_?QuerySize@BUFFER@@QEBAIXZ:PANYARGS
?QuerySize@BUFFER@@QEBAIXZ TEXTEQU <__imp_?QuerySize@BUFFER@@QEBAIXZ>
extern __imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ:PANYARGS
?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ TEXTEQU <__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ>
extern __imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z:PANYARGS
?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z TEXTEQU <__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z>
