extern __imp_??0BUFFER@@QEAA@I@Z:PANYARGS
??0BUFFER@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER@@QEAA@I@Z>
extern __imp_??0BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??0BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??0BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z:PANYARGS
??0BUFFER_CHAIN_ITEM@@QEAA@I@Z TEXTEQU <__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z>
extern __imp_??1BUFFER@@QEAA@XZ:PANYARGS
??1BUFFER@@QEAA@XZ TEXTEQU <__imp_??1BUFFER@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN@@QEAA@XZ>
extern __imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ:PANYARGS
??1BUFFER_CHAIN_ITEM@@QEAA@XZ TEXTEQU <__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ>
extern __imp_??_FBUFFER@@QEAAXXZ:PANYARGS
??_FBUFFER@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER@@QEAAXXZ>
extern __imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ:PANYARGS
??_FBUFFER_CHAIN_ITEM@@QEAAXXZ TEXTEQU <__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ>
extern __imp_?QueryPtr@BUFFER@@QEBAPEAXXZ:PANYARGS
?QueryPtr@BUFFER@@QEBAPEAXXZ TEXTEQU <__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ>
extern __imp_?QuerySize@BUFFER@@QEBAIXZ:PANYARGS
?QuerySize@BUFFER@@QEBAIXZ TEXTEQU <__imp_?QuerySize@BUFFER@@QEBAIXZ>
extern __imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ:PANYARGS
?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ TEXTEQU <__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ>
extern __imp_ServiceMain:PANYARGS
ServiceMain TEXTEQU <__imp_ServiceMain>
extern __imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z:PANYARGS
?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z TEXTEQU <__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z>
extern __imp_SvchostPushServiceGlobals:PANYARGS
SvchostPushServiceGlobals TEXTEQU <__imp_SvchostPushServiceGlobals>
extern __imp_DllEntryPoint:PANYARGS
DllEntryPoint TEXTEQU <__imp_DllEntryPoint>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_wiasCreateChildAppItem:PANYARGS
wiasCreateChildAppItem TEXTEQU <__imp_wiasCreateChildAppItem>
extern __imp_wiasCreateDrvItem:PANYARGS
wiasCreateDrvItem TEXTEQU <__imp_wiasCreateDrvItem>
extern __imp_wiasCreateLogInstance:PANYARGS
wiasCreateLogInstance TEXTEQU <__imp_wiasCreateLogInstance>
extern __imp_wiasCreatePropContext:PANYARGS
wiasCreatePropContext TEXTEQU <__imp_wiasCreatePropContext>
extern __imp_wiasDebugError:PANYARGS
wiasDebugError TEXTEQU <__imp_wiasDebugError>
extern __imp_wiasDebugTrace:PANYARGS
wiasDebugTrace TEXTEQU <__imp_wiasDebugTrace>
extern __imp_wiasDownSampleBuffer:PANYARGS
wiasDownSampleBuffer TEXTEQU <__imp_wiasDownSampleBuffer>
extern __imp_wiasFormatArgs:PANYARGS
wiasFormatArgs TEXTEQU <__imp_wiasFormatArgs>
extern __imp_wiasFreePropContext:PANYARGS
wiasFreePropContext TEXTEQU <__imp_wiasFreePropContext>
extern __imp_wiasGetChangedValueFloat:PANYARGS
wiasGetChangedValueFloat TEXTEQU <__imp_wiasGetChangedValueFloat>
extern __imp_wiasGetChangedValueGuid:PANYARGS
wiasGetChangedValueGuid TEXTEQU <__imp_wiasGetChangedValueGuid>
extern __imp_wiasGetChangedValueLong:PANYARGS
wiasGetChangedValueLong TEXTEQU <__imp_wiasGetChangedValueLong>
extern __imp_wiasGetChangedValueStr:PANYARGS
wiasGetChangedValueStr TEXTEQU <__imp_wiasGetChangedValueStr>
extern __imp_wiasGetChildrenContexts:PANYARGS
wiasGetChildrenContexts TEXTEQU <__imp_wiasGetChildrenContexts>
extern __imp_wiasGetContextFromName:PANYARGS
wiasGetContextFromName TEXTEQU <__imp_wiasGetContextFromName>
extern __imp_wiasGetDrvItem:PANYARGS
wiasGetDrvItem TEXTEQU <__imp_wiasGetDrvItem>
extern __imp_wiasGetImageInformation:PANYARGS
wiasGetImageInformation TEXTEQU <__imp_wiasGetImageInformation>
extern __imp_wiasGetItemType:PANYARGS
wiasGetItemType TEXTEQU <__imp_wiasGetItemType>
extern __imp_wiasGetPropertyAttributes:PANYARGS
wiasGetPropertyAttributes TEXTEQU <__imp_wiasGetPropertyAttributes>
extern __imp_wiasGetRootItem:PANYARGS
wiasGetRootItem TEXTEQU <__imp_wiasGetRootItem>
extern __imp_wiasIsPropChanged:PANYARGS
wiasIsPropChanged TEXTEQU <__imp_wiasIsPropChanged>
extern __imp_wiasParseEndorserString:PANYARGS
wiasParseEndorserString TEXTEQU <__imp_wiasParseEndorserString>
extern __imp_wiasPrintDebugHResult:PANYARGS
wiasPrintDebugHResult TEXTEQU <__imp_wiasPrintDebugHResult>
extern __imp_wiasQueueEvent:PANYARGS
wiasQueueEvent TEXTEQU <__imp_wiasQueueEvent>
extern __imp_wiasReadMultiple:PANYARGS
wiasReadMultiple TEXTEQU <__imp_wiasReadMultiple>
extern __imp_wiasReadPropBin:PANYARGS
wiasReadPropBin TEXTEQU <__imp_wiasReadPropBin>
extern __imp_wiasReadPropFloat:PANYARGS
wiasReadPropFloat TEXTEQU <__imp_wiasReadPropFloat>
extern __imp_wiasReadPropGuid:PANYARGS
wiasReadPropGuid TEXTEQU <__imp_wiasReadPropGuid>
extern __imp_wiasReadPropLong:PANYARGS
wiasReadPropLong TEXTEQU <__imp_wiasReadPropLong>
extern __imp_wiasReadPropStr:PANYARGS
wiasReadPropStr TEXTEQU <__imp_wiasReadPropStr>
extern __imp_wiasSendEndOfPage:PANYARGS
wiasSendEndOfPage TEXTEQU <__imp_wiasSendEndOfPage>
extern __imp_wiasSetItemPropAttribs:PANYARGS
wiasSetItemPropAttribs TEXTEQU <__imp_wiasSetItemPropAttribs>
extern __imp_wiasSetItemPropNames:PANYARGS
wiasSetItemPropNames TEXTEQU <__imp_wiasSetItemPropNames>
extern __imp_wiasSetPropChanged:PANYARGS
wiasSetPropChanged TEXTEQU <__imp_wiasSetPropChanged>
extern __imp_wiasSetPropertyAttributes:PANYARGS
wiasSetPropertyAttributes TEXTEQU <__imp_wiasSetPropertyAttributes>
extern __imp_wiasSetValidFlag:PANYARGS
wiasSetValidFlag TEXTEQU <__imp_wiasSetValidFlag>
extern __imp_wiasSetValidListFloat:PANYARGS
wiasSetValidListFloat TEXTEQU <__imp_wiasSetValidListFloat>
extern __imp_wiasSetValidListGuid:PANYARGS
wiasSetValidListGuid TEXTEQU <__imp_wiasSetValidListGuid>
extern __imp_wiasSetValidListLong:PANYARGS
wiasSetValidListLong TEXTEQU <__imp_wiasSetValidListLong>
extern __imp_wiasSetValidListStr:PANYARGS
wiasSetValidListStr TEXTEQU <__imp_wiasSetValidListStr>
extern __imp_wiasSetValidRangeFloat:PANYARGS
wiasSetValidRangeFloat TEXTEQU <__imp_wiasSetValidRangeFloat>
extern __imp_wiasSetValidRangeLong:PANYARGS
wiasSetValidRangeLong TEXTEQU <__imp_wiasSetValidRangeLong>
extern __imp_wiasUpdateScanRect:PANYARGS
wiasUpdateScanRect TEXTEQU <__imp_wiasUpdateScanRect>
extern __imp_wiasUpdateValidFormat:PANYARGS
wiasUpdateValidFormat TEXTEQU <__imp_wiasUpdateValidFormat>
extern __imp_wiasValidateItemProperties:PANYARGS
wiasValidateItemProperties TEXTEQU <__imp_wiasValidateItemProperties>
extern __imp_wiasWriteBufToFile:PANYARGS
wiasWriteBufToFile TEXTEQU <__imp_wiasWriteBufToFile>
extern __imp_wiasWriteMultiple:PANYARGS
wiasWriteMultiple TEXTEQU <__imp_wiasWriteMultiple>
extern __imp_wiasWritePageBufToFile:PANYARGS
wiasWritePageBufToFile TEXTEQU <__imp_wiasWritePageBufToFile>
extern __imp_wiasWritePropBin:PANYARGS
wiasWritePropBin TEXTEQU <__imp_wiasWritePropBin>
extern __imp_wiasWritePropFloat:PANYARGS
wiasWritePropFloat TEXTEQU <__imp_wiasWritePropFloat>
extern __imp_wiasWritePropGuid:PANYARGS
wiasWritePropGuid TEXTEQU <__imp_wiasWritePropGuid>
extern __imp_wiasWritePropLong:PANYARGS
wiasWritePropLong TEXTEQU <__imp_wiasWritePropLong>
extern __imp_wiasWritePropStr:PANYARGS
wiasWritePropStr TEXTEQU <__imp_wiasWritePropStr>
