extern __imp_AddDeviceWasChosen:PANYARGS
AddDeviceWasChosen TEXTEQU <__imp_AddDeviceWasChosen>
extern __imp_AddDeviceWasChosenA:PANYARGS
AddDeviceWasChosen  TEXTEQU <__imp_AddDeviceWasChosenA>
extern __imp_AddDeviceWasChosenW:PANYARGS
AddDeviceWasChosenW TEXTEQU <__imp_AddDeviceWasChosenW>
extern __imp_MakeFullPidlForDevice:PANYARGS
MakeFullPidlForDevice TEXTEQU <__imp_MakeFullPidlForDevice>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_DoDeleteAllItems:PANYARGS
DoDeleteAllItems TEXTEQU <__imp_DoDeleteAllItems>
