extern __imp_FaxAbort:PANYARGS
FaxAbort TEXTEQU <__imp_FaxAbort>
extern __imp_FaxAccessCheck:PANYARGS
FaxAccessCheck TEXTEQU <__imp_FaxAccessCheck>
extern __imp_FaxClose:PANYARGS
FaxClose TEXTEQU <__imp_FaxClose>
extern __imp_FaxCompleteJobParamsA:PANYARGS
FaxCompleteJobParams  TEXTEQU <__imp_FaxCompleteJobParamsA>
extern __imp_FaxCompleteJobParamsW:PANYARGS
FaxCompleteJobParamsW TEXTEQU <__imp_FaxCompleteJobParamsW>
extern __imp_FaxConnectFaxServerA:PANYARGS
FaxConnectFaxServer  TEXTEQU <__imp_FaxConnectFaxServerA>
extern __imp_FaxConnectFaxServerW:PANYARGS
FaxConnectFaxServerW TEXTEQU <__imp_FaxConnectFaxServerW>
extern __imp_FaxEnableRoutingMethodA:PANYARGS
FaxEnableRoutingMethod  TEXTEQU <__imp_FaxEnableRoutingMethodA>
extern __imp_FaxEnableRoutingMethodW:PANYARGS
FaxEnableRoutingMethodW TEXTEQU <__imp_FaxEnableRoutingMethodW>
extern __imp_FaxEnumGlobalRoutingInfoA:PANYARGS
FaxEnumGlobalRoutingInfo  TEXTEQU <__imp_FaxEnumGlobalRoutingInfoA>
extern __imp_FaxEnumGlobalRoutingInfoW:PANYARGS
FaxEnumGlobalRoutingInfoW TEXTEQU <__imp_FaxEnumGlobalRoutingInfoW>
extern __imp_FaxEnumJobsA:PANYARGS
FaxEnumJobs  TEXTEQU <__imp_FaxEnumJobsA>
extern __imp_FaxEnumJobsW:PANYARGS
FaxEnumJobsW TEXTEQU <__imp_FaxEnumJobsW>
extern __imp_FaxEnumPortsA:PANYARGS
FaxEnumPorts  TEXTEQU <__imp_FaxEnumPortsA>
extern __imp_FaxEnumPortsW:PANYARGS
FaxEnumPortsW TEXTEQU <__imp_FaxEnumPortsW>
extern __imp_FaxEnumRoutingMethodsA:PANYARGS
FaxEnumRoutingMethods  TEXTEQU <__imp_FaxEnumRoutingMethodsA>
extern __imp_FaxEnumRoutingMethodsW:PANYARGS
FaxEnumRoutingMethodsW TEXTEQU <__imp_FaxEnumRoutingMethodsW>
extern __imp_FaxFreeBuffer:PANYARGS
FaxFreeBuffer TEXTEQU <__imp_FaxFreeBuffer>
extern __imp_FaxGetConfigurationA:PANYARGS
FaxGetConfiguration  TEXTEQU <__imp_FaxGetConfigurationA>
extern __imp_FaxGetConfigurationW:PANYARGS
FaxGetConfigurationW TEXTEQU <__imp_FaxGetConfigurationW>
extern __imp_FaxGetDeviceStatusA:PANYARGS
FaxGetDeviceStatus  TEXTEQU <__imp_FaxGetDeviceStatusA>
extern __imp_FaxGetDeviceStatusW:PANYARGS
FaxGetDeviceStatusW TEXTEQU <__imp_FaxGetDeviceStatusW>
extern __imp_FaxGetJobA:PANYARGS
FaxGetJob  TEXTEQU <__imp_FaxGetJobA>
extern __imp_FaxGetJobW:PANYARGS
FaxGetJobW TEXTEQU <__imp_FaxGetJobW>
extern __imp_FaxGetLoggingCategoriesA:PANYARGS
FaxGetLoggingCategories  TEXTEQU <__imp_FaxGetLoggingCategoriesA>
extern __imp_FaxGetLoggingCategoriesW:PANYARGS
FaxGetLoggingCategoriesW TEXTEQU <__imp_FaxGetLoggingCategoriesW>
extern __imp_FaxGetPageData:PANYARGS
FaxGetPageData TEXTEQU <__imp_FaxGetPageData>
extern __imp_FaxGetPortA:PANYARGS
FaxGetPort  TEXTEQU <__imp_FaxGetPortA>
extern __imp_FaxGetPortW:PANYARGS
FaxGetPortW TEXTEQU <__imp_FaxGetPortW>
extern __imp_FaxGetRoutingInfoA:PANYARGS
FaxGetRoutingInfo  TEXTEQU <__imp_FaxGetRoutingInfoA>
extern __imp_FaxGetRoutingInfoW:PANYARGS
FaxGetRoutingInfoW TEXTEQU <__imp_FaxGetRoutingInfoW>
extern __imp_FaxInitializeEventQueue:PANYARGS
FaxInitializeEventQueue TEXTEQU <__imp_FaxInitializeEventQueue>
extern __imp_FaxOpenPort:PANYARGS
FaxOpenPort TEXTEQU <__imp_FaxOpenPort>
extern __imp_FaxPrintCoverPageA:PANYARGS
FaxPrintCoverPage  TEXTEQU <__imp_FaxPrintCoverPageA>
extern __imp_FaxPrintCoverPageW:PANYARGS
FaxPrintCoverPageW TEXTEQU <__imp_FaxPrintCoverPageW>
extern __imp_FaxRegisterRoutingExtensionW:PANYARGS
FaxRegisterRoutingExtensionW TEXTEQU <__imp_FaxRegisterRoutingExtensionW>
extern __imp_FaxRegisterServiceProviderW:PANYARGS
FaxRegisterServiceProviderW TEXTEQU <__imp_FaxRegisterServiceProviderW>
extern __imp_FaxSendDocumentA:PANYARGS
FaxSendDocument  TEXTEQU <__imp_FaxSendDocumentA>
extern __imp_FaxSendDocumentForBroadcastA:PANYARGS
FaxSendDocumentForBroadcast  TEXTEQU <__imp_FaxSendDocumentForBroadcastA>
extern __imp_FaxSendDocumentForBroadcastW:PANYARGS
FaxSendDocumentForBroadcastW TEXTEQU <__imp_FaxSendDocumentForBroadcastW>
extern __imp_FaxSendDocumentW:PANYARGS
FaxSendDocumentW TEXTEQU <__imp_FaxSendDocumentW>
extern __imp_FaxSetConfigurationA:PANYARGS
FaxSetConfiguration  TEXTEQU <__imp_FaxSetConfigurationA>
extern __imp_FaxSetConfigurationW:PANYARGS
FaxSetConfigurationW TEXTEQU <__imp_FaxSetConfigurationW>
extern __imp_FaxSetGlobalRoutingInfoA:PANYARGS
FaxSetGlobalRoutingInfo  TEXTEQU <__imp_FaxSetGlobalRoutingInfoA>
extern __imp_FaxSetGlobalRoutingInfoW:PANYARGS
FaxSetGlobalRoutingInfoW TEXTEQU <__imp_FaxSetGlobalRoutingInfoW>
extern __imp_FaxSetJobA:PANYARGS
FaxSetJob  TEXTEQU <__imp_FaxSetJobA>
extern __imp_FaxSetJobW:PANYARGS
FaxSetJobW TEXTEQU <__imp_FaxSetJobW>
extern __imp_FaxSetLoggingCategoriesA:PANYARGS
FaxSetLoggingCategories  TEXTEQU <__imp_FaxSetLoggingCategoriesA>
extern __imp_FaxSetLoggingCategoriesW:PANYARGS
FaxSetLoggingCategoriesW TEXTEQU <__imp_FaxSetLoggingCategoriesW>
extern __imp_FaxSetPortA:PANYARGS
FaxSetPort  TEXTEQU <__imp_FaxSetPortA>
extern __imp_FaxSetPortW:PANYARGS
FaxSetPortW TEXTEQU <__imp_FaxSetPortW>
extern __imp_FaxSetRoutingInfoA:PANYARGS
FaxSetRoutingInfo  TEXTEQU <__imp_FaxSetRoutingInfoA>
extern __imp_FaxSetRoutingInfoW:PANYARGS
FaxSetRoutingInfoW TEXTEQU <__imp_FaxSetRoutingInfoW>
extern __imp_FaxStartPrintJobA:PANYARGS
FaxStartPrintJob  TEXTEQU <__imp_FaxStartPrintJobA>
extern __imp_FaxStartPrintJobW:PANYARGS
FaxStartPrintJobW TEXTEQU <__imp_FaxStartPrintJobW>
extern __imp_FaxUnregisterServiceProviderW:PANYARGS
FaxUnregisterServiceProviderW TEXTEQU <__imp_FaxUnregisterServiceProviderW>
