extern __imp_SPDApiBufferAllocate:PANYARGS
SPDApiBufferAllocate TEXTEQU <__imp_SPDApiBufferAllocate>
extern __imp_SPDApiBufferFree:PANYARGS
SPDApiBufferFree TEXTEQU <__imp_SPDApiBufferFree>
extern __imp_AddTransportFilter:PANYARGS
AddTransportFilter TEXTEQU <__imp_AddTransportFilter>
extern __imp_DeleteTransportFilter:PANYARGS
DeleteTransportFilter TEXTEQU <__imp_DeleteTransportFilter>
extern __imp_EnumTransportFilters:PANYARGS
EnumTransportFilters TEXTEQU <__imp_EnumTransportFilters>
extern __imp_SetTransportFilter:PANYARGS
SetTransportFilter TEXTEQU <__imp_SetTransportFilter>
extern __imp_GetTransportFilter:PANYARGS
GetTransportFilter TEXTEQU <__imp_GetTransportFilter>
extern __imp_AddQMPolicy:PANYARGS
AddQMPolicy TEXTEQU <__imp_AddQMPolicy>
extern __imp_DeleteQMPolicy:PANYARGS
DeleteQMPolicy TEXTEQU <__imp_DeleteQMPolicy>
extern __imp_EnumQMPolicies:PANYARGS
EnumQMPolicies TEXTEQU <__imp_EnumQMPolicies>
extern __imp_SetQMPolicy:PANYARGS
SetQMPolicy TEXTEQU <__imp_SetQMPolicy>
extern __imp_GetQMPolicy:PANYARGS
GetQMPolicy TEXTEQU <__imp_GetQMPolicy>
extern __imp_AddMMPolicy:PANYARGS
AddMMPolicy TEXTEQU <__imp_AddMMPolicy>
extern __imp_DeleteMMPolicy:PANYARGS
DeleteMMPolicy TEXTEQU <__imp_DeleteMMPolicy>
extern __imp_EnumMMPolicies:PANYARGS
EnumMMPolicies TEXTEQU <__imp_EnumMMPolicies>
extern __imp_SetMMPolicy:PANYARGS
SetMMPolicy TEXTEQU <__imp_SetMMPolicy>
extern __imp_GetMMPolicy:PANYARGS
GetMMPolicy TEXTEQU <__imp_GetMMPolicy>
extern __imp_AddMMFilter:PANYARGS
AddMMFilter TEXTEQU <__imp_AddMMFilter>
extern __imp_DeleteMMFilter:PANYARGS
DeleteMMFilter TEXTEQU <__imp_DeleteMMFilter>
extern __imp_EnumMMFilters:PANYARGS
EnumMMFilters TEXTEQU <__imp_EnumMMFilters>
extern __imp_SetMMFilter:PANYARGS
SetMMFilter TEXTEQU <__imp_SetMMFilter>
extern __imp_GetMMFilter:PANYARGS
GetMMFilter TEXTEQU <__imp_GetMMFilter>
extern __imp_MatchMMFilter:PANYARGS
MatchMMFilter TEXTEQU <__imp_MatchMMFilter>
extern __imp_MatchTransportFilter:PANYARGS
MatchTransportFilter TEXTEQU <__imp_MatchTransportFilter>
extern __imp_GetQMPolicyByID:PANYARGS
GetQMPolicyByID TEXTEQU <__imp_GetQMPolicyByID>
extern __imp_GetMMPolicyByID:PANYARGS
GetMMPolicyByID TEXTEQU <__imp_GetMMPolicyByID>
extern __imp_AddMMAuthMethods:PANYARGS
AddMMAuthMethods TEXTEQU <__imp_AddMMAuthMethods>
extern __imp_DeleteMMAuthMethods:PANYARGS
DeleteMMAuthMethods TEXTEQU <__imp_DeleteMMAuthMethods>
extern __imp_EnumMMAuthMethods:PANYARGS
EnumMMAuthMethods TEXTEQU <__imp_EnumMMAuthMethods>
extern __imp_SetMMAuthMethods:PANYARGS
SetMMAuthMethods TEXTEQU <__imp_SetMMAuthMethods>
extern __imp_GetMMAuthMethods:PANYARGS
GetMMAuthMethods TEXTEQU <__imp_GetMMAuthMethods>
extern __imp_InitiateIKENegotiation:PANYARGS
InitiateIKENegotiation TEXTEQU <__imp_InitiateIKENegotiation>
extern __imp_QueryIKENegotiationStatus:PANYARGS
QueryIKENegotiationStatus TEXTEQU <__imp_QueryIKENegotiationStatus>
extern __imp_CloseIKENegotiationHandle:PANYARGS
CloseIKENegotiationHandle TEXTEQU <__imp_CloseIKENegotiationHandle>
extern __imp_EnumMMSAs:PANYARGS
EnumMMSAs TEXTEQU <__imp_EnumMMSAs>
extern __imp_QueryIKEStatistics:PANYARGS
QueryIKEStatistics TEXTEQU <__imp_QueryIKEStatistics>
extern __imp_DeleteMMSAs:PANYARGS
DeleteMMSAs TEXTEQU <__imp_DeleteMMSAs>
extern __imp_RegisterIKENotifyClient:PANYARGS
RegisterIKENotifyClient TEXTEQU <__imp_RegisterIKENotifyClient>
extern __imp_QueryIKENotifyData:PANYARGS
QueryIKENotifyData TEXTEQU <__imp_QueryIKENotifyData>
extern __imp_CloseIKENotifyHandle:PANYARGS
CloseIKENotifyHandle TEXTEQU <__imp_CloseIKENotifyHandle>
extern __imp_QueryIPSecStatistics:PANYARGS
QueryIPSecStatistics TEXTEQU <__imp_QueryIPSecStatistics>
extern __imp_EnumQMSAs:PANYARGS
EnumQMSAs TEXTEQU <__imp_EnumQMSAs>
extern __imp_AddTunnelFilter:PANYARGS
AddTunnelFilter TEXTEQU <__imp_AddTunnelFilter>
extern __imp_DeleteTunnelFilter:PANYARGS
DeleteTunnelFilter TEXTEQU <__imp_DeleteTunnelFilter>
extern __imp_EnumTunnelFilters:PANYARGS
EnumTunnelFilters TEXTEQU <__imp_EnumTunnelFilters>
extern __imp_SetTunnelFilter:PANYARGS
SetTunnelFilter TEXTEQU <__imp_SetTunnelFilter>
extern __imp_GetTunnelFilter:PANYARGS
GetTunnelFilter TEXTEQU <__imp_GetTunnelFilter>
extern __imp_MatchTunnelFilter:PANYARGS
MatchTunnelFilter TEXTEQU <__imp_MatchTunnelFilter>
extern __imp_OpenMMFilterHandle:PANYARGS
OpenMMFilterHandle TEXTEQU <__imp_OpenMMFilterHandle>
extern __imp_CloseMMFilterHandle:PANYARGS
CloseMMFilterHandle TEXTEQU <__imp_CloseMMFilterHandle>
extern __imp_OpenTransportFilterHandle:PANYARGS
OpenTransportFilterHandle TEXTEQU <__imp_OpenTransportFilterHandle>
extern __imp_CloseTransportFilterHandle:PANYARGS
CloseTransportFilterHandle TEXTEQU <__imp_CloseTransportFilterHandle>
extern __imp_OpenTunnelFilterHandle:PANYARGS
OpenTunnelFilterHandle TEXTEQU <__imp_OpenTunnelFilterHandle>
extern __imp_CloseTunnelFilterHandle:PANYARGS
CloseTunnelFilterHandle TEXTEQU <__imp_CloseTunnelFilterHandle>
extern __imp_EnumIPSecInterfaces:PANYARGS
EnumIPSecInterfaces TEXTEQU <__imp_EnumIPSecInterfaces>
extern __imp_AddSAs:PANYARGS
AddSAs TEXTEQU <__imp_AddSAs>
extern __imp_DeleteQMSAs:PANYARGS
DeleteQMSAs TEXTEQU <__imp_DeleteQMSAs>
extern __imp_GetConfigurationVariables:PANYARGS
GetConfigurationVariables TEXTEQU <__imp_GetConfigurationVariables>
extern __imp_SetConfigurationVariables:PANYARGS
SetConfigurationVariables TEXTEQU <__imp_SetConfigurationVariables>
extern __imp_QuerySpdPolicyState:PANYARGS
QuerySpdPolicyState TEXTEQU <__imp_QuerySpdPolicyState>
extern __imp_OpenIPSecPerformanceData:PANYARGS
OpenIPSecPerformanceData TEXTEQU <__imp_OpenIPSecPerformanceData>
extern __imp_CollectIPSecPerformanceData:PANYARGS
CollectIPSecPerformanceData TEXTEQU <__imp_CollectIPSecPerformanceData>
extern __imp_CloseIPSecPerformanceData:PANYARGS
CloseIPSecPerformanceData TEXTEQU <__imp_CloseIPSecPerformanceData>
extern __imp_SetSddlConfig:PANYARGS
SetSddlConfig TEXTEQU <__imp_SetSddlConfig>
