extern __imp_winmm_ordinal2:PANYARGS
winmm_ordinal2 TEXTEQU <__imp_winmm_ordinal2>
extern __imp_CloseDriver:PANYARGS
CloseDriver TEXTEQU <__imp_CloseDriver>
extern __imp_DefDriverProc:PANYARGS
DefDriverProc TEXTEQU <__imp_DefDriverProc>
extern __imp_DriverCallback:PANYARGS
DriverCallback TEXTEQU <__imp_DriverCallback>
extern __imp_DrvGetModuleHandle:PANYARGS
DrvGetModuleHandle TEXTEQU <__imp_DrvGetModuleHandle>
extern __imp_GetDriverModuleHandle:PANYARGS
GetDriverModuleHandle TEXTEQU <__imp_GetDriverModuleHandle>
extern __imp_MigrateAllDrivers:PANYARGS
MigrateAllDrivers TEXTEQU <__imp_MigrateAllDrivers>
extern __imp_MigrateSoundEvents:PANYARGS
MigrateSoundEvents TEXTEQU <__imp_MigrateSoundEvents>
extern __imp_OpenDriver:PANYARGS
OpenDriver TEXTEQU <__imp_OpenDriver>
extern __imp_PlaySound:PANYARGS
PlaySound TEXTEQU <__imp_PlaySound>
extern __imp_PlaySoundA:PANYARGS
PlaySound  TEXTEQU <__imp_PlaySoundA>
extern __imp_PlaySoundW:PANYARGS
PlaySoundW TEXTEQU <__imp_PlaySoundW>
extern __imp_SendDriverMessage:PANYARGS
SendDriverMessage TEXTEQU <__imp_SendDriverMessage>
extern __imp_WOWAppExit:PANYARGS
WOWAppExit TEXTEQU <__imp_WOWAppExit>
extern __imp_WinmmLogoff:PANYARGS
WinmmLogoff TEXTEQU <__imp_WinmmLogoff>
extern __imp_WinmmLogon:PANYARGS
WinmmLogon TEXTEQU <__imp_WinmmLogon>
extern __imp_auxGetDevCapsA:PANYARGS
auxGetDevCaps  TEXTEQU <__imp_auxGetDevCapsA>
extern __imp_auxGetDevCapsW:PANYARGS
auxGetDevCapsW TEXTEQU <__imp_auxGetDevCapsW>
extern __imp_auxGetNumDevs:PANYARGS
auxGetNumDevs TEXTEQU <__imp_auxGetNumDevs>
extern __imp_auxGetVolume:PANYARGS
auxGetVolume TEXTEQU <__imp_auxGetVolume>
extern __imp_auxOutMessage:PANYARGS
auxOutMessage TEXTEQU <__imp_auxOutMessage>
extern __imp_auxSetVolume:PANYARGS
auxSetVolume TEXTEQU <__imp_auxSetVolume>
extern __imp_gfxAddGfx:PANYARGS
gfxAddGfx TEXTEQU <__imp_gfxAddGfx>
extern __imp_gfxBatchChange:PANYARGS
gfxBatchChange TEXTEQU <__imp_gfxBatchChange>
extern __imp_gfxCreateGfxFactoriesList:PANYARGS
gfxCreateGfxFactoriesList TEXTEQU <__imp_gfxCreateGfxFactoriesList>
extern __imp_gfxCreateZoneFactoriesList:PANYARGS
gfxCreateZoneFactoriesList TEXTEQU <__imp_gfxCreateZoneFactoriesList>
extern __imp_gfxDestroyDeviceInterfaceList:PANYARGS
gfxDestroyDeviceInterfaceList TEXTEQU <__imp_gfxDestroyDeviceInterfaceList>
extern __imp_gfxEnumerateGfxs:PANYARGS
gfxEnumerateGfxs TEXTEQU <__imp_gfxEnumerateGfxs>
extern __imp_gfxLogoff:PANYARGS
gfxLogoff TEXTEQU <__imp_gfxLogoff>
extern __imp_gfxLogon:PANYARGS
gfxLogon TEXTEQU <__imp_gfxLogon>
extern __imp_gfxModifyGfx:PANYARGS
gfxModifyGfx TEXTEQU <__imp_gfxModifyGfx>
extern __imp_gfxOpenGfx:PANYARGS
gfxOpenGfx TEXTEQU <__imp_gfxOpenGfx>
extern __imp_gfxRemoveGfx:PANYARGS
gfxRemoveGfx TEXTEQU <__imp_gfxRemoveGfx>
extern __imp_joyConfigChanged:PANYARGS
joyConfigChanged TEXTEQU <__imp_joyConfigChanged>
extern __imp_joyGetDevCapsA:PANYARGS
joyGetDevCaps  TEXTEQU <__imp_joyGetDevCapsA>
extern __imp_joyGetDevCapsW:PANYARGS
joyGetDevCapsW TEXTEQU <__imp_joyGetDevCapsW>
extern __imp_joyGetNumDevs:PANYARGS
joyGetNumDevs TEXTEQU <__imp_joyGetNumDevs>
extern __imp_joyGetPos:PANYARGS
joyGetPos TEXTEQU <__imp_joyGetPos>
extern __imp_joyGetPosEx:PANYARGS
joyGetPosEx TEXTEQU <__imp_joyGetPosEx>
extern __imp_joyGetThreshold:PANYARGS
joyGetThreshold TEXTEQU <__imp_joyGetThreshold>
extern __imp_joyReleaseCapture:PANYARGS
joyReleaseCapture TEXTEQU <__imp_joyReleaseCapture>
extern __imp_joySetCapture:PANYARGS
joySetCapture TEXTEQU <__imp_joySetCapture>
extern __imp_joySetThreshold:PANYARGS
joySetThreshold TEXTEQU <__imp_joySetThreshold>
extern __imp_mciDriverNotify:PANYARGS
mciDriverNotify TEXTEQU <__imp_mciDriverNotify>
extern __imp_mciDriverYield:PANYARGS
mciDriverYield TEXTEQU <__imp_mciDriverYield>
extern __imp_mciExecute:PANYARGS
mciExecute TEXTEQU <__imp_mciExecute>
extern __imp_mciFreeCommandResource:PANYARGS
mciFreeCommandResource TEXTEQU <__imp_mciFreeCommandResource>
extern __imp_mciGetCreatorTask:PANYARGS
mciGetCreatorTask TEXTEQU <__imp_mciGetCreatorTask>
extern __imp_mciGetDeviceIDA:PANYARGS
mciGetDeviceID  TEXTEQU <__imp_mciGetDeviceIDA>
extern __imp_mciGetDeviceIDFromElementIDA:PANYARGS
mciGetDeviceIDFromElementID  TEXTEQU <__imp_mciGetDeviceIDFromElementIDA>
extern __imp_mciGetDeviceIDFromElementIDW:PANYARGS
mciGetDeviceIDFromElementIDW TEXTEQU <__imp_mciGetDeviceIDFromElementIDW>
extern __imp_mciGetDeviceIDW:PANYARGS
mciGetDeviceIDW TEXTEQU <__imp_mciGetDeviceIDW>
extern __imp_mciGetDriverData:PANYARGS
mciGetDriverData TEXTEQU <__imp_mciGetDriverData>
extern __imp_mciGetErrorStringA:PANYARGS
mciGetErrorString  TEXTEQU <__imp_mciGetErrorStringA>
extern __imp_mciGetErrorStringW:PANYARGS
mciGetErrorStringW TEXTEQU <__imp_mciGetErrorStringW>
extern __imp_mciGetYieldProc:PANYARGS
mciGetYieldProc TEXTEQU <__imp_mciGetYieldProc>
extern __imp_mciLoadCommandResource:PANYARGS
mciLoadCommandResource TEXTEQU <__imp_mciLoadCommandResource>
extern __imp_mciSendCommandA:PANYARGS
mciSendCommand  TEXTEQU <__imp_mciSendCommandA>
extern __imp_mciSendCommandW:PANYARGS
mciSendCommandW TEXTEQU <__imp_mciSendCommandW>
extern __imp_mciSendStringA:PANYARGS
mciSendString  TEXTEQU <__imp_mciSendStringA>
extern __imp_mciSendStringW:PANYARGS
mciSendStringW TEXTEQU <__imp_mciSendStringW>
extern __imp_mciSetDriverData:PANYARGS
mciSetDriverData TEXTEQU <__imp_mciSetDriverData>
extern __imp_mciSetYieldProc:PANYARGS
mciSetYieldProc TEXTEQU <__imp_mciSetYieldProc>
extern __imp_midiConnect:PANYARGS
midiConnect TEXTEQU <__imp_midiConnect>
extern __imp_midiDisconnect:PANYARGS
midiDisconnect TEXTEQU <__imp_midiDisconnect>
extern __imp_midiInAddBuffer:PANYARGS
midiInAddBuffer TEXTEQU <__imp_midiInAddBuffer>
extern __imp_midiInClose:PANYARGS
midiInClose TEXTEQU <__imp_midiInClose>
extern __imp_midiInGetDevCapsA:PANYARGS
midiInGetDevCaps  TEXTEQU <__imp_midiInGetDevCapsA>
extern __imp_midiInGetDevCapsW:PANYARGS
midiInGetDevCapsW TEXTEQU <__imp_midiInGetDevCapsW>
extern __imp_midiInGetErrorTextA:PANYARGS
midiInGetErrorText  TEXTEQU <__imp_midiInGetErrorTextA>
extern __imp_midiInGetErrorTextW:PANYARGS
midiInGetErrorTextW TEXTEQU <__imp_midiInGetErrorTextW>
extern __imp_midiInGetID:PANYARGS
midiInGetID TEXTEQU <__imp_midiInGetID>
extern __imp_midiInGetNumDevs:PANYARGS
midiInGetNumDevs TEXTEQU <__imp_midiInGetNumDevs>
extern __imp_midiInMessage:PANYARGS
midiInMessage TEXTEQU <__imp_midiInMessage>
extern __imp_midiInOpen:PANYARGS
midiInOpen TEXTEQU <__imp_midiInOpen>
extern __imp_midiInPrepareHeader:PANYARGS
midiInPrepareHeader TEXTEQU <__imp_midiInPrepareHeader>
extern __imp_midiInReset:PANYARGS
midiInReset TEXTEQU <__imp_midiInReset>
extern __imp_midiInStart:PANYARGS
midiInStart TEXTEQU <__imp_midiInStart>
extern __imp_midiInStop:PANYARGS
midiInStop TEXTEQU <__imp_midiInStop>
extern __imp_midiInUnprepareHeader:PANYARGS
midiInUnprepareHeader TEXTEQU <__imp_midiInUnprepareHeader>
extern __imp_midiOutCacheDrumPatches:PANYARGS
midiOutCacheDrumPatches TEXTEQU <__imp_midiOutCacheDrumPatches>
extern __imp_midiOutCachePatches:PANYARGS
midiOutCachePatches TEXTEQU <__imp_midiOutCachePatches>
extern __imp_midiOutClose:PANYARGS
midiOutClose TEXTEQU <__imp_midiOutClose>
extern __imp_midiOutGetDevCapsA:PANYARGS
midiOutGetDevCaps  TEXTEQU <__imp_midiOutGetDevCapsA>
extern __imp_midiOutGetDevCapsW:PANYARGS
midiOutGetDevCapsW TEXTEQU <__imp_midiOutGetDevCapsW>
extern __imp_midiOutGetErrorTextA:PANYARGS
midiOutGetErrorText  TEXTEQU <__imp_midiOutGetErrorTextA>
extern __imp_midiOutGetErrorTextW:PANYARGS
midiOutGetErrorTextW TEXTEQU <__imp_midiOutGetErrorTextW>
extern __imp_midiOutGetID:PANYARGS
midiOutGetID TEXTEQU <__imp_midiOutGetID>
extern __imp_midiOutGetNumDevs:PANYARGS
midiOutGetNumDevs TEXTEQU <__imp_midiOutGetNumDevs>
extern __imp_midiOutGetVolume:PANYARGS
midiOutGetVolume TEXTEQU <__imp_midiOutGetVolume>
extern __imp_midiOutLongMsg:PANYARGS
midiOutLongMsg TEXTEQU <__imp_midiOutLongMsg>
extern __imp_midiOutMessage:PANYARGS
midiOutMessage TEXTEQU <__imp_midiOutMessage>
extern __imp_midiOutOpen:PANYARGS
midiOutOpen TEXTEQU <__imp_midiOutOpen>
extern __imp_midiOutPrepareHeader:PANYARGS
midiOutPrepareHeader TEXTEQU <__imp_midiOutPrepareHeader>
extern __imp_midiOutReset:PANYARGS
midiOutReset TEXTEQU <__imp_midiOutReset>
extern __imp_midiOutSetVolume:PANYARGS
midiOutSetVolume TEXTEQU <__imp_midiOutSetVolume>
extern __imp_midiOutShortMsg:PANYARGS
midiOutShortMsg TEXTEQU <__imp_midiOutShortMsg>
extern __imp_midiOutUnprepareHeader:PANYARGS
midiOutUnprepareHeader TEXTEQU <__imp_midiOutUnprepareHeader>
extern __imp_midiStreamClose:PANYARGS
midiStreamClose TEXTEQU <__imp_midiStreamClose>
extern __imp_midiStreamOpen:PANYARGS
midiStreamOpen TEXTEQU <__imp_midiStreamOpen>
extern __imp_midiStreamOut:PANYARGS
midiStreamOut TEXTEQU <__imp_midiStreamOut>
extern __imp_midiStreamPause:PANYARGS
midiStreamPause TEXTEQU <__imp_midiStreamPause>
extern __imp_midiStreamPosition:PANYARGS
midiStreamPosition TEXTEQU <__imp_midiStreamPosition>
extern __imp_midiStreamProperty:PANYARGS
midiStreamProperty TEXTEQU <__imp_midiStreamProperty>
extern __imp_midiStreamRestart:PANYARGS
midiStreamRestart TEXTEQU <__imp_midiStreamRestart>
extern __imp_midiStreamStop:PANYARGS
midiStreamStop TEXTEQU <__imp_midiStreamStop>
extern __imp_mixerClose:PANYARGS
mixerClose TEXTEQU <__imp_mixerClose>
extern __imp_mixerGetControlDetailsA:PANYARGS
mixerGetControlDetails  TEXTEQU <__imp_mixerGetControlDetailsA>
extern __imp_mixerGetControlDetailsW:PANYARGS
mixerGetControlDetailsW TEXTEQU <__imp_mixerGetControlDetailsW>
extern __imp_mixerGetDevCapsA:PANYARGS
mixerGetDevCaps  TEXTEQU <__imp_mixerGetDevCapsA>
extern __imp_mixerGetDevCapsW:PANYARGS
mixerGetDevCapsW TEXTEQU <__imp_mixerGetDevCapsW>
extern __imp_mixerGetID:PANYARGS
mixerGetID TEXTEQU <__imp_mixerGetID>
extern __imp_mixerGetLineControlsA:PANYARGS
mixerGetLineControls  TEXTEQU <__imp_mixerGetLineControlsA>
extern __imp_mixerGetLineControlsW:PANYARGS
mixerGetLineControlsW TEXTEQU <__imp_mixerGetLineControlsW>
extern __imp_mixerGetLineInfoA:PANYARGS
mixerGetLineInfo  TEXTEQU <__imp_mixerGetLineInfoA>
extern __imp_mixerGetLineInfoW:PANYARGS
mixerGetLineInfoW TEXTEQU <__imp_mixerGetLineInfoW>
extern __imp_mixerGetNumDevs:PANYARGS
mixerGetNumDevs TEXTEQU <__imp_mixerGetNumDevs>
extern __imp_mixerMessage:PANYARGS
mixerMessage TEXTEQU <__imp_mixerMessage>
extern __imp_mixerOpen:PANYARGS
mixerOpen TEXTEQU <__imp_mixerOpen>
extern __imp_mixerSetControlDetails:PANYARGS
mixerSetControlDetails TEXTEQU <__imp_mixerSetControlDetails>
extern __imp_mmDrvInstall:PANYARGS
mmDrvInstall TEXTEQU <__imp_mmDrvInstall>
extern __imp_mmGetCurrentTask:PANYARGS
mmGetCurrentTask TEXTEQU <__imp_mmGetCurrentTask>
extern __imp_mmTaskBlock:PANYARGS
mmTaskBlock TEXTEQU <__imp_mmTaskBlock>
extern __imp_mmTaskCreate:PANYARGS
mmTaskCreate TEXTEQU <__imp_mmTaskCreate>
extern __imp_mmTaskSignal:PANYARGS
mmTaskSignal TEXTEQU <__imp_mmTaskSignal>
extern __imp_mmTaskYield:PANYARGS
mmTaskYield TEXTEQU <__imp_mmTaskYield>
extern __imp_mmioAdvance:PANYARGS
mmioAdvance TEXTEQU <__imp_mmioAdvance>
extern __imp_mmioAscend:PANYARGS
mmioAscend TEXTEQU <__imp_mmioAscend>
extern __imp_mmioClose:PANYARGS
mmioClose TEXTEQU <__imp_mmioClose>
extern __imp_mmioCreateChunk:PANYARGS
mmioCreateChunk TEXTEQU <__imp_mmioCreateChunk>
extern __imp_mmioDescend:PANYARGS
mmioDescend TEXTEQU <__imp_mmioDescend>
extern __imp_mmioFlush:PANYARGS
mmioFlush TEXTEQU <__imp_mmioFlush>
extern __imp_mmioGetInfo:PANYARGS
mmioGetInfo TEXTEQU <__imp_mmioGetInfo>
extern __imp_mmioInstallIOProcA:PANYARGS
mmioInstallIOProc  TEXTEQU <__imp_mmioInstallIOProcA>
extern __imp_mmioInstallIOProcW:PANYARGS
mmioInstallIOProcW TEXTEQU <__imp_mmioInstallIOProcW>
extern __imp_mmioOpenA:PANYARGS
mmioOpen  TEXTEQU <__imp_mmioOpenA>
extern __imp_mmioOpenW:PANYARGS
mmioOpenW TEXTEQU <__imp_mmioOpenW>
extern __imp_mmioRead:PANYARGS
mmioRead TEXTEQU <__imp_mmioRead>
extern __imp_mmioRenameA:PANYARGS
mmioRename  TEXTEQU <__imp_mmioRenameA>
extern __imp_mmioRenameW:PANYARGS
mmioRenameW TEXTEQU <__imp_mmioRenameW>
extern __imp_mmioSeek:PANYARGS
mmioSeek TEXTEQU <__imp_mmioSeek>
extern __imp_mmioSendMessage:PANYARGS
mmioSendMessage TEXTEQU <__imp_mmioSendMessage>
extern __imp_mmioSetBuffer:PANYARGS
mmioSetBuffer TEXTEQU <__imp_mmioSetBuffer>
extern __imp_mmioSetInfo:PANYARGS
mmioSetInfo TEXTEQU <__imp_mmioSetInfo>
extern __imp_mmioStringToFOURCCA:PANYARGS
mmioStringToFOURCC  TEXTEQU <__imp_mmioStringToFOURCCA>
extern __imp_mmioStringToFOURCCW:PANYARGS
mmioStringToFOURCCW TEXTEQU <__imp_mmioStringToFOURCCW>
extern __imp_mmioWrite:PANYARGS
mmioWrite TEXTEQU <__imp_mmioWrite>
extern __imp_mmsystemGetVersion:PANYARGS
mmsystemGetVersion TEXTEQU <__imp_mmsystemGetVersion>
extern __imp_sndPlaySoundA:PANYARGS
sndPlaySound  TEXTEQU <__imp_sndPlaySoundA>
extern __imp_sndPlaySoundW:PANYARGS
sndPlaySoundW TEXTEQU <__imp_sndPlaySoundW>
extern __imp_timeBeginPeriod:PANYARGS
timeBeginPeriod TEXTEQU <__imp_timeBeginPeriod>
extern __imp_timeEndPeriod:PANYARGS
timeEndPeriod TEXTEQU <__imp_timeEndPeriod>
extern __imp_timeGetDevCaps:PANYARGS
timeGetDevCaps TEXTEQU <__imp_timeGetDevCaps>
extern __imp_timeGetSystemTime:PANYARGS
timeGetSystemTime TEXTEQU <__imp_timeGetSystemTime>
extern __imp_timeGetTime:PANYARGS
timeGetTime TEXTEQU <__imp_timeGetTime>
extern __imp_timeKillEvent:PANYARGS
timeKillEvent TEXTEQU <__imp_timeKillEvent>
extern __imp_timeSetEvent:PANYARGS
timeSetEvent TEXTEQU <__imp_timeSetEvent>
extern __imp_waveInAddBuffer:PANYARGS
waveInAddBuffer TEXTEQU <__imp_waveInAddBuffer>
extern __imp_waveInClose:PANYARGS
waveInClose TEXTEQU <__imp_waveInClose>
extern __imp_waveInGetDevCapsA:PANYARGS
waveInGetDevCaps  TEXTEQU <__imp_waveInGetDevCapsA>
extern __imp_waveInGetDevCapsW:PANYARGS
waveInGetDevCapsW TEXTEQU <__imp_waveInGetDevCapsW>
extern __imp_waveInGetErrorTextA:PANYARGS
waveInGetErrorText  TEXTEQU <__imp_waveInGetErrorTextA>
extern __imp_waveInGetErrorTextW:PANYARGS
waveInGetErrorTextW TEXTEQU <__imp_waveInGetErrorTextW>
extern __imp_waveInGetID:PANYARGS
waveInGetID TEXTEQU <__imp_waveInGetID>
extern __imp_waveInGetNumDevs:PANYARGS
waveInGetNumDevs TEXTEQU <__imp_waveInGetNumDevs>
extern __imp_waveInGetPosition:PANYARGS
waveInGetPosition TEXTEQU <__imp_waveInGetPosition>
extern __imp_waveInMessage:PANYARGS
waveInMessage TEXTEQU <__imp_waveInMessage>
extern __imp_waveInOpen:PANYARGS
waveInOpen TEXTEQU <__imp_waveInOpen>
extern __imp_waveInPrepareHeader:PANYARGS
waveInPrepareHeader TEXTEQU <__imp_waveInPrepareHeader>
extern __imp_waveInReset:PANYARGS
waveInReset TEXTEQU <__imp_waveInReset>
extern __imp_waveInStart:PANYARGS
waveInStart TEXTEQU <__imp_waveInStart>
extern __imp_waveInStop:PANYARGS
waveInStop TEXTEQU <__imp_waveInStop>
extern __imp_waveInUnprepareHeader:PANYARGS
waveInUnprepareHeader TEXTEQU <__imp_waveInUnprepareHeader>
extern __imp_waveOutBreakLoop:PANYARGS
waveOutBreakLoop TEXTEQU <__imp_waveOutBreakLoop>
extern __imp_waveOutClose:PANYARGS
waveOutClose TEXTEQU <__imp_waveOutClose>
extern __imp_waveOutGetDevCapsA:PANYARGS
waveOutGetDevCaps  TEXTEQU <__imp_waveOutGetDevCapsA>
extern __imp_waveOutGetDevCapsW:PANYARGS
waveOutGetDevCapsW TEXTEQU <__imp_waveOutGetDevCapsW>
extern __imp_waveOutGetErrorTextA:PANYARGS
waveOutGetErrorText  TEXTEQU <__imp_waveOutGetErrorTextA>
extern __imp_waveOutGetErrorTextW:PANYARGS
waveOutGetErrorTextW TEXTEQU <__imp_waveOutGetErrorTextW>
extern __imp_waveOutGetID:PANYARGS
waveOutGetID TEXTEQU <__imp_waveOutGetID>
extern __imp_waveOutGetNumDevs:PANYARGS
waveOutGetNumDevs TEXTEQU <__imp_waveOutGetNumDevs>
extern __imp_waveOutGetPitch:PANYARGS
waveOutGetPitch TEXTEQU <__imp_waveOutGetPitch>
extern __imp_waveOutGetPlaybackRate:PANYARGS
waveOutGetPlaybackRate TEXTEQU <__imp_waveOutGetPlaybackRate>
extern __imp_waveOutGetPosition:PANYARGS
waveOutGetPosition TEXTEQU <__imp_waveOutGetPosition>
extern __imp_waveOutGetVolume:PANYARGS
waveOutGetVolume TEXTEQU <__imp_waveOutGetVolume>
extern __imp_waveOutMessage:PANYARGS
waveOutMessage TEXTEQU <__imp_waveOutMessage>
extern __imp_waveOutOpen:PANYARGS
waveOutOpen TEXTEQU <__imp_waveOutOpen>
extern __imp_waveOutPause:PANYARGS
waveOutPause TEXTEQU <__imp_waveOutPause>
extern __imp_waveOutPrepareHeader:PANYARGS
waveOutPrepareHeader TEXTEQU <__imp_waveOutPrepareHeader>
extern __imp_waveOutReset:PANYARGS
waveOutReset TEXTEQU <__imp_waveOutReset>
extern __imp_waveOutRestart:PANYARGS
waveOutRestart TEXTEQU <__imp_waveOutRestart>
extern __imp_waveOutSetPitch:PANYARGS
waveOutSetPitch TEXTEQU <__imp_waveOutSetPitch>
extern __imp_waveOutSetPlaybackRate:PANYARGS
waveOutSetPlaybackRate TEXTEQU <__imp_waveOutSetPlaybackRate>
extern __imp_waveOutSetVolume:PANYARGS
waveOutSetVolume TEXTEQU <__imp_waveOutSetVolume>
extern __imp_waveOutUnprepareHeader:PANYARGS
waveOutUnprepareHeader TEXTEQU <__imp_waveOutUnprepareHeader>
extern __imp_waveOutWrite:PANYARGS
waveOutWrite TEXTEQU <__imp_waveOutWrite>
extern __imp_winmmDbgOut:PANYARGS
winmmDbgOut TEXTEQU <__imp_winmmDbgOut>
extern __imp_winmmSetDebugLevel:PANYARGS
winmmSetDebugLevel TEXTEQU <__imp_winmmSetDebugLevel>
