extern __imp_BB_Refresh:PANYARGS
BB_Refresh TEXTEQU <__imp_BB_Refresh>
extern __imp_GetBBHwnd:PANYARGS
GetBBHwnd TEXTEQU <__imp_GetBBHwnd>
extern __imp_GetBBMainHwnd:PANYARGS
GetBBMainHwnd TEXTEQU <__imp_GetBBMainHwnd>
extern __imp_GetPanelCount:PANYARGS
GetPanelCount TEXTEQU <__imp_GetPanelCount>
extern __imp_InitBillBoard:PANYARGS
InitBillBoard TEXTEQU <__imp_InitBillBoard>
extern __imp_ProgressGaugeMsg:PANYARGS
ProgressGaugeMsg TEXTEQU <__imp_ProgressGaugeMsg>
extern __imp_SetInfoText:PANYARGS
SetInfoText TEXTEQU <__imp_SetInfoText>
extern __imp_SetProgress:PANYARGS
SetProgress TEXTEQU <__imp_SetProgress>
extern __imp_SetProgressText:PANYARGS
SetProgressText TEXTEQU <__imp_SetProgressText>
extern __imp_SetStep:PANYARGS
SetStep TEXTEQU <__imp_SetStep>
extern __imp_SetTimeEstimate:PANYARGS
SetTimeEstimate TEXTEQU <__imp_SetTimeEstimate>
extern __imp_ShowProgressGaugeWindow:PANYARGS
ShowProgressGaugeWindow TEXTEQU <__imp_ShowProgressGaugeWindow>
extern __imp_StartBillBoard:PANYARGS
StartBillBoard TEXTEQU <__imp_StartBillBoard>
extern __imp_StopBillBoard:PANYARGS
StopBillBoard TEXTEQU <__imp_StopBillBoard>
extern __imp_TermBillBoard:PANYARGS
TermBillBoard TEXTEQU <__imp_TermBillBoard>
