extern __imp_ClassInstall32:PANYARGS
ClassInstall32 TEXTEQU <__imp_ClassInstall32>
extern __imp_SCardAccessNewReaderEvent:PANYARGS
SCardAccessNewReaderEvent TEXTEQU <__imp_SCardAccessNewReaderEvent>
extern __imp_SCardReleaseAllEvents:PANYARGS
SCardReleaseAllEvents TEXTEQU <__imp_SCardReleaseAllEvents>
extern __imp_SCardReleaseNewReaderEvent:PANYARGS
SCardReleaseNewReaderEvent TEXTEQU <__imp_SCardReleaseNewReaderEvent>
extern __imp_SCardAccessStartedEvent:PANYARGS
SCardAccessStartedEvent TEXTEQU <__imp_SCardAccessStartedEvent>
extern __imp_SCardAddReaderToGroupA:PANYARGS
SCardAddReaderToGroup  TEXTEQU <__imp_SCardAddReaderToGroupA>
extern __imp_SCardAddReaderToGroupW:PANYARGS
SCardAddReaderToGroupW TEXTEQU <__imp_SCardAddReaderToGroupW>
extern __imp_SCardBeginTransaction:PANYARGS
SCardBeginTransaction TEXTEQU <__imp_SCardBeginTransaction>
extern __imp_SCardCancel:PANYARGS
SCardCancel TEXTEQU <__imp_SCardCancel>
extern __imp_SCardConnectA:PANYARGS
SCardConnect  TEXTEQU <__imp_SCardConnectA>
extern __imp_SCardConnectW:PANYARGS
SCardConnectW TEXTEQU <__imp_SCardConnectW>
extern __imp_SCardControl:PANYARGS
SCardControl TEXTEQU <__imp_SCardControl>
extern __imp_SCardDisconnect:PANYARGS
SCardDisconnect TEXTEQU <__imp_SCardDisconnect>
extern __imp_SCardEndTransaction:PANYARGS
SCardEndTransaction TEXTEQU <__imp_SCardEndTransaction>
extern __imp_SCardEstablishContext:PANYARGS
SCardEstablishContext TEXTEQU <__imp_SCardEstablishContext>
extern __imp_SCardForgetCardTypeA:PANYARGS
SCardForgetCardType  TEXTEQU <__imp_SCardForgetCardTypeA>
extern __imp_SCardForgetCardTypeW:PANYARGS
SCardForgetCardTypeW TEXTEQU <__imp_SCardForgetCardTypeW>
extern __imp_SCardForgetReaderA:PANYARGS
SCardForgetReader  TEXTEQU <__imp_SCardForgetReaderA>
extern __imp_SCardForgetReaderGroupA:PANYARGS
SCardForgetReaderGroup  TEXTEQU <__imp_SCardForgetReaderGroupA>
extern __imp_SCardForgetReaderGroupW:PANYARGS
SCardForgetReaderGroupW TEXTEQU <__imp_SCardForgetReaderGroupW>
extern __imp_SCardForgetReaderW:PANYARGS
SCardForgetReaderW TEXTEQU <__imp_SCardForgetReaderW>
extern __imp_SCardFreeMemory:PANYARGS
SCardFreeMemory TEXTEQU <__imp_SCardFreeMemory>
extern __imp_SCardGetAttrib:PANYARGS
SCardGetAttrib TEXTEQU <__imp_SCardGetAttrib>
extern __imp_SCardGetCardTypeProviderNameA:PANYARGS
SCardGetCardTypeProviderName  TEXTEQU <__imp_SCardGetCardTypeProviderNameA>
extern __imp_SCardGetCardTypeProviderNameW:PANYARGS
SCardGetCardTypeProviderNameW TEXTEQU <__imp_SCardGetCardTypeProviderNameW>
extern __imp_SCardGetProviderIdA:PANYARGS
SCardGetProviderId  TEXTEQU <__imp_SCardGetProviderIdA>
extern __imp_SCardGetProviderIdW:PANYARGS
SCardGetProviderIdW TEXTEQU <__imp_SCardGetProviderIdW>
extern __imp_SCardGetStatusChangeA:PANYARGS
SCardGetStatusChange  TEXTEQU <__imp_SCardGetStatusChangeA>
extern __imp_SCardGetStatusChangeW:PANYARGS
SCardGetStatusChangeW TEXTEQU <__imp_SCardGetStatusChangeW>
extern __imp_SCardIntroduceCardTypeA:PANYARGS
SCardIntroduceCardType  TEXTEQU <__imp_SCardIntroduceCardTypeA>
extern __imp_SCardIntroduceCardTypeW:PANYARGS
SCardIntroduceCardTypeW TEXTEQU <__imp_SCardIntroduceCardTypeW>
extern __imp_SCardIntroduceReaderA:PANYARGS
SCardIntroduceReader  TEXTEQU <__imp_SCardIntroduceReaderA>
extern __imp_SCardIntroduceReaderGroupA:PANYARGS
SCardIntroduceReaderGroup  TEXTEQU <__imp_SCardIntroduceReaderGroupA>
extern __imp_SCardIntroduceReaderGroupW:PANYARGS
SCardIntroduceReaderGroupW TEXTEQU <__imp_SCardIntroduceReaderGroupW>
extern __imp_SCardIntroduceReaderW:PANYARGS
SCardIntroduceReaderW TEXTEQU <__imp_SCardIntroduceReaderW>
extern __imp_SCardIsValidContext:PANYARGS
SCardIsValidContext TEXTEQU <__imp_SCardIsValidContext>
extern __imp_SCardListCardsA:PANYARGS
SCardListCards  TEXTEQU <__imp_SCardListCardsA>
extern __imp_SCardListCardsW:PANYARGS
SCardListCardsW TEXTEQU <__imp_SCardListCardsW>
extern __imp_SCardListInterfacesA:PANYARGS
SCardListInterfaces  TEXTEQU <__imp_SCardListInterfacesA>
extern __imp_SCardListInterfacesW:PANYARGS
SCardListInterfacesW TEXTEQU <__imp_SCardListInterfacesW>
extern __imp_SCardListReaderGroupsA:PANYARGS
SCardListReaderGroups  TEXTEQU <__imp_SCardListReaderGroupsA>
extern __imp_SCardListReaderGroupsW:PANYARGS
SCardListReaderGroupsW TEXTEQU <__imp_SCardListReaderGroupsW>
extern __imp_SCardListReadersA:PANYARGS
SCardListReaders  TEXTEQU <__imp_SCardListReadersA>
extern __imp_SCardListReadersW:PANYARGS
SCardListReadersW TEXTEQU <__imp_SCardListReadersW>
extern __imp_SCardLocateCardsA:PANYARGS
SCardLocateCards  TEXTEQU <__imp_SCardLocateCardsA>
extern __imp_SCardLocateCardsByATRA:PANYARGS
SCardLocateCardsByATR  TEXTEQU <__imp_SCardLocateCardsByATRA>
extern __imp_SCardLocateCardsByATRW:PANYARGS
SCardLocateCardsByATRW TEXTEQU <__imp_SCardLocateCardsByATRW>
extern __imp_SCardLocateCardsW:PANYARGS
SCardLocateCardsW TEXTEQU <__imp_SCardLocateCardsW>
extern __imp_SCardReconnect:PANYARGS
SCardReconnect TEXTEQU <__imp_SCardReconnect>
extern __imp_SCardReleaseContext:PANYARGS
SCardReleaseContext TEXTEQU <__imp_SCardReleaseContext>
extern __imp_SCardReleaseStartedEvent:PANYARGS
SCardReleaseStartedEvent TEXTEQU <__imp_SCardReleaseStartedEvent>
extern __imp_SCardRemoveReaderFromGroupA:PANYARGS
SCardRemoveReaderFromGroup  TEXTEQU <__imp_SCardRemoveReaderFromGroupA>
extern __imp_SCardRemoveReaderFromGroupW:PANYARGS
SCardRemoveReaderFromGroupW TEXTEQU <__imp_SCardRemoveReaderFromGroupW>
extern __imp_SCardSetAttrib:PANYARGS
SCardSetAttrib TEXTEQU <__imp_SCardSetAttrib>
extern __imp_SCardSetCardTypeProviderNameA:PANYARGS
SCardSetCardTypeProviderName  TEXTEQU <__imp_SCardSetCardTypeProviderNameA>
extern __imp_SCardSetCardTypeProviderNameW:PANYARGS
SCardSetCardTypeProviderNameW TEXTEQU <__imp_SCardSetCardTypeProviderNameW>
extern __imp_SCardState:PANYARGS
SCardState TEXTEQU <__imp_SCardState>
extern __imp_SCardStatusA:PANYARGS
SCardStatus  TEXTEQU <__imp_SCardStatusA>
extern __imp_SCardStatusW:PANYARGS
SCardStatusW TEXTEQU <__imp_SCardStatusW>
extern __imp_SCardTransmit:PANYARGS
SCardTransmit TEXTEQU <__imp_SCardTransmit>
extern __imp_g_rgSCardRawPci:PANYARGS
g_rgSCardRawPci TEXTEQU <__imp_g_rgSCardRawPci>
extern __imp_g_rgSCardT0Pci:PANYARGS
g_rgSCardT0Pci TEXTEQU <__imp_g_rgSCardT0Pci>
extern __imp_g_rgSCardT1Pci:PANYARGS
g_rgSCardT1Pci TEXTEQU <__imp_g_rgSCardT1Pci>
