extern __imp_ldap_abandon:PANYARGS
ldap_abandon TEXTEQU <__imp_ldap_abandon>
extern __imp_ldap_add:PANYARGS
ldap_add TEXTEQU <__imp_ldap_add>
extern __imp_ldap_get_optionW:PANYARGS
ldap_get_optionW TEXTEQU <__imp_ldap_get_optionW>
extern __imp_ldap_unbind:PANYARGS
ldap_unbind TEXTEQU <__imp_ldap_unbind>
extern __imp_ldap_set_optionW:PANYARGS
ldap_set_optionW TEXTEQU <__imp_ldap_set_optionW>
extern __imp_wldap32_ordinal15:PANYARGS
wldap32_ordinal15 TEXTEQU <__imp_wldap32_ordinal15>
extern __imp_LdapGetLastError:PANYARGS
LdapGetLastError TEXTEQU <__imp_LdapGetLastError>
extern __imp_cldap_open:PANYARGS
cldap_open TEXTEQU <__imp_cldap_open>
extern __imp_LdapMapErrorToWin32:PANYARGS
LdapMapErrorToWin32 TEXTEQU <__imp_LdapMapErrorToWin32>
extern __imp_ldap_compare:PANYARGS
ldap_compare TEXTEQU <__imp_ldap_compare>
extern __imp_ldap_delete:PANYARGS
ldap_delete TEXTEQU <__imp_ldap_delete>
extern __imp_ldap_result2error:PANYARGS
ldap_result2error TEXTEQU <__imp_ldap_result2error>
extern __imp_ldap_err2string:PANYARGS
ldap_err2string TEXTEQU <__imp_ldap_err2string>
extern __imp_ldap_modify:PANYARGS
ldap_modify TEXTEQU <__imp_ldap_modify>
extern __imp_ldap_modrdn:PANYARGS
ldap_modrdn TEXTEQU <__imp_ldap_modrdn>
extern __imp_ldap_open:PANYARGS
ldap_open TEXTEQU <__imp_ldap_open>
extern __imp_ldap_first_entry:PANYARGS
ldap_first_entry TEXTEQU <__imp_ldap_first_entry>
extern __imp_ldap_next_entry:PANYARGS
ldap_next_entry TEXTEQU <__imp_ldap_next_entry>
extern __imp_cldap_openW:PANYARGS
cldap_openW TEXTEQU <__imp_cldap_openW>
extern __imp_LdapUTF8ToUnicode:PANYARGS
LdapUTF8ToUnicode TEXTEQU <__imp_LdapUTF8ToUnicode>
extern __imp_ldap_get_dn:PANYARGS
ldap_get_dn TEXTEQU <__imp_ldap_get_dn>
extern __imp_ldap_dn2ufn:PANYARGS
ldap_dn2ufn TEXTEQU <__imp_ldap_dn2ufn>
extern __imp_ldap_first_attribute:PANYARGS
ldap_first_attribute TEXTEQU <__imp_ldap_first_attribute>
extern __imp_ldap_next_attribute:PANYARGS
ldap_next_attribute TEXTEQU <__imp_ldap_next_attribute>
extern __imp_ldap_get_values:PANYARGS
ldap_get_values TEXTEQU <__imp_ldap_get_values>
extern __imp_ldap_get_values_len:PANYARGS
ldap_get_values_len TEXTEQU <__imp_ldap_get_values_len>
extern __imp_ldap_count_entries:PANYARGS
ldap_count_entries TEXTEQU <__imp_ldap_count_entries>
extern __imp_ldap_count_values:PANYARGS
ldap_count_values TEXTEQU <__imp_ldap_count_values>
extern __imp_ldap_value_free:PANYARGS
ldap_value_free TEXTEQU <__imp_ldap_value_free>
extern __imp_ldap_explode_dn:PANYARGS
ldap_explode_dn TEXTEQU <__imp_ldap_explode_dn>
extern __imp_ldap_result:PANYARGS
ldap_result TEXTEQU <__imp_ldap_result>
extern __imp_ldap_msgfree:PANYARGS
ldap_msgfree TEXTEQU <__imp_ldap_msgfree>
extern __imp_ldap_addW:PANYARGS
ldap_addW TEXTEQU <__imp_ldap_addW>
extern __imp_ldap_search:PANYARGS
ldap_search TEXTEQU <__imp_ldap_search>
extern __imp_ldap_add_s:PANYARGS
ldap_add_s TEXTEQU <__imp_ldap_add_s>
extern __imp_ldap_bind_s:PANYARGS
ldap_bind_s TEXTEQU <__imp_ldap_bind_s>
extern __imp_ldap_unbind_s:PANYARGS
ldap_unbind_s TEXTEQU <__imp_ldap_unbind_s>
extern __imp_ldap_delete_s:PANYARGS
ldap_delete_s TEXTEQU <__imp_ldap_delete_s>
extern __imp_ldap_modify_s:PANYARGS
ldap_modify_s TEXTEQU <__imp_ldap_modify_s>
extern __imp_ldap_modrdn_s:PANYARGS
ldap_modrdn_s TEXTEQU <__imp_ldap_modrdn_s>
extern __imp_ldap_search_s:PANYARGS
ldap_search_s TEXTEQU <__imp_ldap_search_s>
extern __imp_ldap_search_st:PANYARGS
ldap_search_st TEXTEQU <__imp_ldap_search_st>
extern __imp_ldap_compare_s:PANYARGS
ldap_compare_s TEXTEQU <__imp_ldap_compare_s>
extern __imp_LdapUnicodeToUTF8:PANYARGS
LdapUnicodeToUTF8 TEXTEQU <__imp_LdapUnicodeToUTF8>
extern __imp_ber_bvfree:PANYARGS
ber_bvfree TEXTEQU <__imp_ber_bvfree>
extern __imp_cldap_openA:PANYARGS
cldap_open  TEXTEQU <__imp_cldap_openA>
extern __imp_ldap_addA:PANYARGS
ldap_add  TEXTEQU <__imp_ldap_addA>
extern __imp_ldap_add_ext:PANYARGS
ldap_add_ext TEXTEQU <__imp_ldap_add_ext>
extern __imp_ldap_add_extA:PANYARGS
ldap_add_ext  TEXTEQU <__imp_ldap_add_extA>
extern __imp_ldap_simple_bind:PANYARGS
ldap_simple_bind TEXTEQU <__imp_ldap_simple_bind>
extern __imp_ldap_simple_bind_s:PANYARGS
ldap_simple_bind_s TEXTEQU <__imp_ldap_simple_bind_s>
extern __imp_ldap_bind:PANYARGS
ldap_bind TEXTEQU <__imp_ldap_bind>
extern __imp_ldap_add_extW:PANYARGS
ldap_add_extW TEXTEQU <__imp_ldap_add_extW>
extern __imp_ldap_add_ext_s:PANYARGS
ldap_add_ext_s TEXTEQU <__imp_ldap_add_ext_s>
extern __imp_ldap_add_ext_sA:PANYARGS
ldap_add_ext_s  TEXTEQU <__imp_ldap_add_ext_sA>
extern __imp_ldap_add_ext_sW:PANYARGS
ldap_add_ext_sW TEXTEQU <__imp_ldap_add_ext_sW>
extern __imp_ldap_add_sA:PANYARGS
ldap_add_s  TEXTEQU <__imp_ldap_add_sA>
extern __imp_ldap_modrdn2:PANYARGS
ldap_modrdn2 TEXTEQU <__imp_ldap_modrdn2>
extern __imp_ldap_modrdn2_s:PANYARGS
ldap_modrdn2_s TEXTEQU <__imp_ldap_modrdn2_s>
extern __imp_ldap_add_sW:PANYARGS
ldap_add_sW TEXTEQU <__imp_ldap_add_sW>
extern __imp_ldap_bindA:PANYARGS
ldap_bind  TEXTEQU <__imp_ldap_bindA>
extern __imp_ldap_bindW:PANYARGS
ldap_bindW TEXTEQU <__imp_ldap_bindW>
extern __imp_ldap_bind_sA:PANYARGS
ldap_bind_s  TEXTEQU <__imp_ldap_bind_sA>
extern __imp_ldap_bind_sW:PANYARGS
ldap_bind_sW TEXTEQU <__imp_ldap_bind_sW>
extern __imp_ldap_close_extended_op:PANYARGS
ldap_close_extended_op TEXTEQU <__imp_ldap_close_extended_op>
extern __imp_ldap_compareA:PANYARGS
ldap_compare  TEXTEQU <__imp_ldap_compareA>
extern __imp_ldap_compareW:PANYARGS
ldap_compareW TEXTEQU <__imp_ldap_compareW>
extern __imp_ldap_count_values_len:PANYARGS
ldap_count_values_len TEXTEQU <__imp_ldap_count_values_len>
extern __imp_ldap_compare_ext:PANYARGS
ldap_compare_ext TEXTEQU <__imp_ldap_compare_ext>
extern __imp_ldap_value_free_len:PANYARGS
ldap_value_free_len TEXTEQU <__imp_ldap_value_free_len>
extern __imp_ldap_compare_extA:PANYARGS
ldap_compare_ext  TEXTEQU <__imp_ldap_compare_extA>
extern __imp_ldap_compare_extW:PANYARGS
ldap_compare_extW TEXTEQU <__imp_ldap_compare_extW>
extern __imp_ldap_perror:PANYARGS
ldap_perror TEXTEQU <__imp_ldap_perror>
extern __imp_ldap_compare_ext_s:PANYARGS
ldap_compare_ext_s TEXTEQU <__imp_ldap_compare_ext_s>
extern __imp_ldap_compare_ext_sA:PANYARGS
ldap_compare_ext_s  TEXTEQU <__imp_ldap_compare_ext_sA>
extern __imp_ldap_compare_ext_sW:PANYARGS
ldap_compare_ext_sW TEXTEQU <__imp_ldap_compare_ext_sW>
extern __imp_ldap_compare_sA:PANYARGS
ldap_compare_s  TEXTEQU <__imp_ldap_compare_sA>
extern __imp_ldap_compare_sW:PANYARGS
ldap_compare_sW TEXTEQU <__imp_ldap_compare_sW>
extern __imp_ldap_connect:PANYARGS
ldap_connect TEXTEQU <__imp_ldap_connect>
extern __imp_ldap_control_free:PANYARGS
ldap_control_free TEXTEQU <__imp_ldap_control_free>
extern __imp_ldap_control_freeA:PANYARGS
ldap_control_free  TEXTEQU <__imp_ldap_control_freeA>
extern __imp_ldap_control_freeW:PANYARGS
ldap_control_freeW TEXTEQU <__imp_ldap_control_freeW>
extern __imp_ldap_controls_free:PANYARGS
ldap_controls_free TEXTEQU <__imp_ldap_controls_free>
extern __imp_ldap_controls_freeA:PANYARGS
ldap_controls_free  TEXTEQU <__imp_ldap_controls_freeA>
extern __imp_ldap_controls_freeW:PANYARGS
ldap_controls_freeW TEXTEQU <__imp_ldap_controls_freeW>
extern __imp_ldap_count_references:PANYARGS
ldap_count_references TEXTEQU <__imp_ldap_count_references>
extern __imp_ldap_count_valuesA:PANYARGS
ldap_count_values  TEXTEQU <__imp_ldap_count_valuesA>
extern __imp_ldap_count_valuesW:PANYARGS
ldap_count_valuesW TEXTEQU <__imp_ldap_count_valuesW>
extern __imp_ldap_create_page_control:PANYARGS
ldap_create_page_control TEXTEQU <__imp_ldap_create_page_control>
extern __imp_ldap_create_page_controlA:PANYARGS
ldap_create_page_control  TEXTEQU <__imp_ldap_create_page_controlA>
extern __imp_ldap_create_page_controlW:PANYARGS
ldap_create_page_controlW TEXTEQU <__imp_ldap_create_page_controlW>
extern __imp_ldap_create_sort_control:PANYARGS
ldap_create_sort_control TEXTEQU <__imp_ldap_create_sort_control>
extern __imp_ldap_create_sort_controlA:PANYARGS
ldap_create_sort_control  TEXTEQU <__imp_ldap_create_sort_controlA>
extern __imp_ldap_create_sort_controlW:PANYARGS
ldap_create_sort_controlW TEXTEQU <__imp_ldap_create_sort_controlW>
extern __imp_ldap_deleteA:PANYARGS
ldap_delete  TEXTEQU <__imp_ldap_deleteA>
extern __imp_ldap_deleteW:PANYARGS
ldap_deleteW TEXTEQU <__imp_ldap_deleteW>
extern __imp_ldap_delete_ext:PANYARGS
ldap_delete_ext TEXTEQU <__imp_ldap_delete_ext>
extern __imp_ldap_delete_extA:PANYARGS
ldap_delete_ext  TEXTEQU <__imp_ldap_delete_extA>
extern __imp_ldap_delete_extW:PANYARGS
ldap_delete_extW TEXTEQU <__imp_ldap_delete_extW>
extern __imp_ldap_delete_ext_s:PANYARGS
ldap_delete_ext_s TEXTEQU <__imp_ldap_delete_ext_s>
extern __imp_ldap_delete_ext_sA:PANYARGS
ldap_delete_ext_s  TEXTEQU <__imp_ldap_delete_ext_sA>
extern __imp_ldap_delete_ext_sW:PANYARGS
ldap_delete_ext_sW TEXTEQU <__imp_ldap_delete_ext_sW>
extern __imp_ldap_delete_sA:PANYARGS
ldap_delete_s  TEXTEQU <__imp_ldap_delete_sA>
extern __imp_ldap_delete_sW:PANYARGS
ldap_delete_sW TEXTEQU <__imp_ldap_delete_sW>
extern __imp_ldap_dn2ufnW:PANYARGS
ldap_dn2ufnW TEXTEQU <__imp_ldap_dn2ufnW>
extern __imp_ldap_encode_sort_controlA:PANYARGS
ldap_encode_sort_control  TEXTEQU <__imp_ldap_encode_sort_controlA>
extern __imp_ldap_encode_sort_controlW:PANYARGS
ldap_encode_sort_controlW TEXTEQU <__imp_ldap_encode_sort_controlW>
extern __imp_ldap_err2stringA:PANYARGS
ldap_err2string  TEXTEQU <__imp_ldap_err2stringA>
extern __imp_ldap_err2stringW:PANYARGS
ldap_err2stringW TEXTEQU <__imp_ldap_err2stringW>
extern __imp_ldap_escape_filter_elementA:PANYARGS
ldap_escape_filter_element  TEXTEQU <__imp_ldap_escape_filter_elementA>
extern __imp_ldap_escape_filter_elementW:PANYARGS
ldap_escape_filter_elementW TEXTEQU <__imp_ldap_escape_filter_elementW>
extern __imp_ldap_explode_dnA:PANYARGS
ldap_explode_dn  TEXTEQU <__imp_ldap_explode_dnA>
extern __imp_ldap_explode_dnW:PANYARGS
ldap_explode_dnW TEXTEQU <__imp_ldap_explode_dnW>
extern __imp_ldap_extended_operation:PANYARGS
ldap_extended_operation TEXTEQU <__imp_ldap_extended_operation>
extern __imp_ldap_extended_operationA:PANYARGS
ldap_extended_operation  TEXTEQU <__imp_ldap_extended_operationA>
extern __imp_ldap_extended_operationW:PANYARGS
ldap_extended_operationW TEXTEQU <__imp_ldap_extended_operationW>
extern __imp_ldap_first_attributeA:PANYARGS
ldap_first_attribute  TEXTEQU <__imp_ldap_first_attributeA>
extern __imp_ldap_first_attributeW:PANYARGS
ldap_first_attributeW TEXTEQU <__imp_ldap_first_attributeW>
extern __imp_ldap_first_reference:PANYARGS
ldap_first_reference TEXTEQU <__imp_ldap_first_reference>
extern __imp_ldap_free_controls:PANYARGS
ldap_free_controls TEXTEQU <__imp_ldap_free_controls>
extern __imp_ldap_free_controlsA:PANYARGS
ldap_free_controls  TEXTEQU <__imp_ldap_free_controlsA>
extern __imp_ldap_free_controlsW:PANYARGS
ldap_free_controlsW TEXTEQU <__imp_ldap_free_controlsW>
extern __imp_ldap_get_dnA:PANYARGS
ldap_get_dn  TEXTEQU <__imp_ldap_get_dnA>
extern __imp_ldap_get_dnW:PANYARGS
ldap_get_dnW TEXTEQU <__imp_ldap_get_dnW>
extern __imp_ldap_get_next_page:PANYARGS
ldap_get_next_page TEXTEQU <__imp_ldap_get_next_page>
extern __imp_ldap_get_next_page_s:PANYARGS
ldap_get_next_page_s TEXTEQU <__imp_ldap_get_next_page_s>
extern __imp_ldap_get_option:PANYARGS
ldap_get_option TEXTEQU <__imp_ldap_get_option>
extern __imp_ldap_get_optionA:PANYARGS
ldap_get_option  TEXTEQU <__imp_ldap_get_optionA>
extern __imp_ldap_get_paged_count:PANYARGS
ldap_get_paged_count TEXTEQU <__imp_ldap_get_paged_count>
extern __imp_ldap_get_valuesA:PANYARGS
ldap_get_values  TEXTEQU <__imp_ldap_get_valuesA>
extern __imp_ldap_get_valuesW:PANYARGS
ldap_get_valuesW TEXTEQU <__imp_ldap_get_valuesW>
extern __imp_ldap_get_values_lenA:PANYARGS
ldap_get_values_len  TEXTEQU <__imp_ldap_get_values_lenA>
extern __imp_ldap_get_values_lenW:PANYARGS
ldap_get_values_lenW TEXTEQU <__imp_ldap_get_values_lenW>
extern __imp_ldap_init:PANYARGS
ldap_init TEXTEQU <__imp_ldap_init>
extern __imp_ldap_initA:PANYARGS
ldap_init  TEXTEQU <__imp_ldap_initA>
extern __imp_ldap_initW:PANYARGS
ldap_initW TEXTEQU <__imp_ldap_initW>
extern __imp_ldap_memfreeA:PANYARGS
ldap_memfree  TEXTEQU <__imp_ldap_memfreeA>
extern __imp_ldap_memfreeW:PANYARGS
ldap_memfreeW TEXTEQU <__imp_ldap_memfreeW>
extern __imp_ldap_modifyA:PANYARGS
ldap_modify  TEXTEQU <__imp_ldap_modifyA>
extern __imp_ldap_modifyW:PANYARGS
ldap_modifyW TEXTEQU <__imp_ldap_modifyW>
extern __imp_ldap_modify_ext:PANYARGS
ldap_modify_ext TEXTEQU <__imp_ldap_modify_ext>
extern __imp_ldap_modify_extA:PANYARGS
ldap_modify_ext  TEXTEQU <__imp_ldap_modify_extA>
extern __imp_ldap_modify_extW:PANYARGS
ldap_modify_extW TEXTEQU <__imp_ldap_modify_extW>
extern __imp_ldap_modify_ext_s:PANYARGS
ldap_modify_ext_s TEXTEQU <__imp_ldap_modify_ext_s>
extern __imp_ldap_modify_ext_sA:PANYARGS
ldap_modify_ext_s  TEXTEQU <__imp_ldap_modify_ext_sA>
extern __imp_ldap_modify_ext_sW:PANYARGS
ldap_modify_ext_sW TEXTEQU <__imp_ldap_modify_ext_sW>
extern __imp_ldap_modify_sA:PANYARGS
ldap_modify_s  TEXTEQU <__imp_ldap_modify_sA>
extern __imp_ldap_modify_sW:PANYARGS
ldap_modify_sW TEXTEQU <__imp_ldap_modify_sW>
extern __imp_ldap_modrdn2A:PANYARGS
ldap_modrdn2  TEXTEQU <__imp_ldap_modrdn2A>
extern __imp_ldap_modrdn2W:PANYARGS
ldap_modrdn2W TEXTEQU <__imp_ldap_modrdn2W>
extern __imp_ldap_modrdn2_sA:PANYARGS
ldap_modrdn2_s  TEXTEQU <__imp_ldap_modrdn2_sA>
extern __imp_ldap_modrdn2_sW:PANYARGS
ldap_modrdn2_sW TEXTEQU <__imp_ldap_modrdn2_sW>
extern __imp_ldap_modrdnA:PANYARGS
ldap_modrdn  TEXTEQU <__imp_ldap_modrdnA>
extern __imp_ldap_modrdnW:PANYARGS
ldap_modrdnW TEXTEQU <__imp_ldap_modrdnW>
extern __imp_ldap_modrdn_sA:PANYARGS
ldap_modrdn_s  TEXTEQU <__imp_ldap_modrdn_sA>
extern __imp_ldap_modrdn_sW:PANYARGS
ldap_modrdn_sW TEXTEQU <__imp_ldap_modrdn_sW>
extern __imp_ldap_next_attributeA:PANYARGS
ldap_next_attribute  TEXTEQU <__imp_ldap_next_attributeA>
extern __imp_ldap_next_attributeW:PANYARGS
ldap_next_attributeW TEXTEQU <__imp_ldap_next_attributeW>
extern __imp_ldap_next_reference:PANYARGS
ldap_next_reference TEXTEQU <__imp_ldap_next_reference>
extern __imp_ldap_openA:PANYARGS
ldap_open  TEXTEQU <__imp_ldap_openA>
extern __imp_ldap_openW:PANYARGS
ldap_openW TEXTEQU <__imp_ldap_openW>
extern __imp_ldap_parse_page_control:PANYARGS
ldap_parse_page_control TEXTEQU <__imp_ldap_parse_page_control>
extern __imp_ldap_parse_page_controlA:PANYARGS
ldap_parse_page_control  TEXTEQU <__imp_ldap_parse_page_controlA>
extern __imp_ldap_parse_page_controlW:PANYARGS
ldap_parse_page_controlW TEXTEQU <__imp_ldap_parse_page_controlW>
extern __imp_ldap_parse_reference:PANYARGS
ldap_parse_reference TEXTEQU <__imp_ldap_parse_reference>
extern __imp_ldap_parse_referenceA:PANYARGS
ldap_parse_reference  TEXTEQU <__imp_ldap_parse_referenceA>
extern __imp_ldap_parse_referenceW:PANYARGS
ldap_parse_referenceW TEXTEQU <__imp_ldap_parse_referenceW>
extern __imp_ldap_parse_result:PANYARGS
ldap_parse_result TEXTEQU <__imp_ldap_parse_result>
extern __imp_ldap_parse_resultA:PANYARGS
ldap_parse_result  TEXTEQU <__imp_ldap_parse_resultA>
extern __imp_ldap_parse_resultW:PANYARGS
ldap_parse_resultW TEXTEQU <__imp_ldap_parse_resultW>
extern __imp_ldap_parse_sort_control:PANYARGS
ldap_parse_sort_control TEXTEQU <__imp_ldap_parse_sort_control>
extern __imp_ldap_parse_sort_controlA:PANYARGS
ldap_parse_sort_control  TEXTEQU <__imp_ldap_parse_sort_controlA>
extern __imp_ldap_parse_sort_controlW:PANYARGS
ldap_parse_sort_controlW TEXTEQU <__imp_ldap_parse_sort_controlW>
extern __imp_ldap_rename_ext:PANYARGS
ldap_rename_ext TEXTEQU <__imp_ldap_rename_ext>
extern __imp_ldap_rename_extA:PANYARGS
ldap_rename_ext  TEXTEQU <__imp_ldap_rename_extA>
extern __imp_ldap_rename_extW:PANYARGS
ldap_rename_extW TEXTEQU <__imp_ldap_rename_extW>
extern __imp_ldap_rename_ext_s:PANYARGS
ldap_rename_ext_s TEXTEQU <__imp_ldap_rename_ext_s>
extern __imp_ldap_rename_ext_sA:PANYARGS
ldap_rename_ext_s  TEXTEQU <__imp_ldap_rename_ext_sA>
extern __imp_ldap_rename_ext_sW:PANYARGS
ldap_rename_ext_sW TEXTEQU <__imp_ldap_rename_ext_sW>
extern __imp_ldap_searchA:PANYARGS
ldap_search  TEXTEQU <__imp_ldap_searchA>
extern __imp_ldap_searchW:PANYARGS
ldap_searchW TEXTEQU <__imp_ldap_searchW>
extern __imp_ldap_search_abandon_page:PANYARGS
ldap_search_abandon_page TEXTEQU <__imp_ldap_search_abandon_page>
extern __imp_ldap_search_ext:PANYARGS
ldap_search_ext TEXTEQU <__imp_ldap_search_ext>
extern __imp_ldap_search_extA:PANYARGS
ldap_search_ext  TEXTEQU <__imp_ldap_search_extA>
extern __imp_ldap_search_extW:PANYARGS
ldap_search_extW TEXTEQU <__imp_ldap_search_extW>
extern __imp_ldap_search_ext_s:PANYARGS
ldap_search_ext_s TEXTEQU <__imp_ldap_search_ext_s>
extern __imp_ldap_search_ext_sA:PANYARGS
ldap_search_ext_s  TEXTEQU <__imp_ldap_search_ext_sA>
extern __imp_ldap_escape_filter_element:PANYARGS
ldap_escape_filter_element TEXTEQU <__imp_ldap_escape_filter_element>
extern __imp_ldap_set_dbg_flags:PANYARGS
ldap_set_dbg_flags TEXTEQU <__imp_ldap_set_dbg_flags>
extern __imp_ldap_set_dbg_routine:PANYARGS
ldap_set_dbg_routine TEXTEQU <__imp_ldap_set_dbg_routine>
extern __imp_ldap_memfree:PANYARGS
ldap_memfree TEXTEQU <__imp_ldap_memfree>
extern __imp_ldap_startup:PANYARGS
ldap_startup TEXTEQU <__imp_ldap_startup>
extern __imp_ldap_cleanup:PANYARGS
ldap_cleanup TEXTEQU <__imp_ldap_cleanup>
extern __imp_ldap_search_ext_sW:PANYARGS
ldap_search_ext_sW TEXTEQU <__imp_ldap_search_ext_sW>
extern __imp_ldap_search_init_page:PANYARGS
ldap_search_init_page TEXTEQU <__imp_ldap_search_init_page>
extern __imp_ldap_search_init_pageA:PANYARGS
ldap_search_init_page  TEXTEQU <__imp_ldap_search_init_pageA>
extern __imp_ldap_search_init_pageW:PANYARGS
ldap_search_init_pageW TEXTEQU <__imp_ldap_search_init_pageW>
extern __imp_ldap_search_sA:PANYARGS
ldap_search_s  TEXTEQU <__imp_ldap_search_sA>
extern __imp_ldap_search_sW:PANYARGS
ldap_search_sW TEXTEQU <__imp_ldap_search_sW>
extern __imp_ldap_search_stA:PANYARGS
ldap_search_st  TEXTEQU <__imp_ldap_search_stA>
extern __imp_ldap_search_stW:PANYARGS
ldap_search_stW TEXTEQU <__imp_ldap_search_stW>
extern __imp_ldap_set_option:PANYARGS
ldap_set_option TEXTEQU <__imp_ldap_set_option>
extern __imp_ldap_set_optionA:PANYARGS
ldap_set_option  TEXTEQU <__imp_ldap_set_optionA>
extern __imp_ldap_simple_bindA:PANYARGS
ldap_simple_bind  TEXTEQU <__imp_ldap_simple_bindA>
extern __imp_ldap_simple_bindW:PANYARGS
ldap_simple_bindW TEXTEQU <__imp_ldap_simple_bindW>
extern __imp_ldap_simple_bind_sA:PANYARGS
ldap_simple_bind_s  TEXTEQU <__imp_ldap_simple_bind_sA>
extern __imp_ldap_simple_bind_sW:PANYARGS
ldap_simple_bind_sW TEXTEQU <__imp_ldap_simple_bind_sW>
extern __imp_ldap_sslinit:PANYARGS
ldap_sslinit TEXTEQU <__imp_ldap_sslinit>
extern __imp_ldap_sslinitA:PANYARGS
ldap_sslinit  TEXTEQU <__imp_ldap_sslinitA>
extern __imp_ldap_sslinitW:PANYARGS
ldap_sslinitW TEXTEQU <__imp_ldap_sslinitW>
extern __imp_ldap_ufn2dn:PANYARGS
ldap_ufn2dn TEXTEQU <__imp_ldap_ufn2dn>
extern __imp_ldap_ufn2dnA:PANYARGS
ldap_ufn2dn  TEXTEQU <__imp_ldap_ufn2dnA>
extern __imp_ldap_ufn2dnW:PANYARGS
ldap_ufn2dnW TEXTEQU <__imp_ldap_ufn2dnW>
extern __imp_ldap_value_freeA:PANYARGS
ldap_value_free  TEXTEQU <__imp_ldap_value_freeA>
extern __imp_ldap_value_freeW:PANYARGS
ldap_value_freeW TEXTEQU <__imp_ldap_value_freeW>
extern __imp_wldap32_ordinal225:PANYARGS
wldap32_ordinal225 TEXTEQU <__imp_wldap32_ordinal225>
extern __imp_wldap32_ordinal226:PANYARGS
wldap32_ordinal226 TEXTEQU <__imp_wldap32_ordinal226>
extern __imp_wldap32_ordinal227:PANYARGS
wldap32_ordinal227 TEXTEQU <__imp_wldap32_ordinal227>
extern __imp_wldap32_ordinal228:PANYARGS
wldap32_ordinal228 TEXTEQU <__imp_wldap32_ordinal228>
extern __imp_wldap32_ordinal229:PANYARGS
wldap32_ordinal229 TEXTEQU <__imp_wldap32_ordinal229>
extern __imp_ldap_check_filterA:PANYARGS
ldap_check_filter  TEXTEQU <__imp_ldap_check_filterA>
extern __imp_ldap_check_filterW:PANYARGS
ldap_check_filterW TEXTEQU <__imp_ldap_check_filterW>
extern __imp_ldap_dn2ufnA:PANYARGS
ldap_dn2ufn  TEXTEQU <__imp_ldap_dn2ufnA>
extern __imp_wldap32_ordinal233:PANYARGS
wldap32_ordinal233 TEXTEQU <__imp_wldap32_ordinal233>
extern __imp_wldap32_ordinal234:PANYARGS
wldap32_ordinal234 TEXTEQU <__imp_wldap32_ordinal234>
extern __imp_wldap32_ordinal235:PANYARGS
wldap32_ordinal235 TEXTEQU <__imp_wldap32_ordinal235>
extern __imp_wldap32_ordinal236:PANYARGS
wldap32_ordinal236 TEXTEQU <__imp_wldap32_ordinal236>
extern __imp_wldap32_ordinal237:PANYARGS
wldap32_ordinal237 TEXTEQU <__imp_wldap32_ordinal237>
extern __imp_wldap32_ordinal238:PANYARGS
wldap32_ordinal238 TEXTEQU <__imp_wldap32_ordinal238>
extern __imp_wldap32_ordinal239:PANYARGS
wldap32_ordinal239 TEXTEQU <__imp_wldap32_ordinal239>
extern __imp_wldap32_ordinal240:PANYARGS
wldap32_ordinal240 TEXTEQU <__imp_wldap32_ordinal240>
extern __imp_wldap32_ordinal241:PANYARGS
wldap32_ordinal241 TEXTEQU <__imp_wldap32_ordinal241>
extern __imp_wldap32_ordinal242:PANYARGS
wldap32_ordinal242 TEXTEQU <__imp_wldap32_ordinal242>
extern __imp_wldap32_ordinal243:PANYARGS
wldap32_ordinal243 TEXTEQU <__imp_wldap32_ordinal243>
extern __imp_wldap32_ordinal244:PANYARGS
wldap32_ordinal244 TEXTEQU <__imp_wldap32_ordinal244>
extern __imp_wldap32_ordinal245:PANYARGS
wldap32_ordinal245 TEXTEQU <__imp_wldap32_ordinal245>
extern __imp_wldap32_ordinal246:PANYARGS
wldap32_ordinal246 TEXTEQU <__imp_wldap32_ordinal246>
extern __imp_wldap32_ordinal247:PANYARGS
wldap32_ordinal247 TEXTEQU <__imp_wldap32_ordinal247>
extern __imp_wldap32_ordinal248:PANYARGS
wldap32_ordinal248 TEXTEQU <__imp_wldap32_ordinal248>
extern __imp_wldap32_ordinal249:PANYARGS
wldap32_ordinal249 TEXTEQU <__imp_wldap32_ordinal249>
extern __imp_wldap32_ordinal250:PANYARGS
wldap32_ordinal250 TEXTEQU <__imp_wldap32_ordinal250>
extern __imp_wldap32_ordinal251:PANYARGS
wldap32_ordinal251 TEXTEQU <__imp_wldap32_ordinal251>
extern __imp_wldap32_ordinal252:PANYARGS
wldap32_ordinal252 TEXTEQU <__imp_wldap32_ordinal252>
extern __imp_wldap32_ordinal253:PANYARGS
wldap32_ordinal253 TEXTEQU <__imp_wldap32_ordinal253>
extern __imp_wldap32_ordinal254:PANYARGS
wldap32_ordinal254 TEXTEQU <__imp_wldap32_ordinal254>
extern __imp_wldap32_ordinal255:PANYARGS
wldap32_ordinal255 TEXTEQU <__imp_wldap32_ordinal255>
extern __imp_wldap32_ordinal256:PANYARGS
wldap32_ordinal256 TEXTEQU <__imp_wldap32_ordinal256>
extern __imp_wldap32_ordinal257:PANYARGS
wldap32_ordinal257 TEXTEQU <__imp_wldap32_ordinal257>
extern __imp_wldap32_ordinal258:PANYARGS
wldap32_ordinal258 TEXTEQU <__imp_wldap32_ordinal258>
extern __imp_wldap32_ordinal259:PANYARGS
wldap32_ordinal259 TEXTEQU <__imp_wldap32_ordinal259>
extern __imp_wldap32_ordinal260:PANYARGS
wldap32_ordinal260 TEXTEQU <__imp_wldap32_ordinal260>
extern __imp_wldap32_ordinal261:PANYARGS
wldap32_ordinal261 TEXTEQU <__imp_wldap32_ordinal261>
extern __imp_wldap32_ordinal262:PANYARGS
wldap32_ordinal262 TEXTEQU <__imp_wldap32_ordinal262>
extern __imp_wldap32_ordinal263:PANYARGS
wldap32_ordinal263 TEXTEQU <__imp_wldap32_ordinal263>
extern __imp_wldap32_ordinal264:PANYARGS
wldap32_ordinal264 TEXTEQU <__imp_wldap32_ordinal264>
extern __imp_wldap32_ordinal265:PANYARGS
wldap32_ordinal265 TEXTEQU <__imp_wldap32_ordinal265>
extern __imp_wldap32_ordinal266:PANYARGS
wldap32_ordinal266 TEXTEQU <__imp_wldap32_ordinal266>
extern __imp_wldap32_ordinal267:PANYARGS
wldap32_ordinal267 TEXTEQU <__imp_wldap32_ordinal267>
extern __imp_wldap32_ordinal268:PANYARGS
wldap32_ordinal268 TEXTEQU <__imp_wldap32_ordinal268>
extern __imp_wldap32_ordinal269:PANYARGS
wldap32_ordinal269 TEXTEQU <__imp_wldap32_ordinal269>
extern __imp_wldap32_ordinal270:PANYARGS
wldap32_ordinal270 TEXTEQU <__imp_wldap32_ordinal270>
extern __imp_wldap32_ordinal271:PANYARGS
wldap32_ordinal271 TEXTEQU <__imp_wldap32_ordinal271>
extern __imp_wldap32_ordinal272:PANYARGS
wldap32_ordinal272 TEXTEQU <__imp_wldap32_ordinal272>
extern __imp_wldap32_ordinal273:PANYARGS
wldap32_ordinal273 TEXTEQU <__imp_wldap32_ordinal273>
extern __imp_wldap32_ordinal274:PANYARGS
wldap32_ordinal274 TEXTEQU <__imp_wldap32_ordinal274>
extern __imp_wldap32_ordinal275:PANYARGS
wldap32_ordinal275 TEXTEQU <__imp_wldap32_ordinal275>
extern __imp_wldap32_ordinal276:PANYARGS
wldap32_ordinal276 TEXTEQU <__imp_wldap32_ordinal276>
extern __imp_wldap32_ordinal277:PANYARGS
wldap32_ordinal277 TEXTEQU <__imp_wldap32_ordinal277>
extern __imp_wldap32_ordinal278:PANYARGS
wldap32_ordinal278 TEXTEQU <__imp_wldap32_ordinal278>
extern __imp_wldap32_ordinal279:PANYARGS
wldap32_ordinal279 TEXTEQU <__imp_wldap32_ordinal279>
extern __imp_wldap32_ordinal280:PANYARGS
wldap32_ordinal280 TEXTEQU <__imp_wldap32_ordinal280>
extern __imp_wldap32_ordinal281:PANYARGS
wldap32_ordinal281 TEXTEQU <__imp_wldap32_ordinal281>
extern __imp_wldap32_ordinal282:PANYARGS
wldap32_ordinal282 TEXTEQU <__imp_wldap32_ordinal282>
extern __imp_wldap32_ordinal283:PANYARGS
wldap32_ordinal283 TEXTEQU <__imp_wldap32_ordinal283>
extern __imp_wldap32_ordinal284:PANYARGS
wldap32_ordinal284 TEXTEQU <__imp_wldap32_ordinal284>
extern __imp_wldap32_ordinal285:PANYARGS
wldap32_ordinal285 TEXTEQU <__imp_wldap32_ordinal285>
extern __imp_wldap32_ordinal286:PANYARGS
wldap32_ordinal286 TEXTEQU <__imp_wldap32_ordinal286>
extern __imp_wldap32_ordinal287:PANYARGS
wldap32_ordinal287 TEXTEQU <__imp_wldap32_ordinal287>
extern __imp_wldap32_ordinal288:PANYARGS
wldap32_ordinal288 TEXTEQU <__imp_wldap32_ordinal288>
extern __imp_wldap32_ordinal289:PANYARGS
wldap32_ordinal289 TEXTEQU <__imp_wldap32_ordinal289>
extern __imp_wldap32_ordinal290:PANYARGS
wldap32_ordinal290 TEXTEQU <__imp_wldap32_ordinal290>
extern __imp_wldap32_ordinal291:PANYARGS
wldap32_ordinal291 TEXTEQU <__imp_wldap32_ordinal291>
extern __imp_wldap32_ordinal292:PANYARGS
wldap32_ordinal292 TEXTEQU <__imp_wldap32_ordinal292>
extern __imp_wldap32_ordinal293:PANYARGS
wldap32_ordinal293 TEXTEQU <__imp_wldap32_ordinal293>
extern __imp_wldap32_ordinal294:PANYARGS
wldap32_ordinal294 TEXTEQU <__imp_wldap32_ordinal294>
extern __imp_wldap32_ordinal295:PANYARGS
wldap32_ordinal295 TEXTEQU <__imp_wldap32_ordinal295>
extern __imp_wldap32_ordinal296:PANYARGS
wldap32_ordinal296 TEXTEQU <__imp_wldap32_ordinal296>
extern __imp_wldap32_ordinal297:PANYARGS
wldap32_ordinal297 TEXTEQU <__imp_wldap32_ordinal297>
extern __imp_wldap32_ordinal298:PANYARGS
wldap32_ordinal298 TEXTEQU <__imp_wldap32_ordinal298>
extern __imp_wldap32_ordinal299:PANYARGS
wldap32_ordinal299 TEXTEQU <__imp_wldap32_ordinal299>
extern __imp_ber_init:PANYARGS
ber_init TEXTEQU <__imp_ber_init>
extern __imp_ber_free:PANYARGS
ber_free TEXTEQU <__imp_ber_free>
extern __imp_ber_bvecfree:PANYARGS
ber_bvecfree TEXTEQU <__imp_ber_bvecfree>
extern __imp_ber_bvdup:PANYARGS
ber_bvdup TEXTEQU <__imp_ber_bvdup>
extern __imp_ber_alloc_t:PANYARGS
ber_alloc_t TEXTEQU <__imp_ber_alloc_t>
extern __imp_ber_skip_tag:PANYARGS
ber_skip_tag TEXTEQU <__imp_ber_skip_tag>
extern __imp_ber_peek_tag:PANYARGS
ber_peek_tag TEXTEQU <__imp_ber_peek_tag>
extern __imp_ber_first_element:PANYARGS
ber_first_element TEXTEQU <__imp_ber_first_element>
extern __imp_ber_next_element:PANYARGS
ber_next_element TEXTEQU <__imp_ber_next_element>
extern __imp_ber_flatten:PANYARGS
ber_flatten TEXTEQU <__imp_ber_flatten>
extern __imp_ber_printf:PANYARGS
ber_printf TEXTEQU <__imp_ber_printf>
extern __imp_ber_scanf:PANYARGS
ber_scanf TEXTEQU <__imp_ber_scanf>
extern __imp_ldap_conn_from_msg:PANYARGS
ldap_conn_from_msg TEXTEQU <__imp_ldap_conn_from_msg>
extern __imp_ldap_sasl_bindW:PANYARGS
ldap_sasl_bindW TEXTEQU <__imp_ldap_sasl_bindW>
extern __imp_ldap_sasl_bind_sW:PANYARGS
ldap_sasl_bind_sW TEXTEQU <__imp_ldap_sasl_bind_sW>
extern __imp_ldap_sasl_bindA:PANYARGS
ldap_sasl_bind  TEXTEQU <__imp_ldap_sasl_bindA>
extern __imp_ldap_sasl_bind_sA:PANYARGS
ldap_sasl_bind_s  TEXTEQU <__imp_ldap_sasl_bind_sA>
extern __imp_ldap_parse_extended_resultW:PANYARGS
ldap_parse_extended_resultW TEXTEQU <__imp_ldap_parse_extended_resultW>
extern __imp_ldap_parse_extended_resultA:PANYARGS
ldap_parse_extended_result  TEXTEQU <__imp_ldap_parse_extended_resultA>
extern __imp_ldap_create_vlv_controlW:PANYARGS
ldap_create_vlv_controlW TEXTEQU <__imp_ldap_create_vlv_controlW>
extern __imp_ldap_create_vlv_controlA:PANYARGS
ldap_create_vlv_control  TEXTEQU <__imp_ldap_create_vlv_controlA>
extern __imp_ldap_parse_vlv_controlW:PANYARGS
ldap_parse_vlv_controlW TEXTEQU <__imp_ldap_parse_vlv_controlW>
extern __imp_ldap_parse_vlv_controlA:PANYARGS
ldap_parse_vlv_control  TEXTEQU <__imp_ldap_parse_vlv_controlA>
extern __imp_wldap32_ordinal323:PANYARGS
wldap32_ordinal323 TEXTEQU <__imp_wldap32_ordinal323>
extern __imp_wldap32_ordinal324:PANYARGS
wldap32_ordinal324 TEXTEQU <__imp_wldap32_ordinal324>
extern __imp_wldap32_ordinal325:PANYARGS
wldap32_ordinal325 TEXTEQU <__imp_wldap32_ordinal325>
extern __imp_wldap32_ordinal326:PANYARGS
wldap32_ordinal326 TEXTEQU <__imp_wldap32_ordinal326>
extern __imp_wldap32_ordinal327:PANYARGS
wldap32_ordinal327 TEXTEQU <__imp_wldap32_ordinal327>
extern __imp_wldap32_ordinal328:PANYARGS
wldap32_ordinal328 TEXTEQU <__imp_wldap32_ordinal328>
extern __imp_ldap_start_tls_sW:PANYARGS
ldap_start_tls_sW TEXTEQU <__imp_ldap_start_tls_sW>
extern __imp_ldap_start_tls_sA:PANYARGS
ldap_start_tls_s  TEXTEQU <__imp_ldap_start_tls_sA>
extern __imp_ldap_stop_tls_s:PANYARGS
ldap_stop_tls_s TEXTEQU <__imp_ldap_stop_tls_s>
extern __imp_ldap_extended_operation_sW:PANYARGS
ldap_extended_operation_sW TEXTEQU <__imp_ldap_extended_operation_sW>
extern __imp_ldap_extended_operation_sA:PANYARGS
ldap_extended_operation_s  TEXTEQU <__imp_ldap_extended_operation_sA>
