extern __imp_RegisterTicketExpiredNotificationEvent:PANYARGS
RegisterTicketExpiredNotificationEvent TEXTEQU <__imp_RegisterTicketExpiredNotificationEvent>
extern __imp_SCardResumeCertProp:PANYARGS
SCardResumeCertProp TEXTEQU <__imp_SCardResumeCertProp>
extern __imp_SCardStartCertProp:PANYARGS
SCardStartCertProp TEXTEQU <__imp_SCardStartCertProp>
extern __imp_SCardStopCertProp:PANYARGS
SCardStopCertProp TEXTEQU <__imp_SCardStopCertProp>
extern __imp_SCardSuspendCertProp:PANYARGS
SCardSuspendCertProp TEXTEQU <__imp_SCardSuspendCertProp>
extern __imp_SchedEventLogOff:PANYARGS
SchedEventLogOff TEXTEQU <__imp_SchedEventLogOff>
extern __imp_SchedStartShell:PANYARGS
SchedStartShell TEXTEQU <__imp_SchedStartShell>
extern __imp_ShowNotificationBalloonW:PANYARGS
ShowNotificationBalloonW TEXTEQU <__imp_ShowNotificationBalloonW>
extern __imp_UnregisterTicketExpiredNotificationEvent:PANYARGS
UnregisterTicketExpiredNotificationEvent TEXTEQU <__imp_UnregisterTicketExpiredNotificationEvent>
extern __imp_SensDisconnectEvent:PANYARGS
SensDisconnectEvent TEXTEQU <__imp_SensDisconnectEvent>
extern __imp_SensLockEvent:PANYARGS
SensLockEvent TEXTEQU <__imp_SensLockEvent>
extern __imp_SensLogoffEvent:PANYARGS
SensLogoffEvent TEXTEQU <__imp_SensLogoffEvent>
extern __imp_SensLogonEvent:PANYARGS
SensLogonEvent TEXTEQU <__imp_SensLogonEvent>
extern __imp_SensPostShellEvent:PANYARGS
SensPostShellEvent TEXTEQU <__imp_SensPostShellEvent>
extern __imp_SensReconnectEvent:PANYARGS
SensReconnectEvent TEXTEQU <__imp_SensReconnectEvent>
extern __imp_SensShutdownEvent:PANYARGS
SensShutdownEvent TEXTEQU <__imp_SensShutdownEvent>
extern __imp_SensStartScreenSaverEvent:PANYARGS
SensStartScreenSaverEvent TEXTEQU <__imp_SensStartScreenSaverEvent>
extern __imp_SensStartShellEvent:PANYARGS
SensStartShellEvent TEXTEQU <__imp_SensStartShellEvent>
extern __imp_SensStartupEvent:PANYARGS
SensStartupEvent TEXTEQU <__imp_SensStartupEvent>
extern __imp_SensStopScreenSaverEvent:PANYARGS
SensStopScreenSaverEvent TEXTEQU <__imp_SensStopScreenSaverEvent>
extern __imp_SensUnlockEvent:PANYARGS
SensUnlockEvent TEXTEQU <__imp_SensUnlockEvent>
extern __imp_TSEventDisconnect:PANYARGS
TSEventDisconnect TEXTEQU <__imp_TSEventDisconnect>
extern __imp_TSEventLogoff:PANYARGS
TSEventLogoff TEXTEQU <__imp_TSEventLogoff>
extern __imp_TSEventLogon:PANYARGS
TSEventLogon TEXTEQU <__imp_TSEventLogon>
extern __imp_TSEventPostShell:PANYARGS
TSEventPostShell TEXTEQU <__imp_TSEventPostShell>
extern __imp_TSEventReconnect:PANYARGS
TSEventReconnect TEXTEQU <__imp_TSEventReconnect>
extern __imp_TSEventShutdown:PANYARGS
TSEventShutdown TEXTEQU <__imp_TSEventShutdown>
extern __imp_TSEventStartShell:PANYARGS
TSEventStartShell TEXTEQU <__imp_TSEventStartShell>
extern __imp_TSEventStartup:PANYARGS
TSEventStartup TEXTEQU <__imp_TSEventStartup>
extern __imp_TermsrvCreateTempDir:PANYARGS
TermsrvCreateTempDir TEXTEQU <__imp_TermsrvCreateTempDir>
