extern __imp_CloseTrace:PANYARGS
CloseTrace TEXTEQU <__imp_CloseTrace>
extern __imp_ControlTraceA:PANYARGS
ControlTrace  TEXTEQU <__imp_ControlTraceA>
extern __imp_ControlTraceW:PANYARGS
ControlTraceW TEXTEQU <__imp_ControlTraceW>
extern __imp_CreateTraceInstanceId:PANYARGS
CreateTraceInstanceId TEXTEQU <__imp_CreateTraceInstanceId>
extern __imp_EnableTrace:PANYARGS
EnableTrace TEXTEQU <__imp_EnableTrace>
extern __imp_GetTraceEnableFlags:PANYARGS
GetTraceEnableFlags TEXTEQU <__imp_GetTraceEnableFlags>
extern __imp_GetTraceEnableLevel:PANYARGS
GetTraceEnableLevel TEXTEQU <__imp_GetTraceEnableLevel>
extern __imp_GetTraceLoggerHandle:PANYARGS
GetTraceLoggerHandle TEXTEQU <__imp_GetTraceLoggerHandle>
extern __imp_OpenTraceA:PANYARGS
OpenTrace  TEXTEQU <__imp_OpenTraceA>
extern __imp_OpenTraceW:PANYARGS
OpenTraceW TEXTEQU <__imp_OpenTraceW>
extern __imp_ProcessTrace:PANYARGS
ProcessTrace TEXTEQU <__imp_ProcessTrace>
extern __imp_QueryAllTracesA:PANYARGS
QueryAllTraces  TEXTEQU <__imp_QueryAllTracesA>
extern __imp_QueryAllTracesW:PANYARGS
QueryAllTracesW TEXTEQU <__imp_QueryAllTracesW>
extern __imp_RegisterTraceGuidsA:PANYARGS
RegisterTraceGuids  TEXTEQU <__imp_RegisterTraceGuidsA>
extern __imp_RegisterTraceGuidsW:PANYARGS
RegisterTraceGuidsW TEXTEQU <__imp_RegisterTraceGuidsW>
extern __imp_RemoveTraceCallback:PANYARGS
RemoveTraceCallback TEXTEQU <__imp_RemoveTraceCallback>
extern __imp_SetTraceCallback:PANYARGS
SetTraceCallback TEXTEQU <__imp_SetTraceCallback>
extern __imp_StartTraceA:PANYARGS
StartTrace  TEXTEQU <__imp_StartTraceA>
extern __imp_StartTraceW:PANYARGS
StartTraceW TEXTEQU <__imp_StartTraceW>
extern __imp_TraceEvent:PANYARGS
TraceEvent TEXTEQU <__imp_TraceEvent>
extern __imp_TraceEventInstance:PANYARGS
TraceEventInstance TEXTEQU <__imp_TraceEventInstance>
extern __imp_UnregisterTraceGuids:PANYARGS
UnregisterTraceGuids TEXTEQU <__imp_UnregisterTraceGuids>
extern __imp_WmiCloseBlock:PANYARGS
WmiCloseBlock TEXTEQU <__imp_WmiCloseBlock>
extern __imp_WmiDevInstToInstanceNameA:PANYARGS
WmiDevInstToInstanceName  TEXTEQU <__imp_WmiDevInstToInstanceNameA>
extern __imp_WmiDevInstToInstanceNameW:PANYARGS
WmiDevInstToInstanceNameW TEXTEQU <__imp_WmiDevInstToInstanceNameW>
extern __imp_WmiEnumerateGuids:PANYARGS
WmiEnumerateGuids TEXTEQU <__imp_WmiEnumerateGuids>
extern __imp_WmiExecuteMethodA:PANYARGS
WmiExecuteMethod  TEXTEQU <__imp_WmiExecuteMethodA>
extern __imp_WmiExecuteMethodW:PANYARGS
WmiExecuteMethodW TEXTEQU <__imp_WmiExecuteMethodW>
extern __imp_WmiFileHandleToInstanceNameA:PANYARGS
WmiFileHandleToInstanceName  TEXTEQU <__imp_WmiFileHandleToInstanceNameA>
extern __imp_WmiFileHandleToInstanceNameW:PANYARGS
WmiFileHandleToInstanceNameW TEXTEQU <__imp_WmiFileHandleToInstanceNameW>
extern __imp_WmiFreeBuffer:PANYARGS
WmiFreeBuffer TEXTEQU <__imp_WmiFreeBuffer>
extern __imp_WmiMofEnumerateResourcesA:PANYARGS
WmiMofEnumerateResources  TEXTEQU <__imp_WmiMofEnumerateResourcesA>
extern __imp_WmiMofEnumerateResourcesW:PANYARGS
WmiMofEnumerateResourcesW TEXTEQU <__imp_WmiMofEnumerateResourcesW>
extern __imp_WmiNotificationRegistrationA:PANYARGS
WmiNotificationRegistration  TEXTEQU <__imp_WmiNotificationRegistrationA>
extern __imp_WmiNotificationRegistrationW:PANYARGS
WmiNotificationRegistrationW TEXTEQU <__imp_WmiNotificationRegistrationW>
extern __imp_WmiOpenBlock:PANYARGS
WmiOpenBlock TEXTEQU <__imp_WmiOpenBlock>
extern __imp_WmiQueryAllDataA:PANYARGS
WmiQueryAllData  TEXTEQU <__imp_WmiQueryAllDataA>
extern __imp_WmiQueryAllDataW:PANYARGS
WmiQueryAllDataW TEXTEQU <__imp_WmiQueryAllDataW>
extern __imp_WmiQueryGuidInformation:PANYARGS
WmiQueryGuidInformation TEXTEQU <__imp_WmiQueryGuidInformation>
extern __imp_WmiQuerySingleInstanceA:PANYARGS
WmiQuerySingleInstance  TEXTEQU <__imp_WmiQuerySingleInstanceA>
extern __imp_WmiQuerySingleInstanceW:PANYARGS
WmiQuerySingleInstanceW TEXTEQU <__imp_WmiQuerySingleInstanceW>
extern __imp_WmiSetSingleInstanceA:PANYARGS
WmiSetSingleInstance  TEXTEQU <__imp_WmiSetSingleInstanceA>
extern __imp_WmiSetSingleInstanceW:PANYARGS
WmiSetSingleInstanceW TEXTEQU <__imp_WmiSetSingleInstanceW>
extern __imp_WmiSetSingleItemA:PANYARGS
WmiSetSingleItem  TEXTEQU <__imp_WmiSetSingleItemA>
extern __imp_WmiSetSingleItemW:PANYARGS
WmiSetSingleItemW TEXTEQU <__imp_WmiSetSingleItemW>
