extern __imp_accept:PANYARGS
accept TEXTEQU <__imp_accept>
extern __imp_bind:PANYARGS
bind TEXTEQU <__imp_bind>
extern __imp_closesocket:PANYARGS
closesocket TEXTEQU <__imp_closesocket>
extern __imp_connect:PANYARGS
connect TEXTEQU <__imp_connect>
extern __imp_getpeername:PANYARGS
getpeername TEXTEQU <__imp_getpeername>
extern __imp_getsockname:PANYARGS
getsockname TEXTEQU <__imp_getsockname>
extern __imp_getsockopt:PANYARGS
getsockopt TEXTEQU <__imp_getsockopt>
extern __imp_htonl:PANYARGS
htonl TEXTEQU <__imp_htonl>
extern __imp_htons:PANYARGS
htons TEXTEQU <__imp_htons>
extern __imp_ioctlsocket:PANYARGS
ioctlsocket TEXTEQU <__imp_ioctlsocket>
extern __imp_inet_addr:PANYARGS
inet_addr TEXTEQU <__imp_inet_addr>
extern __imp_inet_ntoa:PANYARGS
inet_ntoa TEXTEQU <__imp_inet_ntoa>
extern __imp_listen:PANYARGS
listen TEXTEQU <__imp_listen>
extern __imp_ntohl:PANYARGS
ntohl TEXTEQU <__imp_ntohl>
extern __imp_ntohs:PANYARGS
ntohs TEXTEQU <__imp_ntohs>
extern __imp_recv:PANYARGS
recv TEXTEQU <__imp_recv>
extern __imp_recvfrom:PANYARGS
recvfrom TEXTEQU <__imp_recvfrom>
extern __imp_select:PANYARGS
select TEXTEQU <__imp_select>
extern __imp_send:PANYARGS
send TEXTEQU <__imp_send>
extern __imp_sendto:PANYARGS
sendto TEXTEQU <__imp_sendto>
extern __imp_setsockopt:PANYARGS
setsockopt TEXTEQU <__imp_setsockopt>
extern __imp_shutdown:PANYARGS
shutdown TEXTEQU <__imp_shutdown>
extern __imp_socket:PANYARGS
socket TEXTEQU <__imp_socket>
extern __imp_WSApSetPostRoutine:PANYARGS
WSApSetPostRoutine TEXTEQU <__imp_WSApSetPostRoutine>
extern __imp_FreeAddrInfoW:PANYARGS
FreeAddrInfoW TEXTEQU <__imp_FreeAddrInfoW>
extern __imp_GetAddrInfoW:PANYARGS
GetAddrInfoW TEXTEQU <__imp_GetAddrInfoW>
extern __imp_GetNameInfoW:PANYARGS
GetNameInfoW TEXTEQU <__imp_GetNameInfoW>
extern __imp_WPUCompleteOverlappedRequest:PANYARGS
WPUCompleteOverlappedRequest TEXTEQU <__imp_WPUCompleteOverlappedRequest>
extern __imp_WSAAccept:PANYARGS
WSAAccept TEXTEQU <__imp_WSAAccept>
extern __imp_WSAAddressToStringA:PANYARGS
WSAAddressToString  TEXTEQU <__imp_WSAAddressToStringA>
extern __imp_WSAAddressToStringW:PANYARGS
WSAAddressToStringW TEXTEQU <__imp_WSAAddressToStringW>
extern __imp_WSACloseEvent:PANYARGS
WSACloseEvent TEXTEQU <__imp_WSACloseEvent>
extern __imp_WSAConnect:PANYARGS
WSAConnect TEXTEQU <__imp_WSAConnect>
extern __imp_WSACreateEvent:PANYARGS
WSACreateEvent TEXTEQU <__imp_WSACreateEvent>
extern __imp_WSADuplicateSocketA:PANYARGS
WSADuplicateSocket  TEXTEQU <__imp_WSADuplicateSocketA>
extern __imp_WSADuplicateSocketW:PANYARGS
WSADuplicateSocketW TEXTEQU <__imp_WSADuplicateSocketW>
extern __imp_WSAEnumNameSpaceProvidersA:PANYARGS
WSAEnumNameSpaceProviders  TEXTEQU <__imp_WSAEnumNameSpaceProvidersA>
extern __imp_WSAEnumNameSpaceProvidersW:PANYARGS
WSAEnumNameSpaceProvidersW TEXTEQU <__imp_WSAEnumNameSpaceProvidersW>
extern __imp_WSAEnumNetworkEvents:PANYARGS
WSAEnumNetworkEvents TEXTEQU <__imp_WSAEnumNetworkEvents>
extern __imp_WSAEnumProtocolsA:PANYARGS
WSAEnumProtocols  TEXTEQU <__imp_WSAEnumProtocolsA>
extern __imp_WSAEnumProtocolsW:PANYARGS
WSAEnumProtocolsW TEXTEQU <__imp_WSAEnumProtocolsW>
extern __imp_WSAEventSelect:PANYARGS
WSAEventSelect TEXTEQU <__imp_WSAEventSelect>
extern __imp_WSAGetOverlappedResult:PANYARGS
WSAGetOverlappedResult TEXTEQU <__imp_WSAGetOverlappedResult>
extern __imp_WSAGetQOSByName:PANYARGS
WSAGetQOSByName TEXTEQU <__imp_WSAGetQOSByName>
extern __imp_WSAGetServiceClassInfoA:PANYARGS
WSAGetServiceClassInfo  TEXTEQU <__imp_WSAGetServiceClassInfoA>
extern __imp_WSAGetServiceClassInfoW:PANYARGS
WSAGetServiceClassInfoW TEXTEQU <__imp_WSAGetServiceClassInfoW>
extern __imp_WSAGetServiceClassNameByClassIdA:PANYARGS
WSAGetServiceClassNameByClassId  TEXTEQU <__imp_WSAGetServiceClassNameByClassIdA>
extern __imp_WSAGetServiceClassNameByClassIdW:PANYARGS
WSAGetServiceClassNameByClassIdW TEXTEQU <__imp_WSAGetServiceClassNameByClassIdW>
extern __imp_WSAHtonl:PANYARGS
WSAHtonl TEXTEQU <__imp_WSAHtonl>
extern __imp_WSAHtons:PANYARGS
WSAHtons TEXTEQU <__imp_WSAHtons>
extern __imp_gethostbyaddr:PANYARGS
gethostbyaddr TEXTEQU <__imp_gethostbyaddr>
extern __imp_gethostbyname:PANYARGS
gethostbyname TEXTEQU <__imp_gethostbyname>
extern __imp_getprotobyname:PANYARGS
getprotobyname TEXTEQU <__imp_getprotobyname>
extern __imp_getprotobynumber:PANYARGS
getprotobynumber TEXTEQU <__imp_getprotobynumber>
extern __imp_getservbyname:PANYARGS
getservbyname TEXTEQU <__imp_getservbyname>
extern __imp_getservbyport:PANYARGS
getservbyport TEXTEQU <__imp_getservbyport>
extern __imp_gethostname:PANYARGS
gethostname TEXTEQU <__imp_gethostname>
extern __imp_WSAInstallServiceClassA:PANYARGS
WSAInstallServiceClass  TEXTEQU <__imp_WSAInstallServiceClassA>
extern __imp_WSAInstallServiceClassW:PANYARGS
WSAInstallServiceClassW TEXTEQU <__imp_WSAInstallServiceClassW>
extern __imp_WSAIoctl:PANYARGS
WSAIoctl TEXTEQU <__imp_WSAIoctl>
extern __imp_WSAJoinLeaf:PANYARGS
WSAJoinLeaf TEXTEQU <__imp_WSAJoinLeaf>
extern __imp_WSALookupServiceBeginA:PANYARGS
WSALookupServiceBegin  TEXTEQU <__imp_WSALookupServiceBeginA>
extern __imp_WSALookupServiceBeginW:PANYARGS
WSALookupServiceBeginW TEXTEQU <__imp_WSALookupServiceBeginW>
extern __imp_WSALookupServiceEnd:PANYARGS
WSALookupServiceEnd TEXTEQU <__imp_WSALookupServiceEnd>
extern __imp_WSALookupServiceNextA:PANYARGS
WSALookupServiceNext  TEXTEQU <__imp_WSALookupServiceNextA>
extern __imp_WSALookupServiceNextW:PANYARGS
WSALookupServiceNextW TEXTEQU <__imp_WSALookupServiceNextW>
extern __imp_WSANSPIoctl:PANYARGS
WSANSPIoctl TEXTEQU <__imp_WSANSPIoctl>
extern __imp_WSANtohl:PANYARGS
WSANtohl TEXTEQU <__imp_WSANtohl>
extern __imp_WSANtohs:PANYARGS
WSANtohs TEXTEQU <__imp_WSANtohs>
extern __imp_WSAProviderConfigChange:PANYARGS
WSAProviderConfigChange TEXTEQU <__imp_WSAProviderConfigChange>
extern __imp_WSARecv:PANYARGS
WSARecv TEXTEQU <__imp_WSARecv>
extern __imp_WSARecvDisconnect:PANYARGS
WSARecvDisconnect TEXTEQU <__imp_WSARecvDisconnect>
extern __imp_WSARecvFrom:PANYARGS
WSARecvFrom TEXTEQU <__imp_WSARecvFrom>
extern __imp_WSARemoveServiceClass:PANYARGS
WSARemoveServiceClass TEXTEQU <__imp_WSARemoveServiceClass>
extern __imp_WSAResetEvent:PANYARGS
WSAResetEvent TEXTEQU <__imp_WSAResetEvent>
extern __imp_WSASend:PANYARGS
WSASend TEXTEQU <__imp_WSASend>
extern __imp_WSASendDisconnect:PANYARGS
WSASendDisconnect TEXTEQU <__imp_WSASendDisconnect>
extern __imp_WSASendTo:PANYARGS
WSASendTo TEXTEQU <__imp_WSASendTo>
extern __imp_WSASetEvent:PANYARGS
WSASetEvent TEXTEQU <__imp_WSASetEvent>
extern __imp_WSASetServiceA:PANYARGS
WSASetService  TEXTEQU <__imp_WSASetServiceA>
extern __imp_WSASetServiceW:PANYARGS
WSASetServiceW TEXTEQU <__imp_WSASetServiceW>
extern __imp_WSASocketA:PANYARGS
WSASocket  TEXTEQU <__imp_WSASocketA>
extern __imp_WSASocketW:PANYARGS
WSASocketW TEXTEQU <__imp_WSASocketW>
extern __imp_WSAStringToAddressA:PANYARGS
WSAStringToAddress  TEXTEQU <__imp_WSAStringToAddressA>
extern __imp_WSAStringToAddressW:PANYARGS
WSAStringToAddressW TEXTEQU <__imp_WSAStringToAddressW>
extern __imp_WSAWaitForMultipleEvents:PANYARGS
WSAWaitForMultipleEvents TEXTEQU <__imp_WSAWaitForMultipleEvents>
extern __imp_WSCDeinstallProvider:PANYARGS
WSCDeinstallProvider TEXTEQU <__imp_WSCDeinstallProvider>
extern __imp_WSCDeinstallProvider32:PANYARGS
WSCDeinstallProvider32 TEXTEQU <__imp_WSCDeinstallProvider32>
extern __imp_WSCEnableNSProvider:PANYARGS
WSCEnableNSProvider TEXTEQU <__imp_WSCEnableNSProvider>
extern __imp_WSCEnableNSProvider32:PANYARGS
WSCEnableNSProvider32 TEXTEQU <__imp_WSCEnableNSProvider32>
extern __imp_WSCEnumNameSpaceProviders32:PANYARGS
WSCEnumNameSpaceProviders32 TEXTEQU <__imp_WSCEnumNameSpaceProviders32>
extern __imp_WSCEnumProtocols:PANYARGS
WSCEnumProtocols TEXTEQU <__imp_WSCEnumProtocols>
extern __imp_WSCEnumProtocols32:PANYARGS
WSCEnumProtocols32 TEXTEQU <__imp_WSCEnumProtocols32>
extern __imp_WSCGetProviderPath:PANYARGS
WSCGetProviderPath TEXTEQU <__imp_WSCGetProviderPath>
extern __imp_WSCGetProviderPath32:PANYARGS
WSCGetProviderPath32 TEXTEQU <__imp_WSCGetProviderPath32>
extern __imp_WSCInstallNameSpace:PANYARGS
WSCInstallNameSpace TEXTEQU <__imp_WSCInstallNameSpace>
extern __imp_WSCInstallNameSpace32:PANYARGS
WSCInstallNameSpace32 TEXTEQU <__imp_WSCInstallNameSpace32>
extern __imp_WSCInstallProvider:PANYARGS
WSCInstallProvider TEXTEQU <__imp_WSCInstallProvider>
extern __imp_WSCInstallProvider64_32:PANYARGS
WSCInstallProvider64_32 TEXTEQU <__imp_WSCInstallProvider64_32>
extern __imp_WSCUnInstallNameSpace:PANYARGS
WSCUnInstallNameSpace TEXTEQU <__imp_WSCUnInstallNameSpace>
extern __imp_WSAAsyncSelect:PANYARGS
WSAAsyncSelect TEXTEQU <__imp_WSAAsyncSelect>
extern __imp_WSAAsyncGetHostByAddr:PANYARGS
WSAAsyncGetHostByAddr TEXTEQU <__imp_WSAAsyncGetHostByAddr>
extern __imp_WSAAsyncGetHostByName:PANYARGS
WSAAsyncGetHostByName TEXTEQU <__imp_WSAAsyncGetHostByName>
extern __imp_WSAAsyncGetProtoByNumber:PANYARGS
WSAAsyncGetProtoByNumber TEXTEQU <__imp_WSAAsyncGetProtoByNumber>
extern __imp_WSAAsyncGetProtoByName:PANYARGS
WSAAsyncGetProtoByName TEXTEQU <__imp_WSAAsyncGetProtoByName>
extern __imp_WSAAsyncGetServByPort:PANYARGS
WSAAsyncGetServByPort TEXTEQU <__imp_WSAAsyncGetServByPort>
extern __imp_WSAAsyncGetServByName:PANYARGS
WSAAsyncGetServByName TEXTEQU <__imp_WSAAsyncGetServByName>
extern __imp_WSACancelAsyncRequest:PANYARGS
WSACancelAsyncRequest TEXTEQU <__imp_WSACancelAsyncRequest>
extern __imp_WSASetBlockingHook:PANYARGS
WSASetBlockingHook TEXTEQU <__imp_WSASetBlockingHook>
extern __imp_WSAUnhookBlockingHook:PANYARGS
WSAUnhookBlockingHook TEXTEQU <__imp_WSAUnhookBlockingHook>
extern __imp_WSAGetLastError:PANYARGS
WSAGetLastError TEXTEQU <__imp_WSAGetLastError>
extern __imp_WSASetLastError:PANYARGS
WSASetLastError TEXTEQU <__imp_WSASetLastError>
extern __imp_WSACancelBlockingCall:PANYARGS
WSACancelBlockingCall TEXTEQU <__imp_WSACancelBlockingCall>
extern __imp_WSAIsBlocking:PANYARGS
WSAIsBlocking TEXTEQU <__imp_WSAIsBlocking>
extern __imp_WSAStartup:PANYARGS
WSAStartup TEXTEQU <__imp_WSAStartup>
extern __imp_WSACleanup:PANYARGS
WSACleanup TEXTEQU <__imp_WSACleanup>
extern __imp_WSCUnInstallNameSpace32:PANYARGS
WSCUnInstallNameSpace32 TEXTEQU <__imp_WSCUnInstallNameSpace32>
extern __imp_WSCUpdateProvider:PANYARGS
WSCUpdateProvider TEXTEQU <__imp_WSCUpdateProvider>
extern __imp_WSCUpdateProvider32:PANYARGS
WSCUpdateProvider32 TEXTEQU <__imp_WSCUpdateProvider32>
extern __imp_WSCWriteNameSpaceOrder:PANYARGS
WSCWriteNameSpaceOrder TEXTEQU <__imp_WSCWriteNameSpaceOrder>
extern __imp_WSCWriteNameSpaceOrder32:PANYARGS
WSCWriteNameSpaceOrder32 TEXTEQU <__imp_WSCWriteNameSpaceOrder32>
extern __imp_WSCWriteProviderOrder:PANYARGS
WSCWriteProviderOrder TEXTEQU <__imp_WSCWriteProviderOrder>
extern __imp_WSCWriteProviderOrder32:PANYARGS
WSCWriteProviderOrder32 TEXTEQU <__imp_WSCWriteProviderOrder32>
extern __imp_freeaddrinfo:PANYARGS
freeaddrinfo TEXTEQU <__imp_freeaddrinfo>
extern __imp_getaddrinfo:PANYARGS
getaddrinfo TEXTEQU <__imp_getaddrinfo>
extern __imp_getnameinfo:PANYARGS
getnameinfo TEXTEQU <__imp_getnameinfo>
extern __imp_ws2_32_ordinal127:PANYARGS
ws2_32_ordinal127 TEXTEQU <__imp_ws2_32_ordinal127>
extern __imp_ws2_32_ordinal128:PANYARGS
ws2_32_ordinal128 TEXTEQU <__imp_ws2_32_ordinal128>
extern __imp_ws2_32_ordinal129:PANYARGS
ws2_32_ordinal129 TEXTEQU <__imp_ws2_32_ordinal129>
extern __imp_ws2_32_ordinal130:PANYARGS
ws2_32_ordinal130 TEXTEQU <__imp_ws2_32_ordinal130>
extern __imp_ws2_32_ordinal131:PANYARGS
ws2_32_ordinal131 TEXTEQU <__imp_ws2_32_ordinal131>
extern __imp_ws2_32_ordinal132:PANYARGS
ws2_32_ordinal132 TEXTEQU <__imp_ws2_32_ordinal132>
extern __imp_ws2_32_ordinal133:PANYARGS
ws2_32_ordinal133 TEXTEQU <__imp_ws2_32_ordinal133>
extern __imp_ws2_32_ordinal134:PANYARGS
ws2_32_ordinal134 TEXTEQU <__imp_ws2_32_ordinal134>
extern __imp_ws2_32_ordinal135:PANYARGS
ws2_32_ordinal135 TEXTEQU <__imp_ws2_32_ordinal135>
extern __imp_ws2_32_ordinal136:PANYARGS
ws2_32_ordinal136 TEXTEQU <__imp_ws2_32_ordinal136>
extern __imp_ws2_32_ordinal137:PANYARGS
ws2_32_ordinal137 TEXTEQU <__imp_ws2_32_ordinal137>
extern __imp_ws2_32_ordinal138:PANYARGS
ws2_32_ordinal138 TEXTEQU <__imp_ws2_32_ordinal138>
extern __imp_ws2_32_ordinal139:PANYARGS
ws2_32_ordinal139 TEXTEQU <__imp_ws2_32_ordinal139>
extern __imp_ws2_32_ordinal140:PANYARGS
ws2_32_ordinal140 TEXTEQU <__imp_ws2_32_ordinal140>
extern __imp_ws2_32_ordinal141:PANYARGS
ws2_32_ordinal141 TEXTEQU <__imp_ws2_32_ordinal141>
extern __imp_ws2_32_ordinal142:PANYARGS
ws2_32_ordinal142 TEXTEQU <__imp_ws2_32_ordinal142>
extern __imp_ws2_32_ordinal143:PANYARGS
ws2_32_ordinal143 TEXTEQU <__imp_ws2_32_ordinal143>
extern __imp_ws2_32_ordinal144:PANYARGS
ws2_32_ordinal144 TEXTEQU <__imp_ws2_32_ordinal144>
extern __imp_ws2_32_ordinal145:PANYARGS
ws2_32_ordinal145 TEXTEQU <__imp_ws2_32_ordinal145>
extern __imp_ws2_32_ordinal146:PANYARGS
ws2_32_ordinal146 TEXTEQU <__imp_ws2_32_ordinal146>
extern __imp_ws2_32_ordinal147:PANYARGS
ws2_32_ordinal147 TEXTEQU <__imp_ws2_32_ordinal147>
extern __imp_ws2_32_ordinal148:PANYARGS
ws2_32_ordinal148 TEXTEQU <__imp_ws2_32_ordinal148>
extern __imp_ws2_32_ordinal149:PANYARGS
ws2_32_ordinal149 TEXTEQU <__imp_ws2_32_ordinal149>
extern __imp_ws2_32_ordinal150:PANYARGS
ws2_32_ordinal150 TEXTEQU <__imp_ws2_32_ordinal150>
extern __imp___WSAFDIsSet:PANYARGS
__WSAFDIsSet TEXTEQU <__imp___WSAFDIsSet>
extern __imp_ws2_32_ordinal152:PANYARGS
ws2_32_ordinal152 TEXTEQU <__imp_ws2_32_ordinal152>
extern __imp_ws2_32_ordinal153:PANYARGS
ws2_32_ordinal153 TEXTEQU <__imp_ws2_32_ordinal153>
extern __imp_ws2_32_ordinal154:PANYARGS
ws2_32_ordinal154 TEXTEQU <__imp_ws2_32_ordinal154>
extern __imp_ws2_32_ordinal155:PANYARGS
ws2_32_ordinal155 TEXTEQU <__imp_ws2_32_ordinal155>
extern __imp_ws2_32_ordinal156:PANYARGS
ws2_32_ordinal156 TEXTEQU <__imp_ws2_32_ordinal156>
extern __imp_ws2_32_ordinal157:PANYARGS
ws2_32_ordinal157 TEXTEQU <__imp_ws2_32_ordinal157>
extern __imp_ws2_32_ordinal158:PANYARGS
ws2_32_ordinal158 TEXTEQU <__imp_ws2_32_ordinal158>
extern __imp_ws2_32_ordinal159:PANYARGS
ws2_32_ordinal159 TEXTEQU <__imp_ws2_32_ordinal159>
extern __imp_ws2_32_ordinal160:PANYARGS
ws2_32_ordinal160 TEXTEQU <__imp_ws2_32_ordinal160>
extern __imp_ws2_32_ordinal161:PANYARGS
ws2_32_ordinal161 TEXTEQU <__imp_ws2_32_ordinal161>
extern __imp_ws2_32_ordinal162:PANYARGS
ws2_32_ordinal162 TEXTEQU <__imp_ws2_32_ordinal162>
extern __imp_ws2_32_ordinal163:PANYARGS
ws2_32_ordinal163 TEXTEQU <__imp_ws2_32_ordinal163>
extern __imp_ws2_32_ordinal164:PANYARGS
ws2_32_ordinal164 TEXTEQU <__imp_ws2_32_ordinal164>
extern __imp_ws2_32_ordinal165:PANYARGS
ws2_32_ordinal165 TEXTEQU <__imp_ws2_32_ordinal165>
extern __imp_ws2_32_ordinal166:PANYARGS
ws2_32_ordinal166 TEXTEQU <__imp_ws2_32_ordinal166>
extern __imp_ws2_32_ordinal167:PANYARGS
ws2_32_ordinal167 TEXTEQU <__imp_ws2_32_ordinal167>
extern __imp_ws2_32_ordinal168:PANYARGS
ws2_32_ordinal168 TEXTEQU <__imp_ws2_32_ordinal168>
extern __imp_ws2_32_ordinal169:PANYARGS
ws2_32_ordinal169 TEXTEQU <__imp_ws2_32_ordinal169>
extern __imp_ws2_32_ordinal170:PANYARGS
ws2_32_ordinal170 TEXTEQU <__imp_ws2_32_ordinal170>
extern __imp_ws2_32_ordinal171:PANYARGS
ws2_32_ordinal171 TEXTEQU <__imp_ws2_32_ordinal171>
extern __imp_ws2_32_ordinal172:PANYARGS
ws2_32_ordinal172 TEXTEQU <__imp_ws2_32_ordinal172>
extern __imp_ws2_32_ordinal173:PANYARGS
ws2_32_ordinal173 TEXTEQU <__imp_ws2_32_ordinal173>
extern __imp_ws2_32_ordinal174:PANYARGS
ws2_32_ordinal174 TEXTEQU <__imp_ws2_32_ordinal174>
extern __imp_ws2_32_ordinal175:PANYARGS
ws2_32_ordinal175 TEXTEQU <__imp_ws2_32_ordinal175>
extern __imp_ws2_32_ordinal176:PANYARGS
ws2_32_ordinal176 TEXTEQU <__imp_ws2_32_ordinal176>
extern __imp_ws2_32_ordinal177:PANYARGS
ws2_32_ordinal177 TEXTEQU <__imp_ws2_32_ordinal177>
extern __imp_ws2_32_ordinal178:PANYARGS
ws2_32_ordinal178 TEXTEQU <__imp_ws2_32_ordinal178>
extern __imp_ws2_32_ordinal179:PANYARGS
ws2_32_ordinal179 TEXTEQU <__imp_ws2_32_ordinal179>
extern __imp_ws2_32_ordinal180:PANYARGS
ws2_32_ordinal180 TEXTEQU <__imp_ws2_32_ordinal180>
extern __imp_ws2_32_ordinal181:PANYARGS
ws2_32_ordinal181 TEXTEQU <__imp_ws2_32_ordinal181>
extern __imp_ws2_32_ordinal182:PANYARGS
ws2_32_ordinal182 TEXTEQU <__imp_ws2_32_ordinal182>
extern __imp_ws2_32_ordinal183:PANYARGS
ws2_32_ordinal183 TEXTEQU <__imp_ws2_32_ordinal183>
extern __imp_ws2_32_ordinal184:PANYARGS
ws2_32_ordinal184 TEXTEQU <__imp_ws2_32_ordinal184>
extern __imp_ws2_32_ordinal185:PANYARGS
ws2_32_ordinal185 TEXTEQU <__imp_ws2_32_ordinal185>
extern __imp_ws2_32_ordinal186:PANYARGS
ws2_32_ordinal186 TEXTEQU <__imp_ws2_32_ordinal186>
extern __imp_ws2_32_ordinal187:PANYARGS
ws2_32_ordinal187 TEXTEQU <__imp_ws2_32_ordinal187>
extern __imp_ws2_32_ordinal188:PANYARGS
ws2_32_ordinal188 TEXTEQU <__imp_ws2_32_ordinal188>
extern __imp_ws2_32_ordinal189:PANYARGS
ws2_32_ordinal189 TEXTEQU <__imp_ws2_32_ordinal189>
extern __imp_ws2_32_ordinal190:PANYARGS
ws2_32_ordinal190 TEXTEQU <__imp_ws2_32_ordinal190>
extern __imp_ws2_32_ordinal191:PANYARGS
ws2_32_ordinal191 TEXTEQU <__imp_ws2_32_ordinal191>
extern __imp_ws2_32_ordinal192:PANYARGS
ws2_32_ordinal192 TEXTEQU <__imp_ws2_32_ordinal192>
extern __imp_ws2_32_ordinal193:PANYARGS
ws2_32_ordinal193 TEXTEQU <__imp_ws2_32_ordinal193>
extern __imp_ws2_32_ordinal194:PANYARGS
ws2_32_ordinal194 TEXTEQU <__imp_ws2_32_ordinal194>
extern __imp_ws2_32_ordinal195:PANYARGS
ws2_32_ordinal195 TEXTEQU <__imp_ws2_32_ordinal195>
extern __imp_ws2_32_ordinal196:PANYARGS
ws2_32_ordinal196 TEXTEQU <__imp_ws2_32_ordinal196>
extern __imp_ws2_32_ordinal197:PANYARGS
ws2_32_ordinal197 TEXTEQU <__imp_ws2_32_ordinal197>
extern __imp_ws2_32_ordinal198:PANYARGS
ws2_32_ordinal198 TEXTEQU <__imp_ws2_32_ordinal198>
extern __imp_ws2_32_ordinal199:PANYARGS
ws2_32_ordinal199 TEXTEQU <__imp_ws2_32_ordinal199>
extern __imp_ws2_32_ordinal200:PANYARGS
ws2_32_ordinal200 TEXTEQU <__imp_ws2_32_ordinal200>
extern __imp_ws2_32_ordinal201:PANYARGS
ws2_32_ordinal201 TEXTEQU <__imp_ws2_32_ordinal201>
extern __imp_ws2_32_ordinal202:PANYARGS
ws2_32_ordinal202 TEXTEQU <__imp_ws2_32_ordinal202>
extern __imp_ws2_32_ordinal203:PANYARGS
ws2_32_ordinal203 TEXTEQU <__imp_ws2_32_ordinal203>
extern __imp_ws2_32_ordinal204:PANYARGS
ws2_32_ordinal204 TEXTEQU <__imp_ws2_32_ordinal204>
extern __imp_ws2_32_ordinal205:PANYARGS
ws2_32_ordinal205 TEXTEQU <__imp_ws2_32_ordinal205>
extern __imp_ws2_32_ordinal206:PANYARGS
ws2_32_ordinal206 TEXTEQU <__imp_ws2_32_ordinal206>
extern __imp_ws2_32_ordinal207:PANYARGS
ws2_32_ordinal207 TEXTEQU <__imp_ws2_32_ordinal207>
extern __imp_ws2_32_ordinal208:PANYARGS
ws2_32_ordinal208 TEXTEQU <__imp_ws2_32_ordinal208>
extern __imp_ws2_32_ordinal209:PANYARGS
ws2_32_ordinal209 TEXTEQU <__imp_ws2_32_ordinal209>
extern __imp_ws2_32_ordinal210:PANYARGS
ws2_32_ordinal210 TEXTEQU <__imp_ws2_32_ordinal210>
extern __imp_ws2_32_ordinal211:PANYARGS
ws2_32_ordinal211 TEXTEQU <__imp_ws2_32_ordinal211>
extern __imp_ws2_32_ordinal212:PANYARGS
ws2_32_ordinal212 TEXTEQU <__imp_ws2_32_ordinal212>
extern __imp_ws2_32_ordinal213:PANYARGS
ws2_32_ordinal213 TEXTEQU <__imp_ws2_32_ordinal213>
extern __imp_ws2_32_ordinal214:PANYARGS
ws2_32_ordinal214 TEXTEQU <__imp_ws2_32_ordinal214>
extern __imp_ws2_32_ordinal215:PANYARGS
ws2_32_ordinal215 TEXTEQU <__imp_ws2_32_ordinal215>
extern __imp_ws2_32_ordinal216:PANYARGS
ws2_32_ordinal216 TEXTEQU <__imp_ws2_32_ordinal216>
extern __imp_ws2_32_ordinal217:PANYARGS
ws2_32_ordinal217 TEXTEQU <__imp_ws2_32_ordinal217>
extern __imp_ws2_32_ordinal218:PANYARGS
ws2_32_ordinal218 TEXTEQU <__imp_ws2_32_ordinal218>
extern __imp_ws2_32_ordinal219:PANYARGS
ws2_32_ordinal219 TEXTEQU <__imp_ws2_32_ordinal219>
extern __imp_ws2_32_ordinal220:PANYARGS
ws2_32_ordinal220 TEXTEQU <__imp_ws2_32_ordinal220>
extern __imp_ws2_32_ordinal221:PANYARGS
ws2_32_ordinal221 TEXTEQU <__imp_ws2_32_ordinal221>
extern __imp_ws2_32_ordinal222:PANYARGS
ws2_32_ordinal222 TEXTEQU <__imp_ws2_32_ordinal222>
extern __imp_ws2_32_ordinal223:PANYARGS
ws2_32_ordinal223 TEXTEQU <__imp_ws2_32_ordinal223>
extern __imp_ws2_32_ordinal224:PANYARGS
ws2_32_ordinal224 TEXTEQU <__imp_ws2_32_ordinal224>
extern __imp_ws2_32_ordinal225:PANYARGS
ws2_32_ordinal225 TEXTEQU <__imp_ws2_32_ordinal225>
extern __imp_ws2_32_ordinal226:PANYARGS
ws2_32_ordinal226 TEXTEQU <__imp_ws2_32_ordinal226>
extern __imp_ws2_32_ordinal227:PANYARGS
ws2_32_ordinal227 TEXTEQU <__imp_ws2_32_ordinal227>
extern __imp_ws2_32_ordinal228:PANYARGS
ws2_32_ordinal228 TEXTEQU <__imp_ws2_32_ordinal228>
extern __imp_ws2_32_ordinal229:PANYARGS
ws2_32_ordinal229 TEXTEQU <__imp_ws2_32_ordinal229>
extern __imp_ws2_32_ordinal230:PANYARGS
ws2_32_ordinal230 TEXTEQU <__imp_ws2_32_ordinal230>
extern __imp_ws2_32_ordinal231:PANYARGS
ws2_32_ordinal231 TEXTEQU <__imp_ws2_32_ordinal231>
extern __imp_ws2_32_ordinal232:PANYARGS
ws2_32_ordinal232 TEXTEQU <__imp_ws2_32_ordinal232>
extern __imp_ws2_32_ordinal233:PANYARGS
ws2_32_ordinal233 TEXTEQU <__imp_ws2_32_ordinal233>
extern __imp_ws2_32_ordinal234:PANYARGS
ws2_32_ordinal234 TEXTEQU <__imp_ws2_32_ordinal234>
extern __imp_ws2_32_ordinal235:PANYARGS
ws2_32_ordinal235 TEXTEQU <__imp_ws2_32_ordinal235>
extern __imp_ws2_32_ordinal236:PANYARGS
ws2_32_ordinal236 TEXTEQU <__imp_ws2_32_ordinal236>
extern __imp_ws2_32_ordinal237:PANYARGS
ws2_32_ordinal237 TEXTEQU <__imp_ws2_32_ordinal237>
extern __imp_ws2_32_ordinal238:PANYARGS
ws2_32_ordinal238 TEXTEQU <__imp_ws2_32_ordinal238>
extern __imp_ws2_32_ordinal239:PANYARGS
ws2_32_ordinal239 TEXTEQU <__imp_ws2_32_ordinal239>
extern __imp_ws2_32_ordinal240:PANYARGS
ws2_32_ordinal240 TEXTEQU <__imp_ws2_32_ordinal240>
extern __imp_ws2_32_ordinal241:PANYARGS
ws2_32_ordinal241 TEXTEQU <__imp_ws2_32_ordinal241>
extern __imp_ws2_32_ordinal242:PANYARGS
ws2_32_ordinal242 TEXTEQU <__imp_ws2_32_ordinal242>
extern __imp_ws2_32_ordinal243:PANYARGS
ws2_32_ordinal243 TEXTEQU <__imp_ws2_32_ordinal243>
extern __imp_ws2_32_ordinal244:PANYARGS
ws2_32_ordinal244 TEXTEQU <__imp_ws2_32_ordinal244>
extern __imp_ws2_32_ordinal245:PANYARGS
ws2_32_ordinal245 TEXTEQU <__imp_ws2_32_ordinal245>
extern __imp_ws2_32_ordinal246:PANYARGS
ws2_32_ordinal246 TEXTEQU <__imp_ws2_32_ordinal246>
extern __imp_ws2_32_ordinal247:PANYARGS
ws2_32_ordinal247 TEXTEQU <__imp_ws2_32_ordinal247>
extern __imp_ws2_32_ordinal248:PANYARGS
ws2_32_ordinal248 TEXTEQU <__imp_ws2_32_ordinal248>
extern __imp_ws2_32_ordinal249:PANYARGS
ws2_32_ordinal249 TEXTEQU <__imp_ws2_32_ordinal249>
extern __imp_ws2_32_ordinal250:PANYARGS
ws2_32_ordinal250 TEXTEQU <__imp_ws2_32_ordinal250>
extern __imp_ws2_32_ordinal251:PANYARGS
ws2_32_ordinal251 TEXTEQU <__imp_ws2_32_ordinal251>
extern __imp_ws2_32_ordinal252:PANYARGS
ws2_32_ordinal252 TEXTEQU <__imp_ws2_32_ordinal252>
extern __imp_ws2_32_ordinal253:PANYARGS
ws2_32_ordinal253 TEXTEQU <__imp_ws2_32_ordinal253>
extern __imp_ws2_32_ordinal254:PANYARGS
ws2_32_ordinal254 TEXTEQU <__imp_ws2_32_ordinal254>
extern __imp_ws2_32_ordinal255:PANYARGS
ws2_32_ordinal255 TEXTEQU <__imp_ws2_32_ordinal255>
extern __imp_ws2_32_ordinal256:PANYARGS
ws2_32_ordinal256 TEXTEQU <__imp_ws2_32_ordinal256>
extern __imp_ws2_32_ordinal257:PANYARGS
ws2_32_ordinal257 TEXTEQU <__imp_ws2_32_ordinal257>
extern __imp_ws2_32_ordinal258:PANYARGS
ws2_32_ordinal258 TEXTEQU <__imp_ws2_32_ordinal258>
extern __imp_ws2_32_ordinal259:PANYARGS
ws2_32_ordinal259 TEXTEQU <__imp_ws2_32_ordinal259>
extern __imp_ws2_32_ordinal260:PANYARGS
ws2_32_ordinal260 TEXTEQU <__imp_ws2_32_ordinal260>
extern __imp_ws2_32_ordinal261:PANYARGS
ws2_32_ordinal261 TEXTEQU <__imp_ws2_32_ordinal261>
extern __imp_ws2_32_ordinal262:PANYARGS
ws2_32_ordinal262 TEXTEQU <__imp_ws2_32_ordinal262>
extern __imp_ws2_32_ordinal263:PANYARGS
ws2_32_ordinal263 TEXTEQU <__imp_ws2_32_ordinal263>
extern __imp_ws2_32_ordinal264:PANYARGS
ws2_32_ordinal264 TEXTEQU <__imp_ws2_32_ordinal264>
extern __imp_ws2_32_ordinal265:PANYARGS
ws2_32_ordinal265 TEXTEQU <__imp_ws2_32_ordinal265>
extern __imp_ws2_32_ordinal266:PANYARGS
ws2_32_ordinal266 TEXTEQU <__imp_ws2_32_ordinal266>
extern __imp_ws2_32_ordinal267:PANYARGS
ws2_32_ordinal267 TEXTEQU <__imp_ws2_32_ordinal267>
extern __imp_ws2_32_ordinal268:PANYARGS
ws2_32_ordinal268 TEXTEQU <__imp_ws2_32_ordinal268>
extern __imp_ws2_32_ordinal269:PANYARGS
ws2_32_ordinal269 TEXTEQU <__imp_ws2_32_ordinal269>
extern __imp_ws2_32_ordinal270:PANYARGS
ws2_32_ordinal270 TEXTEQU <__imp_ws2_32_ordinal270>
extern __imp_ws2_32_ordinal271:PANYARGS
ws2_32_ordinal271 TEXTEQU <__imp_ws2_32_ordinal271>
extern __imp_ws2_32_ordinal272:PANYARGS
ws2_32_ordinal272 TEXTEQU <__imp_ws2_32_ordinal272>
extern __imp_ws2_32_ordinal273:PANYARGS
ws2_32_ordinal273 TEXTEQU <__imp_ws2_32_ordinal273>
extern __imp_ws2_32_ordinal274:PANYARGS
ws2_32_ordinal274 TEXTEQU <__imp_ws2_32_ordinal274>
extern __imp_ws2_32_ordinal275:PANYARGS
ws2_32_ordinal275 TEXTEQU <__imp_ws2_32_ordinal275>
extern __imp_ws2_32_ordinal276:PANYARGS
ws2_32_ordinal276 TEXTEQU <__imp_ws2_32_ordinal276>
extern __imp_ws2_32_ordinal277:PANYARGS
ws2_32_ordinal277 TEXTEQU <__imp_ws2_32_ordinal277>
extern __imp_ws2_32_ordinal278:PANYARGS
ws2_32_ordinal278 TEXTEQU <__imp_ws2_32_ordinal278>
extern __imp_ws2_32_ordinal279:PANYARGS
ws2_32_ordinal279 TEXTEQU <__imp_ws2_32_ordinal279>
extern __imp_ws2_32_ordinal280:PANYARGS
ws2_32_ordinal280 TEXTEQU <__imp_ws2_32_ordinal280>
extern __imp_ws2_32_ordinal281:PANYARGS
ws2_32_ordinal281 TEXTEQU <__imp_ws2_32_ordinal281>
extern __imp_ws2_32_ordinal282:PANYARGS
ws2_32_ordinal282 TEXTEQU <__imp_ws2_32_ordinal282>
extern __imp_ws2_32_ordinal283:PANYARGS
ws2_32_ordinal283 TEXTEQU <__imp_ws2_32_ordinal283>
extern __imp_ws2_32_ordinal284:PANYARGS
ws2_32_ordinal284 TEXTEQU <__imp_ws2_32_ordinal284>
extern __imp_ws2_32_ordinal285:PANYARGS
ws2_32_ordinal285 TEXTEQU <__imp_ws2_32_ordinal285>
extern __imp_ws2_32_ordinal286:PANYARGS
ws2_32_ordinal286 TEXTEQU <__imp_ws2_32_ordinal286>
extern __imp_ws2_32_ordinal287:PANYARGS
ws2_32_ordinal287 TEXTEQU <__imp_ws2_32_ordinal287>
extern __imp_ws2_32_ordinal288:PANYARGS
ws2_32_ordinal288 TEXTEQU <__imp_ws2_32_ordinal288>
extern __imp_ws2_32_ordinal289:PANYARGS
ws2_32_ordinal289 TEXTEQU <__imp_ws2_32_ordinal289>
extern __imp_ws2_32_ordinal290:PANYARGS
ws2_32_ordinal290 TEXTEQU <__imp_ws2_32_ordinal290>
extern __imp_ws2_32_ordinal291:PANYARGS
ws2_32_ordinal291 TEXTEQU <__imp_ws2_32_ordinal291>
extern __imp_ws2_32_ordinal292:PANYARGS
ws2_32_ordinal292 TEXTEQU <__imp_ws2_32_ordinal292>
extern __imp_ws2_32_ordinal293:PANYARGS
ws2_32_ordinal293 TEXTEQU <__imp_ws2_32_ordinal293>
extern __imp_ws2_32_ordinal294:PANYARGS
ws2_32_ordinal294 TEXTEQU <__imp_ws2_32_ordinal294>
extern __imp_ws2_32_ordinal295:PANYARGS
ws2_32_ordinal295 TEXTEQU <__imp_ws2_32_ordinal295>
extern __imp_ws2_32_ordinal296:PANYARGS
ws2_32_ordinal296 TEXTEQU <__imp_ws2_32_ordinal296>
extern __imp_ws2_32_ordinal297:PANYARGS
ws2_32_ordinal297 TEXTEQU <__imp_ws2_32_ordinal297>
extern __imp_ws2_32_ordinal298:PANYARGS
ws2_32_ordinal298 TEXTEQU <__imp_ws2_32_ordinal298>
extern __imp_ws2_32_ordinal299:PANYARGS
ws2_32_ordinal299 TEXTEQU <__imp_ws2_32_ordinal299>
extern __imp_ws2_32_ordinal300:PANYARGS
ws2_32_ordinal300 TEXTEQU <__imp_ws2_32_ordinal300>
extern __imp_ws2_32_ordinal301:PANYARGS
ws2_32_ordinal301 TEXTEQU <__imp_ws2_32_ordinal301>
extern __imp_ws2_32_ordinal302:PANYARGS
ws2_32_ordinal302 TEXTEQU <__imp_ws2_32_ordinal302>
extern __imp_ws2_32_ordinal303:PANYARGS
ws2_32_ordinal303 TEXTEQU <__imp_ws2_32_ordinal303>
extern __imp_ws2_32_ordinal304:PANYARGS
ws2_32_ordinal304 TEXTEQU <__imp_ws2_32_ordinal304>
extern __imp_ws2_32_ordinal305:PANYARGS
ws2_32_ordinal305 TEXTEQU <__imp_ws2_32_ordinal305>
extern __imp_ws2_32_ordinal306:PANYARGS
ws2_32_ordinal306 TEXTEQU <__imp_ws2_32_ordinal306>
extern __imp_ws2_32_ordinal307:PANYARGS
ws2_32_ordinal307 TEXTEQU <__imp_ws2_32_ordinal307>
extern __imp_ws2_32_ordinal308:PANYARGS
ws2_32_ordinal308 TEXTEQU <__imp_ws2_32_ordinal308>
extern __imp_ws2_32_ordinal309:PANYARGS
ws2_32_ordinal309 TEXTEQU <__imp_ws2_32_ordinal309>
extern __imp_ws2_32_ordinal310:PANYARGS
ws2_32_ordinal310 TEXTEQU <__imp_ws2_32_ordinal310>
extern __imp_ws2_32_ordinal311:PANYARGS
ws2_32_ordinal311 TEXTEQU <__imp_ws2_32_ordinal311>
extern __imp_ws2_32_ordinal312:PANYARGS
ws2_32_ordinal312 TEXTEQU <__imp_ws2_32_ordinal312>
extern __imp_ws2_32_ordinal313:PANYARGS
ws2_32_ordinal313 TEXTEQU <__imp_ws2_32_ordinal313>
extern __imp_ws2_32_ordinal314:PANYARGS
ws2_32_ordinal314 TEXTEQU <__imp_ws2_32_ordinal314>
extern __imp_ws2_32_ordinal315:PANYARGS
ws2_32_ordinal315 TEXTEQU <__imp_ws2_32_ordinal315>
extern __imp_ws2_32_ordinal316:PANYARGS
ws2_32_ordinal316 TEXTEQU <__imp_ws2_32_ordinal316>
extern __imp_ws2_32_ordinal317:PANYARGS
ws2_32_ordinal317 TEXTEQU <__imp_ws2_32_ordinal317>
extern __imp_ws2_32_ordinal318:PANYARGS
ws2_32_ordinal318 TEXTEQU <__imp_ws2_32_ordinal318>
extern __imp_ws2_32_ordinal319:PANYARGS
ws2_32_ordinal319 TEXTEQU <__imp_ws2_32_ordinal319>
extern __imp_ws2_32_ordinal320:PANYARGS
ws2_32_ordinal320 TEXTEQU <__imp_ws2_32_ordinal320>
extern __imp_ws2_32_ordinal321:PANYARGS
ws2_32_ordinal321 TEXTEQU <__imp_ws2_32_ordinal321>
extern __imp_ws2_32_ordinal322:PANYARGS
ws2_32_ordinal322 TEXTEQU <__imp_ws2_32_ordinal322>
extern __imp_ws2_32_ordinal323:PANYARGS
ws2_32_ordinal323 TEXTEQU <__imp_ws2_32_ordinal323>
extern __imp_ws2_32_ordinal324:PANYARGS
ws2_32_ordinal324 TEXTEQU <__imp_ws2_32_ordinal324>
extern __imp_ws2_32_ordinal325:PANYARGS
ws2_32_ordinal325 TEXTEQU <__imp_ws2_32_ordinal325>
extern __imp_ws2_32_ordinal326:PANYARGS
ws2_32_ordinal326 TEXTEQU <__imp_ws2_32_ordinal326>
extern __imp_ws2_32_ordinal327:PANYARGS
ws2_32_ordinal327 TEXTEQU <__imp_ws2_32_ordinal327>
extern __imp_ws2_32_ordinal328:PANYARGS
ws2_32_ordinal328 TEXTEQU <__imp_ws2_32_ordinal328>
extern __imp_ws2_32_ordinal329:PANYARGS
ws2_32_ordinal329 TEXTEQU <__imp_ws2_32_ordinal329>
extern __imp_ws2_32_ordinal330:PANYARGS
ws2_32_ordinal330 TEXTEQU <__imp_ws2_32_ordinal330>
extern __imp_ws2_32_ordinal331:PANYARGS
ws2_32_ordinal331 TEXTEQU <__imp_ws2_32_ordinal331>
extern __imp_ws2_32_ordinal332:PANYARGS
ws2_32_ordinal332 TEXTEQU <__imp_ws2_32_ordinal332>
extern __imp_ws2_32_ordinal333:PANYARGS
ws2_32_ordinal333 TEXTEQU <__imp_ws2_32_ordinal333>
extern __imp_ws2_32_ordinal334:PANYARGS
ws2_32_ordinal334 TEXTEQU <__imp_ws2_32_ordinal334>
extern __imp_ws2_32_ordinal335:PANYARGS
ws2_32_ordinal335 TEXTEQU <__imp_ws2_32_ordinal335>
extern __imp_ws2_32_ordinal336:PANYARGS
ws2_32_ordinal336 TEXTEQU <__imp_ws2_32_ordinal336>
extern __imp_ws2_32_ordinal337:PANYARGS
ws2_32_ordinal337 TEXTEQU <__imp_ws2_32_ordinal337>
extern __imp_ws2_32_ordinal338:PANYARGS
ws2_32_ordinal338 TEXTEQU <__imp_ws2_32_ordinal338>
extern __imp_ws2_32_ordinal339:PANYARGS
ws2_32_ordinal339 TEXTEQU <__imp_ws2_32_ordinal339>
extern __imp_ws2_32_ordinal340:PANYARGS
ws2_32_ordinal340 TEXTEQU <__imp_ws2_32_ordinal340>
extern __imp_ws2_32_ordinal341:PANYARGS
ws2_32_ordinal341 TEXTEQU <__imp_ws2_32_ordinal341>
extern __imp_ws2_32_ordinal342:PANYARGS
ws2_32_ordinal342 TEXTEQU <__imp_ws2_32_ordinal342>
extern __imp_ws2_32_ordinal343:PANYARGS
ws2_32_ordinal343 TEXTEQU <__imp_ws2_32_ordinal343>
extern __imp_ws2_32_ordinal344:PANYARGS
ws2_32_ordinal344 TEXTEQU <__imp_ws2_32_ordinal344>
extern __imp_ws2_32_ordinal345:PANYARGS
ws2_32_ordinal345 TEXTEQU <__imp_ws2_32_ordinal345>
extern __imp_ws2_32_ordinal346:PANYARGS
ws2_32_ordinal346 TEXTEQU <__imp_ws2_32_ordinal346>
extern __imp_ws2_32_ordinal347:PANYARGS
ws2_32_ordinal347 TEXTEQU <__imp_ws2_32_ordinal347>
extern __imp_ws2_32_ordinal348:PANYARGS
ws2_32_ordinal348 TEXTEQU <__imp_ws2_32_ordinal348>
extern __imp_ws2_32_ordinal349:PANYARGS
ws2_32_ordinal349 TEXTEQU <__imp_ws2_32_ordinal349>
extern __imp_ws2_32_ordinal350:PANYARGS
ws2_32_ordinal350 TEXTEQU <__imp_ws2_32_ordinal350>
extern __imp_ws2_32_ordinal351:PANYARGS
ws2_32_ordinal351 TEXTEQU <__imp_ws2_32_ordinal351>
extern __imp_ws2_32_ordinal352:PANYARGS
ws2_32_ordinal352 TEXTEQU <__imp_ws2_32_ordinal352>
extern __imp_ws2_32_ordinal353:PANYARGS
ws2_32_ordinal353 TEXTEQU <__imp_ws2_32_ordinal353>
extern __imp_ws2_32_ordinal354:PANYARGS
ws2_32_ordinal354 TEXTEQU <__imp_ws2_32_ordinal354>
extern __imp_ws2_32_ordinal355:PANYARGS
ws2_32_ordinal355 TEXTEQU <__imp_ws2_32_ordinal355>
extern __imp_ws2_32_ordinal356:PANYARGS
ws2_32_ordinal356 TEXTEQU <__imp_ws2_32_ordinal356>
extern __imp_ws2_32_ordinal357:PANYARGS
ws2_32_ordinal357 TEXTEQU <__imp_ws2_32_ordinal357>
extern __imp_ws2_32_ordinal358:PANYARGS
ws2_32_ordinal358 TEXTEQU <__imp_ws2_32_ordinal358>
extern __imp_ws2_32_ordinal359:PANYARGS
ws2_32_ordinal359 TEXTEQU <__imp_ws2_32_ordinal359>
extern __imp_ws2_32_ordinal360:PANYARGS
ws2_32_ordinal360 TEXTEQU <__imp_ws2_32_ordinal360>
extern __imp_ws2_32_ordinal361:PANYARGS
ws2_32_ordinal361 TEXTEQU <__imp_ws2_32_ordinal361>
extern __imp_ws2_32_ordinal362:PANYARGS
ws2_32_ordinal362 TEXTEQU <__imp_ws2_32_ordinal362>
extern __imp_ws2_32_ordinal363:PANYARGS
ws2_32_ordinal363 TEXTEQU <__imp_ws2_32_ordinal363>
extern __imp_ws2_32_ordinal364:PANYARGS
ws2_32_ordinal364 TEXTEQU <__imp_ws2_32_ordinal364>
extern __imp_ws2_32_ordinal365:PANYARGS
ws2_32_ordinal365 TEXTEQU <__imp_ws2_32_ordinal365>
extern __imp_ws2_32_ordinal366:PANYARGS
ws2_32_ordinal366 TEXTEQU <__imp_ws2_32_ordinal366>
extern __imp_ws2_32_ordinal367:PANYARGS
ws2_32_ordinal367 TEXTEQU <__imp_ws2_32_ordinal367>
extern __imp_ws2_32_ordinal368:PANYARGS
ws2_32_ordinal368 TEXTEQU <__imp_ws2_32_ordinal368>
extern __imp_ws2_32_ordinal369:PANYARGS
ws2_32_ordinal369 TEXTEQU <__imp_ws2_32_ordinal369>
extern __imp_ws2_32_ordinal370:PANYARGS
ws2_32_ordinal370 TEXTEQU <__imp_ws2_32_ordinal370>
extern __imp_ws2_32_ordinal371:PANYARGS
ws2_32_ordinal371 TEXTEQU <__imp_ws2_32_ordinal371>
extern __imp_ws2_32_ordinal372:PANYARGS
ws2_32_ordinal372 TEXTEQU <__imp_ws2_32_ordinal372>
extern __imp_ws2_32_ordinal373:PANYARGS
ws2_32_ordinal373 TEXTEQU <__imp_ws2_32_ordinal373>
extern __imp_ws2_32_ordinal374:PANYARGS
ws2_32_ordinal374 TEXTEQU <__imp_ws2_32_ordinal374>
extern __imp_ws2_32_ordinal375:PANYARGS
ws2_32_ordinal375 TEXTEQU <__imp_ws2_32_ordinal375>
extern __imp_ws2_32_ordinal376:PANYARGS
ws2_32_ordinal376 TEXTEQU <__imp_ws2_32_ordinal376>
extern __imp_ws2_32_ordinal377:PANYARGS
ws2_32_ordinal377 TEXTEQU <__imp_ws2_32_ordinal377>
extern __imp_ws2_32_ordinal378:PANYARGS
ws2_32_ordinal378 TEXTEQU <__imp_ws2_32_ordinal378>
extern __imp_ws2_32_ordinal379:PANYARGS
ws2_32_ordinal379 TEXTEQU <__imp_ws2_32_ordinal379>
extern __imp_ws2_32_ordinal380:PANYARGS
ws2_32_ordinal380 TEXTEQU <__imp_ws2_32_ordinal380>
extern __imp_ws2_32_ordinal381:PANYARGS
ws2_32_ordinal381 TEXTEQU <__imp_ws2_32_ordinal381>
extern __imp_ws2_32_ordinal382:PANYARGS
ws2_32_ordinal382 TEXTEQU <__imp_ws2_32_ordinal382>
extern __imp_ws2_32_ordinal383:PANYARGS
ws2_32_ordinal383 TEXTEQU <__imp_ws2_32_ordinal383>
extern __imp_ws2_32_ordinal384:PANYARGS
ws2_32_ordinal384 TEXTEQU <__imp_ws2_32_ordinal384>
extern __imp_ws2_32_ordinal385:PANYARGS
ws2_32_ordinal385 TEXTEQU <__imp_ws2_32_ordinal385>
extern __imp_ws2_32_ordinal386:PANYARGS
ws2_32_ordinal386 TEXTEQU <__imp_ws2_32_ordinal386>
extern __imp_ws2_32_ordinal387:PANYARGS
ws2_32_ordinal387 TEXTEQU <__imp_ws2_32_ordinal387>
extern __imp_ws2_32_ordinal388:PANYARGS
ws2_32_ordinal388 TEXTEQU <__imp_ws2_32_ordinal388>
extern __imp_ws2_32_ordinal389:PANYARGS
ws2_32_ordinal389 TEXTEQU <__imp_ws2_32_ordinal389>
extern __imp_ws2_32_ordinal390:PANYARGS
ws2_32_ordinal390 TEXTEQU <__imp_ws2_32_ordinal390>
extern __imp_ws2_32_ordinal391:PANYARGS
ws2_32_ordinal391 TEXTEQU <__imp_ws2_32_ordinal391>
extern __imp_ws2_32_ordinal392:PANYARGS
ws2_32_ordinal392 TEXTEQU <__imp_ws2_32_ordinal392>
extern __imp_ws2_32_ordinal393:PANYARGS
ws2_32_ordinal393 TEXTEQU <__imp_ws2_32_ordinal393>
extern __imp_ws2_32_ordinal394:PANYARGS
ws2_32_ordinal394 TEXTEQU <__imp_ws2_32_ordinal394>
extern __imp_ws2_32_ordinal395:PANYARGS
ws2_32_ordinal395 TEXTEQU <__imp_ws2_32_ordinal395>
extern __imp_ws2_32_ordinal396:PANYARGS
ws2_32_ordinal396 TEXTEQU <__imp_ws2_32_ordinal396>
extern __imp_ws2_32_ordinal397:PANYARGS
ws2_32_ordinal397 TEXTEQU <__imp_ws2_32_ordinal397>
extern __imp_ws2_32_ordinal398:PANYARGS
ws2_32_ordinal398 TEXTEQU <__imp_ws2_32_ordinal398>
extern __imp_ws2_32_ordinal399:PANYARGS
ws2_32_ordinal399 TEXTEQU <__imp_ws2_32_ordinal399>
extern __imp_ws2_32_ordinal400:PANYARGS
ws2_32_ordinal400 TEXTEQU <__imp_ws2_32_ordinal400>
extern __imp_ws2_32_ordinal401:PANYARGS
ws2_32_ordinal401 TEXTEQU <__imp_ws2_32_ordinal401>
extern __imp_ws2_32_ordinal402:PANYARGS
ws2_32_ordinal402 TEXTEQU <__imp_ws2_32_ordinal402>
extern __imp_ws2_32_ordinal403:PANYARGS
ws2_32_ordinal403 TEXTEQU <__imp_ws2_32_ordinal403>
extern __imp_ws2_32_ordinal404:PANYARGS
ws2_32_ordinal404 TEXTEQU <__imp_ws2_32_ordinal404>
extern __imp_ws2_32_ordinal405:PANYARGS
ws2_32_ordinal405 TEXTEQU <__imp_ws2_32_ordinal405>
extern __imp_ws2_32_ordinal406:PANYARGS
ws2_32_ordinal406 TEXTEQU <__imp_ws2_32_ordinal406>
extern __imp_ws2_32_ordinal407:PANYARGS
ws2_32_ordinal407 TEXTEQU <__imp_ws2_32_ordinal407>
extern __imp_ws2_32_ordinal408:PANYARGS
ws2_32_ordinal408 TEXTEQU <__imp_ws2_32_ordinal408>
extern __imp_ws2_32_ordinal409:PANYARGS
ws2_32_ordinal409 TEXTEQU <__imp_ws2_32_ordinal409>
extern __imp_ws2_32_ordinal410:PANYARGS
ws2_32_ordinal410 TEXTEQU <__imp_ws2_32_ordinal410>
extern __imp_ws2_32_ordinal411:PANYARGS
ws2_32_ordinal411 TEXTEQU <__imp_ws2_32_ordinal411>
extern __imp_ws2_32_ordinal412:PANYARGS
ws2_32_ordinal412 TEXTEQU <__imp_ws2_32_ordinal412>
extern __imp_ws2_32_ordinal413:PANYARGS
ws2_32_ordinal413 TEXTEQU <__imp_ws2_32_ordinal413>
extern __imp_ws2_32_ordinal414:PANYARGS
ws2_32_ordinal414 TEXTEQU <__imp_ws2_32_ordinal414>
extern __imp_ws2_32_ordinal415:PANYARGS
ws2_32_ordinal415 TEXTEQU <__imp_ws2_32_ordinal415>
extern __imp_ws2_32_ordinal416:PANYARGS
ws2_32_ordinal416 TEXTEQU <__imp_ws2_32_ordinal416>
extern __imp_ws2_32_ordinal417:PANYARGS
ws2_32_ordinal417 TEXTEQU <__imp_ws2_32_ordinal417>
extern __imp_ws2_32_ordinal418:PANYARGS
ws2_32_ordinal418 TEXTEQU <__imp_ws2_32_ordinal418>
extern __imp_ws2_32_ordinal419:PANYARGS
ws2_32_ordinal419 TEXTEQU <__imp_ws2_32_ordinal419>
extern __imp_ws2_32_ordinal420:PANYARGS
ws2_32_ordinal420 TEXTEQU <__imp_ws2_32_ordinal420>
extern __imp_ws2_32_ordinal421:PANYARGS
ws2_32_ordinal421 TEXTEQU <__imp_ws2_32_ordinal421>
extern __imp_ws2_32_ordinal422:PANYARGS
ws2_32_ordinal422 TEXTEQU <__imp_ws2_32_ordinal422>
extern __imp_ws2_32_ordinal423:PANYARGS
ws2_32_ordinal423 TEXTEQU <__imp_ws2_32_ordinal423>
extern __imp_ws2_32_ordinal424:PANYARGS
ws2_32_ordinal424 TEXTEQU <__imp_ws2_32_ordinal424>
extern __imp_ws2_32_ordinal425:PANYARGS
ws2_32_ordinal425 TEXTEQU <__imp_ws2_32_ordinal425>
extern __imp_ws2_32_ordinal426:PANYARGS
ws2_32_ordinal426 TEXTEQU <__imp_ws2_32_ordinal426>
extern __imp_ws2_32_ordinal427:PANYARGS
ws2_32_ordinal427 TEXTEQU <__imp_ws2_32_ordinal427>
extern __imp_ws2_32_ordinal428:PANYARGS
ws2_32_ordinal428 TEXTEQU <__imp_ws2_32_ordinal428>
extern __imp_ws2_32_ordinal429:PANYARGS
ws2_32_ordinal429 TEXTEQU <__imp_ws2_32_ordinal429>
extern __imp_ws2_32_ordinal430:PANYARGS
ws2_32_ordinal430 TEXTEQU <__imp_ws2_32_ordinal430>
extern __imp_ws2_32_ordinal431:PANYARGS
ws2_32_ordinal431 TEXTEQU <__imp_ws2_32_ordinal431>
extern __imp_ws2_32_ordinal432:PANYARGS
ws2_32_ordinal432 TEXTEQU <__imp_ws2_32_ordinal432>
extern __imp_ws2_32_ordinal433:PANYARGS
ws2_32_ordinal433 TEXTEQU <__imp_ws2_32_ordinal433>
extern __imp_ws2_32_ordinal434:PANYARGS
ws2_32_ordinal434 TEXTEQU <__imp_ws2_32_ordinal434>
extern __imp_ws2_32_ordinal435:PANYARGS
ws2_32_ordinal435 TEXTEQU <__imp_ws2_32_ordinal435>
extern __imp_ws2_32_ordinal436:PANYARGS
ws2_32_ordinal436 TEXTEQU <__imp_ws2_32_ordinal436>
extern __imp_ws2_32_ordinal437:PANYARGS
ws2_32_ordinal437 TEXTEQU <__imp_ws2_32_ordinal437>
extern __imp_ws2_32_ordinal438:PANYARGS
ws2_32_ordinal438 TEXTEQU <__imp_ws2_32_ordinal438>
extern __imp_ws2_32_ordinal439:PANYARGS
ws2_32_ordinal439 TEXTEQU <__imp_ws2_32_ordinal439>
extern __imp_ws2_32_ordinal440:PANYARGS
ws2_32_ordinal440 TEXTEQU <__imp_ws2_32_ordinal440>
extern __imp_ws2_32_ordinal441:PANYARGS
ws2_32_ordinal441 TEXTEQU <__imp_ws2_32_ordinal441>
extern __imp_ws2_32_ordinal442:PANYARGS
ws2_32_ordinal442 TEXTEQU <__imp_ws2_32_ordinal442>
extern __imp_ws2_32_ordinal443:PANYARGS
ws2_32_ordinal443 TEXTEQU <__imp_ws2_32_ordinal443>
extern __imp_ws2_32_ordinal444:PANYARGS
ws2_32_ordinal444 TEXTEQU <__imp_ws2_32_ordinal444>
extern __imp_ws2_32_ordinal445:PANYARGS
ws2_32_ordinal445 TEXTEQU <__imp_ws2_32_ordinal445>
extern __imp_ws2_32_ordinal446:PANYARGS
ws2_32_ordinal446 TEXTEQU <__imp_ws2_32_ordinal446>
extern __imp_ws2_32_ordinal447:PANYARGS
ws2_32_ordinal447 TEXTEQU <__imp_ws2_32_ordinal447>
extern __imp_ws2_32_ordinal448:PANYARGS
ws2_32_ordinal448 TEXTEQU <__imp_ws2_32_ordinal448>
extern __imp_ws2_32_ordinal449:PANYARGS
ws2_32_ordinal449 TEXTEQU <__imp_ws2_32_ordinal449>
extern __imp_ws2_32_ordinal450:PANYARGS
ws2_32_ordinal450 TEXTEQU <__imp_ws2_32_ordinal450>
extern __imp_ws2_32_ordinal451:PANYARGS
ws2_32_ordinal451 TEXTEQU <__imp_ws2_32_ordinal451>
extern __imp_ws2_32_ordinal452:PANYARGS
ws2_32_ordinal452 TEXTEQU <__imp_ws2_32_ordinal452>
extern __imp_ws2_32_ordinal453:PANYARGS
ws2_32_ordinal453 TEXTEQU <__imp_ws2_32_ordinal453>
extern __imp_ws2_32_ordinal454:PANYARGS
ws2_32_ordinal454 TEXTEQU <__imp_ws2_32_ordinal454>
extern __imp_ws2_32_ordinal455:PANYARGS
ws2_32_ordinal455 TEXTEQU <__imp_ws2_32_ordinal455>
extern __imp_ws2_32_ordinal456:PANYARGS
ws2_32_ordinal456 TEXTEQU <__imp_ws2_32_ordinal456>
extern __imp_ws2_32_ordinal457:PANYARGS
ws2_32_ordinal457 TEXTEQU <__imp_ws2_32_ordinal457>
extern __imp_ws2_32_ordinal458:PANYARGS
ws2_32_ordinal458 TEXTEQU <__imp_ws2_32_ordinal458>
extern __imp_ws2_32_ordinal459:PANYARGS
ws2_32_ordinal459 TEXTEQU <__imp_ws2_32_ordinal459>
extern __imp_ws2_32_ordinal460:PANYARGS
ws2_32_ordinal460 TEXTEQU <__imp_ws2_32_ordinal460>
extern __imp_ws2_32_ordinal461:PANYARGS
ws2_32_ordinal461 TEXTEQU <__imp_ws2_32_ordinal461>
extern __imp_ws2_32_ordinal462:PANYARGS
ws2_32_ordinal462 TEXTEQU <__imp_ws2_32_ordinal462>
extern __imp_ws2_32_ordinal463:PANYARGS
ws2_32_ordinal463 TEXTEQU <__imp_ws2_32_ordinal463>
extern __imp_ws2_32_ordinal464:PANYARGS
ws2_32_ordinal464 TEXTEQU <__imp_ws2_32_ordinal464>
extern __imp_ws2_32_ordinal465:PANYARGS
ws2_32_ordinal465 TEXTEQU <__imp_ws2_32_ordinal465>
extern __imp_ws2_32_ordinal466:PANYARGS
ws2_32_ordinal466 TEXTEQU <__imp_ws2_32_ordinal466>
extern __imp_ws2_32_ordinal467:PANYARGS
ws2_32_ordinal467 TEXTEQU <__imp_ws2_32_ordinal467>
extern __imp_ws2_32_ordinal468:PANYARGS
ws2_32_ordinal468 TEXTEQU <__imp_ws2_32_ordinal468>
extern __imp_ws2_32_ordinal469:PANYARGS
ws2_32_ordinal469 TEXTEQU <__imp_ws2_32_ordinal469>
extern __imp_ws2_32_ordinal470:PANYARGS
ws2_32_ordinal470 TEXTEQU <__imp_ws2_32_ordinal470>
extern __imp_ws2_32_ordinal471:PANYARGS
ws2_32_ordinal471 TEXTEQU <__imp_ws2_32_ordinal471>
extern __imp_ws2_32_ordinal472:PANYARGS
ws2_32_ordinal472 TEXTEQU <__imp_ws2_32_ordinal472>
extern __imp_ws2_32_ordinal473:PANYARGS
ws2_32_ordinal473 TEXTEQU <__imp_ws2_32_ordinal473>
extern __imp_ws2_32_ordinal474:PANYARGS
ws2_32_ordinal474 TEXTEQU <__imp_ws2_32_ordinal474>
extern __imp_ws2_32_ordinal475:PANYARGS
ws2_32_ordinal475 TEXTEQU <__imp_ws2_32_ordinal475>
extern __imp_ws2_32_ordinal476:PANYARGS
ws2_32_ordinal476 TEXTEQU <__imp_ws2_32_ordinal476>
extern __imp_ws2_32_ordinal477:PANYARGS
ws2_32_ordinal477 TEXTEQU <__imp_ws2_32_ordinal477>
extern __imp_ws2_32_ordinal478:PANYARGS
ws2_32_ordinal478 TEXTEQU <__imp_ws2_32_ordinal478>
extern __imp_ws2_32_ordinal479:PANYARGS
ws2_32_ordinal479 TEXTEQU <__imp_ws2_32_ordinal479>
extern __imp_ws2_32_ordinal480:PANYARGS
ws2_32_ordinal480 TEXTEQU <__imp_ws2_32_ordinal480>
extern __imp_ws2_32_ordinal481:PANYARGS
ws2_32_ordinal481 TEXTEQU <__imp_ws2_32_ordinal481>
extern __imp_ws2_32_ordinal482:PANYARGS
ws2_32_ordinal482 TEXTEQU <__imp_ws2_32_ordinal482>
extern __imp_ws2_32_ordinal483:PANYARGS
ws2_32_ordinal483 TEXTEQU <__imp_ws2_32_ordinal483>
extern __imp_ws2_32_ordinal484:PANYARGS
ws2_32_ordinal484 TEXTEQU <__imp_ws2_32_ordinal484>
extern __imp_ws2_32_ordinal485:PANYARGS
ws2_32_ordinal485 TEXTEQU <__imp_ws2_32_ordinal485>
extern __imp_ws2_32_ordinal486:PANYARGS
ws2_32_ordinal486 TEXTEQU <__imp_ws2_32_ordinal486>
extern __imp_ws2_32_ordinal487:PANYARGS
ws2_32_ordinal487 TEXTEQU <__imp_ws2_32_ordinal487>
extern __imp_ws2_32_ordinal488:PANYARGS
ws2_32_ordinal488 TEXTEQU <__imp_ws2_32_ordinal488>
extern __imp_ws2_32_ordinal489:PANYARGS
ws2_32_ordinal489 TEXTEQU <__imp_ws2_32_ordinal489>
extern __imp_ws2_32_ordinal490:PANYARGS
ws2_32_ordinal490 TEXTEQU <__imp_ws2_32_ordinal490>
extern __imp_ws2_32_ordinal491:PANYARGS
ws2_32_ordinal491 TEXTEQU <__imp_ws2_32_ordinal491>
extern __imp_ws2_32_ordinal492:PANYARGS
ws2_32_ordinal492 TEXTEQU <__imp_ws2_32_ordinal492>
extern __imp_ws2_32_ordinal493:PANYARGS
ws2_32_ordinal493 TEXTEQU <__imp_ws2_32_ordinal493>
extern __imp_ws2_32_ordinal494:PANYARGS
ws2_32_ordinal494 TEXTEQU <__imp_ws2_32_ordinal494>
extern __imp_ws2_32_ordinal495:PANYARGS
ws2_32_ordinal495 TEXTEQU <__imp_ws2_32_ordinal495>
extern __imp_ws2_32_ordinal496:PANYARGS
ws2_32_ordinal496 TEXTEQU <__imp_ws2_32_ordinal496>
extern __imp_ws2_32_ordinal497:PANYARGS
ws2_32_ordinal497 TEXTEQU <__imp_ws2_32_ordinal497>
extern __imp_ws2_32_ordinal498:PANYARGS
ws2_32_ordinal498 TEXTEQU <__imp_ws2_32_ordinal498>
extern __imp_ws2_32_ordinal499:PANYARGS
ws2_32_ordinal499 TEXTEQU <__imp_ws2_32_ordinal499>
extern __imp_WEP:PANYARGS
WEP TEXTEQU <__imp_WEP>
