extern __imp_CreateIndirectData:PANYARGS
CreateIndirectData TEXTEQU <__imp_CreateIndirectData>
extern __imp_GetSignedDataMsg:PANYARGS
GetSignedDataMsg TEXTEQU <__imp_GetSignedDataMsg>
extern __imp_IsFileSupportedName:PANYARGS
IsFileSupportedName TEXTEQU <__imp_IsFileSupportedName>
extern __imp_PutSignedDataMsg:PANYARGS
PutSignedDataMsg TEXTEQU <__imp_PutSignedDataMsg>
extern __imp_RemoveSignedDataMsg:PANYARGS
RemoveSignedDataMsg TEXTEQU <__imp_RemoveSignedDataMsg>
extern __imp_VerifyIndirectData:PANYARGS
VerifyIndirectData TEXTEQU <__imp_VerifyIndirectData>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
