extern __imp_WSHEnumProtocols:PANYARGS
WSHEnumProtocols TEXTEQU <__imp_WSHEnumProtocols>
extern __imp_WSHGetProviderGuid:PANYARGS
WSHGetProviderGuid TEXTEQU <__imp_WSHGetProviderGuid>
extern __imp_WSHGetSockaddrType:PANYARGS
WSHGetSockaddrType TEXTEQU <__imp_WSHGetSockaddrType>
extern __imp_WSHGetSocketInformation:PANYARGS
WSHGetSocketInformation TEXTEQU <__imp_WSHGetSocketInformation>
extern __imp_WSHGetWSAProtocolInfo:PANYARGS
WSHGetWSAProtocolInfo TEXTEQU <__imp_WSHGetWSAProtocolInfo>
extern __imp_WSHGetWildcardSockaddr:PANYARGS
WSHGetWildcardSockaddr TEXTEQU <__imp_WSHGetWildcardSockaddr>
extern __imp_WSHGetWinsockMapping:PANYARGS
WSHGetWinsockMapping TEXTEQU <__imp_WSHGetWinsockMapping>
extern __imp_WSHIoctl:PANYARGS
WSHIoctl TEXTEQU <__imp_WSHIoctl>
extern __imp_WSHNotify:PANYARGS
WSHNotify TEXTEQU <__imp_WSHNotify>
extern __imp_WSHOpenSocket:PANYARGS
WSHOpenSocket TEXTEQU <__imp_WSHOpenSocket>
extern __imp_WSHSetSocketInformation:PANYARGS
WSHSetSocketInformation TEXTEQU <__imp_WSHSetSocketInformation>
