extern __imp_SnmpGetTranslateMode:PANYARGS
SnmpGetTranslateMode TEXTEQU <__imp_SnmpGetTranslateMode>
extern __imp_SnmpSetTranslateMode:PANYARGS
SnmpSetTranslateMode TEXTEQU <__imp_SnmpSetTranslateMode>
extern __imp_SnmpGetRetransmitMode:PANYARGS
SnmpGetRetransmitMode TEXTEQU <__imp_SnmpGetRetransmitMode>
extern __imp_SnmpSetRetransmitMode:PANYARGS
SnmpSetRetransmitMode TEXTEQU <__imp_SnmpSetRetransmitMode>
extern __imp_SnmpGetTimeout:PANYARGS
SnmpGetTimeout TEXTEQU <__imp_SnmpGetTimeout>
extern __imp_SnmpSetTimeout:PANYARGS
SnmpSetTimeout TEXTEQU <__imp_SnmpSetTimeout>
extern __imp_SnmpGetRetry:PANYARGS
SnmpGetRetry TEXTEQU <__imp_SnmpGetRetry>
extern __imp_SnmpSetRetry:PANYARGS
SnmpSetRetry TEXTEQU <__imp_SnmpSetRetry>
extern __imp_SnmpConveyAgentAddress:PANYARGS
SnmpConveyAgentAddress TEXTEQU <__imp_SnmpConveyAgentAddress>
extern __imp_SnmpSetAgentAddress:PANYARGS
SnmpSetAgentAddress TEXTEQU <__imp_SnmpSetAgentAddress>
extern __imp_wsnmp32_ordinal110:PANYARGS
wsnmp32_ordinal110 TEXTEQU <__imp_wsnmp32_ordinal110>
extern __imp_wsnmp32_ordinal111:PANYARGS
wsnmp32_ordinal111 TEXTEQU <__imp_wsnmp32_ordinal111>
extern __imp_wsnmp32_ordinal112:PANYARGS
wsnmp32_ordinal112 TEXTEQU <__imp_wsnmp32_ordinal112>
extern __imp_wsnmp32_ordinal113:PANYARGS
wsnmp32_ordinal113 TEXTEQU <__imp_wsnmp32_ordinal113>
extern __imp_wsnmp32_ordinal114:PANYARGS
wsnmp32_ordinal114 TEXTEQU <__imp_wsnmp32_ordinal114>
extern __imp_wsnmp32_ordinal115:PANYARGS
wsnmp32_ordinal115 TEXTEQU <__imp_wsnmp32_ordinal115>
extern __imp_wsnmp32_ordinal116:PANYARGS
wsnmp32_ordinal116 TEXTEQU <__imp_wsnmp32_ordinal116>
extern __imp_wsnmp32_ordinal117:PANYARGS
wsnmp32_ordinal117 TEXTEQU <__imp_wsnmp32_ordinal117>
extern __imp_wsnmp32_ordinal118:PANYARGS
wsnmp32_ordinal118 TEXTEQU <__imp_wsnmp32_ordinal118>
extern __imp_wsnmp32_ordinal119:PANYARGS
wsnmp32_ordinal119 TEXTEQU <__imp_wsnmp32_ordinal119>
extern __imp_SnmpGetVendorInfo:PANYARGS
SnmpGetVendorInfo TEXTEQU <__imp_SnmpGetVendorInfo>
extern __imp_wsnmp32_ordinal121:PANYARGS
wsnmp32_ordinal121 TEXTEQU <__imp_wsnmp32_ordinal121>
extern __imp_wsnmp32_ordinal122:PANYARGS
wsnmp32_ordinal122 TEXTEQU <__imp_wsnmp32_ordinal122>
extern __imp_wsnmp32_ordinal123:PANYARGS
wsnmp32_ordinal123 TEXTEQU <__imp_wsnmp32_ordinal123>
extern __imp_wsnmp32_ordinal124:PANYARGS
wsnmp32_ordinal124 TEXTEQU <__imp_wsnmp32_ordinal124>
extern __imp_wsnmp32_ordinal125:PANYARGS
wsnmp32_ordinal125 TEXTEQU <__imp_wsnmp32_ordinal125>
extern __imp_wsnmp32_ordinal126:PANYARGS
wsnmp32_ordinal126 TEXTEQU <__imp_wsnmp32_ordinal126>
extern __imp_wsnmp32_ordinal127:PANYARGS
wsnmp32_ordinal127 TEXTEQU <__imp_wsnmp32_ordinal127>
extern __imp_wsnmp32_ordinal128:PANYARGS
wsnmp32_ordinal128 TEXTEQU <__imp_wsnmp32_ordinal128>
extern __imp_wsnmp32_ordinal129:PANYARGS
wsnmp32_ordinal129 TEXTEQU <__imp_wsnmp32_ordinal129>
extern __imp_wsnmp32_ordinal130:PANYARGS
wsnmp32_ordinal130 TEXTEQU <__imp_wsnmp32_ordinal130>
extern __imp_wsnmp32_ordinal131:PANYARGS
wsnmp32_ordinal131 TEXTEQU <__imp_wsnmp32_ordinal131>
extern __imp_wsnmp32_ordinal132:PANYARGS
wsnmp32_ordinal132 TEXTEQU <__imp_wsnmp32_ordinal132>
extern __imp_wsnmp32_ordinal133:PANYARGS
wsnmp32_ordinal133 TEXTEQU <__imp_wsnmp32_ordinal133>
extern __imp_wsnmp32_ordinal134:PANYARGS
wsnmp32_ordinal134 TEXTEQU <__imp_wsnmp32_ordinal134>
extern __imp_wsnmp32_ordinal135:PANYARGS
wsnmp32_ordinal135 TEXTEQU <__imp_wsnmp32_ordinal135>
extern __imp_wsnmp32_ordinal136:PANYARGS
wsnmp32_ordinal136 TEXTEQU <__imp_wsnmp32_ordinal136>
extern __imp_wsnmp32_ordinal137:PANYARGS
wsnmp32_ordinal137 TEXTEQU <__imp_wsnmp32_ordinal137>
extern __imp_wsnmp32_ordinal138:PANYARGS
wsnmp32_ordinal138 TEXTEQU <__imp_wsnmp32_ordinal138>
extern __imp_wsnmp32_ordinal139:PANYARGS
wsnmp32_ordinal139 TEXTEQU <__imp_wsnmp32_ordinal139>
extern __imp_wsnmp32_ordinal140:PANYARGS
wsnmp32_ordinal140 TEXTEQU <__imp_wsnmp32_ordinal140>
extern __imp_wsnmp32_ordinal141:PANYARGS
wsnmp32_ordinal141 TEXTEQU <__imp_wsnmp32_ordinal141>
extern __imp_wsnmp32_ordinal142:PANYARGS
wsnmp32_ordinal142 TEXTEQU <__imp_wsnmp32_ordinal142>
extern __imp_wsnmp32_ordinal143:PANYARGS
wsnmp32_ordinal143 TEXTEQU <__imp_wsnmp32_ordinal143>
extern __imp_wsnmp32_ordinal144:PANYARGS
wsnmp32_ordinal144 TEXTEQU <__imp_wsnmp32_ordinal144>
extern __imp_wsnmp32_ordinal145:PANYARGS
wsnmp32_ordinal145 TEXTEQU <__imp_wsnmp32_ordinal145>
extern __imp_wsnmp32_ordinal146:PANYARGS
wsnmp32_ordinal146 TEXTEQU <__imp_wsnmp32_ordinal146>
extern __imp_wsnmp32_ordinal147:PANYARGS
wsnmp32_ordinal147 TEXTEQU <__imp_wsnmp32_ordinal147>
extern __imp_wsnmp32_ordinal148:PANYARGS
wsnmp32_ordinal148 TEXTEQU <__imp_wsnmp32_ordinal148>
extern __imp_wsnmp32_ordinal149:PANYARGS
wsnmp32_ordinal149 TEXTEQU <__imp_wsnmp32_ordinal149>
extern __imp_wsnmp32_ordinal150:PANYARGS
wsnmp32_ordinal150 TEXTEQU <__imp_wsnmp32_ordinal150>
extern __imp_wsnmp32_ordinal151:PANYARGS
wsnmp32_ordinal151 TEXTEQU <__imp_wsnmp32_ordinal151>
extern __imp_wsnmp32_ordinal152:PANYARGS
wsnmp32_ordinal152 TEXTEQU <__imp_wsnmp32_ordinal152>
extern __imp_wsnmp32_ordinal153:PANYARGS
wsnmp32_ordinal153 TEXTEQU <__imp_wsnmp32_ordinal153>
extern __imp_wsnmp32_ordinal154:PANYARGS
wsnmp32_ordinal154 TEXTEQU <__imp_wsnmp32_ordinal154>
extern __imp_wsnmp32_ordinal155:PANYARGS
wsnmp32_ordinal155 TEXTEQU <__imp_wsnmp32_ordinal155>
extern __imp_wsnmp32_ordinal156:PANYARGS
wsnmp32_ordinal156 TEXTEQU <__imp_wsnmp32_ordinal156>
extern __imp_wsnmp32_ordinal157:PANYARGS
wsnmp32_ordinal157 TEXTEQU <__imp_wsnmp32_ordinal157>
extern __imp_wsnmp32_ordinal158:PANYARGS
wsnmp32_ordinal158 TEXTEQU <__imp_wsnmp32_ordinal158>
extern __imp_wsnmp32_ordinal159:PANYARGS
wsnmp32_ordinal159 TEXTEQU <__imp_wsnmp32_ordinal159>
extern __imp_wsnmp32_ordinal160:PANYARGS
wsnmp32_ordinal160 TEXTEQU <__imp_wsnmp32_ordinal160>
extern __imp_wsnmp32_ordinal161:PANYARGS
wsnmp32_ordinal161 TEXTEQU <__imp_wsnmp32_ordinal161>
extern __imp_wsnmp32_ordinal162:PANYARGS
wsnmp32_ordinal162 TEXTEQU <__imp_wsnmp32_ordinal162>
extern __imp_wsnmp32_ordinal163:PANYARGS
wsnmp32_ordinal163 TEXTEQU <__imp_wsnmp32_ordinal163>
extern __imp_wsnmp32_ordinal164:PANYARGS
wsnmp32_ordinal164 TEXTEQU <__imp_wsnmp32_ordinal164>
extern __imp_wsnmp32_ordinal165:PANYARGS
wsnmp32_ordinal165 TEXTEQU <__imp_wsnmp32_ordinal165>
extern __imp_wsnmp32_ordinal166:PANYARGS
wsnmp32_ordinal166 TEXTEQU <__imp_wsnmp32_ordinal166>
extern __imp_wsnmp32_ordinal167:PANYARGS
wsnmp32_ordinal167 TEXTEQU <__imp_wsnmp32_ordinal167>
extern __imp_wsnmp32_ordinal168:PANYARGS
wsnmp32_ordinal168 TEXTEQU <__imp_wsnmp32_ordinal168>
extern __imp_wsnmp32_ordinal169:PANYARGS
wsnmp32_ordinal169 TEXTEQU <__imp_wsnmp32_ordinal169>
extern __imp_wsnmp32_ordinal170:PANYARGS
wsnmp32_ordinal170 TEXTEQU <__imp_wsnmp32_ordinal170>
extern __imp_wsnmp32_ordinal171:PANYARGS
wsnmp32_ordinal171 TEXTEQU <__imp_wsnmp32_ordinal171>
extern __imp_wsnmp32_ordinal172:PANYARGS
wsnmp32_ordinal172 TEXTEQU <__imp_wsnmp32_ordinal172>
extern __imp_wsnmp32_ordinal173:PANYARGS
wsnmp32_ordinal173 TEXTEQU <__imp_wsnmp32_ordinal173>
extern __imp_wsnmp32_ordinal174:PANYARGS
wsnmp32_ordinal174 TEXTEQU <__imp_wsnmp32_ordinal174>
extern __imp_wsnmp32_ordinal175:PANYARGS
wsnmp32_ordinal175 TEXTEQU <__imp_wsnmp32_ordinal175>
extern __imp_wsnmp32_ordinal176:PANYARGS
wsnmp32_ordinal176 TEXTEQU <__imp_wsnmp32_ordinal176>
extern __imp_wsnmp32_ordinal177:PANYARGS
wsnmp32_ordinal177 TEXTEQU <__imp_wsnmp32_ordinal177>
extern __imp_wsnmp32_ordinal178:PANYARGS
wsnmp32_ordinal178 TEXTEQU <__imp_wsnmp32_ordinal178>
extern __imp_wsnmp32_ordinal179:PANYARGS
wsnmp32_ordinal179 TEXTEQU <__imp_wsnmp32_ordinal179>
extern __imp_wsnmp32_ordinal180:PANYARGS
wsnmp32_ordinal180 TEXTEQU <__imp_wsnmp32_ordinal180>
extern __imp_wsnmp32_ordinal181:PANYARGS
wsnmp32_ordinal181 TEXTEQU <__imp_wsnmp32_ordinal181>
extern __imp_wsnmp32_ordinal182:PANYARGS
wsnmp32_ordinal182 TEXTEQU <__imp_wsnmp32_ordinal182>
extern __imp_wsnmp32_ordinal183:PANYARGS
wsnmp32_ordinal183 TEXTEQU <__imp_wsnmp32_ordinal183>
extern __imp_wsnmp32_ordinal184:PANYARGS
wsnmp32_ordinal184 TEXTEQU <__imp_wsnmp32_ordinal184>
extern __imp_wsnmp32_ordinal185:PANYARGS
wsnmp32_ordinal185 TEXTEQU <__imp_wsnmp32_ordinal185>
extern __imp_wsnmp32_ordinal186:PANYARGS
wsnmp32_ordinal186 TEXTEQU <__imp_wsnmp32_ordinal186>
extern __imp_wsnmp32_ordinal187:PANYARGS
wsnmp32_ordinal187 TEXTEQU <__imp_wsnmp32_ordinal187>
extern __imp_wsnmp32_ordinal188:PANYARGS
wsnmp32_ordinal188 TEXTEQU <__imp_wsnmp32_ordinal188>
extern __imp_wsnmp32_ordinal189:PANYARGS
wsnmp32_ordinal189 TEXTEQU <__imp_wsnmp32_ordinal189>
extern __imp_wsnmp32_ordinal190:PANYARGS
wsnmp32_ordinal190 TEXTEQU <__imp_wsnmp32_ordinal190>
extern __imp_wsnmp32_ordinal191:PANYARGS
wsnmp32_ordinal191 TEXTEQU <__imp_wsnmp32_ordinal191>
extern __imp_wsnmp32_ordinal192:PANYARGS
wsnmp32_ordinal192 TEXTEQU <__imp_wsnmp32_ordinal192>
extern __imp_wsnmp32_ordinal193:PANYARGS
wsnmp32_ordinal193 TEXTEQU <__imp_wsnmp32_ordinal193>
extern __imp_wsnmp32_ordinal194:PANYARGS
wsnmp32_ordinal194 TEXTEQU <__imp_wsnmp32_ordinal194>
extern __imp_wsnmp32_ordinal195:PANYARGS
wsnmp32_ordinal195 TEXTEQU <__imp_wsnmp32_ordinal195>
extern __imp_wsnmp32_ordinal196:PANYARGS
wsnmp32_ordinal196 TEXTEQU <__imp_wsnmp32_ordinal196>
extern __imp_wsnmp32_ordinal197:PANYARGS
wsnmp32_ordinal197 TEXTEQU <__imp_wsnmp32_ordinal197>
extern __imp_wsnmp32_ordinal198:PANYARGS
wsnmp32_ordinal198 TEXTEQU <__imp_wsnmp32_ordinal198>
extern __imp_wsnmp32_ordinal199:PANYARGS
wsnmp32_ordinal199 TEXTEQU <__imp_wsnmp32_ordinal199>
extern __imp_SnmpStartup:PANYARGS
SnmpStartup TEXTEQU <__imp_SnmpStartup>
extern __imp_SnmpCleanup:PANYARGS
SnmpCleanup TEXTEQU <__imp_SnmpCleanup>
extern __imp_SnmpOpen:PANYARGS
SnmpOpen TEXTEQU <__imp_SnmpOpen>
extern __imp_SnmpClose:PANYARGS
SnmpClose TEXTEQU <__imp_SnmpClose>
extern __imp_SnmpSendMsg:PANYARGS
SnmpSendMsg TEXTEQU <__imp_SnmpSendMsg>
extern __imp_SnmpRecvMsg:PANYARGS
SnmpRecvMsg TEXTEQU <__imp_SnmpRecvMsg>
extern __imp_SnmpRegister:PANYARGS
SnmpRegister TEXTEQU <__imp_SnmpRegister>
extern __imp_wsnmp32_ordinal207:PANYARGS
wsnmp32_ordinal207 TEXTEQU <__imp_wsnmp32_ordinal207>
extern __imp_wsnmp32_ordinal208:PANYARGS
wsnmp32_ordinal208 TEXTEQU <__imp_wsnmp32_ordinal208>
extern __imp_wsnmp32_ordinal209:PANYARGS
wsnmp32_ordinal209 TEXTEQU <__imp_wsnmp32_ordinal209>
extern __imp_wsnmp32_ordinal210:PANYARGS
wsnmp32_ordinal210 TEXTEQU <__imp_wsnmp32_ordinal210>
extern __imp_wsnmp32_ordinal211:PANYARGS
wsnmp32_ordinal211 TEXTEQU <__imp_wsnmp32_ordinal211>
extern __imp_wsnmp32_ordinal212:PANYARGS
wsnmp32_ordinal212 TEXTEQU <__imp_wsnmp32_ordinal212>
extern __imp_wsnmp32_ordinal213:PANYARGS
wsnmp32_ordinal213 TEXTEQU <__imp_wsnmp32_ordinal213>
extern __imp_wsnmp32_ordinal214:PANYARGS
wsnmp32_ordinal214 TEXTEQU <__imp_wsnmp32_ordinal214>
extern __imp_wsnmp32_ordinal215:PANYARGS
wsnmp32_ordinal215 TEXTEQU <__imp_wsnmp32_ordinal215>
extern __imp_wsnmp32_ordinal216:PANYARGS
wsnmp32_ordinal216 TEXTEQU <__imp_wsnmp32_ordinal216>
extern __imp_wsnmp32_ordinal217:PANYARGS
wsnmp32_ordinal217 TEXTEQU <__imp_wsnmp32_ordinal217>
extern __imp_wsnmp32_ordinal218:PANYARGS
wsnmp32_ordinal218 TEXTEQU <__imp_wsnmp32_ordinal218>
extern __imp_wsnmp32_ordinal219:PANYARGS
wsnmp32_ordinal219 TEXTEQU <__imp_wsnmp32_ordinal219>
extern __imp_SnmpCreateSession:PANYARGS
SnmpCreateSession TEXTEQU <__imp_SnmpCreateSession>
extern __imp_SnmpListen:PANYARGS
SnmpListen TEXTEQU <__imp_SnmpListen>
extern __imp_SnmpCancelMsg:PANYARGS
SnmpCancelMsg TEXTEQU <__imp_SnmpCancelMsg>
extern __imp_wsnmp32_ordinal223:PANYARGS
wsnmp32_ordinal223 TEXTEQU <__imp_wsnmp32_ordinal223>
extern __imp_wsnmp32_ordinal224:PANYARGS
wsnmp32_ordinal224 TEXTEQU <__imp_wsnmp32_ordinal224>
extern __imp_wsnmp32_ordinal225:PANYARGS
wsnmp32_ordinal225 TEXTEQU <__imp_wsnmp32_ordinal225>
extern __imp_wsnmp32_ordinal226:PANYARGS
wsnmp32_ordinal226 TEXTEQU <__imp_wsnmp32_ordinal226>
extern __imp_wsnmp32_ordinal227:PANYARGS
wsnmp32_ordinal227 TEXTEQU <__imp_wsnmp32_ordinal227>
extern __imp_wsnmp32_ordinal228:PANYARGS
wsnmp32_ordinal228 TEXTEQU <__imp_wsnmp32_ordinal228>
extern __imp_wsnmp32_ordinal229:PANYARGS
wsnmp32_ordinal229 TEXTEQU <__imp_wsnmp32_ordinal229>
extern __imp_wsnmp32_ordinal230:PANYARGS
wsnmp32_ordinal230 TEXTEQU <__imp_wsnmp32_ordinal230>
extern __imp_wsnmp32_ordinal231:PANYARGS
wsnmp32_ordinal231 TEXTEQU <__imp_wsnmp32_ordinal231>
extern __imp_wsnmp32_ordinal232:PANYARGS
wsnmp32_ordinal232 TEXTEQU <__imp_wsnmp32_ordinal232>
extern __imp_wsnmp32_ordinal233:PANYARGS
wsnmp32_ordinal233 TEXTEQU <__imp_wsnmp32_ordinal233>
extern __imp_wsnmp32_ordinal234:PANYARGS
wsnmp32_ordinal234 TEXTEQU <__imp_wsnmp32_ordinal234>
extern __imp_wsnmp32_ordinal235:PANYARGS
wsnmp32_ordinal235 TEXTEQU <__imp_wsnmp32_ordinal235>
extern __imp_wsnmp32_ordinal236:PANYARGS
wsnmp32_ordinal236 TEXTEQU <__imp_wsnmp32_ordinal236>
extern __imp_wsnmp32_ordinal237:PANYARGS
wsnmp32_ordinal237 TEXTEQU <__imp_wsnmp32_ordinal237>
extern __imp_wsnmp32_ordinal238:PANYARGS
wsnmp32_ordinal238 TEXTEQU <__imp_wsnmp32_ordinal238>
extern __imp_wsnmp32_ordinal239:PANYARGS
wsnmp32_ordinal239 TEXTEQU <__imp_wsnmp32_ordinal239>
extern __imp_wsnmp32_ordinal240:PANYARGS
wsnmp32_ordinal240 TEXTEQU <__imp_wsnmp32_ordinal240>
extern __imp_wsnmp32_ordinal241:PANYARGS
wsnmp32_ordinal241 TEXTEQU <__imp_wsnmp32_ordinal241>
extern __imp_wsnmp32_ordinal242:PANYARGS
wsnmp32_ordinal242 TEXTEQU <__imp_wsnmp32_ordinal242>
extern __imp_wsnmp32_ordinal243:PANYARGS
wsnmp32_ordinal243 TEXTEQU <__imp_wsnmp32_ordinal243>
extern __imp_wsnmp32_ordinal244:PANYARGS
wsnmp32_ordinal244 TEXTEQU <__imp_wsnmp32_ordinal244>
extern __imp_wsnmp32_ordinal245:PANYARGS
wsnmp32_ordinal245 TEXTEQU <__imp_wsnmp32_ordinal245>
extern __imp_wsnmp32_ordinal246:PANYARGS
wsnmp32_ordinal246 TEXTEQU <__imp_wsnmp32_ordinal246>
extern __imp_wsnmp32_ordinal247:PANYARGS
wsnmp32_ordinal247 TEXTEQU <__imp_wsnmp32_ordinal247>
extern __imp_wsnmp32_ordinal248:PANYARGS
wsnmp32_ordinal248 TEXTEQU <__imp_wsnmp32_ordinal248>
extern __imp_wsnmp32_ordinal249:PANYARGS
wsnmp32_ordinal249 TEXTEQU <__imp_wsnmp32_ordinal249>
extern __imp_wsnmp32_ordinal250:PANYARGS
wsnmp32_ordinal250 TEXTEQU <__imp_wsnmp32_ordinal250>
extern __imp_wsnmp32_ordinal251:PANYARGS
wsnmp32_ordinal251 TEXTEQU <__imp_wsnmp32_ordinal251>
extern __imp_wsnmp32_ordinal252:PANYARGS
wsnmp32_ordinal252 TEXTEQU <__imp_wsnmp32_ordinal252>
extern __imp_wsnmp32_ordinal253:PANYARGS
wsnmp32_ordinal253 TEXTEQU <__imp_wsnmp32_ordinal253>
extern __imp_wsnmp32_ordinal254:PANYARGS
wsnmp32_ordinal254 TEXTEQU <__imp_wsnmp32_ordinal254>
extern __imp_wsnmp32_ordinal255:PANYARGS
wsnmp32_ordinal255 TEXTEQU <__imp_wsnmp32_ordinal255>
extern __imp_wsnmp32_ordinal256:PANYARGS
wsnmp32_ordinal256 TEXTEQU <__imp_wsnmp32_ordinal256>
extern __imp_wsnmp32_ordinal257:PANYARGS
wsnmp32_ordinal257 TEXTEQU <__imp_wsnmp32_ordinal257>
extern __imp_wsnmp32_ordinal258:PANYARGS
wsnmp32_ordinal258 TEXTEQU <__imp_wsnmp32_ordinal258>
extern __imp_wsnmp32_ordinal259:PANYARGS
wsnmp32_ordinal259 TEXTEQU <__imp_wsnmp32_ordinal259>
extern __imp_wsnmp32_ordinal260:PANYARGS
wsnmp32_ordinal260 TEXTEQU <__imp_wsnmp32_ordinal260>
extern __imp_wsnmp32_ordinal261:PANYARGS
wsnmp32_ordinal261 TEXTEQU <__imp_wsnmp32_ordinal261>
extern __imp_wsnmp32_ordinal262:PANYARGS
wsnmp32_ordinal262 TEXTEQU <__imp_wsnmp32_ordinal262>
extern __imp_wsnmp32_ordinal263:PANYARGS
wsnmp32_ordinal263 TEXTEQU <__imp_wsnmp32_ordinal263>
extern __imp_wsnmp32_ordinal264:PANYARGS
wsnmp32_ordinal264 TEXTEQU <__imp_wsnmp32_ordinal264>
extern __imp_wsnmp32_ordinal265:PANYARGS
wsnmp32_ordinal265 TEXTEQU <__imp_wsnmp32_ordinal265>
extern __imp_wsnmp32_ordinal266:PANYARGS
wsnmp32_ordinal266 TEXTEQU <__imp_wsnmp32_ordinal266>
extern __imp_wsnmp32_ordinal267:PANYARGS
wsnmp32_ordinal267 TEXTEQU <__imp_wsnmp32_ordinal267>
extern __imp_wsnmp32_ordinal268:PANYARGS
wsnmp32_ordinal268 TEXTEQU <__imp_wsnmp32_ordinal268>
extern __imp_wsnmp32_ordinal269:PANYARGS
wsnmp32_ordinal269 TEXTEQU <__imp_wsnmp32_ordinal269>
extern __imp_wsnmp32_ordinal270:PANYARGS
wsnmp32_ordinal270 TEXTEQU <__imp_wsnmp32_ordinal270>
extern __imp_wsnmp32_ordinal271:PANYARGS
wsnmp32_ordinal271 TEXTEQU <__imp_wsnmp32_ordinal271>
extern __imp_wsnmp32_ordinal272:PANYARGS
wsnmp32_ordinal272 TEXTEQU <__imp_wsnmp32_ordinal272>
extern __imp_wsnmp32_ordinal273:PANYARGS
wsnmp32_ordinal273 TEXTEQU <__imp_wsnmp32_ordinal273>
extern __imp_wsnmp32_ordinal274:PANYARGS
wsnmp32_ordinal274 TEXTEQU <__imp_wsnmp32_ordinal274>
extern __imp_wsnmp32_ordinal275:PANYARGS
wsnmp32_ordinal275 TEXTEQU <__imp_wsnmp32_ordinal275>
extern __imp_wsnmp32_ordinal276:PANYARGS
wsnmp32_ordinal276 TEXTEQU <__imp_wsnmp32_ordinal276>
extern __imp_wsnmp32_ordinal277:PANYARGS
wsnmp32_ordinal277 TEXTEQU <__imp_wsnmp32_ordinal277>
extern __imp_wsnmp32_ordinal278:PANYARGS
wsnmp32_ordinal278 TEXTEQU <__imp_wsnmp32_ordinal278>
extern __imp_wsnmp32_ordinal279:PANYARGS
wsnmp32_ordinal279 TEXTEQU <__imp_wsnmp32_ordinal279>
extern __imp_wsnmp32_ordinal280:PANYARGS
wsnmp32_ordinal280 TEXTEQU <__imp_wsnmp32_ordinal280>
extern __imp_wsnmp32_ordinal281:PANYARGS
wsnmp32_ordinal281 TEXTEQU <__imp_wsnmp32_ordinal281>
extern __imp_wsnmp32_ordinal282:PANYARGS
wsnmp32_ordinal282 TEXTEQU <__imp_wsnmp32_ordinal282>
extern __imp_wsnmp32_ordinal283:PANYARGS
wsnmp32_ordinal283 TEXTEQU <__imp_wsnmp32_ordinal283>
extern __imp_wsnmp32_ordinal284:PANYARGS
wsnmp32_ordinal284 TEXTEQU <__imp_wsnmp32_ordinal284>
extern __imp_wsnmp32_ordinal285:PANYARGS
wsnmp32_ordinal285 TEXTEQU <__imp_wsnmp32_ordinal285>
extern __imp_wsnmp32_ordinal286:PANYARGS
wsnmp32_ordinal286 TEXTEQU <__imp_wsnmp32_ordinal286>
extern __imp_wsnmp32_ordinal287:PANYARGS
wsnmp32_ordinal287 TEXTEQU <__imp_wsnmp32_ordinal287>
extern __imp_wsnmp32_ordinal288:PANYARGS
wsnmp32_ordinal288 TEXTEQU <__imp_wsnmp32_ordinal288>
extern __imp_wsnmp32_ordinal289:PANYARGS
wsnmp32_ordinal289 TEXTEQU <__imp_wsnmp32_ordinal289>
extern __imp_wsnmp32_ordinal290:PANYARGS
wsnmp32_ordinal290 TEXTEQU <__imp_wsnmp32_ordinal290>
extern __imp_SnmpStartupEx:PANYARGS
SnmpStartupEx TEXTEQU <__imp_SnmpStartupEx>
extern __imp_SnmpCleanupEx:PANYARGS
SnmpCleanupEx TEXTEQU <__imp_SnmpCleanupEx>
extern __imp_wsnmp32_ordinal293:PANYARGS
wsnmp32_ordinal293 TEXTEQU <__imp_wsnmp32_ordinal293>
extern __imp_wsnmp32_ordinal294:PANYARGS
wsnmp32_ordinal294 TEXTEQU <__imp_wsnmp32_ordinal294>
extern __imp_wsnmp32_ordinal295:PANYARGS
wsnmp32_ordinal295 TEXTEQU <__imp_wsnmp32_ordinal295>
extern __imp_wsnmp32_ordinal296:PANYARGS
wsnmp32_ordinal296 TEXTEQU <__imp_wsnmp32_ordinal296>
extern __imp_wsnmp32_ordinal297:PANYARGS
wsnmp32_ordinal297 TEXTEQU <__imp_wsnmp32_ordinal297>
extern __imp_wsnmp32_ordinal298:PANYARGS
wsnmp32_ordinal298 TEXTEQU <__imp_wsnmp32_ordinal298>
extern __imp_wsnmp32_ordinal299:PANYARGS
wsnmp32_ordinal299 TEXTEQU <__imp_wsnmp32_ordinal299>
extern __imp_SnmpStrToEntity:PANYARGS
SnmpStrToEntity TEXTEQU <__imp_SnmpStrToEntity>
extern __imp_SnmpEntityToStr:PANYARGS
SnmpEntityToStr TEXTEQU <__imp_SnmpEntityToStr>
extern __imp_SnmpFreeEntity:PANYARGS
SnmpFreeEntity TEXTEQU <__imp_SnmpFreeEntity>
extern __imp_wsnmp32_ordinal303:PANYARGS
wsnmp32_ordinal303 TEXTEQU <__imp_wsnmp32_ordinal303>
extern __imp_wsnmp32_ordinal304:PANYARGS
wsnmp32_ordinal304 TEXTEQU <__imp_wsnmp32_ordinal304>
extern __imp_wsnmp32_ordinal305:PANYARGS
wsnmp32_ordinal305 TEXTEQU <__imp_wsnmp32_ordinal305>
extern __imp_wsnmp32_ordinal306:PANYARGS
wsnmp32_ordinal306 TEXTEQU <__imp_wsnmp32_ordinal306>
extern __imp_wsnmp32_ordinal307:PANYARGS
wsnmp32_ordinal307 TEXTEQU <__imp_wsnmp32_ordinal307>
extern __imp_wsnmp32_ordinal308:PANYARGS
wsnmp32_ordinal308 TEXTEQU <__imp_wsnmp32_ordinal308>
extern __imp_wsnmp32_ordinal309:PANYARGS
wsnmp32_ordinal309 TEXTEQU <__imp_wsnmp32_ordinal309>
extern __imp_wsnmp32_ordinal310:PANYARGS
wsnmp32_ordinal310 TEXTEQU <__imp_wsnmp32_ordinal310>
extern __imp_wsnmp32_ordinal311:PANYARGS
wsnmp32_ordinal311 TEXTEQU <__imp_wsnmp32_ordinal311>
extern __imp_wsnmp32_ordinal312:PANYARGS
wsnmp32_ordinal312 TEXTEQU <__imp_wsnmp32_ordinal312>
extern __imp_wsnmp32_ordinal313:PANYARGS
wsnmp32_ordinal313 TEXTEQU <__imp_wsnmp32_ordinal313>
extern __imp_wsnmp32_ordinal314:PANYARGS
wsnmp32_ordinal314 TEXTEQU <__imp_wsnmp32_ordinal314>
extern __imp_wsnmp32_ordinal315:PANYARGS
wsnmp32_ordinal315 TEXTEQU <__imp_wsnmp32_ordinal315>
extern __imp_wsnmp32_ordinal316:PANYARGS
wsnmp32_ordinal316 TEXTEQU <__imp_wsnmp32_ordinal316>
extern __imp_wsnmp32_ordinal317:PANYARGS
wsnmp32_ordinal317 TEXTEQU <__imp_wsnmp32_ordinal317>
extern __imp_wsnmp32_ordinal318:PANYARGS
wsnmp32_ordinal318 TEXTEQU <__imp_wsnmp32_ordinal318>
extern __imp_wsnmp32_ordinal319:PANYARGS
wsnmp32_ordinal319 TEXTEQU <__imp_wsnmp32_ordinal319>
extern __imp_SnmpSetPort:PANYARGS
SnmpSetPort TEXTEQU <__imp_SnmpSetPort>
extern __imp_wsnmp32_ordinal321:PANYARGS
wsnmp32_ordinal321 TEXTEQU <__imp_wsnmp32_ordinal321>
extern __imp_wsnmp32_ordinal322:PANYARGS
wsnmp32_ordinal322 TEXTEQU <__imp_wsnmp32_ordinal322>
extern __imp_wsnmp32_ordinal323:PANYARGS
wsnmp32_ordinal323 TEXTEQU <__imp_wsnmp32_ordinal323>
extern __imp_wsnmp32_ordinal324:PANYARGS
wsnmp32_ordinal324 TEXTEQU <__imp_wsnmp32_ordinal324>
extern __imp_wsnmp32_ordinal325:PANYARGS
wsnmp32_ordinal325 TEXTEQU <__imp_wsnmp32_ordinal325>
extern __imp_wsnmp32_ordinal326:PANYARGS
wsnmp32_ordinal326 TEXTEQU <__imp_wsnmp32_ordinal326>
extern __imp_wsnmp32_ordinal327:PANYARGS
wsnmp32_ordinal327 TEXTEQU <__imp_wsnmp32_ordinal327>
extern __imp_wsnmp32_ordinal328:PANYARGS
wsnmp32_ordinal328 TEXTEQU <__imp_wsnmp32_ordinal328>
extern __imp_wsnmp32_ordinal329:PANYARGS
wsnmp32_ordinal329 TEXTEQU <__imp_wsnmp32_ordinal329>
extern __imp_wsnmp32_ordinal330:PANYARGS
wsnmp32_ordinal330 TEXTEQU <__imp_wsnmp32_ordinal330>
extern __imp_wsnmp32_ordinal331:PANYARGS
wsnmp32_ordinal331 TEXTEQU <__imp_wsnmp32_ordinal331>
extern __imp_wsnmp32_ordinal332:PANYARGS
wsnmp32_ordinal332 TEXTEQU <__imp_wsnmp32_ordinal332>
extern __imp_wsnmp32_ordinal333:PANYARGS
wsnmp32_ordinal333 TEXTEQU <__imp_wsnmp32_ordinal333>
extern __imp_wsnmp32_ordinal334:PANYARGS
wsnmp32_ordinal334 TEXTEQU <__imp_wsnmp32_ordinal334>
extern __imp_wsnmp32_ordinal335:PANYARGS
wsnmp32_ordinal335 TEXTEQU <__imp_wsnmp32_ordinal335>
extern __imp_wsnmp32_ordinal336:PANYARGS
wsnmp32_ordinal336 TEXTEQU <__imp_wsnmp32_ordinal336>
extern __imp_wsnmp32_ordinal337:PANYARGS
wsnmp32_ordinal337 TEXTEQU <__imp_wsnmp32_ordinal337>
extern __imp_wsnmp32_ordinal338:PANYARGS
wsnmp32_ordinal338 TEXTEQU <__imp_wsnmp32_ordinal338>
extern __imp_wsnmp32_ordinal339:PANYARGS
wsnmp32_ordinal339 TEXTEQU <__imp_wsnmp32_ordinal339>
extern __imp_wsnmp32_ordinal340:PANYARGS
wsnmp32_ordinal340 TEXTEQU <__imp_wsnmp32_ordinal340>
extern __imp_wsnmp32_ordinal341:PANYARGS
wsnmp32_ordinal341 TEXTEQU <__imp_wsnmp32_ordinal341>
extern __imp_wsnmp32_ordinal342:PANYARGS
wsnmp32_ordinal342 TEXTEQU <__imp_wsnmp32_ordinal342>
extern __imp_wsnmp32_ordinal343:PANYARGS
wsnmp32_ordinal343 TEXTEQU <__imp_wsnmp32_ordinal343>
extern __imp_wsnmp32_ordinal344:PANYARGS
wsnmp32_ordinal344 TEXTEQU <__imp_wsnmp32_ordinal344>
extern __imp_wsnmp32_ordinal345:PANYARGS
wsnmp32_ordinal345 TEXTEQU <__imp_wsnmp32_ordinal345>
extern __imp_wsnmp32_ordinal346:PANYARGS
wsnmp32_ordinal346 TEXTEQU <__imp_wsnmp32_ordinal346>
extern __imp_wsnmp32_ordinal347:PANYARGS
wsnmp32_ordinal347 TEXTEQU <__imp_wsnmp32_ordinal347>
extern __imp_wsnmp32_ordinal348:PANYARGS
wsnmp32_ordinal348 TEXTEQU <__imp_wsnmp32_ordinal348>
extern __imp_wsnmp32_ordinal349:PANYARGS
wsnmp32_ordinal349 TEXTEQU <__imp_wsnmp32_ordinal349>
extern __imp_wsnmp32_ordinal350:PANYARGS
wsnmp32_ordinal350 TEXTEQU <__imp_wsnmp32_ordinal350>
extern __imp_wsnmp32_ordinal351:PANYARGS
wsnmp32_ordinal351 TEXTEQU <__imp_wsnmp32_ordinal351>
extern __imp_wsnmp32_ordinal352:PANYARGS
wsnmp32_ordinal352 TEXTEQU <__imp_wsnmp32_ordinal352>
extern __imp_wsnmp32_ordinal353:PANYARGS
wsnmp32_ordinal353 TEXTEQU <__imp_wsnmp32_ordinal353>
extern __imp_wsnmp32_ordinal354:PANYARGS
wsnmp32_ordinal354 TEXTEQU <__imp_wsnmp32_ordinal354>
extern __imp_wsnmp32_ordinal355:PANYARGS
wsnmp32_ordinal355 TEXTEQU <__imp_wsnmp32_ordinal355>
extern __imp_wsnmp32_ordinal356:PANYARGS
wsnmp32_ordinal356 TEXTEQU <__imp_wsnmp32_ordinal356>
extern __imp_wsnmp32_ordinal357:PANYARGS
wsnmp32_ordinal357 TEXTEQU <__imp_wsnmp32_ordinal357>
extern __imp_wsnmp32_ordinal358:PANYARGS
wsnmp32_ordinal358 TEXTEQU <__imp_wsnmp32_ordinal358>
extern __imp_wsnmp32_ordinal359:PANYARGS
wsnmp32_ordinal359 TEXTEQU <__imp_wsnmp32_ordinal359>
extern __imp_wsnmp32_ordinal360:PANYARGS
wsnmp32_ordinal360 TEXTEQU <__imp_wsnmp32_ordinal360>
extern __imp_wsnmp32_ordinal361:PANYARGS
wsnmp32_ordinal361 TEXTEQU <__imp_wsnmp32_ordinal361>
extern __imp_wsnmp32_ordinal362:PANYARGS
wsnmp32_ordinal362 TEXTEQU <__imp_wsnmp32_ordinal362>
extern __imp_wsnmp32_ordinal363:PANYARGS
wsnmp32_ordinal363 TEXTEQU <__imp_wsnmp32_ordinal363>
extern __imp_wsnmp32_ordinal364:PANYARGS
wsnmp32_ordinal364 TEXTEQU <__imp_wsnmp32_ordinal364>
extern __imp_wsnmp32_ordinal365:PANYARGS
wsnmp32_ordinal365 TEXTEQU <__imp_wsnmp32_ordinal365>
extern __imp_wsnmp32_ordinal366:PANYARGS
wsnmp32_ordinal366 TEXTEQU <__imp_wsnmp32_ordinal366>
extern __imp_wsnmp32_ordinal367:PANYARGS
wsnmp32_ordinal367 TEXTEQU <__imp_wsnmp32_ordinal367>
extern __imp_wsnmp32_ordinal368:PANYARGS
wsnmp32_ordinal368 TEXTEQU <__imp_wsnmp32_ordinal368>
extern __imp_wsnmp32_ordinal369:PANYARGS
wsnmp32_ordinal369 TEXTEQU <__imp_wsnmp32_ordinal369>
extern __imp_wsnmp32_ordinal370:PANYARGS
wsnmp32_ordinal370 TEXTEQU <__imp_wsnmp32_ordinal370>
extern __imp_wsnmp32_ordinal371:PANYARGS
wsnmp32_ordinal371 TEXTEQU <__imp_wsnmp32_ordinal371>
extern __imp_wsnmp32_ordinal372:PANYARGS
wsnmp32_ordinal372 TEXTEQU <__imp_wsnmp32_ordinal372>
extern __imp_wsnmp32_ordinal373:PANYARGS
wsnmp32_ordinal373 TEXTEQU <__imp_wsnmp32_ordinal373>
extern __imp_wsnmp32_ordinal374:PANYARGS
wsnmp32_ordinal374 TEXTEQU <__imp_wsnmp32_ordinal374>
extern __imp_wsnmp32_ordinal375:PANYARGS
wsnmp32_ordinal375 TEXTEQU <__imp_wsnmp32_ordinal375>
extern __imp_wsnmp32_ordinal376:PANYARGS
wsnmp32_ordinal376 TEXTEQU <__imp_wsnmp32_ordinal376>
extern __imp_wsnmp32_ordinal377:PANYARGS
wsnmp32_ordinal377 TEXTEQU <__imp_wsnmp32_ordinal377>
extern __imp_wsnmp32_ordinal378:PANYARGS
wsnmp32_ordinal378 TEXTEQU <__imp_wsnmp32_ordinal378>
extern __imp_wsnmp32_ordinal379:PANYARGS
wsnmp32_ordinal379 TEXTEQU <__imp_wsnmp32_ordinal379>
extern __imp_wsnmp32_ordinal380:PANYARGS
wsnmp32_ordinal380 TEXTEQU <__imp_wsnmp32_ordinal380>
extern __imp_wsnmp32_ordinal381:PANYARGS
wsnmp32_ordinal381 TEXTEQU <__imp_wsnmp32_ordinal381>
extern __imp_wsnmp32_ordinal382:PANYARGS
wsnmp32_ordinal382 TEXTEQU <__imp_wsnmp32_ordinal382>
extern __imp_wsnmp32_ordinal383:PANYARGS
wsnmp32_ordinal383 TEXTEQU <__imp_wsnmp32_ordinal383>
extern __imp_wsnmp32_ordinal384:PANYARGS
wsnmp32_ordinal384 TEXTEQU <__imp_wsnmp32_ordinal384>
extern __imp_wsnmp32_ordinal385:PANYARGS
wsnmp32_ordinal385 TEXTEQU <__imp_wsnmp32_ordinal385>
extern __imp_wsnmp32_ordinal386:PANYARGS
wsnmp32_ordinal386 TEXTEQU <__imp_wsnmp32_ordinal386>
extern __imp_wsnmp32_ordinal387:PANYARGS
wsnmp32_ordinal387 TEXTEQU <__imp_wsnmp32_ordinal387>
extern __imp_wsnmp32_ordinal388:PANYARGS
wsnmp32_ordinal388 TEXTEQU <__imp_wsnmp32_ordinal388>
extern __imp_wsnmp32_ordinal389:PANYARGS
wsnmp32_ordinal389 TEXTEQU <__imp_wsnmp32_ordinal389>
extern __imp_wsnmp32_ordinal390:PANYARGS
wsnmp32_ordinal390 TEXTEQU <__imp_wsnmp32_ordinal390>
extern __imp_wsnmp32_ordinal391:PANYARGS
wsnmp32_ordinal391 TEXTEQU <__imp_wsnmp32_ordinal391>
extern __imp_wsnmp32_ordinal392:PANYARGS
wsnmp32_ordinal392 TEXTEQU <__imp_wsnmp32_ordinal392>
extern __imp_wsnmp32_ordinal393:PANYARGS
wsnmp32_ordinal393 TEXTEQU <__imp_wsnmp32_ordinal393>
extern __imp_wsnmp32_ordinal394:PANYARGS
wsnmp32_ordinal394 TEXTEQU <__imp_wsnmp32_ordinal394>
extern __imp_wsnmp32_ordinal395:PANYARGS
wsnmp32_ordinal395 TEXTEQU <__imp_wsnmp32_ordinal395>
extern __imp_wsnmp32_ordinal396:PANYARGS
wsnmp32_ordinal396 TEXTEQU <__imp_wsnmp32_ordinal396>
extern __imp_wsnmp32_ordinal397:PANYARGS
wsnmp32_ordinal397 TEXTEQU <__imp_wsnmp32_ordinal397>
extern __imp_wsnmp32_ordinal398:PANYARGS
wsnmp32_ordinal398 TEXTEQU <__imp_wsnmp32_ordinal398>
extern __imp_wsnmp32_ordinal399:PANYARGS
wsnmp32_ordinal399 TEXTEQU <__imp_wsnmp32_ordinal399>
extern __imp_SnmpStrToContext:PANYARGS
SnmpStrToContext TEXTEQU <__imp_SnmpStrToContext>
extern __imp_SnmpContextToStr:PANYARGS
SnmpContextToStr TEXTEQU <__imp_SnmpContextToStr>
extern __imp_SnmpFreeContext:PANYARGS
SnmpFreeContext TEXTEQU <__imp_SnmpFreeContext>
extern __imp_wsnmp32_ordinal403:PANYARGS
wsnmp32_ordinal403 TEXTEQU <__imp_wsnmp32_ordinal403>
extern __imp_wsnmp32_ordinal404:PANYARGS
wsnmp32_ordinal404 TEXTEQU <__imp_wsnmp32_ordinal404>
extern __imp_wsnmp32_ordinal405:PANYARGS
wsnmp32_ordinal405 TEXTEQU <__imp_wsnmp32_ordinal405>
extern __imp_wsnmp32_ordinal406:PANYARGS
wsnmp32_ordinal406 TEXTEQU <__imp_wsnmp32_ordinal406>
extern __imp_wsnmp32_ordinal407:PANYARGS
wsnmp32_ordinal407 TEXTEQU <__imp_wsnmp32_ordinal407>
extern __imp_wsnmp32_ordinal408:PANYARGS
wsnmp32_ordinal408 TEXTEQU <__imp_wsnmp32_ordinal408>
extern __imp_wsnmp32_ordinal409:PANYARGS
wsnmp32_ordinal409 TEXTEQU <__imp_wsnmp32_ordinal409>
extern __imp_wsnmp32_ordinal410:PANYARGS
wsnmp32_ordinal410 TEXTEQU <__imp_wsnmp32_ordinal410>
extern __imp_wsnmp32_ordinal411:PANYARGS
wsnmp32_ordinal411 TEXTEQU <__imp_wsnmp32_ordinal411>
extern __imp_wsnmp32_ordinal412:PANYARGS
wsnmp32_ordinal412 TEXTEQU <__imp_wsnmp32_ordinal412>
extern __imp_wsnmp32_ordinal413:PANYARGS
wsnmp32_ordinal413 TEXTEQU <__imp_wsnmp32_ordinal413>
extern __imp_wsnmp32_ordinal414:PANYARGS
wsnmp32_ordinal414 TEXTEQU <__imp_wsnmp32_ordinal414>
extern __imp_wsnmp32_ordinal415:PANYARGS
wsnmp32_ordinal415 TEXTEQU <__imp_wsnmp32_ordinal415>
extern __imp_wsnmp32_ordinal416:PANYARGS
wsnmp32_ordinal416 TEXTEQU <__imp_wsnmp32_ordinal416>
extern __imp_wsnmp32_ordinal417:PANYARGS
wsnmp32_ordinal417 TEXTEQU <__imp_wsnmp32_ordinal417>
extern __imp_wsnmp32_ordinal418:PANYARGS
wsnmp32_ordinal418 TEXTEQU <__imp_wsnmp32_ordinal418>
extern __imp_wsnmp32_ordinal419:PANYARGS
wsnmp32_ordinal419 TEXTEQU <__imp_wsnmp32_ordinal419>
extern __imp_wsnmp32_ordinal420:PANYARGS
wsnmp32_ordinal420 TEXTEQU <__imp_wsnmp32_ordinal420>
extern __imp_wsnmp32_ordinal421:PANYARGS
wsnmp32_ordinal421 TEXTEQU <__imp_wsnmp32_ordinal421>
extern __imp_wsnmp32_ordinal422:PANYARGS
wsnmp32_ordinal422 TEXTEQU <__imp_wsnmp32_ordinal422>
extern __imp_wsnmp32_ordinal423:PANYARGS
wsnmp32_ordinal423 TEXTEQU <__imp_wsnmp32_ordinal423>
extern __imp_wsnmp32_ordinal424:PANYARGS
wsnmp32_ordinal424 TEXTEQU <__imp_wsnmp32_ordinal424>
extern __imp_wsnmp32_ordinal425:PANYARGS
wsnmp32_ordinal425 TEXTEQU <__imp_wsnmp32_ordinal425>
extern __imp_wsnmp32_ordinal426:PANYARGS
wsnmp32_ordinal426 TEXTEQU <__imp_wsnmp32_ordinal426>
extern __imp_wsnmp32_ordinal427:PANYARGS
wsnmp32_ordinal427 TEXTEQU <__imp_wsnmp32_ordinal427>
extern __imp_wsnmp32_ordinal428:PANYARGS
wsnmp32_ordinal428 TEXTEQU <__imp_wsnmp32_ordinal428>
extern __imp_wsnmp32_ordinal429:PANYARGS
wsnmp32_ordinal429 TEXTEQU <__imp_wsnmp32_ordinal429>
extern __imp_wsnmp32_ordinal430:PANYARGS
wsnmp32_ordinal430 TEXTEQU <__imp_wsnmp32_ordinal430>
extern __imp_wsnmp32_ordinal431:PANYARGS
wsnmp32_ordinal431 TEXTEQU <__imp_wsnmp32_ordinal431>
extern __imp_wsnmp32_ordinal432:PANYARGS
wsnmp32_ordinal432 TEXTEQU <__imp_wsnmp32_ordinal432>
extern __imp_wsnmp32_ordinal433:PANYARGS
wsnmp32_ordinal433 TEXTEQU <__imp_wsnmp32_ordinal433>
extern __imp_wsnmp32_ordinal434:PANYARGS
wsnmp32_ordinal434 TEXTEQU <__imp_wsnmp32_ordinal434>
extern __imp_wsnmp32_ordinal435:PANYARGS
wsnmp32_ordinal435 TEXTEQU <__imp_wsnmp32_ordinal435>
extern __imp_wsnmp32_ordinal436:PANYARGS
wsnmp32_ordinal436 TEXTEQU <__imp_wsnmp32_ordinal436>
extern __imp_wsnmp32_ordinal437:PANYARGS
wsnmp32_ordinal437 TEXTEQU <__imp_wsnmp32_ordinal437>
extern __imp_wsnmp32_ordinal438:PANYARGS
wsnmp32_ordinal438 TEXTEQU <__imp_wsnmp32_ordinal438>
extern __imp_wsnmp32_ordinal439:PANYARGS
wsnmp32_ordinal439 TEXTEQU <__imp_wsnmp32_ordinal439>
extern __imp_wsnmp32_ordinal440:PANYARGS
wsnmp32_ordinal440 TEXTEQU <__imp_wsnmp32_ordinal440>
extern __imp_wsnmp32_ordinal441:PANYARGS
wsnmp32_ordinal441 TEXTEQU <__imp_wsnmp32_ordinal441>
extern __imp_wsnmp32_ordinal442:PANYARGS
wsnmp32_ordinal442 TEXTEQU <__imp_wsnmp32_ordinal442>
extern __imp_wsnmp32_ordinal443:PANYARGS
wsnmp32_ordinal443 TEXTEQU <__imp_wsnmp32_ordinal443>
extern __imp_wsnmp32_ordinal444:PANYARGS
wsnmp32_ordinal444 TEXTEQU <__imp_wsnmp32_ordinal444>
extern __imp_wsnmp32_ordinal445:PANYARGS
wsnmp32_ordinal445 TEXTEQU <__imp_wsnmp32_ordinal445>
extern __imp_wsnmp32_ordinal446:PANYARGS
wsnmp32_ordinal446 TEXTEQU <__imp_wsnmp32_ordinal446>
extern __imp_wsnmp32_ordinal447:PANYARGS
wsnmp32_ordinal447 TEXTEQU <__imp_wsnmp32_ordinal447>
extern __imp_wsnmp32_ordinal448:PANYARGS
wsnmp32_ordinal448 TEXTEQU <__imp_wsnmp32_ordinal448>
extern __imp_wsnmp32_ordinal449:PANYARGS
wsnmp32_ordinal449 TEXTEQU <__imp_wsnmp32_ordinal449>
extern __imp_wsnmp32_ordinal450:PANYARGS
wsnmp32_ordinal450 TEXTEQU <__imp_wsnmp32_ordinal450>
extern __imp_wsnmp32_ordinal451:PANYARGS
wsnmp32_ordinal451 TEXTEQU <__imp_wsnmp32_ordinal451>
extern __imp_wsnmp32_ordinal452:PANYARGS
wsnmp32_ordinal452 TEXTEQU <__imp_wsnmp32_ordinal452>
extern __imp_wsnmp32_ordinal453:PANYARGS
wsnmp32_ordinal453 TEXTEQU <__imp_wsnmp32_ordinal453>
extern __imp_wsnmp32_ordinal454:PANYARGS
wsnmp32_ordinal454 TEXTEQU <__imp_wsnmp32_ordinal454>
extern __imp_wsnmp32_ordinal455:PANYARGS
wsnmp32_ordinal455 TEXTEQU <__imp_wsnmp32_ordinal455>
extern __imp_wsnmp32_ordinal456:PANYARGS
wsnmp32_ordinal456 TEXTEQU <__imp_wsnmp32_ordinal456>
extern __imp_wsnmp32_ordinal457:PANYARGS
wsnmp32_ordinal457 TEXTEQU <__imp_wsnmp32_ordinal457>
extern __imp_wsnmp32_ordinal458:PANYARGS
wsnmp32_ordinal458 TEXTEQU <__imp_wsnmp32_ordinal458>
extern __imp_wsnmp32_ordinal459:PANYARGS
wsnmp32_ordinal459 TEXTEQU <__imp_wsnmp32_ordinal459>
extern __imp_wsnmp32_ordinal460:PANYARGS
wsnmp32_ordinal460 TEXTEQU <__imp_wsnmp32_ordinal460>
extern __imp_wsnmp32_ordinal461:PANYARGS
wsnmp32_ordinal461 TEXTEQU <__imp_wsnmp32_ordinal461>
extern __imp_wsnmp32_ordinal462:PANYARGS
wsnmp32_ordinal462 TEXTEQU <__imp_wsnmp32_ordinal462>
extern __imp_wsnmp32_ordinal463:PANYARGS
wsnmp32_ordinal463 TEXTEQU <__imp_wsnmp32_ordinal463>
extern __imp_wsnmp32_ordinal464:PANYARGS
wsnmp32_ordinal464 TEXTEQU <__imp_wsnmp32_ordinal464>
extern __imp_wsnmp32_ordinal465:PANYARGS
wsnmp32_ordinal465 TEXTEQU <__imp_wsnmp32_ordinal465>
extern __imp_wsnmp32_ordinal466:PANYARGS
wsnmp32_ordinal466 TEXTEQU <__imp_wsnmp32_ordinal466>
extern __imp_wsnmp32_ordinal467:PANYARGS
wsnmp32_ordinal467 TEXTEQU <__imp_wsnmp32_ordinal467>
extern __imp_wsnmp32_ordinal468:PANYARGS
wsnmp32_ordinal468 TEXTEQU <__imp_wsnmp32_ordinal468>
extern __imp_wsnmp32_ordinal469:PANYARGS
wsnmp32_ordinal469 TEXTEQU <__imp_wsnmp32_ordinal469>
extern __imp_wsnmp32_ordinal470:PANYARGS
wsnmp32_ordinal470 TEXTEQU <__imp_wsnmp32_ordinal470>
extern __imp_wsnmp32_ordinal471:PANYARGS
wsnmp32_ordinal471 TEXTEQU <__imp_wsnmp32_ordinal471>
extern __imp_wsnmp32_ordinal472:PANYARGS
wsnmp32_ordinal472 TEXTEQU <__imp_wsnmp32_ordinal472>
extern __imp_wsnmp32_ordinal473:PANYARGS
wsnmp32_ordinal473 TEXTEQU <__imp_wsnmp32_ordinal473>
extern __imp_wsnmp32_ordinal474:PANYARGS
wsnmp32_ordinal474 TEXTEQU <__imp_wsnmp32_ordinal474>
extern __imp_wsnmp32_ordinal475:PANYARGS
wsnmp32_ordinal475 TEXTEQU <__imp_wsnmp32_ordinal475>
extern __imp_wsnmp32_ordinal476:PANYARGS
wsnmp32_ordinal476 TEXTEQU <__imp_wsnmp32_ordinal476>
extern __imp_wsnmp32_ordinal477:PANYARGS
wsnmp32_ordinal477 TEXTEQU <__imp_wsnmp32_ordinal477>
extern __imp_wsnmp32_ordinal478:PANYARGS
wsnmp32_ordinal478 TEXTEQU <__imp_wsnmp32_ordinal478>
extern __imp_wsnmp32_ordinal479:PANYARGS
wsnmp32_ordinal479 TEXTEQU <__imp_wsnmp32_ordinal479>
extern __imp_wsnmp32_ordinal480:PANYARGS
wsnmp32_ordinal480 TEXTEQU <__imp_wsnmp32_ordinal480>
extern __imp_wsnmp32_ordinal481:PANYARGS
wsnmp32_ordinal481 TEXTEQU <__imp_wsnmp32_ordinal481>
extern __imp_wsnmp32_ordinal482:PANYARGS
wsnmp32_ordinal482 TEXTEQU <__imp_wsnmp32_ordinal482>
extern __imp_wsnmp32_ordinal483:PANYARGS
wsnmp32_ordinal483 TEXTEQU <__imp_wsnmp32_ordinal483>
extern __imp_wsnmp32_ordinal484:PANYARGS
wsnmp32_ordinal484 TEXTEQU <__imp_wsnmp32_ordinal484>
extern __imp_wsnmp32_ordinal485:PANYARGS
wsnmp32_ordinal485 TEXTEQU <__imp_wsnmp32_ordinal485>
extern __imp_wsnmp32_ordinal486:PANYARGS
wsnmp32_ordinal486 TEXTEQU <__imp_wsnmp32_ordinal486>
extern __imp_wsnmp32_ordinal487:PANYARGS
wsnmp32_ordinal487 TEXTEQU <__imp_wsnmp32_ordinal487>
extern __imp_wsnmp32_ordinal488:PANYARGS
wsnmp32_ordinal488 TEXTEQU <__imp_wsnmp32_ordinal488>
extern __imp_wsnmp32_ordinal489:PANYARGS
wsnmp32_ordinal489 TEXTEQU <__imp_wsnmp32_ordinal489>
extern __imp_wsnmp32_ordinal490:PANYARGS
wsnmp32_ordinal490 TEXTEQU <__imp_wsnmp32_ordinal490>
extern __imp_wsnmp32_ordinal491:PANYARGS
wsnmp32_ordinal491 TEXTEQU <__imp_wsnmp32_ordinal491>
extern __imp_wsnmp32_ordinal492:PANYARGS
wsnmp32_ordinal492 TEXTEQU <__imp_wsnmp32_ordinal492>
extern __imp_wsnmp32_ordinal493:PANYARGS
wsnmp32_ordinal493 TEXTEQU <__imp_wsnmp32_ordinal493>
extern __imp_wsnmp32_ordinal494:PANYARGS
wsnmp32_ordinal494 TEXTEQU <__imp_wsnmp32_ordinal494>
extern __imp_wsnmp32_ordinal495:PANYARGS
wsnmp32_ordinal495 TEXTEQU <__imp_wsnmp32_ordinal495>
extern __imp_wsnmp32_ordinal496:PANYARGS
wsnmp32_ordinal496 TEXTEQU <__imp_wsnmp32_ordinal496>
extern __imp_wsnmp32_ordinal497:PANYARGS
wsnmp32_ordinal497 TEXTEQU <__imp_wsnmp32_ordinal497>
extern __imp_wsnmp32_ordinal498:PANYARGS
wsnmp32_ordinal498 TEXTEQU <__imp_wsnmp32_ordinal498>
extern __imp_wsnmp32_ordinal499:PANYARGS
wsnmp32_ordinal499 TEXTEQU <__imp_wsnmp32_ordinal499>
extern __imp_SnmpCreatePdu:PANYARGS
SnmpCreatePdu TEXTEQU <__imp_SnmpCreatePdu>
extern __imp_SnmpGetPduData:PANYARGS
SnmpGetPduData TEXTEQU <__imp_SnmpGetPduData>
extern __imp_SnmpSetPduData:PANYARGS
SnmpSetPduData TEXTEQU <__imp_SnmpSetPduData>
extern __imp_SnmpDuplicatePdu:PANYARGS
SnmpDuplicatePdu TEXTEQU <__imp_SnmpDuplicatePdu>
extern __imp_SnmpFreePdu:PANYARGS
SnmpFreePdu TEXTEQU <__imp_SnmpFreePdu>
extern __imp_wsnmp32_ordinal505:PANYARGS
wsnmp32_ordinal505 TEXTEQU <__imp_wsnmp32_ordinal505>
extern __imp_wsnmp32_ordinal506:PANYARGS
wsnmp32_ordinal506 TEXTEQU <__imp_wsnmp32_ordinal506>
extern __imp_wsnmp32_ordinal507:PANYARGS
wsnmp32_ordinal507 TEXTEQU <__imp_wsnmp32_ordinal507>
extern __imp_wsnmp32_ordinal508:PANYARGS
wsnmp32_ordinal508 TEXTEQU <__imp_wsnmp32_ordinal508>
extern __imp_wsnmp32_ordinal509:PANYARGS
wsnmp32_ordinal509 TEXTEQU <__imp_wsnmp32_ordinal509>
extern __imp_wsnmp32_ordinal510:PANYARGS
wsnmp32_ordinal510 TEXTEQU <__imp_wsnmp32_ordinal510>
extern __imp_wsnmp32_ordinal511:PANYARGS
wsnmp32_ordinal511 TEXTEQU <__imp_wsnmp32_ordinal511>
extern __imp_wsnmp32_ordinal512:PANYARGS
wsnmp32_ordinal512 TEXTEQU <__imp_wsnmp32_ordinal512>
extern __imp_wsnmp32_ordinal513:PANYARGS
wsnmp32_ordinal513 TEXTEQU <__imp_wsnmp32_ordinal513>
extern __imp_wsnmp32_ordinal514:PANYARGS
wsnmp32_ordinal514 TEXTEQU <__imp_wsnmp32_ordinal514>
extern __imp_wsnmp32_ordinal515:PANYARGS
wsnmp32_ordinal515 TEXTEQU <__imp_wsnmp32_ordinal515>
extern __imp_wsnmp32_ordinal516:PANYARGS
wsnmp32_ordinal516 TEXTEQU <__imp_wsnmp32_ordinal516>
extern __imp_wsnmp32_ordinal517:PANYARGS
wsnmp32_ordinal517 TEXTEQU <__imp_wsnmp32_ordinal517>
extern __imp_wsnmp32_ordinal518:PANYARGS
wsnmp32_ordinal518 TEXTEQU <__imp_wsnmp32_ordinal518>
extern __imp_wsnmp32_ordinal519:PANYARGS
wsnmp32_ordinal519 TEXTEQU <__imp_wsnmp32_ordinal519>
extern __imp_wsnmp32_ordinal520:PANYARGS
wsnmp32_ordinal520 TEXTEQU <__imp_wsnmp32_ordinal520>
extern __imp_wsnmp32_ordinal521:PANYARGS
wsnmp32_ordinal521 TEXTEQU <__imp_wsnmp32_ordinal521>
extern __imp_wsnmp32_ordinal522:PANYARGS
wsnmp32_ordinal522 TEXTEQU <__imp_wsnmp32_ordinal522>
extern __imp_wsnmp32_ordinal523:PANYARGS
wsnmp32_ordinal523 TEXTEQU <__imp_wsnmp32_ordinal523>
extern __imp_wsnmp32_ordinal524:PANYARGS
wsnmp32_ordinal524 TEXTEQU <__imp_wsnmp32_ordinal524>
extern __imp_wsnmp32_ordinal525:PANYARGS
wsnmp32_ordinal525 TEXTEQU <__imp_wsnmp32_ordinal525>
extern __imp_wsnmp32_ordinal526:PANYARGS
wsnmp32_ordinal526 TEXTEQU <__imp_wsnmp32_ordinal526>
extern __imp_wsnmp32_ordinal527:PANYARGS
wsnmp32_ordinal527 TEXTEQU <__imp_wsnmp32_ordinal527>
extern __imp_wsnmp32_ordinal528:PANYARGS
wsnmp32_ordinal528 TEXTEQU <__imp_wsnmp32_ordinal528>
extern __imp_wsnmp32_ordinal529:PANYARGS
wsnmp32_ordinal529 TEXTEQU <__imp_wsnmp32_ordinal529>
extern __imp_wsnmp32_ordinal530:PANYARGS
wsnmp32_ordinal530 TEXTEQU <__imp_wsnmp32_ordinal530>
extern __imp_wsnmp32_ordinal531:PANYARGS
wsnmp32_ordinal531 TEXTEQU <__imp_wsnmp32_ordinal531>
extern __imp_wsnmp32_ordinal532:PANYARGS
wsnmp32_ordinal532 TEXTEQU <__imp_wsnmp32_ordinal532>
extern __imp_wsnmp32_ordinal533:PANYARGS
wsnmp32_ordinal533 TEXTEQU <__imp_wsnmp32_ordinal533>
extern __imp_wsnmp32_ordinal534:PANYARGS
wsnmp32_ordinal534 TEXTEQU <__imp_wsnmp32_ordinal534>
extern __imp_wsnmp32_ordinal535:PANYARGS
wsnmp32_ordinal535 TEXTEQU <__imp_wsnmp32_ordinal535>
extern __imp_wsnmp32_ordinal536:PANYARGS
wsnmp32_ordinal536 TEXTEQU <__imp_wsnmp32_ordinal536>
extern __imp_wsnmp32_ordinal537:PANYARGS
wsnmp32_ordinal537 TEXTEQU <__imp_wsnmp32_ordinal537>
extern __imp_wsnmp32_ordinal538:PANYARGS
wsnmp32_ordinal538 TEXTEQU <__imp_wsnmp32_ordinal538>
extern __imp_wsnmp32_ordinal539:PANYARGS
wsnmp32_ordinal539 TEXTEQU <__imp_wsnmp32_ordinal539>
extern __imp_wsnmp32_ordinal540:PANYARGS
wsnmp32_ordinal540 TEXTEQU <__imp_wsnmp32_ordinal540>
extern __imp_wsnmp32_ordinal541:PANYARGS
wsnmp32_ordinal541 TEXTEQU <__imp_wsnmp32_ordinal541>
extern __imp_wsnmp32_ordinal542:PANYARGS
wsnmp32_ordinal542 TEXTEQU <__imp_wsnmp32_ordinal542>
extern __imp_wsnmp32_ordinal543:PANYARGS
wsnmp32_ordinal543 TEXTEQU <__imp_wsnmp32_ordinal543>
extern __imp_wsnmp32_ordinal544:PANYARGS
wsnmp32_ordinal544 TEXTEQU <__imp_wsnmp32_ordinal544>
extern __imp_wsnmp32_ordinal545:PANYARGS
wsnmp32_ordinal545 TEXTEQU <__imp_wsnmp32_ordinal545>
extern __imp_wsnmp32_ordinal546:PANYARGS
wsnmp32_ordinal546 TEXTEQU <__imp_wsnmp32_ordinal546>
extern __imp_wsnmp32_ordinal547:PANYARGS
wsnmp32_ordinal547 TEXTEQU <__imp_wsnmp32_ordinal547>
extern __imp_wsnmp32_ordinal548:PANYARGS
wsnmp32_ordinal548 TEXTEQU <__imp_wsnmp32_ordinal548>
extern __imp_wsnmp32_ordinal549:PANYARGS
wsnmp32_ordinal549 TEXTEQU <__imp_wsnmp32_ordinal549>
extern __imp_wsnmp32_ordinal550:PANYARGS
wsnmp32_ordinal550 TEXTEQU <__imp_wsnmp32_ordinal550>
extern __imp_wsnmp32_ordinal551:PANYARGS
wsnmp32_ordinal551 TEXTEQU <__imp_wsnmp32_ordinal551>
extern __imp_wsnmp32_ordinal552:PANYARGS
wsnmp32_ordinal552 TEXTEQU <__imp_wsnmp32_ordinal552>
extern __imp_wsnmp32_ordinal553:PANYARGS
wsnmp32_ordinal553 TEXTEQU <__imp_wsnmp32_ordinal553>
extern __imp_wsnmp32_ordinal554:PANYARGS
wsnmp32_ordinal554 TEXTEQU <__imp_wsnmp32_ordinal554>
extern __imp_wsnmp32_ordinal555:PANYARGS
wsnmp32_ordinal555 TEXTEQU <__imp_wsnmp32_ordinal555>
extern __imp_wsnmp32_ordinal556:PANYARGS
wsnmp32_ordinal556 TEXTEQU <__imp_wsnmp32_ordinal556>
extern __imp_wsnmp32_ordinal557:PANYARGS
wsnmp32_ordinal557 TEXTEQU <__imp_wsnmp32_ordinal557>
extern __imp_wsnmp32_ordinal558:PANYARGS
wsnmp32_ordinal558 TEXTEQU <__imp_wsnmp32_ordinal558>
extern __imp_wsnmp32_ordinal559:PANYARGS
wsnmp32_ordinal559 TEXTEQU <__imp_wsnmp32_ordinal559>
extern __imp_wsnmp32_ordinal560:PANYARGS
wsnmp32_ordinal560 TEXTEQU <__imp_wsnmp32_ordinal560>
extern __imp_wsnmp32_ordinal561:PANYARGS
wsnmp32_ordinal561 TEXTEQU <__imp_wsnmp32_ordinal561>
extern __imp_wsnmp32_ordinal562:PANYARGS
wsnmp32_ordinal562 TEXTEQU <__imp_wsnmp32_ordinal562>
extern __imp_wsnmp32_ordinal563:PANYARGS
wsnmp32_ordinal563 TEXTEQU <__imp_wsnmp32_ordinal563>
extern __imp_wsnmp32_ordinal564:PANYARGS
wsnmp32_ordinal564 TEXTEQU <__imp_wsnmp32_ordinal564>
extern __imp_wsnmp32_ordinal565:PANYARGS
wsnmp32_ordinal565 TEXTEQU <__imp_wsnmp32_ordinal565>
extern __imp_wsnmp32_ordinal566:PANYARGS
wsnmp32_ordinal566 TEXTEQU <__imp_wsnmp32_ordinal566>
extern __imp_wsnmp32_ordinal567:PANYARGS
wsnmp32_ordinal567 TEXTEQU <__imp_wsnmp32_ordinal567>
extern __imp_wsnmp32_ordinal568:PANYARGS
wsnmp32_ordinal568 TEXTEQU <__imp_wsnmp32_ordinal568>
extern __imp_wsnmp32_ordinal569:PANYARGS
wsnmp32_ordinal569 TEXTEQU <__imp_wsnmp32_ordinal569>
extern __imp_wsnmp32_ordinal570:PANYARGS
wsnmp32_ordinal570 TEXTEQU <__imp_wsnmp32_ordinal570>
extern __imp_wsnmp32_ordinal571:PANYARGS
wsnmp32_ordinal571 TEXTEQU <__imp_wsnmp32_ordinal571>
extern __imp_wsnmp32_ordinal572:PANYARGS
wsnmp32_ordinal572 TEXTEQU <__imp_wsnmp32_ordinal572>
extern __imp_wsnmp32_ordinal573:PANYARGS
wsnmp32_ordinal573 TEXTEQU <__imp_wsnmp32_ordinal573>
extern __imp_wsnmp32_ordinal574:PANYARGS
wsnmp32_ordinal574 TEXTEQU <__imp_wsnmp32_ordinal574>
extern __imp_wsnmp32_ordinal575:PANYARGS
wsnmp32_ordinal575 TEXTEQU <__imp_wsnmp32_ordinal575>
extern __imp_wsnmp32_ordinal576:PANYARGS
wsnmp32_ordinal576 TEXTEQU <__imp_wsnmp32_ordinal576>
extern __imp_wsnmp32_ordinal577:PANYARGS
wsnmp32_ordinal577 TEXTEQU <__imp_wsnmp32_ordinal577>
extern __imp_wsnmp32_ordinal578:PANYARGS
wsnmp32_ordinal578 TEXTEQU <__imp_wsnmp32_ordinal578>
extern __imp_wsnmp32_ordinal579:PANYARGS
wsnmp32_ordinal579 TEXTEQU <__imp_wsnmp32_ordinal579>
extern __imp_wsnmp32_ordinal580:PANYARGS
wsnmp32_ordinal580 TEXTEQU <__imp_wsnmp32_ordinal580>
extern __imp_wsnmp32_ordinal581:PANYARGS
wsnmp32_ordinal581 TEXTEQU <__imp_wsnmp32_ordinal581>
extern __imp_wsnmp32_ordinal582:PANYARGS
wsnmp32_ordinal582 TEXTEQU <__imp_wsnmp32_ordinal582>
extern __imp_wsnmp32_ordinal583:PANYARGS
wsnmp32_ordinal583 TEXTEQU <__imp_wsnmp32_ordinal583>
extern __imp_wsnmp32_ordinal584:PANYARGS
wsnmp32_ordinal584 TEXTEQU <__imp_wsnmp32_ordinal584>
extern __imp_wsnmp32_ordinal585:PANYARGS
wsnmp32_ordinal585 TEXTEQU <__imp_wsnmp32_ordinal585>
extern __imp_wsnmp32_ordinal586:PANYARGS
wsnmp32_ordinal586 TEXTEQU <__imp_wsnmp32_ordinal586>
extern __imp_wsnmp32_ordinal587:PANYARGS
wsnmp32_ordinal587 TEXTEQU <__imp_wsnmp32_ordinal587>
extern __imp_wsnmp32_ordinal588:PANYARGS
wsnmp32_ordinal588 TEXTEQU <__imp_wsnmp32_ordinal588>
extern __imp_wsnmp32_ordinal589:PANYARGS
wsnmp32_ordinal589 TEXTEQU <__imp_wsnmp32_ordinal589>
extern __imp_wsnmp32_ordinal590:PANYARGS
wsnmp32_ordinal590 TEXTEQU <__imp_wsnmp32_ordinal590>
extern __imp_wsnmp32_ordinal591:PANYARGS
wsnmp32_ordinal591 TEXTEQU <__imp_wsnmp32_ordinal591>
extern __imp_wsnmp32_ordinal592:PANYARGS
wsnmp32_ordinal592 TEXTEQU <__imp_wsnmp32_ordinal592>
extern __imp_wsnmp32_ordinal593:PANYARGS
wsnmp32_ordinal593 TEXTEQU <__imp_wsnmp32_ordinal593>
extern __imp_wsnmp32_ordinal594:PANYARGS
wsnmp32_ordinal594 TEXTEQU <__imp_wsnmp32_ordinal594>
extern __imp_wsnmp32_ordinal595:PANYARGS
wsnmp32_ordinal595 TEXTEQU <__imp_wsnmp32_ordinal595>
extern __imp_wsnmp32_ordinal596:PANYARGS
wsnmp32_ordinal596 TEXTEQU <__imp_wsnmp32_ordinal596>
extern __imp_wsnmp32_ordinal597:PANYARGS
wsnmp32_ordinal597 TEXTEQU <__imp_wsnmp32_ordinal597>
extern __imp_wsnmp32_ordinal598:PANYARGS
wsnmp32_ordinal598 TEXTEQU <__imp_wsnmp32_ordinal598>
extern __imp_wsnmp32_ordinal599:PANYARGS
wsnmp32_ordinal599 TEXTEQU <__imp_wsnmp32_ordinal599>
extern __imp_SnmpCreateVbl:PANYARGS
SnmpCreateVbl TEXTEQU <__imp_SnmpCreateVbl>
extern __imp_SnmpDuplicateVbl:PANYARGS
SnmpDuplicateVbl TEXTEQU <__imp_SnmpDuplicateVbl>
extern __imp_SnmpFreeVbl:PANYARGS
SnmpFreeVbl TEXTEQU <__imp_SnmpFreeVbl>
extern __imp_SnmpCountVbl:PANYARGS
SnmpCountVbl TEXTEQU <__imp_SnmpCountVbl>
extern __imp_SnmpGetVb:PANYARGS
SnmpGetVb TEXTEQU <__imp_SnmpGetVb>
extern __imp_SnmpSetVb:PANYARGS
SnmpSetVb TEXTEQU <__imp_SnmpSetVb>
extern __imp_SnmpDeleteVb:PANYARGS
SnmpDeleteVb TEXTEQU <__imp_SnmpDeleteVb>
extern __imp_wsnmp32_ordinal607:PANYARGS
wsnmp32_ordinal607 TEXTEQU <__imp_wsnmp32_ordinal607>
extern __imp_wsnmp32_ordinal608:PANYARGS
wsnmp32_ordinal608 TEXTEQU <__imp_wsnmp32_ordinal608>
extern __imp_wsnmp32_ordinal609:PANYARGS
wsnmp32_ordinal609 TEXTEQU <__imp_wsnmp32_ordinal609>
extern __imp_wsnmp32_ordinal610:PANYARGS
wsnmp32_ordinal610 TEXTEQU <__imp_wsnmp32_ordinal610>
extern __imp_wsnmp32_ordinal611:PANYARGS
wsnmp32_ordinal611 TEXTEQU <__imp_wsnmp32_ordinal611>
extern __imp_wsnmp32_ordinal612:PANYARGS
wsnmp32_ordinal612 TEXTEQU <__imp_wsnmp32_ordinal612>
extern __imp_wsnmp32_ordinal613:PANYARGS
wsnmp32_ordinal613 TEXTEQU <__imp_wsnmp32_ordinal613>
extern __imp_wsnmp32_ordinal614:PANYARGS
wsnmp32_ordinal614 TEXTEQU <__imp_wsnmp32_ordinal614>
extern __imp_wsnmp32_ordinal615:PANYARGS
wsnmp32_ordinal615 TEXTEQU <__imp_wsnmp32_ordinal615>
extern __imp_wsnmp32_ordinal616:PANYARGS
wsnmp32_ordinal616 TEXTEQU <__imp_wsnmp32_ordinal616>
extern __imp_wsnmp32_ordinal617:PANYARGS
wsnmp32_ordinal617 TEXTEQU <__imp_wsnmp32_ordinal617>
extern __imp_wsnmp32_ordinal618:PANYARGS
wsnmp32_ordinal618 TEXTEQU <__imp_wsnmp32_ordinal618>
extern __imp_wsnmp32_ordinal619:PANYARGS
wsnmp32_ordinal619 TEXTEQU <__imp_wsnmp32_ordinal619>
extern __imp_wsnmp32_ordinal620:PANYARGS
wsnmp32_ordinal620 TEXTEQU <__imp_wsnmp32_ordinal620>
extern __imp_wsnmp32_ordinal621:PANYARGS
wsnmp32_ordinal621 TEXTEQU <__imp_wsnmp32_ordinal621>
extern __imp_wsnmp32_ordinal622:PANYARGS
wsnmp32_ordinal622 TEXTEQU <__imp_wsnmp32_ordinal622>
extern __imp_wsnmp32_ordinal623:PANYARGS
wsnmp32_ordinal623 TEXTEQU <__imp_wsnmp32_ordinal623>
extern __imp_wsnmp32_ordinal624:PANYARGS
wsnmp32_ordinal624 TEXTEQU <__imp_wsnmp32_ordinal624>
extern __imp_wsnmp32_ordinal625:PANYARGS
wsnmp32_ordinal625 TEXTEQU <__imp_wsnmp32_ordinal625>
extern __imp_wsnmp32_ordinal626:PANYARGS
wsnmp32_ordinal626 TEXTEQU <__imp_wsnmp32_ordinal626>
extern __imp_wsnmp32_ordinal627:PANYARGS
wsnmp32_ordinal627 TEXTEQU <__imp_wsnmp32_ordinal627>
extern __imp_wsnmp32_ordinal628:PANYARGS
wsnmp32_ordinal628 TEXTEQU <__imp_wsnmp32_ordinal628>
extern __imp_wsnmp32_ordinal629:PANYARGS
wsnmp32_ordinal629 TEXTEQU <__imp_wsnmp32_ordinal629>
extern __imp_wsnmp32_ordinal630:PANYARGS
wsnmp32_ordinal630 TEXTEQU <__imp_wsnmp32_ordinal630>
extern __imp_wsnmp32_ordinal631:PANYARGS
wsnmp32_ordinal631 TEXTEQU <__imp_wsnmp32_ordinal631>
extern __imp_wsnmp32_ordinal632:PANYARGS
wsnmp32_ordinal632 TEXTEQU <__imp_wsnmp32_ordinal632>
extern __imp_wsnmp32_ordinal633:PANYARGS
wsnmp32_ordinal633 TEXTEQU <__imp_wsnmp32_ordinal633>
extern __imp_wsnmp32_ordinal634:PANYARGS
wsnmp32_ordinal634 TEXTEQU <__imp_wsnmp32_ordinal634>
extern __imp_wsnmp32_ordinal635:PANYARGS
wsnmp32_ordinal635 TEXTEQU <__imp_wsnmp32_ordinal635>
extern __imp_wsnmp32_ordinal636:PANYARGS
wsnmp32_ordinal636 TEXTEQU <__imp_wsnmp32_ordinal636>
extern __imp_wsnmp32_ordinal637:PANYARGS
wsnmp32_ordinal637 TEXTEQU <__imp_wsnmp32_ordinal637>
extern __imp_wsnmp32_ordinal638:PANYARGS
wsnmp32_ordinal638 TEXTEQU <__imp_wsnmp32_ordinal638>
extern __imp_wsnmp32_ordinal639:PANYARGS
wsnmp32_ordinal639 TEXTEQU <__imp_wsnmp32_ordinal639>
extern __imp_wsnmp32_ordinal640:PANYARGS
wsnmp32_ordinal640 TEXTEQU <__imp_wsnmp32_ordinal640>
extern __imp_wsnmp32_ordinal641:PANYARGS
wsnmp32_ordinal641 TEXTEQU <__imp_wsnmp32_ordinal641>
extern __imp_wsnmp32_ordinal642:PANYARGS
wsnmp32_ordinal642 TEXTEQU <__imp_wsnmp32_ordinal642>
extern __imp_wsnmp32_ordinal643:PANYARGS
wsnmp32_ordinal643 TEXTEQU <__imp_wsnmp32_ordinal643>
extern __imp_wsnmp32_ordinal644:PANYARGS
wsnmp32_ordinal644 TEXTEQU <__imp_wsnmp32_ordinal644>
extern __imp_wsnmp32_ordinal645:PANYARGS
wsnmp32_ordinal645 TEXTEQU <__imp_wsnmp32_ordinal645>
extern __imp_wsnmp32_ordinal646:PANYARGS
wsnmp32_ordinal646 TEXTEQU <__imp_wsnmp32_ordinal646>
extern __imp_wsnmp32_ordinal647:PANYARGS
wsnmp32_ordinal647 TEXTEQU <__imp_wsnmp32_ordinal647>
extern __imp_wsnmp32_ordinal648:PANYARGS
wsnmp32_ordinal648 TEXTEQU <__imp_wsnmp32_ordinal648>
extern __imp_wsnmp32_ordinal649:PANYARGS
wsnmp32_ordinal649 TEXTEQU <__imp_wsnmp32_ordinal649>
extern __imp_wsnmp32_ordinal650:PANYARGS
wsnmp32_ordinal650 TEXTEQU <__imp_wsnmp32_ordinal650>
extern __imp_wsnmp32_ordinal651:PANYARGS
wsnmp32_ordinal651 TEXTEQU <__imp_wsnmp32_ordinal651>
extern __imp_wsnmp32_ordinal652:PANYARGS
wsnmp32_ordinal652 TEXTEQU <__imp_wsnmp32_ordinal652>
extern __imp_wsnmp32_ordinal653:PANYARGS
wsnmp32_ordinal653 TEXTEQU <__imp_wsnmp32_ordinal653>
extern __imp_wsnmp32_ordinal654:PANYARGS
wsnmp32_ordinal654 TEXTEQU <__imp_wsnmp32_ordinal654>
extern __imp_wsnmp32_ordinal655:PANYARGS
wsnmp32_ordinal655 TEXTEQU <__imp_wsnmp32_ordinal655>
extern __imp_wsnmp32_ordinal656:PANYARGS
wsnmp32_ordinal656 TEXTEQU <__imp_wsnmp32_ordinal656>
extern __imp_wsnmp32_ordinal657:PANYARGS
wsnmp32_ordinal657 TEXTEQU <__imp_wsnmp32_ordinal657>
extern __imp_wsnmp32_ordinal658:PANYARGS
wsnmp32_ordinal658 TEXTEQU <__imp_wsnmp32_ordinal658>
extern __imp_wsnmp32_ordinal659:PANYARGS
wsnmp32_ordinal659 TEXTEQU <__imp_wsnmp32_ordinal659>
extern __imp_wsnmp32_ordinal660:PANYARGS
wsnmp32_ordinal660 TEXTEQU <__imp_wsnmp32_ordinal660>
extern __imp_wsnmp32_ordinal661:PANYARGS
wsnmp32_ordinal661 TEXTEQU <__imp_wsnmp32_ordinal661>
extern __imp_wsnmp32_ordinal662:PANYARGS
wsnmp32_ordinal662 TEXTEQU <__imp_wsnmp32_ordinal662>
extern __imp_wsnmp32_ordinal663:PANYARGS
wsnmp32_ordinal663 TEXTEQU <__imp_wsnmp32_ordinal663>
extern __imp_wsnmp32_ordinal664:PANYARGS
wsnmp32_ordinal664 TEXTEQU <__imp_wsnmp32_ordinal664>
extern __imp_wsnmp32_ordinal665:PANYARGS
wsnmp32_ordinal665 TEXTEQU <__imp_wsnmp32_ordinal665>
extern __imp_wsnmp32_ordinal666:PANYARGS
wsnmp32_ordinal666 TEXTEQU <__imp_wsnmp32_ordinal666>
extern __imp_wsnmp32_ordinal667:PANYARGS
wsnmp32_ordinal667 TEXTEQU <__imp_wsnmp32_ordinal667>
extern __imp_wsnmp32_ordinal668:PANYARGS
wsnmp32_ordinal668 TEXTEQU <__imp_wsnmp32_ordinal668>
extern __imp_wsnmp32_ordinal669:PANYARGS
wsnmp32_ordinal669 TEXTEQU <__imp_wsnmp32_ordinal669>
extern __imp_wsnmp32_ordinal670:PANYARGS
wsnmp32_ordinal670 TEXTEQU <__imp_wsnmp32_ordinal670>
extern __imp_wsnmp32_ordinal671:PANYARGS
wsnmp32_ordinal671 TEXTEQU <__imp_wsnmp32_ordinal671>
extern __imp_wsnmp32_ordinal672:PANYARGS
wsnmp32_ordinal672 TEXTEQU <__imp_wsnmp32_ordinal672>
extern __imp_wsnmp32_ordinal673:PANYARGS
wsnmp32_ordinal673 TEXTEQU <__imp_wsnmp32_ordinal673>
extern __imp_wsnmp32_ordinal674:PANYARGS
wsnmp32_ordinal674 TEXTEQU <__imp_wsnmp32_ordinal674>
extern __imp_wsnmp32_ordinal675:PANYARGS
wsnmp32_ordinal675 TEXTEQU <__imp_wsnmp32_ordinal675>
extern __imp_wsnmp32_ordinal676:PANYARGS
wsnmp32_ordinal676 TEXTEQU <__imp_wsnmp32_ordinal676>
extern __imp_wsnmp32_ordinal677:PANYARGS
wsnmp32_ordinal677 TEXTEQU <__imp_wsnmp32_ordinal677>
extern __imp_wsnmp32_ordinal678:PANYARGS
wsnmp32_ordinal678 TEXTEQU <__imp_wsnmp32_ordinal678>
extern __imp_wsnmp32_ordinal679:PANYARGS
wsnmp32_ordinal679 TEXTEQU <__imp_wsnmp32_ordinal679>
extern __imp_wsnmp32_ordinal680:PANYARGS
wsnmp32_ordinal680 TEXTEQU <__imp_wsnmp32_ordinal680>
extern __imp_wsnmp32_ordinal681:PANYARGS
wsnmp32_ordinal681 TEXTEQU <__imp_wsnmp32_ordinal681>
extern __imp_wsnmp32_ordinal682:PANYARGS
wsnmp32_ordinal682 TEXTEQU <__imp_wsnmp32_ordinal682>
extern __imp_wsnmp32_ordinal683:PANYARGS
wsnmp32_ordinal683 TEXTEQU <__imp_wsnmp32_ordinal683>
extern __imp_wsnmp32_ordinal684:PANYARGS
wsnmp32_ordinal684 TEXTEQU <__imp_wsnmp32_ordinal684>
extern __imp_wsnmp32_ordinal685:PANYARGS
wsnmp32_ordinal685 TEXTEQU <__imp_wsnmp32_ordinal685>
extern __imp_wsnmp32_ordinal686:PANYARGS
wsnmp32_ordinal686 TEXTEQU <__imp_wsnmp32_ordinal686>
extern __imp_wsnmp32_ordinal687:PANYARGS
wsnmp32_ordinal687 TEXTEQU <__imp_wsnmp32_ordinal687>
extern __imp_wsnmp32_ordinal688:PANYARGS
wsnmp32_ordinal688 TEXTEQU <__imp_wsnmp32_ordinal688>
extern __imp_wsnmp32_ordinal689:PANYARGS
wsnmp32_ordinal689 TEXTEQU <__imp_wsnmp32_ordinal689>
extern __imp_wsnmp32_ordinal690:PANYARGS
wsnmp32_ordinal690 TEXTEQU <__imp_wsnmp32_ordinal690>
extern __imp_wsnmp32_ordinal691:PANYARGS
wsnmp32_ordinal691 TEXTEQU <__imp_wsnmp32_ordinal691>
extern __imp_wsnmp32_ordinal692:PANYARGS
wsnmp32_ordinal692 TEXTEQU <__imp_wsnmp32_ordinal692>
extern __imp_wsnmp32_ordinal693:PANYARGS
wsnmp32_ordinal693 TEXTEQU <__imp_wsnmp32_ordinal693>
extern __imp_wsnmp32_ordinal694:PANYARGS
wsnmp32_ordinal694 TEXTEQU <__imp_wsnmp32_ordinal694>
extern __imp_wsnmp32_ordinal695:PANYARGS
wsnmp32_ordinal695 TEXTEQU <__imp_wsnmp32_ordinal695>
extern __imp_wsnmp32_ordinal696:PANYARGS
wsnmp32_ordinal696 TEXTEQU <__imp_wsnmp32_ordinal696>
extern __imp_wsnmp32_ordinal697:PANYARGS
wsnmp32_ordinal697 TEXTEQU <__imp_wsnmp32_ordinal697>
extern __imp_wsnmp32_ordinal698:PANYARGS
wsnmp32_ordinal698 TEXTEQU <__imp_wsnmp32_ordinal698>
extern __imp_wsnmp32_ordinal699:PANYARGS
wsnmp32_ordinal699 TEXTEQU <__imp_wsnmp32_ordinal699>
extern __imp_wsnmp32_ordinal700:PANYARGS
wsnmp32_ordinal700 TEXTEQU <__imp_wsnmp32_ordinal700>
extern __imp_wsnmp32_ordinal701:PANYARGS
wsnmp32_ordinal701 TEXTEQU <__imp_wsnmp32_ordinal701>
extern __imp_wsnmp32_ordinal702:PANYARGS
wsnmp32_ordinal702 TEXTEQU <__imp_wsnmp32_ordinal702>
extern __imp_wsnmp32_ordinal703:PANYARGS
wsnmp32_ordinal703 TEXTEQU <__imp_wsnmp32_ordinal703>
extern __imp_wsnmp32_ordinal704:PANYARGS
wsnmp32_ordinal704 TEXTEQU <__imp_wsnmp32_ordinal704>
extern __imp_wsnmp32_ordinal705:PANYARGS
wsnmp32_ordinal705 TEXTEQU <__imp_wsnmp32_ordinal705>
extern __imp_wsnmp32_ordinal706:PANYARGS
wsnmp32_ordinal706 TEXTEQU <__imp_wsnmp32_ordinal706>
extern __imp_wsnmp32_ordinal707:PANYARGS
wsnmp32_ordinal707 TEXTEQU <__imp_wsnmp32_ordinal707>
extern __imp_wsnmp32_ordinal708:PANYARGS
wsnmp32_ordinal708 TEXTEQU <__imp_wsnmp32_ordinal708>
extern __imp_wsnmp32_ordinal709:PANYARGS
wsnmp32_ordinal709 TEXTEQU <__imp_wsnmp32_ordinal709>
extern __imp_wsnmp32_ordinal710:PANYARGS
wsnmp32_ordinal710 TEXTEQU <__imp_wsnmp32_ordinal710>
extern __imp_wsnmp32_ordinal711:PANYARGS
wsnmp32_ordinal711 TEXTEQU <__imp_wsnmp32_ordinal711>
extern __imp_wsnmp32_ordinal712:PANYARGS
wsnmp32_ordinal712 TEXTEQU <__imp_wsnmp32_ordinal712>
extern __imp_wsnmp32_ordinal713:PANYARGS
wsnmp32_ordinal713 TEXTEQU <__imp_wsnmp32_ordinal713>
extern __imp_wsnmp32_ordinal714:PANYARGS
wsnmp32_ordinal714 TEXTEQU <__imp_wsnmp32_ordinal714>
extern __imp_wsnmp32_ordinal715:PANYARGS
wsnmp32_ordinal715 TEXTEQU <__imp_wsnmp32_ordinal715>
extern __imp_wsnmp32_ordinal716:PANYARGS
wsnmp32_ordinal716 TEXTEQU <__imp_wsnmp32_ordinal716>
extern __imp_wsnmp32_ordinal717:PANYARGS
wsnmp32_ordinal717 TEXTEQU <__imp_wsnmp32_ordinal717>
extern __imp_wsnmp32_ordinal718:PANYARGS
wsnmp32_ordinal718 TEXTEQU <__imp_wsnmp32_ordinal718>
extern __imp_wsnmp32_ordinal719:PANYARGS
wsnmp32_ordinal719 TEXTEQU <__imp_wsnmp32_ordinal719>
extern __imp_wsnmp32_ordinal720:PANYARGS
wsnmp32_ordinal720 TEXTEQU <__imp_wsnmp32_ordinal720>
extern __imp_wsnmp32_ordinal721:PANYARGS
wsnmp32_ordinal721 TEXTEQU <__imp_wsnmp32_ordinal721>
extern __imp_wsnmp32_ordinal722:PANYARGS
wsnmp32_ordinal722 TEXTEQU <__imp_wsnmp32_ordinal722>
extern __imp_wsnmp32_ordinal723:PANYARGS
wsnmp32_ordinal723 TEXTEQU <__imp_wsnmp32_ordinal723>
extern __imp_wsnmp32_ordinal724:PANYARGS
wsnmp32_ordinal724 TEXTEQU <__imp_wsnmp32_ordinal724>
extern __imp_wsnmp32_ordinal725:PANYARGS
wsnmp32_ordinal725 TEXTEQU <__imp_wsnmp32_ordinal725>
extern __imp_wsnmp32_ordinal726:PANYARGS
wsnmp32_ordinal726 TEXTEQU <__imp_wsnmp32_ordinal726>
extern __imp_wsnmp32_ordinal727:PANYARGS
wsnmp32_ordinal727 TEXTEQU <__imp_wsnmp32_ordinal727>
extern __imp_wsnmp32_ordinal728:PANYARGS
wsnmp32_ordinal728 TEXTEQU <__imp_wsnmp32_ordinal728>
extern __imp_wsnmp32_ordinal729:PANYARGS
wsnmp32_ordinal729 TEXTEQU <__imp_wsnmp32_ordinal729>
extern __imp_wsnmp32_ordinal730:PANYARGS
wsnmp32_ordinal730 TEXTEQU <__imp_wsnmp32_ordinal730>
extern __imp_wsnmp32_ordinal731:PANYARGS
wsnmp32_ordinal731 TEXTEQU <__imp_wsnmp32_ordinal731>
extern __imp_wsnmp32_ordinal732:PANYARGS
wsnmp32_ordinal732 TEXTEQU <__imp_wsnmp32_ordinal732>
extern __imp_wsnmp32_ordinal733:PANYARGS
wsnmp32_ordinal733 TEXTEQU <__imp_wsnmp32_ordinal733>
extern __imp_wsnmp32_ordinal734:PANYARGS
wsnmp32_ordinal734 TEXTEQU <__imp_wsnmp32_ordinal734>
extern __imp_wsnmp32_ordinal735:PANYARGS
wsnmp32_ordinal735 TEXTEQU <__imp_wsnmp32_ordinal735>
extern __imp_wsnmp32_ordinal736:PANYARGS
wsnmp32_ordinal736 TEXTEQU <__imp_wsnmp32_ordinal736>
extern __imp_wsnmp32_ordinal737:PANYARGS
wsnmp32_ordinal737 TEXTEQU <__imp_wsnmp32_ordinal737>
extern __imp_wsnmp32_ordinal738:PANYARGS
wsnmp32_ordinal738 TEXTEQU <__imp_wsnmp32_ordinal738>
extern __imp_wsnmp32_ordinal739:PANYARGS
wsnmp32_ordinal739 TEXTEQU <__imp_wsnmp32_ordinal739>
extern __imp_wsnmp32_ordinal740:PANYARGS
wsnmp32_ordinal740 TEXTEQU <__imp_wsnmp32_ordinal740>
extern __imp_wsnmp32_ordinal741:PANYARGS
wsnmp32_ordinal741 TEXTEQU <__imp_wsnmp32_ordinal741>
extern __imp_wsnmp32_ordinal742:PANYARGS
wsnmp32_ordinal742 TEXTEQU <__imp_wsnmp32_ordinal742>
extern __imp_wsnmp32_ordinal743:PANYARGS
wsnmp32_ordinal743 TEXTEQU <__imp_wsnmp32_ordinal743>
extern __imp_wsnmp32_ordinal744:PANYARGS
wsnmp32_ordinal744 TEXTEQU <__imp_wsnmp32_ordinal744>
extern __imp_wsnmp32_ordinal745:PANYARGS
wsnmp32_ordinal745 TEXTEQU <__imp_wsnmp32_ordinal745>
extern __imp_wsnmp32_ordinal746:PANYARGS
wsnmp32_ordinal746 TEXTEQU <__imp_wsnmp32_ordinal746>
extern __imp_wsnmp32_ordinal747:PANYARGS
wsnmp32_ordinal747 TEXTEQU <__imp_wsnmp32_ordinal747>
extern __imp_wsnmp32_ordinal748:PANYARGS
wsnmp32_ordinal748 TEXTEQU <__imp_wsnmp32_ordinal748>
extern __imp_wsnmp32_ordinal749:PANYARGS
wsnmp32_ordinal749 TEXTEQU <__imp_wsnmp32_ordinal749>
extern __imp_wsnmp32_ordinal750:PANYARGS
wsnmp32_ordinal750 TEXTEQU <__imp_wsnmp32_ordinal750>
extern __imp_wsnmp32_ordinal751:PANYARGS
wsnmp32_ordinal751 TEXTEQU <__imp_wsnmp32_ordinal751>
extern __imp_wsnmp32_ordinal752:PANYARGS
wsnmp32_ordinal752 TEXTEQU <__imp_wsnmp32_ordinal752>
extern __imp_wsnmp32_ordinal753:PANYARGS
wsnmp32_ordinal753 TEXTEQU <__imp_wsnmp32_ordinal753>
extern __imp_wsnmp32_ordinal754:PANYARGS
wsnmp32_ordinal754 TEXTEQU <__imp_wsnmp32_ordinal754>
extern __imp_wsnmp32_ordinal755:PANYARGS
wsnmp32_ordinal755 TEXTEQU <__imp_wsnmp32_ordinal755>
extern __imp_wsnmp32_ordinal756:PANYARGS
wsnmp32_ordinal756 TEXTEQU <__imp_wsnmp32_ordinal756>
extern __imp_wsnmp32_ordinal757:PANYARGS
wsnmp32_ordinal757 TEXTEQU <__imp_wsnmp32_ordinal757>
extern __imp_wsnmp32_ordinal758:PANYARGS
wsnmp32_ordinal758 TEXTEQU <__imp_wsnmp32_ordinal758>
extern __imp_wsnmp32_ordinal759:PANYARGS
wsnmp32_ordinal759 TEXTEQU <__imp_wsnmp32_ordinal759>
extern __imp_wsnmp32_ordinal760:PANYARGS
wsnmp32_ordinal760 TEXTEQU <__imp_wsnmp32_ordinal760>
extern __imp_wsnmp32_ordinal761:PANYARGS
wsnmp32_ordinal761 TEXTEQU <__imp_wsnmp32_ordinal761>
extern __imp_wsnmp32_ordinal762:PANYARGS
wsnmp32_ordinal762 TEXTEQU <__imp_wsnmp32_ordinal762>
extern __imp_wsnmp32_ordinal763:PANYARGS
wsnmp32_ordinal763 TEXTEQU <__imp_wsnmp32_ordinal763>
extern __imp_wsnmp32_ordinal764:PANYARGS
wsnmp32_ordinal764 TEXTEQU <__imp_wsnmp32_ordinal764>
extern __imp_wsnmp32_ordinal765:PANYARGS
wsnmp32_ordinal765 TEXTEQU <__imp_wsnmp32_ordinal765>
extern __imp_wsnmp32_ordinal766:PANYARGS
wsnmp32_ordinal766 TEXTEQU <__imp_wsnmp32_ordinal766>
extern __imp_wsnmp32_ordinal767:PANYARGS
wsnmp32_ordinal767 TEXTEQU <__imp_wsnmp32_ordinal767>
extern __imp_wsnmp32_ordinal768:PANYARGS
wsnmp32_ordinal768 TEXTEQU <__imp_wsnmp32_ordinal768>
extern __imp_wsnmp32_ordinal769:PANYARGS
wsnmp32_ordinal769 TEXTEQU <__imp_wsnmp32_ordinal769>
extern __imp_wsnmp32_ordinal770:PANYARGS
wsnmp32_ordinal770 TEXTEQU <__imp_wsnmp32_ordinal770>
extern __imp_wsnmp32_ordinal771:PANYARGS
wsnmp32_ordinal771 TEXTEQU <__imp_wsnmp32_ordinal771>
extern __imp_wsnmp32_ordinal772:PANYARGS
wsnmp32_ordinal772 TEXTEQU <__imp_wsnmp32_ordinal772>
extern __imp_wsnmp32_ordinal773:PANYARGS
wsnmp32_ordinal773 TEXTEQU <__imp_wsnmp32_ordinal773>
extern __imp_wsnmp32_ordinal774:PANYARGS
wsnmp32_ordinal774 TEXTEQU <__imp_wsnmp32_ordinal774>
extern __imp_wsnmp32_ordinal775:PANYARGS
wsnmp32_ordinal775 TEXTEQU <__imp_wsnmp32_ordinal775>
extern __imp_wsnmp32_ordinal776:PANYARGS
wsnmp32_ordinal776 TEXTEQU <__imp_wsnmp32_ordinal776>
extern __imp_wsnmp32_ordinal777:PANYARGS
wsnmp32_ordinal777 TEXTEQU <__imp_wsnmp32_ordinal777>
extern __imp_wsnmp32_ordinal778:PANYARGS
wsnmp32_ordinal778 TEXTEQU <__imp_wsnmp32_ordinal778>
extern __imp_wsnmp32_ordinal779:PANYARGS
wsnmp32_ordinal779 TEXTEQU <__imp_wsnmp32_ordinal779>
extern __imp_wsnmp32_ordinal780:PANYARGS
wsnmp32_ordinal780 TEXTEQU <__imp_wsnmp32_ordinal780>
extern __imp_wsnmp32_ordinal781:PANYARGS
wsnmp32_ordinal781 TEXTEQU <__imp_wsnmp32_ordinal781>
extern __imp_wsnmp32_ordinal782:PANYARGS
wsnmp32_ordinal782 TEXTEQU <__imp_wsnmp32_ordinal782>
extern __imp_wsnmp32_ordinal783:PANYARGS
wsnmp32_ordinal783 TEXTEQU <__imp_wsnmp32_ordinal783>
extern __imp_wsnmp32_ordinal784:PANYARGS
wsnmp32_ordinal784 TEXTEQU <__imp_wsnmp32_ordinal784>
extern __imp_wsnmp32_ordinal785:PANYARGS
wsnmp32_ordinal785 TEXTEQU <__imp_wsnmp32_ordinal785>
extern __imp_wsnmp32_ordinal786:PANYARGS
wsnmp32_ordinal786 TEXTEQU <__imp_wsnmp32_ordinal786>
extern __imp_wsnmp32_ordinal787:PANYARGS
wsnmp32_ordinal787 TEXTEQU <__imp_wsnmp32_ordinal787>
extern __imp_wsnmp32_ordinal788:PANYARGS
wsnmp32_ordinal788 TEXTEQU <__imp_wsnmp32_ordinal788>
extern __imp_wsnmp32_ordinal789:PANYARGS
wsnmp32_ordinal789 TEXTEQU <__imp_wsnmp32_ordinal789>
extern __imp_wsnmp32_ordinal790:PANYARGS
wsnmp32_ordinal790 TEXTEQU <__imp_wsnmp32_ordinal790>
extern __imp_wsnmp32_ordinal791:PANYARGS
wsnmp32_ordinal791 TEXTEQU <__imp_wsnmp32_ordinal791>
extern __imp_wsnmp32_ordinal792:PANYARGS
wsnmp32_ordinal792 TEXTEQU <__imp_wsnmp32_ordinal792>
extern __imp_wsnmp32_ordinal793:PANYARGS
wsnmp32_ordinal793 TEXTEQU <__imp_wsnmp32_ordinal793>
extern __imp_wsnmp32_ordinal794:PANYARGS
wsnmp32_ordinal794 TEXTEQU <__imp_wsnmp32_ordinal794>
extern __imp_wsnmp32_ordinal795:PANYARGS
wsnmp32_ordinal795 TEXTEQU <__imp_wsnmp32_ordinal795>
extern __imp_wsnmp32_ordinal796:PANYARGS
wsnmp32_ordinal796 TEXTEQU <__imp_wsnmp32_ordinal796>
extern __imp_wsnmp32_ordinal797:PANYARGS
wsnmp32_ordinal797 TEXTEQU <__imp_wsnmp32_ordinal797>
extern __imp_wsnmp32_ordinal798:PANYARGS
wsnmp32_ordinal798 TEXTEQU <__imp_wsnmp32_ordinal798>
extern __imp_wsnmp32_ordinal799:PANYARGS
wsnmp32_ordinal799 TEXTEQU <__imp_wsnmp32_ordinal799>
extern __imp_wsnmp32_ordinal800:PANYARGS
wsnmp32_ordinal800 TEXTEQU <__imp_wsnmp32_ordinal800>
extern __imp_wsnmp32_ordinal801:PANYARGS
wsnmp32_ordinal801 TEXTEQU <__imp_wsnmp32_ordinal801>
extern __imp_wsnmp32_ordinal802:PANYARGS
wsnmp32_ordinal802 TEXTEQU <__imp_wsnmp32_ordinal802>
extern __imp_wsnmp32_ordinal803:PANYARGS
wsnmp32_ordinal803 TEXTEQU <__imp_wsnmp32_ordinal803>
extern __imp_wsnmp32_ordinal804:PANYARGS
wsnmp32_ordinal804 TEXTEQU <__imp_wsnmp32_ordinal804>
extern __imp_wsnmp32_ordinal805:PANYARGS
wsnmp32_ordinal805 TEXTEQU <__imp_wsnmp32_ordinal805>
extern __imp_wsnmp32_ordinal806:PANYARGS
wsnmp32_ordinal806 TEXTEQU <__imp_wsnmp32_ordinal806>
extern __imp_wsnmp32_ordinal807:PANYARGS
wsnmp32_ordinal807 TEXTEQU <__imp_wsnmp32_ordinal807>
extern __imp_wsnmp32_ordinal808:PANYARGS
wsnmp32_ordinal808 TEXTEQU <__imp_wsnmp32_ordinal808>
extern __imp_wsnmp32_ordinal809:PANYARGS
wsnmp32_ordinal809 TEXTEQU <__imp_wsnmp32_ordinal809>
extern __imp_wsnmp32_ordinal810:PANYARGS
wsnmp32_ordinal810 TEXTEQU <__imp_wsnmp32_ordinal810>
extern __imp_wsnmp32_ordinal811:PANYARGS
wsnmp32_ordinal811 TEXTEQU <__imp_wsnmp32_ordinal811>
extern __imp_wsnmp32_ordinal812:PANYARGS
wsnmp32_ordinal812 TEXTEQU <__imp_wsnmp32_ordinal812>
extern __imp_wsnmp32_ordinal813:PANYARGS
wsnmp32_ordinal813 TEXTEQU <__imp_wsnmp32_ordinal813>
extern __imp_wsnmp32_ordinal814:PANYARGS
wsnmp32_ordinal814 TEXTEQU <__imp_wsnmp32_ordinal814>
extern __imp_wsnmp32_ordinal815:PANYARGS
wsnmp32_ordinal815 TEXTEQU <__imp_wsnmp32_ordinal815>
extern __imp_wsnmp32_ordinal816:PANYARGS
wsnmp32_ordinal816 TEXTEQU <__imp_wsnmp32_ordinal816>
extern __imp_wsnmp32_ordinal817:PANYARGS
wsnmp32_ordinal817 TEXTEQU <__imp_wsnmp32_ordinal817>
extern __imp_wsnmp32_ordinal818:PANYARGS
wsnmp32_ordinal818 TEXTEQU <__imp_wsnmp32_ordinal818>
extern __imp_wsnmp32_ordinal819:PANYARGS
wsnmp32_ordinal819 TEXTEQU <__imp_wsnmp32_ordinal819>
extern __imp_wsnmp32_ordinal820:PANYARGS
wsnmp32_ordinal820 TEXTEQU <__imp_wsnmp32_ordinal820>
extern __imp_wsnmp32_ordinal821:PANYARGS
wsnmp32_ordinal821 TEXTEQU <__imp_wsnmp32_ordinal821>
extern __imp_wsnmp32_ordinal822:PANYARGS
wsnmp32_ordinal822 TEXTEQU <__imp_wsnmp32_ordinal822>
extern __imp_wsnmp32_ordinal823:PANYARGS
wsnmp32_ordinal823 TEXTEQU <__imp_wsnmp32_ordinal823>
extern __imp_wsnmp32_ordinal824:PANYARGS
wsnmp32_ordinal824 TEXTEQU <__imp_wsnmp32_ordinal824>
extern __imp_wsnmp32_ordinal825:PANYARGS
wsnmp32_ordinal825 TEXTEQU <__imp_wsnmp32_ordinal825>
extern __imp_wsnmp32_ordinal826:PANYARGS
wsnmp32_ordinal826 TEXTEQU <__imp_wsnmp32_ordinal826>
extern __imp_wsnmp32_ordinal827:PANYARGS
wsnmp32_ordinal827 TEXTEQU <__imp_wsnmp32_ordinal827>
extern __imp_wsnmp32_ordinal828:PANYARGS
wsnmp32_ordinal828 TEXTEQU <__imp_wsnmp32_ordinal828>
extern __imp_wsnmp32_ordinal829:PANYARGS
wsnmp32_ordinal829 TEXTEQU <__imp_wsnmp32_ordinal829>
extern __imp_wsnmp32_ordinal830:PANYARGS
wsnmp32_ordinal830 TEXTEQU <__imp_wsnmp32_ordinal830>
extern __imp_wsnmp32_ordinal831:PANYARGS
wsnmp32_ordinal831 TEXTEQU <__imp_wsnmp32_ordinal831>
extern __imp_wsnmp32_ordinal832:PANYARGS
wsnmp32_ordinal832 TEXTEQU <__imp_wsnmp32_ordinal832>
extern __imp_wsnmp32_ordinal833:PANYARGS
wsnmp32_ordinal833 TEXTEQU <__imp_wsnmp32_ordinal833>
extern __imp_wsnmp32_ordinal834:PANYARGS
wsnmp32_ordinal834 TEXTEQU <__imp_wsnmp32_ordinal834>
extern __imp_wsnmp32_ordinal835:PANYARGS
wsnmp32_ordinal835 TEXTEQU <__imp_wsnmp32_ordinal835>
extern __imp_wsnmp32_ordinal836:PANYARGS
wsnmp32_ordinal836 TEXTEQU <__imp_wsnmp32_ordinal836>
extern __imp_wsnmp32_ordinal837:PANYARGS
wsnmp32_ordinal837 TEXTEQU <__imp_wsnmp32_ordinal837>
extern __imp_wsnmp32_ordinal838:PANYARGS
wsnmp32_ordinal838 TEXTEQU <__imp_wsnmp32_ordinal838>
extern __imp_wsnmp32_ordinal839:PANYARGS
wsnmp32_ordinal839 TEXTEQU <__imp_wsnmp32_ordinal839>
extern __imp_wsnmp32_ordinal840:PANYARGS
wsnmp32_ordinal840 TEXTEQU <__imp_wsnmp32_ordinal840>
extern __imp_wsnmp32_ordinal841:PANYARGS
wsnmp32_ordinal841 TEXTEQU <__imp_wsnmp32_ordinal841>
extern __imp_wsnmp32_ordinal842:PANYARGS
wsnmp32_ordinal842 TEXTEQU <__imp_wsnmp32_ordinal842>
extern __imp_wsnmp32_ordinal843:PANYARGS
wsnmp32_ordinal843 TEXTEQU <__imp_wsnmp32_ordinal843>
extern __imp_wsnmp32_ordinal844:PANYARGS
wsnmp32_ordinal844 TEXTEQU <__imp_wsnmp32_ordinal844>
extern __imp_wsnmp32_ordinal845:PANYARGS
wsnmp32_ordinal845 TEXTEQU <__imp_wsnmp32_ordinal845>
extern __imp_wsnmp32_ordinal846:PANYARGS
wsnmp32_ordinal846 TEXTEQU <__imp_wsnmp32_ordinal846>
extern __imp_wsnmp32_ordinal847:PANYARGS
wsnmp32_ordinal847 TEXTEQU <__imp_wsnmp32_ordinal847>
extern __imp_wsnmp32_ordinal848:PANYARGS
wsnmp32_ordinal848 TEXTEQU <__imp_wsnmp32_ordinal848>
extern __imp_wsnmp32_ordinal849:PANYARGS
wsnmp32_ordinal849 TEXTEQU <__imp_wsnmp32_ordinal849>
extern __imp_wsnmp32_ordinal850:PANYARGS
wsnmp32_ordinal850 TEXTEQU <__imp_wsnmp32_ordinal850>
extern __imp_wsnmp32_ordinal851:PANYARGS
wsnmp32_ordinal851 TEXTEQU <__imp_wsnmp32_ordinal851>
extern __imp_wsnmp32_ordinal852:PANYARGS
wsnmp32_ordinal852 TEXTEQU <__imp_wsnmp32_ordinal852>
extern __imp_wsnmp32_ordinal853:PANYARGS
wsnmp32_ordinal853 TEXTEQU <__imp_wsnmp32_ordinal853>
extern __imp_wsnmp32_ordinal854:PANYARGS
wsnmp32_ordinal854 TEXTEQU <__imp_wsnmp32_ordinal854>
extern __imp_wsnmp32_ordinal855:PANYARGS
wsnmp32_ordinal855 TEXTEQU <__imp_wsnmp32_ordinal855>
extern __imp_wsnmp32_ordinal856:PANYARGS
wsnmp32_ordinal856 TEXTEQU <__imp_wsnmp32_ordinal856>
extern __imp_wsnmp32_ordinal857:PANYARGS
wsnmp32_ordinal857 TEXTEQU <__imp_wsnmp32_ordinal857>
extern __imp_wsnmp32_ordinal858:PANYARGS
wsnmp32_ordinal858 TEXTEQU <__imp_wsnmp32_ordinal858>
extern __imp_wsnmp32_ordinal859:PANYARGS
wsnmp32_ordinal859 TEXTEQU <__imp_wsnmp32_ordinal859>
extern __imp_wsnmp32_ordinal860:PANYARGS
wsnmp32_ordinal860 TEXTEQU <__imp_wsnmp32_ordinal860>
extern __imp_wsnmp32_ordinal861:PANYARGS
wsnmp32_ordinal861 TEXTEQU <__imp_wsnmp32_ordinal861>
extern __imp_wsnmp32_ordinal862:PANYARGS
wsnmp32_ordinal862 TEXTEQU <__imp_wsnmp32_ordinal862>
extern __imp_wsnmp32_ordinal863:PANYARGS
wsnmp32_ordinal863 TEXTEQU <__imp_wsnmp32_ordinal863>
extern __imp_wsnmp32_ordinal864:PANYARGS
wsnmp32_ordinal864 TEXTEQU <__imp_wsnmp32_ordinal864>
extern __imp_wsnmp32_ordinal865:PANYARGS
wsnmp32_ordinal865 TEXTEQU <__imp_wsnmp32_ordinal865>
extern __imp_wsnmp32_ordinal866:PANYARGS
wsnmp32_ordinal866 TEXTEQU <__imp_wsnmp32_ordinal866>
extern __imp_wsnmp32_ordinal867:PANYARGS
wsnmp32_ordinal867 TEXTEQU <__imp_wsnmp32_ordinal867>
extern __imp_wsnmp32_ordinal868:PANYARGS
wsnmp32_ordinal868 TEXTEQU <__imp_wsnmp32_ordinal868>
extern __imp_wsnmp32_ordinal869:PANYARGS
wsnmp32_ordinal869 TEXTEQU <__imp_wsnmp32_ordinal869>
extern __imp_wsnmp32_ordinal870:PANYARGS
wsnmp32_ordinal870 TEXTEQU <__imp_wsnmp32_ordinal870>
extern __imp_wsnmp32_ordinal871:PANYARGS
wsnmp32_ordinal871 TEXTEQU <__imp_wsnmp32_ordinal871>
extern __imp_wsnmp32_ordinal872:PANYARGS
wsnmp32_ordinal872 TEXTEQU <__imp_wsnmp32_ordinal872>
extern __imp_wsnmp32_ordinal873:PANYARGS
wsnmp32_ordinal873 TEXTEQU <__imp_wsnmp32_ordinal873>
extern __imp_wsnmp32_ordinal874:PANYARGS
wsnmp32_ordinal874 TEXTEQU <__imp_wsnmp32_ordinal874>
extern __imp_wsnmp32_ordinal875:PANYARGS
wsnmp32_ordinal875 TEXTEQU <__imp_wsnmp32_ordinal875>
extern __imp_wsnmp32_ordinal876:PANYARGS
wsnmp32_ordinal876 TEXTEQU <__imp_wsnmp32_ordinal876>
extern __imp_wsnmp32_ordinal877:PANYARGS
wsnmp32_ordinal877 TEXTEQU <__imp_wsnmp32_ordinal877>
extern __imp_wsnmp32_ordinal878:PANYARGS
wsnmp32_ordinal878 TEXTEQU <__imp_wsnmp32_ordinal878>
extern __imp_wsnmp32_ordinal879:PANYARGS
wsnmp32_ordinal879 TEXTEQU <__imp_wsnmp32_ordinal879>
extern __imp_wsnmp32_ordinal880:PANYARGS
wsnmp32_ordinal880 TEXTEQU <__imp_wsnmp32_ordinal880>
extern __imp_wsnmp32_ordinal881:PANYARGS
wsnmp32_ordinal881 TEXTEQU <__imp_wsnmp32_ordinal881>
extern __imp_wsnmp32_ordinal882:PANYARGS
wsnmp32_ordinal882 TEXTEQU <__imp_wsnmp32_ordinal882>
extern __imp_wsnmp32_ordinal883:PANYARGS
wsnmp32_ordinal883 TEXTEQU <__imp_wsnmp32_ordinal883>
extern __imp_wsnmp32_ordinal884:PANYARGS
wsnmp32_ordinal884 TEXTEQU <__imp_wsnmp32_ordinal884>
extern __imp_wsnmp32_ordinal885:PANYARGS
wsnmp32_ordinal885 TEXTEQU <__imp_wsnmp32_ordinal885>
extern __imp_wsnmp32_ordinal886:PANYARGS
wsnmp32_ordinal886 TEXTEQU <__imp_wsnmp32_ordinal886>
extern __imp_wsnmp32_ordinal887:PANYARGS
wsnmp32_ordinal887 TEXTEQU <__imp_wsnmp32_ordinal887>
extern __imp_wsnmp32_ordinal888:PANYARGS
wsnmp32_ordinal888 TEXTEQU <__imp_wsnmp32_ordinal888>
extern __imp_wsnmp32_ordinal889:PANYARGS
wsnmp32_ordinal889 TEXTEQU <__imp_wsnmp32_ordinal889>
extern __imp_wsnmp32_ordinal890:PANYARGS
wsnmp32_ordinal890 TEXTEQU <__imp_wsnmp32_ordinal890>
extern __imp_wsnmp32_ordinal891:PANYARGS
wsnmp32_ordinal891 TEXTEQU <__imp_wsnmp32_ordinal891>
extern __imp_wsnmp32_ordinal892:PANYARGS
wsnmp32_ordinal892 TEXTEQU <__imp_wsnmp32_ordinal892>
extern __imp_wsnmp32_ordinal893:PANYARGS
wsnmp32_ordinal893 TEXTEQU <__imp_wsnmp32_ordinal893>
extern __imp_wsnmp32_ordinal894:PANYARGS
wsnmp32_ordinal894 TEXTEQU <__imp_wsnmp32_ordinal894>
extern __imp_wsnmp32_ordinal895:PANYARGS
wsnmp32_ordinal895 TEXTEQU <__imp_wsnmp32_ordinal895>
extern __imp_wsnmp32_ordinal896:PANYARGS
wsnmp32_ordinal896 TEXTEQU <__imp_wsnmp32_ordinal896>
extern __imp_wsnmp32_ordinal897:PANYARGS
wsnmp32_ordinal897 TEXTEQU <__imp_wsnmp32_ordinal897>
extern __imp_wsnmp32_ordinal898:PANYARGS
wsnmp32_ordinal898 TEXTEQU <__imp_wsnmp32_ordinal898>
extern __imp_wsnmp32_ordinal899:PANYARGS
wsnmp32_ordinal899 TEXTEQU <__imp_wsnmp32_ordinal899>
extern __imp_SnmpFreeDescriptor:PANYARGS
SnmpFreeDescriptor TEXTEQU <__imp_SnmpFreeDescriptor>
extern __imp_SnmpEncodeMsg:PANYARGS
SnmpEncodeMsg TEXTEQU <__imp_SnmpEncodeMsg>
extern __imp_SnmpDecodeMsg:PANYARGS
SnmpDecodeMsg TEXTEQU <__imp_SnmpDecodeMsg>
extern __imp_SnmpStrToOid:PANYARGS
SnmpStrToOid TEXTEQU <__imp_SnmpStrToOid>
extern __imp_SnmpOidToStr:PANYARGS
SnmpOidToStr TEXTEQU <__imp_SnmpOidToStr>
extern __imp_SnmpOidCopy:PANYARGS
SnmpOidCopy TEXTEQU <__imp_SnmpOidCopy>
extern __imp_SnmpOidCompare:PANYARGS
SnmpOidCompare TEXTEQU <__imp_SnmpOidCompare>
extern __imp_wsnmp32_ordinal907:PANYARGS
wsnmp32_ordinal907 TEXTEQU <__imp_wsnmp32_ordinal907>
extern __imp_wsnmp32_ordinal908:PANYARGS
wsnmp32_ordinal908 TEXTEQU <__imp_wsnmp32_ordinal908>
extern __imp_wsnmp32_ordinal909:PANYARGS
wsnmp32_ordinal909 TEXTEQU <__imp_wsnmp32_ordinal909>
extern __imp_wsnmp32_ordinal910:PANYARGS
wsnmp32_ordinal910 TEXTEQU <__imp_wsnmp32_ordinal910>
extern __imp_wsnmp32_ordinal911:PANYARGS
wsnmp32_ordinal911 TEXTEQU <__imp_wsnmp32_ordinal911>
extern __imp_wsnmp32_ordinal912:PANYARGS
wsnmp32_ordinal912 TEXTEQU <__imp_wsnmp32_ordinal912>
extern __imp_wsnmp32_ordinal913:PANYARGS
wsnmp32_ordinal913 TEXTEQU <__imp_wsnmp32_ordinal913>
extern __imp_wsnmp32_ordinal914:PANYARGS
wsnmp32_ordinal914 TEXTEQU <__imp_wsnmp32_ordinal914>
extern __imp_wsnmp32_ordinal915:PANYARGS
wsnmp32_ordinal915 TEXTEQU <__imp_wsnmp32_ordinal915>
extern __imp_wsnmp32_ordinal916:PANYARGS
wsnmp32_ordinal916 TEXTEQU <__imp_wsnmp32_ordinal916>
extern __imp_wsnmp32_ordinal917:PANYARGS
wsnmp32_ordinal917 TEXTEQU <__imp_wsnmp32_ordinal917>
extern __imp_wsnmp32_ordinal918:PANYARGS
wsnmp32_ordinal918 TEXTEQU <__imp_wsnmp32_ordinal918>
extern __imp_wsnmp32_ordinal919:PANYARGS
wsnmp32_ordinal919 TEXTEQU <__imp_wsnmp32_ordinal919>
extern __imp_wsnmp32_ordinal920:PANYARGS
wsnmp32_ordinal920 TEXTEQU <__imp_wsnmp32_ordinal920>
extern __imp_wsnmp32_ordinal921:PANYARGS
wsnmp32_ordinal921 TEXTEQU <__imp_wsnmp32_ordinal921>
extern __imp_wsnmp32_ordinal922:PANYARGS
wsnmp32_ordinal922 TEXTEQU <__imp_wsnmp32_ordinal922>
extern __imp_wsnmp32_ordinal923:PANYARGS
wsnmp32_ordinal923 TEXTEQU <__imp_wsnmp32_ordinal923>
extern __imp_wsnmp32_ordinal924:PANYARGS
wsnmp32_ordinal924 TEXTEQU <__imp_wsnmp32_ordinal924>
extern __imp_wsnmp32_ordinal925:PANYARGS
wsnmp32_ordinal925 TEXTEQU <__imp_wsnmp32_ordinal925>
extern __imp_wsnmp32_ordinal926:PANYARGS
wsnmp32_ordinal926 TEXTEQU <__imp_wsnmp32_ordinal926>
extern __imp_wsnmp32_ordinal927:PANYARGS
wsnmp32_ordinal927 TEXTEQU <__imp_wsnmp32_ordinal927>
extern __imp_wsnmp32_ordinal928:PANYARGS
wsnmp32_ordinal928 TEXTEQU <__imp_wsnmp32_ordinal928>
extern __imp_wsnmp32_ordinal929:PANYARGS
wsnmp32_ordinal929 TEXTEQU <__imp_wsnmp32_ordinal929>
extern __imp_wsnmp32_ordinal930:PANYARGS
wsnmp32_ordinal930 TEXTEQU <__imp_wsnmp32_ordinal930>
extern __imp_wsnmp32_ordinal931:PANYARGS
wsnmp32_ordinal931 TEXTEQU <__imp_wsnmp32_ordinal931>
extern __imp_wsnmp32_ordinal932:PANYARGS
wsnmp32_ordinal932 TEXTEQU <__imp_wsnmp32_ordinal932>
extern __imp_wsnmp32_ordinal933:PANYARGS
wsnmp32_ordinal933 TEXTEQU <__imp_wsnmp32_ordinal933>
extern __imp_wsnmp32_ordinal934:PANYARGS
wsnmp32_ordinal934 TEXTEQU <__imp_wsnmp32_ordinal934>
extern __imp_wsnmp32_ordinal935:PANYARGS
wsnmp32_ordinal935 TEXTEQU <__imp_wsnmp32_ordinal935>
extern __imp_wsnmp32_ordinal936:PANYARGS
wsnmp32_ordinal936 TEXTEQU <__imp_wsnmp32_ordinal936>
extern __imp_wsnmp32_ordinal937:PANYARGS
wsnmp32_ordinal937 TEXTEQU <__imp_wsnmp32_ordinal937>
extern __imp_wsnmp32_ordinal938:PANYARGS
wsnmp32_ordinal938 TEXTEQU <__imp_wsnmp32_ordinal938>
extern __imp_wsnmp32_ordinal939:PANYARGS
wsnmp32_ordinal939 TEXTEQU <__imp_wsnmp32_ordinal939>
extern __imp_wsnmp32_ordinal940:PANYARGS
wsnmp32_ordinal940 TEXTEQU <__imp_wsnmp32_ordinal940>
extern __imp_wsnmp32_ordinal941:PANYARGS
wsnmp32_ordinal941 TEXTEQU <__imp_wsnmp32_ordinal941>
extern __imp_wsnmp32_ordinal942:PANYARGS
wsnmp32_ordinal942 TEXTEQU <__imp_wsnmp32_ordinal942>
extern __imp_wsnmp32_ordinal943:PANYARGS
wsnmp32_ordinal943 TEXTEQU <__imp_wsnmp32_ordinal943>
extern __imp_wsnmp32_ordinal944:PANYARGS
wsnmp32_ordinal944 TEXTEQU <__imp_wsnmp32_ordinal944>
extern __imp_wsnmp32_ordinal945:PANYARGS
wsnmp32_ordinal945 TEXTEQU <__imp_wsnmp32_ordinal945>
extern __imp_wsnmp32_ordinal946:PANYARGS
wsnmp32_ordinal946 TEXTEQU <__imp_wsnmp32_ordinal946>
extern __imp_wsnmp32_ordinal947:PANYARGS
wsnmp32_ordinal947 TEXTEQU <__imp_wsnmp32_ordinal947>
extern __imp_wsnmp32_ordinal948:PANYARGS
wsnmp32_ordinal948 TEXTEQU <__imp_wsnmp32_ordinal948>
extern __imp_wsnmp32_ordinal949:PANYARGS
wsnmp32_ordinal949 TEXTEQU <__imp_wsnmp32_ordinal949>
extern __imp_wsnmp32_ordinal950:PANYARGS
wsnmp32_ordinal950 TEXTEQU <__imp_wsnmp32_ordinal950>
extern __imp_wsnmp32_ordinal951:PANYARGS
wsnmp32_ordinal951 TEXTEQU <__imp_wsnmp32_ordinal951>
extern __imp_wsnmp32_ordinal952:PANYARGS
wsnmp32_ordinal952 TEXTEQU <__imp_wsnmp32_ordinal952>
extern __imp_wsnmp32_ordinal953:PANYARGS
wsnmp32_ordinal953 TEXTEQU <__imp_wsnmp32_ordinal953>
extern __imp_wsnmp32_ordinal954:PANYARGS
wsnmp32_ordinal954 TEXTEQU <__imp_wsnmp32_ordinal954>
extern __imp_wsnmp32_ordinal955:PANYARGS
wsnmp32_ordinal955 TEXTEQU <__imp_wsnmp32_ordinal955>
extern __imp_wsnmp32_ordinal956:PANYARGS
wsnmp32_ordinal956 TEXTEQU <__imp_wsnmp32_ordinal956>
extern __imp_wsnmp32_ordinal957:PANYARGS
wsnmp32_ordinal957 TEXTEQU <__imp_wsnmp32_ordinal957>
extern __imp_wsnmp32_ordinal958:PANYARGS
wsnmp32_ordinal958 TEXTEQU <__imp_wsnmp32_ordinal958>
extern __imp_wsnmp32_ordinal959:PANYARGS
wsnmp32_ordinal959 TEXTEQU <__imp_wsnmp32_ordinal959>
extern __imp_wsnmp32_ordinal960:PANYARGS
wsnmp32_ordinal960 TEXTEQU <__imp_wsnmp32_ordinal960>
extern __imp_wsnmp32_ordinal961:PANYARGS
wsnmp32_ordinal961 TEXTEQU <__imp_wsnmp32_ordinal961>
extern __imp_wsnmp32_ordinal962:PANYARGS
wsnmp32_ordinal962 TEXTEQU <__imp_wsnmp32_ordinal962>
extern __imp_wsnmp32_ordinal963:PANYARGS
wsnmp32_ordinal963 TEXTEQU <__imp_wsnmp32_ordinal963>
extern __imp_wsnmp32_ordinal964:PANYARGS
wsnmp32_ordinal964 TEXTEQU <__imp_wsnmp32_ordinal964>
extern __imp_wsnmp32_ordinal965:PANYARGS
wsnmp32_ordinal965 TEXTEQU <__imp_wsnmp32_ordinal965>
extern __imp_wsnmp32_ordinal966:PANYARGS
wsnmp32_ordinal966 TEXTEQU <__imp_wsnmp32_ordinal966>
extern __imp_wsnmp32_ordinal967:PANYARGS
wsnmp32_ordinal967 TEXTEQU <__imp_wsnmp32_ordinal967>
extern __imp_wsnmp32_ordinal968:PANYARGS
wsnmp32_ordinal968 TEXTEQU <__imp_wsnmp32_ordinal968>
extern __imp_wsnmp32_ordinal969:PANYARGS
wsnmp32_ordinal969 TEXTEQU <__imp_wsnmp32_ordinal969>
extern __imp_wsnmp32_ordinal970:PANYARGS
wsnmp32_ordinal970 TEXTEQU <__imp_wsnmp32_ordinal970>
extern __imp_wsnmp32_ordinal971:PANYARGS
wsnmp32_ordinal971 TEXTEQU <__imp_wsnmp32_ordinal971>
extern __imp_wsnmp32_ordinal972:PANYARGS
wsnmp32_ordinal972 TEXTEQU <__imp_wsnmp32_ordinal972>
extern __imp_wsnmp32_ordinal973:PANYARGS
wsnmp32_ordinal973 TEXTEQU <__imp_wsnmp32_ordinal973>
extern __imp_wsnmp32_ordinal974:PANYARGS
wsnmp32_ordinal974 TEXTEQU <__imp_wsnmp32_ordinal974>
extern __imp_wsnmp32_ordinal975:PANYARGS
wsnmp32_ordinal975 TEXTEQU <__imp_wsnmp32_ordinal975>
extern __imp_wsnmp32_ordinal976:PANYARGS
wsnmp32_ordinal976 TEXTEQU <__imp_wsnmp32_ordinal976>
extern __imp_wsnmp32_ordinal977:PANYARGS
wsnmp32_ordinal977 TEXTEQU <__imp_wsnmp32_ordinal977>
extern __imp_wsnmp32_ordinal978:PANYARGS
wsnmp32_ordinal978 TEXTEQU <__imp_wsnmp32_ordinal978>
extern __imp_wsnmp32_ordinal979:PANYARGS
wsnmp32_ordinal979 TEXTEQU <__imp_wsnmp32_ordinal979>
extern __imp_wsnmp32_ordinal980:PANYARGS
wsnmp32_ordinal980 TEXTEQU <__imp_wsnmp32_ordinal980>
extern __imp_wsnmp32_ordinal981:PANYARGS
wsnmp32_ordinal981 TEXTEQU <__imp_wsnmp32_ordinal981>
extern __imp_wsnmp32_ordinal982:PANYARGS
wsnmp32_ordinal982 TEXTEQU <__imp_wsnmp32_ordinal982>
extern __imp_wsnmp32_ordinal983:PANYARGS
wsnmp32_ordinal983 TEXTEQU <__imp_wsnmp32_ordinal983>
extern __imp_wsnmp32_ordinal984:PANYARGS
wsnmp32_ordinal984 TEXTEQU <__imp_wsnmp32_ordinal984>
extern __imp_wsnmp32_ordinal985:PANYARGS
wsnmp32_ordinal985 TEXTEQU <__imp_wsnmp32_ordinal985>
extern __imp_wsnmp32_ordinal986:PANYARGS
wsnmp32_ordinal986 TEXTEQU <__imp_wsnmp32_ordinal986>
extern __imp_wsnmp32_ordinal987:PANYARGS
wsnmp32_ordinal987 TEXTEQU <__imp_wsnmp32_ordinal987>
extern __imp_wsnmp32_ordinal988:PANYARGS
wsnmp32_ordinal988 TEXTEQU <__imp_wsnmp32_ordinal988>
extern __imp_wsnmp32_ordinal989:PANYARGS
wsnmp32_ordinal989 TEXTEQU <__imp_wsnmp32_ordinal989>
extern __imp_wsnmp32_ordinal990:PANYARGS
wsnmp32_ordinal990 TEXTEQU <__imp_wsnmp32_ordinal990>
extern __imp_wsnmp32_ordinal991:PANYARGS
wsnmp32_ordinal991 TEXTEQU <__imp_wsnmp32_ordinal991>
extern __imp_wsnmp32_ordinal992:PANYARGS
wsnmp32_ordinal992 TEXTEQU <__imp_wsnmp32_ordinal992>
extern __imp_wsnmp32_ordinal993:PANYARGS
wsnmp32_ordinal993 TEXTEQU <__imp_wsnmp32_ordinal993>
extern __imp_wsnmp32_ordinal994:PANYARGS
wsnmp32_ordinal994 TEXTEQU <__imp_wsnmp32_ordinal994>
extern __imp_wsnmp32_ordinal995:PANYARGS
wsnmp32_ordinal995 TEXTEQU <__imp_wsnmp32_ordinal995>
extern __imp_wsnmp32_ordinal996:PANYARGS
wsnmp32_ordinal996 TEXTEQU <__imp_wsnmp32_ordinal996>
extern __imp_wsnmp32_ordinal997:PANYARGS
wsnmp32_ordinal997 TEXTEQU <__imp_wsnmp32_ordinal997>
extern __imp_wsnmp32_ordinal998:PANYARGS
wsnmp32_ordinal998 TEXTEQU <__imp_wsnmp32_ordinal998>
extern __imp_SnmpGetLastError:PANYARGS
SnmpGetLastError TEXTEQU <__imp_SnmpGetLastError>
