extern __imp_accept:PANYARGS
accept TEXTEQU <__imp_accept>
extern __imp_bind:PANYARGS
bind TEXTEQU <__imp_bind>
extern __imp_closesocket:PANYARGS
closesocket TEXTEQU <__imp_closesocket>
extern __imp_connect:PANYARGS
connect TEXTEQU <__imp_connect>
extern __imp_getpeername:PANYARGS
getpeername TEXTEQU <__imp_getpeername>
extern __imp_getsockname:PANYARGS
getsockname TEXTEQU <__imp_getsockname>
extern __imp_getsockopt:PANYARGS
getsockopt TEXTEQU <__imp_getsockopt>
extern __imp_htonl:PANYARGS
htonl TEXTEQU <__imp_htonl>
extern __imp_htons:PANYARGS
htons TEXTEQU <__imp_htons>
extern __imp_inet_addr:PANYARGS
inet_addr TEXTEQU <__imp_inet_addr>
extern __imp_inet_ntoa:PANYARGS
inet_ntoa TEXTEQU <__imp_inet_ntoa>
extern __imp_ioctlsocket:PANYARGS
ioctlsocket TEXTEQU <__imp_ioctlsocket>
extern __imp_listen:PANYARGS
listen TEXTEQU <__imp_listen>
extern __imp_ntohl:PANYARGS
ntohl TEXTEQU <__imp_ntohl>
extern __imp_ntohs:PANYARGS
ntohs TEXTEQU <__imp_ntohs>
extern __imp_recv:PANYARGS
recv TEXTEQU <__imp_recv>
extern __imp_recvfrom:PANYARGS
recvfrom TEXTEQU <__imp_recvfrom>
extern __imp_select:PANYARGS
select TEXTEQU <__imp_select>
extern __imp_send:PANYARGS
send TEXTEQU <__imp_send>
extern __imp_sendto:PANYARGS
sendto TEXTEQU <__imp_sendto>
extern __imp_setsockopt:PANYARGS
setsockopt TEXTEQU <__imp_setsockopt>
extern __imp_shutdown:PANYARGS
shutdown TEXTEQU <__imp_shutdown>
extern __imp_socket:PANYARGS
socket TEXTEQU <__imp_socket>
extern __imp_MigrateWinsockConfiguration:PANYARGS
MigrateWinsockConfiguration TEXTEQU <__imp_MigrateWinsockConfiguration>
extern __imp_wsock32_ordinal25:PANYARGS
wsock32_ordinal25 TEXTEQU <__imp_wsock32_ordinal25>
extern __imp_wsock32_ordinal26:PANYARGS
wsock32_ordinal26 TEXTEQU <__imp_wsock32_ordinal26>
extern __imp_wsock32_ordinal27:PANYARGS
wsock32_ordinal27 TEXTEQU <__imp_wsock32_ordinal27>
extern __imp_wsock32_ordinal28:PANYARGS
wsock32_ordinal28 TEXTEQU <__imp_wsock32_ordinal28>
extern __imp_wsock32_ordinal29:PANYARGS
wsock32_ordinal29 TEXTEQU <__imp_wsock32_ordinal29>
extern __imp_wsock32_ordinal30:PANYARGS
wsock32_ordinal30 TEXTEQU <__imp_wsock32_ordinal30>
extern __imp_wsock32_ordinal31:PANYARGS
wsock32_ordinal31 TEXTEQU <__imp_wsock32_ordinal31>
extern __imp_wsock32_ordinal32:PANYARGS
wsock32_ordinal32 TEXTEQU <__imp_wsock32_ordinal32>
extern __imp_wsock32_ordinal33:PANYARGS
wsock32_ordinal33 TEXTEQU <__imp_wsock32_ordinal33>
extern __imp_wsock32_ordinal34:PANYARGS
wsock32_ordinal34 TEXTEQU <__imp_wsock32_ordinal34>
extern __imp_wsock32_ordinal35:PANYARGS
wsock32_ordinal35 TEXTEQU <__imp_wsock32_ordinal35>
extern __imp_wsock32_ordinal36:PANYARGS
wsock32_ordinal36 TEXTEQU <__imp_wsock32_ordinal36>
extern __imp_wsock32_ordinal37:PANYARGS
wsock32_ordinal37 TEXTEQU <__imp_wsock32_ordinal37>
extern __imp_wsock32_ordinal38:PANYARGS
wsock32_ordinal38 TEXTEQU <__imp_wsock32_ordinal38>
extern __imp_wsock32_ordinal39:PANYARGS
wsock32_ordinal39 TEXTEQU <__imp_wsock32_ordinal39>
extern __imp_wsock32_ordinal40:PANYARGS
wsock32_ordinal40 TEXTEQU <__imp_wsock32_ordinal40>
extern __imp_wsock32_ordinal41:PANYARGS
wsock32_ordinal41 TEXTEQU <__imp_wsock32_ordinal41>
extern __imp_wsock32_ordinal42:PANYARGS
wsock32_ordinal42 TEXTEQU <__imp_wsock32_ordinal42>
extern __imp_wsock32_ordinal43:PANYARGS
wsock32_ordinal43 TEXTEQU <__imp_wsock32_ordinal43>
extern __imp_wsock32_ordinal44:PANYARGS
wsock32_ordinal44 TEXTEQU <__imp_wsock32_ordinal44>
extern __imp_wsock32_ordinal45:PANYARGS
wsock32_ordinal45 TEXTEQU <__imp_wsock32_ordinal45>
extern __imp_wsock32_ordinal46:PANYARGS
wsock32_ordinal46 TEXTEQU <__imp_wsock32_ordinal46>
extern __imp_wsock32_ordinal47:PANYARGS
wsock32_ordinal47 TEXTEQU <__imp_wsock32_ordinal47>
extern __imp_wsock32_ordinal48:PANYARGS
wsock32_ordinal48 TEXTEQU <__imp_wsock32_ordinal48>
extern __imp_wsock32_ordinal49:PANYARGS
wsock32_ordinal49 TEXTEQU <__imp_wsock32_ordinal49>
extern __imp_wsock32_ordinal50:PANYARGS
wsock32_ordinal50 TEXTEQU <__imp_wsock32_ordinal50>
extern __imp_gethostbyaddr:PANYARGS
gethostbyaddr TEXTEQU <__imp_gethostbyaddr>
extern __imp_gethostbyname:PANYARGS
gethostbyname TEXTEQU <__imp_gethostbyname>
extern __imp_getprotobyname:PANYARGS
getprotobyname TEXTEQU <__imp_getprotobyname>
extern __imp_getprotobynumber:PANYARGS
getprotobynumber TEXTEQU <__imp_getprotobynumber>
extern __imp_getservbyname:PANYARGS
getservbyname TEXTEQU <__imp_getservbyname>
extern __imp_getservbyport:PANYARGS
getservbyport TEXTEQU <__imp_getservbyport>
extern __imp_gethostname:PANYARGS
gethostname TEXTEQU <__imp_gethostname>
extern __imp_wsock32_ordinal58:PANYARGS
wsock32_ordinal58 TEXTEQU <__imp_wsock32_ordinal58>
extern __imp_wsock32_ordinal59:PANYARGS
wsock32_ordinal59 TEXTEQU <__imp_wsock32_ordinal59>
extern __imp_wsock32_ordinal60:PANYARGS
wsock32_ordinal60 TEXTEQU <__imp_wsock32_ordinal60>
extern __imp_wsock32_ordinal61:PANYARGS
wsock32_ordinal61 TEXTEQU <__imp_wsock32_ordinal61>
extern __imp_wsock32_ordinal62:PANYARGS
wsock32_ordinal62 TEXTEQU <__imp_wsock32_ordinal62>
extern __imp_wsock32_ordinal63:PANYARGS
wsock32_ordinal63 TEXTEQU <__imp_wsock32_ordinal63>
extern __imp_wsock32_ordinal64:PANYARGS
wsock32_ordinal64 TEXTEQU <__imp_wsock32_ordinal64>
extern __imp_wsock32_ordinal65:PANYARGS
wsock32_ordinal65 TEXTEQU <__imp_wsock32_ordinal65>
extern __imp_wsock32_ordinal66:PANYARGS
wsock32_ordinal66 TEXTEQU <__imp_wsock32_ordinal66>
extern __imp_wsock32_ordinal67:PANYARGS
wsock32_ordinal67 TEXTEQU <__imp_wsock32_ordinal67>
extern __imp_wsock32_ordinal68:PANYARGS
wsock32_ordinal68 TEXTEQU <__imp_wsock32_ordinal68>
extern __imp_wsock32_ordinal69:PANYARGS
wsock32_ordinal69 TEXTEQU <__imp_wsock32_ordinal69>
extern __imp_wsock32_ordinal70:PANYARGS
wsock32_ordinal70 TEXTEQU <__imp_wsock32_ordinal70>
extern __imp_wsock32_ordinal71:PANYARGS
wsock32_ordinal71 TEXTEQU <__imp_wsock32_ordinal71>
extern __imp_wsock32_ordinal72:PANYARGS
wsock32_ordinal72 TEXTEQU <__imp_wsock32_ordinal72>
extern __imp_wsock32_ordinal73:PANYARGS
wsock32_ordinal73 TEXTEQU <__imp_wsock32_ordinal73>
extern __imp_wsock32_ordinal74:PANYARGS
wsock32_ordinal74 TEXTEQU <__imp_wsock32_ordinal74>
extern __imp_wsock32_ordinal75:PANYARGS
wsock32_ordinal75 TEXTEQU <__imp_wsock32_ordinal75>
extern __imp_wsock32_ordinal76:PANYARGS
wsock32_ordinal76 TEXTEQU <__imp_wsock32_ordinal76>
extern __imp_wsock32_ordinal77:PANYARGS
wsock32_ordinal77 TEXTEQU <__imp_wsock32_ordinal77>
extern __imp_wsock32_ordinal78:PANYARGS
wsock32_ordinal78 TEXTEQU <__imp_wsock32_ordinal78>
extern __imp_wsock32_ordinal79:PANYARGS
wsock32_ordinal79 TEXTEQU <__imp_wsock32_ordinal79>
extern __imp_wsock32_ordinal80:PANYARGS
wsock32_ordinal80 TEXTEQU <__imp_wsock32_ordinal80>
extern __imp_wsock32_ordinal81:PANYARGS
wsock32_ordinal81 TEXTEQU <__imp_wsock32_ordinal81>
extern __imp_wsock32_ordinal82:PANYARGS
wsock32_ordinal82 TEXTEQU <__imp_wsock32_ordinal82>
extern __imp_wsock32_ordinal83:PANYARGS
wsock32_ordinal83 TEXTEQU <__imp_wsock32_ordinal83>
extern __imp_wsock32_ordinal84:PANYARGS
wsock32_ordinal84 TEXTEQU <__imp_wsock32_ordinal84>
extern __imp_wsock32_ordinal85:PANYARGS
wsock32_ordinal85 TEXTEQU <__imp_wsock32_ordinal85>
extern __imp_wsock32_ordinal86:PANYARGS
wsock32_ordinal86 TEXTEQU <__imp_wsock32_ordinal86>
extern __imp_wsock32_ordinal87:PANYARGS
wsock32_ordinal87 TEXTEQU <__imp_wsock32_ordinal87>
extern __imp_wsock32_ordinal88:PANYARGS
wsock32_ordinal88 TEXTEQU <__imp_wsock32_ordinal88>
extern __imp_wsock32_ordinal89:PANYARGS
wsock32_ordinal89 TEXTEQU <__imp_wsock32_ordinal89>
extern __imp_wsock32_ordinal90:PANYARGS
wsock32_ordinal90 TEXTEQU <__imp_wsock32_ordinal90>
extern __imp_wsock32_ordinal91:PANYARGS
wsock32_ordinal91 TEXTEQU <__imp_wsock32_ordinal91>
extern __imp_wsock32_ordinal92:PANYARGS
wsock32_ordinal92 TEXTEQU <__imp_wsock32_ordinal92>
extern __imp_wsock32_ordinal93:PANYARGS
wsock32_ordinal93 TEXTEQU <__imp_wsock32_ordinal93>
extern __imp_wsock32_ordinal94:PANYARGS
wsock32_ordinal94 TEXTEQU <__imp_wsock32_ordinal94>
extern __imp_wsock32_ordinal95:PANYARGS
wsock32_ordinal95 TEXTEQU <__imp_wsock32_ordinal95>
extern __imp_wsock32_ordinal96:PANYARGS
wsock32_ordinal96 TEXTEQU <__imp_wsock32_ordinal96>
extern __imp_wsock32_ordinal97:PANYARGS
wsock32_ordinal97 TEXTEQU <__imp_wsock32_ordinal97>
extern __imp_wsock32_ordinal98:PANYARGS
wsock32_ordinal98 TEXTEQU <__imp_wsock32_ordinal98>
extern __imp_wsock32_ordinal99:PANYARGS
wsock32_ordinal99 TEXTEQU <__imp_wsock32_ordinal99>
extern __imp_wsock32_ordinal100:PANYARGS
wsock32_ordinal100 TEXTEQU <__imp_wsock32_ordinal100>
extern __imp_WSAAsyncSelect:PANYARGS
WSAAsyncSelect TEXTEQU <__imp_WSAAsyncSelect>
extern __imp_WSAAsyncGetHostByAddr:PANYARGS
WSAAsyncGetHostByAddr TEXTEQU <__imp_WSAAsyncGetHostByAddr>
extern __imp_WSAAsyncGetHostByName:PANYARGS
WSAAsyncGetHostByName TEXTEQU <__imp_WSAAsyncGetHostByName>
extern __imp_WSAAsyncGetProtoByNumber:PANYARGS
WSAAsyncGetProtoByNumber TEXTEQU <__imp_WSAAsyncGetProtoByNumber>
extern __imp_WSAAsyncGetProtoByName:PANYARGS
WSAAsyncGetProtoByName TEXTEQU <__imp_WSAAsyncGetProtoByName>
extern __imp_WSAAsyncGetServByPort:PANYARGS
WSAAsyncGetServByPort TEXTEQU <__imp_WSAAsyncGetServByPort>
extern __imp_WSAAsyncGetServByName:PANYARGS
WSAAsyncGetServByName TEXTEQU <__imp_WSAAsyncGetServByName>
extern __imp_WSACancelAsyncRequest:PANYARGS
WSACancelAsyncRequest TEXTEQU <__imp_WSACancelAsyncRequest>
extern __imp_WSASetBlockingHook:PANYARGS
WSASetBlockingHook TEXTEQU <__imp_WSASetBlockingHook>
extern __imp_WSAUnhookBlockingHook:PANYARGS
WSAUnhookBlockingHook TEXTEQU <__imp_WSAUnhookBlockingHook>
extern __imp_WSAGetLastError:PANYARGS
WSAGetLastError TEXTEQU <__imp_WSAGetLastError>
extern __imp_WSASetLastError:PANYARGS
WSASetLastError TEXTEQU <__imp_WSASetLastError>
extern __imp_WSACancelBlockingCall:PANYARGS
WSACancelBlockingCall TEXTEQU <__imp_WSACancelBlockingCall>
extern __imp_WSAIsBlocking:PANYARGS
WSAIsBlocking TEXTEQU <__imp_WSAIsBlocking>
extern __imp_WSAStartup:PANYARGS
WSAStartup TEXTEQU <__imp_WSAStartup>
extern __imp_WSACleanup:PANYARGS
WSACleanup TEXTEQU <__imp_WSACleanup>
extern __imp_wsock32_ordinal117:PANYARGS
wsock32_ordinal117 TEXTEQU <__imp_wsock32_ordinal117>
extern __imp_wsock32_ordinal118:PANYARGS
wsock32_ordinal118 TEXTEQU <__imp_wsock32_ordinal118>
extern __imp_wsock32_ordinal119:PANYARGS
wsock32_ordinal119 TEXTEQU <__imp_wsock32_ordinal119>
extern __imp_wsock32_ordinal120:PANYARGS
wsock32_ordinal120 TEXTEQU <__imp_wsock32_ordinal120>
extern __imp_wsock32_ordinal121:PANYARGS
wsock32_ordinal121 TEXTEQU <__imp_wsock32_ordinal121>
extern __imp_wsock32_ordinal122:PANYARGS
wsock32_ordinal122 TEXTEQU <__imp_wsock32_ordinal122>
extern __imp_wsock32_ordinal123:PANYARGS
wsock32_ordinal123 TEXTEQU <__imp_wsock32_ordinal123>
extern __imp_wsock32_ordinal124:PANYARGS
wsock32_ordinal124 TEXTEQU <__imp_wsock32_ordinal124>
extern __imp_wsock32_ordinal125:PANYARGS
wsock32_ordinal125 TEXTEQU <__imp_wsock32_ordinal125>
extern __imp_wsock32_ordinal126:PANYARGS
wsock32_ordinal126 TEXTEQU <__imp_wsock32_ordinal126>
extern __imp_wsock32_ordinal127:PANYARGS
wsock32_ordinal127 TEXTEQU <__imp_wsock32_ordinal127>
extern __imp_wsock32_ordinal128:PANYARGS
wsock32_ordinal128 TEXTEQU <__imp_wsock32_ordinal128>
extern __imp_wsock32_ordinal129:PANYARGS
wsock32_ordinal129 TEXTEQU <__imp_wsock32_ordinal129>
extern __imp_wsock32_ordinal130:PANYARGS
wsock32_ordinal130 TEXTEQU <__imp_wsock32_ordinal130>
extern __imp_wsock32_ordinal131:PANYARGS
wsock32_ordinal131 TEXTEQU <__imp_wsock32_ordinal131>
extern __imp_wsock32_ordinal132:PANYARGS
wsock32_ordinal132 TEXTEQU <__imp_wsock32_ordinal132>
extern __imp_wsock32_ordinal133:PANYARGS
wsock32_ordinal133 TEXTEQU <__imp_wsock32_ordinal133>
extern __imp_wsock32_ordinal134:PANYARGS
wsock32_ordinal134 TEXTEQU <__imp_wsock32_ordinal134>
extern __imp_wsock32_ordinal135:PANYARGS
wsock32_ordinal135 TEXTEQU <__imp_wsock32_ordinal135>
extern __imp_wsock32_ordinal136:PANYARGS
wsock32_ordinal136 TEXTEQU <__imp_wsock32_ordinal136>
extern __imp_wsock32_ordinal137:PANYARGS
wsock32_ordinal137 TEXTEQU <__imp_wsock32_ordinal137>
extern __imp_wsock32_ordinal138:PANYARGS
wsock32_ordinal138 TEXTEQU <__imp_wsock32_ordinal138>
extern __imp_wsock32_ordinal139:PANYARGS
wsock32_ordinal139 TEXTEQU <__imp_wsock32_ordinal139>
extern __imp_wsock32_ordinal140:PANYARGS
wsock32_ordinal140 TEXTEQU <__imp_wsock32_ordinal140>
extern __imp_wsock32_ordinal141:PANYARGS
wsock32_ordinal141 TEXTEQU <__imp_wsock32_ordinal141>
extern __imp_wsock32_ordinal142:PANYARGS
wsock32_ordinal142 TEXTEQU <__imp_wsock32_ordinal142>
extern __imp_wsock32_ordinal143:PANYARGS
wsock32_ordinal143 TEXTEQU <__imp_wsock32_ordinal143>
extern __imp_wsock32_ordinal144:PANYARGS
wsock32_ordinal144 TEXTEQU <__imp_wsock32_ordinal144>
extern __imp_wsock32_ordinal145:PANYARGS
wsock32_ordinal145 TEXTEQU <__imp_wsock32_ordinal145>
extern __imp_wsock32_ordinal146:PANYARGS
wsock32_ordinal146 TEXTEQU <__imp_wsock32_ordinal146>
extern __imp_wsock32_ordinal147:PANYARGS
wsock32_ordinal147 TEXTEQU <__imp_wsock32_ordinal147>
extern __imp_wsock32_ordinal148:PANYARGS
wsock32_ordinal148 TEXTEQU <__imp_wsock32_ordinal148>
extern __imp_wsock32_ordinal149:PANYARGS
wsock32_ordinal149 TEXTEQU <__imp_wsock32_ordinal149>
extern __imp_wsock32_ordinal150:PANYARGS
wsock32_ordinal150 TEXTEQU <__imp_wsock32_ordinal150>
extern __imp___WSAFDIsSet:PANYARGS
__WSAFDIsSet TEXTEQU <__imp___WSAFDIsSet>
extern __imp_wsock32_ordinal152:PANYARGS
wsock32_ordinal152 TEXTEQU <__imp_wsock32_ordinal152>
extern __imp_wsock32_ordinal153:PANYARGS
wsock32_ordinal153 TEXTEQU <__imp_wsock32_ordinal153>
extern __imp_wsock32_ordinal154:PANYARGS
wsock32_ordinal154 TEXTEQU <__imp_wsock32_ordinal154>
extern __imp_wsock32_ordinal155:PANYARGS
wsock32_ordinal155 TEXTEQU <__imp_wsock32_ordinal155>
extern __imp_wsock32_ordinal156:PANYARGS
wsock32_ordinal156 TEXTEQU <__imp_wsock32_ordinal156>
extern __imp_wsock32_ordinal157:PANYARGS
wsock32_ordinal157 TEXTEQU <__imp_wsock32_ordinal157>
extern __imp_wsock32_ordinal158:PANYARGS
wsock32_ordinal158 TEXTEQU <__imp_wsock32_ordinal158>
extern __imp_wsock32_ordinal159:PANYARGS
wsock32_ordinal159 TEXTEQU <__imp_wsock32_ordinal159>
extern __imp_wsock32_ordinal160:PANYARGS
wsock32_ordinal160 TEXTEQU <__imp_wsock32_ordinal160>
extern __imp_wsock32_ordinal161:PANYARGS
wsock32_ordinal161 TEXTEQU <__imp_wsock32_ordinal161>
extern __imp_wsock32_ordinal162:PANYARGS
wsock32_ordinal162 TEXTEQU <__imp_wsock32_ordinal162>
extern __imp_wsock32_ordinal163:PANYARGS
wsock32_ordinal163 TEXTEQU <__imp_wsock32_ordinal163>
extern __imp_wsock32_ordinal164:PANYARGS
wsock32_ordinal164 TEXTEQU <__imp_wsock32_ordinal164>
extern __imp_wsock32_ordinal165:PANYARGS
wsock32_ordinal165 TEXTEQU <__imp_wsock32_ordinal165>
extern __imp_wsock32_ordinal166:PANYARGS
wsock32_ordinal166 TEXTEQU <__imp_wsock32_ordinal166>
extern __imp_wsock32_ordinal167:PANYARGS
wsock32_ordinal167 TEXTEQU <__imp_wsock32_ordinal167>
extern __imp_wsock32_ordinal168:PANYARGS
wsock32_ordinal168 TEXTEQU <__imp_wsock32_ordinal168>
extern __imp_wsock32_ordinal169:PANYARGS
wsock32_ordinal169 TEXTEQU <__imp_wsock32_ordinal169>
extern __imp_wsock32_ordinal170:PANYARGS
wsock32_ordinal170 TEXTEQU <__imp_wsock32_ordinal170>
extern __imp_wsock32_ordinal171:PANYARGS
wsock32_ordinal171 TEXTEQU <__imp_wsock32_ordinal171>
extern __imp_wsock32_ordinal172:PANYARGS
wsock32_ordinal172 TEXTEQU <__imp_wsock32_ordinal172>
extern __imp_wsock32_ordinal173:PANYARGS
wsock32_ordinal173 TEXTEQU <__imp_wsock32_ordinal173>
extern __imp_wsock32_ordinal174:PANYARGS
wsock32_ordinal174 TEXTEQU <__imp_wsock32_ordinal174>
extern __imp_wsock32_ordinal175:PANYARGS
wsock32_ordinal175 TEXTEQU <__imp_wsock32_ordinal175>
extern __imp_wsock32_ordinal176:PANYARGS
wsock32_ordinal176 TEXTEQU <__imp_wsock32_ordinal176>
extern __imp_wsock32_ordinal177:PANYARGS
wsock32_ordinal177 TEXTEQU <__imp_wsock32_ordinal177>
extern __imp_wsock32_ordinal178:PANYARGS
wsock32_ordinal178 TEXTEQU <__imp_wsock32_ordinal178>
extern __imp_wsock32_ordinal179:PANYARGS
wsock32_ordinal179 TEXTEQU <__imp_wsock32_ordinal179>
extern __imp_wsock32_ordinal180:PANYARGS
wsock32_ordinal180 TEXTEQU <__imp_wsock32_ordinal180>
extern __imp_wsock32_ordinal181:PANYARGS
wsock32_ordinal181 TEXTEQU <__imp_wsock32_ordinal181>
extern __imp_wsock32_ordinal182:PANYARGS
wsock32_ordinal182 TEXTEQU <__imp_wsock32_ordinal182>
extern __imp_wsock32_ordinal183:PANYARGS
wsock32_ordinal183 TEXTEQU <__imp_wsock32_ordinal183>
extern __imp_wsock32_ordinal184:PANYARGS
wsock32_ordinal184 TEXTEQU <__imp_wsock32_ordinal184>
extern __imp_wsock32_ordinal185:PANYARGS
wsock32_ordinal185 TEXTEQU <__imp_wsock32_ordinal185>
extern __imp_wsock32_ordinal186:PANYARGS
wsock32_ordinal186 TEXTEQU <__imp_wsock32_ordinal186>
extern __imp_wsock32_ordinal187:PANYARGS
wsock32_ordinal187 TEXTEQU <__imp_wsock32_ordinal187>
extern __imp_wsock32_ordinal188:PANYARGS
wsock32_ordinal188 TEXTEQU <__imp_wsock32_ordinal188>
extern __imp_wsock32_ordinal189:PANYARGS
wsock32_ordinal189 TEXTEQU <__imp_wsock32_ordinal189>
extern __imp_wsock32_ordinal190:PANYARGS
wsock32_ordinal190 TEXTEQU <__imp_wsock32_ordinal190>
extern __imp_wsock32_ordinal191:PANYARGS
wsock32_ordinal191 TEXTEQU <__imp_wsock32_ordinal191>
extern __imp_wsock32_ordinal192:PANYARGS
wsock32_ordinal192 TEXTEQU <__imp_wsock32_ordinal192>
extern __imp_wsock32_ordinal193:PANYARGS
wsock32_ordinal193 TEXTEQU <__imp_wsock32_ordinal193>
extern __imp_wsock32_ordinal194:PANYARGS
wsock32_ordinal194 TEXTEQU <__imp_wsock32_ordinal194>
extern __imp_wsock32_ordinal195:PANYARGS
wsock32_ordinal195 TEXTEQU <__imp_wsock32_ordinal195>
extern __imp_wsock32_ordinal196:PANYARGS
wsock32_ordinal196 TEXTEQU <__imp_wsock32_ordinal196>
extern __imp_wsock32_ordinal197:PANYARGS
wsock32_ordinal197 TEXTEQU <__imp_wsock32_ordinal197>
extern __imp_wsock32_ordinal198:PANYARGS
wsock32_ordinal198 TEXTEQU <__imp_wsock32_ordinal198>
extern __imp_wsock32_ordinal199:PANYARGS
wsock32_ordinal199 TEXTEQU <__imp_wsock32_ordinal199>
extern __imp_wsock32_ordinal200:PANYARGS
wsock32_ordinal200 TEXTEQU <__imp_wsock32_ordinal200>
extern __imp_wsock32_ordinal201:PANYARGS
wsock32_ordinal201 TEXTEQU <__imp_wsock32_ordinal201>
extern __imp_wsock32_ordinal202:PANYARGS
wsock32_ordinal202 TEXTEQU <__imp_wsock32_ordinal202>
extern __imp_wsock32_ordinal203:PANYARGS
wsock32_ordinal203 TEXTEQU <__imp_wsock32_ordinal203>
extern __imp_wsock32_ordinal204:PANYARGS
wsock32_ordinal204 TEXTEQU <__imp_wsock32_ordinal204>
extern __imp_wsock32_ordinal205:PANYARGS
wsock32_ordinal205 TEXTEQU <__imp_wsock32_ordinal205>
extern __imp_wsock32_ordinal206:PANYARGS
wsock32_ordinal206 TEXTEQU <__imp_wsock32_ordinal206>
extern __imp_wsock32_ordinal207:PANYARGS
wsock32_ordinal207 TEXTEQU <__imp_wsock32_ordinal207>
extern __imp_wsock32_ordinal208:PANYARGS
wsock32_ordinal208 TEXTEQU <__imp_wsock32_ordinal208>
extern __imp_wsock32_ordinal209:PANYARGS
wsock32_ordinal209 TEXTEQU <__imp_wsock32_ordinal209>
extern __imp_wsock32_ordinal210:PANYARGS
wsock32_ordinal210 TEXTEQU <__imp_wsock32_ordinal210>
extern __imp_wsock32_ordinal211:PANYARGS
wsock32_ordinal211 TEXTEQU <__imp_wsock32_ordinal211>
extern __imp_wsock32_ordinal212:PANYARGS
wsock32_ordinal212 TEXTEQU <__imp_wsock32_ordinal212>
extern __imp_wsock32_ordinal213:PANYARGS
wsock32_ordinal213 TEXTEQU <__imp_wsock32_ordinal213>
extern __imp_wsock32_ordinal214:PANYARGS
wsock32_ordinal214 TEXTEQU <__imp_wsock32_ordinal214>
extern __imp_wsock32_ordinal215:PANYARGS
wsock32_ordinal215 TEXTEQU <__imp_wsock32_ordinal215>
extern __imp_wsock32_ordinal216:PANYARGS
wsock32_ordinal216 TEXTEQU <__imp_wsock32_ordinal216>
extern __imp_wsock32_ordinal217:PANYARGS
wsock32_ordinal217 TEXTEQU <__imp_wsock32_ordinal217>
extern __imp_wsock32_ordinal218:PANYARGS
wsock32_ordinal218 TEXTEQU <__imp_wsock32_ordinal218>
extern __imp_wsock32_ordinal219:PANYARGS
wsock32_ordinal219 TEXTEQU <__imp_wsock32_ordinal219>
extern __imp_wsock32_ordinal220:PANYARGS
wsock32_ordinal220 TEXTEQU <__imp_wsock32_ordinal220>
extern __imp_wsock32_ordinal221:PANYARGS
wsock32_ordinal221 TEXTEQU <__imp_wsock32_ordinal221>
extern __imp_wsock32_ordinal222:PANYARGS
wsock32_ordinal222 TEXTEQU <__imp_wsock32_ordinal222>
extern __imp_wsock32_ordinal223:PANYARGS
wsock32_ordinal223 TEXTEQU <__imp_wsock32_ordinal223>
extern __imp_wsock32_ordinal224:PANYARGS
wsock32_ordinal224 TEXTEQU <__imp_wsock32_ordinal224>
extern __imp_wsock32_ordinal225:PANYARGS
wsock32_ordinal225 TEXTEQU <__imp_wsock32_ordinal225>
extern __imp_wsock32_ordinal226:PANYARGS
wsock32_ordinal226 TEXTEQU <__imp_wsock32_ordinal226>
extern __imp_wsock32_ordinal227:PANYARGS
wsock32_ordinal227 TEXTEQU <__imp_wsock32_ordinal227>
extern __imp_wsock32_ordinal228:PANYARGS
wsock32_ordinal228 TEXTEQU <__imp_wsock32_ordinal228>
extern __imp_wsock32_ordinal229:PANYARGS
wsock32_ordinal229 TEXTEQU <__imp_wsock32_ordinal229>
extern __imp_wsock32_ordinal230:PANYARGS
wsock32_ordinal230 TEXTEQU <__imp_wsock32_ordinal230>
extern __imp_wsock32_ordinal231:PANYARGS
wsock32_ordinal231 TEXTEQU <__imp_wsock32_ordinal231>
extern __imp_wsock32_ordinal232:PANYARGS
wsock32_ordinal232 TEXTEQU <__imp_wsock32_ordinal232>
extern __imp_wsock32_ordinal233:PANYARGS
wsock32_ordinal233 TEXTEQU <__imp_wsock32_ordinal233>
extern __imp_wsock32_ordinal234:PANYARGS
wsock32_ordinal234 TEXTEQU <__imp_wsock32_ordinal234>
extern __imp_wsock32_ordinal235:PANYARGS
wsock32_ordinal235 TEXTEQU <__imp_wsock32_ordinal235>
extern __imp_wsock32_ordinal236:PANYARGS
wsock32_ordinal236 TEXTEQU <__imp_wsock32_ordinal236>
extern __imp_wsock32_ordinal237:PANYARGS
wsock32_ordinal237 TEXTEQU <__imp_wsock32_ordinal237>
extern __imp_wsock32_ordinal238:PANYARGS
wsock32_ordinal238 TEXTEQU <__imp_wsock32_ordinal238>
extern __imp_wsock32_ordinal239:PANYARGS
wsock32_ordinal239 TEXTEQU <__imp_wsock32_ordinal239>
extern __imp_wsock32_ordinal240:PANYARGS
wsock32_ordinal240 TEXTEQU <__imp_wsock32_ordinal240>
extern __imp_wsock32_ordinal241:PANYARGS
wsock32_ordinal241 TEXTEQU <__imp_wsock32_ordinal241>
extern __imp_wsock32_ordinal242:PANYARGS
wsock32_ordinal242 TEXTEQU <__imp_wsock32_ordinal242>
extern __imp_wsock32_ordinal243:PANYARGS
wsock32_ordinal243 TEXTEQU <__imp_wsock32_ordinal243>
extern __imp_wsock32_ordinal244:PANYARGS
wsock32_ordinal244 TEXTEQU <__imp_wsock32_ordinal244>
extern __imp_wsock32_ordinal245:PANYARGS
wsock32_ordinal245 TEXTEQU <__imp_wsock32_ordinal245>
extern __imp_wsock32_ordinal246:PANYARGS
wsock32_ordinal246 TEXTEQU <__imp_wsock32_ordinal246>
extern __imp_wsock32_ordinal247:PANYARGS
wsock32_ordinal247 TEXTEQU <__imp_wsock32_ordinal247>
extern __imp_wsock32_ordinal248:PANYARGS
wsock32_ordinal248 TEXTEQU <__imp_wsock32_ordinal248>
extern __imp_wsock32_ordinal249:PANYARGS
wsock32_ordinal249 TEXTEQU <__imp_wsock32_ordinal249>
extern __imp_wsock32_ordinal250:PANYARGS
wsock32_ordinal250 TEXTEQU <__imp_wsock32_ordinal250>
extern __imp_wsock32_ordinal251:PANYARGS
wsock32_ordinal251 TEXTEQU <__imp_wsock32_ordinal251>
extern __imp_wsock32_ordinal252:PANYARGS
wsock32_ordinal252 TEXTEQU <__imp_wsock32_ordinal252>
extern __imp_wsock32_ordinal253:PANYARGS
wsock32_ordinal253 TEXTEQU <__imp_wsock32_ordinal253>
extern __imp_wsock32_ordinal254:PANYARGS
wsock32_ordinal254 TEXTEQU <__imp_wsock32_ordinal254>
extern __imp_wsock32_ordinal255:PANYARGS
wsock32_ordinal255 TEXTEQU <__imp_wsock32_ordinal255>
extern __imp_wsock32_ordinal256:PANYARGS
wsock32_ordinal256 TEXTEQU <__imp_wsock32_ordinal256>
extern __imp_wsock32_ordinal257:PANYARGS
wsock32_ordinal257 TEXTEQU <__imp_wsock32_ordinal257>
extern __imp_wsock32_ordinal258:PANYARGS
wsock32_ordinal258 TEXTEQU <__imp_wsock32_ordinal258>
extern __imp_wsock32_ordinal259:PANYARGS
wsock32_ordinal259 TEXTEQU <__imp_wsock32_ordinal259>
extern __imp_wsock32_ordinal260:PANYARGS
wsock32_ordinal260 TEXTEQU <__imp_wsock32_ordinal260>
extern __imp_wsock32_ordinal261:PANYARGS
wsock32_ordinal261 TEXTEQU <__imp_wsock32_ordinal261>
extern __imp_wsock32_ordinal262:PANYARGS
wsock32_ordinal262 TEXTEQU <__imp_wsock32_ordinal262>
extern __imp_wsock32_ordinal263:PANYARGS
wsock32_ordinal263 TEXTEQU <__imp_wsock32_ordinal263>
extern __imp_wsock32_ordinal264:PANYARGS
wsock32_ordinal264 TEXTEQU <__imp_wsock32_ordinal264>
extern __imp_wsock32_ordinal265:PANYARGS
wsock32_ordinal265 TEXTEQU <__imp_wsock32_ordinal265>
extern __imp_wsock32_ordinal266:PANYARGS
wsock32_ordinal266 TEXTEQU <__imp_wsock32_ordinal266>
extern __imp_wsock32_ordinal267:PANYARGS
wsock32_ordinal267 TEXTEQU <__imp_wsock32_ordinal267>
extern __imp_wsock32_ordinal268:PANYARGS
wsock32_ordinal268 TEXTEQU <__imp_wsock32_ordinal268>
extern __imp_wsock32_ordinal269:PANYARGS
wsock32_ordinal269 TEXTEQU <__imp_wsock32_ordinal269>
extern __imp_wsock32_ordinal270:PANYARGS
wsock32_ordinal270 TEXTEQU <__imp_wsock32_ordinal270>
extern __imp_wsock32_ordinal271:PANYARGS
wsock32_ordinal271 TEXTEQU <__imp_wsock32_ordinal271>
extern __imp_wsock32_ordinal272:PANYARGS
wsock32_ordinal272 TEXTEQU <__imp_wsock32_ordinal272>
extern __imp_wsock32_ordinal273:PANYARGS
wsock32_ordinal273 TEXTEQU <__imp_wsock32_ordinal273>
extern __imp_wsock32_ordinal274:PANYARGS
wsock32_ordinal274 TEXTEQU <__imp_wsock32_ordinal274>
extern __imp_wsock32_ordinal275:PANYARGS
wsock32_ordinal275 TEXTEQU <__imp_wsock32_ordinal275>
extern __imp_wsock32_ordinal276:PANYARGS
wsock32_ordinal276 TEXTEQU <__imp_wsock32_ordinal276>
extern __imp_wsock32_ordinal277:PANYARGS
wsock32_ordinal277 TEXTEQU <__imp_wsock32_ordinal277>
extern __imp_wsock32_ordinal278:PANYARGS
wsock32_ordinal278 TEXTEQU <__imp_wsock32_ordinal278>
extern __imp_wsock32_ordinal279:PANYARGS
wsock32_ordinal279 TEXTEQU <__imp_wsock32_ordinal279>
extern __imp_wsock32_ordinal280:PANYARGS
wsock32_ordinal280 TEXTEQU <__imp_wsock32_ordinal280>
extern __imp_wsock32_ordinal281:PANYARGS
wsock32_ordinal281 TEXTEQU <__imp_wsock32_ordinal281>
extern __imp_wsock32_ordinal282:PANYARGS
wsock32_ordinal282 TEXTEQU <__imp_wsock32_ordinal282>
extern __imp_wsock32_ordinal283:PANYARGS
wsock32_ordinal283 TEXTEQU <__imp_wsock32_ordinal283>
extern __imp_wsock32_ordinal284:PANYARGS
wsock32_ordinal284 TEXTEQU <__imp_wsock32_ordinal284>
extern __imp_wsock32_ordinal285:PANYARGS
wsock32_ordinal285 TEXTEQU <__imp_wsock32_ordinal285>
extern __imp_wsock32_ordinal286:PANYARGS
wsock32_ordinal286 TEXTEQU <__imp_wsock32_ordinal286>
extern __imp_wsock32_ordinal287:PANYARGS
wsock32_ordinal287 TEXTEQU <__imp_wsock32_ordinal287>
extern __imp_wsock32_ordinal288:PANYARGS
wsock32_ordinal288 TEXTEQU <__imp_wsock32_ordinal288>
extern __imp_wsock32_ordinal289:PANYARGS
wsock32_ordinal289 TEXTEQU <__imp_wsock32_ordinal289>
extern __imp_wsock32_ordinal290:PANYARGS
wsock32_ordinal290 TEXTEQU <__imp_wsock32_ordinal290>
extern __imp_wsock32_ordinal291:PANYARGS
wsock32_ordinal291 TEXTEQU <__imp_wsock32_ordinal291>
extern __imp_wsock32_ordinal292:PANYARGS
wsock32_ordinal292 TEXTEQU <__imp_wsock32_ordinal292>
extern __imp_wsock32_ordinal293:PANYARGS
wsock32_ordinal293 TEXTEQU <__imp_wsock32_ordinal293>
extern __imp_wsock32_ordinal294:PANYARGS
wsock32_ordinal294 TEXTEQU <__imp_wsock32_ordinal294>
extern __imp_wsock32_ordinal295:PANYARGS
wsock32_ordinal295 TEXTEQU <__imp_wsock32_ordinal295>
extern __imp_wsock32_ordinal296:PANYARGS
wsock32_ordinal296 TEXTEQU <__imp_wsock32_ordinal296>
extern __imp_wsock32_ordinal297:PANYARGS
wsock32_ordinal297 TEXTEQU <__imp_wsock32_ordinal297>
extern __imp_wsock32_ordinal298:PANYARGS
wsock32_ordinal298 TEXTEQU <__imp_wsock32_ordinal298>
extern __imp_wsock32_ordinal299:PANYARGS
wsock32_ordinal299 TEXTEQU <__imp_wsock32_ordinal299>
extern __imp_wsock32_ordinal300:PANYARGS
wsock32_ordinal300 TEXTEQU <__imp_wsock32_ordinal300>
extern __imp_wsock32_ordinal301:PANYARGS
wsock32_ordinal301 TEXTEQU <__imp_wsock32_ordinal301>
extern __imp_wsock32_ordinal302:PANYARGS
wsock32_ordinal302 TEXTEQU <__imp_wsock32_ordinal302>
extern __imp_wsock32_ordinal303:PANYARGS
wsock32_ordinal303 TEXTEQU <__imp_wsock32_ordinal303>
extern __imp_wsock32_ordinal304:PANYARGS
wsock32_ordinal304 TEXTEQU <__imp_wsock32_ordinal304>
extern __imp_wsock32_ordinal305:PANYARGS
wsock32_ordinal305 TEXTEQU <__imp_wsock32_ordinal305>
extern __imp_wsock32_ordinal306:PANYARGS
wsock32_ordinal306 TEXTEQU <__imp_wsock32_ordinal306>
extern __imp_wsock32_ordinal307:PANYARGS
wsock32_ordinal307 TEXTEQU <__imp_wsock32_ordinal307>
extern __imp_wsock32_ordinal308:PANYARGS
wsock32_ordinal308 TEXTEQU <__imp_wsock32_ordinal308>
extern __imp_wsock32_ordinal309:PANYARGS
wsock32_ordinal309 TEXTEQU <__imp_wsock32_ordinal309>
extern __imp_wsock32_ordinal310:PANYARGS
wsock32_ordinal310 TEXTEQU <__imp_wsock32_ordinal310>
extern __imp_wsock32_ordinal311:PANYARGS
wsock32_ordinal311 TEXTEQU <__imp_wsock32_ordinal311>
extern __imp_wsock32_ordinal312:PANYARGS
wsock32_ordinal312 TEXTEQU <__imp_wsock32_ordinal312>
extern __imp_wsock32_ordinal313:PANYARGS
wsock32_ordinal313 TEXTEQU <__imp_wsock32_ordinal313>
extern __imp_wsock32_ordinal314:PANYARGS
wsock32_ordinal314 TEXTEQU <__imp_wsock32_ordinal314>
extern __imp_wsock32_ordinal315:PANYARGS
wsock32_ordinal315 TEXTEQU <__imp_wsock32_ordinal315>
extern __imp_wsock32_ordinal316:PANYARGS
wsock32_ordinal316 TEXTEQU <__imp_wsock32_ordinal316>
extern __imp_wsock32_ordinal317:PANYARGS
wsock32_ordinal317 TEXTEQU <__imp_wsock32_ordinal317>
extern __imp_wsock32_ordinal318:PANYARGS
wsock32_ordinal318 TEXTEQU <__imp_wsock32_ordinal318>
extern __imp_wsock32_ordinal319:PANYARGS
wsock32_ordinal319 TEXTEQU <__imp_wsock32_ordinal319>
extern __imp_wsock32_ordinal320:PANYARGS
wsock32_ordinal320 TEXTEQU <__imp_wsock32_ordinal320>
extern __imp_wsock32_ordinal321:PANYARGS
wsock32_ordinal321 TEXTEQU <__imp_wsock32_ordinal321>
extern __imp_wsock32_ordinal322:PANYARGS
wsock32_ordinal322 TEXTEQU <__imp_wsock32_ordinal322>
extern __imp_wsock32_ordinal323:PANYARGS
wsock32_ordinal323 TEXTEQU <__imp_wsock32_ordinal323>
extern __imp_wsock32_ordinal324:PANYARGS
wsock32_ordinal324 TEXTEQU <__imp_wsock32_ordinal324>
extern __imp_wsock32_ordinal325:PANYARGS
wsock32_ordinal325 TEXTEQU <__imp_wsock32_ordinal325>
extern __imp_wsock32_ordinal326:PANYARGS
wsock32_ordinal326 TEXTEQU <__imp_wsock32_ordinal326>
extern __imp_wsock32_ordinal327:PANYARGS
wsock32_ordinal327 TEXTEQU <__imp_wsock32_ordinal327>
extern __imp_wsock32_ordinal328:PANYARGS
wsock32_ordinal328 TEXTEQU <__imp_wsock32_ordinal328>
extern __imp_wsock32_ordinal329:PANYARGS
wsock32_ordinal329 TEXTEQU <__imp_wsock32_ordinal329>
extern __imp_wsock32_ordinal330:PANYARGS
wsock32_ordinal330 TEXTEQU <__imp_wsock32_ordinal330>
extern __imp_wsock32_ordinal331:PANYARGS
wsock32_ordinal331 TEXTEQU <__imp_wsock32_ordinal331>
extern __imp_wsock32_ordinal332:PANYARGS
wsock32_ordinal332 TEXTEQU <__imp_wsock32_ordinal332>
extern __imp_wsock32_ordinal333:PANYARGS
wsock32_ordinal333 TEXTEQU <__imp_wsock32_ordinal333>
extern __imp_wsock32_ordinal334:PANYARGS
wsock32_ordinal334 TEXTEQU <__imp_wsock32_ordinal334>
extern __imp_wsock32_ordinal335:PANYARGS
wsock32_ordinal335 TEXTEQU <__imp_wsock32_ordinal335>
extern __imp_wsock32_ordinal336:PANYARGS
wsock32_ordinal336 TEXTEQU <__imp_wsock32_ordinal336>
extern __imp_wsock32_ordinal337:PANYARGS
wsock32_ordinal337 TEXTEQU <__imp_wsock32_ordinal337>
extern __imp_wsock32_ordinal338:PANYARGS
wsock32_ordinal338 TEXTEQU <__imp_wsock32_ordinal338>
extern __imp_wsock32_ordinal339:PANYARGS
wsock32_ordinal339 TEXTEQU <__imp_wsock32_ordinal339>
extern __imp_wsock32_ordinal340:PANYARGS
wsock32_ordinal340 TEXTEQU <__imp_wsock32_ordinal340>
extern __imp_wsock32_ordinal341:PANYARGS
wsock32_ordinal341 TEXTEQU <__imp_wsock32_ordinal341>
extern __imp_wsock32_ordinal342:PANYARGS
wsock32_ordinal342 TEXTEQU <__imp_wsock32_ordinal342>
extern __imp_wsock32_ordinal343:PANYARGS
wsock32_ordinal343 TEXTEQU <__imp_wsock32_ordinal343>
extern __imp_wsock32_ordinal344:PANYARGS
wsock32_ordinal344 TEXTEQU <__imp_wsock32_ordinal344>
extern __imp_wsock32_ordinal345:PANYARGS
wsock32_ordinal345 TEXTEQU <__imp_wsock32_ordinal345>
extern __imp_wsock32_ordinal346:PANYARGS
wsock32_ordinal346 TEXTEQU <__imp_wsock32_ordinal346>
extern __imp_wsock32_ordinal347:PANYARGS
wsock32_ordinal347 TEXTEQU <__imp_wsock32_ordinal347>
extern __imp_wsock32_ordinal348:PANYARGS
wsock32_ordinal348 TEXTEQU <__imp_wsock32_ordinal348>
extern __imp_wsock32_ordinal349:PANYARGS
wsock32_ordinal349 TEXTEQU <__imp_wsock32_ordinal349>
extern __imp_wsock32_ordinal350:PANYARGS
wsock32_ordinal350 TEXTEQU <__imp_wsock32_ordinal350>
extern __imp_wsock32_ordinal351:PANYARGS
wsock32_ordinal351 TEXTEQU <__imp_wsock32_ordinal351>
extern __imp_wsock32_ordinal352:PANYARGS
wsock32_ordinal352 TEXTEQU <__imp_wsock32_ordinal352>
extern __imp_wsock32_ordinal353:PANYARGS
wsock32_ordinal353 TEXTEQU <__imp_wsock32_ordinal353>
extern __imp_wsock32_ordinal354:PANYARGS
wsock32_ordinal354 TEXTEQU <__imp_wsock32_ordinal354>
extern __imp_wsock32_ordinal355:PANYARGS
wsock32_ordinal355 TEXTEQU <__imp_wsock32_ordinal355>
extern __imp_wsock32_ordinal356:PANYARGS
wsock32_ordinal356 TEXTEQU <__imp_wsock32_ordinal356>
extern __imp_wsock32_ordinal357:PANYARGS
wsock32_ordinal357 TEXTEQU <__imp_wsock32_ordinal357>
extern __imp_wsock32_ordinal358:PANYARGS
wsock32_ordinal358 TEXTEQU <__imp_wsock32_ordinal358>
extern __imp_wsock32_ordinal359:PANYARGS
wsock32_ordinal359 TEXTEQU <__imp_wsock32_ordinal359>
extern __imp_wsock32_ordinal360:PANYARGS
wsock32_ordinal360 TEXTEQU <__imp_wsock32_ordinal360>
extern __imp_wsock32_ordinal361:PANYARGS
wsock32_ordinal361 TEXTEQU <__imp_wsock32_ordinal361>
extern __imp_wsock32_ordinal362:PANYARGS
wsock32_ordinal362 TEXTEQU <__imp_wsock32_ordinal362>
extern __imp_wsock32_ordinal363:PANYARGS
wsock32_ordinal363 TEXTEQU <__imp_wsock32_ordinal363>
extern __imp_wsock32_ordinal364:PANYARGS
wsock32_ordinal364 TEXTEQU <__imp_wsock32_ordinal364>
extern __imp_wsock32_ordinal365:PANYARGS
wsock32_ordinal365 TEXTEQU <__imp_wsock32_ordinal365>
extern __imp_wsock32_ordinal366:PANYARGS
wsock32_ordinal366 TEXTEQU <__imp_wsock32_ordinal366>
extern __imp_wsock32_ordinal367:PANYARGS
wsock32_ordinal367 TEXTEQU <__imp_wsock32_ordinal367>
extern __imp_wsock32_ordinal368:PANYARGS
wsock32_ordinal368 TEXTEQU <__imp_wsock32_ordinal368>
extern __imp_wsock32_ordinal369:PANYARGS
wsock32_ordinal369 TEXTEQU <__imp_wsock32_ordinal369>
extern __imp_wsock32_ordinal370:PANYARGS
wsock32_ordinal370 TEXTEQU <__imp_wsock32_ordinal370>
extern __imp_wsock32_ordinal371:PANYARGS
wsock32_ordinal371 TEXTEQU <__imp_wsock32_ordinal371>
extern __imp_wsock32_ordinal372:PANYARGS
wsock32_ordinal372 TEXTEQU <__imp_wsock32_ordinal372>
extern __imp_wsock32_ordinal373:PANYARGS
wsock32_ordinal373 TEXTEQU <__imp_wsock32_ordinal373>
extern __imp_wsock32_ordinal374:PANYARGS
wsock32_ordinal374 TEXTEQU <__imp_wsock32_ordinal374>
extern __imp_wsock32_ordinal375:PANYARGS
wsock32_ordinal375 TEXTEQU <__imp_wsock32_ordinal375>
extern __imp_wsock32_ordinal376:PANYARGS
wsock32_ordinal376 TEXTEQU <__imp_wsock32_ordinal376>
extern __imp_wsock32_ordinal377:PANYARGS
wsock32_ordinal377 TEXTEQU <__imp_wsock32_ordinal377>
extern __imp_wsock32_ordinal378:PANYARGS
wsock32_ordinal378 TEXTEQU <__imp_wsock32_ordinal378>
extern __imp_wsock32_ordinal379:PANYARGS
wsock32_ordinal379 TEXTEQU <__imp_wsock32_ordinal379>
extern __imp_wsock32_ordinal380:PANYARGS
wsock32_ordinal380 TEXTEQU <__imp_wsock32_ordinal380>
extern __imp_wsock32_ordinal381:PANYARGS
wsock32_ordinal381 TEXTEQU <__imp_wsock32_ordinal381>
extern __imp_wsock32_ordinal382:PANYARGS
wsock32_ordinal382 TEXTEQU <__imp_wsock32_ordinal382>
extern __imp_wsock32_ordinal383:PANYARGS
wsock32_ordinal383 TEXTEQU <__imp_wsock32_ordinal383>
extern __imp_wsock32_ordinal384:PANYARGS
wsock32_ordinal384 TEXTEQU <__imp_wsock32_ordinal384>
extern __imp_wsock32_ordinal385:PANYARGS
wsock32_ordinal385 TEXTEQU <__imp_wsock32_ordinal385>
extern __imp_wsock32_ordinal386:PANYARGS
wsock32_ordinal386 TEXTEQU <__imp_wsock32_ordinal386>
extern __imp_wsock32_ordinal387:PANYARGS
wsock32_ordinal387 TEXTEQU <__imp_wsock32_ordinal387>
extern __imp_wsock32_ordinal388:PANYARGS
wsock32_ordinal388 TEXTEQU <__imp_wsock32_ordinal388>
extern __imp_wsock32_ordinal389:PANYARGS
wsock32_ordinal389 TEXTEQU <__imp_wsock32_ordinal389>
extern __imp_wsock32_ordinal390:PANYARGS
wsock32_ordinal390 TEXTEQU <__imp_wsock32_ordinal390>
extern __imp_wsock32_ordinal391:PANYARGS
wsock32_ordinal391 TEXTEQU <__imp_wsock32_ordinal391>
extern __imp_wsock32_ordinal392:PANYARGS
wsock32_ordinal392 TEXTEQU <__imp_wsock32_ordinal392>
extern __imp_wsock32_ordinal393:PANYARGS
wsock32_ordinal393 TEXTEQU <__imp_wsock32_ordinal393>
extern __imp_wsock32_ordinal394:PANYARGS
wsock32_ordinal394 TEXTEQU <__imp_wsock32_ordinal394>
extern __imp_wsock32_ordinal395:PANYARGS
wsock32_ordinal395 TEXTEQU <__imp_wsock32_ordinal395>
extern __imp_wsock32_ordinal396:PANYARGS
wsock32_ordinal396 TEXTEQU <__imp_wsock32_ordinal396>
extern __imp_wsock32_ordinal397:PANYARGS
wsock32_ordinal397 TEXTEQU <__imp_wsock32_ordinal397>
extern __imp_wsock32_ordinal398:PANYARGS
wsock32_ordinal398 TEXTEQU <__imp_wsock32_ordinal398>
extern __imp_wsock32_ordinal399:PANYARGS
wsock32_ordinal399 TEXTEQU <__imp_wsock32_ordinal399>
extern __imp_wsock32_ordinal400:PANYARGS
wsock32_ordinal400 TEXTEQU <__imp_wsock32_ordinal400>
extern __imp_wsock32_ordinal401:PANYARGS
wsock32_ordinal401 TEXTEQU <__imp_wsock32_ordinal401>
extern __imp_wsock32_ordinal402:PANYARGS
wsock32_ordinal402 TEXTEQU <__imp_wsock32_ordinal402>
extern __imp_wsock32_ordinal403:PANYARGS
wsock32_ordinal403 TEXTEQU <__imp_wsock32_ordinal403>
extern __imp_wsock32_ordinal404:PANYARGS
wsock32_ordinal404 TEXTEQU <__imp_wsock32_ordinal404>
extern __imp_wsock32_ordinal405:PANYARGS
wsock32_ordinal405 TEXTEQU <__imp_wsock32_ordinal405>
extern __imp_wsock32_ordinal406:PANYARGS
wsock32_ordinal406 TEXTEQU <__imp_wsock32_ordinal406>
extern __imp_wsock32_ordinal407:PANYARGS
wsock32_ordinal407 TEXTEQU <__imp_wsock32_ordinal407>
extern __imp_wsock32_ordinal408:PANYARGS
wsock32_ordinal408 TEXTEQU <__imp_wsock32_ordinal408>
extern __imp_wsock32_ordinal409:PANYARGS
wsock32_ordinal409 TEXTEQU <__imp_wsock32_ordinal409>
extern __imp_wsock32_ordinal410:PANYARGS
wsock32_ordinal410 TEXTEQU <__imp_wsock32_ordinal410>
extern __imp_wsock32_ordinal411:PANYARGS
wsock32_ordinal411 TEXTEQU <__imp_wsock32_ordinal411>
extern __imp_wsock32_ordinal412:PANYARGS
wsock32_ordinal412 TEXTEQU <__imp_wsock32_ordinal412>
extern __imp_wsock32_ordinal413:PANYARGS
wsock32_ordinal413 TEXTEQU <__imp_wsock32_ordinal413>
extern __imp_wsock32_ordinal414:PANYARGS
wsock32_ordinal414 TEXTEQU <__imp_wsock32_ordinal414>
extern __imp_wsock32_ordinal415:PANYARGS
wsock32_ordinal415 TEXTEQU <__imp_wsock32_ordinal415>
extern __imp_wsock32_ordinal416:PANYARGS
wsock32_ordinal416 TEXTEQU <__imp_wsock32_ordinal416>
extern __imp_wsock32_ordinal417:PANYARGS
wsock32_ordinal417 TEXTEQU <__imp_wsock32_ordinal417>
extern __imp_wsock32_ordinal418:PANYARGS
wsock32_ordinal418 TEXTEQU <__imp_wsock32_ordinal418>
extern __imp_wsock32_ordinal419:PANYARGS
wsock32_ordinal419 TEXTEQU <__imp_wsock32_ordinal419>
extern __imp_wsock32_ordinal420:PANYARGS
wsock32_ordinal420 TEXTEQU <__imp_wsock32_ordinal420>
extern __imp_wsock32_ordinal421:PANYARGS
wsock32_ordinal421 TEXTEQU <__imp_wsock32_ordinal421>
extern __imp_wsock32_ordinal422:PANYARGS
wsock32_ordinal422 TEXTEQU <__imp_wsock32_ordinal422>
extern __imp_wsock32_ordinal423:PANYARGS
wsock32_ordinal423 TEXTEQU <__imp_wsock32_ordinal423>
extern __imp_wsock32_ordinal424:PANYARGS
wsock32_ordinal424 TEXTEQU <__imp_wsock32_ordinal424>
extern __imp_wsock32_ordinal425:PANYARGS
wsock32_ordinal425 TEXTEQU <__imp_wsock32_ordinal425>
extern __imp_wsock32_ordinal426:PANYARGS
wsock32_ordinal426 TEXTEQU <__imp_wsock32_ordinal426>
extern __imp_wsock32_ordinal427:PANYARGS
wsock32_ordinal427 TEXTEQU <__imp_wsock32_ordinal427>
extern __imp_wsock32_ordinal428:PANYARGS
wsock32_ordinal428 TEXTEQU <__imp_wsock32_ordinal428>
extern __imp_wsock32_ordinal429:PANYARGS
wsock32_ordinal429 TEXTEQU <__imp_wsock32_ordinal429>
extern __imp_wsock32_ordinal430:PANYARGS
wsock32_ordinal430 TEXTEQU <__imp_wsock32_ordinal430>
extern __imp_wsock32_ordinal431:PANYARGS
wsock32_ordinal431 TEXTEQU <__imp_wsock32_ordinal431>
extern __imp_wsock32_ordinal432:PANYARGS
wsock32_ordinal432 TEXTEQU <__imp_wsock32_ordinal432>
extern __imp_wsock32_ordinal433:PANYARGS
wsock32_ordinal433 TEXTEQU <__imp_wsock32_ordinal433>
extern __imp_wsock32_ordinal434:PANYARGS
wsock32_ordinal434 TEXTEQU <__imp_wsock32_ordinal434>
extern __imp_wsock32_ordinal435:PANYARGS
wsock32_ordinal435 TEXTEQU <__imp_wsock32_ordinal435>
extern __imp_wsock32_ordinal436:PANYARGS
wsock32_ordinal436 TEXTEQU <__imp_wsock32_ordinal436>
extern __imp_wsock32_ordinal437:PANYARGS
wsock32_ordinal437 TEXTEQU <__imp_wsock32_ordinal437>
extern __imp_wsock32_ordinal438:PANYARGS
wsock32_ordinal438 TEXTEQU <__imp_wsock32_ordinal438>
extern __imp_wsock32_ordinal439:PANYARGS
wsock32_ordinal439 TEXTEQU <__imp_wsock32_ordinal439>
extern __imp_wsock32_ordinal440:PANYARGS
wsock32_ordinal440 TEXTEQU <__imp_wsock32_ordinal440>
extern __imp_wsock32_ordinal441:PANYARGS
wsock32_ordinal441 TEXTEQU <__imp_wsock32_ordinal441>
extern __imp_wsock32_ordinal442:PANYARGS
wsock32_ordinal442 TEXTEQU <__imp_wsock32_ordinal442>
extern __imp_wsock32_ordinal443:PANYARGS
wsock32_ordinal443 TEXTEQU <__imp_wsock32_ordinal443>
extern __imp_wsock32_ordinal444:PANYARGS
wsock32_ordinal444 TEXTEQU <__imp_wsock32_ordinal444>
extern __imp_wsock32_ordinal445:PANYARGS
wsock32_ordinal445 TEXTEQU <__imp_wsock32_ordinal445>
extern __imp_wsock32_ordinal446:PANYARGS
wsock32_ordinal446 TEXTEQU <__imp_wsock32_ordinal446>
extern __imp_wsock32_ordinal447:PANYARGS
wsock32_ordinal447 TEXTEQU <__imp_wsock32_ordinal447>
extern __imp_wsock32_ordinal448:PANYARGS
wsock32_ordinal448 TEXTEQU <__imp_wsock32_ordinal448>
extern __imp_wsock32_ordinal449:PANYARGS
wsock32_ordinal449 TEXTEQU <__imp_wsock32_ordinal449>
extern __imp_wsock32_ordinal450:PANYARGS
wsock32_ordinal450 TEXTEQU <__imp_wsock32_ordinal450>
extern __imp_wsock32_ordinal451:PANYARGS
wsock32_ordinal451 TEXTEQU <__imp_wsock32_ordinal451>
extern __imp_wsock32_ordinal452:PANYARGS
wsock32_ordinal452 TEXTEQU <__imp_wsock32_ordinal452>
extern __imp_wsock32_ordinal453:PANYARGS
wsock32_ordinal453 TEXTEQU <__imp_wsock32_ordinal453>
extern __imp_wsock32_ordinal454:PANYARGS
wsock32_ordinal454 TEXTEQU <__imp_wsock32_ordinal454>
extern __imp_wsock32_ordinal455:PANYARGS
wsock32_ordinal455 TEXTEQU <__imp_wsock32_ordinal455>
extern __imp_wsock32_ordinal456:PANYARGS
wsock32_ordinal456 TEXTEQU <__imp_wsock32_ordinal456>
extern __imp_wsock32_ordinal457:PANYARGS
wsock32_ordinal457 TEXTEQU <__imp_wsock32_ordinal457>
extern __imp_wsock32_ordinal458:PANYARGS
wsock32_ordinal458 TEXTEQU <__imp_wsock32_ordinal458>
extern __imp_wsock32_ordinal459:PANYARGS
wsock32_ordinal459 TEXTEQU <__imp_wsock32_ordinal459>
extern __imp_wsock32_ordinal460:PANYARGS
wsock32_ordinal460 TEXTEQU <__imp_wsock32_ordinal460>
extern __imp_wsock32_ordinal461:PANYARGS
wsock32_ordinal461 TEXTEQU <__imp_wsock32_ordinal461>
extern __imp_wsock32_ordinal462:PANYARGS
wsock32_ordinal462 TEXTEQU <__imp_wsock32_ordinal462>
extern __imp_wsock32_ordinal463:PANYARGS
wsock32_ordinal463 TEXTEQU <__imp_wsock32_ordinal463>
extern __imp_wsock32_ordinal464:PANYARGS
wsock32_ordinal464 TEXTEQU <__imp_wsock32_ordinal464>
extern __imp_wsock32_ordinal465:PANYARGS
wsock32_ordinal465 TEXTEQU <__imp_wsock32_ordinal465>
extern __imp_wsock32_ordinal466:PANYARGS
wsock32_ordinal466 TEXTEQU <__imp_wsock32_ordinal466>
extern __imp_wsock32_ordinal467:PANYARGS
wsock32_ordinal467 TEXTEQU <__imp_wsock32_ordinal467>
extern __imp_wsock32_ordinal468:PANYARGS
wsock32_ordinal468 TEXTEQU <__imp_wsock32_ordinal468>
extern __imp_wsock32_ordinal469:PANYARGS
wsock32_ordinal469 TEXTEQU <__imp_wsock32_ordinal469>
extern __imp_wsock32_ordinal470:PANYARGS
wsock32_ordinal470 TEXTEQU <__imp_wsock32_ordinal470>
extern __imp_wsock32_ordinal471:PANYARGS
wsock32_ordinal471 TEXTEQU <__imp_wsock32_ordinal471>
extern __imp_wsock32_ordinal472:PANYARGS
wsock32_ordinal472 TEXTEQU <__imp_wsock32_ordinal472>
extern __imp_wsock32_ordinal473:PANYARGS
wsock32_ordinal473 TEXTEQU <__imp_wsock32_ordinal473>
extern __imp_wsock32_ordinal474:PANYARGS
wsock32_ordinal474 TEXTEQU <__imp_wsock32_ordinal474>
extern __imp_wsock32_ordinal475:PANYARGS
wsock32_ordinal475 TEXTEQU <__imp_wsock32_ordinal475>
extern __imp_wsock32_ordinal476:PANYARGS
wsock32_ordinal476 TEXTEQU <__imp_wsock32_ordinal476>
extern __imp_wsock32_ordinal477:PANYARGS
wsock32_ordinal477 TEXTEQU <__imp_wsock32_ordinal477>
extern __imp_wsock32_ordinal478:PANYARGS
wsock32_ordinal478 TEXTEQU <__imp_wsock32_ordinal478>
extern __imp_wsock32_ordinal479:PANYARGS
wsock32_ordinal479 TEXTEQU <__imp_wsock32_ordinal479>
extern __imp_wsock32_ordinal480:PANYARGS
wsock32_ordinal480 TEXTEQU <__imp_wsock32_ordinal480>
extern __imp_wsock32_ordinal481:PANYARGS
wsock32_ordinal481 TEXTEQU <__imp_wsock32_ordinal481>
extern __imp_wsock32_ordinal482:PANYARGS
wsock32_ordinal482 TEXTEQU <__imp_wsock32_ordinal482>
extern __imp_wsock32_ordinal483:PANYARGS
wsock32_ordinal483 TEXTEQU <__imp_wsock32_ordinal483>
extern __imp_wsock32_ordinal484:PANYARGS
wsock32_ordinal484 TEXTEQU <__imp_wsock32_ordinal484>
extern __imp_wsock32_ordinal485:PANYARGS
wsock32_ordinal485 TEXTEQU <__imp_wsock32_ordinal485>
extern __imp_wsock32_ordinal486:PANYARGS
wsock32_ordinal486 TEXTEQU <__imp_wsock32_ordinal486>
extern __imp_wsock32_ordinal487:PANYARGS
wsock32_ordinal487 TEXTEQU <__imp_wsock32_ordinal487>
extern __imp_wsock32_ordinal488:PANYARGS
wsock32_ordinal488 TEXTEQU <__imp_wsock32_ordinal488>
extern __imp_wsock32_ordinal489:PANYARGS
wsock32_ordinal489 TEXTEQU <__imp_wsock32_ordinal489>
extern __imp_wsock32_ordinal490:PANYARGS
wsock32_ordinal490 TEXTEQU <__imp_wsock32_ordinal490>
extern __imp_wsock32_ordinal491:PANYARGS
wsock32_ordinal491 TEXTEQU <__imp_wsock32_ordinal491>
extern __imp_wsock32_ordinal492:PANYARGS
wsock32_ordinal492 TEXTEQU <__imp_wsock32_ordinal492>
extern __imp_wsock32_ordinal493:PANYARGS
wsock32_ordinal493 TEXTEQU <__imp_wsock32_ordinal493>
extern __imp_wsock32_ordinal494:PANYARGS
wsock32_ordinal494 TEXTEQU <__imp_wsock32_ordinal494>
extern __imp_wsock32_ordinal495:PANYARGS
wsock32_ordinal495 TEXTEQU <__imp_wsock32_ordinal495>
extern __imp_wsock32_ordinal496:PANYARGS
wsock32_ordinal496 TEXTEQU <__imp_wsock32_ordinal496>
extern __imp_wsock32_ordinal497:PANYARGS
wsock32_ordinal497 TEXTEQU <__imp_wsock32_ordinal497>
extern __imp_wsock32_ordinal498:PANYARGS
wsock32_ordinal498 TEXTEQU <__imp_wsock32_ordinal498>
extern __imp_wsock32_ordinal499:PANYARGS
wsock32_ordinal499 TEXTEQU <__imp_wsock32_ordinal499>
extern __imp_WEP:PANYARGS
WEP TEXTEQU <__imp_WEP>
extern __imp_wsock32_ordinal501:PANYARGS
wsock32_ordinal501 TEXTEQU <__imp_wsock32_ordinal501>
extern __imp_wsock32_ordinal502:PANYARGS
wsock32_ordinal502 TEXTEQU <__imp_wsock32_ordinal502>
extern __imp_wsock32_ordinal503:PANYARGS
wsock32_ordinal503 TEXTEQU <__imp_wsock32_ordinal503>
extern __imp_wsock32_ordinal504:PANYARGS
wsock32_ordinal504 TEXTEQU <__imp_wsock32_ordinal504>
extern __imp_wsock32_ordinal505:PANYARGS
wsock32_ordinal505 TEXTEQU <__imp_wsock32_ordinal505>
extern __imp_wsock32_ordinal506:PANYARGS
wsock32_ordinal506 TEXTEQU <__imp_wsock32_ordinal506>
extern __imp_wsock32_ordinal507:PANYARGS
wsock32_ordinal507 TEXTEQU <__imp_wsock32_ordinal507>
extern __imp_wsock32_ordinal508:PANYARGS
wsock32_ordinal508 TEXTEQU <__imp_wsock32_ordinal508>
extern __imp_wsock32_ordinal509:PANYARGS
wsock32_ordinal509 TEXTEQU <__imp_wsock32_ordinal509>
extern __imp_wsock32_ordinal510:PANYARGS
wsock32_ordinal510 TEXTEQU <__imp_wsock32_ordinal510>
extern __imp_wsock32_ordinal511:PANYARGS
wsock32_ordinal511 TEXTEQU <__imp_wsock32_ordinal511>
extern __imp_wsock32_ordinal512:PANYARGS
wsock32_ordinal512 TEXTEQU <__imp_wsock32_ordinal512>
extern __imp_wsock32_ordinal513:PANYARGS
wsock32_ordinal513 TEXTEQU <__imp_wsock32_ordinal513>
extern __imp_wsock32_ordinal514:PANYARGS
wsock32_ordinal514 TEXTEQU <__imp_wsock32_ordinal514>
extern __imp_wsock32_ordinal515:PANYARGS
wsock32_ordinal515 TEXTEQU <__imp_wsock32_ordinal515>
extern __imp_wsock32_ordinal516:PANYARGS
wsock32_ordinal516 TEXTEQU <__imp_wsock32_ordinal516>
extern __imp_wsock32_ordinal517:PANYARGS
wsock32_ordinal517 TEXTEQU <__imp_wsock32_ordinal517>
extern __imp_wsock32_ordinal518:PANYARGS
wsock32_ordinal518 TEXTEQU <__imp_wsock32_ordinal518>
extern __imp_wsock32_ordinal519:PANYARGS
wsock32_ordinal519 TEXTEQU <__imp_wsock32_ordinal519>
extern __imp_wsock32_ordinal520:PANYARGS
wsock32_ordinal520 TEXTEQU <__imp_wsock32_ordinal520>
extern __imp_wsock32_ordinal521:PANYARGS
wsock32_ordinal521 TEXTEQU <__imp_wsock32_ordinal521>
extern __imp_wsock32_ordinal522:PANYARGS
wsock32_ordinal522 TEXTEQU <__imp_wsock32_ordinal522>
extern __imp_wsock32_ordinal523:PANYARGS
wsock32_ordinal523 TEXTEQU <__imp_wsock32_ordinal523>
extern __imp_wsock32_ordinal524:PANYARGS
wsock32_ordinal524 TEXTEQU <__imp_wsock32_ordinal524>
extern __imp_wsock32_ordinal525:PANYARGS
wsock32_ordinal525 TEXTEQU <__imp_wsock32_ordinal525>
extern __imp_wsock32_ordinal526:PANYARGS
wsock32_ordinal526 TEXTEQU <__imp_wsock32_ordinal526>
extern __imp_wsock32_ordinal527:PANYARGS
wsock32_ordinal527 TEXTEQU <__imp_wsock32_ordinal527>
extern __imp_wsock32_ordinal528:PANYARGS
wsock32_ordinal528 TEXTEQU <__imp_wsock32_ordinal528>
extern __imp_wsock32_ordinal529:PANYARGS
wsock32_ordinal529 TEXTEQU <__imp_wsock32_ordinal529>
extern __imp_wsock32_ordinal530:PANYARGS
wsock32_ordinal530 TEXTEQU <__imp_wsock32_ordinal530>
extern __imp_wsock32_ordinal531:PANYARGS
wsock32_ordinal531 TEXTEQU <__imp_wsock32_ordinal531>
extern __imp_wsock32_ordinal532:PANYARGS
wsock32_ordinal532 TEXTEQU <__imp_wsock32_ordinal532>
extern __imp_wsock32_ordinal533:PANYARGS
wsock32_ordinal533 TEXTEQU <__imp_wsock32_ordinal533>
extern __imp_wsock32_ordinal534:PANYARGS
wsock32_ordinal534 TEXTEQU <__imp_wsock32_ordinal534>
extern __imp_wsock32_ordinal535:PANYARGS
wsock32_ordinal535 TEXTEQU <__imp_wsock32_ordinal535>
extern __imp_wsock32_ordinal536:PANYARGS
wsock32_ordinal536 TEXTEQU <__imp_wsock32_ordinal536>
extern __imp_wsock32_ordinal537:PANYARGS
wsock32_ordinal537 TEXTEQU <__imp_wsock32_ordinal537>
extern __imp_wsock32_ordinal538:PANYARGS
wsock32_ordinal538 TEXTEQU <__imp_wsock32_ordinal538>
extern __imp_wsock32_ordinal539:PANYARGS
wsock32_ordinal539 TEXTEQU <__imp_wsock32_ordinal539>
extern __imp_wsock32_ordinal540:PANYARGS
wsock32_ordinal540 TEXTEQU <__imp_wsock32_ordinal540>
extern __imp_wsock32_ordinal541:PANYARGS
wsock32_ordinal541 TEXTEQU <__imp_wsock32_ordinal541>
extern __imp_wsock32_ordinal542:PANYARGS
wsock32_ordinal542 TEXTEQU <__imp_wsock32_ordinal542>
extern __imp_wsock32_ordinal543:PANYARGS
wsock32_ordinal543 TEXTEQU <__imp_wsock32_ordinal543>
extern __imp_wsock32_ordinal544:PANYARGS
wsock32_ordinal544 TEXTEQU <__imp_wsock32_ordinal544>
extern __imp_wsock32_ordinal545:PANYARGS
wsock32_ordinal545 TEXTEQU <__imp_wsock32_ordinal545>
extern __imp_wsock32_ordinal546:PANYARGS
wsock32_ordinal546 TEXTEQU <__imp_wsock32_ordinal546>
extern __imp_wsock32_ordinal547:PANYARGS
wsock32_ordinal547 TEXTEQU <__imp_wsock32_ordinal547>
extern __imp_wsock32_ordinal548:PANYARGS
wsock32_ordinal548 TEXTEQU <__imp_wsock32_ordinal548>
extern __imp_wsock32_ordinal549:PANYARGS
wsock32_ordinal549 TEXTEQU <__imp_wsock32_ordinal549>
extern __imp_wsock32_ordinal550:PANYARGS
wsock32_ordinal550 TEXTEQU <__imp_wsock32_ordinal550>
extern __imp_wsock32_ordinal551:PANYARGS
wsock32_ordinal551 TEXTEQU <__imp_wsock32_ordinal551>
extern __imp_wsock32_ordinal552:PANYARGS
wsock32_ordinal552 TEXTEQU <__imp_wsock32_ordinal552>
extern __imp_wsock32_ordinal553:PANYARGS
wsock32_ordinal553 TEXTEQU <__imp_wsock32_ordinal553>
extern __imp_wsock32_ordinal554:PANYARGS
wsock32_ordinal554 TEXTEQU <__imp_wsock32_ordinal554>
extern __imp_wsock32_ordinal555:PANYARGS
wsock32_ordinal555 TEXTEQU <__imp_wsock32_ordinal555>
extern __imp_wsock32_ordinal556:PANYARGS
wsock32_ordinal556 TEXTEQU <__imp_wsock32_ordinal556>
extern __imp_wsock32_ordinal557:PANYARGS
wsock32_ordinal557 TEXTEQU <__imp_wsock32_ordinal557>
extern __imp_wsock32_ordinal558:PANYARGS
wsock32_ordinal558 TEXTEQU <__imp_wsock32_ordinal558>
extern __imp_wsock32_ordinal559:PANYARGS
wsock32_ordinal559 TEXTEQU <__imp_wsock32_ordinal559>
extern __imp_wsock32_ordinal560:PANYARGS
wsock32_ordinal560 TEXTEQU <__imp_wsock32_ordinal560>
extern __imp_wsock32_ordinal561:PANYARGS
wsock32_ordinal561 TEXTEQU <__imp_wsock32_ordinal561>
extern __imp_wsock32_ordinal562:PANYARGS
wsock32_ordinal562 TEXTEQU <__imp_wsock32_ordinal562>
extern __imp_wsock32_ordinal563:PANYARGS
wsock32_ordinal563 TEXTEQU <__imp_wsock32_ordinal563>
extern __imp_wsock32_ordinal564:PANYARGS
wsock32_ordinal564 TEXTEQU <__imp_wsock32_ordinal564>
extern __imp_wsock32_ordinal565:PANYARGS
wsock32_ordinal565 TEXTEQU <__imp_wsock32_ordinal565>
extern __imp_wsock32_ordinal566:PANYARGS
wsock32_ordinal566 TEXTEQU <__imp_wsock32_ordinal566>
extern __imp_wsock32_ordinal567:PANYARGS
wsock32_ordinal567 TEXTEQU <__imp_wsock32_ordinal567>
extern __imp_wsock32_ordinal568:PANYARGS
wsock32_ordinal568 TEXTEQU <__imp_wsock32_ordinal568>
extern __imp_wsock32_ordinal569:PANYARGS
wsock32_ordinal569 TEXTEQU <__imp_wsock32_ordinal569>
extern __imp_wsock32_ordinal570:PANYARGS
wsock32_ordinal570 TEXTEQU <__imp_wsock32_ordinal570>
extern __imp_wsock32_ordinal571:PANYARGS
wsock32_ordinal571 TEXTEQU <__imp_wsock32_ordinal571>
extern __imp_wsock32_ordinal572:PANYARGS
wsock32_ordinal572 TEXTEQU <__imp_wsock32_ordinal572>
extern __imp_wsock32_ordinal573:PANYARGS
wsock32_ordinal573 TEXTEQU <__imp_wsock32_ordinal573>
extern __imp_wsock32_ordinal574:PANYARGS
wsock32_ordinal574 TEXTEQU <__imp_wsock32_ordinal574>
extern __imp_wsock32_ordinal575:PANYARGS
wsock32_ordinal575 TEXTEQU <__imp_wsock32_ordinal575>
extern __imp_wsock32_ordinal576:PANYARGS
wsock32_ordinal576 TEXTEQU <__imp_wsock32_ordinal576>
extern __imp_wsock32_ordinal577:PANYARGS
wsock32_ordinal577 TEXTEQU <__imp_wsock32_ordinal577>
extern __imp_wsock32_ordinal578:PANYARGS
wsock32_ordinal578 TEXTEQU <__imp_wsock32_ordinal578>
extern __imp_wsock32_ordinal579:PANYARGS
wsock32_ordinal579 TEXTEQU <__imp_wsock32_ordinal579>
extern __imp_wsock32_ordinal580:PANYARGS
wsock32_ordinal580 TEXTEQU <__imp_wsock32_ordinal580>
extern __imp_wsock32_ordinal581:PANYARGS
wsock32_ordinal581 TEXTEQU <__imp_wsock32_ordinal581>
extern __imp_wsock32_ordinal582:PANYARGS
wsock32_ordinal582 TEXTEQU <__imp_wsock32_ordinal582>
extern __imp_wsock32_ordinal583:PANYARGS
wsock32_ordinal583 TEXTEQU <__imp_wsock32_ordinal583>
extern __imp_wsock32_ordinal584:PANYARGS
wsock32_ordinal584 TEXTEQU <__imp_wsock32_ordinal584>
extern __imp_wsock32_ordinal585:PANYARGS
wsock32_ordinal585 TEXTEQU <__imp_wsock32_ordinal585>
extern __imp_wsock32_ordinal586:PANYARGS
wsock32_ordinal586 TEXTEQU <__imp_wsock32_ordinal586>
extern __imp_wsock32_ordinal587:PANYARGS
wsock32_ordinal587 TEXTEQU <__imp_wsock32_ordinal587>
extern __imp_wsock32_ordinal588:PANYARGS
wsock32_ordinal588 TEXTEQU <__imp_wsock32_ordinal588>
extern __imp_wsock32_ordinal589:PANYARGS
wsock32_ordinal589 TEXTEQU <__imp_wsock32_ordinal589>
extern __imp_wsock32_ordinal590:PANYARGS
wsock32_ordinal590 TEXTEQU <__imp_wsock32_ordinal590>
extern __imp_wsock32_ordinal591:PANYARGS
wsock32_ordinal591 TEXTEQU <__imp_wsock32_ordinal591>
extern __imp_wsock32_ordinal592:PANYARGS
wsock32_ordinal592 TEXTEQU <__imp_wsock32_ordinal592>
extern __imp_wsock32_ordinal593:PANYARGS
wsock32_ordinal593 TEXTEQU <__imp_wsock32_ordinal593>
extern __imp_wsock32_ordinal594:PANYARGS
wsock32_ordinal594 TEXTEQU <__imp_wsock32_ordinal594>
extern __imp_wsock32_ordinal595:PANYARGS
wsock32_ordinal595 TEXTEQU <__imp_wsock32_ordinal595>
extern __imp_wsock32_ordinal596:PANYARGS
wsock32_ordinal596 TEXTEQU <__imp_wsock32_ordinal596>
extern __imp_wsock32_ordinal597:PANYARGS
wsock32_ordinal597 TEXTEQU <__imp_wsock32_ordinal597>
extern __imp_wsock32_ordinal598:PANYARGS
wsock32_ordinal598 TEXTEQU <__imp_wsock32_ordinal598>
extern __imp_wsock32_ordinal599:PANYARGS
wsock32_ordinal599 TEXTEQU <__imp_wsock32_ordinal599>
extern __imp_wsock32_ordinal600:PANYARGS
wsock32_ordinal600 TEXTEQU <__imp_wsock32_ordinal600>
extern __imp_wsock32_ordinal601:PANYARGS
wsock32_ordinal601 TEXTEQU <__imp_wsock32_ordinal601>
extern __imp_wsock32_ordinal602:PANYARGS
wsock32_ordinal602 TEXTEQU <__imp_wsock32_ordinal602>
extern __imp_wsock32_ordinal603:PANYARGS
wsock32_ordinal603 TEXTEQU <__imp_wsock32_ordinal603>
extern __imp_wsock32_ordinal604:PANYARGS
wsock32_ordinal604 TEXTEQU <__imp_wsock32_ordinal604>
extern __imp_wsock32_ordinal605:PANYARGS
wsock32_ordinal605 TEXTEQU <__imp_wsock32_ordinal605>
extern __imp_wsock32_ordinal606:PANYARGS
wsock32_ordinal606 TEXTEQU <__imp_wsock32_ordinal606>
extern __imp_wsock32_ordinal607:PANYARGS
wsock32_ordinal607 TEXTEQU <__imp_wsock32_ordinal607>
extern __imp_wsock32_ordinal608:PANYARGS
wsock32_ordinal608 TEXTEQU <__imp_wsock32_ordinal608>
extern __imp_wsock32_ordinal609:PANYARGS
wsock32_ordinal609 TEXTEQU <__imp_wsock32_ordinal609>
extern __imp_wsock32_ordinal610:PANYARGS
wsock32_ordinal610 TEXTEQU <__imp_wsock32_ordinal610>
extern __imp_wsock32_ordinal611:PANYARGS
wsock32_ordinal611 TEXTEQU <__imp_wsock32_ordinal611>
extern __imp_wsock32_ordinal612:PANYARGS
wsock32_ordinal612 TEXTEQU <__imp_wsock32_ordinal612>
extern __imp_wsock32_ordinal613:PANYARGS
wsock32_ordinal613 TEXTEQU <__imp_wsock32_ordinal613>
extern __imp_wsock32_ordinal614:PANYARGS
wsock32_ordinal614 TEXTEQU <__imp_wsock32_ordinal614>
extern __imp_wsock32_ordinal615:PANYARGS
wsock32_ordinal615 TEXTEQU <__imp_wsock32_ordinal615>
extern __imp_wsock32_ordinal616:PANYARGS
wsock32_ordinal616 TEXTEQU <__imp_wsock32_ordinal616>
extern __imp_wsock32_ordinal617:PANYARGS
wsock32_ordinal617 TEXTEQU <__imp_wsock32_ordinal617>
extern __imp_wsock32_ordinal618:PANYARGS
wsock32_ordinal618 TEXTEQU <__imp_wsock32_ordinal618>
extern __imp_wsock32_ordinal619:PANYARGS
wsock32_ordinal619 TEXTEQU <__imp_wsock32_ordinal619>
extern __imp_wsock32_ordinal620:PANYARGS
wsock32_ordinal620 TEXTEQU <__imp_wsock32_ordinal620>
extern __imp_wsock32_ordinal621:PANYARGS
wsock32_ordinal621 TEXTEQU <__imp_wsock32_ordinal621>
extern __imp_wsock32_ordinal622:PANYARGS
wsock32_ordinal622 TEXTEQU <__imp_wsock32_ordinal622>
extern __imp_wsock32_ordinal623:PANYARGS
wsock32_ordinal623 TEXTEQU <__imp_wsock32_ordinal623>
extern __imp_wsock32_ordinal624:PANYARGS
wsock32_ordinal624 TEXTEQU <__imp_wsock32_ordinal624>
extern __imp_wsock32_ordinal625:PANYARGS
wsock32_ordinal625 TEXTEQU <__imp_wsock32_ordinal625>
extern __imp_wsock32_ordinal626:PANYARGS
wsock32_ordinal626 TEXTEQU <__imp_wsock32_ordinal626>
extern __imp_wsock32_ordinal627:PANYARGS
wsock32_ordinal627 TEXTEQU <__imp_wsock32_ordinal627>
extern __imp_wsock32_ordinal628:PANYARGS
wsock32_ordinal628 TEXTEQU <__imp_wsock32_ordinal628>
extern __imp_wsock32_ordinal629:PANYARGS
wsock32_ordinal629 TEXTEQU <__imp_wsock32_ordinal629>
extern __imp_wsock32_ordinal630:PANYARGS
wsock32_ordinal630 TEXTEQU <__imp_wsock32_ordinal630>
extern __imp_wsock32_ordinal631:PANYARGS
wsock32_ordinal631 TEXTEQU <__imp_wsock32_ordinal631>
extern __imp_wsock32_ordinal632:PANYARGS
wsock32_ordinal632 TEXTEQU <__imp_wsock32_ordinal632>
extern __imp_wsock32_ordinal633:PANYARGS
wsock32_ordinal633 TEXTEQU <__imp_wsock32_ordinal633>
extern __imp_wsock32_ordinal634:PANYARGS
wsock32_ordinal634 TEXTEQU <__imp_wsock32_ordinal634>
extern __imp_wsock32_ordinal635:PANYARGS
wsock32_ordinal635 TEXTEQU <__imp_wsock32_ordinal635>
extern __imp_wsock32_ordinal636:PANYARGS
wsock32_ordinal636 TEXTEQU <__imp_wsock32_ordinal636>
extern __imp_wsock32_ordinal637:PANYARGS
wsock32_ordinal637 TEXTEQU <__imp_wsock32_ordinal637>
extern __imp_wsock32_ordinal638:PANYARGS
wsock32_ordinal638 TEXTEQU <__imp_wsock32_ordinal638>
extern __imp_wsock32_ordinal639:PANYARGS
wsock32_ordinal639 TEXTEQU <__imp_wsock32_ordinal639>
extern __imp_wsock32_ordinal640:PANYARGS
wsock32_ordinal640 TEXTEQU <__imp_wsock32_ordinal640>
extern __imp_wsock32_ordinal641:PANYARGS
wsock32_ordinal641 TEXTEQU <__imp_wsock32_ordinal641>
extern __imp_wsock32_ordinal642:PANYARGS
wsock32_ordinal642 TEXTEQU <__imp_wsock32_ordinal642>
extern __imp_wsock32_ordinal643:PANYARGS
wsock32_ordinal643 TEXTEQU <__imp_wsock32_ordinal643>
extern __imp_wsock32_ordinal644:PANYARGS
wsock32_ordinal644 TEXTEQU <__imp_wsock32_ordinal644>
extern __imp_wsock32_ordinal645:PANYARGS
wsock32_ordinal645 TEXTEQU <__imp_wsock32_ordinal645>
extern __imp_wsock32_ordinal646:PANYARGS
wsock32_ordinal646 TEXTEQU <__imp_wsock32_ordinal646>
extern __imp_wsock32_ordinal647:PANYARGS
wsock32_ordinal647 TEXTEQU <__imp_wsock32_ordinal647>
extern __imp_wsock32_ordinal648:PANYARGS
wsock32_ordinal648 TEXTEQU <__imp_wsock32_ordinal648>
extern __imp_wsock32_ordinal649:PANYARGS
wsock32_ordinal649 TEXTEQU <__imp_wsock32_ordinal649>
extern __imp_wsock32_ordinal650:PANYARGS
wsock32_ordinal650 TEXTEQU <__imp_wsock32_ordinal650>
extern __imp_wsock32_ordinal651:PANYARGS
wsock32_ordinal651 TEXTEQU <__imp_wsock32_ordinal651>
extern __imp_wsock32_ordinal652:PANYARGS
wsock32_ordinal652 TEXTEQU <__imp_wsock32_ordinal652>
extern __imp_wsock32_ordinal653:PANYARGS
wsock32_ordinal653 TEXTEQU <__imp_wsock32_ordinal653>
extern __imp_wsock32_ordinal654:PANYARGS
wsock32_ordinal654 TEXTEQU <__imp_wsock32_ordinal654>
extern __imp_wsock32_ordinal655:PANYARGS
wsock32_ordinal655 TEXTEQU <__imp_wsock32_ordinal655>
extern __imp_wsock32_ordinal656:PANYARGS
wsock32_ordinal656 TEXTEQU <__imp_wsock32_ordinal656>
extern __imp_wsock32_ordinal657:PANYARGS
wsock32_ordinal657 TEXTEQU <__imp_wsock32_ordinal657>
extern __imp_wsock32_ordinal658:PANYARGS
wsock32_ordinal658 TEXTEQU <__imp_wsock32_ordinal658>
extern __imp_wsock32_ordinal659:PANYARGS
wsock32_ordinal659 TEXTEQU <__imp_wsock32_ordinal659>
extern __imp_wsock32_ordinal660:PANYARGS
wsock32_ordinal660 TEXTEQU <__imp_wsock32_ordinal660>
extern __imp_wsock32_ordinal661:PANYARGS
wsock32_ordinal661 TEXTEQU <__imp_wsock32_ordinal661>
extern __imp_wsock32_ordinal662:PANYARGS
wsock32_ordinal662 TEXTEQU <__imp_wsock32_ordinal662>
extern __imp_wsock32_ordinal663:PANYARGS
wsock32_ordinal663 TEXTEQU <__imp_wsock32_ordinal663>
extern __imp_wsock32_ordinal664:PANYARGS
wsock32_ordinal664 TEXTEQU <__imp_wsock32_ordinal664>
extern __imp_wsock32_ordinal665:PANYARGS
wsock32_ordinal665 TEXTEQU <__imp_wsock32_ordinal665>
extern __imp_wsock32_ordinal666:PANYARGS
wsock32_ordinal666 TEXTEQU <__imp_wsock32_ordinal666>
extern __imp_wsock32_ordinal667:PANYARGS
wsock32_ordinal667 TEXTEQU <__imp_wsock32_ordinal667>
extern __imp_wsock32_ordinal668:PANYARGS
wsock32_ordinal668 TEXTEQU <__imp_wsock32_ordinal668>
extern __imp_wsock32_ordinal669:PANYARGS
wsock32_ordinal669 TEXTEQU <__imp_wsock32_ordinal669>
extern __imp_wsock32_ordinal670:PANYARGS
wsock32_ordinal670 TEXTEQU <__imp_wsock32_ordinal670>
extern __imp_wsock32_ordinal671:PANYARGS
wsock32_ordinal671 TEXTEQU <__imp_wsock32_ordinal671>
extern __imp_wsock32_ordinal672:PANYARGS
wsock32_ordinal672 TEXTEQU <__imp_wsock32_ordinal672>
extern __imp_wsock32_ordinal673:PANYARGS
wsock32_ordinal673 TEXTEQU <__imp_wsock32_ordinal673>
extern __imp_wsock32_ordinal674:PANYARGS
wsock32_ordinal674 TEXTEQU <__imp_wsock32_ordinal674>
extern __imp_wsock32_ordinal675:PANYARGS
wsock32_ordinal675 TEXTEQU <__imp_wsock32_ordinal675>
extern __imp_wsock32_ordinal676:PANYARGS
wsock32_ordinal676 TEXTEQU <__imp_wsock32_ordinal676>
extern __imp_wsock32_ordinal677:PANYARGS
wsock32_ordinal677 TEXTEQU <__imp_wsock32_ordinal677>
extern __imp_wsock32_ordinal678:PANYARGS
wsock32_ordinal678 TEXTEQU <__imp_wsock32_ordinal678>
extern __imp_wsock32_ordinal679:PANYARGS
wsock32_ordinal679 TEXTEQU <__imp_wsock32_ordinal679>
extern __imp_wsock32_ordinal680:PANYARGS
wsock32_ordinal680 TEXTEQU <__imp_wsock32_ordinal680>
extern __imp_wsock32_ordinal681:PANYARGS
wsock32_ordinal681 TEXTEQU <__imp_wsock32_ordinal681>
extern __imp_wsock32_ordinal682:PANYARGS
wsock32_ordinal682 TEXTEQU <__imp_wsock32_ordinal682>
extern __imp_wsock32_ordinal683:PANYARGS
wsock32_ordinal683 TEXTEQU <__imp_wsock32_ordinal683>
extern __imp_wsock32_ordinal684:PANYARGS
wsock32_ordinal684 TEXTEQU <__imp_wsock32_ordinal684>
extern __imp_wsock32_ordinal685:PANYARGS
wsock32_ordinal685 TEXTEQU <__imp_wsock32_ordinal685>
extern __imp_wsock32_ordinal686:PANYARGS
wsock32_ordinal686 TEXTEQU <__imp_wsock32_ordinal686>
extern __imp_wsock32_ordinal687:PANYARGS
wsock32_ordinal687 TEXTEQU <__imp_wsock32_ordinal687>
extern __imp_wsock32_ordinal688:PANYARGS
wsock32_ordinal688 TEXTEQU <__imp_wsock32_ordinal688>
extern __imp_wsock32_ordinal689:PANYARGS
wsock32_ordinal689 TEXTEQU <__imp_wsock32_ordinal689>
extern __imp_wsock32_ordinal690:PANYARGS
wsock32_ordinal690 TEXTEQU <__imp_wsock32_ordinal690>
extern __imp_wsock32_ordinal691:PANYARGS
wsock32_ordinal691 TEXTEQU <__imp_wsock32_ordinal691>
extern __imp_wsock32_ordinal692:PANYARGS
wsock32_ordinal692 TEXTEQU <__imp_wsock32_ordinal692>
extern __imp_wsock32_ordinal693:PANYARGS
wsock32_ordinal693 TEXTEQU <__imp_wsock32_ordinal693>
extern __imp_wsock32_ordinal694:PANYARGS
wsock32_ordinal694 TEXTEQU <__imp_wsock32_ordinal694>
extern __imp_wsock32_ordinal695:PANYARGS
wsock32_ordinal695 TEXTEQU <__imp_wsock32_ordinal695>
extern __imp_wsock32_ordinal696:PANYARGS
wsock32_ordinal696 TEXTEQU <__imp_wsock32_ordinal696>
extern __imp_wsock32_ordinal697:PANYARGS
wsock32_ordinal697 TEXTEQU <__imp_wsock32_ordinal697>
extern __imp_wsock32_ordinal698:PANYARGS
wsock32_ordinal698 TEXTEQU <__imp_wsock32_ordinal698>
extern __imp_wsock32_ordinal699:PANYARGS
wsock32_ordinal699 TEXTEQU <__imp_wsock32_ordinal699>
extern __imp_wsock32_ordinal700:PANYARGS
wsock32_ordinal700 TEXTEQU <__imp_wsock32_ordinal700>
extern __imp_wsock32_ordinal701:PANYARGS
wsock32_ordinal701 TEXTEQU <__imp_wsock32_ordinal701>
extern __imp_wsock32_ordinal702:PANYARGS
wsock32_ordinal702 TEXTEQU <__imp_wsock32_ordinal702>
extern __imp_wsock32_ordinal703:PANYARGS
wsock32_ordinal703 TEXTEQU <__imp_wsock32_ordinal703>
extern __imp_wsock32_ordinal704:PANYARGS
wsock32_ordinal704 TEXTEQU <__imp_wsock32_ordinal704>
extern __imp_wsock32_ordinal705:PANYARGS
wsock32_ordinal705 TEXTEQU <__imp_wsock32_ordinal705>
extern __imp_wsock32_ordinal706:PANYARGS
wsock32_ordinal706 TEXTEQU <__imp_wsock32_ordinal706>
extern __imp_wsock32_ordinal707:PANYARGS
wsock32_ordinal707 TEXTEQU <__imp_wsock32_ordinal707>
extern __imp_wsock32_ordinal708:PANYARGS
wsock32_ordinal708 TEXTEQU <__imp_wsock32_ordinal708>
extern __imp_wsock32_ordinal709:PANYARGS
wsock32_ordinal709 TEXTEQU <__imp_wsock32_ordinal709>
extern __imp_wsock32_ordinal710:PANYARGS
wsock32_ordinal710 TEXTEQU <__imp_wsock32_ordinal710>
extern __imp_wsock32_ordinal711:PANYARGS
wsock32_ordinal711 TEXTEQU <__imp_wsock32_ordinal711>
extern __imp_wsock32_ordinal712:PANYARGS
wsock32_ordinal712 TEXTEQU <__imp_wsock32_ordinal712>
extern __imp_wsock32_ordinal713:PANYARGS
wsock32_ordinal713 TEXTEQU <__imp_wsock32_ordinal713>
extern __imp_wsock32_ordinal714:PANYARGS
wsock32_ordinal714 TEXTEQU <__imp_wsock32_ordinal714>
extern __imp_wsock32_ordinal715:PANYARGS
wsock32_ordinal715 TEXTEQU <__imp_wsock32_ordinal715>
extern __imp_wsock32_ordinal716:PANYARGS
wsock32_ordinal716 TEXTEQU <__imp_wsock32_ordinal716>
extern __imp_wsock32_ordinal717:PANYARGS
wsock32_ordinal717 TEXTEQU <__imp_wsock32_ordinal717>
extern __imp_wsock32_ordinal718:PANYARGS
wsock32_ordinal718 TEXTEQU <__imp_wsock32_ordinal718>
extern __imp_wsock32_ordinal719:PANYARGS
wsock32_ordinal719 TEXTEQU <__imp_wsock32_ordinal719>
extern __imp_wsock32_ordinal720:PANYARGS
wsock32_ordinal720 TEXTEQU <__imp_wsock32_ordinal720>
extern __imp_wsock32_ordinal721:PANYARGS
wsock32_ordinal721 TEXTEQU <__imp_wsock32_ordinal721>
extern __imp_wsock32_ordinal722:PANYARGS
wsock32_ordinal722 TEXTEQU <__imp_wsock32_ordinal722>
extern __imp_wsock32_ordinal723:PANYARGS
wsock32_ordinal723 TEXTEQU <__imp_wsock32_ordinal723>
extern __imp_wsock32_ordinal724:PANYARGS
wsock32_ordinal724 TEXTEQU <__imp_wsock32_ordinal724>
extern __imp_wsock32_ordinal725:PANYARGS
wsock32_ordinal725 TEXTEQU <__imp_wsock32_ordinal725>
extern __imp_wsock32_ordinal726:PANYARGS
wsock32_ordinal726 TEXTEQU <__imp_wsock32_ordinal726>
extern __imp_wsock32_ordinal727:PANYARGS
wsock32_ordinal727 TEXTEQU <__imp_wsock32_ordinal727>
extern __imp_wsock32_ordinal728:PANYARGS
wsock32_ordinal728 TEXTEQU <__imp_wsock32_ordinal728>
extern __imp_wsock32_ordinal729:PANYARGS
wsock32_ordinal729 TEXTEQU <__imp_wsock32_ordinal729>
extern __imp_wsock32_ordinal730:PANYARGS
wsock32_ordinal730 TEXTEQU <__imp_wsock32_ordinal730>
extern __imp_wsock32_ordinal731:PANYARGS
wsock32_ordinal731 TEXTEQU <__imp_wsock32_ordinal731>
extern __imp_wsock32_ordinal732:PANYARGS
wsock32_ordinal732 TEXTEQU <__imp_wsock32_ordinal732>
extern __imp_wsock32_ordinal733:PANYARGS
wsock32_ordinal733 TEXTEQU <__imp_wsock32_ordinal733>
extern __imp_wsock32_ordinal734:PANYARGS
wsock32_ordinal734 TEXTEQU <__imp_wsock32_ordinal734>
extern __imp_wsock32_ordinal735:PANYARGS
wsock32_ordinal735 TEXTEQU <__imp_wsock32_ordinal735>
extern __imp_wsock32_ordinal736:PANYARGS
wsock32_ordinal736 TEXTEQU <__imp_wsock32_ordinal736>
extern __imp_wsock32_ordinal737:PANYARGS
wsock32_ordinal737 TEXTEQU <__imp_wsock32_ordinal737>
extern __imp_wsock32_ordinal738:PANYARGS
wsock32_ordinal738 TEXTEQU <__imp_wsock32_ordinal738>
extern __imp_wsock32_ordinal739:PANYARGS
wsock32_ordinal739 TEXTEQU <__imp_wsock32_ordinal739>
extern __imp_wsock32_ordinal740:PANYARGS
wsock32_ordinal740 TEXTEQU <__imp_wsock32_ordinal740>
extern __imp_wsock32_ordinal741:PANYARGS
wsock32_ordinal741 TEXTEQU <__imp_wsock32_ordinal741>
extern __imp_wsock32_ordinal742:PANYARGS
wsock32_ordinal742 TEXTEQU <__imp_wsock32_ordinal742>
extern __imp_wsock32_ordinal743:PANYARGS
wsock32_ordinal743 TEXTEQU <__imp_wsock32_ordinal743>
extern __imp_wsock32_ordinal744:PANYARGS
wsock32_ordinal744 TEXTEQU <__imp_wsock32_ordinal744>
extern __imp_wsock32_ordinal745:PANYARGS
wsock32_ordinal745 TEXTEQU <__imp_wsock32_ordinal745>
extern __imp_wsock32_ordinal746:PANYARGS
wsock32_ordinal746 TEXTEQU <__imp_wsock32_ordinal746>
extern __imp_wsock32_ordinal747:PANYARGS
wsock32_ordinal747 TEXTEQU <__imp_wsock32_ordinal747>
extern __imp_wsock32_ordinal748:PANYARGS
wsock32_ordinal748 TEXTEQU <__imp_wsock32_ordinal748>
extern __imp_wsock32_ordinal749:PANYARGS
wsock32_ordinal749 TEXTEQU <__imp_wsock32_ordinal749>
extern __imp_wsock32_ordinal750:PANYARGS
wsock32_ordinal750 TEXTEQU <__imp_wsock32_ordinal750>
extern __imp_wsock32_ordinal751:PANYARGS
wsock32_ordinal751 TEXTEQU <__imp_wsock32_ordinal751>
extern __imp_wsock32_ordinal752:PANYARGS
wsock32_ordinal752 TEXTEQU <__imp_wsock32_ordinal752>
extern __imp_wsock32_ordinal753:PANYARGS
wsock32_ordinal753 TEXTEQU <__imp_wsock32_ordinal753>
extern __imp_wsock32_ordinal754:PANYARGS
wsock32_ordinal754 TEXTEQU <__imp_wsock32_ordinal754>
extern __imp_wsock32_ordinal755:PANYARGS
wsock32_ordinal755 TEXTEQU <__imp_wsock32_ordinal755>
extern __imp_wsock32_ordinal756:PANYARGS
wsock32_ordinal756 TEXTEQU <__imp_wsock32_ordinal756>
extern __imp_wsock32_ordinal757:PANYARGS
wsock32_ordinal757 TEXTEQU <__imp_wsock32_ordinal757>
extern __imp_wsock32_ordinal758:PANYARGS
wsock32_ordinal758 TEXTEQU <__imp_wsock32_ordinal758>
extern __imp_wsock32_ordinal759:PANYARGS
wsock32_ordinal759 TEXTEQU <__imp_wsock32_ordinal759>
extern __imp_wsock32_ordinal760:PANYARGS
wsock32_ordinal760 TEXTEQU <__imp_wsock32_ordinal760>
extern __imp_wsock32_ordinal761:PANYARGS
wsock32_ordinal761 TEXTEQU <__imp_wsock32_ordinal761>
extern __imp_wsock32_ordinal762:PANYARGS
wsock32_ordinal762 TEXTEQU <__imp_wsock32_ordinal762>
extern __imp_wsock32_ordinal763:PANYARGS
wsock32_ordinal763 TEXTEQU <__imp_wsock32_ordinal763>
extern __imp_wsock32_ordinal764:PANYARGS
wsock32_ordinal764 TEXTEQU <__imp_wsock32_ordinal764>
extern __imp_wsock32_ordinal765:PANYARGS
wsock32_ordinal765 TEXTEQU <__imp_wsock32_ordinal765>
extern __imp_wsock32_ordinal766:PANYARGS
wsock32_ordinal766 TEXTEQU <__imp_wsock32_ordinal766>
extern __imp_wsock32_ordinal767:PANYARGS
wsock32_ordinal767 TEXTEQU <__imp_wsock32_ordinal767>
extern __imp_wsock32_ordinal768:PANYARGS
wsock32_ordinal768 TEXTEQU <__imp_wsock32_ordinal768>
extern __imp_wsock32_ordinal769:PANYARGS
wsock32_ordinal769 TEXTEQU <__imp_wsock32_ordinal769>
extern __imp_wsock32_ordinal770:PANYARGS
wsock32_ordinal770 TEXTEQU <__imp_wsock32_ordinal770>
extern __imp_wsock32_ordinal771:PANYARGS
wsock32_ordinal771 TEXTEQU <__imp_wsock32_ordinal771>
extern __imp_wsock32_ordinal772:PANYARGS
wsock32_ordinal772 TEXTEQU <__imp_wsock32_ordinal772>
extern __imp_wsock32_ordinal773:PANYARGS
wsock32_ordinal773 TEXTEQU <__imp_wsock32_ordinal773>
extern __imp_wsock32_ordinal774:PANYARGS
wsock32_ordinal774 TEXTEQU <__imp_wsock32_ordinal774>
extern __imp_wsock32_ordinal775:PANYARGS
wsock32_ordinal775 TEXTEQU <__imp_wsock32_ordinal775>
extern __imp_wsock32_ordinal776:PANYARGS
wsock32_ordinal776 TEXTEQU <__imp_wsock32_ordinal776>
extern __imp_wsock32_ordinal777:PANYARGS
wsock32_ordinal777 TEXTEQU <__imp_wsock32_ordinal777>
extern __imp_wsock32_ordinal778:PANYARGS
wsock32_ordinal778 TEXTEQU <__imp_wsock32_ordinal778>
extern __imp_wsock32_ordinal779:PANYARGS
wsock32_ordinal779 TEXTEQU <__imp_wsock32_ordinal779>
extern __imp_wsock32_ordinal780:PANYARGS
wsock32_ordinal780 TEXTEQU <__imp_wsock32_ordinal780>
extern __imp_wsock32_ordinal781:PANYARGS
wsock32_ordinal781 TEXTEQU <__imp_wsock32_ordinal781>
extern __imp_wsock32_ordinal782:PANYARGS
wsock32_ordinal782 TEXTEQU <__imp_wsock32_ordinal782>
extern __imp_wsock32_ordinal783:PANYARGS
wsock32_ordinal783 TEXTEQU <__imp_wsock32_ordinal783>
extern __imp_wsock32_ordinal784:PANYARGS
wsock32_ordinal784 TEXTEQU <__imp_wsock32_ordinal784>
extern __imp_wsock32_ordinal785:PANYARGS
wsock32_ordinal785 TEXTEQU <__imp_wsock32_ordinal785>
extern __imp_wsock32_ordinal786:PANYARGS
wsock32_ordinal786 TEXTEQU <__imp_wsock32_ordinal786>
extern __imp_wsock32_ordinal787:PANYARGS
wsock32_ordinal787 TEXTEQU <__imp_wsock32_ordinal787>
extern __imp_wsock32_ordinal788:PANYARGS
wsock32_ordinal788 TEXTEQU <__imp_wsock32_ordinal788>
extern __imp_wsock32_ordinal789:PANYARGS
wsock32_ordinal789 TEXTEQU <__imp_wsock32_ordinal789>
extern __imp_wsock32_ordinal790:PANYARGS
wsock32_ordinal790 TEXTEQU <__imp_wsock32_ordinal790>
extern __imp_wsock32_ordinal791:PANYARGS
wsock32_ordinal791 TEXTEQU <__imp_wsock32_ordinal791>
extern __imp_wsock32_ordinal792:PANYARGS
wsock32_ordinal792 TEXTEQU <__imp_wsock32_ordinal792>
extern __imp_wsock32_ordinal793:PANYARGS
wsock32_ordinal793 TEXTEQU <__imp_wsock32_ordinal793>
extern __imp_wsock32_ordinal794:PANYARGS
wsock32_ordinal794 TEXTEQU <__imp_wsock32_ordinal794>
extern __imp_wsock32_ordinal795:PANYARGS
wsock32_ordinal795 TEXTEQU <__imp_wsock32_ordinal795>
extern __imp_wsock32_ordinal796:PANYARGS
wsock32_ordinal796 TEXTEQU <__imp_wsock32_ordinal796>
extern __imp_wsock32_ordinal797:PANYARGS
wsock32_ordinal797 TEXTEQU <__imp_wsock32_ordinal797>
extern __imp_wsock32_ordinal798:PANYARGS
wsock32_ordinal798 TEXTEQU <__imp_wsock32_ordinal798>
extern __imp_wsock32_ordinal799:PANYARGS
wsock32_ordinal799 TEXTEQU <__imp_wsock32_ordinal799>
extern __imp_wsock32_ordinal800:PANYARGS
wsock32_ordinal800 TEXTEQU <__imp_wsock32_ordinal800>
extern __imp_wsock32_ordinal801:PANYARGS
wsock32_ordinal801 TEXTEQU <__imp_wsock32_ordinal801>
extern __imp_wsock32_ordinal802:PANYARGS
wsock32_ordinal802 TEXTEQU <__imp_wsock32_ordinal802>
extern __imp_wsock32_ordinal803:PANYARGS
wsock32_ordinal803 TEXTEQU <__imp_wsock32_ordinal803>
extern __imp_wsock32_ordinal804:PANYARGS
wsock32_ordinal804 TEXTEQU <__imp_wsock32_ordinal804>
extern __imp_wsock32_ordinal805:PANYARGS
wsock32_ordinal805 TEXTEQU <__imp_wsock32_ordinal805>
extern __imp_wsock32_ordinal806:PANYARGS
wsock32_ordinal806 TEXTEQU <__imp_wsock32_ordinal806>
extern __imp_wsock32_ordinal807:PANYARGS
wsock32_ordinal807 TEXTEQU <__imp_wsock32_ordinal807>
extern __imp_wsock32_ordinal808:PANYARGS
wsock32_ordinal808 TEXTEQU <__imp_wsock32_ordinal808>
extern __imp_wsock32_ordinal809:PANYARGS
wsock32_ordinal809 TEXTEQU <__imp_wsock32_ordinal809>
extern __imp_wsock32_ordinal810:PANYARGS
wsock32_ordinal810 TEXTEQU <__imp_wsock32_ordinal810>
extern __imp_wsock32_ordinal811:PANYARGS
wsock32_ordinal811 TEXTEQU <__imp_wsock32_ordinal811>
extern __imp_wsock32_ordinal812:PANYARGS
wsock32_ordinal812 TEXTEQU <__imp_wsock32_ordinal812>
extern __imp_wsock32_ordinal813:PANYARGS
wsock32_ordinal813 TEXTEQU <__imp_wsock32_ordinal813>
extern __imp_wsock32_ordinal814:PANYARGS
wsock32_ordinal814 TEXTEQU <__imp_wsock32_ordinal814>
extern __imp_wsock32_ordinal815:PANYARGS
wsock32_ordinal815 TEXTEQU <__imp_wsock32_ordinal815>
extern __imp_wsock32_ordinal816:PANYARGS
wsock32_ordinal816 TEXTEQU <__imp_wsock32_ordinal816>
extern __imp_wsock32_ordinal817:PANYARGS
wsock32_ordinal817 TEXTEQU <__imp_wsock32_ordinal817>
extern __imp_wsock32_ordinal818:PANYARGS
wsock32_ordinal818 TEXTEQU <__imp_wsock32_ordinal818>
extern __imp_wsock32_ordinal819:PANYARGS
wsock32_ordinal819 TEXTEQU <__imp_wsock32_ordinal819>
extern __imp_wsock32_ordinal820:PANYARGS
wsock32_ordinal820 TEXTEQU <__imp_wsock32_ordinal820>
extern __imp_wsock32_ordinal821:PANYARGS
wsock32_ordinal821 TEXTEQU <__imp_wsock32_ordinal821>
extern __imp_wsock32_ordinal822:PANYARGS
wsock32_ordinal822 TEXTEQU <__imp_wsock32_ordinal822>
extern __imp_wsock32_ordinal823:PANYARGS
wsock32_ordinal823 TEXTEQU <__imp_wsock32_ordinal823>
extern __imp_wsock32_ordinal824:PANYARGS
wsock32_ordinal824 TEXTEQU <__imp_wsock32_ordinal824>
extern __imp_wsock32_ordinal825:PANYARGS
wsock32_ordinal825 TEXTEQU <__imp_wsock32_ordinal825>
extern __imp_wsock32_ordinal826:PANYARGS
wsock32_ordinal826 TEXTEQU <__imp_wsock32_ordinal826>
extern __imp_wsock32_ordinal827:PANYARGS
wsock32_ordinal827 TEXTEQU <__imp_wsock32_ordinal827>
extern __imp_wsock32_ordinal828:PANYARGS
wsock32_ordinal828 TEXTEQU <__imp_wsock32_ordinal828>
extern __imp_wsock32_ordinal829:PANYARGS
wsock32_ordinal829 TEXTEQU <__imp_wsock32_ordinal829>
extern __imp_wsock32_ordinal830:PANYARGS
wsock32_ordinal830 TEXTEQU <__imp_wsock32_ordinal830>
extern __imp_wsock32_ordinal831:PANYARGS
wsock32_ordinal831 TEXTEQU <__imp_wsock32_ordinal831>
extern __imp_wsock32_ordinal832:PANYARGS
wsock32_ordinal832 TEXTEQU <__imp_wsock32_ordinal832>
extern __imp_wsock32_ordinal833:PANYARGS
wsock32_ordinal833 TEXTEQU <__imp_wsock32_ordinal833>
extern __imp_wsock32_ordinal834:PANYARGS
wsock32_ordinal834 TEXTEQU <__imp_wsock32_ordinal834>
extern __imp_wsock32_ordinal835:PANYARGS
wsock32_ordinal835 TEXTEQU <__imp_wsock32_ordinal835>
extern __imp_wsock32_ordinal836:PANYARGS
wsock32_ordinal836 TEXTEQU <__imp_wsock32_ordinal836>
extern __imp_wsock32_ordinal837:PANYARGS
wsock32_ordinal837 TEXTEQU <__imp_wsock32_ordinal837>
extern __imp_wsock32_ordinal838:PANYARGS
wsock32_ordinal838 TEXTEQU <__imp_wsock32_ordinal838>
extern __imp_wsock32_ordinal839:PANYARGS
wsock32_ordinal839 TEXTEQU <__imp_wsock32_ordinal839>
extern __imp_wsock32_ordinal840:PANYARGS
wsock32_ordinal840 TEXTEQU <__imp_wsock32_ordinal840>
extern __imp_wsock32_ordinal841:PANYARGS
wsock32_ordinal841 TEXTEQU <__imp_wsock32_ordinal841>
extern __imp_wsock32_ordinal842:PANYARGS
wsock32_ordinal842 TEXTEQU <__imp_wsock32_ordinal842>
extern __imp_wsock32_ordinal843:PANYARGS
wsock32_ordinal843 TEXTEQU <__imp_wsock32_ordinal843>
extern __imp_wsock32_ordinal844:PANYARGS
wsock32_ordinal844 TEXTEQU <__imp_wsock32_ordinal844>
extern __imp_wsock32_ordinal845:PANYARGS
wsock32_ordinal845 TEXTEQU <__imp_wsock32_ordinal845>
extern __imp_wsock32_ordinal846:PANYARGS
wsock32_ordinal846 TEXTEQU <__imp_wsock32_ordinal846>
extern __imp_wsock32_ordinal847:PANYARGS
wsock32_ordinal847 TEXTEQU <__imp_wsock32_ordinal847>
extern __imp_wsock32_ordinal848:PANYARGS
wsock32_ordinal848 TEXTEQU <__imp_wsock32_ordinal848>
extern __imp_wsock32_ordinal849:PANYARGS
wsock32_ordinal849 TEXTEQU <__imp_wsock32_ordinal849>
extern __imp_wsock32_ordinal850:PANYARGS
wsock32_ordinal850 TEXTEQU <__imp_wsock32_ordinal850>
extern __imp_wsock32_ordinal851:PANYARGS
wsock32_ordinal851 TEXTEQU <__imp_wsock32_ordinal851>
extern __imp_wsock32_ordinal852:PANYARGS
wsock32_ordinal852 TEXTEQU <__imp_wsock32_ordinal852>
extern __imp_wsock32_ordinal853:PANYARGS
wsock32_ordinal853 TEXTEQU <__imp_wsock32_ordinal853>
extern __imp_wsock32_ordinal854:PANYARGS
wsock32_ordinal854 TEXTEQU <__imp_wsock32_ordinal854>
extern __imp_wsock32_ordinal855:PANYARGS
wsock32_ordinal855 TEXTEQU <__imp_wsock32_ordinal855>
extern __imp_wsock32_ordinal856:PANYARGS
wsock32_ordinal856 TEXTEQU <__imp_wsock32_ordinal856>
extern __imp_wsock32_ordinal857:PANYARGS
wsock32_ordinal857 TEXTEQU <__imp_wsock32_ordinal857>
extern __imp_wsock32_ordinal858:PANYARGS
wsock32_ordinal858 TEXTEQU <__imp_wsock32_ordinal858>
extern __imp_wsock32_ordinal859:PANYARGS
wsock32_ordinal859 TEXTEQU <__imp_wsock32_ordinal859>
extern __imp_wsock32_ordinal860:PANYARGS
wsock32_ordinal860 TEXTEQU <__imp_wsock32_ordinal860>
extern __imp_wsock32_ordinal861:PANYARGS
wsock32_ordinal861 TEXTEQU <__imp_wsock32_ordinal861>
extern __imp_wsock32_ordinal862:PANYARGS
wsock32_ordinal862 TEXTEQU <__imp_wsock32_ordinal862>
extern __imp_wsock32_ordinal863:PANYARGS
wsock32_ordinal863 TEXTEQU <__imp_wsock32_ordinal863>
extern __imp_wsock32_ordinal864:PANYARGS
wsock32_ordinal864 TEXTEQU <__imp_wsock32_ordinal864>
extern __imp_wsock32_ordinal865:PANYARGS
wsock32_ordinal865 TEXTEQU <__imp_wsock32_ordinal865>
extern __imp_wsock32_ordinal866:PANYARGS
wsock32_ordinal866 TEXTEQU <__imp_wsock32_ordinal866>
extern __imp_wsock32_ordinal867:PANYARGS
wsock32_ordinal867 TEXTEQU <__imp_wsock32_ordinal867>
extern __imp_wsock32_ordinal868:PANYARGS
wsock32_ordinal868 TEXTEQU <__imp_wsock32_ordinal868>
extern __imp_wsock32_ordinal869:PANYARGS
wsock32_ordinal869 TEXTEQU <__imp_wsock32_ordinal869>
extern __imp_wsock32_ordinal870:PANYARGS
wsock32_ordinal870 TEXTEQU <__imp_wsock32_ordinal870>
extern __imp_wsock32_ordinal871:PANYARGS
wsock32_ordinal871 TEXTEQU <__imp_wsock32_ordinal871>
extern __imp_wsock32_ordinal872:PANYARGS
wsock32_ordinal872 TEXTEQU <__imp_wsock32_ordinal872>
extern __imp_wsock32_ordinal873:PANYARGS
wsock32_ordinal873 TEXTEQU <__imp_wsock32_ordinal873>
extern __imp_wsock32_ordinal874:PANYARGS
wsock32_ordinal874 TEXTEQU <__imp_wsock32_ordinal874>
extern __imp_wsock32_ordinal875:PANYARGS
wsock32_ordinal875 TEXTEQU <__imp_wsock32_ordinal875>
extern __imp_wsock32_ordinal876:PANYARGS
wsock32_ordinal876 TEXTEQU <__imp_wsock32_ordinal876>
extern __imp_wsock32_ordinal877:PANYARGS
wsock32_ordinal877 TEXTEQU <__imp_wsock32_ordinal877>
extern __imp_wsock32_ordinal878:PANYARGS
wsock32_ordinal878 TEXTEQU <__imp_wsock32_ordinal878>
extern __imp_wsock32_ordinal879:PANYARGS
wsock32_ordinal879 TEXTEQU <__imp_wsock32_ordinal879>
extern __imp_wsock32_ordinal880:PANYARGS
wsock32_ordinal880 TEXTEQU <__imp_wsock32_ordinal880>
extern __imp_wsock32_ordinal881:PANYARGS
wsock32_ordinal881 TEXTEQU <__imp_wsock32_ordinal881>
extern __imp_wsock32_ordinal882:PANYARGS
wsock32_ordinal882 TEXTEQU <__imp_wsock32_ordinal882>
extern __imp_wsock32_ordinal883:PANYARGS
wsock32_ordinal883 TEXTEQU <__imp_wsock32_ordinal883>
extern __imp_wsock32_ordinal884:PANYARGS
wsock32_ordinal884 TEXTEQU <__imp_wsock32_ordinal884>
extern __imp_wsock32_ordinal885:PANYARGS
wsock32_ordinal885 TEXTEQU <__imp_wsock32_ordinal885>
extern __imp_wsock32_ordinal886:PANYARGS
wsock32_ordinal886 TEXTEQU <__imp_wsock32_ordinal886>
extern __imp_wsock32_ordinal887:PANYARGS
wsock32_ordinal887 TEXTEQU <__imp_wsock32_ordinal887>
extern __imp_wsock32_ordinal888:PANYARGS
wsock32_ordinal888 TEXTEQU <__imp_wsock32_ordinal888>
extern __imp_wsock32_ordinal889:PANYARGS
wsock32_ordinal889 TEXTEQU <__imp_wsock32_ordinal889>
extern __imp_wsock32_ordinal890:PANYARGS
wsock32_ordinal890 TEXTEQU <__imp_wsock32_ordinal890>
extern __imp_wsock32_ordinal891:PANYARGS
wsock32_ordinal891 TEXTEQU <__imp_wsock32_ordinal891>
extern __imp_wsock32_ordinal892:PANYARGS
wsock32_ordinal892 TEXTEQU <__imp_wsock32_ordinal892>
extern __imp_wsock32_ordinal893:PANYARGS
wsock32_ordinal893 TEXTEQU <__imp_wsock32_ordinal893>
extern __imp_wsock32_ordinal894:PANYARGS
wsock32_ordinal894 TEXTEQU <__imp_wsock32_ordinal894>
extern __imp_wsock32_ordinal895:PANYARGS
wsock32_ordinal895 TEXTEQU <__imp_wsock32_ordinal895>
extern __imp_wsock32_ordinal896:PANYARGS
wsock32_ordinal896 TEXTEQU <__imp_wsock32_ordinal896>
extern __imp_wsock32_ordinal897:PANYARGS
wsock32_ordinal897 TEXTEQU <__imp_wsock32_ordinal897>
extern __imp_wsock32_ordinal898:PANYARGS
wsock32_ordinal898 TEXTEQU <__imp_wsock32_ordinal898>
extern __imp_wsock32_ordinal899:PANYARGS
wsock32_ordinal899 TEXTEQU <__imp_wsock32_ordinal899>
extern __imp_wsock32_ordinal900:PANYARGS
wsock32_ordinal900 TEXTEQU <__imp_wsock32_ordinal900>
extern __imp_wsock32_ordinal901:PANYARGS
wsock32_ordinal901 TEXTEQU <__imp_wsock32_ordinal901>
extern __imp_wsock32_ordinal902:PANYARGS
wsock32_ordinal902 TEXTEQU <__imp_wsock32_ordinal902>
extern __imp_wsock32_ordinal903:PANYARGS
wsock32_ordinal903 TEXTEQU <__imp_wsock32_ordinal903>
extern __imp_wsock32_ordinal904:PANYARGS
wsock32_ordinal904 TEXTEQU <__imp_wsock32_ordinal904>
extern __imp_wsock32_ordinal905:PANYARGS
wsock32_ordinal905 TEXTEQU <__imp_wsock32_ordinal905>
extern __imp_wsock32_ordinal906:PANYARGS
wsock32_ordinal906 TEXTEQU <__imp_wsock32_ordinal906>
extern __imp_wsock32_ordinal907:PANYARGS
wsock32_ordinal907 TEXTEQU <__imp_wsock32_ordinal907>
extern __imp_wsock32_ordinal908:PANYARGS
wsock32_ordinal908 TEXTEQU <__imp_wsock32_ordinal908>
extern __imp_wsock32_ordinal909:PANYARGS
wsock32_ordinal909 TEXTEQU <__imp_wsock32_ordinal909>
extern __imp_wsock32_ordinal910:PANYARGS
wsock32_ordinal910 TEXTEQU <__imp_wsock32_ordinal910>
extern __imp_wsock32_ordinal911:PANYARGS
wsock32_ordinal911 TEXTEQU <__imp_wsock32_ordinal911>
extern __imp_wsock32_ordinal912:PANYARGS
wsock32_ordinal912 TEXTEQU <__imp_wsock32_ordinal912>
extern __imp_wsock32_ordinal913:PANYARGS
wsock32_ordinal913 TEXTEQU <__imp_wsock32_ordinal913>
extern __imp_wsock32_ordinal914:PANYARGS
wsock32_ordinal914 TEXTEQU <__imp_wsock32_ordinal914>
extern __imp_wsock32_ordinal915:PANYARGS
wsock32_ordinal915 TEXTEQU <__imp_wsock32_ordinal915>
extern __imp_wsock32_ordinal916:PANYARGS
wsock32_ordinal916 TEXTEQU <__imp_wsock32_ordinal916>
extern __imp_wsock32_ordinal917:PANYARGS
wsock32_ordinal917 TEXTEQU <__imp_wsock32_ordinal917>
extern __imp_wsock32_ordinal918:PANYARGS
wsock32_ordinal918 TEXTEQU <__imp_wsock32_ordinal918>
extern __imp_wsock32_ordinal919:PANYARGS
wsock32_ordinal919 TEXTEQU <__imp_wsock32_ordinal919>
extern __imp_wsock32_ordinal920:PANYARGS
wsock32_ordinal920 TEXTEQU <__imp_wsock32_ordinal920>
extern __imp_wsock32_ordinal921:PANYARGS
wsock32_ordinal921 TEXTEQU <__imp_wsock32_ordinal921>
extern __imp_wsock32_ordinal922:PANYARGS
wsock32_ordinal922 TEXTEQU <__imp_wsock32_ordinal922>
extern __imp_wsock32_ordinal923:PANYARGS
wsock32_ordinal923 TEXTEQU <__imp_wsock32_ordinal923>
extern __imp_wsock32_ordinal924:PANYARGS
wsock32_ordinal924 TEXTEQU <__imp_wsock32_ordinal924>
extern __imp_wsock32_ordinal925:PANYARGS
wsock32_ordinal925 TEXTEQU <__imp_wsock32_ordinal925>
extern __imp_wsock32_ordinal926:PANYARGS
wsock32_ordinal926 TEXTEQU <__imp_wsock32_ordinal926>
extern __imp_wsock32_ordinal927:PANYARGS
wsock32_ordinal927 TEXTEQU <__imp_wsock32_ordinal927>
extern __imp_wsock32_ordinal928:PANYARGS
wsock32_ordinal928 TEXTEQU <__imp_wsock32_ordinal928>
extern __imp_wsock32_ordinal929:PANYARGS
wsock32_ordinal929 TEXTEQU <__imp_wsock32_ordinal929>
extern __imp_wsock32_ordinal930:PANYARGS
wsock32_ordinal930 TEXTEQU <__imp_wsock32_ordinal930>
extern __imp_wsock32_ordinal931:PANYARGS
wsock32_ordinal931 TEXTEQU <__imp_wsock32_ordinal931>
extern __imp_wsock32_ordinal932:PANYARGS
wsock32_ordinal932 TEXTEQU <__imp_wsock32_ordinal932>
extern __imp_wsock32_ordinal933:PANYARGS
wsock32_ordinal933 TEXTEQU <__imp_wsock32_ordinal933>
extern __imp_wsock32_ordinal934:PANYARGS
wsock32_ordinal934 TEXTEQU <__imp_wsock32_ordinal934>
extern __imp_wsock32_ordinal935:PANYARGS
wsock32_ordinal935 TEXTEQU <__imp_wsock32_ordinal935>
extern __imp_wsock32_ordinal936:PANYARGS
wsock32_ordinal936 TEXTEQU <__imp_wsock32_ordinal936>
extern __imp_wsock32_ordinal937:PANYARGS
wsock32_ordinal937 TEXTEQU <__imp_wsock32_ordinal937>
extern __imp_wsock32_ordinal938:PANYARGS
wsock32_ordinal938 TEXTEQU <__imp_wsock32_ordinal938>
extern __imp_wsock32_ordinal939:PANYARGS
wsock32_ordinal939 TEXTEQU <__imp_wsock32_ordinal939>
extern __imp_wsock32_ordinal940:PANYARGS
wsock32_ordinal940 TEXTEQU <__imp_wsock32_ordinal940>
extern __imp_wsock32_ordinal941:PANYARGS
wsock32_ordinal941 TEXTEQU <__imp_wsock32_ordinal941>
extern __imp_wsock32_ordinal942:PANYARGS
wsock32_ordinal942 TEXTEQU <__imp_wsock32_ordinal942>
extern __imp_wsock32_ordinal943:PANYARGS
wsock32_ordinal943 TEXTEQU <__imp_wsock32_ordinal943>
extern __imp_wsock32_ordinal944:PANYARGS
wsock32_ordinal944 TEXTEQU <__imp_wsock32_ordinal944>
extern __imp_wsock32_ordinal945:PANYARGS
wsock32_ordinal945 TEXTEQU <__imp_wsock32_ordinal945>
extern __imp_wsock32_ordinal946:PANYARGS
wsock32_ordinal946 TEXTEQU <__imp_wsock32_ordinal946>
extern __imp_wsock32_ordinal947:PANYARGS
wsock32_ordinal947 TEXTEQU <__imp_wsock32_ordinal947>
extern __imp_wsock32_ordinal948:PANYARGS
wsock32_ordinal948 TEXTEQU <__imp_wsock32_ordinal948>
extern __imp_wsock32_ordinal949:PANYARGS
wsock32_ordinal949 TEXTEQU <__imp_wsock32_ordinal949>
extern __imp_wsock32_ordinal950:PANYARGS
wsock32_ordinal950 TEXTEQU <__imp_wsock32_ordinal950>
extern __imp_wsock32_ordinal951:PANYARGS
wsock32_ordinal951 TEXTEQU <__imp_wsock32_ordinal951>
extern __imp_wsock32_ordinal952:PANYARGS
wsock32_ordinal952 TEXTEQU <__imp_wsock32_ordinal952>
extern __imp_wsock32_ordinal953:PANYARGS
wsock32_ordinal953 TEXTEQU <__imp_wsock32_ordinal953>
extern __imp_wsock32_ordinal954:PANYARGS
wsock32_ordinal954 TEXTEQU <__imp_wsock32_ordinal954>
extern __imp_wsock32_ordinal955:PANYARGS
wsock32_ordinal955 TEXTEQU <__imp_wsock32_ordinal955>
extern __imp_wsock32_ordinal956:PANYARGS
wsock32_ordinal956 TEXTEQU <__imp_wsock32_ordinal956>
extern __imp_wsock32_ordinal957:PANYARGS
wsock32_ordinal957 TEXTEQU <__imp_wsock32_ordinal957>
extern __imp_wsock32_ordinal958:PANYARGS
wsock32_ordinal958 TEXTEQU <__imp_wsock32_ordinal958>
extern __imp_wsock32_ordinal959:PANYARGS
wsock32_ordinal959 TEXTEQU <__imp_wsock32_ordinal959>
extern __imp_wsock32_ordinal960:PANYARGS
wsock32_ordinal960 TEXTEQU <__imp_wsock32_ordinal960>
extern __imp_wsock32_ordinal961:PANYARGS
wsock32_ordinal961 TEXTEQU <__imp_wsock32_ordinal961>
extern __imp_wsock32_ordinal962:PANYARGS
wsock32_ordinal962 TEXTEQU <__imp_wsock32_ordinal962>
extern __imp_wsock32_ordinal963:PANYARGS
wsock32_ordinal963 TEXTEQU <__imp_wsock32_ordinal963>
extern __imp_wsock32_ordinal964:PANYARGS
wsock32_ordinal964 TEXTEQU <__imp_wsock32_ordinal964>
extern __imp_wsock32_ordinal965:PANYARGS
wsock32_ordinal965 TEXTEQU <__imp_wsock32_ordinal965>
extern __imp_wsock32_ordinal966:PANYARGS
wsock32_ordinal966 TEXTEQU <__imp_wsock32_ordinal966>
extern __imp_wsock32_ordinal967:PANYARGS
wsock32_ordinal967 TEXTEQU <__imp_wsock32_ordinal967>
extern __imp_wsock32_ordinal968:PANYARGS
wsock32_ordinal968 TEXTEQU <__imp_wsock32_ordinal968>
extern __imp_wsock32_ordinal969:PANYARGS
wsock32_ordinal969 TEXTEQU <__imp_wsock32_ordinal969>
extern __imp_wsock32_ordinal970:PANYARGS
wsock32_ordinal970 TEXTEQU <__imp_wsock32_ordinal970>
extern __imp_wsock32_ordinal971:PANYARGS
wsock32_ordinal971 TEXTEQU <__imp_wsock32_ordinal971>
extern __imp_wsock32_ordinal972:PANYARGS
wsock32_ordinal972 TEXTEQU <__imp_wsock32_ordinal972>
extern __imp_wsock32_ordinal973:PANYARGS
wsock32_ordinal973 TEXTEQU <__imp_wsock32_ordinal973>
extern __imp_wsock32_ordinal974:PANYARGS
wsock32_ordinal974 TEXTEQU <__imp_wsock32_ordinal974>
extern __imp_wsock32_ordinal975:PANYARGS
wsock32_ordinal975 TEXTEQU <__imp_wsock32_ordinal975>
extern __imp_wsock32_ordinal976:PANYARGS
wsock32_ordinal976 TEXTEQU <__imp_wsock32_ordinal976>
extern __imp_wsock32_ordinal977:PANYARGS
wsock32_ordinal977 TEXTEQU <__imp_wsock32_ordinal977>
extern __imp_wsock32_ordinal978:PANYARGS
wsock32_ordinal978 TEXTEQU <__imp_wsock32_ordinal978>
extern __imp_wsock32_ordinal979:PANYARGS
wsock32_ordinal979 TEXTEQU <__imp_wsock32_ordinal979>
extern __imp_wsock32_ordinal980:PANYARGS
wsock32_ordinal980 TEXTEQU <__imp_wsock32_ordinal980>
extern __imp_wsock32_ordinal981:PANYARGS
wsock32_ordinal981 TEXTEQU <__imp_wsock32_ordinal981>
extern __imp_wsock32_ordinal982:PANYARGS
wsock32_ordinal982 TEXTEQU <__imp_wsock32_ordinal982>
extern __imp_wsock32_ordinal983:PANYARGS
wsock32_ordinal983 TEXTEQU <__imp_wsock32_ordinal983>
extern __imp_wsock32_ordinal984:PANYARGS
wsock32_ordinal984 TEXTEQU <__imp_wsock32_ordinal984>
extern __imp_wsock32_ordinal985:PANYARGS
wsock32_ordinal985 TEXTEQU <__imp_wsock32_ordinal985>
extern __imp_wsock32_ordinal986:PANYARGS
wsock32_ordinal986 TEXTEQU <__imp_wsock32_ordinal986>
extern __imp_wsock32_ordinal987:PANYARGS
wsock32_ordinal987 TEXTEQU <__imp_wsock32_ordinal987>
extern __imp_wsock32_ordinal988:PANYARGS
wsock32_ordinal988 TEXTEQU <__imp_wsock32_ordinal988>
extern __imp_wsock32_ordinal989:PANYARGS
wsock32_ordinal989 TEXTEQU <__imp_wsock32_ordinal989>
extern __imp_wsock32_ordinal990:PANYARGS
wsock32_ordinal990 TEXTEQU <__imp_wsock32_ordinal990>
extern __imp_wsock32_ordinal991:PANYARGS
wsock32_ordinal991 TEXTEQU <__imp_wsock32_ordinal991>
extern __imp_wsock32_ordinal992:PANYARGS
wsock32_ordinal992 TEXTEQU <__imp_wsock32_ordinal992>
extern __imp_wsock32_ordinal993:PANYARGS
wsock32_ordinal993 TEXTEQU <__imp_wsock32_ordinal993>
extern __imp_wsock32_ordinal994:PANYARGS
wsock32_ordinal994 TEXTEQU <__imp_wsock32_ordinal994>
extern __imp_wsock32_ordinal995:PANYARGS
wsock32_ordinal995 TEXTEQU <__imp_wsock32_ordinal995>
extern __imp_wsock32_ordinal996:PANYARGS
wsock32_ordinal996 TEXTEQU <__imp_wsock32_ordinal996>
extern __imp_wsock32_ordinal997:PANYARGS
wsock32_ordinal997 TEXTEQU <__imp_wsock32_ordinal997>
extern __imp_wsock32_ordinal998:PANYARGS
wsock32_ordinal998 TEXTEQU <__imp_wsock32_ordinal998>
extern __imp_wsock32_ordinal999:PANYARGS
wsock32_ordinal999 TEXTEQU <__imp_wsock32_ordinal999>
extern __imp_WSApSetPostRoutine:PANYARGS
WSApSetPostRoutine TEXTEQU <__imp_WSApSetPostRoutine>
extern __imp_wsock32_ordinal1001:PANYARGS
wsock32_ordinal1001 TEXTEQU <__imp_wsock32_ordinal1001>
extern __imp_wsock32_ordinal1002:PANYARGS
wsock32_ordinal1002 TEXTEQU <__imp_wsock32_ordinal1002>
extern __imp_wsock32_ordinal1003:PANYARGS
wsock32_ordinal1003 TEXTEQU <__imp_wsock32_ordinal1003>
extern __imp_wsock32_ordinal1004:PANYARGS
wsock32_ordinal1004 TEXTEQU <__imp_wsock32_ordinal1004>
extern __imp_wsock32_ordinal1005:PANYARGS
wsock32_ordinal1005 TEXTEQU <__imp_wsock32_ordinal1005>
extern __imp_wsock32_ordinal1006:PANYARGS
wsock32_ordinal1006 TEXTEQU <__imp_wsock32_ordinal1006>
extern __imp_wsock32_ordinal1007:PANYARGS
wsock32_ordinal1007 TEXTEQU <__imp_wsock32_ordinal1007>
extern __imp_wsock32_ordinal1008:PANYARGS
wsock32_ordinal1008 TEXTEQU <__imp_wsock32_ordinal1008>
extern __imp_wsock32_ordinal1009:PANYARGS
wsock32_ordinal1009 TEXTEQU <__imp_wsock32_ordinal1009>
extern __imp_wsock32_ordinal1010:PANYARGS
wsock32_ordinal1010 TEXTEQU <__imp_wsock32_ordinal1010>
extern __imp_wsock32_ordinal1011:PANYARGS
wsock32_ordinal1011 TEXTEQU <__imp_wsock32_ordinal1011>
extern __imp_wsock32_ordinal1012:PANYARGS
wsock32_ordinal1012 TEXTEQU <__imp_wsock32_ordinal1012>
extern __imp_wsock32_ordinal1013:PANYARGS
wsock32_ordinal1013 TEXTEQU <__imp_wsock32_ordinal1013>
extern __imp_wsock32_ordinal1014:PANYARGS
wsock32_ordinal1014 TEXTEQU <__imp_wsock32_ordinal1014>
extern __imp_wsock32_ordinal1015:PANYARGS
wsock32_ordinal1015 TEXTEQU <__imp_wsock32_ordinal1015>
extern __imp_wsock32_ordinal1016:PANYARGS
wsock32_ordinal1016 TEXTEQU <__imp_wsock32_ordinal1016>
extern __imp_wsock32_ordinal1017:PANYARGS
wsock32_ordinal1017 TEXTEQU <__imp_wsock32_ordinal1017>
extern __imp_wsock32_ordinal1018:PANYARGS
wsock32_ordinal1018 TEXTEQU <__imp_wsock32_ordinal1018>
extern __imp_wsock32_ordinal1019:PANYARGS
wsock32_ordinal1019 TEXTEQU <__imp_wsock32_ordinal1019>
extern __imp_wsock32_ordinal1020:PANYARGS
wsock32_ordinal1020 TEXTEQU <__imp_wsock32_ordinal1020>
extern __imp_wsock32_ordinal1021:PANYARGS
wsock32_ordinal1021 TEXTEQU <__imp_wsock32_ordinal1021>
extern __imp_wsock32_ordinal1022:PANYARGS
wsock32_ordinal1022 TEXTEQU <__imp_wsock32_ordinal1022>
extern __imp_wsock32_ordinal1023:PANYARGS
wsock32_ordinal1023 TEXTEQU <__imp_wsock32_ordinal1023>
extern __imp_wsock32_ordinal1024:PANYARGS
wsock32_ordinal1024 TEXTEQU <__imp_wsock32_ordinal1024>
extern __imp_wsock32_ordinal1025:PANYARGS
wsock32_ordinal1025 TEXTEQU <__imp_wsock32_ordinal1025>
extern __imp_wsock32_ordinal1026:PANYARGS
wsock32_ordinal1026 TEXTEQU <__imp_wsock32_ordinal1026>
extern __imp_wsock32_ordinal1027:PANYARGS
wsock32_ordinal1027 TEXTEQU <__imp_wsock32_ordinal1027>
extern __imp_wsock32_ordinal1028:PANYARGS
wsock32_ordinal1028 TEXTEQU <__imp_wsock32_ordinal1028>
extern __imp_wsock32_ordinal1029:PANYARGS
wsock32_ordinal1029 TEXTEQU <__imp_wsock32_ordinal1029>
extern __imp_wsock32_ordinal1030:PANYARGS
wsock32_ordinal1030 TEXTEQU <__imp_wsock32_ordinal1030>
extern __imp_wsock32_ordinal1031:PANYARGS
wsock32_ordinal1031 TEXTEQU <__imp_wsock32_ordinal1031>
extern __imp_wsock32_ordinal1032:PANYARGS
wsock32_ordinal1032 TEXTEQU <__imp_wsock32_ordinal1032>
extern __imp_wsock32_ordinal1033:PANYARGS
wsock32_ordinal1033 TEXTEQU <__imp_wsock32_ordinal1033>
extern __imp_wsock32_ordinal1034:PANYARGS
wsock32_ordinal1034 TEXTEQU <__imp_wsock32_ordinal1034>
extern __imp_wsock32_ordinal1035:PANYARGS
wsock32_ordinal1035 TEXTEQU <__imp_wsock32_ordinal1035>
extern __imp_wsock32_ordinal1036:PANYARGS
wsock32_ordinal1036 TEXTEQU <__imp_wsock32_ordinal1036>
extern __imp_wsock32_ordinal1037:PANYARGS
wsock32_ordinal1037 TEXTEQU <__imp_wsock32_ordinal1037>
extern __imp_wsock32_ordinal1038:PANYARGS
wsock32_ordinal1038 TEXTEQU <__imp_wsock32_ordinal1038>
extern __imp_wsock32_ordinal1039:PANYARGS
wsock32_ordinal1039 TEXTEQU <__imp_wsock32_ordinal1039>
extern __imp_wsock32_ordinal1040:PANYARGS
wsock32_ordinal1040 TEXTEQU <__imp_wsock32_ordinal1040>
extern __imp_wsock32_ordinal1041:PANYARGS
wsock32_ordinal1041 TEXTEQU <__imp_wsock32_ordinal1041>
extern __imp_wsock32_ordinal1042:PANYARGS
wsock32_ordinal1042 TEXTEQU <__imp_wsock32_ordinal1042>
extern __imp_wsock32_ordinal1043:PANYARGS
wsock32_ordinal1043 TEXTEQU <__imp_wsock32_ordinal1043>
extern __imp_wsock32_ordinal1044:PANYARGS
wsock32_ordinal1044 TEXTEQU <__imp_wsock32_ordinal1044>
extern __imp_wsock32_ordinal1045:PANYARGS
wsock32_ordinal1045 TEXTEQU <__imp_wsock32_ordinal1045>
extern __imp_wsock32_ordinal1046:PANYARGS
wsock32_ordinal1046 TEXTEQU <__imp_wsock32_ordinal1046>
extern __imp_wsock32_ordinal1047:PANYARGS
wsock32_ordinal1047 TEXTEQU <__imp_wsock32_ordinal1047>
extern __imp_wsock32_ordinal1048:PANYARGS
wsock32_ordinal1048 TEXTEQU <__imp_wsock32_ordinal1048>
extern __imp_wsock32_ordinal1049:PANYARGS
wsock32_ordinal1049 TEXTEQU <__imp_wsock32_ordinal1049>
extern __imp_wsock32_ordinal1050:PANYARGS
wsock32_ordinal1050 TEXTEQU <__imp_wsock32_ordinal1050>
extern __imp_wsock32_ordinal1051:PANYARGS
wsock32_ordinal1051 TEXTEQU <__imp_wsock32_ordinal1051>
extern __imp_wsock32_ordinal1052:PANYARGS
wsock32_ordinal1052 TEXTEQU <__imp_wsock32_ordinal1052>
extern __imp_wsock32_ordinal1053:PANYARGS
wsock32_ordinal1053 TEXTEQU <__imp_wsock32_ordinal1053>
extern __imp_wsock32_ordinal1054:PANYARGS
wsock32_ordinal1054 TEXTEQU <__imp_wsock32_ordinal1054>
extern __imp_wsock32_ordinal1055:PANYARGS
wsock32_ordinal1055 TEXTEQU <__imp_wsock32_ordinal1055>
extern __imp_wsock32_ordinal1056:PANYARGS
wsock32_ordinal1056 TEXTEQU <__imp_wsock32_ordinal1056>
extern __imp_wsock32_ordinal1057:PANYARGS
wsock32_ordinal1057 TEXTEQU <__imp_wsock32_ordinal1057>
extern __imp_wsock32_ordinal1058:PANYARGS
wsock32_ordinal1058 TEXTEQU <__imp_wsock32_ordinal1058>
extern __imp_wsock32_ordinal1059:PANYARGS
wsock32_ordinal1059 TEXTEQU <__imp_wsock32_ordinal1059>
extern __imp_wsock32_ordinal1060:PANYARGS
wsock32_ordinal1060 TEXTEQU <__imp_wsock32_ordinal1060>
extern __imp_wsock32_ordinal1061:PANYARGS
wsock32_ordinal1061 TEXTEQU <__imp_wsock32_ordinal1061>
extern __imp_wsock32_ordinal1062:PANYARGS
wsock32_ordinal1062 TEXTEQU <__imp_wsock32_ordinal1062>
extern __imp_wsock32_ordinal1063:PANYARGS
wsock32_ordinal1063 TEXTEQU <__imp_wsock32_ordinal1063>
extern __imp_wsock32_ordinal1064:PANYARGS
wsock32_ordinal1064 TEXTEQU <__imp_wsock32_ordinal1064>
extern __imp_wsock32_ordinal1065:PANYARGS
wsock32_ordinal1065 TEXTEQU <__imp_wsock32_ordinal1065>
extern __imp_wsock32_ordinal1066:PANYARGS
wsock32_ordinal1066 TEXTEQU <__imp_wsock32_ordinal1066>
extern __imp_wsock32_ordinal1067:PANYARGS
wsock32_ordinal1067 TEXTEQU <__imp_wsock32_ordinal1067>
extern __imp_wsock32_ordinal1068:PANYARGS
wsock32_ordinal1068 TEXTEQU <__imp_wsock32_ordinal1068>
extern __imp_wsock32_ordinal1069:PANYARGS
wsock32_ordinal1069 TEXTEQU <__imp_wsock32_ordinal1069>
extern __imp_wsock32_ordinal1070:PANYARGS
wsock32_ordinal1070 TEXTEQU <__imp_wsock32_ordinal1070>
extern __imp_wsock32_ordinal1071:PANYARGS
wsock32_ordinal1071 TEXTEQU <__imp_wsock32_ordinal1071>
extern __imp_wsock32_ordinal1072:PANYARGS
wsock32_ordinal1072 TEXTEQU <__imp_wsock32_ordinal1072>
extern __imp_wsock32_ordinal1073:PANYARGS
wsock32_ordinal1073 TEXTEQU <__imp_wsock32_ordinal1073>
extern __imp_wsock32_ordinal1074:PANYARGS
wsock32_ordinal1074 TEXTEQU <__imp_wsock32_ordinal1074>
extern __imp_wsock32_ordinal1075:PANYARGS
wsock32_ordinal1075 TEXTEQU <__imp_wsock32_ordinal1075>
extern __imp_wsock32_ordinal1076:PANYARGS
wsock32_ordinal1076 TEXTEQU <__imp_wsock32_ordinal1076>
extern __imp_wsock32_ordinal1077:PANYARGS
wsock32_ordinal1077 TEXTEQU <__imp_wsock32_ordinal1077>
extern __imp_wsock32_ordinal1078:PANYARGS
wsock32_ordinal1078 TEXTEQU <__imp_wsock32_ordinal1078>
extern __imp_wsock32_ordinal1079:PANYARGS
wsock32_ordinal1079 TEXTEQU <__imp_wsock32_ordinal1079>
extern __imp_wsock32_ordinal1080:PANYARGS
wsock32_ordinal1080 TEXTEQU <__imp_wsock32_ordinal1080>
extern __imp_wsock32_ordinal1081:PANYARGS
wsock32_ordinal1081 TEXTEQU <__imp_wsock32_ordinal1081>
extern __imp_wsock32_ordinal1082:PANYARGS
wsock32_ordinal1082 TEXTEQU <__imp_wsock32_ordinal1082>
extern __imp_wsock32_ordinal1083:PANYARGS
wsock32_ordinal1083 TEXTEQU <__imp_wsock32_ordinal1083>
extern __imp_wsock32_ordinal1084:PANYARGS
wsock32_ordinal1084 TEXTEQU <__imp_wsock32_ordinal1084>
extern __imp_wsock32_ordinal1085:PANYARGS
wsock32_ordinal1085 TEXTEQU <__imp_wsock32_ordinal1085>
extern __imp_wsock32_ordinal1086:PANYARGS
wsock32_ordinal1086 TEXTEQU <__imp_wsock32_ordinal1086>
extern __imp_wsock32_ordinal1087:PANYARGS
wsock32_ordinal1087 TEXTEQU <__imp_wsock32_ordinal1087>
extern __imp_wsock32_ordinal1088:PANYARGS
wsock32_ordinal1088 TEXTEQU <__imp_wsock32_ordinal1088>
extern __imp_wsock32_ordinal1089:PANYARGS
wsock32_ordinal1089 TEXTEQU <__imp_wsock32_ordinal1089>
extern __imp_wsock32_ordinal1090:PANYARGS
wsock32_ordinal1090 TEXTEQU <__imp_wsock32_ordinal1090>
extern __imp_wsock32_ordinal1091:PANYARGS
wsock32_ordinal1091 TEXTEQU <__imp_wsock32_ordinal1091>
extern __imp_wsock32_ordinal1092:PANYARGS
wsock32_ordinal1092 TEXTEQU <__imp_wsock32_ordinal1092>
extern __imp_wsock32_ordinal1093:PANYARGS
wsock32_ordinal1093 TEXTEQU <__imp_wsock32_ordinal1093>
extern __imp_wsock32_ordinal1094:PANYARGS
wsock32_ordinal1094 TEXTEQU <__imp_wsock32_ordinal1094>
extern __imp_wsock32_ordinal1095:PANYARGS
wsock32_ordinal1095 TEXTEQU <__imp_wsock32_ordinal1095>
extern __imp_wsock32_ordinal1096:PANYARGS
wsock32_ordinal1096 TEXTEQU <__imp_wsock32_ordinal1096>
extern __imp_wsock32_ordinal1097:PANYARGS
wsock32_ordinal1097 TEXTEQU <__imp_wsock32_ordinal1097>
extern __imp_wsock32_ordinal1098:PANYARGS
wsock32_ordinal1098 TEXTEQU <__imp_wsock32_ordinal1098>
extern __imp_wsock32_ordinal1099:PANYARGS
wsock32_ordinal1099 TEXTEQU <__imp_wsock32_ordinal1099>
extern __imp_inet_network:PANYARGS
inet_network TEXTEQU <__imp_inet_network>
extern __imp_getnetbyname:PANYARGS
getnetbyname TEXTEQU <__imp_getnetbyname>
extern __imp_rcmd:PANYARGS
rcmd TEXTEQU <__imp_rcmd>
extern __imp_rexec:PANYARGS
rexec TEXTEQU <__imp_rexec>
extern __imp_rresvport:PANYARGS
rresvport TEXTEQU <__imp_rresvport>
extern __imp_sethostname:PANYARGS
sethostname TEXTEQU <__imp_sethostname>
extern __imp_dn_expand:PANYARGS
dn_expand TEXTEQU <__imp_dn_expand>
extern __imp_WSARecvEx:PANYARGS
WSARecvEx TEXTEQU <__imp_WSARecvEx>
extern __imp_s_perror:PANYARGS
s_perror TEXTEQU <__imp_s_perror>
extern __imp_GetAddressByNameA:PANYARGS
GetAddressByName  TEXTEQU <__imp_GetAddressByNameA>
extern __imp_GetAddressByNameW:PANYARGS
GetAddressByNameW TEXTEQU <__imp_GetAddressByNameW>
extern __imp_EnumProtocolsA:PANYARGS
EnumProtocols  TEXTEQU <__imp_EnumProtocolsA>
extern __imp_EnumProtocolsW:PANYARGS
EnumProtocolsW TEXTEQU <__imp_EnumProtocolsW>
extern __imp_GetTypeByNameA:PANYARGS
GetTypeByName  TEXTEQU <__imp_GetTypeByNameA>
extern __imp_GetTypeByNameW:PANYARGS
GetTypeByNameW TEXTEQU <__imp_GetTypeByNameW>
extern __imp_GetNameByTypeA:PANYARGS
GetNameByType  TEXTEQU <__imp_GetNameByTypeA>
extern __imp_GetNameByTypeW:PANYARGS
GetNameByTypeW TEXTEQU <__imp_GetNameByTypeW>
extern __imp_SetServiceA:PANYARGS
SetService  TEXTEQU <__imp_SetServiceA>
extern __imp_SetServiceW:PANYARGS
SetServiceW TEXTEQU <__imp_SetServiceW>
extern __imp_GetServiceA:PANYARGS
GetService  TEXTEQU <__imp_GetServiceA>
extern __imp_GetServiceW:PANYARGS
GetServiceW TEXTEQU <__imp_GetServiceW>
extern __imp_wsock32_ordinal1121:PANYARGS
wsock32_ordinal1121 TEXTEQU <__imp_wsock32_ordinal1121>
extern __imp_wsock32_ordinal1122:PANYARGS
wsock32_ordinal1122 TEXTEQU <__imp_wsock32_ordinal1122>
extern __imp_wsock32_ordinal1123:PANYARGS
wsock32_ordinal1123 TEXTEQU <__imp_wsock32_ordinal1123>
extern __imp_wsock32_ordinal1124:PANYARGS
wsock32_ordinal1124 TEXTEQU <__imp_wsock32_ordinal1124>
extern __imp_wsock32_ordinal1125:PANYARGS
wsock32_ordinal1125 TEXTEQU <__imp_wsock32_ordinal1125>
extern __imp_wsock32_ordinal1126:PANYARGS
wsock32_ordinal1126 TEXTEQU <__imp_wsock32_ordinal1126>
extern __imp_wsock32_ordinal1127:PANYARGS
wsock32_ordinal1127 TEXTEQU <__imp_wsock32_ordinal1127>
extern __imp_wsock32_ordinal1128:PANYARGS
wsock32_ordinal1128 TEXTEQU <__imp_wsock32_ordinal1128>
extern __imp_wsock32_ordinal1129:PANYARGS
wsock32_ordinal1129 TEXTEQU <__imp_wsock32_ordinal1129>
extern __imp_NPLoadNameSpaces:PANYARGS
NPLoadNameSpaces TEXTEQU <__imp_NPLoadNameSpaces>
extern __imp_wsock32_ordinal1131:PANYARGS
wsock32_ordinal1131 TEXTEQU <__imp_wsock32_ordinal1131>
extern __imp_wsock32_ordinal1132:PANYARGS
wsock32_ordinal1132 TEXTEQU <__imp_wsock32_ordinal1132>
extern __imp_wsock32_ordinal1133:PANYARGS
wsock32_ordinal1133 TEXTEQU <__imp_wsock32_ordinal1133>
extern __imp_wsock32_ordinal1134:PANYARGS
wsock32_ordinal1134 TEXTEQU <__imp_wsock32_ordinal1134>
extern __imp_wsock32_ordinal1135:PANYARGS
wsock32_ordinal1135 TEXTEQU <__imp_wsock32_ordinal1135>
extern __imp_wsock32_ordinal1136:PANYARGS
wsock32_ordinal1136 TEXTEQU <__imp_wsock32_ordinal1136>
extern __imp_wsock32_ordinal1137:PANYARGS
wsock32_ordinal1137 TEXTEQU <__imp_wsock32_ordinal1137>
extern __imp_wsock32_ordinal1138:PANYARGS
wsock32_ordinal1138 TEXTEQU <__imp_wsock32_ordinal1138>
extern __imp_wsock32_ordinal1139:PANYARGS
wsock32_ordinal1139 TEXTEQU <__imp_wsock32_ordinal1139>
extern __imp_TransmitFile:PANYARGS
TransmitFile TEXTEQU <__imp_TransmitFile>
extern __imp_AcceptEx:PANYARGS
AcceptEx TEXTEQU <__imp_AcceptEx>
extern __imp_GetAcceptExSockaddrs:PANYARGS
GetAcceptExSockaddrs TEXTEQU <__imp_GetAcceptExSockaddrs>
