extern __imp_GetAUOptionsEx:PANYARGS
GetAUOptionsEx TEXTEQU <__imp_GetAUOptionsEx>
extern __imp_wuaueng_ordinal2:PANYARGS
wuaueng_ordinal2 TEXTEQU <__imp_wuaueng_ordinal2>
extern __imp_wuaueng_ordinal3:PANYARGS
wuaueng_ordinal3 TEXTEQU <__imp_wuaueng_ordinal3>
extern __imp_WUCheckForUpdatesAtShutdown:PANYARGS
WUCheckForUpdatesAtShutdown TEXTEQU <__imp_WUCheckForUpdatesAtShutdown>
extern __imp_WUAutoUpdateAtShutdown:PANYARGS
WUAutoUpdateAtShutdown TEXTEQU <__imp_WUAutoUpdateAtShutdown>
extern __imp_GeneralizeForImaging:PANYARGS
GeneralizeForImaging TEXTEQU <__imp_GeneralizeForImaging>
extern __imp_GetEngineStatusInfo:PANYARGS
GetEngineStatusInfo TEXTEQU <__imp_GetEngineStatusInfo>
extern __imp_RegisterServiceVersion:PANYARGS
RegisterServiceVersion TEXTEQU <__imp_RegisterServiceVersion>
extern __imp_ServiceHandler:PANYARGS
ServiceHandler TEXTEQU <__imp_ServiceHandler>
extern __imp_ServiceMain:PANYARGS
ServiceMain TEXTEQU <__imp_ServiceMain>
extern __imp_WUServiceMain:PANYARGS
WUServiceMain TEXTEQU <__imp_WUServiceMain>
extern __imp_DllInstall:PANYARGS
DllInstall TEXTEQU <__imp_DllInstall>
extern __imp_DllMain:PANYARGS
DllMain TEXTEQU <__imp_DllMain>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
