extern __imp_wucltui_ordinal5:PANYARGS
wucltui_ordinal5 TEXTEQU <__imp_wucltui_ordinal5>
extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
