extern __imp_XsCaptureParameters:PANYARGS
XsCaptureParameters TEXTEQU <__imp_XsCaptureParameters>
extern __imp_XsCheckSmbDescriptor:PANYARGS
XsCheckSmbDescriptor TEXTEQU <__imp_XsCheckSmbDescriptor>
extern __imp_XsConvertServerEnumBuffer:PANYARGS
XsConvertServerEnumBuffer TEXTEQU <__imp_XsConvertServerEnumBuffer>
extern __imp_XsDupStrToWStr:PANYARGS
XsDupStrToWStr TEXTEQU <__imp_XsDupStrToWStr>
extern __imp_XsDupWStrToStr:PANYARGS
XsDupWStrToStr TEXTEQU <__imp_XsDupWStrToStr>
extern __imp_XsI_NetNameCanonicalize:PANYARGS
XsI_NetNameCanonicalize TEXTEQU <__imp_XsI_NetNameCanonicalize>
extern __imp_XsI_NetNameCompare:PANYARGS
XsI_NetNameCompare TEXTEQU <__imp_XsI_NetNameCompare>
extern __imp_XsI_NetNameValidate:PANYARGS
XsI_NetNameValidate TEXTEQU <__imp_XsI_NetNameValidate>
extern __imp_XsI_NetPathCanonicalize:PANYARGS
XsI_NetPathCanonicalize TEXTEQU <__imp_XsI_NetPathCanonicalize>
extern __imp_XsI_NetPathCompare:PANYARGS
XsI_NetPathCompare TEXTEQU <__imp_XsI_NetPathCompare>
extern __imp_XsI_NetPathType:PANYARGS
XsI_NetPathType TEXTEQU <__imp_XsI_NetPathType>
extern __imp_XsNetAccessAdd:PANYARGS
XsNetAccessAdd TEXTEQU <__imp_XsNetAccessAdd>
extern __imp_XsNetAccessDel:PANYARGS
XsNetAccessDel TEXTEQU <__imp_XsNetAccessDel>
extern __imp_XsNetAccessEnum:PANYARGS
XsNetAccessEnum TEXTEQU <__imp_XsNetAccessEnum>
extern __imp_XsNetAccessGetInfo:PANYARGS
XsNetAccessGetInfo TEXTEQU <__imp_XsNetAccessGetInfo>
extern __imp_XsNetAccessGetUserPerms:PANYARGS
XsNetAccessGetUserPerms TEXTEQU <__imp_XsNetAccessGetUserPerms>
extern __imp_XsNetAccessSetInfo:PANYARGS
XsNetAccessSetInfo TEXTEQU <__imp_XsNetAccessSetInfo>
extern __imp_XsNetAccountDeltas:PANYARGS
XsNetAccountDeltas TEXTEQU <__imp_XsNetAccountDeltas>
extern __imp_XsNetAccountSync:PANYARGS
XsNetAccountSync TEXTEQU <__imp_XsNetAccountSync>
extern __imp_XsNetBuildGetInfo:PANYARGS
XsNetBuildGetInfo TEXTEQU <__imp_XsNetBuildGetInfo>
extern __imp_XsNetCharDevControl:PANYARGS
XsNetCharDevControl TEXTEQU <__imp_XsNetCharDevControl>
extern __imp_XsNetCharDevEnum:PANYARGS
XsNetCharDevEnum TEXTEQU <__imp_XsNetCharDevEnum>
extern __imp_XsNetCharDevGetInfo:PANYARGS
XsNetCharDevGetInfo TEXTEQU <__imp_XsNetCharDevGetInfo>
extern __imp_XsNetCharDevQEnum:PANYARGS
XsNetCharDevQEnum TEXTEQU <__imp_XsNetCharDevQEnum>
extern __imp_XsNetCharDevQGetInfo:PANYARGS
XsNetCharDevQGetInfo TEXTEQU <__imp_XsNetCharDevQGetInfo>
extern __imp_XsNetCharDevQPurge:PANYARGS
XsNetCharDevQPurge TEXTEQU <__imp_XsNetCharDevQPurge>
extern __imp_XsNetCharDevQPurgeSelf:PANYARGS
XsNetCharDevQPurgeSelf TEXTEQU <__imp_XsNetCharDevQPurgeSelf>
extern __imp_XsNetCharDevQSetInfo:PANYARGS
XsNetCharDevQSetInfo TEXTEQU <__imp_XsNetCharDevQSetInfo>
extern __imp_XsNetConnectionEnum:PANYARGS
XsNetConnectionEnum TEXTEQU <__imp_XsNetConnectionEnum>
extern __imp_XsNetFileClose2:PANYARGS
XsNetFileClose2 TEXTEQU <__imp_XsNetFileClose2>
extern __imp_XsNetFileEnum2:PANYARGS
XsNetFileEnum2 TEXTEQU <__imp_XsNetFileEnum2>
extern __imp_XsNetFileGetInfo2:PANYARGS
XsNetFileGetInfo2 TEXTEQU <__imp_XsNetFileGetInfo2>
extern __imp_XsNetGetDCName:PANYARGS
XsNetGetDCName TEXTEQU <__imp_XsNetGetDCName>
extern __imp_XsNetGroupAdd:PANYARGS
XsNetGroupAdd TEXTEQU <__imp_XsNetGroupAdd>
extern __imp_XsNetGroupAddUser:PANYARGS
XsNetGroupAddUser TEXTEQU <__imp_XsNetGroupAddUser>
extern __imp_XsNetGroupDel:PANYARGS
XsNetGroupDel TEXTEQU <__imp_XsNetGroupDel>
extern __imp_XsNetGroupDelUser:PANYARGS
XsNetGroupDelUser TEXTEQU <__imp_XsNetGroupDelUser>
extern __imp_XsNetGroupEnum:PANYARGS
XsNetGroupEnum TEXTEQU <__imp_XsNetGroupEnum>
extern __imp_XsNetGroupGetInfo:PANYARGS
XsNetGroupGetInfo TEXTEQU <__imp_XsNetGroupGetInfo>
extern __imp_XsNetGroupGetUsers:PANYARGS
XsNetGroupGetUsers TEXTEQU <__imp_XsNetGroupGetUsers>
extern __imp_XsNetGroupSetInfo:PANYARGS
XsNetGroupSetInfo TEXTEQU <__imp_XsNetGroupSetInfo>
extern __imp_XsNetGroupSetUsers:PANYARGS
XsNetGroupSetUsers TEXTEQU <__imp_XsNetGroupSetUsers>
extern __imp_XsNetLogonEnum:PANYARGS
XsNetLogonEnum TEXTEQU <__imp_XsNetLogonEnum>
extern __imp_XsNetMessageBufferSend:PANYARGS
XsNetMessageBufferSend TEXTEQU <__imp_XsNetMessageBufferSend>
extern __imp_XsNetMessageNameAdd:PANYARGS
XsNetMessageNameAdd TEXTEQU <__imp_XsNetMessageNameAdd>
extern __imp_XsNetMessageNameDel:PANYARGS
XsNetMessageNameDel TEXTEQU <__imp_XsNetMessageNameDel>
extern __imp_XsNetMessageNameEnum:PANYARGS
XsNetMessageNameEnum TEXTEQU <__imp_XsNetMessageNameEnum>
extern __imp_XsNetMessageNameGetInfo:PANYARGS
XsNetMessageNameGetInfo TEXTEQU <__imp_XsNetMessageNameGetInfo>
extern __imp_XsNetPrintDestAdd:PANYARGS
XsNetPrintDestAdd TEXTEQU <__imp_XsNetPrintDestAdd>
extern __imp_XsNetPrintDestControl:PANYARGS
XsNetPrintDestControl TEXTEQU <__imp_XsNetPrintDestControl>
extern __imp_XsNetPrintDestDel:PANYARGS
XsNetPrintDestDel TEXTEQU <__imp_XsNetPrintDestDel>
extern __imp_XsNetPrintDestEnum:PANYARGS
XsNetPrintDestEnum TEXTEQU <__imp_XsNetPrintDestEnum>
extern __imp_XsNetPrintDestGetInfo:PANYARGS
XsNetPrintDestGetInfo TEXTEQU <__imp_XsNetPrintDestGetInfo>
extern __imp_XsNetPrintDestSetInfo:PANYARGS
XsNetPrintDestSetInfo TEXTEQU <__imp_XsNetPrintDestSetInfo>
extern __imp_XsNetPrintJobContinue:PANYARGS
XsNetPrintJobContinue TEXTEQU <__imp_XsNetPrintJobContinue>
extern __imp_XsNetPrintJobDel:PANYARGS
XsNetPrintJobDel TEXTEQU <__imp_XsNetPrintJobDel>
extern __imp_XsNetPrintJobEnum:PANYARGS
XsNetPrintJobEnum TEXTEQU <__imp_XsNetPrintJobEnum>
extern __imp_XsNetPrintJobGetInfo:PANYARGS
XsNetPrintJobGetInfo TEXTEQU <__imp_XsNetPrintJobGetInfo>
extern __imp_XsNetPrintJobPause:PANYARGS
XsNetPrintJobPause TEXTEQU <__imp_XsNetPrintJobPause>
extern __imp_XsNetPrintJobSetInfo:PANYARGS
XsNetPrintJobSetInfo TEXTEQU <__imp_XsNetPrintJobSetInfo>
extern __imp_XsNetPrintQAdd:PANYARGS
XsNetPrintQAdd TEXTEQU <__imp_XsNetPrintQAdd>
extern __imp_XsNetPrintQContinue:PANYARGS
XsNetPrintQContinue TEXTEQU <__imp_XsNetPrintQContinue>
extern __imp_XsNetPrintQDel:PANYARGS
XsNetPrintQDel TEXTEQU <__imp_XsNetPrintQDel>
extern __imp_XsNetPrintQEnum:PANYARGS
XsNetPrintQEnum TEXTEQU <__imp_XsNetPrintQEnum>
extern __imp_XsNetPrintQGetInfo:PANYARGS
XsNetPrintQGetInfo TEXTEQU <__imp_XsNetPrintQGetInfo>
extern __imp_XsNetPrintQPause:PANYARGS
XsNetPrintQPause TEXTEQU <__imp_XsNetPrintQPause>
extern __imp_XsNetPrintQPurge:PANYARGS
XsNetPrintQPurge TEXTEQU <__imp_XsNetPrintQPurge>
extern __imp_XsNetPrintQSetInfo:PANYARGS
XsNetPrintQSetInfo TEXTEQU <__imp_XsNetPrintQSetInfo>
extern __imp_XsNetRemoteTOD:PANYARGS
XsNetRemoteTOD TEXTEQU <__imp_XsNetRemoteTOD>
extern __imp_XsNetServerAuthenticate:PANYARGS
XsNetServerAuthenticate TEXTEQU <__imp_XsNetServerAuthenticate>
extern __imp_XsNetServerDiskEnum:PANYARGS
XsNetServerDiskEnum TEXTEQU <__imp_XsNetServerDiskEnum>
extern __imp_XsNetServerEnum2:PANYARGS
XsNetServerEnum2 TEXTEQU <__imp_XsNetServerEnum2>
extern __imp_XsNetServerEnum3:PANYARGS
XsNetServerEnum3 TEXTEQU <__imp_XsNetServerEnum3>
extern __imp_XsNetServerGetInfo:PANYARGS
XsNetServerGetInfo TEXTEQU <__imp_XsNetServerGetInfo>
extern __imp_XsNetServerPasswordSet:PANYARGS
XsNetServerPasswordSet TEXTEQU <__imp_XsNetServerPasswordSet>
extern __imp_XsNetServerReqChallenge:PANYARGS
XsNetServerReqChallenge TEXTEQU <__imp_XsNetServerReqChallenge>
extern __imp_XsNetServerSetInfo:PANYARGS
XsNetServerSetInfo TEXTEQU <__imp_XsNetServerSetInfo>
extern __imp_XsNetServiceControl:PANYARGS
XsNetServiceControl TEXTEQU <__imp_XsNetServiceControl>
extern __imp_XsNetServiceEnum:PANYARGS
XsNetServiceEnum TEXTEQU <__imp_XsNetServiceEnum>
extern __imp_XsNetServiceGetInfo:PANYARGS
XsNetServiceGetInfo TEXTEQU <__imp_XsNetServiceGetInfo>
extern __imp_XsNetServiceInstall:PANYARGS
XsNetServiceInstall TEXTEQU <__imp_XsNetServiceInstall>
extern __imp_XsNetSessionDel:PANYARGS
XsNetSessionDel TEXTEQU <__imp_XsNetSessionDel>
extern __imp_XsNetSessionEnum:PANYARGS
XsNetSessionEnum TEXTEQU <__imp_XsNetSessionEnum>
extern __imp_XsNetSessionGetInfo:PANYARGS
XsNetSessionGetInfo TEXTEQU <__imp_XsNetSessionGetInfo>
extern __imp_XsNetShareAdd:PANYARGS
XsNetShareAdd TEXTEQU <__imp_XsNetShareAdd>
extern __imp_XsNetShareCheck:PANYARGS
XsNetShareCheck TEXTEQU <__imp_XsNetShareCheck>
extern __imp_XsNetShareDel:PANYARGS
XsNetShareDel TEXTEQU <__imp_XsNetShareDel>
extern __imp_XsNetShareEnum:PANYARGS
XsNetShareEnum TEXTEQU <__imp_XsNetShareEnum>
extern __imp_XsNetShareGetInfo:PANYARGS
XsNetShareGetInfo TEXTEQU <__imp_XsNetShareGetInfo>
extern __imp_XsNetShareSetInfo:PANYARGS
XsNetShareSetInfo TEXTEQU <__imp_XsNetShareSetInfo>
extern __imp_XsNetStatisticsGet2:PANYARGS
XsNetStatisticsGet2 TEXTEQU <__imp_XsNetStatisticsGet2>
extern __imp_XsNetUnsupportedApi:PANYARGS
XsNetUnsupportedApi TEXTEQU <__imp_XsNetUnsupportedApi>
extern __imp_XsNetUseAdd:PANYARGS
XsNetUseAdd TEXTEQU <__imp_XsNetUseAdd>
extern __imp_XsNetUseDel:PANYARGS
XsNetUseDel TEXTEQU <__imp_XsNetUseDel>
extern __imp_XsNetUseEnum:PANYARGS
XsNetUseEnum TEXTEQU <__imp_XsNetUseEnum>
extern __imp_XsNetUseGetInfo:PANYARGS
XsNetUseGetInfo TEXTEQU <__imp_XsNetUseGetInfo>
extern __imp_XsNetUserAdd2:PANYARGS
XsNetUserAdd2 TEXTEQU <__imp_XsNetUserAdd2>
extern __imp_XsNetUserDel:PANYARGS
XsNetUserDel TEXTEQU <__imp_XsNetUserDel>
extern __imp_XsNetUserEnum:PANYARGS
XsNetUserEnum TEXTEQU <__imp_XsNetUserEnum>
extern __imp_XsNetUserEnum2:PANYARGS
XsNetUserEnum2 TEXTEQU <__imp_XsNetUserEnum2>
extern __imp_XsNetUserGetGroups:PANYARGS
XsNetUserGetGroups TEXTEQU <__imp_XsNetUserGetGroups>
extern __imp_XsNetUserGetInfo:PANYARGS
XsNetUserGetInfo TEXTEQU <__imp_XsNetUserGetInfo>
extern __imp_XsNetUserModalsGet:PANYARGS
XsNetUserModalsGet TEXTEQU <__imp_XsNetUserModalsGet>
extern __imp_XsNetUserModalsSet:PANYARGS
XsNetUserModalsSet TEXTEQU <__imp_XsNetUserModalsSet>
extern __imp_XsNetUserPasswordSet2:PANYARGS
XsNetUserPasswordSet2 TEXTEQU <__imp_XsNetUserPasswordSet2>
extern __imp_XsNetUserSetGroups:PANYARGS
XsNetUserSetGroups TEXTEQU <__imp_XsNetUserSetGroups>
extern __imp_XsNetUserSetInfo:PANYARGS
XsNetUserSetInfo TEXTEQU <__imp_XsNetUserSetInfo>
extern __imp_XsNetUserSetInfo2:PANYARGS
XsNetUserSetInfo2 TEXTEQU <__imp_XsNetUserSetInfo2>
extern __imp_XsNetWkstaGetInfo:PANYARGS
XsNetWkstaGetInfo TEXTEQU <__imp_XsNetWkstaGetInfo>
extern __imp_XsNetWkstaSetInfo:PANYARGS
XsNetWkstaSetInfo TEXTEQU <__imp_XsNetWkstaSetInfo>
extern __imp_XsNetWkstaSetUID:PANYARGS
XsNetWkstaSetUID TEXTEQU <__imp_XsNetWkstaSetUID>
extern __imp_XsNetWkstaUserLogoff:PANYARGS
XsNetWkstaUserLogoff TEXTEQU <__imp_XsNetWkstaUserLogoff>
extern __imp_XsNetWkstaUserLogon:PANYARGS
XsNetWkstaUserLogon TEXTEQU <__imp_XsNetWkstaUserLogon>
extern __imp_XsSamOEMChangePasswordUser2_P:PANYARGS
XsSamOEMChangePasswordUser2_P TEXTEQU <__imp_XsSamOEMChangePasswordUser2_P>
extern __imp_XsSetParameters:PANYARGS
XsSetParameters TEXTEQU <__imp_XsSetParameters>
