extern __imp_DllCanUnloadNow:PANYARGS
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow>
extern __imp_DllGetClassObject:PANYARGS
DllGetClassObject TEXTEQU <__imp_DllGetClassObject>
extern __imp_DllRegisterServer:PANYARGS
DllRegisterServer TEXTEQU <__imp_DllRegisterServer>
extern __imp_DllUnregisterServer:PANYARGS
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer>
extern __imp_PIEnroll2GetNoCOM:PANYARGS
PIEnroll2GetNoCOM TEXTEQU <__imp_PIEnroll2GetNoCOM>
extern __imp_PIEnroll4GetNoCOM:PANYARGS
PIEnroll4GetNoCOM TEXTEQU <__imp_PIEnroll4GetNoCOM>
extern __imp_PIEnrollGetNoCOM:PANYARGS
PIEnrollGetNoCOM TEXTEQU <__imp_PIEnrollGetNoCOM>
